### ISSUE TITLE
Document how to configure and run integration tests with docker compose

### ISSUE THREAD

**Issue by zmckinnon** [dotnet/AspNetCore.Docs#10280]
There are great examples on how to run unit tests using docker (https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-unit-testing.md), but it'd be great for examples on how to use docker compose with external tools (like redis, sql server, dynamodb, etc.) to run integration tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zmckinnon ... Great idea, but it's highly unlikely that we'll have the cycles to handle creating such a topic. The community could offer to write such a topic, and we would consider linking our topic to a high quality blog post on the subject if available.

@Rick-Anderson Do you concur?
