### ISSUE TITLE
Docs and sample for combined OIDC and JWT authentication

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/AspNetCore.Docs#10444]
There don't seem to be any docs and samples that show how to combine Azure AD OIDC and JWT authentication in the same site. 

You can call `AddAzureAD()` and `AddAzureADBearer()`, but you have to deduce that on your own, and it's not clear if order matters. Then, once you have both, strategies for using Authorize on API controllers vs view controllers should be discussed. 

Current SPA guidance also discusses using cookie auth for API calls if the auth cookie is same-site. This should be in the docs too. 

It would probably be useful to consider both "standard" OIDC and JWT in addition to the AAD/B2C-specific versions.

**Comment by Rick-Anderson** [comment]
@blowdart 	please review.

**Comment by blowdart** [comment]
"Current SPA guidance also discusses using cookie auth for API calls if the auth cookie is same-site"

Which is frankly still controversial.

But as for using both Azure OIDC and JWT yea, but let's be clear, this is the AAD helpers, it's not a generic JWT and external auth topic.

We do take PRs Oren :p

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
