### ISSUE TITLE
Add link to Microsoft/ApplicationInsights-aspnetcore/wiki/Logging

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#10511]
Microsoft/ApplicationInsights-aspnetcore/wiki/Logging
part of #7316

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#third-party-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by jeremymeng** [comment]
I prefer the docs.microsoft.com as it's more centralized. However, we probably should consult the Application Insights team.

@xiaomi7732 could you please help find a proper contact for this documentation question?

**Comment by xiaomi7732** [comment]
@lmolkova Are you the right person to make the call?

**Comment by lmolkova** [comment]
we've recently changed approach for logging and after we ship a next stable version, the right way to use logging will be via Microsoft.Extensions.Logging.ApplicationInsights package. 

Here is a github issue to document it: https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/251

People with more context are @cijothomas   @RamjotSingh

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/ILogger/Readme.md
This is the new doc.
I have sought help from @mrbullwinkle to modify docs to reflect new changes
