### ISSUE TITLE
Link Documentation to Source Code

### ISSUE THREAD

**Issue by glatzert** [dotnet/AspNetCore.Docs#10535]
Sometimes during browsing the API-Reference on docs.microsoft.com (like this: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.internal.formfile.-ctor?view=aspnetcore-2.2), I'd like to know the _actual_ implementation of the method.

Please provide a link into the GitHub source code - or for namespaces at least the GitHub repository.

**Comment by svick** [comment]
I don't think this is specific to ASP.NET Core. The general request is at https://github.com/MicrosoftDocs/feedback/issues/433.

**Comment by Rick-Anderson** [comment]
@serpent5  reminder we like to link to GitHub source in the docs.
