### ISSUE TITLE
Link to a sample Web Application 

### ISSUE THREAD

**Issue by gvsrini** [dotnet/AspNetCore.Docs#10599]
Design looks good, but a sample working Web Application will help a long way in understanding the implementation aspects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb49e16-b543-30ae-88e5-2241836e2510
* Version Independent ID: d42b1eab-9682-ea69-f203-e519b456a56f
* Content: [ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/data-protection/introduction.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/introduction.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart can you provide a link to a sample app?

**Comment by blowdart** [comment]
Not really, it's all done by default. This isn't really meant as a topic for samples, but rather what you go to for reference. Data Protection is wired up automatically by aspnet
