### ISSUE TITLE
VS Mac 2017 - Unhandled Exception: Could not load type 'RazorPagesMovie.Pages.Movies.IndexModel'

### ISSUE THREAD

**Issue by budwalc** [dotnet/AspNetCore.Docs#10631]
Ran all steps, and I built the solution after the INITIAL MIGRATION.

When typing in "https://localhost:5001/Movies", I'm presented with an unhandled Exception page.

Any idea where I'm going wrong please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac#files-created)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by AlanPBourke** [comment]
VS Code Windows v1.33.1
dotnet core version 2.2.203

   [netcoreapp2.2]: 
   Top-level Package                                          Requested   Resolved
   > Microsoft.AspNetCore.App                           (A)   [2.2.0, )   2.2.0
   > Microsoft.AspNetCore.Razor.Design                        2.2.0       2.2.0
   > Microsoft.EntityFrameworkCore.Design                     2.2.4       2.2.4
   > Microsoft.EntityFrameworkCore.SQLite                     2.2.4       2.2.4
   > Microsoft.NETCore.App                              (A)   [2.2.0, )   2.2.0
   > Microsoft.VisualStudio.Web.CodeGeneration.Design         2.2.3       2.2.3

Getting this same issue. Have rebuilt, closed VS Code and retried, still getting it.

**Comment by AlanPBourke** [comment]
Further information:

If I run the app up using Ctrl-F5 as per the tutorial it fails as detailed above. If I issue `dotnet run` in the Terminal in VS Code, and then manually browse to the URL, it works.
