### ISSUE TITLE
Add non-server side build directions  to docs

### ISSUE THREAD

**Issue by atotalnoob** [dotnet/AspNetCore.Docs#10683]
There isn't anything for building a PROD build that isn't SSR. 

So if one needs to build and deploy their .net Core + Angular app, they would either have to do:

 ng serve --prod (which isn't a safe idea since it isn't a prod level web server) 
or build their Angular app as SSR. 

I want to do neither of those and just want to be able to have a prod build of angular built by the C# app. 
Basically, I want the c# app to run ng build --prod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio#publish-and-deploy)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by drdamour** [comment]
Yes please, 1 project 1 deploy all .net

**Comment by NevillePerkins** [comment]
Yes please. This would be most helpful.

**Comment by Rick-Anderson** [comment]
Move to Master issue: Use the Angular project template with ASP.NET Core #18074

**Comment by MackinnonBuck** [comment]
I'm not really sure what's left to document here. We have a "Publish and deploy" section, which links directly to https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/index.md. That document describes `dotnet publish`, which handles everything mentioned in this issue if I'm not mistaken. For example:

> Basically, I want the c# app to run ng build --prod

This is what `dotnet publish` will do under the hood for the Angular template.

The current "Publish and deploy" section states:

> In production, serve a version of your app that's optimized for performance. This is configured to happen automatically. When you publish, the build configuration emits a minified, ahead-of-time (AoT) compiled build of your client-side code. Unlike the development build, the production build doesn't require Node.js to be installed on the server (unless you have enabled server-side rendering (SSR)).

> You can use standard [ASP.NET Core hosting and deployment methods](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/index.md).

I wonder what's unclear about this? I see this issue has 4 upvotes so maybe there's a way this can be improved. Or, maybe we think this is sufficient and there isn't any remaining work to do here.

Thoughts? @guardrex @Rick-Anderson
