### ISSUE TITLE
ArgumentException: The 'ClientId' option must be provided

### ISSUE THREAD

**Issue by exportio** [dotnet/AspNetCore.Docs#10680]
Followed the steps, but when starting, I get "ArgumentException: The 'ClientId' option must be provided"

**You need to also do this:**

services.AddAuthentication().AddGoogle(googleOptions =>  
{  
    googleOptions.ClientId = Configuration["Authentication:Google:ClientId"];  
    googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];  
});

**Even with this update, after selecting the Google account on the login page, you get the following result after being redirected to https://localhost:44381/signin-google?.....**

HttpRequestException: An error occurred when retrieving Google user information (Forbidden). Please check if the authentication information is correct and the corresponding Google+ API is enabled.
Microsoft.AspNetCore.Authentication.Google.GoogleHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by guardrex** [comment]
Thanks for the report @samboustani ...

Applies to: https://docs.microsoft.com/aspnet/core/security/authentication/social/google-logins

Please open issues using the **Content feedback** button at the bottom of the topic. It tags the issue with metadata that helps us track the work.

This is a candidate to add to the tracking issue https://github.com/aspnet/Docs/issues/1470.

I'll add some notes here:

For local dev, the values come in via User Secrets, which is described in: https://docs.microsoft.com/aspnet/core/security/authentication/social/google-logins#store-google-clientid-and-clientsecret and in https://docs.microsoft.com/aspnet/core/security/authentication/social#use-secretmanager-to-store-tokens-assigned-by-login-providers

It's *lightly covered* by the section: https://docs.microsoft.com/aspnet/core/security/authentication/social/google-logins#multiple-authentication-providers

```csharp
.AddGoogle(googleOptions => { ... })
```

> See the GoogleOptions API reference for more information on configuration options supported by Google authentication. This can be used to request different information about the user.

With "GoogleOptions" linked to https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.builder.googleoptions

... that includes `ClientID` and `ClientSecret`, so the topic assumes that the reader will holdover their knowledge from the User Secrets section when they look at the options and figure out that the Client ID and Secret should be set into configuration *in some way*.



... so, yes, it's **_not very specific_** about the minimum settings and focusing on `ClientID` and `ClientSecret`.

**Comment by serpent5** [comment]
There's nothing to address in the docs here. The advice above about configuring user secrets and should help anyone with this particular issue.
