### ISSUE TITLE
Troubleshoot Blazor topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#10746]
From @guardrex at [Troubleshoot Blazor topic](https://github.com/aspnet/Blazor.Docs/issues/4) ...

Title: *Troubleshoot Blazor*
UID: blazor/troubleshoot

**Comment by guardrex** [comment]
From @mrlife at https://github.com/dotnet/AspNetCore.Docs/issues/17071 ...

Using a razor component, the following error showed up in the console:

>  Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 

After looking through the documentation, I didn't find anything about adding "DetailedErrors" to `appsettings.Development.json".

I added the following, which works great after an app restart.

`"DetailedErrors": true`

Since a razor component error is suggesting this, can this be added to this docs page or another more appropriate one, which this docs page links to?

**Comment by guardrex** [comment]
@danroth27 @mkArtakMSFT ... We've had this issue since 2018 👴. Thus far, we cover troubleshooting with *Troubleshooting* sections in individual topics and via the descriptions of framework error messages. Do you still envision ever having this one? If not, I recommend we close this. We could always create a new issue in the future if there's a renewed interest.

**Comment by danroth27** [comment]
Closing seems fine to me.
