### ISSUE TITLE
Blazor design patterns

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#10742]
From @vertonghenb at [Introducing Design Patterns](https://github.com/aspnet/Blazor.Docs/issues/301)

Requests for new topic

Since Server-side Blazor (a.k.a Razor Components)  shifts the entire idea of a client and back-end, it would be nice to see some advised Design Patterns. For example: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model
- Is it still feasable to use a DDD pattern when we're sharing the domain between the App and Server?
- Should the Service Layer be isolated from the domain so we can use a Proxy Design Pattern when switching from Server Side to Client Side?
- Rich domain model versus anemic domain model (https://martinfowler.com/bliki/AnemicDomainModel.html)
- Form Validation based on Data Annotations and taking a dependency on MVC or using a library such as FluentValidation?
- ...

For newcomers it can be pretty confusing.

**Comment by neven10** [comment]
Maybe also include possible pitfalls of some approaches. On "client side" you can call any server code. For example nothing stops you from calling Save on EF context directly. 
I don't know in depth how SignalR works with Razor components, but calling server code like that directly can't be a good idea.

**Comment by guardrex** [comment]
@danroth27 ... "Form Validation based on Data Annotations" looks good here ... work'in ⛏ *work'in* ⚒ **_work'in_** it ... [Blazor forms and validation](https://docs.microsoft.com/aspnet/core/blazor/forms-validation?view=aspnetcore-3.0).

WRT the rest: Would I be correct in surmising that the PU is going to need to work this one? If so, let's mark this "PU." If not, recommend that we close this.

**Comment by guardrex** [comment]
Hello! Sorry for the **_very late_** triage/reply. Management has decided not to pursue recommendation for the Blazor docs. Thanks for inquiring on it.
