### ISSUE TITLE
Add "Kubernetes/Helm" to the list of container orchestrators.

### ISSUE THREAD

**Issue by clarenceb** [dotnet/AspNetCore.Docs#10757]
&gt; Two different choices are offered: Docker Compose and Service Fabric.

There is now another option available: Kubernetes/Helm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16250
