### ISSUE TITLE
MessagePack Protocol

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#10764]
From @huaxiangyang on https://github.com/aspnet/Docs/issues/10763 ...

When to add the MessagePack protocol to Java Clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by OzBob** [comment]
Also note that the latest version of signalR (3.0.0-preview5-19227-01) is NOT compatible with the matching version of MassagePack. 
"@aspnet/signalr-protocol-msgpack@3.0.0-preview5-19227-01 requires a peer of @aspnet/signalr@^1.0.0-preview3"
https://github.com/aspnet/AspNetCore/issues/10307

**Comment by crow-ua** [comment]
@Rick-Anderson @bradygaster Any chance this will be available in the nearest future? Or maybe you can suggest how to deal with the problem when large json payloads are causing SignalR requests to time out. Our field metrics show ~16 mb payloads are "too much" for Azure SignalR :(.

**Comment by wtgodbe** [comment]
We've added the MessagePack protocol in rc1 - Using this issue to track adding documentation for it

**Comment by OzBob** [comment]
I see rc1 here: [https://www.npmjs.com/package/@microsoft/signalr/v/5.0.0-rc.1.20451.17](https://www.npmjs.com/package/@microsoft/signalr/v/5.0.0-rc.1.20451.17)

thx

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/AspNetCore.Docs/pull/21090
