### ISSUE TITLE
Azure App Service provider AddAzureWebAppDiagnostics

### ISSUE THREAD

**Issue by yellowsix** [dotnet/AspNetCore.Docs#10840]
The language in the Azure App Service provider logging section needs updating, as well as the example of how to enable logging. As it is worded right now, it is pretty ambiguous what is required. I would suggest the following:

1. If you are using the Microsoft.AspNetCore.All metapackage, you do not need to install Microsoft.Extensions.Logging.AzureAppServices. If you are using the Microsoft.AspNetCore.App metapackage, you DO need to install it.

2. You must call AddAzureWebAppDiagnostics. The new and recommended way to do that is in Program.cs, e.g.

WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging(c =&gt;
                {
                    c.AddAzureWebAppDiagnostics();
                })
                .UseStartup&lt;Startup&gt;()
                .Build();

(It is unclear to me whether this is required if you are using the "All" metapackage, but it is definitely required if you are using the "App" metapackage. That should probably be clarified in the documentation as well.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#azure-app-service-provider)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by serpent5** [comment]
Closing as the `Microsoft.AspNetCore.All` metapackage is no longer supported.
