### ISSUE TITLE
context.Resource in SignalR

### ISSUE THREAD

**Issue by evangeloper** [dotnet/AspNetCore.Docs#11261]
Is there a way to get specific Resource information if the resource being protected is a SignalR hub?
I think not, but if possible this information could be valuable to others.
For example, I am trying to get the FullName of SignalR protected resource, but I can't find any information.

// Requires the following import:
//  using Microsoft.AspNetCore.Mvc.Filters;
if (context.Resource is AuthorizationFilterContext mvcContext)
{
    // Examine MVC-specific things like routing data.
}

**Comment by bradygaster** [comment]
@evangeloper is this still an issue for you? I'd like to understand the details of what you were trying to accomplish here. If so, please re-open and provide some details and we'll try to help. 

If you're specifically looking for a way to interrogate a SignalR endpoint - like OpenAPI for a RESTful endpoint - that is a feature we've explored but have not had compelling-enough usage scenarios to implement it yet.
