### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by viktor-nikolaev** [dotnet/AspNetCore.Docs#11275]
Is it safe to call hub methods simultaneously from several threads?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Can you clarify what you mean as you should never be calling a hub method from a thread explicitly.

Do you mean can you call hub methods simultaneously from multiple clients? The answer is yes, although if your logic isn't thread safe and accesses "global" variables/services you can have issues.

**Comment by viktor-nikolaev** [comment]
It's been a long time since I asked this 😀
I mean, I have a .net client in console app and I want to call hub methods from several threads in my console app using same instance of the client.

In short, the question is .net client for signalr thread safe?

**Comment by BrennanConroy** [comment]
Yes, that is thread safe.

**Comment by bradygaster** [comment]
Closing as it looks like this was a question, but I think it'd be good for @IEvangelist to be aware of this question (for it is relatively common) as he is working on an upcoming Learn path about SignalR. This could be an interesting point for it.
