### ISSUE TITLE
No information on accessing context when authorizing a method invocation

### ISSUE THREAD

**Issue by IanIsFluent** [dotnet/AspNetCore.Docs#11331]
We have custom authorization code which I'm trying to port from ASP.Net SignalR to Core. I can get this working fine using an Authorization attribute on the Hub, because I can use the IHttpContextAccessor service to get the HttpContext, which includes a header with our token.
But I can't work out how to get to the HubConnectionContext when the attribute fires from a method invocation :(

So:
```
[Authorize]
public class ChatHub: Hub
```
Is fine, I can use:
```
public MyAuthHandler(IHttpContextAccessor contextAccessor)
        {
            _httpContextAccessor = contextAccessor;
```
But when this is called by method invocation from the hub, the `_httpContextAccessor.HttpContext` is obviously `null`... What service can I use to get the SignalR connection context?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by dj-curls** [comment]
I am also struggling with this, I'm not sure why @IanIsFluent thinks it's obviously null, as the code is still being executed within a request so as far as I can see it shouldn't be null. 

Not sure where else to find the context. I tried using `HubConnectionContext ` but (the built in) DI says it cannot resolve it.

I just want to access the authenticated user's claims in methods outside the hub called from the hub.

**Comment by IanIsFluent** [comment]
> I am also struggling with this, I'm not sure why @IanIsFluent thinks it's obviously null, as the code is still being executed within a request so as far as I can see it shouldn't be null.

Because I'd already issues with the last version of SignalR where the `HttpContext` was always null when accessed inside Hub code. For _some_ transport methods (websockets) I _think_ it makes sense that `HttpContext` is null - so maybe a decision was made to keep it null consistently, and avoid errors with `HttpContext` being null for _some_ transport methods?

**Comment by dj-curls** [comment]
Fair play with the previous version of SignalR, I don't think it should be null in any case though. In the case of websockets a context is still needed to identify the connection. I agree that the full HttpContext object probably isn't required, but with the absence of anything else, (or even any discussion at this stage,) I believe HttpContext (through IHttpContextAccessor) should never be null whilst SignalR is handling a request. 

I got around this by adding in middleware which reads the claims from the authenticated user, and injects them into my services before SignalR handles the request.

**Comment by bradygaster** [comment]
adding @BrennanConroy and @anurse here for their commentary on this.

**Comment by BrennanConroy** [comment]
This looks similar to https://github.com/aspnet/AspNetCore/issues/5279. We currently don't pass a resource to auth handlers which would contain the User and other information.

>I believe HttpContext (through IHttpContextAccessor) should never be null whilst SignalR is handling a request.

SignalR is decoupled from the HTTP request so you aren't guaranteed to have an active HttpContext while processing a hub invocation.

@dj-curls Could you share your middleware here?

**Comment by anurse** [comment]
> I believe HttpContext (through IHttpContextAccessor) should never be null whilst SignalR is handling a request.

This is definitely not the case. `IHttpContextAccessor` can definitely return `null` during a SignalR request. SignalR invocations often run outside of the context of a specific request (in WebSockets, for example, there is one request; in Long Polling there are multiple requests). If you need an HTTP context, you should be using the [`GetHttpContext` extension method on `ConnectionContext`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.httpconnectioncontextextensions.gethttpcontext?view=aspnetcore-2.2).

**Comment by wadepickett** [comment]
Closing, product question addressed.
