### ISSUE TITLE
[RC1] Document prerendering in Blazor (WebAssembly)

### ISSUE THREAD

**Issue by Andrzej-W** [dotnet/AspNetCore.Docs#11366]
Here https://github.com/aspnet/AspNetCore/issues/8033 we can read
> Closing as this has been discussed by @danroth27 and @SteveSandersonMS
We've decided not to enable prerendering by default in Blazor because of the additional complexity it adds for app developers. We should, however, provide guidance about how to add prerendering to the app so people can opt in to it, if they want.

Please add topic about prerendering because without it I don't even know where to start.

**Comment by guardrex** [comment]
@danroth27

**Comment by guardrex** [comment]
Cross-ref: [Update templates/middleware to use MapFallbackToPage/File](https://github.com/aspnet/AspNetCore/issues/8852)

This issue will be worked when Preview 4 is released.

**Comment by guardrex** [comment]
@danroth27 The blog post doesn't address the prerendering situation for Blazor client-side (only server-side), and the [engineering issue](https://github.com/aspnet/AspNetCore/issues/8852) is supposed to cover it according to [Prerendering support for Blazor](https://github.com/aspnet/AspNetCore/issues/8842), but I can't grok it out-of-context.

What can I add on Blazor client-side prerendering to the *Hosting Models* topic?

**Comment by danroth27** [comment]
> What can I add on Blazor client-side prerendering to the Hosting Models topic?

Prerendering support for client-side Blazor is still to be done. Nothing to doc yet.

**Comment by Andrzej-W** [comment]
It looks that prerendering in Blazor client side just works in preview5. See here https://github.com/aspnet/AspNetCore/issues/10750 There is also an example code published by @danroth27

**Comment by mkArtakMSFT** [comment]
@javiercn don't we have content for this doc article anywhere? Can you please put together some write-up here, if there isn't any, so this gap is closed? Should we document only what's possible at this point, and we can revise the doc when 5.0 ships with more 'extended' support for prerendering?
/cc @SteveSandersonMS

**Comment by Andrzej-W** [comment]
A few topics to consider:
- Basic server project configuration for prerendering (https://github.com/danroth27/BlazorWebAssemblyWithPrerendering)
- How to select  the same culture / ui culture on the server during prerendering and on the client?
- How to select  the same time zone on the server during prerendering and on the client?
- Suggested pattern for services used by components. The same interface must have different implementations on the server (for example direct Entity Framework or repository access) and on the client (WebApi call) (https://github.com/danroth27/BlazorDualMode)
- How to update `<title>` tag dynamically during prerendering and on the client after every navigation.
- How to update contents of `<head>` section during prerendering. We have to render different `<meta>` tags for every page and usually for the same page but with different parameters. It is necessary for SEO and social services integration (Facebook, Twitter, etc.)

**Comment by guardrex** [comment]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-webassembly-prerendering
