### ISSUE TITLE
PS script 'Log on as a service' right for service account

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#11362]
Currently, the topic uses a manual process (Local Security Policy console or Local Group Policy Editor console) to provide *Log on as a service* rights to the service user account in the [Log on as a service](https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service#log-on-as-a-service) section.

Should a PS script-based approach replace the current approach (along the lines of this [UserRights](https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0) script)? If engineering provides the script, the docs team can roll the script into the topic. If not, this issue can be closed.

Cross-ref: https://github.com/aspnet/Docs/pull/11342

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by scottluskcis** [comment]
Hi @guardrex has there been any new movement on this topic? I follow the instructions at [Log on as a Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#set-permission-log-on-as-a-service) in the doc but cannot actually call `Start Service` until I open up `services.msc`, find the service and set the password again and click OK to add Logon as a service to the user. Would like to be able to accomplish via PowerShell. I assume that's your intent in adding this issue. Appreciate any input.

**Comment by guardrex** [comment]
You're correct on the goal of this issue. I've marked this for the product unit to address ("PU" label). If a script is created, they'll provide it. Not sure on the ETA when they'll look at this. Now that Preview 4 is out, it might not be long before they look at this.

**Comment by scottluskcis** [comment]
Thanks for the confirmation and response, I'll keep a watch on this and the docs page.

**Comment by guardrex** [comment]
You could try this :point_right: https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0 in the meantime, but it's one of those *use at your own risk things*. If it fries your hard drive, kills your cat, and gives your car a flat tire, you know what they'll say. :smile: lol

**Comment by Rick-Anderson** [comment]
Moved to Master issue, look here first. #18118

**Comment by guardrex** [comment]
Sorry folks! Change of plans. One of the docs team members will take care of the general updates first (3/4 open issues), then I'll come in later and address the Blazor-specific issue later.

**Comment by Rick-Anderson** [comment]
Moved to #28041
