### ISSUE TITLE
HTTP/2 not mentioned

### ISSUE THREAD

**Issue by dlidstrom** [dotnet/AspNetCore.Docs#11619]
It seems to me that any page discussing bundling and minification should mention HTTP/2. It is not clear to me why bundling is necessary in the modern world with HTTP/2 and HTTPS becoming pretty much standard.

Also, this page does not seem to mention the fact that all JS minifiers will eventually fall behind the fast moving languages of JS and CSS. This is a concern because compilation errors are most likely not detected by the minifier in the same way you can expect from a C# compiler and will result in hard to diagnose production errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@danroth27 can we retire this high issue doc?

**Comment by danroth27** [comment]
@Rick-Anderson I don't think so. We need to have some public statement about what our bundling and minification story is for ASP.NET Core. But we can try to simplify or correct it if there are particular sections that are problematic.

**Comment by drdamour** [comment]
it isn't use webpack when building?

**Comment by Rick-Anderson** [comment]
Migrated to Bundle and minify master issue #18523
