### ISSUE TITLE
Bundler & Minitifier is no longer actively worked on or supported

### ISSUE THREAD

**Issue by brightertools** [dotnet/AspNetCore.Docs#11610]
The Bundler & Minitifier plugin mentioned is no longer actively worked on or supported, please demonstrate something that is supported.

Ref (from the creator): https://github.com/madskristensen/BundlerMinifier/issues/407 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by dazinator** [comment]
Not sure if this helps but check out this sample demonstrating my open source "netpack" library for providing development processing pipelines: https://github.com/dazinator/NetPack/tree/develop/src/NetPack.Web

If you browse the various pages it demonstrates:

- Hot module reload
- browser refresh
- Typescript compilation 
- SystemJs based workflows
- RequireJs based workflows

You might find it useful. I plan on adding blazor support in future.

**Comment by mcNux** [comment]
For those still on core 2.2, this may work for you (has for me) - https://stackoverflow.com/a/59774701/1111662.

**Comment by Rick-Anderson** [comment]
Migrated to Bundle and minify master issue #18523
