### ISSUE TITLE
Update Layout doc for 3.1

### ISSUE THREAD

**Issue by PepitoSh** [dotnet/AspNetCore.Docs#11720]
In VS 2019 RC3 using ASP.NET Core 3.0 Preview 3 the generated application template is different from what displayed here. The layouts cannot be managed the same way as in Core 2.2. Please update the documentation and explain how one can use alternative layouts for different pages.

@Rick-Anderson  edit: Also address #11030

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/razor-pages/index?view=aspnetcore-3.0&tabs=visual-studio#using-layouts-partials-templates-and-tag-helpers-with-razor-pages

We recommend you not put the layout file in the Views/Shared folder. Views/Shared is an MVC views pattern. Razor Pages are meant to rely on folder hierarchy, not path conventions.

Add that

**Comment by Perustaja** [comment]
It seems we're being forced to have view and area directories together if we want Identity in an MVC project for example. It's rather frustrating trying to get the two to coexist at times if you need full control of the UI via scaffolding.
