### ISSUE TITLE
How to write a custom logging provider

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#11842]
One reason for needing a new doc about writing custom logging providers:  no built-in logging providers are available that can be used to follow the advice in the [No asynchronous logger methods](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/#no-asynchronous-logger-methods) section.  See #11801 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by haakoo** [comment]
It would also be nice if this example showed how to pass a dependency to the custom logging provider.

I'm trying to figure out how to implement an `ILogger` that prints to my GUI.

**Comment by IanKemp** [comment]
This article is pretty long-winded but gets the job done, so it could maybe be adapted for MS docs? https://www.codeproject.com/Articles/1556475/How-to-Write-a-Custom-Logging-Provider-in-ASP-NET

**Comment by JuergenGutsch** [comment]
@IanKemp Thanks for sharing my post here as an example. 

If it's okay for you all, I would be glad to write that documentation. :-)

**Comment by Rick-Anderson** [comment]
@JuergenGutsch let me know what I can do to help. If you want to create a PR with the content, I can clean it up or assign someone to do that.

**Comment by Rick-Anderson** [comment]
This is tracked in #16174

**Comment by Rick-Anderson** [comment]
@serpent5  can you add a link to additional resources

`* [How to add custom logging in ASP.NET Core](https://asp.net-hacker.rocks/2017/05/05/add-custom-logging-in-aspnetcore.html) `

The sample looks solid to me.

**Comment by Rick-Anderson** [comment]
@JuergenGutsch  let me know if you'd like to provide a sample. We can help you through the PR process.

**Comment by JuergenGutsch** [comment]
Hey @Rick-Anderson 
Sorry, for being that late. Unfortunately I had some completely different priorities the last months :-(

I'm going to start adding the sample later today :-)

**Comment by Rick-Anderson** [comment]
@JuergenGutsch  awesome. Let me know what I can do to help.

**Comment by JuergenGutsch** [comment]
@Rick-Anderson I just created the PR (#18252)
