### ISSUE TITLE
How to replace session_start in ASP.NET Core

### ISSUE THREAD

**Issue by akghasemi** [dotnet/AspNetCore.Docs#11869]
It does not describe how to get session_start and alot of other events, basically events cannot be replaced with methods. You replace application_start event with startup.cs. That is OK but there are alot of events in global.asax, what do you do about them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Application_BeginRequest, Application_EndRequest, Application_AuthenticateRequest and Application_Error can be replaced by a [middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?highlight=middleware&view=aspnetcore-2.2) 

*global.asax* is an HTTP Module. HTTP Modules are replaced by middleware.

This should be added to the doc.

**Comment by akghasemi** [comment]
yet, nothing about session_start, session_end and the document doesn't say how to implement them with middle ware

**Comment by Rick-Anderson** [comment]
@akghasemi  see https://forums.asp.net/t/2140604.aspx?What+s+the+equivalent+of+Session_Start+in+Global+asax+file+ASP+MVC+in+CORE+MVC

**Comment by alex-jitbit** [comment]
@FransBouma thanks
