### ISSUE TITLE
Please mention which conditions are the default on Linux

### ISSUE THREAD

**Issue by zidocread** [dotnet/AspNetCore.Docs#11948]
It would be helpful for people hosting on Linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945c28b7-6cc7-d4ed-3b96-a401eef42f59
* Version Independent ID: eb45fbf9-29fb-c67b-2f50-454380a502dd
* Content: [Data Protection key management and lifetime in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/data-protection/configuration/default-settings.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/default-settings.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by DanielCaspers** [comment]
I did the legwork for someone else to add this to the docs. Surfacing this info to the public would be a very welcome addition :)

https://github.com/aspnet/AspNetCore/blob/master/src/DataProtection/DataProtection/src/Repositories/DefaultKeyStorageDirectories.cs#L24

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
