### ISSUE TITLE
UseAuthentication - missing or not required?

### ISSUE THREAD

**Issue by pekkah** [dotnet/AspNetCore.Docs#12018]
Is UseAuthentication required or is it just missing from the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Yes, you'd need to use `UseAuth` middleware to light up the underlying authentication plumbing. Is this not evident from the other docs on ASP.NET Core auth? I don't mind explicitly adding a mention of this step to the article if you feel that'd add value.

**Comment by Rick-Anderson** [comment]
It's there twice
The order in which you register the SignalR and ASP.NET Core authentication middleware matters. Always call UseAuthentication before UseSignalR so that SignalR has a user on the HttpContext.
