### ISSUE TITLE
Nowin is deprecated in favor of Kestrel - remove Nowin

### ISSUE THREAD

**Issue by davidmi** [dotnet/AspNetCore.Docs#12218]
This page recommends using Nowin, but per Nowin's README it has been largely deprecated in favor of Kestrel. Is it possible or recommended to use Kestrel when self-hosting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34916983-6cf6-590e-0762-df0fe4e4f52c
* Version Independent ID: 1bf5bce0-c571-296e-1e8a-896af7068499
* Content: [Open Web Interface for .NET (OWIN) with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/owin.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/owin.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by dwgray** [comment]
Can Microsoft.AspNetCore.Owin be used to host asp.net identity on asp.net core?  If so, how?

**Comment by Rick-Anderson** [comment]
@Tratcher  how much of this doc should be retired? Nowin only?

**Comment by Tratcher** [comment]
Yes, you can remove Nowin.

**Comment by Tratcher** [comment]
@dwgray It may be possible, but that's not a supported or recommended scenario. We'd suggest moving to ASP.NET Core Identity.

**Comment by dwgray** [comment]
@tratcher Thanks - I guess I will break down and do the full migration.
