### ISSUE TITLE
Web apps Overview topic

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#12235]
Per Dan Roth
Given the options for ASP.NET Core 3.0 currently available in Preview 4, it looks like the Web app TOC node could use a new Overview topic that also helps you quickly narrow down what pattern/set of features to consider to meet a common web app goal.

**Comment by Rick-Anderson** [comment]
Need outline by the PU

**Comment by Rick-Anderson** [comment]
Dup of #17882
