### ISSUE TITLE
Replace Gulp with tooling that offers similar functionality

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#12367]
Discussed at https://github.com/aspnet/AspNetCore.Docs/pull/12366#issuecomment-491331984.

Possibly work in conjunction with #11610 if a comprehensive overhaul is in the works.

Per `@danroth27` in  #10798 - retire Gulp doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio#consume-bundleconfigjson-from-gulp)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Migrated to Bundle and minify master issue #18523
