### ISSUE TITLE
There is no content in "Enable QR Code generation for TOTP authenticator apps in ASP.NET Core"

### ISSUE THREAD

**Issue by gvaduha** [dotnet/AspNetCore.Docs#12436]
Page have only header and footer but no content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-1.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gvaduha** [comment]
This seems to be temporary problem, after several reloads it renders again.

**Comment by gvaduha** [comment]
This seems to be temporary problem, after several reloads it renders again.

**Comment by sadjadbp** [comment]
I still no contents

**Comment by Rick-Anderson** [comment]
Set the version to 2.1 or higher.

**Comment by ChandlerSwift** [comment]
I had the same issue coming from https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1 Since the newest version SMS authentication is supported by is older than the oldest version supported by TOTP, would it be possible to update the redirect on that page to point to at least ASP.NET v2.1?

**Comment by Rick-Anderson** [comment]
I'll fix it.

**Comment by tinatenatean** [comment]
Would you provide TOTP authenticator help for ASP.NET Membership Provider implementations?
