### ISSUE TITLE
Microsoft.AspNetCore.Mvc has to be included as DIRECT dependency

### ISSUE THREAD

**Issue by damtur** [dotnet/AspNetCore.Docs#12447]
I have been investigating for a while why my razor views are not precompiling. The problem was that I was referencing Microsoft.AspNetCore.Mvc as downstream dependency. That was not enough. I had to directly reference Microsoft.AspNetCore.Mvc from the project I was doing compilation in (my webapp project). Can we please add that note to documentation? I hope that will save some others time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
@damtur  can you update #12801
If possible, work some of the comments `@pranavkm` left.

**Comment by ondravondra** [comment]
Fortunatelly I found this after almost a day of pain and frustration.

**Comment by Rick-Anderson** [comment]
Per @pranavkm 

I'm not sure if this statement helps. You specifically need a reference to the `Microsoft.AspNetCore.Mvc` package in Razor Class libraries for 2.x targeting projects since it has build targets which are intended to be non-transitive. Other references can be picked up transitively. I'd also put this near the bottom of the page. Our general guidance is to start from a RCL template which has the reference, so this is a fairly uncommon scenario.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
