### ISSUE TITLE
not available in recent npm

### ISSUE THREAD

**Issue by OzBob** [dotnet/AspNetCore.Docs#12494]
Note add warning at top of doc - this is not released yet

To get 'withAutomaticReconnect' which you can see here:  https://github.com/aspnet/AspNetCore/blob/1cb42b1374de170fe32c100177b300878615b56d/src/SignalR/clients/ts/signalr/src/HubConnectionBuilder.ts#L156 

Install latest 'next' version via npm:

npm i @aspnet/signalr@next

The preview 'next' version as of writing was: 3.0.0-preview5-19227-01

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#reconnect-clients)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Closing as this is no longer relevant
