### ISSUE TITLE
Sqlite to SqlServer causes an issue

### ISSUE THREAD

**Issue by bluebaroncanada** [dotnet/AspNetCore.Docs#12508]
In the tutorial, you have `ConfigureServices`.  In that function that you provide, you connect to an SqlServer database.  Two problems with that: It doesn't like the Data Source keyword and the db is actually Sqlite.  Changing to Sqlite on that one line gets things working again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I need to change `dotnet new webapp --auth Individual -o WebApp1` to `dotnet new webapp --auth Individual -uld -o WebApp1`

**Comment by Rick-Anderson** [comment]
Actually I think I'll mention that code connects to SQL Server. If you're using SQLite, use the SQLite code.

**Comment by bluebaroncanada** [comment]
The template comes with an SQLite db all ready, and the tutorial actually mentions that db.

**Comment by Rick-Anderson** [comment]
Only on the VS/Mac tabs. Most folks on windows use SQL Server.

**Comment by bluebaroncanada** [comment]
Yeah, but now it's not a self-contained example.  Also, .Net Core .. I'm using Rider.  I could well be in Linux.  I don't see why you would provide a DB in sqlite and then switch to SqlServer.  If anything, I'd leave it as Sqlite and mention SqlServer.  I think you're wrong, but it's your world.

**Comment by Rick-Anderson** [comment]
I'll put a comment in the code warning SQLite folks.

**Comment by bluebaroncanada** [comment]
I'm not an SQLite folk.  I just just followed along with the tutorial and SQLite comes preconfigured from the code scaffolding in the tutorial.  I'm MySql folk.

**Comment by bluebaroncanada** [comment]
In fact, I just copied and pasted code right from the tutorial and that one line is the only line in the tutorial that doesn't work out of the box.

**Comment by Rick-Anderson** [comment]
Moved to Moved to #16230
