### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Hubs.IAssemblyLocator

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#12558]
**Help us make content visible**
I am porting existing application to .Net Core 2.2 and find this symbol missing. What was the purpose of this interface and how to port the exiting code which depends on it to .Net Core 2.2 !?!

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

- Explain why this topic is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

**Comment by BrennanConroy** [comment]
`IAssemblyLocator` was used to find loaded assemblies to automatically discover hubs for clients to connect to.

In ASP.NET Core SignalR you need to explicitly map hubs, see https://docs.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-2.2#configure-signalr-hubs

**Comment by khteh** [comment]
How did it work previously? The route.MapHub requires URI. What do you mean "automatically discover hubs for clients to connect to"? Which URIs did the clients connect in the old way? Thanks.

**Comment by BrennanConroy** [comment]
> How did it work previously?

It worked via "magic" before via things like `IAssemblyLocator` which would find classes of type `Hub` and map them for you.

>The route.MapHub requires URI.

Correct, you need to map each hub you have to a different path.

>Which URIs did the clients connect in the old way?

I don't remember the exact paths clients would connect to, but now you use the `HubConnectionBuilder` to connect to a hub. See https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#connect-to-a-hub
