### ISSUE TITLE
Is there a way to persist keys to Azure Key Vault?

### ISSUE THREAD

**Issue by chad-chronotek** [dotnet/AspNetCore.Docs#12592]
I know I can use a key in key vault to protect my keys, but I really want to store my keys in key vault as it seems like a better solution than blob storage or any of the other options when in an Azure deployment multi-region deployment where several app services need access to the same data protection keys.  Is there a way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by amenayach** [comment]
Meanwhile, you can use [this](https://github.com/aspnet/DataProtection/blob/a3484f4a908d73eb73c8194a4e197b06d2625090/src/Microsoft.AspNetCore.DataProtection/Repositories/FileSystemXmlRepository.cs) and [this](https://github.com/aspnet/DataProtection/blob/a3484f4a908d73eb73c8194a4e197b06d2625090/src/Microsoft.AspNetCore.DataProtection/DataProtectionBuilderExtensions.cs) to guide how to implement your own `IXmlRepository` against whatever storage you want.

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Key storage providers in ASP.NET Core #17625

**Comment by tndata** [comment]
I have implemented a sample implementation that stores the key-ring in Azure Key Vault here https://github.com/edumentab/AzureKeyVaultKeyRingRepository

**Comment by Rick-Anderson** [comment]
@tndata thanks for the sample. I don't think we can add your sample to the doc without a security review, but folks can find this issue. @blowdart  might have a better idea.

**Comment by blowdart** [comment]
We specifically didn't implement this because of concerns around permissions and having to give the app the ability to create new keys, so I'm afraid I agree with Rick, we shouldn't link to it I'm afraid.

**Comment by nmg196** [comment]
> We specifically didn't implement this because of concerns around permissions and having to give the app the ability to create new keys, so I'm afraid I agree with Rick, we shouldn't link to it I'm afraid.

Hi @blowdart  - If that's the case, how does this Microsoft solution from @pakrym circumvent that problem? Or am I misunderstanding what it does? :-
[](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.DataProtection.Keys_1.0.2/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/README.md)

**Comment by blowdart** [comment]
You are misunderstanding. Keyvault holds the master encryption key for the keyring. The keyring itself is in blob storage, which is why you need two settings.
