### ISSUE TITLE
Windows authentication does indeed work for browser (javascript) client on chrome - doc says it does not.

### ISSUE THREAD

**Issue by mmezei** [dotnet/AspNetCore.Docs#12735]
Windows authentication does indeed work for browser (javascript) client on chrome - doc says it does not. I am using chrome version  75.0.3770.80 and @aspnet/signalr version 1.1.4 - according to this doc: "Windows Authentication is only supported by the browser client when using Microsoft Internet Explorer or Microsoft Edge." That does not seem to be the case which is a good thing of course...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
The wording was updated a while ago to not completely rule out other browsers.
