### ISSUE TITLE
allowAnonymous set to false causes 401 on CORS OPTIONS preflight request - better to allowAnonymous to be set to true and use Authorize attribute

### ISSUE THREAD

**Issue by mmezei** [dotnet/AspNetCore.Docs#12733]
Looks like directives on this page to turn off anonymous access does not work well for POST/PUT requests. I noticed this for the POST that occurs as part of **SignalR** negotiation but I believe it is true for any POST/PUT requests. On an angular 7 app running on chrome and using the angular http client, it causes a 401 as it tries unsuccessfully to negotiate NTLM authentication on the CORS OPTIONS preflight request. It seems that it is better to leave allow anonymous enabled and use Authorize attributes to lock down an API. Confused why more people don't have this issue so wondering if I am missing something. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Calidus** [comment]
This situation exists in both.Net Core and the .Net Framework. Hosting your UI and the your API in same IIS website gets around this CORS issue. Another work around is to write some code to return 200 on any http options request.

**Comment by mmezei** [comment]
Do those options have an advantage over leaving anonymous authentication enabled and using authorization attributes and better a default policy requiring authentication? I like the idea of locking it down at the IIS level but often the front end is an independently developed app or written using a JavaScript framework like Angular. Hosting it in the same app adds devops/deployment complexities.

**Comment by Calidus** [comment]
I have used those two solutions, because I didn't want other developers to have to think about authentication when adding features to a solution. The default policy sounds like it would accomplish the same thing. The deployment complexities when hosting them in the same website are pretty manageable if you using tools like Azure Dev Ops.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
