### ISSUE TITLE
Update API links when available

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#12833]
Relink to API **AT RTM**:

* &lt;xref:Microsoft.AspNetCore.Authentication.Negotiate?displayProperty=fullName&gt;

  https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.AspNetCore.Authentication

* &lt;xref:Microsoft.Extensions.DependencyInjection.NegotiateExtensions.AddNegotiate*&gt;

  https://github.com/aspnet/AspNetCore/blob/3ce6c1dc5b022116ec9b13f9158e092323ac1158/src/Security/Authentication/Negotiate/src/NegotiateExtensions.cs#L22

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher For ...

* `Microsoft.AspNetCore.Authentication.Negotiate`
* `Microsoft.Extensions.DependencyInjection.NegotiateExtensions.AddNegotiate`

... I'm waiting on these to appear in the API browser for cross-links, but a request to include the API might not have been made. Can u assist, or who should be pinged?

**Comment by Tratcher** [comment]
@Rick-Anderson @anurse these should have been included in the 3.0 API update?

**Comment by guardrex** [comment]
Ping @Rick-Anderson @anurse ...

I'm looking to cross-link from API docs ...

* `Microsoft.AspNetCore.Authentication.Negotiate`
* `Microsoft.Extensions.DependencyInjection.NegotiateExtensions.AddNegotiate`

... but they live in the *Land of Wind and Ghosts.*:tm: (-RN)

> these should have been included in the 3.0 API update?

**Comment by Rick-Anderson** [comment]
@scottaddie can you look into this?

**Comment by anurse** [comment]
These were brand new NuGet packages in 3.0, so they could have been lost. I can probably dig them up if you need to add them to the ingestion process :).

**Comment by guardrex** [comment]
I still need to do the work on the docs side, so let's me on here so I don't lose track of the issue.

**Comment by guardrex** [comment]
Whoever takes care of this between @anurse or @scottaddie, please mark your PR `Addresses` to keep the issue open. I'll close it when I hit the docs for their cross-links.

**Comment by scottaddie** [comment]
API onboarding request submitted. See https://ceapex.visualstudio.com/Onboarding/_workitems/edit/174178 for status updates.

**Comment by scottaddie** [comment]
@guardrex These APIs have been published. Please continue with your work on this issue.

**Comment by guardrex** [comment]
Thanks @scottaddie ... will get it done by EOD.
