### ISSUE TITLE
3.1 update: Update Error Handling article for 5.0 (Generic Host)

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#12840]
* Update links in Startup exception handling section to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#capturestartuperrors
* Update sample app to 5.0

Update database exception handler.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1#additional-resources)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Legends** [comment]
`env.IsDevelopment()` is not anymore in v3.0

**Comment by Legends** [comment]
Just to add my opinion about the `ErrorHandling` sample code:
It kinda su...

// StatusCodePages
// StatusCodePagesWithLambda
// StatusCodePagesWithFormatString
// StatusCodePagesWithRedirect
// StatusCodePagesWithReExecute
// ErrorHandlerPage
// ErrorHandlerLambda
// ProdEnvironment or DevEnvironment
//
// The ErrorHandler directives must be used along with the ProdEnvironment directive.
// The DeveloperExceptionPage is seen only when the DevEnvironment directive is used.

#define StatusCodePages // or StatusCodePagesWithLambda or // StatusCodePagesWithFormatString or StatusCodePagesWithRedirect or StatusCodePagesWithReExecute
#define ErrorHandlerPage // or ErrorHandlerLambda
#define DevEnvironment //ProdEnvironment or

**Comment by Rick-Anderson** [comment]
> `env.IsDevelopment()` is not anymore in v3.0

That's not correct.

**Comment by deap82** [comment]
Since we upgraded to 3.1 the "Developer exception page" response only contains raw error text and not any surrounding html that provides the design and readability we've been used to. It is as if it has lost its "view file" sort of. What could the reason for this be?
