### ISSUE TITLE
Update Proxy and load balancer config doc for 3.0

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#12994]
Forwarded headers middleware update:  https://devblogs.microsoft.com/aspnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Let's reconcile this with https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer#forward-the-scheme-for-linux-and-non-iis-reverse-proxies from https://github.com/aspnet/AspNetCore.Docs/pull/12740.

The added section on that PR is scoped to 2.1-2.2 because the process is manual for <3.0. As of 3.0, that section doesn't appear because it all ✨ *Just Works*:tm: ✨ **_after the new container images land, which will happen by the time 3.0 hits RTM_**. Are we good @bradygaster? If so, this can be closed.

**Comment by tdykstra** [comment]
Is this note still accurate in 3.0:

> If no ForwardedHeadersOptions are specified in Startup.ConfigureServices or directly to the extension method with UseForwardedHeaders, the default headers to forward are ForwardedHeaders.None.

**Comment by bradygaster** [comment]
@guardrex i will be able to confirm that ASAP, have a meeting with that team shortly and will know more about their release cadence once we do chat.

**Comment by guardrex** [comment]
Sry @tdykstra ... Just :eyes: your question. According to their test, *yes* ...

https://github.com/aspnet/AspNetCore/blob/release/3.0-preview6/src/Middleware/HttpOverrides/test/ForwardedHeadersMiddlewareTest.cs#L747

**Comment by Tratcher** [comment]
Also, the section about "Configuration for an IPv4 address represented as an IPv6 address" was addressed by this fix in 2.2:
https://github.com/aspnet/BasicMiddleware/issues/358
https://github.com/aspnet/BasicMiddleware/pull/359

**Comment by Rick-Anderson** [comment]
@Tratcher should I remove the section **[Configuration for an IPv4 address represented as an IPv6 address](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#configuration-for-an-ipv4-address-represented-as-an-ipv6-address)** for 3.1 and later?

Is that the only thing to fix for this issue?

**Comment by Tratcher** [comment]
Yes please, that's all I know about right now.
