### ISSUE TITLE
Code samples are identical for both methods

### ISSUE THREAD

**Issue by empz** [dotnet/AspNetCore.Docs#13026]
This page says that we can either a) Use imperative authorization or b) Write a resource-based handler.

The imperative is pretty straightforward, but can end in a lot of duplicated code if we need to apply the same logic to several action methods.
So I was assuming a resource-based handler could abstract all this and be easily apply as an attribute filter to each action method, but the example shows the same code, the same if / else-if / else. I don't see the benefit here.
Also, [both linked](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authorization/resourcebased/samples) sample projects are almost identical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5234edfa-92bb-a0a4-c523-ad2d7823e865
* Version Independent ID: 89c82c33-8e4f-93dc-af2f-492350557a4b
* Content: [Resource-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/resourcebased.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/resourcebased.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by DrakeLambert** [comment]
It appears that the difference between the two sample projects is their ASP.Net Core version. `netcoreapp2.0` vs `netcoreapp1.1`. I don't think there are two different ways of doing resource based authorization. This documentation should say that you have to "write a resource-based handler" to "use imperative authorization". Someone needs to clear up this documentation.

**Comment by olivergrimes** [comment]
@eparizzi, not sure this would be much use but I wrote up a custom solution to declarative resource based authorisation:  https://undocumented.dev/declarative-resource-based-authorisation-with-asp-net-core/

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
