### ISSUE TITLE
Misleading Implementation Recommendation

### ISSUE THREAD

**Issue by mhintzke** [dotnet/AspNetCore.Docs#13024]
The documentation I am referencing is this one regarding CSRF Attack Prevention

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery
I would recommend adding a note under the section quoted: 

*To send the token on subsequent requests, store the token in the browser's local storage. Don't be concerned about CSRF vulnerability if the token is stored in the browser's local storage. CSRF is a concern when the token is stored in a cookie.*

Although this implementation would in-fact prevent a CSRF attack, by using this kind of implementation you are immediately putting the reader's web application at risk for a XSS attack.  By placing an authentication token into local storage, you are putting the web application at risk as an attacker that has gained access to the token by injecting their own script onto the page (whether directly via HTML inputs or a indirectly via a 3rd party library).

My only suggestion would to be putting a disclaimer after this line to warn readers about such vulnerabilities.

Thanks,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 64418](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64418)

**Comment by guardrex** [comment]
Hello @mhintzke13 ... I've marked this for the Product Unit to take a look at.

btw- Please use the **This Page** feedback button at the bottom of the topic when opening a new issue. It adds metadata that helps us track issues and work. I just mention it for future reference.

**Comment by mhintzke13** [comment]
Ahh ok I see thanks, will do this in the future!

**Comment by adityamandaleeka** [comment]
@blowdart @HaoK

**Comment by blowdart** [comment]
Oh this is interesting. In theory yes, in practice you really need to work hard to get XSS in asp.net because everything is encoded by default. 

OK new wording

> Placing a token in the browser local storage and retrieving it and using it as a bearer token does protection against CSRF attacks. However, should your app be vulnerable to script injection via XSS or a compromised eternal javascript file then an attacker could retrieve any value from local storage and send it to themselves. ASP.NET Core encodes all server side output from variables by default, reducing the risk of XSS. If you override this behavior by using Html.Raw or custom code with untrusted input then you may increase the risk of XSS.
