### ISSUE TITLE
WebSocket transport doesn't work!

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#13035]
Do you have any sample on using HttpTransportType.WebSockets? I tried but keep getting "System.Net.WebSockets.WebSocketException : Unable to connect to the remote server" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by navidmatin** [comment]
I also noticed the WebSocket transport not working on Windows 7 on .NET Framework apps. Is there any workaround for it? Also there is some documentation around older version of SignalR https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms#windows-desktop-and-silverlight-applications, can that get updated for the new version of SignalR client?

**Comment by BrennanConroy** [comment]
We have docs for ASP.NET Core SignalR
https://docs.microsoft.com/aspnet/core/signalr/introduction?view=aspnetcore-2.2

WebSockets isn't supported on Windows 7 unless you use Kestrel without IIS

**Comment by NVentimiglia** [comment]
> WebSockets isn't supported on Windows 7 unless you use Kestrel without IIS
We are talking about _client_ code, correct? This document is specifically about _client_ code, the client will not be using Kestrel, that is a server technology.

> WebSocket transport not working on Windows 7 on .NET Framework apps.
Websockets is not working on Xamarin applications at all. This is *Very* concerning that a realtime technology like SignalR does not use sockets but needs to fall back to HTTP polling. Incomplete work.

**Comment by NVentimiglia** [comment]
@BrennanControy
https://github.com/NVentimiglia/XamarinFormsSignalRDotNetCore
https://www.loom.com/share/6d0adc5740834d41ae903aba29b4b9df

**Comment by davidfowl** [comment]
@NVentimiglia in the video I see wss as the url, why is that? The SignalR client does that automagically under the covers. Just put https/http in there and it'll do the right thing.

**Comment by BrennanConroy** [comment]
If there is a product issue file an issue at https://github.com/dotnet/aspnetcore.
