### ISSUE TITLE
Environment doc - structure and content improvements

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#13140]
* Make the various ways to set environment variables H2s instead of H3s under **Set the environment** H2s.
* The content explaining use of launchsettings.json/launch.json under the  Development H3 in the Environments H2 section would fit better/be more discoverable as one of the ways to set environment variables.
* Document the UseEnvironment extension method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#environments)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
Last code example:

Why query ` env.IsStaging()` in `Configure` method when there is a separate `ConfigureStaging` method, so `Configure` will not be called at all ?!
