### ISSUE TITLE
Error setting Twitter external sign-in with ASP.NET Core

### ISSUE THREAD

**Issue by ajitgoel** [dotnet/AspNetCore.Docs#13203]
I have a ASP.Net Core 2.2 application and the twitter authorization has started showing an `Response status code does not indicate success: 403 (Forbidden) `error. I have triple checked the ClientId, ClientSecret and also the Website url, callback url, Terms and conditions url, Privacy policy url and everything seems to be ok

The [documentation ](https://developer.twitter.com/en/docs/basics/response-codes.html) says "The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits . Other reasons for this status being returned are listed alongside the error codes in the table below.".

How can I trap the error code(along with the HTTP status code(403 in this case)) when ASP.Net Core twitter authentication communicates with Twitter?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
