### ISSUE TITLE
Moving FROM Json.net also needs documentation

### ISSUE THREAD

**Issue by SidShetye** [dotnet/AspNetCore.Docs#13227]
If Json.NET has been removed from ASP.NET 3.0, in addition to getting it back in as a separate package (one path) you should also document what exactly needs to be done to switch to the ASP.NET 3.0 recommended path (using it from the System.Text.Json namespace)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0 Preview](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#update-routing-startup-code)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by SidShetye** [comment]
The default JSON serializer ought to work out of the box without any `AddJsonFormatters()` in the `ConfigureServices` of Startup.cs. BUT there is currently a bug in 3.0-preview6 [with an ugly workaround](https://github.com/aspnet/AspNetCore/issues/11246#issuecomment-502381495) that adds complexity.

Regardless, this guide should explain to people going from 2.x to 3.0 what needs to be done. e.g. "Do nothing, the default JSON serializer is automatically active" or whatever is the ground truth.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
