### ISSUE TITLE
Make sure everything in Microsoft.AspNetCore.Analyzers has an aka.ms link and docs

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#13284]
We're adding `Microsoft.AspNetCore.Analyzers` as a place for general-purpose ASP.NET Core analyzers. This set will be expanded over time to help users know about errors at build-time and also to discourage bad practices.

Each diagnostic we report should come with an `aka.ms` link pointing to a clear description of the diagnostic and what alternatives users should choose instead.

**Comment by rynowak** [comment]
These already have links - just need to make sure we've written appropriate docs.

**Comment by rynowak** [comment]
Here's a general skeleton of a doc for analyzers

# Summary 

This document contains descriptions and recommendations based on diagnostics from the `Microsoft.AspNetCore.Analyzers` package.

## ASP0000 - Do not call 'IServiceCollection.BuildServiceProvider' in 'ConfigureServices'

We do not recommend using the `BuilderServiceProvider` method inside `ConfigureServices` - usually this is done in an attempt to access services before the service provider has been created. The harmful consequence of doing this is that multiple copies of the service provider, and any singleton services will be created. This can cause correctness problems for services that expect only a single copy to exist.

Example code to triggers this diagnostic:

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        var serviceProvider = services.BuildServiceProvider();
        serviceProvider.GetRequiredService<MyService>();
    }
}
```

To prevent this warning, consider alternative designs to accomplish what you want. This could include:
- Using `ConfigureOptions` https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#use-di-services-to-configure-options
- Using service injection into `Configure` 
- Redesigning services to delay doing work

**Comment by danielfoxp2** [comment]
I don't get it. I just created a new MVC with authentication in 3.1 .NET core and it came with those warnings. Why the scaffold is done by you in a way that you do not recommend it?
