### ISSUE TITLE
Logout Flow

### ISSUE THREAD

**Issue by alfkonee** [dotnet/AspNetCore.Docs#13316]
Please include the Logout Flow for Blazor Authorization using AuthenticationStateProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Cross-linking a few existing topics for authn/authz ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
* [Token Based Authorization using IdentityServer with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14191)
* [Signalr Context.User missing on hub](https://github.com/aspnet/AspNetCore.Docs/issues/14097)
* [Logout Flow](https://github.com/aspnet/AspNetCore.Docs/issues/13316)

**Comment by VR-Architect** [comment]
Yes please. Thise code doesn't work:

    private async void LogoutUser()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        
        if (SignInManager.IsSignedIn(authState.User)) 
        { 
            await SignInManager.SignOutAsync(); 
        }

        NavigationManager.NavigateTo("~/", true);
    }

**Comment by guardrex** [comment]
@VR-Architect Blazor Server app?

**Comment by guardrex** [comment]
Note that this issue will be addressed with the scaffolding PR that I'm turning in shortly.

btw -- The answer is along those lines :point_up:, but you need an XSRF token to submit that form. I plan to have that approach on the PR.
