### ISSUE TITLE
Environments update to 3.1

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#13331]
![image](https://user-images.githubusercontent.com/3605364/65566043-6a16b800-deed-11e9-859a-765d4b5f3d75.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
`IHostingEnvironment` is deprecated

**Comment by guardrex** [comment]
Yes, I'll be getting to this topic soon ... either Saturday or Sunday I think.

**Comment by Legends** [comment]
Enjoy your weekend

**Comment by guardrex** [comment]
I **_just realized_** ... @Rick-Anderson reassigned this to himself. **_GOOD!_** :smile: I've got too much on my plate for this release. 🏃🏃🏃🏃🏃🏃🏃🏃🏃🏃🏃😅

**Comment by Rick-Anderson** [comment]
@dougbu  besides `IHostingEnvironment` is deprecated - anything else changed for 3.0 we should document?

**Comment by dougbu** [comment]
Have a look at the 3.0.0 announcements @Rick-Anderson

**Comment by mslot** [comment]
So just to understand, if ASPNETCORE_ENVIRONMENT either isn't set or is set to Production, means that we are on a Production environment. Is this the same for AZURE_FUNCTION_ENVIRONMENT? I find it difficult to make a distinction between those two. Especially when the azure Function is written in. NET Core.

**Comment by ArgTang** [comment]
It seems like the prefix has changed:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createdefaultbuilder?view=dotnet-plat-ext-3.0

```
        //     • load host Microsoft.Extensions.Configuration.IConfiguration from "DOTNET_"
        //     prefixed environment variables ///
```

A least for generic host it is not `ASPNETCORE_ENVIRONMENT ` but `DOTNET_ENVIRONMENT`

**Comment by guardrex** [comment]
@AvgTang They both work.
