### ISSUE TITLE
3.1 update: CORS and master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#13423]
See https://devblogs.microsoft.com/aspnet/aspnet-core-3-preview-2/
CORS is also now endpoint routing aware and will use the CORS policy specified on an endpoint.

Make sure update addresses When using endpoint routing, how do you enable cors with the default policy? #16569

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Recommend enhancing language that pertains to order. See :point_right: https://github.com/aspnet/AspNetCore.Docs/pull/13662#issuecomment-518267111

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  can you assign someone to outline the changes required for the 3.0 version of this and supply the new code?

**Comment by Rick-Anderson** [comment]
@JamesNK are you the right contact to outline this?

**Comment by martonx** [comment]
It seems to me, this documentation is incorrect. Check this: https://github.com/aspnet/AspNetCore/issues/16672
It seems app.UseCors and options inside takes real effect, not service.AddCors.

**Comment by guardrex** [comment]
@martonx `service.AddCors` with a specified policy works if the policy is used with the call to `app.UseCors`, such as in your first example of the engineering issue (and shown in this topic) ... but indeed ... it has to be a cross-domain request to trigger the CORS Middleware to add the headers.

btw - We recommend that you don't test using a browser ... use a tool ... like Postman or Fiddler, where you can explicitly set the request headers.

There seems to be one incorrect example in the topic that doesn't call `app.UseCors`.

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please handle this? Thanks!

> @mkArtakMSFT can you assign someone to outline the changes required for the 3.0 version of this and supply the new code?

**Comment by Rick-Anderson** [comment]
@pranavkm can you give me an ETA on when you can outline this?

**Comment by kevingates** [comment]
Any update on this?

**Comment by kevingates** [comment]
In particular, for 3.1. Trying to get an WebAPI for internal use and we want to allow any origin and this setup has been a nightmare.
