### ISSUE TITLE
OpenInfo is Info now

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#13440]
Hi team, 
I'm moving this from here: https://github.com/aspnet/AspNetCore.Docs.de-de/issues/47 since the user is commenting on the code example

@sk2andy commented 3 hours ago
Swashbuckle changed the name of the class OpenInfo to Info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core Web API help pages with Swagger / OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
This is now `Microsoft.OpenApi.Models.OpenApiInfo` and is reflected in the latest versions of this article.
