### ISSUE TITLE
Add more detail on caching of secrets

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#13484]
&gt; Secrets are cached until `IConfigurationRoot.Reload()` is called.

Let's expand upon the caching aspect. Is this manual call the ONLY way? Can a caching policy be created and observed by the configuration provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2#reload-secrets)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by dandenton** [comment]
FYI there is a way with v3.0.0+ to automatically refresh key vault configuration using `AzureKeyVaultConfigurationOptions.ReloadInterval`
