### ISSUE TITLE
Explain Options Pattern usage with secret store / Key Vault

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#13485]
Consider adding an example to the Key Vault, Secret Manager, or other related docs. Our current focus seems to be on using the pattern with *appsettings.json* only.

**Comment by a-vishar** [comment]
I'm in the process of doing this configuration at the moment, and a pointer would be amazing, even if a full example weren't available.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
