### ISSUE TITLE
Add additional info WebSockets

### ISSUE THREAD

**Issue by woozie164** [dotnet/AspNetCore.Docs#13492]
There is a part that says: "When using a WebSocket, you must keep the middleware pipeline running for the duration of the connection."

However, they don't explicity mention *how* to keep the middleware pipline running. All the examples given on this page assumes that the connection will be closed after sending a websocket message back. However, my use case required the connection to stay open for several messages. I imagine this is a common case for websockets.

My solution looks like this:
   ```
 app.Use(async (context, next) =>
            {
                if (context.Request.Path == "/ws")
                {
                    if (context.WebSockets.IsWebSocketRequest)
                    {
                        WebSocket webSocket = await context.WebSockets.AcceptWebSocketAsync();

                        //  some code that uses the websocket to send and recieve multiple messages
                        await matchMaker.AddPlayer(webSocket); 

                        // Websocket connection closes if the middleware ends.
                        // So keep this function active
                        // TODO: use cancellation token?
                        while (webSocket.State == WebSocketState.Open)
                        {
                            await Task.Delay(TimeSpan.FromMinutes(1));
                        }
                    }
                    else
                    {
                        context.Response.StatusCode = 400;
                    }
                }
                else
                {
                    await next();
                }
            });
```

Essentially I keep the middleware pipleine running by delaying the task for a while, and keep doing this while the websocket is still open.

This worked perfectly for my case, at least.

Is this someting worthwhile adding to the tutorial? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

PU issues:
- [ ]  How to send ping control frame? #17916
- [ ] 
- [ ] 
- [ ] 

**_Not_** PU issues:
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by serpent5** [comment]
Closing as an explanation of how to do this using `TaskCompletionSource` now exists in this article, immediately after the quoted sentence.
