### ISSUE TITLE
connection.invoke example should describe how to retrieve response data

### ISSUE THREAD

**Issue by sdpollack** [dotnet/AspNetCore.Docs#13526]
This example is incomplete.  It is missing a description of how to retrieve data from the response.

I'm pretty sure you use .then(), it it would be very helpful is this was clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
This information is present in the linked doc:
>The invoke method returns a JavaScript Promise. The Promise is resolved with the return value (if any) when the method on the server returns. If the method on the server throws an error, the Promise is rejected with the error message. Use the then and catch methods on the Promise itself to handle these cases (or await syntax).
