### ISSUE TITLE
Explain how to correctly pass context.Items to child tag helpers

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/AspNetCore.Docs#13532]
Please explain the use of `public override void Init(TagHelperContext context)` and its role in adding items to the `context.Items` dictionary which are only visible to child tag helpers.

In my specific application, I wrote a `<group>` tag helper that acts as a parent element for arbitrary child content. Among my tag helpers that may be a child of this parent element is one that targets `<input>` elements (set up to run after the ASP input tag helper). I wanted a way for my tag helpers to discover whether or not they have a `<group>` element as a parent. I decided that an easy way to do this is to have the parent tag helper add an item to the `context.Items` dictionary, and to check for that item's existence in the child tag helpers.

I quickly discovered that adding the item to the `context.Items` dictionary in the `Process()` implementation doesn't work because parent `Process()` methods do not necessarily get called before their children. Fortunately, someone answered my SO question about this and pointed me at the `Init()` implementation as the proper way to add items to the `context.Items` dictionary.

This is really a serious documentation problem. I can't find `Init()` discussed anywhere in this documentation, and a Google search for "child tag helper" turns up several examples that incorrectly add items to the `context.Items` dictionary in the `Process()` implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1#condition-tag-helper)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
