### ISSUE TITLE
.net Core Protected API + Azure AD + Angular 2 front-end (without any code on C#)

### ISSUE THREAD

**Issue by Defee** [dotnet/AspNetCore.Docs#13530]
From my point of view there is a huge gap in docs for the following topics: 
 How can I configure SPA (without any code on c#) to work with Azure AD and call my protected API in Azure?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
