### ISSUE TITLE
There is no way of detaching a callback from HubConnection.onclose

### ISSUE THREAD

**Issue by kirill-chilingarashvili** [dotnet/AspNetCore.Docs#13632]
There is no way of detaching a callback from connection.onclose(callback)
I believe there should be a method connection.offclose(callback) allowing to detach a callback from this event, otherwise there is no way of disposing a connection (it will hold a reference to a callback)

Looking at source code - there is an array - "closedCallbacks", there is a way to push a callback function to that array, but no way of removing it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
If you are seeing a memory leak or have an issue with the library please file an issue on the product repo https://github.com/dotnet/aspnetcore
