### ISSUE TITLE
Static files outside wwwroot

### ISSUE THREAD

**Issue by ivarne** [dotnet/AspNetCore.Docs#13653]
When I tried to store my javascript and css specific for areas in `Areas\*\wwwarearoot\**`, following the examples in this chapter I was surprised to see that they were not copied as part of a publish. 

It seems like I needed the following in my `*.csproj` file:

```xml
    <Content Include="Areas\*\wwwarearoot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```
Would you approve of me adding the following example with som explanation at the end of 
[this section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#serve-files-outside-of-web-root)?

```xml
   <Content Include="StaticFiles\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#serve-files-outside-of-web-root)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Note for your discussion with Rick on this: The only spot we currently mention it is in the Generic Host topic at the bottom of the `ConfigureAppConiguration` section for <3.0 ...

* For <3.0 (current): https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2#configureappconfiguration
* IIRC, it's removed for the upcoming 3.0+ release because for the default experience the SDK will move the settings file(s) without developer code. As of today, the doc set won't cover this for 3.0+ anywhere.

**Comment by guardrex** [comment]
I was hoping common targets and props would land in their own topic: I opened an issue in the 👴 *ancient days* 👴 of .NET Core. It's encouraging to see the interest in it; but alas, it's still backlogged ...

https://github.com/dotnet/docs/issues/2642

**Comment by ivarne** [comment]
I don't understand the responses here.

This is a simple issue asking if the docs for `StaticFiles` should suggest you can host `MyStaticFiles/images/banner1.svg` without mentioning that it probably should be included in a `<CopyToOutputDirectory>` directive in a `*.csproj` file.

**Comment by guardrex** [comment]
WRT my remarks: I was just providing some background info.

WRT your issue: *Yes* ... it has been labeled for work.

**Comment by Rick-Anderson** [comment]
Moved to Static files master issue and update to 3.1 #13599
