### ISSUE TITLE
3.0 update and Verbosity normal is required to see information about launchSettings.json

### ISSUE THREAD

**Issue by Liversage** [dotnet/AspNetCore.Docs#13706]
The documentation states that using `dotnet run` will display information if `launchSettings.json` is used:

> The following output shows an app started with dotnet run:

Part of the output:

```Using launch settings from C:\Websites\EnvironmentsSample\Properties\launchSettings.json...```

Using dotnet 2.2.401 with SDK 2.2.401 I had to add the `--verbosity normal` command line option to see the information about `launchSettings.json` in the console output of the dotnet command. Without this option the information was not displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Liversage  thanks for notifying us.  I think that change was made in 1.1.

**Comment by Rick-Anderson** [comment]
Search for
`The following output shows an app started with`

That output is only displayed when with
`dotnet run --verbosity normal`
