### ISSUE TITLE
provide complete example for ViewModel with CreateVM.cshtml

### ISSUE THREAD

**Issue by michaelmello** [dotnet/AspNetCore.Docs#13752]
I noticed the article talks about Create.cshtml and then mentions and links to a CreateVM.cshtml page when discussing View Models. I thought the CreateVM.cshtml link was a typo but there is in fact a page on Github that was created for purposes of the View Model, but no instruction to create it in the tutorial. Just throwing it out there as it may trip up newcomers (where did CreateVM.cshtml come from?).

`@Rick-Anderson  edit`

* Rename it `StudentInputModel`
* Update the Edit page to use `StudentInputModel`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the tip.

**Comment by HarleyPebley** [comment]
Agreed. This section was a bit confusing. IMO, the CreateVM section should either be completely fleshed out with running code or removed.

**Comment by Rick-Anderson** [comment]
@tdykstra  replace with InputModel approach with complete code.

**Comment by tdykstra** [comment]
Agreed that we should do it that way, and this approach should be adopted in later tutorials as well, not just #2 CRUD.  This will take some time to fix, so it will wait until higher priority 3.0 updates are done.

**Comment by Rick-Anderson** [comment]
@tdykstra  given that view models are so widely used we should keep this too and maybe provide a GitHub link to the complete code. Automapper is pretty popular.

**Comment by tdykstra** [comment]
In that case, we could switch CRUD to InputModel, keep TryUpdateModel in Update Related Data, and add text explaining the alternatives in both places.  If we want to show the ViewModel  as yet a 3rd option, could use it on Course pages in Update Related Data, and keep TryUpdateModel only on Instructor pages.

**Comment by Rick-Anderson** [comment]
Good idea. Before we do, let's run it by the EF folks.

**Comment by CTheCheese93** [comment]
As a newcomer, this section was extremely frustrating. The use of ViewModels in this context feels incomplete and left me with more questions than answers. Is TryUpdateModel preferred when doing Updates while ViewModels are better for Creation? How would an update with a ViewModel be implemented?

I'm unfamiliar with InputModel, but it would make sense if the tutorial represented all three options on their own instead of having us utilize the TryUpdateModel and then scrap it for a ViewModel just to go back to TryUpdateModel.

**Comment by Rick-Anderson** [comment]
`InputModel` is a ViewModel, it's just a VM named `InputModel`

cc @tdykstra

**Comment by smiller7812** [comment]
I agree this is confusing.  I usually just skip over content like this in tutorials and books.  Don't want to waste my time and brain power and get bogged down. I'm just moving on to the update section.
