### ISSUE TITLE
Apply MVC improvements to this topic

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#13776]
Apply improvements to https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio#initial-migration to this topic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@Rick-Anderson.  Could you add a bit of context?   What improvements did you have in mind?  Do you have specific PR's in mind or a range of them, or are you wanting me to go through every single PR that has been applied to to this one and see if I can apply it to Razor Pages?  Thanks.

**Comment by wadepickett** [comment]
@Rick-Anderson, I just realized you meant only the model topic in the series and had pointed to just that, sorry for the brief confusion..  I'll assume you meant I should look through every PR that has merged with the model topic and see what I can apply to the Razor Pages model topic.

**Comment by Rick-Anderson** [comment]
@wadepickett  no, compare [MVC Initial migration VS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.0&tabs=visual-studio-code#initial-migration) to [the RP version](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#initial-migration). 

Add everything to the RP version that the MVC version has and is missing in the RP version.
