### ISSUE TITLE
Explain 'a message sent from one app to all of its own clients will go to all clients of all apps'

### ISSUE THREAD

**Issue by John0King** [dotnet/AspNetCore.Docs#13788]
what should I do if I do want to send a message across multiple app ?  should the Hub class  be put in a class library ? or I can just use same hub name (full namespace class name or just class name)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
When you say "multiple app* what do you mean? Any client connected to a hub will receive a broadcast message to all clients. The app isn't really relevant in this context; it's more about the connection **to the hub**. Any connected client can receive messages, regardless of the app. 

If this answers your question please close the issue, or let us know how we can help further. Thanks!
