### ISSUE TITLE
SameSiteMode  requires using Microsoft.AspNetCore.Http;

### ISSUE THREAD

**Issue by mochr** [dotnet/AspNetCore.Docs#13848]
A using directive (using Microsoft.AspNetCore.Http;) has to be added to enable the SameSiteMode-enum. This should be added as a separate bullet point after the paragraph: "To enable the default cookie consent feature like that found in the ASP.NET Core 2.2 templates in an ASP.NET Core 3.0 template generated app:".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
When updating this, move #8544 to **Additional resources**

**Comment by Rick-Anderson** [comment]
We'll fix this in the next doc update. We typically don't add all the includes in advanced docs.
