### ISSUE TITLE
Document use of pattern parameter when calling MapFallbackToPage

### ISSUE THREAD

**Issue by jerriep** [dotnet/AspNetCore.Docs#13856]
As per https://github.com/aspnet/AspNetCore/issues/13167, can you please document how to specify the `pattern` parameter when calling `MapFallbackToPage()`? Using this parameter, you can host your Blazor application in a non-root URL, for example at `/spa/*`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Note to engineering when this is triaged: If I'm going to address this, I need a note on if/how the app base path relates to this (`<base href="/spa/">`).

**Comment by softlion** [comment]
@guardrex it is documented there https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.1&tabs=visual-studio

**Comment by guardrex** [comment]
Hello @softlion, :smile: lol ... *I wrote that.* :smile: ... No, what I'm asking, need to research further, and receive engineering notes on is if/how **_the MapFallbackToPage pattern relates to the app base path_**.

**Comment by softlion** [comment]
@guardrex 😄
I have searched for this info much longer than necessary, so i copy it on all the pages where the search engine sent me ;)

**Comment by softlion** [comment]
MapFallbackToPage seems to be able to map to both the base path and the non base path. Maybe this is an error.
