### ISSUE TITLE
3.1 update: ASP.NET Core fundamentals

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#13877]
update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson Can I take this one?

If yes, here's a proposal:

1. Copy the existing topic into its own `>= 3.0` version, wrapping the original version in `< 3.0`. This follows the pattern we've been using lately.
2. Remove all other monikers in the file. There are a few scattered around, so this would be all about putting the right content in the right places, collapsing it all down to just those two wrapped versions of the topic.
3. Update the `>= 3.0` version to 3.1, which covers both 3.0 and 3.1 for this particular topic. I can start with just getting all the code updated, along with any references in the surrounding explanation.

If there's more to be done, let me know, assuming this is all cool up to this point. This can be two PRs, with one for points 1 and 2 and another for point 3. Alternatively, I can do it as a single PR, if that's preferred. Another option is a draft PR for all of the the above, which you can take over into your own PR for further changes.

**Comment by Rick-Anderson** [comment]
@serpent5  I'll do steps 1 & 2 for you tonight. Step 3 would be a huge help. It's easier for me to do 1 & 2 because I can do a quick check of the build to verify nothing has changed.

**Comment by serpent5** [comment]
> @serpent5 I'll do steps 1 & 2 for you tonight.

There's no rush. Just let me know when it's ready and I'll pick it up. I'll have a look around for some other topics that need a 3.x update and see if there are any I can help with.

**Comment by Rick-Anderson** [comment]
@serpent5  1 &2 done in #17272
That was a PITA
Really needs an update and improvements. Should be fun to work on.
