### ISSUE TITLE
Improve documentation on migration

### ISSUE THREAD

**Issue by bdelsaz** [dotnet/AspNetCore.Docs#13900]
Hi, thanks for this article! I have a suggestion. In my view the part 'Apply the migrations to initialise the database.' could be a little more clear. I would explain that because the template project contains the IdentityDbContext class, that EF Core will create all the tables you show in the image for you. 
This article was my first stop on how to implement Identity on my existing project. I already had a DbContext with DbSets. It took me a while to figure out that I just needed to extend IdentityDbContext&lt;MyCustomUserClass&gt; in this existing DbContext, and then apply the migration to have the tables created. The rest of the article is really step-by-step but this migration part assumes a lot of previous knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#next-steps)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Moved to #16230
