### ISSUE TITLE
"Major change" highlighting not correct

### ISSUE THREAD

**Issue by HarleyPebley** [dotnet/AspNetCore.Docs#13903]
In the "Update edit page" section, there is one line highlighted as a major change in the OnPostAsync method but in fact the entire method is different from what the scaffolding provided, including the method signature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll look at these in the next doc sweep.
