### ISSUE TITLE
request for a simpler way to simply share a cookie

### ISSUE THREAD

**Issue by mnoreen** [dotnet/AspNetCore.Docs#13985]
The premise here is perfect and on point.  That is, as an organization, we want to move forward with our Microsoft based technology stack, and .NET Core looks great.  But... we have a very large investment in our current *Microsoft* based technology stack, one that is working very well, mind you.  It happens to be a web forms based website that has over 10 years of development investment in it.  So, rewriting that in one fell swoop is not doable.  Bringing up a new .NET Core site along side of the existing web forms and migrating over makes perfect sense.  

Authentication is key here.  So we spent a week trying to follow this technique, including having to add OWIN and "Katana-ize" a web forms website.  OK.  Then add nuget pkg after nuget pkg.  Then tweak the code here and fight Visual Studio (2017, targeting .NET Framework 4.8) to find the right references and usings.  41 DLLs were added to our Bin directory.  It more or less works, but this feels awfully fragile and way too prone to issues.

41 DLLs.  All to share one encrypted cookie to be recognized as the "authentication" cookie.  Do you see how over complicated this is? 

It's hard to fathom that Microsoft couldn't manage one method() to add to .NET core, a CookieAuthenticationOption, a DataProtectionProvider option, something... that simply sets up a "FormsAuthCompatible" cookie.  That's it.  Then all the organizations that have vested years of Web Forms (and even MVC) forms auth are off and running in that "side by side" development.  I'm not asking for .NET to "support" Web Forms.  Just a simple mechanism to share the well established authentication, encryption cookie.   41 DLLs does not seem like a viable solution.  I'd like to believe that for the MS team, however, there is something that could be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by mnoreen** [comment]
I'll be honest in saying that we are really disappointed.  Having a simple way to share the authentication cookie between web forms and .NET Core (aka .NET now) would have made a significant difference in moving forward.  If we have to rewrite everything, including authentication, it is definitely a barrier to entry.
