### ISSUE TITLE
HTTP Server Header

### ISSUE THREAD

**Issue by donile** [dotnet/AspNetCore.Docs#14005]
To instruct Nginx to modify the Server header in the HTTP response to the client, the Nginx directive proxy_pass_header should be used.

Example:
server{
    ...
    location / {
        proxy_pass_header Server;
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Host ASP.NET Core on Linux with Nginx #17735
