### ISSUE TITLE
Signalr Context.User missing on hub

### ISSUE THREAD

**Issue by Alienroid** [dotnet/AspNetCore.Docs#14097]
Not sure if I should post here or SignalR page. 

I am using Server side authentication and implementing SignalR. Previously, connection will have Context.User on the hub side. 

var user = await _userManager.GetUserAsync(Context.User);

I can get the Context.User on the razor component. However, when calling hub, Context.User doesn't contain current authenticated identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Alienroid** [comment]
I guess I could just pass name over signalr call and use _userManager.FindByEmailAsync. I think securitywise, probably better to have Context.User available though.

**Comment by guardrex** [comment]
Cross-linking a few existing topics for authn/authz ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
* [Token Based Authorization using IdentityServer with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14191)
* [Signalr Context.User missing on hub](https://github.com/aspnet/AspNetCore.Docs/issues/14097)

**Comment by enetstudio** [comment]
> I can get the Context.User on the razor component

I wonder how...

> However, when calling hub, Context.User doesn't contain current authenticated identity

Why should it ...

The link below is to a repository of mine, containing a Blazor Server App project and a Signalr Hub, which is protected with the Authorize attribute. My code demonstrates how to pass a security cookie with the SignalR connection in order to make the ClaimsPrincipal (Context.User) available within the SignalR hub 


[SignalR Server Identity Authentication](https://github.com/enetstudio/SignalRServerIdentityAuthentication)

Note: You may find related stuff in my answers in [stackoverflow...](https://stackoverflow.com/search?page=1&tab=Relevance&q=user%3a6152891%20%5bblazor%5d%20is%3aanswer) 

Hope this helps...

**Comment by Alienroid** [comment]
I did this before msft supported additional signalr connection. There was a documention error saying we could get context.user but it was return null. At the time of we used find by email, then it works... This was really old issue though.

**Comment by guardrex** [comment]
Thanks @enetstudio and @Alienroid.

@mkArtakMSFT ... Do you want this issue worked? It will probably fall off the radar with the current labels and lack of a project and assignee. If it is worked, I'll need the PU-recommended approach on how to address it. If you want me to work it, I recommend that we keep the SignalR-Blazor issues on the Blazor.Docs project. Unfortunately, I easily **_lose an issue_** 🙈 if it isn't on the project.

**Comment by enetstudio** [comment]
So why don't you close the issue...

**Comment by guardrex** [comment]
@enetstudio ... Let's see what Artak wants to do with it. As a workitem, it won't get lost on the tracking issue. It definitely won't get lost if he says that I should take it on and we put it back on the Blazor.Docs project.

**Comment by Alienroid** [comment]
This is off my memory 2 years ago, before MSFT said additional SignalR connection is supported (this is no longer the case). 

Original comment was on the documentation page, the sample on server-side's hub class, 

```
public override async Task OnConnectedAsync(){
...
var user = await _userManager.GetUserAsync(Context.User);
...
}
```
This won't work at the time. The only way to get user was "var user = await _userManager.FindByEmailAsync(name);" So documentation was misleading. The misleading sample is no longer in the document anymore (at least not this page).  

I guess all it takes is someone to test this is working. From @enetstudio's sample code, looks like it is working

```
 public override async Task OnConnectedAsync()
        {
            string name = Context.User.Identity.Name;

```

**Comment by guardrex** [comment]
Must have been a point-in-time thing then.

https://docs.microsoft.com/aspnet/core/signalr/hubs#the-context-object

Let's close. Thanks to everyone for their help and remarks on this one.
