### ISSUE TITLE
The name 'GrpcClient' does not exist in the current context	GrpcGreeterClient

### ISSUE THREAD

**Issue by VinceJSV** [dotnet/AspNetCore.Docs#14170]
After pasting the code into program.cs in the Greeter client project I get compiler error "The name 'GrpcClient' does not exist in the current context	GrpcGreeterClient".  I think that this is because no classes are generated by the build process after adding the item group to the project file. No idea why, the project file was edited correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by VinceJSV** [comment]
As work around suggested RobinKetting fixed the issue for now. Had to uninstall the current Grpc.Net.Client package and issue the following command in the PMC "Install-Package Grpc.Net.Client -version 0.1.22-pre2"

**Comment by Rick-Anderson** [comment]
@VinceJSV  thanks for the update. When ASP.NET Core 3.0 GA's, this shouldn't be a problem.

@JamesNK  - do we need to add a note for this problem or is the issue discoverable enough?

**Comment by switch900** [comment]
I just ran into the same problem.  Make sure Grpc.AspNetCore is only installed on the Server project.  If it is installed across the whole solution then it conflicts with Grpc.Net.Client on the Client project and prevents the Client project from installing correctly.

**Comment by ihorbond** [comment]
Why is this issue closed ?! I have the same problem.

**Comment by Rick-Anderson** [comment]
@ihorbond  the cause of the problem and solution are in this issue.

**Comment by hjy1210** [comment]
@ihorbond

I ran into the same problem. 

After inspect the GrpcGreeterClient.csproj, I found a strange node as follows:

```
<ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
</ItemGroup>
```
After delete it, rebuild the project, the problem is gone.

**Comment by chrisbiles** [comment]
To anyone that might still have the above mentioned problem, make 100% sure that your PMC "Default Project" setting is set to GrpcGreeterClient when issuing the following commands:

Install-Package Grpc.Net.Client
Install-Package Google.Protobuf
Install-Package Grpc.Tools

If not, you will have the aforementioned problem.  I just figured it out today that I was doing something that dumb and wondering why the GrpcClient was not being created.  Hope this helps.

Chris

**Comment by Jezuz85** [comment]
in my file GrpcGreeterClient.csproj delete this part

```
	<ItemGroup>
		<Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
	</ItemGroup>
```

compile and then add the line again, and it worked without issue

**Comment by Rick-Anderson** [comment]
@JamesNK  should I mention this in the tutorial? @wadepickett  on testing did you see this?

**Comment by JamesNK** [comment]
Removing and adding the same text from a csproj shouldn't have any impact. I'm not sure what the issue is that people are encountering.

**Comment by wadepickett** [comment]
@Rick-Anderson, I think you are referring to the test I did for  #21657. (Sorry just saw your question from 4 hours ago)

It looked like there was issue around renaming the namespace in the greet.proto to "GrpcGreeterClient" **which was fixed in the doc instructions but was not updated in the current client downloadable sample**: The namespace inside the greet.proto file for the client sample project's namespace should be:
     option csharp_namespace = "GrpcGreeterClient";
but incorrectly, the client sample was showing the original namespace for the server app greet.proto:
     option csharp_namespace = "GrpcGreeter";

**Comment by JamesNK** [comment]
Fix https://github.com/dotnet/AspNetCore.Docs/pull/21732

**Comment by eyal7773** [comment]
How to solve : 
1. Verify again that inside your client app, in `Greeter.proto` file  - this row include the "Client" at the end.
```
option csharp_namespace = "GrpcGreeterClient";

```
2.  Clean the project.

3. Rebuild 
4. Solved, now this method `Greeter.GreeterClient` will be exists.

**Comment by caiomjc** [comment]
The problem, for me, was the csproj.
When I copied the greet.proto from server project to client project, the csproj file added by itself the ItemGroup like this:

<ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
</ItemGroup>

Just replaced the "Server" for "Client" and all worked just fine.
In the end, should be like this:

<ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Client" />
</ItemGroup>
