### ISSUE TITLE
Add a doc talking about issues with connectedness and prerendering

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#14182]

**Comment by guardrex** [comment]
Cross-ref to this same or different issue (close it or work together?): https://github.com/aspnet/AspNetCore.Docs/issues/11366

**Comment by guardrex** [comment]
A lot of work has been done in this area since this was opened over a year ago. We have more to do, but it will be tracked by https://github.com/dotnet/AspNetCore.Docs/issues/14878 with some degree of re-organization of coverage in either a future issue or the UE tracking issue.
