### ISSUE TITLE
Token Based Authorization using IdentityServer with Blazor

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#14191]
From @noufionline ...

> Kindly provide a working sample or comprehensive documentation on how to use Token based authorization using IdentityServer and how to store Access Token and Refresh Token on the client side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by hubert-associates** [comment]
The blazor IdM impl and Steve's doc are great, but as long as we're addressing IdentityServer here, be sure not to forget another important IdP in that doc: Azure. AAD and AADB2C.  The current six page is a bit thin on solutions available to blazor-clients: how to redirect to an AADB2C OpenID-Connect flow for example (blazor-client and server interaction necessary here). This, I'm assuming (currently trying to impl.) would work similar to a pure javascript auth library for OAuth/OpenID such as that provided by Auth0.  Optimal would be a Blazor.net SPA-Component from AAD B2C just like the JS ones you get off the shelf from Auth0 and Okta...? Thanks

**Comment by guardrex** [comment]
Cross-linking a few existing topics for authn/authz ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
* [Token Based Authorization using IdentityServer with Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/14191)

**Comment by PtwHub** [comment]
Great. Clear Identity Management practices, a basis for security and privacy, is the sign of a production-ready design.

**Comment by mkArtakMSFT** [comment]
@guardrex this is something @javiercn is planning to provide content for.
Please hold off from doing anything here till you get the info from @javiercn.

**Comment by mkArtakMSFT** [comment]
@javiercn do you have a separate item tracking your piece of work here>

**Comment by mkArtakMSFT** [comment]
We track this work at https://github.com/dotnet/aspnetcore/issues/12320

**Comment by RedDeathGitHub** [comment]
Is there a "standard" sample on how one would use Blazor WebAssembly + ASP Core API with Identity server? I mean a common case scenario, probably with JWT tokens?

**Comment by mkArtakMSFT** [comment]
@javiercn did you have a sample like this somewhere ?

**Comment by javiercn** [comment]
@mkArtakMSFT I do have a sample, but nothing that I want to share in its current form.

**Comment by danroth27** [comment]
@guardrex I think this should be closed. We have https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1. Let us know though if you think something is still missing!
