### ISSUE TITLE
Code style issues

### ISSUE THREAD

**Issue by HarleyPebley** [dotnet/AspNetCore.Docs#14220]
Two minor nits (they don't impact behavior)...
In Edit.cshtml.cs:
1) In the `HandleDeletedDepartment `method, the `deletedDepartment `variable is not needed and can be removed.
2) `setDbErrorMessage `is a non-standard name for a C# method. Recommend capitalizing the first character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 61967](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61967)

**Comment by Rick-Anderson** [comment]
@HarleyPebley correct on all accounts. We'll update this in the next doc sweep.

**Comment by tdykstra** [comment]
Fixed by #28560
