### ISSUE TITLE
Guidance to run Angular SPA without a proxy in dotnet core 3

### ISSUE THREAD

**Issue by asad-c** [dotnet/AspNetCore.Docs#14236]
Could guidance please be added to explain how the dotnet core 3 Angular spa template project can be run without using a proxy. The proxy slows down debugging too much to be practical. I have tried commenting out the lines below but this does not work with the MVC redirects:

app.UseSpa(spa =>
            {
                // To learn more about options for serving an Angular SPA from ASP.NET Core,
                // see https://go.microsoft.com/fwlink/?linkid=864501

                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    // Start own instance of the Angular CLI server
                    //spa.UseAngularCliServer(npmScript: "start");

                    // Run Angular CLI server independently
                    //spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
                }
            });

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
