### ISSUE TITLE
Misleading statement about claims

### ISSUE THREAD

**Issue by jez9999** [dotnet/AspNetCore.Docs#14295]
I think these documentation should be updated as it makes a misleading statement about claims.  It says "A claim is a name value pair that represents what the subject is, not what the subject can do." - this seems to be untrue, because it's perfectly possible to have a "Permission" claim which specifies what the subject can do.  In fact, this is the way permissions-based authentication should be implemented in ASP.NET Core.  I recommend this be updated to something like "A claim is a name value pair that can represents what the subject is, rather than what the subject can do.", and then later, add "A claim can also explicitly represent what the subject can do, in the form of 'permission claim'.  In this case, there would be multiple claims with the name 'Permission' for the user, and each one would specify a something the user could do; for example, 'ManageUsers' or 'ViewReports'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25051544-0e4d-1715-95b7-3a8616475127
* Version Independent ID: 50736569-fc04-ec6d-7b33-a3e0c860b1ed
* Content: [Claims-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authorization/claims.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll review this on the next doc sweep.

**Comment by Perustaja** [comment]
Currently, the idea of a claim is vague and, honestly, not very useful. When the docs say explicitly it is an identifier and not related to a specific action, it is confusing. For instance, we have RBAC, but how do we handle permissions, which are very practical?

Everyone I see working around permissions just uses claims with key "permission" or a kvp essentially explaining a permission such as canDoX or manageY in one form or another. I think the documentation should explain claims in a more open-ended way, maybe explaining how to model finely-grained permissions with them.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
