### ISSUE TITLE
Need to get claims when logging in to Azure B2C

### ISSUE THREAD

**Issue by simonziegler** [dotnet/AspNetCore.Docs#14304]
Hi, I am building a Blazor Server app (preview9) and need to use Azure Active Directory B2C for authentication. I have started with your template project, and have made sure that the token returned from B2C includes First Name, Given Name and a couple of other properties (viewed from https://jwt.ms). I cannot however work out how to access these properties from the code in the LoginDisplay.razor file. Do you know how to get that information?

Thanks,    Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Cross-linking a few existing topics for authn/authz ...

* [Social login provider tokens+claims for Blazor auth](https://github.com/aspnet/AspNetCore.Docs/issues/15160)
* [Google Social login provider for Blazor](https://github.com/aspnet/AspNetCore.Docs/issues/15325)
