### ISSUE TITLE
Apache when using server-side hosting (websockets error)

### ISSUE THREAD

**Issue by rpc-scandinavia** [dotnet/AspNetCore.Docs#14323]
I am playing with a aspnet-core application that can run either as server-side (Razor) or client-side (WASM/Blazor). It is hosted behind a Apache2 server on Debian Linux.

In your documentation you mention this Apache2 configuration:

```
	ProxyPreserveHost On
	ProxyPass / http://127.0.0.1:5000/
	ProxyPassReverse / http://127.0.0.1:5000/
```

However, this is not enough when running server-side because of the Signal-R web-socket connection. So my configuration is like this:

```
	# Redirect all traffic to the Kestrel server.
	ProxyRequests		On
	ProxyPreserveHost	On

	ProxyPassMatch		^/_blazor/(.*)	http://localhost:5000/_blazor/$1
	ProxyPass		/_blazor	ws://localhost:5000/_blazor
	ProxyPass		/		http://localhost:5000/
	ProxyPassReverse	/		http://localhost:5000/
```

With, among others, the following modules enabled:

```
	a2enmod		proxy
	a2enmod		proxy_wstunnel
```

Without this, the server-side hosting, generates some errors in the web browser console. Some are:

Firefox can’t establish a connection to the server at ws://int-addr.dk/_blazor?id=XXX.
Error: Failed to start the transport 'WebSockets': Error: There was an error with the transport.
Error: Failed to start the transport 'LongPolling': TypeError: this.transport is undefined
Error: Unable to connect to the server with any of the available transports. WebSockets failed
Error: Cannot send data if the connection is not in the 'Connected' State.

Thank you.
René Paw Christensen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **shboyer**

**Comment by mkArtakMSFT** [comment]
Thanks for letting us know, @rpc-scandinavia.
Would you be willing to sending us a PR for this?

**Comment by rpc-scandinavia** [comment]
@mkArtakMSFT, what is a PR and what should I send ?

**Comment by guardrex** [comment]
Recommend that we cover common scenarios that apply to both WebAssembly and Server in the *Host and deploy* overview topic. @rpc-scandinavia, you can create a new section there or I'll take care of it based on your opening remarks here.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/

**Comment by rpc-scandinavia** [comment]
Ok @guardrex, I submitted this: https://github.com/aspnet/AspNetCore.Docs/commit/6120deace6d36983e0c392305d4a5d08cf459d40

**Comment by guardrex** [comment]
You can't commit directly to master that way. Edit the live topic and submit the PR from there ... follow the prompts; or if you want me to handle it, I'll take your update and submit it.

**Comment by rpc-scandinavia** [comment]
Ok, you are welcome to make the update.

I clicked "Edit" at the top of the page (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/?view=aspnetcore-3.1&tabs=visual-studio)

Then I clicked the pencil to "Edit this in my fork" on this page (https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/index.md)

And finally edited and clicked "Propose file change" to make the pull request.

**Comment by guardrex** [comment]
Hummm ... that's to `master` on your fork, but we need the PR to hit `master` here.

I'll take care of it. No worries. I'll ping u on the PR.

**Comment by guardrex** [comment]
I'm on a *brain fry* 😵 tonight tho ....... I'll get back to this asap. It might be a day or two.
