### ISSUE TITLE
HTTP API with JSON doesn't exist (work-around)

### ISSUE THREAD

**Issue by thangchung** [dotnet/AspNetCore.Docs#14377]
About "A formal specification for HTTP API with JSON doesn't exist", we might put the application gateway like Ocelot in front of gRPC Services to trans-code it (HTTP + JSON -&gt; gRPC + Protobuf), I did it at https://github.com/thangchung/GrpcJsonTranscoder. Or otherwise we can use Envoy proxy to trans-code it like https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/filter/http/transcoder.proto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8321e4f0-1d12-c4cd-76af-a7df9ca2e732
* Version Independent ID: c9e71059-2e31-3de3-eb26-0946cfe0ec3d
* Content: [Comparing gRPC services with HTTP APIs](https://docs.microsoft.com/en-us/aspnet/core/grpc/comparison?view=aspnetcore-3.0&WT.mc_id=ondotnet-c9-cxa#feedback)
* Content Source: [aspnetcore/grpc/comparison.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/comparison.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by anurse** [comment]
I don't think I understand this question. The doc is clarifying that one difference between gRPC and HTTP APIs is that there is no consistent "spec" for what an HTTP API looks like, every app does it differently. A gRPC API does have a more formal spec that's consistent between apps. Certainly you *can* build a transcoder like you suggest to create a more consistent HTTP API in front of gRPC but it doesn't really change the assertion made in the doc.

**Comment by Atreyu79** [comment]
What about JSON:API?  https://jsonapi.org/  

It's a formal specification for "HTTP API with JSON" (assuming this means "REST").  We've used it with great success, choosing it over GraphQL.

**Comment by anurse** [comment]
Yeah, formats exist but there isn't a single authoritative one like gRPC has (one is defined right in the spec).

**Comment by thangchung** [comment]
I have seen that Microsoft is starting to working on this item at https://github.com/aspnet/AspLabs/blob/master/src/GrpcHttpApi/README.md

**Comment by JamesNK** [comment]
There are now links to gRPC-Web and gRPC HTTP API on this page.
