### ISSUE TITLE
SignalR client feature matrix

### ISSUE THREAD

**Issue by bradygaster** [dotnet/AspNetCore.Docs#14378]
Create a doc article that represents the client feature matrix of all the SignalR clients. This issue should be edited to come up with the full list of feature we want to list. 

@tdykstra linked us to [this article](https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings#supported-bindings) as an example of such a check-matrix. 

We should agree on the list of features in this issue as our MVP list. Then @bradygaster will write the first pass at the doc article and enable everyone to contribute to it. 

* Client-to-server streaming
* Server-to-client streaming
* Opt-in automatic reconnect
* Supported Transports
* Supported Hub Protocols
* […you help me add to this list, folks…]

**Comment by bradygaster** [comment]
created #14394 cc @davidfowl @halter73 @anurse @mikaelm12 @scottaddie - pinging team to come up with a few more line items to add to the matrix.

**Comment by bradygaster** [comment]
note i did not ping @BrennanConroy as he'd already started commenting b/c he is that is awesome

**Comment by BrennanConroy** [comment]
This is done, https://docs.microsoft.com/aspnet/core/signalr/client-features?view=aspnetcore-3.1#feature-distribution
