### ISSUE TITLE
Update : Migrate from ASP.NET to ASP.NET Core for 3.x

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#14386]
Update the entire ASP.NET-to-ASP.NET Core doc series for 3.x.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
moved to #21570
