### ISSUE TITLE
Microsoft api versioning swagger autogen

### ISSUE THREAD

**Issue by jimasp** [dotnet/AspNetCore.Docs#14407]
Just a comment - I find it odd there is no mention of the autogen provided via the Microsoft api versioning package? 
https://github.com/microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core Web API help pages with Swagger / OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@thangchung please review.

**Comment by thangchung** [comment]
Hi @Rick-Anderson What can I do in this case?
