### ISSUE TITLE
Add Recommendation about Lifetime

### ISSUE THREAD

**Issue by rposener** [dotnet/AspNetCore.Docs#14410]
If we are registering a Client with a DI framework, is there any recommended lifetime?  Should it be Singleton (will it safely reconnect and such)?  Or should we re-resolve it per scope or just make it transient resolution when needed - perhaps the static Channel is managing a persistent connection such that we don't need to worry about these details?  Some information on this page would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by polygreg** [comment]
I found the answers here https://docs.microsoft.com/en-gb/aspnet/core/grpc/clientfactory?view=aspnetcore-3.0

**Comment by JamesNK** [comment]
Using client factory is the answer here.
