### ISSUE TITLE
Avoiding hard-coded strings: needs Controller example

### ISSUE THREAD

**Issue by clintmayer** [dotnet/AspNetCore.Docs#14443]
Right now there's only an example using nameof in Razor views. There should also be an example using typeof when returning ViewComponent from a Controller method. I learned this from: https://visualstudiomagazine.com/articles/2018/02/01/invoking-view-components.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/81768018-a3e50080-9475-11ea-8416-e84b8852b582.png)

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan this might be fun
