### ISSUE TITLE
React to Ctrl+C UseConsoleLifetime issue with VSC

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#14489]
React to https://github.com/microsoft/vscode/issues/81322 after a solution is available. The sample app should run in VSC's `externalTerminal` and respond to `Ctrl+C` to shutdown the app, as it did in prior versions of .NET Core with prior versions of VSC/OmniSharp/debugger. In the meantime, the sample README instructs the dev to run the app in a command shell with `dotnet run`.

Update (9/23): This is under investigation by a VSC 🐈.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
