### ISSUE TITLE
Memory issue in examples with retrieving collections

### ISSUE THREAD

**Issue by komanton** [dotnet/AspNetCore.Docs#14528]
In the current page, I see three examples which use the following construction:

`return View(await students.AsNoTracking().ToListAsync());`

As far as I understood such construction is not correct in case of scaling an application due to improper memory consumption and may lead developers who read this doc to choose the wrong way in the implementation of their endpoints. 

In details: ToListAsync - produces 'in-memory' buffers which have no constant size. Because the size depends on the number of rows which are retrieved from DB. So, if you multiply the number of requests and buffer without constant size, you may exceed the memory limitation of a container.

To sum up, I would suggest revisiting such examples to fix a memory issue.

Please, let me know if you require more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu  I'm going to add a caveat to this doc:

The preceding code works for for small data sets. A real app should limit the number of rows returned.

**Comment by dougbu** [comment]
@Rick-Anderson that sounds fine. I suggest the caveat should mention settings that make `ToListAsync()` and similar safe.

Model binding should limit collections to reasonable sizes e.g. using `MvcOptions.DefaultMaxModelBindingCollectionSize`. @ajcvickers does EF Core have limits on returned data sets that would be applicable here?

**Comment by komanton** [comment]
@Rick-Anderson I expected that examples will be modified to use the new feature: async enumerable, something like this:

`return View(await students.AsNoTracking().ToEnumetableAsync());`

I saw this method in the latest version of EF.

I am not sure that some limitations for the result sets may help in this case. Because even 10 records in results will appear like gigabytes of ram at scaling on thousands of requests.

The idea with enumerable is having a memory buffer for only one record at any moment. Because it will be work like streaming without huge buffers.

**Comment by Rick-Anderson** [comment]
@komanton  can you send me a link to `ToEnumetableAsync`

**Comment by komanton** [comment]
@Rick-Anderson The correct name of this method is AsAsyncEnumerable

I saw documentation for it here https://github.com/aspnet/EntityFrameworkCore/blob/2c341ee6cb9721fdaedbe3cb3b302c8b7a3fe008/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2808

**Comment by Rick-Anderson** [comment]
@ajcvickers  should we replace the scaffolded code
`return View(await students.AsNoTracking().ToListAsync());`

with
`return View(await students.AsNoTracking().AsAsyncEnumerable());`

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd @roji Thoughts on this?

**Comment by AndriySvyryd** [comment]
Sounds like a reasonable suggestion, though to really fix the issue `.Take(DefaultMaxModelBindingCollectionSize)` should probably be added.

**Comment by roji** [comment]
I don't think it's possible to await an IAsyncEnumerable. However, unless I'm mistaken ASP.NET's `View()` should be able to accept an IAsyncEnumerable directly (at the very least it seems to allow this [in web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#return-ienumerablet-or-iasyncenumerablet), which is ideal).

There's one more important point here - whether the IAsyncEnumerable is going to be enumerated multiple times by the view. If it is, it's probably better to do ToListAsync and pass that as the model, although everything depends on the actual amount of data involved. In general, a web page shouldn't be loading an arbitrary number of rows - some sort of paging/limiting is typically involved, in which case ToListAsync should usually be fine.

So there may not be one definite answer here :) The above may be too much complexity for introductory examples, but I'd say that in the general case ToListAsync may be safer.

**Comment by smitpatel** [comment]
https://github.com/aspnet/EntityFrameworkCore/issues/5089

**Comment by komanton** [comment]
> I don't think it's possible to await an IAsyncEnumerable. However, unless I'm mistaken ASP.NET's `View()` should be able to accept an IAsyncEnumerable directly (at the very least it seems to allow this [in web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#return-ienumerablet-or-iasyncenumerablet), which is ideal).
> 
> There's one more important point here - whether the IAsyncEnumerable is going to be enumerated multiple times by the view. If it is, it's probably better to do `ToListAsync` and pass that as the model, although everything depends on the actual amount of data involved. In general, a web page shouldn't be loading an arbitrary number of rows - some sort of paging/limiting is typically involved, in which case `ToListAsync ` should usually be fine.
> 
> So there may not be one definite answer here :) The above may be too much complexity for introductory examples, but I'd say that in the general case `ToListAsync ` may be safer.

@roji Thanks for the detailed explanations. Looks like this doc: [in web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1#return-ienumerablet-or-iasyncenumerablet) is what I have expected to see in the documentation actually. I have no questions at his moment. And, probably, this issue may be closed.

**Comment by Rick-Anderson** [comment]
Need to leave it open to warn about number of rows returned.

**Comment by ajcvickers** [comment]
@rynowak I think it would be useful to align understanding between EF and MVC here around the best practices for using IAsyncEnumerable. Would it be worth putting something on the calendar for the new year, or do you think we can come to a conclusion here?

**Comment by Rick-Anderson** [comment]
@rynowak I think it would be useful to align understanding between EF and MVC here around the best practices for using IAsyncEnumerable. Would it be worth putting something on the calendar for the new year, or do you think we can come to a conclusion here?

**Comment by Rick-Anderson** [comment]
@JeremyLikness @ajcvickers  I'll be updating the [RP/EF](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio) and I'd like to include this. @mkArtakMSFT  who's the right person now that RyanNwak is gone?

**Comment by Rick-Anderson** [comment]
> @rynowak I think it would be useful to align understanding between EF and MVC here around the best practices for using IAsyncEnumerable. Would it be worth putting something on the calendar for the new year, or do you think we can come to a conclusion here?

**Comment by Rick-Anderson** [comment]
Fixed in #19922 at https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#performance-considerations in
