### ISSUE TITLE
Built-in Tag Helpers - ToC inconsistency

### ISSUE THREAD

**Issue by rschindhelm** [dotnet/AspNetCore.Docs#14583]
There are some inconsistencies on the tag helpers documentation page.

1. Inconsistency regarding how the links are represented. Most of them are noted as in `<name> Tag Helper` with the exception of the `FormActionTagHelper`, `LinkTagHelper` and `ScriptTagHelper` links.
1. The following tag helpers are missing from the "Built-in Tag Helpers" section of the table of contents:
    * Form Action Tag Helper (see below)
    * Link Tag Helper
    * Partial Tag Helper
    * Script Tag Helper
1. Please provide some clarity if the `Form Tag Helper` and `Form Action Tag Helper` share a common or separate concept and wether it should be listed as an individual entry in the ToC (marked yellow).
1. Also, the `FormActionTagHelper` seems to be duplicate (marked red).

![image](https://user-images.githubusercontent.com/15197864/65602805-cd175600-dfa4-11e9-9110-c67ff95b3f67.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1692705d-02cc-f371-bae5-580380d2e877
* Version Independent ID: ec9bb36b-d744-5c66-8d60-b55ee2c7007a
* Content: [ASP.NET Core built-in Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63638](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63638)

**Comment by Rick-Anderson** [comment]
@rschindhelm  good info. Hopefully we can get some help fixing this.

**Comment by Rick-Anderson** [comment]
cc @tdykstra
