### ISSUE TITLE
Potential account/mount problem for Windows using Linux containers

### ISSUE THREAD

**Issue by tarwn** [dotnet/AspNetCore.Docs#14632]
If you are running with an AzureAD account, docker cannot mount to the local drive with those credentials, so the certificate will not be shared/accessible to the Docker image. I chased this myself for close to a day, thinking I had entered paths wrong, generated the certificate wrong, etc. Unfortunately, the only workaround I've found for this specific issue is to create a local account (which some folks cannot do and has implications for folks in regulated environments).

Reference: https://github.com/docker/for-win/issues/132

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tarwn** [comment]
Here's another reference: https://github.com/docker/for-win/issues/1352

**Comment by sig9** [comment]
I believe this is resolved with Docker 2.2.0.0.  See release notes https://docs.docker.com/docker-for-windows/release-notes/   and https://www.docker.com/blog/new-filesharing-implementation-in-docker-desktop-windows/
FWIW I also experienced this challenging problem and several other incompatible windows features when using AzureAD accounts.

**Comment by Rick-Anderson** [comment]
Closing due to

> I believe this is resolved with Docker 2.2.0.0.

**Comment by LeeRuns** [comment]
For the next person who finds this issue, does azure ad enable this to work?
What was the result?
