### ISSUE TITLE
ef commands mentioned but not used

### ISSUE THREAD

**Issue by boomalator** [dotnet/AspNetCore.Docs#14638]
The paragraphs starting with "The ef migrations add InitialCreate command ..." refer to ef commands that are not directly used. I assume Add-Migration uses ef, but that's not what is typed. I suggest either explaining that the PMC commands call ef or adjusting the text to reflect the commands used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by boomalator** [comment]
Note that the content of these paragraphs is repeated almost verbatim slightly further in the tutorial. This may just be a cut-paste-move typo-error.

**Comment by Rick-Anderson** [comment]
> Note that the content of these paragraphs is repeated almost verbatim slightly further in the tutorial.

I don't see that. Can you paste a screen shot?

select the VSC or VS Mac tab to see why it's 
`dotnet ef migrations add InitialCreate`

I'll get this fixed.

**Comment by boomalator** [comment]
![image](https://user-images.githubusercontent.com/17992669/65713312-28555100-e056-11e9-9efb-0438a5bcf105.png)

**Comment by boomalator** [comment]
Screenshot -- 1 (commands used) does not match 2.
However, 1 does match 3.
2 and 3 are virtually identical.

**Comment by Rick-Anderson** [comment]
@boomalator thanks

**Comment by Rick-Anderson** [comment]
Moved to #15941
