### ISSUE TITLE
Error while Adding Reference to gRPC service in Class Library (.NET Standard 2.0)

### ISSUE THREAD

**Issue by rupeshtech** [dotnet/AspNetCore.Docs#14702]
# gRPC service

I have created a sample (default) gRPC service with .NET Core 3.0

# Issue

When trying to add service reference in a client (C# class library **.netstandard2.0**) **gives error** ,
Where as  when trying to add service reference in a client (C# class library **.netcoreapp3.0**) is **successfull** 

# Issue description

When trying to add service reference in a client (C# class library **.netstandard2.0**) **gives error** ,
Where as  when trying to add service reference in a client (C# class library **.netcoreapp3.0**) is **successfull** 

![image](https://user-images.githubusercontent.com/24852402/65857528-54c5e180-e364-11e9-9f8d-1bd0768a1cb2.png)

# Service configuration
project type= gRPC service with netcoreapp3.0
`<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Protos\greet.proto" GrpcServices="Server" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.23.1" />
  </ItemGroup>
</Project>`

# Service

Service is deafult service which is created while creating a gRPCS project thru Visual studio 2019
`syntax = "proto3";
option csharp_namespace = "Testmewe";
package Greet;
// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply);
}
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}
// The response message containing the greetings.
message HelloReply {
  string message = 1;
}`

# Client configuration - Which Gives Error while adding reference to gRPC service
project type: C# class library  with netstandard2.0
`<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>`

# Client configuration - Which is successfull while adding reference to gRPC service
project type: C# class library with netcoreapp3.0
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>`

**Comment by JamesNK** [comment]
netstandard20 can't reference netcoreapp31.
