### ISSUE TITLE
How to set a global fallback route?

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/AspNetCore.Docs#14733]
A very basic demand is to set a global fallback route for returning a custom "not found" response, and also log request details. This document does not explain how to perform that. After reading this doc, my intuition is to use the `Order` attribute like this:

```
        [Route("{**unused}", Order = 32767)]
        public IHttpActionResult ReturnNotFound(string unused)
        {
            ...
        }
```

But this doesn't seem to work in all cases, and the document clearly advocates against that when it says "Avoid depending on `order`". Please update the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #13871

**Comment by Rick-Anderson** [comment]
@rynowak  great question, How to set a global fallback route?

**Comment by Rick-Anderson** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0#default-problem-details-response
