### ISSUE TITLE
SQLite requires Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by klinge** [dotnet/AspNetCore.Docs#14740]
Trying to follow this guide after updating to dotnet core 3.0. Everything works well up to the scaffolding of the register/login/logout pages. 

To my best knowledge I followed the previous steps as described. But when running the command
`dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout"`

I get the error message: 
```
It was not possible to find any compatible framework version
The specified framework Microsoft.NETCore.App, version 2.1.3 was not found.
  - The following frameworks were found:
      3.0.0 at [C:\dev\dotnet-sdk\share
```
In my csproj there are no references (direct) to 2.1.3 versions of any of the included packges.
```
 <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UserSecretsId>aspnet-IdentityApp-XXX</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0" />
  </ItemGroup>
```
What is needed to get the aspnet-codegenerator scaffolding to run properly? 

Best regards, Johan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Try nuking the package cache: `dotnet nuget locals --clear all` ... rebuild the project ... then scaffold again.

**Comment by guardrex** [comment]
... and silly ? but should ask ... you did get a good install of the 3.0 SDK, right?

**Comment by klinge** [comment]
Tried clearing the package cache as per your suggestion and rebuilding. Still get the same error message on scaffolding. 

Re "good install" - I installed the latest dotnet 3 sdk via the zip file download. But I assume everything is ok with the SDK since I can build/run the project.

**Comment by guardrex** [comment]
Ok .... open this over at https://github.com/aspnet/Scaffolding/issues for investigation.

**Comment by klinge** [comment]
Thanks. I solved the issue. At some previous stage I had installed a global version of the dotnet-aspnet-codegenerator tool which needed to be updated to 3.0 to make scaffolding work.

**Comment by guardrex** [comment]
Ah ... very good. I'm glad it had a happy ending.

**Comment by klinge** [comment]
Npw that scaffolding is running - I now get another error message that says: 
`Please install the following packages to your project for scaffolding identity: Microsoft.EntityFrameworkCore.SqlServer`

This project uses SQLite and there should be no need for SqlServer.. Should I report this over at aspnet/scaffolding?

**Comment by guardrex** [comment]
That was one of the packages that was removed from the `App` package. The scaffolder may require it in the project. @Rick-Anderson might know. He'll be on here sometime this morning. I'll re-open the issue because if that package is required in the project, the [Scaffold Identity topic](https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity) doesn't say that such is the case.

**Comment by guardrex** [comment]
... but it does say that EF Core Migrations are required. https://docs.microsoft.com/ef/core/managing-schemas/migrations/ ... and that seems likely to require that package. If the EF Core package is added, does that error message go away? `Microsoft.EntityFrameworkCore`

**Comment by klinge** [comment]
I did a `dotnet add package Microsoft.EntityFrameworkCore` for my project. Still getting the same error message when running scaffolding..

**Comment by klinge** [comment]
Full error message for reference: 
```
PS C:\dev\dotnet_code\IdentityApp> dotnet aspnet-codegenerator identity -dc IdentityApp.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout"
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
Please install the following packages to your project for scaffolding identity: Microsoft.EntityFrameworkCore.SqlServer
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

**Comment by Rick-Anderson** [comment]
Good error message. Follow the instructions.

**Comment by klinge** [comment]
OK, sure installing `Microsoft.EntityFrameworkCore.SqlServer` fixes the problem. But then the need to add this package should be added to the guide.. At least to me it's not obvious that you need the EFCore.SqlServer package for a SQLite project..

**Comment by lol768** [comment]
This was also unintuitive to me.

**Comment by Rick-Anderson** [comment]
Moved to Moved to #16230

**Comment by dkja** [comment]
You shold use --useSqLite option

**Comment by ehteshamshahzad** [comment]
Thank you @dkja

**Comment by meech-ward** [comment]
> Good error message. Follow the instructions.

@Rick-Anderson This seemed like a good thread until you joined, left an unhelpful message, and closed the issue. 

Of course, adding `Microsoft.EntityFrameworkCore.SqlServer` fixes the issue, but why do I need to add a SqlServer package to my SQLite, MySQL, or PostgreSQL project? That makes no Sense! 

I am using `Pomelo.EntityFrameworkCore.MySql` and I still need to install `Microsoft.EntityFrameworkCore.SqlServer` just to get codegenerator to work?

@Rick-Anderson Could you please tell me why this is the case, or direct me to the documentation that states why this is the case?

**Comment by pierreantoine-cheron** [comment]
@meech-ward I have the exact same problem, did you get a solution ?
