### ISSUE TITLE
ReplaceOne() method not working properly on .Net Core 3.0

### ISSUE THREAD

**Issue by fabioqueiroz** [dotnet/AspNetCore.Docs#14829]
Hi,

I'm building an api and realized that the ReplaceOne() method you used in the CRUD operations sections is not working as it's supposed to in .Net Core 3.0.

When you call this method as below

_books.ReplaceOne(book => book.Id == id, bookIn);

the lambda expression is not picking up the attributes of the entity (such as the "Id" in this case). 

I needed to downgrade to 2.2 in order for make it work correctly. Could you please check this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by safwendr** [comment]
hi, i have the same issue and i used the .NET CORE 2.2

**Comment by Rick-Anderson** [comment]
Moved to #16196

**Comment by serpent5** [comment]
Fixed in #24126.
