### ISSUE TITLE
Missing guidance on supported scenarios for SSL offloading

### ISSUE THREAD

**Issue by trondhindenes** [dotnet/AspNetCore.Docs#14821]
We usually configure services so that the asp.net core app itself doesnt handle ssl termination, its handled by a load balancer or some reverse proxy. This means that altho the server listens for http (unencrypted) traffic, a client might still send requests on https (encrypted).
So:
client (https) --&gt; rev proxy (https to http) --&gt; server (http)

Most modern proxies will then send the `X-Forwarded-Proto` as an indication of the original protocol which the application (asp.net) can then use for whatever.

This is a super-common scenario, as it (among other) removes the administrative burden of placing ssl certs inside the container running the server app. It would be good if this page documented whether or not this is a supported scenario. It seems to me that it is assumed that the server "knows" the protocol, and imho that is rarely the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
That's beyond the scope of these gRPC docs. However, I'll mention TLS termination in the security doc.
