### ISSUE TITLE
Prerendering parameters guidance

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#14878]
Filing this issue to track adding guidance on how to be successful when passing parameters to server-side blazor apps. We want to describe:
* Implementation and limits.
* How to change your app when you hit these limits.
* Guidance for specific scenarios
  * Rendering a top level component.
  * Rendering multiple components.

**Comment by guardrex** [comment]
I'm going to cross-link our other prerendering-related issues in case any should be worked together ...

* [Prerendering with reconnect](https://github.com/aspnet/AspNetCore.Docs/issues/12854) &ndash; DR to provide content.
* [Add a doc talking about issues with connectedness and prerendering](https://github.com/aspnet/AspNetCore.Docs/issues/14182) &ndash; RN to provide content.

**Comment by guardrex** [comment]
@javiercn This issue has been here for over a year now. Is it still viable for work given the added content over the last year on prerendering+parameters?

Most of the coverage is in the Component Tag Helper doc ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-5.0

... with bits in the *Prerendering and integration* topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0&pivots=server

btw - The *Prerendering and integration* topic had to be merged without fully polished coverage or perhaps the best layout of coverage because we needed the updates for 5.0. I'll return to it before the ⛄ *holidays* 🎁. We might end up organizing all of the prerendering and integration content differently on the next pass. However, that work is covered by another issue ... it doesn't need to be tracked by this issue.

Also, Ryan opened ...

Add a doc talking about issues with connectedness and prerendering https://github.com/dotnet/AspNetCore.Docs/issues/14182

... also well over a year ago. Can that be closed?

**Comment by javiercn** [comment]
Yes, this is still also very much relevant, some of the things too for Blazor wasm.

For example, I would like a section indicating the types of parameters that can be passed to the component:
* Parameters can't be generic
* Parameters must be serializable.
* For serverside blazor:
  * They can't exceed a combined total serialized size of I believe around 20K which approximates the size of a signalr message.
  * When you run into this, you need to use a memory cache or similar, add them to a cache and pass in the key to the cache instead to retrieve them.

* We need to talk about the limitations when you are rendering multiple components, like "let's not have 5 components each with its own router" and so on.
  * It'll be good to give an example on how we can use client-side routing here to implement a wizard or something similar alongside other components rendered on the page.

**Comment by guardrex** [comment]
> Parameters can't be generic

> Parameters must be serializable.

Those two are already covered. :+1:

Bullet 3 ... I can add that with the example. That's not too hard to work out. We can iron out any *RexHacks* 🙈 on the PR later.

The last bullet ... 4 ... that one would be a section+code for you to provide.

**Comment by guardrex** [comment]
What about Ryan's issue ... can that be closed?

#14182

**Comment by bradygaster** [comment]
@guardrex - anything left on this one?

**Comment by guardrex** [comment]
@bradygaster ... I'll take a look, but I'm OOF at the moment. I'll ping u back here no later than first thing tomorrow morning.

**Comment by guardrex** [comment]
@bradygaster ... I don't think bullet points 3 and 4 of https://github.com/dotnet/AspNetCore.Docs/issues/14878#issuecomment-726731323 were addressed.

### Bullet 3

I haven't worked with a "memory cache or similar" approach (bullet 3B) for the bullet 3A scenario. In general, it sounds like bullet 3A refers to SignalR's buffer and message size limit of 32K, as described in https://docs.microsoft.com/aspnet/core/signalr/security#buffer-management.

Question 1: Should that SignalR security section be cross-linked into the *Component parameters* section of the *Components* overview topic for Blazor Server?

Question 2: Which of the following would be best for bullet 3B? I hope for either of the last two given the workload here 😅 ...

* Do I need to work out a "memory cache or similar" code example for readers?
* Are you aware of an existing doc section/example/sample demo that we can cross-link for it?
* Can we just tell readers that they need to implement a solution like that (I'll knock up some text based on Javier's remark) and leave it to them to work out on their own?

### Bullet 4

Bullet 4 sounds like it would be resolved using dynamically-rendered components ( https://docs.microsoft.com/aspnet/core/blazor/components/dynamiccomponent ). If so, then I don't think we need to do anything for it. That topic's example (Rocket Lab 🚀, etc.) isn't a wizard-type of use case, but it's fairly close. I think most devs could create a wizard-type experience based on the DDL example there.

**Comment by javiercn** [comment]
I don't think we need to document anything additional here, since we haven't had customer reports about this, I'm happy to leave the docs as they are.

**Comment by jaryn-kubik** [comment]
Just spent a day debugging Bullet 3.
Would've been nice to have this mentioned in the docs somewhere as it gives absolutely no indication of what went wrong, no exceptions anywhere, the site just doesn't load.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0#blazor-and-shared-state
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#blazor-and-shared-state

Those two sections both recommend the approach of passing data to the root component through a parameter, even just a warning about the limits without any code or examples would be sufficient.
