### ISSUE TITLE
Microsoft.AspNetCore.Mvc.WebApiCompatShim library

### ISSUE THREAD

**Issue by serkanyazicioglu** [dotnet/AspNetCore.Docs#14872]
Since Microsoft.AspNetCore.Mvc.WebApiCompatShim is not available for .Net Core 3.0 this part should be updated or removed from this page. It's misleading right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-3.0)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
* https://github.com/aspnet/AspNetCore/issues/4926
* The topic looks to need 3.0 updates.

cc: @scottaddie
