### ISSUE TITLE
Insufficient clarity about calling an instance from JS

### ISSUE THREAD

**Issue by HughPH** [dotnet/AspNetCore.Docs#14879]
This document is very confusing for me as a C# developer who left JavaScript behind 10 years ago.

Could use a section describing how DotNetObjectReference could be used to pass an instance of a Blazor component to JavaScript (and therefore make its methods available) - or pass an injected singleton, for example.

It was not obvious to me that .then is synonymous with .ContinueWith and .ContinueWith is not ideal in BlazorWASM. A more simple JavaScript example would be welcome, it looks like an attempt has been made to cram as many different use cases as possible into one example, and it reads like insanity - creating a whole class to be a DotNetObjectReference factory to then call JavaScript to call the object created in that factory, which is a separate class to any Blazor pages.

(In the real world, on Client-Side Blazor, I found it simplest to create a static method on the Blazor component and have that call a static Action which is set to the instance method I actually want to call by the component's OnInitialized method - which is great so long as I only have one instance of the Blazor component)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by HughPH** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/14972

**Comment by guardrex** [comment]
@HughPH Are you re-opening a new issue with the same content as on #14972?

**Comment by guardrex** [comment]
Close the other one if you're providing more/new information for the same issue.

**Comment by guardrex** [comment]
Sorry ... didn't see that it was a different community member. I'll look and close it as a duplicate if that's the case.

**Comment by HughPH** [comment]
I think they are _associated_ but not duplicates of one another. Definitely worth looking at together.

**Comment by guardrex** [comment]
Ok ... cool. Thanks.

**Comment by HughPH** [comment]
Thanks for jumping on it so fast!

**Comment by guardrex** [comment]
We should be getting a round of triage from engineering on **_all_** of these issues fairly soon. I don't have an ETA, but getting past the 3.0 release was a big milestone.

**Comment by guardrex** [comment]
@mkArtakMSFT I'm taking a look at rolling this into the JS interop topic split updates today, which should be up for review by EOD or first thing Wednesday morning. Let's go over the pattern and discuss further. Consider this example for discussion ...

*wwwroot/index.html*:

```javascript
<script>
    function updateMessageCallerJS() {
        DotNet.invokeMethodAsync('BlazorClient31', 'UpdateMessageCaller');
    }
</script>
```

*Pages/MyTest.razor*:

```razor
@page "/mytest"

<h1>My Test</h1>

<p>
    Message: @_message
</p>

<p>
    <button onclick="updateMessageCallerJS()">Do IT!</button>
</p>

@code {
    private static Action _action;
    private string _message = "Select the button.";

    protected override void OnInitialized()
    {
        _action = UpdateMessage;
    }

    private void UpdateMessage()
    {
        _message = "UpdateMessage Called!";
        StateHasChanged();
    }

    [JSInvokable]
    public static void UpdateMessageCaller()
    {
        _action.Invoke();
    }
}
```

1. Is this pattern acceptable/reasonable?
1. Name the *gotchas* (e.g., explain out a bit more "which is great so long as I only have one instance of the Blazor component").
1. Is this example (or one close to it, since I'll probably mod it a bit for the PR) fairly close to what you'd like to show?
1. Prioritize this pattern relative to the [current coverage (links to 'Instance method call' section)](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#instance-method-call): Should this pattern be shown first (i.e., a new first bullet and example there)?

**Comment by shashikantx** [comment]
This is fairly easy to follow example to understand how to call a static method of a component to update UI, which is alright, as you pointed out, as long as is only component, but in case of list of same components there is no example so far.

I ran into that issue few times, regarding calling a promise and updating list item on complete of promise. I tried many ways including passing component as object `DotNetObjectReference('this')`. Every time it failed to update all the list items component but one. So I came up with this solution, which is hybrid of your code and **Instance method call**.

Maybe you can extend your example like this.

## Index Page
``` JS
<script>
        window.Blazor31 = {
            updateMessageCallerJS: function (helperRef) {
                helperRef.invokeMethod("UpdateMessageCaller");
            }
        }
</script>
```

## Index Razor
``` Razor
@page "/"

<h3>List Items</h3>

<div>
    <InstanceCall.Pages.components.ListItemComponent></InstanceCall.Pages.components.ListItemComponent>
    <InstanceCall.Pages.components.ListItemComponent></InstanceCall.Pages.components.ListItemComponent>
    <InstanceCall.Pages.components.ListItemComponent></InstanceCall.Pages.components.ListItemComponent>
    <InstanceCall.Pages.components.ListItemComponent></InstanceCall.Pages.components.ListItemComponent>
</div>
```

## ListItemComponent

``` Razor
@inject IJSRuntime JsRuntime

<h1>My Test List Item</h1>

<p>
    Message: @_message
</p>

<p>
    <button @onclick="@InteropCall">Do IT!</button>
</p>

@code {
    private static Action _action;
    private string _message = "Select the button.";

    MessageUpdateInvokeHelper messageUpdateInvokeHelper;

    protected override void OnInitialized()
    {
        _action = UpdateMessage;
        messageUpdateInvokeHelper = new MessageUpdateInvokeHelper(_action);
    }

    protected async Task InteropCall()
    {
        await JsRuntime.InvokeVoidAsync("Blazor31.updateMessageCallerJS", DotNetObjectReference.Create(messageUpdateInvokeHelper));
    }

    private void UpdateMessage()
    {
        _message = "UpdateMessage Called!";
        StateHasChanged();
    }

}
```

## MessageUpdateInvokeHelper
``` C#
public class MessageUpdateInvokeHelper
    {
        Action _action;

        public MessageUpdateInvokeHelper(Action _action)
        {
            this._action = _action;
        }

        [JSInvokable]
        public void UpdateMessageCaller()
        {
            _action.Invoke();
        }
    }
```


I find this case to be more common in cases of web development, such as waiting for promises or async JS calls results, image manipulation, or end of animation, so on.

**Comment by guardrex** [comment]
I think that would be best as an *extended example*, shown after the simple one that I put up. Also, I'd update the example a bit. There isn't a *list item* for an ordered/unordered list in the example. It would be easy to make that into a list item example.

btw -- Note that you don't need the `@` on the method now (i.e., `@onclick="InteropCall"`).

**Comment by shashikantx** [comment]
Sounds great!
