### ISSUE TITLE
Instance method call section is overly complex.

### ISSUE THREAD

**Issue by shashikantx** [dotnet/AspNetCore.Docs#14972]
It could at least have showed how to call methods from same component which doesn't take more than ten lines, which I consider is very common scenario. Calling a method from calling component after a promise is completed to show progress or maybe result. which are not possible by static methods.

But, It goes beyond that and shows how to call methods from different instances created later.

that section could've been simplified or at least be more elaborated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by HughPH** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/14879
