### ISSUE TITLE
Add examples on Custom Route Constraints

### ISSUE THREAD

**Issue by shapeh** [dotnet/AspNetCore.Docs#14998]
In this doc you include description that Custom Route Constraints can be implemented by providing something like this:

```
services.AddRouting(options =>
{
    options.ConstraintMap.Add("customName", typeof(MyCustomConstraint));
});
```

1) How do you implement `MyCustomConstraint`? - an example would be nice.
2) Similarly, an example for the `SlugifyParameterTransformer` would be gold.
3) Last thing, in the doc, you write "_The endpoint routing system doesn't support IRouter-based extensibility, including inheriting from Route._" - what exactly is meant by this? Seems to me Custom Route Constraints needs to be done with something like this where `IRouter` is needed. English is not my first language, so maybe I misread this:

```
public bool Match(HttpContext httpContext, IRouter route, string routeKey, RouteValueDictionary values, RouteDirection routeDirection) 
{
 // return a match...
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak  can you assign someone to respond?

**Comment by rynowak** [comment]
Linking to our built-in constraints is probably the simplest thing to explain this, they are pretty comprehensible. [example](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Routing/src/Constraints/GuidRouteConstraint.cs#L18)

Here's the parameter transformer example: https://github.com/aspnet/AspNetCore.Docs/blob/fe3665f5b3ab8aff2079beabbfc7241abc724587/aspnetcore/mvc/controllers/routing.md#use-a-parameter-transformer-to-customize-token-replacement

> Last thing, in the doc, you write "The endpoint routing system doesn't support IRouter-based extensibility, including inheriting from Route." - what exactly is meant by this? Seems to me Custom Route Constraints needs to be done with something like this where IRouter is needed.

It means that there's no way to inherit from `IRouter` and hook that up to the new routing system.

You can still use custom route constraints.

**Comment by Rick-Anderson** [comment]
Moved to Routing master issue #16501
