### ISSUE TITLE
.AddDefaultUI(UIFramework.Bootstrap4) problem. "UIFramework" no longer exists.

### ISSUE THREAD

**Issue by killerfrienddk** [dotnet/AspNetCore.Docs#15003]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index?view=aspnetcore-3.0&tabs=visual-studio
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.0
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-3.0
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.0
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.0

Under: Configure Microsoft Account Authentication

.AddDefaultUI(UIFramework.Bootstrap4)
"UIFramework" no longer exists.

**Comment by Rick-Anderson** [comment]
@wadepickett all these need to be updated for 3.0

**Comment by wadepickett** [comment]
Excellent, happy to work on these, thanks!

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Facebook, Google, and external provider s #16210
