### ISSUE TITLE
SignalR with background service in Core 3.0

### ISSUE THREAD

**Issue by ccosmincc** [dotnet/AspNetCore.Docs#15042]
Is there a possibility to have [this](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/signalr/background-service/sample) sample updated for Core 3 (along with the [docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-3.0) that reference it)? With the new 'Worker Service' template, WebHost has been replaced by Host and I had to install Microsoft.AspNetCore.Signalr NuGet to be able to add SignalR to the service collection, but I could not figure out how to wire up Hub endpoints, as I could not find any ApplicationBuilder, to add UseEndpoints middleware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bbb2d1c-4dfe-3faf-d4b0-65ae1146961e
* Version Independent ID: 6b203f18-adfa-3a18-183d-b124325064c3
* Content: [Host ASP.NET Core SignalR in background services](https://docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/background-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/background-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @ccosmincc ... Please use the **This Page** feedback form at the bottom of the topic. It adds metadata for issue tracking and automatically pings the author.

No worries ... I've moved this over to :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/15043

**Comment by Rick-Anderson** [comment]
@guardrex  all you need to do is copy/paste the metadata from an open or closed issue.

**Comment by TomRandles** [comment]
I also  need an example of SignalR deployed in a backend Worker Service. This article has "backend service" in its title, yet it is web centric.  Any help appreciated!

**Comment by bradygaster** [comment]
I can definitely update this article. However, I'm curious what you would like to see if the aforementioned article is "not worker/background enough." SignalR's main purpose is to send messages to the client. Would you want us to have a different client in here? Like a .NET Client? Or are you thinking of a worker-to-worker messaging implementation? If so, that's not really what SignalR is for - it's not an enterprise-grade publish-subscribe implementation. If that's what you're after, we probably should just sync up and spend some time on Teams/Skype together.

**Comment by TomRandles** [comment]
Hi,
I have since clarified the correct architecture I need with a Microsoft colleague of yours. See   [https://github.com/aspnet/SignalR-samples/issues/18](url) for details. I now have a better understanding of SignalR. I incorrectly assumed I could put the SignalR server/hub in worker service.  Perhaps this could be clarified in the docs.

**Comment by madarax64** [comment]
Hello,
I'm also trying to use SignalR in a Worker application. I have the following code in main.cs:

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace VerificationWorker
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }
}
`
I'd like to have a BackgroundService hosting a Hub (i.e acting as a server) for Javascript-based clients. Is this possible? If yes, could you tell me what nuget packages to install and how to modify the above code accordingly?
Thanks in advance
