### ISSUE TITLE
BundlerMinifier.Core 3.0 readiness?

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#15101]
` BundlerMinifier.Core` is recommended in this "3.0" page but it is broken! It still refers to ASP.Net Core 2.x!
https://github.com/madskristensen/BundlerMinifier/issues/447
https://github.com/dotnet/cli/issues/12886

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by wadepickett** [comment]
Related to issue #17372

**Comment by wadepickett** [comment]
Fixed with #17848
