### ISSUE TITLE
Add warning on "Microsoft.AspNet.WebApi.Client" still using "Newtonsoft.Json"

### ISSUE THREAD

**Issue by iRubens** [dotnet/AspNetCore.Docs#15183]
If someone is using "Microsoft.AspNet.WebApi.Client" but migrated from "JsonPropertyAttribute" (Newtonsoft.Json) to "JsonPropertynameAttribute" (System.Text.Json) the serialization property names are ignored. 
Please add a warning on the "Microsoft.AspNet.WebApi.Client" chapter that is still necessary to keep previous attributes or provide a way to change the JSON serializer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JamesNK please review and suggest an edit.

**Comment by benmccallum** [comment]
I'd love to know what the plan is here. Will `Microsoft.AspNet.WebApi.Client` swap over to System.Text.Json in v6 onwards? 

And if so, how can we make this transition smooth? I've just written some code with a dependency on `Microsoft.AspNet.WebApi.Client` so the `Newtonsoft.Json` one is transitive; so I'm guessing that'll mean when you guys shift over to `System.Text.Json` instead, `JsonProperty` won't exist anymore and manual edits will be required. But there's definitely projects I can imagine that will have `Newtonsoft.Json` still in the dependency tree and people will just forget to update their `JsonProperty` attributes.

I guess at the end of the day if it's a major version update for `Microsoft.AspNet.WebApi.Client` there just needs to be ample documentation.

**Comment by bnayae** [comment]
On .NET 6 use
`using System.Net.Http.Json;`

**Comment by bnayae** [comment]
On .NET 6 use:
`using System.Net.Http.Json;`

**Comment by benmccallum** [comment]
Further to @bnayae's comment, there was a [new package](https://www.nuget.org/packages/System.Net.Http.Json) created called `System.Net.Http.Json` that contains similar extension methods but that uses `System.Text.Json.JsonSerializer`. 

It actually targets `netstandard2.0`.

So to answer my question from above, nope, it looks like the old package is dead.
