### ISSUE TITLE
Provide examples for DTOs to prevent over-posting

### ISSUE THREAD

**Issue by mrukas** [dotnet/AspNetCore.Docs#15204]
Using DTOs should be described in this article. I know there is a small part about overposting in "Data Access", but especially for APIs there should be a concrete example of using DTOs and mapping them, with for example AutoMapper, to domain objects. It also enforces security by thinking about what properties you want to serialize to the client. This should be mentioned as best practice. In the old Web API tutorials the term DTOs was used, now only the term ViewModel is used, because its used with Razor Pages in mind.

This was in the old docs: https://docs.microsoft.com/en-us/aspnet/web-api/overview/data/using-web-api-with-entity-framework/part-5

@Rick-Anderson  edit:
When this is fixed, PR scaffolding so Web API scaffolding points to this doc and not the RP/MVC approach. See sample PR at https://github.com/aspnet/Scaffolding/pull/1241

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't want to duplicate content in other tutorials. I agree this needs a link. I'll add a link to [Overposting](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.0#overposting)

**Comment by mrukas** [comment]
I understand you concerns on duplicate content. I think it would also be useful to enhance the section about overposting a little bit. As I said above, an example for using a DTOs in a controller method for updating an entity would be awesome. 
For example: A management controller for users. Updating a user by using a UserUpdateDTO and mapping this model with AutoMapper to a user entity in database. This could be a great example to prevent overwriting a user password.

**Comment by Rick-Anderson** [comment]
For sure there will be a section on overposting.  ViewModels are  view specific.

**Comment by Rick-Anderson** [comment]
# Outline

* Add  `public string Secret{ get; set; }` to the model.
* Show 2 different approaches to preventing overposting
  * `TryUpdateModelAsync`
  * Use and `InputModel`
* Add section on overposting

@danroth27  please review outline on overposting with WebAPI tutorial

**Comment by mrukas** [comment]
May I suggest to also show an example or at least mention the possibility of automatic mapping of InputModels (DTOs) to Domain Models?!

**Comment by Kruemelkatze** [comment]
I highly +1 that.

While it may be well-known for users that migrated from older ASP.NET MVC times, more docs on that topic would be very helpful for newcomers.

**Comment by Rick-Anderson** [comment]
Proposed direction at https://github.com/Rick-Anderson/ToDoDTO
Is there a more efficient way to do this?
` public async Task<ActionResult<IEnumerable<TodoItem>>> GetTodoItems()` needs to be updated to not return the `Secret` field.

@serpent5  @tdykstra  any suggestions for more efficient code? PR's welcome

**Comment by serpent5** [comment]
Is that a private repo? It's 404ing.

**Comment by Rick-Anderson** [comment]
It was. I didn't think I could create private. It's public now.
