### ISSUE TITLE
Add Link to Strongly Typed Hubs

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/AspNetCore.Docs#15238]
In the [Inject a strongly-typed HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1#inject-a-strongly-typed-hubcontext) section, I think it would be useful to have a link to: [Strongly typed hubs](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1#strongly-typed-hubs).  

As I was reading this doc page I noticed this option and I definitely wanted to use it but I wasn't sure how to create a `Hub<T>`.

**Screenshot of the section (for quick reference):**
![image](https://user-images.githubusercontent.com/14079228/67224759-f094bb80-f3ff-11e9-9962-43459411d41c.png)

I'm happy to submit a PR but I wanted to get "approval" first.  Thoughts? 💭

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Sounds like a good addition, go for it 👍

**Comment by brcaswell** [comment]
apparently the PR was merged, and this information is present on the doc.. but it doesn't make sense without including `IChatClient` and `ChatClient` declarations.

```csharp
public interface IChatClient
{
    Task ReceiveMessage(string user, string message);
    Task ReceiveMessage(string message);
}

public class ChatHub : Hub<IChatClient>
{
    public async Task SendMessage(string user, string message)
    {
        await Clients.All.ReceiveMessage(user, message);
    }

    public Task SendMessageToCaller(string message)
    {
        return Clients.Caller.ReceiveMessage(message);
    }
}
```

**Comment by spottedmahn** [comment]
thanks @BrennanConroy!
