### ISSUE TITLE
Update HTTPS redirection port configuration for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by cremor** [dotnet/AspNetCore.Docs#15249]
I think the section "Port configuration" needs an update for ASP.NET Core 3.0. According to [this recent announcement](https://github.com/aspnet/Announcements/issues/392) ASP.NET Core 3.0 can detect the HTTPS port by default, without any additional configuration. But this section in the documentation still indicates that you have to specify the HTTPS port somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#port-configuration)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Pasting in the cross-refs for source for when this one is worked ...

* https://github.com/aspnet/AspNetCore/blob/release/3.1/src/Middleware/HttpsPolicy/src/HttpsRedirectionOptions.cs#L22-L25
* https://github.com/aspnet/AspNetCore/blob/release/3.1/src/Middleware/HttpsPolicy/src/HttpsRedirectionMiddleware.cs#L121-L125

btw - No delta between 3.0 and 3.1 for that source.

**Comment by IanKemp** [comment]
There should also be an update to the docs for <= 2.2 to indicate that **HTTPS redirection will not work at all** unless a port is _explicitly_ set, even if the default TLS port 443 is available. Thankfully t[his was fixed in 3.0](https://github.com/aspnet/Announcements/issues/392#issuecomment-550499885), presumably for sanity reasons.

**Comment by Rick-Anderson** [comment]
Moved to Enforce HTTPS Master issue #17356
