### ISSUE TITLE
Automated testing for SignalR Core

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/AspNetCore.Docs#15277]
I don't see any documentation automated testing in the SignalR Core documentation, am I missing it.

I did find a doc page for ASP.NET SignalR [here](https://docs.microsoft.com/en-us/aspnet/signalr/overview/testing-and-debugging/unit-testing-signalr-applications)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
What are you interested in testing, specifically? The actual connection and messaging activity? As in the form of a performance or benchmark test? We have a benchmarking global tool you could learn about here: https://www.nuget.org/packages/Microsoft.dotnet-signalr-benchmark/1.0.0-preview2.19521.1

**Comment by spottedmahn** [comment]
>What are you interested in testing, specifically? The actual connection and messaging activity?

Messaging activity.

At that is stage I was just researching options and learning what's available and I noticed the old version had some documentation but the new one doesn't.

**Comment by bradygaster** [comment]
@spottedmahn did the links above help you? or are you proposing we create a doc that summarizes how to use those benchmarking tools? If so I would want to work with @chenkennt and his team to get that doc initially created, then we can refine together.

**Comment by bradygaster** [comment]
I've added a tracking item for SignalR and unit testing to #23357. So I'll close this as that'll be our work list and we'll accommodate this issue with that article's creation. Thanks!
