### ISSUE TITLE
3.0 update: Mention it requires Sdk="Microsoft.NET.Sdk.Web"

### ISSUE THREAD

**Issue by Leon99** [dotnet/AspNetCore.Docs#15327]
With Sdk="Microsoft.NET.Sdk" in the csproj it doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-3.0&tabs=visual-studio#analyzers-for-web-api-conventions)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
That's not surprising.  All the 3.0 templates use `<Project Sdk="Microsoft.NET.Sdk.Web">`

**Comment by Leon99** [comment]
> That's not surprising. All the 3.0 templates use <Project Sdk="Microsoft.NET.Sdk.Web">

Does the doc mention that it requires a templated project? What about using it with a library project? Microsoft.NET.Sdk.Web is not otherwise necessary/required.

**Comment by AroglDarthu** [comment]
https://github.com/dotnet/aspnetcore/issues/14675
