### ISSUE TITLE
Add a section about route precedence

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#15349]
There doesn't seem to be an explanation about route precedence an ordering works. This is a fundamental routing concept that should be covered as part of this doc.

Specifically:
* How the system determines route precedence.
* How you can change how routes are evaluated using the route order.

/cc: @rynowak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#routing-basics)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak  or @JamesNK  if you can provide a draft I'll get this published ASAP.

**Comment by Rick-Anderson** [comment]
Moved to Routing master issue #16501

**Comment by mkArtakMSFT** [comment]
@javiercn this is back to you. Feel free to handle this post your preview 8 issues are done.

**Comment by javiercn** [comment]
This is described [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#route-template-precedence-and-endpoint-selection-order)
