### ISSUE TITLE
use of self signed certs with grpc-dotnet 

### ISSUE THREAD

**Issue by lonewolfnsp** [dotnet/AspNetCore.Docs#15387]
Hi, using openssl, I've generated the private key and cert pems:
openssl req -x509 -newkey rsa:4096 -keyout privatekey.pem -out cert.pem -days 365 -nodes -subj /CN=localhost
and used openssl to generate the pfx from these 2 pwms:
openssl pkcs12  -export -in cert.pem -inkey privatekey.pem -out mycert.pfx

the pfx is loaded into the greeter app's appsettings.json:
"Kestrel": {
    "Endpoints": {
      "HttpsInlineCertFile": {
        "Url": "https://localhost:5566",
        "Protocols": "Http2",
        "Certificate": {
          "Path": "greeter.pfx",
          "Password": "1111"
        }
      }
    }

Now, in the client side, I tried to load the cert.pem into the grpcchanneloptions this wau:
var cert = new SslCredentials(System.IO.File.ReadAllText("d:\\certs\\greeterpub.pem"));            
GrpcChannelOptions opt = new GrpcChannelOptions();
opt.Credentials = cert;
var channel = GrpcChannel.ForAddress("https://localhost:5566", opt);

when it's run, I get the InvalidOperationException: Using SslCredentials with non null arguments is not supported by GrpcChannel. 

Could you please advice me how I can load the cert.pem into the client to allow connection? or do I have to use the mentioned untrusted cert codes instead? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
See also #15385

**Comment by lonewolfnsp** [comment]
it seems grpc-dotnet's way of doing this is this:
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback =
HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
var httpClient = new HttpClient(httpClientHandler);
var channel = GrpcChannel.ForAddress("https://127.0.0.1:5566",
                new GrpcChannelOptions { HttpClient = httpClient });

with this, it can connect..  the X502Certificate2 is for mutual authentication.. when client also passes over a pfx to server..

**Comment by Ricardoaraujo00** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    },
    "EndPoints": {
      "Https": {
        "Url": "https://*:5003",
        "Certificate": {
          "Path": "c:\\test.pfx",
          "Password": "password1234"
        }
      }
    }
  }
}

**Comment by clarkezone** [comment]
@lonewolfnsp tried that and i'm still getting 

`System.IO.IOException
  HResult=0x80131620
  Message= Received an unexpected EOF or 0 bytes from the transport stream.
  Source=System.Net.Security
  StackTrace:
   at System.Net.Security.SslStream.<ReceiveBlobAsync>d__172`1.MoveNext() in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 540`

**Comment by lonewolfnsp** [comment]
did you generate the SSL certificate using openssl? anyway, it's nearly 2
years ago based on .net core 3.x.. mayube things are different now with
.net 5.. i've not taken a look at it.. you should take a look at that and
see if thjins are done fiffernetly..

**Comment by clarkezone** [comment]
I was using powershell, not opensll to generate but otherwise similar: https://github.com/clarkezone/featherservicetest

**Comment by lonewolfnsp** [comment]
this is the linux shell script I used to generate the SSL certificate.. you
can yse WSL/WSL2 with openssl to try:
#! /bin/bash
read -p "enter component name: " component
read -p "enter CommonName: " CN
ptefile=$component.key
pubfile=$component.cert
openssl req -x509 -newkey rsa:4096 -keyout $ptefile -out $pubfile -days 365
-nodes -subj /CN=$CN
read -p "enter 'y' to create PFX file from the key/cert files: " reply
if [[ $reply = "y" ]]
then
echo "generating $component.pfx now..."
openssl pkcs12 -export -in $pubfile -inkey $ptefile -out $component.pfx
echo "removing $ptefile now..."
rm $ptefile
read -p "Enter 'y' if you want to view the generated pfx: " ans
if [[ $ans = "y" ]]
then
openssl pkcs12 -info -in $component.pfx
fi
fi

try with this first and see if it's the cause of your issues..

**Comment by JamesNK** [comment]
`Grpc.Net.Client` will use a certificate from the cert store automatically. Supplying one using `SslCredentials` is not required.

If you server is using an untrusted cert then instructions to ignore certificate errors are available here: https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0#call-a-grpc-service-with-an-untrustedinvalid-certificate

**Comment by ComptonAlvaro** [comment]
@JamesNK In the documentation that you provided, they talk about untrusted or invalid server certificate, configure the client to accept any server certificate.

In my case, I want mutual authentication, so I don't know to accept any server certificate, I have to validate it because it is a trust certificate, self signed, but trusted.

My problem is in the client side, I don't know how to add the certificate when I use SocketsHttpHandler, I am using .NET Core 7.
