### ISSUE TITLE
No mention of AddRazorSupportForMvc although warning links to this page

### ISSUE THREAD

**Issue by springy76** [dotnet/AspNetCore.Docs#15395]
> C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(838,5): warning RAZORSDK1004: One or more Razor view or page files were found, but the project is not configured to add Razor support for MVC. The MSBuild property 'AddRazorSupportForMvc' must be set to correctly compile Razor files that target MVC. **For more information**, see https://go.microsoft.com/fwlink/?linkid=868374.

I expected to find more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm can we add info for 
The MSBuild property 'AddRazorSupportForMvc' must be set to correctly compile Razor files that target MVC.

**Comment by mkArtakMSFT** [comment]
@pranavkm let's get this covered in docs.

**Comment by AnotherRandomTech** [comment]
Possible Solution: 
Edit Project Class File so it reads below: 

<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
.....

**Comment by guardrex** [comment]
I just hit this issue while following some Javier Blazor guidance.

**Comment by dbarriguete** [comment]
Thanks for your comment, I just got the same issue, @AnotherRandomTech your comment is very helpful.

**Comment by MackinnonBuck** [comment]
Is there any remaining work here? It seems that https://github.com/dotnet/AspNetCore.Docs/pull/16690 already added the missing content for `AddRazorSupportForMvc`.

@mkArtakMSFT @guardrex

**Comment by guardrex** [comment]
Looks right to me ... resolved by #16690 and in the live topic at ...

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-7.0#properties
