### ISSUE TITLE
Move documentation to a more generic place (non ASP.NET)

### ISSUE THREAD

**Issue by paolofulgoni** [dotnet/AspNetCore.Docs#15398]
Since `Microsoft.Extensions.DependencyInjection` can be used in non-ASP.NET projects, this documentation could be moved to some more general place.

Maybe to the .NET Core docs?

This is something similar to this: https://github.com/aspnet/AspNetCore.Docs/issues/14621#issuecomment-535566794

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by paolofulgoni** [comment]
OK, thanks for the clarification

**Comment by guardrex** [comment]
For what it's worth, I agree with you ... and there was thinking to do just that. One discussed idea was to move just about the entire *Fundamentals* node of this doc set over to .NET Core docs. In the end tho after discussion and debate, they decided not to do that.
