### ISSUE TITLE
"Complete the Channel in the catch and outside the catch"?

### ISSUE THREAD

**Issue by Daniel15** [dotnet/AspNetCore.Docs#15408]
This article has a note:

> Wrap logic in a try ... catch. Complete the Channel in the catch and outside the catch to make sure the hub method invocation is completed properly.

This is worded pretty clumsily and doesn't match the code snippet underneath (which just completes the channel under the try-catch, not "in the catch"). 

I think what it's *trying* to say is that you should complete the channel either in a `finally` block or underneath a try-catch block, such that it's always called, even if an exception is thrown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.0)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
@BrennanConroy feels like it'd benefit this doc for us to change the sample code to highlight the `IAsyncEnumerable` approach versus Channel. Yay/Nay?

**Comment by BrennanConroy** [comment]
> it'd benefit this doc for us to change the sample code to highlight the `IAsyncEnumerable`

The bit above the Channels part shows `IAsyncEnumerable`, we just need to update the comment for the Channels section.
