### ISSUE TITLE
Code sample references nonexistent property ApplyCurrentCultureToResponseHeaders

### ISSUE THREAD

**Issue by grovesNL** [dotnet/AspNetCore.Docs#15412]
The following code sample appears on this page:

```csharp
app.UseRequestLocalization(new RequestLocalizationOptions
{
    ApplyCurrentCultureToResponseHeaders = true
});
```

But the `ApplyCurrentCultureToResponseHeaders` property described doesn't seem to exist on the `RequestLocalizationOptions` class, so this code sample fails to build with ASP.NET Core 3.0. The documentation for [`RequestLocalizationOptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.requestlocalizationoptions?view=aspnetcore-3.0) also doesn't reference mention this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review

**Comment by hishamco** [comment]
> But the ApplyCurrentCultureToResponseHeaders property described doesn't seem to exist on the RequestLocalizationOptions class

https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/Localization/src/RequestLocalizationOptions.cs#L90

**Comment by Rick-Anderson** [comment]
@grovesNL  you're probably missing a package. See https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies

**Comment by grovesNL** [comment]
Thanks for the quick response and link to the property on `master`. I think this problem still exists in the 3.0 release though.

This happens when I create a new project with `dotnet new web -f netcoreapp3.0` and make that single change in Startup.cs.

The NET Core 3.0.0 release is tagged at https://github.com/aspnet/AspNetCore/commit/aee5e4080331553ea9dfb7fb388b6d72f715bf6a which doesn't include this property as far as I can tell from https://github.com/aspnet/AspNetCore/blob/aee5e4080331553ea9dfb7fb388b6d72f715bf6a/src/Middleware/Localization/src/RequestLocalizationOptions.cs

**Comment by pranavkm** [comment]
The change is in the 5.0.0 branch, which would explain why it isn't working in 3.0.

**Comment by hishamco** [comment]
If is that shall we remove it from docs?

**Comment by hishamco** [comment]
> The change is in the 5.0.0 branch, which would explain why it isn't working in 3.0.

AFAIK I already started the PR before 3.0 is release I don't know if there's something changed

**Comment by Rick-Anderson** [comment]
We should remove this from the docs if it's not in 3.0

**Comment by hishamco** [comment]
Stange!! I'm not sure why this n't shipped in 3.0, @Rick-Anderson I will create a PR for it

**Comment by OnurGumus** [comment]
Still nothing in 3.1

**Comment by hishamco** [comment]
Any update on this?!!

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please review
