### ISSUE TITLE
Claims added to the user on first registration

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#15445]
Updates will be worked for the linked topic and https://docs.microsoft.com/aspnet/core/security/blazor.

* Claims are added to the user on first registration, not on signin.
* Cross-link this at the Blazor auth topic, but note that an API endpoint for tokens will be required in that scenario.

See:

* https://github.com/aspnet/AspNetCore.Docs/issues/15325#issuecomment-548928837
* https://github.com/aspnet/AspNetCore.Docs/issues/15160

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
> * Open a followup issue to revert the API endpoint/tokens content when engineering resolves auth properties in `GetAuthenticationStateAsync`.

Is there an engineering issue open for this?

**Comment by guardrex** [comment]
@hfaran ... did you open your issue (#15160) on the engineering repo? If ur busy, I can do it. :ear:

**Comment by hfaran** [comment]
@guardrex Haven't had time; would be great if you can do it. :)
Tag me when you create it and I can provide any extra input as necessary. Thanks!

**Comment by guardrex** [comment]
@hfaran No worries. I'll open it now.
