### ISSUE TITLE
Deploy to subdirectory

### ISSUE THREAD

**Issue by ndc** [dotnet/AspNetCore.Docs#15464]
I need to host multiple apps in the same server under different subdirectories, for example http://myserver/myfirstapp and http://myserver/mysecondapp.
I tried to set up nginx with multiple locations, but request from browser can't seem to reach the app (404). It seems like the app works only if put on root (location /).
Need guidance on how to set up multiple apps in subdirectories with nginx.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ndc ... this is akin to (not really an exact duplicate given it's a different server) https://github.com/aspnet/AspNetCore.Docs/issues/14999. See if the SO answer that was posted there is any help (it may only apply to Apache).

I'll mark this for the Product Unit ("PU" label). No ETA on when they'll get to this. In the meantime, your best bet are support forums and chat. See my answer on that other issue :point_up:.

**Comment by mkArtakMSFT** [comment]
@shirhatti FYI

**Comment by sheng-jie** [comment]
@ndc Hi, any clues on this? Thanks.

**Comment by ndc** [comment]
@sheng-jie Thanks! It turned out only `UsePathBase` is needed to make it work. I created [a blog post](http://www.endycahyono.com/article/aspnetcore3-running-under-subdirectory-on-nginx) to gather my notes when working on this.

**Comment by guardrex** [comment]
Thanks for the work you guys have done on this issue. I'll schedule it and see if I can improve the doc based on your findings. I should be able to squeeze it in between rounds of Blazor doc issues on the next sprint (March).

**Comment by sheng-jie** [comment]
> @sheng-jie Thanks! It turned out only `UsePathBase` is needed to make it work. I created [a blog post](http://www.endycahyono.com/article/aspnetcore3-running-under-subdirectory-on-nginx) to gather my notes when working on this.

@ndc , You're welcome. You summarized it very carefully. I’m wondering if I can translate your article to Chinese and post on my blog.

**Comment by ndc** [comment]
@sheng-jie no problem, go ahead!

**Comment by sheng-jie** [comment]
I found a new issue when configuring proxy_path as below.
```
location /myfirstapp/ {
        proxy_pass http://ip1:port1/;
```
For example there is a tag `<a asp-controller="Home" asp-action="About">About</a>` in razor page. It will generate a tag like that: `<a  href="/Home/About">About</a>`. In this way, we will route to wrong endpoint. 

To solve this issue we can just add subpath to proxy_pass like below and you will get right url path `<a  href="/myfirstapp/Home/About">About</a>`.

```
location /myfirstapp/ {
        proxy_pass http://ip1:port1/myfirstapp/;
```

**Comment by mu88** [comment]
Can someone please explain to me why we have to set `UseBasePath` when using Nginx? On IIS, I can simply create a reverse proxy from `http://localhost/demo` to `http://localhost:8000` and it works without setting `UseBasePath`. It seems strange to me that I need to add a deployment feature to my code - I'd expect the code to be "deployment agnostic".

**Comment by guardrex** [comment]
@mu88 The **_app_** doesn't know where it's deployed, and the app has to be able to create links to resources, for example. Such links won't be correct if it doesn't know its base path. 

For IIS/ANCM ...

> Middleware added by IIS Integration updates the scheme, remote IP, and pathbase to account for forwarding the request to Kestrel.

> For out-of-process, CreateDefaultBuilder calls UseIISIntegration to ... Configure the port and base path the server should listen on when running behind the ASP.NET Core Module.

* https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#out-of-process-hosting-model
* https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#out-of-process-hosting-model

That's how the app knows in that scenario ... the ANCM/middleware takes care of it.

**Comment by mu88** [comment]
@guardrex Thank you for your explanation. Do you know the reason with `UseBasePath` is baken into the code, rather than specifying a configuration variable?

**Comment by guardrex** [comment]
I don't know why from a framework-design perspective, but you can set a value in your app's config just like any ordinary string key-value and then read it into `UsePathBase` where you call it.

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Host ASP.NET Core on Linux with Nginx #17735

**Comment by guardrex** [comment]
@Rick-Anderson ... I'm going to close this one because you've placed this on the tracking issue for the topic. I'm not going to have time to address this one, so I'm returning it to the pool without an assignee and will let the tracking issue control it. 🏃

btw tho ... It's marked a "Not PU issues" issue on https://github.com/dotnet/AspNetCore.Docs/issues/17735; however, I think the PU will need to suggest how they want it handled. I think I understand from our discussion that they don't want a cross-link to a community resource. Beyond that, idk what Sourabh would like to do.
