### ISSUE TITLE
Add MFA/2FA section to Docs

### ISSUE THREAD

**Issue by damienbod** [dotnet/AspNetCore.Docs#15471]
I think a MFA, 2FA chapter would be good to add to the Security section of the Docs, and it's important enough to have it's own section.

Sub sections 

- Overview
- MFA with Identity 
- FIDO2 with Azure AD (some info and a link)
- MFA without Identity
- Adding a custom MFA to Identity 
- MFA best practices

What do you think?

Exisiting Docs

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes

Greetings Damien

**Comment by guardrex** [comment]
Hello @damienbod ... Ping @blowdart to take a look at your request.

**Comment by blowdart** [comment]
Adding custom worries me a little, because there's no way to judge how secure custom actually is.

**Comment by damienbod** [comment]
We could not do the custom thing at all, or just explain the Identity interfaces where this could be done, or do a FIDO2 example with health warnings.

**Comment by Rick-Anderson** [comment]
@damienbod  would you be able to draft the first version?

**Comment by damienbod** [comment]
@Rick-Anderson @blowdart 

OK, It will probably be after XMAS before I have anything ready. I'll leave out the 'Adding a custom MFA to Identity' section

Greetings Damien

**Comment by damienbod** [comment]
starting this now
