### ISSUE TITLE
MvcRazorCompileOnBuild is worth to mention

### ISSUE THREAD

**Issue by dario-l** [dotnet/AspNetCore.Docs#15505]
I've build multi-modular project where each module is Razor Class Libraries (RCL) which containing bunch of views. Every time when I edit cshtml file and refresh the browser the view is recompiled. It takes too much time.

Fortunately &lt;MvcRazorCompileOnBuild&gt;false&lt;/MvcRazorCompileOnBuild&gt; switches off recompilation but changes are instantly visible in the browser. Thanks for that. I hope it newer will be removed. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  can we mention exactly what `<MvcRazorCompileOnBuild>true | false</MvcRazorCompileOnBuild>` does?

**Comment by dazinator** [comment]
@pranavkm yes please!

**Comment by pranavkm** [comment]
The property exists as back-compat for the older precompilation tool. The `RazorCompileOnBuild` property - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-3.1#properties - is what we'd recommend using. But the two should be functionally equivalent.
