### ISSUE TITLE
Order of request culture providers and how to change them

### ISSUE THREAD

**Issue by Legends** [dotnet/AspNetCore.Docs#15532]
>  Later in the article we'll see how you can change the order and even add a custom culture provider

Where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Legends** [comment]
My app supports 4 different cultures and I decided to set the request culture using the `CookieCultureProvider`.

As I found out, the

**Comment by Legends** [comment]
In order to make this work with the `CookieProvider` I have to kick all others out:

`o.RequestCultureProviders = o.RequestCultureProviders.Where(rcp => rcp.GetType() == typeof(CookieRequestCultureProvider)).ToList();`

**Comment by Rick-Anderson** [comment]
@hishamco  please review.

**Comment by hishamco** [comment]
I'm back @Legends if you want to make `CookieCultureRequestProvider` serve first you could use `AddInitialRequestCultureProvider`

Hope this answer your question

**Comment by Legends** [comment]
Thanks!

**Comment by Duarte10** [comment]
The issue remains, the documentation was not updated.
