### ISSUE TITLE
Update "ASP.NET Core and Entity Framework 6" for .NET Core 3.0

### ISSUE THREAD

**Issue by alrz** [dotnet/AspNetCore.Docs#15620]
>To use Entity Framework 6, your project has to compile against .NET Framework, as Entity Framework 6 doesn't support .NET Core. If you need cross-platform features you will need to upgrade to Entity Framework Core.

This is no longer the case for ef6.3

Edit by @Rick-Anderson 
6K PV

See [Announcing Entity Framework 6.3 Preview with .NET Core Support](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/)

See also #15684 if it's relevant.

-----

`EDIT` : 6K PV
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [Get Started with ASP.NET Core and Entity Framework 6](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by attrib75** [comment]
Hi, is this a good first timer item?  If I understand correctly someone just needs to delete the paragraph from the documentation?

**Comment by Rick-Anderson** [comment]
@alrz It looks like quite a bit needs to be rewritten.

**Comment by Rick-Anderson** [comment]
@pgrudzien12  @damienpontifex let me know if you're interested in updating this for EF 6.3

**Comment by alrz** [comment]
(I think you meant to mention @attrib75)

**Comment by alrz** [comment]
Also relates to https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/

**Comment by attrib75** [comment]
I'll certainly take any part of this if anyone wants me to.  I just need a little direction to understand.  If not, that's cool too. I'll look out for another beginner issue

**Comment by Rick-Anderson** [comment]
@alrz  you're welcome to work on this. Let us know before you start.

**Comment by wadepickett** [comment]
@attrib75 , go ahead and make the edit you feel comfortable with.  I will take a look and add on any additional changes if needed and we can get your first doc improvement published.  :)

**Comment by Varorbc** [comment]
@Rick-Anderson Is there any recent progress on this issue?

**Comment by attrib75** [comment]
> 
> 
> ~@alrz~ @attrib75 you're welcome to work on this. Let us know before you start.

Whoops!  Somehow I missed this

**Comment by Rick-Anderson** [comment]
6K PV. Hopefully @wadepickett can get to this next month.

**Comment by damienpontifex** [comment]
Sorry, I haven't been working with EF6 for a while so it'd be back to basics for me again researching what would be needed here.

**Comment by tdykstra** [comment]
Same answer as @damienpontifex for me.

**Comment by Rick-Anderson** [comment]
@attrib75  all we need is a sample app using EF 6 and ASP.NET Core 3.1
If you can do that I'll help with the article.

**Comment by attrib75** [comment]
@Rick-Anderson Sure. I can do that.  Help me to understand.  Just make a very basic ASP.NET Core app with EF6?  Just bare bones, nothing else in it?  How do I submit it to this?  How would the app link in the article?  Thanks for helping a beginner contributor!

**Comment by Rick-Anderson** [comment]
Yes, just a basic sample. Most folks seem to do the EF6 code  calls from a web API project so that's fine. 
Create the sample in the AspNetCore.Docs/aspnetcore/data/entity-framework-6/3.xsample
so you'll need to create the 3.x sample. 

If you select version 2.2 or lower in the version selector, you get [this version](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.2)
We can use that to create the 3.1 version. You might want to use that code.

**Comment by attrib75** [comment]
Ok thanks, I'll give that a go this weekend.

**Comment by attrib75** [comment]
@Rick-Anderson I made a PR:  #19537 
thanks

**Comment by Rick-Anderson** [comment]
@attrib75 I brought your commits over to #19546, where I'll continue to work on it. Thanks for doing this, I should have something for you to review in a couple days.

**Comment by Rick-Anderson** [comment]
@attrib75  thanks again for all your help. The new doc is now live https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6

**Comment by attrib75** [comment]
@Rick-Anderson How cool is that?! My pleasure.

**Comment by Rick-Anderson** [comment]
@attrib75 feel free to edit in browser and change the link on your name.
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
