### ISSUE TITLE
Global Blazor and SignalR no-loc

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#15627]
Remove `no-loc: [Blazor, SignalR]` from topics when a solution is available to globally apply no-loc behavior  ...

```json
"no-loc": "[Blazor, SignalR]"
```

If possible, including the "blazor"-named files:

* *blazor.webassembly.js*
* *blazor.server.js*

The files are currently code fenced to avoid localizing the "blazor" part of the file names. Discussion was on https://github.com/aspnet/AspNetCore.Docs/pull/16123.

If including the files isn't possible at the time the global approach is adopted, re-purpose this issue and leave it open for the work.

**Comment by guardrex** [comment]
@JasonCard ... checking in with you on this scenario.

**Comment by JasonCard** [comment]
@guardrex The global solution won't be docfx.json, but we are currently discussing a possible solution that will work with the MT engine. Currently following up and will update when I know more.

**Comment by guardrex** [comment]
@JasonCard Is there any update on this one ... a global approach to setting no-loc words/phrases in one spot for the whole repo? If you think it will take quite a while (or never be a thing), then I may as well close this issue.

**Comment by JasonCard** [comment]
@guardrex I was told that MSR team is planning on a dynamic dictionary feature for the MT engine, but there is no ETA and it may take quite awhile. So I agree, we may want to go ahead and close this issue.

**Comment by guardrex** [comment]
Cool ... thanks. I have a feeling that a non-Blazor issue will be the way to go for this anyway. Now that we have the `no-loc` metadata everywhere, it's more a general thing. The team can tend to it when the time comes.
