### ISSUE TITLE
Add CustomTrustStore section to cert authN doc

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#15699]
See https://github.com/aspnet/AspNetCore/pull/15029#issuecomment-554140968

**Comment by Rick-Anderson** [comment]
@edwardneal should info from  [Allow opt-out from client certificate root checking #15029](https://github.com/dotnet/aspnetcore/pull/15029) be added to [Configure certificate authentication in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-7.0) or another doc?

Would you be able to draft the Add CustomTrustStore section?

**Comment by edwardneal** [comment]
I can't see any other docs which might need to be updated. I'll submit a PR shortly to add the description of the extra `ChainTrustValidationMode` and `CustomTrustStore` properties.

While it's not in the .NET docs, there's a section on the [Add and manage TLS/SSL certificates in Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=apex#can-i-configure-a-private-ca-certificate-on-my-app) page in the Azure docs which is slightly out of date too, and has [caused](https://github.com/MicrosoftDocs/azure-docs/issues/104662) [some](https://github.com/MicrosoftDocs/azure-docs/issues/87769) [confusion](https://github.com/MicrosoftDocs/azure-docs/issues/88132) over the years. I'll see if there's a way to clear that up too.
