### ISSUE TITLE
How to publish views to publish folder.

### ISSUE THREAD

**Issue by suchoss** [dotnet/AspNetCore.Docs#15731]
Could you please also extend this documentation about how to include views to publish folder?

```
<PropertyGroup>
<CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
</PropertyGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please try to provide content for this (should be very little).

**Comment by MackinnonBuck** [comment]
The first link in this document points to the Razor SDK page, which documents the `CopyRazorGenerateFilesToPublishDirectory` property:

> Razor files with a .cshtml extension are compiled at both build and publish time using the [Razor SDK](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/sdk.md).

Given this, is there anything else we need to do here? Should we change the verbage to make it more obvious that the Razor SDK can be used to _configure_ the build/publish steps?

@mkArtakMSFT @guardrex

**Comment by guardrex** [comment]
It seems fine ... ***and*** there's a link directly to the content in the *Additional resources* section ...

> \* \[RazorCompileOnBuild and RazorCompileOnPublish](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-6.0#properties) properties

@Rick-Anderson, please re-open if it needs more work.
