### ISSUE TITLE
This certificate authentication does not work when ASP.Net Core API is a Service Fabric application

### ISSUE THREAD

**Issue by sun-acmx** [dotnet/AspNetCore.Docs#15783]
I am using an ASP.net Core API that is a Service Fabric application (ASP.net Core Stateless Service). I used the code outlined in this doc to configure Kestrel to require certificate, but requests go to controllers without even checking if cert was passed or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
Do you have an authorize attribute on those controllers?

**Comment by sun-acmx** [comment]
Yes, I do. Initially I had it on the action method I was testing, but then moved it to the controller level.

**Comment by Rick-Anderson** [comment]
Can you create the simplest possible sample that reproduces the problem and post on GitHub?

Include steps to reproduce the bug and I'll test it.

**Comment by sun-acmx** [comment]
Finally figured it out. Adding this code in the startup.cs fixed it.
services.AddControllers(options =>
            {
                var policy = new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .Build();
                options.Filters.Add(new AuthorizeFilter(policy));
            });

**Comment by jfalameda** [comment]
I do not manage to get certificate authentication at all on ServiceFabric. Did you need to use `AddCertificateForwarding` on it? Is there any particularity that you struggled with when implementing it on ServiceFabric?

In my case the handshake fails completely and I am not sure why.

```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8877 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: Ally_CA.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8877
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8877
```

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
