### ISSUE TITLE
Loading log filters from appsettings files

### ISSUE THREAD

**Issue by amagrath** [dotnet/AspNetCore.Docs#15827]
It is worth adding that in order to load the log filters from the appsettings files, developers will need to call:

AddConfiguration(configuration.GetSection("Logging"));

on the ILoggingBuilder interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by amagrath** [comment]
in particular if you do not use the default builder

**Comment by Rick-Anderson** [comment]
Tracked in #16174
