### ISSUE TITLE
[3.2] Update Blazor VS4Mac guidance

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#15864]
Not available yet in the VS4Mac UI.

Include:

* https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly
* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/

**WORK WITH https://github.com/dotnet/AspNetCore.Docs/issues/18261, which covers ASP.NET Core topics.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by davidbarrows** [comment]
As of 2020-04-02, this page ( https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio ) says that you get the Blazor WebAssembly template as part of the VS2019 preview - but you don't.  I updated my VS2019 Professional, then also downloaded the VS2019 preview, and in either case, only the server template is shown.  Had to get it manually as shown on this StackOverflow page -> https://stackoverflow.com/questions/59272624/missing-visual-studio-2019-blazor-webassembly-app-template

**Comment by guardrex** [comment]
@davidbarrows This issue pertains to VS4Mac. Please open a new issue from the **This page** feedback button+form at the bottom of the topic.

**Comment by guardrex** [comment]
@pjcollins, I'll use this issue. This was originally opened to activate the UI WASM template choice when it becomes available with 8.6, and it looks like that can be worked with the **Web and Console** update simultaneously.

https://github.com/dotnet/AspNetCore.Docs/issues/18030
