### ISSUE TITLE
3.1 update: Areas

### ISSUE THREAD

**Issue by unionthugface** [dotnet/AspNetCore.Docs#15895]
These instructions do not work for .NET Core 3.0.  There is no more `app.useMVC`.  Please instruct how to do this with endpoints and/or `AddControllersWithViews`.  Thank you.

@Rick-Anderson  edit: 10K PV

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by djary** [comment]
+1 today core 3.1 is out

**Comment by DrewBrasher** [comment]
This is how I'm doing it in core 3.1:
`            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "areaRoute",
                    pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
                endpoints.MapRazorPages();
            });`

**Comment by talanc** [comment]
Thanks @DrewBrasher 
I got caught up trying to use `MapAreaControllerRoute` instead of just `MapControllerRoute`.
