### ISSUE TITLE
app.UseSignalR() is obselete

### ISSUE THREAD

**Issue by TheGoldMonkey** [dotnet/AspNetCore.Docs#15916]
In the configure method, app.UseSignalR() is obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@wadepickett  do this a 2 PR's. When you're read create a new PR where you format this doc as:

```
::: moniker range=">= aspnetcore-3.0"
::: moniker-end
::: moniker range="<aspnetcore-3.0"
::: moniker-end
```

Triple check/compare with the live version. Then update this doc.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/AspNetCore.Docs/pull/19752
