### ISSUE TITLE
Add a model to a Razor Pages app : Master Issue

### ISSUE THREAD

**Issue by halljames631** [dotnet/AspNetCore.Docs#15941]
`Edit by @Rick-Anderson to add other issues`

This is the master issue for this doc.  Reopen each issue you are working on so the owner is notified.

* Add an instruction to add a package reference . #16844
* Add secret field so tutorial teaches how to prevent overposting. #16792
* `services.AddDbContext<MovieContext>` should be `RazorPagesMovieContext` #16720
*  'MovieContext' is used instead of 'RazorPagesMovieContext' #15729
* Correct Namespace #16401
* ef commands mentioned but not used #14638
* Some issues in VS Code version #16580
* Visual Studio for Mac: LocalDB is not supported on this platform. #16561
* https://github.com/aspnet/AspNetCore.Docs/issues/16401

[EDIT by guardrex to add the metadata]

In the model section. I found a broken link. Here is the link of the page to find the broken link https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio 

 
![9369DA29-D6A4-488A-86B4-3D763EFA68F4](https://user-images.githubusercontent.com/54309614/69948669-09dc5d80-14be-11ea-8609-f8ff6ce4398c.jpeg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @halljames631 ... Please use the **This Page** feedback button+form at the bottom of the topic. No worries ... I'll add the metadata to your opening comment.

**Comment by craigybaeb** [comment]
Hi, has the LocalDB bug been fixed?

**Comment by azuc-ct** [comment]
Hey @craigybaeb, I think I may have found some steps that worked if you are using Visual Studio on Mac with the most recent versions of .NET Core and Visual Studio on Mac. I went ahead and posted them over on the relevant issue over on the Closed section of Feedback.
