### ISSUE TITLE
API Calls 401 on a custom domain?

### ISSUE THREAD

**Issue by owlyowl** [dotnet/AspNetCore.Docs#16081]
I've got a funky one with the new dotnet core 3 scaffolded react app with JWT.

I followed the example above and added a pfx generated via openssl and altered appsettings.json to look like so:
"IdentityServer": {
    "Clients": {
      "MyAppName.Web": {
        "Profile": "IdentityServerSPA"
      }
    },
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=MyAppName"
    }
  },

I've deployed it to an azure app and added a custom domain..

If you login on the azurewebsites.net address, calls to protected webapi controllers work as expected.

If you login via the custom domain and then try and hit any webapi controller it 401s.

Is there anything that needs to be done to allow custom domains in the certificate setup or identityserver referrers or something?

I installed an openssl cert as instructed here https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production

But I was wondering if there's a further step that had been left out of that document as try as I might I cannot get any webapi calls working from the custom url only the azurewebsites domain. Is there something in the indentitysever4 config that needs to be setup or configured or is the database involved in any way where it might have a token issued to a userid on the azurewebsites domain and that needs to be cleared out so the custom domain token gets inserted?

In looking at the 401 I'm getting Bearer error="invalid_token", error_description="The issuer is invalid" - which is odd as I can log in to the site I just can't calls to API calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
You might try asking indentitysever4  folks or SO.

**Comment by owlyowl** [comment]
Thanks Rick,
I'll ask in gitter.

**Comment by yujiy0713** [comment]
I had the same problem. Here is the solution for people to save time.
I believe you created openssl certificate to be used for IdentityServer. The subject name was *****.azurewebsites.net.
Create a new one for your custom domain and add it to Private Key Certificates in Azure App Services TLS/SSL Setting in the same way.
In App Services Configuration, revise your WEBSITE_LOAD_CERTIFICATES value to the thumbprint of the new certificate (Don't use *).
It would be nice if someone can tell me why I need to do this. The certificates for the site and IdentityServer need to be different?

**Comment by javiercn** [comment]
> The certificates for the site and IdentityServer need to be different?

Ideally yes. One is to sign tokens, the other one to handle HTTPS. It's possible to use the same cert, but it is definitely not recommended and considered an antipattern.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
