### ISSUE TITLE
Clarify dependency between AddAzureWebAppDiagnostics and AddConsole on linux webapps

### ISSUE THREAD

**Issue by SidShetye** [dotnet/AspNetCore.Docs#16095]
All extension methods referenced here are in C#, .net core 3.0 within Program.cs

It appears that removing `logging.AddConsole();` breaks `logging.AddAzureWebAppDiagnostics();`. One would expect each logger to be independent but from our testing we found that `AddAzureWebAppDiagnostics()` depends on `AddConsole()`.

Further more, going to the portal UI -&gt; web app -&gt; App Service logs -&gt; Application Logging -&gt; File System (enable) makes the `AddAzureWebAppDiagnostics()` redundant because linux AppService now automatically saves console logs to the webapp file system.

In addition, the documented folders are wrong on linux. There is no `Application` folder generated within `LogFiles`. 

I suggest a documentation do-over on the Azure WebApp + Linux + .NET Core 3.x combination.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you create a product bug for:
>It appears that removing `logging.AddConsole();` breaks `logging.AddAzureWebAppDiagnostics();`. One would expect each logger to be independent but from our testing we found that `AddAzureWebAppDiagnostics()` depends on `AddConsole()`.

> Further more, going to the portal UI -&gt; web app -&gt; App Service logs -&gt; Application Logging -&gt; File System (enable) makes the `AddAzureWebAppDiagnostics()` redundant because linux AppService now automatically saves console logs to the webapp file system.

Create the simplest possible sample that reproduces the problem and open an issue at [GitHub ASP.NET Core](https://github.com/aspnet/AspNetCore/issues/new?template=bug_report.md)

Include steps to reproduce the bug and the version you're using `dotnet --version`

**Comment by Rick-Anderson** [comment]
Remaining issues moved to master issue #16174

@SidShetye See https://github.com/aspnet/AspNetCore/issues/17844
