### ISSUE TITLE
Replace config.Filters.Add(new AuthorizeFilter(policy)); with             .RequireAuthorization(policy);

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16101]
Replace

```
public void ConfigureServices(IServiceCollection services)
{

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>(
        options => options.SignIn.RequireConfirmedAccount = true)
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();

    services.AddRazorPages();

    services.AddControllers(config =>
    {
        // using Microsoft.AspNetCore.Mvc.Authorization;
        // using Microsoft.AspNetCore.Authorization;
        var policy = new AuthorizationPolicyBuilder()
                         .RequireAuthenticatedUser()
                         .Build();
        config.Filters.Add(new AuthorizeFilter(policy));
    });
    // Authorization handlers.
    services.AddScoped<IAuthorizationHandler,
                          ContactIsOwnerAuthorizationHandler>();

    services.AddSingleton<IAuthorizationHandler,
                          ContactAdministratorsAuthorizationHandler>();

    services.AddSingleton<IAuthorizationHandler,
                          ContactManagerAuthorizationHandler>();
}
```

With code similar to the following:
```
public void Configure(IApplicationBuilder app)
{
    
    ...
    app.UseRouting();
    app.UseAuthentication();
    app.UseAuthorization();
    app.UseEndpoints(endpoints =>
    {
        // using Microsoft.AspNetCore.Mvc.Authorization;
        // using Microsoft.AspNetCore.Authorization;
        var policy = new AuthorizationPolicyBuilder()
                         .RequireAuthenticatedUser()
                         .Build();
        
        endpoints.MapControllers()
            .RequireAuthorization(policy);
    });
}
```

Consider making the starter app complete and drop the cook-book instructions. Just explain the code in the download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@joeaudette @serpent5  I think in the next update I'm going to drop all the cook book steps and have them download the completed app. In lieu of the cook-book steps I'll have them examine the code and explain it. The end of the tutorial will provide an outline on how to create the app.

Do you agree with this approach?

**Comment by serpent5** [comment]
Yep, I prefer that approach in general. It allows the topic to spend more time explaining the details instead of walking the reader through a set of instructions.

**Comment by raydixon** [comment]
> @joeaudette @serpent5 I think in the next update I'm going to drop all the cook book steps and have them download the completed app. In lieu of the cook-book steps I'll have them examine the code and explain it. The end of the tutorial will provide an outline on how to create the app.
> 
> Do you agree with this approach?

@Rick-Anderson I agree with this approach. But... when? 👀
