### ISSUE TITLE
Disposing HttpResponseMessage

### ISSUE THREAD

**Issue by kkostrzewa** [dotnet/AspNetCore.Docs#16103]
Shouldn't the HttpResponseMessage that you get back from SendAsync be Disposed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
No. See #7297

**Comment by kkostrzewa** [comment]
@Rick-Anderson I'm confused. You're citing an issue about HttpClient disposal, but I'm talking about HttpResponseMessage (returned by HttpClient.SendAsync) disposal.

**Comment by escalonn** [comment]
Agreed, issue question has not been addressed

**Comment by Rick-Anderson** [comment]
Moved to master issue: Make HTTP requests using IHttpClientFactory #16641
