### ISSUE TITLE
Create a new ASP.NET hub page

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16124]
the ASP.NET hub page (https://docs.microsoft.com/aspnet) to the new hub page format. https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-hub-page?branch=master

Per @dend :

We don't need separate hub pages for Core and regular ASP.NET
Just one that is currently on https://docs.microsoft.com/aspnet - it needs to move to the new layout

We have guidance here on the process: https://aka.ms/docshub

@wadepickett  this is your top priority after you wrap up current work.

**Comment by wadepickett** [comment]
Fixed with #17482
