### ISSUE TITLE
UseSpaPrerendering deprecated in netcore 3.0

### ISSUE THREAD

**Issue by pawod** [dotnet/AspNetCore.Docs#16165]
I suppose using the UseSpaPrerendering() extension method in netcore does not work anymore. How can I set up SSR and pass data to my angular app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by pawod** [comment]
followed this article's instructions and it works like a charm for netcore 3.1 - despite the deprecation warning:

https://medium.com/@pieterjandeclippel/server-side-rendering-in-asp-net-core-angular-6df7adacbdaa

**Comment by zd-dalibor** [comment]
@pawod @Rick-Anderson 
Will this deprecation lead to removing `UseSpaPrerendering` method in the future releases of netcore?

If this is true, will there be some alternatives for this or netcore developers plan to totally abandon Angular and React SPAs in favour of Blazor???

**Comment by Rick-Anderson** [comment]
See [this GitHub comment](https://github.com/dotnet/aspnetcore/issues/13593#issuecomment-527966453)

The recommendation is to rely on the SPA framework provided SSR capabilities. For Angular, SSR support is now integrated into Angular CLI. Here is a good article about it: https://medium.com/@MarkPieszak/angular-universal-server-side-rendering-deep-dive-dc442a6be7b7
