### ISSUE TITLE
Master issue for Logging in .NET Core and ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16174]
This is the master issue for this doc.  Reopen each issue you are working on so the owner is notified.

* Using scopes with async/await #17727
* 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JuergenGutsch** [comment]
Hey @Rick-Anderson, 
Sorry for the delay. As mentioned in #11842 I would really like to create a PR with a sample about how to create a custom logging provider. Do I need to assign the PR to the closed ticket or to this ticket? Thanks

**Comment by Rick-Anderson** [comment]
@JuergenGutsch  I'll open the ticket when you PR this.
