### ISSUE TITLE
3.1 update: Migrate from ASP.NET MVC to ASP.NET Core MVC

### ISSUE THREAD

**Issue by doggy8088** [dotnet/AspNetCore.Docs#16199]
`services.AddMvc();` =&gt; `services.AddControllersWithViews();`

`app.UseMvc` ==&gt; `app.UseRouting` and `app.UseEndpoints`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0591f873-94fa-c678-a905-e002e4f2c902
* Version Independent ID: a84e5712-2926-7e6d-d913-54743070e9e8
* Content: [Migrate from ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/mvc.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by KamranShahid** [comment]
Documentation needed some serious concentration.

**Comment by 404Prachi** [comment]
how can I add sitemap to the asp.net core mvc project

**Comment by arbaieffendi** [comment]
Suggest an update to this documentation.
In order to work at first run we need to set EnableEndpointRouting to false in startup.cs, but it's not clear how to do it here. Spend sometimes to figure it out something like this.

public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddMvcOptions( options => options.EnableEndpointRouting = false);
        }

**Comment by wadepickett** [comment]
Fixed with #18796

**Comment by wadepickett** [comment]
@404Prachi, There are a lot of package options for sitemap generation available.  You can check those out here:  [Sitemap packages on NuGet](https://www.nuget.org/packages?q=sitemap) .
