### ISSUE TITLE
Master issue for Get started with Swashbuckle

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16195]
43K PV
---
This is the master issue for this doc.  Reopen each issue you are working on so the owner is notified.

PU issues:

* In "Describe response types", with NET Core 3.1, we need to specify Type to have example model on Swagger page #18173
* Injecting custom css should be done without copying the entire swagger ui #10916
* Add note for Swagger 2.0 versus OpenAPI 3.0.x #16070
* Reverse proxy example is slightly wrong. #15755
* Example for reverse proxy #10337
* Two problems with Swashbuckle tutorial #14631
* Missing services.AddApiExplorer() #14594
* error: Unable to resolve 'Swashbuckle.AspNetCore (>= 5.0.0-rc2)' for '.NETCoreApp,Version=v2.2'. #14478
* How to automatic save "swagger.json" to folder when debug on web API ? #14055
* Automatic paramters added in Swagger produced documentation. #12304
* ./swagger/v1/swagger.json does not work in IIS #16572

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@scottaddie  does the PU own this topic or do you?

**Comment by spboyer** [comment]
@Rick-Anderson Swashbuckle does work, there are maintenance items that need to be done to bring this doc up to date. @bradygaster and I have recently spoken about some needed items. I'll take ownership of updating the document.

**Comment by bradygaster** [comment]
I own this experience, Shayne owns the doc. He and I have had a few meetings on updating it as we're shipping some updates to the tools this month related to Swagger and Swashbuckle. So this is on our short list of things to get done this week.
