### ISSUE TITLE
Container issue: Use the React project template

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16209]
This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.

* using old and unecessary --save flag on npm #24663

PU issues

*  #11326
*  #9344
*  #7644
* #18851
* #27592

![image](https://user-images.githubusercontent.com/3605364/81249132-9fbe6c00-8fb9-11ea-9363-094f96e8b340.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by guisantos** [comment]
Any update?
I'm looking forward for this content

**Comment by mkArtakMSFT** [comment]
Closing as the React project template have been removed from the .NET SDK.
