### ISSUE TITLE
Explanation for what really happens in debug mode

### ISSUE THREAD

**Issue by SidShetye** [dotnet/AspNetCore.Docs#16236]
The `Dockerfile` parts are very clear but VS seems to add some extra "magic" in debug mode which isn't clearly understood. Like:

1) How does VS launch the debug versions of the app in the container? The `Dockerfile`'s entry point is still `ENTRYPOINT ["dotnet", "MyProject.dll"]`. Is that through a hidden `docker exec`?

2) Similar clarity for the in-container remote debugger's lifecycle needed

3) What are the assumptions about the container file-system at /app ? The Dockerfile publishes to `/app/MyProject.dll` which is straight forward but debug uses a volume mount from host to `/app/MyProject.csproj`. Does VS/container tools ever reverse the image back to published state?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Container Tools with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-3.1#debug)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16250
