### ISSUE TITLE
ApplyTo does not accept a ModelState in the Microsoft.AspNetCore.JsonPatch NuGet package

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/AspNetCore.Docs#16286]
This feedback is written regarding the documentation at https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core in the linked section "JsonPatch in ASP.NET Core".

The section indicates that the ASP.NET Core implementation of JSON Patch is provided in the Microsoft.AspNetCore.JsonPatch NuGet package and then cites an example that passes ModelState in as an argument to the `ApplyTo `method on a ` JsonPatchDocument<T>`. This method overload does not exist within the installed library as seen in the below source:

* https://github.com/aspnet/AspNetCore/blob/c759f5b8f82fc0ed1a5e918c6b611ffb861af84d/src/Features/JsonPatch/src/JsonPatchDocumentOfT.cs#L708 
* https://github.com/aspnet/AspNetCore/blob/c759f5b8f82fc0ed1a5e918c6b611ffb861af84d/src/Features/JsonPatch/src/JsonPatchDocumentOfT.cs#L719
* https://github.com/aspnet/AspNetCore/blob/c759f5b8f82fc0ed1a5e918c6b611ffb861af84d/src/Features/JsonPatch/src/JsonPatchDocumentOfT.cs#L753

Rather, it's an extension method available within the Microsoft.AspNetCore.Mvc.NewtonsoftJson package:
https://github.com/aspnet/AspNetCore/blob/c759f5b8f82fc0ed1a5e918c6b611ffb861af84d/src/Mvc/Mvc.NewtonsoftJson/src/JsonPatchExtensions.cs#L21

This specific example should likely be replaced with one that uses only the native implementation (for the time being in the current release) and this example should be moved into another sub-section of this portion of the document that describes both installing this other package to use its extension method for validation purposes.

I'll be submitting an issue in the relevant Github repo to move this extension into the JsonPatchDocument package itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@WhitWaldo see https://github.com/aspnet/AspNetCore.Docs/pull/16824

**Comment by kkbruce** [comment]
This section https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#jsonpatch-in-aspnet-core is written not good.  I also tried it for a long time to implement it. That's why I want to submit JsonPatch example PR.

In ASP.NET Core 3.1, JsonPatch is still needed NewtonsoftJson to support operations.

**Comment by kkbruce** [comment]
Waiting for PR review and merge, you can access my jsonpatch sample version: 
https://github.com/kkbruce/AspNetCore.Docs/tree/master/aspnetcore/web-api/jsonpatch/samples/3.1

**Comment by Rick-Anderson** [comment]
@kkbruce  what's the status of this issue?

**Comment by Rick-Anderson** [comment]
Tracked in JsonPatch Master issue. Look here #18330
