### ISSUE TITLE
RequestServices vs ApplicationServices

### ISSUE THREAD

**Issue by nj-git** [dotnet/AspNetCore.Docs#16323]
Can we get more detail about these two? Where is more detail about them? Also 
"Request Services represent the services configured and requested as part of the app." Are we talking of service explicitly added that are not internal of asp.net core like httpContext itself..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Roughly speaking:

`RequestServices` is used whenever constructor injection is used. e.g. If a controller requires something from DI, it uses a constructor parameter to request said something. It's also used for something like `HttpContext.RequestServices.GetRequiredService<Something>()`. `RequestServices` is _scoped_ to a HTTP request.

`ApplicationServices` is available on `IApplicationBuilder` and can be used when configuring a middleware pipeline. This is the _root_ container used by the application. It's used for providing arguments via DI to `Startup.Configure` and can also be used for something like `app.ApplicationServices.GetRequiredService<Something>()`. `ApplicationServices` isn't scoped, but it can be used to create a new scope if needed.

**Comment by wenhx** [comment]
In what scenario do I have to use ApplicationServices?

**Comment by guardrex** [comment]
@Rick-Anderson I :+1: on PU. Current coverage for common use scenarios is probably ok. We don't talk too much about these for good reason. We *hope* dev use cases for most general purpose apps don't need to sweat these. (Not suggesting tho that coverage is stellar or anything, just that we haven't focused on this on purpose.) I'm 🏃😅 on *Blazorish Thingables*:tm:, so I wouldn't be able to look at this for quite a while.

**Comment by Rick-Anderson** [comment]
Moved to Dependency injection master issue #17298

**Comment by mkArtakMSFT** [comment]
Will find an owner on Monday.

**Comment by davidfowl** [comment]
> The services available within an ASP.NET Core request from HttpContext are exposed through the HttpContext.RequestServices collection.

> Request Services represent the services configured and requested as part of the app. When the objects specify dependencies, these are satisfied by the types found in RequestServices, not ApplicationServices.

> Generally, the app shouldn't use these properties directly. Instead, request the types that classes require via class constructors and allow the framework to inject the dependencies. This yields classes that are easier to test.

This part of the document isn't explained properly. We should explain how ASP.NET Core creates a scope per request and RequestServices exposes the scoped service provider. This means that all scoped services will life for as long as the request is active.

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson is this good high-level explanation you can work with or do you still need more content from the engineering side?

**Comment by Rick-Anderson** [comment]
That should be good.
