### ISSUE TITLE
Multiple authentication schemes

### ISSUE THREAD

**Issue by snake-net** [dotnet/AspNetCore.Docs#16389]
I am trying to create a sample application using multiple authentication schemes (AAD B2C and another AAD tenant). If I configure only one of them (does not matter which one) it works like a charm and everything works correctly. If I configure both of them (as in the provided example), however mention only one of them in the default policy, it also works (only for that scheme):
```
services.AddAuthentication()
.AddJwtBearer("B2C", jwtOptions =>
{
    jwtOptions.Authority = "my-b2c-authority";
    jwtOptions.Audience = "my-audience";
})
.AddJwtBearer("AAD", jwtOptions =>
{
    jwtOptions.Authority = "my-aad-authority";
    jwtOptions.Audience = "my-audience";
});
```

```
services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .AddAuthenticationSchemes("B2C")
        .Build();
});
```
However, if I configure both and mention them in the default policy:
```
services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .AddAuthenticationSchemes("B2C", "AAD")
        .Build();
});
```
it seems that the token gets validated twice (against each configured scheme) and therefore it fails - I am suspecting that as I can see the following messages in the debug window:
```
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: Successfully validated the token.
...
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: Failed to validate the token.

Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys: 
kid: '[PII is hidden]', 
token: '[PII is hidden]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
...
```

I guess I am missing something and I have not been able to figure it out on my own. Would be grateful for any hints regarding what might be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for: Authorize with a specific scheme #16190

**Comment by udlose** [comment]
@Rick-Anderson 
I also have this same issue.  Should I be watching this Issue to track a resolution or https://github.com/aspnet/AspNetCore.Docs/issues/16190?

**Comment by Rick-Anderson** [comment]
@snake-net  yes, watch them both

**Comment by Rick-Anderson** [comment]
Multiple authentication schemes
@HaoK  this is similar to #15791 and tracked in #16190

**Comment by shaysw** [comment]
Any updates on this? I too cannot add 2 schemes

**Comment by shaysw** [comment]
This issue is not resolved, why are the tickets closed?

**Comment by Rick-Anderson** [comment]
Moved to Master issue for: Authorize with a specific scheme #16190

**Comment by TechnoJay** [comment]
@RickAndMSFT is there a resolution to this issue?

**Comment by TechnoJay** [comment]
@snake-net , have you found an solution or workaround to this issue?

**Comment by snake-net** [comment]
Nothing besides trying to use a single authority. I think it also worked in the previous version of the .NET Core, however we could not downgrade and therefore we have not checked that possibility.

**Comment by automachina** [comment]
I was able to workaround this issue by copying the JwtBearerHandler class @ (src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs) into my project and replaced the hard coded scheme check with a check against the current Scheme object:
Replaced this:
https://github.com/dotnet/aspnetcore/blob/1f76cce14ac4e4698a554b65a24f28000b50396e/src/Security/Authentication/JwtBearer/src/JwtBearerHandler.cs#L74-L77
```
if (authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
{
    token = authorization.Substring("Bearer ".Length).Trim();
}
```
With this:

```
if (authorization.StartsWith($"{Scheme.Name} ", StringComparison.OrdinalIgnoreCase)) 
{
     token = authorization.Substring($"{Scheme.Name} ".Length).Trim(); 
}
```



I then created some custom AddJwtAuthentication extensions referencing my modified JwtBearerHandler class (CustomJwtBearerHandler) and .
i.e.
```

public static AuthenticationBuilder AddDefaultJwtAuthentication(this AuthenticationBuilder builder,
            string schema, string displayName, Action<JwtBearerOptions> configureOptions)
{
    return builder.AddScheme<JwtBearerOptions, CustomJwtBearerHandler>(schema, displayName, configureOptions);
}

public static AuthenticationBuilder AddDefaultJwtAuthentication(this AuthenticationBuilder builder,
            string schema, Action<JwtBearerOptions> configureOptions)
{
    return builder.AddScheme<JwtBearerOptions, CustomJwtBearerHandler>(schema, schema, configureOptions);
}

public static AuthenticationBuilder AddDefaultJwtAuthentication(this AuthenticationBuilder builder,
            Action<JwtBearerOptions> configureOptions)
{
    return builder.AddScheme<JwtBearerOptions, CustomJwtBearerHandler>(
        JwtBearerDefaults.AuthenticationScheme,
        JwtBearerDefaults.AuthenticationScheme,
        configureOptions);
}

```
And used those extensions to configure my Jwt authentication.
Seems to work fine, but If there are any security concerns please let me know.

**Comment by udlose** [comment]
@Rick-Anderson any update on this issue?

**Comment by Rick-Anderson** [comment]
@udlose  please use the subscribe button to get updates.

**Comment by udlose** [comment]
> @udlose please use the subscribe button to get updates.

I have been subscribed.  Haven't seen any updates and was checking in.

**Comment by jamir-araujo** [comment]
@snake-net, have you try to use `PolicyScheme`. It worked in my case.

Schemes configuration would look something like this:

```csharp
services.AddAuthentication()
    .AddJwtBearer("B2C", jwtOptions =>
    {
        jwtOptions.Authority = "my-b2c-authority";
        jwtOptions.Audience = "my-audience";
    })
    .AddJwtBearer("AAD", jwtOptions =>
    {
        jwtOptions.Authority = "my-aad-authority";
        jwtOptions.Audience = "my-audience";
    })
    .AddPolicyScheme("B2C_OR_AAD", "B2C_OR_AAD", options =>
    {
        options.ForwardDefaultSelector = context =>
        {
            string authorization = context.Request.Headers[HeaderNames.Authorization];

            if (!string.IsNullOrEmpty(authorization))
            {
                if (authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
                {
                    var token = authorization.Substring("Bearer ".Length).Trim();

                    var jwtHandler = new JwtSecurityTokenHandler();
                    if (jwtHandler.CanReadToken(token))
                    {
                        var jwtToken = jwtHandler.ReadJwtToken(token);

                        if (jwtToken.Issuer.Equals("my-b2c-authority"))
                        {
                            return "B2C";
                        }
                    }
                }
            }

            return "AAD";
        };
    });
```

And then use the `PolicyScheme` on the `AuthorizationPolicy`:

```csharp
services.AddAuthorization(options =>
{
    options.DefaultPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .AddAuthenticationSchemes("B2C_OR_AAD")
        .Build();
});
```

This way the policy will run the `B2C_OR_AAD` scheme, and the `B2C_OR_AAD` scheme will forward select to the actual scheme based on the `ForwardDefaultSelector` delegate.

**Comment by snake-net** [comment]
@jamir-araujo I had to postpone working on it for a while. Thanks for sharing your solution, will definitely give it a try once AAD B2C comes back into the landscape.

**Comment by Sayan751** [comment]
I am also facing the same issue. Only in my case I am using cookie and JWT Bearer authentication. The problem is when I make a request with Cookie, the authorization header is also validated. That results in 401 response. I have also tried what @jamir-araujo suggested. It doe not work in my case.

**Comment by Sayan751** [comment]
The only thing that seems to be working for me is if the Jwt Authentication attempt is preempted using custom events class.

```c#
public class JwtBearerAuthenticationEvents : JwtBearerEvents
{
  public IHttpContextAccessor ContextAccessor { get; }

  public JwtBearerAuthenticationEvents(IHttpContextAccessor contextAccessor)
  {
    ContextAccessor = contextAccessor;
  }

  public override Task MessageReceived(MessageReceivedContext context)
  {
    if (ContextAccessor.HttpContext?.User.Identity?.AuthenticationType == "Cookie_Auth_Type")
    {
      context.Principal = ContextAccessor.HttpContext!.User;
      context.Success();
    }
    else
    {
      base.MessageReceived(context);
    }

    return Task.CompletedTask;
  }
}

// in ConfigureServices
const string defaultScheme = "JwtOrBearer";
services
  .AddAuthentication(defaultScheme)
  .AddPolicyScheme(defaultScheme, defaultScheme, options =>
    options.ForwardDefaultSelector = context => context.Request.HasBearerToken() // Extension method
      ? JwtBearerDefaults.AuthenticationScheme 
      : CookieAuthenticationDefaults.AuthenticationScheme
  )
  .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
  {
    // configure cookie authentication that uses a custom ticket data format that unprotects with "Cookie_Auth_Type" AuthenticationType
  })
  .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
  {
    // set token validation parameters
    options.EventsType = typeof(JwtBearerAuthenticationEvents);
  });
```

**Comment by mradulmodi** [comment]
I am also facing the same issue. I am using 6 JWT validation Authorities and 5 of them are logging exceptions creating a  lot of noise in AI logs

```
foreach (var tokenAuthority in Authorities)
            {
                builder.AddJwtBearer(tokenAuthority.Key, options =>
                 {
                     options.Audience = ClientId;
                     options.Authority = tokenAuthority.Value;
                     options.TokenValidationParameters = new TokenValidationParameters
                     {
                         ValidIssuers = <Issuers>,
                         ValidateIssuer = true,
                         ValidAudiences = <audiences>,
                         ValidateLifetime = true,
                         ValidateIssuerSigningKey = true,
                     };
                     options.EventsType = typeof(AuthenticationJwtBearerEvents);
                 });
            }
```

**Comment by egbakou** [comment]
The same issue here. I tried the solution of @jamir-araujo. I can get the token from AzureB2C and Azure AD but the signature validation fails for Azure AD.

**Comment by jamir-araujo** [comment]
@Sayan751 and @egbakou, in your cases, the `ForwardDefaultSelector` is invoked or not?

**Comment by Sayan751** [comment]
@egbakou You *should* set the token validation parameters as far as I know. I would advice not to disable the audience and issuer validation, you should rather specify the valid values in TokenValidationParameters. To me it seems quite logical (and expected) that without those expected values, the token is considered invalid.

**Comment by egbakou** [comment]
@jamir-araujo @Sayan751 The issue was the `DefaultChallengeScheme ` that was not specified.
This works for me !
```cs
services.AddAuthentication(options => 
{
  options.DefaultScheme = "B2C_OR_AAD";
  options.DefaultChallengeScheme = "B2C_OR_AAD";
})
.AddJwtBearer("B2C", jwtOptions =>
 {
   jwtOptions.MetadataAddress = "B2C-MetadataAddress";
   jwtOptions.Authority = "B2C-Authority";
   jwtOptions.Audience = "B2C-Audience";
})
.AddJwtBearer("AAD", jwtOptions =>
{
   jwtOptions.MetadataAddress = "AAD-MetadataAddress";
   jwtOptions.Authority = "AAD-Authority";
   jwtOptions.Audience = "AAD-Audience"; 
   options.TokenValidationParameters =  new TokenValidationParameters
    {
       ValidateIssuer = true,
       ValidateAudience = true,
       ValidateIssuerSigningKey = true,
       ValidAudiences = config["ValidAudiences"], // stored in appsettings.json
       ValidIssuers = config["ValidIssuers"], // stored in appsettings.json
  }                        
})
.AddPolicyScheme("B2C_OR_AAD", "B2C_OR_AAD", options =>
{
    options.ForwardDefaultSelector = context =>
    {
        string authorization = context.Request.Headers[HeaderNames.Authorization];
	if (!string.IsNullOrEmpty(authorization) && authorization.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            var token = authorization.Substring("Bearer ".Length).Trim();
            var jwtHandler = new JwtSecurityTokenHandler();

            return (jwtHandler.CanReadToken(token) && jwtHandler.ReadJwtToken(token).Issuer.Equals("B2C-Authority"))
                ? "B2C" : "AAD";
        }                
        return "AAD";
    };
});
```
You can create small functions to keep your code clean and use constants for the Policy Schemes.
I hope this may help, :) do not hesitate to tag me in the comment section if you have any question.

**Comment by egbakou** [comment]
> I am also facing the same issue. I am using 6 JWT validation Authorities and 5 of them are logging exceptions creating a lot of noise in AI logs
> 
> ```
> foreach (var tokenAuthority in Authorities)
>             {
>                 builder.AddJwtBearer(tokenAuthority.Key, options =>
>                  {
>                      options.Audience = ClientId;
>                      options.Authority = tokenAuthority.Value;
>                      options.TokenValidationParameters = new TokenValidationParameters
>                      {
>                          ValidIssuers = <Issuers>,
>                          ValidateIssuer = true,
>                          ValidAudiences = <audiences>,
>                          ValidateLifetime = true,
>                          ValidateIssuerSigningKey = true,
>                      };
>                      options.EventsType = typeof(AuthenticationJwtBearerEvents);
>                  });
>             }
> ```

https://github.com/dotnet/AspNetCore.Docs/issues/16389#issuecomment-984468397

**Comment by dandax** [comment]
I came across this issue a few months back and was able to put together a working solution. Here's what worked for me (I'm using ASP.NET Core 3.1)

Note: the "AAD" scheme should work on any AAD tenant. I just happen to be using the same `ClientId` and tenant for both schemes.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    ...

    var identityConfig = configuration.GetSection("AzureAdB2C").Get<MicrosoftIdentityOptions>();

    services.AddAuthentication("B2C")
        .AddJwtBearer("B2C", options =>
        {
            options.Audience = identityConfig.ClientId;
            options.Authority = $"{identityConfig.Instance}/{identityConfig.Domain}/{identityConfig.DefaultUserFlow}/v2.0";
        })
        .AddJwtBearer("AAD", options =>
        {
            options.Audience = identityConfig.ClientId;
            options.Authority = $"https://login.microsoftonline.com/{identityConfig.TenantId}/v2.0";
        });

    services.AddAuthorization(options =>
    {
        options.DefaultPolicy =
            new AuthorizationPolicyBuilder("B2C", "AAD")
                .RequireAuthenticatedUser()
                .Build();
    });

    ...
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    ...

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers().RequireAuthorization();
    });
}
```

**Comment by Denny966** [comment]
> I came across this issue a few months back and was able to put together a working solution. Here's what worked for me (I'm using ASP.NET Core 3.1)
> 
> Note: the "AAD" scheme should work on any AAD tenant. I just happen to be using the same `ClientId` and tenant for both schemes.
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
> {
>     ...
> 
>     var identityConfig = configuration.GetSection("AzureAdB2C").Get<MicrosoftIdentityOptions>();
> 
>     services.AddAuthentication("B2C")
>         .AddJwtBearer("B2C", options =>
>         {
>             options.Audience = identityConfig.ClientId;
>             options.Authority = $"{identityConfig.Instance}/{identityConfig.Domain}/{identityConfig.DefaultUserFlow}/v2.0";
>         })
>         .AddJwtBearer("AAD", options =>
>         {
>             options.Audience = identityConfig.ClientId;
>             options.Authority = $"https://login.microsoftonline.com/{identityConfig.TenantId}/v2.0";
>         });
> 
>     services.AddAuthorization(options =>
>     {
>         options.DefaultPolicy =
>             new AuthorizationPolicyBuilder("B2C", "AAD")
>                 .RequireAuthenticatedUser()
>                 .Build();
>     });
> 
>     ...
> }
> 
> public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
> {
>     ...
> 
>     app.UseAuthentication();
>     app.UseAuthorization();
> 
>     app.UseEndpoints(endpoints =>
>     {
>         endpoints.MapControllers().RequireAuthorization();
>     });
> }
> ```

Doesn't seem to work for me, in you case it would give the error

> [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] "B2C" was not authenticated. Failure message: "IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.

**Comment by jose-escalona** [comment]
> your case it would give the erro

Same issue here, did you managed to make it works? Thanks in advance.

**Comment by jose-escalona** [comment]
@Denny966  i'm facing the same issue in .net 6, did you managed to find a solution?

Thanks in advance.

**Comment by Denny966** [comment]
> 

Nope

**Comment by oclockvn** [comment]
for those who are still struggling with this issue, double check your code base cuz this line is important (notice there are 2 `AddAuthentication`)
![image](https://github.com/dotnet/AspNetCore.Docs/assets/3783976/49401c42-6618-41b5-be9f-5c08ea1937b2)

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-7.0

Few highlights:
- notice there are 2 `AddAuthentication` (I guess the 2nd one to add default Bearer scheme, so maybe register another `AddJwtBearer` with Bearer scheme might work as well)
- no need to use `AddAuthorization` as the default scheme will forward to the corresponding scheme base on the `ForwardDefaultSelector`
