### ISSUE TITLE
Under "Conditionally enable runtime compilation" Env is coming as NULL

### ISSUE THREAD

**Issue by esausilva** [dotnet/AspNetCore.Docs#16420]
Documentation does not say where to assign `Env`. 

Just following the documentation as as is under "Conditionally enable runtime compilation" throws a null reference exception when trying to use `Env.IsDevelopment()`.

I had to assign `Env` as below

```
public Startup(IConfiguration configuration, IWebHostEnvironment env) {
    Configuration = configuration;
    Env = env;
}
```

Then I am able to use `Env.IsDevelopment()` without throwing a null reference exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Create a new project:

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
```

**Comment by scottaddie** [comment]
The following sample app shows how to do it: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/runtimecompilation

**Comment by esausilva** [comment]
@scottaddie Thank you. That is exactly what I did. I wanted to make sure I was doing it the correct way 👍

**Comment by Rick-Anderson** [comment]
@esausilva  I'll get it updated this week. Thanks for reporting the problem.

**Comment by nzcoward** [comment]
@scottaddie - in the sample is it perhaps better to remove the env parameter from the Configure method? Else it feels like the class level property might be a different IWebHostEnvironment. 

Unsure if you're a maintainer, but have created a PR showing my thoughts.

**Comment by scottaddie** [comment]
@nzcoward Let's see what @pranavkm thinks of your proposal.

**Comment by pranavkm** [comment]
Sure, done.

**Comment by nmg196** [comment]
Not sure why 3 months on, the docs are still not correct :(
