### ISSUE TITLE
How to check scopes in .NET Core 3.1 web api app?

### ISSUE THREAD

**Issue by alvipeo** [dotnet/AspNetCore.Docs#16436]
How should we check user's permissions based on scopes in .NET Core 3.1 web api? The sample is .net core 2.0! Is it the same?

Guys, the Azure B2C docs is a mess, sorry... Please implement the whole story:
1) Create 3 parts application
   a. Administrator's part - this is basically a user's manager. It can see/change/delete users. It MUST be able to create B2C CUSTOM CLAIMS, so the SPA (for example, angular app) can get them with id_token.
   b. Web API app - contains biz logic with different types of permissions. Ideally, some API is authorized by scopes and some by custom claims. It could be also a mix!
   c. Web API app that works with Graph API - this requires other type of authentication (I believe). The SPA would authenticate and it could use this web api app only when it's granted enough permissions to work with Graph API. Now, this means user is authenticated in the SPA, then it reaches this API and this API invokes Graph API. How do you make this one work?

Please describe this scenario somewhere as it's very close to a real life apps we build!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
