### ISSUE TITLE
Target Framework section should mention that .NET Framework is only an option for ASP.NET Core 2.1

### ISSUE THREAD

**Issue by Pilchie** [dotnet/AspNetCore.Docs#16437]
You can no longer target .NET Framework with with recent versions of ASP.NET Core (3.0 and 3.1). This section should be updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Related dotnet/docs#16571

**Comment by scottaddie** [comment]
@Rick-Anderson This entire doc needs to be updated from 2.2 to 3.1.

**Comment by Rick-Anderson** [comment]
@scottaddie  thanks for catching that. Your reward is I assigned this to you :)

**Comment by Rick-Anderson** [comment]
moved to #21570
