### ISSUE TITLE
Retire duplicate Create a gRPC client and server in ASP.NET Core 3.0 using Visual Studio

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16467]
[Sample hosted: Create a gRPC client and server in ASP.NET Core 3.0 using VS only (no VSC or VS Mac)](https://docs.microsoft.com/en-us/samples/aspnet/AspNetCore.Docs/create-grpc-client/)

is a complete duplicate of [Tutorial: Create a gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio) (8 K PV/month) with the following exceptions.  The sample hosted version :

* Has instructions that no long work. 
* It's version 3.0
* Has only 325 PV/month

Recommend we retire this version - **OR** remove all the instructions and link to [Tutorial: Create a gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio) 

That way folks would have an easy download mechanism and updated instructions.

I'm guessing we can't move the VS, VSC, VSmac version to https://docs.microsoft.com/samples/ because it doesn't support tabs.

@JamesNK  please advise.

**Comment by JamesNK** [comment]
I don't want to move the tutorial to samples.

Whatever you want to do with the samples copy is fine with me.

**Comment by Rick-Anderson** [comment]
@wadepickett can you replace this tutorial with a link to our sample. Update the download  code to the 3.1 version from our repo.

**Comment by JamesNK** [comment]
Don't you mean the opposite: replace the sample content with a link to the tutorial?

**Comment by Rick-Anderson** [comment]
@JamesNK  Thanks, corrected text.

**Comment by wadepickett** [comment]
@Rick-Anderson, will do, thanks!
