### ISSUE TITLE
.NET 4.x config-builder

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16466]
fix https://github.com/aspnet/AspNetDocs/issues/293

**Comment by guardrex** [comment]
Last setting wins was addressed on [an earlier PR](https://github.com/aspnet/AspNetCore.Docs/pull/8050) in the *Keys* section ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#keys

**Comment by guardrex** [comment]
... also covered in the first sentence of the second paragraph of the *Providers* section (under the table) ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#providers

**Comment by Rick-Anderson** [comment]
@guardrex that's a totally different config builder than the asp.net core version.

**Comment by guardrex** [comment]
Sorry ... I didn't look too closely ... just glanced at the cross-linked issue and didn't notice it wasn't for these bits.

**Comment by Rick-Anderson** [comment]
Fixed
