### ISSUE TITLE
 Migrate aspnet organization docs repos to dotnet organization

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16487]
**Conceptual content repos**

- [x] aspnet/AspNetCore.Docs --> dotnet/AspNetCore.Docs
- [x] aspnet/AspNetDocs --> dotnet/AspNetDocs
- [x] aspnet/EntityFramework.Docs --> dotnet/EntityFramework.Docs

**API reference repos**

- [x] aspnet/ApiDocs -> dotnet/AspNetApiDocs
- [x] aspnet/EntityFramework.ApiDocs -> dotnet/EntityFramework.ApiDocs
- [x] aspnet/JavaApiDocs ->dotnet/JavaApiDocs
- [x] aspnet/JsApiDocs -> dotnet/JsApiDocs
- [x] aspnet/Microsoft.Data.Sqlite.ApiDocs -> dotnet/Microsoft.Data.Sqlite.ApiDocs

**Other migration tasks**

- [x] Work with Jason Card to migrate localized conceptual content repos
- [x] Work with Monica Rush to configure Acrolinx licensing (for VS Code extension) in conceptual content repos

**Comment by scottaddie** [comment]
Handed off the transferred repos to Jason's loc team for completion.
