### ISSUE TITLE
Routing complete rewrite and master issue

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16501]
This is the master issue for this doc. If you PR this doc and don't fix all the issues, open the issues you fix and close against that.

- [ ]  What is the right way to create absolute URL from arbitrary path? #16495
- [ ]  Add a section about route precedence #15349

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
@Rick-Anderson - for `What is the right way to create absolute URL from arbitrary path?`

We'd recommend https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http.Extensions/src/UriHelper.cs#L48

**Comment by rynowak** [comment]
Do you need help with any of the other items listed here?

**Comment by Rick-Anderson** [comment]
I think they're all covered in you PR, which I'm almost finished .
