### ISSUE TITLE
Update for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by breggles** [dotnet/AspNetCore.Docs#16547]
Looks like this page is still about 2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/migration/webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Remove simple from doc. Use basic or similar.

**Comment by GabrielHSFerreira** [comment]
I had the same impression. For example, the IHostingEnvironment  is deprecated on 3.1.

**Comment by wadepickett** [comment]
Closed with #18417
