### ISSUE TITLE
Serialisation of objects in Session

### ISSUE THREAD

**Issue by KalpeshPopat** [dotnet/AspNetCore.Docs#16542]
Hi,

I have found there are many issues with serialising objects and storing them in sessions, i have highlighted my points here: https://github.com/dotnet/aspnetcore/issues/18159 and have provided an alternate approach here: https://technologymythbuster.blogspot.com/2020/01/storing-objects-in-session-in-aspnet.html.

In the documentations - i would either remove the suggestion to use serialisation as a workaround to store objects in session or add a warning "this solution should be implemented with care and recommended only when the serialised objects in the session are readonly".

The sample code also can have that warning.

Cheers,
Kalpesh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63627](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63627)

**Comment by Rick-Anderson** [comment]
Master issue: Session and state management in ASP.NET Core #17881
