### ISSUE TITLE
5.0 update: Razor Pages tutorial series

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16549]
## Update All 9 tutorials in the Razor Pages Series + app samples
* Remove most includes
  * The includes were needed when we had 3 versions of each tutorial. VS, VSC, VSmac. Now that we have tabs, they’re not necessary.
* Add the following command after  `dotnet tool install --global dotnet-aspnet-codegenerator`:
* `dotnet tool install --global dotnet-aspnet-codegenerator`: is missing in Mac version
  
* Make it clear that EF Core is not an ASP.NET Core feature

* Do a scrub of everything that doesn't [MT](https://review.docs.microsoft.com/en-us/help/contribute/localization-mt-guidance?branch=master) such as :
  * Run the app and verify you can create/edit/display   (replace / with , or appropriate)
* dotnet [SPACE] aspnet-codegenerator vs dotnet-aspnet-codegenerator #16997
* ***AS YOU UPDATE EACH RP DOC, LOOK AT BUGS IN MVC VERSION. SOME BUGS APPLY TO BOTH TUTORIALS BUT ARE ONLY REPORTED IN ONE PLACE***.
*  Review the last 5-10 closed issues from each page to ensure nothing was missed or improved.

Add the following (from the MVC version of this tutorial)

Launching the app with Ctrl+F5 (non-debug mode) allows you to make code changes, save the file, refresh the browser, and see the code changes. Many developers prefer to use non-debug mode to quickly launch the app and view changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BartHNL** [comment]
Hello,

I read I am supposed to see the Pages folder like in this image:
https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/razor-pages-start/_static/se2.2.png?view=aspnetcore-3.1

but I see my Project Explorer like this:
http://nedcom.nl/Projects/RazorPagesMovie/RazorPagesMovie_SolutionExplorer.jpg

Do I have a wrong project or is something else at hand?

**Comment by wadepickett** [comment]
@Rick-Anderson , for the download include at the start, do you want me to get rid of the include and pull that back inline to the doc?  I understand you want to get rid of most includes related to needs we had before the IDE tabs.  The download include was more related to eliminating some version mess. Knowing if you want to keep that include gives me a better idea of how far to go in eliminating includes.

**Comment by Rick-Anderson** [comment]
Do a search and see where it's used. I think it's used in many of the tutorials, it's not related to tabs.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks, I'll check where it is used.  Sounds like I should keep the scope to tab related for eliminating includes and pulling in their text (as needed).  There were some 20+ includes, so was just checking to see if I should keep the scope to tab related or try to pull in most that I could, be they tab related or no.

**Comment by Rick-Anderson** [comment]
No problem removing an include you're not sure about as you'll get a build error if another doc requires it.
