### ISSUE TITLE
[Blazor] Blazor + EF documentation topic

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#16558]
Can we make an article about using EF with serverside Blazor in the same way we have one for Razor pages?

I wrote a comment and a sample on the pattern to follow here.

The main points are:
* Showcase how to do CRUD
* Use OwningComponentBase to isolate the usage of the context to the component it is being used in.
* Explain that if you use the context directly, the context is shared among components, which might cause multiple queries to start at the same time, and that is something that Entity Framework doesn't support.

https://github.com/dotnet/aspnetcore/issues/16745#issuecomment-549505605

**Comment by Alexander-Lazarov88** [comment]
Hi, thank you for your work and thank you for Blazor. I am very excited and used for an internal company project. I read the documentation for using EF in Blazor a couple of times, but there is an example only for using DbContext directly in the component via ServiceProvider. Can you make a more complex example when we have a specific service(with injected unitOfWork via constructor) that gets information from a repository and return data to the component? Is direct using of DbContext to get and save data in the component is good practice for server-side Blazor? Sorry if my comment is not for here and thanks for your time.

**Comment by guardrex** [comment]
> Lots of folks stumble when they try to use EF Core with Blazor Server because of the issues described in this doc. Unfortunately, the content in the Use of EF DbContext fromDI section isn't particularly discoverable. I think we should consider having a top level node in the Blazor docs about using Blazor with EF Core that covers this topic and any other related information.

https://github.com/dotnet/AspNetCore.Docs/issues/17713

**Comment by danroth27** [comment]
@JeremyLikness

**Comment by guardrex** [comment]
@javiercn ... Things were going well, then I hit an unusual :boom:. Your sample was based on an old release, so part of the work here was to upgrade it to 3.2 for this new topic.

You have a `UnitService` that looks like this (translated into 🙈 *RexHax code*:tm: 🙈) ...

In the *Shared* project ...

```csharp
public interface IUnitService
{
    Task<List<UnitDto>> GetAsync();
}
```

In the *Client* project ...

```csharp
public class UnitService : IUnitService
{
    private readonly HttpClient httpClient;
    private readonly string baseUrl = "api/Unit";

    public UnitService(HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async Task<List<UnitDto>> GetAsync()
    {
        return await httpClient.GetFromJsonAsync<List<UnitDto>>(baseUrl);
    }
}
```

`Program.Main` goes like this ...

```csharp
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.RootComponents.Add<App>("app");

    builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

    builder.Services.AddScoped<IUnitService, UnitService>();
    builder.Services.AddScoped<IProductService, ProductService>();

    await builder.Build().RunAsync();
}
```

No build error, but when it tries to register the service, it :boom: with the following.

Here's the solution thus far (it's a work-in-progress, but it might run in this state after this 🐞 is resolved) :point_right: https://github.com/guardrex/EntityFrameworkCoreSample

> System.AggregateException
> HResult=0x80131500
> Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: EntityFrameworkCoreSample.Shared.Interfaces.IUnitService Lifetime: Scoped ImplementationType: EntityFrameworkCoreSample.Client.Services.UnitService': Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'EntityFrameworkCoreSample.Client.Services.UnitService'.) (Error while validating the service descriptor 'ServiceType: EntityFrameworkCoreSample.Shared.Interfaces.IProductService Lifetime: Scoped ImplementationType: EntityFrameworkCoreSample.Client.Services.ProductService': Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'EntityFrameworkCoreSample.Client.Services.ProductService'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at EntityFrameworkCoreSample.Server.Program.Main(String[] args) in C:\Users\guard\Documents\GitHub\AspNetCore.Docs\aspnetcore\blazor\common\samples\3.x\EntityFrameworkCoreSample\Server\Program.cs:line 10
>
> This exception was originally thrown at this call stack:
> [External Code]
>
> Inner Exception 1:
> InvalidOperationException: Error while validating the service descriptor 'ServiceType: EntityFrameworkCoreSample.Shared.Interfaces.IUnitService Lifetime: Scoped ImplementationType: EntityFrameworkCoreSample.Client.Services.UnitService': Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'EntityFrameworkCoreSample.Client.Services.UnitService'.
>
> Inner Exception 2:
> InvalidOperationException: Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'EntityFrameworkCoreSample.Client.Services.UnitService'.

**Comment by JeremyLikness** [comment]
Hi @guardrex we are working on a reference sample that shows our clear guidance for using EF Core in Blazor Server projects. It does also include examples using repository, unit of work and MVVM. I am waiting for some internal review and then we'll publish the sample and look into documentation. Thanks!

**Comment by guardrex** [comment]
@JeremyLikness Excellent ... I look forward to it. In that case, it would just be interesting to hear why this service registration is failing as an FYI for future reference. It seems unusual to be failing like this.

WRT content, I have what Mike provided at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di

... which is the basis for this new topic, making sure that the text covers Javier's opening remark ...

> Explain that if you use the context directly, the context is shared among components, which might cause multiple queries to start at the same time, and that is something that Entity Framework doesn't support.

It's fairly close. It perhaps just needs the "EF doesn't support it" piece.

The new topic can reference your sample for code examples and expanations (e.g., `OwningComponentBase` and some CRUD show-'n-tell).

I'll mark this issue ON HOLD on the [Blazor project](https://github.com/dotnet/AspNetCore.Docs/projects/35) for now and then return to it when your sample is ready. Unless there's an objection, I'll drop your sample into the repo as the cross-linked example and code snippets for the new topic.

**Comment by guardrex** [comment]
btw -- You just tipped me off on what was wrong ... **_BLAZOR SERVER_**. I dropped Javier's code into a **_Hosted_** Blazor app. DUH! 🙈 lol Fortunately, I only wasted fifteen minutes with it.
