### ISSUE TITLE
Scaffolding problem

### ISSUE THREAD

**Issue by Lauyea** [dotnet/AspNetCore.Docs#16557]
Scaffold pages will not set namespace automatically.

Like scaffold students in Pages.Students folder, the namespace should be: namespace ContosoUniversity.Pages.Students

But in fact, it will be: namespace ContosoUniversity

Is this operate correctly? Or it's a new change to this function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Check the download. The scaffolder creates the correct namespace.

**Comment by Organwolf** [comment]
I've had the same problem. I see that that isn't an issue in the github project but I have followed the instructions but all of my scaffolding has ended up under the "ContosoUniversity" namespace which is leading to 40+ errors.

**Comment by Rick-Anderson** [comment]
> has ended up under the "ContosoUniversity" namespace which is leading to 40+ errors.

You ran the scaffolder in the wrong folder

**Comment by JackStrap** [comment]
Same thing here, i followed [the instruction](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio#scaffold-student-pages). The scaffolding does not seem to update the namespace. It works well for the first scaffolding, cause the namespace is ContosoUniversity + class IndexModel, class CreateModel.
But when you do a second scaffolding, the namespace is still just ContosoUniversity + class IndexModel... it's a that point you receive 40+ errors.
![image](https://user-images.githubusercontent.com/21227974/72740921-a644e700-3b74-11ea-8a2e-7c53a34f8796.png)

Thanks

**Comment by Rick-Anderson** [comment]
You ran the scaffolder in the wrong folder

**Comment by MrMuzzio** [comment]
Same here, tried several folders but everytime I end up with the wrong namespace. The Students and the Courses scalffolding process set the namespace to "ContosoUniversity". 
I understand you must run the scaffolding over the "Pages\Courses" and "Pages\Students".
Any help would be great, thank you !!!

**Comment by rblackmore** [comment]
Had the exact same problem, seems it doesn't work when doing it the Visual Studio 2019 way.

In the package manager console I ran the following commands (not sure if the first 2 are necessary). I also navigated the PMC to the directory my *.csproj file is in, not sure that was require either.

dotnet tool install --global dotnet-aspnet-codegenerator

dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design

From the VS Code instructions in this turtorial:
dotnet-aspnet-codegenerator razorpage -m Course -dc SchoolContext -udl -outDir Pages\Courses --referenceScriptLibraries

I hope this helps some future people when they get stuck here, and come looking for the solution in the feedback section.

**Comment by smiller7812** [comment]
I had the same problem.  I did not run scaffolding on the wrong folder either or the new pages would end up in the wrong folder.  What happens is for example on the original Pages/Students/Index page the page model is "Index".  Then in courses the scaffolding also names it index.  Now you have to ContosoUniverstiy.Index classes and the compiler complains.  This happens for all the scaffolded pages: Delete, Details, etc.  I just went through all the pages under the Courses folder and renamed the namespace from "ContosoUniversity.IndexModel" to "ContosoUniversity.Courses.IndexModel" for example on the index page.

**Comment by smiller7812** [comment]
I'm actually surprised VS 2019 and Core 3 does this mistake for Razor Pages.  Why not add the sub folder into the namespace as has been the convention for years and years.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
