### ISSUE TITLE
_SelectLanguagePartial.cshtml Code does not remember the value selected

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/AspNetCore.Docs#16563]
Documentation is badly incomplete surrounding the saving of the value of the drop-down in that so it can remember.

When you create the _SelectLanguagePartial.cshtml and place it in your layout file it changes the language and the cookie is created.

However, once you navigate off the page it does not remember the cookie value in the dropdown and reverts back to default Language and not the chosen culture also most language selectors would display the countries flag and feel that the documentation should be set up to show how to do that as well.

_SelectLanguagePartial.cshtml

Please see video of the problem 

https://www.screencast.com/t/vV3Z8nJMXYO

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidbuckleyni** [comment]
This does not fix the problem !!!!!! why is the bot closing these issues

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
Sure, but give me some time coz I'm suffering in my country due a problem with the Internet cable issue

Hope to have a look ASAP

**Comment by hishamco** [comment]
@davidbuckleyni I don't have flash player, AFAIK `_SelectLanguagePartial.cshtml` should work as expected we already implement such thing in OrchardCore and SimplCommerce

**Comment by LazZiya** [comment]
@davidbuckleyni, if the language is changing when you change the page there could be different reasons:
- Make sure you have gave your consent (accepted the GDPR cookie), otherwise the app wont be able to use cookies.
- Make sure that `CookieRequestCultureProvider` is not removed from the request culture providers list.
- Also the order of culture providers is important and may affect the culture fallback behavior.

Re the country flags, there is many css libraries that provides flags named by their relevant country/culture.
- https://flag-sprites.com/
- https://flagicons.lipis.dev/
- [LanguageNavTagHelper](https://github.com/LazZiya/TagHelpers/wiki/LanguageNav-TagHelper-Setup) it creates the language navigation dropdown w/o flags, you may see it in github.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by wstaelens** [comment]
I only got it working by this:
https://stackoverflow.com/a/66411764/187650 

I had to change SameSiteMode.None to Unspecified.
```
services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential 
            // cookies is needed for a given request.
            options.CheckConsentNeeded = context => true;
            // requires using Microsoft.AspNetCore.Http;
            //options.MinimumSameSitePolicy = SameSiteMode.None;
            options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
        });
``` 
https://github.com/dotnet/AspNetCore.Docs/issues/8491#issuecomment-1062758324
