### ISSUE TITLE
Error in documentation when Enabling cors as attribute

### ISSUE THREAD

**Issue by DarkFM** [dotnet/AspNetCore.Docs#16574]
The doc asserts that the call to "app.UseCors()" is unesscary when trying to enable CORS for only specifi endpoints and not have it apply globally.
This issue was raised here [Link](https://github.com/dotnet/aspnetcore/issues/17830).
Please update the docs to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-attributes)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DarkFM  where does it say that? Can you copy/paste the instructions?
