### ISSUE TITLE
Some issues in VS Code version

### ISSUE THREAD

**Issue by Justin-ZS** [dotnet/AspNetCore.Docs#16580]
> In the RazorPagesMovie project, create a new folder called Data. Add the following RazorPagesMovieContext class to the Data folder

Should be:

* Add a folder named *Data*.
* Add a file to the *Data* folder named *RazorPagesMovieContext.cs*.
* Add the following *RazorPagesMovieContext* class to the file.

> Use SQLite for development, SQL Server for production

`MovieContext` should be `RazorPagesMovieContext`
`app.UseDatabaseErrorPage()` should be removed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-a-database-context-class)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Add the following `RazorPagesMovieContext ` class to the _Data_ folder

That doesn't need to be two steps.

> Use SQLite for development, SQL Server for production

We'll fix that in the next sweep. It shows how to use the two DB's.

> `app.UseDatabaseErrorPage()` should be removed

Why?

**Comment by Rick-Anderson** [comment]
Moved to Master Issue #15941

**Comment by Justin-ZS** [comment]
@Rick-Anderson 
I'm an ASP.Net novice, using MacOS and VScode. 

> Add the following RazorPagesMovieContext class to the Data folder . 

I'm confused. How can I add a `class` to a folder?
> app.UseDatabaseErrorPage() should be removed

After copy/paste all code, `UseDatabaseErrorPage` is still a undefined method.
Also, the offical demo [repo](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie30) doesn't has this line code.
