### ISSUE TITLE
Paths on Linux container 

### ISSUE THREAD

**Issue by BWCutters-DBirch** [dotnet/AspNetCore.Docs#16657]
I suggest documentation is updated to use `env.WebRootPath` rather than `Directory.GetCurrentDirectory()`
since the former is cross platform and the later is not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.ihostingenvironment.webrootpath

@BWCutters-DBirch  thanks for pointing that out.

**Comment by Rick-Anderson** [comment]
Moved to Static files master issue and update to 3.1 #13599
