### ISSUE TITLE
Returns null

### ISSUE THREAD

**Issue by KenDarlingPAF** [dotnet/AspNetCore.Docs#16664]
I am trying to get the user name of the user using the my app (published to an IIS server) when I run it local It is able to pick up my user name, but once it is deployed it does not seem to be able to pull user name data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KenDarlingPAF ... I've marked this for triage on the Blazor.Docs project. They might ask you to move it to the engineering repo. They should take a look on Friday. Stand-by for them to see this and react.

**Comment by guardrex** [comment]
@KenDarlingPAF, did you ever figure out the problem? If not, there's not enough information in your post. Explain what you've set up ... show code. Sometimes a cross-linked repro project is best, but you can just put the code snippets in here (use triple-backticks for code blocks).

**Comment by mkArtakMSFT** [comment]
Closing as there was no response here for about 2 weeks now.
