### ISSUE TITLE
3.1 update: Custom storage providers for ASP.NET Core Identity

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/AspNetCore.Docs#16679]
1. It is not clear which sample is meant by linked [The sample app](https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/identity/sample) repo.
2. Using `dotnet new mvc -au Individual`, as doc says, doesn't add `Microsoft.AspNetCore.EntityFramework.Identity` nuget package, but in [Reconfigure app to use a new storage provider](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#reconfigure-app-to-use-a-new-storage-provider) the first step is removing this package.

Also identity is very important and I expect better documentation about customizing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#reconfigure-app-to-use-a-new-storage-provider)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MaherJendoubi please review

**Comment by awaisshabir** [comment]
Custom storage providers for ASP.NET Core Identity is working fine if you followed the tutorial but only one problem i am facing the user claim is null

**Comment by WayneHiller** [comment]
Has anyone tried using this example in a Blazor WebAssembly app? I see they switched to Using IdentitySever for client side.
