### ISSUE TITLE
Avoid memory leaks when invoking .NET instance methods

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#16682]
From @partyelite (moved from https://github.com/aspnet/AspNetCore.Docs/issues/16680) ...

There is nothing in the docs about avoiding memory leaks. I dug through the MS docs and found this link

https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference-1?view=aspnetcore-3.1

It says here that in order to avoid leaking memory, the DotNetObjectReference (used for invoking .NET instance methods from JavaScript) must later be disposed by JS code or by .NET code.

What is the best practice for disposing DotNetObjectReferences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @partyelite ... It hasn't come up in content generation or review of what we show, nor have I been able to locate engineering repo issues or PRs directly pertaining to that remark in the API doc.

I've marked this for triage on the Blazor.Docs project. These issues are usually triaged on Fridays. Engineering will comment on it when they see this shortly. Stand-by for their response. Thanks for writing in about it.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS do you know what the `disposed by JS` part mean:

> To avoid leaking memory, the reference must later be disposed by JS code or by .NET code.

Can you please suggest what should be the preferred way for disposing of DotNetObjectRefrence type? Thanks!

**Comment by SteveSandersonMS** [comment]
The preferred way is to call Dispose on the DotNetObjectRefrence instance, usually within the Dispose method of the component that created it.

**Comment by guardrex** [comment]
Our "HelloHelper" example doesn't assign a `DotNetObjectReference` ... it just calls `Create` ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1#instance-method-call

... so this implies that disposal is only required **_IF_** it's held (assigned to a field/property) by the class/component. Is that correct?

**Comment by guardrex** [comment]
I'm going to merge the current PR #16828 and leave this issue open so that the PR doesn't block me from splitting the JS Interop topic. The last question here is .......

> Help me on the JS scenario because in the tests I can't grok the `unimportant`/`object` pattern for `.dispose()` in JS code ...
>
> https://github.com/dotnet/extensions/blob/master/src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs#L256
>
> That looks like a contrived test where `.dispose()` isn't actually called client-side (i.e., it looks like a **_simulated_** `.dispose()`). What should be shown there in the context of the examples we're using that will dispose of an instance method from JS? Here's our current example ...
>
> https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerSample/wwwroot/exampleJsInterop.js#L15-L18

**Comment by guardrex** [comment]
@mkArtakMSFT I figured out the JS client-side disposal scenario. It was easier than I originally thought. Simply placing a `dotnetHelper.dispose();` in the `sayHello` FN demos it ...

```javascript
sayHello: function (dotnetHelper) {
    dotnetHelper.dispose();
    return dotnetHelper.invokeMethodAsync('SayHello')
      .then(r => console.log(r));
  }
```

The expected error is generated ...

> Error: Microsoft.JSInterop.JSException: System.ArgumentException: There is no tracked object with id '1'. Perhaps the DotNetObjectReference instance was already disposed.

I'll add the scenario to the PR that deals with JS interop content right after we get the JS interop split PR merged. I should have the next PR up tomorrow (Thursday).

**Comment by webebox** [comment]
I have the same problem
