### ISSUE TITLE
how is AuthenticationProperties.RedirectUri intended to be used ?

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#16726]
so I set `AuthenticationProperties.RedirectUri`
after I do 
`await HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity), authProperties);`
and, the redirect doesn't happen in the line above
atm I think I'll just call:
```
if (input.ReturnUrl != null) return Redirect(input.ReturnUrl);
return RedirectToAction("Index", "Home");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by HaoK** [comment]
The redirect uri is only used on a few specific paths by default, the login path and logout paths, see https://github.com/dotnet/aspnetcore/blob/f2e6e6ff334176540ef0b3291122e359c2106d1a/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L334

**Comment by 717009629** [comment]
How can it return 401 code, not redirect to login page, when user cookie authentication?

**Comment by Rick-Anderson** [comment]
`<xref:Microsoft.AspNetCore.Authentication.AuthenticationProperties.RedirectUri>`
