### ISSUE TITLE
Improve CSAT OKR: Host ASP.NET Core on Windows with IIS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16738]
[Internal bug](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1664863)

This advanced topic is inherently low CSAT.  Anyone with problems hosting that can't find a magic bullet in this doc gives it a bad rating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Closing because CSAT at 78%.
@guardrex  let me know if you disagree with my reasoning on low CSAT and if you think this needs a rewrite.

**Comment by guardrex** [comment]
I'm not a fan of CSAT; but if we go by feedback (issues), I think we're doing well. We rarely get 'I don't understand' issues ... or any issues for that matter on this one. :+1: The topic has became *Megahugenourmous*:tm: over time and probably could do with an edit pass and some slimming, if possible. IMO, it can wait. I couldn't do it right now with so many Blazor issues. 🏃

**Comment by Rick-Anderson** [comment]
@guardrex  excellent comments. I agree.
