### ISSUE TITLE
Incorrect statement about IDisposable support

### ISSUE THREAD

**Issue by mvarblow** [dotnet/AspNetCore.Docs#16747]
This statement is no longer correct:

WARNING: The ObjectPool doesn't implement IDisposable. We don't recommend using it with types that need disposal.

Please update the documentation to reflect recent changes. See: 

https://github.com/dotnet/extensions/issues/973

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075aad4c-9e53-92c1-8405-70bd5ed54baa
* Version Independent ID: fa535bff-449d-ac12-ea5b-8a975b0682f6
* Content: [Object reuse with ObjectPool in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/objectpool?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/ObjectPool.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/ObjectPool.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/73299762-debb7500-41b3-11ea-88dd-81e0b04f3c2b.png)

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/extensions/blob/v3.1.5/src/ObjectPool/src/DisposableObjectPool.cs#L41 

@gfoidl  can you draft the documentation update?

**Comment by gfoidl** [comment]
@Rick-Anderson will create a PR over the weekend (in english 😉). Can you assign this issue to me (so that GitHub shows it in my issues -- just as reminder)?
