### ISSUE TITLE
AzureAD[B2C]Defaults

### ISSUE THREAD

**Issue by Heidelberger** [dotnet/AspNetCore.Docs#16742]
"AzureAD[B2C]Defaults" is a terrible way to write "AzureADDefaults OR AzureADB2CDefaults"

Please consider changing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
`AzureAD[B2C]Defaults` won't compile - right?

**Comment by CamSoper** [comment]
Yeah, I totally agree. I don't remember doing that, but if I did, that sucks. I'll fix it.

**Comment by SushrutDeo** [comment]
Could you publish the sample to deploy this site on Azure, please?

**Comment by Heidelberger** [comment]
Thank you @CamSoper !
