### ISSUE TITLE
Link to Web SDK

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#16769]
You could add hyperlinks to the https://docs.microsoft.com/en-us/aspnet/core/razor-pages/web-sdk?view=aspnetcore-3.1 article in at least a couple places near the beginning of the article, like you do for Razor SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you'd like this one.

**Comment by serpent5** [comment]
Yep, sure. I've opened up a PR.
