### ISSUE TITLE
Is `AddRazorPagesOptions` fully supported for Blazor?

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/AspNetCore.Docs#16798]
The documentation does not mention whether the method `services.AddRazorPages().AddRazorPagesOptions(options => { });` is supported in Blazor. If it is,
an example should probably be provided (calling out any differences) as well as a link to https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authorization)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes and no ...

Yes ... indirectly ... if you're asking about (for example) a Razor component embedded in a Razor Page that has RP conventions/options applied and the component isn't routable ... the component is just going along for the ride within the RP page. Example: If the user isn't authenticated/authorized for that page, they also aren't going to get the embedded component.

No ... if you're asking if any RP option has any direct effect on routable Razor components. These are two different app models. Freestanding components are separate from RP pages, and no RP options directly apply. Components do use the same ASP.NET Core authentication bits, but RP options don't directly apply.

I like your idea of continuing to make this distinction between RP/MVC and components. We just added a bit about how Tag Helpers don't apply on https://github.com/aspnet/AspNetCore.Docs/pull/16701 ...

> Tag Helpers aren't supported in Razor components (*.razor* files). To provide Tag Helper-like functionality in Blazor, create a component with the same functionality as the Tag Helper and use the component instead.

I think we can continue to clarify along those lines, so I'll get this scheduled for work. Thanks for writing in on it.
