### ISSUE TITLE
Sample for creating key should use DateTime.UtcNow.AddDays(2)

### ISSUE THREAD

**Issue by matthawley** [dotnet/AspNetCore.Docs#16800]
Per the documentation on key expiration and rolling, it indicates that new keys should be created at with an activation date of now + 2 days. My suggestion is update the sample to also have this by default rather than DateTime.UtcNow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275ff6a6-a3f2-fb2b-6fda-4981abf46a7d
* Version Independent ID: e7547577-5c8a-ce9f-d990-b8a4cbaa5a50
* Content: [Key management in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/implementation/key-management.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The guidelines are clear in the article. Activation now might be better for testing this out.
