### ISSUE TITLE
Does InvokeAsync throw exceptions due to connectivity issues?

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/AspNetCore.Docs#16819]
> InvokeAsync calls methods on the hub. Pass the hub method name and any arguments defined in the hub method to InvokeAsync.

The docs mention that `InvokeAsync` throws exceptions originating on the server.  Does it also throw exceptions for other reasons, e.g. connectivity issues?

> The InvokeAsync method returns a Task which completes when the server method returns. The return value, if any, is provided as the result of the Task. Any exceptions thrown by the method on the server produce a faulted Task. Use await syntax to wait for the server method to complete and try...catch syntax to handle errors.

In particular, might `InvokeAsync` throw an exception that indicates a connectivity issue for which it'd be appropriate to directly respond with a retry attempt?  Or is it sufficient to deal with connectivity issues by handling the `HubConnection.Closed` event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio#call-hub-methods-from-client)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
It is sufficient to deal with connectivity issues either using the `HubConnection.Closed` event as you mention, or if you want to mitigate dropped connections in long-running client scenarios, use the `withAutomaticReconnect` feature. 

Closing this issue as I think this may be the answer you after, but if you'd like more info on this, please re-open with a comment as we're surveying the docs for opportunities to be more clear in how to use SignalR in these various ways.
