### ISSUE TITLE
Pictures do not match code

### ISSUE THREAD

**Issue by vinchatl** [dotnet/AspNetCore.Docs#16818]
There are 3 modifications from "MvcMovie" to "Movie App", as described in the instructions and highlighted in the code: title, header and footer. Although, following pictures show that footer is set to "2017[or 2015] - MvcMovie". Year doesn't really matter as you won't reupload picture every first january, but footer should be "Movie App" instead of "MvcMovie" to match code modifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@VincentChtln  thanks, we'll get this in the next doc sweep.

@wadepickett  in the next update just show

![image](https://user-images.githubusercontent.com/3605364/73612201-b655c100-458d-11ea-8d4c-4dc83b1c1d24.png)

**Comment by Rick-Anderson** [comment]
@wadepickett  on the .NET 8 refresh make sure you look at all open issues on each article. Also take a quick look at the last 10 closed issues to make sure there's not something we could improve.
