### ISSUE TITLE
Add an instruction to add a  package reference .

### ISSUE THREAD

**Issue by morrta** [dotnet/AspNetCore.Docs#16844]
IApplicationBuilder has no definition for UseDataBaseErrorPage() method. 
I fixed it by adding a reference in the csproj file : 
`<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.1" />`

better add and instruction to do that for vscode users .. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting. It's listed in the project file but not in the instructions to add it.

Moved to Add a model to a Razor Pages app : Master Issue #15941

**Comment by wadepickett** [comment]
Re-opening: Addressing this currently in an update of the entire Razor Pages Series.
