### ISSUE TITLE
add some more documentation on docker part and also add the ps command variables

### ISSUE THREAD

**Issue by machie27** [dotnet/AspNetCore.Docs#16859]
instead of linking to github for 
### docker
just show:
Export the HTTPS certificate into a PFX file using the dev-certs global tool
to `$env:APPDATA/ASP.NET/Https/<appname>.pfx using a password of your choice (recommended password new-guid on powershell)`

And for "Trust HTTPS certificate from Windows Subsystem for Linux"
Let users see if powershell or cmd is used. or specify cmd = `dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p <cryptic-password>; `
while ps variable is 
`dotnet dev-certs https -ep $env:APPDATA\.aspnet\https\aspnetapp.pfx -p <cryptic-password>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Enforce HTTPS Master issue #17356
