### ISSUE TITLE
check here first. Container issue for NSwag

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16879]
13K PV

This is the Container issue for this doc.  Reopen each issue you are working on so the owner is notified.

- [ ]  #20866
- [ ]  #16856
- [ ] #15313
- [ ]  #12082
- [ ] #18100
- [ ]  #20089

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson I think we can close this for now.
