### ISSUE TITLE
Web API: Get rid 25 moniker ranges

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16877]
25 of `::: moniker range` is ridiculous.  I wanted to make a minor update but it's too hard to figure out the right place.

cc @scottaddie 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1&branch=pr-en-us-16456&viewFallbackFrom=aspnetcore-2.0#apicontroller-attribute)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by wadepickett** [comment]
@Rick-Anderson, do you want to:
1. Toss all versions previous to a particular version?  If so, which one.  3.0?  3.1?
2.  Do you want completely separate copies of the entire document within moniker ranges for each version you want to keep?

What priority is this?  P1, P2?   

Thanks.

**Comment by Rick-Anderson** [comment]
We maintain the current version and all LTS versions,.
