### ISSUE TITLE
Confusion description about access to the HttpContext from middleware

### ISSUE THREAD

**Issue by tiesmaster** [dotnet/AspNetCore.Docs#16883]
This section at the top:
> Code can be run before a handler method executes using the page constructor or middleware, but only Razor Page filters have access to HttpContext. Filters have a FilterContext derived parameter, which provides access to HttpContext. For example, the Implement a filter attribute sample adds a header to the response, something that can't be done with constructors or middleware.

talks about constructors, and middleware, and that they don't have access to the HttpContext. Constructors surely don't, however, middleware do have access to that. Is this section talking about [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1), or is this about some more Razor page specific middleware that I'm not aware of?

It might be good to clarify what's being meant in this section, since it's going to confuse a lot of people, I suppose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think Middleware can't selectively add a header to a response (on specific pages)  before a handler method executes using the page constructor.

@dougbu  please comment.

**Comment by tiesmaster** [comment]
@Rick-Anderson Indeed, a Middleware component won't be able to selectively add an header to a Razor Page. The last sentence in itself is valid: the sample from the example is not achievable from both a constructor, as well as Middleware.

However, it's more the first sentence of the paragraph that I'm worried about. I think it's confusing, since that talks about "the page constructor or middleware", and then mentions "but only Razor Page filters have access to HttpContext.". To me, that implies that both of these things don't have access to the HttpContext, whereas Middleware does have that (yeah, that's how my brain works, maybe applying a bit too computer logic to the written text, but I think a lot of developers might fall into that trap here).

If you're not worried about the confusion, then I can close the issue, otherwise, I'd recommend rephrasing that a bit. Maybe, along the lines of:

> Code can be run before a handler method executes using the page constructor or middleware, but only Razor Page filters have access to HttpContext (middleware does have access to the HttpContext, but not to the "page context").

That's kinda a hack to fix the paragraph. It might be worth to rewrite the paragraph to start with the example. That might make it work better, but before I put additional time in for that, I'd like to see if you want to proceed with that.

**Comment by dougbu** [comment]
I'm not as familiar with the Razor Pages details as, say, @pranavkm but do think the first sentence can be interpreted multiple ways. @pranavkm what do you think about @tiesmaster's suggestion or perhaps the following?
> Code can be run before a handler method executes using the page constructor or middleware, but only Razor Page filters have access to both HttpContext and the page (middleware does have access to the HttpContext, but not to the "page context").

Do we have a better term than "page context"?

**Comment by Rick-Anderson** [comment]
Code can be run before a handler method executes using the page constructor or middleware, but only Razor Page filters have access to both `HttpContext `and the page. Middleware does have access to the `HttpContext`, but not to the "page context".

**Comment by davidfowl** [comment]
Actually with endpoint routing, a middleware could selectively add a header to to razor page 😄

**Comment by pranavkm** [comment]
Here's what the text looks like now:

> While page constructors and middleware enable executing custom code before a handler method executes, only Razor Page filters enable access to <xref:Microsoft.AspNetCore.Mvc.RazorPages.PageModel.HttpContext> and the page. Middleware has access to the `HttpContext`, but not to the "page context". Filters have a <xref:Microsoft.AspNetCore.Mvc.Filters.FilterContext> derived parameter, which provides access to `HttpContext`. For example, the [Implement a filter attribute](#ifa) sample adds a header to the response, something that can't be done with constructors or middleware.

If the intent is to show a sample of a page filter, couldn't this be reduced to, 

> Here's a sample for a page filter [Implement a filter attribute](#ifa) sample that adds a header to the response.

If there's frequent questions about how to access the page, pagemodel, or pagecontext outside of the context of the page execution pipeline, maybe add,

> Access to the page context, which includes access to the instances of the page and it's model, are only available when executing filters, handlers, or the body of a Razor Page.
