### ISSUE TITLE
Signalr .net core central exception handling

### ISSUE THREAD

**Issue by sumanrajpura** [dotnet/AspNetCore.Docs#16880]
I want to handle exception from any method of Hub onto one single location as we can do that via app.UseExceptionHandler in webapi. Is there any way to do this in signalr .net core?
I tried with GlobalHost.HubPipeline.AddModule(new ErrorHandlingPipelineModule()); but via this also exception is not getting handled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by alexb5dh** [comment]
Same question

**Comment by BrennanConroy** [comment]
There is no way to do this today outside of putting try catch inside all your hub methods.

This support will be added as part of https://github.com/dotnet/aspnetcore/issues/5353

**Comment by BrennanConroy** [comment]
Hub filters are in 5.0, you can add an exception handler filter. More details on hub filters in the docs: https://docs.microsoft.com/aspnet/core/signalr/hub-filters?view=aspnetcore-5.0
