### ISSUE TITLE
Consider putting "set URI" instructions for testing PUT method

### ISSUE THREAD

**Issue by Yonkey1111** [dotnet/AspNetCore.Docs#16901]
I got hung up on testing the PUT method because I didn't realize you had to add the item's id to the URI in postman.  It became clear to me when I looked at how to test the DELETE method, though, because it had a little note about doing that.  Thought you might want to consider adding that under testing PUT method too.  Something like this:

Set the URI of the object to update (for example https://localhost:5001/api/TodoItems/1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Yonkey1111  it's in the code
```
// PUT: api/TodoItems/5
[HttpPut("{id}")]
public async Task<IActionResult> PutTodoItem(long id, TodoItem todoItem)
```

**Comment by Rick-Anderson** [comment]
Link to https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1&branch=pr-en-us-16456#attribute-routing on the first usage of a  `[HTTP verbs](#verb)` ([provide a link to that)

**Comment by Rick-Anderson** [comment]
Make sure each method has URL. See #16497

**Comment by molamaen** [comment]
When i try to use the put method i always get Bad Request since id != todoitem.id (which is empty!!!) why my todoitem is empty? what i am doing wrong ?

here is my code:
public static async void UpdateDatatAsync(string url, Datum data)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            url = url + $"/{data.id}";
        
             //HttpResponseMessage response = await client.PutAsJsonAsync( url, data);
            HttpResponseMessage response = await client.PutAsJsonAsync(url, data);
            response.EnsureSuccessStatusCode();

            // Deserialize the updated product from the response body.
            data = await response.Content.ReadAsAsync<Datum>();
            return ;
        }

**Comment by Rick-Anderson** [comment]
See duplicate  #18834
