### ISSUE TITLE
Document "cancelable background work" pattern for components

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#16903]
https://github.com/dotnet/aspnetcore/issues/13584

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bae853d-80e3-ef81-69eb-e8276eb853fe
* Version Independent ID: 01216f14-b45c-73b0-9f1f-300e7ddd788f
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/lifecycle.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
Pattern is described here
https://github.com/javiercn/CancellableWorkBlazor/blob/master/CancellableWorkBlazor/Pages/LongRunning.razor

gist of it is:
Create a cancellation token source.
On dipose signal the token
After async call returns, call cts.Token.ThrowIfCanceled()
