### ISSUE TITLE
Selectively allowing anonymous access using HttpSys does not work

### ISSUE THREAD

**Issue by ssteiner** [dotnet/AspNetCore.Docs#16902]
I followed the instructions on this page to use HttpSys with windows auth. Set Schemes as explained above, but set AllowAnonymous to true. And I had to call app.UseAuthentication() & app.UseAuthorization() in Startup.Configure (I think the documentation should mention that).

Then in a controller having the [Authorize] attribute, I set [AllowAnonymous] on a single method, expecting the call to that particular method pass without authentication. Yet, when I make the call, I'm asked to provide credentials.

So, what is needed to mix Windows auth and anonymous access? The approach with these attributes works fine on the old OwinSelfHost, as well as when I do selective JWT authentication on Kestrel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
