### ISSUE TITLE
Add documentation for LinkParser

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#16913]
We added `LinkParser` in 3.0 to replace some functionality that people used `IRouter` for in the past. This is briefly mentioned in the 2.2->3.0 migration docs, but we should probably have a dedicated section for it.

https://github.com/dotnet/aspnetcore/pull/9728

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  after #16335 would you be interested in adding a new API app  to the samples folder using `ParsePathByEndpointName`  and stubbing out a section?

**Comment by serpent5** [comment]
Sure, I'd be happy to.
