### ISSUE TITLE
Remove code under "Up and Down methods"

### ISSUE THREAD

**Issue by Spock1024** [dotnet/AspNetCore.Docs#16928]
From the code listed above, I see: 
.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),

When I follow this tutorial using Microsoft Visual Studio Community 2019 Version 16.4.4, I get:
.Annotation("SqlServer:Identity", "1, 1"),

I am assuming the former line of code means the same thing to SQL Server as the latter, which I'm more familiar seeing, but I'm just not as sure in Visual Studio, which is the reason I'm working through the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The scaffolder changes over time, so we shouldn't be showing code. Change this to examine the up and down methods.

**Comment by Rick-Anderson** [comment]
This will be fixed in the next update.
