### ISSUE TITLE
Custom User and UserStore for Core 3.1

### ISSUE THREAD

**Issue by bigteejay** [dotnet/AspNetCore.Docs#16925]
> [Customize the user class](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#customize-the-user-class)
> When implementing a storage provider, create a user class which is equivalent to the [IdentityUser class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnet.identity.corecompat.identityuser?view=aspnetcore-2.0).
>  
> At a minimum, your user class must include an Id and a UserName property.

The IdentityUser link opens the docs, with "ASP.NET Core 2.0", selected in upper left (for "Version").

Switching Version to 3.1 yields...

> "The requested page is not available for ASP.NET Core 3.1. You have been redirected to the newest product version this page is available for."

How am I to create a custom (**very**) minimal user and store for 3.1?

The linked [sample](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers/sample/CustomIdentityProviderSample/CustomProvider/ApplicationUser.cs), and VS errors when I change my existing user class to inherit from `IIdentity` as shown, requires properties other than `Id` and `UserName` as indicated above (requires implementations of: `Name`, `IsAuthenticated`, and `AuthenticationType`).  I just want a simple way to identify registered users and restrict controllers/actions to registered users for my web app (no password, email, confirmation, account editing, etc).

I don't need all the properties, just enough to facilitate Identity (`[Authorize]` for controllers/actions) for my MVC/Razor frontend (which relies on API back-end store for users and data, rather than Project `DbContext`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm sorry this is not up to date. Hopefully we can get some help updating the doc. Closing as duplicate of #16679

**Comment by Rick-Anderson** [comment]
@scottaddie  please review versioning

> [Customize the user class](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#customize-the-user-class)
> When implementing a storage provider, create a user class which is equivalent to the [IdentityUser class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnet.identity.corecompat.identityuser?view=aspnetcore-2.0).
>  
> At a minimum, your user class must include an Id and a UserName property.

The IdentityUser link opens the docs, with "ASP.NET Core 2.0", selected in upper left (for "Version").

Switching Version to 3.1 yields...

> "The requested page is not available for ASP.NET Core 3.1. You have been redirected to the newest product version this page is available for."

**Comment by Rick-Anderson** [comment]
Fixed in  #26008
