### ISSUE TITLE
Add information about unhandled exceptions thrown in BackgroundService

### ISSUE THREAD

**Issue by kolletzki** [dotnet/AspNetCore.Docs#16938]
According to https://github.com/dotnet/extensions/issues/2758, unhandled exceptions that are thrown by an awaited method called from a `Microsoft.Extensions.Hosting.BackgroundService.ExecuteAsync` implementation are not logged and let the service hang.  
In other words: these exceptions do not crash the application, which is [intentional](https://github.com/dotnet/extensions/issues/2758#issuecomment-562710058) and [by design](https://github.com/dotnet/extensions/issues/2758#issuecomment-564695450).

It'd be great to have a small section in the [BackgroundService base class](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#backgroundservice-base-class) docs which explains this behavior.

I'm happy to provide a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good idea @kolletzki ... thanks. I'll get this scheduled.

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
