### ISSUE TITLE
Browser Link: Needs expanded description of problem it solves.

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#16949]
As pointed out by the development team, the intro should include a little more information on what the problem is that the browser link feature solves. 

Possibly something along these lines?
- Test across multiple browsers with specific settings such as screen sizes.
- Select UI elements in browsers in real-time see what markup/source it is correlated to in Visual Studio.
- Allows for real-time browser test automation and is extensible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-3.0)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by JPain** [comment]
Agreed. At brief glance, it should be refreshing the webpage when you make file changes like dotnet watch run and browser sync. However it seems to do very little towards that.
