### ISSUE TITLE
ANYWHERE we use regexes must pass a timeout

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16956]
From [this GitHub comment](https://github.com/aspnet/AspNetCore.Docs/pull/16456/files#r376756308)

ANYWHERE we use regexes (including docs) : 
* must pass a timeout. 
* Add warning.

I added the following to my doc

```
> [!WARNING]
> When using <xref:System.Text.RegularExpressions> to process untrusted input, pass a timeout. A malicious user can provide input to `RegularExpressions` causing a [Denial-of-Service attack](https://www.us-cert.gov/ncas/tips/ST04-015).
```

cc @guardrex  @scottaddie 

Should I make the preceding an include?

**Comment by guardrex** [comment]
@Rick-Anderson I think so on the INCLUDES. Do you want me to work URL Rewriting and RP conventions as "addresses" this issue? There are perhaps another couple of spots, but those aren't in topics that I wrote.

**Comment by Rick-Anderson** [comment]
@guardrex just list the topics that need the warning, I can update them.

**Comment by guardrex** [comment]
I think ... IIRC 🤔 ... they are ...

* Routing, but you have that here.
* Razor Pages Conventions - https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-3.1
* URL Rewriting - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-3.1

I don't recall others. Regex is apparently in jQuery, but I guess we're not warning off of that.
