### ISSUE TITLE
Surface ASP.NET Core on .NET Core site

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#16950]
Per `@mkArtakMSFT`

**Comment by Rick-Anderson** [comment]
ASP.NET Core mentions/links in

* [About .NET Core - Frameworks](https://docs.microsoft.com/en-us/dotnet/core/about#frameworks)

**Comment by wadepickett** [comment]
@Rick-Anderson, The About .NET Core - Frameworks page was updated earlier to list all the frameworks in the API section as (shown in screen shot below.)  So I'll close this one.  If you were envisioning something else let me know and we can re-open.  I updated the .net guide hub to point to ASP.NET Core as well just to help folks find their way from there as well: [19228](https://github.com/dotnet/docs/pull/19228)
![image](https://user-images.githubusercontent.com/10985336/85803936-2f041800-b6fd-11ea-80be-86bd940da36a.png)

**Comment by wadepickett** [comment]
Fixed with #19228
