### ISSUE TITLE
Support colorization of the @page directive for Razor Pages

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#16954]
The highlight.js language definition for CSHTML doesn't currently specify `@page` as a valid directive. Therefore, colorization isn't applied to the keyword in our code snippets. For example:

![image](https://user-images.githubusercontent.com/10702007/74208958-65a82d00-4c4b-11ea-815d-5daaf257b7d0.png)

**Comment by scottaddie** [comment]
The following Docs Engineering PR incorporates the highlight.js changes into the docs site: https://ceapex.visualstudio.com/Engineering/_git/docs-ui-assets/pullrequest/21814?_a=overview

**Comment by scottaddie** [comment]
The fix for this issue is found at https://github.com/DuncanmaMSFT/highlight.js/pull/34.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
