### ISSUE TITLE
Incomplete statement | That gRPC is hosted on ASP.NET Core under logging section

### ISSUE THREAD

**Issue by Dheeraj-GL** [dotnet/AspNetCore.Docs#16975]
Under Logging section it say "gRPC services and the gRPC client write logs using .NET Core logging. " & "Since gRPC services are hosted on ASP.NET Core"
This implies gRPC can not be used with .NET 4.X framework, which is not true. And because that is not true this means this document is incomplete and need more content to complete spl. case where it show how one can implement it with .NET 4.X framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20ca5f3-1e63-e63f-07fa-99d523488893
* Version Independent ID: e9e7c656-a610-7b17-4ca4-8342ecc7298e
* Content: [Logging and diagnostics in gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/diagnostics.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by scottaddie** [comment]
@JamesNK Thoughts on what to do about this issue?

**Comment by JamesNK** [comment]
All our documentation is for gRPC for .NET Core, which is hosted on ASP.NET Core.

**Comment by JamesNK** [comment]
I think this is fine as is. Closing.
