### ISSUE TITLE
"Enforce HTTPS in ASP.NET Core" is missing Linux documentation

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/AspNetCore.Docs#16974]
The instructions say:

> All platforms - certificate not trusted
> 
> Run the following commands:
> .NET Core CLI
> 
>        dotnet dev-certs https --clean
>        dotnet dev-certs https --trust

But the command is listed on this other page which says that it doesn't work on Linux: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio-code

And in my tests, it indeed does not work:

    $ dotnet dev-certs https --trust 
    Specify --help for a list of available options and commands.
    $ dotnet --version
    3.1.101

So it's not really for all platforms. The following sections have specific instructions for Windows, Mac, and Docker, but there are no Linux instructions. Please add Linux instructions!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 62244](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62244)

**Comment by Rick-Anderson** [comment]
Moved to Enforce HTTPS Master issue #17356
