### ISSUE TITLE
Configuring MemoryCache when out of the box enabled

### ISSUE THREAD

**Issue by eholman** [dotnet/AspNetCore.Docs#16995]
Like the documentation states that for most apps IMemoryCache is enabled it also should mention how to be able to configure it.

In my case I want to configure SizeLimit of the MemoryCache, because it's advised to do so.

Finally I found it's possible to do it in the ConfigureServices override:

    public override void ConfigureServices(IServiceCollection services)
    {
      services.Configure<MemoryCacheOptions>(options => { options.SizeLimit = 1000; });
    }
Created Doc request in order to help others who are looking for this because searching for in on the internet didn't brought me much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Note that you _can_ still call `AddMemoryCache`, even if something else has already called it. e.g.:

```csharp
services.AddRazorPages();
services.AddMemoryCache(options => options.SizeLimit = 1000);
```

`AddMemoryCache`, and most of the other `AddXXX` calls, are smart enough to register the associated services only once.

**Comment by Gaurav-Puri101187** [comment]
Any suggestion for the fact like what should be the basis of the size limit of memory cache coz it's difficult to find the size of an managed object to correctly set size of a cache entry.

Like any suggestions around maintaining the memory bounds using  IMemoryCache

**Comment by Rick-Anderson** [comment]
@serpent5  should we add your suggestion to the doc?

```csharp
services.AddRazorPages();
services.AddMemoryCache(options => options.SizeLimit = 1000);
```

**Comment by serpent5** [comment]
Yeah, that's a small addition but it would resolve this issue. I'll get it sorted.

**Comment by serpent5** [comment]
Actually, I don't think this approach is advised. There's a big warning in the topic, under [Use IMemoryCache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#use-imemorycache), that discusses how setting a size limit on the shared `IMemoryCache` is a bad idea.
