### ISSUE TITLE
Replace sample code that uses Newtonsoft.Json code with code that uses System.Text.Json

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#16998]
See https://github.com/aspnet/AspNetCore.Docs/issues/13328#issuecomment-585624666

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by software2Daniel** [comment]
enter this article to inform you about whether or not you are sensitive enter now

https://sites.google.com/aprendizajesignificativo.org/soysensible/p%C3%A1gina-principal

**Comment by Rick-Anderson** [comment]
Fixed in #17122
