### ISSUE TITLE
How to use AddDataProtection in an async way

### ISSUE THREAD

**Issue by mgraf1** [dotnet/AspNetCore.Docs#17038]
Under the "Azure Storage" section, the following code snippet is displayed

```
var tokenProvider = new AzureServiceTokenProvider();
var token = await tokenProvider.GetAccessTokenAsync("https://storage.azure.com/");
var credentials = new StorageCredentials(new TokenCredential(token));
var storageAccount = new CloudStorageAccount(credentials, "mystorageaccount", "core.windows.net", useHttps: true);
var client = storageAccount.CreateCloudBlobClient();
var container = client.GetContainerReference("my-key-container");

// optional - provision the container automatically
await container.CreateIfNotExistsAsync();

services.AddDataProtection()
    .PersistKeysToAzureBlobStorage(container, "keys.xml");
```

In this example, how are async calls awaited in methods like `await container.CreateIfNotExistsAsync()` while still being able to access the `IServiceCollection` to call `services.AddDataProtection()
    .PersistKeysToAzureBlobStorage(container, "keys.xml");`? The `ConfigureServices` methods in Startup is not an async method. Is some other mechanism being used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
THis is a C# question, not ASP.NET COre.

**Comment by mgraf1** [comment]
@Rick-Anderson 

I disagree that this is not an ASP.NET Core question. Async startup tasks have been a point of confusion for ASP.NET core developers.

There are articles out there like [this one](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-1/) which go over several possible approaches, but it would be nice for Microsoft to give some guidelines.

Making blocking async calls is widely considered bad practice. When you need to do something from an ASP.NET Core application on startup that only has async APIs such as working with blob storage containers, the guidelines are unclear.

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Key storage providers in ASP.NET Core #17625

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We recommend moving y our async code into the `Program.Main` method (note, that you will need to have your Main as async).
Alternatively, blocking in `ConfigureServices` is not problematic and you can do that as that happens only once during the lifetime of the application at startup.
