### ISSUE TITLE
C# (Xamarin) client unable to receive SignalR (Core) event with custom object

### ISSUE THREAD

**Issue by VictorK1902** [dotnet/AspNetCore.Docs#17032]
[EDIT by guardrex to add code blocks]

My web (JS) client has no issue receiving the event with custom object but my Xamarin (C#) one does.

Eventually I had to go back and list all the properties on the server hub and config the client accordingly to read and parse these.

So given the type:

```csharp
NewMessageResponse {
    public string Message{ get; set; }
    public Guid ID { get; set; }
}
```

The following doesnt work:

ServerHub:

```csharp
Clients.Clients(stringIds).NewMessage(new NewMessageResponse () {
    Message = "Test", ID = Guid.Empty
});
```

C#/Xamarin client:

```csharp
hubConnection.On<NewMessageResponse>("NewMessage", (response) => {
    // print message
});
hubConnection.On<string, Guid>("NewMessage", (Message, ID) => {
    // print message
});
```

The following approach works:

ServerHub:

```csharp
Clients.Clients(stringIds).NewMessage("Test", Guid.Empty);
```

C#/Xamarin client:

```csharp
hubConnection.On<string, Guid>("NewMessage", (Message, ID) => {
    // print message
});
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f06ca2b-9d96-9979-46a8-d09900af0653
* Version Independent ID: 0f0d321d-46ed-25cb-6bb4-e4611343b131
* Content: [SignalR API design considerations](https://docs.microsoft.com/en-us/aspnet/core/signalr/api-design?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/api-design.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/api-design.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @anurse
* Microsoft Alias: **anurse**

**Comment by BrennanConroy** [comment]
This doesn't reproduce with a C# client outside of Xamarin, which points to some linker issue probably.

Could you try running your app with the linker disabled to rule out linker issues? https://docs.microsoft.com/xamarin/android/deploy-test/linker#linker-behavior

**Comment by VictorK1902** [comment]
@BrennanConroy Sorry for the late response. The issue turns out to be a server config. It works after I added and configed [NewtonsoftJsonProtocol](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson) in my NET Core API.
