### ISSUE TITLE
Help for ordering of app.UseXXXX

### ISSUE THREAD

**Issue by pertraindev** [dotnet/AspNetCore.Docs#17031]
It can be hard to remember the correct ordering of middleware when building an app. The information is already on this page but I think it would be great to see the full list of built-in middleware (e.g. from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#built-in-middleware) listed as pseudo code like the example in "Middleware order" (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order). The description from the "Built-in middleware" table could be comments in the code. Would be a great reference/cheat sheet. Discussed here:
https://twitter.com/davidfowl/status/1228902288627912705

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Related to  https://github.com/dotnet/aspnetcore/issues/18791
We'll likely build off that.

**Comment by scottaddie** [comment]
This request was addressed in https://github.com/dotnet/AspNetCore.Docs/pull/17623.
