### ISSUE TITLE
When is disposed services?

### ISSUE THREAD

**Issue by Orwel** [dotnet/AspNetCore.Docs#17052]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#disposal-of-services

I think all transient and scoped services are disposed at the end of request, but it isn't written explicitly.
Can you confirm this supposition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Dependency injection master issue #17298
