### ISSUE TITLE
Use virtual service accounts instead of local accounts

### ISSUE THREAD

**Issue by fowl2** [dotnet/AspNetCore.Docs#17067]
[Virtual service accounts have several advantages](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/service-accounts#bkmk-virtualserviceaccounts) over regular local accounts:
* no passwords!
* no separate creation step required

It would be great if this article could be updated to recommend or at least mention their use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=netcore-cli#log-on-as-a-service-rights)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue, look here first. #18118

**Comment by guardrex** [comment]
@Rick-Anderson ... Closing this one. The topic already cross-links to the correct coverage for Group Managed Service Accounts on Line 133 of the topic. I recommend that we let devs use this approach :skull: **_at their own risk_** :skull: given that (IIRC) these types of accounts use the computer account to run the service.
