### ISSUE TITLE
Extend User vs Claims

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/AspNetCore.Docs#17065]
Is there a link that can explain when we should extend the user and when we should use claims?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gbjbaanb** [comment]
I think putting the claims in stores them in the cookie that is passed arond for every call, so if you want a commonly used parameter for each user (eg an isadmin one) and you do not want to fetch the entire user object, then claims work better - saves you a DB hit.

On the other hand, if you are fetching the user object anyway, then reading the data from there makes more sense. Putting more user claims in means a larger auth cookie.

**Comment by alij** [comment]
In the example above the JwtClaimTypes.Role, VS says JwtClaimTypes does not exist in current context and I couldn't find any reference for it. Using just ClaimTypes.Role though seemed to work but I get the following error at runtime:

InvalidOperationException: No policy found: IsAdmin.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, object resource, string policyName)
Sampql.Pages.Shared.Pages_Shared__LoginPartial.ExecuteAsync() in _LoginPartial.cshtml

@if ((await AuthorizationService.AuthorizeAsync(User, "IsAdmin")).Succeeded)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
