### ISSUE TITLE
Cannot use UIFramework because it is an internal enum

### ISSUE THREAD

**Issue by thePmr** [dotnet/AspNetCore.Docs#17070]
In ASP.NET Core 3.1:
```
services.AddDefaultIdentity&lt;ApplicationUser&gt;()
    .AddDefaultUI(UIFramework.Bootstrap4)          // this line fails build 
    .AddEntityFrameworkStores&lt;ApplicationDbContext&gt;();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#customize-the-api-authentication-handler)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @thePmr ... see :point_right: https://github.com/dotnet/aspnetcore/issues/13111.
