### ISSUE TITLE
Mention how to turn on Detailed Errors?

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#17071]
Using a razor component, the following error showed up in the console:

>  Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 

After looking through the documentation, I didn't find anything about adding "DetailedErrors" to `appsettings.Development.json".

I added the following, which works great after an app restart.

`"DetailedErrors": true`

Since a razor component error is suggesting this, can this be added to this docs page or another more appropriate one, which this docs page links to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
When the framework provides a suitable error message, we generally don't include that content. However, this would be great for the *upcoming* debug topic, so I'll cross-link this issue to that one and add your content to a comment there. Thanks for mentioning it.

**Comment by guardrex** [comment]
I'm reactivating this for the new *Handle errors* topic that we put into place ... we put the topic up without mentioning this. It's part of the default template, so that might be why more devs aren't asking about it these days.
