### ISSUE TITLE
Error on post in this example

### ISSUE THREAD

**Issue by leandroborgesca** [dotnet/AspNetCore.Docs#17072]
For the post method example, I get System.InvalidOperationException: No route matches the supplied values.

body:

{
	"name":"walk dog",
	"isComplete":true
}

Method:

  [HttpPost]
        public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; PostTodoItem(TodoItem item)
        {
            _context.TodoItems.Add(item);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(HttpGetAttribute), new { id = item.Id }, item);
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by leandroborgesca** [comment]
No, does not work, at least in version 2.1. I didn't miss any step. The CreatedAtAction does not work. If I change it for  

return Created(nameof(GetTodoItem), new { id = item.Id, name = item.Name, isComplete = item.IsComplete });

it works
