### ISSUE TITLE
Loading... An unhandled error has occurred. Reload

### ISSUE THREAD

**Issue by openstud** [dotnet/AspNetCore.Docs#17081]
Unfortunately I have tried this twice and am getting the same results for the index.razor page.  I have updated VS to the newest version, used the cli to get the template, picked webassembly (not server), followed all these instructions and won't load the index page... Any ideas?  seems pretty tricky to troubleshoot, I can't even hit any break-points for the code...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by openstud** [comment]
Ok so I did a Rebuild Solution and ran it again and it works!!!  after smashing my forehead for 2 hrs...  Excellent work on the tutorial!  Ok now I'm off and running :)

**Comment by julianperrott** [comment]
For anyone who may also get this error. I had the same issue which was due to using the 3.1.0 version of the Blazor packages. This issue went away when I used 3.2.0

**Comment by anitconsultantllc** [comment]
Thanks for saving me 2 hours today,  @[openstud](https://github.com/dotnet/AspNetCore.Docs/issues/17081#issuecomment-589492106).  Put simply, this part couldn't be more **highlighted** right now to help those coming after the previous post from  @[julianperrott](https://github.com/dotnet/AspNetCore.Docs/issues/17081#issuecomment-591354376).  Please update the [docs ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=netcore-cli#create-a-hosted-blazor-webassembly-app-project)to change this part to be red, pink, or yellow.  Just anything **NOT** like the remainder of the documentation and you'll get much faster adoption for **Blazor WebAssembly**.

![image](https://user-images.githubusercontent.com/6926175/79250949-1ea20800-7e45-11ea-8db4-e549254f00b0.png)
