### ISSUE TITLE
On Linux: command not found

### ISSUE THREAD

**Issue by gorlok** [dotnet/AspNetCore.Docs#17085]
On Linux, dotnet aspnet-codegenerator could fail with "Could not execute because the specified command or file was not found." 
In such case, you need to add to your path: $HOME/.dotnet/tools

For instance, to add it to the path: 
$&gt; echo 'export PATH=$PATH:$HOME/.dotnet/tools' &gt;&gt; ~/.profile
And to reload profile:
$&gt; source ~/.profile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the tip.
