### ISSUE TITLE
Incorrect date for Tutorial: Create a web API with ASP.NET Core

### ISSUE THREAD

**Issue by rodogd** [dotnet/AspNetCore.Docs#17082]
The posted date for this article is in the future (February 25th 2020)

![image](https://user-images.githubusercontent.com/1495386/75004474-782f1d00-5428-11ea-8532-24fbb675e04f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hang on a few days and it will be correct. I fixed it faster than I anticpated.
