### ISSUE TITLE
Confusing text under "Components"

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/AspNetCore.Docs#17089]
"Razor Pages and MVC also use Razor. Unlike Razor Pages and MVC, which are built around a request/response model, components are used specifically for client-side UI logic and composition."

Perhaps rewrite it so that it doesn't say "Razor Pages and MVC" in opposite context so soon after the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1&WT.mc_id=docsmsft-twitter#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BrunoBlanes ... thanks, but I think it's ok. That contrast is the point there: It's saying that RP/MVC also use Razor (first sentence) and how the goals differ for its use (second sentence).

**Comment by pstricks-fans** [comment]
Emphasizing the client-side and server-side might be better.

"Razor Pages and MVC also use Razor. Unlike Razor Pages and MVC, which are built around a **server-side** request/response model, components are used specifically for client-side UI logic and composition."
