### ISSUE TITLE
withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol()) Disconnect when connected

### ISSUE THREAD

**Issue by gogojames** [dotnet/AspNetCore.Docs#17099]
1.Use javascript:
connection = new signalR.HubConnectionBuilder().withUrl("/feedback")
    .configureLogging(signalR.LogLevel.Information)
    .withHubProtocol(new signalR.protocols.msgpack.MessagePackHubProtocol())
    .build();
After connecting, the server pushes the information and immediately disconnects it.
2.Use javascript:
connection = new signalR.HubConnectionBuilder().withUrl("/feedback")
    .configureLogging(signalR.LogLevel.Information)
    .build();
Will not disconnect.
Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Have you configured your server to support the MessagePackHub protocol?

**Comment by gogojames** [comment]
Please provide a case, thank you.
I checked the official website and I didn't find it。

**Comment by gogojames** [comment]
Configuration is added to the configureservices method in the statup.cs file
`services.AddSignalR()
                .AddMessagePackProtocol(options=>
                {
                    options.FormatterResolvers = new List<MessagePack.IFormatterResolver>()
                    {
                        MessagePack.Resolvers.StandardResolver.Instance
                    };
                });`

**Comment by BrennanConroy** [comment]
Looks like you found it. Is your issue resolved?

**Comment by gogojames** [comment]
No solution，I hope you.

**Comment by gogojames** [comment]
How can I help you?

**Comment by BrennanConroy** [comment]
If you're still having a problem, open an issue at https://github.com/dotnet/aspnetcore.
