### ISSUE TITLE
How to include Microsoft.AspNetCore.DataProtection to the console application?

### ISSUE THREAD

**Issue by sergtk** [dotnet/AspNetCore.Docs#17098]
How to include Microsoft.AspNetCore.DataProtection to the console application?
The code you provided does not work if I create a new console application and paste the code to it.

Is it possible to create a console application with the ASP.Net Core library dependency?

Please add clarification to the page.
Please add instruction including the creation of the projection in Visual Studio.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c171c04b-f813-59b7-6dd1-a20d72c0011f
* Version Independent ID: 95037a5f-4ac4-ba74-47a9-32919193a7fb
* Content: [Non-DI aware scenarios for Data Protection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/non-di-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/configuration/non-di-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/non-di-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-3.1#package-layout

**Comment by sergtk** [comment]
Could you provide more specific answer?
