### ISSUE TITLE
Troubles with code generation

### ISSUE THREAD

**Issue by ticianaciminari** [dotnet/AspNetCore.Docs#17107]
@Yaro77 commented on [Sun Feb 23 2020](https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/73)

If NetCore.SDK-3 is installed using xcopy in random location one should set %DOTNET_ROOT% also to successfuly use aspnet-codegenerator from command line.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [Команда dotnet aspnet-codegenerator](https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sun Feb 23 2020](https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/73#issuecomment-590049160)

Hello, @Yaro77
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check comment above from user?

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
If you install the NetCore.SDK-3  xcopy in random location you're expected to know this.

**Comment by ticianaciminari** [comment]
@Yaro77 FYI
