### ISSUE TITLE
Clarification required

### ISSUE THREAD

**Issue by eku1s** [dotnet/AspNetCore.Docs#17100]
It took me a while to work out what the below code does (referenced above), after which I realised all it was for was the three column layout. It would be nice if you added an explination to this as it's fairly insignificant bearing in mind this is a data focussed tutorial. Until I'd worked it out, I thought it had a more important function.

@{
                    int cnt = 0;
                    List&lt;ContosoUniversity.Models.SchoolViewModels.AssignedCourseData&gt; courses = ViewBag.Courses;

                    foreach (var course in courses)
                    {
                        if (cnt++ % 3 == 0)
                        {
                            @:&lt;/tr&gt;&lt;tr&gt;
                        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [Tutorial: Update related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's part of programming, figuring out how code works.

**Comment by eku1s** [comment]
Surely that's the whole point of a tutorial... with that logic, why not just forget the tutorial and just give me the code to look at?

All it requires is one line to explain the point of this section of code, as for those who are beginners, it can really help them out. I didn't ask for a condescending response, I was hoping you'd take this as constructive feedback... clearly not.

**Comment by Rick-Anderson** [comment]
With a better title, this is very discoverable. Can you fix that? Also, edit and fix the code. You can't past code into the doc page, but you can fix it here.

There are hundreds of similar snippets in this series. It's not a beginning tutorial.

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
