### ISSUE TITLE
HttpContext.Session.IsAvailable will cause an exception if not created by DI, there should be a safe way to test if session is available

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/AspNetCore.Docs#17103]
One should have a possibility to test for the availability of a session. At the moment having code that tests for 
 HttpContext.Session is null ||  HttpContext.Session.IsAvailable will throw a InvalidOperationException.

One should be able to safely test for sessions without an exception

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63351](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63351)

**Comment by Rick-Anderson** [comment]
Catch the exception.

**Comment by davidfowl** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
IsAvailable is intended to check for transient failures (e.g. temporarily lost connection to the database). The InvalidOperationException means that the app never had session properly set up and it will fail for all requests.

Is this a library and you're trying to test if the app set up session for you? In that case you can do something like `HttpContext.Features.Get<ISessionFeature>()?.Session != null`.

**Comment by PeterPann23** [comment]
Yes, one can go and test for that however the recommended practice is that you are able to test and not go an raise exceptions to swallow them.

Good thing that File.Exists was written, or TryGet in dictionaries and TryParse on value types. The work around going over the DI is causing issues when the interface changes and I think bad practice. 

You should be able to test for null or test for the property and as you already have IsAvailable ...

**Comment by Tratcher** [comment]
Is this a library and you're trying to test if the app set up session for you?

**Comment by Rick-Anderson** [comment]
Master issue: Session and state management in ASP.NET Core #17881
