### ISSUE TITLE
Writing a custom scaffolder using aspnet-codegenerator...

### ISSUE THREAD

**Issue by gkochanowsky** [dotnet/AspNetCore.Docs#17117]
I think is possible to create a custom scaffolder. It would be nice if there were some documentation as to how to do this. The out of the box scaffolders are nice but they are really just a starting point for an organization specific scaffolder.

[Please don't close this base on an issue posted on your very first version of Core from four years ago after four year of changes. That is a very thoughtless thing to do. Besides that post was based on a hack I made. I'm trying to use whatever extensiblity that exists in aspnet-codegenerator.]

**Comment by Rick-Anderson** [comment]
@gkochanowsky  can't you just fork https://github.com/aspnet/Scaffolding and modify the scaffolder?

@deepchoudhery would have to write the doc, and I don't think he has time.

**Comment by scottaddie** [comment]
@gkochanowsky Why not create a template to use with `dotnet new`? Both item and project templates are supported. The documentation is at https://docs.microsoft.com/dotnet/core/tutorials/cli-templates-create-item-template.

**Comment by gkochanowsky** [comment]
@scottaddie I looked at that. Maybe I'm mistaken, but isn't that a facility for generating a project from scratch? I'm looking for something to generate code in an existing project from one or more  models. Would dotnet new that work? If so how would you make it work?

**Comment by scottaddie** [comment]
@gkochanowsky The `dotnet new` approach is capable of adding code to an existing project. Custom parameters can be defined to pass data into the template. What kind of code do you want generated, and what information would be inferred from the existing models?

**Comment by gkochanowsky** [comment]
@scottaddie, I'm looking for similar functionality to aspnet-codegenerator functionality when a model is specified in terms of using reflection to determine all the properties of a model class and using that to generate code for many files.

**Comment by gkochanowsky** [comment]
@scottaddie, I'm also looking for it to work from a project local template directory that can be modified by the user specifically for that project.

**Comment by scottaddie** [comment]
@vijayrkn What do you recommend for @gkochanowsky? I don't think this is easily accomplished with `dotnet new`.

**Comment by deepchoudhery** [comment]
we can (and plan to use) dotnet new for very simple scaffolders (empty controllers, and views) but for scaffolders that have model reflection, we have to use aspnet-codegenerator.

**Comment by gkochanowsky** [comment]
@deepchoudhery, I've forked the project, how to I develop and debug with it?

**Comment by thestonehead** [comment]
I would also be interested in knowing how to add custom scaffolders either to aspnet-codegenerator or Visual Studio. Can't find the documentation anywhere.

**Comment by daviddionys** [comment]
I came across [this article](https://dotnetthoughts.net/custom-scaffold-templates-in-asp-net-core/) which explains how it is done.  Worked perfectly well for me for overwriting view templates.

**Comment by thestonehead** [comment]
I have seen this method before, but this only *overrides existing* templates. I wanted to make *entirely new* ones.

**Comment by Rick-Anderson** [comment]
Feel free to create an issue in https://github.com/dotnet/Scaffolding/issues
