### ISSUE TITLE
Missing Nuget packge (breaks tutorial)

### ISSUE THREAD

**Issue by Tintow** [dotnet/AspNetCore.Docs#17118]
The project also needs the Microsoft.EntityFrameworkCore.InMemory Nuget package adding otherwise the UseInMemoryDatabase in the Register Database Context section fails  in Core 3.1

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#register-the-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's listed in the instructions

**Comment by pandeyvaibhav** [comment]
I also encountered same issue. Where is this instruction provided to add this Nuget and assembly reference - using Microsoft.EntityFrameworkCore.InMemory;??

**Comment by LeoCosta16** [comment]
Thanks for the help, i was trying to figure out what was wrong in my code. I install the Microsoft.EntityFrameworkCore.InMemory Nuget package and now it's working and I can continue the tutorial

**Comment by Rick-Anderson** [comment]
That's listed in the instructions
