### ISSUE TITLE
I'm having error following the Razor page creation tutorial.

### ISSUE THREAD

**Issue by teshalecaleb** [dotnet/AspNetCore.Docs#17110]
Cant create a new Scaffolded Item in Razor pages  "https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio#scaffold-the-movie-model" as the tutorial implies; i'm using the latest version of visual studio 2019 with asp.net core 3.1 with all the appropriate Prerequisites installed , here is the pic of error message i keep getting.
![error_pic](https://user-images.githubusercontent.com/34672036/75233601-2987d700-57ca-11ea-91ce-6eed52355a88.png)

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
