### ISSUE TITLE
Custom aspnet-codegenerator....

### ISSUE THREAD

**Issue by gkochanowsky** [dotnet/AspNetCore.Docs#17113]
I think is possible to create a custom scaffolder. It would be nice if there were some documentation as to how to do this. The out of the box scaffolders are nice but they are really just a starting point for an organization specific scaffolder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You've already opened an issue in the correct place.
https://github.com/aspnet/Scaffolding/issues/159

**Comment by gkochanowsky** [comment]
I feel like I'm getting the runaround. You're closing an issue based on a issue opened 4 years ago on a product that has undergone dramatic change. Please reopen this and address it based on what is on the ground on February 2020.

**Comment by Rick-Anderson** [comment]
Any documentation on custom documentation would need to come from the scaffold team. We're not resourced to do that. You can leave a note in the issue you opened.

**Comment by gkochanowsky** [comment]
I originally posted the issue on the dotnet aspnet-codegenerator page [
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1]
is that not the place to post issues regarding dotnet aspnet-codegenerator?

**Comment by Rick-Anderson** [comment]
Yes, on using the tool, not writing a new one.

**Comment by gkochanowsky** [comment]
My understanding based on what I discovered in previous issues is there is
a method in the current code for creating custom scaffolders. It's not
documented, at least not on the dotnet aspnet-codegenerator page. I've been
unable to find any documentation.

**Comment by gkochanowsky** [comment]
As you can see, three years back it was added to the code:

https://stackoverflow.com/questions/41352970/writing-custom-code-generator-for-dotnet-core

https://github.com/aspnet/Tooling/issues/922

The stuff I did was four years back, when core was in its first RC. I would
prefer to use what was implemented, but it is not documented. Also that was
three years ago. Has anything changed?
