### ISSUE TITLE
Is this related to windows services?

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#17126]
Can i register this as an windows service? if so please do provide a link how to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hoksource ... Yes, you can do that. Create the app per the instructions in this topic and then follow the instructions in https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service to deploy the app as a Windows Service.

**Comment by hoksource** [comment]
Thank you for the quick response. :)

**Comment by lakshya-itt** [comment]
Which class is available in worker service in place of NotifyIcon class in Windows service?
