### ISSUE TITLE
Add link about customizing SignalR

### ISSUE THREAD

**Issue by stevenjamesfrank** [dotnet/AspNetCore.Docs#17127]
Under Users, it states: "By default, SignalR uses the ClaimTypes.NameIdentifier from the ClaimsPrincipal associated with the connection as the user identifier."

I would like to change this default behavior (to use the currently logged in user's name (Identity)).  But I see no additional documentation about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Hmm, we do have a section about customizing it at https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#use-claims-to-customize-identity-handling

We should add a link to it from the groups.md page.

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you can fix this.

**Comment by serpent5** [comment]
Sure, will do.

**Comment by serpent5** [comment]
@Rick-Anderson This can be closed, as it was fixed in the linked PR.
