### ISSUE TITLE
Server GC could lead to huge performance issues in containerized applications

### ISSUE THREAD

**Issue by aienabled** [dotnet/AspNetCore.Docs#17123]
As many applications are often hosted in docker containers now, it's important to note that hosting more than a single application with default Server GC configuration and no docker container memory limit will result in this application to allocate a heap and a GC thread for each CPU core which will result in a very low total throughput (and much higher memory usage than necessary) when there is more than a single container/application running on this machine.

It's recommended to either set up a heap number limit in the application configuration (probably the best option in the most scenarios; should be done with also disabling the GC affinity), or limit the docker container's available memory amount, or even switch to Workstation GC as it doesn't allocate extra heaps (though it will result in more often GC calls so overall throughput would suffer).

Further read:
https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2019-update/
https://devblogs.microsoft.com/dotnet/middle-ground-between-server-and-workstation-gc/
https://devblogs.microsoft.com/dotnet/running-with-server-gc-in-a-small-container-scenario-part-0/
https://devblogs.microsoft.com/dotnet/running-with-server-gc-in-a-small-container-scenario-part-1-hard-limit-for-the-gc-heap/

I've personally stumped on this issue—as the number of dockerized applications increased on a virtual machine I've noticed surprisingly long GC pauses in every one of them even though the CPU load was still low. It took a while to figure out what's causing it. Somehow I've missed the point that Server GC assumes that the whole machine's resources (all available CPU cores and memory) are available to the process so having more than a single process will result in memory overuse and high threads contention.
Also, I'm definitely not the first to have this issue, e.g. https://github.com/aspnet/AspNetCore/issues/3409#issuecomment-437391232

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9e2f78-9caf-3b88-05a6-537e031ecddf
* Version Independent ID: 06ca8420-5ca0-24ae-3584-9a4c486d3ebe
* Content: [Memory management and patterns in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@spboyer  please review.

**Comment by spboyer** [comment]
@richlander to review

**Comment by Rick-Anderson** [comment]
It seems pretty obvious to me that when hosting multiple docker instances you should profile under load to see if GC should be changed from server to workstation.

I'm going to add that to the doc unless @richlander  or @Maoni0 disagree
