### ISSUE TITLE
Text about `RequireAuthorization` is not correct.

### ISSUE THREAD

**Issue by michielvoo** [dotnet/AspNetCore.Docs#17128]
This document states:

&gt; The DefaultPolicy is triggered by `[Authorize]` or `RequireAuthorization`

But this is not true for the following uses of `RequireAuthorization`:

    app.UseEndpoints(builder =>
    {
        builder.MapRazorPages().RequireAuthorization();
        builder.MapControllers().RequireAuthorization();
    });

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/17300.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
