### ISSUE TITLE
C#8 Nullable ref types - returnUrl field is required

### ISSUE THREAD

**Issue by djhmateer** [dotnet/AspNetCore.Docs#17145]
When scaffolding out the Identity code and I have C#8 nullable ref types checking set in the .csproj

```
<Nullable>enable</Nullable>
```
I need to change the methods which have a default value set to null eg

```
public async Task OnGetAsync(string returnUrl = null)
```

to be a nullable string ie `string?` otherwise, the UI will set ModelState error giving returnUrl field is required

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli#scaffold-identity-into-a-razor-project-with-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@deepchoudhery  do you want to transfer this issue?

**Comment by deepchoudhery** [comment]
> @deepchoudhery do you want to transfer this issue?

Not an admin so cannot. Feel free to transfer it please.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/1270
