### ISSUE TITLE
[Blazor][Wasm] Authentication docs

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#17144]
Here are the docs for the new authentication options in Blazor Webassembly. Work with @mkArtakMSFT and @danroth27 on giving them a sensible structure.
https://gist.github.com/javiercn/85a6d4ce46a78239ccb427baad3a66da

There are placeholders for the relevant Azure Active Directory and Azure Active Directory B2C walk-through docs. Replace those with the relevant links to the AAD and B2C sections. Separately i'm asking the AAD team for specific docs to cover our scenarios.

There are a bunch of missing images in the project creation dialog and so on that need to be added to the walk-throughts

https://github.com/dotnet/aspnetcore/issues/19283

**Comment by mkArtakMSFT** [comment]
Thanks @javiercn.
@guardrex can you please prioritize this so that this is available by March 10th?

**Comment by guardrex** [comment]
@mkArtakMSFT I'm wrapping up and submitting the new **_CSP with Blazor_** doc today (Thursday), and much of the upcoming new **_EF Core with Blazor_** topic has been addressed by Mike's supplied content. I can work on this issue immediately (best to start on Monday).

I **_DO_** need guidance on how to structure the content by topic. The titles seem to suggest  that these are *separate topics* under a Blazor WebAssembly node, which would appear under the Blazor Security node.

### Titles from the gist

* Authentication for client-side blazor applications
* Authenticating Blazor webassembly applications with Open ID Connect
* Authenticating hosted applications using Identity and the authentication and authorization support for single page applications in ASP.NET Core.
* Authenticating standalone applications using Microsoft.AspNetCore.Components.WebAssembly.Authentication
* Authenticating Blazor webassembly hosted applications using Azure Active Directory with Microsoft.Authentication.WebAssembly.Msal
* Authenticating Blazor webassembly standalone applications using Azure Active Directory with Microsoft.Authentication.WebAssembly.Msal
* Authenticating Blazor webassembly hosted applications using Azure Active Directory B2C with Microsoft.Authentication.WebAssembly.Msal
* Authenticating Blazor webassembly standalone applications using Azure Active Directory with Microsoft.Authentication.WebAssembly.Msal
* Authenticating standalone applications with microsoft accounts
* Look to be *General subject content* ...
  * Handling token request errors
  * Saving application state before an authentication operation
  * Requesting additional access tokens
  * Customizing application routes
  * Customizing the authentication user interface

### Title/TOC/UID i-dears

Here are some ideas to get the discussion going on how this content might be organized ...

* **_Blazor_** security node in the TOC
    * **_ASP.NET Core Blazor authentication and authorization_** (*Overview* in TOC)
      uid: security/blazor/index
    * **_Blazor WebAssembly_** node in the TOC
        * **_Secure ASP.NET Core Blazor WebAssembly apps_** (*Overview* in the TOC) (uses the *Authentication for client-side blazor applications* content)
          uid: security/blazor/web-assembly/index
        * ... **EACH OF THE SUBSEQUENT AUTH TOPICS ABOVE** ... `security/blazor/web-assembly/*`
        * **_Additional Blazor WebAssembly scenarios_** (uses the *General subject content*)
          uid: security/blazor/web-assembly/additional-scnearios
    * **_Secure ASP.NET Core Blazor Server apps_** (*Blazor Server* in the TOC)
      uid: security/blazor/server
    * **_Enforce a Content Security Policy for ASP.NET Core Blazor_** (*Content Security Policy* in the TOC)
      uid: security/blazor/content-security-policy
