### ISSUE TITLE
Accessing Razor Components in a different folder location

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#17148]
The below paragraph is worded confusingly. I'm pretty sure it's trying to say: "To use a custom folder, e.g. {PROJECT ROOT}/Components, add the following `@using` to the top of the page accessing the component."

Does that sound right?

> To use a custom folder, add the custom folder's namespace to either the parent component or to the app's _Imports.razor file. For example, the following namespace makes components in a Components folder available when the app's root namespace is BlazorApp:

```
@using BlazorApp.Components
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mrlife ... I'll improve that bit guided by your suggestion.
