### ISSUE TITLE
Docs for the Component Tag Helper (or how to send a string parameter)

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#17160]
[**EDIT by guardrex** to note that this issue can be worked with #17210]

I'm unable to find the docs for the Component Tag Helper, i.e. `<component>`. I'm trying to send a string as a parameter but getting a build error. I know you can send an integer, per this page of the docs, but I can only send a string if it's in a variable. Here is the code and error.

Code
```
<component type="typeof(ColorfulCheckbox)"
	   render-mode="Server"
	   param-Color="blue" />
```

Error

> The name 'blue' does not exist in the current context (CS0103)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#render-components-from-a-page-or-view)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrlife ... You're saying that it will work if you add an `int` prop to the component and assign to that (as the example shows) but as soon as you try a `string` prop it fails? Let's just rule out the possibility that this is a namespace problem. If it works for a `string` but not an `int` then we'll go to engineering with this, but if they both don't work, then troubleshoot it as a namespace issue.

**Comment by mrlife** [comment]
Hi @guardrex 

> You're saying that it will work if you add an int prop to the component and assign to that (as the example shows) but as soon as you try a string prop it fails?

Yes, that's what I'm seeing... The assignment of `10` like in the example works because it is numeric. If I add any characters, it throws the error.

> If it works for a string but not an int then we'll go to engineering with this; but if they both don't work, then troubleshoot it as a namespace issue.

Never works for raw string but raw int works fine.

Also, would it be worthwhile to have a page in the docs that provides the details of the Component Tag Helper?

**Comment by guardrex** [comment]
In reverse order ...

Yes, I agree on that ... in the [TH section of the TOC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-3.1) as a *built-in* TH. I can cross-link from here to there and place the additional content there on whatever this turns out to be.

WRT the error, open an issue with engineering ...

* https://github.com/dotnet/aspnetcore/issues
* Add a `cc: @guardrex` to the bottom of your issue so that I can track along.
* Leave this open. I'll work it when we get an answer over there, and I'll use this to track our visibility of the TH. Thanks for the suggestion @mrlife! 🎷

**Comment by mrlife** [comment]
Great thanks, here is the direct link to the issue: https://github.com/dotnet/aspnetcore/issues/19466

**Comment by guardrex** [comment]
Note to self: Seeking to put the `Blazor` label on the upcoming Blazor Component TH topic issues because that PR is going in anyway for something else. Confirm that it was merged or do it when this is worked.

```
"(?i).*master\/aspnetcore\/mvc\/views\/tag-helpers\/built-in\/component.md": {
  "labels-add": "Blazor"
},
```

**Comment by guardrex** [comment]
*Now, we know!* 💡 ... I'll update and work on a Component TH topic asap. It will be perhaps 1-2 weeks due to high priority Blazor issues.
