### ISSUE TITLE
Problem with scaffolding

### ISSUE THREAD

**Issue by Decompressor-art** [dotnet/AspNetCore.Docs#17163]
When I try scaffold, I get error:
There was an error running the selected code generator: 'There was an error creating a DbContext, the file C:\Users\Asus\source\repos\ContosoUniversity\Data\SchoolContext.cs  already exists'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a great error message to help you figure out what you did wrong.

**Comment by luizhp** [comment]
> When I try scaffold, I get error:
> There was an error running the selected code generator: 'There was an error creating a DbContext, the file C:\Users\Asus\source\repos\ContosoUniversity\Data\SchoolContext.cs already exists'
> 
> #### Document Details
>  _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
> * Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
> * Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#feedback)
> * Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-data**
> * GitHub Login: @Rick-Anderson
> * Microsoft Alias: **riande**

had the same problem.

just replace this
--dataContext AppMvcBasica.Models.ApplicationDbContext

to this
--dataContext ApplicationDbContext

example:
dotnet aspnet-codegenerator controller --force -async -name FornecedoresController -m Fornecedor --dataContext ApplicationDbContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries
