### ISSUE TITLE
Further split Blazor Razor Components

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#17169]
Tracking issue for splitting long topics: https://github.com/dotnet/AspNetCore.Docs/issues/17167

I-dears ...

* Reduce the length of the *Use components* example.
* Split out *Cascading values and parameters* section into its own topic.

@mkArtakMSFT, did you spot additional splits or *document diet* 🍰 strategies? Is this list ok thus far?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex. I want to go over this with @danroth27 first. Please hold on from starting on this.

**Comment by mkArtakMSFT** [comment]
@guardrex what do you think? We are not yet sure, so let's discuss this first and not rush doing this yet. Just wondering about your opinion on this. Also, if you have other suggestions, please advice.

Some notes from the discussion with @danroth27:
- it's important to maintain the "got to next" ability after each sub-topic
- [Static-assets](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#static-assets) and tag helpers are tiny and not really a topic. It's just a note which should be moved from the first section
- [Routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#routing) is also a small subsection and shouldn't be in the top
- Here is a proposal for three high-level areas for the doc:
  - What is component?
  - Using components
  - Creating components
    - routing (the section above should be here as a small paragraph
- [Capture references to components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#capture-references-to-components) should be a separate topic
- [Import components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#import-components) should be a sub-section in the `using components`
- [Partial class support]() and [Specify base class]() also should be in the `Creating component` section
- [Specify an attribute]() should be replaced with `Apply an attribute`

**Comment by guardrex** [comment]
> three high-level areas for the doc

Feels like that's going to be challenging in practice. I think what we'll find is that it's difficult to cleanly maintain all of the content so rigidly as that or that it's a valuable effort in the end if we do try to radically re-organize all of the content (but perhaps that's not what you're suggesting).

You probably noticed this ... some of the sections are *scenario based*. They're more like 'here's a scenario' and 'here's how to **_create AND use_** components to achieve it.'

Insofar as "create and use" means "generally how to create and use a basic component" and create+use scenarios follow in subsequent sections, that's about how the topic is organized currently (admittedly a little messily so given new scenarios, gotchas, and other sources of doc churn).

This topic is mostly following two basic concepts, and there are trade-offs with other content layout strategies ...

1. General to specific - Cover general, common component concepts, then cover specific and probably less common/less used/less important concepts.
1. Start to finish - Cover in order anything pertaining to either stepwise execution by the reader or concepts that build on one another.

As we see today, it doesn't work out perfectly well. We can try to go with, for example, three high-level doc areas (2nd level sections) and try to group the rest of the content under those ... and what happens in a lot of cases is that all we did was move stuff around with little benefit. The reader still ends up consuming all of the same content and ultimately referencing individual sections as needed without much benefit for the effort.

A/B testing would help .... **_if it's properly performed_**. :trollface: :smile: lol

* Static-assets and tag helpers

Originally here (early) for *visibility* under my **General-to-specific** goal ... to make some orienting remarks right off the bat that generally apply to all components.

* Routing

Also fell under my **General-to-specific** rule for content: Routing is a general thing that applies to all components, so I get it out of the way early. I like your position for it as long as no routing-related concepts precede its first appearance. In the topic, it usually means that no example with an `@page` directive and a route should precede this content.

* Capture references to components as a topic

:+1:

* Import components as a sub-section of components

:+1: &ndash; I was just concerned about distracting from the most general and useful concepts. If they put their components in *Shared* or *Pages*, they might be able to get along for quite a while before a :boom::cry:.

* Partial class support and specify base class in *Creating component*

:+1: &ndash; Also concerned about distracting content, but we seem to be leaning toward re-orienting parts of the topic to group more on purely subject matter. Agree that grouping by subject matter is fine. If they don't like a piece, I'm sure they'll just skip it and move on to the next bit.

* "Specify"-to-"Apply" an attribute

:+1:

I'll stand by until you let me know when to pull the trigger. 📑🔫 ... This obviously will become a draft that we can look at to see how it composes.

I've started working on Javier's content, which I think is going to take all week. Should I plan to take a shot at this early next week? This shouldn't take more than a few hours. (*Put that on my tombstone please!* ⚰️)

... and what about these two possibilities ...

* Do you want to keep the **Cascading values and parameters** section in this topic?
* Do you want to move **Invoke component methods externally to update state** to the **State management** topic?

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your thoughts, @guardrex.
I need some more time on this, so please leave this aside for now, till I get back. It won't be forgotten, as I have this on my to-do list and will get back you.
