### ISSUE TITLE
Have a way to measure impact of doc changes

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17165]
This is critical, as without measuring we don't know whether the outcome of a change is positive or negative. This will also help us understand the types of changes people prefer more.

**Comment by Rick-Anderson** [comment]
We use CSAT as a rough proxy for the improvements. I'm currently rewriting #17152 which has terrible CSAT and I can guarantee my version will be much higher.

**Comment by mkArtakMSFT** [comment]
Thanks @Rick-Anderson.
Also, after reviewing the data it seems the participation rate in the CSAT survey is really low and it's hard to evaluate the results given such small data sets.
We're starting an effort with @danroth27 to improve that rating. Part of this effort will be explicit call in our release notes to participate in that survey. We will also have other types of call-for-participation efforts like tweets and others.

**Comment by Rick-Anderson** [comment]
> Thanks @Rick-Anderson. Also, after reviewing the data it seems the participation rate in the CSAT survey is really low and it's hard to evaluate the results given such small data sets. We're starting an effort with @danroth27 to improve that rating. Part of this effort will be explicit call in our release notes to participate in that survey. We will also have other types of call-for-participation efforts like tweets and others.

Any updates on this?

**Comment by Rick-Anderson** [comment]
I send out monthly traffic reports which have the CSAT change for each doc. That's all we can do.
