### ISSUE TITLE
Scope ToC to current topic

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17166]
At the moment, when a user navigates to some section in the ToC, all the other topics are still visible: 
![image](https://user-images.githubusercontent.com/34246760/75615468-e8a8fe80-5af8-11ea-9494-2b3d3da84aaa.png)

To simplify navigation, consider hiding all the other topics and showing only sibling and child-level subtopics in the ToC. To allow further navigation, extend the breadcrumb to include sub-topics. In the above example it shows "Docs / ASP.NET / ASP.NET Core".
Instead, it should show "Docs / ASP.NET / ASP.NET Core / Web Apps / Blazor"

This will clear up the overall UI and reduce the visual load.

**Comment by scottaddie** [comment]
The change which extends the breadcrumbs to include sub-topics is live now.

**Comment by guardrex** [comment]
Fixed by #17209.
