### ISSUE TITLE
Split too large doc articles into multiple sections

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17167]
This issue is going to be used to track all the relevant work below:

- [ ] [Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
- [x] [Razor Components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande** 

---

[Associated WorkItem - 64338](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64338)

**Comment by guardrex** [comment]
I opened **Further split Blazor Razor Components** (dotnet/AspNetCore.Docs #17169) to address that one. I have some additional ideas there for cutting it down further. We just need to be careful ... many of those concepts *build*, so splitting things out has to be performed *with surgical precision* 🔪👨‍⚕.

**Comment by hishamco** [comment]
How this need to be organized?

**Comment by Rick-Anderson** [comment]
> How this need to be organized?

@tdykstra  will take care of it.
