### ISSUE TITLE
Parent/Child Razor Component in Razor Page

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#17170]
The following quote implies that the child component functionality is supported in calls to a parent component from a razor page.

> While pages and views can use components, the converse isn't true. Components can't use view- and page-specific scenarios, such as partial views and sections. To use logic from partial view in a component, factor out the partial view logic into a component.

I'm referencing the parent/child razor component functionality from [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#parent-to-child-binding-with-component-parameters).

When I try this using a parent `<component>` tag in a razor page, the parent is rendered and the included call to the child `<component>` is visible in the DOM but is not processed (and is not displayed on the page in any way).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#render-components-from-a-page-or-view)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @mrlife ...

> the parent is rendered and the included call to the child <component>

Are you trying to nest these? ... show your code.

**Comment by mrlife** [comment]
@guardrex Here is what I'm trying to do; it's just like in the docs except using `<component>`.

Index.cshtml
```
Razor component contents:
<component type="typeof(ParentComponent)" render-mode="Server" />
```

ParentComponent.razor
```
In the parent component...
<component type="typeof(ChildComponent)" render-mode="Server" />
```

ChildComponent.razor
```
In the child component...
```

What visiting Index.cshtml should display

> Razor component contents:
In the parent component...
In the child component...

**Comment by guardrex** [comment]
That's not a supported scenario. To place the child in the parent, just use ...

```razor
<ChildComponent />
```

... in the parent component (*ParentComponent.razor*).

We have [content early in the *Components* topic that explains that Tag Helpers don't work in components](https://docs.microsoft.com/aspnet/core/blazor/components#tag-helpers-arent-supported-in-components); however, the text might need more work to make it very clear that the Component Tag Helper is for pages and views only and that it shouldn't be (a) used in components directly and (b) nested in CSHTML markup.

Leave this issue open. There will be slight delay of maybe a week or two ... high priority issues demand full attention right now. 🏃 I'll get to this asap.

**Comment by guardrex** [comment]
I had a few minutes here, and I didn't want to wait on this. I took a look, and I don't think the current text is confusing.

It states at the top of the [Render components from a page or view](https://docs.microsoft.com/aspnet/core/blazor/integrate-components#render-components-from-a-page-or-view) section in the integration topic ...

> This section pertains to adding components to pages or views ...

The passage ...

>While pages and views can use components, the converse isn't true. Components can't use view- and page-specific scenarios, such as partial views and sections. To use logic from partial view in a component, factor out the partial view logic into a component.

... only says that you can place a component in a page or view, but you can't use page and view scenarios inside of a component. It doesn't speak to nesting beyond that concept.

The [Parent-to-child binding with component parameters](https://docs.microsoft.com/aspnet/core/blazor/data-binding#parent-to-child-binding-with-component-parameters) section of the binding topic has examples that aren't using the Component Tag Helper ...

```razor
<ChildComponent @bind-Year="ParentYear" />
```

... and ...

```razor
<ChildComponent @bind-Year="ParentYear" @bind-Year:event="YearChanged" />
```

I think we're ok right now. I'll keep an :ear: open for additional feedback. Thanks for commenting on this.

**Comment by mrlife** [comment]
Ok, thanks for clarifying that `<RazorFileName />` is always the format for a child component, even when the parent is called with `<component>`. That was the part that wasn't clear to me.
