### ISSUE TITLE
Use SingleOrDefaultAsync() Method?

### ISSUE THREAD

**Issue by chattermc** [dotnet/AspNetCore.Docs#17171]
Nice tutorial, however I've spotted a minor issue: in the GetTodoItem(long id) action of the TodoItemsController (when updating this to use the DTO), the LINQ query is using the .SingleAsync method. This will throw an exception if a request asks for an id which does not exist and returns a server 500 code (the code checking for null after the query is never reached). I think the query should be using the SingleOrDefaultAsync method instead, then the null-checking code will work and return either the item or 404 code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@chattermc  good suggestion.

**Comment by serpent5** [comment]
Yep, good spot. I'll patch this up in a bit.
