### ISSUE TITLE
Invoke arrow function

### ISSUE THREAD

**Issue by zachneu** [dotnet/AspNetCore.Docs#17173]
Is there some way to call an arrow function from InvokeVoidAsync? something like this:
JSRuntime.InvokeVoidAsync(() =&gt; alert('testing'))();");

This could be use full to execute js code not defined in any js files. I think this could be specially use full when you create a class library with Razor components which need to invoke js code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zachneu ... The signatures require a function identifier. See the API :point_right: https://docs.microsoft.com/dotnet/api/microsoft.jsinterop.jsruntimeextensions.invokevoidasync

You can open product feedback on it with engineering/management on the engineering repo :point_right: https://github.com/dotnet/aspnetcore/issues
