### ISSUE TITLE
thanks Daniel - error trying to create new web assembly project

### ISSUE THREAD

**Issue by toddharvey** [dotnet/AspNetCore.Docs#17175]
in Visual Studio 2019 (Version 16.4.2) , nuget package manager console
enter command:
dotnet new blazorwasm
result: 
dotnet : No templates matched the input template name: blazorwasm. (either local or online, per long message)

Should I have entered the command somewhere else? I tried from cmd prompt and got same message ("couldn't find an installed template … searching online")

Perhaps there's a dependency I'm missing ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @toddharvey ... Reinstall the template with ...

```dotnetcli
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1
```

... per https://docs.microsoft.com/aspnet/core/blazor/get-started.

This has happened to me, too, but VS losing track of the template after upgrading VS doesn't seem to occur for me every update. Therefore, I haven't been able to pin down what to document. Blazor WebAssembly is **_Coming Soon!_** ⏳ After that, we won't have the separate template install step, and this sort of issue should be cleared up permanently.
