### ISSUE TITLE
No mention of IItemsFeature

### ISSUE THREAD

**Issue by mungojam** [dotnet/AspNetCore.Docs#17187]
I've seen that IItemsFeature is used by the AWS lambda .net core integration libraries but it isn't mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d7ad78-542f-236c-f5b4-0273558674b9
* Version Independent ID: f64165fc-ccf3-62cd-9ae4-313dfe7d1911
* Content: [Request Features in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/request-features.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/request-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you provide a link?

**Comment by mungojam** [comment]
I raised it on the page so the link is in the auto-generated bit at the bottom. Or do you mean the AWS use of it?

**Comment by Rick-Anderson** [comment]
AWS

**Comment by mungojam** [comment]
they use it [here](https://github.com/aws/aws-lambda-dotnet/blob/85dd6e164c324120535815e02c30e3ae2e5d72f3/Libraries/src/Amazon.Lambda.AspNetCoreServer/AbstractAspNetCoreFunction.cs#L360-L366) as a way to pass the lambda context through to the controllers:

```c#
var itemFeatures = (IItemsFeature)features;
itemFeatures.Items = new ItemsDictionary();
itemFeatures.Items[LAMBDA_CONTEXT] = lambdaContext;
itemFeatures.Items[LAMBDA_REQUEST_OBJECT] = request;
PostMarshallItemsFeatureFeature(itemFeatures, request, lambdaContext);
```

**Comment by Rick-Anderson** [comment]
Can you provide a link to `LAMBDA_REQUEST_OBJECT`

**Comment by davidfowl** [comment]
It's a pretty advanced topic honestly. These wouldn't usually come up unless you were building a custom server or doing something just as advanced.

**Comment by mungojam** [comment]
I went looking for documentation on it as I thought I might want to use it to inject some additional context information into the controllers. I did end up doing just that but maybe there was a more natural way or something.

**Comment by davidfowl** [comment]
Amazon implements a custom `IServer` (like Kestrel or IIS) and this is how they are setting state in HttpContext.Items (that's backed by the IItemsFeature).
