### ISSUE TITLE
Log location in linux

### ISSUE THREAD

**Issue by ndc** [dotnet/AspNetCore.Docs#17184]
> On Linux, this provider writes logs to /var/log/message.

On Ubuntu 18.04.4 LTS there is no `/var/log/message`. The log is recorded in `/var/log/syslog`.

Hopefully this info saves someone time from troubleshooting why the application doesn't write to log.

If you call `ILogger.LogError(myException, "some message")` for example, it will appear in `/var/log/syslog` as multiple lines that start like `Mar  3 07:26:22 myServerName myAppName[aNumber]: ...`. So you can grep only the relevant lines: `sudo grep myAppName /var/log/syslog`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We document access with `journalctl` here :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx#view-logs (but don't say where the logs are stored). I suppose that was engineering's recommended approach and location was considered to be less important for that bit of content.

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Logging in .NET Core and ASP.NET Core #16174 and looks like a dup of #16095

I'll be addressing these next week.
