### ISSUE TITLE
Examples link to docs

### ISSUE THREAD

**Issue by jburkett** [dotnet/AspNetCore.Docs#17188]
All the links labeled "example" seem to link to the (skeletal) class documentation for the associated topic, rather than actual examples. This doesn't provide anything similar to an actual example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
- Replace Example with API
