### ISSUE TITLE
Add using statements to examples in Blazor DI topic

### ISSUE THREAD

**Issue by adam000** [dotnet/AspNetCore.Docs#17189]
The following sample doesn't work with the previews available to me:

```
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.Services.AddSingleton&lt;IMyDependency, MyDependency&gt;();
        builder.RootComponents.Add&lt;App&gt;("app");

        await builder.Build().RunAsync();
    }
}
```

In 3.1.0-preview4... the type `WebAssemblyHostBuilder` doesn't exist and VS tries to suggest `IWebAssemblyHostBuilder`. In 3.2.0-preview1... the type does exist, but `builder.Services` has no method `AddSingleton`.

I need a simple DI example but I can't find anything that works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by adam000** [comment]
It looks like there was a missing dependency on `Microsoft.Extensions.DependencyInjection`. Wish the code samples showed using statements too, it would be useful and insightful.

**Comment by guardrex** [comment]
@adam000, Yes, adding the `using` statements is an **_on-going effort_**. I'll use this issue to address that for this topic. We add them regularly as we go through the topics, and I'll keep adding them as I go.

Leave this open and it will close when the PR merges. Thanks for writing in on it.
