### ISSUE TITLE
Auto-rebuild for Blazor WASM apps will now work in VS (16.6-preview1)

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17195]
@guardrex some docs where we 've mentioned that this is not a thing should be updated to now talk about this. This is about automatically rebuilding project when changes in transitive dependencies are made. 
/cc @danroth27 am I missing something else as part of it?

**Comment by guardrex** [comment]
> some docs where we 've mentioned that this is not a thing

@mkArtakMSFT I don't recall that in this doc set. I searched, too. Did you have a reference in mind that I missed?

**Comment by danroth27** [comment]
Auto rebuild will now work for Blazor WebAssembly and Razor Class Libraries with Visual Studio 2019 16.6, but it looks like we don't have any docs to update as a result. Closing.
