### ISSUE TITLE
Update static assets docs if necessary

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17191]
@javiercn we've made some changes during 3.2-preview2 and I'm not sure whether docs have been updated or not. If yes, feel free to close this. Otherwise, please use this issue to address all the necessary changes related to Static Assets.

**Comment by guardrex** [comment]
I'm going to continue to add these to the Blazor.Docs project for my visibility, even when I'm not initially assigned. It's easier, too, for you to assign to me with provided content this way when I should take an issue over at some point.

**Comment by mkArtakMSFT** [comment]
@javiercn also, please cover the `precompression` docs too as part of this.

**Comment by guardrex** [comment]
Here's the blog post content for reference ...

> Blazor WebAssembly apps now integrate seamlessly with how ASP.NET Core handles static web assets. Blazor WebAssembly apps can use the standard ASP.NET Core convention for consuming static web assets from referenced projects and packages: \*_content/{LIBRARY NAME}/{path}\*. This allows you to easily pick up static assets from referenced component libraries and JavaScript interop libraries just like you can in a Blazor Server app or any other ASP.NET Core web app.
>
> Blazor WebAssembly apps are also now hosted in ASP.NET Core web apps using the same static web assets infrastructure. After all, a Blazor WebAssembly app is just a bunch of static files! 
>
> This integration simplifies the startup code for ASP.NET Core hosted Blazor WebAssembly apps and removes the need to have an assembly reference from the server project to the client project. Only the project reference is needed, so setting \`ReferenceOutputAssembly\` to \`false\` for the client project reference is now supported. 
>
> Building on the static web assets support in ASP.NET Core also enables new scenarios like hosting ASP.NET Core hosted Blazor WebAssembly apps in Docker containers. In Visual Studio you can add docker support to your Blazor WebAssembly app by right-clicking on the Server project and selecting Add > Docker support.

**Comment by guardrex** [comment]
Here's the blog post content for reference ...

> Blazor WebAssembly apps now integrate seamlessly with how ASP.NET Core handles static web assets. Blazor WebAssembly apps can use the standard ASP.NET Core convention for consuming static web assets from referenced projects and packages: \*_content/{LIBRARY NAME}/{path}\*. This allows you to easily pick up static assets from referenced component libraries and JavaScript interop libraries just like you can in a Blazor Server app or any other ASP.NET Core web app.
>
> Blazor WebAssembly apps are also now hosted in ASP.NET Core web apps using the same static web assets infrastructure. After all, a Blazor WebAssembly app is just a bunch of static files! 
>
> This integration simplifies the startup code for ASP.NET Core hosted Blazor WebAssembly apps and removes the need to have an assembly reference from the server project to the client project. Only the project reference is needed, so setting \`ReferenceOutputAssembly\` to \`false\` for the client project reference is now supported. 
>
> Building on the static web assets support in ASP.NET Core also enables new scenarios like hosting ASP.NET Core hosted Blazor WebAssembly apps in Docker containers. In Visual Studio you can add docker support to your Blazor WebAssembly app by right-clicking on the Server project and selecting \*\*Add\*\* > \*\*Docker support\*\*.

**Comment by guardrex** [comment]
@mkArtakMSFT I'll use the blog post content to cover this subject.
