### ISSUE TITLE
Docs for browser caching for Blazor WASM

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17194]
@SteveSandersonMS do we need to add docs regarding the caching feature you've created? If so, please use this issue to provide content for it and then reassign to @guardrex to inject that into the docs. Otherwise, please close this issue.

**Comment by guardrex** [comment]
Blog post content for reference ...

> If you look at the network trace of what's being download for a Blazor WebAssembly app after it's initially loaded, you might think that Blazor WebAssembly has been put on some sort of extreme diet:
>
> !\[Blazor network](https://devblogs.microsoft.com/aspnet/wp-content/uploads/sites/16/2020/03/blazor-network.png)
> 
> Whoa! Only 159kB? What's going on here?
>
> When a Blazor WebAssembly app is initially loaded, the runtime and framework files are now stored in the browser cache storage:
>
> !\[Blazor cache](https://devblogs.microsoft.com/aspnet/wp-content/uploads/sites/16/2020/03/Blazor-cache.png)
>
> When the app loads, it first uses the contents of the \`blazor.boot.json\` to check if it already has all of the runtime and framework files it needs in the cache. If it does, then no additional network requests are necessary.
>
> You can still see what the true size of the app is during development by checking the browser console:
>
> !\[Blazor loaded resources](https://devblogs.microsoft.com/aspnet/wp-content/uploads/sites/16/2020/03/blazor-loaded-resources.png)

**Comment by guardrex** [comment]
@mkArtakMSFT I'll use the blog post content to cover this subject.

**Comment by guardrex** [comment]
@mkArtakMSFT Looking at this closer, it seems like it falls into the *framework implementation detail* bucket ... a level of detail that we wouldn't normally cover. Do you want to close it? If not, what aspect would you like to cover?
