### ISSUE TITLE
Updated Blazor WASM debugging docs

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17192]
@SteveSandersonMS can you please list out the changes here, so that @guardrex can update the docs as necessary. When done, please assign this issue to him to take over.

To start, here is what I know:
- [ ] F5 debugging is now supported in VS
- [ ] Debugging in VSCode is now supported.

EDIT by guardrex ... Plz comment on this remark by @tedypranolo ...

> I am using 3.2 preview. I followed the instructions here and added breakpoint in the browser debugger. Because I want to break within `OnInitializedAsync` I figured the obvious way is to reload the page. But that didn't work. The breakpoint would only work if I navigate to the razor.page , for example using the navigation menu in my blazor app. I think this fact should be mentioned in the doc.

Original issue: https://github.com/dotnet/AspNetCore.Docs/issues/17336

**Comment by guardrex** [comment]
WRT "now supported" ... `preview2`, correct?
