### ISSUE TITLE
Docs for Blazor WASM PWA support

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17198]
@SteveSandersonMS can you please provide content for PWA support we just added for Blazor WASM? Thanks!

**Comment by SteveSandersonMS** [comment]
OK, content is here: https://gist.github.com/SteveSandersonMS/6482fe31bc744fdd19bf5360d0ce88c0

Note that this also includes the "caveats" section we need to link to from the project template.

Unassigning myself now. @guardrex, can you take over from here? Let me know if you need anything more from me!
