### ISSUE TITLE
Update to .NET Core 3.1

### ISSUE THREAD

**Issue by ARambazamba** [dotnet/AspNetCore.Docs#17203]
Please update this sample to .NET Core 3.1 and maybe build the image from GitHub. Using a ready made image really does not help at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ARambazamba  this doc is focused only on `how to run pre-built container images with HTTPS.`

What about the  version makes it difficult to follow in 3.1?

**Comment by ARambazamba** [comment]
Sorry ... did not read the pre-build part!
