### ISSUE TITLE
A problem changing from app.UseEndpoint to app.UseMvc

### ISSUE THREAD

**Issue by jl-rey** [dotnet/AspNetCore.Docs#17206]
### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Rick-Anderson** [comment]
@jl-rey  you should start over and follow the [current tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio)

**Comment by jl-rey** [comment]
Actually the new tutorial is the same. The problem seems to be that the `app.UseMvc` is the older method and should not be needed in the new tutorial but is still there.

At least not following the link provided.

**Comment by Rick-Anderson** [comment]
That's not correct. Select the default 3.1 version.
