### ISSUE TITLE
ASP.NET Core CancellationToken

### ISSUE THREAD

**Issue by jstclair** [dotnet/AspNetCore.Docs#17205]
After reading [this article on action binding for CancellationTokens](https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/) I looked through all the existing ASP.NET Core topics for any details on the same topic, but didn't find any. 

Why: after reading the article above, ASP.NET Core's behavior is quite understandable but non-documented. In our scenario, we have some underlying resources used by the API which could not open a connection before the client timed out.  Our HttpClient with a short timeout (~5 seconds) and Polly for automatic retries had non-intuitive behavior when the API is under load, since IIS/Kestrel were keeping the async operations in-flight.  I would suggest that this be officially documented.

Location: ASP.NET Core (3.1) / Advanced

Abstract/Outline: a shortened version of the above article, with perhaps links or details on the CancellationToken parameter binding. The article also uses an older version of exception filtering that could be updated to 3.1's `IExceptionFilter`

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by jstclair** [comment]
Hi, 

So did you want me to create and issue from the docs page? Unclear since you closed and then re-opened

**Comment by Rick-Anderson** [comment]
That would be great if you can create it from the doc page.
