### ISSUE TITLE
dotnet user-secrets init

### ISSUE THREAD

**Issue by oyvindvik** [dotnet/AspNetCore.Docs#17214]
I had to run this init statement first:
dotnet user-secrets init

before adding the secrets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The VS templates create initialize the secret. Did you create the project with `dotnet new` ?

To fix:

* Repo the problem. 
* Create an include - something like

If the `dotnet user-secrets set ` command has the following error
error
run `dotnet user-secrets init`

**Comment by scottaddie** [comment]
Heads up that the `dotnet user-secrets init` command was added in .NET Core 3.0. It adds the `UserSecretsId` element to the project file, which is necessary to associate secrets with this project.

**Comment by scottaddie** [comment]
I'll take care of this one.

**Comment by Rick-Anderson** [comment]
@scottaddie  this is low priority as it only impact `dotnet new`. It's always been the case that `dotnet new` project didn't have the `UserSecretsId ` - but before you needed to add that yourself.

With 5K PV, this is low pri. Why don't you assign it to @wadepickett

**Comment by scottaddie** [comment]
@Rick-Anderson It's a bigger problem than what's indicated in this issue. A consistent set of instructions needs to be provided across the social authN docs.
