### ISSUE TITLE
Mention [ApiController] with ValidateModelAttribute

### ISSUE THREAD

**Issue by ardalis** [dotnet/AspNetCore.Docs#17216]
[ApiController] makes [ValidateModel] obsolete for APIs that use it. Would be worth mentioning here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#action-filters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ardalis  thanks for the heads up. I hope to get this documented soon.

**Comment by Rick-Anderson** [comment]
I'll let @serpent5  have dibs on this.
