### ISSUE TITLE
Passing tokens to a server-side Blazor app

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#17221]
Opening a new issue for this as per @danroth27 request.

This is how you pass and use access tokens and refresh tokens to a server-side Blazor API
https://github.com/javiercn/blazor-server-aad-sample

There's several people asking for this on a regular basis, (AAD or any other provider) so this sample and associated redme covers it.

I'll leave it up to @danroth27 and the docs team from here.

**Comment by guardrex** [comment]
This is up next immediately after 3.2p3 releases. My plan is to create a TOC node for *Blazor Server* in the *Blazor Security* TOC node (akin to our *Blazor WebAssembly* node there). The new node will have an *Overview* topic to receive our current Blazor Server guidance. The content on this issue will be a new topic in that node. If there's any objection to this plan, I'm :ear::ear::ear:.
