### ISSUE TITLE
Could you add some information about type conversion

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/AspNetCore.Docs#17228]
I believe type converters were added in preview 7 and it would be useful to have an example. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LaughingJohn ... This is a dup of https://github.com/dotnet/AspNetCore.Docs/issues/16370.

**Comment by LaughingJohn** [comment]
Aha, thanks, sorry didn't spot that!
