### ISSUE TITLE
Scaffolding TodoItem Controller

### ISSUE THREAD

**Issue by htwigg** [dotnet/AspNetCore.Docs#17224]
I'm on Linux Mint.
'When I run the command

 `dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
`
I get this error: 

> Could not execute because the specified command or file was not found.
> Possible reasons for this include:
>   * You misspelled a built-in dotnet command.
>   * You intended to execute a .NET Core program, but dotnet-aspnet-codegenerator does not exist.
>   * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Thing is, I installed dotnet-aspnet-codegenerator. I added 
`export PATH="$PATH:$HOME/.dotnet/tools/"` to my bashrc . Now I don't knnow what to do

**Comment by Rick-Anderson** [comment]
That error is pretty helpful. what happens when you run `dotnet --version` ?
My guess is the path is incorrect.

**Comment by htwigg** [comment]
it outputs 3.1.101

**Comment by Rick-Anderson** [comment]
confirm you installed the code generator
