### ISSUE TITLE
Misspelled method name

### ISSUE THREAD

**Issue by f-engstrom** [dotnet/AspNetCore.Docs#17227]
Receive is misspelled in the chathub sendmessage method which leads to no message being displayed when sent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by scottaddie** [comment]
@f-engstrom I don't see any spelling mistakes. Can you please include the exact line of code where you see the problem?

**Comment by f-engstrom** [comment]
Hi! I’m really sorry to have bothered you, I checked again and it turns out I’m the one that introduced the misspell, I thought I had used the copy function on the site for both the chathub, where I believed to have found the error, and the JavaScript. After you sent me this I realised that I had written the code for the chathub myself just looking at the page and at that point introduced the error myself. Sorry for so much ado about nothing, I’ll check more thoroughly next time!   Från: Scott AddieSkickat: den 6 mars 2020 17:02Till: dotnet/AspNetCore.DocsKopia: f-engstrom; MentionÄmne: Re: [dotnet/AspNetCore.Docs] Misspelled method name (#17227) @f-engstrom I don't see any spelling mistakes. Can you please include the exact line of code where you see the problem?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by scottaddie** [comment]
No problem. Thank you for confirming.
