### ISSUE TITLE
Query String Changed Event Notification

### ISSUE THREAD

**Issue by CoryGM** [dotnet/AspNetCore.Docs#17220]
The previous items don't address this question specifically.

The LocationChanged event only covers about half of our scenarios. We have a number of search pages where the users are allowed to enter a number of different criteria. That criteria is passed through as parameters to the page service, rendering a different set of results for each change.

In the most common scenario this feature is handled by updating the query object and passing that through to the service. However, this approach has two significant drawbacks:

1 - Built-in browser forward / back functionality doesn't work because even though there was a change in application state, there technically wasn't a change in location. You can partially manage this by tracking application state in the Blazor app but it breaks if the user leaves the Blazor site for a different site and then navigates back to the Blazor site using the browser's back button. In this case the criteria used to generate the page state are lost.

2 - It's very common in our systems for users to either book mark search pages with a specific set of criteria. Users will also frequently create queries on a page and then copy the URL for the search and send it to a colleague. This is used when users from one area of the company want to reference a certain set of data for use by a set of users in another area of the company. 

In the second scenario we can change change/set the URL based on the user's actions and programmatically trigger a retrieval of the data set. This works UNTIL the user tries to navigate back through a series of searches using the browsers forward and back buttons. The URL in the browser will change with the query string changes and same locatio but the search results will not because there isn't an event tied to query parameter changes that can be triggered. 

The ideal solution would be the addition of a QueryStringChanged() event on the navigation manager similar to the LocationChanged event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @CoryGM ... This seems more along the lines of product feedback, especially the remark ...

> the addition of a QueryStringChanged() event on the navigation manager similar to the LocationChanged event.

That type of suggestion has to go to the product unit (engineers) on their repo. It's not a documentation issue. Although this will be seen here *eventually* by engineering, you might want to close here and open this on their repo :point_right: https://github.com/dotnet/aspnetcore/issues.

**Comment by CoryGM** [comment]
Good point. I'll close this out.
