### ISSUE TITLE
New 'AddKeyVault' overload simplifies client code

### ISSUE THREAD

**Issue by fsimonazzi** [dotnet/AspNetCore.Docs#17234]
The overload that takes only the key vault URI takes care of setting up the token provider for managed identities https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azurekeyvaultconfigurationextensions.addazurekeyvault?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Configuration_AzureKeyVaultConfigurationExtensions_AddAzureKeyVault_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_String_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fsimonazzi  thanks for the tip.

**Comment by daveabrock** [comment]
@Rick-Anderson I'm back! Want me to take a stab?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I'm back! Want me to take a stab?

@daveabrock  yes

**Comment by twentytwokhz** [comment]
Great addition! Should be included here - in this doc - as well
