### ISSUE TITLE
Blazor tutorial: Unclear instructions for making the todo list

### ISSUE THREAD

**Issue by JMackey1** [dotnet/AspNetCore.Docs#17235]
Hello,

I ran into some issues while doing this tutorial. Note, I am fairly new to C# and my first experience with Razor/Blazor is through the Blazor section of the ASP.NET Core documentation. It's possible that if I had gone through all of the documentation (particularly Razor Pages and MVC) first that I wouldn't have had any issues.

1) Step 1 of the "build a todo list" section threw me off. I expected to be able to right click on the pages folder -&gt; add -&gt; razor page, but trying to do so gives me an error:

There are no scaffolders supported for this item.

Instead, I had to do add -&gt; new item -&gt; Razor component and was able to proceed as normal.

2) In step 6 we are to add some code to the Todo.razor file. The problem here is the type "TodoItem" is not recognized. There is no mention of how to include a class in a razor file. I guessed that it had to be included somehow, so I tried:

@using ToDoList.wwwroot;

Which seems to have worked. This step just excludes the fact that you need to include a using directive here to get things working.

Perhaps include these instructions for each step, or note at the start of the Blazor section that you should be familiar with Razor Pages before learning Blazor (assuming that this knowledge is in the Razor Pages documentation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JMackey1 ... Thanks for your feedback. I will take a look, but I'm 🏃🏃🏃🏃🏃😅 on many high priority Blazor issues for the next week (or *two* 😅) ... I'll get to this as soon as I can.

**Comment by ysq5202121** [comment]
看不懂哈
