### ISSUE TITLE
There is no example how to add authorization to all razor pages

### ISSUE THREAD

**Issue by joaoGoncalves81** [dotnet/AspNetCore.Docs#17231]
How to set authorization to all razor pages in aspnet core application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1

**Comment by jeremycook** [comment]
I visited https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1 and found no example of applying authorization to all razor pages.

**Comment by joaoGoncalves81** [comment]
supposing that Rick refer to the "Require authenticated users" section (https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1#require-authenticated-users)
but I use this instead:
`services.AddRazorPages().AddMvcOptions(options =>
                {
                    var policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();
                    options.Filters.Add(new AuthorizeFilter(policy));
                });`

**Comment by jeremycook** [comment]
I withdraw my statement. Thanks @joaoGoncalves81
