### ISSUE TITLE
picture and described test is different. 3.0 vs 3.1

### ISSUE THREAD

**Issue by ibalasenthil** [dotnet/AspNetCore.Docs#17232]
picture and version described text is different.
works fine in 3.1.
UseInMemoryDatabase not getting added in solution because of version conflict. entityframework.UseInMemoryDatabase installed from NuGet package than its working fine.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The image needs to be updated, but the instructions are correct.
