### ISSUE TITLE
How to add Microsoft.NET.Sdk.Web reference?

### ISSUE THREAD

**Issue by JGregoryAtiba** [dotnet/AspNetCore.Docs#17243]
The page offers a path to get around the locked deployment files by using Web Deploy and adding a Microsoft.NET.Sdk.Web reference to the project file.  However, there's no indication of how to got about adding that reference... Microsoft.NET.Sdk.Web doesn't appear to be a Nuget package, and it doesn't appear anywhere in the "Add Reference..." dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#deploy-the-app)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#webconfig-file

Put `<Project Sdk="Microsoft.NET.Sdk.Web">` at the top of your csproj

**Comment by JGregoryAtiba** [comment]
I've already got that at the top of my project file and I'm using Web Deploy, but still ran into the locked deployment files problem.  But no biggie, I just manually stopped and started the app pool.  Thanks for the super-fast response!
