### ISSUE TITLE
Roles don't work unless NormalizedName is populated

### ISSUE THREAD

**Issue by mako-ng** [dotnet/AspNetCore.Docs#17240]
After going through the process to migrate my existing Membership tables, roles would not work until I manually set the NormalizedName values on all my roles.  

I suggest you update the documentation to set the NormalizedName when populating the AspNetRoles table

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
