### ISSUE TITLE
AddMvc() and UseMvc() in 3.1 at ConfigureServices and Configure methods

### ISSUE THREAD

**Issue by dush-a** [dotnet/AspNetCore.Docs#17249]
Even after selecting or refreshing the page it still shows: 
services.AddMvc()
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_2); 

and 
app.UseMvc();

Do we still need it in ASP.NET Core 3.1?

Another doc it says use AddControllers() or AddControllersWithViews() or AddRazorPages()
reference: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows#feedback)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This topic hasn't been updated to 3.1 yet. The work for that is being tracked in https://github.com/dotnet/AspNetCore.Docs/issues/13877.

**Comment by Rick-Anderson** [comment]
Dup of  #13877.
