### ISSUE TITLE
How to Localize validation message (DataAnnotationsValidator) in Blazor server side:

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17257]
See [this SO](https://stackoverflow.com/questions/59659489/how-to-localize-validation-message-dataannotationsvalidator-in-blazor-server-s) question.

The SO answer is correct. However, this is not really Blazor Server specific, rather just MVC.

This doc needs to point to [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1) where appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The Blazor doc cross-links the regular coverage at the top and in the *Additional resources* section. 

As for content, approaches, and examples, I don't have any further information from engineering at this point for this topic specific to Blazor.

There are a handful of globalization/localization issues for the product unit, so we might be getting some new toys eventually.

I also have an issue wrt `IStringLocalizer` support to address. I'll get to it as soon as I can. 🏃😅
