### ISSUE TITLE
Something about this article need adjusts

### ISSUE THREAD

**Issue by CaboFernando** [dotnet/AspNetCore.Docs#17256]
I'm read this page:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio

 This article was very useful, but it was missing to talk about two things that can get around by searching the web. I will quote them: 

1 - When creating the project from scratch, visual studio adds a controller to run from the beginning, which can be changed by going to louchSettings.json and changing where "weatherforecast" is written to "api"  

2 - The article tells us to create an API with .Net Core 3.0 but at the end of everything, it asks to install the Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.1.2, however this version does not support the .Net Core 3.0, only for .Net Core 3.1+. The version that supports .Net Core 3.0 is Version 3.0.3.  These were the only points for improvement, otherwise the article was very useful.

**Comment by Rick-Anderson** [comment]
Moved to #16196

Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by CaboFernando** [comment]
Thanks Dude

**Comment by serpent5** [comment]
Fixed in #24126.
