### ISSUE TITLE
Styling the message

### ISSUE THREAD

**Issue by jtheisen** [dotnet/AspNetCore.Docs#17252]
There's no information on how to style the mail, and the "htmlMessage" parameter already contains the text including the link. The `IEmailSender` interface also says it's not intended to be directly used by user code.

So how to I customize the mail to use a proper mail template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's beyond the scope of this tutorial.

**Comment by jtheisen** [comment]
Is it also out of the scope of ASP.NET Core Identity?

Because if it is, it renders all the rest of the tutorial absolutely useless.
