### ISSUE TITLE
Can I change ApplicationUser PK when used with IdentityServer4?

### ISSUE THREAD

**Issue by seanronan** [dotnet/AspNetCore.Docs#17267]
Without IdentityServer4 my DbContext would inherit/implement IdentityDbContext - which supports changing the ApplicationUser PK to an int.
With IdentityServer4 above my DbContext now inherit/implements ApiAuthorizationDbContext which appears to only accept a single param and gives the error
The type 'MyApp.Web.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'ApiAuthorizationDbContext&lt;TUser&gt;'. There is no implicit reference conversion from 'MyApp.Web.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'.

Am I missing a trick here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
I would ask the IdentityServer4 folks.

**Comment by seanronan** [comment]
It was an issue with the lightweight ApiAuthorizationDbContext written for this sample which didn't support all the IdentityDbContext constructors. 
https://stackoverflow.com/questions/58208894/aspnet-core-identity-custom-apiauthorizationdbcontext gives the work around, nothing to do with IdentityServer4

**Comment by Rick-Anderson** [comment]
@seanronan  thanks for the follow up.
