### ISSUE TITLE
CS0103 C# The name does not exist in the current context

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17265]
Hi team, 
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/75

@OleksandrFomenko commented 35 minutes ago — with docs.microsoft.com
updated Program.cs file has mistake CS0103 C# The name "Host" does not exist in the current context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by ttdivava** [comment]
The same thing happened to me as well

**Comment by ThomGreer** [comment]
The same thing happened to me as well, can someone help?
