### ISSUE TITLE
Provide guidance about asp.net core apps that run signalR

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/AspNetCore.Docs#17263]
I believe this section should be here
https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-3.1#linux-with-nginx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We have a topic for Linux with Nginx :point_right: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

I think we need to re-organize a bit. We have a PR with updates for WebSockets at https://github.com/dotnet/AspNetCore.Docs/pull/17181. The content can be moved to the Linux with Nginx topic and then cross-linked from both locations (WebSockets and Blazor's SignalR topic).

I'll take care of this when I get caught up a bit. 🏃😅 Thanks for calling it out @xrkolovos! :rocket:
