### ISSUE TITLE
Something about this article need adjusts

### ISSUE THREAD

**Issue by CaboFernando** [dotnet/AspNetCore.Docs#17271]
This article was very useful, but it was missing to talk about two things that can get around by searching the web. I will quote them:

1 - When creating the project from scratch, visual studio adds a controller to run from the beginning, which can be changed by going to louchSettings.json and changing where "weatherforecast" is written to "api"

2 - The article tells us to create an API with .Net Core 3.0 but at the end of everything, it asks to install the Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.1.2, however this version does not support the .Net Core 3.0, only for .Net Core 3.1+. The version that supports .Net Core 3.0 is Version 3.0.3. These were the only points for improvement, otherwise the article was very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
moved to Master list: Create a web API and MongoDB #16196

**Comment by serpent5** [comment]
Fixed in #24126.
