### ISSUE TITLE
Working with Visual Studio Code Section

### ISSUE THREAD

**Issue by anuraj** [dotnet/AspNetCore.Docs#17284]
## Add a database context

1) Need to install the Microsoft.EntityFrameworkCore package

## Register the database context

1) Need to install the Microsoft.EntityFrameworkCore.InMemory package

## Scaffold a controller

1) When I ran the Scaffold a controller command. I received an error message like this.

"To scaffold controllers and views using models please install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design, Microsoft.EntityFrameworkCore.SqlServer"
![image](https://user-images.githubusercontent.com/276411/76477179-83270d00-642a-11ea-8829-1098213d7561.png)

And if I am installing the SqlServer package only I am able to scaffold a controller. Since I am using InMemory provider why I need to use SqlServer provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#add-a-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
All those steps are in the tutorial.
