### ISSUE TITLE
Hosting Kestrel behind a reverse proxy requires Forwarded Headers Middleware configuration, not host filtering

### ISSUE THREAD

**Issue by mmarinchenko** [dotnet/AspNetCore.Docs#17286]
Hosting Kestrel behind a reverse proxy requires Forwarded Headers Middleware configuration, not host filtering

Warning messages which state about host filtering requirement in reverse proxy scenario are wrong.

Correct info provided:
- in final note about AllowedHosts option (on this page)
- in "Configure a reverse proxy server" section of dedicated pages such as "Linux with Nginx" and "Linux with Apache"
- on "Configure ASP.NET Core to work with proxy servers and load balancers" page (this is actually the right place to point to - https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mmarinchenko** [comment]
Mentioned warnings are present in the following sections:
- When to use Kestrel with a reverse proxy
- Transport configuration

**Comment by guardrex** [comment]
Cross-ref to the original PR for the content ...

https://github.com/dotnet/AspNetCore.Docs/pull/5674

... the issues are private/internal. A few PRs that touched this text were :eyes: by engineering and approved since then.

**Comment by Rick-Anderson** [comment]
@jkotalik please review

**Comment by Tratcher** [comment]
The proxy-load-balancer link is the one that already covers this scenario. That's not a kestrel specific behavior, but adding a cross link wouldn't hurt.

**Comment by mmarinchenko** [comment]
@Tratcher 

I'm sorry if I misread you... This particular issue is not about proxy-load-balancer link itself but about warning balloons which mention host filtering instead of forwarded headers middleware. Proxy-load-balancer page contains right info so it would be great to also add the link to it.

**Comment by Tratcher** [comment]
Ah, I was confused which doc you were trying to correct.

@Rick-Anderson yes, the warning in https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md#when-to-use-kestrel-with-a-reverse-proxy should refer to Forward Headers and link to the proxy doc, not to host filtering. Host filtering is already covered several other places.
