### ISSUE TITLE
Missing GetTodoItem method in POST section?

### ISSUE THREAD

**Issue by andrew-lewell** [dotnet/AspNetCore.Docs#17287]
I think the scaffolding may have changed as I am unable to build with the code for the POST method. It cannot find the GetTodoItem method which I assume is because this does not exist yet in the GET method. I am going to work forwards through the rest of the code and see if it fixes it. 

My scaffolded code: 
// GET: TodoItems
        public async Task&lt;IActionResult&gt; Index()
        {
            return View(await _context.TodoItems.ToListAsync());
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by andrew-lewell** [comment]
I've been looking into this and it seems that the scaffolded controller inherits from Controller but in your code it inherits from Controller:Base. The scaffolded controller I have also scaffolds views which I believe I should not have.

**Comment by andrew-lewell** [comment]
I managed to get my POST working by removing all the views and commenting out other methods for now. After doing some digging - It looks like the scaffolded controller in .NET Core has to use the MVC approach with views. I believe your tutorial must use the scaffolding from .NET or perhaps an old scaffolding.

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
