### ISSUE TITLE
We're missing guidance about using Dispose to unhook from .NET events in Blazor

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#17293]
@DamianEdwards and I can't find anywhere that the docs tell you to unsubscribe from .NET events (like those from `NavigationManager` and `EditForm`).

It's not enough for us to add this to the dispose/lifecycle method, we probably need to call it out anywhere else we document using a .NET event.

[This example](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#enable-the-submit-button-based-on-form-validation) is really problematic because it doesn't show unhooking the event.

[Dispose](https://docs.microsoft.com/en-us/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#component-disposal-with-idisposable)

[NavigationManager](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1#uri-and-navigation-state-helpers) is documented here but doesn't show using the events.

**Comment by DamianEdwards** [comment]
Would be a great candidate for an analyzer

**Comment by guardrex** [comment]
Is this the pattern you'd like to recommend?

```razor
@implements IDisposable

...

@code {
    private Starship _starship = new Starship();
    private bool _formInvalid = true;
    private EditContext _editContext;
    private EventHandler<FieldChangedEventArgs> _fieldChanged;

    protected override void OnInitialized()
    {
        _editContext = new EditContext(_starship);

        _fieldChanged = (_, __) =>
        {
            _formInvalid = !_editContext.Validate();
            StateHasChanged();
        };

        _editContext.OnFieldChanged += _fieldChanged;
    }

    public void Dispose()
    {
        _editContext.OnFieldChanged -= _fieldChanged;
    }
}
```

> ... using the events [from NavigationManager]

(plural)

... you're referring to more than just `LocationChanged`?

**Comment by rynowak** [comment]
Looks right. In the case the `EditContext` example it's a bit of defense in depth because in this particular example the `EditContext` lives as long as the component. However, it would be easy for someone to turn this code into an example that leaks memory.

We should also look for cases where we show timers and double-check those.

> ... you're referring to more than just LocationChanged?

You're right, there's just `LocationChanged`. There used to be others 😆

**Comment by guardrex** [comment]
Ok ... I think I have enough to work this. *See you on the PR!* 🏃

**Comment by DamianEdwards** [comment]
Would this be cleaner by just using a private method rather than a private field and lambda expression?, e.g.

``` c#
    private Starship _starship = new Starship();
    private bool _formInvalid = true;
    private EditContext _editContext;

    protected override void OnInitialized()
    {
        _editContext = new EditContext(_starship);
        _editContext.OnFieldChanged += HandleFieldChanged;
    }

    private void HandleFieldChanged(FieldChangedEventArgs e)
    {
        _formInvalid = !_editContext.Validate();
        StateHasChanged();
    };

    public void Dispose()
    {
        _editContext.OnFieldChanged -= HandleFieldChanged;
    }
```

**Comment by guardrex** [comment]
Sounds good to me.

```csharp
private void HandleFieldChanged(object sender, FieldChangedEventArgs e)
{
    _formInvalid = !_editContext.Validate();
    StateHasChanged();
}
```
