### ISSUE TITLE
Support colorization of the @code directive for Razor components

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#17296]
The highlight.js language definition for CSHTML/Razor doesn't currently specify `@code` as a valid directive. Therefore, colorization isn't applied to the keyword in our code snippets. For example:

![image](https://user-images.githubusercontent.com/10702007/76586016-9fb85900-64ad-11ea-936f-6b1262bcd9c7.png)

**Comment by Paul-Dempsey** [comment]
September now and syntax highlighting in .razor is still seriously broken (not just the @code keyword as this issue suggests -- the duped issue covers the problem better).

**Comment by scottaddie** [comment]
@Paul-Dempsey We're blocked on build issues in the fork of highlight.js that's being used for syntax highlighting on the docs platform. I'm involved in an offline discussion with @IEvangelist and @DuncanmaMSFT on how we move forward.

**Comment by scottaddie** [comment]
The fix for this issue is found at https://github.com/DuncanmaMSFT/highlight.js/pull/34.

**Comment by guardrex** [comment]
Fixed by https://github.com/DuncanmaMSFT/highlight.js/pull/34 (merged on May 27).
