### ISSUE TITLE
Provide guidance on how to switch an app from Blazor Server to Blazor WebAssembly and the reverse

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#17294]
We should provide guidance on how to take a Blazor Server app and convert it to a Blazor WebAssembly app and the reverse.

**Comment by guardrex** [comment]
Is this merely related to ... or is it a dup of ... https://github.com/dotnet/AspNetCore.Docs/issues/12572?

**Comment by danroth27** [comment]
They are certainly related, although the scenarios are a bit different. This issue is about migrating from one hosting model to the other. #12572 is about having a hybrid app that can do either hosting model. There's certainly a lot of overlap between these two topics.

**Comment by guardrex** [comment]
*Switch* is merely *conversion*, and that's easy enough to work out.

When we come to #12572, I'll either need notes/snippets on how to compose it or one of the engineers to hack up a sample.

I wish both subjects could be covered in the same topic to economize coverage of related subject matter.

If covered together **_in a new topic_** .........

* **_ASP.NET Core Blazor hosting model conversion and hybrid apps_**
* Physical location (URL): blazor/hosting-model-conversion-and-hybrid-apps.md
* TOC: Hosting model conversion and hybrid apps (position it after the existing *Hosting models configuration* topic)
* UID: blazor/hosting-model-conversion-and-hybrid-apps

If **_not a new topic_**, can these subjects be covered in new sections of the [Hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1) topic?

**Comment by shoffma1** [comment]
From a user perspective, both topics would be great to have.  For me currently, I already have a production server-side app that seems like it would benefit from moving to web assembly, due to network latency.  From what I have seen of the preview sample template, its missing quite a bit, such as the ability to setup authentication from the start.
Looking forward to the work on this documentation, and it is most appreciated.

**Comment by guardrex** [comment]
> its missing quite a bit, such as the ability to setup authentication from the start.

We just loaded those docs for **_preview_**. The scenarios aren't supported for production just yet. You can see those topic tho starting at :point_right: https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/

**Comment by MisinformedDNA** [comment]
Anything new here since Build/Blazor 3.2 RTM?

**Comment by guardrex** [comment]
There's a sample of this now ... see https://github.com/danroth27/BlazorNet5Samples.

We'll get this topic/section done asap, but it should follow the Blazor WASM security work. I have this as a high P2 priority item, and I hope to get to it *soon-ish* ... within a couple of weeks. In the meantime, check out the sample app :point_up:.

**Comment by guardrex** [comment]
So much for **_"within a couple of weeks"_** ... yeah ... right! :smile:

It's not clear if this can be reached until 2021 due to the need for UE passes on all of the Blazor topics. If not reached before mid-December, then I'll try to work this early in 2021 ... January hopefully 🤞.

**Comment by guardrex** [comment]
**UPDATE (11/2/22)**: This issue is in discussion offline right now. I'll post an update as soon as I hear back if the update doesn't come directly from DR or Artak.

**Comment by guardrex** [comment]
@danroth27 @mkArtakMSFT ... Do you still want this worked? I'm trying to work off the backlog, and I don't recall what you decided on this one.

If we do ... I'm glad that we (*cough cough* ... ***I*** ... *cough* 😄) waited this long. Any such conversion topic will need attention ***every release***, and I think ... ***hope*** ... things are stable enough to make coverage for this stable going forward.

If we proceed with coverage, I recommend that we go >=7.0 and not cover prior releases, but let me know which versions you want covered.

**Comment by guardrex** [comment]
Thanks @danroth27 ... *Will do!* 👍

**Comment by guardrex** [comment]
@danroth27 ... Looks like *Full-stack web UI* feature coverage will make this issue obsolete. Should it be closed? 🗑️
