### ISSUE TITLE
Capture references to components - in a foreach loop?

### ISSUE THREAD

**Issue by rrsit** [dotnet/AspNetCore.Docs#17291]
[EDIT by guardrex to set the code block]

the section "Capture references to components" explains how to "link a component to a variable".

but what happens when components are declared in a @foreach loop?

```razor
@foreach (var x in list)
{
    <MyLoginDialog @ref="_loginDialog" ... />
}

@code {
    private MyLoginDialog _loginDialog;

    private void OnSomething()
    {
        _loginDialog.Show();  <---- which component do we access, assuming list contains 3 elements?
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the question @rrsit ... does this help :point_right: https://github.com/dotnet/aspnetcore/issues/17361#issuecomment-558138782

... and leave this issue open if it does because I agree that the pattern might be worth mentioning.

**Comment by guardrex** [comment]
... this is also looks related :point_right: https://github.com/dotnet/aspnetcore/issues/13358

**Comment by guardrex** [comment]
Like this example :point_right: https://github.com/dotnet/aspnetcore/issues/13358#issuecomment-582057368

**Comment by guardrex** [comment]
These are usually triaged by engineering on Fridays, so let's leave this up for a look. :eyes:

Artak, should we engage with any coverage for this scenario?

**Comment by rrsit** [comment]
thanks, i was expecting this answer (and actually using this pattern in my test code, it works).
the reason i'm posting here is because i think the doc needs clarification on that specific question. why? because i ran into the following thing today:

i tried out radzen blazor components today, and when i generate a page with a grid, that contains a sub-grid for each row, the following code is generated:

`<RadzenGrid @ref="grid0" ...>
          <Columns>
            ... some columns...
          </Columns>
          <Template Context="testModelsTestMeasure">
            <RadzenGrid @ref="grid1" ... >
              <Columns>
                  ... inner columns...
               </Columns>
`
so, the code generated has a ref to grid0, and then several refs to grid1 objects per row of the parent grid. (?)

in the codebehind file i see this:

`        protected RadzenGrid<Test.Models.Test.Measure> grid0;

        protected RadzenGrid<Test.Models.Test.MeasureTask> grid1;
`

so there is only a single reference to grid1 (as oposed to your answer, which should be a list)

grid1 then gets called and used like this:
`        protected async System.Threading.Tasks.Task MeasureTaskAddButtonClick(MouseEventArgs args, dynamic data)
        {
            var result = await DialogService.OpenAsync<AddMeasureTask>("Add Measure Task", new Dictionary<string, object>() { {"measureid", data.id} });
              grid1.Reload();
        }`

and everything is fine, no exceptions, the program works as expected and inserts data correctly at the intended tables and rows.
this is contracting your statement. what am i missing?

**Comment by guardrex** [comment]
Sure thing.

As far as I can tell from the discussion over there, they just haven't reached a critical mass of feedback to say/do more. When Artak sees this, he'll let us know if we should doc something now or close and wait until more feedback comes in for formal engineering action or an approved engineering pattern that they'd like to pitch.
