### ISSUE TITLE
[Blazor] Host multiple client applications side-by-side

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#17308]
This is a placeholder issue for the docs. I'll be writing the contents and posting them here. No action needed until then

**Comment by javiercn** [comment]
Full sample here
https://github.com/javiercn/BlazorMultipleApps/tree/05a66d42c024baec7b9701b3eebf5ca8dd6f93b4

Startup.cs
https://github.com/javiercn/BlazorMultipleApps/commit/05a66d42c024baec7b9701b3eebf5ca8dd6f93b4#diff-db34dd0fe01572a34b75d3013ab5b828R47-R58

Base path for the app
https://github.com/javiercn/BlazorMultipleApps/commit/05a66d42c024baec7b9701b3eebf5ca8dd6f93b4#diff-8e7ed314d2c8757612dcae9e3af39deaR6

Alternative using MapWhen
https://github.com/javiercn/BlazorMultipleApps/blob/13cefa97483641e08ee2c1d7eabee186147d4dd3/BlazorMultipleApps/Server/Startup.cs#L47-L71

**Comment by glararan** [comment]
I would like to ask how to setup correctly following:

- First app: domain.com/{......}
- Second app: domain.com/login
- Third app: domain.com/thirdapp/{...}

Brackets means there can be addional pages

For now I am troubleshooting just second app.
Startup.cs is following
```
            app.UseHttpsRedirection();
            app.UseBlazorFrameworkFiles();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.MapWhen(context => context.Request.Path.Value.Contains("login"), login =>
            {
                //login.Use((ctx, nxt) =>
                //{
                //    ctx.Request.Path = "/FirstApp" + ctx.Request.Path;
                //    return nxt();
                //});
                login.UseBlazorFrameworkFiles("/login");
                login.UseStaticFiles();
                login.UseRouting();
                login.UseAuthentication();
                login.UseAuthorization();

                login.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapFallbackToFile("/login/{*path:nonfile}", "login/index.html");
                });
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
                endpoints.MapFallbackToFile("index.html");
            });
```

wwwroot structure:
- index.html (base href: /)
- login
 - index.html (base href: /login/)

Issue: if i navigate to /login/ then its using first app instead second with output "Not found". I am pretty sure I did something wrong in app.MapWhen
