### ISSUE TITLE
dotnet-client.md : Add an example for console application

### ISSUE THREAD

**Issue by rakotomandimby** [dotnet/AspNetCore.Docs#17305]
Issue description

The code sample in https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md is about a WPF application.
I would like to complete it to cover a "Console Application" too.

_I create this issue in order to PR against it_

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
