### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by lukos** [dotnet/AspNetCore.Docs#17301]
I don't think the motivation for these is very clear. I can inject per-page scripts/css using @section and bringing in content via an html file to avoid having that inline would work with a normal script tag. The examples would be better if they did something that wouldn't otherwise be possible using the existing mechanisms.

What would be useful is explaining how to do the same thing inside a normal tag helper e.g. add scripts or css to head/body conditionally based on tag helper logic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d627ece-78c4-d244-63a8-d43556ca1653
* Version Independent ID: 069ef9fd-61c2-2c65-d0fe-60d272723f03
* Content: [Tag Helper Components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/th-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/th-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/th-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. Unfortunately we don't have the resources to update this doc.
