### ISSUE TITLE
async controllers

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17302]
@JHeLiu commented on [Fri Mar 13 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/252)

On. Net core we're seeing more asynchronous controllers, and whether it's better to do that, or whether it's better to do that in a write case, or whether it's better to do that in a write case, or all of that, hopefully the documentation will give you a hint

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [教程：使用 ASP.NET Core 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Fri Mar 13 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/252#issuecomment-598614422)

Hello, @JHeLiu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Async is generally preferred.
