### ISSUE TITLE
Additional Section for Adding Roles, or Policies

### ISSUE THREAD

**Issue by denmitchell** [dotnet/AspNetCore.Docs#17317]
This documentation was very helpful.  The page suggests that we have full access to configure Identity Server as we see fit.  In looking at the overloads for .AddIdentityServer and .AddApiAuthorization in the server project's Startup class, that does seem to be true; however, it would be helpful to provide another section where you demonstrate how to configure an app to support roles or policies -- to support [Authorize(Roles="...")], [Authorize(Policy="...")], &lt;AuthorizeView Roles="..."&gt;, &lt;AuthorizeView Policy="..."&gt;.  Also, it would be helpful to discuss (even at a high-level) how the pattern could be adapted to support a single Blazor WebAssembly app that uses multiple APIs with a single login and multiple Blazor WebAssembly applications that each use a common API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @denmitchell ... Thanks for the feedback. This was the one topic that I didn't get a chance to personally test here (the technical aspects were published directly from engineering), so I'm glad to hear that your experience was good.

> another section where you demonstrate

Covered as *overview*-level concepts ...

* For the `[Authroize]` attribute, we cross-link to the main doc set :point_right: https://docs.microsoft.com/aspnet/core/security/blazor/#authorization
* For `<AuthorizeView {Roles or Policy}="...">` :point_right: https://docs.microsoft.com/aspnet/core/security/blazor/#role-based-and-policy-based-authorization

> discuss (even at a high-level) how the pattern could be adapted to support a single Blazor WebAssembly app that uses multiple APIs with a single login and multiple Blazor WebAssembly applications that each use a common API.

For that, we'll see if management is interested. They usually look at these on Fridays, so you should hear back on Friday, the 20th or the 27th.

**Comment by AlbertoPa** [comment]
If you are trying to use roles in the Auth API, see this (aka they don't work without some manual hack): https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-3.1

**Comment by AlbertoPa** [comment]
One way to make roles work is the following:

1. Add roles as claims. The traditional
`await _userManager.AddToRoleAsync(user, roleName);`
is not sufficient. One needs to use:
`await _userManager.AddClaimAsync(user, new Claim(ClaimTypes.Role, roleName));`
where 'roleName' is a string with the name of the role (e.g. "Administrator").

2. Implement the 'IProfileService' interface (See: http://docs.identityserver.io/en/latest/reference/profileservice.html). Specifically, in the 'GetProfileDataAsync' of the implementation, map the roles added as claims to Identity to the roles used in the generation of the JWT. 
```
...
// Create a System.Security.Claims.ClaimsPrincipal for the user (get the user from UserManager as usual)
System.Security.Claims.ClaimsPrincipal claimsPrincipal = await 
    _claimsPrincipalFactory.CreateAsync(user);

// Recover the existing claims
List<System.Security.Claims.Claim> claimList = claimsPrincipal.Claims.ToList();

// Recover user claims from Identity
var userClaimList = await _userManager.GetClaimsAsync(user);

// Map role claims in identity to role claims in the JWT
foreach (var claim in userClaimList)
{
    if (claim.Type == ClaimTypes.Role)
    {
        claimList.Add(new Claim(JwtClaimTypes.Role, claim.Value));
    }
    else
     {
         claimList.Add(claim);
     }
}

context.IssuedClaims = claimList;
```

3. In Startup.cs add roles to Identity, modify:

```
services.AddDefaultIdentity<ApplicationUser>(
    options => options.SignIn.RequireConfirmedAccount = true)
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

to

```
services.AddDefaultIdentity<ApplicationUser>(
    options => options.SignIn.RequireConfirmedAccount = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

4. Always in Startup.cs, add the IndentityProfuleService implementation to IdentityServer:
```
services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, ApplicationDbContext>()
    .AddProfileService<IdentityProfileService>();
```
This should work and checking the user's claims should list roles.

**Comment by guardrex** [comment]
Related to https://github.com/dotnet/AspNetCore.Docs/issues/17649. Work these together.
