### ISSUE TITLE
Add an example for console application

### ISSUE THREAD

**Issue by rakotomandimby** [dotnet/AspNetCore.Docs#17315]
The code sample is about a WPF application.
 I would like to complete it to cover a "Console Application" too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
We'll consider this. Thanks for the suggestion.

**Comment by rakotomandimby** [comment]
@Rick-Anderson , I am going to provide the PR myself

**Comment by Rick-Anderson** [comment]
@bradygaster can you approve or reject the proposed PR?

**Comment by mincasoft** [comment]
I'm too

**Comment by epmpub** [comment]
The code sample is about a WPF application.
I would like to complete it to cover a "Console Application" too.

me too.

**Comment by bradygaster** [comment]
@Rick-Anderson I don't see the PR linked herein. Apologies if I'm missing it - attach that and i'll gladly approve. I'd also like to add a sample herein for the Blazor .NET client scenario.

**Comment by Rick-Anderson** [comment]
@rakotomandimby  go ahead and provide a PR.

**Comment by bradygaster** [comment]
Closing as we have seen no PR. Also - the Background Service article may be of interest to you, as it shows how to use an `IHostedService`-based console app (like a Worker Service template) as a SignalR client. Hope this is helpful, but if you do have a PR, please send it in and link to it in this issue. Thanks!
