### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Buzzkill-McSquare** [dotnet/AspNetCore.Docs#17311]
I've followed the steps verbatim and the "ResolveBlazorRuntimeDependencies" task fails with the following error;

```System.IO.FileNotFoundException: Could not load file or assembly '/home/ryan/BlazorSignalRApp/Client/obj/Debug/netstandard2.1/BlazorSignalRApp.Client.dll'```

I'm using Visual Studio Code to work on the app. I've tried running the "Run Without Debugging" command as well as running `dotnet run`, `dotnet build` and `dotnet clean && dotnet build` in both the Client & Server apps, all result in the same error.

I'm also using WSL2 along with its integration into VSCode. I've tried running the commands both through the integrated terminal and the Windows Terminal.

The .NET CLI version I'm using is 3.1.101

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Buzzkill-McSquare ... Open this for the product unit on the engineering repo. Put a "cc: @guardrex" at the bottom of your opening comment so that I get pings on the discussion. If the error is something we need to address on the doc side, then I'll re-open and work this issue after we hear back from engineering.

https://github.com/dotnet/aspnetcore/issues
