### ISSUE TITLE
ApiController attribute on multiple controllers

### ISSUE THREAD

**Issue by JandosKh** [dotnet/AspNetCore.Docs#17314]
Example code shows MyControllerBase being an non-abstract class. However this will throw an error: "Action methods on controllers annotated with ApiControllerAttribute must be attribute routed".
Must be abstract class derived from ControllerBase class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by domicioam** [comment]
@JandosKh this should be the expected behavior according to the docs. The error message is saying you need to add the [Route] attribute to the action in the controller.
