### ISSUE TITLE
Update publish folder paths

### ISSUE THREAD

**Issue by cornem** [dotnet/AspNetCore.Docs#17325]
It appears that the latest preview no longer publishes assets to `{ASSEMBLY NAME}/dist/` but instead to `wwwroot`. The documentation should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cornem ... it was taken care of on https://github.com/dotnet/AspNetCore.Docs/pull/17283. It *almost* went live on Friday on https://github.com/dotnet/AspNetCore.Docs/pull/17313. :smile: I'll take it live now.

**Comment by guardrex** [comment]
*Oh!* I see what you mean ... additional lines not covered by #17283. Thanks ... I'll patch those up.

**Comment by guardrex** [comment]
.

**Comment by guardrex** [comment]
.
