### ISSUE TITLE
Can not get routing desired working, worked in framework

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/AspNetCore.Docs#17320]
I cannot get routing to work the same way as i could in Framework with Core 3.1

I am using Core 3.1....and preferred way, using UseEndpoints and Route attribute.

Framework;
I have the default area registers
```
 public override string AreaName 
        {
            get { return "Importer"; }
        }

        public override void RegisterArea(AreaRegistrationContext context)
        {
            context.MapRoute(
                "Importer_default",
                "Importer/{controller}/{action}/{id}",
                new { controller = "Dashboard", action = "Index", id = UrlParameter.Optional},
                new[] { "Paradox.Web.Areas.Importer.Controllers" } //need for when using areas
            );
        }
```
```
[RouteArea("Importer", AreaPrefix = "")]
[RoutePrefix("Org/{orgName}/Importer/Source/Template")]
 public class TemplateController : BaseController
```
In my "Importer" Area, I have controllers with names: "Template" and "Source"

 [area] Importer
------- [controller] Source     
------------------------- Url: Importer/Source
------------------------- Url: Importer/Source/Create [get]
------------------------- Url: Importer/Source/Create [post]
------------------------- Url: Importer/Source/Edit/{id} [get]
..ect
------- [controller] Template  
------------------------- Url: Importer/Source/Template/{id}
------------------------- Url: Importer/Source/Template/Create/{id}
------------------------- Url: Importer/Source/Template/Edit/{id}
..ect

In Framework i could use the above as prefix, and then use on these on the actions.
[Route("{id}")]
[Route("Create/{id}")]
[Route("Edit/{id}")] 
[Route("Delete/{id}")]

But in Core, this does not work.

given the 
```
    &lt;a class="" href="@Url.Action("Index", "Template", new { Area = "Importer", id = item.Id })"&gt;
           Templates &lt;span class="badge badge-info"&gt;@item.TemplateCount&lt;/span&gt;
     &lt;/a&gt;
```
or new way 
```
     &lt;a asp-area="Importer"  asp-controller="Template" asp-action="Index"  asp-route-id="@item.Id"&gt;
              Templates &lt;span class="badge badge-info"&gt;@item.TemplateCount&lt;/span&gt;
     &lt;/a&gt;
```
I have been playing around with like every combo i can think of and simply cant get it to do the right 
thing.

The above tags either should results in :
Org/{orgName}/Importer/Source/Template/{id}
but will either be 
Org/{orgName}/Importer/Template/{id}

in core 
as a base for core im using 
```
       endpoints.MapAreaControllerRoute(
                   name: "Importer_default",
                   areaName: "Importer",
                   pattern: "Org/{orgName}/{area:exists}/{controller=Dashboard}/{action=Index}/{id?}");
```

or breaking other links. please advise how i would get this to work.

I can put this on stack-overflow but really think its something to do with the Routing itself.
aka what are these in core.
[RouteArea("Importer", AreaPrefix = "")]
[RoutePrefix("Org/{orgName}/Importer/Source/Template")]
as every combo i have tried on Template controller has not working

Core:
[Area("Importer")]
[Route("Org/{orgName}/Importer/Source/Template")]
[Route("Org/{orgName}/Importer/Source/Template/[action]/{id?}")] &lt;--- tried
[Route("Org/{orgName}/[area]/Source/[controller]/[action]/{id?}")]   &lt;--- tried
[Route("Org/{orgName}/[area]/Source/[controller]/[action]")]            &lt;--- tried
[Route("Org/{orgName}/Importer/Source/[controller]")]                    &lt;--- tried
[Route("Org/{orgName}/[area]/Source/[controller]")]                         &lt;--- tried
public class TemplateController : BaseController

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
A quick glance looks like your mixing up conventional routing with attribute routing.  Hopefully PR #16456 will merge soon and you'll be able to use that to figure out what you're doing wrong.

**Comment by Seabizkit** [comment]
hi Rick, I'm trying to read :
https://github.com/dotnet/AspNetCore.Docs/blob/rynowak/3.x-routing-update/aspnetcore/fundamentals/routing.md
and honestly its making it hard to understand what i need to do;

im starting with Core 3.1 and moving a framework mvc 5.7.2 over.

I have 3 areas, 
- Org
- Sysadmin
- Importer

and the default mvc [controller]/[action]/id?  (area = "")

I am using traditional controllers and views, moving over from framework.

how am i meant to get his to all work, its really confusing... am i meant to use 
```
app.UseEndpoints(endpoints =>
{
}
```
or 
assuming this has config for "Area"'s. 
```
app.UseMvc(routes =>
{
    routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}");
});
```
normal routes
- {controller=Home}/{action=Index}/{id?}
then for importer, this is not how ive registered just stating the type of url 
- Org/{orgname}/Importer/Source/{action=Index}/{id?}
- Org/{orgname}/Importer/Source/Template/{action=Index}/{id?}
- Org/{orgname}/Importer/{controller=Home}/{action=Index}/{id?}

reading the new doc implies i should try `app.UseMvc(routes =>`
Thought this was the older way and `app.UseEndpoints` should be preffered

like dont get me wrong i can get most of it to work, using  `app.UseEndpoints` but when i trying and say `Url.Action("Index", "Template", new { Area = "Importer", id = item.Id })`

It will not put "Source" as a "Prefex" 

`Org/CompName/Importer/Source/Template/Index/ItemId`

but will do something like 

`Org/CompName/Importer/Template/Index/ItemId`

which i can understand as the default ares is kicking in 
```
  endpoints.MapAreaControllerRoute(
                   name: "Importer_default",
                   areaName: "Importer",
                   pattern: "Org/{orgName}/{area:exists}/{controller=Dashboard}/{action=Index}/{id?}");
```
so how do i for "Template" controller in "Importer" area tell it to generate 

`Org/CompName/Importer/Source/Template/Index/ItemId`

when it sees 

`Url.Action("Index", "Template", new { Area = "Importer", id = item.Id })`

would appreciate your help in point me in the right direction.

**Comment by Seabizkit** [comment]
an answer to this would be great! as i believe i'm am using it correctly simply does not work.

this is hold me back, a have taken time to try figure this out would love some feedback on how this is meant to work.

This was possible in framework, seem not supported or a am doing something wrong, but what?

**Comment by Rick-Anderson** [comment]
* Go to [this DropBox link](https://www.dropbox.com/sh/yy994551cje0kap/AAB0tRnm7gze2kYrSYPSFHIda?dl=0)
* In the upper right, select Donwload -> Direct download
* Click on HTML files.

**Comment by Seabizkit** [comment]
Hi Rick, fyi finally figure out a solution

 constraints: new { area = "Importer", controller = "Template" }

so something like this seesm to be doing the trick
```
 endpoints.MapAreaControllerRoute(
                   name: "ImporterSource_default",
                   areaName: "Importer",
                   pattern: "Org/{orgName}/Importer/Source/{controller=Template}/{action=Index}/{id?}", 
                   constraints: new { area = "Importer", controller = "Template" }
                   );
```
as always seem obvious now ;-)

thx

**Comment by Rick-Anderson** [comment]
@Seabizkit  glad you got it working. Did you have a chance to review the updated topics?

**Comment by Seabizkit** [comment]
looks gook...(see all types fixed) so much info.., i think even if its not perfect,  more current info is better than older info, thx rick
