### ISSUE TITLE
Incorrect command: dotnet aspnet-codegenerator

### ISSUE THREAD

**Issue by Jaraxal** [dotnet/AspNetCore.Docs#17322]
I'm using dotnet v 3.1.102 on LinuxMint (Ubuntu).  When I ran the command to install the code generator: `dotnet tool install --global dotnet-aspnet-codegenerator`

It installed as `~/.dotnet/tools/dotnet-aspnet-codegenerator`

The command example to run doesn't work: `dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries`

I had to run: `~/.dotnet/tools/dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries`

Similarly, I had a problem with dotnet ef.  The example shows:

```
dotnet ef migrations add InitialCreate
dotnet ef database update
```

I had to run:

```
~/.dotnet/tools/dotnet-ef migrations add InitialCreate
~/.dotnet/tools/dotnet-ef database update
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Jaraxal  your saying all 
`dotnet command`
must be replaced with
`~/.dotnet/tools/dotnet-command`

There must be an alias `~/.dotnet/tools/dotnet command` that also works.

**Comment by Jaraxal** [comment]
@Rick-Anderson This may be a Linux specific issue; I'm not sure.  I'm able to run dotnet commands just fine.  

```
$ dotnet --version
3.1.102
```

The install command for aspnet-codegenerator as listed in the tutorial is:

```
dotnet tool install --global dotnet-aspnet-codegenerator
```

That is what I ran and it installed successfully.  However, it created the tools under `~/.dotnet/tools`

```
$ ls ~/.dotnet/tools/
dotnet-aspnet-codegenerator  dotnet-ef
```

I'm unable to run `dotnet aspnet-codegenerator`:

```$ dotnet aspnet-codegenerator
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-aspnet-codegenerator does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I'm unable to run `dotnet dotnet-aspnet-codegenerator`:
$ dotnet dotnet-aspnet-codegenerator
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-dotnet-aspnet-codegenerator does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by serpent5** [comment]
In Linux, the `~/.dotnet/tools` must be added to `PATH`.

**Comment by Rick-Anderson** [comment]
@Jaraxal  I was under the impression that Linux folks were supposed to know they needed to:

 `~/.dotnet/tools` must be added to `PATH`.
Can you try that and test the commands?

**Comment by Jaraxal** [comment]
@Rick-Anderson I know that adding `~/.dotnet/tools` to the `PATH` will work, somewhat.  I would still need to run the command as `dotnet-aspnet-codegenerator` whereas the example in the tutorial is `dotnet aspnet-codegenerator`.  Notice the difference of the `-`.

I approached the tutorial as a new .NET programmer and only recently installed .NET to work through the tutorial.  In doing so, I followed these instructions: [Install Docs](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804).

I didn't see any references to a requirement to modify my PATH.  The tutorial doesn't cover it either.  So it seems to me to be a bit of "curse of knowledge" where it is assumed that someone knows it is a requirement.

**Comment by Rick-Anderson** [comment]
> I would still need to run the command as `dotnet-aspnet-codegenerator` 

Are you sure? Have you tried it?

Didn't you need to export `dotnet` to get it to work?

**Comment by Jaraxal** [comment]
It actually works without the `=`.  I had a typo in my PATH.  So it looks like I'm good, but it wasn't a blocker.  I was able to move past that as indicated by specifying the path.

I'm curious, are there docs that reference having to modify PATH as part of the installation of .NET?  I could have missed it.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/core/install/sdk?pivots=os-linux

```
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

**Comment by Jaraxal** [comment]
Thank you @Rick-Anderson.  The reference to the path is under the manual install section.  The very beginning of that doc also shows the Package Manager approach, which is what I followed.  The only references to the PATH in Package Manager install document are that it will be auto-set, which didn't happen for me.
