### ISSUE TITLE
Cancel method is not static 

### ISSUE THREAD

**Issue by MichaelStett** [dotnet/AspNetCore.Docs#17323]
[There](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server?view=aspnetcore-3.1#cancel-early-and-avoid-use-after-dispose) is a mistake in:
```csharp
public void Dispose()
{
    CancellationTokenSource.Cancel();
}
```

`Cancel()` is not a static method

So it should be:
```csharp
public void Dispose()
{
    TokenSource.Cancel();
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a9f84a-feaa-d2b0-409a-01f75f9101a0
* Version Independent ID: aeec639f-a9d6-2f00-b61f-2c316ef6afb6
* Content: [Secure ASP.NET Core Blazor Server apps](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @MichaelStett ... I'll fix that up in the morning.
