### ISSUE TITLE
Reload/Refresh won't trigger breakpoint, but navigation would.

### ISSUE THREAD

**Issue by tedypranolo** [dotnet/AspNetCore.Docs#17336]
I am using 3.2 preview. I followed the instructions here and added breakpoint in the browser debugger. Because I want to break within `OnInitializedAsync` I figured the obvious way is to reload the page. But that didn't work. The breakpoint would only work if I navigate to the razor.page , for example using the navigation menu in my blazor app. I think this fact should be mentioned in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @tedypranolo ... I'm going to move this over to the existing issue that pertains to updates for Blazor WebAssembly debugging. When the engineer supplies content for that issue, we should get feedback on this scenario.

**Comment by guardrex** [comment]
@tedypranolo I'm re-opening to take a look at this separately from the 3.2 Preview 3 release.

**Comment by guardrex** [comment]
@tedypranolo I can't repro this behavior here ... my breakpoint is hit both via navigation and page reload in the browser. I'll keep an :ear: open for further reports on this. If you think you've discovered a bug, open an issue with engineering at https://github.com/dotnet/aspnetcore/issues.
