### ISSUE TITLE
Obselete Functions

### ISSUE THREAD

**Issue by ibrahimuludag** [dotnet/AspNetCore.Docs#17338]
Some functions like UseWebpackDevMiddleware is obselete for .Net Core 3.1. Could you update this page for .Net Core 3.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Tracked in #18405
