### ISSUE TITLE
Configure<IdentityOptions> doesn't work

### ISSUE THREAD

**Issue by angar4ik** [dotnet/AspNetCore.Docs#17347]
The code doesn't affect password complexity.

`services.Configure<IdentityOptions>(options =>
            {
                // Password settings.
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequiredLength = 3;
                options.Password.RequiredUniqueChars = 0;
            });`

.NET Core 3.1

**Comment by guardrex** [comment]
@angar4ik ... Recommend that you close this and re=open it from the **This page** feedback button and form at the bottom of the topic ... it will add metadata to your issue for tracking and automatically ping the author of the topic.
