### ISSUE TITLE
What about constraints for type parameters?

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/AspNetCore.Docs#17348]
How do you (can you) specify type parameter constraints?  In particular, specify that the type must implement an interface or derive from a base class?  For example, suppose you wanted to use functionality in the constraint (i.e. modify the table template in the example to include autogenerated cells in each row, displaying values provided by a constraint base class or interface the type parameter must implement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e918d36-59d2-2264-e6b3-27071cda549c
* Version Independent ID: c7e7e5bc-4686-d641-4f1e-da2de7491758
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/templated-components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ClaudioFriederich ... Open an issue for the product unit. Cross-link this topic ...

```
[Templated components topic](https://docs.microsoft.com/aspnet/core/blazor/templated-components)
```

Add a "cc: @guardrex" to your opening issue comment so that I can follow the discussion.

Open it at: https://github.com/dotnet/aspnetcore/issues

I'll re-open this if we can add something to the doc to cover it.

**Comment by ClaudioFriederich** [comment]
I searched and found that an issue already exists in the product unit: https://github.com/dotnet/aspnetcore/issues/8433

 

As I understand the discussion there, constraints are possible by creating a partial class for the component, and declaring the constraints in the partial class.  I have not had a chance to try this, but several people reportedly got it to work.

 

Thank you for the information and quick reply.

**Comment by guardrex** [comment]
@ClaudioFriederich ... Cool. I'll see if I can craft something temporarily for that in the doc. We don't usually document workarounds while they work on a new feature. However, I see a lot of :+1: on that issue. I'll ping you on the PR.
