### ISSUE TITLE
Dozen of blazor dotnet command doesn't work if we are using a latest listed Microsoft.AspNetCore.Blazor.Templates package

### ISSUE THREAD

**Issue by tomidix** [dotnet/AspNetCore.Docs#17349]
All of the authentication commands (standalone) in docs doesn't work if we don't specifically follow get started page of the docs in which it is stated that 3.2.0-preview2.20160.5 should be used. 
However, it doesn't make sense to go through all the documentation each and every time you want to update your project so please list this version on nuget.org. You'll save people a lot of time.

**Comment by guardrex** [comment]
Hello @tomidix ...  I hear you on that. They don't know the version number for a preview release until they get to the release. It's just one of those little things that devs have to deal with during this period. The good news is that Blazor WebAssembly will be an officially released product in a few months. After that, you won't need to do the separate template install step.

@mkArtakMSFT can comment on why the latest version of the package isn't listed in NuGet.

https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor.Templates/3.2.0-preview1.20073.1

**Comment by tomidix** [comment]
I thought this would be the case so that's why I wrote just to list this specific version. 

If there is a specific reason why it's not listed then it would be nice if the standalone auth documentation pages could have the requirements changed too.. specific template version should be mentioned there as I red this and thought that I'm satisfying the requirements:
_The guidance in this article applies to the ASP.NET Core Blazor WebAssembly template version 3.2 or later. To obtain the latest Blazor WebAssembly template, see Get started with ASP.NET Core Blazor._

**Comment by guardrex** [comment]
> specific template version should be mentioned there

We do have the Blazor WebAsssembly notes in INCLUDE files for all of the topics ...

The article note is ...

> [!NOTE]
> The guidance in this article applies to the ASP.NET Core Blazor WebAssembly template version 3.2 or later. To obtain the latest Blazor WebAssembly template, see <xref:blazor/get-started>.

The section note is ...

> [!NOTE]
> The guidance in this section applies to the ASP.NET Core Blazor WebAssembly template version 3.2 or later. To obtain the latest Blazor WebAssembly template, see <xref:blazor/get-started>.

Those could say at the end .....

> The latest Blazor WebAssembly template version is `3.2.0-preview2.20160.5`.

Then, I only need to update two files to update the version everywhere each pre-release. That would be easy, and it would only be temporary. Of course, the NOTE INCLUDE files will be deleted when Blazor WebAssembly reaches its first regular release.

@mkArtakMSFT, does that sound good to you?
