### ISSUE TITLE
PaginatedList<T> causes a warning in combination with IQueryable<T>.Include

### ISSUE THREAD

**Issue by dfyx** [dotnet/AspNetCore.Docs#17354]
`PaginatedList<T>.CreateAsync()` as it appears right now causes an EFCore warning at runtime when `source` loads related data through `Include`. For example if I want to display a list of enrollments in my table, I get the following:

> [Warning] Microsoft.EntityFrameworkCore.Query: The Include operation for navigation '[s].Enrollments' is unnecessary and was ignored because the navigation is not reachable in the final query results. See https://go.microsoft.com/fwlink/?linkid=850303 for more information."

This is correct in the sense that `CountAsync()` does indeed ignore `Include` operations but not really helpful because the `ToListAsync()` in the following line uses the same `IQueryable<T>` and relies on those `Include` operations to produce the correct result.

While this issue doesn't relate directly to the content of this tutorial, the page appears the very first google search result for "asp.net core pagination" and is therefore considered *the* reference implementation by many. I would expect such an implementation to not cause any warnings in a **very** common use case.

Unfortunately, I can't think of an easy fix as `IQueryable<T>` doesn't seem to have any methods to remove operations (something like `var count = await source.WithoutIncludes().CountAsync();`) nor a way to suppress the warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you check the razor pages version? It's up to date.

Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
