### ISSUE TITLE
Unable to run with Microsoft Account

### ISSUE THREAD

**Issue by miri10134** [dotnet/AspNetCore.Docs#17367]
First, thank you for detailed guide. Unfortunately I couldn't get this to work with Microsoft (AAD) Authentication, both in my own app and in the sample application that is created by the "dotnet new blazorwasm -au Individual" command. There appeared to be several issues: 

1st: The sample application created by "dotnet -au" uses a different Javascript file. Your guide references to "_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js" which belongs to the Microsoft-Account guide and won't work here. The sample application uses "_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js" instead. 

2nd: In the sample application the value for "Authority" is set to "https://login.microsoftonline.com/". I believe this isn't a valid endpoint (at least I got a 404 with that). The url should end with something like "/common" or "/common/v2.0". 

3rd: After changing the url to https://login.microsoftonline.com/common/v2.0 I could click on "Log in" and got a promt to sign in to my Microsoft Account. It also redirected me back to my application which then stuck at "Completing your log in". I could see that it got an application token in the url, but it was unable to parse it, because the url was of the format "/login-callback#id_token=". After replacing the # with a ? the URL got parsed, but the script ended with an error somewhere deep inside the usermanager-Javascript saying that it could not find a valid state (despite one being shown in the debugger). I tried to debug and look into the Code on GitHub but couldn't find the source of this error. 

I gave up on this approach and repeated the steps from the "Standalone with Microsoft Accounts" instead (which worked in the end). 
Could you please tell me whether and what I did wrong? Or is this not intended to work with Microsoft Authentication (despite the url in the sample)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @miri10134 ...

You opened this from the [Standalone with Authentication Library topic](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1), but you seem to be referring to the [Standalone with AAD topic](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1).

Which topic are you looking at?

**Comment by miri10134** [comment]
Hello @guardrex. No, I was referring to the "Standalone with Authentication Library" topic. It is my understanding, that this method should work with any Oidc provider, including Microsoft, as stated in the topic ("such as Google, Microsoft, or other OIDC-compliant provider"). And the AAD was the only way I found to register my application for authentication with a Microsoft Account. If that was a mistake, could you give some hints in the topic where to obtain the client ID from, if not from an AAD registration?

In fact, I probably should have started with the "AAD" or "Microsoft Accounts" topic. But the issues I pointed out still remain for this topic. It should be consistent with the code example it refers to.

**Comment by guardrex** [comment]
Good point about OIDC, but *yes*, the intention is for devs who want to use AAD to follow (from scratch) the steps in either the *Standalone with AAD* or the *Hosted with AAD* topics.

Note that we're having our own little internal deltas as to what's seen and done and these topics are so new that *the paint isn't dry yet.* :smile: They've only been up a few days, so I am expecting bug reports and suggestions from readers. For example, we're working on UI and config deltas for the *Hosted with AAD* topic on https://github.com/dotnet/AspNetCore.Docs/issues/17304. Another dev is having trouble with *Hosted with AAD B2C*, but I can't repro their problem (that's on https://github.com/dotnet/AspNetCore.Docs/issues/17319).

I recommend we close this until you try the *Standalone with AAD* topic, which specifically works with AAD. If you hit a snag there (*or several* 🙈), open an issue from the bottom of that topic.

**Comment by guardrex** [comment]
wrt ...

> But the issues I pointed out still remain for this topic.

... let me check on that script and confirm. Stand-by.

wrt the authority ... that was part of my confusion about which topic you were looking at. This topic isn't directed at AAD, so this isn't where authority is documented.

**Comment by guardrex** [comment]
I see what you mean ...

```html
<script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
```

... a cut-'n-paste error (probably) ..... cut-'n-paste ... it's **_GrEaT!_** ....... until it **isn't**. :cry:

**Comment by miri10134** [comment]
As I said, I got the authentication working with the steps from "Standalone with Microsoft Accounts". So it's not critical for me any longer, just wanted to point out my struggels, so hopefully nobody has to repeat them ;) 

Yeah, those errors happen. I'm aware that this topic is quite new and that especially the Blazor templates are changing pretty fast. I just learned yesterday that there is a new preview out which uses completely different assemblies ... But I really like Blazor, so I will continue to point out issues when I run into them :)

**Comment by guardrex** [comment]
> I got the authentication working with the steps from "Standalone with Microsoft Accounts". 

Right ... sorry that I forgot what you said. I'm 🏃 on multiple fronts here.

I have that PR done, so I'll get that script source fixed shortly.

Because the Standalone with Auth Lib **didn't** work without the MSAL script and MSAL package, I'll need to ask engineering what should be done .........

@mkArtakMSFT TL;DR ... We say that the base case *Standalone with Auth Lib* guidance should work for any OIDC provider ...

> The AddOidcAuthentication method accepts a callback to configure the parameters required to authenticate an app using OIDC. The values required for configuring the app can be obtained from the IP, such as Google, Microsoft, or other OIDC-compliant provider.

... but the *AuthenticationLibrary.js* script and the package used are different for AAD topics in this node. Seems like we should guide devs right to the AAD-series topics for AAD and steer them away from this topic.
