### ISSUE TITLE
Blazor forms and validation topic feedback

### ISSUE THREAD

**Issue by bdnts** [dotnet/AspNetCore.Docs#17360]
This documentation has gaps in it larger than Florida sink holes.  These gaps leave questions unanswered, and resolving those questions suck up hours of research trying to get authoritative answers.  All of this leads to lower engineer productivity.  What gaps?  Let me list them:
1) Where is the code example?  If you are going to do code snippets, it should be required that there be an accompanying code example.  That is the first and best way to fill in the gaps.
2) Can Model and EditContext coexist?  There is nothing here that says they can or cannot.  So I'm reduced to trial and error (Boom! Error: System.InvalidOperationException: EditForm requires a Model parameter, or an EditContext parameter, but not both.)  Why couldn't that have been noted in this doc?
3) The form may be valid, but that doesn't mean the business transaction/flow can complete.  (e.g. "User already exists.") How to show that form data is incorrect (vs acceptable)?  A bank withdraw is another example.  Entering $100 as the amount to withdraw may be an acceptable form entry, but incorrect for the business transaction since there is only $50 in the account.  How is this kind of error communicated back to the form?
4) "You just gonna leave me hangin', bro?"  in the example just above "InputText based on the input event"  there is the beginning of an answer to 3, but a powerful code example was replaced with ellipses.  ("Hah, no matter, I can just go to the code example....")

All of the beautiful architecture, elegant design and hard work of developing Blazor is WORTHLESS without comprehensive documentation.  Documentation makes adoption easier, increasing productivity, and isn't Developer Productivity one of the tenets of this whole paradigm shift?  Close the loop and make great documentation to go along with a great product.

P.S. The bloggers are great, but, they rarely revisit a topic unless there is a major change.  Just look at how many use @function{} in their Blazor examples!  Authoritative documentation has to come from the source.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bdnts ... Thanks for your feedback, and I agree with your editorial remarks. [btw -- ❤️ your **_Florida_** reference ... I live in Pensacola! 🏖] Let's take a look at your points ...

1. The snippets are "code examples;" so when you say "code example," do you mean a running sample app? If so, it's a dup of https://github.com/dotnet/AspNetCore.Docs/issues/14216. We plan to perform a *big sample app overhaul* to re-align the sample app with the text. The reason that the sample app diverged from the topics was that our workload for basic scenario coverage in the topics required all of our time. The plan is to get several of the missing scenarios, such as the forms and validation coverage, into the sample app for live demonstration.
1. Sure thing, we can get that surfaced.
1. (and 4) Yes, we can flesh that out further. On the first version of the topic, we wanted to show the basic pattern. I'm interested in using a custom validation attribute with the `ServerValidate` method, if possible. I don't have any such example right now to show you ... I'll see what we can do and what engineering suggests when I work this issue.

Artak will add his notes/ideas and get this prioritized. Note that we're all 🏃🏃🏃😅 for the upcoming 3.2 release at the moment, so there could be a delay of up to eight weeks. That's a worst case scenario ... I don't think it will take that long. I'm just letting you know that we're a very small team with a heavy workload and backlog. We'll get to this as soon as we can. Worst case scenario is that we get to this **_after 3.2 releases_** (May), but I'll try to get to it before then.

**Comment by bdnts** [comment]
Hi Luke,

 

Thanks for the response.  I try to be constructive in my criticisms, but, boy you should have seen the first draft!  Lol.  It seems the big points on everything from MS are done well, but when you get down to making something real, there are these gaps that waste hours doing research.  I’m 4 months behind on a critical project—and I’m the boss!—because I’m dying by a thousand questions, that I feel should be in the documentation.  If I was in any way rude or offensive, my apologies.

 

I was employee 38 for BEA Systems (Tuxedo, Weblogic) and their first EA back in the 90s.  I know the time pressures when it comes to delivering product.  I saw on one of the requests for example around LinkGenerator that broke in a new version.  It took 6 months for the team to deliver.  Whhooaa!  I feel sorry for you all, there must be serious resource constraints, because the willingness was 110% there.  You guys must really be under the gun to deliver new products.  I am very sympathetic. 

 

And I’ll add I love Blazor.  I’ve been developing for nearly 40 years, on just about anything you can imagine, and some things you can’t.  Blazor and SignalR represent breakthrough technological approaches (the socket), which was pretty much abandoned for the web.  With the return of a continuous circuit, the possibilities are endless.  Once I get through my current deliveries, I’ll be posting full examples to Github to share.  

 

1.	Yes, running application.  I believe everything must be QAed.  One part of QAing documentation is testing with a running example to insure the snippets are bug free.  I will check out #14216.
2.	Thank you.
3.	And 4 Cool.  Taking multiple sweeps at a topic is called the Nautilus pattern in literature—working down from the macro in broad strokes down to the minute details, and is a powerful technique.  ServerValidate is also where my interest lies.  The big rock I’m trying to move at the moment is actually Identity with Blazor.  I have test project at https://github.com/bdnts/BlazorIdentity where I’m trying to work out the details of scaffolding MS Identity in an existing Blazor project.  Then I found BlazorBoilerPlate and BlazorWithIdentity.  I’m not convinced about their wholesale use of APIs, so I’m working a new branch and have converted Register.cshtml/.cs to Register.razor.  This is where I’m using the <Editform> and failure testing with duplicate names.  Working my way through EditContext, that’s where all this came up. If I come up with anything on ServerValidate, I’ll let you know.  

 

 

Cheers

Brian Douglass

 <mailto:Brian.douglass@tps-eoltp.com> Brian.douglass@tps-eoltp.com

702-254-5485

**Comment by weitzhandler** [comment]
Related: #17746.
