### ISSUE TITLE
Document how to add an XML linker config file to a library

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#17369]
@guardrex Currently we have [docs](https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/configure-linker) on how to specify an XML linker config file for a Blazor app, but we don't document how to provide one for a library, like a component library. I've put together a sample that shows how to do this: https://github.com/danroth27/ComponentLibWithXmlLinkerConfig. Basically you embed the XML file into the library as an embedded resource with the correct name the linker will pick it up. We should document this pattern. Maybe we should elevate the Configure the Linker doc to be a top level Blazor topic and add it there? Or if you have a better location, that's fine.

Eventually, this content on embedding an XML link config in a library should probably live in the .NET docs - @samsp-msft is working on that. So it would be nice to keep this content mostly generic so that once it move to the .NET docs we can then juts link off to that content.

**Comment by guardrex** [comment]
Is it directly germane to libs? If so, can it go in the [Component libary topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&tabs=visual-studio)?

**Comment by danroth27** [comment]
Yup, this is all about libs. The Component library topic is fine.
