### ISSUE TITLE
Blazor WebAss embly template missing in VS  2019  preview 16.6

### ISSUE THREAD

**Issue by uzabumuhire** [dotnet/AspNetCore.Docs#17363]
I have just installed VS 2019 preview 16.6.NET, 5.0 preview 1 SDK and the WebAssembly  3.2 preview 2 template, but when I try to create a new Blazor WebAssembly app in VS, the template is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> 5.0 preview 1 SDK

Hello @uzabumuhire ... The SDK should be 3.1.102 (check `dotnet --version` to confirm). If that's correct, next try re-installing the template (run the command in Step 2 again). If you're still having trouble getting it to show up in VS under **Blazor App* > **Configure your new project** > **Create a new Blazor app**, then open an issue for the product unit at https://github.com/dotnet/aspnetcore/issues.
