### ISSUE TITLE
Request additional access tokens - standalone

### ISSUE THREAD

**Issue by tomidix** [dotnet/AspNetCore.Docs#17366]
Hi,

I need 'Request additional access tokens' scenario but for wasm - standalone, I suppose this is already possible but probably the documentation about it is missing.
Then, what's also missing is how to use those tokens further in httpClient calls. I assume that we don't have to inject those tokens manually.
I'd appreciate if you could add this.

I described what I need to achieve in detail: https://stackoverflow.com/questions/60754751/blazor-webassembly-standalone-access-multiple-aad-protected-apis

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
