### ISSUE TITLE
It's unclear how to handle a '.' in an environment variable configuration value.

### ISSUE THREAD

**Issue by mnmadscience** [dotnet/AspNetCore.Docs#17378]
In the "environment variables" setting, it's stated clearly that ':' is not always valid and can be replaced with double underscore. However, it's very common for .NET Core configuration to reference a namespace like MyNamespace.MyClass. In that situation, I believe .NET Core lets us use a single underscore since the dot is illegal for environment variable names in most systems. A very close read of the section, including the code, lets us infer that single underscore will work. But it was not clear to me at all, and I think it should be explicitly stated just as substituting double underscore for a colon is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#environment-variables)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jbmadscience  when would you need a fully qualified name that required a `.` ?
@serpent5  please review.

**Comment by jbmadscience** [comment]
"Logging": {
    "LogLevel": {
        "MyNamespace.MyClass": "Trace"
    }
}

**Comment by Rick-Anderson** [comment]
@jbmadscience  why not write it as

```
"Logging": {
    "LogLevel": {
        "MyNamespace_MyClass": "Trace"
    }
}
```

Then config file and environment are the same.

**Comment by Rick-Anderson** [comment]
@jbmadscience  this is in thhe default *appsettings.json* file:

```
  "LogLevel": {
    "Default": "Information",
    "Microsoft": "Warning",
    "Microsoft.Hosting.Lifetime": "Information"
  },
```

You're right.

**Comment by Rick-Anderson** [comment]
```
C:\keep\ConfigSample>set Logging__LogLevel__Microsoft_Hosting_Lifetime=EnvironmentLoggingMShosting

C:\keep\ConfigSample>dotnet run
Unhandled exception. System.InvalidOperationException: Configuration value 'EnvironmentLoggingMShosting' is not supported.
```

**Comment by jbmadscience** [comment]
I had the idea that underscore would work because of the samples in the
topic we're discussing. But if that doesn't work that would explain an
issue I'm having.

Any idea what does work for setting a variable with a namespace dot in it?

**Comment by Rick-Anderson** [comment]
I'll find out - or more likely @serpent5 

```
C:\keep\ConfigSample>set Logging__LogLevel__Microsoft.Hosting.Lifetime="MyKey val"

C:\keep\ConfigSample>dotnet run
Unhandled exception. System.InvalidOperationException: Configuration value '"MyKey val"' is not supported.
```

**Comment by Rick-Anderson** [comment]
OOPs, I had that wrong. The following 3 approaches don't throw, but they don't work either:

```
set LogLevel__Microsoft_Hosting_Lifetime=EnvironmentLoggingMShosting
cd C:\keep\ConfigSample
set LogLevel__Microsoft.Hosting.Lifetime=MyEnvironmentLoggingMShosting
set LogLevel__Microsoft__Hosting__Lifetime=MyEnvironmentLoggingMShosting
dotnet run
```

The exception was because I had `Logging` before the actual key.

**Comment by Rick-Anderson** [comment]
BINGO

This works
`set LogLevel__Microsoft__Hosting__Lifetime=MyEnvironmentLoggingMShosting3`

using double underscore for dot

**Comment by Rick-Anderson** [comment]
@jbmadscience  see https://github.com/dotnet/extensions/issues/3095

**Comment by jbmadscience** [comment]
Thanks Rick!

That turns out to be a more complex issue than I had realized - I
definitely hadn't caught on that it needed only 2 nesting levels!

**Comment by serpent5** [comment]
@jbmadscience Is your problem specific to logging? As far as I know, there's no conversion from `_` or `__` to `.` in either the env provider or the logging system.

**Comment by jbmadscience** [comment]
No, the problem is in the environment variable configuration provider.

Logging is an easily reproducible and common scenario where the issue would
be visible. I'm not aware of any logging specific issue affecting the
behavior.

The env configuration provider documentation clearly discusses the
conversion between ':' and '__' because some OS's don't allow ':' in a
variable name.

The issue here is that I don't see any  documentation for handling a dot in
the name, despite that being necessary for common cases such as logging.
I'm a little confused whether that's because there is no support for it, or
whether it's just not documented. Several blog posts for earlier versions
of .NET Core appear to suggest it was supported, but is now broken.

- Joshua

**Comment by bamancio-futura** [comment]
This issue was closed neither with an explanation nor a link to how the bug is being handled.

**Comment by doggy8088** [comment]
@Rick-Anderson
Is it possible improve the doc that explain what to do if the dot or colon appear in the environment variable?

**Comment by alan994** [comment]
Any update for this? @mnmadscience @Rick-Anderson

**Comment by YarekTyshchenko** [comment]
I'm not sure if this is the right place to add this, but dots are not valid in IoT Edge config:

```
ERROR: {
  "validationErrors":[
    {
      "description":"'Logging__LogLevel__Example.Nested.Namespace' does not match any of the regexes: '^[^\\\\+#$\\\\s\\\\.]+$'",
      "contentPath":"$edgeAgent.properties.desired.modules.example-nested-namespace.env",
      "schemaPath":"properties.$edgeAgent.properties.properties.desired.properties.modules.patternProperties.^[a-zA-Z0-9_-]+$.properties.env.additionalProperties"
    }
  ]
```

I'm unable to use the workaround of setting env var for `Logging__LogLevel__Example` as this namespace contains my whole app.

**Comment by aradalvand** [comment]
How are you supposed to do this?! Still no explanation and no hint in the docs!

**Comment by LordMike** [comment]
This should be reopened. There are places where dots cannot be added, such as `systemd` units or the other deployment methods mentioned in the comments.

Similar issue that was also closed: https://github.com/dotnet/docs/issues/22817

**Comment by worldspawn** [comment]
Its clear that you cannot do this at present. Its not a supported thing. The only option currently is to create your own configuration provider (just decompile EnvironmentVariablesConfigurationProvider) and modify to support some custom character substitution.
