### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by bencalnan** [dotnet/AspNetCore.Docs#17387]
Just to clarify, when you say:

"If the user isn't authenticated, the user is redirected to the underlying authentication system, which is usually ASP.NET Core Identity." 

Is this the part when I would log in to a Google/Facebook/etc account (if i'm not logged in)?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34f7534-347a-5752-3127-fd774abea530
* Version Independent ID: af2c6c8a-d398-0202-4c28-cd5e15ce5219
* Content: [Secure ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-gb/aspnet/core/security/blazor/webassembly/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bencalnan ... *Yes* when one of those 3rd party providers is used. That's why it says "*usually*" there ... if you don't configure anything else, then it would be ASP.NET Core Identity.

**Comment by bencalnan** [comment]
Thanks that's helpful
