### ISSUE TITLE
Cookie Asp.core

### ISSUE THREAD

**Issue by Javier118** [dotnet/AspNetCore.Docs#17385]
HelLo:
I implemented the code for Cookie on file. Cs , also implemnated <partial name"_CookieConsertPartial" /> in layout.cshtml but when I hit the web through visual studio I do not get the banner with the button which may be the bug.

**Comment by guardrex** [comment]
Hello @Javier118 ... Recommend that you close this and re-open using the **This page** feedback button and form at the bottom of the topic that you're working with. It will automatically attach metadata to your issue here and automatically ping the author.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
