### ISSUE TITLE
Build a ToDo list #14

### ISSUE THREAD

**Issue by gomomohapi** [dotnet/AspNetCore.Docs#17389]
Step 14 under Build a Todo List specifies changing the &lt;h1&gt; heading instead of the &lt;h3&gt; heading. The code block makes the same mistake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1#component-parameters)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
My bad @gomomohapi ... I was working fast 🏃 on and just after the release day. I'll patch that up. Thanks for letting me know.
