### ISSUE TITLE
In CreateVM.cshtml.cs Models should be Data as shown in this comment

### ISSUE THREAD

**Issue by lwcwew** [dotnet/AspNetCore.Docs#17396]
I am such a newbe to this that I hesitate to try to make the actual change.
This:  private readonly ContosoUniversity.Models.SchoolContext _context;
Should be:  private readonly ContosoUniversity.Data.SchoolContext _context;
and
This: public CreateVmModel(ContosoUniversity.Models.SchoolContext context)
Should be: public CreateVmModel(ContosoUniversity.Data.SchoolContext context)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
They may not have been updated when we changed from models to data. It won't compile if the path is incorrec.
