### ISSUE TITLE
When adding Students CreateVM probably should add the comment below

### ISSUE THREAD

**Issue by lwcwew** [dotnet/AspNetCore.Docs#17397]
In Pages Students Index.cshtml 
This: &lt;a asp-page="Create"&gt;Create New&lt;/a&gt;
Should be changed to: &lt;a asp-page="CreateVM"&gt;Create New&lt;/a&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll look at these in the next doc sweep.
