### ISSUE TITLE
Clarify jQuery

### ISSUE THREAD

**Issue by LautaroLobo12** [dotnet/AspNetCore.Docs#17406]
It says "the built in validation methods"... but are not built in. I have to use jQuery. It should be clear that you need jQuery linked somewhere to make it work.

Cheers,
Lautaro.-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Server side is built in and client side is built in because jQuery is added to the templates.
