### ISSUE TITLE
Can you please clearly say which IDistributedCache implementations are thread safe?

### ISSUE THREAD

**Issue by alvipeo** [dotnet/AspNetCore.Docs#17400]
Please see this - https://stackoverflow.com/q/60792384/2896495.

I couldn't find answers but people suggest all the implementation *should* be thread safe. Are they?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Distributed caching master page #17553

**Comment by Rick-Anderson** [comment]
Yes
