### ISSUE TITLE
How to return the error message specified in the validation attribute

### ISSUE THREAD

**Issue by IndigoHealth** [dotnet/AspNetCore.Docs#17407]
Suppose I declare instance of my custom validation attribute like this:

```
[MyValidator(ErrorMessage = "Ouch!")]
public string SomeProperty { get; set; }
```

All of the examples in this article return a specific message (`$"Classic movies must have a release year no later than {Year}."`) when validation fails. This obviously bypasses the error message specified by the attribute declaration.

So, how does a custom validator return the error message configured by either the `ErrorMessage` or `ErrorMessageResource` attribute declaration arguments?

For extra credit: Assuming the custom validator correctly returns the error message configured by the attribute declaration arguments (if any), then how does the validator implement a "default" error message in the case where the attribute declaration doesn't explicitly configure the error message?

***EDIT by @Rick-Anderson***
Write a standalone sample at https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/models/validation/samples showing how to call `return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));`

That's it. After that, open an issue to update this doc with the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sbsw** [comment]
After looking at `ValidationAttribute` and a some Googling, the answer to my question is:

```
return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));
```

This should be documented in the example. I haven't yet dug out the answer to how to correctly override the default error message if the `ErrorMessage` argument isn't specified on the attribute declaration...

**Comment by Rick-Anderson** [comment]
@dougbu  this should be easy to answer when you have time.

**Comment by dougbu** [comment]
@Rick-Anderson there's a number of options available, depending on the specific type of "custom validator" returning an error message. For example, a direct implementation fo `IModelValidator` can directly use resources in the validator's assembly. A subclass of [`ValidationAttributeAdapter<TAttribute>`](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.DataAnnotations/src/ValidationAttributeAdapterOfTAttribute.cs) can override its methods, including `GetErrorMessage(...)` as necessary. A `ValidationAttribute` that doesn't need additional special cases can override or use its `FormatErrorMessage(...)`. And, `ValidationAttribute`s can also implement `IClientModelValidator` to return the right error message.

But, just adding the words above for the simple `ValidatorAttribute` case would help.

**Comment by Rick-Anderson** [comment]
@serpent5  should we change the sample code from
`return new ValidationResult(GetErrorMessage());` to
```
return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));
```
and then add the following:

Custom validator errors can be returned by any of the following approaches:

* List of doug's approaches.

**Comment by sbsw** [comment]
How about the question of how to return a "default" error message in the case where the attribute declaration doesn't explicitly configure the error message? The way I currently do it (no clue if this is the "correct" way to do it, but it works) is to include some code in the validator's constructor, like this:

```
public sealed class MyValidatorAttribute : ValidationAttribute
{
    public MyValidatorAttribute()
    {
        // Default error message
        var defaultErrorMessage = "This is the error message";
        if (ErrorMessage == null && ErrorMessageResourceName == null) ErrorMessage = defaultErrorMsg;
    }

    protected override ValidationResult IsValid(object value, ValidationContext validationContext)
    {
        // <...>
    }
}
```

**Comment by serpent5** [comment]
@Rick-Anderson Sure, that seems like a good plan.

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky @fiyazbinhasan  @david-acker  this looks like an easy fun sample to write.

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson which location should be used for the sample?

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  per the top of the issue:

***EDIT by @Rick-Anderson***
Write a standalone sample at https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/models/validation/samples showing how to call `return new ValidationResult(FormatErrorMessage(validationContext.DisplayName));`

That's it. After that, open an issue to update this doc with the sample.

**Comment by IndigoHealth** [comment]
The sample code I posted (above) for initializing the default error message (in the constructor) uses hard-coded English language text. You get extra credit for showing how to localize the error message ;)
