### ISSUE TITLE
SignInManager incompatible with Blazor?

### ISSUE THREAD

**Issue by bdnts** [dotnet/AspNetCore.Docs#17401]
At the top of this documentation it implies that "using ASP.NET Core's Identity system" is a viable option.  The Identity scaffold generates Razor pages (.cshtml & .cs) but not Blazor pages (.razor, which is damn confusing, but a different topic).  However, in my testing, SignInManager will always throw an exception: "The response headers cannot be modified because the response has already started."  SignInManager is incompatible with Blazor's underlying SignalR technology.  The work-arounds are either API  call to the Server, or implementing JWT Identity Server.  
Is SignInManager incompatible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio#authentication)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@bdnts ... ASP.NET Core Identity is working under the covers in these scenarios. I'm working on these topics *right now* to improve them, so I'm glad you called out your confusion here.

In a *component*, use either or both ...

* `AuthenticationStateProvider`
* `AuthorizeView` component

... and *yes!* ... `SignInManger`/`UserManager` are incompatible. 

Leave this open. I'll make some updates to improve the guidance.

**Comment by guardrex** [comment]
btw @bdnts ... I threw up a quick example that mirrors the guidance in the topic over on https://github.com/dotnet/AspNetCore.Docs/issues/17402#issuecomment-602184048.

We're discussing something a different on that issue, but that comment shows the `AuthenticationStateProvider` and `AuthorizeView` component in use.

**Comment by bdnts** [comment]
Whew!  Thought I was going crazy cause it should work, but wasn't!  Thanks.

I created a project called BlazorIdentity (https://github.com/bdnts/BlazorIdentity) that documents the steps I took (readme.md), and the dead end I hit with SignInManager.  The project was a personal lab, but happy to share.  Blazor actions are on the Index page, while Asp.Net scaffolded pages are on the Header.
However, the problem with Blazor A&A is just the "last mile" of Authentication.   Authorization works great.  I'll break it down:

**Authentication**:
- I have a working Blazor Registration page available on the home page
![image](https://user-images.githubusercontent.com/56051634/77341638-41307d80-6cec-11ea-853f-f8b78d9b4558.png)
-You can also do the traditional asp.net registration from the header:
![image](https://user-images.githubusercontent.com/56051634/77341765-75a43980-6cec-11ea-95b9-23abf97bc649.png)
--I have a hard coded Blazor login with the Login button, using the default account "admin@example.com" "P@ssword1234".  This will trap the exception thrown by SignInManager.
![image](https://user-images.githubusercontent.com/56051634/77341989-c1ef7980-6cec-11ea-92aa-9172ccddc70c.png)

**Here is the interesting part**
--Use the Asp.Net Login in the header, with the admin account and login succeeds.
![image](https://user-images.githubusercontent.com/56051634/77342162-04b15180-6ced-11ea-9aeb-32bf9324e457.png)

**Authorization**
Once past the problem with SignInManager, Authorization works as documented.  
- AuthorizeView used in NavMenu.razor to enable the Administration menu items.
- AuthorizeView in Index.razor, depending on role, 3 different messages will appear.
- CascadingAuthenicationState in App.razor allows auth state to flow down to all pages.
- AuthenticationStateProvider will get the current user state within the app.  Click on the button
![image](https://user-images.githubusercontent.com/56051634/77343066-5dcdb500-6cee-11ea-9118-a550208fdb42.png) and the user plus authenticationstate will display.
--Cascading Auth State, Administration only authorizes Admin Roles to use.  Logout, access Administration directly, and error "42" pops up.
(Administration page from Michael Washington)

The only problem I couldn't overcome was SignInManager, which I now know cannot be overcome.  However, call the Asp.Net page, that SignInManager works, and then the rest of Blazor A&A works  as documented.  

I never got time to experiment with Claims, but I'm guessing they will work as advertised.  (Oops, said the same thing about SignInManager for Blazor.  lol) 

If I can be of further assistance, happy to oblige.

**Comment by guardrex** [comment]
Thanks @bdnts ... that just about mirrors the updates on the recent PRs, including the new one that seeks to make sure that the *Overview* coverage applies to both Blazor WebAssembly and Blazor Server apps. I checked most of the scenarios here this morning, and they all worked. :tada:

I also added a NOTE at the top calling out that `SignInManager` and `UserManager` aren't Razor component concepts.

**Comment by guardrex** [comment]
> AuthorizeView used in NavMenu.razor to enable the Administration menu items.

:heart: that one ... that's someting that I'll keep in mind as I continue to work these. It would make a nice example in the *Overview* topic.

**Comment by bdnts** [comment]
Cool.  Glad to be of help.
