### ISSUE TITLE
Not using npm

### ISSUE THREAD

**Issue by johnmackerras** [dotnet/AspNetCore.Docs#17403]
How do I get the javascript client if I don't have NPM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
This tutorial requires NPM

**Comment by BrennanConroy** [comment]
@Rick-Anderson That page is not a tutorial, and maybe we should consider showing other ways of obtaining the client without using npm.

Such as how this **tutorial** shows using libman with VS and VS Code: https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio#add-the-signalr-client-library

**Comment by scottaddie** [comment]
Another option that doesn't require LibMan is a CDN such as https://cdnjs.com/libraries/microsoft-signalr.
