### ISSUE TITLE
Error CS0029 - Blazor Component

### ISSUE THREAD

**Issue by jackptoke** [dotnet/AspNetCore.Docs#17416]
Hi,
I've received this error.

/Users/jackptoke/Coding/BlazorApps/TokeHRM.Server/TokeHRM.Server/Pages/EmployeeOverview.razor(46,46): Error CS0029: Cannot implicitly convert type 'Microsoft.AspNetCore.Components.ElementReference' to 'TokeHRM.Server.Components.AddEmployeeDialogBase' (CS0029) (TokeHRM.Server)

I can't figure out the issue.  I know that the issue at the last line of the Blazor component.  

```C#
<AddEmployeeDialog @ref="AddEmployeeDialog" ></AddEmployeeDialog>
```

### **Here is the Blazor Component.**

```C#
@page   "/employeeoverview"
@inherits EmployeeOverviewBase


<h1 class="page-title">All Employees</h1>
@if(Employees == null)
{
    <p><em>Loading ...</em></p>
}
else
{
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Employee Id</th>
                <th>First name</th>
                <th>Last name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var employee in Employees)
            {
                <tr>
                    <td><img src="@($"https://gillcleerenpluralsight.blob.core.windows.net/person/{employee.EmployeeId}-small.jpg")" class="rounded-circle" /></td>
                    <td>@employee.EmployeeId</td>
                    <td>@employee.FirstName</td>
                    <td>@employee.LastName</td>
                    <td>
                        <a href="@($"employeedetail/{employee.EmployeeId}")" class="btn btn-primary table-btn">
                            <i class="fas fa-info-circle"></i>Detail
                        </a>
                        <a href="@($"employeeedit/{employee.EmployeeId}")" class="btn btn-primary table-btn">
                            <i class="fas fa-edit"></i>Edit
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<button @onclick="@QuickAddEmployee" class="bn btn-dark table-btn quick-add-btn">&nbsp;&nbsp;+&nbsp;&nbsp;</button>
<AddEmployeeDialog @ref="AddEmployeeDialog" ></AddEmployeeDialog>

```
### **Then here is the it's base class.****

``` C#

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using TokeHRM.Server.Services;
using TokeHRM.Shared;
using System.Linq;
using TokeHRM.Server.Components;

namespace TokeHRM.Server.Pages
{
    public class EmployeeOverviewBase : ComponentBase
    {
        [Inject]
        public IEmployeeDataService EmployeeDataService { get; set; }

        protected AddEmployeeDialogBase AddEmployeeDialog { get; set; }

        protected override async Task OnInitializedAsync()
        {
            Employees = (await EmployeeDataService.GetAllEmployees()).ToList();
        }

        public IEnumerable<Employee> Employees { get; set; }

        protected void QuickAddEmployee()
        {
            AddEmployeeDialog.Show();
        }

        public async void AddEmployeeDialog_OnDialogClose()
        {
            Employees = (await EmployeeDataService.GetAllEmployees()).ToList();
            StateHasChanged();
        }
    }
}

```

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by husam-ebish** [comment]
It seems to set a reference to the **Components** namespace in the **_imports.razor** file. 

In `_Imports.razor` add: `@using "Components namespace"`

For example: if you created the `AddEmployeeDialogBase.cs` component in a folder names _Components_ under _TokeHRM.Server_ project, just add: `@using TokeHRM.Server.Components` in `_Imports.razor` .

**Comment by johnyjp** [comment]
And me, directly after an update to vs2022 17.6.   Checking VS issues list in case its MS issue.

**Comment by johnyjp** [comment]
Have loaded project in 1.7 and compiles ok.

Noticed when clicking on the errors in the error window as you click on the error it removes it from the errors window. But recompiling brings it back.   Will see if I can find the difference v17.5 v 17.6

**Comment by johnyjp** [comment]
Removing the @ref makes it compile.  eg
<AgentFullRecord @ref="agentForm" Agent="@selectedAgent" OnChanged="OnChanged" />

does not compile, but

<AgentFullRecord Agent="@selectedAgent" OnChanged="OnChanged" />
does

**Comment by johnyjp** [comment]
Dont think its Blazorise, but a VS issue. Cant find any reference to it on VS forums at the moment.

**Comment by johnyjp** [comment]
Also noted on devblog https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-6-now-available/#comment-28766

**Comment by tecxx** [comment]
> I get this error after upgrading from Visual Studio 17.5.5 to 17.6.0. Nothing was changed in code , just stopped working what is used to work

same here.

**Comment by Rick-Anderson** [comment]
> same here. please advice. please re-open issue.

See [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/17416#issuecomment-603551020) 
Create a new issue from the doc page and link to this issue.

**Comment by johnyjp** [comment]
Added at https://github.com/dotnet/docs/issues/35449  even though instructions say to add comments to the closed issue.
