### ISSUE TITLE
Wrong AuthenticationService reference in Index Page section

### ISSUE THREAD

**Issue by rdadkins** [dotnet/AspNetCore.Docs#17418]
The referenced authentication service is
```
&lt;script src="_content/Microsoft.Authentication.WebAssembly.Authentication/AuthenticationService.js"&gt;&lt;/script&gt;
```
when it should instead be:
```
&lt;script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"&gt;&lt;/script&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @rdadkins ... probably just another one of my *cut-'n-paste errors*. 🙈

I'll take a look and patch it up in a few minutes. I'm **_buried in Blazor authn/z code_** at the moment. ⛏
