### ISSUE TITLE
Callback method as a parameter.

### ISSUE THREAD

**Issue by bdnts** [dotnet/AspNetCore.Docs#17411]
Following on to mrlife's question, passing callback methods to components is perfectly legal in Blazor.  Is this supported when calling a component from a View?  The use case is a modal dialog with a Save and Cancel button.  When clicked, the corresponding callback method fires back in the Model.
&lt;component type="typeof(ZipCodeModal)" render-mode="Serverprerendered" param-Save="@Model.Save" param-Cancel="@Model.Cancel" /&gt; 
which, of course does not work.  
A) Is it possible to pass a method parameter?
B) If it is, what is the correct declarations and syntax?
TIA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That would be good feedback for the product unit. Open on the engineering repo :point_right: https://github.com/dotnet/aspnetcore/issues
