### ISSUE TITLE
Add an example of using a custom IValidateOptions<TOptions>

### ISSUE THREAD

**Issue by jeremyVignelles** [dotnet/AspNetCore.Docs#17413]
There is a sample about how to use `.ValidateDataAnnotations()`, but that does not explain how to create and register a custom `IValidateOptions<TOptions>`
Could you include such sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#options-validation)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu [this SO thread](https://stackoverflow.com/questions/57135724/how-to-validate-configuration-settings-using-ivalidateoptions-in-asp-net-core-2) show's two approaches. What should we document?

**Comment by Rick-Anderson** [comment]
Tracked in Options pattern master issue: Check here first #18291

**Comment by dougbu** [comment]
FYI I would strongly recommend documenting the addition of `IValidateOptions<TOptions>` implementation instances to DI. The other option I see adds fluent validation layers that are not germain to .NET Core without other extensions and additional complication.

**Comment by Rick-Anderson** [comment]
@serpent5  when you get a chance can you fix the code in https://github.com/Rick-Anderson/Validate ?
It's a copy/paste from [this SO post](https://stackoverflow.com/questions/57135724/how-to-validate-configuration-settings-using-ivalidateoptions-in-asp-net-core-2)

**Comment by serpent5** [comment]
Sure, will do.
