### ISSUE TITLE
[Remote] attribute is Client side Only?

### ISSUE THREAD

**Issue by JaySkyworker** [dotnet/AspNetCore.Docs#17439]
It doesn't seem to emphasize enough that out of all built-in attributes, that [Remote] attribute is client side Only?
also for purpose like checking duplicate (emails), [Remote] only verify when unfocused,
and does not verify when form submit , which can easily be invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#remote-attribute)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's pretty clear
The` [Remote]` attribute implements client-side validation
