### ISSUE TITLE
Is it possible to customize Authentication.razor ?

### ISSUE THREAD

**Issue by Blackleones** [dotnet/AspNetCore.Docs#17448]
Given a Blazor WebAssembly with IdentityServer 4 (project template)

I would like to know if it is possible to customize the behavior of `Authentication.razor` and accomplish the login/logout without leaving the Blazor Client context.

My goal is to replicate the [LoginDisplay.razor](https://github.com/SteveSandersonMS/presentation-2019-06-NDCOslo/blob/master/demos/MissionControl/MissionControl.Client/Shared/LoginDisplay.razor) of SteveSanderson's NDC presentation (2019-06). In this example, you can login and logout without leaving the Blazor client-side interface.

Is it possible to have an example of how to customize the Autentication.razor?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Blackleones ... I've marked this for triage. Management usually looks on Fridays.

**Comment by javiercn** [comment]
This is not possible with the default implementation we provide, since openid requires a redirect and we don't support popup login.
