### ISSUE TITLE
Code examples related to CORS are generally unrealistic

### ISSUE THREAD

**Issue by vasont** [dotnet/AspNetCore.Docs#17442]
In general, all CORS code examples have hard-coded domains which is unrealistic. Please put realistic code examples or references to github examples into documentation. Furthermore, real-world use the domains need to be derived from the host bindings. Why and how would one want to manage domain names in a configuration file (assumed that's your go-to example response) and a web server (IIS, Azure, etc) ... which requires manual and double-work (aka DevOps hell)... instead, write code to retrieve bindings from the host and add those dynamically to CORS allowed orgins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#set-the-allowed-origins)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
As you mentioned, it's not hard to get this information from config.
