### ISSUE TITLE
TimedHostedService

### ISSUE THREAD

**Issue by SourceStudio** [dotnet/AspNetCore.Docs#17450]
The TimedHostedService example appears to make use of the (legacy) System.Threading.Timer class, and therefore doesn't allow asynchronous code to be executed from within the callback, which essentially renders it useless for most scenarios.

Perhaps a more useful example would be one that simply relies on the BackgroundService, similar to the standard .NET Core Worker template. This is clearer, more concise, doesn't require any esoteric calls to the Timer object from within StopAsync(), and allows the CancellationToken to be passed to any underlying user code:

```
public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;
    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by TomRandles** [comment]
Thanks for posting this; I have spent the day implementing a background worker service based on the Timed background tasks example. I've just hit the same problem with the inability of the Timer class to implement an asynchronous callback function.

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
