### ISSUE TITLE
"Theme" button/menu missing at top of docs pages

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#17454]
![Screen Shot 2020-03-25 at 10 43 08 AM](https://user-images.githubusercontent.com/213164/77548905-8c31c880-6e85-11ea-821a-490a71d0e11e.png)

**Comment by scottaddie** [comment]
Thank you for reporting. I've notified the engineering team.

**Comment by scottaddie** [comment]
I've received confirmation from engineering that the selector has moved to the page footer.
