### ISSUE TITLE
AntiForgeryConfig.UniqueClaimTypeIdentifier in .net core nuget packages

### ISSUE THREAD

**Issue by redtaped** [dotnet/AspNetCore.Docs#17466]
System.Web.AntiForgeryConfig doesn't appear to exist in any .net core nuget packages. Is there a more appropriate solution for setting AntiForgeryConfig.UniqueClaimTypeIdentifier?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in *System.Web.WebPages.dll*
