### ISSUE TITLE
Add warning for not using Route Parameter named "page"

### ISSUE THREAD

**Issue by datvm** [dotnet/AspNetCore.Docs#17462]
I was so confused when I get 404 with a route like this:

`@page "/Extension/{cat?}/{page?}"`
(in a Razor Page)

It matches "/Extension/" and "/Extension/foo" but not "/Extension/foo/1".

Turned out `page` is used for the Page name. I didn't know this. Maybe add a warning about using the keywords as Route Parameter name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#host-matching-in-routes-with-requirehost)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc, `page` shouldn't be used as a route param.
