### ISSUE TITLE
option must not have c# in element attribute declaration area

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/AspNetCore.Docs#17461]
how to solve this question

**Comment by guardrex** [comment]
Hello @bouyeijiang ... It's best if you close this and re-open it from the topic that you're looking at. There's a This page feedback button+form at the bottom of every topic. When that form is used it automatically adds metadata to the issue and automatically pings the author of the topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
