### ISSUE TITLE
TPT Inheritance

### ISSUE THREAD

**Issue by mohebbisaeed** [dotnet/AspNetCore.Docs#17463]
I used your source to create an TPT inheritance, but the following error was created:
"The entity type 'Instructor' cannot be mapped to a table because it is derived from 'Person'. Only base entity types can be mapped to a table."

**Comment by guardrex** [comment]
Hello @mohebbisaeed ... It's best if you close this and re-open it from the topic that you're looking at. There's a **This page** feedback button+form at the bottom of every topic. When that form is used it automatically adds metadata to the issue and automatically pings the author of the topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
