### ISSUE TITLE
Backlinks in api reference to relevant documentation

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/AspNetCore.Docs#17467]
I often search for information on apis and how to best use them.
As a result of starting the search from the api starting point I usually end up on api reference pages. It would be really helpful if documentation (say asp.net core fundamentals) keeps a list of relevant types/namespace globs as metadata, this way highly relevant backlinks could be given on the (presumably autogenerated) api reference page without needing those to know anything about these hand written documentation pages.

As an example, say I want to know more about logging, I search for `ILogger` and I end up here still not quite sure how to use this api:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=dotnet-plat-ext-3.1

Beyond helpful would be to then see a direct link to:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1

**Comment by scottaddie** [comment]
Thank you for the suggestion. I've been in conversations with @davidfowl about solving this problem. See the following **Remarks** section for the `JsonSerializer` class: https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer?view=netcore-3.1#remarks. Is this what you had in mind?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
