### ISSUE TITLE
Replace old text for PartialView - View only when the word appears

### ISSUE THREAD

**Issue by JesperPetersenDk** [dotnet/AspNetCore.Docs#17468]
It is so that if I write something specific in my text on the page then I should have shown a form on the page when writing the simple word that I want it to be overwritten with.

The problem is right now that I can in no way make my PartialView appear.

I've looked at these here: https://stackoverflow.com/a/19208941

It causes problems when trying to just "run" as it is now and I get this error.

Microsoft.AspNetCore.Mvc.PartialViewResult

Code her:

return text.Replace("{{text}}", PartialView("ViewHelper/Email/EmailView").ToString());

i have C# 7.3 and .net core 2.1

**Comment by guardrex** [comment]
Hello @JesperPetersenDk ... Recommend that you close this and re-open it from the **This page** feedback button+form at the bottom of ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial

... Doing so will automatically add tracking metadata to your issue and automatically ping the author of the topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
