### ISSUE TITLE
Prerendering with Authentication

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#17470]
Content is here https://github.com/dotnet/aspnetcore/issues/15253#issuecomment-604581439

**Comment by guardrex** [comment]
@javiercn I must be slightly off on your guidance. Here's what **_almost_** works but throws ...

> InvalidOperationException: Cannot consume scoped service 'Microsoft.AspNetCore.Components.NavigationManager' from singleton 'Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationOptions`1[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions]]'.

## Support authentication with prerendering

After following the guidance in one of the hosted Blazor app topics, use the following instructions to create an app that:

* Prerenders paths for which authorization isn't required.
* Doesn't prerender paths for which authorization is required.

In the Client app's `Program.Main` (*Program.cs*), factor common service registrations into a separate method (for example, `ConfigureCommonServices`):

```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("app");

        ConfigureCommonServices(builder.Services);

        await builder.Build().RunAsync();
    }

    public static void ConfigureCommonServices(IServiceCollection services)
    {
        services.AddBaseAddressHttpClient();
        services.Add...;
    }
}
```

In the Server app's `Startup.ConfigureServices`, register the services required for the UI and the app to work:

```csharp
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Server;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;

public void ConfigureServices(IServiceCollection services)
{
    ...

    services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
    services.AddScoped<SignOutSessionStateManager>();

    Client.Program.ConfigureCommonServices(services);
}
```

In the Server app's `Startup.Configure` method, replace `endpoints.MapFallbackToFile("index.html")` with `endpoints.MapFallbackToPage("/_Host")`:

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
    endpoints.MapFallbackToPage("/_Host");
});
```

In the Server app, create a *Pages* folder if it doesn't exist. Create a *_Host.cshtml* page inside the Server app's *Pages* folder. Paste the contents from the Client app's *wwwroot/index.html* file into the *Pages/_Host.cshtml* file. Replace the `<app>Loading...</app>` tag with the following:

```cshtml
<app>
    @if (!Context.Request.Path.StartsWithSegments("/authentication"))
    {
        <component type="typeof(Wasm.Authentication.Client.App)" render-mode="Static" />
    }
    else
    {
        <text>Loading...</text>
    }
</app>
```
