### ISSUE TITLE
Unclear child to parent binding with chained bind language 

### ISSUE THREAD

**Issue by JonnyWaffles** [dotnet/AspNetCore.Docs#17479]
Hi friends,

This section child-to-parent-binding-with-chained-bind [https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind is rather confusing. First the example has a bad html tag, h1 opening and h2 closing. 

The third coding example does not even use the child component from the first section. What exactly is this trying to demonstrate? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> First the example has a bad html tag, h1 opening and h2 closing.

Thanks ... just a typo. I'll fix that up.

> The third coding example does not even use the child component from the first section. What exactly is this trying to demonstrate?

**_Yikes!_** ... that's supposed to be an **_alternate CHILD example_**. Idk how the heading and `@page` directive got on there.

*Wait* ...... I know what happened ............... 👽 ..... *yep* .... had to be. :smile: (*They are among us!* lol)

I'll fix it right now. Interesting how long that sat there without generating an issue. Thanks for calling these out.
