### ISSUE TITLE
Anyway for Intellisense to work for static resources in RCL?

### ISSUE THREAD

**Issue by shawnpaige** [dotnet/AspNetCore.Docs#17484]
Hello!

I have successfully added static files  (i.e. jQuery 3.4.1 and Bootstrap 4.4.1) to my .NET Core 3.1 Razor Class Library and am able to use the files in multiple projects (awesome).  However, there is no IntelliSense for the CSS/JavaScript items when I am working in the Razor pages of the web projects that reference the RCL (not so awesome).  The IntelliSense works as expected only for files located within the RCL.

Is there any way to get the CSS/JavaScript IntelliSense working on dependent projects without adding the the files directly to the project?  The whole idea of course is to not have to add/update them in the dependent projects.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by shawnpaige** [comment]
I found information on a workaround for JavaScript files here:

https://stackoverflow.com/questions/59909704/js-css-intellisense-between-projects-in-vs-2019

I am still having an issue with how to reference CSS via IntelliSense (especially Bootstrap) that only resides in the RCL.

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Create reusable UI using the RCL project #16639

**Comment by MackinnonBuck** [comment]
This doesn't appear to be a scenario we currently support, so there isn't anything to document here. We have issues tracking improvements to this area.
