### ISSUE TITLE
[3.2] Document Blazor + IdentityServer deployment to Azure AppService

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#17483]
[EDIT by guardrex to add the metadata]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Javier covered this already: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production

**Comment by danroth27** [comment]
I'm reopening this as I think we need to somehow surface this content as part of the Blazor docs as well. Currently this content is in the SPA docs. Maybe we could cross-link to this section from https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?

Also, the current content doesn't mention using Azure Key Vault at all for setting up the signing certificate. I think we want that as a first-class scenario. I've added some content on using Blazor + IdentityServer + Key Vault to the Blazor Workshop that shows how to do this that we could reuse: https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/10-publish-and-deploy.md.

We've also seen some feedback from customers that they need additional instructions on how to setup the signing key on App Service for Linux: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/#comment-1842. @javiercn Do you know what additional steps are required?

**Comment by danroth27** [comment]
Related https://github.com/dotnet/aspnetcore/issues/20700

**Comment by javiercn** [comment]
I've unassigned myself here since I already provided the contents.
