### ISSUE TITLE
Concurreny problem in best-practice-edit-requst: ArgumentNullException 

### ISSUE THREAD

**Issue by ghefarm** [dotnet/AspNetCore.Docs#17495]
Hello, 
you need to optimize your code/documentation about best practice in case of edit-request (because a best practice should be perfect!):
```
 Student studentToUpdate = await _context.Students.FirstOrDefaultAsync(s => s.ID == id);
            if (await TryUpdateModelAsync<Student>(...) 
```
A second user may have deleted the entity under update before the first user clicks on "save". And as the method TryUpdateModelAsync doesn't accept NULL (entity deleted), the first user will get the following error (i tested it :)):

> An unhandled exception occurred while processing the request.
> ArgumentNullException: Value cannot be null. (Parameter 'model')
> 
> Microsoft.AspNetCore.Mvc.ControllerBase.TryUpdateModelAsync<TModel>(TModel model, string prefix, Expression<Func<TModel, object>>[] includeExpressions)

**One simple change would be calling the method inside the try-catch and not outside/before it.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-3.0#update-the-edit-page)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency?view=aspnetcore-3.0
