### ISSUE TITLE
Anchors for .NET Generic Host all have a -1 suffix

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#17491]
I'm in the process of updating the Fundamentals Overview (#13877), where I'm looking at updating some of the links that currently target the Web Host topic to target this topic. I noticed that the anchors in this topic all have a -1 suffix, which doesn't seem right. It also means that some of the internal links in this topic don't work. For example, in the [IHostEnvironment](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#ihostenvironment-1) section, 4 out of the 5 links are internal links, and they're all broken. I've checked a couple of other topics, which seem fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The `-1` suffix from from repeating  the same `## H2's` with the monikered versions. Because of duplicate H2's, one bookmark stays as predicted, and the other has The `-1` suffix 
I believe the first version of the H2 stays as predicted, and the 2nd has The `-1` suffix  appended. That's why I always put the new version on top.

I'm surprised we haven't had any complaints on broken links.

I'm not sure if file versioning will fix that problem. CC @scottaddie

**Comment by serpent5** [comment]
Right, I see. There's a >= 5.0 version of this topic, so that gets e.g. `#webroot`, the >=3.0 version gets e.g. `#webroot-1`, and the < 3.0 version gets e.g. `#webroot-2`.

So once a new version gets added, it breaks all existing links to anchors. That could be a problem, right? For example, in [Content root in 2.1 Fundamentals Overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.1&tabs=windows#content-root-1), click the "Web root" link, which is now dead. It's looking for `#web-root`, but it's `#web-root-1` since there's a 3.0 version of the topic. It's the same for the "building the host" link.

**Comment by Rick-Anderson** [comment]
@serpent5  that's correct. A short term help is to move the 5.0 version at the end of the file, so most folks won't hit the problem.

The reason we've had zero reports on this is almost everyone is reading the default (current) version.

cc @scottaddie  @guardrex  @wadepickett
