### ISSUE TITLE
Scaffold settings ignore Layout if left blank

### ISSUE THREAD

**Issue by CGrijalva90** [dotnet/AspNetCore.Docs#17498]
The scaffold settings indicate to leave the layout section blank if I want to use layout that's found in `_viewstart`, however, once the scaffold is executed the generated pages are created with a `null` layout:

```cshtml
@page
@model RazorPagesMovie.Pages.Movies.IndexModel

@{
    Layout = null;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Follow the instructions and you get the right layout.

**Comment by heitorgiacominibrasil** [comment]
Try to scaffold via command line add -udl attribute
