### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by FrankSzendzielarz** [dotnet/AspNetCore.Docs#17519]
Is it just me or is reading this page like wading through blancmange with lead boots? For example, the phrase "IAuthorizationRequirement is a marker" … why is that there? And why wasn't the reference to that class in the preceding code highlighted? For me, this is very dense and confusing documentation. In retrospect when I understand the concepts it might seem clear, but for newcomers this seems to me almost unreadable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Policy-based authorization #16191
