### ISSUE TITLE
HTTP 500 thrown on a POST with the code from this document

### ISSUE THREAD

**Issue by johnathan-s** [dotnet/AspNetCore.Docs#17518]
Hello,

Following the documentation (.net core 3.1 and mongodb 4.2.1) the GET is fine but the POST throws a 500.
Repro Steps:
Have a few documents in the mongodb collection.
In postman, perform a GET (all is fine).
Perform a POST to the web service (the create method will pick it up).
Results:  
The document IS posted to the mongodb collection.
However, the service gives a 500 "System.InvalidOperationException: No route matches the supplied values."

There is a thread on this in github but the thread is closed.
Is this a bug or is there something missing in this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
I think starting .NET Core 3, the default Web API template uses this:
```
app.UseEndpoints(endpoints =>
{
       endpoints.MapControllers();
});
```
which 
> Adds endpoints for controller actions to the Microsoft.AspNetCore.Routing.IEndpointRouteBuilder without specifying any routes.

You can try changing that to
`endpoints.MapDefaultControllerRoute();`

which 
> Adds endpoints for controller actions to the Microsoft.AspNetCore.Routing.IEndpointRouteBuilder **and adds the default route {controller=Home}/{action=Index}/{id?}.**

**Comment by johnathan-s** [comment]
Hello Pratik,

I tried the suggestion.
There was no change in behavior.
Any ideas?

- Johnathan

**Comment by prkhandelwal** [comment]
@johnathan-s That's strange... Lemme try replicate that!

**Comment by prkhandelwal** [comment]
Hi @johnathan-s , I tried creating the project from scratch using ASP.NET Core 3.1 Web API template & I'm unable to replicate the issue. Can you provide more details about your solution?

**Comment by johnathan-s** [comment]
Thanks Pratik,
Found it.
In the Create method of the Controller, there was a mistyped char in "GetBook" (Getbook)
return CreatedAtRoute("GetBook", new { id = book.Id.ToString() }, book);
Thanks for your patience.
Please close this one.

**Comment by Rick-Anderson** [comment]
Moved to Master list: Create a web API and MongoDB #16196

**Comment by johnathan-s** [comment]
Thank you Rick.
Stay well.
