### ISSUE TITLE
Localization for Blazor-Wasm

### ISSUE THREAD

**Issue by pranavkm** [dotnet/AspNetCore.Docs#17512]
* By default, .NET WebAssembly sets the culture using the user's language preference. See https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages
* Application developers can optionally configure the application culture by setting `CultureInfo.DefaultThreadCurrentCulture` \ `CultureInfo.DefaultThreadCurrentUICulture` as part of their `Program.MainAsync`.
* To minimize network costs, only satellite assemblies for the selected culture are downloaded.
* Sample app with culture picker: https://github.com/pranavkm/LocSample

**Comment by pranavkm** [comment]
cc @guardrex

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/17513.
