### ISSUE TITLE
Installation of a global tool required as well

### ISSUE THREAD

**Issue by Leon99** [dotnet/AspNetCore.Docs#17514]
`dotnet sql-cache ` requires installing dotnet-sql-cache, of which it notifies, but the command line it recommends is incorrect - `dotnet tool install --global dotnet-sql-cache` doesn't work and suggests a number of reasons for that. I was able to install it by specifying the version explicitly, but it would be better to mention the requirement to install the tool right here, as well as the link to its NuGet page, which contains a correct command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-sql-server-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Distributed caching master page #17553

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
