### ISSUE TITLE
Blazor AAD B2C additional user flows

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#17522]
From @Alienroid ...

> I am not sure where to ask this. So Blazor WebAssembly with Hosted AAD B2C authentication is working. However, there’s no documentation or sample code on how to add an userflow.
>
> The examples from blazor server side only configures in startup.cs and it gets configuration from AppSettings.json. That’s the same as Blazor WebAssembly with Hosted (on the server side). However, the client side, we only have program.cs that configures ‘authentication’ so we can use authentication/login in LoginDisplay. However, no idea how we can do that for other userflow. I am not sure if AAD B2C for Blazor WebAssembly is completed or just lack of documentation? Is there some way we can subscribe to the status of the project? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good point @Alienroid ... We do need coverage on those scenarios (reset password and edit profile). I suspect we'll end up linking off to Azure docs for details on setting up the userflow on the Azure portal side.

* https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
* https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows

Presumably, the Blazor app makes an auth request with the userflow policy ID (similar to their *Run user flow*/*Run now* links from their portal examples). I'll need to look into that a bit further. Engineering might have baked something into the auth lib to make it easy.

**Comment by guardrex** [comment]
After starting to look a little closer, it looks more like this scenario is going to be handled by an MVC controller. The component hits up the controller endpoint, and the controller takes care of triggering the flow. I'll try to get to this issue next week and see what's what, but that concept seems likely based on how Identity flows for components are generally customized in Blazor Server apps.

**Comment by Alienroid** [comment]
Hi Luke,

I think this ask is regarding blazor WASM how to connect to aadb2c edit profile. If the user flow for signup isn't going through mvc controller, why should edit profile going through this route?

I know I've asked on both server side and wasm... I get confused on my asks too :)

On the side note, I rewrote/port most of the areas/identity to blazor based and no longer razor pages. (With exceptions on login, which requires cookie update that cannot be edited from browser ).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
Sorry ... you're right ... my :eye: must have hit the "Blazor Server" wording at the start of the 2nd paragraph. I'll remove the comment and change the title of this issue.

**Comment by guardrex** [comment]
Actually, I won't change the title. User flows aren't covered for Blazor Server either. I have that issue for working on scaffolding and Identity concepts in Blazor Server, but I think AAD B2C user flows will be a separate issue from that one. I'll probably try to work both WASM and Server sides off of this issue.

**Comment by Alienroid** [comment]
Thanks Luke.

I look forward to getting aadb2c works so I can migrate all my clients to it 😉

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by javiercn** [comment]
For server-side blazor other userflows should be supported out of the box (the default ones). For blazor webassembly, msal.js doesn't support them, so it is up to the developer to implement them.

**Comment by Alienroid** [comment]
Thanks Javier. For blazor wasm, is this feature on the roadmap or MSFT just leave it to us? Any particular reason not supported by msal.Js?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
If the packages are added, is `GetOwinContext` a viable approach for Blazor WASM? For example ...

```csharp
public void ResetPassword()
{
        HttpContext.GetOwinContext().Authentication.Challenge(
            new AuthenticationProperties() { RedirectUri = "/" }, "{PW RESET POLICY ID}");
}
```
https://github.com/AzureADQuickStarts/B2C-WebApp-OpenIDConnect-DotNet-SUSI/blob/complete/WebApp-B2C-DotNet/Controllers/AccountController.cs#L32-L33

... or is it really going to be a manual effort to build the challenges (or use a community package of some sort)?

**Comment by guardrex** [comment]
Given how clear their doc is on forming the challenge, I'll just cross-link their doc in a new section of the two AAD B2C topics. For example, the following works ...

```
https://XXXXX.b2clogin.com/XXXXX.onmicrosoft.com/oauth2/v2.0/authorize?
client_id=11111111-1111-1111-1111-111111111111
&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fauthentication%2Flogin-callback
&response_mode=form_post
&response_type=id_token
&scope=openid
&nonce=10636b65-924d-4456-8c58-3610ddf473e9
&state=12345
&p=B2C_1_passwordreset1
```

**Comment by guardrex** [comment]
@Alienroid Hack'in around with bits and probably creating some 🙈 **_giant security holes_** 🙈  ...

* Registered a callback in the portal for a password reset: `https://localhost:5001/passwordreset-callback`
* Have a basic password reset user flow: `B2C_1_passwordreset1`
* In `LoginDisplay`, I hack up a challenge ...

  ```razor
  <button class="nav-link btn btn-link" @onclick="ResetPassword">Reset password</button>

  ...

  private void ResetPassword(MouseEventArgs args)
  {
      Navigation.NavigateTo("https://XXXXX.b2clogin.com/XXXXX.onmicrosoft.com/oauth2/v2.0/authorize?" +
          "client_id=11111111-1111-1111-1111-111111111111" +
          "&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fpasswordreset-callback" +
          "&response_mode=query" +
          "&response_type=id_token" +
          "&scope=openid" +
          $"&nonce={Guid.NewGuid()}" +
          "&state=12345" +
          "&p=B2C_1_passwordreset1");
  }
  ```

* A component to handle the callback (*PasswordReset.razor*) ...

  ```razor
  @page "/passwordreset-callback"
  @inject NavigationManager Navigation

  <p>@_errorMessage</p>
  <p>@_errorDescription</p>

  @code {
      private string _errorMessage;
      private string _errorDescription;

      protected override void OnInitialized()
      {
          var state = QueryStringHelper.GetParameter(new Uri(Navigation.Uri).Query, "state");

          if (state == "12345")
          {
              _errorMessage = $"Error: {QueryStringHelper.GetParameter(new Uri(Navigation.Uri).Query, "error")}";

              if (_errorMessage == "")
              {
                  Navigation.NavigateTo("/");
              }

              _errorDescription = $"Description: {QueryStringHelper.GetParameter(new Uri(Navigation.Uri).Query, "error_description")}";
          }
      }
  }
  ```

* I used the `QueryStringHelper` from the repo at https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/QueryStringHelper.cs.

... and those 😵 **_RexHacks!_**:tm: 😵 seem to work.

Since it all basically ✨ **_Just Works!_**:tm: ✨, I think the new tiny section in each doc can just throw the reader over to the Azure doc for how to build the challenge. If I get feedback that devs are having trouble later, then perhaps we can have some example code along these lines for this scenario.

**Comment by Alienroid** [comment]
Thanks for the sample Luke, I got the reset user flow to work!

If I do blazor server side, AADB2C only needs to define one application (in Azure portal) and I can use multiple user flows using the same one. The redirect path is the same for /signin-oidc.

On Blazor WASM, I have to define one app for each user flow (SignInSignOut, ResetPassword, etc) because they have different redirect?

Thanks again.

**Comment by guardrex** [comment]
> On Blazor WASM, I have to define one app for each user flow (SignInSignOut, ResetPassword, etc) because they have different redirect?

AFAICT, there would be:

* One app.
* One app registration in the portal with however many callback paths the app needs.
* However many user flows are needed, which can be reused across different apps.

**Comment by Alienroid** [comment]
Omg, I can’t believe I sent that out after I validated it. I really shouldn’t stayed up until 5. Brain turned off.

Thanks again 😉

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
