### ISSUE TITLE
Signature mismatch

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17528]
@lilymaybenichou commented on [Sat Mar 28 2020](https://github.com/dotnet/AspNetCore.Docs.fr-fr/issues/243)

In the last code sample I think this 
```
public async Task<ActionResult<TodoItem>> CreateTodoItem(TodoItemDTO todoItemDTO)
// should become
public async Task<ActionResult<TodoItemDTO>> CreateTodoItem(TodoItemDTO todoItemDTO)
```

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Didacticiel : créer une API Web avec ASP.NET Core](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sat Mar 28 2020](https://github.com/dotnet/AspNetCore.Docs.fr-fr/issues/243#issuecomment-605472782)

Hello, @lilymaybenichou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
cc @serpent5
