### ISSUE TITLE
Needs to state the type of authorization being used

### ISSUE THREAD

**Issue by philipstratford** [dotnet/AspNetCore.Docs#17520]
This tutorial details how to create a web app using the new Policy-based authorization. Since I'm new to .NET Core I followed it along thinking this was how authorization is done now, only to discover later that Role-based authentication is still very much a thing. Near the top this article needs to state "This tutorial shows you how to create a web app using Policy-based authorization but there are other types of authorization which you could use. See &lt;blah blah&gt; for more information."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is the only tutorial we have for authorization and it gets into the policy approach pretty quickly.

**Comment by philipstratford** [comment]
> This is the only tutorial we have for authorization and it gets into the policy approach pretty quickly.

Agreed, but it wasn't clear, at least to me, that this tutorial was specifically going to use the policy approach and, given that I'm still picking up Core and coming from a .NET Framework background, I followed it with the presumption (which I accept was a failing on my part) that this technique in .NET Core superseded Roles-based Authentication, not realising that the older pattern was still also viable. A short sentence near the start could have cleared that up.
