### ISSUE TITLE
Info about the recommendation of a package not developed by Microsoft

### ISSUE THREAD

**Issue by kmute90** [dotnet/AspNetCore.Docs#17523]
If someone wants to just add a Redis cache to their project from Nuget they find two packages:
- Microsoft.Extensions.Caching.StackExchangeRedis
- Microsoft.Extensions.Caching.Redis

It's clear to me now, that &gt;2.1 the recommendation is to use the package developed by StackExcange, however if someone just arrives to this page has no info about WHY to use that one. Maybe a note would be nice to point to the fact that there are two separate imlementations of Redis caching and which one to use.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Distributed caching master page #17553
