### ISSUE TITLE
Yahoo

### ISSUE THREAD

**Issue by dsiddananja** [dotnet/AspNetCore.Docs#17530]
There are specific instructions on using Yahoo external login provider!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f869636-630e-2542-b029-199154ef70c3
* Version Independent ID: cea7e5a6-383f-aeb5-2476-7c7d0a8bb851
* Content: [External OAuth authentication providers](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/social/other-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/other-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dsiddananja  sorry about that. And we don't have the resources to add that either.
