### ISSUE TITLE
Excluding static assets hide them from Visual Studio Solution explorer

### ISSUE THREAD

**Issue by metoule** [dotnet/AspNetCore.Docs#17539]
Excluding static assets by adding them to the `<DefaultItemExcludes>` hide them from the Visual Studio Solution explorer. This is a bit annoying, because I can't access them from VS anymore (or I have to update the `.csproj` beforehand).

Is there a reason why the way to exclude static assets from a RCL is different than from another ASP.NET Core project? For example, why can't I use this:

```
<ItemGroup>
  <Content Update="wwwroot\lib.css" CopyToPublishDirectory="Never" />
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#create-an-rcl-with-static-assets)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
RCL's don't support that approach.

**Comment by metoule** [comment]
I would have liked more info, but OK..

What about the fact that excluding items with the recommended way also hide them from the VS Solution Explorer? Is there a way to show them?

**Comment by Rick-Anderson** [comment]
> What about the fact that excluding items with the recommended way also hide them from the VS Solution Explorer? Is there a way to show them?

I'll check with the PU

**Comment by Rick-Anderson** [comment]
See Master issue: Create reusable UI using the RCL project #16639
