### ISSUE TITLE
Render a component inside a partial view

### ISSUE THREAD

**Issue by wocar** [dotnet/AspNetCore.Docs#17531]
I have `Index.cshtml` that Invokes a partial view called `_details.cshtml`
Within that partial view I'm trying to invoke `Details.razon` Razor component like this:

    @(await Html.RenderComponentAsync<Details>(RenderMode.Server))

Events don't get fired but content does get rendered.
If I use

    @(await Html.RenderComponentAsync<Details>(RenderMode.Server))

The content doesn't even get rendered. On the other side, if I use either of the above in the `Index.cshtml` the component works perfectly. 

Here is the Details component code

```
@using System.Net.Http
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.JSInterop

<h3>Event Binding</h3> <br /> <br />
<button @onclick=@ButtonClicked>Event Binding Example</button>  <br /> <br />
<button @onclick=@(() => Message = "Inline:Button Clicked")>Inline Event Binding</button> <br /> <br />
<p>Message: @Message</p>

@functions {
    private string Message { get; set; } = "";
    void ButtonClicked()
    {
        Message = "Button Clicked";
    }
}
```
Any clues? Is this scenario supported? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#render-components-from-a-page-or-view)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wocar ... Open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... but fix one thing ... you listed the same `RenderComponentAsync` code example twice.

**Comment by wocar** [comment]
Done. Thank you.

https://github.com/dotnet/aspnetcore/issues/20332

**Comment by guardrex** [comment]
Cool ... if they come back with something that only requires documentation, then I'll re-open this issue and get it covered.

**Comment by quocduong** [comment]
Hi @wocar  @guardrex ,

How you guys resolve the problem? If possible, please share your solution to me?

Many thanks.
