### ISSUE TITLE
Exception: DNS resolution failed

### ISSUE THREAD

**Issue by dirkbaum** [dotnet/AspNetCore.Docs#17533]
I've built the server and client according to the directions.  It worked fine.  I then built another set using .Net Core 3.0 (rather than 3.1 I had used in the successful server/client).  The Grpc.net.client package requires .Net 3.1 so I used the Grpc package.  This compiles, but when run I get this result:  Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="DNS resolution failed").  I get this result using both localhost and an explicit IP address.  I need to support .net core 3.0/standardlib 3.0 at the present.  Any ideas on a way forward?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by JACKCHEN96** [comment]
Hi, how did you fix this bug then?

**Comment by JamesNK** [comment]
Sounds like a networking issue. I don't have any specific advice other than to search for that error but in the context of HttpClient.
