### ISSUE TITLE
Attempting the RazorPagesMovie tutorial

### ISSUE THREAD

**Issue by BartHNL** [dotnet/AspNetCore.Docs#17538]
Hello,
On this page, 
https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1
I have built the RazorPagesMovie Project, but the Project contents are different from the displayed image:
https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/razor-pages-start/_static/se2.2.png?view=aspnetcore-3.1
I don't see the Pages folder
I have this Project Explorer contents:
http://nedcom.nl/Projects/RazorPagesMovie/RazorPagesMovie_SolutionExplorer.jpg
Do I have a wrong project type or is something else at hand?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Start over, you created the wrong project.

**Comment by KeithDoran** [comment]
I had the same problem and fixed it by updating Visual Studio 2019 (see Help -> Check for Updates)

**Comment by Rick-Anderson** [comment]
@KeithDoran  good tip, thanks for posting.
