### ISSUE TITLE
Live Reloading

### ISSUE THREAD

**Issue by CGrijalva90** [dotnet/AspNetCore.Docs#17541]
Is Live Reloading supported for Visual Studio for Mac and .NET Core 3.1? I've been trying to see updated changes rendered on my browser after saving a file but nothing happens and I'm forced to restart my server. I've already cleared my cache on my browser and tried both starting the application with and without debugging. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's only supported on IIS Express on Windows.
