### ISSUE TITLE
Globbing not working with `PhysicalFileProvider`

### ISSUE THREAD

**Issue by ydogus** [dotnet/AspNetCore.Docs#17547]
As title says, globbing is not working with `PhysicalFileProvider`. This was already reported in related GitHub repository but got rejected: https://github.com/dotnet/extensions/issues/486.

I'm opening the issue here because the documentation says the opposite (even if the doc is generic but not only for `PhysicalFileProvider`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-3.1#glob-patterns)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ydogus  thanks for pointing this out.
