### ISSUE TITLE
No RP tile

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17555]
On https://docs.microsoft.com/en-us/aspnet/core/

Why is Blazor featured over RP (Razor Pages)?

![image](https://user-images.githubusercontent.com/3605364/78085204-ff3fb100-7355-11ea-9217-05690e3cf15d.png)

CC @wadepickett  @scottaddie

**Comment by Rick-Anderson** [comment]
We should change this to RP as it's currently getting more traffic. Unless the PU specifically asked for Blazor 
Blazor is featured in the first box below.

cc @scottaddie

**Comment by wadepickett** [comment]
@Rick-Anderson, I thought we had some feedback at one point from PM, Dan that we were to go with Blazor getting started as an entry point.   Happy to set it to Razor Pages if that was what it should have been instead.

I assume then I should point to this from the First UI card:
[Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio)

( The 5min get started with Razor seems way too minimal, and the we have another get started option for Razor but is a bit advanced in comparison. )

**Comment by wadepickett** [comment]
@danroth27, point to Blazor or Razor Pages for a "Create your first web UI" link on the ASP.NET Core hub page?  Which do you want for the definitive starting point for developers new to ASP.NET Core web UI?

[See the ASP.NET Core Hub page](https://docs.microsoft.com/en-us/aspnet/core/)  and note the _Create your first web UI_ card in the featured area at the top.

**Comment by danroth27** [comment]
> Point to Blazor or Razor Pages for a "Create your first web UI" link on the ASP.NET Core hub page? Which do you want for the definitive starting point for developers new to ASP.NET Core web UI?

Razor Pages.
