### ISSUE TITLE
Clean up Enable secret storage

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17557]
`dotnet user-secrets init` is missing and the VS version is hidden in a TIP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows#enable-secret-storage)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
The `dotnet user-secrets init` command becomes visible when selecting 3.0 or later. The command was added in the 3.0 SDK. See https://docs.microsoft.com/aspnet/core/security/app-secrets?view=aspnetcore-3.0&tabs=windows#enable-secret-storage.

**Comment by Rick-Anderson** [comment]
The entire doc is `::: moniker ` train wreck. In the next update we need to make 3 version and get rid of all the 1.0 stuff.

It shouldn't say
The Secret Manager tool includes an init command in .NET Core SDK 3.0.100 or later.

The 3.x version should just show the init command.
