### ISSUE TITLE
Hub page incorrectly points here

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17554]
https://docs.microsoft.com/en-us/aspnet/core/

![image](https://user-images.githubusercontent.com/3605364/78085071-92c4b200-7355-11ea-8919-202aa7c44248.png)

It should point to the first page, not this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e3baf6-6cba-aee0-9a8d-1e1fced2b690
* Version Independent ID: 74b76258-36a3-17de-6648-292da0a9e400
* Content: [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by 404Prachi** [comment]
hi How to add sitemap in mvc core asp.net
