### ISSUE TITLE
Running tests on published code.

### ISSUE THREAD

**Issue by gklittlejohn** [dotnet/AspNetCore.Docs#17564]
Can you give guidance on running tests on how to run tests on ASP.NET Core projects for published output? There is some guidance here [here](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-published-output) but this doesn't seem to work for projects that use a WebApplicationFactory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
