### ISSUE TITLE
the type or namespace 'DataTypeAttribute' could not be found

### ISSUE THREAD

**Issue by axfreeman** [dotnet/AspNetCore.Docs#17575]
The line '[DataType(DataType.Date)]' gave a syntax error 'the type or namespace 'DataTypeAttribute' could not be found'.

Fixed this by adding explicitly the line 'using System.ComponentModel.DataAnnotations;'

Don't know if that was the best workaround or why the error arose. Looks like a problem with the template to me, but I'm not an expert ASP or C# user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's in the article.
