### ISSUE TITLE
How does Blazor Server Circuits handle threads for multiple requests?

### ISSUE THREAD

**Issue by timahrentlov** [dotnet/AspNetCore.Docs#17570]
Hi,

I’m trying to understand how threading is handled in Blazor Server. Is the circuit executing code using multiple threads? Is repeated signalR requests to the same Page executed using the same single thread for all requests?  What is guaranteed? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @timahrentlov ... This question/scenario is under related discussion ... see ...

https://github.com/dotnet/AspNetCore.Docs/issues/17371#issuecomment-602683104

Let's use that existing issue to address it. You can comment over there if you have questions or remarks.
