### ISSUE TITLE
How to implement this in an app

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17585]
Hi team,
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.it-it/issues/46

@aleBiagini commented 6 hours ago — with docs.microsoft.com
Hello,
It's not very clear how to implement the authentication cookie into an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@aleBiagini  this is an advanced topic for those who don't want to use Identity. Most folks use Identity and don't need this topic.

**Comment by aleBiagini** [comment]
Well the point is that. I don't want to use Identity. Yet I've found this topic lacking in clarity. For example: where do I insert the cookie? I do not suggest that you should explain auth cookies in the article, but some more links to get the full picture would be great.
