### ISSUE TITLE
Client Secret in AddOidcAuthentication

### ISSUE THREAD

**Issue by ferguson-eric** [dotnet/AspNetCore.Docs#17580]
How do we pass the client secret with the AddOidcAuthentication extension method? The client secret is required for 'authorization_code'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ferguson-eric ... Ask the product unit. Open an issue for engineering at ...

https://github.com/dotnet/aspnetcore/issues

Please add a ...

cc: @guardrex 

... to the end of your opening comment so that I can see what they say.
