### ISSUE TITLE
app-state example for 3.x doesn't work.

### ISSUE THREAD

**Issue by woody1329** [dotnet/AspNetCore.Docs#17586]
The example here: AspNetCore.Docs-master\aspnetcore\fundamentals\app-state\samples\3.x\SessionSample
Just displays "verified true"
In contrast the example here: AspNetCore.Docs-master\aspnetcore\fundamentals\app-state\3.0samples\RazorPagesContacts
works as expected.

**Comment by Rick-Anderson** [comment]
They just don't have the same output. Next time create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by woody1329** [comment]
They don't have the same output, that is correct. However the relevant app-state example's output is not the output coded into the cshtml files, and even adding new pages, it doesn't output those correctly. Just get the verified line every time.
