### ISSUE TITLE
Where is CookiePolicyOptions.HandleSameSiteCookieCompatibility() ?

### ISSUE THREAD

**Issue by jitterbox** [dotnet/AspNetCore.Docs#17588]
There is published sample code in the Microsoft.Identity.Web repo that references a new method in the CookiePolicyOptions class called HandleSameSiteCookieCompatibility(). In the comment directly above it, there is a link back to this page.

I know they're working on a NuGet package for the new Microsoft.Identity.Web, and until they do so I assume(?) that method is not available. What important thing does it do beyond what is done above it in the sample code:
      options.CheckConsentNeeded = context =&gt; true;
      options.MinimumSameSitePolicy = SameSiteMode.Unspecified;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1945dedd-e2b8-37c1-2676-e473498bcb30
* Version Independent ID: 631281cb-65db-3196-1a6a-da9b3f2e3fed
* Content: [Work with SameSite cookies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/samesite.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/samesite.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Open an issue in that repo. 
I see `HandleSameSiteCookieCompatibility` at https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/CookiePolicyOptionsExtensions.cs too
