### ISSUE TITLE
WebsSoeckets: Update to 3.1

### ISSUE THREAD

**Issue by woody1329** [dotnet/AspNetCore.Docs#17587]
I'm looking at the ASP.NET Core 3.1 Docs, and I'm directed to examples which are for V2.2. This is unhelpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/78299072-9419ea00-74cf-11ea-84dc-2a1603ccee7d.png)

**Comment by Rick-Anderson** [comment]
@woody1329  I don't see any 2.2 specific code.

**Comment by woody1329** [comment]
The line that says targeted framework is 2.2 is at the very least.
