### ISSUE TITLE
More information around IJSInProcessRuntime and synchronous calling

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/AspNetCore.Docs#17595]
It would be helpful to have some more information around when to use synchronous or asynchronous calls to Javascript when doing client side Blazor. I have noticed that the synchronous calls are much faster than the asynchronous calls and make much more sense when the calling code is already on the UI thread as presumably there's a lot of marshalling going on. In fact I've converted all my calls to synchronous as pretty much all are for UI related reasons and my application is now much snappier. 
It would also be helpful to know whether calling synchronously will work from a non UI thread, I'm guessing not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by xxCruciblexx** [comment]
Would be nice if it mentioned Blazor server doesn't support synchronous JavaScript calls as well.

**Comment by guardrex** [comment]
We have coverage on this in the *Performance* topic. What's missing is a cross-link from the JS *Overview* to that coverage. I'll take care of that. Thanks for the issue here.

**Comment by LaughingJohn** [comment]
Thank you @guardrex!
