### ISSUE TITLE
User.Identity.Name empty when implementing Azure B2C in Blazor WebAssembly

### ISSUE THREAD

**Issue by IIStevowII** [dotnet/AspNetCore.Docs#17594]
This issue is about the following doc page:
[Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)

## Description
When trying to access *HttpContext.User.Identity.Name* in the Server project inside an API that is protected by the [Authorize] attribute, the name will appear empty. This while I am logged in at the name is shown in the Client application just fine.

## Fix
I had to add the following snippet in Startup.cs to fix this.

```C#
services.AddAuthentication(AzureADB2CDefaults.JwtBearerAuthenticationScheme)
		.AddAzureADB2CBearer(options => Configuration.Bind("AzureAd", options));

services.Configure<JwtBearerOptions>(AzureADB2CDefaults.JwtBearerAuthenticationScheme, options =>
{
	options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters()
	{
		NameClaimType = "name"
	};
});
```

I am not sure if this is the right place to report it, not even sure if it is something that should be fixed. At most it will hopefully help other people that come across the same issue and save them some time.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
