### ISSUE TITLE
Example AAD in combination with local roles

### ISSUE THREAD

**Issue by bertgroenveld** [dotnet/AspNetCore.Docs#17593]
With this approach, application roles are not stored in Azure AD at all. Instead, the application stores the role assignments for each user in its own DB using ASP.NET Core Identity. I would really appreciate an example where this is implemented. This would be a nice addition to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9816eaee-5eff-c3c8-5d58-e2c02c760a00
* Version Independent ID: 60992d09-2a04-1d10-4c85-9642b20ff0e3
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bertgroenveld ... Yes, I think I can work something out for you here. I'll get back to you on Monday mid-morning. If it looks good, then we can see if management would like me to roll it into the doc. *Get back to you soon!*

**Comment by bertgroenveld** [comment]
Thank you so much!

Best regards, Bert Groenveld

**Comment by guardrex** [comment]
I've taken a closer look here ...

> the application stores the role assignments for each user in its own DB using ASP.NET Core Identity

... can't be a Blazor **_WebAssembly_** scenario given that the app is a standalone piece that runs on the client. You can go with Blazor Server for this scenario. You could even have a hybrid hosted scenario where via API calls the back-end app, which does the Identity part (like the Identity Server scenario).

Given that Identity works with Blazor Server OOB for this scenario, that's the one that we want to guide devs to use for this use case.
