### ISSUE TITLE
So far so good

### ISSUE THREAD

**Issue by claudelarocque** [dotnet/AspNetCore.Docs#17596]
[En suivant les directions, tout se passe comme prévu... à suivre]

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/fr-ca/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows#feedback)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Thank you for the feedback! It's great to hear that your learning is going well.
