### ISSUE TITLE
Hosted Service Threading Model Not Documented

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/AspNetCore.Docs#17604]
The documentation doesn't explain the underlying threading model for Hosted Services. 

For example, do they run on a different thread pool than the one ASP uses for requests, or will calling Task.Run create potential contention (as it does in normal ASP)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
