### ISSUE TITLE
Consuming Background Services via Dependency Injection Not Documented

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/AspNetCore.Docs#17603]
Given a simple background worker that implements BackgroundService, the documentation recommends registering the service via Program.cs, with AddHostedService. However, controllers and other items will be unable to consume the service with this alone. If this is combined with an AddSingleton in Startup.cs, then two distinct objects are created.

It would be great if the documentation explained how to use the provider overload, so we could register a singleton for the service (so it's visible to DI), and then also start the service. This is explained here:
https://stackoverflow.com/questions/58397807/how-to-resolve-hostedservice-in-controller

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Background tasks with hosted services: master issue #17605
