### ISSUE TITLE
Getting docker: Error response from daemon: 

### ISSUE THREAD

**Issue by jikkujj** [dotnet/AspNetCore.Docs#17602]
When I run 

> docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="Docker@2020" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ mcr.microsoft.com/dotnet/core/samples:aspnetapp

as per instructions in https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1
I get 

> docker: Error response from daemon: create ${HOME}/.aspnet/https: "${HOME}/.aspnet/https" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
@jikkujj  that looks like a pretty good error message

**Comment by jikkujj** [comment]
Also I used the wrong command. Just was coming around to closing the issue. I was using the linux version of the docker command instead of the windows version of the command.

**Comment by Rick-Anderson** [comment]
@jikkujj  thanks for the update
