### ISSUE TITLE
Dependency on launchBrowser setting

### ISSUE THREAD

**Issue by jsayce** [dotnet/AspNetCore.Docs#17607]
Debugging in VS seems to be dependent on having "launchBrowser": true in the launchSettings.json file. I know this is the setting you have in your example file in the doc, but it might be worth explicitly mentioning that debugging doesn't work if the launchBrowser setting is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jsayce ... That's the default (and as you say, it's shown), so let's see if more feedback comes in on it. I'll keep an :ear: open for more devs hitting it. If so, I'll call it out.

**Comment by jsayce** [comment]
OK - just thought that if someone has set it not to open a browser (like I did), then it's really not very obvious why debugging isn't working.

**Comment by guardrex** [comment]
🤔 ... Why would one set it to `false` tho for debugging in this scenario? Usually, one would want the browser to launch for a browser-based app framework, such as Blazor.

**Comment by guardrex** [comment]
> for debugging

... or perhaps I should say ... *if they know that they plan to debug in this scenario*.

**Comment by jsayce** [comment]
I'm coming from an MVC background, where I'm used to keeping the browser open, and sometimes having the debugger attached, sometimes running without the debugger. Maybe that's not the best way to work with Blazor...?

**Comment by guardrex** [comment]
Given that Blazor (specifically Razor components) is a SPA/web technology, there isn't much that it can do (I don't think 🤔) without a browser. Certainly in the Blazor WebAssembly case, that would be true.

I'll keep an :ear: open for more feedback on this. We don't want to load the docs with default setting call-outs. It's true as you suggest that if devs keep hitting a problem, even with a default, that we would want to say something. However, we need more of a critical mass of comments before making such a change as this. Let's see if a dozen devs hit a problem and comment and especially if devs open issues with engineering saying that they can't get debugging to work.
