### ISSUE TITLE
Javascript subscribe to stream on page load

### ISSUE THREAD

**Issue by JasOcher** [dotnet/AspNetCore.Docs#17613]
This doesn't appear to want to work.  I've tried a number of methods and the stream won't fire unless I use a button click event listener.  How do I start the stream subscription on page load?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Can you share what you're trying to do? Have you made sure the connection has started before trying to stream?

**Comment by JasOcher** [comment]
I'm streaming live price data from my broker and am wanting the stream to start on page load.  It works when I use a JavaScript button click event listener, but not when any sort of window or page load is used.

**Comment by BrennanConroy** [comment]
Sure, can you provide your javascript code?

**Comment by JasOcher** [comment]
You bet, here it is...

`var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};

var connection = new signalR.HubConnectionBuilder()
    .withUrl("/streamHub")
    .build();

connection.serverTimeoutInMilliseconds = 200000;

document.getElementById("streamButton").addEventListener("click", (event) => __awaiter(this, void 0, void 0, function* () {
    try {
        document.getElementById("messages").innerHTML = "";

        connection.stream("OandaPriceStream")
            .subscribe({
                next: (item) => {
                    ... do stuff
                },
                disconnected: () => {
                    ... do stuff
                },
                complete: () => {
                    ... do stuff
                },
                error: (err) => {
                    ... do stuff
                }
            });
    }
    catch (e) {
        console.error("stream error:" + e.toString());
    }
    event.preventDefault();
}));

(() => __awaiter(this, void 0, void 0, function* () {
    try {
        yield connection.start();
    }
    catch (e) {
        console.error(e.toString());
    }
}))();`

**Comment by JasOcher** [comment]
Eh, looks like some of it got formatted poorly.  Here it is w/o the code tags.

var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};

var connection = new signalR.HubConnectionBuilder()
    .withUrl("/streamHub")
    .build();

connection.serverTimeoutInMilliseconds = 200000;

document.getElementById("streamButton").addEventListener("click", (event) => __awaiter(this, void 0, void 0, function* () {
    try {
        document.getElementById("messages").innerHTML = "";

        connection.stream("OandaPriceStream")
            .subscribe({
                next: (item) => {
                    ... do stuff
                },
                disconnected: () => {
                    ... do stuff
                },
                complete: () => {
                    ... do stuff
                },
                error: (err) => {
                    ... do stuff
                }
            });
    }
    catch (e) {
        console.error("stream error:" + e.toString());
    }
    event.preventDefault();
}));

(() => __awaiter(this, void 0, void 0, function* () {
    try {
        yield connection.start();
    }
    catch (e) {
        console.error(e.toString());
    }
}))();

**Comment by JasOcher** [comment]
Well, guess it's just going to do it regardless.

**Comment by BrennanConroy** [comment]
That's the working code I'm assuming? Since it uses the "click" event. Where is the broken code?

**Comment by JasOcher** [comment]
The broken code was reverted as I'm currently using this code.  I would need to see a working example from someone at this point.

**Comment by BrennanConroy** [comment]
Well, generally we would need to see your code to try and see what's wrong, so instead I'll have to guess what's wrong.

You probably aren't waiting for the connection to start before trying to stream. Your code should look something like:
```
connection.start().then(function () {
    connection.stream("OandaPriceStream")...
}).catch(function (err) {
    return console.error(err.toString());
});
```

but probably looks more like:
```
connection.start()
.catch(function (err) {
    return console.error(err.toString());
});

connection.stream("OandaPriceStream")...
```

**Comment by JasOcher** [comment]
I'm not sure what else you're wanting to see.  What I posted is the whole of the signalrstream.js file, minus the actual data processing.

**Comment by BrennanConroy** [comment]
>  would need to see a working example from someone at this point.

The code I provided works:
```
connection.start().then(function () {
    connection.stream("OandaPriceStream")...
}).catch(function (err) {
    return console.error(err.toString());
});
```

**Comment by JasOcher** [comment]
Is that the entirety of the signalrstream.js file?
