### ISSUE TITLE
Rendering glitch

### ISSUE THREAD

**Issue by leotsarev** [dotnet/AspNetCore.Docs#17612]
See s/shot
![изображение](https://user-images.githubusercontent.com/909808/78472192-78b51600-773f-11ea-84a4-aeba04628b5d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs/commit/8483cf7489e9962ab521c59d43e88cff2da0f426
