### ISSUE TITLE
Insecure localhost connection

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17622]
Hi team, 
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.de-de/issues/62 

@ArdorDeosis commented 2 days ago — with docs.microsoft.com
In Step 3.7 my Chrome browser at first blocked non-certified connections to localhost as insecure. A link to resources fixing this problem would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ArdorDeosis ... I think we'll need more information ...

> In Step 3.7

There's no "step 3.7" ... which step? ... and which IDE are you using?

> at first blocked

"at first" ... and then later it worked?

> non-certified connections to localhost as insecure

Can you provide the exact error and where the error appeared? ... provide a screenshot or text.

**Comment by ArdorDeosis** [comment]
Hi! 3.7 related to the (probably german) version of the page I originally wrote this for. It is the step in which you navigate to https://localhost:5001 in your browser (on the linked page step 9 with Visual Studio Code, but the point should come with the others, too).
'At first' as in before I allowed the browser to use uncertified resources from localhost, which can be done in Chrome as described [here](https://superuser.com/questions/772762/how-can-i-disable-security-checks-for-localhost).
I can't provide a screenshot right now, but it would be pretty much the same as in the stack exchange link describing the fix. If it helps I still can provide one though, some time in the coming days.

**Comment by guardrex** [comment]
> before I allowed the browser to use uncertified resources from localhost

Oh, I see what you mean now.

Trusting the development certificate should have been taken care of when the SDK was installed. I think the guidance is over here :point_right: https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos

WRT cross-linking that here, we probably wouldn't do it unless it was a very common problem. Trusting the development certificate is a common practice that relates to every topic that involves HTTPS. Generally, trusting the dev certificate goes ok when the SDK is installed. We only very rarely get an issue like this. I'll keep an :ear: open for more devs hitting it.

If you installed the SDK and the certificate wasn't trusted **_and_** that documentation :point_up: doesn't help, then open a new issue at the bottom of that topic (the English version) with the **This page** feedback button. Rick Anderson is the author of that topic, and he will see if your issue should be moved to engineering for a closer look by the product unit or if there's something missing from the document for VSC.
