### ISSUE TITLE
Add what's new page for April 2020

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#17624]
@Rick-Anderson @wadepickett Feel free to update this issue with any major updates you make this month. When I generate the what's new page on May 1st, I'll check this issue to confirm everything has been included.

**Comment by Rick-Anderson** [comment]
`[Enable Cross-Origin Requests (CORS)]` (xref:security/cors)`https://github.com/dotnet/AspNetCore.Docs/pull/17345 total rewrite of CORS doc
