### ISSUE TITLE
Dealing with other ActionResult values

### ISSUE THREAD

**Issue by jlinstrum** [dotnet/AspNetCore.Docs#17634]
It would be nice to have information about dealing with Http requests that return values other than the expected serialized object. The default MVC core controller templates return all results in wrapped in an ActionResult object, including "NotFound()" or "BadRequest()" results, but as a beginner looking at this page I have no idea how to deal with any result other than the expected serialized object, and I also don't know where to look to find out more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jlinstrum Yes, we're going to need a short section on that point here with a cross-link to the *Handle errors* topic and perhaps something over there, too. Basically, this is going to be up to your code to handle (at least for the time being). You'll need to `try-catch` yourself on these calls and recover the status and handle it yourself.

For example, see :point_right: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample/Components/HTTPRequestTester.razor#L118-L125
