### ISSUE TITLE
'Code Above' vs. 'Preceding Code'

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/AspNetCore.Docs#17638]
Both these terms are used frequently throughout the documentation but are synonymous. "code above" appears 23 times while "preceding code" appears 342 times. The latter is more formal and may not meet the requirement of [targeting fifth-grade level](https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-voice-tone#target-a-fifth-grade-reading-level). 

One term should should be chosen and rolled out throughout the repository.

**Comment by guardrex** [comment]
"Preceding" is the way to go per our repo guidelines. We generally don't use *directional* terms, such as "above" and "below."

Inconsistencies are present because ...

* Many contributors have worked on the topics. Sometimes, a nit is missed on review.
* There are **_many_** topics ... like nearly **400** now. 😅 
* The guidelines change from time-to-time, but we're often too busy to go back and update many topics at once. This is a small team.

We fix things up as we go. When a topic is overhauled, we get all the little nits updated.

**Comment by MelbourneDeveloper** [comment]
@guardrex understood, but my next step was going to be to submit a PR to straighten this out. Should I do that?

**Comment by guardrex** [comment]
Sure thing! That would be great. I thought you were just letting us know.

**Comment by MelbourneDeveloper** [comment]
@guardrex I would have just submitted the PR without creating an issue first but wasn't sure which term you wanted.

**Comment by guardrex** [comment]
Issues are good to make sure that time isn't lost. The team occasionally needs to decline a PR. When it happens, we wish the contributor had opened an issue to ask first.

**Comment by MelbourneDeveloper** [comment]
@guardrex I'm still intending on doing this... Hopefully, I will get to this soon.

**Comment by guardrex** [comment]
I'm going to move this to backlog just so that we can close this old milestone ... it keeps popping up on me and getting in the way when working with new issues. 🏃

**Comment by MelbourneDeveloper** [comment]
@guardrex sorry about that. I meant to work through this one, but didn't end up getting time.

**Comment by guardrex** [comment]
That's ok ... I'm just cleaning up the old milestones. When I pop open the drop down on GH, I was getting flooded with old ones, and it has been slowing me down 0.37 seconds per issue. :smile:

Too many milestones on here is ...........

![thecollector](https://user-images.githubusercontent.com/1622880/90622516-cf952680-e1da-11ea-99fc-da9d4eb6b8c7.jpg)

### *An unprofitable operation, Hade.*
&ndash; The Collector ([Henry Woolf](https://tardis.fandom.com/wiki/Henry_Woolf))
[Doctor Who](https://www.bbc.co.uk/programmes/b006q2x0): [The Sun Makers](https://www.bbc.co.uk/programmes/p00q05st), ©1977 [BBC](https://www.bbc.com/)
