### ISSUE TITLE
Scaffold Identity section "Create full identity UI source" still has 2.1 version code when viewing 3.1 version docs.

### ISSUE THREAD

**Issue by dbrennan** [dotnet/AspNetCore.Docs#17639]
There are references to both `CompatibilityVersion.Version_2_1` and `AllowAreas = true` which are both not applicable in version 3.1 and should be updated.  In addition, the suggestion to add the EmailSender at the end of the C# code for this case is optional and only relevant to Email configuration and not a required change for the scaffolding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#scaffold-identity-into-an-mvc-project-with-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fdbva** [comment]
I also can't make it work after following the example for `Scaffold identity into an MVC project without existing authorization`.
I'm creating new Data context class and User class using the scaffolding window.
Also, the default startup for `3.1` does not use `.AddMvc()` anymore, it uses `.AddControllersWithViews()`.

What's the point of `IdentityHostingStartup` if everything will be configured in `Startup.cs`?
I want to isolate everything inside the identity Area and not mix it with everything else.

**Comment by fdbva** [comment]
If it's scaffolding, there's probably going to exist more than one context.
While the error when you execute the command without specifying the context is very clear, I think the guide should tip about the possibility and explain the solution

**Comment by danieldiazastudillo** [comment]
This is terribly inconsistent. Calling the `AddRazorPagesOptions`, the `options` object doesn't even have the `AllowAreas` prop, very confusing. Just wanna control the Authenticate URL strings.

**Comment by Rick-Anderson** [comment]
Fixed in Disable pages in Identity UI #18768
