### ISSUE TITLE
Grpc.Core.RpcException when running sample

### ISSUE THREAD

**Issue by SuschNL** [dotnet/AspNetCore.Docs#17630]
If I try running this sample directly (downloaded from GitHub), I get the following exception in the client:

Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Bad gRPC response. Expected HTTP status code 200. Got status code: 403")

I also tried a different gRPC example (https://auth0.com/blog/implementing-microservices-grpc-dotnet-core-3/) and get a different error:

Unhandled exception. Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

Why is none of this code working for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
What is `dotnet --version` and `dotnet --info`` on your machine?
What version was the sample created for?

**Comment by wadepickett** [comment]
Closing.  We could use more information to help.  We can re-open if you are able to provide more detail for the questions above.  Thanks very much for taking the time to let us know your experience.
