### ISSUE TITLE
Edge not loading with URL after addition of inspectUri

### ISSUE THREAD

**Issue by alfkonee** [dotnet/AspNetCore.Docs#17631]
After adding the inpectUri property to launchSettings  Upon launch the browser just loads without a URL causing the link to fail and Timeout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alfkonee ... Open that for engineering at ...

https://github.com/dotnet/aspnetcore/issues

If you get an answer that requires content to be added to the doc, ping me back here, and I'll re-open this.

Alternatively, you can add a "cc: @guardrex" to your engineering issue, and I'll follow the discussion there.
