### ISSUE TITLE
Term 'IO' inconsistency

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/AspNetCore.Docs#17637]
# Issue description

This is a correctness issue. Some places in the documentation use the term IO, while others use the term I/O. There should be consistency but I didn't know which is the preferred term. Here are some examples:

[>  Synchronous **IO**](https://github.com/MelbourneDeveloper/AspNetCore.Docs/blob/31ace995f6a07aafcc84834deaadcef035e4c6b6/aspnetcore/fundamentals/servers/kestrel.md#synchronous-io)

[> With synchronous code, many threads may be tied up while they aren't actually doing any work because they're waiting for **I/O** to complete.](https://github.com/MelbourneDeveloper/AspNetCore.Docs/blob/072292c86acad5167d3c453e54aed969f468cf02/aspnetcore/data/ef-mvc/intro.md#asynchronous-code)

**Comment by MelbourneDeveloper** [comment]
@guardrex again, this is a PR offer

**Comment by guardrex** [comment]
Sure thing ... it should be "I/O" ... see https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/input-output
