### ISSUE TITLE
not very useful

### ISSUE THREAD

**Issue by aadurham** [dotnet/AspNetCore.Docs#17644]
I bet everything one needs is here, but it would be great if there were a complete set of sample code with explanations, this is very technical for somebody new to signalr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
Authentication and authorization are inherently complex topics.  There is a download link at the top of the article.
