### ISSUE TITLE
Data Protection - Provide IXmlRepository with singleton dependencies

### ISSUE THREAD

**Issue by AlissonRS** [dotnet/AspNetCore.Docs#17643]
In a .NET Core 3.1 project, one may configure Data Protection in `ConfigureServices` like below:

```
public void ConfigureServices(IServiceCollection services)
{
    // ...

    var sp = services.BuildServiceProvider();
    services.AddDataProtection()
            .AddKeyManagementOptions(o => o.XmlRepository = sp.GetService<IXmlRepository>());
}
```

This raises below warning (which makes sense):

> Calling 'BuildServiceProvider' from application code results in an additional copy of singleton services being created. Consider alternatives such as dependency injecting services as parameters to 'Configure'.

I'm using a service provider there because my implementation of `IXmlRepository` has a dependency to a singleton service.

What would be the recommended way of providing my `IXmlRepository` implementation without having to build the service provider (and thus making additional copies of singleton services)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532d66a6-fa01-54d3-1dfa-20d1889668bb
* Version Independent ID: 6489c522-2148-e39a-92cc-6f631c065422
* Content: [Get started with the Data Protection APIs in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/using-data-protection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/using-data-protection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by csalgo70** [comment]
I am having the same issue with this trying to call services.BuildServiceProvider().GetDataProtectionProvider(). What is the correct way to inject it ?

```
public void ConfigureServices(IServiceCollection services)
{
      services.AddControllers();

      services.AddDataProtection();
            
      var dpp = services.BuildServiceProvider().GetDataProtectionProvider();

      services.AddSingleton<IDataProtectionProvider>(dpp);
}
```

**Comment by ryan-morris** [comment]
It looks like they EF Core version created a wrapper that creates temporary scopes. [See here](https://github.com/dotnet/aspnetcore/tree/master/src/DataProtection/EntityFrameworkCore/src) . That nuget package actually eliminated our need for any of our custom stuff.

**Comment by stefanb05** [comment]
I had this problem too because MyDataStore is a singleton, inspired by EF implementation I managed to do this:

`services.AddDataProtection().Services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(serv =>
{
	return new ConfigureOptions<KeyManagementOptions>(options =>
	{
		options.XmlRepository = new MyXmlRepository(serv.GetService<IMyDataStore>());
	});
});`

**Comment by maulik-modi** [comment]
@Tratcher or @davidfowl , can you suggest the recommendations here?

**Comment by Tratcher** [comment]
@stefanb05's answer is good.

**Comment by davidfowl** [comment]
We added more convenient helpers for this:

```C#
services.AddOptions<KeyManagementOptions>()
        .Configure<IMyDataStore>((options, store) => 
        {
            options.XmlRepository = new MyXmlRepository(store);
        });
```

It removes the clunky calls to `GetService` and hides `IConfigureOptions<T>`

**Comment by Tratcher** [comment]
Doesn't that use an odd lifetime?

**Comment by Rick-Anderson** [comment]
@Tratcher should I add the sample you recommend or @davidfowl  sample.

**Comment by Tratcher** [comment]
@HaoK ?

**Comment by HaoK** [comment]
David's one is better:

```
services.AddOptions<KeyManagementOptions>()
        .Configure<IMyDataStore>((options, store) => 
        {
            options.XmlRepository = new MyXmlRepository(store);
        });
```

**Comment by AlissonRS** [comment]
@Rick-Anderson @davidfowl @HaoK I tried using it like below:

```
// register EF DB Context
services.AddDbContext<MyAppDbContext>();

// register XmlRepository for data protection
services.AddOptions<KeyManagementOptions>()
.Configure<MyAppDbContext>((options, dbContext) =>
{
    options.XmlRepository = new CustomXmlRepository(dbContext);
});
```

But I got the exception below upon initialization:

> Cannot resolve scoped service 'MyApp.Data.Context.MyAppDbContext' from root provider.

I'm using .NET Core 3.1, not sure what I'm missing, but my dependency (EF DbContext) is scoped, not singleton.

**Comment by davidfowl** [comment]
You don't want to inject a DbContext, you want to inject something that can create a DbContext (like a factory).

**Comment by AlissonRS** [comment]
@davidfowl thanks, I changed it to get `IServiceScopeFactory` as a dependency so I can create a scope and create a DbContext within the `CustomXmlRepository`. Can we make this a little more explicit in the docs?

Here is my final solution:

Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
    // register DbContext
    services.AddDbContext<DataProtectionDbContext>();

    // ...

    // register XmlRepository for data protection
    services.AddOptions<KeyManagementOptions>()
    .Configure<IServiceScopeFactory>((options, factory) =>
    {
        options.XmlRepository = new CustomXmlRepository(factory);
    });
}
```

CustomXmlRepository.cs
```
public class CustomXmlRepository : IXmlRepository
{
    private readonly IServiceScopeFactory factory;

    public CustomXmlRepository(IServiceScopeFactory factory)
    {
        this.factory = factory;
    }

    public IReadOnlyCollection<XElement> GetAllElements()
    {
        using (var scope = factory.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<DataProtectionDbContext>();
            var keys = context.XmlKeys.ToList()
                .Select(x => XElement.Parse(x.Xml))
                .ToList();
            return keys;
        }
    }

    public void StoreElement(XElement element, string friendlyName)
    {
        var key = new XmlKey
        {
            Xml = element.ToString(SaveOptions.DisableFormatting)
        };

        using (var scope = factory.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<DataProtectionDbContext>();
            context.XmlKeys.Add(key);
            context.SaveChanges();
        }
    }
}
```

DataProtectionDbContext.cs
```
public class DataProtectionDbContext: DbContext
{
    public DbSet<XmlKey> XmlKeys { get; set; }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

       builder.Entity<XmlKey>().Property(x => x.Xml).HasColumnType("TEXT");
    }
}
```

XmlKey.cs
```
public class XmlKey
{
    public Guid Id { get; set; }
    public string Xml { get; set; }

    public XmlKey()
    {
        this.Id = Guid.NewGuid();
    }
}
```

**Comment by davhdavh** [comment]
Why is the options pattern for KeyManagementOptions so bad?

KeyManagementOptions.XmlRepository (and others) should have been a factory method instead of the concrete instance to use.

Anyway, workaround:
```

   /// <summary>
   /// Persist keys to a custom <see cref="IXmlRepository" /> implementation.
   /// </summary>
   /// <example>
   /// services.AddSingleton&lt;MyXmlRepository&gt;();
   /// services.AddDataProtection().SetApplicationName(startup.Domain).PersistKeysTo&lt;MyXmlRepository&gt;();
   /// </example>
   /// <typeparam name="T">The concrete implementation type to use for persistance</typeparam>
   /// <param name="builder">The <see cref="IDataProtectionBuilder" />.</param>
   /// <returns>A reference to the <see cref="IDataProtectionBuilder" /> after this operation has completed.</returns>
   public static IDataProtectionBuilder PersistKeysTo<T>(this IDataProtectionBuilder builder) where T:IXmlRepository
   {
      if (builder == null) throw new ArgumentNullException(nameof(builder));
      builder.Services.AddSingleton<IConfigureOptions<KeyManagementOptions>>(sp => {
         return new ConfigureOptions<KeyManagementOptions>(options => options.XmlRepository = new DummyXmlRepository<T>(sp));
      });
      return builder;
   }

   private sealed class DummyXmlRepository<T> : IXmlRepository where T:IXmlRepository
   {
      private readonly Lazy<T> _lazy;
      public DummyXmlRepository(IServiceProvider sp) => _lazy = new(sp.GetRequiredService<T>);

      public IReadOnlyCollection<XElement> GetAllElements() => _lazy.Value.GetAllElements();
      public void  StoreElement(XElement element, string friendlyName) => _lazy.Value.StoreElement(element, friendlyName);
   }
```
