### ISSUE TITLE
Authorization by Roles

### ISSUE THREAD

**Issue by abubakarbaig** [dotnet/AspNetCore.Docs#17659]
I want to ask that if we may assign role-based authorization to the controllers dynamically? For example, an end-user of the application create a role with the name of "ExampleRole" and assign the role to a user. Now if the role is not hard-coded over the controller like this [Authorize(Roles = "ExampleRole")], it could not be used by the end-user. There should be a way to create a role and utilize it throughout your application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is not a tutorial on security. Review the security docs.
