### ISSUE TITLE
How to give a different name for the controller?

### ISSUE THREAD

**Issue by YeskaNova** [dotnet/AspNetCore.Docs#17658]
I have a generic controller that I want to register for different entities at runtime, but because routing is done based on the controller name by convention, is there any way to give the name for each new controller type? So that MyGenericController< Document > will be considered like DocumentController?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Share controllers, views, Razor Pages and more with Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
By default routing is done by controller name and action. You can change that. See the routing docs.
