### ISSUE TITLE
Create Default Builder also seems to do some other static files stuff

### ISSUE THREAD

**Issue by dazinator** [dotnet/AspNetCore.Docs#17655]
When running on a Development environment inspecting the `IWebHostEnvironment.WebRootFileProvider` immediately in startup.cs Configure method:

```
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

```

Shows me that WebRootFileProvider is now being set to a composite that inlcudes static files (web assets) from project references "wwwroot" directories as well as "bin/{build-config/{target-framework}/wwwroot" directories. I assume this host.CreateDefaultBuilder configuring this and including static web assets from referenced projects for you - but I can't see this documented anywhere. Is here the right location for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It sets the content root directory and other things.
You can look at the source to see all that it's doing, but you can't access static files without calling `app.UseStaticFiles();`

**Comment by dazinator** [comment]
@Rick-Anderson - understood.

I wasn't very clear though so apologies, and just let me make sure I have actually put my point accross - if you still dismiss it fair enough.

The docs specifically talk about serving files within the "WebRoot" directory (its all over them).
With the introduction of "Static Web Assets" this is no longer true when the environment is a "Development" Environment.

I thought it might be worth mentioning that when the `environment.IsDevelopment` is true, the host will serve up files from outside the projects "web root" folder, by virtue of using the new manifest file that is produced by a build - there are "content root" paths in there that point to possibly other locations:

- Locally referenced projects "wwwroot" and bin/ output directories
- Referenced NuGet packages that contain static web assets.

CreateDefaultBuilder doesnt just set content root (which has no impact on static files, web root does) - it now also extends WebRootFileProvider to include additional ones to serve outside the webroot directory, but only for Development environments.

I think it might benefit the docs to mention this or link to some other doc that describes this feature, but I'm just putting it out there - if you think otherwise obviously happy to leave this issue closed!

Cheers

**Comment by Rick-Anderson** [comment]
@dazinator  that's good information. Yes, in dev mode there is more access. This info might be useful because an app that works in dev mode won't work in production mode because it's using resources only available in dev mode.

**Comment by dazinator** [comment]
@Rick-Anderson
> because an app that works in dev mode won't work in production mode because it's using resources only available in dev mode.

- In production mode (after a dotnet publish occures) these static assets that get sourced from the manifest, are copied by `dotnet publish` into the `wwwroot `directory of the published application. Therefore in production mode, all the same assets should still be reolvable using the same subpaths as before and the application should work as it always has - except now there is no manifest mapping those assets to their source locations.

The only time I think you could hit an issue is if you were to `dotnet run` a non published application 's binaries (bin output folder) on a non Development environment - where those sources (projects and nuget packages) weren't available. I think it's fairly safe to say that this isn't typical or recommended workflow however :-)

**Comment by Rick-Anderson** [comment]
Moved to Static files master issue and update to 3.1 #13599
