### ISSUE TITLE
Add CORS support in this example

### ISSUE THREAD

**Issue by oridespavaneli** [dotnet/AspNetCore.Docs#17656]
I tried to use this WebApi to test with Blazor WebAssembly, but I couldn't get the API to work with CORS.
I tried hard ... could you give me a tested example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson I have the CORS support in the topic. I'm not sure if over time the example in the tutorial drifted from what I used in the Blazor *Call a web API* topic to the point where the Blazor topic is broken now.

In the Blazor topic, CORS is described here :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#cross-origin-resource-sharing-cors

... and the exact example is at the end of this section :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#httpclient-and-httprequestmessage-with-fetch-api-request-options

My local implementation of this web API does work with the current Blazor common sample app. What I *should do* is set up a new web API from the updated topic (after your PR) to see if the Blazor topic example is broken.

I'll re-open @oridespavaneli original issue and schedule it to do so. It could take a week (or a few) to get to it tho.

**Comment by Rick-Anderson** [comment]
@oridespavaneli  CORS 3.1 update #17345 has samples you can test.

**Comment by oridespavaneli** [comment]
Everything is working properly!
I must apologize, because I didn't notice the following in "Program.cs":
                    //webBuilder.UseStartup <Startup> ();
                    webBuilder.UseStartup <StartupJavaScript> ();

I had configured CORS in "Startup.cs", and did not make the change to use the procedure, StartupJavaScript was being used.
