### ISSUE TITLE
Can we have _Layout.cshtml.cs for the page _Layout.cshtml

### ISSUE THREAD

**Issue by smjltd** [dotnet/AspNetCore.Docs#17668]
need documentation for dynamics Shared Layout, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by SimpleSamples** [comment]
It seems to me that _Can we have _Layout.cshtml.cs for the page _Layout.cshtml_ is different from _need documentation for dynamics Shared Layout_. The first is a question and the second sounds like a feature request that implies the answer to the question is known. I assume that the answer to the question is  no, it is not supported.
