### ISSUE TITLE
GPDR on mobile problems

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17663]
Hi team, 
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.it-it/issues/48

@mtugnoli commented 11 hours ago
I see the GDPR sample for asp.net core, but I don't understand why don't run on mobile !
this row seem have problems,
can you help me ?

document.cookie = button.dataset.cookieString;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Check with a mobile tutorial site.

**Comment by mtugnoli** [comment]
Thanks Rick your help has been really valuable.
