### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by glennsills** [dotnet/AspNetCore.Docs#17672]
Where are keys stored on Linux or Macs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722632a9-288e-7023-91a4-a92709de6986
* Version Independent ID: 6db8586d-0fe4-9afe-73f7-b047af588e73
* Content: [Key storage format in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-format?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-format.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-format.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@glennsills The default key storage directory for both macOS & Linux is *$HOME/.aspnet/DataProtection-Keys*. See https://github.com/dotnet/aspnetcore/blob/f3963e7cb75c985dcdd84c4f015267c7e5371f35/src/DataProtection/DataProtection/src/Repositories/DefaultKeyStorageDirectories.cs#L24. I'm working on documenting this right now.
