### ISSUE TITLE
Change log. 

### ISSUE THREAD

**Issue by Bhimbim** [dotnet/AspNetCore.Docs#17676]
Hello, 

I've been looking for the signalr change log. Sometimes the client side got updates and the server not. Without the change log it worries me to update the client. Who knows this client version need to have certain server version. So can we have change log for signalr ?, for the clients and servers. Thank you.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
