### ISSUE TITLE
please install the package Microsoft.VisualStudio.Web.CodeGeneration.Design

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17677]
@antonywusz commented on [Wed Apr 08 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/257)

when entering into the step"Add Razor pages  using Entity Framework(CRUD)"
the ui shows scaffolding for a long time  and then shows the error including"please install the package Microsoft.VisualStudio.Web.CodeGeneration.Design"
and I try to install the Nuget with different version but the error still appears
<img width="950" alt="111" src="https://user-images.githubusercontent.com/34709085/78776390-5f73ca00-79ca-11ea-8f1f-cd2ad68429a9.png">

---

@srvbpigh commented on [Wed Apr 08 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/257#issuecomment-610895393)

Hello, @antonywusz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Exit and restart Visual Studio.

**Comment by nk1125** [comment]
Is there any resolution for this issue?
