### ISSUE TITLE
Blazor WebAssembly and keys

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs#17675]
It is not clear where a Blazor WebAssembly using Microsoft.AspNetCore.ProtectedBrowserStorage should save the keys.
At the moment Microsoft.AspNetCore.ProtectedBrowserStorage seems working only on server-side Blazor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1#client-side-in-the-browser)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's correct @GioviQ ... from the topic ...

> localStorage and sessionStorage can be used in Blazor WebAssembly apps but only by writing custom code or using a 3rd party package.

It's a Blazor Server technology at this time.
