### ISSUE TITLE
Razor - Run the app section does not cover how to run the app in Linux

### ISSUE THREAD

**Issue by spectrumcomputing** [dotnet/AspNetCore.Docs#17687]
[Enter feedback here]

Hello,

The run the app section does not cover how to run the app in Linux.  I assume its just:

```
dotnet run RazorPagesMovie
```
In the Visual Studio Code Terminal, as Ctrl + F5 just seems to produce this.  Am I missing something?

![Capture](https://user-images.githubusercontent.com/38283339/78888226-19197c00-7a59-11ea-823a-a04949e34a43.PNG)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc
`dotnet run`

**Comment by spectrumcomputing** [comment]
Hi, thanks for the reply, but I don't see dotnet run in the docs:

![Capture](https://user-images.githubusercontent.com/38283339/78929159-c8764300-7a99-11ea-84d9-8cd8b572b683.PNG)
