### ISSUE TITLE
MVC - Run the app section does not cover how to run the app in Linux

### ISSUE THREAD

**Issue by spectrumcomputing** [dotnet/AspNetCore.Docs#17688]
[Enter feedback here]

Hello,

The run the app section does not cover how to run the app in Linux.  I assume its just:

```
dotnet run MvcMovie
```
In the Visual Studio Code Terminal, as Ctrl + F5 just seems to produce this.  Am I missing something?

![Capture](https://user-images.githubusercontent.com/38283339/78888132-fd15da80-7a58-11ea-95e5-f1032247abe0.PNG)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc
`dotnet run`

**Comment by spectrumcomputing** [comment]
Hi, sorry but I don;t see that:

![Capture2](https://user-images.githubusercontent.com/38283339/78929350-26a32600-7a9a-11ea-8a83-ca77f41fb41b.PNG)

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio-code
