### ISSUE TITLE
Add Info about supporting ALL cultures in .net Core

### ISSUE THREAD

**Issue by Nils-Berghs** [dotnet/AspNetCore.Docs#17689]
Localization is not about translations, (you can expect everybody to understand English). The main reason for localization is date and number formatting. The USA uses a mathematically wrong date format and you cannot expect people to accept that.

The workaround is to set the supported cultures to  CultureInfo.GetCultures(CultureTypes.AllCultures). This will not help with translations, but you will at least not insult people by forcing wrong number and dateformats on them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your comment.
