### ISSUE TITLE
Need small change to make example for User name and ID work

### ISSUE THREAD

**Issue by jlinstrum** [dotnet/AspNetCore.Docs#17682]
A feedback that has already been closed still requires one additional small change on the document. I already put a comment on the closed issue, but I should have opened a new issue. Here's a link to the comment:

https://github.com/dotnet/AspNetCore.Docs/issues/17402#issuecomment-611220730

Basically a line needs to be added to the Server App Configuration section under the Startup class section:

services.Configure(options =&gt;
options.ClaimsIdentity.UserIdClaimType = ClaimTypes.NameIdentifier);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jlinstrum It's already covered. It doesn't go in the *Startup* content at the top because it isn't intended to be an OOB scenario. It falls in under the [UserManager and SignInManager section](https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/hosted-with-identity-server#usermanager-and-signinmanager).
