### ISSUE TITLE
can you really rely on Directory.GetCurrentDirectory()

### ISSUE THREAD

**Issue by mnoreen** [dotnet/AspNetCore.Docs#17696]
One thing I liked about the web.config &lt;-&gt; machine.config hierarchy was it just worked. I see pretty much every example of using Json files and the Directory.GetCurrentDirectory() base path. The problem is, you search on that, and you'll find that the "CurrentDirectory" is a very subjective / elusive thing.   Debugging from Visual Studio vs runtime, process directory, did some other process set a current working directory, etc.

I'd like to see something that gave us a reliable method for finding a path to load the json config settings in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#access-configuration-in-startup)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's the path where the *appSetting.Json* family of files are.
```
  var path = Directory.GetCurrentDirectory();
                Console.Write(path);
```
