### ISSUE TITLE
Conflicting Instructions: Hierarchal Keys with Azure Key Vault Provider

### ISSUE THREAD

**Issue by DrakeLambert** [dotnet/AspNetCore.Docs#17698]
In the [Configuration keys and values](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#configuration-keys-and-values) section, the following instruction is given for using hierarchal keys with the Azure Key Vault Provider:

> In Azure Key Vault, hierarchical keys use `--` as a separator. Write code to replace the `--` with a `:` when the secrets are loaded into the app's configuration.

To me, this sounds like I'll need to add custom code to my application to handle converting the `--` to `:`. In practice, I've found that this is not the case. It would appear that the Azure Key Vault Configuration Provider handles the conversion for me.

In the article, [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#secret-storage-in-the-production-environment-with-azure-key-vault), it's documented that:

> Azure Key Vault secret names are limited to alphanumeric characters and dashes. Hierarchical values (configuration sections) use `--` (two dashes) as a separator. Colons, which are normally used to delimit a section from a subkey in ASP.NET Core configuration, aren't allowed in key vault secret names. Therefore, two dashes are used and swapped for a colon when the secrets are loaded into the app's configuration.

Are these articles providing conflicting information, or am I misunderstanding?

I'll create a PR for this issue in the case of the former.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DrakeLambert good catch. 
I think the only difference is in how to store the keys/values. In AKV, replace `:` with `--`
You don't change the code to read the key/values.

A PR would be great.

**Comment by DrakeLambert** [comment]
@Rick-Anderson see #17706
