### ISSUE TITLE
Error in example code

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17692]
The comments below were machine-translated

@Maximys commented on [Thu Apr 09 2020](https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/79)

The Update method (string id, Book bookIn) contains an error - we in bookIn do not fill in the Id property, and therefore ReplaceOne will throw an exception. It should be something like this:
public async void Update(string id, Book bookIn)
        {
            bookIn.Id = id;//фикс ошибки.
            await Books.ReplaceOneAsync(b =&gt; b.Id == id, bookIn);
        }

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Создание веб-API с помощью ASP.NET Core и MongoDB](https://docs.microsoft.com/ru-ru/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

---

@srvbpigh commented on [Thu Apr 09 2020](https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/79#issuecomment-611377836)

Hello, @Maximys
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Maximys** [comment]
May be my repository will helpful for understanding what's wrong: https://bitbucket.org/Mixim/e-learning/src/master/Src/NoSQL/BooksApi/BooksApi/Services/BookService.cs

**Comment by Rick-Anderson** [comment]
Moved to Master list: Create a web API and MongoDB #16196

**Comment by serpent5** [comment]
Fixed in #24126.
