### ISSUE TITLE
Using builder.Configure() in custom WebApplicationFactory causes Client 404 Error

### ISSUE THREAD

**Issue by jmichas** [dotnet/AspNetCore.Docs#17697]
I spent the better part of the last 2 days trying to figure out why my integration test client would only return 404 when I had another project with its own test project using the same setup that worked fine.
It turned out after to tearing things down and building them up a block/line of code at a time and testing, that I added to the "override void ConfigureWebHost(IWebHostBuilder builder)" a build.Configure(app=&gt;{});
I did this because I planned on inserting a custom auth middleware so that I could test secured endpoints.
I had commented out the call to my middleware but left the build.Configure() block there event though it was empty. This causes the Client to fail giving a 404 error no matter what you do.
If build.Configure should not be used, it should be noted in the docs and, if possible, TestServer or whatever makes sense should throw an exception if it is used in an integration test. This would have saved me an unbelievable amount of time. I ended up adding the auth handler as a service as explained in these docs, but how would I have known that build.Configure would blow up the client silently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Integration tests MASTER issue #16341
