### ISSUE TITLE
AspNetCore.SignalR CROS Error: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by mrjmCyber** [dotnet/AspNetCore.Docs#17705]
i followed the exact tutorial  from 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio
and then i wanted to access the hub from another Origin. so i followed the exact instructions in https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1

but i get this error:
`Access to XMLHttpRequest at 'http://localhost:55039/myhub/negotiate?negotiateVersion=1' from origin 'http://localhost:54114' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
```
 public void ConfigureServices(IServiceCollection services)
        {

            services.AddCors();
 services.AddSignalR(o =>
            {
                o.EnableDetailedErrors = true;
                o.HandshakeTimeout = TimeSpan.FromSeconds(5);
            });
}
```
and :
```
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {   
app.UseCors(builder =>
            {
                builder.WithOrigins("http://localhost:54114/")
                    .AllowAnyHeader()
                    .WithMethods("GET", "POST")
                    .AllowCredentials();
            });
            app.UseStaticFiles();

            app.UseRouting();
          
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<MyHub>("/myhub");
            });
}
```
- **asp.net core 3.1**
- **AspNetCore.SignalR**
any tips and guides will be appriciated
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af11946-ea05-3be2-6fa1-c4c01aa76d8c
* Version Independent ID: 58e87eb0-240b-ab00-c5f4-32a0ab2e0028
* Content: [Security considerations in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **anurse**

**Comment by BrennanConroy** [comment]
I'm not sure if this is the issue, but could you try removing the trailing `/`?
`http://localhost:54114/` -> `http://localhost:54114`

**Comment by mrjmCyber** [comment]
thank you so much , im struggling with this about 3 hours.
its been solved

**Comment by ChrisTorng** [comment]
If the `WithOrigins` method can't work with trailing `/`, can it just trim the trailing `/` to make it just work? Or throw `ArgumentException` to remind the extra `/` char? Currently the people using trailing `/`, needs to search all the CORS documents/problems, tries many different solutions, struggling for many hours, at last just found the problem is the extra `/` char.
