### ISSUE TITLE
Add docs about the default error page in the templates

### ISSUE THREAD

**Issue by shirhatti** [dotnet/AspNetCore.Docs#17708]
We currently display a request Id in the default error pages in our templates. There are no docs today on the format of that request Id or how can customers can use it to find their issue.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/4734691/78943334-40843f00-7a81-11ea-8463-5872f5028e8c.png)

I'm proposing we create a doc that covers what the request id (or [suitable replacement](https://github.com/dotnet/aspnetcore/issues/20705)) is and how you can use it to find more diagnostics both in VS and in Azure with Application Insights.

![Using Operation ID in VS](https://user-images.githubusercontent.com/4734691/78943582-c56f5880-7a81-11ea-9cb2-68bc2f1cc772.png)

**Comment by Rick-Anderson** [comment]
@shirhatti  if you can provide a draft I'll finish it off. Any format fine.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
