### ISSUE TITLE
Review CORS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17711]
Doc needs a read through and review.

* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-endpoint-routing)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
We do plan to tackle this as part of https://github.com/dotnet/aspnetcore/issues/21541. Using the referenced issue to prioritize during next sprint planning.

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson, let's close this as a dupe and wait till we get to the one I pointed out.

**Comment by mkArtakMSFT** [comment]
Closing this as a dupe of https://github.com/dotnet/aspnetcore/issues/21541
