### ISSUE TITLE
Do we need to export the private key also?

### ISSUE THREAD

**Issue by CmdrBeavis** [dotnet/AspNetCore.Docs#17715]
Under the /The sample app uses an Application ID and X.509 certificate when the #define statement at the top of the Program.cs file is set to Certificate./ section, where you talk about exporting the .pfx, it would be REALLY helpful if you'd let us know whether or not we're supposed to "..export the private key."  &gt;:|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CmdrBeavis** [comment]
Okay, well, after re-reading;

c. Select *Upload certificate* to upload the certificate, **_which contains the public key_**. A .cer, .pem, or .crt certificate is acceptable.

I tried it without the private key, and this appears to be the correct option given that a `DER encoded binary X.509 (.CER)` option is the first thing I see.

Seriously though, this is computers folks, **specificity** is kinda key here in our world. People reading through this doc trying to learn how to do this stuff do not just automatically know these things.

**Comment by Rick-Anderson** [comment]
@CmdrBeavis  thanks for the update. This isn't a tutorial, it's an advanced topic. We'll review this issue when we have time to update the doc. Feel free to PR to improve the instructions.
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
