### ISSUE TITLE
Using scopes with async/await

### ISSUE THREAD

**Issue by joshmouch** [dotnet/AspNetCore.Docs#17727]
I've noticed that logging scopes are lost when using `async/await` and a thread switch occurs.  Is there a way to prevent this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Logging in .NET Core and ASP.NET Core #16174

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Logging in .NET Core and ASP.NET Core #16174

**Comment by Rick-Anderson** [comment]
@joshmouch  can you post the simplest possible sample that reproduces the issue on GitHub?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
