### ISSUE TITLE
Halts at "Scaffold the movie model"

### ISSUE THREAD

**Issue by TyneBridges** [dotnet/AspNetCore.Docs#17729]
When trying the "Scaffold the movie model" I keep seeing the error that RazorPagesMovie.dll can't be accessed because it's already in use. This is despite closing all files and then closing the editor.  This is extremely frustrating because I can't see any advice on what the problem is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by TyneBridges** [comment]
Should have mentioned that the command that brings the multiple errors is dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries . I'm using Windows 10 and Visual Studio Core latest version, downloaded today.

**Comment by Rick-Anderson** [comment]
The error message tells the problem. Usually that's Kestrel is running, not the editor or other tool.
