### ISSUE TITLE
Should specify that UseForwardedHeaders should be placed before UseHttpsRedirection

### ISSUE THREAD

**Issue by carnadso** [dotnet/AspNetCore.Docs#17723]
I just had this happen to a greener colleague. They thought that Configure is somewhat similar to ConfigureServices in that the ordering of statements is less crucial and ended up placing UseForwardedHeaders *after* UseHttpsRedirection.

The documentation already states that UseForwardedHeaders should be placed before UseAuthentication, so I imagine it could also specify that it should be placed before UseHttpsRedirection, even if for some people it's a bit obvious.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @carnadso ... Of course, there's nothing wrong with adding that little tidbit here. It's currently covered in the linked topic ...

> Invoke the `UseForwardedHeaders` method in `Startup.Configure` before calling other middleware:

... where it's placed right at the very top in the example code.

https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer#other-proxy-server-and-load-balancer-scenarios

It should also be changed in the companion Apache topic.

I have a minute here to do the update (I'm off today! lol), so I'll knock this out.

**Comment by carnadso** [comment]
Thanks a bunch for taking the time to work on this!

I know about the other article and I also know that having the correct statement order seems obvious, but there you have it, sometimes -- when feeling slightly overwhelmed by the newness o it all, perhaps -- it's simply not *that* obvious.

Maybe nudging the reader to *really* consider reading the proxy/LB-specific article could also be a good idea? Or letting them know that if they get an infinite redirect loop then maybe they should check that the statement order in Configure is not messed up?

**Comment by guardrex** [comment]
IMO, we shouldn't go further than our standard remark for cross-linked content ... 'for more info, see.' When/where to be pushy and how to word it (e.g., 'for important info, see') would be rather subjective and thus probably not be helpful. *All* of the related guidance is *important* for devs to read and digest. That's why any cross-links is present anywhere in the docs. We're careful to avoid cross-linking irrelevant content.

**Comment by carnadso** [comment]
Got it, thanks for the explanation! It really helps with trying to figure out the tone/scope that's desired for the documentation articles, which I'm still trying to figure for when I ever feel like I can directly contribute with a PR.
