### ISSUE TITLE
Should explain how testCert.crt/testCert.key can be generated

### ISSUE THREAD

**Issue by carnadso** [dotnet/AspNetCore.Docs#17724]
Right now the files are just assumed to be there. There should be a small paragraph/section detailing how to create a self-signed cert if its use is shown in the NGINX config file example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by carnadso** [comment]
I *do* realize that this is somewhat off-topic in regards to the main purpose of the article, as it's more about doing NGINX config work.

So I'm not sure what to suggest about how to approach this as not to go off-topic.
As an aside, I *do* like the way DigitalOcean has such a topic covered (https://www.digitalocean.com/community/tutorials/how-to-deploy-an-asp-net-core-application-with-mysql-server-using-nginx-on-ubuntu-18-04#prerequisites) , but they can just reference other articles that specifically target configuring NGINX .

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Host ASP.NET Core on Linux with Nginx #17735
