### ISSUE TITLE
Middleware Scope operation disagrees between documents

### ISSUE THREAD

**Issue by syndicatedshannon** [dotnet/AspNetCore.Docs#17730]
I think this document and another are in conflict on a salient point. Compare:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-3.1
"Activation per client request (injection of scoped services) ... IMiddleware is activated per client request (connection), so scoped services can be injected into the middleware's constructor."

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1#per-request-middleware-dependencies
"Because middleware is constructed at app startup, not per-request, scoped lifetime services used by middleware constructors aren't shared with other dependency-injected types during each request."

I think this is one of the key points here. I'm going to the source code now, to find out which is actually true, but hopefully the documentation can be cleared up for others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f5eb44-55e5-d4a5-0ab1-5122c29a1db5
* Version Independent ID: 0b8da6a7-8333-5d8f-23a5-05bf0ca661f9
* Content: [Factory-based middleware activation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/extensibility.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Both statements are true, but in different contexts, i.e. whether using the conventional approach (second link) or the factory-based approach (first link).

Perhaps [Per-request middleware dependencies](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1#per-request-middleware-dependencies) could mention and link to [Factory-based middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-3.1).

**Comment by syndicatedshannon** [comment]
@serpent5 Thank you, I'm not positive I follow you. I think I understand, but if so it's surprising.

Do you mean that UseMiddleware<T>() where T : IMiddleware results in a different lifetime than UseMiddleware<T>() where T : object?

If so, I wasn't expecting that at all. I normally prefer to implement interfaces when available for clarity. When a convention approach and interface approach are available, with mostly the same signatures, I don't expect them to behave so differently. What I expected to find was that the convention approach was present entirely to support additional parameters on the invoke method. I can see why someone would have wanted to support more limited scopes for IMiddleware, given the fixed Invoke signature; but still surprising.

Reading the additional links you provided still didn't clarify it for me, unfortunately.

I think the first problem for me is the grammar here on the referenced page. Re-reading the first paragraph "UseMiddleware checks if the middleware... if it does... then the middleware..." multiple times; the phrase "then the middleware" could read "any/all middlewares". I did not read it as "this entire paragraph describes only one type of middleware. Throughout the page, examples of both interface-based and convention-based are given.

So there are three confusing things here, IMO. The behavior, the grammar, and the document layout.

No offense intended, just really having a hard time following.

**Comment by syndicatedshannon** [comment]
Also, I didn't follow that IMiddleware *IS* factory-based activation. I think I have to know that already when I start reading, for the document to be clear.

**Comment by syndicatedshannon** [comment]
Also, I think part of my confusion is that I didn't realize factory approach and conventional approach were mutually exclusive. I understand from experience what is meant when contrasting API surfaces... but when someone asks if I want factories or interfaces my answer may be "yes please".

**Comment by syndicatedshannon** [comment]
And the same confusion on the other document. When it says "Because middleware is constructed at app startup, not per-request", I assumed it meant all middleware in the ASP.NET Core implementation. I didn't find any reason to think that the "Write custom ASP.NET Core middleware" document didn't describe the IMiddleware as well.

Note that I had visited both links, and included them in the initial report, and spent a while trying to de-conflict them mentally before concluding incorrectly they were incompatible. So I don't think just providing a link would have clarified, for me at least.

**Comment by serpent5** [comment]
Another option might be to combine the two topics - they're both small, making a total 6-minute read, although they may be split for a good reason.

That might allow for a better flow from one into the other. @Rick-Anderson What do you think?

**Comment by syndicatedshannon** [comment]
@serpent5 : I know you weren't speaking to me, but I think that would have helped me out. The flow of both documents is already similar, and where they aren't I feel like the information is missing from one or the other.

Alternately if they need to be separate, it would have also helped me to have a "Middleware" guidance, and separate children for factory/interface and conventional implementations, both referring to the parent, with a note in the parent regarding differing behavior.

**Comment by syndicatedshannon** [comment]
Now that I understand the difference, I'm also confused, and would love some guidance added on a concern. I thought that middleware should generally be a singleton anyway, with per-request properties in the Invoke, to avoid ending up with dependency chain initialization running for every request.

Now that I see it's a significant behavioral difference, I'm uncertain about how to implement. I try to avoid premature optimization, but I also generally try to follow guidance. This situation may have left me with a refactor ahead.

**Comment by syndicatedshannon** [comment]
Oh noes! I'm also confused now about possible behavioral differences on UseMiddleware<T>(TDependency). Disaster! LOL.

**Comment by serpent5** [comment]
> Now that I understand the difference, I'm also confused, and would love some guidance added on a concern.

I'm just a contributor here in the docs, so I can't give official guidance. I'll leave it up to @Rick-Anderson to take any necessary action for that.

> I'm also confused now about possible behavioral differences on `UseMiddleware<T>(TDependency)`.

`UseMiddleware<TMiddleware>` throws an exception if `TMiddleware` implements `IMiddleware` and `args` are passed ([source](https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Http/Http.Abstractions/src/Extensions/UseMiddlewareExtensions.cs#L46-L56)). You can also see there in the source how the middleware registration differs when it implements `IMiddleware`.

**Comment by syndicatedshannon** [comment]
@serpent5 TY. Be well.

**Comment by Rick-Anderson** [comment]
> Perhaps [Per-request middleware dependencies](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1#per-request-middleware-dependencies) could mention and link to [Factory-based middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-3.1).

Let's go with that.

**Comment by syndicatedshannon** [comment]
@Rick-Anderson : It may be irrelevant to your decision, but another link probably wouldn't have helped me through the issue I reported, since I had found both documents, and merely found them to conflict.
