### ISSUE TITLE
Chrome issues with logged in user

### ISSUE THREAD

**Issue by mouleja** [dotnet/AspNetCore.Docs#17737]
Just a note- I was not able to complete steps initially because I kept getting to a screen with 'Couldn't sign you in -&gt; This browser or app may not be secure.' message when using Chrome.  Oddly it worked with Firefox.  After a bit of digging, it turned out the issue was that I couldn't sign in with my Google id because I had another Chrome window open that I was already signed in to.  I could open the app (localhost:xxxxx) in a new tab on that window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
THanks for the info.
