### ISSUE TITLE
DI in code-behind constructor?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/AspNetCore.Docs#17747]
Hi,

When using C# 8 nullable references, the compiler isn't aware of the injection and issues warnings for those properties.
Current workaround is:
```c#
[Inject]
[SuppressMessage("Compiler", "CS8618")]
protected AppDbContext DbContext { get; set; }
```

But I was hoping for a less verbose way of achieving this.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce9457c7-13d4-1520-790c-a18187532ff4
* Version Independent ID: 43f87dbb-2f36-c91e-084c-c28d93da923f
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @weitzhandler ... best to ask about that one on the engineering repo. Open it at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your issue so that I can follow the discussion.

**Comment by weitzhandler** [comment]
Done: https://github.com/dotnet/aspnetcore/issues/20776.
