### ISSUE TITLE
Encryption at rest section seems to be out of place

### ISSUE THREAD

**Issue by sergy2k** [dotnet/AspNetCore.Docs#17742]
Why is there an 'Encryption at rest' section in on this page? How does it relate to the 'EU General Data Protection Regulation (GDPR) support in ASP.NET Core'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.1#encryption-at-rest
