### ISSUE TITLE
Documentation about ModelStateDictionary.AddModelError

### ISSUE THREAD

**Issue by derth** [dotnet/AspNetCore.Docs#17744]
Trying to find documentation about ModelState.AddModelError(), but can't find anything, except the .net api docs.
I can find usage of it in sample projects, but not official docs for it. Can you point me to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#custom-client-side-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Here's some examples
* https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/handling-concurrency-with-the-entity-framework-in-an-asp-net-mvc-application#modify-department-controller
* https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing
* https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests
