### ISSUE TITLE
We could use EnsureCreatedAsync using async Main

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/AspNetCore.Docs#17749]
In .NET Core &gt; 2.1, `async Task Main` can be used instead, then `EnsureCreatedAsync` could be used.

I find it really important to point that out in the docs, because many people are looking for ways to initialize post-build app stuff, that are many times asynchronous.

[Here](https://stackoverflow.com/a/61166934/75500)'s an example question in SO.

Created PR #17750. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#update-main)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`EnsureCreatedAsync` is not suitable for production apps.

**Comment by weitzhandler** [comment]
Can you please explain?

**Comment by Rick-Anderson** [comment]
@ajcvickers please review. We should probably update the doc's with best practice.

**Comment by ajcvickers** [comment]
@Rick-Anderson @weitzhandler As part of the [plan for EF Core 5](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/plan#migrations-and-deployment-experience), we are investigating better experiences for migrating the database that don't involve running migrations from code--see https://github.com/dotnet/efcore/issues/19587. This will likely result in something like "migration bundles" that can easily be deployed at the same time as the database. We also have https://github.com/dotnet/efcore/issues/20402 which is about integrating this into something like the ASP.NET Core error page middleware.

With regard to the associated PR, the async change is probably marginally better than what we have now, but we need to revisit this after we have got further along the bundles path.

/cc @JeremyLikness @bricelam

**Comment by bricelam** [comment]
Async doesn't really help in this situation. The application isn't accepting requests at this point. There is effectively only one thread running and yielding will probably only make it take longer to start up and begin accepting requests.
