### ISSUE TITLE
Issue injecting a service using DI into a class that inherits from Hub

### ISSUE THREAD

**Issue by MagicPelikan** [dotnet/AspNetCore.Docs#17745]
Hi everyone. I'm using asp net core 3.1 but I can't inject a service into a class that inherits from Hub.
I have something like:
```
public class MyHub : Hub
{
	private IMyCustomService _myCustomService;
		
	public MyHub(IMyCustomService myCustomService)
	{
		_myCustomService = myCustomService;
	}
	
	
public async Task SendMessage(string user, string message)
	{
		// I want to do something here with _myCustomService...
		
		_myCustomService.Method(....);
		
		await Clients.All.SendAsync("ReceiveMessage", user, message);
	}
}
```
Then in my Startup.cs I have something like:
```
public void ConfigureServices(IServiceCollection services)
{
	...
	services.AddSignalR();
	...
}


public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
	...
	endpoints.MapHub<MyHub>("/testHub");
	...
}
```

I'm getting this error:
**System.InvalidOperationException: A suitable constructor for type 'BlazorSignalRApp.Server.Hubs' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.**

I feel I'm missing something when DI is trying to create an instance of MyHub but I can't figure out what ?

Thanks a lot for your help and stay home please :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Have you added a `IMyCustomService` type into DI?
https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#service-registration-methods

**Comment by MagicPelikan** [comment]
Hi Brennan. No, I have not. But after reading now my initial post I found out I made a mistake posting the example code.
The code that it's actually throwing the error is:

```
public class MyHub : Hub
{
	private IMyCustomService _myCustomService;
		
	MyHub(IMyCustomService myCustomService)
	{
		_myCustomService = myCustomService;
	}
	
	// This method is invoked from the SignalR Client
	public async Task SendMessage(string user, string message)
	{
		// I want to do something here with _myCustomService...
		
		_myCustomService.Method(....);
		
		await Clients.All.SendAsync("ReceiveMessage", user, message);
	}
}
```

I removed the **public** keyword in front of ```MyHub(IMyCustomService myCustomService)``` because when I put **public** I got an error from the VS intellisense saying: 
**Inconsistent accessibility: parameter type 'IMyCustomService' is less accessible than method 'MyHub.MyHub(IMyCustomService)'**

So I think I should fix that error first, right ? I know the error comes from how I'm coding the app but I've been hours tying to find out where it is. Any help will be greatly appreciated!

**Comment by BrennanConroy** [comment]
You should probably fix both errors

**Comment by MagicPelikan** [comment]
Working on it...

**Comment by MagicPelikan** [comment]
After I clear my head today doing other stuff I just sat down in front of the computer and I discovered the error. I fixed it and everything started to work like a charm!

The error was that I missed to make **public** the interface in my custom service...
Thank you Brennan for your time yesterday anyway :)

**Comment by NB250102** [comment]
> I fixed it and everything started to work like a charm!
> 
> The error was that I missed to make **public** the interface in my custom service...

I forgot to make constructor of the custom service public, so this helped me figure that out, thank you!
