### ISSUE TITLE
Getting nested config values from KeyVault fails.  

### ISSUE THREAD

**Issue by robcamer** [dotnet/AspNetCore.Docs#17748]
I am using the sample code in my app.  For nested configuration sections that I put into KeyVault with the '--' instead of ':' fail to load when managed as a config section in the app.  I found I had to add "builder.build()" a second time after loading the KeyVault secrets.  My code is below.  Note the addition of builder.build() at the end after configuring Key Vault:

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
Host.CreateDefaultBuilder(args)
.ConfigureWebHostDefaults(webBuilder =>
{
webBuilder.UseStartup<Startup>();
})
.ConfigureAppConfiguration((context, builder) =>
                {
                    var builtConfig = builder.Build();
                    if (context.HostingEnvironment.IsProduction())
                    {
                        var azureServiceTokenProvider = new AzureServiceTokenProvider();
                        var keyVaultClient = new KeyVaultClient(
                            new KeyVaultClient.AuthenticationCallback(
                                azureServiceTokenProvider.KeyVaultTokenCallback));

                        builder.AddAzureKeyVault(
                            $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                            keyVaultClient,
                            new PrefixKeyVaultSecretManager(builtConfig["EnvPrefix"]));
                        builder.Build();
                    }
                });
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@robcamer  I clean up your code a bit, can you check it. You can't enter code from the doc page, that needs to be done on GitHub or replaces `>`  with the HTML encoded version `&gt;
`
Code needs to be code fenced

**Comment by scottaddie** [comment]
@robcamer If I understand correctly, your hierarchical keys aren't being loaded. Have you tried using the following `AddAzureKeyVault` call instead of what you have?

```csharp

                        builder.AddAzureKeyVault(
                            $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                            keyVaultClient,
                            new DefaultKeyVaultSecretManager());
```

`DefaultKeyVaultSecretManager` automatically replaces `--` with `:`. See https://github.com/Azure/azure-sdk-for-net/blob/84c629c08a3cff748b48585d1c816dd2a8194d5f/sdk/extensions/Azure.Extensions.Configuration.Secrets/src/KeyVaultSecretManager.cs#L24.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as we have heard no response from you for some time now. If you have more details and are encountering this issue please add a new reply and re-open the issue.
