### ISSUE TITLE
Invalidate Cache on new data

### ISSUE THREAD

**Issue by AndiRudi** [dotnet/AspNetCore.Docs#17752]
Hi, i tried to find more information on how to invalidate the response cache when underlaying data has changed. The link to change tokes is very interesting but I didn't get if it is possible to use change tokens to invalidate the cache on a GET call when a new POST/PATCH/PUT call was made or the data changed in any other way. Some pages I found mention this is not possible. Maybe a note about how this works would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo can you please provide some writeup for this? Thanks!

**Comment by JunTaoLuo** [comment]
This is not possible with the current API. A feature request should be filed instead.
