### ISSUE TITLE
dotnet dev-certs https --trust will fail on Linux platform

### ISSUE THREAD

**Issue by shukebeta** [dotnet/AspNetCore.Docs#17761]
At least on Unbuntu 18.04, dotnet dev-certs https --trust will fail on a message "Specify --help for a list of available options and commands." 

you could see &lt;https://stackoverflow.com/questions/55485511/how-to-run-dotnet-dev-certs-https-trust&gt; to get more detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per doc
dotnet dev-certs https --trust is only supported on macOS and Windows. You need to trust certs on Linux in the way that is supported by your distro.
