### ISSUE TITLE
Unable to connect to SignalR hub from some other client apllication

### ISSUE THREAD

**Issue by sravanithamatamqualbrain** [dotnet/AspNetCore.Docs#17765]
Hi Team, 

In the example that you have given is for local SignalHub.

if SignalHub application and client application are in different projects and when signalr application is hosted and when we tried to connect to SignalR hub from client application, i am facing some issues related to cors policy and signalr.map is not loaded. And i am unable to connect to hosted signalR hub. 

please provide me a example where i can connected to signalR hub remotely from client apllication.

Thank you
Sravani Thamatam

**Comment by BrennanConroy** [comment]
Read up on [CORS in SignalR](https://docs.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-3.1#cross-origin-resource-sharing) to resolve CORS issues.

> signalr.map is not loaded

What errors are you getting?

**Comment by sravanithamatamqualbrain** [comment]
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sravanithamatamqualbrain** [comment]
The above error i am getting.

please help me.

**Comment by BrennanConroy** [comment]
Did you read the doc I linked? It should help you resolve the CORS error.

**Comment by sravanithamatamqualbrain** [comment]
Yes i read that page. But it couldn't help me.

**Comment by BrennanConroy** [comment]
Share your code on the server that's setting up CORS

**Comment by sravanithamatamqualbrain** [comment]
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
                options.AddDefaultPolicy(builder => builder
                .WithOrigins("http://localhost:57223/")
                .AllowAnyHeader().AllowAnyMethod()));
        

        services.AddRazorPages();
            services.AddSignalR();

            
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCors();
            app.UseRouting();

            

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<ChatHub>("/chathub");
                endpoints.MapRazorPages();
            });
        }
}

**Comment by sravanithamatamqualbrain** [comment]
This is the code that is written in Startup.cs file of SignalR application server.

**Comment by BrennanConroy** [comment]
Remove the trailing "/" in `.WithOrigins("http://localhost:57223/")`
And add `.AllowCredentials()` to your CORS options

**Comment by sravanithamatamqualbrain** [comment]
Sure. I will do that.

**Comment by sravanithamatamqualbrain** [comment]
Still i am facing the same issue.

**Comment by sravanithamatamqualbrain** [comment]
services.AddCors(options =>
                options.AddDefaultPolicy(builder => builder
                .WithOrigins("http://localhost:57223")
                .AllowAnyHeader().AllowAnyMethod()
                .AllowCredentials()));

**Comment by BrennanConroy** [comment]
Place `UseCors()` above the other middleware
```c#
app.UseCors();
app.UseHttpsRedirection();
app.UseStaticFiles();
```

**Comment by sravanithamatamqualbrain** [comment]
Okay

**Comment by sravanithamatamqualbrain** [comment]
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
                options.AddDefaultPolicy(builder => builder
                .WithOrigins("http://localhost:57223")
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials()));
           services.AddRazorPages();
            services.AddSignalR();

            
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseCors(builder =>
            {
                builder.WithOrigins("http://localhost:57223")
                    .AllowAnyHeader()
                    .AllowCredentials();
            });
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            
            app.UseRouting();

            

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<ChatHub>("/chathub");
                endpoints.MapRazorPages();
            });
        }
    }

**Comment by sravanithamatamqualbrain** [comment]
Still same issue.

**Comment by BrennanConroy** [comment]
Why did you change your `UseCors` method to use the builder? If you're going to do that, then you need to have `AllowAnyMethod()` or `WithMethods("GET", "POST")`.

**Comment by sravanithamatamqualbrain** [comment]
@page
<div class="container">
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-2">User</div>
        <div class="col-4"><input type="text" id="userInput" /></div>
    </div>
    <div class="row">
        <div class="col-2">Message</div>
        <div class="col-4"><input type="text" id="messageInput" /></div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-6">
            <input type="button" id="sendButton" value="Send Message" />
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-6">
        <ul id="messagesList"></ul>
    </div>
</div>
<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>
<script src="https://localhost:44390" type="text/javascript"></script>

**Comment by sravanithamatamqualbrain** [comment]
"use strict";

var connection = new signalR.HubConnectionBuilder().withUrl("http://localhost:57223").build();

//Disable send button until connection is established
document.getElementById("sendButton").disabled = true;

connection.on("ReceiveMessage", function (user, message) {
    var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    var encodedMsg = user + " says " + msg;
    var li = document.createElement("li");
    li.textContent = encodedMsg;
    document.getElementById("messagesList").appendChild(li);
});

connection.start().then(function () {
    document.getElementById("sendButton").disabled = false;
}).catch(function (err) {
    return console.error(err.toString());
});

document.getElementById("sendButton").addEventListener("click", function (event) {
    var user = document.getElementById("userInput").value;
    var message = document.getElementById("messageInput").value;
    connection.invoke("SendMessage", user, message).catch(function (err) {
        return console.error(err.toString());
    });
    event.preventDefault();
});

**Comment by sravanithamatamqualbrain** [comment]
this is client code.

**Comment by BrennanConroy** [comment]
> Access to XMLHttpRequest at 'http://localhost:57223/negotiate?negotiateVersion=1' from origin 'http://localhost:57606'

Ok, here's your issue, the client is at origin "http://localhost:57606", so that's the URL you need to use in `WithOrigins(...)`

**Comment by sravanithamatamqualbrain** [comment]
Failed to load resource: 57223/negotiate?negotiateVersion=1:1 
responded with a status of 404 (Not Found)

**Comment by sravanithamatamqualbrain** [comment]
Now this issue is coming.

**Comment by BrennanConroy** [comment]
Your client needs to be pointing at the hub which is at "/chathub"
So: `var connection = new signalR.HubConnectionBuilder().withUrl("http://localhost:57223/chathub").build();`

**Comment by sravanithamatamqualbrain** [comment]
<img width="960" alt="Error" src="https://user-images.githubusercontent.com/61418209/79099051-ef29c780-7d80-11ea-9d20-52ed91560b0a.PNG">

**Comment by sravanithamatamqualbrain** [comment]
Issue is resolved. 

Thank you thank you very much @BrennanConroy.
