### ISSUE TITLE
Blazor client app- accessing the users token for onward api calls

### ISSUE THREAD

**Issue by AlexSapple** [dotnet/AspNetCore.Docs#17760]
Hi guys, 

another great page of information - but just one point (and I might be being really silly) - but the reference to 

var tokenResult = await AuthenticationService.RequestAccessToken(); 

in order to get hold of the token and add to http headers in onward API calls - where is this library? when firing up a pure client blazor template from VS - this library doesn't appear to be included and I'm not sure what the namespace is (I can find - Microsoft.AspNetCore.Authentication namespace, but that doesn't appear to have the method RequestAccessToken()). It might be just an extra 1 liner in this document to clarify that.

thanks very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by ferguson-eric** [comment]
Hi AlexSapple,

In your razor page, you will need:
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@inject IAccessTokenProvider AuthenticationService

In your _Imports.razor file, you will also need:
@using Microsoft.AspNetCore.Components.Authorization

**Comment by AlexSapple** [comment]
Hi @ferguson-eric 

thanks for the info - that does indeed do the trick (although I'm only getting null for the actual token). I've forgotten how to do much of this but I think I need to tell something somewhere to cache or make it locally available. In any case, the original question is answered, so thanks very much.
