### ISSUE TITLE
Tracking Tip

### ISSUE THREAD

**Issue by HamidMolareza** [dotnet/AspNetCore.Docs#17764]
Why _AsNoTracking()_ method not used in [Loading related data with Select](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.1&tabs=visual-studio-code#loading-related-data-with-select)?

Can say it's because of the following reason?

> If the result set doesn't contain any entity types, then no tracking is done.

If yes, I think it's better to mention this as a tip. Because it can be confusing for **beginners**.
(Can i create a PR?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We already mention 
`AsNoTracking ` improves performance because the entities returned are not tracked

I can help you find some PR's if you'd like. Most open issues you're welcome to work on. If it's assigned to someone and scheduled for the current sprint (April 2020 currently), check with me.

**Comment by Rick-Anderson** [comment]
cc @tdykstra

**Comment by HamidMolareza** [comment]
@Rick-Anderson 
It has already been explained why `AsNoTracking` is used, But it is not clear why it was **not used**.

In the [previous section](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.1&tabs=visual-studio-code#display-the-department-name), `AsNoTracking` is used and the reason is well mentioned. But in this section, **without mentioning the reason**, `AsNoTracking` has been removed. I think it can be confusing or questionable for beginners.

I mean, it's a good idea to provide a link to [this address](https://docs.microsoft.com/en-us/ef/core/querying/tracking) so that the audience better understands **when to use it and when not**. specially [this section](https://docs.microsoft.com/en-us/ef/core/querying/tracking#tracking-and-custom-projections).
