### ISSUE TITLE
More context needed for Razor component integration

### ISSUE THREAD

**Issue by besdsol** [dotnet/AspNetCore.Docs#17771]
This article has a lot of inatructions, but assumes too much context many or even most readers will not have. The impression from an experienced developer familiar with the content is still to wonder what this article is talking about till right at the end.

It could benefit from adding the why to the what.

One specific example is it talks about adding a razor component to a page, but it's not really clear this means a server side Blazor component. This is additionally confusing because the terms have been renamed through the release cycle, and both 'razor' and 'component' are used to mean various things in asp.net both current and past. Adding some preamble and additional context explaining why you would do this, will help the reader infer what the article is about earlier/at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @besdsol ... Of course, we can't do much about ...

> 'razor' and 'component' are used to mean various things in asp.net both current and past

... that's true and a bit painful from time-to-time.

I'll work on your suggestion. Thanks again, and I'll ping you on the PR. Given the workload right now for 3.2, I should be able to get to this after the 3.2 release, which is scheduled for May.

**Comment by guardrex** [comment]
> to wonder what this article is talking about till right at the end.

Not sure about that, as the article says what it's about in the very first sentence ...

> Razor components can be integrated into Razor Pages and MVC apps. 

**_BUT_**, I agree that there's no context for the following sections. Basically, one has to *prepare* the app (with that section's content), then *decide* if they want to just use a component in a page/view (and follow the guidance in that section) **OR** if they want to have routable components that can be reached directly (and follow the guidance in that section) ... or both.

The opening remarks don't *orient* the reader as to what the options are for using components in pages/views and then link down to the relevant sections.

Actually, I'll probably get to this one well before May. It's a quicky-ish one.
