### ISSUE TITLE
PDF export of Microsoft .NET documentation doesn't generate code colorization

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#17779]
## PDF export of the .NET documentation doesn't colorize highlighted portions of code:
![No syntax highlighting - 0](https://user-images.githubusercontent.com/9283914/79171816-55e7c900-7df3-11ea-92ca-e96b9f072761.png)

![No syntax highlighting - 1](https://user-images.githubusercontent.com/9283914/79171554-a4e12e80-7df2-11ea-94d5-ab399855dd1a.png)

#### Comparison between PDF and HTML output:
![No syntax highlighting - 2](https://user-images.githubusercontent.com/9283914/79171557-a579c500-7df2-11ea-9847-fce6aa3621c4.png)
<br/>

So, reading the docs offline it's hard to grasp the important parts of changed code.
<br/>

NB: This issue is not about full code colorization, but only about colorizing the highlighted portions of code:

### Current PDF Result
![No syntax highlighting - 4a](https://user-images.githubusercontent.com/9283914/79172290-93008b00-7df4-11ea-9ebb-baf13607d897.png)

### Expected PDF Result
![No syntax highlighting - 4b](https://user-images.githubusercontent.com/9283914/79172291-93008b00-7df4-11ea-8a97-60781774e60f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-getstarted**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks. This [has been reported](https://github.com/MicrosoftDocs/feedback/issues?q=is%3Aissue+is%3Aopen+PDF)

**Comment by SetTrend** [comment]
@Rick-Anderson : None of the issues in the list you pointed to deals with colorization.

**Comment by Rick-Anderson** [comment]
Can you create one in that repo? That's where it needs to be reported.

**Comment by SetTrend** [comment]
Sure. Thanks for pointing me to that repo. I created a corresponding issue there.
