### ISSUE TITLE
CREATE DATABASE failed.

### ISSUE THREAD

**Issue by LeeRossCritchlow** [dotnet/AspNetCore.Docs#17776]
CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\LeeRazorPagesMovieContext-51805274-cb93-467f-914b-ab2b210a09f3.mdf'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See #6837 #8446 and [this](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+%22CREATE+FILE+encountered+operating+system+error%22)

**Comment by LeeRossCritchlow** [comment]
> 
> 
> CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\LeeRazorPagesMovieContext-51805274-cb93-467f-914b-ab2b210a09f3.mdf'.
> #### Document Details
> 
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
>     * ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
> 
>     * Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
> 
>     * Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio#feedback)
> 
>     * Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
> 
>     * Product: **aspnet-core**
> 
>     * Technology: **aspnetcore-tutorials**
> 
>     * GitHub Login: @Rick-Anderson
> 
>     * Microsoft Alias: **riande**

problem was fixed by https://support.microsoft.com/en-us/help/4342123/cumulative-update-10-for-sql-server-2017

**Comment by Rick-Anderson** [comment]
@LeeRossCritchlow  thanks for the update.

**Comment by PiotrBitner** [comment]
"LocalDB is not supported on this platform on Mac". After dotnet ef database update. How to run sample on Mac?

**Comment by hcovitz** [comment]
![image](https://user-images.githubusercontent.com/8238705/121613536-f21e5780-ca19-11eb-9b9e-0f4ec3819cec.png)
Running as Administrator.

![image](https://user-images.githubusercontent.com/8238705/121613612-1b3ee800-ca1a-11eb-8e0d-afeb07f97760.png)
