### ISSUE TITLE
Error on AuthorizationService

### ISSUE THREAD

**Issue by alij** [dotnet/AspNetCore.Docs#17772]
I am using asp.net core 3.1.

In the example above the JwtClaimTypes.Role, VS says JwtClaimTypes does not exist in current context and I couldn't find any reference for it. Using just ClaimTypes.Role though seemed to work but I get the following error at runtime:

InvalidOperationException: No policy found: IsAdmin.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, object resource, string policyName)
Sampql.Pages.Shared.Pages_Shared__LoginPartial.ExecuteAsync() in _LoginPartial.cshtml

@if ((await AuthorizationService.AuthorizeAsync(User, "IsAdmin")).Succeeded)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Try ...

```csharp
using IdentityModel;
```

**Comment by alij** [comment]
Well, didn't need IdentityModel as I could use ClaimsTypes.Role defined in System.Security.Claims. However, for the other error I needed to add the "IsAdmin" policy in ConfigureServices. This should perhaps be mentioned. I am adding it below:

            services.AddAuthorization(options =>
                {
                    options.AddPolicy("IsAdmin",
                         policy => policy.RequireRole("admin"));
                });

**Comment by DenisMtfl** [comment]
Hello, i have added the code from @alij but my code seems not working. No error but when i have IsAdmin setted to 'true' no Successded with the code below.

`@if ((await AuthorizationService.AuthorizeAsync(User, "IsAdmin")).Succeeded)`

anyone a idea why it is not working?

**Comment by DenisMtfl** [comment]
So i found a solution, this is working but not with _RequireRole_ ?!

`options.AddPolicy("IsAdmin", policy => policy.RequireClaim("role", "admin"));`
