### ISSUE TITLE
WriteResponseBodyAsync is wrong for 3.1

### ISSUE THREAD

**Issue by PeterWone** [dotnet/AspNetCore.Docs#17788]
The last line of the method reads
```
await response.WriteAsync(buffer.ToString());
```

but `Microsoft.AspNetCore.HttpResponse` does not have a WriteAsync method. 

It _does_ have a property `Body` which has a WriteAsync method but this does not have a signature supporting a string parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The code works. Must be an extension method your missing.

cc @scottaddie

**Comment by serpent5** [comment]
This requires `using Microsoft.AspNetCore.Http;` for the [extension method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponsewritingextensions.writeasync?view=aspnetcore-3.1#Microsoft_AspNetCore_Http_HttpResponseWritingExtensions_WriteAsync_Microsoft_AspNetCore_Http_HttpResponse_System_String_System_Threading_CancellationToken_).

**Comment by PeterWone** [comment]
I just went through the article again and couldn't see any mention of the requirement for `using Microsoft.AspNetCore.Http`. Don't you think it would be appropriate to put a comment in the code?

```

**Comment by Rick-Anderson** [comment]
That's a change that will be picked up by #16486
