### ISSUE TITLE
Should differentiate between Microsoft work vs microsoft personal accounts

### ISSUE THREAD

**Issue by timrobinson33** [dotnet/AspNetCore.Docs#17787]
It's not clear whether the term "Microsoft account" refers to a work account, a personal account, or whether it works with both. Even if it does work with both, it's worth being explicit about that fact because developers are used to having to distinguish between them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It works for both. To test it, most developers use personal account.

cc  @Tratcher 

I could add:

To test it with your Microsoft personal account, select personal account.

But I thought that was too obvious.

**Comment by Tratcher** [comment]
Clarification: "This sample shows you how to enable users to sign in with their work, school, or personal Microsoft account using the ASP.NET Core 3.0 project created on the previous page."

**Comment by Rick-Anderson** [comment]
@Tratcher thanks. Fixed in #17800
