### ISSUE TITLE
How to create a gRPC server with explicitly defined parameters? 

### ISSUE THREAD

**Issue by pawelpetruch** [dotnet/AspNetCore.Docs#17789]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio doesn't show how to create a server with explicit parameters like IPAddress and port we want the server to listen on. 

In Grpc.Core you can create a server with a set of parameters like Services and Ports which is very convenient. Also being given an instance of a server allows you to start / stop it. 

I assume the same functionality is implemented in Grpc.Net but not documented at all. Therefore, any docs on that matter would be hugely beneficial.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
