### ISSUE TITLE
Client side?

### ISSUE THREAD

**Issue by JasOcher** [dotnet/AspNetCore.Docs#17784]
An HttpClient PatchAsync requires HttpContent, so you're going to have to wrap it up to send it over.  This solution and PatchAsync don't seem to really jive with one another, so what does the client side look like for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Tracked in JsonPatch Master issue. Look here #18330
