### ISSUE TITLE
Blazor WASM with Auth Lib groups and roles

### ISSUE THREAD

**Issue by ferguson-eric** [dotnet/AspNetCore.Docs#17790]
**EDIT by guardrex:** This is a companion issue to https://github.com/dotnet/AspNetCore.Docs/issues/17660 and https://github.com/dotnet/AspNetCore.Docs/issues/17683.

Is it possible for roles to be mapped to claims and used against the authorization attribute (e.g., [Authorize("Admin")])? This is possible in other non AddOidcAuthentication implementations by first assigning the claims via IClaimsTransformation, then doing something similar to https://visualstudiomagazine.com/articles/2019/10/29/aspnet-authentication.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ferguson-eric ... *Yes!* ... but I haven't worked on the experience yet for the base Auth Library topic. I only have the Azure AD experience at this time on https://github.com/dotnet/AspNetCore.Docs/issues/17660. I'll be working that one very soon.

Let's leave this issue open, and I'll use it to work this particular topic for this scenario.

Basically tho ... WRT the issue itself ... you should just need to get your auth provider to furnish a `roles` claim. It should ✨ **_Just Work!_**:tm: ✨ after that.

If you need to manually work with the claims, then you can create a custom `AuthenticationStateProvider` (see https://docs.microsoft.com/aspnet/core/security/blazor/#implement-a-custom-authenticationstateprovider). In fact, that example there would be the basis of a quick-'n-dirty test for a `roles` claim just to make sure that the auth behavior of the auth state provider is correct for the approaches that the topic covers, such as with the `AuthorizeView` component, the `[Authorize]` attribute, and `IsInRole` (`Task<AuthenticationState>`), which are all covered there.

Note btw tho that the format is a bit different than what you posted. See :point_right: https://docs.microsoft.com/aspnet/core/security/blazor/#authorize-attribute

**Comment by guardrex** [comment]
@ferguson-eric Have a look at the following examples to get started with it ...

* https://github.com/dotnet/AspNetCore.Docs/issues/17649
* https://github.com/dotnet/AspNetCore.Docs/issues/17660#issuecomment-616710615

If you read the whole #17660 issue and the current live docs, you'll see that once you get role(s) into one or more `roles` claims that the app will pick that up for things like ...

* `<AuthorizeView Roles="customrole">`
* `@attribute [Authorize(Roles = "customrole")]`
* `if (user.IsInRole("customrole")) { ... }`

I'm going to close this one now and work on it from the #17649 issue (and for AAD from the #17660 issue).
