### ISSUE TITLE
MVC - Run the app section does not cover how to run the app in Linux v2

### ISSUE THREAD

**Issue by spectrumcomputing** [dotnet/AspNetCore.Docs#17794]
Sorry to raise this again, but when I logged it last time under https://github.com/dotnet/AspNetCore.Docs/issues/17688 the ticket was closed

The guide does not show how to run the app in Linux.  The reply I got was 'Per the doc
dotnet run' however this is not in the document.  I know its shown in other MS Beginner Guides, but if someone is coming straight to this page they will struggle. 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The instructions work if you've followed the VSC set up. If you can't get VSC setup, use `dotnet run`.
