### ISSUE TITLE
Improve Docs about identity server

### ISSUE THREAD

**Issue by gilmishal** [dotnet/AspNetCore.Docs#17798]
I came across these docs from another github issue that was closed about identity with web apis being a bit confusing and I would like to add a bit about it.

This page does an excellent job of explaining how to get started with an angular web api app, and how to set everything up from the beginning - *if* I am indeed starting from scratch.

However, this page's title, and how it is structured makes it very confusing if I come with a different, very related usecase.

This title title makes it hard to find if I want API authorization for mobile apps, even though everything stated here is perfectly useful for mobile apps - a better title, would be identity with ASP.NET Core Web API. This would have been forgivable had there been a decent documentation about Identity with Asp.Net Core Web API, but this is as close as it gets.

The second issue is that if I come across this after I had created my web app, without scaffolding - this tutorial is extremely unhelpful. Sure, I can copy paste everything displayed - but I feel that the explanation is poor (why would I need a DefaultUI in a web api?), and some of these lines of code require NuGet packages that I am not sure where to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Great feedback. Moved to master issue: Authentication and authorization for SPAs #16406
