### ISSUE TITLE
How can I request a token after login?

### ISSUE THREAD

**Issue by luisbecerril-ips** [dotnet/AspNetCore.Docs#17795]
I would like to know how can a token be requested after logging in. On the 'Additional Scenarios' webpage 
https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#request-additional-access-tokens there are instructions on how to retrieve a token, however I am unsure whether this applies to the current article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c712850b-27d8-58a6-5fed-da7eb832f51e
* Version Independent ID: 1454a434-3f05-d0cc-2d59-405fef19cef0
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Microsoft Accounts](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-microsoft-accounts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @luisbecerril-ips ... Yes, it applies ... I placed it in this TOC node for that purpose. However, I think an *Additional resources* section in each of these topics with a link to that topic would make it clear that it applies.

Leave this open ... this issue will close when the PR merges.

Thanks for writing in on this.

**Comment by luisbecerril-ips** [comment]
Glad to know that, a follow up question would be, how do I get an instance of the `AuthenticationService` specified? It is stated that this is an overload of the `IAccessTokenProvider.RequestToken` however, at least from the default template that was created when creating the Blazor WebAssembly project and adding the MSAL authentication I cannot get a new instance of such object. Am I missing some assembly reference i.e. NuGet Package?

**Comment by guardrex** [comment]
I need to provide the namespace, and someone just asked me about that recently. IIRC, it's on another issue due to be worked in the coming hours/days. It appears in the *Overview* topic up above this, but we need it down here, too ...

```razor
@using Microsoft.AspNetCore.Components.Authorization
```

I'll get it in on the other issue or this one ... *whichever issue I work first*. :smile:
