### ISSUE TITLE
IE 11 does not fully support `MessagePack` serialization

### ISSUE THREAD

**Issue by udlose** [dotnet/AspNetCore.Docs#17809]
[This document](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1) says that IE 11 is supported.  However, there is a caveat - according to 
[](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-3.1#hubs) 

> Older browsers must support XHR level 2 to provide MessagePack protocol support.

And [XMLHttpRequest advanced features](https://caniuse.com/#feat=xhr2), the `MessagePack` serialization type is not supported by IE11.  

**I just think this should be explicitly called out.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#javascript-client)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
IE 11 supports XMLHttpRequest advanced features. Are you seeing an issue when using IE 11 and MessagePack? I just checked and it's working fine.

**Comment by udlose** [comment]
TBH, I was going off of all of the documentation I referenced. I have not explicitly tried it. If this is truly working, I am fine closing it.

**Comment by BrennanConroy** [comment]
Well, the link you provided for XMLHttpRequest advanced features states that IE 11 does provide support except for the json response type, which is not being used.
