### ISSUE TITLE
Add AsNoTracking to Course-Edit page

### ISSUE THREAD

**Issue by HamidMolareza** [dotnet/AspNetCore.Docs#17807]
Why `AsNoTracking` not used in `OnGetAsync` at [Update the Course Edit page model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-3.1#update-the-course-edit-page-model)?

Isn't it better to add? Like _Detail_ and _Delete_ page.

(I have more experience with MVC than Razor, so sorry if I missed a point.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The EF is the same for Razor Pages and MVC. 

This tutorial isn't optimal use of each API, but if obviously should use `AsNoTracking` we should update the doc.

**Comment by Rick-Anderson** [comment]
Updated in RP version.
