### ISSUE TITLE
Any browsers other than IE supported?

### ISSUE THREAD

**Issue by udlose** [dotnet/AspNetCore.Docs#17802]
Documentation on [Differences between ASP.NET SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#differences-on-the-client) says:

_Internet Explorer support - ASP.NET Core SignalR requires Microsoft Internet Explorer 11 or later (ASP.NET SignalR supported Microsoft Internet Explorer 8 and later)._

Are any browsers, other than Internet Explorer, supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
> Are any browsers, other than Internet Explorer, supported?

Yes
https://docs.microsoft.com/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1

**Comment by udlose** [comment]
Then this Documentation needs to change:

[Differences between ASP.NET SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#differences-on-the-client)

**Comment by BrennanConroy** [comment]
Maybe it could be reworded to not say "**requires** Microsoft Internet Explorer 11".

"ASP.NET Core SignalR can run on Microsoft Internet Explorer 11 or later whereas ASP.NET SignalR supported Microsoft Internet Explorer 8 and later."

**Comment by udlose** [comment]
But both of those comments _could_ imply that again only IE is supported.  I'd be happy if someone changed the docs to point to [ASP.NET Core SignalR supported platforms - JavaScript Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#javascript-client)

**Comment by udlose** [comment]
@BrennanConroy has this been deployed to PROD?  I assume not yet.  The docs still say:

> ASP.NET Core SignalR requires Microsoft Internet Explorer 11 or later (ASP.NET SignalR supported Microsoft Internet Explorer 8 and later).

If this was deployed, then it is still misleading by saying IE is *required*

https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#internet-explorer-support

**Comment by BrennanConroy** [comment]
> has this been deployed to PROD

Probably not.

If you want to see what it says you can look at the change https://github.com/dotnet/AspNetCore.Docs/commit/98ccdaa1dfa6bafa27d2b9d8991db1fdd6c780e6

**Comment by udlose** [comment]
just for my own knowledge, what is the deployment schedule for docs? so i don't have to ask this silly question in the future :)
