### ISSUE TITLE
Scaleout for Asp.Net SignalR (not Core)

### ISSUE THREAD

**Issue by klioqc** [dotnet/AspNetCore.Docs#17825]
The doc contains:
&gt;&gt;Scaleout differences
&gt;&gt;ASP.NET SignalR supports SQL Server and Redis. ASP.NET Core SignalR supports Azure SignalR Service and Redis.

Why Azure SignalR Service is only mentioned for ASP.NET Core, if ASP.NET version also works with Azure SignalR service? Is there some  difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Azure SignalR Service supports both flavors of SignalR. It will **not** translate between the two - if you're running Framework you can't bounce messages to Core, and vice-versa, through the service, but as long as both the server and the client are talking **either** Core or Framework, it will work. 

Is there something we can do to the docs to make this more evident? If not, can this issue be closed?
