### ISSUE TITLE
troubleshooting

### ISSUE THREAD

**Issue by gbjbaanb** [dotnet/AspNetCore.Docs#17827]
There are so many roadbumps to getting cache headers set that the troubleshooting checklist needs a bt of extension

eg: 

[Authorise] attribute causes no-cache but you can use [AllowAnonymous] on an action.

Any page with a form taghelper will cause no-cache. You must use the asp-antiforgery="false" property in the form or the invisible and automatically-added input field will silently break your caching (grrr). This applies even if the action has the [IgnoreAntiForgery] attribute.

SetCookie will break it too, but (I think) only if the cookie changes or there is a new one set. 
I'm not sure why TempDataCookie prevents the cache-control header being set when I can set a cookie and have it honoured (or even why this condition exists, a cached page with a cookie set in its response should simply remain until the cache expires)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1#troubleshooting)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JunTaoLuo** [comment]
I don't think we should make any changes here. It's not feasible to come up with an exhaustive list of every scenario where caching can be disabled, there are too many component interactions that might result in a request or response being considered uncacheable. 

In the troubleshooting portion of the docs, we recommend turning on logging which would have addressed most of the scenarios listed here. For example, our [logging](https://github.com/dotnet/aspnetcore/blob/cd9da1c3503d89e7f42b7ee780416eb1d4036b84/src/Middleware/ResponseCaching/src/LoggerExtensions.cs) would indicate the reason for why caching was disabled and includes unique messages for when Authorization and SetCookies are set. Given that it's not feasible to track each scenario to individual components such as Mvc filters or taghelpers, turning on logging should be sufficient for troubleshooting the behaviour of response caching middleware..
