### ISSUE TITLE
Is authentication safe client-side?

### ISSUE THREAD

**Issue by ferguson-eric** [dotnet/AspNetCore.Docs#17823]
'Blazor WebAssembly apps run on the client. Authorization is only used to determine which UI options to show. Since client-side checks can be modified or bypassed by a user, a Blazor WebAssembly app can't enforce authorization access rules.'

I previously asked a question (https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1 Blazor WASM with Auth Lib groups and roles) regarding authorization client-side.

From this, I assume no authorization should be conducted client-side. If the [Authorize] tag can be bypassed, then is authentication itself secure client-side? Perhaps someone can manipulate GetAuthenticationStateAsync() to create a new claims principal with IsAuthenticated set to true? Should Blazor WASM only be used for displaying insensitive content to unauthenticated users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Unless a check is made server-side (e.g., typically server-side checks made via an API) *before* sending content to the client, yes, that's right. Content sent to the client can't be secured *after* it's sent. Further details are in the WASM Overview topic.

https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/
