### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by HamidMolareza** [dotnet/AspNetCore.Docs#17826]
Please see `UpdateInstructorCourses` method in [Create an Instructor page model base class](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-3.1#create-an-instructor-page-model-base-class):

Iterate through all courses (`context.Courses`) isn't optimal and necessary, especially if there are a lot of courses.
We can combine the two `HashSet` and just iterate them.

But we can't combine them because one is `string` and the other is `int`.
Yes, this problem will be solved if we use `int[] selectedCourses` instead of `string[]` in the method parameter, and update related [action](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-3.1#update-the-instructor-edit-page-model) (`OnPostAsync`).

I checked and these changes work well, so can create a PR for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JonPSmith please review

**Comment by JonPSmith** [comment]
Hi @Rick-Anderson,

Having just looked at the page in question it looks OK. Let me say why in case I have misunderstood.

First, the `AssignedCourseDataList` will contain ALL the courses, with the `Assigned` property set to true if the instructor is assigned to that course. That sounds OK, as the display at the top of the article shows a list of courses, with ticked box next to courses that the instructor is working. (I assume this is what happens - I haven't run the code)

So, in the second part the user ticks/unticks boxes and clicks Save. This calls the `UpdateInstructorCourses` method. At this point the code has to go though all the courses, because the `selectedCourses` array only holds the courses the instructor is assigned to now, so you do need iterate over all the courses to make sure that the instructor is removed from any other courses that they were assigned to before the update.  

I hope that helps. Please check as this is a quick answer.

**Comment by HamidMolareza** [comment]
@JonPSmith Thanks for reviewing.
The first part (`PopulateAssignedCourseData` method) has no problem.

Focus on the second part (`UpdateInstructorCourses` method) :
the `selectedCoursesHS` holds updated checklists, and the `instructorCourses` holds checklists that were in the database.

Suppose:
All courses id: 1, 2, 3, ....., 10000
(Old data) `instructorCourses`: 1, 2, 3
(New data) `selectedCoursesHS`: 2, 3, 4

We only need to Iterate through one to four not all the courses!
Please see this [source](https://gist.github.com/HamidMolareza/d115fde80221e48aa460dcc6143792fe).

**Comment by JonPSmith** [comment]
@HamidMolareza,

There is a trade-off here - your code would be quicker if there were lots of courses and instructors only dealt with a few courses. But your code has two database queries, each with a database round-trip cost, while the current code does only one database access. The point is that two queries are more costly than one (see my [NDC London 2020 video](https://www.youtube.com/watch?v=zySHbwl5IeU) at about 13 minutes in).

As always you would need to test the two approaches with real data and see which is faster.

The other thing I would say is your code is a bit more complex than the the current code - `UnionWith` isn't a typical EF Core command to use. The Microsoft Docs are meant for a large range of readers and I think the current version is slightly simpler.

**Comment by HamidMolareza** [comment]
@JonPSmith Thanks for the video.

> But your code has two database queries, each with a database round-trip cost, while the current code does only one database access.

I don't understand why my code has two database queries. Conversely, I think the current code has a query and **my code has zero query**! Please note that the current code has access to the `context` through the method parameter, but my code does not.

`instructorToUpdate` is in **memory** and `selectedCourses` is in memory too. `UnionWith` operations are performed in memory, not database.

**Comment by JonPSmith** [comment]
Sorry, i missed that. I'm trying to do this in my spare time, so I haven't run any code. This would take me more time than I can provide so I am bowing out. 

Sorry @Rick-Anderson, I didn't help here.

**Comment by Rick-Anderson** [comment]
@JonPSmith  thanks for your expert help. Hope all is well.

**Comment by HamidMolareza** [comment]
@Rick-Anderson  I didn't understand what the result was!

**Comment by Rick-Anderson** [comment]
@HamidMolareza  we won't be changing queries on this tutorial unless it's a problem. In this case it's a trade-off and your approach isn't a clear advantage. We are a small doc team with more work than we can do. This doesn't meet the bar.

**Comment by HamidMolareza** [comment]
@Rick-Anderson 

> We are a small doc team with more work than we can do

This is another matter and hope the open community can help too.

> your approach isn't a clear advantage

1. Access to `SchoolContext` **isn't necessary**.
2. Query to database has **cost**. (`context.Courses`)
3. It doesn't matter in few courses/requests (many approach is good), but for lots of courses/requests, get all courses from database and iterate through can be very costly. (**iterate through all courses isn't necessary**)
4. Convert `int` to `string` isn't necessary and has cost.
5. Check the condition at the end of the code isn't necessary. (Remove it can make the code **more readable**)
6. Microsoft's official tutorial is expected to provide good code.

These problems do not exist in [this source](https://gist.github.com/HamidMolareza/d115fde80221e48aa460dcc6143792fe).
