### ISSUE TITLE
No documentation on *how* to implement problem details factory

### ISSUE THREAD

**Issue by vanpyrzericj** [dotnet/AspNetCore.Docs#17837]
You just say to implement problems detail factory for custom work. But provide no details (ironically) on how to actually do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1#implement-problemdetailsfactory)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Handle errors in ASP.NET Core web APIs #16385
hopefully we can get to this in the next review.
