### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#17839]
Hi team, 
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.es-es/issues/49

@oacostam commented 4 hours ago — with docs.microsoft.com
The docs should explain how to setup the site in IIS, for instance, what physical path should be used, the same as project? Or it's needed to deploy the project to some location before debugging?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by avidme** [comment]
Yes the doc must also explain how to set up site in IIS so that the complete picture of using IIS profile for the .Net Core applications will be easy to understand and implement. I had very tough time putting all these pieces together. Though we try to keep all the missing pieces together there are some loop holes of which we cannot reason about.
