### ISSUE TITLE
Better to create a new empty Core 3.1 Project then copy code across

### ISSUE THREAD

**Issue by manukautech** [dotnet/AspNetCore.Docs#17842]
These instructions for migration Core 2.2 to Core 3.1 are very complex, time consuming and a lot to go wrong. Also these instructions are for Core 3.0 so they are out of date and need adaptation. It is better, faster and more efficient to create an all new Core 3.1 app and copy files and some code-within-critical-files across. This article needs a complete replacement with one based on copy-across into a fresh app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's how I do it.

**Comment by Rick-Anderson** [comment]
See [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-3.1)

A quick way to get an overview of the changes in 2.1 is to:

Create an ASP.NET Core 2.0 web app named WebApp1.
Commit the WebApp1 in a source control system.
Delete WebApp1 and create an ASP.NET Core 2.1 web app named WebApp1 in the same place.
Review the changes in the 2.1 version.
