### ISSUE TITLE
Link to "Routing: Reserved routing names is broken"?

### ISSUE THREAD

**Issue by urig** [dotnet/AspNetCore.Docs#17854]
At the very beginning of the article there is a link to "Routing: Reserved routing names" referring to URL: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#reserved-routing-names

The document behind this URL makes no mention of reserved routing names. The word "reserved"  does not appear in the document.

Might the link be wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c32c8-ec27-1771-bb62-71d6aa55b1d6
* Version Independent ID: 99dc76fb-8762-20a6-d7b1-df3ce6e6fc4d
* Content: [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/razor-pages/razor-pages-conventions.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by urig** [comment]
Thank you @Rick-Anderson and @serpent5 for taking care of this and so quickly. 💯
