### ISSUE TITLE
Please add InvertedSoftware.PLogger.Core the the third party logging provider list

### ISSUE THREAD

**Issue by invertedsoftware** [dotnet/AspNetCore.Docs#17865]
Please add InvertedSoftware.PLogger.Core the the third party logging provider list.
Nuget:
https://www.nuget.org/packages/InvertedSoftware.PLogger.Core/1.0.0

GitHub
https://github.com/invertedsoftware/InvertedSoftware.PLogger.Core

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
