### ISSUE TITLE
 UseCors must come before UseAuthorization 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#17862]
See https://github.com/dotnet/aspnetcore/issues/20709

cc @serpent5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#enable-cors-with-endpoint-routing)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Bottswana** [comment]
I believe this is the wrong way round, UseCors() must come before UseAuthorization

Working code example (From other issue):
```
    public void Configure(IApplicationBuilder app)
    {
        app.UseDeveloperExceptionPage();

        app.UseRouting();

        app.UseCors();

        app.UseAuthentication();
        app.UseAuthorization();

        app.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
        });
    }
```
