### ISSUE TITLE
Call services from main ObjectDisposedException explanation

### ISSUE THREAD

**Issue by gardc** [dotnet/AspNetCore.Docs#17860]
In [call services from main](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#call-services-from-main) section, `var serviceScope = host.Services.CreateScope()` should not be wrapped in a `using` block, according to `ObjectDisposedException `runtime explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#call-services-from-main)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik please quick review

**Comment by Rick-Anderson** [comment]
Moved to Dependency injection master issue #17298

**Comment by Rick-Anderson** [comment]
@halter73  quick review

**Comment by halter73** [comment]
I don't understand what this issue is. I don't see anything wrong with `using (var serviceScope = host.Services.CreateScope())`. What does `ObjectDisposedException` have to do with this? Is that being thrown from somewhere in the sample code?
