### ISSUE TITLE
Please add https://www.nuget.org/packages/InvertedSoftware.PLogger.Core/ to the 3rd party providers

### ISSUE THREAD

**Issue by invertedsoftware** [dotnet/AspNetCore.Docs#17878]
Please add https://www.nuget.org/packages/InvertedSoftware.PLogger.Core/ to the 3rd party providers
The project is here: https://github.com/invertedsoftware/InvertedSoftware.PLogger.Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Added 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#third-party-logging-providers

Appreciate any feedback you have on the topic
