### ISSUE TITLE
The Sample App section

### ISSUE THREAD

**Issue by mouleja** [dotnet/AspNetCore.Docs#17886]
It's not entirely clear what the purpose of this section is.  I followed the steps (Sqlite flow) successfully and was able to see the completed app but then had to delete everything again in order to continue the tutorial.  (In fact, copying the created CU.db file to the new project caused issues since Students had FirstName instead of FirstMidName.)  Perhaps a link to the repo is sufficient along with a working demo on Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The sample app section is just to give you an overview of what the project will look like.
