### ISSUE TITLE
Scenario: Custom Attributes like ActionFilter in AspCore

### ISSUE THREAD

**Issue by mbedded** [dotnet/AspNetCore.Docs#17893]
I hope this is the correct area for my issue. Otherwise feel free to move this ticket :)

I have an issue with custom Attributes to add logic via @attribute-Annotation.

As example i have in ASP Core an action with a parameter. With the annotation (ActionFilter) i want to verify the parameter before the Controller executes.

```
// Example code
[CheckProjectId] // Extends ActionFilterAttribute
public IActionResult DisplayProject(int projectId){
  return View();
}
```

The `CheckProjectAttribute` verifies if the ID exists. If true: Nothing happens. If false, there will be a redirect to "project not found view".

I would like to add such logic to Blazor Server.

Pseudocode
```
@page "/project/{projectId:int}"
@attribute [CheckProjectId]

<h1>Content</h1>
```

For me it seems that ActionFilter is not working for Blazor. Is there a different type i can use to inject logic into the workflow?
I could write something like

```
@code {
  protected override async Task OnInitializedAsync() {
    // Check parameter and do redirect if project not existing
  }
}
```

but this doesn't look good to me compared with attributes because i think it's cleaner to abort the request as early as possible instead of adding checks into every component itself and overwrite an additional method which is not needed in most components (in my case).

Thank you for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a84b780b-ca41-c255-9fbf-12e9af990c8a
* Version Independent ID: 8d522def-5710-f0ec-97aa-9ac636785f12
* Content: [ASP.NET Core Blazor advanced scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/advanced-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/advanced-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mbedded ... Move that to the engineering repo (you'll need to do it, I don't have 'move issue' authority) ...

https://github.com/dotnet/aspnetcore/issues

**Comment by mbedded** [comment]
Thank you for your feedback :)
