### ISSUE TITLE
The link to Unrestricted File Upload is broken

### ISSUE THREAD

**Issue by jasekiw** [dotnet/AspNetCore.Docs#17897]
The link: Unrestricted File Upload to https://www.owasp.org/index.php/Unrestricted_File_Upload does not work. It results in a 404. 

I believe the link should be changed to https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're forwarding for me; but yes, let's definitely avoid the redirect. I'll patch it up.

Thanks @jasekiw!

**Comment by jasekiw** [comment]
@guardrex Thanks!
