### ISSUE TITLE
Link to DataType attribute broken

### ISSUE THREAD

**Issue by albinkc** [dotnet/AspNetCore.Docs#17896]
In the explanation:
[
DataType(DataType.Date)]: The DataType attribute specifies the type of the data (Date). With this attribute:

The user is not required to enter time information in the date field.
Only the date is displayed, not time information.

The link to DataType pointing to https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.dataannotations.internal.datatypeattributeadapter

is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[DataType(DataType.Date)]: The DataType attribute specifies the type of the data (Date). With this attribute:

DataType should be `<xref:System.ComponentModel.DataAnnotations.DataTypeAttribute.DataType>`

Need to figure out what include that's in.

@albinkc  thanks for the report.

cc @serpent5
