### ISSUE TITLE
Missing code highlight in "Update the Delete Razor page" section

### ISSUE THREAD

**Issue by hafniz** [dotnet/AspNetCore.Docs#17907]
The code block shown in this seciton replaces FirstMidName with FullName in the Administrator field. However, its corresponding row (`@Html.DisplayFor(model =&gt; model.Department.Administrator.FullName)`) is not highlighted in yellow/green. Hope this can be fixed so that readers can more easily see which part of the code they need to change. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, we'll address this in the next update.
