### ISSUE TITLE
Pdf summary issue on e-reader

### ISSUE THREAD

**Issue by Tidus972** [dotnet/AspNetCore.Docs#17908]
# Issue description
Hello,
Using an e-reader, the generated summary pages target correctly the corresponding chapter but using the e-reader summary  the target fail starting at the "depedency injection" chapter. It really start at page 852 but the summary indicate page 851. Then all the following chapter are pushed several page down.

**Comment by Rick-Anderson** [comment]
Can you check [these issues](https://github.com/MicrosoftDocs/feedback/issues?q=is%3Aissue+is%3Aopen+PDF+in%3Atitle), if it's not there. open a new issue. That's the right repo.
