### ISSUE TITLE
This doesn't work with AWS Cognito

### ISSUE THREAD

**Issue by JSpring3** [dotnet/AspNetCore.Docs#17904]
[EDIT by guardrex to add the topic metadata and fix the code block]

I could not get your example working AWS Cognito.
It will send me back a valid ID token and a valid access token in the response but the example application does nothing with the two tokens so it doesn't display the name or show that you are logged in.

Here is my AWS Cognito Config

```csharp
builder.Services.AddOidcAuthentication(options =>
{
    // Configure your authentication provider options here.
    // For more information, see https://aka.ms/blazor-standalone-auth

    options.ProviderOptions.Authority = "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ydUErvZQJ/";
    options.ProviderOptions.ClientId = "2m50t6m94ec7pcnuk4179k15sf";
    options.ProviderOptions.ResponseType = "token";
    options.ProviderOptions.RedirectUri = "https://localhost:5001";
    options.ProviderOptions.DefaultScopes.Add("aws.cognito.signin.user.admin email openid phone profile");
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JSpring3 ... btw ... please use the **This page** feedback button+form at the bottom of any topic. It adds metadata and automatically pings the author of the topic. No worries tho, I added the metadata manually to your opening comment. Oh, and I noticed that you have a single backticks for the code. Single backticks are used for inline code. Three backticks (on their own lines) above and below code will style a code block.

I was about to suggest that you open that for engineering, but your scopes may not be correctly added. I haven't seen them added as a space-separated list passed to the `DefaultScopes.Add` method like that. I just haven't seen a MS engineering sample providing them to the `DefaultScopes` collection like that. Did you try one per line? ... like this ...

```csharp
options.ProviderOptions.DefaultScopes.Add("aws.cognito.signin.user.admin");
options.ProviderOptions.DefaultScopes.Add("email");
options.ProviderOptions.DefaultScopes.Add("openid");
options.ProviderOptions.DefaultScopes.Add("phone");
options.ProviderOptions.DefaultScopes.Add("profile");
```

Don't close this in case that works. I envision that if that's the trick, then I'll need to call out adding scopes one-per-line. This issue will automatically close when such a PR merges.

**Comment by guardrex** [comment]
... or try adding them as a `List<string>` ...

https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs#L33

**Comment by guardrex** [comment]
I'm going to go ahead and schedule this for work to make it clear how the scopes are added. If this doesn't solve your issue, open an issue with engineering at ...

https://github.com/dotnet/aspnetcore/issues

... and add a `cc: @guardrex` to your open comment so that I can track the discussion.

**Comment by JSpring3** [comment]
Thanks for the info,
Your fix did not resolve the issue.
Do I need add this issue somewhere else or here?

**Comment by guardrex** [comment]
Open a new issue on the engineering repo at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to the bottom of your opening comment so that I can track the discussion. Thanks.

Leave this docs issue open. I still need to add a little more info about setting up multiple scopes. This issue will automatically close when the PR merges. ......... **_and_** engineering may have a solution for your situation that I can roll onto the PR, too.

**Comment by guardrex** [comment]
Reconsidered this, and I think we'll hold off for now and listen :ear: for additional feedback before making changes. Assigning a `List<string>` is a C# convention. Also, I don't want to make the content longer than it needs to be with only a small benefit.
