### ISSUE TITLE
what is the default behaviour when the ResponseCache is not added to an API?

### ISSUE THREAD

**Issue by stiasta** [dotnet/AspNetCore.Docs#17917]
Hi, what is the default behaviour when the ResponseCache is not added to an API?
Let us say you have an incoming GET request without cache headers and nothing is configured in the dotnet core API regarding cache. What will default cache headers be for the response?

I am thinking more specifically of the IE GET request client side caching that is on by default and the evergreen browsers do not have this. This quirk might be a problem that many developers struggles with when developing with backwards comp. for IE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
This is not a common question and we don't plan to include it in the docs. People can simply try this out if ever come across and find out easily.
