### ISSUE TITLE
How to send ping control frame?

### ISSUE THREAD

**Issue by ArjunVachhani** [dotnet/AspNetCore.Docs#17916]
web sockets protocol allows to send ping control frame to check if other endpoint is responsive or not. how to send ping/pong control frames?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Add additional info WebSockets : Master issue #13492

**Comment by ArjunVachhani** [comment]
it looks like by mistake you have closed wrong comment.
