### ISSUE TITLE
Why is no client secret required?

### ISSUE THREAD

**Issue by danijam** [dotnet/AspNetCore.Docs#17919]
In the section "Register the app in Azure AD B2C" it says that a client secret isn't required in this tutorial. I'd like to understand why? Does there not need to be a secret trust relationship between the application and Azure B2C?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
It's not doing the following

If your application exchanges an authorization code for an access token, you need to create an application secret.
