### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by 1cm** [dotnet/AspNetCore.Docs#17918]
This section has wrong url:

"View or download sample code from the AspNetCore GitHub repository. Download the dotnet/AspNetCore repository ZIP file. Unzip the file. Navigate to the src/Security/samples/CustomPolicyProvider project folder."

View or download sample code is wrong.
The good one is this one:
https://github.com/dotnet/aspnetcore/tree/master/src/Security/samples/CustomPolicyProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by mjrousos** [comment]
Thanks for spotting this, @1cm. I've opened a PR with a fix.
