### ISSUE TITLE
Add an example how to do 2-way data binding to a grandchild component

### ISSUE THREAD

**Issue by timcromarty** [dotnet/AspNetCore.Docs#17921]
2 way data binding through a hierarchy of components is really confusing

Parent component --&gt; Child component --&gt; grandchild component

Parent component:
&lt;childComponent @bind-Property="somevalue" /&gt;

Child component:
[Parameter] public Property { get; set;}
[Parameter] public EventCallback&lt;type&gt; PropertyChanged { get; set; }

How can I pass the bound value on to the grandchild component?
It won't met me add OnValueChanged and @bind-Property

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#child-to-parent-binding-with-chained-bind)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good ❓ @timcromarty ... I haven't tried a three-level multi-level bind like that. I have a suspicion that a state container is the way to go.

I whipped up a test, and I discovered that the last bind going up from the grandchild to the grandparent seems not to work. Try this set of components and you'll see what I mean ...

Added to *Shared/NavMenu.razor* ...

```razor
<li class="nav-item px-3">
    <NavLink class="nav-link" href="parentcomponent">
        <span class="oi oi-list-rich" aria-hidden="true"></span> Parent Component
    </NavLink>
</li>
```

*Pages/ParentComponent.razor* ...

```razor
@page "/parentcomponent"

<h1>ParentComponent</h1>

<p>In Parent Property: <b>@Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Parent</button>
</p>

<ChildComponent @bind-Property="@Property" />

@code {
    public string Property { get; set;} = "Intial value set in Parent";

    private void ChangePropertyValue()
    {
        Property = $"New value set in Parent {DateTime.Now}";
    }
}
```

*Shared/ChildComponent.razor* ...

```razor
<h2>ChildComponent</h2>

<p>In Child Property: <b>@Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Child</button>
</p>

<GrandchildComponent @bind-Property="@Property" />

@code {
    [Parameter]
    public string Property { get; set;}

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    private Task ChangePropertyValue()
    {
        Property = $"New value set in Child {DateTime.Now}";

        return PropertyChanged.InvokeAsync(Property);
    }
}
```

*Shared/GrandchildComponent.razor* ...

```razor
<h2>GrandchildComponent</h2>

<p>In Grandchild Property: <b>@Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Grandchild</button>
</p>

@code {
    [Parameter]
    public string Property { get; set; }

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    private Task ChangePropertyValue()
    {
        Property = $"New value set in Grandchild {DateTime.Now}";

        return PropertyChanged.InvokeAsync(Property);
    }
}
```

Now, let's try the state container approach ...

*StateContainer.cs* ...

```csharp
public class StateContainer
{
    public string Property { get; set; } = "Initial value from StateContainer";

    public event Action OnChange;

    public void SetProperty(string value)
    {
        Property = value;
        NotifyStateChanged();
    }

    private void NotifyStateChanged() => OnChange?.Invoke();
}
```

In `Program.Main` ...

```csharp
builder.Services.AddSingleton<StateContainer>();
```

Added to *Shared/NavMenu.razor* ...

```razor
<li class="nav-item px-3">
    <NavLink class="nav-link" href="parentcomponent2">
        <span class="oi oi-list-rich" aria-hidden="true"></span> Parent Component 2
    </NavLink>
</li>
```

*Pages/ParentComponent2.razor* ...

```razor
@page "/parentcomponent2"
@inject StateContainer StateContainer
@implements IDisposable

<h1>ParentComponent2</h1>

<p>In Parent Property: <b>@StateContainer.Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Parent</button>
</p>

<ChildComponent2 />

@code {
    protected override void OnInitialized()
    {
        StateContainer.OnChange += StateHasChanged;
    }

    private void ChangePropertyValue()
    {
        StateContainer.SetProperty($"New value set in Parent {DateTime.Now}");
    }

    public void Dispose()
    {
        StateContainer.OnChange -= StateHasChanged;
    }
}
```

*Shared/ChildComponent2.razor* ...

```razor
@inject StateContainer StateContainer
@implements IDisposable

<h2>ChildComponent2</h2>

<p>In Child Property: <b>@StateContainer.Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Child</button>
</p>

<GrandchildComponent2 />

@code {
    protected override void OnInitialized()
    {
        StateContainer.OnChange += StateHasChanged;
    }

    private void ChangePropertyValue()
    {
        StateContainer.SetProperty($"New value set in Child {DateTime.Now}");
    }

    public void Dispose()
    {
        StateContainer.OnChange -= StateHasChanged;
    }
}
```

*Shared/GrandchildComponent2.razor* ...

```razor
@inject StateContainer StateContainer
@implements IDisposable

<h2>GrandchildComponent2</h2>

<p>In Grandchild Property: <b>@StateContainer.Property</b></p>

<p>
    <button @onclick="ChangePropertyValue">Change Property from Grandchild</button>
</p>

@code {
    protected override void OnInitialized()
    {
        StateContainer.OnChange += StateHasChanged;
    }

    private void ChangePropertyValue()
    {
        StateContainer.SetProperty($"New value set in Grandchild {DateTime.Now}");
    }

    public void Dispose()
    {
        StateContainer.OnChange -= StateHasChanged;
    }
}
```

... and that turned out well. :+1:

These issues are usually triaged on Fridays. Artak will look this over (probably on 4/24) and say if I missed something on the multi-level chained-bind experience (the earlier bit, the first approach :point_up:).

WRT the state container approach, which definitely works here for what you're trying to do, I wonder if that should be an example in the topic ... I mean at least as a general example. It's really a quite flexible approach that can be used across the app in a nice sort of on-demand/as-needed way ... *inject and go!* I think 🤔 that example is about what we would want to cover for that approach.

**Comment by mkArtakMSFT** [comment]
@javiercn do you know why this doesn't work:

> How to fix (if possible) the chained bind (first approach ☝️). It only fails for one scenario, when the property is changed in the grandchild. Other than that, it works in every other aspect:

> Parent change -> Child and Grandchild updates
> Child change -> Parent and Grandchild updates
> Grandchild change -> Only the Child updates, not the Parent.
> If this behavior is expected, then perhaps a callout that chained bind only works for a single parent. If that example can be fixed, then perhaps a callout for whatever the solution is in the Chained bind section of the topic.

**Comment by mkArtakMSFT** [comment]
Thanks @guardrex. Before documenting let's first understand why the chained bind doesn't work.

**Comment by guardrex** [comment]
@mkArtakMSFT I still don't have a solution for the *Three-level-bind approach* (chained bind). Only the *State container approach* was working when I took a look at this earlier. Should I try the chained-bind approach again to confirm that it still isn't working?

**Comment by guardrex** [comment]
I've to rebuilt the three-level bind scenario using the latest guidance (i.e., components shouldn't write directly to their own parameters), but it still doesn't work. The child and grandchild affect their immediate senior components, and none of them bind down components.

@SteveSandersonMS, can you provide a tip to make three-level two-way chained binding work, or should I only document the state container approach, which seems simpler and works fine? After working with these scenarios, **_I really like state containers!_** :smile: That's what I would use for multiple-level two-way "binding" (using *binding* loosely in this context ... I just mean one component updates data and all components everywhere get the updated value). The state container example that I built is in [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/17921#issuecomment-616608463).

### Revised three-level chained bind (not working)

*Pages/ParentComponent.razor* ...

```csharp
@page "/parentcomponent"

<h1>ParentComponent</h1>

<p>In Parent Property: <b>@parentValue</b></p>

<p>
    <button @onclick="ChangeValue">Change from Parent</button>
</p>

<ChildComponent @bind-Property="@parentValue" />

@code {
    private string parentValue;

    [Parameter]
    public string Property { get; set; } = "Intial value set in Parent";

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    protected override void OnInitialized()
    {
        parentValue = Property;
    }

    private Task ChangeValue()
    {
        parentValue = $"New value set in Parent {DateTime.Now}";

        return PropertyChanged.InvokeAsync(parentValue);
    }
}
```

*Shared/ChildComponent.razor* ...

```csharp
<h2>ChildComponent</h2>

<p>In Child Property: <b>@childValue</b></p>

<p>
    <button @onclick="ChangeValue">Change from Child</button>
</p>

<GrandchildComponent @bind-Property="@childValue" />

@code {
    private string childValue;

    [Parameter]
    public string Property { get; set; }

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    protected override void OnInitialized()
    {
        childValue = Property;
    }

    private Task ChangeValue()
    {
        childValue = $"New value set in Child {DateTime.Now}";

        return PropertyChanged.InvokeAsync(childValue);
    }
}
```

*Shared/GrandchildComponent.razor* ...

```csharp
<h2>GrandchildComponent</h2>

<p>In Grandchild Property: <b>@grandchildValue</b></p>

<p>
    <button @onclick="ChangeValue">Change from Grandchild</button>
</p>

@code {
    private string grandchildValue;

    [Parameter]
    public string Property { get; set; }

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    protected override void OnInitialized()
    {
        grandchildValue = Property;
    }

    private Task ChangeValue()
    {
        grandchildValue = $"New value set in Grandchild {DateTime.Now}";

        return PropertyChanged.InvokeAsync(grandchildValue);
    }
}
```

### Cascading values

Useful for cascading values **_down_** to children, not up to parents.

**Comment by guardrex** [comment]
@javiercn I'm up to working on this one now.

Three-level chained bind doesn't seem to work. A state container works great.

We need to add the state container approach to the docs anyway, but is a three-level chained bind either ...

* Not supported ... it doesn't work by-design.
* Not programmed correctly in my attempts. In this issue :point_up:, I tried a couple of approaches:
  * https://github.com/dotnet/AspNetCore.Docs/issues/17921#issuecomment-616608463
  * https://github.com/dotnet/AspNetCore.Docs/issues/17921#issuecomment-638194413

**Comment by javiercn** [comment]
@SteveSandersonMS can chime in here. I'm fully booked for the next week, so I'll be slow to answer.

**Comment by SteveSandersonMS** [comment]
You can bind through any number of levels, but you have to respect the one-way data flow. It's best if you only store the underlying data in one place (the parent component) to avoid any confusion about what state needs to be updated.

Try this:

*ParentComponent.razor*

```razor
<h1>ParentComponent</h1>

<p>In Parent Property: <b>@parentValue</b></p>

<p>
    <button @onclick="ChangeValue">Change from Parent</button>
</p>

<ChildComponent @bind-Property="parentValue" />

@code {
    private string parentValue = "Intial value set in Parent";

    private void ChangeValue()
    {
        parentValue = $"New value set in Parent {DateTime.Now}";
    }
}
```

*ChildComponent.razor*

```razor
<h2>ChildComponent</h2>

<p>In Child Property: <b>@Property</b></p>

<p>
    <button @onclick="ChangeValue">Change from Child</button>
</p>

<GrandchildComponent @bind-Property="BoundValue" />

@code {
    [Parameter]
    public string Property { get; set; }

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    private string BoundValue
    {
        get => Property;
        set => PropertyChanged.InvokeAsync(value);
    }

    private Task ChangeValue()
    {
        return PropertyChanged.InvokeAsync($"New value set in Child {DateTime.Now}");
    }
}
```

*GrandchildComponent.razor*

```razor
<h2>GrandchildComponent</h2>

<p>In Grandchild Property: <b>@Property</b></p>

<p>
    <button @onclick="ChangeValue">Change from Grandchild</button>
</p>

@code {
    [Parameter]
    public string Property { get; set; }

    [Parameter]
    public EventCallback<string> PropertyChanged { get; set; }

    private Task ChangeValue()
    {
        return PropertyChanged.InvokeAsync($"New value set in Grandchild {DateTime.Now}");
    }
}
```

**Comment by timcromarty** [comment]
That's great. Thanks - very helpful
