### ISSUE TITLE
Seeddata not working

### ISSUE THREAD

**Issue by Gunner64** [dotnet/AspNetCore.Docs#17943]
Hello, I've added the class seeddata as indicated on this page + changed the start-up class.
After I do update-database nothing happens. I don't get an error although I've at least one movie in the database. + the 2 new seeds are not added either.
I even tried to do an add-migration (since this an additional class to the models folder), afterwards update-database. But no luck either. Any pointers?
Many thanks

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Gunner64** [comment]
Yes, it works, after I deleted my entry in the database. This was the final step. I wanted to test If I would receive the error. But that is only if something else might go wrong.
