### ISSUE TITLE
AntiForgeryToken is reusable. Is there any configuration to make it unique on every request?

### ISSUE THREAD

**Issue by iptecuico** [dotnet/AspNetCore.Docs#17949]
AntiForgeryToken is reusable. Is there any option/configuration to make it unique on every request and invalidate the previous ones?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
