### ISSUE TITLE
**Cache Eviction Based On Memory Pressure**

### ISSUE THREAD

**Issue by Gaurav-Puri101187** [dotnet/AspNetCore.Docs#17944]
**Cache Eviction Based on memory  pressure**

- I think the question is how to decide size for the memory cache is it should be object size and if yes what are the best practices to fetch managed object size. 
- Cache Size

**Comment by guardrex** [comment]
Hello @Gaurav-Puri101187 ... Please use the **This page** button+form at the bottom of the topic, as it will add metadata for issue tracking and automatically ping the author of the topic.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
