### ISSUE TITLE
Explain how refresh works in load balanced scenarios

### ISSUE THREAD

**Issue by Vaccano** [dotnet/AspNetCore.Docs#17942]
When there are more than one host sharing keys, what happens when both think they need to create the key at the same time?  Which key wins if they both try to call the IXmlRepository at the same time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275ff6a6-a3f2-fb2b-6fda-4981abf46a7d
* Version Independent ID: e7547577-5c8a-ce9f-d990-b8a4cbaa5a50
* Content: [Key management in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-3.1#data-protection-implementation-key-management)
* Content Source: [aspnetcore/security/data-protection/implementation/key-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
They don't need to create a key at the same time. The 2-day delay before activation gives the key time to propagate through the system.
