### ISSUE TITLE
Services that depend on HttpContextAccessor

### ISSUE THREAD

**Issue by jesslilly** [dotnet/AspNetCore.Docs#17959]
Hi!  When you create a new scope, quite often, services require IHttpContextAccessor to get user or route info.    With the code OnPostAddTaskAsync I was getting an error that IHttpContextAccessor Context was null.  So I create the scope while my http request is still alive and THEN enqueue the work item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio#queued-background-tasks-1)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Right, you shouldn't use `HttpContext `for background work.

**Comment by Rick-Anderson** [comment]
Added to Background tasks with hosted services: master issue #17605
