### ISSUE TITLE
Using ValidationMessage with custom CSS-class

### ISSUE THREAD

**Issue by pekspro** [dotnet/AspNetCore.Docs#17955]
I am using **ValidationMessage** in a razor component to show validation message, like this:

    <ValidationMessage For="@(() => ViewModel.CompanyNumber)" />;

This generates this HTML-code:

    <div class="validation-message">The company number field is required.</div>

Is it possible to change the CSS-class? I want to use something else than `validation-message`. Adding `class="myclass"` is ignored by the controller. I've also tried with `@attributes` without success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pekspro ... Can you just set the style for `validation-message` in the app's *wwwroot/css/site.css* file? Would that work for you rather than changing the class?

Look for it in the file. There should be an existing entry from the template setting the color to red ...

```css
.validation-message {
    color: red;
}
```

**Comment by pekspro** [comment]
Thanks for a super fast answer @guardrex . Yes, I want to change the class to be use (in my case to `text-danger`). I know I can add a class in my CSS-styles, but I consider that to be cheating 😉 But if there are no other solution, I will use that.

**Comment by guardrex** [comment]
Open it for engineering at ...

https://github.com/dotnet/aspnetcore/issues

... and explain that you really want to change the class, not just set styles on `validation-message`.

Please add a `cc: @guardrex` to your opening comment so that I can follow the discussion. You can also add a link to this doc issue to cross-link them. Just place a ...

```
https://github.com/dotnet/AspNetCore.Docs/issues/17955
```

... somewhere in your opening comment.

However it works out, leave this issue open. Let's at least call out the style *override* approach if that's all we have right now.

**Comment by pekspro** [comment]
It turned out that there already was an issue for this: https://github.com/dotnet/aspnetcore/issues/8695

Thanks for your support @guardrex, it’s very much appreciated.

**Comment by carlblanchard** [comment]
It would be great to be able to supply a template to render as the message. I would like to add an icon to my validation message. which means having to supply a I element to use font awesome <i class="fas fa-exclamation-triangle"></i>

**Comment by catman0745** [comment]
The `ValidationMessage` component has a hard-coded classname `validation-message`, which is the only classname bound to the html `class` attribute. You can take a look at the `BuildRenderTree` method in the [source code](https://github.com/dotnet/aspnetcore/blob/0a52bb721c08d29cff3f07c3228d12a68c4477f3/src/Components/Web/src/Forms/ValidationMessage.cs#L71) to make sure:
```csharp
protected override void BuildRenderTree(RenderTreeBuilder builder)
{
    foreach (var message in CurrentEditContext.GetValidationMessages(_fieldIdentifier))
    {
        builder.OpenElement(0, "div");
        builder.AddMultipleAttributes(1, AdditionalAttributes);
        builder.AddAttribute(2, "class", "validation-message"); // hard-coded classname
        builder.AddContent(3, message);
        builder.CloseElement();
    }
}
```

Thus, You can neither change this classname nor specify other classes. This means You need to implement Your own ValidationMessage (don't worry - the implementation can be around 25-50 LoC).

But I recently came across this great [article](https://chrissainty.com/creating-a-custom-validation-message-component-for-blazor-forms/). The guy explains the problem and offers several solutions. I also changes his implementation a bit to something that better suits my needs: [my implementation](https://github.com/catman0745/Catman.Education.BlazorUI/blob/0d67957fc728bb0f6c78f747759b3279db48026d/Components/Forms/ValidationFeedback.razor).

**Comment by AradAral** [comment]
This is absolutely ridiculous! Why can't you change the class of this element?!!! By what logic??

**Comment by guardrex** [comment]
Hello @catman0745 and @AradAral ... Please provide **_product feedback_** to the product unit. We only work on docs here (and this is a closed issue, too). These remarks won't be seen by anyone in authority to take them into account for future releases or even to discuss them further with you.

Open an issue here :point_right: https://github.com/dotnet/aspnetcore/issues
