### ISSUE TITLE
Component Invoking

### ISSUE THREAD

**Issue by CliffConway** [dotnet/AspNetCore.Docs#17966]
I am confused with the 'BlazorSample' reference in the following statement

DotNet.invokeMethod('BlazorSample', 'UpdateMessageCaller');

What does 'BlazorSample' refer/relate to?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The assembly name of the app. This particular app is "BlazorSample."

I'll update it to make that clear. Thanks for calling it out.
