### ISSUE TITLE
i have error in linux

### ISSUE THREAD

**Issue by goliverma** [dotnet/AspNetCore.Docs#17967]
AuthenticationException: The remote certificate is invalid according to the validation procedure.
HttpRequestException: The SSL connection could not be established, see inner exception.

these two error in my blazor project

**Comment by goliverma** [comment]
![Screenshot from 2020-04-23 20-34-32](https://user-images.githubusercontent.com/57150942/80115007-dc459d00-85a1-11ea-9276-aa6cd0468d03.png)

**Comment by goliverma** [comment]
![Screenshot from 2020-04-23 20-36-32](https://user-images.githubusercontent.com/57150942/80115261-2a5aa080-85a2-11ea-8fed-820ba842b8c3.png)

**Comment by guardrex** [comment]
Hello @goliverma ... Try the Linux guidance for that ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#https-configuration

**Comment by goliverma** [comment]
i'm remove app.UseHttpsRedirection() and my project is working now thank u @guardrex
