### ISSUE TITLE
Blazor Client can not get access token after login successfully

### ISSUE THREAD

**Issue by hieuluong1989** [dotnet/AspNetCore.Docs#17963]
[EDIT by guardrex to add the metadata]

# Issue description
I am using Blazor Webassembly Standalone with AAD. Login is ok, but I can not get access token by `AuthenticationService.RequestAccessToken`. The tokenResult is not null but when I get `tokenResult.TryGetToken(out var token)` it can not get token

**Program.cs**
```
builder.Services.AddMsalAuthentication(options =>
            {
                var authentication = options.ProviderOptions.Authentication;
                authentication.Authority = "https://login.microsoftonline.com/...";
                authentication.ClientId = "...";
            });
```

**Index.cshtml**
```
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

@inject HttpClient Http
@inject IAccessTokenProvider AuthenticationService

<button type="button" class="btn btn-secondary oi oi-loop-circular" @onclick="Search"></button>

@code {
    protected async Task Search()
    {
        var tokenResult = await AuthenticationService.RequestAccessToken();
        if (tokenResult.TryGetToken(out var token))
        {
            Http.DefaultRequestHeaders.Add("Authorization", $"Bearer {token.Value}");
        }
    }
}
```

![image](https://user-images.githubusercontent.com/52130197/80085996-02fcd700-8594-11ea-8916-c6009d7042e3.png)

# Software versions
- [ ] .NET Core: 3.1.200
- [ ] Microsoft.AspNetCore.Components.WebAssembly : 3.2.0-preview4.20210.8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30c952e-6e09-5486-1b3a-3f7b1941c75c
* Version Independent ID: e281407e-e12b-e618-88d9-3a2b3a9074b5
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hieuluong1989 ...

* You meant to type "Index.razor," correct?
* Can you try running the app securely (HTTPS) with a secure callback URL configured in Azure?
* Make sure that you've checked the **Access Tokens** checkbox in the app's **Web** platform config in Azure.
* What you show :point_up: doesn't indicate that the token isn't there. Assign `token.Value` to a private field and show it in your component, log it, or write it to the console.

btw - Please use the **This page** feedback button and form at the bottom of any topic to open issues. It identifies the topic, tags the issue with metadata to help us track the work, and pings the author. No worries here, I'll manually add the metadata to your opening comment.

**Comment by hieuluong1989** [comment]
@guardrex : Thank for your replying!
- Yes, Index.razor
- I tried upgrade to 3.1.201, Https, and also checked checkbox Access Tokens. I tried with Console.WriteLine but code flow didn't go into the IF condition
```
if (tokenResult.TryGetToken(out var token))
{
      Console.WriteLine($"TOKEN: {token.Value}");
}
```

**Comment by guardrex** [comment]
What about HTTPS? ... Did you convert over to secure communication (like `https://localhost:5001`) with Azure AD and use a secure callback URL (`https://localhost:5001/authentication/login-callback`)?

**Comment by hieuluong1989** [comment]
@guardrex : yes, I tried with https://localhost:5001
![image](https://user-images.githubusercontent.com/52130197/80112329-2f701d80-85ab-11ea-936d-245bb470cd9c.png)
I uploaded my simple project [https://github.com/hieuluong1989/BlazorAAD](https://github.com/hieuluong1989/BlazorAAD). If you have time, please take a look for me. I have this problem from 3.2.0-preview2, I hoped it was fixed in preview4 but not.

**Comment by guardrex** [comment]
Nothing really jumping out as obviously wrong.

Open an issue for engineering at ...

https://github.com/dotnet/aspnetcore/issues

... and give them the link to your repro project. Please add a `cc: @guardrex` to your opening comment and a link to this docs issue ...

```
https://github.com/dotnet/AspNetCore.Docs/issues/17963
```

If they come up with something that we need to document, then I'll re-open this issue and work it from there.

**Comment by RogueJin** [comment]
I got the same issue now. the project is a Blazor Webassembly Standalone with OIDC authentication by a third-party provider Authing.cn. Login function works properly, but access token can not be gotten. did I miss somthing?

Program.cs
``` csharp
builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("Local", options.ProviderOptions);
});
```

Index.razor.cs
``` csharp
    [Authorize]
    public partial class Index : ComponentBase
    {
        [Inject]
        public required HttpClient Http { get; set; }

        [Inject]
        public IAccessTokenProvider TokenProvider { get; set; }

        protected override async Task OnInitializedAsync()
        {
            var option = new AccessTokenRequestOptions
            {
                Scopes = new[] { "openid" }
            };
            var tokenResult = await TokenProvider.RequestAccessToken(option);
            if (tokenResult.TryGetToken(out var token))
            {
                Http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.Value);
            }
        }
    }
```

![Screenshot 2023-09-20 at 18 13 03](https://github.com/dotnet/AspNetCore.Docs/assets/21214103/521f09d8-a93c-4775-b885-b85ac20659d7)

- net 7.0
- Microsoft.AspNetCore.Components.WebAssembly: 7.0.10

**Comment by guardrex** [comment]
@RogueJin ... First, go to ...

https://github.com/dotnet/aspnetcore/issues

... and search the open and closed issues to see if anyone else has asked about this. If you can't find an existing issue, open a new issue for them.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/17963
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by RogueJin** [comment]
@guardrex got it
