### ISSUE TITLE
Is it possible to exchange voice stream between different clients?

### ISSUE THREAD

**Issue by NaumovEvgeniy** [dotnet/AspNetCore.Docs#17976]
For example, I use a browser as a client, another user uses a mobile app. 
I'm starting to speak and I want to send my voice message to a mobile app for another user.  

Is it possible?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Yes, you can stream anything. You'll need to figure out how to get the audio and how you want to encode it and decode it.

**Comment by NaumovEvgeniy** [comment]
@BrennanConroy thanks for your quick response!
Do you have any examples?

**Comment by BrennanConroy** [comment]
No, I've never tried capturing audio in the browser before. You'll need to do some research.

We have a sample that does ASCII-video with streaming at https://github.com/SignalR/sample-StreamR.
And a live example of it at https://streamr.azurewebsites.net/
