### ISSUE TITLE
Augment logging documentation for Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#17977]
@mkArtakMSFT brought up the fact that the our logging documentations show how to configure logging during startup, but not how to use logging within components.

We should add a documentation page that shows the following code samples for using loggers within a component.

```csharp
@page "/counter"

@using Microsoft.Extensions.Logging;
@inject ILogger<Counter> logger;

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        logger.LogWarning("Someone has clicked me!");
        currentCount++;
    }
}
```

OR

```csharp
@page "/counter"

@using Microsoft.Extensions.Logging;
@inject ILoggerFactory LoggerFactory

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        var logger = LoggerFactory.CreateLogger<Counter>();
        logger.LogWarning("Someone has clicked me!");
        currentCount++;
    }
}
```

Note that:
* The using directive for `Microsoft.Extensions.Logging` is needed to support Intellisense completions for APIs like `LogWarning` and `LogError`.
* The Loggers will respect whatever config is registered in startup.

**Comment by mkArtakMSFT** [comment]
Thanks @captainsafia!
@guardrex no need for a separate page for this. I think this can become a small subsection into some existing page which talks about logging already.
