### ISSUE TITLE
Sharing secrets

### ISSUE THREAD

**Issue by mattwill09** [dotnet/AspNetCore.Docs#17981]
The section about the Secret Manager states:

The app secrets are associated with a specific project or shared across several projects.

but everything after that point only discusses using project ids. It would be helpful to discuss how secrets can be shared across projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows#feedback)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Use the same `<UserSecretsId>GUID</UserSecretsId>`

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>GUID</UserSecretsId>
  </PropertyGroup>
``

**Comment by mattwill09** [comment]
That makes sense.  I will close this issue.
