### ISSUE TITLE
Web SDK Is Not A True Prerequisite

### ISSUE THREAD

**Issue by mark-monteiro** [dotnet/AspNetCore.Docs#17983]
The web SDK does not appear to be required for test projects running integration tests. In fact, specifying this SDK failed to build for our project, whereas using the default `&lt;Project Sdk="Microsoft.NET.Sdk"&gt;` worked as expected. Is this a true prerequisite or an optional one? What difference does specifying the web SDK it make?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#test-app-prerequisites)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mark-monteiro ... It is ... *or at least was* ... required. Here's where it was discussed after engineering explicitly called for it and then another reader asked about it ...

https://github.com/dotnet/AspNetCore.Docs/issues/7095#issuecomment-400416474

I recommend that you have a further question about that to open an issue with engineering to ask them if the guidance is still valid.

https://github.com/dotnet/aspnetcore/issues

Give them this link to that content ...

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#test-app-prerequisites

... and that link to his answer :point_up: about why it was needed. If he/they say that it's no longer the case, ping back on this issue. I'll re-open this, and we'll work it from there.
