### ISSUE TITLE
ILoggerFactory doesn't seem to have a `Create` method.

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/AspNetCore.Docs#17989]
Given a `loggerFactory` instance, what's the easiest way to call `AddProvider` on it, specifying console and debug logger-providers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d0e6d5d-0b03-5238-cbb6-aef834377f11
* Version Independent ID: dbcd23c0-3bca-e480-936b-2cf6f2d62c7e
* Content: [Migrate from Microsoft.Extensions.Logging 2.1 to 2.2 or 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/logging-nonaspnetcore?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/Logging-nonaspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/Logging-nonaspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @pakrym
* Microsoft Alias: **pakrym**

**Comment by Rick-Anderson** [comment]
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddConsole();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Comment by weitzhandler** [comment]
Thank you Rick  🙏🏻
