### ISSUE TITLE
Why does logging in have to happen server side?

### ISSUE THREAD

**Issue by rolandoldengarm** [dotnet/AspNetCore.Docs#17985]
&gt; The ASP.NET Core app is intended to be used for data access, authorization, and other server-side concerns

Is there a particular reason why all identity server pages (login, register, etc.) are server side? Technically they can be implemented in Angular as well, which will ensure a more seamless experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment]
That's not how they're implemented.
