### ISSUE TITLE
missing clear explanation to add import 

### ISSUE THREAD

**Issue by thx1766** [dotnet/AspNetCore.Docs#17987]
There is a comment in the code, in the section
"Add the following highlighted properties to Pages/Movies/Index.cshtml.cs:"

// Requires using Microsoft.AspNetCore.Mvc.Rendering;

The tutorial should probably take this comment out and make it clear that the user needs to add
using Microsoft.AspNetCore.Mvc.Rendering;
to the top of the file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This approach has worked well for some time.
