### ISSUE TITLE
MovieContext -> RazorPagesMovieContext

### ISSUE THREAD

**Issue by thx1766** [dotnet/AspNetCore.Docs#17986]
This tutorial should be corrected in section "Use SQLite for development, SQL Server for production":
The context should be corrected to "RazorPagesMovieContext" from "MovieContext" - this change is necessary to properly build at this step, and is not necessarily intuitive to new new developers or those new to dotnetcore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by vvdavid** [comment]
Yep, I'm having trouble understanding what is that for. New to web apps.

**Comment by RSP531** [comment]
I agree. I was not able to run "dotnet build" until I changed "Movie Context" to "RazorPagesMovieContext" This was very unclear.I appreciate the comment by thx1766 to help out

**Comment by TCooper1996** [comment]
Had the same issue and was unable to build until I tried your solution. Thanks.

**Comment by geofflangenderfer** [comment]
> I agree. I was not able to run "dotnet build" until I changed "Movie Context" to "RazorPagesMovieContext" This was very unclear.I appreciate the comment by thx1766 to help out

Do you mean
```
// Startup.cs

      public void ConfigureServices(IServiceCollection services)
      {
         services.AddRazorPages();

-        services.AddDbContext<MovieContext>(options =>
+        services.AddDbContext<RazorPagesMovieContext>(options =>
            options.UseSqlite(
                Configuration.GetConnectionString("MovieContext")));
  
      }
```
