### ISSUE TITLE
TextWriterTraceListener not used in the sample app

### ISSUE THREAD

**Issue by pappasa** [dotnet/AspNetCore.Docs#17991]
This page states:

The provider can route messages to a variety of listeners, such as the TextWriterTraceListener used in the sample app.

However the sample app mentioned at the top of this page (https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/logging/index/samples) does not use TextWriterTraceListener.

Can you please provide an example with TextWriterTraceListener?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Logging in .NET Core and ASP.NET Core #16174
