### ISSUE TITLE
Move Blazor Lifecycle topic UP in the sidebar TOC

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18009]
https://github.com/dotnet/AspNetCore.Docs/pull/18005

cc: @behroozbc

**Comment by behroozbc** [comment]
hi @guardrex  
i dont know what is name of this but i think be like is good
![image](https://user-images.githubusercontent.com/20381616/80284054-3aed5100-8731-11ea-81be-f7fbc17ef60e.png)
