### ISSUE TITLE
Move two Blazor topic sections

### ISSUE THREAD

**Issue by NaserParhizkar** [dotnet/AspNetCore.Docs#18007]
I am a little confused about 3 last code box title's, actually about last one 'HTML' file type is correct because it contains some script's, but about two others before last one why their code box title's are not 'razor' and they are 'CSHTML' file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a015ab57-3e5c-f5c8-338c-d491c3e9e3fb
* Version Independent ID: 951c8cfc-6aae-2e15-a085-66071d80f6a4
* Content: [ASP.NET Core Blazor hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui)
* Content Source: [aspnetcore/blazor/hosting-model-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-model-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @NaserParhizkar ... Those are Razor Pages that use the [Component Tag Helper](https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper), so they're correct showing `CSHTML`.

**_BUT_** ... I'm glad that you opened this issue to ask about those two sections. We created a topic a little while ago to cover integrating components into Razor pages and MVC views. I failed to move the content from this topic into the new topic. The new topic is at ...

https://docs.microsoft.com/aspnet/core/blazor/integrate-components

I'll use this issue to track moving those two sections. Leave this issue open. It will close automatically when the PR merges.

Thanks for commenting!

**Comment by NaserParhizkar** [comment]
How to add '@code { // }' in a 'CSHTML' file?

**Comment by guardrex** [comment]
Use `@functions` in Razor Pages ...

https://docs.microsoft.com/aspnet/core/mvc/views/razor#functions

`@code` is only for Razor components.

**Comment by NaserParhizkar** [comment]
OK, based on your previous comment's  '@code {  }' should have been '@function { }' in those sections.
Is it correct?

**Comment by guardrex** [comment]
Yes ... and I highly suspect **_find and replace_** is what happened there. There was a time early on in the development of Blazor that Razor components also used `@functions`. Then, they created the `@code` directive as an alias of `@functions` (AFAIK, they'll both work there). I think I probably did a find-and-replace to "fix them" everywhere in Blazor topics ... well ... "fix" 🙈 ... you see how well that worked. :smile:

I'll go ahead and move those sections and patch the examples right now.

**Comment by NaserParhizkar** [comment]
yes you right, I had forgotten about '@function{}' in 'Blazor file' previous releases.
Anyway ,Thank you very much, don't worry bro. it's great and I appropriate for your time and response's. Bless you.
