### ISSUE TITLE
PUT and DELETE are not working.

### ISSUE THREAD

**Issue by Geekays** [dotnet/AspNetCore.Docs#18006]
I just created the project in the similar manner. However, PUT and DELETE are not working. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by anhkhoaken** [comment]
you can use Post Man to test PUT HTTP and Delete HTTP. if you use the browser, it will be Post HTTP

**Comment by Geekays** [comment]
> 
> 
> you can use Post Man to test PUT HTTP and Delete HTTP. if you use the browser, it will be Post HTTP

I am trying with Postman only. But it is not working. I am running the API code from visual studion (without deploying to a web server) on Windows 10.

Hope you can help me. I am looking for a solution.

**Comment by prkhandelwal** [comment]
Can you please share the exact error u're getting & the payload u're sending?

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Geekays** [comment]
I think this is closed little in a haste.

**Comment by Geekays** [comment]
Just attached a screenshot from Postman showing the error and headers.

![image](https://user-images.githubusercontent.com/5683341/80350454-5e79de00-888e-11ea-96d5-388fa116e14e.png)
