### ISSUE TITLE
Blazor UserManager not supported Architecture conumdrum

### ISSUE THREAD

**Issue by bdnts** [dotnet/AspNetCore.Docs#18001]
I'm well aware of the reasoning behind `SignInManager` and `UserManager` not having official support, even though they mostly work.  And also the guidance to indirectly use `AuthenticationStateProvider` and directly use `AuthorizeView` component, and `Task<AuthenticationState>`.  However, this now creates an architecture conundrum, that unauthenticated users can't be worked with--except using `UserManager` which isn't supported.

The use case is a simple registration flow, where email confirmation is required prior to SignIn.
A User can be in a registered state  where they have Signed Up (lets say state 1), and confirmation email has been sent (state 2).  Once confirmed, (state 3) Authentication is possible.  While EmailConfirmed tracks that status in the Identity database, a RegistrationState Claim tracks overall progress (states 1-6).  

A User in state 1 or 2 cannot be authenticated, and therefore is not accessible to AuthenticationStateProvider (because there is no current user).  Only via UserManager, can the unauthenticated User information be retrieved (e.g. `UserManager.IsEmailConfirmedAsync()`, or RegistrationState claim [`UserManager.GetClaimsAsync()` etc.]), which is not a supported approach, hence the conundrum.

Please tell me I've missed something, like 
```
var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync(TUser);
```
?

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bdnts ... This falls more into the *product feedback* bucket. Best bet is to ask about it on the engineering repo. They might have a long-range plan (for Blazor WASM anyway) for the framework to provide some features that would ease setting up that type of flow, but I'm not aware of it if they do. Right now, it's *every-dev-for-themselves!* ⚔️

Ask them directly ....

https://github.com/dotnet/aspnetcore/issues

**Comment by ADefWebserver** [comment]
I am able to use SignInManager and UserManager in server side C# code in my Blazor WASM applications. See the Register.cshtml.cs page in the following Blog post:
http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4376/Implementing-Roles-In-Blazor-WebAssembly.aspx

**Comment by marwalsch** [comment]
The linked Issue in [dotnet/aspnetcore](https://github.com/dotnet/aspnetcore): [#21199](https://github.com/dotnet/aspnetcore/issues/21199).
