### ISSUE TITLE
Which nuget package to use for singnalR hub?

### ISSUE THREAD

**Issue by karataliu** [dotnet/AspNetCore.Docs#18018]
According to sample it uses 'Microsoft.AspNetCore.SignalR', the last version is published on 2018
There is a new package named 'Microsoft.AspNetCore.SignalR.Common', last version published in last month

What's the relationship between the two?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
You would no longer need to reference the NuGet package explicitly in 3.1 (or a few versions prior) as it is included in the shared framework. It's "just there" when you're building new ASP.NET Core 3.1 applications. 

Hope that helps!
