### ISSUE TITLE
Debugging web assembly on visual studio unable to inspect any value

### ISSUE THREAD

**Issue by kostasxagoraris** [dotnet/AspNetCore.Docs#18014]
[EDIT by guardrex to add the metadata. Please use the **This page** feedback button+form at the bottom of the topic to open new issues.]

After a lot of effort i managed to make the break points to hit debugging a blazor web assembly application . I did what ever the documentation said but the debugger was unable to bind the breakpoints. It seems that what is needed is the chrome debugger window to open immediately after the chrome window when I start to debug from visual studio.

But now after I managed to stop at the breakpoint it is not useful at all because i can't inspect any values no matter what their type is (int string objects arrays). 

I have installed visual studio 16.6.0 preview 4.0.

Is there something I could do?

![blazordebugging](https://user-images.githubusercontent.com/63858034/80286213-c2878f80-8732-11ea-9a49-6e187ed97e78.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@kostasxagoraris ... We've had the 3.2 release now. If you're still having this problem, open an issue with the product unit for investigation at ...

https://github.com/dotnet/aspnetcore/issues
