### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by BillOBrien-Palatine** [dotnet/AspNetCore.Docs#18015]
I created a const in the movies.cs class I called BindString 
public const string BindString = "Id,Title,ReleaseDate,Genre,Price,Rating";
I used it in 2 methods in MoviesController.cs
public async Task&lt;IActionResult&gt; Create([Bind(Movie.BindString)] Movie movie)
public async Task&lt;IActionResult&gt; Edit(int id, [Bind(Movie.BindString)] Movie movie)
Ideally when you add other properties to the class you will remember to add them to the BindString.  Just my idea.  BTW, add this string *after* you have scaffolded this class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
thanks
