### ISSUE TITLE
GetJsonAsync  Not Available 

### ISSUE THREAD

**Issue by raisircl** [dotnet/AspNetCore.Docs#18019]
Severity	Code	Description	Project	File	Line	Suppression State
Error: CS1061	'HttpClient' does not contain a definition for 'GetJsonAsync' and no accessible extension method 'GetJsonAsync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)	
So I have use 
Newtonsoft.Json
System.IO
Write following code :
 forecasts = JsonConvert.DeserializeObject&lt;WeatherForecast[]&gt;(File.ReadAllText("sample-data/weather.json"));
in the behalf of
            forecasts = await Http.GetJsonAsync&lt;WeatherForecast[]&gt;("sample-data/weather.json");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @raisircl ... It was a Preview 4 update that I missed. The new method is `GetFromJsonAsync`. I'll fix this topic up right now. The blog post with the updates is here :point_right: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/.

The most recent update (a few days ago) is Preview 5, which you can read about here :point_right: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/

Thanks for calling this out.

**Comment by guardrex** [comment]
I see how this happened. When I performed the search to replace the method name, I scoped my search to markdown files. The file that supplies this is actually a *.razor* file in a samples folder. 🙈
