### ISSUE TITLE
How to test the app RazorPagesMovie

### ISSUE THREAD

**Issue by satoryosuke4** [dotnet/AspNetCore.Docs#18016]
At the step, to test the app, i got the same error in the tutorial, so i restarted from the migration step.

-After the PMC, there's an examination paragraph, with 2 codes.
The first seems shows some errors since the update of Visual Studio, so i let 
the new code by default, and effectively there's some new lines added.

-I don't find the code in the tutorial, in any folder of the solution explorer, for the second.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What error?

**Comment by satoryosuke4** [comment]
When, debug the webapp, there's a page which i have to add /movies. But, there's this message.

SqlException: Cannot open database "RazorPagesMovieContext-GUID" requested by the login. The login failed.
Login failed for user 'User-name'.

**Comment by Rick-Anderson** [comment]
You missed a step in the instructions

**Comment by satoryosuke4** [comment]
I'll watch more carefully, thanks for your help.

**Comment by Rick-Anderson** [comment]
Per the doc

![image](https://user-images.githubusercontent.com/3605364/80328708-cd4a2f00-87db-11ea-92e2-a80d8a0b1a45.png)
