### ISSUE TITLE
File Signature magic numbers

### ISSUE THREAD

**Issue by gbjbaanb** [dotnet/AspNetCore.Docs#18012]
I note that Microsoft has a class for determining file types already, but it does a lookup on file extension (which we know, some pesky users will modify to cheat the system), so would it be possible to extend that to also return file types based on the contents. 

eg, this exists in the Microsoft.AspNetCore.StaticFiles assembly.

new FileExtensionContentTypeProvider().TryGetContentType(FileName, out mimeType);

Admittedly, this determines mime types, not necessarily file types, but it'd be nice to have a similarly definitive method so we all don;t have to reinvent this wheel over and over.

I've updated the code sample in the page to reflect a more complex example of mp4 files, as they require an offset. The file signatures DB also seems to be somewhat incomplete and not available for updates - https://www.garykessler.net/library/file_sigs.html appears to be better.

		private static readonly Dictionary&lt;string, (int offset, List&lt;byte[]&gt; data)&gt; _fileSignature = new Dictionary&lt;string, (int, List&lt;byte[]&gt;)&gt;
			{
				{ ".jpeg", (0, new List&lt;byte[]&gt;
					{
						new byte[] { 0xFF, 0xD8, 0xFF, 0xE0 },
						new byte[] { 0xFF, 0xD8, 0xFF, 0xE2 },
						new byte[] { 0xFF, 0xD8, 0xFF, 0xE3 },
					})
				},
				{ ".mp4", (4, new List&lt;byte[]&gt;
					{
						new byte[] { /*ftyp*/ 0x66, 0x74, 0x79, 0x70, /*mmp4*/ 0x6D, 0x6D, 0x70, 0x34 },
						new byte[] { /*ftyp*/ 0x66, 0x74, 0x79, 0x70, /*mp41*/ 0x6D, 0x70, 0x34, 0x31 },
						new byte[] { /*ftyp*/ 0x66, 0x74, 0x79, 0x70, /*mp42*/ 0x6D, 0x70, 0x34, 0x32 },
					})
				},
				{ ".webm", (0, new List&lt;byte[]&gt; { new byte[] { 0x1A, 0x45, 0xDF, 0xA3 } }) },
				{ ".mkv", (0, new List&lt;byte[]&gt; { new byte[] { 0x1A, 0x45, 0xDF, 0xA3 } }) },
				{ ".pdf", (0, new List&lt;byte[]&gt; { new byte[] { 0x25, 0x50, 0x44, 0x46 } }) },
				{ ".odt", (0, new List&lt;byte[]&gt; { new byte[] { 0x50, 0x4B, 0x03, 0x04 } }) },
				{ ".docx", (0, new List&lt;byte[]&gt; { new byte[] { 0x50, 0x4B, 0x03, 0x04, 0x14, 0x00, 0x06, 0x00 } }) },
				{ ".doc", (0, new List&lt;byte[]&gt; { new byte[] { 0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1 } }) },
			};

		public static bool CheckFileContents(string ext, Stream stream)
		{
			(int offset, List&lt;byte[]&gt; data) signatures;

			using var reader = new BinaryReader(stream);
			if (_fileSignature.TryGetValue(ext, out signatures))
			{
				var headerBytes = reader.ReadBytes(signatures.offset + signatures.data.Max(m =&gt; m.Length));

				return signatures.data.Any(signature =&gt; headerBytes.Skip(signatures.offset).Take(signature.Length).SequenceEqual(signature));
			}
			return false;
		}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#validation)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to File Uploads topic enhancements and master issue #12285
