### ISSUE TITLE
providing a password when exporting the certificate is necessary

### ISSUE THREAD

**Issue by baharestani** [dotnet/AspNetCore.Docs#18017]
It should have been mentioned that providing a password when exporting the certificate is necessary otherwise the exported file will not contain the private key and your app will throw '`The server mode SSL must use a certificate with the associated private key - during TLS handshake`' during runtime. The error isn't helpful when you don't know the reason for missing private key is using a blank password during the export.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Closing as the doc already calls out for providing password.
