### ISSUE TITLE
An error occurs when you hit the <Previous> Button if you have just one page with items

### ISSUE THREAD

**Issue by codename95** [dotnet/AspNetCore.Docs#18023]
An unhandled exception occurred while processing the request.
SqlException: The offset specified in a OFFSET clause may not be negative.
Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action&lt;Action&gt; wrapCloseInAction)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
There's code that doesn't enable previous button for that reason. There are things you can do to get around that.
