### ISSUE TITLE
"Strong/Weak" vs "Static/Dynamic"

### ISSUE THREAD

**Issue by AlexScheller** [dotnet/AspNetCore.Docs#18025]
Throughout the document, the terms "strong" and "weak" seem to be used to describe "static" and "dynamic" typing, not "strong" and "weak" typing. I know there's not a universal definition of these terms, but It seems like the author is intending to convey the concepts of static vs dynamic typing, since they reference explicit type declaration (or the lack thereof) and the *time* (compile vs run) that types are checked, rather than if implicit conversions take place or not. Not a huge problem, but could be misleading to learners unfamiliar with these concepts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Strongly typed data (viewmodel)](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-3.1#strongly-typed-data-viewmodel) has a good definition, and that's a standard definition.

[Weakly typed data (ViewData, ViewData attribute, and ViewBag)](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-3.1#weakly-typed-data-viewdata-viewdata-attribute-and-viewbag) also has a good definition.

Neither of theses could be labeled more accurately static or dynamic.
