### ISSUE TITLE
Newer VS2019

### ISSUE THREAD

**Issue by EdwardL75** [dotnet/AspNetCore.Docs#18022]
Seems like even though this post was just updated 4 months ago there is some out-dated info. Basically most of the Identity stuff is not viewable or "exposed":

The generated project provides ASP.NET Core Identity as a Razor Class Library. The Identity Razor Class Library exposes endpoints with the Identity area. For example:
/Identity/Account/Login
/Identity/Account/Logout
/Identity/Account/Manage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @EdwardL75 ... It says that the **_endpoints_** are exposed in the Identity **_area_**, and those remarks are correct.

If you want the actual pages added to the app, then you "scaffold" them in ...

https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity
