### ISSUE TITLE
Disable registration does not work in asp.net core angular template (with authentification)

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18029]
Hi team, 
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.de-de/issues/65
@3im3r commented 3 days ago — with docs.microsoft.com
In this template there is already a subset available, a new scaffold is not compatible with the existing code.

To disable the register comment out the link in _LoginPartial.cshtml:
@*
&lt;p&gt;
&lt;a asp-page="./Register" asp-route-returnUrl="@Model.ReturnUrl"&gt;Register as a new user&lt;/a&gt;
&lt;/p&gt;
*@

And add endpoint redirections in code:
app.UseEndpoints(endpoints =&gt;
{
endpoints.MapGet("/Identity/Account/Register", context =&gt; Task.Factory.StartNew(() =&gt; context.Response.Redirect("/Identity/Account/Login", true, true)));
endpoints.MapPost("/Identity/Account/Register", context =&gt; Task.Factory.StartNew(() =&gt; context.Response.Redirect("/Identity/Account/Login", true, true)));
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@haok we have [Disable register page](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli#disable-register-page)

Should we add this tip for angular?
