### ISSUE TITLE
VS Mac Console and Web template instructions will need updating for version 8.6

### ISSUE THREAD

**Issue by pjcollins** [dotnet/AspNetCore.Docs#18030]
# Issue description
The getting started instructions for various .NET Core templates in VS Mac will need to be updated soon to replace instances of:

> Select **.NET Core** > **App** >

with 

> Select **Web And Console** > **App** >

See the screen shot below for the new template hierarchy in VS Mac 8.6:
![Screen Shot 2020-04-27 at 12 35 57 PM](https://user-images.githubusercontent.com/2000163/80398212-418cdd00-8885-11ea-8938-8e246d9df5c6.png)

# Software versions
Visual Studio Enterprise 2019 for Mac (Preview)
Version 8.6 Preview (8.6 build 4274)

**Comment by ssimontis** [comment]
Also, the Xamarin.Mac documentation is 2 years out of date at this point and needs some serious updating to be relevant. None of the screenshots or instructions correspond to modern versions of XCode. It needs to be either fixed or deprecated because they are useless right now and create a terrible first time experience for new Xamarin users.

**Comment by guardrex** [comment]
@pjcollins ... I'm going to take care of the Blazor aspects on a separate Blazor issue. I'll open it and ping u there.

**Comment by guardrex** [comment]
@wadepickett VS4Mac Preview 4 is out now :tada:. Do you want me to just do the Blazor reference (there's one Blazor topic that needs this addressed, which I'm putting on a PR for Blazor 3.2 RC updates right now), or do you want me to do them all and resolve this whole issue?

**Comment by wadepickett** [comment]
@guardrex, thanks for the offer.  I just finished some high pri but minor updates for the EF and .NET core repo.  I can hit this now.  If you hit the Blazor Reference that's great, I can hit the rest.   However it is not clear to me what the scope is for the topics that need updates.  It sounds like all Mac tutorials where we step through selecting any template, do I understand that correctly?

**Comment by guardrex** [comment]
Search for ...

> \*\*.NET Core\*\* > \*\*App\*\*

... and replace with ...

> \*\*Web and Console\*\* > \*\*App\*\*

... I think 🤞 that will do the trick.

**Comment by guardrex** [comment]
I did the Blazor one here :point_right: https://github.com/dotnet/AspNetCore.Docs/pull/18066/files#diff-aad9be3b2ba853ffc4d9ec1bb908d272R93

**Comment by wadepickett** [comment]
Thanks, I guess where I am not connecting is the preview scope.  I have not been up on the VS Mac Preview discussions so I don't know what the scope is.  We are putting the preview instructions in all content (which I would not expect) or is there a subset of Preview specific content?

**Comment by wadepickett** [comment]
@guardrex, since it is already out, we are short on time, you started and I am catching up on what is happening with the preview, perhaps it would be best if you finish the whole thing for this issue and I'll pick off something else right now.

**Comment by Rick-Anderson** [comment]
@pjcollins we don't have a way to support VS Mac preview releases. Additionally, we don't have the resources to do much VS Mac support. We get much of our VS Mac support from the Mac PMs such as  @sayedihashimi 

cc @scottaddie

**Comment by guardrex** [comment]
Good point @wadepickett ... I have *Blazor on the 🧠* 😁. I only needed the Blazor content updated. We tell all Blazor 🐈 that if they want Blazor to work as well as it can, then they must be on the VS4Mac preview.

Since we can't version 3.2, an option (for May) is something like ...

> If using VS4Mac earlier than version 8.6, select \*\*.NET Core\*\* > \*\*App\*\*. If using VS4Mac version 8.6 or later, select \*\*Web and Console\*\* > \*\*App\*\*.

**Comment by wadepickett** [comment]
@guardrex, no worries.  If there is a subset specific to Blazor where you and @Rick-Anderson decided to tie to previews, then it might be best for you to handle the rest since you are already rolling.  Thanks again.

**Comment by guardrex** [comment]
Sure ... he'll let me/us know if he wants ...

* Text to cover <8.6 and >=8.6.
  * Now, or ....
  * In May at VS4Mac 8.6 GA
* Text to only cover >=8.6 but we don't do anything until 5.0 lands, when the change can be properly versioned.

**Comment by sayedihashimi** [comment]
I like the "Text to cover <8.6 and >=8.6" option
