### ISSUE TITLE
Example Console logger doesn't work because it doesn't dispose LoggerFactory;

### ISSUE THREAD

**Issue by samrueby** [dotnet/AspNetCore.Docs#18039]
`LoggerFactory` implemented `IDisposable`. It needs to be disposed.

The following example code on this page, copied-and-pasted, does not work for me:
```
var loggerFactory = LoggerFactory.Create(builder =>
{
builder
.AddFilter("Microsoft", LogLevel.Warning)
.AddFilter("System", LogLevel.Warning)
.AddFilter("LoggingConsoleApp.Program", LogLevel.Debug)
.AddConsole()
.AddEventLog();
});
ILogger logger = loggerFactory.CreateLogger<Program>();
logger.LogInformation("Example log message");
```

You will not see any output. Disposing the loggerFactory allows the output to be seen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#console-provider)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Just tested and code works fine.

**Comment by samrueby** [comment]
Maybe I should have mentioned I was testing in a .NET framework console app, but boy that was a quick close!
