### ISSUE TITLE
How to use Static Files with CatchAll Routing?

### ISSUE THREAD

**Issue by ackava** [dotnet/AspNetCore.Docs#18038]
Currently if router has catch all, all requests go to catch all instead of serving static files. It seems we need some clarity on how to configure it with new router. This was working correctly in 2.2, turning of catch all fixed this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1#usefileserver)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Currently if router has catch all, all requests go to catch

Do you mean endpoint routing?

`UseStaticFiles` enables static files.

**Comment by ackava** [comment]
I guess you have not understood the comment.

1. Yes I am using `UseStaticFiles`
2. And one of my mvc route has CatchAll route `[HttpGet("{*all}, Order = Int.MaxValue)]`

This should work, but it is not working, I guess order of `UseStaticFiles` and `MapRoutes` needs to be arranged.

This is correctly working in 2.2.

Is there any documentation says that this is not possible in 3.*+ ?

There is no extension method for `routes.MapStaticFiles()` similar to `routes.MapControllers()`, is it missing?

**Comment by Rick-Anderson** [comment]
Create the simplest possible project the reproduces the problem and send the GitHub link.

**Comment by ackava** [comment]
https://github.com/ackava/asp-net-core-static-files-not-working

You can run this project which reproduces the issue.

I don't know if it is a bug or a missing piece in documentation to configure both.

**Comment by Rick-Anderson** [comment]
per the routing docs, [ `[HttpGet("{*all}", Order = int.MaxValue)]`](https://github.com/ackava/asp-net-core-static-files-not-working/blob/master/StaticFilesWithRouting/Controllers/DefaultController.cs#L13) is doing a greedy match.

The following code fixes the problem:

`[HttpGet("api/{*all}", Order = int.MaxValue)]`

cc @serpent5  @rynowak

**Comment by serpent5** [comment]
The static-files middleware will not handle the request if an endpoint has been matched ([source](https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L71)). Place the call to `UseStaticFiles` _above_ `UseRouting`, as shown in [Middleware Order](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order).

**Comment by davidfowl** [comment]
@rynowak

**Comment by Rick-Anderson** [comment]
@serpent5  thanks, that fixes it

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseStaticFiles();

    app.UseRouting();

    //app.UseStaticFiles(new StaticFileOptions {
    //    FileProvider = new PhysicalFileProvider(Path.Combine(env.ContentRootPath, "wwwroot"))
    //});

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();

        endpoints.MapGet("/", async context =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    });
}
```

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/aspnetcore/issues/18791 could have prevented this.

**Comment by SteffenBlake** [comment]
This issue comes up in 2023 now for similar searches on the topic of how to make StaticFiles play nice with a generic catch all endpoint, so I wanted to comment the solution here:

The solution is to use the very specific methods for this task that are designed to prevent this issue.

`app.MapFallback(...)`
`app.MapFallbackToFile(...)`

Etc etc (there's a few MapFallback... methods), all serve the purpose of being a final "catch all" endpoint that you must declare at the very end of `Program.cs` right before `app.RunAsync()`

This will avoid "overriding" your static file routes.
