### ISSUE TITLE
[Blazor] Async guidance for Blazor

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18036]
We are missing some guidance regarding async on our docs (or at least I couldn't find it).

We should have explicit guidance about not calling `.Result` or any other method on tasks that blocks the thread.

There might be other guidance we need to provide here.

**Comment by guardrex** [comment]
I think on this one the question is **_where_** to cover it. I think in the *Components* topic. Sound right to you, @mkArtakMSFT?
