### ISSUE TITLE
Web API conventions return type

### ISSUE THREAD

**Issue by EngSayed** [dotnet/AspNetCore.Docs#18047]
When we use `ProducesResponseType `we can specify the return type of the action "Model", how to specify the return type while using Web API conventions? 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Comment by EngSayed** [comment]
You didn't provide any solution nor any suggestion before closing the issue!
