### ISSUE TITLE
Missing  Microsoft.VisualStudio.Web.CodeGeneration.Tools package

### ISSUE THREAD

**Issue by DiomedesDominguez** [dotnet/AspNetCore.Docs#18040]
For the scaffold section, it's also required run ```dotnet tool install -g dotnet-aspnet-codegenerator```, later to add the ```Microsoft.VisualStudio.Web.CodeGeneration.Tools``` package beforre running ```dotnet aspnet-codegenerator identity -dc WebApp1.Data.ApplicationDbContext --files "Account.Register;Account.Login;Account.Logout"```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=netcore-cli#next-steps)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Introduction to Identity #16230
