### ISSUE TITLE
Passing render fragments to components

### ISSUE THREAD

**Issue by joseph-turk** [dotnet/AspNetCore.Docs#18053]
Is it possible to pass render fragments to Blazor components when rendering them inside an MVC view? Including a component with a ChildContent render fragment like this did not work:

```
<component type="typeof(MyComponent)" render-mode="ServerPrerendered">
  <p>Content to go inside ChildContent</p>
</component>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c1a41f-0615-ef27-f9a3-032b9db702a3
* Version Independent ID: 8ac3492b-34dd-d94e-e661-c3028ca2acdb
* Content: [Component Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I don't think that that's a supported scenario. You can pass a parameter to the component with the content in a similar fashion to how the `MyClass` example works.

These issues are triaged on Fridays, so hopefully you'll get some feedback on 5/1 here.

**Comment by joseph-turk** [comment]
Ok, that makes sense. The `MyClass` example isn't a good fit for my use case because the component that I'm trying to render is more of a container component that can have arbitrary elements inside it.

This would be an excellent feature to have. I'm currently trying to add as many new features to an existing MVC app as I can using Blazor components, and this would make it much easier to standardize between older MVC views and newer routable Blazor components.

**Comment by guardrex** [comment]
When Artak sees this on Friday, he'll move it to the engineering repo if he thinks it should be discussed further.

**Comment by guardrex** [comment]
@joseph-turk Since this is more of a feature request than a doc issue, it's best if you want to float it for it to go to the engineering repo. You can open an issue with them here ...

https://github.com/dotnet/aspnetcore/issues
