### ISSUE TITLE
GDPR cookie consent in Blazor

### ISSUE THREAD

**Issue by schwabenlander** [dotnet/AspNetCore.Docs#18055]
Could you explain how to implement GDPR cookie consent in a Blazor app? Something like: https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.1 but for Blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@schwabenlander It's not something that will work OOB at this time in a Razor component. You would need to roll your own component to do it.

I'll leave this on the Blazor.Docs project for triage this Friday. Artak will look :eyes: and advise if we should take on docs to do it (*next year* 🏃😅 ... or in *2022!* :smile: lol), the framework should provide something, or else we'll leave it to the community to provide solutions.

**Comment by guardrex** [comment]
@schwabenlander It's probably best if you ask the product unit directly about this. We don't have anything specific to document on it. The guidance right now would be that a dev should build their own component to handle it across their Blazor app. Open an issue for engineering if you still want feedback on this or to suggest that the framework offer something built-in for it ...

https://github.com/dotnet/aspnetcore/issues

**Comment by majorimi** [comment]
You can use this GDPR Consent component from [Nuget](https://www.nuget.org/packages/Majorsoft.Blazor.Components.GdprConsent/). However it is only helping you to save work on UI side. It does not restricts any Cookies or Tracking scripts.
