### ISSUE TITLE
MVC View creation change in VS 2019

### ISSUE THREAD

**Issue by wsmelton** [dotnet/AspNetCore.Docs#18068]
Not a C# dev so just going through this to get a sample app created. I find that to add a view to the project the only options are "Razor View", so seems that the workflow has changed. The initial steps to create the view and the screenshots would need to be updated for this process in VS 2019.

I don't have lower versions installed to verify the process is any different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's the same.

**Comment by wsmelton** [comment]
I just went through the whole tutorial and can tell you the instructions could not be followed as is on 2019.

But if y'all want to leave it that is your decision.

**Comment by wsmelton** [comment]
Your screenshot in the doc shows this:
![image](https://user-images.githubusercontent.com/11204251/80747318-e0fdda00-8ae8-11ea-9a1d-b80192859e9c.png)

Your steps show:
```
In the Add New Item - MvcMovie dialog

In the search box in the upper-right, enter view

Select Razor View

Keep the Name box value, Index.cshtml.

Select Add
```

**Comment by Rick-Anderson** [comment]
Dup of #16818 
This will get updated in the next doc sweep.
