### ISSUE TITLE
Background tasks demo in .Net core

### ISSUE THREAD

**Issue by veteran1** [dotnet/AspNetCore.Docs#18069]
Did not understand why a semaphore is used here, if the intent is to allow only one thread at a time
I think ManualResetEventSlim is more suitable for this situation?.
https://github.com/dotnet/AspNetCore.Docs/blob/83111b4009e4c39d5c85e8347d0a38779ccc824b/aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/BackgroundTaskQueue.cs#L21

**Comment by guardrex** [comment]
Hello @veteran1 ... Would you mind re-opening this using the **This page** feedback button and form at the bottom of the topic? It will add metadata to your issue to indicate the topic and automatically ping the author.
