### ISSUE TITLE
Warning - CreateWebHostBuilder -

### ISSUE THREAD

**Issue by Chapeaunyra** [dotnet/AspNetCore.Docs#18063]
Hey MS,
You have forgotten to change - CreateWebHostBuilder - to - CreateHostBuilder - (I guess ?) during "Initialize DB with test data".
It's not really important because Visual Studio auto-generate few lines after the right method, but for a real beginner it can be a little weird.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the tutorial

This tutorial has not been updated to ASP.NET Core 3.0.
