### ISSUE TITLE
Facebook requires valid response from domain/signin-facebook to move to production

### ISSUE THREAD

**Issue by CusterN** [dotnet/AspNetCore.Docs#18067]
The [tutorial ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1) on how to add an external login provider provides instructions that work while the app is in "development" through facebook dev. When you try to move to production, Facebook shows the following error:

_URL(s) listed on your app dashboard settings could not be accessed for platform compliance review. Kindly make sure that the following field(s) on your app dashboard are working correctly:
Website: Site URL https://<domain.net>/signin-facebook
The corresponding URL(s) should return a successful HTTP status code. You can verify this using the Sharing Debugger._

Until you move your app to production in facebook dev, users will get an error message when trying to athenticate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc and error message you need to change the callback URL
