### ISSUE TITLE
No background color for the selected row

### ISSUE THREAD

**Issue by crismunt** [dotnet/AspNetCore.Docs#18062]
I was running the app for this section of the tutorial on Instructors, and I tried to select an instructor. The "select" operation works fine, but there was nothing changed for background color. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by crismunt** [comment]
I replaced the code  -- selectedRow = "success";-- with  selectedRow = "alert-success"; and now is woking fine.

**Comment by Rick-Anderson** [comment]
Thanks for the report.
