### ISSUE TITLE
Document appcontext switch for catch all routing fix

### ISSUE THREAD

**Issue by rynowak** [dotnet/AspNetCore.Docs#18072]
See: https://github.com/dotnet/aspnetcore/issues/21114

This is a relatively impactful bug that we're fixing with an **opt-in** switch in an upcoming patch. Once this is gone out in servicing we should document the switch prominently.

This should go in the 3.1 version of the main routing doc where catch all routes are discussed, as well as in the 2.2->3.X migration docs. Users porting an app from 2.1->3.1 have a high potential to be broken if they make use of catch all routes in some specialized ways.

This bug is already fixed in 5.0, so we don't need to document the workaround there.

The fix looks like:

```C#
AppContext.SetSwitch("Microsoft.AspNetCore.Routing.UseCorrectCatchAllBehavior", true);
```

Put this in Program.Main as the first statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak  Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

Add this to Catch-all  section in [Route template reference](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#route-template-reference)
