### ISSUE TITLE
container issue: Use the Angular project template with ASP.NET Core

### ISSUE THREAD

**Issue by dankellett** [dotnet/AspNetCore.Docs#18074]
This is the container issue for this doc.  Reopen each issue you are working on so the owner is notified.

* Add non-server side build directions to docs #10683
* Example for Pass data from .NET code into TypeScript code #22102
* Pre-rendering APIs are now obsolete.: The UseSpaPrerendering API mentioned in this article under section "Pass data from .NET code into TypeScript code" is now deprecated in Core 3.1. I can see passing data to typescript code still valuable. Is there an new API for this?
* spa.UseAngularCliServer(npmScript: "start"); still doesnt work for me 3rd Jan 2021 #21102
* Outdated Angular version #22487

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#pass-data-from-net-code-into-typescript-code)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by MackinnonBuck** [comment]
I'm going to close this out - I believe each of the issues linked above have either been addressed or are no longer relevant due to product changes. Happy to reopen if there is any disagreement.
