### ISSUE TITLE
Terms that should not be localized

### ISSUE THREAD

**Issue by JasonCard** [dotnet/AspNetCore.Docs#18076]
This article contains product name "Razor" that should not be localized and some of those are being over-localized by Machine Translation. It would be great if those terms can be blocked from localization by using [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @JasonCard ... I'll get that squared away this weekend.

@Rick-Anderson I'll only have time to do the Blazor docs ... it's just a find-and-replace for that set given that I created all of the `no-loc` metadata entries with the same content (i.e., with "Blazor" and "SignalR"). I guess you would like a companion issue to update the rest of the docs?

**Comment by guardrex** [comment]
cc: @wadepickett on that last remark. I just got wind of the loc repo issue.

**Comment by guardrex** [comment]
Actually ... you know ... since we don't have a universal way to do this yet, we could have a `no-loc` on every topic with the no-loc words and use the same word set across every topic. Then, find and replace would work everywhere every time. I suppose I could script kitty 🐱 that if you want me to. Let me know. :ear:

**Comment by Rick-Anderson** [comment]
@guardrex  go for the script
cc @scottaddie

**Comment by wadepickett** [comment]
For the script are you talking about setting the no-loc value in the topic meta data like this below correct?  Rather than inline to the text:

`no-loc: [Blazor, SignalR, Razor]`

One other  item.  This particular issue on this topic was within a title used in a link.  Just in case that matters for any reason.

**Comment by guardrex** [comment]
Yes ... that's right. I'd use one of my magic scripts to do the heavy lifting on that.

**Comment by wadepickett** [comment]
Although this is fixed/closed for the original English version.  To verify the fix can be seen by customers, here is the link of the Polish (pl-pl) version and the highlighted word that should show up as "Razor" , replacing the previous translation _golenia_ which means "shaving"

https://docs.microsoft.com/pl-pl/aspnet/core/blazor/components?view=aspnetcore-3.1#conditional-html-element-attributes
 
![image](https://user-images.githubusercontent.com/10985336/81246439-7a872900-8fcc-11ea-80ba-e9a54005904d.png)

**Comment by JasonCard** [comment]
I've also been looking into this and unfortunately we've run into an engineering issue that may take some time to resolve. The source string is: 
For more information, see <xref:mvc/views/razor>.
So the translation of <xref:mvc/views/razor> (topic title) is coming from this topic:
[https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/mvc/views/razor.md)

It was one of the files fixed in the script with added no-loc metadata. However, our automation run into check-in error saying that the yaml header is invalid. It seems we've run into a side effect from the no-loc feature. the machine translated handback failed during the check-in process. Check-in failed due to invalid yaml header error. This error was triggered by the no-loc metadata, as the tags added from the no-loc feature caused the title metadata in yaml header to become localizable. For some reason, it seems when

**Comment by JasonCard** [comment]
I've also been looking into this and unfortunately we've run into an engineering issue that may take some time to resolve. 
The source string is:
For more information, see \<xref:mvc/views/razor\>.
So the translation of \<xref:mvc/views/razor\> (topic title) is coming from this topic:
https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/mvc/views/razor.md

It was one of the files with no-loc metadata added from the script. However, our automation run into check-in error saying that the yaml header is invalid. The yaml header is usually not localized, but it seems we've run into a bug where yaml header became localizable. This seems to only happen when the no-loc term (e.g. Razor) is at the beginning of a title. It appears to be unwanted side effect of the no-loc feature and will need our engineering team to take a look. Will update.

**Comment by wadepickett** [comment]
Testing the temporary workaround of changing to lower-case for the term "Razor" in the title meta data with pr #18192.   After the translation runs in a few days we will see if that works.

**Comment by wadepickett** [comment]
JasonCard was able to verify this issue is fixed for Razor in the localized content:

https://docs.microsoft.com/pl-pl/aspnet/core/blazor/components?view=aspnetcore-3.1#conditional-html-element-attributes
Aby uzyskać więcej informacji, zobacz odwołanie do składni **Razor** dla ASP.NET Core.
