### ISSUE TITLE
Q: What is the benefit of streaming?

### ISSUE THREAD

**Issue by YehudahA** [dotnet/AspNetCore.Docs#18070]
It is not clear what is the benefit of reading manually parsing of the request body ("Streaming"), above using ```IFormFile``` ("Buffering").

You say that ```IFormFile``` is for uploading small files, and for large files it's better to use streaming.

But ```IFormFile``` also have only streaming methods. so where is the buffering?

In addition, in your examples, streaming method also ended up with bufferning. the ```ProcessFormFile``` read all data to byte array.

So, what is the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to  File Uploads topic enhancements and master issue #12285
