### ISSUE TITLE
Add "Consume [static] content from a referenced RCL in C# Server Side"

### ISSUE THREAD

**Issue by Arlorean** [dotnet/AspNetCore.Docs#18073]
I struggled for a long time to understand how to access the static content in wwwroot from a RCL on the Blazor Server side. It would be useful to expand the docs to cover this. This is what I've found works but I may have it wrong:

```
@using Microsoft.AspNetCore.Hosting
@inject IWebHostEnvironment Environment

@code {
    byte[] ReadAllBytesFromRCL(string library, string path) {
        var fileInfo = Environment.WebRootFileProvider.GetFileInfo($"_content/{library}/{path}");
        return File.ReadAllBytes(fileInfo.PhysicalPath);
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Create reusable UI using the RCL project #16639
cc @guardrex  - Blazor Server side shouldn't make a difference - right?

**Comment by Arlorean** [comment]
It's probably very clear if you're used to ASP.NET/Blazor but coming from the Desktop/WPF world I really didn't have a clue where to get the files for wwwroot from on the server side. It wasn't specific to RCLs, even the vanilla Blazor project didn't show me how to do this. On the client side we can `@inject HttpClient Http` and then call `await Http.GetByteArrayAsync("myfile.dat")`. I wanted the equivalent call from the server side but I didn't find it easy to discover `@inject IWebHostEnvironment Environment` and then `Environment.WebRootFileProvider` in the documentation. I'm happy to close this off though. Maybe my comments will help the next person looking for the solution I was. Thanks for the quick reply. I'm loving Blazor!
