### ISSUE TITLE
Overly long code sample

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/AspNetCore.Docs#18082]
The code section following "When using WebSockets and Server-Sent Events, the token is transmitted as a query string parameter. To support this on the server, additional configuration is required:" contains a ton of stuff which is not relevant (even establishing a database context), and it is not clear at a glance what part of it is the "additional configuration". Overly long samples containing irrelevant information makes it cumbersome to quickly check out what you need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@Tommigun1980  thanks for bringing this to our attention. One of our goals is to provide the simplest possible complete snippets that demonstrate the point.

**Comment by bradygaster** [comment]
I'm closing this and want to explain why - I feel that this topic - auth - is *always* something that requires a bit of discussion. The code for it is literally as simple as we could make it (and we even had some colorful feedback as it was "less secure than it needed to be" by making it even less verbose). 

If you have specific feedback or ideas on how this doc could be improved, please file another issue (or series of them) on things you'd like to see here. But this code is about as simple as we could have made it without being irresponsible and downplaying some of the requirements we feel would make one's code more secure.
