### ISSUE TITLE
SignalR Hubs doc shouldn't contain basic C# rules

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/AspNetCore.Docs#18081]
The documentation suddenly assumes that the user doesn’t know how interfaces work:
"Any methods defined on the interface can still be defined as asynchronous. In fact, each of these methods should return a Task. Since it's an interface, don't use the async keyword."

This is redundant and confusing as it has nothing to do with the subject at hand. Why is it even bringing this up? I guess that the message is that it is mandatory that the interface methods used in strongly typed hubs return tasks, but the message gets muddled there.

Then there is the note section which reads:
"The Async suffix isn't stripped from the method name. Unless your client method is defined with .on('MyMethodAsync'), you shouldn't use MyMethodAsync as a name."

I have no idea what it’s trying to say - why can’t I use MyMethodAsync as a name, why does the doc even care about what I name my methods, and why does it assume that the reader doesn’t know C#?

These are explaining generic language features while not conveying any information about Hubs, and should imho be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@Tommigun1980  great comments. This doc needs a UE scrub. A quick look.

* Avoid idiomatic expressions which don't machine translate.  is that it relies on a `magic string` 
* You can specify a return type and parameters, including complex types and arrays, as you would in any C# method.  @Tommigun1980  this should be deleted. Why would you think this isn't true?
* Clients can call methods that are defined as public. -> Clients can call `public` methods.
* Remove `you` unless it aids in clarity. 
  * The SignalR Hubs API enables you to call methods on connected clients from the server.
  * The SignalR Hubs API enables methods to be called on connected clients from the server. In this case, you is not calling them, connected clients are. 
  * In the client code, you define methods that are called from the server.
  * Methods are defined in the client code that are called from the server.
* The SignalR middleware requires some services, which are configured by calling services.AddSignalR. -> SignalR middleware is enabled with `AddSignalR`. Show the complete snippet, not just a call. Import the snippet.

That's just looking at the first couple of paragraphs.

**Comment by bradygaster** [comment]
@Rick-Anderson or @scottaddie i'd love to have your editorial view on this. Is it something with which we could get your help on this doc? Or you want me to take a pass at removing the extraneous stuff and let you review and suggest?

**Comment by Rick-Anderson** [comment]
@bradygaster Please create a PR and remove all the extraneous stuff. I'll have @wadepickett  do an edit pass to clean up the doc.
