### ISSUE TITLE
Example for IEnumerable<T> action as non-blocking, is Incorrect and misleading

### ISSUE THREAD

**Issue by SDP190** [dotnet/AspNetCore.Docs#18090]
Quote:
> Both of the preceding actions are non-blocking as of ASP.NET Core 3.0

However the first example seems to be incorrect, since the first action example calls: `_repository.GetProducts()`
 which returns a List<Product> object - as shown in first example on this page - it is a synchronous blocking call to the database returning a List. Only if return type of `GetProducts` would be `IAsyncEnumerable` then even if the controller action signature itself would be IEnumerable<T> still the serializer would detect its actually an IAsync and would iterate over it asynchronously.

Is that right?

Quote:
![Capture](https://user-images.githubusercontent.com/16751213/80831301-8af86780-8bb8-11ea-994e-b8d7bba2547a.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@SDP190  See #17259
Moved to Controller action return types Master issue #18092

**Comment by SDP190** [comment]
Hi, @Rick-Anderson, issue #17259 doesn't refer or solve at all to the issue I described above.
The issue is very simple, again:
Since `GetOnSaleProducts` has a call to `_repository.GetProducts()` which itself is a blocking function -as demonstrated in a preceding code example on that page in the docs- it returns `List<Product>` not `IAsyncAnumerable<Product>` or `Task<List<Product>>` :

![GetProducts](https://user-images.githubusercontent.com/16751213/82466474-73612000-9a8e-11ea-8c0c-3dd9de438889.png)

So `GetOnSaleProducts` will also be blocking even in Asp.Net Core 3!

So either you have to clarify that `_repository.GetProducts()` returns an `IAsyncEnumerable<Products>` and thus you would have to modify the example code  shown in the embedded image, either change the code here in this example so `GetOnSaleProducts` shouldn't call a blocking function!

**Comment by SDP190** [comment]
Hi, @Rick-Anderson, this docs is still incorrect even the net6 version.

Since `GetProducts` seems to return a type `List<Product>` that means it already blocks (iterates to get all records into memory and only then returns the full List) !
Either change GetProducts or create another example function which should return IEnumerable<Products>, so assuming the underlying concrete type is asyncable, AspNetCore >3 will buffer its results.

**Comment by Rick-Anderson** [comment]
We're no longer using a repository for this sample.
