### ISSUE TITLE
The linker sample reference is referring to a repo

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#18096]
I would expect it to reference to actual xml files, but none are there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861a95e9-b329-6408-3127-9806c50a00dc
* Version Independent ID: f1bb4fd6-29cd-4e11-e912-9c86b351bc31
* Content: [Configure the Linker for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/blazor/configure-linker.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/configure-linker.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Link directly to these? ...

https://github.com/mono/linker/blob/master/docs/data-formats.md
