### ISSUE TITLE
Update VS Step

### ISSUE THREAD

**Issue by leahtmsft** [dotnet/AspNetCore.Docs#18098]
@danroth27
Step 2 provides a link to hosting model page, but from user testing, we found that users expect the link after 'Install' to be the actual template. Removing the link would likely mitigate this confusion. It would also be clearer if we tell the user where to run the command, as some users could not figure out where to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Fair enough. I've cross-linked the definitions of "Blazor Server" and "Blazor WebAssembly" to the hosting model topic to clarify what they are. A better approach will be to say (I've done this, too, in a few spots) ...

> For more information on the two Blazor hosting models, Blazor WebAssembly and Blazor Server, see \[links to hosting model topic].

... that'll do the trick.

**Comment by guardrex** [comment]
btw @leahtmsft ... no need to ping DR on these. I'll take care of them. I'm pinged ✨ auto-magically ✨ via the metadata :point_up: when the issue opens.

**Comment by danroth27** [comment]
@guardrex I've asked @leahtmsft to keep me in the loop on these issues :smile:

**Comment by guardrex** [comment]
Tried to save you a ping there! lol

<img width="360" alt="kelner" src="https://user-images.githubusercontent.com/1622880/80845729-bc306200-8bcf-11ea-88c3-7099fb63f03b.png">

### *He is young yet, Chancellor. Impetuous, I know, but I still believe his hearts are in the right places.*

&ndash; Castellan Kelner ([Milton Johns](https://www.imdb.com/name/nm0424350/)) - [Dr. Who: The Invasion of Time](https://www.bbc.co.uk/programmes/articles/30GXnmn1ppcnTYHfZ4bDzJQ/the-fourth-dimension), 1978 &copy;[BBC](https://www.bbc.com/)
