### ISSUE TITLE
Request & Response Examples

### ISSUE THREAD

**Issue by connelhooley** [dotnet/AspNetCore.Docs#18100]
Would it be possible to document how to generate example requests & responses please?
I've seen some things about using the &lt;example&gt; XML doc tag but I can't seem to get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.1&tabs=netcore-cli)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Master issue, check here first. #16879

**Comment by RicoSuter** [comment]
Have a look at: 
https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator#specify-the-operation-response-type-and-description

**Comment by connelhooley** [comment]
Hi @RicoSuter thanks for the link. I have what you posted working, but that doesn't let me specify actual examples.

E.g. I want to have an example like this:

``` JSON
{
  "name": "Joe Blogs"
}
```
Instead I can only get this:

``` JSON
{
  "name"; "string"
}
,```
The documentation in NJsonSchema says you can use an example XML doc comment to specify an example of the request or response object but I can't get it to work:

https://github.com/RicoSuter/NJsonSchema/wiki/XML-Documentation#define-property-examples

**Comment by RicoSuter** [comment]
I think these example tags only work on DTO classes/schemas not on operations (not sure). You can however implement a custom operation processor:

https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by connelhooley** [comment]
Yeah I tried them on the DTOs and I couldn't get them to work. I'm using .NET Core 3.1, I'm not sure if that has anything to do with it, hence why I asked for some documentation around it to see if I wasn't doing anything stupid. I'll try the custom operation processor though, thanks for your help.
