### ISSUE TITLE
Error CS0246	The type or namespace name 'ProtectedLocalStorage' could not be found

### ISSUE THREAD

**Issue by chanmmn** [dotnet/AspNetCore.Docs#18106]
I followed exactly the doc  https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-3.0
Install-Package Microsoft.AspNetCore.ProtectedBrowserStorage -Version 0.1.0-alpha.19521.1
Put the script in _Host.cshtml.
Add server to startup.cs.

Somehow I still get the error:
Error CS0246	The type or namespace name 'ProtectedLocalStorage' could not be found

This picture here https://1drv.ms/u/s!Aje-DdIVpfjSjABz7_FrpigPdOQ2?e=0DfdBX.

**Comment by guardrex** [comment]
Hello @chanmmn ...

Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
