### ISSUE TITLE
The nginx configuration does not work with signalR

### ISSUE THREAD

**Issue by AtzederSerbe** [dotnet/AspNetCore.Docs#18101]
When using signalR with the nginx configuration provided in this page, there is an error "Error during WebSocket handshake: Unexpected response code: 200". When setting "proxy_set_header   Connection $http_connection;", the WebSocket connection can be established without a problem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @BrennanConroy

**Comment by BrennanConroy** [comment]
We have an issue for proxies and signalr at https://github.com/dotnet/AspNetCore.Docs/issues/10827
