### ISSUE TITLE
Typo in the first note in the 'Update the Instructor views' section

### ISSUE THREAD

**Issue by hafniz** [dotnet/AspNetCore.Docs#18112]
&lt;/tr&gt;&lt;tr&gt; in the note should be @:&lt;/tr&gt;&lt;tr&gt;
which corresponds to the line after `if (cnt++ % 3 == 0)` in the following code region. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [Tutorial: Update related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-3.1#add-instructors-edit-page)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hafniz** [comment]
The colon `:` after the at sign `@` is missing.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/80891664-31984300-8c61-11ea-9ce3-bef68209f9dc.png)

Proposed change
<a id="notepad"></a>
> [!NOTE]
> When you paste the code in Visual Studio, line breaks might be changed in a way that breaks the code. If the code looks different after pasting, press Ctrl+Z one time to undo the automatic formatting. This will fix the line breaks so that they look like what you see here. The indentation doesn't have to be perfect, but the `@</tr><tr>`, `@:<td>`, `@:</td>`, and `@:</tr>` lines must each be on a single line as shown or you'll get a runtime error. With the block of new code selected, press Tab three times to line up the new code with the existing code. This problem is fixed in Visual Studio 2019.

change to

Indentation doesn't have to be perfect, but the `@:</tr><tr>`, `@:<td>`, `@:</td>`, and `@:</tr>` lines must each be on a single line.

cc @serpent5
