### ISSUE TITLE
Important note

### ISSUE THREAD

**Issue by mcurko** [dotnet/AspNetCore.Docs#18115]
"Deploy a 32-bit app with a 32-bit (x86) .NET Core SDK unless the app..."
For this to work, one has to enable the following: Application Pools - Enable 32-Bit Applications.

I spent a lot of time figuring this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mcurko ... I'll surface that in the doc.
