### ISSUE TITLE
Navigation Panes

### ISSUE THREAD

**Issue by code-mogwai** [dotnet/AspNetCore.Docs#18124]
Can there please be a toggle or setting for hiding/showing the navigation panes? I read these docs with a relatively large font size and the continuous presence of the left and right navigation panes in full screen view is very irritating. It gives me very little space to read the main article, and in that respect is not particularly accessible. I've noticed the page is responsive in that these navigation panes disappear when the page is resized. First the one on the right then the one on the left. However neither of these give enough space to read the main article or allow the superfluous information of the navigation panes to be removed when they are not needed. A toggle would do this. I've tried the PDF version to give me more reading space but this comes with it's own issues. The PDF has 19 pages of scrolling through the documentation's table of contents and the inability to go back if you want to cross reference things by clicking on a link and then going back. Can there be a toggle to hide/show the navigation panes please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @code-mogwai ... We just handle the doc ASP.NET Core **_content_** on this repo.

Open your issue at ...

https://github.com/MicrosoftDocs/feedback/issues

... and the managers and engineers there who work on the entire documentation system will see it.
