### ISSUE TITLE
how to see the blazor version in the project ??? !!!

### ISSUE THREAD

**Issue by v-radelg** [dotnet/AspNetCore.Docs#18136]
@yoosYyd commented 9 hours ago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We won't be covering it, but something like ...

```
System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription
```

... will get it ... depending on what you mean by "blazor version."

This ...

```razor
<p>
    Version: @System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription;
</p>
```

... yields ...

<img width="478" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81013660-20963000-8e21-11ea-827a-be03a3f8e970.PNG">
