### ISSUE TITLE
Readonly properties VS Constants

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18146]
@forteg24 commented 3 hours ago — with docs.microsoft.com
Maybe is just cosmetic but I don't see the reason why you use readonly properties (Static) instead of public consts.
public static string Entry { get { return "_Entry"; } } VS public const string Entry = "_Entry";

Are not the constants created by things like that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Feel free to use `public const string Entry = "_Entry";`
