### ISSUE TITLE
Redundant bracket 

### ISSUE THREAD

**Issue by vvgonline** [dotnet/AspNetCore.Docs#18142]
In the section "Additional security guidance" the list item "Cross-site scripting (XSS))" redundant bracket in the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c753bd5-4617-8344-0b92-03f9b9c1d744
* Version Independent ID: a482b6be-e96e-f70f-bd61-d36fe0e8042d
* Content: [Threat mitigation guidance for ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/threat-mitigation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/server/threat-mitigation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/server/threat-mitigation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @vvgonline ... I'll fix it.
