### ISSUE TITLE
Error when implementing DTO in the Controller

### ISSUE THREAD

**Issue by v-radelg** [dotnet/AspNetCore.Docs#18152]
@pinkblez commented 7 hours ago •

Following the steps of the "Create a Web API" tutorial, I had some errors that I couldn't understand initially. When creating TodoItemDTO and making changes to the Controller, the following errors appeared:

The name 'ItemToDTO' does not exist in the current context [TodoApi] csharp (CS0103)
The name 'TodoItemExists' does not exist in the current context [TodoApi] csharp (CS0103)
This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run (...)' to CPU-bound work on a background thread. [TodoApi] csharp (CS1998)
'TodoItemsController.PostTodoItem (TodoItemDTO)': not all code paths return a value [TodoApi] csharp (CS0161)

And so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Rick-Anderson** [comment]
Create a DTO model:

public class TodoItemDTO
{
    public long Id { get; set; }
    public string Name { get; set; }
    public bool IsComplete { get; set; }
}

That's probably the step you missed.

**Comment by Rick-Anderson** [comment]
`    private bool TodoItemExists(long id) =>
         _context.TodoItems.Any(e => e.Id == id);`

**Comment by wouldBeNerd** [comment]
I had the same issue at first and hope this might clarify for the next person. 

The problem began When I attempted to apply the code sample just under "Update the TodoItemsController to use TodoItemDTO:" in the tutorial.

The methods 'ItemToDTO' and 'TodoItemExists' are exposed at the bottom of the TodoItemsController.

If you start by updating the HTTP methods manually; you will encounter errors immediately because you will not have added the required methods yet. If you copy and paste the whole code sample to replace the one that is currently there. Then it should work. Either that or write those missing methods out in the bottom first.

**Comment by johnsonaussie** [comment]
I myself encounter the same problem with **Update the TodoItemsController**:
This is the root issue by this code: **_var todoItem = await _context.TodoItems.FindAsync(id);_**
**todoItem** sometime  return **null ,** when it return **null** ,  the **Update(Put)** action is fail. 
when it is not return **null**, the **Update(Put)** action is successful. 
If you use Postman or dos command to update a TodoItem it work.
But if you write code in Java or C# to insert 3 or 4 Todoitem then do Update one of the Todoitem the code: 
**_var todoItem = await _context.TodoItems.FindAsync(id);_** of **todoItem** return null. 
And the Update is fail, It is something related to the **UseInMemoryDatabase** option bugs.
