### ISSUE TITLE
CreditCard Attribute requires additional scripts

### ISSUE THREAD

**Issue by andrebaltieri** [dotnet/AspNetCore.Docs#18155]
In order to have client-side validation using the CreditCard attribute you need to reference jQuery Validation Additional Methods scipts, which can be found here: https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js

Consider checking the latest scripts version on jQuery Validation official website:
https://jqueryvalidation.org/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-US/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Add to the end of
`[CreditCard]`: Validates that the property has a credit card format.
Requires [jQuery Validation Additional Methods](https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js)

cc @serpent5
