### ISSUE TITLE
CS0246

### ISSUE THREAD

**Issue by fboisro1** [dotnet/AspNetCore.Docs#18156]
Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'RazorPagesMovieContext' could not be found (are you missing a using directive or an assembly reference?) \RazorPagesMovies\Models\SeedData.cs	13	Active

Error went away when I changed (var context = new RazorPagesMovieContext) to (var context = new RazorPagesMoviesContext)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Good work.

**Comment by aucolins** [comment]
I had a similar problem. I noticed that program.cs did need this code added to it:

using RazorPagesMovie.Data;

In the tutorial page: 

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio#files-created-and-updated

That was visible in the Files created and updated section, of the Visual Studio tab, but not in the Visual Studio code tab.
