### ISSUE TITLE
Add handler registration to example shown in "Use Custom IAuthorizationPolicyProvider"

### ISSUE THREAD

**Issue by LukeBolly** [dotnet/AspNetCore.Docs#18154]
It's not very clear where the handling of your custom policy occurs when you read just this document (as most will when they are coming from google). Creating a Handler is a pre-requisite for a custom policy provider and that should be made more explicit.

I suggest adding
```
services.AddSingleton<IAuthorizationPolicyProvider, MinimumAgePolicyProvider>();
```
to the example shown. If you're like me, you'll implement what you see in the examples and skim over text, resulting in 3 hours of time wasted debugging. It's a pretty critical implementation detail to place in a dot-point. A note at the top pointing to https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#authorization-handlers would have cleared a lot of this up for me too. I found the handler in the GitHub repo and was wondering where that came from before I found the note at the bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  this looks like an easy one for me to fix if you approve.

**Comment by blowdart** [comment]
Hah, yes, go for it
