### ISSUE TITLE
Error because "Rating" empty

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18163]
@Koulbrise1030 commented on [Wed May 06 2020](https://github.com/dotnet/AspNetCore.Docs.fr-fr/issues/246)

I get an error adding the [Required] attribute in the "Rating" class.
You must fill in the "Rating" data to avoid having the error

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Ajouter une validation à une application ASP.NET Core MVC](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs.fr-fr/blob/live/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Wed May 06 2020](https://github.com/dotnet/AspNetCore.Docs.fr-fr/issues/246#issuecomment-624756751)

Hello, @Koulbrise1030
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by i-stanislaw-mlynski** [comment]
Indeed, if you do leave some records in Rating column empty, the page will break, saying that 'SqlNullValueException: Data is Null. This method or property cannot be called on Null values.' and pointing to this line:
`            var movieGenreVM = new MovieGenreViewModel`

Removing the required label does indeed work the problem around.
