### ISSUE TITLE
Configuring ALL HttpClients named or unnamed

### ISSUE THREAD

**Issue by antmdvs** [dotnet/AspNetCore.Docs#18162]
Hi, to me it seems unclear how to configure not just particular named/typed clients, but ALL `HttpClient` instances created from any `HttpClientFactory`. For example, what if I want the same header propagation behavior and/or fault tolerance policies for all my `HttpClient`s?

It looks like [IHttpMessageHandlerBuilderFilter](https://gist.github.com/davidfowl/c34633f1ddc519f030a1c0c5abe8e867#file-headerpropagation-cs-L40) may be the way to accomplish that, but it's not given any treatment in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#header-propagation-middleware)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Make HTTP requests using IHttpClientFactory #16641
