### ISSUE TITLE
Be clear about custom middleware limitations

### ISSUE THREAD

**Issue by yringler** [dotnet/AspNetCore.Docs#18177]
The documentation provides a middleware (quoted below). However, it should be noted that it is over-ridden by the contents of a ResponseCacheAttribute on the action or controller.
If the ResponseCacheAttribute doesn't use VaryByHeader, that is understood to mean that for this action, no varying by header is wanted.
The only way to set defaults when using ResponseCacheAttribute is via [cache profiles](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-3.1#cache-profiles).
This is partly relevant to the [documentation for ResponseCacheAttribute](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response), but also relevant here. If someone is trying to set a default ResponseCacheAttribute for a controller and adds another on an action, because only attributes are being dealt with, it'll be more clear that one ResponseCacheAttribute is cancelling another.
Here, though, I was very confused as to why the cache response wasn't varying by header for a bit.
```c#
app.Use(async (context, next) =>
{
    context.Response.GetTypedHeaders().CacheControl = 
        new Microsoft.Net.Http.Headers.CacheControlHeaderValue()
        {
            Public = true,
            MaxAge = TimeSpan.FromSeconds(10)
        };
    context.Response.Headers[Microsoft.Net.Http.Headers.HeaderNames.Vary] = 
        new string[] { "Accept-Encoding" };

    await next();
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@yringler  what is `cache profiles`? The link doesn't make sense.

**Comment by yringler** [comment]
Sorry about that, updated the comment. I had meant to link to https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-3.1#cache-profiles
