### ISSUE TITLE
Environment TagHelper in Blazor?

### ISSUE THREAD

**Issue by XmlmXmlmX** [dotnet/AspNetCore.Docs#18175]
What about this example? I thought Tag Helpers can't be used with Blazor?
https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#code-try-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1440e7-febc-3fbc-09d7-7f47b740fd3b
* Version Independent ID: 31071595-7c71-b6f7-3856-74f78c5c7cdf
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/handle-errors?view=aspnetcore-3.1#code-try-1)
* Content Source: [aspnetcore/blazor/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @XmlmXmlmX ... The Environment Tag Helper is in a page (*.cshtml*), not in a Razor component (*.razor*).
