### ISSUE TITLE
Problem following this tutorial

### ISSUE THREAD

**Issue by BryanFitzpatrick** [dotnet/AspNetCore.Docs#18174]
I am working through "Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8" with Microsoft Visual Studio Professional 2019 Preview Version 16.6.0 Preview 5.0.  When I get to the "Add &gt; New Scaffolded Item" for "Student" step, I fill in the "Add Razor Pages using Entity Framework (CRUD)" box with
 Model class:  Student (ContosoUniversity.Models), and 
 Data context class:  ContosoUniversity.Data.SchoolContext as instructed in the tutorial and then click Add.   I get an error:
Microsoft Visual Studio   Error There was an error running the selected code generator: 'Package restore failed.  Rolling back package changes for 'ContosoUniversity'.'

I also get this error when I try to follow other Razor tutorials.  Clearly I have some setting wrong or something missing in my install.  Any suggestions, please.

Bryan Fitzpatrick

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-au/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
* Try following the visual studio code instructions. 
* Try https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-3.1&tabs=visual-studio
* Verify you have the correct .NET SDK
