### ISSUE TITLE
In "Describe response types", with NET Core 3.1, we need to specify Type to have example model on Swagger page

### ISSUE THREAD

**Issue by nguyenlamlll** [dotnet/AspNetCore.Docs#18173]
The picture in the [Describe response types section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#describe-response-types) is not achievable with the code shown there. (`[ProducesResponseType(StatusCodes.Status201Created)]`). I also use `c.IncludeXmlComments(xmlPath);` in the previous section.

I'm using .NET Core 3.1.2, this is what I get following exactly the tutorial:
![image](https://user-images.githubusercontent.com/20963684/81257614-e4034800-905d-11ea-88a0-4af4a5a6d95d.png)
Using: `[ProducesResponseType(StatusCodes.Status201Created)]`

To have the desired result like this:
![image](https://user-images.githubusercontent.com/20963684/81257567-c7671000-905d-11ea-9602-76d697d755d7.png)

I have to use `[ProducesResponseType(typeof(AuthenticationToken), StatusCodes.Status201Created)]`. `AuthenticationToken` is the model to be displayed on the Swagger page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#describe-response-types)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@nguyenlamlll  thanks for the feedback. I added this to the top of 
Master issue for Get started with Swashbuckle #16195
