### ISSUE TITLE
dotnet ef migrations remove. Build failed. VS Code

### ISSUE THREAD

**Issue by RSP531** [dotnet/AspNetCore.Docs#18189]
Do I really have to re-label "InitialCreate" to something else?
This seems broken. I tried "dotnet ef migrations remove" in the command line which deleted all my migrations files from VSCode, however I cannot add InitialCreate
This is really frustrating for VS Code use. This is a fairly basic task that requires a terrible work-around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
```
dotnet ef database drop
dotnet ef migrations add InitialCreate
dotnet ef database update
```
