### ISSUE TITLE
limit_req block the correct operation of Blazor WebAssembly

### ISSUE THREAD

**Issue by OrihuelaConde** [dotnet/AspNetCore.Docs#18183]
Blazor WebAssembly fetch from the server more than 50 files at loading. If the limit_req  zone=one burst=10 nodelay; is set, like the example in this doc, will block the correct operation of Blazor WebAssembly, since Nginx will not deliver the files to the browser. This limit should be 60 at least (tested with 3.2.0-rc1.20223.4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @OrihuelaConde ... Stand-by. These issues are usually triaged on Fridays. We'll find out if we should provide that information in the topic. ...... and perhaps in the Blazor *Host and Deploy* node, too, at ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#nginx

**Comment by OrihuelaConde** [comment]
@guardrex, the issue is not in the "[Standalone deployment](https://docs.microsoft.com/es-es/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#standalone-deployment)", like you mentioned. It is in "[Hosted deployment with ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#hosted-deployment-with-aspnet-core)", because it guide you to "[Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-3.1)" and then to the specific doc for [Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1).

**Comment by guardrex** [comment]
Thanks ... I've updated my note :point_up:.
