### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by RSP531** [dotnet/AspNetCore.Docs#18188]
Is there something I am missing? My search is case sensitive. For example, I cannot search "ghost" as I will get no results. I must search "Ghost". thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by RSP531** [comment]
I see the comment about case sensitivity in the notes as it is the CONTAINS that is run on the db. However, I think this should be explicit in the examples or provide an option for non-case sensitivity.

**Comment by Rick-Anderson** [comment]
I don't see how I could make it more clear
![image](https://user-images.githubusercontent.com/3605364/81341859-f9707600-904d-11ea-9931-9985d4966d9e.png)
