### ISSUE TITLE
Add section for Authentication/ClaimsTransformation 

### ISSUE THREAD

**Issue by HaoK** [dotnet/AspNetCore.Docs#18191]
We currently don't have any official documentation talking about claims transformation which has been a fairly common source of questions.  We should add something basic with some general guidance

**Comment by damienbod** [comment]
@haok @Rick-Anderson 

I could do this if you want, I did some blogs in this direction

https://damienbod.com/2019/11/01/user-claims-in-asp-net-core-using-openid-connect-authentication/

https://damienbod.com/2018/10/30/implementing-user-management-with-asp-net-core-identity-and-custom-claims/

- claims mapping from authentication
- Name claim and Role claim mapping
- claims mapping from external IDPs
- claims namespaces
- Where the profile claims come from,  id_token,  user profile
- Extending or adding custom claims in Identity

Greetings Damien

**Comment by HaoK** [comment]
That'd be awesome @damienbod !

**Comment by Rick-Anderson** [comment]
> That'd be awesome @damienbod !

Ditto. @damienbod  let me know how I can help. Just PR a rough draft with some snippets and I'll clean it up. You can even use embedded snippets (code `pasted into the md file` ) and I'll migrate them to `.cs` files.

**Comment by damienbod** [comment]
Where should I add the new file in the docs?

**Comment by Rick-Anderson** [comment]
> Where should I add the new file in the docs?

How about https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authentication

Once you PR it, we can always move it.

**Comment by damienbod** [comment]
@Rick-Anderson @HaoK 

Here's a rough outline of what I plan. Is this good for you? 

https://github.com/damienbod/dotnet-AspNetCore.Docs/blob/damienbod/Authentication-ClaimsTransformation/aspnetcore/security/authentication/claims.md

Greetings Damien

**Comment by HaoK** [comment]
Looks good to me, cc @blowdart for his review on this content as well

**Comment by damienbod** [comment]
@Rick-Anderson @HaoK @blowdart 

I created a PR for this. I have not linked this in any menus yet. 

Greetings Damien
