### ISSUE TITLE
[Blazor][Webassembly] CORS sample

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18198]
This is an area of confusion for people, so it will be nice to have a sample we can point people to that showcases how to achieve this scenario.

This is a tracking issue for us to do the work here to provide such sample.

**Comment by guardrex** [comment]
We sort of **_do_** have this. It's in the common sample app and there's a brief section. Perhaps, we'll need to expand the section. However, keep in mind that CORS is a very **_known_** thing with a set of standard behaviors that the cross-linked content in our ASP.NET Core CORS docs covers in detail.

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#cross-origin-resource-sharing-cors

**Comment by javiercn** [comment]
There are a bunch fo Blazor specific things here, like configuring the HttpClient instance and is painful in general to setup CORS, the CORS doc describes several ways to do it and I think we should have one specific straightforward way to do it with Blazor.

I'll elaborate on this once I get time to look into the area.
