### ISSUE TITLE
Add more detail about the fact that the "/Identity/Account/" Login & Register pages are virtual

### ISSUE THREAD

**Issue by wcrowther** [dotnet/AspNetCore.Docs#18195]
Current documentation says: "The generated project provides ASP.NET Core Identity as a Razor Class Library. The Identity Razor Class Library exposes endpoints with the Identity area." 

Please make it more clear that these pages are virtual with no razor template as it is very non-standard and counter to years of expectation as to how ASP.NET works. Personally, I think it a bad idea to hide this functionality from the developer. Regardless,  I wasted a half an hour figuring what was going on until I found an outside explanation.

Additionally it would be helpful for the developer to know how to actually modify or replace the current virtual templates, especially since the tutorial is a starting point for further development.

Until then, here is a StackOverflow page with more details: https://stackoverflow.com/questions/50802781/where-are-the-login-and-register-pages-in-an-aspnet-core-scaffolded-app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Class libraries do not include source code. A couple sections later is **Scaffold Register, Login, and LogOut**

**Comment by wcrowther** [comment]
Obviously. I stand by my point the it is not clear that these page are virtual. Looks like DiomedesDominguez also had a similar confusion, too. 

Good point about the "Scaffold Register, Login, and LogOut" section. But it is not clear that in that section either that this will surface the templates unless you follow the link.  

Endpoint, page, view, etc., ultimately it is all just a templating engine to create a big string to download...
