### ISSUE TITLE
Migrate from ASP.NET MVC to ASP.NET Core MVC

### ISSUE THREAD

**Issue by arbaieffendi** [dotnet/AspNetCore.Docs#18197]
Suggest an update to the documentation. In order to work at first run we need to set EnableEndpointRouting to false in startup.cs, but it's not clear how to do it there. Spend sometimes to figure it out something like this.

`
public void ConfigureServices(IServiceCollection services)
{
services.AddMvc().AddMvcOptions( options => options.EnableEndpointRouting = false);
}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0591f873-94fa-c678-a905-e002e4f2c902
* Version Independent ID: a84e5712-2926-7e6d-d913-54743070e9e8
* Content: [Migrate from ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/migration/mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak This looks like it should be added.
cc @scottaddie
