### ISSUE TITLE
Configuring Local Git Deployments Not Working 

### ISSUE THREAD

**Issue by richardohara** [dotnet/AspNetCore.Docs#18196]
Running the command in step 2.f returns: 'None' app doesn't exist

The command is: 
`echo Git deployment URL: $(az webapp deployment source config-local-git --name $webappname --resource-group AzureTutorial --query url --output tsv)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7d2cbf-8299-4482-5113-6a7835ce1064
* Version Independent ID: 9db3a696-1da4-42f0-98b0-3393e83ef582
* Content: [Deploy an app to App Service - DevOps with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/aspnet/core/azure/devops/deploying-to-app-service?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/azure/devops/deploying-to-app-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/azure/devops/deploying-to-app-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/81444517-fb503d00-9112-11ea-8a73-142e0bbebe7f.png)

@CamSoper  can we replace this topic with a link to something on Azure? If so, recommend a replacement.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
