### ISSUE TITLE
NGINX and ASP.NET Core configuration for Cloudflare configured websites.

### ISSUE THREAD

**Issue by TheMisir** [dotnet/AspNetCore.Docs#18200]
Asp.Net core doesn't knows real ip address of user. Instead it only know cloudflare IP. How could I configure nginx and aspnet core to see real ip address.

**Comment by guardrex** [comment]
Hello @TheMisir ... Take a look at ...

**Configure ASP.NET Core to work with proxy servers and load balancers**
https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer
