### ISSUE TITLE
Local Identity to Azure AD

### ISSUE THREAD

**Issue by AmitavaHazra** [dotnet/AspNetCore.Docs#18203]
Let's see we have an razor application with Local identity. Now we want to move to Azure AD authentication. Is there any document that illustrates this movement for a asp.net core web application using razor pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-migration might help?

**Comment by AmitavaHazra** [comment]
@Rick,
I am not pointing this. Actually we have local identity in application. then we want to take help of Azure AD authentication service which is explained in additional authentication service section later in this tutorial. Let me post my question over there that will make it more relevant.
