### ISSUE TITLE
Request Features miss doc for IHttpsCompressionFeature

### ISSUE THREAD

**Issue by espenrl** [dotnet/AspNetCore.Docs#18205]
The whole page is a bit dated so there may others too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d7ad78-542f-236c-f5b4-0273558674b9
* Version Independent ID: f64165fc-ccf3-62cd-9ae4-313dfe7d1911
* Content: [Request Features in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/request-features.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/request-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I agree. Moved to Request Features needs a sample project with compiling code. #10557
