### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Cristigeo** [dotnet/AspNetCore.Docs#18210]
This page contains links to AzureAppServicesFile & AzureAppServicesBlob that do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I think we can collapse those two links into one, which would be the relevant section in the topic. If that sounds good, I can do it. I noticed a broken line highlight in the topic too so I can fix that up at the same time.

**Comment by Rick-Anderson** [comment]
Sounds good.
