### ISSUE TITLE
@onscroll not Working

### ISSUE THREAD

**Issue by masoudafar** [dotnet/AspNetCore.Docs#18221]
&lt;div class="container" @onscroll="@(e =&gt; Console.WriteLine("Hello, world!"))" style="height:500px"&gt;
but @onscroll not Working?whay?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de31c7e-7895-9d7c-0d9a-5bdfe83b60a9
* Version Independent ID: 334b7206-d383-40c3-b346-b54df9d87293
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @masoudafar ... I can't repro that behavior ...

```razor
<div @onscroll="@(e => Console.WriteLine($"The div is scrolling at {DateTime.Now}"))" style="height:300px;width:400px;overflow-y:scroll">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque turpis elit, et vulputate justo laoreet eu. Quisque ut dictum ipsum, ut tincidunt lacus. Ut lorem tortor, volutpat sed nunc ac, mollis ullamcorper dui. Proin a lectus lectus. Ut sed ligula vitae diam finibus ultrices ac vitae enim. Nunc venenatis eros enim, non pretium velit condimentum eget. Phasellus a ligula elementum, dictum magna sed, rhoncus odio. Duis egestas, arcu eget tincidunt rutrum, mauris purus bibendum arcu, non viverra mauris magna et eros. Nulla faucibus libero vel nisl lacinia mollis. Duis aliquet ex lorem, in tempus justo facilisis non. Integer accumsan diam vel magna finibus cursus. Donec mauris purus, tristique ultricies semper vestibulum, fermentum feugiat ante. Maecenas efficitur mauris odio, nec volutpat mi ultrices eget. Proin purus dui, suscipit ut est vitae, aliquam lobortis sem. Morbi commodo, nunc eget efficitur cursus, arcu ex gravida purus, eget hendrerit arcu urna id neque. Aliquam eleifend ante gravida metus auctor, at porttitor nulla sollicitudin.

    Ut vel est finibus, cursus turpis id, lacinia nisl. Maecenas semper pulvinar ipsum, ac lacinia turpis iaculis et. Mauris eu nisl vulputate, iaculis est a, consequat lectus. Integer tempor turpis quis ligula aliquet elementum. Nam pharetra accumsan velit non semper. Cras tempus rutrum fermentum. Cras vel quam sed tortor posuere laoreet eu et dolor. Vestibulum nulla nulla, sollicitudin consectetur consectetur vitae, egestas sit amet massa.
</div>
```

<img width="688" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81472225-2e024000-91bc-11ea-87ee-7661dfd7ad17.PNG">

**Comment by masoudafar** [comment]
Thanks,Putting overflow-y:scroll is an important point that I forgot.
I'm sorry
