### ISSUE TITLE
Move to Microsoft identity platform for Azure AD authentication

### ISSUE THREAD

**Issue by AmitavaHazra** [dotnet/AspNetCore.Docs#18224]
I want to use Microsoft identity platform.   
 When we use below it works:
```
services.AddAuthentication().AddMicrosoftAccount(microsoftOptions =>
{
microsoftOptions.ClientId = Configuration["Authentication:Microsoft:ClientId"];
microsoftOptions.ClientSecret = Configuration["Authentication:Microsoft:ClientSecret"];
});
```

But when I wan to use below it is showing error.

```
services.AddSignIn(Configuration);
 services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
            .AddAzureAD(options =&gt; Configuration.Bind("AzureAd", options));
```
Error:
OptionsValidationException: The 'Instance' option must be provided.
Microsoft.Extensions.Options.OptionsFactory&lt;TOptions&gt;.Create(string name)

Can anyone please suggest how to move to this new v2 option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp

**Comment by AmitavaHazra** [comment]
@Rick, thank you so much.
