### ISSUE TITLE
Call data from RESTApi very slow. suggest me to fixed this.

### ISSUE THREAD

**Issue by leapoutdom** [dotnet/AspNetCore.Docs#18223]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @leapoutdom ... We only handle documentation issues here. You would need to report that to the product unit engineers at ...

https://github.com/dotnet/aspnetcore/issues

... and they will need more information than that. Put up a repro project or show your code to them and provide information on how long the calls are taking. They will advise you on what sort of network traffic and/or detailed app logging that they need.
