### ISSUE TITLE
Incorrect explanation of Genre's regular expression validation.

### ISSUE THREAD

**Issue by CommanderMark** [dotnet/AspNetCore.Docs#18222]
The explanation for the validation attributes mentions that it ensures Genre "Must only use letters."

The RegEx however shows `^[A-Z]+[a-zA-Z""'\s-]*$`, which indicates that every character that isn't the first one can include double/single quotes, white space and a dash in addition to letters.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-ca/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, that should be
`   [RegularExpression(@"^[A-Z]+[a-zA-Z]*$")]`

This also needs to be fixed in https://docs.microsoft.com/en-ca/aspnet/core/tutorials/first-mvc-app/validation
