### ISSUE TITLE
Localization Tutorial Does Not Show How to Initialize If you are only using API

### ISSUE THREAD

**Issue by HockeyJustin** [dotnet/AspNetCore.Docs#18234]
The [.NET Core Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1) Document (otherwise, excellent), does not include instruction for how to instantiate the localization if you are using ONLY API functionality - it focusses solely on projects with MVC views.

I have just lost hours trying to work out why `ResourceNotFound` (from `Microsoft.Extensions.Localization.LocalizedString`) would always be `true` in an HTTP API GET request, no matter what I did.

The eventual answer was [here](https://www.syncfusion.com/blogs/post/how-to-use-localization-in-an-asp-net-core-web-api.aspx). 

In the startup.cs code, I needed to do the following, which I could not find in the documentation, or in the sample:

```
var localizeOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
app.UseRequestLocalization(localizeOptions.Value);
```

The document and sample code only state the following (which does not seem to work for API requests):
```

app.UseRequestLocalization(new RequestLocalizationOptions
{
    DefaultRequestCulture = new RequestCulture("en-US"),
    // Formatting numbers, dates, etc.
    SupportedCultures = supportedCultures,
    // UI strings that we have localized.
    SupportedUICultures = supportedCultures
});
```

Please could the documentation be updated to include this?

If you would like me to create a PR and suggest an edit, I will be happy to do so. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  quick review of proposal please. cc @hishamco

**Comment by hishamco** [comment]
There are two ways to configure `UseRequestLocalization()` the one that you pointed is already there in the [Localization.StarterWeb](https://github.com/aspnet/Entropy/blob/master/samples/Localization.StarterWeb/Startup.cs#L108-L109)

This is only needed if you configure the `RequestLocalizationOptions` in the `ConfigureServices` using the following code:

```csharp
services.Configure<RequestLocalizationOptions>(options =>
{
    ...
});
```

**Comment by Rick-Anderson** [comment]
@hishamco but the document is controller with views focused. Don't we need to add something to the doc for REST APIs?

**Comment by hishamco** [comment]
Strange!! why it doesn't work, @HockeyJustin could please create a repo to reproduce the issue you are facing?

**Comment by HockeyJustin** [comment]
@hishamco  . Thanks for getting back to me. The project I used this on was a work one, so I would need to create something completely separate. I don't think it's needed in this case.

You have correctly identified the key point that I am utilising `services.Configure<RequestLocalizationOptions>(..)`. 

The sample you reference does indeed include the correct setup, but that isn't detailed or referenced from this document.

The [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1) includes `services.Configure<RequestLocalizationOptions>(..)` ,but does not include the corresponding [UseRequestLocalization](https://github.com/aspnet/Entropy/blob/master/samples/Localization.StarterWeb/Startup.cs#L108-L109) needed to make a working solution if `services.configure` was used. Hence, I believe the document is lacking a vital piece of information that would save a developer hours of debugging/ hunting for the solution online.


To be clear: This is not a coding issue. The issue is that the referenced document does not provide adequate information for a developer to get set up when using `services.Configure<RequestLocalizationOptions>(..)` as part of their setup.

**Comment by hishamco** [comment]
> To be clear: This is not a coding issue. The issue is that the referenced document does not provide adequate information for a developer to get set up when using services.Configure<RequestLocalizationOptions>(..) as part of their setup.

Agree but I think the Configuration & Options patterns should have somethings related, because this not for localization only

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @HockeyJustin.
We recommend using the same mechanisms as you would in non-API application.
Given that configuring localization in web-api only applications is not a common scenario we don't plan to modify the docs to reflect on this.
