### ISSUE TITLE
Debug instructions should include note about new Edge

### ISSUE THREAD

**Issue by Logis-Intrope** [dotnet/AspNetCore.Docs#18231]
The instructions for using Blazor Webassembly should include a note that this may require installing the new Edge from https://www.microsoft.com/edge; the version likely to be installed on many Win 10 environments is the old one, which doesn't debug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Logis-Intrope ... The platform guidance already covers it ...

https://docs.microsoft.com/aspnet/core/blazor/supported-platforms

... only the current versions of browsers are supported for all scenarios.
