### ISSUE TITLE
Developer exception page just gives raw error text since 3.1?

### ISSUE THREAD

**Issue by deap82** [dotnet/AspNetCore.Docs#18237]
Since we upgraded to 3.1 the "Developer exception page" response only contains raw error text and not any surrounding html that provides the design and readability we've been used to. It is as if it has lost its "view file" sort of. What could the reason for this be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No repo. Create a new 3.1 project

```
public IActionResult Privacy()
{
    throw new Exception("Testing error page");
    return View();
}
```
