### ISSUE TITLE
Confusion: 404 returned regardless of whether or not id:int is optional

### ISSUE THREAD

**Issue by osamakawish** [dotnet/AspNetCore.Docs#18238]
> A request to the page with the "{id:int}" route template that does not include the integer will return an HTTP 404 (not found) error. For example, http://localhost:5000/Movies/Details will return a 404 error. To make the ID optional, append ? to the route constraint:
> 
> ```CSHTML
> @page "{id:int?}"
> ```
> 
> To test the behavior of @page "{id:int?}":
> 
> Set the page directive in Pages/Movies/Details.cshtml to @page "{id:int?}".
> Set a break point in public async Task<IActionResult> OnGetAsync(int? id) (in Pages/Movies/Details.cshtml.cs).
> Navigate to https://localhost:5001/Movies/Details/.
> With the @page "{id:int}" directive, the break point is never hit. The routing engine returns HTTP 404. Using @page "{id:int?}", the OnGetAsync method returns NotFound (HTTP 404).

So the 404 error is returned regardless of whether or not the `id:int` directive is optional or not? In that case, what does making it optional do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It doesn't match.

**Comment by firewater** [comment]
@Rick-Anderson Can you please explain? Thanks.

**Comment by Rick-Anderson** [comment]
Doc is correct.

**Comment by osamakawish** [comment]
@Rick-Anderson I think he was asking for an explanation as to why.

@firewater This is an old post, but looking at the documentation again, it highlights the part of the code explaining this. I think an optional `id`, when not included, leads to `Movie == null`. If `Movie == null` isn't handled, then the 404 page is returned.
