### ISSUE TITLE
Example code not valid under 2.2.x

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/AspNetCore.Docs#18248]
The section ["Set the environment"](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#set-the-environment-1) refers to some code, like `CreateHostBuilder`, that I can't find in any version of 2.2.x.

https://github.com/dotnet/aspnetcore/blob/v2.2.9/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @AnthonyMastrean ... I'll take a look.

**Comment by pranavkm** [comment]
@AnthonyMastrean as an FYI .NET Core 2.2 has been out of support for some time now: https://dotnet.microsoft.com/platform/support/policy/dotnet-core#lifecycle. I'd encourage you to supported version of the runtime.

**Comment by guardrex** [comment]
2.1 is still a thing, and the PR is already up at #18254.
