### ISSUE TITLE
What if I do not replace [Route("api/[controller]")] by [Route("api/TodoItem")]  ?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18249]
@guiljs commented on [Sat May 09 2020](https://github.com/dotnet/AspNetCore.Docs.pt-br/issues/135)

At tutorial, we are asked to :

Replace [controller] with the name of the controller, which by convention is the controller class name minus the "Controller" suffix. For this sample, the controller class name is TodoItemsController, so the controller name is "TodoItems". ASP.NET Core routing is case insensitive.

But what if don't replace [Route("api/[controller]")] by [Route("api/TodoItem")] ?
Why do I need to change it?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: criar uma API Web com ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@srvbpigh commented on [Sat May 09 2020](https://github.com/dotnet/AspNetCore.Docs.pt-br/issues/135#issuecomment-626194540)

Hello, @guiljs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@guiljs see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing
