### ISSUE TITLE
Doesn't this update a resource regardless of if there is an error or a test fails?

### ISSUE THREAD

**Issue by leenay** [dotnet/AspNetCore.Docs#18243]
The document implies that JSON Patch is atomic however from running the examples this appears to not be the case. For example running the "test" example still actually sets the customer's name to "Barry" regardless of whether the test passes or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  please review.

**Comment by serpent5** [comment]
The `test` example relies on `ModelState`. The `JsonPatchWithModelState` action passes `ModelState` into `ApplyTo`. If the `test` fails, which it does for the example shown in the topic, `ModelState` is updated to include an error.

When I run this, I get a 400 response along with this serialised `ModelState` value:

```json
{
  "Customer": [
    "The current value 'John' at path 'customerName' is not equal to the test value 'Nancy'."
  ]
}
```

So, I think that's working as intended...

**Comment by leenay** [comment]
If inspect the value of the customer variable whilst debugging you'll see it is set to "Barry". The fact the method throws an error doesn't matter. If you persisted the customer to memory its name would now be changed. To see the issue just update the method to return the customer when the modelstate is in error and you'll see its name is no longer John, which according to the docs it still should be.

**Comment by serpent5** [comment]
Ok, so that's just a matter of how the errors get reported. If you pass `ModelState` in to `ApplyTo`, exceptions are handled and turned into `ModelState` errors. If you don't pass in `ModelState`, the first exception bubbles up to the calling code, which, in this case, means the model doesn't get updated. Order matters here, though. If the `test` operation is second, the `customerName` change applies before the exception is thrown.
