### ISSUE TITLE
Controller Injection and Passing Model

### ISSUE THREAD

**Issue by SushrutDeo** [dotnet/AspNetCore.Docs#18247]
Is it possible to pass a model to a controller in which we are injecting a dependency? If yes, could you publish the sample, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08d2cf2e-55fb-33a4-b1d4-c97b2d531741
* Version Independent ID: f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf
* Content: [Dependency injection into controllers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-3.1#constructor-injection)
* Content Source: [aspnetcore/mvc/controllers/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
This isn't typically how models are accessed in MVC. The controller would get the request model through model binding as parameters on action methods. The controller accesses the domain model using interfaces exposed by the domain and injected into the controller constructor (typically). Trying to "inject" the domain model into the controller is not how the pattern is designed to work.

**Comment by Rick-Anderson** [comment]
thanks @ardalis !

**Comment by SushrutDeo** [comment]
Thanks @ardalis. Can I have controller like following:
public IActionResult SaveUser( [FromServices]ISaveUserService saveUserService, User user)
{
    // Some code to save user
}
Here User model is being passed to the controller from a view and we are also injecting a Save user service.
