### ISSUE TITLE
AAD B2C instance

### ISSUE THREAD

**Issue by rleath82** [dotnet/AspNetCore.Docs#18251]
I've completed the first step of creating a tenant and am able to see the tenant domain, but I'm not seeing where to find the AAD B2C instance. Where would I find this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Uses your organization name in the following format. I'll be making further improvements on how this is explained shortly.

```json
"Instance": "https://{ORGANIZATION}.b2clogin.com/",
```

For example:

```json
"Instance": "https://contoso.b2clogin.com/",
```

**Comment by rleath82** [comment]
Ok thank you!
