### ISSUE TITLE
Custom Polymorphic model binding with complex properties in child classes

### ISSUE THREAD

**Issue by J523** [dotnet/AspNetCore.Docs#18260]
I have followed the Polymorphic Custom Model Binder using [this post](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1). However it illustrates a basic scenario assuming simple type properties for the child classes. It doesn't explores the possibility of a child class having a complex property. It would be helpful to share some thoughts on it. 

E.g.

```
public abstract class Device
{
    public string Kind { get; set; }
}

public class Laptop : Device
{
    public string CPUIndex { get; set; }
}

public class SmartPhone : Device
{
    public string ScreenSize { get; set; }
    
   public Dimension PhoneDimension{ get; set; }
}
```

where  Dimension  is a complex type
```
public class Dimension  
{
    public double height{ get; set; }
    
   public double width{ get; set; }
}
```
If any resources for this already exists it would be great if someone directs to those

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by J523** [comment]
Yes did ! Thank you :)
