### ISSUE TITLE
Is there any demo on Blazor ServerSide?

### ISSUE THREAD

**Issue by LuohuaRain** [dotnet/AspNetCore.Docs#18268]
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
I don't know of any plans for one.

AFAIK the sample should just work if you switch to Server-side Blazor.

**Comment by guardrex** [comment]
I guess I should test then. If we can broaden the current topic out to a choice between the hosting models, that would be best ... take the least time and take the least coverage.

I'll let Artak give me the priority on this and then give it a shot and see how it goes. I'm going to change the metadata on this issue to reflect the current tutorial.

**Comment by guardrex** [comment]
> I guess I should test then.

Given the workload, I don't want to waste time (thus 💰) testing something that should work. There haven't been any new issues or further comment on this one, nor has management called for any action.

We'll keep an :ear: open for more feedback in this vein.
