### ISSUE TITLE
SignalR IHubContext via Middleware Suggestion

### ISSUE THREAD

**Issue by caseymarquis** [dotnet/AspNetCore.Docs#18275]
The example which shows how to get an IHubContext instance from the middleware pipeline doesn't show the required call to next.Invoke(). Using the documentation as is results in portions of aspnetcore silently failing.

The example currently shows:
```C#
app.Use(async (context, next) =>
{
    var hubContext = context.RequestServices
                            .GetRequiredService<IHubContext<MyHub>>();
    //...
});
```

Changing it to the following might save some other users a few hours of debugging:
```C#
app.Use(async (context, next) =>
{
    var hubContext = context.RequestServices
                            .GetRequiredService<IHubContext<MyHub>>();
    if (next != null) {
        await next.Invoke();
    }
});
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Good catch, @caseymarquis. Bringing in @BrennanConroy from our dev team here. Brennan - this looks like we may have cut the sample off too early. This look good to you? If so I'll either request @caseymarquis submit a pull request, or i'll do it. :)

**Comment by BrennanConroy** [comment]
:+1:

**Comment by davidfowl** [comment]
It should be constructor injected...

**Comment by bradygaster** [comment]
@davidfowl mmhmm. agreed and will alter the example with that in mind should I be the one to do the editing. (cloning the repo again now in preparation for this very thing)

**Comment by caseymarquis** [comment]
Sounds like you're suggesting something like this?

```C#
var hostBuilder = Host.CreateDefaultBuilder();
var host = hostBuilder.ConfigureWebHostDefaults(webBuilder => {
    //Configure the webservice...
}).Build();

var hubContext = host.Services.GetService(typeof(IHubContext<THub, THubClient>));
//inject hubContext into other DI system
```

If so, I like that much better! Aside from not adding overhead to every request, it makes the host object the source of all web dependencies, and keeps pulling out web dependencies away from the nitty gritty configuration code.

Thanks guys! Let me know if there's a better way to do this, otherwise I'll watch for the change in the docs.

**Comment by davidfowl** [comment]
Oh wait this inline I just realized this was inline middleware carry on 😁

**Comment by bradygaster** [comment]
@caseymarquis based on @davidfowl's comment, i'd be open to you submitting a PR on the doc for us to review that reflects your ideas. If you've not submitted a PR to docs before I could help with the process if you need it. Or just tell us to do it and i'll jump on it. 👍

**Comment by caseymarquis** [comment]
Hey, why not. I feel like this is a slippery slope that leads toward community contributions.

That said, having never done a github PR, is the procedure:

1. Fork?
2. Create a branch for changes?
3. Make purposeful commits?
4. Press some magic button which opens a PR form?

I'll see how far I get. I figure step four is the only mysterious part.

**Comment by Rick-Anderson** [comment]
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
