### ISSUE TITLE
Customize WebApplicationFactory clarification on ConfigureServices

### ISSUE THREAD

**Issue by houbi56** [dotnet/AspNetCore.Docs#18286]
"The test app's builder.ConfigureServices callback is executed after the app's Startup.ConfigureServices code is executed. The execution order is a breaking change for the Generic Host with the release of ASP.NET Core 3.0. To use a different database for the tests than the app's database, the app's database context must be replaced in builder.ConfigureServices"

This is valid ONLY if the host is an IHost using IHostBuilder. 
For IWebHost ConfigureServices in ConfigureWebHost will run BEFORE the Startups ConfigureServices, while using IHost it will run AFTER. 
For IWebHost usage a workaround is to instead use builder.ConfigureTestServices. 

I would like the docs to clarify this. When reading the above I assumed that the behaviour would be the same for IWebHost.

For me migrating from ASP.CORE 2.2 to 3.1, and still using IWebHost, following the documentation broke the tests (I'd removed a routines specific for 2.2 for performing configuration after Startup was run). 
This was not mentioned in the migration guide either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Integration tests MASTER issue: Look here #16341

**Comment by michal-ciechan** [comment]
For anyone struggling with this after using the Docs, if you use `ConfigureTestServices(Action<IServiceProvider> services)` extension method, they will run after the WebHost  `Startup.ConfigureServices` file is run!.
