### ISSUE TITLE
Add DI options sample

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18292]
From @guardrex  in #10553

 I wonder about explaining how to achieve the following pattern that's often used by the framework ...

```csharp
services.AddMyService(options =>
{
    options.SomeOption = "some value";
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Tracked in Options pattern master issue: Check here first #18291

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you can provide a sample for this.

**Comment by serpent5** [comment]
Sure, I can put something together.

**Comment by serpent5** [comment]
@Rick-Anderson Do you want this as:

1. A sample app I create under my own GitHub account that you can pull code from?
1. A follow-up PR once the rewrite that's in-progress completes?
1. Inline code here?

**Comment by Rick-Anderson** [comment]
Do a PR with just the sample app in https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/configuration/options/samples/3.x
