### ISSUE TITLE
WebApplicationFactory and HttpClient lifecycle and scope?

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/AspNetCore.Docs#18307]
Can you document the expected scope and lifecycle of a WebApplicationFactory? 

The documentation assumes familiarity with xUnit's IClassFixture, which I'm certainly not (I could read up, but we use a lot of NUnit). Am I correct that it should be as close to singleton/static across a test run (barring the need to create one with different settings)? I believe that was the recommendation for the underlying TestServer, but can't find any supporting docs right now.

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#sut-environment

Following that, and based on some lite source code reading, it looks like the WebApplicationFactory is handing out new `HttpClient`s every time `CreateClient` is called... isn't that in contradiction to the latest recommendations around pooling the internals via `IHttpClientFactory`?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1

Is there some way that these two patterns can be made to work together? I'm not seeing it yet, since the APIs are kinda opposite ("here's a specifically configured client" vs. "here's a generic client with pooled internals").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#aspnet-core-integration-tests)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Tracked in Integration tests MASTER issue: Look here #16341
