### ISSUE TITLE
Service-worker-assets.js is not generated

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#18305]
Adding PWA to exisiting app afterwards. It is not producing the following file.
&lt;ServiceWorkerAssetsManifest&gt;service-worker-assets.js&lt;/ServiceWorkerAssetsManifest&gt;
getting error 
Failed to execute 'importScripts' on WorkerGlobalScope service-wroker.js  it failed to load 'https://localhost:44383/service-worker-assets.js' i also could ot find that file manually as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8c235e-1ce4-046f-e848-294096361922
* Version Independent ID: 6240f626-97d4-ace0-5e34-20e1c3592f86
* Content: [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/progressive-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... Open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
