### ISSUE TITLE
run with docker

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/AspNetCore.Docs#18302]
i have an asp core 2.1 project with angular template. i added docker support for it, but only the API works, the SPA fails to  load with error message on browser 

`An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: 'npm' is not recognized as an internal or external command,

))
System.Threading.Tasks.Task<TResult>.GetResultCore(bool waitCompletionNotification)

InvalidOperationException: The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: 'npm' is not recognized as an internal or external command,

Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(string sourcePath, string npmScriptName, ILogger logger)`

**Comment by guardrex** [comment]
Hello @tnlthanzeel ... It's best if you close this and re-open the issue from the **This page** feedback button+form at the bottom of the English topic. It will add metadata to the issue and automatically ping the author.

**Comment by tnlthanzeel** [comment]
okay sure, thanks
