### ISSUE TITLE
Multiple authorization policies

### ISSUE THREAD

**Issue by jeremycook** [dotnet/AspNetCore.Docs#18310]
[EDIT by guardrex to add the metadata. @radical ... Please use the **This page** feedback button and form at the bottom of a topic to open new issues]

**Help us make content visible**

- I googled 'asp.net core 3.1 multiple authorization policies'
- It seems that https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1 would address this. It showed up in search results but it was because of all the other uses of "multiple, "authorization" and "policies" like "multiple authorization requirements".

**Describe the new topic**

- It is not clear what happens when two or more policies are applied to the same controller action or Razor page. It is also not clear why each policy would succeed when in isolation, but when both are applied to the same controller action results in authorization failure.
- Suggest a location in the Table of Contents: This seems like an important concept and should be included as part of the explanation of policy based authorization or immediately after and before getting into technical details.
- Write an abstract. In one **short** paragraph, describe what this topic will cover: I don't know enough sorry.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic: (a) general discussion of multiple authorization policies, (b) ways multiple authorization policies can be applied to MVC and the impact of doing so, (c) ways multiple authorization policies can be applied to Razor pages and the impact of doing so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#accessing-request-context-in-handlers)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jeremycook  see [What should a handler return?](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#what-should-a-handler-return) and the following section **Why would I want multiple handlers for a requirement?**

**Comment by Rick-Anderson** [comment]
See also  https://github.com/blowdart/AspNetAuthorizationWorkshop#step-6-multiple-handlers-for-a-requirement

**Comment by jeremycook** [comment]
@Rick-Anderson thank you for reminding me of Blowdart's workshop. I went through it to make sure I'm not forgetting something. Nothing jumped out at me. So I tried something new and discovered something unexpected. Perhaps you could point me at some documentation that helps me understand how/why applying the AuthorizeAttribute to a controller is not equivalent to applying the AuthorizeFilter globally to controllers when there is another policy involved.

The two snippets share the following bit of code in common. I confirmed that the `AccessAuthorizationHandler` does not call `context.Fail()` unexpectedly and calls `context.Succeed(requirement)` based on the user and context as I would expect.

```csharp
// In Startup.cs
services.AddAuthorization(options =>
{
    options.AddPolicy("Internal", policy => policy.RequireRole("RoleA", "RoleB"));
    options.AddPolicy("Access", policy => policy.Requirements.Add(new AccessAuthorizationRequirement()));
});
services.AddSingleton<IAuthorizationHandler, AccessAuthorizationHandler>();

// Elsewhere, the AccessAttribute applied to the controller like this, and is used by the AccessAuthorizationHandler
public class AccessAttribute : AuthorizeAttribute
{
    public AccessAttribute(Type accessType) : base("Access")
    {
        AccessType = accessType;
    }

    public Type AccessType { get; }
}
```

The two code snippets do not behave the same, and it is very surprising to me.

This first one results in access denied.

```csharp
// In Startup.cs
services.AddControllersWithViews(options =>
{
    options.Filters.Add(new AuthorizeFilter("Internal"));
});

// In SomeController.cs
[Access(typeof(SomeAccess))]
public class SomeController : Controller
{
```

If instead I do not apply the `AuthorizeFilter("Internal")` globally but instead apply an `AuthorizeAttribute` directly to the controller everything works as expected, and I don't get access denied.

```csharp
// In SomeController.cs
[Authorize("Internal")]
[Access(typeof(SomeAccess))]
public class SomeController : Controller
{
```

When I created this issue I had assumed I was missing some important concept of policies but that doesn't seem to be the case. It seems I'm just misunderstanding the `AuthorizeFilter`. Is it possible to apply a policy globally to all controller actions while applying a more specific policy to an controller/action through an AuthorizeAttribute? Why doesn't AuthorizeFilter make sense to me?

**Comment by jeremycook** [comment]
In case it matters, here is the code of the `AccessAuthorizationHandler`:

```csharp
public class AccessAuthorizationHandler : AuthorizationHandler<AccessAuthorizationRequirement>
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public AccessAuthorizationHandler(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, AccessAuthorizationRequirement requirement)
    {
        var succeeded = false;
        var failed = false;

        if (context.Resource is Endpoint endpoint)
        {
            foreach (var descriptor in endpoint.Metadata.OfType<ControllerActionDescriptor>())
            {
                var accessAttributes = descriptor.ControllerTypeInfo.GetCustomAttributes(inherit: true).OfType<AccessAttribute>();
                foreach (var accessAttr in accessAttributes)
                {
                    var type = accessAttr.AccessType;

                    var access = httpContextAccessor.HttpContext.RequestServices.GetService(type) ?? Activator.CreateInstance(type);

                    var matches = type.GetMethods().Where(o => o.Name == descriptor.ActionName);
                    if (matches.Count() != 1)
                    {
                        throw new InvalidOperationException($"The {type.FullName} type must have exactly one method named {descriptor.ActionName}.");
                    }
                    var actionMethod = matches.Single();

                    var parameters = new List<object>();
                    foreach (var param in actionMethod.GetParameters())
                    {
                        if (param.ParameterType == typeof(ClaimsPrincipal))
                        {
                            parameters.Add(context.User);
                        }
                        else
                        {
                            if (!httpContextAccessor.HttpContext.GetRouteData().Values.TryGetValue(param.Name, out var value))
                            {
                                throw new NullReferenceException($"The {type.FullName}.{actionMethod.Name} method has a parameter named {param.Name} but the RouteValueDictionary does not contain an item with that key.");
                            }

                            var convertedValue =
                                value == null ? value :
                                typeof(Guid?).IsAssignableFrom(param.ParameterType) && value is string guid ? Guid.Parse(guid) :
                                Convert.ChangeType(value, param.ParameterType);

                            parameters.Add(convertedValue);
                        }
                    }

                    var accessResult = actionMethod.ReturnType == typeof(Task<bool>) ?
                        (bool)await InvokeAsync(access, actionMethod, parameters.ToArray()) :
                        (bool)actionMethod.Invoke(access, parameters.ToArray());
                    if (accessResult)
                    {
                        succeeded = true;
                    }
                    else
                    {
                        failed = true;
                    }
                }
            }

            if (succeeded)
            {
                context.Succeed(requirement);
            }
            if (failed)
            {
                context.Fail();
            }
        }
    }

    public static async Task<object> InvokeAsync(object instance, MethodInfo method, object[] parameters)
    {
        var task = (Task)method.Invoke(instance, parameters);
        await task.ConfigureAwait(false);
        var resultProperty = task.GetType().GetProperty("Result");
        return resultProperty.GetValue(task);
    }
}
```
