### ISSUE TITLE
Securing SignalR Hubs

### ISSUE THREAD

**Issue by joshgreenwald** [dotnet/AspNetCore.Docs#18326]
The authorization context and user claims do not seem to pass down to SignalR Hubs in the ASP.NET Core server project of the ASP.NET Core hosted WASM solution. Can this be documented here?

**Comment by guardrex** [comment]
Hello @joshgreenwald ... Your "here" isn't clear. Re-open this using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
