### ISSUE TITLE
WebAssembly: Can't get User in WeatherForecastController, it returns null value (authenticated user)

### ISSUE THREAD

**Issue by jvallejoa** [dotnet/AspNetCore.Docs#18327]
[Enter feedback here]
Hi, I implemented the example related to this section of the page

<<The following WeatherForecastController logs the UserName when the Get method is called:
        private readonly UserManager<ApplicationUser> **_userManager**;
        private readonly ILogger<WeatherForecastController> logger;
        public WeatherForecastController(ILogger<WeatherForecastController> logger, 
            **UserManager<ApplicationUser> userManager**)
        {
            this.logger = logger;
            **_userManager = userManager;**
        }" >>

My target is to get the current user, so I implemented the example above as is in Controller WeatherForecast, but when run application the user (var user = await _userManager.GetUserAsync(User);) is taking null value always. 

I'm using Blazor WebAssembly 3.2.0 Release Candidate.
Please, could you take a look?

Thanks
Juan Vallejo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jvallejoa ... AFAIK, the topic's guidance isn't broken (it was working a couple of weeks ago); but given that we're in preview, things do sometimes break preview release-to-preview release. I'll be looking at all of the topics in this node this weekend to see if anything has broken in the last week or two. If I find anything wrong, I hope to have things fixed by the end of the day on Monday. You can keep an eye on the PR's on Monday to see if I found anything.
