### ISSUE TITLE
Get bearer token for other requests

### ISSUE THREAD

**Issue by joshgreenwald** [dotnet/AspNetCore.Docs#18329]
Secured SignalR hubs require the auth token to be sent in the hub connection request. How is this achieved? I could not successfully inject the IAccessTokenProvider (maybe this is not injected automatically by Blazor).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Cross-ref: https://docs.microsoft.com/aspnet/core/signalr/configuration#configure-bearer-authentication-1

**Comment by guardrex** [comment]
@BrennanConroy ... It doesn't seem like this should be addressed by content in the Blazor *Security* node given that the SignalR docs should apply and the SignalR *Authn and Authz* topic is already cross-linked in the [Blazor *SignalR* config doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=webassembly).

Do you concur? Can I close this?

**Comment by guardrex** [comment]
Actually, I don't think I understand the ask really. "hub connection request" ... "bearer token for other requests" ... these don't seem to ask for the same thing. We'd need to clear up what the ask is first and then see if the Blazor docs need to address anything for it.

**Comment by joshgreenwald** [comment]
It's been awhile, but I believe the original ask about getting authenticated user's JWT access token for use in other requests, such as a hub connection request to SignalR.

**Comment by guardrex** [comment]
I see ... something in the realm of ...

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#authenticate-users-connecting-to-a-signalr-hub

... for after a user authenticates to the app. I just wonder tho if the exact coverage at ...

https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#identity-server-jwt-authentication

... is all that's needed.

**Comment by guardrex** [comment]
... and we also added the following since this issue was opened ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=webassembly#signalr-cross-origin-negotiation-for-authentication-1

**Comment by BrennanConroy** [comment]
This looks like an ask of "how to get auth information into a component for use in things such as a SignalR connection.", which should be covered by https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0
