### ISSUE TITLE
Language and code example around the "thread-staticness" of Thread.CurrentPrincipal is misleading

### ISSUE THREAD

**Issue by madelson** [dotnet/AspNetCore.Docs#18321]
# Issue description

In multiple places, the page refers to `Thread.CurrentPrincipal` as being "thread-static" and says that it will not work in async scenarios. There is even an included code example intended to demonstrate this:

```
// Create a ClaimsPrincipal and set Thread.CurrentPrincipal
var identity = new ClaimsIdentity();
identity.AddClaim(new Claim(ClaimTypes.Name, "User1"));
Thread.CurrentPrincipal = new ClaimsPrincipal(identity);

// Check the current user
Console.WriteLine($"Current user: {Thread.CurrentPrincipal?.Identity.Name}");

// For the method to complete asynchronously
await Task.Yield();

// Check the current user after
Console.WriteLine($"Current user: {Thread.CurrentPrincipal?.Identity.Name}");
```

**However**, `Thread.CurrentPrincipal` is not, in fact, thread-static. It behaves more like `AsyncLocal` and flows nicely across awaits. Simply running the code snippet demonstrating the problem shows that it works fine on both .NET Framework and .NET Core (at least in the scenarios I tried) :-)

We were migrating to ASP.NET Core with a large codebase that used Thread.CurrentPrincipal pretty heavily. All we had to do to get things working was set this in a middleware upfront and it flows nicely just like it did before.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
