### ISSUE TITLE
Antiforgery Token required

### ISSUE THREAD

**Issue by wadebee** [dotnet/AspNetCore.Docs#18320]
Don't forget to send an antiforgery token or set [IgnoreAntiforgeryToken] on your controller action. Wasted many hours trying to trace down the 400 Bad Requests I couldn't get around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadebee  can you provide a GitHub link to the simplest possible sample that reproduces this problem?

**Comment by Rick-Anderson** [comment]
Tracked in JsonPatch Master issue. Look here #18330
