### ISSUE TITLE
AllowAnonymous being ignored with multiple auth schemes

### ISSUE THREAD

**Issue by pbakun** [dotnet/AspNetCore.Docs#18334]
I have an issue with Authorization for my signalr hub. 
In my app I have started with Razor pages MVC with default cookie auth. Later I've developed React-based SPA with JWT. I have different controllers which uses auth scheme depending on target front-end. Till that point everything works fine.
App also uses signalr hub, which needs to be accessed by both kind of auth schemes and an anonymous user for few methods. I've created a policy:

```
services.AddAuthorization(options =>
            {
                options.AddPolicy("Combined", new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .RequireRole(StaticDetails.AdminUser, StaticDetails.DoctorUser)
                     .AddAuthenticationSchemes(CookieAuthenticationDefaults.AuthenticationScheme, JwtBearerDefaults.AuthenticationScheme)
                     .Build());
            });
```
And decorated my hub class like [Authorize(Policy = "Combined"].
With this solution I can access my hub by both kind of authorization, but methods decorated with [AllowAnonymous] cannot be accessed by unauthorized user.
On the other hand if I decorate all methods I want to protect with [Authorize(Policy = "Combined"] (without decorating class) only cookie authenticated and anonymous user can access hub. In my SPA app I get 401 unauthorized.
I have just updated my app to .NET Core 3.0, but it did not help.

Is that a known issue? I couldn't find any topic covering my problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
We might want to add some information about this [here](https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#authorize-users-to-access-hubs-and-hub-methods)

**Comment by pbakun** [comment]
> * Allow anonymous connections to the Hub and put your auth policies on the methods that require authenticated users. This allows a single connection, but is more error-prone since you have to put auth policies on all the methods you want to secure.

I tried that. With that setup only cookie authenticated user could invoke methods. In SPA I got 401.

**Comment by BrennanConroy** [comment]
Right now your app is configured to run Authentication on Cookies by default. So your SPA is running Authentication on Cookies and doesn't get authenticated, so later when the Hub method runs Authorization, it fails because there wasn't a valid cookie in the SPA case.

You should be able to add `cfg.ForwardDefault = JwtBearerDefaults.AuthenticationScheme;` to `AddCookie(...)` so that in the SPA case you'll skip Cookies and run the Jwt logic.

@blowdart Correct me if I'm wrong please 😄

**Comment by blowdart** [comment]
@Tratcher or @HaoK would know best about how combining works.

**Comment by HaoK** [comment]
With the forwarding, basically the Cookie would always defer to the JwtBearer, are there really no situations where there is only a cookie and no JwtBearer?

**Comment by BrennanConroy** [comment]
There are 2 scenarios:
1. In my app I have started with Razor pages MVC with default cookie auth.
2. Later I've developed React-based SPA with JWT.

Is there a way to prefer Cookie over JWT then fallback? Or does it really matter, or is having Cookie defer to Jwt first then going back to Cookie fine?

**Comment by HaoK** [comment]
You can definitely add a 'virtual' scheme which does the behavior you want, a scheme called 'CookiesFirst' which implements Authenticate in that manner, first try authenticating against cookie, if that fails, then return Jwt's authenticate.  Or JwtFirst, I don't think it particularly matters which one has priority when there's both?

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Core/src/AuthenticationBuilder.cs#L169

AddPolicyScheme is what we refer to these 'handlerless' virtual schemes

**Comment by HaoK** [comment]
Actually it looks like since you want to do true chaining/fallback rather than pure forwarding, you will have to implement a handler that does that logic, so policy schemes aren't sufficient since those were intended to be schemes that only forward to other schemes

**Comment by pbakun** [comment]
Thanks for all answers!

I managed to make a workaround.
I've implemented authorization handler with both schemes and passing everything through:
```
public class HubRequirement : AuthorizationHandler<HubRequirement>, IAuthorizationRequirement
    {
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, HubRequirement requirement)
        {

            context.Succeed(requirement);

            return Task.CompletedTask;
        }
    }
```

```
services.AddAuthorization(options =>
            {
                options.AddPolicy("Combined", new AuthorizationPolicyBuilder()
                     .RequireAuthenticatedUser()
                     .RequireRole(StaticDetails.AdminUser, StaticDetails.DoctorUser)
                     .Build());

                options.AddPolicy("HubRestricted", policy =>
                {
                    policy.AddRequirements(new HubRequirement());
                    policy.AddAuthenticationSchemes(CookieAuthenticationDefaults.AuthenticationScheme, JwtBearerDefaults.AuthenticationScheme);
                });

            });

            services.AddSingleton<IAuthorizationHandler, HubRequirement>();
```
In signalr I have Authorize attribute with custom requirements decorating hub's class. Also each method I want user to be authorized I've put Authorize attribute with previously used "Combined" policy, but without specifying auth schemes.

```
[Authorize(Policy = "HubRestricted")]
public class QueueHub : Hub
    {
        [Authorize("Combined")]
        public async Task RegisterDoctor(string roomNo)
        {
                //method only for authorized users, I have claims and can identify user
        }

        public async Task RegisterPatient(string roomNo)
        {
                //method for anonymous users
        }
```

Now I'm able authorize for cookie or jwt client. For some methods anonymous user can also log into the signalr hub.

Thanks for help!
