### ISSUE TITLE
Difference between @bind and @bind-value

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#18331]
This page uses @bind for binding to a variable.

The following page uses @bind-value -- https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0

As noted in the opening comment here, both can be used.
https://github.com/dotnet/aspnetcore/issues/10893#issue-452468712

I looked but didn't see any documentation on how they are different. Could the difference between the 2 be talked about somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mrlife ... What I think happened is that the content was sent over from engineering that way. I didn't question it. I'll need to research back and find out if I inquired on it, which I'll do next week.

I do **_NOT_** think we should show it if it's only a fallback and the topic can be consistent with everyplace we bind with `@bind`.

**Comment by guardrex** [comment]
@mrlife ... Took a look and now I recall ... this is just *property binding*. Actually, it is called out in the opening example ...

> The `InputText` component's `@bind-Value` binds:
> * The model property (`exampleModel.Name`) to the `InputText` component's `Value` property.
> * A change event delegate to the `InputText` component's `ValueChanged` property.

... and property binding is covered in the *Data binding* topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1#parent-to-child-binding-with-component-parameters

... so what it needs there is a **_cross-link_**. I'll take care of that right now ... it's a quick fix.
