### ISSUE TITLE
Clarification on when/how expired items are removed from memory

### ISSUE THREAD

**Issue by danobri** [dotnet/AspNetCore.Docs#18332]
I would like some clarification regarding when/how expired items are cleared from memory.  Specifically I am trying to understand this sentence:

Expiration doesn't happen in the background. There is no timer that actively scans the cache for expired items. Any activity on the cache (Get, Set, Remove) can trigger a background scan for expired items. 

Does that mean if you have 5 expired cache entries all 5 will remain in memory until the next time ANY key is accessed, OR only when that specific key is accessed?

I am also confused by the wording "can trigger" - shouldn't it be "will trigger"?  Or will it only trigger an expiration under certain circumstances?  If so, what are they?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by danobri** [comment]
So all expired items will be evicted every time get, set or remove is called, regardless of whether it is called on one of the expired items?

**Comment by serpent5** [comment]
You can learn more about the specifics by looking at the source code. Look for calls to [`StartScanForExpiredItems`](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L309) and you'll see _exactly_ when the scan runs.

**Comment by Rick-Anderson** [comment]
Thanks @serpent5 
@danobri  this is an implementation detail that shouldn't matter to you ***AND*** it's subject to change.

**Comment by danobri** [comment]
I really wasn't looking for implementation details.  I'm just trying to understand the functionality, as I find the current documentation confusing, specifically this sentence:

> Any activity on the cache (Get, Set, Remove) can trigger a background scan for expired items.
