### ISSUE TITLE
The documentation provided here is wrong.

### ISSUE THREAD

**Issue by carlthecoder** [dotnet/AspNetCore.Docs#18346]
The button onclick event binding seems wrong. It does not seem to accept method groups, but instead wants a method call with the parantheses included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de31c7e-7895-9d7c-0d9a-5bdfe83b60a9
* Version Independent ID: 334b7206-d383-40c3-b346-b54df9d87293
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Dup of #18345.
