### ISSUE TITLE
Startup.cs and scaffolding

### ISSUE THREAD

**Issue by kylesunumich** [dotnet/AspNetCore.Docs#18349]
1.) I'm guessing we are supposed to create a new file called Startup.cs and copy and paste ALL of the code, not just the highlighted code? This was not mentioned in the instructions

2.) when I run the command: 
dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers

I am getting this in terminal: 
Scaffolding failed.
Could not find project file in /Users/kylesun/Projects/TodoApi

Any help is appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Rick-Anderson** [comment]
> 1.) I'm guessing we are supposed to create a new file called Startup.cs and copy and paste ALL of the code, 

No, follow the instructions
