### ISSUE TITLE
Asp.Net 5, .Net 5, "Asp.Net Core 5" confusion in the screenshot

### ISSUE THREAD

**Issue by ewdlop** [dotnet/AspNetCore.Docs#18343]
I think the "Home Page" screenshot under _Combine social and local login accounts_  probably is going to be very outdated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This content has not been updated to  ASP.NET Core 5. We don't always update all the images.
