### ISSUE TITLE
Orderby has been overriden by Distinct

### ISSUE THREAD

**Issue by luilver** [dotnet/AspNetCore.Docs#18351]
I have tested using *.NET Core 3.1.4* and `Distinct`, as per described in MSDN, will return an unsorted collection overriding previous `OrderBy`. This could confuse newbies like me to fully understand the goal behind sorting genres. For better understanding I suggest to remove **orderby m.Genre** line.

Happy coding !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
