### ISSUE TITLE
java client issues 

### ISSUE THREAD

**Issue by alonsd** [dotnet/AspNetCore.Docs#18352]
I am using the java client for SignalR but I ran into 2 issues for my Android application - 

1) how can I configure a connection state listener ? I saw one that looks perfect for iOS development in Swift language but I did not see anything at Java. 

2) how can I configure the logging level of the library? in the readme file it states to add the `slf4j` library and I did so, but it literally did nothing. Hopefully someone can help me how to actually make it work. 

Thanks!

> Hello @alonsd ... I recommend that you close this and re-open it using the **This page** feedback button and form at the bottom of the topic that you're looking at. It will add metadata to the issue automatically, which also automatically pings the author. You'll probably get a faster answer that way.

thanks for the help, I didn't really understand how to work with that metadata

**Comment by guardrex** [comment]
Hello @alonsd ... I recommend that you close this and re-open it using the **This page** feedback button and form at the bottom of the topic that you're looking at. It will add metadata to the issue automatically, which also automatically pings the author. You'll probably get a faster answer that way.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
