### ISSUE TITLE
launch.json build target

### ISSUE THREAD

**Issue by SgtSQL** [dotnet/AspNetCore.Docs#18355]
I had to modify the launch.json build target to work with the instructions provided regarding running in a non-debug config. I think this was because of how the OmniSharp dependency works. It definitely took longer for me to get through this page than I would have liked, and the snag was not about the content I was trying to learn about. First impression was frustration. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is not written for OmniSharp

**Comment by SgtSQL** [comment]
It's listed in the dependencies for VS Code by way of being a dependency of the C# for VS Code plugin i.e. powered by OmniSharp.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
