### ISSUE TITLE
Polymorphic model binding example not working

### ISSUE THREAD

**Issue by KoditkarVedant** [dotnet/AspNetCore.Docs#18368]
Polymorphic model binding example given [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1#polymorphic-model-binding) always returns null result.

`var modelTypeValue = bindingContext.ValueProvider.GetValue(modelKindName).FirstValue;` in particular should return a value but always returns null.

I've added the binder like this in my `startup.cs`

```
services.AddMvc(options =>
{
      options.ModelBinderProviders.Insert(0, new DeviceModelBinderProvider());
}); 
```
Can anyone help me with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for Custom Model Binding #16319
