### ISSUE TITLE
[Blazor] Update debugging instructions for Blazor WASM on VS Code

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#18364]
[EDIT by guardrex to add the metadata]

This is a placeholder issue to update the Blazor WASM debug guidelines with details on how to debug with the new blazorwasm debug adapter.

1. Create a new Blazor WASM application and open it in VS Code.
2. Ensure that you have the OmniSharp and JS Debug extensions installed.
3. Navigate to the "Debug" section on the left. Then, click "create a launch.json file". In the window that pops up, select "Blazor WebAssembly Debug".
4. Launch the "Launch and Debug Blazor WebAssembly Application" configuration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
We're gearing up to release this as part of the upcoming C# release, likely this week.

I'll submit a PR with the docs that we can collaborate on.

**Comment by guardrex** [comment]
Cool ... we have a big one with ToC updates landing tonight (I hope 🤞) and merging either tonight or tomorrow early AM. Recommend holding off on creating your branch until that PR merges. I'll ping u back here when the coast is clear.

**Comment by captainsafia** [comment]
Sounds good. I'll write up the docs in another file for the time being and integrate it when the time is write.

Good luck with the ToC refactor!

**Comment by captainsafia** [comment]
@guardrex The O# extension has been released. Are we cleared to update the docs now?

**Comment by guardrex** [comment]
I didn't receive my guidance from DR and Artak yet, so I haven't set up the mega-ToC branch/PR yet. Yes, let's go ahead with this issue, and I'll work the ToC thing after this is done and merged.

**Comment by captainsafia** [comment]
Cool! I'll open up a PR with a draft of the text I've produced thus far.

**Comment by guardrex** [comment]
@captainsafia This was fixed by https://github.com/dotnet/AspNetCore.Docs/pull/18570, right?

**Comment by captainsafia** [comment]
Correct -- we can close this now.

**Comment by guardrex** [comment]
Cool.

![who](https://user-images.githubusercontent.com/1622880/83780734-29ae3300-a653-11ea-9c48-7450aa4745b1.jpg)

**_It's a pleasure to work with you, Captain!_**
&mdash; The Doctor (Tom Baker), Dr Who: [The Pirate Planet](https://www.bbc.co.uk/programmes/p00r9wqx), ©1978 [BBC](https://www.bbc.co.uk/)
