### ISSUE TITLE
Screenshots / steps out of date

### ISSUE THREAD

**Issue by AngelosP** [dotnet/AspNetCore.Docs#18366]
The latest version of Visual Studio (16.6) looks and behaves differently than this article describes. That's because Publish in Visual Studio has been getting UX updates in the last few releases.

I own this feature in Visual Studio so if you need any help updating this content just let me know. I'm happy to submit PRs or whatever the right process is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.1&viewFallbackFrom=vs-2019)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
5.8 K PV/month.
@AngelosP a PR would be great.

**Comment by AngelosP** [comment]
https://github.com/dotnet/AspNetCore.Docs/pull/18392

**Comment by mcurko** [comment]
These options don't exist on newest VS:
Expand Databases and check Use this connection string at runtime.
Expand Entity Framework Migrations and check Apply this migration on publish.
