### ISSUE TITLE
Should page names be localized?

### ISSUE THREAD

**Issue by JasonCard** [dotnet/AspNetCore.Docs#18372]
Should the page names like "Home", "Counter", "Fetch data" be localizable? If yes, no changes needed. If not, then it would be great if those terms can be blocked from localization by using either in-line code, or [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, they should be blocked because AFAIK the templates aren't translated in any way.

I'll use in-line code because these might be translated in other contexts.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @wadepickett Seems like under the latest thinking that we should be code fencing ...

* File names (e.g. *_Host.cshtml* :point_right: `_Host.cshtml`)
* Folder names (e.g., *Pages* :point_right: `Pages`)
* Page names (e.g., *Counter* page :point_right: `Counter` page)
* Paths (e.g., *wwwroot/css* :point_right: `wwwroot/css`)
* Extensions (e.g., *.razor* :point_right: `.razor`)

In terms of the IDEs, it's difficult to know what changes for our UI text references. I theoretically can set VS to another language and back and :pray: *hopefully not get hosed* :pray:, but I don't really want to risk it.

**Comment by guardrex** [comment]
I felt a safer changing the language on my iMac. Interesting outcome ...

* A lot of UI is changed (e.g., "Application" is translated to "Aplicacion"), but some isn't (e.g. the new "Web and Console" isn't).
* One Blazor template is translated ... "Blazor Server App" is "Aplicacion de servidor Blazor" in Spanish ... but "Blazor WebAssembly App" isn't.
* In a Blazor Server app, everything is in English. I assume the same for all template-based apps.

The IDE is variable, but the list above :point_up: looks right for code fencing changes.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @wadepickett I'll be working on this soon. Has a decision been made on what to code-fence ... is the list that I posted correct? :point_up:

**Comment by Rick-Anderson** [comment]
I don't think there's much problem with Home. I suggest some time in the past, when updating a doc, look at the doc in another language. I look at spanish and german. Usually problems like this jump out.

**Comment by guardrex** [comment]
The app won't be localized, so the sidebar navlink will render "Home."

**Comment by guardrex** [comment]
@JasonCard ... Code-fence package names, correct? For example ... 

`Microsoft.AspNetCore.SignalR.Client`

**Comment by JasonCard** [comment]
@guardrex Yes, I agree.

**Comment by guardrex** [comment]
:smile: ...

```
\*.*\*
```

... is rapidly becoming my favorite RegEx on this issue.

We've already gone a little bit down the slippery slope of styling link text. The manual says 'don't do it,' but we're likely going to need to in some cases if we don't use the `no-loc` metadata for a given topic. I caution against using `no-loc` in specific topics because that will eliminate the possibility of performing a massive find-'n-replace on that line to add something to the list for every topic.

Another challenge is bold text for UI that we also want to code-fence to avoid loc. The Blazor app template has a counter button with text of "Click me" on a button. We'd normally put that in bold (\*\*Click me\*\*) in the doc text because it's a UI element. Because template text isn't translated, I guess that I'll need to attempt both with:

```
**`Click me`**
```

**Comment by Rick-Anderson** [comment]
> We've already gone a little bit down the slippery slope of styling link text. The manual says 'don't do it,'

Unless there's a risk of over-localization, then do it. Same with hard coded file names like `wwwroot`.

**Comment by guardrex** [comment]
Yes, I'll continue with it. :point_up:

WRT bold and code-fencing, it seems ok.

Before:

<img width="192" alt="Capture" src="https://user-images.githubusercontent.com/1622880/85209823-92a6d380-b300-11ea-92b4-a1746173e9d8.PNG">

After:

<img width="173" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/85209827-989cb480-b300-11ea-896b-036bfb65cb7e.PNG">

**Comment by Rick-Anderson** [comment]
How do you do bold code fenced?

**Comment by CHOWYANYAN** [comment]
？
    	
    	

    	******************************************DISCLAIMER NOTICE: This transmission may contain confidential information protected by law. The information is intended only for use consistent with the business stated and discussed in this transmission. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or the taking of any action based on the contents is strictly prohibited. If you have received this transmission in error, your cooperation is appreciated.* ©️ Copyright SOYA 2019
    
  




On Sun, Jun 21, 2020 at 2:17 AM +0800, "Jason Card" <notifications@github.com> wrote:















@guardrex Yes, I agree.

**Comment by guardrex** [comment]
Like this ...

```
**`Click me`**
```
