### ISSUE TITLE
Record the App ID URI (Client App)

### ISSUE THREAD

**Issue by marshallr12** [dotnet/AspNetCore.Docs#18386]
In the "Register a Client App" section, right after getting the the API permissions section, the instructions say "Record the App ID URI (for example, https://{TENANT}.onmicrosoft.com/{SERVER API APP CLIENT ID OR CUSTOM VALUE})." Where do we get this value? At this point, if I follow the directions in order, the "Application ID URI" value in the overview is blank (i.e., it says "Add an application ID URI).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @marshallr12 ...

It's in the sidebar panel that pops up after you select the **API / Permissions name** in the **Configured permissions**.

I named mine `API.Access`, so select that ...

<img width="386" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/82374052-2294ed00-99e4-11ea-8116-bf373acdf18d.PNG">

... and then you get this ...

<img width="554" alt="Capture" src="https://user-images.githubusercontent.com/1622880/82373924-f4171200-99e3-11ea-8ce1-976c1d0cfbb4.PNG">

... the APP ID URI is the part before the permission name; so in this case, it's ...

```
https://{TENANT}.onmicrosoft.com/16473e7d-4d8d-401f-a2d4-95230088a256
```

You can also get it from the Server app's registration (**Expose an API** blade) ...

<img width="512" alt="Capture3" src="https://user-images.githubusercontent.com/1622880/82374458-b49cf580-99e4-11ea-9a26-3dc5c30f0a0a.PNG">

**Comment by guardrex** [comment]
Actually, the "record" language is an errant cut-'n-paste. At this point, there's no need to record it. I'll strike that in that location. The line stays up above where the Server app is configured.

I'll be improving this process soon. For one thing, we'll have proper VS vs. CLI instructions so that devs using VS don't need to work with this **_GIANT_** command ... they'll just use the VS UI experience. That's coming soon.
