### ISSUE TITLE
Generating unobtrusive validation attributes

### ISSUE THREAD

**Issue by jeremycook** [dotnet/AspNetCore.Docs#18385]
This was possible in ASP.NET MVC 5. What would it look like to manually add unobtrusive validation attributes to an `<input />` element? Here is an example of what I am thinking where `Html.UnobtrusiveValidationAttributes()` is something I made up.

```cshtml
// EditorTemplates/ExampleInput.cshtml
@model string
<input id="@Html.IdForModel()" name="@Html.NameForModel()" value="@Model" data-myattribute="Yar" @Html.UnobtrusiveValidationAttributes() />
```

Same example with a hypothetical `asp-formodel` attribute that would add name, id, and validation attributes.

```cshtml
// EditorTemplates/ExampleInput.cshtml
@model string
<input asp-formodel data-myattribute="Yar" />
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Seehttps://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation
