### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by marshallr12** [dotnet/AspNetCore.Docs#18389]
Once you create the app via the dotnet command, the redirect URI is not necessarily going to be 5001 as is specified in the client app setup (for example, I had to update it to 44355, which was the SSL port assigned for the server app in launchSettings.json ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good point. VS defaults to the IIS profile, so it should be more flexible (i.e., `{PORT}`) and say where to find it. I'll patch that right now.

**Comment by marshallr12** [comment]
I was able to get thinkings working after following the tutorial this time - I didn't work for me when I first followed it a couple months ago. Well done!

**Comment by guardrex** [comment]
Thanks.

I just noticed something else that's a pain point here. Thus far, the dev reads down and performs the Azure configuration, collects the values, **_THEN_** creates the app. Well, at the point where the callback URI would be provided, there's no app and no randomly generated IIS Express port.

What I'll need to do is have the user perform the API step in the portal **after** they create the app. I'll open a new issue for that and get it done first thing tomorrow morning.

**Comment by guardrex** [comment]
Alternatively, I could stick with this sequence, but I'll be forced to tell the reader to use the Kestrel profile. 🤔 I'll sleep on it. :smile: lol

**Comment by guardrex** [comment]
I'll combine this with the "instance" issue that you opened. I was going to work that in the morning anyway.
