### ISSUE TITLE
Blazor WASM security topic updates

### ISSUE THREAD

**Issue by marshallr12** [dotnet/AspNetCore.Docs#18387]
In the dotnet command, I'm assuming {AAD B2C INSTANCE} refers to the directory id GUID recorded earlier? If so, this should probably be { AAD B2C DIRECTORY ID} in the instruction instead, since that's how it's referred to earlier in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by marshallr12** [comment]
Actually, nevermind, I see this is recorded earlier in the totiral.

**Comment by marshallr12** [comment]
It's not clear where to find the value of "AAD B2C instance." Many people who follow this tutorial would have created their B2C instance at some prior to the tutorial and would want to try using Blazor with the existing instance. So it would be helpful to know where to look to find this value.

**Comment by guardrex** [comment]
I agree with the sentiment, and I think I have the tenant setup instruction in one topic but not the other. I'll get this on my next pass of these topics, which will be soon. Thanks for calling it out.

**Comment by guardrex** [comment]
Also work a sequence problem with the port.

See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/18389#issuecomment-631082892
