### ISSUE TITLE
Production environment setup

### ISSUE THREAD

**Issue by danielheddelin** [dotnet/AspNetCore.Docs#18398]
It would be very useful if you added information regarding the SendGridUser and SendGridKey when moving to e.g. Azure. To get it to work here - simply add these two values to the app's appsettings.
Also a minor comment - your async code example lacks async in the signature and await in the calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The key should never be stored in app settings. see secret manager and configuration
