### ISSUE TITLE
Using HTTPContext in other layers

### ISSUE THREAD

**Issue by balukantu** [dotnet/AspNetCore.Docs#18397]
Hi team,

As per the documentation, we can easily access the HTTP context in other layers. 
However, I have question regarding using the HTTP context in the business layer. Is it recommended or a good approach to use HTTPContext in other layers apart from the WebApi/ MVC context.

**Comment by guardrex** [comment]
Hello @balukantu ... Please open this issue using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
