### ISSUE TITLE
Movie App Link

### ISSUE THREAD

**Issue by nicklocascio** [dotnet/AspNetCore.Docs#18396]
In the previous section, when we were updating the views and layout, there was a line in the tutorial that said that the Movie App link was not yet functional. However, in this part in the Test the App section, when I click on the Movie App link, I get an error that there is no page found. Am I missing the part where we make that link functional, or is that part of registering the database that I am doing incorrectly, or is that part skipped in the tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio-mac#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
keep going
