### ISSUE TITLE
Access to the Identity Token

### ISSUE THREAD

**Issue by allderidge** [dotnet/AspNetCore.Docs#18401]
Are there any plans to expose a reliable way of accessing the identity token obtained from Identity Provider?

I require a means to send the users identity token to a backend web service in order to identify that user and authorise them dependent on groups claims present in the token. Ideally the token would be automatically refreshed in the background.

I have a working solution that obtains the token directly via Java Script interop using the following function after checking the user is authenticated in c# :
            async getToken() {
                var user = await window.AuthenticationService.instance._userManager.getUser();
                return user.id_token;
            }

This approach works but has limitations in that the identity token could have expired and isn't part of an official API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55d96ce7-2ead-ebc2-973e-e319082937b0
* Version Independent ID: 44ee9a17-4e34-6463-66e8-f1eb212845a4
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @allderidge ... Ask the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your question. I'm curious to see what they say on this.
