### ISSUE TITLE
Directing page to send after routing to an MVC Controller

### ISSUE THREAD

**Issue by BryanFitzpatrick** [dotnet/AspNetCore.Docs#18407]
I found this page ("Routing to controller actions in ASP.NET Core") really useful, and I have my controller successfully intercepting the urls I want to intercept so I can do my processing (in a Blazor WebAssembly App using Telerik components).  What I cannot manage to figure out is how I return an ActionResult to send it to the page I want (or actually just to resend the page the client was on).  Clearly I must be able to do such a thing.  Can you help me please?

BryanMFitzpatrick@Yahoo.CO.UK

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-au/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @babakramak ...

> in a Blazor WebAssembly App

... doesn't make sense in the context of this topic. The routing in this topic would be for an ASP.NET Core MVC app. There are no controllers in a Blazor WebAssembly app. The routing coverage for Blazor is in ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/routing
