### ISSUE TITLE
Using HTTPContext in other layers

### ISSUE THREAD

**Issue by balukantu** [dotnet/AspNetCore.Docs#18419]
As per the documentation, we can easily access the HTTP context in other layers.
However, I have a question regarding using the HTTP context in the business layer. Is it a recommended approach or a better approach to use HTTPContext in other layers apart from the WebApi/ MVC context.

I have heard that accessing HTTP context is another layer apart from Controllers is not an ideal approach.

**UseCase**
I would like to update user details who has modified the database tables and save the changes. In order to update userId, I am passing userId in headers and accessing that in the business layer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
> I would like to update user details who has modified the database tables and save the changes. In order to update userId, I am passing userId in headers and accessing that in the business layer.

That's the worst thing you can do. Don't couple your business logic to the specific `HttpContext`.

The usual ways to solve this are to do something like this:

1. Pass the user id explicitly to your APIs.

2. Introduce an abstraction for accessing the current user:

```C#
public interface IUserAccessor
{
    string UserId { get; }
}
```

Then you business logic layer can take a dependency on `IUserAccessor`.

The implementation can be tied to the `IHttpContextAccessor`:

```C#
public class HttpUserAccessor : IUserAccessor
{
    private readonly IHttpContextAccessor _accessor;
    public HttpUserAccessor(IHttpContextAccessor accessor)
    {
        _accessor = accessor;
    }

    string UserId => _accessor.HttpContext.Request.Headers["userId"];
}
```

Then you would register this in ConfigureServices:

```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpContextAccessor();
    services.AddSingleton<IUserAccessor, HttpUserAccessor>();
}
```

**Comment by weitzhandler** [comment]
Thanks @Rick-Anderson for your kind and detailed answer,
I'm facing a related issue where in my acceptance test I want to verify the `HttpContext.User` is filled with the current user.
I'm using [ASP.NET Core Integration Tests](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests) for this.  
When trying `IHttpContextAccessor.HttpContext` (from service-provider), it's `null`.
I also tried `IFeatureCollection` or IHttpAuthenticationFeature`, neither of which were registered.

[This](https://github.com/dotnet/AspNetCore.Docs/issues/19358) approach which also doesn't seem to work.

**Comment by davidfowl** [comment]
IHttpContextAccessor requires that somebody called `AddHttpContextAccessor`.

**Comment by StevenLiekens** [comment]
I thought that _IHttpContextAccessor_ was meant to enable smoother migrations from .NET Framework to .NET Core but now the documentation recommends using it for new code. Did something change?

**Comment by davidfowl** [comment]
@StevenLiekens I'm surprised that's our guidance. I think there are definitely scenarios where you need it but I don't think we should recommend it. It should be listed as a requirement in a very particular case. 

cc @Rick-Anderson @guardrex can we fix this?

**Comment by davidfowl** [comment]
@weitzhandler can you create an issue on the product repo with a sample that reproducers the problem

**Comment by weitzhandler** [comment]
> on the product repo

Would that be https://github.com/dotnet/aspnetcore?

**Comment by davidfowl** [comment]
Yep

**Comment by guardrex** [comment]
> now the documentation recommends using it for new code

The doc language is specific: It specifies "inside a service."

> ASP.NET Core apps access `HttpContext` through the `IHttpContextAccessor` interface and its default implementation `HttpContextAccessor`. **_It's only necessary to use `IHttpContextAccessor` when you need access to the `HttpContext` inside a service._**

(emphasis added)

https://docs.microsoft.com/aspnet/core/fundamentals/http-context

The following RP, view, and controller sections use the property. After that, the *Use HttpContext from custom components* section is specific as well ...

> For other framework and custom components that require access to `HttpContext`, the recommended approach is to register a dependency using the built-in dependency injection container. The dependency injection container supplies the `IHttpContextAccessor` to any classes that declare it as a dependency in their constructors:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#use-httpcontext-from-custom-components

**Comment by weitzhandler** [comment]
> @davidfowl 
> can you create an issue on the product repo with a sample that reproducers the problem

Yessir: https://github.com/dotnet/aspnetcore/issues/24416
