### ISSUE TITLE
Simpler example

### ISSUE THREAD

**Issue by baloodevil** [dotnet/AspNetCore.Docs#18426]
My opinion is that this example would be better with something simple in JavaScript being called, like a 'Hello World' dialog box, rather than an esoteric [Decoder library](https://developer.mozilla.org/docs/Web/API/TextDecoder).  When learning one topic it is best to make any associated topic as simple as possible.  That would help users to understand that the interop is simple and encourage adoption.  IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @baloodevil ... Thanks for that feedback, but this is a JS API. Sure, it could be anything, but this is one that offloads work to the client and would be a pain to implement yourself, so it does make a decent example from that perspective. We'll keep an :ear: open for more feedback.

> like a 'Hello World' dialog box

... that's a latter example ... keep reading, and you'll come to it. It's also in the common sample app.

Actually, it's the latter examples in this topic and the 'call .NET from JS' that cause more negative feedback. Those examples are already scheduled for updates, which I hope to get to within the next couple of months. 🏃😅
