### ISSUE TITLE
Add a sample of creating your own specialized authorizationmessagehandler

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18422]
Can we add a sample that instead of configuring the handler like this, creates a custom class? The idea is to follow the pattern for BaseAddressMessageHandler but for other origins:

* Create a class
* Extend AuthorizationMessageHandler
* Create a constructor with any dependency you need
* Call ConfigureHandler within the constructor
* Register the handler as transient on DI
* Call AddMessageHandler&lt;CustomHandler&gt; in the client configuration.

```csharp
    return new HttpClient(sp.GetRequiredService&lt;AuthorizationMessageHandler&gt;()
        .ConfigureHandler(
            new [] { "https://www.example.com/base" },
            scopes: new[] { "example.read", "example.write" }))
        {
            BaseAddress = new Uri(builder.HostEnvironment.BaseAddress)
        };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
> @javiercn "add" and "instead of" don't jive ... which is it ... **_add_** a another example to what's shown or **_replace_** what's shown?

Add but make it the first example you show people or if you don't want both samples remove the existing one

**Comment by guardrex** [comment]
Cool ... yeah ... I have a plan in place now to do this in two **sub-sections** there so that the dev can see both approaches. I'll place the custom class section first. I'll ping u for review on the PR, which should be up shortly.
