### ISSUE TITLE
Kestrel maximum request body size sample code is incorrect

### ISSUE THREAD

**Issue by dwalleck** [dotnet/AspNetCore.Docs#18423]
As I was working through some of the samples, I ran into an issue where the code block in the [Kestrel maximum request body size](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#kestrel-maximum-request-body-size) had an error that the **ConfigureKestrel** method did not exist. 

After a bit of searching, I found another [example](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#kestrel-in-aspnet-core-apps) that shows that **ConfigureKestrel** should be called on the webBuilder and not chained off the **CreateDefaultBuilder** method, which appears to work. The code sample on this page just needs to correctly show how to configure kestrel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @dwalleck ... I'll patch that up right now.

**Comment by guardrex** [comment]
I think that was an accidental holdover from the 2.x doc that didn't get the change. I see that in the 2.x example, we had ...

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .ConfigureKestrel((context, options) =>
        {
            // Handle requests up to 50 MB
            options.Limits.MaxRequestBodySize = 52428800;
        });
```
