### ISSUE TITLE
documentation on custom data context and user model for identity server

### ISSUE THREAD

**Issue by ghost** [dotnet/AspNetCore.Docs#18427]
Good day,

Is there a documentation on how to use a custom user model and custom dbcontext for AddApiAuthorization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17515ff7-32a6-c6f7-0425-535775cd6e28
* Version Independent ID: 1416abd7-0b23-ca93-62e7-59d2532d4275
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=netcore-cli)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hoksource ... We don't at this time. We only have the customizing the user coverage at :point_right: https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#customize-the-user, but it only involves a claims example.

I speculate that you can inject a context into the factory and then using the custom user class (a `RemoteUserAccount`) do what you like with them. However, I'm **_very new_** to Identity Server, so I haven't tried that myself (*yet*).

I'll mark this for triage to see if they want to go further with our example. We'd either have another example that does something with the dB and the factory or expand the current example (a claim) with some kind of dB operation in there.
