### ISSUE TITLE
Performance implications of EventCallback and this document

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/AspNetCore.Docs#18420]
## Summary
I think the section on ShouldRender is useful, but it needs to be put in a wider context and the preventative measure of being more cautious with EventCallback should be included.

## Detail
I think you should mention on this page of the effect of using EventCallback in your components - and the connection that has to the first performance tip here about manually preventing re-rendering through ShouldRender.

This is especially important for anyone rendering a grid (or any component with a large number of children - like a dashboard) - where use of EventCallback in one component in one cell of that grid will, of course call StateHasChanged on the parent (the grid) and therefore cause a re-render of every child. 

And, of course if that "grid" declares an EventCallback which is triggered by the user clicking that one cell on the grid (quite common) then the grid parent also gets StateHasChanged invoked, which means that clicking that one cell in the grid has potentially re-rendered the entire grid/page/application unnecessarily.

At the moment, the developer that came to this page with issues, would see "you should override ShouldRender" and thinking "oh my, I have to add code to every component to prevent this performance issue" when what they should be thinking is - "where have I used EventCallback when I don't actually want an automatic re-render of the parent tree"

## And finally...
I have seen exactly these performance issues in the wild - where use of an EventCallback where it wasn't actually needed was causing a dashboard to perform very badly - and addressing that specific issue solved a major part of the performance problems (there were others).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe8c28b-47a1-dbd4-131c-5ca25006107d
* Version Independent ID: 70b7635d-767d-aff9-255f-aec457e86b64
* Content: [ASP.NET Core Blazor WebAssembly performance best practices](https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1#avoid-unnecessary-component-renders)
* Content Source: [aspnetcore/performance/blazor/webassembly-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/blazor/webassembly-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @pranavkm
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pranavkm This seems like it's fairly well covered at ...

https://docs.microsoft.com/en-us/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1#avoid-unnecessary-component-renders

... is there anything further that you'd like to say?

**Comment by SQL-MisterMagoo** [comment]
That page makes no reference to EventCallback at all does it?

**Comment by pranavkm** [comment]
> At the moment, the developer that came to this page with issues, would see "you should override ShouldRender" and thinking "oh my, I have to add code to every component to prevent this performance issue" when what they should be thinking is - "where have I used EventCallback when I don't actually want an automatic re-render of the parent tree"

@SQL-MisterMagoo does raise a valid point. We don't want to give users the impression that you want to use this all the time. Maybe 

> Most apps don't require fine-grained control, but ShouldRender can also be used to selectively render a component responding to a UI event.

could elaborate to call out where you might consider using this. The example he's listed in the issue is very well-written. Maybe we could adopt :

> Most apps don't require fine-grained control, but ShouldRender can also be used to selectively render a component responding to a UI event. Using `ShouldRender` might also be important to in scenarios involving a large number of components being rendered. Consider a grid, where use of EventCallback in one component in one cell of that grid call StateHasChanged on the grid and therefore cause a re-render of every child. If only a small number of cells need to re-rendered, using `ShouldRender` can avoid the penalty of unnecessary renders. In the following example:

Or something along those lines. Thoughts?

**Comment by SQL-MisterMagoo** [comment]
To illustrate what I mean, take a look here : https://blazorevents.azurewebsites.net/

Increase the number of balls to 20 or 30 or even more, then click one of the "Action" balls (these don't use EventCallback in their binding) and notice only that one ball updates.

Now click one of the EventCallback balls. 

Now imagine instead of 20 copies of one component that was a dashboard with 20 different components - this documentation suggests changing 20 components to each override ShouldRender - instead of changing the core problem - EventCallback being used when it is not needed.

**Comment by guardrex** [comment]
Ok ... yes ... I see what you mean. I'll work your paragraph into the doc, @pranavkm.

@SQL-MisterMagoo, I'll ping u on the PR for review. I should be able to get to this next week. 🤞&dagger;

&dagger;My estimates on when issues will be worked can't be trusted. :smile: When I say "next week," what I really mean is, **"I'd like to work on it next week, but it might take _SIX MONTHS._"** :smile::cry::smile::cry: ... it's the way of the world around here with a pile of high priority issues potentially landing at any second.

**Comment by ChristianWeyer** [comment]
@SQL-MisterMagoo Has this been resolved to your satisfaction?
If I go to https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0 and search for 'Action' or 'EventCallback' I do not seem to see your discussion above covered there...?

**Comment by guardrex** [comment]
It was removed by Steve at ...

https://github.com/dotnet/AspNetCore.Docs/pull/20057/files#diff-b1d24359c635e2fa9e71ffa26bde58f992f974d0925722b60b6eeb93dab26a46L30

btw- It's best to open a new issue from the **This page** feedback button+form and not comment on closed issues and PR. Add a cross-link from the new issue to the close issue(s)/PR(s). In this case tho, I don't think it's necessary ... it looks like Steve didn't approve of those remarks given that he gave them the chop 🔪.

**Comment by guardrex** [comment]
:smile: ... but of course ... open a new issue if you think he should've left that ... or part of it. I'm sure he'll take a look at whatever feedback you offer on it.

**Comment by ChristianWeyer** [comment]
> It was removed by Steve at ...
> 
> https://github.com/dotnet/AspNetCore.Docs/pull/20057/files#diff-b1d24359c635e2fa9e71ffa26bde58f992f974d0925722b60b6eeb93dab26a46L30
> 
> btw- It's best to open a new issue from the **This page** feedback button+form and not comment on closed issues and PRs. Add a cross-link from the new issue to the closed issue(s)/PR(s). In this case tho, I don't think it's necessary ... it looks like Steve didn't approve of those remarks given that he gave them the chop 🔪.

Maybe I am blind, but where exactly was the section about `Action` vs `EventCallback` being removed...?

**Comment by guardrex** [comment]
I see what you mean. I was focused on what @pranavkm said ... not on @SQL-MisterMagoo's example and remark on `EventCallback`.

@pranavkm ... I'm re-opening for another look. We might be missing guidance on the **_avoidance of `EventCallback` for improved perf_**. I'll mark it for triage given that I don't know if this is actionable at this point for work.

**Comment by guardrex** [comment]
@ChristianWeyer ... I'm taking a sec here to see where the Blazor.Docs issues stand, close some issues out, and schedule other issues.

I ran an eye :eye: back over this: I don't see what the actionable issue is for `Action` (yet). We addressed the original issue and remark that Pranav made ... then Steve cut it 🔪 on a later update, so I imagine that he didn't care for it. Steve has ...

https://docs.microsoft.com/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-3.1#avoid-rerendering-after-handling-events-without-state-changes

... and that at least calls out what was on his mind at the time of his update.

If there is something in addition to cover, please open a new issue from the bottom of the topic and explain what's missing for `Action`/`EventCallback` as it pertains to WASM perf, then I'll ask Steve to take a look and see if your suggestion should be addressed.
