### ISSUE TITLE
Top-level node validation doesn't seem to be working in ASP.NET Core 3.1

### ISSUE THREAD

**Issue by eparizzi** [dotnet/AspNetCore.Docs#18438]
The examples provided in the Top-level node validation section (https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#top-level-node-validation) doesn't seem to be working or the documentation is missing to explain how to activate it.

A simple ASP.NET Core 3.1 Web API with a Controller mark with the ApiController attribute doesn't enforce the validation rules directly written next to the parameter name.

```
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet]
    public IActionResult GetSomething([Required]string someValue) 
    {
        // not passing someValue doesn't return Bad Request. The method just runs with someValue = null.
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#top-level-node-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The doc is on ASP.NET Core controllers and views, not web APIs

**Comment by eparizzi** [comment]
Isn't Core MVC and Web API almost the same thing in ASP.NET Core 3? If not,
then this should be clarify because I'm testing this in a project that uses
.AddMvcCore() but the controllers inherit from  BaseController instead of
Controller. So what's the real requirement for this to work? Does it only
work for controllers inheriting from Controller?

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#prevent-over-posting and

**Comment by eparizzi** [comment]
Not sure what I'm supposed to see on those links.

The first one just shows the use of a DTO in a Web API controller. But there's no mention of any ModelState.IsValid or anything.

From the second link, I guess the issue here is that model binding is not happening in this case, just formatters from [FromBody], [FromQuery] and such.

So, I guess my question is... can we use Model Binding in ASP.NET Core 3 ApiControllers? If so, how?

**Comment by eparizzi** [comment]
**For future reference**

In order for this to work you need to use `services.AddDataAnnotations()` if you're using `services.AddMvcCore()`.

It's already included when using any of the following:
```
services.AddMvc()
services.AddControllers()
services.AddControllersWithViews()
services.AddRazorPages()
```

**Comment by Rick-Anderson** [comment]
@eparizzi thanks for the follow up. That's looks like it should be added.
