### ISSUE TITLE
Inaccuracies in the article aspnet/core/mvc/controllers/routing

### ISSUE THREAD

**Issue by StasD** [dotnet/AspNetCore.Docs#18430]
[EDIT by guardrex to add the metadata. @StasD, please use the **This page** feedback button+form at the bottom of the topic to open a new issue. It will add metadata for tracking and ping the doc author automatically.]

This article https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1 doesn't seem to be accurate on a number of issues. It makes a clear distinction between 'conventional routing' and 'attribute routing', and implies that one has to call `endpoints.MapControllerRoute(...);` to enable 'conventional routing', and call `endpoints.MapControllers();` for 'attribute routing'. But asp.net app created with 'react' template (`dotnet new react`) has just `endpoints.MapControllerRoute(...);` call in `Startup.cs` file, yet attribute routing (in the included `WeatherForecastController.cs` controller, as well as my own controllers) works perfectly fine. So perhaps the documentation is not accurate.
Also, it says `With attribute routing, the controller name and action names play no role in which action is matched.` yet a couple of paragraphs below you can see an example of just the opposite behaviour: `[Route("[controller]/[action]")]`...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-au/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@StasD 

> implies that one has to call `endpoints.MapControllerRoute(...);` to enable 'conventional routing', and call `endpoints.MapControllers();` for 'attribute routing'. 

Where does it do that?

**Comment by StasD** [comment]
> Where does it do that?

The box with blue background, right before the "Conventional routing" paragraph, which says:
```
Important

Routing is configured using the UseRouting and UseEndpoints middleware. To use controllers:

Call MapControllers inside UseEndpoints to map attribute routed controllers.
Call MapControllerRoute or MapAreaControllerRoute, to map conventionally routed controllers.
```
In reality, it seems that MapControllerRoute would map attribute routed controllers as well.

P.S.: In my 'react' project I actually replaced the MapControllerRoute call by combination of `MapControllers(); ` and `MapRazorPages();` calls. Not because "attribute routing" didn't work, but because it makes more sense for this kind of project. The template provides the "Error" page, which is a Razor page, and it doesn't work unless I call `AddRazorPages()` and then `MapRazorPages()` in `Startup.cs`. Also, some server-side Razor pages might be useful, in general, even in SPA application.

**Comment by Rick-Anderson** [comment]
@serpent5  it should say

Call `MapControllerRoute `or `MapAreaControllerRoute`, to map conventionally routed controllers ***AND*** attribute routed controllers.
