### ISSUE TITLE
Blazor WASM - Debug In Browser - Suggested Clarifications

### ISSUE THREAD

**Issue by snerks** [dotnet/AspNetCore.Docs#18439]
## Debug in the browser

1. Run a Debug build of the app in the Development environment (e.g. Visual Studio Code).

1. Launch a browser and navigate to the app URL, as indicated by the Debug output (e.g. at https://localhost:5001)

1. In the browser, attempt to commence remote debugging, by pressing <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>D</kbd>.

1. For the previous step to succeed, the browser must be running with remote debugging enabled (which is not the case, by default). If remote debugging is disabled, an **Unable to find debuggable browser tab** error page is rendered. **Helpfully, the error page also contains instructions for launching the browser with the debugging port open**, so that the Blazor debugging proxy can connect to the app. ~~*Close all browser instances* and restart~~ Restart the browser as instructed.

Once the browser is running with remote debugging enabled, the debugging keyboard shortcut (<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>D</kbd>) opens a new debugger tab. 

After a moment, the **Sources** tab shows a list of the .NET assemblies in the app (within the **file://** node). 

Expand each assembly and find the *.cs*/*.razor* source files available for debugging. 

Set breakpoints, switch back to the app's tab, and the breakpoints are hit when the code executes. 

After a breakpoint is hit, single-step (<kbd>F10</kbd>) through the code or resume (<kbd>F8</kbd>) code execution normally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @snerks ... I'll take a look at this asap. Probably after another week tho. We have a couple of high priority issues being addressed on the short holiday week next week.

**Comment by snerks** [comment]
Thanks @guardex!

**Comment by rstewartgithubacct** [comment]
Also having all kinds of problems trying to debug the car-checker app with client and server side code in both vs2019 and vs code.  https://channel9.msdn.com/Events/Build/2020/BOD104#comments

**Comment by guardrex** [comment]
@rstewartgithubacct We only handle documentation here. You'll need to open an issue with engineering at ...

https://github.com/dotnet/aspnetcore/issues

... and they'll need full details of the issues that you're facing in the issue that you open with them.
