### ISSUE TITLE
Non-working code sample

### ISSUE THREAD

**Issue by TheBeardedLlama** [dotnet/AspNetCore.Docs#18435]
Hey peeps, the first code sample on this page doesn't quite work.
I'm not 100% sure of the intention, so I'm filing this first and happy to submit a PR to fix, if someone lets me know what was the original intention :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b15fd3-39b5-3ad9-8c4e-b8160360dee9
* Version Independent ID: c33981af-93ce-d4be-a265-5d4696666c7a
* Content: [Request and Response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.1&source=docs#feedback)
* Content Source: [aspnetcore/fundamentals/middleware/request-response.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/request-response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by jkotalik** [comment]
So the first example should work, but is used more to demonstrate the issues of not using a pipe to read the request body. 

What exception or incorrect behavior are you observing?

**Comment by TheBeardedLlama** [comment]
I appreciate that, however the sample is not working. 
The obvious thing is that the loop breaks before the stream is read. There are other issues too.
To be fair I haven't fully checked the other samples so they might not be working either.

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama  The sample doesn't compile with ASP.NET Core 3.1. How did you fix the 	
Error	CS1501	No overload for method 'UseRouting' takes 1 arguments	RequestResponseSample	C:\tmp\0\RequestResponseSample\Startup.cs	30	N/A

```
pp.UseRouting(routes =>   // No overload for method 'UseRouting' takes 1 arguments	
{
    routes.MapPost("/Streams", async context =>
    {
        var list = await GetListOfStringsFromStream(context.Request.Body);

        foreach (var item in list)
        {
            await context.Response.WriteAsync(item.ToUpperInvariant());
            await context.Response.WriteAsync(Environment.NewLine);
        }
    });
```

**Comment by TheBeardedLlama** [comment]
Hey @Rick-Anderson 
I'm on 2.1 for my current project (don't ask...), so unfortunately, I can't help with that question.
Apologies. I can do some digging outside of work if you like. Happy to help

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama  that explains it. The sample project is using 3.0, which I upgraded to 3.1.

@jkotalik  I can make a 3.1 version of this for you if you can supply the 3.1 code for `app.UseRouting(routes =>   // No overload for method 'UseRouting' takes 1 arguments	`

**Comment by TheBeardedLlama** [comment]
The sample I'm referring to is the first one on that page.
Cursory glance at the loop and you will see what I mean.
 
my offer to help stands

**Comment by Rick-Anderson** [comment]
@TheBeardedLlama  any chance you could install 3.1 and look at https://github.com/dotnet/AspNetCore.Docs/pull/18557 ? Can you suggest how I can test? Postman only works with the first snippet.

@jkotalik  can you review #18557

**Comment by TheBeardedLlama** [comment]
apologies @Rick-Anderson I got distracted!

I will have a look this evening (UK time)

**Comment by Amestdian** [comment]
ASPNETCore 2.1, in the controller's  

Method:
public async Task<IActionResult> UploadPhysical() 

I get the following error at  

Line of code:
await targetStream.WriteAsync(streamedFileContent);

Error:
Error	CS1501	No overload for method 'WriteAsync' takes 1 arguments

**Comment by jkotalik** [comment]
@Amestdian some of these features weren't added until 3.1. The article is targeted for 3.1 and above, and isn't relevant until 3.1.
