### ISSUE TITLE
Visual Studio Debugging

### ISSUE THREAD

**Issue by TPJ11** [dotnet/AspNetCore.Docs#18434]
Add the follow to the guide on debugging with VS - To debug using VS you need to enable "Enable JavaScript debugging for ASP.NET (Chrome, Edge and IE)" setting within Options -&gt; Debugging -&gt; General

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @TPJ11 ... That's the default, but I think it's a good idea to mention it as such. I'll mark this for triage to see if Artak agrees.
