### ISSUE TITLE
[RC1] Provide steps for using Blazor WebAssembly based components from views and pages

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#18431]
Currently the Integrate components topic shows how to integrate components in views and pages using Blazor Server, but it doesn't show how to do the same thing with Blazor WebAssembly. You need to use the Blazor WebAssembly script and then the appropriate CSS selector to place your root components (you can't use the component tag helper unfortunately).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcac856a-7cdc-41fb-b7ea-7c5583916019
* Version Independent ID: b6f9f287-407a-6036-10b0-4bc13cfade17
* Content: [Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/integrate-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/integrate-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 @mkArtakMSFT I think this issue is referring to a **_Hosted_** WASM app, correct? Otherwise, the whole issue (i.e., for a standalone WASM app) doesn't make sense.

> appropriate CSS selector to place your root components

I probably need a little more info on that ... can you shoot a quick example in here?

**Comment by danroth27** [comment]
>  I think this issue is referring to a Hosted WASM app, correct? Otherwise, the whole issue (i.e., for a standalone WASM app) doesn't make sense.

Correct, you can't have views and pages without a host ASP.NET Core app.

> I probably need a little more info on that ... can you shoot a quick example in here?

Sure, in Blazor WebAssembly you add root components in *Program.cs* and then supply a CSS selector about where you want that component to be rendered. Something like this:

```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<Counter>("my-counter"); 
        await builder.Build().RunAsync();
    }
}
```

You then mark in your view or page where you want the component to appear accordingly:

```html
<my-counter>Loading...</my-counter>
```

**Comment by guardrex** [comment]
@danroth27 Those instructions don't seem complete.

### Content draft thus far

1. In the *Server app's* layout file (*_Layout.cshtml*):

   * Add the following `<base>` tag to the `<head>` element:

     ```html
     <base href="~/" />
     ```

     The `href` value (the *app base path*) in the preceding example assumes that the app resides at the root URL path (`/`). If the app is a sub-application, follow the guidance in the *App base path* section of the <xref:host-and-deploy/blazor/index#app-base-path> article.

     The *_Layout.cshtml* file is located in the *Pages/Shared* folder in a Razor Pages app or *Views/Shared* folder in an MVC app.

   * Add a `<script>` tag for the *blazor.webassembly.js* script immediately before the closing `</body>` tag:

     ```html
     <script src="_framework/blazor.webassembly.js"></script>
     ```

     The framework adds the *blazor.webassembly.js* script to the *Server app*. There's no need to manually add the script to the app.

1. In the *Client app*, add root components in `Program.Main` (*Program.cs*). In the following example, the `Counter` component is added as a root component:

   ```csharp
   using {CLIENT APP ASSEMBLY}.Client.Pages;
   
   ...
   
   builder.RootComponents.Add<Counter>("my-counter");
   ```
   
1. In a page or view of the *Server app*, place a CSS selector where you want a component to appear. In the following example, the CSS selector for the `Counter` component is placed in a page:

   ```cshtml
   <my-counter>Loading...</my-counter>
   ```

### Errors are thrown 💥 ...

In the *Client app* (`Index` component) ...

> ﻿Microsoft.JSInterop.JSException: Could not find any element matching selector 'my-counter'.

In the *Server app* when I navigate to the page that has the CSS selector ...

> Microsoft.JSInterop.JSException: Could not find any element matching selector 'app'.

I tried a couple of things and searched for community posts, but no 🎲🎲.

Two more ❓ ...

* In the *Server app*, I see a *css/app.css* stylesheet. Is that the same one that the hosted WASM app uses? Because if that's a set of RP styles, then isn't the component going to render with the wrong stylesheet?
* WRT the term "CSS selector," I'm not familiar with the term being used in this context, as an element tag in markup for rendering. The setup looks like a Tag Helper or some kind of named component syntax unique to Blazor. We don't have a doc in our doc set that names "CSS selector" anywhere, and this doesn't seem to be an HTML spec.

**Comment by danroth27** [comment]
I think the problem is that by adding the blazor.webassembly.js script in the layout, it gets added to every page whether it contains the `my-counter` tag or not. I think you need to instead only add the script to the page that has the tag.

You're correct that if your component has specific styles associated with it, then you'll need to link those in too on the view/page.

The CSS selector is just like a normal selector that you would have in a .css file. It's used to indicate where you want the root component to be rendered. For example, you could change `<my-counter>` to `<div id="counter">` and then specify the location of the counter root component using `#counter`.

**Comment by guardrex** [comment]
I placed the script tag into the page where the CSS selector appears, but it :boom: on me again ...

`Index` component ...

> ﻿Microsoft.JSInterop.JSException: Could not find any element matching selector 'my-counter'.
blazor.webassembly.js:1:37761


Razor page ...

> ﻿Microsoft.JSInterop.JSException: Could not find any element matching selector 'app'.

This is a template-based Hosted WASM app. The only things I did to it I showed in the draft text earlier.

The *Client* app has ...

```csharp
public class Program
{
    public static async Task Main(string[] args)
    {
        var builder = WebAssemblyHostBuilder.CreateDefault(args);
        builder.RootComponents.Add<App>("app");

        builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

        builder.RootComponents.Add<Counter>("my-counter");

        await builder.Build().RunAsync();
    }
}
```

The page that I created in the *Server* app ...


```cshtml
@page "/TestMe"
@model HostedTestDELETEME.Server.Pages.TestMeModel
@{
    ViewData["Title"] = "TestMe";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>TestMe</h1>

<p>Counter component here</p>

<my-counter>Loading...</my-counter>

<p>That was the Counter component</p>

<script src="_framework/blazor.webassembly.js"></script>
```

The routing seems bug-ish, too. Sometimes when I run the *Server* app the client-side router takes over and says that the page (the endpoint for the Razor page that I created in the *Server* app's *Pages* folder) doesn't exist. The request never reaches the *Server* app to be processed by the endpoint router in the *Server* app.

Do you have a working solution that you could show me?

**Comment by danroth27** [comment]
Here's a simple sample: https://github.com/danroth27/RazorPageWithBlazorWebAssembly.

This approach, however, does have limitations. It doesn't really scale up to multiple components on different pages, because we throw if the CSS selector for a root component doesn't match anything on a given page with the Blazor WebAssembly script. Given these limitations I think we should hold off on documenting this for now.

**Comment by ChrisBertrand** [comment]
I am following this to add a root component to the page which is displaying correctly. However, no parameters that are passed into this from the views is being read correctly. Is this not possible on rootcomponents?

**Comment by danroth27** [comment]
Hi @ChrisBertrand.  There isn't a built-in way right now to flow parameters from the view/page to the component when it is rendered client-side in the browser. You'd have to somehow serialize the parameters into the rendered page and then pick them up in your component implementation.
