### ISSUE TITLE
A PWA does not need to be a SPA and question

### ISSUE THREAD

**Issue by Ponant** [dotnet/AspNetCore.Docs#18436]
[EDIT by guardrex to add the metadata. @Ponant, please use the **This page** feedback button and form at the bottom of a topic to open a new issue. It automatically adds the metadata and automatically pings the author of the topic.]

The docs says a PWA is a SPA, but that is not true in my opinion.

https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio

Can we use Razor Pages and turn the resulting website into a PWA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8c235e-1ce4-046f-e848-294096361922
* Version Independent ID: 6240f626-97d4-ace0-5e34-20e1c3592f86
* Content: [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/progressive-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@SteveSandersonMS

**Comment by guardrex** [comment]
Ping @SteveSandersonMS ... the comment pertains to a line that you provided for this doc.

**Comment by SteveSandersonMS** [comment]
PWAs are usually SPAs, but I agree you could make a case that some non-SPA sites make sensible PWAs too. It's a pretty minor distinction so I don't mind too much exactly how this is phrased :)
