### ISSUE TITLE
Document using logging config from existing configuration object

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#18444]
The current logging docs in Blazor show how you can add logging config using an in-memory property or the `ILoggingBuild` API methods.

We don't showcase how you can read the logging config included in your appsettings.json file.

To do this, the user needs to invoke `builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"))` in their startup logic.

More context at https://github.com/dotnet/aspnetcore/issues/20969.

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-logs-in-blazor
