### ISSUE TITLE
Doc for launchsetting.json

### ISSUE THREAD

**Issue by cecilphillip** [dotnet/AspNetCore.Docs#18447]
Apologies if this exists somewhere, but I was unable to find it.

I think there should be a document to the `launchsettings.json` file that gets generated in the templates and details on how it's configuration settings relate to debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 967496ea-59b6-1f17-4f39-1e4c232126c6
* Version Independent ID: 09bb2010-fe5c-1061-23ec-a0dcc92bdd3f
* Content: [Troubleshoot and debug ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cecilphillip ... It's in the *Environments* topic at ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#development-and-launchsettingsjson
