### ISSUE TITLE
Create detailed documentation for adding additional client access to ServerAPI resources.

### ISSUE THREAD

**Issue by bdfin** [dotnet/AspNetCore.Docs#18454]
It would be great to get some clear instructions on how to add additional clients to access the Blazor WebAssembly .NET Core hosted server-side API endpoints using the new `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` package.

After not finding any information I was able to implement the following:

```
services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
                {
                    options.Clients.Add(new IdentityServer4.Models.Client
                    {
                        ClientId = "web_id",
                        ClientSecrets = { new Secret("web_id".ToSha256()) },
                        AllowedGrantTypes = GrantTypes.ClientCredentials,
                        AllowedScopes = { "WebAssemblyTest.ServerAPI" }

                    });
                });
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@javiercn can you suggest a good pattern to use here? Do you think the one @bdfin came up with a good one?

**Comment by guardrex** [comment]
I don't think this quite fits our coverage any longer, given that we're focusing coverage on Duende Identity Server now. Also, this ask seems to be more in the vein of how to configure any ASP.NET Core app to access an ASP.NET Core web API, which is all that the **`Server`** app is of a hosted WASM solution is in this use case. It's not really specific to Blazor apps AFAICT. @bdfin, thanks for your request. We'll continue to take feedback in this area.
