### ISSUE TITLE
The following code applies [Route("[controller]/[action]")] to the controller

### ISSUE THREAD

**Issue by JCPuerto** [dotnet/AspNetCore.Docs#18451]
There's a line in the page where it says 

> The following code applies [Route("[controller]/[action]")] to the controller

But then the code shown is a basic controller which will not work since there are not attributes whatsoever.

![image](https://user-images.githubusercontent.com/10167695/82730389-2c14a280-9ccd-11ea-8ab4-97dc6350c7c6.png)

Was the idea to put the `[Route("[controller]/[action]")]` as an attribute of the controller I guess?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It must be assuming the default route set up by the templates
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Home/Error");
        app.UseHsts();
    }
    app.UseHttpsRedirection();
    app.UseStaticFiles();

    app.UseRouting();

    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllerRoute(
            name: "default",
            pattern: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

**Comment by Rick-Anderson** [comment]
@serpent5  do you remember what we were thinking?

**Comment by serpent5** [comment]
It looks like it should be referencing [this snippet](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing/samples/3.x/main/Controllers/HomeController.cs#L79). There's two in there called `snippet24` and it should be that first one, instead of the one that follows.

**Comment by serpent5** [comment]
Shall I fix this?

**Comment by Rick-Anderson** [comment]
Yes please.

**Comment by Rick-Anderson** [comment]
@serpent5  I think I did a PR that changed it so you might want to get rid of that change.
