### ISSUE TITLE
builder.Logging.AddConfiguration does not compile

### ISSUE THREAD

**Issue by emiliovmq** [dotnet/AspNetCore.Docs#18450]
Hi blazor-team, 

According to the documentation (https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#logging-configuration) for blazor-wasm,  having the configuration below

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```
and calling 
```
builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"));
```
should make possible to set up the logging mechanism with minimum levels, filters, and so on...

However, the compiler says "_'ILoggingBuilder' does not contain a definition for 'AddConfiguration' and the best extension method overload ...._'

Do I have to use a specific package? This is how my code looks like:

```C#
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace OneSpaWorld.Olympus.Manager
{
    public class Program
    {
       public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            // ERROR here
            builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"));

            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            builder.Services.AddOidcAuthentication(options =>
            {
                // Configure your authentication provider options here.
                // For more information, see https://aka.ms/blazor-standalone-auth
                builder.Configuration.Bind("OpenIdConnect", options.ProviderOptions);
            });

            await builder.Build().RunAsync();
        }
    }
}
```
and these are the packages used

```C#
<ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.4" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.0" />
  </ItemGroup>
```
Am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a015ab57-3e5c-f5c8-338c-d491c3e9e3fb
* Version Independent ID: 951c8cfc-6aae-2e15-a085-66071d80f6a4
* Content: [ASP.NET Core Blazor hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-model-configuration?view=aspnetcore-3.1#configuration)
* Content Source: [aspnetcore/blazor/hosting-model-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-model-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Add ...

```xml
<PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="3.1.4" />
```

... and use namespace ...

```csharp
using Microsoft.Extensions.Logging;
```

We'll get it covered when I work the docs issue shortly on https://github.com/dotnet/AspNetCore.Docs/issues/18444.
