### ISSUE TITLE
No mention of dependencies needed to use library

### ISSUE THREAD

**Issue by mowoolli** [dotnet/AspNetCore.Docs#18456]
In the second code snippet, I was unable to use `Microsoft.EntityFrameworkCore` before getting the following package:

`dotnet add package Microsoft.EntityFrameworkCore.SqlServer`

I also saw it was recommended to get:

`dotnet add package Microsoft.EntityFrameworkCore.Tools`

I did not see these requirements mentioned before the code snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there

**Comment by mowoolli** [comment]
I now see it in the PDF, but my Chrome browser loads an out-dated version of the documentation (from 01/13/2020) which does not have that information. Not sure why that's happening. Apologies for the false alarm.
