### ISSUE TITLE
Doc and code in the ASP.NET 4x + Core section is incomplete/non-functional

### ISSUE THREAD

**Issue by ransagy** [dotnet/AspNetCore.Docs#18460]
As it currently stands, If you follow the section on how to share auth cookies between ASP.NET Core and 4.x (OWIN) apps, You'll come across the issue of conflicting SessionId claim names (as described at https://stackoverflow.com/questions/48510143/adding-a-sessionstore-iticketstore-to-my-application-cookie-makes-my-data-prot ) and there is no guidance or code to address the situation.

Have i misunderstood something here or does this problem remain unsolved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-3.1#share-authentication-cookies-without-aspnet-core-identity)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
