### ISSUE TITLE
Details about reconfiguring existing API resources and clients

### ISSUE THREAD

**Issue by kuritsu** [dotnet/AspNetCore.Docs#18465]
It would be very helpful to include information about how to reconfigure from code the existing clients and/or resources (or at least include links to point to that information). For example, I wasn't sure how to include a `role` claim when requesting the user information, from both the API and the SPA. I had to do the following:

First, enable the roles.

```
public virtual void ConfigureServices(IServiceCollection services) {
...
  services.AddDefaultIdentity<ApplicationUser>()
                .AddRoles<IdentityRole>()
...
```
Then, we'll need to tell the API to return the role claim that gets injected after enabling the roles.

```
  services.AddIdentityServer()
     .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
                {
                    var apiScope = options.ApiResources["RestApi"].Scopes.FirstOrDefault(s => s.Name == "RestApi");
                    apiScope.UserClaims.Add(JwtClaimTypes.Role);
....
```
Now, the SPA client is another story. It gets configured differently, as it requires some extra options enabled (the following code is the continuation of the previous code).
```
                    var client = options.Clients["spa"];
                    client.AllowOfflineAccess = true;
                    client.AllowAccessTokensViaBrowser = true;
                    client.AlwaysSendClientClaims = true;
                    client.AlwaysIncludeUserClaimsInIdToken = true;
  })
  .AddProfileService<SpaProfileService>();
```
And we also need, at least for the SPA client, to define a Profile (SpaProfileService) so it can return the role claims when requesting the user info (oddly that's not needed for the API resource).

The code I used for implementing SpaProfileService is the following:

```
using AuthServer.Models;
using IdentityModel;
using IdentityServer4.Models;
using IdentityServer4.Services;
using Microsoft.AspNetCore.Identity;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AuthServer
{
    public class SpaProfileService : IProfileService
    {
        protected readonly UserManager<ApplicationUser> userManager;

        public SpaProfileService(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var user = await userManager.GetUserAsync(context.Subject);
            var roles = await userManager.GetRolesAsync(user);

            var roleClaims = new List<Claim>();
            foreach (var role in roles)
                roleClaims.Add(new Claim(JwtClaimTypes.Role, role));

            roleClaims.Add(new Claim(JwtClaimTypes.Name, user.UserName));
            context.IssuedClaims.AddRange(roleClaims);
        }

        public Task IsActiveAsync(IsActiveContext context)
        {
            return Task.CompletedTask;
        }
    }
}
```

Anyway, these pieces were gathered exhaustively searching in StackOverflow, GitHub issues, source code of the IdentityServer and other projects, and it is not clear at all, neither in your documentation nor IdentityServer's, but I strongly believe it will help the developers a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406
