### ISSUE TITLE
Sample apps for Client and Server seem to be identical Client projects

### ISSUE THREAD

**Issue by BryanFitzpatrick** [dotnet/AspNetCore.Docs#18463]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BryanFitzpatrick ... I don't follow ... please be more specific.

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/18469.

No need to open a new issue @BryanFitzpatrick ... just comment on an existing issue.
