### ISSUE TITLE
Need example of programmatically calling EventCallback

### ISSUE THREAD

**Issue by ndc** [dotnet/AspNetCore.Docs#18461]
Since the way to programmatically trigger EventCallback is not so obvious (at least for me), I think it is worth adding an example on how to do it.

My 2c:

```
<select @onchange="SelectChanged">
...
</select>

@code {
    [Parameter]
    public EventCallback<string> ValueChanged { get; set; }

    private async Task SelectChanged(ChangeEventArgs args)
    {
        await ValueChanged.InvokeAsync("custom value");
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Artak, this would be a violation of our guideline (at least in that form) on not building components that write to their own parameters. I'm :ear: for another common scenario, but I should be able to come up with something similar tho that doesn't violate that guidance.

**Comment by guardrex** [comment]
Turns out that we already cover this at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1#eventcallback

... but I don't like the syntax of that example. I'll touch that up using this issue.
