### ISSUE TITLE
Web API test error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18475]
The comments below were machine-translated

@spring-rool commented on [Sat May 23 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/271)

Navigating https: // localhost: 44337 / api / books / {id 5ec79ace9be07f5cca5c1a78} shows that the webpage of localhost cannot be found

     --- Solved: https: // localhost: 44337 / api / books / 5ec79ace9be07f5cca5c1a78

#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [使用 ASP.NET Core 和 MongoDB 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

---

@srvbpigh commented on [Sat May 23 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/271#issuecomment-633062177)

Hello, @spring-rool
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
