### ISSUE TITLE
anti forgery tokens

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#18471]
Are there any blazow web assembly samples on implementing anti forgery tokens like this one?

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1#javascript-ajax-and-spas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hoksource ... Not in the official docs for Blazor. For a Blazor Server app, you can generate a token and pass it to components in the Blazor app, and I show that on an open PR that submits a form (a POST request that requires a token) for an Identity-based signout endpoint ...

https://github.com/dotnet/AspNetCore.Docs/pull/17940/files#diff-c84ac8de444898b748860f452e19412bR180

... which is based on ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/additional-scenarios?view=aspnetcore-3.1#pass-tokens-to-a-blazor-server-app

We don't have any further coverage at the moment. I'll leave this on the Blazor.Docs project for Artak to see. If we do cover anything else, we'd need to figure out **_what to cover_**. Let's **not** leave this open if we don't know what to cover right now. Blazor.Docs has a crazy number of open issues right now, and I'd rather not leave very low priority, unactionable issues lying around ... not good for my morale trying to dig out of a backlog. 🏃😅 It's going to take me one to two months just to catch up as it is.

**Comment by hoksource** [comment]
thank you for the quick response. will try doing experiment and will wait for the best option when it is ready. :) have a great day, stay kickin

**Comment by hoksource** [comment]
I'll close this for now. will check again in the near future. :)
