### ISSUE TITLE
auto compile client wasm on self hosted app

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#18472]
Good day,
I created a template with

`dotnet new blazorwasm --hosted`

is it possible to have auto recompiling on the client side?

`dotnet watch run`

does not seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
See :point_right: https://github.com/dotnet/aspnetcore/issues/5456

**Comment by hoksource** [comment]
Thanks, sorry was not able to check.
