### ISSUE TITLE
Web API testing

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18476]
The comments below were machine-translated

@spring-rool commented on [Sat May 23 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/272)

How to test the create update delete operation method of the controller

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [使用 ASP.NET Core 和 MongoDB 创建 Web API](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

---

@srvbpigh commented on [Sat May 23 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/272#issuecomment-633072288)

Hello, @spring-rool
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
Hi @spring-rool 
Your question is beyond the scope of this document. There is some testing information in https://docs.microsoft.com/aspnet/core/test/integration-tests
