### ISSUE TITLE
Sample does not work

### ISSUE THREAD

**Issue by rverschuur** [dotnet/AspNetCore.Docs#18487]
The sample that shows how to use Views from a separate assembly, as described in this page and located on https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/advanced/app-parts/3.0sample1/WebAppParts does not work.

The Controller in a separate assembly does work. But the view gives the error as attached. I tried to get it to work, but I didn't succeed. Does the feature to load views from an other assembly, still works?

![image](https://user-images.githubusercontent.com/23360938/82916832-d82ae780-9f72-11ea-9ebd-0d0da4cca5f9.png)

```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/MyShared/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
```

Kind regards,

Robin Verschuur
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Share controllers, views, Razor Pages and more with Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article
Use a Razor class library to include views in the assembly.

**Comment by rverschuur** [comment]
Hi Rick,

Thank you for your response. I use a Razor Class Library, it is provided by the same sample. I noticed I linked a directory to deep when linking to the Github repository in my previous post.

The article contains 3 samples. Located here: https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/advanced/app-parts/

The 3.0Sample1, which contains both the web-project and the Razor Class Library, doesn't work. Try it. The link that opens a controller from a separate assembly works, but the link that opens a View from the separate assembly does not work.

Kind regards,

Robin

**Comment by ronnyek** [comment]
I just ran into this very issue... And while I agree the documentation does state RCL need to be used, the link that talks about RCL, makes only brief mention of views. Creating a new RCL project to house my controllers and views seems to be very specifically setup for razor pages or something (not sure if I should just be able to make a controllers folder and a views folder mirroring typical mvc structure.

Very confusing to say the least.

**Comment by ronnyek** [comment]
> The 3.0Sample1, which contains both the web-project and the Razor Class Library, doesn't work. Try it. The link that opens a controller from a separate assembly works, but the link that opens a View from the separate assembly does not work.

I'm actually not sure this example uses razor class library at all. Looking at the .csproj its not setup as
`<Project Sdk="Microsoft.NET.Sdk.Razor">`

I just want controllers and views in an external application part... and even trying to create a RCL to house those things, I'm totally totally lost. Seems like documentation for RCL outlines about every scenario but this, and the default template for RCL creates a bunch of what I assume is razor page stuff.
