### ISSUE TITLE
How does bind-{ATTRIBUTE} and bind-{ATTRIBUTE}:event exactly work?

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/AspNetCore.Docs#18482]
In the example about: `@bind-style="paragraphStyle" @bind-style:event="onchange"`

How does that `@bind-style:event="onchange"` exactly work?
I could literally just put in `onload` as the value and it would still work.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/da-dk/aspnet/core/blazor/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Assassinbeast ... We don't document that level of detail. You can research how anything works in the engineering repo reference source ...

https://github.com/dotnet/aspnetcore/issues
