### ISSUE TITLE
ValidationSummary across multiple forms.

### ISSUE THREAD

**Issue by carlblanchard** [dotnet/AspNetCore.Docs#18481]
Does the ValidationSummary control support multiple forms on a page? 
Regards

**Comment by guardrex** [comment]
Hello @carlblanchard ... please use the **This page** feedback button+form at the bottom of a topic to open an issue.

**Comment by carlblanchard** [comment]
Hmm, that would be amazing if it was true... I get the following error. 
Unhandled exception rendering component: EditForm requires a Model parameter, or an EditContext parameter, but not both

The structure of my HTML is 
```
<section class="section">
            <EditForm>
                <ValidationSummary />
            </EditForm>
            <div class="row">
.... more HTML

 <EditForm Model="@UserPreferences" OnValidSubmit="LanguageSettingOnValidSubmit">
.... more form contents
</EditForm>

.... more HTML
<EditForm Model="@UserPreferences" OnValidSubmit="TimezoneOnValidSubmit">
.... more form contents
</EditForm>
```

**Comment by guardrex** [comment]
Oh, yes. I forgot that the `ValidationSummary` component must be in the form. I just got up and no ☕ yet.

Open a suggestion for this as a feature with the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by carlblanchard** [comment]
Done, Thanks Luke and Enjoy your morning coffee... I am already at least 15 down lol
