### ISSUE TITLE
Standalone deployment with Azure Storage: problems with mime types and compression

### ISSUE THREAD

**Issue by daviddejaeger** [dotnet/AspNetCore.Docs#18483]
Hi,

When deploying my Blazor WebAssembly app on Azure Storage a lot of mime types are not correct. For example I had to change the dotnet.wasm to 'application/wasm' to get it working. also for the .js files I also had to change the mime type to 'application/javascript'. 

Additionally nothing was compressed because the content encoding was also missing on the dll files so my application was huge. I changed it by hand the first time which was very cumbersome and later I found a script.

This issue is nowhere mentioned in the documentation. I don't know if this should be mentioned here or in the 'Static website hosting in Azure Storage' Docs but I think this should be mentioned somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @daviddejaeger ... I'll need to look :eyes: to see if I can repro a regression in the guidance. It *used to work* OOB the way that their topic describes with the guidance that we have. I should be free later this afternoon. I'll try to get back to you later today.

**Comment by daviddejaeger** [comment]
Hi,

I followed this: For more information, see [Static website hosting in Azure Storage.](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)

And there it says under the section 'Setting up a static website': For step-by-step guidance, see [Host a static website in Azure Storage.](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-portal)

So i followed that guidance: I used the 'Azure Storage Explorer' to copy the files, I don't know if this issue is the same for the other options (Storage Explorer (preview), AzCopy, Powershell) but I think so because there is a already a note there regarding html files:

"Storage Explorer automatically sets this property to text/html for commonly recognized extensions such as .html. However, in some cases, you'll have to set this yourself. If you don't set this property to text/html, the browser will prompt users to download the file instead of rendering the contents. To set this property, right-click the file, and then click Properties."

Let me know if you need more information.

**Comment by guardrex** [comment]
That might the problem. IIRC, I used CloudBerry for my file transfer, and it may have been a little smarter about assigning the MIME types. What we might need to do is call this out in the topic. I'll need to investigate further. I'll get back to you.

**Comment by guardrex** [comment]
I was bogged down yesterday, but I can look at this now.

**Comment by guardrex** [comment]
Yes, we need a NOTE here. I only had to change one in my retest of this scenario for the weather data file (JSON) because a default site will load compressed resources by default. WRT the weather data file, my Cloudberry sent it as `application/octet-stream`, which failed on load. Changing it to `application/json` put things back into good order.

We should cover the non-compressed case, too. I'll note the correct Content Types for the framework files.

Thanks for calling this out, @daviddejaeger! :rocket:
