### ISSUE TITLE
Temporary debugging state for hosted wasm under visual studio code

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#18490]
I'll just temporary leave and close this for those in need.

1. For debugging the blazor wasm client in vs code, the below statement simply means
a.)  after you start the blazor stand alone server
b.)  you should go to the debug tab choose the launch option ".NET Core Debug Blazor Web Assembly in Chrome" (dropdown above) then run 

> 2. After the app has started, start the browser using the .NET Core Debug Blazor Web Assembly in Chrome launch configuration (requires Chrome). To use Edge instead of Chrome, change the type of the launch configuration in .vscode/launch.json from pwa-chrome to pwa-msedge.

2. To make auto compile/build of the blazor wasm app. You can add the below to the .Server.csproj

```
  <ItemGroup>
    <Watch Include="..\Client\**\*.razor" Exclude="obj\**\*;bin\**\*" />
  </ItemGroup>

```
Then start the server app using dotnet watch run. This will recompile the entire project when the razor files has been changed

3. The auto generated .vscode/launch.json by vs code will generate a configuration that does not load debug symbols for the server app.

`
            "program": "dotnet",
            "args": ["run"],
`

You can temporary fix this by changing it to

`
            "args" : [],
            "program": "${workspaceFolder}/Server/bin/Debug/netcoreapp3.1/MyWasm.Server.dll",
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`watch` is covered by a few engineering issues ...

* https://github.com/dotnet/aspnetcore/issues/22219
* https://github.com/dotnet/aspnetcore/issues/5456

Since it's still in design, we'll hold off on documenting anything for it at the moment. Readers can comment on the engineering issues if they have product unit feedback.
