### ISSUE TITLE
how to bind a complex list

### ISSUE THREAD

**Issue by athinboy** [dotnet/AspNetCore.Docs#18499]
Model Binding in ASP.NET Core is complex . I do not know how to  invoke a get/post webapi that contain a complex type collection,
for example:
``` bat
string Add( List<Apple> apples).
```
OR :
```
class Apple{public string Name;}     class Pear {public string Name;}

string Merge( Apple apple,Pear pear  );
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-au/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at [Binding Complex Collections link]{https://www.learnrazorpages.com/razor-pages/model-binding#binding-complex-collections)
cc @serpent5

**Comment by athinboy** [comment]
@Rick-Anderson  Thanks!

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
