### ISSUE TITLE
Attribute binding example doesn't express the case sensitive rule properly.

### ISSUE THREAD

**Issue by send2vinnie** [dotnet/AspNetCore.Docs#18500]
>Attribute binding is case sensitive. For example, `@bind` is valid, and **`@bind`** is invalid.

It looks like the above example itself is not case sensitive...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b1b6ad8-13ba-0195-8829-ade3b1b0b9cb
* Version Independent ID: 6609ea68-a918-f3b9-8c9c-004a4436e350
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @send2vinnie ... I'll patch it up. This was a causality 🤕 of a large find-'n-replace. It should read ...

> Attribute binding is case sensitive. For example, @bind is valid, and @Bind is invalid.
