### ISSUE TITLE
Example doesn't support IHostingStartup

### ISSUE THREAD

**Issue by Levridge-Tory** [dotnet/AspNetCore.Docs#18513]
In the section ["Accessing options during startup"](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#accessing-options-during-startup) it states, "IOptions<TOptions> and IOptionsMonitor<TOptions> can be used in `Startup.Configure`." However this is not true when [using a Hosting Startup Assembly](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.1). This is because you must implement [IHostingStartup](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.ihostingstartup?view=aspnetcore-3.1) which requires a single IWebHostBuilder parameter in Startup.Configure().

I would suggest mentioning this and providing an alternative to access the options in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#accessing-options-during-startup)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[using a Hosting Startup Assembly](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-3.1):

* is not typical of most readers.
* Is an advanced scenario, that advanced users like yourself can figure out.

cc @serpent5, the author, to see if he disagrees.
