### ISSUE TITLE
Blazor webassembly configuration binding update in version 3.2.0

### ISSUE THREAD

**Issue by RedBlue1776** [dotnet/AspNetCore.Docs#18516]
The instructions under Program.cs no longer work in the latest build; the webassembly configuration binding system has been changed significantly 

                builder.Configuration.Bind("AzureAdB2C", options.ProviderOptions.Authentication);

Useful related links:

* https://github.com/dotnet/aspnetcore/issues/20231

* https://github.com/dotnet/aspnetcore/pull/20647

Also: https://stackoverflow.com/q/62052986/12900015
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d682d4c-86b5-c47e-89a3-3684b2235320
* Version Independent ID: a80e115c-466a-288d-a918-9ef7514f5add
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @RedBlue1776.

@captainsafia ... Is the change `options.ProviderOptions.Authentication` to `options` everywhere?

**Comment by guardrex** [comment]
@RedBlue1776 Actually, they do work here as shown in the current topics. **_BUT_** ...

* The OIDC example is bad, so I'm glad you opened this to remind me of that fix. We don't want the a generic OIDC provider example to show Azure AD. We want devs to use the Azure AD topic and MSAL.
* The config example seems to be wrong to me, so I'll fix that, too. I didn't get a chance to test that one scenario. I didn't have a readily available non-Azure, non-Identity Server OIDC provider at the time we were setting up the topics.

If you feel we need to discuss anything further, I can re-open the issue. :ear:
