### ISSUE TITLE
If the command 'code' does not work for you (mac)

### ISSUE THREAD

**Issue by ellenos** [dotnet/AspNetCore.Docs#18511]
The command "code" might not work for you on a Mac because its not in your path.  Recommended to do this:   
    Add this to your ~/.bash_profile, or to ~/.zshrc if you are running MacOS Catalina or later.
        export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie  is this something we should consider adding to https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/includes/net-core-prereqs-vsc-3.1.md ?

I don't think so, because:

* This has never been reported for VSC/Mac users.
* Mac users more typically use VS for Mac
* VSC/Mac users are expected to figure out the setup.

If we add something, it would need to apply to windows/linux/macOS

**Comment by scottaddie** [comment]
@Rick-Anderson Yes, but I think we should only add a link to https://code.visualstudio.com/docs/setup/mac for detailed setup instructions.

**Comment by Rick-Anderson** [comment]
@scottaddie  great idea.

**Comment by Rick-Anderson** [comment]
Add to https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/includes/net-core-prereqs-vsc-3.1.md

The Visual Studio Code instructions use the .NET Core CLI for ASP.NET Core development functions such as project creation. You can follow these instructions on any platform (macOS, Linux, or Windows) and with any code editor. Minor changes may be required if you use something other than Visual Studio Code. ***ADD HERE***. For more information on on installing Visual Studio Code on macOS, see [Visual Studio Code on macOS](https://code.visualstudio.com/docs/setup/mac)

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you can take this. Thanks again @scottaddie  for the right solution.

**Comment by ellenos** [comment]
Great solution, I hoped to save someone time if they ran into this (which this will do)

**Comment by Rick-Anderson** [comment]
@ellenos  thanks for notifying us of this problem. We'll keep the issue open until it's fixed.

**Comment by scottaddie** [comment]
@Rick-Anderson You're welcome. If @serpent5 has the time to fix, that would be great.

**Comment by serpent5** [comment]
I'll get this sorted tonight. I'm working on a couple of bigger issues but this looks quick...
