### ISSUE TITLE
In Blazor, unable to make use of OnLogInSucceeded for post login actions

### ISSUE THREAD

**Issue by mattruma** [dotnet/AspNetCore.Docs#18527]
This is in regards to https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation.

I am trying to respond to a post login event to grab additional profile information.

Looking at the code:

```
<RemoteAuthenticatorViewCore Action="@Action" 
    AuthenticationState="AuthenticationState" OnLoginSucceded="RestoreState" 
    OnLogoutSucceded="RestoreState" />
```

I am not seeing an `OnLoginSucceded` property, but rather a `OnLogInSucceeded`. Is this a misprint? If so, what would the example look like because when I change it to `OnLoginSucceeded` the compiler complains. 

If this is NOT a misprint, what am I failing to understand? :)

Appreciate all the effort of the Docs team!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mattruma ... It's a typo ...

* https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.remoteauthenticatorviewcore-1.onloginsucceeded?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_WebAssembly_Authentication_RemoteAuthenticatorViewCore_1_OnLogInSucceeded
* https://github.com/dotnet/aspnetcore/blob/blazor-wasm/src/Components/WebAssembly/WebAssembly.Authentication/src/RemoteAuthenticatorViewCore.cs#L81

**Comment by mattruma** [comment]
Thanks @guardrex!  

I'll wait for that change to post before my next issue. 🙂

Even when corrected, the example does not work, the compile will now complain about `cannot convert from 'method group' to 'Event Callback'`. 

Probably just a complete solution to see this in action.

**Comment by guardrex** [comment]
Because that example came over from engineering, open that for them at ...

https://github.com/dotnet/aspnetcore/issues

... show them the full error (stack trace) and post a link to that doc section ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation

Please add a `cc: @guardrex` to your opening comment so that I can follow the discussion. I'll open an issue based on what they say.

> I'll wait for that change to post before my next issue.

Yes, give it about ten minutes before opening your issue. I'll update the live site right now.

**Comment by guardrex** [comment]
@mattruma Ok ... the update is on the live docs site now.
