### ISSUE TITLE
Constructor injection behavior

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18522]
[Constructor injection behavior](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#constructor-injection-behavior) 

Should we add a sample, based on [this](https://stackoverflow.com/questions/58222775/how-to-register-dependencies-based-on-the-class-they-are-required-fromusing-bui/58243333#58243333)?

Explain why you would use it.

Probably change H3  from **Constructor injection behavior*** to something better.

cc @serpent5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Maybe call the section something simple like _Inject services_ and cover that:

- The built-in container uses constructor injection. This could even pull the info that's currently in the linked MVC page re what that means and then linked back from there.
- `IServiceProvider` has `GetService`/`GetRequiredService` methods, along with an example of both.
- `ActivatorUtilities` works with `IServiceProvider` for both resolving and providing constructor arguments.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
