### ISSUE TITLE
I don't understand the value proposition of IdentityServer in an SPA scenario

### ISSUE THREAD

**Issue by benrhere** [dotnet/AspNetCore.Docs#18524]
I'm struggling to understand the value that we get by incorporating IdentityServer in an ASP.NET Core SPA application. I have my own ASP.NET Core app running React in the front end. I'm also leveraging Identity Core for authentication and authorization. And just like you describe, I expose APIs that I'll call from the front end via a javascript fetch call. All I had to do was set the credentials to 'same-origin'
https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials

and I believe that by doing that, it will pull the token from cookie storage (as already placed there by the Identity Core template I believe) and I can now hit API endpoints that have the [Authorize] attribute applied. When I remove the 'same-origin' option, I can no longer hit the endpoint, indicating to me that it is indeed locked.

So, can you clarify the value being added here? I can imagine that if you want to serve APIs to a system and you don't want it to have to authenticate via an HTML form, IdentityServer may be able to help you there. But for a SPA, the user will already be logging in and the cookie will be stored and can be included for API calls as I describe.

I think some additional clarity in this document would be helpful.

Thank you...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406

**Comment by benrhere** [comment]
Thank you. If it's helpful, I posted a much more detailed question, along with a code sample here:

https://stackoverflow.com/questions/62122607/asp-net-core-react-template-v3-15-secure-without-identityserver

**Comment by Rick-Anderson** [comment]
@benrhere  thanks for posting that. If you get a good response, post back here. I'll try to get a security resource to review it.

**Comment by benrhere** [comment]
Thanks @Rick-Anderson . No, I hadn't reached out to anyone in particular, but based on your suggestion I added the "IdentityServer4" tag to the post. I'll keep you updated if there's good traction on that thread. Thanks!

**Comment by Rick-Anderson** [comment]
Look at https://github.com/IdentityServer and maybe cross post an issue there and link to here.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Comment by dathoang** [comment]
@benrhere I see you found your answer, could you please share it here ?
IMO, The AspNetCore Spa template is an isomorphic application and will be deploy in a single domain.
I don't see the benefit of using token for authenticating api endpoints because the auth cookie will be sent anyway. 
In the server side, Authorize attribute still work on api controllers without auth tokens being send.
Is that wasteful sending both the cookie and token in every request ?

**Comment by benrhere** [comment]
@dathoang From what I recall, IdentityServer can support some scenarios where you want some additional decoupling of your authentication from your application (you could host auth in a different microservice), or if you want to provide authentication services to multiple applications who don't have a trust relationship between them. In the context of a single SPA, this seems to me like overkill. This post https://stackoverflow.com/questions/42121854/net-core-identity-server-4-authentication-vs-identity-authentication has some thoughts.

Because I have already implemented a solution around ASP.NET Identity Core without IdentityServer, I was trying to understand if there was a compelling need (or advantage) to my updating / converting my code to leverage IdentityServer and I couldn't find one.

Ultimately, it was a bit disconcerting that Microsoft made this pretty large change in their SPA template with no explanation as to why, nor guidance about when to leverage IdentityServer vs  the built-in ASP.NET Identity Core libraries. I speculate that there may be motivation in the long term to rely more on open source and deprecate their own library in this case, but again, since no message has come from Microsoft I don't really know. I'd still appreciate some word from Microsoft as to why they made this change in the SPA template and if they are now discouraging writing auth-enabled ASP.NET Core apps without it.

I don't know for sure about your question regarding sending both a cookie and token in every request.

**Comment by marrrcin** [comment]
I'm also interested to know the reasoning behind this change, especially w.r.t the fact that Identity Server went commercial (https://leastprivilege.com/2020/10/01/the-future-of-identityserver/).

Register / login flow in the current SPA template is really weird:
1. User accounts are managed by ASP.NET Core Identity
2. Login / register UI is routed out of the SPA, which looks weird and feels like a nasty workaround.
3. JWT tokens are provided by IdentityServer 4, which in the default template imposes a hard-dependency on the Entity Framework and the `DbContext` from ASP.NET Core Identity, making it difficult to opt-out from using SQL for user storage.
