### ISSUE TITLE
Static File Authentication

### ISSUE THREAD

**Issue by mjarosch** [dotnet/AspNetCore.Docs#18525]
The sample in the section on Static File Authentication is very simplistic. It would be nice to have a sample that doesn't require creating a route per file. It would also be nice to have a sample for a razor pages site. If I extend the sample to have the route take a file path and use Path.Join code in the sample, do I open myself up for security issues?

There is a sample in the AspNetCore GitHub repo that takes a different implementation approach. It would be nice if the documentation linked to this sample as an alternative implementation, if it is valid. I only stumbled upon it while searching for a solution to a different authorization issue.

***EDIT by @Rick-Anderson***
1. Update [AuthSamples.StaticFilesAuth](https://github.com/dotnet/aspnetcore/tree/main/src/Security/samples/StaticFilesAuth) to .NET 8 or higher.
2. Split into two samples, the _only authenticated users to access static files_ and  u_se an authorization policy to determine who should have access to specific files_
3. Use updated routing, not `app.Map()`
4. As a separate issue, point to the samples in this doc.

Consider putting updated samples in https://github.com/dotnet/AspNetCore.Docs.Samples in a security folder.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 82752](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82752)

**Comment by Rick-Anderson** [comment]
@mjarosch 
> There is a sample in the AspNetCore GitHub repo that takes a different implementation approach. 
Can you provide the link?

**Comment by mjarosch** [comment]
@Rick-Anderson Here is the link: https://github.com/dotnet/aspnetcore/tree/master/src/Security/samples/StaticFilesAuth

**Comment by Rick-Anderson** [comment]
@Tratcher OK if I add this first to the doc and keep the original as an alternate approach for folks who have only a couple static files that need authentication.

**Comment by Tratcher** [comment]
What do you think @blowdart, is that sample sensible guidance? If anything I think it highlights how messy our story is for static file auth.

It would at least need to be split into two samples for clarity.

**Comment by Tratcher** [comment]
> It would be nice to have a sample that doesn't require creating a route per file.

You should be able to use MVC's path pattern matching to limit the redundancy.

**Comment by blowdart** [comment]
Yea it needs splitting and avoidance of app.Map()

**Comment by Rick-Anderson** [comment]
@Tratcher  or @blowdart  can one of you review [this code](https://github.com/fiyazbinhasan/StaticFileAuthorization/blob/main/Program.cs) by @fiyazbinhasan ? If it's good, he can create a PR with his code for this issue.

**Comment by fiyazbinhasan** [comment]
Thanks for the review. I'll make a PR soon!
