### ISSUE TITLE
Possible Typo/Example Will Not Compile

### ISSUE THREAD

**Issue by mattruma** [dotnet/AspNetCore.Docs#18534]
In regards to https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation.

I think there is a typo in:

```
<RemoteAuthenticatorViewCore Action="@Action" 
    AuthenticationState="AuthenticationState" OnLogInSucceeded="RestoreState" 
    OnLogoutSucceded="RestoreState" />
```

The `OnLogoutSucceeded` should be `OnLogOutSucceeded`.

Also, even when this corrected, the example will not compile as the compiler will complain about RestoreState with `Argument 2: cannot convert from 'method group' to EventCallback`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2cdb52c-843f-5944-429d-11ea821c1e22
* Version Independent ID: 9c4f99ef-f070-b527-4efc-96a04798d9ef
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation)
* Content Source: [aspnetcore/security/blazor/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks again @mattruma ... I didn't even look (obviously). I'm 🏃 and spread a little thin these days. I'll patch that right now.
