### ISSUE TITLE
Microsoft.Extensions.Options.DataAnnotations needed for validation example

### ISSUE THREAD

**Issue by stevebelskie** [dotnet/AspNetCore.Docs#18538]
The package Microsoft.Extensions.Options.DataAnnotations is needed for the example shown for validation:

```cs
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddOptions<MyConfigOptions>()
            .Bind(Configuration.GetSection(MyConfigOptions.MyConfig))
            .ValidateDataAnnotations();

        services.AddControllersWithViews();
    }
}
````

While the package is implicitly referenced for an Asp.Net Core project, it isn't in other scenarios where option configuration and validation might be used. It took me a bit to figure out what package was needed when trying to use the `ValidateDataAnnotations` extension method in a worker project. I realize these are the Asp.Net Core docs, but it applies to other host/ project types as well.

I imagine something like the mention for the [Microsoft.Extensions.Options.ConfigurationExtensions](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#optionsconfigurationextensions-nuget-package) package would be appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#optionsconfigurationextensions-nuget-package)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you want this one, otherwise I'll do it next month.
@stevebelskie  thanks for letting us know.

**Comment by serpent5** [comment]
@Rick-Anderson Sure, I'll do this one.
