### ISSUE TITLE
Add a sample for Jwt

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/AspNetCore.Docs#18544]
JSON Web Tokens are fairly popular. I think there should be a sample for them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82950389-524e-0754-a125-addeccbdb1b3
* Version Independent ID: 80b7f7cf-dc2e-137a-5aa7-fa88da63ac80
* Content: [Authentication samples for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. We currently don't have the resources for this request. Should this issue get enough up-votes we'll reconsider.

**Comment by MisinformedDNA** [comment]
I wouldn't say that considering https://github.com/dotnet/dotnet-api-docs/issues/3259.
