### ISSUE TITLE
routing additionalassemblies not sure if working

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#18540]
I created a hosted blazorwasm

created a Test.razor with @page="/test" at Shared/Pages

i added the following in the app.razor
<Router AppAssembly="@typeof(Program).Assembly"
AdditionalAssemblies="new[] { typeof(TestWasm.Shared.WeatherForecast).Assembly }"
>

and tried

<Router AppAssembly="@typeof(Program).Assembly"
AdditionalAssemblies="@(new[] { typeof(TestWasm.Shared.WeatherForecast).Assembly })"
>

I was not able to view /test page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79da574a-570f-04eb-86bd-c8065a016f44
* Version Independent ID: ac771374-6102-b838-57d2-e99bcf3f7d3e
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Did you mean `TestWasm.Shared.Test` instead of `TestWasm.Shared.WeatherForecast`?

If you're hitting an error tho, you should ask engineering directly. I haven't spent any time working with this approach. Open at .....

https://github.com/dotnet/aspnetcore/issues

... and btw ... use triple backticks on lines above and below your code block to get formatting ...

> \`\`\`razor
> 
> ... markup ...
>
> \`\`\`

**Comment by hoksource** [comment]
I tried the following and it gives a compiler error

```
<Router AppAssembly="@typeof(Program).Assembly"
AdditionalAssemblies="new[] { typeof(TestWasm.Shared.Test).Assembly }"
>
```
```

<Router AppAssembly="@typeof(Program).Assembly"
AdditionalAssemblies="new[] { typeof(TestWasm.Shared.Pages.Test).Assembly }"
>

```


 error CS0234: The type or namespace name 'Test' does not exist in the namespace 'TestWasm.Shared' (are you missing an assembly reference?)

**Comment by guardrex** [comment]
It feels like to me that this scenario is for when the component is in another assembly, not the app's own assembly ... like the way Javier says when the component is in a Razor Class Lib.

Like I said, I'm not sure about this scenario. I haven't touched it. I just placed the engineering content into the topic. It's best to ask Javier on the engineering repo and cc: me on the issue. I'll re-open and react to what he says if he provides an actionable doc content change.
