### ISSUE TITLE
Unable to Add Named HttpClient in Blazor WebAssembly App

### ISSUE THREAD

**Issue by mattruma** [dotnet/AspNetCore.Docs#18541]
In regards to https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#typed-httpclient.

I am trying to implement the following code that was provided in the article:

```
builder.Services.AddHttpClient("ServerAPI", client => 
    client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress));
```

The compiler is raising the error `'IServiceCollection' does not contain a definition 'AddHttpClient' ...` ... trying to figure out what I am missing, maybe an `imports`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mattruma ... Do this .......

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#packages

**Comment by guardrex** [comment]
Ooooops!

Do this ..........

```csharp
<PackageReference Include="Microsoft.Extensions.Http" Version="3.1.4" />
```

... I'll update the topic. Thanks for calling this out.
