### ISSUE TITLE
Update PoLocalization sample for 3.x

### ISSUE THREAD

**Issue by hishamco** [dotnet/AspNetCore.Docs#18559]
This is related to #18545, @Rick-Anderson you can assign this to me, after we merge the PR #18556

---
[Associated WorkItem - 63637](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63637)

**Comment by Rick-Anderson** [comment]
@hishamco  should this be updated for .NET 6 or higher?

**Comment by hishamco** [comment]
I will update it soon to target .NET 6.0
