### ISSUE TITLE
Error on Build from Visual Studio for Mac

### ISSUE THREAD

**Issue by alejograjal** [dotnet/AspNetCore.Docs#18569]
Working with visual studio for Mac, I create an ASP.NET Core 3.1 MVC web page!
Once was created I try to build it but I got this error:

> /usr/local/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets(5,5): Error MSB6003: No se pudo ejecutar la tarea ejecutable especificada "dotnet". System.ComponentModel.Win32Exception (0x80004005): ApplicationName='/usr/local/bin/dotnet', CommandLine=' exec "/usr/local/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/../../tools/netcoreapp3.0/rzc.dll" @"/var/folders/fw/gclm_x1j7j7_njl094h_7c600000gn/T/tmpaeb657e1f32847dab38256710b8e583e.rsp"', CurrentDirectory='', Native error= Cannot find the specified file
>   at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/mcs/class/System/System.Diagnostics/Process.cs:778 
>   at System.Diagnostics.Process.Start () [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System/services/monitoring/system/diagnosticts/Process.cs:2006 
>   at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
>   at Microsoft.Build.Utilities.ToolTask.ExecuteTool (System.String pathToTool, System.String responseFileCommands, System.String commandLineCommands) [0x000c9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:705 
>   at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.ExecuteTool (System.String pathToTool, System.String responseFileCommands, System.String commandLineCommands) [0x00017] in <cd49f2251c6c4be3b20e21244e30c717>:0 
>   at Microsoft.Build.Utilities.ToolTask.Execute () [0x00432] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-12/external/bockbuild/builds/msbuild-15/src/Utilities/ToolTask.cs:1515  (MSB6003) (PruebasCoreMVC)

With this error I add some package references but it doesn't work, this is my csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="3.1.4" />
  </ItemGroup>
</Project>
```

Besides, this is not the only case because I try to make an API AS.NET Core application and the command scaffold context to work with an existing database it doesn't work.
I don't keno if is something with visual studio or the sdk or the runtime.

This is my sdk and runtimes:

> MacBook-Pro-de-Alejandro:~ alejos$ dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.300
>  Commit:    b2475c1295
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/3.1.300/
> 
> Host (useful for support):
>   Version: 3.1.4
>   Commit:  0c2e69caa6
> 
> .NET Core SDKs installed:
>   3.1.101 [/usr/local/share/dotnet/sdk]
>   3.1.200 [/usr/local/share/dotnet/sdk]
>   3.1.202 [/usr/local/share/dotnet/sdk]
>   3.1.300 [/usr/local/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try to follow the command line instructions or try with VSC
Compare the project file to https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/TodoApi.csproj
You'll want to update the versions
