### ISSUE TITLE
Lacks detailed examples for more common scenarios

### ISSUE THREAD

**Issue by THammond9** [dotnet/AspNetCore.Docs#18565]
I have a simple DI scenario which I am having trouble finding some specific examples for. Most of the documentation I has seen is in relation to web applications which behave differently than a windows service which does not usually stop running.
````
services.AddHostedService<MainEntryPoint>();
services.AddTransient<TransientDependency, TransientDependency>();
services.AddTransient(x => new ContextFactory(hostContext.Configuration).CreateDbContext(new[] {
                        hostContext.Configuration.GetConnectionString("MyConnectionString") }));
----

public class MainEntryPoint {
  private ITransientDependency TransientDependency {get;set;}
  MainEntryPoint (ITransientDependency  t) {
    this.TransientDependency = t;
  }
}

----

public TransientDependency : ITransientDependency {
  private Context Context {get;set;}
    TransientDependency(Context c) {
    this.Context = c;
  }
}
````

From what I understand `MainEntryPoint` is treated as a singleton which causes the dependencies to only have one instance initialized. It would be helpful if the documentation for windows services covered very common scenarios where a database connection is needed and how to properly set that up. If there is already such documentation then there should be a link indicating that more common scenarios are covered in the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
