### ISSUE TITLE
AddDefaultIdentity vs AddIdentity

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18573]
See [AddDefaultIdentity and AddIdentity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio#adddefaultidentity-and-addidentity)

@HaoK, @serpent5  is out top contributor. See his popular [SO answer](https://stackoverflow.com/questions/55361533/addidentity-vs-addidentitycore/55361961#55361961) to this question. Should we have him add that to this doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
These are slightly different things. The topic's section is about `AddDefaultIdentity` vs `AddIdentity`, whereas the SO answer is about `AddIdentity` vs `AddIdentityCore`.

**Comment by Rick-Anderson** [comment]
Maybe that's not worth adding to the doc.  Maybe we should link to it at the end of the doc?

**Comment by serpent5** [comment]
@Rick-Anderson I don't think it's worth adding to the docs, because it's not something that a typical user cares about. The docs don't mention `AddIdentityCore` at all, so I think anyone that does want to know the difference will find it easily enough using their favourite search engine.
