### ISSUE TITLE
Instructions on new Windows install don't work

### ISSUE THREAD

**Issue by emersonp** [dotnet/AspNetCore.Docs#18578]
These instructions don't appear to work with either the most recent release of .NET Core, or the most recent release of VSCode.

Fresh install of Windows (on VM). Grab

- VSCode
- .Net Core 3.1.300 SDK
- Chrome

Follow instructions (extensions, etc.).

"The site can't be reached."

Likely a bug with Blazor/.NET Core, but currently these entry level instructions do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@emersonp ... Did you trust the ASP.NET Core dev certificate after installing the SDK (`dotnet dev-certs https --trust`)?

**Comment by guardrex** [comment]
A VM's browser has a number of restrictions by default. Blazor is supported in a browser configured by default for a user's device. Did you reconfigure the VM's browser to remove it default restrictions?

**Comment by guardrex** [comment]
I'm going to close given that the behavior is by-design if the browser's security settings, such as those on a VM, are highly restricted (or the dev cert isn't trusted, which is called out by the SDK installer).
