### ISSUE TITLE
"dotnet -v" returns "Unknown option: -v"

### ISSUE THREAD

**Issue by akunaatrium** [dotnet/AspNetCore.Docs#18589]
The page suggests to execute a command to determine the version of installed .NET Core SDK but executing it gives an unexpected result.

![image](https://user-images.githubusercontent.com/1319115/83353009-3fbcaa80-a358-11ea-9897-7e8c774c83e4.png)

The result:
```
PS C:\Users\anvar> dotnet -v
Unknown option: -v
.NET Core SDK (3.1.300)
Usage: dotnet [runtime-options] [path-to-application] [arguments]
...
```

I suppose the command to execute should be something else to determine the installed version(s) of .NET Core SDKs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @akunaatrium ... It should be `--version`. I'll patch it now.
