### ISSUE TITLE
you state the following: --If you want to apply authorization to an action rather than the controller, apply the AuthorizeAttribute attribute to the action itself.-- But when I apply it to a page handler method, I get a warning that says, I can only apply it class wide. 

### ISSUE THREAD

**Issue by Coscotex101** [dotnet/AspNetCore.Docs#18583]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The article is correct. Scaffold Identity and look at the tempates.

**Comment by Coscotex101** [comment]
@Rick-Anderson  I just scaffolded for razor pages core 3.1 to reconfirm this, and there are no page-handler-method filters. You are allowed to use [Authorize] at class levels for pagemodels but not for OnGet or OnPost handler methods. This is infact the same reason my organisation is stuck at core 2.1, because it's the last version you guys allowed for page-handler-method filters. If you use [Authorize] for a page-handler-method from Core2.2 and above, you'll get a warning and it won't work.

**Comment by Rick-Anderson** [comment]
Right, the document doesn't say you can apply it to Razor page handler methods.
