### ISSUE TITLE
Insufficient information

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/AspNetCore.Docs#18593]
- The article should mention the **exact** lowest version needed for using Blazor WebAssembly. (It mentiones .NET Core 3.1, but I think it should be .NET Core 3.1.201
- Running `dotnet new blazorwasm` lead to "No templates matched the input template name" error in my case. This got fixed in my case by running `dotnet new -i Microsoft.AspNetCore.Components.WebAssembly.Templates::3.2.0-rc1.20223.4`. The article should also mention something on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Get started with ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Youssef1313 ... Blazor WebAssembly officially released with the 3.1.300 SDK; so as far as a minimum **_supported_** version is concerned, it will be 3.1.300. That SDK includes the template.

I'll make the text say "latest version" when referring to 3.1, as it does on the VSC tab.
