### ISSUE TITLE
Do the users of a razor wasm app need to download ~6MB of data in the first run?

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/AspNetCore.Docs#18595]
I'm trying to experiment with blazor wasm, I've created the default template and run it. Opening it for the first time in a browser downloads a significantly large amount of data (around 6MB), will the client need to download this size of data on the first run? or there is a way to publish something reduced in size?

I don't know if these information documented somewhere, but I couldn't find.

**Comment by guardrex** [comment]
@Youssef1313, yes, the app's assemblies **_and the .NET runtime_** (Mono) must be downloaded to the browser, then the .NET runtime is cached. It's documented here :point_right: https://docs.microsoft.com/aspnet/core/blazor/?view=aspnetcore-3.1#blazor-webassembly. It's a bit of an implementation detail, so there's not much else to say about it outside of perf, and the only main perf at the moment is default [precompression](https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#precompression) and [IL stripping of unused assemblies](https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1), which is also automatic. ... btw ... I see that accidental extra parentheses after "Gzip" in the *Precompression* section. I'll patch that out of the doc shortly.

**Comment by guardrex** [comment]
... and there's a perf doc for Blazor WebAssembly ...

https://docs.microsoft.com/aspnet/core/performance/blazor/webassembly-best-practices?view=aspnetcore-3.1

**Comment by Youssef1313** [comment]
@guardrex Thanks again for the fast response. Much appreciated!

> the only main perf at the moment is default precompression and IL stripping of unused assemblies, which is also automatic

I saw in the network tab in the browser developer tools that some *unneeded* assemblies are being downloaded, these includes:

- *mscorlib.dll*, which I think is a .NET Framework-related dll. How is that relevant for .NET Core? (btw, it's the largest downloaded dll, around 4MB)
- *System.Xml.Linq.dll* and *System.xml.dll*, I don't think the default template uses XML anywhere.

Do you know if there're there some planned optimizations to reduce the size of components needed for the first run in the next releases for Blazor WebAssembly?

**Comment by guardrex** [comment]
Search on the engineering repo Blazor issues to see what they're working on ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-blazor

... but I don't see much in the perf area. The general answer tho is *yes* ... they're aware of the issues, and they've said that they're continually working on getting the first load experience better for Blazor WebAssembly.

As for the assemblies that you mentioned, I think they are used. You'd need to study the Blazor code in the engineering repo to see what namespaces they might be using from those assemblies.

**Comment by Youssef1313** [comment]
Thanks again! :)
