### ISSUE TITLE
Resources are not being applied on Razor Page Input models

### ISSUE THREAD

**Issue by DavidShukvani** [dotnet/AspNetCore.Docs#18596]
Hello,

I have an example where the Localizer is not affecting the ViewModel classes' properties' data annotation, it's a plain MS template project code:

```
public class ChangePasswordModel : PageModel
{
// ...
        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Current password")]
            public string OldPassword { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }
//...
```

I have tried several versions to make it work:
`Areas/Identity/Pages/Account/Manage/ChangePassword.ka-GE.resx`
`Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs.ka-GE.resx` (this was read as CZ)
`Areas/Identity/Pages/Account/Manage/ChangePasswordModel.ka-GE.resx`

Maybe you could create a Razor pages example?
I know how to correct this issue, but with another approach, but it would be better if all localization tasks will be dealt with in same manner.
Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#make-the-apps-content-localizable)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DavidShukvani  looks like you scaffolded Identity and tried to localize it?

My guess is the fully qualified name is not correct.

cc @hishamco

**Comment by DavidShukvani** [comment]
Yes, exactly, but I tried dozens of combinations for matching, but no luck.

**Comment by hishamco** [comment]
@DavidShukvani could please share a minimal repo to reproduce the issue?

**Comment by DavidShukvani** [comment]
@hishamco please see: https://github.com/DavidShukvani/IssuePresentationForLocalizer
I have setup the registration and login pages to localize Georgian (ka-GE) and English (en-GB).
Thank you!

**Comment by hishamco** [comment]
After I saw your demo, your remind me with a weird bug that AspNetCore doesn't solve yet, but I already fixed this in OC and blogged about few years ago

Just avoid to use inner classes, so move your `InputModel` into `LocalizerIssue.Areas.Identity.Pages.Account` and it should work

**Comment by DavidShukvani** [comment]
Ok, thanks!

**Comment by DavidShukvani** [comment]
I would suggest you add an clause in article in this [part](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#dataannotations-localization).
