### ISSUE TITLE
Queued background tasks not going to be implemented in .netcore

### ISSUE THREAD

**Issue by akempe** [dotnet/AspNetCore.Docs#18605]
For the section *Queued background tasks*, there is a link to an issue regarding tentative implementation in .netcore. This issue is now closed as "will not implement". Docs should be updated to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Aye @akempe ... That's on me. I didn't catch their note there. 🏃🏃🏃😅 I'll patch that out right now. Thanks for calling it out.
