### ISSUE TITLE
Matching UNIT to specific APP

### ISSUE THREAD

**Issue by samgithub** [dotnet/AspNetCore.Docs#18617]
In the doc, you show how to create a service for the app **helloapp**.

Can you please explain what happens if I have a second app **helloapp2** and a service to run **helloapp2**

Since they'll use **defferent** UNITs with 
a)  EecStart=/usr/bin/dotnet /var/www/helloapp/**helloapp.dl**
b)  ExecStart=/usr/bin/dotnet /var/www/helloapp2/**helloapp2.dll** 

 HOW do we map the **server** to NGINX the specific **UNIT**

Including an explanation of this in the doc will make it more comprehensive and useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the question. We're a small doc team that maintains all the docs in this repo. We don't have the resources to work on a response for you. You might try https://stackoverflow.com/
