### ISSUE TITLE
Page Error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18614]
@detmach commented on [Fri May 29 2020](https://github.com/dotnet/AspNetCore.Docs.tr-tr/issues/16)

Page Error

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [ASP.NET Core 'de yanıt önbelleğe almaResponse caching in ASP.NET Core](https://docs.microsoft.com/tr-tr/aspnet/core/performance/caching/response?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs.tr-tr/blob/live/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @olprod

---

@srvbpigh commented on [Fri May 29 2020](https://github.com/dotnet/AspNetCore.Docs.tr-tr/issues/16#issuecomment-636202919)

Hello, @detmach
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
The localized versions of this document have the tables broken
It's Machine-translated

best

**Comment by Rick-Anderson** [comment]
@JasonCard  @CeciAc  Take a look at Content: [ASP.NET Core 'de yanıt önbelleğe almaResponse caching in ASP.NET Core](https://docs.microsoft.com/tr-tr/aspnet/core/performance/caching/response?view=aspnetcore-2.2) or look at it in Chrome and select translate to english. It looks like MT is broken. I don't see an issue with the MD file.

My guess is the following metadata is causing the problem
`no-loc: [Blazor, "Identity", "Let's Encrypt", Razor, SignalR]`

It's not needed for this file. I could remove it and merge to live to see if that fixes it. 

cc @scottaddie @wadepickett @guardrex

**Comment by JasonCard** [comment]
@Rick-Anderson @CeciAc I recognize this issue which was fixed in another repo, so I'm now trying re-upload the source file into our loc platform to see if it will resolve the issue. Will update. This issue appears to be on loc tooling side, so it can be moved back to loc repo and/or assigned to me.

**Comment by JasonCard** [comment]
Hi @detmach 
Thank you for your feedback.
It appears this issue is now resolved, but please let me know if there are still any issues.

@Rick-Anderson Could you please help to close this issue?

**Comment by detmach** [comment]
Merhabalar, Gün içerisinde inceledim ve herhangi bir sorun göremedim. İlgilendiğiniz ve yardımcı olduğunuz için teşekkürler.
