### ISSUE TITLE
Bug in Tutorial

### ISSUE THREAD

**Issue by DominikTripet** [dotnet/AspNetCore.Docs#18628]
[Enter feedback here]
In the Startup.cs file in method `Configure` you add `app.UseCors()`. But there you are missing the defined string "allowAll" in method `ConfigureServices`. It should be `app.UseCors("AllowAll");`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c13a1c7-4683-a9a5-9ab3-e28d4506af26
* Version Independent ID: ea3b00c8-8f09-c045-4641-dc3a0030d6e5
* Content: [Use gRPC in browser apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/browser.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/browser.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@JamesNK, I will update app.UseCors() to app.UseCors("AllowAll") if that was your intent.

**Comment by JamesNK** [comment]
The sample is correct as it is. The CORS policy name is specified on the endpoint with `RequireCors("AllowAll")`.

**Comment by wadepickett** [comment]
Thanks @DominikTripet for showing some community love for the docs.  Always appreciated.  I will go ahead and close this one since as James points out, the policy name is specified where intended.
