### ISSUE TITLE
Default deploy of default (newly created Blazor-server app) to Azure is imposible.

### ISSUE THREAD

**Issue by Lionberg** [dotnet/AspNetCore.Docs#18634]
[Enter feedback here]

Despite local solution works fine, it is impossible to deploy the same code to azure.

Error: The circuit failed to initialize.
Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at e.connectionClosed (blazor.server.js:1)
    at e.connection.onclose (blazor.server.js:1)
    at e.stopConnection (blazor.server.js:1)
    at e.transport.onclose (blazor.server.js:1)
    at e.raiseOnClose (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:1)
    at blazor.server.js:1
    at Object.next (blazor.server.js:1)
    at a (blazor.server.js:1)
---

And big umbrella question: **WHY** even default settings cannot work with Microsoft services?.. 
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef32cc5-6a1f-25c9-0d89-a984a3f68851
* Version Independent ID: 3e302985-8504-d333-3222-ab8da8902da2
* Content: [Logging and diagnostics in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @anurse
* Microsoft Alias: **anurse**

**Comment by guardrex** [comment]
Hello @Lionberg ... It looks like you didn't open this issue from the correct topic. Which topic or tutorial are you trying to follow?

**Comment by guardrex** [comment]
Are you working from this one? ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio
