### ISSUE TITLE
Blazor Docs Need Improved Containerization Steps

### ISSUE THREAD

**Issue by jongio** [dotnet/AspNetCore.Docs#18631]
This page: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#nginx

The nginx file and Dockerfile example don't actually work if you follow the steps in the doc.  Let's provide a step-by-step approach to getting Blazor WebAssembly running in a container.  

I have also created a bug for vscode-docker extension here: https://github.com/microsoft/vscode-docker/issues/2034

I suggest we added a new page that is all about running Blazor in a container, both standalone and hosted.  Thanks

azsdke2e
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b4d6a1-1436-7ba8-a5c5-8dcb6a955bb0
* Version Independent ID: 4a6a13b4-fe5c-a9fb-5d7d-33d5aa0fbac3
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.1#nginx)
* Content Source: [aspnetcore/host-and-deploy/blazor/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jongio ... We'll further scope this down to what type of update (enhancement, bug, or new doc) when the issue is triaged. It usually happens on Fridays, but I suspect due to high priority internal work that this won't be seen by the product unit until Friday, 6/12.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this up. This is not something we want to include in our docs at this point.

**Comment by mkArtakMSFT** [comment]
It looks like we missed the fact that this is an existing content. Reopening.

**Comment by pranavkm** [comment]
@guardrex have you tried the nginx config listed in the docs recently?

**Comment by guardrex** [comment]
@pranavkm The original content goes way back to ancient times ... Blazor experimental days 👴 ... *blazor.net* docs ... before the docs even arrived on this repo. We've touched them up from there based on feedback, and I assumed with each update based on reader feedback that what we had was working at least in the non-containerized scenario. I haven't tested any of the updates myself.

WRT the guidance being "existing" or not. I'm not aware if the current guidance works but merely **_doesn't work in a container_** or if the guidance just flatout fails now ... container or not.

**Comment by pranavkm** [comment]
Ok. If we think the instructions work outside of Docker, could we remove the section that talks about deploying it inside a container? It feels out of place (why is it specific to Ngnix, why not Kestrel or YARP?) and has issues.

**Comment by guardrex** [comment]
> If we think the instructions work outside of Docker

No complaints currently. I have an :ear: open for feedback. When I reach this topic on UE passes of docs, I hope to test the guidance on Nginx and see how it goes.

> remove the section

Very well. @mkArtakMSFT ... Ok with you to remove it?

**Comment by mkArtakMSFT** [comment]
> Very well. @mkArtakMSFT ... Ok with you to remove it?

Yes please, @guardrex

**Comment by jongio** [comment]
It's unclear to me if we are saying that we are going to remove all guidance for containerizing blazor apps or just removing from this doc.  IMO we need to provide the guidance and it needs to work.  I personally spent a bunch of time trying to get it to work and resorted to external blogs and the MS guidance was incorrect.

I believe the correct answer is to publish a doc that provides detailed guidance on how one can containerize a blazor app.

I wrote about all the various ways here:
https://github.com/jongio/BlazorDocker

Happy to meet up and chat about it and come up with a plan, just LMK

@danroth27

**Comment by guardrex** [comment]
@jongio ... Sorry for the delay in getting back to you. I'm finally getting caught back up here ⛰️⛏️😅 ... just enough to get back to a series of topic overhauls that I started before the holidays! 🏃🏃🏃

Would you consider listing your GH repo/tutorial at Awesome Blazor ...

https://github.com/AdrienTorris/awesome-blazor

We cross-link and refer readers to Awesome Blazor for scenarios like this that we have trouble covering and maintaining. Also, I noticed that a web search with "blazor" and "docker" turn up several great tutorials. SO also provides support for various Blazor+Docker questions.
