### ISSUE TITLE
there's no `withAutomaticReconnect` on type `HubConnectionBuilder`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/AspNetCore.Docs#18638]
[Enter feedback here]

when use signalr follow the docs, will get an error like follows:

```
Property 'withAutomaticReconnect' does not exist on type 'HubConnectionBuilder'
```

the docs maybe out of date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
That is probably because you are using an older version of the client that doesn't have support for automatic reconnect yet. You need to use 3.1 or newer.

**Comment by WeihanLi** [comment]
> That is probably because you are using an older version of the client that doesn't have support for automatic reconnect yet. You need to use 3.1 or newer.

Thanks for the info, I checked the package I used before is `@aspnet/signalr` 1.1.4, seemed the package had change to `@microsoft/signalr`
