### ISSUE TITLE
jQuery setup is missing

### ISSUE THREAD

**Issue by yyordanov** [dotnet/AspNetCore.Docs#18642]
I don't see the steps needed to be executed to enable the client side validation (e.g. installation of the jQeury packages and their initialization)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's done by the template generate code.
