### ISSUE TITLE
Static Files from Razor Class Library | CaseSensitive on Linux-Docker Containers

### ISSUE THREAD

**Issue by oiBio** [dotnet/AspNetCore.Docs#18640]
Hello,

i have just "lost" a few hours searching for a bug when i tried to run my blazor project in a linux docker container. The problem was that I pointed to the static files in _host.cshtml as being in the wrong case. It worked perfectly with IIS and Windows containers, but was not found when I ran a Linux container.

I used 
   ` <link href="~/_content/my-app-name.components/css/components.css" rel="stylesheet" />`
 instead of 
   ` <link href="~/_content/My-App-Name.components/css/components.css" rel="stylesheet" />`

so I just got a 404 for my static filesm because the linux filesystem is case sensitive and the windows filesystem is not.

I'm not super familiar with Linux nor Docker, but I think this could be mentioned in the documents. Like a little hint or something.... that would have saved me a lot of headaches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#create-an-rcl-with-static-assets)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Sorry for that. We expect Linux users to know it's case-sensitive by default thoughout our docs.
