### ISSUE TITLE
Using view components for shared forms

### ISSUE THREAD

**Issue by bathetrade** [dotnet/AspNetCore.Docs#18648]
Please add information and an example on how to use view components for shared forms in Razor pages. For example, imagine a login form that needs to be used on multiple Razor pages. Further, some of those pages have various bits of logic that depend on whether a user is logged in. In that case, the view component cannot handle the POST (by checking Request.HasFormContentType and using Request.Form), because it would only be invoked after the page has started to render. Bits of the page before the view component is invoked would decide that the user isn't logged in (possibly by looking at session state). Bits of the page after the view component is invoked would decide the user is logged in.

The best I've come up with is adding a controller that the shared login form posts to. When the controller is done, it redirects back to the originating URL (included as a hidden form field). However, it's unclear in this case how to handle redisplaying the form with errors when model state is invalid.

When the shared form is included on a Razor page, it's also unclear how to pass complex or large amounts of data back to it from the controller without resorting to session state or temp data (we're trying to avoid these for scalability reasons). For example, imagine the login form has an email and password field initially, but displays more rich information about a user once they've logged in. How can the controller get information about the user back to the view component if the component is invoked from a Razor page? 

Conceptually, I'd love to be able to do "return Page(pageName, someModel)", where someModel gets passed to the view component (perhaps via a property on it), but something like this isn't possible to my knowledge.

Is this a scenario better handled by views than pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
