### ISSUE TITLE
HUB pages needs core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18647]
ASP.NET Core is always ASP.NET Core and never ASP.NET without Core.

https://docs.microsoft.com/en-us/aspnet/core/

Also fix https://docs.microsoft.com/ or create another issue for that

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/83677851-80930a00-a578-11ea-89cf-6bc383e981c4.png)

**Comment by Rick-Anderson** [comment]
Fix the following:
https://docs.microsoft.com/aspnet/overview
![image](https://user-images.githubusercontent.com/3605364/83678045-c2bc4b80-a578-11ea-8bb8-774c80ff9f5e.png)

**Comment by wadepickett** [comment]
Fixed ASP.NET docs toc portion of this issue in that repo with: https://github.com/dotnet/AspNetDocs/issues/399
