### ISSUE TITLE
Unable to evaluate

### ISSUE THREAD

**Issue by srudin** [dotnet/AspNetCore.Docs#18657]
Debugging generally works, my breakpoints are hit. However I cannot display any variables: The locals window, quick watch etc. simply display "Unable to evaluate" for all variables, objects etc. Therefore expanding an object (by clicking on the +) also doesn't work. Debugging without seeing any values is of course not very helpful...

I am using the newest releases of both VS2019 (16.6.1) and the .NET SDK (3.1.300). Is there something else I need to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @srudin ... Please open this for engineering at ...

https://github.com/dotnet/aspnetcore/issues

Add a `cc: @guardrex` to your issue. If a solution is found that we need to call out in the topic, I'll re-open this issue.
