### ISSUE TITLE
Blazor WASM debug: Old Edge troubleshoot coverage

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18672]
Call out **_old Edge_** 👴 error with Edge upgrade guidance.

https://github.com/microsoft/vscode-js-debug/issues/504#issuecomment-638991206

cc: @captainsafia ... I'll get this on Friday morning. 🏃

btw --- Idk if we should do anything about it, **_but_** .......

* I had no idea that there was a **new** Edge.
* Edge doesn't say anything about it.
* Windows Update doesn't try to get it.

I'll leave it to you/Artak if you want to try to contact them internally about what happened here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
To be honest, I'm hesitant to include this in the documentation.

This is more-so something that should be documented for the JS debugger than for the `blazorwasm` debug type. I worry about crowding our docs with troubleshooting info that isn't completely relevant to us.

My inclination is to wait a bit and see how many other users run into this. If this ends up being a more common issue, we can add it to the docs.

FWIW, I tested on a Windows 10 VM and Edge was installed in program files. There might be some funkiness depending on which RTM of windows you are on.

**Comment by guardrex** [comment]
Readers won't see it that way, but ok ... let's see. Hopefully, I'm the only one to hit this.
