### ISSUE TITLE
Examples Don't Work

### ISSUE THREAD

**Issue by jdosser** [dotnet/AspNetCore.Docs#18671]
Well, this would be a fine document IF it actually worked.
It's frustrating enough there's not any documentation on Blazor, but to come to 
Microsoft's site and try and get stuff to work by following the examples and finding
out it doesn't.....

Let's look at the 1st two examples. Pretty simple, right? So I add AboutModel
to a new Blazor project and instantiate an instance in the default 'IncrementCount'
method. 
Inside I make a call to AboutModel.Message. Value returned "null". Not real
Useful. 
Next, I try the second example: var username = Context.User.Identity.Name;
And i receive the error: The name 'Context' does not exist in current context.

There needs to either 1) Be more detail or 2) Ensure these examples work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jdosser Not sure yet from your remarks what approach you're taking and what you're trying to do ... even if you discovered the Blazor doc node. `HttpContext` in the MVC/Razor Pages part of a Blazor Server app doesn't have anything to do with Blazor. You mention `IncrementCount`, but that's part of a Razor component. If you're new to Blazor apps ... how they're set up and how they work ... access the docs in the Blazor node, which should clear a lot of things up for you. Coverage starts here ...

https://docs.microsoft.com/aspnet/core/blazor/
