### ISSUE TITLE
PassThroughAuthorizationHandler is there to allow an IAuthorizationRequirement to be its own IAuthorizationHandler

### ISSUE THREAD

**Issue by michaeldz** [dotnet/AspNetCore.Docs#18695]
If requirement also implements IAuthorizationHandler (or AuthorizationHandler<T>) it is not necessary to register handler in service collection because there is PassThroughAuthorizationHandler

Please add this to the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I looked into this and found that the [`PassThroughAuthorizationHandler`](https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Security/Authorization/Core/src/PassThroughAuthorizationHandler.cs) is there to allow an `IAuthorizationRequirement` to be its own `IAuthorizationHandler`, as suggested. It's added by the core authz services, so it should be enough to just implement both interfaces and it'll all work magically. HTH.

**Comment by stijnherreman** [comment]
@Rick-Anderson the PassThroughAuthorizationHandler remains undocumented on that page. Is it OK to depend on its behaviour, or should we register handlers regardless?

**Comment by Rick-Anderson** [comment]
@blowdart  please suggest text to document the [`PassThroughAuthorizationHandler`](https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Security/Authorization/Core/src/PassThroughAuthorizationHandler.cs)

**Comment by blowdart** [comment]
@HaoK suggestions? Is this the actual behaviour, because that's a new one on me.

As for should you depend on an undocumented feature? No, not unless Hao states otherwise and we document it :)

**Comment by HaoK** [comment]
Oh its definitely intentional, that is meant to be a convivence class to do exactly that, so any IAuthorizationRequirement that implements IAuthorizationHandler is both things.

**Comment by blowdart** [comment]
So no DI needs to happen if both interfaces are used? What version did that come in?

**Comment by HaoK** [comment]
V0 :)

**Comment by HaoK** [comment]
Quality of life thing for when I was testing/writing things

**Comment by blowdart** [comment]
Fair enough. Mind you, do we recommend mixing both? I only used that in simple demos, it seems that mixing the two is odd-ish

**Comment by HaoK** [comment]
I guess the way I'd phrase it is, all requirements need to have handlers, its up to them to choose the proper elegant design, they can simply have all requirements be their own handlers if they like.  Generally for simple handlers/requirements that is nice.  But complex handlers probably should be explicitly registered in their own class

**Comment by HaoK** [comment]
Its more of an implementation details than anything else, sugar

**Comment by HaoK** [comment]
A good example of where I used this was our AssertionRequirement which is both a requirement and the handler for itself since its fully selfcontained:

https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Security/Authorization/Core/src/AssertionRequirement.cs#L13

**Comment by blowdart** [comment]
OK then

@Rick-Anderson In the Handler registration section a new paragraph something like

> It is possible to bundle both a requirement and a handler in a single class implementing both IAuthorizationRequirement and IAuthorizationHander. This creates a tight coupling between the handler and requirement, and is only recommended for simple requirements and handlers. Creating a class which implements both interfaces removes the need to register the handler in DI.

**Comment by Rick-Anderson** [comment]
Can someone PR the article with updated text and I'll clean it up?

**Comment by HaoK** [comment]
> Creating a class which implements both interfaces removes the need to register the handler in DI.

Maybe also add ", because there's a built in PassThroughtAuthorizationHandler that allows requirements to handle themselves."
