### ISSUE TITLE
Asp.Net Core gRPC Azure App Service Linux Support?

### ISSUE THREAD

**Issue by EddyHaigh** [dotnet/AspNetCore.Docs#18706]
The warning talks about Azure App Service and IIS, but I assume that it means that the Azure App Service Windows offering does not support it. So, does Azure App Service Linux support gRPC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
@bradygaster  softball here.

**Comment by bradygaster** [comment]
There is no support on App Service for gRPC without using gRPC-web at the moment. adding @JamesNK as he has a few examples in the gRPC repository that may prove helpful.

**Comment by Rick-Anderson** [comment]
> The warning talks about Azure App Service and IIS,

Actually it says
ASP.NET Core gRPC is not currently supported on Azure App Service ***OR*** IIS

which is not ambiguous
