### ISSUE TITLE
information required how to change th e messages to match the rules for registration

### ISSUE THREAD

**Issue by beardiedog** [dotnet/AspNetCore.Docs#18704]
[Enter feedback here]
I modified my password rules in my Blazor Server app to minimum 8 characters but the registration screen still states it needs 6 characters it would be helpful to explain how to get these in sync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ac09f0-74ca-1a5d-4fec-695b84c1ac95
* Version Independent ID: cd2c1f5e-e4f0-d2c3-4737-8ff4f0c176c2
* Content: [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@beardiedog, can you show your `IdentityOptions` configuration (your code) and show a screenshot of the registration screen?

**Comment by beardiedog** [comment]
Hi I found out where this is now, you have to modify the string in the default cshtml that the Identity adds.so my configuration states this options.Password.RequiredLength = 8; while in the register.cshtml.cs the attribute is [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]

**Comment by guardrex** [comment]
> default cshtml that the Identity adds

I see what you mean.

I took one of my apps and scaffolded in the Register page. I received what you did ...

```csthml
[StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
```

This isn't specific to Blazor ... it's a general Identity scenario.

@Rick-Anderson I think we'll need to call this out in both this topic and the [scaffolding topic](https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity). Neither of these topics mention that scaffolding may result in pages with Identity page model attributes that conflict with configured `IdentityOptions`. If you agree, I have a few minutes ... I'm waiting on Blazor feedback from engineering right now, so I have a little time until they get back to me. If you, @wadepickett, or @AdrienTorris would rather work it, then unassign me. I'll wait to hear back from you before I do anything.
