### ISSUE TITLE
Add information regarding using reference

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [dotnet/AspNetCore.Docs#18719]
Please update all examples and or page to mention that the reference 
using System.Net.Http;
 needs to be added to use this.
It's an ongoing and completely unnecessary obstacle for people to need to be forced to independently research the namespace all the time in the .net examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@serpent5  can you add something like the following near the top of the tutorial.

The code samples used in this doc can be found at `[http-requests/samples/3.x/](https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/http-requests/samples/3.x)

That should help.

**Comment by serpent5** [comment]
@Rick-Anderson We already have "View or download sample code (how to download)." near the top, so I think adding the suggested text would just repeat that, perhaps. Would it be helpful to add something [here](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1#how-to-download-a-sample) that explains how usings are usually dropped for brevity but can be seen in the samples, for example?

**Comment by Rick-Anderson** [comment]
@serpent5  I missed that.  We usually don't add using on advanced tutorials. I thiink we're OK for now.
