### ISSUE TITLE
Invalid App ID The provided app ID does not look like a valid app ID.

### ISSUE THREAD

**Issue by Rabin77** [dotnet/AspNetCore.Docs#18711]
when i click on login into facebook i have faced this error 
[Enter feedback here]

---
#### Document Details
![image](https://user-images.githubusercontent.com/51988992/84052996-0546b380-a9d1-11ea-85e3-e4d05abd5ce1.png)
![image](https://user-images.githubusercontent.com/51988992/84053036-1394cf80-a9d1-11ea-990d-e55f50f3b338.png)

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Copy/paste error? 
Make sure you get it from https://developers.facebook.com/apps/
