### ISSUE TITLE
Provide guidance on SignalR Service modes when using with Blazor Server

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#18710]
At the time of writing, Azure SignalR Service offers the following 3 services modes:

1. Serverless
1. Default
1. Classic

There should be guidance in the following section that explains which mode should be used and why: https://docs.microsoft.com/aspnet/core/host-and-deploy/blazor/server#azure-signalr-service. I've used Classic mode in the past, but is there ever a good reason to select Default?

/cc: @sffamily @bradygaster 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eddf2de-7e50-5680-ff2d-a4307f26b5c0
* Version Independent ID: 673f220c-ad49-bd27-5d74-3a9c44747cba
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/server?view=aspnetcore-3.1#azure-signalr-service)
* Content Source: [aspnetcore/host-and-deploy/blazor/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/blazor/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
"mode" seems to only be mentioned explicitly in one spot in this SignalR doc set ...

> If you're using Azure SignalR Service in *Serverless mode*, you cannot call hub methods from a client.

Reference:

* https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.1&tabs=visual-studio#call-hub-methods-from-client
* https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-3.1#call-hub-methods-from-client
* https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#call-hub-methods-from-client

In Azure docs ...

> Azure SignalR Service can be configured in different modes. When used with Azure Functions, the service must be configured in Serverless mode.

Reference: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config#signalr-service-configuration

> After the instance is deployed, open it in the portal and locate its Settings page. Change the Service Mode setting to Serverless.

Reference: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-tutorial-authenticate-azure-functions#create-an-azure-signalr-service-instance

> Serverless mode is not supported for ASP.NET SignalR applications. Always use Default or Classic for the Azure SignalR Service instance.

Reference: https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet#create-an-azure-signalr-service-instance

From https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-event-grid-integration#serverless-state, they link to the following ...

https://github.com/Azure/azure-signalr/blob/dev/docs/faq.md#what-is-the-meaning-of-service-mode-defaultserverlessclassic-how-can-i-choose

... which states ...

> Modes:
>
> * Default mode requires hub server. When there is no server connection available for the hub, the client tries to connect to this hub fails.
> * Serverless mode does NOT allow any server connection, i.e. it will reject all server connections, all clients must in serverless mode.
>
> Classic mode is a mixed status. When a hub has server connection, the new client will be routed to hub server, if not, client will enter serverless mode.
>
> This may cause some problem, for example, all of server connections are lost for a moment, some clients will enter serverless mode, instead of route to hub server.
>
> Choosing:
>
> * No hub server, choose Serverless.
> * All of hubs have hub servers, choose Default.
> * Some of hubs have hub servers, others not, choose Classic, but this may cause some problem, the better way is create two instances, one is Serverless, another is Default.

**Comment by guardrex** [comment]
I'm not sure that that's the only spot to cover it. This seems like general guidance. I'll wait for feedback on *where to cover it* before proceeding.

**Comment by scottaddie** [comment]
@guardrex I was chatting offline with @sffamily about this. Let's see what Zhidi recommends.

**Comment by mkArtakMSFT** [comment]
This indeed seems to be something to be documented on the SignalR side.

**Comment by mkArtakMSFT** [comment]
Having said that, I don't think there is much from the Blazor side we want here.

**Comment by guardrex** [comment]
I'll work it as a SignalR issue unless @BrennanConroy and/or @scottaddie says otherwise. Plz go ahead and reassign it if anyone else should work it.

**Comment by mkArtakMSFT** [comment]
@bradygaster who is the best person to document this for SignalR ? I'm removing this from the Blazor docs project.

**Comment by bradygaster** [comment]
Will do - will reach out to our friends in the service team to get this carved out with them. There's another doc update I'd like to make on using the service so this is good timing.

**Comment by mkArtakMSFT** [comment]
Thanks for following up, @bradygaster. Just saw their response.
@scottaddie the recommendation here is to use the `default` mode. As the other modes either nor recommended or won't work - let's not even bother mentioning those.

**Comment by guardrex** [comment]
The only coverage in this doc set is ...

> If you're using Azure SignalR Service in Serverless mode, you cannot call hub methods from a client.

I list the topics (looks like that's in three spots) above :point_up:. The remark can be removed in favor of an explicit remark to use `Default`.

@scottaddie ... I can remain assigned and work this if u want or ur welcome to it.

**Comment by bradygaster** [comment]
I'm fine with either, but I know @scottaddie is super-slammed and has little time for this (I asked yesterday!). @guardrex if you have time put me on as reviewer.

**Comment by guardrex** [comment]
Will do ... I'll be able to take care of this tomorrow (Friday, 8/6). Will hit u up for the review.
