### ISSUE TITLE
With Origins Port is not explained

### ISSUE THREAD

**Issue by Javaman2** [dotnet/AspNetCore.Docs#18714]
```
                builder.AllowAnyMethod().AllowAnyHeader()
                       .WithOrigins("http://localhost:55830")
                       .AllowCredentials();
```

Is 55830 the front-end port;  which is the same port the main web page is served?  How does, Signalr use the same port as the web page, that's the odd thing. It seems similar to IP tunneling...

Then a section on debugging connection errors would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@Javaman2  you wrote:
> Do not use relative URLs as the asp.net core documentation shows, it makes no sense.

I just deployed the sample to Azure and `var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();` works fine for anyone with my Azure URL.

> Don't mix schemas, if your backend is HTTPs make sure this url schema is indicated.

We recommend never using HTTP, always use HTTPS. I could mention that.

**Comment by Rick-Anderson** [comment]
To close this, add `<xref:security/cors>` to the additional resources section (top).
