### ISSUE TITLE
Document System.Net.Http.Json in "Make HTTP requests..."

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#18716]
With the recent release of [`System.Net.Http.Json`](https://www.nuget.org/packages/System.Net.Http.Json), it might be useful to document how it works in the context of this topic. For example, it'd be useful to show that the following:

```csharp
public async Task<IEnumerable<GitHubIssue>> GetAspNetDocsIssues()
{
    var response = await Client.GetAsync(
        "/repos/aspnet/AspNetCore.Docs/issues?state=open&sort=created&direction=desc");

    response.EnsureSuccessStatusCode();

    var result = await response.Content
        .ReadAsAsync<IEnumerable<GitHubIssue>>();

    return result;
}
```

-can become something like this-:

```csharp
public async Task<IEnumerable<GitHubIssue>> GetAspNetDocsIssues()
{
    return await Client.GetFromJsonAsync<IEnumerable<GitHubIssue>>(
        "/repos/aspnet/AspNetCore.Docs/issues?state=open&sort=created&direction=desc");
}
```

With a `=>` and no `async`/`await`, that can be even less to type, but I didn't want to push it. 😄 

[API Docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json?view=net-5.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@serpent5  great idea, consider adding

The preceding code can be  written more concisely using a [lambda expression](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions):

```
pushing it code here
```
