### ISSUE TITLE
the command is invalid

### ISSUE THREAD

**Issue by koshdim** [dotnet/AspNetCore.Docs#18728]
after running "docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="password" -e ASPNETCORE_Kestrel__Certificates__Default__Path=\https\aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:C:\https\ mcr.microsoft.com/dotnet/core/samples:aspnetapp"

I get

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: %!U(string=is not a valid Windows path)SERPROFILE%!\(MISSING).aspnet\https.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

the guide is either wrong or incomplete
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a good error message, look at your path, it's not valid

**Comment by koshdim** [comment]
sorry, the editor here seems to be cutting the slash. I literally try the command from the article

![image](https://user-images.githubusercontent.com/5932819/84240111-31b01c00-ab06-11ea-926e-e52f38a6c0ff.png)

and the "%USERPROFILE%\.aspnet\https" is a valid path on my machine.

**Comment by GilesC9** [comment]
> sorry, the editor here seems to be cutting the slash. I literally try the command from the article
> 
> ![image](https://user-images.githubusercontent.com/5932819/84240111-31b01c00-ab06-11ea-926e-e52f38a6c0ff.png)
> 
> and the "%USERPROFILE%.aspnet\https" is a valid path on my machine.

I was getting this and found out that it doesn't work in powershell because %USERPROFILE% isn't resolved in powershell you have to use `$env:USERPROFILE`. The command in the docs does work for cmd prompt though. @koshdim
