### ISSUE TITLE
NotifierService should be injected as scoped service not singleton for BlazorServer

### ISSUE THREAD

**Issue by galaldev** [dotnet/AspNetCore.Docs#18721]
In (Invoke component methods externally to update state) section
I think NotifierService should be injected as scoped service not singleton for BlazorServer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @galaldev ... It came in per https://github.com/dotnet/AspNetCore.Docs/pull/16831 after https://github.com/dotnet/AspNetCore.Docs/pull/13974 covered the original scenario without service registrations.

@NTaylorMullen @SteveSandersonMS, should the `NotifierService` for Blazor Server be registered as as scoped?

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state

**Comment by guardrex** [comment]
Ping @NTaylorMullen @SteveSandersonMS 

In ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#invoke-component-methods-externally-to-update-state

... should the `NotififerService` in the Blazor Server example be injected as the topic shows, **Singleton**, or should it be **Scoped** for Blazor Server?

**Comment by NTaylorMullen** [comment]
> Ping @NTaylorMullen @SteveSandersonMS

Going to have to wait for @SteveSandersonMS to respond or maybe @pranavkm @javiercn or @captainsafia knows? A bit outside of my context area.

**Comment by pranavkm** [comment]
Yeah, looks like it should be scoped. Singleton in Server is generally problematic.

**Comment by guardrex** [comment]
Thanks ... I'll update it now.

**Comment by galaldev** [comment]
Thank you for updating it 👍
