### ISSUE TITLE
Most of the links located in left side menu are broken under Web apps > Blazor

### ISSUE THREAD

**Issue by trueway0617** [dotnet/AspNetCore.Docs#18724]
[Enter feedback here]
Left side menu under Web apps > Blazor works fine.
https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1

However if I open the same document in Japanese, the most of the links for "Web アプリ" > "Blazor" is broken and redirected to Docs top page.

For example in English the URL for Web apps > Blazor > Overview is below.
https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1

But in Japanese URL for "Web アプリ" ("Web apps" in Japanese) > "概要" ("Overview" in Japanese) is below.
https://docs.microsoft.com/ja-jp/?view=aspnetcore-3.1

I am able to open the document under Web apps > Blazor by modifying URL from en-us to ja-jp, but it is time consuming to navigate back and force from EN document to JA document and modifying URL each time to view the document.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @trueway0617 ... Yes, I see what you mean.

cc: @JasonCard @scottaddie

**Comment by JasonCard** [comment]
Hi @trueway0617 

Thank you for your feedback.
We are aware of this issue and currently following up.
Will update when resolved.

cc @guardrex @scottaddie

**Comment by guardrex** [comment]
@JasonCard ... This seems to be fixed now. Is that correct?

**Comment by JasonCard** [comment]
@guardrex Most articles were fixed, but I'm still following up on a few files. I also found there was [Blazor ToC updates](https://github.com/dotnet/AspNetCore.Docs/commit/d5b7249fd16715a045d0077d147341d95c7f17bf#diff-eb266db7614fc817a336219e758027af) today, so will need to wait for those updates to be synced in loc repos.

**Comment by guardrex** [comment]
Ok ... Thanks.  There's nothing for me to do here, as this seems to be an internal issue. Is it ok for me to close this, or is it better to leave this open for public tracking or other reason?

**Comment by JasonCard** [comment]
Yes, it's okay to close and I can update when it's all resolved.

**Comment by JasonCard** [comment]
Hi @trueway0617

Thank you again for your feedback.
All affected files have been fixed.
