### ISSUE TITLE
Confusion regarding Claims

### ISSUE THREAD

**Issue by DrGriff** [dotnet/AspNetCore.Docs#18723]
Been reading up on Identity Claims, and came across two Microsoft articles that seemingly conflict:

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1

> A claim is a name value pair that represents what the subject is, not what the subject can do.

https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/managing-claims-and-authorization-with-the-identity-model#claims

> A claim is the expression of a right with respect to a particular value. A right could be something like "Read", "Write", or "Execute."

So in the first example, the claim is about the user's date-of-birth.  It's a fact about the user.  An eCommerce website can take this claim and determine whether the user may buy alcohol.  A games website can take the same claim and determine whether the user may access age-restricted content.  What they can do is determined by the consuming application.

For the second example, the Claim is telling the consuming program what the user can and cannot do, _e.g._ this user may view pricing, but they can not edit it.  Okay, the example is in respect to WCF, but it's still using Claims.

When trying to ascertain "best practice" for Claims, these documents appear to conflict in their approach.  My suggestion would be to update the one that doesn't adhere to Microsoft's current view of "best practice" (which I'm guessing is that the Claim is a "fact" and not a "right").

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25051544-0e4d-1715-95b7-3a8616475127
* Version Independent ID: 50736569-fc04-ec6d-7b33-a3e0c860b1ed
* Content: [Claims-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you open an issue at https://github.com/dotnet/docs/issues ?
