### ISSUE TITLE
HubConnectionBuilder WithURL Relative Path Meaning

### ISSUE THREAD

**Issue by Javaman2** [dotnet/AspNetCore.Docs#18731]
Assume server is running on port 8081
http://localhost:8081/chatHub 

Client is running on port 4200
http://localhost:4200/chatHub

In the code below which url is the relative path referring to? The client or host side?
```
const connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .configureLogging(signalR.LogLevel.Information)
    .build();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
> In the code below which url is the relative path referring to? The client or host side?

Client side, there is no way for the client to magically know the server url unless the script is hosted by that server.

**Comment by BrennanConroy** [comment]
We could add a bit to https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#cross-origin-connections mentioning the need to change the url in the client.

**Comment by Javaman2** [comment]
The pain points were just trying to get it up and running for the first time. If I follow the client examples they do not clearly indicate the URL.  Let me ask why would a relative URL ever be used?  I can't figure out why?  Yet that is exactly what the example shows  @BrennanConroy

**Comment by BrennanConroy** [comment]
The client examples have the client hosted by the server. The browser tells us what url the client came from and we append the path to that url. In your case you are using a different server to host the client, so you need to change the url that the client uses otherwise it'll try to connect to `http://localhost:4200/chatHub` instead of `http://localhost:8081/chatHub`. 

And like I said:
> We could add a bit to https://docs.microsoft.com/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1#cross-origin-connections mentioning the need to change the url in the client.

**Comment by Javaman2** [comment]
`so you need to change the url that the client uses otherwise it'll try to connect to http://localhost:4200/chatHub instead of http://localhost:8081/chatHub.`

That's my point, the examples show relative urls which become :4200 ports, if Angular is running on theat port.  It's not possible to have a hub in Typescript or JavaScript on an Angular port,  as Signalr only supports hub on a server in C#.
