### ISSUE TITLE
How to avoid printing the exception in the console

### ISSUE THREAD

**Issue by mc0re** [dotnet/AspNetCore.Docs#18733]
[Enter feedback here]

The exception handling middleware is a fairly flexible thing. But even before the lambda inside `UseExceptionHandler` is executed, the exception information is printed into the console. Twice. Is there any way to avoid it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Why do you care it's logged to the console twice? Exceptions should be rare.

**Comment by mc0re** [comment]
Currently I'm using the console as my main log :-)  so polluting with many lines it is not to my liking. Maybe there is a flag to switch the standard output off?

**Comment by Rick-Anderson** [comment]
Set the logging level in appsettings.JSON

**Comment by mc0re** [comment]
That'll switch off all console logs. I only want them switched off in the custom exception handler. They are considered unhandled by ASP and printed out, but then they are handled in the exception middleware.
