### ISSUE TITLE
Incorrect Word in Sentence Under "Configure an Email Provider" Section

### ISSUE THREAD

**Issue by brkline** [dotnet/AspNetCore.Docs#18745]
In this section of the document:  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#configure-an-email-provider, there is a sentence that reads 

> The SendGrid account **my** require adding a Sender.

I believe the word should be "may" so the sentence would be "The SendGrid account **may** require adding a Sender."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/18750.
