### ISSUE TITLE
Link to more useful resources

### ISSUE THREAD

**Issue by SirJosh3917** [dotnet/AspNetCore.Docs#18740]
After I completed reading the information, some immediate questions of mine were "How can I make this strongly typed" and "How can I configure this to use a binary format instead of JSON?". It'd be useful to link to these documents, and perhaps many other more general ones so that once someone completes the tutorial, they have other places to turn to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?tabs=visual-studio&view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---
[Associated WorkItem - 65692](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65692)

**Comment by bradygaster** [comment]
cc @IEvangelist as I think he and I could come up with some ideas for next-steps and also, link to his upcoming Learn path once it exists.

**Comment by wadepickett** [comment]
For the scope of this issue, I will add a ## Next steps section with what is available presently and relevant. We can keep adding to that of course as we have more content that would fit.

As we define and discuss additional topics, those would merit their own tracking issues as they come up.  Adding this to my pile for the next sprint.
