### ISSUE TITLE
How to generate proxies?

### ISSUE THREAD

**Issue by Thorium** [dotnet/AspNetCore.Docs#18747]
How do I set hubConfig to `EnableJavaScriptProxies` true?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-gb/aspnet/core/signalr/hubs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Thorium** [comment]
It was so convenient to use the Hubs with Typescript in AspNet.SignalR with `EnableJavaScriptProxies` (...or you could have generate the proxies manually with signalr.exe):

```TypeScript
// Typescript types:
interface ISignalHub extends SignalR { SignalHub : any; }
$.connection.hub.url = "/signalr";
(<ISignalHub>$.connection).SignalHub.server
   .myServerMethod("some parameter").done(function (data) {
        // it just works!
    });
```

Compare the AspNetCore version, so much wizzard-walkthrough, and still not showing is it possibe to call a Hub server side method:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio

**Comment by BrennanConroy** [comment]
There is no equivalent to proxies in ASP.NET Core.

The same code in ASP.NET Core SignalR would look like:
```
connection.invoke("myServerMethod", "some parameter")
    .then(function (result) {
        // code
    });
```

The walkthrough shows calling a method on the server in https://docs.microsoft.com/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio#enable-client-and-server-communication-1

**Comment by bradygaster** [comment]
Closing this per @BrennanConroy's reply.
