### ISSUE TITLE
Documentation not up to date for .Net Core 3.1 Identity

### ISSUE THREAD

**Issue by ThroughTheWind** [dotnet/AspNetCore.Docs#18766]
Hello,

I'm trying to learn how to build Web Apis using built-in Identity feature of .Net Core 3.1.  
It seems the documentation refers to version 3.0 as the following code isn't available in 3.1 :  
`
services.AddDefaultIdentity<ApplicationUser>()
.AddDefaultUI(UIFramework.Bootstrap4)
.AddEntityFrameworkStores<ApplicationDbContext>();
`

It's pretty hard to find documentation of how to reproduce Identity integrated authentication and user registration behavior without using the default bootstrap interface but with consumables endpoints instead.   

I'll keep digging but any advice would be appreciated. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to master issue: Authentication and authorization for SPAs #16406
