### ISSUE TITLE
Adding user sample code clarification

### ISSUE THREAD

**Issue by ps-tb** [dotnet/AspNetCore.Docs#18773]
I created an application based on the sample code that is provided for adding a user after registration is removed. The sample code contains the following line:
```
host.Run();
```
I'd like to know if this line is required? It appears that the `CreateHostBuilder` method is needed in order to create an `IHostBuilder` that is then used to create an `IHost` and access its `IServiceProvider`. After the `IServiceProvider` is accessed, it doesn't appear that `IHost` needs to be `Run` to achieve anything related to adding a user. Is there an alternative use for `Run`ning that isn't apparent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
The `run` method is required for any ASP.NET Core app. You can read a bit more about host setup at https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host#set-up-a-host.

**Comment by ps-tb** [comment]
@scottaddie thanks for the link. In this case, I'm asking specifically about this program because if you keep `Run` in at the end, it doesn't terminate. The goal is to add a new user to the database so after that's done, `Run` is called but the work has been accomplished. My question should have been more specific: Is this non-terminating behavior intended?
