### ISSUE TITLE
Blazor wasm ASP.NET Core hosted app with Azure AD AUTHORIZATION doesn't work for USER DEFINED ROLE

### ISSUE THREAD

**Issue by rubeesh** [dotnet/AspNetCore.Docs#18777]
Blazor wasm ASP.NET Core hosted app with Azure AD AUTHORIZATION doesn't work for USER DEFINED ROLE
Server:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(AzureADDefaults.BearerAuthenticationScheme)
                .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

            services.Configure<JwtBearerOptions>(
                AzureADDefaults.JwtBearerAuthenticationScheme, options =>
                {
                    options.TokenValidationParameters.NameClaimType = "name";
                    options.TokenValidationParameters.NameClaimType = "role";
                });

            services.AddControllersWithViews();
            services.AddRazorPages();
}
```

Client:
``` 
public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddHttpClient("MyApp.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

             builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("MyApp.ServerAPI"));

            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add("861be009-5e73-4c6c-a095-b6e19354f4d7/API.Access");
                options.UserOptions.RoleClaim = "role";
            });

            await builder.Build().RunAsync();
        }
```

User defined role in azure app registration manifest:
```
"appRoles": [
		{
			"allowedMemberTypes": [
				"User"
			],
			"description": "test1",
			"displayName": "test1",
			"id": "d1c2ade8-98f8-45fd-aa4a-6d06b947c66f",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"value": "test1"
		}
	]
```
Even though the CLAIM contains the roles claim , roles base authorization fails:
```
  "roles": [
    "test1"
  ],
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9816eaee-5eff-c3c8-5d58-e2c02c760a00
* Version Independent ID: 60992d09-2a04-1d10-4c85-9642b20ff0e3
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rubeesh ...

Customize the user to convert that `roles` claim JSON array into individual `role` claims. When that JSON array (and the name of the claim changes) from ...

```
"roles": [
    "test1"
  ]
```

... to ...
```
"role": "test1"
```

... it will work.

See: https://docs.microsoft.com/aspnet/core/security/blazor/webassembly/azure-active-directory-groups-and-roles

**Comment by rubeesh** [comment]
fixed
changed 
   options.UserOptions.RoleClaim = "role";
to
    options.UserOptions.RoleClaim = "roles";
