### ISSUE TITLE
Terms that should not be localized

### ISSUE THREAD

**Issue by JasonCard** [dotnet/AspNetCore.Docs#18771]
This article contains terms that should not be localized and some of those are being over-localized: 
- Reserved keywords in headings (e.g. "@try, catch, finally")
- Reserved keywords in bulleted lists (under headings "Razor reserved keywords")
- Directory structure in bulleted list (under heading "Inspect the Razor C# class generated for a view") 
It would be great if those terms can be blocked from localization by using either in-line code, or [no-loc custom syntax](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#non-localized-strings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JasonCard** [comment]
@Rick-Anderson Thank you for the quick fix on the reserved keywords!
There are also directory structures (folder names) in bulleted list under the heading "Inspect the Razor C# class generated for a view" that are being over-localized. 
Could you please also take a look at those?

**Comment by Rick-Anderson** [comment]
@JasonCard  sorry I missed that. Fixed in #18787

**Comment by JasonCard** [comment]
Thank you again for the quick fix!
