### ISSUE TITLE
Service start timeout issue for self-hosted webserver as windows service

### ISSUE THREAD

**Issue by engfro** [dotnet/AspNetCore.Docs#18779]
Hi - working on this .netcore 3.1 project where we are hosting a self-contained webserver (http.sys w/windows auth) as a windows service. For the most part startup seems to be working fine, but we sometimes see this 30sec timeout issue during windowsservice-startup and have a hard time figuring out what is causing this behavior. We also have several "normal" .net framework 4.7.2 windows services, but they don't seem to suffer from the 30sec startup issue as the .net core one do.

The project is a pretty simple one, almost just out of the online docs. Contains 1 simple controller talking to a webapi backend. Hoping for any pointers in what could be causing this startup issue.

Windows Error Reporting is enabled, but it hasn't registered any crashdumps yet for the application when the timeout issue occurs. 

[ProgramStartupFiles.zip](https://github.com/dotnet/AspNetCore.Docs/files/4770632/ProgramStartupFiles.zip)

**Comment by guardrex** [comment]
Hello @engfro ... Open this for engineering at ...

https://github.com/dotnet/aspnetcore/issues

... but attaching the ZIP is no good for them. They don't usually have the time to look at developer projects in that format. You can put a simple repro project up on GH and then cross-link the repo to your issue.

**Comment by engfro** [comment]
I understand. I created this simple GitHub project https://github.com/engfro/WebFrontend which for the most part reflects our current setup.
The problem seems to be that hostBuilder.Build(); can't finish it's execution within the default 30sec windows service startup intervall
