### ISSUE TITLE
Blazor transient disposables

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18786]
Can you add details about how to detect incorrect usages?

Sample is here:
https://github.com/javiercn/BlazorServerTransientDisposable

WebAssembly detector:
https://github.com/javiercn/BlazorServerTransientDisposable/blob/master/BlazorApp1/Program.cs
https://github.com/javiercn/BlazorServerTransientDisposable/blob/master/BlazorApp1/DetectIncorrectUsagesOfTransientDisposablesWebAssembly.cs
Blazor server detector:
https://github.com/javiercn/BlazorServerTransientDisposable/blob/master/BlazorServerTransientDisposable/Program.cs#L24
https://github.com/javiercn/BlazorServerTransientDisposable/blob/master/BlazorServerTransientDisposable/DetectIncorrectUsagesOfTransientDisposables.cs

**Comment by oatsoda** [comment]
Hmm, so the detection code finds that `BaseAddressAuthorizationMessageHandler` and `AuthorizationMessageHandler` are both `IDisposable` registered as `Transient`...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly.Authentication/src/WebAssemblyAuthenticationServiceCollectionExtensions.cs#L43-L44
