### ISSUE TITLE
Component Tag Helper

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#18799]
I modified my existing Razor pages app to support Blazor components.
Among other instructions, this must be done:
[Component Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-3.1
)
However, I get the following error while assigning the Layout:
![Capture](https://user-images.githubusercontent.com/38800605/84582712-0892d280-ae09-11ea-8535-c74b6b8c88b8.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c1a41f-0615-ef27-f9a3-032b9db702a3
* Version Independent ID: 8ac3492b-34dd-d94e-e661-c3028ca2acdb
* Content: [Component Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/component-tag-helper?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/component-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dajma00 ... "{APP ASSEMBLY}" is a placeholder. Replace that with the app's assembly name.

> Among other instructions

What instructions? Are you following ...

https://docs.microsoft.com/aspnet/core/blazor/integrate-components

**Comment by guardrex** [comment]
The line that tells the reader about the placeholder is too far down the topic.

I'll move it up and probably put it in a few spots where example code is shown.

**Comment by dajma00** [comment]
> Hello @dajma00 ... "{APP ASSEMBLY}" is a placeholder. Replace that with the app's assembly name.
> 
> > Among other instructions
> 
> What instructions? I assume you followed the guidance in the following topic first ...
> 
> https://docs.microsoft.com/aspnet/core/blazor/integrate-components

Oh.... totally missed that. 

I used the following link to include Blazor in Razor:
[Integrate ASP.NET Core Razor components into Razor Pages and MVC apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/integrate-components?view=aspnetcore-3.1#render-components-from-a-page-or-view)

**Comment by dajma00** [comment]
> The line that tells the reader about the placeholder is too far down the topic.
> 
> I'll move it up and probably put it in a few spots where example code is shown.

I totally missed that. And I wonder why Visual Studio doesn't complain...
Yes, moving that comment up should  help.

**Comment by dajma00** [comment]
> The line that tells the reader about the placeholder is too far down the topic.
> 
> I'll move it up and probably put it in a few spots where example code is shown.

@guardrex Please replace the placeholder text with something like "Replace-with-your-assembly-name". That way even if you miss the comment, we would know what to do.

**Comment by guardrex** [comment]
We can't really use language like that in the code. The code isn't translated into other languages. What I'll do is move the note up on the placeholder and perhaps change what it says a bit.
