### ISSUE TITLE
Authentication service support should be better detailed

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18791]
I moved this from here: https://github.com/dotnet/AspNetCore.Docs.it-it/issues/54
@ciacco85 commented 10 hours ago
Authentication service support should be better detailed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9816eaee-5eff-c3c8-5d58-e2c02c760a00
* Version Independent ID: 60992d09-2a04-1d10-4c85-9642b20ff0e3
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/blazor/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ciacco85 ... I'm not aware of any additional detail that should be covered here. You would need to be more specific about what you think is missing.

`UseAuthentication` and `UseAuthorization` and other security concepts are covered in more detail in the ASP.NET Core docs starting at ...

https://docs.microsoft.com/aspnet/core/security/

... and in the linked additional resources at the bottom of this topic.
