### ISSUE TITLE
Missing link to content helper

### ISSUE THREAD

**Issue by bgever** [dotnet/AspNetCore.Docs#18804]
> To return plain text formatted data, use Content and the Content helper:

The Content helper link links to the same Content object instead of the Content method on Controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  you know about https://xrefgen.azurewebsites.net/?handler=GetSearchResults to get `xref:` links, right?

Applied `GII` label

**Comment by bgever** [comment]
Thank you @serpent5 & @Rick-Anderson 👍
