### ISSUE TITLE
Load Testing Guidance

### ISSUE THREAD

**Issue by ardalis** [dotnet/AspNetCore.Docs#18809]
Microsoft has discontinued their Azure DevOps load testing: 
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

It would be good if this docs article actually has some useful, practical information on writing and running load tests for ASP.NET Core apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce92350f-25e5-63bc-c815-a8a41b2253c3
* Version Independent ID: e8f9ec21-4e0a-054e-b9ba-fd27e71e31a0
* Content: [ASP.NET Core load/stress testing](https://docs.microsoft.com/en-us/aspnet/core/test/load-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/load-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/load-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Jeremy-Meng
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Jeremy-Meng please review.
