### ISSUE TITLE
How to access via ip address

### ISSUE THREAD

**Issue by godshades** [dotnet/AspNetCore.Docs#18805]
Hi I was doing same as tutorial, now it can run on localhost:5000, but when I access via ip 192.168.1.X:5000 => refuse connection

What I need to do
I'm using centos7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by Rick-Anderson** [comment]
You need to use local host or deploy.

**Comment by godshades** [comment]
@Rick-Anderson this mean I can't make it access via ip address ?

**Comment by Rick-Anderson** [comment]
Not using LocalHost
