### ISSUE TITLE
No response after clicking the previous tutorial

### ISSUE THREAD

**Issue by CeciAc** [dotnet/AspNetCore.Docs#18817]
The comments below were machine-translated (the issue replicates in all locales)

@IDAmosWang commented on [Sat Jun 13 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/280)

Click at the end of the page
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [ASP.NET Core 中的 Razor 页面和 EF Core - CRUD - 第 2 个教程（共 8 个）](https://docs.microsoft.com/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

@Rick-Anderson commented on [Sun Jun 14 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/280#issuecomment-643714538)

Clicking at the end of the page does not respond to the previous tutorial

Transfer to https://github.com/dotnet/AspNetCore.Docs/issues

---

@srvbpigh commented on [Sun Jun 14 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/280#issuecomment-643728422)

Hello, @IDAmosWang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@Rick-Anderson commented on [Sun Jun 14 2020](https://github.com/dotnet/AspNetCore.Docs.zh-cn/issues/280#issuecomment-643823894)

@CeciAc bug on our side, Transfer to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by Rick-Anderson** [comment]
@serpent5  see [bottom of tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1#next-steps)
note GII label

**Comment by serpent5** [comment]
@Rick-Anderson I guess I might be missing something here, but clicking on the "Previous tutorial" at the bottom takes me to https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro.

**Comment by Rick-Anderson** [comment]
@serpent5  you're right, it's only the https://docs.microsoft.com/zh-cn/aspnet/core/data/ef-rp/crud?view=aspnetcore-3.1 that has that problem.
