### ISSUE TITLE
Please provide a JS client sample instead of .Net client Console app

### ISSUE THREAD

**Issue by BenHayat** [dotnet/AspNetCore.Docs#18823]
[EDIT by guardrex to add the metadata]

Hello team;
Now that the gRPC is GA, could you update the docs to show how to generate ProtoBuf for JS client, i.e. Vue and also how to create Js client to comunicate a .Net Core gRPC server?

https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio

Thanks!
..Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
Hello @BenHayat ... Please use the **This page** feedback button+form at the bottom of a topic to add metadata to the issue automatically. No worries on this one ... I'll add it manually.

**Comment by BenHayat** [comment]
> 
> 
> Hello @BenHayat ... Please use the **This page** feedback button+form at the bottom of a topic to add metadata to the issue automatically. No worries on this one ... I'll add it manually.

I did. That how it brought me to page.
Go try it yourself.

**Comment by guardrex** [comment]
Not sure what happened ... you should see the metadata in the opening comment ...

<img width="687" alt="Capture" src="https://user-images.githubusercontent.com/1622880/84845767-f71d1680-b012-11ea-863a-c1734a29b6ce.PNG">

**Comment by BenHayat** [comment]
> 
> 
> Not sure what happened ... you should see the metadata in the opening comment ...
> 
> <img alt="Capture" width="687" src="https://user-images.githubusercontent.com/1622880/84845767-f71d1680-b012-11ea-863a-c1734a29b6ce.PNG">

My fault. I accidentally deleted it. Sorry!

**Comment by JamesNK** [comment]
There are many platforms supported by gRPC (10+) and providing documentation with how to crease each isn't realistic.

If you want to see how to use gRPC from a Node app then you should view that gRPC platform's documentation.
