### ISSUE TITLE
Conditionally enable runtime compilation

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#18824]
See https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0&tabs=visual-studio#conditionally-enable-runtime-compilation

Why do we need `#if DEBUG` ?

see https://stackoverflow.com/a/56042266/502537

cc @serpent5 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0&tabs=visual-studio#conditionally-enable-runtime-compilation)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I think this is already covered in the topic as it stands today:

> Conditionally enabling in this manner ensures that the published output:
>
> - Uses compiled views.
> - Doesn't enable file watchers in production.

What do you think?

**Comment by Rick-Anderson** [comment]
agreed
