### ISSUE TITLE
Text and example needs better explanation

### ISSUE THREAD

**Issue by surenazatyan** [dotnet/AspNetCore.Docs#18826]
This section would benefit from more elaborate explanation. "Don't create components that write to their own parameter properties". The point what I understand is to keep the state in private fields instead of setting public properties that should be set from outside, but the given example and explanation does not exactly illumniate the "why" or it is not apparent from given code and its results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be4c4d0c-149c-bde1-c7fa-f082916390ca
* Version Independent ID: 9d945996-ad02-bd4b-58ea-c465cc5cc74c
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @surenazatyan ... It's explained fully in the linked section :point_right: https://docs.microsoft.com/aspnet/core/blazor/components#dont-create-components-that-write-to-their-own-parameter-properties

**Comment by surenazatyan** [comment]
Hello @guardrex , I agree that the linked section has explanation with examples, and the most relevant text that explaines it goes like this "To maintain state in the preceding scenario, use a private field in the Expander component to maintain its toggled state.". And it works like a charm. But, what is not apparent is - why the private fields preserve their state in the face of parent being rerendered by calling StateHasChanged() ? Refering to an explanation on how parent/child rerendering and fields/states lifecycle work is what would have helped alot to fully internalize the inner workings of components lifecycle and state. Btw lifecycle document does not address this question either.

**Comment by guardrex** [comment]
I don't think that's the explanation line. It's this ...

> Parameters are reset because the parent component rerenders when `StateHasChanged` is called and new parameter values are supplied to the child component.

i.e., **Parameters** are reset, **private fields** obviously can't be reset like that. A parent can't overwrite the value of a field in a child.

The current text seems good.

WRT ...

> fully internalize the inner workings of components lifecycle and state

Dan Roth has mentioned that at https://github.com/dotnet/AspNetCore.Docs/issues/16287, so we'll see what he wants to do on it at some point.
