### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by ta1H3n** [dotnet/AspNetCore.Docs#18822]
`Don't add the HSTS header or chose an appropriate max-age if HTTPS will be disabled in the future.`
chose -> choose.

The grammar of the sentence is also confusing. Maybe change or -> nor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think it should be 
If HTTPS will be disabled in the future, use one of the following approaches:

* Don't add the HSTS header.
* Choose an appropriate `max-age` for ...

cc @serpent5  and note the `GII` label.
