### ISSUE TITLE
Following your tutorial verbatim, there isn't a startup class.

### ISSUE THREAD

**Issue by sjk2243** [dotnet/AspNetCore.Docs#18832]
[EDIT by guardrex for content. I understand your frustration @sjk2243, but let's plz keep it civil. I'm sure whatever the problem is that it's something that can be explained or addressed in the topic with a PR.]

For [...] sake, do you people even try with these tutorials? I don't know that I've ever used your documentation once where it hasn't produced more problems than it solved. AND YOU"RE THE ONES WHO OWN THE SOFTWARE. Jesus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sjk2243  we had over a million folks report success, and yes, there is a startup class generated.
