### ISSUE TITLE
Error, DbContext not recognized in Startup.cs

### ISSUE THREAD

**Issue by samira-ouraga** [dotnet/AspNetCore.Docs#18839]
Here is the error I see when following the tutorial. I can't move on the next steps of the tutorial.
{
	"resource": "/c:/NET Tutorial/RazorPagesMovie/Startup.cs",
	"owner": "csharp",
	"code": "CS0246",
	"severity": 8,
	"message": "The type or namespace name 'MovieContext' could not be found (are you missing a using directive or an assembly reference?) [RazorPagesMovie]",
	"source": "csharp",
	"startLineNumber": 33,
	"startColumn": 39,
	"endLineNumber": 33,
	"endColumn": 51
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
