### ISSUE TITLE
Argument 2: cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action'

### ISSUE THREAD

**Issue by captmomo** [dotnet/AspNetCore.Docs#18833]
Hi,

I"m trying to configure my options. I'm trying to use the same method in the docs, but I get the error:  
  
`Argument 2: cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action'`

My code:

```
public static IServiceCollection AddCustomOptions(this IServiceCollection services, IConfiguration configuration)
        {
            services.Configure<CommonSettings>(configuration.GetSection(nameof(CommonSettings)));
            return services;
        }
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by captmomo** [comment]
Sorry! Realised I needed to include the package "Microsoft.Extensions.Options.ConfigurationExtensions"

**Comment by xela-trawets** [comment]
Ha! was looking for this too. 
It is hard to search for packages that contain missing extension methods.

**Comment by scuba6388** [comment]
Same here.  Documentation for extensions is lacking to put it very nicely.  I keep running into issues like this and tracking them down is very difficult.
