### ISSUE TITLE
Provide more information about react with ASP.NET

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/AspNetCore.Docs#18851]
I've created an app from the ASP.NET Core MVC. After playing around for some time, I decided to use React in it. I couldn't find how to do that in the documentation. It only talks about creating a new app from react template.

I think there should be a way to add react support in the app created from another template that worth to be documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Youssef1313** [comment]
I'm also getting the following error when trying to run a newly created asp.net with react app:

```
AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was: 'rimraf' is not recognized as an internal or external command,
```

It's just the default template. If there are any additional steps required to run it, it should be mentioned in the article.

**Comment by Rick-Anderson** [comment]
Moved to Master issue: Use the React project template #16209
