### ISSUE TITLE
[Blazor] Add section on configuring a GRPC service to be used with Blazor Webassembly and auth

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#18850]
Main piece on configuring the client is [here](https://github.com/javiercn/BlazorGrpcAuth/blob/master/BlazorGrpcAuth/Client/Program.cs#L30-L37) and the repo contains all the details.

**Comment by guardrex** [comment]
@javiercn In your sample app, you have the *greeter.proto* file in a *Contracts* folder of **both** the `Server` project **and** the `Shared` project. Is that by-design?

**Comment by javiercn** [comment]
@guardrex the one on the server project is a mistake. It should be linked from the shared folder.
