### ISSUE TITLE
Clarify that the casing is important for Todo.razor file name

### ISSUE THREAD

**Issue by leahtmsft** [dotnet/AspNetCore.Docs#18852]
In user studies, we saw that some users accidentally named the file `todo.razor`, which resulted in compilation errors. We should clarify that casing is significant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Build your first Blazor app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @leahtmsft ... It's documented in the second paragraph of the *Components* topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.1#component-classes

... and I'll add a quick bit to the tutorial to surface it there. Thanks for the note.
