### ISSUE TITLE
Steps to be done by the VS tooling itself

### ISSUE THREAD

**Issue by hcanand** [dotnet/AspNetCore.Docs#18858]
The steps to include the relevant *.razor pages and startup modification should be automatically done by the VS tools/Templates itself. this will prevent developer from having to do these manually and/or reduce potential errors.
![to be generated by the tooling](https://user-images.githubusercontent.com/17921466/85103645-b5fc5080-b224-11ea-84f3-8f7ba22ae37d.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b02665-c8ab-bd91-8057-3b07b4e238d3
* Version Independent ID: e4f176f5-0b94-d532-53d5-cffce437961a
* Content: [ASP.NET Core Razor components class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/class-libraries?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hcanand ... Please open an issue for product unit feedback directly with the product unit. We only work on docs here. Open this issue here 👉 https://github.com/dotnet/aspnetcore/issues
