### ISSUE TITLE
Could you elaborate more for the following statement?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#18856]
>Specifying an event type in the method call is only necessary if the event type is used in the method.

I don't understand the statement without an example in code. Could you elaborate more with code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3de31c7e-7895-9d7c-0d9a-5bdfe83b60a9
* Version Independent ID: 334b7206-d383-40c3-b346-b54df9d87293
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pstricks-fans ... Yes, I can make an improvement. It means what it says, but it would be good to use the word "optional" there. Specifying an event type is **_optional_**. That's all that it's trying to say.

**Comment by pstricks-fans** [comment]
What does "Specifying a event type in the method call" mean in code?

How can we specify an event type in the method call? Did you mean "specifying an argument in event handler method call"?

**Comment by pstricks-fans** [comment]
I have a shared component named `Earth.razor` 

    <div>
        <button @onclick=@(() =>OnStop.InvokeAsync(DateTime.Now))>
            Stop Spinning
        </button>
    </div>
    
    @code
    {
        [Parameter]
        public EventCallback<DateTime> OnStop { get; set; }
    }


I use the `Earth.razor` in my `Index.razor` page as follows.

    @page "/"
    
    The earth stopped spinning at @(dt.ToString("hh:mm:ss")).
    
    <Earth OnStop=StopHandler1 />
    
    <Earth OnStop=StopHandler2 />
    
    @code{
    
        private DateTime dt = DateTime.Now;
        private void StopHandler1()
        {
            this.dt = DateTime.Now;
        }
    
        private void StopHandler2(DateTime dt)
        {
            this.dt = dt;
        }
    }


Here `OnStop` event of type `EventCallback<DateTime>` can be assigned either `StopHandler1` and `StopHandler2` which have different signatures.

**Comment by guardrex** [comment]
> Does it mean that an event of type `EventCallback<DateTime>` can be assigned many different event handlers regardless of their signatures?

> Did you mean "specifying an argument in event handler method call"?

No, this statement only applies to `EventArg` types shown in the [Event argument types](https://docs.microsoft.com/en-us/aspnet/core/blazor/event-handling?view=aspnetcore-3.1#event-argument-types) section.

WRT to the statement itself ...

It also doesn't say "parameter." It should say "optional" and "parameter."

> Specifying an event parameter in the method call is optional and only necessary if the event type is used in the method.

```csharp
private async Task UpdateHeading(MouseEventArgs e) { ... }
```

... or ...

```csharp
private async Task UpdateHeading() { ... }
```

`MouseEventArgs` is an optional parameter. You only need it if you're going to use it in the method.

**Comment by guardrex** [comment]
Well .... 🤔 ..... actually .......... I'll need to look closer at this when I get to this issue. An "optional parameter" is a **_real thing_**, so I need to make sure that I'm not overloading the term inappropriately.

**Comment by pstricks-fans** [comment]
Thank you very much.

**Comment by guardrex** [comment]
Leave this open. I can't work the issue if it's closed. 😉😄
