### ISSUE TITLE
Move Blazor WASM perf topic to Fundamentals node

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18864]
Per https://github.com/dotnet/AspNetCore.Docs/pull/18831#discussion_r441931906 ...

> I made only a comment regarding moving the WASM perf best practices under fundamentals.
Maybe we should do this change first and then follow-up with a separate change for that, if necessary. @danroth27 thoughts?

Note: This is a little bit of a break from the doc set at large. We keep perf separate from fundamentals in the main ToC.

cc: @mkArtakMSFT ... I'll place this issue on HOLD until the decision is made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679bec37-eb9b-8092-5b99-118e4f2eb1a1
* Version Independent ID: 710987ea-42fb-1306-5750-ff8956907748
* Content: [ASP.NET Core Blazor WebAssembly performance best practices](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/webassembly-performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @pranavkm
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mkArtakMSFT ... Are you still interested in doing this? It's a break from the approach taken for ASP.NET Core docs ... i.e., performance **_isn't_** considered a "fundamental" concept the way the topics are laid out today.

**Comment by guardrex** [comment]
I guess we'll continue with things as they are. Let me know if you want this one re-opened for work. :ear:

**Comment by mkArtakMSFT** [comment]
we should be consistent for sure. Let's wait and listen to the community feedback before making any changes here.
