### ISSUE TITLE
Which version of .netstandard does Blazor support

### ISSUE THREAD

**Issue by operationslazlo326** [dotnet/AspNetCore.Docs#18867]
The page states, "Blazor implements .NET Standard 2.0." but Blazor project templates target 2.1.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @operationslazlo326 ... It was 2.0 during Blazor WebAssembly's preview, and we didn't say "or later" because 2.1 wasn't released until September IIRC. I'll adjust it.
