### ISSUE TITLE
TabSet.SetActivateTab should, maybe, be SetActiveTab

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#18865]
The `TabSet`'s `SetActivateTab` method doesn't read how I'd expect. Should it be `SetActiveTab`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7ba96d-bae0-96ee-e76a-71c6e5f4c23f
* Version Independent ID: 5fe884b8-51e1-1b91-57f8-522ff0b7890c
* Content: [ASP.NET Core Blazor cascading values and parameters](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/cascading-values-and-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @serpent5 ... Possibly/probably so. I'll take a look at this on Monday **_-ish_**. I'm **_buried_** in localization updates on https://github.com/dotnet/AspNetCore.Docs/issues/18372 right through the weekend. ⛏️⛰️😅

**Comment by serpent5** [comment]
Sure, no worries. I'm happy to patch it up if you like, but of course it's fine if not.

**Comment by guardrex** [comment]
![big_trouble](https://user-images.githubusercontent.com/1622880/85146885-b3ddc600-b213-11ea-9306-473da0bc2efd.png)

*Sit tight, hold the fort and keep the home fires burning. And if I'm not back by Monday ... call the president.*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&mdash; Jack Burton ([Kurt Russell](https://www.imdb.com/name/nm0000621/)), [Big Trouble in Little China](https://www.20thcenturystudios.com/movies/big-trouble-in-little-china), &copy;1986 [20th Century Fox](https://www.20thcenturystudios.com/)

**Comment by guardrex** [comment]
Well, I was too curious to wait for an investigation.

This goes way, way ... **_WAY_** back 👴. It's been like this since ancient Blazor times ... **_two years ago_** 😄. I don't recall naming it that way. I'm not sure if I had a reason or if another wonderful 🙈 **_find-'n-replace debacle_** 🙈 did this in ancient times.

Whatever the case, *yeah!* ... I think ur right @serpent5. Go ahead if you want to and fix it up. It should be in both the WASM and Server common sample apps. Fortunately, it's not in the text of the topic, so no changes needed there.

**Comment by serpent5** [comment]
@guardrex Yeah, like you said in your most recent edit, the example works properly as it is. It probably wasn't worth reporting.

**Comment by guardrex** [comment]
I think it's worth changing tho. It sounds funky like that. I'll take care of it.

**Comment by serpent5** [comment]
Ok, sorry. I was more than happy to do it, but after your edit I didn't feel like it was really significant. Sorry about closing this, then. I will just leave you to take care of it now to save the back and forth.
