### ISSUE TITLE
Update approach used for antiforgery in "Integration tests in ASP.NET Core"?

### ISSUE THREAD

**Issue by martincostello** [dotnet/AspNetCore.Docs#18860]
[EDIT by guardrex to add the metadata]

As part of some recent application work I needed to get antiforgery tokens to submit with POST requests as part of integration testing with `WebApplicationFactory<T>`. However, I wasn't happy with the need to load pages and parse the HTML, so I came up with a different approach using Application Parts to inject a controller into the app that could be used to make JSON requests to get the required values. I've written it up on [my blog](https://blog.martincostello.com/integration-testing-antiforgery-with-application-parts/) and also provided some [sample code](https://github.com/martincostello/antiforgery-testing-application-part).

Would you be interesting in me making some updates to the [page (see text after item 3)](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory) to suggest such an approach, rather than HTML scraping with libraries such as AngleSharp, or would you prefer it be left as-is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's an interesting approach @martincostello, but the product unit discussed and debated what the topic suggests when it was drafted and firmly decided to go this way. I was in the *plz don't pick a winner camp* because I think it can stifle innovation. However, they felt it was the best approach. 

We don't have the staffing to perform the updates that you recommend for the foreseeable future. Let me ask you this ... **_IF_** engineering said "ok, yes, a section describing this would be nice" would **_YOU_** be willing to contribute the content for it? If so, then we can ask and see. If not tho, I think we should close this because it will sit forever and never be addressed (probably) given the workload here.

**Comment by guardrex** [comment]
btw - Please open new issues using the **This page** feedback button+form at the bottom of the topic. It will add the metadata to the issue. No worries tho ... I'll manually add it now.

**Comment by martincostello** [comment]
@guardrex Sorry about that - I started by pressing the edit button, but then changed my mind and thought I'd ask in an issue first.

I'm happy to have a go at updating the guidance myself and contributing something for review, if it's welcome to be revisited and updated at the high-level I've suggested.

If engineering would rather leave it as-is, then no worries and I'll this close this. Thanks!

**Comment by guardrex** [comment]
@javiercn :point_up: @martincostello is pitching an interesting approach for the Integration Testing topic and willingness to write a section for the topic ...

> using Application Parts to inject a controller into the app that could be used to make JSON requests

Just need to know from you if he should go to the trouble of submitting a PR for a draft section?

**Comment by javiercn** [comment]
@guardrex I'll have to think about it a bit. Doesn't sound very problematic though, let me sleep on it a bit and I'll share my thoughts.

**Comment by guardrex** [comment]
It seems step away from **_testing the app's own code_**, thus it may be a step away from a proper integration test **_of the SUT_**. However, I might not understand the scenario/use case well enough.

**Comment by mkArtakMSFT** [comment]
We've discussed this internally and we think that the proposed approach is really good. @martincostello please go ahead and propose changes with your approach.

**Comment by martincostello** [comment]
Thanks @mkArtakMSFT - I'll look at coming up with a draft in the next few weeks 👍

**Comment by Rick-Anderson** [comment]
@martincostello any chance you could come up with a draft?

**Comment by martincostello** [comment]
Sure - sorry I've not done it already, this is one of this things that's been continuously sat at the bottom of my todo pile for like a year being overtaken by other things.

I'll try and put something together over the December/holiday lull.

**Comment by martincostello** [comment]
Sorry for taking so long to properly look at this... 🙈

Looking through the sample app that goes with the content properly, it seems to sort of be doing headless HTML navigation of the app generally with the tests, so on reflection it makes sense to handle the antiforgery the same way. Otherwise it'd be a mix and match of two different approaches that might look a little odd.

I think the approach I originally suggested makes more sense if you're just testing the endpoints backing the forms directly at a lower-level, without caring about how they render in the browser. Still not unit tests, but considering the back-end as a black box, rather than the _app_ as a block box including the HTML.

I've updated the [sample repo](https://github.com/martincostello/antiforgery-testing-application-part#readme) from my original blog post for .NET 6, so instead of restructuring the content wholesale (as I think it would only make sense as sort of rewrite otherwise), would you instead consider taking a smaller update to the content [here](https://github.com/dotnet/AspNetCore.Docs/blob/b7e17431779fbbabe5ee29d52e932776af955963/aspnetcore/test/integration-tests.md?plain=1#L224) to add a link to the sample repo and/or the blog post for the approach suggested in the final sentence?

> Another approach is to write code to handle the antiforgery system's request verification token and antiforgery cookie directly.

**Comment by Rick-Anderson** [comment]
> I've updated the [sample repo](https://github.com/martincostello/antiforgery-testing-application-part#readme) from my [original blog post](https://blog.martincostello.com/integration-testing-antiforgery-with-application-parts/) for .NET 6, so instead of restructuring the content wholesale (as I think it would only make sense as sort of rewrite otherwise), would you instead consider taking a smaller update to the content [here](https://github.com/dotnet/AspNetCore.Docs/blob/b7e17431779fbbabe5ee29d52e932776af955963/aspnetcore/test/integration-tests.md?plain=1#L224) to add a link to the sample repo and/or the blog post for the approach suggested in the final sentence?

Yes.

**Comment by Rick-Anderson** [comment]
@jvandertil would you be able to apply the suggestions here to your code at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/test/integration-tests/IntegrationTestsSample

**Comment by Rick-Anderson** [comment]
> @jvandertil would you be able to apply the suggestions here to your code at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/test/integration-tests/IntegrationTestsSample

Nevermind, fixed in [this commit](https://github.com/dotnet/AspNetCore.Docs/pull/27215/commits/822f3193cb03d32524d4a80a0e49b13ce2c12fa5)
