### ISSUE TITLE
Add common anti-patterns samples and outcomes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#18869]
There are a set of patterns that can cause bad behavior when using the DI container (I reference some of them in my talk here https://youtu.be/x-C-CNBVTaY?t=1628 code samples here 
 https://github.com/davidfowl/NDCLondon2017/blob/417394eaa2c764eb9ed85b64a1dde0574068eea2/DependencyInjectionDemos/Program.cs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#design-services-for-dependency-injection)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/docs/issues/21229
