### ISSUE TITLE
InvalidOperationException: The view 'Index' was not found.

### ISSUE THREAD

**Issue by BramKreuger** [dotnet/AspNetCore.Docs#18861]
I'm completely new to MVC, but when I follow the tutorial (MVC part 3, views) I get the following error:

InvalidOperationException: The view 'Index' was not found. The following locations were searched: /Views/HelloWorld/Index.cshtml /Views/Shared/Index.cshtml

What am I doing wrong?

Thanks

**Comment by guardrex** [comment]
Hello @BramKreuger ... Would you please re-open this issue using the **This page** feedback button and form at the bottom of the topic? It will create this issue with metadata for tracking and automatically ping the author ...... *you'll get a faster response*.
