### ISSUE TITLE
Comments in JSON files and localization?

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18882]
The JSON spec doesn't permit comments, and we've been moving away from unlocalized comments in code/data files anyway. Should the comments in the JSON files of this topic be moved to the text?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It doesn't disallow them either. Visual Studio editor recognizes them.
Can you provide content, screen shot?

**Comment by guardrex** [comment]
Nevermind. I can see where this is going. :smile:
