### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by smartprogrammer93** [dotnet/AspNetCore.Docs#18884]
[Enter feedback here]
in this section
IIS can be configured via web.config to serve Brotli or Gzip compressed Blazor assets. For an example configuration, see web.config.

web.config link is broken : https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly/_samples/web.config?raw=true&view=aspnetcore-3.1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#brotli-and-gzip-compression)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by smartprogrammer93** [comment]
i really want to know the info tho, because i am deploying my blazor application. and the server is serving uncompressed files

**Comment by guardrex** [comment]
Thanks @smartprogrammer93 ... The correct link is ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config

I'll patch that right now.

**Comment by smartprogrammer93** [comment]
omg thank you @guardrex

**Comment by guardrex** [comment]
Here's the link for the raw file contents ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly/_samples/web.config?raw=true
