### ISSUE TITLE
Wrong configuration example for logging

### ISSUE THREAD

**Issue by wsy** [dotnet/AspNetCore.Docs#18880]
This document, under "Configure logging" section, the second json example.
As I understand it, "EventSource" should be something under the "Logging" scope. However, in your code, it's under "Debug" scope. See screenshot below.

![image](https://user-images.githubusercontent.com/2684991/85215532-b0317700-b3ac-11ea-8ba4-8b15bb64587a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It is under logging, it's at the same level as `Debug`

**Comment by Rick-Anderson** [comment]
@wsy thanks for bringing this to our attention and fixing
