### ISSUE TITLE
Example dotnet watch -> Build Failed

### ISSUE THREAD

**Issue by JeroenBos** [dotnet/AspNetCore.Docs#18895]
I wanted to use `dotnet watch` for triggering a `<Target> <Exec Command = "...">`  rather than building/running/testing (the normal usage). I found an example in the docs that shows how to do that. 

Copy/pasting the example gave me the following error:
```
$ dotnet watch build
watch : Started
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Nothing to do. None of the projects specified contain packages to restore.
/home/jeroen/.dotnet/sdk/3.1.300/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/jeroen/git/feedback/x.csproj]

Build FAILED.
```
Now it may very well be that you need the other projects to have the the build succeed, although I can't really infer that from the error message. Is there a way to have a watcher without any test projects or cs files but that just executes a `<Target Name="..."><Exec Command ="..."/><Target/>`?

Steps to reproduce: 
- Open vscode in an empty directory. 
- Copy paste the example verbatim into a file, e.g. `x.csproj`, as in:
```
<Project>
    <ItemGroup>
        <TestProjects Include="**\*.csproj" />
        <Watch Include="**\*.cs" />
    </ItemGroup>

    <Target Name="Test">
        <MSBuild Targets="VSTest" Projects="@(TestProjects)" />
    </Target>

    <Import Project="$(MSBuildExtensionsPath)\Microsoft.Common.targets" />
</Project>
```
- Run `dotnet watch build`

----------

It's the same error if I remove the target with name `Test`, and if I run `dotnet watch msbuild instead, and without the line `TestProjects Include`.
Some versions:
- vscode=1.45.1
- ms-dotnettools.csharp (Omnisharp) 1.22.1
- dotnet version 3.1.300
- Ubuntu 18.04.3
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3163f-1903-f2c7-8909-d34f917944bf
* Version Independent ID: 55aae418-9d32-5b2b-1df7-5e4e76313ec4
* Content: [Develop ASP.NET Core apps using a file watcher](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/dotnet-watch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a pretty good error message. Why is it referencing .NET 4x? .NET Core 3.x doesn't support .NET 4x.

**Comment by JeroenBos** [comment]
> That's a pretty good error message. Why is it referencing .NET 4x?

I don't know why it's referencing .NET 4x. In fact that's the reason why I think this error message is so strange. 

> The sample download is .NET Core 2.0 which is out of support.

Actually, the sample is not from .NET  Core 2.0, but from 3.1. Specifically from the bottom of this page: `https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-3.1`.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
