### ISSUE TITLE
Trace is listed as "Trace " instead of "Trace"

### ISSUE THREAD

**Issue by oneEyedSunday** [dotnet/AspNetCore.Docs#18896]
LogLevel.Trace is listed as "Trace " instead of "Trace"  [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1&source=docs#configure-logging)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1&source=docs)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Extra whitespace? Where?

**Comment by oneEyedSunday** [comment]
A few sections below [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1&source=docs#configure-logging)

**Comment by Rick-Anderson** [comment]
`Microsoft.Hosting": "Trace " // Debug:Microsoft.Hosting category.
      },`

**Comment by oneEyedSunday** [comment]
Yes that

**Comment by Rick-Anderson** [comment]
Fixed  in #18881
Thanks for bringing this to our attention.
