### ISSUE TITLE
External links

### ISSUE THREAD

**Issue by agap2-ag** [dotnet/AspNetCore.Docs#18899]
The _globbing_ patterns link seems to be down (Europe):
https://www.tldp.org/LDP/abs/html/globbingref.html

And the _configuration options_ links:

- [CSS Minifier](https://github.com/madskristensen/BundlerMinifier/wiki/cssminifier) mentions no configuration options for CSS;
- [HTML Minifier](https://github.com/madskristensen/BundlerMinifier/wiki) points to the project's main wiki page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Bundle and minify master issue #18523
