### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by yaxum** [dotnet/AspNetCore.Docs#18892]
Hi!

I tried to follow the tutorial "Tutorial: Create a web API with ASP.NET Core"

But think it was hard. Because when I tried to run up the code in the end I always get the weather app up and running. I though I was going to get up and running the API I made in the tutorial :)

Then I tried to find the example code in the folders you provide but could not find it. Think it was hard to find around in the folers..

I have probably missed something, thank you in before hand :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#test-posttodoitem-with-postman)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It works, you might want to try again. Code is https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0

**Comment by yaxum** [comment]
Hi!
When I run the vs code I always get the weather website up and running. Do not understand how I will get the todo todoApi app and running without getting the localsite weather to open...
