### ISSUE TITLE
Malformed xref

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#18893]
The following is rendered in the output of this topic:

> Similarly, JavaScript code may initiate calls to .NET methods indicated by the [JSInvokable]](xref:blazor/call-dotnet-from-javascript) attribute.

The JSInvokable link seems to work, but some thing's up with the xref. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbc1392-92dc-c42e-ba48-a722cffa9b6d
* Version Independent ID: 66a0b1c2-c45c-98ca-9808-6f340a861c44
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-3.1#javascript-interop)
* Content Source: [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thx @serpent5!
