### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by f-quintero** [dotnet/AspNetCore.Docs#18906]
Please, explain why dependencies contained in the container are called "Services", this clarification helps to understand the term service in a ASP.NET (web services) context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What do you mean by ASP.NET (web services) context ?

**Comment by f-quintero** [comment]
Hi Rick, what i mean is:

The title of the article is: "Dependency injection in ASP.NET Core", so, is about http (web) services provided by ASP.NET.

best regards,


________________________________
De: Rick Anderson <notifications@github.com>
Enviado: lunes, 22 de junio de 2020 5:57 p. m.
Para: dotnet/AspNetCore.Docs <AspNetCore.Docs@noreply.github.com>
Cc: f-quintero <fabian.quintero@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [dotnet/AspNetCore.Docs] Clarification (#18906)


What do you mean by ASP.NET (web services) context ?

**Comment by Rick-Anderson** [comment]
No, it has nothing to do with Web API's
