### ISSUE TITLE
onended event in wrong grouping?

### ISSUE THREAD

**Issue by LaughingJohn** [dotnet/AspNetCore.Docs#18901]
I could be wrong, but shouldn't the "onended" event be grouped with the media events rather than general?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Excellent :eye: @LaughingJohn!

Would you believe that I put that there on purpose to see how long it would take for someone to spot and report it? ....... *No?* ...... Indeed, it would be wise *not to believe that!* :smile:

I'll patch that up shortly. I have a mega-PR going in on localization that touches a gazillion topics. I'll patch it right after I get this 👹 *beast PR* 👹 in.

**Comment by LaughingJohn** [comment]
Thanks @guardrex - I'd never heard of it if that's any consolation! Curiosity killed the cat and all that...  :)
