### ISSUE TITLE
Configuration is wrong

### ISSUE THREAD

**Issue by theo-albers** [dotnet/AspNetCore.Docs#18919]
The section with the final configuration has 4 issues which results in RoleId1, UserId1, etc., see also https://GitHub.com/dotnet/EFCore/issues/15199. 

The wrong example:
```csharp
// Each User can have many UserClaims
            b.HasMany(e => e.Claims)
                .WithOne()
                .HasForeignKey(uc => uc.UserId)
                .IsRequired();
.....
```
The correct example:

```csharp
// Each User can have many UserClaims
            b.HasMany(e => e.Claims)
                .WithOne(e => e.User)    // <-- missing User
                .HasForeignKey(uc => uc.UserId)
                .IsRequired();
.....
```

This applies to all 4 HasMany calls.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
@ajcvickers please review.

**Comment by ajcvickers** [comment]
@theo-albers I don't see any place where we use `.WithOne()` when it is supposed to be `.WithOne(e => e.User)`. Specifically, the examples with `.WithOne()` are in cases where navigations have been added only in one direction, and hence there is no `User` navigation here.

**Comment by theo-albers** [comment]
Hey @ajcvickers, I followed the document on an existing project without the relations. As soon as I ran "dotnet ef migrations add foo" to see if it was all fine and had zero migrations, I got 4 migrations. As soon as I changed the .WithOne() to ..WithOne(x ...) and reran the migrations, all migrations disappeared. So it seems to me it's directly related to the example config.

By the way I extended all of my entities, used the IdentityDbContext with all the generic parameters and used configuration classes.

**Comment by ajcvickers** [comment]
@theo-albers If you have `User` navigation property, then you definitely need to use `.WithOne(e => e.User)`. But I don't see any examples that are intended to have `User` navigation property and don't show this.

**Comment by theo-albers** [comment]
Have another close look. This is the EF setup in the docs and which I'm using as well:

```csharp
public class ApplicationUser : IdentityUser
{
    public virtual ICollection<ApplicationUserClaim> Claims { get; set; }
    public virtual ICollection<ApplicationUserLogin> Logins { get; set; }
    public virtual ICollection<ApplicationUserToken> Tokens { get; set; }
    public virtual ICollection<ApplicationUserRole> UserRoles { get; set; }
}

public class ApplicationRole : IdentityRole
{
    public virtual ICollection<ApplicationUserRole> UserRoles { get; set; }
    public virtual ICollection<ApplicationRoleClaim> RoleClaims { get; set; }
}

public class ApplicationUserRole : IdentityUserRole<string>
{
    public virtual ApplicationUser User { get; set; }
    public virtual ApplicationRole Role { get; set; }
}

public class ApplicationUserClaim : IdentityUserClaim<string>
{
    public virtual ApplicationUser User { get; set; }
}

public class ApplicationUserLogin : IdentityUserLogin<string>
{
    public virtual ApplicationUser User { get; set; }
}

public class ApplicationRoleClaim : IdentityRoleClaim<string>
{
    public virtual ApplicationRole Role { get; set; }
}

public class ApplicationUserToken : IdentityUserToken<string>
{
    public virtual ApplicationUser User { get; set; }
}
```

**Comment by theo-albers** [comment]
And another nasty one: if you want to treat your entities as "aggregate root", you are going to use non default constructors. You will most likely use collections as IReadOnlyCollection with backing field. Now when you add a protected default constructor, just for EF, you will still run into another issue: InvalidOperationException AddEntityFrameworkStores can only be called with a role that derives from IdentityRole<TKey>. It took me a while to realize it was due to the fact I didn't have a public default constructor. It's helpfull when that's documented as well.

**Comment by theo-albers** [comment]
@ajcvickers / @Rick-Anderson can you have another look?

**Comment by ajcvickers** [comment]
@theo-albers The [configuration that goes with those types](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#add-all-navigation-properties) already shows:

```C#
b.HasMany(e => e.Claims)
     .WithOne(e => e.User)
     .HasForeignKey(uc => uc.UserId)
     .IsRequired();
```

**Comment by theo-albers** [comment]
> @theo-albers The [configuration that goes with those types](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#add-all-navigation-properties) already shows:
> 
> ```cs
> b.HasMany(e => e.Claims)
>      .WithOne(e => e.User)
>      .HasForeignKey(uc => uc.UserId)
>      .IsRequired();
> ```
Ah, shoot, you are absolutely right: I initially used the config a couple of lines above. That one didn't have the User in the WithOne(). I guess this is due to the build up of the example, from top to bottom. Sorry for wasting your time on this.

**Comment by theo-albers** [comment]
```csharp
 =>
        {
            // Each User can have many UserClaims
            b.HasMany(e => e.Claims)
                .WithOne()
                .HasForeignKey(uc => uc.UserId)
                .IsRequired();

            // Each User can have many UserLogins
            b.HasMany(e => e.Logins)
                .WithOne()
                .HasForeignKey(ul => ul.UserId)
                .IsRequired();

            // Each User can have many UserTokens
            b.HasMany(e => e.Tokens)
                .WithOne()
                .HasForeignKey(ut => ut.UserId)
                .IsRequired();

            // Each User can have many entries in the UserRole join table
            b.HasMany(e => e.UserRoles)
                .WithOne(e => e.User)
                .HasForeignKey(ur => ur.UserId)
                .IsRequired();
      
```

It was easy to overlook the difference.
