### ISSUE TITLE
sample code and instructions out of date

### ISSUE THREAD

**Issue by gdavisarms** [dotnet/AspNetCore.Docs#18915]
Hello,
 I have just tried to follow the instructions for the SignalR tutorial, but it is not possible to run the app.

On line 37 of Index,razor, HubConnectionBuilder() cannot be found.
There seems to be some missing steps, or something has changed in the API since this tutorial was written.

If it could be updated, that would be great thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
Did you make sure to include the `@using Microsoft.AspNetCore.SignalR.Client` at the top of the file?

**Comment by gdavisarms** [comment]
I got the wrong package it turns out, sorry.
Microsoft.AspNet.SignalR.Client was also available, turns out searching for SignalR.Client can point you to the wring package.

It is up and running now, thanks :)
