### ISSUE TITLE
Should "Blazor Server" appear in English?

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18921]
@JasonCard, I noticed that because "server" is translated, the product name "Blazor Server" is half translated. Shouldn't I add "Blazor Server" to the no-loc metadata to stop this from happening everywhere? cc: @scottaddie @Rick-Anderson @wadepickett @mkArtakMSFT 

From ...

```
no-loc: [Blazor, "Identity", "Let's Encrypt", Razor, SignalR]
```

... to (maintaining alphabetical list with a find-'n-replace on the full line) ...

```
no-loc: [Blazor, "Blazor Server", "Identity", "Let's Encrypt", Razor, SignalR]
```

WRT my earlier suggestion on not changing this metadatum on a per-file basis: I was concerned that if individual topics float their own words/phrases in the list that we wouldn't be able to use find-'n-replace to make a repo-wide addition. That's not correct: We can find-'n-replace on just the first part (`no-loc: [`) as long as we don't mind the list going out of alphabetical order. That seems like a reasonable compromise. :ear:

Here's an example in this specific case for "Blazor Server" ...

<img width="360" alt="Capture" src="https://user-images.githubusercontent.com/1622880/85401442-a0866f80-b51f-11ea-8485-82c2982f0f2c.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
btw @JasonCard ... Although I'm not seeing broken styling (*yet*) as a look at the outcome of the PR, I do see additional opportunities to improve localization further. One aspect that I'll need to address in a couple of spots is headings. In the following heading, "@key" was localized. 

English heading:

> Use @key to control the preservation of elements and components

Japanese heading:

> @ キーを使用して要素とコンポーネントの保存を制御する

We know that code-fenching `@key` is fine from how we handle the Razor syntax topic (`@attributes` example) ...

```
### `@attributes`
```

... rendered as ...

<img width="249" alt="Capture" src="https://user-images.githubusercontent.com/1622880/85406640-b6982e00-b527-11ea-80d2-7d63074c7eb4.PNG">

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#attributes

... and in Japanese ...

<img width="250" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/85406657-be57d280-b527-11ea-9b6c-f70766f5411b.PNG">

https://docs.microsoft.com/ja-jp/aspnet/core/mvc/views/razor?view=aspnetcore-3.1#attributes

... with an easy cross-link as "#attributes" bookmarked ...

> \<xref:mvc/views/razor#attributes>

However, this particular heading can be simply rewritten from ...

> Use @key to control the preservation of elements and components

... to ...

> Control the preservation of elements and components

I'll work these further on upcoming UE passes of the Blazor topics.

**Comment by JasonCard** [comment]
Regarding "Blazor Server", I confirmed in the [Language Portal](https://www.microsoft.com/en-us/language/Search?&searchTerm=Blazor%20Server&langID=412&Source=true&productid=0) that "Server" part should be localized, so current translation is correct and only "Blazor" should be in the no-loc metadata. 

Regarding "@key", I think the use of in-line code within headings is fine too and working well.

Thank you for all of your help to improve and avoid over-localization!

**Comment by guardrex** [comment]
Ok ... I'm a bit surprised. "Blazor Server" is a product proper noun. Idk if it's an official "product name," but it doesn't seem like a proper noun would get a split translation. For example, it would be strange to only translate the word "Directory" of "Azure Active Directory."

**Comment by JasonCard** [comment]
It looks like the "server" part was translated because the first letter "s" was not capitalized in [Term Studio](https://termstudio.azurewebsites.net/viewdata.aspx?tid=2861183&langCode=English). I found in its [Term History](https://termstudio.azurewebsites.net/History.aspx?t=ts&id=2861183) that the term was changed from 'Blazor Server' to 'Blazor server app'. So we should clarify if 'Blazor Server' is a product name and should always be capitalized or not. If so, the term should be updated again in Term Studio and re-localized. 
BTW, the no-loc metadata is case sensitive, so even if 'Blazor Server' is added, any instances of 'server' or 'server app' will be localized.

**Comment by danroth27** [comment]
Blazor Server and Blazor WebAssembly are both product terms that I believe shouldn't be localized.

**Comment by JasonCard** [comment]
@danroth27 Thank you for confirming. 
@guardrex In that case, yes, please go ahead and add both "Blazor Server" and "Blazor WebAssembly" to no-loc metadata.
I'll follow up with our loc vendor to update the Source and Target terms in the Term Studio.
