### ISSUE TITLE
Regarding Azure AD built-in Admin role object IDs for Blazor security topics

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#18924]
@mkArtakMSFT May we chat with an Azure AD team member/PM here about the Azure AD role object IDs that we had to publish? ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1#aad-adminstrative-role-group-ids

AFAICT, these aren't published anywhere (including in external 3rd party blogs and support forums), nor do they show up in the Azure portal when shown/added to a user.

These are the IDs that Azure sends in the `groups` claims for built-in Azure AD Admin roles, but they don't match what Azure docs show, for example "role template IDs" ...

https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-template-ids

Questions:

* What's the context on these IDs that we're using?
* Are they hidden on purpose in Azure AD docs? If so, why?
* Should we be showing them? Taking a step back, should we be taking some other approach in the topic to allow an app to use Azure AD built-in Admin roles? What we show in the topic works, but is this the best or correct guidance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
@javiercn do you have any advice regarding this? If not, can you please ping someone from the Azure AD side here?

**Comment by guardrex** [comment]
Let's ask @VinceSmith ... Vince, we haven't met. I found that you contributed to the Azure doc ...

**Administrator role permissions in Azure Active Directory**
https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-template-ids

... so you might either know the answer to my questions here or be able to ping someone who can help.

The question pertains to Object IDs from Azure AD for Azure built-in Administrator Roles. The IDs that we're using here ... that I had to publish in one of our ASP.NET Core docs to get Azure AD roles working in Blazor apps ... don't seem to be published anywhere for any purpose, in Azure docs or even out on the open Net. I ask a few questions about these Object IDs in my opening remarks :point_up:.

Can u help, or can you point me/us to someone who can help? Thanks.

**Comment by guardrex** [comment]
@curtand ... Hello Curtis, may I consult with u on the following subject/topic? I see from the topic's history that you've worked on it in the past ...


**Administrator role permissions in Azure Active Directory**
https://docs.microsoft.com/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-template-ids

You might either know the answer to my questions or be able to ping someone who can help.

The question pertains to Object IDs from Azure AD for Azure built-in Administrator Roles. The IDs that we're using aren't the "role template IDs" that the topic lists and don't seem to be published anywhere for any purpose in Azure docs or even out on the open Net. I ask a few questions about the Object IDs that we're using in my opening remarks at the top of this issue :point_up:.

Can u help or suggest someone who might be able to assist? Thanks.

**Comment by guardrex** [comment]
@Rick-Anderson ... No ❤️ from Azure cats after asking two folks to comment. Do you know an Azure **_engineer_** in the AD area? I hope to chat for a few minutes with an engineer and not a docs author because the questions here pertain to the internals of the service. Specifically, I'd like to discuss Object IDs for the built-in Azure Administrator Roles, which **_aren't published anywhere_** but are sent in `groups` claims to apps.

**Comment by javiercn** [comment]
Let me ping some folks.

**Comment by kylemar** [comment]
I am from the Azure AD team. There is a overriding issue with the advice on using the group claim this way, there is no discussion of claim overage issues. While it is possible an application may want to limit the scope of the app based on the Azure AD roles the user is assign, I doubt this is a common requirement. It should really only apply to applications that are managing Azure AD.

**Comment by guardrex** [comment]
Hello @kylemar ... thanks for helping me.

> claim overage issues

We have an existing issue at https://github.com/dotnet/AspNetCore.Docs/issues/18510 to work on it.

> I doubt this is a common requirement ... only apply to applications that are managing Azure AD

Should Blazor apps never manage Azure AD? I didn't think that there would be any reason to prevent it.

It's certainly convenient to have this capability explained in this topic because you get the feature for free along with the main focus on regular security groups. Even if not popular today, devs could use the built-in roles for a variety of scenarios outside of Azure AD management in the future.

Perhaps, we will ultimately pull the coverage here, but let me ask generally for non-Blazor apps that do manage Azure AD ...

Azure sends the Object IDs for built-in roles; however, Azure docs don't publish the IDs. Why aren't they published in the Azure docs?

**Comment by guardrex** [comment]
Moving discussion offline.

#18510 will cover work to deal with claims overage when users are in more groups/roles than can be sent directly to the app on authentication.
