### ISSUE TITLE
More sample with reverse proxies/load balancers would be nice

### ISSUE THREAD

**Issue by HarrySpyrou** [dotnet/AspNetCore.Docs#18922]
I would like to see samples of how to get service and client to work through something like NGINX, IIS etc.  It's nowhere to be found around the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
IIS is currently not supported.

I think discussing how to setup NGINX with gRPC is out of scope of this documentation.

**Comment by wadepickett** [comment]
I think we call out IIS not being supported on the intro gRPC docs in a few places but I'll take a fresh look at it.   Thanks @HarrySpyrou for taking the time to point out your interest in that scenario, good to know.  Closing this issue.
