### ISSUE TITLE
Query parameter parsing description missing for Blazor 

### ISSUE THREAD

**Issue by softchris** [dotnet/AspNetCore.Docs#18940]
Told to copy you in @guardrex

[Enter feedback here]
The Docs page for routing is only covering route parameters. Imo it should cover query parameters as well as this is an important part of dealing with URLs.. 

To parse query parameters currently, one needs to do the following:

1) Install `WebUtilities` package, like so `dotnet add package Microsoft.AspNetCore.WebUtilities`
2) Write code to parse query parameters, e.g:

   ```
   if (Microsoft.AspNetCore.WebUtilities.QueryHelpers.ParseQuery(uri.Query).TryGetValue("page", out var param))
   {
      this.pageParam = param; 
   }
   ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @softchris ... We'll consider it on the next round of issue triage, which usually happens on Fridays.

Cross-reference: https://github.com/dotnet/aspnetcore/issues/14236#issuecomment-542341510

**Comment by scottaddie** [comment]
@guardrex Chris has some time to create a PR for this issue. Are you okay with him moving forward?

**Comment by guardrex** [comment]
Of course, @softchris, you're welcome to submit the PR, but I recommend waiting until @mkArtakMSFT triages this issue and we determine the best thing to show. The following is from another example that we have, which might be good to show along with what you will want to add for getting the exact values out. Sometimes, the dev just wants the whole query string for other reasons.

```csharp
var currentQuery = new Uri(Navigation.Uri).Query;
```

Also, I have a vague recollection of this coming up before. I'll need to research it and see. I sort of have the impression that they didn't want to cover it. I'll have to check. Give me a bit longer. I'm buried in another issue at the moment. I'll take a look right after I'm done with this current task.

**Comment by guardrex** [comment]
Wait for Artak to respond, but here are some recommendations for when you work this ...

https://github.com/dotnet/aspnetcore/issues/5489 was closed without a new engineering issue that pertains to doing anything special for query strings, so it seems like devs will use `WebUtilities`. At the time I [responded to a reader's issue](https://github.com/dotnet/AspNetCore.Docs/issues/12425), that was still open. It looked like something might have been designed. Seems not to be the case.

Given that this will be for a reference topic, you'll only need to mention and cross-link the NuGet.org package for `Microsoft.AspNetCore.WebUtilities` at https://www.nuget.org/packages/Microsoft.AspNetCore.WebUtilities. You don't need to describe adding the package to a project. We usually do that in tutorials.

Show any `inject` directives and required `using` directives in your sample. It's ok to use an ellipsis between them and the lines of code. You don't need to show a method ... you can jump right to the line(s) of code right after the ellipsis appears (see my example below).

Recommend this for a new section at the end of the topic. That way, the reader has already consumed the `NavigationManger` coverage.

I recommend that you mention ...

```razor
@inject NavigationManager Navigation

...

var currentQuery = new Uri(Navigation.Uri).Query;
```

... as an approach to grab the query string **_either_** as a paragraph and example for the end of the [URI and navigation state helpers](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#uri-and-navigation-state-helpers) section or in the new section that you add.

**Comment by srisuk2519** [comment]
เมื่อ พ. 24 มิ.ย. 2563 เวลา 23:54 Luke Latham <notifications@github.com>
เขียนว่า:

**Comment by scottaddie** [comment]
@mkArtakMSFT Any thoughts? I don't want to wait too much longer, as Chris has time right now to work on this.

**Comment by guardrex** [comment]
If Chris doesn't have time, assign me and mark this a P1 for *fastest service* 🏃. I'm actually working in the P2 area right now, so this would be addressed quickly after I have your, Artak, feedback on the direction to take with it.

**Comment by softchris** [comment]
@guardrex hi Luke, feel free to go at it :)
