### ISSUE TITLE
var name has typo error

### ISSUE THREAD

**Issue by kdanilkov** [dotnet/AspNetCore.Docs#18943]
_logger.LogWarning(MyLogEvents.GetItemNotFound, ex, "TestExp({**Id**})", **id)**;
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 can you fix this?

**Comment by serpent5** [comment]
_Technically_, there's nothing wrong with this. `Id` and `id` don't have to match, because this is using structured logging. You might want to see `Id` as a searchable property in the logs, but use the `id` variable to populate that value for this specific message, for example.

**Comment by Rick-Anderson** [comment]
So maybe the better fix is to add the following:

Note: `Id` and `id` don't have to match, because this is using structured logging.

**Comment by serpent5** [comment]
This `Id`/`id` approach is used in a number of the examples in the topic, so I'm not sure if that's a note we'd add under the first occurence, or something else.

There's a section, [Log message template](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-message-template), that talks about these parameters and structured logging. I'm not sure if that's enough, but it does call out that it's about order and not name.

What do you think?

**Comment by Rick-Anderson** [comment]
That explains it well.

The order of placeholders, not their names, determines which parameters are used to provide their values. In the following code, the parameter names are out of sequence in the message template:
