### ISSUE TITLE
Document resolving IEnumerable<TService> when multiple registrations are provided

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/AspNetCore.Docs#18942]
Given multiple registrations in **Startup.cs**

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddTransient<IService, ServiceA>();
    services.AddTransient<IService, ServiceB>();
    services.AddTransient<IService, ServiceC>();
}
```

You should be able to depend on an `IEnumerable<TService>` in the depending service.

```csharp
public Foo(IEnumerable<IService> services)
{
    this.services = services;
}
```

This does not appear to be documented yet, although, strangely, the opposite behavior is documented as the `TryAdd*` methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#service-registration-methods)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`TryAddEnumerable(ServiceDescriptor)` methods only register the service if there isn't already an implementation of the same type.

**Comment by AnthonyMastrean** [comment]
@Rick-Anderson I'm saying that there's evidence that resolving `IEnumerable<TService>` works, but there's no documentation. In fact, there's no documentation on what happens when you call, for example, `AddScoped` multiple times on the same type.

I only mentioned `TryAdd*` as a counter-example.

https://stackoverflow.com/questions/46740270#comment80872352_46740270
https://stackoverflow.com/a/49781834/3619
https://medium.com/agilix/asp-net-core-inject-all-instances-of-a-service-interface-64b37b43fdc8

**Comment by Rick-Anderson** [comment]
Why not use `TryAddEnumerable(ServiceDescriptor)`?

**Comment by AnthonyMastrean** [comment]
My problem is that this "multiple registration" stuff is _only_ discussed in the context of `TryAddEnumerable(ServiceDescriptor)` and it fails to mention the counter-examples, both *why* you might use it (competing consumer, concurrent handling) and *how* it works (literally how multiple calls to the `Add{LIFETIME}` methods work and how that affects service resolution).

Emphasis mine:

> TryAddEnumerable(ServiceDescriptor) methods only register the service if there isn't already an implementation of the same type. Multiple services are resolved via IEnumerable<{SERVICE}>. When registering services, **the developer only wants to add an instance** if one of the same type hasn't already been added. Generally, this method is used by library authors **to avoid registering two copies** of an instance in the container.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#service-registration-methods

For example, registration of different implementations for a service is perfectly fine (undocumented?). 

```csharp
services.AddSingleton<IService, ServiceA>();
services.AddSingleton<IService, ServiceB>();
services.AddSingleton<IService, ServiceC>();
```

The last registration "wins" (undocumented?).

```csharp
provider.GetService<IService>(); #=> ServiceC
```

Asking for a list of the service returns _all_ of the registered implementations (only documented under `TryAddEnumerable(ServiceDescriptor)`).

```csharp
provider.GetService<IEnumerable<IService>>(); #=> [ServiceA, ServiceB, ServiceC]
```

Multiple registration of the same implementation for a service is perfectly fine (undocumented?). 

```csharp
services.AddSingleton<IService, ServiceA>();
services.AddSingleton<IService, ServiceA>();
services.AddSingleton<IService, ServiceA>();
```

Asking for a list of the service returns _all_ of the registered implementation, including "duplicates" (only documented under `TryAddEnumerable(ServiceDescriptor)`).

```csharp
provider.GetService<IEnumerable<IService>>(); #=> [ServiceA, ServiceA, ServiceA]
```

This same behavior works, according to my testing, for all of the `Add{LIFETIME}<{IMPLEMENTATION}>()` methods, but the table says "No" under "Multiple implementations". So, I'm confused by that, too.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @AnthonyMastrean.
This does indeed seem important to document.

@Tratcher who will be best positioned to provide a writeup from the engineering side?

**Comment by Tratcher** [comment]
@halter73

**Comment by mkArtakMSFT** [comment]
@halter73 can you please document this? Thanks!

**Comment by halter73** [comment]
Yeah. This looks like a pretty big gap. Is this urgent?

**Comment by Rick-Anderson** [comment]
> Is this urgent?
No, but I'd like to have it completed  before Sept 1, 2020.

**Comment by Rick-Anderson** [comment]
@halter73  no hurry, do you have an ETA on this?

**Comment by halter73** [comment]
I'm trying to wrap up some other work, but I can look at us during our rc2 milestone. I expect I can submit a PR for this by the end of September. Hopefully sooner.

**Comment by Rick-Anderson** [comment]
October is fine. thanks.

**Comment by mkArtakMSFT** [comment]
@halter73 this is still pending your input.
