### ISSUE TITLE
Documentation Update for Key Vault Config

### ISSUE THREAD

**Issue by itsyashpal** [dotnet/AspNetCore.Docs#18946]
[Enter feedback here]
In .NET core 3.1 , i am able to read from key vault even if it disabled secerts only the disabled secrets are skipped and hence documenation can be updated to reflect in .Net core 3.1 it no longer fail to read configuration if there are disabled secrets. 

Section containing troubleshooting and disabled/expired secrets should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  can you recommend the new resource for this topic now that `@anurse` doesn't own this?

@itsyashpal  
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
