### ISSUE TITLE
Does ASP.Net Core uses MSAL behind the scene?

### ISSUE THREAD

**Issue by Anand-Moghe** [dotnet/AspNetCore.Docs#18964]
Is ASP.Net core identity built on MSAL or MSAD library?
Otherwise how is it different from MSAD (or MSAL) libraries?
When should one select ASP.Net Core Identity framework over MSAL library for .Net  and what business cases does it enables that is not covered by MSAL libraries?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/aspnetcore/tree/master/src/Identity

**Comment by Anand-Moghe** [comment]
@Rick-Anderson   Thanks you very much !
