### ISSUE TITLE
RequiredAttribute behaviour unclear

### ISSUE THREAD

**Issue by agoodwin** [dotnet/AspNetCore.Docs#18963]
Hi,

If I'm reading it correctly, the section "[Required] validation on the server" explains that the `[Required]` attribute won't ever have any effect for value types (except maybe if they're made nullable, e.g. `int?`).

Just about every discussion about that attribute that I've ever seen (in the context of ASP.NET) agrees with that description. However, it is not actually the behaviour I'm seeing in a REST API I'm working with in .NET Core 3.1.

For example, we have an action like the following:

```
public async Task<IActionResult> GetSomething(
            [FromQuery(Name = "anumber"), Required] int aNumber,
            [FromQuery(Name = "anothernumber"), Required] int anotherNumber)
```

If I call that action without one of the integers, e.g. with the following:

`http://localhost/test/api/v1.0/numbercontroller/getsomething?anumber=123`

I get the following error:

```
{
  "errors":{
    "anothernumber":[
      "The anothernumber field is required."
    ]
  },
  "type":"https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title":"One or more validation errors occurred.",
  "status":400,
  "traceId":"|67fe2e79-4aa273e4879755e6."
}
```

Don't get me wrong, I am happy that this is the behaviour now as it has introduced some consistency and I don't seem to need to use a mixture of `[BindRequired]` and `[Required]` depending on whether I'm working with value type or reference type parameters. Basically it seems that `[Required]` is now treated similarly to `[BindRequired]`, and as far as I'm concerned that's a good thing.

The only thing is I can't find any record of this change being intentional, and this page in the documentation (which I'm assuming is the right place to be looking) is still describing the old behaviour where, with the above GET call, I'd expect no error to occur and instead `anothernumber` would just be defaulted to `0`.

To be clear, I'm not suggesting that this is a bug and I wouldn't want the behaviour to change back, I am just unsure if it is documented anywhere. If it is, I guess this issue should be closed, but if not, would this page be the place to explain more clearly how the attributes are expected to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@agoodwin  until I get a chance to work on this see https://www.strathweb.com/2017/12/required-and-bindrequired-in-asp-net-core-mvc/

**Comment by Rick-Anderson** [comment]
To repo,  use `WeatherForecastController` 
```
[ApiController]
[Route("[controller]/[action]")]
public class WeatherForecastController : ControllerBase
{
    [HttpGet]
    public IActionResult GetSomething([Required] int aNumber)
    {
        return Content(aNumber.ToString());
    }
}
```

https://localhost:50001/weatherforecast/GetSomething

@filipw @serpent5 @scottaddie  has something changed since https://www.strathweb.com/2017/12/required-and-bindrequired-in-asp-net-core-mvc/

**Comment by Rick-Anderson** [comment]
Here's the answer, from the same doc
[Required] validation on the client
Non-nullable types and strings are handled differently on the client compared to the server. On the client:

A value is considered present only if input is entered for it. Therefore, client-side validation handles non-nullable types the same as nullable types.

Use postman and no error is returned.

**Comment by agoodwin** [comment]
Hi Rick, thanks for looking into it.

So I think the example you're using is a slightly different situation to the one I'm talking about, and it does behave as described in the docs.

i.e. a GET request to `https://localhost:50001/weatherforecast/GetSomething` with your implementation will return a response of `0`, because the default value of `0` for an `int` is being used. That seems to be consistent with the docs and every other resource I've seen on the matter, like for example the strathweb.com post you linked to – which I have seen before. So I don't have any particular problem with that.

However, the situation I'm referring to is similar in implementation but with the `Required` attribute, like this:

```
[HttpGet]
public IActionResult GetSomething([System.ComponentModel.DataAnnotations.Required] int aNumber)
{
    return Content(aNumber.ToString());
}
```

So, once the `Required` attribute is in place, making the same GET request results in this response:

```
{
  "type":"https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title":"One or more validation errors occurred.",
  "status":400,"traceId":"|abb20ef7-4da732c2bb06d528.",
  "errors": {
    "aNumber": [
      "The aNumber field is required."
    ]
  }
}
```

Which again, I am totally fine with – that's the behaviour I would intuitively expect to see.

The only problem is that every resource on the matter seems to suggest (if not outright directly state) that the request will succeed and that the error will _not_ be returned. The docs, as I'm reading them, seem to say that the only way to get a similar error with this example code would be to use the `BindRequired` attribute.

Fortunately that doesn't seem to be necessary, and no handling of a mixture of `Required`/`BindRequired` needs to be done, as that linked post addresses and implies is necessary.

**Comment by serpent5** [comment]
I can't find anything authoritative on the subject, but I've discovered that this changed when the `AllowValidatingTopLevelNodes` compatibility switch was added as part of 2.1. In a sample project that uses 2.1, just switching that between `true` and `false` shows the difference.
