### ISSUE TITLE
How to override templates with project-specific t4 templates

### ISSUE THREAD

**Issue by Tiberriver256** [dotnet/AspNetCore.Docs#18976]
Looking for the .NET Core Razor Pages equivalent to this document:
https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/june/asp-net-mvc-override-the-default-scaffold-templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This one? ...

https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity

**Comment by Tiberriver256** [comment]
Nope, that is for how to use identity scaffolding to override the defaults. I'm looking to customize the templates used when you click this button:

![image](https://user-images.githubusercontent.com/6989492/85880970-dee38f00-b7aa-11ea-9c16-e5791acb5695.png)

I did find something that works on [StackOverflow](https://stackoverflow.com/questions/38382954/custom-scaffold-templates-in-asp-net-core) but it's not really documented anywhere that I can find and there are other questions beyond that (i.e. how to customize file names).

![image](https://user-images.githubusercontent.com/6989492/85881069-0d616a00-b7ab-11ea-8760-5bdf3823bc8b.png)

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
