### ISSUE TITLE
Language Resources are wrong.

### ISSUE THREAD

**Issue by soylerr** [dotnet/AspNetCore.Docs#18978]
When i change language from Turkish to English the name of "Console" still remains in Turkish ("Konsol"). Not a big deal but its confusing.

Original Language (in English)
![image](https://user-images.githubusercontent.com/37771635/85888718-d1ea8e00-b7f2-11ea-8920-8dc1662bf0dd.png)

When i change read in English
![image](https://user-images.githubusercontent.com/37771635/85888786-ed559900-b7f2-11ea-9132-86d073655727.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
It must be a caching anomaly.
