### ISSUE TITLE
Suggestion: Custom validation improvements

### ISSUE THREAD

**Issue by lfrancke** [dotnet/AspNetCore.Docs#18973]
I come here from [this](https://stackoverflow.com/questions/62559817/how-to-get-inject-services-in-custom-validationattributes) StackOverflow post.

The page mentions custom validation attributes but those have a limitation compared to MVC in that one cannot GetService from the ValidationContext.

One issue about this is here https://github.com/dotnet/aspnetcore/issues/23380

So it'd be great if this page would mention that limitation and also provide documentation on how to do proper validation where an external service is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @lfrancke ...

> custom validation attributes but those have a limitation

Yes, great idea ... we need that called out.

> how to do proper validation where an external service is needed.

It's covered in the topic (lightly currently) in the last example (`ServerValidate` method) of the opening section. Another dev also asked for additional detail/example(s), and I'm planning to split server validation out into a section and enhance the content. I envision adding a more advanced example with a web API endpoint (and show the web API piece) that performs a validation and returns success/failure (probably with a failure message).

**Comment by lfrancke** [comment]
Thank you for the super quick response.

> It's covered in the topic (lightly currently) in the last example (ServerValidate method) of the opening section.

I managed to miss that! Thanks.

If you look at the SO post we were told to subscribe to `OnFieldChanged` events instead (which I believe mimics the behavior of the current ValidationAttribute.IsValid.

I now next to nothing about any of this but HandleSubmit sounds like it only validates when the user actually submits the form. I _think_ the events get fired for changes before submit.

**Comment by guardrex** [comment]
Sure ... and `OnFieldChanged` is covered, just not in this context. When a new (better) section of content is added specifically for this scenario, a third example using that approach makes sense.

**Comment by lfrancke** [comment]
Thank you!
