### ISSUE TITLE
It looks like a typo.

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#18975]
Is it a typo?

>  `EventCallback` is weakly typed and allows any argument type.

It should be

>  `EventCallback` is weakly typed and **only** allows **no** argument type.

or more precisely

>  `EventCallback` is weakly typed and only allows callbacks (or event handling methods) with no paramater.

**Comment by guardrex** [comment]
Hello @pstricks-fans ... Would you mind closing this and opening it from the topic that you're looking at?

**Comment by guardrex** [comment]
<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
btw -- I don't think that's a typo. I believe it pertains to `EventCallback` or `EventCallback<T>`.

**Comment by guardrex** [comment]
I found the source ... it came from ...

https://github.com/dotnet/aspnetcore/issues/6351#issue-395755868

**Comment by pstricks-fans** [comment]
Thank you. Do I still need to repost this issue to the proper place indicated by the red arrow pointing to "This Page" button?

**Comment by guardrex** [comment]
Yes, if you think Ryan mis-typed it in the engineering content.
