### ISSUE TITLE
Now EventCallback only allows parameterless callback. Update is needed?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#18977]
[EDIT by guardrex to manually add the metadata]

Is it a typo?

>  `EventCallback` is weakly typed and allows any argument type.

It should be

>  `EventCallback` is weakly typed and **only** allows **no** argument type.

or more precisely

>  `EventCallback` is weakly typed and only allows callbacks (or event handling methods) with no paramater.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pstricks-fans ... Please open issues using the **This page** feedback button and form at the bottom of a topic. I'll add the metadata to your opening comment. When you use the button and form, we don't need to add it manually to issues.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Artak, the source is ...

https://github.com/dotnet/aspnetcore/issues/6351#issue-395755868

It's in the **Invoking EventCallback manually** section of the remarks, which reads ...

> Invoking EventCallback manually
>
> You can invoke an `EventCallback` like: `await callback.InvokeAsync(arg)`.
>
> Yes, `EventCallback` and `EventCallback<>` are async. We think that this will work well, because it's now much easier to use async thanks to the other improvements we made in this area. `EventCallback<>` is strongly typed and requires a specific argument type to invoke. `EventCallback` is weakly-typed and will allow any argument type.

**Comment by pstricks-fans** [comment]
Sorry. I clicked the "this page" button but  I accidentally removed the template provided by the github. Thank you.

**Comment by serpent5** [comment]
@guardrex Did you intend to ping Artak on this?

FWIW, I think Ryan's comments are accurate. `EventCallback` has an `InvokeAsync(object arg)` method but `EventCallback<TValue>` has an `InvokeAsync(TValue arg)` method. The former is weakly-typed because you can pass anything in place of the `object`, but the latter is strongly-typed because the value passed in must be assignable to `TValue`.

**Comment by guardrex** [comment]
Artak sees these when he has time to triage issues. By not pinging him, he's not disturbed with an email; but by addressing him by name, readers know (and he knows) that I'm addressing my remarks to him.

Thanks for calling out the detail on it. I'll add/modify the text to clarify it.
