### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by erhanalankus** [dotnet/AspNetCore.Docs#18988]
[Enter feedback here]
A couple of typos:

- "setDbErrorMessage" method name starts with a lowercase letter instead of an uppercase one.

- In the last code snippet(Pages/Departments/Delete.cshtml), "Administrator.FullName" line isn't highlighted.

- There is a "git add " in this sentence: "RowVersion must be added so postgit add back binds the value.".

- Typo in the last sentence: "Clicking Delete deletes the entity, unless RowVersion has been updated.department has been deleted.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Part 8, Razor Pages with EF Core in ASP.NET Core - Concurrency](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-3.1&tabs=visual-studio#update-the-delete-page)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson I can fix these typos. Do you know what that last sentance was going for?

**Comment by Rick-Anderson** [comment]
Just remove `git add`
I would make it
Clicking **Delete** deletes the entity, unless `RowVersion `has been updated.
I wouldn't address setDbErrorMessage right now.
