### ISSUE TITLE
missing Grpc.AspNetCore

### ISSUE THREAD

**Issue by sebastianolafhandjojo** [dotnet/AspNetCore.Docs#18985]
as i've come from this link
https://devblogs.microsoft.com/aspnet/grpc-web-for-net-now-available/?utm_source=vs_developer_news&utm_medium=referral

the tutorial only mentioned to add  "Grpc.AspNetCore.Web" 
didn't mention to use  "Grpc.AspNetCore"
because of that visual studio didn't recognize  services.AddGrpc(); method

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c13a1c7-4683-a9a5-9ab3-e28d4506af26
* Version Independent ID: ea3b00c8-8f09-c045-4641-dc3a0030d6e5
* Content: [Use gRPC in browser apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/browser.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/browser.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
The page discusses adding gRPC-Web to an existing gRPC service.

I think the only change is to make that more clear, and possibly link to the gRPC getting started tutortial.

**Comment by wadepickett** [comment]
@JamesNK, I will update per your recommendation.  Thanks so much.
