### ISSUE TITLE
IHostedService startup documentation

### ISSUE THREAD

**Issue by atykhyy** [dotnet/AspNetCore.Docs#18996]
Documentation page says

> When a host starts, it calls IHostedService.StartAsync on each implementation of IHostedService that it finds in the DI container.

However that's not what the code in Microsoft.Extensions.Hosting/src/Internal/Host.cs does. `IHostedService` implementations have to be registered with the service container by adding them to the instance of `IEnumerable<IHostedService>` bound in the container. Simply registering a class or object implementing `IHostedService` with `AddSingleton` is insufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @atykhyy ... You seem to be looking in the wrong spot. and the API moved several months ago. See ...

https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L55

I don't think I understand your remark tho if you still have a complaint about the way in which this is phrased. The topic is accurate AFAICT.

**Comment by guardrex** [comment]
btw - there's a full topic on hosted services that provides a lot more detail on the developer-registered services ...

https://docs.microsoft.com/aspnet/core/fundamentals/host/hosted-services

**Comment by atykhyy** [comment]
Thank you. Existing wording seems to imply that `Host` looks through *all* service descriptors in the container to find ones whose types implement `IHostedService` ("each implementation of IHostedService that it finds in the DI container"). This would mean that e.g. calling `services.AddSingleton<MyHostedService> ()` will cause `MyHostedService` to be started/stopped by the host. However, this is not what actually happens. Hosted services must be specially registered with the DI container for the host to start/stop them. This can be done either with the `AddHostedService` extension methods, or directly with `TryAddEnumerable`.

**Comment by guardrex** [comment]
I see what you mean now. At first, I thought you were focusing on the dev taking action on registration, not how all hosted services are registered/discovered.

I still don't think that phrase "that it finds" implies anything in particular about **_how_** a registration was made. I think ur reading too far into the text for an introductory paragraph in a fundamentals topic. This text is only meant to provide a general remark on getting hosted services started. A dev can look at reference source and the topic (cross-linked at the bottom of this article) for more info.

However, this concept could be written more specifically. I'd caution tho that it would be easy **_to get too far into the weeds here_** for what is supposed to be just a broad overview of the host. Perhaps, a small change would do the trick.

> When a host starts, it calls `IHostedService.StartAsync` on each implementation of `IHostedService` registered in the DI container's collection of hosted services.

We'll see if Rick wants to make a change like that. Rick, you can assign me if ur busy and want to see something along those lines. I wouldn't want to go much further tho in this context. I mean calling out `AddHostedService` and direct registration seems like too much :cow2:🔔 to me in this context.

**Comment by guardrex** [comment]
@atykhyy, you'd also be welcome to make the change, too, if Rick wants to press forward with it. If so, wait until he looks and confirms that the change (and what it should be exactly) is stated here.

**Comment by Rick-Anderson** [comment]
> When a host starts, it calls `IHostedService.StartAsync` on each implementation of `IHostedService` registered in the DI container's collection of hosted services.

LGTM

**Comment by guardrex** [comment]
@atykhyy ... Do you want to submit a PR?

If so, use the "Edit" (pencil) on the topic and follow the prompts to submit the change.

Search **_the whole topic for multiple lines_** that might need an update. We hold multiple versions of a topic in the same file. This sentence might appear two or more times.

When you open the PR, put ...

```
Fixes #18996
```

... in the opening comment so that this issue will automatically close when the PR merges.
