### ISSUE TITLE
Column headers are required for tables. Add appropriate header text

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19007]
Any PR yields the following [complaints](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/column-header-missing):

Column headers are required for tables. Add appropriate header text. NOTE: This Suggestion will become a Warning in late September, 2020.

Fix this before  it becomes a warning. See https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/column-header-missing

cc @guardrex  @scottaddie

**Comment by guardrex** [comment]
I can't see the site ... it just means that *some text* must be in the header, correct?

**Comment by Rick-Anderson** [comment]
> I can't see the site ... it just means that some text must be in the header, correct?

Column headers are required for screen readers. Without headers, users who can't visually scan the whole table before reading won't know what to expect from each column.

Add a header to each column that meaningfully describes the content of the column. The Markdown for a basic table with headers is as follows:

```
|header 1 |header 2 |header 3 |
|---------|---------|---------|
|content 1|content 2|content 3|
|and......|so.......|on.......|
```

I don't see any Blazor complaints.

**Comment by guardrex** [comment]
Understood ..... I'll run a quick :eye: over the Blazor topics just to make sure. They're easy to reveal with a search filter on `| -`.

**Comment by guardrex** [comment]
Pardon my trolling :smile: :trollface: :smile: ... **_but_** .......

> users who can't visually scan the whole table before reading won't know what to expect from each column

Likewise, users with screen readers that get link lists from a topic don't get information about a destination from "see this GitHub issue" link text either. I continue to support the title with GH issue # format. For example ...

> For more information, see \[Support for custom decoder in headers (dotnet/aspnetcore #23491)](https:\/\/github.com/dotnet/aspnetcore/issues/23491).

For more information, see [Support for custom decoder in headers (dotnet/aspnetcore #23491)](https://github.com/dotnet/aspnetcore/issues/23491).

**Comment by guardrex** [comment]
The build system doesn't like it when the header text is an API cross-link. I saw an entry this morning for ...

> Suggestion | User | column-header-missing | aspnetcore/blazor/fundamentals/additional-scenarios.md

... referring to this header ...

```
| <xref:Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.RenderMode> | Description |
```

I'll patch that to just say "Render mode" in text.

**Comment by guardrex** [comment]
It doesn't like code either. It choked on ...

```
| `RewriteContext.Result` | Action |
```

**Comment by guardrex** [comment]
Was this fixed by https://github.com/dotnet/AspNetCore.Docs/pull/19114?
