### ISSUE TITLE
CustomIdentityProviderSample Update for LTS Releases .NET Core 2.1 and .NET Core 3.1

### ISSUE THREAD

**Issue by IainCoSource** [dotnet/AspNetCore.Docs#19014]
# Issue description

CustomIdentityProviderSample is for .net core 1.1 (EOL June 27 2019) and has not been updated in 3 years and as such is not relevant to any current LTS 

.NET Core 2.1 (August 21, 2021)
.NET Core 3.1 (December 3, 2022)

https://github.com/dotnet/AspNetCore.Docs/tree/live/aspnetcore/security/authentication/identity-custom-storage-providers/sample/CustomIdentityProviderSample

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [ x] .NET Core

**Comment by serpent5** [comment]
The work for this is being tracked in #16679.

**Comment by Rick-Anderson** [comment]
closing for dup
