### ISSUE TITLE
Following documentation but using Blazor Server results in Identity.Name being Null

### ISSUE THREAD

**Issue by DatenThielt** [dotnet/AspNetCore.Docs#19020]
Following the linked document mostly works for Blazor Server however Once logged in,  The Identity.Name is null.  

This is a similar issue to #17598 however using the default Blazor server project set it up using 

`services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme)
                .AddAzureADB2C(options => Configuration.Bind("AzureAdB2C", options));`

and the fixes proposed are about either JWTBearerAuthentication or BearerAuthentication Schemes

The same with the proposed fixed from

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#useridentityname

the standard AuthenticationScheme does not appear to have a TokenValidationParameters

I am very new to AAD B2C, and newer still to Blazor server authentication and have not been able to find a fix so far to suggest unfortunately.

If any additional information is I'm more than happy to help.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by guardrex** [comment]
Noting here @CamSoper that this isn't really a "Blazor Server" issue. It's a general issue pertaining to any ASP.NET Core app. I don't have or recall the config for the `name` claim that pipes it through of the top of my head (and I'm off today 🏖️, so I can't look for it right now). I thought it was the linked example in the [WASM doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#useridentityname), but that's apparently not working for @DatenThielt.

**Comment by DatenThielt** [comment]
I seemed to have found a fix for this, however I am not sure this is the correct process or just a new step that needs to be added.

I checked my B2C_1_SiUpIn applications claims,  And the only item that was selected was Identity Provider  (which I could see was being returned)  

As a test I selected Display Name to be returned as well, and that seems to get picked up after logging in now?

Not sure if that's the correct fix however

**Comment by guardrex** [comment]
HA! :smile: lol ..... I was just about to send you this message .............

@DatenThielt Make sure that in your app's signup/signin user flow that you have "Display Name" in the **Application claims** setting. I fired up my test app here, and that claim worked without any configuration at all in the app. Therefore, I think your problem is that Azure isn't sending it down. Also, you can read out the claims in the app and see if it's there.

<img width="735" alt="Capture" src="https://user-images.githubusercontent.com/1622880/86163460-e02bf900-bad5-11ea-8498-e8a728c957fa.PNG">

**Comment by guardrex** [comment]
Yes, we can close this now. You're good. This setting btw is actually covered in the Azure docs. We try not to carry detailed guidance for these sorts of things over here. We don't have the staffing to do it, and it would be a duplication of what they have over there.

**Comment by DatenThielt** [comment]
Understood, yep can be closed! thank you!
