### ISSUE TITLE
An introduction into gRPC could sure benefit from stating what the abbreviation actually stands for.

### ISSUE THREAD

**Issue by harleydk** [dotnet/AspNetCore.Docs#19021]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/da-dk/aspnet/core/grpc/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
It's in the link in the first sentence.

**Comment by harleydk** [comment]
No, I checked beforehand; that link does not lead to a page that explains what the abbreviation stands for. It should - but that's no excuse for this page in question.

**Comment by wadepickett** [comment]
It's true, the gRPC open source site doesn't explain the acronym.   Not on the Intro, or the About.  It is hidden away in the FAQ.  https://grpc.io/faq/  and defines it as:  "What does gRPC stand for?  gRPC Remote Procedure Calls, of course!".   

This article is intended for an audience that knows what gRPC is, and wants to create a gRPC service with .NET Core.  It is not an introduction to gRPC.  Being a recursive acronym like GNU, it is one of those unfortunate satiations where providing a definition also sort of demands an explanation on its own.  I guess we could go with "gRPC (gRPC Remote Procedure Calls) is a language agnostic, high-performance Remote Procedure Call (RPC) framework"?  Any way you look at it, recursive acronyms are awkward.

**Comment by harleydk** [comment]
Thanks @wadepickett for the insight. Ever the nit-picker, if "It is not an introduction to gRPC" the headline should probably be changed. 
Don't want to be an a** about it, it's excellent documentation, I'm merely new to gRPC and understanding the acronym was the first that came to mind.

**Comment by Rick-Anderson** [comment]
@harleydk  consider opening an issue with https://grpc.io
We're not documentng gRPC, we're documenting the .NET implementation of it.
