### ISSUE TITLE
Nowin project references is discontinued

### ISSUE THREAD

**Issue by dmartensson** [dotnet/AspNetCore.Docs#19034]
The Nowin project references is discontinued according to the owner so this guide should be revised as it should use active solutions.

As far as I can see there are no cross platform server suggested that supports websockets, since kestrel does not have that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34916983-6cf6-590e-0762-df0fe4e4f52c
* Version Independent ID: 1bf5bce0-c571-296e-1e8a-896af7068499
* Content: [Open Web Interface for .NET (OWIN) with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/owin.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/owin.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  should I remove the section [Using ASP.NET Core Hosting on an OWIN-based server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-2.1#using-aspnet-core-hosting-on-an-owin-based-server) which features Nowin?

**Comment by Tratcher** [comment]
> As far as I can see there are no cross platform server suggested that supports websockets, since kestrel does not have that.

Kestrel supports Upgrades, and WebSockets are supported on top of that via middleware. Do you mean there's no OWIN WebSocket middleware?

> @Tratcher should I remove the section [Using ASP.NET Core Hosting on an OWIN-based server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-2.1#using-aspnet-core-hosting-on-an-owin-based-server) which features Nowin?

It's still useful as an example. @dmartensson any suggestions for an active project to replace it with?

**Comment by dmartensson** [comment]
Hi

No, unfortunately I have not found any I could recommend and no guide to
websockets on kestrel.

For most parts I can just start a webapi project under IIS, but in this
case I was trying to build a webserver into a library and that proved to be
a bit more of a problem ;)

A quick search found these but I have not tested any of them yet so I do
not know if they are solving the problem:
https://suave.io
https://github.com/unosquare/embedio


Best regards

David



Den fre 3 juli 2020 kl 00:12 skrev Chris Ross <notifications@github.com>:

**Comment by Tratcher** [comment]
Here are the websocket docs: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1

You don't need OWIN for cross platform support, Kestrel already covers that.

**Comment by dmartensson** [comment]
Hi

are you sure it works with Kestrel.
According to the documentation you linked IIS or HTTP.sys is a prerequisite


Prerequisites

   -

   ASP.NET Core 1.1 or later
   -

   Any OS that supports ASP.NET Core:
   - Windows 7 / Windows Server 2008 or later
      - Linux
      - macOS
   -

   If the app runs on Windows with IIS:
   - Windows 8 / Windows Server 2012 or later
      - IIS 8 / IIS 8 Express
      - WebSockets must be enabled (See the IIS/IIS Express support
      <https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1#iisiis-express-support>
      section.).
   -

   If the app runs on HTTP.sys
   <https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-3.1>
   :
   - Windows 8 / Windows Server 2012 or later
   -

   For supported browsers, see https://caniuse.com/#feat=websockets.


Den fre 3 juli 2020 kl 02:28 skrev Chris Ross <notifications@github.com>:

**Comment by davidfowl** [comment]
Yes websockets works with kestrel 😄 .

**Comment by dmartensson** [comment]
Then that might be mentioned as many threads I found suggested that it was not supported, so I did not even bother trying. :)

**Comment by Tratcher** [comment]
That says `If the app runs on Windows with IIS:`. 

The doc never mentions Kestrel because Kestrel doesn't have any prerequisites for WebSockets, it just works. It might be worth mentioning Kestrel for clarity though.
