### ISSUE TITLE
Out of context example code

### ISSUE THREAD

**Issue by simonziegler** [dotnet/AspNetCore.Docs#19040]
Hi, there's a snippet of sample code on your page referencing a `_userManager` variable. This is really hard to understand because you give no context as to where that is supposed to go. Please explain context/destination for all code snippets otherwise other readers will have the same question as me: "where am I meant to put this, then?".

Otherwise many thanks of course for the docs. Simon
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#use-claims-to-customize-identity-handling)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @simonziegler ... Yes, it can be mentioned in text and/or more code can be shown. In general tho when there's a sample app available and the code in the topic is linked from it, you can look at the sample app, which is linked at the top of the topic. In this case ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz/sample/Pages/Account/Register.cshtml.cs#L23

**Comment by simonziegler** [comment]
Thanks - I’ll do that

**Comment by Rick-Anderson** [comment]
You can see it when you scaffold Identity. It's shown in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity
