### ISSUE TITLE
Azure AD ambiguous

### ISSUE THREAD

**Issue by clarkezone** [dotnet/AspNetCore.Docs#19042]
[Enter feedback here]
Select app in azure AD.. this is ambiguous, there are many azure AD entries in the portal.  Please update /test these instructions with latest state of Azure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> there are many azure AD entries in the portal

There's only one entry per app per tenant in the UI. The instruction is just saying to select the app that you intend to work with and then navigate to **Certificates & secrets**.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
