### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kenleese** [dotnet/AspNetCore.Docs#19048]
Near the bottom of the page this link rewards the supplicant with a 404:
Integrate components into Razor Pages and MVC apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b7135b-b7a0-2fba-b846-530480aeb415
* Version Independent ID: 69e5b8fb-04e0-817e-434f-72cf6ba12923
* Content: [Migrate from ASP.NET Core 3.0 to 3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/30-to-31.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/30-to-31.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @kenleese ... The topic moved and this one was missed on the find-and-replace of links because these cross-links aren't normal XREF links ... they're relative links to the markdown files. I'll patch it up now.
