### ISSUE TITLE
Drop EF Core content from the Blazor DI topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19051]
Drop EF Core content after https://github.com/dotnet/AspNetCore.Docs/pull/18981 merges.

@JeremyLikness Please confirm my plan here. After we merge and take your PR content live, I'll circle back around and work this issue to delete the EF Core section from the DI topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#use-of-entity-framework-dbcontext-from-di

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by JeremyLikness** [comment]
@guardrex That is correct - confirmed. /cc @danroth27 and @javiercn
