### ISSUE TITLE
razor tutorial docment typo

### ISSUE THREAD

**Issue by tongzhipeng** [dotnet/AspNetCore.Docs#19062]
[Enter feedback here]
there is a typo in the "Use SQLite for development, SQL Server for production" section under "visual studio code" tab.
 services.AddDbContext<**MovieContext**>(options =>   should be 
 services.AddDbContext<**RazorPagesMoiveContext**>(options =>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tongzhipeng** [comment]
I found some more errors, like the step in "Scaffold the movie model" section will fail because  RazorPagesMovieContext already exists,  it's kinda like that the document under "visual studio code" tab is not maintained anymore.
actually, I'm not a big fan of "VS Code",  I just want to learn more details other than just use Visual Studio's Wizzard and Menus.  Well,  since they are some errors, and I don't want to spend too much time on the survey, so I let it go, I will turn back to "Visual Studio" tab,  it's the default tab, I think it supposes to be right.

**Comment by tongzhipeng** [comment]
the document under "Visual Studio" tab is perfect, I haven't met any problems, thanks for your work, "Razor" is fantastic new technology!

**Comment by Rick-Anderson** [comment]
dup of #17986
