### ISSUE TITLE
Access denied when using this guide.

### ISSUE THREAD

**Issue by davidbuckleyni** [dotnet/AspNetCore.Docs#19078]
[Enter feedback here]
When I follow the steps in this guide I still get access deined when I log in my user who belongs to manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25051544-0e4d-1715-95b7-3a8616475127
* Version Independent ID: 50736569-fc04-ec6d-7b33-a3e0c860b1ed
* Content: [Claims-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This doesn't have a complete sample but is an overview.
