### ISSUE TITLE
UseCors & UseRouting / UseAuthentication

### ISSUE THREAD

**Issue by brechtvhb** [dotnet/AspNetCore.Docs#19074]
Please put in the documentation that calling UseCors must happen before UseRouting and USeAuthentication. Our team spelt half a day to found out why we were having authentication issues on Preflight requests.

Refering to his page: https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1

**Comment by guardrex** [comment]
@brechtvhb ... Recommend that you close this and re-open it using the **This page** feedback button and form at the bottom of the topic. It will add metadata that automatically pings the author ... you'll get a faster response.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
