### ISSUE TITLE
HTTP401 exception in OPTIONS preflight because of unclarity in documentation.

### ISSUE THREAD

**Issue by brechtvhb** [dotnet/AspNetCore.Docs#19084]
Please put in the documentation that calling UseCors must happen before UseRouting AND UseAuthentication. Our team spent half a day to find out why we were having authentication issues on preflight requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af11946-ea05-3be2-6fa1-c4c01aa76d8c
* Version Independent ID: 58e87eb0-240b-ab00-c5f4-32a0ab2e0028
* Content: [Security considerations in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **anurse**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by Rick-Anderson** [comment]
The first example shows before routing and the doc links right away to the CORS doc.
