### ISSUE TITLE
Link to sample downloads is incorrect

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#19080]
*View or download sample code* points to https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/common, but that doesn't seem to be right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @serpent5 ... I'll fix it right now. It escaped my re-linking efforts when we did the ToC shakeup.
