### ISSUE TITLE
Clarification request for "Apply Migration" in the troubleshooting step.

### ISSUE THREAD

**Issue by Nhawdge** [dotnet/AspNetCore.Docs#19086]
I'm having issues getting my database to create the required tables for auth. The segment below specifically applies to me. But I have no idea where 'Apply Migrations' is selected from. I'm using `dotnet` cli and VS Code with MySql. 

> If the site database has not been created by applying the initial migration, you get A database operation failed while processing the request error. Select Apply Migrations to create the database, and refresh the page to continue past the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.1#configure-google-authentication)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't support MySql. Can you use SQLite or SQL Server?
