### ISSUE TITLE
The Enforce HTTPS in ASP.NET Core page appears to have an error.

### ISSUE THREAD

**Issue by rledyard** [dotnet/AspNetCore.Docs#19094]
The page in question:
[Enforce HTTPS in ASP.NET Core] (https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1)

The command:
> $ dotnet dev-certs https --trust 

is not a valid command. I am using SDK 3.1.301 on Linux.

This is the output for the command: 
> $ dotnet dev-certs https --help

> Usage: dotnet dev-certs https [options]
>
>Options:
>  -ep|--export-path  Full path to the exported certificate
>  -p|--password      Password to use when exporting the certificate with the private key into a pfx file
>  -c|--check         Check for the existence of the certificate but do not perform any action
>  --clean            Cleans all HTTPS development certificates from the machine.
>  -v|--verbose       Display more debug information.
>  -q|--quiet         Display warnings and errors only.
>  -h|--help          Show help information

Nowhere in the help text above is the option "--trust" mentioned. Perhaps it was removed as an option in an earlier version of the SDK, and the docs were not updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
The `--trust` option isn't available on Linux.

**Comment by Rick-Anderson** [comment]
@rledyard  you need to follow the Linux instructions, not the windows

**Comment by rledyard** [comment]
@serpent5  > The `--trust` option isn't available on Linux.
If it's not available, then why does it state under the heading = "Troubleshoot certificate problems", subheading = "_All_ platforms - certificate not trusted" - to use the command with the "--trusted" option? I think that needs to be clarified.

@Rick-Anderson > you need to follow the Linux instructions, not the windows
Maybe I'm too dense to see them, but I don't see any Linux instructions. I do see the WSL ones, but that's only to use it from Windows. I am on Linux Mint - not on Windows or WSL. Am I missing something?
