### ISSUE TITLE
Custom policy provider - IAuthorizationPolicyProvider link results in GitHub's 404

### ISSUE THREAD

**Issue by amoraitis** [dotnet/AspNetCore.Docs#19093]
Clicking the `Custom policy provider - IAuthorizationPolicyProvider` results in a 404 page.

https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/CustomPolicyProvider

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82950389-524e-0754-a125-addeccbdb1b3
* Version Independent ID: 80b7f7cf-dc2e-137a-5aa7-fa88da63ac80
* Content: [Authentication samples for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/samples?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
2.2 is out of support.

**Comment by stevebelskie** [comment]
@Rick-Anderson It also results in a 404 when looking at the 2.1 version of the docs though. Looks like it's using 2.2 urls for all versions 2.X and lower.

```
::: moniker range="< aspnetcore-3.0"

The [ASP.NET Core repository](https://github.com/dotnet/AspNetCore) contains the following authentication samples in the *AspNetCore/src/Security/samples* folder:

* [Claims transformation](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/ClaimsTransformation)
* [Cookie authentication](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/Cookies)
* [Custom policy provider - IAuthorizationPolicyProvider](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/CustomPolicyProvider)
* [Dynamic authentication schemes and options](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/DynamicSchemes)
* [External claims](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/Identity.ExternalClaims)
* [Selecting between cookie and another authentication scheme based on the request](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/PathSchemeSelection)
* [Restricts access to static files](https://github.com/dotnet/AspNetCore/tree/release/2.2/src/Security/samples/StaticFilesAuth)
```

I would imagine these should point to 2.1 instead since it's LTS. If that's the case, I'd be happy to submit a PR for this.

**Comment by Rick-Anderson** [comment]
@stevebelskie  a PR would be appreciated.
