### ISSUE TITLE
Suggestions for Blazor Components Overview

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#19090]
Here's a few suggestions for this topic:

- Component classes | Namespaces:
The `using` and fully-qualified examples both use a different project name (`BlazorApp` vs `BlazorSample`).
- Child Content:
I noticed that it's possible to use multiple `RenderFragments` for different sections of child content. I think this is just "Templated components", but it might be helpful to reference those here to show that `@ChildContent` isn't the only option. For example, the panel component could have `Title`, `Content`, and `Footer` elements.
- Synchronization Context:
There's a line that reads *Register the NotifierService as a singletion:*, but the second example uses `AddScoped`. *singletion* is also misspelt.
- Don't create components that write to their own parameter properties:
It looks like the `onclick` handler can be simplified to just `@onclick="StateHasChanged"`.

I hope this is useful. If I'm just covering stuff that's already been considered, etc, I'm happy to stop raising issues like this. I know it takes time to go through these suggestions... Please don't feel the need to justify decisions, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#dont-create-components-that-write-to-their-own-parameter-properties)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... all bugs should be fixed asap, and other suggestions for less critical updates can be addressed at the same time.
