### ISSUE TITLE
Creating routing-integrated middleware missing attribute consumption example

### ISSUE THREAD

**Issue by jarrettv** [dotnet/AspNetCore.Docs#19096]
In the section **Creating routing-integrated middleware** there is no example of checking for the attribute metadata. The doc shows how to create a proper attribute, but I'm left wondering how do I check the attribute value in my custom middleware.

Also there is a typo in the last C# example in this doc: **RequrireAuthorization();**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#configuring-endpoint-metadata)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I don't see a typo in `RequrireAuthorization` in the two examples.

Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by jarrettv** [comment]
Don't see typo "Requrire" 🤷

**Comment by Rick-Anderson** [comment]
@serpent5  added label [GII](https://github.com/dotnet/AspNetCore.Docs/labels/GII)
