### ISSUE TITLE
IE mode in Edge Chromium with Blazor

### ISSUE THREAD

**Issue by Truong072348** [dotnet/AspNetCore.Docs#19100]
We have blazor application that requires Edge Chromium to run.
Everything is perfect, but in IE mode, my project doesn't work.
My question is: Is Blazor supported in IE Mode?
If possible please give me material about this
Regards.

**Comment by guardrex** [comment]
Hello @Truong072348 ... For Blazor Server, it might run with polyfills. You can try using the [Polyfill.io bundle](https://polyfill.io/v3/). Blazor WebAssembly isn't supported.

https://docs.microsoft.com/aspnet/core/blazor/supported-platforms
