### ISSUE TITLE
Bad Blazor navigation UE

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19124]
@scottaddie ... Can u advise on this one?

When a dev finishes the new Blazor Get Started experience at https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/next, we want them to follow the link ...

<img width="729" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/86785733-ac4a5980-c028-11ea-843c-80691ef807e8.PNG">

...  to the Blazor todo list tutorial at ...

https://docs.microsoft.com/aspnet/core/tutorials/build-a-blazor-app

Because the sidebar ToC matches the first URL in the *toc.yml* file to the browser's URL, the sidebar ToC opens to the *Tutorials* folder ...

<img width="289" alt="Capture" src="https://user-images.githubusercontent.com/1622880/86785770-b9ffdf00-c028-11ea-90c6-53a8e7e50a0d.PNG">

I don't want that behavior. I want the reader to land in the Blazor ToC at the latter tutorial link ...

<img width="336" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/86785838-d4d25380-c028-11ea-90b5-897cb511f0df.PNG">

Can I either ...

* Do something with the *toc.yml* or a redirect to stop the matching behavior on that *Tutorials* node link in the sidebar?
* Failing that, I'd like to remove that *Tutorials* node link in *toc.yml* so that the first matching link will be the one in the Blazor > Tutorials ToC node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Same problem with the security node cross-links. When I select the "CORS section" link in the following section ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1#cross-origin-resource-sharing-cors

... it doesn't show the Blazor ToC node for the link after it opens at `https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#cross-origin-resource-sharing-cors`. It actually opens in the *Security and Identity* node.

Apparently, the sidebar ToC selection is derived by scanning top-to-bottom **_AND at each indent level_** until it finds the match.

For the Blazor Security topics, this is also highly **_undesirable_** because we don't want readers thrown out of the sidebar ToC node as they select cross-links and jump around in the Blazor node.

Unless there's a way to mark these *undesirable* entries in the *toc.yml* file, they should be removed. When I think about finding something for Blazor, I'm going to bookmark the top of the node or else navigate to the node and look for the topic. However, I admit that there's no sound conclusion to draw here ... just my intuition on it.

**Comment by scottaddie** [comment]
@guardrex I'm also unaware of a feature that would accomplish this.
