### ISSUE TITLE
Page Lacks needed documentation.

### ISSUE THREAD

**Issue by jja256** [dotnet/AspNetCore.Docs#19122]
This page lacks instructions. It should state that you must add the Nuget package before any of this code works. Was very confusing and I spent 30 mins looking for the answer that stumbled across in another video from Udemy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Doesn't it say that in the first bullet of ...

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-3.1#create-the-app-in-facebook
