### ISSUE TITLE
Where do the options get added to the EmailSender instance?

### ISSUE THREAD

**Issue by VergilPrime** [dotnet/AspNetCore.Docs#19120]
I'm stuck, this documentation explains how to put the API key into the secrets but not how/when to retrieve the secrets and set them into the options instance in the EmailSender. I'm going to keep chipping away at this but it might be helpful to add this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#require-email-confirmation)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
For more information, see the Options pattern and configuration.
