### ISSUE TITLE
Incorrect instructions in tutorial 7

### ISSUE THREAD

**Issue by tealbert1943** [dotnet/AspNetCore.Docs#19125]
I ran into a problem in Part 7. The instructions said to “Create a Pages/Courses/DepartmentNamePageModel.cs file with the following code:” But following the instructions resulted in several errors in the code.  Comparing with the completed app, it appears that the intent was to create a DepartmentNamePageModel.cshtml.cs file. 

It wasn't clear how to create the DepartmentNamePageModel.cshtml.cs file.  I tried creating it as a Razor Page, but that didn't work.   So I tried simply creating DepartmentNamePageModel.cshtml.cs as a class.  That was successful.  But its confusing in that nowhere in the series of tutorials had there been a case of creating a Class.cshtml.cs file without an associated Class.cs file.

The same issue occurs with the instructions to create the InstructorCoursesPageMOdel.cshtml.cs class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Part 7, Razor Pages with EF Core in ASP.NET Core - Update Related Data](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, see https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro/samples/cu30/Pages/Courses/DepartmentNamePageModel.cs
