### ISSUE TITLE
Add documentation on lazy-loading support for Blazor

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#19149]
For preview8, we need to add documentation on Blazor's new support for lazy-loading.

@guardrex This [PR description](https://github.com/dotnet/aspnetcore/pull/23290#issue-439057914) can be a useful starting ground for this. Let me know if you need any more info.

**Comment by guardrex** [comment]
@captainsafia ... Do you feel that this fits best as a new section in the performance best practices topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices

... or as a new section in the Blazor WASM Host and deploy topic ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1

... or as a new topic in the Host and deploy node given that there's enough content to merit creating a new topic from your remarks on the engineering issue?

If a new topic, then perhaps ...

* **_Title:_** Lazy load assemblies in ASP.NET Core Blazor WebAssembly
* **_Physical location/filename:_** `aspnetcore/blazor/host-and-deploy/lazy-load-assemblies.md`
* **_TOC entry:_** Blazor > Host and deploy > Lazy load assemblies (as the last entry in the node)

Note: We try to avoid gerunds in titles, section headings, and TOC entries. When used as a noun/subject, they apparently don't translate well. Let's see if we can just use "load" in titles and section headings for this.

**Comment by captainsafia** [comment]
> ... or as a new topic in the Host and deploy node given that there's enough content to merit creating a new topic from your remarks on the engineering issue?

I like this option the most since there is enough content to warrant an entire page.

> * **_Title:_** Lazy load assemblies in ASP.NET Core Blazor WebAssembly
> * **_Physical location/filename:_** `aspnetcore/blazor/host-and-deploy/lazy-load-assemblies.md`
> * **_TOC entry:_** Blazor > Host and deploy > Lazy load assemblies (as the last entry in the node)

This looks good!

**Comment by guardrex** [comment]
ok ... I'll get to work on that very soon ... probably tomorrow (Friday) tho. The family :cat2:, *Merlin*, woke me up at **_4am_** (!!!! 😠) to be fed and let outside. I was wide awake, so started at 4am ... my workday is almost over. :smile:

**Comment by captainsafia** [comment]
Cool! Ping me with any questions.

Heads up: there will be some follow-up PRs so interfaces and such might change a bit. I'll keep you up to date on the changes.

**Comment by guardrex** [comment]
Include: https://github.com/dotnet/aspnetcore/pull/23290#issuecomment-656313665

**Comment by guardrex** [comment]
@captainsafia ...

```razor
<Router Assembly="typeof(App)" ...>
    ...
</Router>
```

... implies some structural changes in Blazor WASM apps for 5.0 given that today the `App` component contains the `Router` component. It's all I can do to *barely* keep up 😅 today with coverage for the current framework. I don't run preview bits until much closer to a release. Is there a stock 5.0 WASM sample on the engineering repo that I can visually inspect? If not, no worries ... I'll just look at the template on master.

**Comment by captainsafia** [comment]
That was me abbreviating while writing the docs quickly. There haven't been any structure changes so things will look like this.

```
<Router AppAssembly=typeof(StandaloneApp.Program).Assembly AdditionalAssemblies="@lazyLoadedAssemblies">
    <Found Context="routeData">
        <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    </Found>
    <NotFound>
        <LayoutView Layout="@typeof(MainLayout)">
            <h2>Not found</h2>
            Sorry, there's nothing at this address.
        </LayoutView>
    </NotFound>
</Router>
```

**Comment by captainsafia** [comment]
> If that's not right, can you explain it out a bit more?

Your assumption is correct. Only packages that are used by the app can be lazy loaded.

> I'm planning on adding a try-catch to OnNavigateAsync. If assemblies fail to load, should we show anything in particular in the catch block?

We're sorting through how we surface unhandled exceptions to the UI as part of the PR.

If a user is providing a try-catch, they can implement some conditional logic to toggle showing an error bar or redirect to a 500 page or something. That behavior is up to the user.

Apologies for the late reply. I took yesterday off as a sick day.

**Comment by guardrex** [comment]
Get well soon. 🐔🥣

**Comment by captainsafia** [comment]
@guardrex BTW, is there an open PR with the text you are editing?

**Comment by guardrex** [comment]
Not yet ... I'll put the PR up this morning (Wednesday).
