### ISSUE TITLE
Add --no-restore option for dotnet publish command in dockerfile

### ISSUE THREAD

**Issue by moebius87** [dotnet/AspNetCore.Docs#19145]
About the dockerfile: I suggest using --no-restore with the publish command otherwise the benefit of doing restore and publish in two different steps and having different layers is canceled. This is because dotnet publish command runs dotnet restore implicitly.

see [https://docs.microsoft.com/it-it/dotnet/core/tools/dotnet-publish#implicit-restore](https://docs.microsoft.com/it-it/dotnet/core/tools/dotnet-publish#implicit-restore) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1#the-dockerfile-1)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
