### ISSUE TITLE
Selecting target framework to 3.1 is not available

### ISSUE THREAD

**Issue by c0g1t8** [dotnet/AspNetCore.Docs#19143]
I was doing a walkthrough for Visual Studio for Mac and found a discrepancy. Under [Create a hosted Blazor WebAssembly app project](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio-mac&source=docs#create-a-hosted-blazor-webassembly-app-project), step 4 implies the ability to change the target framework.

![image](https://user-images.githubusercontent.com/23250332/86948259-b8eeb080-c101-11ea-8c6b-d1aeead5e2d4.png)

No such option exists. 🙂.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... I'll put a fix in for that right now. I just put a PR up where I can tack it on.

The VS4Mac UI is under **_contstant_** flux as the new features roll into it. Thanks for reporting this one.

**Comment by guardrex** [comment]
@c0g1t8 ... Idk if this is a Blazor-only thing. Do you happen to know (or can you check) if you create a Razor Pages or MVC project and that **Target Framework** entry has also gone away? If so, I need to fix this in two of our tutorials.

My iMac is buried in the closet and will take 15 minutes to fire up. Greatly appreciated if you could walk thru the setup for a Razor Pages project just far enough to see if it's gone or still there.

**Comment by c0g1t8** [comment]
@guardrex 

The **Target Framework** entry is missing for both **Web Application** and **Web Application(Model-View-Controller)**.

![image](https://user-images.githubusercontent.com/23250332/86959170-31f60400-c112-11ea-8aa6-550b0f48e525.png)

![image](https://user-images.githubusercontent.com/23250332/86959067-05da8300-c112-11ea-875c-9488de4b6f7e.png)

**Comment by guardrex** [comment]
Thanks @c0g1t8 ... I'll open an issue and get those other topics fixed up by EOD.
