### ISSUE TITLE
Docs for HTTPS on WSL

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#19141]
Trust and export the HTTPS developer certificate from the windows machine with `dotnet dev-certs https -ep https.pfx -p <<password>> --trust`

Run the following command `dotnet dev-certs https --clean --import <<path-to-pfx>> --password <<password>>`
**Warning:** This will replace any existing asp.net core localhost dev-cert from your wsl distro with the certificate from your host machine.

After that, you can create an app, run it and access it from the Windows host and it should show as trusted in your browser.

***EDIT by @Rick-Anderson*** to add doc meta-data
@javiercn  it helps to open the issue from the doc page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot-certificate-problems)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Looks like I need to update [Trust HTTPS certificate from Windows Subsystem for Linux](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux) with the preceding information.
