### ISSUE TITLE
Add code samples on docs to configure startup options for Blazor Server

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#19153]
[EDIT by guardrex to add the metadata and update the link]

We should add some code samples that show how to modify the reconnection UI and interval using JavaScript in this docs page.

~https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#configure-the-signalr-client-for-blazor-server-apps~

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#configure-the-signalr-client-for-blazor-server-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc56d254-09c5-993b-2559-76af9a3f97ed
* Version Independent ID: a0bb183f-7e4d-ba39-c94c-cf60e951c7a9
* Content: [ASP.NET Core Blazor hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#configure-the-signalr-client-for-blazor-server-apps)
* Content Source: [aspnetcore/blazor/fundamentals/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It will be faster if engineering provides the content and example(s). Of course, they can be pasted into a comment here.

**Comment by guardrex** [comment]
Let me know tho if this is what u want to show ...

### Hide the ReconnectionDisplay

```cshtml
<script>
  window.addEventListener('beforeunload', function () {
    Blazor.defaultReconnectionHandler._reconnectionDisplay = { };
  });
</script>
```

### retryIntervalMilliseconds

```cshtml
<script>
  Blazor.start({
      reconnectionOptions: {
          retryIntervalMilliseconds: 2000,
      }
  });
</script>
```

... and any additional remarks, gotchas, etc.

**Comment by captainsafia** [comment]
Those samples are good! I'd also include the sample that shows how you can modify the reconnection handler as well. 

Something like this:

```
  Blazor.start({
      reconnectionHandler: {
             onConnectionDown: (options, error) => console.error(error);
             onConnectionUp: () => console.log("Up, up, and away!");
      }
  });
```

The reconnection handler can be used to register callbacks that are registered when the circuit is connected and disconnected.
