### ISSUE TITLE
Update Azure Key Vault Configuration Provider in ASP.NET Core page to recommend Azure.Extensions.AspNetCore.Configuration.Secrets rather than Microsoft.Extensions.Configuration.AzureKeyVault

### ISSUE THREAD

**Issue by dylanlerch** [dotnet/AspNetCore.Docs#19155]
## Back story
I was struggling with very slow startup times when using the [Microsoft.Extensions.Configuration.AzureKeyVault](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault/) package, I did a bit of digging and noticed that there was an issue with [Microsoft.Azure.Services.AppAuthentication](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/) having slow token fetching times. This was [fixed in version 1.2.0](https://github.com/Azure/azure-sdk-for-net/issues/4645#issuecomment-506256389), but Microsoft.Extensions.Configuration.AzureKeyVault is referencing 1.0.3.

If I add a reference the latest version of Microsoft.Azure.Services.AppAuthentication (1.5.0), everything speeds up nicely.

I was going to make an update to `Microsoft.Extensions.Configuration.AzureKeyVault`, but it looks like that [has been deprecated](https://github.com/dotnet/extensions/issues/3057) and replaced with [Azure.Extensions.Configuration.Secrets](https://www.nuget.org/packages/Azure.Extensions.Configuration.Secrets), which has since been replaced with [Azure.Extensions.AspNetCore.Configuration.Secrets](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets/).

## Suggestion
This page currently recommends using the `Microsoft.Extensions.Configuration.AzureKeyVault`, should this be updated to recommend `Azure.Extensions.AspNetCore.Configuration.Secrets`?

Or would it be better to add a new page explaining how to to use the new package (as I'm not sure there is 100% feature parity between the two, for example not sure how to [authenticate with application id and cerificate](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-application-id-and-x509-certificate-for-non-azure-hosted-apps))?

Could potentially link to the [Azure Key Vault Secrets configuration provider for `Microsoft.Extensions.Configuration` - Version 1.0.0](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/Extensions.AspNetCore.Configuration.Secrets-readme?view=azure-dotnet) page, but it's pretty basic at this point.

---

Happy to start writing the documentation myself, but this would be my first contribution so want to make sure that there isn't a better process for more significant changes like this 😄.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#secret-storage-in-the-production-environment-with-azure-key-vault)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT  can you assign someone to review this proposal?
