### ISSUE TITLE
This doesn't work in Asp.Net 3.1.5 in Mac

### ISSUE THREAD

**Issue by erick2red** [dotnet/AspNetCore.Docs#19150]
Hi,

It' simple. I read the instructions. Created a `bundleconfig.json` file, ran `dotnet build` and nothing happened.

The document doesn't says what's required, or how to troubleshoot it. I'm using a basic template created with `dotnet new`. It'd be good to provide some guidance, or at the very least, come out and explicitly says: _"This is not supported in Mac"_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Bundle and minify master issue #18523
Currently bundle/minify is not great on any platform. We hope to have a solution eventually.

**Comment by erick2red** [comment]
@Rick-Anderson The fact that there's an issue open doesn't fix the misleading documentation. The less you could do is mention the issue in the page: _Currently bundle/minify is not great on any platform. We hope to have a solution eventually. (For updates follow issue #18523)_
