### ISSUE TITLE
Add information about configuring a website in IIS

### ISSUE THREAD

**Issue by Dobby007** [dotnet/AspNetCore.Docs#19160]
There should be more information about configuring a website in IIS. Also there should a remark about non-obvious flag `setProfileEnvironment="true"` which is set in `C:\Windows\System32\inetsrv\config\applicationHost.config` in order to load the user profile and set all environment variables to point to the home directory of the current user. Otherwise it will not be possible to use certain APIs, e.g. DPAPI or AWS SDK (which uses credentials and other settings stored in the home directory).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Dobby007 ... We have the coverage, but not here. It's in the IIS main topic. See the 2nd bullet at ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#data-protection

**Comment by guardrex** [comment]
There's also a nibble in the DP docs at ...

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-3.1#key-management

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
