### ISSUE TITLE
Provide information for console apps

### ISSUE THREAD

**Issue by Devmanitu** [dotnet/AspNetCore.Docs#19173]
[Enter feedback here]
When I search for information about configuration code examples, I alway come to this page. However, this page has no additional information about console apps. Maybe this is not the right place, but there isn't any other. 
I spent hours trying to figure out the right packages, because key functions are put into extension methods which are in separate NuGet packages. They are not included by default in console apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See Non-web scenarios at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-3.1&tabs=windows#non-web-scenarios

and search for `config.Add` on the config document.

cc @serpent5

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration
