### ISSUE TITLE
Remove reference to a closed issue and clarify a contradiction

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/AspNetCore.Docs#19184]
Since the [issue](https://github.com/dotnet/AspNetCore/issues/5410) mentioned on this page is already closed and there is now an official way to resend email confirmations, I think the **Resend email confirmation** section should be entirely removed or at least updated to show where and how to implement the feature.

Also, I'd like some clarification as to the following code in the **Configure startup to support email** section:
``` c#
    [...]
    services.AddTransient<IEmailSender, EmailSender>();
    services.Configure<AuthMessageSenderOptions>(Configuration);
```

[This](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#scaffold-identity-into-a-blazor-server-project-with-authorization) doc on Scaffolding Identity suggests that the email sender service should be a singleton and it let me a bit confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in .NET 5
