### ISSUE TITLE
Update the AdventureWorks Data Dictionary

### ISSUE THREAD

**Issue by FoxyChmoxy** [dotnet/AspNetCore.Docs#19182]
# Issue Description
The information in the documentation ["Schemas in AdventureWorks"](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/ms124894(v=sql.100)) and ["AdventureWorks Data Dictionary”](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/ms124438(v=sql.100)) was updated last time in **2010**, and many of these articles are currently not relevant.

I work with the **AdventureWorks** database, and in the latest version of **2019**, new tables appeared and some old ones disappeared that you will not find in these documents. There is also no detailed description of each column in separate tables.

I can write and update the documentation myself if it is allowed and recommended.

**Comment by guardrex** [comment]
Hello @FoxyChmoxy ... That doc set has been retired and is no longer updated/supported. The current AdventureWorks coverage is provided by the SQL docs ...

https://docs.microsoft.com/sql/samples/adventureworks-install-configure

If you want to interact with the doc authors and managers that support that coverage, you can open an issue for that team at ...

https://github.com/MicrosoftDocs/sql-docs/issues
