### ISSUE TITLE
Graceful integration of ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C

### ISSUE THREAD

**Issue by jmacCity** [dotnet/AspNetCore.Docs#19186]
Hello @guardrex / @javiercn ,

I just completed your ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C tutorial and it was a great intro! I was wondering if there is a more integrated way to incorporate the authentication process into the SPA 

Apologies in advance if I am missing the obvious.

Thanks,
Jordan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#access-token-scopes)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jmacCity ... Thanks. The supported approach is described by the topic and the guidance in the [Additional scenarios](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios) document. I don't understand what you mean by "more integrated way;" but if you have a feature request for the product unit, you can open it at https://github.com/dotnet/aspnetcore/issues. We only work on the documentation here, so if you have framework feedback or feature requests, that repo is the right spot to ask. Thanks again for your kind remark.
