### ISSUE TITLE
Warning to always use HTTPS is too broad a statement for gRPC due to TLS offloading scenarios. 

### ISSUE THREAD

**Issue by ChiefInnovator** [dotnet/AspNetCore.Docs#19183]
There is a warning that should probably have more clarification.

**Warning**
HTTP/2 without TLS should only be used during app development. Production apps should always use transport security. For more information, see Security considerations in gRPC for ASP.NET Core.

It is a common practice to do TLS offloading and is definitely common practice in Kubernetes clusters where you have internal services which reside on a private V-Net.  So you run your services without TLS, but configure TLS at the load balancer for those services that are exposed.  The warning to not use HTTP/2 without TLS suggests that gRPC is being developed with the expectation that HTTPS is the expected behavior in production which it is not in the common situation I just mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-US/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
@blowdart Do you know of guidance that can be linked to that discusses when it is ok to not use TLS?

**Comment by blowdart** [comment]
Nope. This is probably quite grpc specific, would there be general resources in Google's docs?
