### ISSUE TITLE
Link for "Entity Framework - Code-Based Configuration" is broken

### ISSUE THREAD

**Issue by Veverke** [dotnet/AspNetCore.Docs#19189]
Link for "Entity Framework - Code-Based Configuration": https://docs.microsoft.com/en-us/ef6/fundamentals/configuring/code-based --> is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [ASP.NET Core and Entity Framework 6](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It should be https://docs.microsoft.com/en-us/ef/ef6/fundamentals/configuring/code-based
cc @serpent5
