### ISSUE TITLE
Link tells websocket without signal R, Typo Error

### ISSUE THREAD

**Issue by jazeem-azeez** [dotnet/AspNetCore.Docs#19190]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/8478849/87259320-d6799c80-c4aa-11ea-81c8-a696b3fc8cf6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Where is the typo, it looks correct to me

**Comment by jazeem-azeez** [comment]
> 
> 
> Where is the typo, it looks correct to me



> 
> 
> Where is the typo, it looks correct to me

I have highlighted in image, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1
sharing again 
![image](https://user-images.githubusercontent.com/8478849/87886248-b2263e80-ca1b-11ea-8078-7d1d9c62a023.png)

**Comment by Rick-Anderson** [comment]
What's wrong with that?
