### ISSUE TITLE
[WinAuth] Further clarify app configuration and deployment

### ISSUE THREAD

**Issue by xr280xr** [dotnet/AspNetCore.Docs#19194]
I have just run into the 500.19 Internal Server Error after following this page to set up Windows authentication. I found[ this previous, closed Issue](https://github.com/dotnet/AspNetCore.Docs/issues/12144#issue-436890384) about the same thing but still ended up with the same problem. Am I correct in understanding that if you are running your project out of Visual Studio under IIS Express, you should not include the web.config outlined on this page? Rather just configure windows authentication and anonymous access directly through IIS for the target site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
ASP.NET Core doesn't use web.config

**Comment by xr280xr** [comment]
Right so it can be confusing if you’re setting up a project to be run in IIS and using IIS Express in VS and the documentation has an IIS section talking about how to configure your web.config.
