### ISSUE TITLE
Add explanation about how to install the trusted root on Linux and Linux service fabric enviroments

### ISSUE THREAD

**Issue by jfalameda** [dotnet/AspNetCore.Docs#19197]
Hi,

In this example, you are only explaining how to install the trusted root CA on Windows. I cannot manage to make it work on a Linux environment running service fabric. Since .NET core is multiplatform, it would be great to add instructions about how to do it in other systems.

Have a nice day.
José.

**Comment by guardrex** [comment]
Hello @jfalameda ...

> this example

???

Please close and re-open this issue using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
