### ISSUE TITLE
Question on duplication

### ISSUE THREAD

**Issue by dylanfranck** [dotnet/AspNetCore.Docs#19199]
[EDIT by guardrex to add the metadata. @dylanfranck, please use the **This page** feedback button+form at the bottom of any topic to open an issue.]

**Help us make content visible**

https://stackoverflow.com/questions/61427947/entity-framework-core-error-an-error-occurred-using-the-connection-to-database
As far as I'm aware, everything should be set correctly because of previous work.

**Describe the new topic**

- _**Explain why this topic is needed.**_
I want to be able to play with the website and edit as needed while also being able to go back easily to a previous version. I could store the code through Github but was concerned with Database stuff.
- _**Suggest a location in the Table of Contents.**_
Replication and Further Testing at the end
- _**Write an abstract. In one **short** paragraph, describe what this topic will cover.**_
Now that you've made the app, lets discover how you might modify it and get it into the production environment on your system. Other than of course the structure of the app, the bare bones of this application rest on the following files: Program, Startup, DbInitializer, School Context, and appsettings. These are what create the database and set the platform for our framework we've created.
_**Context:**_ 
I'm very new to this, what I tried was simply changing the connection string in appsettings.json from:
"ConnectionStrings": {
    "SchoolContext": "Server=(localdb)\\mssqllocaldb;Database=SchoolContext6;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
to
"ConnectionStrings": {
    "SchoolContext": "Server=(localdb)\\mssqllocaldb;Database=SchoolContext7;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
Because my idea was that it would tell that the database doesn't exist and therefore create it from the Program, Startup, and DbInitializer files.

![error](https://user-images.githubusercontent.com/43482452/87453517-96143e80-c5d0-11ea-9a25-5f8148f89e36.PNG)

![errorsnip](https://user-images.githubusercontent.com/43482452/87452893-c3142180-c5cf-11ea-86cf-bcf84801865b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@dylanfranck ... What topic are you looking at?

Normally, we ask readers to open topics using the **This page** feedback button and form at the bottom of the topic, which adds metadata and pings the author.

In this case, I'll manually add the metadata, so which topic are you looking at (provide the link to the topic)?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
