### ISSUE TITLE
Incorrect namespace of ProblemDetailsFactory

### ISSUE THREAD

**Issue by heemskerkerik** [dotnet/AspNetCore.Docs#19192]
The fully qualified name of `ProblemDetailsFactory` is `Microsoft.AspNetCore.Mvc.Infrastructure.ProblemDetailsFactory`; the text omits `Infrastructure`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by guardrex** [comment]
Thanks @heemskerkerik ... it should be cross-linked to the API doc, too. I'll fix it right now.
