### ISSUE TITLE
different behavior with using TempData

### ISSUE THREAD

**Issue by FredHan001** [dotnet/AspNetCore.Docs#19205]
In [this SO thread](https://stackoverflow.com/questions/62843105/why-tempdata-attribute-retain-after-first-read), we can find that applying `[TempData]` attribute to a property of PageModel class, like below.

```
public class AModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public void OnGet()
        {
            Message = "test Page A";
        }
    }
```
then accessing value using `<p>@Model.Message</p>` in current page `A.cshtml`, which seems not read TempData value, but can access TempData value using same code `<p>@Model.Message</p>` in `B.cshtml`.

Besides, if directly set value for `TempData["message"]` as below, can access TempData value using `TempData["message"]` in `A.cshtml` 

```
public class AModel : PageModel
{
    public void OnGet()
    {
        TempData["message"] = "test Page A1";
    }
}
```

Can explain more about this behavior? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1#tempdata)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
SO has the answer, your code in A is not reading tempdata. Refresh B and the message is gone.
cc @serpent5
