### ISSUE TITLE
Cross-link Blazor Hosted IdS topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19208]
### Summary

The ask is for a Blazor security topic that can focus on interacting with Identity Server with ...

* Standalone WASM.
* Hosted WASM without scaffolding Identity and storing users in the server app (i.e., the server app is only being used to host the WASM app and isn't involved in auth/IdS).

The topic would probably largely focus on the [client app configuration of the current *Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server* topic](https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-identity-server#client-app-configuration) that would have a different lead-in for creating the app.

@javiercn @mkArtakMSFT ... Shall we provide this version of the coverage in a new topic?

### Comments

@psiservices-mhart stated on https://github.com/dotnet/AspNetCore.Docs/issues/19151#issuecomment-658526826 ...

@guardrex - Thank you. I will raise the issue about ACR values with the engineering team and cc you as requested. 
	
In regards to the rest:

I appreciate your modifications. I think one of my disconnects is that the docs assume you have created the app with Authentication included (and indeed they instruct you to at the top).  However, for someone who wants to use an external identity server as I do, scaffolding with Authentication doesn't seem like something you'd want to do, since the only option currently is ` Store user accounts in-app - Select this option to create a project that includes a local user accounts store.`
If I am trying to work with an external identity server, then clearly I don't want to store user accounts in-app. Therefore I did **_not_** choose the option to scaffold with authentication.

Keeping the above scenario in mind:

- hosted app
- external identity server
- no authentication scaffolded

 I think that's when the docs become a little less clear to me. 
- Right off the bat, the docs start out with instructions to scaffold with authentication/storing user accounts in-app - not applicable to my scenario.
- Under **Server app configuration**, much of that doesn't apply to my scenario either. You said,

> Devs can follow the client configuration guidance in the topic.

 If the intended path through the doc page (for the above scenario) is actually to disregard half of it (ie; the server app configuration section), this is why I raised the question that maybe this scenario warrants its own topic, or at the least, a little more clarity. As it stands, it's unclear whether _anything_ covered in the server app Startup class section applies given the above scenario. Some of it _obviously_ doesn't (the first two code samples for instance), but with some of it it's less clear.
<br/>

> A Blazor WebAssembly app in a hosted solution is the same as a standalone Blazor WebAssembly app. The only difference is how it's served. OIDC concepts are the same. 

That makes sense. The reason I questioned whether the middleware was dependent upon the hosting model you chose was because I noticed the hosted app doc page exclusively describes using the `AddApiAuthorization()` middleware, while the standalone app doc page exclusively describes using the `AddOidcAuthentication()` middleware. 

 Is the difference between these two pieces of middleware roughly that
   - 	`AddApiAuthorization()` loads the authentication config via http?
   - 	`AddOidcAuthentication()` takes the authentication config options directly or gets them from a JSON file?

If this is the case, I assume for hosted you can use either, and it really just comes down to preference? If this is the case, I really think it'd be helpful to call this out.
<br/>

One other thing I found a little unclear: If you are using an external identity server and thus do NOT scaffold authentication, there is a lack of clarity on working with the `AddApiAuthorization()` middleware. If I am understanding correctly, `AddApiAuthorization()` loads the authentication config via HTTP, and the URL defaults to `_configuration/{client-id}`. If you _had_ scaffolded with authentication, this would map to the server app's `OidcConfigurationController`. However, if you do _NOT_ scaffold with authentication, this controller & route do not exist. Now, the docs state the middleware can be configured "to point to a separate endpoint by calling the overload with options." But there is no indication of precisely what that endpoint is expected to return. (I needed to create and debug a separate sample app with authentication scaffolded in order to figure out where the `_configuration/{client-id}` route the docs mentioned was even coming from.) Again, I think this disconnect is because the docs are geared towards authentication having been scaffolded.
 
I fully appreciate that the docs cannot possibly hope to cover every scenario that's out there. However it seems like the scenario I describe above (hosted, external identity server, no authentication scaffolded) would be pretty common.

As always, thanks for being receptive to community feedback.

**Comment by javiercn** [comment]
@guardrex the scenario described here is a standalone app that uses OIDC. I think we already have that covered and I don't think we need additional docs for it.

**Comment by guardrex** [comment]
Ok, but we don't say that in that topic, so should I call out in the introductory remarks in the Standalone WASM topic (and cross-link it with a brief remark at the top of the Hosted IdS topic) that that's how one would interact with IdS?

**Comment by javiercn** [comment]
@guardrex if you feel is important, go ahead.
