### ISSUE TITLE
Migrate Authentication and Identity to ASP.NET Core

### ISSUE THREAD

**Issue by Sambhav007** [dotnet/AspNetCore.Docs#19206]
[Enter feedback here]
 When i try to migrate Authentication and identity to ASP.NET core.  
 Problem 1:  i am facing issue during the Uncomment the @Html.Partial line in _Layout.cshtml;

Problem 2: I added a new Razor view called _LoginPartial to the Views/Shared folder:

Updated _LoginPartial.cshtml with the following code:

Facing issue in below line:
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

Issue is: Error	CS0246	The type or namespace name 'UserManager<>' could not be found (are you missing a using directive or an assembly reference?) during the build.

Using : .NET Core 3.1

Please help me to resolve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6772c4-1017-5e86-8045-8849b5dd1ad7
* Version Independent ID: bcb8d6b2-f38a-ac10-d3f2-69d4223bfd72
* Content: [Migrate Authentication and Identity to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #9770
