### ISSUE TITLE
Instructions for enabling stdout logs no longer work

### ISSUE THREAD

**Issue by rhamlett** [dotnet/AspNetCore.Docs#19202]
The instructions for enabling the stdout logs that appears on this page are no longer followable in the Azure Portal.  The first three steps involve a convoluted method of reaching Kudu that includes a round-about method that doesn't work anymore.  I offer the following instructions as a replacement:

1. Open the Azure Portal for your web app.
2. Search at the top of the menu on the left side of the page.  Type ‘kudu’ into the search box.
3. Click on Advanced Tools, then click the word 'Go ->' to open the Kudu diagnostic console.
4. From the menu at the top, select 'Debug Console', and then CMD
5. Navigate to ‘site\wwwroot’ and find the web.config file.  (Usually at the bottom of the list.)
6. Click the pencil icon next to the web.config file.
7. Set stdoutLogEnabled to true and change the stdoutLogFile path to: \\?\%home%\LogFiles\stdout.
8. Select Save to save the updated web.config file.
9. Make a request to the app.
10. Return to the Kudu diagnostic console (Steps 1 -4 above)
11. Select the LogFiles folder and select the pencil icon for the stdout log with the latest modification date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#aspnet-core-module-stdout-log-azure-app-service)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rhamlett  your instructions look good but changing to the  `stdoutLogFile` path to: `\?%home%\LogFiles\stdout` didn't produce a log file.

cc @davidebbo

**Comment by davidebbo** [comment]
That's a typo, it should be `\\?\%home%\LogFiles\stdout` (two slashes). This is the same as the current instructions at the Kudu level. Seems what changed is the Azure portal's Diagnose UI which broke the early parts of the instructions. Those instructions were too complex anyway, and what @rhamlett suggests is simpler.

cc @suwatch as I'm no longer on the team.
