### ISSUE TITLE
[VSCode] Add in details on how to debug blazorwasm when project structure is nested

### ISSUE THREAD

**Issue by Kronos11** [dotnet/AspNetCore.Docs#19204]
Would love to have details on how to enable debugging when the project structure is not the default in VSCode

For Example:
/
/.vs
/src
/src/Blazor.App
/src/Blazor.App/Client
/src/Blazor.App/Server
/src/Blazor.App/Shared

The default setup will not work for a blazorwasm hosted app
#19204 https://github.com/dotnet/aspnetcore/issues/21166#issuecomment-632933868
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think debugging in the browser for the client app will work.

Pinging @captainsafia for help on this one.

**Comment by captainsafia** [comment]
@guardrex I think the person who reported the issue might've intended to link to https://github.com/dotnet/aspnetcore/issues/23265 where I provided a response in https://github.com/dotnet/aspnetcore/issues/23265#issuecomment-651880080.

We might consider adding a sample for this in the docs.

**Comment by guardrex** [comment]
These instructions don't seem correct ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-hosted-blazor-webassembly

I agree to add the assets, but the generated `.vscode` folder **_is empty_** after that. I presume that it's because the *Server* folder should be opened in VSC.

I'll play around with it and see if I can figure it out.

**Comment by guardrex** [comment]
I clarified the language on the PR. It's up for review now.
