### ISSUE TITLE
Sample code bug - Use cookie authentication without ASP.NET Core Identity

### ISSUE THREAD

**Issue by eddlilley** [dotnet/AspNetCore.Docs#19214]
[EDIT by guardrex to add the metadata]

When running the sample code for "Use cookie authentication without ASP.NET Core Identity" which can be found at AspNetCore.Docs/aspnetcore/security/authentication/cookie/samples/3.x/CookieSample/ a bug has been found.

Once signed in, select the browser's back button and attempt to log in again. The post request isn't handled and  HTTP 400 status code is returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---

**Comment by guardrex** [comment]
Hello @eddlilley ... It's best to open an issue using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

No worries on this one. I'll add the metadata manually to the issue.

**Comment by guardrex** [comment]
Ping @HaoK to say if this is a real 🐞 or just a bad artifact of the back button.

**Comment by serpent5** [comment]
I think this is a case of "The provided anti-forgery token was meant for a different claims-based user". Using the back button means the CSRF tokens for the unauthenticated user are cached, so they no longer match when you go back.

I found a comment where `@javiercn` confirms this: https://github.com/dotnet/aspnetcore/issues/2882#issuecomment-425253252, for context.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
