### ISSUE TITLE
Sample HttpResponseException should be immutable.

### ISSUE THREAD

**Issue by yevster** [dotnet/AspNetCore.Docs#19228]
The sample `HttpResponseException` on this page is mutable. This is not a good programming practice, and we don't want customers to copy&paste antipatterns into their code:

```csharp
public class HttpResponseException : Exception
{
    public int Status { get; set; } = 500;

    public object Value { get; set; }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
@pranavkm  please suggest how to fix this.

**Comment by pranavkm** [comment]
Lots of result types in MVC are mutable. Why is it considered a bad programming practice?
