### ISSUE TITLE
Adding a third-party open source project to the MVC unit testing article

### ISSUE THREAD

**Issue by mihail-vladov** [dotnet/AspNetCore.Docs#19223]
Hi, guys! My name is Mihail Vladov and I am the engineering manager of [JustMockLite ](https://github.com/telerik/JustMockLite )which is an open-source mocking framework. My team and I are part of [Telerik ](https://www.telerik.com/) which is a long time partner with Microsoft.
I wanted to ask you if it is possible to add JustMockLite to the additional resources in the following article?  
[https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1)

I am willing to submit а pull request with all the necessary changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Sounds great to me. 
 @scottaddie @mkArtakMSFT if you have objections voice them ASAP.

**Comment by scottaddie** [comment]
@Rick-Anderson I'm okay with this.

**Comment by Rick-Anderson** [comment]
@mihail-vladov  a PR would be welcome.
