### ISSUE TITLE
Code Paging Suggestion

### ISSUE THREAD

**Issue by ChClaude** [dotnet/AspNetCore.Docs#19229]
You might want to consider the following logic for method CreateAsync() in the PaginatedList class.

        public static async Task<PaginatedList<T>> CreateAsync(IQueryable<T> source, int pageIndex, int pageSize)
        {
            var count = await source.CountAsync();
            var items = await source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();

            // New Code
            pageSize = items.Count;
            return new PaginatedList<T>(items, count, pageIndex, pageSize);
        }

The new line inserted will set the right pageSize value when the number of items to be paginated is less than the pageSize parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Part 3, Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the tip

**Comment by Rick-Anderson** [comment]
I don't see how that helps? It correctly paginates when the number of items is less than the page size?

![image](https://user-images.githubusercontent.com/3605364/94877491-5ce0b300-03f6-11eb-880c-9587c68e2236.png)
