### ISSUE TITLE
Install Microsoft.EntityFrameworkCore.InMemory instead of Microsoft.EntityFrameworkCore.SqlServer 

### ISSUE THREAD

**Issue by baoqger** [dotnet/AspNetCore.Docs#19222]
[Enter feedback here]

In the tutorial, it's said to install "Microsoft.EntityFrameworkCore.SqlServer " package, but in the code, it used Microsoft.EntityFrameworkCore.InMemory. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It says install them both. See https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#add-a-database-context

**Comment by BEsanov** [comment]
Add the following code to **TodoApi.csproj**   inside the `<Project></Project>` tags:   
`  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="3.1.6" />
  </ItemGroup>`

Source : https://stackoverflow.com/a/58469004/7745916
