### ISSUE TITLE
New docs for Log Formatter APIs

### ISSUE THREAD

**Issue by shirhatti** [dotnet/AspNetCore.Docs#19224]
**Describe the new topic**

https://github.com/dotnet/runtime/pull/38616 adds a few new features to ILogger:
- A new in-box JSON format for Console logs
- Support for custom log formatters

## Explain why this topic is needed.

In environments where folks scrape/redirect console logs for structured logging, they want to know how to enable JSON formatted logs

## Suggest a location in the Table of Contents.

https://docs.microsoft.com/aspnet/core/fundamentals/logging/

## Write an abstract. In one **short** paragraph, describe what this topic will cover.

Console log formatting APIs

The Console Logger provides built-in formatters and the ability author your own custom formatter.

## Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

- What is a console log formatter? 
- What are the in-box console log formatters?
  - Simple
  - JSON
  - SystemD
  - Compact
- How do register a new formatter?
- How do I select which formatter to use (via both code and config)?
- How do I author a new formatter?

@maryamariyan

**Comment by Rick-Anderson** [comment]
@shirhatti  @maryamariyan can you suggest someone to prove code samples and the first draft?

**Comment by maryamariyan** [comment]
@Rick-Anderson I can help out.

**Comment by shirhatti** [comment]
Closing this issue as it was addressed in https://github.com/dotnet/docs/pull/21189
