### ISSUE TITLE
How to add user-secrets while publishing .NET Core Console App?

### ISSUE THREAD

**Issue by sukesh-ak** [dotnet/AspNetCore.Docs#19239]
[Enter feedback here]
I used user-secrets in my SignalR Client Console App and it works fine during development.
I published the .NET Core Console App to a different machine (Raspberry Pi running RPI OS with .NET Core 3.1 SDK)
Exception is thrown saying the user-secrets are not found.

How do I transfer the user-secrets to make sure my application can find it on a different machine?
_I understand in the case of ASP.NET Core when published on Azure, Key Vault is a good option._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows#installing-the-secret-manager-tool)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
he values are stored in a JSON configuration file in a system-protected user profile folder on the local machine:

**Comment by sukesh-ak** [comment]
> The values are stored in a JSON configuration file in a system-protected user profile folder on the local machine:

I understand that.

Question is
How do I transfer the user-secrets to make sure my application can find it on a different machine?
