### ISSUE TITLE
Unity asset bundles not working

### ISSUE THREAD

**Issue by VR-Architect** [dotnet/AspNetCore.Docs#19235]
I am using the UploadPhysical controller method with multiple files. It works fine for *.txt files. If I try to upload a Unity asset bundle, which is a type of LZ compressed file, it fails in the ProcessStreamedFile method as the memoryStream length is zero. However, if I take the same file and put inside a zip file, it works fine.

Also, I see the controller is checking for a cookie, but I don't see where the cookie is ever set. I use ASP.net security tokens though. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to File Uploads topic enhancements and master issue #12285
