### ISSUE TITLE
Please improve content structure (e.g. headings ranking) to be more distinctive

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#19230]
The ranking of headings in Microsoft Docs very often isn't clear.
<img alt="" align="right" src="https://user-images.githubusercontent.com/9283914/87696415-0c5f9f00-c791-11ea-9d9a-88fa0ef82ac1.png">Reading the docs I often tend to find myself lost in the jungle of: "What does this piece information belong to? What does it pertain to? Where am I?".

### See this sample (from Document Details below)

![MS Docs - 1](https://user-images.githubusercontent.com/9283914/87696770-93ad1280-c791-11ea-9a11-57e916df4cf9.png)

_(I removed much of the paragraph content to give a better overview of the headings I'm referring to.)_

### Here I highlighted all the headings to better demonstrate what I'm referring to

![MS Docs - 2](https://user-images.githubusercontent.com/9283914/87696927-cf47dc80-c791-11ea-90e3-595d78c6a7de.png)
<br/>

From the above example you can see that in the above section there is no meaningful heading ranking whatsoever:

- Why are `macOS` and `Linux` smaller than `Windows`?
   Are they a sub-section of `Windows`?
- Why is `Set the environment in code` next to `Windows`?
   Is `Set the environment in code` a novel OS?
- Why is `Command prompt` and `PowerShell` next to `web.config`?
   They are just two flavors of the same thing and, thus, should be grouped one level down.
<br/>

In the screenshots above I removed much of the text to give a better overview. Yet, reading through the actual text you quickly get lost and forget why you're reading a piece of information anyway. Most importantly: You wouldn't even recall where in particular you found a piece of information trying to figure it out at a daily meeting the other day.

The above is only an example. Misleading formatting can be found at many places in the documentation.
<br/>

Please revise your pages and [improve structure](https://www.userfocus.co.uk/articles/usermanuals.html#Anchor-How-11481).

- https://www.userfocus.co.uk/articles/usermanuals.html#Anchor-How-11481
- https://developers.google.com/tech-writing/one/lists-and-tables#keep_list_items_parallel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#development)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> - Why are `macOS` and `Linux` smaller than `Windows`?
>   Are they a sub-section of `Windows`?

No, they are under a different heading that is an H3

> - Why is `Set the environment in code` next to `Windows`?
>    Is `Set the environment in code` a novel OS?

I don't see that. Maybe another screen shot?

- Why is `Command prompt` and `PowerShell` next to `web.config`?
   They are just two flavors of the same thing and, thus, should be grouped one level down.

It's not

![image](https://user-images.githubusercontent.com/3605364/87710375-659fe200-c741-11ea-8ec1-5d81ea486e53.png)

**Comment by SetTrend** [comment]
Thanks for replying.
<br/>



> > * Why are `macOS` and `Linux` smaller than `Windows`?
> >   Are they a sub-section of `Windows`?
> 
> No, they are under a different heading that is an H3

My above question was meant to be ironically. I didn't mention that, sorry.

The current layout _suggests_ `macOS` and `Linux` to be a sub-section of `Windows` (though, it's actually not):

![MS Docs - 4](https://user-images.githubusercontent.com/9283914/87712444-f1992480-c7a8-11ea-84b0-24a17fa166a7.png)
<hr/>

> > * Why is `Set the environment in code` next to `Windows`?
> >   Is `Set the environment in code` a novel OS?
> 
> I don't see that. Maybe another screen shot?

Sure:

![MS Docs - 3](https://user-images.githubusercontent.com/9283914/87712334-ce6e7500-c7a8-11ea-99f5-7910e3499b38.png)
<br/>

> 
>     * Why is `Command prompt` and `PowerShell` next to `web.config`?
>       They are just two flavors of the same thing and, thus, should be grouped one level down.
> 
> 
> It's not

Oh, yes it is:

![MS Docs - 5b](https://user-images.githubusercontent.com/9283914/87714356-f14e5880-c7ab-11ea-8114-f98f88c46e30.png)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
