### ISSUE TITLE
Improve Switch Mappings section

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#19236]
The [Switch Mappings](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#switch-mappings) section of (Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#switch-mappings) is quite confusing.

It doesn't get clear what Switch Mappings actually do.

Moreover, the content is a jumble:
<br/>

> Switch mappings
>
> Switch mappings allow key name replacement logic. Provide a dictionary of switch replacements to the AddCommandLine method.

Is that second sentence of this section an imperative? Is it necessary to "Provide a dictionary of switch replacements to the AddCommandLine method" to be able to read further on? Why should I do that? - If it isn't an imperative, what's it supposed to tell me?
<br/>

> The following code shows the key values for the replaced keys:

The code snippet following this introduction doesn't actually show anything reasonable and is by no means the conclusion of the previous paragraph.
<br/>

> Run the following command to test the key replacement:

Why should I do that? It's not working!

If I actually had taken the frustrating step to unsuccessfully run that command line snippet, then, after reading further on, I would have read a faint note under the command line snippet explaining in general when a command line isn't working. It doesn't tell that the command line snippet above is an example of such non-functional command line.

Notwithstanding the above, what's the reason behind all this?
- First there's a sudden, unexpected imperative (_"Run the following command to test the key replacement:"_), not introduced by a "how to" header. (How to ... what anyway?)
- Next, there's a non-functional command line snippet that I'm supposed to execute. (For whatever reason ...)
- Finally there's a faint note, solving the riddle and explaning that all the above is just a joke.
- And in the end, no output is given to demonstrate what the result of all this finally is.

Please revise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by SetTrend** [comment]
@Rick-Anderson:

Ah, I'm too late. Wanted to add another flaw, without raising another issue:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#bind-an-array

The code samples are missing the most important part: the definition of the custom `ArrayExample` class.

**Comment by Rick-Anderson** [comment]
look in the sample download

**Comment by SetTrend** [comment]
A documentation is not an addendum to sample code. To be a documentation in contrast to scribble, the documentation must stand by itself. You cannot expect readers to download code every time they just want to read some piece of information.

Did you notice that the ASP.NET documentation takes 5,000 pages when converted to PDF? You don't expect readers/learners to also download numerous samples just to fill in the gaps missing in the documentation, do you?
