### ISSUE TITLE
What is the MyDebug in the code examples?

### ISSUE THREAD

**Issue by fitprotracker** [dotnet/AspNetCore.Docs#19244]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
You can see it in the sample app here ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters/3.1sample/FiltersSample/Helper/MyDebug.cs
