### ISSUE TITLE
API authorization option fails

### ISSUE THREAD

**Issue by fornax76** [dotnet/AspNetCore.Docs#19248]
As per this document, I tried both approaches to Configure Identity Server - API authorization options & Profile Service.

API authorization options failed with a runtime exception "IUserClaimsPrincipalFactory`1 not registered.'"
Profile Service worked fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio#name-and-role-claim-with-api-authorization)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fornax76 ... That approach was verified working when the content was put up. If you're willing to put up a repro project on GH, I'll take a look. Otherwise, it's not really actionable without more information.

**Comment by guardrex** [comment]
@fornax76 ... Can you paste your `Startup.ConfigureServices` in to a comment here?

**Comment by fornax76** [comment]
Yes - I am adding the repro project.

**Comment by fornax76** [comment]
Created a new project and tried to recreate my steps with API authorization option - **but it works fine now**. I am unable to reproduce the error, my apologies. Please close this issue.

Uploaded here: https://github.com/fornax76/IdentityDemo
