### ISSUE TITLE
AddRazorPages().AddRazorPagesOptions(...) could be AddRazorPages(...)

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#19245]
A few of the examples in this topic use the following code:

```csharp
services.AddRazorPages()
    .AddRazorPagesOptions(options => ...);
```

The following code is essentially the same, but a bit simpler:

```csharp
services.AddRazorPages(options => ...);
```

There's another use of this in [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions). The explanation that goes with that one actually talks of `AddMvc`, but shows `AddRazorPages`. I'm not sure if that should be considered as a separate GitHub issue to this one, as it's a different topic.

I do realise that switching to this approach would hide the availability of `AddRazorPagesOptions` for anyone that's using `AddMvc` or just wants to configure the RP options separately to adding the services. I think that's more of an advanced use-case, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The "MVC" language is leftover from a bygone age when green dinosaurs walked the Earth ...

https://github.com/dotnet/AspNetCore.Docs/pull/4623/files#diff-7dd60462f639e5ca08accb6d2d4723dcR389

... and can be changed.
