### ISSUE TITLE
Example in "component should not write to their own state" is using wrong field

### ISSUE THREAD

**Issue by codertimu** [dotnet/AspNetCore.Docs#19249]
The example uses the public parameter in `If` statement:
```
@if (Expanded)
{
    <div class="card-text">
        @ChildContent
    </div>
}
```

Instead, it should use the private field:
```
@if (expanded)
{
    <div class="card-text">
        @ChildContent
    </div>
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1#dont-create-components-that-write-to-their-own-parameter-properties)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good :eye: @codertimu! ... It was an oversight (bad cut-'n-paste! 😣) on a recent update when I copied the code down to that example from the prior example but didn't update the var ...

https://github.com/dotnet/AspNetCore.Docs/pull/19102/files#diff-6a6f708418fe3a9fd4de83332f7bf03cL660

I'll fix it right now.
