### ISSUE TITLE
Request: Tidy up ASP.NET Core documentation

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#19250]
After reading a number of ASP.NET Core documentation pages (Fundamentals section) for the last couple of days, I'm disappointed. I realize I'm losing much of my time because large chunks of content in the pages are frequently (and unnecessarily) repeated across a page.

While reading, it's generally realized that the same information that has already been read a couple of paragraphs before has been read again _after_ it's read. So, productive time is wasted instead of required information gathered.

The documentation on Routing, for example, spreads across three sprawling pages, each consisting of hundreds of paragraphs [[^1]](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1)[[^2]](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)[[^3]](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-3.1). Converted to PDF this sums up to 151 printed pages! So, just the documentation on Routing in ASP.NET alone is comprising a full-grown book on its own.

Speaking in general, the pages lack a narrative thread. A documentation page's paragraphs often are just a collection of thoughts with no cognitive relation to each other, tinkered over time. A mix of side nodes instead of structural information. Perhaps that's one of the reasons for content being copied/pasted across a page, unnecessarily bloating and blurring the documentation.

A couple of times, I find contextless information spit right in the middle of other information. I wonder if I ever will find such contextless information burried among other information later again, when I will need it.

Please tidy up documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment
