### ISSUE TITLE
Should mention that these considerations don't necessarily apply to Azure

### ISSUE THREAD

**Issue by timrobinson33** [dotnet/AspNetCore.Docs#19257]
In the page https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.1&tabs=visual-studio#data-protection-key-ring-and-deployment-slots it says "Data Protection keys are persisted to the %HOME%\ASP.NET\DataProtection-Keys folder. This folder is backed by network storage and is synchronized across all machines hosting the app."

This implies to me that for a standard azure deployment, the default configuration for data protection is applicable even when the azure app is spread over multiple machines. If this is true, I think it would be a good idea to explicitly state it here, because there are already several references to Azure, so the reader would otherwise assume that the web farm considerations apply equally to azure as to to other deployment methods.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be127bb-755c-98ab-d7fb-b3f50687857f
* Version Independent ID: 9562d8c0-563d-21ca-e802-80f9b99689ff
* Content: [Host ASP.NET Core in a web farm](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/web-farm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/web-farm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @timrobinson33 ... This topic doesn't imply or assume anything about how Azure will host. It only mentions Azure in three spots:

* As a "Scalability" example.
* Cross-link to the Azure App Service topic as a "General configuration" section link, which is where DP config for Azure App service is covered.
* As an additional resource for the Custom Script Extension.

The topic is only meant to signal to the reader the types of considerations that they must take into account when configuring an app for a web farm. The cross-links get into the details for specific approaches, including for Azure App Service.

We'll leave this for now and see if we get additional feedback on it. Thanks for commenting.
