### ISSUE TITLE
Asking for clarification in a statement on this document

### ISSUE THREAD

**Issue by krchome** [dotnet/AspNetCore.Docs#19256]
[Enter feedback here]
Hi There,

In this line "Each delegate can perform operations before and after the next delegate." vide URL:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1
Can someone clarify the context of the words "after the next delegate" which is a bit confusing?
As far as I understand, Delegate performing operations after the next delegate is only in the context of the upstream flow of response back to the client where this could hold good. 
In the request flow through the pipeline, the term "before the next delegate" is fine as it would refer to flow of request from one middleware to the next in the middleware pipeline. 
Can you please confirm if my understanding is correct? Or could the entire block be worded something like 
"Each middleware component chooses
Whether to pass on the incoming HTTP request to another middleware in the pipeline (with or without any modification) 
 Pass on the outgoing HTTP response to another middleware (or the ASP.NET Core webserver) in the pipeline (with or without any modification) "
Cheers,
Kaushik
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Keep reading any look at the code.
