### ISSUE TITLE
SignalR with Blazor Server

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#19264]
Can this be updated or forked to include how it would be done in Blazor Server as well?

I don't see anything official using or mentioning using SignalR with Blazor Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It should work with a standard app conversion.

We're keeping an :ear: open for more feedback ...

https://github.com/dotnet/AspNetCore.Docs/issues/18268#issuecomment-655527792

I think ur the 2nd reader to ask.

Given that most of the guidance will be the same, I don't think it will take a lot of effort to address it when the time comes. I wonder if we should use our shiny new **_doc pivots_** for this, where the reader can select *Blazor WebAssembly* or *Blazor Server* at the top and get a different version of the topic that focuses on each hosting model. For an example of pivots in a doc (for OS selection), see ...

https://docs.microsoft.com/aspnet/core/blazor/tooling

@BrennanConroy, do you want to continue to collect feedback, or should we go ahead and ask Artak to triage this for work?

**Comment by mrlife** [comment]
The pivot is pretty cool - it remembers which one was chosen when you return to the page.

**Comment by guardrex** [comment]
They (tabs vs. pivots vs. new docs) each have their downsides ...

* Tabs: We can't create the tab titles at-will. There's an approval process, and management might say 'no' to *Blazor WebAssembly* and *Blazor Server* tabs. They also clutter a doc when there are several of them.
* Pivots: Require in-text duplication for the common content or the use of INCLUDES.
* Multiple topics: Same as pivots (duplication or INCLUDES), and it's costlier (💰) build and maintain added topics.

**Comment by mrlife** [comment]
If it saves money, I think if it's mentioned somewhere that SignalR is compatible with all varieties of ASP.NET Core, that would be enough.

**Comment by guardrex** [comment]
In a tutorial, we expect the reader to be able to follow the topic step-by-step to a good outcome. That can't be done for Blazor Server in the topic's current form, so we either need to not proceed (close this and collect more feedback), create a new topic, or go with pivots. *I still favor pivots for this.*

Let's see what Brennan wants to do, and we'll take it from there.

**Comment by mrlife** [comment]
@guardrex Sorry, when I mentioned "somewhere", I didn't mean in the tutorial, just in the docs somewhere, if that makes a difference.

**Comment by guardrex** [comment]
It's broadly acknowledged in the Blazor overview and then picked up with specific configuration guidance in other Blazor topics, for example in the Blazor *Fundamentals* > *Additional scenarios* topic.

If we make the updates to the tutorial, it will be even better over in the Blazor docs node because this tutorial shows up *very early* in the topic reading list, and we know that readers often go right down the ToC topic list when they're learning Blazor.

**Comment by guardrex** [comment]
@BrennanConroy ... TL;DR ... The ask is for a dedicated Blazor Server pivot for *Use ASP.NET Core SignalR with Blazor WebAssembly* (with a rename to *Use ASP.NET Core SignalR with Blazor*). Do you want me to proceed, or shall we save the 💰 for other things and close this as a *won't fix*?

**Comment by BrennanConroy** [comment]
We might need a **pivot** for server side Blazor as there are gotchas that don't apply to WebAssembly. Would need Blazor experts to weigh in on what some of those might be.

**Comment by guardrex** [comment]
Ok ... I'll set up the PR with the general Blazor Server guidance pivot. Then, we can add the gotcha scenarios to it from this issue if they land in a comment here or on the PR if they land in a comment on the PR.

I think I can get to this soon ... probably either Friday or Saturday. I'll call for review on Monday if all goes well 🤞.

**Comment by guardrex** [comment]
@BrennanConroy ... The draft PR is up at https://github.com/dotnet/AspNetCore.Docs/pull/21271, but don't look yet. I need to hit that again on Friday morning to iron the 🐞🐞🐞 out. However, you can post the **_gotchas_** 😈 in here if you want for me to include in the PR tomorrow. Otherwise, I should be able to wrap that PR up tomorrow and call for review, then we'd pick up with gotchas to add over there. I'm mentioning this on the issue here so that you don't get pinged a lot over there tomorrow morning if I need to make a bunch of commits to the PR.

**Comment by BrennanConroy** [comment]
Thanks, but I'll get pinged since you included "SignalR" in the title and I filter on that 😉 (not an issue at all so don't worry)
