### ISSUE TITLE
A typo in Customize WebApplicationFactory section

### ISSUE THREAD

**Issue by MatsyshynAnton** [dotnet/AspNetCore.Docs#19263]
Hi everyone! I'm working on integration tests in my web application, and trying to customize WebApplicationFactory. I found sample [here](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory), but when I tried it, it didn't work.

I think there is a mistake when from app's context remove `DbContextOptions<ApplicationDbContext>` instead of `ApplicationDbContext` (in 9 line). When I noticed that, I change `DbContextOptions<ApplicationDbContext>` to `ApplicationDbContext` and all worked as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MatsyshynAnton ...

The app runs here in it's present form ...

<img width="284" alt="Capture" src="https://user-images.githubusercontent.com/1622880/87944986-bbd49400-ca65-11ea-93c8-ac2b6773e3f8.PNG">

... but your SUT's dB context might be registered differently.

I see two registrations when the sample solution's SUT runs ...

> Service: Microsoft.EntityFrameworkCore.DbContextOptions`1[[RazorPagesProject.Data.ApplicationDbContext, RazorPagesProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
>      Lifetime: Scoped
>      Instance: 
> Service: RazorPagesProject.Data.ApplicationDbContext
>      Lifetime: Scoped
>      Instance: RazorPagesProject.Data.ApplicationDbContext

I wonder if it should be `ApplicationDbContext` and we didn't update it when some changes were made over the history of this document. This topic is one of our older topics, and it has received a couple of rounds of significant updates over the years. This might have been a line update that was missed.

We can't ask engineering a question about this at the moment. The engineer who works with us to maintain this topic is heads-down on high priority work for the next couple of weeks. 🏃

I'll schedule this and ask him when he gets free. Until then, I'm glad you found an approach that works for you.

Note to self: I don't think it's necessary to check for a `null` descriptor before calling `Remove`. If `Remove` doesn't find it, I believe it will just return `false` (i.e., not throw).

**Comment by guardrex** [comment]
@MatsyshynAnton ... Can you show your SUT's db context? Did you set it up exactly like the SUT does? ...

```csharp
public class ApplicationDbContext : IdentityDbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }
    
    ...
```

**Comment by MatsyshynAnton** [comment]
@guardrex Thank you for response :) Looks like here is my mistake
Here is my database context:
```
public class HomeworkDbContext:DbContext
    {
        public HomeworkDbContext(DbContextOptions<HomeworkDbContext> options) 
            : base(options) { }
            ...
    }
```
I have tried to replace this context with context which use SQLite in-memory database (for integration tests) like this:
```
    public class CustomWebApplicationFactory : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                var descriptor = services.SingleOrDefault(d => d.ServiceType == typeof(HomeworkDbContext));

                if (descriptor != null)
                {
                    services.Remove(descriptor);
                }

                var connection = new SqliteConnection("Filename=:memory:");
                connection.Open();

                services.AddDbContext<HomeworkDbContext>(options =>
                {
                    options.UseSqlite(connection);
                });
               ...
            }
        }
     }
```
But, **this approach didn't work**, somehow I kept working with my old database context and create/read/update/delete entities from my SQL-server.

When I tried sample from docs one more time, all start worked as expected. Here is code for my case:

```
    public class CustomWebApplicationFactory : WebApplicationFactory<Startup>
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureServices(services =>
            {
                var descriptor = services.SingleOrDefault(d => d.ServiceType == typeof(DbContextOptions<HomeworkDbContext>));

                if (descriptor != null)
                {
                    services.Remove(descriptor);
                }

                var connection = new SqliteConnection("Filename=:memory:");
                connection.Open();

                services.AddDbContext<HomeworkDbContext>(options =>
                {
                    options.UseSqlite(connection);
                });

                var sp = services.BuildServiceProvider();

                using (var scope = sp.CreateScope())
                {
                    var scopedServices = scope.ServiceProvider;
                    var db = scopedServices.GetRequiredService<HomeworkDbContext>();

                    db.Database.EnsureCreated();
                }
            });
        }
    }
```
I don't know what I did wrong first time, anyway thank you for your answer.

P. S. Sorry if I wasted your time) I found difference in code and in comment to this code and thought I can help to improve documentation.

**Comment by guardrex** [comment]
That's ok ... no worries. In fact, let's leave this open for a sec. I want to drop that conditional check. `Remove` just returns `false` if the service isn't found. The conditional check isn't doing anything there.

Also, I'd like to move the code comments into the text. They aren't localized when they're in the code like that, and I'd like to change a little bit of the language used.

This issue will close automatically when the PR merges.
