### ISSUE TITLE
Get all solution and make test in visual studio

### ISSUE THREAD

**Issue by nellonet** [dotnet/AspNetCore.Docs#19272]
hi, excuse me if my question is stupid but I don't have solution:
can I get the entire solution ../sample/3.x/Localization/ and test it in my visual studio? (I don't have clone button)
thank you for answer
nello

**Comment by guardrex** [comment]
@nellonet ... You have to be at [the top level of the repo](https://github.com/dotnet/AspNetCore.Docs). It's under the **Code** button now.
