### ISSUE TITLE
Add new section Optimized type activation

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19279]
Add `### Optimized type activation` before  `## Recommended patterns for multi-tenancy in DI` based on [this video](https://youtu.be/x-C-CNBVTaY?t=1880).

@serpent5  after #19271 merges, can you help me add this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Yep, of course. Just let me know what you need when you get there.

**Comment by serpent5** [comment]
I just watched the section on "Optimized type activation". My interpretation of that is it's not something that should be documented, as such. I think it's just another reason to prefer "proper" DI over using the service-locator. I could well be wrong though, as there wasn't much information in the video.

**Comment by Rick-Anderson** [comment]
That's what I was thinking, thanks.
