### ISSUE TITLE
Static file authorization

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19278]
Under [Static file authorization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1#static-file-authorization) say *put StaticFiles after Authorization if they want to require the static files to be authorized. That's actually the easiest way to do static file auth.* per [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/18825#discussion_r458422734)

Add `[!INCLUDE[](~/includes/requireAuth.md)]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  in   [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/18825#discussion_r458422734) , you said:

> They can put StaticFiles after Authorization if they want to require the static files to be authorized. That's actually the easiest way to do static file auth.

The problem with doing that is that until you sign-in, you have no css/javascript or any of the other resources you need to display a nice login menu and home screen.

**Comment by Rick-Anderson** [comment]
@Tratcher  calling  `UseStaticFiles` twice works, is that what you intended?

```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseDatabaseErrorPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }

    app.UseHttpsRedirection();

    app.UseStaticFiles();

    app.UseRouting();

    app.UseAuthentication();
    app.UseAuthorization();

    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(
                     Path.Combine(env.ContentRootPath, "MyStaticFiles")),
        RequestPath = "/StaticFiles"
    });

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapRazorPages();
    });
}
```

**Comment by Tratcher** [comment]
Yeah, you have one static files instance for the default wwwroot folder with public files, and another one for restricted files in another directory.
