### ISSUE TITLE
Add information about ControllerBase.Problem(), ControllerBase.ValidationProblem(), ProblemDetails, ValidationProblemDetails to this topic

### ISSUE THREAD

**Issue by IanKemp** [dotnet/AspNetCore.Docs#19282]
These methods and classes are very useful, but there seems to be little official information around their usage and how they tie back into model validation. The docs would be greatly enhanced if such information was added.

***EDIT by @Rick-Anderson*** 

- [ ] First step is create sample code with these APIs at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/mvc (create samples in validation folder you create). Use .NET 7
- [ ] Update this doc, pointing to samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@IanKemp Are there any specific questions you'd like answered in the doc? Also, have you seen https://docs.microsoft.com/aspnet/core/web-api/handle-errors?

**Comment by wildough57** [comment]
Sorry that this never got any attention.  It looks like these might be very useful.  But without any doc, not so much.  I did look at the tease included in https://docs.microsoft.com/aspnet/core/web-api/handle-errors but that's all it is, a tease.  That's the ONLY reference I can find.  No source code either.

**Comment by Rick-Anderson** [comment]
We should at least point to the source.

**Comment by wildough57** [comment]
Thanks, that would be helpful.
It would also be nice to know why the Problem() and ValidationProblem() methods of the ControllerBase have no overloads accepting the ProblemDetail/ValidationProblemDetail objects as parameters.
