### ISSUE TITLE
`int.MaxValue - 10` as default value for `Order` in `HttpResponseExceptionFilter` class.

### ISSUE THREAD

**Issue by fyodorklimenko** [dotnet/AspNetCore.Docs#19281]
[EDIT by guardrex to add the metadata. @fyodorklimenko, Use the **This page** feedback button and form at the bottom of the English US topic to open new issues. It will add the metadata automatically and ping the author of the topic for you.]

Hey!

I found this line: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors/samples/3.x/Filters/HttpResponseExceptionFilter.cs#L10

As you can see the default value for `Order` property is `int.MaxValue - 10`.
Why do you use `- 10`? If you want to set the max value you should use `int.MaxValue`.

Could someone explain it to me?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#configuring-status-code-pages)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
