### ISSUE TITLE
Missing blazor WebAssembly tooling instructions at link

### ISSUE THREAD

**Issue by rollandjb** [dotnet/AspNetCore.Docs#19291]
[EDIT by guardrex to change the metadata]

Debug instructions [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-3.1#visual-studio-code) where it says:

> For information on installing Visual Studio Code for Blazor app development, see [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-3.1).

brings you to this page, which, for mac, only says _Install Visual Studio for Mac_, and nothing about vs code setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-3.1#visual-studio-code)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rollandjb ... Management recently decided to recommend that users on Mac use VS for Mac and users on Linux to use VS Code. Follow the instructions on the Linux tab to get VS Code.

I'll fix the line in the Debug WebAssembly topic to point directly to the VS Code install page. Thanks for calling it out.
