### ISSUE TITLE
Document Internal Workings/Implementation of AspNetCore Framework.

### ISSUE THREAD

**Issue by vnwonah** [dotnet/AspNetCore.Docs#19290]
The dotnet ecosystem has seen a shift towards working more openly since large parts of the frameworks became open source, however, for such a widely used framework, we are seeing orders of magnitude fewer oss (non -Microsoft) contributors than similar frameworks in other ecosystems.

One of the reasons for this is documentation, an area that if improved, can make all the difference.

The documentation that tells you how to do things is fantastic, usually up to date, well organized and versioned (Kudos!), the trouble starts when you have to do some customization on the framework itself, and realize you need to understand how things work together, for this there's almost no documentation.

I believe that more people will contribute to dotnet's oss if there are clear documents on how the framework works, where to find x, design decisions, documents, etc.

Several good people from Microsoft have mentioned on [twiter](https://twitter.com/vnwonah/status/1285960306129240065?s=20) that the team will be focusing on this effort, while that's a great idea, I think doing this in tandem with the community, as opposed to just getting it done and handing it out will go a long way. 

As always, I'm happy to help these efforts and I'm sure several other contributors are willing.

Thanks!

**Comment by scottaddie** [comment]
Thank you for opening this issue, Vincent! Adding @davidfowl, as I know he was involved in the Twitter thread too.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
