### ISSUE TITLE
Cannot open Client-Side Package Manager

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#19295]
Anyone know why "Client-Side" Package Manager will not come up?
When I click on Manage client-side library, libman.json pops up.
Cannot get the GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d69ef46-689c-33d0-c86b-078c8172c480
* Version Independent ID: 519af8ab-78e5-88c9-f268-431f417eca73
* Content: [Use LibMan with ASP.NET Core in Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/libman/libman-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/libman/libman-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved issue to the engineering repo for review.
