### ISSUE TITLE
Can't get groups from claimms

### ISSUE THREAD

**Issue by swannet** [dotnet/AspNetCore.Docs#19304]
I setup my project based on the doc’s (https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-3.1) and authentication is working fine.

On https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1 I found this:
“The single groups claim sent by AAD presents the user's groups and roles as Object IDs (GUIDs) in a JSON array. The app must convert the JSON array of groups and roles into individual group claims that the app can build policies against.

I’ve setup the "groupMembershipClaims" to "SecurityGroup" in the manifest of my app. But the ‘groups’ claim is missing. The only claim I found is ‘hasGroups: true’.

How can I get the groups as claim in my authentication process using Blazor WebAssembly? 

Extra info:
My ‘old’ ASP.NET core 3.1 project is working and I got the groups claim correctly. This one is using “AzureAD” scheme. The new backend project is using “AzureADBearer” as scheme and I can’t find a way to setup a scheme in the ClientApp. Are the missing claims the result from the different scheme? If so, is it possible to use the AzureAD scheme in the ClientApp? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @swannet ...

> The only claim I found is ‘hasGroups: true’.

It means that the user has more than five groups. Azure sends this claim and then the app should make a separate Graph API call to get the user's groups.

We have an issue to address this at https://github.com/dotnet/AspNetCore.Docs/issues/18510.

Azure docs are mentioned in my remark at :point_right: https://github.com/dotnet/aspnetcore/issues/22197#issuecomment-634755817

The Graph API call can be made in the `CustomUserFactory` where the app is setting the `group` claim. When you detect the `hasGroups` claim there, make the Graph API call, get the full security groups, and then make a separate `group` claim in the user identity for each security group. I don't have a full working example yet, but I can ping you on #18510 as soon as I have something.

I'll close this as a duplicate. I'll move the priority up to P1 (high priority) on that issue and try to work it up on Monday (7/27). It might get pushed back if Monday get slammed with high priority work, but I'm not expecting anything to interfere with this right now.

**Comment by guardrex** [comment]
@swannet ... I have a working draft now. Do you need me to paste it in here, or can you wait until the PR is put up tomorrow (Tuesday, 7/28) morning? I can ping u on the PR tomorrow if that's ok.

**Comment by swannet** [comment]
I can wait for the PR, have planned to look at it next week. So no need to hurry!
