### ISSUE TITLE
What are the limits on concurrent connections in ASP.NET Core SignalR

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#19307]
Since connections as persistent between client and server, is there a way to find out how many concurrent connection can be kept open per server ?
How do i estimate the sizing when deploying it to Azure App Service ?
How do i estimate the sizing if i decide to use Azure SignalR Service ?

When does server release the connection, if client closes the app, so that server can accommodate other clients ?

I am creating a an app where i cannot predict the number of connected users but at the same time want honor all clients that will connect.
Say creating app for foot ball or soccer match, this is mostly a one way from server to client communication, what consideration or optimizations one should think about or consider in such scenarios?

**Comment by guardrex** [comment]
Hello @nssidhu ...

For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
