### ISSUE TITLE
Missing deployment information 

### ISSUE THREAD

**Issue by kenleese** [dotnet/AspNetCore.Docs#19303]
The page text provides a link to further information: “ For more deployment samples, see the Web SDK repository Readme.”

Unfortunately due to repo reorg it no longer contains anything useful. Where is this additional content now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@AngelosP can you recommend a new link?

**Comment by scottaddie** [comment]
@kenleese Here's a permalink to the README file: https://github.com/dotnet/websdk/blob/0e8c90a4a71c98a0eae4311fa53176843fdf84bf/README.md. @vijayrkn is working on moving this info to the root of the dotnet/websdk repo.

**Comment by kenleese** [comment]
Thank you.
Respectfully, perhaps it would be an improvement to move this useful content into the docs.

**Comment by scottaddie** [comment]
I think that's a great idea. It would prevent this issue from occurring again in the future. The content would also get localized in the docs. I'll work with @vijayrkn to make this happen.
