### ISSUE TITLE
Clarity on how to "Reference the Brotli decoder" for Blazor stand-alone app

### ISSUE THREAD

**Issue by HillPhelmuth** [dotnet/AspNetCore.Docs#19302]
This is a little unclear how exactly to get from 

>Reference the Brotli decoder from the google/brotli GitHub repository in the app

To the 

> Update the app to use the decoder. Change the markup inside the the closing <body> tag in wwwroot/index.html to the following...

And the brotli Github repo itself has a variety of ways to install brotli, but I'm assuming that's not what this document is intending. 
Do we just need to copy the decode.js file into wwwroot and then modify index.html, or is there more to it than that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @HillPhelmuth ... This is a scenario that I haven't personally tried yet. Yes, that's my take on it. Let's confirm ......

@mkArtakMSFT ... Is the intention to get `decode.min.js` from the following for this ...

https://github.com/google/brotli/blob/master/js/decode.min.js
