### ISSUE TITLE
Is and example of Slug style routing where it's typical to have an article name as part of the URL.

### ISSUE THREAD

**Issue by kobedddh** [dotnet/AspNetCore.Docs#19309]
Is **and** example of Slug style routing where it's typical to have an article name as part of the URL. 
should be replaced with
Is **an** example of Slug style routing where it's typical to have an article name as part of the URL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5

**Comment by serpent5** [comment]
@Rick-Anderson Is it OK to fix this and https://github.com/dotnet/AspNetCore.Docs/issues/19311 as part of the same PR, or do you prefer for them to be two separate PRs?

**Comment by Rick-Anderson** [comment]
Your call, either way.
