### ISSUE TITLE
Invalid link for an example of dotnet aspnet-codegenerator controller

### ISSUE THREAD

**Issue by Xymanek** [dotnet/AspNetCore.Docs#19311]
```
See Scaffold the movie model for an example of dotnet aspnet-codegenerator controller.
```

The above links to https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model which is about razor pages, not controllers...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  can you change this to https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller
