### ISSUE TITLE
Your example code throws an error.

### ISSUE THREAD

**Issue by wrc3** [dotnet/AspNetCore.Docs#19313]
This line throws an error in your code.

services.AddDbContext<TodoContext>(opt =>
               opt.UseInMemoryDatabase("TodoList"));

DBContextOptionsBuilder does not contain a defintion for 'UseInMemoryDatabase' and no accessible extension method....

Kind of sucks to work through code trying to learn and find out it doesn't work.

B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wrc3 ... Looks like you may have missed a line ...

> Use the preceding instructions to add the `Microsoft.EntityFrameworkCore.InMemory` NuGet package.

**Comment by wrc3** [comment]
Yep you are right. Walked right over that one.  Sorry.

B

On Jul 24, 2020, at 14:59, Luke Latham <notifications@github.com> wrote:

﻿

Hello @wrc3<https://github.com/wrc3> ... Looks like you may have missed a line ...

Use the preceding instructions to add the Microsoft.EntityFrameworkCore.InMemory NuGet package.

**Comment by guardrex** [comment]
No worries ... it's happened a few times. I think ultimately if we keep getting this report that Rick will probably do something to make that step more prominent.

**Comment by Rick-Anderson** [comment]
> I think ultimately if we keep getting this report that Rick will probably do something to make that step more prominent.

We did

# Add NuGet packages

**Comment by guardrex** [comment]
Right, but that section doesn't plainly list those two packages ... they're in the instruction text. That fifth bullet item seems like it's getting away from a few readers. I wasn't suggesting doing anything about it now ... I just meant if devs keep writing in about it.

**Comment by Rick-Anderson** [comment]
@serpent5  can you change `Microsoft.EntityFrameworkCore.InMemory` to **Microsoft.EntityFrameworkCore.InMemory** or even ***Microsoft.EntityFrameworkCore.InMemory*** ?

**Comment by serpent5** [comment]
@Rick-Anderson Is it alright if I switch the `/dotnet/api` links over to xrefs as part of this? It feels like I'm being more valuable that way. 😄

**Comment by Rick-Anderson** [comment]
> switch the /dotnet/api links over to xrefs 

Yes, xrefs is preferred.

**Comment by Rick-Anderson** [comment]
But we should make it bold. People won't following the directions when it's not bold :)

https://github.com/dotnet/AspNetCore.Docs/issues/19346
