### ISSUE TITLE
Not helpful for VS Code Users

### ISSUE THREAD

**Issue by lonpalmer** [dotnet/AspNetCore.Docs#19312]
This section:
```
Debug standalone Blazor WebAssembly
Open the standalone Blazor WebAssembly app in VS Code.

If you receive the following notification that additional setup is required to enable debugging:

Confirm that you have the correct extensions installed.
Confirm that JavaScript preview debugging is enabled.
Reload the window.

```

Doesn't help anyone.  Need to add a lind to the "Correct Extensions" that should be installed and also a link to enable "JavaScript preview debugging"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-3.1#vscode)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @lonpalmer ...

... also "extensions" should be singular. It should just require the **C# for Visual Studio Code extension**, which is mentioned in the **Linux** version of the [Tooling doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-3.1&pivots=os-linux).

Preview debugging is in the IDE's **Settings**. Try search the settings for "preview" ...

<img width="441" alt="Capture" src="https://user-images.githubusercontent.com/1622880/88422421-dbdebd00-cdaf-11ea-8b87-a264357b9044.PNG">
