### ISSUE TITLE
Promote `Prevent over-posting` section to be the main section

### ISSUE THREAD

**Issue by tymtam2** [dotnet/AspNetCore.Docs#19327]
I understand that this may seen as opinion based, but exposing db models is bad practice. By a db model I mean a class that is used by the DbContext to interact with the db;

I believe that using DTOs from the start produces better solutions, even when the mapping is one to one to the db model (i.e. all properties match). (One of the advantages of this is that the DTOs can be immutable.)

I think that the official documentation showing exposing db models encourages bad practice and the fact that the article contains `Prevent over-posting` section confirms that DTOs are the way to go. It also may be confusing to new readers that two approaches are shown. 

I suggest making the article use DTOs in the main part and maybe just mentioning that DTOs are not technically needed. 

This way the article will be shorter and will tip readers into the pit of success.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion.
