### ISSUE TITLE
JsonPatch fix for ASP.NET Core 3.1 no longer works?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/AspNetCore.Docs#19320]
I've done as instructed by writing the following snippet of code
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews(options =>
    {
        options.InputFormatters.Insert(0, GetJsonPatchInputFormatter());
    });
}

private static NewtonsoftJsonPatchInputFormatter GetJsonPatchInputFormatter()
{
    var builder = new ServiceCollection()
        .AddLogging()
        .AddMvc()
        .AddNewtonsoftJson()
        .Services.BuildServiceProvider();

    return builder
        .GetRequiredService<IOptions<MvcOptions>>()
        .Value
        .InputFormatters
        .OfType<NewtonsoftJsonPatchInputFormatter>()
        .First();
}
```
But it doesn't seem to work at all. I get the same PatchDocument error as per usual.

An example of my Endpoint (deriving from `ControllerBase`)

```
        [HttpPatch("save")]
        public TaskDto SaveObject([FromBody] JsonPatchDocument<SampleObject> patchDoc)
        {
            var obj= new SampleObject();
            patchDoc.ApplyTo(obj);
            return obj;
        }
```

If I just include the Newtonsoft json serializer into the service collection, it all works, but I lose the benefits of Microsoft's System.Text.Json package, as the serializer is now Newton's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-3.0#jsonpatch-addnewtonsoftjson-and-systemtextjson)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> If I just include the Newtonsoft json serializer into the service collection, it all works, 
currently JSON patch requires `NewtonsoftJson`

**Comment by SpiritBob** [comment]
@Rick-Anderson docs say you can still leverage `System.Text.Json` by doing the above snippet of code? But that's not the case at all!

**Comment by Rick-Anderson** [comment]
Where does it say that? What exactly. It says:
currently JSON patch requires `NewtonsoftJson`

**Comment by SpiritBob** [comment]
Direct quote from documentation:

> `AddNewtonsoftJson` replaces the `System.Text.Json`-based input and output formatters used for formatting all JSON content. To add support for JSON Patch using `Newtonsoft.Json`, **while leaving the other formatters unchanged**, update the project's `Startup.ConfigureServices` method as follows:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews(options =>
    {
        options.InputFormatters.Insert(0, GetJsonPatchInputFormatter());
    });
}

private static NewtonsoftJsonPatchInputFormatter GetJsonPatchInputFormatter()
{
    var builder = new ServiceCollection()
        .AddLogging()
        .AddMvc()
        .AddNewtonsoftJson()
        .Services.BuildServiceProvider();

    return builder
        .GetRequiredService<IOptions<MvcOptions>>()
        .Value
        .InputFormatters
        .OfType<NewtonsoftJsonPatchInputFormatter>()
        .First();
}
```

The text in bold is where I believe it says that. The code snippet included is part of the documentation - using it as provided does nothing - the json converter fails to convert incoming JSON to `JsonPatchDocument`.

**Comment by serpent5** [comment]
The approach in the topic works. What are you sending as the `Content-Type` and what's the error?

**Comment by sarahbe** [comment]
I am having the same issue and the same configuration  mentioned above. 

`{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|f5ba494d-422d1595d82115d9.",
    "errors": {
        "$": [
            "The JSON value could not be converted to Microsoft.AspNetCore.JsonPatch.JsonPatchDocument`1[Portal.Web.DataModels.TestModel]. Path: $ | LineNumber: 0 | BytePositionInLine: 1."
        ]
    }
}`

**Comment by SpiritBob** [comment]
Minimal reproducible repository/solution: https://github.com/SpiritBob/BrokenJsonPatch

Could we finally get back to opening this issue?

**Comment by serpent5** [comment]
> Minimal reproducible repository/solution: https://github.com/SpiritBob/BrokenJsonPatch

This also works when I try it. You must use `application/json-patch+json` as the `Content-Type` for the request being sent to that controller. If you use `application/json`, you'll see the error message shown in @sarahbe's comment.
