### ISSUE TITLE
With Core 3.1, unless I disable Antiforgery, MultipartReader.ReadNextSectionAsync() causes error "Unexpected end of Stream"

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/AspNetCore.Docs#19322]
When streaming file uploads, you say that Antiforgery is good and should be used, but in Razor Pages ASP.Net Core 3.1, unless I disable Antiforgery, MultipartReader.ReadNextSectionAsync() causes error "Unexpected end of Stream". It seems that Antiforgery reads the content body, and so the stream has already been read.

See my comment here that has an attached sample app that reproduces it:
https://github.com/dotnet/aspnetcore/issues/18087#issuecomment-663890220

I'm submitting this docs issue, so that you are aware of the problem. I'm guessing this is a bug, and that we shouldn't have to disable Antiforgery?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Dean-NC ... Since engineering hasn't determined the cause of what you reported (or even if it's the same problem reported by others there), we'll need to wait until it's resolved over there. Ping back here when it's been resolved over there, then we can re-open this and work on the doc+sample if needed.
