### ISSUE TITLE
Doesn't show what to add in Progarm.cs File

### ISSUE THREAD

**Issue by smjltd** [dotnet/AspNetCore.Docs#19324]
[Enter feedback here]

Missing Program.cs example to add configurations on startup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7367a651-2b27-0a57-e7d0-95686cc97f1c
* Version Independent ID: 8c769648-728d-72ce-ebf6-2a06e5076aa2
* Content: [ASP.NET Core Blazor configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @smjltd ... The topic shows when adding code to `Program.Main` is required. Can you be more specific ... exactly what are you trying to do?

**Comment by smjltd** [comment]
for the first example wwwroot/appsettings.json

@page "/"
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<'h1>Configuration example</h1'>

<'p>Message: @Configuration["message"]</p'>

what should be in Program.Main is not clear

**Comment by guardrex** [comment]
Nothing ... app settings from `appsettings.json` and `appsettings.{ENVIRONMENT}.json` are loaded by default. It's stated in the opening remarks ...

> Blazor WebAssembly loads configuration from:
>
> * App settings files by default:

**Comment by guardrex** [comment]
FYI ... to make code blocks work in GH comments, use triple-backticks above and below the code ...

> \`\`\`
> ... code ...
> \`\`\`

**Comment by smjltd** [comment]
But for some reason the configuration doesn't load at start. it always start's with null

https://stackoverflow.com/questions/63097669/blazor-webassembly-configuration-appsettings-json-loading-null-values-in-compo

**Comment by guardrex** [comment]
Works here. Show the contents of your `appsettings.json` file.

**Comment by guardrex** [comment]
Try using a capital "C" for "configuration" ...

```razor
@Configuration["message"]
```

**Comment by smjltd** [comment]
Here is an example;

{
  //App
  "TasksListGuid": "965A8914-1990-4801-998E-A513794F008B",
  "TaskHistoryListGuid": "9FA09951-1B05-4E82-8F4D-16F0B6380094",
  "TaskListName": "Workflow Tasks",
  "ViolationTypeListGuid": "5E47A409-9F44-48ED-9A85-706F5CFAC390",
  "MainListGuid": "DBC926D0-66ED-4A03-9A2D-BDB34B34224A",
  "MainListType": "SP.Data.MainListItem",

}

**Comment by guardrex** [comment]
In your SO post ... `OnParametersSetAsync` ... that's not a thing any longer. Are you following some old blog post? See the Lifecycle topic ...

https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle#before-parameters-are-set

It will work if you use `SetParametersAsync`.

**Comment by smjltd** [comment]
I am getting the value's correctly but always null first then re-renders with correct values, i am using OnParametersSetAsync() as entry point, i understand OnParametersSetAsync() changes on every Parameter Change. but the Configuration Values should be constant not null first right?

**Comment by guardrex** [comment]
OH ... my bad. Strike that. Stand by.

**Comment by smjltd** [comment]
OnParametersSetAsync still exists 😁

**Comment by guardrex** [comment]
I know. I just woke up. It's 6:30am here. :smile:

**Comment by smjltd** [comment]
I am trying to switch my project from just constant's in Constants/Settings.cs to appsetting.json found this issue.

Old Way Example Project:
https://github.com/smjltd/BlazorPoint/blob/master/Pages/Log.razor

**Comment by guardrex** [comment]
In testing here, I do see it being called twice, but I can't repro a configuration value being `null` on the first call.

Open an issue for engineering at https://github.com/dotnet/aspnetcore/issues. 

They prefer not to look at dev code, which slows them down. Either just ask without showing code or try to show a minimalist example that demos the problem.

Can you add a `cc: @guardrex` to your opening comment? No worries tho if you don't ... you can either add a comment back here in case we need to add a remark to the document or they'll ping me there or open an issue when they see that something is missing from the coverage. I'll re-open this issue for work if they identify what's going on and determine that we need more guidance.
