### ISSUE TITLE
The maximum number of websocket  connections

### ISSUE THREAD

**Issue by Heroins** [dotnet/AspNetCore.Docs#19330]
I create an object with the code in AspNetCore.Docs-master\aspnetcore\fundamentals\websockets\samples\2.x\WebSocketsSample， and i try use page to use websocket connect the services，The maximum number of connections seems like is 10， The pages after that cannot be connected websocket， state is Connecting。How can I connect more pages？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Are you running on IIS 7 on windows 10?

**Comment by Heroins** [comment]
> Are you running on IIS 7 on windows 10?

yes  , I'm very confused about why the maximum number of websocket connections is 10. I didn't find a profile address that could change this maximum number of connections.

**Comment by davidfowl** [comment]
I believe that's a windows client limit specifically on IIS. I'd recommend using kestrel instead if this is for local development

**Comment by davidfowl** [comment]
Or if you're dead set on using IIS get windows sever

**Comment by Heroins** [comment]
> Or if you're dead set on using IIS get windows sever or use IIS express

i had try IIS express but it seems the max is 10， if there has no other way,that i have to use kestrel

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
