### ISSUE TITLE
ActionFilter: code block can be moved out of foreach scope

### ISSUE THREAD

**Issue by merlinko637** [dotnet/AspNetCore.Docs#19331]
In the ActionFilter section, 

this:
      
```
foreach (var address in ip)
{
    if (remoteIp.IsIPv4MappedToIPv6)
    {
        remoteIp = remoteIp.MapToIPv4();
    }
    var testIp = IPAddress.Parse(address);
    if (testIp.Equals(remoteIp))
    {
        badIp = false;
        break;
    }
}
```

can be simplified to this:

```
if (remoteIp.IsIPv4MappedToIPv6)
{
    remoteIp = remoteIp.MapToIPv4();
}

foreach (var address in ip)
{
    var testIp = IPAddress.Parse(address);
    if (testIp.Equals(remoteIp))
    {
        badIp = false;
        break;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @merlinko637 ... I'll fix that up.
