### ISSUE TITLE
Nested maps

### ISSUE THREAD

**Issue by icelava** [dotnet/AspNetCore.Docs#19349]
For nested request mapping, where do the level1App, level2AApp, and level2BApp objects come from? I suppose they're all IApplicationBuilder but where're their definitions of origin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  can you answer this?

**Comment by serpent5** [comment]
>     app.Map("/level1", level1App => {
>         level1App.Map("/level2a", level2AApp => {
>             // "/level1/level2a" processing
>         });
>         level1App.Map("/level2b", level2BApp => {
>             // "/level1/level2b" processing
>         });
>     });

`level1App`, `level2AApp`, and `level2BApp` are all implementations of `IApplicationBuilder`. The second argument passed into `Map` is a callback function. The framework creates an implementation of `IApplicationBuilder` that's preconfigured for the path, e.g. `"/level"`, and passes it to your callback function.
