### ISSUE TITLE
Improve Doc readability

### ISSUE THREAD

**Issue by tarekahsan709** [dotnet/AspNetCore.Docs#19346]
The instruction to add Microsoft.EntityFrameworkCore.SqlServer is in bold text. Also others major instructions too. But the instruction to add Microsoft.EntityFrameworkCore.InMemory is not bold. While going through the doc I missed this instruction and spent few times to figure it out. It would be helpful to bold this text for preventing lose concentration. 

Link: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#add-a-database-context
  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Bold is for UI and `InMemory` is correctly formatted because in this context it's not UI, but code. It's being changed anyway.
