### ISSUE TITLE
Possibly Update Information (?)

### ISSUE THREAD

**Issue by Deadened** [dotnet/AspNetCore.Docs#19347]
As appsettings.json has been faded out in favor of .csproj. Would it be possible to update the tutorial (Web API with MongoDB) to use .csproj instead of appsettings.json? That is, could someone update the examples/explanation to use csproj over json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @Deadened ... Where did you hear that?

*appsettings.json* is the default, primary configuration file for ASP.NET Core apps. The project file (*.csproj*) handles the app's package references, target framework, and other compiler settings.
