### ISSUE TITLE
Move Web SDK samples to docs

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#19351]
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/19303#issuecomment-663750217. Relocate the content at https://github.com/dotnet/sdk/tree/master/src/WebSdk to docs, perhaps in https://docs.microsoft.com/aspnet/core/host-and-deploy/visual-studio-publish-profiles. Once relocated, remove the README file's content and replace with a link to the conceptual doc.

**Comment by Rick-Anderson** [comment]
@scottaddie  I question value moving this provides. Google does a good job of translating the content for other languages. You've fixed the link, so maybe we should close this issue.

This is a very low priority in our backlog, and moving the doc to our repo would incur a maintenance load. Where it's at the Dev team updates it.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
