### ISSUE TITLE
Include details on how to debug on Linux

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/AspNetCore.Docs#19367]
It would be nice if this page got updated to also work for Linux, as it apparently requires a lot of workarounds to debug a Blazor WebAssembly application which are not very obvious. (I can't get it to work on Ubuntu 18.04 LTS)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JansthcirlU ... Are you referring to VSC on Linux? That should work as described.

**Comment by captainsafia** [comment]
Not that I am aware. @JansthcirlU Can you help us understand the issues you are running into that should be better documented?

**Comment by JansthcirlU** [comment]
@captainsafia @guardrex I created a new Blazor WebAssembly project, and when trying to run it I get the following exception:

```csharp
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Components.Web.DevServer.Commands.ServeCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args)
```
So I go to the link in the exception and follow the instructions there, but here's the output from my terminal:
```
$ dotnet dev-certs https --clean
HTTPS development certificates successfully removed from the machine.
$ dotnet dev-certs https --trust
Specify --help for a list of available options and commands.
```
So I'm stuck not being able to update the certificates on Ubuntu, hence not being able to debug.

**Comment by guardrex** [comment]
Those instructions are for macOS and Windows only.

You'll have to create and supply a cert for the app per the Kestrel guidelines ... 

https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel#listenoptionsusehttps

**Comment by guardrex** [comment]
Our guidance in the Get Started topic for Linux is ...

> See the documentation for your Linux distribution on how to trust the HTTPS development certificate.

https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-3.1&tabs=linux#trust-the-development-certificate

That seems like a weak UE to me, but that's what has been approved for the Linux scenario.

**Comment by JansthcirlU** [comment]
@guardrex I managed to get the app to run after running `dotnet dev-certs https` without any extra parameters, but I still can't debug it.

**Comment by guardrex** [comment]
That's cool. I'm glad that worked. The guidance is kind'a rough had it not worked. 🙈 

@captainsafia will be along in a bit to help with that one.

**Comment by JansthcirlU** [comment]
I'm sorry but it's getting rather late where I live, I probably won't be able to answer in the next couple of hours. Since I've accidentally run into this issue for a hobby project, I don't consider it to be a very urgent issue. Could we perhaps continue this discussion tomorrow?

**Comment by guardrex** [comment]
Of course.

**Comment by JansthcirlU** [comment]
Thanks!

**Comment by captainsafia** [comment]
@JansthcirlU Does debugging with non-HTTPS work?

You can do this by setting the `url` property in the `launch.json` configuration.

**Comment by JansthcirlU** [comment]
This is what my `launchSettings.json` looks like at the moment:
```json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:30626",
      "sslPort": 44312
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Tutorial": {
      "commandName": "Project",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:5001;https://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
Changing `applicationUrl` to `http` (for both 5001 and 5000) still yields the same VS Code error.

**Comment by captainsafia** [comment]
@JansthcirlU I meant the `launch.json` file inside the `.vscode` directory. [Our docs](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#launch-configuration-options) have more info.

**Comment by JansthcirlU** [comment]
For some reason VS Code didn't give me that notification and as a result I don't have a `.vscode` directory, is there a way to manually activate it? In the meantime I'll try to create a fresh `blazorwasm` project in an entirely new directory to see if I have more success there.

**Comment by captainsafia** [comment]
> For some reason VS Code didn't give me that notification and as a result I don't have a .vscode directory, is there a way to manually activate it? 

If you click on the `Debug` sidebar element, there's should be a hyperlink that you can click to create a launch.json file.

**Comment by JansthcirlU** [comment]
@captainsafia I'm sorry for neglecting this thread over the weekend, I have added `launch.json` from the `Debug` sidebar and it currently looks like this:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "blazorwasm",
            "name": "Launch and Debug Blazor WebAssembly Application",
            "request": "launch"
        }
    ]
}
```
Upon creating the file it prompted me to select a configuration from the dropdown list so I just picked Blazor Webassembly.

**Comment by captainsafia** [comment]
> @JansthcirlU Does debugging with non-HTTPS work?

> You can do this by setting the url property in the launch.json configuration.

Does using a non-HTTPS URL work as recommended in the comment above.

**Comment by JansthcirlU** [comment]
If I add `"url":"http://localhost:5001"` to `launch.json` I get the pop-up error again.

**Comment by captainsafia** [comment]
If should be http://localhost:5000. The non-HTTPS version of the app runs on port 5000.

**Comment by JansthcirlU** [comment]
@captainsafia Thanks, that did the trick!

**Comment by JansthcirlU** [comment]
I noticed that I get the same error if my `launchSettings.json`'s `applicationUrl` isn't the same as `launch.json`'s `url`, don't know if that has been an issue before.

**Comment by captainsafia** [comment]
>  I get the same error if my launchSettings.json's applicationUrl isn't the same as launch.json's url

It shouldn't have to be the same. You just need to make sure that the `url` in `launch.json` is included in the list of `applicationUrl`s.

**Comment by debevv** [comment]
I would like to report the same issue in Ubuntu 20.04. I can't get a Blazor app to debug in VSCode. Chrome opens, but stays on the about:blank page. After a while, I get this error popup: ![picture](https://user-images.githubusercontent.com/8508972/90137527-0a7c0200-dd76-11ea-9726-815d94a05e70.png)

This is my `launch.json`
```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "blazorwasm",
            "name": "Launch and Debug Blazor WebAssembly Application",
            "request": "launch",
            "url": "http://localhost:5000"
        }
    ]
```

**Comment by guardrex** [comment]
@debevv It's best not to post on closed issues. Also, please open the issue for engineering. We'll create a docs issue if needed after it's worked out by the product unit. Open your issue here ...

https://github.com/dotnet/aspnetcore/issues
