### ISSUE TITLE
My dotnet says: No templates matched the input template name: blazorserver

### ISSUE THREAD

**Issue by KettuJKL** [dotnet/AspNetCore.Docs#19363]
Could you please add a link for source package, SDK or something to make this work?

I do have VS 2019 installed and dotnet (should I have some specific version?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KettuJKL ... Yes, I'll add a link to the Get Started page at https://docs.microsoft.com/aspnet/core/getting-started/.

**Comment by guardrex** [comment]
Actually, we'll go with a SDK prereq. The reason is that management wanted this to be CLI based. Therefore, the dev should just grab the 3.1 or later SDK.
