### ISSUE TITLE
UseStatusCodePagesWithReExecute docs unclear

### ISSUE THREAD

**Issue by brgrz** [dotnet/AspNetCore.Docs#19364]
The docs regarding [UseStatusCodePagesWithReExecute](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#usestatuscodepageswithreexecute) are somewhat unclear.

The text says 

> If you point to an endpoint within the app, create an MVC view or Razor page for the endpoint. For a Razor Pages example, see Pages/StatusCode.cshtml in the sample app.

I am having issues trying to get the UseStatusCodePagesWithReExecute to work in an MVC app. 

Where are we supposed to create such an MVC view and what should the path to it look like? 

There is not MVC app sample available.

Further down the text says 

> The URL and query string templates may include a placeholder ({0}) for the status code. The URL template must start with a slash (/). When using a placeholder in the path, confirm that the endpoint (page or controller) can process the path segment.

Sample code only shows placeholder being used in query string templates. 

Is it really true that placeholder can also be used in the URL (path) template? Because it is not working for me.

Further, docs say "confirm that the endpoint (page or controller) can process the path segment". Here docs talk about "page or controller", while previously (see above) you were referring to a MVC view, so which is it? 

I'm posting this because I cannot get the UseStatusCodePagesWithReExecute to work, while the UseStatusCodePagesWithRedirect works just fine (but I'd wish to use the ReExecute to retain the original request URL in the browser bar).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#usestatuscodepageswithreexecute)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Where are we supposed to create such an MVC view and what should the path to it look like?

It's exactly the same as the RP endpoint. Just supply an MVC endpoint such as

`app.UseStatusCodePagesWithReExecute("/Home/StatusCode","?code={0}");`
for the Home controller.

I think when the author was writing View, he meant Controller with Views. A MVC view is not an endpoint.

**Comment by brgrz** [comment]
Yes, I assumed it was that way (via controller) but I cannot get it to work with NotFound() result. The Redirect one does work but then both the context and status code are lost.

**Comment by brgrz** [comment]
I've solved the issue I was having with UseStatusCodePagesWithReExecute. Turns out the order of Use... calls matters. I had UseStatusCodePagesWithReExecute() after UseRouting() and it didn't work (shows the browser's native status code pages). Strangely, having both UseStatusCodePages() and UseStatusCodePagesWithRedirects() after UseRouting() does seem to work. That's why I couldn't figure out what was wrong until I created a new project from scratch putting those calls before UseRouting().

I think this should be pointed out within the Docs, I'd even argue this is a bug.

**Comment by brgrz** [comment]
Having it like this doesn't work

```
			app.UseRouting();
			app.UseStatusCodePagesWithReExecute("/status-code/{0}");
```

However having the other two in the same order does work (for what they're supposed to do):

```
			app.UseRouting();
			app.UseStatusCodePagesWithRedirects("~/status-code/{0}");
			app.UseStatusCodePages();

```

**Comment by Rick-Anderson** [comment]
@JamesNK please review.

**Comment by serpent5** [comment]
@Rick-Anderson The issue mentioned just above this comment was transferred over to the docs repo by `@Tratcher`, where there's an actionable edit suggestion for this topic.

**Comment by Rick-Anderson** [comment]
Moved to Order of UseStatusCodePagesWithReExecute and UseRouting shouldn't matter #19374
