### ISSUE TITLE
Document Blazor WebAssembly .NET Standard support

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#19366]
Blazor WebAssembly 3.2 supports .NET Standard 2.1, but many APIs throw `PlatformNotSupportedExceptions` due to limitations imposed by the browser. We should broadly document these limitations and their impact.

@lewing

**Comment by guardrex** [comment]
If the notes for the content can be placed here in a comment, I'll take care of loading it into the docs.

**Comment by danroth27** [comment]
@guardrex Yup, I'm working on putting that together this week. Stay tuned!

**Comment by mkArtakMSFT** [comment]
@danroth27 what's pending here?

**Comment by danroth27** [comment]
I put together a draft of this content internally, but it needs @lewing 's review.

We should also follow up on what the plan is for documenting platform specific APIs in the API refs for .NET 5.

**Comment by danroth27** [comment]
Closing this out as we now have the [.NET Platform Compatibility Analyzer](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer) that will let you know which .NET APIs are supported in browsers.
