### ISSUE TITLE
Instructions for changing the RootNamespace are unclear, and do not appear to work

### ISSUE THREAD

**Issue by MrRWolf** [dotnet/AspNetCore.Docs#19368]
I am attempting to use a root namespace like MyCompany.MyProduct

dotnet core appears to have moved back to the .csproj format for containing assembly information.  Adding an AssemblyInfo.cs file appears to do nothing.

Adding a root namespace in the .csproj is easy:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
      <RootNamespace>MyCompany.MyProduct</RootNamespace>
      ...
```

What is unclear, is how to set ResourceLocation

No mater what I do, my injected IStringLocalizer has a ResourceNotFound=true, and a SearchedLocation field like "MyProduct.Resources.MyCompany.MyProduct.Controllers.MyController"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review. Has this changed?

**Comment by hishamco** [comment]
> Has this changed?

AFAIK Nothing changed, 

> @MrRWolf simply you can use `ResourceLocationAttribute` like this https://github.com/aspnet/Localization/blob/master/test/ResourcesClassLibraryWithAttribute/AssemblyInfo.cs#L7

FYI I refer to a very old repo, but the APIs still work the same ;)
