### ISSUE TITLE
GitHub pages sample

### ISSUE THREAD

**Issue by wilsoncg** [dotnet/AspNetCore.Docs#19370]
I notice the sample github pages repo [blazor-demo/blazor-demo.github.io](https://github.com/blazor-demo/blazor-demo.github.io) in the link is 3 years old. It contains a snapshot of various wasm.js & supplemental framework files, along with binary dlls checked in which represent the compiled blazor project. 

Would it make more sense to reference @SteveSandersonMS updated github demo sample [SteveSandersonMS/BlazorOnGitHubPages](https://github.com/SteveSandersonMS/BlazorOnGitHubPages)? I notice this reference is a better starting point as it has all the blazor starting points you'd expect (razor & .cs files). It also has a github actions workflow file ready to go.

Another option would be to take Steve's sample and just copy over on top of the blazor-demo/blazor.demo.github.io repo, that way if Steve forgets his sample is referenced in the docs and deletes his sample repo, then it does not leave a broken link in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#github-pages)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wilsoncg ... Yes, I agree. I'll send him a PR to update the versions on that project and then work on the cross-link update. Thanks for calling it out.

**Comment by guardrex** [comment]
I'm not sure if he's really going to maintain that. I think our best bet might be to maintain the content here. I mean get that *github actions workflow file* coverage into the doc here along with anything else that's needed to make it work.
