### ISSUE TITLE
Dependency injection is not covered in tutorial

### ISSUE THREAD

**Issue by DarkChocoholicDev** [dotnet/AspNetCore.Docs#19379]
The tutorial indicates that the reader will learn about Dependency Injection in the tutorial, yet the tutorial doesn't cover it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @DarkChocoholicDev ... It was leftover from an earlier version of the tutorial that spoke to it. I'll knock that list item out right now.

**Comment by guardrex** [comment]
I'll leave the routing remark tho. That's there.
