### ISSUE TITLE
Razor.RuntimeCompilation instructions are only valid for IISExpress

### ISSUE THREAD

**Issue by PredatH0r** [dotnet/AspNetCore.Docs#19389]
The documentation fails to mention that editing a .cshtml in VisualStudio will only change the live page when using IISExpress.
This does not work when using Kestrel or HTTP.sys as a host.

However, when using HTTP.sys, Razor will recompile and use a modified .cshtml file located in the project output folder.
i.e. when setting a .cshtml file to "Copy to Output Directory: Copy if newer" and then editing the file in the output folder.
Unfortunately this is very unpractical to work with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It works fine with Kestrel when you follow the instructions to Enable runtime compilation

**Comment by PredatH0r** [comment]
Sorry for the trouble, the error was on my end.
The VS Project was configured to "Launch: Executable" with the .exe in the Debug output folder - and that doesn't work with recompilation.
After copying the configuration from a blank project with "Launch: Project" it worked as expected with IISExpress, Kestrel and Http.sys
I leave this here just in case someone else is in a similar situation.
