### ISSUE TITLE
UseInMemoryDatabase don't works

### ISSUE THREAD

**Issue by queirozsume** [dotnet/AspNetCore.Docs#19386]
That tutorial was writed for dotnet 3.0, but right now it is at 3.1. I can't compile the "UseInMemoryDatabase", because it returns a error. I have leave that tutorial, and started an other issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @queirozsume ... You need a package reference to `Microsoft.EntityFrameworkCore.InMemory`.

https://docs.microsoft.com/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#add-nuget-packages
