### ISSUE TITLE
Clarify ARM template parameter

### ISSUE THREAD

**Issue by gantta** [dotnet/AspNetCore.Docs#19388]
The ARM template code snippet references a paramater named aspnetcoreVersion, however there is no documentation that I can find that specifies the allowable values for this paramater.

![Annotation 2020-07-31 103713](https://user-images.githubusercontent.com/12602697/89045635-d4706400-d319-11ea-967d-913166eaa36e.png)

The siteextensions reference page doesn't include any additional details either: (https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/sites/siteextensions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
@pakrym ... It appears in one of your repos at https://gist.github.com/pakrym/f22f813806b8d42c1ac212904b562d20. Can you provide more info? 

@glennc ... It's also in one of your blog posts at https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-0-preview1-using-asp-net-core-previews-on-azure-app-service/.

**Comment by pakrym** [comment]
The variable is the version of the site extension package wit th
I think this template might be a bit outdated for a couple of reasons:
1. We started producing extensions with AspNetCoreRuntime.X.X name after 3.0 release
2. I'm not sure there is a siteextension for 5.0 at all.

**Comment by guardrex** [comment]
@davidebbo ... I see you've remarked on this subject at least once in my research.

For the ARM template example at the end of the following section ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.1&tabs=visual-studio#install-the-preview-site-extension

Can I set the file up in the following way ...

* The `name` adopts the latest naming of runtime site extensions.
* The `version` explicitly states the version.

Perhaps, use the following example ...

```json
{
    "type": "siteextensions",
    "name": "AspNetCoreRuntime.5.0.x64",
    "apiVersion": "2015-04-01",
    "location": "[resourceGroup().location]",
    "properties": {
        "version": "5.0.0-rc-2-20475-17"
    },
    "dependsOn": [
        "[resourceId('Microsoft.Web/Sites', parameters('siteName'))]"
    ]
}
```

... but even if so, is that `apiVersion` correct?

Perhaps, add that the `name` and `version` can be set up with parameters ...

* `"name": "[parameters('extensionName')]`
* `"version": "[parameters('aspnetcoreVersion')]"`

What I'd really like to do is delete this example and link to an Azure doc for this, but I don't see anything to link to in Azure docs. Are you aware of something that I can link to and then shed this example?

**Comment by davidebbo** [comment]
@guardrex sorry, I have been disconnected from this world for the past two years, so my knowledge is not up to date and I will let a current expert respond.

**Comment by guardrex** [comment]
Working backwards from the Azure portal (add the site extension and then export the app's template), I get ...

```json
{
    ...
    "parameters": {
        "site_name": {
            "defaultValue": "{SITE NAME}",
            "type": "String"
        },
        ...
    },       
    ...
    "resources": [
        ...
        {
            "type": "Microsoft.Web/sites/siteextensions",
            "apiVersion": "2018-11-01",
            "name": "[concat(parameters('site_name'), '/AspNetCoreRuntime.5.0.x64')]",
            "location": "[resourceGroup().location]",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('site_name'))]"
            ]
        }
    ]
}
```

* I substituted `[resourceGroup().location]` for the string name of the datacenter, which is what my file contained.
* I don't see a `properties` > `version`, but this is based on a live template from the portal, so I assume it's good.

I'll base the update to the topic on this result.
