### ISSUE TITLE
Blazor tutorial problem

### ISSUE THREAD

**Issue by BrettPrime** [dotnet/AspNetCore.Docs#19381]
[EDIT by guardrex to add the metadata. @BrettPrime, please use the **This page** feedback button and form at the bottom of a topic to open an issue.]

# Issue description

line 
<h3>Todo (@todos.Count(todo => !todo.IsDone))</h3>

causes 

Pages\Todo.razor(3,32): error CS0023: Operator '!' cannot be applied to operand of type 'string'

<h3>Todo (@todos.Count(todo => todo.IsDone == "false"))</h3>

might be the fix.  a straight false is not allowed here either.

this is for 

https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@BrettPrime Show your `TodoItem` class. Paste it into a comment here.

**Comment by guardrex** [comment]
@BrettPrime ... I'm going to close because I think you didn't make `IsDone` a `bool` in the `TodoItem` class, which is called out earlier in the topic.
