### ISSUE TITLE
Disabling client-side validation at just the form level in MVC Core

### ISSUE THREAD

**Issue by aquacat123** [dotnet/AspNetCore.Docs#19394]
In MVC Core is there an easy way to disable client-side validation at just the form level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
MFV doesn't have form level.

**Comment by aquacat123** [comment]
I'm not sure what MFV is.  I can use the code below to disable unobtrusive client-side validation across my application.  What I am trying to do is disable unobtrusive client-side validation for just a single view or form.  

services.AddMvc().AddViewOptions(options => 
    options.HtmlHelperOptions.ClientValidationEnabled = false);
