### ISSUE TITLE
Blazor WebAssembly Hosted on ASP.NET Core - Issue

### ISSUE THREAD

**Issue by fornax76** [dotnet/AspNetCore.Docs#19398]
[EDIT by guardrex to change the metadata]

I have a Blazor WebAssembly app hosted using ASP.NET Core server. I have added a Razor page to Pages folder of the ASP.NET Core server project - which should also be able to recognize a logged in user, but it doesn't.

I followed the override path method, but it doesn't work. Relevant sections of my Startup.cs are as follows:-

       `public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options => options
                .UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
                .EnableSensitiveDataLogging());

            services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddClaimsPrincipalFactory<AppClaimsPrincipalFactory>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
                {
                    options.IdentityResources["openid"].UserClaims.Add("role"); // Roles
                    options.ApiResources.Single().UserClaims.Add("role");

                    options.IdentityResources["openid"].UserClaims.Add("First_Name"); // Custom Claim
                    options.ApiResources.Single().UserClaims.Add("First_Name");

                    options.IdentityResources["openid"].UserClaims.Add("Last_Name"); // Custom Claim
                    options.ApiResources.Single().UserClaims.Add("Last_Name");

                    options.IdentityResources["openid"].UserClaims.Add("Organization"); // Custom Claim
                    options.ApiResources.Single().UserClaims.Add("Organization");

                    options.IdentityResources["openid"].UserClaims.Add("Domain"); // Custom Claim
                    options.ApiResources.Single().UserClaims.Add("Domain");

                    options.IdentityResources["openid"].UserClaims.Add("Email"); // Custom Claim
                    options.ApiResources.Single().UserClaims.Add("Email");
                });
            
            //JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");

            //services.AddTransient<IProfileService, ProfileService>();

            services.AddAuthentication()
                .AddIdentityServerJwt();

            
            var keysFolder = Path.Combine(hostingEnvironment.ContentRootPath, "KeyRing");
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(keysFolder))
                .SetApplicationName("MY_APP_NAME");

            services.ConfigureApplicationCookie(options => {
                options.Cookie.Name = ".AspNet.SharedCookie";
                options.Cookie.Path = "/";
            });            

            services.AddControllersWithViews();
            services.AddRazorPages();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "ToDo API",
                    Description = "A simple example ASP.NET Core Web API",
                    TermsOfService = new Uri("https://example.com/terms"),
                    Contact = new OpenApiContact
                    {
                        Name = "Shayne Boyer",
                        Email = string.Empty,
                        Url = new Uri("https://twitter.com/spboyer"),
                    },
                    License = new OpenApiLicense
                    {
                        Name = "Use under LICX",
                        Url = new Uri("https://example.com/license"),
                    }
                });
            });
        }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fornax76 ... That's close (sans the cookie and DP bits) to what's published in the hosted Blazor with IdS topic at https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/hosted-with-identity-server. Did you create your app (or an earlier app) exactly per that guidance and hit this problem? If not, you might try creating an app via the topic's guidance with the scenarios you need (e.g., profile service, custom user factory, etc.) and see if page auth behavior works as expected. If so, see how deltas may explain your app's behavior. If not, I'll need to test our guidance here to see if I can repro the behavior. If I can repro the behavior (page auth not working as expected), then we'd ask engineering to have a look. AFAIK (and there aren't reports from the community AFAIK), the guidance in that topic will result in an app that works with ordinary ASP.NET Core+IdS auth.

**Comment by fornax76** [comment]
I have a Blazor WA + ASP.NET Core hosted solution here, which followed the IdS setup doc link you mentioned above. Here is the specific ask I want to achieve:-
1. In the server project under Pages folder, I created a razor page named **Index**. 
2. I want to enable cookie authentication for this folder / file, but unable to do so using the suggested cookie config changes. 

Repo
https://github.com/fornax76/IdentityDemo

Cookie config change commit
https://github.com/fornax76/IdentityDemo/commit/1f5299e1f45155b8561a3a90284e813f4bf769a1

Index razorpage source code: https://github.com/fornax76/IdentityDemo/blob/1f5299e1f45155b8561a3a90284e813f4bf769a1/IdentityDemo/Server/Pages/Index.cshtml.cs

What am I doing wrong? I simply followed the WA Ids configration and cookie customization, but still unable to get the Index page authenticated. Would appreciate any help.

**Comment by guardrex** [comment]
> and cookie customization ... using the suggested cookie config changes

I didn't know that there would be a problem for that scenario. This is the first report that we've had in the docs issues on this scenario. If you don't see an existing issue on this in the engineering issues, open a new issue for them.

Start looking with these filters (open and closed Blazor issues) ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+label%3Aarea-blazor+

... try filtering that down with some search terms (e.g., cookie). If nothing related comes up, then open a new issue there and please add a `cc: @guardrex` to your opening comment so that I can follow the discussion. I'll re-open and work on this depending on what they say.
