### ISSUE TITLE
Codes for [Replace the content of the Views/Shared/_Layout.cshtml file with the following markup.] may be wrong...

### ISSUE THREAD

**Issue by machoy** [dotnet/AspNetCore.Docs#19395]
With reference to the section for 
**Replace the content of the Views/Shared/_Layout.cshtml file with the following markup. The changes are highlighted:**

The codes:
<a class="navbar-brand" asp-controller="Movies" asp-action="Index">Movie App</a>

aps-controller="Home" in my template.   If I had follow your codes, I will hit an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Its correct
