### ISSUE TITLE
Requesting addition of a basic persistent storage

### ISSUE THREAD

**Issue by quakeboy** [dotnet/AspNetCore.Docs#19399]
Can this sample also include a basic persistent storage feature, so that the todos get saved and load even if we restart the app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @quakeboy ... We have a PR in review now on how to work with a database via EF Core with Blazor. It should be live within a week or two. If you want to look at the guidance while they finish working on it, you can look at the diff on the PR ...

https://github.com/dotnet/AspNetCore.Docs/pull/18981
