### ISSUE TITLE
Dispose whilst in OnInitializedAsync 

### ISSUE THREAD

**Issue by JvanderStad** [dotnet/AspNetCore.Docs#19396]
According to https://github.com/dotnet/aspnetcore/issues/22932 dispose can be called at any time. Any resolved services in a component can be disposed at any time, even in the OnInitializedAsync event. 

I made the assumption OnInitializedAsync would finish before Dispose could/would be called. I assumed wrongly. Update the docs to prevent others from making the same wrong assumption?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JvanderStad ... Yes, I think a quick remark that that's the case can be placed in the *Component disposal* section. The use of a cancellation token is already covered in the last section.
