### ISSUE TITLE
Customizing built-in tag helpers

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/AspNetCore.Docs#19408]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs. built-in tag helper, customizing
- Tell us what docs you found that didn't address your concern.  [ASP.NET Core built-in Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-3.1)

**Describe the new topic**

- Explain why this topic is needed.
    - I think customizing built-in tag helper is common task and should be explained in the doc.
- Suggest a location in the Table of Contents.
    - Built-in Tag Helpers
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
    - How to customize built-in tag helpers to alter final rendered HTML.

**Comment by guardrex** [comment]
Hello @dehghani-mehdi ... That's not a common ask here. This is the first time that I recall this coming up in the last several years. Fortunately, it's a straightforward process: A dev would grab the TH code from the framework and make their own custom version using the guidance in the TH authoring topic.

* https://github.com/dotnet/aspnetcore/tree/master/src/Mvc/Mvc.TagHelpers/src
* https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/authoring
