### ISSUE TITLE
error trying to generate controller from models with views with no keys

### ISSUE THREAD

**Issue by blomm** [dotnet/AspNetCore.Docs#19409]
Using netcoreapp3.1 (3.1.6 libraries) in VS Code

I have built a simple web api project, reverse engineered my database (dotnet ef dbcontext scaffold) which contains views that have no keys, which shouldn't be a problem since ef core 3.

I can see that in onModelCreating code is added to clarify that there is no key:

```
modelBuilder.Entity<VwAverageRuns>(entity =>
            {
                entity.HasNoKey();
```
The problem arises when I go to generate a controller:

`dotnet aspnet-codegenerator controller -name VwAverageRunsController -async -api -m VwAverageRuns -dc dbContext -outDir Controllers
`
It errors with:

```
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'VwAverageRuns'
Primary key not found.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

```
But from everything I've read, the hasNoKey() inside onModelCreating should mean that I don't need to specify a key. What's going on here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think scaffolding requires a key.
