### ISSUE TITLE
How to sign the user out when browser tab or window is closed?

### ISSUE THREAD

**Issue by MarcusRhodes** [dotnet/AspNetCore.Docs#19404]
I implemented this ideas expressed in this documentation, but I have run into a problem with the user remaining logged in even after the close the browser tab. If more than one browser window is open, and they close the window with my app, they are also still logged in. They are only logged out if they close all the browser windows completely. 
There is no mention of this in the article, and there should be. A solution would also be beneficial for all, I feel. How does one code their app to sign out users if the user closes the browser tab or window?
Thanks for your time!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you [Sign out](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#sign-out) ?

**Comment by MarcusRhodes** [comment]
> Did you [Sign out](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-3.1#sign-out) ?

I have that implemented, and I can when I click a button. I need to user to be signed out when they close the browser tab, window, or search for something in the url bar that causes them to leave the page. 

Can .net sign the user out when they leave they app?

**Comment by Rick-Anderson** [comment]
> Can .net sign the user out when they leave or close the app?

It's impossible to know if they signed out.

**Comment by MarcusRhodes** [comment]
> > Can .net sign the user out when they leave or close the app?
> 
> It's impossible to know if they signed out.

You mean it is impossible to know if they closed the app?

**Comment by Rick-Anderson** [comment]
@Tratcher  this comes up too much. Should I create an include file for [the doc's that mention SignOutAsync](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-3.1&terms=SignOutAsync&category=Documentation) to say you must call `SignOutAsync` to sign out. It's impossible to know if the user meant to sign out when they navigate to another page, close a browser tab, etc.

**Comment by Tratcher** [comment]
> I implemented this ideas expressed in this documentation, but I have run into a problem with the user remaining logged in even after the close the browser tab. If more than one browser window is open, and they close the window with my app, they are also still logged in. They are only logged out if they close all the browser windows completely.
> There is no mention of this in the article, and there should be. A solution would also be beneficial for all, I feel. How does one code their app to sign out users if the user closes the browser tab or window?
> Thanks for your time!
> 

That's how session-lifetime cookies work in the browser, that's not something the server has any control over. I think your only alternative is to register javascript events for tab close and call signout. https://stackoverflow.com/questions/21227383/how-to-detect-browser-window-tab-close-event

**Comment by MarcusRhodes** [comment]
> > I implemented this ideas expressed in this documentation, but I have run into a problem with the user remaining logged in even after the close the browser tab. If more than one browser window is open, and they close the window with my app, they are also still logged in. They are only logged out if they close all the browser windows completely.
> > There is no mention of this in the article, and there should be. A solution would also be beneficial for all, I feel. How does one code their app to sign out users if the user closes the browser tab or window?
> > Thanks for your time!
> 
> That's how session-lifetime cookies work in the browser, that's not something the server has any control over. I think your only alternative is to register javascript events for tab close and call signout. https://stackoverflow.com/questions/21227383/how-to-detect-browser-window-tab-close-event

Thanks for the response! I have been doing that, so I will try to refine my approach, then. Window.onbeforeunload fires on every request, but I just need tab closes and when the user leaves the site.
