### ISSUE TITLE
unable to Scaffold movie pages

### ISSUE THREAD

**Issue by xouaib** [dotnet/AspNetCore.Docs#19418]
Hi .net developer please regarding to the following command, i get stacked to scaffold movie pages

 `dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries`

FYI, i use ubuntu 18.04 with dotnetcore SDK 3.1.302 using VSC of course.

This is the error that i always get when i hit enter

`dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
A file matching the name MvcControllerWithContext.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.40`

**Comment by Rick-Anderson** [comment]
Make sure you have the current SDK installed and run

```
dotnet tool install -g dotnet-aspnet-codegenerator
dotnet tool update -g dotnet-aspnet-codegenerator
```

Try creating only the model, then run

```
dotnet aspnet-codegenerator controller -name MoviesController -m Movie

``

If that doesn't work open an issue in  https://github.com/dotnet/Scaffolding/issues

report the output of `dotnet --version`

**Comment by luanpham107** [comment]
I found the way how to solve this.
The problem is caused by aspnet-generator itself. Please downgrade your version from v3.1.4 to v3.1.0 by using these commands:
```
dotnet tool uninstall --global dotnet-aspnet-codegenerator
dotnet tool install --global dotnet-aspnet-codegenerator --version 3.1.0

```

**Comment by Rick-Anderson** [comment]
@deepchoudhery FYI, multiple reports of this problem/solution

**Comment by deepchoudhery** [comment]
Will take a look ty.

**Comment by gastori** [comment]
@luanpham107  .. downgrade solution is not working ... as lots people are experienced same issue .. please provide a solution

**Comment by deepchoudhery** [comment]
@gastori @xouaib What platform are you currently working on? We have some issues with the Linux tool and I'm working on a fix for that.

**Comment by gastori** [comment]
> @gastori @xouaib What platform are you currently working on? We have some issues with the Linux tool and I'm working on a fix for that.

I am using an Ubuntu dev PC.

Ver: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-1093-oem x86_64

.Net Core environment

.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Dev IDE: VS Code 1.48.2 and Jetbrain Rider 2020.2.1

**Comment by gastori** [comment]
So as we are waiting for a possible fix that updates the pkg .. do we have temp ways to get through this error on Linux?

**Comment by deepchoudhery** [comment]
Yes, there was a change in 3.1.400 sdk and breaks the Linux tool so a package update will be needed. An older sdk would definitely solve the issue as a workaround with the newest or older versions of the code gen tool.

**Comment by gastori** [comment]
Do you have an estimated ETA when the new version would be available? 
Also, which pkg you are referring? the .Net Core SDK or the dotnet-aspnet-codegenerator?
