### ISSUE TITLE
Page appears to refer to files and methods that existed prior to simplification of app/program startup.

### ISSUE THREAD

**Issue by DarkChocoholicDev** [dotnet/AspNetCore.Docs#19411]
1. For the description of Program.cs, the WebAssembly section references configuration via the "**ConfigureServices** method on the host builder".

2. For the description of wwwroot/index.html (Blazor WebAssemly), there is a reference to **Startup.Configure**.

Are these still correct, or has this page not been fully updated to reflect the simplification of the app/program startup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab93ded4-34f4-eddc-d967-96b2326fce9c
* Version Independent ID: 4ee1d242-ec4f-c760-d1ce-26d31e3d2f49
* Content: [ASP.NET Core Blazor templates](https://docs.microsoft.com/en-us/aspnet/core/blazor/templates?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/templates.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/templates.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good :eye: @DarkChocoholicDev ... It should say "`Services` property" now. The other one should remark that the `App` component is a root component mapping. I'll fix those right now. Thanks for letting me know.
