### ISSUE TITLE
Enforcing SSL section makes REST API recommendations but doesn't provide or link to how

### ISSUE THREAD

**Issue by mtaylorfsmb** [dotnet/AspNetCore.Docs#19410]
On the page for ASP.NET Core enforcing SSL it demonstrates the default behavior of `UseHttpRedirection` and optionally `UseHSTS` to secure apps. However the page correctly documents that neither HTTP redirection nor HSTS should be used on REST APIs as they won't work (probably).

For HSTS you just leave out the middleware and the default project template (when creating an API only) does this. But for not redirecting the default template for APIs in Visual Studio still calls `UseHttpsRedirection`. Therefore the project template is doing what the documentation recommends against. This is an issue with the default project template (as of 16.6). 

But the documentation doesn't discuss the steps to properly disable HTTP redirection in an API. This should be documented. It makes sense to remove the call to `UseHttpsRedirection` but then the API allows both HTTP and HTTPS by default. The documentation does mention some things later about changing the launch.json file and whatnot but doesn't really provide a clear list of steps that REST API projects should use to disable HTTP and therefore enforce SSL as the documentation is trying to explain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  please comment.

**Comment by blowdart** [comment]
That seems fair. To disable HTTP the steps would be

Edit launchsettings.json in properties and remove the http URL from

"applicationUrl": "https://localhost:5001;http://localhost:5000"

and remove app.UseHttpsRedirection(); in startup.cs (although that's optional, if you only listen on https that call has no effect)

@halter73 may know a better way to edit program.cs to enforce it by adjusting the host builder.

The reason the templates don't enforce it is they can't, there's no way for the templates to know that there's a valid HTTPS certificate, and VS wants to avoid errors when you hit f5. As we've said before the templates are a starting point for your customization.

**Comment by halter73** [comment]
> @halter73 may know a better way to edit program.cs to enforce it by adjusting the host builder.

There are too many ways to do this in program.cs. Including [IWebHostBuilder.UseUrls](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0#server-urls) and [KestrelServerOptions.Listen](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0#bind-to-a-tcp-socket). 

I recommend using the `ASPNETCORE_URLS` environment variable or `--urls` command line flag though. That way, you don't have to have a different build for testing and deployment if they have different binding requirements.

https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/ describes all the options pretty well
