### ISSUE TITLE
Update .NET Azure topics with metadata so they can be reported on

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#19427]
Locate all .NET topics (Non-reference) for Azure across all repos that publish to /azure/ and add the following custom metadata values based on language that dev content org agreed to.

Add these values:

- devx-track-fsharp
- devx-track-csharp
- devx-track-visualbasic

Fixed by these PR's in both AspNetCore.Docs and azure-docs-pr:
https://github.com/dotnet/AspNetCore.Docs/pull/19466           (14 files in AspNetCore.Docs)
https://github.com/MicrosoftDocs/azure-docs-pr/pull/125801  (35 files azure-docs-pr)
https://github.com/MicrosoftDocs/azure-docs-pr/pull/125970  (117 files azure-docs-pr)
https://github.com/MicrosoftDocs/azure-docs-pr/pull/126544  (271 files azure-docs-pr)
https://github.com/MicrosoftDocs/azure-docs-pr/pull/127474  (514 files azure-docs-pr)

951 files in total updated.

A large percentage of these 951 files had to be manually reviewed to ensure the topics qualified for .NET/C#/F#/VB tracking since many of the original query hit had barely a mention or used .NET/C# related keywords under Next steps, etc and should not qualify to be pulled into reporting for .NET + Azure focused topics.

**Comment by Rick-Anderson** [comment]
@wadepickett  be sure to remove `Not Triaged` label when you triage.

**Comment by wadepickett** [comment]
Fixed by these PR's in both AspNetCore.Docs and azure-docs-pr:
#19466 (14 files in AspNetCore.Docs)
MicrosoftDocs/azure-docs-pr#125801 (35 files azure-docs-pr)
MicrosoftDocs/azure-docs-pr#125970 (117 files azure-docs-pr)
MicrosoftDocs/azure-docs-pr#126544 (271 files azure-docs-pr)
MicrosoftDocs/azure-docs-pr#127474 (514 files azure-docs-pr)

951 files in total updated.

A large percentage of these 951 files had to be manually reviewed to ensure the topics qualified for .NET/C#/F#/VB tracking since many of the original query hit had barely a mention or used .NET/C# related keywords under Next steps, etc and should not qualify to be pulled into reporting for .NET + Azure focused topics.
