### ISSUE TITLE
Is HealthCheck functionality moving to Microsoft.Extensions.Diagnostics.HealthChecks from Xabaril / AspNetCore.Diagnostics.HealthChecks?

### ISSUE THREAD

**Issue by udlose** [dotnet/AspNetCore.Docs#19421]
I recently came across the `Microsoft.Extensions.Diagnostics.HealthChecks` nuget and was wondering if this is supposed to replace the `AspNetCore.Diagnostics.HealthChecks` that Xabaril has built at https://github.com/xabaril/AspNetCore.Diagnostics.HealthChecks.

Can you please clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@glennc  can you recommend someone to update the HealthChecks  doc?

**Comment by guardrex** [comment]
@udlose It's not a replacement ... it's a dependency of the framework's healthchecks packages and provides types used by the framework's infrastructure to make health checks work. For example, it's a dependency of [Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore/). Xabaril's package is a suggestion/example for health check scenarios that simplify some of the set up in common scenarios (this topic uses it for dB probe scenario). If you look at the [sample app](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks/samples/3.x/HealthChecksSample/SampleApp.csproj) for this topic, you'll see both in use. Xabaril supports a whole bunch of health check scenarios, which their docs cover. Anything performed by Xabaril's package(s) can be programmed by the dev on their own ... one can even look at their public repo(s) to see and use their approaches **_per whatever their license is_**, of course.

@Rick-Anderson AFAIK, there are no changes at this time. We'll need to check with Unai (`unaizorrilla`) tho for potential 5.0 updates later. Hopefully, we'll just need to update to their 5.0-enabled packages and things will ✨ *Just Work!* ✨. It's probably best that I take care of this topic when that time comes when we get to the holidays. 🎁 I don't recommend keeping an open issue for it now tho. I'll get it when the time comes.
