### ISSUE TITLE
Refactor Custom ProblemDetailsFactory 

### ISSUE THREAD

**Issue by sameer-kumar** [dotnet/AspNetCore.Docs#19430]
As described and documented [here](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1#implement-problemdetailsfactory), I like to customize the **ProblemDetails** hence extended **ProblemDetailsFactory** class.
However, I want to have this custom implementation to live in .Net Standard shared class library and not in the Web project itself. But I can't do that. It says that the base class **ProblemDetailsFactory** is not found.
I realized that the version of *Microsoft.AspNetCore.Mvc.Core.dll* referenced in OOB web application is 3.1 whereas its 2.2.5 in my class library project.

Is it something doable or thought through or am I missing something here?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-3.1#client-error-response)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by pranavkm** [comment]
The type is part of the ASP.NET Core shared framework. You'll need to target a `netcoreapp3.1` or `net5.0` project to be able reference it.

**Comment by sameer-kumar** [comment]
This is what my csproj file looks like:
```
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netcoreapp3.1</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.6" />
    <PackageReference Include="System.Reflection.Metadata" Version="1.8.1" />
  </ItemGroup>
```

**Comment by scottaddie** [comment]
@sameer-kumar See the following doc for guidance on using the ASP.NET Core shared framework in a library: https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore.
