### ISSUE TITLE
Re-version Blazor <head> component section

### ISSUE THREAD

**Issue by augaldecr** [dotnet/AspNetCore.Docs#19434]
The page must go to Blazor's Title component, but redirects to another unrelated content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc56d254-09c5-993b-2559-76af9a3f97ed
* Version Independent ID: a0bb183f-7e4d-ba39-c94c-cf60e951c7a9
* Content: [ASP.NET Core Blazor hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#influence-html-head-tag-elements)
* Content Source: [aspnetcore/blazor/fundamentals/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @augaldecr ... It's a 5.0 preview feature. Select the 5.0 version of the topic to see that section.

Leave this issue open. I might temporarily remove the component link from the table of contents until 5.0 releases later this year.

**Comment by guardrex** [comment]
I'm going to surface that section until 5.0 ships, then I'll put the versioning of that section back into place.

Leave this issue open ... I'm going to re-purpose it to track the next update on this.

Thanks @augaldecr! :rocket:

**Comment by guardrex** [comment]
This work will be tracked by https://github.com/dotnet/AspNetCore.Docs/issues/20319.
