### ISSUE TITLE
Call component instance method in specific component when multiple of the same component are on screen

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#19442]
The code in this section is for calling a method in a razor component. If there are more than one of the same component onscreen, the function is called only on the last one in the DOM.

Is it possible to specify which one to call the method on?

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#component-instance-method-call

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#component-instance-method-call)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I thought this was already covered down where the topic recommends .......

> When there are several components, each with instance methods to call, use a helper class to invoke the instance methods (as Actions) of each component.

... and the example that follows.

**Comment by mrlife** [comment]
@guardrex  Isn't that for calling the method in multiple components? I want to call one method in one specific component (there are more than one component of this type).

**Comment by guardrex** [comment]
That's not the way that I recall it ... I thought it did what you're asking about.

I'm ⛰️⛏️ digging out from under three forms validation issues right now ... almost done; but given that it's Friday and I'm out of hours this week, I'll have to take a closer look early next week.

**Comment by mrlife** [comment]
> I thought this was already covered down where the topic recommends .......
> 
> > When there are several components, each with instance methods to call, use a helper class to invoke the instance methods (as Actions) of each component.
> 
> ... and the example that follows.

Ah, when I read that, I read it as "this is how you call the method on all the components on screen."

Is it saying the same thing as the following?

> When several components of the same type are rendered on screen, use a helper class to invoke the instance method (as an Action) on the desired component(s).

**Comment by guardrex** [comment]
I'm not sure ... I'll have to take a closer look next week.

I'm **_buried_** ⛰️⛏️ in code at the moment. :smile: lol

I'll get back to you on this as soon as I can.

**Comment by guardrex** [comment]
I'm back. Yes, I think an update to the sentence would be good. I'll put that in now.
