### ISSUE TITLE
Add Blazor WASM debug note

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19440]
https://github.com/dotnet/aspnetcore/issues/24623#issuecomment-670300570

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
@guardrex One thing that came up today is that we should clarify that this will cause performance issues in the app to account for overhead needed to set up for debugging.

**Comment by guardrex** [comment]
Did u mean to put that here? This issue was about surfacing ...

```
**Start Without Debugging** (<kbd>Ctrl</kbd>+<kbd>F5</kbd>) isn't supported.
```

... or really that "start without" and "start with" do the same thing.

**Comment by guardrex** [comment]
Should I open a new issue?

btw --- Clarify what "this" means.

**Comment by captainsafia** [comment]
> or really that "start without" and "start with" do the same thing.

Start without and start with do the same thing. The consequence of that is that there is some performance overhead to debugging.

**Comment by guardrex** [comment]
ok ... I'll open a new issue and take care of it by EOD.
