### ISSUE TITLE
Identity and Basic authentication

### ISSUE THREAD

**Issue by mc0re** [dotnet/AspNetCore.Docs#19452]
I'm not sure which exact page I shall tag this one to. So please move if improper.

I am retrofitting *Identity* into an existing *ASP NET Core 3.1* project. I managed to adjust *Identity*, so the existing `Users` and `Roles` tables are used, and the existing password hashing works, so the users can log in via Web. But they also use programs, that employ API access to the service, and there *basic* authentication is used (via HTTP header).

I couldn't find any information on how to use *basic* authentication with *Identity*. Everything expects *JWT tokens*. But I can't change the service and all programs simultaneously. So how can I make *basic* authentication work with an *Identity*-enabled service during the migration period?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0676a8c8-8009-8a7e-72ac-7cde0013fb97
* Version Independent ID: e35e8811-07d1-ca9b-d6e7-e28c1d4b1853
* Content: [Articles based on ASP.NET Core projects created with individual user accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/individual.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/individual.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I recommend you post this on SO as it doesn't seem to fit our documents. CC @blowdart  who owns security in case he disagrees.

**Comment by blowdart** [comment]
Yup, we don't support basic authentication on inbound connections due to its security and scalability problems.
