### ISSUE TITLE
ASP.NET Core MVC and Blazor are confusing

### ISSUE THREAD

**Issue by donhuvy** [dotnet/AspNetCore.Docs#19469]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization

![image](https://user-images.githubusercontent.com/1328316/89855083-b5968b00-dbbf-11ea-8ed4-35180d8f9ba8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @guardrex

**Comment by guardrex** [comment]
@donhuvy What's confusing? It's just saying that if you're scaffolding Identity into a Blazor Server project that you won't have a layout page ... so you don't select an existing layout page for that step. There's no danger of overwriting anything.

**Comment by donhuvy** [comment]
After read your comment, I am confusing :)
