### ISSUE TITLE
How to log in via Web and via API?

### ISSUE THREAD

**Issue by mc0re** [dotnet/AspNetCore.Docs#19464]
The article explains the technical implementation of multiple schemes on the server side. But it is missing an important bit - how exactly would I modify the *Identity* `Login` page and `Startup` file to achieve both logging in via Web (entering user name and password), as well as from API (requesting a JWT token)? The client for the latter is not complicated, but I can't figure the server part, which can do both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Logging in via API is beyond the scope of this article. You could post the question to SO. 
cc @blowdart  in case he disagrees

**Comment by mc0re** [comment]
I understand your point. But please try to see it from my perspective as well. There is an article about API login (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1). There is an article about Web login (this one). But the two are not compatible, and I can't find an official article describing a hybrid solution.

There are some articles on SO, but I can't get them to work, none of them. And an official article usually goes to a greater depth. I'd really appreciate if there was one around.
