### ISSUE TITLE
Add documentation for debugging in VS4Mac

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#19465]
Let's add docs on debugging Blazor WASM on VS4Mac since this will ship in VS4Mac 8.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I keep my VS4Mac on the stable channel. If you're ok with my performing the update on the day that 8.8 releases, then I can handle the update.

**Comment by captainsafia** [comment]
> I keep my VS4Mac on the stable channel. If you're ok with my performing the update on the day that 8.8 releases, then I can handle the update.

Yea, no rush to write this up. Just wanted to make sure that we are tracking this.

Content wise, I was thinking we could just update the heading for debugging on VS to "Debugging on Visual Studio/Visual Studio for Mac" and then update the keyboard shortcuts. Thoughts on this?

**Comment by guardrex** [comment]
Ideally, we'll go with our usual tooling tab control. I meant to do that for what we have now, but you know the story ... 🏃🏃🏃🏃🏃🏃🏃😅🏃🏃🏃🏃🏃🏃🏃🏃😅.

**Comment by jongalloway** [comment]
VS for Mac 8.8 P2 is out today. Happy to help with any screenshots or review.

**Comment by guardrex** [comment]
I'll put my iMac on the preview channel and work this first thing Wednesday morning.

We try to avoid screenshots, and we might be pulling a few from existing content. For IDEs and the Azure portal, they change every **_6.27 minutes!_** :smile:

**Comment by guardrex** [comment]
Ran into an issue this morning without an obvious solution:

1. Took VS to the preview channel. Received v8.8 Build 1532
1. Installed .NET 5 Pre8
1. Debugging works in the *Server* app of a hosted project.
1. Debugging does **not** work on the counter increment (`currentCount++;`) in the `Counter` component. The breakpoint that I set isn't hit.

:ear:

**Comment by guardrex** [comment]
**Also ...** a few more ❓ ...

1. Is debugging in the browser [*Debug in the browser* section](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#debug-in-the-browser) not supported on macOS/Safari? 

   If not supported, I'll need to add a line to that section ...

   > *The guidance in this section only applies to debugging on Windows with Google Chrome or Microsoft Edge.*

2. Same question for the [*Browser source maps* section](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#browser-source-maps) ... does that require a qualification line? If so, use the same line :point_up: or something else?

3. For the [*Prerequisites* section](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#prerequisites), is the minimum supported Safari version 13.1.2 or later? (v13.1.2 is the current version here.)

**Comment by mrward** [comment]
The only problem I see with .NET 5 preview 8, which also affects .NET Core 3.1, is that it takes a while before the breakpoints work. VS Mac does not correctly indicate that the breakpoints are not yet enabled. This is a known bug. Eventually the breakpoint is enabled and can be hit.

Safari is not supported. Only Edge and Chrome are supported.

**Comment by guardrex** [comment]
> Safari is not supported. Only Edge and Chrome are supported.

That would explain my problem. I'll install Chrome. Thanks for the tip!

> takes a while

This initial test is just for the counter increment after waiting several seconds. Also by the time the user gets to testing the controller the app has been running a while. We also have the NOTE on this delay earlier in the topic. I think we'll be ok on this one.

**Comment by guardrex** [comment]
Ok ... it works ... **_BUT_** ...

* It seems like it's necessary to use Google Chrome when the app starts ... i.e., Chrome must be selected in VS4Mac for the Debug run before starting the debug run. I wasn't able to select Safari, start, then open Chrome and get debugging to run.
* It was **_very slow_** to react to the breakpoint being hit ... several seconds, especially because I'm using an ancient 2009 iMac (👴 *Yikes!*) and this iMac is slow at *everything* 🐌.

I have enough now to get the PR in ... will do that now and ping for review.

**Comment by mrward** [comment]
Correct - Chrome or Edge need to be selected in the main toolbar before you start the debug run. If Safari is selected VS Mac does not launch the Blazor debugger when you debug the project.

It seems to be much slower for the breakpoint to be enabled/verified with .NET 5 preview 8 than with .NET Core 3.1.401. It is much more difficult to miss the breakpoint with .NET Core 3.1.401 - you have to be quite fast there.

**Comment by guardrex** [comment]
The *Debug in the browser* guidance seems like it's about to work ... but I haven't quite got it running yet.
