### ISSUE TITLE
Context should be capitalized

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/AspNetCore.Docs#19475]
In the example:

` Hello, @context.User.Identity.Name!`
'context' should become 'Context' with capital 'C'

Reference: 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by serpent5** [comment]
The example is correct: it's `context` in Blazor. I believe it's known as a [Template context parameter](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1#template-context-parameters).

cc @guardrex, as _the_ Blazor expert.

**Comment by shadinamrouti** [comment]
Sorry guys for inconvenience, you're correct. 
The example is correct in Blazer. I thought it's in Razor.
