### ISSUE TITLE
Text conflicts with the title "Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C"

### ISSUE THREAD

**Issue by peereflits** [dotnet/AspNetCore.Docs#19470]
Reading https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1 the title says: "Secure an ASP.NET Core Blazor WebAssembly **hosted** app with Azure Active Directory B2C".
But the first textline states: This article describes how to create a Blazor WebAssembly **standalone** app that uses Azure Active Directory (AAD) B2C for authentication.
Futhermore: the text does not explain the difference between a "*hosted* app" and a "*standalone* app".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#access-token-scopes)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @peereflits ... that's a typo.

... and the difference is described in the Hosting Models topic at ...

https://docs.microsoft.com/aspnet/core/blazor/hosting-models

I'll patch that typo up right now. I'll see about cross-linking it to the Hosting Model topic to surface what it means.
