### ISSUE TITLE
Replace IIdentity with IdentityUser<T>

### ISSUE THREAD

**Issue by Exagram** [dotnet/AspNetCore.Docs#19482]
The Identity tutorial (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1) recommends that your custom user should extend IdentityUser<T>, not IIdentity. I believe Identity's UserManager doesn't utilize IIdentity's fields so why use it? Was this a typo?

https://github.com/dotnet/AspNetCore.Docs/blob/644661bc46c1c5b5e8480fa6d8b66c4b790ced2b/aspnetcore/security/authentication/identity-custom-storage-providers/sample/CustomIdentityProviderSample/CustomProvider/ApplicationUser.cs#L6

---

Edit by @Rick-Anderson  5.6K PV
PU needs to outline what needs to be updated for 3.1/5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Next time Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by HaoK** [comment]
I think the docs are fine, the example here is just demonstrating a custom identity user and showing that you don't have to extend from our base classes.  So in this case I believe its intentional that its showing IIdentity instead.  

The canonical case is extending IdentityUser, this example is showing the less common path
