### ISSUE TITLE
Unnecessary injection of db context in constructor of IndexModel

### ISSUE THREAD

**Issue by MojtabaMontazery** [dotnet/AspNetCore.Docs#19481]
Regarding the _QueuedBackgroundTask_ section, the code is confusing. You are injecting `AppDbContext` in the constructor but not using that. Instead, as you mentioned yourself, you are using `IServiceScopeFactory ` to create a scope and use `AppDbContext`.  So, you can remove the injection in the constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task-1)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MojtabaMontazery ... We pull the example code in many of these topics from the sample app that goes with the topic. It's used in `OnGetAsync` in the sample app ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services/samples/2.x/BackgroundTasksSample/Pages/Index.cshtml.cs#L37
