### ISSUE TITLE
Blazor MSAL auth options login mode

### ISSUE THREAD

**Issue by Ma3yTa** [dotnet/AspNetCore.Docs#19491]
clicking on 'Log In' opens login popup
setting ``NavigateToLoginRequestUrl: true`` inside ``wwwroot/appsettings.json`` from ``MsalProviderOptions`` has no effect and popup opens instead of redirecting to login URL in the same window
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ma3yTa ... Yes, it was by-design for 3.x. It's going to be a new feature for 5.0, which is in preview now and should be out by the end of the year.

* https://github.com/dotnet/aspnetcore/issues/20374
* https://github.com/dotnet/aspnetcore/pull/23694

It's going to be a property (`LoginMode`) on `MsalAuthenticationOptions`.

**Comment by guardrex** [comment]
Actually, I won't close this ... I was going to open an issue to track the update for the docs, but I can use your issue here and take care of this today. It will appear in the doc when the doc version selector is set to 5.0.

**Comment by adixon501** [comment]
Is this feature available for .Net Core 3.1 or only available for .Net 5?

**Comment by guardrex** [comment]
@adixon501 ... Only 5.0 or later.

**Comment by adixon501** [comment]
@guardrex, thats one way to get us to migrate to 5.0 😄
