### ISSUE TITLE
PMC deps.json error

### ISSUE THREAD

**Issue by SageDav** [dotnet/AspNetCore.Docs#19493]
`Add-Migration InitialCreate 
Update-Database
`

When running the above PMC command on a project with a UNC path, I get the "The specified deps.json [..] does not exist" error. The deps.json file does exist in the bin folder, but the project is unable to locate it. I moved the project to various UNC locations and received the same error each time. 

When I moved the project to a non-UNC path, the PMC command executed successfully. The project worked in the UNC location on each tutorial step up to this point. 

The image on the first page of the tutorial shows the project created in the C:\ drive, but it does not specifically say that is required. Are there some setups missing on step 1 to configure this project to work with UNC paths?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
non-UNC paths are beyond the scope of this tutorial.
