### ISSUE TITLE
Implications of "For internal framework use only."

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#19494]
# Issue description

Some methods are described with "For internal framework use only."

I have been using `EventCallback.Factory.Create(Object, EventCallback)`- it really helps my app work the way I need it to - and recently saw in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.eventcallbackfactory.create?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_EventCallbackFactory_Create_System_Object_Microsoft_AspNetCore_Components_EventCallback_) it is described by the following:

> Returns the provided callback. For internal framework use only.

Does "For internal framework use only" mean it should not be used or that it can disappear from a future release (with or without notice)?

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core 3.1.6

**Comment by guardrex** [comment]
Hello @mrlife ... IIRC a few times this has come up over the years, they may have also called out security, perf, and stability reasons in addition to the 'it might change' and 'it might go away' reasons. Ask on the engineering repo ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your issue. I'd like to hear what they say on this one.
