### ISSUE TITLE
documentation issue for @inherits

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#19502]
[EDIT by guardrex to fix the code blocks. Triple backticks above and below for a block, singles for inline]

Good day, for 

```razor
@inherits CustomRazorPage<TModel>
```

where 

```csharp
public abstract class CustomRazorPage<TModel> : RazorPage<TModel>
```

this will raise an error:

> The name 'PageContext' does not exist in the current context 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hoksource  were you able to update the project for 3.1?

@pranavkm @NTaylorMullen  what's the 3.1 version of [MvcRazorTemplateEngine Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.razor.extensions.mvcrazortemplateengine?view=aspnetcore-2.2) ?

**Comment by hoksource** [comment]
yes, im using 3.1. although calling
`
inherit PageBase
`

works. for razor pages

**Comment by Rick-Anderson** [comment]
@hoksource  can you post a basic sample on GitHub and I'll get engineer to review it.

**Comment by hoksource** [comment]
below does not work
Test.cshtml
`
@@page
@@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<int>

`


below works
Test1.cshtml
`
@@page
@@inherits Microsoft.AspNetCore.Mvc.RazorPages.PageBase

`

**Comment by Rick-Anderson** [comment]
@HDONGDeveloper from https://github.com/dotnet/aspnetcore/issues/21013 and @hoksource  remind me where you get the 3.1 version of [RazorTemplateEngine](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.razor.language.razortemplateengine)

I upgraded the sample from 2.0 to 3.1 but need the replacement for `RazorTemplateEngine`
https://github.com/Rick-Anderson/RazorTemplateEngine

**Comment by Rick-Anderson** [comment]
I found https://github.com/dotnet/aspnetcore/issues/5079 where `RazorTemplateEngine` was removed.

So that needs to be removed from the sample.

**Comment by Rick-Anderson** [comment]
> this will raise an error:

> The name 'PageContext' does not exist in the current context 

@hoksource  all the pages with
```razor
@inherits CustomRazorPage<TModel>
```

work fine.

**Comment by Rick-Anderson** [comment]
@hoksource  if you can put the simplest possible complete sample on GitHub and ***Explain why you need this**, I'll look into it

below does not work
Test.cshtml
```
@page
@inherits Microsoft.AspNetCore.Mvc.Razor.RazorPage<int>

```


below works
Test1.cshtml
```
@page
@inherits Microsoft.AspNetCore.Mvc.RazorPages.PageBase

```

**Comment by hoksource** [comment]
Thank you for the info @Rick-Anderson . I was trying to see if i can work with razor pages with just the .cshtml no PageModels. using .cshtml only is not well documented for razor so i'm not sure how to add property and binding models to the property with .cshtml razorpage only. So I ended up using PageModels.
