### ISSUE TITLE
Measure Network Latency sample causes errors

### ISSUE THREAD

**Issue by marin-bratanov** [dotnet/AspNetCore.Docs#19504]
The sample tries to use JS Interop in the OnInitialized event which will throw. It must be in the OnAfterRender event, like this:

```razor
@inject IJSRuntime JS

@if (latency is null)
{
    <span>Calculating...</span>
}
else
{
    <span>@(latency.Value.TotalMilliseconds)ms</span>
}

@code {
    private DateTime startTime;
    private TimeSpan? latency;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            startTime = DateTime.UtcNow;
            var _ = await JS.InvokeAsync<string>("toString");
            latency = DateTime.UtcNow - startTime;
            StateHasChanged();
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1#measure-network-latency)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @marin-bratanov ... The code originally came over from engineering like that. Later, this was reported, but we missed an update. 🙈 This was asked about on #16615, but Artak closed it without realizing that the reader was working from the published code, and I didn't catch it at the time ...

https://github.com/dotnet/AspNetCore.Docs/issues/16615#issuecomment-580876488

I'll get that fixed today. Thanks for writing in on it.

**Comment by marin-bratanov** [comment]
No worries, I just saw the issue and the "feedback" button and sent it, I didn't even look for previous ones (maybe I should have). Btw, that was probably the most detailed history for such a small thing I've ever seen :) Thank you so much for your efforts :)

**Comment by guardrex** [comment]
You did the right thing. We missed it. When Artak closed it, I'm sure that I was buried in something else and didn't give it a second thought.

We're good now. The update will go live by the end of day. Thanks again.
