### ISSUE TITLE
Update time and minutes to read is incorrect 

### ISSUE THREAD

**Issue by veritas27** [dotnet/AspNetCore.Docs#19510]
For this page, it says 04/01/2020 101 minutes to read at the top.

When I change from ver 2.1 to ver 3.0, there is twice as much content, but the 04/01/2020 101 minutes stays the same. My guess is that the time to read is not correctly subscribing to the version change event.

Thanks,

John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @veritas27 ... We use an approach called "whole topic versioning," where multiple versions of the topic are in the same file using version monikers. This value is very likely being determined by the length of **_the whole file_**. There's probably no way around this error given what we're doing. Our approach very probably never was a design spec for the docs. It's just something that helps us be more efficient 💰.

**Comment by Rick-Anderson** [comment]
Time to read has no basis in reality and many wish it would be removed.
