### ISSUE TITLE
No Platform configuration added yet.

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/AspNetCore.Docs#19527]
Tutorial states:
"In Authentication > Platform configurations > Web:"

But at this point in the tutorial one has not added a platform yet and just sees the following:

![image](https://user-images.githubusercontent.com/357219/90327100-5919de00-dfba-11ea-88f3-e3662927ed3b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
When you provide the callback address on Step 4 of the previous instruction block ...

<img width="792" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/90332171-7467f780-df80-11ea-8161-8c4b7637b99c.PNG">

... it automatically adds a **Web** platform configuration ...

<img width="382" alt="Capture" src="https://user-images.githubusercontent.com/1622880/90332148-3539a680-df80-11ea-9b0d-fa3341cc1c83.PNG">

**Comment by StevenTCramer** [comment]
Hmm dang I must have missed that sorry.
