### ISSUE TITLE
authorization is not working even the user is logged in

### ISSUE THREAD

**Issue by jfvaleroso** [dotnet/AspNetCore.Docs#19525]
authorization is not working when adding authorize attribute. Im gettinc 401 error with invalid token, even If I followed the exact documentation. Any idea about this?

**Comment by guardrex** [comment]
@jfvaleroso ... Please use the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
