### ISSUE TITLE
Update version in Msal

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/AspNetCore.Docs#19528]
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#authentication-package-1

<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" 
  Version="3.2.0" />

is now 

<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" 
  Version="3.2.1" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#authentication-package-1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is a dup of #19526 ... I'm fixing all of them in one shot.

**Comment by StevenTCramer** [comment]
@guardrex You rock!!!
