### ISSUE TITLE
Secure an ASP.NET Core web API using Azure AD B2C link redirecting to 404 page

### ISSUE THREAD

**Issue by anuraj** [dotnet/AspNetCore.Docs#19520]
[Enter feedback here]
The link - Secure an ASP.NET Core web API using Azure AD B2C - redirecting to URL - https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-dotnetcore-webapi/an-aspnet-core-20-web-api-with-azure-ad-b2c/ which is redirecting to a not found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by guardrex** [comment]
Thanks @anuraj ... I'll see if I can track that down and report back, then I'll fix this link.

**Comment by guardrex** [comment]
Might be this one these days ...

https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C

**Comment by guardrex** [comment]
Note that they either have moved everything or are in the process of moving everything to Identity v2.0. Our repo hasn't made all of the updates yet. There might be some deltas between what our topics show and theirs.
