### ISSUE TITLE
Command does not run successfully on windows 10 Pro

### ISSUE THREAD

**Issue by Dheerajmentor** [dotnet/AspNetCore.Docs#19532]
Hello, 

I am trying to follow this document and below command does not run 
```
dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p { password here }
```
and return below message 

![image](https://user-images.githubusercontent.com/28488401/90336022-afa50d80-dff6-11ea-8071-1032607a1d02.png)

as per observing message returned, its seems that it more of Linux/mac command.

please help 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #18017
