### ISSUE TITLE
How to deploy a hosted blazor app with SSL and Identity Server to apache

### ISSUE THREAD

**Issue by AlbertoPa** [dotnet/AspNetCore.Docs#19536]
I think it would be beneficial to document how to deploy a web app based on Blazor WebAssembly with Identity Server and SSL support. 

There are several aspects to explain about doing so that are spread over many documents, and some of them are not extensively documented (i.e. certificates for tokens in Identity Server) in the context of a deployment to Apache. The same can be said about ngix. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by Rick-Anderson** [comment]
That's probably too specific for a doc. cc @guardrex

**Comment by davidfowl** [comment]
Why apache?

**Comment by guardrex** [comment]
Even Windows Server/IIS isn't covered that way: We don't cover certs/IIS config (external doc set) for hosted WASM with IdS. Even Kestrel HTTPS config requires another doc (in this doc set). The entire configuration for a production deployment will probably always require multiple docs, usually across multiple doc sets, to avoid maintaining duplicate content.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by AlbertoPa** [comment]
Thanks! I understand, but this is essentially leaving the template app undocumented for use outside the development environment, since activating Identity with Blazor WASM automatically introduces Identity Server, and the app won't work properly when deployed to anything with at least a self-signed certificate.

**Comment by AlbertoPa** [comment]
@davidfowl because apache is one of the supported platforms as stated in the asp.net core documentation. Anything that is not IIS/Kestrel only would also work, since that would be a realistic scenario on a non-Windows/non-MS infrastructure.
