### ISSUE TITLE
No longer a Default scope

### ISSUE THREAD

**Issue by StevenTCramer** [dotnet/AspNetCore.Docs#19539]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/357219/90398910-52778d80-e0c4-11ea-9788-280adfe63792.png)

The screen doesn't reference a default and looks like the following:

![image](https://user-images.githubusercontent.com/357219/90399115-a2eeeb00-e0c4-11ea-94c6-2b71e94dfb3a.png)

The "API.Access" is at the end of the Scopes URL
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StevenTCramer ... The word "default"  refers to what will be the app's default scope. However, it isn't necessary there. It can just say "Scope;" therefore, I'll remove the word "Default" to remove any confusion. Thanks for the feedback.
