### ISSUE TITLE
I would suggest to renmae the examples of ApplicationXxx and IdentityXxx

### ISSUE THREAD

**Issue by LiviuSosu** [dotnet/AspNetCore.Docs#19531]
[Enter feedback here]

Instead of: 
_Remember to change the types of the navigation properties to reflect that ApplicationXxx types are now being used instead of IdentityXxx types._

You may write:
_Remember to change the types of the navigation properties to reflect that ApplicationXYZ types are now being used instead of IdentityXYZ types._

The same gors for the following sentence:  _Remember to use the ApplicationXxx in the generic ApplicationContext definition._

It is just a suggestipon.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by guardrex** [comment]
Good idea @LiviuSosu ... I'll knock that out right now.
