### ISSUE TITLE
What a Waste of Space

### ISSUE THREAD

**Issue by francisco-chavez** [dotnet/AspNetCore.Docs#19548]
[Enter feedback here]
Bad use of space. I'm looking at this page from a 1440P screen, and it's throwing away pixels at the edges. I have two wide bands of empty space on the left and right of my screen. When I look at this screen, this is what I see is (from left to right): big empty space, vertical site-navigation bar (that's much wider than needed), actual content, vertical feed back link with page navigation, and another big empty space. 

Why isn't the content area expanding to make better use of the available space? The actual content area of this page has horizontal scroll bars for the code samples because they aren't being given enough room. You have very important areas on the page that need additional horizontal space, and you're just throwing away horizontal space on two big columns of nothing? **_WTF_**, at least the old MSDN documentation site allowed us to re-size the nav-bar on the left to stop it from collapsing the page conent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @francisco-chavez ... We only work on content here. Please open an issue for docs general feedback at ...

https://github.com/MicrosoftDocs/feedback/issues
