### ISSUE TITLE
Distributed caching points to a deprecated Chocolatey package

### ISSUE THREAD

**Issue by petrsvihlik** [dotnet/AspNetCore.Docs#19542]
[This section](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache) points to a [deprecated package](https://chocolatey.org/packages/redis-64).
Is there a replacement package?

To install Redis on your local machine:

1. Install the [Chocolatey Redis package](https://chocolatey.org/packages/redis-64/).
1. Run `redis-server` from a command prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-redis-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mohsinnasir do you know if there's a replacement?

**Comment by petrsvihlik** [comment]
@Rick-Anderson this one works perfect - https://github.com/tporadowski/redis

I just tried it with the code from the MS docs example:

```
 services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = "localhost";
                options.InstanceName = "SampleInstance";
            });
```
and it just works.

**Comment by mohsinnasir** [comment]
@petrsvihlik redis generally targets linux OS, so for windows you may find redis packages deprecated or supported unofficially.
For windows based distrbuted caching software you may wanna try NCache as mentioned [here](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#distributed-ncache-cache).

**Comment by mohsinnasir** [comment]
@Rick-Anderson for native windows there is none provided by MSOPENTECH. However, WSL may be a good choice to use redis on windows as mentioned [here](https://dzone.com/articles/running-redis-on-windows-10)

**Comment by Rick-Anderson** [comment]
@mohsinnasir  why don't I just change that section to link to [Azure Cache for Redis](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-overview)

That's what you'll need for production anyway. You can use it in dev too.

**Comment by petrsvihlik** [comment]
@mohsinnasir yeah, I know. I was looking for something that I could use to test my code quickly on Windows. 

@Rick-Anderson yeah, I generally agree with that. but that was something I was too lazy to do :D so I was glad that I found https://github.com/tporadowski/redis and that it worked out of the box.

**Comment by abdollahkahne** [comment]
Just for complementary comment to this thread, I installed an extension package named  `Microsoft.Extensions.Caching.Redis` and it gives me the extension method for registration of **redis** distributed cache service as below

```
services.AddDistributedRedisCache(options =>
{
     options.Configuration = "localhost:6379";
     options.InstanceName = "Calculator";
});
```

**Comment by xXAvoraXx** [comment]
can you add RemoveByPattern GetByPattern method?
