### ISSUE TITLE
Download PDF of ASP.NET Core docs returns pdf with duplicate pages (and consequently wrong table of contents page pointers)

### ISSUE THREAD

**Issue by Veverke** [dotnet/AspNetCore.Docs#19560]
https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1
Clicking the "Download PDF" of ASP.NET Core docs returns a pdf with duplicate pages (and consequently wrong table of contents page pointers).
For example, try browsing for Handle JSON Patch Requests under Web API section. The table of contents page is wrong, and if you manually browse the contents for the topic you will find duplicate pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This should be reported at [MicrosoftDocs-feedback](https://github.com/MicrosoftDocs/feedback/issues).
