### ISSUE TITLE
HTML encoding on Blazor sample razor files

### ISSUE THREAD

**Issue by PWSys** [dotnet/AspNetCore.Docs#19569]
# Issue description
The sample applications below have an HTML encoding issue on the razor pages.  

https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/3.x/BlazorServerSample
https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/blazor/common/samples/3.x/BlazorWebAssemblySample

Examples below:
`&lt;div&gt;`

`&lt;h1 style="font-style:@@headingFontStyle"&gt;@@headingText&lt;/h1&gt;`

'@@code {}'

# Software versions
3.X

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @PWSys ... Some of that is normal escaping for Razor markup. The rest is normal encoding for showing tags in a rendered page. The apps are currently designed to show you information about what each component is doing in the rendered markup when you run the app. We'll be moving away from that approach when the sample apps are rebuilt on https://github.com/dotnet/AspNetCore.Docs/issues/14216 after .NET 5 releases later this year. The approach was **_very useful_** when Blazor was brand new and there were only a handful of scenarios. We won't be able to support that much content in the sample apps on the next round of sample updates.
