### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nb77qlik** [dotnet/AspNetCore.Docs#19577]
[Enter feedback here]
First ref to 'https://localhost:5001/api/TodoItem' should be 'https://localhost:5001/api/TodoItems' (as per Postman screenshot)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It is.

**Comment by nb77qlik** [comment]
Did this get fixed recently? As soon as I returned to the page it appears fixed...

**Comment by Rick-Anderson** [comment]
Yes, take a look at the [history](https://github.com/dotnet/AspNetCore.Docs/commits/master/aspnetcore/tutorials/first-web-api.md) 
Merge to live was an hour ago.
