### ISSUE TITLE
bad user experience if EmailSender service take long time to send email confirmation

### ISSUE THREAD

**Issue by FredHan001** [dotnet/AspNetCore.Docs#19571]
In ["Account confirmation and password recovery in ASP.NET Core"](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#implement-iemailsender) doc, we can find example approach of sending email confirmation is implementing a custom EmailSender service. 

But if sending email confirmation take long time as discussed in [this SO thread](https://stackoverflow.com/questions/63230038/asp-net-core-identity-at-register-page-register-then-wait-5-minutes-and-more), which would cause user waiting a long time on Register page.

Perhaps updating doc with a queue based background service as example approach of sending confirmation email would be better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio#implement-iemailsender)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> a queue based background service as example approach of sending confirmation email would be better.

A queue based won't solve that SO problem. Author needs to trouble shoot email sending.
