### ISSUE TITLE
Add signalr.js full path for easier understanding

### ISSUE THREAD

**Issue by DaeunSim** [dotnet/AspNetCore.Docs#19587]
Why don't you put the full path of signalr.js in the description box, or add a capture screen to the solution explorer?
Readers may misunderstand the path to wwwroot/js/signalr/signalr.js.

Link: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio#add-the-signalr-client-library

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @DaeunSim ... There's no "Description" field. I think you're addressing the "Target Location" field.

There's no meaningful full path to show. The path is relative to the project root, which can be anywhere on the drive that a project resides.

**Comment by DaeunSim** [comment]
> Hello @DaeunSim ... There's no "Description" field. I think you're addressing the "Target Location" field.
> 
> There's no meaningful full path to show. The path is relative to the project root, which can be anywhere on the drive that a project resides.



I appreciate your feedback.

I was confused whether the signalr.js file was generated on **Target Location Path**, 
or on **Target Location Path/dist/browser/**.
So I thought it would be better to add the **Target Location Path/dist/browser/signalr.js** path in the document.

**Comment by guardrex** [comment]
Side-note: It's more of a "copy" than a "generate." See the Visual Studio Code tab there. When using VSC, the steps require a manual copying of the files over with a console command (`--files` = file, `-d` = destination).

The target for the file (the destination) is the `wwwroot/js/signalr/` folder. This is just the way that that dialog works in VS. The remark under the dialog image seems clear ...

> LibMan creates a *wwwroot/js/signalr* folder and copies the selected files to it.

**Comment by DaeunSim** [comment]
> Side-note: It's more of a "copy" than a "generate." See the Visual Studio Code tab there. When using VSC, the steps require a manual copying of the files over with a console command (`--files` = file, `-d` = destination).
> 
> The target for the file (the destination) is the `wwwroot/js/signalr/` folder. This is just the way that that dialog works in VS. The remark under the dialog image seems clear ...
> 
> > LibMan creates a _wwwroot/js/signalr_ folder and copies the selected files to it.


I see what you mean. 
Thank you for your detailed explanation.
