### ISSUE TITLE
Sample source code link?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/AspNetCore.Docs#19589]
Hi,

Can you please include GH links to the project in this article?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @weitzhandler ... There won't be samples for this node of topics, at least not in the immediate future ...

* There's been a lot of new coverage added given that the Blazor WASM security API is new and devs needed to address a number of specific use cases with it. It's kept me quite busy just keeping up with covering the various security scenarios and configuration.
* The security is currently based on MS Identity Platform v1.0, but we knew that v2.0 would be adopted quickly. Most of the Azure docs and samples are already on v2.0. Blazor will go v2.0 with the .NET 5 release later this year.

Therefore, we won't have a linked samples for this node at this time. We may eventually have samples ... just not right now. I think we'd need to get beyond .NET 5's release and the aftermath of doc update requests that follow. Therefore, we'd be looking at 2021 if we wanted to place sample apps into the docs for this node.

What I did to counteract the negative consequences was to place the code from sample apps into the sections of the topic for inspection. That's worked fairly well thus far.

**Comment by weitzhandler** [comment]
Thanks for your kind detailed answer, Luke.
