### ISSUE TITLE
getting error at AddDefaultIdentity

### ISSUE THREAD

**Issue by vivektv111** [dotnet/AspNetCore.Docs#19588]
![image](https://user-images.githubusercontent.com/69970848/90771472-54f30680-e2c1-11ea-908b-7482fb0131ff.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The error message tells you everything you're missing.
