### ISSUE TITLE
Issue with the command "dotnet-aspnet-codegenerator"

### ISSUE THREAD

**Issue by ppv95** [dotnet/AspNetCore.Docs#19582]
In the "Scaffold a controller" part.
the command 
```
dotnet-aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
```
 it has a error syntaxis error and wont be executable in the terminal. It should be instead.

```
dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you miss this?

```
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet tool update -g Dotnet-aspnet-codegenerator
```

That's the new name for the tool, note it has the dash in the command

**Comment by ppv95** [comment]
> Did you miss this?
> 
> ```
> dotnet tool install --global dotnet-aspnet-codegenerator
> dotnet tool update -g Dotnet-aspnet-codegenerator
> ```
> 
> That's the new name for the tool, note it has the dash in the command

I did the  all the steps, including the ones you describe.
But i had to remove the dash from the command `dotnet aspnet-codegenerator controller`

**Comment by Rick-Anderson** [comment]
They ultimately run the same tool, but `dotnet SPACE aspnet-REST-of-command` is preferred because it has better error handling.
