### ISSUE TITLE
Current WebAPI documentation doesn't cover returning binary data

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/AspNetCore.Docs#19583]
While the API documentation discusses returning objects, as well as custom formatters, it does not cover how to return binary items (either `byte[]` arrays or `Stream` objects). 

It would be great if the documentation covered the `File` helper (as well as any other preferred way of returning binary streams). 

While there are tutorials online on this topic, there are lots of answers that suggest writing to the response stream, or using `HTTPResponse` objects, and it's unclear if this is recommended in modern ASP.NET Core. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-3.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
