### ISSUE TITLE
Need to show the code for `MyMiddleware`

### ISSUE THREAD

**Issue by Vaccano** [dotnet/AspNetCore.Docs#19591]
This page is fantastic in showing how to unit test a middleware.  But to replicate it, I need to see the code for `MyMiddleware` that it the code under test.  (It causes a 404 in some situations).

It would be nice to include the code for this file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9421feee-5207-e379-00fb-847cc880014c
* Version Independent ID: 8415adee-793e-2ba7-b97b-672b493ba42b
* Content: [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Tratcher
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Vaccano ... This isn't meant to be a tutorial. It's a reference doc that shows in a general way how to compose a test in a mostly arbitrary way. You would add/subtract from the tests as needed for whatever middleware that you want to test. My recommendation is for you to use an existing middleware that you have or just whip one up to try out the features described, then tailor the tests to that middleware.
