### ISSUE TITLE
Remote Validation does not seem to work for nested objects

### ISSUE THREAD

**Issue by MarcAir** [dotnet/AspNetCore.Docs#19594]
Remote validation for the samples provided seem to work for single level objects within a razor page.
however when validation is against objects in a model that are nested: E.g. 
 <input class="form-control" asp-for="@Model.CProfile.CompanySlug" />

the parameter that is added to the route by jquery includes a '.' which cannot be included as a parameter in the controller.
the resulting call get by jquery
https://localhost:5001/Company/VerifyCompanySlug?CProfile.CompanySlug=ttt

as you can see the parameter 'CProfile.CompanySlug' is not accessible by the action. the variable is always null when the remote call is made. 

perhaps adding detail about this Jquery flaw? or a way to potentially correct this issue?

thanks :) 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#additional-resources)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. jQuery behavior is beyond the scope of this article.
 Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
