### ISSUE TITLE
Add Cors section not the same as main page example.

### ISSUE THREAD

**Issue by lucasgl** [dotnet/AspNetCore.Docs#19606]
The example on add cors is using the app.UseSignalR instead of app.UseEndpoints

For me it worked only if I added cors in the endpoint.
```            
app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<NTLHub>("/NTLHub").RequireCors("cors");
            });
```

Which one is the latest? UseEndpoints or UseSignalR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by serpent5** [comment]
@Rick-Anderson Is it alright if I take this one?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Is it alright if I take this one?

Yes, that would be great, thanks.
