### ISSUE TITLE
Reference to `Wrapper`

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#19607]
The `Wrapper` ref is associated with additional code from [this blog post](https://blog.jeremylikness.com/blog/build-a-blazor-webassembly-line-of-business-app-part-4) that was not needed in this docs page.

Docs page:
```c#
var contact = await context.Contacts.FirstAsync(
        c => c.Id == Wrapper.DeleteRequestId);
```

Blog post:
```razor
<GridWrapper @ref="Wrapper"
             FilterChanged="async () => await ReloadAsync()"
             DeleteRequested="id => Wrapper.DeleteRequestId = id">
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment]
Hi @mrlife - not sure I understand the issue. The reference app uses the GridWrapper to propagate changes across controls. The snippet you show is excerpted directly from the sample project. The code for wrapper is there.

**Comment by mrlife** [comment]
@JeremyLikness Thanks for that clarification. Since `Wrapper` is not mentioned anywhere else on the page, I found it confusing. Maybe adding a note similar to your comment here would be a useful clarification in the docs.
