### ISSUE TITLE
SameSite issue for CorrelationIdCookie

### ISSUE THREAD

**Issue by Joshlo** [dotnet/AspNetCore.Docs#19629]
Hi,

With the change Google did to how Chrome handles "SameSite" for cookies, you might want to add troubleshooting to this site.
If you try to login with any of the providers you'll get "correlation failed cookie not found" out of the box in chrome, since SameSite by default is set to "Unspecified" and therefor isn't included in the request for the provider.

you'll need:
```
services.Configure<CookiePolicyOptions>(options => 
{
	options.MinimumSameSitePolicy = SameSiteMode.Lax; // or SameSiteMode.None;
});
```

and
`app.UseCookiePolicy();` before `app.Authorization();`

Because without that help you can spend hours in fiddler trying to figure it out.

Alse if you create your own Handler then it wouldn't find the cookie either for some reason when doing `HttpContext.AuthenticateAsync("<Scheme>");` and that resulted in an empty principal, but after adding that CookiePolicyOptions it works every time.

I hope it makes sense and that is can save other from staring at fiddler for hours :)

Best regards
Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not necessary. See [.NET Core support for the sameSite attribute](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1#net-core-support-for-the-samesite-attribute)

.NET Core 3.0 supports the updated SameSite values and adds an extra enum value, SameSiteMode.Unspecified to the SameSiteMode enum. This new value indicates no sameSite should be sent with the cookie.
