### ISSUE TITLE
Swashbuckle requires  GenerateDocumentationFile in .csproj file

### ISSUE THREAD

**Issue by Stallind** [dotnet/AspNetCore.Docs#19639]
For .net core 3.1 this part doesn't work
 `var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";`
 `var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile); `
  `c.IncludeXmlComments(xmlPath);`

unless you add   `<GenerateDocumentationFile>true</GenerateDocumentationFile>`  to the `<PropertyGroup>` of the .csproj file.  
  
I'd like to see that added to the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
3.0 is out of support. Is that true for 3.1?

**Comment by Rick-Anderson** [comment]
@bradygaster  @spboyer  @scottaddie  Is that correct? If so, I'll update the doc.

**Comment by Stallind** [comment]
@Rick-Anderson Thanks for replying. It's also true for 3.1

**Comment by spboyer** [comment]
@Rick-Anderson @Stallind - This is true and the current document [does mention it here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#xml-comments)

Swashbuckle docs mentions it as well [here](https://github.com/domaindrivendev/Swashbuckle#including-xml-comments).

C# Reference Docs also has a [how to](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc) for more information as well. 

@Rick-Anderson can close.

**Comment by Stallind** [comment]
> @Rick-Anderson @Stallind - This is true and the current document [does mention it here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio#xml-comments)
> 
> Swashbuckle docs mentions it as well [here](https://github.com/domaindrivendev/Swashbuckle#including-xml-comments).
> 
> C# Reference Docs also has a [how to](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc) for more information as well.
> 
> @Rick-Anderson can close.

Can't believe I missed that, I'm sorry about that. Thanks for checking
