### ISSUE TITLE
[RC1] Add documentation on DisplayName for validation messages

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#19633]
We now support setting a `DisplayName` attribute on InputNumber, InputDate, and InputSelect components. So for example, I can have a form that looks like this.

```
@page "/form"

<EditForm Model="@this" OnValidSubmit="@HandleValidSubmit">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text" id="birth-date">Date of Birth</span>
         </div>
         <InputDate Class="form-control" Id="DateOfBirth" @bind-Value="@BirthDate" DisplayName="birthday"/>
          <div class="invalid-feedback d-block">
              <ValidationMessage For="@(() => BirthDate)" />
          </div>
    </div>
</EditForm>

@code {
    public DateTime BirthDate { get; set; }

    public void HandleValidSubmit()
    {
        Console.WriteLine("foo");
    }
}
```

If the date field is invalid, then the validation message will read:

> The birthday must be a date.

Wheras previously, it would show this.

> The BirthDate must be a date.

We probably want to add this under the "Validation Support" heading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mxmissile** [comment]
Why does this apply to `<InputText...>` also?

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/22515.

@mxmissile ... Best to open a new issue. We don't work closed issues/PRs.
