### ISSUE TITLE
Document distinction between running with WebSockets enabled/disabled in Azure App Service

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#19649]
Azure App Service allows you to run an app service with WebSocket support enabled or disabled.

When WebSockets are disabled, the app service simulates a real-time connection using HTTP long-polling. This is noticeably slower than running with WebSockets enabled, which doesn't use polling to simulate.

We should recommend that folks deploying Blazor Server apps to Azure run with WebSockets enabled for perf improvements.

cc: @pranavkm @javiercn 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by pranavkm** [comment]
One thing we've punted on all along is simply disabling support for Long Polling by default in Blazor's Hub config. Do you want to bring this up as something to packle for now?

**Comment by captainsafia** [comment]
> One thing we've punted on all along is simply disabling support for Long Polling by default in Blazor's Hub config. Do you want to bring this up as something to packle for now?

Yeah. If we can do the right thing by default in the framework, that's probably better for users. Do we already have an issue tracking this?

**Comment by javiercn** [comment]
We can't disable long polling by default, that leads to a broken experience when your host doesn't have enabled websockets.
