### ISSUE TITLE
[Blazor] Can we make HttpRequestMessage options more visible?

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#19646]
It's hard to find docs for https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-5-release-now-available/#configure-http-fetch-request-options

It would be great if we could bring more visibility to it. (I tried explicitly googling for this several times and it takes me a few tries, and the best I get is the preview5 blog post announcement).

**Comment by guardrex** [comment]
We have it ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#httpclient-and-httprequestmessage-with-fetch-api-request-options

We should should move the section to the *Call web API* topic.

When I Google "HttpRequestMessage" and "Fetch," I get the *Call web API* topic as the 3rd returned result, which does refer to the terms in passing.
