### ISSUE TITLE
Use GetTestClient instead of GetTestServer().CreateClient()?

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#19645]
I was playing around with some of the stuff in this topic today, and I noticed the following:

```csharp
host.GetTestServer().CreateClient()
```

-can be replaced with-:

```csharp
host.GetTestClient()
```

It's only a minor point, but is it worth updating the example to use this approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9421feee-5207-e379-00fb-847cc880014c
* Version Independent ID: 8415adee-793e-2ba7-b97b-672b493ba42b
* Content: [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Tratcher
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There's [something broken in the API Browser](https://github.com/MicrosoftDocs/feedback/issues/2575#issuecomment-680154630), but yeah ... that looks good ...

https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/TestHost/src/HostBuilderTestServerExtensions.cs#L32

That goes back to 2.1, so we can cover back to 2.1 for it.

**Comment by Tratcher** [comment]
It was actually added 3.0: https://github.com/aspnet/Hosting/pull/1595

**Comment by guardrex** [comment]
My bad ... I looked at the wrong branch. I looked at the `2.1.3` branch and thought that it was dropped in after 2.1 released. Also, the API Browser is broken right now, and versions aren't showing up correctly at this time there.
