### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#19647]
Nice article. Perhaps you could add some tips on how to ensure that if a view name is changed, the change can be transmitted automatically to any references to the view in controllers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
pass in `viewName` as a strongly typed string rather than `"theViewName"` magic string

**Comment by xenophilios** [comment]
Thank you, Ric,k, for the fast response. Could you please demonstrate?
