### ISSUE TITLE
Adjust openapi dotnetcore tool docs

### ISSUE THREAD

**Issue by jkone27** [dotnet/AspNetCore.Docs#19657]
add details on how to use the feature in code, and from visual studio. with code examples

e.g. declare empty classes as partial, classname should be the same as openapi.json file,
also does not work for openapi.yaml, so it needs to be in json format.

is this using new C# source generators in the background?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by Rick-Anderson** [comment]
Dup of #15899
