### ISSUE TITLE
How to handle production secrets ?

### ISSUE THREAD

**Issue by Ninjanaut** [dotnet/AspNetCore.Docs#19658]
Hello,

If I implement user secrets or environment variables to store secrets for development purpose, how to handle production secrets ? Where should production secrets be located and in what form to avoid check-in to version control system ? Should I import, in run time, some secrets.json from location outside the project ? This seems as general approach for all environments, where I can only set `secretsLocationPath` attribute in related appsettings.json setting or is there any other preferred or established approach ?

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @Ninjanaut ... Environment variables are commonly used. If they leak or get hacked on a server, one has *serious problems to contend with* 😨 ... the whole server is probably compromised.

**Comment by scottaddie** [comment]
@Ninjanaut Azure Key Vault is the team's recommended approach for storing production secrets. You can learn more about using Key Vault [here](https://docs.microsoft.com/aspnet/core/security/key-vault-configuration). I have an example [here](https://github.com/scottaddie/ViewComponentsDemo/blob/d1969f283d0e560681fef5d9e5110941e4ad1cfd/ViewComponentsDemo/Program.cs#L22-L42) of how I've used Secret Manager in Development and Key Vault in Production.

**Comment by guardrex** [comment]
The current topic already covers both ... if you mean for the AKV config provider ...

https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1

**Comment by guardrex** [comment]
What we don't have tho is a cross-link to the **new** (new-ish :smile: ... it's been around for a while now) ... the new Azure features for setting the secrets via the UI. It's probably faster than those commands. Also, the commands themselves could be offloaded from this doc set to the Azure docs if we had the desire and time to do so.

**Comment by scottaddie** [comment]
@guardrex Do you have a link to that UI doc? I'm working on this doc for an internal project.

**Comment by guardrex** [comment]
I don't ... at the time this was written those AKV UI features didn't exist. Since then tho, I think they have something, but it might just be a tutorial section.

**Comment by Ninjanaut** [comment]
Thank you very much for your answers. For production I will try to use environment variables configured directly on the IIS server, because I do not have AKV available yet and for development I will use Secret Manger in the visual studio.

**Comment by scottaddie** [comment]
Closing this issue, as there are already other issues to track the problems I'm addressing.
