### ISSUE TITLE
Doesn't have example of adding Redis to DI container

### ISSUE THREAD

**Issue by Tommigun1980** [dotnet/AspNetCore.Docs#19680]
I looked everywhere on how to set up Redis, and the only mention of this is:

"An app configures the cache implementation using a RedisCache instance (AddStackExchangeRedisCache)."

Does that mean?
`services.AddStackExchangeRedisCache(options => { });`

Why not have that as an example instead, as all other MS documentation does for configuring the services?
It is absolutely misleading to talk about some RedisCache instance, in case that is what it is trying to convey. What 'RedisCache' instance does it talk about? It mentions AddStackExchangeRedisCache but doesn't say what class it is in. Are we supposed to magically guess where things are?

So I think `services.AddStackExchangeRedisCache(options => { });` should be added. The page contains examples for the other cache providers,

```c#
services.AddDistributedSqlServerCache(options => ...
services.AddNCacheDistributedCache(configuration => ...
```

so why not for Redis?

Furthermore -- AddStackExchangeRedisCache doesn't seem to be documented anywhere. What options are mandatory? Does it work like other Azure services, such as Azure SignalR Service, that if no connection string is specified it will use the appropriate app service string/app setting automatically ("CacheConnection" in this case)? Or does it need to be set somewhere?

Documentation is supposed to tell these things. I shouldn't have to play detective to set something up as simple as this.

See https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-dotnet-core#add-azure-signalr-to-the-web-app for how other services document this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-dotnet-core-quickstart

**Comment by Tommigun1980** [comment]
> See https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-dotnet-core-quickstart

Hi Rick and thanks for the answer. I can’t see AddStackExchangeRedisCache being mentioned at all in the document you linked to, nor the mandatory parameters in it. Maybe I’m just missing it?

**Comment by Rick-Anderson** [comment]
@petrsvihlik can you provide the code to use Azure Redis cache?  Something like

```
 services.AddStackExchangeRedisCache(options =>
            {
                options.Configuration = <MyEndpoint>;
                options.InstanceName = "MyInstance";
            });
```

**Comment by petrsvihlik** [comment]
@Rick-Anderson yeah, here are the steps I've just taken to make it work with Azure Redis:

1. Spin up the [Azure Cache for Redis](https://azure.microsoft.com/en-us/services/cache/)
2. Navigate to the resource's Access Keys
![image](https://user-images.githubusercontent.com/9810625/92040918-8666da00-ed77-11ea-82df-6b35bb34da09.png)
3. Copy the connection string for StackExchange.Redis
4. Configure the Startup class as follows:
![image](https://user-images.githubusercontent.com/9810625/92041025-be6e1d00-ed77-11ea-9e69-fbd8616121d3.png)
5. 🎉🎈 It works!

PS: sorry for the delayed answer, we just had a baby so I'm quite busy :)

**Comment by Rick-Anderson** [comment]
@petrsvihlik  Congratulations on the new baby. Thanks for this info, I'll get the doc updated.

**Comment by Rick-Anderson** [comment]
@petrsvihlik  I can't have an example of copy/paste PW into code. How do you recommend I get the config? I could have them copy/paste into the environment and access that way.

**Comment by petrsvihlik** [comment]
@Rick-Anderson definitely. On a local machine, I'd go with User Secrets and anywhere else either Environment Variables or a Key Vault. So the env variables seem to be the easiest way to demonstrate the usage while not going against the [best practices](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows).
