### ISSUE TITLE
most github samples are self contained. Yours isn't. Very frustrating

### ISSUE THREAD

**Issue by cellurl3** [dotnet/AspNetCore.Docs#19686]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-3.1#how-to-download-a-sample)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment.
