### ISSUE TITLE
Issue with Claims in this example

### ISSUE THREAD

**Issue by JSpring3** [dotnet/AspNetCore.Docs#19687]
I posted this issue on stackoverflow but I thought you might want to know about it.

https://stackoverflow.com/questions/63621523/how-do-i-use-the-blazor-clientside-authorizeview-control-policy-feature-with-azu

I am using the Microsoft example featured at this link https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1

My Program.cs file looks like this

```
 public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("#app");

            builder.Services.AddScoped(sp => 
             new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

            builder.Services.AddAuthorizationCore(config =>
            {
                config.AddPolicy("BackOfficeEditor", policy =>
                    policy.RequireClaim("groups", "4dd6726b-3949-4b8a-a8e0-9e5eaa65e358"));
            });


            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
            });

            await builder.Build().RunAsync();
        }
    }

```
My index.razor files looks like this
```
@page "/"
<AuthorizeView Policy="BackOfficeEditor">
    <p>You can only see this if you satisfy the 
    <b style="color:magenta;font-size:larger">
    BackOfficeEditor</b> policy.</p>
     </AuthorizeView>

    <AuthorizeView>
        <NotAuthorized>
            <br />
            You are not logged in
            <br />
        </NotAuthorized>
        <Authorized>
            <br />
            Hello, @context.User.Identity.Name! <br />
            <h2>here's the list of your claims:</h2>
            <ul>
                @foreach (var claim in context.User.Claims)
                {
                    <li><b>@claim.Type</b>: @claim.Value</li>
                }
            </ul>
        </Authorized>
    </AuthorizeView>
```
You can see in the claims in the attached screenshot that the user (minonOne) has the right claim in the "groups" section but it doesn't display the custom message I added for users in that group.
![stackOwerflowPic1](https://user-images.githubusercontent.com/34101090/91490126-f230da80-e87f-11ea-90c8-e1f0cc500b1d.jpg)

I tried the following and it worked. It seems like it's treating the "groups" collection like a literal string.
```
                config.AddPolicy("BackOfficeEditor", policy =>
                    policy.RequireClaim("groups", "[\"4dd6726b-3949-4b8a-a8e0-9e5eaa65e358\"]"));
```
Did I find a bug or did I do something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b9c5cb-0e48-25bc-2b7e-e7354bafbe2d
* Version Independent ID: b1e8aedc-b46b-41f1-55c1-e293bc6c93db
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The `groups` claim has to be converted into individual `group` claims with a custom user factory. See ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles
