### ISSUE TITLE
.NetCore WebApi Controller Action methods: return Task or VallueTask?

### ISSUE THREAD

**Issue by DrGriff** [dotnet/AspNetCore.Docs#19681]
From the Microsoft documentation [Examine the PostTodoItem create method](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#examine-the-posttodoitem-create-method) we see the following code in the API's Controller:
```
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem todoItem)
{
    ....
}
```
This returns a Task<T>, but since this is only ever awaited, could/should it return a ValueTask<T>?  Does the answer differ if hosted by IIS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It returns `Task<ActionResult<TodoItem>>` and has nothing to do with IIS.

**Comment by DrGriff** [comment]
@Rick-Anderson: apologies if I wasn't clear, but I think you may have misunderstood the question.

So the question is regarding the use of `Task<T> vs ValueTask<T>`, in other words, is it better go to with:
```
Task<ActionResult<TodoItem>>
```
or
```
ValueTask<ActionResult<TodoItem>>
```

I'm referring to Stephen Toub's argicle [Understanding the Whys, Whats, and Whens of ValueTask](https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/)

As for IIS, one can host a .Net Core WebApi in IIS, or not in IIS.  I mentioned IIS because I wondered if the web hosting model may affect the decision.

**Comment by Rick-Anderson** [comment]
The recommended return is what we have. That's what the scaffolder generates.

The hosting model has nothing to do with this.
