### ISSUE TITLE
Scope validation section should be updated

### ISSUE THREAD

**Issue by raman-kazhadub** [dotnet/AspNetCore.Docs#19682]
There are 3 points for scope validation:
- Scoped services aren't resolved from the root service provider.
- Scoped services aren't injected into singletons.
- Transient services aren't injected into singletons or scoped services.

But the last one is not true, transient service can be injected to singletons or scoped service (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-3.1#scope-validation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @raman-kazhadub ... I'll add the cross-link to the commit where it came in for the discussion ...

https://github.com/dotnet/AspNetCore.Docs/pull/19271/commits/a662030c90f6dfc223a86bfe6dca1f924588aed7#diff-6326842a605b080714f289bc8cb24390R428

**Comment by Rick-Anderson** [comment]
@serpent5  do you want to remove the following line?

`* Transient services aren't directly or indirectly injected into singletons or scoped services.`

**Comment by serpent5** [comment]
@Rick-Anderson Sure, I'll do it now.

**Comment by serpent5** [comment]
Thanks @Rick-Anderson. That point _made sense_, but clearly it wasn't actually correct. 🤭
