### ISSUE TITLE
How to do Business Validation with ObjectGraphDataAnnotationsValidator & complex types?

### ISSUE THREAD

**Issue by Assassinbeast** [dotnet/AspNetCore.Docs#19685]
Making complex types validation with the `ObjectGraphDataAnnotationsValidator` works.

But how do you add custom errors with the `CustomValidator` to do business validation? 
I tried to add error with the key `ShipDescription.ShortDescription` key, eg:

```
errors.Add("ShipDescription.ShortDescription", new List<string>() { "Some error" });
customValidator.DisplayErrors(errors);
```

But it didn't work.
I assume that was the key since the form models property path is `starship.ShipDescription.ShortDescription`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Assassinbeast ... Sorry for the delay. I've been 🏃😅 lately. I'll take a look at this and get back to you soon.

**Comment by guardrex** [comment]
Ok ... It went well, except I did discover a nit along the way.

I set up a test like this ...

```csharp
public class ShipDescription
{
    [Required]
    [StringLength(40, ErrorMessage = "Description too long (40 char).")]
    public string ShortDescription { get; set; }

    [Required]
    [StringLength(240, ErrorMessage = "Description too long (240 char).")]
    public string LongDescription { get; set; }
}
```

... with ...

```csharp
[ValidateComplexType]
public ShipDescription ShipDescription { get; set; } = new ShipDescription();
```

... on my `Starship` class. **NIT** ... The current example doesn't new up the `ShipDescription`, so the code example from the topic fails if it isn't created *somewhere* before the fields are bound to the form. It could be done in the component, too, like this ...

```csharp
private Starship starship = new Starship()
                            {
                                ProductionDate = DateTime.UtcNow,
                                ShipDescription = new ShipDescription()
                            };
```

The simplest way to go tho is just to add a ` = new ShipDescription();` in the class to make it happy and load the component without an NRE.

I use the same `CustomValidator` component described earlier in the topic.

The form gets ...

```razor
<EditForm Model="@starship" OnValidSubmit="@HandleValidSubmit">
    <DataAnnotationsValidator />
    <ObjectGraphDataAnnotationsValidator />
    <CustomValidator @ref="customValidator" />
    <ValidationSummary />

    ...
```

... with ...

```razor
<p>
    <label>
        Long Description:
        <InputTextArea @bind-Value="starship.ShipDescription.LongDescription" />
    </label>
</p>
<p>
    <label>
        Short Description:
        <InputTextArea @bind-Value="starship.ShipDescription.ShortDescription" />
    </label>
</p>
```

... and ...

```csharp
private CustomValidator customValidator;
```

I then add a custom check to see if the `LongDescription` starts with a capital letter ...

```csharp
private void HandleValidSubmit()
{
    customValidator.ClearErrors();

    var errors = new Dictionary<string, List<string>>();

    char[] ldesc = starship.ShipDescription.LongDescription.ToCharArray();
    var startsUppercase = char.IsUpper(ldesc[0]);

    if (!startsUppercase)
    {
        errors.Add(nameof(starship.ShipDescription.LongDescription),
            new List<string>() { "The Long Description must start with an uppercase character." });
    }

    if (errors.Count() > 0)
    {
        customValidator.DisplayErrors(errors);
    }
    else
    {
        formStatus = "The form processed successfully!";
    }
}
```

..... sooooo .... It's all just about as expected with the explanation provided in the *Business logic validation* section.

I **do** want to fix that nit.

In the code that you showed, I used `nameof` to avoid the magic string. `nameof(starship.ShipDescription.LongDescription)` evaluates to ...

```
LongDescription
```

... that's it. If you prefer that ✨ *magic string* ✨, try it as ...

```csharp
errors.Add("ShortDescription", new List<string>() { "Some error" });
```

Leave this issue open. It will close when the PR merges for that nit that I identified.
