### ISSUE TITLE
It would be helpful to specify how to use optional parameters

### ISSUE THREAD

**Issue by mschluper** [dotnet/AspNetCore.Docs#19695]
I'd like to have routes 
(1) ~/admin/user
(2) ~/admin/users?siteID=42

I'd expect .NET Core to support these two in one endpoint, but I cannot find on this page how to do this. There is something about optional parameters but this is limited to a route like

(3) ~/admin/users/42

But that's not what I want. It's not a request for user 42, but for site 42.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1#parameter-transformer-reference)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there, keep reading.
