### ISSUE TITLE
Blazor CascadingParameter design has multiple flaws

### ISSUE THREAD

**Issue by velocitytoo** [dotnet/AspNetCore.Docs#19698]
The Blazor CascadingParameter design has multiple flaws:

1) A child component has to know that its parameter will be used in a cascading manner and has to decorate the parameter with [CascadingParameter]. Why not just come up with a design so that a child component does not have to know whether or not it will be used in a cascading manner? This would be a much better SOC design; only the parent should have to know how the child's parameters will be used. For children, properties should simply use [Parameter] everywhere, and a proper cascading design should allow for cascading usage/specification (or not) at the parent (higher) level only.

2) The [CascadingParameter] attribute uses a string to identify the parameter to cascade! This is a horrible design pattern. We have all the type-safety, compile-time checks, and reflection of .NET at our disposal now, and someone chose to use a string value to represent the identifier of the parameter. Why? a) What if I want to change the string identifier of the parameter (answer: I have to do a fuzzy search through all the code to try to make the change, which puts us right back to the Javascript world, ugh). b) What if I have two different types of child components that for some reason decided to use the same identifiers for their cascading parameters? Such a poor design choice.

Can we please come up with a better design choice for cascading parameters in Blazor?

**Comment by guardrex** [comment]
Hello @velocitytoo ... We only handle the docs on this repo. Please open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
