### ISSUE TITLE
Configure ASP.NET Core project without Webpack?

### ISSUE THREAD

**Issue by scheelings** [dotnet/AspNetCore.Docs#19696]
Is it possible to add the SignalR Typescript library to an existing ASP.NET Core project without Webpack?

I have this existing ASP.NET Core project where I use TypeScript, RequireJS and Gulp to compile (and copy) my TypeScript files. I do not want to add WebPack to this configuration, but I cannot seem to find out how to add SignalR to this project.
Can somebody help me with this? I would be nice to have an AspNetCore Doc for this ;-)

Regards,
Danny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by scottaddie** [comment]
@scheelings Gulp and RequireJS replace the task runner and module loading capabilities that Webpack provides. You'll need to add the SignalR JavaScript client library to your project. Choose one of the 3 approaches documented at https://docs.microsoft.com/aspnet/core/signalr/javascript-client#install-the-signalr-client-package. For questions on how to load the client library via RequireJS, we recommend that you ask over at StackOverflow.

**Comment by scheelings** [comment]
OK, thx.
But this way I do not have the possibility to use intellisense in TypeScript, because there are no type definitions available at https://definitelytyped.org/.
