### ISSUE TITLE
Link in "Publish to Azure" section points to "error 404 - Content Not Found" page

### ISSUE THREAD

**Issue by Tuan96** [dotnet/AspNetCore.Docs#19705]
[Enter feedback here]
In the "Publish to Azure" section in "Part 10, examine the Details and Delete methods of an ASP.NET Core app"
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-3.1

Quoted:
"For information on deploying to Azure, see Tutorial: Build a .NET Core and SQL Database web app in Azure App Service."

When I click on the tutorial link, it points to this link, which returns error 404. 
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-dotnetcore-sqldb

I believe this should be the right link: 
https://docs.microsoft.com/en-us/azure/app-service/tutorial-dotnetcore-sqldb-app?pivots=platform-linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97234f18-4009-0ebf-a379-9b63125529cd
* Version Independent ID: 1bf4792d-dab4-e03d-2021-3dcdcaff6a0f
* Content: [Part 10, examine the Details and Delete methods of an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/details.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/details.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you'd like to fix this one.
