### ISSUE TITLE
Scope validation recommendation mixes up Singleton and Scoped

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#19703]
I was just reading through some of the suggestions in here, and I noticed this bullet, which I think is the wrong way around:

> Enable scope validation to make sure the app doesn't have scoped services that capture singletons. For more information, see Scope validation.

Should it be?:

> Enable scope validation to make sure the app doesn't have **singletons** that capture **scoped services**. For more information, see Scope validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  please fix. Arg, I missed that one.

**Comment by serpent5** [comment]
I think this was more my fault, really.

This is what it was:

> Enable scope validation to make sure the app doesn't have scoped services capturing singletons.

I changed it like so:

> Enable scope validation to make sure the app doesn't have scoped services **that capture** singletons.

I wonder if the original version was somehow describing the singleton as being "scoped service capturing"...

Anyhoo, I'll fix it up.
