### ISSUE TITLE
Component instance method callback helper constructor method is incorrect.

### ISSUE THREAD

**Issue by swijnands** [dotnet/AspNetCore.Docs#19709]
The  example for the Blazor Server Side component instance Javascript to .NET callback helper class (_MessageUpdateInvokeHelper.cs_) contains an error:

```
public class MessageUpdateInvokeHelper
{
    private Action action;

    public MessageUpdateInvokeHelper(Action action)
    {
        action = action;
    }
    ....
} 

```

The constructor does not actually assign the parameter 'action' to the field 'action', but actually assigns the parameter to it self. 
It was quite confusing why I was receiving a NullReferenceException ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#component-instance-method-helper-class)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @swijnands ... We recently moved away from underscores on field names. It should just be `this. action = action;`. I'll patch that right now. Thanks for reporting it.
