### ISSUE TITLE
End-to-end tutorial

### ISSUE THREAD

**Issue by JohnStraumann66** [dotnet/AspNetCore.Docs#19707]
[Enter feedback here]
Hello:

Is there an end-to-end tutorial somewhere that goes through building out an ASP.NET Core Website, and incrementally adds features providing explicit "walk though" instructions at each step? So for example, start with a HelloWorld, then add DB access, then add User Account Security, etc. and build the site step-by-step? I have found many tutorials, but they are not linked together, they cover individual topics. What would be really cool is a book that builds out an entire web site, step-by-step.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, but all you need to do is scaffold identity, follow the tutorials you've found, and examine the code.
