### ISSUE TITLE
The Sample Code

### ISSUE THREAD

**Issue by SaravananRIndia** [dotnet/AspNetCore.Docs#19717]
Looks like the sample code has not been updated to ASPNET Core 3.1 and fails to run when downloaded.

Can this be updated at the earliest pls.

SaravananR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by SaravananRIndia** [comment]
The Sample code has not been udpated to run on ASPNET Core 3.1, and that is a kind of blocker in our learning process.

**Comment by Rick-Anderson** [comment]
All the snippets work fine in 3.1

I'll be updating for 5.0 RC1 next week.

**Comment by SaravananRIndia** [comment]
I had downloaded Sample code to experiment  ErrorHandling.  And in the csproj configured for 2.2 as below, 

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
