### ISSUE TITLE
Breakpoint set but not yet bound

### ISSUE THREAD

**Issue by StefanLundmark** [dotnet/AspNetCore.Docs#19723]
I have followed the instructions on this page and the only thing I get when placing breakpoints is that the "Breakpoint set but not yet bound". Some information:

- I tried both creating the project from the template dialogs in Visual Studio 2019, Version 16.5.4 - and from the command line by creating a new blazorwasm project.
- I tried with both IIS Express and BlazorApp as debug targets.
- WebAssembly Nuget versions are v3.2.1 
- Target framework appears to be .NET Standard 2.1
- "Enable JavaScript debugging for ASP.NET (Chrome, Edge and IE)" is enabled.
- In the template dialogs the .NET Core version is mentioned as 3.1.8.
- Browser is Chrome.
- Edge refuses to work, says it "Failed to launch debug adapter" with "ECONNREFUSED". Could it be related to my issues in Chrome?
- Breakpoint is at "currentCount++" in Counter.razor from the example project.

Tried on two different computers, same issue and same parameters above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StefanLundmark ... Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
