### ISSUE TITLE
Bundling does not work by adding bundleconfig.json

### ISSUE THREAD

**Issue by MithunChopda** [dotnet/AspNetCore.Docs#19729]
Is there anything else that needs to be done in addition to adding the bundleconfig.json file? The path specified in outputFileName attribute in the bundleconfig.json file does not resolve when running a .net core 3.1 MVC application.
I don't want to rely on Third party tools like Gulp or Grunt. Is it possible to do bundling and minification without using a third party library? is it supported out-of-box in .net core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1&source=docs)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by damienbod** [comment]
@MithunChopda You need to add the nuget package. Here's a blog showing how you could do this with npm to load the packages. You could also use libman instead.

https://damienbod.com/2018/11/09/asp-net-core-mvc-ajax-form-requests-using-jquery-unobtrusive/

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by MithunChopda** [comment]
Can you please add this dependency to the original document? I found lot of questions regarding this on StackOverflow. Adding a note on the need for the nuget package will make it easy for reader to follow and implement.

**Comment by damienbod** [comment]
@Rick-Anderson I could add this, if you want, sounds like a good idea.

Greetings Damien

**Comment by Rick-Anderson** [comment]
@damienbod  that would be  great, thanks
