### ISSUE TITLE
Typed HttpClient in singleton component

### ISSUE THREAD

**Issue by Kamil-Zakiev** [dotnet/AspNetCore.Docs#19724]
Hello, could you please clarify if it's OK to inject typed HttpClient to singleton component.

Will be the underlying HttpClientMessageHandler instances managed? Or should I avoid injecting typed HttpClient (which is transient) to Singleton component?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#outgoing-request-middleware)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Dup of  #19354
