### ISSUE TITLE
@bind-style Generating Unintelligible Compiler Error

### ISSUE THREAD

**Issue by CincySteve** [dotnet/AspNetCore.Docs#19721]
[EDIT by guardrex to add the metadata and the code block ... @CincySteve, please use the **This page** feedback form at the bottom of any topic to open a new issue, which will add the metadata automatically. Also, GitHub uses triple backticks for code blocks.]

Just came across the ability to dynamically include styling in an html element via @bind-style as described in [this document](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1).  I get the following compiler error message, which is unintelligible to me, on the following code, which mirrors the example in the documentation.

The attribute names could not be inferred from bind attribute 'bind-style'. Bind attributes should be of the form 'bind' or 'bind-value' along with their corresponding optional parameters like 'bind-value:event', 'bind:format' etc.	

```razor
<td contenteditable="true" style="border: 1px solid; border-color: lightgray">
    <input @bind-style="inputStyle" @bind=@TableValueList[@year - @CBB.BBHeader.FirstYear][@colIndex].Value_Decimal />
</td>

@code {
    private string inputStyle = "color:red";
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It requires the event for the delegate. Do it this way using whatever [event](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1#event-argument-types) makes sense for your `<input>` element ...

```razor
<input @bind-style="inputStyle"  @bind-style:event="onchange" ... />
```

I'll add a remark to the doc to cover this requirement.

**Comment by guardrex** [comment]
Actually, I think we'll let this remark stands as is ...

> Use `@bind-{ATTRIBUTE}` with `@bind-{ATTRIBUTE}:event` syntax to bind element attributes other than `value`. 

It's also in the example that goes with the text.

I'll keep an :ear: open for more feedback. If devs write in on it, then I'll try something else

**Comment by CincySteve** [comment]
I'd like to make a final comment as this issue gets closed.  If the purpose of @bind-style is to provide a means to style an element (only) when an event occurs, the documentation does not make that clear to me.

I can use @variables within the style attribute of the html markup, thereby providing a way to set style settings based on program values.  As such, I don't need @bind-style.  Assuming that's true, I don't think the documentation makes clear that the purpose of @bind-style is to re-style an element (only) when an event occurs.  If that's not true, then at least to this Blazor user, the purpose of @bind-style and the documentation behind it are not clear.  Sorry if I am being a dunce on this.

**Comment by guardrex** [comment]
You can set **_any_** attribute value this way, not just a `style` value. A style just happens to be an example here. The concept is to cover `@bind-{ATTRIBUTE}` on the basis of a DOM event.

I'll keep an :ear: open for more feedback on it.

**Comment by guardrex** [comment]
Keep in mind that this content isn't in a new section. It immediately flows from ...

> Bind a property or field on other events by also including an @bind:event attribute with an event parameter.

It's describing the same scenarios ...... but for attributes on the element for whatever DOM event you need to track.

**Comment by guardrex** [comment]
I've come around to the way that you've framed this. The `onchange` event isn't the best example because the `onchange` event is the default event for the element losing focus. In this example, it only makes sense to use the `onchange` event to capture a complete style string for the paragraph's style. It would be better to bind a non-default event, like `oninput` and use a different example so that the user can make a change in the `<input>` and get immediate UI feedback (of some sort) on the other element. It could still be a style change ... just not this one.

I'll give it a shot and see what I come up with. I don't think there's anything cosmically wrong with what the text says or what the example shows, but it's not the best demo of this concept. Thanks for being persistent.

**Comment by guardrex** [comment]
@CincySteve ... **_I totally agree with you now_**. Sorry for not seeing it sooner and thanks again for your persistence ... *and patience!*

I did some testing with what I thought was an actual framework feature; but when I went down the rabbit hole with it, it felt more like 🏰 *Wonderland* 🏰. I suspect that I misinterpreted some remarks/discussion from one or more engineering issues and **_totally made something up_** that doesn't exist. This was reviewed and approved, but it's more my fault than their fault. It was small part of a larger set of changes that improved binding coverage, and I clearly didn't have a clear head on it nor test it enough.

I've opened an engineering discussion to get to the bottom of it at https://github.com/dotnet/aspnetcore/discussions/25490. I suspect that they're going to say that **_direct assignment_** is the way to go, as you suggested. I'll address this text+example as soon as I hear back from them. Stand-by ... I think we'll get a resolution to this fairly quickly.

**Comment by guardrex** [comment]
Now that I've dropped that content, I'll hold the content here for reference ...

> Use \`\@bind-{ATTRIBUTE}\` with \`\@bind-{ATTRIBUTE}:event\` syntax to bind element attributes other than \`value\`. In the following example:
>
> \* The paragraph's style is \*\*red\*\* when the component loads (\`style="color:red"\`).
> \* The user changes the value of the text box to reflect a different CSS color style and changes the page's element focus. For example, the user changes the text box value to \`color:blue\` and presses the \<kbd>Tab\</kbd> key on the keyboard.
> \* When the element focus changes:
>   \* The value of \`paragraphStyle\` is assigned from the \`\<input>\` element's value.
>   \* The paragraph style is updated to reflect the new style in \`paragraphStyle\`. If the style is updated to \`color:blue\`, the text color changes to \*\*blue\*\*.
>
> \`\`\`razor
> ```
> <p>
>     <input type="text" @bind="paragraphStyle" />
> </p>
>
> <p @bind-style="paragraphStyle" @bind-style:event="onchange">
>     Blazorify the app!
> </p>
>
> @code {
>     private string paragraphStyle = "color:red";
> }
> ```
> \`\`\`

**Comment by CincySteve** [comment]
That's now clear to me, including both the description and the example.  Thanks for collaborating to make this improvement.

**Comment by guardrex** [comment]
Sure thing ..... don't close this yet tho ..... I still need to resolve this issue. This issue will automatically close when the upcoming PR merges.

**Comment by guardrex** [comment]
@CincySteve ... So yeah ... I can hear David now on this one ...

> **_That's not a thing. You just made that up._** — David Fowler, 2016

See Steve's remark at ... https://github.com/dotnet/aspnetcore/discussions/25490#discussioncomment-86109.

IIRC, I based the original coverage on some engineering remarks that I thought worked. It seemed like in a quick test that it worked, too. It was also approved (but in fairness, it went in on a PR with *a lot* of other coverage updates on binding, so it snuck in on that PR 😈).

No further action is required because the content was pulled when you raised this issue. This issue is fixed by https://github.com/dotnet/AspNetCore.Docs/pull/19743.

Thanks for writing in on it. This *very rarely happens*, and I'll continue efforts to avoid it.
