### ISSUE TITLE
StartMode=AlwaysRunning does not work unless you change garbage collection settings

### ISSUE THREAD

**Issue by unionthugface** [dotnet/AspNetCore.Docs#19733]
The suggestions mentioned in the document for the Application Initialization Module that allegedly make a .NET Core app restart after shutdown in IIS (StartMode=`AlwaysRunning` and IdleTimeout=`0`) are not sufficient by themselves.  With these settings, an app will get to the end of the application lifetime and still shut down without restarting; a hard recycle of the app will likewise shut the app down without restarting it.  The missing component for me was changing the garbage collection settings:

```
<PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
</PropertyGroup>
```

See issues:
https://github.com/dotnet/aspnetcore/issues/3849
https://github.com/dotnet/aspnetcore/issues/19509

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Let's keep the issue in dotnet/aspnetcore#19509 until it's verified
