### ISSUE TITLE
Issue with controller code generator instuctions

### ISSUE THREAD

**Issue by mnapoleon** [dotnet/AspNetCore.Docs#19739]
[Enter feedback here]
The VS Code section for installing the aspnet-codegenerator appears to be wrong.  Following these instructions
```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet tool update -g Dotnet-aspnet-codegenerator
dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers
```

I continually get this message running the last line.

```
Building project ...
Finding the generator 'controller'...
No code generators found with the name 'controller'
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:03.16

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The instructions are correct. Make sure you've installed the currently release .NET Core SDK.

**Comment by donhuvy** [comment]
This problem happen again

![image](https://user-images.githubusercontent.com/1328316/114268482-86286e80-9a2b-11eb-8cf1-5aa91ea1e57c.png)

**Comment by donhuvy** [comment]
I add video for you easy investigate


https://user-images.githubusercontent.com/1328316/114268734-e835a380-9a2c-11eb-97ed-2378f8a51050.mp4

**Comment by Rick-Anderson** [comment]
Use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture within VS, which open internal issues for the VS team and send me the link. I'll push the bug internally.
