### ISSUE TITLE
Tiny, but possibly crucial, detail

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#19747]
Thank you for a very nice article.

In the section copied in the following image, I had to add an at-sign to the highlighted "await" to get this example to work.

![image](https://user-images.githubusercontent.com/50146995/91881109-a0ed6600-ec46-11ea-9476-ab9c85fc0947.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@xenophilios  can you paste in the code you used?

**Comment by Rick-Anderson** [comment]
```
@model PartialViewsSample.ViewModels.Article

<h2>@Model.Title</h2>
@* Pass the author's name to Views\Shared\_AuthorPartial.cshtml *@
@await Html.PartialAsync("_AuthorPartial", Model.AuthorName)
@Model.PublicationDate

@* Loop over the Sections and pass in a section and additional ViewData to 
   the strongly typed Views\Articles\_ArticleSection.cshtml partial view. *@
@{
    var index = 0;

    foreach (var section in Model.Sections)
    {
        await Html.PartialAsync("_ArticleSection", 
                                section,
                                new ViewDataDictionary(ViewData)
                                {
                                    { "index", index }
                                });

        index++;
    }
}
```

**Comment by xenophilios** [comment]
Yes, that's it.

**Comment by Rick-Anderson** [comment]
That's not required, because it's in a code block started by `@{`

**Comment by xenophilios** [comment]
That's what I thought, too. But the proof of the pudding is in the eating. Perhaps there was some other issue in my environment.
