### ISSUE TITLE
[DOCS] Browser requirements - list the actual browser version

### ISSUE THREAD

**Issue by christoment** [dotnet/AspNetCore.Docs#19740]
**Hi .NET Core team,**

At the moment, the [Browser requirements page](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1) only shows "Current" instead of the actual browser version required. This made it hard to figure out the exact minimum version we need to support.

Can we put the actual browser version that was tested by .NET Team in this page?

![image](https://user-images.githubusercontent.com/35278147/91783468-b0b77b00-ec43-11ea-93e2-79bfcf7a9f10.png)
**Figure: No specific browser version listed in the browser requirement**

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @christoment ... It's been discussed with engineering a few times, and they can't  report supported browser versions for Blazor due to the support policy for SignalR, which is "current." It's up to devs to test their apps with browser versions that they wish to support and report to their users which versions to use.
