### ISSUE TITLE
Disable Javascript output from blazor.server.js

### ISSUE THREAD

**Issue by flacidsnake** [dotnet/AspNetCore.Docs#19744]
After logging in, the access token used to connect to SignalR is printed to the browser console. Could you explain if there is any way to disable this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff954815-0f8b-9f1b-9772-1657744b4f9e
* Version Independent ID: ed7d726d-41c6-73d8-d564-91530b4935c3
* Content: [Threat mitigation guidance for ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/server/threat-mitigation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/threat-mitigation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @flacidsnake ... Ask that question on the product unit's repo at ...

https://github.com/dotnet/aspnetcore/issues
