### ISSUE TITLE
where-can-i-see-the-request-data-in-an-asp-net-core-webservice

### ISSUE THREAD

**Issue by cellurl3** [dotnet/AspNetCore.Docs#19750]
https://stackoverflow.com/questions/63694552/where-can-i-see-the-request-data-in-an-asp-net-core-webservice

**Comment by guardrex** [comment]
Hello @cellurl3 ... You did the right thing opening that support question at SO. We don't provide product support. We just work on the docs. In addition to SO, you can chat with devs at Slack and Gitter ...

* [ASP.NET Core Slack](http://tattoocoder.com/aspnet-slack-sign-up/)
* [ASP.NET Gitter](https://gitter.im/aspnet/Home)
