### ISSUE TITLE
ASP.NET Core SignalR does not support mapping users to connections

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/AspNetCore.Docs#19766]
According to this open [github issue](https://github.com/dotnet/aspnetcore/issues/6104) our recommendation to developers is to continue building your own map using [In-memory storage](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#in-memory-storage) or an [external storage medium](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/mapping-users-to-connections#azure-table-storage).

Opened this issue because this looks like this page is the right place, or is near the right section, of the ASP.NET Core docs that should include the current recommendation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@BrennanConroy  please review

**Comment by bradygaster** [comment]
As @BrennanConroy mentioned, there is no built-in (nor will there be) way of doing this in SignalR. This is something you need to do on your own. Closing, but I think the spirit of this issue (to have better documentation around ack'ing and user/group/connection management in your own app) - is captured by one of the items listed in #23357.
