### ISSUE TITLE
Update Prevent Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by agitkaplan** [dotnet/AspNetCore.Docs#19765]
I think if we not use `document.write()` in "JavaScript Encoding using Razor" examples it would be better. 
Some people might see these in examples and use in their production code without much change.
And these examples with `document.write()` have XSS flaws.

Examples with XSS containing inputs - see [JavaScript Encoding using Razor](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-3.1#javascript-encoding-using-razor)

```
@{
       var untrustedInput = "<\"123\">";
   }

   <div
       id="injectedData"
       data-untrustedinput="@untrustedInput" />

   <script>
     var injectedData = document.getElementById("injectedData");

     // All clients
     var clientSideUntrustedInputOldStyle =
         injectedData.getAttribute("data-untrustedinput");

     // HTML 5 clients only
     var clientSideUntrustedInputHtml5 =
         injectedData.dataset.untrustedinput;

     document.write(clientSideUntrustedInputOldStyle);
     document.write("<br />")
     document.write(clientSideUntrustedInputHtml5);
   </script>
```

[example1.txt](https://github.com/dotnet/AspNetCore.Docs/files/5164472/example1.txt)
[example2.txt](https://github.com/dotnet/AspNetCore.Docs/files/5164474/example2.txt)

If you think this is reasonable I suggest we use `createElement()` and `innerText` in examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart please review

**Comment by blowdart** [comment]
I think the point here is actually the document.write is safe because of the automatic encoding. Swithing to createElement and innerText moves away from demonstrating that.

**Comment by agitkaplan** [comment]
When set input value as `var untrustedInput = "<script>alert(1)</script>"`
Razor's auto encode converts this: `<div id="injectedData" data-untrustedinput="&lt;script&gt;alert(1)&lt;/script&gt;" />`
Browser's auto decode converts value to this: `"<script>alert(1)</script>"` again.
`document.write("<script>alert(1)</script>")` writes this to DOM.
And popup shows.
I think a re-review would be nice. And I know XSS is a tricky topic so if I am mistaken, I would be glad for a correction too.
