### ISSUE TITLE
DataProtection Configuration references the wrong libraries

### ISSUE THREAD

**Issue by markmcgookin** [dotnet/AspNetCore.Docs#19770]
# Issue description

The configuration document for DataProtection references the incorrect packages, which include issues requiring awkward workarounds.

I'll create a PR to change 

Microsoft.AspNetCore.DataProtection.AzureStorage
Microsoft.AspNetCore.DataProtection.AzureKeyVault

to 

Azure.Extensions.AspNetCore.DataProtection.Blobs
Azure.Extensions.AspNetCore.DataProtection.Keys

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x ] .NET Core - 3.1 
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @markmcgookin ... thanks for offering to help.

Cross-ref to the announcement discussion issue: https://github.com/dotnet/aspnetcore/issues/19570

@pakrym ... Do we have breaking change concerns WRT any dependencies in the 2.1/3.1 frameworks depending on the old packages, or can @markmcgookin just perform a find-'n-replace in the docs to update the packages and versions?

**Comment by markmcgookin** [comment]
There is a minor change in the configuration that I am including in the PR

**Comment by pakrym** [comment]
> @pakrym ... Do we have breaking change concerns WRT any dependencies in the 2.1/3.1 frameworks depending on the old packages, or can @markmcgookin just perform a find-'n-replace in the docs to update the packages and versions?

Not sure I understand the possible concern.

**Comment by guardrex** [comment]
> These are new packages that bring in a new version of the Azure SDK which includes breaking changes. The general usage patterns are the same as the existing packages, but some overloads and options may be different (in order to react to the changes to the underlying Azure SDK APIs).

Just making sure that if someone goes to use these new packages in a 2.x/3.x app that they won't hit these breaking changes (whatever they may be ... overloads, options, etc.) without us saying anything to them. Perhaps, a remark like that :point_up: is all we need **_if_** there is any potential concern about devs only changing the the packages and going straight into production with their updated apps.

The docs question boils down to: In spite of the new packages being supported for 2.x/3.x, should these new packages be versioned in the docs/doc samples for any reason?

**Comment by pakrym** [comment]
Thank you for the explanation @guardrex!

No, there are no concerns, for anyone 2.1 up. These packages target 2.1 of Extensions and only OOB BCL packages. They would cause some ASP.NET Core package updates for 2.0 customers but even that shouldn't be a problem, compat bar between 2.0 and 2.1 was pretty high.
