### ISSUE TITLE
Can I Unprotect in a different program?

### ISSUE THREAD

**Issue by MNF** [dotnet/AspNetCore.Docs#19776]
It is not clear, will unprotect work if the original protecter will be closed and a new protecter will be created in a different console application. 
Please modify sample to clarify it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23af4f99-387c-b2f5-3d5b-3d98cfac247c
* Version Independent ID: 0d95b7b7-5e46-5718-ca09-bdae43c86963
* Content: [Consumer APIs overview for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/overview?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/consumer-apis/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@MNF ... Yes ... as long as the apps share the key repository, the keys are maintained there (i.e., not deleted), and the keys aren't revoked/expired. You also have to set the same app name across apps and use the same DP stack across the apps (see [this section for more info](https://docs.microsoft.com/aspnet/core/security/data-protection/configuration/overview#setapplicationname)). You can use the file system, a service like Azure, or roll your own repository. For more info, see ...

* https://docs.microsoft.com/aspnet/core/security/data-protection/configuration/overview#setapplicationname
* https://docs.microsoft.com/aspnet/core/security/data-protection/implementation/key-storage-providers

The direct answer to your question is at the last sentence of the first paragraph at https://docs.microsoft.com/aspnet/core/security/data-protection/consumer-apis/dangerous-unprotect ...

> Keys are never removed from the key ring, so `IDataProtector.Unprotect` can always recover existing payloads as long as the keys are available and valid.
