### ISSUE TITLE
Need clarity on limitations for popup (window.open) based apps on Blazor Server

### ISSUE THREAD

**Issue by Code-DJ** [dotnet/AspNetCore.Docs#19779]
The documentation states "By default, there's no limit on the number of connections per user for a Blazor Server app.", is this true for Blazor only or browsers as well. I read somewhere that browsers allow max of 6 continuous connections (e.g. SignalR) to a single server. Does this apply to Blazor Server as well?

Want clarity on limitations for future Blazor Server enterprise apps that are popup-based (window.open). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff954815-0f8b-9f1b-9772-1657744b4f9e
* Version Independent ID: ed7d726d-41c6-73d8-d564-91530b4935c3
* Content: [Threat mitigation guidance for ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/server/threat-mitigation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/threat-mitigation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Code-DJ ... I'll place this up for triage. The engineers are busy at the moment with the upcoming RC1 release of ASP.NET Core. Within a couple of weeks, they'll be able to answer your question here.

**Comment by guardrex** [comment]
@javiercn and/or @SteveSandersonMS will need to remark on this one.

**Comment by SteveSandersonMS** [comment]
Blazor doesn't impose any per-user limits. If a browser chooses to impose some limits it may do so (and Blazor wouldn't control that), though I'm not personally aware of such limits.

**Comment by guardrex** [comment]
I'll close as answered given that we can't document anything specific beyond what the topic already states.
