### ISSUE TITLE
I found Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core's pagelist doesn't work for List 

### ISSUE THREAD

**Issue by BrandoZhangTest** [dotnet/AspNetCore.Docs#19777]
[So link](https://stackoverflow.com/questions/63727970/i-get-the-following-error-when-i-add-paging-iqueryable-doesnt-implement-iasync/)

I have created a `PaginatedList` class as this [article](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-3.1#add-paging-to-students-index) shows. I found if I pass List object into this `PaginatedList`, it will throw `The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.` error.

That means we couldn't use `List<T>.AsQueryable()` as parameter pass into `PaginatedList.CreateAsync` method.

I suggest we could provide some notice to tell other people who faces the same issue.

**Comment by guardrex** [comment]
@BrandoZhangTest ... It's best if you close this and re-open it using the **This page** feedback button at the bottom of the English-US topic. It will add metadata to your issue for tracking and ping the author of the topic automatically.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Rick-Anderson** [comment]
It's not intended to work with all providers.
