### ISSUE TITLE
Calling Dispose after AcceptWebSocketAsync()

### ISSUE THREAD

**Issue by Matiszak** [dotnet/AspNetCore.Docs#19788]
Hi,
I've been investigating high cpu usage and memory leak on WebSockets recently. It turned out that I was missing a `Dispose()` after accepting WebSocket.

Basically, before fix:
```
WebSocket webSocket = await context.WebSockets.AcceptWebSocketAsync();
... other code
```
After fix
```
using (WebSocket webSocket = await context.WebSockets.AcceptWebSocketAsync()) {
   ... other code
}
```

It turns out that the `Dispose()` fixes the issue in case the connection is abnormally closed without WebSockets close handshake. For normal closures, such leaks does not occur.

I think it should be mentioned in the documentation and in code samples/snippets that it should be disposed - right now it's not clear right away because the function call (AcceptWebSocketAsync) returns an object that receiver (my code) is supposed to call `Dispose` on. Also, current documentation somehow suggests that objects related to websocket connection are cleaned up after exiting pipeline (by saying that it should only be used before exiting pipeline/middleware) - at least that's the thought I had after reading and looking at the example without `Dispose`.

To justify putting `Dispose` in the documentation here are aspnet source codes that use `Dispose`:
https://github.com/dotnet/aspnetcore/blob/4e44025a52e4b73aa17e09a8041b0e166e0c5ce0/src/Middleware/WebSockets/test/ConformanceTests/AutobahnTestApp/Startup.cs#L25
https://github.com/dotnet/aspnetcore/blob/1867750ec997911a64a0a02c0eaf82cc8a2ba4ae/src/SignalR/common/Http.Connections/src/Internal/Transports/WebSocketsServerTransport.cs#L54

Note: I didn't have resources at the moment to test it but I think this fix (https://github.com/dotnet/corefx/commit/c5688531605218f58b30b377f48e74de4d6c83d3) might cause the leaks to never be there in the first place but it is not included in runtime version I'm working on (if I see correctly it's only included in release/3.0 and later). Nevertheless `Dispose` behaviour of object returned from `AcceptWebSocketAsync` should be mentioned in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bradygaster @mkArtakMSFT who's the right person to review this issue?

**Comment by bradygaster** [comment]
adding @BrennanConroy to see if he has any insight into this one.
