### ISSUE TITLE
Platform Configuration

### ISSUE THREAD

**Issue by jmacCity** [dotnet/AspNetCore.Docs#19786]
Hello, Item 4 of the **Register a Client App** [section](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1#register-a-client-app) specifies that the app authentication platform should be "Web". 

However, the platform config in Azure warns that "This app has implicit grant settings enabled. If you are using any of these URIs in a SPA with MSAL.js 2.0, you should migrate URIs." Is that an issue?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jmacCity ... Yes, implicit grant is fine for this scenario with the current Identity v1.0 packages and current MSAL version in use. It will change to the authorization code flow for the upcoming .NET 5 release later this year when Blazor + packages move to using Microsoft Identity Platform 2.0. The preview docs for the new packages in preview will be put up (by me) right after RC1 releases within a few weeks. You can track that work on https://github.com/dotnet/AspNetCore.Docs/issues/19503. I think the engineering work is tracked by https://github.com/dotnet/aspnetcore/issues/23821, but you might need to dig around a little bit over there for all of the updates.
