### ISSUE TITLE
The (ambiguous) app's responsibility

### ISSUE THREAD

**Issue by em-jones** [dotnet/AspNetCore.Docs#19784]
In the paragraph there's ambiguity as it relates to the notion of "the app"

> The blazor.server.js script establishes the client connection. It's the app's responsibility to persist and restore app state as required (for example, in the event of a lost network connection). The blazor.server.js script is served from an embedded resource in the ASP.NET Core shared framework.

Would love to know... is it the server-side app's responsibility, or is the `blazor.server.js` script delivering an application that manages app state?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @em-jones ... I'll do some work on the text this week to clarify.

The `blazor.server.js` script doesn't deliver the app ... it establishes the client connection from the client-side. If the connection is lost, it's the client-side app that must deal with it. By default, a client-side app will attempt to re-establish the connection. If it fails on its own, it offers the user a button to retry. The behaviors are customizable (explained in another topic). For example, you can register a callback for a lost connection and then try to reconnect in your own code with your own logic. Those aspects are explained in the *Fundamentals* > *Additional scenarios* topic.

I'll improve the language in the section of this topic. Thanks for writing in about it.

**Comment by em-jones** [comment]
I super appreciate you taking your time to respond and look into this. Especially considering this was on a Saturday. In case there was any doubt, anybody who didn't already think the team behind blazor really cared about this project would likely be really hard to impress. Thanks for your hard work!
