### ISSUE TITLE
Error when adding Index.cshtml

### ISSUE THREAD

**Issue by PSCRIMS** [dotnet/AspNetCore.Docs#19791]
[When following tutorial, encountered error InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/GetQuote/Index.cshtml
/Views/Shared/Index.cshtml]

Environment dotnet 3.1.7 sdk 3.1.401. File Index.cshtml was created in the /Views/Shared/ folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by PSCRIMS** [comment]
Found my  mistake
