### ISSUE TITLE
myuser should be myservername

### ISSUE THREAD

**Issue by mdurscher-logisoft** [dotnet/AspNetCore.Docs#19790]
In Section [Windows environment configuration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#windows-environment-configuration) the execute example should be **`setspn -S HTTP/myservername.mydomain.com myservername`** and not `setspn -S HTTP/myservername.mydomain.com myuser` (myservername instead of myuser).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shirhatti one minute review

**Comment by JunTaoLuo** [comment]
I don't think so, the user name doesn't have to be the same as the server name, even if that is usually the case.
