### ISSUE TITLE
Folder name "Models" should not be localized

### ISSUE THREAD

**Issue by JasonCard** [dotnet/AspNetCore.Docs#19802]
This Issue will address: [https://github.com/dotnet/AspNetCore.Docs.pt-br/issues/142#issuecomment-687851066](https://github.com/dotnet/AspNetCore.Docs.pt-br/issues/142#issuecomment-687851066)  

This article contains folder name "Models" that's used in code sample and should not be localized. Please help to add this term to the metadata for no-loc custom syntax like below:
no-loc: ["ASP.NET Core Identity", cookie, Cookie, Blazor, "Blazor Server", "Blazor WebAssembly", "Identity", "Let's Encrypt", Razor, SignalR, Models]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  can you append `Models` to the `no-loc: ["` metadata?

Edit in browser should be fine.

**Comment by serpent5** [comment]
@Rick-Anderson Done.
