### ISSUE TITLE
5.0 Update: Intro to MVC tutorial series

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19801]
Update 10 tutorial series and app samples to .NET 5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e3baf6-6cba-aee0-9a8d-1e1fced2b690
* Version Independent ID: 74b76258-36a3-17de-6648-292da0a9e400
* Content: [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@Rick-Anderson,
I assume you want includes pulled in where possible much like the Razor Pages series.

..but just to double check before I do this across all tutorials in this mvc series: 

Pull in includes where its purpose was to eliminate repeated text between IDE tabs?
For example:    [!INCLUDE [explains scaffold generated params](~/includes/mvc-intro/model4.md)]  in the adding-model.md

**Comment by Rick-Anderson** [comment]
Be smart about it. If it make sense, keep it. In most cases I created includes so I could have 3 versions of the tutorial. Now that we have one version and 3 tabs, you can eliminate alot of the includes.

**Comment by wadepickett** [comment]
Removing my assignment per Mark.

**Comment by Rick-Anderson** [comment]
We'll finish this in 6.0
