### ISSUE TITLE
Add Microsoft.Identity.Web migration guide to 3.1->5.0 documentation

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/AspNetCore.Docs#19810]
# Issue description

In addition to updating existing docs for AAD in https://github.com/dotnet/AspNetCore.Docs/issues/19809, we also need to include a migration guide for users going from 3.1 to 5.0. The following information would be helpful in constructing the migration doc:
- https://github.com/AzureAD/microsoft-identity-web/wiki/Web-Apps#with-azure-ad
- https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#why-to-use-microsoftidentityweb-in-web-apis

Looking at our docs at https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-3.1&tabs=visual-studio, it seems like the AAD migration doc belongs in the list of breaking changes.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core (.NET 5 replaces both)
- [x] .NET Framework (.NET 5 replaces both)
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by JunTaoLuo** [comment]
cc @Tratcher  @jmprieur

**Comment by mkArtakMSFT** [comment]
@JunTaoLuo assigning to you to handle as necessary.

**Comment by JunTaoLuo** [comment]
I think @jmprieur would be the best to provide these docs. I think most of the information is already available at https://github.com/AzureAD/microsoft-identity-web/wiki and https://developer.microsoft.com/en-us/microsoft-365/blogs/microsoft-identity-web-is-now-generally-available/#:~:text=We're%20excited%20to%20announce,Web%20is%20now%20generally%20available.&text=Web%20brings%20a%20renewed%2C%20simplified,Graph%20or%20other%20web%20APIs. There's potentially work in synthesizing this information into aspnetcore relevant docs.

**Comment by jmprieur** [comment]
Yes: the following wiki pages explain how to migrate:
- https://github.com/AzureAD/microsoft-identity-web/wiki/web-apps (for web apps)
- https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis for web apis

We also have the ASP.NET Core web app and web API tutorials which explain the migration:
- https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC/1-1-MyOrg#option-2-create-the-sample-from-the-command-line
- https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/master/1.%20Desktop%20app%20calls%20Web%20API#how-was-the-code-created
