### ISSUE TITLE
Discuss performance issues (or lack therof)

### ISSUE THREAD

**Issue by yringler** [dotnet/AspNetCore.Docs#19811]
A year or so ago, we released a new API based on aspnetcore, which was a year in the making. It is such a relief to be using a proper, modern, well thought out solution!
One small point of contention which keeps on being brought up is the question of performance and DI. Does having many dependencies increase CPU usage? RAM? Etc. How much is too much?
Note that I don't think we have noticed any abnormal performance issues, but it would make life easier for me if there would be some sort of (at least cursory) discussion in the docs about performance, and recommendations vis-à-vis performance, and perhaps some real world numbers (eg "The .net documenation site injects 700 dependencies")
For some context, we inject roughly 30 items, just about all of them using scoped lifetime.
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's the trade off between scoped and singleton. Singletons are only instantiated once but hand on to memory.

It's impossible to come up with real numbers because there is  no standard app, standard services, and standard usage patterns. It sounds like it's not a problem for you.
