### ISSUE TITLE
5.0 Update routing comments about default catch-all behavior

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#19817]
We have a disclaimer indicating an existing issue with regards to routing in 3.1 on our docs. (https://github.com/aspnet/aspnetcore/issues/18677). We made this behavior the default in 5.0, so we should update the docs accordingly.

@Rick-Anderson  edit to add meta-data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by Rick-Anderson** [comment]
@javiercn  next time,  Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
