### ISSUE TITLE
Localization is not up to date for target framework 3.1

### ISSUE THREAD

**Issue by Rozinek** [dotnet/AspNetCore.Docs#19826]
Hello Microsoft,

the article is obsolete for target framework .NET Core 3.1. In a section "Using one resource string for multiple classes" should be at least line or rewritten for utilizing endpoints.

1. AddMvc(options => options.EnableEndpointRouting = false)
2. services.AddControllersWithViews();
    app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });

The example in Github is not running after cloning repository, unzip and starting the project. They are needed additionaly steps mentioned previously.

We offer also our help to Microsoft if is a capacity problem.

Best Regards
Ondrej Rozinek
www.rozinet.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco should the code at [Using one resource string for multiple classes](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1#using-one-resource-string-for-multiple-classes) be:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews()
        .AddDataAnnotationsLocalization(options => {
            options.DataAnnotationLocalizerProvider = (type, factory) =>
                factory.Create(typeof(SharedResource));
        });
}
```

**Comment by hishamco** [comment]
@Rozinek the steps you are added for configuring the MVC and end points

@Rick-Anderson that code is right AFAIK

Let me check the provided sample in 3.1 and come back to you

**Comment by hishamco** [comment]
Just added End-Points and make sure that the sample works fine

Thanks @Rozinek
