### ISSUE TITLE
I had to do this:  Install-Package Microsoft.EntityFrameworkCore.InMemory

### ISSUE THREAD

**Issue by pekkamanninen** [dotnet/AspNetCore.Docs#19827]
[Kirjoita palautteesi tähän]

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/fi-fi/aspnet/core/tutorials/first-web-api?tabs=visual-studio&view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pekkamanninen ... It's the fifth bullet point at ...

https://docs.microsoft.com/aspnet/core/tutorials/first-web-api#add-nuget-packages

We've had this issue come in a few times. I think a change to how that appears might lick this. A short bit right before the steps that lists both packages might work 🤞🍀 ... something like ...

> \#\#\# Add NuGet packages
>
> Add the following NuGet packages to the app:
>
> \* \[Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer)
> \* \[Microsoft.EntityFrameworkCore.InMemory](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.InMemory)
>
> Packages can be added to the app with the \*NuGet Package Manager\* in Visual Studio:
>
> \* From the \*\*Tools\*\* menu, select \*\*NuGet Package Manager\*\* > \*\*Manage NuGet Packages for Solution\*\*.
> \* Select the \*\*Browse\*\* tab and then enter the package name in the search box.
> \* Select package from the search results in the left pane.
> \* Select the \*\*Project\*\* check box in the right pane and then select \*\*Install\*\*.
