### ISSUE TITLE
IsDevelopment doesn't exist in IWebHostEnvironment

### ISSUE THREAD

**Issue by cpn-paladino** [dotnet/AspNetCore.Docs#19829]
[Enter feedback here]

According to https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iwebhostenvironment?view=aspnetcore-3.1

the method "IsDevelopment" doesn't exist, please fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there.
