### ISSUE TITLE
Code-first gRPC with .NET

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#19825]
All our gRPC documentation discusses the .proto file approach using grpc-dotnet. MS generally recommends the .proto file approach because it is inline with the rest of the gRPC ecosystem and it is an easier path to cross-platform apps.

protobuf-net.Grpc builds on top of grpc-dotnet, and offers a code-first alternative. It is familiar to people who have WCF apps which are also code-first. protobuf-net.Grpc is a good choice when making .NET apps that talk to each other. No .proto file is needed.

I think we should have a docs page that:
* Shows how to do code-first gRPC using protobuf-net.Grpc
* Discusses the pros and cons
* Links to protobuf-net.Grpc home page for more information
* Have disclaimer that it is a third-party solution

@mgravell @shirhatti

**Comment by JamesNK** [comment]
We should also mention protobuf-net.Grpc on this page - https://docs.microsoft.com/aspnet/core/grpc/why-migrate-wcf-to-dotnet-grpc

**Comment by mgravell** [comment]
Happy to help here if I can be of use.
