### ISSUE TITLE
Tutorial: Get started with Razor Pages in ASP.NET Core

### ISSUE THREAD

**Issue by bobbryant** [dotnet/AspNetCore.Docs#19820]
In Part 2, add a model to a Razor Pages app in ASP.NET Core

In the step “Complete the Add Razor Pages using Entity Framework (CRUD) dialog:”
The Data context class text shown in the tutorial:  RazorPagesMovie.Models.RazorPagesMovieContext.
Is showing up as  RazorPagesMovie.Data.RazorPagesMovieContext  in VS version 16.7.3 using ASP.NET Core 3.1  
Note the tutorial used "ASP.NET Core 2.2"

I was able to complete part 2 but I had to try more than once.  (Core 2.2, Core 3.1, Update VS etc...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Why aren't you following the 3.1 version?

**Comment by bobbryant** [comment]
I searched for “How to create web application in visual studio 2019” and chose “Create an ASP.NET Core web app in C# - Visual Studio ...” (https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2019) and followed the links to the next step.

 

Where is the tutorial for the 3.1 version?

 

Bob Bryant

Email address:  <mailto:bob.bryant@pobox.com> bob.bryant@pobox.com

Cell Phone:       602.430.2024

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/92807419-9291ff00-f356-11ea-9208-5d5e86ad54dd.png)
