### ISSUE TITLE
Docs on modelexpression

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#19838]
I would like to request some Examples on using ModelExpression.

I would like to make a custom version of asp-for
Is there a documentation on how to use modelexpression in custom taghelpers?

My use case is dynamic property member access. 
```
<input custom-for="@Model.Input" custom-for-property-name="@("FirstName")" />

```

I could do this with dictionaries but it would be fun to be able to do this also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
