### ISSUE TITLE
Visual Studio Code Windows command needs quotes around the '-outDir "Pages\Movies"' tag 

### ISSUE THREAD

**Issue by DutchBoyd** [dotnet/AspNetCore.Docs#19834]
Following along with the RazorPages tutorial and running the codegenerator, I got stuck for a bit after running this command:

dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries

The next step was to run the app and check the localhost:port/movies page, and I got not found error. The problem was solved when I put quotes around the outDir tag like so:

dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir "Pages\Movies" --referenceScriptLibraries

**Comment by guardrex** [comment]
@DutchBoyd ... For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Rick-Anderson** [comment]
@DutchBoyd  not sure what you did wrong but that doesn't need to be quoted.
