### ISSUE TITLE
Page should mention installing "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"

### ISSUE THREAD

**Issue by cbgrey** [dotnet/AspNetCore.Docs#19839]
In the section for using different databases for dev vs prod....UseDatabaseErrorPage does not work unless package "Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" is installed. 

Page should mention that this package needs to be installed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Need to update https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code#add-nuget-packages-and-ef-tools to include `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore`
