### ISSUE TITLE
Why does AuthorizeAsync not work with AuthorizeView?

### ISSUE THREAD

**Issue by philmiller84** [dotnet/AspNetCore.Docs#19842]
AuthorizeAsync should have the ability to set Authorized or NotAuthorized, so that the AuthorizeView tag could be used. Otherwise, resource-based authorization is required to use AuthorizeAsync with a separate if-check. 

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aad527d-62e1-a5de-af9e-4bba8e747b76
* Version Independent ID: 8e447a28-81e7-d80e-a447-08413e88cf98
* Content: [View-based authorization in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/views?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/views.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/views.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
