### ISSUE TITLE
How to debug RCL static files

### ISSUE THREAD

**Issue by yezi34880** [dotnet/AspNetCore.Docs#19862]
Now I split the Areas to another project (Razor Class Library), Include controller views and other static files like js css image and so on.
and I load the Assembly in main project dynamic
At first the js and css can't load, until to the load then as EmbeddedResource
now it is used in main project as well
but there is another problem do you have
when i debug , the modify can't show real time,
I use the AddRazorRuntimeCompilation ,it resolved the razor page ( .cshtml ) but not the js and css files,
I only can close debug and rebuild the module and restart , is's very complex
do you have a easy way to debug RCL

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not something we plan to document. We recommend asking the questions you've raised here in StackOverflow to find answers.
