### ISSUE TITLE
Update Intro to SingnalR to .net core 3.1

### ISSUE THREAD

**Issue by patware** [dotnet/AspNetCore.Docs#19869]
.net core 3.0 is end of life, please update the tutorial for 3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@patware  it looks like it has been
![image](https://user-images.githubusercontent.com/3605364/93544450-d312ef00-f8f9-11ea-8eb1-048c59fbb624.png)

What in the tutorial is out of date?

**Comment by patware** [comment]
Hi,

Yes, the image is fine, but the text says 3.0 SDK in three places.

![image](https://user-images.githubusercontent.com/1571612/93545777-4551f680-f92f-11ea-8d74-e4bda8b27e72.png)
![image](https://user-images.githubusercontent.com/1571612/93545793-526ee580-f92f-11ea-89ba-112bf5fa0d2e.png)
![image](https://user-images.githubusercontent.com/1571612/93545796-5864c680-f92f-11ea-8fcc-a0c5ab166bdd.png)

Pat
