### ISSUE TITLE
[RC1] Blazor JavaScript isolation and object references

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19873]
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-javascript-isolation-and-object-references

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mrlife** [comment]
@guardrex Hi, I see where this was merged about 4 weeks ago, and the date on this doc is 10/2/2020, though I don't see anything about JavaScript Isolation on the live docs page. Is the information in the merged files ok to use as a reference?

**Comment by guardrex** [comment]
Flip the document version selector (upper left hand corner) to the 5.0 preview version of the doc to see the content.

**Comment by mrlife** [comment]
Yes, thank you. Sorry, I realized that after and deleted my comment. Sorry to bother you about this. If you delete your comment, I will go ahead and delete this one too. Thanks for getting back to me on it anyhow.

**Comment by GeorgeS2019** [comment]
@guardrex  Can we have [Blazor JS Isolation examples](https://github.com/simutaroman/BlazorNet5JsInterOp/issues/1#issuecomment-724119614) using [different module format](https://www.sitepoint.com/understanding-module-exports-exports-node-js/)?

- The Asynchronous Module Definition (**AMD**) format
- The CommonJS (**CJS**) format
- The ES Module (**ESM**) format.
- The System.register format 
- The Universal Module Definition (**UMD**) format
