### ISSUE TITLE
Add examples for multi render fragment components

### ISSUE THREAD

**Issue by campbel** [dotnet/AspNetCore.Docs#19879]
It would be helpful to include documentation for creating components of the form:

```
<List>
  <Item @onclick="action1"></Item>
  <Item @onclick="action2"></Item>
  <Item @onclick="action3"></Item>
</List>
```
The docs currently only show examples where you pass a list of items to the parent component instead of providing the fragments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698a8824-7a38-70d6-c041-0dca4c040217
* Version Independent ID: ae663e33-6a08-0b24-aa19-3fc3c9edccfc
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@campbel ... I'm going to close this in favor of https://github.com/dotnet/AspNetCore.Docs/issues/19871 for the latest version of the `Virtualize` component, which accepts an item template. I just put a PR up based on Dan Roth's blog post coverage at https://github.com/dotnet/AspNetCore.Docs/pull/19898. The component received updates for 5.0, so you'd need to be on 5.0 RC1 or later to use it as the topic suggests.
