### ISSUE TITLE
ConsumeScopedServiceHostedService Overrides StopAsync incorrectly

### ISSUE THREAD

**Issue by redwyre** [dotnet/AspNetCore.Docs#19889]
It seems like the example for ConsumeScopedServiceHostedService wont shutdown correctly as it overrides StopAsync without calling the base.

The QueuedHostedService seems to do this correctly

(btw, great examples, extremely helpful page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@huan086 please review

**Comment by huan086** [comment]
Most of the examples are missing the call to base.StopAsync() 🤦‍♀️. Could you do a pull request to fix them?

**Comment by serpent5** [comment]
I can pick this one up if needed. I think it's only `ConsumeScopedServiceHostedService` that needs the fix, because the others implement `IHostedService` directly.

**Comment by Rick-Anderson** [comment]
@serpent5  thanks!
