### ISSUE TITLE
[RC1] Update Blazor-EF Core sample app to .NET 5 RC1

### ISSUE THREAD

**Issue by justSteve** [dotnet/AspNetCore.Docs#19883]
[EDIT by guardrex to add the metadata]

# Issue description

In this repo's path for app samples that indicates .net 5 generation (AspNetCore.Docs/aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample) the included project has 3.1 as the target framework.

Even if there are no breaking changes, shouldn't we be starting with code hitting 5.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Hello @justSteve ... Please use the **This page** feedback form at the bottom of any topic to open a new issue ...

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

I'll add the metadata manually, so no worries on that for this issue.

> Even if there are no breaking changes, shouldn't we be starting with code hitting 5.x?

.NET 5 RC1 is supported, so you are welcome to use .NET 5 now if you wish.

https://dotnet.microsoft.com/download/dotnet/5.0
