### ISSUE TITLE
Drop-Database called immediately prior to "View the DB section"; no instructions to run app to rebuild DB

### ISSUE THREAD

**Issue by timkatje** [dotnet/AspNetCore.Docs#19899]
[Enter feedback here]
At the very end of the "Add code to initialize the DB with test data" section, we are told to stop the app if running, and run the `Drop-Database` command in the PMC.

The start of the next section, "View the DB" provides a quick overview of how DBs are named in localdb, and describes how we should go about viewing the contents of the database.

However, at no point did the instructions state that the webapp needs to be rebuilt and run for the database to be recreated in order to view its details.  If you follow these instructions to the letter, there is no longer any database to review.

Recommend inserting a statement telling the user to rebuild and run their code at the very start of the "View the DB" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Also fix namespace as the bug has been fixed

Note: The preceding code uses Models for the namespace (namespace ContosoUniversity.Models) rather than Data. Models is consistent with the scaffolder-generated code. For more information, see this GitHub scaffolding issue.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
I think most folks know to do that, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
