### ISSUE TITLE
File signature check fails when there is white space at the starting of the file's content

### ISSUE THREAD

**Issue by vizgtcoc** [dotnet/AspNetCore.Docs#19896]
# Issue description
In /aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Utilities/FileHelpers.cs,
in IsValidFileExtensionAndSignature(),
in case of adding signature bytes for pdf as below,
`{ ".pdf",new List<byte[]>
                {
                    new byte[] {  0x25, 0x50, 0x44, 0x46 }
                }
            }`
It works fine if the contents in the uploaded file start with 

> %PDF

but fail when the content starts with a few white spaces

> (white space)
> (white space)
> %PDF

**Comment by guardrex** [comment]
Hello @vizgtcoc ...

FYI ... Please use the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

No worries ... I'll add the metadata manually to the issue.

WRT your question about the file signature ...

What's in the topic and the sample app amount to merely *sample code*. You'll likely need to modify sample code for specific use cases and edge cases. If you're encountering white space in the file signature, you could create a file signature check that trims/ignores white space.
