### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by phil123456** [dotnet/AspNetCore.Docs#19903]
[Enter feedback here]

- AuthorizePageHandlerAttribute cannot be found

- the following line does not compile

        var policy = await AuthorizationPolicy.CombineAsync(policyProvider, new[] { attribute });

        cannot convert from '?[]' to 'System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Authorization.IAuthorizeData>'	

- [AuthorizePageHandler] cannont be found

here is the controller I  use with your tutorial

```
    [Authorize]
    [Route("api/[controller]")]
    [TypeFilter(typeof(AuthorizeIndexPageHandlerFilter))]
    [ApiController]
    public class UsersController : ControllerBase
    {
        private readonly SomeDBContext context;
        private readonly Settings settings;

        public UsersController(SomeDBContext context, IOptions<Settings> settings)
        {
            this.context = context;
            this.settings = settings.Value;
        }

        // POST: api/Users
        [AllowAnonymous]
        [AuthorizePageHandler]        
        [HttpPost("authenticate")]
        public async Task<ActionResult<Authenticatification>> PostLogin(Authenticate authenticate)
        {
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Missing an include?
https://github.com/pranavkm/PageHandlerAuth/blob/0be16c56ec2a2a82d3bc5137213a73938117df84/Pages/Index.cshtml.cs#L16
