### ISSUE TITLE
Documentation does not reflect how the rotation of certificate happes in this case

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#19901]
[EDIT by guardrex to add the metadata]

---
**Issue moved from MicrosoftDocs/feedback#3098**
- Please respond to @khandelwalbrijesh.

---

_From @khandelwalbrijesh on Tuesday, September 8, 2020 12:25:44 PM_

**Is your feature request related to a problem? Please describe.**
I am following the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1) which shows how to do https certificate binding in asp.net app inside docker. We are using the same approach in our production containers but It is not explained here what happens when certificate is rotated. What is the best way to configure the rotation here? Will it work by simply updating the certificate at the location ASPNETCORE_Kestrel__Certificates__Default__Path. Or there is something else needs to be done here. 
Internally, does this way of binding certificate uses ServerCertificateSelector while doing the binding so, the certificate can be updated after the owner of the app updates the certificate at the ASPNETCORE_Kestrel__Certificates__Default__Path location?

**Describe the solution you'd like**
Need some guidance on the best way to configure the autorotation here

**Describe alternatives you've considered**
We are considering to bind the certificate from the code and use Server Selector while doing so, the certificate will get updated without crashing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf7806c-d9e4-1811-3308-b5efb6f159f0
* Version Independent ID: 2117dfa1-9e6d-2bc2-2348-e792f3c81806
* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-compose-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ravipal
* Microsoft Alias: **ravipal**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3098**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, September 8, 2020 12:25:45 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
