### ISSUE TITLE
What is the scope of AddNewtonsoftJson()?

### ISSUE THREAD

**Issue by k3davis** [dotnet/AspNetCore.Docs#19912]
When you call AddNewtonsoftJson on a particular method:

```csharp
services.AddRazorPages().AddNewtonsoftJson();
```

...is the scope limited to RazorPages (in this example), or does it affect the entire pipeline, equivalent (as far as JSON.NET is concerned) to calling

```csharp
services.AddMvc().AddNewtonsoftJson();
```

I ask because some third-party libraries use JSON.NET still but my project doesn't (in this case Coravel Pro, which also uses RazorPages which my application also doesn't), and I'm concerned about potential conflicts.

Hopefully this is an appropriate place to ask this question; if not please feel free to redirect me. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
``* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher 30 second question

**Comment by Tratcher** [comment]
@pranavkm

**Comment by pranavkm** [comment]
Razor Pages and MVC have the same underpinnings. If you reference a library that calls `AddNewtonsoftJson` on your behalf, it will also affect controllers (and other MVC features) in your app.

Within MVC, it changes the following things to use Json.Net: 

* input and output formatting (reading or writing) of JSON an ActionResult
* JsonResult
* IJsonHelper
* adds support for JsonPatch
* the serialization format used internally by ITempDataDictionary

**Comment by Rick-Anderson** [comment]
cc @serpent5  if you're interested in updating this doc.

**Comment by k3davis** [comment]
Thank you, that answered my question precisely. I would close this but I'll defer to @serpent5 in case he wants to clarify this in the doc. If not, feel free to close. Thanks again.

**Comment by serpent5** [comment]
I'm happy to do something here. How about adding a "for more information" link in this migration topic to the [Add Newtonsoft.Json-based JSON format support](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1#add-newtonsoftjson-based-json-format-support) section in "Format response data in ASP.NET Core Web API" and including some of Pranav's information in that section?

**Comment by Rick-Anderson** [comment]
@serpent5  that would be great.
