### ISSUE TITLE
Update MessagePack Hub Protocol in SignalR for ASP.NET Core to state that MessagePack 2.x is incompatible with ASP.NET Core in the Section that Explains How to set Security to UntrustedData

### ISSUE THREAD

**Issue by dcs3spp** [dotnet/AspNetCore.Docs#19937]
Hi,

I am new user with using MessagePack Hub Protocol in SignalR for ASP.NET Core, Blazor Server.

At the time of writing the latest version of MessagePack is v2.1.194. The page refers to manually installing MessagePack v1.9.3 and setting MessagePackSecurity.Active property to ```MessagePackSecurity.UntrustedData;``` in ```Program Main```. So....I tried installing v2.x thinking it was a later version and thus, more secure.......

However, I have read [elsewhere](https://github.com/dotnet/aspnetcore/issues/18716#fixing-transitive-dependencies), that MessagePack v2.x is incomaptible with ASP.NET Core. 

Could further information be added to explain that although there is a later version of MessagePack (2.x), it is incompatible with ASP.NET Core. It has to be MessagePack 1.9.3 that is manually installed.

Also, what namespace should added be added to allow ```AddMessagePackProtocol``` to be recognised on the [.NET SignalR Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-3.1#net-client-1)  I have added package ```Microsoft.AspNetCore.SignalR.Protocols.MessagePack```  and tried referencing ```Microsoft.AspNetCore.SignalR.Protocols.MessagePack``` on Blazor server page but it is not recognising ```AddMessagePackProtocol``` on the ```HubConnectionBuilder```.

Also tried  referencing```@using Microsoft.AspNetCore.SignalR.Protocol;``` to a blazor server page and ```AddMessagePackProtocol``` is still unrecognised on the ```HubConnectionBuilder``` of the .NET client.

Finally, after 1hr 15mins due to lack of experience on my part and lack of information included on the page, I resorted to looking at the [source code](https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/common/Protocols.MessagePack/src/MessagePackProtocolDependencyInjectionExtensions.cs)

Included ```@using Microsoft.Extensions.DependencyInjection;``` and finally managed successful compilation.

If such information had been initially included in the source code snippet of the page to start with, this would have saved time for new users like myself who are learning the technology!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Closed via https://github.com/dotnet/AspNetCore.Docs/pull/19980
