### ISSUE TITLE
EF Best practices review

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#19931]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&branch=pr-en-us-19922&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JeremyLikness  let me know when you'll be able to review  [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://review.docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&branch=pr-en-us-19922&tabs=visual-studio) and find places to add new EF features and best practices.

**Comment by JeremyLikness** [comment]
@Rick-Anderson Soon. I've looked at the tutorial and just want to make sure new features make sense to use. After release next week should be able to tackle this fully.
