### ISSUE TITLE
Remove or explain note in debugging section

### ISSUE THREAD

**Issue by Postlagerkarte** [dotnet/AspNetCore.Docs#19933]
![image](https://user-images.githubusercontent.com/8482283/93634371-c9b87e00-f9f0-11ea-81fb-1f12a3cba441.png)

What is the point of the the Note?

The section is about "Debugging an Application" isn't it obvious that "Start without Debugging" can not be used if you whish to debug the application? Or am I missing something here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-US/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Postlagerkarte ... It's more of a *side note* ... an FYI type of note just here to provide some info in passing.
