### ISSUE TITLE
Microsoft.AspNetCore.WebUtilities documentation indicates no support in ASP.NET Core 5.0 Preview

### ISSUE THREAD

**Issue by rollandjb** [dotnet/AspNetCore.Docs#19936]
`Microsoft.AspNetCore.WebUtilities.QueryHelpers` is used in an example to parse query parameters, but the [documentation for `QueryHelpers`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.queryhelpers?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-5.0) reports no support in ASP.NET Core 5.0 Preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rollandjb ... API docs aren't updated until release. `QueryHelpers.ParseQuery` is available in RC1 and will be there when 5.0 ships ...

https://github.com/dotnet/aspnetcore/blob/release/5.0-rc1/src/Http/WebUtilities/src/QueryHelpers.cs#L155

**Comment by rollandjb** [comment]
Thank you.
