### ISSUE TITLE
xUnit over NUnit within Asp.NET Core Doc

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#19939]
xUnit is chosen in this page, in fact, the whole dcoment, over NUnit.

What is the reason for choosing xUnit over NUnit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
It's what the product teams use to test the product and when Core was first being developed it was the only tool that was built to work on and with Core. It also has certain technical advantages over NUnit, like better isolation since every test runs in a new instance of its class, but these were secondary considerations.

**Comment by PingPongSet** [comment]
From this below NUnit predates xUnit?
https://stackoverflow.com/questions/9769047/nunit-vs-xunit

**Comment by ardalis** [comment]
Yes, NUnit is older.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

Thanks @ardalis
