### ISSUE TITLE
Suggested steps for Brotli compression do not work

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#19938]
The #compression section of the page says to use `decode.min.js` from here https://github.com/google/brotli/tree/master/js

But when I follow those steps I see the following error
```
	Uncaught (in promise) TypeError: BrotliDecode is not a function
```

On the following line in index.html
```
	const decompressedResponseArray = BrotliDecode(originalResponseArray);
```

Using decode.js instead works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#compression)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrpmorris ... I agree ... I **_can_** repro that.

They haven't changed the script (and the last time they did, they changed both versions simultaneously on https://github.com/google/brotli/pull/749 ... April 2019). I feel that I must have tested with the unminifed version, felt good about it, and then just blindly assumed the minified version would work on https://github.com/dotnet/AspNetCore.Docs/pull/19335. I think (*guessing*) that @captainsafia felt the same.

**_However_** if you go all the way back to @pranavkm's original content for this where the minified version **_was_** used, the name of the file was different ...

https://github.com/dotnet/AspNetCore.Docs/pull/18697/commits/851a3571611aea775ef942cdbd7356cf01c9dd42#diff-9d063de26462c89fb0345a4954096907R41

... which implies that your, @pranavkm, own compression of the script was in use (June 2020). Google's compressed version was there, but you didn't use it.

It's easy enough to just change the script and add a NOTE, but I think we'll need to ask @pranavkm and @captainsafia about possibly moving this to the product unit repo for further investigation/resolution. Even if we change the script and add a NOTE that says 'use the unminified version,' some devs will read past the NOTE and some will ignore it and try to use the minified version anyway. It would be nice to get to the bottom of this and have the example startup code work with both the unminified and minified versions of the Google scripts.

**Comment by mrpmorris** [comment]
It's a bug in the BrotliDecode lib.

https://github.com/google/brotli/issues/844#issuecomment-696324652

**Comment by guardrex** [comment]
Thanks @mrpmorris ... I'll keep an :eye: on the resolution there.

**Comment by captainsafia** [comment]
>  I think (guessing) that @captainsafia felt the same.

Yep, didn't assume there would be an issue with that change.

> but I think we'll need to ask @pranavkm and @captainsafia about possibly moving this to the product unit repo for further investigation/resolution.

Considering the release timeline, there's nothing we can do in the product to address this.

Regardless, the issue seems to be in the BrotliJS library itself. Unfortunately, it doesn't look like Google provides older versions of this package. Perhaps we can point users to the [npm package](https://www.npmjs.com/package/brotli) instead. Also, there's a chance someone might respond to @mrpmorris's thread above with a fix.

**Comment by guardrex** [comment]
I probably should temporarily call it out with a NOTE and show in the example using the unminified script or the npm package. I'll open a follow-up issue and place it on hold on the Blazor.Docs project so that I don't forget to keep tabs on it.
