### ISSUE TITLE
How to access real DataBase in unit testing?

### ISSUE THREAD

**Issue by nexawo** [dotnet/AspNetCore.Docs#19946]
I want to get data from my actual database in unit testing. I have a table named person and I have data in that table. Now, I want to get data from that table in unit testing. Below is the code which I am using to fetch data from the DB.

**public class PersonAppService_Tests: AppTestBase
{
private readonly IRepository<Person> _PersonRepositroy;
private readonly IUnitOfWorkManager _unitOfWorkManager;

public PersonAppService_Tests()
        {
            
            _PersonRepositroy = Resolve<IRepository<Person>>();
            _unitOfWorkManager = Resolve<IUnitOfWorkManager>();

        }
public async Task<List<PersonListDto>> GetAll()
        {
           List<PersonListDto> a = new List<PersonListDto>();
            using (var uow = _unitOfWorkManager.Begin())
            {
                var test = from Person in _PersonRepositroy.GetAll()
                           select new PersonListDto
                           {
                               Id = Person.Id,
                               Text = Person.Text,
                               Code = Person.Code,                               
                               TenantId = Person.TenantId
                           };
                a = test.ToList();//No Data is apppearing, event though database has the data
                await uow.CompleteAsync();
            }

            
        }

}**
using this code I get null data as I have data in my DB.

I am using asp.net Core (3.0) +Entity Framework 5.0

**Comment by Rick-Anderson** [comment]
Unit tests typically don't connect to a real DB.
