### ISSUE TITLE
Suggestion: Create an ASP.NET Core Web Application + Angular template tutorial.

### ISSUE THREAD

**Issue by KariNarhi** [dotnet/AspNetCore.Docs#19942]
Core docs have tutorials for Razor Pages, MVC and Blazor.

It would be nice to have some beginner level tutorial projects for **ASP.NET Core Web Application + Angular** and possibly for **ASP.NET Core Web Application + React** too.

Speaking from personal experience, in order to understand the **Core Web App + Angular** template, I had to go through the Razor Pages / MVC tutorials + Angular tutorial from Angular website.

While this was useful and interesting, it still does not exactly teach me how these technologies play together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
