### ISSUE TITLE
IWebHostEnvironment availability

### ISSUE THREAD

**Issue by icelava** [dotnet/AspNetCore.Docs#19947]
The typical ASP.NET Core project setup only makes IWebHostEnvironment available at the Configure() stage, while part of this documentation states it can be injected as early as the Startup instantiation/construction stage.

Why is the former the standard practice? Is there any disadvantage to making available earlier?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
The templates etc only _use_ `IWebHostEnvironment` in `Startup.Configure`, so there's no need to inject it earlier. It's perfectly reasonable to inject it into the `Startup` constructor, though, if you need to e.g. add services in `Startup.ConfigureServices` based on the runtime environment.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
