### ISSUE TITLE
Similar to OptionsWrapper which returns an instance of Ioptions, what is the alternative to get an instance of IOPtionsMonitor or OPtionsMonitor

### ISSUE THREAD

**Issue by mallikarjuna06** [dotnet/AspNetCore.Docs#19943]
Context here

![image](https://user-images.githubusercontent.com/21369057/93729073-b552bd80-fb77-11ea-9298-1bffb00e6f67.png)

How can we achieve this? Can some one help me out here
@HaoK   @bratsche  @noahfalk @suprak @adamsitnik @brianrob

**Comment by davidfowl** [comment]
Unfortunately there's no convenience API for making an options monitor.

**Comment by mallikarjuna06** [comment]
@davidfowl 
Is there a way to use OptionMonitor for this ? As shown in above code snippet ?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
