### ISSUE TITLE
Administrative Roles do not come from group claim

### ISSUE THREAD

**Issue by partmachine** [dotnet/AspNetCore.Docs#19941]
This article suggests you can get Azure Administrative roles assigned to the user from the 'groups' claim.
Tenant wide roles such as 'Billing Administrator' and 'Global Administrator' will come back in the token 'wids' claim not in the 'groups' claim, furthermore the the 'wids' claim does not contain the objectId for the role but the [RoleTemplateId](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-template-ids).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-3.1#user-defined-groups-and-built-in-administrative-roles)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Are you using Identity Platform v2.0? The topic's guidance at this time is for v1.0 with v2.0 updates coming soon.

**Comment by partmachine** [comment]
I'm using the latest from Blazor WebAssembly which is using MSAL so I guess I am.

**Comment by guardrex** [comment]
Blazor goes to Identity 2.0 for .NET 5. The current release 3.x is on Identity 1.0. I hope to get to work on the doc updates for .NET 5 this week.
