### ISSUE TITLE
[issue]: Unable to continue starter tutorial on Web App with Razor Pages at Part 2

### ISSUE THREAD

**Issue by KilianKilmister** [dotnet/AspNetCore.Docs#19959]
There seems to be an Issue with`Microsoft.VisualStudio.Web.CodeGeneration.Design` package not being found by the dotnet aspnet-codegenerator tool on ***NIX** systems with **SDK** `v3.1.*`. [Related issue in `Scaffolding`](https://github.com/dotnet/Scaffolding/issues/1393)

I have not been able to complete the second step of this tutorial on MacOS Catalina + vs-code, and i have tried the suggestions mentioned in the linked issue above.
Cross posting it here since it affects the 2nd tutorial. Right after the 'Hello World in 10min' and linked by that, so any starter could run into this issue.

I would also apreciate a suggenstion on a tutorial of a similar level, detail and topic. I'm not at all familiar with `ASP.NET`.

my `dotnet --info`:
```fish
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Leave a comment in  [Related issue in `Scaffolding`](https://github.com/dotnet/Scaffolding/issues/1393)

**Comment by KilianKilmister** [comment]
@Rick-Anderson Why was this closed?

Neither of my issues has been resolved in any way, and many people new to ASP.NET Core  are bound to run into this. Also, i not only left a comment there already, i also crossreferenced this issue from there as is clearly visible in the timeline.

> Leave a comment in [Related issue in `Scaffolding`](https://github.com/dotnet/Scaffolding/issues/1393)

This isn't a response to this issue, and closing it with that *"explanation"* only is frankly unacceptable.
