### ISSUE TITLE
Don't await the task at the end of method, just return it if it is the only await. 

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/AspNetCore.Docs#19950]
Regarding following code in one of "Do this" section above, I think it can use little bit improvement.

public class GoodStreamReaderController : Controller
{
    [HttpGet("/contoso")]
    public async Task<ActionResult<ContosoData>> Get()
    {
        return await JsonSerializer.DeserializeAsync<ContosoData>(Request.Body);
    }
}

=> 

public class GoodStreamReaderController : Controller
{
    [HttpGet("/contoso")]
    public  Task<ActionResult<ContosoData>> Get()
    {
        return  JsonSerializer.DeserializeAsync<ContosoData>(Request.Body);
    }
}

If return statement is awaiting and returning a task, and it is the only await in the code, then asyc/awite is not needed, just return the task.   It is not huge performance gain, but lots of people look up at this page as guideline, so I think make sense improve even tiny bit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by mjrousos** [comment]
Good suggestion. Thanks, @RyanLiu99.

**Comment by guardrex** [comment]
Is there any caveat for what happens with exceptions with this change when `DeserializeAsync` throws?

I've only gathered thus far that prior to making such a change the error would be thrown in the method and with the change the error would be thrown in the caller. Just wondering if that has any bearing on this change?

**Comment by mjrousos** [comment]
You're right about that difference, @guardrex, but I don't think it matters in this case. We weren't catching any exceptions in the sample method, so anything that threw when we awaited would have bubbled to the caller anyhow. So, it's a good point that this will be slightly different, but I think not in a way that's worth calling out.

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you're interested in this one.

**Comment by serpent5** [comment]
I'd suggest handling this one a bit differently:

David Fowler's [async guidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task) says to "Prefer `async`/`await` over directly returning `Task`". I understand that this particular example is safe in terms of the usual gotchas, but my suggestion is to consider adding guidance within this topic that uses David's explanation of the pitfalls. Perhaps it would be something along the lines of "you can drop the `async`/`await` to help performance, but do make sure you're aware of the potential problems with doing so".

**Comment by mjrousos** [comment]
I like that compromise. In this case (and since this is a performance-focused doc) dropping async/await may be useful, but you're right that we don't want to demonstrate a pattern that might get people into trouble elsewhere.

**Comment by serpent5** [comment]
I've just looked into this, to the point of opening a pull request, but it occurred to me that this example doesn't compile without `async`/`await`.

The return type of the action is `Task<ActionResult<ContosoData>>`, but `JsonSerializer.DeserializeAsync<ContosoData>` returns `ValueTask<ContosoData>`. For what I believe is down to `Task<T>` not being covariant, this doesn't compile without `async`/`await`.
