### ISSUE TITLE
Check for direct return of Task opportunities in Blazor docs

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19958]
#19950

**Comment by guardrex** [comment]
I checked all of the async `Task`-returning methods ... nothing is screaming for an update in this regard AFAICT. There might be one or a few example spots in the *Call web API* topic, but the sample app has to await multiple `Task`s in the methods that interact with the server API because the UI has to be updated after server API requests. We could update one or a couple of examples there perhaps, but a better solution is perhaps to make the code examples reflect more of a real-world scenario (e.g., what's in the sample app for those topic examples) where two awaited methods are called, thus there would be no changes for this issue ... we'd still be using `async`-marked methods with `await`s in the method bodies. We'll take a look at code on individual topic reviews later and perhaps something will turn up.

**Comment by serpent5** [comment]
FWIW, I think this is a good outcome. I think it's much better for the docs to provide code samples that are better protected when being copy/pasted and modified to including a `using`, introduce different exception semantics, etc. David Fowler's [async guidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#prefer-asyncawait-over-directly-returning-task) appears to echo this, too.
