### ISSUE TITLE
dotnet-aspnet-codegenerator error: Create.cshtml file not found.

### ISSUE THREAD

**Issue by anderson036** [dotnet/AspNetCore.Docs#19965]
Hi.
I was following the RazorPage tutorial (using VisualCode on Ubuntu 20.04 OS, and dotnet-aspnet-codegenerator version 3.1.4), but I couldn't generate the razor page with the code genertor. When I execute the following command:

dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries

the following message appear on my:

Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
A file matching the name Create.cshtml was not found within any of the folders: 
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:06.48

It seems that the tool require a file named  Create.cshtml, and I dont know why because I followed all the steps of the tutorial. I was searching on internet for a possible solution to this problem and I found that someone fixed a  similar error using  version 3.1.0 of dotnet-aspnet-codegenerator tool. I uninstalled the version 3.1.4 and install the version 3.1.0, and them, I executed the same command, but it gave me another error who tell me that the razorpage generator was not found. I will appreciate any help to allow me to find a solution to this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is tracked in https://github.com/dotnet/Scaffolding/issues/1393 and has work arounds.
