### ISSUE TITLE
3.1 update: Scaffold Identity

### ISSUE THREAD

**Issue by richardcox13** [dotnet/AspNetCore.Docs#19974]
In the section Create full Identity UI source the code includes setting the option `AllowAreas` in the changes for `Startup.ConfigureServices`. But this was removed in Core 3.0 (see [here](https://github.com/dotnet/AspNetCore.Docs/issues/14357)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#create-full-identity-ui-source)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@richardcox13 thanks for the report
`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)`

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
