### ISSUE TITLE
Revert to minified Google Brotli script in Blazor WASM hosting

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#19979]
When https://github.com/google/brotli/issues/844 is resolved, revert guidance and NOTE on using the unminified version of the script in the *Compression* section of the topic (Lines 38-41 + the in the example on Line 46).

Guidance was updated temporarily on https://github.com/dotnet/AspNetCore.Docs/pull/19978.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@javiercn @SteveSandersonMS @danroth27 ... Google (or their contractor ... or their open source community support) isn't maintaining their Brotli JS decoder script. They won't address [the problem reported](https://github.com/google/brotli/issues/844) to permit the use of the cross-linked minified script. Their repo has unanswered issues going back to October.

I don't think that we want to maintain a fork.

I'm personally not even allowed to submit a PR to them under Aquent rules, and there's no reason to believe that they'd even look at it based on their unresponsiveness anyway even if I did.

Is there anything else we could use besides Google's Brotli script for this scenario?

**Comment by danroth27** [comment]
Maybe https://www.npmjs.com/package/brotli?

**Comment by guardrex** [comment]
Thanks ... I'll give that a shot. I'll probably try it when I reach this topic on the UE sweep. I'll add a cross-link to my tracking issue so that I don't forget this.

**Comment by guardrex** [comment]
**UPDATE**: I'm following up with Google to ask about an ETA on fixing their compressed script. I think what we can do is just host a fixed version of their script and keep an :eye: on their issue. Let's see if they respond.

btw - https://www.npmjs.com/package/brotli seems a bit sketchy on support looking at their GH issues, so I'm concerned about recommending it.

**Comment by guardrex** [comment]
**UPDATE**: I've tried **_multiple times_** to reach out to Google on maintenance of their script, but the maintainers won't respond. They have some substantial languishing updates, too, in their submitted PRs, including a fix submitted back in October for our problem.

https://www.npmjs.com/package/brotli isn't being maintained either. Devs have opened bug reports, but the maintainer won't reply.

I'm going to poke around and see if I can't scare something else up.

**Comment by guardrex** [comment]
**UPDATE**: *FIXED!* ... They fixed it. I'll proceed and reverting back to the text that what we had and drop the NOTE.
