### ISSUE TITLE
There is no information on the <port>. What is the default, how to configure?

### ISSUE THREAD

**Issue by Scherlac** [dotnet/AspNetCore.Docs#19976]
There is no information on the <port>. What is the default, how to configure?

> Launch the app, and navigate to http:\/\/localhost:&lt;port>/swagger/v1/swagger.json. The generated document describing the endpoints appears as shown in OpenAPI specification (openapi.json).
> The Swagger UI can be found at http:\/\/localhost:&lt;port>/swagger. Explore the API via Swagger UI and incorporate it in other programs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
When using Kestrel , for example, from `dotnet run`, the default port is 5001. Visual studio generates a random port and launches the default browser to that port.
