### ISSUE TITLE
Ideas for restructuring ANCM/IIS docs

### ISSUE THREAD

**Issue by jkotalik** [dotnet/AspNetCore.Docs#19982]
We were recently chatting in the ASP.NET Core team about how some of our docs for Servers/Host and Deploy are a bit long and have many topics that don't closely relate to each other. For example, the IIS overview doc takes 76 minutes to read and is just a collection of different topics that aren't strictly related to each other: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1. To a new user, seeing a 76 minute document is quite intimidating if they are just trying to get started with IIS or trying to find a specific issue.

My current thought is to break down these large grouping documents into more subsections. Here is a list of topics that I was thinking of breaking things into.

- Getting started
- Publishing
- Logging and diagnostics
- Troubleshooting lookup (similar to https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1)
- Troubleshooting guide (More of a walkthrough guide like https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-3.1)
- Hosting model - Inprocess
- Hosting model - Out of process
- Hosting bundle
- Application warmup
- app_offline.htm
- web.config
- Advanced
- Handler settings/configuration

Again, this wouldn't be changing the content, just the organization. 
@guardrex @Rick-Anderson @shirhatti Thoughts?

**Comment by guardrex** [comment]
I agree. It started at a reasonable length; but years later, it has become a BeAsT 👹.

Do you propose to set the PR up, or do you want to provide the breakouts and have me (or someone else) set it up. I'll be free-er-ish in a couple of weeks right after Blazor WASM security docs are updated.

**Comment by jkotalik** [comment]
I can do the basic layout and a bit of polish, I started specing it out locally to see what topics I wanted to highlight. I'll make a PR and we can decide how to party on afterwards.

**Comment by guardrex** [comment]
Cool ... We won't need a redirect entry for this AFAIK because the overview will remain with whatever isn't stripped out.

**Comment by jkotalik** [comment]
I was hoping to just target 5.0 with this change? That way 3.1 links will all still work.

**Comment by guardrex** [comment]
It can be done at the risk of creating more maintenance overhead until the LTM for 3.x drops. Two copies mean two updates for at least some issues.

On the other hand, this content has been remarkably stable over the years. IIS doesn't change much, fortunately.

I recommend just a re-org and as little dup as possible. In addition to the forward maintenance saved, I think it would

**Comment by jkotalik** [comment]
Sounds good, I'll try that.

**Comment by Rick-Anderson** [comment]
If you need more than 2 pairs of 
```
::: moniker range=">= aspnetcore-3.0 < aspnetcore-5.0"

::: moniker-end

::: moniker range=">= aspnetcore-5.0"

::: moniker-end
```

Then it's better to do whole version copies. We've found that soon after a major release is GA, 97% of the traffic uses the latest release. It's not difficult to make the same update in 2 places if that's warranted. But many monikers makes the doc very fragile to update and hard to reason about. Customers are less likely to update such a doc.
