### ISSUE TITLE
Obsolete Interface of IDbContextFactory being shown in example

### ISSUE THREAD

**Issue by EddyHaigh** [dotnet/AspNetCore.Docs#19989]
The example factory talks about using the [obsolete interface of IDbContextFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.infrastructure.idbcontextfactory-1?view=efcore-2.2). Documentation needs to be updated for the recommended interface of IDesignTimeDbContextFactory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment]
@EddyHaigh the documentation you are looking at for is EF Core 2.2. The interface doesn't exist in 3.1, and is implemented locally in the sample. The interface has been [reintroduced in EF Core 5.0](https://github.com/dotnet/efcore/blob/main/src/EFCore/IDbContextFactory.cs) and is not obsolete. 

Am I missing anything?

**Comment by EddyHaigh** [comment]
I was looking at the [Asp.Net Core 3.1 documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1). It's not really clear that the interface isn't available, the docs make it sound more like its just the concrete type (DbContextFactory) that is missing since there's no code for the interface.

**Comment by guardrex** [comment]
https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Data/IDbContextFactory.cs

We *might* want to call out that it's implemented in the sample. @JeremyLikness, do you want me to add a sentence in those two sections to make that clear for the 3.1 version of the doc and then ping u to review, or do you want to take care of this (or do nothing, in which case we can close)?

**Comment by JeremyLikness** [comment]
I think it will be valuable to add some context and I'm happy to review.
