### ISSUE TITLE
Lacking info for AKS CSI integration

### ISSUE THREAD

**Issue by irperez** [dotnet/AspNetCore.Docs#19993]
There is no info on how to utilize Key Vault & .Net Core with the AKS CSI driver.  There is documentation on setting up the CSI driver in AKS, but not how .Net Core leverages Key Vault in that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> There is documentation on setting up the CSI driver in AKS,

Where is that?

**Comment by irperez** [comment]
Its here:
https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes#assign-your-service-principal-or-use-managed-identities

However, it's not clear that in .Net Core, if we just need to use normal Configuration or if we need some other mechanism or a NuGet library to access secrets.

**Comment by Rick-Anderson** [comment]
> However, it's not clear that in .Net Core, if we just need to use normal Configuration or if we need some other mechanism or a NuGet library to access secrets.

Unless it states otherwise, the built in configuration should work and you'd get a compiler error if missing a NuGet package.

**Comment by Rick-Anderson** [comment]
@irperez  have you reviewed https://github.com/Azure/secrets-store-csi-driver-provider-azure
By AKS, I assume you mean Azure Key Vault.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
