### ISSUE TITLE
services.AddDistributedMemoryCache() Not needed

### ISSUE THREAD

**Issue by YSternlicht** [dotnet/AspNetCore.Docs#19992]
In the docs, it says
"To enable the session middleware, Startup must contain:

Any of the IDistributedCache memory caches. The IDistributedCache implementation is used as a backing store for session. For more information, see Distributed caching in ASP.NET Core.
A call to AddSession in ConfigureServices.
A call to UseSession in Configure."

However, the app seems to work with sessions fine, even without the call to services.AddDistributedMemoryCache();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by YSternlicht** [comment]
Wrong page. Sorry guys

**Comment by Rick-Anderson** [comment]
@serpent5  any comment?

**Comment by serpent5** [comment]
A quick scan of the codebase shows that both `AddControllersWithViews` and `AddRazorPages` end up triggering a call to `AddDistributedMemoryCache`, so it's not _required_ in those cases. I think it's still important to show it in this topic, in case these particular features aren't being used.

**Comment by Rick-Anderson** [comment]
@serpent5  Thanks.

**Comment by YSternlicht** [comment]
Thanks for your help
