### ISSUE TITLE
Warning about obsolete docs should link to updated documentation

### ISSUE THREAD

**Issue by IronSean** [dotnet/AspNetCore.Docs#19998]
The warning on this page states the content is obsolete, and recommended using an updated package. However, it only links to the NuGet page for the package and not to any documentation about how to use or implement said package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScript Services to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Dup of #18405
