### ISSUE TITLE
Documentation from hell...

### ISSUE THREAD

**Issue by OneGenkiGirl73** [dotnet/AspNetCore.Docs#19996]
Reading MicroSoft's documentation always reminds me of one of Bart Simpson's math tests...

"At 7:30am an express train leaves the station for Santa Fe..."

https://youtu.be/6Jq_9ghf-jI 

@@<< Cat...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @OneGenkiGirl73 ... We can only address specific comments. If you send actionable feedback, we can re-open and work this.
