### ISSUE TITLE
Scaffold the movie model failed when referring to the link below

### ISSUE THREAD

**Issue by guowil2018** [dotnet/AspNetCore.Docs#19994]
I followed the link below to auto generate the code using scaffold process. But those files are not generated as expected. I got an error during the process. Error message: there was an error running the selected code generator 'Install the package Microsoft.VisualStudio.Web.CodeGeneration.Design and try again'. I am using VS2019. 

Pages/Movies: Create, Delete, Details, Edit, and Index.
Data/RazorPagesMovieContext.cs 

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Follow the instructions in the error message.

**Comment by guowil2018** [comment]
It does not work. I figured out the root cause. I have net5.0 installed which has this issue. When I use dedicated .detcore SDK version 3.1.302 through global.json file, then it works.

**Comment by Rick-Anderson** [comment]
I've been using .NET 5 RC1, and it does work. The error message explained the problem.
