### ISSUE TITLE
services.AddDistributedMemoryCache() Not needed

### ISSUE THREAD

**Issue by YSternlicht** [dotnet/AspNetCore.Docs#19991]
In the docs, it says
"To enable the session middleware, Startup must contain:

Any of the IDistributedCache memory caches. The IDistributedCache implementation is used as a backing store for session. For more information, see Distributed caching in ASP.NET Core.
A call to AddSession in ConfigureServices.
A call to UseSession in Configure."

However, the app seems to work with sessions fine, even without the call to services.AddDistributedMemoryCache();

**Comment by guardrex** [comment]
Hello @YSternlicht ...

For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
