### ISSUE TITLE
Source code for the page

### ISSUE THREAD

**Issue by chanmmn** [dotnet/AspNetCore.Docs#20002]
It is quite hard for people to follow with the source code. Why not put a source code link with the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698a8824-7a38-70d6-c041-0dca4c040217
* Version Independent ID: ae663e33-6a08-0b24-aa19-3fc3c9edccfc
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @chanmmn ... I don't understand your ask. Can you explain in more detail?

**Comment by guardrex** [comment]
... "with" ... did you mean "without the source code [from the sample app]"?

Yes, I'll cross-link the sample app.

I'll also show a little more code in the component that uses the templated component.
