### ISSUE TITLE
Adding Grpc.Tools doesn't result in a buildable solution

### ISSUE THREAD

**Issue by clarkezone** [dotnet/AspNetCore.Docs#20009]
[Enter feedback here]
I just installed clean VS2019, file new gRPC service, all good it builds.  Now I want a test client

File new Console app, add the greet.proto from the service, install Grpc.Tools (2,32.0)
Switch the build action to protobuf compiler, Client only
Build the client project 
Result:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	8	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	9	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	10	N/A
Error	CS0538	'Google.Protobuf.IMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	61	N/A
Error	CS0115	'HelloRequest.Equals(object)': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	95	N/A
Error	CS0115	'HelloRequest.GetHashCode()': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	112	N/A
Error	CS0115	'HelloRequest.ToString()': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	122	N/A
Error	CS0538	'Google.Protobuf.IBufferMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	143	N/A
Error	CS0538	'Google.Protobuf.IBufferMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	199	N/A
Error	CS0538	'Google.Protobuf.IMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	236	N/A
Error	CS0115	'HelloReply.Equals(object)': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	270	N/A
Error	CS0115	'HelloReply.GetHashCode()': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	287	N/A
Error	CS0115	'HelloReply.ToString()': no suitable method found to override	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	297	N/A
Error	CS0538	'Google.Protobuf.IBufferMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	318	N/A
Error	CS0538	'Google.Protobuf.IBufferMessage' in explicit interface declaration is not an interface	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\Greet.cs	374	N/A
Error	CS0400	The type or namespace name 'Grpc' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	8	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	18	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	37	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	37	N/A
Error	CS0400	The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	59	N/A
Error	CS0246	The type or namespace name 'ClientBaseConfiguration' could not be found (are you missing a using directive or an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	83	N/A
Error	CS0246	The type or namespace name 'ClientBaseConfiguration' could not be found (are you missing a using directive or an assembly reference?)	gRPCClientTest	C:\Users\jeclarke\source\repos\GrpcService1\gRPCClientTest\obj\Debug\netcoreapp3.1\Protos\GreetGrpc.cs	132	N/A

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
Can you try https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start

It has more complete steps.

**Comment by DzonnyDZ** [comment]
Also add reference to ``Google.Protobuf``, it builds than.
