### ISSUE TITLE
Refactor the entire document

### ISSUE THREAD

**Issue by cijothomas** [dotnet/AspNetCore.Docs#20007]
This document has gotten really long with too many information and is hard to navigate. Despite being long, some critical questions are hard to find answers to. For eg:
Does Logging work on Console apps?
Does it work in .NET Framework apps? If yes, which versions are supported?
If I write own LoggingProvider, should I cache my ILogger instance or create new one always?
What is ExternalScopeProvider?

Proposing to break this doc into several separate docs.

1. Introduction to Logging in .NET - what is structured logging, what capabilities ILogger has, why should one use Ilogger vs directly using NLog or ApplicationInsights API?, support .NET versions/app models, explain terminology like LoggerFactory, LoggingBuilder, LoggerProvider etc.

2. Features like - EventId, LogFiltering, Logging Exceptions, etc.

3. Usage examples in DI/Host based apps (Asp.Net Core), non DI/Host apps (plain Console apps or libraries)

4. Well known providers:
   a. Built-in providers or providers shipped as part of shared framework. (Console, Debug)
   b. Microsoft supported providers providers (AzureBlob,ApplicationInsights)
   c. Third party providers - NLog, Serilog. 

4. How to write a custom logging provider? (Implement ILogger, implement ILoggerProvider, provide extension method on ILoggingBuilder, best practices)

5. Advanced usage - scopes, loggermessage, correlation (traceid/spanid stamping in logger scopes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Does Logging work on Console apps?
See https://github.com/dotnet/docs/issues/4567  Logging is planned next. See https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers

> Does it work in .NET Framework apps? If yes, which versions are supported?
See the 2.1 version.  .NET Framework is not supported on 3.0 and higher

Writing a logging provider is a very advanced scenario that we typically don't cover in detail.

**Comment by mkArtakMSFT** [comment]
@ericstj as logging is now owned by your team, how do you want to track this work? Should we move this issue somewhere else?

**Comment by ericstj** [comment]
@mkArtakMSFT let's add the area-runtime-extensions label to such issues and we can look at them.  cc @maryamariyan

**Comment by Rick-Anderson** [comment]
> This document has gotten really long with too many information and is hard to navigate. Despite being long, some critical questions are hard to find answers to. 

We don't have the resource to refactor for easy navigation.

For eg: Does Logging work on Console apps? 
Yes, there's a link in the first paragraph for that.

Does it work in .NET Framework apps? If yes, which versions are supported?

This is ASP.NET Core.

 If I write own LoggingProvider, should I cache my ILogger instance or create new one always? What is ExternalScopeProvider?

That issue should be opened in [Implement a custom logging provider in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider);
> 
> Proposing to break this doc into several separate docs.
> 
> 1. Introduction to Logging in .NET - what is structured logging, what capabilities ILogger has, why should one use Ilogger vs directly using NLog or ApplicationInsights API?, support .NET versions/app models, explain terminology like LoggerFactory, LoggingBuilder, LoggerProvider etc.
> 2. Features like - EventId, LogFiltering, Logging Exceptions, etc.
> 3. Usage examples in DI/Host based apps (Asp.Net Core), non DI/Host apps (plain Console apps or libraries)
> 4. Well known providers:
>    a. Built-in providers or providers shipped as part of shared framework. (Console, Debug)
>    b. Microsoft supported providers providers (AzureBlob,ApplicationInsights)
>    c. Third party providers - NLog, Serilog.
> 5. How to write a custom logging provider? (Implement ILogger, implement ILoggerProvider, provide extension method on ILoggingBuilder, best practices)
> 6. Advanced usage - scopes, loggermessage, correlation (traceid/spanid stamping in logger scopes)
> 

As mentioned we don't have the resources for that. I'll close this issue unless you can suggest realistic actionable items.

**Comment by cijothomas** [comment]
@Rick-Anderson Thanks for responding. I opened this issue, when https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line was not yet available. That doc fixes most of the issues.

> I'll close this issue unless you can suggest realistic actionable items.

When I opened this issue originally, everything was realistic and actionable 😆 , and since the https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line is available now, okay to close this.
