### ISSUE TITLE
docker example needs updating since curl no longer included

### ISSUE THREAD

**Issue by gitting** [dotnet/AspNetCore.Docs#20012]
According to [this](https://github.com/dotnet/dotnet-docker/issues/1814) (and my own experience) `curl` is no longer included in 5.0 and so healthcheck using `curl` fails. Documentation needs to address this somehow as it is confusing in comparison with 2.1/3.1 where it does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It states;
**We will install git, curl,** and wget packages in the 5.0 SDK images going forward.

**Comment by gitting** [comment]
OK, so then the preview documentation (ASP.NET Core 5.0 Preview in this case) describes the final release behavior and should not be expected to match a particular current preview version.

**Comment by gitting** [comment]
Pulled the latest release images just now and it looks like `curl` is still not there.

**Comment by gitting** [comment]
Looks like the exclusion is permanent now per [this](https://github.com/dotnet/dotnet-docker/issues/2379).
