### ISSUE TITLE
When I have multiple .net core SDK installed in system at that time new project creation is not working.

### ISSUE THREAD

**Issue by VinodTarsariya** [dotnet/AspNetCore.Docs#20022]
Whenever I am creating a web API project from VS code at that time default application is being created in a newer version of .net core SDK. So if I want to create a project in the lower version then no option available for it. For example in my system I have .net core 2.0, 3.1, 2.1 and 5RC .net core and when I create new project default app version is 5RC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @VinodTarsariya ... You can control the version of the SDK with a `global.json` file in the project.

https://docs.microsoft.com/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version
