### ISSUE TITLE
Code example for using implementation of IAuthorizationHandler

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#20021]
`PermissionHandler` implements `IAuthorizationHandler` in the article. But how to use `PermissionHandler`?

Please provide a code example of how to use `PermissionHandler`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#security-authorization-policies-based-handler-registration)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1#handler-registration

**Comment by PingPongSet** [comment]
@Rick-Anderson Thanks. But I cannot see `PermissionHandler` in the example. Please point it out.

**Comment by Rick-Anderson** [comment]
It's the same as the `MinimumAgeHandler`

**Comment by PingPongSet** [comment]
@Rick-Anderson Thanks.
How to declare `ReadPermission`, `EditPermission`, and `DeletePermission` for `PermissionHandler`, if required like below

```
 services.AddAuthorization(options =>
    {
        options.AddPolicy("AtLeast21", policy =>
            policy.Requirements.Add(new MinimumAgeRequirement(21)));
    });
```
Please provide an example if possible.

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data
