### ISSUE TITLE
Instructions for lazy loading with server side prerender incorrect

### ISSUE THREAD

**Issue by GisliSig** [dotnet/AspNetCore.Docs#20020]
It is said that you need to add this line into ConfigureServices in the Server project when using Server Prerender:
`services.AddSingleton<LazyAssemblyLoader>();`

This throws an error, because in a Server project, IJsRuntime has a scoped lifetime and the LazyAssemblyLoader tries to dependency inject it throws this error:
AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Components.WebAssembly.Services.LazyAssemblyLoader Lifetime: Singleton ImplementationType: Microsoft.AspNetCore.Components.WebAssembly.Services.LazyAssemblyLoader': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Microsoft.AspNetCore.Components.WebAssembly.Services.LazyAssemblyLoader'.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690632ad-f357-161f-217b-faba56e90f36
* Version Independent ID: 626c5ed9-6424-7940-56e2-a19989b6de38
* Content: [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-lazy-load-assemblies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@captainsafia

**Comment by captainsafia** [comment]
@guardrex Argh! Yeah, this should be `AddScoped`. I think you might've actually had it set to that at first before I nudged you to the wrong solution.
