### ISSUE TITLE
After completing the steps on this page, cannot build due to error

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#20029]
I'm getting the following error on the latest release of Visual Studio for Mac 8.8 Preview (8.8 build 2120) on a Blazor Server project. I'm not sure why it's looking for a .NETFramework. Could a step be missing from the instructions?

I see where [Blazor WebAssembly in 5.0 RC1 isn't supported yet,](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2019-mac-preview-relnotes#knownissues) but Blazor Server should be.

> /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks (MSB3644)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @mrlife ... Could you open this one for the product unit to address? If they say that we need something else in the migration doc, then signal us back here ... or you can add me to the engineering issue `cc: @guardrex` and I'll follow along and re-open this if actionable here.

https://github.com/dotnet/aspnetcore/issues
