### ISSUE TITLE
Blazor InputFile 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/AspNetCore.Docs#20035]
[EDIT by guardrex to add the metadata]

The InputFile component allows reading one or more files selected by a user to be upload. The `OnChange` event handler is invoked when a file selection is performed by the user. 

`FileChangeEventArgs.GetMultipleFiles` allows reading multiple files. Specify the maximum number of files you expect to read here., This prevents a malicious user from uploading a larger number of files than the app expects. `FileChangeEventArgs.File` allows reading the first and only file if the file upload does not support multiple files. 

`IBrowserFile` returns metadata [exposed by the browser](https://developer.mozilla.org/en-US/docs/Web/API/File#Instance_properties) as properties. This metadata can be useful to preliminary validation. It's important to understand and apply the the security consideration described in https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads here when reading these files.

To begin reading a file, use `ReadAsync`. By default `ReadAsync` only allows reading a file smaller than 512kb in size. This limit is present to prevent developers from accidentally reading large files in to memory. Specify a reasonable approximation for the maximum expected file size if larger files need to be supported. Avoid reading the incoming file stream is not read to memory (copied to a `MemoryStream`, read as a byte array etc) as this can result in performance and security issues, especially in Blazor Server. Instead consider copying to an external store such as a blob or a file on disk.

In Blazor Server, file upload is performed by sending chunks of data over the SignalR connection. `<xref:Microsoft.AspNetCore.Components.Forms.RemoteBrowserFileStreamOptions />` allows configuring some of the implementation that drives the file upload.

Sample app demonstrating file upload + validation + progress bar: https://github.com/pranavkm/FileUpload/blob/master/Pages/Index.razor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by pranavkm** [comment]
@guardrex this is a bit of a brain dump. Can you help me structure this in to a section for https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#built-in-forms-components?

**Comment by guardrex** [comment]
Sure thing ... I'll take a look Tuesday morning.

**Comment by guardrex** [comment]
This is for ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0

... correct?

**Comment by guardrex** [comment]
btw --- just so you know --- and perhaps you can correct me if you think I'm wrong about this ...

I placed file uploads into its own new topic and not into forms in the first place because this component works outside of a form AFAIK. Therefore, it seemed like it would be best on its own. It's also more visible this way in the ToC.

Anyway ... yeah ... to the extent these new concepts go into the forms validation topic, I'll cross-link both ways.
