### ISSUE TITLE
Why is the check `if (id != movie.ID)` required in the Edit POST method?

### ISSUE THREAD

**Issue by tekkies** [dotnet/AspNetCore.Docs#20033]
* Why is the check `if (id != movie.ID)` required in the Edit POST method?  It seems unnecessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Part 6, controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tekkies** [comment]
Question more fully asked here: https://stackoverflow.com/q/64106714/270155

**Comment by Rick-Anderson** [comment]
The scaffolder generates that. Feel free to remove it. In some cases it may be needed.
