### ISSUE TITLE
Missing link to source code

### ISSUE THREAD

**Issue by ChrisKlug** [dotnet/AspNetCore.Docs#20039]
The page contains a lot of references to sample code, and includes comments like "Code removed for brevity", but I can't find a link to the actual code. This makes it really hard to grasp the whole picture as the codes is very limited and shows only the exact things talked about.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebdbdab0-c474-3fdd-76aa-ade905e76079
* Version Independent ID: 761ea2cc-7e05-4ae0-0875-44061a163621
* Content: [Multi-factor authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/mfa.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by damienbod** [comment]
@ChrisKlug @Rick-Anderson 

I could add src code projects for this if you want. Most of the code was built using snippets from this repo:

https://github.com/damienbod/AspNetCoreHybridFlowWithApi

Greetings Damien

**Comment by ChrisKlug** [comment]
I found that repo after Googling it, but the problem is that it is not linked anywhere in the page. This makes it really hard to find, and makes the code hard to understand to be honest.

**Comment by guardrex** [comment]
The problem with moving the samples into the repo is keeping them up-to-date. Given that you, @damienbod, are the topic author and keep that repo up-to-date, I recommend cross-linking that repo as an additional resource for the topic. If you ever stopped keeping that repo up-to-date in the future, then I recommend that they come into the repo.

**Comment by guardrex** [comment]
In addition to a title, you can also add some parenthetical info. For example something like ...

> \* [Authentication samples (damienbod/AspNetCoreHybridFlowWithApi GitHub repository)](https://github.com/damienbod/AspNetCoreHybridFlowWithApi): Code examples in this article are demonstrated in the sample apps.

**Comment by damienbod** [comment]
I 'll do a PR then. @guardrex  What's the best way to link it? A note at the top and a link?

@ChrisKlug Would you find this good, would this help?

Greetings Damien

**Comment by ChrisKlug** [comment]
I would say that a link at the top would be awesome! It would make it nice and easy to clone the repo before reading the code. 

Cheers,
Chris

**Comment by guardrex** [comment]
We generally only link samples that are part of the repo at the top. Since I don't think we should host the samples in this case, I recommend placing the cross-link into the **Additional resources** section at the bottom.

This is a somewhat arbitrary opinion tho. We'll ask Rick to review+approve the PR. You can put the link at the top and see if he thinks it will be ok. Something like ...

```
[View or download sample code (damienbod/AspNetCoreHybridFlowWithApi GitHub repository)](https://github.com/damienbod/AspNetCoreHybridFlowWithApi)
```

... immediately under the author byline.
