### ISSUE TITLE
Conflicting statement

### ISSUE THREAD

**Issue by emmerel37** [dotnet/AspNetCore.Docs#20040]
In the "Project file" section you instructed to use the assembly name without the ".dll" extension. Then in the sample XML you included it.

Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690632ad-f357-161f-217b-faba56e90f36
* Version Independent ID: 626c5ed9-6424-7940-56e2-a19989b6de38
* Content: [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-lazy-load-assemblies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @emmerel37 ... There was a change during the preview and it merely didn't get updated in **_both_** spots. It takes the file with the `.dll` extension in the RC1 release (and going forward to GA). I'll patch this right now. Thanks for reporting it.
