### ISSUE TITLE
Azure AD B2C Blazor - Doc needs to reference the needed Add of an "API Permission" for the API scope and Grant or you will get a strange json error.

### ISSUE THREAD

**Issue by BruceHunter** [dotnet/AspNetCore.Docs#20045]
Cross-link Reference to the issue and discussion: https://github.com/dotnet/aspnetcore/issues/26364

Probably needed for 3.1 and 5.x - Version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @BruceHunter ... I'll get back to you as soon as I can. 🏃🏃🏃🏃🏃🏃
