### ISSUE TITLE
IIS Module is no longer founded but also not need it. Also, Contet-Type Header is not exposed by default

### ISSUE THREAD

**Issue by LiviuSosu** [dotnet/AspNetCore.Docs#20058]
Hi,

I jsut want to provide you some input after follwoing this article.

I was not able to install IIS Module (you may see the screeshon - unfortunatelly in Germna language, after running the cors.exe that I downloaded). Apparently was not necessary. From my sie, you may remove the section in question.

Alos, in order to consume the JSON api, on the same machine, but from another web application I need to set mannyl teh header "Content-type: application/json".

It is not set by default to exposed, as per my understanding.

I would like to mention that this issue was raised only with good intentions. You may have a check and updated it if you finf it necessary.

![Unbenannt](https://user-images.githubusercontent.com/11800340/94729987-3590d400-036b-11eb-9597-efe2ebfa4b6d.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the input. Hopefully this will help someone else using IIS like you. This doc is not about IIS so we won't add it for now.

**Comment by LiviuSosu** [comment]
As you wish. But you have the following sections in your documentation.

_CORS in IIS
When deploying to IIS, CORS has to run before Windows Authentication if the server isn't configured to allow anonymous access. To support this scenario, the IIS CORS module **needs to be installed** and configured for the app._

No it does not. and the link will download an executable that will look for something that is no longer available.

Also,

_Set the exposed response headers
By default, the browser doesn't expose all of the response headers to the app. For more information, see W3C Cross-Origin Resource Sharing (Terminology): Simple Response Header.

The response headers that are available by default are:

Cache-Control
Content-Language
Content-Type
Expires
Last-Modified
Pragma__

 I had to "Content-Type" add it explicitly.

**Comment by Rick-Anderson** [comment]
> The response headers that are available by default are:

It doesn't say it always sends them, it must be able to determine the type.

> When deploying to IIS, CORS has to run before Windows Authentication if the server isn't configured to allow anonymous access.

You've done all the following:

* Deployed app to IIS
* Require Windows authentication
* Do not allow anonymous

?

**Comment by LiviuSosu** [comment]
I deployed to IIS.
Windows Authentification is disabled, as I do not need it,
I Some requests like logn need to allow anonymous.

The German message says: Microsoft-Webplatffform-Installer could not find the Product, that you tried to install. The link that you clicked its either incorrect, or you may overide your feed with another.

I think the link dor downloading the IIS Module is broken, but I didn't need it. It worked without it.

**Comment by shirhatti** [comment]
I just verified that the WebPI link for the IIS CORS module does indeed work.

If you're having issues with that link, I'd recommend installing the CORS module from the direct link listed on the page instead.
- x86 installer- https://go.microsoft.com/fwlink/?linkid=862443
- x64 installer- https://go.microsoft.com/fwlink/?linkid=862444

**Comment by shirhatti** [comment]
Closing. Feel free to re-open if the issue persists.
