### ISSUE TITLE
The sample should use IAsyncDisposable instead of IDisposable

### ISSUE THREAD

**Issue by meziantou** [dotnet/AspNetCore.Docs#20055]
Blazor supports `IAsyncDisposable` in .NET 5. I think the sample in the section "Add Razor component code for chat" should be updated to use this interface.

````
@implements IAsyncDisposable

    public ValueTask DisposeAsync()
    {
        return hubConnection.DisposeAsync(); // or await ...
    }
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @meziantou.

@BrennanConroy, do you concur with @meziantou's suggestion?

**Comment by BrennanConroy** [comment]
Yep, 5.0+ only
