### ISSUE TITLE
How to prevent reflected XSS with javascript-uri

### ISSUE THREAD

**Issue by SecTex** [dotnet/AspNetCore.Docs#20066]
Add a section with explanation on how to prevent the following xss case:

Index.cshtml:
```html
//...
<a href="@Model.ReturnUrl">Return to ...</a>
//...
```
Index.cshtml.cs:
```cs
public class IndexModel : PageModel {
        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }
}
```
URL:
```
/Index?ReturnUrl=javascript:alert(0)
/Index?ReturnUrl=j&#X41vascript:alert('test2')
...
```

I dont know if the following approach is correct here or if there is any (easier) solution:
Index.cshtml
```html
//...
<form method="post">
        <input name="ReturnUrl" value="@Model.ReturnUrl" />
        <button type="submit">Return to ...</button>
</form>
//...
```
Index.cshtml.cs:
```cs
public class IndexModel : PageModel {
        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }

        public void OnPost()
        {
            LocalRedirect(ReturnUrl);
        }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  please review

**Comment by blowdart** [comment]
This seems an odd use case, why would someone do such a thing?

**Comment by SecTex** [comment]
I don't know the specific use case, I just found the code in another open source project and was curious how to fix this.
One use case that would come to mind would be a login-page (`auth.example.com`) displaying a link to redirect back to the original host (`application.example.com`). I'm not saying this is the right way to do, just curious if there is a way to fix this.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
