### ISSUE TITLE
need a new page: "Troubleshooting connection issues"

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20063]
per @BrennanConroy  in #20056

I think we need a new page: "Troubleshooting connection issues" and contain more general information about possible errors.
These errors aren't necessarily specific to the javascript client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/AspNetCore.Docs/pull/20125
