### ISSUE TITLE
Redirect (go.microsoft.com) to over-posting section is broken

### ISSUE THREAD

**Issue by sbol-coolblue** [dotnet/AspNetCore.Docs#20087]
In the scaffolding for Controllers, a warning is included in the HttpPost endpoint:
```
// To protect from overposting attacks, enable the specific properties you want to bind to, for
// more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
```
https://go.microsoft.com/fwlink/?linkid=2123754 redirects to https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#over-post 

The actual document fragment it should point to is now called "#prevent-over-posting-1". Following the permalink results in the user landing at the top of the page, instead of the section of the tutorial about overposting.

Suggested fix: either update go.microsoft.com to point to the correct document fragment instead (that's why you have permalinks, right?), or update the scaffolding to point to a new permalink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio#over-post)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sbol-coolblue  thanks, it's fixed now

**Comment by seantleonard** [comment]
@Rick-Anderson The link is broken again, however the link exists within the code snippets in the Prevent Overposting section.
 
Existing go.microsoft link forwards to: `https://docs.microsoft.com/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio#over-post`
The new link should be: `https://docs.microsoft.com/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio%22#prevent-over-posting`

**Comment by Rick-Anderson** [comment]
`https://docs.microsoft.com/aspnet/core/tutorials/first-web-api#prevent-over-posting` is the correct without all those query strings
