### ISSUE TITLE
Broken GitHub Links

### ISSUE THREAD

**Issue by ShahJe** [dotnet/AspNetCore.Docs#20081]
Links to Virtualize samples are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor component virtualization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ShahJe ... The product unit just removed that code yesterday on https://github.com/aspnet/samples/pull/63. I'll fix it up right now.

**Comment by captainsafia** [comment]
@guardrex Woop! Didn't realize there were links to that sample. Thanks for addressing.
