### ISSUE TITLE
Issue with tutorial

### ISSUE THREAD

**Issue by grahamharris1975** [dotnet/AspNetCore.Docs#20088]
What about creating the app via Visual Studio? Why use the command line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @grahamharris1975 ... It was decided by management to make the experience dead-simple with no additional downloads required. You're welcome, of course, to use VS of any flavor or VS Code, but we'll leave this topic in this format per management's decision.
