### ISSUE TITLE
DbInitializer only seeding one table and not the others

### ISSUE THREAD

**Issue by LayersOfAbstraction** [dotnet/AspNetCore.Docs#20080]
DbInitializer is only seeding Students table and not the others.

In DbInitializer.cs I notice you are checking for Students, like this.

`
	if (context.Students.Any())
	{
		return;   // DB has been seeded
	}
`

But you are not doing it for the other tables you are creating which in turn will not populate them with any data. Only Students. Was that on purpose or did I mess something up on my end? I do it like this and it works for me.

`
	if (context.Students.Any() && context.Courses.Any() && context.Enrollments.Any())
	{
		return;   // DB has been seeded
	}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.2#initialize-db-with-test-data)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, keep reading
