### ISSUE TITLE
Adding API info runtime error

### ISSUE THREAD

**Issue by MattBH** [dotnet/AspNetCore.Docs#20089]
Following the tutorial and it worked up until I tried to customize the document info:

```
services.AddSwaggerDocument(config =>
{
    config.PostProcess = document =>
    {
        document.Info.Version = "v1";
        document.Info.Title = "ToDo API";
        document.Info.Description = "A simple ASP.NET Core web API";
        document.Info.TermsOfService = "None";
        document.Info.Contact = new NSwag.OpenApiContact
        {
            Name = "Shayne Boyer",
            Email = string.Empty,
            Url = "https://twitter.com/spboyer"
        };
        document.Info.License = new NSwag.OpenApiLicense
        {
            Name = "Use under LICX",
            Url = "https://example.com/license"
        };
    };
});
```

Which throws the following error in the Chrome Console:
`swagger-ui-bundle.js:2 TypeError: Failed to construct 'URL': Invalid base URL`

![image](https://user-images.githubusercontent.com/4545960/94937432-90c2e380-049d-11eb-8e64-dca8fd47fc22.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to #16879

What's the base URL - that looks like a pretty good error message.

**Comment by MattBH** [comment]
Chrome URL: https://localhost:5001/swagger/index.html. 

I'm not sure how to check what it's configured as in the NSwag middleware?

**Comment by blomm** [comment]
The error message does not help with the solution, which is to replace AddSwaggerDocument() with AddOpenApiDocument()

**Comment by Rick-Anderson** [comment]
Moved to  Container issue for NSwag #16879
