### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by MarcelGosselin** [dotnet/AspNetCore.Docs#20102]
I believe there is a missing dash `-` before `p:` in the first item in the list below.
>
MSBuild properties can be passed using either of the following formats:
* p:\<NAME>=\<VALUE>
* /p:\<NAME>=\<VALUE>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sayedihashimi let me know if it should be `-p:<NAME>=<VALUE>` and I'll update the doc.

**Comment by sayedihashimi** [comment]
@Rick-Anderson yes, it should have -

**Comment by Rick-Anderson** [comment]
Thanks @sayedihashimi  I'll fix this.
