### ISSUE TITLE
Remove references to IdentityServer4 in .Net 5 docs

### ISSUE THREAD

**Issue by spasecookee** [dotnet/AspNetCore.Docs#20106]
IdentityServer4 support and development [will be discontinued](https://leastprivilege.com/2020/10/01/the-future-of-identityserver/) along with the EOL of .NetCore 3.1. For .Net 5, IdentityServer is becoming a commercial product requiring a paid license, except for use by OSS developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
Identity server will still be part of the .NET 5 documentation, and your understanding of their licensing for the .NET 5 is incorrect. NET 5's lifetime will, in fact, end before 3.1. The current version of Identity Server 4 will run on .NET 5.

This is not an issue.
