### ISSUE TITLE
Is AddDbContextFactory compatible with Identity in .NetCore 3.1 & Blazor

### ISSUE THREAD

**Issue by CGuthrie72** [dotnet/AspNetCore.Docs#20101]
[Enter feedback here]
I've successfully used AddDbContextFactory in a project without Identity which works great.  However in one with Identity I get exceptions on startup:

InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser] Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory`1[Microsoft.AspNetCore.Identity.IdentityUser]': Unable to resolve service for type 'AV.OMS.DALInterfaces.Models.OmsDbContext' while attempting to activate 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9[Microsoft.AspNetCore.Identity.IdentityUser,Microsoft.AspNetCore.Identity.IdentityRole,AV.OMS.DALInterfaces.Models.OmsDbContext,System.String,Microsoft.AspNetCore.Identity.IdentityUserClaim`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserRole`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserLogin`1[System.String],Microsoft.AspNetCore.Identity.IdentityUserToken`1[System.String],Microsoft.AspNetCore.Identity.IdentityRoleClaim`1[System.String]]'.

Startup has:
  services.AddDbContextFactory<OmsDbContext>(opt =>
                opt.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))
                .EnableSensitiveDataLogging());

// instead of
 //services.AddDbContext<OmsDbContext>(options =>
            //    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")),
            //    ServiceLifetime.Transient
            //    );

services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<OmsDbContext>();

So can you indicate if Identity is compatible with using AddDbContextFactory ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
@JeremyLikness ... Thoughts on this one? ... or do you want to move it to an engineering repo for further investigation?

**Comment by CGuthrie72** [comment]
Hi guys, I received a response on StackOverflow from Jason Furr with the following solution:

        services.AddDbContextFactory<ApplicationDbContext>(options =>
        {
            options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
            options.EnableSensitiveDataLogging();
        });

        services.AddScoped<ApplicationDbContext>(p => p.GetRequiredService<IDbContextFactory<ApplicationDbContext>>().CreateDbContext())


https://stackoverflow.com/questions/64169025/using-identity-with-adddbcontextfactory-in-blazor


Regards, Craig

**Comment by guardrex** [comment]
Thanks @CGuthrie72 ... We'll see if Jeremy wants to reflect that in the doc.

I'm going to perform a quick touch-up edit to your post to code-fence the code and drop the extra text. :point_up:

**Comment by guardrex** [comment]
[EDIT by guardrex to add a code block and drop extra text]

Hi guys, I received a response on StackOverflow from Jason Furr with the following solution:

```csharp
services.AddDbContextFactory<ApplicationDbContext>(options =>
{
    options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
    options.EnableSensitiveDataLogging();
});

services.AddScoped<ApplicationDbContext>(p => 
    p.GetRequiredService<IDbContextFactory<ApplicationDbContext>>().CreateDbContext())
```

https://stackoverflow.com/questions/64169025/using-identity-with-adddbcontextfactory-in-blazor

Regards, Craig

**Comment by JeremyLikness** [comment]
@guardrex that looks fine if we want to call it out for identity server. The only caveat is the "EnableSensitiveDataLogging" - that is only if you want detailed logs and is a security risk with identity as it may expose passwords and other information when it logs the SQL statements.

**Comment by guardrex** [comment]
Thanks ... I'll schedule this and get to it as soon as I can. It might take a few days or a week to reach it. I'm **_BURIED_** ⛰️⛏️ in Blazor WASM security at the moment! 😨

**Comment by CGuthrie72** [comment]
You’re also creating some great stuff.

Regards, Craig
