### ISSUE TITLE
This page is also linked from 'Built-in components > Title' 

### ISSUE THREAD

**Issue by iadaz** [dotnet/AspNetCore.Docs#20118]
Under the list of built-in components is a link for "Title". But it links to https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios which appears to be an unrelated page which has a ToC entry under 'Fundamentals > Additional Scenarios'.

![image](https://user-images.githubusercontent.com/6428165/95191815-31304500-07c9-11eb-86de-7db5c8e083e2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc56d254-09c5-993b-2559-76af9a3f97ed
* Version Independent ID: a0bb183f-7e4d-ba39-c94c-cf60e951c7a9
* Content: [ASP.NET Core Blazor hosting model configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report @iadaz ... I'll take a look.

**Comment by guardrex** [comment]
@iadaz ... This is a point-in-time problem before we reach .NET 5 GA. We don't have a way to version the sidebar ToC. Therefore, a link there for .NET 5 preview content will appear to go **_nowhere_** 😨. If you flip that doc over to the .NET 5 preview version, you'll get the content ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-5.0#influence-html-head-tag-elements

I've thought about placing a ToC update in to address the entries where each .NET 5 feature would have something like "(.NET 5 Preview)" after the entry; but we're so close to .NET 5 GA, that I think we can probably leave it. Although I think we can wing it this time, I think next time (5.1? ... 6.0 if I'm still around) we should have a cue like that on the entries.

**Comment by guardrex** [comment]
🤔 ...... I'll keep an 👂 open for more feedback. If more devs hit this, then I will go ahead and put that cue on the entries for .NET 5. Let's see how it goes.

Thanks again for writing in on it.

**Comment by guardrex** [comment]
btw @scottaddie ... I suppose that another way to go would be to specify the version of the loaded doc with the query string param ...

```
?view=aspnetcore-5.0
```

... my concern there is that we would be switching the version **_without the reader knowing/noticing_** ... we may generate a worse problem than we currently have.

I think for now let's keep going. We're getting close to release. I'll just let devs know what to do when this happens for now.
