### ISSUE TITLE
Outdated code sample in "Configure ASP.NET Core Data Protection"

### ISSUE THREAD

**Issue by krish-gh** [dotnet/AspNetCore.Docs#20112]
This page is not updated to use code as per new SDKs as mentioned in the beginning of the document.
Azure.Extensions.AspNetCore.DataProtection.Blobs
Azure.Extensions.AspNetCore.DataProtection.Keys

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@krish-gh  thanks for notifying us. Would you be able to provide a PR to fix this? I can help.

**Comment by krish-gh** [comment]
@Rick-Anderson sure, I will raise a PR tommorrow.

**Comment by krish-gh** [comment]
Fixed with pull #20329
