### ISSUE TITLE
Kestrel without reverse proxy

### ISSUE THREAD

**Issue by FrankAtHexagon** [dotnet/AspNetCore.Docs#20114]
Good afternoon!

I have a question regarding Kestrel and reverse proxies. The Microsoft Docs article _Kestrel web server implementation in ASP.NET Core_ has the following text:
> Even if a reverse proxy server isn't required, using a reverse proxy server might be a good choice.

Several folks I have interacted with have interpreted this to mean 'Kestrel should not be used without a reverse proxy in production.' Is this a correct interpretation?

Common feedback I'm hearing is that IIS should instead be used to host ASP.NET Core apps directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@FrankAtHexagon no, we would say that if it was true. The doc lists the reasons for that statement.

**Comment by FrankAtHexagon** [comment]
Awesome, thanks for your help.
