### ISSUE TITLE
[Authorize] attribute as stated above is not anonymous, unauthenticated access. I think this statement is wrong.  It only indicates non demanding a particular role. Authentication is enforced by the request pipeline.

### ISSUE THREAD

**Issue by tauqirghani** [dotnet/AspNetCore.Docs#20129]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What statement are you talking about?

`    [AllowAnonymous] ` does allow anonymous

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
