### ISSUE TITLE
Add NO_PROXY environment variable to Blazor Debugging Troubleshooting section

### ISSUE THREAD

**Issue by AdrianSanguineti** [dotnet/AspNetCore.Docs#20127]
In a corporate environment, users may have a HTTP proxy server set via the `HTTP_PROXY` and/or `HTTPS_PROXY` environment variables. We have found that if `localhost` has not been added as a value to the `NO_PROXY` environment variable, the Blazor debugger may fail to start, especially if the HTTP proxy server requires authentication.

Can this information be added to the Troubleshooting section of the Blazor Debugging documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's sounds a bit *edgy-ish* to me :smile:, but let's ask @captainsafia about it.

**Comment by AdrianSanguineti** [comment]
I agree its a bit _edgy-ish_ but due to the unhelpful error message thrown when the debugger fails to start:

> One or more errors occurred.
>
> Failed to launch debug adapter. Additional information may be available in the output window.
>
> Exception of type 'Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.ProtocolException`

With not much more useful information included in the VS debugger log file to indicate what was happening, I feel some troubleshooting hints to check HTTP proxy settings would be helpful. We spent 2 days bagging our heads against the wall trying figure out what was causing the debugger to not start, not realizing that the debugger requests were being erroneously redirected to the HTTP proxy.

**Comment by captainsafia** [comment]
Thanks for bringing this up, @AdrianSanguineti!

Agree this is a little edgy-ish. However, I'm actually in favor of adding these docs to the debugging page. I think we've had a few users report this issue over on the aspnetcore repo so it'll help reduce our triage burden if we have it documented somewhere.

**Comment by guardrex** [comment]
@AdrianSanguineti ... Do you want to open a PR against the doc and add the base content?

**Comment by AdrianSanguineti** [comment]
Thanks,

>I think we've had a few users report this issue over on the aspnetcore repo so it'll help reduce our triage burden if we have it documented somewhere.

Those reports are exactly what made us realize our mistake, which is why I'm suggesting this. So good to see you agree!

@guardrex, unfortunately for the same reasons why I'm behind a HTTP proxy (corporate environment), I unable to clone a github repository right now. Our organisation's security only lets us access github from workstation that we can't use any DEV tools on, but only from the browser, which is why I can raise this issue. 

I know it's stupid, but unfortunately that the situation I'm in, with the result being that all .NET Core development has been 20 times harder than it should be due to poor handling of HTTP proxy at the framework level since the sockets code was made cross platform, especially when it comes to proxies that uses Windows Authentication.

It therefore might be a couple of days before I'm in a position where I'm in a location where I can clone the repo to make the change and have the time to do so.

**Comment by guardrex** [comment]
You don't need to do that. Select the pencil icon link on the live topic. You can edit the topic directly on a branch created for you and submit the PR that way.

<img width="728" alt="Capture" src="https://user-images.githubusercontent.com/1622880/95267987-0dd2bd80-07fc-11eb-9073-fd546b12c112.PNG">

**Comment by guardrex** [comment]
Just provide a few sentences in a new bullet point in that section that you think would've saved you in this scenario. We'll edit it from there.

**Comment by AdrianSanguineti** [comment]
@guardrex, thanks - I did not know that was possible now, (or haven't really paid attention enough). I've add some base content.
