### ISSUE TITLE
can't start hub connection

### ISSUE THREAD

**Issue by AymanMubark** [dotnet/AspNetCore.Docs#20130]
[Enter feedback here]

---
#### Document Details
blazor.webassembly.js:1 WASM: ﻿Unhandled exception rendering component:
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM: System.NotImplementedException: Cannot invoke method because it was wiped. See stack trace for details.
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClientHandler.Dispose (System.Boolean disposing) <0x2248578 + 0x00006> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpMessageHandler.Dispose () <0x22483e8 + 0x00008> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.DelegatingHandler.Dispose (System.Boolean disposing) <0x22484a0 + 0x0002e> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpMessageHandler.Dispose () <0x22483e8 + 0x00008> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.DelegatingHandler.Dispose (System.Boolean disposing) <0x22484a0 + 0x0002e> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpMessageHandler.Dispose () <0x22483e8 + 0x00008> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpMessageInvoker.Dispose (System.Boolean disposing) <0x2248310 + 0x0002e> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpClient.Dispose (System.Boolean disposing) <0x2241c30 + 0x00040> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Net.Http.HttpMessageInvoker.Dispose () <0x2241ae8 + 0x00008> in <e70b36886e7e4dc58fe28561030dc516>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.DisposeAsyncCore () <0x2241660 + 0x0021c> in <de08f9fa6cb44734a391f1a0509ccf4c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () <0x2231810 + 0x00026> in <de08f9fa6cb44734a391f1a0509ccf4c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.DisposeAsync () <0x2240db0 + 0x000de> in <de08f9fa6cb44734a391f1a0509ccf4c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync (System.Net.EndPoint endPoint, System.Threading.CancellationToken cancellationToken) <0x20ecdd8 + 0x00298> in <de08f9fa6cb44734a391f1a0509ccf4c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2242a10 + 0x0002c> in <e3f87ddffc9541298e1692f6027ea9f6>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore (System.Threading.CancellationToken cancellationToken) <0x20e2dd0 + 0x0010a> in <bc2d0813d9da4878975b99b042eba12c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner (System.Threading.CancellationToken cancellationToken) <0x20d4fd0 + 0x002ea> in <bc2d0813d9da4878975b99b042eba12c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult () <0x2242c08 + 0x00026> in <bc2d0813d9da4878975b99b042eba12c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync (System.Threading.CancellationToken cancellationToken) <0x20d15f0 + 0x000fa> in <bc2d0813d9da4878975b99b042eba12c>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at QBandWeb.Pages.Index.OnInitializedAsync () <0x1fdb028 + 0x0013e> in <cab58ac1be5b4861a18cda97c442e1df>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x1ed4ed8 + 0x0014c> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 
h.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x21d23b0 + 0x000c2> in <cbf249d7f04d4fa18d15bfae8ef7f389>:0 

using Microsoft.AspNetCore.Components.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace QBandWeb
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IComponentsApplicationBuilder app)
        {
            app.AddComponent<App>("app");
        }
    }
}

@page "/"
@inject NavigationManager NavigationManager
@using Microsoft.AspNetCore.SignalR.Client
@implements IDisposable

<div class="form-group">
    <label>
        User:
        <input @bind="userInput" />
    </label>
</div>
<div class="form-group">
    <label>
        Message:
        <input @bind="messageInput" size="50" />
    </label>
</div>
<button @onclick="Send" disabled="@(!IsConnected)">Send</button>

<hr>

<ul id="messagesList">
    @foreach (var message in messages)
    {
        <li>@message</li>
    }
</ul>

@code {
    public HubConnection hubConnection;
    private List<string> messages = new List<string>();
    private string userInput;
    private string messageInput;

    protected override async Task OnInitializedAsync()
    {
        hubConnection = new HubConnectionBuilder()
            .WithUrl("https://localhost:5004/chatHub")
            .Build();

        hubConnection.On<string, string>("ReceiveMessage", (user, message) =>
        {
            var encodedMsg = $"{user}: {message}";
            messages.Add(encodedMsg);
            StateHasChanged();
        });

        await hubConnection.StartAsync();
    }

    Task Send() =>
        hubConnection.SendAsync("SendMessage", userInput, messageInput);

    public bool IsConnected =>
        hubConnection.State == HubConnectionState.Connected;
        
    public void Dispose()
    {
        _ = hubConnection.DisposeAsync();
    }
}

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.HttpClient" Version="3.1.0-preview4.19579.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.1.0-preview4.19579.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.1.8" />
    <PackageReference Include="System.Net.Http.Json" Version="3.2.1" />
  </ItemGroup>

</Project>

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AymanMubark ...

Please open an issue with the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... and btw ... to code-fence your code examples, use triple backticks above and below the code block. See :point_right: https://docs.github.com/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks
