### ISSUE TITLE
ASP.NET Core Blazor hosting models SEO

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20142]
The current title is not great for SEO. Consider some of the following:

* ASP.NET Core Blazor client and server hosting
* ASP.NET Core Blazor hosting using WebAssembly (client-side) and Blazor server

> The principal hosting model for Blazor is running client-side in the browser on WebAssembly

What does principal  mean? Recommended ?  If so,, maybe

We recommend, when possible, hosting Blazor client-side in the browser using WebAssembly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.1#blazor-webassembly)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... I'll marked this on the tracking topic to make sure that it's addressed. I'm going to run down the ToC roughly in topic order, so it will be reached soon.
