### ISSUE TITLE
CORS Configuration not working

### ISSUE THREAD

**Issue by rawueest** [dotnet/AspNetCore.Docs#20145]
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1
The configuration as documented does not work in my eyes.

Two changes were necessary in our case:

 services.AddCors(options =>
            {
                options.AddPolicy(name: MyAllowSpecificOrigins,
                                  builder =>
                                  {
                                      builder.WithOrigins("http://foobar.com")
                                      **.SetIsOriginAllowed((host) => true)**
                                      .AllowAnyHeader()
                                      .AllowAnyMethod();
                                  });
            });

Secondly, 

**app.UseHttpsRedirection();**

had to come after app.UseCors(MyAllowSpecificOrigins);

https://stackoverflow.com/questions/59317789/trouble-with-cors-policy-and-net-core-3-1

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#cors-with-named-policy-and-middleware)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The configuration as documented does not work in my eyes.

You can test the configuration as documented. Use the deployed sample app at https://cors3.azurewebsites.net/

> `app.UseHttpsRedirection();`  had to come after `app.UseCors(MyAllowSpecificOrigins);`

That's not correct. See [Middleware order](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order)

> https://stackoverflow.com/questions/59317789/trouble-with-cors-policy-and-net-core-3-1

Although I was configuring CORS incorrectly 

The "actual" issue ended up being related to the SQL connection,
