### ISSUE TITLE
Prerendering Blazor WASM with Azure B2C

### ISSUE THREAD

**Issue by jonhilt** [dotnet/AspNetCore.Docs#20156]
Following the steps here about prerendering:

https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication

If you do this for a Blazor WASM app which is using MSAL with (in this case) Azure B2C..

**Client\Program.cs**
``` csharp
            builder.Services.AddMsalAuthentication(options =>
            {
                builder.Configuration.Bind("AzureAdB2C", options.ProviderOptions.Authentication);
                options.ProviderOptions.DefaultAccessTokenScopes.Add(
                    "https://xxxxxxx.onmicrosoft.com/<guid-here>/<scope-here>");
            });
```

Then register the relevant services in the Server project:
**Server\Startup.cs**
``` csharp
services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
services.AddScoped<SignOutSessionStateManager>();
```

All works perfectly until you try to log out, at which point you run into this error:

_InvalidOperationException: Cannot provide a value for property 'AuthenticationService' on type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorView'. There is no registered service of type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IRemoteAuthenticationService`1[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState]'_.

Would it be possible to clarify what the alternative is here. Presumably this is the service which takes care of logging out from Azure B2C via MSAL.

I wonder how we work around this to avoid errors when running the WASM app prerendered on the server.

Thanks :-)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-gb/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jonhilt ... I don't recall seeing this particular error. Open this issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please put a `cc: @guardrex` at the bottom of your opening comment so that I can follow the discussion. If it results in the need for a documentation update, I'll re-open this issue and work it from there.
