### ISSUE TITLE
Please include the AddDbContextFactory extension method!

### ISSUE THREAD

**Issue by kinetiq** [dotnet/AspNetCore.Docs#20150]
The documentation shows this code sample:

_The following example configures SQLite and enables data logging. The code uses an extension method to configure the database factory for DI and provide default options:_

```
services.AddDbContextFactory<ContactContext>(opt =>
    opt.UseSqlite($"Data Source={nameof(ContactContext.ContactsDb)}.db")
    .EnableSensitiveDataLogging());

```
I want to use this, it is extremely important, however without the extension method it's incomplete / not usable.

I did find the code here: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/3.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Data/FactoryExtensions.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Thank @kinetiq ... I'll cross-link that to surface it.

**Comment by JeremyLikness** [comment]
The download sample code link has the extension method.

**Comment by guardrex** [comment]
True, but I think he's saying that it isn't very discoverable that way. In the PR, I cross-link that bit of text to surface it without going to the extreme of placing it into the topic.

**Comment by guardrex** [comment]
An alternative is not to cross-link but to add an un-linked remark to 'see the sample app.' Do you think that would be better. I do have a bad feeling about linking to a specific version of code in topics and try to avoid doing it as much as possible.
