### ISSUE TITLE
generating jwt hosted updated

### ISSUE THREAD

**Issue by ghost** [dotnet/AspNetCore.Docs#20155]
duplicate of #9940

Hello,

Last time i checked there is a way to generate jwt by setting the signing keys.
below is a sample code

```

AsymmetricSigningKey myAsymmetricKey = new AsymmetricSigningKey(RSA.create());

            .AddJwtBearer(options =>
            {
                // Configure JWT Bearer Auth to expect our security key
                options.TokenValidationParameters =
                    new TokenValidationParameters
                    {
                        LifetimeValidator = (before, expires, token, param) =>
                        {
                            return expires > DateTime.UtcNow;
                        },
                        ValidateAudience = false,
                        ValidateIssuer = false,
                        ValidateActor = false,
                        ValidateLifetime = true,
                        IssuerSigningKey = myAsymmetricKey
                    };


```

questions:
1.) I am aware that you are migrating everything to identity server. but is there a way to recreate this without the complicated setup for identityserver? (because at the same time identity server is starting to become expensive)

2.) Is this fixed by .net 5?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by hoksource** [comment]
Took a while but i found some sample.

https://github.com/dotnet/aspnetcore/tree/master/src/SignalR/samples/JwtSample

Will wait for a response if this is safe to use. Ill use this for now. Feel free to close this when you want to.

**Comment by hoksource** [comment]
I would also like to know more about the
Microsoft.IdentityModel.Tokens.SymmetricSecurityKey
Microsoft.IdentityModel.Tokens.CryptoProviderFactory
Microsoft.IdentityModel.Tokens.Provider

I can't find the source code of the above files and i can't find sample codes on how to use them. I would like to use the pre existing algorithms on creating Json Web Signature. Not necessarily Jwt.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
