### ISSUE TITLE
There's no comprehensive example blazor wasm project with lazy loading

### ISSUE THREAD

**Issue by AlbrenDeyto** [dotnet/AspNetCore.Docs#20154]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690632ad-f357-161f-217b-faba56e90f36
* Version Independent ID: 626c5ed9-6424-7940-56e2-a19989b6de38
* Content: [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-lazy-load-assemblies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AlbrenDeyto ... I'll consider it, but I'm going to track it on the existing issue for updating the sample app. I'll mark that issue with a cross-link to this so that I won't lose your suggestion. Thanks for writing in on it.
