### ISSUE TITLE
Blazor File Upload

### ISSUE THREAD

**Issue by arvindram11** [dotnet/AspNetCore.Docs#20160]
Thanks for the article on File Upload in Blazor .net core 5 RC1.

Is there a way to restrict the number of files that the user can select (when multiple is set for an InputFile component)?  There is a way to process only "X" number of files when using the eventArgs.GetMultipleFiles, but when the user selects a large number of files (I tried about 300), the connection is lost on the browser to the server (it displays attempting to reconnect but then throws an exception).

Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.

I am trying with the Blazor Server (not Web Assembly) because we have dependencies on other .net libraries (third party) that don't appear to work well with WASM (get encoding errors when trying to use those in WASM).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @arvindram11 ... I don't think Blazor can do it directly, so you'd likely need to do it in JavaScript. That's a good question and possible feature suggestion for the product unit. Open this over on their repo at ...

https://github.com/dotnet/aspnetcore/issues
