### ISSUE TITLE
Link is 404

### ISSUE THREAD

**Issue by ahriman-ru** [dotnet/AspNetCore.Docs#20165]
An ASP.NET Core web API with Azure AD B2C link is 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdae773-368b-a0c1-64d0-2a7b8c8fb134
* Version Independent ID: 2816eb27-7fc5-19e6-7f79-7e81a388647f
* Content: [Microsoft identity platform and Azure Active Directory with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-active-directory/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/azure-active-directory/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-active-directory/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ahriman-ru  thanks for reporting this. Fix should go live in a few days. Check the PR if you need the link now.
