### ISSUE TITLE
wrong namespace in proto file

### ISSUE THREAD

**Issue by cantSleepNow** [dotnet/AspNetCore.Docs#20167]
`option csharp_namespace = "GrpcGreeterClient";`
should be changed to 
`option csharp_namespace = "GrpcGreeter";` 

- It's under the bulletpoint "Update the namespace inside the greet.proto file to the project's namespace:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by cantSleepNow** [comment]
alternatively Program.cs can be changed to use GrpcGreeterClient namespace - `using GrpcGreeterClient ;` instead of `using GrpcGreeter;`

**Comment by JunTaoLuo** [comment]
Yup this is a bug. I looked through the sample and it seems like the namespace is set to `GrpcGreeter` https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Protos/greet.proto#L3. 

However, I'd like to propose an alternative fix. Given that there is no reason `GrpcGreeter` and `GrpcGreeterClient` both needs to exist, we should just use one. In other words:

1. The md doc should stay as is and continue using `GrpcGreeterClient`
2. The proto file https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Protos/greet.proto should change to use the namespace  `GrpcGreeterClient`
3. The Program.cs file should remove the `using GrpcGreeter;` import statement. It's already in the `GrpcGreeterClient` namespace: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start/sample/GrpcGreeterClient/Program.cs#L8

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan let me know if you're interested.

**Comment by fiyazbinhasan** [comment]
Sure. I'll take a look at it

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson Already been fixed in https://github.com/dotnet/AspNetCore.Docs/pull/21732. We can close this issue.

**Comment by Rick-Anderson** [comment]
Thanks @fiyazbinhasan
