### ISSUE TITLE
Not able to Publish to Azure API Management through VisualStudio Community edition

### ISSUE THREAD

**Issue by SatyanarayanaMutyala** [dotnet/AspNetCore.Docs#20174]
Hi,

This Page was informative, but I am using Visual Studio Community Edition and I don't see any option to publish to API Management. I am able to do to App Service, but not Azure API Management. Is there a plug in I am missing to install or is that not part of community edition?

Thank,
Satya
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by sayedihashimi** [comment]
@AngelosP should be able to answer, he is the owner of web publish.

**Comment by AngelosP** [comment]
Thanks @sayedihashimi. I'm also tagging @bradygaster and @vijayrkn as well. 

The question is answered by this part of the guide:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-3.1#publish-the-aspnet-core-web-api-to-azure-api-management

> **from @SatyanarayanaMutyala:** This Page was informative, but I am using Visual Studio Community Edition and I don't see any option to publish to API Management.

[The guide](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-3.1#publish-the-aspnet-core-web-api-to-azure-api-management) has the steps numbered: 1, 2, 3, etc. can you please clarify which step is not working for you? Also please let us know what version of Visual Studio you are using.

Thank you
Angelos

**Comment by bradygaster** [comment]
Does the project you're publishing have a reference to the Swashbuckle.AspNetCore NuGet package? If it **does**, you should see the API Management publishing light up for you. It only lights up when you've referenced Swashbuckle, as that's how the Open API is generated.

**Comment by SatyanarayanaMutyala** [comment]
@bradygaster, I have used Swashbuckle.AspNetCore.SwaggerGen Nuget package to generate Open API doc and I am using Visual Studio 16.7.4 Community edition.

**Comment by Sam-Carson** [comment]
I believe I am having the same issue as Satya. At the step where it says to "Add an API to Azure API Management" it states that I am to "Open the API Management Service instance created previously in the Azure portal. Select the APIs blade". I read this as there will a window opening to Azure. I am not having anything pop up and when I manually go to the API Management Services in my browser, everything is different than what is illustrated in the tutorial. From this step forward I have no clue wat to do. I have SwashBuckle installed the way previously stated in the comments by bradygaster

**Comment by codemillmatt** [comment]
Hi @Sam-Carson - thanks for the feedback.

> Open the API Management Service instance created previously in the Azure portal.

Is referring to a step referenced in the prerequisites section, [Create a new Azure API Management Instance](https://docs.microsoft.com/en-us/azure/api-management/get-started-create-service-instance)

Nothing will pop up.

So this tells me the tutorial could be worded better.

**Comment by mpnow** [comment]
I'm having the same issue. Have a .NET Core 2.1 app. Swashbuckle 6.1.4 is installed:
![image](https://user-images.githubusercontent.com/2540658/121964823-1c358980-cd3a-11eb-9588-d3f3d1da7551.png)

When I go to publish (Visual Studio Community 16.9.4), there is no API Management option:
![image](https://user-images.githubusercontent.com/2540658/121965278-c6adac80-cd3a-11eb-8dd2-0a15ddeffe49.png)

**Comment by bradygaster** [comment]
We aspired to get 2.1 into it but with the [2 months left in the 2.1 LTS status](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/) we opted for 3.1 only. Can your app be upgraded to 3.1, which is also in LTS?

**Comment by mpnow** [comment]
> We aspired to get 2.1 into it but with the 2 months left in the 2.1 LTS status we opted for 3.1 only.

Ah, interesting, OK. Note that I specifically checked for that before posting, and found that the doc for 2.1 also showed it as being available there - you might want to fix that:
![image](https://user-images.githubusercontent.com/2540658/122321208-7b89ca00-cef1-11eb-8be6-bd5ef34e2ae6.png)

Unfortunately the app can't be upgraded; it's part of a larger system that's stuck on 2.1 for the time being. Oh well, I can of course still publish and update it from the Azure portal.

**Comment by bradygaster** [comment]
Ah that's a great catch - thanks for letting us know, I'll get that doc updated with help from @spboyer

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
