### ISSUE TITLE
'SchoolContext' does not contain a definition for 'Student'

### ISSUE THREAD

**Issue by LydiaCha** [dotnet/AspNetCore.Docs#20176]
I get this error when I try to run the app:

```
`html.cs(26,38): error CS1061: 'SchoolContext' does not contain a definition for 'Student' and no accessible extension method 'Student' accepting a first argument of type 'SchoolContext' could be found (are you missing a using directive or an assembly reference?)`

The build failed. Fix the build errors and run again.
```

The error is in
Create.cshtml.cs, Delete.cshtml.cs, Edit.cshtml.cs and Index.cshtml.cs where '`Student`' is. For example, Student in this line is underlined --> `_context.Student.Add(Student);`

I feel like I've copied-pasted everything so I'm not sure what the issue is.

This is the tutorial II'm following--> https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio-code

ASP.NET Core 3.1
On Mac, using VSCode.

Thanks,
Lydia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You're missing the step where your rename student I think. The tutorial does work.

**Comment by datttrian** [comment]
I believe The tutorial does work! The entity classes in SchoolContext.cs should be in singular form.

**Comment by datttrian** [comment]
I believe The tutorial does not work! The entity classes in SchoolContext.cs should be in singular form.
