### ISSUE TITLE
Hosting SignalR in worker serivce.

### ISSUE THREAD

**Issue by vijaykumarkolli** [dotnet/AspNetCore.Docs#20172]
[Enter feedback here]

is this example is applicable for web api, it will be good to have example or article which can explain on host SignalR in WorkerSerivce. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bbb2d1c-4dfe-3faf-d4b0-65ae1146961e
* Version Independent ID: 6b203f18-adfa-3a18-183d-b124325064c3
* Content: [Host ASP.NET Core SignalR in background services](https://docs.microsoft.com/en-us/aspnet/core/signalr/background-services?view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/background-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/background-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Hosting a SignalR Hub in a Worker Service is like hosting it in a Web Host, but you need to spin up the HTTP host, in which case it's just easier to use a Web Host anyway. We have an article on hosting a client - hosting a Hub is essentially the same as hosting a Hub in Web Host. Let us know if this fails to answer the question, closing for now.
