### ISSUE TITLE
ElementReference Validity

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#20195]
Is the following accurate, or is it also true that `ElementReference`s are valid any time after render?

> An ElementReference is only guaranteed valid in a component's OnAfterRender method 

I'm currently using an `ElementReference` in a function that's called when the user clicks something and haven't had any problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This remark came straight from the product unit, so I believe it's accurate. My understanding is that this guarantee exists because after that point the element ref might be lost clientside.

@pranavkm ... Do u think we need to say something like that or something else if the guarantee is lost due to some other factor?

**Comment by mrlife** [comment]
@guardrex Thank you. The main thrust of opening the issue was about `ElementReference` being valid during `OnAfterRender`  but also after that function has been called. Did we get an answer on that?

**Comment by guardrex** [comment]
> guaranteed valid

I still think it's because the DOM can mutate it after that point ...... but it shouldn't in most cases.

We'd need @pranavkm to confirm if that's correct.

**Comment by guardrex** [comment]
Now, I'm wondering if the original intent of that passage is to clarify that the element reference isn't guaranteed available **_until `OnAfterRender`_** ... looking at it from the other side. That interpretation lends itself to the following passage about not passing them between components.

Yeah ... we'll need some help to further clarify. I'll re-open and submit a new PR to improve it.

**Comment by guardrex** [comment]
Yes ... I slept on this 💤, and I think I'm right. There's this other passage that states it clearly ...

> The `exampleButton` variable [referring to an `ElementReference` for the example] is only populated after the component is rendered. If an unpopulated `ElementReference` is passed to JavaScript code, the JavaScript code receives a value of `null`. To manipulate element references after the component has finished rendering use the `OnAfterRenderAsync` or `OnAfterRender` component lifecycle methods.

I believe that's what "guaranteed" means in the prior context. Therefore, this will be easy to fix.

I have another PR for this topic ... I'll add the update to that ... and we'll have Safia put an :eye: on it.

**Comment by mrlife** [comment]
@guardrex https://github.com/dotnet/AspNetCore.Docs/pull/20236/commits/6ab73025baf77be5974461a34befd2e0d71ecb58 looks perfect!

> The instance is only guaranteed to exist after the component is rendered, which is during or after a component's OnAfterRender/OnAfterRenderAsync method executes.

**Comment by guardrex** [comment]
Yes ... I **_finally_** connected the dots from the other remarks. Sometimes the content arrives from the product unit and goes straight in with **_assumed understanding_** of what a phrase or sentence means. This was a case where things went badly until you asked about it. Your issue [and persistence after my first (failed) attempt] was critical to getting it fixed. Thank you again for your issue. 🎷
