### ISSUE TITLE
Make `services.AddMemoryCache()` aspect more visible

### ISSUE THREAD

**Issue by efrainsteinbach** [dotnet/AspNetCore.Docs#20191]
Please make it a bit more apparent that one may need to add `services.AddMemoryCache();` for this whole thing to work. 
I.e. I suggest adding a short, dedicated section for that bullet point in the end, that shows an example from `Startup.cs` - where you could actually set all this up. 

I _was_ expecting that I need to do this, but I didn't find it on the page first .. and only after 10mins of googleing, I found it at the very bottom of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#use-setsize-size-and-sizelimit-to-limit-cache-size)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's a side case when you need to call `services.AddMemoryCache();` and is documented correctly. We'll reconsider updating the doc should we get more requests.
