### ISSUE TITLE
Access to service provider when setting options?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/AspNetCore.Docs#20202]
Hi,

Is there a method to configure options with a delegate that gives access to the service provider?
For example:

```c#
services.AddTransient<ISettings, ...>();

services.Configure<MySettings>((serviceProvider) => 
{ 
  // setup MySettings with stuff from serviceProvider
});
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#options-interfaces)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I don't think so. cc @serpent5

**Comment by weitzhandler** [comment]
Or any alternative, that will allow late configuration or re-configuration, using the service-provider.

**Comment by Rick-Anderson** [comment]
Using the default configuration, the appsettings.json and appsettings.Environment.json files are enabled with reloadOnChange: true. Changes made to the appsettings.json and appsettings.Environment.json file after the app starts are read by the JSON configuration provider.

Many providers reloadOnChange

**Comment by weitzhandler** [comment]
My question is slightly different.

After having my options loaded from JSON, I need to add some options that are based on other registered services from the container.

Thanks for your comments!

**Comment by serpent5** [comment]
There's a section for this in the topic: [Use DI services to configure options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1#use-di-services-to-configure-options). You can inject `IServiceProvider` as one of the types, or just inject the services themselves.

**Comment by weitzhandler** [comment]
Thank you, that is perfect!
Does the `AddOptions` call also pre-load the options from jsonsettings?
