### ISSUE TITLE
Update 3.1-to-5.0 migration guide for ASP.NET Core 5.0 RC2

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#20201]
Update the following doc for RC2:
https://docs.microsoft.com/aspnet/core/migration/31-to-50

Incorporate details mentioned at https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-2/

**Comment by guardrex** [comment]
@scottaddie @Rick-Anderson ... Confirm if you still want me to handle the Blazor section of the file. :ear: I'm **_almost done_** with the Blazor .NET 5 updates 😁. I'll be available perhaps tomorrow (Friday) morning to work on it.

WRT timing ... Given that I would be touching sections not touched by other PRs (and if I leave the date alone), I don't think that any merge conflict :boom: will crop up (or be difficult to resolve if it happens). If you prefer that I hold off and work on the doc ... say ... this weekend ... *yeah*, I can do that. Let me know if you think I should wait until existing PRs are merged into it before doing the work. :ear:

**Comment by scottaddie** [comment]
@guardrex Yes, please work on the Blazor section. I'll work on the rest of it.

**Comment by guardrex** [comment]
btw --- I have 😈 **_one pesky Blazor WASM security scenario_** 😈 left to work out. I've asked Jean-Marc for a tip, but I also have a clue as to what might be wrong. Anyway ... my week is burned, so it will have to wait until Monday morning. I'll get to the Blazor updates for the migration topic for sure by EOD on Monday.
