### ISSUE TITLE
Lifecycle Images are too big

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#20209]
The component lifecycle images on this page are great, but they render really big. Is there any way to tighten them up so that the text in the images is roughly on the same scale as the text in the doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Last week, I worked on it ...

https://github.com/dotnet/AspNetCore.Docs/pull/20136/files#diff-901b5c1cb3df671cf6cf3a99588ef5d90ff0e9c760bbbd0aa0f97cdeceec70adR28

... the current tag is (for example) ...

```html
<img src="lifecycle/_static/lifecycle1.png" alt="xxxxxxxxxx" data-linktype="relative-path" 
    style="max-width:350px;display:block;margin:0 auto">
```

... and the build system isn't supposed to touch HTML, but it seems like the build system **_IS_** stripping out my `style` attributes ...

<img width="745" alt="Capture" src="https://user-images.githubusercontent.com/1622880/96194200-7cf09600-0f0f-11eb-81db-0df7376736a5.PNG">

I'll take another stab at it.
