### ISSUE TITLE
JwtSettings and Cookie Settings sections

### ISSUE THREAD

**Issue by peteralbanese** [dotnet/AspNetCore.Docs#20206]
Would be helpful if you specified an example of the JwtSettings and Cookie Settings sections of the json settings file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by vanillajonathan** [comment]
In the project's `appsettings.json` file you can put:
```json
{
  "JwtSettings": {
    "Audience": "audience",
    "TokenValidationParameters": {
      "IssuerSigningKey": "secret", // This will not be set
      "ValidateIssuerSigningKey": true,
      "ValidIssuers": ["abc", "def"]
    }
  }
}
```

However the `IssuerSigningKey` will not be set because it is of type `SecurityKey`, so if you need to set it, then you cannot bind directly to your configuration, you would have to do:
```cs
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.Audience = Configuration["Jwt:Audience"];
    options.TokenValidationParameters = new TokenValidationParameters
    {
        IssuerSigningKey =
            new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Jwt:IssuerSigningKey"])),
        ValidateIssuerSigningKey = true,
        ValidIssuers = Configuration.GetSection("Jwt:ValidIssuers").Get<IEnumerable<string>>()
    };
});
```

**Comment by Rick-Anderson** [comment]
You wouldn't put secrets in the the JSON file, but you could put them is a secure store and access them from configuration..

**Comment by vanillajonathan** [comment]
Indeed. My point was that you cannot bind the `IssuerSigningKey` with:
```cs
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
    Configuration.Bind("JwtSettings", options))
```

**Comment by Rick-Anderson** [comment]
@vanillajonathan  can you check my rewrite?

***Edit by @Rick-Anderson*** remove secret from `appsettings.json` file.

Set `JwtSettings:IssuerSigningKey` in a [secure store](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets)

In the project's `appsettings.json` file you can put:
```json
{
  "JwtSettings": {
    "Audience": "audience",
    "TokenValidationParameters": {
      "ValidateIssuerSigningKey": true,
      "ValidIssuers": ["abc", "def"]
    }
  }
}
```

However the `IssuerSigningKey` cannot be set in the JSON file because it is of type `SecurityKey`. The following code sets the `IssuerSigningKey`

```cs
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.Audience = Configuration["Jwt:Audience"];
    options.TokenValidationParameters = new TokenValidationParameters
    {
        IssuerSigningKey =
            new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["Jwt:IssuerSigningKey"])),
        ValidateIssuerSigningKey = true,
        ValidIssuers = Configuration.GetSection("Jwt:ValidIssuers").Get<IEnumerable<string>>()
    };
});
```

**Comment by vanillajonathan** [comment]
@Rick-Anderson Yeah, that is a better way to put it. I just wrote here to explain it to @peteralbanese and whoever might stumble upon it. For documentation purposes it should  be rewritten, I am sure it can be expressed in a more pedagogic way and with better prose (my explanation uses the word "you").

Option binding ought to be sufficient for uses cases where an `Authority` is used, but for use cases where a `IssuerSigningKey` is used, the configuration have to be declared with code.

**Comment by Rick-Anderson** [comment]
@mjrousos @blowdart  should this be added to the doc?

**Comment by blowdart** [comment]
Because it's not automatic in any way and you have to do it all yourself I don't know if it's necessary or not. Personally I wouldn't as it's not special, it's just like any other middleware with parameters where you decide to put some in config.
