### ISSUE TITLE
Dose this doc for .razor file?

### ISSUE THREAD

**Issue by ahdung** [dotnet/AspNetCore.Docs#20203]
I hope `.razor` file don't precompile too, how?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in the doc.

**Comment by ahdung** [comment]
@Rick-Anderson 
I don't think so, i want handle `.razor` file too.
![image](https://user-images.githubusercontent.com/12094247/96084578-e5307f00-0ef1-11eb-98f9-ad3fb1a9fac3.png)

**Comment by Rick-Anderson** [comment]
I'm guessing Razor components are treated the same as Razor file.

**Comment by Rick-Anderson** [comment]
@guardrex  who's the right resource to ask for Blazor prrojects.

**Comment by guardrex** [comment]
The Razor SDK doesn't act on Razor components. Runtime compilation (hot reload) is being considered for .NET 6 ...

* https://github.com/dotnet/aspnetcore/issues/25999
* https://github.com/dotnet/aspnetcore/issues/5456

For .NET 5, Blazor app developers can use `dotnet watch`.

**Comment by ahdung** [comment]
sad news. Thank you @guardrex @Rick-Anderson
