### ISSUE TITLE
Azure Key Vault Configuration Provider, code sample using deprecated packages

### ISSUE THREAD

**Issue by Hjortsberg** [dotnet/AspNetCore.Docs#20216]
The documentation for Azure Key Vault Configuration Provider has code samples showing how to get secret configurations loaded with Managed Identity but depends on [Microsoft.Azure.KeyVault](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/) which is deprecated.
Would appreciate an updated sample using the [new configuration packages](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets) which i guess is the replacement. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This started in a good way with ...

https://github.com/dotnet/AspNetCore.Docs/pull/20164

... but required more work. Idk why it was closed. Not everything that I mentioned in my remarks has to be done. The only thing is that the sample app will require the update along with the topic. That's the main thing. The rest is just some color on why one day the topic will probably need more work (i.e., the Azure portal vs. using Azure CLI commands).
