### ISSUE TITLE
Obsolete code example

### ISSUE THREAD

**Issue by ThomasPrioul** [dotnet/AspNetCore.Docs#20229]
The segment about localization using cookies tells to use "this.HttpContext", now the member is named Context, not HttpContext. (ASP .NET core 3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @ThomasPrioul ... I'll mark this for triage and get to it asap.

**Comment by guardrex** [comment]
@ThomasPrioul ... `Context` isn't available in the current context of either `PageBase` or `ControllerBase`. I can't repro a problem with what the topic shows in either case.

**Comment by ThomasPrioul** [comment]
Created a PR #20239 about what I meant.

**Comment by ThomasPrioul** [comment]
> 
> 
> @ThomasPrioul ... `Context` isn't available in the current context of either `PageBase` or `ControllerBase`. I can't repro a problem with what the topic shows in either case.

The member comes from the RazorPage class. The snippet is to be used in a .cshtml file

**Comment by guardrex** [comment]
The base class for a Razor page is `PageBase`. `_Host.cshtml` is based on `Microsoft.AspNetCore.Mvc.RazorPages.Page`, which is a `PageBase`.

I think we need two examples ... one for each of `PageBase` and `RazorPage` class. I'll modify your PR and ask Pranav to take a look.

**Comment by guardrex** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/20239.
