### ISSUE TITLE
aspnet-codegenerator razorpage Edit generates stacktrace

### ISSUE THREAD

**Issue by paolovalladolid** [dotnet/AspNetCore.Docs#20225]
I ran this command:

dotnet aspnet-codegenerator razorpage Edit Edit  -outDir Pages\Restaurants

I got this error:

Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Razor.RazorPageGeneratorTemplateModel2' does not contain a definition for 'ViewDataTypeShortName'
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:05.23

I also ran this command and got the same stack trace:
dotnet aspnet-codegenerator razorpage RestaurantEdit Edit  -outDir Pages\Restaurants

**Comment by guardrex** [comment]
Hello @paolovalladolid ... It's best if you use the **This page** feedback button and form at the bottom of an **English-US** topic to open new issues here. It will add metadata for the article and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by paolovalladolid** [comment]
> Hello @paolovalladolid ... It's best if you use the **This page** feedback button and form at the bottom of an **English-US** topic to open new issues here. It will add metadata for the article and automatically ping the author.
> 
> <img alt="Capture" width="404" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

Thanks, I thought that was what I did to get here but will try again

**Comment by guardrex** [comment]
You might have deleted the metadata when the issue opened. Leave it there, and the author of the topic will get the ping to respond.

**Comment by Rick-Anderson** [comment]
@paolovalladolid  please don't create duplicate issues.  #20226

**Comment by guardrex** [comment]
That was my fault @Rick-Anderson ... I didn't see the new issue open and then close this issue, and I didn't tell @paolovalladolid to close this either after creating the new issue. Sorry about that @paolovalladolid.
