### ISSUE TITLE
dotnet aspnet-codegenerator razorpage Edit template generates Stack Trace

### ISSUE THREAD

**Issue by paolovalladolid** [dotnet/AspNetCore.Docs#20226]
I ran this command:

dotnet aspnet-codegenerator razorpage Edit Edit -outDir Pages\Restaurants

I got this error:

Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
'Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Razor.RazorPageGeneratorTemplateModel2' does not contain a definition for 'ViewDataTypeShortName'
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.b__6_0()
at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:05.23

I also ran this command and got the same stack trace:
dotnet aspnet-codegenerator razorpage RestaurantEdit Edit -outDir Pages\Restaurants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/Scaffolding/issues/1432
