### ISSUE TITLE
Using untrusted input as part of a URL path

### ISSUE THREAD

**Issue by TobiDimmel** [dotnet/AspNetCore.Docs#20228]
In section [Encoding URL Parameters](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-3.1#encoding-url-parameters) it is warned about using untrusted input as part of a URL path. However it isn't said why this is problematic. Couldn't you just percent-encode the untrusted input?

In my research I couldn't find any resources that explain this either. And if I understand [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.3) and [RFC7230](https://tools.ietf.org/html/rfc7230#section-2.7) correctly the specs allow it as long as reserved characters are percent-encoded.

Could you please elaborate on the problem behind the warning or point me in the right direction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-3.1#encoding-url-parameters)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It states:

If you want to build a URL query string with untrusted input as a value use the UrlEncoder to encode the value. For example,

**Comment by TobiDimmel** [comment]
Yes, but in the warning box it states:

> Don't use untrusted input as part of a URL path. Always pass untrusted input as a query string value.

Hence, my question in regard to the URL **path**, not the query string.
