### ISSUE TITLE
Process Name for OutOfProcess hosting in ASP.Net Core 3.1

### ISSUE THREAD

**Issue by TheShaikhFaiyaz** [dotnet/AspNetCore.Docs#20220]
[Enter feedback here]
In ASP.Net Core 3.1, the process name is returned as application name instead of 'dotnet' for 'OutOfProcess' hosting model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#out-of-process-hosting-model)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shirhatti  please confirm and I'll get this fixed ASAP.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by gurucharan2206** [comment]
This could help:
https://stackoverflow.com/questions/62276413/why-do-i-see-project-directory-name-instead-of-dotnetout-of-process-while-runn

**Comment by transfomerdnn** [comment]
Thanks @gurucharan2206.
