### ISSUE TITLE
Issue with Client proto instructions and csharp_namespace

### ISSUE THREAD

**Issue by kmauzoul** [dotnet/AspNetCore.Docs#20230]
Hello Team,

The tutorial says to update the csharp_namespace within the proto file to "GrpcGreeterClient" after copying the proto from the Server project to the client.  This does not match with the "Program.cs" contents as the using directive says "GrpcGreeter" (which would be valid if the tutorial didn't instruct readers to change the csharp_namespace).  As well, the sample project should also reflect this.

First time users may stumble at this point and not understand why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
Dup of  #20167
