### ISSUE TITLE
Serve default documents section should be changed for clarity

### ISSUE THREAD

**Issue by LepomisGibbosus** [dotnet/AspNetCore.Docs#20233]
[Serve default documents](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files#serve-default-documents)  should be clarified regarding serving default documents.

The language in the documentation uses the concept of "a fully qualified URI". However, no definitive explanation of a fully qualified URI or URL can be found easily on the web. Concepts like a fully-qualified domain name, absolute URI, relative URI yes but that of a fully qualified URI ? No.

The documentation should either provide a definition for a "fully qualified URI" or change the language so the concept is clearer and easily understood. Consider this quote from _Professional Microsoft IIS 8_

> IIS uses default documents to determine which file to serve when a site (/) or directory (/folder/) is requested and no explicit filename is specified. 

That example explains the concept of serving default documents while being easily understood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://stackoverflow.com/questions/17406848/what-is-the-definition-of-an-absolute-url-fully-qualified
