### ISSUE TITLE
Use DBcontext in blazor webassembly 

### ISSUE THREAD

**Issue by NaserParhizkar** [dotnet/AspNetCore.Docs#20245]
Hi guy.
I want to use context in Blazor web assembly exactly like in Blazor server side
without any limitation.
 
```
Context = DbFactory.CreateDbContext();
        Contact = await Context.Contacts
            .SingleOrDefaultAsync(c => c.Id == ContactId);
```

Does it possible right now by latest version of EF Core or Blazor web assembly?
I saw 'BlazorWasmEFCoreExample' link on your git page but I want to work directly with DbContext and manage all things 
like tracking or others on Blazor web assembly.
Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by JeremyLikness** [comment]
That is not possible. The only database accessible from your browser via Web Assembly is Azure Cosmos DB using the HTTPS proxy, and then only if you make sure you don't store credentials and use temporary tokens for access. SQLite may be an option in the future, but the other databases all require ports and protocols that are prohibited in the browser security sandbox.
