### ISSUE TITLE
Clarify connection between Controller class name and URL

### ISSUE THREAD

**Issue by sethpeasley** [dotnet/AspNetCore.Docs#20258]
Overall a good tutorial so far. However, I've been on an immensely frustrating quest for over 30 minutes trying to understand how the name of the controller class corresponds to the URL. I cannot anywhere find definite documentation that says the name of the controller is converted to the path. It obviously is, I've experimented with a number of variants of `HelloWorldController` and whatever is written before the word "Controller" is converted to the URL. However, this is not documented anywhere from what I can tell. 

Please clarify the connection between the Controller Class name and the URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-5.0#set-up-conventional-route

**Comment by sethpeasley** [comment]
Thanks for the reply. However, the document you shared does not explicitly state how the the sequence of characters in the [Controller] portion of the route shall match (map) to the sequence of characters preceding the word 'Controller' in the controller class name. Yes, it's in bold in the example you show  (**HelloWorld**Class), but bolding is just formatting. The documentation should be much more clear about the connection between the two sequences of characters. Are there additional rules on the matching? Is it case-sensitive?
