### ISSUE TITLE
Parent-to-child binding example: EventCallback confusing/not needed.

### ISSUE THREAD

**Issue by mdekok** [dotnet/AspNetCore.Docs#20263]
In the paragraph 'Parent-to-child binding with component parameters' the use of YearChanged EventCallback is confusing because it's not needed to let the updated year flow down to the child element, what the example tries to show. Setting <Child Year="year" /> is enough to show updated years in the child.

If in the Child component editing the year is made possible, using the EventCallback would make sense. But this is shown in the paragraph following (Child-to-parent binding) in another example concerning editing of a password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I agree @mdekok ... and I'm upset about the last round of updates, which has made this content worse in some ways (e.g., headings and examples). I greatly appreciate your feedback and patience.

@captainsafia ... May I have your help to sort this out on the PR? AFAICT ...

* The first heading should just be *Bind to a property* ... or something along those lines with a simple example that performs a `@bind` to a property in a single component.
* The two component examples here across these two sections should be chained bind examples. The first one being a simple example, while the second one is more complex. The first example needs to invoke the delegate, either ...

  ```csharp
  private Task Update()
  {
      return YearChanged.InvokeAsync(...);
  }
  ```

  ... or ...

  ```csharp
  private async Task Update()
  {
      await YearChanged.InvokeAsync(...);
  }
  ```

I'll put up the PR now and we can resolve this ... hopefully **_once and for all_**. I'll ping on the PR.
