### ISSUE TITLE
"Blazor logging " content missing

### ISSUE THREAD

**Issue by davelobban** [dotnet/AspNetCore.Docs#20264]
The linked content from 
```
For information on Blazor, see Create logs in Blazor and Blazor WebAssembly in this document.
```
is missing. I can't see any Blazor-specific logging content. Where should I be looking?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#clib)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @davelobban ... Did you change the document version to `5.0 Preview` with the drop down in the upper left-hand corner of the page?

**Comment by guardrex** [comment]
Let me check ... given where this link is coming from ... I think we might have a broken bookmark here. I'll get back to you shortly.

**Comment by guardrex** [comment]
**Indeed!** .... the 🧀 moved and the link wasn't found/changed. We have a new location for that content now at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-3.1

... I'll update that link. Thanks for writing in on it.
