### ISSUE TITLE
Colorization of razor code is wrong in the docs

### ISSUE THREAD

**Issue by dibarbet** [dotnet/AspNetCore.Docs#20278]
On this link, scrolling down to the razor component "FormsValidation"
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1#built-in-forms-components

Everything from the line containing ```DataAnnotationsValidator``` up to ```<option value="">Select classification ...</option>``` seems to be colorized as a string when it's not actually a string.  Actual strings inside like ```starship.Identifier``` are colorized as not strings
![image](https://user-images.githubusercontent.com/5749229/96940350-5f2dae80-1484-11eb-9c04-98a430b2ce2e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dibarbet ... This is a known issue. I believe that there's an internal issue tracking it.

**Comment by guardrex** [comment]
I'm not sure the status of any internal issues, but there are a few public ones ...

* https://github.com/dotnet/AspNetCore.Docs/issues/17296
* https://github.com/dotnet/AspNetCore.Docs/issues/16954

You could ask Scott on one of the open ones if there are any updates.

**Comment by guardrex** [comment]
Update @dibarbet ... There's on-going internal discussion to address it. There's no ETA on the solution, but it **_will be fixed asap_**. They're working on it, but it might take them a while to resolve because it's not trivial to fix.
