### ISSUE TITLE
No PostTodoItem create method in controller scaffolding result (Create a web API)

### ISSUE THREAD

**Issue by Danoctum** [dotnet/AspNetCore.Docs#20287]
After running the commands for [Scaffold a controller](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code#scaffold-a-controller-1), in visual studio code for Mac. It says that it scaffolds the `TodoItemsController`. However, after running the commands I do not even have a `TodoItemsController` in my project.

This means that the next step can't be completed, since there is no `PostTodoItem` method anywhere in the project.

This is probably a result of the `aspnet-codegenerator` having updated/changed controllers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What was the error?

**Comment by Danoctum** [comment]
There is no error by itself, but the docs explain that there is supposed to be a `TodoItemsController` after scaffolding, but it's nowhere to be found after running the  'Scaffold a controller' commands.

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-web-api/samples/3.0

**Comment by Rick-Anderson** [comment]
We haven't had the complaint before. You might try running the command again.

**Comment by Danoctum** [comment]
Interesting, I'll try to dig into it some more. Thanks for the help!

**Comment by 2ec** [comment]
Just to add to this issue; I had the same problem in the guide for Visual Studio Code, but it should work if you stop the service before running the commands in "Scaffold a controller".

It would be nice to add a note to remember to stop the service after the first time it is run.
