### ISSUE TITLE
Part 2, add a model to a Razor Pages app in ASP.NET Core Webpage Clarification

### ISSUE THREAD

**Issue by v015eyjd** [dotnet/AspNetCore.Docs#20283]
[Enter feedback here]

The section on the webpage with the code:

`Add-Migration InitialCreate`
`Update-Database`

should clarify that each line of code should be entered individually.  Just using the "Copy" link at the top of the code on the webpage won't work as it will paste both at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Copy paste generally works

**Comment by v015eyjd** [comment]
"generally" != always.  Didn't work for me.
