### ISSUE TITLE
[May, 2022] Remove VS NOTEs from WASM security docs

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#20297]
Remove the VS NOTE added on https://github.com/dotnet/AspNetCore.Docs/pull/20192 when VS is updated for the 5.0 Blazor templates and organizational accounts.

*  aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md
*  aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md

**_UPDATE_**: I'll plan to remove the NOTEs in May of 2022, which will be six months after VS 17 is released.

**Comment by guardrex** [comment]
@danroth27 With the 5.0 release, can we drop the NOTE now from the Blazor WASM security AAD topics?

The NOTE says ...

> For Blazor WebAssembly apps created in Visual Studio that are configured to support accounts in an AAD organizational directory, Visual Studio doesn't configure the app correctly on project generation. This will be addressed in a future release of Visual Studio. This article shows how to create the app with the .NET Core CLI's `dotnet new` command. If you prefer to create the app with Visual Studio before the IDE is updated for the latest Blazor templates in ASP.NET Core 5.0, refer to each section of this article and confirm or update the app's configuration after Visual Studio creates the app.

If we can't drop it today (5.0 GA), will it be a drop for VS 16.8? ... or what VS version can I can I keep an :eye: out for?

**Comment by danroth27** [comment]
@guardrex I believe that note is still needed. VS doesn't provision the Blazor WebAssembly app correctly yet, even in 16.8. The fix will come in a future release of VS.

Adding @javiercn as well in case he has anything to add.

**Comment by guardrex** [comment]
I'll re-label this then and put it back on HOLD for the time being.

**Comment by guardrex** [comment]
**_UPDATE_** ... I checked latest VS (16.8.3) ... VS is still doing some .... er ... **_interesting things_** :smile: in project config.

I'll check again on a future release.

**Comment by guardrex** [comment]
**UPDATE** ... Checked with 16.10 ...

# 🎉🕺

Look'in good ... but let's keep a NOTE for a little while. I'm going to change what the current NOTE says to instruct devs to get 16.10 or later. In perhaps ... say ... six months? ... we can 🔪 the NOTE from the two docs.
