### ISSUE TITLE
More details on ModelBindingContext

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#20314]
I would like to see more details about architecture/object model of binding context. Like what's the difference between field name and model name. What ValueProvider does, etc.
Otherwise example of custom model binder is far from being that useful, tbh.

Example of custom model binder contains this string:
```
 bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);
```

Is it required to make this call? Why? What is it for? Why is not  `bindingContext.Result = ModelBindingResult.Success(model);` enough?
When should I set `bindingContext.Model` value, or should I at all?

When `ModelBinderProviderContext.Metadata` can be of type other than `DefaultModelMetada` or its ancestors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
