### ISSUE TITLE
Docker commands inaccurate

### ISSUE THREAD

**Issue by TeaBaerd** [dotnet/AspNetCore.Docs#20328]
When attempting to get started using this article, it instructs a developer to run the command below which results in an error "Error response from daemon: invalid mode: \https\".

`docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="password" -e ASPNETCORE_Kestrel__Certificates__Default__Path=\https\aspnetapp.pfx -v $env:USERPROFILE\.aspnet\https:C:\https\ mcr.microsoft.com/dotnet/core/samples:aspnetapp`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What OS?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
