### ISSUE TITLE
no longer compiles

### ISSUE THREAD

**Issue by dmaziuk** [dotnet/AspNetCore.Docs#20333]
[Enter feedback here]
```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
```
-- CS1929 IWebHostEnvironment does not contain a definition for IsDevelopment
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try compiling
`dotnet new webapi`

**Comment by dmaziuk** [comment]
apologies for abbreviated/mis-titled report, but compiling wasn't the point.  the point was that particular code snippet from previous iteration of .net is no longer valid code, and it's all over the docs: you find it everywhere there's `Startup.cs`.

**Comment by Rick-Anderson** [comment]
It's in the 3.1 versions as that code is correct. See the 5.0 version
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
You're missing
`using Microsoft.Extensions.Hosting;`

**Comment by dmaziuk** [comment]
OK so the disconnect is basically that anyone starting w/ the current version of the IDE is getting the "5.0 preview" version of the framework, but all documentation resources default to 3.x version.

**Comment by dmaziuk** [comment]
PS. 
1. all documentation links default to 3.1 because they lack `?view=aspnetcore-5.0` and 
2. https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.startupbase.configure?view=aspnetcore-5.0 still refers to Microsoft.AspNetCore.Hosting, not Microsoft.Extension.Hosting

**Comment by Rick-Anderson** [comment]
The template generated code works.

**Comment by dmaziuk** [comment]
Yeah, you're probably right, I have to try that sometime. I get to play with existing code; evidently that was generated using an older version of the template. ;)
