### ISSUE TITLE
Clean up Repo: Removed orphaned files.

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#20346]
Use the CleanRepo tool to find and delete orphaned markdown and media files for the AspNetCore.Docs repo.
The AspNetDocs repo is being cleaned first by gewarren, Follow her lead/recommendations on how to do this successfully after that is completed.

See AspNetDocs PR [462](https://github.com/dotnet/AspNetDocs/pull/462)

**Comment by wadepickett** [comment]
@Rick-Anderson, why close?  We are no longer doing this?

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetDocs/pull/462

**Comment by wadepickett** [comment]
I saw gewarren closed 462.  I assumed she was going to open another PR after addressing the problems.  I'll assume then instead the project itself is canceled until I hear otherwise.
