### ISSUE TITLE
Export localizable content from source code - c# (cs) and Razor Page Engine (cshtml) - to PO file

### ISSUE THREAD

**Issue by jmglezgz** [dotnet/AspNetCore.Docs#20343]
Hi guys, 
  Thanks for the great content in this documentation. I'm working on a razor page web app and I would like to include localization using PO files. I have read this document and others trying to answer this question:

How can I create/ update the po files with the new content created in the source code? it's like to scan and extract the translatable content from the source file and insert as empty strings in the PO file to deliver to my translators.

Thanks so much for your help,
Jose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1098b7-dbe7-a8d8-f57f-017b1c94e960
* Version Independent ID: 96179de2-df1c-ff1d-5a2e-89b0949e0620
* Content: [Configure portable object localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/portable-object-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/portable-object-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @sebastienros
* Microsoft Alias: **scaddie**

**Comment by sebastienros** [comment]
For Orchard Core a contributor made a tool that does exactly that:
https://github.com/lukaskabrt/PoExtractor

**Comment by jmglezgz** [comment]
Thanks @sebastienros It's exactly what I was looking for.
Only to know that the latest published version (--version 0.4.0-rc1-13272) for orchard core doesn't work with razor pages and the team has fixed [here](https://github.com/lukaskabrt/PoExtractor/issues/37)

To work with razor pages, download and build the tool from [github ](https://github.com/lukaskabrt/PoExtractor)

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
