### ISSUE TITLE
Excellent article. Thank you!

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#20355]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks
