### ISSUE TITLE
UseRouting and UseEndpoints are not applicable for ASP.NET Core v2.2

### ISSUE THREAD

**Issue by danushkap** [dotnet/AspNetCore.Docs#20352]
Please correct me if I'm wrong, I think following statements are not applicable for ASP.NET Core v.2.2 

> When using endpoint routing, the call to UseAuthentication must go:
> After UseRouting, so that route information is available for authentication decisions.
> Before UseEndpoints, so that users are authenticated before accessing the endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by danushkap** [comment]
Accidently closed.

**Comment by Rick-Anderson** [comment]
See [Endpoint Routing](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-3.1#endpoint-routing) 

ASP.NET Core 2.2 uses a new endpoint routing system for improved dispatching of requests. The changes include new link generation API members and route parameter transformers.

For more information, see the following resources

2.2 is out of support.
