### ISSUE TITLE
please give PermissionHandler better conetxt on this page

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/AspNetCore.Docs#20364]
[Enter feedback here]
I feel like its mix in the middle of another example and its making it harder than it should be to figure out what is going on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
