### ISSUE TITLE
Combine two "What's new sections"

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20368]
![image](https://user-images.githubusercontent.com/3605364/97759027-3faa0d80-1aa4-11eb-846e-169d63544fb9.png)

These should be combined.

**Comment by Rick-Anderson** [comment]
@scottaddie  if you can't get to this in the next couple of weeks could you help @wadepickett  fix this?

**Comment by serpent5** [comment]
@Rick-Anderson These two being separate makes sense to me, so I'm not sure they should be combined. The first is "what's new in the docs", whereas the second is "what's new in the different versions of ASP.NET Core". Perhaps one might just need a rename or reposition?

I realise I'm just passing by here, so feel free to disregard if there's more to this, of course.

**Comment by Rick-Anderson** [comment]
@serpent5  I agree they are different. but you can't see that in the TOC entries

* What's new in ASP.NET Core
  * What's new in each version
    * 5.0
    * 3.1
  * What's new in the documents
    * Oct 2020
