### ISSUE TITLE
incomprehensible sign in the article

### ISSUE THREAD

**Issue by FoxyChmoxy** [dotnet/AspNetCore.Docs#20365]
I can't understand whether this is a cross and I need to pray a little, or whether this is a plus and means something. Before you fix it, please let me know what that sign was.

![image](https://user-images.githubusercontent.com/38606307/97738570-baa50f80-1b08-11eb-93db-7310330472da.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
```
* HTTP/2 (except on macOS&dagger;)

&dagger;HTTP/2 will be supported on macOS in a future release.
```

It's how MD files do footnotes.
