### ISSUE TITLE
Generic Host settings documentation inconsistency

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/AspNetCore.Docs#20376]
[EDIT by guardrex to add the metadata]

_From @galakt on Thursday, October 31, 2020_

Related to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#shutdowntimeout
```
By default, environment variables used to configure these settings can have a DOTNET_ or ASPNETCORE_ prefix.
```
But GenericHost provided by `Host.CreateDefaultBuilder().Build()` does not respect `ASPNETCORE_` prefixed envs, e.g.
* ApplicationName
* ContentRoot
* EnvironmentName
* ShutdownTimeout

Afaik, because of HostBuilder has only
`config.AddEnvironmentVariables(prefix: "DOTNET_");`

_Copied from original issue: dotnet/runtime#44101_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#shutdowntimeout)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@galakt ... See the description of [ConfigureWebHostDefaults](https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.generichostbuilderextensions.configurewebhostdefaults) in the [*Default builder settings* section](https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host#default-builder-settings), which is chained right after calling `CreateDefaultBuilder` when building an ASP.NET Core app.

I'll add the metadata to the issue. It might be good to add the following right after that sentence ...

> For more information, see the \[Default builder settings](#default-builder-settings) section.

... at the end of that line.
