### ISSUE TITLE
What is light-up?

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20372]
Microsoft.AspNetCore.AzureAppServices.HostingStartup uses IHostingStartup to provide ASP.NET Core ***light-up*** integration with Azure App Service. The added logging features are provided by the Microsoft.AspNetCore.AzureAppServicesIntegration package.

I don't know what that means in english and I doubt the MT (machine translation) will know either.

Entire doc needs clean-up

related issue #20326

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-5.0&branch=pr-en-us-20324&tabs=visual-studio#specify-the-net-core-sdk-version)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
let's change to "startup" or just remove the word
