### ISSUE TITLE
How do I escape {fooBar} in log message template, so it is not treated as a placeholder?

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#20379]
```CSharp
Logger.LogDebug("{fooBar} status is {status}", status);
```
Is there any way to mark {fooBar} just as a literal instead of a placeholder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @voroninp ... Did you try a double-brace?

```csharp
Logger.LogDebug("{{fooBar}} status is {status}", status);
```

**Comment by voroninp** [comment]
Ok, tried it, and it works, also to make  it like `{10}` it should be `{{{id}}}`.
And it becomes braces madness, if you combine template with string interpolation: `$"{nameof(id)} = {{{{{{id}}}}}}"`  :-D

**Comment by guardrex** [comment]
Look @voroninp .... I realize that it's 👹 *Halloween* 👹 and all ..... **_but don't ScArE me like that!!!!_** 🎃👻 I felt the chill of *cold death* ⚰️ come over me when you sprang that 🔥 *Braces from Hell* 🔥 example on me! lol 

Rick will be on later or Monday to take a look. He'll determine if a mention of it would be good. Leave this issue open for him.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/docs/issues/21291
