### ISSUE TITLE
Current dotnet new cli example adds an extra `api://` to api uri

### ISSUE THREAD

**Issue by scdehmlow** [dotnet/AspNetCore.Docs#20381]
When specifying the `{SERVER API APP ID URI}` in the dotnet new command to create the app it automatically prepends a `api://`. The example value is `api://41451fa7-82d9-4673-8fa5-69eff5a761fd` which will create the line `options.ProviderOptions.DefaultAccessTokenScopes.Add("api://api://41451fa7-82d9-4673-8fa5-69eff5a761fd/API.Access");` in the client Program.cs file.

Unless this is not how the dotnet new command should behave can you add some indication in the docs that the `api://` should not be provided with the server api app id uri please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'll probably end up opening an engineering issue on it, but I'm not opposed to calling out behavior like this in the topic either. I also think that the *Troubleshoot* section should have a general remark that says that any small misconfiguration can break the authn/z. Almost all of the doc issues opened here have been just like this one ... a tiny misconfig broke the app ... the dev just had to read down the topic's sections and compare to their app to find the little 😈 and squash it. Thanks for reporting this. I'll see about perhaps getting it done next week. Leave this issue open. It will close automatically when the PR merges.

**Comment by guardrex** [comment]
Whatever the outcome of the product unit issue, I agree that the instruction should be to strip the scheme from the entry when providing the argument to the command. That seems to be a better path than adjusting the broken value in `Program.cs` after the app is created. I'll get this done on Monday morning, and it should go live by EOD on Monday.
