### ISSUE TITLE
"Add Validation to Dynamic Controls" - duplicate events

### ISSUE THREAD

**Issue by yurikus** [dotnet/AspNetCore.Docs#20384]
I verified (thanks to [this SO post](https://stackoverflow.com/a/35310509/1165889) ) that indeed, multiple duplicate events are attached to the form when removeData(..) is called and form then reparsed.

repro:
```
frm = $('selector')
frm.removeData("validator");
frm.removeData("unobtrusiveValidation");
$.validator.unobtrusive.parse(frm[0]);
```

Original:
![image](https://user-images.githubusercontent.com/11010776/97831810-b9095200-1c96-11eb-9f1b-ff1c82a61428.png)

After 3 reparses:
![image](https://user-images.githubusercontent.com/11010776/97831833-ccb4b880-1c96-11eb-9756-857f6a7b2f4b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-3.1#add-validation-to-dynamic-forms)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you asking that this be added to the document? It doesn't seem to fit.

**Comment by yurikus** [comment]
I guess clicking "document problem" might not the right thing. This seems like a bug + doc deficiency. If I do exactly as the doc suggests, I'm guaranteed problems with perf on page. Must add extra code to account for events. So .. not sure.
```
.off("submit.validate click.validate focusin.validate focusout.validate keyup.validate invalid-form.validate");
````

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate).

**Comment by yurikus** [comment]
At this point I think amending the doc to account for events (as I mentioned above) should suffice.

**Comment by fokkog** [comment]
It's a pity that this issue was closed without actioning it.
It cost me a few days to understand why my large/dynamic form was getting so slow, e.g. a few cloning action would lead to form submission times of over 1 minute where 99.9% of the time was spent in client-side validations.
The root cause was exactly what was reported here: duplicate event handler registrations when following the MS docs.

**Comment by Rick-Anderson** [comment]
@serpent5  please review

**Comment by fokkog** [comment]
Much appreciated if this is getting reconsidered. In the end these SO posts pointed me to the correct solution:
- https://stackoverflow.com/a/35310509
- https://stackoverflow.com/a/35435644 (in the comment)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by yurikus** [comment]
The only lack of activity is from MS side here ..
