### ISSUE TITLE
Problem with code at https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio

### ISSUE THREAD

**Issue by djduncan585** [dotnet/AspNetCore.Docs#20382]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by djduncan585** [comment]
A section exists with the following code:

public string Welcome(string name, int numTimes = 1)
{
    return HtmlEncoder.Default.Encode($"Hello {name}, NumTimes is: {numTimes}");
}

The query string does not accept any changes to the numTimes parameter. I was able to work around this by making the following changes:

       public string Welcome(string name, string numTimes = "1")
        {
            return HtmlEncoder.Default.Encode($"Hello {name}, NumTimes is: {int.Parse(numTimes)}");
        }

I'd submit a pull request for this but I don't have the time right now.

**Comment by Rick-Anderson** [comment]
it does.
