### ISSUE TITLE
RenderPartialAsync works but Partial Async doesnt work in foreach

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#20380]
This issue is related to this page content
https://github.com/MicrosoftDocs/feedback/issues/3240

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-3.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate). 

Please provide a link to a GitHub repo with the simplest possible app that reproduces the bug.
Please close https://github.com/MicrosoftDocs/feedback/issues/3240 and don't open multiple issues for the same problem.
