### ISSUE TITLE
Tutorial for installing on IBM Cloud

### ISSUE THREAD

**Issue by KissConsult** [dotnet/AspNetCore.Docs#20398]
I would like to write a step-by-step tutorial for installing ASP.NET on IBM Cloud kubernetes cluster

**Comment by Rick-Anderson** [comment]
I think https://www.ibm.com/cloud/container-service/kubernetes-tutorials would be a better place for that, and we could publish the link.

We appreciate the offer, but I don't think we have the resources to review + maintain the tutorial.

cc @scottaddie  @mkArtakMSFT  @bradygaster  @LadyNaggaga in case one of them has the resources to take this on.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
