### ISSUE TITLE
Explain more detailed the Async-Part of Impersonation-Section

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/AspNetCore.Docs#20407]
Section: **Impersonation**
Sentence: _RunImpersonated doesn't support asynchronous operations and shouldn't be used for complex scenarios._

Please explain more detailed what async means in this context. Does it only mean that the impersonated delegate is forbidden to run async code or does it mean that two independent threads should not start impersonation at same time.

### Second Szenario

Please let me explain what I mean with the **second** szenario:

My Asp.Core app gets two user requests (I think the requests are handled by two different threads). At some point both requests would impersonate at same time but on two different threads. Is this meant with "_asynchronous operations_" or not?

### First Szenario

For the **first** szenario I have a technical question:

What is the exactly problem when running an async task within the impersonated delegate. 
a) Is it because the async task would not run within impersonation context 
b) or because the sync delegate close the impersonation before async has finished?

---
By the way, it would be helpfull if the documentation of **WindowsIdentity.RunImpersonated** would reference about the asp.net-core behavior or link this page (https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#impersonation)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
