### ISSUE TITLE
Why Scoped HTTPClient instead of Singleton HTTPClient

### ISSUE THREAD

**Issue by JustinGrote** [dotnet/AspNetCore.Docs#20402]
Why is a scoped HTTPClient recommended here? lots of modern examples use singleton and the httpclient documentation itself says you should resuse a single instance of httpclient wherever possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7683690c-e3aa-4a00-152a-e44cfd7fc789
* Version Independent ID: d9aabe95-69e9-0a03-81ff-429914137f9d
* Content: [ASP.NET Core Blazor dependency injection](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JustinGrote ... It's in the *Service lifetimes* section at https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-3.1#service-lifetime ...

> Blazor WebAssembly apps don't currently have a concept of DI scopes. Scoped-registered services behave like Singleton services. However, the Blazor Server hosting model supports the Scoped lifetime. In Blazor Server apps, a scoped service registration is scoped to the connection. For this reason, using scoped services is preferred for services that should be scoped to the current user, even if the current intent is to run client-side in the browser.

That's what the product unit wished to convey on the point. I think the obvious changes are ...

* Cross-link the *Service lifetimes* section to the `HttpClient` default service entry.
* Where it says "even if the current intent is to run client-side in the browser," indicate explicitly that it's referring to Blazor WASM.

Those improvements won't address the concept tho. For Blazor WASM, it would be fine to use singleton given that that's the behavior anyway according to their remarks.

cc: @javiercn ... if he wants to advise on clarifying or updating this paragraph.

**Comment by JustinGrote** [comment]
Thanks @guardrex, I'll let @javiercn chime in if changes are needed and if not it can be closed.

My recommendation would be for a note added to https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/dependency-injection.md#default-services httpclient description that scoped and singleton have same behavior in WASM and then link down to the corresponding detail.

**Comment by guardrex** [comment]
Yes ... I agree with that.

Leave the issue open even if Javier doesn't have anything to change. These issues close automatically when a PR that we create is ultimately merged. I do plan to take those two actions that I outlined that will help surface this concept in the *Default services* section. I'll ping u on the PR later.

**Comment by accountrequired** [comment]
Why if it's the same thing, does it require one to use "scoped". Even more so since the scopes are actually singletons as you say.
I have a singleton service that, to work correctly, is required to actually be a singleton. So if I change it to scoped to work around this nonsense, it will continue to work for the time being, but only until Blazor WASM actually does support scopes. At that time it will fall apart / become flaky and it could be completely avoided if I could just declare it as a singleton from the start.

What's the rationale here? Because "scoped" looks prettier on paper? I don't get it.
