### ISSUE TITLE
Better documentation for scope DI usage with HttpClientFactory scenarios

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#20401]
> The IHttpClientFactory creates a separate DI scope for each handler. Handlers can depend upon services of any scope. Services that handlers depend upon are disposed when the handler is disposed.

This statement should be more visible (like a **NOTE** in yellow in bold). We should also show examples of how scoped services resolved. Show the same scoped service being resolve in an HttpMessageHandler and the request with difference lifetimes. That's bitten some people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#outgoing-request-middleware)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@serpent5  let me know if you're interested in working on this.

**Comment by serpent5** [comment]
@Rick-Anderson Yeah, sure. I'll investigate the specifics and submit something. Do you want me to prioritise this one over the others I've got on my list? I see it's a P0.

**Comment by Rick-Anderson** [comment]
`@davidfowl ` requests have the highest priority, much higher that **P0**  :ghost: :sunglasses: :fire:
