### ISSUE TITLE
Customer requested documentation update for file uploads.

### ISSUE THREAD

**Issue by rhamlett** [dotnet/AspNetCore.Docs#20404]
From: | crahimzadeh@wavetronix.com
The .NET Core team changed how you increase file size intake in IIS and kestrel. Now the   developer has to specify the file limit just like the answer in this stack   overflow post: 
https://stackoverflow.com/questions/63439508/unable-to-upload-file-size-larger-than-200-mb-in-asp-net-core-web-api   

It seems to change a lot over each .net core release. If possible can you propagate a message to the .NET Core team and the people who right your documentation for this page: 
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#upload-large-files-with-streaming

The question/feedback I have to help mitigate issues like this is to notify   the community in a better way and have better docs. We wasted two days of   work because this change wasn't documented well. There was only one web page out there that was moderately easy to find that has the answer. Thank you for your help and the services you provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-3.1#upload-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback. We'll try to document these changes more quickly. I see the doc has been updated.

cc @guardrex

**Comment by guardrex** [comment]
`MaxRequestBodySize` was the missing limit, and it was added three months ago on https://github.com/dotnet/AspNetCore.Docs/issues/19592. Three of them were there from the start ... going back perhaps four years. I don't know why `MaxRequestBodySize` didn't make the original topic ... it's my fault for missing it, and the engineering review didn't catch it. The good news is that AFAIK today, all of the limits are present. I don't expect the framework to change further on these 🤞🍀 ... but I can't guarantee that either, of course.
