### ISSUE TITLE
How is authentication scheme selected?

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#20414]
Docs say nothing how scheme is probed. For the jwt token one must properly set Authorization header, for Cookies it's another header.

Does it work the other way around? That is we either define default scheme, or specify required scheme in `[Authorize]` attribute? But before the controller is hit I'd expect request be already authenticated:

```CSharp
app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

 // Execute the matched endpoint.
app.UseEndpoints(endpoints => ...);
```
Yet while playing with the project I found out that authentication scheme handler gets activated based on `AuthenticationSchemes` in `[Authorize]` attribute. For me it's a weird backward functionality: endpoints middleware affect authentication middleware.  How is it even possible? Explanation would not hurt, I assume.

My mental model is the following:

1. Select the scheme to be used for authentication. (maybe multiple schemes)
2. Authenticate. (maybe with multiple handlers each returning authentication ticket resulting in a principal with multiple identities)
3. Map request to controller, check required auth schemes, 
4. Profit!

IMO, you should document this part in more details. Also it is not obvious that absence of default scheme requires setting `AuthenticationShemes` property of `[Authorize]` attribute. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by voroninp** [comment]
@Rick-Anderson I added more comments to the text.

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/aspnetcore/issues/26002 uses multiple

**Comment by voroninp** [comment]
@Rick-Anderson You may add multiple schemes, but nothing seems to be responsible for selecting a set of them other than the list in Authorize attribute

**Comment by mkArtakMSFT** [comment]
@HaoK can you document this please? Thanks!

**Comment by HaoK** [comment]
I'm not sure what the best way to document this is @Rick-Anderson so I'll just add my explanation here to start, and we can figure out if we are missing anything.

So the basic idea is there Authentication is responsible for providing the ClaimsPrincipal for Authorization to make permission decisions against.  That is what AuthenticationSchemes are used for, selecting which authentication handler is responsible for generating the correct set of claims.  The default authentication scheme is one mechanism for determining the scheme.  Another way is via specifying the AuthenticationSchemes of the authorize property (which is described in https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-5.0). Yet another way is to just directly set HttpContext.User.  But there is no automatic probing of schemes, if you don't specify a default scheme, you must specify it in the authorize attribute or you will get an error saying as much.
