### ISSUE TITLE
Link "SameSiteSupport class" redirect to Page Not Found

### ISSUE THREAD

**Issue by joaoGoncalves81** [dotnet/AspNetCore.Docs#20419]
The link "SameSiteSupport" in this page is broken.

"If SameSite is set to None and the current user agent is known to not support the none attribute value. The check is done using the **SameSiteSupport** class:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e06d128-3cb4-f058-421d-31a790621cf8
* Version Independent ID: 2fe4c6b7-de18-881a-01f5-252e94fd155a
* Content: [ASP.NET Core 3.1 Razor Pages SameSite cookie sample](https://docs.microsoft.com/en-us/aspnet/core/security/samesite/rp31?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/samesite/rp31.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/samesite/rp31.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@joaoGoncalves81  thanks for reporting. It's https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/samesite/snippets/SameSiteSupport.cs
I'll get it fixed.
