### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by dnt91** [dotnet/AspNetCore.Docs#20416]
Here is a pretty simple scenario with jwt authentication > https://jasonwatmore.com/post/2020/08/13/blazor-webassembly-jwt-authentication-example-tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dnt91 ... Of course, you're welcome to use any tutorial that you wish. If you're mentioning this for a possible cross-link, we can't do that because blog posts go stale so quickly. I'll take a look at what's there to see how they composed their coverage and then open a new issue here if I see anything that would be good to do. Thanks for writing in.

**Comment by dnt91** [comment]
Hi @guardrex 
Thanks you for your answer. I actually have an application which use asp.net core MVC 3.1 as a backend and angular as the frontend. I'm migrating the angular part to blazor and was loking for a simple way to integrate my existing authencation api. I read the msdn documentation, tried to undestand (with the documentation) the standalone approach with auth library, tried to use to VS Blazor template with authentication and don't achieve my goal. To my mind the documentation is not clear enough and the template is useless (or there is something that I don't understand). So I was looking for a real world step by step example when I found this article which is to my mind more simple and understandable.nevertheless I would like to have a standardized approach. also if the msdn documentation could be revised to rely on such a simple scenario that would be a great idea. This is the main reason for my initial comment
