### ISSUE TITLE
Front Door recommendation for Blazor, but Front Door does not work with Blazor.

### ISSUE THREAD

**Issue by jraadt** [dotnet/AspNetCore.Docs#20417]
Under the "Client connections" section, one recommendation is to use Front Door to manage the number of client connections. Azure Front Door does not support web sockets/SignalR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff954815-0f8b-9f1b-9772-1657744b4f9e
* Version Independent ID: ed7d726d-41c6-73d8-d564-91530b4935c3
* Content: [Threat mitigation guidance for ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/server/threat-mitigation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/server/threat-mitigation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @jraadt.

@javiercn ... Do you want me to strike that remark or replace it with something else? Current text is .....

> At the server level: Use a proxy/gateway in front of the app. For example, Azure Front Door enables you to define, manage, and monitor the global routing of web traffic to an app.
