### ISSUE TITLE
How do I know if IMiddleware is registered as scoped or transient?

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/AspNetCore.Docs#20420]
In the introduction, the following is mentioned: _"The middleware is registered as a scoped or transient service in the app's service container."_

Is there any way to determine which one is chosen?  It's not mentioned further in the document, yet the phrasing here makes it sound like automatic behaviour as part of the registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f5eb44-55e5-d4a5-0ab1-5122c29a1db5
* Version Independent ID: 0b8da6a7-8333-5d8f-23a5-05bf0ca661f9
* Content: [Factory-based middleware activation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/middleware/extensibility.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection 

[Lifetime and registration options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#services-injected-into-startup) uses `UseMiddleware`

**Comment by atrauzzi** [comment]
Hmm, that's not what I'm observing presently. I have a middleware that gets instantiated during a request, then injected for another request-scoped middleware.  But when I request the same service in my controller, I get a totally new instance.

**Comment by Rick-Anderson** [comment]
>request-scoped

That's not a lifetime
Services can be registered with one of the following lifetimes:

Transient
Scoped
Singleton

https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-lifetimes

**Comment by atrauzzi** [comment]
Well, you took a very literal interpretation there, but yes.  Request-scoped or scoped, they're usually used interchangably.
