### ISSUE TITLE
Missing [FromBody] attribute in web api POST tutorial.

### ISSUE THREAD

**Issue by lud** [dotnet/AspNetCore.Docs#20424]
Hi, 

It looks that I had to put the `[FromBody]` attribute for the json to be deserialized as a model, otherwise it would not work. This does not seem to be told in the tutorial.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's not needed in this tutorial. See https://docs.microsoft.com/en-us/aspnet/core/web-api

**Comment by lud** [comment]
Hey @Rick-Anderson sorry I totally missed the `ApiController` controller attribute.
