### ISSUE TITLE
IApplicationBuilder#UseGrpcWeb is not defined

### ISSUE THREAD

**Issue by nishants** [dotnet/AspNetCore.Docs#20431]
The document here : https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1 suggests to add following line in _Startup.cs_
`app.UseGrpcWeb(new GrpcWebOptions { DefaultEnabled = true });`

However, `IApplicationBuilder` does not have this method or extension. Also in the GRPC project created using `dotnet new grpc`,  this line is missing.

Can you please check if there is something missing in the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c13a1c7-4683-a9a5-9ab3-e28d4506af26
* Version Independent ID: ea3b00c8-8f09-c045-4641-dc3a0030d6e5
* Content: [Use gRPC in browser apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-3.1)
* Content Source: [aspnetcore/grpc/browser.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/browser.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by nishants** [comment]
Here is a template to reproduce this : https://github.com/nishants/bug-grpc-to-web-service

**Comment by Rick-Anderson** [comment]
Go through https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.1&tabs=visual-studio
You must be  missing a package that has the extension method.

**Comment by Rick-Anderson** [comment]
https://devblogs.microsoft.com/aspnet/grpc-web-experiment/
