### ISSUE TITLE
redirect uri for the client should be set for single page app instead of web app

### ISSUE THREAD

**Issue by jhgbrt** [dotnet/AspNetCore.Docs#20435]
After following this guidance, a login won't be able to complete. The request for a token (after succesful login) will fail with `AADB2C90079: Clients must send a client_secret when redeeming a confidential grant`. Changing the reply url type to 'Spa' fixed the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's a 5.0 gesture @jhgbrt ... Flip the topic over to 5.0 Preview with the document version selector for the preview 5.0 content, which includes the instruction to use the SPA platform.
