### ISSUE TITLE
The "jQuery" library could not be resolved by the cdnjs provider

### ISSUE THREAD

**Issue by Dulanjali-Senarathna** [dotnet/AspNetCore.Docs#20442]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d69ef46-689c-33d0-c86b-078c8172c480
* Version Independent ID: 519af8ab-78e5-88c9-f268-431f417eca73
* Content: [Use LibMan with ASP.NET Core in Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/libman/libman-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/libman/libman-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
