### ISSUE TITLE
Is assembly already loaded?

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#20444]
The example code shows how to load an assembly which is then (presumably) cached. Does the assembly loader have a way of letting us know the difference between a load and a cache retrieval?

Sometimes we need to perform reflection on the newly retrieved dll but only when it is first loaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690632ad-f357-161f-217b-faba56e90f36
* Version Independent ID: 626c5ed9-6424-7940-56e2-a19989b6de38
* Content: [Lazy load assemblies in ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-lazy-load-assemblies?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-lazy-load-assemblies.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-lazy-load-assemblies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ping @captainsafia for comment.

**Comment by captainsafia** [comment]
> Does the assembly loader have a way of letting us know the difference between a load and a cache retrieval?

We don't return this data by default from the assembly loader service. However, you can determine if an assembly has already been loaded by evaluating the the list of assemblies loaded into the default app domain.
