### ISSUE TITLE
remove dup instructions

### ISSUE THREAD

**Issue by RickAndMSFT** [dotnet/AspNetCore.Docs#20440]
![image](https://user-images.githubusercontent.com/1638506/98425195-528a8800-2038-11eb-9d8d-30144b8f06fd.png)

`dotnet tool install --global dotnet-ef`  
Didn't you do that in a previous page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This doesn't appear to be an issue with all the more recent updates. The instruction on this page seems to be the first to call out `dotnet tool install --global dotnet-ef` in the series.
