### ISSUE TITLE
Redundant Configuration of DelegatingHandler in ASP.NET Core

### ISSUE THREAD

**Issue by Rookian** [dotnet/AspNetCore.Docs#20449]
Is there a reason why we have to register `DelegatingHandler`s twice?

```csharp
services.AddTransient<ValidateHeaderHandler>();
services.AddHttpClient("externalservice")
  .AddHttpMessageHandler<ValidateHeaderHandler>();
```

`ValidateHeaderHandler` is registered via `services.AddTransient` and `AddHttpMessageHandler`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@Rookian  I think you've answered your own question. The first time it adds it to the DI container, the second call  is `AddHttpMessageHandler`

cc @serpent5

**Comment by serpent5** [comment]
> 
> 
> @Rookian I think you've answered your own question. The first time it adds it to the DI container, the second call is `AddHttpMessageHandler`

Yes, I agree. I think the question might be more about why the call to `AddHttpMessageHandler` doesn't do both. I think the split offers up more flexibility re configuring the handler for DI. For example, you might want to use a factory callback to create the handler when it's needed.
