### ISSUE TITLE
Explain component lifecycle events for reconnections

### ISSUE THREAD

**Issue by akovac35** [dotnet/AspNetCore.Docs#20441]
The page would benefit from an explanation of differences of component reconnection related lifecycle events compared to normal component lifecycle events. The explanation should distinguish between successful reconnection and component disposal.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @akovac35 ... Let's see if this is something that we should pursue.

@javiercn, our current reconnection coverage is in the following spots of **Fundamentals** > **Additional scenarios** (and note that we'll probably be re-organizing the coverage at some point *soon-ish* ... a few weeks or early 2021) ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#reflect-the-connection-state-in-the-ui
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1#modify-the-reconnection-handler (**_and the following two sections_**)

Is that sufficient on its own, or should we tie in the lifecycle of reconnection with component lifecycle? ... I've assumed to this point that they're managed separately thus should be described separately.

**Comment by akovac35** [comment]
@guardrex To clarify my comment: when reconnection is established, what happens with OnInitialized, OnParametersSet and OnAfterRender? It would make sense that only OnAfterRender is invoked? <— Just add a few lines to docs to clarify this.

**Comment by guardrex** [comment]
I don't think anything happens, per se, as long as state isn't lost. I thought that no events fire merely on reconnection. These are separately managed things AFAIK. @javiercn will let us know and then I'll see if I can add coverage to cover it.

**Comment by javiercn** [comment]
Nothing happens when the connection is lost. 

Components keep working the same way they were, the only thing that gets interrupted are UI updates, which resume the moment reconnection happens.

The only events triggered are the circuit handler lifecycle events if you have a handler registered.
