### ISSUE TITLE
.net 5 -v -> --version

### ISSUE THREAD

**Issue by rvanlieshout** [dotnet/AspNetCore.Docs#20450]
Hi all,

Section `Add NuGet packages and EF tools` states

```
dotnet tool install --global dotnet-ef -v 5.0.0-rc.2.20475.6
dotnet tool install --global dotnet-aspnet-codegenerator -v 5.0.0-rc.2.20516.1
dotnet add package Microsoft.EntityFrameworkCore.SQLite -v 5.0.0-*
dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -v 5.0.0-*
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design -v 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.Design -v 5.0.0-*
dotnet add package Microsoft.EntityFrameworkCore.SqlServer -v 5.0.0-*
dotnet add package Microsoft.Extensions.Logging.Debug -v 5.0.0-*
```

Shouldn't that be `--verstion 5.0.0-rc.2.20475.6` for version 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
` -v 5.0.0-*` brings in the latest 5.0 version

**Comment by rvanlieshout** [comment]
My bad. In my mind I had typed 'version'. For me '-v' is about verbosity, not about a version

**Comment by rvanlieshout** [comment]
@Rick-Anderson, i don't know if it's fixed, but the problem wasn't about the version number, it's about using '-v' in the first two lines where that should be '--version'

**Comment by Rick-Anderson** [comment]
They're the same

**Comment by rvanlieshout** [comment]
Not for me:

```
$ dotnet tool install --global dotnet-ef -v 5.0.0-rc.2.20475.6
Unrecognized command or argument '5.0.0-rc.2.20475.6'
Required argument missing for option: --verbosity
Usage: dotnet tool install [options] <PACKAGE_ID>
```

**Comment by rvanlieshout** [comment]
for both:

```
$ dotnet --help
.NET Core SDK (3.1.403)
```

and

```
$ dotnet --help
.NET SDK (5.0.100-rc.2.20479.15)
```

**Comment by Rick-Anderson** [comment]
@rvanlieshout  thanks for notifying us, it will be fixed in the next hour.
