### ISSUE TITLE
{handler?} docs incomplete

### ISSUE THREAD

**Issue by WouterrV** [dotnet/AspNetCore.Docs#20453]
IMO the information regarding `@page "{handler?}"` is incomplete - it's not clear that by using this, the form tag helpers magically produce new links, and also I can't find information on how to modify my PageModel to deal with this new style of URLs. Should I make switch cases using some `handler` variable? Is the `handler` variable mapped to handler methods? Where is it stored?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/razor-pages/?view=aspnetcore-3.1&tabs=visual-studio#custom-routes-1)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No magic, you've created a custom route,, and TH create links for routes. See the following:

- https://docs.microsoft.com/aspnet/core/fundamentals/routing
- https://docs.microsoft.com/aspnet/core/razor-pages/razor-pages-conventions
