### ISSUE TITLE
services.AddMvc().AddNewtonsoftJson()

### ISSUE THREAD

**Issue by mbilal5** [dotnet/AspNetCore.Docs#20460]
I was creating a ASP.NET Core 3.1 from scratch as I was following the article. 
Without a call to .AddNewtonsoftJson(), my api controller didn't return the expected results.
```cs
services.AddMvc(options => options.EnableEndpointRouting = false)
    .AddNewtonsoftJson();
```

My suggestion is The code snippet in "Registering OData" section should include a comment or note that provides this information

The issue was hinted at in this [devblogs.microsoft.com article](https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/)

> Notice that we added AddNewtonsoftJson() to resolve the formatting issue with $select,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcb541d-c695-99f6-dde7-f01d0d9307d5
* Version Independent ID: 9585545a-9047-85ff-6117-ddd07ef6ee46
* Content: [Compatibility version for ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/compatibility-version.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/compatibility-version.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
2.2 is out of support. Can you update to 3.1?
