### ISSUE TITLE
Blazor JS interop across module formats

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#20461]
@GeorgeS2019 asked on https://github.com/dotnet/AspNetCore.Docs/issues/19873#issuecomment-724340803 ...

> @guardrex  Can we have [Blazor JS Isolation examples](https://github.com/simutaroman/BlazorNet5JsInterOp/issues/1#issuecomment-724119614) using [different module format](https://www.sitepoint.com/understanding-module-exports-exports-node-js/)?
>
> - The Asynchronous Module Definition (**AMD**) format
> - The CommonJS (**CJS**) format
> - The ES Module (**ESM**) format.
> - The System.register format 
> - The Universal Module Definition (**UMD**) format

My general feeling is that we're pressed for time with the current workload well into 2021, and these approaches ...

* Aren't really pivotal for coverage of Blazor concepts.
* Exist in external doc sets.

Even if we took this on, I think it would have to be a *new JS interop topic* that shows how each module format can be used in a Blazor scenario with the same example in a SxS format.

I've marked this for triage so that management can consider it and decide if it should be taken on. Thanks for asking @GeorgeS2019.

**Comment by GeorgeS2019** [comment]
@guardrex  As anyone who want to believe that Blazor will empower c# developer to do web development, we want Microsoft ASPNetCore team to provide a comprehensive solution that SHOW blazor JS Isolation is able to handle all possible JS Module format scenarios. 

The JS Isolation solution is A very GOOD promising START.  

The more we work on it, the more we realize, there are still questions that limit our abilities to implement JS Isolation

For example.  in the documentation,  it is important to state that the current Blazor JS Isolation is ONLY LIMITED to the following FORMAT. We are working with the community to get help to handle OTHER FORMATS. Your feedback is important so we will prioritize the typical use cases. 

In my view, the typical use cases, are having NodeModues installed in wwwroot directory and we need Blazor JS Isolation to play nice with these NodeModules e.g. using CommonJS format module that involve "require" ==> which unfortunately does not WORK YET in current implementation of Blazor JS Isolation ( If I understand correctly, and I hope I am wrong about that).

**Comment by javiercn** [comment]
@GeorgeS2019 I'm not sure I completely understand what you are asking.

There is no JS isolation support for anything other than importing ES modules, which is what the browser supports.

If you are asking for support for JS isolation in combination with other module formats, that's not really the goal of the JS isolation support that we currently ship. I would suggest you file an issue in the asp.net core repository instead if you want to see support for other module formats (whatever that means) so that it can be considered for an addition in a future release.

**Comment by guardrex** [comment]
With that, I'm going to close this for action here.

**Comment by GeorgeS2019** [comment]
@javiercn @guardrex 

Thanks for clarifying that the Blazor JS Isolation adheres to the ESM module format.

=> Is that clearly documented in the official Blazor JS Isolation currently only the ESM format is supported right now. 
=> By stating that, it helps the majority of JavaScript developers evaluating migrating projects to Blazor to plan more effectively. 
=> [How to span the CJS to ESM gap](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b)  => by taking this into consideration, it helps to convince these non Blazor developers that the team implementing JS Isolation has considered important use cases (e.g. Work in Progress in evaluating how to address the CJS to ESM gap). I believe, this will give more credibility to the Blazor vision - thinking ahead of needs for others joining the Blazor as the choice for web development.

**Comment by guardrex** [comment]
Good idea @GeorgeS2019 ...

> Is that clearly documented in the official Blazor JS Isolation currently only the ESM format is supported right now.

I can address that aspect with a quick one-liner at the tops of our two JS interop topics. I propose ...

> JS interop supports \[ES modules](https://developer.mozilla.org/docs/Web/JavaScript/Guide/Modules) for JS isolation. Other module formats aren't supported at this time.
