### ISSUE TITLE
Update: Publish an ASP.NET Core web API to Azure API Management with Visual Studio

### ISSUE THREAD

**Issue by bizinbarefeet** [dotnet/AspNetCore.Docs#20474]
Try allowing several hours for this task.  It's not as intuitive or as clear as this document suggests.  Latest visuals look different too.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by Rick-Anderson** [comment]
@CodeMillMatt any chance you could update this for 5.0 and the latest UI on VS/Azure?

**Comment by codemillmatt** [comment]
I'll add it to my backlog - most likely first part of next week.
