### ISSUE TITLE
Uses out of date Azure library for keyvault

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/AspNetCore.Docs#20478]
There's a new library built on top of Azure.Identity/Azure.Security.KeyVaults.Secrets: Azure.Extensions.AspNetCore.Configuration.Secrets.  There are docs here for that:  https://docs.microsoft.com/en-us/dotnet/api/overview/azure/extensions.aspnetcore.configuration.secrets-readme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@twsouthwick can you outline the changes that need to be made? Any chance you could provide the first draft PR and I could clean it up?
