### ISSUE TITLE
incorrect GetConnectionString param for VSC and macOS

### ISSUE THREAD

**Issue by flaviomarcilio** [dotnet/AspNetCore.Docs#20473]
The part **services.AddDbContext<RazorPagesMovieContext>(options => options.UseSqlite(Configuration.GetConnectionString("RazorPagesMovieContext")));** of tutorial using Visual Studio Code isn't working well. 
My solution **services.AddDbContext<RazorPagesMovieContext>(options => options.UseSqlite(Configuration.GetConnectionString("*MovieContext*")));**

The command **dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir *Pages\Movies* --referenceScriptLibraries** produces a folder named PagesMovies and not a folder Movies into folder Pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The command **dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir *Pages\Movies* --referenceScriptLibraries** produces a folder named PagesMovies and not a folder Movies into folder Pages.

You ran the wrong command:

![image](https://user-images.githubusercontent.com/3605364/98712416-5c5b0680-232a-11eb-949d-3689031c0d42.png)

The `MovieContext` problem should be fixed, thanks for reporting.

**Comment by wadepickett** [comment]
Rick, I think this is related to the same issue I was running into on  #20428 yesterday for your MVC series.

**Comment by wadepickett** [comment]
@flaviomarcilio,  thanks very much for the heads up.  Greatly appreciated!  I'll get it fixed.

**Comment by wadepickett** [comment]
Will correct on the appsettings.json end with "RazorPagesMovieContext" to keep consistent with how VS tooling names these.
