### ISSUE TITLE
5.0 Intro to MVC cleanup pass

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20486]
Do another pass and fix problems on the series.

**Scope:**
Blocking issues/major headaches such as but not limited to:
- Screenshots with significant (nearly blocking) mismatches.
- Code highlighting that is showing the wrong thing, 
- Code sample that does not match.

**Outside of the scope of this issue** 
(to be follow up in another tracking issue):
- remove unnecessary includes
- Machine translation improvements
- Style guide issues
- General readability improvement 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@Rick-Anderson This tutorial series has almost as many issues as the  RazorPages series had (hundreds), that I am going to scope this to stages. So I am defining this one as centered on potential blocking issues/major headaches for this one:  Screenshots that do not match.  Code highlighting that is showing the wrong thing, Code sample that does not match.  We can get those in and then in another issue I'll hit MT/readability, style guide issues, etc.
