### ISSUE TITLE
MonoDB Rest API Tutorial : explain port

### ISSUE THREAD

**Issue by barnard09** [dotnet/AspNetCore.Docs#20488]
Edit: I found the solution to my problems, but include some feedback below that might be useful.
Following the tutorial, towards the end at the "Test Web API" section, there is no comment on the port to be used. Initially I tried 27017 but was greeted with an error, following this I searched and found that the default is 5000, which gave a blank response of [] followed by the warning:

`warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.`

Considering this is an introductory tutorial you'd expect that the port configuration would be explained.

I found after this that the rest api was connecting to some other instance of mongodb, as it was able to respond even when mongod.exe wasnt running and generating blank responses even though the collection connected to through mongo.exe was populated. After terminating the service from task manager the correct instance could be connected to once mongod was relaunched and the desired response received through the rest API. Also while it is mentioned that the mongdodb path variable needs to be updated, the reader is left to searchfor how to do this elsewhere, for the sake of inclusivity it feels like this should be included also. Perhaps it would be useful for the tutorial to give better advice on these areas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@barnard09  thanks for the feedback. It should be  updated to use https and port 5001 with VS instructions on how to run on Kestrel

Moved to Master list: Create a web API and MongoDB #16196
