### ISSUE TITLE
Migrating Razor Class Libraries

### ISSUE THREAD

**Issue by PoisnFang** [dotnet/AspNetCore.Docs#20480]
Please Document how to migrate Razor Class Libraries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Related to your request @PoisnFang, let me jump in and ask about packages created from RCLs ...

@captainsafia ... Something caught my :ear: from your talk with Dan: 🤔 We might be missing something pertaining to how **_NuGet packages supply static content ✨ *auto-magically* ✨ to the consumer in 5.0_** ... if that's what you were talking about ... I mean if I didn't *just make that up!* 🙈😄 I don't recall us making an update for something like that. We **_do_** have coverage that says 'you don't need to move the assets into the package with project file configuration.'

Do we need to add guidance here ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-5.0&tabs=visual-studio#build-pack-and-ship-to-nuget

... and/or here ...

https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio#consume-content-from-a-referenced-rcl

In general, is there anything else? That ☝️ is a potential migration issue, but is there anything else to cover @PoisnFang's ask?

@scottaddie ... If we need something on this, I can take care of it.

**Comment by pranavkm** [comment]
> We might be missing something pertaining to how NuGet packages supply static content ✨ auto-magically ✨ to the consumer in 5.0

The mechanisms haven't changed here since 3.1, there's nothing new to report here.

The only thing that might be useful would be to tweak the documentation in the Css isolation topic to show an example of what the `link` tag would look like for a scoped css brought in as part of a RCL. I don't see that documented.

`<link href="_content/MyClassLib/MyClassLib.bundle.scp.css" rel="stylesheet">`

**Comment by guardrex** [comment]
> there's nothing new to report here

Good ...

**_That's not a thing. You just made that up._** - David Fowler, 2015

### 😁

This issue is addressed by https://github.com/dotnet/AspNetCore.Docs/pull/20506.

It will close out when I get the CSS isolation-RCL add in the CSS isolation topic (probably Thursday morning).

**Comment by PoisnFang** [comment]
Thank you very much!

**Comment by guardrex** [comment]
Sure thing ... leave this open ... it will close automatically when the PR merges tomorrow.
