### ISSUE TITLE
Put the name of the file directly above code samples

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#20499]
I just want to mention that I really like it when the name of the file that should be created is directly above the code sample, like this:

Blazor uses natural HTML tags for UI composition. The following Razor markup demonstrates a component (Dialog.razor) that displays a dialog and processes an event when the user selects a button:

Dialog.razor
```
<div class="card" style="width:22rem">
    <div class="card-body">
        <h3 class="card-title">@Title</h3>
        <p class="card-text">@ChildContent</p>
        <button @onclick="OnYes">Yes!</button>
    </div>
</div>
...
```

Even though it is mentioned in the line of text above it, it makes it much more clear to have it directly above.  For example, this is the way that I usually read the docs:

1. First Pass - read all of it, including the code sample.
2. Second Pass, I create a sample project, and then cody and paste the code into my own app, creating the components. When the name is directly above, it is crystal clear what I need to name it.  When it is embedded in the text, I usually miss that, and name it whatever comes to mind.  Then later, I will find that the name was actually specified.

For example, this doc in the [Bind Across more than two components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0) uses the method of putting the file name directly above the code, and that is much appreciated.

If the name doesn't matter, then of course this is not needed.

I can't find it just now, but there have been instances of my being confused about this before in the docs, so wanted to bring it to your attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I agree, and you'll find that there are many that are just like that all through the docs. However, not **_all_** of them have it. For one thing, several of the topics were written by other authors, and they didn't do it. Also, we work on these docs continuously (and *quickly* 🏃) dropping in new examples all the time ... some of them miss getting the file name above them.

As I make the UE (user experience) passes on all of the topics over the holidays, I'll try to add them to any code examples where they don't appear. I'll update this example and move the file name (`Dialog.razor`) to that position.

Thanks for the feedback. I will take care of this over the ⛄ *holidays* 🎁.

**Comment by gregoryagu** [comment]
Sounds great Luke.  As a note, I saw this example of putting the file name on the right on this [site](https://bunit.egilhansen.com/docs/getting-started/writing-csharp-tests.html?tabs=mstest) and I thought I would pass it on:

![image](https://user-images.githubusercontent.com/3810620/98974212-a5ee5180-24e2-11eb-9407-9f766c156ffc.png)

**Comment by guardrex** [comment]
We don't have that capability. We only work on content here. You could suggest that to the docs engineers tho ... open an issue and explain/show it to them at ...

https://github.com/MicrosoftDocs/feedback/issues

**Comment by guardrex** [comment]
Hummmm 🤔 ...

```
[!code-cshtml[HelloWorld.razor](../../../samples/components/HelloWorld.razor)]
```

... so they're using the comment field. I didn't think we rendered anything for that.

I'll do a quick test right now and see what happens and report back in a bit.

**Comment by guardrex** [comment]
No ❤️ @gregoryagu ...

<img width="865" alt="Capture" src="https://user-images.githubusercontent.com/1622880/98976219-b4d20580-24dc-11eb-8f09-310087908c42.PNG">

I'll leave it up to you if you want to float that suggestion to them.

**Comment by gregoryagu** [comment]
Opened [#3266](https://github.com/MicrosoftDocs/feedback/issues/3266)
