### ISSUE TITLE
Blazor Todo List tutorial enhancement

### ISSUE THREAD

**Issue by KS-HW** [dotnet/AspNetCore.Docs#20498]
The first executing the dotnet run command leads to nothing. Neither an error message nor a html page are shown. 
Working on the command line is not efficient.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.1)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KS-HW ... We use the command line to make the tutorial accessible to a wide array of readers. Given that ASP.NET Core is cross-platform and cross-IDE, this makes it simplest to maintain.

I'm not sure why a template-based app wouldn't run. Your command shell is in the project root, correct?

**Comment by KS-HW** [comment]
Hi Luke, 
Thank you for your quick reaction.
I made a guess and typed the localhost url being shown within the command prompt window in a browser and - 'suprise' - saw the pages.
For a newby like me this is not self-evident. Can you add a hint? On the tutorial's pages before Visual Studio is used delivering this step as a service when you start debugging.

**Comment by guardrex** [comment]
Yes, of course. That's a great idea. I'll do that on a PR that I'm creating this morning to mop-up leftover 5.0 coverage, so we'll have it there by the end of the day.

Leave this issue open. It will close when the PR merges.

**Comment by guardrex** [comment]
Ok ... it's done. I suppose that what I thought at the time this was written is that a reader would have already performed the *Get Started* experience first. They have it over there (it's actually handled by another team) ...

https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run

... but that's a bad assumption that (a) readers will have performed that one first and (b) that they'll remember the address if they don't see it in the command shell.

Thanks again ... it will be live by the end of the day.
