### ISSUE TITLE
You have an error in the code on the page Part 2 of the tutorial -> Add a data database connection string

### ISSUE THREAD

**Issue by Realchange** [dotnet/AspNetCore.Docs#20497]
You have an error in the code on the page Part 2 of the tutorial -> Add a data database connection string
I am using Visual Studio Code under Windows. 
Therefore you can run on an compile error in the scaffold section!

Instead of: 
_"ConnectionStrings": {
    "MovieContext": "Data Source=MvcMovie.db"
  }_

You should enter: 
"ConnectionStrings": {
    "RazorPagesMovieContext": "Data Source=MvcMovie.db"
  }_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I agree,, this is the right fix. cc @wadepickett

**Comment by wadepickett** [comment]
Yep, agree.  Thanks @Realchange for taking the time to let us know.  Greatly appreciated!
