### ISSUE TITLE
Missing explanation for localization in view components

### ISSUE THREAD

**Issue by majbo** [dotnet/AspNetCore.Docs#20503]
How can I use resources in a view component? I tried to create a resource file `Resources/Views.Shared.Components.Foo.Default.resx` and injecting the IViewLocalizer in my view. Calling `GetAllStrings` on the localizer throws a `MissingManifestResourceException`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
I will have a look ASAP

**Comment by hishamco** [comment]
@majbo could please provide a minimal repo to reproduce the issue?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
