### ISSUE TITLE
Upgrading from ASPNetCore 3.1 to 5.0 breaks blazor debugging (solved)

### ISSUE THREAD

**Issue by JoelW187** [dotnet/AspNetCore.Docs#20505]
I just installed Visual Studio 2019 16.8.0 and AspNetCore 5.0. I followed the instructions in https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio and was able to compile but when I tried to run the app under IISExpress from VS2019 it failed with the error "Failed to launch debug adapter. Exception of type 'Microsoft.VisualStudio.Shared.VSCodeDebugProtocolException' was thrown.'"

I shut down VS2019 and "manually" cleaned my solution by deleting every bin and obj folder in all the projects and deleting the .vs\<project> folder where the IISExpress config is stored.

After that I restarted VS2019 and was able to launch with blazor debugging enabled and working (breakpoints worked as expected).

Just a heads up that you might want to include this in the migration document.

![image](https://user-images.githubusercontent.com/15229643/98835356-4f174800-240e-11eb-8766-68486c9027a7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @JoelW187 ... Generally, we regard this as a common situation that affects apps rather widely when they need troubleshooting.

@captainsafia, do you think this is common enough that we should mention it?

**Comment by mkArtakMSFT** [comment]
@captainsafia assigning this to you to answer the pending question from @guardrex.

**Comment by captainsafia** [comment]
> @captainsafia, do you think this is going to be common enough that we should mention it in the migration doc?

I don't think there's anything specific to debugging that we should document here.

**Comment by guardrex** [comment]
Thanks ... closing. 

@JoelW187 ... We'll keep an :ear: open for more reports like that, and they'll probably reconsider if it looks like a common thing happening.
