### ISSUE TITLE
Creating a new app with authentication doesn't match the docs

### ISSUE THREAD

**Issue by Oxyrus** [dotnet/AspNetCore.Docs#20517]
Currently, the docs imply you can create a new application with authentication right away by simply selecting *individual user accounts*.

> Select File > New > Project.
> Select ASP.NET Core Web Application. Name the project WebApp1 to have the same namespace as the project download. Click OK.
> Select an ASP.NET Core Web Application, then select Change Authentication.
> Select Individual User Accounts and click OK.

This does not work with the current version of Visual Studio (16.8), because a window asking for some Azure Credentials shows up:

![image](https://user-images.githubusercontent.com/11398826/98872730-0a5ad380-2445-11eb-8fb9-e3f8300c2af6.png)

You can't continue with the process without first filling in those settings, it isn't mentioned in the docs you have to create an Azure AD B2C, so I presume they refer to a missing option for local user storage

![image](https://user-images.githubusercontent.com/11398826/98873142-cf0cd480-2445-11eb-8907-83db4a014035.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Don't select Azure

![image](https://user-images.githubusercontent.com/3605364/98876937-70366380-2423-11eb-9e61-828c383f9b18.png)

**Comment by Oxyrus** [comment]
@Rick-Anderson there aren't any other options
![image](https://user-images.githubusercontent.com/11398826/98878894-24e77980-2452-11eb-8991-02fa7be61091.png)

**Comment by Rick-Anderson** [comment]
For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. 

You might try reinstalling VS.
