### ISSUE TITLE
Need to document which OWIN keys are supported in the translation layer

### ISSUE THREAD

**Issue by aspnet-hello** [dotnet/AspNetCore.Docs#20515]
_From @Eilon on Friday, December 12, 2014 9:34:08 AM_

Something like this table:

http://katanaproject.codeplex.com/wikipage?title=OWIN%20Keys&referringTitle=Documentation

@Tratcher FYI from our discussion.

_Copied from original issue: aspnet/HttpAbstractions#156_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34916983-6cf6-590e-0762-df0fe4e4f52c
* Version Independent ID: 1bf5bce0-c571-296e-1e8a-896af7068499
* Content: [Open Web Interface for .NET (OWIN) with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/owin.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/owin.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

---
[Associated WorkItem - 62989](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62989)

**Comment by Rick-Anderson** [comment]
@Tratcher  is the following the correct doc to add this information?

* Content: [Open Web Interface for .NET (OWIN) with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/owin?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/owin.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/owin.md)

**Comment by Tratcher** [comment]
Yes.
