### ISSUE TITLE
Core Logging Issues

### ISSUE THREAD

**Issue by EMStokely** [dotnet/AspNetCore.Docs#20520]
There are a number of bugs in the Core 3.1-5 Logging system as well as the page that explains it (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#create-logs-in-main). For that reason the whole logging/DI system feels half-baked.

1. Event Logs / Window Application logs / Event providers do not respond to custom configurations via the appsettings.json file. Even using customized JSON settings for say "EventLog", then adding that log to either a CreateDefaultBuilder's Logger or a custom ILoggerFactory type does not change the providers display. Warning and high log levels always get displayed. I had to disable or remove this provider completely.

2. Program.cs Logging - to enable complete logging inside the program.cs file I had to create a separate ILoggerFactory instance inside the top of the class to write a simple informational log. This applies if you want to log before the "CreateHostBuilder" is even called that creates the generic logger. That seems like bad design. Would be better if instead of forcing us to use a DI Logging that affects mainly just injectable Controllers, to build a much more expansive Logging system that can be added to any class, controller, or page by say simple inheritance of a base class.

3. The Logging System, like the error handler system you designed, are very specific to the MVC Controller architecture and not comprehensive enough to integrate with broader concerns in the wider application - like handling of HTTP errors, unhandled exceptions, Program or Startup class logging, full HTML5 markup support, custom class logging and DI outside the pre-build DI system. Though it makes sense to force developers into these limited boxes, as more classes, errors, and logs need to get handled and injected across libraries the limited range of these solutions becomes very limiting. Ive seen this problem with Microsoft for many years where there is not much forethought or comprehensive development of these solutions. Instead we end up rolling our own and abandoning your own ideas. It would be nice to have some things designed that impact the WHOLE application and support the full set of web standards rather than cherry-picking things that might feel good to the small team who designed it.

M Stokely

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate). 

https://docs.microsoft.com/en-us/dotnet/core/extensions/logging is the primary .NET logging doc.

Can you point out what part of the doc is wrong?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
