### ISSUE TITLE
Document HttpRepl integration with VS

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#20553]
Move the relevant content from https://devblogs.microsoft.com/aspnet/httprepl-a-command-line-tool-for-interacting-with-restful-http-services/ into a new doc. The content will need to be updated for the latest versions too. This proposed doc will replace the stopgap solution introduced in https://github.com/dotnet/AspNetCore.Docs/pull/20552.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
