### ISSUE TITLE
SEC_ERROR_INADEQUATE_KEY_USAGE in Firefox after update to .Net 5

### ISSUE THREAD

**Issue by egorpavlikhin** [dotnet/AspNetCore.Docs#20567]
# Dev SSL certificates invalid after update to .Net 5

Just upgraded a web API project from .net 3.1 (core) to .net 5 and now opening a default path in a browser fails with a certificate error:
Firefox: SEC_ERROR_INADEQUATE_KEY_USAGE

# General

I am running Windows 10.0.18363 Build 18363
I've ran ` dotnet dev-certs https --clean` and then ` dotnet dev-certs https --trust` but that didn't help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
We should add docs explaining how Firefox doesn't work by default and should need to do:
`about:config → security.enterprise_roots.enabled = true`
to make it work.

**Comment by mattjbrent** [comment]
Im still getting this error - with security.enterprise_roots.enabled set to true in firefox on multiple projects

**Comment by orbitasol** [comment]
I faced the same issue and adding this "ImportEnterpriseRoots" to about:config solve my problem.
Reference: https://superuser.com/questions/1492553/firefox-refuses-iis-express-certificate-with-error-sec-error-inadequate-key-usa

**Comment by sabuncu** [comment]
Had the same problem on Firefox.  This fixed it for me:

`about:config` → Add `ImportEnterpriseRoots` and set it to `True`

Incidentally, it works out of the box using MS Edge.

Thanks to @orbitasol.
