### ISSUE TITLE
@ symbol optional when passing EventCallback to child component

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#20565]
[EDIT by guardrex to make this update in the Component node's index topic]

I'm seeing that the `@` in `OnClickCallback="@ShowMessage"` below is optional in practice but don't see any mention of that in documentation. Is there a guideline on this?

```
<ChildComponent Title="Panel Title from Parent"
                OnClickCallback="@ShowMessage">
    Content of the child component is supplied
    by the parent component.
</ChildComponent>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrlife ... AFAIK, it's by convention. Every product unit sample/example uses this convention. I'll add a remark on this to the topic and then see if on review my hunch is correct or not.
