### ISSUE TITLE
var stream = await ... ?

### ISSUE THREAD

**Issue by harveytriana** [dotnet/AspNetCore.Docs#20562]
About: “.NET client, Server-to-client streaming”. In the first snip, the clause await shows a syntax error: “'IAsyncEnumerable<int>' does not contain a definition for 'GetAwaiter'”, whereas, without “await”, it works fine.

Is this an error in the article, or am I doing something wrong? 

I appreciate your answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-3.1&source=docs)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
Probably missing an include.  See https://github.com/dotnet/AspNetCore.Docs/tree/live/aspnetcore/signalr/streaming/samples/3.0

**Comment by harveytriana** [comment]
Hi Rick - Thanks for your attention

The reference you mention to me I had already seen. It does not match with my question, which refers to a non-web client.

I published a test project for more information, you can check in https://github.com/harveytriana/StreamingTest, look in the Program class of ConsoleClient the comment: // QUESTION.

I still believe that it is an error in the documentation, correct me if anything.

NOTE. The same happens with .NET Core 3.1

**Comment by Rick-Anderson** [comment]
What line  in https://github.com/dotnet/AspNetCore.Docs/tree/live/aspnetcore/signalr/streaming/samples/3.0 is wrong?

**Comment by BrennanConroy** [comment]
https://docs.microsoft.com/aspnet/core/signalr/streaming?view=aspnetcore-3.1&source=docs#server-to-client-streaming-1

The line:
```
var stream = await hubConnection.StreamAsync<int>(
    "Counter", 10, 500, cancellationTokenSource.Token);
```
should not have an `await`.

**Comment by Rick-Anderson** [comment]
@BrennanConroy  thanks, I'll get this fixed.

**Comment by harveytriana** [comment]
Thanks
