### ISSUE TITLE
DataAnnotations localization has no clear description

### ISSUE THREAD

**Issue by koviroli** [dotnet/AspNetCore.Docs#20579]
DataAnnotations localization has no clear description about how to implement the localization. There is a code copied from a RegisterViewModel sample but makes no sense writing a code without any mention about the localization itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think you need to read the entire article.

cc @hishamco

**Comment by hishamco** [comment]
The https://github.com/aspnet/Entropy/tree/master/samples/Localization.StarterWeb is a great resource, but we could add a section about `DataAnnotations` if it's not included in the docs

**Comment by Rick-Anderson** [comment]
@hishamco  when you have time can you PR that? Mostly point to samples  but add some advice.

**Comment by hishamco** [comment]
Seems it's there https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#dataannotations-localization-2

**Comment by hishamco** [comment]
> There is a code copied from a RegisterViewModel sample but makes no sense writing a code without any mention about the localization itself.

@koviroli what kind of the information needed here?
