### ISSUE TITLE
Scaffolding fails - Install Package Microsoft.VisualStuido.Web.CodeGeneration.Design required

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20584]
Scaffolding fails - Install Package Microsoft.VisualStuido.Web.CodeGeneration.Design required.
Should this be included in the tutorial someplace before running scaffolding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you using Visual Studio? If your VS is up to date, it will add this package.

**Comment by Rick-Anderson** [comment]
If you're using VSC, it's listed

**Comment by wadepickett** [comment]
@Rick-Anderson, I verified VS for Mac version 8.9 is requiring an install step.  I would have expected it to be included as well.  

Following the current instruction for VS for Mac, (using VS for Mac version 8.9) the scaffolding command cannot be run. It generates an error indicating dotnet-aspnet-codegenerator does not exist.

However, once the following install is run in the terminal on the command line then the scaffolding runs:
dotnet tool install --global dotnet-aspnet-codegenerator --version 5.0.0


I will fix this in #20530

@Smith-Rick,  Thanks very much for pointing out the issue.  We greatly appreciate that you took the time to let us know!  We are getting this fixed.

**Comment by Smith-Rick** [comment]
Visual Studio 2019 v16.8.1

**Comment by Rick-Anderson** [comment]
> I verified Visual Studio for Mac version 8.9 (current version as of today) is requiring an install step for dotnet-aspnet-codegenerator. 

Open a VS Mac bug and include the bug # here.

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate). For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).
