### ISSUE TITLE
Change title of SignalR-Blazor tutorial

### ISSUE THREAD

**Issue by NibblyPig** [dotnet/AspNetCore.Docs#20581]
The page says:

> In the search results, select the Microsoft.AspNetCore.SignalR.Client package and select Install.

The next step is to add a Hub. The `Hub` class does not exist in the NuGet package. It appears to exist in `Microsoft.AspNetCore.SignalR.Core` so I have had to add that too.

Next, it mentions editing Startup.cs however I this tutorial is titled ` SignalR with Blazor WebAssembly` and WebAssembly does not use `Startup.cs`, only Blazor Server uses `Startup.cs` whereas WebAssembly uses `Program.cs`.

In my `Program.cs` I can modify the services:

```
 builder.Services
                .AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) })
                .AddSignalRCore();
```

Note that I have to do `AddSignalRCore` rather than `AddSignalR`. I don't know why this is. There is also no `AddResponseCompression()`  method that I've been able to find.

This point it talks about a `Configure` method to register the Hub, however I cannot find anywhere this might go. At this point I am stuck and cannot continue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
I think you missed the very first step "Create a **hosted** Blazor WebAssembly app project".

The title could probably be updated to be clearer.

**Comment by guardrex** [comment]
How could it be clearer?

**Comment by BrennanConroy** [comment]
"Use ASP.NET Core SignalR with a Blazor WebAssembly hosted app"?

**Comment by guardrex** [comment]
Oh, you mean the title of the topic. I thought you meant the title of that section.

**Comment by guardrex** [comment]
I'd do it right now, but the docs build system is broken today. :cry:

I'll just wait until Monday morning. Perhaps, it will be back up by then.
