### ISSUE TITLE
Max file size

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/AspNetCore.Docs#20603]
First of all, "524,288 KB (512 KB)" can't right!  :-)

Secondly, the method signature is:

>  Stream OpenReadStream(long maxAllowedSize = 512000, CancellationToken cancellationToken = default)

so the default max file size would seem to be 512,000 bytes = 500 KB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Just typos @Andrew-Webb. It's also possible that the framework changed from 512 to 500 during preview releases but the final, correct value didn't make its way into the topic. I'll fix it up. Thanks for writing in on it.

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/InputFile/IBrowserFile.cs#L41-L42

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/InputFile/IBrowserFile.cs#L60

> 500 * 1024

... 512,000 bytes.
