### ISSUE TITLE
Potential issue that cannot get user secrets

### ISSUE THREAD

**Issue by junyuan** [dotnet/AspNetCore.Docs#20600]
as described in [https://stackoverflow.com/questions/64116657/could-not-find-usersecretsidattribute-on-assembly-but-it-exists-and-correct-pa](https://stackoverflow.com/questions/64116657/could-not-find-usersecretsidattribute-on-assembly-but-it-exists-and-correct-pa)
I found that we need set 
`<GenerateAssemblyInfo>true</GenerateAssemblyInfo>` in .csproj file to resolve it.

I think we set GenerateAssemblyInfo=false to avoid another error info in VS Code before.

Thanks,
Jun

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate). For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team.

**Comment by Rick-Anderson** [comment]
```
<PropertyGroup>
<UserSecretsId>Your GUID</UserSecretsId>
```
