### ISSUE TITLE
Declaring those as private breaks the compilation

### ISSUE THREAD

**Issue by moonolgerd** [dotnet/AspNetCore.Docs#20613]
[EDIT by guardrex to add the metadata]

https://github.com/dotnet/AspNetCore.Docs/blob/87d7bf6a039e6b6e950e64bb63c7c9817895c5e9/aspnetcore/blazor/file-uploads/samples/5.x/Components/FileUpload.razor#L62

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @moonolgerd ... Best to open issues on the repo from the topic (**This page** feedback form). No worries ... I'll add the metadata.

I'll get back to you tomorrow on this.

**Comment by guardrex** [comment]
Very strange. IIRC, this code was cut-'n-paste from ...

https://github.com/pranavkm/FileUpload/blob/master/Pages/Index.razor#L95

No worries ... I'll patch that right now.
