### ISSUE TITLE
Instructor Controller problem

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20625]
The instructions state: "Create an Instructors controller with EF read/write actions as shown in the following illustration:" but then the illustration does not appear if you follow the instructions using the latest visual studio version. What shows is another screen.

Instead, should the instructions read  "Create an Instructors controller using the same options for the MVC Controller with views, using Entity Framework"

Or is this actually a bug with Visual Studio 16.8.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This images might change but you should be able to follow the instructions. We'll look at this in the next sweep.
