### ISSUE TITLE
Indicate that the HomeController is being replaced and not simply added to

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20624]
In the section for "Add a class variable for the database context immediately after the opening curly brace for the class, and get an instance of the context from ASP.NET Core DI:"

It isn't clear that the existing lines of code should be replaced:
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

with 
        private readonly SchoolContext _context;

        public HomeController(SchoolContext context)
        {
            _context = context;
        }

Add wording or a before and after that helps students better understand what is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
In the [Modify the Home Controller](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-5.0#modify-the-home-controller) section.

**Comment by Rick-Anderson** [comment]
@Smith-Rick  you don't replace it, you update it. I'd keep the logger and add the DB context.

**Comment by Smith-Rick** [comment]
Sounds good to me... I'm still learning, so I am not entirely sure how you would merge the two so that it is updated vs replaced.

**Comment by andrew13165** [comment]
@Smith-Rick  - I'm also just learning but I tried this and it seemed to work:

    public class HomeController : Controller
    {
        private readonly SchoolContext _context;
        private readonly ILogger<HomeController> _logger;

        public HomeController(SchoolContext context,ILogger<HomeController> logger )
        {
            _context = context;           
            _logger = logger;
        }

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan here's an easy one.
