### ISSUE TITLE
Update contents of Rout Data

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20622]
Under the section Route Data, I would add a reference that the code can be found in Startup.cs.

The error in the documentation is that with version 5, it should be using the updated code for UseEndpoints vs UseMvc

`
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
`

where it currently shows:
`
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Smith-Rick  thanks for your through review. Hopefully @wadepickett  will get to these soon.

I think the Razor Pages version is in better shape.

**Comment by wadepickett** [comment]
Thanks @Smith-Rick!
