### ISSUE TITLE
Implement a built-in mechanism/configuration to map existing classes

### ISSUE THREAD

**Issue by hcanand** [dotnet/AspNetCore.Docs#20630]
Rewriting existing WCF ServiceContracts (Services)  & DataContracts (Messages) classes to match their equivalent gRPC counterparts (defined in *.proto files) is a lot of efforts for people already invested in WCF and which are in production.

I would highly recommend Microsoft to implement a built-in mechanism/configuration to map existing classes, similar to the implementation done in the following link:

https://github.com/protobuf-net/protobuf-net.Grpc

This would greatly save tons of efforts required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67e987d3-28fc-6fb4-3a4c-d4f6ee9cb32d
* Version Independent ID: 0587f983-8a67-b732-8292-836e5388c439
* Content: [Why migrate WCF to ASP.NET Core gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/why-migrate-wcf-to-dotnet-grpc?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/why-migrate-wcf-to-dotnet-grpc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/why-migrate-wcf-to-dotnet-grpc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
@hcanand  this is for documentation. I think you probably want to create this issue in https://github.com/dotnet/aspnetcore/issues
cc @JamesNK

**Comment by JamesNK** [comment]
Has been added here - https://docs.microsoft.com/en-us/aspnet/core/grpc/code-first?view=aspnetcore-5.0
