### ISSUE TITLE
Suggestion: It would be helpful if you provide copy button next to Project Name, Solution Name, Nuget package etc. 

### ISSUE THREAD

**Issue by chinmay-trivedi** [dotnet/AspNetCore.Docs#20643]
It would be helpful if you provide copy button next to Project Name, Solution Name, Nuget package etc. This will help us to follow article quickly (The way we have copy button next to code segments)

![image](https://user-images.githubusercontent.com/20231926/99441554-07992c00-28e6-11eb-96f2-8968bca9a114.png)
![image](https://user-images.githubusercontent.com/20231926/99441600-1aabfc00-28e6-11eb-9954-b7f5b0cb4cd4.png)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @chinmay-trivedi ... We don't control the docs system here, just the content. Make your suggestion here ...

https://github.com/MicrosoftDocs/feedback/issues

**Comment by chinmay-trivedi** [comment]
Hi @guardrex , I have clicked on below button and end up reaching to this repo. I believe below button redirection link need to be changed then.

![image](https://user-images.githubusercontent.com/20231926/99442059-c7867900-28e6-11eb-89b9-8c85c2881122.png)

**Comment by guardrex** [comment]
The feedback button/form is for "**_this page_**" ... i.e. ... this page's **content**. We control that here. We author the docs and work on doc samples here.

The docs system ... the whole system ... is controlled by another team. Your feedback is about the *docs experience*. They hope readers will see the link at the bottom of the page for "site feedback" ...

<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/1622880/99443641-b6d30480-28e0-11eb-8f70-af9d356df549.PNG">

If you think this is all too cryptic in terms of where/how to provide feedback, that's also a suggestion for that team. Like I said, we only work on the content, text and examples, on this repo.

**Comment by guardrex** [comment]
Perhaps, they should have a third button in the **Feedback** section: "Site feedback". If you agree, you can create another issue for them. They prefer to work each issue separately, so that would be a new issue from the one you opened with them.
