### ISSUE TITLE
Missing instruction to add namespace

### ISSUE THREAD

**Issue by afluiter** [dotnet/AspNetCore.Docs#20645]
[EDIT by guardrex to move the title content into the opening issue comment]

Missing instruction to reference System.Text.Encodings.Web in BlazorRignalRapp.Server which cause an error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @afluiter ... Where are you referring to in the app? Which file because I didn't see a need for it when working with the sample app.

https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/signalr-blazor-webassembly/samples/5.x/BlazorSignalRApp/Server

**Comment by guardrex** [comment]
@afluiter ... I'm going to close, but please provide more information about the difference between the sample app and your app that required the use of the additional namespace if you feel coverage is missing. If there's something here that I missed, I'll re-open this issue and work on the problem with the article.
