### ISSUE TITLE
Upgrade steps for Blazor WebAssembly (netstandard2.1 to .NET 5) are broken

### ISSUE THREAD

**Issue by qwertie** [dotnet/AspNetCore.Docs#20659]
Regarding the "Update Blazor WebAssembly projects" section, I attempted to follow those steps on a netstandard2.1 Blazor WebAssembly project that was generated a few months ago. The altered project failed to work, so next I tried creating a new ".NET Core 3.1" Blazor WebAssembly project from the standard template, and I repeated the steps again.

Both attempts failed, even though a .NET 5 Blazor Wasm project does work on my machine if it is created directly.

Based on my experience I think the following changes are needed:

1. Users should be instructed to Clean and Rebuild their project
2. Do not change the `<app>` element to `<div id="app">Loading...</div>` (in step 5) because the older project template is not designed to work with this change.
3. In Program.cs, do not change `"app"` to `"#app"` (in step 6)

Details follow.

### First Attempt (upgrade existing project) ###

After the first attempt, I got a long series of errors in the dev console of both Firefox and Chrome. It turned out that all of these errors were fixed after asking Visual Studio to "Clean" the project before building it. Here's how the errors looked in Firefox:

~~~
None of the “sha256” hashes in the integrity attribute match the content of the subresource. 2 localhost:52709
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
...
...
Error: Failed to start platform. Reason: TypeError: NetworkError when attempting to fetch resource.
    g http://localhost:52709/_framework/blazor.webassembly.js:1
    s http://localhost:52709/_framework/blazor.webassembly.js:1
    s http://localhost:52709/_framework/blazor.webassembly.js:1
    s http://localhost:52709/_framework/blazor.webassembly.js:1
blazor.webassembly.js:1:14681
~~~

And in Chrome:

~~~
Debugging hotkey: Shift+Alt+D (when application has focus)
localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:52709/_framework/Microsoft.AspNetCore.Authorization.dll' with computed SHA-256 integrity '9x0ibRAOMmEZK2MbZQ+HMnLABEaCh/R8ZHu6uDV6OFQ='. The resource has been blocked.
localhost/:1 Unknown error occurred while trying to verify integrity.
...
...
blazor.webassembly.js:1 Error: Failed to start platform. Reason: TypeError: Failed to fetch
    at blazor.webassembly.js:1
    at blazor.webassembly.js:1
    at Object.throw (blazor.webassembly.js:1)
    at s (blazor.webassembly.js:1)
~~~

After doing a Clean, these errors disappeared and a new problem occurred, which is the same problem I got in the Second Attempt:

### Second Attempt ###

This time I followed the upgrade steps directly on the .NET Core 3.1 Blazor WebAssembly project template. This time, the site's sidebar loads correctly (Home, Counter, Fetch Data tabs) but the page content is mangled - it looks blank, but it actually loads into a partially hidden region that is partially visible if you scroll down. No errors appear in the console:

~~~
blazor Loaded 8.63 MB resources
This application was built with linking (tree shaking) disabled. Published applications will be significantly smaller. blazor.webassembly.js:1:69909
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28 dotnet.5.0.0.js:1:138552
~~~

I was able to fix the formatting by changing the main element back to `<app>Loading...</app>` and changing `"#app"` back to `"#app"` in Program.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-blazor-webassembly-projects)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @qwertie ... Did you add the `MainLayout.razor.css` and `NavMenu.razor.css` files to the `Shared` folder (and use the guidance as shown for the `<div>` and CSS selector)?

**Comment by guardrex** [comment]
It looks like you didn't follow the general guidance that applies to **_all_** WASM apps at ...

https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-blazor-webassembly-and-blazor-server-projects

**Comment by guardrex** [comment]
I'll add an instruction on cleaning and rebuilding the project. I'd also like to highlight again the general troubleshoot guidance about using a clean inprivate/incognito browser for **_every test_**. I'll add a remark at the top of each of those WASM security sections to see the general coverage at the top that applies to all WASM apps ... that should help make sure that the guidance isn't missed.

Leave this issue open. It will close when the PR merges. Thanks for writing in.

**Comment by qwertie** [comment]
I see. I had followed a link from elsewhere that went directly to "Update Blazor WebAssembly projects" section. I thought it was kind of odd that instructions for different kinds of upgrades were on the same page... Now I know why.
