### ISSUE TITLE
Document changes between 3.2 and 5.0 docs 

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#20657]
Since some users are upgrading from 3.2 to 5.0, they would like a summary of the differences between the two. Things like:
- SPA vs Web
- Disabling implicit grant

We also need to document the difference between what is auto-generated in VS and what actually works. @guardrex I think you might've already done this?

**Comment by guardrex** [comment]
It's in the migration topic starting with ...

https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#standalone-blazor-webassembly-app-with-microsoft-accounts

... and over the next four sections with a fifth section to cover an apparently common problem where some app registrations have the wrong `allowPublicClient` value in the app's manifest.

**Comment by guardrex** [comment]
>  document the difference between what is auto-generated in VS and what actually works

IIRC, DR asked to **leave our NOTE** in place until VS receives the updates that it needs to do the right thing for apps that it creates. The NOTE is at the tops of our two AAD topic. For example ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0

The idea is that the dev can use VS, but they need to go down the topic and correct any bad config using the guidance in the sections.

**Comment by guardrex** [comment]
... for example ... if you already know the exact bad config that VS is setting up, we could put that into the NOTE and link down to the exact section(s).

If you're not aware of what it's breaking, I can test with VS and figure it out and take it from there with more specific guidance. If we go that way tho, is it ok if I work on it tomorrow or Monday? I'm buried in Blazor WASM security code at the moment. 😨😄

**Comment by guardrex** [comment]
I just made some improvements to the migration coverage that *hopefully* 🤞 will help ... we have quite a few combos to cover!

I added one-liners to the latter sections telling readers to be sure and follow the guidance in the first two sections that apply to all WASM apps. At least one reader jumped into the middle of the coverage and didn't apply the guidance from the first two sections. I also added a bit on cleaning and rebuilding, including how to clear package caches. I finished with cross-links to the individual topics mentioning the *Troubleshoot* sections ... I hope everyone is testing with an inprivate/incognito browser for **_every test run_**.

If you have additional ideas, we can work them on this issue along with whatever we might need to do with those VS NOTEs.

**Comment by guardrex** [comment]
Note that WRT the CORS issue, it came up on the docs repo at ...

https://github.com/dotnet/AspNetCore.Docs/issues/20482#issuecomment-725015546

I suppose we could use this issue to track two things (if you want to) ...

* Specifically determine and call out what VS is breaking in our NOTE and cross-link to the relevant section(s) for guidance.
* Head off whatever is causing this pesky CORS error that is cropping up for some devs. Will keep :eyes: on the engineering issue.

**Comment by captainsafia** [comment]
@guardrex I hadn't realized that we provided a warning about the differences between VS/CLI already.

> Specifically determine and call out what VS is breaking in our NOTE and cross-link to the relevant section(s) for guidance.

Yep, this is what @javiercn was talking about writing docs for.

> Head off whatever is causing this pesky CORS error that is cropping up for some devs. Will keep 👀 on the engineering issue.

As for the CORS stuff, at this point we're fairly confident that it is some funkiness in the way Azure AD behaves when you change app configs and not something in Blazor itself. I think we should avoid documenting anything until we've figured out what's up.

**Comment by guardrex** [comment]
> I think we should avoid documenting anything until we've figured out what's up.

I'm :ear: on the engineering issue, and I'll open a new issue when the time comes to document something.

For now, I'll proceed to determine where VS is misconfiguring apps and make the NOTE more specific. I should be able to get that done this morning (Saturday morning at the latest).

**Comment by captainsafia** [comment]
@guardrex Sounds like a plan. Thanks, Luke!

**Comment by guardrex** [comment]
Several problems discovered ...

* It sets up the app registrations with implicit grant and a Web platform config.
* Although it sets up the server API with a correct API exposure and the app itself gets a correct default token scope, the client app registration in Azure is set up to expose an API and isn't configured to access the server API.
* The server API scope is wrong for an untrusted publisher domain. It sets up the apps in the solution with the `api://` scope, but the server API registration uses the `https://` format for an untrusted publisher domain.
* The server API app's ClientID is wrong ... it's placing the API scope into the value in `appsettings.json`. It's also not adding the `Authority` for an untrusted publisher domain.

It's badly broken and would require a lot of (temporary) text to explain the correct setup, so it seems like we're taking the right direction to be general in the NOTE about what needs to be addressed.

The current NOTE reads ...

> For Blazor WebAssembly apps created in Visual Studio that are configured to support accounts in an AAD organizational directory, Visual Studio doesn't configure the app correctly on project generation. This will be addressed in a future release of Visual Studio. This article shows how to create the app with the .NET Core CLI's `dotnet new` command. If you prefer to create the app with Visual Studio before the IDE is updated for the latest Blazor templates in ASP.NET Core 5.0, refer to each section of this article and confirm or update the app's configuration after Visual Studio creates the app.

It should further say ...

* It isn't just the app ... the app registrations are bad, too.
* Also, I should refactor a bit and talk about the *solution* instead of the app. Both projects in the solution need work after VS creates it.

I'll put the following on a PR for this and ping u for review ...

> For Blazor WebAssembly apps created in Visual Studio that are configured to support accounts in an AAD organizational directory, Visual Studio doesn't configure the solution projects or the Azure portal app registrations correctly on project generation. This will be addressed in a future release of Visual Studio.
>
> This article shows how to create the solution and Azure app portal registrations with the .NET CLI `dotnet new` command and by manually creating the app registrations in the Azure portal.
>
> If you prefer to create the solution and Azure registrations with Visual Studio before the IDE is updated, refer to **_each section of this article_** and confirm or update the apps' configuration and the apps' registrations after Visual Studio creates the app.
