### ISSUE TITLE
สำหับ(นักออกแบบ)

### ISSUE THREAD

**Issue by gguyza001** [dotnet/AspNetCore.Docs#20652]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

- Explain why this topic is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

**Comment by gguyza001** [comment]
![Uploading 2EE5B430-2FAC-4007-8D92-8669831947E6.jpeg…]()

**Comment by guardrex** [comment]
Hello @gguyza001 ... Please use the **This page** feedback form at the bottom of the **English - US** topic to open an issue. Also note that we only speak English, so please place translated text into the issue.

สวัสดี @gguyza001 ... โปรดใช้แบบฟอร์มแสดงความคิดเห็น ** หน้านี้ ** ที่ด้านล่างของหัวข้อ ** English - US ** เพื่อเปิดปัญหา โปรดทราบว่าเราพูดภาษาอังกฤษได้เท่านั้นดังนั้นโปรดใส่ข้อความที่แปลแล้วลงในปัญหา

S̄wạs̄dī @gguyza001 ... Pord chı̂ bæb fxr̒m s̄ædng khwām khidh̄ĕn** h̄n̂ā nī̂ ** thī̀ d̂ān l̀āng k̄hxng h̄ạwk̄ĥx** English - US** pheụ̄̀x peid pạỵh̄ā pord thrāb ẁā reā phūd p̣hās̄ʹā xạngkvs̄ʹ dị̂ thèānận dạngnận pord s̄ı̀ k̄ĥxkhwām thī̀ pæl læ̂w lng nı pạỵh̄ā
