### ISSUE TITLE
Custom authorization attribute without policy providers

### ISSUE THREAD

**Issue by anthonn** [dotnet/AspNetCore.Docs#20650]
Could the above example with the _MinimumAgeAuthorizeAttribute_ be solved with only one attribute class and no additional AuthorizationPolicyProvider, handlers etc described in this stackoverflow question:
https://stackoverflow.com/questions/64858772/net-core-custom-authorization-with-attribute-best-practice

Or would that be considered to be a less good solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Perustaja** [comment]
This is just at a glance and from someone without extensive experience but the downside of using custom attributes like these is that it becomes harder to apply multiple rules to one controller action. For instance, if you used handlers/requirements, this would be one modular block and you could reuse it later on in tandem with others as opposed to adding multiple attributes to one action. However, you may not need that flexibility.

At the end of the day I would say authorization is very different for each project and as long as what you want is being done then what you're doing is fine. However, there is one pain point as mentioned above. You may or may not run into it.

**Comment by mjrousos** [comment]
Using `IAuthorizationFilter` is a fine alternative for MVC/WebAPI scenarios, though I think there's still value in the existing docs that cover the more flexible (if more verbose) policy/requirement/handler approach.

What we should probably do is leave the current docs as they are but add an additional page covering the use or IAuthorizationFilter. As far as I can tell, that interface isn't well documented at the moment.

**Comment by blowdart** [comment]
Combining in this case is probably going to add confusion rather than the more explicit example we have now with everything separate. It's fine as-is.
