### ISSUE TITLE
First-MVC Series: New-Field cshtml example should use MovieDateRatingDAmult.cs model and included only when defined

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#20665]
The cshtml files for view Views/Movies/IndexGenreRating.cshtml needs to use the model https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie3/Models/MovieDateRatingDAmult.cs.  It also needs to be set up to use #if to be included only when defined.

**Comment by Rick-Anderson** [comment]
@wadepickett  this is the wrong approach.

**Comment by Rick-Anderson** [comment]
No, the model defined is the earliest stage, not this code. The code needs to be in the final build.
