### ISSUE TITLE
Info on type of component parameters

### ISSUE THREAD

**Issue by vborovikov** [dotnet/AspNetCore.Docs#20675]
It's not clear if Blazor can support custom types for the component parameters or not. Provided examples use built-in primitive types `string` and `int`.  It's not stated what type of a property tagged with `[Parameter]` attribute could be. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vborovikov ... Great :question: ... Answer: **_Yes!_** ... and as you suggest, we need to surface that information.

I'd like to add it where component parameters are defined in the [Component params section of the Components overview topic](https://docs.microsoft.com/aspnet/core/blazor/components/?view=aspnetcore-5.0#component-parameters), and I'd like to cross-link "component parameter" here to that section.

@captainsafia ... Are u aware of any restrictions, limitations, or gotchas?

We currently say that they are ...

> ... public properties on the component class with the [Parameter] attribute ...

... so if there aren't any restrictions, the wording would go something like the following. Note that the C# doc on propeties uses the word "simple" over "primitive," so we probably should go that way.

> ... public simple or complex properties on the component class with the [Parameter] attribute ...

**Comment by captainsafia** [comment]
I can't recall any restrictions that are worthy of documenting in this way so I think that language works well!

**Comment by vborovikov** [comment]
Initially I wanted to investigate what are requirements for these custom types are because my code works if I use a parameter with `string` type but when I use my custom struct for the parameter type it stops working. So I assumed that I'm missing some traits like specific interface implementation in my custom type or some kind of initialization code. This kind of information I was looking for on this page.

**Comment by guardrex** [comment]
> custom struct

Structs are supported types for parameters with the usual struct characteristics, so I think it's specific to some kind of struct condition in your scenario. Open a product unit issue at ...

https://github.com/dotnet/aspnetcore/issues

... and show them your struct, your parent component, and your child component with the parameter. I suspect that they'll uncover something about your struct that does break parameters.

Please add a `cc: @guardrex` to your opening issue comment or return here and post a comment with the answer. It might be something that we need to call out in the topic.

In the meantime, I'm going to make that small change that I pointed out :point_up: now. This issue will close automatically, but it's ok if you come back later and post the answer on the struct situation here. I'll re-open this for more work if that's what we need to do.
