### ISSUE TITLE
Need to document adding Using System;

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20670]
When modifying the inheritance.cs file with the copied code, users also need to know to add "using System;"

This is due to the inclusion of the DateTime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Most folks know that. This is an advanced tutorial at an advanced stage. Thanks for the feedback, I'll consider adding that when I next update.
