### ISSUE TITLE
Component virtualization section link missmatch

### ISSUE THREAD

**Issue by xiety** [dotnet/AspNetCore.Docs#20686]
Current link directs to:
ASP.NET Core Blazor forms and validation.
https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#radio-buttons

Instead of:
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a85af-14dd-7102-e2f9-d3850e0e0658
* Version Independent ID: d20b1af2-b6a4-5428-3e79-b2c8f8881446
* Content: [What's new in ASP.NET Core 5.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-5.0?view=aspnetcore-5.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-5.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-5.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sorry about that @xiety ... We created that new topic and this cross-link got under the radar and became a 😈. I'll patch this up right now. Thanks for the report.
