### ISSUE TITLE
PWA: service-worker registration

### ISSUE THREAD

**Issue by josekpaul** [dotnet/AspNetCore.Docs#20684]
[EDIT by guardrex to fix the code block. @josekpaul ... use a triple-backtick on lines around the code block to get them formatted]

Thank you, this document helped. The service-worker registration for PWAs changed in .net5, and it caused build error (file parameter not available for a service-worker copy step). This line needs to be added to the client csproj file:

```xml
<ItemGroup>
  <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @josekpaul. I'll get to this soon but probably early next week. I'll provide info in the migration topic and also update the main [Blazor PWA doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio).
