### ISSUE TITLE
Not able to Login in when add @attribute [Authorize] in _Imports.razor

### ISSUE THREAD

**Issue by hanslai** [dotnet/AspNetCore.Docs#20689]
According to [Require authorization for the entire app](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-5.0#require-authorization-for-the-entire-app) We can protect the entire app by adding the following two lines in in _Imports.razor.
```
@using Microsoft.AspNetCore.Authorization
@attribute [Authorize]
``` 

Yet, when adding `@attribute [Authorize]`  in` _Imports.razo`, the login link will do nothing.   Instead of redirect to the IDP, the page will get redirect to `https://localhost:44399/authentication/login?returnUrl=https%3A%2F%2Flocalhost%3A44399%2F`, so user is not able to login.   And the browser's console will show
```
blazor.webassembly.js:1
 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
```
remove `@attribute [Authorize]` from  _Imports.razor, then login will redirect to IDP's login page successfully and user is able to login.

Step to duplicate:
use Visual Studio
1. Create a new Blazor WASM app and set Authentication to "Individual User Accounts"
2. Add the correct OIDC data in `appsettings.json` of `wwwroot`
3. Run the App
4. click the login link 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c572618c-8b98-95af-6a75-1f8e413071db
* Version Independent ID: 8670b314-460d-3194-c53b-9a44f39c6b2a
* Content: [Secure ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hanslai ... Open this for the product unit on their repo ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc:@guardrex` to your opening comment or come back here later and leave a cross-link if you come to a solution with them that we should document. I'll re-open this issue and work on it if we need to make a docs update.

**Comment by guardrex** [comment]
BTW --- Search their open and closed issues first before opening a new issue just to make sure that someone else hasn't already opened an issue there on this subject.

**Comment by m-gug** [comment]
Hello!
Just stumbled upon the same problem and found a solution to it too. However, it seems to me to be more of a documentation problem than a technical one.

If you add `@attribute [Authorize]` in the `_Imports.razor` as described, then you have to add `@attribute [AllowAnonymous]` in the `Authentication.razor` so that the forwarding works.

**Comment by guardrex** [comment]
Right ... that makes sense. I believe that the original content was supplied directly by the PU, so I felt it was safer to ask them about such a change. I have a *healthy fear* 😨 these days for security updates and like to have them verify all security updates to security content that they provide. It's easy enough to ping them on the update for this tho, so I'll work this forward asap. Thanks for commenting, @m-gug!

**Comment by MTwiford** [comment]
> Hello! Just stumbled upon the same problem and found a solution to it too. However, it seems to me to be more of a documentation problem than a technical one.
> 
> If you add `@attribute [Authorize]` in the `_Imports.razor` as described, then you have to add `@attribute [AllowAnonymous]` in the `Authentication.razor` so that the forwarding works.

Thank you! This solved my issue.
