### ISSUE TITLE
DisplayName support for InputText and InputTextArea?

### ISSUE THREAD

**Issue by ErikApption** [dotnet/AspNetCore.Docs#20682]
InputText and InputTextArea do have a DisplayName parameter but they don't seem to be working. Are they supposed to support the DisplayName annotation as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ErikApption ... Both are based on `InputBase`, which has the [`DisplayName`](https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/InputBase.cs#L56) property. However, engineering states that `DisplayName` is only supported at this time for `InputDate`, `InputNumber`, and `InputSelect`.

They might be planning to expand use of the parameter in a future release. If you can't find anything searching the [product unit's issues](https://github.com/dotnet/aspnetcore/issues) (check both open and closed issues), you can open a new issue to ask them there.

If you end up opening a new issue on their repo, please add a `cc: @guardrex` to your opening comment or add their response to this issue. What we might do is indicate in the doc that `DisplayName` for other components is coming in a future release.

I'll close this for the time being and re-open it if this becomes actionable based on their response.

Reference: https://docs.microsoft.com/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#display-name-support
