### ISSUE TITLE
Add > Scaffolded Item section does not work

### ISSUE THREAD

**Issue by johnbcable** [dotnet/AspNetCore.Docs#20692]
When trying to add a scaffolded item to the MvcMovie solution the process fails to complete with the errors as shown in the attached file
![MvcMovieScaffolidngError](https://user-images.githubusercontent.com/2606316/99808029-30186480-2b38-11eb-8b9e-7064d9d595cb.jpg)

So I cant complete the tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Exit VS and restart. If that doesn't fix it, 
use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team.

**Comment by hawihaw** [comment]
Have had the same problem and it did not work with restarting VS

**Comment by robbkenobi** [comment]
I had the same issue too, but with some investigation I discovered that I had a malformed appsettings.json file (the final curly brace } was missing. Scaffolding worked fine after that

**Comment by hawihaw** [comment]
Thanx  robbkenobi you were spot on, Silly of me not recognize bad formed  json.
