### ISSUE TITLE
For versions lower than 3.0, the page shows duplicate content

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetCore.Docs#20697]
For versions lower than 3.0, the page shows duplicate content.

Shoukd this content even be available for these versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-1.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@paulomorgado  2.1 is still under LTS.

**Comment by paulomorgado** [comment]
Is that why it shows this?

> By Rick Anderson
> 
> This tutorial examines the Razor Pages created by scaffolding in the previous tutorial.
> 
> By Rick Anderson
> 
> This tutorial examines the Razor Pages created by scaffolding in the previous tutorial.
