### ISSUE TITLE
Confusing asp-for sentence

### ISSUE THREAD

**Issue by jesslilly** [dotnet/AspNetCore.Docs#20693]
This sentence is confusing:

"and move before the m."

I don't understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
As in `m => m.Property1`
