### ISSUE TITLE
Catch with IdentityServer when using Blazor WA hosted.

### ISSUE THREAD

**Issue by tesar-tech** [dotnet/AspNetCore.Docs#20699]
[EDIT by guardrex to update the metadata]

There is a problem with IdentityServer that needs to sign and perform token validations. After publishing it results in `500.30` error. (And [this error](https://stackoverflow.com/questions/64186403/blazor-web-assembly-app-net-core-hosted-publish-runtime-error) in stream log). This can be solved by creating self signed certificate or changing `ASPNETCORE_ENVIRONMENT` settings in App Service configuration to Development (not suitable for production). 

Summarized [here](https://gavilan.blog/2020/08/18/blazor-using-a-self-signed-certificate-for-identityserver4-in-azure-app-service/).

Or is there some better solution? 

Please save future time of fellow "Blazorers" and mention this in documentation. (Or I can do it, just need some fact check on the paragraph above)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tesar-tech ... This is somewhat covered by the custom domain configuration because that section covers the use of a self-signed cert with a production app in Azure Apps. Thanks for the offer to help, but this will require some careful choice of words and guidance, so I'll take care of it.
