### ISSUE TITLE
Where is the Applies To section for this resource ?

### ISSUE THREAD

**Issue by rsschomburg** [dotnet/AspNetCore.Docs#20715]
[Enter feedback here]
Where is the Applies To section for this resource ?:  (see referrer URL)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-5.0#opt-out)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Where is that?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
