### ISSUE TITLE
Why do we need to call `bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);`

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/AspNetCore.Docs#20717]
Why do we need to call `bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);` in the [custom model binder sample](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#custom-model-binder-sample)?

Also, can you please provide a test case that would go wrong if that is not called?

I have the following implementation and it seems to be working fine.

```c#
public Task BindModelAsync(ModelBindingContext bindingContext)
{
    var modelName = bindingContext.ModelName;
    var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);
    var value = valueProviderResult.FirstValue!;
    var model = MyModel.Get(value);
    if (model == null)
        bindingContext.ModelState.AddModelError(modelName, $"The value '{value}' is not valid.");
    else
        bindingContext.Result = ModelBindingResult.Success(model);
    return Task.CompletedTask;
}
```

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#custom-model-binder-sample)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
