### ISSUE TITLE
Provide Perspective Versus CSS Layouts

### ISSUE THREAD

**Issue by CincySteve** [dotnet/AspNetCore.Docs#20716]
I must confess to finding it difficult to fully grasp the 3 or 4 dimensional chess this description forces me to grasp, given all the default and override rules it expresses.  I would welcome some perspective on the pros and cons of this layout scheme versus using CSS layouts.

**Comment by guardrex** [comment]
Hello @CincySteve ... Please re-open the issue from the bottom of the topic that you're looking at with the **This page** feedback form. It will attach metadata and ping the author of the topic.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
