### ISSUE TITLE
Provide Perspective Versus CSS Layout

### ISSUE THREAD

**Issue by CincySteve** [dotnet/AspNetCore.Docs#20723]
CSS also provides a layout scheme, one that allows multiple components to be integrated at various places in a layout using CSS id and class attributes.  It would be helpful to have some perspective on the pros and cons of using Blazor layouts versus CSS, or in using them together.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello again @CincySteve ... This is too subjective an issue for us to cover in the docs. We focus on reference topics to cover the framework behaviors and usually only get into *best practices* for perf and security. We'll have to leave this one to the blog-o-sphere.
