### ISSUE TITLE
Second example in "Kerberos authentication and role-based access control (RBAC)" wrong

### ISSUE THREAD

**Issue by hAmpzter** [dotnet/AspNetCore.Docs#20729]
Example is wrong:

```
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
    .AddNegotiate(options =>
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            options.EnableLdap("contoso.com");
            options.MachineAccountName = "machineName";
            options.MachineAccountPassword = "PassW0rd";            
        }
    });
```

Should be:

```
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
    .AddNegotiate(options =>
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            options.EnableLdap(settings =>
            {
                settings.Domain = "contoso.com";
                settings.MachineAccountName = "machineName";
                settings.MachineAccountPassword = "PassW0rd";
            });
        }
    });
```

Note: Update with the if-statement that I forgot. 🙂 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  please review

**Comment by blowdart** [comment]
On vacation. Passing to @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Yea the recommendation is correct, this should be updated.
