### ISSUE TITLE
"dotnet watch run" could be helpful for new learners

### ISSUE THREAD

**Issue by papalanga** [dotnet/AspNetCore.Docs#20728]
[Enter feedback here]
Just a minor suggestion instead of having them stop the application multiple times during the tutorial ... it could be a good time to introduce "dotnet watch run"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
**_I like IT!_** ... but it will need to wait a bit. I'm busy for the next few weeks and then leaving on vacation for a while. I'll get to this when I get back. Thanks for the suggestion.

**Comment by guardrex** [comment]
I might be able to do this tho when I hit this topic for a UE pass ("User Experience"). I'll note it on my tracking issue and try to reach it soon ... before I leave 🏖️.

**Comment by papalanga** [comment]
Thanks for the positive feedback. I'm all for improving productivity :-)

Also, I'm happy to help out where I can. I'm even up for doing some Blazor tutorials that haven't been released yet if you'd like someone to try them out. I'm coming from a heavy WPF background.

Enjoy that vacation!
