### ISSUE TITLE
Updating Java library version

### ISSUE THREAD

**Issue by alexalok** [dotnet/AspNetCore.Docs#20733]
Tutorial suggests adding the following line:

`implementation 'com.microsoft.signalr:signalr:1.0.0'`

This version of the library, however, is heavily outdated and doesn't work well with the latest SignalR Core 5.0.0 server. 
Perhaps it should be changed to `implementation 'com.microsoft.signalr:signalr:5.0.0'`, which is currently [the latest version](https://search.maven.org/artifact/com.microsoft.signalr/signalr/5.0.0/jar).
We've run into this issue recently and it took us some time to figure out the reason behind it due to a semi-working functionality when combining an outdated client version with the latest server version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e954a77-daa3-980c-0a0b-c4e7dabc8ed0
* Version Independent ID: 09e7b88b-8373-89d4-7360-d71370c095da
* Content: [ASP.NET Core SignalR Java client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/java-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/java-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @mikaelm12
* Microsoft Alias: **mimengis**

**Comment by BrennanConroy** [comment]
> semi-working functionality when combining an outdated client version with the latest server version

Could you explain please? Older clients should continue working with newer servers, obviously any new features would need a client update, but the core functionality should continue to work.

**Comment by alexalok** [comment]
We had issues with the client-side deserialization - some of the fields were missing in the messages received from the server. After updating client library to 5.0.0 everything worked fine. Perhaps we used something that is not supported on 1.0.0.
