### ISSUE TITLE
Mention the InputFormatterException as option for InputFormatterResult.Failure

### ISSUE THREAD

**Issue by OldrichDlouhy** [dotnet/AspNetCore.Docs#20732]
The examples do not mention usage of `InputFormatterException` which can be thrown instead of returning the `InputFormatterResult.Failure()` from the `ReadRequestBodyAsync` method.

Advantage of the the exception is that it allows returning meaningful message from the custom input formatter.

For example if the input formatter is reading CSV data and it validates required columns, the exception allows to set the exception message like "Column X is missing" which then translates to bad request response with the message.

Simply returning `InputFormatterResult.Failure` returns 404 with message like "data is NULL" which is not user friendly as it is not obvious what is the issue with input data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  for comment

**Comment by serpent5** [comment]
@Rick-Anderson This might be undocumented for a reason, so it might be worth running this past PU. In the example `text/vcard` input formatter, the call to `TryAddModelError` ensures that an error message is set for `ModelState`, so the benefit cited in this issue is covered by that.

I noticed that the sample controller has `return BadRequest()` instead of `return BadRequest(ModelState)`, though, so that could be fixed to surface the error message in the 400 response. Once that's done, a helpful error message is displayed in the response.

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
> For example if the input formatter is reading CSV data and it validates required columns

If you have concrete information about data, adding content to ModelState is the way to go. That way you aren't limited to the first issue with your data format: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs#L270. Consider using the exceptions for truly exceptional cases as opposed to issues with the data format.
