### ISSUE TITLE
Some improvement on PWA authentication section

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/AspNetCore.Docs#20742]
Hi

I've made a blazor wasm application, aspnet core hosted, with google authentication and custom AuthenticationStateProvider. When i try to create the same application from scratch but selecting Progressive Web App upon project creation, i'm not able to authenticate users. I've replicated the situation by building again a simple blazor wasm app with google authentication and custom AuthenticationStateProvider and again the exact same steps on the PWA version.
It doesn't work!
In this documentation is missing what we are supposed to change in PWA application to be able to login with identity providers.

Debug:
I see that the redirection from "user/signin"  back to "/" is not working, it stays in address "user-signin" and in the log on visual studio there's a error message saying: "Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed."
In the network tab i see the navigation to "user/signin" and at the end, when trying to retrieve the user, the data for "/user" is retrieved from the service worker.
I cant understand what is going on but the documentation should state what are the adaptations we should do on the PWA scenario to keep the login working...

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8c235e-1ce4-046f-e848-294096361922
* Version Independent ID: 6240f626-97d4-ace0-5e34-20e1c3592f86
* Content: [Build Progressive Web Applications with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/progressive-web-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/progressive-web-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ricardoaraujo00 ... Please open this for the product unit ...

https://github.com/dotnet/aspnetcore/issues

... and please add a `cc: @guardrex` to your opening comment. I'd like to see what they say about this scenario. If they provide guidance that clears it up, I'll re-open this issue and add the guidance to the topic.

**Comment by Ricardoaraujo00** [comment]
Well seems that this is in fact a problem due to the service worker on the PWA application.
I've found this suggestion of Steve Sanderson [here](https://github.com/dotnet/aspnetcore/issues/20888), and this should be on this documentation on PWA section. 
But i followed his instructions and even so the service worker doesn't exclude the login urls from caching. Maybe something had changed from 2017 to now.... Should i question there??

**Comment by guardrex** [comment]
Yes, that's a good idea.

> followed his instructions and even so the service worker doesn't exclude the login urls from caching

Yes ... add that to your issue and cross-reference the original.

**Comment by Ricardoaraujo00** [comment]
Well, seems i cannot comment there as the issue is closed and limited to collaborators.
Even so this problem shouldn't arise as i figured out that on development the service worker should pull always from server.
This code is on "service-worker.js" which is the one used on development:
```
"// In development, always fetch from the network and do not enable offline support.
// This is because caching would make development more difficult (changes would not
// be reflected on the first load after each change).
self.addEventListener('fetch', () => { });
.js  
```
So in fact seems that the Steve Sanderson solution may be correct even today.
This leave us with no clues for the reason why the service worker his hindering the login procedure even in development... 

Debug:
I've made a new project with userlogins in app to check if there is any difference in the development  service-worker and there wasn't any. In the published version of the service-worker there is in fact the exclusion as Steve Sanderson stated
```
const shouldServeIndexHtml = event.request.mode === 'navigate'
            && !event.request.url.includes('/connect/')
            && !event.request.url.includes('/Identity/');
```

There must be something else that we must change in order to make PWAs with a custom identity provider
I don't see any major difference on the client side project. 
The only one is in program.cs.
Mine:
```
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();
```
Templated:
```
builder.Services.AddHttpClient("BlazorApp5PWAwithlogins2.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

            // Supply HttpClient instances that include access tokens when making requests to the server project
            builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp5PWAwithlogins2.ServerAPI"));

            builder.Services.AddApiAuthorization();
```

When i move the mouse over "builder.Services.AddApiAuthorization();" it says: "Adds support for authentication for SPA applications using ApiAuthorizationProviderOptions and the RemoteAuthenticationState"

I check that this is dependent on the Microsoft.AspNetCore.Components.WebAssembly.Authentication nuget package but for some reason the extension method is not detected. On the users in-app templated project the installed version of this nugget package is 3.2.1.0, which i cannot install in my project due to my project being 3.1 version. But i can install the 5.0 version, but the extension code is not detected.

On the users in-app templated project there is also this on the start-up class:
```
services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

            services.AddAuthentication()
                .AddIdentityServerJwt();
```
and "app.UseIdentityServer();" on the configure method still inside startup.cs

Seems there must be done some amount of tweeking to be able to make a PWA Blazor app login with a custom login and custom authentication state provider. Some documentation and guidance is needed to accomplish this because this is a much needed feature.

**Comment by guardrex** [comment]
Best to post that where they'll see it on the engineering issue ...

https://github.com/dotnet/aspnetcore/issues/28101

> seems i cannot comment there as the issue is closed and limited to collaborators.

I meant comment on your issue and cross-link that closed issue in your issue.

**Comment by guardrex** [comment]
From the product unit issue ...

> On the service worker script i did not included the return url from the google signin service in the service worker excluded cache adresses on the onFetch method. Like so:
>
> ```javacript
> const shouldServeIndexHtml = event.request.mode === 'navigate' && !event.request.url.includes('/user') &&
>   !event.request.url.includes('/user/signin') && !event.request.url.includes('/signin-google');
> ```
>
> I had tried it before but i was wrongly excluding "/user/signin-google" and the correct address to exclude should be "/signin-google", as it is on the last line.
