### ISSUE TITLE
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory) is wrong

### ISSUE THREAD

**Issue by vit100** [dotnet/AspNetCore.Docs#20751]
There is no ILoggerFactory in Configure.

Document is misleading

> The only types the generic Host supports for Startup constructor injection are IHostEnvironment, IWebHostEnvironment, and IConfiguration
See [https://github.com/aspnet/Announcements/issues/353](https://github.com/aspnet/Announcements/issues/353)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Starting at [Create a custom logger](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#create-a-custom-logger)

```
public void Configure(
    IApplicationBuilder app,
    IWebHostEnvironment env,
    ILoggerFactory loggerFactory)
{
    loggerFactory.AddProvider(new CustomLoggerProvider(new CustomLoggerConfiguration()));
```

**Comment by Rick-Anderson** [comment]
Replace with https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider

**Comment by serpent5** [comment]
Sure thing. I'll get it sorted soon. 👍

**Comment by serpent5** [comment]
@vit100 The announcement you referenced is specific to the `Startup` _constructor_. The `Startup.Configure` method is capable of receiving `ILoggerFactory`.

**Comment by vit100** [comment]
You are right. 
Closing issue
