### ISSUE TITLE
SingleOrDefaultAsync throws if multiple rows returned, not null

### ISSUE THREAD

**Issue by THanev** [dotnet/AspNetCore.Docs#20754]
In the "Examine SQL Queries" section there is wrong explanation for SingleOrDefaultAsync method - "If the query would return multiple rows, the method returns null."
Actually, if the query would return multiple rows, the method **throws** exception. And if there are no rows, it will return default value which is null in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Container issue for EF/MVC #17465
