### ISSUE TITLE
Update Many-to-Many example for EF Core 5

### ISSUE THREAD

**Issue by johnmackerras** [dotnet/AspNetCore.Docs#20757]
The Many-to-Many section contains the phrase "(EF 6.x supports implicit join tables for many-to-many relationships, but EF Core doesn't. For more information, see the discussion in the EF Core GitHub repository.)"

For EF Core 5 this statement is no longer true. Please work through the examples showing how CourseAssignment can be constructed as a raw/native Many-to-Many and also please show how Enrollment can be rebuilt as a Many-to-Many with Payload, using the Enrollment class. including how to access the Grade field in code.

Please also reflect these changes in the Razor version of this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [Tutorial: Create a complex data model - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Many-to-Many relationships](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-5.0#many-to-many-relationships)
[EF Core 5.0 supports many-to-many relationships without explicitly mapping the join table.](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many)
