### ISSUE TITLE
Example uses "For internal use only" method

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#20753]
The [InputText based on the input event](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#inputtext-based-on-the-input-event) section uses [CreateBinder()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.eventcallbackfactorybinderextensions.createbinder?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_EventCallbackFactoryBinderExtensions_CreateBinder_Microsoft_AspNetCore_Components_EventCallbackFactory_System_Object_System_Action_System_Boolean__System_Boolean_System_Globalization_CultureInfo_), which is labeled as "For internal use only."

Please update with a safe alternative. See https://github.com/dotnet/aspnetcore/issues/24883#issuecomment-710099785 for a related discussion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mrlife ... Let's ask ..........

@pranavkm @SteveSandersonMS  ... The original version of this (it was updated at least once along the way) was a Ryan bit that came at 3.0 Preview 9 ...

* Issue: [[Preview 9] Add sample for InputText with oninput (dotnet/AspNetCore.Docs #13912)](https://github.com/dotnet/AspNetCore.Docs/issues/13912)
* PR: [Add sample for InputText with oninput (dotnet/AspNetCore.Docs #14123)](https://github.com/dotnet/AspNetCore.Docs/pull/14123)

Do you want to keep it, replace it, or 🔪💀 **_kill it?_** 💀🔪

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS can you please look into this and see whether there is an alternative API we can use in this sample? Thanks!

**Comment by SteveSandersonMS** [comment]
@guardrex Do you remember any details about why the sample was written that way? My first thought is there's no obvious reason to use `EventCallback.Factory.CreateBinder` here - it looks like it could just use `@bind`. That is, `CustomInputText.razor` could be:

```razor
@inherits InputText
<input 
    @attributes="AdditionalAttributes" 
    class="@CssClass" 
    @bind="CurrentValueAsString"
    @bind:event="oninput" />
```

Do you know of some reason that doesn't work?

**Comment by guardrex** [comment]
It looks like it was just a workaround back when Ryan sent it over in August, 2019 (ages ago during Preview 9) ...

https://github.com/dotnet/AspNetCore.Docs/issues/13912

**Comment by SteveSandersonMS** [comment]
OK cool, looks like it could be updated then!

**Comment by mrlife** [comment]
Thank you all, it works great!
