### ISSUE TITLE
Many-to-Many Relationships now supported in EF 5.x

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20763]
[Many-to-Many Relationships](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio#many-to-many-relationships)

See [EF Core 5.0 supports many-to-many relationships without explicitly mapping the join table.](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew#many-to-many)

Related #20757 #19931

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JeremyLikness  could you provide the new model/code and outline and I'll update the 5.x version of the document?

**Comment by JeremyLikness** [comment]
I'm working on a 5.0 "clean" version that we can hopefully update from. Will keep you posted and have a branch checked out already. @Rick-Anderson
