### ISSUE TITLE
Typo in variable name

### ISSUE THREAD

**Issue by sosandris** [dotnet/AspNetCore.Docs#20760]
In this section: [Use Managed identities for Azure resources](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0#use-managed-identities-for-azure-resources)
In the line:
```
config.AddAzureKeyVault(SecretClient, new KeyVaultSecretManager());
```
the variable ```SecretClient``` should be ```secretClient``` (lower case)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[This code](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/Program.cs#L76-#L78)

@FrankieTF please review. Any chance you could fix this?

**Comment by FrankieTF** [comment]
> [This code](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/3.x/SampleApp/Program.cs#L76-#L78)
> 
> ```
> var secretClient = new SecretClient(new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
>                                                          new DefaultAzureCredential());
> config.AddAzureKeyVault(SecretClient, new KeyVaultSecretManager());
> ```
> 
> @FrankieTF please review. Any chance you could fix this?

I have sent another [Pull Request](https://github.com/dotnet/AspNetCore.Docs/pull/20771) to solve this. Sorry for missing this change.

**Comment by scottaddie** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs/pull/20771
