### ISSUE TITLE
Book Class

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#20773]
Using Version 5 and the Swagger test page. 

When trying to insert data using the PUT, the book name always appears null. 

I had to change the book.cs "BookName" property to just "Name". Once I did that, the data inserted correctly. 

Is this expected and maybe needs an update to the document? Or did I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Master list: Create a web API and MongoDB #16196

**Comment by serpent5** [comment]
Fixed in #24126, which now uses `System.Text.json` for the 6.0 version.
