### ISSUE TITLE
Suggestion to add a chapter and modify the sample app

### ISSUE THREAD

**Issue by KurtP20** [dotnet/AspNetCore.Docs#20775]
Two suggestions if I may:
1) It would be nice if you could add a section describing how to use DbContextFactory together with Identity. It was not straight forward to get that up and running, see [this question on SO](https://stackoverflow.com/questions/64169025/using-identity-with-adddbcontextfactory-in-blazor).

2) The sample project does not use the recommended `Dispose` pattern, not sure if this is done on purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
@JeremyLikness If you confirm that the SO answer is correct ...

https://stackoverflow.com/questions/64169025/using-identity-with-adddbcontextfactory-in-blazor

... I can add it to the topic and ping u for review.

>  sample project does not use the recommended Dispose pattern

Referring to in the topic ...

> The sample app ensures the context is disposed when the component is disposed:

Reference: https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#scope-to-the-component-lifetime-5x

@KurtP20 ... but it does tho where it's relevant to do so at ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/5.x/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/EditContact.razor#L183-L186

**Comment by KurtP20** [comment]
@guardrex Regarding `Dispose` pattern: The sample app only implements `Dispose`, and when I did so in my app, code analysis complained about violation of rule [CA1063](https://docs.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1063) and [CA1816](https://docs.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1816). I think the recommended pattern is (as suggested by VisualStudio):
```
// define as member variable
private bool disposedValue;

protected virtual void Dispose(bool disposing)
{
    if (!disposedValue)
    {
        if (disposing)
        {
            _context.Dispose();
        }
        disposedValue = true;
    }
}

public void Dispose()
{
    Dispose(disposing: true);
    GC.SuppressFinalize(this);
}
```

**Comment by guardrex** [comment]
Thanks for that clarification @KurtP20 ... @JeremyLikness will be along at some point to respond and advise on that.

**Comment by JeremyLikness** [comment]
Hi @KurtP20  and @guardrex... there is certainly nothing wrong with implementing the full pattern. If we feel it makes the sample more complete we can. The idea behind the disposing overload is the fact the class can be derived and there is potential for a derived class to implement a finalizer. When I am confident my code is not going to deal with unmanaged resources and know there is no finalizer in the chain I typically just use the simpler pattern, but again no issue with implementing the full pattern.

**Comment by guardrex** [comment]
@JeremyLikness ... It's best for the full pattern scenario if you (or @KurtP20) submit a PR if you think it should be covered. I'm buried in other Blazor work ⛰️⛏️ right now ... will be out for an extended holiday vacation and not back until 2021 ... and then return to *high priority issues* that will keep me 🏃 for a while.

However, the first bit is quick ... the SO answer for `DbContextFactory` with Identity. If you don't want to cover the disposal pattern and just get that first piece in (if the SO answer is correct), I can knock that out tomorrow morning and ping u on the PR.

**Comment by JeremyLikness** [comment]
> Two suggestions if I may:
> 
> 1. It would be nice if you could add a section describing how to use DbContextFactory together with Identity. It was not straight forward to get that up and running, see [this question on SO](https://stackoverflow.com/questions/64169025/using-identity-with-adddbcontextfactory-in-blazor).

@ajcvickers see the referenced SO question/answer... does that look right to you? Aside from EnableSensitiveDataLogging.

**Comment by ajcvickers** [comment]
@JeremyLikness It looks correct. However, this should be filed as an issue against ASP.NET Core Identity such that it is not necessary. It should be possible to use `AddEntityFrameworkStores` with `AddDbContextFactory` without having to make any custom registrations.

/cc @HaoK @blowdart I'm willing to help on the implementation of this for 6.0. It's not something we should patch.

**Comment by guardrex** [comment]
On the doc side, I'll proceed (sans the call for `EnableSensitiveDataLogging`).

I won't be able to version it for <6.0 for quite a long time, but I'll open a follow-up docs issue that's cross-linked to the engineering issue and get it versioned correctly later.

Please provide the cross-link to the engineering issue when it's available.

**Comment by KurtP20** [comment]
The `Dispose` pattern is not very important, so it's fine to leave the sample as it is now. 

Thanks for adding the docs regarding Identity and for changing `AddEntityFrameworkStores` to accept a DbFactory in 6.0.

**Comment by guardrex** [comment]
@KurtP20 ... I just looked to prepare for an update to the topic, but this pattern seems to already be covered. See the end of the following section :point_right: https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#new-dbcontext-instances-5x

**Comment by KurtP20** [comment]
Oh. I read that page multiple times as it served as my primary source for figuring out how to use DbFactory. Unfortunately I must have missed that part (or it was added later). But the information is there, I agree. And if the link to Identity works, it should also be obvious enough that one finds this information.
Sorry I kept you from other things, I think we can close this case now.

**Comment by guardrex** [comment]
No worries @KurtP20 ... If we get more feedback on the disposal aspect of our discussion, then we have the background we need to address it. We also fixed a broken link here. It's all good.
