### ISSUE TITLE
documentation on blazor threads, event loops, and httpclient

### ISSUE THREAD

**Issue by hoksource** [dotnet/AspNetCore.Docs#20772]
[EDIT by guardrex to change the metadata]

Hello, please do document that the blazor wasm and server runs on event loops such that each async await called are similar to promises async await that runs on different iterations of the event loop. But no concurrency happens (each functions are executed before or after another but not at the same time).
@danroth27 
https://github.com/dotnet/AspNetCore.Docs/issues/17371#issuecomment-602683104

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

click events dispatch, keyboard events dispatch, Thread.DelayAsync, HttpClient.PostAsync
are executed in 1 single thread but different event loop iterations.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop

Question 3:
How do i cancel an Http Request by HttpClient while it is running? should i just include a cancellationToken and check if the token is cancelled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hoksource ... 

> each functions are executed before or after another but not at the same time

It's covered in the [*Components* overview topic](https://docs.microsoft.com/aspnet/core/blazor/components/#synchronization-context). The coverage doesn't call out anything for JS event loops specifically, but that's where we cover the subject of sync contexts.

> click events dispatch, keyboard events dispatch, Thread.DelayAsync, HttpClient.PostAsync
are executed in 1 single thread but different event loop iterationsevent loops

It could be stated, but why? What's the context for the remark relevant to **_general_** Blazor development? We focus on covering subjects that apply to general use cases. We have to be careful about loading up the docs with content that wouldn't apply to the vast majority of dev scenarios. cc: @SteveSandersonMS ... if he feels that we need to say anything specific about this aspect and what we would say.

[btw - Anything we cover for this probably would go in the [Call JS from .NET topic](https://docs.microsoft.com/aspnet/core/blazor/call-javascript-from-dotnet).] 

> How do i cancel an Http Request by HttpClient while it is running? should i just include a cancellationToken and check if the token is cancelled?

Yes, that sounds reasonable. I haven't explored that scenario myself, but that's consistent with cancelling long-running tasks guidance.

**Comment by SteveSandersonMS** [comment]
As long as we state somewhere that .NET on WebAssembly runs single-threaded, then I think this is adequately covered.

**Comment by guardrex** [comment]
Thanks @SteveSandersonMS ... that's exactly what we say.

@hoksource ... I'm going to close on that basis. Thanks for writing in. We'll keep an :ear: open for more feedback on this subject.

**Comment by hoksource** [comment]
Thank you @guardrex @SteveSandersonMS ,
I got most of the information i needed. No need to discuss details on

> click events dispatch, keyboard events dispatch, Thread.DelayAsync, HttpClient.PostAsync
