### ISSUE TITLE
Provide authentication documentation for standalone Angular

### ISSUE THREAD

**Issue by virshu** [dotnet/AspNetCore.Docs#20779]
Angular template, even in Visual Studio 16.9 Beta _still_ scaffolds Angular 8. It's a major pain upgrade 8 to current version 11; especially with ng-universal. Moreover, *all* of 15-20 projects that I saw have Angular and .NET running as separate web applications (frequently, Angular even on a different VM or in a different container).

It would be really helpful to document how to implement authentication (especially with new IdentityServer foundation) for Angular project scaffolded with `ng new`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
