### ISSUE TITLE
Typo in the Scaffold the movie model

### ISSUE THREAD

**Issue by sbitaxi** [dotnet/AspNetCore.Docs#20778]
There is a typo in the VSCode commands in the [Scaffold section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code#tabpanel_CeZOj-G++Q-1_visual-studio-code)

`dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries`

Should be the following, without the extra '-' between dotnet and aspnet

`dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries`

It may be the same issue in the macOS and Linux section, but the syntax may be different and I'm not aware.
![image](https://user-images.githubusercontent.com/11016387/100403867-fc54a780-302d-11eb-9b72-72fa99d23465.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
They both work.

**Comment by sbitaxi** [comment]
> They both work.
> 
> ```
> >dotnet-aspnet-codegenerator --help
> Usage: aspnet-codegenerator [arguments] [options]
> 
> Arguments:
>   generator  Name of the generator. Check available generators below.
> 
> Options:
>   -p|--project             Path to .csproj file in the project.
>   -n|--nuget-package-dir
>   -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
>   -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net46)
>   -b|--build-base-path
>   --no-build
> 
> To see more information, enable tracing by setting environment variable 'codegen_trace' = 1.
> RunTime 00:00:00.07
> ```

Thank you, and I have to apologize as it does work fine. The command failed every time I included the hyphen between dotnet and aspnet - copied from the page or typed manually.

It now works, and I don't understand why so I can only assume it was something transient in my system.
