### ISSUE TITLE
Layout for Identity/Account/Manage pages broken after scaffolding full .Net Identity UI source

### ISSUE THREAD

**Issue by br3nt** [dotnet/AspNetCore.Docs#20770]
I'm following along to these to guides:
1. [Scaffold Identity into an MVC project without existing authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization-1)
2. [Create full Identity UI source](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#create-full-identity-ui-source-1)

After following the 1st guide I get what I expect for the Identity/Account/Manage pages:
![FullUI](https://user-images.githubusercontent.com/1089651/100299972-ea9ae200-2fe4-11eb-8266-dbcd11542017.PNG)

However, after following the 2nd guide the layout is broken. The side menu is missing. The app is no longer finding `Areas/Identity/Pages/Account/Manage/_Layout.cshtml`, and I don't understand why.
![defaultUI](https://user-images.githubusercontent.com/1089651/100299984-f1c1f000-2fe4-11eb-8b62-587b76f030d0.PNG)

This is the git diff.
```c#
namespace WebIdentity.Areas.Identity
{
    public class IdentityHostingStartup : IHostingStartup
    {
        public void Configure(IWebHostBuilder builder)
        {
            builder.ConfigureServices((context, services) => {
                services.AddDbContext<IdentityDbContext>(options =>
                    options.UseSqlServer(
                        context.Configuration.GetConnectionString("IdentityDbContextConnection")));
 
-                services.AddDefaultIdentity<User>(options => options.SignIn.RequireConfirmedAccount = true)
-                    .AddEntityFrameworkStores<IdentityDbContext>();
+                services
+                    .AddIdentity<User, IdentityRole>(options => options.SignIn.RequireConfirmedAccount = true)
+                    .AddEntityFrameworkStores<IdentityDbContext>()
+                    .AddDefaultTokenProviders();
+
+                services
+                    .AddMvc()
+                    .AddRazorPagesOptions(options =>
+                    {
+                        options.Conventions.AuthorizeAreaFolder("Identity", "/Account/Manage");
+                        options.Conventions.AuthorizeAreaPage("Identity", "/Account/Logout");
+                    });
+
+                services.ConfigureApplicationCookie(options =>
+                {
+                    options.LoginPath = $"/Identity/Account/Login";
+                    options.LogoutPath = $"/Identity/Account/Logout";
+                    options.AccessDeniedPath = $"/Identity/Account/AccessDenied";
+                });
+
+                services.AddSingleton<IEmailSender, EmailSender>();
             });
         }
     }

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What version of ASP.NET Core?
It might be using the wrong layout.

**Comment by br3nt** [comment]
I'm using Core 5.0.

I didn't change anything in the views, just in `IdentityHostingStartup.cs`.  I merely followed [these steps](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#create-full-identity-ui-source-1) as you can see from the diff in the OP.

I've also committed the changes from each step here: https://github.com/br3nt/WebIdentity

**Comment by Rick-Anderson** [comment]
1. Create MVB project ***WITH*** auth.
2.  TEST
3.[Scaffold Identity into an MVC project ***WITH*** existing authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization-1)

**Comment by br3nt** [comment]
I just realised that I linked to the .net core 2.2 docs in the OP, but in actual fact I was following along to the .Net 5.0 docs.  I have updated the links.

So, I've now followed the same steps from the OP but with a new .Net Core 3.1 MVC app.  I got the same results where `Areas/Identity/Pages/Account/Manage/_Layout.cshtml` was getting skipped.

I also tried by creating an MVB project WITH identity.  Then followed your step 3 (worked as I expected).  Then follow [Create full Identity UI source](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#create-full-identity-ui-source-1) and I got the same results where `Areas/Identity/Pages/Account/Manage/_Layout.cshtml` was getting skipped.

I also tried including `.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)` like the docs say, but it didn't solve the problem.

**Comment by br3nt** [comment]
Adding `AddDefaultUI` seems to make everything work as expected, however, according to [these docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0) `AddDefaultUI` it shouldn't be needed.  

In fact, it says multiple times to remove that line:

> If the Identity scaffolder was used to add Identity files to the project, remove the call to AddDefaultUI

Following [the source code of AddDefaultUI](https://github.com/aspnet/Identity/blob/feedcb5c53444f716ef5121d3add56e11c7b71e5/src/UI/IdentityBuilderUIExtensions.cs#L48), it seems to be doing a lot more than what I would want it to :/.

The code is a little convoluted, so I'm not sure which part specifically is making everything work.

**Comment by Rick-Anderson** [comment]
Looks like this is fixed in .NET 6
