### ISSUE TITLE
Web Debugging Not Working For Me

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#20774]
I am following the steps of Browser Debugging.  Note that I can use VS debugging with no issues. But following all of the steps of Web debugging concludes with this message: Debugging connection was closed.  Reason: WebSocket disconnected.

I have tried:

1. All of the steps multiple times trying with both Edge and Chrome.

2. All of the steps in Trouble Shoot.

Here are repo steps:

1. Create new Blazor WASM app with dotnetcore hosting.

2.F5 to run app.

3. In Browser, `Shilft+Alt+D`, which opens debugger tab.

4. Copy command.

5. Windows + R, run command.

6. Website Opens in Browser.

7. `Shift+Alt+D` which opens new debugger tab.

8. View "Inspectable pages" page:

![image](https://user-images.githubusercontent.com/3810620/100332113-ffed1d80-2f9e-11eb-9dc1-b30d765657f1.png)

9. Click on first page on list.

10. View Message that Websocket disconnected:

![image](https://user-images.githubusercontent.com/3810620/100332258-2b700800-2f9f-11eb-8ddd-1e975f18dbbf.png)

Am I doing something wrong? 

I am using VS 16.9.0 Preview 1.0 which is the latest at present.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-gb/aspnet/core/blazor/debug?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gregoryagu ... Open that for the product unit for investigation, as we only handle docs here. Please add a `cc: @guardrex` to your opening comment. I'll re-open this issue if we need to add or change something in the doc.

https://github.com/dotnet/aspnetcore/issues
