### ISSUE TITLE
Additional requirements for Razor pages to work in host app using RCL

### ISSUE THREAD

**Issue by br3nt** [dotnet/AspNetCore.Docs#20788]
For .Net 5.0 (And probably .Net Core 3.1), the following is needed in `Startup.cs` of the host app:

```c#
        public void ConfigureServices(IServiceCollection services)
        {
            // ...
            services.AddRazorPages();
        }
```

And

```c#
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            // ...
            app.UseEndpoints(endpoints =>
            {
                // ...
                endpoints.MapRazorPages();
            });
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  can you test and verify. I think it's correct. I'll prep the doc for you so you'll only need to add these two items to the .NET 3.1 and higher version.

**Comment by fiyazbinhasan** [comment]
Yes. @br3nt is right. But if we use the new templates i.e 3.1 and 5.0, those lines will be added by default. I think the sample needs an update for 3.1/5.0. @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  should I prep the doc and you could change  the  V6 version. Might as well update it for V6.

```
::: moniker range=">= aspnetcore-6.0"

V6 Version
::: moniker-end
```

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan just update the 5.0 version

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson sure I can do tha :)

**Comment by Rick-Anderson** [comment]
Looks like it's prepared
```
::: moniker-end

::: moniker range=">= aspnetcore-5.0"
<!-- Start update here -->
```
