### ISSUE TITLE
Minor reference error/typo

### ISSUE THREAD

**Issue by mcalexster** [dotnet/AspNetCore.Docs#20789]
In the Add a view - Visual Studio section
in the In the Add New Item - MvcMovie dot point
Sub item 2 'Select Razor V
View' should read 'Select Razor View - Empty'

and the corresponding graphic should be updated (but don't use mine, I changed the project name)

![image](https://user-images.githubusercontent.com/6275182/100492262-76d41300-3165-11eb-9553-840c9e603af0.png)

**Comment by guardrex** [comment]
@mcalexster ... Best to close this and re-open using the **This page** feedback button and form at the bottom of the topic. It will add the topic metadata and ping the author of the topic.
