### ISSUE TITLE
GenericArguments[5], 'SecondHandWeb.Areas.Identity.Data.SecondHandWebUserRole', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9[TUser,TRole,TContext,TKey,TUserClaim,TUserRole,TUserLogin,TUserToken,TRoleClaim]' violates the constraint of type 'TUserRole'.

### ISSUE THREAD

**Issue by Martin-Stein** [dotnet/AspNetCore.Docs#20785]
Hi,
i have followed your instructions to extent the IdenityUserRole class (and some other),
for IdentityUserRole I receive the error below, when 

**services.AddIdentity<SecondHandWebUser, SecondHandWebRole>( )** is called in IdentityHostingStartup

The error message is:
GenericArguments[5], 'SecondHandWeb.Areas.Identity.Data.SecondHandWebUserRole', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9[TUser,TRole,TContext,TKey,TUserClaim,TUserRole,TUserLogin,TUserToken,TRoleClaim]' violates the constraint of type 'TUserRole'.

my extension works for classes IdentityUser and IdentityRole.

here is the declaration of my ConextClass:
 **public class SecondHandWebContext : IdentityDbContext<SecondHandWebUser, IdentityRole<string>, string, IdentityUserClaim<string>, SecondHandWebUserRole, IdentityUserLogin<string>, IdentityRoleClaim<string>, IdentityUserToken<string>>**

here is my IdentityUserRole Classe:
    **public class SecondHandWebUserRole:IdentityUserRole<string>**..

it turn out, thas this error occurs,when the constructor

**public SecondHandWebUserRole(SecondHandWebContext context, UserManager<SecondHandWebUser> userManager)**

is called.

I am using Nuget-Pakage Microsoft.AspNetCore.Identity.EntityFrameworkCore 5.0

what is wrong with my code??

Kind regards,

Martin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by blowdart** [comment]
Without the example code it's hard to say what's going on. If you could upload a small repo that would be great, @ajcvickers can probably figure out the EF error after that.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
