### ISSUE TITLE
Wrong parameter value in "Controller action return types in ASP.NET Core web API"

### ISSUE THREAD

**Issue by edespong** [dotnet/AspNetCore.Docs#20780]
In the example code of the page, there are a number of calls to `CreatedAtAction(nameof(GetById), new { id = product.Id }, product);`

However, the actions calling that method is always `CreateAsync`, so should the first argument not be `nameof(CreateAsync)`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
It's `nameof(GetById)` because the `CreatedAtAction` method is used to generate a URL to the `GetById` action. `CreateAsync` returns a URL that points to the location of the new resource, which is actually served by `GetById`.
