### ISSUE TITLE
How to use IdentityRoleClaim Table (IdentityRoleClaim<TKey> Class) in Identity in ASP.Net Core

### ISSUE THREAD

**Issue by AbrarJahin** [dotnet/AspNetCore.Docs#20786]
[EDIT by guardrex to add the metadata. @AbrarJahin, If you use the **This page** feedback button and form at the bottom of a topic, it adds the metadata automatically and pings the author.]

I am trying to make the best use of [Identity Core][1]. In Identity, I am seeing, there are 7 tables like this-

[![Identity Tables][2]][2]

In there, I am curious about this table-

[![RoleClaim Table][3]][3]

Which can be found in [here][4].

I am trying to use this table for claim based authentication where Super Admin can assign claims onto any role. So that Roles could be dynamic. So, what I am thinking is something like this-

[![ERD][5]][5]

But there is no table exists named **`Claim`** or close to this.

That is why I am thinking I have some gap in my knowledge. But there is no clear documentation known to me on this topic as far as I have found.

Can anyone please let me know,

1. How can I add an entry to the **RoleClaim** table?
2. Why there is no **Claim** table in ***Identity***?
3. Is there any clear documentation regarding this?

I have found one close to my need, but I am not sure. The doc can be found in **[here][6]**.
Thanks in advance for helping.

  [1]: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio
  [2]: https://i.stack.imgur.com/8ZcfN.png
  [3]: https://i.stack.imgur.com/sdIYY.png
  [4]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.entityframeworkcore.identityroleclaim-1?view=aspnetcore-1.1
  [5]: https://i.stack.imgur.com/S23A1.png
  [6]: https://benfoster.io/blog/asp-net-identity-role-claims/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  please review

**Comment by AbrarJahin** [comment]
Hi, I have implemented it with a different approach.

I have made an enum variable which holds all claims. So, all claims are fixed from code. But I am not sure if it is the best way.

Code can be found in [here](https://github.com/AbrarJahin/Asp.NetCore_3.1-PostGRE_Role-Claim_Management).

**Comment by HaoK** [comment]
Right there's no claim table because claims are just strings really, and you can even have duplicate claims, so there's a userclaims and roleclaims table which similarly just allow the same thing, arbitrary name/values for claims.
