### ISSUE TITLE
Getting `Public clients can't send a client secret` error when adding Microsoft auth

### ISSUE THREAD

**Issue by tehtertot** [dotnet/AspNetCore.Docs#20796]
I created a new MVC project with authentication (`dotnet new mvc -o MyApp -au Individual`) and then followed these instructions to add a Microsoft account. When I run it, I get the Microsoft sign-in button and the link initially appears to work, and then I get an error stating `Public clients can't send a client secret`. The stack trace:
```
Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
And some of the exception text from the browser:
```
Exception: OAuth token endpoint failure: Status: BadRequest;Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 9f5635be-1c82-4157-aee7-cf343e003801
x-ms-ests-server: 2.1.11251.20 - WUS2 ProdSlices
Set-Cookie: fpc=[some value]; expires=Tue, 29-Dec-2020 05:15:50 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; samesite=none; httponly, stsservicecookie=ests; path=/; secure; samesite=none; httponly
Date: Sun, 29 Nov 2020 05:15:50 GMT
;Body: {"error":"invalid_request","error_description":"AADSTS90023: Public clients can't send a client secret.\r\nTrace ID: 9f5635be-1c82-4157-aee7-cf343e003801\r\nCorrelation ID: 68499378-9c10-4cec-8efa-15c79776f1c3\r\nTimestamp: 2020-11-29 05:15:50Z","error_codes":[90023],"timestamp":"2020-11-29 05:15:50Z","trace_id":"9f5635be-1c82-4157-aee7-cf343e003801","correlation_id":"68499378-9c10-4cec-8efa-15c79776f1c3"};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tehtertot** [comment]
I walked through the Google authentication steps to make sure the app was working, and that worked great; I registered a new app in Azure, and everything worked fine!

**Comment by Rick-Anderson** [comment]
@tehtertot  thanks for the update.
