### ISSUE TITLE
Offer very detailed examples for library authors

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/AspNetCore.Docs#20799]
I'm having a difficult time piecing together exactly how library authors should be leveraging the options pattern.

Ideally a whole section of examples where the options pattern is configured/leveraged from within `IServiceCollection` extension methods would really be helpful.

It would be nice to see every technique detailed, including individual and combinations of: 

 - How to leverage strongly typed configuration data while registering services
 - How to allow users to provide their own `Action<OptionsType>` on top of configuration obtained from the options pattern
 - How to establish a default `.Configure` for conventions based section binding
 - Any way to work with `IConfiguration` without requiring users to pass it in to extension methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See  https://docs.microsoft.com/en-us/dotnet/core/extensions/options

**Comment by atrauzzi** [comment]
@Rick-Anderson - I can't tell if/how this document can help with the items I listed, is there anything specific you can connect my points to on this page?

I'm looking for a way to leverage strongly typed configuration within extension methods, during the service configuration phase, but outside of a `Startup` class.

**Comment by Rick-Anderson** [comment]
Open an issue at https://docs.microsoft.com/en-us/dotnet/core/extensions/options
that's the primary doc place. This is just for ASP.NET Core specific stuff.

**Comment by atrauzzi** [comment]
Thanks!
