### ISSUE TITLE
Replace NewtonSoftJson reference for Version 3.1 and newer

### ISSUE THREAD

**Issue by the1abel** [dotnet/AspNetCore.Docs#20791]
The following portion of this tutorial page should be updated for .NET Core Versions 3.1 and all newer versions.
In the "Configure JSON serialization options" section (#configure-json-serialization-options), the reference to NewtonSoftJson should be removed.  This change is due to the addition of System.Text.Json in Version 3.1.

The following changes should be made (per https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-core-3-1#customize-individual-property-names):
1. Step #1 should be removed
2. Step #2 should be removed
3. Step #3 should remove `[JsonProperty("Name")]` and instead insert `[JsonPropertyName("Name")]`
4. Step #4 should remove `using Newtonsoft.Json;` and instead insert `using System.Text.Json.Serialization;`
5. Step #5 should remain the same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
MOved to Master list: Create a web API and MongoDB #16196
This doc needs alot of work. WOuld you be able to PR and fix a few bug?

**Comment by the1abel** [comment]
Rick, I'd love to contribute; however I'm unfamiliar with the process.  If you're willing and able to point me to materials to understand the process or brief me, that would be great.

Abel Wenning
c: 714.900.9699
www.LinkedIn.com/in/AbelW<http://www.linkedin.com/in/abelw>

________________________________

**Comment by Rick-Anderson** [comment]
@the1abel  do you need help with GitHub or just the process of updating a doc? I can help with updating the doc.

**Comment by the1abel** [comment]
I've only used GitHub for code, not for tutorial/documentation.  If the tutorial/documentation is just HTML/CSHTML+CSS/Scss, that's easy—I'll just need to understand how you handle the various .NET Core versions of the tutorial (just separate HTML/CSHTML files or a more sophisticated CMS?).
I've not handled Pull Requests on GitHub, but I expect there are tutorials that I can read and test on my own repos to learn the ins and outs of that.  Then, I presume I would need pointers on process/procedures specific to your way of doing things.

Abel Wenning
c: 714.900.9699
www.LinkedIn.com/in/AbelW<http://www.linkedin.com/in/abelw>

________________________________

**Comment by Rick-Anderson** [comment]
It's Markdown ( `.md`) files. Take a look at https://github.com/dotnet/AspNetCore.Docs/blob/master/CONTRIBUTING.md

If you have time, I'll prepare the [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md) by duplicating the content with monikers:

```
::: moniker range=">= aspnetcore-5.0"
// copy of current version
::: moniker-end

::: moniker range="< aspnetcore-5.0"
// current version
::: moniker-end
```

You would  just update the 5.0 version.

**Comment by the1abel** [comment]
Oh, cool.  MD is great.  But, as you mention having time, I realize that I really shouldn't commit to anything additional on my plate right now, as much as I really would love to contribute.
I just started a new job, am still working on my BS in Software Engineering (yes, at age 43; I got a late start), and we just learned my wife is pregnant with our 5th child.
So, I should apologize for taking your time now, and I'll put it on my calendar to circle back with you in about a year.
Thanks for your time, and sorry for stealing some of it fruitlessly.

Abel Wenning
c: 714.900.9699
www.LinkedIn.com/in/AbelW<http://www.linkedin.com/in/abelw>

________________________________
