### ISSUE TITLE
Problems Getting SeedData to work in EF based on following Docs

### ISSUE THREAD

**Issue by pkellner** [dotnet/AspNetCore.Docs#20793]
Struggling for the n+1 time to seed a database with EF. I thought I had hit the gold rush here when the docs showed current with EF Core 5.  I couldn't find a reference to the github repo where the code shown might be so I looked at the repo source and found it in:

Part 5, work with a database in an ASP.NET Core MVC app 

`https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/first-mvc-app/start-mvc/sample/MvcMovie5`

Sadly, that code does not compile with .net core 5.

I managed to get my own source working again, but noticed the example does not have auth in it so am back to struggling with how to create a constructor to the below call instead of null.

I've been off in React and GraphQL land for the last many moons but am back to asp.net core for the moment again.

The experience hasn't been so good getting things to work. :(

```
using (ApplicationDbContext context = new ApplicationDbContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<ApplicationDbContext>>(),null))
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> but noticed the example does not have auth in it so am back to struggling with how to create a constructor to the below call instead of null.

Auth is beyond the scope of this tutorial. I suggest https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data
