### ISSUE TITLE
Lost the "Visual" in Visual Studio

### ISSUE THREAD

**Issue by fudanchu** [dotnet/AspNetCore.Docs#20798]
I'm just curious why the command prompt is used to create folders/projects etc.  Have we regressed into the DOS era?  Can't this be done inside a GUI?  Wouldn't a friendly UX lower the bar for new developers and be considered a universally good thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fudanchu ... You're welcome to use any IDE that you like ... VS, VS4Mac, VSCode, but given that .NET is xplat even beyond what those IDEs support, CLI makes the tutorial the most widely accessible.

WRT "lower the bar" ... VS and other IDEs have a (small) learning curve to get started. For example, there's the install/upgrade steps to contend with. Also, the UIs of these IDEs have a learning curve. The CLI comes in the SDK, so one only needs to get the SDK installed and open a command shell to get started. Management wanted to keep this experience ultra simple.

**Comment by fudanchu** [comment]
Thanks for the explanation!
