### ISSUE TITLE
Small sample code error

### ISSUE THREAD

**Issue by DarkMonkDev** [dotnet/AspNetCore.Docs#20801]
The sample code has using and var in the wrong order-> var using context = new MyContext();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Thanks @DarkMonkDev ... I'll fix that up right now.
