### ISSUE TITLE
compression do not work in my Controller

### ISSUE THREAD

**Issue by ym503908378** [dotnet/AspNetCore.Docs#20800]
i just created a new ..net core 3.1 WebAPI project based by the template and vs2019 , and I added code follow the official example in startup.cs like this
      public void ConfigureServices(IServiceCollection services)
        {
            services.AddResponseCompression();
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseResponseCompression();
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

but the compression middleware do not work 
![image](https://user-images.githubusercontent.com/48427779/100562046-6b175680-32f5-11eb-8999-67d84943c406.png)

**Comment by guardrex** [comment]
For a faster response, close this issue and re-open it using the **This Page** feedback button+form at the bottom of the English topic. It will add metadata to cross-link the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
