### ISSUE TITLE
Use Managed identities for Azure resources example error

### ISSUE THREAD

**Issue by BenyErnest** [dotnet/AspNetCore.Docs#20807]
Hi there,
I think there is an error in the variable in the Use Managed identities for Azure resources section example:

```
    var secretClient = new SecretClient(new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
                                                         new DefaultAzureCredential());
    config.AddAzureKeyVault(SecretClient, new KeyVaultSecretManager());
```
The variable secretClient should be passed to `config.AddAzureKeyVault(SecretClient, new KeyVaultSecretManager());` instead of the object type.
 Greets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@BenyErnest ... I think it was just fixed on https://github.com/dotnet/AspNetCore.Docs/pull/20771. We probably haven't merged to live yet to make it visible in the topic. That will happen soon (if the topic is using the sample app code for that bit of text coverage).

**Comment by BenyErnest** [comment]
Thanks!
