### ISSUE TITLE
I am using VS2019 16.8.2 and ASP.Net 5.0 and tried to create a new app following the instructions.

### ISSUE THREAD

**Issue by BobLangdown** [dotnet/AspNetCore.Docs#20802]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BobLangdown** [comment]
What I get does not look anything like the tutorial. I get something called Swagger that does not look like a web page.

**Comment by Rick-Anderson** [comment]
You selected the wrong template.
