### ISSUE TITLE
"Create" is blocked from localization

### ISSUE THREAD

**Issue by JasonCard** [dotnet/AspNetCore.Docs#20813]
The term "Create" is blocked from localization with the no-loc metadata, but it may need to be localized in some cases such as "Create New" link, "Create" page/UI. If those UI terms should be left in English, then other UI such as "Save" and "Edit" may also need to be blocked from localization. Please help to check and update.

Similar issue/question with the term "Delete" in following article:
[https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Part 8, add validation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Unfortunately, the VS UI seems somewhat variable on translations. Sometimes UI entries were translated, sometimes not. Sometimes, translations were in VS or VS4Mac, but not both. The only way I could proceed would be to check each IDE UI entry on all three IDEs across platforms. It was intractable at the time given time constraints.
