### ISSUE TITLE
HTTP.sys options section is out of sync with HttpSysOptions 

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#20827]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysoptions?view=aspnetcore-5.0

Duplicating the docs for these options isn't ideal, they get out of sync. It might be better to improve the API docs and direct people to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-the-aspnet-core-app-to-use-httpsys)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  I could put common options in an include file they can all share.

I'll drop two out of support versions:
`::: moniker range="= aspnetcore-2.2"`
`::: moniker range="= aspnetcore-3.0"`

2.1 will be out of support soon which leaves only one version. Has there been any changes for 5.x?

**Comment by Tratcher** [comment]
There are a few APIs not covered by the concept docs list like Http503Verbosity which has been around since 2.1. Do we even need this list in the concept docs if it's supposed to match 1:1 with the API docs?

**Comment by Tratcher** [comment]
Other APIs not covered in the concept docs:
Authentication.AutomaticAuthentication
Authentication.AuthenticationDisplayName
ClientCertificateMethod

**Comment by Rick-Anderson** [comment]
It's much better to have the information in the API docs. I'm fine with removing them from this doc. 
The descriptions here are sometimes much better, for example, https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.authenticationmanager.schemes 
Many of the types have defaults which don't seem to be in the API docs.

**Comment by Tratcher** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/28297 for improving the API docs.

**Comment by smflorentino** [comment]
I just fixed a few missing entries. It's really helpful to have these on the main HttpSys page. If we do remove them, we should make sure the links to the API docs are prominent and clear. Even then I'm not sure browsing API types is the best way to learn how to configure HttpSys (or Kestrel, or anything, for that matter).

**Comment by guardrex** [comment]
From @Tratcher ...

> FYI I'd filed #20827 when this first came up. Long term we'd like to avoid maintaining multiple lists.

Sorry ... this issue wasn't cross-linked. @smflorentino, please make sure that you at least place an `Addresses #{ISSUE NUMBER}` if not a `Fixes #{ISSUE NUMBER}` on PRs that you open so that we can have them cross-linked.

Anyway ... no worries. There's no harm with that PR.

🤔 The defaults ... I didn't think that they were in the API docs. Idk if scrapping the table would result in a poor UE for devs without them, but I'd be concerned about it.

**Comment by Tratcher** [comment]
@smflorentino didn't know about this issue either.

> 🤔 The defaults ... I didn't think that they were in the API docs. Idk if scrapping the table would result in a poor UE for devs without them, but I'd be concerned about it.

Right, I filed https://github.com/dotnet/AspNetCore.Docs/pull/20893 to improve the API docs. Once those are good enough then we can remove the duplicate table from the concept docs.

**Comment by smflorentino** [comment]
>Right, I filed #20893 to improve the API docs. Once those are good enough then we can remove the duplicate table from the concept docs.
Is this the right issue number?

**Comment by Tratcher** [comment]
No 😁, it's https://github.com/dotnet/aspnetcore/issues/28297.

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/issues/28297 has been fixed for .NET 8, we should see about removing the duplicate table from the concept docs for 8 as well.

**Comment by tdykstra** [comment]
Fixed by #28166
