### ISSUE TITLE
Add link to relevant types

### ISSUE THREAD

**Issue by maloo** [dotnet/AspNetCore.Docs#20823]
Please add a link to relevant types, like Virtualize component documentation page.

Also add information about how to control the height of the component (to get the scrollbar instead of a long list of items as default).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor component virtualization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @maloo for the feedback. I'm buried in work ⛏️⛰️ for the next couple of weeks then out for an extended ⛄ *holiday vacation* 🎁, but I've added this to my **Post-holiday Triage** issue list and will take a look when I return. Sorry for the delay, but I must get some long-standing priorities resolved before leaving, so only serious bug fixes will be addressed before I get some (*much needed* 😅) rest. I assure you that this won't get lost.

**Comment by maloo** [comment]
No hurry, I solved my issue. But in general the type docs are in really bad shape. But there are lots of really good articles and examples on most types hidden in the docs. I think all of docs would benefit from an auto generated cross reference between these type doc pages and the articles/examples.

**Comment by guardrex** [comment]
We don't have a facility such as that. We have to manually create cross-links to the API docs. Also note that such links can't be created until **_AFTER_** GA (5.0 just released a couple of weeks ago) because they don't activate **_preview_** API docs for us to link. The framework is in churn before GA as they work on it, so API docs only get the final, approved, released API coverage when the framework reaches GA. I tend to return to docs after GA and get the types cross-linked in the weeks and months following release.

**Comment by maloo** [comment]
I understand, but as a user that sounds like a technical issue (that can/should be resolved). As a user you just want the cross ref, doesn't matter how docs are generated ;)

**Comment by guardrex** [comment]
> you just want the cross ref

That's the crux of it tho ..... **_there is nothing to cross ref_** ... nothing that we can link to. When the framework is in preview, the best one can do is go into the framework source code, issues, and PRs themselves on the product unit repo at ...

https://github.com/dotnet/aspnetcore/

They can't make API docs out of something that's under active development by the product unit engineers. It changes constantly. Our docs flow downstream from that point. **_After_** they've settled on everything and worked out the final bugs and bits, then the API docs go live (at GA) **_and then_** we can cross-link the API. Until that point tho, there's nothing to cross-link.

What is a bit troubling is that we have no way to set up a **_pre-API doc cross-link_** when writing **_preview docs_**. If we make API doc links today during preview, they create **_broken links_** that we don't want to trouble readers (or ourselves) with. They'll click ... the link will break (404) ... we'll get issues opened every hour of every day during preview if we do that. *We'll be flooded with issues!* 😨

If you want to provide feedback about that aspect ... an XREF API doc link that doesn't break during preview ... you can provide that feedback, but that's not something we take care of here. We just work on ASP.NET Core doc content here. Provide the feedback at ...

https://github.com/MicrosoftDocs/feedback/issues

**Comment by guardrex** [comment]
btw ... are you aware of the API Browser? ....

https://docs.microsoft.com/en-us/dotnet/api/

At least with that, you can get the API during the period while we're updating docs post GA.

**Comment by guardrex** [comment]
@maloo ... I'm back from vacation now.

* On the API docs cross-links. I'll see if I can address that right now to close this out. This issue will close automatically when the PR goes in.
* On "control the height of the component," I've marked that on the [UE tracking issue for this topic](https://github.com/dotnet/AspNetCore.Docs/issues/19286), and I'll address that with all of the updates to this topic that I make at that time.
