### ISSUE TITLE
Tag Helpers are not setting tags to bold

### ISSUE THREAD

**Issue by the-wazz** [dotnet/AspNetCore.Docs#20832]
Re: section starting with: [The Create Razor Page](https://docs.microsoft.com/en-ca/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio#the-create-razor-page)

Quote: "Visual Studio displays the following tags in a distinctive bold font used for Tag Helpers:...".
An image follows to show the bolded tags.

Issue: No tags are in bold for me. The *only* things in bold are attributes that start with **asp-**.

I'm just starting out with Razor Pages. I updated my VS 2019 today to: 
Microsoft Visual Studio Community 2019
Version 16.8.2

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-ca/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's what makes them tag helpers. HTML is not bolded.

**Comment by the-wazz** [comment]
The HTML in the image provided in the article IS bolded, that's my point. So I assumed mine should be too.
