### ISSUE TITLE
Why handlers that use Entity Framework shouldn't be registered as singletons.

### ISSUE THREAD

**Issue by bgbrooks2017** [dotnet/AspNetCore.Docs#20842]
There is a note that mentions "Handlers that use Entity Framework shouldn't be registered as singletons". 

Any explanation as to why singletons cause a problem with Entity Framework?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcab4fd-00de-6e6f-0552-30c07ffc4086
* Version Independent ID: 5c2b0d48-ef1a-5875-35d1-865cb022fa71
* Content: [Dependency injection in requirement handlers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/dependencyinjection?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/dependencyinjection.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/dependencyinjection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Check the EF site.
