### ISSUE TITLE
Middleware Testing Guide is not detailed enough

### ISSUE THREAD

**Issue by js8080** [dotnet/AspNetCore.Docs#20853]
Although I appreciate this guide being available at all, it does not provide enough details as it should. For example, the example code given refers `services.AddMyServices()` but then fails to explain that is not real code and you need to insert your own there.

```C#
                .ConfigureServices(services =>
                {
                    services.AddMyServices();
                })
```

Adding some real example dependencies to inject would be helpful. In fact, having a complete code example available on github or on the page itself would be even more useful.

There is also no discussion of how you can get the TestServer to return different responses. Maybe I can use the HttpContext approach for this... maybe not? I have no idea as the guide doesn't actually specify this so I have to trial and error to figure it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9421feee-5207-e379-00fb-847cc880014c
* Version Independent ID: 8415adee-793e-2ba7-b97b-672b493ba42b
* Content: [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Tratcher
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT please set priority on this. If @javiercn  can provide a sample I'll get it documented ASAP.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
