### ISSUE TITLE
Should mention Blazor component parameters are optional and can have a default value?

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#20855]
I was reading this completed ticket (https://github.com/dotnet/aspnetcore/issues/6864) and realized component parameter default values were not something I've been using and not something I recall seeing in the docs. It may also be worth mentioning that component parameters are optional.

I'm happy to create a small PR if it would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mrlife ... That's fine if you want to submit a PR. Otherwise, let's wait until after the holidays ⛄🎁 ... I'm buried in work right now and will be out for an extended vacation. 😅
