### ISSUE TITLE
EF dependencies

### ISSUE THREAD

**Issue by DickBaker** [dotnet/AspNetCore.Docs#20857]
[Enter feedback here]
docs say "The EF SQL Server package and its dependencies, Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Relational, provide runtime support for EF" which is technically true but misleading, and would read better as "The EF SQL Server package and its dependencies, Microsoft.EntityFrameworkCore.Relational and thence Microsoft.EntityFrameworkCore provide runtime support for EF". Thus it is only necessary for devs to enter the top-level package (then child dependencies will be pulled in automatically. i.e. you ONLY need the PS/PMC command
Install-Package Microsoft.EntityFrameworkCore.SqlServer

BTW congrats on all the effort on the docs which is definitely improving apace!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment. The EF team is reviewing the series and I'll have them review this suggestion.
