### ISSUE TITLE
blazor debug VsRegEdit command parameter confusion..

### ISSUE THREAD

**Issue by tony-asu** [dotnet/AspNetCore.Docs#20851]
The documentation makes reference to "TIMEOUT" being a variable to replace, but..  There's a second parameter (VSInstallFolder ) that isn't mentioned and it's formatted differently.  

VsRegEdit.exe set "<VSInstallFolder>" HKCU JSDebugger\Options\Debugging "BlazorTimeoutInMilliseconds" dword {TIMEOUT}

<VSInstallFolder> should be replaced with the visual studio directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tony-asu ... Could you re-open this over for the product unit. Please add a `cc: @guardrex` to your opening comment so that I can follow the discussion ...

https://github.com/dotnet/aspnetcore/issues
