### ISSUE TITLE
More documentation about the actual OpenAPI client usage required.

### ISSUE THREAD

**Issue by cjb110** [dotnet/AspNetCore.Docs#20866]
The documentation covers a reasonable amount about the OpenAPI document generation (though notably security is missing).
But there's hardly anything on the client generated, like how to expand it (e.g. I'm trying to get logging, and JWT bearer working) etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Master issue for NSwag #16879
