### ISSUE TITLE
Very small difference between doc and template

### ISSUE THREAD

**Issue by the-wazz** [dotnet/AspNetCore.Docs#20865]
Found a small difference between the VS template and the code in the docs.

In the section [Set up the site style](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#set-up-the-site-style), in the docs, right below the toggle button is

    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

but in the VS template (created today, 2020-12-04) is

    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll take a look at this in the next update.

**Comment by the-wazz** [comment]
P.S. _Does not affect the tutorial_. I'm not completely up on Bootstrap 4 yet, so not sure if there's an effect on the layout; I haven't noticed one yet.
