### ISSUE TITLE
Image does not exactly match instructions

### ISSUE THREAD

**Issue by the-wazz** [dotnet/AspNetCore.Docs#20864]
In the section, "Create the web app project," [the image](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#create-the-web-app-project) does not match instruction #5b: 

5. In the Create a new ASP.NET Core web application dialog, select:
    a. .NET Core and ASP.NET Core 5.0 in the dropdowns.
    b. ASP.NET Core Web App.
    c. Create

'ASP.NET Core Web App (Model-View-Controller)' is selected. Assuming the error is the image because it's a Razor Pages tutorial.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of  #20792
