### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by the-wazz** [dotnet/AspNetCore.Docs#20872]
In [this section](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#scaffold-student-pages), there's one 'Add' step missing

- In the Add Razor Pages using Entity Framework (CRUD) dialog: 
  - In the Model class drop-down, select Student (ContosoUniversity.Models).
  - In the Data context class row, select the + (plus) sign.
    - Change the data context name to end in SchoolContext rather than ContosoUniversityContext. The updated context name: ContosoUniversity.Data.SchoolContext
    - **[missing:]** Select **Add** [to finish adding the Data context class].
  - Select Add [to finish the dialog/adding the pages].

Also, another reference is added: Microsoft.EntityFrameworkCore.Sqlite

Microsoft Visual Studio Community 2019
Version 16.8.2

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll look at this on the next update. It's an advanced tutorial, I don't think this will stop anyone.

**Comment by Rick-Anderson** [comment]
@the-wazz  why don't you fix this. I can help if needed.
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by the-wazz** [comment]
Sure. I switched from editing to opening issues but I can do that.
