### ISSUE TITLE
Error in description

### ISSUE THREAD

**Issue by the-wazz** [dotnet/AspNetCore.Docs#20875]
In the section [here](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#asynchronous-code), the text says `Task<T>`

    In the following code, the async keyword, Task<T> return value, ...

but the code says just `Task`

    public async Task OnGetAsync()

`Task<T>` is also mentioned in the 2nd bullet-point below the code.

I know this is nitpicky stuff but it's better when everything matches. No time and brainwaves lost wondering 'am I missing something?'. Tnx.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-ca/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, that needs to be fixed.
