### ISSUE TITLE
Possibly incorrect statements regarding calling hub methods

### ISSUE THREAD

**Issue by matthewkrieger** [dotnet/AspNetCore.Docs#20871]
[Enter feedback here]

Should "Now, with access to an instance of `IHubContext`, you can call hub methods as if you were in the hub itself."

be changed to

"Now, with access to an instance of `IHubContext`, you can call _client_ methods as if you were in the hub itself."?

and should "When hub methods are called from outside of the `Hub` class..."

be changed to

"When _client_ methods are called from outside of the `Hub` class"?

My understanding is that the `HubContext` does not give access to methods in the hub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Good catch, this wording should definitely be fixed.

**Comment by matthewkrieger** [comment]
Thanks Brennan.  Anything I need to do?

**Comment by BrennanConroy** [comment]
You're welcome to make a PR to fix it if you're interested!

**Comment by matthewkrieger** [comment]
Good point, LOL! why didn't I think of that. Will do.
