### ISSUE TITLE
The definition for AddDatabaseDeveloperPageExceptionFilter does not exist in the IServiceCollection.

### ISSUE THREAD

**Issue by kieseld** [dotnet/AspNetCore.Docs#20870]
The section regarding adding this code needs more instructions.

`services.AddDatabaseDeveloperPageExceptionFilter();`

The definition for AddDatabaseDeveloperPageExceptionFilter does not exist in the IServiceCollection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#add-the-database-exception-filter

**Comment by Concresent** [comment]
Hi I'm doing the tutor and getting the error in Program.cs
The definition for AddDatabaseDeveloperPageExceptionFilter does not exist in the IServiceCollection.  5/10/2022, so its not fixed.

**Comment by Concresent** [comment]
Hi an update.
The error appears before the step Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore which makes it disappear but the document text doesn't mention the error directly or that it will be resolved with the above step. Thanks!
