### ISSUE TITLE
Guidance for adding ILogger that depends on HttpClient

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/AspNetCore.Docs#20881]
I think it's not uncommon for the `ILogger` to log to a server. It would be nice to provide some guidance on how to add an `ILogger` that depends on an `HttpClient` especially that loggers are usually singleton while the `HttpClient` is scoped in blazor wasm. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8795bcc-45ef-7edc-4657-fca867c8ff81
* Version Independent ID: d0b1a040-5dae-8233-dbee-c5837a0c231d
* Content: [ASP.NET Core Blazor logging](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-5.0&source=docs)
* Content Source: [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/logging.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gojanpaolo ... That's a custom scenario that you would [need to develop on your own](https://docs.microsoft.com/dotnet/core/extensions/custom-logging-provider) or [use a 3rd party provider](https://docs.microsoft.com/aspnet/core/fundamentals/logging/#third-party-logging-providers) to accomplish.

> HttpClient is scoped in blazor wasm

Scoped in WASM behaves like Singleton. See :point_right: https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection#service-lifetime
