### ISSUE TITLE
HOW DO I CREATE A CUSTOM CALLPROCESSOR

### ISSUE THREAD

**Issue by petersgiles** [dotnet/AspNetCore.Docs#20883]
What does it do? Why did you leave its implementation out?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @petersgiles ... We only work on documentation on this repo. If you have a product feature request for Blazor, open it on the product unit's repo ...

**Comment by petersgiles** [comment]
yep, so the reason I raised the issue it that your documentation declares a thing called a callprocessor with no implementation or even a description of what it should do.

It should be better documented.

**Comment by guardrex** [comment]
I see ... yes, I didn't pick up on what you were referring to. The whole point of this topic is to cover **_Graph API_**, not all of the things that one could do with data returned via Graph API. That "call processor" mention is merely an example of what one could do with a phone number obtained for a user.

**Comment by guardrex** [comment]
Let's just remove it. I agree that having it without an implementation isn't so great.

**Comment by petersgiles** [comment]
> ... but that was there. It was in the NOTE under the example, where it said ...
> 
> In the preceding example, the developer implements the custom ICallProcessor (CallProcessor) to queue and then place automated calls.
> 
> Anyway ... no worries. I removed that bit of the example

You know, when I read it originally I read CallProcessor as putting the value on a queue to make a `Call` i.e. some kind of fetch or other request to an API related to MSGraph. Now I see that the intent was to process the returned phone number in some business-related way.

I guess `Call` is a loaded term, thanks for making the article clearer by removing it.
