### ISSUE TITLE
Integration Testing an Application with Authentication

### ISSUE THREAD

**Issue by logandrews** [dotnet/AspNetCore.Docs#20887]
While going through this documentation, I have found some issues/gaps with it for an application that has authentication in it.

I started with a project that didn't have authentication and had a basic test getting a page on the site and validating success. I then added WSFederation authentication to the project. At this point, I got an exception `System.Net.CookieException: An error occurred when parsing the Cookie header for Uri 'http://localhost/manage'. ---> System.Net.CookieException: The 'Path'='/signin-wsfed' part of the cookie is invalid.`. This appears to be an issue with the cookie parsing being strict for paths per RFC 2109. It appears that RFC 6265 should resolve the issue and made it into .NET 5, but I haven't tested it: https://github.com/dotnet/runtime/issues/26141

Ignoring that, I attempted to setup the mock authentication in the article and avoid the cookie and redirect. I use the default WsFederation scheme, so I replaced the `"Test"` string with `WsFederationDefaults.AuthenticationScheme`. This gave the error `System.InvalidOperationException: Scheme already exists: WsFederation`. I followed the instructions in the documentation and made sure that the scheme name matched what my application expected, so I expected this to work. I wondered how the sample application dealt with this and jumped into the code, only to find that [the actual application](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/src/RazorPagesProject/Startup.cs) doesn't appear to setup any authentication providers with the name "Test". The call to `AddDefaultIdentity` adds a scheme with a different name. In my case, I use the authentication scheme as part of a security policy, so this is important for my use case. I haven't worked around this one yet, but I imagine it will involve removing the existing scheme and adding in the mock scheme instead.

A few thoughts on improvements to this documentation:
1) Provide additional guidance on dealing with mock authentication with additional scheme.
2) Provide additional guidance on dealing with dealing with the cookie path error for some authentication providers.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
