### ISSUE TITLE
Should mention that parameter name in controllers action and Map Route is case insensitive

### ISSUE THREAD

**Issue by thisisjaymehta** [dotnet/AspNetCore.Docs#20898]
Should mention that parameter name in controllers action and Map Route is case insensitive.

![image](https://user-images.githubusercontent.com/31812582/101488979-4ae73780-3986-11eb-8217-6a96519d493f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-in/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's mentioned in the routing doc and I think someplace in this doc.
