### ISSUE TITLE
Remove SendGrid as a Recommended Email Provider 

### ISSUE THREAD

**Issue by WilldotNET** [dotnet/AspNetCore.Docs#20906]
Hi,

Great article, but I am stuck at registering with an email sender.

Send grid have reviewed my application for a free account and decided "I am not a suitable fit" :

I've got no reason to be denied an account as far as I know and suspect the lack of evidence that I'm going to spend money with them in the future was the sticking point - as it will be for most devs spinning up practice apps.

Email response to my application:

"Hello,

Thanks for reaching out. Twilio SendGrid leverages many different vetting techniques and as such we've determined that you're not a good fit for our platform. Because of this, we will not be able to activate your account. Our system does not provide myself or other members of Support with details regarding decisions made in the sign-up process. As such we are not able to provide any more information to you.

I apologize for this inconvenience."

I'm going to have a look for a couple of alternatives - just thought I'd let you guys know. It appears they've retreated entirely from supporting azure/dot net devs - 

Just letting you guys know, I'll send more feedback when I find alternatives - or maybe you have another partner to recommend? It MAY just be that they don't like me :) but I've got no history of email abuse e.g. spam or phishing so can only conclude they don't want to waste time with devs who might not pay them lots of money in the future.

Cheers,

Will

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the heads up.

**Comment by Rick-Anderson** [comment]
@WilldotNET  I opened another ticket. Unfortunately you need an account to access it.

**Comment by Rick-Anderson** [comment]
@WilldotNET  SendGrid doesn't seem to understand your complaint. It's pretty clear to me. If you have a SendGrid account, you can probably review the ticket.

**Comment by WilldotNET** [comment]
Thanks @Rick-Anderson  - I'll check it out - sorry just seeing this now..

**Comment by WilldotNET** [comment]
Hi @Rick-Anderson  I have created a Twilio account to get to that ticket - but it says I am unauthorised, it does however seem to let me have a dev account for sending texts. Sendgrid on the other hand wont even let me log in, I'm probably going to have to give up on email confirmation - is there a way of using outlook or gmail to send mail programatically? I realise I could search for info on that but was wondering if it was recommended or prone to getting shut down ..

**Comment by Rick-Anderson** [comment]
You need an email provider, it doesn't need to be SendGrid.

> it does however seem to let me have a dev account for sending texts. 

SendGrid is part of Twilio. If you can send texts with a dev account, you're good.
