### ISSUE TITLE
incorrect path in example code

### ISSUE THREAD

**Issue by nzstevem** [dotnet/AspNetCore.Docs#20904]
Hi, when I ran through this example I found a path error.
 
This browser code: 

<script src="~/lib/signalr/dist/browser/signalr.js"></script>

Should be :

<script src="~/lib/aspnet/signalr/dist/browser/signalr.js"></script>

Regards
Steve 9 Dec 2020
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
You missed a step
>Set Target Location to wwwroot/lib/signalr/, and select Install.

There is also a picture with the Target Location highlighted showing the modified value.

**Comment by nzstevem** [comment]
Fair enough… 😊
