### ISSUE TITLE
Incorrect default stated.

### ISSUE THREAD

**Issue by JohnCOsborne** [dotnet/AspNetCore.Docs#20910]
It states [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1) that Kestrel is used as the default. 

> ASP.NET Core project templates use Kestrel by default. In Program.cs, the ConfigureWebHostDefaults method calls UseKestrel:

On [other docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1
), also for 3.1, it states that In-process is the default and that uses IISHttpServer

> Since ASP.NET Core 3.0, in-process hosting has been enabled by default for all app deployed to IIS.

> CreateDefaultBuilder adds an IServer instance by calling the UseIIS method to boot the CoreCLR and host the app inside of the IIS worker process (w3wp.exe or iisexpress.exe).

> IIS HTTP Server (IISHttpServer) is used instead of Kestrel server. For in-process, CreateDefaultBuilder calls UseIIS to:

I may be mixed up but these seem like a direct conflict.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JohnCOsborne** [comment]
[Rick Strahl's blog ](https://weblog.west-wind.com/posts/2019/Mar/16/ASPNET-Core-Hosting-on-IIS-with-ASPNET-Core-22)states that Kestrel is not the default web server when using In-process hosting. So if Strahl is correct then the [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#kestrel-in-aspnet-core-apps) stating that Kestrel is the default for 3.1 is incorrect, IF in-process is the default hosting method for a 3.1 app.

**Comment by Rick-Anderson** [comment]
@jkotalik please review

**Comment by jkotalik** [comment]
I think the first doc comment can mention `ASP.NET Core project templates use Kestrel by default when not hosted with IIS.`

**Comment by JohnCOsborne** [comment]
Yeah, that threw me off. Makes sense now that I understand ASP.NET Core projects use kestrel when run outside of IIS
