### ISSUE TITLE
Missing code sample for ShortCircuitingResourceFilter 

### ISSUE THREAD

**Issue by yanxiaodi** [dotnet/AspNetCore.Docs#20925]
I'm reading the document of the Filter in ASP.NET Core and found that there is a piece of code sample missing.

In the `Cancellation and short-circuiting` section, it mentioned 
> In the following code, both the ShortCircuitingResourceFilter and the AddHeader filter target the SomeResource action method. 

But in the code sample, there is no Action that applies the `ShortCircuitingResourceFilter`.

I can make a PR to fix this. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, a PR would be great!

**Comment by yanxiaodi** [comment]
Hi @Rick-Anderson  I just checked the source code of the docs and it seems not as easy as I thought. It references the code in the sample project by the region name. Based on my investigation, the issue is on line 276:
```
[!code-csharp[](./filters/3.1sample/FiltersSample/Controllers/SampleController.cs?name=snippet_AddHeader&highlight=1)]
```
The `snippet_AddHeader` region does not contain the `ShortCircuitingResourceFilter` part. I see there is a `snippet3` region but it contains another piece of code that is unnecessary for this scenario. So what do we do for this case? Can I replace the current region name by `snippet3`? Thanks.

**Comment by Rick-Anderson** [comment]
Can't you create another method with the code you need? Surround it by `#region snippet-name` and reference it.

**Comment by yanxiaodi** [comment]
PR raised on #20927
