### ISSUE TITLE
Wrong .conf sample

### ISSUE THREAD

**Issue by glestwid** [dotnet/AspNetCore.Docs#20926]
[EDIT by guardrex to add the code block]

This section 

```
<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>
```

leads to "Unrecognized header format %" upon "sudo service httpd configtest"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by guardrex** [comment]
cc: @spboyer

**Comment by tedclarke3** [comment]
I am getting the same error when using the apache conf example helloapp.conf

When I run the command "sudo service httpd configtest" I get the error shown below in the second line.

Jan 22 16:30:49 edgolxtcv03 httpd[23838]: AH00526: Syntax error on line 2 of /etc/httpd/conf.d/helloapp.conf:
Jan 22 16:30:49 edgolxtcv03 httpd[23838]: Unrecognized header format %
Jan 22 16:30:49 edgolxtcv03 systemd[1]: httpd.service: main process exited, code=exited, status=1/FAILURE
Jan 22 16:30:49 edgolxtcv03 systemd[1]: Failed to start The Apache HTTP Server.
Jan 22 16:30:49 edgolxtcv03 systemd[1]: Unit httpd.service entered failed state.
Jan 22 16:30:49 edgolxtcv03 systemd[1]: httpd.service failed.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
