### ISSUE TITLE
BlazorSignalRApp won't start from VSCode

### ISSUE THREAD

**Issue by plhosk** [dotnet/AspNetCore.Docs#20938]
Launch.json looks like this after allowing the c# plugin to create it:
```
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}/Server"
        }
```

When I press F5 it opens Chrome (not my default browser Edge for some reason) and just hangs for around 15 secs before a VSCode debug error dialog opens with "Unable to launch browser: "Could not open ...:5001/_framework/debug/ws-proxy?browser=ws.%3A%2F127.0.0.1%3A63392%2Fdevto..."

One thing that sticks out is the port 5001, but this project is not configured to be served on that port, rather it should be port 5000. There's no instance of the string 5001 anywhwere in the project.

This is what appears in the VSCode terminal:
```
Building...
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\BlazorSignalRApp\Server
```

Also this notification appears in VSCode:

```
The terminal process "cmd.exe '/c', 'chcp 65001 >NUL & dotnet run'" terminated with exit code: 3762504530.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @plhosk ... Open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
