### ISSUE TITLE
Not seeing bundling happening from Razor Class Library consumption?

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#20931]
> If other projects are utilized, such as NuGet packages or Razor class libraries, the bundled file:
>
> References the styles using CSS imports.
> Isn't published as a static web asset of the app that consumes the styles.

I'm not able to get this to work, but maybe I'm doing something wrong or not interpreting these comments correctly.

From my understanding, I have a Razor Class Library/NuGet Package, [BlazingApple.Survey](https://github.com/BlazingApple/Survey), and I want to add CSS isolation to one of the components. 
Instructions are as follows for the developer of the NuGet package or class library:

1. Create the CSS isolation file (same name, `ComponentName.razor.css`).
2. Build Razor Class Library solution, which are referenced by a consuming client project, where this will automatically be picked up.

Instructions for the consuming project to pickup the CSS isolation associated with an RCL component:

1. In the consuming project, `BlazorConsumer2.Client` we reference a stylesheet `BlazorConsumer2.Client.styles.css`, which should have the sum total of all of the CSS from our referenced NuGet packages/RCLs, right?

I don't see that happening. Is there something that the NuGet package/RCL needs to do in order to have _it's_ CSS consumed in the project using it? When I look at the bundled CSS file in the consuming project, none of the styles have been added to that stylesheet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@taylorchasewhite ... What you just said doesn't match the guidance at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#razor-class-library-rcl-support. Are you looking at/attempting to follow that section?

**Comment by guardrex** [comment]
See if they're available from ...

```
https://localhost:5001/_content/BlazingApple.Survey/BlazingApple.Survey.bundle.scp.css
```

Note that I don't see any isolated CSS in your lib btw. They should be named there for their components (e.g., `DisplaySurvey.razor.css` SxS with `DisplaySurvey.razor`) AFAIK.

I admit to not having time yet to play with these bits. I'm largely going off of what the product unit has told me. I've been 🏃😅 on high priority work ever since 5.0 released. I **_WILL_** have time to really get into the scenarios and topic updates when I reach this issue on my [UE pass tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286), but I won't reach this topic until Q1 2021.

**Comment by daveabrock** [comment]
Hey @taylorchasewhite, I'd also echo what @guardrex is saying. After adding `razor.css` files, let us know how it goes.

**Comment by guardrex** [comment]
@taylorchasewhite ... I'm about to leave for an extended ⛄ *holiday vacation* 🎁 ... a much needed vacation 😅 ... and back in 2021. I'm closing out unactionable issues before I take off. AFAIK, the scenario works as described. I'll have more time to play with the bits in 2021 as I run through all of the topics making minor updates, so there might be some touch-ups later. However, we can re-open this if you come up with something concrete that we need to address. @daveabrock and I will be :ear: here.
