### ISSUE TITLE
Expand on Request/response features

### ISSUE THREAD

**Issue by brgrz** [dotnet/AspNetCore.Docs#20936]
I posted previously about the lack of detailed docs with some of more advanced ASP.NET Core features and the list just goes on and on.

On the page referenced below, we have a list of request/response feature interface which supposedly we could use to manipulate (as it seems) all sorts of stuff in our ASP.NET Core apps.

Sadly, the article starts with three paragraphs of a talk that delivers very little value and is written in a very hard to understand way.

**The article should start with the problem. What the issue is and how the features/tech outlined below solves it. Most of these pages fail at that premise.**

Next, given the talk is about a more advanced topic, at least one of these feature interfaces should've been explained in detail, providing code how to use/manipulate it. Not a single of these interfaces has been provided with that. The links which the interface names link to go to API docs and there's the most minimal description of an API possible.

for example 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttpresetfeature?view=aspnetcore-3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d7ad78-542f-236c-f5b4-0273558674b9
* Version Independent ID: f64165fc-ccf3-62cd-9ae4-313dfe7d1911
* Content: [Request Features in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/request-features.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/request-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by brgrz** [comment]
If I break it down, for example

> The Features property of HttpContext provides access to the collection of feature interfaces for the current request. Since the feature collection is mutable even within the context of a request, middleware can be used to modify the collection and add support for additional features. 

Great, now how do we do that?

> Some advanced features are only available by accessing the associated interface through the feature collection.

What does that even mean? An example of code would be nice.

> Most feature interfaces provide optional, light-up functionality, and their associated HttpContext APIs provide defaults if the feature isn't present. 

Again, an example would be nice. How does that optionality look like? What is a light-up functionality, an example maybe?

In general, what I'm saying is: all this seems nice and _kinda_ looks like we could do a lot with **but** is lacking on documentation and code samples.

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. This is an advanced feature not needed by most apps. 

We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.

**Comment by brgrz** [comment]
Providing docs/sample on one or two of the features to showcase proper use is too much work? That's a bummer.

Should someone else stumble upon this issue, here is an article by Rick Strahl on this topic, does not cover everything but it covers enough. Especially since he isn't paid to do it.

https://weblog.west-wind.com/posts/2020/Mar/29/Content-Injection-with-Response-Rewriting-in-ASPNET-Core-3x

It's unfortunate the community has to rely on posts from MVPs for just about anything that's a bit more advanced these days.
