### ISSUE TITLE
Tutorial: Create a web API with ASP.NET Core Gives 415 Error With ASP.NET 5

### ISSUE THREAD

**Issue by AlejandroHuerta** [dotnet/AspNetCore.Docs#20939]
I'm using .NET 5. I get to the point where I make a POST with Postman and I get a 415 Unsupported Media Type response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by AlejandroHuerta** [comment]
I forgot to mention I followed the VS Code instructions. Did you try those?

**Comment by olippold** [comment]
@AlejandroHuerta I had the same issue today but resolved it when I realised that I had not set the type to "JSON" in Postman.

**Comment by Rick-Anderson** [comment]
@olippold  Thanks. That's a typical reason for getting the excellent error message.

**Comment by AlejandroHuerta** [comment]
Yup, that was it. Thanks for the help @olippold
