### ISSUE TITLE
Suggestion: refer to proxy configuration guidelines on non-IIS scenarios

### ISSUE THREAD

**Issue by AlbertoPa** [dotnet/AspNetCore.Docs#20930]
When deploying a hosted Blazor app with Identity Server to a reverse proxy on Linux are needed to avoid errors related to header forwarding. It may be worth linking to these resources:

-  https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#scenarios-and-use-cases

- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0#forward-the-scheme-for-linux-and-non-iis-reverse-proxies

Thanks for considering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback! I'm buried in work ⛏️⛰️ for the next couple of weeks then out for an extended ⛄ *holiday vacation* 🎁. I've added this to my **Post-holiday Triage** issue list and will take a look when I return. Sorry for the delay, but I must get some long-standing priorities resolved before leaving, so only bug fixes will usually be addressed before I get some *much needed* rest 😅. I assure you that this issue won't get lost.

**Comment by AlbertoPa** [comment]
No rush at all with this. All the info is in the doc, so it's not critical. I thought the links would be useful because when deploying on Apache, I had to add some extra configuration, but it is explained in the page about proxy servers and load balancers.

Have a nice break!
