### ISSUE TITLE
Need to document how to create custom EditForm component

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/AspNetCore.Docs#20947]
We've seen that many customers are having trouble with this. So a doc article would help to point everyone to, when they stumble upon this.

**Comment by guardrex** [comment]
@mkArtakMSFT ... I can work this if by "custom" you mean just building one from scratch ... i.e., we could cross-link `master` for this in a new section in the [Forms and valication](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0) doc ...

https://github.com/dotnet/aspnetcore/blob/master/src/Components/Web/src/Forms/EditForm.cs

... and I can call out some of the obvious bits and pieces of it and then have one of the product unit engineers round out the coverage from there. 

However if you were planning on doing something special or beyond/different than that, then I'll leave this issue for the PU to resolve.

**Comment by guardrex** [comment]
@mkArtakMSFT ... I've started working the UE pass for the *Forms and Validation* topic. Do you want me to address this issue as a new section of the topic?

If so, I need a little more info :point_up: if I can work it up from the [framework's `EditForm` class](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/EditForm.cs) ... **_IF_** that's what the ask is&dagger;. However if the PU should compose the initial content+examples, then I'll wait on this issue.

... and &dagger;*if that's what the ask is* ... I wonder if cross-linking to the PU repo [framework's `EditForm`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/EditForm.cs) isn't enough for those users seeking to create a custom `EditForm` in a short section.

**Comment by mkArtakMSFT** [comment]
Haven't seen any recent asks about this one, so just closing this.
