### ISSUE TITLE
First Test is Wrong

### ISSUE THREAD

**Issue by terryclancy** [dotnet/AspNetCore.Docs#20948]
In first test it says will launch the default browser and navigates to https://localhost:<port>/swagger/index.html

It does not it goes to https://localhost:44351/weatherforecast.

Swagger does not appear to be installed at all. (No Swagger Nuget package or other references) ???

This tutorial needs to be tested !!!!!!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's for the 5.0 version.
