### ISSUE TITLE
Facebook Developers UI has changed

### ISSUE THREAD

**Issue by MrChriZ** [dotnet/AspNetCore.Docs#20955]
There's a few changes to the Facebook Developer UI that need to be reflected in this documentation.
First of all when you first try to create a 'Facebook application' Facebook requests what kind of application you would like to add.
I 'think' the correct answer here is 'Build Connected Experiences'.
Also it's not clear that when looking for the App Secret you need the settings under the Dashboard, not the settings under the newly created login.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This was fixed
