### ISSUE TITLE
What range of status code does UseStatusCodePagesWithReExecute support

### ISSUE THREAD

**Issue by daping123** [dotnet/AspNetCore.Docs#20958]
We know `UseExceptionHandler` is used to catch the exception and you could custom error handling page by using this middleware.But this only support for http 500 error.I have meet some threads in Stackoverflow that they want to handle both 500 and 400 or 404 and so on.Microsoft provide a middleware called `UseStatusCodePagesWithReExecute` which seems could did such thing.But it does not support for http 500 error.And the document does not mention the range of the http status code for `UseStatusCodePagesWithReExecute`.

Reference:

https://stackoverflow.com/questions/65312473/why-i-cant-return-view-with-usestatuscodepageswithreexecute-middleware-in-asp-n/65316603

https://stackoverflow.com/questions/62985803/global-customization-of-error-responses-from-bet-core-3-1-webapi/62989600

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0#usestatuscodepages)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  this looks interesting

**Comment by serpent5** [comment]
`UseStatusCodePagesWithReExecute` handles all codes from `400` to `599`, but it achieves this only by looking at the `HttpResponse.StatusCode` set by following middleware. It doesn't catch exceptions, so it will not run for unhandled exceptions.
