### ISSUE TITLE
Range limitation for InputNumber not working

### ISSUE THREAD

**Issue by martinmueller4voice** [dotnet/AspNetCore.Docs#20959]
When I bind a numeric property with a `Range(x,y)` data annotation attribute to a Blazor `InputNumber` component, the corresponding validation messages are generated when I leave the range.

But in order to actually limit the range available using the up/down arrows, I must resort to the `min` and `max` HTML attributes for `input` tags.

This leads to range values having to be entered at separate locations, easily leading to mistakes.

Shouldn't the InputNumber component set the `min` and `max` value from the `Range` attribute of the bound property automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @martinmueller4voice ...

> the corresponding validation messages are generated when I leave the range

... but the form won't submit with validation errors is the way that they were probably thinking about it. You could build a custom `InputNumber` component that has that behavior.

As far as the framework component having that behavior OOB, it falls into the *feature request* bucket, so open that request for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... if they agree, they'll schedule it and add the behavior to the component.
