### ISSUE TITLE
Manually delete bin and obj folders

### ISSUE THREAD

**Issue by ThomasBleijendaal** [dotnet/AspNetCore.Docs#20956]
I updated two of my .NET Core 3.1 Blazor Webassembly apps to .NET 5.0 and in both cases the dev server kept serving `dotnet.3.1.x.js` file instead of `dotnet.5.0.1.js` which resulted in a lot of 404 since the wrong DLLs were requested. Solved the issue in both cases by just deleting the `bin` and `obj` folders manually, because even Clear Solution did not delete them enough. Perhaps this could be included in the "Clean and rebuild the solution" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@ThomasBleijendaal  @SteveSandersonMS  @guardrex  should I update the migration doc with this tip?

**Comment by guardrex** [comment]
I wish it weren't that way, but IIRC "cleaning a solution" only gets the compiled files (.dll and .exe), so I've had to do that too from time-to-time.

I think all of the migration topics could have a general *Troubleshoot* section that calls out this tip for all app types.

Plus, it might be nice to call out the `dotnet nuget locals --clear all` command to nuke package caches. It doesn't help as much as it used to in the old days 👴, but I've still seen it clear a rare package problem even these days. If you want to add that, the cross-link is ....

> \[dotnet nuget locals](/dotnet/core/tools/dotnet-nuget-locals)

**Comment by Rick-Anderson** [comment]
That seems like good advice right at the top.

1. Delete bin and obj folders
2. `dotnet nuget locals --clear all`
