### ISSUE TITLE
Cookie authentication without ASP.NET Core Identity 400 Error

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#20968]
---
**Issue moved from MicrosoftDocs/feedback#3308**
- Please respond to @gabriel-rod.

---

_From @gabriel-rod on Thursday, December 3, 2020 2:40:10 AM_

**Describe the bug**
The bug it's 400 error when i want to authenticate with this project https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/security/authentication/cookie/samples/3.x/CookieSample

**To Reproduce**
1. Execute the project
2. Sign In with the suggested information
3. Write in the url the path to sign in (base url + /account/login), go to that url
4. Try to sign in
5. This result in a 400 error

**Expected behavior**
It should go to Login (httpPost) method and sign in.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 87.0.4280.66 (Build oficial) (64 bits)

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3308**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Thursday, December 3, 2020 2:40:12 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by guardrex** [comment]
I can't repro a problem with the 3.x sample app ...

<img width="408" alt="Capture" src="https://user-images.githubusercontent.com/1622880/102408749-ae3f1e00-3fb3-11eb-8f2f-844dfbe1b664.PNG">

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
