### ISSUE TITLE
Bad performance in code example

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetCore.Docs#20966]
The example code, splits a string into an array of strings and parses IP addresses for each request.

This is a bad advice to users as it cause unnecessary use of memory and CPU cycles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
With 2K PV/month, the most we can do is add a warning that this is sub-optimal.
Saving the list  as a string is probably not how  customers with large lists store them. I'm sure it's more common to store them in data store they can edit.

@mkArtakMSFT  please review and comment.

**Comment by paulomorgado** [comment]
@Rick-Anderson, the `string` as list is only one of the issues.

The code is still parsing the IP address and creating an array of bytes for each one, for EVERY REQUEST.

This is general bad advice. A user might come to this doc looking for advice on a different use case and take from this doc that everything must be initialized on every request.
