### ISSUE TITLE
swagger support

### ISSUE THREAD

**Issue by jefdaels** [dotnet/AspNetCore.Docs#20964]
I have to check the Enable open API support to start the swagger page when pressing ctrl-F5, although that option is unchecked in the provided screenshot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This tutorial doesn't cover API, it's UI only.

**Comment by jefdaels** [comment]
Hi,
I'm sorry, I posted the remark in the wrong tutorial (I had several ones open, got redirected to github to log in, and returned to the wrong one)
The issue should have been made for https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio
Do you want me to repost?
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio>
Tutorial: Create a web API with ASP.NET Core<https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio>
Learn how to build a web API with ASP.NET Core.
docs.microsoft.com



Met vriendelijke groeten,

Kind regards,

Jef Daels

________________________________

**Comment by Rick-Anderson** [comment]
That tutorial works correctly. I'm not sure why you had a problem.

**Comment by jefdaels** [comment]
Hi,
When I follow the tutorial https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio , I unchecked Enable OpenAPI support as suggested in the screenshot below (found in the tutorial)
When I start the program with CTRL-F5 (also according to the tutorial) the swagger page was not shown (as should according to the tutorial) but the weatherforcast page was.
When I recreated the project with Enable OpenAPI support checked, the swagger page was shown when starting using CTRL-F5.
I'm working on a Windows system, the screenshot suggests to be a Linux installation, so maybe that's a difference.
Since I got it working, I have no further issue with it.


[cid:6619a435-b6e0-45e0-9dfc-accbed2254a1]


Met vriendelijke groeten,

Kind regards,

Jef Daels

________________________________
