### ISSUE TITLE
Not updated for .Net 5

### ISSUE THREAD

**Issue by supachris28** [dotnet/AspNetCore.Docs#20961]
This has not been updated for .Net 5 - the samples in here generate deprecation build errors in favour of using Microsoft.Identity.Web

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@supachris28 ... It's live now ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0

That's the link to the English-US (`en-US`) version of the topic, which is updated immediately. If you're looking at a localized version of the topic (e.g., English-British, `en-GB`), that might take longer to update ... a day ... or a few days. Localized topics are built by a separate build system for that purpose.

You may need to hit the refresh button in your browser if you were looking at the old `en-US` page, which might be cached locally.

Thanks again for the report. Although technically I'm ⛄ *OOF and on vacation* 🎁 until 2021, I hate 😈 *little doc gremlins* 😈 so much that I'll pause the vacation to squash them as soon as they're reported.

This topic was updated at the top ... the instructions for a new app. The sections for **_upgrades_** obviously slipped, including through product unit review of the 5.0 updates. Sorry about that. It happens. There were *a lot* of updates for 5.0. No doubt, I'll find and receive reports of a few more as we go. If you spot anything else, please do open another issue, and I'll get right on it.
