### ISSUE TITLE
scaffolding fail

### ISSUE THREAD

**Issue by scatman255** [dotnet/AspNetCore.Docs#20969]
---------------------------
Microsoft Visual Studio
---------------------------
Fehler

Fehler beim Ausführen des ausgewählten Codegenerators:

"Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[RazorPagesMovie.Data.RazorPagesMovieContext]' while attempting to activate 'RazorPagesMovie.Data.RazorPagesMovieContext'."
---------------------------
OK   
---------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
