### ISSUE TITLE
Missing instruction to install NuGet package

### ISSUE THREAD

**Issue by kevingy** [dotnet/AspNetCore.Docs#20975]
Following these instructions, I received compile time errors:
error CS1061: 'IServiceCollection' does not contain a definition for 'AddDatabaseDeveloperPageExceptionFilter' and no accessible extension method 'AddDatabaseDeveloperPageExceptionFilter' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
error CS1061: 'IApplicationBuilder' does not contain a definition for 'UseMigrationsEndPoint' and no accessible extension method 'UseMigrationsEndPoint' accepting a first argument of type 'IApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)

I fixed the issue by installing the Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore NuGet package. Needing to install this package to resolve the dependencies is not included in the documentation on this page. Instructions like these are essential to getting the documentation to work end-to-end. If this documentation _requires_ that I go off and research other documentation to get it to work, this page is only half-baked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
No repo. I created a 3.1 UI project with individual user accounts, upgrade NuGet and TFM, updated the code. No new packages were required.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp5.0</TargetFramework>
    <UserSecretsId>aspnet-WebApplication143-E3598AD8-EB7A-403C-AE7E-B692EFB608D7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
