### ISSUE TITLE
https://github.com/guardrex/HostedWASM50AADGroupsAndRolesSample

### ISSUE THREAD

**Issue by manasimahajann** [dotnet/AspNetCore.Docs#20979]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I assume that this has been opened by mistake given that there's no message.

**Comment by manasimahajann** [comment]
> Hello! when i log in the page just hangs in on Completing login... with url https://localhost:5001/authentication/login-callback# in the browser.
I have made sure that api app has GroupMember.Read.All with admin consent
In expose api -- in our case we see "api://" url which i have put it in "https://tenantname. .. " as suggested in the article.
