### ISSUE TITLE
Queued background tasks for .NET Core?

### ISSUE THREAD

**Issue by adamfoneil** [dotnet/AspNetCore.Docs#20976]
[Enter feedback here]
Hi there, I'm wondering about this topic on [Queued background tasks](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#queued-background-tasks). It says this applies to .NET 4.x. Is there any plan to bring this queuing capability to .NET Core `IHostedService`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by adamfoneil** [comment]
okay I just saw this issue
https://github.com/dotnet/AspNetCore.Docs/issues/18605
so maybe this is not happening?

**Comment by Rick-Anderson** [comment]
Correct
