### ISSUE TITLE
Need @ before await Html.PartialAsync(...)

### ISSUE THREAD

**Issue by ig2bagd** [dotnet/AspNetCore.Docs#20987]
Corrected command below:
        @await Html.PartialAsync("_ArticleSection", 
                                section,
                                new ViewDataDictionary(ViewData)
                                {
                                    { "index", index }
                                });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, it's in a block

```
@{
    var index = 0;

    foreach (var section in Model.Article.Sections)
    {
        await Html.PartialAsync("_ArticleSectionRP",
```

**Comment by ig2bagd** [comment]
I tested the associated codes at https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/views/partial/sample and they don't work without the '@' before await Html.PartialAsync .  I ran & checked the codes at both https://localhost:5001/ArticlesRP/ReadRP & https://localhost:5001/Articles/Read.
