### ISSUE TITLE
remove Queued background tasks

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#20995]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by halter73** [comment]
Not that I feel this section was very important or anything, but why is it being removed?

**Comment by Rick-Anderson** [comment]
@halter73 

A background task queue is based on the .NET 4.x QueueBackgroundWorkItem:

If that's in .NET Core 3, .NET 5, then I'll close this issue and related PR.

**Comment by halter73** [comment]
The sample is based on `QueueBackgroundWorkItem` but not dependent on it AFAICT. It defines `IBackgroundTaskQueue.QueueBackgroundWorkItem` and `BackgroundTaskQueue` itself in the sample code.
