### ISSUE TITLE
IIS Hosting documentation has lost instructions for configuring data protection.

### ISSUE THREAD

**Issue by blowdart** [dotnet/AspNetCore.Docs#20994]
In the warning box on this page we have links which say

- Creation of a registry hive for ASP.NET Core Data Protection
- Configuration of the app pool's Access Control List (ACL)

These links used to give instructions on how to configure data protection and the app pool. Now they lead to a generic page with no instructions, and seemingly no link to instructions either (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-5.0#data-protection for example).

So I can't say "Well we documented this" any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson ... I'm sitting here on a Saturday morning at 5am after the 🐈 just woke me up (*Rotten* 😼!) and can't work on the Jeep for another four hours or so. The work splitting up the *BIG* IIS topic into smaller topics broke those links to ...

* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-5.0#data-protection
* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-5.0#application-pool-identity

I'll patch the links up right now.
