### ISSUE TITLE
Scaffold New Items from DB or Identity Fails when Project is created via Visual Studio for .Net Core 3.1 + Angular 8 + Identity Enabled

### ISSUE THREAD

**Issue by aloosh9007** [dotnet/AspNetCore.Docs#21007]
I will be a bit specific on the process as the issue is a bit ambiguous to solve yet quite common. I created a new API project using Visual Studio Enterprise Edition targeting .Net Core 3.1 with Angular 8. I have checked enable identity checkbox and have received all working components successfully. I then created my database using SQL Server and created DB Models within my project using recommended DBScaffold by Microsoft. Next, I ran the migration provided by Identity to include my AspNet Identity tables in my DB and that ran successfully. However, I ran into scaffolding problems when I tried the following:

Right-Click Solution > Add > New Scaffolded Item > API Controller with actions, using Entity Framework.
Right-Click Solution > Add > New Scaffolded Item > Identity > Add Identity > Account\Login (or any other component) > Add
The error in both cases was very general and says:
"There was an error running the selected code generator: Package restore failed. Rolling back package changes for 'ProjectName'.'
I do have the following NuGet packages:
microsoft.visualstudio.web.codegeneration.utils 3.1.4
microsoft.aspnetcore.identity.ui 3.1.4
in addition to web.CodeGeneration.Core, Web.CodeGeneration, EFCore.SqlServer, EFCore.Tools and they are all 3.1.4 to make sure I am consistent
This seems an issue that many have reported and seems to be closed several times without a resolution. I even tried upgrading my VS Enterprise to latest as of (12/1/2020) and still no luck

**Comment by guardrex** [comment]
@aloosh9007 ... Are you deleting the metadata when you open the issue? 

Paste the link to the topic into a comment here, and I'll manually add the metadata to your opening comment.

**Comment by Rick-Anderson** [comment]
use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).
