### ISSUE TITLE
Scaffold New Items from DB or Identity Fails when Project is created via Visual Studio for .Net Core 3.1 + Angular 8 + Identity Enabled

### ISSUE THREAD

**Issue by aloosh9007** [dotnet/AspNetCore.Docs#21004]
I will be a bit specific on the process as the issue is a bit ambiguous to solve yet quite common. I created a new API project using Visual Studio Enterprise Edition targeting .Net Core 3.1 with Angular 8. I have checked enable identity checkbox and have received all working components successfully. I then created my database using SQL Server and created DB Models within my project using recommended DBScaffold by Microsoft. Next, I ran the migration provided by Identity to include my AspNet Identity tables in my DB and that ran successfully. However, I ran into scaffolding problems when I tried the following: 
1. Right-Click Solution > Add > New Scaffolded Item > API Controller with actions, using Entity Framework.
2. Right-Click Solution > Add > New Scaffolded Item > Identity > Add Identity > Account\Login (or any other component) > Add
The error in both cases was very general and says: 
"There was an error running the selected code generator: Package restore failed. Rolling back package changes for 'ProjectName'.'
I do have the following NuGet packages:
1.  microsoft.visualstudio.web.codegeneration.utils 3.1.4
2.  microsoft.aspnetcore.identity.ui 3.1.4
3. in addition to web.CodeGeneration.Core, Web.CodeGeneration, EFCore.SqlServer, EFCore.Tools and they are all 3.1.4 to make sure I am consistent 
This seems an issue that many have reported and seems to be closed several times without a resolution. I even tried upgrading my VS Enterprise to latest as of (12/1/2020) and still no luck

**Comment by guardrex** [comment]
Hello @aloosh9007 ... If this issue pertains to a specific topic, close this issue and re-open it using the **This page** feedback button and form at the bottom of the topic. It will add document metadata to your issue and ping the author of the topic.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/21007.
