### ISSUE TITLE
Is ThenInclude even required anymore?

### ISSUE THREAD

**Issue by MikeyFriedChicken** [dotnet/AspNetCore.Docs#21009]
I have been testing out including properties from multiple levels using just the Include extension method and it seems to work completely fine.  The exact same SQL is generated if i had used the long winded Include / ThenInclude pattern.

For example instead of

            var result = query
                .Include(x=> x.Item)
                .ThenInclude(x=> x.User)
                .ThenInclude(x=> x.Address)

I just do

            var result  = query
                .Include(x => x.Item.User.Address)

If this is indeed the case can the documents be updated accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Looks correct to me. cc @tdykstra 
@roji  or @JeremyLikness 30 second review.
