### ISSUE TITLE
Need to check "Enable OpenAPI support"

### ISSUE THREAD

**Issue by botura** [dotnet/AspNetCore.Docs#21012]
Need this option to enable Swagger support and tutotial work as expected.

[Create a web project](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#create-a-web-project)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It does. Try it again

```
dotnet new webapi -o TodoApi
cd TodoApi
code -r ../TodoApi
```

**Comment by Rick-Anderson** [comment]
Image needs to have default OpenAPI checked.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api/_static/5/vs.png?view=aspnetcore-5.0
