### ISSUE TITLE
There's no WriteAsync method on the HttpResponse

### ISSUE THREAD

**Issue by opcodewriter** [dotnet/AspNetCore.Docs#21015]
On https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0 there are different examples which shows a call to `WriteAsync` on the `HttpResponse` instance returned by HttpConext.Response:

```
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapGet("/", async context =>
        {
            await context.Response.WriteAsync("Hello World!");
        });
    });
```
But no matter the version of ASP.NET Core, there was never a `WriteAsync` on the `HttpResponse`:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponse?view=aspnetcore-5.0

There are different code examples with `context.Response.WriteAsync`, please fix them all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @opcodewriter ... Add a `using` ...

```csharp
using Microsoft.AspNetCore.Http;
```

... it comes in from `HttpResponseWritingExtensions` ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresponsewritingextensions.writeasync?view=aspnetcore-5.0
