### ISSUE TITLE
Tutorial generates an error

### ISSUE THREAD

**Issue by MemTet** [dotnet/AspNetCore.Docs#21025]
In Migration, at the ASP.Net Core MVC totorial 
Using both CLI and PMC I got the following error:
"There is already an object named 'Course' in the database".
Help.

**Comment by guardrex** [comment]
Hello @MemTet ... Please re-open this issue using the **This page** feedback button and form at the bottom of the English-US (`en-us`) topic. It will add metadata indicating the topic and automatically ping the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
