### ISSUE TITLE
Remove myget urls from docs

### ISSUE THREAD

**Issue by mmitche** [dotnet/AspNetCore.Docs#21021]
The aspnet myget uris in some files in this repo are no longer live (those feeds have been retired). They should be removed. I do not believe they need to be replaced with any new feed.

**Comment by Rick-Anderson** [comment]
Can you give me some examples.

**Comment by mmitche** [comment]
Example: https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index/sample/NuGet.config#L5

Might be the only one.
