### ISSUE TITLE
Add documentation for how to use W3C Trace Context correlation ids

### ISSUE THREAD

**Issue by svdHero** [dotnet/AspNetCore.Docs#21022]
I am trying to use correlation ids in .NET in general and, in particular, with ASP.NET 5.0. As mentioned in https://docs.microsoft.com/de-de/dotnet/core/compatibility/core-libraries/5.0/default-activityidformat-changed .NET 5.0 uses W3C Trace Context as defined in https://www.w3.org/TR/trace-context.

However, I have never used the `Activity` class before. All I want to do in ASP.NET is access the `traceparent` http header and update the `parent-id` value on outgoing requests, according to https://www.w3.org/TR/trace-context/#processing-model.

How would I do that? In particular, how would I generate a unique 8 Byte `parent-id` value as specified here: https://www.w3.org/TR/trace-context/#parent-id, while .NET only offers a 16 Byte `GUID`. Are there any helper methods for this?

Is there any documentation/tutorial how to work with said W3C Trace Context values in (ASP).NET 5.0? If not, please add some.

**Comment by serpent5** [comment]
There's some information about `Activity` in the dotnet/runtime repo [here](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md). I don't know if it covers everything you need, but it might be a start.

**Comment by svdHero** [comment]
@serpent5 Thank you for the link. I will certainly have a look. However, I was hoping for some information that is more specific to ASP.NET Core. I don't need the whole Activity machinery. All I want is to generate a `parent-id` for outgoing requests to other back-end services or when implementing a process manager that generates commands in a CQRS / DDD setting.

Is there any TL;DR version on how to use / forward W3C Trace Context in ASP.NET Core?

**Comment by svdHero** [comment]
@serpent5 I've read the guide you linked now. However, it dos not mention W3C at all and the Activity Id format described does not reflect what I in my Visual Studio Debugger. Is this guide still relevant or is it outdated?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by svdHero** [comment]
@Rick-Anderson the lack of activity was not from my side. I don't see how this issue is resolved. My last question has not been answered. I haven't checked the documentation recently, but if it hasn't changed significantly, I still think it should be improved for people who are new to tracing.

**Comment by Rick-Anderson** [comment]
Lack of activity means others who are looking for a solution.

**Comment by svdHero** [comment]
@Rick-Anderson okay. Fair enough. Thanks for clarifying.
