### ISSUE TITLE
Impersonation: RunImpersonated should work for async workloads

### ISSUE THREAD

**Issue by poke** [dotnet/AspNetCore.Docs#21020]
The docs on impersonation currently say this:

> `RunImpersonated` doesn't support asynchronous operations and shouldn't be used for complex scenarios. For example, wrapping entire requests or middleware chains isn't supported or recommended.

However, that doesn’t seem to be the case, going by what happened in dotnet/runtime#24009. The async overloads there do nothing than forward `Func<Task<T1>>` as a `Func<T2>` to the `RunImpersonated` so that the return type is `Task<T1>` itself. This also seems to be supported by [the docs on `RunImpersonated`](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=net-5.0):

> This method may be used reliably with the async/await pattern, unlike `Impersonate`. In an async method, the generic overload of this method may be used with an async delegate argument so that the resulting task may be awaited.

So maybe warning in the documentation is just a remnant from previous docs that used `Impersonate` there?

Anyway, in the runtime issue, there is also explicit mention by @davidfowl of [wrapping the entire middleware pipeline in a `RunImpersonated`](https://github.com/dotnet/runtime/issues/24009#issuecomment-544196325):

```csharp
app.Use(async (context, next) =>
{
    await WindowsIdentity.RunImpersonated(someToken, () => next());
});
```

So I would expect that this scenario is indeed fully supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#impersonation)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@poke  please ping me after the new year and I'll have the security folks review this.

**Comment by poke** [comment]
@Rick-Anderson I’ll try to remember! 😅 Happy holidays!

**Comment by poke** [comment]
@Rick-Anderson Happy New Year! _(\*ping\*)_

**Comment by Rick-Anderson** [comment]
@blowdart  please review or suggest a reviewer. I can get this fixed ASAP once approved.

**Comment by blowdart** [comment]
@GrabYourPitchforks should know, this is corefx rather than asp.net, and I'm not sure who owns it. 

@davidfowl is your suggestion actually tested, or theoretical?

**Comment by davidfowl** [comment]
No async impersonation should work fine
