### ISSUE TITLE
Missing dotnet run command

### ISSUE THREAD

**Issue by GirishKumarSharma** [dotnet/AspNetCore.Docs#21039]
I am following this link :
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio-code
in the last step you showed the browser page, but there is no mention of dotnet run command.
Why you people left in the dark? Do you feel any joy after it?

**Comment by guardrex** [comment]
Please open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
