### ISSUE TITLE
This page missing the navigation  for Connection string prefixes

### ISSUE THREAD

**Issue by VitorX** [dotnet/AspNetCore.Docs#21035]
The page is missing navigation title on the right side for **Connection string prefixes** like figure below
![image](https://user-images.githubusercontent.com/12635993/103051828-a7776300-45d2-11eb-838d-44e09db16afa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Only H2's show up in navigation, not H3's
