### ISSUE TITLE
Is Microsoft.AspNetCore.Diagnostics.HealthChecks still referenced by ASP.NET Core apps?

### ISSUE THREAD

**Issue by IvanAlekseev** [dotnet/AspNetCore.Docs#21031]
I am not sure that information in Prerequisites section is correct. I am refering to this bit:
>The Microsoft.AspNetCore.Diagnostics.HealthChecks package is referenced implicitly for ASP.NET Core apps. To perform health checks using Entity Framework Core, add a package reference to the

Microsoft.AspNetCore.Diagnostics.HealthChecks package looks stuck on .net 2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@IvanAlekseev ... The statement is still true. Framework assemblies aren't referenced as individual packages any longer. You won't see them in nuget.org with the latest package version any longer. If you look in the `Microsoft.AspNetCore.App` framework package in a 5.0 app's framework assemblies in VS, you'll see it in there at 5.0. Here's an example for a 5.0 test app that I use to test Razor Pages apps ...

<img width="335" alt="Capture" src="https://user-images.githubusercontent.com/1622880/103038457-181b7280-4534-11eb-8b87-83dc6b706a82.PNG">
