### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by GirishKumarSharma** [dotnet/AspNetCore.Docs#21040]
[Enter feedback here]
I using Ubuntu 20.10 64 bit.

I have downloaded the AspNetCore.Docs-master.zip and placed the contents of
AspNetCore.Docs/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50/
RazorPagesMovie50 folder in /home/girish/Projects/aspnetcore folder. All went fine.When I runs the code by Runing Ctrl+F5 and clicks on first RpMovie link it gives me :

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'RazorPagesMovie.Data.RazorPagesMovieContext' while attempting to activate 'RazorPagesMovie.Pages.Movies.IndexModel'.

Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)

and here it is complete error stack :

InvalidOperationException: Unable to resolve service for type 'RazorPagesMovie.Data.RazorPagesMovieContext' while attempting to activate 'RazorPagesMovie.Pages.Movies.IndexModel'.

    Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
    lambda_method24(Closure , IServiceProvider , object[] )
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelActivatorProvider+<>c__DisplayClass1_0.<CreateActivator>b__0(PageContext context)
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelFactoryProvider+<>c__DisplayClass3_0.<CreateModelFactory>b__0(PageContext pageContext)
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.CreateInstance()
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

How do I solve it. This is my first issue posting, so there are big chances that I am not following proper rules or missing basic info. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Not sure. Why don't you just follow the tutorial.

**Comment by Rick-Anderson** [comment]
Please try following the tutorial and let us know how that works.

**Comment by Rick-Anderson** [comment]
You probably need to set it up for SQLite, it defaults to SQL Server Express.

**Comment by Rick-Anderson** [comment]
@GirishKumarSharma 
See 
![image](https://user-images.githubusercontent.com/3605364/103146325-9110fa80-46eb-11eb-81a8-11ec67696ebf.png)

**Comment by GirishKumarSharma** [comment]
Are you sure there is sqllite instructions for this tutorial exists? What is link? Don't behave like an alien.
