### ISSUE TITLE
Unhelpful replies by maintener

### ISSUE THREAD

**Issue by GirishKumarSharma** [dotnet/AspNetCore.Docs#21044]
[Enter feedback here]
I have mentioned all the error stack and required info which I could in earlier post but by just saying:

"Not sure. Why don't you just follow the tutorial."

is not a proper reply. I downloaded the zip file, extracted the code and simply run. Code run without any error but one tab RpMovie (the first one) returning the error.

There are many new technologies emerging and lot of mainteners welcome newbies, they don't shows their expertise to them. If Microsoft still works like this, shutters may be down near in future. Be polite and helpful as much as possible.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #21040

**Comment by Rick-Anderson** [comment]
Please try following the tutorial.

**Comment by GirishKumarSharma** [comment]
This is really very bad behavior of maintener. I want to complaint against him. Neither he is saying where to start tutorial nor providing any answer to the error.

**Comment by Rick-Anderson** [comment]
Start at the beginning

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start

**Comment by GirishKumarSharma** [comment]
Now I am getting localdb not supported on this platform. I am on Ubuntu 20.10, I don't have sql server, don't know how to configure / install is sqllite blah-blah.

**Comment by Rick-Anderson** [comment]
Select the VSC tab, which provides SQLite instructions.

**Comment by GirishKumarSharma** [comment]
Where is that VSC tab? What is VSC means?

**Comment by GirishKumarSharma** [comment]
Leave it, all this is waste of time. I will learn some other technologies (other than these shit MS tech)

Bye. Last post.
