### ISSUE TITLE
missing: Learning Path or Learn TV links.

### ISSUE THREAD

**Issue by croban** [dotnet/AspNetCore.Docs#21058]
Can you also add links to Learning Path or even better links to Learn TV. That would be great ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @croban ... The learning path is to work down the topics in order in the table of contents (the sidebar list of links). We can't provide video of anything due to staffing limitations and the high degree of churn in framework features.

**Comment by croban** [comment]
I was thinking something like this https://docs.microsoft.com/en-us/learn/modules/build-blazor-webassembly-visual-studio-code/
as a learning path, but okay...

**Comment by guardrex** [comment]
We don't want to focus on VS Code ... or any particular IDE for that matter. Also, we want to focus new-dev experiences on Blazor Server, not WASM ... at least at this time.
