### ISSUE TITLE
System.Text.Encodings.Web nuget package required on server project.

### ISSUE THREAD

**Issue by rob-github** [dotnet/AspNetCore.Docs#21054]
I had to add System.Text.Encodings.Web nuget package to server project to get this to work. 
You might mention that in the tutorial. 
Thanks for providing it anyway :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rob-github ... I've seen this come up a few times, but I can't repro it, and the posters never say **_exactly_** what bit of API in the app is requiring it ...

* https://github.com/dotnet/AspNetCore.Docs/issues/20752#issuecomment-736523984
* https://github.com/dotnet/AspNetCore.Docs/issues/20645

Can you say what API is requiring it in the app? ... perhaps paste in the method to clarify it so that I can try and repro this again.

**Comment by guardrex** [comment]
Also, please specify more environment details: Framework version? SDK version? Platform (OS)?

**Comment by BrennanConroy** [comment]
This is a bug when users use System.Text.Json 5.0 in a netcoreapp3.1 project.
Issue: https://github.com/dotnet/runtime/issues/45560

**Comment by guardrex** [comment]
Thx @BrennanConroy ... Although Eric gave it a 5.0.x milestone, it's easy for me to surface this to readers in a NOTE and open a follow-up issue cross-linked to the engineering issue to revert the NOTE later. It's probably the best course of action given that @rob-github is the third reader to open a docs issue on it.

**Comment by rosdi** [comment]
I just had the same problem. I just updated my dependencies and suddenly the system won't run on the server anymore with this error (it runs fine in Visual Studio).

Adding `System.Text.Encodings.Web 5.0.1` explicitly into my ASP.NET Core 5.0 project makes the error goes away.
