### ISSUE TITLE
div class page

### ISSUE THREAD

**Issue by ndc** [dotnet/AspNetCore.Docs#21066]
This is about point 3 in `Update Blazor WebAssembly and Blazor Server projects`:

> In the MainLayout component (Shared/MainLayout.razor), surround the component's HTML markup with a <div> element that has a class attribute set to page: `<div class="page">`

I tried googling about the "page" css class, maybe it has something to do with the new CSS isolation feature. Didn't look like it. Maybe it is related to some other new features in asp.net core 5? I couldn't find any further info about it.

My suspicion is that it is only related to the CSS in the default project template. I don't use the CSS from the default template anymore so this step is not relevant to me.

If my suspicion is true, can you add a note for step 3 that this is only needed if you still use the CSS from the default template? It may save some time for future readers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @ndc ... Yes, it's CSS isolation (in >=5.0) ...

* https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/common/samples/5.x/BlazorWebAssemblySample/Shared/MainLayout.razor.css#L1
* The stylesheet is called out in the *Project structure* topic :point_right: https://docs.microsoft.com/aspnet/core/blazor/project-structure.
* The stylesheet is the very next bullet point (`MainLayout.razor.css`).

We're probably not going to document the template CSS classes given that ...

* These classes supplied by the default template are easy to find and use or not use as one see's fit.
* Might change in any given release.

The *Migration* topic just needs to cover the changes. When I get to my UE (i.e., user experience) pass on the *Layouts* topic on https://github.com/dotnet/AspNetCore.Docs/issues/19286, I'll take a look at how we're describing the styles. I'll cross-link this issue to that one to make sure that I'm reminded of your remarks.

**Comment by guardrex** [comment]
FYI @ndc ... I was able to resolve this in the *Layouts* topic updates. For >=5.0 content, the topic will cross-link to the *CSS isolation* topic and show the `MainLayout` component's companion CSS stylesheet. I didn't want to ping u on that PR because it will receive several more commits and I don't want you to get pinged to death 😵😄.

https://github.com/dotnet/AspNetCore.Docs/pull/21636

**Comment by ndc** [comment]
Appreciate the update @guardrex !
