### ISSUE TITLE
ASP.NET Core SignalR client support for Internet Explorer unclear

### ISSUE THREAD

**Issue by chrisseed** [dotnet/AspNetCore.Docs#21068]
The "Differences between SignalR and ASP.NET Core SignalR" page under "Internet Explorer support" states that IE 11 is supported.

However, the "suppported platforms" link goes to https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#javascript-client which doesn't mention Internet Explorer at all - which implies no versions of Internet Explorer are supported.

Which interpretation is right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?preserve-view=true&view=aspnetcore-3.1)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @chrisseed ... **_NOT_** supported is the correct answer now. We nipped it at https://github.com/dotnet/AspNetCore.Docs/pull/20006/files#diff-46981e07c501d40216198dc1bbaa56d8fed881f537e51e19d62134b961eee2f1L28 from the *Supported platforms* doc but didn't catch it here. I'll take care of it right now. Thanks for calling it out. I'll ping u on the PR.
