### ISSUE TITLE
Confusing single \` at the end of a code try that I suspect should be removed

### ISSUE THREAD

**Issue by MrSethT** [dotnet/AspNetCore.Docs#21078]
#code-try-13 ends in a \`.  This one \` is the only one on the whole page.  If it should be there, it should be mentioned.  If it should not be there, it should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MrSethT ... Would you mind looking in the GH blame and identifying the exact line that you're referring to by line number?

https://github.com/dotnet/AspNetCore.Docs/blame/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

**Comment by MrSethT** [comment]
#209

-Seth

**Comment by guardrex** [comment]
Ah ... yes ... that's a bug. I'll patch that up. Thanks.
