### ISSUE TITLE
Suggestion: Add Paragraph "Set Env in Web.config Manually"

### ISSUE THREAD

**Issue by shadinamrouti** [dotnet/AspNetCore.Docs#21079]
_Dear Friends_

_It will be useful to add a section about modifying the web.config manually in order to set the env. 
Personally, I was looking for a similar section as below_

### Set Env in Web.config Manually

1. Open web.config
2. Modify the section:

```xml
<aspNetCore processPath="dotnet" arguments=".\ExampleProject.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
```

to become:
```xml
<aspNetCore processPath="dotnet" arguments=".\ExampleProject.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" >

      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
      </environmentVariables>

</aspNetCore>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0&source=docs)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @shadinamrouti ... The existing cross-link got a little bit broken. It goes to the right area (node), but the content was moved around a bit recently. It now lives at ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0#set-environment-variables

Rick, it's Line 219 of this topic ... should probably be changed from ...

> To set the \`ASPNETCORE_ENVIRONMENT\` environment variable with \*web.config\*, see the \*Setting environment variables\* section of \<xref:host-and-deploy/aspnet-core-module#setting-environment-variables>.

... to (this is a cut-'n-paste) ...

> To set the \`ASPNETCORE_ENVIRONMENT\` environment variable with \`web.config\`, see the `*Set environment variables`* section of \<xref:host-and-deploy/iis/web-config#set-environment-variables>.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
