### ISSUE TITLE
where is the parameterless constructor?

### ISSUE THREAD

**Issue by sdudnic** [dotnet/AspNetCore.Docs#21072]
The doc says: 

> ```
> public class PositionOptions
> {
>     public const string Position = "Position";
> 
>     public string Title { get; set; }
>     public string Name { get; set; }
> }
> ```
> An options class:
> * Must be non-abstract with a public parameterless constructor.

so, **where is** the *parameterless constructor* in the example ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by RugerSR9** [comment]
Your parameterless constructor in this case is created by default since you do not have any constructors defined to override that behavior. So it'd just be `new PositionOptions();`.

See docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors

**Comment by sdudnic** [comment]
> Your parameterless constructor in this case is created by default since you do not have any constructors defined to override that behavior. So it'd just be `new PositionOptions();`.
> 
> See docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors

this fact could be mentionned at least by the way, for the readers, because is not evident when reading. it clearly says it _should have parameterless constructor_, but if fact, there is any need to create a constructor at all, because a parameterless constructor is created by default, so the readers will not bother creating a constructor if they could leave it as is...
