### ISSUE TITLE
Global exception handling feature

### ISSUE THREAD

**Issue by yv989c** [dotnet/AspNetCore.Docs#21074]
It would be nice to highlight somewhere in this page that global exception handling is being discussed here: https://github.com/dotnet/aspnetcore/issues/13452

I had to search for it because the concept is missing from this documentation.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbc1392-92dc-c42e-ba48-a722cffa9b6d
* Version Independent ID: 66a0b1c2-c45c-98ca-9808-6f340a861c44
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-5.0#lifecycle-methods)
* Content Source: [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @yv989c ... We don't document most cases of in-design discussions for a few reasons ...

* I'm usually swamped with work such that cross-links to discussions would go stale when those discussions are closed out as either worked items or won't-fix scenarios.
* Product unit managers and engineers don't want "*bikeshedding*" to occur, where the document leads *many readers* over to the engineering issue and a massive number of comments, including silly ":+1:" comments, are left that overwhelm the engineers.

We generally focus the docs on what the framework can do in a given release today. Searching the product unit's repo is the right thing to do when you want to know what they're considering and what they're working on.

**Comment by yv989c** [comment]
That makes sense @guardrex . Thank you for taking the time to explain.
