### ISSUE TITLE
Configuration.GetSection is not static, but presented as such

### ISSUE THREAD

**Issue by sdudnic** [dotnet/AspNetCore.Docs#21082]
Having this example on the bellow mentioned page 

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<TopItemSettings>(TopItemSettings.Month,
                                       Configuration.GetSection("TopItem:Month"));
    services.Configure<TopItemSettings>(TopItemSettings.Year,
                                        Configuration.GetSection("TopItem:Year"));

    services.AddRazorPages();
}
```
I have a compile error

> Error	CS0120	An object reference is required for the non-static field, method, or property 'Configuration.GetSection(string)'	..\Program.cs

Surely, the `GetSection` is not a static method of the `Configuration `class, so, is not clear from where it is coming this "Configuration"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
The template projects create a `Configuration` property on the `Startup` class:

```csharp
public IConfiguration Configuration { get; }
```

This means that the call to `Configuration.GetSection` operates on the `Configuration` property and not the `Configuration` class.

**Comment by sdudnic** [comment]
> The template projects create a `Configuration` property on the `Startup` class:
> 
> ```cs
> public IConfiguration Configuration { get; }
> ```
> 
> This means that the call to `Configuration.GetSection` operates on the `Configuration` property and not the `Configuration` class.

I don't use a template, I have a **Console** .NET Core application. **I have no Startup class.**

**Comment by Rick-Anderson** [comment]
@sdudnic  per the doc
This topic provides information on the options pattern in ASP.NET Core. For information on using the options pattern in console apps, see Options pattern in .NET.
