### ISSUE TITLE
UseInMemoryDatabase extension method is no longer in the Microsoft.EntityFrameworkCore.SqlServer package

### ISSUE THREAD

**Issue by hoborm** [dotnet/AspNetCore.Docs#21094]
Hi!

I've found an issue in the documentation under the "[Add database context](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#add-a-database-context)" section. The issue is in that the UseInMemoryDatabase cannot be found in the NuGet package Microsoft.EntityFrameworkCore.SqlServer it can actually be found in the Microsoft.EntityFrameworkCore.InMemory NuGet package. Installing this package through the UI actually makes this code snippet work:
`            services.AddDbContext<TodoContext>(opt =>
                                               opt.UseInMemoryDatabase("TodoList"));`

Also, adding the NuGet package with VSCode is also missing. My suggestion would be to provide CLI commands to add the mentioned package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hoborm ... It's in the topic ... see the last bullet of ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#add-nuget-packages

**Comment by hoborm** [comment]
Oh right, well the VSCode problem still persist.

**Comment by guardrex** [comment]
That's in a different section earlier in the topic ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#create-a-web-project

**Comment by guardrex** [comment]
... and the macOS way is a little further down ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-mac#to-access-a-command-terminal-from-finder

**Comment by hoborm** [comment]
You are right @guardrex excuse my lack of thoroughness.
