### ISSUE TITLE
Where is DisposeAsync() called?

### ISSUE THREAD

**Issue by firewater** [dotnet/AspNetCore.Docs#21095]
In BlazorSignalRApp/Client/Pages/Index.razor :

```
public async ValueTask DisposeAsync() {
    await hubConnection.DisposeAsync();
}
```
Can someone please help me understand what part of the application actually calls the DisposeAsync method above. I'm struggling to connect the dots. Thanks.

**Comment by guardrex** [comment]
Hello @firewater ... Please re-open this issue from the bottom of the topic that you're using with the **This page** feedback button and form. The metadata added to your opening comment using that approach will automatically ping the author of the topic.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
