### ISSUE TITLE
JwtBearerOptions在哪里？？？

### ISSUE THREAD

**Issue by yangbing007** [dotnet/AspNetCore.Docs#21098]
[JwtBearerOptions类是.net core 1中的，在.net core 5的文章中为什么不移除？？？迷惑大家。]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
English translation ...

> Why not remove from the article? ? ? Confused everyone.

**Comment by guardrex** [comment]
If you're looking for the assembly/namespace for API, you can use the API Browser. For example (for `JwtBearerOptions`) ...

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer.jwtbeareroptions

**Comment by yangbing007** [comment]
In the section "https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0#customize-the-api-authentication-handler", the class "JwtBearerOptions" is no longer in "asp.net core 5.0"!!!!!, but it has not been removed in time....

**Comment by guardrex** [comment]
Ok ... thanks for clarifying.

Javier is the author on this topic, and he's already been notified of this issue.

cc: @scottaddie ... just because it looks like you performed the last major overhaul/update on this one.

**Comment by Rick-Anderson** [comment]
Per @serpent5 
The `JwtBearerOptions` class comes from the [Microsoft.AspNetCore.Authentication.JwtBearer](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.JwtBearer/) NuGet package, so the @yangbing007might not have referenced this. It's included indirectly via [Microsoft.AspNetCore.ApiAuthorization.IdentityServer](https://www.nuget.org/packages/Microsoft.AspNetCore.ApiAuthorization.IdentityServer/), which is included in the templates used by this topic.
