### ISSUE TITLE
This is missing a few key usage scenarios

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#21109]
like if you need to have the same service exposed via both http based and non http based bindings, you cant migrate. 

On the same topic, are there any performance comparisons available for a .net gRPC service vs a .net WCF service using protobuf and netTCP binding?  That would be a more Apples/Apples comparison than grpc vs http-based wcf bindings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67e987d3-28fc-6fb4-3a4c-d4f6ee9cb32d
* Version Independent ID: 0587f983-8a67-b732-8292-836e5388c439
* Content: [Why migrate WCF to ASP.NET Core gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/why-migrate-wcf-to-dotnet-grpc?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/why-migrate-wcf-to-dotnet-grpc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/why-migrate-wcf-to-dotnet-grpc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @markrendle
* Microsoft Alias: **wpickett**

**Comment by JamesNK** [comment]
There isn't an option for non-HTTP-based gRPC.

There isn't a performance comparison between gRPC and WCF from Microsoft but someone in the community compared them: https://unwcf.com/posts/wcf-vs-grpc/

Note that gRPC on .NET has gotten much faster since then.
