### ISSUE TITLE
Improve Kestrel endpoints page

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#21117]
Giant Kestrel page [is being split up](https://github.com/dotnet/AspNetCore.Docs/pull/21091). After that PR is merged the new standalone endpoints page should be improved.

Currently the most important sections are focused around APIs, rather than what a user wants to achieve.

Possible table of contents:

* Introduction to endpoints (e.g. high-level description of address, protocol, HTTPS, etc)
* Configure endpoints with `URLs`
  * URL prefixes
* Configure endpoints in appsettings.json
  * Configure endpoint defaults
  * HTTPS
* Configure endpoints in code
  * Endpoint defaults
  * HTTPS
  * TCP socket endpoints
  * Unix socket endpoints
  * Dynamic port binding
  * Connection logging
* Configure HTTPS
  * Summary (links to other HTTPS sub-sections)
  * Configure endpoints using SNI
* Endpoint protocols

@halter73 @tratcher

tdykstra edit to add Document details section

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**
* 

---
[Associated WorkItem - 82758](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82758)

**Comment by Tratcher** [comment]
I'd move appsettings.json above the endpoints API as more commonly used for intermediate scenarios.

HTTPS as a separate node? Wouldn't you cover a lot of that when doing appsettings.json and the endpoints API?

**Comment by JamesNK** [comment]
> HTTPS as a separate node? Wouldn't you cover a lot of that when doing appsettings.json and the endpoints API?

Yes, although I think it is still useful to have a high-level `Configure HTTPS` section. "I want HTTPS" is such a common task, it will provide a place for people to find which would then link to configuring HTTPS in the appsettings.json and endpoint API sections.

It's complicated to structure this doc because everything is so cross-cutting (you could configure a HTTPS URL in appsettings.json and specify HTTPS defaults in code, etc)

😬
