### ISSUE TITLE
Scaffolding errors on MVC5

### ISSUE THREAD

**Issue by foxychev** [dotnet/AspNetCore.Docs#21123]
I encounter an error while scaffolding identity into MVC project with authorization:
 "/path-to-project/obj/Debug/net5.0/Razor/Templates/Identity/Pages/_ValidationScriptsPartial.cshtml.g.cs(36,135): error CS0103: The name StartTagHelperWritingScope does not exist in the current context"
It also repeats for 'EndTagHelperWritingScope' and 'CreateTagHelper'.
I do not encounter this error while scaffolding controller and view files, without changing any file in the project. What could be the problem?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Scaffolding problems should be reported to https://github.com/dotnet/Scaffolding
