### ISSUE TITLE
Feedback on RazorPagesMovie part 2, add a model

### ISSUE THREAD

**Issue by henriquebg88** [dotnet/AspNetCore.Docs#21125]
Pasting the command `dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries` on the console was creating a folder named PagesMovies instead of creating a folder Movies inside Pages folder. Had to change  from `Pages\Movies` to `Pages/Movies`.
Probally because i am using git Bash on windows. i know it's not a bug, but since it's a tutorial for beginners(?), maybe the page should mention it. 
Also i had many problems with "RazorPagesMovieContext.cs" where VS Code was not detecting: 
_public DbSet<RazorPagesMovie.**Models**.Movie> Movie { get; set; }_ 
i typed the Models folder name wrong (_Moels_), and then renamed it. VS Code could't find the file anymore.
_"The type or namespace name 'Models' does not exist in the namespace 'RazorPagesMovie' (are you missing an assembly reference?) [RazorPagesMovie]csharp(CS0234)"_
I had to delete both Models and Data folders and do it all again, and Add NuGet packages again, following the tutorial order.
But i still have no idea why VS Code was not identifying it, since it was right there, and the namespaces where all correct..
Even tryed to insert `using RazorPagesMovie.Models`  
But no problem to compile and run the page. 

i'd appreciate if i could get an explanation, or a link to one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Probally because i am using git Bash on windows
Bash on windows in not supported. This is a rare configuration. Even so, the instructions help you out

![image](https://user-images.githubusercontent.com/3605364/103692135-6fa9dd00-4f3b-11eb-954c-f9a06d47774c.png)

Not sure about your other problem. Might try asking on SO
