### ISSUE TITLE
Missing a section abuout using dynamic configuration

### ISSUE THREAD

**Issue by Lechus** [dotnet/AspNetCore.Docs#21124]
[Enter feedback here]
I would like to see a section about using dynamic configuration (using Azure Application Configuration) in Typed HttpClient.

TypedHttpClient(HttpClient httpClient, IOptionsSnapshot<ApiConfigurations> apiConfig)

```
private async Task<string> GetAccessToken()
{
	var dynamicValue = apiConfig.Value.Email;
}
```

The value should be updated / up2date in next call (changing sentinel,  the cache timeout, etc).
Is this even possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
