### ISSUE TITLE
Suggestion: Enable Azure AD RBAC option for connection string

### ISSUE THREAD

**Issue by mdddev** [dotnet/AspNetCore.Docs#21145]
Hello

In some cases the DB is Azure-AD-aware, e.g. Azure SQL. User principals with admin permissions should be able to leverage RBAC not needing to provide either user id or password in the connection string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows#secret-manager)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
> User principals with admin permissions should be able to leverage RBAC not needing to provide either user id or password in the connection string.

Do you have an issue with the doc? We document ASP.NET Core. Your assertion has nothing to do with this document.
