### ISSUE TITLE
@layout Limitation

### ISSUE THREAD

**Issue by ehsangfl** [dotnet/AspNetCore.Docs#21143]
@layout directive is working only for pages that accessed via @page directive of internal navigation system.
this is not work for component call inside another component or page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0#specify-a-layout-in-a-component)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ehsangfl ... Yes, that's correct. The framework permits [nested layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0#nested-layouts) but not **_nested components with layouts_**. I'll add content to the introduction to cover it. If you want to suggest a new framework feature for it, you can open it on their repo at ...

https://github.com/dotnet/aspnetcore/issues

Leave this issue open. It will close automatically when the PR merges.

**Comment by guardrex** [comment]
This was fixed by https://github.com/dotnet/AspNetCore.Docs/pull/21162.
