### ISSUE TITLE
Simplified Blazor Component without Overhead

### ISSUE THREAD

**Issue by neufel42** [dotnet/AspNetCore.Docs#21165]
I would love to see a simplified Blazor Component Model that is just basically a RenderFragment.  I have a few lists where each row of the list is a set of components.  These are basic components just so I don't have to have 10 lines of html code for each column.  These lists when done with components get really slow really fast. (25 - 50 rows and it almost becomes unusable).  To work around this I use RenderFragments and it works well and makes it speedy again.   However, I then lose the nice readability of using a custom tag for each item.  Instead I find myself injecting code within my html.  

// This just returns a RenderFragment
@MyComponent.RenderComponent(new MyComponentOptions()
{
	Param1="some Parameter",
	Param2="some Parameter",
	Param3="some Parameter",
})

instead of:
// Can not use simple components that just basically render html because they make the application way too slow
<MyComponent
	Param1="some Parameter",
	Param2="some Parameter",
	Param3="some Parameter"
></MyComponent>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @neufel42 ... Please open product feedback for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
