### ISSUE TITLE
 ReceiveBufferSize used in the snippet is incorrect

### ISSUE THREAD

**Issue by mattsmall1972** [dotnet/AspNetCore.Docs#21164]
[Enter feedback here]
The image below shows that "ReceiveBufferSize" is used in the code snippet but this property is obsolete:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.websocketoptions.receivebuffersize?view=aspnetcore-5.0#Microsoft_AspNetCore_Builder_WebSocketOptions_ReceiveBufferSize

![image](https://user-images.githubusercontent.com/28765633/104051399-113c6300-51b6-11eb-985d-be8729fdf420.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-5.0#configure-the-middleware)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BrennanConroy @bradygaster  is someone can provide the upgraded code I'll get this fixed ASAP.

**Comment by BrennanConroy** [comment]
Remove the property and reference to it. There is no equivalent
