### ISSUE TITLE
Sharing Cookies among ASP.NET apps does not work with a session store

### ISSUE THREAD

**Issue by avendel** [dotnet/AspNetCore.Docs#21163]
The instructions at https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-3.1#share-authentication-cookies-with-aspnet-core-identity don't work when you use an `ITicketStore` (`CookieAuthenticationOptions.SessionStore`).

The reason is that the session id claim set by Owin has the type string `Microsoft.Owin.Security.Cookies-SessionId` while ASP.Net Core expects `Microsoft.AspNetCore.Authentication.Cookies-SessionId`. The result is that the ASP.Net core can't find a session key to use. See https://github.com/dotnet/aspnetcore/blob/master/src/Security/Authentication/Cookies/src/CookieAuthenticationHandler.cs#L151.

I implemented a workaround that can be found at https://stackoverflow.com/a/65630992/587277.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-3.1#share-authentication-cookies-with-aspnet-core-identity)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  @blowdart  please review.

**Comment by Tratcher** [comment]
The scenario and workaround make sense, though both are pretty advanced.
