### ISSUE TITLE
MessagePackProtocol in Blazor

### ISSUE THREAD

**Issue by harveytriana** [dotnet/AspNetCore.Docs#21169]
I have used MessagePackProtocol in projects with SignalR.

Does it apply the same way for Blazor WebAssembly projects?

(is not an issue, is only a doubt)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @harveytriana ... I haven't heard that it wouldn't work, but ask the product unit on their repo at ...

https://github.com/dotnet/aspnetcore/issues
