### ISSUE TITLE
Inconsistent instruction for new project creation

### ISSUE THREAD

**Issue by ConaxLiu** [dotnet/AspNetCore.Docs#21171]
Just want to make aware that in the **Create the web app project** section, 5b states to select ASP.NET Core Web App. However, the screenshot that follows is highlighting **ASP.NET Core Web App (Model-View-Controller)** instead. Reader is confused with which template to choose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #20631
