### ISSUE TITLE
Demo isnt working

### ISSUE THREAD

**Issue by Dyloneus** [dotnet/AspNetCore.Docs#21179]
For this demo, I had to add the System.Text.Encodings.Web nuget package to get it to compile.

I also kept getting stuck when clicking send, with the following message: 
Cannot send data if the connection is not in the 'Connected' State. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [Use ASP.NET Core SignalR with a hosted Blazor WebAssembly app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Dyloneus ... You're likely looking at the wrong version of the topic. It's covered here (in this version) ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#add-the-systemtextencodingsweb-package

> I also kept getting stuck when clicking send, with the following message:
>
> Cannot send data if the connection is not in the 'Connected' State.

That one I haven't seen. You'd need to open an issue for the product unit to investigate or receive feedback on. Open an issue at ...

https://github.com/dotnet/aspnetcore/issues

I'll close given that the first part is already covered and the second part isn't actionable for docs (*yet* ... after you chat with engineering about it, we can re-open this issue if the topic needs a NOTE or a content change).
