### ISSUE TITLE
Static file auth doc fix

### ISSUE THREAD

**Issue by ScottStabb** [dotnet/AspNetCore.Docs#21184]
In this article, you'll find the sentence
"The preceding approach requires users to be authenticated:"

But the preceding approach actually was showing how resources could be served to non-authenticated users by placing the UseStaticFiles line before authentication.

You could update this to:

"The preceding approach requires users to be authenticated, but serves static resources to unauthenticated requests"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by ScottStabb** [comment]
Not sure how to do that and don’t want to screw something up.
The problem text actually refers to the ‘following’ code, not preceding


Existing text:
The preceding approach requires users to be authenticated:


Recommended text:
The following approach requires user authentication while serving static files anonymously:
