### ISSUE TITLE
No content??

### ISSUE THREAD

**Issue by conflab15** [dotnet/AspNetCore.Docs#21192]
[Enter feedback here]

Absolutely no content whatsoever?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not available for 1.1.
1.1 is not supported.
Select another version that's supported.

![image](https://user-images.githubusercontent.com/3605364/104249596-e0576a80-540f-11eb-8fbd-4562324bcb7d.png)

 @scottaddie 
Can we get unsupported versions removed from the version selector?
