### ISSUE TITLE
Ugly text

### ISSUE THREAD

**Issue by vuguzum** [dotnet/AspNetCore.Docs#21191]
Very ugly description. Meaningless and useless. Makes no sence for programmers used to MVC and WebForms. What's the difference? Why it all is needed? No answer. Just auto documentation. Like we did it because we get paid for this. Eat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What specifically don't you like?

**Comment by vuguzum** [comment]
You may have noticed two questions in my previous note?

пн, 11 янв. 2021 г. в 22:37, Rick Anderson <notifications@github.com>:
