### ISSUE TITLE
Update all layout files to use non minified CSS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21193]
The templates generate a layout file the uses the minified assets:

```
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" 
...
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
```

But our `.gitignore` file excludes them. So remove the `.min`

---
[Associated WorkItem - 63629](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63629)

**Comment by Rick-Anderson** [comment]
cc @scottaddie, @wadepickett , @guardrex 
When creating new content, try to remember to make this change.  It's not easy to remember because you have the minified assets locally and don't notice the problem.

**Comment by guardrex** [comment]
To resolve this for Blazor samps, I keep a `.gitignore` in the Blazor directory at ...

https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/.gitignore

If it's ok with you, I'd like to keep that because it solves troublesome maintenance problems for the sample apps.

**Comment by Rick-Anderson** [comment]
@guardrex  you own blazor and I have no objections.  I won't update any blazor files.

**Comment by guardrex** [comment]
Cool ... one less thing for me to foul up. lol :smile:😅:smile:
