### ISSUE TITLE
Importing modules in blazor needs specific path prefix

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/AspNetCore.Docs#21206]
The section "Blazor JavaScript isolation and object references" on https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references describes how to import modules. The documentation is correct in using `"./_content/MyComponents/exampleJsInterop.js"` as the path. I think it should be highlighted that the prefix `./` is crucial here, as just `"_content/MyComponents/exampleJsInterop.js"` would *not* work.

Please consider adding a warning note to this section, highlighting the importance of the correct path specification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aada0049-99a8-2f91-5d60-6970474e2371
* Version Independent ID: c29fb1a8-028f-6efd-f1bc-e889fb362311
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references)
* Content Source: [aspnetcore/blazor/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stefanloerwald ... This bit was a cut-'n-paste from the release blog post at ...

https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-release-candidate-1/#blazor-javascript-isolation-and-object-references

... and I didn't :eyes: notice the delta there.

@captainsafia ... We normally don't require the relative path/current directory segment (`./`) for static assets. This is the only spot in the Blazor docs where we call for it. Is this a special case requirement? If so, why?

The example above with the segment is ...

```csharp
var module = await js.InvokeAsync<IJSObjectReference>(
    "import", "./_content/MyComponents/exampleJsInterop.js");
```

I'd correct the text to match that with a reason along the lines of ...

> Specify the module using its stable static web asset path: \`./_content/{LIBRARY NAME}/{PATH UNDER WWWROOT}\`.  The relative path segment for the current directory (\`./\`) is required because ... {WE SAY WHY HERE}.
