### ISSUE TITLE
DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase' 

### ISSUE THREAD

**Issue by gregrobinsongmailcom** [dotnet/AspNetCore.Docs#21214]
In the section "Register the database context"

Updating the class "Startup.c"

I am geting the error with the line " opt.UseInMemoryDatabase("TodoList")); "  it can't dind the method UseInMemoryDatabase
The error message is 
"Error	CS1061	'DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase' and no accessible extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)"

What I am I missing here ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gregrobinsongmailcom ...

It's the last bullet of ...

https://docs.microsoft.com/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#add-nuget-packages

> Use the preceding instructions to add the `Microsoft.EntityFrameworkCore.InMemory` NuGet package.
