### ISSUE TITLE
[Request] Host public (MVC/RazorPages) and private (WebAPI) apps in same solution

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#21216]
## Help us make content visible
search terms: web app api mvc razor host together server

## Describe the new topic
Building and deploying multiple apps from the same solution.

## Explain why this topic is needed.
It's a common use case.
 
## Suggest a location in the Table of Contents.
Either under hosting, or a link in the advanced sections in MVC, RazorPages and WebAPI sections.

## Write an abstract. In one **short** paragraph, describe what this topic will cover.

Sites typically have:
- `www.example.com`: a public MVC/RazorPages server-rendered app for guests
- `app.example.com`: a private WebAPI app for customers and admins (accessible by a SPA)

To keep things simple and manageable these two apps (i.e. projects) should be kept in the same solution. They share lots of stuff: code, styling, database, etc.

I expect this is a simple config change in `Startup.cs`. Please show us how to do that.

## Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
- explain problem (www vs app)
- explain how to enable MVC/RazorPages and WebAPI in same `Startup.cs`
- explain how deployment works

**Comment by Rick-Anderson** [comment]
Hosting web UI and Web API in the same solution is no problem, it's implementing the security on the web API side and deploying the app. Closing unless @blowdart  objects.

**Comment by lonix1** [comment]
Sure it's no problem, it can be done. But how? That's the question.

Many sites have the "app.example.com" section, as well as the "www.example.com" section for marketing stuff. This is a very common use case.

There's no guidance for that.

**Comment by blowdart** [comment]
That's a different question altogether though. Those are generally separate sites running on specific host names, not one big site which adjust behavior based on host

**Comment by lonix1** [comment]
Agreed big sites run subdomains separately, but most aspnet users aren't "big", so if they have this need (it's common) they'll run both in the same app. I've designed my that way.

That's why I was hoping for official docs on this. We're talking about config really, not design decisions or anything complex like that.

The security is where it gets interesting.
