### ISSUE TITLE
Explain reason for using Newtonsoft.JSON

### ISSUE THREAD

**Issue by mikewop** [dotnet/AspNetCore.Docs#21229]
With the switch to using System.Text.Json as the default in .Net 5, why is Newtonsoft.Json needed for JSON PATCH processing?
The webpage does not explain the rationale for having to use Newtonsoft.Json.

Is it a limitation in System.Text.Json? Is it being added/fixed in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5 @tdykstra  can we do this with `System.Text.Json` ?

**Comment by serpent5** [comment]
`Microsoft.AspNetCore.JsonPatch` has used `Newtonsoft.Json` long before `System.Text.Json` was introduced. I don't think there are plans to update it to use `System.Text.Json` or to create a spin-out version.

See https://github.com/dotnet/aspnetcore/issues/24333.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
