### ISSUE TITLE
Add docs on building Authentication.Msal dependency with custom MSAL.js version

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#21230]
[EDIT by guardrex to add the metadata]

We need to add a new section in our docs about building a custom version of the Authentication.MSAL JavaScript library in Blazor that uses a different version of MSAL than the one we distribute.

This will allow users to chose their own MSAL dependency version to ship with in case ours does not contain a bug fix or feature they need.

The steps require:

1. Closing the aspnetcore repo.
2. Updating the package version [here](https://github.com/dotnet/aspnetcore/blob/e4a0a800171cd354edb4ef6c33c2048cb89511ea/src/Components/WebAssembly/Authentication.Msal/src/Interop/package.json#L16).
3. Building the project and copying the JavaScript file placed in `dist/Release`.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@captainsafia ... Is the plan that the draft content will be provided in a comment here that I can then shape into content for this?

Also, is this for a new topic in the Blazor *Security and Identity* node? ... or should this become a new section in the [*Security and Identity* node *Overview* topic](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0).

**Comment by captainsafia** [comment]
@guardrex I can help you draft the content in whatever way is helpful.

The steps above are a good start.

> ... section ... yea ... I hear you and the short list of clear steps indicates that a mere section in the Overview topic should cover this.

Sounds good!

**Comment by guardrex** [comment]
**_Note to self_** ...

* https://www.npmjs.com/package/@azure/msal-browser
* https://github.com/AzureAD/microsoft-authentication-library-for-js/releases
