### ISSUE TITLE
Surprising mention of WeatherForecastService

### ISSUE THREAD

**Issue by hugh-maaskant** [dotnet/AspNetCore.Docs#21240]
Hi, 

It looks like this section was lifted from an example or tutorial as it mentions the "WeatherForecastService" which is not introduced (e.g. as "an example service used by the app").

This is confusing, thanks, Hugh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31248d7-d2c2-1a17-3173-889a0d9bb6e8
* Version Independent ID: 6f27ff37-6b3a-57f5-353a-5cf5aabba7cf
* Content: [ASP.NET Core Blazor project structure](https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/project-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's part of the project template as called out by the opening ...

> The following files and folders make up a Blazor app generated from a Blazor project template:

**Comment by guardrex** [comment]
I think I see what you mean now. I was just looking at composing the topic in two sections for the hosting models and noticed that the mention of the service is a bit out of context where it appears early in the list. It might work out tho that if I go alphabetical with the file and folder names that the service call out under "Data" (letter "D") earlier than "Startup" ("S") might do the trick. Therefore, I'll re-open this and resolve both at the same time.
