### ISSUE TITLE
Consider describing structure separately for Blazor WebAssembly and Blazor Server templates

### ISSUE THREAD

**Issue by hugh-maaskant** [dotnet/AspNetCore.Docs#21241]
The structure of a Blazer project itself is already rather complex (on first read). For me it would be easier if the structure + content would be described separately for a WebAssembly template and a Server template. The "inlining" now is hard to parse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31248d7-d2c2-1a17-3173-889a0d9bb6e8
* Version Independent ID: 6f27ff37-6b3a-57f5-353a-5cf5aabba7cf
* Content: [ASP.NET Core Blazor project structure](https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/project-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hugh-maaskant ... I *think* 🤔 that I agree with you. I'll see how it composes tomorrow and get back to you.
