### ISSUE TITLE
Error Page Documentation Doesn't Explain how Non-Get Failures Work

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/AspNetCore.Docs#21255]
Currently, the exception handler documentation shows how to write a custom exception handler in the `OnGet` method of the error page. 

What isn't covered is that the Error page method executed will mirror the type of operation that generated the failure. For example, if the error occurred in a post request, the Error page's `OnGet` will never be called, and instead an `OnPost` method will be called on the error handler page. 

So, for example, you could add something like this to the example:

```csharp
public void OnPost() # for failures in POST requests. 
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;

        var exceptionHandlerPathFeature =
        HttpContext.Features.Get<IExceptionHandlerPathFeature>();
        if (exceptionHandlerPathFeature?.Error is FileNotFoundException)
        {
            ExceptionMessage = "File error thrown";
            _logger.LogError(ExceptionMessage);
        }
        if (exceptionHandlerPathFeature?.Path == "/index")
        {
            ExceptionMessage += " from home page";
        }
    }
```

And then add a note indicating that the handler fired depends on the verb where the error occurred. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0#exception-handler-page)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  this sounds like a fun one.

**Comment by serpent5** [comment]
@Rick-Anderson Sure, I'll sort this one.
