### ISSUE TITLE
context has not ModelState - (sample code seems to be not correct!)

### ISSUE THREAD

**Issue by aehomay** [dotnet/AspNetCore.Docs#21254]
[Here](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#validation-failure-error-response)  the code shows that the context has ModelState while it does not!

```
services.AddControllers()
    .ConfigureApiBehaviorOptions(options =>
    {
        options.InvalidModelStateResponseFactory = context =>
        {
            var result = new BadRequestObjectResult(context.ModelState);
            result.ContentTypes.Add(MediaTypeNames.Application.Json);
            result.ContentTypes.Add(MediaTypeNames.Application.Xml);

            return result;
        };
    });

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#use-apibehavioroptionsclienterrormapping)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by Rick-Anderson** [comment]
@pranavkm is this code wrong?

**Comment by serpent5** [comment]
This sample code looks good to me.

[`InvalidModelStateResponseFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apibehavioroptions.invalidmodelstateresponsefactory) receives an instance of [`ActionContext`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actioncontext) as the `context` argument in the sample code, which has a [`ModelState`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.actioncontext.modelstate) property:

```csharp
public ModelStateDictionary ModelState { get; }
```

**Comment by pranavkm** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/174281/105419916-5029da00-5bf4-11eb-8835-8607c6901924.png)
