### ISSUE TITLE
Blazor InputFile component example should be extended.

### ISSUE THREAD

**Issue by EdCharbeneau** [dotnet/AspNetCore.Docs#21261]
The Blazor InputFile component example should be extended to include:

1. Creating a proper Http request using PostAsync
2. Binding a controller action to receive the request using IFormFile

Please see the example linked below for ideas. https://github.com/EdCharbeneau/BlazorPowerHour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@guardrex Let's get this work prioritized. I witnessed much confusion this morning while Ed was covering this topic on his Twitch stream. A handful of customers in the audience were looking for the same info in our docs.

**Comment by guardrex** [comment]
Thanks @scottaddie and @EdCharbeneau ... Let's call this a dup of https://github.com/dotnet/AspNetCore.Docs/issues/20323.
