### ISSUE TITLE
Blazor CSS isolation scopes

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#21269]
https://github.com/dotnet/aspnetcore/issues/29493

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by daveabrock** [comment]
Want me to take this? I can probably do it tonight.

**Comment by guardrex** [comment]
@daveabrock ... That would be a **_HUGE_** help if you can. I'm 🏃⛰️⛏️ buried in things to do around here right now, including a big Blazor Server + SignalR tutorial update. Greatly appreciated if you can do this.

**Comment by daveabrock** [comment]
Will do. In a few talks I've given, folks have asked about inheritance like this, so it'll be good to document.

**Comment by musictopia2** [comment]
Just to let you know that I found out by using the sample that the scoped even works if not doing inheritance.  However, somehow requires the name to always be custom-scope though.
