### ISSUE TITLE
Adding keys table to database is not straight-forward

### ISSUE THREAD

**Issue by lukos** [dotnet/AspNetCore.Docs#21279]
In our application, we have a DbContext that is obtained from shared libraries and is not defined in the app, this means that neither of the methods of adding the tables to the DB will work since the context won't be found in the app.

I'm not sure if this is a shortcoming of the product, but the document should describe how to add the table manually in case the dotnet/migration methods can't be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio#entity-framework-core)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by lukos** [comment]
Sorry, I just realised it is semi-described below the instructions on adding it. Can you confirm that this is the entire table in the text and not just some of the columns used for the illustration.

**Comment by Rick-Anderson** [comment]
The columns were not added just for illustration.
