### ISSUE TITLE
Introducing mess with "Blazor" first word

### ISSUE THREAD

**Issue by sdudnic** [dotnet/AspNetCore.Docs#21277]
Suppose I am newbie in .net core, and start learning  about _ASP.NET Core Razor components_ (the article's title).

I am completely out of the theme, when, having any idea on what is that "razor components", the first word of the article is "**Blazor**"... I would think this is a typo, the author probably would like to write "_Razor_" instead. 

I suppose you can imagine if reader reads first time about "Razor", it usually means it has any idea of "Blazor"'s even existence. 

I propose to rewrite the first paragraph in order to be compatible with people that does not necessarily want to know about "Blazor" but rather wondering to understand the concept of the .net core razor components, as the title suggest. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [Create and use ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sdudnic ... Yes, I agree that we can generalize Razor components at this point. On first release, they could **_only_** be used in Blazor apps. Now, they can be used in Razor Pages/MVC apps.

I'm currently performing a set of UE ("user experience") passes to update all of the Blazor topics on #19286, and I hope to reach this topic soon for work. I've cross-linked this to that issue, and I'll take care of this when I reach the topic.

Thanks for writing in on it.
