### ISSUE TITLE
Scoped CSS file and associated .razor component must be in the same directory - but this is not mentioned anywhere

### ISSUE THREAD

**Issue by Maritims** [dotnet/AspNetCore.Docs#21289]
It would seem that for CSS isolation to work the CSS file has to be placed in the same directory as the associated razor component. It took me a little while to figure out as it's not written in the documentation.

Ideally I'd prefer to be able to keep these files in separate directories, but if it can at least be added to the docs that they need to be in the same directory that'd probably save the next guy some time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Maritims ... It already explains (by example) that ...

> ... create a file alongside the component ...

A couple of lines before that, it says ...

> To define component-specific styles, create a .razor.css file matching the name of the .razor file for the component.

... so that could receive an update where "in the same folder as the component" is added to the end of the sentence for ...

> To define component-specific styles, create a .razor.css file matching the name of the .razor file for the component in the same folder as the component.

WRT ...

> Ideally I'd prefer to be able to keep these files in separate directories,

... open product suggestions for the product unit. They do want to hear dev feedback for feature improvements. You can open an issue with them at ...

https://github.com/dotnet/aspnetcore/issues

@daveabrock ... Do you want to include this work with the other issue that you're planning to do ... knock them both out 🥊😵 on the same PR?

**Comment by daveabrock** [comment]
@guardrex, yep, I'll clarify it and bundle both issues in the same PR.

**Comment by guardrex** [comment]
Ok, cool. No rush on these, of course. I'm very happy to have your assistance given my workload. The 🙏 *server gods* 🙏 will bless you with *galactic programmer karma!* :smile:

**Comment by Maritims** [comment]
@guardrex Ah, I see the "alongside" now. Thank you for pointing that out 😄 I will blame my mistake on English not being my primary language, sorry! 😖

**Comment by guardrex** [comment]
No worries. Dave was going to work up some bits to cover https://github.com/dotnet/AspNetCore.Docs/issues/21269, and this will be quick to address at the same time.

**Comment by daveabrock** [comment]
@Maritims - thanks for reaching out! It could definitely be clearer.
