### ISSUE TITLE
Document easier Razer file compilation in .net5

### ISSUE THREAD

**Issue by aersamkull** [dotnet/AspNetCore.Docs#21280]
There is a quite complicated tutorial for how to enable Razor View Compilation with Asp.Net Core 3+
However if I just do `dotnet new webapp --razor-runtime-compilation` with .Net 5 SDK, it seems to be as easy as follows:

- Add `<CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>` to csproj
- Add Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation v5.*
- Add `"ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" ` to launchSettings.json

There is no need to change anything in Startup.cs
So, please delete the no longer needed content in order to not scare anyone :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  should we add these instructions?

**Comment by Rick-Anderson** [comment]
@aersamkull are you talking about [Enable runtime compilation in an existing project](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio#enable-runtime-compilation-in-an-existing-project) ? `.AddRazorRuntimeCompilation();` is needed in that case.

**Enable runtime compilation at project creation** has your instructions.

**Comment by aersamkull** [comment]
Oh, I'm sorry, it really seems to be there...
