### ISSUE TITLE
You guys forgot to include the "dotnet run" in the VisualStudio code tab

### ISSUE THREAD

**Issue by mauriciogracia** [dotnet/AspNetCore.Docs#21282]
In your **Tutorial: Create a web API with ASP.NET Core** you forgot to include the "dotnet run" command before trying to open the swagger

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there
Press Ctrl+F5 to run the app. In a browser, go to following URL: https://localhost:5001/swagger

**Comment by mauriciogracia** [comment]
Ctrl + F5 tries to run the web browser and open the launch.json to configure it. That does not execute the "dotnet run" command to have the api running. Please ask or gather information before closing issues

**Comment by Rick-Anderson** [comment]
It does run the app which exposed the API.

**Comment by mauriciogracia** [comment]
Is not doing that, please read my comment above, why would I open this issue if it was working ?

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by mauriciogracia** [comment]
I just run this tutorial and it did not work until I run "dotnet run" in the Terminal.

Maybe you can include that in the tutorial ?

**Comment by Rick-Anderson** [comment]
I recommend finding out why `^F5` is not working in VSC.

**Comment by mauriciogracia** [comment]
Since the documentation is perfect, instead of pointing me to StackOverflow why don't you guys tell me what step I missed ? It should be obvious right ?

I just doubled checked the steps and I run all of the them.

You have not mentioned anything CTRL + F5 opening the launch.json configuration process, is that normal for this kind of proyects ? is that shourcut should run "dotnet run" ?

I feel that you attitude to this simple suggestion is "to close it as fast as possible" without gathering more information and blaming the user instead of helping them out

By the way someone already mention many issues with the CTRL+F5 shortcode 
https://stackoverflow.com/questions/56049421/easiest-way-to-run-debug-asp-net-core-app/59716442#59716442

Thanks for fast but not so useful answers

**Comment by poke** [comment]
> You have not mentioned anything CTRL + F5 opening the launch.json configuration process, is that normal for this kind of proyects ? is that shourcut should run "dotnet run" ?

That’s not what happens here.

If you have the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) installed for Visual Studio Code, which the [documentation lists as a prerequisite](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#prerequisites), then you should get the following prompt when you open your project in Visual Studio:

![“Required assets are missing” prompt in VS Code](https://user-images.githubusercontent.com/132240/105538279-74201500-5cf3-11eb-83d7-e4583eab2674.png)

This is also mentioned [by the documentation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#create-a-web-project):

> When a dialog box asks if you want to add required assets to the project, select **Yes**.

Once you do confirm that, the extension will automatically create the `launch.json` along with a `tasks.json` for other actions. Hitting F5 then will correctly launch the application then.

You do not need to have the C# extension create the `launch.json` for you. You can also do that manually ([see the documentation](https://code.visualstudio.com/docs/editor/debugging)). VS Code even assists you with doing that by offering a template when you hit F5 the first time:

![Templates for the launch action](https://user-images.githubusercontent.com/132240/105538613-f6a8d480-5cf3-11eb-8537-37f5364aa733.png)

Choosing “.NET Core” option there will create the `launch.json` with pretty much the same configuration. Afterwards, you will be able to start your application using F5.

**Comment by mauriciogracia** [comment]
Thanks so much.

I did install the extension for C# and it did created the task.json and other settings. but when selecting from the options:
![image](https://user-images.githubusercontent.com/2321661/105548413-930bb080-5ccd-11eb-9ef5-75024db2cbb5.png) 
Since in the documentation it does not tell you which one to use I selected **Chrome** instead of **.NET Core**

Now when I selected **.NET Core** and press F5 or CTRL+F5 is now working, maybe these steps are mentioned in other documents but not in the specific tutorial
![image](https://user-images.githubusercontent.com/2321661/105548657-e41ba480-5ccd-11eb-9769-ce891e19f2ad.png)

I would be nice if the tutorial documentation could be improved to show this important detail that @poke has mention above or a link to an existing setup documentation

Thanks again.

**Comment by poke** [comment]
> maybe these steps are mentioned in other documents but not in the specific tutorial

I'm confused. I linked to and quoted the particular parts in the documentation that gives you the exact working outcome.

**Comment by mauriciogracia** [comment]
In that document I don't see anything regarding selecting .NET CORE when running CLTR +F5 for the first time (as I show in the screen where only a single row mentions that step)
![image](https://user-images.githubusercontent.com/2321661/105552898-9bb2b580-5cd2-11eb-9d85-9f66dc51ae61.png)

Do you see the step of selecting .NET CORE from the options in the tutorial ?

Basically not all of your detailed steps are mentioned in the tutorial.

**Comment by poke** [comment]
As I said above, confirming to add the required build assets in the prompt that appears is both enough _and_ mentioned in the docs.

The part about creating the `launch.json` manually or through that menu is an optional alternative way which usually isn't the recommended default way to do it. I only included it for completeness sake since you specifically asked about the `launch.json`.

My point was that the explanations outlined in the docs are enough to get the application running.

**Comment by Rick-Anderson** [comment]
> My point was that the explanations outlined in the docs are enough to get the application running.

Correct, we get about 100K folks hitting this tutorial per month, with no reports of a problem. These instructions haven't changed in several years.

**Comment by mauriciogracia** [comment]
@poke please understand that the FIRST TIME you press CTRL+F5 the user has to select the .NET CORE option, can you please show me where that is shown in that tutorial with a screenshot ? (I have shown you 2 times that this is not mentioned) the images that you shown me here and the specific step is not in the tutorial I have checked 5 times at least.

Documentation is no updated by the lack of feedback received by people who successfully use it, speciall because most of them are aware on how to configure the LAUNCH.JSON for the first time, documentation is improved by covering corner cases and things that are not obvious to everyone (meaning to the people that take the time to open issues and document them in detail)

Also please be aware that this issue was CLOSED with the first answer without even trying to understand what I am saying, which is not only rude bud a bad practice. (Best practice is to make sure the issue was solved...THEN is closed)

Just to provide you some background I have been working 17 years with .NET in general and only 1 year in NET CORE, plus 5 years providing support, and based on that experience I want to say that this whole thread does not seem oriented to solve issues but just a way of saying "we are right and you are wrong and we are not going to add a single line to our docs because is obvious"

This is an experience I don't ever want to live again.

**Comment by mauriciogracia** [comment]
@Rick-Anderson your argument is that something is perfect because it has not changed in years ? then remove the button to provide feedback on that page, that would have save me a lot of time.

**Comment by poke** [comment]
To quote myself again:

>> When a dialog box asks if you want to add required assets to the project, select Yes.
>
> Once you do confirm that, the extension will automatically create the launch.json along with a tasks.json for other actions. Hitting F5 then will correctly launch the application then.

This is in the documentation and all that you need to do here.

**Comment by mauriciogracia** [comment]
@poke it seems then that the extension did not created the launch.json otherwise It will not ask me to choose the type of configuration to use
@poke it seems then that the extension did not created the launch.json otherwise It will not ask me to choose the type of configuration to use
@poke it seems then that the extension did not created the launch.json otherwise It will not ask me to choose the type of configuration to use
@poke it seems then that the extension did not created the launch.json otherwise It will not ask me to choose the type of configuration to use
@poke it seems then that the extension did not created the launch.json otherwise It will not ask me to choose the type of configuration to use
