### ISSUE TITLE
Breaking links

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#21283]
@wadepickett ... I think something broke on https://github.com/dotnet/AspNetCore.Docs/pull/21233 ...

* The ToC has an `xref-not-found` in `aspnetcore/toc.yml` ... "Cross reference not found: 'tutorials/first-mvc-app/index'." AFAICT, that topic doesn't exist or was moved to `start-mvc.md`.
* For the article at https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-5.0 ... When the **Edit** button is clicked, it tries to load `https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/index.md`, but that's not a topic/UID any longer, so it 404s. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  make sure you redirect the deleted file.
commit comment says
@wadepickett
Removed overview (index.md), added **_redirect_**, updated toc, updated ref… …
d05b270
But there's no redirect

**Comment by wadepickett** [comment]
I see what happened.  I updated the redirect in .openpublishing.redirection.json accidently in the wrong branch.

**Comment by Rick-Anderson** [comment]
@wadepickett  make sure you check the build before you merge.

**Comment by guardrex** [comment]
> check the build before you merge

I think it's fair to say that we've all been burned by this over the years :cry:🙈:smile:.

Wade ......

<img width="634" alt="willis" src="https://user-images.githubusercontent.com/1622880/105532195-20d8a300-5cb0-11eb-86de-f8065db785f4.png">

*Welcome to the party, pal!* - John McClane ([Bruce Willis](https://www.imdb.com/name/nm0000246/)), [Die Hard](https://www.20thcenturystudios.com/movies/die-hard), @copy;1988 [20th Century Fox](https://www.20thcenturystudios.com/)

**Comment by wadepickett** [comment]
I did test* the build, and verified the TOC was looking as it should, but *failed (completely, totally and embarrassingly)  to test links that would use the redirect.
