### ISSUE TITLE
System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

### ISSUE THREAD

**Issue by V4A001** [dotnet/AspNetCore.Docs#21284]
I cannot reach the exact product page where to post this to.

I received suddenly this error by using docker compose. 
`System.InvalidOperationException: 'Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.`

I tried all solutions except the one on this page particular for docker compose. Why? Because I never had to and it worked for a couple of months out of the box.

Recreating the developer certificates did not work. So finally I deleted the docker-compose setup in the VS solution. I recreated it by add --> Container Orchestration Support. The running it in either debug and release mode worked again.

I see a lot of people struggling and why this is happening if fully unclear. Maybe you can post it on the right page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf7806c-d9e4-1811-3308-b5efb6f159f0
* Version Independent ID: 2117dfa1-9e6d-2bc2-2348-e792f3c81806
* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-compose-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ravipal
* Microsoft Alias: **ravipal**

**Comment by Rick-Anderson** [comment]
>  I cannot reach the exact product page where to post this to.

@spboyer  can you help out?

**Comment by spboyer** [comment]
https://docs.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/visual-studio-tools-for-docker
