### ISSUE TITLE
Incorrect/misleading steps for configuring custom user storage providers

### ISSUE THREAD

**Issue by Ara225** [dotnet/AspNetCore.Docs#21288]
The steps under the header **[Reconfigure app to use a new storage provider](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1#reconfigure-app-to-use-a-new-storage-provider)** say to remove a package called Microsoft.AspNetCore.EntityFramework.Identity. This package exists however it doesn't seem to be installed by default in generated ASP .NET Core apps setup to use individual users stored in app - at least not on .NET 3.1 or higher.

The packages included by default on .NET 3.1+ are:
* Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
* Microsoft.AspNetCore.Identity.EntityFrameworkCore
* Microsoft.AspNetCore.Identity.UI
* Microsoft.EntityFrameworkCore.SqlServer
* Microsoft.EntityFrameworkCore.Tools

It also doesn't mention that Views\Shared\_LoginPartial.cshtml needs to be changed on these projects so that the UI uses the correct user class.

EDIT by @Rick-Anderson : 5.5K pv/month

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's now     `<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.0-*" />`

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
