### ISSUE TITLE
NU1202: Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.2 supports: net5.0 

### ISSUE THREAD

**Issue by davidjackson148** [dotnet/AspNetCore.Docs#21299]
[Enter feedback here]
NU1202: Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 5.0.2 supports: net5.0 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Correct, use the 3.1 version
