### ISSUE TITLE
Type in code example for NavigationManager.Uri

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/AspNetCore.Docs#21291]
The page example for NavigationManager.Uri has a code example that incorrectly reads:
```
var query = new Uri(Navigation.Uri).Query;
```

I believe it should be:
```
var query = new Uri(NavigationManager.Uri).Query;
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @AndrewTriesToCode ... I'll be working tomorrow (Saturday) morning, and I'll take a look and see what's what. Thanks for reporting this. I'll get back to you tomorrow.

**Comment by guardrex** [comment]
It's not incorrect @AndrewTriesToCode ... `NavigationManager` is named `Navigation` on injection (look at the `@inject` line). However, let's go with `NavigationManager` to match the other examples. :+1:
