### ISSUE TITLE
Add documentation on how to automatically create a log scope containing the Activity.Current.Id for each request

### ISSUE THREAD

**Issue by svdHero** [dotnet/AspNetCore.Docs#21306]
At the moment the default JSON error response, e.g., for model validation is something like
```json
{
    "errors": {
        "myValue": [
            "The value 'foo' is not valid."
        ]
    },
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-1958ab77e30b474b9b3fb63a9644756f-3731b87868e4d345-00"
}
```
This error response includes a `TraceId` which has the value of `Activity.Current.Id`, here `"00-1958ab77e30b474b9b3fb63a9644756f-3731b87868e4d345-00"`.
In order to trace back errors like the one above, I want to add this trace id to all of my log messages.

Is there any way to have the ASP.NET Framework create a log scope for each http request BEFORE passing it on to the controller?
I want to avoid having to wrap each single handler method with
```csharp
using (_logger.BeginScope("{TraceId}", Activity.Current.Id))
{
    ...
}
```
Setting `ConsoleFormatterOptions.IncludeScopes` to `true` does not create the scope for me (obviously). That's only half of the job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ericstj please review.

**Comment by ericstj** [comment]
Actually, this might be more ASP.NET specific:
> Is there any way to have the ASP.NET Framework create a log scope for each http request BEFORE passing it on to the controller?

I would imagine this needs to happen in ASP.NETCore cc @pranavkm

**Comment by tarekgh** [comment]
I think @shirhatti can help with this one and answer the raised questions.

**Comment by shirhatti** [comment]
@svdHero What version of .NET are you using? As of .NET 5, the logging libraries implicitly create a scope object with SpanId, TraceId, and ParentId. This behavior can be configured via `LoggerFactoryOptions.ActivityTrackingOptions`

```csharp
  var loggerFactory = LoggerFactory.Create(logging =>
  {
      logging.Configure(options =>
      {
          options.ActivityTrackingOptions = ActivityTrackingOptions.SpanId
                                              | ActivityTrackingOptions.TraceId
                                              | ActivityTrackingOptions.ParentId;
      }).AddSimpleConsole(options =>
      {
          options.IncludeScopes = true;
      });
  });
```

**Comment by tarekgh** [comment]
And this is publicly documented here https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactoryoptions.activitytrackingoptions?view=dotnet-plat-ext-5.0

**Comment by tarekgh** [comment]
@svdHero can we close this issue or do you have any question?

**Comment by Rick-Anderson** [comment]
> @svdHero can we close this issue or do you have any question?

Let's keep this open until I add

> As of .NET 5, the logging libraries implicitly create a scope object with SpanId, TraceId, and ParentId. This behavior can be configured via `LoggerFactoryOptions.ActivityTrackingOptions`

**Comment by svdHero** [comment]
@shirhatti I am using .NET 5 and I will try your code snippet later today and will give feedback. Thank you very much for now.
@Rick-Anderson It might be helpful for beginners to add @shirhatti's little code snippet to the documentation as well.

**Comment by svdHero** [comment]
I have just tried this and it works. When I log a message via `_logger.LogInformation("Hello World!)`, I get a log entry
```
[2021-01-26 11:16:16.362] info: MyProject.MyService[0]
      => SpanId:a59e9e37da39d847, TraceId:dc1c0c758701e74a8f925e9babe78347, ParentId:0000000000000000 => ConnectionId:0HM61TET1KEKT => RequestPath:/api/my-controller/foo RequestId:0HM61TET1KEKT:00000003 => MyProject.MyController.GetFoo (MyProject)
      Hello World!
```
and when an error occurs, I get the JSON corresponding JSON response
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "title": "An error occurred while processing your request.",
    "status": 500,
    "detail": "Boom!",
    "traceId": "00-dc1c0c758701e74a8f925e9babe78347-a59e9e37da39d847-00"
}
```
However, I have a two additional questions:

1. How can the log scopes `ConnectionId:0HM61TET1KEKT => RequestPath:/api/my-controller/foo RequestId:0HM61TET1KEKT:00000003 => MyProject.MyController.GetFoo (MyProject)` be configured?
I assume that `LoggerFactoryOptions.ActivityTrackingOptions` is only responsible for the outer scope ` SpanId:a59e9e37da39d847, TraceId:dc1c0c758701e74a8f925e9babe78347, ParentId:0000000000000000`.

2. It seems as if what [W3C](https://www.w3.org/TR/trace-context/#version-format) calls `parent-id` (compare JSON error repsonse) appears in the Activity log scope as `SpanId`, while `ParentId` is not set at all. Is this intentional, because the ParentId concept differs between the two?

**Comment by svdHero** [comment]
I just did some testing. For all beginners like myself: If the `traceparent` http request header is set, then the `ParentId` in the log scope shows the W3C `parent-id` from in-bound `traceparent` header and the `SpanId` in the log scope shows the updated `parent-id` for the next out-bound step/span. So this should correspond to the specification https://www.w3.org/TR/trace-context/#mutating-the-traceparent-field.
