### ISSUE TITLE
Please give example code for use in .NET 4.8.

### ISSUE THREAD

**Issue by glittle** [dotnet/AspNetCore.Docs#21302]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709a375-e1f3-a47a-5f91-6bed1782a594
* Version Independent ID: 53e91296-c75c-b446-1487-6710b024ad60
* Content: [Replace the ASP.NET machineKey in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/replacing-machinekey?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/compatibility/replacing-machinekey.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/compatibility/replacing-machinekey.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
ASP.NET Core doesn't support the .NET Framework 4.8

**Comment by glittle** [comment]
But the point of this page is explaining how it can be used in .net 4.5+
