### ISSUE TITLE
Tag <location> on trasnsform

### ISSUE THREAD

**Issue by diego81b** [dotnet/AspNetCore.Docs#21311]
[Enter feedback here]
If the tag `<location>` is present in transform, the transformation in web.config in output (publish folder in my case) is ignored

this doesn't work:
```
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <location>
    <system.webServer>
      <aspNetCore>
        <environmentVariables xdt:Transform="InsertIfMissing">
          <environmentVariable name="Configuration_Specific" 
                               value="Configuration_Specific_Value" 
                               xdt:Locator="Match(name)" 
                               xdt:Transform="InsertIfMissing" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
  </location>
</configuration>
```

this works
```
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
    <system.webServer>
      <aspNetCore>
        <environmentVariables xdt:Transform="InsertIfMissing">
          <environmentVariable name="Configuration_Specific" 
                               value="Configuration_Specific_Value" 
                               xdt:Locator="Match(name)" 
                               xdt:Transform="InsertIfMissing" />
        </environmentVariables>
      </aspNetCore>
    </system.webServer>
</configuration>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c703c55-7ece-6e0d-2518-50786599530a
* Version Independent ID: 7e68f62c-8c84-e7a5-2a74-201fc60b3036
* Content: [Transform web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/transform-webconfig.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/transform-webconfig.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@vijayrkn should I remove the ` <location>` element?

@diego81b  is that the only difference?

**Comment by vijayrkn** [comment]
@Rick-Anderson - It depends on whether the user has the location tag in the source web.config or not. The web.config that WebSDK generates always adds the location tag. The right fix here would be for the transform to work irrespective of whether the location tag is present or not.

**Comment by Rick-Anderson** [comment]
> The right fix here would be for the transform to work irrespective of whether the location tag is present or not.

@vijayrkn 
Can you move this issue to the right repo to fix that?

**Comment by diego81b** [comment]
> @vijayrkn should I remove the ` <location>` element?
> 
> @diego81b is that the only difference?

Yes for the moment
I'm wondering if in previous version of visual studio was working because the problem is happening on a project that was already deploied

**Comment by vijayrkn** [comment]
The fix here would be to fix the sample. Let me see if we can have a conditional transform.

**Comment by diego81b** [comment]
> The fix here would be to fix the sample. Let me see if we can have a conditional transform.

Another thing.
In previous version of visual studio the published web.config was working even if the source web.config was not in the project

**Comment by vijayrkn** [comment]
@diego81b - It should continue to work the same way. If you are seeing a different behavior, can you please share a sample project to help diagnose the issue?

**Comment by diego81b** [comment]
> @diego81b - It should continue to work the same way. If you are seeing a different behavior, can you please share a sample project to help diagnose the issue?

Sorry for bothering you,
I have done some tests on some old projects and I discover that tag location sometimes is in origin web.config sometimes not.

So if location tag is present in web.config should be present in trasformation and viceversa, am i right?

Thanks

**Comment by vijayrkn** [comment]
@diego81b - Yes, if you follow that pattern, then it should always work.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
