### ISSUE TITLE
Add documentation for Microsoft.AspNetCore.ConcurrencyLimiter

### ISSUE THREAD

**Issue by halter73** [dotnet/AspNetCore.Docs#21327]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
  - I didn't personally search for it, but searches related to concurrent request *limits*, request *throttling* and request *queues* would be relevant.
- Tell us what docs you found that didn't address your concern.
  - I couldn't find anything related to concurrent request limiting or request queuing

**Describe the new topic**

- Explain why this topic is needed.
  > Currently, the only queuing that occurs in ASP.NET Core applications is through use of the thread-pool queue, which queues completions of async operations (i.e. async/await) and other thread-pool work items. This can be difficult to manage and measure. For some applications, the introduction of a concurrent request limit can mitigate issues caused by problematic async patterns (like "sync-over-async" where blocking calls are done in async code paths). The "Right Thing" to do in most of these cases is to unravel these "sync-over-async" calls into a true async/await pattern, but sometimes that's infeasible or too costly. Limiting concurrent requests conserves these resources.
 
    https://github.com/dotnet/aspnetcore/issues/10702
- Suggest a location in the Table of Contents.
  - Its own page under the "Performance"
  - Maybe link to it from https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices

- Write an abstract. In one **short** paragraph, describe what this topic will cover.

  This document would describe the issues that can occur when too many requests are handled concurrently (particularly if it involves blocking calls). That there's no concurrent request limit by default (at least with Kestrel). And how Microsoft.AspNetCore.ConcurrencyLimiter enforces this limit by queuing requests when the limit is hit and/or rejecting the requests.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
  - Discuss the motivation which is mainly to avoid ThreadPool starvation and more generally to better handle situations where the server doesn't have enough resources to handle every request as it arrives.
  - Demonstrate basic usage
    - Link to  https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/
    - See https://github.com/dotnet/aspnetcore/blob/7c0c74b7a1f68bb762a4b83d7667c7fbcb85b2cd/src/Middleware/ConcurrencyLimiter/sample/Startup.cs
  - Discuss queuing requests vs rejecting requests
    - Smooth out spikes in by queuing requests
    - Get errors faster by rejecting request rather than queuing
  - Discuss queue vs stack policy
    - Queue is more fair
    - Stack reduces average latency

**Comment by Rick-Anderson** [comment]
@halter73  can you review this issue now that [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit) has published.

**Comment by AKruimink** [comment]
@Rick-Anderson That documentation talks about the currently in preview [Microsoft.AspNetCore.RateLimiting](https://www.nuget.org/packages/Microsoft.AspNetCore.RateLimiting/#usedby-body-tab) that works for net7. This ticked asked about [Microsoft.AspNetCore.ConcurrencyLimiter](https://www.nuget.org/packages/Microsoft.AspNetCore.ConcurrencyLimiter/) which is a different package with support going back all the way to net core 3.0 and up to net 8 preview, where is the documentation specific to that one?
