### ISSUE TITLE
A very important and detailed step that is not mentioned in the "Application Pool Identity" configuration

### ISSUE THREAD

**Issue by ToMakeSense** [dotnet/AspNetCore.Docs#21321]
In the step-5(Screenshot below), we need pay attention to the **Locations** selection, It should be the local server in the very top of the popup window, Directory in the the Entire Directory tree is selected by default, however.

> ![image](https://user-images.githubusercontent.com/6244148/105805304-ad4ed280-5fdc-11eb-87c7-cb47b563bae4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d172b69-845d-739a-742c-617b9eed04fe
* Version Independent ID: 79d553f1-9112-b61a-0ad0-dfbb11e5071a
* Content: [Advanced configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-5.0#application-pool-identity)
* Content Source: [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
closing due to advanced configuration
