### ISSUE TITLE
Update instructions to scaffold a controller in Visual Studio Code and Ubuntu 20.10

### ISSUE THREAD

**Issue by semiliranda** [dotnet/AspNetCore.Docs#21322]
I got this [problem](https://github.com/dotnet/Scaffolding/issues/559) with Ubuntu 20.10 and Visual Studio Code, using the code generator, as it was described on your page right in the beginning of [the chapter](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#update-the-posttodoitem-create-method) **Scaffold a controller**. Consider to add [this solution](https://github.com/dotnet/Scaffolding/issues/559#issuecomment-742905009) to the page, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@semiliranda  if that's the case, https://github.com/dotnet/Scaffolding/issues/559 should be reopened.

@deepchoudhery, should I add the following to the scaffolding instructions?

If you get the following scaffolding error:

`A file matching the name ApiControllerWithActions.cshtml was not found within any of the folders:`

Copy the *Template/ControllerGenerator* and *Template/ViewGenerator* to the project folder. For more information, see [this GitHub issue](https://github.com/dotnet/Scaffolding/issues/559#issuecomment-742905009)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
