### ISSUE TITLE
Please describe and detail the PMC commands alongside the CLI commands

### ISSUE THREAD

**Issue by JeromeAtchison** [dotnet/AspNetCore.Docs#21330]
[Enter feedback here]
It would be very helpful to show and explain the PMC commands along side the CLI commands.  Simply referencing the package needed (at the bottom of the article) to use the commands is not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [Tutorial Part 5, apply migrations to the Contoso University sample](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. This is an advanced tutorial so we don't duplicate PMC
