### ISSUE TITLE
"Host ASP.NET Core on Windows with IIS" Reading Time Appears To Be Incorrect

### ISSUE THREAD

**Issue by collinkruger** [dotnet/AspNetCore.Docs#21346]
Hi There!

This number appears to be a tad off 😁
![image](https://user-images.githubusercontent.com/23742214/106164212-5ae1f300-614f-11eb-85c0-15f57174cab0.png)

I'm not sure what it should be, otherwise I would have updated it myself 😊

Happy Thursday/Friday!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@collinkruger  thanks for pointing that out. The calculation doesn't take into account the version. 95% of the content is hidden by `::: moniker` in the current version. Take a look at the [previous version](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1) and 78 is consistent with other docs estimates.

@scottaddie @tdykstra  do you have permissions to use the **Transfer issue** button?
![image](https://user-images.githubusercontent.com/3605364/106190434-625bd780-61f5-11eb-8f68-0773a3f57057.png)

**Comment by collinkruger** [comment]
You're most welcome! Happy to help :)

**Comment by tdykstra** [comment]
@Rick-Anderson What repo would we transfer it to?

**Comment by Rick-Anderson** [comment]
https://github.com/MicrosoftDocs/feedback

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/MicrosoftDocs/feedback/issues/3429
