### ISSUE TITLE
Where is 'ConfigureService'

### ISSUE THREAD

**Issue by DRAirey1** [dotnet/AspNetCore.Docs#21351]
I'm using .NET 5.0, I tried this code:

       public static IHostBuilder CreateHostBuilder(string[] args) =>
                Host.CreateDefaultBuilder(args)
                    .UseWindowsService()
                    .ConfigureAppConfiguration((hostingContext, config) =>
                    {
                        config.AddJsonFile("custom_settings.json");
                    })
                    .ConfigureServices((hostContext, services) =>
                    {
                        services.AddHostedService<Worker>();
                    });

And there's no 'UseWindowsService' method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DRAirey1 ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.windowsservicelifetimehostbuilderextensions.usewindowsservice

Try adding a ...

```csharp
using Microsoft.Extensions.Hosting;
```

... to the namespaces at the top.

**Comment by DRAirey1** [comment]
Gosh.  I didn't think about adding a using statement.  Thanks so much.

It's not the namespace, you need to explicitly add the package 'Microsoft.Extensions.Hosting.WindowsServices'

**Comment by guardrex** [comment]
I thought u were good on that because that's covered ...

> The app requires a package reference for Microsoft.Extensions.Hosting.WindowsServices.

I think if the namespace isn't there the same thing happens, and the topic doesn't show it. However, that namespace should be there in an app generated from the template.

**Comment by DRAirey1** [comment]
You are correct.  I missed the line that told us to include the package.  Gomen nasai!
