### ISSUE TITLE
Link to CultureInfo.CurrentCulture is incorrect

### ISSUE THREAD

**Issue by davidsk** [dotnet/AspNetCore.Docs#21367]
The link to CultureInfo.CurrentCulture in the [SupportedCultures and SupportedUICultures](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#supportedcultures-and-supporteduicultures-1) section is incorrect, linking to StringComparer.CurrentCulture instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @davidsk ... I'll get that patched up right now.
