### ISSUE TITLE
Inconsistent casing of HTTP.sys

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#21360]
I've seen:

* Http.sys
* Http.Sys
* HTTP.sys
* HttpSys

I think the offical case is HTTP.sys - https://docs.microsoft.com/en-us/iis/get-started/introduction-to-iis/introduction-to-iis-architecture#hypertext-transfer-protocol-stack-httpsys

Should be consistent across docs.

**Comment by guardrex** [comment]
I made an effort a few years ago to fix this, and we were consistent at that time on `HTTP.sys`. This problem has slowly churned its way back into existence 😈. I'll fix it up again.
