### ISSUE TITLE
Small disconnect in Creating DB

### ISSUE THREAD

**Issue by LockpickingDev** [dotnet/AspNetCore.Docs#21376]
The tutorial makes it unclear on how the DB was created.  The DB name that contains the Movies table looks like it was autogenerated someway and there's no way of knowing if we are to set it up manually this way to work with the DB Context.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@LockpickingDev, thanks for taking the time to make the suggestion.  I agree, we need to make that more clear where we introduce SQL Server Express LocalDB.  LocalDB is installed with Visual Studio, so there is no extra step to install or set it up.  It is the connection string set to that triggers the necessary SQL Server infrastructure to be created and started, and that's it.

"ConnectionStrings": {
    "MvcMovieContext": "**Server=(localdb)**\\mssqllocaldb;Database=MvcMovieContext-c807572a-0609-4a2d-9f34-8fb041dafd69;Trusted_Connection=True;MultipleActiveResultSets=true"
  }
