### ISSUE TITLE
Add Rebus / Rebus.SignalR as a Third-party SignalR backplane provider

### ISSUE THREAD

**Issue by ryanbuening** [dotnet/AspNetCore.Docs#21386]
[Rebus](https://github.com/rebus-org/Rebus) has the ability to work as a [SignalR backplane](https://github.com/rebus-org/Rebus.SignalR). Could be added to the list of third-party backplane providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54bf3510-4a8a-468e-c9dd-84eb4514808b
* Version Independent ID: 9b4f1776-1851-5bd3-0cd9-fba69f23aadc
* Content: [ASP.NET Core SignalR production hosting and scaling](https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-5.0#third-party-signalr-backplane-providers)
* Content Source: [aspnetcore/signalr/scale.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/scale.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
Interesting consideration. Have you used it for that purpose and do you have any numbers or examples that would lead to a good doc on the topic?

**Comment by ryanbuening** [comment]
I personally use Rebus.SignalR as a backplane for SignalR in a .NET Core chat app. I followed the readme [here](https://github.com/rebus-org/Rebus.SignalR#rebussignalr). Not sure if @mookid8000 would have anything to add.

**Comment by Rick-Anderson** [comment]
@BrennanConroy @bradygaster if you agree, I'll add this today (or @ryanbuening  can add it and get commit credit).

**Comment by ryanbuening** [comment]
PR created [here](https://github.com/dotnet/AspNetCore.Docs/pull/21405).
