### ISSUE TITLE
[Blazor] Diagram and explanation on this page are wrong.

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#21385]
The diagram and the code explanation are misleading.

Here is how it works

The important bit is whether the method runs synchronously or asynchronously, not whether the method returns a task or not. Some examples:

This returns a task but runs synchronously, it will **only render once**.
```csharp
protected Task OnInitializedAsync()
{
    Console.WriteLine("Hello world!");
    return Task.CompletedTask;
}
```

This runs asynchronously because it invokes an asynchronous operation (the network request).
```csharp
protected async Task OnInitializedAsync()
{
    var result = await httpClient.GetStringAsync("somewhere-on-the-web");
}
```

Low level explanation:
The resulting task of this method will have IsCompleted == false;
* The component internally calls `StateHasChanged()` to trigger a render at this point no matter what.
* Then it does something like this.
  ```
  if(!onInitializedResultTask.IsCompleted)
  {
      onInitializedResultTask.ContinueWith(t => this.StateHasChanged());
  }
  ```
The diagram above should depict that clearly and the explanation text should explain what I mentioned above in more detail.

The current diagram and text make it seem that the render won't happen up until the task has completed, which is not the case, or whether the decision is based on the method returning a task or not.

In essence:
* OnInitialized -> No problem since this will always run and complete synchronously. (1 render)
* OnInitializedAsync -> Same as OnInitialized when the method runs synchronously. (1 render).
* OnInitializedAsync -> Two renders, the first one after the first time an async method `yields control` and another one after the method completes executing.
  * You can `await something` and still run synchronously if the task you are awaiting is already completed by the time it is awaited, for example if you are retrieving something from a cache and it is already available in memory.

Please update the docs and diagrams to reflect that.

The same thing happens with `OnParametersSetAsync`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
cc: @SteveSandersonMS @danroth27 @mkArtakMSFT 

The email chain where discussion took place included the link to the PR with the text at ...

https://github.com/dotnet/AspNetCore.Docs/pull/19543

... but you, @javiercn, were on vacation 🏖️, so I don't think you saw that. An additional email message was warranted and/or I should have mentioned to you, @SteveSandersonMS, that the text should be examined on the image revision PR later. I did call everyone for review of the PR with the text, but I didn't follow-up. My bad on that.

The diagrams were based on the original versions that you, @SteveSandersonMS, provided. Initial version of the first one ...

![image1](https://user-images.githubusercontent.com/1622880/106470672-65113380-6466-11eb-92a7-fd8f631e7096.png)

... with some minor updates approved at https://github.com/dotnet/AspNetCore.Docs/pull/20430#issuecomment-725439983. Given your remark, @SteveSandersonMS, I should've mentioned the text. I don't think that you looked at it.

> Please update the docs and diagrams to reflect that.

I'm not sure how to diagram it. @SteveSandersonMS, do you want to produce the diagram? ... and possibly text? If only diagram, I can try to update the text based on @javiercn remarks here :point_up: once I get the visual from your updated image.

I'll address this *ASAP* 🏃 as soon as I know how we'll proceed.

**Comment by javiercn** [comment]
@guardrex The way I explain this to people is with a sample:

```
@if(data == null)
{
    <p>Loading...</p>
} 
else
{
    <!-- Display the data -->
}

@code
{
    // How the data was constructed
    private Data _data = new();
}
protected async Task OnInitializedAsync()
{
   // All this happens SYNCHRONOUSLY
    _data = null;
   
   // The Task.Delay WILL EXECUTE ASYNCHRONOUSLY
   // A render happens before Task.Delay finishes
   await Task.Delay(5000);
  // A render has happened at this point
   _data = new Data(){ ... }
  // Another render will be triggered automatically after the invocation completes
}

This can be done with "FetchData"

**Comment by guardrex** [comment]
At least conceptually ... i.e., not necessarily for the diagram using the following exact phrasing ... where the diagram says "Returned task?" is the behavior closer to ...

> Yields control to an asynchronous call where the awaited task hasn't already completed?

... with matching text to that effect?

**Comment by javiercn** [comment]
We'll have to workout the details on how to phrase things, I'm not sure how the best way to do this is. I believe we will need to put in context how Tasks and async programming work in an introductory paragraph or clarification note and point to more documentation details.

The main thing is to make sure folks understand how tasks work and how that affects the Blazor rendering process. It might be better of if we try to explain this with a couple of cases and include screenshots showing the different stages of each case.

(When there is actual asynchronous work vs when there isn't)

**Comment by guardrex** [comment]
Do you want me to temporarily withhold the diagrams and the remarks on them in the topic until this gets sorted out? At least the coverage won't be wrong if I comment out the current text for now. That would give us some breathing room if you don't think this can be resolved today.

**Comment by javiercn** [comment]
@guardrex we don't have to solve it right away.

Maybe some folks on @dotnet/aspnet-blazor-eng can chime in here to help.

**Comment by SteveSandersonMS** [comment]
The diagram necessarily has to simplify the rules. If it didn't, it would be the framework source code, not a diagram :)

If the distinction between "completed tasks" and "incomplete tasks" is causing readers to get the wrong idea, then yes let's definitely try to clarify that detail. For example we could change the labels "*Returned task?*" to "*Returned incomplete task?*".

Javier's code sample is good for explaining the flow too. Some readers may prefer to see it expressed as code, and some may prefer a box-and-lines diagram.

**Comment by guardrex** [comment]
Here's a **_start_** for text updates with updated images for further discussion.

I understand that this is **_NOT_** correct. I just want to get the ball rolling on what to do. **_Feel free to edit this comment directly to make the needed changes._**

Component lifecycle events:

1. If the component is rendering for the first time on a request:
   * Create the component's instance.
   * Perform property injection. Run `SetParametersAsync`.
   * Call `OnInitialized{Async}`. 
   * Call `OnParametersSet{Async}`.
   * For asynchronous method calls that don't finish by the time `OnInitializedAsync`/`OnParametersSetAsync` are finished, the component:
     * Internally calls `StateHasChanged` to trigger a render immediately.
     * Makes one or more `StateHasChanged` calls to trigger a render for each asynchronous method call completion.
   * For synchronous method execution, the component calls `StateHasChanged` to trigger a render.

![lifecycle1](https://user-images.githubusercontent.com/1622880/106657535-c538d000-6561-11eb-8d0d-58c87a04966a.png)

Document Object Model (DOM) event processing:

1. The event handler is run.
1. The event handler executes.
   * For asynchronous method calls within an asynchronous event handler that don't finish by the time the event handler is finished, the component:
     * Internally calls `StateHasChanged` to trigger a render immediately.
     * Makes one or more `StateHasChanged` calls to trigger a render for each asynchronous method call completion.
   * For synchronous method execution, the component calls `StateHasChanged` to trigger a render.

![lifecycle2](https://user-images.githubusercontent.com/1622880/106657569-ccf87480-6561-11eb-98df-574eca189da8.png)

The `Render` lifecycle:

1. Avoid further rendering operations on the component:
   * After the first render.
   * When `ShouldRender` is `false`.
1. Build the render tree diff (difference) and render the component.
1. Await the DOM to update.
1. Call `OnAfterRender{Async}`.

![lifecycle3](https://user-images.githubusercontent.com/1622880/106657582-d2ee5580-6561-11eb-9b7a-9a00ff1e2588.png)

**Comment by javiercn** [comment]
The part I take issue with is the fact that it looks like the render only happens after the task has been awaited/completed.

![image](https://user-images.githubusercontent.com/6995051/106660852-5fdee200-6555-11eb-84c7-36bd9fd6eb05.png)

**Comment by SteveSandersonMS** [comment]
@javiercn That’s a good clarification

**Comment by guardrex** [comment]
Ok ... I'll update again tomorrow and post back with new images.

Does this apply to the DOM event handler diagram, too?

**Comment by javiercn** [comment]
Yep, and SetParametersAsync too

**Comment by javiercn** [comment]
sorry, I meant OnParametersSetAsync

**Comment by guardrex** [comment]
ok ... I'll ping back tomorrow.

**Comment by guardrex** [comment]
@javiercn ... I wasn't quite sure about integrating the "Renders" and `OnParametersSetAsync` given that your diagram is a subset of flow if our goal is to keep all of the methods in the same image.

I just did the first one on this pass. I'll do the other one when we get this one worked out.

Is this how it goes?

![lifecycle1](https://user-images.githubusercontent.com/1622880/106775495-c96bf880-6608-11eb-9319-6be9bea570ed.png)

**Comment by guardrex** [comment]
Indeed, I can't grok your diagram in the context of `OnParametersSetAsync` and all of the renders with flows **_in the same diagram_**. Can you produce the full stick figure diagram with both methods' flows indicated? It's how they're connected to each other that's throwing me off. I have a few guesses on how it might compose, but it's not a good use of 💰 for me to guess over and over ... *unless DR says it is*. :smile:

**Comment by guardrex** [comment]
It looks like the leg coming off of `OnInitializedAsync` would be ...

**Is task complete?** > **NO** > **Render** > **await Task** > **Render** (END)
**Is task complete?** > **YES** > Rejoin flow line out of `OnInitializedAsync` out to `OnParametersSetAsync`

**Comment by Ariansh** [comment]
may I suggest this?
![image](https://user-images.githubusercontent.com/3452323/107384118-e91e8780-6b06-11eb-9f27-247063dc7a57.png)
and please mention if the object which caries data is not bind to any element, the component should be rendered manually. so you might do many tasks at the same time and refresh when awaited all

**Comment by guardrex** [comment]
Your flow doesn't show how to get to `OnParametersSet{Async}`. I don't think it's all that different really. The timeline in mine is encapsulated in the flow and `await`s. Idk if it adds value to use the vertical layout as the concept of time. 🤔

>  if the object which caries data is not bind to any element, the component should be rendered manually

Possibly something for either or both ... or perhaps already covered by the second one ...

* `StateHasChanged` section at https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle#state-changes. 
* *An asynchronous handler involves multiple asynchronous phases* in https://docs.microsoft.com/aspnet/core/blazor/components/rendering#an-asynchronous-handler-involves-multiple-asynchronous-phases

**Comment by Ariansh** [comment]
I didn't mean to show the entire process here. actually not even all events. I tried to use it to Describe the situation to my team two months ago as simply as I could. of course we need it to be more detailed in the documentation. but it would be easier to understand if you simulated time somehow here. it was that simple for my team, surly you could do better for docs.

**Comment by guardrex** [comment]
Fair enough. I'll wait for the product unit engineers to react before doing anything else. Thanks for remarking. It's great to have your experience involved in explaining it.

**Comment by guardrex** [comment]
@SteveSandersonMS @javiercn ... I'm blocked until we either ...

* Resolve the renders in your, @SteveSandersonMS, integrated diagram.
* Add the path and associated logic for `OnParametersSetAsync` to your, @javiercn, diagram.

The following would need to integrate `OnParametersSetAsync` ...

![image](https://user-images.githubusercontent.com/6995051/106660852-5fdee200-6555-11eb-84c7-36bd9fd6eb05.png)

Alternatively using the existing diagram, it looks like the paths coming off of `OnInitializedAsync` would be ...

* **Is task complete?** > **NO** > **Render** > **await Task** > **Render** (END) ... If so, it looks like we add the **Render** before awaiting a task of `OnParametersSetAsync`, too, to match.
* **Is task complete?** > **YES** > Rejoin flow line out of `OnInitializedAsync` out to `OnParametersSetAsync`
  * ,,, but is there a render there? If so, does the **YES** line intersect before (as shown below) or after it?
  * If after **YES**, is it still inside the **First render only** box?

![lifecycle1_1](https://user-images.githubusercontent.com/1622880/106791554-b06c4300-661a-11eb-9651-33f279726a38.png)

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/112305520-0729ec80-8c5c-11eb-88f7-03e9a7af47c0.png)

The OnInitialized render gets folded into the OnParametersSet render. At most there are 3 renders that happens if you override both OnInitAsync, OnParametersSetAsync and you do asynchronous work on both:
* First render for all the synchronous work.
* Second render after OnInitAsync completes.
* Third render after OnParametersSetAsync completes.
