### ISSUE TITLE
Missing Using line on the ToDo.razor page.

### ISSUE THREAD

**Issue by XzipbitA** [dotnet/AspNetCore.Docs#21381]
[Enter feedback here]
The Second line in the ToDo.razor is missing the following line:

@using Mutual_Blzr.Data

Else you end up getting errors on the 'TodoItem' not being available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @XzipbitA ... The instructions are to make the content of the file **_exactly_** using what's shown in the topic's code block (no namespace) ...

> Use the following C# code for the TodoItem class.

The instructions focus on the use of the CLI and a text editor, not VS. Even if using VS, one would use the **Copy** button and replace the content of an added class, which would remove the namespace that VS generates.

What I'll do here is mention that no namespace is used if using VS or VS4Mac.
