### ISSUE TITLE
API will not show up in Firefox

### ISSUE THREAD

**Issue by mu88** [dotnet/AspNetCore.Docs#21382]
I've been following your approach. In Google Chrome, the Swagger page can be displayed. However, in Firefox it will show up with an `SEC_ERROR_INADEQUATE_KEY_USAGE` error. I could get around this error my importing the created certificate into Firefox as my own certificate ([see here](https://dimitri.janczak.net/2019/11/25/firefox-displays-ssl-error-sec_error_inadequate_key_usage-when-using-self-signed-certificate/)).

Maybe it is worth mentioning?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e087007-7838-e0f9-d713-22182a5d9704
* Version Independent ID: 2f32c7c3-8667-0e88-495b-c0c888572964
* Content: [Hosting ASP.NET Core Images with Docker over HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/docker-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/docker-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We have instructions in many lower level [tutorials](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-5.0&terms=SEC_ERROR_INADEQUATE_KEY_USAGE&category=Documentation).
