### ISSUE TITLE
Response.Headers.Append should be replaced with Headers.Add in documentation

### ISSUE THREAD

**Issue by RedFeet** [dotnet/AspNetCore.Docs#21387]
Could you please update the sample code of this paragraph to match the syntax of Net 5?
[aspnetcore-5.0#set-http-response-headers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#set-http-response-headers)

The current example code is:
`Response.Headers.Append`
This should be replaced with:
`Response.Headers.Add`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Append ](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2?view=net-5.0#extension-methods) is there. per the code snippet, it's an extension and needs `using Microsoft.AspNetCore.Http;`

**Comment by RedFeet** [comment]
OK. Then I hope they both do the same.
Thanks.
