### ISSUE TITLE
SignalR ChatHub Sample works in IIS Express but Not IIS - failing with Negotiate 404 error.

### ISSUE THREAD

**Issue by Geoff-Holder** [dotnet/AspNetCore.Docs#21407]
# The SignalR ChatHub sample works in _IIS Express_ but Not _IIS_ where the Negotiate fails with a 404 error.
Note - every Chathub sample that I have found suffers from this same error.

**Failed to load resource: the server responded with a status of 404 (Not Found)
chatHub/negotiate:1** 

I tried 100 dead ends,
Including the URL into the Hub Connection, it then satisfies both versions of IIS. Else both use the root path, which is incorrect when the URL is actually http://localhost/SignalRChat.

**chat.js** 
const url = this.document.URL;  // allow both IIS & IIS Express.
const connection = new signalR.HubConnectionBuilder()
    **.withUrl(url + "/chatHub")**
    .configureLogging(signalR.LogLevel.Information)
    .build();

I am brand new to Web Dev, so I am sire that there must be better ways to ensure that the correct path is passed down the line, More experienced Web Devs can address that. 
But this at least gets the SignalR ChatHub sample running 'out of the box'.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
