### ISSUE TITLE
Item size

### ISSUE THREAD

**Issue by bsHobbit** [dotnet/AspNetCore.Docs#21414]
Does Item size define the width or height?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor-Komponentenvirtualisierung](https://docs.microsoft.com/de-de/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bsHobbit ... **_Height_** ...

https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Components/Web/src/Virtualization/Virtualize.cs#L389

I'll make the topic say that. Thanks for asking.

Leave this issue open. It will close when the PR merges later.
