### ISSUE TITLE
 System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by throne-developer** [dotnet/AspNetCore.Docs#21419]
[在此处输入反馈]
macos下使用visual studio for mac 8.8.6 版本时，该教程触发异常，定位在
endpoints.MapHub<ChatHub>("/chathub");

通过安装 System.Text.Encodings.Web 5.0.0 包后解决该异常

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 08de9daf-79aa-ee76-431e-f2432f8d691e
* Version Independent ID: 1a1ee728-1741-c82a-75e1-06159709935b
* Content: [将 ASP.NET Core SignalR 与承载的 Blazor WebAssembly 应用一起使用](https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-5.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/signalr-blazor-webassembly.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/tutorials/signalr-blazor-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This one was addressed ...

https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio#add-the-systemtextencodingsweb-package
