### ISSUE TITLE
Code Samples seems to be wrong record 

### ISSUE THREAD

**Issue by hannespreishuber** [dotnet/AspNetCore.Docs#21415]
public IActionResult Index() => View();

is missing a new person

Taghelper without Model.
@model Person

Name: <input asp-for="Model.Name" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6a85af-14dd-7102-e2f9-d3850e0e0658
* Version Independent ID: d20b1af2-b6a4-5428-3e79-b2c8f8881446
* Content: [What's new in ASP.NET Core 5.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-5.0?view=aspnetcore-5.0#aspnet-core-mvc-and-razor-improvements)
* Content Source: [aspnetcore/release-notes/aspnetcore-5.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/release-notes/aspnetcore-5.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
* 
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6c6a85af-14dd-7102-e2f9-d3850e0e0658
* Version Independent ID: d20b1af2-b6a4-5428-3e79-b2c8f8881446
* Content: [Neuerungen in ASP.NET Core 5.0](https://docs.microsoft.com/de-de/aspnet/core/release-notes/aspnetcore-5.0?view=aspnetcore-5.0#aspnet-core-mvc-and-razor-improvements)
* Content Source: [aspnetcore/release-notes/aspnetcore-5.0.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/release-notes/aspnetcore-5.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
