### ISSUE TITLE
Code sample is wrong...

### ISSUE THREAD

**Issue by enetstudio** [dotnet/AspNetCore.Docs#21416]
The following code is wrong...specifically the if statement which is always evaluated to true:
 
     public override async Task SetParametersAsync(ParameterView parameters)
     {
        if (parameters.TryGetValue<string>(nameof(Param), out var value))
        {
            message = $"The value of 'Param' is {value}.";
        }
        else 
        {
            message = "The value of 'Param' is null.";
        }

        await base.SetParametersAsync(parameters);
     }

It should be something like this:

       if (parameters.TryGetValue<string>(nameof(Param), out var value))
        {
            if (value == null)
            {
                message = "The value of 'Param' is null.";
            }
            else
            {
                message = $"The value of 'Param' is {value}.";
            }
         }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Blazor lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @enetstudio .... I'll take a look within ... mmmmm 🤔 ..... *soon* lol .... within 24 hours I hope. We just put this in a few days ago, and Safia did take a look.

https://github.com/dotnet/AspNetCore.Docs/pull/21281

I'll get back to you as soon as I can.

**Comment by captainsafia** [comment]
@guardrex Ah, no. This one is my fault. The semantics of the `TryGetValue` on the `ParameterView` are that it returns false if the _parameter_ wasn't found in the entry, not the parameter's value.

The original code sample you had (and the one above) are correct.
