### ISSUE TITLE
Extensión de Archivo incorrecto

### ISSUE THREAD

**Issue by supervas** [dotnet/AspNetCore.Docs#21418]
Google translate to English
In the section " https://docs.microsoft.com/es-es/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#update-net-core-sdk-version -in-globaljson "text appears" If the solution relies on a global.jsen file to target a specific .net Core SDK version, update its version property to version 3.0 installed on the machine: " and the extension for the "global" file should be "json".

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrar de ASP.NET Core 2,2 a 3,0](https://docs.microsoft.com/es-es/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 61014](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61014)

**Comment by guardrex** [comment]
I don't think that will work ... I think it's literal.

What I've been doing is code-fencing **_all_** file names. That'll lick it ... eventually when I get done with these UE passes.

**Comment by Rick-Anderson** [comment]
On many (?most) file names, I think they look better `code fenced` than *italic* and with less ambiguity.

**Comment by guardrex** [comment]
Yes, I agree and takes care of this loc problem.

I put my iMac into Spanish, looked at the VS UI, and then created a Blazor project. The VS UI was variable on translations ... a real mix of Spanish and English. The project came out 100% English. Referring to something like "Program.cs" as "Programa.cs" in a topic isn't good imo.

**Comment by Rick-Anderson** [comment]
@guardrex  let's just add global.json and all the other JSON's to the new file approach.

**Comment by Rick-Anderson** [comment]
@guardrex do we still need to add `global.json` ? That sounds like a bug in the translator.

**Comment by guardrex** [comment]
I code-fence all filenames. You can add it tho ... at least it only needs to go in one place now ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/docfx.json#L69

... still tho ... I'd find-'n-replace on the whole repo. That line could get ***full*** of files over time if find-'n-replace isn't used for files.
