### ISSUE TITLE
Recommend step stops including access tokens 

### ISSUE THREAD

**Issue by sterneric** [dotnet/AspNetCore.Docs#21428]
[EDIT by guardrex to add code blocks and inline code style]

Step 6 In Program.Main (Program.cs):

```diff
-builder.Services.AddTransient(sp => new HttpClient 
-    { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
+builder.Services.AddScoped(sp => new HttpClient 
+    { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
```

The `AddTransient` is not present in the visual studio templated webassembly application.  Not really knowing what to do (very new to blazor) I added the line to my program.cs 

Adding the line after this one

```csharp
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("Test.ServerAPI"));
```

So the final code looks like this

```csharp
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("Test.ServerAPI"));
builder.Services.AddScoped(sp => new HttpClient{ BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
```

allows the code to run but stops tokens being passed on `GetFromJsonAsync` webapi calls.  

Good learning experience for me but one I'd sooner have lived without.  

Changing the wording to recommend only adding the problem line if the `AddTransient` line exists might have helped me.

Steps to reproduce
- create a new web assembly project with Individual; user accounts and HTTPS.  
- follow the steps in the article but guess incorrectly on how to handle the section mentioned above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b031caa0-c62b-37da-46c3-59043256cac2
* Version Independent ID: bdf98c9a-96f6-79fd-a650-5c0385d1a62b
* Content: [Migrate from ASP.NET Core 3.1 to 5.0](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-50.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/31-to-50.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @sterneric ... I'll take a look at this on Thursday.
