### ISSUE TITLE
Getting type cannot be instantiated error for abstract base class

### ISSUE THREAD

**Issue by IronSean** [dotnet/AspNetCore.Docs#21430]
When I attempt to do something similar to what this guide shows using .Net 5, I set up an abstract base class and several concrete child classes then adding a DbSet and a modelBuilder mapping as shown,

`public DbSet<MyAbstractType> myType {get;set;};`
`modelBuilder.Entity<MyAbstractType>().ToTable("MyTable");`

but I get the following error:

The corresponding CLR type for entity type 'MyAbstractType' cannot be instantiated, and there is no derived entity type in the model that corresponds to a concrete CLR type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you reproduce with the exact steps in the tutorial?

**Comment by Rick-Anderson** [comment]
Container issue for EF/MVC #17465
