### ISSUE TITLE
Clarification on Hosting Module backward compat

### ISSUE THREAD

**Issue by dazinator** [dotnet/AspNetCore.Docs#21446]
As per the discussion here: https://docs.microsoft.com/en-us/answers/questions/176303/net-core-31-apps-with-the-net-5-hosting-bundle-are.html

It would be good to clarify somewhere whether the `ASP.NET Core Module` that get's installed via the Hosting Bundle, will still run older asp.net core websites. There can be some concern around this when you already have an IIS server hosting asp.net core 3.1 websites and you wish to test out deploying an asp.net core 5.0 website along side - the runtimes install side by side, but the `ASP.NET Core Module` appears to be "shared"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik  please review

**Comment by dazinator** [comment]
Tagged as "Needs more info" - is there anything else I can provide or clarify?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
