### ISSUE TITLE
WebAppParts sample is not working.

### ISSUE THREAD

**Issue by babula38** [dotnet/AspNetCore.Docs#21449]
Error:- Application part sample not working on clicking "MyShared View"

Steps to reproduce:- Just clone the project from "https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/advanced/app-parts/3.0sample1/WebAppParts" then try to run it. once the page appears click on "MyShared View"

Expected:- It show the pages from the shared project.

Actual:- it is showing the error page "Could not found the views"

Dotnet core version:-  Version: 5.0.2

**Comment by guardrex** [comment]
Hello @babula38 ... Can you re-open this from the bottom of the topic where this sample is linked. When you do so, it will add metadata, and the author of the topic gets an automatic ping.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by babula38** [comment]
Done
