### ISSUE TITLE
hit error trying to work through example

### ISSUE THREAD

**Issue by jrkcoder** [dotnet/AspNetCore.Docs#21456]
hit error trying to work through example:
Just hit this using ASP.NET Core 5.
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
Tool 'dotnet-aspnet-codegenerator' (version '5.0.1') was successfully installed.
PM> aspnet-codegenerator razorpage -m Contact -udl -dc ApplicationDbContext -outDir Pages\Contacts --referenceScriptLibraries
aspnet-codegenerator : The term 'aspnet-codegenerator' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1

aspnet-codegenerator razorpage -m Contact -udl -dc ApplicationDbConte ...
  + CategoryInfo          : ObjectNotFound: (aspnet-codegenerator:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

PM>

--- per directions on page, go look at GitHub bug -- it does not seem to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#create-the-starter-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
