### ISSUE TITLE
the view / movie with the create / delete ... methods is not regenerated, you have to restart the command from part 4 and add -f 

### ISSUE THREAD

**Issue by aminGandouz** [dotnet/AspNetCore.Docs#21450]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Part 8, add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
dup of #21452
