### ISSUE TITLE
Large Cookie Size Issue Due to IDataSerializer not using gzip compression : Documentation needed

### ISSUE THREAD

**Issue by vaibhavramdasi** [dotnet/AspNetCore.Docs#21455]
I have a .NET 4.5.2 web app that uses ASP.NET Identity for authentication. There is large data in one of the claims (Serialized json) which went un-noticed until we tried to share the cookie with asp.net core application.

Basically, the IDataSerializer<AuthenticationTicket> implementation used by Katana has gzip compression while writing cookie. Same is absent in Interop serializer and asp.net core serializer. This results in large cookie which mandates chunking.

I would like to know reason behind this change(no compression in asp.net core vs gzip in katana/owin). Also if we could highlight this change in the documentation, it would help developers to comprehend drastic change in cookie size after enabling AspNetTicketDataFormat

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core 2.2
* [ ] .NET Framework 4.5.2

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
@vaibhavramdasi  2.2 is out of support. Have you tested this on 5.0?

@Tratcher  would this be useful in the migration docs?

**Comment by Tratcher** [comment]
@blowdart for comment.

**Comment by blowdart** [comment]
We're back at "don't compress data that is encrypted and can include user-controlled information"

The change was made in light of the crime and breach attacks, and the potential for the principle behind them to apply elsewhere. It was too breaking to backport. We can note that cookies are no longer compressed, and that developers should minimize the amount of claims included to just those necessary for their needs.

**Comment by Rick-Anderson** [comment]
@vaibhavramdasi  can you recommend a doc this should be added to? How about the following?

* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
* https://docs.microsoft.com/en-us/aspnet/core/migration/identity
* https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/
* https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity

That seems like overkill. I can create an include file with the information and add it to multiple docs.

**Comment by vaibhavramdasi** [comment]
> @vaibhavramdasi can you recommend a doc this should be added to? How about the following?
> 
> * https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
> * https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state#cookies
> * https://docs.microsoft.com/en-us/aspnet/core/migration/identity
> * https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/
> * https://docs.microsoft.com/en-us/aspnet/core/security/authentication/
> * https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme
> * https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
> * https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity
> 
> That seems like overkill. I can create an include file with the information and add it to multiple docs.

I think this should be added to all ASP.NET Core Cookie authentication related docs. I don't see one doc in above list from where I came to know about this change.

https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2#share-authentication-cookies-with-aspnet-core-identity

**Comment by Tratcher** [comment]
The cookie sharing doc does seem the most appropriate place to document a behavioral difference vs the prior platform.

**Comment by Rick-Anderson** [comment]
> The cookie sharing doc does seem the most appropriate place to document a behavioral difference vs the prior platform.

I added it to the cookie sharing doc. But I'm not documenting new behavior. I'm [documenting the behavior and good advice](https://github.com/dotnet/AspNetCore.Docs/blob/538544ccd53a3930ad53ff6c83b74990b7c361a1/aspnetcore/includes/cookies-not-compressed.md)

I can remove some of the **[files ](https://github.com/dotnet/AspNetCore.Docs/pull/21571/files)** in #21571, but the information doesn't hurt.
