### ISSUE TITLE
No login options in application

### ISSUE THREAD

**Issue by aggaio** [dotnet/AspNetCore.Docs#21458]
I followed all the steps from the documentation to add Google authentication to .NET Core API sample project (Weather Service). 
I tried the below step.

**Run the app and click Log in. An option to sign in with Google appears.**

I ran the app but no log in options to click. It directly shows the JSON string. Do I need to make changes to the controller?

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
