### ISSUE TITLE
brotli compression results in TypeError

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/AspNetCore.Docs#21465]
For the brotli compression code in blazor wasm, I'm experiencing an issue reported here: https://github.com/google/brotli/issues/881

This seems related to https://github.com/dotnet/AspNetCore.Docs/issues/19979, but I'm not sure it's the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stefanloerwald ... Did you try the uncompressed script, `decode.min.js`?

**Comment by stefanloerwald** [comment]
I'll try just after lunch. Related question: is there a snippet for gzip-compressed dll fetching?

**Comment by stefanloerwald** [comment]
Managed to squeeze it in before lunch. It seems to work with the unminified JS.

**Comment by guardrex** [comment]
> is there a snippet for gzip-compressed dll fetching?

A Gzip decoder recommendation didn't come over when we put this up. Let's ping @pranavkm to ask about that.

> It seems to work with the unminified JS.

Thanks ... I'll restore the NOTE and update the guidance that we had there to use that script until they fix your issue.

**Comment by pranavkm** [comment]
> is there a snippet for gzip-compressed dll fetching?

My hope was that if you were going thru the trouble of manually decompression, you might as well use the brotli that compresses better.

**Comment by guardrex** [comment]
If we get more requests inquiring about Gzip, we could react later with something to the effect ...

> Other compression formats, such as Gzip, can be used with a suitable third-party decompression library. However, we recommend the use of the Brotli format to maximize the benefit of compression to an app.

... unless you want me to add that now, @pranavkm.

**Comment by pranavkm** [comment]
> ... unless you want me to add that now

We can wait. @stefanloerwald if you feel strongly about this, we'd be happy to accept a contribution.

**Comment by guardrex** [comment]
If so @stefanloerwald, please mark your PR "Addresses" and not "Fixes" ... I'll need this issue to remain open to work it later for whenever they fix your Brotli repo issue.

**Comment by stefanloerwald** [comment]
I do _not_ feel strongly about this. Of course I also prefer better compression, so I ended up simply using the unminified brotli for now.

Speaking about blazor itself, not the docs: Is this a common enough scenario that it would maybe make sense to put a working minified brotli JS file into the `_framework` portion of blazor? The absolute perfect thing in my eyes would be something like `<script src="_framework/blazor.wasm.js" use-brotli></script>`.

**Comment by stefanloerwald** [comment]
I've done some more analysis into this issue. Turns out there is an obvious error in the minified version, but it's not affecting the decoding itself. Fixing the error results in a far smaller minified file, which I'd recommend using.

**Comment by stefanloerwald** [comment]
@guardrex: Would it make sense to replace the link to the brotli repo with direct download of working JS files?

@pranavkm: Would the feature I suggested [two comments above](https://github.com/dotnet/AspNetCore.Docs/issues/21465#issuecomment-775275659) be considered for a future version of blazor? If so, should I open a new issue on dotnet/aspnetcore?

**Comment by pranavkm** [comment]
@stefanloerwald that has come up in our offline conversation, but I don't think we've had user requests for it so I would start with an issue on https://github.com/dotnet/aspnetcore. 

One of my issues is that we would likely not turn it on by default since having the browser handle decompression is preferable to doing this in JS. At the point that you have to perform a gesture to enable it, copying this snippet seems to be about as much work.

**Comment by guardrex** [comment]
They're terrible at even communicating with dev on the issues, much less actually maintaining their code. I investigated other options seeking to get away from Google, and I found a bunch of other barely or not maintained repos.

I hope we **_don't_** host a minified+fixed script here. If we have to host it, then we have to maintain and support it.

**Comment by pranavkm** [comment]
@guardrex can we update the docs to link to a point in time commit that we know works? We could add a comment that says why we're doing this with an advisory to update to the latest at one's own peril.

**Comment by stefanloerwald** [comment]
Very much understandable points from both @guardrex and @pranavkm.

Regarding the docs: I think technically the notice can be removed, as the script works. It just displays an unrelated and entirely avoidable error message, which is misleading, but not critical. Maybe replace it by a warning that it does that at the moment?

**Comment by guardrex** [comment]
My understanding is that they've applied bug fixes since the last known working minified version. I don't know about security patches, but I can look and see.

We're linking to the current working non-minified version. Can't the user just minify the latest version on their own? Can we just link the current NOTE over to ...

https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0#configure-bundling-and-minification

**Comment by guardrex** [comment]
WRT ...

> technically the notice can be removed ... as the script works

... I'll need to look tomorrow. I'm mostly OOF the rest of the day. I'll take a closer look tomorrow.

**Comment by stefanloerwald** [comment]
I have to retract my statement from yesterday evening that the code is working despite the error. Turns out I was looking at a deployment that actually didn't use BrotliDecode at all.

Minifying the code correctly solves the issue. That means, we should just leave the notice as-is for the time being. I'll write another comment here as soon as the issue is resolved in the google/brotli repo.

**Comment by guardrex** [comment]
I've cross-linked the BuildBundlerMinifier coverage in the NOTE.

**Comment by guardrex** [comment]
@stefanloerwald, it's been three weeks since [your report to them (google/brotli #881)](https://github.com/google/brotli/issues/881). I'm trying to reach someone offline in Google OSS management. I'll update if/when I have any luck getting in touch with someone. 🤞🍀
