### ISSUE TITLE
GRPC Cancellation doc - what about awaiting the task

### ISSUE THREAD

**Issue by BadgerTheAdger** [dotnet/AspNetCore.Docs#21464]
Hey guys,

I see this doc about GRPC streaming call cancellations: https://docs.microsoft.com/en-us/aspnet/core/grpc/deadlines-cancellation?view=aspnetcore-5.0#cancellation

and am wondering if I should await the Task after calling dispose() / token cancellation - to perhaps get some errors (so they are not eaten)

This is how I do this: 

```
StreamingCall.Dispose();
CancellationTokenSource.Cancel();

try
{
    StreamingTask.GetAwaiter().GetResult();
}
catch (RpcException e) when (e.StatusCode == StatusCode.Cancelled)
{
    Logger.Info("Stopped GRPC websocket {0}", typeof(T).ToString());
}
```

CancellationTokenSource - it's the source of a token I pass to MoveNext in another task: (and that's the Task I'm waiting for to end)

```
var cancellationTokenSource = new CancellationTokenSource();
var socket = new GRPCWebSocket<T>(streamingCall, cancellationTokenSource);

var streamTask = Task.Run(async () =>
{
    while (await streamingCall.ResponseStream.MoveNext(cancellationTokenSource.Token))
    {
        var update = streamingCall.ResponseStream.Current;
        await onUpdateCallback(update);
    }
    socket.OnStreamClosed();
});

socket.StreamingTask = streamTask;

return socket;
```

See I'm calling MoveNext(CancellationToken) there.

And I want this streamTask to finish also - but when I call GetAwaiter().GetResult() it's blocking the thread I think forever.. Hence I'm worried about the state of the task i.e why it's not finished if I called Dispose() and Cancel()

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
