### ISSUE TITLE
Add-Migration InitialCreate creates error "Unable to create an object of type 'RazorPagesMovieContext'."

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#21462]
When entering the command "Add-Migration InitialCreate" an error is displayed "Unable to create an object of type 'RazorPagesMovieContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728" and no migration file is created. Using .net 5.0 Core instructions. 

VS Version Info:
Microsoft Visual Studio Enterprise 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by Smith-Rick** [comment]
I was able to identify the issue. We use this tutorial to help our students get introduced to Razor pages, and I do not remember this issue appearing in the past several versions we have used. However the additional details are below.

The problem occurs until you modify the startup.cs as later indicated. See the image below. No step was missed.
[cid:image001.png@01D6FCCE.DC5440E0]

Once you modify the startup.cs file with the code, the message then changes to the one warned about in the tutorial. See image below.
[cid:image002.png@01D6FCCE.DC5440E0]


Rick Smith
Email: rictersmith@hotmail.com<mailto:rictersmith@hotmail.com>

**Comment by Smith-Rick** [comment]
![error1](https://user-images.githubusercontent.com/22126614/107137526-51305c00-68c2-11eb-8723-995c2210287d.png)
![Error2](https://user-images.githubusercontent.com/22126614/107137527-51c8f280-68c2-11eb-951a-2f706592f48d.png)

In case the images did not come through, I am trying to upload them here.

**Comment by Rick-Anderson** [comment]
Sounds like you figured out the problem.

**Comment by Smith-Rick** [comment]
Yes, thank you. I still think it would be beneficial for learners to adjust the instructions so that the startup.cs file is modified before instructed to run the DB commands. I've annotated our teaching notes so that we can help students realize the error will resolve itself in the next step. We encourage them that when errors come up during these tutorials to stop and go back to see what was missed. In this case, nothing is missed, and a change in the order in the instructions, I think would help.

Rick Smith

**Comment by Rick-Anderson** [comment]
The tutorial works as it is. Can you reproduce this behavior? What startup needs to be changed for it to work? We have over a million reports of success and this is the first failure that you describe.

**Comment by Smith-Rick** [comment]
Rick,

Thanks for getting back to me. As a reminder, this is using .Net Core v5.0 with the latest version of visual Studio. It is totally possible that this issue was introduced by .Net 5 or an update to Visual Studio that has since broken the flow of the tutorial since I last ran through it with our students.

I recorded a zoom video that can be seen here. You can see that I can reproduce the error, and it should help validate that I did not miss any steps in the tutorial.

https://byui.zoom.us/rec/share/IYgcLh9o_XDTGGmtwB0597a2UYhg8V5F36demJJfPPLSshhjo8xyCUfCGBj7fFQP.8xp1yYPc7P6GetaV?startTime=1612749931000

Rick Smith

**Comment by Rick-Anderson** [comment]
What exactly is the step that's missing?

**Comment by Smith-Rick** [comment]
Rick,

The suggestion I made in the case, and in the video, was to adjust "when" you run the two commands:
Add-Migration InitialCreate
Update-Database

If you first modify the startup code with this, Add-Migration will not error out. Otherwise it refuses to run and the process is stalled. Users are left to guess at what they should do next or simply try the next steps to see if it fixes the issue or not:
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();

services.AddDbContext<RazorPagesMovieContext>(options => options.UseSqlServer(Configuration.GetConnectionString("RazorPagesMovieContext")));
}

Again, I have no idea why this is now happening with Visual Studio 2019 and .net Core 5.0. We have been leveraging this tutorial since at least 2.2 and every version since. This is the first time we are trying the steps using .net 5.0, which is when we became aware of the issue.

Maybe the issue isn't with the instructions but with the Visual Studio or .net core 5.0 code updates, which might justify having you submit a bug fix to the other teams. I don't know myself, and so maybe the suggestion to modify when the Add-Migration is merely a work around to a different problem that needs to be solved so that the modification to the startup.cs file isn't required before running the Add-Migration InitialCreate command. I'm hoping your expertise on what "should" be happening, might help pinpoint root cause for the error appearing.

I apologize if what I have been sending is not helpful in showing exactly where the issue is. I'm just that one in a million guy trying to make it better for the next million. If I didn't care, I would not have submitted any feedback at all.

Rick Smith

**Comment by Rick-Anderson** [comment]
You never add that. The templates add that for you. I guess that's where you missed the step.
See https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio#examine-the-context-registered-with-dependency-injection

**Comment by Smith-Rick** [comment]
I guess the question is, why isn't it adding it as expected as in the past? Did the video who that I missed a step in the tutorial? Or is this maybe a new VS bug?

Rick Smith

**Comment by Smith-Rick** [comment]
"The scaffolding tool automatically created a database context and registered it with the dependency injection container."

Maybe when the fixed the problem when the instructions required fixing the name in the Data context class setup during the scaffolding part (ASP.NET Core EF Scaffolder uses incorrect namespace - Developer Community (visualstudio.com)<https://developercommunity.visualstudio.com/content/problem/652166/aspnet-core-ef-scaffolder-uses-incorrect-namespace.html>, they broke something else.

Rick Smith
