### ISSUE TITLE
bundleconfig.json is not available anymore

### ISSUE THREAD

**Issue by lwilson1973** [dotnet/AspNetCore.Docs#21461]
This is just one example of the 5.0 docs referencing something from a previous version.
Please update the docs so that the 5.0 filter only references things I can do with 5.0.

bundleconfig.json can't be used in 5.0, yet the docs clearly say this is something that you can do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
> Please update the docs so that the 5.0 filter only references things I can do with 5.0.

That's not possible, sorry.
