### ISSUE TITLE
Doc on differences between Razor pages and MVC

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#21473]
Is there document on differences between Razor pages and MVC? given that Razor pages is recommended over MVC.

cheatsheets or comparison page would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://github.com/Rick-Anderson/RP-vs-MVC unofficial 
See #17882

cc @LadyNaggaga @danroth27
