### ISSUE TITLE
Talk about what runs client-side and what runs server-side

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#21479]
Especially for Blazor Server, it would be nice to know what runs in the browser and what runs on the server. Specifically, except for JSRuntime, what parts of the `@code` block run on the server?

If this is elsewhere in the docs, I couldn't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think a change to the bullet list here will cover it. A bullet point can say that the runtime on the server handles the C# code and something to the effect that the C# code stays on the server. We may have had that (or even still do). I'll check further in a minute and probably float a PR for what we're missing. Thanks for suggesting it.

**Comment by guardrex** [comment]
We do have it in the *Hosting models* topic, where is says for Blazor Server ...

> The app's .NET/C# code base, including the app's component code, isn't served to clients.

... listed in the list of benefits.

However, I still think a quick one-liner in the bullet list here would be ok. I'll do that and see if DR is ok with it.
