### ISSUE TITLE
Please add -sqlite flag to command documentation

### ISSUE THREAD

**Issue by sethpeasley** [dotnet/AspNetCore.Docs#21475]
The tutorial to use EntityFramework, specifically the section to scaffold pages (https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio-code#scaffold-student-pages) includes instruction for MacOS and Linux users to run this command: `dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Data.SchoolContext -udl -outDir Pages/Students --referenceScriptLibraries -sqlite`

All of the flags used in the command are documented here (that is, this page about the aspnet-codegenerator) except for the '-sqlite' flag. (I searched on the page (using CTRL-F) for the word "sqlite", "database", and "connection", and find no results.)

I found, by accident, this passing mention of what that flag does, "you need to add the --useSqlite or -sqlite flag for the tool to know sqlite is being used. Otherwise it looks for sqlserver." (https://github.com/dotnet/Scaffolding/issues/1393#issuecomment-683910709). 

Please update this documentation to mention the use of this '-sqlite' flag.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517fdd63-f70b-a52b-56fa-e5051a13ae00
* Version Independent ID: 754e1c4d-4742-a83b-7f2d-5dead439e569
* Content: [dotnet aspnet-codegenerator command](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson this issue is similar to https://github.com/dotnet/AspNetCore.Docs/issues/21789. I do think adding a section mentioning the `--useSqlite` flag would be a good idea.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  you're right, hopefully you can  PR this.
