### ISSUE TITLE
Update to .Net 5.0

### ISSUE THREAD

**Issue by alvipeo** [dotnet/AspNetCore.Docs#21471]
The sample is very outdated. Please update. 
VS2019 (Version 16.9.0 Preview 3.0) doesn't have a template with B2C fields, at least I couldn't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
Dup of #18233
@CamSoper  do you have an ETA on updating this?
