### ISSUE TITLE
Dotnet core Web API debug through visual studio inside Docker (Linux) failed at certificate mapping while Web App works

### ISSUE THREAD

**Issue by brijesh-1111** [dotnet/AspNetCore.Docs#21472]
# Issue description

Visual Studio (I have VS 2019) not able to run Web API (asp.net core 5) Project in debug mode if the launch setting is "Docker" (Generated from the Visual Studio template - no modification whatsoever)

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core
* [x] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

Microsoft Visual Studio Enterprise 2019  Version 16.8.2
Dotnet --version: 5.0.100

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

# How to reproduce

It's very simple steps to reproduce this issue:

1. Create a new visual studio 2019 blank solution.
2. Add Web App Project with Docker Support (Linux based) and .net core framework 5.0 with Model-View-Controller
3. Add Web API Project with Docker Support (Linux based) and .net core framework 5.0
4. Build the Project one after another
5. Run the Web App Project first
6. Run the Web API Project next

You will notice that Web App Project runs without any issue and you will get the page in your browser (with HTTPS).
However, the same thing you will expect for Web API Project (with Weatherforecast API) but it gives a Certificate error.

# OUTPUT Window of Visual Studio

When you run the Web App Project you will notice that it run the docker run command along with all the drive mapping and environment variables settings something similar like below

`docker run -dt -v "C:\Users\bmshah\vsdbg\vs2017u5:/remote_debugger:rw" -v "D:\Temp\UseThrow\DockerSamples\WebApplication01:/app" -v "D:\Temp\UseThrow\DockerSamples:/src/" -v "C:\Users\bmshah\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\bmshah\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -v "C:\Users\bmshah\.nuget\packages\:/root/.nuget/fallbackpackages3" -v "C:\Microsoft\Xamarin\NuGet\:/root/.nuget/fallbackpackages" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "NUGET_PACKAGES=/root/.nuget/fallbackpackages3" -e "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2;/root/.nuget/fallbackpackages3" -P --name WebApplication01 --entrypoint tail webapplication01:dev -f /dev/null`

When you run the Web Api Project you will notice that it run the docker exec command with no such arguments. something like below

`docker exec -i e0e3b6a8c92e1f1d3a9ea6c31677e7f58b674ab2d519614c897f9fa3e3d57dd0 /bin/sh -c "if PID=$(pidof dotnet); then kill $PID; fi"`

Not sure why there are two different commands for the same kind of projects. I believe docker run with all drive mapping and environment variable makes sense here but not sure what others feel/ suggest.

![Docker Web API Error](https://user-images.githubusercontent.com/25770825/107162459-dc642d00-6968-11eb-8d25-7cfa67fb7dfe.jpg)

I have also checked my Certification location "AppData\Roaming\ASP.NET\Https" and both the certificates (Web App + Web Api) are well available there. Moreover, If I use IIS Express launch profile it works without giving me a certificate warning. Only thing is Docker Launch Profile for Web API is not adding this certificate inside the docker.
 
# Comparing the Container File System

I took a bit step further to check the container file system for Web App and for Web Api (after F5) and I found that both Web App and Web API containers have the certificate at root > .aspnet > https > {app name}.pfx file. 

![Docker - 01](https://user-images.githubusercontent.com/25770825/107162624-47faca00-696a-11eb-8445-e943098fb13e.jpg)
![Docker - 02](https://user-images.githubusercontent.com/25770825/107162625-4b8e5100-696a-11eb-89a6-46f4befd2ff0.jpg)

# Summary

Dotnet Core 5 Web API for Docker (Linux) from Visual Studio debugging is not working while the same for Web App it's all working as expected.

**Comment by guardrex** [comment]
@brijesh-1111 When an issue is opened using the **This page** feedback button and form, topic metadata is added automatically, which automatically pings the author of the topic. What topic is this associated with? Please provide the link. I'll add the metadata manually to your issue.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
