### ISSUE TITLE
document that ASP.NET Core doesn’t use or read app pool configuration or system.web sections.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21487]
Per @jkotalik 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Configuration sections of web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0#configuration-sections-of-webconfig) states:

Configuration sections of ASP.NET 4.x apps in `web.config` aren't used by ASP.NET Core apps for configuration:

* `<system.web>`
* `<appSettings>`
* `<connectionStrings>`
* `<location>`

I'll rewrite that as 
***THE FOLLOWING*** Configuration sections ~of ASP.NET 4.x apps~ in `web.config` aren't used by ASP.NET Core apps for configuration:

**Comment by jkotalik** [comment]
I think making it the title more obvious would be better as well. Something like "Section that aren't used by ASP.NET Core"

**Comment by Rick-Anderson** [comment]
Per `@davidfowl` 

The runtime config settings are at https://docs.microsoft.com/en-us/dotnet/core/run-time-config
