### ISSUE TITLE
Clarify "Cache dependencies" example

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/AspNetCore.Docs#21505]
I'm trying to understand the [Cache dependencies](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory#cache-dependencies) example, but some of it is eluding me.

First off, please clarify what is meant by "parent" and "child".  I'm confused as to which expires upon the expiry of which other.

`CancellationTokenSource` allows evicting multiple cache entries as a group.  But what's the point of the `using` block in the example?  I downloaded the sample project and replaced the `using` block with the following:

    _cache.Set( CacheKeys.Parent, DateTime.Now, new CancellationChangeToken( cts.Token ) );
    _cache.Set( CacheKeys.Child, DateTime.Now, new CancellationChangeToken( cts.Token ) );

While my two lines are simpler, they seem to have the same effect as the `using` block.  The doc says:

> With the `using` pattern in the code above, cache entries created inside the `using` block will inherit triggers and expiration settings.

What does "triggers and expiration settings" refer to here?

I must add dependent cache entries in my application, but they must be added at separate times.  Therefore I can't take the approach shown in the example's `using` block since it requires both entries be added at the same time, right?  What functionality am I missing out on by instead taking the approach shown above in my two lines of code?

Finally, shouldn't `Dispose` be called on `CancellationTokenSource` after the `Cancel` call?  The sample doesn't do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0#cache-dependencies)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> First off, please clarify what is meant by "parent" and "child". 
It's the normal computer science parent child.

```
public IActionResult CreateDependentEntries()
{
    var cts = new CancellationTokenSource();
    _cache.Set(CacheKeys.DependentCTS, cts);

    using (var entry = _cache.CreateEntry(CacheKeys.Parent))
    {
        // expire this entry if the dependant entry expires.
        entry.Value = DateTime.Now;
        entry.RegisterPostEvictionCallback(DependentEvictionCallback, this);

        _cache.Set(CacheKeys.Child,
            DateTime.Now,
            new CancellationChangeToken(cts.Token));
    }

    return RedirectToAction("GetDependentEntries");
}
``

> I'm confused as to which expires upon the expiry of which other.

Per the doc, 

When Cancel is called on the CancellationTokenSource, both cache entries are evicted.

> What does "triggers and expiration settings" refer to here?

Per the doc:

Any activity on the cache (Get, Set, Remove) can trigger a background scan for expired items. A timer on the CancellationTokenSource (CancelAfter) also removes the entry and trigger a scan for expired items.

**Comment by HappyNomad** [comment]
> When `Cancel` is called on the `CancellationTokenSource`, both cache entries are evicted.

How is this "the normal computer science parent child"?  If they're mutually dependent then they're siblings rather than parent/child.  Better to avoid confusion by calling it what it is.

> Any activity on the cache (Get, Set, Remove) can trigger a background scan for expired items.

You copy and pasted that from a different section of the doc.  It doesn't flow from the section we're discussing and I don't see how it fits together.  What **code** in the example of the **same** section does "triggers and expiration settings" refer to?  If there isn't any then please add some to demonstrate.

Please kindly answer my last two questions:
  - I must add dependent cache entries in my application, but they must be added at separate times. Therefore I can't take the approach shown in the example's `using` block since it requires both entries be added at the same time, right? What functionality am I missing out on by instead taking the approach shown above in my two lines of code?
 - Finally, shouldn't `Dispose` be called on `CancellationTokenSource` after the `Cancel` call? The sample doesn't do that.

Please consider improving the doc instead of simply closing this issue.
