### ISSUE TITLE
Clarify "Cache dependencies" example

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/AspNetCore.Docs#21504]
I'm trying to understand the [Cache dependencies](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory#cache-dependencies) example, but some of it is eluding me.

First off, please clarify what is meant by "parent" and "child".  I'm confused as to which expires upon the expiry of which other.

`CancellationTokenSource` allows evicting multiple cache entries as a group.  But what's the point of the `using` block in the example?  I downloaded the sample project and replaced the `using` block with the following:

    _cache.Set( CacheKeys.Parent, DateTime.Now, new CancellationChangeToken( cts.Token ) );
    _cache.Set( CacheKeys.Child, DateTime.Now, new CancellationChangeToken( cts.Token ) );

While my two lines are simpler, they seem to have the same effect as the `using` block.  The doc says:

> With the `using` pattern in the code above, cache entries created inside the `using` block will inherit triggers and expiration settings.

What does "triggers and expiration settings" refer to here?

I must add dependent cache entries in my application, but they must be added at separate times.  Therefore I can't take the approach shown in the example's `using` block since it requires both entries be added at the same time, right?  What functionality am I missing out on by instead taking the approach shown above in my two lines of code?

**Comment by guardrex** [comment]
Hello @HappyNomad ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
