### ISSUE TITLE
IIS vs. Kestrel in Docker

### ISSUE THREAD

**Issue by FrankAtHexagon** [dotnet/AspNetCore.Docs#21503]
Hi everyone. I have a few quick questions about running ASP.NET Core apps in Docker.

* If I'm running an ASP.NET Core app in Docker, like how it's outlined [here](https://docs.docker.com/engine/examples/dotnetcore/), is the app running in Kestrel or IIS?
* Is IIS involved whatsoever in the above configuration? Is the configuration out-of-process or is this not relevant?
* Is it recommended to use Kestrel or IIS when running an app in Docker?

Thanks everyone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=windows)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by FrankAtHexagon** [comment]
These answers to these questions are not clear from the documentation and is the reason I'm opening this issue.

**Comment by Rick-Anderson** [comment]
IIS doesn't run cross-platform on  MacOS, and Linux

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-5.0&tabs=windows#kestrel-vs-httpsys

**Comment by sotoh** [comment]
Thanks for the short and valid answer
