### ISSUE TITLE
Cache dependencies: Additional scenario

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/AspNetCore.Docs#21509]
The scenario shown in the "Cache dependencies" section covers adding two dependent objects to the cache at the same time.  What if two objects are dependent but must be added to the cache in different parts of the code?  This scenario should be covered by the doc.

Below is the code that demonstrates the approach.  Note that it eliminates some unneeded complexity from the existing example by using `PostEvictionCallback` instead of `CancellationTokenSource` to manage the dependency among cache entries.

    public IActionResult CreateDependentEntries()
    {
        _cache.Set( CacheKeys.Parent, DateTime.Now, new MemoryCacheEntryOptions()
            .RegisterPostEvictionCallback( ( k, v, r, s ) => _cache.Remove( CacheKeys.Child ) ) );
        _cache.Set( CacheKeys.Child, DateTime.Now );

        return RedirectToAction("GetDependentEntries");
    }

    public IActionResult GetDependentEntries()
    {
        return View("Dependent", new DependentViewModel
        {
            ParentCachedTime = _cache.Get<DateTime?>(CacheKeys.Parent),
            ChildCachedTime = _cache.Get<DateTime?>(CacheKeys.Child),
            Message = _cache.Get<string>(CacheKeys.DependentMessage)
        });
    }

    public IActionResult RemoveChildEntry()
    {
        _cache.Remove( CacheKeys.Parent );
        return RedirectToAction("GetDependentEntries");
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0#cache-dependencies)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by HappyNomad** [comment]
@Rick-Anderson Who do you "need more info" from?  If it's from me then what do you need?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
