### ISSUE TITLE
Can or Can Not be applied to?

### ISSUE THREAD

**Issue by MacArthur** [dotnet/AspNetCore.Docs#21519]
> The ResponseCacheAttribute can be applied to:
> - Razor Pages: Attributes can't be applied to handler methods.

Can be applied to, can't be applied to... who wrote this? Can we get some clarification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's correct. Can be applied to entire page, just not at handler level.
