### ISSUE TITLE
SQL?

### ISSUE THREAD

**Issue by JohnStraumann66** [dotnet/AspNetCore.Docs#21513]
[Enter feedback here]
For this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio
Do you have a similar tutorial that uses an Azure SQL database? Is there a tutorial that shows how to generate a Web API for existing Azure SQL Database tables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's just a matter of setting the connection string. 

> Is there a tutorial that shows how to generate a Web API for existing Azure SQL Database tables?

**Comment by Rick-Anderson** [comment]
> It's just a matter of setting the connection string.
> 
> > Is there a tutorial that shows how to generate a Web API for existing Azure SQL Database tables?

See https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding?tabs=dotnet-core-cli
