### ISSUE TITLE
Distributed NCache Getting Started Guide for Windows link broken

### ISSUE THREAD

**Issue by Guru-Soft** [dotnet/AspNetCore.Docs#21517]
NCache Getting Started Guide for Windows

![image](https://user-images.githubusercontent.com/34564164/107539709-3f64f680-6beb-11eb-8375-1901ad41d2af.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Guru-Soft ... I've got a quick sec to patch it up before calling it a day. It should go to ...

https://www.alachisoft.com/resources/docs/ncache/getting-started-guide-windows/

... now.
