### ISSUE TITLE
Confusing guidance

### ISSUE THREAD

**Issue by esamk** [dotnet/AspNetCore.Docs#21512]
@guardrex 

At the beginning of the doc reads:

> To create a new Blazor WebAssembly project with an authentication mechanism:
> 1. ...
> 2. Select Individual User Accounts with the Store user accounts in-app option to store users within the app using ASP.NET Core's Identity system.
> 3. ...

Since the doc is for standalone, not hosted apps, this guidance seems confusing to me since I can't remember on the top of my head exactly what packages this selection will install. Why not add a remark clarifying that this selection does not mean you have to store users in the app, it merely installs the package mentioned in the next section of the doc. 

Besides, it would be much clearer if the doc would start by saying that a standalone blazor app needs the Microsoft.AspNetCore.Components.WebAssembly.Authentication package and you can either install it to an existing app OR if you're creating a new app from scratch, doing the "Select Individual User Accounts" thing will install the package for you.

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/fi-fi/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'm doing that now, but I'm using your other issue to address it.

I'll move this remark over there.
