### ISSUE TITLE
remove the redundant entries here and link to the API docs instead.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21528]
See [this issue](https://github.com/dotnet/aspnetcore/issues/28297#issuecomment-774133945)
cc @nmnick18

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-the-aspnet-core-app-to-use-httpsys)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@nmnick18 have you had a chance to work on this?

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hello!
A newbie to aspnetcore docs here.
Is this available to work on?

**Comment by Rick-Anderson** [comment]
@vijaya-lakshmi-venkatraman  yes, let me know if you need any help.

**Comment by utsabshrestha** [comment]
Hello, I want to contribute on this if its available to work on.
From what i understand we want to update the comments here:
[https://github.com/dotnet/aspnetcore/blob/58a7eb63ad5c6b037c43d2bd178c79f4248bb71f/src/Servers/HttpSys/src/HttpSysOptions.cs](url) using the descriptions from [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0#configure-the-aspnet-core-app-to-use-httpsys](url).

The final doc will be rendered in the [ https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.httpsys.httpsysoptions?view=aspnetcore-5.0](url) with detail descriptions from the concept docs for HttpSys.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi does fixing review comments from [this](https://github.com/dotnet/aspnetcore/pull/37949) PR fix this issue?

**Comment by adityamandaleeka** [comment]
The API docs have been updated in https://github.com/dotnet/aspnetcore/pull/44380.

The conceptual docs can now be cleaned up for 8.0.
