### ISSUE TITLE
HttpClientFactory: Can I create a Typed Client instance from an IHttpClientFactory instance?

### ISSUE THREAD

**Issue by svdHero** [dotnet/AspNetCore.Docs#21538]
Hi there,

I already have defined a Typed Client
```csharp
public class MyExternalFooService: IMyExternalFooService
{
    public HttpClient Client { get; }
    public MyExternalFooService(HttpClient client)
    {
        Client = client;
    }
    
    [...]
}
```
and registered it as follows:
```csharp
services.AddHttpClient<IMyExternalFooService, MyExternalFooService>(client => client.BaseAddress = new Uri("www.foo.bar/api"));
```

A few of my services use this Typed Client and get it injected through their constructor, which works fine.

However, I also want to use such a client in a long running task sending out many thousands of http requests, possible running for weeks or months. If the DI magic only happens through the constructor once, when the long running task is created, this means that the same `HttpClient` instance is used for a long time, possibly resulting in the well known DNS problems.

Hence, I'd like to inject a `IHttpClientFactory` to the long running task constructor. The documentation only describes how to create an `HttpClient` instance from an `IHttpClientFactory` instance using [Named Clients](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#named-clients) but not using [Typed Clients](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#typed-clients).

Since I already have configured the Typed Client, I don't want to duplicate my configuration code by configuring a Named Client for the same `MyExternalFooService` class. Is it possible to create a Typed Client instance via an injected `IHttpClientFactory`? And if so, could you please add that to the documentation? That would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by svdHero** [comment]
Side note: The same issue may arise outside ASP.NET when using `.NET Generic Host` with a .NET console application that has many long running (event) processing loops. E.g. in a microservice system's back-end worker or similar.

**Comment by serpent5** [comment]
At the risk of doing typed clients a huge disservice, they're really just fancy wrappers around `HttpClient`s. This means you can use `IServiceProvider` to create a scope and resolve your `IMyExternalFooService` typed client implementation from there. Something along the lines of this:

```csharp
using var serviceScope = serviceProvider.CreateScope();
var myExternalFooService = serviceScope.ServiceProvider.GetRequiredService<IMyExternalFooService>();

// ...
```

**Comment by svdHero** [comment]
I've never called a ServiceProvider directly. Isn't that an anti-pattern (aka service locator)? Also, what exactly is the `serviceProvider` variable in your code snippet? Where does it come from?

**Comment by serpent5** [comment]
It's generally known as an antipattern but there are cases where it's the only option. See [](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task), where the second code example shows injecting `IServiceProvider` into the ctor and then using the approach I described, but for a different service.

**Comment by serpent5** [comment]
I forgot that there’s already an example for console apps on the page: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#use-ihttpclientfactory-in-a-console-app. That shows resolving the typed client through `IServiceProvider`, as I described. The only real difference then is in resolving the `IServiceProvider` through the ctor.

@Rick-Anderson I think this can be closed now.

**Comment by svdHero** [comment]
@serpent5 Thank you for your help. I will consider using the service provider.
