### ISSUE TITLE
Remove repository from Create backend services for native mobile apps

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21542]
At the suggestion of the EF team, we removed the repository from the  [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) over 3 years ago. Removing the repository:

* Improved customer satisfaction 10%.
* Eliminated all the repository questions and problems issues.

Also change ID from GUID to long. Much better for postman, testing, etc.

Use the same code as [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdbdf1ed-c52a-3be8-1f41-aecbdab0883b
* Version Independent ID: d06996cc-14aa-96e2-fd62-9d5bbc059107
* Content: [Create backend services for native mobile apps with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mobile/native-mobile-backend.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mobile/native-mobile-backend.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mobile**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
I can't argue with the numbers but there are plenty of MS devs who lament that too many conference demos, blog posts, and even docs show new developers "hello world" samples that lead to poorly-designed, tightly-coupled code with no abstractions. So, yes, creating services that are just a thin wrapper around a database works for simple demos/docs, but when complex systems are built this way it (often) leads to problems.

At the very least it's worth including a note in the article that discusses the proper use of dependency inversion and injection. It can link here if you like: 

https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/architectural-principles#dependency-inversion

**Comment by Rick-Anderson** [comment]
>I can't argue with the numbers but there are plenty of MS devs who lament that too many conference demos, blog posts, and even docs show new developers "hello world" samples that lead to poorly-designed, tightly-coupled code with no abstractions. So, yes, creating services that are just a thin wrapper around a database works for simple demos/docs, but when complex systems are built this way it (often) leads to problems.

The EF team doesn't agree with that.

We no longer own this code.
