### ISSUE TITLE
Enhanced diagnostic logging for ANCM is missing

### ISSUE THREAD

**Issue by shirhatti** [dotnet/AspNetCore.Docs#21541]
Looks like this link might have been broken in a document refactor? `xref:host-and-deploy/aspnet-core-module#enhanced-diagnostic-logs`

Referenced from:
- https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/test/troubleshoot-azure-iis.md#L313
- https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/test/troubleshoot-azure-iis.md#L314
- https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/test/troubleshoot-azure-iis.md#L317

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0#aspnet-core-module-debug-log-azure-app-service)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by shirhatti** [comment]
@Rick-Anderson The PR didn't fix it. There's some actual content that's been lost in the process. The content is available on the 3.1 version of docs- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1#enhanced-diagnostic-logs

**Comment by shirhatti** [comment]
I'm happy to PR then content if need be. @Rick-Anderson let me where this content should be included. This is a really important scenario

**Comment by Rick-Anderson** [comment]
Looks like it's at https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-6.0#enhanced-diagnostic-logs
