### ISSUE TITLE
Cascadingvalue/parameter across razor class library doesn’t seem to pass across class libraries.

### ISSUE THREAD

**Issue by Alienroid** [dotnet/AspNetCore.Docs#21549]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

Cascadingvalue/parameter across razor class library doesn’t seem to pass across class libraries.

- Explain why this topic is needed.

I am trying to refactor commonly used razor/blazor components into razor class library. I have a theme cascading value defined in layout of the main project. The razor class library contains the components that uses this theme definition. However, seems the cascadingvalue is not passed across from main project to class library

- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

**Comment by guardrex** [comment]
Hello @Alienroid ... This scenario pertains to a framework feature that I don't have information on from the product unit. Open an issue on this at :point_right: https://github.com/dotnet/aspnetcore/issues.
