### ISSUE TITLE
dotnet dev-certs https --trust not working on an AzureAD user session

### ISSUE THREAD

**Issue by blackhill** [dotnet/AspNetCore.Docs#21551]
Dotnet version: 5.0.103

When I execute this command line "dotnet dev-certs https --trust" on a user session **connected to an AzureAD**, I have the following error "**There was an error trusting HTTPS developer certificate**."

But If I execute this command line on a user session **not connected to AzureAD**, it's working.

I've also tried to install the self-signed certificate manually but I'm not able to add a certificate to the "Trusted Root Certification Authorities".

I have the following error when I try to paste the certificate: "**The certificate cannot be pasted into the Trusted Root Certification Authorities store. Access denied.**" (I'm the Admin of my machine)

I have this error if I try to import the certificate: "**The import failed because the store was read-only, the store was full, or the store did not open correctly**"

I've found on StackOverflow someone that has the same issue: https://serverfault.com/questions/1008035/unable-to-import-certificate-into-user-trusted-root-certificate-store - But it didn't work for me. 

The issue might come from a default AzureAD GPO.

Thanks for the help.

**Comment by Rick-Anderson** [comment]
The dotnet cert is only supported on the local machine, not Azure.

**Comment by blackhill** [comment]
I'm trying to install it on a local machine for development but it's not
working when the windows session is connected to azureAD.

I don't want to use it on azure.

Thanks for your help
