### ISSUE TITLE
[CSS Isolation] More in depth explanation about the `::deep` pseudoelement

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#21558]
The section on the `::deep` pseudo selector could use a more in-depth explanation about how deep works. There is no mention to how `::deep` affects the transformation of the CSS rule and that makes it incredibly hard to reason about.

We should include a section that describes what `::deep` does with a sample "before" and "after" `::deep` at several locations in the rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by daveabrock** [comment]
Hey @guardrex - I see you've got `needs-more-info` but let me know if you would like me to assist with this update.

**Comment by guardrex** [comment]
Sure, thanks @daveabrock. I think 'needs more info' was a stray click ... looks like I added and then removed it immediately.

**Comment by daveabrock** [comment]
OK, give me a few weeks. I should be able to dig into it a little more.

**Comment by daveabrock** [comment]
Hey @javiercn - I'm working on this improvement but would like some clarification on other scenarios you are looking for, in addition to what's covered in the section, [_Child component support_](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support). 

In that section, I use the `::deep` combinator to illustrate how you can inherit identically named styles from parent components. What other scenarios or details are you looking for? Are you looking to expand with a more complex example with multiple children?

**Comment by guardrex** [comment]
Checking in on this one @javiercn ...

:point_up: @daveabrock is asking if that section at [Child component support](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#child-component-support) is enough to cover your ask? If not, what else are u requesting for `::deep`?

**Comment by guardrex** [comment]
@daveabrock ... Javier is very 🏃😅 with a large workload. We'll circle back around to this later, which might even be post 6.0 GA.
