### ISSUE TITLE
Code example to provision the container automatically is invalid

### ISSUE THREAD

**Issue by alex737876** [dotnet/AspNetCore.Docs#21566]
The code 
```
string connectionString = "<connection_string>";
string containerName = "my-key-container";
BlobContainerClient container = new BlobContainerClient(connectionString, containerName);

// optional - provision the container automatically
await container.CreateIfNotExistsAsync();

services.AddDataProtection()
    .PersistKeysToAzureBlobStorage(container, "keys.xml");
```
is invalid, because `.PersistKeysToAzureBlobStorage()` does not take the provided arguments using dotnet >= 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'd strongly suggest moving to the Azure SDK owned packages now, see https://github.com/Azure/azure-sdk-for-net

See https://github.com/dotnet/aspnetcore/issues/25229

@markmcgookin  can you outline the changes I need to make to this document?

**Comment by alex737876** [comment]
Thank you. You have do get  blobClient with name like „keys.xml“ from the blobContainerClient and pass this as argument
