### ISSUE TITLE
PersistKeysToAzureBlobStorage wrong docs

### ISSUE THREAD

**Issue by alex737876** [dotnet/AspNetCore.Docs#21567]
The lin `.PersistKeysToAzureBlobStorage("<storage account connection string", "<key store container name>", "<key store blob name>")` is described to create blob automatically, but thorws exception if container does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You'll have to open an issue with the source repository and have the simplest possible public sample that reproduces the issue.
