### ISSUE TITLE
中文內容有誤

### ISSUE THREAD

**Issue by Zeno199** [dotnet/AspNetCore.Docs#21564]
[請在此輸入您的意見]
類別名稱 Razor PagesMovie。 Razor產生 PagesMovieCoNtext 。 
應該改為 RazorPagesMovie.Data.RazorPagesMovieContext

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---

#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [第2部分：加入模型](https://docs.microsoft.com/zh-tw/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
感谢您的举报。它被固定在＃21565
Gǎnxiè nín de jǔbào. Tā bèi gùdìng zài#21565

Thanks for report this. It's being fixed in #21565
