### ISSUE TITLE
Namespaces and NuGet package please!

### ISSUE THREAD

**Issue by jrutley** [dotnet/AspNetCore.Docs#21561]
On every page, it would make developer lives easier if the actual NuGet packages were displayed higher up on the page: either at the top, or above each code listing.

![image](https://user-images.githubusercontent.com/771365/108088100-16f35700-7046-11eb-87bf-4fede260192e.png)

e.g. I didn't remember off the top of my head where to include this. A couple of Google searches later tells me it's in Microsoft.Extensions.Http, but it's not obvious from here.

After finding the correct NuGet package, I came back to this page to check and found a reference to Microsoft.Extensions.Http near the bottom.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
It's listed the first time it's needed by the code displayed.
