### ISSUE TITLE
6.0 Migrate from ASP.NET to ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21570]
Update to ~3.1~ ***UPDATED***  6.0 when 6.0 releases and 2.1 is dropped from LTS

The entire series needs to be review by the PU
Review  #16437 and #14386

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 60622](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60622)

**Comment by scottaddie** [comment]
@Rick-Anderson I recommend updating the doc for 6.0 instead of 3.1. 6.0 will be the latest LTS release when it hits GA in November.

**Comment by SMNRST** [comment]
As I know there is no `Startup` class in ASP.NET Core 6. It is a kind of confusing, should I need to add the `Startup` class, when .net 6 obviously designed without it?
