### ISSUE TITLE
Rewrite the background task queue using Channels

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#21577]
The current implementation can be simplified using System.Threading.Channels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio&source=docs#queued-background-tasks)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@huan086 can you rewrite the code to use [System.Threading.Channels](https://www.stevejgordon.co.uk/an-introduction-to-system-threading-channels)

**Comment by davidfowl** [comment]
I can review.

**Comment by Rick-Anderson** [comment]
cc @stevejgordon @serpent5 @jo-ninja @mizrael @maartenba  if one of you want to help and get on the authors list for this doc.

**Comment by mizrael** [comment]
I'd be happy to help. What it is exactly that you need?

**Comment by serpent5** [comment]
I can help too, if needed.

**Comment by Rick-Anderson** [comment]
> What it is exactly that you need?

Rewrite https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/hosted-services/samples/3.x/BackgroundTasksSample/Services/BackgroundTaskQueue.cs using `System.Threading.Channels`

**Comment by davidfowl** [comment]
Right, remove the ConcurrentQueue and SemaphoreSlim and use a Channel< instead

**Comment by mizrael** [comment]
I'll take a look later today/tonight

**Comment by mizrael** [comment]
@Rick-Anderson @davidfowl something like this https://github.com/dotnet/AspNetCore.Docs/pull/21582 ?

**Comment by Rick-Anderson** [comment]
@mizrael  we can't comment or review it until you sign the CLA.

**Comment by mizrael** [comment]
> @mizrael we can't comment or review it until you sign the CLA.

sorry, I missed that. Done now
