### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by tacoWanneeJama** [dotnet/AspNetCore.Docs#21572]
[Enter feedback here]

At the start I was told to remove the applicationUrl , but later on it was mentiononed te be valuable. What should I do?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by Rick-Anderson** [comment]
Remove to publish
