### ISSUE TITLE
Add a topic for graceful shutdown and how it works in Kestrel

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#21574]
We should have a page that describes how graceful shutdown works in Kestrel (for both HTTP/1.1 and HTTP/2) and how it could be configured in various environments with a load balancer to gracefully drain traffic.

cc @Tratcher @halter73 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 66053](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66053)

**Comment by Rick-Anderson** [comment]
@Tratcher @halter73 can one of you write this draft?

**Comment by Tratcher** [comment]
Rough outline:
- The Host receives a shutdown signal (e.g. CTL+C, StopAsync, etc.)
- IHostApplicationLifetime.ApplicationStopping is signaled to notify the application. Long running operations should subscribe to this event.
- The Host calls IServer.StopAsync with a configurable shutdown timeout (default 30s)
- Kestrel (and Http.Sys) close their port bindings and stop accepting new connections. They also signal current connections to stop processing new requests. For HTTP/2 and HTTP/3 this involves sending a preliminary GoAway message to the client. For HTTP/1.1 requests are processed in order so it stops that connection loop.
  - IIS is a little different, it rejects new requests with a 503.
- Active requests are given until the shutdown timeout to complete. If everything completes before the timeout then the server returns control to the host sooner. If the timeout expires then pending connections & requests are forcibly aborted which can cause errors to be reported in the logs and to the clients.

When working with a load balancer several steps can ensure a smooth transition of clients to a new destination.
- Bring up the new instance and start balancing traffic to it (you may already be running several instances for scale purposes)
- Disable or remove the old instance in the load balancer config so it stops receiving new traffic.
- Signal the old instance to shut down
- Wait for it to drain or timeout
(need specific examples for different environments)

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/docs/issues/34879

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/docs/pull/35317
