### ISSUE TITLE
Questions on Tutorial Page: ASP.NET Core/Tutorials/Web apps/Razor Pages/Work with a database

### ISSUE THREAD

**Issue by drjhkom** [dotnet/AspNetCore.Docs#21581]
I'm new to this technology, so I am almost certainly wrong.  Even so, perhaps the page could be adjusted so that people like me are not confused.  Here goes:

This tutorial page says:

    In the previous code, the Main method has been modified to do the following:
    *  Get a database context instance from the dependency injection container.
    *  Call the seedData.Initialize method, passing to it the database context instance.

It seems to me the code is getting the DI container itself and passing it to SeedData.Initialize(...).  SeedData.Initialize(...) then seems to extract the database context.  

Related, I wonder why SeedData.Initialize(...) creates a new Database Context rather than just using the one registered in the DI container.  Is a new database connection created?  Please excuse my newbie ignorance!

Finally, the tutorial page says, "The following exception occurs when Update-Database has not been run...".  I don't get this exception, and don't see what "Update-Database" refers to.  There are no other textual instances of "Update-Database" on the tutorial page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-ca/aspnet/core/fundamentals/dependency-injection and the EF documentation.
