### ISSUE TITLE
SendGrid has been blacklisted?

### ISSUE THREAD

**Issue by ConaxLiu** [dotnet/AspNetCore.Docs#21596]
This is probably a SendGrid issue that the .NetCore team can't do anything about. But it may help people who are wondering why they did not receive the register confirmation email from the WebPWrecover project.

I've followed the instructions on this article and successfully registered with SendGrid (free plan), configured WebPWrecover, and registered several new users, each with a different email domain:
* @hotmail.com
* @gmail.com
* @conax.co.nz (my Azure account)
* @xtra.co.nz (provided by my ISP)

Two of them received the email, and two did not. I checked the Activity Feed on SendGrid for the two that had problem, and here are the error messages:

@hotmail.com
> Received by hotmail-com.olc.protection.outlook.com
>  Blocked
> 2021/02/21 2:54pm UTC+13:00
> 
> The hotmail.com server blocked this message from being delivered. While we won't try to send this message again, we will attempt to send new messages to this address in the future.
> You can view all addresses in your Blocks suppression group. Learn more.
> 
> Full response from the hotmail.com server:
> 550 5.7.1 Unfortunately, messages from [50.31.49.42] weren't sent. Please contact your Internet service provider since part of their network is on our block list (S3140). You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors. [DM6NAM11FT066.eop-nam11.prod.protection.outlook.com]
> 

@xtra.co.nz
> The email was not delivered to the recipient. We'll continue trying to send this email for a few more hours, then show a Bounce if it can't be delivered. Learn more.
> Latest response from the xtra.co.nz server:
> 554 5.7.1 Connection from 167.89.12.138 rejected due to an RBL match
> 

In summary, SendGrid may have already been blocked by some ISPs.

To check the Activity Feed on SendGrid:
1. Log onto SendGrid.
2. Click Activity on the left side navigation pane.
3. Click the 'Show All Activity' button in the middle of the screen.
4. Click any activity in the list to get delivery/issue details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio#debug)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the info. I found the same when testing and mention most of that at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio#debug-email

**Comment by Rick-Anderson** [comment]
@ConaxLiu I updated the title to make it more discoverable.

**Comment by ConaxLiu** [comment]
Thanks Rick. FYI, I was able to receive the email on my Azure account. Only Hotmal and my ISP (xtra.co.nz) had rejected SendGrid emails. So you might want to remove 'Azure' from the title.

**Comment by Rick-Anderson** [comment]
Removed. You can edit it too :)
