### ISSUE TITLE
Does not include use information

### ISSUE THREAD

**Issue by marcnoon** [dotnet/AspNetCore.Docs#21590]
New developers will have no clue where to find the nuget package to install gRPC into their console app much less any web api or mvc app.  The documenters did not spend any time considering other people and are heartless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
This is an intro to gRPC, not a tutorial. It links to https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start
