### ISSUE TITLE
Unnecessary classes in project

### ISSUE THREAD

**Issue by elegault** [dotnet/AspNetCore.Docs#21595]
What is the purpose of the StartupInject and StartupTemplate classes?  They don't appear to be used in the project, and are not referenced in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1#environments)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Probably previous versions or perhaps other docs.

**Comment by elegault** [comment]
Should I remove them and create a PR for https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/fundamentals/environments/3.1sample?

**Comment by Rick-Anderson** [comment]
They might be used. No harm having them. The StartupInject looks useful. I think the StartupTemplate shows what the default templates generate.

Next time I do review of this doc I'll consider removing them,, after I've confirmed they're not used and not useful.

**Comment by Rick-Anderson** [comment]
They are used, see https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/environments/3.1sample/EnvironmentsSample/StartupInject.cs#L10
