### ISSUE TITLE
Very poor documentation

### ISSUE THREAD

**Issue by marcnoon** [dotnet/AspNetCore.Docs#21591]
Documentation is poor.  It doesn't provide links to adding gRPC to new MVC, WCF, or Web API in .net core or a regular .net app.  Does not spend any time distinguishing different types of apps and their capabilities.   Does not consider new developers.  Does not consider existing .net developers.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
Integrating gRPC into UI or Web API apps is beyond the scope of this tutorial. 

> Does not spend any time distinguishing different types of apps and their capabilities. 

That's tracked in #17882

**Comment by marcnoon** [comment]
Docs are better now. I won't have to move to Dart web api now.  You must have spoken with Charles Petzold.
