### ISSUE TITLE
新增 NuGet 套件 有錯誤

### ISSUE THREAD

**Issue by AsiaOstrich** [dotnet/AspNetCore.Docs#21592]
新增 NuGet 套件
![image](https://user-images.githubusercontent.com/19768691/108592066-f826f480-73a6-11eb-95d4-64ed67ba23ab.png)

文字是寫microsoft.entityframeworkcore, 正確的應該是 Microsoft.EntityFrameworkCore.InMemory , 圖片是正確的

[請在此輸入您的意見]

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [教學課程：使用 ASP.NET Core 建立 Web API](https://docs.microsoft.com/zh-tw/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JasonCard** [comment]
@Rick-Anderson Yes, this MT issue has been escalated in the past and we'll re-escalate it. MT engine issue can take a long time to get addressed, so I appreciate your help to code fence the affected terms to address these over-localization issues.
