### ISSUE TITLE
CaptureStartupErrors not defined for IHostBuilder

### ISSUE THREAD

**Issue by glenn2223** [dotnet/AspNetCore.Docs#21600]
Can [this section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0#capture-startup-errors) be expanded to highlight it's for `IWebHostBuilder` and state what happens in `IHostBuilder` (I'm assuming it does no startup capturing). Or, apply the functionality if required 😁

> 'IHostBuilder' does not contain a definition for 'CaptureStartupErrors' and the best extension method overload 'HostingAbstractionsWebHostBuilderExtensions.CaptureStartupErrors(IWebHostBuilder, bool)' requires a receiver of type 'IWebHostBuilder'

This would need applying to v3 onwards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik  how do you use [Capture Startup Errors](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0#capture-startup-errors) with `IHostBuilder`?
cc @serpent5

**Comment by serpent5** [comment]
Yeah, it's covered on the Generic Host page: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#capturestartuperrors

**Comment by Rick-Anderson** [comment]
Closing since Generic host is now used.
