### ISSUE TITLE
Using the VSCode instructions, a v3.1 project is created.

### ISSUE THREAD

**Issue by lebull** [dotnet/AspNetCore.Docs#21607]
Using the cli as instructed in this tutorial, `dotnet new webapi -o TodoApi` creates a 3.1 project.

![image](https://user-images.githubusercontent.com/3135984/108862313-b9b35480-75b5-11eb-90bd-6ba431e15a48.png)

![image](https://user-images.githubusercontent.com/3135984/108862340-c0da6280-75b5-11eb-9131-d908d63baaed.png)

The rest of the tutorial is incompatible with 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Select the 3.1 version of the tutorial in the version selector.

**Comment by lebull** [comment]
Sorry, am I missing something?  The 3.1 tutorial uses dependencies that are not compatible with 3.1.

![image](https://user-images.githubusercontent.com/3135984/108925806-e2157000-7602-11eb-9ca1-4a0fe2c2ae17.png)


![image](https://user-images.githubusercontent.com/3135984/108925716-c4480b00-7602-11eb-9503-99a204182796.png)

**Comment by Rick-Anderson** [comment]
Yes, read about Global.Json

```
{
  "sdk": {
    "version": "3.1.301"
  }
}
```
