### ISSUE TITLE
Blazor WebAssembly localization from browser culture requires all globalization data

### ISSUE THREAD

**Issue by marin-bratanov** [dotnet/AspNetCore.Docs#21619]
The first sentence of the localization docs for WebAssembly is

> Blazor WebAssembly apps set the culture using the user's language preference.

For that to work for browsers that are not set to `en-US` (that is, man people outside of the USA), you must still add

```
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```

Which is, admittedly, a few paragraphs down, but I think it makes sense to explicitly add that sentence in the first paragraph. I would personally combine both options in a list, something like this (I have not added the links here for readability):

```
By default, Blazor WebAssembly apps set the culture using the user's language preference. To explicitly configure the culture, set CultureInfo.DefaultThreadCurrentCulture and CultureInfo.DefaultThreadCurrentUICulture in Program.Main.

Both approaches change the culture of the app dynamically, so you need to prepare it for that.

<The rest of the current docs could go here - about the csproj flag, about "hardcoding" a culture in blazor.start(), and so on>
```

Once you scratch your head a little why you see `en-GB`, for example, but the dates are formatted according to the `en-US` format it will become apparent that this is a dynamic change from the app perspective, but if you are working on a large app that you are only now starting to localize you can have a hard time figuring this out.

Frankly, there is quite a lot to unpack in those few paragraphs and I would personally probably divide it into a couple of sections if I were writing the article, maybe something like "invariant culture" (currently the last snippet, but it is the easiest), "static culture" (the one with Blazor.start()) and "dynamic culture" where all the info above would go into that last section. This lets you explain the culture format early on, and go from basic that works for most cases to complex and real globalization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#blazor-webassembly)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @marin-bratanov ... I've marked this issue on my UE ("user experience", i.e., topic overhauls) tracking issue. I'll work on it when I reach this topic for updates. Thanks for your feedback.
