### ISSUE TITLE
Further explanation not provided

### ISSUE THREAD

**Issue by Duarte10** [dotnet/AspNetCore.Docs#21614]
Further explanation is not provided.

> Later in the article we'll see how you can change the order and even add a custom culture provider

There was no further explanation later in the article on how to change the order of the culture providers.

[Related issue](https://github.com/dotnet/AspNetCore.Docs/issues/15532)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
Rick I will have a look ASAP, I may push a PR if it's required

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.

**Comment by Duarte10** [comment]
@Rick-Anderson The effort to keep the backlog clean should be by fixing these issues, which have led me and other developers into utter confusion when reading ASP.NET Core docs.

**Comment by hishamco** [comment]
> There was no further explanation later in the article on how to change the order of the culture providers.

@Duarte10, I think I already pointed to that especially when you use a custom `RequestCultureProvider`, if there's something else you need to know, please let me know or explain the use case that you are facing

**Comment by Duarte10** [comment]
@hishamco I'm sorry but nothing was added to the documentation, I'm sure other developers will be as confused as me, no one needs to search AspNetCoreDocs issues in git to understand its documentation.

**Comment by hishamco** [comment]
https://github.com/dotnet/AspNetCore.Docs/blob/7b7704b1beb5c0569f1e5590dbe39becb22d4766/aspnetcore/fundamentals/localization-extensibility.md?plain=1#L48-L62

https://github.com/dotnet/AspNetCore.Docs/blob/7b7704b1beb5c0569f1e5590dbe39becb22d4766/aspnetcore/fundamentals/localization-extensibility.md?plain=1#L48-L62

This shows you how to change the order for a custom provider, for default providers there's a predefine sequence, but you could change it if that's the case

**Comment by hishamco** [comment]
https://github.com/dotnet/AspNetCore.Docs/blob/7b7704b1beb5c0569f1e5590dbe39becb22d4766/aspnetcore/fundamentals/localization-extensibility.md?plain=1#L48-L62

https://github.com/dotnet/AspNetCore.Docs/blob/7b7704b1beb5c0569f1e5590dbe39becb22d4766/aspnetcore/fundamentals/localization-extensibility.md?plain=1#L48-L62

This shows you how to change the order for a custom provider, for default providers there's a predefine sequence, but you could change it if that's the case

**Comment by cocowalla** [comment]
@hishamco I'm sure I'm not the only one who is confused here - the docs clearly state that later in the article it will explain how to change the order... and then never explains it:

```
The default list goes from most specific to least specific. Later in the article we'll see how you can change the order
```

The links you provided appear to show how to add a new provider (which is already covered by the docs), but not how to change the order of configured providers.

**Comment by hishamco** [comment]
Thanks @cocwalla, I will update the docs ASAP, to distinguish between add a new provider and change the existing once

**Comment by hishamco** [comment]
@cocowalla hope the PR, make it clears now

**Comment by Duarte10** [comment]
@Rick-Anderson The added section has a render problem
![image](https://user-images.githubusercontent.com/45232013/147467825-d45111b2-5942-4b86-aa92-ce74acab8e0b.png)

**Comment by hishamco** [comment]
@Rick-Anderson could you please handle this ASAP

Thanks
