### ISSUE TITLE
Got Scaffolding failed error following that page.

### ISSUE THREAD

**Issue by fedeoo** [dotnet/AspNetCore.Docs#21612]
[Enter feedback here]

I got this error saying Scaffolding failed. when running cmd `dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries` on [this step](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio-code#scaffold-movie-pages-1)

Finally, I come to this page https://github.com/dotnet/Scaffolding/issues/1388 and it turns out I need to downgrade `dotnet-aspnet-codegenerator` to `3.1.3` 

Hopefully, it could help to improve this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks. Can you try .NET 5?

**Comment by fedeoo** [comment]
We're using .NET 3.1 as it's in LTS.

**Comment by fedeoo** [comment]
Far be it from me to criticize, Just hope the docs is user friendly. I think I know why it's so terrible.

**Comment by Rick-Anderson** [comment]
What OS?
