### ISSUE TITLE
Precision of instructions MapFallbackToFile -> MapFallbackToPage

### ISSUE THREAD

**Issue by stefanloerwald** [dotnet/AspNetCore.Docs#21613]
Hi @guardrex 

There's a tiny imprecision in the "Prerender and integrate ASP.NET Core Razor components" article for blazor wasm, that made me stumble this morning.

It says under step 5:

> Change the fallback from the `index.html` page (`endpoints.MapFallbackToFile("index.html");`) to the `_Host.cshtml` page.

I took that rather literally and (even looking at the code block below) replaced `endpoints.MapFallbackToFile("index.html");` with `endpoints.MapFallbackToFile("/_Host");`, not `endpoints.MapFallbackToPath("/_Host");`.

This great article would be even better, if for step 5 it said:

> Change the fallback from the `index.html` file (`endpoints.MapFallbackToFile("index.html");`) to the `_Host.cshtml` path: `endpoints.MapFallbackToPath("/_Host");`.

Thanks
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329a19ef-fb46-1f6b-a734-fa1c1334b1e5
* Version Independent ID: 3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2
* Content: [Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/prerendering-and-integration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stefanloerwald ... I'll improve it with your suggestion, but `MapFallbackToPath` doesn't exist. AFAIK, it should be `MapFallbackToPage`.

**Comment by stefanloerwald** [comment]
That's how confused I got. Of course it's page. Thank you!
