### ISSUE TITLE
Known unepxected behavior with Internet Explorer?

### ISSUE THREAD

**Issue by avendel** [dotnet/AspNetCore.Docs#21618]
Internet Explorer is explicitly mentioned as not supported with SignalR. Smoke testing indicates that basic functionality seems to work, though.

Is the reason you are not supporting IE that you know of things that won't work, or that you don't want to take the cost of testing and dealing with IE quirks in the future?

It seems IE support was dropped from the documentation with a [commit](https://github.com/dotnet/AspNetCore.Docs/commit/c6ad4fbe88a6211a9fa50c02696798398effc823#diff-46981e07c501d40216198dc1bbaa56d8fed881f537e51e19d62134b961eee2f1) related to Blazor, and further clarified in #21263 with [this commit](https://github.com/dotnet/AspNetCore.Docs/commit/3ed8d58f5c285f8750bb1b54a5de08b2feca0f47#diff-46981e07c501d40216198dc1bbaa56d8fed881f537e51e19d62134b961eee2f1).

Is the problem only with Blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-3.1#javascript-client)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @avendel ... I don't recall outside of the Blazor announcement and perhaps something that I either found in the product unit issues, one of Dan's blog posts, or was told over email.

If you have a question about the support policy, it's best to ask the product unit directly. I don't think we have any further information here.

https://github.com/dotnet/aspnetcore/issues
