### ISSUE TITLE
How to configure AuthorizationMessageHandler after WebAssembly app is started?

### ISSUE THREAD

**Issue by KanaHayama** [dotnet/AspNetCore.Docs#21617]
I want to add several additional authorized URLs to my custom AuthorizationMessageHandler after webassembly app is started.
Such as I want to attach access token to API servers loaded from a web API call.
How can I achieve that?

In the constructor of custom AuthorizationMessageHandler, I tried to load additional URLs saved somewhere, and create named HttpClient by using IHttpClientFactory. This approach doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KanaHayama ... That scenario didn't come up in the time that we've had these topics in the doc set. Ask the product unit engineers on their repo at ...

https://github.com/dotnet/aspnetcore/issues

... please add a `cc: @guardrex` to your opening comment and a cross-link to this docs issue (`https://github.com/dotnet/AspNetCore.Docs/issues/21617`). If they provide guidance that I can add to the topic, I'll re-open this issue and update the topic.
