### ISSUE TITLE
Appear Image No Name When Run Command docker-compose up -d --build

### ISSUE THREAD

**Issue by manhhung94qn** [dotnet/AspNetCore.Docs#21625]
[Nhập phản hồi vào đây]
I has problem.
When i run `docker build -t test .` it works fine.
But i run `docker-compose run up -d -build`, a image no name appear each times run command, it has size up to 1.2Gb
This is content of Dockerfile
`
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /source

COPY *.sln .
COPY ./test.csproj ./
RUN ls
RUN dotnet restore
COPY . ./
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "test.dll"]
`

This is content of docker-compose.yml
`
version: "3.9"

services:
  web:
    build: .
    ports: 
      - 5218:80
      - 5219:443

`

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/vi-vn/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-3.1&source=docs)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #27141
