### ISSUE TITLE
Document changes to Blazor WASM debugging in VS Code

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#21627]
We've made some changes to debugging in Blazor WASM in VS Code. We now require that users install the [debugging extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion) alongside the C# extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@captainsafia ... "We now require" ... what release version(s) does the requirement apply to?

**Comment by captainsafia** [comment]
Yep -- this affects all versions of VS Code and Blazor.

**Comment by guardrex** [comment]
Thanks ... I'll get this on a PR first thing tomorrow (Friday) morning and ping u for review.
