### ISSUE TITLE
Need implementation notes

### ISSUE THREAD

**Issue by rachmann** [dotnet/AspNetCore.Docs#21629]
When implementing a View Component, note that the VC model is not the same as the main page model.

For saving data, ensure the VC model has a member with the identical naming of the parent model member.
For loading an 'Edit' view, you must pass the existing member value to the VC when calling the Invoke, or InvokeAsync members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
