### ISSUE TITLE
錯誤文字

### ISSUE THREAD

**Issue by cai30304** [dotnet/AspNetCore.Docs#21638]
translated
Customize the [details] page paragraph
https://docs.microsoft.com/zh-tw/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0#customize-the-details-page

In the section
of Controllers/StudentsController.cs, the action method of the [Details] view will use the SingleOrDefaultAsync method to retrieve a single Student entity.

The SingleOrDefaultAsync error here should be FirstOrDefaultAsync

----
Original

在自訂 [詳細資料] 頁面段落

https://docs.microsoft.com/zh-tw/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0#customize-the-details-page

其中一段
在 Controllers/StudentsController.cs 中，[詳細資料] 檢視的動作方法會使用 SingleOrDefaultAsync 方法來擷取單一 Student 實體。

該處的SingleOrDefaultAsync錯誤 應該是 FirstOrDefaultAsync

---

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [教學課程：實行 CRUD 功能-使用 EF Core ASP.NET MVC](https://docs.microsoft.com/zh-tw/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/dotnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Add [Ways to read one entity](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-5.0#ways-to-read-one-entity)
