### ISSUE TITLE
Need link to Linux Distribution documentation

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/AspNetCore.Docs#21646]
The documentation for certificate installation on Linux simply reads to refer to the Distribution Documentation but does not provide a link to that documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#ssl-linux)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@csharpfritz  isn't that dependant on the distribution? We could list some examples. Do you have some links in mind?

**Comment by csharpfritz** [comment]
Totally agree that it is dependent on the distribution...  but there currently is no link to go to the distribution installation pages where some of that information might live.

This page is the page linked to by the .NET SDK when executing dotnet dev-certs on Linux

**Comment by Rick-Anderson** [comment]
> This page is the page linked to by the .NET SDK when executing dotnet dev-certs on Linux

Let's open an issue on the ***.NET SDK page that links to this page.***
