### ISSUE TITLE
the Sample can not work on Net 6 Preview.

### ISSUE THREAD

**Issue by hylinux** [dotnet/AspNetCore.Docs#21644]
I tried to working the sample code according the document, I found it work prefrect on Net 5. but it doesn't work on Net 6.

![image](https://user-images.githubusercontent.com/145199/109418490-96e4ce00-7a03-11eb-9e15-cf07f19495fd.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hylinux ... I haven't worked with .NET 6 bits yet. I tend to hold off until the first RC comes out, when things are stable enough to document. Open an issue with the product unit at ...

https://github.com/dotnet/aspnetcore/issues
