### ISSUE TITLE
AspNetCore Identity Custom Storage Provider Inquiry

### ISSUE THREAD

**Issue by spencer741** [dotnet/AspNetCore.Docs#21642]
#### Quoting the docs:

> Customize the user class
>
> When implementing a storage provider, create a user class which is equivalent to the IdentityUser class.
>
> At a minimum, your user class must include an Id and a UserName property.
>
> The IdentityUser class defines the properties that the UserManager calls when performing requested operations. The default type of the Id property is a string, but you can inherit from IdentityUser<TKey, TUserClaim, TUserRole, TUserLogin, TUserToken> and specify a different type. The framework expects the storage implementation to handle data type conversions.

#### My inquiry:
When implementing a [user class](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-5.0#customize-the-user-class), are there any AspNetCore functionalities that require the naming of the properties in my custom `ApplicationUser` class to be the same as in the `IdentityUser` class? Since I am implementing a custom UserStore:`IUserStore<ApplicationUser>` and thus providing custom getters and setters.. like 

` GetNormalizedEmailAsync(ApplicationUser user, CancellationToken cancellationToken)`
 or
`GetUserIdAsync(ApplicationUser user, CancellationToken cancellationToken)`)

... My properties in ApplicationUser don't have to conform to any other naming besides the properties of IdentityUser, right?

Apologies for the confusion.
Thanks for any insight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> My properties in ApplicationUser don't have to conform to any other naming besides the properties of IdentityUser, right?

Correct
