### ISSUE TITLE
Remove B&M for all versions

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21659]
See internal email. Subject: **Bundle and minify**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@Rick-Anderson ... What's the current recommended (perhaps 3rd party) tool for script minification ... if there is one? I ask because we're having to tell devs in a Blazor doc to minify a Google-hosted JS script in their app as a compile-time task. I'd like to recommend an approach to devs until Google fixes the problem, then I can drop it and just cross-link back to Google's minfied script.

**Comment by guardrex** [comment]
@wadepickett ... I took care of it [in a Blazor topic](https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly#compression) :point_up:, where B&M is temporarily mentioned as a workaround for a broken Google script that we cross-link.

**Comment by wadepickett** [comment]
I had removed mention of B&M back in April 2020, but then 2 months later it was put back in by another author.  I will remove it again.  I am also looking into putting WebOptimizer in its place for  an example.

**Comment by wadepickett** [comment]
@Rick-Anderson, I think I should remove the B&M  link and instructions from all versions of this topic rather than just >= 5.    The oldest .NET Core LTS release we have is 2.1. The bundleconfig.json file was removed from those project templates. Let me know if that doesn't sound right to you.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, I think I should remove the B&M link and instructions from all versions of this topic rather than just >= 5. The oldest .NET Core LTS release we have is 2.1. The bundleconfig.json file was removed from those project templates as Scott A. pointed out. Let me know if that doesn't sound right to you.

I'm fine as along as @scottaddie  agrees
