### ISSUE TITLE
"The conventions are based on the controller (ValuesController.cs) provided in the ASP.NET Core API project template."

### ISSUE THREAD

**Issue by cedwards-telis** [dotnet/AspNetCore.Docs#21655]
I can't find anywhere the (ValuesController.cs) provided in the ASP.NET Core API project template in .net 5.  have the templates been changed?

I'd rather have some documentation rather than "go look at some example code" in any case, especially when the example code is missing!  I have noticed by experiment that the name of parameters matter.   "id" will get conventions to apply buy "myId" will not.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-gb/aspnet/core/web-api/advanced/conventions?view=aspnetcore-5.0&WT.mc_id=dotnet-13135-bradyg)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@cedwards-telis thanks for letting us know. Since 3.0, it's now the `WeatherForecastController`. I hope to get this updated soon.

**Comment by cedwards-telis** [comment]
Hi Rick.  I don't see any examples of the api conventions on the .net 5 WeatherForecastController?

**Comment by pranavkm** [comment]
@Rick-Anderson it might help to simply have an example here. `WeatherForecastController` doesn't really have a GET / POST / PUT / DELETE pattern the way ValuesController did. If you scaffold a new controller in VS (`Add new Controller`), it follows this pattern. Perhaps we could simply paste it in?
