### ISSUE TITLE
Testing the Authorization example app - issue when seeding the DB

### ISSUE THREAD

**Issue by dharmatech** [dotnet/AspNetCore.Docs#21668]
# Issue

As described here:

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#the-starter-and-completed-app

I downloaded the repository zip file:

https://codeload.github.com/dotnet/AspNetCore.Docs/zip/master

I used the project in the following directory:

    AspNetCore.Docs-master\aspnetcore\security\authorization\secure-data\samples\final3

Then, following the steps here:

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#test-the-completed-app

here's the output I get after setting the user secrets and running the app:

```
PS C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3> dotnet user-secrets set SeedUserPW Secret123!
Successfully saved SeedUserPW = Secret123! to the secret store.
PS C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3> dotnet run
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
fail: ContactManager.Program[0]
      An error occurred seeding the DB.
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'password'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'password')
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at ContactManager.Data.SeedData.EnsureUser(IServiceProvider serviceProvider, String testUserPw, String UserName) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Data\SeedData.cs:line 49
   at ContactManager.Data.SeedData.Initialize(IServiceProvider serviceProvider, String testUserPw) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Data\SeedData.cs:line 26
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ContactManager.Program.Main(String[] args) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Program.cs:line 35
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

# Workaround

In case someone else runs into this issue, here's a workaround I used. Edit `Program.cs` as follows:

// EDIT UPDATE by @Rick-Anderson 
// insecure code redacted
     var testUserPw = config["SeedUserPW"];

After making this change, the program ran and I was able to test it according to the suggestions in the [Test the completed app](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#test-the-completed-app) section.

# Notes

SDKs that I have installed:

```
PS C:\Users\dharm> dotnet --list-sdks
3.1.200 [C:\Program Files\dotnet\sdk]
3.1.405 [C:\Program Files\dotnet\sdk]
5.0.101 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
```

Let me know if you'd like any other information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#test-the-completed-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Passwords should never be added to source code. Follow the instructions to set it securely with password manager.

**Comment by dharmatech** [comment]
@Rick-Anderson ,

In my explanation above, I show that I did set the password as directed:

```
PS C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3> dotnet user-secrets set SeedUserPW Secret123!
Successfully saved SeedUserPW = Secret123! to the secret store.
```

Is there something else we should be doing?

**Comment by Rick-Anderson** [comment]
I'll update the code to throw if fetching the password from config fails.

**Comment by Rick-Anderson** [comment]
@dharmatech  feel free to PR this or maybe @serpent5  wants it if you don't.

**Comment by Rick-Anderson** [comment]
@dharmatech  you should figure out why configuration is failing.

**Comment by dharmatech** [comment]
OK, some more info regarding the issue...

While in the project directory, I set the password:

    dotnet user-secrets set SeedUserPW Secret123!

If I run the program via `ctrl-f5` or `f5` in vscode, the program works fine! I.e. the database is seeded.

However, if I remove the database:

    sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "DROP DATABASE [aspnet-ContactManager-02]"

and then run the program directly from PowerShell:

    dotnet run

I get the error message I originally reported:

```
PS C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3> dotnet run
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\ContactManager.csproj]
fail: ContactManager.Program[0]
      An error occurred seeding the DB.
System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'password'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'password')
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user, String password)
   at ContactManager.Data.SeedData.EnsureUser(IServiceProvider serviceProvider, String testUserPw, String UserName) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Data\SeedData.cs:line 49
   at ContactManager.Data.SeedData.Initialize(IServiceProvider serviceProvider, String testUserPw) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Data\SeedData.cs:line 26
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ContactManager.Program.Main(String[] args) in C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3\Program.cs:line 35
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\dharm\Dropbox\Documents\VisualStudio\AspNetCoreDocsAuthorization\final3
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

Now, if I run the program once from vscode or VS in order to seed the database, then of course running the program via `dotnet run` in PowerShell works fine.

@Rick-Anderson, ever seen an issue like this before?

**Comment by dharmatech** [comment]
Here's a minimal test case:

```
cd C:\Temp

mkdir init-db-issue-new-app

cd init-db-issue-new-app

dotnet new webapp -o ContactManager -au Individual -uld

cd .\ContactManager

dotnet user-secrets set SeedUserPW abc

@"
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;

namespace ContactManager
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();
                               
            var config = host.Services.GetRequiredService<IConfiguration>();
        
            var testUserPw = config["SeedUserPW"];

            Console.WriteLine("{0}", testUserPw);
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}

"@ | Set-Content .\Program.cs

dotnet run # abc is displayed

mv .\Properties\launchSettings.json .\Properties\_launchSettings.json

dotnet run # abc is not displayed
```

This demonstrates that the secret is not retrieved if `Properties/launchSettings.json` does not exist.

**Comment by dharmatech** [comment]
> @dharmatech you should figure out why configuration is failing.

The password isn't being retrieved because `Properties/launchSettings.json` does not exist in this project:

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authorization/secure-data/samples/final3

See previous comments for details.

**Comment by dharmatech** [comment]
Should we just add `Properties/launchSettings.json` to `final3`?

Or do you feel it is time to remake the `final3` by going through the steps of the tutorial manually to ensure `final3` matches what's in the documentation?

**Comment by Rick-Anderson** [comment]
> Should we just add `Properties/launchSettings.json` to `final3`?

That has nothing to do with configuration.

**Comment by serpent5** [comment]
@dharmatech `launchSettings.json` sets `ASPNETCORE_ENVIRONMENT` to `Development`. Secrets are only loaded when it's set to `Development`, and it'll default to `Production`.

**Comment by dharmatech** [comment]
@serpent5

Aha! That's the issue! Thank you!!!

**Comment by dharmatech** [comment]
OK, so the tutorial:

[Create an ASP.NET Core web app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0)

in this section:

[The starter and completed app](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#the-starter-and-completed-app)

directs the user to test the completed app before going through the tutorial.

The section:

[Test the completed app](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#test-the-completed-app)

does not mention anything having the user set `ASPNETCORE_ENVIRONMENT` manually.

So two options I see for resolving this are:

- Add `Properties/launchSettings.json`. 

or

- Update the tutorial to instruct the user to set `ASPNETCORE_ENVIRONMENT` manually.

I'm in favor of the first option. Reason being, if the user goes through the manual steps of creating the project, they will end up with this file after the `dotnet new` step.
