### ISSUE TITLE
Pass along selected encoding

### ISSUE THREAD

**Issue by veloek** [dotnet/AspNetCore.Docs#21664]
The `selectedEncoding` argument to `WriteResponseBodyAsync` should be passed along to `Response.WriteAsync` in the example, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@veloek  where is it not being passed?

**Comment by veloek** [comment]
@Rick-Anderson it's not being passed when writing the response. I made a PR with the code change: #21669.
