### ISSUE TITLE
SupportsGet properties values not change when navigating between pages

### ISSUE THREAD

**Issue by Kawthar-Ebrahim** [dotnet/AspNetCore.Docs#21676]
I have built a search razor page using ASP.NET Core following [Microsoft Documentation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-5.0) exactly. The search is working as expected on my page but I am facing an issue in the following scenario:
- I searched for a first value and the result appeared. 
- I searched for a second value.
- When going back to the previous page "the first value search result" by browser back button, all the data displayed successfully except the search value which is a Model property that is defined that way same as the example in the Microsoft documentation.
`[BindProperty(SupportsGet = true)]
 public string searchValue { get; set; }
`  
The query string is changed and all the search results refreshed except that value which is confusing.
Appreciate any help.

**Comment by guardrex** [comment]
Hello @Kawthar-Ebrahim ...

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
