### ISSUE TITLE
Especify the nugget version for Microsoft.AspNetCore.Authentication.JwtBearer depending of your Net Core Version.

### ISSUE THREAD

**Issue by elcaytuiro** [dotnet/AspNetCore.Docs#21674]
[Please especify if you are using Net Core 3.1 , you should use Microsoft.AspNetCore.Authentication.JwtBearer 3.1.1]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @elcaytuiro ... We can't do that without explicit text in each topic for each set of versioned content, which would generate a *massive amount of work* 😅 for us. We do sometimes call out specific package versions, but it's more likely to be seen in our *Migration* topics. We rely on devs to make sure that they're using the correct versions of packages for the TFM of their app (and rely on roll-forward behavior for patch releases).
