### ISSUE TITLE
Problem with the statement around the "?"

### ISSUE THREAD

**Issue by artman-shane** [dotnet/AspNetCore.Docs#21680]
In the section discussing the passing of a parameter, there is a statement:

> In the preceding URL:
> 
>     The third URL segment matched the route parameter id.
>     The Welcome method contains a parameter id that matched the URL template in the MapControllerRoute method.
>     **The trailing ? (in id?) indicates the id parameter is optional.**

I do not believe that this is the case in this statement. It is my belief that this specific "?" is a separator and indicates that a query is following as stated in a previous comment just prior to this section.

It is the immediate following statement that talks about the Startup.cs with the {ID?} that refers to the optional inclusion of a parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not correct. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing

**Comment by Rick-Anderson** [comment]
Actually, there is no `id`
I was looking at the wrong partition of the doc.

**Comment by artman-shane** [comment]
I was assuming that the id was replaced with the “3” and thus the 3?... so the ? Would not be a separator?

Please forgive the typos, I am sending from my iPhone


Shane

**Comment by Rick-Anderson** [comment]
Yes, `?` is the query string separator.
