### ISSUE TITLE
UseStatusCodePagesWithReExecute: request is re-executed with the same HTTP method (not converted to GET)

### ISSUE THREAD

**Issue by metoule** [dotnet/AspNetCore.Docs#21696]
In the `UseStatusCodePagesWithReExecute` section, could you emphasize that the request is re-executed *with the same HTTP method*? And thus that the chosen endpoint must support all the HTTP methods? For years I couldn't understand why all errors were converted to 405 errors, until I realized that my error endpoint only supports the GET method. Any POST request is re-executed with the POST method, and thus the endpoint can't process it, resulting in an error 405..

Example:

`app.UseStatusCodePagesWithReExecute("/Error/{0}");`

````c#
[Route("[controller]")]
public class ErrorController : Controller
{
  [HttpGet("{statusCode:int?}")] // <-- must be changed to Route
  public IActionResult Index([FromRoute] int statusCode = 500)
  {
    return View();
  }
}
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JamesNK who can review this?

**Comment by serpent5** [comment]
@Rick-Anderson I believe this is similar to what happens with `UseExceptionHandler`. There's a note in the topic for _that_ [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-3.1#exception-handler-page-1):

> Don't mark the error handler action method with HTTP method attributes, such as `HttpGet`. Explicit verbs prevent some requests from reaching the method. Allow anonymous access to the method if unauthenticated users should see the error view.

I think the same note applies for `UseStatusCodePagesWithReExecute`.

**Comment by JamesNK** [comment]
@Tratcher Are you fimilar with `UseStatusCodePagesWithReExecute` middleware? Do you know the answer here?

**Comment by Tratcher** [comment]
Yes this functions the same as UseExceptionHandler, and should get a similar notice.

**Comment by Rick-Anderson** [comment]
@Tratcher  since you've commented, do you want to review #21719
