### ISSUE TITLE
Suggest splitting the page and changing the title

### ISSUE THREAD

**Issue by MarkStega** [dotnet/AspNetCore.Docs#21698]
Much of the content is generally applicable to Blazor on both server & wasm. I'd suggest renaming the page and adding two 'breakouts' at the bottom, one server specific, one wasm. The content is too good to 'hide' under webassembly best practices. It really should be 'Blazor performance best practices'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679bec37-eb9b-8092-5b99-118e4f2eb1a1
* Version Independent ID: 710987ea-42fb-1306-5750-ff8956907748
* Content: [ASP.NET Core Blazor WebAssembly performance best practices](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/webassembly-performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @pranavkm
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MarkStega ... We use a docs feature called "pivots" for that setup. An example can be seen in the [Blazor DI topic](https://docs.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0&pivots=webassembly). This topic is coming up for a UE ("user experience," i.e. topic overhaul) pass on https://github.com/dotnet/AspNetCore.Docs/issues/19286. I've marked this issue on my tracking issue, so it won't get lost. Thanks for the feedback.
