### ISSUE TITLE
An update on Many-To-Many parts is needed

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#21707]
Dear .NET guys,

As the current release of EF Core has had many-to-many support without a joint table, this tutorial should have been updated accordingly. 

In addition, I think updating the tutorial thoroughly will be necessary to adopt the newest features in both C#, Asp.net Core and EF Core. 

Thank  you for your attention.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See **** #21576
