### ISSUE TITLE
Compile time issue with provided sample code on page. 

### ISSUE THREAD

**Issue by qudooschaudhry** [dotnet/AspNetCore.Docs#21715]
the following code sample at this url https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio#change-the-email-token-lifespan does not compile and I get this error 

'DataProtectorTokenProvider<TUser>' does not contain a constructor that takes 3 arguments. If I remove the logger, it works however,  identity crashes at runtime.

```
public class CustomEmailConfirmationTokenProvider<TUser>
                                       : DataProtectorTokenProvider<TUser> where TUser : class
{
    public CustomEmailConfirmationTokenProvider(IDataProtectionProvider dataProtectionProvider,
        IOptions<EmailConfirmationTokenProviderOptions> options,
        ILogger<DataProtectorTokenProvider<TUser>> logger)
                                          : base(dataProtectionProvider, options, logger)
    {

    }
}
public class EmailConfirmationTokenProviderOptions : DataProtectionTokenProviderOptions
{
    public EmailConfirmationTokenProviderOptions()
    {
        Name = "EmailDataProtectorTokenProvider";
        TokenLifespan = TimeSpan.FromHours(4);
    }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by qudooschaudhry** [comment]
Is there any update on this?

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authentication/accconfirm/sample/WebPWrecover30 for a working sample

**Comment by qudooschaudhry** [comment]
But this sample is for .net core 3.0 and the document I referenced was for .net 5.0
