### ISSUE TITLE
Doc says [ProducesResponseType] are not necessary for ActionResult<T>, yet the examples include them.

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#21711]
If they arent needed, they should be removed from that example set. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
Can you show where it says that `ProducesResponseType` isn't needed? All I can find is this, where it states that only the `Type` property isn't needed:

> The [ProducesResponseType] attribute's Type property can be excluded. For example, [ProducesResponseType(200, Type = typeof(Product))] is simplified to [ProducesResponseType(200)].

I see only one example in the topic that shows `ProducesResponseType` with the `Type` property, but this is `IActionResult` and therefore required:

> ```csharp
> [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(Product))]
> [ProducesResponseType(StatusCodes.Status404NotFound)]
> public IActionResult GetById(int id)
> ```

**Comment by StingyJack** [comment]
No, I missed the Type following ProducesResponseType.
