### ISSUE TITLE
"Entity Framework Core with ASP.NET Core MVC" link points to Razor pages EF tutorial

### ISSUE THREAD

**Issue by casualc0der** [dotnet/AspNetCore.Docs#21710]
# Issue description

On the main [docs](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-5.0) page the "Entity Framework Core with ASP.NET Core MVC" link points to Razor pages EF tutorial. As this is the main docs page, there is no option to edit and open a PR directly i'm afraid 

I guess the link path is intentional as the preferred method for new development is Razor pages, but opened this issue for discussion.

I think it may be more beneficial to maintain the link to the MVC tutorial, and then direct the user with a prominent banner on the MVC overview that they should prefer Razor pages? 

Otherwise it is confusing for the user that they have been directed to the Razor pages tutorial 🤔 

![Screenshot 2021-03-07 at 16 17 26](https://user-images.githubusercontent.com/42304980/110246721-9fd42300-7f60-11eb-9649-c3d2e8e3fe09.png)

**Comment by Rick-Anderson** [comment]
@wadepickett  can you fix this?
