### ISSUE TITLE
How do you do this with AD authentication for Blazor WASM?

### ISSUE THREAD

**Issue by pallu** [dotnet/AspNetCore.Docs#21717]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329a19ef-fb46-1f6b-a734-fa1c1334b1e5
* Version Independent ID: 3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2
* Content: [Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/components/prerendering-and-integration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pallu ... See this for more info ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#support-prerendering-with-authentication

... and leave this issue open. I'll cross-link that section from this topic. This issue will close automatically when the PR merges.
