### ISSUE TITLE
Details for SignalR configuration with Blazor

### ISSUE THREAD

**Issue by ErikApption** [dotnet/AspNetCore.Docs#21723]
Any chances to get more details about the SignalR configuration for Blazor & Azure? I realize Visual Studio has some templates to do that but without the wizard, it is not clear on how to:
- configure asp net core/blazor to use a separate signalr service;
- how to validate the blazor configuration with a separate signalr service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ErikApption ... I'm not sure that there's anything in particular to document for your first ask. BTW if you didn't see it, there's a tutorial with bare bones guidance at ...

https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=webassembly

WRT the 2nd point, I'm not familiar with the scenario.

Let's ask @BrennanConroy to advise.

**Comment by ErikApption** [comment]
@guardrex Thanks - I've seen that tutorial but are the same configuration settings applicable to blazor server? Because I suspect it is a different setup. Somewhere in there, there should be a reference to the signalr hub that lets the js bootstrap code connects to the signalr service hub instead of the built-in one in App Service.  Also that tutorial leverages SignalR for the app itself not for the blazor backend, so seems a different scenario... Also it would be nice to have couple points to help debug the signalR connection. We have done all the steps from the tutorial with Blazor Server (asp.net 5.0) but it is unclear if the external hub is used or not...

**Comment by guardrex** [comment]
I'll defer to @BrennanConroy. I don't want to misspeak, but a Blazor Server app is just an ASP.NET Core app. It's SignalR bits (I thought) are the same as for any SignalR ASP.NET Core-based app, so the main docs apply, including even troubleshooting the connection doc at https://docs.microsoft.com/aspnet/core/signalr/troubleshoot.

**Comment by BrennanConroy** [comment]
> there should be a reference to the signalr hub that lets the js bootstrap code connects to the signalr service hub instead of the built-in one in App Service

The "signalr service hub" and the "built-in-one" are the same. Client code does not change when adding the SignalR Service.

I agree with everything @guardrex has said.

**Comment by guardrex** [comment]
I'll take a look at expanding the first few lines of ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=server

... to clarify basic concepts. The current remarks *imply* what we've been discussing. I think an added sentence or two can clarify the concepts.

Leave this issue open @ErikApption. It will close automatically when the PR merges later.

**Comment by ErikApption** [comment]
@BrennanConroy one detail that puzzles me... in a "standard" signalr, lets say a JS client will connect to the signalr hub - the js client would know the details of the hub. Whereas with blazor server, my understanding is that there is a handshake between the browser (bootstrap blazor.server.js code) and the server, that is performed in the startup to figure out the protocol (and I assume the server will send the connection details used for the signalr hub assuming that this protocol is selected). The doc says "On the client, the blazor.server.js script establishes the SignalR connection with the server"

So in this case - wouldn't the server need to know the details of the signalr hub (that the client will need to use) and if so, where is that configured? and how do I know if the blazor.server.js connects to the hub configured above?

**Comment by ErikApption** [comment]
@BrennanConroy thank you! That's exactly the info I was looking for - any chances you could throw a line or two about `MapBlazorHub` in the docs? So my only remaining question is how can I validate what is configured for `MapBlazorHub`

**Comment by BrennanConroy** [comment]
> I have a hub configured in my appconfig.json

Not sure what that means, hubs are configured in your Startup class.

If you're wanting to get the list of endpoints in your app so you can run "validation" on them, I don't think there are any docs on that currently.

It looks like you can grab `IOptions<RouteOptions>` from DI after `UseEndpoint` to get all the routing information, including the endpoints.
