### ISSUE TITLE
In the table Feature distribution - what does version 2.1.0 mean? Is it SignalR version or .NET Core version?

### ISSUE THREAD

**Issue by gintarasg** [dotnet/AspNetCore.Docs#21729]
In the table Feature distribution - what does version 2.1.0 mean? Is it SignalR version or .NET Core version?
According to the first table, SignalR versions are: 1.0.x, 1.1.x, 3.x or higher. So there's 2.1.0 SignalR version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c888abac-0b7a-6529-e3a9-dc43ca14ffce
* Version Independent ID: 08a0cb80-db1e-0ca5-abd7-9bfc3a28b01e
* Content: [ASP.NET Core SignalR clients](https://docs.microsoft.com/en-us/aspnet/core/signalr/client-features?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/client-features.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/signalr/client-features.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
That entire section and page is specific to Core. SignalR for .NET Framework docs are here: https://docs.microsoft.com/en-us/aspnet/signalr/
