### ISSUE TITLE
This Tutorial doesn't work at all

### ISSUE THREAD

**Issue by mhakim-bim** [dotnet/AspNetCore.Docs#21726]
[Enter feedback here]

i have tried step by step walkthrough and got to dead end,
so I had to manually add string (hardcoded)  to the bookService.

please fix this issue
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
@mhakim-bim Can you please describe the issue you are facing? Is it with the configuration strings?

**Comment by Rick-Anderson** [comment]
Configuration hasn't changed. If you're having trouble with configuration, see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration
See [dup issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=%2283a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a%22+is%3Aopen)
