### ISSUE TITLE
UserCors has to be at top of the Configure method

### ISSUE THREAD

**Issue by mauriciogracia** [dotnet/AspNetCore.Docs#21735]
After following the Enable Cross-Origin Requests (CORS) in ASP.NET Core and struggling with a CORS error for hours
the problem was fixed by calling the app.UseCors() at the very top of the Configure method in the Startup.cs

This dos not match what is documented and if I'm correct, updating the docs can save precious hours for other developers

This is the details of the issue I was having, and how it was solved
https://stackoverflow.com/questions/66557715/cross-origin-request-blocked-between-angular-frontend-and-webapi-net-core-5-0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mauriciogracia ... Rick will be on a little later to assist. I just want to mention in passing that there's CORS Middleware ordering info in the [*Middleware* topic (*Middleware order* section)](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order) that is cross-linked in this topic. However ...

* The cross-link is possibly buried a bit, not in the *Enable CORS* section or *Additional resources* section here.
* There's no mention here of ...

  > UseCors, UseAuthentication, and UseAuthorization must go in the order shown.

  ... with the "order shown" and that remark explained by the *Middleware* topic. That bit isn't here.

**Comment by Rick-Anderson** [comment]
> he problem was fixed by calling the app.UseCors() at the very top of the Configure method in the Startup.cs

@mauriciogracia  that's not correct.

The document has the code in the correct order. The code in the document is running at https://cors3.azurewebsites.net/ and it works.

**Comment by mauriciogracia** [comment]
I guess the Middleware sections are the ones that mention the UseCors() in other places, and I got confused because of that, thanks for updating the document.

Next time feel free to ask the person who open the ticket instead of answering with "that is not correct"
