### ISSUE TITLE
Package dotnet-aspnet-codegenerator 5.0.2 is not compatible with netcoreapp3.1

### ISSUE THREAD

**Issue by jeffDX619** [dotnet/AspNetCore.Docs#21730]
When I tried to run the command 

> dotnet tool install --global dotnet-aspnet-codegenerator

received the below error in terminal.

![image](https://user-images.githubusercontent.com/56828393/110514524-643a8400-812d-11eb-89d1-a4b7115ab67a.png)

I am using .Net Core version 3.1 as suggested in the document. But why I am getting the error

> error NU1202: Package dotnet-aspnet-codegenerator 5.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package dotnet-aspnet-codegenerator 5.0.2 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?tabs=visual-studio-code&view=aspnetcore-3.1#overview-1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's a great error. You need to use global.json to specify version 3.1 if that's what you want.

**Comment by Rick-Anderson** [comment]
The default document version is 5.0 and that's what you should be using.
