### ISSUE TITLE
The significance of accessTokenAcceptedVersion attribute should be mentioned

### ISSUE THREAD

**Issue by acatuttle** [dotnet/AspNetCore.Docs#21741]
The template generates an `appsettings.json` with `"Authority": "https://login.microsoftonline.com/{TENANT ID}"`, which I interpret as implying that v2.0 endpoints will be used? I believe that the instructions should mention that you need to open the Manifest Blade for your Application Registration in Azure AD and make sure that [accessTokenAcceptedVersion](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute) has the correct value with respect to the endpoint version you are intending to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b9c5cb-0e48-25bc-2b7e-e7354bafbe2d
* Version Independent ID: b1e8aedc-b46b-41f1-55c1-e293bc6c93db
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @acatuttle ... The version of the token and the version of the endpoint aren't the same thing.

WRT the token version ...

> v1.0 for Azure AD-only apps, and v2.0 for apps that support consumer accounts

WRT versions generally ...

> The Microsoft identity platform supports issuing any token version from any version endpoint - they are not related.

Cross-reference: https://docs.microsoft.com/azure/active-directory/develop/access-tokens

AFAIK, the **_token version_** is v1.0 (from experience ... all of my test apps have the attribute set to `null`, which defaults to v1.0). While the **_endpoints_** are v2.0 for >=5.0 docs that all use MS Identity v2.0, we're using v1.0 **_tokens_**. I even tried a test with one of my apps setting the attribute to `2`, and it 💥 on me trying to use the access token.

Given that this is the default and that Azure docs cover it ... and that we cross-link the Azure docs ... I'm going to leave things as they are for now. If more devs hit a problem, then we'll do something with our docs. We kind'a don't want to load our topics with Azure coverage. It's better for us to cross-link their docs and let their docs cover the juicy details. Thanks tho for raising this issue ... I will keep an :ear: open for more feedback on this point.

One thing tho regarding the link to this particular Azure doc. I **_do_** want that one cross-linked into our AD/B2C coverage docs as an additional resource. It's quite a good doc. I've marked your issue on my tracking issue to make sure that the cross-link is present.
