### ISSUE TITLE
Multiple Blazor WebAssembly apps - Using authentication 

### ISSUE THREAD

**Issue by tesar-tech** [dotnet/AspNetCore.Docs#21745]
I followed [this](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#hosted-deployment-with-multiple-blazor-webassembly-apps) document. 

Multiple apps work, but very poorly with authentication option (this settings from vs) :
![image](https://user-images.githubusercontent.com/33880579/110673067-9e109680-81d0-11eb-9ac3-4bf86042ac3e.png)

I had to add few options to make it work. 

First of all. When trying to login, the urls are wrong. They are "redirected" to `FirstApp/Identity/Account/Login` . This url is processed by server part and there is nothing with ` FirstApp` . 

Next problem came with login and calling `https://localhost:5001/.well-known/openid-configuration`, basically the same problem (throws error ` There was an error trying to log you in: 'Invalid response Content-Type: text/html, from URL: https://localhost:5001/.well-known/openid-configuration'` ). 

I fixed that with `if` inside `Use`  : 

```csharp
app.MapWhen(ctx => ctx.Request.Host.Port == 5001 ||
ctx.Request.Host.Equals("firstapp.com"), first =>
{
    first.Use((ctx, nxt) =>
    {
        if(!ctx.Request.Path.Value.Contains("Identity") && !ctx.Request.Path.Value.Contains("openid-configuration")
        && !ctx.Request.Path.Value.Contains("connect"))
        ctx.Request.Path = "/FirstApp" + ctx.Request.Path;
        return nxt();
    });
//other config...
```

It works, but doesn't feel right. Is there another way how to config authentication? If not, consider mentioning my workaround in docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#hosted-deployment-with-multiple-blazor-webassembly-apps)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback @tesar-tech.

@javiercn @mkArtakMSFT ... Should we explore updating/improving our guidance for multiple apps ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#hosted-deployment-with-multiple-blazor-webassembly-apps

... for when authn/z is included in the scenario? If so, advise me on the approach (i.e., the answer to @tesar-tech's question on the best practices approach) and the priority for doing the doc work.

**Comment by javiercn** [comment]
I don't think it is a common scenario, we can only document so many things. We try to offer general guidance and examples for common scenarios, but we can't document all scenarios. At some point users need to be aware of how the system works and how to adapt it to suit their needs.

**Comment by guardrex** [comment]
Thanks @javiercn.

@tesar-tech We'll keep an :ear: open going forward. Now that you've placed this issue and it's attached to the topic, it will be easy for us and readers to find it later.
