### ISSUE TITLE
Apache X-Forwarded-Proto did not work (with letsencrypt)

### ISSUE THREAD

**Issue by the-s-a-m** [dotnet/AspNetCore.Docs#21740]
The configuration recommended:
`<VirtualHost *:*>
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>`

Did not work until I moved it into the specific virtual host tags: VirtualHost *:80 and VirtualHost *:443

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-3.1#configure-apache)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by guardrex** [comment]
Hello @the-s-a-m ...

Side ? ... I thought the quotes go around the whole expression, not the header name. Anyway ...

I see that wildcard usage (`*:*`) in one of their examples at https://httpd.apache.org/docs/2.4/vhosts/examples.html#proxy (although not specifically with `RequestHeader`).

Ping @shirhatti for a look. :eyes:

**Comment by shirhatti** [comment]
Based on my reading of the Apache docs:
- Multiple `<VirtualHost>` sections with matching are permissble
- Ordering should **not** matter

I don't have a repro environment handy to try this in.

@the-s-a-m Could you try re-ordering to see if that makes a difference?

Basically put the `<VirtualHost *:80>` section before the `<VirtualHost *:*>`



@guardrex 

> Side ? ... I thought the quotes go around the whole expression, not the header name. Anyway ...

As far as I can tell, both (`RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}` and `RequestHeader set "X-Forwarded-Proto" "expr=%{REQUEST_SCHEME}"`) are acceptable and regardless that doesn't seem to be the issue reported.

**Comment by shirhatti** [comment]
Fair enough 😄

**Comment by guardrex** [comment]
@the-s-a-m ... Response?

**Comment by the-s-a-m** [comment]
I still reccomend 
<VirtualHost *:80>
    ServerName xyz.ch
    ServerAlias www.xyz.ch

    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>

The reason for this is, if you create the virtual host and then later active letsencrypt with automated mv from 80 to 443 it wraps around the  <IfModule mod_ssl.c> header and completly misses out the <VirtualHost *:*> tag

**Comment by guardrex** [comment]
AFAICT, there's nothing technically wrong with the way that it's documented based on Apache docs. If that's a correct reading, your use case and problem should be reported to the Let's Encrypt folks for them to investigate and document. @shirhatti, do you concur?

**Comment by shirhatti** [comment]
> AFAICT, there's nothing technically wrong with the way that it's documented based on Apache docs.

That's my understanding.

**Comment by guardrex** [comment]
Thanks @the-s-a-m ... We're going to go with what we have. I recommend contacting the Let's Encrypt folks on it. It seems like they may need to address something on their side.
