### ISSUE TITLE
Remove TLS < 1.2 from examples, please.

### ISSUE THREAD

**Issue by NavitaireSecurity** [dotnet/AspNetCore.Docs#21743]
Per the CA/Browser forum (and many other authorities), TLS versions older than 1.2 are deprecated.  Those who copy/paste the current examples will end up with an obsolete configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @NavitaireSecurity.

Ping @shirhatti ... Removing `TLSv1.1` from `ssl_protocols` looks like it will do the trick.

**Comment by shirhatti** [comment]
👍🏾 on removing TLS 1.1

It might another pass to ensure all the suggested ciphers are still up to date.

**Comment by guardrex** [comment]
Thanks @shirhatti ... Sure thing. I'll do that, too.
