### ISSUE TITLE
Unresolved AddConfiguration

### ISSUE THREAD

**Issue by KevinBurton** [dotnet/AspNetCore.Docs#21756]
I tried these steps but when I add the configuration as specified Visual Studio gives me an error that ILoggingBuilder does not have a method AddConfiguration 

![image](https://user-images.githubusercontent.com/2643566/110804536-e1f1b300-8245-11eb-8e16-25ce614dc0d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7367a651-2b27-0a57-e7d0-95686cc97f1c
* Version Independent ID: 8c769648-728d-72ce-ebf6-2a06e5076aa2
* Content: [ASP.NET Core Blazor configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1#logging-configuration)
* Content Source: [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KevinBurton ... Please show the full `Program.cs` file.

**Comment by guardrex** [comment]
Nevermind ... I see what you mean. It looks like the 🧀 moved. All of the examples were tested.

I'll get back to you.

**Comment by guardrex** [comment]
Ok .... you didn't follow the opening sentence ...

> Add a package reference for Microsoft.Extensions.Logging.Configuration to the app's project file.

Leave this issue open. I can change that to make it much more obvious.

**Comment by KevinBurton** [comment]
Confirmation that the issues is resolved.
