### ISSUE TITLE
Using streams, seems to contradict itself in the last sentence, third bullet point from the top.

### ISSUE THREAD

**Issue by tylerwp** [dotnet/AspNetCore.Docs#21754]
"Avoid reading the incoming file stream directly into memory. For example, don't copy file bytes into a MemoryStream or read as a byte array. These approaches can result in performance and security problems, especially in Blazor Server. Instead, consider copying file bytes to an external store, such as a blob or a file on disk."

Seems to contradict itself in the last sentence. 
How can we avoid using a stream when copying to an external source when for example BlobContainerClient.UploadBlobAsync requires a stream?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the question @tylerwp.

Can you do a `new StreamReader(...)` and then use the `reader.BaseStream` in the `UploadBlobAsync`?

... and note that I'm just spitball'in here without looking in detail.

cc: @pranavkm

**Comment by tylerwp** [comment]
Thanks @guardrex 
gotcha,  but would still need to use OpenReadStream, not seeing any way around it with IBrowserFile. this would still be reading into memory right?
Here is using new StreamReader
```
async Task SaveFile(InputFileChangeEventArgs e)
    {

        IBrowserFile browserFile = await e.File.RequestImageFileAsync("image/jpg", 1000, 1000);

        //MemoryStream s = new MemoryStream();            
        //await browserFile.OpenReadStream().CopyToAsync(s);     

        StreamReader s = new StreamReader(browserFile.OpenReadStream());


        var blobContainerClient = new BlobContainerClient(storageConnectionString, container);
        await blobContainerClient.UploadBlobAsync(browserFile.Name, s.BaseStream);

    }

```

**Comment by guardrex** [comment]
I'm not a framework jockey, but @pranavkm 🏇 is 😄 ... I'll defer to him on the ✨ *Framework Magic*&trade; ✨ aspects.

AFAIK at the moment 🤔, we should call out using the `BaseStream` there as the best practice because it doesn't have the dev read **_directly into memory_**. Pranav will provide the full understanding and exact wording for the update.

Let's start with the following draft ...

> \* Avoid reading the incoming file stream directly into memory. For example, don't copy file bytes into a \<xref:System.IO.MemoryStream> or read as a byte array. These approaches can result in performance and security problems, especially in Blazor Server. Instead, consider copying file bytes to an external store, such as a blob or a file on disk. If you need access to a \<xref:System.IO.Stream>, use a \<xref:System.IO.StreamReader.BaseStream?displayProperty=nameWithType>.

**Comment by tylerwp** [comment]
Thanks! @guardrex Always love a magic show! 🎇 😆

**Comment by pranavkm** [comment]
```
async Task SaveFile(InputFileChangeEventArgs e)
    {

        IBrowserFile browserFile = await e.File.RequestImageFileAsync("image/jpg", 1000, 1000);

        var blobContainerClient = new BlobContainerClient(storageConnectionString, container);
        await blobContainerClient.UploadBlobAsync(browserFile.Name, browserFile.OpenReadStream());
    }
```

Something like this should be fine. The comment is meant to dissuade from doing things like:

```
var memoryStream = new();
browserFile.OpenReadStream().CopyToAsync(memoryStream);

or 
new StreamReader(browserFile.OpenReadStream()).ReadToEndAsync();
```

because both of those would allocate resources on the server.

**Comment by guardrex** [comment]
Thanks @pranavkm ... I'll get a PR up on this Friday morning 🌄.

**Comment by guardrex** [comment]
@pranavkm I should clarify with you (and in the topic perhaps) tho that we're talking client-side because our `FilesaveController` does it. We show ...

`Controllers/FilesaveController.cs:`

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

[ApiController]
[Route("[controller]")]
public class FilesaveController : ControllerBase
{
    private readonly IWebHostEnvironment env;
    private readonly ILogger<FilesaveController> logger;

    public FilesaveController(IWebHostEnvironment env, 
        ILogger<FilesaveController> logger)
    {
        this.env = env;
        this.logger = logger;
    }

    [HttpPost]
    public async Task<ActionResult<IList<UploadResult>>> PostFile(
        [FromForm] IEnumerable<IFormFile> files)
    {
        var maxAllowedFiles = 3;
        long maxFileSize = 1024 * 1024 * 15;
        var filesProcessed = 0;
        var resourcePath = new Uri($"{Request.Scheme}://{Request.Host}/");
        IList<UploadResult> uploadResults = new List<UploadResult>();

        foreach (var file in files)
        {
            var uploadResult = new UploadResult();
            string trustedFileNameForFileStorage;
            var untrustedFileName = file.FileName;
            uploadResult.FileName = untrustedFileName;
            var trustedFileNameForDisplay = 
                WebUtility.HtmlEncode(untrustedFileName);

            if (filesProcessed < maxAllowedFiles)
            {
                if (file.Length == 0)
                {
                    logger.LogInformation("{FileName} length is 0", 
                        trustedFileNameForDisplay);
                    uploadResult.ErrorCode = 1;
                }
                else if (file.Length > maxFileSize)
                {
                    logger.LogInformation("{FileName} of {Length} bytes is " +
                        "larger than the limit of {Limit} bytes", 
                        trustedFileNameForDisplay, file.Length, maxFileSize);
                    uploadResult.ErrorCode = 2;
                }
                else
                {
                    try
                    {
                        trustedFileNameForFileStorage = Path.GetRandomFileName();
                        var path = Path.Combine(env.ContentRootPath, 
                            env.EnvironmentName, "unsafe_uploads", 
                            trustedFileNameForFileStorage);
                        using MemoryStream ms = new();
                        await file.CopyToAsync(ms);
                        await System.IO.File.WriteAllBytesAsync(path, ms.ToArray());
                        logger.LogInformation("{FileName} saved at {Path}", 
                            trustedFileNameForDisplay, path);
                        uploadResult.Uploaded = true;
                        uploadResult.StoredFileName = trustedFileNameForFileStorage;
                    }
                    catch (IOException ex)
                    {
                        logger.LogError("{FileName} error on upload: {Message}", 
                            trustedFileNameForDisplay, ex.Message);
                        uploadResult.ErrorCode = 3;
                    }
                }

                filesProcessed++;
            }
            else
            {
                logger.LogInformation("{FileName} not uploaded because the " +
                    "request exceeded the allowed {Count} of files", 
                    trustedFileNameForDisplay, maxAllowedFiles);
                uploadResult.ErrorCode = 4;
            }

            uploadResults.Add(uploadResult);
        }

        return new CreatedResult(resourcePath, uploadResults);
    }
}
```

**Comment by guardrex** [comment]
I wonder if ...

```csharp
using MemoryStream ms = new();
await file.CopyToAsync(ms);
await System.IO.File.WriteAllBytesAsync(path, ms.ToArray());
```

... should be ...

```csharp
using FileStream fs = new FileStream(path, FileMode.Create);
await file.CopyToAsync(fs);
```

**Comment by guardrex** [comment]
From @M2r4Miller on https://github.com/dotnet/AspNetCore.Docs/issues/21803 ...

In Blazor Server, the following code works correctly ...

```csharp
MemoryStream ms = new MemoryStream();

...

var reader = new StreamReader(e.File.OpenReadStream());
await reader.BaseStream.CopyToAsync(ms);

...
```

Use the `MemoryStream (ms)` to access the file contents without error.

I found the `CopyToAsync` necessary in order to avoid synchronous file access errors, including Visual Studio crashing.

**Comment by guardrex** [comment]
**UPDATE**: Sorry for the delay on this one. I'll try to get to it ASAP, but I'm 🏃🏃🏃 on UE passes at the moment and for the next couple of weeks. With 6.0 content on the way within a few months, it's important to get as many UE passes done as possible. Once 6.0 content arrives in force, it probably won't be possible to work UE passes. WRT this issue, I'll try to reach it within a few weeks.

**Comment by guardrex** [comment]
@pranavkm ... In the Blazor *File Uploads* topic, I'm resolving the guidance for avoiding reading a file stream into memory with your guidance :point_up:. However for server-side controller code, we use a `MemoryStream` to save a file. We have ...

In `Controllers/FilesaveController.cs`:

```csharp
public async Task<ActionResult<IList<UploadResult>>> PostFile([FromForm] IEnumerable<IFormFile> files)
{
    ...
    foreach (var file in files)
    {
        ...
        using MemoryStream ms = new();
        await file.CopyToAsync(ms);
        await System.IO.File.WriteAllBytesAsync(path, ms.ToArray());
    }
}
```

Alternatively, I have the following working that seems improved (compact anyway) ...

```csharp
public async Task<ActionResult<IList<UploadResult>>> PostFile([FromForm] IEnumerable<IFormFile> files)
{
    ...
    foreach (var file in files)
    {
        ...
        using FileStream fs = new FileStream(path, FileMode.Create);
        await file.CopyToAsync(fs);
    }
}
```

What's the **_right way_** to go there?

@tylerwp ... I've reached the Blazor *File Uploads* topic for a UE ("user experience", i.e., total overhaul+update) pass. 🏃😅

I'm drafting the **_DON'T do this_** + examples and **_DO this_** + example from @pranavkm's remarks as something like ...

> In the following examples, `broswerFile` represents the uploaded file and implements \<xref:Microsoft.AspNetCore.Components.Forms.IBrowserFile>.
>
> &#x274C; NOT recommended:
>
> ```csharp
> var memoryStream = new();
> browserFile.OpenReadStream().CopyToAsync(memoryStream);
> ```
>
> &#x274C; NOT recommended:
>
> ```csharp
> var reader = new StreamReader(browserFile.OpenReadStream()).ReadToEndAsync();
> ```
>
> ✔️ Recommended:
>
> ```csharp
> var blobContainerClient = 
>     new BlobContainerClient(storageConnectionString, container);
> await blobContainerClient.UploadBlobAsync(
>     browserFile.Name, browserFile.OpenReadStream());
> ``` 

What I don't like is that the *Recommended* example is an Azure Blob Service example following the generic code in the *NOT recommended* examples. I'd like to place the **wrong** Azure example immediately above the **right** Azure example ... **_and_** keep those initial @pranavkm examples there.

Do you have your original code (or can you show) the not recommended `MemoryStream` matching approach for Azure Blob Storage? For example, were you using a `MemoryStream` with `UploadFromStreamAsync` somehow?

**Comment by guardrex** [comment]
For discussion using `StreamContent` ...

```razor
@page "/upload-files-1"

<h3>Upload Files</h3>

<p>
    <label>
        Max file size:
        <input type="number" @bind="maxSize" />
    </label>
</p>

<p>
    <label>
        Max allowed files:
        <input type="number" @bind="maxAllowedFiles" />
    </label>
</p>

<p>
    <label>
        Upload up to @maxAllowedFiles of up to @maxSize bytes:
        <InputFile OnChange="@LoadFiles" multiple />
    </label>
</p>

<p>@exceptionMessage</p>

@if (isLoading)
{
    <p>Loading...</p>
}

<ul>
    @foreach (var (file, content) in loadedFiles)
    {
        <li>
            <ul>
                <li>Name: @file.Name</li>
                <li>Last modified: @file.LastModified.ToString()</li>
                <li>Size (bytes): @file.Size</li>
                <li>Content type: @file.ContentType</li>
                <li>Content: @content</li>
            </ul>
        </li>
    }
</ul>

@code {
    private Dictionary<IBrowserFile, string> loadedFiles = new();
    private long maxSize = 1024 * 15;
    private int maxAllowedFiles = 3;
    private bool isLoading;
    string exceptionMessage;

    private async Task LoadFiles(InputFileChangeEventArgs e)
    {
        isLoading = true;
        loadedFiles.Clear();
        exceptionMessage = string.Empty;

        try
        {
            foreach (var file in e.GetMultipleFiles(maxAllowedFiles))
            {
                var fileContent = new StreamContent(file.OpenReadStream(maxSize));

                loadedFiles.Add(file, await fileContent.ReadAsStringAsync());
            }
        }
        catch (Exception ex)
        {
            exceptionMessage = ex.Message;
        }

        isLoading = false;
    }
}
```

**Comment by pranavkm** [comment]
* Using a FileStream would be preferable. Super minor nit:

```diff
- using FileStream fs = new FileStream(path, FileMode.Create);
+ await using FileStream fs = new FileStream(path, FileMode.Create);
```

* I like the good / bad pattern. It's very clear. 
* 
``` 
loadedFiles.Add(file, await fileContent.ReadAsStringAsync()); 
```
Seems like a bad idea. It's essentially a `StreamReader.ReadToEndAsync()` with more steps. Could you elaborate on what you're trying to do? The file could be binary (e.g. an image) and not meant to be displayed as text.

**Comment by guardrex** [comment]
Thanks @pranavkm ... The PR just went up at https://github.com/dotnet/AspNetCore.Docs/pull/22161. Hold off tho looking at the PR ... it's still very **_draft-ish_** at the moment. I'll take into account what you just remarked :point_up: on my next update to it.

I'll ping u from the PR tomorrow (Thursday) to discuss further. I've been working since 3:30am and hit a 🧠🔥 **_brain fry_** 🧠🔥😄.
