### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21751]
Do each PR in groups of 20 fixed links.
See https://ops.microsoft.com/#/repos/332f35cd-658d-4914-0f85-907e40ee89f0?tabName=brokenlinks

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks.  I get a 404 for the link provided above so something must have changed.  I looked around but I am not spotting anything that might fit what you were trying to point met to, but I just may not know where to look.  I am new to using that portal.  Could you provide an updated link or tell me where to look?  I tried searching around by repo but was not getting it.

**Comment by Rick-Anderson** [comment]
It's the broken links link on that portal.

**Comment by wadepickett** [comment]
Fixed for all documents back through version 2.0 of the docs with with #2307.   Looking through the 1.x docs it does not make sense to keep updating those, which should be archived at this point and replacement links often do not exist.  So closing this.  Reopen of someone does not agree priority-wise.

**Comment by Rick-Anderson** [comment]
Higher priority is deleting all content lower than 3.1
