### ISSUE TITLE
Missing steps for Blazor-WASM

### ISSUE THREAD

**Issue by alexclarkmusa** [dotnet/AspNetCore.Docs#21760]
The section for using grpc web client as part of a Blazor-WASM app is missing steps.  There's no instruction for how/where to add the .proto file for instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c13a1c7-4683-a9a5-9ab3-e28d4506af26
* Version Independent ID: ea3b00c8-8f09-c045-4641-dc3a0030d6e5
* Content: [Use gRPC in browser apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/browser.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/browser.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
@JamesNK, perhaps due to my lack of familarity with this gRPC+Blazor scenario, should I let you handle this one?

**Comment by JamesNK** [comment]
The instructions on this page are written with the assumation that you have already added the nessessary packages and proto files for basic gRPC, and they just talk about how to add gRPC-Web on top. Not every page can re-explain everything from scratch.

Add a link to https://docs.microsoft.com/en-us/aspnet/core/grpc/basics

**Comment by guardrex** [comment]
Will do :+1:.

**Comment by JamesNK** [comment]
Hmm, there are already links in the introduction to other pages with instructions on getting started.

**Comment by guardrex** [comment]
I won't be able to look until Friday morning, but feel free to close now if you think it's all good.

**Comment by guardrex** [comment]
I had a minute to look this evening. I see what you mean ... and there's a Blazor sample, too.

@alexclarkmusa ... Start earlier in the gRPC coverage than this topic.

@JamesNK ... You might want to consider as a long-range idea that I work from your guidance + your sample to create a gRPC-Blazor tutorial akin to the one we did for SignalR-Blazor. Just work it up to your current sample step-by-step but also include a Blazor Server experience. It takes a little while to create one tho. I still have a lot of UE pass work to do 🏃 + 6.0 content for Blazor is just starting to land now 🏃. I have a feel'in that it would take several months to get to it unless you/DR/Artak feel that it should be higher priority than UE passes. Anyway ... just tossing that out there as an idea.

**Comment by JamesNK** [comment]
I think this is fine for now. If there is more feedback that people are stuck on this then we can reconsider.
