### ISSUE TITLE
ProblemDetailsFactory

### ISSUE THREAD

**Issue by habibcs** [dotnet/AspNetCore.Docs#21767]
services.AddTransient<ProblemDetailsFactory, CustomProblemDetailsFactory>();

When this code is going to become public? .NET 5 patch level or its after 1 year to be disclosed in .NET6 release?

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#implement-problemdetailsfactory)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by pranavkm** [comment]
We do not intend to make the type public. Our recommendation is to copy the type in to your app, or use a DI container that [supports decorating](http://structuremap.github.io/interception-and-decorators) to wrap the framework implementation.
