### ISSUE TITLE
Add documentation for Blazor generic type cascading feature

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/AspNetCore.Docs#21769]
[EDIT by guardrex to add the metadata]

As of .NET 6 Preview 2, we're adding the ability for generic types to be inferred based on ancestor components. High-level info and motivation is at https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/#infer-component-generic-types-from-ancestor-components

This can be a fairly brief addition to the docs at https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-5.0. The key thing we need to document is that by adding `@attribute [CascadingTypeParameter(...)]` onto a component, the specified generic type argument will automatically be used by descendants that:

 * Are nested as child content for your component in the same `.razor` document
 * Also declare a `@typeparam` with the exact same name
 * Don't have any other value supplied or inferred for that type parameter. If they do, that takes precedence over the cascaded generic type.

When receiving a cascaded type parameter, components will obtain it from the *closest* ancestor that has a `[CascadingTypeParameter(...)]` with a matching name. In other words, the cascaded generic types parameters can be overridden within a particular subtree.

A caveat worth mentioning is that the matching is done purely by name. So it's not a good idea to cascade a generic type parameter with an excessively - ahem - *generic* name like `T`. If a developer opts into cascading a type parameter, they are implicitly promising that its name is unique enough not to clash with other cascaded type parameters from unrelated components.

Is this enough info? I'm happy to supply more details!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 698a8824-7a38-70d6-c041-0dca4c040217
* Version Independent ID: ae663e33-6a08-0b24-aa19-3fc3c9edccfc
* Content: [ASP.NET Core Blazor templated components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/templated-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/templated-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@SteveSandersonMS ... Can you provide the markup for the ellipses in the example?

**_Feel free to edit this comment directly ..._**

`Shared/Grid.razor`:

```razor
@typeparam TItem
@attribute [CascadingTypeParameter(nameof(TItem))]

...

@code {
    [Parameter]
    public IEnumerable<TItem> Items { get; set; }

    [Parameter]
    public RenderFragment ChildContent { get; set; }
}
```

`Shared/Column.razor`:

```razor
@typeparam TItem

...

@code {
    [Parameter]
    public string Title { get; set; }
}
```

**Comment by guardrex** [comment]
@SteveSandersonMS ... I've set up a prototype (using a `TItem="SaleRecord"` because I'm still on 5.x at this time). Is this about the direction the example should be heading? If so, I think I can take this forward to a PR with the mods for `CascadingTypeParameter`. **_Feel free to edit the prototype below directly._**

`Shared/Column.razor`:

```razor
@typeparam TItem

<th>@Title</th>

@code {
    [Parameter]
    public string Title { get; set; }
}
```

`Shared/Grid.razor`:

```razor
@typeparam TItem
<!-- @@attribute [CascadingTypeParameter(nameof(TItem))] -->

<table class="table">
    <thead>
        <tr>
            @HeaderTemplate
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Items)
        {
            <tr>
                @RowTemplate(item)
            </tr>
        }
    </tbody>
</table>

@code {
    [Parameter]
    public RenderFragment<TItem> RowTemplate { get; set; }

    [Parameter]
    public IEnumerable<TItem> Items { get; set; }

    [Parameter]
    public RenderFragment HeaderTemplate { get; set; }
}
```

`Pages/GenericCascadedType.razor`:

```razor
@page "/generic-cascaded-type"

<Grid Items="@GetSaleRecords()" Context="item">
    <HeaderTemplate>
        <Column TItem="SaleRecord" Title="Product name" />
        <Column TItem="SaleRecord" Title="Number of sales" />
    </HeaderTemplate>
    <RowTemplate>
        <td>@item.Name</td>
        <td>@item.Quantity</td>
    </RowTemplate>
</Grid>

@code {
    private IEnumerable<SaleRecord> GetSaleRecords()
    {
        return new List<SaleRecord>()
        {
            new SaleRecord() { Name = "Product 1", Quantity = 100 },
            new SaleRecord() { Name = "Product 2", Quantity = 200 },
            new SaleRecord() { Name = "Product 3", Quantity = 50 },
        };
    }

    private class SaleRecord
    {
        public string Name { get; set; }
        public int Quantity { get; set; }
    }
}
```

Result:

<img width="444" alt="Capture" src="https://user-images.githubusercontent.com/1622880/111304287-906d6d80-8623-11eb-97b9-4bb1f1ee622f.PNG">

```html
<table class="table">
    <thead>
        <tr>
            <th>Product name</th>
            <th>Number of sales</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Product 1</td>
            <td>100</td>
        </tr>
        <tr>
            <td>Product 2</td>
            <td>200</td>
        </tr>
        <tr>
            <td>Product 3</td>
            <td>50</td>
        </tr>
    </tbody>
</table>
```
