### ISSUE TITLE
Add blazor

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21765]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
What did you have in mind ... it's already present in three sections.

**Comment by guardrex** [comment]
@Rick-Anderson ... What would u like to do on this one? Blazor is already covered in three sections of the topic.

**Comment by Rick-Anderson** [comment]
@guardrex  I'll have you review it.

**Comment by guardrex** [comment]
Hi @Rick-Anderson ... I'm running down Blazor issues ... addressing/fixing things ... scheduling things. Is this one still on hold for work?
