### ISSUE TITLE
[Blazor] Add documentation for persisting prerendering state

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#21771]
Content to come

**Comment by guardrex** [comment]
Do u want me to base draft content on the blog post?

https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-2/#preserve-prerendered-state-in-blazor-apps

**Comment by javiercn** [comment]
@guardrex Give me a week so that I can give you content to put in there, we are doing a few API renames and want to provide some usage patterns
