### ISSUE TITLE
Add link to Project Code in GitHub

### ISSUE THREAD

**Issue by ppittle** [dotnet/AspNetCore.Docs#21774]
Tutorial is good as a step-by-step, but it would be nice to also link to a fully working solution for users that want to dive in any play with the code or need a sample app.

Or link to something similar:  
- https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-rp/intro/samples/cu50

Or link to a 3rd party:
- https://github.com/jbogard/ContosoUniversityDotNetCore-Pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ppittle  thanks for the suggestion. we've done that in the past but the code is built for the documentation rendering and is not very friendly to view. I'll try something like that in my RP update. See https://github.com/dotnet/AspNetCore.Docs/pull/21576

We don't like to maintain multiple versions. 

We've also found most customers who want to try the sample app don't want the complexity of the completed app, they prefer something before inheritance.

We typically don't link to 3rd party samples.

We'll reconsider this if we get enough interest.
