### ISSUE TITLE
The student's enrolled in a selected course needs a if (Model.Enrollments != null) block added

### ISSUE THREAD

**Issue by craigkehl** [dotnet/AspNetCore.Docs#21776]
The tutorial doesn't explain that on line 103, the following table is wrapped in a check for null expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What line? In the following?
```
<h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @item.Student.FullName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
            </tr>
        }
    </table>
}
``

**Comment by craigkehl** [comment]
Hi, Rick.
I am new to C# and ASP.NET Core. So forgive me if I missed something that is there in the tutorial.

Following the tutorial, I got a null reference error on Model.Enrollments. To get my code to work, I had to encase the code presented in the tutorial in:
@if (Model.Enrollments != null)
{
                Code….
}

After getting it to work, I checked it against the github repo. In the repo, you have that check. I just couldn’t find it in the tutorial. Coming from Node.JS, PHP and vanilla SQL, I am having a difficult time following MVC’s flow. It took a while before considering the solution might not be in the tutorial’s prompted code as in the screenshot below.

However, it might be cool in the tutorial to prompt: “See if you can see what needs to be added to the following code.” Once I got out of the box of blindly worshipping the tutorial, having thought I had to have mis-typed something if it didn’t work, I learned a lot more trying to debug it.
***@***.***D71763.7531D440]

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
