### ISSUE TITLE
Missing documentation about execution order of global ExceptionFilterAttributes

### ISSUE THREAD

**Issue by st-agnes** [dotnet/AspNetCore.Docs#21779]
Hi,

I have the following issue:

I'm using multiple global ExceptionFilters, each filter derives from `ExceptionFilterAttribute`. I'm registering my filters in the application startup logic like this:

```
            services.AddMvcCore(options =>
            {
                options.Filters.Add<OperationCancelledExceptionFilter>(3);
                options.Filters.Add<DataExceptionFilter>(2);
                options.Filters.Add<GameLogicExceptionFilter>(1);
                options.Filters.Add<UnexpectedExceptionFilter>(0);
            });
```

Calling this method:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.filters.filtercollection.add?view=aspnetcore-5.0#Microsoft_AspNetCore_Mvc_Filters_FilterCollection_Add__1_System_Int32_

I'd like my exception filters to be executed in the following order:
1. OperationCancelledExceptionFilter
2. DataExceptionFilter
3. GameLogicExceptionFilter
4. UnexpectedExceptionFilter

But in order to achieve this, I must register them with their sequence numbers reversed, as in the above code example (i.e. with `UnexpectedExceptionFilter `having the lowest sequence number, and so on). 

I can't find any documentation that says that this is the way it works. So it's not even clear if this is a bug or it's really intended to work this way: exception filters must be added to the `FilterCollection` with sequence numbers reflecting the reverse of the intended execution order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article

A filter with a lower Order value:

Runs the before code before that of a filter with a higher value of Order.
Runs the after code after that of a filter with a higher Order value.
