### ISSUE TITLE
Using .net5, the FromSQL produces an error

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#21783]
MS appears to have changed how this is called in the newer versions. 
https://docs.microsoft.com/en-us/ef/core/querying/raw-sql

I believe this line of code should be updated from using "FromSql" to "FromSqlRaw:

            string query = "SELECT * FROM Department WHERE DepartmentID = {0}";
            var department = await _context.Departments
                .FromSqlRaw(query, id)
                .Include(d => d.Administrator)
                .AsNoTracking()
                .FirstOrDefaultAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Container issue for EF/MVC #17465
