### ISSUE TITLE
Unable to update database using Entity Core Framework after migrations

### ISSUE THREAD

**Issue by adeisbright** [dotnet/AspNetCore.Docs#21780]
I tried updating my database after running migrations but got a System exception error.
This is the command I used : 
> dotnet ef database update 

This is the error message : 
> System.ArgumentException: Connection string keyword 'server' is not supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What environment? What version? What does the connection string look like.

The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by adeisbright** [comment]
I am running the tutorial on Windows 10.
This is a snapshot of the connection string : 
"Server=(localdb)\\mssqllocaldb;Database=RazorPagesMovieContext-236d8ba3-1734-471d-a757-143be5b60c2f;Trusted_Connection=True;MultipleActiveResultSets=true"

**Comment by adeisbright** [comment]
I will not say the tutorial is not working if I everything worked fine.
I checked Stackoverflow for answers before creating the issues here.
All what it pointed was some error connected to ADO.NET but none linked to the SystemException that was thrown.
I will gladly accept any help to fix the issue

**Comment by Rick-Anderson** [comment]
Exit/restart VS.

**Comment by procome** [comment]
The tutorial is mis-leading up to this point.
The development setting is using options.**UseSqlite** in Startup.cs, but the connection string in appsettings.json is using SqlServer format. 

change **SqlServer format**
"Server=(localdb)\mssqllocaldb;Database=RazorPagesMovieContext-236d8ba3-1734-471d-a757-143be5b60c2f;Trusted_Connection=True;MultipleActiveResultSets=true"

To
**SqlLit format:**
"ConnectionStrings": {
    "RazorPagesMovieContext": "Data Source=MvcMovie.db"
  }

**Comment by Rick-Anderson** [comment]
@wadepickett  please review

**Comment by Rick-Anderson** [comment]
> The tutorial is mis-leading up to this point.
> The development setting is using options.**UseSqlite** in Startup.cs, but the connection string in appsettings.json is using SqlServer format.

When you scaffold for SQLite, it generates the SQLite connection string.

**Comment by procome** [comment]
No idea. Follow the step of the tutorial,

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code

Adding this
 _if (Environment.IsDevelopment())
        {
            services.AddDbContext<RazorPagesMovieContext>(options =>
            options.UseSqlite(
                Configuration.GetConnectionString("RazorPagesMovieContext")));
        }
        else
        {
            services.AddDbContext<RazorPagesMovieContext>(options =>
            options.UseSqlServer(
                Configuration.GetConnectionString("MovieContext")));
        }_

Then run 
**dotnet ef migrations add InitialCreate
dotnet ef database update**

may duplicate the problem.

**Comment by Rick-Anderson** [comment]
[Use SQLite for development, SQL Server for production](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code#use-sqlite-for-development-sql-server-for-production) is exactly that, for deploying to production, not for this tutorial.

**Comment by Rick-Anderson** [comment]
@wadepickett 
`dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries`

Why are we using `-dc RazorPagesMovieContext` ? I think that's used when you specify the db context. In this case we want the scaffolder to generate it.

**Comment by Rick-Anderson** [comment]
@wadepickett  you're also missing 
`--useSqlite|-sqlite                 : Flag to specify if DbContext should use SQLite instead of SQL Server.`

This is a pri 0 bug.

**Comment by tsewaiho** [comment]
I know this framework two years ago. But I found no way to learn this framework at that time.
Today, I try to learn it again. And I already stucked at part two of the first tutorial due to this problem.
Why can the .NET ecosystem have a completable and enlightenment course? Like Laracasts from Laravel ecosystem.

**Comment by wadepickett** [comment]
@Rick-Anderson, I am on this one now.

You asked: "Why are we using -dc RazorPagesMovieContext ?"

I don't know actually, sorry.  You had _-dc RazorPagesMovieContext_ in your topic for updates to Model.md from 2018 to 2021.  On 4/2021 you still kept -"dc RazorPagesMovieContext" but added _-sqlite_"

2018-12 [Update model.md (#9947)](https://github.com/dotnet/AspNetCore.Docs/pull/9947)
_dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries_

2020-1 [Update model.md by Rick-Anderson · Pull Request #16588](https://github.com/dotnet/AspNetCore.Docs/pull/16588)
_dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries_

2021-4 [Update model.md (#22029)](https://github.com/dotnet/AspNetCore.Docs/pull/22029)
_dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite_

On this last one (#22029) you originally tried the following without -dc, but it didn’t work:
dotnet aspnet-codegenerator razorpage -m Movie -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite
… so you put the -dc RazorPagesMovieContext back in.  That is why it is there.

At the time you asked deepchoudhery for verification but I don't think we got a reply, he may have been out.

I am honestly not sure what the proper command is supposed to be for this case.  There is very little info available.   It seems like the scaffolding isn't working how we expect it to, I don't know how to get it to generate on its own if the dc is not specified in the command.

If you know exactly what it should be, please let me know.   If not, I will check with the developer on the intent. The command reference may also need to be updated.  Thanks for all the help.

**Comment by Rick-Anderson** [comment]
Instructions work fine as they are.
