### ISSUE TITLE
Debugger does not work, this page does not solve the problem

### ISSUE THREAD

**Issue by ddobric** [dotnet/AspNetCore.Docs#21785]
Debugger breakpoints do not hit in Blazor in some projects. Many people are complaining because of this issue. This page seems to provide a few interesting hints, but it does not really solve the problem.
Even more, if "JavaScript debugging" *recommended setting is configured, then the F5 does not start the project at all.

Thanks in advance
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1&tabs=visual-studio#troubleshoot)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ping @captainsafia

**Comment by captainsafia** [comment]
@ddobric If you're running into issues in VS, I would recommend reporting a bug via VS so we can get the appropriate logs to investigate. If you're running into issues in VS Code/standalone debugging, you can report it on the dotnet/aspnetcore issue page.

**Comment by guardrex** [comment]
THX @captainsafia 🎷 

@ddobric ... Here are the docs for that ...

* [**Report a Problem**](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio)
* [Visual Studio feedback options](https://docs.microsoft.com/visualstudio/ide/feedback-options)
