### ISSUE TITLE
Adding details about auto-increment and handling of arbitrary properties

### ISSUE THREAD

**Issue by david-haemmerle** [dotnet/AspNetCore.Docs#21792]
The tutorial is good overall but I noticed two things that are not explained there:
1. When I post a TodoItem then I do not have to specify a value for "id". It is automatically incremented. Why is that and which component handles the auto-increment? What requirements must an object or API fulfill to leverage the auto-increment funtionality?
2. The TodoItems API is able to handle the case when I post a JSON containing fields that are not defined in the TodoItems/TodoItemsDto object. For example, sending the request body
    ```
    {
      "name": "feed dog",
      "isComplete":true,
      "foo": "bar"
    }
    ````
returns HTTP 201 despite `TodoItem` not having a `Foo` property. Why is that and is there a way to define the response behavior automatically? For example, responding with a serialization exception or similar?

My suggestion for improvement is to add such details to the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> When I post a TodoItem then I do not have to specify a value for "id". It is automatically incremented. Why is that and which component handles the auto-increment? 

That's how DBs work and is beyond the scope of this tutorial.
