### ISSUE TITLE
Provide links for demo features missing in ASP.NET MVC

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#21791]
Is it possible to provide links for the points below?

> Some things the Razor Pages tutorial has that this one doesn't:
> 
>     Use Select method to load related data
>     Best practices for EF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d4c57d-4eb1-71fe-6587-b9967ad1b445
* Version Independent ID: 8f0488f1-adc0-b42c-9549-b4028d4317d6
* Content: [ASP.NET Core MVC with EF Core - tutorial series](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
