### ISSUE TITLE
Duplicate example with different resolved routes (copy/paste error?)

### ISSUE THREAD

**Issue by StefanJanssen95** [dotnet/AspNetCore.Docs#21793]
![image](https://user-images.githubusercontent.com/6250246/111120564-c94a0b80-856b-11eb-963e-61c065c7cdf6.png)

As seen in the above image the routes in the bottom two rows are the same, while they have a different resolved route. I think the last row should be:
`{controller=Products}/{action=Index}/{id?}` instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The doc is correct.
