### ISSUE TITLE
Regular Expression for Genre

### ISSUE THREAD

**Issue by smoore4moma** [dotnet/AspNetCore.Docs#21794]
The regular expression for Genre does not allow for spaces, however the examples includes "Romantic Comedy" which throws an error.  The RegEx should be `[RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Part 8, add validation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  also fix the MVC version

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan let me know if you're interested. Can you verify and fix in both places?

**Comment by fiyazbinhasan** [comment]
I did a fix for this a few days back. we can close this https://github.com/dotnet/AspNetCore.Docs/pull/22156

**Comment by Rick-Anderson** [comment]
Thanks!
