### ISSUE TITLE
development certificate is only available for the current active user

### ISSUE THREAD

**Issue by agilmore30** [dotnet/AspNetCore.Docs#21799]
You could improve this documentation by stating:

The development certificate is only available for the current active user. Windows Services run as a different user and the development certificate is not supported in that environment. You'll need to provide your own certificate configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik  should I add:

The development certificate is only available for the current user. Windows Services run as a different user and the development certificate is not supported in that environment.
