### ISSUE TITLE
InputFile clarification

### ISSUE THREAD

**Issue by M2r4Miller** [dotnet/AspNetCore.Docs#21803]
In Blazor Server, the following code works correctly
MemoryStream ms = new MemoryStream();
...
var reader = new StreamReader(e.File.OpenReadStream());
await reader.BaseStream.CopyToAsync(ms);
...

Use the MemoryStream (ms) to access the file contents without error.

I found the CopyToAsync necessary in order to avoid synchronous file access errors, including Visual Studio crashing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @M2r4Miller ... I'm tracking updates at https://github.com/dotnet/AspNetCore.Docs/issues/21754. I'll look closer at what you've posted :point_up: when I get back to that issue.

**Comment by M2r4Miller** [comment]
Thanks @guardrex. After I posted this I found #21754. 
My use case is reading an Excel spreadsheet into my Blazor Server app. I'm using the ClosedXML package which supports supplying a spreadsheet in a MemoryStream to process into a POCO list, so in my use case, I must read the entire file into memory.

BTW, when I was trying to get it to work, I repeatedly crashed VS2019 without errors, had to publish the site to a dev web server in order to get the browser to report an error to me.

**Comment by guardrex** [comment]
> BTW, when I was trying to get it to work, I repeatedly crashed VS2019 without errors, had to publish the site to a dev web server in order to get the browser to report an error to me.

I can't explain why that might happen. If that's easy to reproduce, I recommend opening an issue for the product unit to take a look. Give them exact steps to repro it, your code, your use case, and any logged errors that you find.

https://github.com/dotnet/aspnetcore/issues

**Comment by guardrex** [comment]
> ClosedXML package

... keeping in mind, of course, that they can't help you with that. If that's the cause ... somewhere in that package ... they can't and won't help.
