### ISSUE TITLE
Change example code from AddSingleton to AddScoped

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#21808]
In the example for a StateContainer, it shows this line of code:

`services.AddSingleton<StateContainer>();
`
I would like to suggest that this be changed to:

`
services.AddScoped<StateContainer>();
`

The demo will work until a second tab is open and clicks on the button to change the State.  An exception is thrown:
`
System.InvalidOperationException: 'The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.'
`
While this could be fixed, the point is that state is rarely going to be shared accoss an app (with a Singleton).  More likely it is going to be state for a user (circuit) . I know this is just a demo app, but thought I would bring it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @gregoryagu ... I agree, and I'll do that first thing in the morning. Thanks for the suggestion!

**Comment by TLA020** [comment]
Don't you want to have a singleton to persist the state in one instance? So you always get the right instance/state?
I suppose this can't be scoped..
