### ISSUE TITLE
Is it possible to specify another css file for isolation?

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#21800]
> file must reside in the same folder as the Example component

I am curious whether it is a hard convention, or is there a mechanism which lets me specify arbitrarily named css file with the styles to be used in isolation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @voroninp ... It's a hard convention. You can search the product unit repo issues to see if anyone has provided feedback on it. If there are no issues on it, you can open an issue to float your suggestions to the team.

https://github.com/dotnet/aspnetcore/issues
