### ISSUE TITLE
OnConnectedAsync() example needs adjustment

### ISSUE THREAD

**Issue by josbol** [dotnet/AspNetCore.Docs#21812]
[Enter feedback here]

The the last line of the example of OnConnectedAsync() should be the following:

"return base.OnConnectedAsync();"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
The sample has `await base.OnConnectedAsync();` which is equivalent.

Side note: the base method doesn't actually do anything so it doesn't matter if you call it.
