### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by MixaKonan** [dotnet/AspNetCore.Docs#21813]
The fifth section is now named "меморикачинтрйоптионс" in the Russian version of the page

Opened in https://github.com/dotnet/AspNetCore.Docs.ru-ru/issues/115

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Кэширование в памяти в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#memorycacheentryoptions)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs.ru-ru/blob/live/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I've had these reported to me, too ... these C#-ish named things in headings. This one is for `MemoryCacheEntryOptions` ...

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#memorycacheentryoptions

<img width="451" alt="Capture" src="https://user-images.githubusercontent.com/1622880/111523081-dfe99180-8728-11eb-8a3b-5dfb0caba719.PNG">

<img width="383" alt="Capture" src="https://user-images.githubusercontent.com/1622880/111523470-4cfd2700-8729-11eb-842b-2fd0722a884b.PNG">

... which translates to "memoricacintryoptions".

I've been code-fencing them per Jason's remark that he's cool with it. The bookmarks still work code fenced :tada:.

**Comment by Rick-Anderson** [comment]
@JasonCard  for the number being reported, I'm guessing there are a 1000 more unreported. Hopefully they can fix this bug soon.

**Comment by JasonCard** [comment]
@Rick-Anderson I totally understand and have requested to raise this issue again with our MT engine team.
