### ISSUE TITLE
Performance Considerations - Max Model Binding

### ISSUE THREAD

**Issue by jasontaylordev** [dotnet/AspNetCore.Docs#21818]
The following code:

```csharp
    int MyMaxModelBindingCollectionSize = 100;
    Int32.TryParse(Configuration["MyMaxModelBindingCollectionSize"],
                               out MyMaxModelBindingCollectionSize);
    
    services.Configure<MvcOptions>(options => 
           options.MaxModelBindingCollectionSize = MyMaxModelBindingCollectionSize);
```

Will result in `MaxModelBindingCollectionSize` set to 0 when configuration has not been added.

If the intention is to default to 100, implement the following changes:

```csharp
            int MyMaxModelBindingCollectionSize;
            if (!int.TryParse(Configuration["MyMaxModelBindingCollectionSize"], out MyMaxModelBindingCollectionSize))
            {
                MyMaxModelBindingCollectionSize = 100;
            }

    services.Configure<MvcOptions>(options => 
           options.MaxModelBindingCollectionSize = MyMaxModelBindingCollectionSize);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio#performance-considerations)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Right, this is even simpler

```
            int MyMaxModelBindingCollectionSize = Convert.ToInt32(
                        Configuration["MyMaxModelBindingCollectionSize"] ?? "100");
                  
            services.Configure<MvcOptions>(options => 
                   options.MaxModelBindingCollectionSize = MyMaxModelBindingCollectionSize);
``

and is in #21576
