### ISSUE TITLE
Create a web UI overview doc on ASP.NET Core Web UI's

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#21820]

**Comment by spboyer** [comment]
@justinyoo @IEvangelist

**Comment by Rick-Anderson** [comment]
Dup of #17882 and related to #21821

**Comment by wadepickett** [comment]
Rather then doing both an overview and a decision tree type topic, after discussion with danroth27, it was decided a single new "decision tree" topic would handle this. Thanks everyone for the suggestions and feedback.

The tracking item for the decision tree topic is #21821.
