### ISSUE TITLE
Create a web UI decision tree doc

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#21821]
Goal: Guidance for ASP.NET Core that explains when to use the various web UI technologies Microsoft provides and supports: 
- MVC
- Razor Pages
- Blazor Server
- Blazor
- SPA

**Comment by spboyer** [comment]
Looking at this doc as a guide - https://docs.microsoft.com/en-us/azure/architecture/guide/technology-choices/compute-decision-tree
 @justinyoo @IEvangelist

**Comment by Rick-Anderson** [comment]
Dup of #17882 ?
