### ISSUE TITLE
Issue debugging Blazor WASM in Visual Studio Code

### ISSUE THREAD

**Issue by RicardoValero95** [dotnet/AspNetCore.Docs#21825]
I think I followed everything from the article but without success. 
I am currently working on

MacBook Air (M1, 2020) 
- macOS Big Sur v11.2.3 (20D91)
- .NET SDK v5.0.201
- Visual Studio Code v1.54.3
  - C# v1.23.9
  - .NET Install Tool for Extension Authors v1.0.0
  - Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension v1.0.0
- Microsoft Edge v89.0.774.54 

I am attempting to debug a simple Blazor WASM `dotnet new blazorwasm -o MyBlazorApp`

> launch.json

```json 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "browser": "edge",
            "cwd": "${workspaceFolder}/src/MyFirstBlazorApp"
        }
    ]
}
```

This message keeps popping on:
```
Couldn't find a debug adapter descriptor for debug type 'blazorwasm' (extension might have failed to activate)
```

I also can't get rid of this from the `Problems` tab:
```json
{
	"resource": ".../MyBlazorApp/src/MyBlazorApp/Program.cs",
	"owner": "csharp",
	"code": "CS0246",
	"severity": 8,
	"message": "The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?) [MyBlazorApp]",
	"source": "csharp",
	"startLineNumber": 18,
	"startColumn": 40,
	"endLineNumber": 18,
	"endColumn": 43
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RicardoValero95 ... Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... please add a cross-link to this docs issue and and ping for me so that I can follow the discussion. I'll re-open this if we end up adding content to the doc. Here's a cut-'n-paste for your engineering issue ...

```
Cross-reference: https://github.com/dotnet/AspNetCore.Docs/issues/21825
cc: @guardrex
```
