### ISSUE TITLE
Doc sweep

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#21834]
Review docs for best security practices.

**Comment by wadepickett** [comment]
@Rick-Anderson I'm sorry Rick, you will have to take this one.  I have too much on my plate at the moment with a new assignment that was just added outside of content writing.  Were you intending to review the _entire_ repo for best security practices manually, or using a tool of some sort?  This is rather huge to say the least unless there was some sort of automatic check you had in mind.

**Comment by wadepickett** [comment]
We might be able to run CodQL against the whole thing to help, but it isn't set up for handling hundreds of nested projects that this repo has.   It might be possible to run it on the artifact output from the Snippet compiling tool.  So everything is precompiled and then run CodeQL as a thought.  Maybe.

**Comment by wadepickett** [comment]
I'll assign back to me.  If an automation option works out, then I can take it on.  But a manual retro check on the whole repo would be too big.

**Comment by wadepickett** [comment]
Just saw your email explaining the scope.  Sorry, I assumed the scope and task of "Review docs for best security practices." as you noted above which would be a rather large project.
