### ISSUE TITLE
Add additional JSON property so Swagger looks like non Swagger URL

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#21836]
In the section for JSON serialization, I would suggest adding the following:

[JsonPropertyName("name")]

The updated code would then look like this:
        [BsonElement("Name")]
        [JsonProperty("Name")]
        [JsonPropertyName("name")]
        public string BookName { get; set; }

The goal is to allow the swagger output to look like the output seen in the direct URL test. 

The addition of another using statement will be needed:
using System.Text.Json.Serialization;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio#test-the-web-api)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Container list: Create a web API and MongoDB #16196
