### ISSUE TITLE
"dotnet ef migrations remove" fails

### ISSUE THREAD

**Issue by drguildo** [dotnet/AspNetCore.Docs#21837]
When I got to the part of the tutorial that tells me to run:

```
dotnet ef migrations remove
dotnet ef database drop
dotnet ef migrations add InitialCreate
dotnet ef database update
```

The `dotnet ef migrations remove` command failed with:

```
> dotnet ef migrations remove
Build started...
Build succeeded.
The migration '20210320131259_InitialCreate' has already been applied to the database. Revert it and try again. If the migration has been applied to other databases, consider reverting its changes using a new migration instead.
```

To get the command to succeed I had to do `dotnet ef database drop` first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Part 8, add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Also update https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-remove
