### ISSUE TITLE
Can we please have  a Similar Example with Identity(free) and not IdentityServer(paid for).

### ISSUE THREAD

**Issue by brightertools** [dotnet/AspNetCore.Docs#21844]
Is it possible to create an SPA example that rellies on Identity and not IdentityServer for an SPA application?

I have started a few projects using the SPA example and Identity server, which is becoming a proprietary and paid for product, which is very expensive to upgrade to when the time comes. It would be great to have these examples using out the box authentication/authorization from Microsoft only available in .net core without using 3rd party products.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
