### ISSUE TITLE
Book link gives 404 - not found

### ISSUE THREAD

**Issue by hugh-maaskant** [dotnet/AspNetCore.Docs#21847]
The link to the .pdf file for the mentioned book, as well as the link behind the cover photo, lead to the GitHub 404 - not found page.

I managed to find the book eventually, but this should be fixed so that other people do not have to search too long ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0d56c8f-85da-6c32-ce99-1df8d1a71edd
* Version Independent ID: 388cf375-58cc-1035-4de0-6ed3f6ae6b9c
* Content: [DevOps with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/aspnet/core/azure/devops/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/azure/devops/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/azure/devops/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
@hugh-maaskant  can you provide the fixed link?

**Comment by hugh-maaskant** [comment]
Hi Rick,

I found it on the GitHub repository for the e-books:

https://github.com/dotnet-architecture/eBooks <https://github.com/dotnet-architecture/eBooks>

This is the specific link:

https://github.com/dotnet-architecture/eBooks/blob/master/current/devops-aspnet-core/DevOps-with-ASP.NET-Core-and-Azure.pdf <https://github.com/dotnet-architecture/eBooks/blob/master/current/devops-aspnet-core/DevOps-with-ASP.NET-Core-and-Azure.pdf>

Best Regards, Hugh

——
Hugh Maaskant
The Netherlands
