### ISSUE TITLE
Improvement suggestions for Razor Pages Tutorial - VS Code Version

### ISSUE THREAD

**Issue by amarie401** [dotnet/AspNetCore.Docs#21852]
I have recently conducted a user study on this tutorial. There were a few areas of improvement opportunities that we concluded based on watching a user go through the VS Code version of this tutorial and noticing the issues that they ran into. 

Issue 1:
* In the get started section, when told to _press ctrl + f5 to run without the debugger_, there was no image or instructions on which environment to select from the dropdown. The user eventually selected .NET but was confused on which one they should have chose.  

Improvement 1:
* Add a screenshot or instructions on which environment to select from the dropdown in VS Code for that step. 

Issue 2
* In the add a model section, when told to _"Build the project to verify there are no compilation errors."_ There was no clear instruction given on how to build it so the user was confused and stuck on this part. The user mentioned that the first part told you to press ctrl + f5 for running the app without the debugger, but didn't tell you how to build it in the next section. 

Improvement 2:
* Add clarification on what keyboard shortcuts to press or where to go inside of VS Code to build the app.  

cc: @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@amarie401 Thanks for this valuable feedback. We'll make addressing this a top priority. @wadepickett  please create an issue for the MVC version, I'm sure it's similar.

**Comment by wadepickett** [comment]
Thanks @amarie401!

**Comment by wadepickett** [comment]
I just realized this is really old.  It was assigned and then unassigned then assigned.  It seems to me that since then that VSC changed how it was set up by default and we updated that section a bit.  I will test through with a fresh install of VSC however to verify of course.
