### ISSUE TITLE
Some users confused regarding the sample code for Razor Pages tutorial

### ISSUE THREAD

**Issue by amarie401** [dotnet/AspNetCore.Docs#21850]
I recently conducting a user study and watched users work through the steps in this tutorial. We found that there were a few users who were confused and thought that the sample code was something that they needed to download as step 1 of the tutorial instead of starting with the prerequisites and beginning from that point.  In order to reduce this confusion, my suggestion would be to add more clarification so that users know that downloading the sample code is optional or perhaps move the sample code to the end of the tutorial. 

cc: @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@amarie401  great suggestion.
Update @wadepickett  fix the MVC version when you fix this issue.

**Comment by Rick-Anderson** [comment]
@wadepickett 

Move `[View or download sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50) ([how to download](xref:index#how-to-download-a-sample)).` to the bottom of the page as an include in AspNetCore.Docs/aspnetcore/includes/RP/

And change it to something like

`## Troubleshooting`

`If you run into a problem you can't resolve, compare your code to the [completed project](link). A good way to get help is by posting a question to [StackOverflow.com](link), using the [ASP.NET Core tag](https://stackoverflow.com/questions/tagged/asp.net-core) or the [EF Core tag](https://stackoverflow.com/questions/tagged/entity-framework-core).`
