### ISSUE TITLE
Missing template ASP.NET Core Web Application (Visual Studio Community 2019)

### ISSUE THREAD

**Issue by swbiddle** [dotnet/AspNetCore.Docs#21867]
Have downloaded all Web & Cloud and Desktop & Mobile workflows in MS Visual Studio Community 2019. Where is template 'ASP.NET Core Web Application?' Please recommend other template for use in tutorial.
[2021_3_24 template screenshot.pdf](https://github.com/dotnet/AspNetCore.Docs/files/6197631/2021_3_24.template.screenshot.pdf)
[2021_3_24 visual studio template options.pdf](https://github.com/dotnet/AspNetCore.Docs/files/6197632/2021_3_24.visual.studio.template.options.pdf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio#prerequisites

**Comment by swbiddle** [comment]
I’m very new to this, so please be patient. I have Visual Studio 16.9.2 and SDK 5.0.201 installed. The closest template I have for RazorPages is ASP.Net Core Web App. I know it’s only a slightly different name, but I had trouble once I was working through the Model on the next tutorial page. Not having the same template is confusing.

Thanks,
Samuel W. Biddle

**Comment by wadepickett** [comment]
@swbiddle, thanks very much for taking the time to point out the issue you ran into.

The template name did recently change slightly.  It is "ASP.NET Core Web App" in VS 16.9.2 that you should select.

![image](https://user-images.githubusercontent.com/10985336/112526875-ab488c00-8d5f-11eb-966b-4a9afa6f4161.png)

The tutorial has not been updated from VS 16.8 to VS 19.9.2 yet. It specifies VS 16.8 in the prerequisites but also says "or later".  So you are right to expect it to work with later versions.  Sorry for the difficult experience.  We do need to update the tutorial yet.

**Comment by wadepickett** [comment]
@swbiddle, I have opened a new issue #21883 that is specific to calling out the template name difference for VS 16.9.2.  Thanks again.

**Comment by swbiddle** [comment]
Thank you very much for your time!
