### ISSUE TITLE
Route-to-code is an awesome feature. I love the terse but informative content. Nice one Microsoft! 

### ISSUE THREAD

**Issue by riccardo10** [dotnet/AspNetCore.Docs#21865]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7abf4aa-38d6-0d52-3ca9-f1898eb5af91
* Version Independent ID: 410b4c9d-65f6-8f0e-ade9-9c93d9e4d98f
* Content: [Basic JSON APIs with Route-to-code in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/route-to-code.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/route-to-code.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
Thanks
