### ISSUE TITLE
Not working example that demonstrates sending large binary payloads in Blazor Server 

### ISSUE THREAD

**Issue by Jarek300** [dotnet/AspNetCore.Docs#21864]
Article contains a sentence:

> For an example that demonstrates sending large binary payloads in Blazor Server that uses techniques similar to the InputFile component, see the Binary Submit sample app.

[Binary Submit sample app](https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/BinarySubmit) does not work -  key javascript file is missing. There is [issue](https://github.com/aspnet/samples/issues/65)  from 13 Dec 2020 about not working sample. The author of the sample is @pranavkm - could he fix it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdccf73-41ed-b996-86c1-d8b7838f8773
* Version Independent ID: 32d99e69-dc2d-c452-cfdb-2bf1f1956e16
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-5.0#size-limits-on-js-interop-calls)
* Content Source: [aspnetcore/blazor/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Jarek300 ... https://github.com/aspnet/samples/issues/65 is a good spot ... it just perhaps needed the ping for @pranavkm to take a look and advise on it. Let's work it on that issue; but if @pranavkm has something that we should change here, I'll re-open this issue for work here on the doc. :ear:

**Comment by guardrex** [comment]
... and btw @pranavkm ... There doesn't seem to be :eyes: on the issues there, as a bunch aren't answered.

https://github.com/aspnet/samples/issues
