### ISSUE TITLE
Manual migration code is wrong for resulting model

### ISSUE THREAD

**Issue by northwestfrog** [dotnet/AspNetCore.Docs#21860]
The manual migration code is for a flatened model where Instructor, Student and Person are one single table.

The generated model is meant to work with 3 tables Person, Instructor and Student.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Container issue for EF/MVC #17465
