### ISSUE TITLE
Home Controller About  Custom Code is wrong

### ISSUE THREAD

**Issue by northwestfrog** [dotnet/AspNetCore.Docs#21861]
The code snippet that is suggested after :
"In HomeController.cs, replace the About method with the following code"

refers to a structure where Person, Student and Instructor are a single table. It is not the case.

It should read : 
...
                    string query = "SELECT EnrollmentDate, COUNT(*) AS StudentCount "
                        + "FROM Student "
                        + "GROUP BY EnrollmentDate";
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Container issue for EF/MVC #17465
