### ISSUE TITLE
Examine SQL queries... not working

### ISSUE THREAD

**Issue by northwestfrog** [dotnet/AspNetCore.Docs#21862]
In order for this section to work, a few changes needed to be done to the startup.cs file and also the appsettings.json

I was able to achieve what was described in this section after following the instructions provided through this URL:

https://dev.to/galwaycoder/how-to-inspect-the-sql-generated-by-entity-framework-core-using-net-core-s-built-in-logging-18do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4482f94f-bb17-fb95-d00b-c1c02410221a
* Version Independent ID: 84ed5b8e-5546-9086-e233-2605e1b35d37
* Content: [Tutorial: Learn about advanced scenarios - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to Container issue for EF/MVC #17465

**Comment by Rick-Anderson** [comment]
@northwestfrog  take a look at #21576
I should have that published in a week. It's updated, unlike this series.
