### ISSUE TITLE
Query could not add to the request.

### ISSUE THREAD

**Issue by KaraBilly** [dotnet/AspNetCore.Docs#21874]
Look like there are many imperfection in this package. Such as query could not bind to request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa3c933-30c4-eb49-d9a5-507aff44ce00
* Version Independent ID: 1485c456-eb24-a446-e296-dd3686456837
* Content: [Create JSON Web APIs from gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/httpapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/httpapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
Potential bugs in the ASP.NET Core framework and product feedback can be reported at [dotnet/aspnetcore issues](https://github.com/dotnet/aspnetcore/issues) (include full repro steps and cross-link to a repro project in GH when appropriate).
