### ISSUE TITLE
XSRF: Pass $CREDENTIAL_PLACEHOLDER$ from view to JavaScript

### ISSUE THREAD

**Issue by RickAndMSFT** [dotnet/AspNetCore.Docs#21872]
@fiyazbinhasan  any chance you could supply the code to fetch the credential in the view (using `Configuration["myCredential"]` and pass it to the JavaScript. That way the credential isn't hard coded in the JavaScript.

See https://github.com/dotnet/AspNetCore.Docs/pull/21851/files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0&branch=pr-en-us-21851)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Are these code snippets coming from a sample? Sorry, I can't find the `changeCode` action @RickAndMSFT

**Comment by Rick-Anderson** [comment]
This [this JavaScript](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0&branch=pr-en-us-21851#javascript)

The following example uses JavaScript to make an AJAX request with the appropriate header:

```
function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

var csrfToken = getCookie("CSRF-TOKEN");

var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (xhttp.readyState == XMLHttpRequest.DONE) {
        if (xhttp.status == 200) {
            alert(xhttp.responseText);
        } else {
            alert('There was an error processing the AJAX request.');
        }
    }
};
xhttp.open('POST', '/api/password/changepassword', true);
xhttp.setRequestHeader("Content-type", "application/json");
xhttp.setRequestHeader("X-CSRF-TOKEN", csrfToken);
xhttp.send(JSON.stringify({ "newPassword": "ReallySecurePassword999$$$" })); // <--------------------
```

I would like to pass `ReallySecurePassword999$$$` into the JavaScript so we don't hardcode it.

![image](https://user-images.githubusercontent.com/3605364/112518170-38c6b480-8d3d-11eb-96a9-599c7d92d5eb.png)

The problematic code is just above [AngularJS](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0&branch=pr-en-us-21851#angularjs)

**Comment by fiyazbinhasan** [comment]
I think the sample serves the purpose well. Practically you would want to send the `newCode` / `newPassword` directly from a user input field. A generic placeholder is good enough in this case. Reading from `Configuration["myCredential"]` and pass it to js and then using it in a ajax request - the whole process seems confusing. Moreover, it will require another HTTP call to fetch the value of `Configuration["myCredential"]`. However, we can return the value of `Configuration["myCredential"]` in a cookie and then read it just like the XSRF token and use it in `xhttp.send(JSON.stringify({ "newPassword": "ReadTheValueFromACookie" }));`

**Comment by Rick-Anderson** [comment]
However, we can return the value of `Configuration["myCredential"]` in a cookie and then read it just like the XSRF token and use it in `xhttp.send(JSON.stringify({ "newPassword": "ReadTheValueFromACookie" }));`

Let's do that. We can't have code samples with embedded passwords in them. 
@blowdart  do you concur?

**Comment by blowdart** [comment]
That seems worse, because it stores the credentials in a cookie, something you want to avoid. An API call is cleaner IMO

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  we also want to modify the sample to remove changing passwords. The sample doesn't need to be about passwords. How about:

```
<form asp-controller="Manage" asp-action="ChangeCode" method="post">
    ...
</form>

@using (Html.BeginForm("ChangeCode", "Manage"))
{
    ...
}
``

Change `xhttp.open('POST', '/api/password/changepassword', true);` to `xhttp.open('POST', '/api/token/changeCode', true);`

Or maybe we need a totally new sample that shows the CORS concepts this is showing.

**Comment by fiyazbinhasan** [comment]
Why not just use the todo app [link](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/anti-request-forgery/sample/AngularSample) sample for the basis of demonstration? It's way too easy to understand the flow and the sample is also linked in the documentation. The following snippet will suffice,

```
function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}

var csrfToken = getCookie("CSRF-TOKEN");

var xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
    if (xhttp.readyState == XMLHttpRequest.DONE) {
        if (xhttp.status == 200) {
            alert(xhttp.responseText);
        } else {
            alert('There was an error processing the AJAX request.');
        }
    }
};
xhttp.open('POST', '/api/items', true);
xhttp.setRequestHeader("Content-type", "application/json");
xhttp.setRequestHeader("X-CSRF-TOKEN", csrfToken);
xhttp.send(JSON.stringify({ "name": "Do the dishes" }));
```
What do you think? @RickAndMSFT

**Comment by Rick-Anderson** [comment]
@blowdart  can you approve the preceding change?

**Comment by blowdart** [comment]
That works much better, no confusion at all :)

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  would you like to make the PR or should @wadepickett  and I do it? If you update it:

* Make the preceding Razor Page and comments consistent with the JavaScript changes.
* Change `By Rick Anderson, Fiyaz Hasan, and Steve Smith` to `By Fiyaz Hasan, Rick Anderson, and Steve Smith`

It's not urgent, anytime next week is fine.

**Comment by fiyazbinhasan** [comment]
Sure. Will make a pull request in the weekends @RickAndMSFT
