### ISSUE TITLE
What is a RemoteAuthenticationHandler<TOptions> compared to a AuthenticationHandler<TOptions>?

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/AspNetCore.Docs#21879]
This page explains how to create your own AuthenticationHandler (by deriving from `IAuthenticationHandler`, `AuthenticationHandler<TOptions>`, but fails to mention what `RemoteAuthenticationHandler<TOptions>` is and how it differs from `AuthenticationHandler<TOptions>`.

The summary of `RemoteAuthenticationHandler<TOptions>` is `An opinionated abstraction for an Microsoft.AspNetCore.Authentication.AuthenticationHandler that performs authentication using a separately hosted provider.`

What exactly is a provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[ public class RemoteAuthenticationOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs)

@pranavkm  should this be documented?

**Comment by SpiritBob** [comment]
> [ public class RemoteAuthenticationOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/RemoteAuthenticationOptions.cs)
> [AuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/AuthenticationHandler.cs) is abstract
> 
> Providers are low level components of ASP.NET Core that provide services, like debug log provider, external authentication provider, configuration provider etc.
> 
> @pranavkm should this be documented?

I think you meant [RemoteAuthenticationHandler](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/RemoteAuthenticationHandler.cs) (not RemoteAuthenticationOptions)?

Both classes are abstract. Options were never abstract.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-5.0&terms=provider&category=Documentation

**Comment by SpiritBob** [comment]
> https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-5.0&terms=provider&category=Documentation

Thank you. Does closing this issue mean it's resolved? Because I still don't know the difference between `RemoteAuthenticationHandler` and `AuthenticationHandler`.

**Comment by Rick-Anderson** [comment]
@martincostello can you outline the differences between `RemoteAuthenticationHandler` and `AuthenticationHandler`?

@SpiritBob  have you looked at the source?

**Comment by davidfowl** [comment]
cc @Tratcher @HaoK

**Comment by HaoK** [comment]
RemoteAuthenticationHandler is the class for auth that requires a remote authentication step that when finished calls back to the CallbackPath set by the handler which will then finish the authentication step using the information passed to the callback path (HandleRemoteAuthenticateAsync).  OAuth2 and OIDC both use this pattern.  JWT and cookies do not since they can just directly use the bearer header/cookie to authenticate.  Is that enough detail?

**Comment by HaoK** [comment]
The remotely hosted provider in this case, means an authentication provider, which could be Google/facebook/twitter/any OIDC provider, etc which handles authenticating users in whatever way they want.
