### ISSUE TITLE
.NET 6:  Use cookie authentication without ASP.NET Core Identity

### ISSUE THREAD

**Issue by 78Star** [dotnet/AspNetCore.Docs#21885]
The Section "Create an authentication cookie" uses a reference to an obsolete library call (httpContext.Authentication).
This library call was marked obsolete here
https://github.com/aspnet/Security/issues/1310

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Where is `IAuthenticationManager` used in [Create an authentication cookie](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-6.0#create-an-authentication-cookie) ?
