### ISSUE TITLE
It's misleading to say there's built-in support for bundling and minifying

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/AspNetCore.Docs#21886]
It's misleading to say there's built-in support for bundling and minifying. The `evironment` tag is great, but it's just that, an environment tag. Perhaps a better way to say it is: Use our [suggested guidelines for bundling and minifying](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by mjrousos** [comment]
Thanks, @Dean-NC. That's a good suggestion. I agree your wording would be more accurate.

**Comment by Rick-Anderson** [comment]
@Dean-NC  are you interested in fixing this?
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Dean-NC** [comment]
@Rick-Anderson PR submitted.
