### ISSUE TITLE
Handling exceptions if the response has already started? ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#21908]
Would it be possible to append the error handling documentation to show how to capture an exception that occurs **AFTER** a response has been started?  (If possible)?

From reading the docs and the ASP.Net source code, it seems that this would be impossible to do !

The ASP.Net source code for the error handling middleware at:
[https://github.com/dotnet/aspnetcore/blob/6255c1ed960f5277d2e96ac2d0968c2c7e844ce2/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs](https://github.com/dotnet/aspnetcore/blob/6255c1ed960f5277d2e96ac2d0968c2c7e844ce2/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs) contains the following comment (line 93):

`// We can't do anything if the response has already started, just abort.`

So, theoretically, if we have a web application with the following lines of code within Configure(), in Startup.cs:

```
app.UseExceptionHandler(errorApp =>
   {
        errorApp.Run(async context =>
        {
            context.Response.StatusCode = 500;

            context.Response.ContentType = "text/html";

            // Error logging code removed for clarity

            await context.Response.WriteAsync("<html><body>An Exception occurred</body></html>" );

        });
    });
```

... Then, somewhere within our application, the following gets executed:

```
http_context.Response.ContentType = "text/html";

await http_context.Response.WriteAsync( "<html><body>some content" );

await http_context.Response.WriteAsync( "more content..." );

// other logic is performed that throws an exception (simulated below) ...

throw new Exception( $"HA-HA -- This exception can never be caught because the response has already started !!" );
```

In the case above, the exception would never be caught -- correct?  

If not correct, can an example be provided of capturing an exception AFTER a response has started?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0#exception-handler-page)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> // We can't do anything if the response has already started, just abort.

That's correct.

**Comment by bdcoder2** [comment]
@Rick-Anderson - thanks for confirming ! 👍
