### ISSUE TITLE
Server Example needs updating

### ISSUE THREAD

**Issue by Equiverse** [dotnet/AspNetCore.Docs#21906]
Could you please update the server here as it would be nice as im kind of new to MVC. Its hard to kind of second guess how the Blazor endpoint constructed to interact with MVC at this point. 🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31248d7-d2c2-1a17-3173-889a0d9bb6e8
* Version Independent ID: 6f27ff37-6b3a-57f5-353a-5cf5aabba7cf
* Content: [ASP.NET Core Blazor project structure](https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Equiverse ... I don't understand your ask (i.e., "Server Example needs updating" and "update the server here").

> how the Blazor endpoint constructed to interact with MVC at this point.

Merely `MapFallbackToPage("/_Host")` and `MapBlazorHub`, which are explained here with cross-links to the API docs.

Further info on routing is in the Routing doc at ...

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/routing
