### ISSUE TITLE
Are the Scenarios listed exclusive or can they be combined in any way?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#21909]
I mean the ones listed after 

> Kestrel supports the following scenarios:

Specifically I'm looking to see if using the first two (http + http2) at the same time on the same host is possible or supported or not before I dedicate time to trying it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StingyJack ... HTTP/2 is backward-compat with HTTP/1.1 by design.

**Comment by guardrex** [comment]
..... in fact, when either the client or server aren't HTTP/2 compat when attempting to use the HTTP/2 protocol, the protocol goes to HTTP/1.1 automatically. Check out web docs on the details.

There are still some caveats and conditions ... see :point_right:

* https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel/endpoints#listenoptionsprotocols
* https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel/http2
