### ISSUE TITLE
assign Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext.Result to a result instance and...

### ISSUE THREAD

**Issue by paul-cheung** [dotnet/AspNetCore.Docs#21911]
The description in this page as following,
`To short-circuit, assign Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext.Result to a result instance and`
Should it be `assign a result instance to Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext.Result and`
Or `assign Microsoft.AspNetCore.Mvc.Filters.ActionExecutingContext.Result with a result instance and` ?

Maybe I misunderstand it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think that's correct, the main thing is don't call next, like other examples show:

```
public class MyAsyncResponseFilter : IAsyncResultFilter
{
    public async Task OnResultExecutionAsync(ResultExecutingContext context,
                                             ResultExecutionDelegate next)
    {
        if (!(context.Result is EmptyResult))
        {
            await next();
        }
        else
        {
            context.Cancel = true;
        }

    }
}
```

cc @serpent5

**Comment by paul-cheung** [comment]
> I think that's correct, the main thing is don't call next, like other examples show:
> 
> ```
> public class MyAsyncResponseFilter : IAsyncResultFilter
> {
>     public async Task OnResultExecutionAsync(ResultExecutingContext context,
>                                              ResultExecutionDelegate next)
>     {
>         if (!(context.Result is EmptyResult))
>         {
>             await next();
>         }
>         else
>         {
>             context.Cancel = true;
>         }
> 
>     }
> }
> ```
> 
> cc @serpent5

the main thing is don't call next, it is correct and I can not agree more. My question is assign A to B, or assign B to A?

**Comment by serpent5** [comment]
> My question is assign A to B, or assign B to A?

Your question reads more like "Assign A to B?" or "Assign B with A?", which (I think) is essentially the same thing. Do you mean something else?
