### ISSUE TITLE
Q: Packages required for scaffolding in VSC version of Razor pages tutorial

### ISSUE THREAD

**Issue by amarie401** [dotnet/AspNetCore.Docs#21917]
For the VSC version, you must add 8 NuGet packages and EF tools by running the following command:

```
dotnet tool install --global dotnet-ef
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
dotnet add package Microsoft.Extensions.Logging.Debug
```

**Question & Suggestion**: These are a lot of packages that users have to install when trying out this tutorial for the first time for new .NET developers. This can be overwhelming for them. Is it possible to scope the packages down in the tutorial or are all of these necessary for adding a data model and scaffolding?

cc @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@amarie401  I think it only requires 2 tools and 4 packages:
  <ItemGroup>
 <PackageReference Include="Microsoft.EntityFrameworkCore.SQLite" Version="5.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.4">
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
  </ItemGroup>

So we might be able to remove a couple packages. @wadepickett  can you test this?

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan I know you don't need `dotnet add package Microsoft.Extensions.Logging.Debug` but what else can be cut?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson will take a look at it soon

**Comment by fiyazbinhasan** [comment]
@amarie401 for VSC we can crop down the commands to the followings,

```
dotnet tool install --global dotnet-ef
dotnet tool install --global dotnet-aspnet-codegenerator
dotnet add package Microsoft.EntityFrameworkCore.Design
dotnet add package Microsoft.EntityFrameworkCore.SQLite
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
dotnet add package Microsoft.EntityFrameworkCore.SqlServer
```
