### ISSUE TITLE
Reduction in duplicate code in scaffolding the movie model for Razor pages tutorial

### ISSUE THREAD

**Issue by amarie401** [dotnet/AspNetCore.Docs#21918]
For the VSC version of the tutorial, when running the scaffolding command `dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries` there are two versions of this command for Windows and Mac/Linux with the difference being either using a \ or / slash. After locally testing, the forward slash does work on Windows for this tutorial. 

**Suggestion**: Have one version of the command using the / slash to reduce code duplication. 

cc: @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@amarie401  thanks, that was a request I made long ago. Glad it's works on windows now.

**Comment by Rick-Anderson** [comment]
@amarie401 I miss-read this issue in that once command works.  This is still a bug that requires different commands
See https://github.com/dotnet/Scaffolding/issues/582
cc @deepchoudhery
