### ISSUE TITLE
Suggestion: Add clarification for <port> in 'Test the web API' section

### ISSUE THREAD

**Issue by kakyoin01** [dotnet/AspNetCore.Docs#21920]
[EDIT by guardrex to add the metadata. @kakyoin01, please use the **This page** feedback button and form at the bottom of the English-US topic to open issues here. That approach adds the metadata, which also automatically pings the author of the topic.]

For this section: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app#test-the-web-api

Steps 2 and 3 refer to the general URL `http://localhost:<port>/api/books`. However, it is not specified what this port number usually is--as someone relatively new to ASP.NET and MongoDB still, I (and perhaps others) got confused over it initially given that the only reference to an explicit port number in previous steps was the default MongoDB daemon process port (`27017`) discussed in the section about setting up the **appsettings.json** database settings. I got stuck when I tried to change the URL to include `localhost:27107` and getting an *"It looks like you are trying to access MongoDB over HTTP on the native driver port"* message in the resulting web page because I was inadvertently directly trying to access Mongo even though [it has been deprecated already](https://docs.mongodb.com/manual/release-notes/3.6-compatibility/index.html#http-interface-and-rest-api).

Suggestion is to add a brief blurb to step 2 (and maybe step 3) describing what `<port>` in those URLs usually is--it refers to the default IIS app startup port in the page URL, which is in **launchSettings.json** under `iisSettings->iisExpress->sslPort`--and to leave it unchanged when testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio#test-the-web-api)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Container list: Create a web API and MongoDB #16196
