### ISSUE TITLE
Guidance on Getting This to Work with SQL Server

### ISSUE THREAD

**Issue by pevans360** [dotnet/AspNetCore.Docs#21921]
Article and demo are both very helpful.  

The demo uses SQLite.  All our databases are on SQL Server, so wanted to try getting to work there.  Made a few attempts.  Tried viewing the SQLite database in "DB Browser for SQLite" and then exporting the tables as .sql - then load them into a SQL Server database.  Datatypes were almost all "TEXT" leading to script errors creating primary keys.  

Then tried using the scripts here:
 (https://id4withclients.readthedocs.io/en/latest/id4/ID4Database/DatabaseGenScriptID4.html and following pages)
to create the database.  They worked - with some minor errors.  

Added the NuGet package for EF Core SQL Server and changed the connection string.  Changed AddDbContext options to "UseSqlServer".  The project built and would display the home page and Registration page, but would not save registration data - got type 500 errors.  

Long story short, could really use some guidance on getting this working with SQL Server.    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Use the `uld` option. From help
 -uld|--use-local-db        Whether to use LocalDB instead of SQLite.
