### ISSUE TITLE
Regarding ASP NET Core 5.0 Razor Pages, AD authentication and authorization 

### ISSUE THREAD

**Issue by tomkla-nha** [dotnet/AspNetCore.Docs#21923]
H!. Can you please point me in the right direction to where you have written about this. I feel that I stumble with regards to the right source as I think I mix terms a bit.
I have allready implemented this in my app using a mysql database and in that database I have a table named aspnetusers....I guess I followed one of your articles on that.
(I have two classes called AppIdentityUser and AppIdentityRole)

I want two convert this to just using AD as authentication and authrization mechanism.

Can you advice me how to procees.

Thanks anyhow for good written articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tomkla-nha ...

Try this one :point_right: https://docs.microsoft.com/aspnet/core/security/authentication/azure-active-directory/
