### ISSUE TITLE
When I should surround IHttpClientFactory.CreateClient in a using block?

### ISSUE THREAD

**Issue by frankyuan** [dotnet/AspNetCore.Docs#21930]
[Enter feedback here]
Hi, I saw some articles(such as https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) said can't use `using` block to surround HTTP client, and in the demo in this page, doesn't surround `var client = _clientFactory.CreateClient();` in using block. But in https://docs.microsoft.com/en-us/dotnet/api/system.net.http.ihttpclientfactory.createclient?view=dotnet-plat-ext-5.0, it said _Callers may cache the returned HttpClient instance indefinitely or surround its use in a block to dispose it when desired_. Does that mean a `using` block? If so, when I should surround in a using block?

As I'm encountering a gradual memory leak (after the application runs about 7-10 days, managed memory usage is 110M but the total memory usage is 800M), not sure if it related HTTP client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Gladskih** [comment]
You should not dispose objects you not created.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by frankyuan** [comment]
> You should not dispose objects you not created.

Thanks.
