### ISSUE TITLE
"HTTPS Port" content placed in row instead of column

### ISSUE THREAD

**Issue by oreze** [dotnet/AspNetCore.Docs#21931]
As in the title, section "HTTPS Port" under the "Host configuration values" has specification content placed in row instead of column
![Screenshot from 2021-03-31 12-09-02](https://user-images.githubusercontent.com/22376195/113128273-ecd2ae80-9219-11eb-9614-21e9fb0a2561.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @oreze ... I'll patch that up ... it's a quick fix. Two spaces at the of a line signifies to the doc build engine to drop in a `<br>`; but on some edit of the file, the doc author removed (or didn't add) the double spaces at the ends of these lines ... so no `<br>`s were added to them.
