### ISSUE TITLE
Why is SendAsync() not awaited?

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#21938]
In [this section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=server#add-razor-component-code-for-chat-1), I noticed the following async method is not awaited.

```c#
Task Send() =>
        hubConnection.SendAsync("SendMessage", userInput, messageInput);
```

Is this recommended over the following?

```c#
async Task Send() =>
        await hubConnection.SendAsync("SendMessage", userInput, messageInput);
```

**Update**

In the [official expression-bodied members docs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members), I don't see anything about it.

I do see an explanation in [this external article](https://www.informit.com/articles/article.aspx?p=2414582). Is there anything like this in the official docs?

> ```c#
> public async Task<string> ReadFromWeb() => await RunWebRequest();
> ```
> The compiler is performing some heavy lifting to implement the async state machine for this method. Because of the structure of the method, that extra work isn't really accomplishing much. It's creating a state machine to wrap a task that simply unwraps a task returned from a different method. Instead, you might write this construct as follows:
>```c#
> public Task<string> ReadFromWebSimple() => RunWebRequest();
>```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ping @BrennanConroy

**Comment by BrennanConroy** [comment]
They are effectively the same thing.

There are some technical reasons you might prefer the non-async version, but for normal use cases it doesn't matter.

**Comment by guardrex** [comment]
Thx @BrennanConroy.

Let's leave this open until I get a chance to see if a single line would clarify it. I'm OOF until tomorrow morning.

**Comment by BrennanConroy** [comment]
Honestly, I've seen enough people complain about this sort of thing that I think we should just always use `async` `await` to avoid these questions.

**Comment by mrlife** [comment]
@BrennanConroy The quote from the article seems to say that removing the `async` and `await` from expression-bodied members is more efficient. Is that accurate, and if so, would it be good practice to do so?

> The compiler is performing some heavy lifting to implement the async state machine for this method. Because of the structure of the method, that extra work isn't really accomplishing much.

**Comment by BrennanConroy** [comment]
While somewhat true, it's an advanced scenario and it's better to just avoid the questions about why `async` `await` isn't being used.

**Comment by mrlife** [comment]
@BrennanConroy Thanks. Just to clarify, it's technically ok to use either?

**Comment by guardrex** [comment]
... and ...

> it's technically ok to use either?

... the PR doesn't address it; so if you want a blurb on the alternative with an example (that won't be in the sample app), I'm :ear: for dropping that into the PR. It can be a NOTE if you want. :ear::ear::ear::ear:
