### ISSUE TITLE
ASP .NET Core Blazor CSS isolation documentation

### ISSUE THREAD

**Issue by Chadley08** [dotnet/AspNetCore.Docs#21949]
I believe [this section](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#css-isolation-bundling) of the ASP .NET Core Blazor CSS isolation documentation regarding CSS isolation bundling could be made more clear by explicitly stating that the developer needs to create the {ProjectName}.styles.css file in their wwwroot/css folder and manually add the `<link href="{ProjectName}.styles.css"` rel="stylesheet"> to their site `<head>` tag.

The way it is currently written, it really sounds like the framework is doing this stuff for you, which it is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> The way it is currently written, it really sounds like the framework is doing this stuff for you, which it is not.

But it does do that ... at build time, as the section calls out.

@daveabrock to comment further, but I think we'll be able to close this, as the section seems to state everything correctly.

**Comment by daveabrock** [comment]
Hey, @Chadley08 - yes, this *does* do it automatically. To make sure I wasn't crazy I created a new .NET 5 Blazor project, ran it, and noticed my `Project.styles.css` was present as expected.

**Comment by guardrex** [comment]
Thx @davidabrock.

We'll continue to take feedback on this, @Chadley08. If more devs write in with confusion, we'll take a closer look at the phrasing to see what might be done.
