### ISSUE TITLE
Need to do Windows Authentication in a Linux container

### ISSUE THREAD

**Issue by ArrowRaider** [dotnet/AspNetCore.Docs#21947]
We need an example of how to do this in Docker/Kubernetes.  People do not want to host an entire machine/vm anymore, we want things to work in containers.  There are no resources anywhere on the internet for how get to Windows authentication to **work** in a Linux container.  The solution also should not involve joining the container to the domain.  It should be possible to do this without that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ArrowRaider ... Did you search the PU (product unit) issues. For example (and note I'm not a Docker :cat2:), I found the following in a search ...

https://github.com/dotnet/aspnetcore/issues/19397

... but even if that and similar topics that come up in search aren't helpful, you might be better off opening a new issue there to inquire further on this.

btw ---- Be sure to search both open and closed issues there. They'll close an issue as a `won't-fix` that might have exactly the info that you're seeking.

**Comment by blowdart** [comment]
Machines need to be domain joined, including containers, for the domain controllers to allow them to connect. The documentation is right here, we don't have any other way to do it.

**Comment by guardrex** [comment]
Thx @blowdart.

Closing as covered.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#linux-and-macos-environment-configuration

**Comment by ArrowRaider** [comment]
You guys need to document how to join a container to the domain then, because I cannot get that to work.

**Comment by guardrex** [comment]
We're in transition @ArrowRaider. Scott has left for a different position at MS, which is why I stepped in to try and help in spite of my lack of Docker skills. Let's ping @Rick-Anderson to put an :eye: on the convo here and see what he thinks.

**Comment by ArrowRaider** [comment]
It will most likely involve a sidecar.  I know there is some sort of daemon that needs to be running in order to join the domain.  Since a container should only run process.  I know it doesn't work out of the box because the relamd or sssd daemon isn't running and there is no init system.

**Comment by ArrowRaider** [comment]
I am pretty sure this should be possible by making krb keytab files.  There can be a dummy machine account in the domain for the SPN records and the keytabs will be created against it.  Each keytab is good for 24 hours, so the sidecar or side-job would need to make a new keytab in that period.

My particular environment is messed up and something is triggering negotiate to perform ldap queries on IPs that do not exist.  I did a packet trace with wireshark.  Sometimes the asp.net core app successfully authenticates my kerberos token, and other times it does not.  When it doesn't work, wireshark shows the machine trying to perform ldap queries on IPs that do not exist.  I checked all DNS records for stale _ldap._tcp records for gone servers and it is clean.  So I have no idea where dotnet is pulling these IPs from.

**Comment by maulik-modi22** [comment]
See how AWS allows **domain less containers** to use Windows authentication https://aws.amazon.com/blogs/containers/using-windows-authentication-with-gmsa-on-linux-containers-on-amazon-ecs/#:~:text=With%20today%27s%20release%2C%20customers%20modernizing,cost%2Defficient%2C%20and%20scalable.
