### ISSUE TITLE
ASP.NET Core Blazor state management code smell

### ISSUE THREAD

**Issue by kjhf** [dotnet/AspNetCore.Docs#21948]
Hi,
The "In-memory state container service" demo code contains a major code-smell --

```cs
    public string Property { get; set; } = "Initial value from StateContainer";

    public event Action OnChange;

    public void SetProperty(string value)
    {
        Property = value;
        NotifyStateChanged();
    }
```

The property `Property` has a public setter but the demo code shows that the property should be set through the `SetProperty` method. It's bad practice to have both a SetPropertyName method, and public property setter which would only set the autoproperty without doing the other bits (like the notifying of the UI which defeats the point!)

A sub-optimal fix would be to make the set private on the property so SetProperty must be called.
Better, the fix would be to scrap the SetProperty, move its implementation into the setter, and have a backstore for the property.

```cs
        private string savedStringValue;

        public string SavedStringValue
        {
            get => savedStringValue;
            set 
            {
                savedStringValue = value;
                NotifyStateChanged();
            }
        }
 ```

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-3.1&pivots=server#in-memory-state-container-service-server)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @kjhf ... I seem to recall that this wasn't a randomly hacked approach, but the issue/PR doesn't indicate the source, and I don't recall where I pulled/hacked it from. The chained bind came directly from our convo, @SteveSandersonMS, so that's a good section/example, but the "State Container Approach" wasn't reviewed. I pinged on https://github.com/dotnet/AspNetCore.Docs/pull/20047, but it didn't receive a review. Do you concur with @kjhf?

**Comment by SteveSandersonMS** [comment]
I agree with @kjhf that having a `SetProperty` independent of the regular setter is quite confusing and risks things getting out of sync. I agree that moving the notification into the setter would be a reasonable solution.

**Comment by guardrex** [comment]
Thanks ... I'll square this away first thing Friday morning.
