### ISSUE TITLE
Why do you need scope in console app usage example?

### ISSUE THREAD

**Issue by Gladskih** [dotnet/AspNetCore.Docs#21958]
Why do you need scope in console app usage example?

        using (var serviceScope = host.Services.CreateScope())
        {
            var services = serviceScope.ServiceProvider;

            try
            {
                var myService = services.GetRequiredService<IMyService>();

Why not just  `var myService = host.Services.GetRequiredService<IMyService>();` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @Gladskih ... `IMyService` is registered as transient ...

```csharp
services.AddTransient<IMyService, MyService>();
```

... so if you don't create a scope for it within the app's scope, it's probably going to resolve as a singleton, which wouldn't be the correct pattern for this scenario. It's covered at https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection#call-services-from-main. However, that section doesn't call out the consequence of avoiding the correct pattern, which is something that we might want to do there in the DI topic. For sure, we can cross-link the DI section to this.

@Rick-Anderson @stevejgordon ... I'll try to resolve this and ping for review.

**Comment by davidfowl** [comment]
Transients don't resolve as singletons when resolved from the root. They are created whenever they are asked for. If they happen to be disposable transients then they will be rooted by the container until disposal.

**Comment by guardrex** [comment]
Scoped only then is the concern? ...

https://docs.microsoft.com/dotnet/core/extensions/dependency-injection-guidelines#scoped-service-as-singleton

So going back to @Gladskih's question then, what's the point of the approach the doc example takes if not to preserve the correct lifetime?

Notwithstanding the answer to that, what I put on the PR might be ok given that it speaks to scoped ...

> This approach is useful to access a scoped service at startup **_with the correct service lifetime_** to run initialization tasks.

Emphasis added to show the text that the PR adds.

**Comment by davidfowl** [comment]
> Scoped only then is the concern? ..

That's right

**Comment by guardrex** [comment]
But what about the approach of creating a scope for a transient service? ... just do it for consistency, or is there a separate reason to adopt this strategy for transients?

**Comment by davidfowl** [comment]
I think you'd create a scope if you need a scope. I wouldn't just do it without a need. Especially if the article is just explaining concepts
