### ISSUE TITLE
How to Secure secrets in Unit Testing

### ISSUE THREAD

**Issue by motor75** [dotnet/AspNetCore.Docs#21954]
This article is a great source when trying to access secrets or passwords from an API or some other ASP.NET core program.  However, we are needing to store and access secrets (specifically application secrets created in Azure) via unit testing projects within an API.  The purpose of these application or client secrets is to test out the security of the API using the client credentials flow in Azure.  As part of that process, we need to be able to call into Azure AD to get an OAuth token using the client secret and verify - via unit testing in the project - that certain clients can or can not access certain parts of the API based on their app roles.  

The best I can tell, we can's use this procedure because the unit testing project doesn't have any "entry point" like an API or other ASP.NET component would have.  It simply runs the unit tests.  So, this question is really about whether or not this process of creating a local secret store can be used with unit testing (and if it can, how)?  If it can't, then what is the recommended practice to secure secrets needed in unit testing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update.
