### ISSUE TITLE
Mime types: FileExtensionContentTypeProvider works differently than described in this article

### ISSUE THREAD

**Issue by jsmarsch** [dotnet/AspNetCore.Docs#21960]
The article makes it look as though you can easily add additional mime types by adding them with a FileExtentionContentTypeProvider. However, when you do this, it's not additive, it replaces the existing map.  So if I add .vtt files with the technique described, it wipes out the mime mapping for .js files (and all others).  I really need a way to just add a mime type and keep the default ones.  The doc implies you can do this, because it shows how to remove a type.

Ideally, this doc would show how to add a new mime map for a file extension while keeping the default ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you post to a public GitHub repo the simplest possible sample that reproduces this problem?

**Comment by serpent5** [comment]
I don't see an issue with the sample for this:

```csharp
var provider = new FileExtensionContentTypeProvider();
provider.Mappings[".myapp"] = "application/x-msdownload";
```

The default constructor for `FileExtensionContentTypeProvider` initialises the default map, so the line that follows adds to that existing map.

@jsmarsch Are you following the example exactly, or are you passing a dictionary of your own into the `FileExtensionContentTypeProvider` constructor?

**Comment by serpent5** [comment]
@Rick-Anderson I think this one has gone stale. Do you want to close it?
