### ISSUE TITLE
The client also requires installation of Grpc.Net.Client

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#21965]
or the example client wont find things like GrpcChannel. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548ea859-02aa-913e-a2bb-e75d45d45f75
* Version Independent ID: 50d09935-a98d-86ae-7196-4d9a55f9121e
* Content: [Code-first gRPC services and clients with .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/code-first?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/code-first.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/code-first.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by fiyazbinhasan** [comment]
Yes. Unless someone is coming from [Tutorial: Create a gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-5.0&tabs=visual-studio), there is no way to know that the client project needs `Grpc.Net.Client`. Also, a sample source code would have been great. @Rick-Anderson

**Comment by Rick-Anderson** [comment]
If @JamesNK  agrees, @fiyazbinhasan  are you able to create the sample and PR this? I can help.

**Comment by fiyazbinhasan** [comment]
Sure! I can do that.

**Comment by JamesNK** [comment]
Go ahead.

**Comment by Rick-Anderson** [comment]
> Go ahead. I think some extra bullet points that prompt to add `Grpc.Net.Client` to the project would be enough.

But a complete project they can download doesn't hurt.
