### ISSUE TITLE
Error while Add new scaffolding item from razor page tutorial

### ISSUE THREAD

**Issue by grenadin** [dotnet/AspNetCore.Docs#21968]
I cannot follow the step in the razor page tutorial. In the step add new scaffolding item step. see the error follow by a picture

in the first attempt.
![error1](https://user-images.githubusercontent.com/11970460/113435565-4949ef80-940d-11eb-927f-c80de246bbea.png)

and the second attempt.
![error2](https://user-images.githubusercontent.com/11970460/113435616-61ba0a00-940d-11eb-987b-8557fca08d03.png)

and the Code Generation Log: 

Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Generating a new DbContext class 'RazorPagesMovie.Data.RazorPagesMovieContext'
Attempting to compile the application in memory with the added DbContext.
There was an error creating a DbContext :(10,19): error CS1001: Identifier expected
(11,6): error CS1513: } expected
(12,44): error CS8124: Tuple must contain at least two elements.
(13,13): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()

(13,27): error CS8124: Tuple must contain at least two elements.   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)

(14,9): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)

(18,5): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

(19,1): error CS1022: Type or namespace definition, or end-of-file expected
C:\Users\harir\source\repos\RazorPagesMovie\RazorPagesMovie\Startup.cs(30,13): error CS8389: Omitting the type argument is not allowed in the current context

And the csproj file
![error3](https://user-images.githubusercontent.com/11970460/113435961-06d4e280-940e-11eb-8879-e744ce90e2e1.png)

Actually. I have 2 laptop that installs Visual Studio 2019 and VSCode(Its error occur in the command line too). The error occurs on 2 laptops too. And I found scaffolding error either razor page, web api, or MVC, control if it involves using Entity Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's in the .proj file?
What is the `DbContext`?

**Comment by grenadin** [comment]
@Rick-Anderson 
for the .proj
-------------------------
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Pages\Movies\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
  </ItemGroup>

</Project>

For the DbContext. 
---------------------
After click the + and click Add the scaffolding does not generate DbContext file in Data folder. and Data folder does not generate too.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/Scaffolding/issues/1543
