### ISSUE TITLE
View Older Versions of the Razor Pages (ASP.NET) Tutorial

### ISSUE THREAD

**Issue by TrevorSlobodnickSCC** [dotnet/AspNetCore.Docs#21969]
Is it possible to view older versions of the tutorial(s)? I worked through the tutorial last semester for school and built the Razor Pages Movie App without any issues. However, I am working through it again to refresh my memory and I am getting errors after typing in this command: `dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries` which is located on [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code) page. After typing in that command, my connection string inside appsettings.json has the following value:

"Server=(localdb)\\mssqllocaldb;Database=RazorPagesMovieContext-7225042d-eea8-4c28-a403-8f8d16f4d6f3;Trusted_Connection=True;MultipleActiveResultSets=true"

But the old version of the tutorial had you manually type this part in, and you set up a SQLite database with the following connection string value:

"Data Source=MvcMovie.db"

Based on [this stackoverflow post](https://stackoverflow.com/a/45862887), localDB only works on Windows, and I am on a Mac. So I thought an easy solution would be to just find the old tutorial but it doesn't seem like that is an option. Is there some kind of archive I could go to or is that version of the tutorial just gone forever? 

---
#### Document Details

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code#scaffold-the-movie-model)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Is it possible to view older versions of the tutorial(s)? I worked through the tutorial last semester for school and built the Razor Pages Movie App without any issues. However, I am working through it again to refresh my memory and I am getting errors after typing in this command: `dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries` which is located on [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code) page. After typing in that command, my connection string inside appsettings.json has the following value:
> 
> "Server=(localdb)\mssqllocaldb;Database=RazorPagesMovieContext-7225042d-eea8-4c28-a403-8f8d16f4d6f3;Trusted_Connection=True;MultipleActiveResultSets=true"
> 
> But the old version of the tutorial had you manually type this part in, and you set up a SQLite database with the following connection string value:

The scaffolder generates the correct connection string for you.

Use the version selector for previous versions

![image](https://user-images.githubusercontent.com/3605364/113467153-d032a400-93dc-11eb-87aa-6fe3bddfc983.png)
