### ISSUE TITLE
Consolidate ASP.NET to ASP.NET Core migration guidance

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#21966]
In addition to this section on migrating from ASP.NET to ASP.NET Core, we also have an eBook on the topic at https://docs.microsoft.com/dotnet/architecture/porting-existing-aspnet-apps/. We should consolidate all of this migration content into the eBook and then make the "Migration > ASP.NET to ASP.NET Core" node in the ASP.NET Core docs point to the eBook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 60643](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60643)

**Comment by Rick-Anderson** [comment]
@danroth27  @ardalis who's updating the ebook? The ASP.NET Core team doesn't have access to it.

**Comment by ardalis** [comment]
The eBook points to the docs quite a bit. It's meant to be guidance, not low-level how-to, so I wouldn't necessarily recommend doing away with the docs and making the book much heavier. The individual docs articles are in my experience much easier to keep up-to-date than chapters of a book.

That said, the docs team has access to it. @nishanil was my main point of contact on the eBook work, but I believe he's OOO for a bit. HTH.
