### ISSUE TITLE
Correct the initial sentence that moves the user into the wrong type of Azure Active Directory.

### ISSUE THREAD

**Issue by mrgitmr** [dotnet/AspNetCore.Docs#21963]
If this (sentence below) should be "Navigate to Azure Active Directory B2C in" in the sentence below please change as it is a source for error and confusion.

"Navigate to Azure Active Directory in the Azure portal. Select App registrations in the sidebar. Select the New registration button."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce89fc06-2c18-fbf8-0ac5-f50d41a67d8a
* Version Independent ID: 490b7aec-0d31-9032-cb1d-ffcdfea5c976
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrgitmr ... It's correct in its present form.
