### ISSUE TITLE
Incorrect single tag syntax in package reference XML

### ISSUE THREAD

**Issue by gopkumr** [dotnet/AspNetCore.Docs#21974]
The *C# Tooling support for .proto files* section, client project package reference XML is missing single tag closure for Gprc.Tools package reference.
Screenshot as below

![image](https://user-images.githubusercontent.com/1662197/113504043-f4c38300-9578-11eb-9fbd-d6dae7062a5c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7223e694-85ba-4b95-96c8-68ae14753e7c
* Version Independent ID: 28ec8399-ba0e-c995-3ac2-b1f28e93331b
* Content: [gRPC services with C#](https://docs.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/basics.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/basics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
Thanks @gopkumr ... I'll patch that up right now.

**Comment by guardrex** [comment]
Turns out that it's an opening tag ... the full package reference from the file is ...

```xml
<PackageReference Include="Grpc.Tools" Version="2.28.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

However, it is confusing. I'll make that code sample show the **_full_** package reference in the topic to avoid confusion.

**Comment by gopkumr** [comment]
Yes thats correct. I saw that the source csproj has more code to it but the documentation just leaves out the last few lines.  I agree it is better to include the whole tag pairs.

**Comment by guardrex** [comment]
There are a few 🐞 bug fixes this morning ... this and a bad link on another PR. I'll go ahead merge to live. These updates should hit the live site within 15 minutes. Thanks again for the issue on this.

**Comment by gopkumr** [comment]
Thanks for the fix. The documentation looks perfect now. Starters will not face an issue when following the documentation.
