### ISSUE TITLE
Msal and the NavigationManager conflicting in the di container?

### ISSUE THREAD

**Issue by MartijnCarolTREFF** [dotnet/AspNetCore.Docs#21972]
I'm misssing some information versions of blazor etc. I'm planing to update my existing blazor autentication from:
 
```
services.AddAuthentication(AzureADB2CDefaults.AuthenticationScheme).AddAzureADB2C(options =>
{
   Configuration.Bind("AzureAdB2C", options);
}
```
To 

```
services.AddMsalAuthentication(options =>
{
	Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
	options.ProviderOptions.LoginMode = "redirect";
 });
```

Off course I've created a new Aad aplication in azure and removed all b2c logic. With the demo project all works fine. But on my existing application I've the error:

```
InvalidOperationException: Error while validating the service descriptor 'ServiceType: 
Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider Lifetime: Scoped ImplementationType: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService'3[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState,Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount,Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions]': Cannot consume scoped service 'Microsoft.AspNetCore.Components.NavigationManager' from singleton 'Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationOptions`1[Microsoft.Authentication.WebAssembly.Msal.Models.MsalProviderOptions]]'.
```
I'can make the code compile with  commention just these lines so.

```
//services.AddMsalAuthentication(options =>
//{
//	Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
//	options.ProviderOptions.LoginMode = "redirect";
// });
```

Looking at the differences in my old project and the demo project I see 2 diffrences :

1. The program.cs is using the class Startup.cs to set all the services, and the demo does this directly
2. The nuget package    Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.4" is used in the deo code but doesn't copile in my existing app.

So could one off these be the reason that I can't make this work? Am I looking at some wrong version issues or some thing? The current project has the flollowing packages:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  ....
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.4" />
    <!--<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.4" PrivateAssets="all" />-->
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="5.0.4" />
    <PackageReference Include="Blazor.Extensions.Storage" Version="1.0.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="3.0.0" />
    <PackageReference Include="BlazorPro.BlazorSize" Version="3.2.1" />
    <PackageReference Include="Highlight.js" Version="1.0.4" />
    <PackageReference Include="Markdig" Version="0.24.0" />
    <PackageReference Include="MatBlazor" Version="2.8.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Pek.Markdig.HighlightJs" Version="0.5.1" />
    <PackageReference Include="Radzen.Blazor" Version="3.1.11" />
  </ItemGroup>
...

```
I hope this is enough information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b9c5cb-0e48-25bc-2b7e-e7354bafbe2d
* Version Independent ID: b1e8aedc-b46b-41f1-55c1-e293bc6c93db
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MartijnCarolTREFF ... Your best bet to convert an app from AAD B2C to AAD (non-B2C) is probably to work from the AAD topic to create a **_new_** AAD (non-B2C) app, probably with a new AAD registration following the topic's guidance. Confirm the new app runs correctly, then transfer your custom code from the old AAD B2C app to the new AAD (non-B2C) app. In general, an in-place conversion with this many moving parts is often a painful experience because any one little missed thing can result in a 💥 such as this.
