### ISSUE TITLE
There should be a list of the package dependencies required by the generated code

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#21979]
For C# thats at least newtonsoft.json and I think Microsoft.AspnetCore.Mvc.Core (just for ProblemDetails)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to  Container issue for NSwag #16879
