### ISSUE TITLE
Should I use IEmailSender?

### ISSUE THREAD

**Issue by LukeOwlclaw** [dotnet/AspNetCore.Docs#21986]
The [documentation for Microsoft.AspNetCore.Identity.UI.Services.IEmailSender](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.ui.services.iemailsender) reads "This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used directly from your code. This API may change or be removed in future releases."

[This docs page](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio) tells me to implement the interface. Is this really needed? Does the Identity Framework actually use the implementation of `IEmailSender`? The [default implementation](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/UI/src/Areas/Identity/Services/EmailSender.cs) does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, it uses it.

**Comment by LukeOwlclaw** [comment]
Could you please elaborate? What for is it used? I removed my custom implementation of `IEmailSender` and still everything works as expected. Thanks!
