### ISSUE TITLE
Forms Authentication won't work

### ISSUE THREAD

**Issue by marafiq** [dotnet/AspNetCore.Docs#21988]
>When you install the package, it inserts a line into Web.config that tells ASP.NET to use it for most cryptographic operations, including forms authentication, view state, and calls to MachineKey.Protect. The line that's inserted reads as follows.

While recently trying to share authentication cookie between .NET Framework 4.5.x and .NET 5. I found that if code base explicitly calls `FormsAuthenctication.Encrypt` it will not use new data protection API, while view state does work. It should be noted in paragraph likewise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709a375-e1f3-a47a-5f91-6bed1782a594
* Version Independent ID: 53e91296-c75c-b446-1487-6710b024ad60
* Content: [Replace the ASP.NET machineKey in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/replacing-machinekey?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/compatibility/replacing-machinekey.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/compatibility/replacing-machinekey.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  do you want this added?

**Comment by blowdart** [comment]
Well it does say most 🤷‍♂️ I have no preference.

**Comment by marafiq** [comment]
Noting it also does say 'including forms authentication...' as well
