### ISSUE TITLE
As .NET 5 is released - could you provide now working example of using drag events i.e. ondragstart, ondragover and ondrop? 

### ISSUE THREAD

**Issue by Jarek300** [dotnet/AspNetCore.Docs#21985]
Could you provide working example of using drag events i.e. ondragstart, ondragover and ondrop? Example should show how to put data into DataTransfer and DataTransferItem .NET objects and how data is received in ondrop event.

The problem was discussed [here](https://github.com/dotnet/AspNetCore.Docs/issues/19913) and postponed until .NET 5 was released.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Jarek300** [comment]
Ok.
