### ISSUE TITLE
Error in code.

### ISSUE THREAD

**Issue by twojnarowski** [dotnet/AspNetCore.Docs#21990]
Everywhere in the code, "String" starting with a capital letter is used, and that generates a compilation error in Visual Studio. It should be a lowercase "string" to make it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Samouczek: Dodawanie sortowania, filtrowania i stronicowania — ASP.NET MVC z EF Core](https://docs.microsoft.com/pl-pl/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://stackoverflow.com/questions/7074/what-is-the-difference-between-string-and-string-in-c

**Comment by twojnarowski** [comment]
Well, I am fully aware of the difference between a `String` and a `string` in C#. But if you want to use String in your code, you either need to use `System.String`, or `using System;`, and neither of these is present in the code snippets, so for people who don't know the difference, it adds unnecessary confusion and errors.
