### ISSUE TITLE
Missing EntityFrameworkCore key persistence

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetCore.Docs#21996]
The documentation doesn't mention EntityFrameworkCore key persistence: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.entityframeworkcoredataprotectionextensions.persistkeystodbcontext?view=aspnetcore-5.0#Microsoft_AspNetCore_DataProtection_EntityFrameworkCoreDataProtectionExtensions_PersistKeysToDbContext__1_Microsoft_AspNetCore_DataProtection_IDataProtectionBuilder_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@paulomorgado  would you be able to start a PR? I can edit.  @ajaybhargavb and @markmcgookin can you help?
@blowdart cc.

**Comment by markmcgookin** [comment]
PR #22003 Created to cover this.
