### ISSUE TITLE
Using asynchronous MongoClient APIs

### ISSUE THREAD

**Issue by InDieTasten** [dotnet/AspNetCore.Docs#21991]
Following the advice from [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0#avoid-blocking-calls) you should avoid blocking calls to prevent thread pool starvation.

The MongoDB Sample application does not follow these practices. I am not familiar with MongoClient and when it actually does blocking IO over the wire, but in the current tutorial nothing is asynchronous, so I am certain there is potential for optimization. There are asynchronous overloads for quite a few methods.

I would appreciate, if the sample would showcase asynchronous calls to the mongo database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Container list: Create a web API and MongoDB #16196
