### ISSUE TITLE
Confusing example of DisplayFor.

### ISSUE THREAD

**Issue by LeTranAnhVu** [dotnet/AspNetCore.Docs#22000]
[Enter feedback here]
I found the unclear code in https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio#the-create-delete-details-and-edit-pages

In the above section, there is a example of Pages/Movies/Index.cshtml : 
`@Html.DisplayFor(modelItem => item.Title)`

Why does **modelItem** can relate to **item**?

Do I miss something or it is typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/aspnetcore/issues/3956
