### ISSUE TITLE
integrity.ps does not run in Windows powershell 

### ISSUE THREAD

**Issue by carsten-moos** [dotnet/AspNetCore.Docs#22007]
the presented script **integrity.ps** does not run in Windows 10 powershell:
1.) you are using old style if: || is no longer supported, you have to correct to -or
2.) lots of errors like this:

[integrity.log](https://github.com/dotnet/AspNetCore.Docs/files/6279213/integrity.log)

Get-Content : Es wurde kein Parameter gefunden, der dem Parameternamen "AsByteStream" entspricht.
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:191 Zeichen:34
+     $content = Get-Content $File -AsByteStream;
+                                  ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Ausnahme beim Aufrufen von ".ctor" mit 1 Argument(en):  "Der Puffer darf nicht NULL sein.
Parametername: buffer"
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:193 Zeichen:3
+   $dataStream = [System.IO.MemoryStream]::new($content);
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Get-FileHash : Das Argument kann nicht an den Parameter "InputStream" gebunden werden, da es NULL ist.
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:194 Zeichen:42
+   $signature = Get-FileHash -InputStream $dataStream -Algorithm SHA25 ...
+                                          ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-FileHash], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-FileHash

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:197 Zeichen:3
+   $dataStream.Dispose();
+   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Fehler beim Aufrufen der Methode, da [System.IO.Path] keine Methode mit dem Namen "GetRelativePath" enthält.
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:182 Zeichen:3
+   $relativePath = [System.IO.Path]::GetRelativePath($Base, $File.Full ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Get-Content : Es wurde kein Parameter gefunden, der dem Parameternamen "AsByteStream" entspricht.
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:231 Zeichen:40
+   $compressedBytes = Get-Content $File -AsByteStream;
+                                        ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Ausnahme beim Aufrufen von ".ctor" mit 1 Argument(en):  "Der Puffer darf nicht NULL sein.
Parametername: buffer"
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:232 Zeichen:3
+   $compressedStream = [System.IO.MemoryStream]::new($compressedBytes) ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Ausnahme beim Aufrufen von ".ctor" mit 2 Argument(en):  "Der Wert darf nicht NULL sein.
Parametername: stream"
In C:\users\myuser\daten\src\vsCodeCS\integrity.ps1:234 Zeichen:3
+   $decompressionStream = [System.IO.Compression.GZipStream]::new($com ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#disable-integrity-checking-for-pwas)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @carsten-moos.

@javiercn ... The script was [your submission (dotnet/AspNetCore.Docs #20852)](https://github.com/dotnet/AspNetCore.Docs/issues/20852) with ...

> Please remark that this script is provided as a starting point when you have integrity issues in your app and that we don't provide any sort of official support for it (if it doesn't work for your app, you get to adjust it).

... which I stated in the topic as ...

> The script is provided as a starting point when the app has integrity issues that the Blazor framework can't identify. Customization of the script might be required for your apps.

How do you want to resolve this issue? Is it a ...

* `won't-fix` & close with the current doc language.
* `won't-fix` but we should strengthen the doc remarks, perhaps we should state the PS version for the script. Perhaps, we should state more explicitly that the script isn't supported by the PU and that devs should seek community support for *all* use cases with it ... exact phrasing TBD.
* Keep this issue for script work ... but perhaps out past 6.0 GA (i.e., it will need to go on HOLD for the time being).
* Keep this issue for work ... but drop the script/section from the docs on the grounds that it just can't be supported under the workload ... it will break/become unsupported even for whatever version of PS that you used ... and it's just all going to end in tears eventually if we keep it.

**Comment by javiercn** [comment]
@guardrex just mention that it requires powershell **core** 6 or similar (don't remember the exact version) and just point people to check their version with `$PSVersionTable`

**Comment by guardrex** [comment]
@carsten-moos ... Do you want to give PS 6 or PS latest (7.1) a shot and see how it fares?

https://docs.microsoft.com/powershell/scripting/install/installing-powershell-core-on-windows

If u don't want to try it, I'll find some time to run it here (I already have 6 locally). I can try under 7, too.

I'm buried at the moment ⛰️⛏️, but I'll dig out 😅 in a day or two 🤞.

**Comment by carsten-moos** [comment]
Thank you Luke,

I already regarded it as a starting point. I also expected a startable
script. I wanted to put out, that there are problems with it.
You asked me "How do you want to resolve this issue? Is it a ..." or did
you mean javiercn?

<https://github.com/javiercn>

Your 4 options I cannot understand  in all details and did not expect
that reaction. Maybe I did not cover all the rules for this issue.
Sorry, you can do what you want for closing this "and end in tears".

I think, that with blazor becoming more populated, many other will come
across this script for solving sha256 on blazor wasm on problems with
deploying. So maybe someone can redesign this script for better usage.

For me the problem was solved by:


      Deaktivieren der Integritätsprüfung für Nicht-PWA-Apps
      <https://docs.microsoft.com/de-de/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0>

|<BlazorCacheBootResources>false</BlazorCacheBootResources> in the
<PropertyGroup> |

Carsten

Am 08.04.2021 um 16:24 schrieb Luke Latham:

**Comment by carsten-moos** [comment]
Hi Luke,

thank you for your ideas. At the moment I will spend my time with the
blazor project and normally dont 't need a PS .

Carsten

Am 08.04.2021 um 16:51 schrieb Luke Latham:

**Comment by carsten-moos** [comment]
Yes that would help.
I used

PSVersion                      5.1.19041.610
PSEdition                      Desktop


Am 08.04.2021 um 16:43 schrieb Javier Calvarro Nelson:

**Comment by guardrex** [comment]
That list was for discussion with Javier. I was presenting options on how to proceed with this issue.

"End in tears" :cry: just means that there is a sequence of events that one day will end up with a broken, useless script here ...

* The script runs in PS 6 today.
* The script might **not** run in PS 7 or later versions.
* PS 6 will fall out of support at some point in the future.
* Eventually, we will have a broken script with current, supported PS versions.

I don't know if that will happen. The best thing for me (or you) to do is try it under PS 6 and under PS 7. I'd like to see if it breaks in both cases. Then, I'll know what to write about it in the document.

If you install PS 6, PS 7, or both, and try running it ... let me know if you get it running. I'm 🏃😅, so it will save me time if you find out in either or both cases.

**Comment by guardrex** [comment]
@carsten-moos ... Sorry for the delay getting back to this. I've been 🏃 on other issues.

@javiercn ... I can't get the `integrity.ps1` script running on PS7, nor can I test it with PS6 because apparently PS7 is an in-place upgrade for PS6. If I try to get PS6, the PS6 installer complains that it can't run because a newer version of PS is on my system.

When I execute the script in a PS7 console, it seems like the script is malformed somehow in the `New-BlazorFile` function. I think it's malformed because the script seems to hang in there without throwing an error.

How do you want to proceed? :ear: Do you want to ...

* Leave this here labeled for PU work later, perhaps assigned to you.
* Open an issue on the PU repo. Resolve this docs issue after the PU issue is closed out.
* We keep the 'this is just a starting point' language and close out this issue with a PR that updates the doc to say that the script is for PS6 only, not PS7.
* I can try to troubleshoot further; however, I don't have VSC happily debugging PS7 at this time, nor have I really worked in PS to any degree since PS5 ... it's probably not efficient for me to spend docs 💰 on it.
* Do something else.

**Comment by javiercn** [comment]
@guardrex the script is provided as a starting point to troubleshoot these types of issues. I don't plan to offer bug fixes or support for it beyond the initial drop. People can change the script to make it work on the environment or manually perform the same checks that the script tries to automate.

**Comment by guardrex** [comment]
Thanks @javiercn ... We say it's a starting point, but we don't currently state the exact version of the script. I'll call that out and close this.
