### ISSUE TITLE
Incorrect path on Windows

### ISSUE THREAD

**Issue by petrkoutnycz** [dotnet/AspNetCore.Docs#22002]
Hi, I suppose there is a bug in the path on Windows.
Page says: `%APPDATA%\Microsoft\UserSecrets`
On my machine it is: `%APPDATA%\Roaming\Microsoft\UserSecrets`

I'm running preview 2 of .NET 6 SDK, though I think it's been the same all along.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
```
cd %APPDATA%\Microsoft\UserSecrets

C:\Users\rickk\AppData\Roaming\Microsoft\UserSecrets>
```

```
cd %APPDATA%\Roaming\Microsoft\UserSecrets
The system cannot find the path specified.
```

**Comment by petrkoutnycz** [comment]
Oh man, you're right. That was stupid of me, sorry. I did not think that APPDATA stands for "Roaming" as well. I had to make some kind of another typo. Thank you.
