### ISSUE TITLE
 "Add new OpenAPI service reference" documentation is lacking

### ISSUE THREAD

**Issue by user1568891** [dotnet/AspNetCore.Docs#22006]
The help page https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.0 unfortunately doesn't have a lot of detail about the screen it is linked from, the "Add new OpenAPI service reference" wizard in Visual Studio. That page only seems to have information about the command line tool.

![image](https://user-images.githubusercontent.com/12611912/114039104-b0b5d400-983f-11eb-8b39-902c86b6fb1b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.0)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
