### ISSUE TITLE
Update MessagePack article for .NET 6

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#22008]
Update this section for https://github.com/aspnet/Announcements/issues/454. The breaking change is doc'd here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/messagepack-library-change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-6.0#javascript-client)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  have you used SignalR?

**Comment by fiyazbinhasan** [comment]
I have few ideas. I can take a look at this 🚀

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan I'm going to work on it and hopefully you can review it.

**Comment by fiyazbinhasan** [comment]
Sure. that would be great! I'll get to learn about message pack 😁
