### ISSUE TITLE
Where is the redirect to login configured?

### ISSUE THREAD

**Issue by jdege** [dotnet/AspNetCore.Docs#22009]
I have been trying to work through this example.

In _Layout.cshtml, two links are created, one to "/Index" and one to "/Contact".

Clicking "/Index" directs you to the Index page. Clicking "/Contact" page directs you to the Contact page, if you're logged in, and to the login page if you are not.

Where is this distinction implemented in the code? Where do we code or configure that '/Contact" requires login and "/Index" does not?

And where is it coded or configured that when you need to log-in, that it's "/Account/Login" that you are redirected to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jdege ... Details that aren't called out can be found in the sample app in most cases. For example pertaining to authorization for the Contact page ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie/samples/3.x/CookieSample/Startup.cs#L16

The path for login is by convention, but can be changed.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#create-full-identity-ui-source

**Comment by guardrex** [comment]
There's also a whole doc on RP conventions. See ....

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-5.0

**Comment by jdege** [comment]
I think that explains what's going on in that sample app, thanks.

But if my site doesn't have Razor pages, but is instead built with MVC?

The app I'm actually trying to get authentication working for doesn't have a call to services.AddRazorPages(), it has a call to services.AddMvc(), and that doesn't seem to work the same way.

(And we already have [Microsoft.AspNetCore.Authorization.Authorize] decorating the controllers.)

**Comment by Rick-Anderson** [comment]
@jdege  take a look at 

* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-5.0
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio

And related.
