### ISSUE TITLE
Login with Facebook page is outdated

### ISSUE THREAD

**Issue by Chirimorin** [dotnet/AspNetCore.Docs#22014]
The information on how to obtain an App ID and Secret for Facebook is outdated, the Facebook developer page has been updated to be targeted at management and marketing with actual developer features hidden out of the way.  
Not only is it now hard to find the login or app creation buttons, but the process on Facebook itself also ensures that you'll spend as much time as possible trying to find the page where they're willing to display the App Secret. 

Please update the documentation to match the new and convoluted Facebook "developer" page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The FB for dev UI changes so frequently we need to remove our instructions and leave that to FB.

dup of  #20955
