### ISSUE TITLE
Issue in Student Model in tutorial EF core with Asp.Net Core

### ISSUE THREAD

**Issue by MohammedPapad** [dotnet/AspNetCore.Docs#22018]
Hi,

I found that in the sample Contoso University Web App, the Student model should not have the field EnrollmentDate, reason is, say I Mohammed Papad enroll for Asp.Net MVC in Jan 2021 so Student table will have one record of mine, now say for example my course got completed in Jan end itself and I am given certificate so it's over, now I came back in April 2021 to Contoso University for enrollment of new course Asp.Net Core, now Student table has already my record with my FirstName and LastName, now if new record is created for Asp.net Core it will duplicate the data just for one field i.e. EnrollmentDate.
My suggestion is to move EnrollmentDate to Enrollment table or model which will solve this issue.

Thanks and regards,
Mohammed Papad.
Sr. Microsoft Dotnet Developer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
There are lots of changes that could be made to the schema.
