### ISSUE TITLE
`UseExceptionHandler()`   only catches unhandled exceptions, correct?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#22026]
pretty sure its not going to intercept something like this in my code

``` csharp

var stuff = FunctionThatAlwaysReturnsNullString();
try
{
 someOtherCodeThatCalls =  stuff.Trim();
}
catch (Exception e)
{
    // This is OK when it happens
}
//...more code

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes. @serpent5  should we make that more clear?

**Comment by serpent5** [comment]
We could change:

> The Developer Exception Page displays detailed information about request exceptions.

-to-:

> The Developer Exception Page displays detailed information about _unhandled_ request exceptions.

...and...:

> Catches and logs exceptions.

-to-:

> Catches and logs _unhandled_ exceptions.

That's not much of a change, but I think including "unhandled" like that would cover it. @Rick-Anderson Do you think that would be enough?

**Comment by Rick-Anderson** [comment]
> it. @Rick-Anderson Do you think that would be enough?

Sounds great. Do you want to PR this?

**Comment by serpent5** [comment]
@Rick-Anderson Sure. It's a quick one so I'll do it through GitHub now...

**Comment by Rick-Anderson** [comment]
@StingyJack thanks for bringing this to our attention. Fix makes for a much clearer doc.

**Comment by StingyJack** [comment]
It helps that I'm easily confused

**Comment by Rick-Anderson** [comment]
I see you have a strong SO score. PR's are welcome and good issues like this. Have you reviewed [Razor Pages with Entity Framework Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio) ?
