### ISSUE TITLE
[HTTPS] Correct instructions to use the HTTPS development certificate on wsl

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#22021]
In [this section](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux)

Replace the existing instructions with the following:
* Export the developer certificate to a file on **Windows**
   ```console
   dotnet dev-certs https --ep C:\<<path-to-folder>>\aspnetcore.pfx -p <<password>>
   ```
* Import the exported certificate on the WSL instance
  ```console
  dotnet dev-certs https --clean --import /mnt/c/<<path-to-folder>>/aspnetcore.pfx -p <<password>>
  ```

This is a one time operation per certificate and per wsl distro compared to having to export the certificate over and over (if you update/regenerate the certificate on windows you might need to run it again)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-on-linux)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by glen-84** [comment]
@javiercn

This still doesn't work for me. When running `dotnet watch` I get:

> warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.

I have followed your instructions above, and I've also done the [Ubuntu trust the certificate for service-to-service communication](https://learn.microsoft.com/en-gb/aspnet/core/security/enforcing-ssl#ubuntu-trust-the-certificate-for-service-to-service-communication) part (on Debian in WSL).

What am I missing? This should work with the default paths used by Kestrel, right?

(dotnet 7, OpenSSL 1.1.1n, etc.)
