### ISSUE TITLE
No information on customizing an ITicketStore?

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/AspNetCore.Docs#22025]
There're some good community posts about this, which speak directly to the use case we have, which is managing user sessions across devices (specifically supporting idle and manual session expiration).

https://ml-software.ch/posts/implementing-a-custom-iticketstore-for-asp-net-core-identity
https://ml-software.ch/posts/implementing-a-custom-iticketstore-for-asp-net-core-identity-update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  I'm guessing we don't have the resource to document customizing an `ITicketStore`

If you or the product team can do this, reopen the issue and assign as appropriate.
