### ISSUE TITLE
Add alternative way to conditionally enable runtime compilation of Razor pages

### ISSUE THREAD

**Issue by Miggleness** [dotnet/AspNetCore.Docs#22028]
The documentation currently shows one way to conditionally enable runtime compilation of Razor pages, involving setting and environment variable.  I'd be nice to also show an alternative option in `Startup.cs`.

```csharp
// Store IWebHostEnvironment in the Startup's property
public Startup(IConfiguration configuration, IWebHostEnvironment env)
{
  Configuration = configuration;
  Env = env;
}

public IWebHostEnvironment Env { get;}

public void ConfigureServices(IServiceCollection services)
{
   var mvcBuilder = services.AddControllersWithViews();
   if (Env.IsDevelopment())
   {
        mvcBuilder.AddRazorRuntimeCompilation();
   }

    // code omitted for brevity
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a trivial step from the example:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages()
        .AddRazorRuntimeCompilation();

    // code omitted for brevity
}
```

What's the harm of `AddRazorRuntimeCompilation` in all environents?

**Comment by Miggleness** [comment]
> That's a trivial step from the example:
> 
> ```
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddRazorPages()
>         .AddRazorRuntimeCompilation();
> 
>     // code omitted for brevity
> }
> ```
> 
> What's the harm of `AddRazorRuntimeCompilation` in all environents?

The reason why it isn't enabled by default, you dont want that behavior outside of development.

**Comment by Rick-Anderson** [comment]
@captainsafia should this be added?

**Comment by mustex** [comment]
I was specifically looking for this callout in the documentation.  This is a better option if you want runtime compilation on some environments rather than within the launch configuration which only affects running from visual studio (which for us is not the DEV environment since we have more than three environments).  Having a sample for MVC (rather than Razer Pages) as well as choosing specific environments would have helped me while researching this capability since is important to us that our apps don't use runtime compilation in production.
