### ISSUE TITLE
CLI command in example doesnt work in PowerShell

### ISSUE THREAD

**Issue by kondelik** [dotnet/AspNetCore.Docs#22034]
```
dotnet aspnet-codegenerator identity -u WebApp1User -fi Account.Register;Account.Manage.Index
```

doesnt work in PowerShell. (It work in older CMD) becouse it doesnt recognize `;` as file/params delimeter but as command delimeter and ends 

```
Account.Manage.Index : The term 'Account.Manage.Index' is not recognized as the name of a cmdlet, function, script file
, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and t
ry again.
At line:1 char:74
+ ... tor identity -u WebApp1User -fi Account.Register;Account.Manage.Index
+                                                      ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Account.Manage.Index:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Should be:

```
dotnet aspnet-codegenerator identity -u WebApp1User -fi "Account.Register;Account.Manage.Index"
```

(i just added quotation marks) and it will work in both PowerShell and CMD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by kondelik** [comment]
For working example in doc, see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=netcore-cli#scaffold-register-login-logout-and-registerconfirmation (this one have quotation marks and works fine in PowerShell)

**Comment by Rick-Anderson** [comment]
Just above [Standalone or hosted Blazor WebAssembly apps](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=netcore-cli#standalone-or-hosted-blazor-webassembly-apps)

PowerShell uses semicolon as a command separator. When using PowerShell, escape the semi-colons in the file list or put the file list in double quotes. For example:
