### ISSUE TITLE
Windows specific paths in platform independent EF-RP example

### ISSUE THREAD

**Issue by cpjolly** [dotnet/AspNetCore.Docs#22035]
Perhaps the platform independent documentation and code samples should not use Windows-specific paths ? For example the SQLite database context connection string in the ef-rp [appsettingsSQLite.json](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/appsettingsSQLite.json) file is defined to be

`  "ConnectionStrings": {
    "SchoolContext": "Data Source=c:\\tmp\\CU.db"
  }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's really only used in the optional build step. Those who want to build on non-windows platforms are expected to know a valid path.

**Comment by cpjolly** [comment]
A lot of non-windows developers are unfamiliar with ASP.NET and EF, so might not understand that that this is the path to the database file. If they just change it to /tmp, they may get caught out because /tmp is normally cleared on reboot in unix & macOS. Perhaps a comment in the text that they need to use a valid & permanent local path, as was the case in the previous version of this file ?

**Comment by Rick-Anderson** [comment]
> If they just change it to /tmp, they may get caught out because /tmp is normally cleared on reboot in unix & macOS. 

That's a good reason to change it. @JeremyLikness what should we change the non-windows connection string to?

> Perhaps a comment in the text that they need to use a valid & permanent local path, as was the case in the previous version of this file 
Where did it say that?

[Previous version](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.1&tabs=visual-studio-code#database-connection-string-1)

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "SchoolContext": "Data Source=CU.db"
  }
}```



> Perhaps the platform independent documentation and code samples should not use Windows-specific paths ? For example the SQLite database context connection string in the ef-rp [appsettingsSQLite.json](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/appsettingsSQLite.json) file is defined to be
> 
> ` "ConnectionStrings": { "SchoolContext": "Data Source=c:\\tmp\\CU.db" }`
> 

` "ConnectionStrings": { "SchoolContext": "Data Source=c:\\tmp\\CU.db" }` is not windows specific, it's a relative path on non-windows platforms. We don't want to get into OS specifics. This is an advanced tutorial and developers at this level are familiar with the OS.

**Comment by JeremyLikness** [comment]
Good catch! Looping in @bricelam ... Brice, any thoughts re: the appropriate cross-platform connection string?

**Comment by bricelam** [comment]
Why isn't it relative to the app? (E.g. `Data Source=CU.sqlite3` or `Data Source=App_Data/CU.db`)

**Comment by Rick-Anderson** [comment]
> Why isn't it relative to the app? (E.g. `Data Source=CU.sqlite3` or `Data Source=App_Data/CU.db`)
It is.
I'll  change it from `"SchoolContext": "Data Source=c:\\tmp\\CU.db"`  to  `"SchoolContext": "Data Source=CU.db"`
