### ISSUE TITLE
継承後のテーブルをPersonに変更すべきではないでしょうか。

### ISSUE THREAD

**Issue by mtomo39** [dotnet/AspNetCore.Docs#22032]
[Please enter your feedback here] I am
copying the sutras for learning.

https://docs.microsoft.com/ja-jp/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0#add-person-to-the-model

SchoolContext.cs
の
modelBuilder.Entity().ToTable("Student");
modelBuilder.Entity().ToTable("Instructor");

Each

modelBuilder.Entity().ToTable("Person");
modelBuilder.Entity().ToTable("Person");

it might be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---

[フィードバックをこちらに入力してください]
学習のため写経させていただいています。

https://docs.microsoft.com/ja-jp/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0#add-person-to-the-model

SchoolContext.cs
の
modelBuilder.Entity<Student>().ToTable("Student");
modelBuilder.Entity<Instructor>().ToTable("Instructor");

はそれぞれ、

modelBuilder.Entity<Student>().ToTable("Person");
modelBuilder.Entity<Instructor>().ToTable("Person");

ではないでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [チュートリアル: 継承を実装する - ASP.NET MVC と EF Core](https://docs.microsoft.com/ja-jp/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is the correct code:

```
using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Data
{
    public class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Course> Courses { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<OfficeAssignment> OfficeAssignments { get; set; }
        public DbSet<CourseAssignment> CourseAssignments { get; set; }
        public DbSet<Person> People { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>().ToTable("Course");
            modelBuilder.Entity<Enrollment>().ToTable("Enrollment");
            modelBuilder.Entity<Student>().ToTable("Student");
            modelBuilder.Entity<Department>().ToTable("Department");
            modelBuilder.Entity<Instructor>().ToTable("Instructor");
            modelBuilder.Entity<OfficeAssignment>().ToTable("OfficeAssignment");
            modelBuilder.Entity<CourseAssignment>().ToTable("CourseAssignment");
            modelBuilder.Entity<Person>().ToTable("Person");

            modelBuilder.Entity<CourseAssignment>()
                .HasKey(c => new { c.CourseID, c.InstructorID });
        }
    }
}
```

Try your approach and let me know what happens.

**Comment by mtomo39** [comment]
すみません。コードをコピーしたときに欠落していました。

SchoolContext.cs
の

```
modelBuilder.Entity<Student>().ToTable("Student");
modelBuilder.Entity<Instructor>().ToTable("Instructor");
```

はそれぞれ、

```
modelBuilder.Entity<Student>().ToTable("Person");
modelBuilder.Entity<Instructor>().ToTable("Person");
```

ではないでしょうか、というのが前回の質問内容です。

```
modelBuilder.Entity<Student>().ToTable("Student");
```

のままでデバッグモードで実行すると、DbInitializer　の　Initialize　の
```
if (context.Students.Any())
```
の行で例外が発生します。
```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Invalid object name 'Student'.
  Source=Core Microsoft SqlClient Data Provider
```
出力されているSQL文は下記です。

```
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [Person] AS [p]
        INNER JOIN [Student] AS [s] ON [p].[ID] = [s].[ID]) THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
```

例外が発生する原因は「Student」テーブルがデータベースに存在しないからではないかと思い
```
modelBuilder.Entity<Student>().ToTable("Person");
modelBuilder.Entity<Instructor>().ToTable("Person");
```
と修正したところ、例外が発生しなくなりました。
