### ISSUE TITLE
"The name 'Host' does not exist in the current context"

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#22046]
[EDIT by guardrex to add the metadata. @OddEyesMage, when an issue is opened from the bottom of the topic with the **This page** feedback button and form, it adds metadata to the issue and pings the topic author automatically.]

---
**Issue moved from MicrosoftDocs/feedback#3594**
- Please respond to @OddEyesMage.

---

_From @OddEyesMage on Sunday, April 4, 2021 1:48:08 AM_

When I tried to follow the tutorial and right when I get to where I need to setup the add scaffold I see that in my Program.cs I have an error saying that 'the name "Host" does not exist in the current context'. I do not understand what I am doing wrong, I have retried this numerous times, I have followed the tutorial, yet I keep getting this error the only difference is that I am using NET Core 2.2 instead of 5.0. If anyone can tell me why this issue is happening it would be much appreciated. For context im referring to this https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3594**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Sunday, April 4, 2021 1:48:09 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by Rick-Anderson** [comment]
> I am using NET Core 2.2 instead of 5.0

.NET Core 2.2 is out of support.
