### ISSUE TITLE
MVC totorial: There is already an object named 'Course' in the database

### ISSUE THREAD

**Issue by AnasAlhejaili** [dotnet/AspNetCore.Docs#22051]
[Enter feedback here]

In Migration, at the ASP.Net Core MVC totorial
Using both CLI and PMC I got the following error:
"There is already an object named 'Course' in the database".
Help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [Tutorial Part 5, apply migrations to the Contoso University sample](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a good error. Easiest thing is to [Drop and re-create the database](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model)

**Comment by Rick-Anderson** [comment]
To fix this:

Make an include and add to both series that point to [Drop and re-create the database](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model)

**Comment by Rick-Anderson** [comment]
The first instruction was missed

![image](https://user-images.githubusercontent.com/3605364/117521852-b0e2e580-af4b-11eb-95c6-f7cea78930c7.png)
