### ISSUE TITLE
Possible section rename and minimal code/style improvements

### ISSUE THREAD

**Issue by agap2-ag** [dotnet/AspNetCore.Docs#22058]
After learning the basics in [VS Code's Blazor module](https://docs.microsoft.com/en-us/learn/modules/build-blazor-webassembly-visual-studio-code/?ns-enrollment-type=Collection&ns-enrollment-id=5xo6hjyrgjg8qp), I followed the link to this todo-list tutorial and I found it as relevant as the module itself, complementing very well the material in there.

So after finishing it, I noticed some margin for improvement:
- the [_Next Steps_](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0#next-steps) section contains a _Summary_ of what the tutorial provided (possible rename?)
- add bootstrap classes
- add an `@onkeydown` event handler for detecting Enter presses on the _Add Todo_ input
- add alert with the most recently added item

## Example

Original:

![Blazor todo-list current version](https://user-images.githubusercontent.com/48947803/114909443-0b899580-9e15-11eb-84e3-947aeae28d29.png)

After adjustments:

![Blazor todo-list with bootstrap classes](https://user-images.githubusercontent.com/48947803/114906478-f9f2be80-9e11-11eb-8cf2-bac15788e010.png)

If this is useful, feel free to use parts or the code below entirely:

```csharp
@page "/todo"

<h3>Todo (@todos.Count(todo => !todo.IsDone))</h3>

<section class="w-50">
  <ul class="list-unstyled">
    @foreach (var todo in todos)
    {
      <li class="input-group mt-1">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <input type="checkbox" @bind="todo.IsDone" />
          </div>
        </div>
        <input class="form-control" @bind="todo.Title" />
      </li>
    }
  </ul>

  <div class="input-group">
    <input class="form-control" placeholder="Some thing todo" @bind="newTodo" @onkeyup="HandleTodoInput" />
    <div class="input-group-append">
      <button class="btn btn-outline-primary" @onclick="AddTodo">Add todo</button>
    </div>
  </div>

  @if (!string.IsNullOrWhiteSpace(recentTodo)) { 
    <div class="alert alert-success mt-2" role="alert">
      Recently added: <span class="font-weight-bold">@recentTodo</span>
    </div>
  }
</section>

@code {
  private List<TodoItem> todos = new();
  private string recentTodo;
  private string newTodo;
  private void AddTodo()
  {
    if (!string.IsNullOrWhiteSpace(newTodo))
    {
      todos.Add(new TodoItem { Title = newTodo });
      recentTodo = newTodo;
      newTodo = string.Empty;
    }
  }

  private void HandleTodoInput(KeyboardEventArgs e)
  {
    if (e.Code == "Enter" || e.Code == "NumpadEnter")
    {
      AddTodo();
    } else {
      recentTodo = string.Empty;
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @agap2-ag ... Thanks for the feedback, but we won't make changes to this tutorial at this time outside of bug fixes. Management created and tested this tutorial for use with new users. They even went as far as having a live coding experience with devs new to Blazor with this tutorial, interacting with the developers as they worked through it and making updates to the tutorial in response to the data and feedback that they collected. They're happy with it in its present form. Thanks for the feedback tho.
