### ISSUE TITLE
Config certificate authentication: how to  use nginx proxy

### ISSUE THREAD

**Issue by github-amazingboy** [dotnet/AspNetCore.Docs#22054]
when i use nginx proxy, and config proxy_set_header X-SSL-CERT $ssl_client_cert;
the response status code is 400, 

when i remove the config, it is ok.

netcore doesn't receive too long header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
This document only covers IIS. nginx configuration is out of scope, however you can tweak the [max header size](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxrequestheaderstotalsize?view=aspnetcore-5.0#Microsoft_AspNetCore_Server_Kestrel_Core_KestrelServerLimits_MaxRequestHeadersTotalSize) if that's the problem (you'd see that in the server logs)


Furthermore you'll need to configure a custom header decoder for nginx, something like this

```c#
services.AddCertificateHeaderForwarding(options =>
{
    options.CertificateHeader = "YOUR_CUSTOM_HEADER_NAME";
    options.HeaderConverter = (headerValue) => 
    {
        // for Nginx use HttpUtility.UrlDecode
        var clientCertificate = new X509Certificate2(HttpUtility.UrlDecodeToBytes(headerValue));
           /* or some other weird conversion logic to create an X509Certificate2 */
        return clientCertificate;
    }
});
```

the nginx misc

**Comment by Rick-Anderson** [comment]
per @blowdart 
> We should find an nginx person internally and figure out how to do it well

@blowdart  who can I `@mention` to help find the right resource?

**Comment by Rick-Anderson** [comment]
@shirhatti @halter73 @jkotalik who can provide help on Config certificate authentication: how to use nginx proxy?

**Comment by github-amazingboy** [comment]
```nginx
server{
        listen 443 ssl;
        server_name demo.com;
        ssl_certificate /etc/ssl/nginx.crt;
        ssl_certificate_key /etc/ssl/nginx.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;
		
	ssl_verify_client on;  
	ssl_verify_depth 1;
	ssl_client_certificate /etc/ssl/trustClient.cer;

         location / {
		proxy_pass  http://host.docker.internal:5000/;
		proxy_set_header Host $host;
		proxy_set_header X-SSL-CERT $ssl_client_cert;
		proxy_set_header X-SSL-CERT-Fp $ssl_client_fingerprint;
	}
	location /print.txt {
		set $cert $ssl_client_cert;
		return 200 $cert;
	}
	location /s.asp {
		proxy_pass  http://host.docker.internal:80;
		proxy_set_header  X-Real-IP  $remote_addr;
		#proxy_set_header Host $host;
		proxy_http_version 1.1;
		proxy_set_header X-SSL-CERT $ssl_client_cert;
		#proxy_set_header X-SSL-CERT-Fp $ssl_client_fingerprint;
		proxy_set_header Connection keep-alive;
		proxy_set_header Keep-Alive 600;
		keepalive_timeout 600;
	}
    }
```
```C#
services.AddCertificateForwarding(options =>
{
    options.CertificateHeader = "X-SSL-CERT";
    options.HeaderConverter = (headerValue) =>
    {
        var clientCertificate = Helper.CertHelper.GetX509Certificate(headerValue);
        return clientCertificate;
    };
});

app.UseCertificateForwarding();

//HomeController.cs
var clientCertificate = this.HttpContext.Connection.ClientCertificate;
```

when i access /s.asp , the page can show X-SSL-CERT header and its content , the s.asp is under my iissite.
when i access /print.txt, it can download the txt file which content is the certificate pem format, it contains many \n char.
when i access /, it is http 400 error.
when i access / with postman, it is ok, i can get clientCertificate .  
**the postman header value box is a singleline textbox**.

i seach the error, maybe it is the nginx'error, please fllow the link [Problem with multiline $ssl_client_cert HTTP header in proxy mode](https://trac.nginx.org/nginx/ticket/857).

some applications can read multiline header such as iis, but the kestrel cannot.

In the end, which should be changed, the nginx or kestrel ?
