### ISSUE TITLE
PostAsJsonAsync section is out of date.

### ISSUE THREAD

**Issue by ToiWright** [dotnet/AspNetCore.Docs#22063]
The PostAsJsonAsync section needs to be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @ToiWright ... I'll look in the morning, but can u be more specific?

**Comment by ToiWright** [comment]
It is late here. So – I will have to be quick.

 

The help document says the following:

 <https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.postasjsonasync> PostAsJsonAsync: Sends an HTTP POST request, including JSON-encoded content, and parses the JSON response body to create an object.

 

But, PostAsJsonAsync returns an HttpResponseMessage.

 

Toi
