### ISSUE TITLE
Missing step about DbContext connection string

### ISSUE THREAD

**Issue by gjaryczewski** [dotnet/AspNetCore.Docs#22076]
It looks like the fragments about DbContext, appsettings.json and connection string, which are available in docs for 3.1 version, is not available now, so scaffolding with Visual Code is not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@gjaryczewski  nothing has changed, the tutorial now generates all of those things. It works great with VSC.
