### ISSUE TITLE
traduzione automatica alla lingua italiana

### ISSUE THREAD

**Issue by Hybrid1973** [dotnet/AspNetCore.Docs#22079]
English translation

[Enter your comments here]
The translation into the Italian language is not bad;
however there are things that are really "terrible" like the phrase:
" specify the Home controller and the Privacy action. " which should be " specify the Home controller and the Privacy action ".

The following instead causes the reader to get lost at first sight:
" The Index method in has HelloWorldController executed the return View () statement; " which should be " The Index method in HelloWorldController has executed the return View () statement; "

In general then there are errors such as "the className class, the methodName method, the view viewName" instead of "the className class, the methodName method, the view viewName".

If whoever is reading this ticket is Italian, they will understand my doubts ...

----

[Immetti qui i commenti]
La traduzione alla lingua italiana non è male;
tuttavia ci sono cose che sono veramente "terribili" tipo la frase:
"_specifica il Home controller e l' Privacy azione._" che dovrebbe essere "**specifica il controller Home e l'azione Privacy**".

Il seguente invece causa proprio smarrimento nel lettore a una prima vista:
"_Il Index metodo in ha HelloWorldController eseguito l'istruzione return View();_" che dovrebbe essere "**il metodo Index in HelloWorldController ha eseguito l'istruzione return View();**"

In generale poi ci sono errori tipo "la className classe, il methodName metodo, la viewName vista" invece di "la classe className, il metodo methodName, la vista viewName".

Se chi sta leggendo questo ticket è italiano, capirà le mie perplessità...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
*
---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Parte 2, aggiungere un controller a un'app MVC ASP.NET Core](https://docs.microsoft.com/it-it/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JasonCard  can someone review this and let me know if there is anything I can do to help the MT. It doesn't look like words need to be code fenced to prevent over-translation.

**Comment by JasonCard** [comment]
Will update if there's any reply from the escalation, but there is no ETA and may take time, so closing this ticket for now.
