### ISSUE TITLE
the doc is conflicted between the previous layout and nested layout and the code is not easy to keep track and follow

### ISSUE THREAD

**Issue by JayNg17x** [dotnet/AspNetCore.Docs#22077]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d64b8062-f910-a918-c5db-b2b67708602c
* Version Independent ID: 56c6cc6e-be94-d164-947c-cb14dbe91a19
* Content: [ASP.NET Core Blazor layouts](https://docs.microsoft.com/en-us/aspnet/core/blazor/layouts?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JayNg17x ... A nested layout is just one layout nested inside of another layout. What do you mean by "previous layout"? That phrase doesn't appear in the document.

**Comment by guardrex** [comment]
I took a look at the section and example, and I don't see a problem with it, even the rendered output of the three components is shown.

1. The `DoctorWhoLayout` is nested inside of the `ProductionsLayout`.
2. The `Episodes` component uses the `DoctorWhoLayout`.
3. You end up with nested layouts. `Episodes` > `DoctorWhoLayout` > `ProductionsLayout` ... and the rendered HTML output is shown.

Can you explain further what you find confusing?

Perhaps, it should show a nested diagram before the first layout to explain the goal ... like .......

&#42; `ProductionsLayout`
&nbsp;&nbsp;&#42; `DoctorWhoLayout`
&nbsp;&nbsp;&nbsp;&nbsp;&#42; `Episodes`

**Comment by guardrex** [comment]
@JayNg17x ... I read it again. I don't see a glaring problem with the explanation. I'm going to close and continue to collect feedback on it. Let me know here if you can say specifically what you find confusing. I can re-open the issue for work if I'm just not seeing the problem.
