### ISSUE TITLE
Tutorial: Handle concurrency: There is already an object named 'Course' in the database

### ISSUE THREAD

**Issue by AnasAlhejaili** [dotnet/AspNetCore.Docs#22078]
[Enter feedback here]

Hello,
after using dotnet ef migrations add RowVersion and then updating the database I get this error:

Error Number:2714,State:6,Class:16
There is already an object named 'Course' in the database.

it's similar to the one I posted in part 5 of the tutorial
.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6081e36d-a501-324b-3d5a-e0554658d301
* Version Independent ID: 232ef04e-563a-86b4-e397-1359bb5579ca
* Content: [Tutorial: Handle concurrency - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/concurrency.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
SQLite?

**Comment by Rick-Anderson** [comment]
BTW, the [RP version](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio) is much more up to date.
