### ISSUE TITLE
Documentation request - discussion of Authentication and Swagger UI

### ISSUE THREAD

**Issue by John-Garland** [dotnet/AspNetCore.Docs#22070]
It would be helpful if the documentation here also considered addressing or introducing the use of Authentication with the Swagger UI page. It's probably a bit of a judgement call to decide how deeply to document things here vs the 3rd party page, but an introductory mention may be advisable.

Extending that a little bit, it would also be helpful to have the content team here collaborate with the Swashbuckle content/content maintainers to move the default guidance (a suggestion to update their page) away from Implicit flow and focus more deliberately on Auth Code/PKCE as the default/page-0 content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
