### ISSUE TITLE
Provide a more meaningful environment variable example!

### ISSUE THREAD

**Issue by drathnow** [dotnet/AspNetCore.Docs#22071]
[EDIT by guardrex]

Perhaps you might consider providing a more meaningful example for setting log level through environment variables.   For example, how you set environment variables for something like this:

```
"Logging": {
    "Console": {
      "LogLevel": {
        "Microsoft.Hosting.Lifetime": "Trace"
      }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @drathnow ... It's in this section ...

https://docs.microsoft.com/aspnet/core/fundamentals/logging/#set-log-level-by-command-line-environment-variables-and-other-configuration

**Comment by drathnow** [comment]
Thanks for the reply but I don't see the answer.  The section you
reference has the answer for

Logging:LogLevel:Microsoft=Trace

It does not have the answer to my question.  How would you define an env
variable for:

Logging:LogLevel:Microsoft.Foo.Man.Choo=Trace

There are no examples that show how to define a variable using namespace or
class that contains dots ".".

**Comment by guardrex** [comment]
It's the same pattern ... for an env var for something like ...

```
Microsoft.Hosting.Lifetime
```

... one would set the env var ...

```
Logging__LogLevel__Microsoft.Hosting.Lifetime
```

... so the command (if setting it via command) would be like ...

```
set Logging__LogLevel__Microsoft.Hosting.Lifetime=Trace
```

... if you were setting it via `launchSettings.json`, it would be like ...

```json
"environmentVariables": {
  "ASPNETCORE_ENVIRONMENT": "Development",
  "Logging__LogLevel__Microsoft.Hosting.Lifetime": "Trace"
}
```

... and that should do the trick. Give it a shot with your setup and key and see if it works.

WRT to the topic, Rick will be along in a bit to see if this should be called out. We only call out the double-underscore for colon scenario because that's the main scenario that breaks. He'll decide if a remark about periods is a good idea or not.

**Comment by Rick-Anderson** [comment]
I'll add https://stackoverflow.com/a/65459743/502537 to the samples.

**Comment by drathnow** [comment]
Thanks Luke,

That clears it up. I have been having problems configuring  logging in a
Docker container and was wondering if it was because of variable naming.
Nothing I tried seemed to work and the documentation page I reference,
while helpful, doesn't make it clear that dots would work.  Since
namespaces are rarely one level deep, it would be really helpful to add at
least one sample showing a variable with a namespace that contains dots.

Cheers,
Dave.
