### ISSUE TITLE
Correção de ortografia

### ISSUE THREAD

**Issue by thdq** [dotnet/AspNetCore.Docs#22084]
Translation to English
The document Packaging and reducing static assets in ASP.NET Core available at https://docs.microsoft.com/pt-br/aspnet/core/client-side/bundling-and-minification has a spelling error in the document title .
---

O documento **Empacotar e reduzirr ativos estáticos no ASP.NET Core** disponível no link https://docs.microsoft.com/pt-br/aspnet/core/client-side/bundling-and-minification possui erro de ortografia no título do documento.

--

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

---

Exclusivamente na palavra **reduzirr** deveria ser **reduzir**.

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Empacotar e reduzirr ativos estáticos no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-5.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs.pt-br/blob/live/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@JasonCard how should I be handling these? This looks like a MT problem I can't correct from English.

**Comment by JasonCard** [comment]
@thdq Thank for your feedback. This article is machine translated, so there may be translation quality issue. Please let us know if there is a critical misspelling issue and if so, what is the incorrect and proposed fix. 
@Rick-Anderson Please go ahead and close this issue as we will not fix minor misspelling issue for machine translated content.
