### ISSUE TITLE
Not enough information about Roles

### ISSUE THREAD

**Issue by suchoss** [dotnet/AspNetCore.Docs#22094]
Pretty please, add some more info about roles - `AspNetUserRoles`. If someone needs to migrate from old MVC where they used this table for roles then there is no information here.

I needed `[Authorize(Roles = "Admin")]` attribute to work. With following piece of code (in startup.cs) it didn't work:
```
services.AddDefaultIdentity<ApplicationUser>()
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
```

I couldn't find any solution in documentation, but after some time spent on google I found a _solution_ here:
https://github.com/aspnet/Identity/issues/1813

Specifically this code:
```
services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultUI()
            .AddDefaultTokenProviders()
```

But this is nowhere properly explained so I am not sure if what I am doing is proper way or some _kind of hack_.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/Identity/pull/1832 which fixes this problem.

**Comment by suchoss** [comment]
@Rick-Anderson I went quickly through https://github.com/aspnet/Identity/pull/1832, but I am not sure if I understand that. 

My today's story is that I started a new .NET 5 project with user authentication, scaffolded identity, migrated users (AspNet tables) and their roles. And according this documentation https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-5.0 tried to use following just to check if it works (my user has the Administrator role in **AspNetUserRoles** table assigned)
```
[Authorize(Roles = "Administrator")]
public class AdministrationController : Controller
{
}
```

My startup looked like here https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#add-role-services-to-identity
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>(
        options => options.SignIn.RequireConfirmedAccount = true)
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>();
```
But it didnt work - I kept getting false on `User.IsInRole()` method.


So a bit confused by documentation (I would say that at least I am missing more description in documentation), I started searching on internet and find solution (posted by HaoK - https://github.com/aspnet/Identity/issues/1813#issuecomment-394543909) which works fine for me. I am just wondering if this solution is "stable".
```
 services.AddIdentity<ApplicationUser, IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultUI()
            .AddDefaultTokenProviders()
```

I hope my sentences makes sense. My english is not perfect. I just wanted to ask if it is possible to add this solution into the documentation. Maybe somewhere here on this page https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-5.0

Thanks a lot.

**Comment by Rick-Anderson** [comment]
@haok I thought  https://github.com/aspnet/Identity/pull/1832  fixed this. If that's not the case I'll document this.

> not sure if what I am doing is proper way or some _kind of hack_.

Not a hack, those were (are) the  API's required and documented.

**Comment by HaoK** [comment]
I'm not sure, if @suchoss could provide a full repro of the non working behavior in an app I can try, I can see what's going on.  There's not enough info from just the startup to tell what the issue is, as that looks like it should work

**Comment by Rick-Anderson** [comment]
@suchoss please provide the simplest possible GitHub project that reproduces your problem and we'll investigate.

**Comment by suchoss** [comment]
@Rick-Anderson @HaoK 
Sincerely sorry guys. Now I feel like a dumbass. I must have been tired yesterday and did some mysterious mistake - I can't reproduce this issue. Not in a new project - not even in the old one if I revert changes.

**Comment by Rick-Anderson** [comment]
@suchoss  That's what happens with the simplest possible repo :)
