### ISSUE TITLE
Any Changes in .Net 6?

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#22095]
I am going back through this tutorial for .Net 6 Preview. (I went through it last year for .Net 5.)  I see the .Net 5 tutorial is being used for .Net 6 Preview.  Are there going to be any changes in .Net 6 Release and will the tutorial be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Not that I know.
Try the Razor Pages versions, it's much more up to date with best practices and the new EFC 5 M:M
