### ISSUE TITLE
Wish you guys would no longer align yourselves with IdentityServer4 since it has become a commercial product.

### ISSUE THREAD

**Issue by cosmoKenney** [dotnet/AspNetCore.Docs#22098]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cosmoKenney ... Please see :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/20106#issuecomment-703275657. Although the focus of management's decision there isn't on commercial versus free, they've decided to continue regardless for the time being.
