### ISSUE TITLE
I have never been in contact with asp net identity, how to learn asp net core identity systematically?

### ISSUE THREAD

**Issue by Sc7-git** [dotnet/AspNetCore.Docs#22096]
[在此处输入反馈]

Dear senior, Hello:
I have never been in contact with asp net identity, how to learn asp net core identity systematically?
I read security/authentication and security/authorization/ under the asp net core document, I have practiced all my examples, except for examples such as spa, Azure, and third-party authentication.
But I still don’t understand how asp net core identity works, such as:
1. How does jwt work in identity, how to issue tokens to users, and how to verify users' tokens.
2. There is no detailed introduction to RoleManager, UserManager, and SignInManager in the document, especially RoleManager at all. Although I know that these auxiliary classes are to operate identity
For the database, since there is no specific document or demo, I still don't know what scenarios these functions are used in.
3. https://docs.microsoft.com/en-us/learn/modules/secure-aspnet-core-identity/ There are only simple cases.
5. Is there a step-by-step document, or recommend some information.
There is an urgent need to master this part of knowledge, and I hope my predecessors will advise. 
Poor English, please understand. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---

#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 90aa2423-5082-413f-1009-86b353c27cf6
* Version Independent ID: 84241d82-3261-1225-d1f9-a94d38f6155b
* Content: [ASP.NET Core 中的授权简介](https://docs.microsoft.com/zh-cn/aspnet/core/security/authorization/introduction?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/introduction.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/authorization/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hello @Sc7-git,

Your English is excellent and I understand and agree with you. ASP.NET had detailed documents on all these features.

I can suggest the following:

* https://docs.microsoft.com/zh-cn/learn/modules/secure-aspnet-core-identity/
* https://docs.microsoft.com/aspnet/core/security/authentication/identity-api-authorization
* https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity&tabs=visual-studio
* https://docs.microsoft.com/aspnet/core/security/authentication/add-user-data&tabs=visual-studio
* https://docs.microsoft.com/aspnet/core/security/authentication/add-user-data&tabs=visual-studio
* https://docs.microsoft.com/aspnet/core/security/authentication/customize-identity-model
* https://docs.microsoft.com/aspnet/core/security/authentication/identity-configuration

@mkArtakMSFT  @HaoK  Do you want to dedicate time to write some of these docs?

**Comment by Sc7-git** [comment]
Hello @Rick-Anderson ，
I have seen all the cookie examples above. Is there any jwt related?

**Comment by Sc7-git** [comment]
Hello @Rick-Anderson ，
aspnetcore\src\Security\Authentication\JwtBearer\samples\JwtBearerSample
这个示例中也仅有客户端代码。没有认证服务器代码。

**Comment by Sc7-git** [comment]
Hello @Rick-Anderson ，
aspnetcore\src\Security\Authentication\JwtBearer\samples\JwtBearerSample
There is also only client code in this example. There is no authentication server code.

**Comment by HaoK** [comment]
@blowdart for his thoughts as well

**Comment by blowdart** [comment]
Yea we do a poor job. At some point I'll be doing a channel 9 video which might make a good starting point for an approach.

For the original question jwt isn't linked to identity at all. Third party products like identity server do that.

**Comment by Rick-Anderson** [comment]
> At some point I'll be doing a channel 9 video which might make a good starting point for an approach.

ESL folks are unanimous, English language video's are unwatchable. English text doc's are fine. Maybe I can create a doc from your video. Be sure to mention me when it's published.

**Comment by HaoK** [comment]
You can probably dupe this against this issue: https://github.com/dotnet/AspNetCore.Docs/issues/15374
