### ISSUE TITLE
Windows 10 Insiders build needed for gRPC with IIS??

### ISSUE THREAD

**Issue by richardbartley** [dotnet/AspNetCore.Docs#22107]
You state gRPC needs;

†IIS requires .NET 5 and Windows 10 Build 20241 or later.
‡HTTP.sys requires .NET 5 and Windows 10 Build 19529 or later

Does this mean (at time of writing) I need to be running Windows 10 Insiders Build Version?
If so, could that be made clearer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#add-grpc-services-to-an-aspnet-core-app)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by guardrex** [comment]
Hello @richardbartley ... In the *Protocols* topic, it's clearer, so we can do that here, too.

It was phrased this way ...

> May require use of Windows Insider Builds.

I'll add that to the instruction here; **_BUT_** before taking action, there might be a version mismatch here.

@BrennanConroy ...

Is there a version mismatch in the coverage? The following is what's in the IIS area *Protocols* topic (emphasis added) ...

> Advanced HTTP/2 features to support gRPC
>
> Additional HTTP/2 features in IIS support gRPC, including support for response trailers and sending reset frames.
>
> Requirements to run gRPC on IIS:
>
> * In-process hosting.
> * Windows 10, OS **_Build 20300.1000 or later_**. May require use of Windows Insider Builds.
> * TLS 1.2 or later connection

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/protocols?view=aspnetcore-5.0#advanced-http2-features-to-support-grpc

... and in this topic states (emphasis added) ...

> IIS
>
> Internet Information Services (IIS) is a flexible, secure and manageable Web Server for hosting web apps, including ASP.NET Core. .NET 5 and Windows 10 **_Build 20241 or later_** are required to host gRPC services with IIS.
>
> IIS must be configured to use TLS and HTTP/2. For more information, see Use ASP.NET Core with HTTP/2 on IIS.

https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-5.0&tabs=visual-studio#iis

**Comment by BrennanConroy** [comment]
@JamesNK @Tratcher

**Comment by Tratcher** [comment]
> ... although I need to review how Insider Build numbers are generated/used or be reminded on it. I think 🤔 the Insider Build number becomes the Release Build number when the build is released.

I believe that's correct, the actual released build number will be something higher than the insiders versions we've referenced above.

**Comment by guardrex** [comment]
@Tratcher ... Between showing 20241 or 20300.1000, should I show the latter (20300.1000) in both topics?

**Comment by JamesNK** [comment]
Go ahead. Search to see if 20241 is used in other places and replace those as well.

Fundamentally this probably won't matter to the end-user. The Windows Insiders dev channel is greater than both numbers:

![image](https://user-images.githubusercontent.com/303201/115783794-67ee4580-a411-11eb-9238-c43dbf93755f.png)

https://insider.windows.com/en-us/

**Comment by richardbartley** [comment]
Thanks for the quick responses here.

Background to this:
I figured out as my home PC was working (latest Windows 10 Pro 20H2 release seems fine but my corporate work PC is Windows 10 Enterprise and still on 1909 so 2 major versions behind. 😣
