### ISSUE TITLE
Example for Pass data from .NET code into TypeScript code

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/AspNetCore.Docs#22102]
The link below about Angular in VS is very helpful. Ideally, the more the better.
https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular

On the Angular project generated from VS 2019, I cannot see the code below mentioned on the link below

```
options.SupplyData = (context, data) =>
{
    // Creates a new value called isHttpsRequest that's passed to TypeScript code
    data["isHttpsRequest"] = context.Request.IsHttps;
};

```
https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio#pass-data-from-net-code-into-typescript-code

Is it possible to provide more info on how to Pass data from .NET code into TypeScript code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment]
Moved to container issue: Use the Angular project template with ASP.NET Core #18074

**Comment by MackinnonBuck** [comment]
This topic pertains to server-side rendering, which the current Angular template no longer supports (and the section mentioned in is issue no longer exists in the latest versions of the doc). So, I don't think there's any remaining work to do here.
