### ISSUE TITLE
Obsolete IHostingEnvironment interface reference

### ISSUE THREAD

**Issue by danjagnow** [dotnet/AspNetCore.Docs#22110]
The page references `IHostingEnvironment.ContentRootFileProvider`, but [IHostingEnvironment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostingenvironment?view=dotnet-plat-ext-5.0) is obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson ... This is a quick fix ... I'll knock it out while watching the SpaceX launch. **_Woot!_**

# 🚀👨‍🚀
