### ISSUE TITLE
Not mentioning if razor components can be used in MVC and razor pages projects

### ISSUE THREAD

**Issue by EKanadily** [dotnet/AspNetCore.Docs#22123]
It is not obvious if razor components can be used in MVC and razor pages projects or not. it seem to me that it can be added but its functionality is greatly "reduced". I came to the docs to clarify that but can't find any answer.

thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @EKanadily ... I'll add a remark on it and a cross-link right at the very top of this. It's described in detail in [Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/aspnet/core/blazor/components/prerendering-and-integration).

Leave this issue open ... it will close automatically when the PR merges.

**Comment by guardrex** [comment]
With regard to ...

> but its functionality is greatly "reduced"

... I'm not sure what you mean by that. There's no loss of functionality that I can think of.
