### ISSUE TITLE
Incorrect cmd command

### ISSUE THREAD

**Issue by ManojPrasad1984** [dotnet/AspNetCore.Docs#22127]
net stop was /y
This command should be 
net stop w3svc /y
Please do the needful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ManojPrasad1984 ... There's a difference between the the *Windows Process Activation Service* and *WWW Publishing Service* and why the PU had the guidance state to stop WAS and then restart W3SVC (but I don't recall the exact reason). The commands here are still correct AFAIK, but I admit that their docs are hard to navigate to find similar remarks for the latest versions of Windows Server along the lines of ...

https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj635851(v=ws.11)

... and then trying searches like the following aren't so fruitful ...

* https://www.google.com/search?client=firefox-b-1-d&q=site%3Adocs.microsoft.com%2Fen-us%2Fiis+%22Start+or+Stop+the+Web+Server%22
* https://www.google.com/search?client=firefox-b-1-d&q=site%3Adocs.microsoft.com%2Fen-us%2Fiis+%22net+stop+was%22

The results (of the 2nd search) with this exact command sequence present are in the following current IIS topics ...

* https://docs.microsoft.com/iis/extensions/installing-application-request-routing-arr/install-application-request-routing#step-2--install-microsoft-application-request-routing-version-1
* https://docs.microsoft.com/iis/extensions/installing-application-request-routing-arr/install-application-request-routing-version-2#step-2---install-microsoft-application-request-routing-version-2
* https://docs.microsoft.com/iis/extensions/iis-compression/iis-compression-overview#installation

Most of their docs may focus on using PS these days. I see the commands in the IIS PS Snap-in to start and stop sites and app pools, but not the WAS. It's probably meant to be handled by the usual PS commands for working with services (i.e., `Start-Service`/`Stop-Service`), but they don't say that anywhere as far as I can tell. I think they just have using the IIS Manager UI to do it. IIRC, we had a PS approach here ... *somewhere* ... at one time, but that was several years ago.

@jkotalik @shirhatti, TL;DR ... I feel that would could add this little bit from the (now defunct) IIS topic about `net stop was /y` + `net start w3svc` to help devs understand what they're doing. Their text is (which I'll mostly steal for this) ...

> To stop the web server, you must stop the Windows Process Activation Service (WAS) and the World Wide Web Publishing Service (W3SVC). You can then start the web server when you are ready for the web server to serve content again.

... btw tho ... can you say **_WHY_** this is the case? Even they don't explain it out in that topic, just that this is what one does.
