### ISSUE TITLE
Genre Regular Expression

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#22137]
One of the Genres is seeded with "Romantic Comedy".
But you cannot save from the edit page with this after adding the regular expression validation because the RE does not allow for the one whitespace between the two words.
I changed the Regular to this and it seems to work.
`[RegularExpression(@"^[A-Z]+[a-zA-Z ]*$")]`
`[RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]`   <------ original

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Part 9, add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan easy one to review and fix. Also fix in https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation as appropriate

**Comment by fiyazbinhasan** [comment]
will take a look at it soon :slightly_smiling_face:
