### ISSUE TITLE
route parameter id

### ISSUE THREAD

**Issue by KerivexDan** [dotnet/AspNetCore.Docs#22138]
if the Welcome method contains an ID parameter, how does it also contain an id parameter?  The parameter is case-sensitive, I tried just to be sure.  I am confused as to what the route parameter actually does.  I get the controller and action parts of the explanation, but I don't understand how passing 3?name=Rick in the query string results in a 3 being printed instead of the default value of 1.  

Does this happen because the Startup.cs doesn't care about case?  Is it because any of the datatypes of the Welcome method were matched by the input that occurs before the '?'  (that would make much sense though)

how does an 'anonymous' 3 get put in for the ID parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Keep reading the docs. When you're finished see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing
Use search engines and SO.
