### ISSUE TITLE
Missing '}'

### ISSUE THREAD

**Issue by chrisfokz** [dotnet/AspNetCore.Docs#22133]
When adding the selected courses in the code for Views/Instructors/Index.cshtml file, there is a missing bracket '}'  at the end of the code. 

```
@if (Model.Courses != null)
{
    <h3>Courses Taught by Selected Instructor</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Department</th>
        </tr>

        @foreach (var item in Model.Courses)
        {
            string selectedRow = "";
            if (item.CourseID == (int?)ViewData["CourseID"])
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.ActionLink("Select", "Index", new { courseID = item.CourseID })
                </td>
                <td>
                    @item.CourseID
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Department.Name
                </td>
            </tr>
        }
    </table>
**} <----- Here**
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks @chrisfokz 
Consider the Razor Pages version which is much more up  to date and with best practices.

**Comment by chrisfokz** [comment]
@Rick-Anderson  Thanks for the advice, I will switch over to the Razor tutorial!
