### ISSUE TITLE
Warning about EF Core using shared IMemoryCache instance without specifying size is outdated

### ISSUE THREAD

**Issue by divega** [dotnet/AspNetCore.Docs#22142]
The warning at https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0#use-imemorycache is very prominent in this page and uses EF Core as an example of a memory caching usage that can lead to problems, but the statements about EF Core are actually outdated. 

See See https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.x/breaking-changes#adddbc for the changes in EF Core 3.

Also, the paragraph seems to contain a bit of repetition. 

cc @ajcvickers in case you want to follow up on what exactly changed and cannot find the answer in the previous link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-5.0#use-imemorycache)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ajcvickers** [comment]
See comment on PR: https://github.com/dotnet/AspNetCore.Docs/pull/22145#pullrequestreview-646248512
