### ISSUE TITLE
Recommend increasing keepalive_requests in nginx config

### ISSUE THREAD

**Issue by halter73** [dotnet/AspNetCore.Docs#22141]
Our sample nginx configuration in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx does not configure a keepalive_requests to be higher than its default value of 1000: http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests

In older versions of nginx, this defaulted to 100 leading to even worse perf. We should consider increasing this (to Int32.MaxValue?) in our sample config. It might be worth consulting with nginx experts about why the default is lower. But in [YARP](https://github.com/microsoft/reverse-proxy) for example, there is no per-connection request limit by default.

@sebastienros @Tratcher 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by halter73** [comment]
@Tratcher highlighted this section of the docs which does make me worry that nginx's default value for `keepalive_requests` is working around some memory leak in nginx:

> Closing connections periodically is necessary to free per-connection memory allocations. Therefore, using too high maximum number of requests could result in excessive memory usage and not recommended.

It's also possible they default to this to work around potential per-connection memory leaks in the backend. I've always found it odd that nginx hasn't switched to defaulting to keep-alive connections by now and have wondered if that is the reason. Kestrel's keep-alive timeout (along with nginx's' own `keepalive_timeout` and `keepalive_time` for that matter) should mitigate this "excessive memory usage".

Either way, this is why I've suggested consulting nginx experts about why the defaults are what they are today before making any hasty changes.

**Comment by Rick-Anderson** [comment]
@sebastienros @Tratcher please review

**Comment by Tratcher** [comment]
@Rick-Anderson we are not the nginx experts @halter73 is asking for. We need to refer this question to the nginx project/community directly.

**Comment by Rick-Anderson** [comment]
Posted question to https://nginxcommunity.slack.com/archives/C02MRSU7CKT/p1676586493082559

**Comment by Rick-Anderson** [comment]
[Here's the response](https://app.slack.com/client/T017X0LHM2T/threads) I got back from [nginxcommunity.slack.com](https://app.slack.com/client/T017X0LHM2T/browse-channels):

* you can safely increase keepalive_requests to, say, millions.
* the thing is that sometimes openssl has bugs, sometimes nginx may have problems masked by internal memory allocator. It may also happen that a 3rd party module will have a problem and finding proper balance may be a bit tricky
* in most common scenarios though 1k or 1m doesn't make much difference =) most of users will never have 1M requests in a reasonable time. Those who will can tune nginx themselves
*
