### ISSUE TITLE
Remove releases from the GitHub page as they are not being updated anymore

### ISSUE THREAD

**Issue by DamionGans** [dotnet/AspNetCore.Docs#22148]
On this GitHub repository, there is a releases list of which the latest release has been October last year. Maybe it is a great idea to remove the releases from the repository, because it might look messy or people might think the repository isn't updated since then.

**Comment by guardrex** [comment]
Hello @DamionGans ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
