### ISSUE TITLE
Broken/stale Mongo API tutorial links

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#22149]
From @DamionGans on https://github.com/dotnet/AspNetCore.Docs/pull/22147 ...

> The documentation uses many links to the `https://api.mongodb.com/csharp/current/html/*` site, but that site gives an access denied error following those links. After a quick search I found out that MongoDB now hosts its documentation on GithHub pages at `https://mongodb.github.io/mongo-csharp-driver/[version number]/apidocs/html/`. I inserted the latest version number as version "current" does not exist on the site. I also updated the existing links towards the GitHub pages documentation site to use the latest version of the csharp/.NET driver.

I closed the PR on the grounds that ...

> Linking to a version for a rapidly evolving technology these days is just going to end in **_big tears_** 😢 for us. 😄 .... I think what we should do is come up with another way to reference their API via their landing page at ...
>
> https://mongodb.github.io/mongo-csharp-driver/
>
> ... i.e. ... call it out ... tell readers to search for code-fenced API from there ... something like that. Hard-coded links are going to go very stale, very fast around here.

@prkhandelwal, @Rick-Anderson, I have a little time today ... I'm transitioning from one Blazor UE pass to another today. I can take this issue if you like after we decide how to address it. Assign me if you like.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by steveberdy** [comment]
@Rick-Anderson this should be closed by #22687

**Comment by Rick-Anderson** [comment]
@steveberdy Thanks!
