### ISSUE TITLE
What is the relationship between IAuthorizationService and IAuthorizationHandler?

### ISSUE THREAD

**Issue by aschuhardt** [dotnet/AspNetCore.Docs#22144]
This documentation page starts by introducing the IAuthorizationService interface without providing any implementation or usage examples...  And then never mentions it again.  The rest of the article concerns Requirements and the IAuthorizationHandler interface, and IAuthorizationService never comes up again.

I have two questions:

- What is the relationship between the IAuthorizationService and IAuthorizationHandler?  It's not clear from this documentation.
- If I want to use a custom IAuthorizationHandler implementation do I also need to implement a custom IAuthorizationService?  The service implementation is discussed right at the start of the start of the document but is never mentioned again... So I'm guessing.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0#iauthorizationservice)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
There are samples at https://github.com/blowdart/AspNetAuthenticationWorkshop and https://github.com/blowdart/AspNetAuthenticationWorkshop

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
