### ISSUE TITLE
Add a database context section is incomplete

### ISSUE THREAD

**Issue by keensyo** [dotnet/AspNetCore.Docs#22162]
[フィードバックをこちらに入力してください]
The tab [Visual Studio Code / Visual Studio for Mac] in Add a database context section is incomplete.

<img width="820" alt="ScreenShot" src="https://user-images.githubusercontent.com/28209852/116491592-34119500-a8d5-11eb-81c9-ce90d8f6cd13.png">

Please fix in the same way as the [Visual Studio] tab.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [チュートリアル: ASP.NET Core で Web API を作成する](https://docs.microsoft.com/ja-jp/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code#add-a-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.ja-jp/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's missing? 

```
dotnet new webapi -o TodoApi
cd TodoApi
dotnet add package Microsoft.EntityFrameworkCore.InMemory
code -r ../TodoApi
```
takes care of what's needed.

**Comment by keensyo** [comment]
I apologize for overlooking the command line in "Create a web project" section Visual Studio for Mac tab.
`dotnet add package Microsoft.EntityFrameworkCore.InMemory`

I close this issue.

**Comment by Rick-Anderson** [comment]
No problem. Glad it's working.
