### ISSUE TITLE
Stylesheet should reference AssemblyName not ProjectName

### ISSUE THREAD

**Issue by darcyreimer** [dotnet/AspNetCore.Docs#22163]
The documentation currently indicates that the CSS reference should be to ProjectName.styles.css. It should instead reference the assembly name (e.g. AssemblyName.styles.css).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @darcyreimer ... They're often related via project generation from the project templates, but your suggestion is technically correct.

@daveabrock ... If ur busy, I can update it. :ear:

**Comment by daveabrock** [comment]
Thanks, @darcyreimer - that's a good distinction. @guardrex, I can update it in a little bit, it should be a quick change.

**Comment by guardrex** [comment]
Thanks ... as usual I'm 🏃🗻⛏️😅 and appreciate ur help.
