### ISSUE TITLE
Needs configuration instructions

### ISSUE THREAD

**Issue by Vaccano** [dotnet/AspNetCore.Docs#22166]
It would be useful if this page indicated how to get configuration changes into the container.  

By "Configuration Changes" I mean settings in appsettings.json like Environment, ConnectionString and such.  (Things that change as it moves through testing and deployment.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
config files are like code.

**Comment by Vaccano** [comment]
I have since done the research on this. What I was needing was a link to the environment variables support in the configuration system. That is how you get configuration settings into a container.

There are docs on this. A link from this page would be helpful to those in my scenario.
