### ISSUE TITLE
Docs are amazing!

### ISSUE THREAD

**Issue by codespaceinc** [dotnet/AspNetCore.Docs#22160]
This is amazing! I couldn't find where else to post more feedback so I'm doing it here please feel free to close. Guys, .NET Core docs are AMAZING as well as the framework itself. Very clear explanations and nice examples both to real life and with code snippets. I tend to learn better by reading than watching videos so this is perfect for me. Thank you, ❤ .NET Core/5 !!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5234edfa-92bb-a0a4-c523-ad2d7823e865
* Version Independent ID: 89c82c33-8e4f-93dc-af2f-492350557a4b
* Content: [Resource-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/resourcebased.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/resourcebased.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks!
