### ISSUE TITLE
why we can't use LocalStoragein Asp. Netcore

### ISSUE THREAD

**Issue by saeednoruzi** [dotnet/AspNetCore.Docs#22170]
[Enter feedback here]
would be nice if we had access to LocalStorage in asp.net core apps  I wish Microsoft team implement this features later

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @saeednoruzi ... Thus far, it's only a feature for Blazor Server apps ...

https://docs.microsoft.com/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=server

Outside of that, feedback on the framework must be submitted to the PU ("product unit") on their repo. We just work on docs here. You can open a feature request at ...

https://github.com/dotnet/aspnetcore/issues
