### ISSUE TITLE
Custom User Data correction

### ISSUE THREAD

**Issue by JoeMumm** [dotnet/AspNetCore.Docs#22179]
Identity model customization in ASP.NET Core | Custom user data

The article says to Update the Pages/Shared/_LoginPartial.cshtml which doesn't exist since Identity is provided as a Razor Class Library.

Instead in the Views/Shared/_LoginPartial.cshtml change IdentityUser to ApplicationUser.

@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

Also in the startup.cs there is no services.AddIdentity, use .AddDefaultIdentity; and .AddDefaultUI does not appear to be needed.

     services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
          .AddEntityFrameworkStores<ApplicationDbContext>();
          //.AddDefaultUI();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9869895-9ba2-5027-46cd-89d1d995cba4
* Version Independent ID: 8750939b-6ae5-3b9a-6c32-5e84b7fea22c
* Content: [Identity model customization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/customize-identity-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/customize-identity-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
See scaffold Identity.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity

**Comment by JoeMumm** [comment]
I'm commenting on this article:

Identity model customization in ASP.NET Core
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0

I am not trying to scaffold, just add custom data.  Why are you pointing to the Scaffolding article and if there is something of relevance in there please explicitly point it out rather than leaving one to puzzle as to what you are referring to in a 13 screen long article.

**Comment by Rick-Anderson** [comment]
> The article says to Update the Pages/Shared/_LoginPartial.cshtml which doesn't exist since Identity is provided as a Razor Class Library.

**Comment by fiyazbinhasan** [comment]
I think for `5.0`, the snippet should be updated to,

```
services.AddDefaultIdentity<ApplicationUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();
```

Internally, the `AddDefaultIdentity<TUser>` calls `AddIdentityCore<TUser>` and `AddDefaultUI()`

**Comment by Rick-Anderson** [comment]
I'll take a look. We'll probably use monikers to keep the old version and add a new version.

**Comment by Rick-Anderson** [comment]
Need to

* delete `::: moniker range="<= aspnetcore-1.1"` and the 2.0 moniker sections
* Change `::: moniker range=">= aspnetcore-2.1"` as appropriate. Probably to `::: moniker range=">= aspnetcore-2.1 < aspnetcore-5.0"

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson 

1. Agreed, as these versions lack long term support ( <= 1.1 and =2.0)
2.  `::: moniker range=">= aspnetcore-2.1 < aspnetcore-5.0"` looks good
3. Not sure about `::: moniker range=">0 aspnetcore-5.0"`. `AddDefaultIdentity` was introduced in `2.1` and up until now all the templates (version `2.1`, `3,1` and `5.0`) are using `AddDefaultIdentity`. So second moniker that you suggested can handle everything

**Comment by Rick-Anderson** [comment]
Oops, that should have been the correct min version, either 2.1 or 3.1

`::: moniker range=">= 2.1 aspnetcore-5.0"`
