### ISSUE TITLE
Critical first step missing

### ISSUE THREAD

**Issue by szalapski** [dotnet/AspNetCore.Docs#22177]
Nowhere in this page does it direct the reader to manually insert `<link href="AssemblyName.styles.css" rel="stylesheet">` into their own index.html file or equivalent.  This is a critical step.

Can we add such an instruction to the "Enable CSS isolation" section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
btw ... It's "critical" for upgrades, but not missing from the docs in the sense that it's covered by the Migration topic ...

https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio#update-blazor-webassembly-and-blazor-server-projects

... but, of course, it is a good idea to call it out in the topic.

**Comment by szalapski** [comment]
I encountered this not when upgrading, but when trying out CSS isolation for the first time.

**Comment by guardrex** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/22178.
