### ISSUE TITLE
Costs of CreateProtector

### ISSUE THREAD

**Issue by sitepodmatt** [dotnet/AspNetCore.Docs#22171]
Seems odd to build the instance of this in the constructor, is there a cost to CreateProtector? Can this be clarified in the doc. I guess this pattern is limitation of the DI abstractions not supporting named instances.

If I only used one key can I do this, is there a reason not too?

```
serviceColl.AddSingleton<IDataProtector>(sp => {
  sp.GetRequiredInstance<IDataProtectorProvider>().CreateProtector("just1");
})
```

I think the docs need to clarify why this pattern, the docs explicitly call out that both provider and the instance are threadsafe and then strangely go on with examples of CreateProtector everywhere, is CreateProtector zero cost? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23af4f99-387c-b2f5-3d5b-3d98cfac247c
* Version Independent ID: 0d95b7b7-5e46-5718-ca09-bdae43c86963
* Content: [Consumer APIs overview for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/overview?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/consumer-apis/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Nothing is zero cost. It's good to measure the cost of your services.
