### ISSUE TITLE
NOT: By default, LocalDB database creates .mdf files in the C:/Users/{user} directory.

### ISSUE THREAD

**Issue by RichLoba** [dotnet/AspNetCore.Docs#22188]
Nice tutorial...

As a note the following didn't work for me, but instead tried to build the database in C:\Users directory, not C:\Users/{user} directory. Which failed because of permissions. Once i set permissions on c:\users it worked fine. However i don't believe it is your instructions but some possible bug in the creation of the database (Add-Migration InitialCreate ).

Text in this page:
By default, LocalDB database creates .mdf files in the C:/Users/{user} directory.

Hope it helps, and have a good day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio#sql-server-express-localdb)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What OS? We've never seen this problem before. Hopefully if someone else runs into it, this will help.

**Comment by Rick-Anderson** [comment]
Why did the problem just occur at this stage? This step doesn't change the directory.
