### ISSUE TITLE
Do not translate Kestrel

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs#22180]
It's not a good idea to translate in Italian or other languages the name Kestrel, for the same reason you do not translate Windows as Finestre.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Ospitare ASP.NET Core in un servizio Windows](https://docs.microsoft.com/it-it/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs.it-it/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by GioviQ** [comment]
I still see this
![Ospitare-ASP-NET-Core-in-un-servizio-Windows-Microsoft-Docs](https://user-images.githubusercontent.com/7103057/116806524-daf06e00-ab2d-11eb-8f53-1b63cc7dc7b3.png)

**Comment by Rick-Anderson** [comment]
The change won't be live for at least another week.
