### ISSUE TITLE
go to top or table of content

### ISSUE THREAD

**Issue by saeednoruzi** [dotnet/AspNetCore.Docs#22183]
[Enter feedback here]
it would be nice if, we have ,go to top button ,or go to table of content ,for page like this ,that have a lot of content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @saeednoruzi ... We just work on doc content here. You can open that suggestion at ...

https://github.com/MicrosoftDocs/feedback/issues
