### ISSUE TITLE
Typo in dev-certs command

### ISSUE THREAD

**Issue by jjgriff93** [dotnet/AspNetCore.Docs#22190]
In Trust HTTPS certificate with Windows Subsystem for Linux the command:
```
dotnet dev-certs https --ep C:\<<path-to-folder>>\aspnetcore.pfx
```
should be
```
dotnet dev-certs https -ep C:\<<path-to-folder>>\aspnetcore.pfx
```
(single - for ep as its a short-name)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks @jjgriff93 
I worked in Reading for a month. MSFT sent me over to support the Y2K bug. Best one month paid vacation I ever had, had zero problems.

**Comment by jjgriff93** [comment]
Glad you enjoyed it @Rick-Anderson :) you should pay another visit when things are back to normal!
