### ISSUE TITLE
What should we do when the ItemsProvider throws an exceptions because Cancellation?

### ISSUE THREAD

**Issue by PeterHimschoot** [dotnet/AspNetCore.Docs#22208]
What should we do when the ItemsProvider throws an exceptions because Cancellation. 
For example, using gRPC results in an exception thrown by gRPC when cancellation is requisted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor component virtualization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @PeterHimschoot ... Please ask on the PU ("product unit") repo at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your opening comment so that I can follow the discussion, **_OR_** ping me back over here on this issue if you find out a suitable answer for documentation (I'll re-open this for work with the PU's blessing for coverage).

**Comment by PeterHimschoot** [comment]
Thank you. Should I get a good answer I will let you know and maybe add it to documentation myself

Vriendelijke groeten, Sincères salutations, Best Regards,
Peter HIMSCHOOT
Email: ***@***.******@***.***>
Mobile: +32 475 97 00 84  
Author of Microsoft Blazor<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.apress.com%2Fgp%2Fbook%2F9781484259276&data=01%7C01%7Cpeter%40u2u.be%7C1094b45b18fe4871a67b08d825a782fe%7Cbde242ba8b3149b18e7a9a5399b85bce%7C0&sdata=3F3jXcm9MDZgpayz3iLhpJoKT4QtC7DhTLFFkwxBHhE%3D&reserved=0>
U2U Z1 Research Park 110, B-1731 Brussels (Zellik), Belgium
Tel: +32 2 466 00 16,  Fax: +32 2 466 67 71 www.u2u.be<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.u2u.net%2F&data=01%7C01%7Cpeter%40u2u.be%7C1094b45b18fe4871a67b08d825a782fe%7Cbde242ba8b3149b18e7a9a5399b85bce%7C0&sdata=23idewxvC2eA5WoJdIdWKr8KJXY2%2FhAxr4ppAQJsHQA%3D&reserved=0>

**Comment by guardrex** [comment]
Thanks @PeterHimschoot ... Very good.

Keep in mind that it's best to discuss potential coverage here on the issue before creating a PR.

* Sometimes, we end up refusing to cover a scenario:
  * It's too much of an edge case.
  * It involves a very ugly hack that the PU doesn't want to show.
  * It's something that they're working on for an upcoming release, so it's better to just wait to cover it.
* If we proceed with coverage, submitted content may require a significant amount of refactoring before publishing. For example, code that goes into the sample snippet apps. Doc examples are built by the docs build system going forward. I'm refactoring a lot of code examples now for snippet building.

Ping me back here if you find out that docs could/should cover the scenario. If so, I'll re-open this issue.
