### ISSUE TITLE
ModelState as a parameter for ApplyTo no longer appears to be valid.

### ISSUE THREAD

**Issue by nathanjwtx** [dotnet/AspNetCore.Docs#22207]
[Enter feedback here]
This line from the Action method code causes me errors regarding the ModelState parameter; is it no longer valid?
`patchDoc.ApplyTo(customer, ModelState);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0#the-replace-operation)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's the error. The API hasn't changed. Can you get the same code working with a previous .NET version?

**Comment by nathanjwtx** [comment]
Yes, it was working previously in 2.1 but I was trying to update the course I was following to 5.0.

The build error reads:
`  PointsOfInterestController.cs(141, 49): [CS1503] Argument 2: cannot convert from 'Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary' to 'System.Action<Microsoft.AspNetCore.JsonPatch.JsonPatchError>'`

Hovering over the red squiggly gives me:
`Cannot resolve method 'ApplyTo(CityInfo.API.Models.PointOfInterestForPut, Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary)', candidates are:
  void ApplyTo(CityInfo.API.Models.PointOfInterestForPut, Microsoft.AspNetCore.JsonPatch.Adapters.IObjectAdapter) (in class JsonPatchDocument<PointOfInterestForPut>)
  void ApplyTo(CityInfo.API.Models.PointOfInterestForPut, System.Action<Microsoft.AspNetCore.JsonPatch.JsonPatchError>) (in class JsonPatchDocument<PointOfInterestForPut>)`

**Comment by nathanjwtx** [comment]
here is my full controller method if that helps:
`
        [HttpPatch("{poiId}")]
        public IActionResult PartiallyUpdatePointOfInterest(int cityId, int poiId,
            [FromBody] JsonPatchDocument<PointOfInterestForPut> patchDoc)
        {
            var city = CitiesDataStore.Current.Cities.FirstOrDefault(c => c.Id == cityId);

            if (city == null)
            {
                return NotFound("City not found.");
            }

            var poiToPatch = city.PointOfInterest.FirstOrDefault(i => i.Id == poiId);

            if (poiToPatch == null)
            {
                return NotFound("PoI not found.");
            }

            var pointOfIntToPatch = new PointOfInterestForPut()
            {
                Name = poiToPatch.Name,
                Description = poiToPatch.Description
            };

            patchDoc.ApplyTo(pointOfIntToPatch, ModelState);

            // at this point the ModelState will be valid as the JsonPatchDocument is valid
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            
            // need to recheck validation after document has been applied with this new custom validation
            if (pointOfIntToPatch.Description == pointOfIntToPatch.Name)
            {
                ModelState.AddModelError(
                    "Description",
                    "The provided description should be different from the name");
            }

            if (!TryValidateModel(pointOfIntToPatch))
            {
                // return BadRequest("Name can't match Description!");
                return BadRequest(ModelState);
            }
            
            poiToPatch.Description = pointOfIntToPatch.Description;
            poiToPatch.Name = pointOfIntToPatch.Name;

            return new NoContentResult();
        }
`

**Comment by Rick-Anderson** [comment]
That's a pretty good error message. The API hasn't changed.

**Comment by nathanjwtx** [comment]
Well, maybe if you know what you are doing :)

How does my ModelState differ to what is shown in the example code/documentation?

**Comment by Rick-Anderson** [comment]
Looks like it was tested with 3.1. Can you try that?
cc @tdykstra

**Comment by nathanjwtx** [comment]
It appears I was missing a NuGet package: `Microsoft.AspNetCore.Mvc.NewtonsoftJson`.

Thanks for your help. Hopefully I didn't take up too much of your time.
