### ISSUE TITLE
Blazor Server Authorize Attribute

### ISSUE THREAD

**Issue by EdSF** [dotnet/AspNetCore.Docs#22217]
In the documentation regarding `Authorize` attribute in [WeatherService](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#weatherforecastcontroller), this doesn't seem to have _any_ effect. The "default" seems to be that _all_ controllers in the `Blazor Server` app _require_ authorization. I can actually comment that attribute out and it will still rediect/require Login.

To reproduce:
1. Create any controller - e.g. `FooController` 
2. Add any method - eg. `GetHelloWorld` that returns a `string` (e.g. "hello world")
3. Call this from the Blazor Wasm app, e.g. in the `Counter.razor` (which does **not** have any auth restrictions) .

Result: this call will fail authorization

##### FooController in Blazor server
```
[Route("[controller]")]
[ApiController]
public class FooController : ControllerBase
{
  private readonly ILogger<WeatherForecastController> _logger;
  public FooController(ILogger<WeatherForecastController> logger)
  {
      _logger = logger;
  }

  public string GetHelloWorld()
  {
      var rng = new Random();
      return $"Hello World {rng.Next(19, 100)}";
  }
}
```

##### Added to `Counter.razor` in Blazor Wasm client
```
page "/counter"
@inject HttpClient Http

<h1>Counter @helloWorld</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;
    private string helloWorld;

    private void IncrementCount()
    {
        currentCount++;
    }

    protected override async Task OnInitializedAsync()
    {
        helloWorld = await Http.GetStringAsync("Foo");
    }

}
```

The above **will work** if you register/login (only).

Is this because of the [`HttpClient` configured](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#httpclient-configuration). If so, perhaps expand on the topic?

Otherwise, what have I missed/misconfigured.

The goal is to allow _selectively_ requiring `Authorize` on Controllers/Actions (as it "should").

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @EdSF ...

> Is this because of the HttpClient configured

Yes, take a look at the *Unauthenticated or unauthorized web API requests in an app with a secure default client* section of the *Additional Scenarios* topic ...

https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client

**Comment by EdSF** [comment]
Ahhh....got it. I _did_ miss something in the docs  @guardrex , thank you! 👍


> Hello @EdSF ...
> 
> > Is this because of the HttpClient configured
> 
> Yes, take a look at the _Unauthenticated or unauthorized web API requests in an app with a secure default client_ section of the _Additional Scenarios_ topic ...
> 
> https://docs.microsoft.com/aspnet/core/blazor/security/webassembly/additional-scenarios#unauthenticated-or-unauthorized-web-api-requests-in-an-app-with-a-secure-default-client
> 
> ☝️ It's cross-linked in the _Additional Resources_ section of this topic.

**Comment by guardrex** [comment]
This whole node of WASM security topics is due for a major overhaul (tracked by https://github.com/dotnet/AspNetCore.Docs/issues/19286). I've made a note on there for the *Additional Scenarios* topic about possibly better surfacing this in the individual WASM topics. Thanks for asking ... this **_IS_** how we find out where devs are having trouble with the docs. It's a bit painful ... but when we get the right coverage in the right spot, *future generations will thank us!* 😄

**Comment by EdSF** [comment]
Thanks for the reference! 

Well, I did submit a [PR/proposed change](https://github.com/dotnet/AspNetCore.Docs/pull/22220) in the AspNetCore.Docs repo. I _think_ I did that correctly based on "easy/quick contributions"....but seems moot with the bigger effort...
