### ISSUE TITLE
example on serving content outside wwwroot no longer serves content from inside wwwroot

### ISSUE THREAD

**Issue by ssteiner** [dotnet/AspNetCore.Docs#22219]
I spent quite some time scratching me head until I figured out that the example on how to access red-rose.jpg is incomplete. It shows the whole Configure method, but the way the method is written, with just one access to 

` app.UseStaticFiles`

your app then only serves content from the MyStaticFilesFolder under /StaticFiles. For my applications to also serve content from wwwroot, I had to add the basic

`app.UseStaticFiles();`

*in addition* to the `app.UseStaticFiles(new StaticFileOptions...);` shown in the sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> For my applications to also serve content from wwwroot, 
That's covered at the start of the doc.

**Comment by ssteiner** [comment]
You're correct, it is covered, but the section that covers hosting files outside of wwwroot has this path example

* `wwwroot`
  * `css`
  * `images`
  * `js`
* `MyStaticFiles`
  * `images`
    * `red-rose.jpg`

So it lists wwwroot. I saw wwwroot and immediately assumed that the sample that follows would serve files from both 'MyStaticFiles' and 'wwwroot'. So, I think it would be helpful to have an additional note along these lines:

to combine serving files that reside inside wwwroot and files that reside outside wwwroot, you enable serving files from wwwroot by calling `app.UseStaticFiles()` an addition to `app.UseStaticFiles(new StaticFileOptions...)`.
