### ISSUE TITLE
docs.microsoft.com should be updated ?

### ISSUE THREAD

**Issue by boglungu** [dotnet/AspNetCore.Docs#22216]
Hello AspNetCore , 

Describe the bug
Got multiple errors.

Using ASP.NET Core SDK 5 and VS 2019
Create a new Blazor Server app.
Use all the information available[ here ](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0) and will be impossible to upload any file to server.
My supposition is that the documentation is misleading or maybe incorrect...

After you manage to solve the "ILogger" and "services.AddHttpClient" problems you get to :   

Uncaught (in promise) Error: System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PatchAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PatchAsync(String requestUri, HttpContent content)
   at pi_project.Pages.FetchData.up(InputFileChangeEventArgs e) in C:\xxx\xxx\xxx\xxx\xxx.razor:line 58
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
    at Object.endInvokeDotNetFromJS (blazor.server.js:1)
    at e.<anonymous> (blazor.server.js:10)
    at blazor.server.js:1
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at WebSocket.i.onmessage (blazor.server.js:1)

Usually for a product with a god design you don't need documentation..........
I read multiple times the documentation and implemented several times (from zero on new solutions )without success .
Please tell me , is the product problematic ? is the documentation problematic or I am the problem ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@boglungu ...

The current live topic focuses on uploading a file to a server for hosted Blazor WebAssembly apps.

There are a number of updates to this topic on https://github.com/dotnet/AspNetCore.Docs/pull/22161, which includes guidance for Blazor Server apps. It should merge shortly and go live, perhaps on Friday if I don't hear back from the product unit by then. You can look at the PR diff for the latest guidance.

Alternatively, you can wait a few days until I get those updates published and then look at the live document. I can ping you back here if you like. Let me know if that's best for you. :ear:

**Comment by guardrex** [comment]
BTW ... If you look at the diff on the PR, look at the `FileUpload2` component (`Pages/FileUpload2.razor`) in the Blazor Server common sample app. There's text content in the `file-uploads.md` document that explains aspects of the component, including setting up the app for HTTP requests.

But if that's too much of a pain because of the presence of the docs system code in the raw markdown file, then I can ping you back in a couple of days when the updates are live.

**Comment by boglungu** [comment]
Thank you for replay!
I will study the info from your side.
You can ping me anytime.

What I try to accomplish is to have a single Blazor Server app witch should have the ability to send ( upload ) file from the Clint to Server .

My app is developed for a raspberry platform, and I try to avoid WebAssembly .
( but first I debug locally )

Maybe my skills are at a very low ( small ) level , but my initial comment want also to reveal that for a beginner sometimes the official documentation is not very friendly.

 I truly appreciate what you manage to accomplish via Blazor. Is a fantastic product overall !!! But I am afraid that lack of basic functionality ( very well documented) there will be a very show adoption of this technology…

**Comment by guardrex** [comment]
I made some updates to the PR. I think we should show the right approach for saving a file with a Blazor Server example.

However, I really need the PU ("product unit") to look that over before merging it. Pranav already told me to be careful with the streams ... specifically, not to recommend reading them directly (e.g., `ReadToEndAsync`). He also said that copying to a `MemoryStream` is a bad practice. The new Blazor Server example on the PR is copying to a `FileStream` tho, so I can't say at the moment if the updated guidance is exactly right. I'll wait until tomorrow (Friday) and then ping Pranav to see if the PR is still on his radar.

Let's leave this issue open for the moment. That way, I can send you an update here on what's going on with the guidance. I hope it will only take a day (or a couple) to get everything resolved and get the new topic into the live doc set.

**Comment by guardrex** [comment]
@boglungu ... We just decided (offline) to go ahead and merge the guidance. The instruction for Blazor Server to copy to a `FileStream` is correct and covered by the topic. The PR has been merged, and the topic is live now. The (English-US) topic is at the following link (you may need to reload the page). If you need the localized version of the doc (non English-US), that usually takes up to two weeks to appear online.

https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=server

If you run into problems with the new guidance, use the **This page** feedback button+form at the **_bottom of the English-US topic_** to open a new issue.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

I'm going to close now as answered. Thanks for your feedback. :rocket:

**Comment by boglungu** [comment]
I managed to make it work thank to you ! God job ! Thank you ! Beautiful team !
