### ISSUE TITLE
Resource is not an EndPoint or an AuthorizationFilterContext

### ISSUE THREAD

**Issue by nkkarasu** [dotnet/AspNetCore.Docs#22228]
When i check the resource in a simple Web Api project (.Net 5), it is not an EndPoint instance or AuthorizationFilterContext instance as documentation describes. 

I get resource as DefaultHttpContext.

Below is how i configure enpoints:

```c#
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecks("/liveness", new HealthCheckOptions
                {
                    Predicate = r => r.Name.Contains("self")
                });
                endpoints.MapHealthChecks("/hc", new HealthCheckOptions()
                {
                    Predicate = _ => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
            });
```

And that is how i try to get what the resource is:

```c#
        protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
            PbsAuthorizationRequirement requirement)
        {
            if (context.Resource is Endpoint endpoint)
            {
                // ... nothing in here
            }

            if (context.Resource is AuthorizationFilterContext filterContext)
            {
                // ... nothing in here
            }

            if (context.Resource is HttpContext httpContext)
            {
                // ... every thing is in here
                var actionDescriptor = httpContext.GetEndpoint()?.Metadata.GetMetadata<ControllerActionDescriptor>();
            }

            context.Succeed(requirement);

            return Task.CompletedTask;
        }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  please review.

**Comment by serpent5** [comment]
@Rick-Anderson This changed in v5: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/5.0/authorization-resource-in-endpoint-routing.
