### ISSUE TITLE
Blazor docs need to be streamlined

### ISSUE THREAD

**Issue by PhilParisot** [dotnet/AspNetCore.Docs#22230]
# Issue description

It's hard to read the Blazor docs in a streamlined fashion base on my personal experience reading the docs, I'm quite green when it comes to using web frameworks for front-end development.

One suggestion I'd like to make is swapping the spots of the "fundamentals" section with "components" (both under "Web Apps -> Blazor") because the "routing" article under "fundamentals" assume fair bit of Razor markup and components knowledge in order to follow.

I was reading the .NET 5 version of the docs.

**Comment by guardrex** [comment]
Thanks for the feedback @PhilParisot. I've added this to a tracking issue for doc overhauls on #19286 that I'm working down right now. One way to address the problem with the *Routing* topic is to have the *Routing* topic move to the *Compoents* node or move it out into the open ToC as the first topic **_below_** the *Components* node. There could even be a super-slimmed down *Routing* topic left in the *Fundamentals* node that just covers the bare basics. I'll take a look at our options and see what I can do with it. Thanks again for your feedback!

**Comment by PhilParisot** [comment]
Awesome @guardrex thanks for the quick reply!

**Comment by guardrex** [comment]
@PhilParisot ... I just took a look at this subject on the UE passes, and I would need more information on exactly what's confusing to address further in any given topic in this node (or section of a topic in this node). These articles in the *Fundamentals* node are more general ... i.e., at the *app level* ... than the building block of the Blazor framework, *components*, but there is ...

* A significant amount of component coverage before reaching this node.
  * Overview has basic component anatomy and cross-links to the Razor syntax topic.
  * Hosting models covers SPA concepts for the two models.
  * Get started tutorials have quite a bit of basic component coverage as the dev gets their feet wet with the framework and two sample apps (a 'build your first' and a more advanced 'build a Todo List app').
  * Project structure covers basic app anatomy, including the built-in components of the project templates ... what they do and what they're called.
* A number of component explanations and examples to go with the fundamentals coverage.

I scanned down the *Routing* topic, and I don't see anything that isn't explained earlier, explained in place, and/or cross-linked, often with examples. (However, I am just scanning it quickly 🏃.) I think to proceed with further content in any given section I'd need specific feedback on exactly what's confusing.

**Comment by PhilParisot** [comment]
Hey @guardrex sorry for late reply!

It's been a while since I've read "Routing" I can't recall specifically where I was having trouble. Gimme some time and I'll eventually give it another read. I'll reopen another issue for it. Thank you for following up!
