### ISSUE TITLE
Visual Studio Issues

### ISSUE THREAD

**Issue by arseyam** [dotnet/AspNetCore.Docs#22245]
[EDIT by guardrex to add the metadata]

I discovered that - during running the Scaffolding task - if you don't run Visual Studio in administrator mode you will get tons of issues that are not clearly saying you don't have enough permissions.

like this one!
![image](https://user-images.githubusercontent.com/16021754/117540111-39c65380-b016-11eb-8c9e-582dd9d9f29b.png)

If you can add the statement "Run Visual Studio in Administrator mode" to the beginning of tutorial this will fix lots of issues!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@arseyam ... I just asked that you re-open the issue from the English-US topic that you're looking at because there are tutorials that use scaffolding and we have a scaffolding topic. We can't understand which topic you're looking at if you don't use the **This Page** feedback button and form at the bottom of the English-US topic when you open the issue.

**Comment by arseyam** [comment]
@guardrex here is the link to the tutorial 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
You don't need to run VS in admin mode.

**Comment by arseyam** [comment]
Then why the error didn't go until I ran VS in admin mode?

**Comment by Rick-Anderson** [comment]
That can happen for many of reasons, for example, file permissions. We don't want customers running in admin mode. We have 50K folks/month reporting success without admin mode.
