### ISSUE TITLE
Provide a code sample for the RequireAuthorization method on the "Require authenticated users" paragraph

### ISSUE THREAD

**Issue by BrightSoul** [dotnet/AspNetCore.Docs#22247]
Hey guys, I'm linking an issue I opened on the `aspnetcore` repo as reference.
[https://github.com/dotnet/aspnetcore/issues/32518](https://github.com/dotnet/aspnetcore/issues/32518)

I think the ["Requiring authenticated users" paragraph](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-5.0#require-authenticated-users) in the documentation should include @pranavkm [code sample](https://github.com/dotnet/aspnetcore/issues/32518#issuecomment-835464267) about using the `RequireAuthorization` method. This should be the suggested alternative to using a global `AuthorizeFilter` but the documentation is suggesting a `FallbackPolicy` which does not actually provide an equivalent behavior.

**Comment by guardrex** [comment]
Hello @BrightSoul ...

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
