### ISSUE TITLE
Visual Studio Issues

### ISSUE THREAD

**Issue by arseyam** [dotnet/AspNetCore.Docs#22244]
I discovered that - during running the Scaffolding task - if you don't run Visual Studio in administrator mode you will get tons of issues that are not clearly saying you don't have enough permissions.

like this one!
![image](https://user-images.githubusercontent.com/16021754/117539375-02a27300-b013-11eb-8f63-93f7e2945704.png)

If you can add the statement "Run Visual Studio in Administrator mode" to the beginning of tutorial this will fix lots of issues!

**Comment by guardrex** [comment]
Hello @arseyam ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
