### ISSUE TITLE
Inline middleware example doesn't compile in Routing doc

### ISSUE THREAD

**Issue by mikebrind** [dotnet/AspNetCore.Docs#22242]
The inline middleware example in the [ASP.NET Core Endpoint Definition section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0#aspnet-core-endpoint-definition) needs to be corrected. Currently, the first line is

`app.Use(next => context =>`

That should be 

`app.Use((context, next)  => `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mikebrind** [comment]
Ignore

**Comment by Rick-Anderson** [comment]
Hey @mikebrind, love your tutorials. I'd like to start pointing to more of them where you go in more depth. Great work on https://www.mikesdotnetting.com/

**Comment by mikebrind** [comment]
@Rick-Anderson Thanks for your kind words and apologies for wasting your time on this non-issue. 

Feel free to link to anything you find useful. Also, I'm happy to consider ideas for new articles if there are areas you'd like to see covered.

**Comment by Rick-Anderson** [comment]
Any chance you could PR a few articles and improve them. I'd put you as the lead author and that would drive traffic to your site. We need to get an exception approved to point to 3rd party articles, that's why it's very rare.

**Comment by mikebrind** [comment]
I'm happy to help where I can, but at the moment, I'm writing a book on Razor Pages which is taking up a lot of time. I'm not sure how much I can commit to outside of that. Do you have any examples of the articles you have in mind, and what kind of improvements you are looking for?

**Comment by Rick-Anderson** [comment]
I'll mention you in the issues as I find them. Looking forward to your book.

**Comment by Rick-Anderson** [comment]
Awesome! Contributions welcome and where relevant, add a link to you book in [Additional resources](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md?plain=1#L1026)

Anytime you make non-trivial improvements to an article, add yourself (or I can) to the authors list. If we can help customers succeed with links to your book where we have gaps, it's a `win:win:win`

I'm guessing I can refresh my preview copy of your book now.
