### ISSUE TITLE
[Https] Linux: Instructions for trust on Fedora 34

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#22251]
I roughly followed the steps in the comment below.
https://github.com/dotnet/aspnetcore/issues/32361#issuecomment-837111639

I don't think we should document this until we have a clear set of steps that we've verified with a clean machine, however I want to leave here the set of steps I mostly followed in case someone is looking for this, wants to try it out and improve the docs with a proper set of steps to follow

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?tabs=netcore-cli&view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
I won't be spending time creating a set of "vetted" steps to ensure they are correct, however I got this to work and want to make sure the steps/sources I used are somewhat visible for anyone wanting to try this out and come up with a validated set of steps.

**Comment by omarerc** [comment]
Check this Fedora Documentation

Set up a .NET development environment
[https://fedoramagazine.org/set-up-a-net-development-environment/]
