### ISSUE TITLE
Document specific DPAPI dependencies in ASP.NET

### ISSUE THREAD

**Issue by MV10** [dotnet/AspNetCore.Docs#22263]
Please document the specific scenarios where ASP.NET has dependencies on the Data Protection API.

The referenced page, and related pages ([hosting](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-5.0#data-protection) and [config](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0) are two examples) emphasize the importance of configuring DPAPI in load balanced web farms. However, if the application developer does not encrypt data, it isn't clear _exactly_ when or why ASP.NET itself requires DPAPI. The only concrete example I've found in the docs is an anti-XSRF token. I do realize some uses are probably optional (perhaps the _Identity_ extensions also use it, for example -- just a guess).

For example, if I'm only using Kestrel to host a simple Web Socket middleware server, it seems unlikely there is a role for DPAPI, but without documented dependencies, it seems unsafe to make this assumption, which means I'm forced to contemplate a more complex startup/config than is probably actually necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb49e16-b543-30ae-88e5-2241836e2510
* Version Independent ID: d42b1eab-9682-ea69-f203-e519b456a56f
* Content: [ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  please review.

**Comment by MV10** [comment]
@blowdart Yes, data protection, is there any other way DPAPI could be interpreted?

How would one prove data protection is not in use? I don't think protect/unprotect calls are logged, although I feel any use of in-memory keys should probably be logged just to draw attention to them (I think you call this "ephemeral"). But that's an issue outside of docs.

If it's truly that pervasive, I suppose it would be better to clearly state we should always assume data protection is in use. 

And in that case I think ASP.NET should also log a warning when "ephemeral" storage is used at startup. I realize I'm straying from "documentation here", but I am a senior dev with one of your largest corporate customers, and I have run across many, many teams working on real apps who don't have the slightest idea what DPAPI key-ring storage is or means. I'm trying to get the word out, but I find they stumble into it only after their apps reach the point that they start deploying to lower-lane load-balanced servers, at which point it becomes difficult to understand and troubleshoot. (And if I were to stray further, it's also a major pain-point that we can't easily distribute the key-ring among live/live geo-dispersed DCs... I should probably open an issue to discuss.)

I'd still personally like to know exactly where it is used within the MS ecosystem, but I can see how that could be a future maintenance headache, and you make a good point about 3rd party usage.

**Comment by blowdart** [comment]
DPAPI is a windows api that data protection can use under the hood hence my confusion.

And ephemeral key rings do log a warning on startup.

Regardless I'll have a think about how word that it's pretty much always in use.

**Comment by MV10** [comment]
@blowdart Ah, gotcha ... my use on Linux has been pretty limited (and you couldn't _give_ me a Mac) but that makes sense.

I'll proceed as if it's always needed and push it to the others that way. Thanks!!
