### ISSUE TITLE
`c:\tmp` assumed to exist

### ISSUE THREAD

**Issue by dharmatech** [dotnet/AspNetCore.Docs#22261]
In the section [Database connection string](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio-code#database-connection-string), there's a reference to `c:\\tmp`:

![image](https://user-images.githubusercontent.com/20816/117756936-ed287700-b1d3-11eb-85fb-08e7c2dace1f.png)

As far as I can tell, there isn't a step instructing the user to create `c:\tmp`.

On my system, `c:\tmp` didn't exist. So when I ran the app and went to the `Students` link, the following was the result:

![image](https://user-images.githubusercontent.com/20816/117757041-24972380-b1d4-11eb-9133-b23d00cd3234.png)

I changed it to `c:\temp` (which does exist on my system) and the app  ran fine.

Some options to consider:

- Have the user create `c:\tmp`
  - Seems a bit heavy-handed
- Place `CU.db` in the project folder 
- Place `CU.db` in their home directory
- Use some other standard temp directory that can be expected to exist on Windows 10?

I didn't want to push a patch for this without checking with y'all first. :-) 

Also note that later in the tutorial, it is stated that `CU.db` will be in the project folder:

![image](https://user-images.githubusercontent.com/20816/117757753-8906b280-b1d5-11eb-9983-cd94a64c61e4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-5.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The scaffolding tool creates it in a valid directory.
