### ISSUE TITLE
Sone of tge pages in the documentation dont have navigation button to go to the next page or the previous page

### ISSUE THREAD

**Issue by Sammylaw23** [dotnet/AspNetCore.Docs#22276]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3e99ba-cbe1-e8a1-6628-9b6eb39710a4
* Version Independent ID: dd777362-b92d-cac6-2343-a7aaf31d0bdf
* Content: [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tooling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sammylaw23 ... That's by-design. We only use such buttons for leaping across the doc set or when a set of pages are part of a tutorial and meant to be consumed one right after the other. The rest of the docs are considered to be reference docs and not necessarily meant to be consumed in an exact order.

**Comment by Sammylaw23** [comment]
Alright Luke.

I understand that. Thank you for the clarification.

Regards,
