### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#22277]
I am running sdk 5.02.
When I make a Blazor Web Assembly project, there is only one project.
No server side and client side project.  Just all one.
Also there is no startup.cs file.

One of the authors I follow said there were some changes to the setup in Blazor WebAssmebly but I haven't gotten into it yet.

I don't think this tutorial will work for Blazor Web Assembly in .Net 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @smiller7812 ... Sounds like you didn't pass the `-ho|--hosting` switch (or use VS's checkbox to create a hosted WASM app) when creating the app from the WebAssembly project template.

Use ...

```dotnetcli
dotnet new blazorwasm -ho -o BlazorWebAssemblySignalRApp
```

... where `BlazorWebAssemblySignalRApp` will be the folder and solution assembly name.

Use the CLI if you're having trouble with VS. If VS isn't creating the solution correctly with the **ASP.NET Core hosted** checkbox, use the **Report a Problem** gesture from within VS to report it to the VS team.

**Comment by smiller7812** [comment]
Oh, when I create through VS, I have to choose either a Blazor Server or WebAssembly project.  It's no longer choosing Blazor and then what type on the  next page.  I'll go through again and pay closer attention to the options in the Create dialogues and check out the CLI command.  Thanks!

**Comment by guardrex** [comment]
Yes ... select Blazor WebAssembly to see the checkbox for **ASP.NET Core hosted** ... that will do it for you.

**Comment by guardrex** [comment]
It's Step 4 of that VS instruction set.

Yes tho in general on getting a mis-match between a topic and VS. They do from time-to-time change the VS UI and that breaks our topics. Same thing happens with Azure online UI ... they change it all the time ... and it breaks topics. If you spot a delta, you did the right thing to open an issue on it.

**Comment by smiller7812** [comment]
Oh that was my fault.  I went back through.  I didn't pick ASP Hosted the first time in Visual Studio Create BlazorWebAssembly project.  Live and learn!
