### ISSUE TITLE
ASPNETCORE_MODULE_DEBUG_FILE Environment Variable doesn't work.

### ISSUE THREAD

**Issue by liangpeihui** [dotnet/AspNetCore.Docs#22273]
The Environment variable named with 'ASPNETCORE_MODULE_DEBUG_FILE' doesn't work with the section 'handlerSettings' of web.config.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6638bf14-1d5c-61b3-5de0-1b16f933cc1e
* Version Independent ID: 1ed7b9ab-8a47-d948-b3ab-cfe3b1867fe3
* Content: [ASP.NET Core 模块的日志创建和重定向](https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/logging-and-diagnostics.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/host-and-deploy/iis/logging-and-diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jkotalik quick question please

**Comment by liangpeihui** [comment]
At this point, I doesn't use environment variables to configure the enhanced diagnostics log of ASPNETCORE Module.
<img width="994" alt="G1" src="https://user-images.githubusercontent.com/79532375/117928338-ffb6c380-b32d-11eb-9104-17b5ddd7c71f.png">
<img width="965" alt="G3" src="https://user-images.githubusercontent.com/79532375/117928502-3987ca00-b32e-11eb-87fc-a3cbb230effa.png">
<img width="994" alt="G2" src="https://user-images.githubusercontent.com/79532375/117928484-3260bc00-b32e-11eb-98cb-ac66975fd879.png">
Now I attempt to use environment variables to configure the enhanced diagnostics log of ASPNETCORE Module. but it doesn't work for ASPNETCORE_MODULE_DEBUG_FILE Environment Variable. the log file named "aspnetcore-debug.log" is generated by default.
![image](https://user-images.githubusercontent.com/79532375/117928651-6d62ef80-b32e-11eb-9025-e8f2d4381b7b.png)
<img width="423" alt="g4" src="https://user-images.githubusercontent.com/79532375/117928681-76ec5780-b32e-11eb-8ce4-154e682b8c76.png">
<img width="513" alt="g5" src="https://user-images.githubusercontent.com/79532375/117928760-95525300-b32e-11eb-9d6e-d5418a56aaea.png">

**Comment by jkotalik** [comment]
Where are you setting the environment variable?

From what I can tell, we definitely trying to read the environment variable here: https://github.com/dotnet/aspnetcore/blob/52eff90fbcfca39b7eb58baad597df6a99a542b0/src/Servers/IIS/AspNetCoreModuleV2/CommonLib/debugutil.cpp#L219

**Comment by liangpeihui** [comment]
I set the two environment variables in system environment variables, but only the "ASPNETCORE_MODULE_DEBUG" took effect. I saw DebugInitializeFromConfig couldn't read "ASPNETCORE_MODULE_DEBUG_FILE" environmentvariable but DebugInitialize do it.

**Comment by liangpeihui** [comment]
![image](https://user-images.githubusercontent.com/79532375/118156987-95e10b80-b44c-11eb-9a92-bac0c658950a.png)
![image](https://user-images.githubusercontent.com/79532375/118157004-9a0d2900-b44c-11eb-8e17-3f9e97cd3e85.png)
From my test,  "ASPNETCORE_MODUEL_DEBUG_FILE" need absolute path and isn't related to debugFile of handlerSettings.

**Comment by liangpeihui** [comment]
![image](https://user-images.githubusercontent.com/79532375/118156987-95e10b80-b44c-11eb-9a92-bac0c658950a.png)
![image](https://user-images.githubusercontent.com/79532375/118157004-9a0d2900-b44c-11eb-8e17-3f9e97cd3e85.png)
From my test,  "ASPNETCORE_MODUEL_DEBUG_FILE" need absolute path and isn't related to debugFile of handlerSettings.
