### ISSUE TITLE
Needs update: Continuous deployment to Azure with Visual Studio and Git 

### ISSUE THREAD

**Issue by dayo05** [dotnet/AspNetCore.Docs#22280]
[Enter your feedback here]

1. Html tag has been displayed in this page.
2. least .net core version is 5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813f1599-cd04-8003-4883-da21a1643b31
* Version Independent ID: aeb7a06b-b321-e95f-a69b-37dcc17217df
* Content: [Continuous deployment to Azure with Visual Studio and Git with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/azure-continuous-deployment?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
* 
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 813f1599-cd04-8003-4883-da21a1643b31
* Version Independent ID: aeb7a06b-b321-e95f-a69b-37dcc17217df
* Content: [ASP.NET Core와 함께 Visual Studio 및 Git을 사용하여 Azure에 지속적인 배포](https://docs.microsoft.com/ko-kr/aspnet/core/host-and-deploy/azure-apps/azure-continuous-deployment?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md](https://github.com/dotnet/AspNetCore.Docs.ko-kr/blob/live/aspnetcore/host-and-deploy/azure-apps/azure-continuous-deployment.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
redirect to https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment
