### ISSUE TITLE
IXmlRepository: Clarify behavior during key roll-over

### ISSUE THREAD

**Issue by MV10** [dotnet/AspNetCore.Docs#22286]
I am contemplating writing a custom `IXmlRepository` implementation for geo-replication scenarios (we deploy to multiple data centers across the country, and users may be load-balanced to different DCs). The repository interface is simple, but because [`SetDefaultKeyLifetime`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionbuilderextensions.setdefaultkeylifetime?view=aspnetcore-5.0) (and by extension, [`NewKeyLifetime`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.keymanagement.keymanagementoptions.newkeylifetime?view=aspnetcore-5.0#Microsoft_AspNetCore_DataProtection_KeyManagement_KeyManagementOptions_NewKeyLifetime)) can't be set any lower than _one week_, it will make testing a custom implementation extremely difficult, to say the least.

I should probably open an issue to ask about that, but my documentation question is about the runtime behavior when a repository is in use -- since I don't want to set up a simple test and leave it running for a week just to see if I'm right!

The key-ring is cached, so I'm guessing when a key expires, the server re-reads the current key-ring to see whether another server has already updated it, and then performs a write shortly thereafter to add a new key.

Is that accurate? Is it worth a note in the documentation? What happens if a read or write fails?

(Bonus question: Is there an easier way to test a faster expiration-based key rotation?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34a00d6-1197-1a89-6fb6-9adcc4643850
* Version Independent ID: 46f5eaf3-930a-7442-ad4f-4615c38d03b8
* Content: [Key management extensibility in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/extensibility/key-management?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/extensibility/key-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/extensibility/key-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BrennanConroy who's the right person to review this issue?

**Comment by BrennanConroy** [comment]
@blowdart ?

**Comment by blowdart** [comment]
When we tested we used reflection and messed with the internals to set the rollover to a minute.

But here you're testing not your code, but ours, which, honestly, isn't really a unit test, or an integration test. I can understand not trusting us, but XML repositories are simple, create a new key, load all the keys, roll over is handled by our code not yours.

As testing it by messing with reflection is very dependent on runtime versions, it's not something we'd ever consider documenting. @grabyourpitchforks may have some of that old test code somewhere

**Comment by MV10** [comment]
Thanks for that explanation, @blowdart ... I should be able to backtrack it myself and figure out how to do the same thing, it just hadn't occurred to me.

Behaviors seem to be adequately described in another article:

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-3.1

Perhaps it would be helpful to link to this?

**Comment by Rick-Anderson** [comment]
Any chance you could PR this with the link you suggested? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by MV10** [comment]
@Rick-Anderson Not necessary ... the article I asked about links to the article I "found" way up at the top. I had just skipped straight to the area of interest and missed that. Thanks for your time!
