### ISSUE TITLE
Missing template, cli version is missing import

### ISSUE THREAD

**Issue by rabol** [dotnet/AspNetCore.Docs#22295]
[Enter feedback here]
I'm trying to follow the sample

Using Visual studio 2017 pro, installed .NET core 3.1.409

There is no 'Worker service' when trying to create a new project

Command line :
dotnet new worker -o ContosoWorker

works, but when you open the project you get an error:
"Project file is incomplete. Expected imports are missing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=netcore-cli)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rabol ... 3.1 requires VS 2019. You'll need to upgrade VS, use a late model VSC, or use the CLI and a different editor.

Cross-reference: https://docs.microsoft.com/dotnet/core/install/windows?tabs=net50#install-with-visual-studio
