### ISSUE TITLE
Consuming a css file from a RCL in the sample doesn't work

### ISSUE THREAD

**Issue by jernej-erker-labs-isystem** [dotnet/AspNetCore.Docs#22302]
Hi,

I was following the [article](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio#consume-content-from-a-referenced-rcl-1) about sharing static files between web projects. When I tried testing it, I couldn't make it work with the [sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/razor-pages/ui-class/samples/cli), let alone my actual project.

What I did:
* created new folders "wwwroot" and "css" in RazorUIClassLib & put a _styles.css_ in it
* modified WebApp1/Pages/Shared/_Layout.cshtml to include css file from the RCL
`<link rel="stylesheet" href="_content/RazorUIClassLib/css/styles.css" />`

Browser returns a 404
![slika](https://user-images.githubusercontent.com/78487040/118242370-8d64f100-b49d-11eb-827e-6a600ed75e40.png)

I guess I'm doing something wrong, apparently this works for others, as I couldn't find other complaints.

Could you please include sharing a static file in the sample?

Thanks, BR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan including *styles.css* in the sample would be nice. I can test deploying the sample to Azure.

**Comment by fiyazbinhasan** [comment]
I guess that feature never worked on 2.2. I can see a previous commit regarding an update of rcl doc and sample to 3.1, but unfortunately, the sample stayed in 2.2 for some reason. I've updated the sample to 3.1 and added an `address` class which is used in the host app. I think it will do the job.

@Rick-Anderson

**Comment by jernej-erker-labs-isystem** [comment]
Thanks, after updating to 3.1 the css from the RCL is properly fetched.

But, it seems that this only works when `ASPNETCORE_ENVIRONMENT = Development`. If I change the envirnoment to 'Test', `lib.css` is still unavailable.

(`_Layout.cshtml` should be fixed when running in 'Test' environment, so it doesn't use non-existing minified versions of js & css files - like so: [_Layout.zip](https://github.com/dotnet/AspNetCore.Docs/files/6493381/_Layout.zip))

Any help would be appreciated.

**Comment by fiyazbinhasan** [comment]
As the documentation suggests,

> When running the consuming app from build output (dotnet run), static web assets are enabled by default in the Development environment. To support assets in other environments when running from build output, call UseStaticWebAssets on the host builder in Program.cs:

```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStaticWebAssets();
                webBuilder.UseStartup<Startup>();
            });
}
```

> Calling UseStaticWebAssets isn't required when running an app from published output (dotnet publish).

I hope it will solve the problem that you are having @jernej-erker-labs-isystem

**Comment by jernej-erker-labs-isystem** [comment]
Yeah, works like a charm 👍 

I RTFM, but apparently already forgot about that detail in the mean time... :(

Thanks for the help, BR
