### ISSUE TITLE
Is this documentation complete

### ISSUE THREAD

**Issue by cactusoft** [dotnet/AspNetCore.Docs#22305]
I would have thought accessing configuration settings from anywhere should be basic functionality? I am looking down a lot of source code that seems to need to be added to get things out of appsettings.json.

I remember the happy old days of web.config where you could put settings in and pull them out with a single line of code, from anywhere in your app.

I am sure there is a good reason we now need a whole bunch of code to do this, but is this really progress? Surely one of the basic starting points for any new platform should be to consider the kind of things we need to do routinely in every app, and put those in for us. If we're being encouraged to put settings into appsettings.json, it would be really nice if there was functionality to pull those settings out without me having to write it all myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cactusoft ... We only work on the docs here. To provide product feedback, open an issue on the PU ("product unit") repo ...

https://github.com/dotnet/aspnetcore/issues

... and btw WRT your remarks: I think it's fair to say that we'd generally disagree with you on it being at all challenging to simply pull values out of app settings for configuration purposes. The base case to merely provide the key-value pairs in the app settings file ...

```json
{
  "MyKey":  "My appsettings.json Value"
}
```

... and then inject `IConfiguration` (say as `Config`) (namespace: `Microsoft.Extensions.Configuration`) and then read `Config["MyKey"]`. There are more advanced config scenarios that require more code, but the base use case is simple imo.

So, I'm not sure what you're referring to when you remark that you need to "write it all myself."
