### ISSUE TITLE
Multiple policy guidance could be more clear.

### ISSUE THREAD

**Issue by nhwilly** [dotnet/AspNetCore.Docs#22315]
I spent quite a bit of time misunderstanding this section.

I have an API I'm trying to secure.  I have a global authentication requirement in `startup` so that none of my endpoints is exposed to an **unauthenticated** request.

But I wanted specific authorization policies in each controller.  A global one that looks for an `owner` claim to allow all actions for an `owner` of the account.  And then a specific one at the action level that checks for a `permission` claim to see if that action is permitted for that user, in case they are not the owner.

So I created two policies and two handlers for the same requirement, based on the documentation that this would be an OR condition.

In my testing, it seems that works, but only if both attributes are applied at the action level, like this:
```csharp
[Authorize(Policy = OwnerPolicy.IsOwner)]
[Authorize(Policy = AccountPolicies.Read)]
[HttpGet(GetAccountByIdQuery.ControllerRoute)]
```

Below works as an AND condition:
```csharp
[ApiController]
[Authorize(Policy = OwnerPolicy.IsOwner)]
public class AccountsController : ControllerBase
{
    private readonly IMediator _mediator;
    private readonly IHttpContextAccessor _httpContextAccessor;
    public AccountsController(IMediator mediator, IHttpContextAccessor httpContextAccessor)
    {
        _mediator = mediator;
        _httpContextAccessor = httpContextAccessor;
    }

    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [Authorize(Policy = AccountPolicies.Read)]
    [HttpGet(GetAccountByIdQuery.ControllerRoute)]
.
.
.

```
My goal was to apply a policy at the controller level in case an action level permission attribute was missed, in the spirit of least privilege.

I believe the documentation could be more clear in that the OR condition is limited to two policies at the same level, either action or controller.

HTH someone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-5.0#security-authorization-policies-based-handler-registration)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart please review

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
