### ISSUE TITLE
Error dlg for missing NuGet package when on "Creating controller and views" step

### ISSUE THREAD

**Issue by costarec** [dotnet/AspNetCore.Docs#22317]
![image](https://user-images.githubusercontent.com/679279/118380919-9c7d9900-b59a-11eb-98dc-068cb54690f5.png)

In the code creation step, "Create controller and views", if you get the above error dialog, just follow the directions on the dialog - go back to the NuGet PackageManager Console, and install the missing Nuget package. try again. It should work fine. This happened to me in VS2019 Enterprise 16.9.5 release version. (using .NET 5.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks
