### ISSUE TITLE
Antiforgery - Ensure request sequencing

### ISSUE THREAD

**Issue by MikeCardiff** [dotnet/AspNetCore.Docs#22311]
In the article it states:
> The token can also be used to ensure proper sequencing of a series of requests (for example, ensuring the request sequence of: page 1 > page 2 > page 3).

Would it be possible to elaborate further on how this is achieved or implemented? Or does it just mean that using the antiforgery token will prevent page 1 from posting to page 2 or 3 etc?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Right.
