### ISSUE TITLE
View Component - Poor Example

### ISSUE THREAD

**Issue by clockwiseq** [dotnet/AspNetCore.Docs#22312]
Maybe I'm missing something, but there's no view component anywhere in this example:

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/views/view-components/sample/StarterViewComp

**Comment by guardrex** [comment]
Hello @clockwiseq ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
btw tho ... that looks like the starting project of a tutorial with the final project (that probably has the view component in it) at ...

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/views/view-components/sample/ViewCompFinal
