### ISSUE TITLE
Route data fragment should show call to app.UseEndpoints in place of app.UseMvc

### ISSUE THREAD

**Issue by costarec** [dotnet/AspNetCore.Docs#22319]
![image](https://user-images.githubusercontent.com/679279/118381299-7659f800-b59e-11eb-9115-a44fd4cd8b1b.png)

(In the 5.0 tutorial version), in the Route data section, the above code fragment in Startup.cs calling app.UseMvc is replaced with the code generated below calling app.UseEndpoints

![image](https://user-images.githubusercontent.com/679279/118381289-575b6600-b59e-11eb-8ffb-948709283300.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's why we suggest the RP version. We know this is out of date.
