### ISSUE TITLE
worth to mention that sending env variable via argument with double `__` doesnt work

### ISSUE THREAD

**Issue by RoyiNamir** [dotnet/AspNetCore.Docs#22326]
this doesnt work in win : 

![image](https://user-images.githubusercontent.com/2842123/118389178-4c054a80-b631-11eb-86bd-52408fc3a813.png)

while this does work : 

![image](https://user-images.githubusercontent.com/2842123/118389183-56bfdf80-b631-11eb-9c47-e93454520acd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#command-line)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Right. It's not an environment variable if specified as an argument. We should clarify that.
