### ISSUE TITLE
why am i getting only few timezone

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#22329]
[EDIT by guardrex to add the metadata]

I am following this article which mentions about how to get the full list of time zone.
I am using .NET Blazor Hosted Web Assembly Project.

https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization

I created this entry in the Blazor WebAssembly(Client) Project
```
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```

I only get the following time zone, was expecting 140+ time zones.
What else should i do to get the full list

```
foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
                  _logger.LogInformation(z.Id);
```

     America/St_Johns
      America/Argentina/Catamarca
      America/Sao_Paulo
      UTC
      Europe/London
      Europe/Lisbon
      Europe/Berlin
      Africa/Tripoli
      Africa/Nairobi
      Europe/Moscow
      Australia/Perth
      Australia/Sydney
      Pacific/Tongatapu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by nssidhu** [comment]
That is how i did it.

**Comment by guardrex** [comment]
You probably erased all of the metadata when you provided the content. I'll manually add it to this issue ... but please in the future leave the metadata in the opening issue comment. We're always 🏃😅 here and need the community to help speed us up as much as possible.

**Comment by guardrex** [comment]
@hishamco ... Do you know why @nssidhu culture list is so short? If not, I'll refer to the PU for help with this.

**Comment by guardrex** [comment]
I see what you mean @nssidhu ... it's reproducible here. I get ...

America/Los_Angeles
America/St_Johns
America/Argentina/Catamarca
America/Sao_Paulo
UTC
Europe/London
Europe/Lisbon
Europe/Berlin
Africa/Tripoli
Africa/Nairobi
Europe/Moscow
Australia/Perth
Australia/Sydney
Pacific/Tongatapu

**Comment by guardrex** [comment]
@nssidhu ... Let's go ahead and open for the PU. The behavior is strange to me, too, and it might be a 🐞. Open an issue for the PU ("product unit") at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to your opening comment, or please come back here and leave a comment if this does turn out to be something that requires documentation to cover it if there's no framework action for them to take.
