### ISSUE TITLE
An unhandled exception occurred while processing the request.  Exception: OAuth token endpoint failure: Status: Unauthorized;

### ISSUE THREAD

**Issue by devwilsonm** [dotnet/AspNetCore.Docs#22325]
Following the steps ocurr this error:

An unhandled exception occurred while processing the request.
Exception: OAuth token endpoint failure: Status: Unauthorized;Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 70a88d1d-6066-4e1c-813e-0894a95d2401
x-ms-ests-server: 2.1.11722.21 - NCUS ProdSlices
Set-Cookie: fpc=AmLJAS0D6aFGq3x9vFO6PE2qRkppAgAAADiiMtgOAAAA; expires=Tue, 15-Jun-2021 05:21:44 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Sun, 16 May 2021 05:21:44 GMT
;Body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 70a88d1d-6066-4e1c-813e-0894a95d2401\r\nCorrelation ID: 48f72f61-8e20-44f4-8a2b-96417f839c17\r\nTimestamp: 2021-05-16 05:21:44Z","error_codes":[7000215],"timestamp":"2021-05-16 05:21:44Z","trace_id":"70a88d1d-6066-4e1c-813e-0894a95d2401","correlation_id":"48f72f61-8e20-44f4-8a2b-96417f839c17","error_uri":"https://login.microsoftonline.com/error?code=7000215"};
Unknown location

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

--------------------------------------------------------------
STACK:

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That can fail for countless reasons. 
I can tell you the app works. Let us know when you figure out what you did wrong.

**Comment by devwilsonm** [comment]
Sure maybe with this config  i miss something? Google its ok, but Microsoft is giving me problems.

         services.AddAuthentication().AddGoogle(options =>
                {
                    //options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.ClientId = Configuration["GoogleConfig:ClientId"];
                    options.ClientSecret = Configuration["GoogleConfig:ClientSecret"];
                    //options.CallbackPath = "/Identity/Account/Login";
                    //options.AuthorizationEndpoint = "?prompt=consent";
                }).AddMicrosoftAccount(microsoftOptions =>
                {
                   microsoftOptions.ClientId = Configuration["MicrosoftConfig:ClientId"];
                    microsoftOptions.ClientSecret = Configuration["MicrosoftConfig:ClientSecret"];
                });

![image](https://user-images.githubusercontent.com/79812435/118419798-ac70a800-b682-11eb-8597-e9086b38cd54.png)
