### ISSUE TITLE
The article claims that EF6 doesn't support .NET core, but other documentation implies that from EF 6.3, it is supported.

### ISSUE THREAD

**Issue by benbelow** [dotnet/AspNetCore.Docs#22330]
The article claims that EF6 doesn't support .NET core, but this release note https://devblogs.microsoft.com/dotnet/announcing-ef-core-3-0-and-ef-6-3-general-availability/#what-s-new-in-ef-6-3 from EF 6.3 indicates that as of EF 6.3 - it *does* support targeting .NET Core.

I'm assuming that the 6.3 release note is correct - while I'm having some trouble with connection strings, it does seem to be the case that EF 6.4.0 does run on a .net core targeting project.

If my assumption is correct, I think this article should be updated to specify that it is only incompatible for versions < 6.3, to avoid confusion - especially as the last updated date of the article is currently later than the 6.3 release note one!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [ASP.NET Core and Entity Framework 6](https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You're right, but you selected the 2.1 version of this document, which doesn't support EF6. For higher versions, we recommend you use EF Core.

Use the version selector:

![image](https://user-images.githubusercontent.com/3605364/117202152-323e4a80-ad89-11eb-82d4-22b9bcbd4035.png)

**Comment by benbelow** [comment]
Aha, that makes sense - thanks! I hadn't noticed the version discrepancy as I'd found the page through Google, and was thrown off by the updated date.
