### ISSUE TITLE
Missing `services.AddGrpc()`?

### ISSUE THREAD

**Issue by janamtote** [dotnet/AspNetCore.Docs#22339]
I believe this page is missing the step to call `services.AddGrpc()` in `Startup.ConfigureServices`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
Right, this is just a quick overview. It's in the template and in https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-5.0&tabs=visual-studio
