### ISSUE TITLE
Filter is not implemented correctly

### ISSUE THREAD

**Issue by rmissier** [dotnet/AspNetCore.Docs#22334]
When the students are filtered and the sortOrder is changed, the filter is lost.

This is caused by:
<a asp-page="./Index" asp-route-sortOrder="@Model.NameSort">

It is missing the filter information, it should be:
<a asp-page="./Index" asp-route-sortOrder="@Model.NameSort" asp-route-searchString="@Model.CurrentFilter">

The asp-route-searchString should also be added for sorting on EnrollmentDate.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Part 3, Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rmissier sounds like a nice improvement but this is not a production app.
