### ISSUE TITLE
It is unclear when to use ExecuteAsync vs StartAsync

### ISSUE THREAD

**Issue by RoyiNamir** [dotnet/AspNetCore.Docs#22347]
Besides the basic facts that each has its own methods ,
It is unclear and there are no guiding rules when to use what.

You.can do anything in start and also executeasync.

The only benefit i see here is when stopasync.

Imo , there should be guidelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@huan086 can you comment on this?

**Comment by huan086** [comment]
Looks like the rationale stated in https://github.com/dotnet/aspnetcore/commit/712c992ca827576c05923e6a134ca0bec87af4df was lost in the docs.

From what I understand, StartAsync should be kept short, so that callers (`await service.StartAsync`) can proceed with executing, while long running tasks should be placed in `ExecuteAsync`.

**Comment by RoyiNamir** [comment]
But you can perfectly run long running operation in startasync

You just need to not await it

Task.yield etc....

So i don't see the clarification

**Comment by Tratcher** [comment]
@huan086 is correct, ExecuteAsync is a simplified pattern for long running background tasks. Yes you can do this yourself, but it's such a common pattern with services that we made it first class.

Take a look at the implementation for reference:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs

StartAsync starts the service and hold onto the task. StopAsync triggers the Cancellation token to notify background task to stop and then waits for it.

**Comment by RoyiNamir** [comment]
@Tratcher cant you start long task in startAsync ? You can not await it or Task.yield

The pipe will continue without blocking. So still i do not see the diff, besides the actual hooks of start/stop

**Comment by Tratcher** [comment]
Yes, you can start a long task in StartAsync, that's exactly what we do in BackgaroundServices. 

Note Task.Yield is different, if you await it then it still blocks the StartAsync caller asynchronously.

**Comment by Tratcher** [comment]
Counter example: Some services only do work on Start/Stop, they don't need a long running task. Those are easier to write with IHostedService than BackgroundService.

To answer your question another way, IHostedService and BackgroundService are two flavors of the same thing, they aren't that different, use whichever is simpler for your scenario.

**Comment by RoyiNamir** [comment]
> Counter example: Some services only do work on Start/Stop, they don't need a long running task. Those are easier to write with IHostedService than BackgroundService.
> 

Exactly.

And so , I'd summarize it by : 

If you need only to hook start and stop events without long running , go for backgroundService.

If you need long running operation , go for executeAync.

**Comment by fiseni** [comment]
@RoyiNamir 

The `BackgaroundServices` is just a convenience, and you're not forced to use it. It's provided just as a ready-to-go implementation, in order to avoid some common pitfalls.

Your idea with Task.Yield (without awaiting) is only partially good. Once you do that, you have no mechanism for how to terminate the job (in case it's a long-running task). That presents a problem when the app shut downs and StopAsync is called. You won't be able to notify your job, and you can end up with a partially completed task. And you may end up corrupting some state. 

So, instead of trying to implement by yourself, just use the given implementation in those scenarios. It handles the cancellation token.

**Comment by RoyiNamir** [comment]
> So, instead of trying to implement by yourself, just use the given implementation in those scenarios. It handles the cancellation token.


But both startAsync and executeAsync accept cancellation token

**Comment by fiseni** [comment]
That's not the point. The whole trick is to create a linked token, so you can use it from StopAsync and gracefully terminate the running task.

Refer to the implementation [here](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs), I think it will be more clear. In ASP.NET Core 6 there will be further improvement to this.

**Comment by RoyiNamir** [comment]
> That's not the point. The whole trick is to create a linked token, so you can use it from StopAsync and gracefully terminate the running task.
> 
> Refer to the implementation [here](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs), I think it will be more clear. In ASP.NET Core 6 there will be further improvement to this.

Thanks it does make sense now.
Someone is watching my back when app terminates and triggers the cancellation token for me.

So this leaves executeAsync as a "  just run it and leave me alone and i dont care"

I hope I'm right in this one.

What i don't get is why in startasync: 

Await task.yield();
RunLongOperation():  // no await

Is not a good one....

**Comment by fiseni** [comment]
If you actually use `await` in StartAsync, then you will be asynchronously blocking the whole call chain.
Remember, hosted services are run and awaited. It will wait for the service to complete, and then it will execute the next one. Makes sense?

**Comment by RoyiNamir** [comment]
> If you actually use `await` in StartAsync, then you will be asynchronously blocking the whole call chain.
> Remember, hosted services are run and awaited. It will wait for the service to complete, and then it will execute the next one. Makes sense?

But i await on task.yield.
Not the operation itself.

It takes a ms to await task.yield.
So the chain can continue... no?

**Comment by fiseni** [comment]
I misread your comment. Yes, you can do that. But, you're facing the issue I'm referring to in the previous answers.

Let me just summarize.

- Do implement `IHostedService` by yourself if you just need to run something quickly. Or, if you intentionally want to block/delay the app startup, i.e. Database Migration. The hosted services are run sequentially, in the same order as they are registered.
- If you need a background job, just use the provided `BackgroundService` which actually is `IHostedService` implementation. It takes care of the cancellation token, and gracefully terminates the job on `StopAsync`. Yes, you can go and have your own implementation, but why torture yourself when there is a ready one 😄
