### ISSUE TITLE
error CS1061: 'HttpClient' does not contain a definition for 'PostAsJsonAync' and no accessible extension method 'PostAsJsonAync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by lampeTechnidoo** [dotnet/AspNetCore.Docs#22354]
I tried this example : [https://docs.microsoft.com/en-us/azure/app-service/tutorial-auth-aad?pivots=platform-linux](https://docs.microsoft.com/en-us/azure/app-service/tutorial-auth-aad?pivots=platform-linux)

and failed on step "Modify the Front-End-Codes"

`Next, find the method that's decorated with [HttpPost] and replace the code inside the curly braces with:

var response = await _client.PostAsJsonAsync($"{_remoteUrl}/api/Todo", todoItem);
var data = await response.Content.ReadAsStringAsync();
return Content(data, "application/json");`

after this build fail with this error. If have tried some stackoverflow answer, but it does't worked for me. IOne of them let it build it doesn't work. 

` Controllers/TodoController.cs(65,33): error CS1061: 'HttpClient' does not contain a definition for 'PostAsJsonAync' and no accessible extension method 'PostAsJsonAync' accepting a first argument of type 'HttpClient' could be found (are you missing a using directive or an assembly reference?)
`
Can someone help me to fix it?
I used the same configuration as in the example and cloned the repository  on 20.05 14:00 CET.

**Comment by guardrex** [comment]
Hello @lampeTechnidoo ... 
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
btw @lampeTechnidoo ... We've had similar reports. See :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/15430#issuecomment-548560375
