### ISSUE TITLE
SignalR for Razor Pages, WebAPIs, Xamarin Forms and Blazor 5

### ISSUE THREAD

**Issue by jlchavez** [dotnet/AspNetCore.Docs#22350]
Working in .net core 3.1 and 5.0 with Blazor or React, I found conflicts with Identity Server Account Manage pages, SignalR from Xamarin Forms identifying the user, using JWT for asp.net Core, without the need for intercepting IPostConfigureOptions<JwtBearerOptions> or .AddJwtBearer(options => options.Events ...).

In term of compatibility with alll possible technologies in .net core, I would like to add to this, for other developers that if you required Identity Server and JWT Tokens to coexists in the same application. the best to do is to leave the Default Schemas alone in this scenario, and NOT setting them as stated in 'Built-in JWT authentication' as the following code in startup.cs:

>    services.AddAuthentication(options =>
>    {
>        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
>        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
>    });

but for seamelss integration to SignalR set the IUserProvider in Startup.cs, not to confuse it with the sample that is included in the 'Windows authentication' section, but other examples found in StackOverflow. This would be the integration points:

>            services.AddSingleton<IUserIdProvider, NameUserIdProvider>();

with this code, and notice that the Calim Type is name, and not username, when using Identity Server 4 in .net core 5 (haven't checked on previous versions)

>        internal class NameUserIdProvider : IUserIdProvider
>        {
>            public NameUserIdProvider()
>            {
>            }
>            public string? GetUserId(HubConnectionContext connection)
>            {
>                var principal = connection.User as ClaimsPrincipal;
>                var username = principal?.Claims?.Where(x => x.Type == "name").FirstOrDefault()?.Value;
>                return username;
>            }
>        }

and allow the Authentication and Authorization mechanism to be configure on the WebAPIs and the SignalR Hubs by specifing the Authentication Scheme:

SignalR:
>    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
>    public class ChatHub : Hub<IChatClient>
>    {

WebAPI:
>    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
>    [ApiController]
>    [Route("[controller]")]
>    public class WeatherForecastController : ControllerBase
>    {

This could be explained on a separate page for Blazor, React and Xamarin Forms. This made the trick for my new project where I needed to fix this once and for all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @jlchavez ... Management has decided not to support additional scenarios in documentation (or via the product unit for that matter) that aren't currently covered by the Blazor WebAssembly with Identity Server topic. This issue will be linked to this topic as a closed issue for those that want to look at what you did. I recommend that you blog about your approach and post a link at Awesome Blazor, perhaps in the *Articles* or *Tutorials* section or *Authentication* section of *Sample Projects* if you put one up.

https://github.com/AdrienTorris/awesome-blazor
