### ISSUE TITLE
Doc URI differences between ASP.NET and Core

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#22352]
ASP.NET Core has some URI decoding differences compared to ASP.NET 4.x. Here's a recent Q&A:

> The only differences I’m seeing are 1) %5C (i.e., \ ) gets converted to a / in ASP.NET but is respected as a \ in ASP.NET Core and 
 
The %5C conversion to / was a deviation from the spec in IIS that we’ve avoided in Core. It was derived from the outdated idea that all of your paths were based on file system paths and it tried to mitigate some spoofing situations.

> 2) %2F (i.e., / ) gets properly converted to a / in ASP.NET but gets left as %2F in ASP.NET Core.

This one we don’t handle as gracefully. The whole path gets un-escaped except %2F because converting it to / would change the path structure. It can’t be decoded until the path is split into segments.

> For the HttpRequest.Url, I’m returning “new Uri(this.AspNetCoreHttpRequest.GetDisplayUrl());”. GetDisplayUrl returns a url which has the same quirks as above but otherwise is correct. The problem is when I wrap it in a Uri object, the Uri class does some decoding (e.g. “/’%20’” turns into “/’ ‘”) which doesn’t match the behavior in ASP.NET. 

That should be “new Uri(this.AspNetCoreHttpRequest.GetEncodedUrl());” to avoid Uri misinterpreting the values.

@davidfowl 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 60645](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60645)

**Comment by Rick-Anderson** [comment]
> The only differences I’m seeing are 1) %5C (i.e., \ ) gets converted to a / in ASP.NET but is respected as a \ in ASP.NET Core and

I'll document that without giving a history lesson unless you want me to explain why it's changed.

>> `%2F` (i.e., / ) gets properly converted to a `/` in ASP.NET but gets left as %2F in ASP.NET Core.
> This one we don’t handle as gracefully. The whole path gets un-escaped except `%2F` because converting it to `/ ` would change the path structure. It can’t be decoded until the path is split into segments.

`WebUtility.UrlDecode(Car.MyString);`  when I enter  `%2F`  by itself if properly decoded.

Do you want something like 

To generate the value for `HttpRequest.Url`, use `new Uri(this.AspNetCoreHttpRequest.GetEncodedUrl());`  to avoid Uri misinterpreting the values.

**Comment by Tratcher** [comment]
> `WebUtility.UrlDecode(Car.MyString);` when I enter `%2F` by itself, it's properly decoded.

That's ok, but it should only be done after splitting path segments so you don't loose the segment boundaries.

The rest sounds good.

**Comment by Rick-Anderson** [comment]
@adityamandaleeka @mjrousos @twsouthwick

I'm updating [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/) and I'll include  this issue (URI differences between ASP.NET and Core).  I think it should be in this doc and not the incremental docs. Let me know if you disagree.
