### ISSUE TITLE
Need new document/migration guide for Identity Server/AAD

### ISSUE THREAD

**Issue by HaoK** [dotnet/AspNetCore.Docs#22355]
We need to provide some recommended guidance about how developers can migrate from their existing identity server apps to using AAD.

More details will follow, I'll provide the first draft of this content in the net6.0 time frame.  Would @guardrex be who I work with to get the official docs reviewed and edited?

cc @blowdart @mkArtakMSFT @javiercn @danroth27

**Comment by javiercn** [comment]
Yep.

I think we also need to put disclaimers in the docs where we reference this. @blowdart will be handling the specific wording?

**Comment by guardrex** [comment]
@HaoK ... If it's easiest, you can paste the content into an issue comment here. I'll take it from there.

**Comment by HaoK** [comment]
@guardrex awesome then we'll use this issue to create the topic/content

**Comment by blowdart** [comment]
https://github.com/dotnet/aspnetcore/issues/32881 has a first draft of the wording around licenses

**Comment by HaoK** [comment]
What do we actually want to put in the docs about this change over?  It doesn't look like much needs to be updated other than a namespace change

**Comment by HaoK** [comment]
@guardrex looks like duende has a decent migration doc @blowdart agreed that we can probably just reference this https://docs.duendesoftware.com/identityserver/v5/upgrades/is4_v4_to_dis_v5/

**Comment by guardrex** [comment]
@HaoK ... I'm a hair confused by the "just reference" part given that (at least for Blazor) IdS4 is part of a hybrid tutorial/reference topic where the walk-through produces a running app in [Secure an ASP.NET Core Blazor WebAssembly hosted app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio). I assume that we're keeping that coverage for 5.0, but what are we doing for 6.0?

**Comment by HaoK** [comment]
Ah thanks for pointing me to that doc, yeah that one should just be updated to duende, I'll do that exercise now to make sure it works

**Comment by HaoK** [comment]
In regards to the reference, I was just referring to a new section (somewhere), that specifically addresses migration for existing apps using IdentityServer to the new Duende version, we could just point them to the duende doc.

**Comment by guardrex** [comment]
> a new section (somewhere), that specifically addresses migration for existing apps

Gotcha. No problem.

> that one should just be updated to duende, I'll do that exercise now to make sure it works

Ok. I usually go on the new bits at RC1, so that would be best for me to work it forward. I think there will be plenty of time. The updates thus far are going well. We're not running late AFAICT with coverage.

**Blazor 6.0 content tracking issue**
https://github.com/dotnet/AspNetCore.Docs/issues/22045

**Comment by HaoK** [comment]
I did a relatively quick pass reading over https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio (great and very thorough doc btw), I don't see any thing immediately that should be affected by the duende change, hopefully none of the minor changes leak out of `AddApiAuthorization` in a way that requires tweaking things.  When updating the tests/samples, the main difference was changing the ef migrations to add a new Keys table, and then namespace updates, which I don't think you have any (to the Id4 namespace) in this doc

**Comment by guardrex** [comment]
Thanks for the remark ... and @javiercn gets credit for a lot of it. I put the **_Rex Spin_**&trade; on what he sent over and then added some bits.

> When updating the tests/samples, the main difference was changing the ef migrations to add a new Keys table, and then namespace updates, which I don't think you have any (to the Id4 namespace) in this doc

Yes, that's right. I don't anticipate any special coverage outside of calling out the Duende approach with the license text from the PU issue. If I have questions, I'll ping u here. Otherwise, you should get a PR review ping in the RC1 timeframe.
