### ISSUE TITLE
Hints not described

### ISSUE THREAD

**Issue by MarkAtAgilliance** [dotnet/AspNetCore.Docs#22366]
[Enter feedback here]
In the 2nd step of Apply web API conventions, it says "A convention method is marked with **hints** that determine the actions to which the convention method applies. For more information on **hints**, see Create web API conventions)."

When I jump to that section, there is no information on hints but I think it relates to ApiConventionNameMatchBehavior.

Good to clarify those are what is being referred to as hints (if that is the case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@pranavkm can you clarify this?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
