### ISSUE TITLE
. Strange is that dotnet dev-certs --clean didn't removed it.

### ISSUE THREAD

**Issue by YaroslV** [dotnet/AspNetCore.Docs#22379]
[Enter feedback here]
I can not run the wep api app from VS Code by clicking Ctrl+F5 neither dotnet build command from the terminal.
It throws error about missing dev certificate or smth similar to it, although I had run previously dotnet dev-certs https --trust

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by YaroslV** [comment]
ok. my bad. I had old certificate on my windows and VS code used it. Strange is that dotnet dev-certs --clean didn't removed it. Closing.

**Comment by Rick-Anderson** [comment]
@YaroslV  that's interesting  Does https://github.com/dotnet/aspnetcore/issues/15357#issuecomment-555782605 help?

**Comment by Rick-Anderson** [comment]
@YaroslV  https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#windows---certificate-not-trusted has the answer
