### ISSUE TITLE
Snippet needs to be updated

### ISSUE THREAD

**Issue by dharmatech** [dotnet/AspNetCore.Docs#22374]
Section:

https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio#update-the-database-context

![image](https://user-images.githubusercontent.com/20816/119217756-3066cd80-ba91-11eb-875d-446bfd407cc4.png)

The above mentions a concurrency token for `Department`, however, note that it is not setup in the code snippet.

Looking at the referenced file:

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/Data/SchoolContext.cs

The `snippet_SS` seems to be the currently referenced one:

![image](https://user-images.githubusercontent.com/20816/119217779-60ae6c00-ba91-11eb-95d4-829416bb28cb.png)

The `snippet_SQLLite` seems to have the code that reflects the text description:

![image](https://user-images.githubusercontent.com/20816/119217790-7d4aa400-ba91-11eb-9f83-b6f473cf6f30.png)

That said, the `Department` entity as defined in the page doesn't have the referenced `ConcurrencyToken`:

https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio#the-department-entity

![image](https://user-images.githubusercontent.com/20816/119217917-5476de80-ba92-11eb-8331-3abf5f88effa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can't you just delete 
Configures a concurrency token for the Department entity. Concurrency is discussed later in the tutorial.

That's introduced much later. When I rewrote this I thought I'd introduce that earlier, but then I changed my mind. If that's right, do you want to fix this?

BTW, better to include code snippets rather than images when possible.

**Comment by dharmatech** [comment]
@Rick-Anderson,

Yes, we can do that.

It looks like there's one more issue however. Looking at the code:

```csharp
using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Data
{
    public class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Course> Courses { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<OfficeAssignment> OfficeAssignments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>().ToTable(nameof(Course))
                .HasMany(c => c.Instructors)
                .WithMany(i => i.Courses);
            modelBuilder.Entity<Student>().ToTable(nameof(Student));
            modelBuilder.Entity<Instructor>().ToTable(nameof(Instructor));
        }
    }
}
```

the following:

    modelBuilder.Entity<...>().ToTable(nameof(...))

is called for `Course`, `Student`, and `Instructor`. It should also be called for `Department`, `Instructor`, and `OfficeAssignment`.

That will require updating the snippet (and thus the sample project itself).

**Comment by Rick-Anderson** [comment]
What's the issue. Unless we're showing wrong code, don't worry about transient classes. Do we show that someplace? It's best  to call out code in the repository and where it's referenced in the MD file. The following examples have nothing to do with this issue but show how to point out markup and code:

https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/data/ef-rp/complex-data-model.md#L506

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/Data/SchoolContext.cs#L36-L66

I can show you how to quickly access these from an issue if you like.

**Comment by dharmatech** [comment]
If we do the following:

    modelBuilder.Entity<...>().ToTable(nameof(...));

for `Course`, `Student`, and `Instructor`, but not for `Department`, `Enrollment`, and `OfficeAssignment`, then the table names will be:

```
Course
Student
Instructor
Departments
Enrollments
OfficeAssignments
```

I.e. the first three will be singular and the latter three will be plural. Seems like it would be good to encourage beginners to be consistent in their table naming convention? :-)

**Comment by Rick-Anderson** [comment]
> I.e. the first three will be singular and the latter three will be plural. Seems like it would be good to encourage beginners to be consistent in their table naming convention? :-)
> 
> > Do we show that someplace?
> 
> The tutorial encourages the reader to view the database tables. So yes, we do indirectly show them these names.

We can look at this on the next update. It's not a bug just an inconsistency.
