### ISSUE TITLE
Anonymous delegate event handler performance

### ISSUE THREAD

**Issue by darraghjones** [dotnet/AspNetCore.Docs#22370]
I've just found out about an issue (https://github.com/dotnet/aspnetcore/issues/17886) which can dramatically affect the performance of a BlazorServer application which has a lot of data displayed on a page.

However, I could not find anywhere that this performance 'gotcha' is documented..and indeed the docs seem to also suffer from the same issue. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0#lambda-expressions

It would be good to get clear documentation about the best way to bind an onclick event handler on a list of objects so as not to have poor performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @darraghjones ... I'll get back to you no later than Monday morning on this.

**Comment by guardrex** [comment]
Yes, @darraghjones ... I like your suggestion for covering this. I'll schedule this now, but just FYI on the timing of resolution: I'm working on major topic overhauls that might run all the way to when we start covering 6.0 and then 6.0 will take a while to address. I'm going to place a **_QUICK_** 🏃 cross-link to this issue in the topic, but I won't close the issue out ... this link will be temporary and this issue will remain open. I just can't say exactly when it will get worked. The cross-link that I'm about to place will surface this to readers in the meantime.
