### ISSUE TITLE
Invoke an instance .NET method Example Start with Generic then go to advanced

### ISSUE THREAD

**Issue by MSIH** [dotnet/AspNetCore.Docs#22383]
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-5.0#invoke-an-instance-net-method

The example should start with the most generic and simple case, which is the method within the component page. Intead i found this solution on someone's blog.

```
    var dotNetReference = DotNetObjectReference.Create(this);
    return js.InvokeAsync<string>("sayHello", dotNetReference );


    public string Name { get; set; }

    [JSInvokable]
    public string GetHelloMessage() => $"Hello, {Name}!";
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-gb/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MSIH ... The PU ("product unit") only recommended that components use an `Action` for a static method call (Blazor WASM) (it's in the next section after the one you're mentioning, *Invoke a component instance .NET method*) or the use of a helper class (Blazor WASM or Blazor Server) (in the section after that, *Component instance .NET method helper class). Let's ask them for more info on this .......

@SteveSandersonMS @pranavkm ... Why wasn't that approach :point_up: sent over for coverage? If it should be covered, please provide any *gotchas to avoid* 😈 and any other descriptive bits that you'd like to see included.

**Comment by guardrex** [comment]
* > is covered in the docs

  Yes, but I meant exactly as called out by @MSIH ... as in passing the component (`this`) in that way. We say ...

  > The .NET instance can also be passed as an argument when invoking other .NET methods from JS.

  ... to cover it. We don't say/show that the .NET instance is the component instance itself. If you're happy with the current coverage, then nothing further is actionable on this point.

* > it fails to Dispose the DotNetObjectReference, which is important to avoid leaking memory.

  *Gotcha* ... the class has a `Dispose`, but it isn't called. I'll take care of that. (The other example, `CallDotNetExample3`, has it covered and should be ok.)

* clarify where that guidance came from ... content dates back to 3.x before DotNetObjectReference existed

   **_Yes!_** ... It even predates the Blazor docs arriving officially on the docs repo. The topic has been PU-reviewed several times over the past few years, but this is the first time removal of that approach has been called for. I'll take care of that right now.

**Comment by SteveSandersonMS** [comment]
> passing the component (this) in that way

Passing `this` like this is completely fine and is a normal, recommended way to be able to call back to the same instance from JS. Like you've noted above, the one key caveat is that you have to dispose the `DotNetObjectReference` instance.

> this is the first time removal of that approach has been called for. I'll take care of that right now.

Thanks very much - that's great! Ideally it could be replaced by showing the specific example of `new DotNetObjectReference(this)` to pass the component instance to JS, as that solves the same problem but without causing issues on Blazor Server.

**Comment by guardrex** [comment]
> showing the specific example of new DotNetObjectReference(this) to pass the component instance to JS, as that solves the same problem but without causing issues on Blazor Server.

Cool ... will do. I'll ping u on the PR.

**Comment by guardrex** [comment]
While I'm at it @MSIH, I'll reverse the two examples making the component example go first and the class example go second.
