### ISSUE TITLE
NuGet packages are required to enable external login

### ISSUE THREAD

**Issue by kuldeepsinghgill** [dotnet/AspNetCore.Docs#22399]
Some key points are missing on this page. It seems that documentation is not up to date for .NET Core 5. Here is what I found missing.
You have to install NuGet packages with the authentication middleware components of the services you wish to use. Earlier versions of .NET Core was not required any package to enable this external logins. Below are the packages for Microsoft, Facebook, Google, and Twitter:

- Microsoft.AspNetCore.Authentication.MicrosoftAccount
- Microsoft.AspNetCore.Authentication.Facebook
- Microsoft.AspNetCore.Authentication.Google
- Microsoft.AspNetCore.Authentication.Twitter

I hope it will save your time and documentation will be updated soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kuldeepsinghgill ... The packages are called out in the dedicated topics for each provider. There's no need to call them out at this level.

**Comment by kuldeepsinghgill** [comment]
Ah! I see, it is there but it will be great if can include in overview. It will help to those peoples who have old keys for external login and they don't want to go through the each login provider documentation as they are already experienced. So, in my opinion, breaking changes like these must be highlighted on  overview page if possible. Thanks for your reply @guardrex

**Comment by guardrex** [comment]
I suppose the list for the instructions could get the package ref and a cross-link.

From ...

```
* [Facebook](xref:security/authentication/facebook-logins) instructions
* [Twitter](xref:security/authentication/twitter-logins) instructions
* [Google](xref:security/authentication/google-logins) instructions
* [Microsoft](xref:security/authentication/microsoft-logins) instructions
* [Other provider](xref:security/authentication/otherlogins) instructions
```

... to ...

```
* [Facebook](xref:security/authentication/facebook-logins) instructions ([`Microsoft.AspNetCore.Authentication.Facebook`](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Facebook))
* [Twitter](xref:security/authentication/twitter-logins) instructions ([`Microsoft.AspNetCore.Authentication.Twitter`](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Twitter))
* [Google](xref:security/authentication/google-logins) instructions ([`Microsoft.AspNetCore.Authentication.Google`](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Google))
* [Microsoft](xref:security/authentication/microsoft-logins) instructions ([`Microsoft.AspNetCore.Authentication.MicrosoftAccount`](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.MicrosoftAccount))
* [Other provider](xref:security/authentication/otherlogins) instructions
```

@Rick-Anderson will decide and let u know.

Rick, that's a cut-'n-paste :point_up: for the *Setup login providers required by your application* section if ur interested.

**Comment by Rick-Anderson** [comment]
Let's keep the details in the dedicated doc.
