### ISSUE TITLE
Does CORS Work according to http verbs?

### ISSUE THREAD

**Issue by VINEET230** [dotnet/AspNetCore.Docs#22423]
Do we require enabling CORS for httpGet calls in .net core?
I wrote an angular application without enabling CORS and Get works perfectly fine but we have error while using httpPOST.
I thought this is a bug and maybe some action is required on it.

email- vineetchaudhary230@gmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Read this doc.

**Comment by VINEET230** [comment]
> 

@Rick-Anderson : Could you please be more specific in which section we have to check?
