### ISSUE TITLE
Azure App Service: DOTNET_ENVIRONMENT vs. ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by sashaeve** [dotnet/AspNetCore.Docs#22429]
Documentation stated: "In the Add/Edit application setting window, provide ASPNETCORE_ENVIRONMENT for the Name. For Value, provide the environment (for example, Staging)."

I created ASP.NET Core app, set .NET 5 version, slot - Staging.

ASPNETCORE_ENVIRONMENT did not change the environment, I used DOTNET_ENVIRONMENT which worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0#environment-based-startup-class-and-methods)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Where was it not working? *launchSettings.json* has the following

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:4038",
      "sslPort": 44340
    }
  },
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Production"
      }
    },
    "MemoryLeak": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

You can see this in VS too.

**Comment by sashaeve** [comment]
This is for Azure environment not localhost. I did not use _launchSettings.json_.

**Comment by Rick-Anderson** [comment]
They must have just changed the Azure portal UI. How do I set this on Azure?

![image](https://user-images.githubusercontent.com/3605364/119905053-286eb980-bee7-11eb-8b1e-22ff0ebdec92.png)

**Comment by Rick-Anderson** [comment]
It's working for me. Did you copy/paste an extra white space?

https://bt39.com/GearWheelSpeed/about
