### ISSUE TITLE
Error while copying content to a stream .net 6 preview 3

### ISSUE THREAD

**Issue by sajrashid** [dotnet/AspNetCore.Docs#22434]
[Enter feedback here]
Hi,
I copied the example exactly as is 
FileUpload2.razor
```
Uncaught (in promise) Error: System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StreamContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__82`2[[System.Net.Http.HttpContent, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Chameleon.Client.Pages.FileUpload2.OnInputFileChange(InputFileChangeEventArgs e) in c:\Users\Me\source\repos\Chameleon\src\Client\Pages\FileUpload2.razor:line 103
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
    at Object.endInvokeDotNetFromJS (http://localhost:5000/_framework/blazor.webassembly.js:1:2941)
    at Object.invokeJSFromDotNet (http://localhost:5000/_framework/blazor.webassembly.js:1:2597)
    at Object.lt [as invokeJSFromDotNet] (http://localhost:5000/_framework/blazor.webassembly.js:1:52027)
    at _mono_wasm_invoke_js_blazor (http://localhost:5000/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:210324)
    at <anonymous>:wasm-function[10695]:0x194d82
    at <anonymous>:wasm-function[2465]:0x59c7c
    at <anonymous>:wasm-function[2189]:0x46258
    at <anonymous>:wasm-function[7948]:0x12dfac
    at <anonymous>:wasm-function[7420]:0x117c6e
    at <anonymous>:wasm-function[3361]:0x7a160
```
**dotnet --info**

```
NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.115 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly#inputfile-component)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sajrashid ... I can't repro a problem here with 5.0 ...

<img width="818" alt="Capture" src="https://user-images.githubusercontent.com/1622880/119918314-ceddad80-bf2d-11eb-96ae-9de782940543.PNG">

There might be a general problem with the example that I can't reproduce or their might be a new problem with 6.0 preview, which I can't test here because I'm not using preview bits yet.

Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add a `cc: @guardrex` to the bottom of your opening comment, and you can just cut-and-paste all of what you put into the opening comment here :point_up: into the new issue there.

Cross-link them to this for the doc ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly#upload-files-to-a-server

... and you can add a cross-link to this doc issue ...

```
https://github.com/dotnet/AspNetCore.Docs/issues/22434
```

... and mention that @guardrex can't repro the problem with the example for 5.0 but isn't on preview yet to test for 6.0.

There's no repro sample app for this example because it's a hosted WASM project that uploads to a server app, and I don't have such a snippet samples app on the docs repo to host the code. The code in the document is physically in the doc. Therefore, I recommend that you put up a hosted WASM project with the full setup (client and server) for this component and give them the link to that ... it will speed them up quite a bit. They'll use your sample app to test. If you're too busy yourself to put a repro project up, let me know ... I'll do it tomorrow (Friday) morning.

**Comment by sajrashid** [comment]
Hi @guardrex , have created [repo](https://github.com/sajrashid/preview6Issues), hope I followed your instructions correctly

https://github.com/dotnet/aspnetcore/issues/33101

Thanks for your help.

**Comment by guardrex** [comment]
You need to copy the entire report from your opening comment here into the new issue over there.

**Comment by guardrex** [comment]
... and you didn't cross-link to a repro GitHub project that they can pull down and run.

**Comment by guardrex** [comment]
... and you didn't cross-link to the document section.

No, you didn't set that engineering issue up per my instructions. They're probably going to just close it if you leave it like that.

**Comment by sajrashid** [comment]
Hi I've updated it thanks for the reply

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by guardrex** [comment]
Cool ... thanks. They'll work that issue now.

I'll re-open this issue if it turns out to be a problem with the component example and not the framework. Thanks for writing in on this.

**Comment by sajrashid** [comment]
Great thanks Luke

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ToddBonnewell** [comment]
Seems like the sample code got updated and no longer includes: fileContent.Dispose();

That did the trick. But for those of us who had been using the old sample, well, shame on us for working on the edge.
