### ISSUE TITLE
Http Logging Middleware - MediaTypeOptions doc typos

### ISSUE THREAD

**Issue by lohithgn** [dotnet/AspNetCore.Docs#22431]
HttpLogging Middleware documentation has typos in MediaTypeOptions section.

![image](https://user-images.githubusercontent.com/2450336/119914699-61646800-bf93-11eb-85f5-773d430f2632.png)

Just logging an issue here so that i can create a PR fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by lohithgn** [comment]
created PR https://github.com/dotnet/AspNetCore.Docs/pull/22432

**Comment by Rick-Anderson** [comment]
It's overloaded
![image](https://user-images.githubusercontent.com/3605364/119917334-11899080-bf02-11eb-83df-2aad94545fe8.png)

**Comment by lohithgn** [comment]
@Rick-Anderson I know its overloaded. its ``` AddText(string contentType)``` - which will default to UTF-8 encoding and ```Addtext(string contentType, Encoding encoding)``` - where consumer provides the encoding.

The doc has two bullets with the same method signature:

- public void AddText(string contentType, Encoding encoding)
  - Adds a contentType to be used for logging as text using UTF-8 encoding.
- public void AddText(string contentType, Encoding encoding)
  - Adds a contentType to be used for logging as text using the specified encoding.

That was my point of filing the bug. The bullets need to be:
- public void AddText(string contentType)
  - Adds a contentType to be used for logging as text using UTF-8 encoding.
- public void AddText(string contentType, Encoding encoding)
  - Adds a contentType to be used for logging as text using the specified encoding.

Aad that's  the change I proposed in the PR.

thoughts ?
