### ISSUE TITLE
Blazor Server updates for 6.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#22444]
The following 6.0 Blazor Server enhancements/updates will be worked together on one PR from this issue:

- [x] **CUT** More control over circuits lifetime
- [x] Support byte-array transfer in JS Interop
- [ ] Remove size limitations imposed by SignalR message size
- [x] **CUT** Specific components for dealing with large binary data (files and media)
- [x] **CUT** Specific component for dealing with large amounts of text data (`InputTextArea`)

See the [6.0 Tracking Issue](https://github.com/dotnet/AspNetCore.Docs/issues/22045) for cross-links to PU issues/PRs and blog post remarks.

**Comment by guardrex** [comment]
@TanayParikh ... I'm looking over PU work for the last item here for RC1 documentation updates.

* `RemoteBrowserFileStreamOptions` -> `JSDataStream` options ... Only briefly mentioned in the Blazor File Uploads topic. This seems easy to update for >=6.0. I'll swap the cross-link to `JSDataStream` for >=6.0 here ...

  > In Blazor Server, file data is streamed over the SignalR connection into .NET code on the server as the file is read from the stream. <xref:Microsoft.AspNetCore.Components.Forms.RemoteBrowserFileStreamOptions> allows configuring file upload characteristics for Blazor Server.

* `OpenReadStreamAsync` dropping `pauseIncomingBytesThreshold` and `resumeIncomingBytesThreshold` ... Doesn't appear in conceptual docs, only in API docs. Therefore, no action required for Blazor docs.

* `IJSStreamReference` ... Covered now (>=6.0) at https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-javascript-to-net

Much of the work is related to internal framework implementations. Is there anything else to cover for *Remove size limitations imposed by SignalR message size*? For example, is there anything for SignalR Fundamentals at the two pivots (Server and/or WebAssembly)? ...

* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0&pivots=server
* https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0&pivots=webassembly

Anything for Blazor File Uploads?

* https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server
* https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly

**Comment by TanayParikh** [comment]
> * `RemoteBrowserFileStreamOptions` -> `JSDataStream` options ... Only briefly mentioned in the Blazor File Uploads topic. This seems easy to update for >=6.0. I'll swap the cross-link to `JSDataStream` for >=6.0 here and add my temporary _this will be available for RC1_ text to it ...

>   > In Blazor Server, file data is streamed over the SignalR connection into .NET code on the server as the file is read from the stream. ~~xref:Microsoft.AspNetCore.Components.Forms.RemoteBrowserFileStreamOptions allows configuring file upload characteristics for Blazor Server.~~

Can we remove this last part, this isn't directly configurable by developers for file uploads as we use the defaults.

> * `OpenReadStreamAsync` dropping `pauseIncomingBytesThreshold` and `resumeIncomingBytesThreshold` ... Doesn't appear in conceptual docs, only in API docs. Therefore, no action required for Blazor docs.

👍 

> * `IJSStreamReference` ... Covered now (>=6.0) at https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-javascript-to-net ... is there anything else that you'd like to add to that?

The JS->.NET looks good to me. In RC1, we added the reverse .NET->JS which would be nice to add in (not sure of the appropriate timeline/process in terms of documentation for this). 

https://github.com/dotnet/aspnetcore/pull/34817

**Comment by guardrex** [comment]
@TanayParikh ... 

1. > Can we remove this last part

   You'll have to clarify that further. There are three versions of the doc ...

   * 3.1 ... Indicates they can configure `RemoteBrowserFileStreamOptions`.
   * 5.0 ... Indicates they can configure `RemoteBrowserFileStreamOptions`.
   * 6.0 ... Incidates they can configure `RemoteJSDataStream`.

   What should change?

1. For *.NET->JS*, I added it to the 6.0 tracking issue ... https://github.com/dotnet/AspNetCore.Docs/issues/22045.

**Comment by TanayParikh** [comment]
> Wasn't it configurable for 3.1 and 5.0?

Yes, you're correct, 3.1 & 5.0 can be left as is. I meant remove the configurability details specifically for `6.0 ... Incidates they can configure RemoteJSDataStream.`.

> For .NET->JS, I added it to the 6.0 tracking issue ... Blazor 6.0 content tracking issue #22045.

Thanks!
