### ISSUE TITLE
Documentation claims that all uploads are virus scanned?

### ISSUE THREAD

**Issue by CaiusJard** [dotnet/AspNetCore.Docs#22452]
>  In production scenarios, an anti-virus/anti-malware scanner API is used on files before making them available for download or for use by other systems

Is it really true? Or perhaps there is a word missing from the docs and it should instead say "ensure an anti-virus..."

If it is true, please extend the docs to say which service does this, as it could have important data sharing/privacy implications

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @CaiusJard ... That's fine ... I can reword that.
