### ISSUE TITLE
RazorRuntimeCompilation does not work for "cshtml.cs" files on Visual Studio for Mac - ASP.NET 5.0

### ISSUE THREAD

**Issue by DhyeyMoliya** [dotnet/AspNetCore.Docs#22459]
Editing `.cshtml` files woks. But it does not work for `.cshtml.cs` files. The steps given in the page are not working as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DhyeyMoliya ... We only work on documentation on this repo. Report that to the VS for Mac team via the guidance in [How to report a problem in Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019).
