### ISSUE TITLE
A completely useless documentation

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/AspNetCore.Docs#22463]
I was searching for how to enable localization in **ASP.NET Core Blazor web assembly** and came across this official documentation. But after reading this documentation I have found this completely useless. No single instruction of how to enable localization in ASP.NET Core Blazor web assembly. We don't expect such low-quality documentation from Microsoft ASP.NET Core Team.

Look at the following third-party documentation that clearly instructs of how to enable localization in Blazor Web Assembly. 

https://code-maze.com/localization-in-blazor-webassembly-applications/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback, @TanvirArjel. I can't speak to this subject to any great degree, as I didn't write this topic and my globalization/localization experience as a dev is limited to a few Xamarin apps that I built something like five years ago (at least). The topic is currently due for a total overhaul on the [UE ("user experience") issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286). After we discuss it further here, we might close this in favor of tracking the work via that issue. I'll ping for help 🚓🚒🚑 ...............

@mkArtakMSFT @danroth27 How do you want to triage this? I have it on the [UE passes issue](https://github.com/dotnet/AspNetCore.Docs/issues/19286), but do you want me to overhaul it? It would be time consuming, but I certainly can brush-up on the subject and then tackle it. However, I guesstimate that I wouldn't reach this until post-6.0 GA unless you table other work that I am making great progress with at this time.

cc: @pranavkm

**Comment by guardrex** [comment]
@TanvirArjel ... We just discussed this offline, and the PU ("product unit") agrees that this very bare-bones coverage isn't good enough. We'll overhaul the topic as part of the UE ("user experience") passes that I'm conducting on https://github.com/dotnet/AspNetCore.Docs/issues/19286, and this topic has been placed **_NEXT_** 🏃 on the list for an overhaul. I'll get started on it tomorrow (Friday). I'm not really a loc expert, but I'll work out what I can and then Pranav will follow-up on the PR with suggestions for updates. I'll ping u on the PR when it goes up within a week or so depending on the workload. I'm going to close this issue because the work is tracked by #19286.

**Comment by guardrex** [comment]
@TanvirArjel ... I've dug into the UE pass on the topic. Indeed, I see that you mean 👀🙈. This topic **only** covers how to set the app's culture, **_not how to localize it_**, and it's incomplete even at that. If the title were *How to set a Blazor app's culture*, it might have been fine to add a few additional remarks+examples, but I agree with you that that's not the right way to go here. I'm performing a major overhaul to include ...

* Reorganization of the topic: Sections for globalization, setting the culture (both statically at app start and dynamically via a user's selection), and localizing the app with pivots for WASM and Server scenarios.
* Fully-working examples for WASM and Server will be provided.
* I'm adding helpful cross-links to API resources.

I'm probably not quite half-way through the work. I'll ping u on the PR when it's ready for review, and we can discuss it further with the the PU from there. I'll also ping Hisham Ben Ateya for his input. Hisham is a loc expert and helps us quite a lot with loc docs on the repo.

cc: @marin-bratanov ... Your remarks, Marin, are being addressed by the updates. I'll ping u, too, when the PR is ready for review. Cross-ref: https://github.com/dotnet/AspNetCore.Docs/issues/21619
