### ISSUE TITLE
The first argument of CreatedAtAction should be "Get" or "Create"?

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#22460]
I open this issue by removing the given template because the feedback button provided in [this page](https://docs.microsoft.com/en-us/learn/modules/build-web-api-aspnet-core/8-exercise-implement-crud) brings me to a different form. The form does not lead me to this github.

The potential problem:

![asp net](https://user-images.githubusercontent.com/50270635/120076714-38e28800-c0d1-11eb-9dad-3334e9db9807.png)

**Comment by guardrex** [comment]
Hello @pstricks-fans ... Please re-open this from the bottom of the topic ... it will ping the author automatically via the metadata that it adds to the bottom of the issue.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
I see ... It's a Learn module ... follow the guidance under their link at the bottom of that page .........

<img width="818" alt="Capture" src="https://user-images.githubusercontent.com/1622880/120078653-153e2400-c076-11eb-9c66-75634b957ddf.PNG">

**Comment by pstricks-fans** [comment]
@guardrex Thank you. I have posted the issue. :-)
