### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by PoulBak** [dotnet/AspNetCore.Docs#22464]
`index = Array.IndexOf(buffer, (byte)'\n', prevIndex);`

The example use `(byte)'\n'` to check for newline in a byte array. but 13 can be part of a unicode char, not necessarily newline!
It only works correct for ASCII and other one byte encodings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49b15fd3-39b5-3ad9-8c4e-b8160360dee9
* Version Independent ID: c33981af-93ce-d4be-a265-5d4696666c7a
* Content: [Request and Response operations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/middleware/request-response.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/request-response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by Rick-Anderson** [comment]
@jkotalik please review

**Comment by serpent5** [comment]
I'm no expert in UTF-8, but [this explanation of how it works](https://www.twilio.com/docs/glossary/what-utf-8) demonstrates that it isn't possible for `\n` (13) to be part of a continuation byte, because its decimal value is less than 128.
