### ISSUE TITLE
Invalid example since GET request has no body

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/AspNetCore.Docs#22465]
The example has the following code:

```cs
public class GoodStreamReaderController : Controller
{
    [HttpGet("/contoso")]
    public async Task<ActionResult<ContosoData>> Get()
    {
        return await JsonSerializer.DeserializeAsync<ContosoData>(Request.Body);
    }
}
````

But this is a GET request and GET requests have no body, so this should be a POST request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
GET requests can return data non-blocking  fully asynchronous using a non buffered request body:

**Comment by vanillajonathan** [comment]
Oh it seems GET requests actually can have a request body, but this was rare enough to confused me, it is not anything I've came across before.

Perhaps a more commonly used scenario for the example ought to be used, such as a POST request that saves the stream to a file.
