### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JohnStraumann66** [dotnet/AspNetCore.Docs#22471]
I followed these steps exactly for a web API I created, and which works fine when I run locally, but when I try to access the Azure API via Postman, I get an error: 

500 Internal Server Error

which is not helpful. 

I am confused as to where the Management API service fits in? The API URL is: 

https://adcourtapi.azurewebsites.net/Api/Matches

but then in the Management API site I see different URLs, and no services show up, do I need to create the GET/POST services manually?

If I run locally and in Postman if I use GET and send: https://localhost:44352/api/Matches

it works perfectly.

I used to be able to just publish the WEB API Directly, this need for the API management site change seems to complicate things...

John.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by Rick-Anderson** [comment]
Set the https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments to development to get better errors and use F12 tools

**Comment by JohnStraumann66** [comment]
> Set the https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments to development to get better errors and use F12 tools

Thanks for the reply but I don't see how that article applies to the Azure Publishing question? Is there more detail on why this API Management step is now needed, how to create teh actions (i.e. in my controller I have GET, PUT, POST etc., do these all need to be manually created in teh API Management app?). The Publish API to Azure process worked fine before, why introduce these new steps that complicate the process?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
