### ISSUE TITLE
Are optional routes with constraints possible?

### ISSUE THREAD

**Issue by ErikApption** [dotnet/AspNetCore.Docs#22477]
From the current page, it is not clear if one can combine both optional routes with constrains... e.g
```
@page "/RouteParameter/{text?}" 
```
 is possible

but can I do?
```
@page "/RouteParameter/{text:bool?}" 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ErikApption ... Yes, that's fine. I'll add a remark to the topic with an example.

**Comment by ErikApption** [comment]
Fantastic

**Comment by guardrex** [comment]
Sure thing. FYI: When there's an attached PR, the issue closed automatically when the PR merges.
