### ISSUE TITLE
What's the recommended pattern to prevent adding duplicated "base" service/option 

### ISSUE THREAD

**Issue by yantang-msft** [dotnet/AspNetCore.Docs#22483]
Our project has common pattern like this:
``` csharp
IServiceCollection AddBaseService(this IServiceCollection services, IConfiguration configuration) => services
    .Configure<BaseServiceOptions>(options =>
    {
        configuration.Bind(BaseServiceOptions.SectionName, options.SomeList);
    })
    .AddSingleton<IBaseService, BaseService>();

IServiceCollection AddServiceA(this IServiceCollection services, IConfiguration configuration) => services
    .AddBaseService(configuration)
    .AddSingleton<IServiceA, ServiceA>();

IServiceCollection AddServiceB(this IServiceCollection services, IConfiguration configuration) => services
    .AddBaseService(configuration)
    .AddSingleton<IServiceB, ServiceB>();

public void ConfigureServices(IServiceCollection services)
{
    services.AddServiceA(Configuration);
    services.AddServiceB(Configuration);
}
```

It all worked fine until recently we had a problem because of duplicated items in `BaseServiceOptions.SomeList` (becasue `AddBaseService` is executed twice). During investigation, we found 2 issues:

1) `BaseService` SeviceDescriptor is added twice. It's not a problem since our controller just asks for `IBaseService`. But if the controller asks for `IEnumerable<IBaseService>` or we call `container.GetServices<IBaseService>`, then the same `BaseService` will be instantiated multiple times.
    Since the function name is `AddSingleton`, I took it for granted it will only instantiate a singleton instance of the same implementation, i.e., `BaseService`.
    What's more, the [doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#service-registration-methods) demonstrated AddSingleton of different implementations will instantiate different implementation, which actually makes me believe more that the same implementation will only be instantiated once.
    
2) `Configure<TOptions>(Action<TOptions>)` is executed twice. And since `configuration.Bind(string, IEnumerable)` append items to the list, we end up have duplicated items in `BaseServiceOptions.SomeList` and thus had problem somewhere.

I didn't find any examples of having a "base" service that may get added multiple times in the program, so I'm trying to see what's the recommend pattern to solve the above 2 issues. Here is some options that I thought about

1) For issue 1, change `AddSingleton` to `TryAddSingleton` so `IBaseService` will only be added once for sure.
    It's not perfect because if we really want to add different implementations of `IBaseService`, we have to switch back to `AddSingleton`, then there is no guarantee the service descriptor of the same implementation will only be added once.

2) For issue 2
    a)  Change `configuration.Bind(BaseServiceOptions.SectionName, options.SomeList)` to `options.SomeList = configuration.GetSection(BaseServiceOptions.SectionName).Get<IEnumerable<string>>()`, so the items are **not appended**. The `Configure<TOptions>()` is still unnecessarily executed multiple times though.
    b) Add a class that implements IConfigureOptions, i.e., `ConfigureBaseServiceOptions: IConfigureOptions<BaseServiceOptions>` and add it as a service `services.TryAddSingleton<IConfigureOptions<BaseServiceOptions>, ConfigureBaseServiceOptions>`. This adds complication in code and not the recommended way as documented [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#use-di-services-to-configure-options).

3) For both issues, check if the service descriptor exists. This adds complication in code.
``` csharp
static readonly ServiceDescriptor s_baseServiceDescriptor = ServiceDescriptor.Singleton<IBaseService, BaseService>();
IServiceCollection AddBaseService(this IServiceCollection services, IConfiguration configuration)
{
    if (services.contains(s_baseServiceDescriptor))
    {
        return services;
    }

    services.Configure<BaseServiceOptions>(options =>
    {
        configuration.Bind(BaseServiceOptions.SectionName, options.SomeList);
    })
    .AddSingleton<IBaseService, BaseService>();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#service-registration-methods)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
I think you're looking for TryAddEnumerable? There are examples of its usage all over that you can take inspiration from https://grep.app/search?q=TryAddEnumerable&filter[repo][0]=dotnet/aspnetcore

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by yantang-msft** [comment]
@Rick-Anderson @davidfowl , `TryAddEnumerable()` addressed the first issue we have.

What about the second issue, i.e., `service.Configure<T>(Action<T>)` get registered multiple times?
I understand `IConfigurationOptions` would work, but that adds complication and pretty tedious. i.e., we have to create 2 classes for each option, i.e., `MyOptions` and `MyOptionsSetup : IConfigurationOptions`. Ideally there is something like `services.TryConfigure<T>(Action<T>)` so it only register the callback once, is it ever considered?

**Comment by davidfowl** [comment]
> Ideally there is something like services.TryConfigure<T>(Action<T>) so it only register the callback once, is it ever considered?

That doesn't exist, you can propose it here https://github.com/dotnet/runtime. (use the API template).

**Comment by yantang-msft** [comment]
@Rick-Anderson all my questions are addressed, so I'll close the ticket.
