### ISSUE TITLE
Guidance on allowed characters in routing rules and ?

### ISSUE THREAD

**Issue by ErikApption** [dotnet/AspNetCore.Docs#22480]
We tried to create routing rules with optional parameters with ? 
`@page "/mypage/{id:int}?option1={option1:bool?}"` but this actually generates an error in blazor. I see a section in routing about handling urls - are `?` characters in URLs expected to be handled manually using the whole URL? Or which characters are actually allowed in routing rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Let's discuss it on the PR ... Pranav, on the product unit, will need to look at that anyway. I can add info from his response to the existing PR.

https://github.com/dotnet/AspNetCore.Docs/pull/22478
