### ISSUE TITLE
AddDatabaseDeveloperPageExceptionFilter step missing source package for clarity

### ISSUE THREAD

**Issue by estebanes22** [dotnet/AspNetCore.Docs#22482]
Document should clarify that AddDatabaseDeveloperPageExceptionFilter requires use of Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore (via https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore)

This is in this section of the doc: https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0#add-the-database-exception-filter

Credit to this Dennis from this SO question for the finding: https://stackoverflow.com/questions/65007086/services-adddatabasedeveloperpageexceptionfilter-error-code-cs1061

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in the doc. See [EF Core NuGet packages](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0#ef-core-nuget-packages)

![image](https://user-images.githubusercontent.com/3605364/120591508-f8885000-c3d7-11eb-87bd-bfdf4286deef.png)
