### ISSUE TITLE
Generalize Blazor performance guidance

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#22498]
Much of the performance guidance in this doc applies equally to Blazor Server. It seems like should generalize this doc to be about Blazor performance, not just Blazor WebAssembly performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679bec37-eb9b-8092-5b99-118e4f2eb1a1
* Version Independent ID: 710987ea-42fb-1306-5750-ff8956907748
* Content: [ASP.NET Core Blazor WebAssembly performance best practices](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-performance-best-practices?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/webassembly-performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/webassembly-performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @pranavkm
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is a bit of a dup. It was already on the schedule for the UE pass of this topic per reader feedback at https://github.com/dotnet/AspNetCore.Docs/issues/21698.

https://github.com/dotnet/AspNetCore.Docs/issues/19286
