### ISSUE TITLE
Wrong location for modules

### ISSUE THREAD

**Issue by JohnBergman** [dotnet/AspNetCore.Docs#22499]
In the module version info

%PROGRAMFILES%\IIS\Asp.Net Core Module\V2.

This does not exist on my system, there is no programfiles\iis folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@JohnBergman ... `%PROGRAMFILES%` a Windows variable for ...

> C:\Program Files

In a path (console or window location bar), Windows will replace the value with the actual path. There's probably a list of all of them *somewhere* over in the Windows docs.
