### ISSUE TITLE
Blazor WASM Net 6 Preview 4 Azure AD - There was an error trying to log you in: 'Cannot read property 'toLowerCase' of undefined'

### ISSUE THREAD

**Issue by aherrick** [dotnet/AspNetCore.Docs#22500]
Sorry for the cross post but I wasn't having any success posting on SO. I've followed this guide for NET6 Prev4 and am receiving this error.

https://stackoverflow.com/questions/67805062/blazor-wasm-net-6-preview-4-azure-ad-there-was-an-error-trying-to-log-you-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @aherrick ... Open for the product unit on their repo at ...

https://github.com/dotnet/aspnetcore/issues

... but you can't throw them to a SO post for the description. Place all of the context on the issue that you open for them. The less clicking they have to do the better under their heavy workload ⛰️⛏️😅.

**Comment by aherrick** [comment]
thank you! :)
