### ISSUE TITLE
fileContent gets disposed prior to upload

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#22503]
From @kenjohnson03 on https://github.com/dotnet/AspNetCore.Docs/pull/22502 ...

> Added the StreamContent as ByteArrayContent to allow the fileContent variable to get disposed as expected without impacting the PostAsync call.

https://github.com/dotnet/AspNetCore.Docs/pull/22502/files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pranavkm @javiercn ... This code was reviewed/approved on #21325 back in February. This is the first that I've heard of a problem, and testing here hasn't turned up any foul disposal behavior.

https://github.com/dotnet/AspNetCore.Docs/pull/21325/files#diff-9012cebaab9cbf7514d15a5fe98bf0796212a89ab3de29029487d329f6cf9a4bR235

Is there a problem? Even if there is, can we devise an approach that doesn't read the bytes as @kenjohnson03 is proposing on ...

https://github.com/dotnet/AspNetCore.Docs/pull/22502/files

**Comment by renner2** [comment]
I had the same problem with the original code from today - made a complete new .NET 5 (VS Version 16.11.0 Preview 1.0)
 Blazor WASM project - copy/pasted only the original code - got the Error:

Uncaught (in promise) Error: System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.StreamContent'.

With the changes from @kenjohnson03:

var byteContent = new ByteArrayContent(await fileContent.ReadAsByteArrayAsync());
                    content.Add(
                        content: byteContent,

 it worked like expected - THX @ken !!!

One last question is there any disadvantage using Ken´s ByteArray solution?

**Comment by javiercn** [comment]
@guardrex not exactly sure what's going on with your sample, can you at least post the callstack?

@pranavkm thoughts?

**Comment by guardrex** [comment]
My app (i.e., the doc's code) isn't breaking. @kenjohnson03 and/or @renner2 should submit the callstack.

**Comment by renner2** [comment]
![CallStack and Errors](https://user-images.githubusercontent.com/4989628/122137961-16c56580-ce46-11eb-8ce3-ae4d3ea6c693.PNG)

This is a picture of the edge browser dev tools callstack and error page..... hope that helps you...
Can I do anything else?

p.s. hope you can download the pic to see everything sharp....

**Comment by guardrex** [comment]
@renner2 ... Since I can't repro this locally with my (rather small, really) test files, can you put up on GH a test file that makes the current code break and produce that error :point_up:? I'll then see if I can get my app to break, too.

**Comment by renner2** [comment]
@guardrex .... here is a project made with the latest VisualStudio Version 16.11.0 Preview 2.0 and .Net 5 - I gave you the original which is NOT working - but in FileUpload2.razor Line 82 there is also the working code as comment.

Hope that helps you.... I am ready to help....

cU 


[WebApplication6.zip](https://github.com/dotnet/AspNetCore.Docs/files/6682067/WebApplication6.zip)

**Comment by guardrex** [comment]
I already have a test app here with the component from the topic. I only tested it here with a few small test files. I'd like to have one of your test files that causes the error when the file is uploaded.

**Comment by guardrex** [comment]
Does it throw there for *any* file that you try to upload? ... or does it break with some files but others upload ok?

**Comment by renner2** [comment]
@guardrex the error occurs with ANY file - I tried 3kb text file or larger media files as well as docx and so on .... so yes every file makes the error....

**Comment by guardrex** [comment]
I see. I haven't had a problem here with it (yet). I'll compare your WebApplication6 to my local setup and see if I can spot any deltas. I'll check first thing on Monday morning and get back to you.

**Comment by guardrex** [comment]
@renner2 ... You changed the component. It's not ...

```csharp
using var fileContent = new StreamContent(file.OpenReadStream());
```

It should be ...

```csharp
var fileContent = new StreamContent(file.OpenReadStream());
```

Cross-ref: https://docs.microsoft.com/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=server#upload-component

<img width="574" alt="Capture" src="https://user-images.githubusercontent.com/1622880/122756304-dd349600-d25b-11eb-8e9c-1229694d12e7.PNG">

**Comment by kenjohnson03** [comment]
Thanks Luke the page was changed a couple weeks ago to remove the using statement!

Ken J.
________________________________

**Comment by guardrex** [comment]
@kenjohnson03 ... Our page ... or your page? AFAICR, we always had it this way. I think our example was introduced here ...

https://github.com/dotnet/AspNetCore.Docs/pull/21325/files#diff-9012cebaab9cbf7514d15a5fe98bf0796212a89ab3de29029487d329f6cf9a4bR224

... but to be honest, these topics get **_a LOT of churn_**, so there may have been some flavor of this around here with a different approach. Anyway today, I think we're ok here. I'll keep an :ear: open for more feedback on this. There are a lot of moving parts to make this work, including security 😨 concerns.

**Comment by renner2** [comment]
@guardrex  
I copied the code from:
https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=webassembly
and the "using" is still there and also a second one which is also wrong: using var content = new MultipartFormDataContent();

THANKS for your help anyway....

![Bildschirmfoto vom 2021-06-21 14-58-11](https://user-images.githubusercontent.com/4989628/122765777-21965500-d2a1-11eb-9d2a-48184086126d.png)

**Comment by guardrex** [comment]
Let me check on that. We have pivots ... we may have a snippet from a sample messing with me! 😈

**Comment by kenjohnson03** [comment]
I went back Saturday to get you a stack trace but the example had changed a couple weeks ago. The one using removal does fix the issue. To be clear I’m looking at the hosted WASM solution. The new example works and I was able to avoid a call to get the bytearray.

Ken J.
________________________________

**Comment by guardrex** [comment]
Very good. I'm putting the PR up now. I'll ping u cats on it.

**Comment by renner2** [comment]
@guardrex 
yes I was successful without the firts "using" it works perfectly - var fileContent = new StreamContent(file.OpenReadStream()); - THX
