### ISSUE TITLE
Scaffold Identity in ASP.NET Core projects

### ISSUE THREAD

**Issue by imoni-2** [dotnet/AspNetCore.Docs#22508]
[There are two observations under Disable Page near the bottom of the page.
1. You omitted the loginPartial page correction hence Register is still part of the Page Header.
2. Your presentation of Using another App to add users is too brief. Your example did the not give complete idea of the SeedData class from where the Initialize method is used.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in #23968
