### ISSUE TITLE
Linux dotnet sdk error A fatal error occurred. The required library libhostfxr.so could not be found.

### ISSUE THREAD

**Issue by robosthetique** [dotnet/AspNetCore.Docs#22509]
Hey, I've added all the packages listed, but still running anything with dotnet aspnet-codegenerator, even just -h, gives the error:

A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/usr/.dotnet/tools/.store/dotnet-aspnet-codegenerator/5.0.2/dotnet-aspnet-codegenerator/5.0.2/tools/net5.0/any/].

I'm working via the command line on Linux Mint, 5.4.0-52-generic, dotnet 5.0.300 installed via the dotnet-install.sh file currently given on the Install ASP.NET Core page on Jun 6 2021.

EDIT:
Fixed it.
From grantzvolsky at https://github.com/dotnet/sdk/issues/9304
Put the following in a bash file and run it as source:

# run this every time you open a new terminal as:
# . ~whatever-path/new.sh or source ~whatever-path/new.sh
# makes dotnet aspnet-codegenerator work

export DOTNET_ROOT=/snap/dotnet-sdk/current
export MSBuildSDKsPath=$DOTNET_ROOT/sdk/$(${DOTNET_ROOT}/dotnet --version)/Sdks
export PATH="${PATH}:${DOTNET_ROOT}"
export PATH="$PATH:$HOME/.dotnet/tools"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@robosthetique  thanks for the update
