### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Jasow4444** [dotnet/AspNetCore.Docs#22517]
[Enter feedback here]
There is a broken link at the bottom of the page where it says :
Apply the migration to the existing database. The instructions in this section work for SQL Server only, not for SQLite.
The link does not send the user to anything.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-au/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Need to fix the 5.0 version

**Comment by Rick-Anderson** [comment]
We'll fix this in the .NET 7 push.
