### ISSUE TITLE
Loc Middleware order inconsistency between topics

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#22512]
The Middleware Order section of the *Middleware Topic* indicates that Loc Middleware (`app.UseRequestLocalization(...)`) should be **_after_** Routing Middleware ...

```csharp
app.UseHttpsRedirection();
    app.UseStaticFiles();
    // app.UseCookiePolicy();

    app.UseRouting();
    // app.UseRequestLocalization();
    // app.UseCors();

    app.UseAuthentication();
    app.UseAuthorization();
```

Cross-ref: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order

The *Globalization and localization* topic indicates that `app.UseRequestLocalization(...)` should be **_before_** Routing Middleware ...

```csharp
var supportedCultures = new[] { "en-US", "fr" };
var localizationOptions = new RequestLocalizationOptions().SetDefaultCulture(supportedCultures[0])
    .AddSupportedCultures(supportedCultures)
    .AddSupportedUICultures(supportedCultures);

app.UseRequestLocalization(localizationOptions);

app.UseRouting();
app.UseStaticFiles();
```

Cross-ref: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#localization-middleware-2

**NOTE**: Seems to work either way, but I have no idea if any 😈 *sneaky grimlins* 😈 will show up one way or the other.

cc: @hishamco 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
AFAIK it should work in both way, but I think there's a use case especially when you are using `RouteDataRequestCultureProvider` this will require route comes first. @ryanbrandenburg @pranavkm  correct me if I'm wrong

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
@hishamco that's my understanding too. Might be easier to simply place it after routing in both cases and/or add some text about how the order can impact the loc middleware depending on which providers are being used and what runs after the middleware obviously being affected by the current culture.
