### ISSUE TITLE
Additional providers for email confirmation and recovery

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/AspNetCore.Docs#22526]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Email-Configuration-for-Blazor-Serve-Ind/1446545)._

---
I have created the Microsoft Blazor server default application with Individual Authentication in Visual Studio 2019. If I submit the email address for for password resetting. It does not sent password link to given mail address due to email configuration not configured in that application. [Email configuration References] (https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio) only available with Send Grid. Could you please share the guidelines references for Email configuration with gmail or office 365?

---
#### Feedback Bot on 6/9/2021, 11:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
Looks like the customer wants to learn how to send email using some of the most popular email providers. If using SMTP, it'll be the same for all.
I am wondering whether we can add a small note linking to "https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-5.0". Something like:

```
Note, that sending email the way shown here is only an example. You can use [SmtpClient](link to the doc page) type to get lower level access to email sending primitives.
```

And maybe even update the SmtpClient doc page to include a section like this:

```md
Below you can find details about popular mail server settings:

- [Outlook](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040?ui=en-us&rs=en-us&ad=us#:~:text=If%20you%20want%20to%20add%20your%20Outlook.com%20account,587%209%20SMTP%20encryption%20method%20STARTTLS%20See%20More)
- [Google](https://support.google.com/a/answer/176600?hl=en#zippy=%2Cuse-the-gmail-smtp-server)
```

**Comment by guardrex** [comment]
@mkArtakMSFT ...

> even update the SmtpClient doc page to include a section like this:

Do you want me to open for that aspect at https://github.com/dotnet/runtime/issues?

**Comment by guardrex** [comment]
@Rick-Anderson ... Upon closer inspection, this really isn't a Blazor issue, it's an ASP.NET Core Identity issue for just having more providers explained out with examples. A Blazor Server app uses Identity infrastructure, so it maps to the *Account confirmation and password recovery in ASP.NET Core* topic. I thought this question/request for more email providers was asked and answered years ago and that the answer back then was that it couldn't be done for some reason(s). How do you want to handle this one?

**Comment by Rick-Anderson** [comment]
Thanks for your question,  we strongly recommend against configuring your own SMTP server.

> Looks like the customer wants to learn how to send email using some of the most popular email providers. If using SMTP, it'll be the same for all.
> I am wondering whether we can add a small note linking to "https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=net-5.0". Something like:
> 
> ```
> Note, that sending email the way shown here is only an example. You can use [SmtpClient](link to the doc page) type to get lower level access to email sending primitives.
> ```
> 
> And maybe even update the SmtpClient doc page to include a section like this:
> 
> ```lisp
> Below you can find details about popular mail server settings:
> 
> - [Outlook](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040?ui=en-us&rs=en-us&ad=us#:~:text=If%20you%20want%20to%20add%20your%20Outlook.com%20account,587%209%20SMTP%20encryption%20method%20STARTTLS%20See%20More)
> - [Google](https://support.google.com/a/answer/176600?hl=en#zippy=%2Cuse-the-gmail-smtp-server)
> ```

@blowdart specifically recommends against configuring your own SMTP server.

**Comment by Rick-Anderson** [comment]
Per the article:

We recommend you use SendGrid or another email service to send email. SMTP is difficult to secure and set up correctly.
