### ISSUE TITLE
Error Running the Selected Code Generator

### ISSUE THREAD

**Issue by RoyKM** [dotnet/AspNetCore.Docs#22523]
[Enter feedback here]
I have followed the tutorial steps; however when I add the Scaffolding I get an error:

"There was an error running the selected code generator: 'To scaffold controllers and views using models, install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design.'

I have tried installing it.  Uninstalling it.  Installing it.  Rebooting.  Start from the beginning of the Tutorial, ensuring I didn't miss any steps.  All to no avail.  I keep getting this error message.

The only thing I see that is different, is when I add the Project, the Tutorial says to use "ASP.NET Core Web Application", but I don't have that template.  The one I have that is closest to what the Tutorial uses is: "ASP.NET Core Web App".

I am using a Windows 10 64-Bit, build 18363
Microsoft Visual Studio Enterprise 2019, Version 16.10.0
Microsoft .NET Framework, Version 4.8.03752

Please assist.

Thank you, 
    Roy Mathur
    240-541-8068 (7am-3pm Mon-Fri)
    RoyMathur@geico.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design.'
