### ISSUE TITLE
HTTP Logging: how to display [Redacted] request & response info

### ISSUE THREAD

**Issue by JeepNL** [dotnet/AspNetCore.Docs#22529]
[Here in Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0) I read "_Request headers are logged as soon as the middleware is invoked. Headers are redacted by default with the character '[Redacted]' unless specified in the HttpLoggingOptions.RequestHeaders._"

But not how to specify it in `HttpLoggingOptions.RequestHeaders`. Maybe you could provide an example?

I've looked in [the sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/http-logging/samples/6.x) also

![Screenshot 2021-06-11 105644](https://user-images.githubusercontent.com/39458532/121661914-03607600-caa5-11eb-893d-a00be9bff514.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by wadepickett** [comment]
@JeepNL, thanks very much for feedback on this topic.  I see what you mean, it does bring up a scenario that it doesn't really follow through on, and an example would be helpful.

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/aspnetcore/issues/40981
