### ISSUE TITLE
Virtualize with 1Million items

### ISSUE THREAD

**Issue by BitawareUnleashed** [dotnet/AspNetCore.Docs#22537]
Hello,
I have a problem with virtualization. I have a text file to show on screen in a Blazor Wasm application. The file contains more than 1 million lines. If I open it and I scroll for a while, there are no problems. No problems too if I scroll with the scrollbar for a while. But if I try to scroll near the end to something like that, my controller is flooding with a great number of requests and they are absolutely incoherent with each other. The screen is white and no items are shown. I have an example on GitHub here
https://github.com/BitawareUnleashed/Blazor-virtualize-sample
There's something wrong with the implementation or did I do something wrong?
thank you for help

**Comment by guardrex** [comment]
Hello @BitawareUnleashed ... We only handle docs here. Please open for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
