### ISSUE TITLE
Not accurate for Azure

### ISSUE THREAD

**Issue by FrankSzendzielarz** [dotnet/AspNetCore.Docs#22539]
The section [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-5.0#can-i-configure-my-app-to-require-a-certificate-only-on-certain-paths) is not true for Azure hosted App Services, which allow you to exclude paths from certificate authentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
That doesn't make it incorrect. That's a host configuration, not an app one, and not one that the middleware knows or cares about to be honest,

**Comment by FrankSzendzielarz** [comment]
True. But if you are googling how to's for this stuff at the moment, it's pretty sparse, so hitting something like "Can I configure my app to require a certificate only on certain paths?" while scanning the material and it saying "no you can't" is a little unhelpful. True you can't configure the app, but by configuring the host you are configuring the app.
