### ISSUE TITLE
GrpcClientFactory.Create should be GrpcClientFactory.CreateClient

### ISSUE THREAD

**Issue by TimHess** [dotnet/AspNetCore.Docs#22543]
There is an error in this code snippet:

```csharp
public class AggregatorService : Aggregator.AggregatorBase
{
    private readonly Greeter.GreeterClient _client;

    public AggregatorService(GrpcClientFactory grpcClientFactory)
    {
        _client = grpcClientFactory.Create<Greeter.GreeterClient>("GreeterAuthenticated");
    }
}
```
`grpcClientFactory.Create` should be `grpcClientFactory.CreateClient`, as noted in the text immediately preceding the code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f64666-6632-cfca-2c3b-a20ea016f62b
* Version Independent ID: caebee8f-f4aa-17a4-3681-d10c4695e9c0
* Content: [gRPC client factory integration in .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/clientfactory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/clientfactory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@TimHess, thanks very much for bringing up this issue.  Your PR will be reviewed.
