### ISSUE TITLE
The ProtectKeysWithAzureKeyVault section of this page suggests a series of steps that result in a serious security issue.

### ISSUE THREAD

**Issue by hypermoose** [dotnet/AspNetCore.Docs#22546]
The ProtectKeysWithAzureKeyVault section of this page suggests that the reader run the sample code twice.  Once with the ProtectKeysWithAzureKeyVault call commented out to create the initial blob and then a second time with the protect call left in.  The problem with that is that not only is the block file created for the keyring but an initial key is created that is valid for 3 months from the time you ran it.  When you add the ProtectKeysWithAzureKeyVault it actually does NOTHING!.   Your key is now free and clear in blob storage for anyone to read UNTIL that key expires and a new one is generated which is keyvault encrypted.   The instructions should state that the block file should be edited to remove the key or the sample empty file is so small you should just include it in the instructions.  

<?xml version="1.0" encoding="utf-8"?><repository></repository>

The other thing that is wrong is the permissions need for the web app in keyvault, You must have the get permissions as well as wrap and unwrap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@markmcgookin please review

**Comment by markmcgookin** [comment]
Yeah, this is a super confusing topic. We do state [here](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/configuration/overview.md#protectkeyswithazurekeyvault) that ideally you should just upgrade to the new libraries as that will create things properly, but it might be made clearer that this doesn't require running the code twice with the line removed.

> We recommended upgrading to the Azure.Extensions.AspNetCore.DataProtection.Blobs and Azure.Extensions.AspNetCore.DataProtection.Keys packages because the API provided automatically creates the blob if it doesn't exist.

Maybe we should remove the workaround and just insist people use the new packages? 

Also... re: keyvault config, yeah we should probably mention that those specific permissions are needed. Even though this isn't necessarily about configuring keyvault itself, it would make sense to at least give users a heads up for what is required.

**Comment by Rick-Anderson** [comment]
> Maybe we should remove the workaround and just insist people use the new packages?

Yes, let's do that. We want to encourage folks to use the latest bits.

> we should probably mention that those specific permissions are needed. Even though this isn't necessarily about configuring keyvault itself, it would make sense to at least give users a heads up for what is required.

Can you PR this?

**Comment by hypermoose** [comment]
I did use the new libraries and I believe it threw an exception until I commented out the second line that the blob did not exist.    Not 100% sure though.

Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by markmcgookin** [comment]
I am pretty sure the new libraries work fine without the second line commented out. I had this discussion [here](https://github.com/dotnet/aspnetcore/issues/25229) and [here](https://github.com/dotnet/AspNetCore.Docs/issues/19770)

I'll have a look at re-doing this bit as it's pretty confusing at the minute.

**Comment by Rick-Anderson** [comment]
@markmcgookin  can you take a look at this and #24096

**Comment by markmcgookin** [comment]
> @markmcgookin can you take a look at this and #24096

PR #24184 should cover both of these, not sure if it's automatically picked up this one though. Might need to manually close if/when it's merged.
