### ISSUE TITLE
Should use the same admin username & password used in the previous step in the Configure Azure SQL Database dialog

### ISSUE THREAD

**Issue by puran1218** [dotnet/AspNetCore.Docs#22555]
In the next step of the Configure Azure SQL Database dialog, there is a best practice that to avoid using the same admin username & password used in the previous step. This could make the **publish failed** as you can't login the new user:
- Enter the Database connection user name and Database connection password fields. These are the details your application will use to connect to the database at runtime. **Best practice is to avoid using the same details as the admin username & password used in the previous step.**

![image](https://user-images.githubusercontent.com/15075826/122491550-ce10d680-d016-11eb-874e-be7df77a3bd6.png)

The best practice should be removed or make a bit more clarify?

![image](https://user-images.githubusercontent.com/15075826/122404033-74c28c00-cfb1-11eb-80e5-5b8c78466f3f.png)
![image](https://user-images.githubusercontent.com/15075826/122404047-78eea980-cfb1-11eb-982e-c945c0167475.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
