### ISSUE TITLE
If it is concentrated on only model would be good

### ISSUE THREAD

**Issue by KNAjay** [dotnet/AspNetCore.Docs#22554]
Dear Sir/Maam

I feel this page mixed with topics i feel it is good to have details about only model in this page good anyways we dealing about database in next page, i was following with code as well now i stuck  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start and then come back to this

**Comment by KNAjay** [comment]
Hi Rick,

Thank you for reply,
I checked the other link but even that is same with different example, in add model topic added EF, SQL logging etc i feel it should go to working with database, where you can also talk about code first, db first and how to achieve both etc., even scaffolding added in model page only but we have separate topic for that as well,  now stuck with model creation page too many things to follow under same topic.

Overall the documentation is nice

Thanks and Regards
Ajay K N
