### ISSUE TITLE
https://support.microsoft.com/kb/309408/#6 is not valid

### ISSUE THREAD

**Issue by asbestos** [dotnet/AspNetCore.Docs#22556]
[Enter feedback here]

Please fix url to https://support.microsoft.com/kb/309408/#6
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c24ccb9-b297-f942-ebf1-c994d672f183
* Version Independent ID: 5d6eb72e-b1b5-1507-6162-16a9a4a01aa0
* Content: [Key encryption at rest in Windows and Azure using ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-encryption-at-rest?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/data-protection/implementation/key-encryption-at-rest.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/implementation/key-encryption-at-rest.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for reporting this @asbestos. I'll fix these up. They've moved it to ...

https://support.microsoft.com/topic/bf374083-626f-3446-2a9d-3f6077723a60
