### ISSUE TITLE
Confusing language describing the different lifespans

### ISSUE THREAD

**Issue by PandaFoxx** [dotnet/AspNetCore.Docs#22559]
There seems to be an error in language regarding the lifespans, just above the section ["Call services from main"](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#call-services-from-main)...

The document states: "Scoped objects are the same for each request but different across each request."

I assume it's instead meant to be: ""Scoped objects are the same for each request but different across each **session**."? (or something similar to that nature)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#lifetime-and-registration-options)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's right but poorly worded.
See [Scoped](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scoped) which is clear.

**Comment by JeffOkaki** [comment]
"Services of a given lifetime shouldn't use a database context with a lifetime that's shorter than the service's lifetime"

What? Time to refactor the docs 

How about. "Do not use a database context with a lifetime shorter than the services'"

**Comment by Rick-Anderson** [comment]
Fantastic. Do you want to PR this? IF you do, add the link I mentioned above.

**Comment by JeffOkaki** [comment]
No, I tried doing a PR earlier on this but it wasn't working for some reason. Need to get back to reading the docs for now :)

**Comment by Rick-Anderson** [comment]
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by nyctef** [comment]
+1 for finding this confusing! I assumed it was intended to be "Scoped objects are the same for each request but different across different requests."
