### ISSUE TITLE
Tutorial inadvertently blurs distinction between view models and DTOs

### ISSUE THREAD

**Issue by itowlson** [dotnet/AspNetCore.Docs#22553]
The sentence on this page "The subset of a model is usually referred to as a Data Transfer Object (DTO), input model, or view model" has confused at least one colleague into concluding that DTOs and view models are the same thing.  While the use of view models in ASP.NET server side code may be similar to DTOs, they are very different in general.  Would it be possible to remove or re-word this sentence please?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#prevent-over-posting)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What did you have in mind? The or indicates they aren't necessarily the same thing. Sometimes you use a DTO, sometimes an input model, sometimes a view model.
