### ISSUE TITLE
Missing section "Apply the migration to the existing database"

### ISSUE THREAD

**Issue by nubok** [dotnet/AspNetCore.Docs#22574]
The text says:

> With the existing database, there are two approaches to changing the database:
> 
> - Drop and re-create the database. Choose this section if when using SQLite.
> - Apply the migration to the existing database. The instructions in this section work for SQL Server only, not for SQLite.
> 
> Either choice works for SQL Server. While the apply-migration method is more complex and time-consuming, it's the preferred approach for real-world, production environments.

The target for the link "Apply the migration to the existing database" (and thus this section) is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #22517
