### ISSUE TITLE
CORS HttpOptions is not working as per doc. 

### ISSUE THREAD

**Issue by vishaljaiswal1993** [dotnet/AspNetCore.Docs#22579]
As per https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1
it says if we want allow specific header in CORS Access-Control-Request-Headers then we can use WithHeaders and define our specific header .

But in .netcore 3.1 when we define header list in side WithHeaders it simply return Header list in Access-Control-Allow-Headers.
Example - In .netcore 2.1 if we pass some invalid header(which is not listed in WithHeaders) in Access-Control-Request-Headers it doesn't return  Access-Control-Allow-Header or Access-Control-Allow-Methods .
But in 3.1 whatever we pass in Access-Control-Request-Headers value it simply return the list, inside WithHeaders we define.
And it's not the behavior as per doc.

**Comment by guardrex** [comment]
Hello @vishaljaiswal1993 ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
