### ISSUE TITLE
Caching > Overview jumps straight to Response Caching

### ISSUE THREAD

**Issue by lonelydev** [dotnet/AspNetCore.Docs#22572]
I was going through the docs and clicked on the Overview sub-section of Caching under Performance. 

It seems like instead of giving an overview of Caching in general, the documentation jumps straight into Response Caching in ASP.NET Core. I am not sure if this was intentional. 

I felt it might be better to give the reader an introduction into the sort of Caching that can be implemented in a web application and gradually delve into the details of the different types of caching. 

![image](https://user-images.githubusercontent.com/9505396/122683418-de7fa780-d1f6-11eb-8a7a-3032506a7378.png)

Looking at the image, the sections are titled appropriately but the contents seem to have a subtle mismatch. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, we'll take a look on the next update.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
