### ISSUE TITLE
CORS HttpOptions is not working as per doc

### ISSUE THREAD

**Issue by vishaljaiswal1993** [dotnet/AspNetCore.Docs#22581]
[EDIT by guardrex to add the original issue comment and metadata]

> As per https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1
it says if we want allow specific header in CORS Access-Control-Request-Headers then we can use WithHeaders and define our specific header .
>
> But in .netcore 3.1 when we define header list in side WithHeaders it simply return Header list in Access-Control-Allow-Headers.
Example - In .netcore 2.1 if we pass some invalid header(which is not listed in WithHeaders) in Access-Control-Request-Headers it doesn't return Access-Control-Allow-Header or Access-Control-Allow-Methods .
But in 3.1 whatever we pass in Access-Control-Request-Headers value it simply return the list, inside WithHeaders we define.
And it's not the behavior as per doc.

~Old issue is closed with any information. Please provide correct information regarding this.~
Old issue Link - https://github.com/dotnet/AspNetCore.Docs/issues/22579

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@vishaljaiswal1993 ... Open issues here using the **This page** feedback form at the bottom of the **English-US** topic. I'll add the metadata this time, but please use our process. We're very busy here. 🏃😅

**Comment by fiyazbinhasan** [comment]
Hi, @vishaljaiswal1993, I suppose you are talking about the preflight requests,

With a wrong request header that is not set in `WithHeaders("x-custom-header")`,

```
this.httpClient.get('http://localhost:5001/api/values',
    {
      headers: {'x-custom-heade':'missing an R'}
    })
    .subscribe(
      data => {
        console.log(data);
      },
      err => {
        console.log(err);
      }
    );
```

### For 2.1 - 

![image](https://user-images.githubusercontent.com/6568968/125273678-01513780-e32f-11eb-82a8-ac2d1ca4b214.png)


### For 3.1 -

![image](https://user-images.githubusercontent.com/6568968/125274219-90f6e600-e32f-11eb-9a8a-22c92e0fe139.png)

Seems ok. In 2.1 `Access-Control-Allow-Methods` wasn't available in the `Response`. In 3.1, you can see what request headers you have sent in the preflight request.

Could you point out the place in the docs where this information is misleading? thanks 🚀

**Comment by vishaljaiswal1993** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1#preflight-requests
In .netcore 3.1
doc says if we want allow specific header then we can list inside withheaders("") and these particular headers will be allowed.
But if we define specific header inside withheaders("") and pass any header value. it simply return Header list define in withheaders(""). means it doesn't filter from withheaders list.

**Comment by fiyazbinhasan** [comment]
That's the default behavior from what I can understand. There is no mention of filtering headers if I have read the documentation correctly.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
