### ISSUE TITLE
Document producing ProblemDetails using ASP.NET Core middleware

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#22587]
In order to react to https://github.com/dotnet/aspnetcore/issues/4953, we want to document how developers can use a middleware to produce a [ProblemDetails ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-5.0) object when handling exceptions from their application. This can be done using:

- The open source ProblemDetails middleware (see https://github.com/khellang/Middleware)
- Their own middleware built on top of the ExceptionHandler for example

I think we probably in the [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by serpent5** [comment]
@Rick-Anderson This one's already been handled in https://github.com/dotnet/AspNetCore.Docs/pull/22600.
