### ISSUE TITLE
Improvement needed

### ISSUE THREAD

**Issue by mcurko** [dotnet/AspNetCore.Docs#22580]
[EDIT by guardrex to add the metadata. @mcurko, I'm going to tag this for the HTTP.sys doc because we tend to roll security coverage for servers into the individual server doc and not in the *Security and Identity* node. That node might be the right spot in the end tho. Let's just start by tagging the HTTP.sys doc with this for now. Since this is a broad security feedback issue, let's cc: @blowdart.]

I find the whole "Security and identity" documentation very hard to understand. It introduces many new concepts without clear description on how it all works. I'll give you an example of my own code (part of it), which is an Service Fabric web app with Windows authentication:

```
.UseHttpSys(options =>
{
	options.Authentication.Schemes = AuthenticationSchemes.Negotiate | AuthenticationSchemes.NTLM;
	options.Authentication.AllowAnonymous = false;
})
```

Why do I need to use those authentication schemes and is this correct at all? I chose these simply by experimenting with several browsers and discovered that this is what works for all of them. Now, I'm not asking anyone to analyze and fix my code, I'm rather stressing the fact that for real-life questions like this one there's no information to be found in the documentation. And this is just a very simple and common case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
