### ISSUE TITLE
Please mention magic "drop API permission and re-add" in the document

### ISSUE THREAD

**Issue by Alienroid** [dotnet/AspNetCore.Docs#22584]
Referring to https://github.com/dotnet/AspNetCore.Docs/issues/21640, particular this "I dropped the API permission from the app and re-added it."

I've changed 0 code and re-added second time to get it to work. Just magic! :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Alienroid ... It's already being tracked by the UE tracking issue at https://github.com/dotnet/AspNetCore.Docs/issues/19286.

**Comment by Alienroid** [comment]
Thank you Luke. I just wanted to praise you on the documentation and the follow up on that other thread. Thanks again, we really appreciate your hard work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
