### ISSUE TITLE
UseExceptionHandler and UseStatusCodePagesWithReExecute re-execution

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#22598]
Some FAQ for UseExceptionHandler:

Since this middleware can re-execute the request pipeline...
- Middleware need to handle reentrancy with the same request. This normally means either cleaning up their state after calling _next or caching their processing on the HttpContext to avoid re-doing it. When dealing with the request body this either means buffering or caching the results like the Form reader.
- For the UseExceptionHandler(IApplicationBuilder, String) overload used in templates, only the request path is modified and the route data cleared. Request headers, method, items, etc. are all re-used as-is.
- Scoped services remain the same.

UseStatusCodePagesWithReExecute has the same considerations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 58443](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58443)

**Comment by wadepickett** [comment]
@Tratcher (Chris),  Thanks very much for the suggested improvement!
