### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sababuvercetti** [dotnet/AspNetCore.Docs#22596]
[That is nice information right there]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Thanks @sababuvercetti! :rocket:
