### ISSUE TITLE
PasswordEntry's Password parameter binding is confusing

### ISSUE THREAD

**Issue by peterbozso** [dotnet/AspNetCore.Docs#22593]
The `PasswordEntry` component which is referenced twice on this page seems to be faulty. It's `Password` parameter is never used inside the component's logic, but it's private `password` member is referenced both in the markup and the event handler. Because of this, the parent component is notified of changes, but if the parent component sets the initial value of this parameter (like it does in the `PasswordBinding` example), nothing happens. So currently, it's essentially a one-way binding: from the child to it's parent, but not a two-way one, which it supposed to be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @peterbozso ... I might need to get back to you further tomorrow morning because my brain got fried out on Blazor form validation and other tasks this morning 😅. But .... isn't that property set via attribute in the example of the parent ...

```razor
<PasswordEntry @bind-Password="password" />
```

**Comment by guardrex** [comment]
Ok ... I'm **_baaaaack_**. The idea here was merely to show the chained bind *UP*. That 'Not Set' piece was purely for the initial value display **_in the parent component_**. It wasn't intend to bind down, IIRC. I mean that it doesn't, of course as you say, so I think that's what I assumed would be understood. It's causing confusion here, so it needs a bit of work.

If you want that behavior, you can get it with the pattern in next example (next section), which avoids the shared component writing to its own parameter by setting up a 2nd property with accessors ...

```csharp
private string BoundValue
{
    get => Password;
    set => PasswordChanged.InvokeAsync(value);
}
```

... and then bind the `<input>` to that ...

```razor
<input @oninput="OnPasswordChanged"
        required
        type="@(showPassword ? "text" : "password")"
        value="@BoundValue" />
```

... then you get a bind *down* to the child. You can go both ways at that point. Note that even thus far with such an update that `password` in the child only gets an update when the field is changed, not if updated from the parent on an initial load of the shared component or if the `password` in the parent is updated, say via an event in the parent --- the field would be updated, but the actual value of `password` in the child is unchanged until that field gets an `oninput` fired. I think it's fair to assume tho that if one has a "password entry" shared component that what they're often trying to do is get a little reusable, shared HTML/CSS/form thing going that takes the password from the user and gets the value up to the parent. By the time the parent uses it, the child has validated/modified it or whatever the dev wants to do.

I'll look in the morning and see what I can do to clarify this password entry scenario further. I'll probably write out a bit more on this example and what's up with the 'Not Set' bit. It might be a good idea to go ahead and mention this angle on the 2nd property (and a component avoiding writing to its own parameter). Thanks for commenting on this.
