### ISSUE TITLE
Error popup on tutoirial adding a model to a Razor Pages app in ASP.NET Core. please install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by chrisleadbeater** [dotnet/AspNetCore.Docs#22604]
Error in tutorial adding a model to a Razor Pages app in ASP.NET Core during scaffold creation. "...please install Entity Framework core packages and try again: Microsoft.EntityFrameworkCore.Design"

Part 2, add a model to a Razor Pages app in ASP.NET Core

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1&tabs=visual-studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Why are you following the 2.1 version, it will soon be unsupported. 3.1, 5.0 has correct, complete instructions. I think 2.1 does too.

**Comment by chrisleadbeater** [comment]
Got it. Thanks.

**Comment by chrisleadbeater** [comment]
This attitude is a concern to me.

We have dozens of applications in ASP.NET web forms and a limited number of staff. What happens when we start rewriting these old ones as ASP.Net core pages version 5.0 and then that becomes unsupported? We still even have some very old classic ASP with VB dcom.

These are not always simple applications and take several months to develop. We don't have time to rewrite every 2 years when a new .net core version comes along and the old one is un-supported. Or "forget everything else, use Blazor".

Until there is a stable, real "long term" - meaning 5 years not 1 or 2 years release, I'm hesitant to move anything or rewrite anything in ASP.NET dot net core.



Chris
