### ISSUE TITLE
Mention easier way of adding persisting additional tokens 

### ISSUE THREAD

**Issue by KurtP20** [dotnet/AspNetCore.Docs#22613]
I am fighting my way through integrating Microsoft/AzureAD as an external login provider in my Blazor server side app with asp.net Identity. As I do this for the first time, I was overwhelmed with the instructions given on this site on how to persist additional tokens. But luckily I found out, that - at least with Microsoft as external login provider - one can configure the token to include additional claims in the ID token in Azure portal. Those claims are received in `info.Principle`, which simplifies the procedure a lot!

It would be nice if you add a section mentioning this easier way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KurtP20 ... Although we cross-link to this topic for Blazor Server, it might be best to document this item in both spots.

https://docs.microsoft.com/aspnet/core/blazor/security/server/?view=aspnetcore-5.0&tabs=visual-studio#additional-claims-and-tokens-from-external-providers

We also need to find the appropriate cross-link in Azure docs because ideally we should punt as much as we can on this point to their docs. I'll start by searching around ...

https://docs.microsoft.com/azure/architecture/multitenant-identity/claims

If you discover the Azure AD doc that pertains to the portal setting, @KurtP20, please post it here.

**Comment by KurtP20** [comment]
Thanks for adding the link to this page. It would have helped me. 
Maybe I have overlook a second change you made to this page. My origianl suggestions was to add a note, that the procedure described on this page might not be necessary for Microsoft as authentication provider: with AzureAD, one can simple select additional claims in the ID token in Azure portal, and they automagically appear in `info.Priciple`. So no need to search for the right scope, `MapJsonKey` etc. I have not found any documentation describing this, I found out by trial and error, and whished it would have been desribed on this page.

**Comment by KurtP20** [comment]
Could you please comment on my previous (comment)[https://github.com/dotnet/AspNetCore.Docs/issues/22613#issuecomment-869206704]

**Comment by guardrex** [comment]
We don't really work off of closed issues and PRs. I'm not sure why you were guided to leave a comment here. You did the right thing to open a new issue. AFAIK, it's addressed. Open a new issue and explain why you think it wasn't resolved if https://github.com/dotnet/AspNetCore.Docs/pull/22621 didn't cover it.

**Comment by Rick-Anderson** [comment]
@guardrex  he had incomplete information in the new issue and the issue had been resolved. If the issue is  not resolved and has all the information, it's OK to reopen the issue.
