### ISSUE TITLE
Update TestServer limitation

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/AspNetCore.Docs#22618]
Let's add a comment about this limitation of TestServer: https://github.com/dotnet/aspnetcore/issues/33780

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9421feee-5207-e379-00fb-847cc880014c
* Version Independent ID: 8415adee-793e-2ba7-b97b-672b493ba42b
* Content: [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Tratcher
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wade, look at dotnet/aspnetcore#33780 and add a comment to this article.
