### ISSUE TITLE
Derive from Controller vs. ControllerBase

### ISSUE THREAD

**Issue by marshalluous** [dotnet/AspNetCore.Docs#22610]
Dear .Net Team

Could you get more specific about the following description of yours?
"Don't create a web API controller by deriving from the Controller class. Controller derives from ControllerBase and adds support for views, so it's for handling web pages, not web API requests".

Yours sincerely
Marcel Stocker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by marshalluous** [comment]
e.g. If I want to handle API's what advantage do I have when my very own concrete controller derives from ControllerBase and which disadvantages do I have if I then derive from Controller?

**Comment by wadepickett** [comment]
Thanks @marshalluous for taking the time to make suggestions for improving this topic.  It is appreciated.

**Comment by fiyazbinhasan** [comment]
@marshalluous `Controller` class has the same functionality as `ControllerBase` 

```
public class Controller : ControllerBase 
{
     /* Additional view related stuff */
}
```
However, practically you don't return `Views` from your `Actions` defined in the controller when working in a WEB API app. Using the `Controller` class will carry over some extra things (nonbeneficial) that you only need in an MVC app.

**Comment by Rick-Anderson** [comment]
Thanks @fiyazbinhasan
