### ISSUE TITLE
Uploading Large Files - Over 4GB 

### ISSUE THREAD

**Issue by Eelesy** [dotnet/AspNetCore.Docs#22623]
See #22549

Hi All,

Been following the file upload samples and after many days of trying to get this to work I am stuck.

I need to be able to upload files up to 10GB - I am using the streaming physical method. I have changed the Request Size limit. I am using IIS, so I have turned off Request Filtering to get a file over 4GB to be accepted. But any file over 4GB I choose, the controller hits and then errors with Unexpected end of stream. I have the DisableFormBinding attribute, I have tried enabling buffering, I have tried ignoring the AntiForgeryToken - I am out of ideas.

Is a file over 4GB impossible to do via streaming, do I need to use an older chunking method?

Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Close per https://github.com/dotnet/AspNetCore.Docs/pull/22549#issuecomment-869189291
