### ISSUE TITLE
Uploading Large Files over 4GB - Unexpected End of Stream

### ISSUE THREAD

**Issue by Eelesy** [dotnet/AspNetCore.Docs#22622]
Hi All,

Been following the file upload samples and after many days of trying to get this to work I am stuck.

I need to be able to upload files up to 10GB - I am using the streaming physical method. I have changed the Request Size limit. I am using IIS, so I have turned off Request Filtering to get a file over 4GB to be accepted. But any file over 4GB I choose, the controller hits and then errors with Unexpected end of stream. I have the DisableFormBinding attribute, I have tried enabling buffering, I have tried ignoring the AntiForgeryToken - I am out of ideas.

Is a file over 4GB impossible to do via streaming, do I need to use an older chunking method?

Thanks,

**Comment by guardrex** [comment]
Hello @Eelesy ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
