### ISSUE TITLE
Launching Woker Service with scoped DI

### ISSUE THREAD

**Issue by mikeren2014** [dotnet/AspNetCore.Docs#22626]
[EDIT by guardrex to add the metadata. @mikeren2014 ... Please use the **This page** feedback button and form at the bottom of the US-English topic to have the metadata added automatically. We use the info for tracking, and it will ping the author of the topic automatically.]

I am using .net 5 worker service

If I try to inject a scoped service, and run it with "dotnet run --environment Development", I will get below error.

> Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: TestScoped.Worker': Cannot consume scoped service 'TestScoped.IMyScopedService' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)

But if I run the project with "dotnet run --environment qa", it will work without any problem.

I know [this document ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task) suggests to consume scoped services like this:

 ```
private async Task DoWork(CancellationToken stoppingToken)
    {
        _logger.LogInformation(
            "Consume Scoped Service Hosted Service is working.");

        using (var scope = Services.CreateScope())
        {
            var scopedProcessingService = 
                scope.ServiceProvider
                    .GetRequiredService<IScopedProcessingService>();

            await scopedProcessingService.DoWork(stoppingToken);
        }
    }
```

But I am really curious why it works just by changing the environment.  The appestting transforms for Development and qa are exactly the same.

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

Here is my code in case needed. Except the scoped service, nothing is really changed based off the worker template.

Program.cs

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace TestScoped
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddScoped<IMyScopedService, MyScopedService>();
                    services.AddHostedService<Worker>();
                });
    }
}
```

MyScopedService.cs

```
using System;
using Microsoft.Extensions.Hosting;

namespace TestScoped
{
    public interface IMyScopedService
    {
        void TestFunc();

    }

    public class MyScopedService : IMyScopedService
    {
        readonly IHostEnvironment _env;
        public MyScopedService(IHostEnvironment env) => _env = env;

        public void TestFunc() => Console.WriteLine($"TestFunc: {_env.EnvironmentName}");
    }
}
```
Worker.cs
```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace TestScoped
{
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        readonly IMyScopedService _myScopedService;

        public Worker(ILogger<Worker> logger, IMyScopedService myScopedService)
        {
            _logger = logger;
            _myScopedService = myScopedService;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _myScopedService.TestFunc();

                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
    }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#consuming-a-scoped-service-in-a-background-task)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
We validate scopes by default in development. There's a sight performance hit so we do it during dev so that you can fix these bugs before deploying

**Comment by mikeren2014** [comment]
> 
> 
> We validate scopes by default in development. There's a sight performance hit so we do it during dev so that you can fix these bugs before deploying

But the code does work for other environment( like qa) without the validation. Does it mean the validation in development is not accurate?

**Comment by davidfowl** [comment]
I didn't explain it properly then. Scope validation and dependency validation only happens when the environment is development (because of the performance cost I mentioned before). 

The check will "pass" in other environments and your dependencies will be wrong (In this case a scoped dependency injected into a singleton)

**Comment by mikeren2014** [comment]
Thanks for your answers, but I am still confused.

> I didn't explain it properly then. Scope validation and dependency validation only happens when the environment is development (because of the performance cost I mentioned before).

Yes, I understand what you mean. I don't see any error happening, because the validation doesn't happen in other environments, right?

> The check will "pass" in other environments and your dependencies will be wrong (In this case a scoped dependency injected into a singleton)

But when I run in other environments, it doesn't go wrong at all. I can see the expected output without any problem. That's what really confuses me.

**Comment by davidfowl** [comment]
> But when I run in other environments, it doesn't go wrong at all. I can see the expected output without any problem. That's what really confuses me.

Ah! Well it works but your scoped service will end up being a singleton. This might have a few problems:
- It's may not be thread safe
- It may hold onto state longer than you expect 
- It won't be disposed until the host is disposed

**Comment by mikeren2014** [comment]
> > But when I run in other environments, it doesn't go wrong at all. I can see the expected output without any problem. That's what really confuses me.
> 
> Ah! Well it works but your scoped service will end up being a singleton. This might have a few problems:
> 
> * It's may not be thread safe
> * It may hold onto state longer than you expect
> * It won't be disposed until the host is disposed

Ok, now I see your point . So it will have some potential issue, although looks like it works. I guess that's why you do the validation in Development, as that's not encouraged.

Thank you very much for all your comments:-)

**Comment by Rick-Anderson** [comment]
@mikeren2014 I'm re-opening this to see if we want to update the doc.
