### ISSUE TITLE
AspNetCore Windows authentication web.config <authentication> section vs. launchSettings.json iisSettings section

### ISSUE THREAD

**Issue by Vesper14** [dotnet/AspNetCore.Docs#22636]
Hi. There is one thing about AspNetCore IIS integration I do not understand. Could you please clarify it for me.

I have AspNetCore 3.1 app with Windows authentication turned on.
The app has explicitly defined _web.config_ file which does not include `<authentication>` section: authentication settings (like _windowsAuthentication_ and _anonymousAuthentication_) are defined only within _launchSettings.json_.
_Csproj_-file does not include `<IsTransformWebConfigDisabled>` option.

When I deploy locally I can freely change authentication settings from  _launchSettings.json_ so they are instantly reflected in IIS site Authentication pane.

However, [it is said](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio#iis) that before deployment you need either to manually select Windows authentication for website in IIS or add `<authentication>` section in your _web.config_.
After I add `<authentication>` section to my _web.config_ I receive an error about locked section in IIS.

I wonder why do I need to go through these steps if everything works just fine even without `<authentication>` section?
Won't my app start on remote server if I omit these steps during deployment?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
