### ISSUE TITLE
Two problems concerning explanation of Use ASP.NET Core SignalR with Blazor1

### ISSUE THREAD

**Issue by ekleiman22** [dotnet/AspNetCore.Docs#22638]
[EDIT by guardrex to fix the code. @ekleiman22 ... use single-backticks around HTML/XML markup ("LangVersion" tags here).

1. On the step "Add Razor component code for chat" when I added  the code for Index.razor I got an error on
    `@using Microsoft.AspNetCore.SignalR.Client`
because that was not said that this package should be added to BlazorWebAssemblySignalRApp.Client project. Just after I added this package the error was fixed.
2. I got an error on 
    `if (hubConnection is not null)`   
as: 
> Error	CS8400	Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater
The only thing I found was to add the following text in .csproj-file
 `<LangVersion>latest</LangVersion>`
That fixed the problem.
So I think that you should to give add more details in your explanations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ekleiman22 ...

For 1 ... it's covered at ...

https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=webassembly#add-the-signalr-client-library

For 2 ... that's 5.0 era, so let me see what the versioning is doing here and get back to you.

**Comment by guardrex** [comment]
For 2 ... it's fine in its present form. The 3.x version of the topic doesn't use the *not pattern* ...

https://docs.microsoft.com/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-3.1&tabs=visual-studio&pivots=webassembly#add-razor-component-code-for-chat

I think we're good here. You'll just drop back to the 3.x version of the topic if you're on C# 8, and the package is covered in the earlier section.
