### ISSUE TITLE
Version incorrect in the instructions

### ISSUE THREAD

**Issue by Smith-Rick** [dotnet/AspNetCore.Docs#22632]
The .net 5 specific instructions, under creating the solution indicates in step 4 that the user should select version 3.0 and not leave it as version 5.0. 

Do the instructions really require version 3 and a downgrade of the .net version, or should the instructions be updated?

Specific text reads:
"Select the .NET Core target framework and ASP.NET Core 3.0. Select the API project template, and select Create."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
@Smith-Rick The document needs to be updated.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/123847726-c6c9b280-d8cb-11eb-81cd-08fe06eaef2d.png)

Filters "83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a" is:open 

![image](https://user-images.githubusercontent.com/3605364/123847818-dc3edc80-d8cb-11eb-86a0-9f2ce9ee20c3.png)

@Smith-Rick  any chance you can update this doc?
