### ISSUE TITLE
Maybe you should start with.....

### ISSUE THREAD

**Issue by vmateiaiv** [dotnet/AspNetCore.Docs#22643]
[Enter feedback here]

Add a nuget reference to Microsoft.Extensions.FileProviders.Embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Share controllers, views, Razor Pages and more with Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #16522
