### ISSUE TITLE
The X-Forwarded-Proto disappear from HttpContext.Request.Headers after config ForwardedHeadersOptions

### ISSUE THREAD

**Issue by YuxuanLin** [dotnet/AspNetCore.Docs#22640]
Hi team,

With the setup
```
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedProto;
}
```
The HttpContext.Request.Scheme will be setup correctly according to the document.

However it didn't mention that the `X-Forwarded-Proto` header will also be removed from HttpContext.Request.Headers. Our team was confused with what was happening and did some experiments to figure out what and how. It's good to have this logic  documented somewhere for reference in case other people have the same confusion. It's not a very straightforward thing to understand but very crucial for many components like authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher please comment.

**Comment by Tratcher** [comment]
Yes, that's by design. The consumed values are removed from X-Forwarded-Proto and old values are persisted in X-Original-Proto.
https://github.com/dotnet/aspnetcore/blob/13621123dbdea889def9cde78eb9141f504f4114/src/Middleware/HttpOverrides/src/ForwardedHeadersOptions.cs#L47-L52

**Comment by YuxuanLin** [comment]
Thanks for the explanation. Is it possible to add this detail into the doc for better context? Even just a mention with little annotation would be saving hours for someone someday.

**Comment by Rick-Anderson** [comment]
> Is it possible to add this detail into the doc for better context? Even just a mention with little annotation would be saving hours for someone someday.

Yes, that's why the issue is open, we'll add that. Feel free to PR this with your proposed update.

At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by YuxuanLin** [comment]
Will do thanks

**Comment by Rick-Anderson** [comment]
@YuxuanLin did you want to submit a PR for this?
