### ISSUE TITLE
Suggestion to make an instruction more clear

### ISSUE THREAD

**Issue by nubok** [dotnet/AspNetCore.Docs#22659]
Suggestion:

Replace text

> Create SchoolViewModels/InstructorIndexData.cs with the following code:

by either

> Under Models, create SchoolViewModels/InstructorIndexData.cs with the following code:

or

> Create Models/SchoolViewModels/InstructorIndexData.cs with the following code:

The text of the tutorial does not make it clear that this folder is relative to the Models folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Part 6, Razor Pages with EF Core in ASP.NET Core - Read Related Data](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

Go with

`Create *Models/SchoolViewModels/InstructorIndexData.cs* with the following code:`

**Comment by nubok** [comment]
OK, as you wished https://github.com/dotnet/AspNetCore.Docs/pull/22660
