### ISSUE TITLE
Possible to navigate to an empty page

### ISSUE THREAD

**Issue by pdavis68** [dotnet/AspNetCore.Docs#22652]
There's something glitchy going on in the documentation. I started on a page like this:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2

And then clicked on the "Make Http requests" link right below this in the navigation. It takes you to the "Make HTTP requests using IHttpClientFactory in ASP.NET Core" page, but the content is empty. This is fixed by changing the "view=" version, but I did not realize that was the issue at first and was confused why there was no text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
2.2 is out of support. Select something supporte3d.

**Comment by pdavis68** [comment]
@Rick-Anderson Yes, but it's still confusing since the first page is the one I arrived at via Google search and then when I navigated to the link SHOWN, it gave me an empty page. That is a bug. Of the topic doesn't exist for 2.2, then it shouldn't be presented in the navigation.
