### ISSUE TITLE
Unclear information about Conventional Routing order dependency

### ISSUE THREAD

**Issue by bartosz-jarmuz** [dotnet/AspNetCore.Docs#22656]
Hello,
As detailed in this SO question https://stackoverflow.com/questions/68173485/is-asp-net-core-5-0-conventional-routing-order-dependent-or-not the info about conventional routing order dependency (vs precedence) is unclear.

I would happily create a PR for this, but I am not sure on the details of how it should be phrased (warning box, a section rewrite etc).

Kind regards,
Bartosz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-5.0#conventional-routing-order)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You could propose a change. At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
This answers it
In general, route precedence does a good job of choosing the best match for the kinds of URL schemes used in practice. Use [Order](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.routeendpoint.order#microsoft-aspnetcore-routing-routeendpoint-order) only when necessary to avoid an ambiguity.
