### ISSUE TITLE
Initial Creation Build failed

### ISSUE THREAD

**Issue by mamagnus** [dotnet/AspNetCore.Docs#22653]
When I ran the Add-Migration InitialCreate command in the Package Manage Console, I got this:
Build started...
Build Failed.

This is the end of the log file:
  <entry>
    <record>944</record>
    <time>2021/07/03 20:04:24.907</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [FileSystem Package]</description>
    <guid>{AC2BF811-80A4-4FA9-A405-21EC39316782}</guid>
  </entry>
  <entry>
    <record>945</record>
    <time>2021/07/03 20:04:25.062</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [LocalFileSystemProviderPackage Package]</description>
    <guid>{BCB28B82-7692-4875-8943-5D68025049AE}</guid>
  </entry>
  <entry>
    <record>946</record>
    <time>2021/07/03 20:04:25.068</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [LocalFileSystemProviderPackage Package]</description>
    <guid>{BCB28B82-7692-4875-8943-5D68025049AE}</guid>
  </entry>
  <entry>
    <record>947</record>
    <time>2021/07/03 20:04:25.084</time>
    <type>Error</type>
    <source>GlobalBrokeredServiceContainer</source>
    <description>Microsoft.ServiceHub.Framework.ServiceActivationFailedException: Activating the &quot;Microsoft.VisualStudio.FileSystem.LocalFileSystemProvider (1.0)&quot; service failed. ---&gt; System.InvalidCastException: Unable to cast object of type &apos;Microsoft.VisualStudio.PlatformUI.Packages.FileSystem.LocalFileSystemProvider&apos; to type &apos;Microsoft.VisualStudio.RpcContracts.FileSystem.IRemoteFileSystemProvider&apos;.&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.ProfferedServiceFactory.&lt;GetProxyAsync&gt;d__28`1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at System.Threading.Tasks.ValueTask`1.get_Result()&#x000D;&#x000A;   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.ServiceBroker.GlobalBrokeredServiceContainer.View.&lt;GetProxyAsync&gt;d__19`1.MoveNext()&#x000D;&#x000A;   --- End of inner exception stack trace ---</description>
  </entry>
</activity>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Make sure you have all the Prerequisites

For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team.
