### ISSUE TITLE
Can not find the document for my country language

### ISSUE THREAD

**Issue by cnmade** [dotnet/AspNetCore.Docs#22667]
Hello, microsoft document website good so far, some document has much language(English/Chinese)
But the AspNet document does not have other language translate.

Why not provided us the different language translate document?

I would like to join and contribute translate, but not see any way to do it .

**Comment by guardrex** [comment]
Hello @cnmade ... We only handle content here for ASP.NET Core docs, not the docs build/publish system itself. See if this resource directs you to the right people ...

https://docs.microsoft.com/contribute/

**Comment by cnmade** [comment]
@guardrex No one knows who can handle this situation. For example. If i seek for ASP.NET core docs Chinese version, where is it . Who can create it .

**Comment by guardrex** [comment]
You'll have to follow the link that I provided. We don't handle localization here at all.
