### ISSUE TITLE
"public IList<Movie> Movie { get;set; } " Movie is a namespace but used like a type!

### ISSUE THREAD

**Issue by Pscyan** [dotnet/AspNetCore.Docs#22663]
The followings are the Visual studio spitting error after following through the tutorial that's in the docs! :
Severity	Code	Description	Project	File	Line	Suppression State
1. Error	CS0118	'Movie' is a namespace but is used like a type	RazorPagesMovie	D:\1. YZU Study Folder\4th Semester\0. YT and online Material folder\ASP.Net Core Tutorial follow ups from docs.ms.com\RazorPageMovies\RazorPagesMovie\Pages\Movie\Delete.cshtml.cs	23	Active

2. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0118	'Movie' is a namespace but is used like a type	RazorPagesMovie	D:\1. YZU Study Folder\4th Semester\0. YT and online Material folder\ASP.Net Core Tutorial follow ups from docs.ms.com\RazorPageMovies\RazorPagesMovie\Pages\Movie\Index.cshtml.cs	22	Active

3. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0118	'Movie' is a namespace but is used like a type	RazorPagesMovie	D:\1. YZU Study Folder\4th Semester\0. YT and online Material folder\ASP.Net Core Tutorial follow ups from docs.ms.com\RazorPageMovies\RazorPagesMovie\Pages\Movie\Create.cshtml.cs	28	Active

4. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0118	'Movie' is a namespace but is used like a type	RazorPagesMovie	D:\1. YZU Study Folder\4th Semester\0. YT and online Material folder\ASP.Net Core Tutorial follow ups from docs.ms.com\RazorPageMovies\RazorPagesMovie\Pages\Movie\Details.cshtml.cs	22	Active

5. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'System.Collections.Generic.List<RazorPagesMovie.Models.Movie>' to 'System.Collections.Generic.IList<RazorPagesMovie.Pages.Movie>'. An explicit conversion exists (are you missing a cast?)	RazorPagesMovie	D:\1. YZU Study Folder\4th Semester\0. YT and online Material folder\ASP.Net Core Tutorial follow ups from docs.ms.com\RazorPageMovies\RazorPagesMovie\Pages\Movie\Index.cshtml.cs	26	Active

![image](https://user-images.githubusercontent.com/74078575/124541393-df9a1100-de53-11eb-915e-e493d605b60e.png)

Also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Hi @Pscyan! You are getting this error because you have a namespace `RazorPagesMovie.Pages.Movie` which is conflicting with the `Movie` type under the `Models` folder. Please rename your namespace to `RazorPagesMovie.Pages.Movies` for the files under `Pages > Movie`. I would suggest you go with pluralized naming for the `Pages` folders as the documentation also does the same. Thanks.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

Thanks @fiyazbinhasan
