### ISSUE TITLE
Changelog for the Javascript client

### ISSUE THREAD

**Issue by Tiberriver256** [dotnet/AspNetCore.Docs#22685]
Hello,

I am upgrading from version 3.1.7 of the javascript client to version 5.0.7. I would like to know what breaking changes were introduced in version 4 and version 5 of the library and ideally some instructions on how to migrate from the older version of the library.

Is there any resource like this available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-5.0#additional-resources)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @Tiberriver256 ...

We keep any relevant migration info in the *Migration* node. For this version jump, check ...

https://docs.microsoft.com/aspnet/core/migration/31-to-50

You can also check the announcements to see if anything was put up there ...

https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+label%3A5.0.0

You can also look at the product unit release notes for each release. For example for 5.0 ......

https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0.0/5.0.0.md

... and then there are similar readme files for each of the patches for 5.0 (5.0.1, etc.).

**Comment by Tiberriver256** [comment]
Thanks @guardrex! Good to know. I had seen those pages but they all seemed specific to the .NET stuff without mentioning the javascript libraries. It makes sense though if nothing has really changed.

**Comment by guardrex** [comment]
Ok ... I'll close this. If you discover a delta that we need to call out, please open a new issue from the **This page** feedback button at the bottom of the topic as you did for this issue.
