### ISSUE TITLE
Error installing EF

### ISSUE THREAD

**Issue by andrei-mu** [dotnet/AspNetCore.Docs#22681]
When running the commands to install EF, if only .Net Core SDK is installed, there's an error:
`dotnet tool install --global dotnet-aspnet-codegenerator`
error NU1202: Package dotnet-aspnet-codegenerator 5.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package dotnet-aspnet-codegenerator 5.0.2 supports: net5.0 (.NETCoreApp,Version=v5.0) / any
The tool package could not be restored.

The correct command is
`dotnet tool install -g dotnet-aspnet-codegenerator --version="3.1.5"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@andrei-mu  why are you installing the 3.x version and not the current 5.x version?
