### ISSUE TITLE
services.Configure<T>() not working this way anymore?

### ISSUE THREAD

**Issue by MichiSpahr93** [dotnet/AspNetCore.Docs#22699]
It seems that deserializing the appsettings.json to BookstoreDatabaseSettings (Step 3) doen´t work this way anymore...?!
services.Configure<T>() couldn´t handle the given section. => I couldn´t find a matching overload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by steveberdy** [comment]
@MichiSpahr93 Did you include the `Microsoft.Extensions.DependencyInjection` using directive? That includes the `IServiceCollection.Configure<TOption>` method.

**Comment by MichiSpahr93** [comment]
Hi @steveberdy - I did. But the method expects an argument of type `Action<T>` instead of `IConfigurationSection`. 
I´m targeting .NET 5.0. Do I miss something else?

**Comment by steveberdy** [comment]
It's probably expecting a lambda, such as `x => x.Configure<T>...`
Can you show a code snippet from `Startup.cs` please?

**Comment by MichiSpahr93** [comment]
Right - I think I should give a bit more context here :) 
I´m referring to the tutorial [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio)
In step "3 Add the following highlighted code to Startup.ConfigureServices:" the document shows:
```
services.Configure<BookstoreDatabaseSettings>(
        Configuration.GetSection(nameof(BookstoreDatabaseSettings)));
```
Now this statement puts a IConfigurationSection into the Configure<T>() method. 
Trying this I get the intellisenses message : cannot convert from IConfigurationSection to Action<T>.

**Comment by steveberdy** [comment]
@MichiSpahr93 what are your using directives? The line above that line in the tutorial says that it "requires using Microsoft.Extensions.Options"

**Comment by MichiSpahr93** [comment]
Yeah, this seem confusing as well. 
My using-imports are:
```
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
```
The mentioned `Microsoft.Extensions.Options` is needed to resolve the `IOptions` - Interface used in the line below.

**Comment by steveberdy** [comment]
[Here](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app/samples/3.x/SampleApp/Startup.cs) is the sample `Startup.cs` script. Since you know your script best, you should be able to identify what's wrong faster. Let me know if that helped.

**Comment by MichiSpahr93** [comment]
Ah, there it is...
Against the documentation I wanted to pull these statements to an separate DataAccessService-Library, providing a `IServiceCollection` -Extension method. The using statements are correct, but the missing overload for `Configure<T>(IConfiguration config)` accepting the IConfigurationSection is in a library called `Microsoft.Extensions.Options.ConfigurationExtensions`.  
Thank you very much for giving me a rope here! @steveberdy

**Comment by steveberdy** [comment]
You're welcome!
