### ISSUE TITLE
How to pass arguments into the queued background work

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/AspNetCore.Docs#22702]
The example given, while helpful, doesn't shed much light into how it could be modified to allow arguments to be passed into the queue and stored along the tasks for processing at a later time.

As it is, since the QueueHostedService implements BackgroundService, it neatly handles a no-argument situation since the ExecuteAsync override simply calls BackgroundProcessing and passes in its CancellationToken, but then BackgroundProcessing itself then pulls the function out of the queue to execute, and.. well, there's no argument that's been stored, so passing anything into the `await workItem(customArg, stoppingToken)` fails for lack of a sourced `customArg`.

It'd be useful to see a second example provided that explains how to queue data to pass into the ValueTask methods so it's available at processing time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Hi, @WhitWaldo! If I've understood the use case correctly, isn't that something you would do with a `ValueTask<T>` where T is the `customArg` type? Something like the following,

```
ValueTask<CustomArg> QueueBackgroundWorkItemAsync(Func<CancellationToken, ValueTask<CustomArg>> workItem);

ValueTask<Func<CancellationToken, ValueTask<CustomArg>>> DequeueAsync(
    CancellationToken cancellationToken);
```

**Comment by WhitWaldo** [comment]
Hello @fiyazbinhasan and thanks for writing back! It's definitely something I can share the type of through the ValueTask<T>, but where I can define the Func that accepts that argument, it wasn't clear how I'd pass the actual data comprising that argument into the Func when doing the work.

Looking at the example [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#queued-background-tasks), I can queue the work item (the Func) to the channels queue. When it's executed on in the following class (`1QueuedHostedService`), it's unclear where the argument would come from to pass into `BackgroundProcessing` to actually run the Func against that data. 

It doesn't make a lot of sense to have a function pop out that I can evaluate without any data stored alongside it, so that's the crux of my inquiry here. Yeah, I can modify the signature from `Func<CancellationToken, ValueTask>` and instead have it do something like `Func<CancellationToken, TThing, ValueTask<TThing>>` so I have the background task work against my TThing and return its own TThing, but it's not clear where I can then put the TThing so the data is queued alongside the function itself.

**Comment by davidfowl** [comment]
@WhitWaldo I'm a bit confused. Where does TThing come from in your case? Right now the state of these functions can be captured via a closure:

```C#
var state = new TThing();
_taskQueue.QueueBackgroundWorkItemAsync(token => DoSomeWork(state));
```

Does that work in your situation?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
