### ISSUE TITLE
re: Authentication:Microsoft:ClientSecret

### ISSUE THREAD

**Issue by anichin** [dotnet/AspNetCore.Docs#22706]
dotnet user-secrets set "Authentication:Microsoft:ClientSecret" "<client-secret>"

Does <client-secret> refer to the Secret ID or the Secret Value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's explained at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0#store-the-microsoft-client-id-and-secret

**Comment by anichin** [comment]
It is mentioned under
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-5.0#create-client-secret


   -

   Under Client secrets, copy the value of the client secret.

It implies you will need the value later but it is not explicit enough. It
will be better to say:

dotnet user-secrets set "Authentication:Microsoft:ClientSecret"
"<client-secret-value>"

or just add text "replace <client-secret> with the client secret value"

The client secret has a description, value and secret id. Since the value
and the secret id look similar (random string of symbols) it can be
confusing.
In addition one can assume that if we store the Client *ID* we should store
the Secret *ID* too (instead of the secret value).

**Comment by Rick-Anderson** [comment]
See the link to secret manager
