### ISSUE TITLE
Suggestion to add a code example

### ISSUE THREAD

**Issue by fukalov** [dotnet/AspNetCore.Docs#22712]
Code below depends on the NuGet package Microsoft.AspNetCore.Authentication.Google
```
    services.AddAuthentication()
        .AddGoogle(options =>
        {
            IConfigurationSection googleAuthNSection =
                Configuration.GetSection("Authentication:Google");

            options.ClientId = googleAuthNSection["ClientId"];
            options.ClientSecret = googleAuthNSection["ClientSecret"];
        });
```
I believe that the code below is necessary as an alternative  
```
	services.AddAuthentication()
		.AddOpenIdConnect("Google", "Google", options =>
			{
				IConfigurationSection googleAuthNSection =
					Configuration.GetSection("Authentication:Google");
					
				options.ClientId = googleAuthNSection["ClientId"];
				options.ClientSecret = googleAuthNSection["ClientSecret"];
				options.Authority = "https://accounts.google.com";
				options.ResponseType = OpenIdConnectResponseType.Code;
				options.CallbackPath = "/signin-google"; 
			})
		.AddIdentityServerJwt();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion but the existing code is what we want to show.
