### ISSUE TITLE
thêm video

### ISSUE THREAD

**Issue by xthanh1212** [dotnet/AspNetCore.Docs#22715]
nên tạo ra một video tôi có thể hiểu thêm cách thức hoạt động mà bạn hướng dâ·

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/vi-vn/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
should make a video i can understand more how it works you guide

Sorry, we don't do video's.
