### ISSUE TITLE
Trying to Deploy .netcore application on Linux using Nginx

### ISSUE THREAD

**Issue by harikrishnamupp** [dotnet/AspNetCore.Docs#22716]
[Enter feedback here]

I am trying to deploy a .netcore app (2.1) on ubuntu 16.04 machine

When i run command dotnet "filename.dll" i am getting below error,

All the dependencies are installed (dotnet runtime, dotnet core sdk 2.1)

code runs fine on IIS

Unhandled Exception: System.Security.Cryptography.CryptographicException: Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores. ---> System.PlatformNotSupportedException: Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Synapse.STS.Startup.ConfigureServices(IServiceCollection services) in C:\PATH\Startup.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Synapse.STS.Program.Main(String[] args) in C:\PATH\Program.cs:line 38

line 38 from program.cs var host = BuildWebHost(args);
Line 77 from startup.cs store.Open(OpenFlags.ReadOnly);

below is the code defined for certificate,

X509Store store = new X509Store(StoreLocation.LocalMachine);
            X509Certificate2 cer = new X509Certificate2();
            try
            {
                string tb = _configuration["Settings:SigningCredentialsTP"];
                store.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection col = store.Certificates.Find(X509FindType.FindByThumbprint,
                  tb, false);

Kindly advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @harikrishnamupp ... I think it defaults to the `My` store, and ........

> On Linux, stores are created on first write, and no user stores exist by default ...

You could try the suggestion from the message that's shown in various online posts about this error ...

```csharp
new X509Store(StoreName.CertificateAuthority, StoreLocation.LocalMachine)
```

... and get more info on supported stores from https://docs.microsoft.com/dotnet/standard/security/cross-platform-cryptography#the-my-store (although that is for 5.x and there's no <5.x topic AFAICT).

There's only one reference to that error on the PU repo, and it has to do with Linux in Docker containers on Azure, not when the app is on a local machine. Therefore, that mention doesn't apply. https://github.com/dotnet/aspnetcore/issues/15366#issuecomment-546681045

@Rick-Anderson ... If that works out to be correct, perhaps merely a cross-link in the *Additional resources* (combined with the straightforward error message) would be enough to cover it. 🤔

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
