### ISSUE TITLE
Bad link in Net 5.0 Documents "RCL Pages Layout"

### ISSUE THREAD

**Issue by rm-code** [dotnet/AspNetCore.Docs#22727]
The link in the section below is invalid in the 5.0 Version of the page. 
![image](https://user-images.githubusercontent.com/11627131/125613535-8b56de17-d39d-46d0-9f02-8b752c196ce6.png)

The 3.0 version of the page the link works as expected:
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#rcl-pages-layout

In the 5.0 version of the page the link needs to be changed from:
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio#rcl-pages-layout

To:
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio#rcl-pages-layout-2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by rm-code** [comment]
@Rick-Anderson I briefly looked at it before opening this issue, but I couldn't figure out the issue - I'm not familiar with the way these docs are created.

```
::: moniker range=">= aspnetcore-5.0"
```
Seems to control the version the docs target, but the anchor-link itself is defined as `[RCL Pages layout](#rcl-pages-layout)` which should provide the right URL afaict.

But if you can give me some pointers I'll gladly open a PR.

**Comment by Rick-Anderson** [comment]
Monikers are confusing and make for fragile automatic links. Thanks for reporting the problem.
