### ISSUE TITLE
Explain how to handle websockets in controller

### ISSUE THREAD

**Issue by trampster** [dotnet/AspNetCore.Docs#22747]
The docs show how to handle a websocket connection in the Startup.cs which seems like very bad design.

It does not say how to handle a websocket request in a controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
You should be able to copy and paste the codez

**Comment by trampster** [comment]
Not really,

You have to:
* create [HttpGet] method in your Controller 
* use if (this.HttpContext.WebSockets.IsWebSocketRequest) to determine that is is a websocket
* use his.HttpContext.WebSockets.AcceptWebSocketAsync(); to accept the connection

**Comment by davidfowl** [comment]
> use if (this.HttpContext.WebSockets.IsWebSocketRequest) to determine that is is a websocket

This in the document. You only need to check that if you want to handle non websocket requests to the same endpoint.

> use his.HttpContext.WebSockets.AcceptWebSocketAsync(); to accept the connection

Yes, you have to use `this.` instead of having the `HttpContext` passed into the method.

```C#
public class WebSocketController : ControllerBase
{
    [HttpGet("/ws")]
    public Task WebSocket()
    {
        if (Context.WebSockets.IsWebSocketRequest)
        {
            using (WebSocket webSocket = await Context.WebSockets.AcceptWebSocketAsync())
            {
                await Echo(Context, webSocket);
            }
        }
    }
}
```

We can add that to the doc.

**Comment by trampster** [comment]
I think that would be helpful.

The [HttpGet] bit was the part that I was missing, if you don't know how exactly WebSockets work then it isn't obvious that your websocket is started from a HttpGet.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan can you write a sample with this approach?

**Comment by fiyazbinhasan** [comment]
Sure. I'll come up with a sample. 👍
