### ISSUE TITLE
What server side nuget to install?

### ISSUE THREAD

**Issue by Zapnologica** [dotnet/AspNetCore.Docs#22749]
This tutorial does not cover installing the server-side nuget package?

I am not sure which one to install?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
That's because there isn't one. The SignalR server-side binaries are included in the ASP.NET Core shared framework which is referenced automatically in a web app.

**Comment by Zapnologica** [comment]
Does this also work for mvc 5 older platforms or only. Net core

**Comment by guardrex** [comment]
@Zapnologica ... Closing as answered. WRT your 2nd question: ASP.NET Core only for the ASP.NET Core docs. The .NET Framework docs are here ...

https://docs.microsoft.com/aspnet/signalr/
