### ISSUE TITLE
Mention easier way of adding persisting additional tokens 2

### ISSUE THREAD

**Issue by KurtP20** [dotnet/AspNetCore.Docs#22743]
My previous issue was closed and I do not know how to reopen it. Since I think it is not resolved, I kindly ask you to check my comment to [#22613#issuecomment-869206704](https://github.com/dotnet/AspNetCore.Docs/issues/22613#issuecomment-869206704). 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex closed that in #22621 19 days ago

**Comment by Rick-Anderson** [comment]
Leave a comment in  #22613
