### ISSUE TITLE
Mention easier way of persisting additional tokens 3

### ISSUE THREAD

**Issue by KurtP20** [dotnet/AspNetCore.Docs#22754]
This is in response to #22613. As far as I understand this page, you describe a way of persisting additional claims when using an externel login provider. The way you described is very complex and might be necessary in case of google authentication, I cannot tell. But if AzureAD is used, it is way too complicated. Ticking the right marks in Azure Portal is enough to receive the additional claims in `info.Principle`. 

Maybe I misinterpret the intention of this page then it's fine. When I first read this page, I was overwhelmed by the amount of learning it would take me to receive the additional claims. 

So if, in the case of e.g. google authenticaion, it is necessary to establish an authentication scope, manually map the keys and create the claims I would leave the page as it is. At the top of the page however, I suggest to add a note, that if AzureAD is used, it suffices to select the additional tokens in AzurePortal and be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
