### ISSUE TITLE
Internal Server Error in RazorPagesMovie Scaffolding

### ISSUE THREAD

**Issue by Sailormoon56** [dotnet/AspNetCore.Docs#22750]
In scaffolding stage, i cannot run the app. It says JsonReaderException: ',' is an invalid start of a property name. Expected a '"'. LineNumber: 9 | BytePo
![Scaffolding](https://user-images.githubusercontent.com/85798779/125932616-a33c165b-b102-4fb4-a9c3-8dee43c0cabc.png)
sitionInLine: 5. 
I don't know how to solve in LineNumber 9.

**Comment by guardrex** [comment]
Hello @Sailormoon56 ... Please re-open this from the bottom of the doc page that you're looking at ... it will automatically ping the author and add metadata to your issue for tracking.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Sailormoon56** [comment]
Thank You. I sent the feedback. 

> Hello @Sailormoon56 ... Please re-open this from the bottom of the doc page that you're looking at ... it will automatically ping the author and add metadata to your issue for tracking.
> 
> <img alt="Capture" width="404" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
