### ISSUE TITLE
Unable to get the database to seed correctly. 

### ISSUE THREAD

**Issue by byronwarwick** [dotnet/AspNetCore.Docs#22756]
// Using VS Code --
Error at the "Add The Seed Initializer" Step in this tutoriel and have just copied the code into the Program.cs file. 

It seems to work only when i comment out the "//using MvcMovie.Data" line in each of the "SeedData.cs" & "Program.cs" files.

Also when told to create the SeedData file might be beneficial to call it SeedData.cs in the tutorial.

Trust this helps.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> It seems to work only when i comment out the "//using MvcMovie.Data" line in each of the "SeedData.cs" & "Program.cs" files.

That doesn't have any impact on it working.
