### ISSUE TITLE
Article gives good overview, but quite some important "details" are missing

### ISSUE THREAD

**Issue by HansGuckInDieLuft** [dotnet/AspNetCore.Docs#22752]
I would have had expected to find some hints on when objects in services are explored and subsequently rendered, and how a binding is being set up and can be modified if needed.
I found from trial-and-error that there is no execution plan for initialization is being set up within Blazor, instead it reliies on (non-null) objects being found at some early stage (before intialization). Objects that are being instanciated later simply "come too late". There should also be a documentation as to the dependency of the kind of services as well as client- or server-sided Blazor apps.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @HansGuckInDieLuft ... It's true that we don't have that level of detail, but we'll need engineering input from the PU ("product unit") on your remarks to see how much more content to provide and if that content should go into an advanced topic. Unfortunately, they're all working high priority framework issues for the upcoming 6.0 release and can't be pinged at this time. This won't get lost ... we will get an answer, but there will be a delay ... perhaps even several months while they complete the work on the framework for 6.0.

**Comment by guardrex** [comment]
Hello! Sorry for the **_very late_** triage/reply. Management has decided not to pursue recommendation for the Blazor docs. Thanks for inquiring on it.
