### ISSUE TITLE
CSP meta tags update

### ISSUE THREAD

**Issue by Ponant** [dotnet/AspNetCore.Docs#22755]
In https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-6.0

I had to add a connect-src to make the blazor wasm work properly in .Net 6 preview 6.
 ```
<meta http-equiv="Content-Security-Policy"
          content="base-uri 'self';
          connect-src 'self' ws://localhost:49773/;
               block-all-mixed-content;
               default-src 'self';
               img-src data: https:;
               object-src 'none';
               script-src https://stackpath.bootstrapcdn.com/
                          'self'
                          'sha256-v8v3RKRPmN4odZ1CWM5gw80QKPCCWMcpNeOmimNL2AA='
                          'unsafe-eval';
               style-src https://stackpath.bootstrapcdn.com/
                         'self'
                         'unsafe-inline';
               upgrade-insecure-requests;">
```
Otherwise I get the error `Refused to connect to 'ws://localhost:49773/BlazorAppWasm/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88177a7d-c9ff-c245-5629-a462c9258abf
* Version Independent ID: 6e0b5c52-90a1-5ca6-bfad-df33a8beae6c
* Content: [Enforce a Content Security Policy for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/content-security-policy.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/content-security-policy.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ponant ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/21898.

**Comment by guardrex** [comment]
btw @Ponant ... I note that you're not necessarily claiming that only the hash has to be addressed (i.e., the addition of `connect-src`). I'll take a look at this after 6.0 GA in case engineering churn results in updates that would lead to additional changes. Your issue here is cross-linked now to that existing issue, so I will see this when the time comes.

**Comment by Ponant** [comment]
Yup 🥇 
I think we should worry more about CSP frankly 🔢
