### ISSUE TITLE
it 's usefull

### ISSUE THREAD

**Issue by tcjwj2008** [dotnet/AspNetCore.Docs#22768]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tcjwj2008** [comment]
it 's usefull for me

**Comment by Rick-Anderson** [comment]
thanks
