### ISSUE TITLE
Razor Pages json error

### ISSUE THREAD

**Issue by Sailormoon56** [dotnet/AspNetCore.Docs#22761]
In the layout stage of Scaffolding, there is an error like this. I don't know what it means by that as i have no code experience.
![layout](https://user-images.githubusercontent.com/85798779/126031046-6aa3a262-a556-43d3-922a-2c3cd6de64a0.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
