### ISSUE TITLE
Default Hosting Model Seems wrong

### ISSUE THREAD

**Issue by EsraShrouf** [dotnet/AspNetCore.Docs#22766]
I have a reason to think there’s a small mistake in it though, regarding the default process hosting model. This https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1 article says it’s in process hosting, however, we experienced otherwise:

We have ASP.NET Core (on .ENT Core 3.1) app hosted on IIS. When hostingModel was not configured in <aspnetcore> in web.config, we could still see the dotnet process (changed its name and recycled the app pool to make sure also). We even saw events clearly indicating that w3wp.exe process is sending shutdown request to the dotnet process upon recycling the app pool (sorry don’t have the actual logs with me):

Application '….' with physical root '….' shut down process with Id '….' listening on port '….'
Process Id: …..
File Version: …. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: ….

If you are on the same page with me, we kindly ask you to please change it. There are also other pages containing the same information regarding in proc being the default, like: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5945c30c-0dfb-040e-8bdc-a6c1f06c9931
* Version Independent ID: f47ff3cc-cd78-d41c-af1c-ef1e752cae88
* Content: [web.config file](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/web-config.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/web-config.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@EsraShrouf ... Did you open the following ...

https://github.com/dotnet/AspNetCore.Docs/issues/22764

That's the issue to track this subject.

**Comment by EsraShrouf** [comment]
Hi,

Yes, apologies, I had problems with using my account so used both personal and MSFT account. First created an issue with Esrash11 then was informed by someone that I instead need to use MSFT account (EsraShrouf).

I opened the following:
MSFT account:
Default Hosting Model Seems wrong · Issue #22766 · dotnet/AspNetCore.Docs (github.com)<https://github.com/dotnet/AspNetCore.Docs/issues/22766>
Opened another one (can’t find it) and closed it referencing the above one.

Personal Account:
Default Process Hosting Model Seems Wrong · Issue #22764 · dotnet/AspNetCore.Docs (github.com)<https://github.com/dotnet/AspNetCore.Docs/issues/22764>

This is the very first time I put anything on Github. Please excuse me.


﻿ --
[Microsoft]

Esraa Alshrouf
SUPPORT ENG EMEA
Dev Support
Office: +962 (6) 5509485
***@***.******@***.***>
9 AM - 6 PM (UTC+3)
Sunday - Thursday
﻿If you have any feedback about my work, please let either me or my manager Simona Roman known at ***@***.******@***.***>
Alternate Contact: If you require further assistance and are unable to reach me, please contact ***@***.*** providing the Case number.

**Comment by guardrex** [comment]
Ok, thanks. I understand. I'm not sure what difference that would make ... **_BUT_** ... I do know that there's a lot of internal tracking of things; so if it is best for the issue to be under this GH account, then let me know @Rick-Anderson ... I can close the other issue and move my Justin ping over here.

**Comment by guardrex** [comment]
Actually, yes ... let's do that. I've closed the other issue, and I'm placing my ping here ..................

That is reproducible here. Let's check with the product unit on it ... it may have changed at some point.

@jkotalik ... Publishing defaults to the presence of `hostingModel="inprocess"`, but did the default change if `hostingModel` attribute isn't present? The docs say that `hostingModel` is a optional attribute with a default to `inprocess`, but I can reproduce @Esra11's case where the `hostingModel` attribute isn't present (3.1 and 5.0) and out-of-process behavior results (i.e., the `dotnet.exe` process is present). 

**UPDATE**: Looks like it did change at some point (if I'm looking at the right bits) ...

```
if (hostingModel.empty() || equals_ignore_case(hostingModel, CS_ASPNETCORE_HOSTING_MODEL_OUTOFPROCESS))
{
    m_hostingModel = HOSTING_OUT_PROCESS;
}
```

https://github.com/dotnet/aspnetcore/blob/main/src/Servers/IIS/AspNetCoreModuleV2/AspNetCore/ShimOptions.cpp#L22

**Comment by guardrex** [comment]
Adding @halter73 ... as @jkotalik might be away/busy.

@halter73 ... Please see https://github.com/dotnet/AspNetCore.Docs/issues/22766#issuecomment-882074267 for a question on the default hosting model (inproc vs. outofproc) when the `hostingModel` attribute isn't present in ANCM config of `web.config`.
