### ISSUE TITLE
Default Process Hosting Model Seems Wrong

### ISSUE THREAD

**Issue by Esra11** [dotnet/AspNetCore.Docs#22764]
[Enter feedback here]
Th article https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1 says it’s in process hosting, however, we experienced otherwise.

 We had an ASP.NET Core (on .NET Core 3.1) app hosted on IIS. When hostingModel was not configured in <aspnetcore> in web.config, we could still see the dotnet process (changed its name and recycled the app pool to make sure also). We even saw events clearly indicating that w3wp.exe process is sending shutdown request to the dotnet process upon recycling the app pool (sorry don’t have the actual logs with me):

Application '….' with physical root '….' shut down process with Id '….' listening on port '….'
Process Id: …..
File Version: …. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: ….

If you are on the same page with me, we kindly ask you to please change it. There are also other pages containing the same information regarding in proc being the default, like: 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1

---

***@Rick-Anderson edit:***  Esraa is an MSFT FTE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5945c30c-0dfb-040e-8bdc-a6c1f06c9931
* Version Independent ID: f47ff3cc-cd78-d41c-af1c-ef1e752cae88
* Content: [web.config file](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/web-config?view=aspnetcore-5.0&viewFallbackFrom=aspnetcore-3.1)
* Content Source: [aspnetcore/host-and-deploy/iis/web-config.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/web-config.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Esra11 ... That is reproducible here. Let's check with the product unit on it ... it may have changed at some point.

@jkotalik ... Publishing defaults to the presence of `hostingModel="inprocess"`, but did the default change if `hostingModel` attribute isn't present? The docs say that `hostingModel` is a optional attribute with a default to `inprocess`, but I can reproduce @Esra11's case where the `hostingModel` is removed (3.1 and 5.0) and out-of-process behavior results (i.e., the `dotnet.exe` process is present).

**Comment by guardrex** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/22766.
