### ISSUE TITLE
Cannot Scaffold movie pages [Part 4].

### ISSUE THREAD

**Issue by nutchyleo** [dotnet/AspNetCore.Docs#22774]
I just followed tutorials to create web apps with .NET 5.0 ( for specific it is v5.0.302)
with Microsoft Visual Studio Community 2019 version Version 16.10.3

but after I use the scaffolding tool to produce Create, Read, Update, and Delete (CRUD) pages for the movie model
by using "Add MVC Controller with views, using Entity Framework" tool in "Add Scaffold dialog"
and followed tutorials  to  complete MVC Controller with views, using Entity Framework dialog , I got this error showing

<img src="https://www.img.in.th/images/19fc483a61fa31ea5f26817ad150e011.png" alt="19fc483a61fa31ea5f26817ad150e011.png" border="0" />
(I thought this error coming from "Microsoft.VisualStudio.Web.CodeGeneration")

any advice to let me pass this step ?
if you need more information please tell me.

==== Code Generation Log ====

Finding the generator 'controller'...
Running the generator 'controller'...
Generating a new DbContext class 'MvcMovie.Data.MvcMovieContext'
Attempting to compile the application in memory with the added DbContext.
There was an error creating a DbContext :(10,19): error CS1001: Identifier expected
(11,6): error CS1513: } expected
(12,44): error CS8124: Tuple must contain at least two elements.
(13,13): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()

(13,27): error CS8124: Tuple must contain at least two elements.   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)

(14,9): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)

(18,5): error CS1022: Type or namespace definition, or end-of-file expected   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

(19,1): error CS1022: Type or namespace definition, or end-of-file expected
G:\Working_Repo\MvcMovie\MvcMovie\Startup.cs(30,13): error CS8389: Omitting the type argument is not allowed in the current context

========================================

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by nutchyleo** [comment]
Code in "MvcMovie.csproj"
==============================

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="5.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="5.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGenerators.Mvc" Version="5.0.2" />
  </ItemGroup>

</Project>

**Comment by nutchyleo** [comment]
Package that installed.

<img src="https://www.img.in.th/images/08b622d2cfc5607598da49dbdaeab7ae.png" alt="08b622d2cfc5607598da49dbdaeab7ae.png" border="0" />

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
What version of .NET and VS?
