### ISSUE TITLE
Missing paths and file-names for DB entities, schema etc.

### ISSUE THREAD

**Issue by Jamiermusic** [dotnet/AspNetCore.Docs#22833]
The shared layout is clearly defined where resides. When the reader progresses to the DB entities and schema, it's not so clear where these should reside within the folder hierarchy. This makes it challenging for beginners to progress.

It would be great if the paths and file names would be added in each of these sections as well.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-5.0#create-the-data-model)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is not a beginning tutorial. Where is path and filename missing?

**Comment by Jamiermusic** [comment]
Thanks for the clarification Rick.
