### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by capesean** [dotnet/AspNetCore.Docs#22843]
The link to download gives a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @capesean ... I'll patch that up right now. In the meantime, you can get the latest release Hosting Bundle installer here (under **ASP.NET Core Runtime 5.0.8** on the right) ...

https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by guardrex** [comment]
@capesean ... I can't repro that. Perhaps, it was just a temporary network failure.

<img width="1129" alt="Capture" src="https://user-images.githubusercontent.com/1622880/126894001-36aa4db4-cfe8-4e3c-944b-f65eabc00133.PNG">

**Comment by capesean** [comment]
I'm still getting it. I thought it might be due to cookies but In Private I still get it.

![image](https://user-images.githubusercontent.com/642609/126907084-ca077598-30ac-4c5e-b9ff-1542747fe557.png)

Maybe a regional redirect (coming from South Africa)?

Separate issue, but installing from the direct link has blown up my development environment - see below.

![image](https://user-images.githubusercontent.com/642609/126907119-cd622abd-7814-4d6c-89f6-56394c484129.png)

I'm probably doing something stoopidly wrong here. All I was trying to do it test if I could publish to a folder for a client to host on their IIS server, as it's currently published to Azure. I kept getting 500.19 errors, seemed to indicate I needed to install the self-hosting module, but now it's all gone to pot. Can you recommend somewhere I can get chat help from - gitter maybe? Rushing to get it installed on client infrastructure...

**Comment by guardrex** [comment]
Let's ask @shirhatti ... ☝️ There might be a regional problem obtaining the Hosting Bundle Installer from the permalink. Do you want to dig deeper here or move this issue?

**Comment by capesean** [comment]
Ok, I went back to the page and it seems to work for me now. Not sure why, but I'd close this off as I'm sure you've got more important issues to worry about. (Sorry, not sure why I was getting that 404)

**Comment by guardrex** [comment]
No worries, @capesean ... probably just a glitch in **_the Matrix_**.&copy; :smile:

![end-smith](https://user-images.githubusercontent.com/1622880/126910586-a2b99f28-c426-40ef-9599-2de60416a42e.jpg)
Agent Smith ([Hugo Weaving](https://www.imdb.com/name/nm0915989/?ref_=tt_cl_t_4)) &copy;1999 [Warner Brothers Entertainment, Inc.](https://www.warnerbros.com/movies/matrix)
