### ISSUE TITLE
(Get started with ASP.NET Core MVC tutorial) Refreshing page does not reflect changes

### ISSUE THREAD

**Issue by davidwinter** [dotnet/AspNetCore.Docs#22857]
When following this tutorial on macOS, with ASP.NET Core 5 and Visual Studio Code, running without debug mode does not allow you to edit files, and then refresh the browser to see changes. When testing this myself, I made a change to a view template and updated some static text. I needed to restart the server to see changes.

```
Launching the app without debugging by selecting Ctrl+F5 allows you to:

* Make code changes.
* Save the file.
* Quickly refresh the browser and see the code changes.
```

Is it still expected behaviour to be able to edit a file, refresh browser and see the reflected change, without needing to restart the server?

```
dotnet --version
5.0.302
```

Running on macOS Big Sur with Visual Studio Code 1.58.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc 
Launching the app without debugging

**Comment by Rick-Anderson** [comment]
You're using kestrel, right?

**Comment by davidwinter** [comment]
> You're using kestrel, right?

Is there a way I can tell? I installed the .NET SDK, and then followed the instructions for the ASP.NET Core MVC tutorial.

**Comment by Rick-Anderson** [comment]
VS uses IIS Express, VS Code uses Krestel

**Comment by davidwinter** [comment]
I'm using Visual Studio Code for macOS, version 1.58.2

**Comment by Rick-Anderson** [comment]
try `dotnet run` in a command window. What does the command window show?

**Comment by davidwinter** [comment]
```
dotnet run
Building...
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/davidwinter/projects/MvcMovie
```

**Comment by davidwinter** [comment]
Also seeing the same on Ubuntu too - running without debugging, and editing a view template file, saving, and reloading the page in Firefox, results in no change.

**Comment by davidwinter** [comment]
Also, just wanted to confirm that if I manually run `dotnet watch run` in the terminal, then file changes are reflected and auto-refreshed, on both macOS and Linux systems I'm trying this on.

It's just in the tutorial documentation, it sounds like it should also do this with CTRL + F5, in which case, it isn't for me.

**Comment by davidwinter** [comment]
@Rick-Anderson should I recreate this issue, as I'm aware that it is currently closed - unless you could reopen it? Thanks.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
