### ISSUE TITLE
"Place extension methods in the Microsoft.Extensions.DependencyInjection namespace to encapsulate groups of service registrations." ??

### ISSUE THREAD

**Issue by StingyJack** [dotnet/AspNetCore.Docs#22862]
Why would we put any of our code in a Microsoft namespace?  What is the value in doing that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#combining-service-collection)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
convention

**Comment by davidfowl** [comment]
That's right. They show up in intellisense automagically as more components are referenced

**Comment by StingyJack** [comment]
> convention

> That's right. They show up in intellisense automagically as more components are referenced

By the convention you are advocating, it sounds like you would expect me to put any extension method I have for `System.String` into the `System` namespace so that intellisense can find it. TBH this advice is strange enough that it feels like you are having a laugh at my expense (which is fine if you need it, just dont take it too far).

Intellisense finds the extension methods no matter where I tend to put them. "My" code belongs in "my" namespaces so it can be located or identified correctly.

**Comment by davidfowl** [comment]
I think in reality the IServiceCollection and the IApplicationBuilder aren't as pervasive as string 🙃. So you're argument while valid doesn't apply here. Also it's guidance but if you feel strongly about your component you can ignore it. It's something that all of the built in components do and something we will continue to do.

**Comment by StingyJack** [comment]
> So you're argument 

My argument what?🤔

Autocorrect fun aside, your guidance here (to all users, not just MSFT ones) is to break long standing convention and guidance regarding namespaces. Do you know how many people that don't work at MSFT will blindly follow this and the arguments that will be had over it? And the reasons proponents will be giving is that intellisense performs better this way, and that it's Best Practice to do this. 

Unfortunately, Im a veteran participant of that kind of discussion and would really like to avoid getting into another one when the reasoning is dubious or debunked. Is there some other reason this guidance exists and why it applies to non- MSFT organizations?

**Comment by Rick-Anderson** [comment]
> Do you know how many people that don't work at MSFT will blindly follow this and the arguments that will be had over it? 

The issue is open, I'll update the doc.  It hasn't been a problem until now :)

**Comment by davidfowl** [comment]
Your slippery slope comparison to string. The fact remains that we already did this and continue to do it.

**Comment by StingyJack** [comment]
> It hasn't been a problem until now :)

Because you arent doing code reviews for people who are convinced they are doing the right thing by sticking our company's code in a Microsoft namespace because it helps intellisense performance (which If thats really true, then you have a design problem with intellisense because its penalizing the most common use case - far from a slippery slope). It not fun having                                                                                        

You probably also havent had someone review your code and demand things like the `SuppressMessageAttributes` be removed from source not because it using it was even questionable, but because the docs page says it will cause performance issues at runtime (even though its not present in the compiled output).  The silent changing of when to suffix Async on a function name was another recent point of dispute created by documentation issues,  

> The fact remains that we already did this and continue to do it.

Go ahead then. You are Microsoft. It makes sense for you to use the Microsoft (or System) namespaces.  For everyone else, it's advice that has no benefit to users and implies there is.

**Comment by StingyJack** [comment]
@davidfowl - did you really what you said about using a Microsoft.* namespace rather than my own, intellisense performance improves?

**Comment by davidfowl** [comment]
There are a couple of key types and namespaces where we put extension methods. So no, it's not Microsoft.*, it's Microsoft.Extensions.DependencyInjection for IServiceCollection extension methods, Microsoft.AspNetCore.Builder for IApplicationBuilder and Microsoft.AspNetCore.Routing for IEndpointRouterBuilder.

I dunno if that answers your question, I couldn't parse it.

**Comment by StingyJack** [comment]
> That's right. They show up in intellisense automagically as more components are referenced

This is the statement I'm working from, also interpreted as "if i dont use those namespaces my extension methods wont be automagically showing up via intellisense".   The observable evidence makes that statement incorrect because I see my extensions showing up in intellisense suggestions without any noticeable difference from Microsoft or System ones. 

If you are part of Microsoft and making these extension methods, then using those guidelines makes sense but only because thats where your namepsace is already going to be scoped. If you are not part of Microsoft there is no reason to be following this guidance and it conflicts with the [best practice for namespace naming](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces). This guidance document targets everyone, not just Microsoft.

> I dunno if that answers your question, I couldn't parse it.

Words are hard sometimes. especially when the brain gets ahead of the fingers and misses words.  Editied to add the words in.

**Comment by davidfowl** [comment]
I think we both expressed our points of view, I'm not sure what else is left to discuss.

**Comment by StingyJack** [comment]
@davidfowl - I still dont know why you said that using these namespaces makes intellisense automagically work. Its one of two reasons given so far and its just not true- intellisense is going to work for these automagically in whatever namespace they exist in.

The other reason given was "convention", but there is no convention for putting my application's code in another company's namespace.  It would be as strange as if you started putting the controller classes for your next asp.net core app in a namespace called `Google.Controllers`.

Guidance without reason is only personal preference, and personal preferences do not does not belong in documents like this.

**Comment by davidfowl** [comment]
This will be my last reply to this thread so I'll be specific and pedantic to make sure its clear:

> @davidfowl - I still dont know why you said that using these namespaces makes intellisense automagically work. Its one of two reasons given so far and its just not true- intellisense is going to work for these automagically in whatever namespace they exist in.

When you're using `IServiceCollection`, `IApplicationBuilder` and `IEndpointRouteBuilder` you already have the namespaces Microsoft.Extensions.DependencyInjection, Microsoft.AspNetCore.Builder and Microsoft.AspNetCore.Routing imported in the file. If you were to create a package that has extension methods [e.g.](https://github.com/abpframework/abp/blob/7488b929ba80c8535591a7be0fed15390ca11915/framework/src/Volo.Abp.MemoryDb/Microsoft/Extensions/DependencyInjection/AbpMemoryDbServiceCollectionExtensions.cs#L10), it would show up in the intellisense as an extension method on those types with no further work from the user.

Hopefully that clarifies things and I'm not going to respond to this thread anymore, again, thanks for the discussion.

**Comment by StingyJack** [comment]
@davidfowl - yes. thank you. _Only in libraries_ would this be considered, not classes that are part of the hosting **app**lication.  

@Rick-Anderson can the docs differentiate the scenarios and not say things like
 > We recommended that **apps** ...
