### ISSUE TITLE
hide reconnection element

### ISSUE THREAD

**Issue by Bartmax** [dotnet/AspNetCore.Docs#22876]
```
    window.addEventListener('beforeunload', function () {
      Blazor.defaultReconnectionHandler._reconnectionDisplay = {};
    });
```

having that on `beforeunload` as suggested on the guide doesn't work. 

this does work:
```
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
    Blazor.defaultReconnectionHandler._reconnectionDisplay = {};
    Blazor.start();
</script>
```

Not sure why the idea of having on `beforeunload` event, doesn't make any sense to me, blazor is already available, if we can call start we can update the `_reconnectionDisplay` property. I may be missing something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6613df5d-3ca6-d744-a46a-67fd113bc3eb
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-3.1&pivots=server#reflect-the-connection-state-in-the-ui)
* Content Source: [aspnetcore/3.1/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/3.1/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@BrennanConroy ... Should the event be removed from the example?

```javascript
window.addEventListener('beforeunload', function () {
  ...
});
```

... leaving ...

```html
<script src="_framework/blazor.server.js" autostart="false"></script>
<script>
    Blazor.defaultReconnectionHandler._reconnectionDisplay = {};
    Blazor.start();
</script>
```

... as @Bartmax suggested?

**Comment by BrennanConroy** [comment]
@javiercn

**Comment by Bartmax** [comment]
I think there is something else going on. I'll investigate and reopen if needed. sorry.
