### ISSUE TITLE
API analyzers only apply to Web projects, not libraries

### ISSUE THREAD

**Issue by eatdrinksleepcode** [dotnet/AspNetCore.Docs#22879]
Please document that the analyzers and the procedure on this page only apply to web projects. If you are breaking up your web project into libraries for modularity (by using `<Project Sdk="Microsoft.NET.Sdk">` and `<FrameworkReference Include="Microsoft.AspNetCore.App" />`), the analyzers are not available in those libraries.

This was previously reported at #15327, but that issue was closed with no resolution.

See also:
dotnet/aspnetcore#14675
dotnet/sdk#3706

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by wadepickett** [comment]
Expanded scenario to mention likely as a note.  I tagged as doc-enhancement.
