### ISSUE TITLE
The type or namespace name 'IHttpClientFactory' could not be found 

### ISSUE THREAD

**Issue by wbehning** [dotnet/AspNetCore.Docs#22889]
I have a new templated Blazor Web Application, .net 5.0, 

I followed this verbatim.  I get a compiler error: The type or namespace name 'IHttpClientFactory' could not be found (are you missing a using directive or an assembly reference?)		

How do I fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d89dd2c-e365-d67a-b635-0050c5c37158
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API in an ASP.NET Core Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0&pivots=server)
* Content Source: [aspnetcore/5.0/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/5.0/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the `System.Net.Http` namespace. Which hosting model are you adopting, WASM or Server? Which file are you receiving that error for?

**Comment by guardrex** [comment]
@wbehning ... I'm going to close. I think the app is just missing the package reference, which is called out in the section at https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0&pivots=webassembly#named-httpclient-with-ihttpclientfactory. If that's not the case (e.g., it threw for content earlier in the topic) or this is a Blazor Server app problem, ping me back here. I'll re-open for further discussion, and please provide full details on the hosting model and how/where you're consuming the doc ... which section(s) ... what were you implementing exactly.
