### ISSUE TITLE
Delete, Edit, and Details pages throw 404

### ISSUE THREAD

**Issue by mark311fl** [dotnet/AspNetCore.Docs#22896]
Hi,

The title just about says it all. I'm at the end of Part 2; create and index pages run fine, but the other three throw 404s. Any idea why?

Thank you.

Mark

**Comment by guardrex** [comment]
@mark311fl ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
