### ISSUE TITLE
DefaultAzureCredential does not work for managed identity access to Key Vault secret manager

### ISSUE THREAD

**Issue by aw230012** [dotnet/AspNetCore.Docs#22902]
The document on this page is incorrect. When using DefaultAzureCredential() for Managed Identities, the Managed Identity Client ID is required and should be passed in a DefaultAzureCredentialOptions object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  when you do this topic, maybe test this and we can ping the PU with problems.

**Comment by serpent5** [comment]
I think this is dupe of #23004. I've tested using `DefaultAzureCredential` with a system-assigned identity, and it works well. I think the ID is needed only for user-assigned identities, as described in the issue I just linked.
