### ISSUE TITLE
Following the steps show YSoD

### ISSUE THREAD

**Issue by FarhanIqbal2003** [dotnet/AspNetCore.Docs#22900]
After updating the code as the steps mentioned, code display following error message:
An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Welcome' was not found. The following locations were searched:
/Views/HelloWorld/Welcome.cshtml
/Views/Shared/Welcome.cshtml

Note that, this can be fixed, by updating following line:
return View();
with 
return View("Index");
inside Welcome method of HelloWorldController.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Great error message should help with what you did wrong.
