### ISSUE TITLE
download link broken

### ISSUE THREAD

**Issue by jimmybbb** [dotnet/AspNetCore.Docs#22905]
the download link is broken

 "View or download sample code" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae88427b-2c3c-9acc-ded2-cfaa4ebb8261
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0#feedback)
* Content Source: [aspnetcore/5.0/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/5.0/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Thanks for the report @jimmybbb, and I'm sorry for the broken link. The sample is here ...

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/5.0/blazor/samples/BlazorServerEFCoreSample

It just moved to a new location yesterday, and I didn't get the link updated. I'll do that right now.

**Comment by guardrex** [comment]
**_Yikes!!!_** :smile: ... I just found three more for the SignalR-Blazor tutorial. Make that estimate on going live 15 **_more minutes_** ... I'll put another PR in.  The move to a new docs versioning system required juggling about ten balls in the air to get it implemented. Thanks again for calling these **_sneaky links_** 😈 out.
