### ISSUE TITLE
Include Aspnet User Claims in Jwt token

### ISSUE THREAD

**Issue by danzfairs** [dotnet/AspNetCore.Docs#22904]
This could use more info on how to use claims to secure different parts of the api.  I added a rule that requires an Admin claim, but the jwt token that is generated when a user logs in does not have any of the claims in it.  I have added the claim to the aspnetUserClaims table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Moved to Container issue: Authentication and authorization for SPAs #16406
