### ISSUE TITLE
Microsoft.Dotnet-OpenApi How to integrate nswag.json ?

### ISSUE THREAD

**Issue by jkone27** [dotnet/AspNetCore.Docs#22920]
Hello, is not really clear how to use this feature or to configure all NSwag available options.

https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-5.0

Could more information be added onto that page?

for example, seeing this, it's not clear how for example to interop with all available nswag options, and which options are availabe at all?

https://cezarypiatek.github.io/post/auto-generated-web-api-client/

The docs for this resource/page are very limited considering the amount of options (e.g. on nullability or many others) the developers would need to know, and NSwag docs are also not very easy/self-explanatory

Cheers,
Giacomo

**Comment by guardrex** [comment]
Hello @jkone27 ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to cross-link the topic to your issue and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
