### ISSUE TITLE
SignalR tutorial 404: Failed to negotiate with the server

### ISSUE THREAD

**Issue by berrigo2** [dotnet/AspNetCore.Docs#22921]
Using VS Community 2019 16.10.4

Followed the tutorial as instructed and everything worked great until the "Run the App", I get the following when I run without debugging:

Error: Failed to complete negotiation with the server: Error
Error: Failed to start the connection: Error

Various articles online point to using the HTTPTransportLayer property in SignalR to change the .withUrl line to a websocket transport, but trying this has not solved it either. Seems like an error that I really shouldn't be getting in a tutorial :/

I don't see any way to attach my project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Can you show your network trace and any server logs?

Also, double check you have the endpoint configured correctly
server:
```
endpoints.MapHub<ChatHub>("/chatHub");
```

client:
```
var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();
```

**Comment by berrigo2** [comment]
This did fix it, thank you
