### ISSUE TITLE
Is the AddDirectoryBrowser optional when using directory browsing? 

### ISSUE THREAD

**Issue by Dillion132** [dotnet/AspNetCore.Docs#22925]
[Enter feedback here]

When use the Directory browsing, if we are not adding the `AddDirectoryBrowser` in `Startup.ConfigureServices`, the `app.UseDirectoryBrowser` or the `app.UseFileServer()` method (the `EnableDirectoryBrowsing` property value is true) also works well. But in the document, it said "`AddDirectoryBrowser` must be called when the EnableDirectoryBrowsing property value is true."

So, is AddDirectoryBrowser optional when using directory browsing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#serve-files-from-multiple-locations)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wanttoh** [comment]
In asp.net core3.1 or 5 or 2.1, the same issue take place. But [the document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#directory-browsing) said **AddDirectoryBrowser inStartup.ConfigureServices**  is needed.

![image](https://user-images.githubusercontent.com/33505944/129174896-89092cf0-1191-4fe0-aa5b-413ec2eca9c9.png)

**Comment by Dillion132** [comment]
Hi @Rick-Anderson Can you tell me which info I should provide? I just create a new Asp.net core Application using the Asp.net Core Web App template, then refer [the document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#directory-browsing) to enable Directory browsing. And then, just adding the following code in the Configure method, without adding the `services.AddDirectoryBrowser();` in the ConfigureServices method.

```
    app.UseDirectoryBrowser(new DirectoryBrowserOptions
    {
        FileProvider = new PhysicalFileProvider(
            Path.Combine(env.WebRootPath, "images")),
        RequestPath = "/MyImages"
    });
```

Then, you can see the Directory browsing works well. So, is the AddDirectoryBrowser optional?

**Comment by wanttoh** [comment]
Hi Team, is  is there any update? Pls kindly show us your requirement for more details if needed. Thanks for your reply in advance.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
