### ISSUE TITLE
Directory Browsing Considerations link issue

### ISSUE THREAD

**Issue by Dillion132** [dotnet/AspNetCore.Docs#22926]
[Enter feedback here]

From Asp.net core 3.0, when we view the [Directory Browsing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#directory-browsing), and click the `Considerations` link, the page url will change to `https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-3.0#considerations`, but the page will not move to the considerations part.

If we change the version to Asp.net core 2.2 and lower version, when we click the `Considerations` link, the page URL will change to "https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2#considerations", and the page will navigate to the Considerations part. 

The screenshot as below:

![119836-8.gif][1]

  [1]: https://i.stack.imgur.com/0jjpO.gif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#additional-resources)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Dillion132 ... It's just a broken internal link. I'll patch it up right now. Thanks for the report.
