### ISSUE TITLE
Default settings for `ForwardedHeadersMiddleware` are not described correctly

### ISSUE THREAD

**Issue by nenadvicentic** [dotnet/AspNetCore.Docs#22928]
The way `default settings` are currently described is a bit confusing, because it's easy to assume that default settings are actually forwarding headers `X-Forwarded-For` and `X-Forwarded-Proto`.

It should be explicitly stated that default `ForwardedHeaders` values is `ForwardedHeaders.None` - so that it's clear that defaults need to be modified in order for *any* forwarder functionality to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in #22930
@nenadvicentic  thanks for bringing this to our attention.
