### ISSUE TITLE
The information presented on this page is almost useless

### ISSUE THREAD

**Issue by KirkMunroSagent** [dotnet/AspNetCore.Docs#22948]
Of course you support the latest version of each of the major web browsers.

What is not obvious is what downlevel versions of web browsers are supported. Each of the major web browsers releases a new version every time you turn a corner, and if you look at web browser usage statistics, consumers obviously are not keeping up with browser updates.

Please consider putting more effort into the information presented here so that customers who are evaluating Blazor WASM as a front-end technology can properly assess what browsers (and versions!) can be expected to work should they adopt Blazor WASM for their front end technology.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63759755-cf32-b97c-bd29-4715db83f3fd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-5.0)
* Content Source: [aspnetcore/5.0/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/5.0/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KirkMunroSagent ... We've had this discussion a few times.

> Each of the major web browsers releases a new version every time you turn a corner, and if you look at web browser usage statistics, consumers obviously are not keeping up with browser updates.

That's exactly right ... and also exactly the problem for Blazor. Only the latest (i.e., the current release) is **officially** supported because MS can't keep up with rapidly-rolled-out browser versions over time and make an **official** commitment to patch Blazor for any particular prior browser release. They consider bug reports for resolution for prior releases on a case-by-case basis reported them on the product unit's repo.

> what downlevel versions of web browsers are supported

"**_None_**" is the official answer, which is what this page indicates. You'll find the same for SignalR ...

https://docs.microsoft.com/aspnet/core/signalr/supported-platforms

I asked the last time this subject came up about adding some text to explain the reasoning, but management declined. They might reconsider if more devs write in asking, so we'll keep an 👂 open for more feedback.

**Comment by KirkMunroSagent** [comment]
Thanks for the fast reply @guardrex.

From a business perspective, I understand, but the communication is wrong.

The only value in saying "current" is in telling customers that Microsoft will officially support all updates to each of the major browsers that are supported (Edge, Chrome, Firefox and Safari), but in that case, that's exactly what the support docs should day, because that is what Microsoft is saying.

The existing wording doesn't convey the same message, and indicates that Microsoft isn't testing with recent browser releases at all. That's simply untrue, because by the simple nature of software development taking time and Blazor WASM having a long release cycle (tied to the .NET release cadence), you're naturally passing through multiple versions of each of the major browsers since they release more frequently than Blazor does. i.e., Blazor ships its next major update as part of the November 11, 2021 release of .NET 6. At that point in time, whatever "current" versions will be supported. Then as that version of Blazor remains supported over time (36 months since it is an LTS release), many updates will ship for each of those browsers, with each of those updates becoming the current version, which will be supported by Blazor. Patches released during that time will very likely (but not necessarily, I get that) work on these updated versions.

Also, for what it's worth, other front-end technologies such as Angular and Vue declare browser support more broadly than "current", although Angular isn't much better (last two versions).

My personal perspective: declaring browser support based on date rather than version (e.g., releases in the last 6 months) does not feel like a stretch for offering _official_ support, especially considering the release cadence of Blazor. That's barely saying more than "current", since you're obviously working with these versions as mentioned above, and it offers your customers more value than you are currently offering with "Current" today.

**Comment by guardrex** [comment]
Management declined to provide more or different coverage ... i.e., anything along the lines of the example text that I floated to them. This is exactly what they want to say. You'll have to make your adoption decision on that basis.
