### ISSUE TITLE
Update gRPC tutorial for .NET 6 dynamic port

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#22945]
In .NET 6 the gRPC server template will have a dynamic port (i.e. it will no longer always be 5001)

The gRPC tutorial needs to take that into account when writing the client. The developer will need to use the server port when writing the address in the client.

**Comment by davidfowl** [comment]
I would wait on this

**Comment by JamesNK** [comment]
Wait until the templates with the dynamic template are released? Yes, this should happen with .NET 6 RC1.

**Comment by davidfowl** [comment]
No it seems we've possibly broken the spa templates as well (I'm not sure yet).

**Comment by wadepickett** [comment]
Fixed by #25397 
Didn't see this issue at the time, linking and closing now.
