### ISSUE TITLE
Please clarify your JavaScript client support

### ISSUE THREAD

**Issue by KirkMunroSagent** [dotnet/AspNetCore.Docs#22949]
Apparently, the Blazor WASM support page only lists "Current" the supported version for each of the major browsers because they are dependent on the support information on this page.

This page indicates that the client runs on NodeJS 8 (which passed the end-of-life date at the end of 2019) and later versions, yet only indicates current for browsers that release a new version every time that you turn the corner. How can you declare support for something that is end-of-life already without putting in some effort to identify version support in major browsers?

By avoiding testing support in/declaring support for different browser versions, you are making life much more difficult for customers who are trying to understand what they can expect when it comes to browser support with modern technologies like ASP.NET Core SignalR and Blazor WASM.

Please consider the impact that this has on customers before they even start building consumer web applications with these technologies. Microsoft must have some idea what versions of each of these browsers are supported beyond "Current", so why aren't you sharing that information with us?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Answered at https://github.com/dotnet/AspNetCore.Docs/issues/22948#issuecomment-892651960.
