### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by jkone27** [dotnet/AspNetCore.Docs#22947]
Hello, is not really clear how to use this feature or to configure all NSwag available options.

https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-5.0

Could more information be added onto that page?

for example, seeing this, it's not clear how for example to interop with all available nswag options, and which options are availabe at all?

https://cezarypiatek.github.io/post/auto-generated-web-api-client/

The docs for this resource/page are very limited considering the amount of options (e.g. on nullability or many others) the developers would need to know, and NSwag docs are also not very easy/self-explanatory

Cheers,
Giacomo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by ryanbrandenburg** [comment]
CC @mkArtakMSFT who will know who the current area expert is now that I've moved teams.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
