### ISSUE TITLE
Incorrect variable value assignment

### ISSUE THREAD

**Issue by AntoninJarolim** [dotnet/AspNetCore.Docs#22946]
In this section
[](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#use-claims-to-customize-identity-handling)

`var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email };`
should be 
`var user = new ApplicationUser { UserName = Input.UserName, Email = Input.Email };
`
![obrázek_2021-08-04_130953](https://user-images.githubusercontent.com/60815963/128171097-dbc33889-eb79-43e9-afc4-88307e1bdd9b.png)

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @AntoninJarolim ... It's correct. The email address is being used as the username in this example.
