### ISSUE TITLE
Dotnet-grpc documentation doesn't state if dotnet 6 is supported (doesn't appear to be)

### ISSUE THREAD

**Issue by clarkezone** [dotnet/AspNetCore.Docs#22955]
[Enter feedback here]
Attempted to use this tool with dotnet 6 and doesn't appear to be working.  Would be good for docs to list which versions work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a7d945-e49f-d76f-a5fd-43ac81dbef80
* Version Independent ID: b5b132db-9667-d5a9-8671-002cb2c0277f
* Content: [Manage Protobuf references with dotnet-grpc](https://docs.microsoft.com/en-us/aspnet/core/grpc/dotnet-grpc?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/dotnet-grpc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/dotnet-grpc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
It works in .NET 6. What was the problem you encountered?

@JamesNK  are there .NET 6 preview limitations?

**Comment by clarkezone** [comment]
Are you testing on nightlys or on the most recent preview?

**Comment by Rick-Anderson** [comment]
Knightlys don't get the most rigorous testing

**Comment by davidfowl** [comment]
It's supported.

cc @JamesNK
