### ISSUE TITLE
Syntax error in code example

### ISSUE THREAD

**Issue by hackmods** [dotnet/AspNetCore.Docs#22952]
In the Rerun validation section of the documentation, the following example code line needs a right bracket removed.

I believe this line:
ModelState.ClearValidationState(nameof(Movie)));

Needs to be updated to:
ModelState.ClearValidationState(nameof(Movie));

Thanks for all the great work you do!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hackmods great catch!
