### ISSUE TITLE
Missing nuget package

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [dotnet/AspNetCore.Docs#22954]
There is no indication in the documentation that this package is also needed:

    Microsoft.NET.Test.Sdk

Without it the following error appears:

    CSC  : error  CS5001: Program does not contain a static 'Main' method suitable for an entry point

And if you add one the error changes to:

    Unable to find <Path-to-your-project>\testhost.dll. Please publish your test project and retry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Thanks @carlosmunozrodriguez for pointing this out!  Much appreciated and sorry for the bad experience in the doc.   The doc you pointed to was for version  .NET SDK 3.1.  Just so I have more info to work with, were you working with .NET 5.x SDK and using the 3.1 instructions or with .NET SDK 3.1?

**Comment by carlosmunozrodriguez** [comment]
I am using this `global.json`

```
{
  "sdk": {
    "version": "3.1.411"
  }
}
```

**Comment by guardrex** [comment]
I don't think it's required. Are you starting from the test project, @carlosmunozrodriguez? ...

https://github.com/dotnet/AspNetCore.Docs/issues/7095#issuecomment-400418391

... and compare to the sample app, which doesn't reference that package ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/RazorPagesProject.Tests.csproj

**Comment by carlosmunozrodriguez** [comment]
The behavior appears when updating `xunit.runner.visualstudio` to 2.4.3 (latest so far)

    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

Probably because of `PrivateAssets` and/or  `IncludeAssets`

According to [xUnit documentation](https://xunit.net/docs/getting-started/netcore/cmdline) the line

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />

Is required

**Comment by guardrex** [comment]
Thanks for the additional detail, @carlosmunozrodriguez.

@Rick-Anderson ... I'll take a look in the morning.
