### ISSUE TITLE
grpcurl syntax for json in screenshot is incorrect

### ISSUE THREAD

**Issue by clarkezone** [dotnet/AspNetCore.Docs#22974]
The screenshot showing invoking grpcurl using a json payload no longer works with the most recent versions.. the need to escape the " character is no longer there (on the mac at least).  It should be this:

grpcurl -d '{ "name": "world" }' --plaintext localhost:5000 greet.Greeter/SayHello 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b505f0f-8312-90a1-c143-23d4fc7fbaf4
* Version Independent ID: 771cd7a3-e343-1f85-8c8a-a65eeb2dc2ab
* Content: [Test gRPC services with gRPCurl in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/test-tools?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/test-tools.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/test-tools.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
PowerShell has different escaping rules compared to the console you are using.

**Comment by Rick-Anderson** [comment]
> The screenshot showing invoking grpcurl using a json payload no longer works with the most recent versions.. the need to escape the " character is no longer there (on the mac at least).

No longer needed implies it's OK to use it. Is that not the case?

 It should be this:
> 
> grpcurl -d '{ "name": "world" }' --plaintext localhost:5000 greet.Greeter/SayHello

How about adding

Depending on the console used, you may need to escape the `"` character.

**Comment by clarkezone** [comment]
Something like that would be helpful
