### ISSUE TITLE
Not compatible screen

### ISSUE THREAD

**Issue by juskuz** [dotnet/AspNetCore.Docs#22998]
First screen (in 'Add a view' paragraph) seems not to be compatible with description above (Razor View).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you using 2.1? That's the 2.1 page. 2.1 will soon be out of support.

**Comment by juskuz** [comment]
I haven't noticed it is tutorial for older version (I'm begginer in Web
apps and .NET). (It worked for me so I didn't check)

I have installed .NET Core 3.1.
I'm not sure where to find this info in my project (if in .csproj file then
TargetFramework is set as netcoreapp3.1). In 'Frameworks' in project files
tree there is 'Microsoft.AspNetCore.App' too (and here the version is
3.1.10).




śr., 11.08.2021, 18:58 użytkownik Rick Anderson ***@***.***>
napisał:
