### ISSUE TITLE
Missing details on requiring client id for managed identity

### ISSUE THREAD

**Issue by KallDrexx** [dotnet/AspNetCore.Docs#23004]
In the managed identity section it shows the following code snippet:

```
                var secretClient = new SecretClient(
                    new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
                    new DefaultAzureCredential());
                config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
```

However, when attempting to use this in a function deployed to Azure this failed with a 400 bad request failure.  After much searching I came across this issue: 

https://github.com/Azure/azure-sdk-for-net/issues/11400#issuecomment-620179175

This indicates that by design this isn't enough, that you must specify the client id of the managed identity, either through a not well documented `AZURE_CLIENT_ID` app setting, or via `new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = "<your client id>" });`.

Both of these issues fixed my problem, and it would be helpful if this was added to the documentation so the doc's suggestions work out of the box.

*Edit:* Specifically it would be useful if its called out that extra steps are needed for user assigned identities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KallDrexx  thanks for bringing this to our attention. Can you provide the complete snippet and I'll get his updated ASAP.

**Comment by KallDrexx** [comment]
Not a problem!

What type of snippet are you looking for.  In our code we fixed it by setting the `AZURE_CLIENT_ID`  configuration setting on the Azure function itself.  This had the added benefit of working out of the box with the snippet above for local development purposes (as `DefaultAzureCredential` seems to be picking up my local azure authentication properly).  

The only reason this wouldn't work is if you need multiple user assignable identities for different purposes and thus can't rely on a global `AZURE_CLIENT_ID`, in which case you'd have to do 

```
var secretClient = new SecretClient(
    new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
    new DefaultAzureCredential
    (
        new DefaultAzureCredentialOptions
        {
            ManagedIdentityClientId = "<client id>",
        }
    ));

    config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
```

For simplicity sake, just calling out the `AZURE_CLIENT_ID` portion is probably enough with a quick link if a more complicated manner is needed.  

I'm not a good tech writer though, so I don't know the exact wording that's best for the doc :)

**Comment by Rick-Anderson** [comment]
@KallDrexx  fantastic, I'll take it from here.

**Comment by MPapst** [comment]
Before adding this to the documentation - shouldn't be clarified, why it is working sometimes without adding the ClientId and why it is sometimes necessary to add the ClientId?

**Comment by KallDrexx** [comment]
Yeah the documentation should definitely reflect that this is only needed when using user assigned identities, and the example works as expected without it for system assigned identities.
