### ISSUE TITLE
Blazor WASM "Dynamically set the culture from the Accept-Language header" not working as described

### ISSUE THREAD

**Issue by craigbrown** [dotnet/AspNetCore.Docs#23010]
This issue is about the "Blazor WebAssembly" version of the article.

I'm in the UK so my computer and browser settings are all `en-GB`. The section titled "Dynamically set the culture from the Accept-Language header" implies that this all I need - as long as my browser settings are `en-GB`, I should get GB date formats.

But when I run the Demonstration Component provided in the article, I see the following:
<img width="510" alt="Screenshot 2021-08-12 at 16 02 14" src="https://user-images.githubusercontent.com/8934235/129221801-da7ba9ec-9152-443b-8759-116649048f62.png">
These appear to be `en-US` date formats.

When I add the `BlazorWebAssemblyLoadAllGlobalizationData` tag to my csproj, I see the correct date formats:
<img width="465" alt="Screenshot 2021-08-12 at 16 02 19" src="https://user-images.githubusercontent.com/8934235/129222126-f34f2862-e37e-4cea-b490-a1da434b9634.png">

The article implies I should only need to add this tag if I want to load a different culture or change the current culture at runtime. But apparently I also need to add it when I just want to rely on the Accept-Language header.

So my question is - is this a gap in the documentation or a bug with Blazor WebAssembly? I'm using .NET 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0&pivots=webassembly#blazor-webassembly)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @craigbrown ... I'll take a look as soon as I can. I'm 🏃😅 on some 6.0 stuff at the moment, but I should be able to look within 24 hours.

In the meantime tho, can you check for me ...

**_NOT_** setting :x: `BlazorWebAssemblyLoadAllGlobalizationData` :x: in the project file, what do you get for `es-CL`? Does that match the date format that the topic shows for Chilean Spanish? ...

* Date: 7/6/2021 6:49:38
* Number: 1.999,69

**Comment by guardrex** [comment]
Indeed, I'll need to research this further. I had a report of this here :point_right: https://github.com/dotnet/AspNetCore.Docs/issues/21619 ...

> Once you scratch your head a little why you see en-GB, for example, but the dates are formatted according to the en-US format it will become apparent that this is a dynamic change from the app perspective

... and I made a large UE pass that enhanced the coverage considerbly.

This subject was under discussion on the PR at ...

https://github.com/dotnet/AspNetCore.Docs/pull/22525#issuecomment-866012270

... and testing seemed at the time to not require it if only using the header ...

https://github.com/dotnet/AspNetCore.Docs/pull/22525#issuecomment-869065611

... but I didn't base that on a working knowledge of the deep internal framework code or special knowledge. I'm not a loc guru, so I based it on testing only. I wouldn't be surprised if I **_DO_** need to move that property setting into the header section.

I'll get to this soon ... perhaps Friday morning ... or this weekend ... and work further on it. Thanks for the report.

**Comment by guardrex** [comment]
I'll cc: @hishamco, who helps us quite a bit on loc scenarios.

@hishamco ... TL;DR ... it looks like in my testing for updates to the Blazor loc topic that `BlazorWebAssemblyLoadAllGlobalizationData` wasn't required for automatic globalization of dates with the `Accept-Language` header, but the report here is that for `en-GB` the date format isn't correct without that setting when relying solely on the `Accept-Language` header. I'll do some research on it and report back here within a few days. I'm just letting you know about this right now.

**Comment by craigbrown** [comment]
Thanks for getting back so quickly @guardrex. 

I can confirm that removing the `BlazorWebAssemblyLoadAllGlobalizationData` setting from csproj, and changing the `accept-language` header to `es-CL`, _does_ show the same format that the document shows - correct day/month order, 24hr time, comma decimal separator. But not for `en-GB`.

I tried a few other locales and compared them to what I got using plain .NET 5 without Blazor:
```
Locale    Plain .NET 5                         Blazor (no glob load)           match?
en-US     M/d/yyyy h:mm:ss tt                  M/d/yyyy h:mm:ss tt             ✅
en-GB     dd/MM/yyyy HH:mm:ss                  M/d/yyyy h:mm:ss tt             ❌
en-AU     d/M/yyyy h:mm:ss tt                  M/d/yyyy h:mm:ss tt             ❌
en-NZ     d/MM/yyyy h:mm:ss tt                 M/d/yyyy h:mm:ss tt             ❌
en-CA     yyyy-MM-dd h:mm:ss tt                M/d/yyyy h:mm:ss tt             ❌
fr-FR     dd/MM/yyyy HH:mm:ss                  dd/MM/yyyy HH:mm:ss             ✅
fr-CA     yyyy-MM-dd HH 'h' mm 'min' ss 's'    dd/MM/yyyy HH:mm:ss             ❌
es-ES     d/M/yyyy H:mm:ss                     d/M/yyyy H:mm:ss                ✅
es-CL     dd-MM-yyyy HH:mm:ss                  d/M/yyyy H:mm:ss                ❌
es-MX     dd/MM/yyyy H:mm:ss                   d/M/yyyy H:mm:ss                ❌
```

And with the `BlazorWebAssemblyLoadAllGlobalizationData` setting included in the csproj file:

```
Locale    Plain .NET 5                         Blazor (w glob load)                 match?
en-US     M/d/yyyy h:mm:ss tt                  M/d/yyyy h:mm:ss tt                  ✅
en-GB     dd/MM/yyyy HH:mm:ss                  dd/MM/yyyy HH:mm:ss                  ✅
en-AU     d/M/yyyy h:mm:ss tt                  d/M/yyyy h:mm:ss tt                  ✅
en-NZ     d/MM/yyyy h:mm:ss tt                 d/MM/yyyy h:mm:ss tt                 ✅
en-CA     yyyy-MM-dd h:mm:ss tt                yyyy-MM-dd h:mm:ss tt                ✅
fr-FR     dd/MM/yyyy HH:mm:ss                  dd/MM/yyyy HH:mm:ss                  ✅
fr-CA     yyyy-MM-dd HH 'h' mm 'min' ss 's'    yyyy-MM-dd HH 'h' mm 'min' ss 's'    ✅
es-ES     d/M/yyyy H:mm:ss                     d/M/yyyy H:mm:ss                     ✅
es-CL     dd-MM-yyyy HH:mm:ss                  d/M/yyyy H:mm:ss                     ❌
es-MX     dd/MM/yyyy H:mm:ss                   dd/MM/yyyy H:mm:ss                   ✅
```

Interestingly, the `es-CL` format is the only one that doesn't match regular .NET 5 when the globalization data is loaded.
Without the globalization data loaded it looks like there's only one format per language, regardless of the region. I've only looked at three languages though so maybe that's not true for all of them.

So, assuming this isn't a bug, it seems like the `BlazorWebAssemblyLoadAllGlobalizationData` tag is required. But it would be interesting to know if this is expected behaviour or a bug.

Thanks

**Comment by guardrex** [comment]
Excellent ... thanks for going to all of that trouble @craigbrown. I agree ... I'll move that remark into the section; or given that it's going to be a scenario requirement for every section, I'll pull it out to the top of the doc and make it more like a prerequisite.

@hishamco ... Let me know you feel that would be the wrong direction.
