### ISSUE TITLE
calling class constructor in a record?

### ISSUE THREAD

**Issue by mshwf** [dotnet/AspNetCore.Docs#23015]
Please explain this code, is it a trimmed version of legit code?

```
public class Person(string Name)

public record Person([Required] string Name, [Range(0, 100)] int Age)
{
   public Person(string Name) : this (Name, 0);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors

**Comment by mshwf** [comment]
I've constructed millions of objects already in the last 5 years :D
What I don't understand is this line:
`public class Person(string Name)`
is it part of a class definition that is not presented?

and its relation to the record below it (which has the same name!):
```
public record Person([Required] string Name, [Range(0, 100)] int Age)
{
   public Person(string Name) : this (Name, 0);
}
```
