### ISSUE TITLE
Can't run blank, newly created Blazor WASM app with ASP.Net Hosting and Individual Authentication

### ISSUE THREAD

**Issue by Cmohan** [dotnet/AspNetCore.Docs#23026]
I have created multiple Blazor WASM apps with ASP.NET hosting and Individual Authentication from the base template, but none of them run upon initial creation. I always get the following error:

![image](https://user-images.githubusercontent.com/2027643/129402228-bae0e3f5-4eea-4a6f-a595-11a30024f9d8.png)

It doesn't happen with Standalone Blazor WASM apps with Individual Authentication and it doesn't happen with Blazor WASM apps with ASP.NET Hosting and NO authentication. Just when both are used.

As far as I can tell, my Visual Studio is up to date, .NET SDKs too. The Client project is created fine and exists in the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#additional-resources-1)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Cmohan ... I haven't seen anything like this reported. Open this for the product unit for investigation at ...

https://github.com/dotnet/aspnetcore/issues

... and please add a `cc: @guardrex` to the bottom of your opening comment so that I can follow along.

**Comment by Cmohan** [comment]
Thank you, here is the new Issue link: https://github.com/dotnet/aspnetcore/issues/35337
