### ISSUE TITLE
[Required] on non-nullable reference types has some weird differences from the actual Required attribute.

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/AspNetCore.Docs#23034]
This is an opinion.

I feel like once you know you will get a `[Required]` attribute on your non-nullable reference types, unless disabled by `services.AddControllers(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true);`, you expect as a developer to get the full package of what `[Required]` has to offer.

Currently, `[Required]` not only checks if a field is null, but it also checks if the type is string - to not be an empty string, or string filled with only white spaces. But, it seems `[Required]` is only applied in the following situations for non-nullable reference types _(Accentuations are mine)_:

> If the app was built with <Nullable>enable</Nullable>, a **missing value** for Name in a JSON or form post results in a validation error. Use a nullable reference type to allow null or missing values to be specified for the Name property: ([source](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#non-nullable-reference-types-and-required-attribute))

But then when you explicitly define a `null` value to a non-nullable field in a JSON payload, you still get an error, unless "missing value" here refers to strictly missing "any value other than `null`", and not what `[Required]` is supposed to do.

These ambiguities are really confusing:

- Is `[Required]` applied to any non-nullable reference type? If yes: Why is the behavior entirely different from the actual `[Required]` attribute? For example, If you define an empty string to a non-nullable string, no error occurs, and yet if you really had the `[Required]` attribute on a string, you would get an error.

- Is `[Required]` applied only to fields not explicitly given a value? If yes: Why then do we get an error when we explicitly define a `null` value to them?

I hope this made sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-5.0#required-attribute)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> to not be an empty string, or string filled with only white spaces
Where does it say that?

**Comment by SpiritBob** [comment]
> > to not be an empty string, or string filled with only white spaces
> > Where does it say that?

That is what `[Required]` does.

**Comment by Rick-Anderson** [comment]
@serpent5  please review

**Comment by serpent5** [comment]
The [source](https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsMetadataProvider.cs#L405-L413) shows that the `AllowEmptyStrings` property is set to `true` for the _inferred_ `[Required]`, as @SpiritBob suggests:

```csharp
// Since this behavior specifically relates to non-null-ness, we will use the non-default
// option to tolerate empty/whitespace strings. empty/whitespace INPUT will still result in
// a validation error by default because we convert empty/whitespace strings to null
// unless you say otherwise.
requiredAttribute = new RequiredAttribute()
{
    AllowEmptyStrings = true,
};

attributes.Add(requiredAttribute);
```

I'm not sure what the comment means by "empty/whitespace INPUT", but I'll try and find some time over the next few days to dig into it a bit more.

**Comment by SpiritBob** [comment]
> The [source](https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Mvc/Mvc.DataAnnotations/src/DataAnnotationsMetadataProvider.cs#L405-L413) shows that the `AllowEmptyStrings` property is set to `true` for the _inferred_ `[Required]`, as @SpiritBob suggests:
> 
> ```cs
> // Since this behavior specifically relates to non-null-ness, we will use the non-default
> // option to tolerate empty/whitespace strings. empty/whitespace INPUT will still result in
> // a validation error by default because we convert empty/whitespace strings to null
> // unless you say otherwise.
> requiredAttribute = new RequiredAttribute()
> {
>     AllowEmptyStrings = true,
> };
> 
> attributes.Add(requiredAttribute);
> ```
> 
> I'm not sure what the comment means by "empty/whitespace INPUT", but I'll try and find some time over the next few days to dig into it a bit more.
> 
> I think it's talking about this logic ([source](https://github.com/dotnet/aspnetcore/blob/release/5.0/src/Mvc/Mvc.Core/src/ModelBinding/Binders/SimpleTypeModelBinder.cs#L70-L74)):
> 
> ```cs
> // Already have a string. No further conversion required but handle ConvertEmptyStringToNull.
> if (bindingContext.ModelMetadata.ConvertEmptyStringToNull && string.IsNullOrWhiteSpace(value))
> {
>     model = null;
> }
> ```
> 
> From what I can see there, the standard non-JSON model-binding will convert such strings to `null`, but I don't see that the JSON input-formatter will do the same thing.

Perhaps it's referring to the following [DataAnnotation attribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayformatattribute.convertemptystringtonull?view=net-5.0), or is this an entirely separate logic?

Personally, I've never had this encounter of ASP.NET Core automatically converting empty strings/strings filled with white-spaces to `null`.

**Comment by SpiritBob** [comment]
@serpent5 I've gone ahead and created a PR that could somehow clear the ambiguity present in the documentation. If you've got any better ideas on how we can tackle this, please feel free to scream at me!
