### ISSUE TITLE
URL typo on the "Part 2, add a model to a Razor Pages app in ASP.NET Core" page

### ISSUE THREAD

**Issue by coxantohi** [dotnet/AspNetCore.Docs#23036]
On the [Part 2, add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio) page, inside the [Test the app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio#test-the-app) section item 1 has the following phrase:
> Run the app and append `/Movies` to the URL in the browser (`http://localhost:port/movies`).

I find that the url has an extras *s*, so `/Movie` and `http://localhost:port/movie` are the correct references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It plural, see the next section. How did you scaffold the pages.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/129586539-c6d80f6e-9c99-439f-b9fd-5921c43a1e26.png)

**Comment by coxantohi** [comment]
Hi. Sorry, it was my mistake. I think I typed _Movie_ instead of _Movies_ when creating the Pages subfolder. The instructions that I did not observe were under the [Scaffold the movie model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio#scaffold-the-movie-model) section

> 1. Create a *Pages/Movies* folder:
>    a. Right-click on the *Pages* folder > **Add** > **New Folder**.
>    b. Name the folder *Movies*.

Thanks for the quick reply.
