### ISSUE TITLE
Fed up withy GitHub, unable to download any of these ASP.NET Sample code

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#23043]
---
**Issue moved from MicrosoftDocs/feedback#3672**
- Please respond to @Johnvan.

---

_From @Johnvan on Saturday, August 7, 2021 5:55:34 AM_

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3672**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Saturday, August 7, 2021 5:55:36 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3672**
- Please respond to @gewarren.

---

_From @gewarren on Monday, August 9, 2021 9:10:03 PM_

@Johnvan Can you provide a link to the page you were trying to download sample code from?

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3672**
- Please respond to @Johnvan.

---

_From @Johnvan on Wednesday, August 11, 2021 7:39:06 AM_

I was doing a step by step procedure by Microsoft, where in the old days I would click on their link to download, with no problems, their example code.
But now when I click that link I get sent to GitHub where, as far as I can see, there is no way, even when logging in, to download the files. In fact the files don’t seem to have anything to do with my subject.
The URL is as follows:
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50
It is all so confusing, he subject is correct “RazorPageMovie50” but the files !!!!!. and there is no way of downloading anything.
Kind regards,

John van der Linden
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3672**
- Please respond to @gewarren.

---

_From @gewarren on Monday, August 16, 2021 6:52:34 PM_

@wadepickett Could you take a look at this feedback?

**Comment by gewarren** [comment]
It looks like this is (one of?) the docs page with the download link: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
@Johnvan that's how GitHub works. The links show where the code is in GitHub, but you cannot download just that folder. You need to download the entire repo.

**Comment by Johnvan** [comment]
The **how to download** page is just as confusing, I have downloaded the zip file and had a look but what do I do now. There is nothing there that is obvious to me. That is what I mean, the whole system you use is very very confusing and even the comments here are just as confusing and lack any description.

**Comment by Johnvan** [comment]
I have loaded the GitHub Desktop program and am still just stuck, no help and any help I find does not address my problem.

**Comment by Johnvan** [comment]
The address was addressed in the previous email and is :
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie50
Please don’t ask this question again, it makes me think you are not reading my posts, but brushing me off.

John van der Linden
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
