### ISSUE TITLE
Localization shared resources cs file should be able to live outside of root 

### ISSUE THREAD

**Issue by Ponant** [dotnet/AspNetCore.Docs#23051]
I used to have a website with .Net Core 2.0 that had the cs SharedResources.cs and associated resx files all under a custom folder "Myresources", and it worked well. Now it seems that the cs file needs to be moved out of the "MyResources" folder and put in the root, see this PR https://github.com/dotnet/AspNetCore.Docs/pull/19905 .
To me this causes two issues:
1) Documentation should be updated and it is yet not clear what should be done (I lost a day on that)
2) Link to the issues below and coordinate with the sdk team (?)
3) Imposing the user to put the shared resource file at the root of the folder is a loss of flexibility and not so tidy in my opinion; it was better before

I still do not understand what is going on, eventhough I made it work following the PR above.

Related issues for coordination
https://github.com/dotnet/aspnetcore/issues/12412
https://github.com/dotnet/aspnetcore/issues/17960
https://github.com/dotnet/docs/issues/16964

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review

**Comment by Ponant** [comment]
For example one could add  to the doc how to circumvent the breaking change, by adding this to the csproj
```
	<PropertyGroup>
		<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
	</PropertyGroup>
```

In this way the cs and resx resource file can live in "MyResources".

**Comment by Ponant** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.0#resource-manifest-file-name-change

**Comment by hishamco** [comment]
> Now it seems that the cs file needs to be moved out of the "MyResources" folder and put in the root

You mean the `SharedResource.cs`? It's just a marker, please share a minimal repo if you have any issue

**Comment by Ponant** [comment]
@hishamco , yes I mean the SharedResources.cs file. I know it is a marker but you cannot put it in the resources folder, "MyResources" in my exampe case, and this is a loss with respect to previous versions. This is why you made the PR linked above. The only solution is to modify the csproj file. If you take the sample project and move the file to the Resources folder then you would see the problem. My point was to improve the docs explainng this change since 3.0 and I provided above the links where this is discussed.

**Comment by hishamco** [comment]
I will check this one if I got time in `netcore5.0`

**Comment by hishamco** [comment]
> I know it is a marker but you cannot put it in the resources folder, "MyResources" in my example case, and this is a loss with respect to previous versions

Are you sure it's working in the previous versions?

**Comment by hishamco** [comment]
BTW the `SharedResources` should be in the default namespace - even if you move it into another folder -

**Comment by Ponant** [comment]
@hishamco, yes it is wokring in 2.0 . And yes I am using the root namespace regardless of in which folder I put it....

**Comment by ryanbrandenburg** [comment]
@hishamco I no longer work in the localization area. @mkArtakMSFT should be able to direct you to the folks currently working on localization.

**Comment by hishamco** [comment]
You are one of the very old localization friends that I knew ;)

Thanks

**Comment by Rick-Anderson** [comment]
See [Serve files from multiple locations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#serve-files-from-multiple-locations)
