### ISSUE TITLE
Is RegisterConfirmation now ConfirmEmail?

### ISSUE THREAD

**Issue by bildzeitung** [dotnet/AspNetCore.Docs#23050]
Working through the tutorial and to the point where the overrides for the Identity pages are selected and there doesn't appear to be a "Account\RegisterConfirmation" page. There *does* seem to be a ConfirmEmail page -- is this what's meant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authentication/identity/sample/WebApp5x 
you might be right. I know it changed for 5.0 but I though we fixed the tutorial.

**Comment by bildzeitung** [comment]
Oh hey! Thanks for the triage!

The current page text that I see[1] is this: 
```
Add the Register, Login, LogOut, and RegisterConfirmation files. Follow the Scaffold identity into a Razor project with authorization instructions to generate the code shown in this section.
```
[1] https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio

It then follows with a section on "Disable default account verification" that I suspect may also be different in v5.0.

**Comment by Rick-Anderson** [comment]
It's there
<img width="597" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/213848aa-3639-4ff1-9018-4a5876289abd">
