### ISSUE TITLE
Improve and update Localization docs and samples

### ISSUE THREAD

**Issue by Ponant** [dotnet/AspNetCore.Docs#23062]
I may suggest to drastically improve the localization docs.
I am happy to help, but I would like not to go through all versions of .Net Core, and rather focus on .Net 6.
I could do a video on youtube or wherever if that is acceptable on the site.
The strategy would be to first do the video and if you like it we transform it to text.
You can check out my tuto skills here https://www.youtube.com/watch?v=n5DI3VDtvAQ , and feel free to complain :)!
I have a better microphone.

Background: I worked on Localization in the past, so I knew it, but after 2-3 years I came back to Localization for a new project and somewhat needed a refresher. So I went back to the docs and found them somewhat dismanteled and not so in line with typical docs on asp.net core. It is a very confusing experience, going back and forth through the main page. I am sorry for this negative feedback.
 
Here is some feedback:
**Sample**
-The startup does not need to register `RequestLocalizationOptions`  twice, once in services and once in app builder, see here https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization/sample/3.x/Localization/Startup.cs
-Update to Razor Pages or put in some sentence in the docs. For example I figured out on my own that I could do it, for example by using IndexModel as a type for `IStringLocalizer`. It was not difficult to guess but I believe if it was there in the docs, it would have been better

**Main docs**
In typical docs in this repo, the usage is to go straight with a basic configuration, i.e. AddLocalization, Configure `RequestLocalizationOptions`, `UseRequestLocalization`.

1. Then run and observe via the query string how a date is displayed in a different culture (no need for resx files at this stage).
2. Experience with fallbacks through the providers (Query, cookie and accept header)
3. Then move on to add resx files, by highlighting IStringLocalizer, IHtmlLocalizer, IViewLocalizer, data annotations
4. In that respect I find it important to mention that you can use IStringLocalizer in views and stick with that only. The other two are for html based strings
5. Then cookie
6. Then of course go to higher levels by tweaking the providers and mentionning the factory
7. etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Ponant  and update for .NET 6 would be great.  You could do a video, but we're found non-English speakers don't like video's in English, they like documentation.  The updates need to be in this doc.

**Comment by Ponant** [comment]
@Rick-Anderson , for .Net 6, do I need to use the same document structure? Because personally, I would re-order sections.

**Comment by Rick-Anderson** [comment]
I think your suggestion works better. Please provide a more complete outline.

**Comment by Rick-Anderson** [comment]
@Ponant I prepared the MD file for V6. See https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md and the raw version.

**Comment by Ponant** [comment]
OK @Rick-Anderson , so I guess I first submit in this issue a more precise template, namely sections and they will do and in which order they appear. And once you give a green light I modify the md file and put a sample in a 6.x folder. Correct?

**Comment by Rick-Anderson** [comment]
> OK @Rick-Anderson , so I guess I first submit in this issue a more precise template, namely sections and what they will do and in which order they appear. And once you give a green light I modify the md file and put a sample in a 6.x folder. Correct?

That's correct. Thanks for the help.

**Comment by Ponant** [comment]
Hi @Rick-Anderson ,
Here is what I could come with without going into code and full explanations. I believe you should be able to grasp the structure and intent.

Currently, the Overview contains almost all, which is too much in my view. Also, it seems a few stuff could go to extensibility. Also there are small details, such as the use of an async on a sync return method (the custom provider) and "Notes" which could be better placed.

Ideally, I would recommend to split the Overview to form a document tree, with sections, subsections and subsubsection, and a left panel, but I am also ok with one big page.

Below, when I mention "title is optional" it means that the content flows in the preceding section, without breaking the lecture with another title. This is easier for the user to learn from top to bottom, see below. It also removes the need to introduce sub-sub-sections. But not having sub-sub-sections makes it difficult for a returning user. For example, if the user wants to see what is the value of the query string, he could jump directly to the sub-sub-section where that is discussed.

-----------------------------------------------------------------------------------------------------

### Globalization and localization terms (section)

Mostly kept as is and merged with current intro (some shortening will occur). CultureInfo is mentioned here, which is needed for what follows.

### ASP.NET Core's non-localized behavior (section)

Understanding how to localize an ASP.NET Core application starts with understanding the CurrentCulture and CurrentUICulture, dates and formats.

- 	Start with a new .Net 6 project
- 	Briefly recall the CultureInfo object, and to access the CultureInfo object in all views, add a @using System.Globalization in _ViewImports.cshtml
- 	Display CurrentCulture and CurrentUICulture, dates and a 6-digit currency number in the index.cshtml View
- 	Discuss results, namely why the CultureInfo returns en-GB (because I am running windows 10 in en-GB display language and format). The user will be instructed to take notice of which locale appears for him/her. Change the regional format to French and observe how culture is changed, dates and numbers are changed, but not the UI culture. Pictures shown throughout. To change the latter, the user will have to change the display language of the OS, logout and login anew on Windows 10.
- 	The paragraph ends by stating that we set back the regional format in the OS as it was, i.e. en-GB in our case

### ASP.NET Core's localized behavior (section)

Briefly explain that a full localization is done in two main steps, each of which addresses different parts of the API. Step 1 is the use of the AddRequestLocalization and Step 2 is AddLocalization with the localizers and their resx’s. Addressing in this way is important to see the separation of concerns, and to see how far one can get without resx’s

**Part I: Configure and control the Cultures and UICultures to be used (subsection)** 

- 	To control the culture and ui-culture to be displayed in the browser, we start by injecting the AddRequestLocalization (not AddLocalization) service as well as the request localization middleware
- 	We chose on purpose to set as cultures and uicultures fr-FR and it-IT in the service, not en or en-* such that there is a distinction with respect to the default culture info gotten from the first section.
- 	We recommend the user to follow a similar approach for learning/testing, i.e. if he/she has an Italian OS, then he/she would set the cultures to fr-fr and en-us, for example. This also assumes that the browser is not configured for fr-FR and it-IT.

       
**The Query String Request Culture Provider (subsubsection, title is optional)**

- 	Once we run, the user will see en-GB, because we did not set a default culture. Here we play with the query string to display in French and Italian. We also display all languages registered
- 	Make the remark that, in general, it is important to be specific with which culture we are dealing. For example, prefer fr-FR or fr-CA (for canada) rather than the generic fr. The latter indeed will lead, for instance to numbers without currency when using ToString(“c”), as done in code, because fr is a parent culture of many French cultures. However, putting in fr is also a good idea for a fallback. So we show that by doing so, someone querying fr-ca will fall back to fr, so that he can read dates and numbers, but not the currency
- 	Modify the code to set as default language de-DE, and run again. Now the displayed information is in German by default, and no more en-GB. This is good because we gain control.
- 	Mention now that the query string provider is the first in the list of RequestCultureProviders, how can we get that via the Features in the HttpContext, and we display the list in the index page, which introduces the cookie and request header providers
-  	We mention how to customize the query string provider, by e.g. changing the query strings culture and uiculture to lang and uilang, so that https://localhost:5001/?lang=fr-fr returns something
- 	We next remove the querystring provider from the list to see that the query string method is not working. 


**The Accept Language Header Request Culture Provider (subsubsection, title is optional)**

We set the browser to accept a new language, es-ES, in addition to en-GB, and we add es-ES in the service. Again, the user will be recommended to use a language he knows he does not have on his machine. Now we see that, when run, the language displayed is es-ES and not the default de-DE (or en-GB if no default was set). This is the role of the header request provider, it found es-ES so skips the default. We remove this provider, arguing that in common usage one should avoid relying on this provider, so that we are left with the cookie provider, and back to the default, German.  

**The Cookie Request Culture Provider  (subsubsection, title is optional)**

- 	Here we set the cookie request provider. For this we clear all providers, set a new Cookie request provider, and set the cookie name to  .Contoso.Culture 
- 	We make use of the MakeCookie method in a new language page, which displays the cultures and which is accessible from a partial view. This part actually makes use of all what has been discussed before. For example the used culture is displayed as a nav-link by using the http features.

**Part II: Localize the content (subsection)**

- 	This part will take large parts of what is already in the docs, but adapted to Razor Pages because we started with that. MVC will be mentioned when need be. It will have subsections (guessable from the bullet points below)
- 	We now make use of AddLocalization with a MyResources folder and explain that this extension will inject IStringLocalizer and the accompanying factory as well as the resource manager
- 	We introduce the SharedResources with notes on the breaking change from MSBuild since 3.0
- 	We show how far we can go without AddViewLocalization and AddDataAnnotationLocalization, and then show these
- 	The section on resource files could be simplified
- 	We mention the conventions for naming the resx’s
- 	We check culture fallback, as we did already from fr-CA to fr

-----------------------------------------------------------------------------------------------------

Custom provider section and Model binding route data and query strings go to **Extensibility** (left panel)

**Comment by Rick-Anderson** [comment]
@Ponant  fantastic outline. A few comments:

On sub-sub sections. I think titles are best, you  `## section title`  `### sub-section section title`   `#### sub-sub-section section title` You can go with `###### if needed, but that shouldn't be necessary. Having titles gives you in page links which are useful.

Only H2's ( `## section title`  ) show up in the right side table. See https://github.com/dotnet/AspNetCore.Docs/pull/23068/files where I added an H3 today.  [Data Protection and app isolation](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0#data-protection-and-app-isolation) is the link, but it doesn't show up on the right side.

![image](https://user-images.githubusercontent.com/3605364/130303367-a5a0975d-b02b-4c99-a203-e3afeca7cdcb.png)

> with "Core", since .Net 6 is not named Core anymore.

Where .NET 6 is the correct framework, use .NET 6 and remove Core. Where it's ASP.NET Core specific, obviously keep Core.

**Comment by Ponant** [comment]
Should I draft the md?

**Comment by Ponant** [comment]
BTW, how do you preview the md file, with the pictures and code? I never found a way.

**Comment by Rick-Anderson** [comment]
> BTW, how do you preview the md file, with the code, pictures and Notes? The Preview button does not show a "live" version.

https://github.com/dotnet/AspNetCore.Docs/blob/main/CONTRIBUTING.md

## Docs Authoring Pack extension in Visual Studio Code

If you use Visual Studio Code to contribute to the ASP.NET documentation, you can boost your productivity by installing the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) extension. The extension provides a variety of tools that helps with Markdown linting, code spell checking, and article templates.

@guardrex uses this approach, hopefully he can help if you get stuck

**Comment by Rick-Anderson** [comment]
> Should I draft the md?

Yes, create a draft PR

**Comment by guardrex** [comment]
Building locally with DocFX helps, too. The latest stable release is at ...

https://github.com/dotnet/docfx/releases/tag/v2.58

1. Put the `docfx.exe` on your PATH.
1. Set GH Desktop to your working branch.
1. Open a console and change the directory to the `aspnetcore` directory, which is where the `docfx.json` file is located.
1. The command ... IIRC 🤔 ... is just ...

   ```console
   docfx --serve
   ```

1. It will build and put the output (that you can browse) of your branch at ...

   http://localhost:8080/group1-dest/

The build process shows any suggestions/warnings. You may see some (e.g., Xamarin repo cross-links for code snippets) that you can ignore. Your suggestions/warnings indicate the file and line number ...... er .... *most of the time!* 😝

**Comment by Rick-Anderson** [comment]
@guardrex  will correct me if I'm wrong, but you'll have access to the build errors on server when you push. Those error messages are more important.

**Comment by Ponant** [comment]
OK I guess I will have a heart attack if I install docfx and so on, for now., so I will skip the @guardex method :)
I already started and I am doing it the old way, check every line and so on. let's see!

Visual studio Community, a pity it hasn't this kind of stuff, but it gives some formatting for my md. I am on 2022 so I could not install an extension from Mads.

In addition to the sample I have pictures which I believe will go to the _static folder.
I am almost done with part I, which I plan to finish tonight.

Will keep you posted.

**Comment by Rick-Anderson** [comment]
>

> I already started and I am doing it the old way, check every line and so on. let's see!

No problem. Once you push I'll share the built HTML with you.
If we coordinate, you can tell me when I can make changes to fix problems. Then you can pull. We have to coordinate to prevent merge conflicts. I'll avoid making changes but sometimes that can speed things up because then I can get a clean build and provide you the HTML to review.

**Comment by Ponant** [comment]
OK sorry for that limitation, I carry on for now on and will popup here anew.

**Comment by Ponant** [comment]
As we say in French, my first attempt is a "sans faute" :). Just a bunch of spelling which I will go through 👍 
Part I is done, will clean tomorrow.

**Comment by guardrex** [comment]
> you'll have access to the build errors on server when you push

Unless you use DocFX locally ... it does build the docs locally and gives you all of the warnings and build errors ... same set as if you push to the repo. That's why I use it ... and to see them locally :eyes: rendered in a browser ... layouts, tables, lists, etc.

**Comment by Ponant** [comment]
Hi,
I would like to point to links, such as https://docs.microsoft.com/en-us/dotnet/core/extensions/create-resource-files ,
Ahould I put the link in this way

 [Resource files](/dotnet/core/extensions/create-resource-files)

or by putting in the full url?

**Comment by Rick-Anderson** [comment]
`Resource files](/dotnet/core/extensions/create-resource-files)`
is correct

**Comment by Ponant** [comment]
As such the link does not work in preview (404), so I guess it works once live?

**Comment by guardrex** [comment]
It's relative to `https://docs.microsoft.com/` after going live.

**Comment by Ponant** [comment]
Does Visual Studio Code allow one to create a resx in a way similar to Visual Studio, Add->New Item-->resx?

**Comment by Rick-Anderson** [comment]
> Does Visual Studio Code allow one to create a resx in a way similar to Visual Studio, Add->New Item-->resx?

I don't know of an extension that does. That's why #2501 is open.

**Comment by Ponant** [comment]
I think it will be usefull to have a Json equivalent of resx, at least for strings, optimized and maintained. It seems from the link that people are struggling. Creating and editing a resx by hand without a viewer is not so fancy.

I am on IViewlocalizer and will then polish.

**Comment by Ponant** [comment]
@guardrex , I am not sure what you mean. To me we just need a key/value pair storage file and JSON does that. What I was suggesting is to wire up localizers such as IStringLocalizer and IViewLocalizer to JSON instead of calling up resx's.
If you suggest people to use JSON to store their text instead of resx, I believe everyone will go for that.

**Comment by Ponant** [comment]
take for instance this from the repo

```
internal static void AddLocalizationServices(IServiceCollection services)
        {
            services.TryAddSingleton<IStringLocalizerFactory, ResourceManagerStringLocalizerFactory>();
            services.TryAddTransient(typeof(IStringLocalizer<>), typeof(StringLocalizer<>));
        }
```

I did not dig into such implementations, but I am wondering if the concrete imeplementations `ResourceManagerStringLocalizerFactory` and `StringLocalizer` can understand JSON without too much re-writting, or if they are too wired to the resx format. If so, maybe you could offer that to users.

**Comment by Ponant** [comment]
I was not talking about the docs, but about the api.

**Comment by guardrex** [comment]
I thought so ... it wouldn't be a supported scenario for .NET loc (i.e., it wouldn't be supported by the PU as a built-in approach for loc). I guess it could be a *nice to show/have* thing for docs, but that would commit the docs to supporting it going forward. Anyway ... it's up to management. I'm just asking a question because I was just curious if JSON support was (or will be) a formal .NET feature ... and the answer is *not apparently* ........ *yet*. :smile:

**Comment by Rick-Anderson** [comment]
> If you suggest people to use JSON to store their text instead of resx, I believe everyone will go for that.

You can ask for that in #2501

**Comment by Ponant** [comment]
Already did, a few days agoo actually 🥇

**Comment by Ponant** [comment]
Can you quickly advise on how to make localization work with the SubFolder option in Razor Pages
`        .AddViewLocalization(LanguageViewLocationExpanderFormat.SubFolder);
`
I just cannot make it work. It is not mentionned in the docs, so I will skip it unless you can come up with a guidance.

**Comment by Ponant** [comment]
I did, for the RazorPages
Pages
    de-DE
        Index.cshtml

Then for the resources, I tried

MyResources
    de-DE
        Index.resx

I also tried 
MyResources
    de-DE
        IndexModel.resx

and

MyResources
        Index.de-DE.resx

and

MyResources
        IndexModel.de-DE.resx

**Comment by Ponant** [comment]
Actually, ViewLocalizer does not seem to work in Razor Pages. No problem with IStringLocalizer. Will check further.

**Comment by Rick-Anderson** [comment]
`services.AddLocalization(options => options.ResourcesPath = "MyResourcesPath");`

See [Localisation in ASP.NET Core Razor Pages - Cultures](https://www.mikesdotnetting.com/article/345/localisation-in-asp-net-core-razor-pages-cultures)

**Comment by Ponant** [comment]
@Rick-Anderson , sure this is done already, I will check the link though.

**Comment by Rick-Anderson** [comment]
> See [Localisation in ASP.NET Core Razor Pages - Cultures](https://www.mikesdotnetting.com/article/345/localisation-in-asp-net-core-razor-pages-cultures)

Mikes page is all Razor Pages.

**Comment by Ponant** [comment]
@Rick-Anderson , my apologies, ViewLocalizer works without issues on RP. Only bug that remains is how to use the SubFolder convention. 

Mikes tuto is pretty old but he mentions aother tutos so I will cross-check.
What remains is the SubFolder convention. Google is scarce on that.

**Comment by Ponant** [comment]
OK I abandon the LanguageViewLocationExpanderFormat.SubFolder . 
I am not sure it is compatible with RP.

**Comment by Rick-Anderson** [comment]
> OK I abandon the LanguageViewLocationExpanderFormat.SubFolder .
> I am not sure it is compatible with RP.

I think everything that works for MVC works for RP (Razor Pages). @hishamco can you confirm that?

**Comment by Ponant** [comment]
I would like to believe that. Here is my resources folder structture for the docs. If anyone could say how to structure it when using `SubFolder`.

![solutionexplorerprivacy3](https://user-images.githubusercontent.com/19961806/130688366-214360dc-3bde-48b0-a59f-e25b92fc1051.png)
![solutionexplorerprivacy](https://user-images.githubusercontent.com/19961806/130688371-341bcd50-be88-4a98-ae99-c2298ba60295.png)
![solutionexplorerprivacy2](https://user-images.githubusercontent.com/19961806/130688373-9912be30-cc0c-4c1e-9dde-eb08ab63097a.png)

**Comment by Ponant** [comment]
I remember I used `SubFolder` once in the past, but it was for MVC.

**Comment by Ponant** [comment]
@Rick-Anderson , in passing Mike's docs are great (as usual) but he skips ViewLocalizer and uses IStringLocalizer extensively via shared resources. I used a lot shared resources and the StringLocalizer for the docs, too, but I present it in a different way.

**Comment by Rick-Anderson** [comment]
@Ponant  I think you'll just have to do what you can get working right now. The team is heads down with the .NET 6 release for several more months. After that we can get some help. @hishamco  has done all the work on this doc for the last few years.

**Comment by hishamco** [comment]
Seems the thread got too long ;) @Ponant could you please summarize what's the issue you are facing

**Comment by Ponant** [comment]
Thank you @hishamco.
I am almost done with the docs. The issue I am facing is the following:
In razor Pages, how would you structure a Razor Page and the resource files when using the SubFolder format:

 `.AddViewLocalization(LanguageViewLocationExpanderFormat.SubFolder);
`
I know that this works in MVC and I tried it a few years ago, however I did some (quick) tests to try to make it work in Razor Pages, without success. If oyu can show me a snapshot like the one above for the solution explorer, for say one resource file and one razor page, I should be able to make it work, and then put it in the docs. Otherwise, I will leave it with the Suffix convention as @Rick-Anderson suggested. Let me know.

**Comment by Ponant** [comment]
@Rick-Anderson , I will be done tonight, most likely (Italy time). I can read it tomorrow calmely and then submit. If I understood you well, I should push but not pull tomorrow when I am ready?

**Comment by Rick-Anderson** [comment]
>  If I understood you well, I should push but not pull tomorrow when I am ready?

After you've pushed and not going to do any work for the next 8 hours, let me know it's OK to push commit. Then I'll tell you when I'm finished. The next day you do a pull to bring in al my commits. If you make changes after you push and I make changes, we'll have merge conflicts to resolve.

**Comment by hishamco** [comment]
@Ponant there are some localization limitation in Razor Pages which I remembered long time ago, anyhow I will try it if I got a time

**Comment by hishamco** [comment]
@Ponant could you plase share a minimal repo so it's easier for me to start with

**Comment by hishamco** [comment]
@Rick-Anderson this might need to be closed too

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
