### ISSUE TITLE
Doesn't show how to prevent over-posting

### ISSUE THREAD

**Issue by Freysi21** [dotnet/AspNetCore.Docs#23066]
It confusing to have header that say how to prevent over-posting and then only explaining this bit
- Hide properties that clients are not supposed to view.
which doesn't really have anything to do with the overpost and just explains DTOs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#over-post)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's overposting. You don't want the secret field set.

**Comment by bbf-007** [comment]
That still doesn't solve the issue. The "Prevent over-posting" section doesn't explain how to:
- Verify you can post and get the secret field.
- Update the TodoItemsController to use TodoItemDTO
- Verify you can't post or get the secret field
