### ISSUE TITLE
Issues with DB Context on migration

### ISSUE THREAD

**Issue by cdort** [dotnet/AspNetCore.Docs#23060]
In working through these steps, I encountered an error about the Context of the migration not being selected. It seems that the current release of VS19 creates multiple DB Contexts and has to be specified in the PackageManager with a -Context %name% switch on the AddMigration -InitialCreate -Context %name% and Update-Database -Context %name%.

Did anyone else see a similar situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, you have multiple DB contexts. That can happen for a variety of reasons. The instructions only generate one context.
