### ISSUE TITLE
Indicate that `[Library Name]` = MSBuild $(PackageId) in the default convention

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#23070]
Relevant discussion here
https://github.com/dotnet/aspnetcore/issues/26055#issuecomment-704848519

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This is already covered ...

https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-5.0&tabs=visual-studio#consume-content-from-a-referenced-rcl-1

... but I see a number of opportunities to improve it. Many locations just remark on the "library name," so I'll make those explicit about the assembly name and indicate that the `PackageId` is used if specified. I'll include a cross-link for that to NuGet docs.
