### ISSUE TITLE
What is the official list of types that Blazor can automatically detect changes in Parameters to avoid re-rendering?

### ISSUE THREAD

**Issue by szalapski** [dotnet/AspNetCore.Docs#23084]
This doc states rerendering will be skipped when "All of the parameter values are of known immutable primitive types, such as int, string, DateTime, and haven't changed since the previous set of parameters were set."

What is the official list of types that Blazor can detect changes in?   I assume double, float, long, short?  All the types that have C# keywords for them?  But then I saw DateTime.  What about enums?  Records?  Any arbitrary struct? Any arbitrary value type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8201d0b-a6c4-7656-a8d9-9ae1fee26d10
* Version Independent ID: 27742f9a-95e5-a2d0-aa54-0ef24cad3d2a
* Content: [ASP.NET Core Blazor component rendering](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/rendering.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@szalapski ... I agree ... and not just for this single location. It should be clarified in the *Components* overview topic where component parameters are first explained. The language is a bit sloppy in perhaps two or three spots around the Blazor docs (`DateTime` struct but in a list of "primitive types"). If the text isn't going to specify types in those locations, it should just say "C# types." However, it should to call out (*somewhere*) types explicitly and/or types not supported (possibly including plans for future support).

*Yes* IIRC for everything on your list, but I'd have to check on `enums` ... I think so tho, and IIRC complex types always trigger rerendering ... the Blazor framework doesn't track if values within a complex type change.

I want to do a 🤠 **_Texas Two-step_** 🕺 on this one. I'll merge a quick PR on Monday just to clean up "primitive type" language in a few spots. Later after 6.0 releases, I'd like to consult with the PU on a permanent fix.

**Notes to self** for when I reach this issue ...

* I wonder if the list of unsupported types is so short that the text can say "C# types" with a &dagger; (dagger) short list that follows to show/explain any caveats.
* A mere improvement to the single sentences on this in the components topic might do the trick. Note that other places that need to specify supported types explicitly do so (e.g., route parameters that support constraints ... there's a table of them, new query string support ... there's an explicit list, etc.).
* Adding a pure reference topic to the end of the *Components* node (just lists of types supported by various Blazor features) or a section within the *Components* node overview topic are possible approaches. 
* If text on types is general in a few spots (e.g., "C# types"), that could cross-link to the types coverage that I'll add or modify in the components topic or elsewhere.

I'll need to wait until after 6.0 GA to engage with the PU on this. They're all crazy super busy right now  🗻⛏️😅 with 6.0 bits. 

Thanks for commenting on this, @szalapski.

**Comment by szalapski** [comment]
Sorry--accidentally closed it.

I am not sure "C# types" would be sufficient, as to me, every type is a C# type.  [Do you mean what this page calls "Simple types"](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#simple-types)?
 
Also, I would hope that Blazor could handle arbitrary enums and records too...but not sure whether it does (that's what brought me here to begin with).

**Comment by guardrex** [comment]
>  every type is a C# type

Yes, that's goal to get out of lengthy explanations in accessory docs to where component parameters (and route parameters) are discussed. Such cases will probably need &dagger; remark(s) or a cross-link to where types are explained out explicitly.

WRT the exact approach, I'll have to come back to this after a quick fix on Monday. I also have high priority 6.0 things that I've been ordered to address by *Vulcan High Command* 🖖😆.

Yes on indications for simple types and their nullable value variants, including DT struct ... and records ... enums (if they work ... and they probably do) ... but not sure what will happen with `string?` ... it might 🎉 or 💥.

My quick fix is just going to be to not imply that a DT is a "primitive type." I'm not sure that I can go further than that at the moment with high priority 6.0 doc work (e.g., MAUI probably needs attention, and we haven't touched it yet ... hot reload, too).

**Comment by mkArtakMSFT** [comment]
@guardrex can you please document the fact that the framework tries to do its best and doesn't offer any guarantees about how the change detection works. It'll be best if you can nicely link to the source code here for more advanced users to find the code: https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ChangeDetection.cs
