### ISSUE TITLE
"Recommended learning path" block 

### ISSUE THREAD

**Issue by Narick9** [dotnet/AspNetCore.Docs#23089]
There is "Recommended learning path" block in the text, but there is also "Next steps" block at the end. The same topic, but different directs. Heh, I think somebody from authors just decided to put his view of things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I don't see the problem.
