### ISSUE TITLE
Its incredibly how bad are documentations

### ISSUE THREAD

**Issue by garsiv1932** [dotnet/AspNetCore.Docs#23087]
## Failing Test(s)

I experience this all the time. I am implementing the SignalR with the oficial documentation.

I installed the libman and the JS libraries, then i iclude the libraries in the cshtml, and finally i copied the configuration js, and in the first line, in the:

var connection = new signalR.HubConnectionBuilder().withUrl("/ranchHub").build();

i got a "cannot find a declaration to go to" in the HubConnectionBuilder() function.

Can you finish a documentation please. All documents looks grate, but when you start implementing it you start seeing that you need to go to google because something is missed.

-

## Error Message

```text

```

## Stacktrace

<details>

```text

```
</details>

## Logs

<details>

```text

```
</details>

**Comment by guardrex** [comment]
@garsiv1932 ... It's best if you open an issue using the **This page** feedback button and form at the bottom of the **English-US** topic. It adds metadata to tell us which topic that you're looking at and it pings the author automatically.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by Rick-Anderson** [comment]
Can you create an issue from the  ***English-US*** topic page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

See [Writing Useful Github Issues](https://upthemes.com/blog/2014/02/writing-useful-github-issues/) and the **What Not To Do** section where it states "Be Courteous. "
