### ISSUE TITLE
Update ASP.NET Core integration tests shadow copying section

### ISSUE THREAD

**Issue by GabrielMajeri** [dotnet/AspNetCore.Docs#23086]
The [instructions](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#disable-shadow-copying) for integration testing with ASP.NET Core recommend disabling shadow copying when using Xunit to run the tests.

However, [this issue](https://github.com/dotnet/runtime/issues/2936) has been closed by https://github.com/dotnet/core-setup/pull/3938, which fixed running the tests with shadow copying enabled.

I'd propose removing or updating the respective section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by GabrielMajeri** [comment]
> Any chance you could PR this? At the top right of the article, select the Edit pen icon:

Sure! Is it alright to completely remove the section, or should I update the wording to indicate it only applies for .NET Core versions older than 2.1?

**Comment by Rick-Anderson** [comment]
Completely remove it. Only 3.1 and higher are supported.
