### ISSUE TITLE
Remove unnecessary SendGridUser field from Identity SendGrid example code

### ISSUE THREAD

**Issue by Webreaper** [dotnet/AspNetCore.Docs#23096]
The SendGrid client API doesn't need (or use) the 'user' field, so including it in the sample code and stored secrets/keys, etc, is just unnecessary and confusing. It should be removed; the only field that's required is the API Key.1

The SendGrid API example demonstrates that only the API key is required: https://app.sendgrid.com/guide/integrate/langs/csharp

If you want to add a second config field, it would make more sense to put the 'from address' into config, as that is directly associated with the API key, and if they don't match, SendGrid will return a 400 response, i.e, change:

```
   From = new EmailAddress("Joe@contoso.com", Options.SendGridUser),
```
to 
```  
    From = new EmailAddress(Options.SendGridFromAddres, "Password Recovery System"),
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Webreaper** [comment]
The SendGrid API example demonstrates that only the API key is required: https://app.sendgrid.com/guide/integrate/langs/csharp

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Maniizzle** [comment]
Hi Rick, Has this been worked on? Can I make a PR with the correction?

**Comment by Webreaper** [comment]
I've not had a chance to do it so be my guest if Rick hasn't either!

**Comment by Rick-Anderson** [comment]
@Maniizzle  yes, a PR would be great.

**Comment by Maniizzle** [comment]
@Rick-Anderson Since we are removing the sendgrid user information. I think only the key would be stored as user secrets as the "FromEmail" is not a confidential information. Right?

**Comment by Rick-Anderson** [comment]
Correct

> the only field that's required is the API Key.
