### ISSUE TITLE
Handling exceptions that can't be caught by middleware

### ISSUE THREAD

**Issue by RRode** [dotnet/AspNetCore.Docs#23101]
Hi! :)

I think that exception handling docs are missing a description of application crashes, which can not be caught by middleware. E.g. uncaught exception in an Task that was not awaited - which is bad code, but can happen. Also thanks for the hard work in building the docs!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Unhandled excepts are not in the scope of **Handle errors***
