### ISSUE TITLE
It doesn't work. Should probably have proofread this

### ISSUE THREAD

**Issue by slindra** [dotnet/AspNetCore.Docs#23116]
[Enter feedback here]

You tell people to create a class named: HelloWorldController

You then tell us how public class names are queryable from the url. 

You say: localhost:port/HelloWorld/ 

will you show you your controller.  

If you can't see the problem in this, you're the wrong person for evaluating this feedback, lol. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
