### ISSUE TITLE
Format response data in ASP.NET Core Web API gives a code sample that only makes sense for MVC

### ISSUE THREAD

**Issue by kcaswick** [dotnet/AspNetCore.Docs#23132]
The code sample for configuring JSON serialization on a per-action basis is not valid in controllers derived from ControllerBase, and will not work if pasted into the .Net 5 sample project linked at the top of the article. I am guessing the intent was to say `return new JsonResult(`, not `return Json(`. The same error appears to be repeated elsewhere in the article.

This code is right above https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-5.0#add-newtonsoftjson-based-json-format-support 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This is fixed in the 6.0 version.
