### ISSUE TITLE
Unclarity about defining Authorization Policies without additional Providers

### ISSUE THREAD

**Issue by marwalsch** [dotnet/AspNetCore.Docs#23131]
When defining policies via funcs, you can specify a scheme and additional assertions:

```

                    services.AddAuthorization(options =>
                    {
                        options.AddPolicy("NegotiateFallback, policy =>
                        {
                            policy.AuthenticationSchemes.Add(CookieAuthenticationDefaults.AuthenticationScheme);
                            policy.RequireAuthenticatedUser();

                            policy.RequireAssertion(context =>
                                context.User.HasClaim(c =>
                                    (c.Type == Claims.Something.Name &&
                                     c.Value == Claims.Something.Value)));
                        });
                    });
```
However, I have a scenario where the authentication scheme to be applied is conditional and I am not sure if and how I could express this through a func.
Thus the preferred way would be to define a method that handles this. I stumbled across `IAuthorizationPolicyProvider`, which appear to be a policy factory for dynamically generated Policies (which I don't need). 
An `AuthorizationHandler `also does not appear to be the way to go as there is no mention of any API that allows checking a specific scheme.

What is the recommended way to concisely define Policy? I am looking for something like:

```
MyPolicy : IAuthorizationPolicy{
     public override Task<bool> AssertSuccessAsync(...){ 
            // initiate certain auth scheme challenges like the following call does
            // policy.AuthenticationSchemes.Add(CookieAuthenticationDefaults.AuthenticationScheme);
     }
}
```

Obviously there would still be a registration required like 

```
services.AddAuthorization(options =>
                    {
                        options.AddPolicy("NegotiateFallback, MyPolicy);
                     {

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by marwalsch** [comment]
It appears if policies are to evaluated disjunctively, the correct way is to register one Requirement with multiple Handlers. Invoking authentication challenges also works through the HttpContext rather than the authorization context.
However I still have not found a way to Define One Policy as an Actual Fallback to another one. It actually appears rather arbitrary which scheme is executed. (for instance, if cookie and Negotiate authentication is available, the middleware goes for Negotiate if no cookie is present, but for the cookie if it is available).

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
