### ISSUE TITLE
Review Blazor Hosting Models topic for trimming

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23145]
Per https://github.com/dotnet/AspNetCore.Docs/pull/23065#discussion_r697629003, review looking for opportunities to shorten and sharpen the guidance for making choice of hosting model. Extra information should be offloaded to other topics where possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542f38c4-1502-f739-372a-80c86c377491
* Version Independent ID: 72c2a844-ffb2-4799-2c7a-a7a73d3b6833
* Content: [ASP.NET Core Blazor hosting models](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/hosting-models.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hosting-models.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by danroth27** [comment]
I think the high-level goal for this topic is help Blazor users choose between the different Blazor hosting models: Blazor Server, Blazor WebAssembly, Blazor Hybrid (new with .NET 6). I think this means providing two pieces of information: 1. A basic overview of how the hosting model works, and 2. what hosting model's benefits and limitations are. We should also reassure users that regardless of which hosting model they start out with, the component model doesn't change and switching between hosting models is straight forward.

What I don't think we want in this topic are details about using the hosting model, deployment specifics, etc.

Here's my list of suggestions for this topic:

- Remove the note in the Blazor Server section about using sticky sessions. That should be covered in the [Host and deploy Blazor Server](https://docs.microsoft.com/aspnet/core/blazor/host-and-deploy/server)
- Reword the 3rd bullet in the Blazor Server limitations to emphasize that scale out requires server resources to handle client connections and state. Blazor Server scalability isn't "challenging", it just requires scaling out server resources appropriately.
- Remove the paragraphs about support for Docker. While true, it's not immediately relevant to this topic. Docker support is generally assumed for ASP.NET Core.
- Move the [Comparison to server-rendered UI](https://docs.microsoft.com/aspnet/core/blazor/hosting-models) section to the [Blazor Overview](https://docs.microsoft.com/aspnet/core/blazor).
- Simplify the content from the [Circuits](https://docs.microsoft.com/aspnet/core/blazor/hosting-models#circuits) section and incorporate it as a single paragraph in the description of Blazor Server before diving into the pros & cons. We'll need to check if this section is referenced from elsewhere and figure out what to do about that.
- Remove the "UI latency" and "Connection to the server" sections. We already mention these as Blazor Server limitations. It doesn't seem like these sections add much that's necessary.
- It would be great if we could also update the diagrams in this topic to use the somewhat nicer diagrams from the [Blazor Overview](https://docs.microsoft.com/en-us/aspnet/core/blazor/).
