### ISSUE TITLE
In-memory state container service code fails to compile

### ISSUE THREAD

**Issue by WolfgangBaeck** [dotnet/AspNetCore.Docs#23155]
The provided example will result in:
"StateContainer": member names cannot be the same as their enclosing type. The intermediate code results in:
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private Models.StateContainer StateContainer { get; set; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://docs.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report @WolfgangBaeck ... I'll try to get it fixed by the end of the day.
