### ISSUE TITLE
Tried the steps in this Document, but was running into error

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#23166]
I tried the Steps mentioned in this document but running into error.

I am using VS2022 preview 3.1 and .NET 6 preview 7

Sample at this location
https://github.com/nssidhu/SignalRTest/

Error 
![image](https://user-images.githubusercontent.com/3267605/131438795-35c8f32d-62f4-4303-801e-5250840eb95f.png)

F12 windows scrolled and error continues

![image](https://user-images.githubusercontent.com/3267605/131438919-a641e8d9-663e-4cd9-983e-336a24951852.png)

![image](https://user-images.githubusercontent.com/3267605/131438965-0ae66a9a-f7e4-4e08-b467-e19779557d3d.png)

**Comment by guardrex** [comment]
@nssidhu ... Please open issues here using the **This page** feedback button to add metadata to the issue and ping the author.

From the screenshot, it looks like you started the app from the **Client** project, not the **Server** project. Highlight the **Server** project in the **Solution Explorer** and run the app again.

If you hit this error again (or another error), open it for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by nssidhu** [comment]
You are right. did not notice it. works after correcting the startup project.
 The new Template in VS2022 Preview 3 has a bug where it defaults the startup project to Client one.
 https://github.com/dotnet/aspnetcore/issues/35356

**Comment by guardrex** [comment]
Thanks @nssidhu ... This has been an on-and-off issue for years around here 😈. Even when they fix the startup project for VS ... which I believe has broken in this way a few times over the years ... we're still left with the problem of devs running a hosted WASM app from the **Client** project in a command shell. I've made a note on one of my tracking issues to double-check the guidance and confirm that I say 'run from the **Server** project' in CLI instructions. Thanks for commenting on this.
