### ISSUE TITLE
Remove CompatibilityVersion.Version_2_1 code from doc and test with latest .NET

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#23162]
It is necessary to make improvements in the document, it must be remembered that this document is read by people who are learning or who are looking for a guide on how to proceed.

A good manual accompanies the reader and gives him information step by step.

Doc  show an ejample with "ASP.NET Core 2.1 web app"  **that is from 2018** but for .NET 5 there are not example.

And you need to add a good explanation of why each line is added and what is the purpose of the added code.
Likewise, the place where the EmailSender class should be added is not specified.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It was updated for 3.1 and didn't change in 5.0

**Comment by Byron2016** [comment]
> It was updated for 3.1 and didn't change in 5.0

@Rick-Anderson  For a "**Scaffold Identity into an MVC project with authorization**" (ASP.NET Core Web App (Model-View-Controller) - Target framework: NET 5.0)  these are the errors inside section "**Create full Identity UI source doc enhancement**"

1. options.MinimumSameSitePolicy = SameSiteMode.None;  **// show a error then it need to be commented**
2. CompatibilityVersion.Version_2_1                                        **// show a error then itneed to be changed to: Microsoft.AspNetCore.Mvc.CompatibilityVersion.Latest**
3. options.AllowAreas = true;                                                 **// show a error then itneed to be commented**
