### ISSUE TITLE
Is there an Event for connection state Changed

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#23189]
I see a code that get the state of connection.
```
 public bool IsConnected =>
        hubConnection.State == HubConnectionState.Connected;
```

But is it possible to have Event which I can subscribe to so that i can get notification about changes in states like
Connected, Disconnected, Reconnecting etc. ?
Any links to such a sample ?

Additional, in F12 Bowser tools there is an option to go offline for HTTP Requests, how would one be able to simulate this for web sockets ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... Take a look at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=server#blazor-server-circuit-handler-1

Outside of a circuit handler, I'm not aware of another approach. If that doesn't seem like it would work for your scenario, then you can ask the product unit directly by opening an issue at ...

https://github.com/dotnet/aspnetcore/issues

> Additional, in F12 Bowser tools there is an option to go offline for HTTP Requests, how would one be able to simulate this for web sockets ?

That will need go to the product unit. You'd have to ask them directly at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by nssidhu** [comment]
Looks like i found the link to correct documentation for client side state change event.

https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-5.0&tabs=visual-studio

Now i am still looking out for ways to simulate web socket connection on/off in developer tools or some other way.

**Comment by guardrex** [comment]
For client-side, there's also possibly this ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=server#modify-the-reconnection-handler-1
