### ISSUE TITLE
Host.CreateDefaultBuilder soruce code

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#23196]
Where is located the source code of "**Host.CreateDefaultBuilder**"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0#set-up-a-host)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/aspnetcore/tree/main/src/Hosting/Hosting/src/GenericHost

@serpent5  we should start adding a link to the source

**Comment by Byron2016** [comment]
> https://github.com/dotnet/aspnetcore/tree/main/src/Hosting/Hosting/src/GenericHost
> 
> @serpent5 we should start adding a link to the source

Maybe that is not the correct link because it is to this namespace "Microsoft.AspNetCore.Hosting" and when you press right button over "Program.cs / Program / CreateHostBuilder / **Host.CreateDefaultBuilder**" it sent into visual studio 2019 this code:

```
namespace Microsoft.Extensions.Hosting
{
    public static class Host
    {
        public static IHostBuilder CreateDefaultBuilder();
        public static IHostBuilder CreateDefaultBuilder(string[] args);
    }
}
```

**Comment by guardrex** [comment]
@Byron2016 ...

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs

Side Note: @Rick-Anderson @wadepickett @serpent5 -- I have the rare need for a few code cross-links but didn't want to confuse devs about the version of what they're looking at. I keep the following INCLUDE for those cases in the Blazor docs includes folder. Should I move it out to the repo root's include folder for all docs?

The text of the INCLUDE is (with the usual `no-loc` at the top) ...

\> \[!NOTE]
\> Documentation links to the ASP.NET Core reference source load the repository's \`main\` branch, which represents the product unit's current development for the next release of ASP.NET Core. To select the branch for a different release, use the \*\*Switch branches or tags\*\* dropdown list to select the branch. For example, select the \`release/5.0\` branch for the ASP.NET Core 5.0 release.

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/includes/aspnetcore-repo-ref-source-links.md

**Comment by Rick-Anderson** [comment]
@guardrex  sounds good but no hurry.

**Comment by guardrex** [comment]
Cool ... actually have a few minutes right now. I'm waiting on the CJ tarp to dry enough in the 🌞 so that I can get the tarp off and do some work on it today. *Woot!* 🛻
