### ISSUE TITLE
Not easy to read

### ISSUE THREAD

**Issue by mogaozq** [dotnet/AspNetCore.Docs#23192]
I've read this page twice. There are lots of similar interfaces and methods like `OptionsBuilder`, `Configure`, `AddOptions` that made me confused. I think I have to read it 2 more times to get it completely. I don't know if I can't understand well or it is not understandable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#val)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback. It helps to write some code that uses it.
