### ISSUE TITLE
.NET 6: Add custom config provider code

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23208]
See [Custom configuration provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0&branch=pr-en-us-23188#custom-configuration-provider) 

Create a new ASP.NET Core 6 web app the implements the Custom configuration provider in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/configuration/index/samples/6.x/EFconfigSample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0&branch=pr-en-us-23188#add-configuration-from-an-external-assembly)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan See the [6.x version and code](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson taking care of it. However, why does it say `62 minutes` to read? 😄 

![image](https://user-images.githubusercontent.com/6568968/132118729-16197958-3182-4f08-b141-219a782902fa.png)

**Comment by fiyazbinhasan** [comment]
Is this some kind of a bug? Outputs are garbled. I'm on `6.0.100-preview.7.21379.14`

![image](https://user-images.githubusercontent.com/6568968/132121746-4d918e7f-03f8-441e-99e3-0475139001a2.png)

**Comment by Rick-Anderson** [comment]
Yes, that will be fixed in the next release. see https://github.com/dotnet/roslyn/issues/55461

> @Rick-Anderson taking care of it. However, why does it say `62 minutes` to read? 😄

I never liked those reading estimates.
