### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureADB2C.UI package

### ISSUE THREAD

**Issue by vangundy** [dotnet/AspNetCore.Docs#23206]
This page includes a reference to Microsoft.AspNetCore.Authentication.AzureADB2C.UI package which is now obsolete.  Please update doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure an ASP.NET Core Blazor WebAssembly hosted app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-3.1&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__fcpaflfvy9kfqwzpf9c6pq3lnu2xrnwh3t3jxorp00%29%287593%29%281243925%29%28je6NUbpObpQ-QYnJHQkER2SAa3gm1XXWIQ%29%28%29&irclickid=_fcpaflfvy9kfqwzpf9c6pq3lnu2xrnwh3t3jxorp00&source=docs#access-token-scopes&ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-QYnJHQkER2SAa3gm1XXWIQ&epi=je6NUbpObpQ-QYnJHQkER2SAa3gm1XXWIQ)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vangundy ... You're looking at the 3.1 version of the doc. Change the version selector to 5.0 to see the updated content.

**Comment by vangundy** [comment]
Oops! sorry and thank you 😊 

-Paul
