### ISSUE TITLE
bug in migration Inheritance in ContosoUnivercity  tutorial 

### ISSUE THREAD

**Issue by soufianeBenRahim** [dotnet/AspNetCore.Docs#23212]
hi
this issue is moved from https://github.com/MicrosoftDocs/feedback/issues/3670
Thank you for your tremendous efforts in clarifying dotnet
in the Project of ContosoUnivercity :https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-5.0
The code in SchoolContext in methode OnModelCreating is incorrect after the modification related to Inheritance migration,
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0
 because studen corresponds to Steuden's table and instrector is to Instrector's table, while they should be to Pearson's table,
because the tabel Steuden and a instrector does not exist after the Migraration
![image](https://user-images.githubusercontent.com/32791470/132124534-2dc28e5a-b466-4921-8f16-60682a2507a7.png)
The solution you applied is
![Capture 2](https://user-images.githubusercontent.com/32791470/132124096-70125451-6871-4005-9a5a-97ad7160e151.PNG)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I believe the code is correct. Have you compared your code to https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-mvc/intro/samples/cu-final

**Comment by soufianeBenRahim** [comment]
thank you so much
I want to give you more explanations
in the tutorial https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-5.0
and in the source code which you referenced
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/ef-mvc/intro/samples/cu-final
after changing the TPH inertance, in the SchoolContext in the OnModelCreating method (ModelBuilder modelBuilder),
There are
modelBuilder.Entity <Student> () .ToTable ("Student")
and
modelBuilder.Entity <Instructor> () .ToTable ("Instructor");
but there is no Student and Instructor table in the database
there is only one "person" table, because the two entities Student and Instructor are mapped into a single Person table by the TPH technique
is it correct ?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog clean. If you believe there is a concern related to the ASP.NET Core which hasn't been addressed, please file a new issue.
