### ISSUE TITLE
Sparse documentation on full binding concepts - Binding and necessary to call ValidationMessage For from Custom Component

### ISSUE THREAD

**Issue by GregBrubaker** [dotnet/AspNetCore.Docs#23214]
When you @bind-Value you get mapping to 3 fields, and the 3rd one not mentioned well enough in binding section is critical to let a custom component use validation, and therefore also useful here in the validation page.  You also need this accessor expression to pull out Data Annotation like Required, Display, Max Length, and etc; so people need to understand that it exists and how to get to it.

    CustomComponent TValue="DateTime?" @bind-Value="order.PurchaseDate" /CustomComponent

    [Parameter]
    public virtual TValue Value { get; set; }
    [Parameter]
    public EventCallback<TValue> ValueChanged { get; set; }
    [Parameter]
    public Expression<Func<TValue>> ValueExpression { get; set; }
    
    
     ValidationMessage For="ValueExpression" /ValidationMessage

https://stackoverflow.com/questions/58196797/blazor-twoway-binding-on-custom-component/69063826#69063826

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-5.0#binding-inputselect-options-to-c-object-null-values)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GregBrubaker ... When you refer to "custom component," do you mean 'custom `EditForm` component?

**Comment by GregBrubaker** [comment]
@guardrex Yes, you could consider it related.  Because if you're making a custom edit form component you'd want to talk about the binding trinity.  And even if someone didn't want to use edit form for any reason, as long as you cover it there, you've still covered it.

**Comment by guardrex** [comment]
Thanks @GregBrubaker ... We'll get this covered under the original issue.
