### ISSUE TITLE
PUT and DELETE do not work

### ISSUE THREAD

**Issue by AntWatCDL** [dotnet/AspNetCore.Docs#23225]
The Post and Get examples work, but for the others I get:

HTTP/1.1 405 Method Not Allowed
Transfer-Encoding: chunked
Allow: GET, POST

This looks like a variation of this problem:

"https://mozartec.com/asp-net-core-error-405-methods-not-allowed-for-put-and-delete-requests-when-hosted-on-iis/"

But I can't get anything to work.

I am running locally, using .NET Core 3.1 and Visual Studio 2019 Professional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by AntWatCDL** [comment]
I have downloaded the sample code and run it without changes, and I still get the same behaviour.
I am using SoapUI, rather than Postman, but I don't think that should make any difference.
So, while it works on your pc it currently doesn't work on mine.

**Comment by Rick-Anderson** [comment]
This topic has over 100K users per month testing it in addition to us testing it, so we know it works. Try Postman or curl.

**Comment by AntWatCDL** [comment]
I am not saying the tutorial doesn't work at all, but it still doesn't work for me, and I'm sure others of your 100k users will have had the same problem.  I have tested on Postman and get the same behaviour.  I was hoping for some insight to the problem.

![image](https://user-images.githubusercontent.com/67459880/132473529-e28a6229-08a3-441b-be9d-8b2117e33ac5.png)

**Comment by morganaugbrown** [comment]
I was having the same issue, but I managed to figure out my mistake. You need to make sure that you add the id value to the end of the URL for the PUT action.

So, for your case, the URL would be https://localhost:44345/api/todoitems/1

**Comment by AntWatCDL** [comment]
Thanks @morganaugbrown that fix worked!
