### ISSUE TITLE
Add a section about troubleshooting common problems on windows

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#23233]
Some Windows configurations prevent self-signed certs from being trusted. These are rare, but we've run into them a couple of times.

It'll be great to add a section with docs about how to troubleshoot these issues. An example of those is https://github.com/dotnet/aspnetcore/issues/21173 where a group policy is preventing the certs from being trusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'll put 👀 on this for a possible cross-link to the new coverage from the Blazor *Debug* topic given that that's the scenario the dev was engaged with.
