### ISSUE TITLE
Add custom config section back to doc .NET 6 version

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23232]
Code provided by #23221

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  let me know if you're interested in this part. You would copy the markup for [Custom configuration provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#custom-configuration-provider) -the 3.0 version, into the same area under the `::: moniker range=">= aspnetcore-6.0"` region and update all the snippets to the right place in the 6.0 code you just wrote.

**Comment by fiyazbinhasan** [comment]
Sure, I'll take a look at it pretty soon. 😀
