### ISSUE TITLE
docker exec aspnetcore_sample ipconfig return error   executable file not found in $PATH

### ISSUE THREAD

**Issue by tindecken** [dotnet/AspNetCore.Docs#23236]
Follow document in page for Windows

PS C:\dev\ATTM> docker exec aspnetcore_sample ipconfig
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ipconfig": executable file not found in $PATH: unknown

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/vi-vn/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #27141
