### ISSUE TITLE
Swagger needs explicit http verbs

### ISSUE THREAD

**Issue by mogaozq** [dotnet/AspNetCore.Docs#23248]
There is a warning in the page that says:

> Don't mark the error handler action method with HTTP method attributes, such as HttpGet. Explicit verbs prevent some requests from reaching the action method. Allow anonymous access to the method if unauthenticated users should see the error.

The  problem is that Swagger requires all actions to use explicit http verbs. If I use [Route(...)] for my error handler action, Swagger throws an exception.

Please may you give me a clue how this problem is resolved.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by mogaozq** [comment]
I resolve the problem by decorating my ErrorController with` [ApiExplorerSettings(IgnoreApi = true)]`.
This ignore the controller for making swagger documents.

**Comment by mogaozq** [comment]
It should be better if you mention  `[ApiExplorerSettings(IgnoreApi = true)]` attribute in this page into the warning

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan can you reproduce the problem and solution? If this works, can you create a PR?

**Comment by fiyazbinhasan** [comment]
Yes. I'll take a look at it soon 🙂
