### ISSUE TITLE
Web Package (single-file) deployments aren't supported

### ISSUE THREAD

**Issue by davidsk** [dotnet/AspNetCore.Docs#23261]
In the [Differences between in-process and out-of-process hosting](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0#differences-between-in-process-and-out-of-process-hosting) section, it stipulates that:

```Web Package (single-file) deployments aren't supported```

Is there any more information available as to why this isn't supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52491d2-5493-260a-41cf-f6f8732738c1
* Version Independent ID: bc7f1ef8-0ccc-1233-a4eb-d9dc26ac9529
* Content: [In-process hosting with IIS and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/in-process-hosting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/in-process-hosting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @davidsk ... See :point_right: https://github.com/dotnet/runtime/issues/36590

**Comment by guardrex** [comment]
Actually, out-of-process seems to be supported.

https://github.com/dotnet/runtime/issues/36590#issuecomment-631913654

**Comment by davidsk** [comment]
So, the term package here is perhaps overloaded; I read the term web package meaning [_WebDeploy_ ](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/introduction-to-web-deploy) packages.  I assumed there was some issue between webdeploy and the ASP.Net Core Module or similar, but perhaps not. Can someone confirm?

**Comment by guardrex** [comment]
WebDeploy is fine ... for example, see ...

* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-5.0#publish-profiles
* https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-5.0#publish-to-an-msdeploy-endpoint-from-the-command-line
