### ISSUE TITLE
DeveloperExceptionPage does not show "Query string parameters if any ..."

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#23265]
Documentation says:

> The Developer Exception Page includes the following information about the exception and the request:
> 
> Stack trace
> Query string parameters if any
> Cookies if any
> Headers

but for .NET 5.0 that is not true. Currently it is only showing "Stack Trace" there are not links to Query string parameters / Cookies or Headers.

How to reproduce:

Create a EmptyWebApplicationCore with .NET 5.0

Insert this code:
```

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();  //app.UseFileServer();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                throw new Exception("Manual Error");
                endpoints.MapGet("/", async context =>
                {
                    
                    await context.Response.WriteAsync("Hello World!");
                });
            });
        }

```

Call a Url with queryString: 

`..../abc.html?a=124 `

Error screem capture go to:  ibb.co/svxMNQy

[https://ibb.co/svxMNQy](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The DeveloperExceptionPage  misses alot. Use logging.

**Comment by Byron2016** [comment]
> misses alot

Your answer is not clear and inside documentation show this:
```

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }
    else
    {
        app.UseExceptionHandler("/Error");
        app.UseHsts();
    }
   ....

```

and after that said that is going to show this elements:

> The Developer Exception Page includes the following information about the exception and the request:
> 
> Stack trace
> Query string parameters if any
> Cookies if any
> Headers

and that is not happening.

Please your help with this, it is a error with documentation, is something that is not complete and is not working with .NET 5.0?  
It is necesary to update documentation to currently status?

**Comment by Rick-Anderson** [comment]
That's not guaranteed. The DeveloperExceptionPage  is to help, but logging provides all the information.

**Comment by Byron2016** [comment]
> That's not guaranteed. The DeveloperExceptionPage is to help, but logging provides all the information.

I know that "The DeveloperExceptionPage is to help, but logging provides all the information." but I am following the **official microsoft documentation**, and **inside** of that documentation said that is going to show this elements,  **Stack trace/ Query string parameters if any/Cookies if any/Headers** and that is not happening (I give you how to reproduce the case), then I ask support about why in official documentation said something and it is happening another thing. I wait for an adequate answer of you @Rick-Anderson  in concordace with the documentation that I am following. Please try the problem, and give me a **adequate answer**. Remember @Rick-Anderson  that Microsoft paid you for a good job, sorry for this words, but you are not doing it.

**Comment by Byron2016** [comment]
@Rick-Anderson  If you change from "**include**" to "**Can include**" which are the conditions to "include or not" that information? Remember that add logging means to do some steps that are not necesary with UseDeveloperExceptionPage and it is for that reason that UseDeveloperExceptionPage was create with this 4 information links (**Stack trace/ Query string parameters if any/Cookies if any/Headers**)
Into this link: https://stackoverflow.com/questions/41883064/how-to-get-developer-exception-page-to-show-multiple-lines-of-code-around-except you will see a screen capture about what oficial Microsoft Documentacion refers. There you will see the 4 buttons  **Stack trace/ Query string parameters if any/Cookies if any/Headers**. Please your answer @Rick-Anderson in a adequate and complete way.
