### ISSUE TITLE
Please update 'Mock authentication' example

### ISSUE THREAD

**Issue by GorbunowArtem** [dotnet/AspNetCore.Docs#23262]
Code example in [Mock authentication](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#mock-authentication) section does not work or at least works in some cases.
[Here](https://stackoverflow.com/questions/61769497/skip-jwt-auth-during-tests-asp-net-core-3-1-web-api) example that worked in my case, I think it can be added to the page.

`	services.AddAuthentication(options =>
						{
							options.DefaultAuthenticateScheme = TestAuthHandler.DefaultScheme;
							options.DefaultScheme = TestAuthHandler.DefaultScheme;
						})
						.AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(
							TestAuthHandler.DefaultScheme, options => { });`
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0#mock-authentication)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #23543
