### ISSUE TITLE
UseDefaultFiles Middleware order

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#23260]
The middleware order is very important and there are only one example for a typical MVC aplication. But for example for middleware **UseDefaultFiles** does not said about it must be before UseStaticFiles. 
It is important to place in some place which middleware is necesary to be before and after others middleware.
I think could be a good idea to construct a table with this dependencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestions. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-5.0#middleware-order

**Comment by Rick-Anderson** [comment]
It's stated in https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0
