### ISSUE TITLE
Links to sections in JS interop topic broken

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#23278]
Some of the links to sections within this article seem to be broken. For example, links to #javascript-isolation-in-javascript-modules don't work because the corresponding section has an ID of `javascript-isolation-in-javascript-modules-1`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#javascript-libraries-that-render-ui-1)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 ... This is the known issue that I was telling you about earlier as one of the main problems using *whole-topic versioning* (i.e., multiple copies of a topic in a single markdown file ... a virtual necessity given the engineering churn and rapid release cycle). Duplicated headings are auto-numbered by the build engine using *whole-topic versioning*, so links break after we put up a preview release moniker ... in this case ... 6.0 preview docs. This is one of the reasons why I went to so much trouble trying to get *version by file* working on my own, but you know how that went 😈💥😢. @Rick-Anderson is planning on working with the DocFX engineers in 2022 to set up *version by file* to solve this problem once and for all. At 6.0 GA, it will be solved for 6.0 docs. I've been pitching to docs management for several years to address this problem without success. I don't have a better solution/approach at the moment.

**Comment by guardrex** [comment]
@Rick-Anderson ... Have you had success with duplicated named anchors? I could convert over to the HTML5-way of using named `id`s that wouldn't auto-number; but if you already know that duplicated named anchors don't work, then such an effort (named `id`s) will fail as well. I use a few named `id`s to avoid intra-doc link failures with pivots, but I don't think I've tried them with whole-topic versioning. Perhaps, I should run a test and see if they work.

**Comment by Rick-Anderson** [comment]
@guardrex  see https://github.com/dotnet/AspNetCore.Docs/pull/23246/files where I left you a comment.

**Comment by guardrex** [comment]
> I put the default version at the top

*Ah!* ... yes, that makes good sense.

**Comment by guardrex** [comment]
Discussed offline. We're going to wait for ...

* 6.0 becomes the default doc set at 6.0 GA.
* *Version by File* becomes a thing next year 🤞🍀.
