### ISSUE TITLE
Doc update to remove AllowAreas

### ISSUE THREAD

**Issue by rustyweb** [dotnet/AspNetCore.Docs#23280]
It's minor, but took me a bit to find the answer so just to help anyone else.

In this section the **options.AllowAreas** should be removed as it isn't needed anymore - from what I could dig up it was removed in .net core 3. Also the **CompatibilityVersion** had to be a minimum of 3, but maybe that's because my project is .net5?:
[Create full Identity UI source](https://docs.microsoft.com/en-ca/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio#create-full-identity-ui-source)

```
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
        .AddRazorPagesOptions(options =>
        {
            options.AllowAreas = true;
            options.Conventions.AuthorizeAreaFolder("Identity", "/Account/Manage");
            options.Conventions.AuthorizeAreaPage("Identity", "/Account/Logout");
        });
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-ca/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rustyweb `CompatibilityVersion` should be removed too.

**Comment by rustyweb** [comment]
@Rick-Anderson thank you for that additional info! I'll take that out of my code as well.

**Comment by Rick-Anderson** [comment]
.NET 6 scaffolding prerelease has a few bugs that should be fixed in RC1 or RC2. Once that's done I'll update this to .NET 6. Hopefully you'll be on .NET 6 soon too.
