### ISSUE TITLE
internal "hash" links not working on a page

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/AspNetCore.Docs#23288]
For example click "EventSource" - it points to `#event-source` while the actual link is `#event-source-1`.

BUT it does work when I'm looking at the article via Github. I guess the CMS that publishes markdown to docs.microsoft.com has a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x&view=aspnetcore-5.0#event-source-1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alex-jitbit ... This is a known issue at that will be partially resolved when the 6.0 preview docs become the default loaded doc set. The problem will be permanently fixed in 2022 with a new versioning system.
