### ISSUE TITLE
Azure AAD: Update for .NET 6

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23287]
.NET 6 uses the minimal hosting model. Startup goes away. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0 for an example of migrating to .NET 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
@damienbod  any chance you could update the code in a PR? I'll fix up the article.

**Comment by damienbod** [comment]
Hi @Rick-Anderson , yes I can do this

Greetings Damien
