### ISSUE TITLE
Update to Cloud authentication with Azure Active Directory B2C in ASP.NET Core

### ISSUE THREAD

**Issue by vinthefantastic1** [dotnet/AspNetCore.Docs#23285]
`public void Configure(IApplicationBuilder app, IWebHostEnvironment env)` needs an update to enable `signin` and `signout` to work:

Please update `app.UseEndpoints(endpoints =>`

    /* add this */
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");

    endpoints.MapRazorPages();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
It currently has

```
app.UseEndpoints(endpoints =>
    {
        endpoints.MapRazorPages();
        endpoints.MapControllers();
    });
}
```

`endpoints.MapControllers();` is exactly the same as 



> ```
> /* add this */
> endpoints.MapControllerRoute(
>     name: "default",
>     pattern: "{controller=Home}/{action=Index}/{id?}");
> 
> endpoints.MapRazorPages();
> ```
