### ISSUE TITLE
Deprecated document

### ISSUE THREAD

**Issue by tnlthanzeel** [dotnet/AspNetCore.Docs#23292]
Hi All, i was setting up a project with identity razor library  in .NET5 and i was following this document. seems like this document is out dated and does not work when followed the steps in the document. please provide a working example so we can finish the setup for identity. thanks in advance!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-ca/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It works for 5.0
I'll be updating it for 6.0 soon.

**Comment by tnlthanzeel** [comment]
@Rick-Anderson , hi sir, we are not able to build on the example provided in the documentations. is it possible to give us a sample code base where you have implemented in .NET 5 please. this will be a great help sir!.
