### ISSUE TITLE
FormFile ContentType = null from Blazor

### ISSUE THREAD

**Issue by Continuitis** [dotnet/AspNetCore.Docs#23305]
Hello,

I tried your example and I have an issue with the ContentType on Api side.
My Api is self hosted and separated from the blazor WebAssembly website.
On controller look for the ContentType of all the files ( IEnumerable<IFormFile> files) it's always null (I send jpg...)

The weird thing is when I try via Swagger it's working.
My Cors is set to:
`app.UseCors(builder => builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
services.AddCors(x=>x.AddDefaultPolicy(y=>y.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin()));
`

And I run locally... Any clue?

Thanks in advance!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Great idea @Continuitis ... Idk if it was an oversight on my part or it was just something that I figured a dev would see/find/know about multipart form data. Try this ...

1. Add a `using` to the top of the WASM app (client) component for `System.Net.Http.Headers` ... 

   ```razor
   @using System.Net.Http.Headers
   ```

2. In `OnInputFileChange` of the component, you set the header on the `new StreamContent`, so right after the line that sets `fileContent`, you set the header as ...

   ```csharp
   fileContent.Headers.ContentType = new MediaTypeHeaderValue(file.ContentType);
   ```

See if that works.

Don't close this issue tho if it works ok ... I would like to add this to the sample code. This issue will close automatically later when the PR merges.

**Comment by Continuitis** [comment]
It worked perfectly - thanks!
