### ISSUE TITLE
Docs & Example not compliant with Microsoft API Guidelines

### ISSUE THREAD

**Issue by flxdot** [dotnet/AspNetCore.Docs#23339]
The example shows an endpoint `https://localhost:<port>/WeatherForecast` and the default template also creates this endpoint. This is in contrast with https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#172-casing.

The example endpoint should be: `https://localhost:<port>/weatherForecast`

It would be great if this could be resolved so that the templates and docs are compliant with the API Guidelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
REST API's use lower case. cc @tdykstra

**Comment by Rick-Anderson** [comment]
Issues for ASP.NET Core templates should be opened in https://github.com/dotnet/aspnetcore.

**Comment by Rick-Anderson** [comment]
@tdykstra  let's change the URL to lowercase
