### ISSUE TITLE
Add startup dropped to Migrate from ASP.NET Core 5.0 to 6.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by davidfowl** [comment]
I wrote a thing https://gist.github.com/davidfowl/0e0372c3c1d895c3ce195ba983b1e03d

**Comment by davidfowl** [comment]
@Rick-Anderson  I suggest we put this under a section labeled "Migrating to the new hosting model". We want to make sure people see that migrating existing projects is minimal effort then show them the new hosting model and show them how to adopt it (that's my gist).
