### ISSUE TITLE
Update cross-link to official EFCore doc when available

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23342]
Per https://github.com/dotnet/AspNetCore.Docs/issues/22985, the cross-link to ...

https://blog.jeremylikness.com/blog/multitenancy-with-ef-core-in-blazor-server-apps/

... that was added on https://github.com/dotnet/AspNetCore.Docs/pull/23341 will change to point to an official EFCore doc that will be based on that content. This issue is to update the Blazor doc cross-link when the new EFCore topic is live.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @JeremyLikness
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
@JeremyLikness ... Did your blog post at ...

https://blog.jeremylikness.com/blog/multitenancy-with-ef-core-in-blazor-server-apps/

... become an official doc yet? If not, is there an EF Core or .NET Docs repo issue that I can track on for it?

**Comment by JeremyLikness** [comment]
@guardrex will work on it soon. I made [issue #3589](https://github.com/dotnet/EntityFramework.Docs/issues/3589)
