### ISSUE TITLE
Integration tests in Asp.Net 6

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/AspNetCore.Docs#23344]
Is there a demo of how to do integration tests in Asp.Net 6 with minimal apis?

I found this: https://github.com/DamianEdwards/MinimalApiPlayground/blob/main/tests/MinimalApiPlayground.Tests/PlaygroundApplication.cs

but it doesn't work for me. 

1) If I use `WebApplicationFactory<Program>`, I get `InvalidOperationException: Can't find 'bin\Debug\net6.0\testhost.deps.json'`
2) But that's fine. I can use a random class from api project instead of `Program`. When I do that there's another problem. DbContext is not being replaced with test DbContext for some reason, even though I'm removing regular DbContext and adding a test one like described here: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0 It worked in .net6-preview7, and doesn't work in .net6-rc1

**Comment by pkanavos** [comment]
Second time that I link to those samples in an SO question that uncover something interesting. A quick blog post would be useful to help people until the docs are done

**Comment by davidfowl** [comment]
https://gist.github.com/davidfowl/0e0372c3c1d895c3ce195ba983b1e03d#testing-with-webapplicationfactorytestserver

**Comment by Rick-Anderson** [comment]
See [Test with WebApplicationFactory or TestServer](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#test-with-webapplicationfactory-or-testserver)
