### ISSUE TITLE
Clarifications on the ASP.NET Fundamentals/Configuration page

### ISSUE THREAD

**Issue by JohnSurina** [dotnet/AspNetCore.Docs#23368]
Hey team,

I want to make a documentation addition to add explicit clarification on how to retrieve values from an applications configurations. There are many examples in the file on how to do this, but there is no explicit verbiage (at least none that I could find, or made sense to me) on how to get access to the configurations via the dependency injected IConfiguration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you look at the .NET version (link in first paragraph)? What's missing? Have you read the entire article?

**Comment by JohnSurina** [comment]
Following up, I read through the regular dotnet configuration documentation, and it does not mention the dependency injected IConfiguration service. I've looked quite a bit, I certainly could have missed something, but I put a considerable amount of time into looking.

To reiterate, the goal is just to make sure that that Configuration-getting functionality is explicitly explained in the docs.

**Comment by Rick-Anderson** [comment]
Create a PR.

**Comment by JohnSurina** [comment]
I did, I have a link up above in a hyperlink, here's the link more explicitly though:

https://github.com/dotnet/AspNetCore.Docs/pull/23369

**Comment by serpent5** [comment]
Closed in #23369.
