### ISSUE TITLE
Sample Web Api Tutorial

### ISSUE THREAD

**Issue by LindomarSilva** [dotnet/AspNetCore.Docs#23367]
[Enter feedback here]

Hi! Congratulation for tutorial, simple and didatic.
But, i think that http status code used is wrong for empty return for route get ({id}). 
Definition of StatusCode 404 not is apllyed to search with empty results, it's used when can’t map the client’s URI to a specific resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-5.0&tabs=visual-studio#return-values-1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
per the article I think they are correct. Can you site a definitive reference saying otherwise?

**Comment by LindomarSilva** [comment]
Hi Rick!
We can find any references, i see that exists anothers codes using 404, but
these codes do not converge, all articles find for us...
Sample:
https://restfulapi.net/http-status-codes/
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml#http-status-codes-1

But, it's a suggestion, after we read some documentations.

Em ter., 21 de set. de 2021 às 18:38, Rick Anderson <
***@***.***> escreveu:

**Comment by serpent5** [comment]
I agree that 404 is generally acceptable here, but feel free to use a different status-code if it works better for your clients.
