### ISSUE TITLE
HTTPS certificate on Linux needs to trust the user, not root, certificate

### ISSUE THREAD

**Issue by sgryphon** [dotnet/AspNetCore.Docs#23378]
In **Trust HTTPS certificate on Linux**, when exporting the certificate, you need to make sure you export the developer certificate for the current, not root, i.e. check the thumbprint you are trusting is the one you want.

To export the current user's developer certificate I had to make sure it was created (`dotnet dev-certs https`), then run `sudo -E dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM`, to use the current user's environment. You can check the current users certificate via `ls ~/.dotnet/corefx/cryptography/x509stores/my`; the filename will be the SHA1 thumbprint, and the certificate you are trusting (`https.crt`) has to match.

To check the thumbprint of the exported certificate: `openssl x509 -noout -fingerprint -sha1 -inform pem -in /usr/local/share/ca-certificates/aspnet/https.crt`

Running `sudo dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM`, without the `-E`, would export root's certificate (generating it if necessary), which had a different thumbprint. You can check this certificate at `sudo ls -la /root/.dotnet/corefx/cryptography/x509stores/my`

If I ran without sudo (just `dotnet dev-certs https -ep ...`), then I didn't have permission; if I ran `sudo -E` without first generating the cert (e.g. straight after `dotnet dev-certs https --clean`), then it failed creating the cert.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sgryphon** [comment]
Note that the original instructions may work fine if you are logged in as root (but then you would not need the sudo), or running the dotnet application as root. Adding details of where to check the certificates is also useful.

**Comment by sgryphon** [comment]
I'm happy to write up and do an actual pull request, if that is easier.

**Comment by Rick-Anderson** [comment]
_A PR would be great _
