### ISSUE TITLE
Project Confusion.

### ISSUE THREAD

**Issue by DarylGraves** [dotnet/AspNetCore.Docs#23374]
I can only get the window shown in step 5. to appear if I use choose the "ASP.NET Web Application (.Net Framework)" project but then there isn't an option to choose "ASP.NET Core Web App"

I originally tried with the "ASP.NET Core Web App" project instead but when I got to the stage where I needed to make my first class in the Models folder, there was no option to make a class, it wasn't an option so not sure if I'm using the wrong project type, missing a package on my computer or both?

![image](https://user-images.githubusercontent.com/46203429/134416928-10b6d139-faa6-4e8b-b992-d950b41cdbe1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by DarylGraves** [comment]
It appears I was missing the full ASP.NET and web development workload required which explains why I couldn't create classes - I will continue with my first attempt however I do believe that New Project Wizard is still out of date.

**Comment by Rick-Anderson** [comment]
Use the version selector if you're on .NET 6
