### ISSUE TITLE
The examples which show how not to do things, towards the end of the document, render with a white background in dark mode, which looks wrong.

### ISSUE THREAD

**Issue by ssg47** [dotnet/AspNetCore.Docs#23383]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you provide a screen shot?

**Comment by Rick-Anderson** [comment]
They are correct, they're images, not code
![image](https://user-images.githubusercontent.com/3605364/134777300-bc6bb75d-b023-4eb3-b815-6cb3319de27f.png)
