### ISSUE TITLE
nullable string as query parameter

### ISSUE THREAD

**Issue by cantSleepNow** [dotnet/AspNetCore.Docs#23385]
[Enter feedback here]
I could be nitpicking here :) but under [query strings](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#query-strings), it could be that it's a bit misleading to say 

> except string, which doesn't have a nullable variant

 even if it's correct that one can't use nullable strings as query parameters here (which I don't know now, going through the docs first time :) )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#query-strings)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Nullable variants of the preceding types (except string, which doesn't have a nullable variant).

@IEvangelist  that's not true for .NET 6 is it?

**Comment by guardrex** [comment]
[Came in at C# 8/.NET Core 3.0](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/nullable-reference-types), but this is the first time we've had the compiler roll with it (`<Nullable>enable</Nullable>` ... [see this](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/nullable-reference-types#setting-the-nullable-context)). I'm fighting with the compiler over one pesky warning 😈 in the EF Core-Blazor Server sample app.

**Comment by IEvangelist** [comment]
Hi @Rick-Anderson,

I'm not sure as it relates to routing, but yes a `string` does have a nullable variant. In other words, `string?` is valid.

**Comment by Rick-Anderson** [comment]
> I'm fighting with the compiler over one pesky warning 😈

@IEvangelist  told me about the [the damn-it operator (more properly the “null-forgiving operator”](https://codeblog.jonskeet.uk/category/c-8/)

@IEvangelist  can I write damn-it on your connect review?

**Comment by guardrex** [comment]
Before zapping it tho, I'd like to research further with the PU. I *really, really, REALLY* wish 🙏 the compiler wouldn't just flag a possible NRE but **_also SAY what type it's flagging_** ... i.e., *be more specific* in its warning message. Anyway, I know I'm not going to see that this time around. I'll have a **_real programmer_** 😄 tell me where that one line has gone astray.

**Comment by cantSleepNow** [comment]
> Hi @Rick-Anderson,
> 
> I'm not sure as it relates to routing, but yes a `string` does have a nullable variant. In other words, `string?` is valid.

That's exactly what I wanted to point out - string can be nullable, but not sure can it be nullable when used in routing query

**Comment by Rick-Anderson** [comment]
@guardrex  can you change the text to
Nullable variants of the preceding types (except string, which doesn't ~have~ support a nullable variant).

**Comment by guardrex** [comment]
We can strike the line. Nullable string is supported for query string params.
