### ISSUE TITLE
Implement IExceptionFilter instead of IActionFilter for HttpResponseExceptionFilter

### ISSUE THREAD

**Issue by trionia** [dotnet/AspNetCore.Docs#23388]
The document suggests creating a filter
```cs
public class HttpResponseExceptionFilter : IActionFilter, IOrderedFilter
```
Why not use `IExceptionFilter` instead? In that case `IOrderedFilter` will be also unnecessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-5.0#implement-problemdetailsfactory)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @pranavkm
* Microsoft Alias: **prkrishn**

**Comment by pranavkm** [comment]
@trionia the intent was to use an error type that the action returns and turn that in to a response status. Since this is specific to the action, an exception filter isn't warranted.
