### ISSUE TITLE
An asp.net core web api application, using "UseWindowsService", reports an error “System.NotSupportedException: The content root changed. Changing the host configuration is not supported ” when starting the service 

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/AspNetCore.Docs#23387]
- System 

  - Provider 

   [ Name]  .NET Runtime 
 
  - EventID 1026 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 0 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2021-09-26T05:59:39.0432975Z 
 
   EventRecordID 14008 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Computer USER-20210710BJ 
 
   Security 
 

- EventData 

   Application: ZhaoyangParking.exe CoreCLR Version: 6.0.21.45113 .NET Version: 6.0.0-rc.1.21451.13 Description: The process was terminated due to an unhandled exception. Exception Info: System.NotSupportedException: The content root changed. Changing the host configuration is not supported at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureHostConfiguration(Action`1 configureDelegate) at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseContentRoot(IHostBuilder , String ) at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder, Action`1 configure) at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder) at Program.<Main>$(String[] args) in E:\Learn\ZhaoyangParking\ZhaoyangParking\Program.cs:line 20  

**But There is nothing wrong with the program in .NET Version: 6.0.0-preview.7.21377.19** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
We need to update the windows service hosting document https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio to mention that the service should be created passing the `--contentRoot` argument.

We might want to do the same here for good measure:

https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service#create-the-windows-service cc @IEvangelist

**Comment by IEvangelist** [comment]
> We need to update the windows service hosting document https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-5.0&tabs=visual-studio to mention that the service should be created passing the `--contentRoot` argument.
> 
> We might want to do the same here for good measure:
> 
> https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service#create-the-windows-service cc @IEvangelist

Thanks for the heads up @davidfowl - see https://github.com/dotnet/docs/issues/26274

**Comment by Rick-Anderson** [comment]
See [Create the Windows Service](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service#create-the-windows-service)

https://github.com/dotnet/docs/pull/26372/files:

> [!TIP]
> If you need to change the content root of the [host configuration](./generic-host.md#host-configuration), you can pass it as a command-line argument when specifying the `binpath`:
>
> ```powershell
> sc.exe create "Svc Name" binpath="C:\Path\To\App.exe --contentRoot C:\Other\Path"
> ```

**Comment by davidfowl** [comment]
Yes, we plan to make this a bit more seamless so nothing has to be changed by default.

**Comment by josdan018** [comment]
> I am trying to create my service with the new `--contentRoot` argument but am experiencing this issue where the argument isn't accepting a space character:
> 
> `sc.exe create Diagnostics binPath="C:\Program Files\Diagnostics\Diagnostics.exe --contentRoot C:\Program Files\Diagnostics"`
> 
> ```
> Application: Diagnostics.exe
> CoreCLR Version: 6.0.322.12309
> .NET Version: 6.0.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.DirectoryNotFoundException: C:\Program\
> ```

@DapperDeer .exe path should be quoted [ref](https://stackoverflow.com/a/11084834)

**Comment by SimoneBWS** [comment]
In my case it works with:
`
sc create MyApp binpath="C:\Program Files\Contoso\MyApp\bin\MyApp.exe --contentRoot C:\Program Files\Contoso\MyApp\bin\"
`

**Comment by tbayart** [comment]
2 years later, we still face the same issue
@davidfowl can you tell me if there is a reason to set the ContentRootPath only when the application run as a Windows service ?
>     ContentRootPath = WindowsServiceHelpers.IsWindowsService() ? AppContext.BaseDirectory : default
also if this is still considered as a workaround, is there a cleaner way to start a Krestrel as a Windows service ?

**Comment by davidfowl** [comment]
What version of .NET are you running?

**Comment by tbayart** [comment]
net6.0 LTS

**Comment by davidfowl** [comment]
It's fixed in .NET 7+

**Comment by tbayart** [comment]
Thanks for the update, i will check that with incoming net8.0 upgrade

**Comment by mateuszPATeam** [comment]
Apologies for digging up an old thread, but I'm unable to set the content root path, no matter what I do. My application is self-contained, single executable, and I want to host it as a Windows Service. I applied the above snippet and tried to create the service with --contentRoot, but it just doesn't do anything and my Content Root is always pointing to a folder in Windows. The target framework is .NET 6. Any ideas how I can fix it?

**Comment by tbayart** [comment]
@davidfowl answer solved the issue on my side for my .net 6 version
https://github.com/dotnet/AspNetCore.Docs/issues/23387#issuecomment-927317675

if it's not your case, try to reproduce your issue with minimal code and post it here so we can help you solve your problem
