### ISSUE TITLE
Broken bookmarks

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23396]
Local builds indicate broken bookmarks. I'd patch these myself, but I'm 🏃😅 on Blazor issues for the foreseeable future and don't have time right now. Please close this issue if this will be tracked in some other way.

* (security/authorization/secure-data.md#L52)Invalid link: '\<a href="tutorials/first-mvc-app/adding-model.md#scaffold-the-movie-model">scaffolding</a>'. The file tutorials/first-mvc-app/adding-model.md doesn't contain a bookmark named 'scaffold-the-movie-model'.
* (security/authorization/secure-data.md#L408)Invalid link: '\<a href="tutorials/first-mvc-app/adding-model.md#scaffold-the-movie-model">scaffolding</a>'. The file tutorials/first-mvc-app/adding-model.md doesn't contain a bookmark named 'scaffold-the-movie-model'.
* (tutorials/first-web-api.md#L1420)Invalid link: '\<a href="mvc/controllers/routing.md#attribute-routing-with-httpverb-attributes">Attribute routing with Http[Verb] attributes</a>'. The file mvc/controllers/routing.md doesn't contain a bookmark named 'attribute-routing-with-httpverb-attributes'.
* (tutorials/first-web-api.md#L1517)Invalid link: '\<a href="mvc/controllers/routing.md#attribute-routing-with-httpverb-attributes">Attribute routing with Http[Verb] attributes</a>'. The file mvc/controllers/routing.md doesn't contain a bookmark named 'attribute-routing-with-httpverb-attributes'.
* (host-and-deploy/health-checks.md#L2241)Invalid link: '\<xref:fundamentals/middleware/index#use-run-and-map>'. The file fundamentals/middleware/index.md doesn't contain a bookmark named 'use-run-and-map'.
* (migration/http-modules.md#L65)Invalid link: '\<a href="fundamentals/middleware/index.md#use-run-and-map">Pipeline branching</a>'. The file fundamentals/middleware/index.md doesn't contain a bookmark named 'use-run-and-map'.
* (fundamentals/configuration/index.md#L835)Invalid link: '\<xref:fundamentals/environments#development>'. The file fundamentals/environments.md doesn't contain a bookmark named 'development'.
* (fundamentals/configuration/index.md#L1683)Invalid link: '\<xref:fundamentals/environments#development>'. The file fundamentals/environments.md doesn't contain a bookmark named 'development'.

**Comment by Rick-Anderson** [comment]
@wadepickett  can you get this friction removed?
