### ISSUE TITLE
A simple IF to make the code more "universal"

### ISSUE THREAD

**Issue by leogag1** [dotnet/AspNetCore.Docs#23407]
I read the section about configuring Kestrel to run on macOS without TLS and looking at the code, I wonder whether it would be better to make the example more "universal" by adding a simple "if" in it:

``` csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            if (OperatingSystem.IsMacOS())
            {
                webBuilder.ConfigureKestrel(options =>
                {
                    options.ListenLocalhost(5000, o => o.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2);
                });
            }
            webBuilder.UseStartup<Startup>();
        });

```

Validating that it is a macOS operating system would allow deploying the service on other OSes without caring about this issue, I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-US/aspnet/core/grpc/troubleshoot?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
@leogag1  sounds like a good idea to me. @JamesNK  - can we add that line?

**Comment by JamesNK** [comment]
I don't think it is required.

The workaround for MacOS - HTTP/2 without TLS - doesn't stop the gRPC app from working on Windows.

**Comment by wadepickett** [comment]
Closing this 2021 suggestion per JamesNK feedback above.  Feel free to reopen if there is more discussion.
