### ISSUE TITLE
Make Identity more simple and understandable for newbies

### ISSUE THREAD

**Issue by cryoelite** [dotnet/AspNetCore.Docs#23408]
Currently [Introduction to Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0) welcomes new learners to Identity in a very daunting manner, this is elevated by the fact that the documentation jumps straight to parts such as configuring IdentityOptions and using Identity in the app without much explaination. 

The code for the same directly uses the concepts explained in later docs in deep and not briefly, this can confuse new learners as there is no explaination to what an Identity is, what a claim is, what a token is and so on. These are the parts that must be addressed before Identity's use is demonstrated. Currently Introduction to Identity is more like a Summary of Identity rather than an Introduction.

Proposal: A new doc with the title "Identity at a glance" right after [Overview](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-5.0) in Authentication. 

This doc should explain what Identity in Microsoft Universe is, what differences are there between a traditional Username/Password based authentication and how it could be done, then it must elaborate what Identity does, what claims/tokens/ etc. are and give a very basic barebone example of an Identity based authentication.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
