### ISSUE TITLE
V6: gRPC diagnostics 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23418]
Make V6 moniker version first and ref but don't close this. See #23405

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20ca5f3-1e63-e63f-07fa-99d523488893
* Version Independent ID: e9e7c656-a610-7b17-4ca4-8342ecc7298e
* Content: [Logging and diagnostics in gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Closed with #23434
