### ISSUE TITLE
"= new()" results in error

### ISSUE THREAD

**Issue by TylerGoldenHart** [dotnet/AspNetCore.Docs#23416]
Line 19 of Todo.razor in this tutorial results in error CS 8400 when running in Visual Studio 2019.

**private List<TodoItem> todos = new();**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0&pivots=server)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @TylerGoldenHart ... You must be on 3.1. Roll the doc version selector back to 3.1 ...

<img width="397" alt="Capture" src="https://user-images.githubusercontent.com/1622880/135357245-c4caa759-670d-44fe-8b9f-b2e550d8cde9.PNG">

... and you'll see that type inference isn't used ...

```csharp
private IList<TodoItem> todos = new List<TodoItem>();
```

... or update to ASP.NET Core 5.0 ...

https://dotnet.microsoft.com/download/dotnet/5.0
