### ISSUE TITLE
Don't forget to add missing dependencies

### ISSUE THREAD

**Issue by gabriel-ayusso** [dotnet/AspNetCore.Docs#23423]
Hi there, 

In case of someone faces the same issue as I, I would suggest to add a note in the page saying that the following dependency is required:
```ps
Install-Package Microsoft.AspNetCore.Authentication.Facebook
```
Bests,
- Gabriel Ayusso

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gabriel-ayusso ... It's covered for each provider in the provider-dedicated topics. For example ...

https://docs.microsoft.com/aspnet/core/security/authentication/social/facebook-logins

... for FB.
