### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by Elijah2101021** [dotnet/AspNetCore.Docs#23426]
![image](https://user-images.githubusercontent.com/86936446/135555251-f3bbe7b7-29c0-44ed-be48-e4dabb8ce0aa.png)
I got this error and how do i fix this, is there any problem with my code or the database problem?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the  ***English-US*** topic page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

See [Writing Useful Github Issues](https://upthemes.com/blog/2014/02/writing-useful-github-issues/) and the **What Not To Do** section.

**Comment by Rick-Anderson** [comment]
It's a good error message that should help.
