### ISSUE TITLE
Proposed solution for overwritten parameters breaks two-way binding

### ISSUE THREAD

**Issue by DarkStarDS9** [dotnet/AspNetCore.Docs#23431]
If I am not mistaken, the solution proposed on the page will not allow to bind the expanded-parameter to a model (or the be exact: it will in effect only do a one-way-binding, but you will never know the current value of .expanded).

How would you solve the use-case "page state should be remembered" (= when  I come back to the page, everything that was expanded before should be expanded again)?

Personally, I kinda expect data-binding to "just work" in Blazor, and having a general guidance in the docs that seems to break it just feels wrong. I'd rather provide the following solution:

```
@using System.Linq.Expressions
<div class="card custom-card @ActiveBackground">
    <div class="card-header" id="@Title" @onclick="@Toggle">
        <h3 class="card-title mb-0 @ActiveIcon">
            @Title
        </h3>
    </div>
    <div id="" class="collapse show">
        <div class="container-fluid">
            <div class="visually-hidden pr-2 pl-2" hidden="@(!_expanded)">
                @ChildContent
            </div>
        </div>
    </div>
</div>
@code
{
    [Parameter]
    public RenderFragment ChildContent { get; set; }

    private bool _expanded;

    [Parameter]
    public bool Expanded { get; set; }

    [Parameter]
    public EventCallback<bool> ExpandedChanged { get; set; }

    [Parameter]
    public Expression<Func<bool>> ExpandedExpression { get; set; }

    [Parameter]
    public string Title { get; set; }
	
    private string ActiveIcon => Expanded ? "cardheader-active" : "";
    private string ActiveBackground => Expanded ? "custom-card-active" : "";
	
    async Task Toggle()
    {
        _expanded = !_expanded;
		
        if (ExpandedExpression == null) return;
		
        Expanded = _expanded;
        await ExpandedChanged.InvokeAsync(Expanded);
    }
    protected override void OnInitialized()
    {
        _expanded = Expanded;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#overwritten-parameters-1)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DarkStarDS9 ... The current guidance is the PU-approved approach **_only perhaps_** as a base case. Many of the approaches aren't meant to address every conceivable state management scenario, and Steve did put up a whole doc on the subject at [ASP.NET Core Blazor state management](https://docs.microsoft.com/aspnet/core/blazor/state-management), which pivots at the top for WASM versus Server coverage. Whether we were to make further updates here (this topic) or there (state mgmt topic), we'll need to wait for a bit before we can address your remarks. The PU (including little 'ole 🦖 *me*)  is very 🏃😅 at the moment with 6.0 work for the 6.0 release. I'll ping them on this at the appropriate time shortly after RC2 comes out. That's not too far off ... just a few weeks. Sit tight, and we'll get back to you here.

**Comment by guardrex** [comment]
I slept on this, and we'll stick with what we have here to keep this section focused on the concept at hand. However, I'll cross-link to the two-way binding section at https://docs.microsoft.com/aspnet/core/blazor/components/data-binding#binding-with-component-parameters-1. The password entry example performs a two-way bind and doesn't write to its own parameter.
