### ISSUE TITLE
The .NET Core 5.0 example is incomplete and is not as per documented solution

### ISSUE THREAD

**Issue by MithunChopda** [dotnet/AspNetCore.Docs#23437]
The .NET Core 5.0 Solution is incomplete. In fact it is not at all as per the solution documented on the page. The document solution too doesn't clearly mention that it's Razor page specific solution. The upload solution for MVC Views is missing.

The 3.x solution is not compatible with 5.0 thus breaks.

Please upload the correct and properly tested MVC Views as well as Razor Pages based solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The 3.x solution is not compatible with 5.0 thus breaks.

Where? 3.1 and 5.0 are very compatible.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
