### ISSUE TITLE
CSS Isolation document doesn't mention :root

### ISSUE THREAD

**Issue by oliverholliday** [dotnet/AspNetCore.Docs#23445]
The docs mention using `::deep` to remove the attribute scoping on subsequent parts of the selector chain but it doesn't mention how to avoid scoping the first part of the selector - which can be done using `:root`. This can be helpful in situations such as needing to make components theme-aware.

If you have the following components, for example:

`Page.razor` -> `<div class="light"><Tab /></div><div class="dark"><Tab /></html>`
`Tab.razor` -> `<div class="tab"><Btn /></tab>`
`Btn.razor` -> `<button>hello</button>`

produces the following markup with generated b-1, b-2, b-3 css scoping attributes:

```html
<div class="light" b-1>
   <div class="tab" b-2><button b-3>hello</button></div>
</div>
<div class="dark" b-1>
   <div class="tab" b-2><button b-3>hello</button></div>
</div>
``` 

In `Tab.razor.css`:

`.tab ::deep button { color: red; }` becomes `.tab[b-2] button { color: red; }` so this matches content in a *child* component. It's not specified in the documentation how you'd target the `.light` and `.dark` classes that come from the *parent* component `Page.razor`.

In `Tab.razor.css`:

`::deep .light .tab ::deep button { color: red; }` becomes `[b-2] .light[b-2] .tab[b-2] button { color: red; }` so this **doesn't** match.
`.light ::deep .tab ::deep button { color: red; }` becomes `.light[b-2] .tab button { color: red; }` so this **doesn't** match.

However: 
`:root .light .tab ::deep button { color: red; }` becomes `.light .tab[b-2] button { color: red; }` so this **does** match.

In this way you can make styles apply dependent on parent conditions, e.g.
```
:root .light .tab ::deep button { color: white; }
:root .dark .tab ::deep button { color: black; }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @oliverholliday.

@daveabrock ... I'll wait until you advise on this scenario. FYI ... If this is a scenario that requires coverage, I likely won't reach it immediately, as I'm ⛰️⛏️😅  this week on high priority 6.0 work. I'll get to it asap.

**Comment by guardrex** [comment]
Potentially related :point_right: https://github.com/dotnet/aspnetcore/issues/25796

**Comment by oliverholliday** [comment]
> > Does :root ::deep not do the trick?
> > In general this is not something I'm supportive off, since it can introduce non-scoped rules within the scoped css and that'll cause things like bundling to become unreliable.
> > All rules in scoped css files should be scoped and not leak over, for things like that it's simple enough to define a regular css file and use the "link" tag on the component (for example)

I understand the reasoning to not use `:root ::deep` as it would allow you to "inject" css up to a higher scope which is always going to be a nightmare both for bundling and for maintainability, but also just defeats the purpose of scoping in the first place, 

The use case and examples I've listed above the CSS is still scoped to the relevant component - it's just allowing switching functionality dependent on parents, which I think is useful functionality in some cases. The alternative would be to follow the suggestion of having a separate CSS file which has no scope at all, which also defeats the purpose.

**Comment by guardrex** [comment]
We might have some qualified advice on it. I'll yield to @daveabrock (and possibly Javier later). @daveabrock, if you end up on the fence, then I'll ping Javier after RC2 releases for him to consider it further. I can't ping him before then, as he's buried in work at the moment for the 6.0 release. 🏃

@oliverholliday, I disagree with your last line tho. Global styles don't defeat the purpose of the CSS isolation feature. This feature isn't designed to completely replace global styles. Besides, there's the new `HeadOutlet` piece that could help by bringing in a stylesheet that's effectively scoped to the component.
