### ISSUE TITLE
Can't find AddGraphClient()

### ISSUE THREAD

**Issue by devlife** [dotnet/AspNetCore.Docs#23444]
Trying to follow the article but I can't find `builder.Services.AddGraphClient();`. Does this still exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @devlife ... It's consumed prior to that point in this topic. Scroll up to the earlier guidance ...

> Add a package reference to the CLIENT app's project file for Microsoft.Graph.

... that cross-links to ...

https://www.nuget.org/packages/Microsoft.Graph

... and then ...

> Add the Graph SDK utility classes and configuration in the Graph SDK section of the Use Graph API with ASP.NET Core Blazor WebAssembly article.

... which refers to https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-5.0#graph-sdk ... where you'll see the extension method.

**Comment by guardrex** [comment]
btw ... There will probably be an assessment of these Blazor security subjects in an upcoming "UE" ("user experience") pass early next year. A "UE pass" means that I'll be analyzing where content appears in the ToC (table of contents), how content is cross-linked, the specific guidance provided for each scenario, and the order in which guidance appears (e.g., we know that devs like to read our guidance top-to-bottom down the ToC, so it's best to order our coverage that way). The goal is to try and avoid the problem that you just hit where it isn't perfectly clear what order to consume guidance or how different segments of guidance are related. The work is tracked by https://github.com/dotnet/AspNetCore.Docs/issues/19286, and I think that I'll reach it (if I have management's approval to continue with those efforts) in early to mid-2022.
