### ISSUE TITLE
Add Blazor hosted WASM prerendering steps when using Azure Ad authentication

### ISSUE THREAD

**Issue by Markz878** [dotnet/AspNetCore.Docs#23441]
Please create documentation that shows the steps to use Blazor Hosted prerendering when using Azure Ad authentication. Currently the error page says that it can't get CascadingAuthenticationState cascading parameter. If I copy the builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("scope_uri");
});
the error page says that it can't perform JS interop during server-side prerendering.
My index page does not even require authorization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329a19ef-fb46-1f6b-a734-fa1c1334b1e5
* Version Independent ID: 3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2
* Content: [Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/prerendering-and-integration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Markz878 ... It isn't supported. See ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#support-prerendering-with-authentication-1

... which is cross-linked in the *Prerendering* topic at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly#additional-blazor-webassembly-resources

I'll add a cross-link to that to the WASM Security Overview topic as well. What I might do in the end is make an INCLUDE file out of that section and place a copy of the entire section in both docs. I'll make a note to myself to check on doing that when I reach that topic for more work later. Thanks for commenting on this.
