### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/AspNetCore.Docs#23450]
All links to "Enhanced diagnostic logs" are broken, there's no such section on the target page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by alex-jitbit** [comment]
Should probably link here?? https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-5.0#enhanced-diagnostic-logs

I don't know, just a suggestion

**Comment by guardrex** [comment]
Thanks @alex-jitbit ... Yes, that's right. There was a large set of changes made to how the content is organized. The content was split out into several topics, and this one got by us 😈. Thanks for calling it out. I'll fix it right now.
