### ISSUE TITLE
Is this page up-to-date

### ISSUE THREAD

**Issue by drathnow** [dotnet/AspNetCore.Docs#23470]
I was following the instruction for "PersistKeysToDbContext" on this page and found that the interface in this statement:

"The preceding code stores the keys in the configured database. The database context being used must implement IDataProtectionKeyContext. IDataProtectionKeyContext exposes the property DataProtectionKeys"

does not exist.  That is "IDataProtectionKeyContext. IDataProtectionKeyContext" does not exist.  However, the interface "IDataProtectionKeyContext" does exist with the property "DataProtectionKeys".  I discovered this after adding Microsoft.AspNetCore.DataProtection.EntityFrameworkCore 5.0.10 to my project.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0#persistkeystodbcontext)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, it's up to date. See https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.entityframeworkcore.idataprotectionkeycontext.dataprotectionkeys

**Comment by cn-ml** [comment]
I just had the same problem. Visual studio kept giving me errors like

```csharp
// EntityFrameworkCore does not exist in namespace Microsoft.AspNetCore.DataProtection
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
```

```csharp
// IDataProtectionKeyContext not found
public class AppDbContext(DbContextOptions options) : DbContext(options), IDataProtectionKeyContext;
```

Turns out, the nuget package installation was not clean somehow, I couldn't figure out the issue, because the package manager output seems to have succeeded, but my package file did not immediately show the newly installed package.

For me, restarting visual studio did the trick and the package was installed correctly then.
