### ISSUE TITLE
What about the data base structure?

### ISSUE THREAD

**Issue by Zapnologica** [dotnet/AspNetCore.Docs#23489]
There is no mention of the implications of what happens to the actual database?

We are trying to migrate from mvc 4.6.5 to .net 5 and done what you have suggested. However the database is moaning about missing columns etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db6772c4-1017-5e86-8045-8849b5dd1ad7
* Version Independent ID: bcb8d6b2-f38a-ac10-d3f2-69d4223bfd72
* Content: [Migrate Authentication and Identity to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-5.0)
* Content Source: [aspnetcore/migration/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by JochenFalk** [comment]
@Zapnologica : 

Perhaps you had the same issue I had...

In SchoolContext.cs the Discriminator property needs to be set and the table assignment for Student and Instructor needs to be removed;

//modelBuilder.Entity<Student>().ToTable("Student");
//modelBuilder.Entity<Instructor>().ToTable("Instructor");
modelBuilder.Entity<Person>().HasDiscriminator<string>("Discriminator");

If not the app is looking for missing tables. The tutorial should perhaps be updated with this addition ;)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
