### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by saha80** [dotnet/AspNetCore.Docs#23497]
[http://go.microsoft.com/fwlink/?LinkID=615859](http://go.microsoft.com/fwlink/?LinkID=615859)

https://github.com/dotnet/AspNetCore.Docs/blob/7e8a2966ef9b70418a4de3892ce17403183232e8/aspnetcore/fundamentals/localization/sample/2.x/Localization/Startup.cs#L74
https://github.com/dotnet/AspNetCore.Docs/blob/7e8a2966ef9b70418a4de3892ce17403183232e8/aspnetcore/fundamentals/localization/sample/3.x/Localization/Startup.cs#L66

**Comment by guardrex** [comment]
Looks like the best cross-link is to this ...

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime

... so I'll put that in for this old link.
