### ISSUE TITLE
Library Manager Install Command Does Not Work As Documented

### ISSUE THREAD

**Issue by bdubose** [dotnet/AspNetCore.Docs#23502]
When going through the Signal R tutorial using VS Code, the tutorial says to install LibraryManager. However, the example command provided does not include a version or a placeholder for a version. Without a version provided, the dotnet tool install command will fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Confirm that the preview SDK isn't in use on that machine that threw the error. That would probably explain it because in preview the version would be required. We don't document preview; so if that turns out to explain this, then we won't need to take further action on it.

**Comment by bdubose** [comment]
@guardrex Here is the output that I receive:

![image](https://user-images.githubusercontent.com/19719602/136869028-4e4b7043-b5b6-4ea7-b871-e561092647d3.png)
 
This is pretty odd. I grabbed .NET from here, so I don't think it's a beta version or anything:
https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.401-windows-x64-installer

**Comment by guardrex** [comment]
You might want to show them a second screenshot, too ... show them a shot with the version specified in the command and the tool getting installed ... just to confirm to them that it's the version specification that's required and hanging the install without it.

**Comment by bdubose** [comment]
I finally found something that worked -- apparently there was some cache that was left over and causing these issues. The cache wasn't wiped away when I uninstalled/reinstalled dotnet, so that's why my problems kept persisting and was only on this computer. I believe the cache I needed to remove was somewhere under the AppData directory.
