### ISSUE TITLE
Microsoft.AspNetCore.Identity.UI.Services.IEmailSender implementation

### ISSUE THREAD

**Issue by johnye2e** [dotnet/AspNetCore.Docs#23514]
Why is implementing IEmailSender recommended to send email confirmation with Identity? The interface is "not intended to be used directly from your code".

   ```
 // Summary:
    //     This API supports the ASP.NET Core Identity default UI infrastructure and is
    //     not intended to be used directly from your code. This API may change or be removed
    //     in future releases.
    public interface IEmailSender [...]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
