### ISSUE TITLE
 kestrel settings are not applied if configure KestrelServerOptions in appsettings.json file?

### ISSUE THREAD

**Issue by MM-RYO** [dotnet/AspNetCore.Docs#23528]
Are we able to configure KestrelServerOptions in appsettings.json file?
I tested the below settings, it won't work.
-- MaxRequestBodySize
-- MaxRequestHeaderCount
if I do it in C# code, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-5.0#kestrel-options)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by robinNode** [comment]
moved to https://github.com/dotnet/aspnetcore/issues/37544
