### ISSUE TITLE
This is a typo

### ISSUE THREAD

**Issue by yangzhongke** [dotnet/AspNetCore.Docs#23539]
According to rfc7118, it should be 'WebSocket'  instead of 'WebSocket**s**'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
