### ISSUE TITLE
.NET 6 update: Response Caching Middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23540]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-5.0)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by smandia** [comment]
@Rick-Anderson  I will work and update on it soon.

**Comment by smandia** [comment]
It is being worked on

**Comment by Rick-Anderson** [comment]
@smandia This one is available.

**Comment by smandia** [comment]
@Rick-Anderson Please review it
