### ISSUE TITLE
Startup command with Application dll

### ISSUE THREAD

**Issue by hugsilva** [dotnet/AspNetCore.Docs#23560]
Hello,

I would like to suggest to add a recommendation section on the documentation where we explain how to add a start up command to run the Application dll.
Some times when the Azure App Service restarts the default dll is picked up and it does not load the deployed application and reverts back to the default Hostingstart.dll. The recommendation given by the Product Group is to add a custom startup command with the correct application dll.
![image](https://user-images.githubusercontent.com/92784769/137878825-2c7d8c9a-acce-4236-b756-2564a95a52ba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-5.0&tabs=visual-studio#publish-and-deploy-the-app)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
