### ISSUE TITLE
Why should I use only Newtonsoft.Json serialization if API is generating OpenAPI docs?

### ISSUE THREAD

**Issue by julealgon** [dotnet/AspNetCore.Docs#23576]
The section that talks about differences between Newtonsoft.Json and System.Text.Json mention this as a reason to continue using Newtonsoft.Json instead of the new default serializer:
> Continue using the Newtonsoft.Json-based formatters if the app:
> - ...
> - Generates OpenAPI documentation.

From what I can tell, Swashbuckle at least works fine with System.Text.Json, and I'd imagine other solutions like NSwag do too.

Why is there an explicit mention to use Newtonsoft in the documentation when working in an API that produces OpenAPI docs? Is this outdated information, or is there something about it that the documentation is not explaining?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-5.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JamesNK  should we  remove Continue using the Newtonsoft.Json-based formatters if the app: Generates OpenAPI documentation.

**Comment by pranavkm** [comment]
I think this was a point-in-time thing when libraries hadn't updated to support STJ. We should remove it now.
