### ISSUE TITLE
A few points needed to be addressed

### ISSUE THREAD

**Issue by BrokenShoeLace** [dotnet/AspNetCore.Docs#23580]
First of all, the information in these pages is outdated and the language has changed since it was written.

Secondly, and more importantly, there are no semantics so people with reading impairment wouldn't be able to follow this tutorial. Because of this, the code is not fully W3C validated which is bad practice.

The project relies heavily on Bootstrap, which as people are aware is not a lightweight solution with lots of clashing classes relying on **!Important**. You can achieve more by using Flexbox/Grid yourself and ditching Bootstrap.

The authors can say this is just an example, and they are correct but point 2 above is very important.

There is one very important lesson here: any time you require **!Important** in your CSS, your code isn't correct. That sums up Bootstrap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Would you like me to transfer this issue to https://github.com/dotnet/Scaffolding/issues ? We just document the generated code, we didn't create it.
