### ISSUE TITLE
Some links don't work

### ISSUE THREAD

**Issue by alex47** [dotnet/AspNetCore.Docs#23595]
Links for 
 - OnInitialized{Async}
 - OnParametersSet{Async}
 - OnAfterRender{Async}

don't work at all.
When I click on them they don't jump to their section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#after-component-render-onafterrenderasync)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alex47 ... This is a known issue that will be partially resolved when 6.0 releases and the 6.0 docs become the default doc set. The problem will be permanently resolved next year when we adopt a new content versioning system for docs.
