### ISSUE TITLE
URL encoded path segments?

### ISSUE THREAD

**Issue by plettb** [dotnet/AspNetCore.Docs#23617]
I ran into this problem today while hosting on Azure.  https://stackoverflow.com/questions/37178949/how-do-i-allow-url-encoded-path-segments-in-azure.  That post is over five years old, but still doesn't appear to have a good solution.  Is there a setting or configuration in Azure that addresses this?

Is there anything I can do besides going to something like Base64 encoding/decoding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?highlight=route&view=aspnetcore-6.0#template-routes)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
