### ISSUE TITLE
Not detailed explanation of application parts.

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#23657]
Hello, guys.
I just tried to reference assembly with controllers, and they got discovered by the host (.NET 5), so it's not clear why I would need application parts in this case. Are application parts relevant mostly for the situations when we need to deal with embedded resources?

Can I also register controllers with their own settings?
```CSharp
services.AddControllers()
    .AddNewtonsoftJson(
        options => options.SerializerSettings.ReferenceLoopHandling =
            Newtonsoft.Json.ReferenceLoopHandling.Ignore
    );            
```
For example one app part may expect Newton.Json, whereas another one requires `System.Text.Json` serializer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Share controllers, views, Razor Pages and more with Application Parts in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
