### ISSUE TITLE
.NET 6 update: Configure options for the ASP.NET Core Kestrel web server

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23653]
Also add [Emit KestrelServerOptions via EventSource event](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04754ed9-3508-6f40-fd7f-8e4a46e538af
* Version Independent ID: 5a5a34c5-1c75-ff17-b3d6-762194391319
* Content: [Configure options for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
I think "Emit KestrelServerOptions via EventSource event" should be added to the Kestrel diagnostics article instead of this one. What do you think @Rick-Anderson?
