### ISSUE TITLE
Hash passwords: Document Microsoft.AspNetCore.Identity.PasswordHasher instead of obscure crypto API

### ISSUE THREAD

**Issue by Socolin** [dotnet/AspNetCore.Docs#23666]
There is a `Microsoft.AspNetCore.Identity.PasswordHasher` that look a lot more simple to use than what is currently documented with `KeyDerivation.Pbkdf2` but there is no documentation / example for this.

I thinks it would be nicer to have a simple example with PasswordHasher for most common use case / details and an example /details about `SuccessRehashNeeded`, before the complex example with KeyDerivation.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.passwordhasher-1?view=aspnetcore-5.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by Socolin** [comment]
Hello,

The lack of activity is that I got no answer to my suggestion, can you re-open this ?

**Comment by Rick-Anderson** [comment]
See https://andrewlock.net/exploring-the-asp-net-core-identity-passwordhasher/

**Comment by Socolin** [comment]
> See https://andrewlock.net/exploring-the-asp-net-core-identity-passwordhasher/

I know how it works and how to use it.

I just want the official documentation to refer a simple API instead of scaring developers with some hard-to-understand code.
Moreover, the documentation does not explain the iteration count part and that the passwords should be rehash over time cause compute power increase over time.

If there is a simpler method which is less error prone to a complex subject as password hashing, why not documenting this first ?
