### ISSUE TITLE
Subcategories for better filtering of Kestrel logs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23665]
Add [Subcategories for better filtering of Kestrel logs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-5/#subcategories-for-better-filtering-of-kestrel-logs)
Check the what's new version first.

Share or link this with Kestrel docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 60754](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60754)

**Comment by tdykstra** [comment]
Fixed by #23319
