### ISSUE TITLE
.NET 6 update: prefer new Use middleware extension method

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23688]
Add a new `app.Use` overload that requires users to pass the `HttpContext` to the `next` function which will save 2 per-request allocations over the previous extension method.

## Customer Impact

Less per-request allocations when using simple middleware.

See https://github.com/dotnet/aspnetcore/pull/31784

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  or @smandia would one of you be able to write a sample app showing the new `app.Use` overload?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson sure. Will take a look at this soon 🙂
