### ISSUE TITLE
`dotnet dev-certs` not working as intended on Linux, docs could use a notice

### ISSUE THREAD

**Issue by PhilParisot** [dotnet/AspNetCore.Docs#23686]
The instructions for

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communication

and 

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux

unfortunately do not work on Ubuntu LTS 20.04 and I suspect a few other Linux distributions as well. There are two open issues regarding this:

https://github.com/dotnet/aspnetcore/issues/7246

https://github.com/dotnet/aspnetcore/issues/32842

This comment worked as a workaround for me: https://github.com/dotnet/aspnetcore/issues/7246#issuecomment-744022452

But the docs were a major source of confusion for me because I repeatedly followed the steps and I could not get the certs to be trusted by Chrome and Firefox on Ubuntu 20.04.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 58139](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58139)

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
@serpent5  I created `P0.5` for higher priority but not urgent (`P0`). .NET6 updates are all higher than `P0.5`
