### ISSUE TITLE
wrong word

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#23692]
here:
"Most of the flights aren't rendered because they fall outside of the height of the `<div>` element."
should be aren't **seen**
sentence before: 
"Instead of rendering the entire list of flights at once, replace the foreach loop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f4ab8b4-4d2e-9e1b-793e-dbb17f6d694d
* Version Independent ID: 26ed2425-63ec-e206-edcb-e51f17edb844
* Content: [ASP.NET Core Blazor component virtualization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/components/virtualization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/virtualization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @omuleanu ... I'll patch that right now.
