### ISSUE TITLE
Why render/not render when having/not having ChildContent set?

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#23704]
for this line:
"The second Expander component's Expanded value isn't reset because no child content is rendered in the second component."

I don't understand why is that when the `Expander.ChildContent` property is set, the component is rendered when calling StateHasChanged on the parent

what's the link between a component having `ChildContent` set and getting rendered on parent's `StateHasChanged`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#overwritten-parameters-1)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We can explore fleshing it out further. I'll ping Steve later this month to look and see if he'll supply some additional information. Leave this issue open for now.

**Comment by guardrex** [comment]
**UPDATE**: Sorry for the delay. It wasn't possible to converse with Steve on this prior to the holiday season. We'll take a look at this in 22Q1 when everyone gets back 🏖️.

**Comment by SteveSandersonMS** [comment]
The diffing system re-renders child components if their parameters might have changed.

 * For parameters of known immutable primitive types (strings, bools, ints, and a few others), the diffing system explicitly checks if they have changed and can skip re-rendering this child if none of them have. That's what's happens with your Expander component that only receives a bool.
 * For all other parameter types, the framework can't know if the value has mutated in some way, so it has to re-render the child. For example your Expanded that takes a ChildContent - this is of type RenderFragment which is a delegate that refers to other mutable objects (which logically makes sense - the render fragment's output can change over time), so in this case the framework does re-render that one.
