### ISSUE TITLE
Kestrel Http/3 localhost

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#23700]
The "Localhost testing" section is inaccurate. It turns out that localhost isn't the problem, the real issue is that browsers won't do HTTP/3 with self-signed certs like the Kestrel dev cert. There are workarounds but they're complicated.

@JamesNK can you share the workaround here? Or can we link to instructions elsewhere if we think it's too complex?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57282931-0741-9ae0-1bc3-1918160769e2
* Version Independent ID: d8ff0551-6287-7921-b18d-2cad70fce012
* Content: [Use HTTP/3 with the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/http3.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/http3.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @wtgodbe
* Microsoft Alias: **wigodbe**

**Comment by JamesNK** [comment]
The workaround is really hard.

> .\chrome.exe --user-data-dir=c:\Temp\chrometemp --no-proxy-server --enable-quic --origin-to-force-quic-on=www.kestrelhttp3.com:443 --host-resolver-rules='MAP www.kestrelhttp3.com:443 127.0.0.1:5001' --ignore-certificate-errors-spki-list=usAHwUNu8W7Q/aV3QQFRhtL118F7yJBTpVbfXF0bbw4= --log-net-log=c:\Temp\chrometemp\chrome.json --net-log-capture-mode=IncludeSensitive --quic-version=h3 https://www.kestrelhttp3.com

Getting this bit - `--ignore-certificate-errors-spki-list=usAHwUNu8W7Q/aV3QQFRhtL118F7yJBTpVbfXF0bbw4=` depends on your cert and requires getting a value that is deep in the cert and encoding it a certain way.

I think it is too hard to do reliably.
