### ISSUE TITLE
Wrong NuGet package referenced (Microsoft.EntityFrameworkCore.SqlServer

### ISSUE THREAD

**Issue by breusshe** [dotnet/AspNetCore.Docs#23705]
In the Add a Database Context => Add NuGet packages section of this tutorial, the screenshot shows the package to install as Microsoft.EntityFrameworkCore.SqlServer rather than the correct library Microsoft.EntityFrameworkCore.InMemory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You're looking at an old tutorial. Use the version selector to see the current version.

**Comment by Rick-Anderson** [comment]
@breusshe  how did you end up on the old version?

**Comment by breusshe** [comment]
I selected it.  I have a project that has a requirement to use .NET Core
v3.1

**Comment by johanlindfors** [comment]
This is still flawed. Even though I have chosen 7.0 the tutorial asks me to install .SqlServer and not the .InMemory package.
