### ISSUE TITLE
Expanded property public is only used once privately

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#23715]
in the second `Shared/Expander.razor` (fixed)
the property `Expanded` has a public `get` which is only used once in `OnInitialized`
and it makes no sense to use it after because it won't have the value of the private `expanded`
so we can make it `private get`, because there's no point/intention to use it for any other reason.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#overwritten-parameters-1)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @omuleanu ... We'll take this one up after the 6.0 release. I'd like to have Steve look at this before we make changes, and he can't be asked about this at this time. He (and everyone) is 🏃🏃🏃🏃🏃😅 right now for the 6.0 release. It's been scheduled for a look as soon as we get past the release. It won't get lost. Thanks for the comment.

**Comment by guardrex** [comment]
**UPDATE**: Again, sorry for the delay here @omuleanu ... After a big round of work by the PU right after 6.0 was released (the usual flood of issues appeared right after 6.0 went into GA), they all bugged out for holiday vacations 🏖️😄 .... yeah ... there are only crickets 🦗🦗🦗 over there now 😄. We'll pick back up in 22Q1 with these issues and get feedback from engineering, including for your suggestion here, which seems reasonable to me.
