### ISSUE TITLE
"offline_access" scope with AddOidcAuthentication?

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/AspNetCore.Docs#23712]
The other authentication pages mentions the "offline_access" scope.
But this page does not mention it. Can the "offline_access" scope be used with this OpenID Connect authentication? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vanillajonathan ... Yes, we just don't cover/list them all.

**Comment by vanillajonathan** [comment]
Maybe the documentation could mention that?

So the "offline_access" scope works when using `AddOidcAuthentication` just like with the others? The users will stay logged in?

**Comment by guardrex** [comment]
They all work if the IP supports them. I don't think we need to list them all. The IPs documentation should cover the scopes or they'll refer to the OIDC spec as their documentation of them.

**Comment by guardrex** [comment]
This whole node is due for a major overhaul on https://github.com/dotnet/AspNetCore.Docs/issues/19286. Every section will get careful consideration for what's covered/not covered. I marked this issue on the tracking issue for review when the topic is reached.
