### ISSUE TITLE
Error when Scaffolding an MVC Controller with views, using Entity Framework

### ISSUE THREAD

**Issue by ianq22** [dotnet/AspNetCore.Docs#23722]
So far I've followed the tutorial to the letter, using Visual Studio Version 16.11.5. When I reach the step on scaffolding out the MVC Controller for Movie App, I keep hitting the following error:

Error there wa an error running the selected code generator: 'Method 'Create' in type 'Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerSqlTranslatingExpressionVisitorFactory' from assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=3.1.20.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'' does not have an implementation.'

I've tried deleting and reinstalling the packages, but no dice. I'm running on .NET Core 3.1 which matches up with the versioning mentioned in the tutorial, so I'm curious what I could have done wrong or missed to hit this point. Any help is appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you try ASP.NET 6 or at least V 5?

**Comment by Rick-Anderson** [comment]
We don't support the scaffolder, just the document. You could open an issue at https://github.com/dotnet/Scaffolding/issues but I think  you're better off trying a newer version.

**Comment by ianq22** [comment]
So I totally rebuilt the project following the tutorial but this time with ASP.NET 5. This time it would seem I'm getting a different error saying 'The RPC server is unavailable'. When you run through your own document on the most recent Visual Studio you can confirm that you do not, in fact, have any problems when it comes to scaffolding out the MVC controller?
