### ISSUE TITLE
Should include an example other than a 404. I'm stuck on how to do this.

### ISSUE THREAD

**Issue by NealCallaghan** [dotnet/AspNetCore.Docs#23734]
Should include an example other than a 404. I'm stuck on how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9421feee-5207-e379-00fb-847cc880014c
* Version Independent ID: 8415adee-793e-2ba7-b97b-672b493ba42b
* Content: [Test ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/test/middleware?view=aspnetcore-5.0)
* Content Source: [aspnetcore/test/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Tratcher
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @NealCallaghan. Thanks for the feedback. What exactly is it that you're getting stuck with here?

**Comment by jovton** [comment]
Hi. I agree with @serpent5 's sentiment.

The title is called "Test ASP.NET Core middleware", and the examples contain references to the type ```MyMiddleware```, but we're not given any insight as to the context of what is being tested, i.e. we don't know what ```MyMiddleware``` look like.

What, for example, could a person do to check whether or not the "next" request delegate has been called (under certain conditions)?

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
