### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by michalmika** [dotnet/AspNetCore.Docs#23746]
After following the first two steps, On "Test Register and Login" I was able to Register but received a "invalid login" when was trying to login. What might be the problem? (email and password were correct)

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
