### ISSUE TITLE
Update section Accessing options during startup

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23751]
See [Accessing options during startup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0&branch=pr-en-us-23750#accessing-options-during-startup)
That section was Removed from the .NET 6 version. 

@serpent5 : Do a full review of V6 and look at open issues for this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0&branch=pr-en-us-23750)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@halter73  See [Accessing options during startup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0&branch=pr-en-us-23750#accessing-options-during-startup)
That section was Removed from the .NET 6 version. 

What do you want for that section in the .NET 6 version of this article?

**Comment by halter73** [comment]
We should show the ability to read options from `app.Services`. 

```c#
var optionsAccessor = app.Services.GetRequiredService<IOptionsMonitor<MyOptions>>();
```
