### ISSUE TITLE
Update tutorial images to show LTS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23771]
Update all the tutorial images that currently show .NET 6 (Preview) to the correct LTS text.

**Comment by wadepickett** [comment]
Note to self on an example of this:

![image](https://user-images.githubusercontent.com/10985336/140671244-fa68f98d-9366-44a3-8a04-2852e6a580c6.png)

**Comment by wadepickett** [comment]
Will have these in soon today, updated .NET Hub page at the moment, almost done.
