### ISSUE TITLE
small clarification

### ISSUE THREAD

**Issue by sterneric** [dotnet/AspNetCore.Docs#23777]
I followed most of the steps and debugging (wasm) does not work but I have reported that issue as well 

It would take less time to follow the steps here if 

            #if DEBUG
                Thread.Sleep(10000);
            #endif

was changed to 

            #if DEBUG
                System.Threading.Thread.Sleep(10000);
            #endif

Unless system.threading is on a using statement the code, as supplied in the article, won't compile. 

thanks and no follow up needed (and obviously I'm not good with c# and too jaded to try and learn it to an expert level)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @sterneric ... I've noted this on my tracking issue for performing document overhauls in 22H1.
