### ISSUE TITLE
Outdated code in the `Built-in JWT authentication` section

### ISSUE THREAD

**Issue by mmarinchenko** [dotnet/AspNetCore.Docs#23785]
I think the following line can be safely deleted since MVC has nothing to do with the SignalR topic.

```csharp
public void ConfigureServices(IServiceCollection services)
{
    <...>

    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1); // <- this one

    <...>
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by serpent5** [comment]
Hi @mmarinchenko. Thanks for the feedback. The sample application uses both SignalR and MVC, but you could happily remove the line from your own code if it doesn't use MVC.

**Comment by mmarinchenko** [comment]
@serpent5 I'm sorry if I didn't make myself clear enough.

1. The `.SetCompatibilityVersion(CompatibilityVersion.Version_2_1)` call is outdated. This function should not be used starting from .NET Core 3.1+. It exists only for compatibility reasons and does nothing.
See https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version for some details.

2. It's quite obvious that the mentioned code example does not use MVC at all. What makes you think otherwise?

**Comment by serpent5** [comment]
Hi @mmarinchenko. Thanks for clarifying.

- Yes, I agree that the sample code itself is outdated. That will need to be updated.
- The sample that's associated with this topic includes an [`AccountController`](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz/sample/Controllers/AccountController.cs). It's not shown in the topic you've been reading, but it is part of the sample it references.

**Comment by mmarinchenko** [comment]
Oh, I see. Thanks for the link!

The problem is AccountController doesn't mentioned in any SignalR topic, so this confused me.
