### ISSUE TITLE
Blazor's tutorial is unclear

### ISSUE THREAD

**Issue by liangpeihui** [dotnet/AspNetCore.Docs#23783]
[Enter feedback here]

Blazor's tutorial is unclear, even after reading it, I don’t know the underlying details.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by liangpeihui** [comment]
Why not just put the source code？

**Comment by guardrex** [comment]
Hello @liangpeihui ... This isn't a tutorial, it's a reference topic. Even if it were a tutorial, we still wouldn't have that level of detail in the documentation. You can access the reference source for Blazor in the product unit's repo at ...

https://github.com/dotnet/aspnetcore/issues
