### ISSUE TITLE
appsettings / Authority value needs a '/' between the B2C instance and domain

### ISSUE THREAD

**Issue by bizframe** [dotnet/AspNetCore.Docs#23780]
appsetting.json file entries that gets generated is on lines of what is mentioned on this page.

"Authority": "{AAD B2C INSTANCE}{DOMAIN}/{SIGN UP OR SIGN IN POLICY}",
**However, note that this does not work**. 
We need a '/' between the B2C instance and domain - "{AAD B2C INSTANCE}**/**{DOMAIN}"
Example mentioned does have a / . 
So the command line generator and documentation seem out of sync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce89fc06-2c18-fbf8-0ac5-f50d41a67d8a
* Version Independent ID: 490b7aec-0d31-9032-cb1d-ffcdfea5c976
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @bizframe ... Looks like just a typo. I'll fix it either this evening or first thing Monday morning.

**Comment by guardrex** [comment]
Actually ... not really a 🐛 ... just confusing. The `{AAD B2C INSTANCE}` includes the forward slash, so the fix here is to call that out and not have readers get confused by it not appearing there. I'll fix this with an instruction or a NOTE right there to call it out. Thanks for mentioning it, @bizframe.
