### ISSUE TITLE
DTO example does not compile and missing full implementation

### ISSUE THREAD

**Issue by tonysurma** [dotnet/AspNetCore.Docs#23803]
In the 'Prevent over-posting' section.  The TodoItemDTO code in both the standalone block showing the object definition as well as the full code sample to copy/paste for Program.cs is missing and Id member.  without it the code will not compile as the public constructor of the DTO that takes a Todo cannot assign 'Id'

Adding this line below to TodoItemDTO fixes the issue
`public int Id {get; set; }`

Further to complete the example the return of the following methods needs to be updated to use TodoItemDTO (currently they return Todo objects and expose the secrets:

- `app.MapPost("/todoitems"...`
- `app.MapDelete("/todoitems/{id}"...`

Thanks for the helpful tutorial, just used it to learn this topic after the launch today

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tonysurma thanks for bringing this to our attention.
