### ISSUE TITLE
Migration doc between LTS versions

### ISSUE THREAD

**Issue by k3davis** [dotnet/AspNetCore.Docs#23817]
It would be tremendously helpful if documentation was provided to migrate between LTS versions without having to migrate to each interim version (especially since all those workloads are optional/additional installs we otherwise don't need). For example, "Migrate from ASP.NET Core 3.1 to 6.0" in this case. Thanks for consideration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@k3davis thanks for the suggestion. Hopefully we can get lots of 👍🏿 so we can increase the priority of this request.
