### ISSUE TITLE
Missing code for IAsyncDisposable section

### ISSUE THREAD

**Issue by ericmutta** [dotnet/AspNetCore.Docs#23827]
In the [IAsyncDisposable supported](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#iasyncdisposable-supported) section, towards the end and below the words **"Awaits DisposeAsyncCore, shown in the following code"**...there doesn't seem to be any code in the box:

![image](https://user-images.githubusercontent.com/20465797/140999641-8e6d3d3d-48af-44a8-94f6-e80f220b2123.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ericmutta thanks for letting us know. There was a bunch of unnecessary code that got removed on review.

**Comment by Rick-Anderson** [comment]
Thanks again @ericmutta , fix should be live in 5 minutes.

**Comment by ericmutta** [comment]
Always a pleasure @Rick-Anderson and I can see the fix is already live :+1: 

Super excited about VS2022 and ASP.NET on .NET 6. Thanks to all of you on the team for the hard work you've done to make this possible (...and I hope the Razor editor evolves rapidly because its pretty buggy right now, with autocomplete mangling text in nearby lines).
