### ISSUE TITLE
WebApplicationFactory<TStartup>: Program is inaccessible!

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#23837]
I am migrating my existing ASP.Net 5 to 6 and bump into the finla hurdle of integration test projects.

Following the document, I added the following code snippet to the .csproj which contains the top-level statements:

```
<ItemGroup>
    <InternalsVisibleTo Include="Web.Api.Integration.Tests" />
</ItemGroup>
```
And change all references to `Startup` to `Program` in my test project. However, building the solution bumps into `Program is inaccessible due to it's protection level`!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated from ASP.NET Core 5.0 to the the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @khteh. Have you tried adding the following, from the example, to your `Program.cs`:

```csharp
public partial class Program { }
```

**Comment by khteh** [comment]
Yes, I have.
