### ISSUE TITLE
Exclamation mark on the end of method argument

### ISSUE THREAD

**Issue by mwinkler** [dotnet/AspNetCore.Docs#23839]
Hi
On section "Test with WebApplicationFactory or TestServer", chapter "ASP.NET Core 6", line

```await context.Response.WriteAsync(helloService.HelloMessage!);```

Is a exclamation mark on the end, witch seems wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated from ASP.NET Core 5.0 to the the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @mwinkler. That's the [! (null-forgiving) operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving). In this example, [`IHelloService.HelloMessage` is nullable (`string?`)](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples/samples/Web6Samples/IHelloService.cs#L3), but we know in the example that it won't be `null` when we pass it into `WriteAsync`.

@Rick-Anderson The examples here switch between `public string? HelloMessage {  get; set; }` and `public string HelloMessage => ...;`. From what I can see here, the `MockHelloService` won't compile. Do you want me to fix this up?
