### ISSUE TITLE
Blazor CSS isolation project bundle filename

### ISSUE THREAD

**Issue by liangpeihui** [dotnet/AspNetCore.Docs#23849]
[EDIT by guardrex to shorten the issue title]

> A project bundle is created with the convention {STATIC WEB ASSETS BASE PATH}/Project.lib.scp.css?

![image](https://user-images.githubusercontent.com/79532375/141143960-c42fc6e6-60ad-48b4-85d1-55762c8f0b14.png)
![image](https://user-images.githubusercontent.com/79532375/141144089-f375cb6b-8085-4c28-95c5-5dc4d9afa7d0.png)
i can't find the file.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0#css-isolation-bundling-1)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @daveabrock
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @liangpeihui ... It looks like there was a change in the naming of the file that we didn't get into the docs. You have the right path, and that is the right file.

**Comment by liangpeihui** [comment]
*.styles.css is in the same path of referenced razor class library. so why the generated *.styles.css contains the following?
![image](https://user-images.githubusercontent.com/79532375/141235476-581d8530-bc51-4cb0-b590-b01e7ddacfba.png)
the static web assets path of the referenced razor class library is "/whenpublish/reltowwwroot/".

**Comment by liangpeihui** [comment]
![image](https://user-images.githubusercontent.com/79532375/141235828-9f30fdb6-893e-42ed-8bb8-d704dab0ba8b.png)
In fact, the CSS file of the referenced project is not imported in wwwroot/index.html and Pages/_Host.cshtml, but in the bundled css file of the project.
