### ISSUE TITLE
.NET 6: Host ASP.NET Core in a Windows Service

### ISSUE THREAD

**Issue by YehudahA** [dotnet/AspNetCore.Docs#23847]
This page is outdated and not correct with aspnet 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Wraith2** [comment]
It would be very useful to get this documentation updated. 
I've tried to put together a way to host blazor server in worker designed to run as a windows service in order to have a service host it's own small web interface but I've been unable to get anything that works.

**Comment by guardrex** [comment]
I'm working this one as a crossover issue for Blazor, too. I'll investigate a few reported errors as I work through the updates. Updates include removing the 2.x pieces and adding bits for 5.x and 6.x. I'll deal with PS script updates. Note that the PS updates move all guidance to working PS 7 commands. *We don't document old tooling.*

**Comment by guardrex** [comment]
Sorry folks! Change of plans. One of the docs team members will take care of the general updates first (3/4 open issues), then I'll come in later and address the Blazor-specific issue later.

**Comment by guardrex** [comment]
Note to the doc author working this issue. There's a community-supplied sample on ...

**Minimal API windows service sample**
https://github.com/dotnet/AspNetCore.Docs/pull/25037

... that is here but isn't added to the text of the topic. I felt it could be merged and then tied in here when this issue is worked.
