### ISSUE TITLE
Error with dotnet 6.0 (samples/6.0/SwashbuckleSample)

### ISSUE THREAD

**Issue by jefflindholm** [dotnet/AspNetCore.Docs#23850]
`dotnet build` gets the following errors, lots of 'swagger' examples that I have found get the same errors (sorry if there is a simple fix for this I am missing)

C:\Users\jeff\dev\AspNetCore.Docs-main\aspnetcore\tutorials\web-api-help-pages-using-swagger\samples\6.0\SwashbuckleSample\SwashbuckleSample.csproj : error NU1100: Unable to resolve 'Microsoft.EntityFrameworkCore.InMemory (>= 6.0.0-rc.2.21480.5)' for 'net6.0'.

C:\Users\jeff\dev\AspNetCore.Docs-main\aspnetcore\tutorials\web-api-help-pages-using-swagger\samples\6.0\SwashbuckleSample\SwashbuckleSample.csproj : error NU1100: Unable to resolve 'Swashbuckle.AspNetCore (>= 6.2.3)' for 'net6.0'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
Hi @jefflindholm. I just double-checked this, and it all appears to work fine for me. I even deleted all my cached NuGet packages to make sure. As a first step, can you run `dotnet nuget list source` and double-check that you see an enabled source for `nuget.org`?

**Comment by jefflindholm** [comment]
That was it thanks, I forgot I was on the work network and nuget packages come from our manager, sorry

**Comment by serpent5** [comment]
No worries. I'm glad it's working for you now.
