### ISSUE TITLE
Typo in header

### ISSUE THREAD

**Issue by blockingHD** [dotnet/AspNetCore.Docs#23860]
There is a typo in the 'Services injected into Program.c' it should be 'Services injected into Program.cs'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Thanks for reporting this, @blockingHD.

Would you be interested in fixing this via a Pull Request? If you'd like to, select the Edit pen icon at the top-right of the article:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again, make your changes, then select the "Commit Changes" button and follow the instructions.

**Comment by blockingHD** [comment]
Sure! :)

**Comment by serpent5** [comment]
Hi @blockingHD. Someone else has provided a fix for this, which I've linked above. Please do consider contributing other edits/changes as you see fit. Thanks again for taking the time to report this.
