### ISSUE TITLE
VS 2022 Hot Reload with debugger

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23864]
When VS 2022 can do it, remove the following remark ...

> In Visual Studio 2022 GA (17.0), Hot Reload is only supported when running without the debugger.

I'm going to track this one on the Blazor.Docs project so that I don't lose it 😄.

### **UPDATE 12/28**

Checked with VS release 17.0.4, and Hot Reload is working, including with the debugger and with code changes in a component of a Blazor Server app with the debugger running. **_However_**, it seems to be working **when the file is saved in the IDE** with the **Hot Reload on File Save** option in use. That's the approach that DR demoed in the Standup. AFAICT, physically reloading the page in the browser per https://github.com/dotnet/aspnetcore/issues/38809#issuecomment-989019093 **_is NOT required_**. The topic here currently doesn't mention saving the file specifically to trigger the automatic browser reload, so we might add a bit more guidance when we remove the NOTE about running with the debugger. I'll check with Tanay when we get back from the 💃🕺 *holidays* 🎆🥳 for the latest info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Version Independent ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Content: [.NET Hot Reload support for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/hot-reload.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/hot-reload.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ldsenow** [comment]
My personal experience is to use dotnet watch cli for hot reload is much better than vs' at the moment.

**Comment by guardrex** [comment]
I'll be checking in with the product unit within a few weeks on the latest status. Everyone just returned from the holidays, and they're still **_digging out of mountains of email_** ⛏️⛰️📧😅.

**Comment by vchirikov** [comment]
> My personal experience is to use dotnet watch cli for hot reload is much better than vs' at the moment.

I can't attach to a process runned with `dotnet watch` with vs code (vsdbg)

Error:
```
Failed to attach to process: Attaching a .NET debugger to this process is not allowed because code changes have been applied. The process must be restarted to allow debugging.
```

After `dotnet watch` restarted the process (like after `touch src/Project.csproj`) I can attach, but debugger completely unusable (hit a breakpoint, but `continue` doesn't work).

Where I should create an issue? (MIEngine or ???) Or debugging with vsdbg shouldn't work at all with `dotnet watch`?

**Comment by guardrex** [comment]
I think before thinking about opening an issue that devs should search the open ones. I haven't reached this yet to discuss it with any of the PU members or management, but I do see **_a bunch of open, actively discussed_** PU issues. Read these and see if they match your situation with Hot Reload and debugging ...

https://github.com/dotnet/aspnetcore/issues?q=is%3Aissue+is%3Aopen+label%3Aarea-blazor+hot+reload

**Comment by guardrex** [comment]
**UPDATE (4/15)**: Whatever was wrong seems to be fixed. Local testing is 👍 and 🎉 for Hot Reload with the debugger. Removing the remark now.

**Comment by Engincode** [comment]
I found the solution. [](http://www.engincode.com/-solved-visual-studio-2022-hot-reload-not-working-xamarin-forms-xaml)
