### ISSUE TITLE
great tutorial thanks!

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/AspNetCore.Docs#23879]
:-)

**Comment by guardrex** [comment]
Thanks @SogoGolf! 🎸

btw -- It's easier for us to see which topic you're referring to when you open an issue from the **This page** feedback button and form, which adds metadata to the issue indicating the topic and pings the author automatically.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
