### ISSUE TITLE
Example for UseWebRoot throws exception

### ISSUE THREAD

**Issue by ascott18** [dotnet/AspNetCore.Docs#23873]
The example under "Change the web root" throws an exception. I'm not sure why the UseWebRoot method even exists if you can't use it.

![image](https://user-images.githubusercontent.com/5017521/141379948-5d15a5a0-94f3-4ead-b476-fda024a5259c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated from ASP.NET Core 5.0 to the the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#cii)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ascott18  thanks for the report, confirmed.

@serpent5  can you fix that snippet? It requires the [CreateBuilder(WebApplicationOptions)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createbuilder?view=aspnetcore-6.0) overload.

**Comment by Rick-Anderson** [comment]
@ascott18 the updated sample will be live in a few minutes.
