### ISSUE TITLE
App base path works locally, but not as an IIS Sub App

### ISSUE THREAD

**Issue by mkerchenski** [dotnet/AspNetCore.Docs#23875]
I have an ASP.NET 4 site and my goal is to create a new hosted blazor web assembly app that runs in a subdirectory of the ASP.NET 4 site running as an application.  I've created the blazor app locally and tested it and everything works.  I followed all the instructions in the App base path section.  I even set up the `--pathbase` command arg, and changed the launch url to app in the launchSettings.json file.  It's working well on my local machine from VS 2022 and from a command prompt.

Then I took the existing site in IIS and add a sub app.  I updated the app pool to use no managed code.  I published the server project within my blazor app and moved it to a directory that is referenced from the IIS sub app.  The blazor webassembly runs well.  The site loads, but none of the server apps (controllers, api endpoints) work.  The source looks like it's referencing app/fetchdata, but the endpoint isn't there.  It's returning a 404 error.  Also, when you load any of the secondary URLs within the app subdirectory (like app/counter) from the browser url it fails.  It works when you navigate from within the app, but not when you link to the page.

I can't find anything on this topic online.  Not sure if you can help, but I'm not sure how to proceed.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=visual-studio#app-base-path-1)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mkerchenski ... I'm not sure that that's a supported scenario. Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... please add a `cc: @guardrex` to the bottom of your opening comment so that I can follow the discussion.
