### ISSUE TITLE
MvcNewtonsoftJsonOptions.OutputFormatterMemoryBufferThreshold sample code is under wrong heading

### ISSUE THREAD

**Issue by madhub** [dotnet/AspNetCore.Docs#23887]
MvcNewtonsoftJsonOptions.OutputFormatterMemoryBufferThreshold sample code is under wrong heading
```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages()
            .AddNewtonsoftJson(options =>
            { 
                options.OutputFormatterMemoryBufferThreshold = 48 * 1024;
            });

var app = builder.Build();
```

![image](https://user-images.githubusercontent.com/8907962/141521514-513e39fd-a283-4c1f-8f40-402394ee4dd0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@madhub thanks for reporting this. I got those two snippets swapped. Fix will be live in 10 minutes or less.
