### ISSUE TITLE
What about Entity Framework code like CreateDbIfNotExists and such ?

### ISSUE THREAD

**Issue by stephenhauck** [dotnet/AspNetCore.Docs#23880]
How / what do we do for things like CreateDbIfNotExists and such with Entity Framework Core ...
Trying to follow the tutorial here  https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated from ASP.NET Core 5.0 to the the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's a better question for the EF folks.

**Comment by stephenhauck** [comment]
Not really … it’s an “architecture” question for asp core people … you merged the two (program.cs and  startup.cs) … what did you expect us to do in migrating ?

**Comment by stephenhauck** [comment]
@Rick-Anderson 
Why is there push back on this ... either you thought ahead and actually tried to merge the two files before doing it or you didn't and you should to make clear what your usage intentions were in doing so.

**Comment by stephenhauck** [comment]
@Rick-Anderson 
I'm going to stop reporting documentation issues because apparently expecting information on how to use something correctly and not being happy with basically auto generated docs is wrong in some way ...

How do we explain it to our management and co-workers if you don't provide the information needed ?

Merging the two files is a major change .... even though you may not think so ...

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio#create-the-database
It's no different for MVC
cc @serpent5
