### ISSUE TITLE
ArrayExample is referred to but to find out what it is requires searching the codebase linked to in github

### ISSUE THREAD

**Issue by BonnieSoftware** [dotnet/AspNetCore.Docs#23892]
ArrayExample is defined in the example but it isn't obvious from looking at the examples what ArrayExample is supposed to be. You have to download the linked to example to find the 3 lines of code that would have been useful to include in the examples for completeness.

```
public class ArrayExample
{
    public string[]? Entries { get; set; }
}
```

For the sake of saving some time when reading the docs, would it be possible to include this class within the example code somewhere on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BonnieSoftware  good suggestion, thanks for taking the time to open this issue. I think it's actually
```
    public class ArrayExample
    {
        public string[] Entries { get; set; } = new string[] { "", "" };
    }
```
I'm fixing this now.
