### ISSUE TITLE
Drop SkiaSharp preview language at GA

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23904]
Offline discussion indicates GA might be reached by EOY. Will check at 🎁⛄🏂 time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 119b7711-dc49-4525-199a-c75bee9c43b5
* Version Independent ID: 119b7711-dc49-4525-199a-c75bee9c43b5
* Content: [ASP.NET Core Blazor WebAssembly native dependencies](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/webassembly-native-dependencies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/webassembly-native-dependencies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
**UPDATE 12/28**: We don't have a GA release yet for SkiaSharp. I'll check back in January.

**Comment by guardrex** [comment]
**UPDATE 1/14**: No 🎲🎲 yet ... https://www.nuget.org/packages/SkiaSharp.Views.Blazor. I'll check back in February.

**Comment by guardrex** [comment]
**UPDATE 2/25**: Not yet ⏱️.

**Comment by guardrex** [comment]
**UPDATE 3/8**: Not yet ⏱️. I sent an offline message to the package maintainer to ask about progress given that a target of '21 EOY was stated back in November.

**Comment by guardrex** [comment]
**UPDATE 4/16**: Nothing yet. There was no response to my email message, so I'm going to try at the SkiaSharp GH repo ...

https://github.com/mono/SkiaSharp/issues/2005

**Comment by guardrex** [comment]
**UPDATE 4/20**: No response on the issue that I opened, so I closed it. Management will try to reach them. If we can't get guidance, we'll likely swap out SkiaSharp for SQLite+EF Core.

**Comment by mattleibow** [comment]
Sorry about that, been pretty hectic this side with all the stuff.

We are going GA at //build when we ship maui

So basically next month.

**Comment by guardrex** [comment]
# :tada:

**_It's LIVE!_** 🍾🕺💃 

https://www.nuget.org/packages/SkiaSharp.Views.Blazor/2.88.0

I'll resolve this issue now.
