### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by BrennyAlbany** [dotnet/AspNetCore.Docs#23906]
[Enter feedback here]
I just tried the tutorial here - https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio - in Visual Studio 2022 Community, and when I try to run it, I get the following.....

Secure Connection Failed

An error occurred during a connection to localhost:7106. Certificate key usage inadequate for attempted operation.

Error code: SEC_ERROR_INADEQUATE_KEY_USAGE

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you [trust the certificate](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)? If not, trust it. If that doesn't solve the problem, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture

**Comment by BrennyAlbany** [comment]
Yes, I trusted the certificate - I was following the instructions
explicitly.  I will attempt to do the Report a Problem at some point
tomorrow.

**Comment by BrennyAlbany** [comment]
I see you closed the ticket/issue already.  Fascinating.

**Comment by Rick-Anderson** [comment]
Try https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#windows---certificate-not-trusted

**Comment by BrennyAlbany** [comment]
Golly...I don't know about doing that.  I'll just try that process you
noted above about Report a Problem.

**Comment by Rick-Anderson** [comment]
Just run the following
```
dotnet dev-certs https --clean
dotnet dev-certs https --trust
```
