### ISSUE TITLE
"Layout in ASP.NET Core" page missing @namespace in list of directives supported by _

### ISSUE THREAD

**Issue by milostns** [dotnet/AspNetCore.Docs#23908]
On the page: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-6.0#importing-shared-directives
`@namespace` directive is not on the list of `_ViewImports` file supported directives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's the use case for `@namespace` in the layout file?
