### ISSUE TITLE
Tag Helpers causes exception "ViewResultExecutor The view 'zzzz' was not found. Searched locations

### ISSUE THREAD

**Issue by k-bromose** [dotnet/AspNetCore.Docs#23900]
Hi.

The following component:

     [ViewComponent(Name = "RuteRaekkefoelgeSpecialaftaler")]
    public class RuteRaekkefoelgeSpecialaftalerComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(SpecifikRuteViewModel model)
        {
            return await Task.FromResult(View(model.Specialaftales));
        }
    }

With
_ViewImports:
@addTagHelper *, MapPlanner.Mvc

causes exception "ViewResultExecutor The view 'zzzz' was not found. Searched locations

when referenced as: 
<vc:rute-raekkefoelge-specialaftaler model="@Model"/>

The reason is that the component is called from the first page loaded - and with Model = null.

To fix the problem:
Remove @addTagHelper *, MapPlanner.Mvc from _ViewImports

and change vc: to: @await Component.InvokeAsync(typeof(RuteRaekkefoelgeSpecialaftalerComponent), new { model = Model })

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  who's the right person to review this. That error message is wrong.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
