### ISSUE TITLE
There's a problem with the sample code for @inherits in <Razor syntax reference for ASP.NET Core>

### ISSUE THREAD

**Issue by wenhx** [dotnet/AspNetCore.Docs#23914]
The url of the document is here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#inherits

The code does not make it clear that it is only for MVC projects and does not apply to Razor Pages projects.
It took me a long time to fix the error when I referenced this part of the code in my Razor Pages project to use @inherits.
Until I see this link: https://github.com/aspnet/Mvc/issues/6769#issuecomment-327902990

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#inherits)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per that same issue, it was fixed for ASP.NET Core 2.2  in https://github.com/aspnet/Mvc/pull/6813

**Comment by wenhx** [comment]
The problem is a documentation problem, not a code problem.
Since @inherits can be used in MVC projects as well as Razor Pages projects, the base class that you need to inherit to define your own Razor page type are different in both types of projects. The problem with the documentation is that the sample code only applies to MVC projects, not Razor Pages projects, and the documentation is not clear on this.

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
> The problem with the documentation is that the sample code only applies to MVC projects, not Razor Pages projects, and the documentation is not clear on this.

You had to use different code before the issue was fixed. 
Per [this comment](https://github.com/aspnet/Mvc/issues/6769#issuecomment-371187931) it works.
