### ISSUE TITLE
Runtime compilation not relevant/working in asp.net core 6?

### ISSUE THREAD

**Issue by edgar-tamm-uptime** [dotnet/AspNetCore.Docs#23910]
Recently converted from an asp.net core 5 project to a .net 6 one, and it seems that, at least the ["Conditionally enable .."](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio#conditionally-enable-runtime-compilation-in-an-existing-project) is not working anymore in asp.net core 6?

When creating a new asp.net core 6 project from Visual Studio template (which configures the project to use the "Conditionally enable ..." version) even the option seems to have been removed:
.net 5
![image](https://user-images.githubusercontent.com/91314311/141732442-2de33751-fb98-428f-90e6-67447632adfd.png)

.net 6
![image](https://user-images.githubusercontent.com/91314311/141732522-988cbd8c-dc68-4416-a9e2-557c0eb721bc.png)

So the question is, has this feature been replaced by hot-reloading (even when hot-reloading has been disabled)? If yes, then the documentation should probably reflect that.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  quick question on why **Enable Razor runtime compilation** was dropped in .NET 6

**Comment by pranavkm** [comment]
The Runtime package continues to be available if you'd like to use it in your application: https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation. The primary motivation for having the `Enable Razor runtime compilation` option was to provide developers a way to have a fast inner-loop experience when working with .cshtml files. 

In .NET 6, the fast inner loop experience is provided by Hot reload in VS and `dotnet-watch`. Using hot reload also removes some of the idiosyncrasies of runtime compilation such as views being compiled to a separate assembly that did not have the same assembly identity as the assembly views were initially compiled to.

**Comment by edgar-tamm-uptime** [comment]
@pranavkm 

What does it mean that the package is available? It doesn't seem to work, at least not in the way it used to (Maybe this wasn't clear enough in my initial post). As stated in my post I converted from .net 5 to .net 6. The .net 5 project was configured to use the "Conditionally enable runtime compilation.." version (ie only modifying launchsettings.json) and it worked well. Now when I save a cshtml file then the view isn't updated (even after refreshing the page), I have to actually compile for the updates to apply.

I haven't tested the other versions of enabling runtime compilation, maybe those work.

**Comment by davidfowl** [comment]
@edgar-tamm-uptime did you update all of your package references to the 6.0.0 version? Can you show the project file after the upgrade?

**Comment by edgar-tamm-uptime** [comment]
@davidfowl 

I have: `<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />`

This is a small test solution I made after I noticed that it didn't work (it contains both .net 5 and .net 6 versions). Created new projects from zero, for .net 6 manually added the necessary package and launchsettings (copied from .net 5 project). This is basically the same that I have in the actual project:
[RazorRuntimeCompilationTest.zip](https://github.com/dotnet/AspNetCore.Docs/files/7543302/RazorRuntimeCompilationTest.zip)

**Comment by serpent5** [comment]
I've spent a little time looking into this, and I've found that it works with the call to `AddRazorRuntimeCompilation()`, but not with the `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES` approach. I'll do some more troubleshooting and report back...

**Comment by pranavkm** [comment]
The hosting environment issue is known and I'm working on getting it back-ported to 6.0: https://github.com/dotnet/aspnetcore/pull/39381

**Comment by JoeMarkov** [comment]
Could someone please add to the documentation and also clarify when would I want to add Runtime compilation vs when do I want to use the HotReload feature in .NET 6? Or is Runtime compilation only today in .NET 6 applicable if I want to do things on the server once my app is deployed?

**Comment by davidfowl** [comment]
That's the intent yes. Only if you need to change the razor at runtime after deployment would you need runtime compilation.

**Comment by jakenuts** [comment]
> 

This is helpful to know. One concern I have though is the “fast inner-loop” of hot reload in dotnet 6 seems to take much longer than RRC & live reload in my 3.1 projects. Is that a common experience for other developers?

**Comment by jjxtra** [comment]
Calling `.AddRazorRuntimeCompilation()` and adding the `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` nuget breaks all my views. I get errors that none of my classes and types are available. I assume it is something to do with the `AdditionalReferencePaths` property on the `MvcRazorRuntimeCompilationOptions` class?
