### ISSUE TITLE
Custom web.config blazor wasm server hosted vs client

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/AspNetCore.Docs#23911]
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#use-a-custom-webconfig

I think for this section, it should be made more clear that if you are using asp.net host for your blazor webassembly that the web.config file needs to be in your server project not the client project. 

I initially had the web.config file in the blazor webassembly project and it never merged the web.config file settings when using the `PublishIISAssets.` setting

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Looks like setting the `<PublishIISAssets>` property to `true` is no longer required.

@jkotalik, I was about to place an update in the guidance for how to use a custom `web.config` file for a Blazor project. It looks like merely placing the custom `web.config` at the root of the project results its use ✨ *automagically* ✨ without having to set the `<PublishIISAssets>` property to `true`. Can you confirm that this is the case? If so, can you say if there was a change for this at either 3.1-to-5.0 or 5.0-to-6.0? I'd check here, but I was rather hasty about shedding old bits and removed my 3.1 SDK 🙈.

**Comment by guardrex** [comment]
Related ... https://github.com/dotnet/aspnetcore/issues/26965

**Comment by guardrex** [comment]
Actually based on that discussion ☝️, best to ask @pranavkm about it.

@pranavkm ... I don't see that setting the `<PublishIISAssets>` property to `true` is required for 6.0. It seems from the discussion that we should keep the guidance to set that for 3.1 and 5.0 and drop it now for 6.0 or later.
