### ISSUE TITLE
Typo in section Add a data model class 

### ISSUE THREAD

**Issue by shashank-shekhar** [dotnet/AspNetCore.Docs#23917]
The last sentence in [Add a data model class](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio#add-a-data-model-class) is missing 'T' at the very beginning. 
Instead of _The question mark..._ it currently reads as _he question mark..._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks, fixed in [this commit](https://github.com/dotnet/AspNetCore.Docs/commit/e88b3d56c4dbc0af2d2a0e779a6c1ee87e90ea49#diff-07dd32733972ab02d094b382a629be22d24fe19ef2489c9e154f20ef0972fbb2)
