### ISSUE TITLE
Minimal API overview - adding example of how to get service from DI

### ISSUE THREAD

**Issue by Swiftly1** [dotnet/AspNetCore.Docs#23921]
I believe that there was relatively popular usecase that people used before Minimal APIs and I think it'd be worth documenting how to do it with Minimal APIs

Previously there was Configure method where you could add parameter and it'd be injected, that was used for e.g DbContext or SomeService (I'm not saying those are best practices or something)

It was unclear for me how to achieve this in Minimal API style, so the question is what do you think about adding example like this:

    using App;

    var builder = WebApplication.CreateBuilder(args);

    builder.Services.AddControllers();
    builder.Services.AddTransient<SomeService>();

    var app = builder.Build();

    using (var scope = app.Services.CreateScope()) // this part
    {
        var service = scope.ServiceProvider.GetRequiredService<SomeService>();
        service.Test();
    }

    app.MapControllers();
    app.Run();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Parameter Binding](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#parameter-binding), that section  uses DI

**Comment by serpent5** [comment]
@Rick-Anderson That section is more about binding incoming request data for endpoints, rather than accessing a service from DI when the app starts up to, e.g. [seed the database](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-6.0&tabs=visual-studio#add-the-seed-initializer-2).

**Comment by Swiftly1** [comment]
Yup, the equivalent in non-Minimal APIs version would be:

	other Startup.cs stuff...

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddControllers();
		services.AddTransient<SomeService>();

		services.AddDbContext<BloggingContext>(options => options.UseSqlServer(ConnectionStrings.BloggingDatabase));
	}
			
	public void Configure(IApplicationBuilder app, SomeService test) // <----- this
	{

	}

As you see there's `SomeService` being injected to the `Configure`

**Comment by Rick-Anderson** [comment]
@serpent5  assigned this to you.

**Comment by serpent5** [comment]
@Swiftly1 Would you be interested in creating a Pull Request to add your example?

**Comment by Swiftly1** [comment]
I believe that from technical standpoint this should work (urls, code snippet), but I did something weird with my MS/GH account and I'm unable to access preview link

![obraz](https://user-images.githubusercontent.com/77643169/142705961-1092ad81-7e95-4238-aba3-dcb4fb97b4ca.png)

**Comment by Rick-Anderson** [comment]
> but I did something weird with my MS/GH account and I'm unable to access preview link
Those are internal links, you need to be joined to a MICROSOFT domain to read them
