### ISSUE TITLE
AddCors not found

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#23926]
I tried following this page to enable cors. However when I inserted the statement
````builder.Services.AddCors...````
I got the error that IConfigurationCollection does not contain definition for AddCors. The page shows no guidance as to what package must be added to the app as a prerequisite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I'm not sure what's wrong with your app, but you don't need any packages.

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

**Comment by dajma00** [comment]
Thanks for the reply. Figured it out, I was working on a wasm app, not the server. So this was not even required. CORS settings is not a concern on the browser side.
