### ISSUE TITLE
Please have the date at the top of the page in the format 5-Sep-2021 rather than 09/05/2021. This will be helpful to everyone, not just US residents. 

### ISSUE THREAD

**Issue by pmia** [dotnet/AspNetCore.Docs#23927]
Please have the date at the top of the page in the format 5-Sep-2021 rather than 09/05/2021. This will be helpful to everyone, not just US residents. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pmia ... We only work on the content here for ASP.NET Core, but ......

* There's a language setting at the bottom of the doc pages. Click on the text **English (United States)** to select a different language. I think if you change the language there, you get a localized date on all of the pages.
* If you want to provide general feedback on the docs for this, open an issue here :point_right: https://github.com/MicrosoftDocs/feedback/issues
