### ISSUE TITLE
Not able to resolve reference to WebApplication.CreateBuilder

### ISSUE THREAD

**Issue by jjjohn538** [dotnet/AspNetCore.Docs#23933]
In "Tutorial 1 of 8" for Razor Pages with Entity Framework Core in ASP.NET Core under the section labelled "Update the database context class", there are instructions to modify the Program.cs (NOTE: This should be labelled Startup.cs).
The modification required is to add the code:
var builder = WebApplication.CreateBuilder(args);

Based on the docs [https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication?view=aspnetcore-6.0],
I need to add the package Microsoft.AspNetCore.App.Ref v6.0.0 to my solution. After downloading and installing v6.0.0 of both Microsoft.AspNetCore.App and Microsoft.NetCore.App, I tried running (at CLI):
dotnet add <MyProjectName> -f -v6 Microsoft.AspNetCore.App

I receive the following error message:
error: Package 'Microsoft.AspNetCore.App' is incompatible with 'user specified' frameworks in my project file.csproj.

Am I on the right track? My progress is delayed as I try to work my way through this tutorial. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> there are instructions to modify the Program.cs (NOTE: This should be labelled Startup.cs).

You need to follow the Prerequisites and install .NET 6.
