### ISSUE TITLE
The official documentation

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/AspNetCore.Docs#23946]
I think it would help for the tutorial to provide a link to the official documentation. It has a link to advanced material but I see nothing linking to the documentation. The Microsoft documentation search facility is very frustrating; it shows many pages for a search topic but usually not the main documentation page. I found this tutorial, hoping it would link to the documentation.

Hey, Microsoft; what I am asking is for you to do things the good old-fashioned way. Half a century ago when I was in high school I read the documentation for the machine language of IBM computers back then. I know what clear documentation looks like.  Microsoft needs to learn how to do documentation the old-fashioned way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is the official documentation
