### ISSUE TITLE
Link points to .NET 5 for page displayed for .NET 6.

### ISSUE THREAD

**Issue by biilmanndk** [dotnet/AspNetCore.Docs#23949]
The permalink under section "Direct download (current version)" points to .NET 5 - should by .NET 6 by now!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @biilmanndk ... This is a dup of https://github.com/dotnet/AspNetCore.Docs/issues/23934. We'll get the link updated.

**Comment by guardrex** [comment]
btw --- It's one of those permalink deals. It should work out that no matter where this link is, it's destination will get updated internally so that the link URL in the doc won't need a change. They just need to make the update internally to make it point to latest.
