### ISSUE TITLE
Where is the main documentation?

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/AspNetCore.Docs#23947]
If this is the main documentation page then it should not begin by showing how to create a sample project. That is not good documentation.

I think good documentation should begin by saying something such as Razor is facility for processing a cshtml file as input to produce a HTML file as output that does processing and substitution requested in the file. I hope that is close to accurate. Something like that would be good. Beginning with an **indirect** sample of that does not help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is more advanced, you hit the right doc in your last issue. It tells you that right up front.
