### ISSUE TITLE
You do not specify what the variable [args] is, which is used 17 times in the example.

### ISSUE THREAD

**Issue by hrgell** [dotnet/AspNetCore.Docs#23944]
You need to specify what the variable [args] is, which is used 17 times in the example. Is it from Main(string[] args) or elsewhere, and what should the contents of it be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
args is used all ASP.NET Core templates and in virtually all our docs. Yes, it's command line args, nothing to do with CORS.
