### ISSUE TITLE
Typo in docs for dotnet-watch

### ISSUE THREAD

**Issue by Nefarion** [dotnet/AspNetCore.Docs#23956]
Imo the following line should read "...`dotnet watch` might ***not*** be ->able<- to inject the script...", not "unable".
https://github.com/dotnet/AspNetCore.Docs/blob/22a03d1bbcd12ed57268728154c5ccb5ff7755a4/aspnetcore/tutorials/dotnet-watch.md?plain=1#L216

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3163f-1903-f2c7-8909-d34f917944bf
* Version Independent ID: 55aae418-9d32-5b2b-1df7-5e4e76313ec4
* Content: [Develop ASP.NET Core apps using a file watcher](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/dotnet-watch.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/dotnet-watch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @Nefarion. Yep, that's a good spot. Would you like to open a Pull Request to fix it yourself?

**Comment by Nefarion** [comment]
@serpent5 Sorry, i am unable to sign the CLA at the moment, thus i cannot open a PR.

**Comment by serpent5** [comment]
Ok, sure, no problem. I'll take care of this then. Thanks again for reporting it.
