### ISSUE TITLE
Method naming

### ISSUE THREAD

**Issue by jgauffin** [dotnet/AspNetCore.Docs#23950]
The method is named `InvokeAsync` and just `Invoke` sometimes, despite that all examples use async.

Which name should it have?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @jgauffin. At the end of the [Middleware class](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0#middleware-class) section, we list the requirements for a middleware class:

> - A public method named `Invoke` or `InvokeAsync`. This method must:
>   - Return a Task.

---

> Which name should it have?

.NET uses the `Async` suffix as a convention, but not everyone agrees with the convention. I'll update the article to use `InvokeAsync` everywhere for consistency. Thanks for raising this.
