### ISSUE TITLE
Samples on page are not up-to-date

### ISSUE THREAD

**Issue by johandanforth** [dotnet/AspNetCore.Docs#23953]
Most of the samples on this page are not up-to-date with .net 6 and VS2022.  Can I contribute with corrections?

/Johan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @johandanforth. Thanks for reporting this.

> Can I contribute with corrections?

Yes, absolutely. I can help you get started if you like. Just ping me here if you have any questions.

**Comment by johandanforth** [comment]
Yeah, I just started looking at it, cloned the repo from github and just got it up in VS2022, folder view 😊 What I’m not sure of is - is there a 6.x section code-samples and such, and is it “automagically” referenced when ppl select this platform in the docs? I can see there’s a

\aspnetcore\security\authentication\social\social-code\3.x\

folder, should I create a \6.x\ folder and what else to make sure the right docs are shown? 😊

I got some time, I’m home with the classic flu :/

/Johan

**Comment by serpent5** [comment]
Here's a few things for getting started:

- Pull the latest from `main`, and then branch from that. I suggest something like `johandanforth-23953` for the branch name, which is your GitHub username and the issue number.
- Make your 6.0 changes to `microsoft-logins.md` inside of the `:::moniker range=">= aspnetcore-6.0"` and first `:::moniker-end` pair. This is how the version selector affects which version gets shown.
- Create the code files you need in a `6.0` folder.
- Open up a PR when done, or open a draft PR and mark it ready for review when you feel that's the case. If you have specific questions, you can comment on your PR.

**Comment by johandanforth** [comment]
Great, I'll try it 😊

Mvh
Johan Danforth
________________________________

**Comment by johandanforth** [comment]
Ok, I got things setup. Do you know of any tools or plugins for VS Code (or VS2022) that renders a preview with consideration to "moniker" range? Also an MD-plugin that can also render includes? Like the [asd[](filepath)] includes?

Cheers!

/Johan

**Comment by johandanforth** [comment]
Ah, great, I will try that later. Teams-meeting now 😊 I just installed the doc Auth pack. Thanks for the guidance, I’ve been thinking of contributing for years! It’s a great way to learn new stuff and I love to write 😊


/Johan

**Comment by johandanforth** [comment]
Sorry for pestering you like this – I got docfx running, but how do I tell it the moniker range I’m interested in? Hopefully I can do this from env vars?

/Johan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by johandanforth** [comment]
Also, I’m new to DocFx but I thought it could do ”hot compile/reload” when the .md source file is changed and saved?

/Johan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Johan ***@***.***>
Sent: den 17 november 2021 15:50
To: ***@***.***>
Subject: RE: [dotnet/AspNetCore.Docs] Samples on page are not up-to-date (Issue #23953)

Ah, great, I will try that later. Teams-meeting now 😊 I just installed the doc Auth pack. Thanks for the guidance, I’ve been thinking of contributing for years! It’s a great way to learn new stuff and I love to write 😊


/Johan

**Comment by serpent5** [comment]
DocFX doesn't support the monikers, so you'll see all versions one after another. You can just focus on the >= 6.0 version and ignore everything after. DocFX handles the includes you mentioned, however. Don't worry if you don't quite get the monikers right - we can sort that at the PR stage.

I don't think DocFX can hot reload. I usually have to restart it when I make a change, but it's usually much faster due to some form of caching.

**Comment by johandanforth** [comment]
Ah, pity. I’m trying out a simple nmp-watch solution now just to make it perhaps a bit easier to work with. The rebuilding seems very slow though… Even if I change just one file it takes 10 seconds or more to build. :/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
