### ISSUE TITLE
Visual Studio 2022:  Menu item "Add -> Client side library" is absent.

### ISSUE THREAD

**Issue by Andrey-Bushman** [dotnet/AspNetCore.Docs#23976]
> _In Solution Explorer, right-click the project folder in which the files should be added. Choose Add > Client-Side Library. The Add Client-Side Library dialog appears_

Visual Studio 2022 hasn't this context menu item.

![image](https://user-images.githubusercontent.com/14824805/142411648-64333b42-2af6-4781-bc35-f8248e72ec8c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d69ef46-689c-33d0-c86b-078c8172c480
* Version Independent ID: 519af8ab-78e5-88c9-f268-431f417eca73
* Content: [Use LibMan with ASP.NET Core in Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/client-side/libman/libman-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/libman/libman-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Did you add the ASP.NET Core workload when you install VS22?
![image](https://user-images.githubusercontent.com/3605364/142487220-da92f892-82ab-4530-a969-8e483b743226.png)

**Comment by Andrey-Bushman** [comment]
@Rick-Anderson What is "_ASP.NET Core workload_"? I have installed .Net 6.0.100 SDK, Visual Studio 2022 and all its updates.

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio#prerequisites-2

**Comment by Rick-Anderson** [comment]
Run the installer again

**Comment by Andrey-Bushman** [comment]
@Rick-Anderson I see this:

![image](https://user-images.githubusercontent.com/14824805/142491715-5a8b094e-08d2-43b1-b792-a0a4ba7f2a27.png)

This is my istalled components:

![image](https://user-images.githubusercontent.com/14824805/142491846-fa2ede98-6cc2-4039-b79d-19091d51df86.png)

and

![image](https://user-images.githubusercontent.com/14824805/142491969-cceff498-701d-41c2-a3d0-537e92b39dfc.png)

**Comment by Andrey-Bushman** [comment]
@Rick-Anderson why you closed the issue?

**Comment by Rick-Anderson** [comment]
For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture

**Comment by WiseyD** [comment]
Having the same issue as of yet unable to find a solution
