### ISSUE TITLE
Link for 'Current .NET Core Hosting Bundle' goes to .net 5 instead of .net 6

### ISSUE THREAD

**Issue by PriceyCoder** [dotnet/AspNetCore.Docs#23970]
The link for "Current .NET Core Hosting Bundle installer (direct download)" on this page downloads the .net 5 installer, when I would expect it to be the .net 6 installer now. 
ie. it links to https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @PriceyCoder ... This is a dup of https://github.com/dotnet/AspNetCore.Docs/issues/23934.
