### ISSUE TITLE
Development time IIS support missing in the Visual Studio 2022 Installer

### ISSUE THREAD

**Issue by Andyc751** [dotnet/AspNetCore.Docs#23975]
There is no Option for "Development time IIS support" in the Visual Studio 2022 Installer. This no longer exists in Visual Studio 2022.  Is there a new name for this ?

For the ASP.NET and web development workload, locate and install the Development time IIS support component.

The component is listed in the Optional section under Development time IIS support in the Installation details panel to the right of the workloads. The component installs the ASP.NET Core Module, which is a native IIS module required to run ASP.NET Core apps with IIS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@shirhatti Can you answer this question?

**Comment by Rick-Anderson** [comment]
I asked @John-Hart if we should remove this topic and he responded

No, I don’t think it’s the topic, just the section “Enable development-time IIS support in Visual Studio” needs to be updated for if the optional component no longer exits. Not sure which versions of VS removed that as we don’t own that component, but you can still create a profile for IIS of .NET 6.0+
