### ISSUE TITLE
.NET 6: Tutorial: Call an ASP.NET Core web API with JavaScript

### ISSUE THREAD

**Issue by happylennychen** [dotnet/AspNetCore.Docs#23979]
When I finished coding following Create a web API with ASP.NET Core, I cannot find Startup.cs anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's all in main. If you followed https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api, it's similar. We hope to get this updated by early 2022.

**Comment by Rick-Anderson** [comment]
@smandia  this is ready. Can you build and test? You'll need to copy[ the code outside of GitHub to test. ](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi) 
Make changes that are necessary. When testing delete `Program.cs` and remove the `#def` from https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/StartupJavaScript.cs
When you make the PR, remove the line `<!-- TODO: Copy code to another folder outside GitHub and test: -->`

**Comment by smandia** [comment]
@Rick-Anderson  Sure I will take it up and raise a pull request as mentioned

**Comment by smandia** [comment]
Done with https://github.com/dotnet/AspNetCore.Docs/pull/24247 . Please have a look. I took the liberty to deletedstartupJavascript.cs file and move the code to program.cs after testing .  Your feedback would be helpful on such moves

**Comment by Rick-Anderson** [comment]
Fixed in #24247
