### ISSUE TITLE
Page is pointing to the .net 5 hosting bundle

### ISSUE THREAD

**Issue by MattCartwright-EH** [dotnet/AspNetCore.Docs#23971]
The "Current .NET Core Hosting Bundle installer (direct download)" link points to the .net 5 hosting bundle installer rather than the .net 6 hosting bundle installer at https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-hosting-bundle-installer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @MattCartwright-EH. Thanks for taking the time report this. We're already tracking this as part of #23934.

**Comment by mairaw** [comment]
The link was fixed today. Thanks for reporting!
