### ISSUE TITLE
Wrong example for section "Services not created by the service container"

### ISSUE THREAD

**Issue by mahidulalvi** [dotnet/AspNetCore.Docs#23986]
The [page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#services-not-created-by-the-service-container) has a section where it shows the services that are not created by the service container as non self-disposable. The example used to show this actually uses methods that are self-disposable. The correct way would be one of these described [here](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-registration-methods) - see the table for references for self-disposable vs non self-disposable methods.

The [examples](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/dependency-injection/samples) need to be changed for the different asp net core versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#services-injected-into-programcs)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The [page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#feedback) has a section where it shows the services that are not created by the service container as non self-disposable. 

The link you provided is the feedback anchor. What section? What example?

**Comment by mahidulalvi** [comment]
Its this [link](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#services-not-created-by-the-service-container). I have updated the description as well.

**Comment by Rick-Anderson** [comment]
@mahidulalvi  you're right. @serpent5  do you want to delete that section? Any idea what the intention was?

**Comment by Rick-Anderson** [comment]
I see the problem

```
builder.Services.AddSingleton<Service2>();
```

The example is supposed to show newing up the service.

```
services.AddSingleton(new Service1());
    services.AddSingleton(new Service2());
```

**Comment by serpent5** [comment]
> The example is supposed to show newing up the service.

Yes, that looks right to me. I can fix this first thing on Monday, unless you have time to fix it before then.

**Comment by Rick-Anderson** [comment]
@mahidulalvi  thanks  for reporting this and helping me find the problem. The fix should be live in 10 minutes.

**Comment by mahidulalvi** [comment]
No problem, glad I was able to help.
