### ISSUE TITLE
Check/update bool value entries for host config

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#23984]
Check and update each entry as needed in host config settings.

For at least some of them, string numbers `1`/`0` are acceptable for `true`/`false`, while others must be provided as `true`/`false` only.

Cross-ref: #23982

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by yecril71pl** [comment]
Even if this is true, the value `false` is supported and undocumented.

**Comment by guardrex** [comment]
Yes, that's what I mean about doc churn breaking how these are described. I'm one of the early authors on this topic. Since I wrote one of the early versions of the topic, several authors (and perhaps community authors) have worked on the text. These descriptions have become broken. I'll fix them up. It will be tracked by the issue that I opened.
