### ISSUE TITLE
link to to create self signed certificate by powershell is broken

### ISSUE THREAD

**Issue by FerdousR** [dotnet/AspNetCore.Docs#23999]
link to to create self signed certificate by powershell is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Link is just above [Bind to a Unix socket
](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#bind-to-a-unix-socket)

`[!INCLUDE [How to make an X.509 cert](~/includes/make-x509-cert.md)]`

[~/includes/make-x509-cert.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/make-x509-cert.md)

**Comment by guardrex** [comment]
I think it's trying to go here ...

https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate

... they seem to have dropped the "client" from the "pkiclient" segment.

Rick, I'll put up a patch PR and ping u on it in a sec.
