### ISSUE TITLE
.NET 6: Scaffold Identity  Blazor only

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#23993]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&branch=pr-en-us-23968&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's the same as for ASP.NET Core apps. There's nothing else to cover.

**Comment by guardrex** [comment]
Ok ... **_confirmed_** :+1:. AFAIK, the content can just be copied up to 6.0 without changes.

**Comment by Rick-Anderson** [comment]
Change you need to make:

1. Add `[!INCLUDE[](~/includes/scaffold-identity/install-pkg.md)]` before scaffolding. This adds 
```powershell
Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
```

2. remove: Identity is configured in Areas/Identity/IdentityHostingStartup.cs. For more information, see IHostingStartup.

3. In the Startup class:  Change that to current *Program.cs* code

**Comment by guardrex** [comment]
Oh, I see what you mean. I didn't pick up on the H2 headings. I'm 🧠-fried for the week.

I'll fix this up on Monday and ping u for review.

**Comment by guardrex** [comment]
@Rick-Anderson ... The package install piece wasn't required here **_manually_** AFAICT at the start of the process ...

```console
Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
```

VS installed that ✨ *automagically* ✨. Do you still want me to place the INCLUDE?

**Comment by guardrex** [comment]
A few more points of 😕 ...

* The topic is versioned. The INCLUDE for use in the topic's versioned content at `includes/scaffold-identity/id-scaffold-dlg-auth.md` is also versioned. This topic seems to nest the moniker ranges. In the past, such nesting has caused build warnings/errors, so I'm confused about the structure of the topic. I'm going to go ahead in a sec and put the PR up. We can see if it 💥 ... I think it will. We'll see.

* This step ...
 
  > From the left pane of the **Add Scaffold** dialog, select **Identity** > **Add**.

  ... isn't what I see now in VS. It seems to be ...

  > From the left pane of the **Add New Scaffolded Item** dialog, select **Identity**. Select **Identity** in the center pane. Select the **Add** button.

  Do you want me to make that change to the `includes/scaffold-identity/id-scaffold-dlg-auth.md` INCLUDE?

**Comment by Rick-Anderson** [comment]
> **UPDATE**: I'm about to submit the PR. Let's take this up on the PR.
> 
> @Rick-Anderson ... The package install piece wasn't required here **_manually_** AFAICT at the start of the process for VS scaffolding ...
> 
> ```
> Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
> ```
> 
> VS installed that ✨ _automagically_ ✨. Do you still want me to place the INCLUDE in the Blazor section (or make any mods to it otherwise)?

For RP, MVC, I've repo'd it 10 times that it's required. Maybe not for Blazor. SKip it for Blazor and see if we get any complaints.

**Comment by guardrex** [comment]
I see ... ok ... yeah, I only did a Blazor Server app.

Ok ... I'll update the PR by EOD. I'm :ear: for any other feedback on the PR ❓. I'll ping u back later today.
