### ISSUE TITLE
Greet.GreeterClient(channel) should be Greeter.GreeterClient(channel)

### ISSUE THREAD

**Issue by felinepunch** [dotnet/AspNetCore.Docs#24002]
[Enter feedback here]
In this sentence, 
"For example, a service called **Greeter** generates a GreeterClient type with methods to call the service."

but in code, 
var client = new **Greet**.GreeterClient(channel);

so Greet.GreeterClient(channel) should be Greeter.GreeterClient(channel)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7ec3c3-918c-6ffd-1ac0-4f88b89d9295
* Version Independent ID: 1c1f72f1-3d5d-3397-c17d-1889dbae6fee
* Content: [Call gRPC services with the .NET client](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
Thanks for the report, @felinepunch. It seems that given so much of the topic uses `Greet` that the service should be called `Greet` to match rather than change all of the code blocks down the topic. I'll do that on the PR and ping James for review.

**Comment by JamesNK** [comment]
Greet is the name of the package that the Greeter service is in.
