### ISSUE TITLE
Who is still using IE in Microsoft for documentation?

### ISSUE THREAD

**Issue by hexbinoct** [dotnet/AspNetCore.Docs#24001]
The first image on this page is a screenshot of IE, now if Microsoft is going out of its way to discourage IE, they shouldnt let it be used on their official year 2021 updated doc page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
:smile: *Yes!* We agree. There's just a few people working here at any one time ... approximately 3 people ... with >400 topics, >100 sample apps, and > 500 issues on the repo. You get the picture! 😅🏃

Rick, I'm going to submit a quick fix PR that just takes the guts of the app in the image and splices it into the browser portion of the 2nd image to replace the first image, given that they're on the same page (Contacts) in the browser. Photoshop will make fast work of it. If you like the new image on the PR, then that's the quickest way to hack it right ..... 🙈 **_RexHack IT!_**&trade; 🙈 ....... I'll ping you on the PR shortly.

Thanks for reporting this @hexbinoct.
