### ISSUE TITLE
.NET 6 update: Create a web API with ASP.NET Core and MongoDB

### ISSUE THREAD

**Issue by Marerc** [dotnet/AspNetCore.Docs#24017]
[Enter feedback here]
I am a newer to asp.net and webapi, when I follow the instruction in this page, no Startup.cs file was found in my project, so that I can not follow the instruction. are there some disaccordings in the latest template in vs studio community edtion and the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
@Marerc Yes, the new .NET 6 templates introduce some heavy changes with the introduction of top-level statements and also minimal API templates. This tutorial is more suited for the MVC template, which gets rid of the startup class and puts that code in the `Program.cs`

Until the tutorial is updated for the new templates, I hope the below explanation helps:

These are the parallel of `ConfigureServices` method.
```
// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
```

Both your builder and middleware pipelines can be configured from the `Program.cs` file itself, you might find the analogy among how Services are Added to the builder -> the app is built with `builder.Build()`, then middleware are added like in `Confugre` method.

```
// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

**Comment by Marerc** [comment]
@prkhandelwal Thanks for your reply. I have compared the current Program.cs file with the one provided in the sample along with Startup.cs file, and got a general idea. However I still can not config the database configuration mentioned in this page. Error occurs as the pic shows.
> These are the parallel of `ConfigureServices` method.

> ```
> 
> Both your builder and middleware pipelines can be configured from the `Program.cs` file itself, you might find the analogy among how Services are Added to the builder -> the app is built with `builder.Build()`, then middleware are added like in `Confugre` method.

![image](https://user-images.githubusercontent.com/14820859/142881427-5ad4662b-7233-49a1-ba7a-6ca2039f52df.png)

**Comment by serpent5** [comment]
@Marerc You've almost got it. Use `builder.Configuration.GetSection(nameof(BookstoreDatabaseSettings))`.

**Comment by Marerc** [comment]
@serpent5 Thanks, now it goes smothly.

**Comment by Rick-Anderson** [comment]
@Marerc  the fixed and updated doc will be live in 30 minutes. Thanks for reporting the issue.
