### ISSUE TITLE
Apache Configuration files directories

### ISSUE THREAD

**Issue by viremman** [dotnet/AspNetCore.Docs#24014]
the configuration files for apache are located in **/etc/apache2/sites-available** rather than the one mentioned in the documentation. Kindly make necessary corrections it is misleading. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by viremman** [comment]
Well noted. Will do so. Thanks.

**Comment by Rick-Anderson** [comment]
@viremman  sorry I was too fast. I reopened this issue so you can PR it. Thanks

**Comment by Rick-Anderson** [comment]
Looks like it was updated
