### ISSUE TITLE
Documentation Somewhat Ambigious On Usage of Asynchronous Calls

### ISSUE THREAD

**Issue by StrangeWill** [dotnet/AspNetCore.Docs#24040]
Currently discussing with a colleague usage of async calls inside of EF Core specifically.

> Do call all data access APIs asynchronously.

I think one of the hangups is "data access API" isn't _entirely_ clear, common nomenclature among some developers may include things like "Data access APIs" being strictly for web communications (ex: JSON API web requests to 3rd party data APIs), is there a better way to make this more clear (and am I right in assuming this includes all I/O?)

Is there a benefit in say -- a web application to leveraging EF's synchronous calls (outside of crazy edge-cases where microseconds matter)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9599d917-4e43-f1ae-452a-1f11aaa985ed
* Version Independent ID: 5cc05b6c-c671-3607-3217-7db73ebc1f28
* Content: [ASP.NET Core Performance Best Practices](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0#optimize-data-access-and-io)
* Content Source: [aspnetcore/performance/performance-best-practices.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/performance-best-practices.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
