### ISSUE TITLE
UseKestrel mentioned but not shown in the sample code

### ISSUE THREAD

**Issue by mschiedon** [dotnet/AspNetCore.Docs#24049]
In the [Get Started](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0#get-started) section, there is mention of the `UseKestrel` method. However, nowhere in the provided sample code this is demonstrated.

![image](https://user-images.githubusercontent.com/70693718/143212295-0822009a-3ab3-4903-8246-53383bfc49de.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @mschiedon. The text just before the code there states that `UseKestrel` is called by `ConfigureWebHostDefaults`, so there's no need for a direct call to `UseKestrel` in the example.
