### ISSUE TITLE
Blazor resource authorization

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24052]
https://github.com/dotnet/aspnetcore/issues/33958

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@optimizasean ... I've scheduled this work for Monday. I'll show Javier's example, but I strongly favor including fully-working/cut-'n-paste demonstrations. Looking at your edit-user suggestion, I think I'll angle the demonstration along those lines, given that it is a common use case. I have an idea for what I'd like to show in an authorization policy for that scenario that will be simple and effective. I just need to *RexHack*&trade;-up some code 🙈😄  and write a section for the Blazor Security overview. Do you want to look at the PR when I put it up on Monday?

**Comment by optimizasean** [comment]
@guardrex - sorry somehow this got sucked into the void, looks great!  I can't wait to use it!
