### ISSUE TITLE
IBrowserFile and StreamContent are not compatible.

### ISSUE THREAD

**Issue by liangpeihui** [dotnet/AspNetCore.Docs#24065]
When uploading multiple large files through IBrowserFile, StringContent throws a timeout exception, but multiple small files do not.
![image](https://user-images.githubusercontent.com/79532375/143391632-919a29f8-0905-4fdc-a32a-e375c9b71165.png)

![image](https://user-images.githubusercontent.com/79532375/143391550-1517913a-577e-4484-af01-80c314292655.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @liangpeihui ... Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
