### ISSUE TITLE
Couldn't find a valid certificate for Azure hosted

### ISSUE THREAD

**Issue by SzymonSel** [dotnet/AspNetCore.Docs#24069]
I've created the:

1. CI/CD with a default appservice name <appname>.azurewebsites.net
2. Azure Key Vault
3. Certificate for IndentityServer
4. Added the ```WEBSITE_LOAD_CERTIFICATES``` configuration on the app service with the certificates thumbnail

I'm getting a error on app startup:
`System.InvalidOperationException: Couldn't find a valid certificate with subject 'CN=IdentityServerSigning' on the 'CurrentUser\My'`

In Kudu Tools, doing a search on ```Get-ChildItem -path Cert:\CurrentUser\My also return no results.```

I've troubleshooted this on other app services including F1 and B1 tiers to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio#additional-resources)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Please add this to the issue that I opened.
