### ISSUE TITLE
Fixture Class in Integration Test

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24064]
https://github.com/dotnet/AspNetCore.Docs/blob/5c1943439bcbf0f2e73334c5be5c118e88dd7d06/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/IntegrationTests/BasicTests.cs#L9

Should'nt be `CustomWebApplicationFactory` instead of `WebApplicationFactory`?

**Comment by serpent5** [comment]
Hi @abdollahkahne. Thanks for taking the time to report an issue.

I don't think this should be changed. The code you've shown supports the [Basic tests with the default WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory) section of the article. `CustomWebApplicationFactory` is demonstrated later in [Customize WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#customize-webapplicationfactory).
