### ISSUE TITLE
Confirm hosted Blazor IdS AKV certificate access guidance

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24067]
Confirm guidance per https://github.com/dotnet/AspNetCore.Docs/issues/19572#issuecomment-979277203

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-6.0&tabs=visual-studio#host-in-azure-app-service-with-a-custom-domain-and-certificate

cc: @SzymonSel ... I'll get to this as soon as I can. 🏃🏃🏃🏃🏃🏃🏃🏃🏃🏃😅 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-3.1&tabs=visual-studio#host-in-azure-app-service-with-a-custom-domain)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by SzymonSel** [comment]
I've created the:

1.     CI/CD with a default appservice name .azurewebsites.net
2.     Azure Key Vault
3.     Certificate for IndentityServer
4.     Added the WEBSITE_LOAD_CERTIFICATES configuration on the app service with the certificates thumbnail

I'm getting a error on app startup:
System.InvalidOperationException: Couldn't find a valid certificate with subject 'CN=IdentityServerSigning' on the 'CurrentUser\My'

In Kudu Tools, doing a search on Get-ChildItem -path Cert:\CurrentUser\My also return no results.

I've troubleshooted this on other app services including F1 and B1 tiers to no avail.

**Comment by guardrex** [comment]
@SzymonSel ... I can't repro any problems here with the basic guidance that we keep for this scenario. Here's the quick-'n-dirty test that I did to confirm the main aspect of the guidance ..

1. Created a self-signed cert in a KV.
2. Created an App Service at B1 level (with the app setting and thumbprint called out by Step 7).
3. Just for a side-test to make sure that any cert in KV would be seen by the app for use with a custom domain, I just checked the **Import Key Vault Certificate** area (for TLS/SSL settings) to make sure that the cert shows up in the drop-down list. You wouldn't do this for this IdS key signing cert. I'm just checking to make sure that the app in App Service can see 👁️ the cert. This is the process one would follow if they had uploaded a PFX for DNS purposes.
4. Executed the PS command to see if that cert shows up. It does.

<img width="372" alt="Capture" src="https://user-images.githubusercontent.com/1622880/143589666-8f734f5b-d4ef-45ef-8a65-f6b671182891.PNG">

<img width="545" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/143589675-91a4ee05-077f-423e-82c6-c6360e823b03.PNG">

<img width="663" alt="Capture2" src="https://user-images.githubusercontent.com/1622880/143589679-d6e9ff9d-a8fa-49a1-a1c4-9fd777a2d791.PNG">

Two things ...

* There's a couple of NIT side problems that I'll use this issue to fix. They change the Azure portal **all the time** 😅, and our Azure portal guidance is under constant threat of churn gremlins 😈.

  For the phrase "**Advanced Policy Configuration**" in the doc, that should have the prefix selection and read: "**Issuance Policy** > **Advanced Policy Configuration**". So, I'll use this issue to make that quick update. There might other 😈😈😈 in these steps due to other portal churn, and I'll get it all fixed up when I reach this topic for further updates in 22H1.

  I see a second little NIT in what's said about the PS command. It's useful in that case to see the IdS cert from that cert store, not the one that will be used for DNS. I should call that out. I'll see if I can find a good troubleshooting Azure doc for either/both App Service and KV cert problems, including a possible PS doc for troubleshooting. If I find something, I'll cross-link it in there at the end.

* Second thing is that this is about the limit of what we'll be able to do here WRT the problem that you're having getting the cert to show up. Idk if the problem has to do with your CI/CD (I'm not experienced in that area for one thing) or if the problem just lies more in the config steps that you took.

  We only work the ASP.NET Core side of things. Not getting a cert to show up for an App Service app from KV is an Azure gesture and falls to Azure docs for edge cases, gotchas, and troubleshooting. I realize that this is not what many devs hope for on their requests here, but we can't provide product support for **_all of Azure_** or deal directly with **_Azure docs_**. Those are completely different groups of folks from us. If Azure docs don't lead you to a solution for getting a cert available, then one should use the normal Azure support channels both within MS and via external, public support channels (SO, Slack, Gitter, etc.).

If you eventually discover a gotcha 😈 that would be good to call out in the doc here, please do come back and add a comment here on it. I'm open to hearing about things that could save folks time and trouble. It's especially good when we can cross-link from here to Azure docs for whatever it is. I'll take a look at the Azure links here to confirm that we're linking to their best, current content for this process.

**_Leave this issue open. It will close automatically when my PR merges shortly.**

**Comment by SzymonSel** [comment]
But wait, what if I don't want to create the TLS/SSL certificate for the domain? (Which is my case, I'm fully satisfied with the default https://<my-app>.azurewebsites.net)

**Comment by SzymonSel** [comment]
Is it possible that the `WEBSITE_LOAD_CERTIFICATES` isn't loaded if don't explicitly add a custom TLS/SSL domain certificate? This is not possible for F1 tier app services, although:

> Although the guidance focuses on using the certificate with a custom domain, the guidance is equally applicable to using a default Azure Apps domain, for example contoso.azurewebsites.net.

**Comment by guardrex** [comment]
You don't need to follow that part of the guidance then. You can just create a self-signed cert for the IdS signing cert, put the app setting in the (B1 level) App Service, and the app should be able to use it from there. Still tho ... you should be able to 👁️ it with the PS command in a Kudu PS console. If you don't, I can't explain why that's the case per this set of guidance.

WRT having both pieces of guidance here (the IdS signing cert and a custom domain), I'm going to leave these together in the section for the time being. Most devs need to do both really when using a custom domain because we don't recommend using the same cert for the DNS part as they use for IdS. Therefore, they should follow every step here. When I reach the topic next year for a large round of updates, I might split out the IdS piece.

> Is it possible that the WEBSITE_LOAD_CERTIFICATES isn't loaded if don't explicitly add a custom TLS/SSL domain certificate? 

That's not relevant AFAIK. If you only want to use a cert for IdS, then you just put one thumbprint there for that self-signed cert. It should just work at that point.

**Comment by guardrex** [comment]
... and btw ... I don't recall exactly if the B1 aspect was only a custom domain aspect. I know that the B1 level is required for custom domains. I don't know if that's a requirement for just IdS cert. I don't know because I'm explaining out **both** scenarios and it's required for custom domains. I'll take a look at that aspect when I circle around in 22H1. If I do split the section and B1 isn't required for merely the IdS cert, then I'll call that out after I've confirmed that it's the case.

**Comment by SzymonSel** [comment]
Thanks. Just to summarize, I don't need a custom domain or TLS cert. I just need one for the IdS.

**Comment by guardrex** [comment]
> I just need one for the IdS.

Ok ... that's cool. After you add the app setting, it should work (and show up in the `CurrentUser\My` store). If not, seek help from Azure :cat2::cat2::cat2: on the Net. There's likely an edge case here of some sort with your Azure scenario ... something that the doc can possibly call out depending on what it is.

If you haven't already done so, I've had some luck in the past just starting a process over from scratch because I was unaware that I missed something along the way. You could try (if you haven't already) a fresh KV and a fresh App Service. If it works, then it was just a tiny misconfiguration in the original attempt.

**Comment by SzymonSel** [comment]
Yeah thanks, I've guess I've already also or almost all possible combinations. Will give a go again and report back if I find anything.

**Comment by SzymonSel** [comment]
After some tests, It seems clear to me, than in order to have the certificate specified in `WEBSITE_LOAD_CERTIFICATES` to be loaded by the app, it also need to be added in TLS/SSL settings.

I'm quite sure if you remove the certificate from the TLS/SSL settings, it will also dissappear from the app service ie. Get-ChildItem will not return this certificate.

So in short - one cannot run IdetintityServer with this scenario on F1 tier

**Comment by guardrex** [comment]
Ok ... we're good. I must have known/seen that, too, because the instruction is ....

> Select the app's TLS/SSL settings. Select Private Key Certificates (.pfx). Use the Import Key Vault Certificate process twice to import both the site's certificate for HTTPS communication and the site's self-signed Identity Server token signing certificate.

... keyword there is "**_both_**" ... so the guidance seems ok right now 🤞 on that point.

**Comment by guardrex** [comment]
When I revisit this for the big round of updates later, I think it will be worth making that whole sentence in **BOLD TEXT**. I'll do that when I circle back.
