### ISSUE TITLE
ASP.NET MVC tutorial is broken -- "EF Core no longer compatible with .NET 5"

### ISSUE THREAD

**Issue by jking11** [dotnet/AspNetCore.Docs#24078]
Part 1 of this tutorial specifically instructs users to use .NET Core 5.0

However, part 4 cannot be followed as written; the instruction "In the PMC, run the following command: [PowerShell] Install-Package Microsoft.EntityFrameworkCore.Design" gives an error message "Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Design 6.0.0 is not compatible with net5.0".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @jking11. As a workaround for now, use `Install-Package Microsoft.EntityFrameworkCore.Design -Version 5.0.12` if you're targetting .NET 5.

**Comment by serpent5** [comment]
@Rick-Anderson Can we do something about this in the tutorial?

**Comment by jking11** [comment]
Thanks -- had just found that same workaround before I saw your reply.  Worked perfectly.
