### ISSUE TITLE
Add search by genre - MovieGenreViewModel does not exist

### ISSUE THREAD

**Issue by BOBOfra** [dotnet/AspNetCore.Docs#24074]
When I Update Index.cshtml in Views/Movies/ in order to [add search by genre to the index view](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0#add-search-by-genre-to-the-index-view), i get an error on the first line, `@model MvcMovie.Models.MovieGenreViewModel`:
CS0234: The type or namespace name 'MovieGenreViewModel' does not exist in the namespace 'MvcMovie.Models'.
I'm pretty sure I have not skip steps. 

Vs 2022, .NET 6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Part 7, add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0#add-search-by-genre-to-the-index-view)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @BOBOfra. You create the `MovieGenreViewModel` as the first step in the [Add Search by genre](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0#add-search-by-genre) section. Did you complete that step? If you did, check for typos in the `namespace` or `class` declarations.

**Comment by BOBOfra** [comment]
Thank you, i've skipped that step...
