### ISSUE TITLE
Please update tutorial "Get started with ASP.NET Core MVC" for VS 2022

### ISSUE THREAD

**Issue by jbeschler** [dotnet/AspNetCore.Docs#24085]
Hi,
The tutorial at this  link: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio does not work in VS 2022.  I assume that's due to the differences in how VS 2019 and VS 2022 build a project. And, I get that; but, I can't follow the tutorial in VS 2022.

If I follow the steps in Part 2 - Add  a controller, when it tells me to append HelloWorld to the URL, I get an error:
This localhost page can’t be found No webpage was found for the web address: https://localhost:44361/HelloWorld 

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio&source=docs#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial at this link: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0
# ?view=aspnetcore-5.0
You must have gotten to the 5.0 version by a link, the default is 6.0. Use the version selector
![image](https://user-images.githubusercontent.com/3605364/143689603-793cda70-f9d8-4e55-8cec-d0a9d16b36a7.png)
