### ISSUE TITLE
Blazor demo app as shown on dotnetconf

### ISSUE THREAD

**Issue by cveld** [dotnet/AspNetCore.Docs#24098]
During dotnetconf James Newton showed a great  Blazor demo app that was able to do client side load balancing using dns and a headless kubernetes service. Can you add a pointer to the source code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac62acc-1270-cc98-024e-659b3a80f4ca
* Version Independent ID: d6f25885-6c43-0d2c-96e2-3b47a4fd7bd7
* Content: [gRPC client-side load balancing](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/loadbalancing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/loadbalancing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
@JamesNK ... FYI side-note/suggestion for these sorts of requests. Given that conference samples go stale PDQ around the docs, an option is for the description of the conference session at the conference website include a link to the source. **_Docs don't maintain a link to it_**. It's just a pop-up deal in this case; but if the link can appear there, it wards off stale content here.

<img width="476" alt="Capture" src="https://user-images.githubusercontent.com/1622880/143774191-6d74795a-c73e-4327-83a6-9c5f30bdb050.PNG">

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet/tree/master/examples#container
