### ISSUE TITLE
Dns refresh process

### ISSUE THREAD

**Issue by cveld** [dotnet/AspNetCore.Docs#24099]
I am trying to figure out how the dns refresh is working. Using the pointer to the pod lifecycle docs I am not able to find the answer. Is the resolver using polling the dns? Or is there an event generated by the cluster which is subscribed? And how is the health of the endpoints determined? As seen in the dotnetconf demo.

Maybe the grpc client is connecting with all endpoints and when the connection is dropped the endpoint is deemed unhealthy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac62acc-1270-cc98-024e-659b3a80f4ca
* Version Independent ID: d6f25885-6c43-0d2c-96e2-3b47a4fd7bd7
* Content: [gRPC client-side load balancing](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/loadbalancing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/loadbalancing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
I've added some more docs about this - https://github.com/dotnet/AspNetCore.Docs/pull/24102

Does the "Address caching" section make it clearer how it works?

**Comment by JamesNK** [comment]
> Maybe the grpc client is connecting with all endpoints and when the connection is dropped the endpoint is deemed unhealthy?

That depends on the load balancing policy. It is true for a round-robin load balancer that connects to all endpoints. A pick-first load balancer connects to only one endpoint.
