### ISSUE TITLE
.NET 6: Health checks

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24092]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in #24215
cc @serpent5  addresses doesn't close
Closes or Fixes work

**Comment by serpent5** [comment]
I've been using `Addresses` for the prep commits. I do use `Fixes` for the actual updates, but the PR you've mentioned above was just some cleanup stuff in preparation for the 6.0-specific changes.
