### ISSUE TITLE
.NET 6: Generic Host 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24091]
Also do #21637

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
@Rick-Anderson @guardrex How should we frame the 6.0 version of this? With `WebApplicationBuilder`, we don't see the underlying `Host`, so I'd appreciate some guidance on this. e.g. Can we keep it roughly as-is, calling out that `WebApplicationBuilder` uses `Host` underneath?

**Comment by guardrex** [comment]
Given that the project templates favor `WebApplicationBuilder`, it seems like the doc should favor it, too. The current guidance remains, but it seems like it would be deemphasized. Doesn't the PU favor devs using Minimal APIs from this point forward?

**Comment by Rick-Anderson** [comment]
> Given that the project templates favor `WebApplicationBuilder`, it seems like the doc should favor it, too. The current guidance remains, but it seems like it would be de-emphasized. Doesn't the PU favor devs using Minimal APIs from this point forward?

Agree

**Comment by guardrex** [comment]
... and side-note on the ref source link if it ends up that way. If you want, there's an INCLUDE to help devs get the right branch at ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/aspnetcore-repo-ref-source-links.md


```
[!INCLUDE[](~/includes/aspnetcore-repo-ref-source-links.md)]
```

Example usage in a live doc ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/persist-component-state?view=aspnetcore-6.0#persist-state-for-prerendered-components
