### ISSUE TITLE
link to Blazor WASM setup/app

### ISSUE THREAD

**Issue by SogoGolf** [dotnet/AspNetCore.Docs#24103]
hi, i came here looking for a link to guide me through setting up a Blazor WASM app, however all i can see is a link for Blazor server side. Can you please add that link here ? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 089d24e3-8ebb-f65c-0044-10ca7af02895
* Version Independent ID: 91951296-594a-17e9-453e-711f50e031a7
* Content: [ASP.NET Core Blazor tutorials](https://docs.microsoft.com/en-au/aspnet/core/blazor/tutorials?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/tutorials.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SogoGolf ... Management decided that Blazor Server is the default tutorial for a *first* experience and that we won't maintain a matching Blazor WebAssembly tutorial. For Blazor WebAssembly, you should be able to jump directly to the ToDo List tutorial.

The Todo List tutorial uses the .NET CLI. If you prefer to use Visual Studio, there's guidance for creating a Blazor WebAssembly app in the Tooling article.

* https://docs.microsoft.com/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-6.0&pivots=webassembly
* https://docs.microsoft.com/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=windows

**Comment by SogoGolf** [comment]
oh, why is that? 
maybe add a note to explain that so folks like me don't think there are no getting started tutorials for Blazor WASM.

**Comment by guardrex** [comment]
It was decided to take this approach to simplify the adoption of Blazor by making the decision for first-time Blazor users. Having to decide on the hosting model immediately isn't something that management wants developers to be concerned about on first use. I'll add the hosting model in parentheses to each entry. Thanks for the suggestion.
