### ISSUE TITLE
The tutorial skips creating SeedData.cs

### ISSUE THREAD

**Issue by Firesong25** [dotnet/AspNetCore.Docs#24105]
The tutorial says to edit SeedData but that class has never been added to the solution.  When I try to manually add it, it fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Part 7, add a new field](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @Firesong25. There's a step in part 4, [Seed the database](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-6.0&tabs=visual-studio#seed-the-database-2), that shows creation of the `SeedData` class.

**Comment by Firesong25** [comment]
I'm an idiot.  Thanks!
