### ISSUE TITLE
Demote the hyperlink to Understanding HTML Helpers

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/AspNetCore.Docs#24106]
> while [HTML Helpers](https://stephenwalther.com/archive/2009/03/03/chapter-6-understanding-html-helpers) are invoked

The target page is buggy and unmaintained.  I understand it is an attempt to get crowd-sourced proofreading (which is, in itself, commendable, of course).  It is not even meant to be there any more:

> When [the book](https://www.amazon.com/ASP-NET-Framework-Unleashed-Stephen-Walther/dp/0672329980/ref=pd_bbs_sr_1) is published, the text from this blog entry will be removed

Having the link in the running content creates an impression of endorsement.  If it is to stay on the page, it should be demoted to a **See Also** section as historical.  It cannot be rewritten (otherwise than from scratch) because it is unlicensed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Stephen Walther was working for MS when he authored that.
