### ISSUE TITLE
_defaultFormOptions variable not declared

### ISSUE THREAD

**Issue by massimoforni-turboden** [dotnet/AspNetCore.Docs#24107]
The variable _defaultFormOptions is not declared anywhere nor the document explains where it come from 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the sample apps (earlier than the 5.x sample) at ...

* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Controllers/StreamingController.cs#L32
* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads/samples/2.x/SampleApp/Controllers/StreamingController.cs#L32

The strange thing is that the 5.x version of the topic is referring to the 3.x sample app for this bit. This isn't in the 5.x sample app, which isn't our normal approach (i.e., when 3.x drops, this setup is going to drop coverage for 5.x or require work to get this code into the 5.x sample).

**Comment by Nova-Logic** [comment]
it's still not declared in .net core 7
