### ISSUE TITLE
I can't PUT "secret"

### ISSUE THREAD

**Issue by BOBOfra** [dotnet/AspNetCore.Docs#24108]
Before implement the TodoItemDTO class I've tested the Todo class adding the Secret field. As it turns out, I can get the secret field, and I can post it. But i can't PUT an already existent item in order to change the secret field. If i try to do it, only Name and isComplete fields changes, but Secret is still the same.
That's normal? How can I fix it?

Visual studio 2022, .NET 6.0

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
