### ISSUE TITLE
Improve Accessibility for New and Neurodivergent Developers Request

### ISSUE THREAD

**Issue by JustinErdmier** [dotnet/AspNetCore.Docs#24114]
I am both a brand-new developer and autistic. In learning more about C# and .NET (especially .NET 6), I find myself living inside the documentation. However, I've found the Minimal APIs Overview page to be unfriendly for new developers and non-accessible for neurodivergent developers.

**Improving Accessibility for New Developers**
The documentation for minimal APIs was written with the heavy assumption that the developer has an extensive understanding ASP.NET and developing APIs within the ASP.NET environment. Without branching out of the page's scope, adding a section to the top of the page explaining the expected level of understanding and depth of knowledge would be helpful. In addition, a list of navigational links to other areas of the docs, listed as "prerequisite knowledge" or something akin, would be amazing.

**Improving Accessibility for Neurodivergent Developers**
Along with the assumptions regarding the developer's experience/understanding, the structure and presentation of the page is not neurodivergent friendly. The description of minimal APIs is almost non-existent, comprising of a barebones 3-point bullet list. There is no clear transition or order of the sections, and again, they are written assuming extensive knowledge. And finally, the docs consistently refer to the ASP.NET Core Web App (the empty project template). It offers no overview of the handful of project templates available in VS (i.e., comparing the referenced empty web app to the available web app API project template).

One of the things autistic people, like myself, really struggle with is needing to know _**why**_ something is the way it is and struggling to "just accept it" or "move on" if we don't have a proper answer as to that. It would mean a lot if this understanding were prioritized when writing documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> One of the things autistic people, like myself, really struggle with is needing to know _**why**_ something is the way it is and struggling to "just accept it" or "move on" if we don't have a proper answer as to that. It would mean a lot if this understanding were prioritized when writing documentation.

I think needing to know _**why**_  is beneficial to everyone. Thanks for your feedback and we'll try to keep that in  mind.
