### ISSUE TITLE
--razor-runtime-compilation is not a valid option in net6.0

### ISSUE THREAD

**Issue by solrevdev** [dotnet/AspNetCore.Docs#24111]
Since I've upgraded from .NET 5 to .NET 6 conditional razor runtime compilation no longer works. 

So, in an effort to debug why it's stopped working I noticed that even the `dotnet new ` switch example from the doc does not work either. 

For example: 

```bash
dotnet new webapp --razor-runtime-compilation

Error: Invalid option(s):
--razor-runtime-compilation
   '--razor-runtime-compilation' is not a valid option

For more information, run:
   dotnet new webapp -h
``` 

Could the document be updated with the latest instructions on how to get razor runtime compilation working again as it used to in .NET 5. Making a change to a .cshtml during development should cause a recompile etc.

.NET info

```bash
 dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Computer info

```bash
OS: macOS 11.6 20G165 x86_64
Host: Macmini7,1
Kernel: 20.6.0
Uptime: 7 days, 4 hours, 20 mins
Packages: 313 (brew)
Shell: zsh 5.8
Resolution: 2560x1440
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: AnonymicePowerline 14
CPU: Intel i5-4278U (4) @ 2.60GHz
GPU: Intel Iris
Memory: 10445MiB / 16384MiB
```

And for completeness, in .NET 5 this is all I had to do in order to get my project compiling razor pages in development 

launchSettings.json
 
```json
{
"web": {
            "commandName": "Project",
            "dotnetRunMessages": true,
            "launchBrowser": true,
            "applicationUrl": "https://localhost:5001;http://localhost:5000",
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development",
                "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation",
                "ASPNETCORE_HTTPS_PORT": "5001"
            }
        },
}
```

launch.json
```json
{
    "name": ".NET Core Launch (web)",
    "type": "coreclr",
    "request": "launch",
    "preLaunchTask": "build",
    "program": "${workspaceRoot}/src/web/bin/Debug/net6.0/web.dll",
    "args": [],
    "cwd": "${workspaceFolder}/src/web",
    "stopAtEntry": false,
    "internalConsoleOptions": "openOnSessionStart",
    "launchBrowser": {
        "enabled": true,
        "args": "${auto-detect-url}",
        "windows": {
            "command": "cmd.exe",
            "args": "/C start ${auto-detect-url}"
        },
        "osx": {
            "command": "open"
        },
        "linux": {
            "command": "xdg-open"
        }
    },
    "env": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation"
    },
    "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
    }
}
```

and in my csproj file

```xml
 <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0" />
```

Can I also add that adding `AddRazorRuntimeCompilation()` to my `services.AddRazorPages()`  does work but hot reload does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by andrerom** [comment]
Similar issue, on .net 6 can't get Hot Reload to work on Mac M1 (Arm) , and seems RuntimeCompilation only works if I add `AddRazorRuntimeCompilation()` in `Startup.cs`.

Settings in `launch.json` seems to not be picked up anymore after upgrade to .net 6 here on my setup.
