### ISSUE TITLE
.NET 6: Distributed caching in ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24121]
V6 code was added in #24363
Now just update the doc to use the new code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by smandia** [comment]
@Rick-Anderson  will this be a tough nut to crack or an attempt can be given

**Comment by Rick-Anderson** [comment]
@smandia yes, let me know how I can help. I have fixed the monikers for you. Create a new 6.x fold in the samples directory for the 5.0 sample app. Update the markdown in the `::: moniker range=">= aspnetcore-6.0"` section at the top of the file.

**Comment by smandia** [comment]
@Rick-Anderson  Can I create a new sample in the folder that I will create with name as 6.x and not copy over the proj from 5.x folder and keep the baseline same in terms of content (apart the startup and program cs change) and also update the documentation or am i missing the bigger picture

**Comment by smandia** [comment]
@Rick-Anderson  The code is work in progress but I am stuck at one place.  your guidance might be helpful. 
How to mimik or write fresh part.

5.x example in configure method for lifetime applicationstarted

 public void Configure(IApplicationBuilder app, IWebHostEnvironment env,
            IHostApplicationLifetime lifetime, **IDistributedCache cache**)
        {
            lifetime.ApplicationStarted.Register(() =>
            {
                var currentTimeUTC = DateTime.UtcNow.ToString();
                byte[] encodedCurrentTimeUTC = Encoding.UTF8.GetBytes(currentTimeUTC);
                var options = new DistributedCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromSeconds(20));
                **cache.**Set("cachedTimeUTC", encodedCurrentTimeUTC, options);
            });

And the new one for 6.x

var app = builder.Build();

app.Lifetime.ApplicationStarted.Register(() =>
{
    var currentTimeUTC = DateTime.UtcNow.ToString();
    byte[] encodedCurrentTimeUTC = System.Text.Encoding.UTF8.GetBytes(currentTimeUTC);
    var options = new DistributedCacheEntryOptions()
        .SetSlidingExpiration(TimeSpan.FromSeconds(20));
**last time to set cache** 
});

I cannot seem to figure how to write the last line in dotnet 6.x

Random thoughts 
1. Should I create an implementation of Idistributable cache and then use dependency injection or something 
your guidance here would be helpul

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  can you help out? We might need to wait until next year, everyone is on holiday.

**Comment by smandia** [comment]
@Rick-Anderson  @fiyazbinhasan  I figured out it will be AddSingleton . Many thanks and have a great holiday.

**Comment by fiyazbinhasan** [comment]
@smandia poke me if you need a hand 🙂
