### ISSUE TITLE
Add async example for Bearer token authentication gRPC client factory

### ISSUE THREAD

**Issue by ferronsw** [dotnet/AspNetCore.Docs#24132]
This [paragraph](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-6.0#bearer-token-with-grpc-client-factory) describes how to setup the client factory. It also show how to provide a token. I tried making this method async, but when I do that it doesn't work anymore. Please provide an example how to provide a token using an async method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 363b40bb-4e20-e4b3-4456-5eb8fe6b30fb
* Version Independent ID: 8a7e85b0-5c1c-969d-9748-5e5e2dc45cce
* Content: [Authentication and authorization in gRPC for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/authn-and-authz?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
Are you using the latest version of Grpc.Net.Client?

**Comment by ferronsw** [comment]
I see that version 2.32.0 is installed by the connected services wizard.

**Comment by JamesNK** [comment]
And do you still have this problem after updating to the latest version?

If you still have problems, upload a reproduction of what you're doing and I can take a look at it.

**Comment by ferronsw** [comment]
` services
            .AddGrpcClient<GreeterClient>("GreeterAuthenticated", o =>
            {
                o.Address = new Uri("https://localhost:5001");
            })
            .ConfigureChannel((provider, options) =>
            {
                var scopeFactory = provider.GetRequiredService<IServiceScopeFactory>();
              
                var asyncAuthInterceptor = new AsyncAuthInterceptor(async (authUri, metadata) =>
                {
                    using (var scope = scopeFactory.CreateScope())
                    {
                        var tokenAcquisition = scope.ServiceProvider.GetRequiredService<ITokenAcquisition>();
                        var token = await tokenAcquisition.GetAccessTokenForUserAsync(new string[] { "<scope>" });
                        metadata.Add("Authorization", $"Bearer {token}");
                    }
                });

                options.Credentials = ChannelCredentials.Create(new SslCredentials(),
                    CallCredentials.FromInterceptor(asyncAuthInterceptor));
                
            });
`

This works, but I don't know if this is the way to go.

**Comment by wadepickett** [comment]
I'm in the middle of updating this topic for v6, so I am assigning the issue to myself to make sure I include this in the update, however it works out.  @JamesNK, I will watch for your recommendation.

**Comment by JamesNK** [comment]
This seems like a product bug. If it doesn't work then create an issue at https://github.com/grpc/grpc-dotnet

**Comment by wadepickett** [comment]
Closing per JameNK conclusion this may be a product bug.  Feel free to reopen if needed.  Thanks for raising awareness.  Product issues can be created here: https://github.com/grpc/grpc-dotnet
