### ISSUE TITLE
Debug standalone Blazor WebAssembly in Visual Studio Code - .NET 6 - not working

### ISSUE THREAD

**Issue by hkusulja** [dotnet/AspNetCore.Docs#24137]
Please check and update documentation for "Debug standalone Blazor WebAssembly" in "Visual Studio Code" (on Windows).
I have Windows 11, .NET 6 SDK, VS Code and mentioned extensions, all in stable/production latest versions.
However still mentioned notification is raised up (Additional setup is required to debug Blazor WebAssembly applications).

Maybe you can document expected launch.json and tasks.json.

Start debugging starts listening on port http and https, but it does not open browser (Edge) , nor is connected anyhow to app and breakpoint is not working

If I start from VS Code Terminal > dotnet watch (with hot-reload), then it is opening Edge, but still no breakpoints are triggered.

Please clarify, test and update documentation. Thank you

mentioned launchSettings.json is not existent / not used in VS Code and default launch.json is:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

Repro steps:
1. Use Windows 10 or Windows 11
2. Install latest stable VS Code
3. Install mentioned VS Code extensions , https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.blazorwasm-companion and https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
4. Create a new folder / project with dotnet new blazorwasm
5. dotnet build
6. set debugging in Counter.razor on line counter++;
7. Start debugging (F5)
8. Open Edge browser to your URL (example: https://localhost:7173/ )
9. Click button click me on counter page, nothing is happening on breakpoint in VS Code
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?tabs=visual-studio-code&view=aspnetcore-6.0#vscode)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hkusulja ... Your repro steps don't mention following the guidance of Step 6 in ...

https://docs.microsoft.com/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux

... and if you prefer Edge, add the setting to `.vscode/launch.json` for it ...

```
"browser": "edge"
```

**Comment by hkusulja** [comment]
@guardrex thank you for fast response.
I do not know why your referenced docs are saying pivots=linux, since I am using VS Code on Windows.
I do not have nor use Chrome, i do have only edge, and added "browser": "edge", "url": "http://localhost:5073"
now the edge is opening, but still no breakpoint is not triggered.
Also, mentioned launchSettings.json exists and is used with Visual Studio and IISExpress, which is not my case at all.

Can you please help / advise, what other information you need more, and were you able to repro the issue?

**Comment by guardrex** [comment]
I don't think I've attempted it under 6.0, which just released. I don't see any issues about the guidance not working on the product unit's repository.

Your configuration seems correct. I'll try it here and see what happens in a few minutes. I'll get back to you.

"WRT" == "With Regard To"

**Comment by guardrex** [comment]
I don't see a problem here ...

<img width="336" alt="Capture" src="https://user-images.githubusercontent.com/1622880/144122981-04b9047b-cb11-4f39-9728-5c2bd95aff7b.PNG">

I note that you seem to be trying to use the insecure endpoint (HTTP). Try the secure endpoint (HTTPS)

If it doesn't work at the secure endpoint, open an issue for investigation on the product unit's repo at ...

https://github.com/dotnet/aspnetcore/issues

Provide that setup that you described here :point_up:. You can let them know that I tried the guidance but that I couldn't repro a problem.

Please add a `cc: @guardrex` to the bottom of your opening comment. I'll keep an 👁️ on the discussion. If it turns out that we need to modify the guidance, I'll re-open this issue. If you don't add a CC for me, that's ok, too. You can come back to this issue and leave a comment on what the problem turned out to be, then I'll re-open the issue if we need to make an update to the topic.

**Comment by hkusulja** [comment]
Yes, no variable value during debugging, and it is not triggered still, tried on my several computers.
Tried on https (trusted cert) and http, both should work but none of them does. 
Thank you for trying and confirming it works for you.

**Comment by bamers-nlp** [comment]
I'm having the same problem. I copied your files into a brand new blazor wasm app and the browser crashes 
> Unable to launch your browser: "Could not connect to debug target at http://localhost:9222: Could not find any debugging target"
