### ISSUE TITLE
Razor tutorial: How to use custom templates

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/AspNetCore.Docs#24147]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs:  custom template
- Tell us what docs you found that didn't address your concern.: nothing for Razor

**Describe the new topic**

- Explain why this topic is needed.
  1. Customising how a model property is displayed is a very common need.
- Suggest a location in the Table of Contents.
  1. A section in [Step&nbsp;5 of the Razor tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1).
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
  1. It is possible and fairly easy to alter the default rendering used by [Html.DisplayFor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.rendering.ihtmlhelper-1.displayfor#Microsoft_AspNetCore_Mvc_Rendering_IHtmlHelper_1_DisplayFor__1_System_Linq_Expressions_Expression_System_Func__0___0___System_String_System_String_System_Object_).
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
  1. How you can use the [UIHint attribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.uihintattribute) to specify a custom template to render the Release date.
  2. How to code the template to render the release year as a Roman numeral. Note: this would be the only documentation available for this feature.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/

**Comment by yecril71pl** [comment]
OK, it seems I have to write it myself (for anyone else interested).  I do not submit it because it is obviously too sketchy and I have no intention to sabotage your current work.

File `Models/MovieDateFixed.cs`
```csharp
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RazorPagesMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; } = string.Empty;

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [UIHint("RomanYear")]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; } = string.Empty;

        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }
    }
}
```

File `Pages/DisplayTemplates/RomanYear.cshtml`
```cshtml
@model DateTime
@(
    RomanNumeral .ToString (this .Model .Year)
)

```

Writing a class `RomanNumeral` with a static method `ToString` is left as an exercise to the reader.

**Comment by Rick-Anderson** [comment]
@serpent5  do you think we should invest  in this ?

**Comment by yecril71pl** [comment]
> A custom Tag Helpers would be the right approach

Requires dotnet/aspnetcore#3956

**Comment by serpent5** [comment]
@Rick-Anderson I agree with your original assessment. Given the current 6.0 focus, we should leave this one here and see if it generates some interest.
