### ISSUE TITLE
Identity Server is not Open Source

### ISSUE THREAD

**Issue by gabriel-ayusso** [dotnet/AspNetCore.Docs#24157]
Hi there,

I was working with IS, but when I've updated to AspNet Core 6.0 I noticed that IS is now provided by Duende and its product is not Open Source.  As I understand, this page would list only Open Source Software (OSS), right? 

Ssorry if I've misunderstood it.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a218cc00-a5c0-717e-5b42-5efd6caf8abb
* Version Independent ID: 69bded75-ba42-d3ff-f27b-f7e715f6d2f8
* Content: [Community OSS authentication options for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/community.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gabriel-ayusso ... "Open source" and requiring a license are different concepts. It's still open source by definition. For more info, see ...

https://docs.microsoft.com/aspnet/core/migration/50-to-60#project-templates-use-duende-identity-server

**Comment by gabriel-ayusso** [comment]
> Hello @gabriel-ayusso ... "Open source" and requiring a license (for production) are different concepts. It's still open source by definition. For more info, see ...
> 
> * https://docs.microsoft.com/aspnet/core/migration/50-to-60#project-templates-use-duende-identity-server
> * https://github.com/DuendeSoftware/IdentityServer

Hi @guardrex , 

I understood what you mean, but disagree since the Open Source definition says:
"Open Source software is software that can be freely accessed, used, changed, and shared (in modified or unmodified form) by anyone"

For more info, see ...
* https://opensource.org/osd

**Comment by guardrex** [comment]
You can do all of those things. You just can use anything from the fork commercially without a license in production for commercial purposes. Their license is here ...

https://duendesoftware.com/license/identityserver.pdf

... and it is open source by definition. The RPL license is an open source license ...

https://opensource.org/licenses/RPL-1.5
