### ISSUE TITLE
Documentation is missing code? Blank example

### ISSUE THREAD

**Issue by martinandersen3d** [dotnet/AspNetCore.Docs#24156]
[Enter feedback here]

One of the code examples is blank

Link:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio-code#performance-considerations

Screenshot:
![image](https://user-images.githubusercontent.com/19984581/144316301-10fd8d24-dacc-4eb0-8e96-ad57e2535451.png)

@Rick-Anderson 
@guardrex 
@dharmatech 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio-code#performance-considerations)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@martinandersen3d  thanks for reporting this. Fix should be live in 24 hours.
