### ISSUE TITLE
Http Based Response Caching-Need Clarification

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24176]
In description regarding Public Cache-Control it is said that:
**"Location.Any (Cache-Control set to public) indicates that the client or any intermediate proxy may cache the value, including Response Caching Middleware."**
Does Asp.Net Server Cache the response too?! And If the server does not cache the response (which I think this is the case) what the "**including Response Caching Middleware**" means here?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-6.0)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... Response Caching Middleware is covered here ...

https://docs.microsoft.com/aspnet/core/performance/caching/middleware

The server doesn't cache the response outside of that middleware or other caching approaches that might be in use. See https://docs.microsoft.com/aspnet/core/performance/caching/middleware#caching-respects-request-cache-control-directives.

**Comment by abdollahkahne** [comment]
Thanks for your clarification.
