### ISSUE TITLE
Identity without scaffolding

### ISSUE THREAD

**Issue by died** [dotnet/AspNetCore.Docs#24181]
[Enter feedback here]

Can we have a version Identity not scaffold, is Controller, so It can fit MVC, not spread code to dozens files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, Identity is provided as Razor Pages.

**Comment by died** [comment]
> No, Identity is provided as Razor Pages.

So any way can transfer Razor Pages style to MVC style ?
Razor Identity was unfriendly and hard to maintain if you are not only doing hello world.
