### ISSUE TITLE
Needs to be updated for .Net 6 templates

### ISSUE THREAD

**Issue by tabinnorway** [dotnet/AspNetCore.Docs#24190]
Needs to be updated for .Net 6 templates. They do not user Startup.cs.
This article assumes you are using .Net 5 templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello ... This is a duplicate. The work is already in progress on the PR at https://github.com/dotnet/AspNetCore.Docs/pull/23989.
