### ISSUE TITLE
Do not call BuildServiceProvider in docs, samples

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#24204]
The ["Customize WebApplicationFactory"](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#customize-webapplicationfactory) section should not recommend calling `BuildServiceProvider`, this pattern can cause lifetime issues with services.

Multiple alternatives are given in https://github.com/dotnet-architecture/eShopOnWeb/issues/465. @javiercn may also have some input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#customize-webapplicationfactory)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@javiercn  we can fix this as soon as you provide input.

**Comment by Rick-Anderson** [comment]
@jvandertil please review

**Comment by sevenmay** [comment]
Hi @Rick-Anderson 

Ok, this is bad.
```
protected override IHost CreateHost(IHostBuilder builder) {
  builder.ConfigureServices(services => {
    //...
    var sp = services.BuildServiceProvider();
    //...
  }
}
```

In the new docs you cut this (at least I can't find it).
I don't know if I have missed something, but what's the correct way to get a service from the DI in ConfigureServices? Or is it bad practice?
What if I want to seed the DB once per WebApplicationFactory?

Thanks

**Comment by Tratcher** [comment]
@sevenmay services shouldn't be built/consumed in ConfigureServices, you're still setting them up.

Here are some tips for seeding a database:
https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0#initialize-db-with-test-data
