### ISSUE TITLE
Chinese and English translations show inconsistent results

### ISSUE THREAD

**Issue by 1301536601** [dotnet/AspNetCore.Docs#24209]
[Enter feedback here]

![image](https://user-images.githubusercontent.com/33918700/144987058-e7431d1d-ff52-4c50-9f21-6dc60b2f5b47.png)

The English result is:

builder.Services.AddSingleton(new Service1());
builder.Services.AddSingleton(new Service2());

But the Chinese version is shown below

![image](https://user-images.githubusercontent.com/33918700/144987090-17985141-b2c8-4ac9-b433-196f7b36c51c.png)

builder.Services.AddSingleton<Service1>();
builder.Services.AddSingleton<Service2>();

The results of the Chinese presentation are very different. Looking forward to hearing from you soon
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0#services-not-created-by-the-service-container)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Let's keep this open for now.  @1301536601  can you let us know if this isn't fixed within a week? I don't think this doc is human translated. It should update snippets by now.

**Comment by guardrex** [comment]
I think ur right ... looks like it's merely due to a delay in the MT schedule for the whole repo. The French version of the doc is the same ...

https://docs.microsoft.com/fr-fr/aspnet/core/fundamentals/dependency-injection

... and the Mexican version ...

https://docs.microsoft.com/es-mx/aspnet/core/fundamentals/dependency-injection

... and probably the rest as well. IIRC, it took over two weeks for the MT updates to land after my problems with Version by File broke localized docs. I don't think it took more than three weeks.

**Comment by Rick-Anderson** [comment]
@khoiph1 why is there a 3 week delay in MT of this content? Can we do anything to speed that up?

**Comment by 1301536601** [comment]
> 

It has been solved for now

**Comment by 1301536601** [comment]
> 让我们暂时保持开放。 @1301536601 如果这周内没有解决，你能告诉我们吗？我不认为这个文档是人工翻译的。它现在应该更新截图。

It has been solved for now

**Comment by Rick-Anderson** [comment]
@1301536601  thanks for reporting back.

@khoiph1 why is there a 3 week delay in MT of this content? Can we do anything to speed that up?
