### ISSUE TITLE
Client-side load-balancing and gRPC over HTTP/3?

### ISSUE THREAD

**Issue by khteh** [dotnet/AspNetCore.Docs#24207]
[Enter feedback here]
It's mentioned that k8s using network load balancer is not effective for the use case of gRPC over HTTP/2. How about HTTP/3 when it is supported in .Net 7? Would this feature still make sense or it becomes obsolete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac62acc-1270-cc98-024e-659b3a80f4ca
* Version Independent ID: d6f25885-6c43-0d2c-96e2-3b47a4fd7bd7
* Content: [gRPC client-side load balancing](https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/loadbalancing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/loadbalancing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
I don't know what support the default Kubernetes service load balancer has for HTTP/3. It's still useful if you want to customize how load is distributed.

**Comment by wadepickett** [comment]
Closing.  @JamesNK, feel free to re-open if you want me to add info here for the topic.
