### ISSUE TITLE
Nuget version compatible for Dotnet Core 3.1

### ISSUE THREAD

**Issue by nguqtruong** [dotnet/AspNetCore.Docs#24210]
In the doc for version 3.1, the command to install package failed because of version compatibility. 

For example, when I run `dotnet tool install --global dotnet-aspnet-codegenerator `. The error appears:
```
error NU1202: Package dotnet-aspnet-codegenerator 6.0.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package dotnet-aspnet-codegenerator 6.0.0 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
The tool package could not be restored.
Tool 'dotnet-aspnet-codegenerator' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

Suggestion:
- Update the command to include the package version like `dotnet tool install --global dotnet-aspnet-codegenerator  --version 3.1`
- Remove the comand `dotnet tool update -g Dotnet-aspnet-codegenerator`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Thanks for reporting this, @nqtrg. Would you be interested in fixing this via a Pull Request?

**Comment by Rick-Anderson** [comment]
@nqtrg  why are you on 3.1?  We've never updated our tutorials for this common issue because:

* Folks that knowingly are working with older versions typically know how to use  `global.json` to set the version or how to explicitly set the version. In this case the error message was very good, making it easy to resolve the issue.
* They don't typically installed newer versions if they're targeting an older version.
