### ISSUE TITLE
Opening and closing port at runtime

### ISSUE THREAD

**Issue by adamradocz** [dotnet/AspNetCore.Docs#24219]
I'm not sure that I'm submitting this issue on the correct repo.
I need a solution to open/close/change a port on the kestrel at runtime, but I haven't found anything about that. All the articles show how to change the listening port when you configure the kestrel, but not at runtime.

Is there any way to do it?

Thank you in advance!

**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
  - "asp.net core open a new port at runtime"
  - "asp.net change listening port at runtime"
- Tell us what docs you found that didn't address your concern.
  - I haven't found any docs about the topic.

**Comment by guardrex** [comment]
Hello @adamradocz ... Indeed, that's not configurable AFAIK. Could you ask the product unit directly and explain why you want that feature at ...

https://github.com/dotnet/aspnetcore/issues

If I'm correct about the lack of a feature, they might entertain it as a feature in a future release.

**_Please add a `cc: @guardrex` to the bottom of your opening comment._** I'd like to follow the discussion. I'll re-open this issue if there's something we need to add to the Kestrel docs.
