### ISSUE TITLE
Increase width for code on pages, or rework the layout for pages

### ISSUE THREAD

**Issue by ZooDoo4U** [dotnet/AspNetCore.Docs#24223]
It would be great and a lot less frustrating to see all the code in coding samples on the MSDN/Microsoft docs page(s).  Please look at the attached screen shot, simply seems crazy to artificially make reference pages hard to use.  Really is more of a pain not to be able to see all the source...

![image](https://user-images.githubusercontent.com/11509268/145114095-7e083a78-f2aa-4ff6-a5b4-f6d267111bb4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ZooDoo4U ... We don't control the layout aspect of the docs here. We only work on the content for ASP.NET Core. Please provide your feedback at ...

https://github.com/MicrosoftDocs/feedback/issues

**Comment by Rick-Anderson** [comment]
@ZooDoo4U we do have a goal of minimizing the need for the horizontal scroll bar.
PR #24224 eliminates the need for a horizontal scroll bar on a tablet sized display (widest window with no left or right TOC).

**Comment by guardrex** [comment]
I thought the ask was for content that fills 100% of the width of the main container. I apologize if I misunderstood. If the ask were for that tho, it would have to go to the other repo, as that layout aspect isn't controlled here, @ZooDoo4U.

**Comment by Rick-Anderson** [comment]
@guardrex  I read it the same way, however he did comment 
![image](https://user-images.githubusercontent.com/3605364/145119587-00870972-bac0-4fd8-9323-cc7bd19b4506.png)

So I thought I'd fix that.

**Comment by Rick-Anderson** [comment]
@ZooDoo4U  we try to balance showing what code we think is necessary to explain the topic. We usually provide a link to the full source

![image](https://user-images.githubusercontent.com/3605364/145119765-4ade35e0-dacf-400e-a8fe-eaadfaa91d04.png)

**Comment by guardrex** [comment]
I suspect it would only be *"most code"* tho on a narrower screen than the docs are laid out to support. It might be that they should consider how they use a menu (the olde' hamburger!) at a larger width layout than they currently do ... and thus lose one of the sidebars sooner (narrower) ... thus all of our code samples would look good on @ZooDoo4U's screen. It seems like that one fix for this one code block example isn't going to solve all of @ZooDoo4U's woes and pain around the repo.

**Comment by guardrex** [comment]
Yeah tho ... that one was CrAzY LoNg!!! 😵 

```csharp
_logger.LogInformation("Queued Background Task {Guid} is running. " + "{DelayLoop}/3", guid, delayLoop);
```

**Comment by Rick-Anderson** [comment]
And it was already set up to break up.  Why is that string split up with a `+` if you're not going to put it on a new line.

**Comment by guardrex** [comment]
I didn't leave it that way. See what I mean, @serpent5 ???? .....

# 👽

*They are among us!*

**Comment by ZooDoo4U** [comment]
The issue is the page appears to be responsive in design but in the worst way.  Sure the content resized based on the screen display, but it seems (estimating it) 35%->40% of the screen is simply eaten up by white space for not reason.  Really seems as is it is the worst user experience.  Specifically the nav for topics on the left and the "This article summary" on the right,  can't be hidden/collapsed, and the section for the code,  which I'd assert is the main thing most people will want to see gets the lowest priority on the resize.   Would assert on smaller/narrower screens hide or compress both the nav and "in this article first.  The main section with the textual description and code shouldn't be clipped and fully visible if desired?

**Comment by Rick-Anderson** [comment]
@ZooDoo4U  as @guardrex  stated, all of `docs.microsoft.com`  uses the same system. We're less than 1% of that. We don't disagree with you but this has been brought up many times at https://github.com/MicrosoftDocs/feedback/issues (where @guardrex  said it needs to be reported). You could upvote an issue there and voice your opinion.
