### ISSUE TITLE
Add headers (and/or <head> content) dynamically to Blazor apps

### ISSUE THREAD

**Issue by christianAtSuddath** [dotnet/AspNetCore.Docs#24237]
This page is helpful, but instead of just highlighting the shortcoming of the meta tag, it should have pointed to where in startup.cs or elsewhere the appropriate CSP header could have been added with code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88177a7d-c9ff-c245-5629-a462c9258abf
* Version Independent ID: 6e0b5c52-90a1-5ca6-bfad-df33a8beae6c
* Content: [Enforce a Content Security Policy for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/content-security-policy.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/content-security-policy.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @christianAtSuddath ... Clarify what you mean by "shortcoming." What are you trying to accomplish? Are you interested in a  dynamic calculation of hashes at build/publish time?

**Comment by damienbod** [comment]
If you use a hosted WASM, you can still define this dynamically in the startup or the program class, this is what I always do. Here's an example:

https://github.com/damienbod/Blazor.BFF.AzureAD.Template/blob/main/content/BlazorBffAzureAD/Server/Startup.cs#L69-L71

You just need to host the project using a razor page and not a static html. 

Greetings Damien

**Comment by guardrex** [comment]
That's a good one as well given that for the prerendering hosted WASM scenario **_the server app is taken off of serving the static html file in favor of the `_Host` page_**.

BTW for full disclosure on the static approach ... I believe it would go like this ...

```csharp
var staticFileOptions = new StaticFileOptions
{
    OnPrepareResponse = context =>
    {
        context.Context.Response.Headers.Add("Content-Security-Policy", {POLICY STRING});
    }
};

...

app.MapFallbackToFile("index.html", staticFileOptions);
```

I haven't conferred with the PU (*yet*) on any of the approaches, so there might be some *gotchas* 😈 and additional considerations. For example, I doubt that caching is a problem given that we're dealing with Blazor apps, but it's best to confer with the PU on such things to confirm that any side-effects are dealt with or at least covered.

@christianAtSuddath ... I think what we'll do at this point is leave you with what we've discussed and then take this subject up with the PU ("product unit") engineers in '22. Everyone is bugging out for the ⛄ *holidays* right now and will return from vacations in '22. I recommend that you leave your **_exact use case_** here in an issue comment ...

* Exactly what are you trying to do with a dynamic policy? Is it for creating file hashes on-the-fly?
* What hosting model are you using (i.e., WASM, hosted WASM, prerendered hosted WASM, or Blazor Server).
* Are there any other details about your hosting environment that are relevant?

Side Notes:

* We can cover dynamic policy generation in a new section on this topic, but I feel that this subject generally lacks coverage. I like the idea of covering this subject somewhere in the *Fundamentals* node of topics. This subject both ...
  * Pertains to controlling head content (e.g., `<meta>` tags), so we might find a home for new guidance and/or a cross-link in the existing [*Control \<head> content* article](https://docs.microsoft.com/aspnet/core/blazor/components/control-head-content).
  * Pertains to setting headers on the server response for Blazor apps. New article, perhaps?
* It might not be helpful enough to merely explain controlling \<head> content and setting headers. If dynamic file hash calculation is a good scenario to explain, then we should probably show at least one or more examples (i.e., by hosting model) of how the PU recommends it be accomplished.

**_Leave this issue open. We'll get back to this after the holidays._**

**Comment by christianAtSuddath** [comment]
Hi Luke,

Thank you so much for the quick and insightful response!

The code snippet is basically what I was looking for! 😊

Our use case is an app that was started using the “DotNet angular” template and it was flagged by the OWASP process that it didn’t have the “X-Frame-Options” header or the CSP header with “frame-ancestors”. Since that can’t be added using meta tags, I needed to find another way.

So the feedback I left wasn’t exactly in the right place, although I was hoping that the startup.cs would be similar enough for both cases and the solution applicable. I think it is, so thank you again!

Christian Stahl
Director, Application Architecture
Suddath®
Mobilizing Opportunity℠

***@***.***

**Comment by guardrex** [comment]
Awesome, @christianAtSuddath ... that's what we needed. Yes, that falls more under my remark about covering this subject generally in the *Fundamentals* area of the articles. I think that's what we'll end up doing. WRT dynamic policies for this article, it's also worth considering, including a specific example. It would at least be a cross-link to *Fundamentals* coverage.

We'll pick this back up in '22. Thanks again for the issue and discussion.
