### ISSUE TITLE
Compare .NET 6 vs .NET 5 Directory browsing

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24239]
For the .NET 6 version, I removed
```
// using System.IO;
    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(
            Path.Combine(env.WebRootPath, "images")),
        RequestPath = "/MyImages"
    });
```

See [V6 Directory browsing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#directory-browsing) vs [V5 Directory browsing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-5.0#directory-browsing-1) vs 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#directory-browsing)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@serpent5  is that OK or should I have `@Tratcher` review the code I removed?

**Comment by serpent5** [comment]
In the screenshot for this section, we show links to the files, e.g. `banner1.svg`. The code you've removed adds the ability to serve the files behind the links, so without it, clicking on those links 404s. I think I'd include it for a more complete example, but it's up to you. I think we should be able to share the `FileProvider` instance between the two calls too, to make it slightly cleaner.
