### ISSUE TITLE
Startup V6 doc: Add ConfigureServices section from V5

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24241]
Add the content from [The ConfigureServices method](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-5.0#the-configureservices-method) and maybe some content from **The Configure method**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by smandia** [comment]
@Rick-Anderson - I tried to understand the intend here but could not quite get it what we intend to achieve. Apologies for my limited understanding.

**Comment by Rick-Anderson** [comment]
@smandia  sorry, it's in the title. Add ConfigureServices section to the ASP.NET Core 6.0 version from the ASP.NET Core 5.0 version. I'm not sure this is a good one for you to work on. I'll look for better candidates. Try [`is:open is:issue label:"Good first issue"`](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Comment by smandia** [comment]
@Rick-Anderson I will do as followed. However my question was more on the lines that in version 6.0 we do not have configureServices method/section due to  introduction of top level statements as all merged in program.cs, thus a bit  lost on what is the main intend. Apologies once again.
