### ISSUE TITLE
Missing Configuration Classes/Methods

### ISSUE THREAD

**Issue by JustinErdmierLieberman** [dotnet/AspNetCore.Docs#24267]
In DotNet 6, when building a Blazor Server Application, following the examples through the doc does not follow. Given the following excerpt:

"The following code:

Calls ConfigurationBinder.Bind to bind the PositionOptions class to the Position section.
Displays the Position configuration data.

```
public class Test22Model : PageModel
{
    private readonly IConfiguration Configuration;

    public Test22Model(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public ContentResult OnGet()
    {
        var positionOptions = new PositionOptions();
        Configuration.GetSection(PositionOptions.Position).Bind(positionOptions);

        return Content($"Title: {positionOptions.Title} \n" +
                       $"Name: {positionOptions.Name}");
    }
}
```
"

I do not have access to "Configuration.GetSection..." instead, I am given the following options:

- ConfigurationBuilder
- ConfigurationBinder
- ConfigurationSection
- etc

Please update to reflect changes made in Microsoft.Extensions.Configuration library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This all works for .NET 6. Have you downloaded the sample and tested it? You're probably missing an include.

**Comment by Rick-Anderson** [comment]
@JustinErdmierLieberman See [Bind hierarchical configuration data using the options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#bind-hierarchical-configuration-data-using-the-options-pattern)

I'm guessing you missed the step Create the following `PositionOptions `class:
