### ISSUE TITLE
update for Minimal API

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/AspNetCore.Docs#24273]
.net 6 `minimal api` resolved some issues mentioned there
([Notable missing features compared to Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-6.0#notable-missing-features-compared-to-web-api) section)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7abf4aa-38d6-0d52-3ca9-f1898eb5af91
* Version Independent ID: 410b4c9d-65f6-8f0e-ade9-9c93d9e4d98f
* Content: [Basic JSON APIs with Route-to-code in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/route-to-code?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/route-to-code.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/route-to-code.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
