### ISSUE TITLE
Confusing command line example when setting configuration

### ISSUE THREAD

**Issue by BonnieSoftware** [dotnet/AspNetCore.Docs#24276]
The example command on the page:

> dotnet run --MyKey "Using --" --Position:Title=Cmd-- --Position:Name=Cmd--Rick

Is confusing, the -- at the end of each value, and in the middle of the Position:Name value is really odd for an example, it is likely to confuse most, yet the example comes with no explanation as to what it is showing, and then even more frustrating is just below it, the previous two examples have explanations of what they are doing.

The example seems to be trying to demonstrate too much, it could easily be split into three examples like so:

> dotnet run --MyKey "MyValue"
> dotnet run --Logging:LogLevel:Default=Warning
> dotnet run --Command=Cmd-- --AlternativeCommand=Cmd--Run

With an explanation of whet each is showing.

At the moment it feels a bit like a guessing game.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-6.0#commandline-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See also #24277

**Comment by BonnieSoftware** [comment]
This has been marked as needs more info, but you've not said what info you don't get?
