### ISSUE TITLE
Setting switch values doesn't have an example of a single letter

### ISSUE THREAD

**Issue by BonnieSoftware** [dotnet/AspNetCore.Docs#24277]
There are examples showing:
-k1
-k2

but none showing -k or -a, which are much more likely to be used on a *nix machine.

Also, I think that on a *nix machine, **k1** would be `--k1` and **k2** would be `--k2`. Typically if you really did mean **-k2**, this would equate to `-k -2` on a *nix machine.

I get that the examples are supposed to be for all operating systems, but I suspect they will confuse some.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-6.0#commandline-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BonnieSoftware** [comment]
I've also proposed a change to the way command line arguments are parsed too (https://github.com/dotnet/aspnetcore/issues/38967), which in itself would alleviate the confusion if implemented.

**Comment by Rick-Anderson** [comment]
Moved to #24276

**Comment by BonnieSoftware** [comment]
I also don't understand why this was merged into #24276 when the two are unrelated, #24276 is about the examples being confusing, so need explanations to accompany them, and this issue is more so a question based on a feature that doesn't exist yet that may not be desirable to add to .NET Core given not all *nix apps follow the convention stated, along with an explanation to make it clear not all *nix conventions are followed. I've found a page showing some of the linux command conventions I'm referring to, that are not supported out the box: https://nullprogram.com/blog/2020/08/01/
