### ISSUE TITLE
Remove app.UseDeveloperExceptionPage();

### ISSUE THREAD

**Issue by gjuwindev** [dotnet/AspNetCore.Docs#24281]
This page says that some things are in Program.cs, but they are not

Namely, they are not there at the time of building the project from scratch, but will be added later in this list of short tutorials. 

It is confusing for a beginner to read such inaccurate info. Should be corrected. 

Thnx  :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @gjuwindev. Thanks for reporting this.

I see the following that's not part of the template:

- The call to `AddDbContext`: This is added in the next tutorial part [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio#scaffold-the-movie-model).
- An explicit call to `AddDveloperExceptionPage`. This should be removed as it's no longer needed.

**Comment by Rick-Anderson** [comment]
> * An explicit call to `AddDveloperExceptionPage`. This should be removed as it's no longer needed.

The preview version I used at the time added that. I'll remove it now that the templates no longer generate that code.
