### ISSUE TITLE
Update React Redux Template disponibility in .NET6

### ISSUE THREAD

**Issue by BuddhaCodes** [dotnet/AspNetCore.Docs#24284]
[Enter feedback here]

It will be useful for people to know that reactredux template has been dropped and new possibilities are available https://github.com/aspnet/Announcements/issues/465

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7264db1b-55ec-e419-d2c4-bd4fe64922a2
* Version Independent ID: 720995d2-006a-3573-4868-d253c8a2acc7
* Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-6.0)
* Content Source: [aspnetcore/client-side/spa/react-with-redux.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/react-with-redux.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
Fixed in #25031.
