### ISSUE TITLE
`.ValidateOnStart()`

### ISSUE THREAD

**Issue by dgaspar** [dotnet/AspNetCore.Docs#24282]
The useful `.ValidateOnStart()` method (for early validation of options) isn't mentioned in this documentation.
c.f. https://github.com/dotnet/runtime/issues/36391
The documentation also doesn't seem to mention that validation and Configure() are otherwise "lazy" evaluated (e.g., only when the first request is processed and the Controller is instantiated for the first time etc.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0#options-validation-1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Great suggestions. PR's welcome.
