### ISSUE TITLE
Missing element in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0

### ISSUE THREAD

**Issue by Firesong25** [dotnet/AspNetCore.Docs#24289]
If you don't put a symbolic link from the sites-available to sites-enabled it won't work.

**Comment by guardrex** [comment]
Hello @Firesong25 ...

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
