### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by cdwiegand** [dotnet/AspNetCore.Docs#24298]
The link at the top that says `Non-host console apps are discussed later in this document.` is broken, and there doesn't appear to be documentation on how console apps should use Microsoft's logging library (just ASP.Net Core apps?). This text is found in the Logging providers section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cdwiegand ... Thanks for reporting. It looks like this is a 5.0 section link and that section isn't supposed to appear in the 6.0 doc. Therefore, the 6.0 version link should be dropped. If you want to read the 5.0 version section, it's here ...

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#non-host-console-app
