### ISSUE TITLE
Add Blazor Quick Start Link to Introduction

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/AspNetCore.Docs#24296]
I think we may want to consider having this as a button at the top to get started with Blazor quickly. cc/ @danroth27 

https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro

This page is currently the top search result when you search for `Blazor`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
*Tutorials* is currently the forth entry in the ToC. We could move the *Tutorials* node **_up_** to just under the *Overview* ... make it next after this topic ... 

* Overview
* Tutorials
* Supported platforms
* Tooling
* Hosting models
* Project structure
* ...

**Comment by guardrex** [comment]
**_Note to self_**: I see that I need to reverse the order of the WASM and Server sections of this topic.

**Comment by TanayParikh** [comment]
I agree that'd be helpful, however I think we may want to also include it as (one of) the first things on the `Overview` page as well, simply because it's the first result when you search for `Blazor`. I believe that tutorial may be a "quicker start" than reading through the overview and so on. This is entirely my opinion, and I'd love to hear other feedback on it (this isn't necessarily a request to make the change yet).

**Comment by guardrex** [comment]
Yeah, that's cool. We could do both.

We should keep in mind that the first tutorial links directly to the *Todo List* tutorial before returning the reader back over here. Right now just following our links, we kind'a force readers into a double-tutorial experience. Perhaps, they should return to the *Overview* after the first tutorial, knowing that they'll hit the *Tutorial* node PDQ for the other two tutorials.

WRT the best path for pushing readers one way or the other, I think we'd need the results of a properly-designed A-B test. Personally, I like to read a little bit of the basics of a framework before I spend my time in a tutorial, but I'm sure others prefer the other learning path.
