### ISSUE TITLE
Multipart/form-data request inference - Incorrect

### ISSUE THREAD

**Issue by SDP190** [dotnet/AspNetCore.Docs#24293]
Docs says:

> 

> ### Multipart/form-data request inference
> The [ApiController] attribute applies an inference rule when an action parameter is annotated with the **[FromForm]** attribute. The multipart/form-data request content type is inferred.
To disable the default behavior, set the SuppressConsumesConstraintForFormFileParameters property to true in Startup.ConfigureServices:

I think this is incorrect, the "**multipart/form-data**" content-type should only be inferred for action params of type `IFormFile` used to upload files which normally uses **multipart/form-data**, and not for any type annotated with **[FromForm]** attribute. **[FromForm]** can be used for form fields encoded with URL-encoded form data as well. And I really think this is actually how it works, (Hence the suppression property name: **SuppressConsumesConstraintForFormFileParameters**) but the documentation is incorrect. 

Please verify whether I am correct and fix the docs accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by SDP190** [comment]
Hi @Rick-Anderson after testing it myself I found that I am completely right, when an action takes a param with the attribute `[FromForm]` it can still consume both "`application/x-www-form-urlencoded`" and also "`multipart/form-data`", so unlike docs states, `[FromForm]` does not infer "multipart/form-data request content type ".

However, I believe the docs should say that using `IFormFile` for the action's parameter type, that will indeed infer `multipart/form-data` , as I have tested it and see that this is indeed the case (when using `IFormFile` as the parameter type) then trying to call the api with content-type `application/x-www-form-urlencoded` will result in a 415 (media type is not supported). And to disable the default behavior, set the `SuppressConsumesConstraintForFormFileParameters` property to true in Startup.ConfigureService

**Comment by SDP190** [comment]
Hi @Rick-Anderson, any news on this one?

**Comment by SDP190** [comment]
Thanks!!!

**Comment by serpent5** [comment]
@SDP190 Thanks for bringing this to our attention.
