### ISSUE TITLE
Don't you need symlinks in sites-enabled for this to work?

### ISSUE THREAD

**Issue by Firesong25** [dotnet/AspNetCore.Docs#24290]
It didn't work for me and it seems that I was missing symlinks in sites enabled.

**Comment by guardrex** [comment]
@Firesong25 ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form **_adds metadata to your GitHub issue that cross-links the topic and automatically pings the author_**.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
If you took that approach to open this, try again **_and leave the metadata in the opening comment_**.
