### ISSUE TITLE
Change tokens examples memory leak

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/AspNetCore.Docs#24302]
Examples are not disposing `IDisposable` returned by `ChangeToken.OnChange` promoting bound object (owner of `InvokeChanged`) lifetime to lifetime of change token issuer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9310e951-5185-4c31-064d-3a151acc17cf
* Version Independent ID: 42bc4b7b-2a1c-0248-2740-0decdda6000c
* Content: [Detect changes with change tokens in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/change-tokens.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/change-tokens.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by serpent5** [comment]
We have a note in the article for this:

> `OnChange` returns an `IDisposable`. Calling `Dispose` stops the token from listening for further changes and releases the token's resources.

The sample code demonstrates adding an `OnChange` callback handler to the `Startup` class, with no intention to stop listening for changes. I think that coverage and example is fine as-is, but more than happy to take a second opinion @Rick-Anderson.
