### ISSUE TITLE
How about explaining first what is "Publish Profile" or at least provide link do documentation ?

### ISSUE THREAD

**Issue by KWodarczyk** [dotnet/AspNetCore.Docs#24309]
[How about explaining first what is "Publish Profile" or at least provide link do documentation ?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This probably works as well as anything. There are several spots in VS docs that speak to them.

https://docs.microsoft.com/visualstudio/deployment/publish-overview

**Comment by KWodarczyk** [comment]
The thing I would like to know is how is different from doing UWP apps ? Let's say someon is moving from UWP to WinUI and see "Publishing Profiles" folder that hey did not see in UWP but still could publish. For those users it might bo not clear what is the point of this, you can still create .appx so is this needed for desktop ?

**Comment by postmeback** [comment]
I think this ticket can be closed
