### ISSUE TITLE
Unit test fails when Razor page returns a partial

### ISSUE THREAD

**Issue by lauraemilyjacobsen** [dotnet/AspNetCore.Docs#24312]
A small update to the sample code is needed when unit testing a Razor page action that returns a partial. Here's the last line of the action that I'm testing.

 `return Partial("_PartialViewName", modelObject);`

The page works perfectly when running in the browser. When called from a unit test, the return statement throws an `ArgumentNullException`, "Value cannot be null. (Parameter 'metadataProvider')".

   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(IModelMetadataProvider metadataProvider, ModelStateDictionary modelState, Type declaredModelType)  
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary..ctor(IModelMetadataProvider metadataProvider, ModelStateDictionary modelState)  
   at Microsoft.AspNetCore.Mvc.RazorPages.PageModel.Partial(String viewName, Object model)  
   at MyNamespace.Web.Pages.UploadModel.OnPost() in C:\***.Web\Pages\Upload.cshtml.cs:line 67  
   at **.Tests.Pages.UploadPageTests.OnPost_SavesUploadWithClaimsUserName() in ***.Tests\Pages\UploadPageTests.cs:line 119  

The unit test sets up a `PageContext` exactly as shown in the sample code. I am instantiating a new `EmptyModelMetadataProvider` and using it to instantiate the `ViewData` as indicated.

```
    var httpContext = new DefaultHttpContext();
    var modelState = new ModelStateDictionary();
    var actionContext = new ActionContext(httpContext, new RouteData(), new PageActionDescriptor(), modelState);
    var modelMetadataProvider = new EmptyModelMetadataProvider();
    var viewData = new ViewDataDictionary(modelMetadataProvider, modelState);
    var tempData = new TempDataDictionary(httpContext, Mock.Of<ITempDataProvider>());
    var pageContext = new PageContext(actionContext)
    {
        ViewData = viewData
    };
    var pageModel = new MyPageModel()
    {
        PageContext = pageContext,
        TempData = tempData,
        Url = new UrlHelper(actionContext)
    };

```

 However, the Razor engine expects the Page itself to have a `ModelMetadataProvider` and this is null.

The solution is to set the PageModel.MetaDataProvider like so:
```
    var pageModel = new MyPageModel()
    {
        PageContext = pageContext,
        TempData = tempData,
        Url = new UrlHelper(actionContext),
        MetadataProvider = modelMetadataProvider
    };
```

Again, this only seems to be necessary when the page action returns a Partial. This is in .NET Core 3.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@lauraemilyjacobsen thanks for the detailed report.

**Comment by fiyazbinhasan** [comment]
oops, I missed it. I will take a look at it 🙂
