### ISSUE TITLE
Improve Antiforgery section titles to help reduce confusion

### ISSUE THREAD

**Issue by serpent5** [dotnet/AspNetCore.Docs#24326]
Context: https://stackoverflow.com/questions/70361843/changes-in-client-side-if-we-are-setting-httpcookie-httponly-as-true

I think we should rename some of the headings here:

| Current | Suggested | Rationale |
| - | - | - |
|ASP.NET Core antiforgery configuration|Antiforgery in ASP.NET Core|This is less about configuration and more about usage.|
|Antiforgery options|Configure Antiforgery with `AntiforgeryOptions`|This is where we actually describe configuration.|
|Configure antiforgery features with IAntiforgery|Generate antiforgery tokens with IAntiforgery|This is about using `IAntiforgery` to get/store tokens and not about configuration.|

@Rick-Anderson Please review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Much better. We need to be looking for ways to improve SEO.
