### ISSUE TITLE
Azure Application Insights/Blob storage logging in minimal API

### ISSUE THREAD

**Issue by newbiedev123** [dotnet/AspNetCore.Docs#24320]
**Help us make content visible**

I am trying out minimal API, but not sure how to log information to either a BLOB storage or a App Insights.
In the older version of .netcore API we could do it in the program file by calling CreateWebHostBuilder and passing the App Insight values. But I can see we have WebApplicationBuilder in the minimal API, so not sure how to configure logging to Azure.
Could you please provide some documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @newbiedev123. There's an example in the logging docs [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#azure-app-service) for the Blob/File provider. The docs over [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core) discuss Application Insights, but that's not yet been updated to 6.0. You should be able to use something like this to register that provider in 6.0:

```csharp
builder.Services.AddApplicationInsightsTelemetry();
```
