### ISSUE TITLE
Poor explanation of altering startup behavior

### ISSUE THREAD

**Issue by mduffey** [dotnet/AspNetCore.Docs#24349]
The section discussing StartAsync and how to alter the behavior of how it's started is inaccurate. It suggests that to customize the startup behavior, the service should only be registered after calling WebApplication.CreateBuilder. However, you can only register the service after the builder exists, because until that point, you don't have the service collection to manage the registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@huan086 please review
cc @serpent5
