### ISSUE TITLE
.NET 6: Write custom ASP.NET Core middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24345]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by smandia** [comment]
@Rick-Anderson  I will take this up if it is fine by you guys.

**Comment by Rick-Anderson** [comment]
@smandia  sorry, I'm already working on it
![image](https://user-images.githubusercontent.com/3605364/146627589-25d047d4-98a7-4939-a649-6066af5233c6.png)
Hopefully you can review.
Lots of other issue you could work on.

**Comment by Rick-Anderson** [comment]
@smandia  #24386 looks like a good one if you're interested.
