### ISSUE TITLE
Generic Third Party Authentication with Identity

### ISSUE THREAD

**Issue by rhires** [dotnet/AspNetCore.Docs#24359]
Hello - 

I'm looking for something that's not here: how to do third party authentication that doesn't use Facebook/Google/etc., doesn't use federation, or OAuth, or anything else, but does use a simple API call to the third party over HTTPS that validates a username/password, returns some data and lets the user go on their way. 

I'm using MVC, so I want to be able to manage the controllers via the [Authenticated] attribute. Most of the other functionality in terms of user accounts, password resets and such is already managed by the third party api, but I still want the dotnet core web app to be my front end. 

The way the FB/Google authentication works, it sends you out to them, and then you come back, which is not what I want. I'd like to have an example of what needs to be changed in the code...

I want to use the existing Identity infrastructure to manage the UI in some respects, since it's already there...

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0676a8c8-8009-8a7e-72ac-7cde0013fb97
* Version Independent ID: e35e8811-07d1-ca9b-d6e7-e28c1d4b1853
* Content: [Articles based on ASP.NET Core projects created with individual user accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/individual?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/individual.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/individual.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think you want https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity

**Comment by rhires** [comment]
Yes, but where's the part where I use my third party api to send the username/password and get a response back (that I get then feed into the rest of everything)? That's the part I'm missing. The existing instructions don't say anything about that. Here's a bit of pseudocode to show what mean. Where would this go? The docs don't say...
```
var response = MyRestServer.Post("url", loginCredentials);
if (response.IsSuccessful)
return response.UserInfo;
```
I posted [this question](https://stackoverflow.com/questions/70329258/net-core-authentication-with-a-generic-third-party-user-store-api/70331024#70331024) on Stackoverflow, but the answer was less than satisfying, because the example points to 3.1, and the latest examples don't show anything like this, or where I would edit code to make this happen as in the 3.1 example. But also, I'm not sure I want to use CookieAuthentication since the unmodified template seems to be able to do everything except get whether the user is authenticated by my third party. I could be missing something obvious though...

**Comment by Rick-Anderson** [comment]
We don't have the resource to document this edge case. Should enough folks request this, we'll reconsider.
