### ISSUE TITLE
Link to the Facebook case study is broken

### ISSUE THREAD

**Issue by dusekdan** [dotnet/AspNetCore.Docs#24365]
There is a broken link that should be pointing towards case study from Facebook. It links to facebook.com/unsupportedbrowser instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you copy/paste the link?

**Comment by dusekdan** [comment]
https://www.facebook.com/unsupportedbrowser

**Comment by smandia** [comment]
@Rick-Anderson  I just had a look into the history and the old link was https://developers.facebook.com/docs/apps/register and replaced with this https://www.facebook.com/unsupportedbrowser in commit id 
![image](https://user-images.githubusercontent.com/3833082/146684181-9d1d700d-3d27-40c7-8451-2effa63c1b8a.png)

**Comment by smandia** [comment]
Code commit https://github.com/dotnet/AspNetCore.Docs/pull/24371
