### ISSUE TITLE
.Net 5.0 template link no longer works

### ISSUE THREAD

**Issue by mhoelzel142** [dotnet/AspNetCore.Docs#24362]
The go.microsoft.com link in the .net core Angular SPA template redirects to the Bing homepage. 

Reproduction steps: 
1. From the command line, run `dotnet new angular -f net5.0`
2. Open the newly created project in your editor of choice and navigate to Startup.cs
3. On line 64, copy the URL (https://go.microsoft.com/fwlink/?linkid=864501) and paste it in a browser

Expected result: I should be navigated to the Angular template help page in the Microsoft docs - [Use the Angular project template with ASP.Net core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-6.0&tabs=visual-studio)

Actual result: I am sent to the Bing homepage with this query string: https://www.bing.com/?ref=go&linkid=864501

![image](https://user-images.githubusercontent.com/15573387/146617996-11de15b2-9903-4192-a4ea-d7b253bce108.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by guardrex** [comment]
Hello @mhoelzel142 ... The project templates are maintained by the product unit. Open this on their repo at ...

https://github.com/dotnet/aspnetcore/issues

... but note that most of them are out on holiday break ⛄ until early '22. Their response might be delayed.
