### ISSUE TITLE
Utilize Microsoft.AspNetCore.Http.StatusCodes instead of Integers for RouteHandler Produces

### ISSUE THREAD

**Issue by Huntk23** [dotnet/AspNetCore.Docs#24360]
Minor feedback about utilizing available convention.

Mention of `Microsoft.AspNetCore.Http.StatusCodes` should be used over integer codes to avoid the confusion or time to lookup what a specific code means when we have access to a class with descriptions in the property name and documentation within IntelliSense.

Before-
```cs
app.MapGet("/api/todoitems/{id}", async (int id, TodoDb db) =>
         await db.Todos.FindAsync(id) 
         is Todo todo
         ? Results.Ok(todo) 
         : Results.NotFound())
   .Produces<Todo>(200)
   .Produces(404);
```

After-
```cs
app.MapGet("/api/todoitems/{id}", async (int id, TodoDb db) =>
         await db.Todos.FindAsync(id) 
         is Todo todo
         ? Results.Ok(todo) 
         : Results.NotFound())
   .Produces<Todo>(StatusCodes.Status200OK)
   .Produces(StatusCodes.Status404NotFound);
```

To me, it just makes more sense. Would love to hear other opinions on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Huntk23 Yes, that's much better. 
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
In this case you'd find and edit the `.cs` file.

Let me know if you need any help. This is a nice improvement.

**Comment by Huntk23** [comment]
@Rick-Anderson Absolutely can, PR created: #24361

> Let me know if you need any help. This is a nice improvement.

Thank you!
