### ISSUE TITLE
Is there a way to check Connection State ? 

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#24378]
```
public class RandomRetryPolicy : IRetryPolicy
{
    private readonly Random _random = new Random();

    public TimeSpan? NextRetryDelay(RetryContext retryContext)
    {
        // If we've been reconnecting for less than 60 seconds so far,
        // wait between 0 and 10 seconds before the next reconnect attempt.
        if (retryContext.ElapsedTime < TimeSpan.FromSeconds(60))
        {
            return TimeSpan.FromSeconds(_random.NextDouble() * 10);
        }
        else
        {
            // If we've been reconnecting for more than 60 seconds so far, stop reconnecting.
            return null;
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-6.0&tabs=visual-studio#manually-reconnect)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Is the question about checking connection state in the retry handler? There wouldn't be a point because you're always in the reconnecting state when the handler is called.

**Comment by nssidhu** [comment]
No.After retrying fails, it disconnects. When connection is established again, I have no event or way of knowing other than constantly checking state in timer.


Sent from Yahoo Mail for iPhone


On Monday, January 3, 2022, 12:56 PM, Brennan ***@***.***> wrote:




Is the question about checking connection state in the retry handler? There wouldn't be a point because you're always in the reconnecting state when the handler is called.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BrennanConroy** [comment]
I'm not really sure what you're trying to do, could you explain your scenario please.
