### ISSUE TITLE
How hosted Blazor WebAssembly solution Connect Client and Server together here?

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24376]
Here you used Absolute url of the Client App in creating the hub connection while Hub and its endpoint located on Server App project:
https://github.com/dotnet/AspNetCore.Docs/blob/81c32afe46782cc130657c647d1e6461fed47af2/aspnetcore/tutorials/signalr-blazor/samples/6.0/BlazorWebAssemblySignalRApp/Client/Pages/Index.razor#L40

Also at the end you only run the Server Project in dotnet command, but everything works as expected. So it is no issue with code here and I be grateful to have some clarification regard them. 
I tried to find the connection between them and only found this:
1- Server project uses Client project as dependency
2- They both have same port to launch in `launchsetting.json`. 
`"applicationUrl": "https://localhost:7094;http://localhost:5104"`

So I concluded that running the server automatically runs the client and since the port is same for both projects, they both merge together in one app but only the client project sent to browser and the server DLL only runs in server and do not sent to browser (which it is the case). Is it this pattern true for all cases of server-client apps in dotnet for example using a web API and a presentation layer both in dotnet or only it is correct in Blazor web Assembly?

Sorry if it sounds trivial to you, I am a Linux user of .Net and using Visual Code (Not Visual Studio) for development and I am new in some more advanced topics.
Thanks again as always

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**_NOTE THO ..._** We're out on vacations right now. Most issues will be looked at upon return in '22.
