### ISSUE TITLE
Events don't fire after reconnecting from Closed Events

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#24377]
In the Section 
Manually reconnect
https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-6.0&tabs=visual-studio#manually-reconnect

```
connection.Closed += async (error) =>
{
    await Task.Delay(new Random().Next(0,5) * 1000);
    await connection.StartAsync();
};
```

This code does work but, if i have wired up events, those events do not fire anymore even after successful reconnection.
This applies to all events of connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-6.0&tabs=visual-studio#manually-reconnect)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Similar issue filed in product repo and closed as not an issue.
