### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by markharwood101** [dotnet/AspNetCore.Docs#24379]
You state:

These security features allow you to build robust **yet** secure ASP.NET Core apps.

Is the 'yet' correct? Surely robustness and secureness do not counteract each other, shouldn't it be:

These security features allow you to build robust **and** secure ASP.NET Core apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by markharwood101** [comment]
Sure, let me take a look

**Comment by markharwood101** [comment]
Done

**Comment by guardrex** [comment]
Fixed per https://github.com/dotnet/AspNetCore.Docs/pull/24413.

@markharwood101 ... Note for future reference that if you place the text `Fixes #{ISSUE NUMBER}`, where the placeholder `{ISSUE NUMBER}` is the issue number, at the top of the opening comment of the PR, GH will close the issue automatically when the PR merges. If you place `Addresses #{ISSUE NUMBER}` at the top, it cross-links the issue without closing it (i.e., you plan to return later and create one or more additional PRs for the issue, so you don't want to close it until the last PR is done ... the last one would get the `Fixes` line).

Thanks again for taking care of this issue, @markharwood101! :rocket:
