### ISSUE TITLE
.NET6 update: SignalR Authentication -

### ISSUE THREAD

**Issue by Rhywden** [dotnet/AspNetCore.Docs#24372]
For example, reading the accessToken using the method presented is not working anymore.

`context.Request.Query["access_token"]` now returns `StringValues` instead of `string` which in turn makes `string.IsNullOrEmpty` **always** return `true`

Not to mention that the first connection to the hub will always be `/chathub/negotiate?negotiateVersion=1` where the access token will be in the *header* and not in the query. As it is, using the code provided I always get a "401 - Unauthorized".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by abdollahkahne** [comment]
This is okay for me (at least cookies and query strings) if you try to use:
```
var httpContext = Context.GetHttpContext();
            var accessToken = httpContext?.Request?.Query["access_token"];
            Console.WriteLine(accessToken);
```
And also the web socket does not include headers in handshake request although it include it in negotiation request (from client side network tab investigation) so the header possibly is not available even in case of using the above method. 
Getting `HttpContext` from `HttpContextAccessor` Service returns null in case of web socket always and `getHttpContext` use not that I believe.

**Comment by abdollahkahne** [comment]
Also to use other places than Authorization Header for authentication you can use **Hub Filters** which have the `getHttpContext` method and can use it in filters or use the code mentioned here (It do not belong to me! I can not find the original article)
```

// To add authentication from other places than Authorization Header, We should hook to an event name OnMessageReceived (specially for WebSocket and Sever Sent Events which header does not allow)
            services.AddAuthentication().AddJwtBearer(options =>
            {
                options.Authority = "Ourself";
                options.ClaimsIssuer = "SignalR App";
                options.Events = new JwtBearerEvents
                {
                    OnMessageReceived = (ctx) =>
                    {
                        // Altough we have to use the query string for authentication but it has some security consideration (for example in http it is not secured)
                        // When using HTTPS, query string values are secured by the TLS connection. However, many servers log query string values.
                        // As an alternative we can use single use of it which generated from cookie-based authentication which used on other component of our App
                        var accessToken = ctx.HttpContext.Request.Query["access_token"];
                        var path = ctx.HttpContext.Request.Path;
                        if (!string.IsNullOrEmpty(accessToken) && path.StartsWithSegments("/chathub"))
                        {
                            ctx.Token = accessToken;
                        }
                        return Task.CompletedTask;
                    }
                };
            });
```

**Comment by BrennanConroy** [comment]
> `context.Request.Query["access_token"]` now returns `StringValues` instead of `string` which in turn makes `string.IsNullOrEmpty` **always** return `true`

That's not true, `StringValues` implicitly casts to a string and will be null if there is no string value stored internally.

> Not to mention that the first connection to the hub will always be `/chathub/negotiate?negotiateVersion=1` where the access token will be in the _header_ and not in the query. As it is, using the code provided I always get a "401 - Unauthorized".

Have you actually tried the code provided? It's been working for years.

The negotiate request will have the token in the header and so the code provided will be skipped and the code inside the auth middleware will properly look at the header and get the token.
