### ISSUE TITLE
Mention of Shared IIS App Pool is still not supported should be in .NET 5/6 documentation

### ISSUE THREAD

**Issue by Huntk23** [dotnet/AspNetCore.Docs#24385]
Interesting find here during production deployment under the same IIS App Pool. I figured when going from .NET Core 3.1 to .NET 5 and even tested in .NET 6 that we can finally use shared app pools again originally supported by .NET Framework. Unfortunately I kept receiving 503 errors with shared app pools. I think some indication from .NET Core 3.1 documentation should carry over to .NET 5/6 about the following point:

- Sharing an app pool among apps isn't supported. Use one app pool per app.

With a simple search, I find issues asking about this very similar issue:
- https://github.com/dotnet/aspnetcore/issues/17605
- https://stackoverflow.com/questions/58635664/hosting-multiple-net-core-using-the-same-application-pool-with-aspnetcoremodule

These issues are not necessarily recent, but I personally foresee them coming up again.

**Goal**: to hopefully prevent any confusion of future document readers about this behavior without realizing the same restriction existed in earlier versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-6.0#in-process-hosting-model)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @Huntk23 ... I think it was perhaps covered more obviously before there was a big overhaul to this node of topics, when it went from one topic on IIS to several. It's currently described in this (*somewhat buried*) spot ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-6.0#differences-between-in-process-and-out-of-process-hosting

@Rick-Anderson ... It's a quick fix. I'll put up a PR tomorrow morning and ping u.

Thanks @Huntk23 for calling it out.

**Comment by guardrex** [comment]
btw ... I also found it covered (*in another buried spot*) at ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0#application-pools

**Comment by guardrex** [comment]
Actually, @Rick-Anderson ... let's sit on this until we get back. I'll make a **_Note to Self_** here so that I don't forget about this. I'd like to chat with Justin. Some of this really isn't "advanced config" ... this is like really basic, important stuff. I don't understand why some of this was placed in this topic and not in the overview of the IIS node. I'd like to make a list of sections (or parts of sections) that I think should move and ask Justin what he thinks about promoting those pieces.

**Comment by Huntk23** [comment]
> btw ... I also found it covered (_in another buried spot_) at ...
> 
> https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0#application-pools
> 
> 😄 ... I think I wrote that (or an earlier version of it anyway) ... and it was a lot easier to spot when this wasn't considered "advanced config" for IIS.

Oh geez! I am usually good at searching like a maniac and somehow missed this section. Thanks for pointing it out!

Documents are a dream now-a-days! Keep up the awesome work. Love the communication.

**Comment by guardrex** [comment]
**UPDATE (1/18)**: Ok ... I'm *BACK!* 🏃 This is next up @Huntk23. It takes a while to circle back around on some of these given the workload. If we make changes here, I hope to get this resolved tomorrow, Wednesday. I'll certainly get it squared away by the end of this week.

❓ for @jkotalik ... It looks like you placed quite a bit of what I would think is basic IIS config guidance in this "advanced" article, which buries it to a degree. @Huntk23 is asking specifically about the *Application Pools* guidance in this article, but let's also consider the whole topic ... all of it's sections. Is there anything here ... any sections ... that you would like to move to the *Overview* topic, or do you prefer this layout of content and to close this issue as a won't fix?

**Comment by guardrex** [comment]
**UPDATE**: No response from @jkotalik, so I think I'll just add a cross-link to the *Overview* of the IIS node that links back to the *Advanced* topic. This will be addressed on a PR today that's also going to fix some other IIS-related guidance.

**Comment by Rick-Anderson** [comment]
@guardrex  look at @jkotalik profile, he's no longer on the ASP.NET team.
