### ISSUE TITLE
.NET 6: SignalR .NET Client

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#24388]
Where Exactly should the Retry Logic be created?

Missing the information about where to create this method, i.e does it need to be created din separate class ? etc.
Also how to call this new method is also not clear

```
public static async Task<bool> ConnectWithRetryAsync(HubConnection connection, CancellationToken token)
{
    // Keep trying to until we can start or the token is canceled.
    while (true)
    {
        try
        {
            await connection.StartAsync(token);
            Debug.Assert(connection.State == HubConnectionState.Connected);
            return true;
        }
        catch when (token.IsCancellationRequested)
        {
            return false;
        }
        catch
        {
            // Failed to connect, trying again in 5000 ms.
            Debug.Assert(connection.State == HubConnectionState.Disconnected);
            await Task.Delay(5000);
        }
    }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-6.0&tabs=visual-studio#manually-reconnect)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Huntk23** [comment]
I believe it is implied to replace your typical `HubConnection.StartAsync()` with the example method `ConnectWithRetryAsync(HubConnection, CancellationToken)` when you need to manually handle initial start failures because `WithAutomaticReconnect()` does not handle that.

E.g.

```cs
using System;
using System.Threading.Tasks;
using System.Windows;
using Microsoft.AspNetCore.SignalR.Client;

namespace SignalRChatClient
{
    public partial class MainWindow : Window
    {
        HubConnection connection;
        public MainWindow()
        {
            InitializeComponent();

            connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:53353/ChatHub")
                .Build();

            connection.Closed += async (error) =>
            {
                await Task.Delay(new Random().Next(0,5) * 1000);
                await connection.StartAsync();
            };
        }

        private async void connectButton_Click(object sender, RoutedEventArgs e)
        {
            connection.On<string, string>("ReceiveMessage", (user, message) =>
            {
                this.Dispatcher.Invoke(() =>
                {
                   var newMessage = $"{user}: {message}";
                   messagesList.Items.Add(newMessage);
                });
            });

            try
            {
                var cancellationToken = new CancellationTokenSource(TimeSpan.FromSeconds(5)).Token;
                await ConnectWithRetryAsync(connection, cancellationToken);
                messagesList.Items.Add("Connection started");
                connectButton.IsEnabled = false;
                sendButton.IsEnabled = true;
            }
            catch (Exception ex)
            {
                messagesList.Items.Add(ex.Message);
            }
        }

        private async void sendButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                await connection.InvokeAsync("SendMessage", 
                    userTextBox.Text, messageTextBox.Text);
            }
            catch (Exception ex)
            {                
                messagesList.Items.Add(ex.Message);                
            }
        }
    }
}
```

Perhaps an example needs to be in place explicitly showing how to use the method?

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan would you be able to create a .NET 6 version of this? Show how to use `ConnectWithRetryAsync`
Delete `aspnetcore/signalr/dotnet-client/6sample/readmd.txt` and put the code in the `aspnetcore/signalr/dotnet-client/6sample` folder.

You can use `#define  #if ##elif ` to test  or run each version.


@nssidhu good questions and thanks for bringing this to our attention. You can put `ConnectWithRetryAsync` anywhere you like. See https://www.dotnetcurry.com/aspnet-core/realtime-app-using-blazor-webassembly-signalr-csharp9 for a sample.

**Comment by fiyazbinhasan** [comment]
On it! 🙂
