### ISSUE TITLE
@LeonardoDaga Could that be accomplished by layout pages and/or partial pages? I'm not asking this rhetorically; I honestly don't know.

### ISSUE THREAD

**Issue by mirta777** [dotnet/AspNetCore.Docs#24384]
@LeonardoDaga Could that be accomplished by layout pages and/or partial pages? I'm not asking this rhetorically; I honestly don't know.

_Originally posted by @briangithex in https://github.com/dotnet/AspNetCore.Docs/issues/3889#issuecomment-410720468_

**Comment by guardrex** [comment]
Hi @mirta777 ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Ask either from the bottom of ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout

... or ...

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial

... and the metadata will ping a topic author. Note that responses are delayed during holiday vacations.
