### ISSUE TITLE
Results of tutorial incorrect

### ISSUE THREAD

**Issue by gardnerbp** [dotnet/AspNetCore.Docs#24386]
I followed the tutorial to the letter, and while the client displayed the correct results in the console,
the server did not display any information that it received a client request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
The logging level changed in .NET 6. Either need to tell people to change it, or update the tutorial to not expect the server to log a request.

**Comment by Rick-Anderson** [comment]
@gardnerbp  can you change `appsettings.Development.json` from:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  }
}
```
To 

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Microsoft.AspNetCore.Hosting": "Information",
      "Microsoft.AspNetCore.Routing.EndpointMiddleware": "Information"
    }
  }
}
```

That should show the output as before. You could even just `// comment out "Microsoft.AspNetCore": "Warning",` or delete that line, but that might give you too much output.

Let me know how that works and I'll get someone to update this topic.

**Comment by smandia** [comment]
@Rick-Anderson As discussed - I am on it and will update soon.

**Comment by smandia** [comment]
Work in progress

**Comment by smandia** [comment]
@Rick-Anderson  Changes committed under https://github.com/dotnet/AspNetCore.Docs/pull/24503

I have tested that both options suggested by you works with required logging .
Also your suggesstion about // comment out "Microsoft.AspNetCore": "Warning",  - Result [ It doesnot give extra logs and works fine ]

**In short summary**

"Microsoft.AspNetCore": "Warning",
      "Microsoft.AspNetCore.Hosting": "Information",
      "Microsoft.AspNetCore.Routing.EndpointMiddleware": "Information"
**Also works fine and just** 

      "Microsoft.AspNetCore.Hosting": "Information",
      "Microsoft.AspNetCore.Routing.EndpointMiddleware": "Information"

also works fine.
