### ISSUE TITLE
Cannot create Windows Service

### ISSUE THREAD

**Issue by ygoe** [dotnet/AspNetCore.Docs#24389]
**Issue description**

Following the [documentation here](https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio&source=docs), I get an error message I don't understand. So for me, the complete instructions are not usable and I cannot complete my task to install the ASP.NET Core app as a Windows service. I'll have to recommend my customer to use Linux instead of Windows, I know how it works there. It's really easy. And fully scriptable in Bash, instead of multiple GUI installers, GUI configs and interleaved PowerShell commands.

I could create the user and assign it the privilege to logon as service. But the next step fails.

```
PS C:\Windows\system32> $acl = Get-Acl "C:\Demo\WebApplication1.exe"
PS C:\Windows\system32> $aclRuleArgs = "my-pc\Demo", "Read,Write,ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow"
PS C:\Windows\system32> $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($aclRuleArgs)
PS C:\Windows\system32> $acl.SetAccessRule($accessRule)
Ausnahme beim Aufrufen von "SetAccessRule" mit 1 Argument(en):  "Es können keine Flags gesetzt werden.
Parametername: inheritanceFlags"
In Zeile:1 Zeichen:1
+ $acl.SetAccessRule($accessRule)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

PS C:\Windows\system32>
```

**Target framework**

.NET Core 3.1 (may not apply here)
Windows 10.20H2 x64 (not Server)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Ausnahme beim Aufrufen von "SetAccessRule" mit 1 Argument(en):  "Es können keine Flags gesetzt werden.
Parametername: inheritanceFlags"
MT to English:
Exception when calling "SetAccessRule" with 1 argument (s): "No flags can be set.
Parameter name: inheritanceFlags "

**Comment by guardrex** [comment]
I'm working this one as a crossover issue for Blazor, too. I'll investigate the reported error as I work through the updates. Updates include removing the 2.x pieces and adding bits for 5.x and 6.x. I'll deal with PS script updates. Note that the PS updates move all guidance to working PS 7 commands. *We don't document old tooling.*

**Comment by ygoe** [comment]
@Rick-Anderson Please don't edit in questions, I don't see them.

Here's the value of the requested variable:

```
FileSystemRights  : Write, ReadAndExecute, Synchronize
AccessControlType : Allow
IdentityReference : mypc\myuser
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None
```

**Comment by guardrex** [comment]
Sorry folks! Change of plans. One of the docs team members will take care of the general updates first (3/4 open issues), then I'll come in later and address the Blazor-specific issue later.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
