### ISSUE TITLE
Use workaround for 6.0 hosted WASM example

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24394]
Per https://github.com/dotnet/aspnetcore/issues/39087 and https://github.com/dotnet/aspnetcore/pull/39060.

We'll be reverting back to what the topic shows today for 6.0 at 7.0 GA. The 6.0 version will keep the workaround permanently. Open a follow-up issue on hold for 7.0 after the PR for this merges.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by TanayParikh** [comment]
Let's actually hold off on this for now (blocked) until we get some clarity on whether we'll be backporting https://github.com/dotnet/aspnetcore/pull/39075 or not. If we are, this change won't be needed.

The documentation as it is currently works, the error from https://github.com/dotnet/aspnetcore/issues/39087 occurs when you specifically remove the `if (upload)` section of the code block in the `FileUpload2` component.

**Comment by guardrex** [comment]
@TanayParikh ... Based on the patch going in, should this issue be closed?

**Comment by TanayParikh** [comment]
Yep, thanks!
