### ISSUE TITLE
Remove unused package import

### ISSUE THREAD

**Issue by ethanhou99** [dotnet/AspNetCore.Docs#24391]
[Enter feedback here]
Hi there,

I think the second line of the file HelloWorldController.cs using `System.Text.Encodings.Web;` is not used, could you please remove this line?

![image](https://user-images.githubusercontent.com/43047951/146944594-b1be01eb-4ec5-437f-b79d-d383994a62e5.png)

Please correct me if I'm wrong.

Best,
Ethan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's needed later in the sample

```
// GET: /HelloWorld/Welcome/ 
// Requires using System.Text.Encodings.Web;
public string Welcome(string name, int numTimes = 1)
{
    return HtmlEncoder.Default.Encode($"Hello {name}, NumTimes is: {numTimes}");
}
```
