### ISSUE TITLE
Tutorial: Get started with Razor Pages in ASP.NET Core

### ISSUE THREAD

**Issue by philomatix** [dotnet/AspNetCore.Docs#24396]
[Enter feedback here]
The tutorial Get started with Razor Pages in ASP.NET Core starts quite easy step by step and works for me up to Program.cs so yes I get the exactly the same Program.cs code and everything is fine up to there.

But I am not sure if I follow correctly 

So I look at the bottom and see I can download an already completed example -  which I do -  but when I run that  it contains a SQL connection which is not covered in tutorial yet which is obviously not set up correctly by me yet and it has seemingly the code you mentioned in program.cs   in separate other .cs files like ProgramSeed.cs etc.

How can you start a basic slow step by step learning curve and then shoot up a very steep curve next?

Maybe should have a partially finished but working  project available and then a part two that include further dependencies like SQL connection etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We've tried to keep partial samples but found that had little benefit for alot of work. The sample is easy to follow.
