### ISSUE TITLE
Can't find Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by dresdedream** [dotnet/AspNetCore.Docs#24408]
I'm trying this tutorial with the VS community 2022 and my NuGet Package Manager for solution.. cannot find "Microsoft.EntityFrameworkCore.Design" is this because the tutorial isn't up to date ?

![image](https://user-images.githubusercontent.com/48597427/147308122-5f5c9ac7-b1d1-447c-974c-a606678ba8ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's up to date
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/
