### ISSUE TITLE
Can't start debugger because of certifcation confusion

### ISSUE THREAD

**Issue by kayleidoscope** [dotnet/AspNetCore.Docs#24406]
I'm having the exact same problem as https://github.com/dotnet/AspNetCore.Docs/issues/14581 and have tried the suggested fixes there but nothing is working. If I run dotnet dev-certs https --clean, it seems to complete successfully:
```
Kay-Holtens-MBP:~ imac$ dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. This operation might require elevated privileges. If that is the case, a prompt for credentials will be displayed.
```
But then if I run dotnet dev-certs https --trust, it says there already is a certificate.
```
Kay-Holtens-MBP:~ imac$ dotnet dev-certs https -t
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <<certificate>>'
This command might prompt you for your password to install the certificate on the system keychain.
Password:
A valid HTTPS certificate is already present.
```
I am working on a Mac, trying to run a barebones C# .NET API from Visual Studio. I have already tried to delete my certification from the Keychain Access application and was told it would regenerate, but no such luck. How do I get my computer to recognize there is no certificate and make a new one?

**Comment by Rick-Anderson** [comment]
Try https://github.com/dotnet/AspNetCore.Docs/issues/14581#issuecomment-535280484

**Comment by kayleidoscope** [comment]
OK, I was able to get that error resolved by following the steps under OS X - certificate not trusted. Thanks :)
