### ISSUE TITLE
Documentation for "Configure Identity services" is not clear

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#24405]
Documentation for "Configure Identity services" is not clear, Microsoft post this:
"
Services are added in Program.cs. The typical pattern is to call methods in the following order:

1. Add{Service}
2. Services.Configure{Service}

"
After that there are a example and next this text:
"
The preceding code configures Identity with default option values. Services are made available to the app through dependency injection.
"
BUT

1. What is the equivalent code for add{service}?

> 2. Add{**service**} means builder.Services.Add**DbContext**.....?
> 4. what about builder.Services?

5. What is the equivalent code for Services.Configure{Service}?
6.  **Services.Configure**{Service} means builder.**Services.Configure**<IdentityOptions>?

> 7. What about builder.?
> 8. What about "builder.Services.Configure<IdentityOptions>" does don´t have the pattron "Services.Configure{Service}"

Could be a good idea to indicate into documentation what is the specifict section por each part of

1. Add{Service}
2. Services.Configure{Service}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
The docs for Identity are very confusing and lacking in general.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
