### ISSUE TITLE
 HTTP Logging V6 fixes

### ISSUE THREAD

**Issue by amitdixit** [dotnet/AspNetCore.Docs#24415]
[Enter feedback here]
Please add the below line in the appsettings , else the logging does not work
      "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by Rick-Anderson** [comment]
Need to also change:

By default, HTTP Logging logs common properties such as path, status-code, and headers for requests and responses.

to
By default, HTTP Logging at the information level is not enabled.  To enable information level HTTP Logging common properties such as path, status-code, and headers for requests and responses, add the following ....

**Comment by smandia** [comment]
@Rick-Anderson  I see that the documentation is still pointing to old samples . Can I create a new sample for DotNet 6 and update the documentation also or I am missing something .

**Comment by Rick-Anderson** [comment]
Yes, see #24504
