### ISSUE TITLE
Documetation improve 

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#24411]
In .NET5 to access **appseting.json key** we could use IConfiguration like a DI into starup class :

`
public class starup
{
    private IConfiguration _config;
    public Startup(IConfiguration config)
    {
        _config = config
    }

   .....

  app.Run(async (context) => {
      await context.Response.WriteAsync(_config["MyKey"]):
  })

  
}
`
there are not indication in this documentation about how to access IConfiguration interface or create a constructor into program.cs class, equivalent to the old way with NET5.0

**It is necesary to improve the documentation.**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
WebApplication.CreateBuilder initializes a new instance of the WebApplicationBuilder class with preconfigured defaults. The initialized WebApplicationBuilder (builder) provides default configuration for the app in the following order:

ChainedConfigurationProvider : Adds an existing IConfiguration as a source. In the default configuration case, adds the host configuration and setting it as the first source for the app configuration.
