### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by Byron2016** [dotnet/AspNetCore.Docs#24412]
There are a link to [The shared framework](https://natemcmaster.com/blog/2018/08/29/netcore-primitives-2/) but this link was wroted on 2018 and it has not been updated, and there are not references to NET6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Microsoft.AspNetCore.App metapackage for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback. The link doesn't need to be updated.
