### ISSUE TITLE
Many of the Microsoft.AspNetCore.* packages do not have a 6.0.0 version

### ISSUE THREAD

**Issue by PjotrB** [dotnet/AspNetCore.Docs#24423]
The advice to change the version to "6.0.0" for all `Microsoft.AspNetCore.*` packages seems flawed. After doing so, I got a long list of errors saying that requested packages could not be found. It took me quite some time browsing on NuGet.org to find out which packages have a 6.0.0 version and which do not.

I hope this upgrade guide can be made more accurate and more specific about which new versions to use for each package, and which packages to leave unchanged. E.g. the newest version for several packages is "2.2.0", like this one: https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication/

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 2221be91-501e-a2bc-b3db-1c7df98a0c82
* Version Independent ID: 2221be91-501e-a2bc-b3db-1c7df98a0c82
* Content: [Migrate from ASP.NET Core 3.1 to 6.0](https://docs.microsoft.com/nl-nl/aspnet/core/migration/31-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/31-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/31-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`Microsoft.AspNetCore.Authentication` has been in the shared framework since 3.0 and is included by the TFM 

```
<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
``
