### ISSUE TITLE
review and clean up write middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24434]
Address comments in  #24348

@fiyazbinhasan can you take this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Taking a look :)

**Comment by Rick-Anderson** [comment]
```
::: moniker range=">= aspnetcore-6.0"

By Fiyaz Hasan, Rick Anderson and Steve Smith
```

**Comment by Rick-Anderson** [comment]
That should be
By Fiyaz Hasan, Rick Anderson***,*** and Steve Smith

**Comment by fiyazbinhasan** [comment]
Just noticed you added my name as well! 😃
