### ISSUE TITLE
Expand docs about SPA-Apps, explaining the plumbing

### ISSUE THREAD

**Issue by Ducki** [dotnet/AspNetCore.Docs#24447]
The spa template is very confusing and does a lot of magic, that is nowhere really described. Please expand documentation about explaining how the proxying works, how kestrel knows what to serve when, etc. It is just unclear how it all works together.

For example: "app.MapFallbackToFile("index.html");" -> where is defined, that this index.html is located in ClientApp/public/? Why is there no wwwroot directory, even though is appears in the obscure part of the .csproj.
The csproj file seems to be doing a lot of stuff, that really needs to be explained, because many of its parts are very cryptic.

Please expand the docs about the plumbing of ASP.net Core and the react app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/

We have a 6 person month backlog on existing SPA articles.
