### ISSUE TITLE
"Change the web root" sample code misleading/outdated because of .NET 6 breaking change of Webhost settings

### ISSUE THREAD

**Issue by Ducki** [dotnet/AspNetCore.Docs#24452]
Concerning: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#change-the-web-root

The docs on "Change the web root" and the code sample following that state, that changing the _webroot_ can be done by using `builder.WebHost.UseWebRoot("webroot");`.

This is false, because:
- It contradicts documentation on this change between .NET 5 and 6:
  - https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#change-the-web-root (see code sample)

  - https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#differences-between-the-aspnet-core-5-and-6-hosting-models:
    > It's not possible to change any host settings such as app name, environment, or the content root after the creation of the WebApplicationBuilder. […]

- Using the sample code on .NET 6 results in a build error:

  > Unhandled exception. System.NotSupportedException: The web root changed from "[…]" to "[…]". Changing the host configuration using WebApplicationBuilder.WebHost is not supported. Use WebApplication.CreateBuilder(WebApplicationOptions) instead. […]

Perhaps the extension method should be removed as well, because it doesn't seem to serve a purpose anymore.)

Thank you! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Ducki  thanks for reporting this.

> Using the sample code on .NET 6 results in a build error:

That's actually a run time error. It would be nice to issue a build warning.

> Perhaps the extension method should be removed as well, because it doesn't seem to serve a purpose anymore.)

We have many customers using .NET 3.1 and 5.0, so we can't remove it.

**Comment by Ducki** [comment]
I see, sorry for the wrong wording. I opened a [pull request](https://github.com/Ducki/AspNetCore.Docs/pull/1) that uses the sample code from the migration guide.

Thank you 👍
