### ISSUE TITLE
Do not use external input as cache keys.

### ISSUE THREAD

**Issue by ChrisGroupScape** [dotnet/AspNetCore.Docs#24464]
Could you please add clarification to "external input" in the statement: Do not use external input as cache keys.
I take it to mean as "external to the application" such as user input but that took a bit of searching.
It could also be taken as external to the memorycache instance which would lend someone to think they had to use MemoryCache.EntryKey.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think it means the app doesn't control how many cached entries are created, but I'll escalate this and get an answer.
