### ISSUE TITLE
Error on "Install-Package Microsoft.EntityFrameworkCore.SqlServer"

### ISSUE THREAD

**Issue by raoulteeuwenPE** [dotnet/AspNetCore.Docs#24471]
Hello. I was following this tutorial, and on this page, when executing "Install-Package Microsoft.EntityFrameworkCore.SqlServer" i get an incompat-error:

"PM> Install-Package Microsoft.EntityFrameworkCore.Design
Restoring packages for C:\Users\r.teeuwen\source\repos\MvcMovie\MvcMovie\MvcMovie.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/index.json 417ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/6.0.1/microsoft.entityframeworkcore.design.6.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/6.0.1/microsoft.entityframeworkcore.design.6.0.1.nupkg 6ms
Installed Microsoft.EntityFrameworkCore.Design 6.0.1 from https://api.nuget.org/v3/index.json with content hash odZLopaluipZXgJxue4VbBXe9YoTOOmg324rkyr0XqXWR7DSdWy5Mi0+99OvsOmvl6LxEqK4IOgNnycB+oF3pQ==.
Install-Package : NU1202: Package Microsoft.EntityFrameworkCore.Design 6.0.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.EntityFrameworkCore.Design 6.0.1 supports: net6.0 
(.NETCoreApp,Version=v6.0)
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Design
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'MvcMovie'.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Design
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.2582060
PM> "

(Btw: i don't recall the actual path that lead me to this 'course', but i only noticed the 'version dropdown in the top left' while starting 'Part 5', so some (all?) of my 'issues' might be related to me not having noticed that version dropdown earlier ... maybe a not could be made in Part 1 if working in the right version is relevant).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by raoulteeuwenPE** [comment]
(running "Install-Package Microsoft.EntityFrameworkCore.Design -version:5.0.13" fixes it for me)

**Comment by Rick-Anderson** [comment]
You need to install the .NET 6 SDK and start over, that's why you're having problems.

**Comment by raoulteeuwenPE** [comment]
Sorry for that than. Will do. Thank you for your time & this course!

**Comment by ethanknapp** [comment]
I am having the same issue... not sure how to properly install .NET 6 SDK...

Would really appreciate some guidance or additional resources to help me continue the MVC tutorial

**Comment by Rick-Anderson** [comment]
@ethanknapp  see See https://stackoverflow.com/questions/67049414/windows-or-visual-studio-cant-find-the-latest-installed-net-sdk-due-to-bitness

**Comment by ethanknapp** [comment]
@Rick-Anderson Thanks for that - unfortunately, I think I have a different issue.
I figured it was because I didn't have .NET 6 before starting the tutorial, but I still get the same error after re-doing the tutorial with the .NET 6 SDK.
"dotnet --list-sdks" in the command line only shows one installation, 6.0.300 [C:\Program Files\dotnet\sdk].
Should this appear in Program Files (x86) instead? Did I get the wrong SDK?

**Comment by ethanknapp** [comment]
@Rick-Anderson I found the solution to my error... embarrassed but not defeated.

I forgot to add NuGet to my list of sources before installing the package. My apologies for the confusion.
