### ISSUE TITLE
Failed to build the project (after "The type or namespace name 'DateTime' could not be found")

### ISSUE THREAD

**Issue by raoulteeuwenPE** [dotnet/AspNetCore.Docs#24472]
On "Build the project as a check for compiler errors." in the "Add NuGet packages" step, i get "Error	CS0246	The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)".

Until this step, everything seems to work as intended. I tried to continue while ignoring this compilation error, but i get an error also and don't get past the "Scaffold movie pages" step (an error when i try to add the controller: "Failed to build the project.")

I've also checked all steps from step 1, but don't see that i missed or mistyped anything.

When i use "public System.DateTime ReleaseDate { get; set; }" in Movie.cs, the error is gone and i can also execute the next step successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Great error message. You can't ignore compiler errors.

Does your project file include `<ImplicitUsings>enable</ImplicitUsings>`?

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```
