### ISSUE TITLE
The final line does not seem to be complete

### ISSUE THREAD

**Issue by jonas-lomholdt** [dotnet/AspNetCore.Docs#24474]
The final line in this doc seems to be incomplete. I'm not sure what it was supposed to say, so I can't create a PR to fix it. 

> The .NET 5 version and .NET 6 version with the WebApplicationFactory by design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated to the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jonas-lomholdt thanks for pointing that out. Fix will be live soon.

**Comment by jonas-lomholdt** [comment]
> @jonas-lomholdt thanks for pointing that out. Fix will be live soon.

Awesome! Thanks.
