### ISSUE TITLE
no more "The compiler generates several warnings about how null values are handled. See this GitHub issue and Nullable reference types for more information."

### ISSUE THREAD

**Issue by raoulteeuwenPE** [dotnet/AspNetCore.Docs#24476]
Just wanted to share i read

"The compiler generates several warnings about how null values are handled. See this GitHub issue and Nullable reference types for more information."

but i did not have such errors. So maybe that now is solved and this text can be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, not resolved yet.
