### ISSUE TITLE
Can a dotnet 6.0 Worker App (with a BackgroundService) run as a docker container in Azure?

### ISSUE THREAD

**Issue by agiletea** [dotnet/AspNetCore.Docs#24494]
[Enter feedback here]
 Following the best practice guide [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio), I am struggling to deploy such a background worker application into a Azure Web App for Containers (Linux) as a Docker Image as the service shuts down after expecting a ping response which is does not get as there are no http entry points to hit.
Is this deployment scenario unsupported or should we be able to deploy our app to ACR and then allow the Web App to run as a container?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
