### ISSUE TITLE
Changing package references advice

### ISSUE THREAD

**Issue by stuart-lawrence** [dotnet/AspNetCore.Docs#24495]
the article says: In the project file, update **each** Microsoft.AspNetCore.* and Microsoft.Extensions.* package reference's Version attribute to 6.0.0 or later

Is that right?

Doing this broke every reference to AspNetCore packages. For instance - Microsoft.AspNetCore.Http the latest version is 2.2.2, so changing it to 6.0.0 means the package cannot load.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&amp%3Btabs=visual-studio&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @stuart-lawrence. Which version are you migrating _from_? A large number of packages were [removed in 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio#remove-obsolete-package-references), so if you're using something earlier than that, you'll need to remove the affected package references.
