### ISSUE TITLE
.NET 6: HTTP Logging 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24504]
Replace https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/http-logging/samples/6.x with the current template generated code. This article was written with .NET 6 preview 1.

@smandia  do you want this one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by smandia** [comment]
@Rick-Anderson  Yes I want to work on it

**Comment by smandia** [comment]
work in progress

**Comment by smandia** [comment]
@Rick-Anderson  Please review https://github.com/dotnet/AspNetCore.Docs/pull/24533
