### ISSUE TITLE
Error in About Page

### ISSUE THREAD

**Issue by gabicantarini** [dotnet/AspNetCore.Docs#24508]
[It is missing an assembly ref. and I think this is the biggest error in the about page. I made the code download available in the  tutorial, but it is different from the section sorting, filtering, and paging tutorial. But the download code is more complete and because of that I cannot compare the errors. Thank you.]
![aboutpageerror](https://user-images.githubusercontent.com/89015121/148206628-e2e3d5cc-d2ca-4f85-ab7b-07c3d800e2b7.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutorial: Add sorting, filtering, and paging - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you show the code that has the error?

**Comment by gabicantarini** [comment]
This is the code:

[cid:f60f0e18-6e1d-4106-9125-2f1c70d77237]


@model IEnumerable<ContosoUniversity.Models.SchoolViewModels.EnrollmentDateGroup>

@{
    ViewData["Title"] = "Student Body Statistics";
}

<h2>Student Body Statistics</h2>

<table>
    <tr>
        <th>
            Enrollment Date
        </th>
        <th>
            Students
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>
            <td>
                @item.StudentCount
            </td>
        </tr>
    }
</table>

Those are the errors:


[cid:79251893-bd29-484e-95d7-b463cce93126]

[cid:9516b9c4-9d38-465e-b6ef-12fcad53cd0f]

________________________________
De: Rick Anderson ***@***.***>
Enviado: quarta-feira, 5 de janeiro de 2022 17:53
Para: dotnet/AspNetCore.Docs ***@***.***>
Cc: Gabriela Cantarini ***@***.***>; Author ***@***.***>
Assunto: Re: [dotnet/AspNetCore.Docs] Error in About Page (Issue #24508)


Can you show the code that has the error?

**Comment by Rick-Anderson** [comment]
Take a look at https://docs.microsoft.com/aspnet/core/data/ef-rp/sort-filter-page
It's much more up to date.

**Comment by gabicantarini** [comment]
Yes, I saw. But this is the razor pages tutorial. I was following the MVC tutorial. Is it not good?

________________________________
De: Rick Anderson ***@***.***>
Enviado: quarta-feira, 5 de janeiro de 2022 23:49
Para: dotnet/AspNetCore.Docs ***@***.***>
Cc: Gabriela Cantarini ***@***.***>; Author ***@***.***>
Assunto: Re: [dotnet/AspNetCore.Docs] Error in About Page (Issue #24508)


Take a look at https://docs.microsoft.com/aspnet/core/data/ef-rp/sort-filter-page
It's much more up to date.

**Comment by Rick-Anderson** [comment]
MVC or RP (Razor Pages) is a choice. Some people use both. They are very similar. RP makes many things easier. The RP version is much more up to date. I hope to update the MVC version this year.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
