### ISSUE TITLE
Is this updated for .net 6.0?

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/AspNetCore.Docs#24525]
Instructions in `Typescript integration` section do not appear to work. The property `ResolveCurrentProjectStaticWebAssetsInputsDependsOn` is not consumed in `Microsoft.NET.Sdk.Razor.StaticWebAssets.targets` file and the generated javascript files are not copied to right location when a web project referencing the razor class library is published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @nvmkpk. No, this hasn't yet been updated for .NET 6. That's being tracked in #24053.

**Comment by nvmkpk** [comment]
Thanks for pointing the issue tracking it. It appears Microsoft.Typescript.Msbuild packages also has changed and just adding CompileTypescript target as dependency is not enough. I had to add a custom target to get the typescript targets to run before the static web assets are discovered.

**Comment by fabianffrank** [comment]
I had the same problem and was able to solve it with this:
```
<StaticWebAssetsPrepareForRunDependsOn>
    CompileTypeScript;
    $(StaticWebAssetsPrepareForRunDependsOn)
</StaticWebAssetsPrepareForRunDependsOn>
```
