### ISSUE TITLE
New ProblemDetails Json formatting configuration

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#24529]
A new topic talking about new APIs https://github.com/dotnet/aspnetcore/issues/39010 should be included to explain how to configure the output Problem Detail formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@brunolins16  should this be a new topic or a section in this document? Can you provide a sample project showing how to use your new API and we can write an article around the sample. cc @serpent5

**Comment by brunolins16** [comment]
@Rick-Anderson , I think the new documentation could be added as part of those two topics

https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0#configure-systemtextjson-based-formatters

https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0#add-newtonsoftjson-based-json-format-support

@pranavkm , are you ok with that?

**Comment by pranavkm** [comment]
Yup, those look reasonable.

**Comment by brunolins16** [comment]
@Rick-Anderson here is a very simple sample (https://github.com/brunolins16/aspnet.samples/tree/main/Samples/JsonMetadataAPI). Let me know if that is enough.
