### ISSUE TITLE
Question: Purpose of AddressTagHelperComponentTagHelper 

### ISSUE THREAD

**Issue by seangwright** [dotnet/AspNetCore.Docs#24537]
In the examples above, what is the role of the `AddressTagHelperComponentTagHelper`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d627ece-78c4-d244-63a8-d43556ca1653
* Version Independent ID: 069ef9fd-61c2-2c65-d0fe-60d272723f03
* Content: [Tag Helper Components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/th-components?view=aspnetcore-5.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/th-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/th-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Use the custom address Tag Helper Component to inject HTML markup as follows:

**Comment by seangwright** [comment]
@Rick-Anderson I think whatever you typed was swallowed up by the internet and disappeared... 🤔

![Screenshot 2022-01-10 173614](https://user-images.githubusercontent.com/1382768/148849870-2925f999-5bec-4c05-855f-198bbc077508.jpg)

**Comment by Rick-Anderson** [comment]
That's a copy/paste from the article
