### ISSUE TITLE
app.UseRouting() does not contribute to the order of middleware execution (custom middleware runs first each time).

### ISSUE THREAD

**Issue by ViktorYeah** [dotnet/AspNetCore.Docs#24539]
Hi, I'll try to briefly explain my finding:

**Expected:**
In the article https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0
mentioned:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/41510265/148648576-6f713927-d85d-4b34-a7d6-842378375ae0.png">
...
> If the preceding example didn't include a call to UseRouting, the custom middleware would run after the route matching middleware.

**What I've tried :**

- use app.UseRouting()
- don't use app.UseRouting() 
- move  MapGet() before Use() middleware and use app.UseRouting()
- move  MapGet() before Use() middleware and don't use app.UseRouting()

**Observed:**
The result is the same: "custom" middleware app.Use(...) always runs first in any of mentioned combinations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0&source=docs)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @ViktorYeah. The custom middleware is the code that runs as part of the `app.Use` call from the example you've shown. The endpoint that returns "Hello World!" always runs last, regardless of the order of the route matching middleware, `UseRouting`. The example demonstrates that, with `UseRouting` placed as-shown, the code inside of the custom middleware sees a `null` result when it calls `context.GetEndpoint()`. You should see the difference by inspecting `context.GetEndpoint()` in the custom middleware with and without the call to `UseRouting`.

If you still think there's an issue here, please provide a minimal GitHub repo as a demo.

**Comment by ViktorYeah** [comment]
Hi @serpent5 , thank you, that was an excellent explanation!

**Comment by geertdoornbos** [comment]
> Hi @ViktorYeah. The custom middleware is the code that runs as part of the `app.Use` call from the example you've shown. The endpoint that returns "Hello World!" always runs last, regardless of the order of the route matching middleware, `UseRouting`. The example demonstrates that, with `UseRouting` placed as-shown, the code inside of the custom middleware sees a `null` result when it calls `context.GetEndpoint()`. You should see the difference by inspecting `context.GetEndpoint()` in the custom middleware with and without the call to `UseRouting`.
> 
> If you still think there's an issue here, please provide a minimal GitHub repo as a demo.

Well, this [documentation](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md) about routing basics is out of date. The explained UseRouting behavior is incorrect:

> However, apps can change the order in which UseRouting and UseEndpoints run by calling these methods explicitly. For example, the following code makes an explicit call to UseRouting: 
...
> If the preceding example didn't include a call to UseRouting, the custom middleware would run after the route matching middleware.

As explained by @serpent5 the order of execution is **not** changed.

**Comment by geertdoornbos** [comment]
> the order of execution is not changed.

It's not about the order of execution of endpoints; it's about order of middleware; when the _matching_ takes place.
