### ISSUE TITLE
Capture logs within ASP.NET Core startup code - NO EXAMPLE GIVEN FOR NET CORE 6.0

### ISSUE THREAD

**Issue by gagwithgaffer** [dotnet/AspNetCore.Docs#24538]
[Enter feedback here]

Please add the correct code sample.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by smandia** [comment]
it will be fixed when this commit is merged 
https://github.com/dotnet/AspNetCore.Docs/pull/24533
@Rick-Anderson @gagwithgaffer
