### ISSUE TITLE
Replace Troubleshoot code with 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24530]
Replace [Troubleshoot](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0#troubleshoot) code  ith the new Request Logging Middleware per https://github.com/dotnet/AspNetCore.Docs/pull/24489#discussion_r779939296

```
using Microsoft.AspNetCore.HttpLogging;
using Microsoft.AspNetCore.HttpOverrides;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.AddHttpLogging(options =>
{
    options.LoggingFields =
    HttpLoggingFields.RequestPropertiesAndHeaders |
    HttpLoggingFields.RequestScheme |
    HttpLoggingFields.RequestMethod |
    HttpLoggingFields.RequestPath;
});

builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders =
        ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
});

var app = builder.Build();

app.UseForwardedHeaders();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
You need to call UseHttpLogging after UseForwardedHeaders.
https://github.com/dotnet/aspnetcore/blob/c68d3b7b7822cef64f07628009a6d0f81ee7291b/src/Middleware/HttpLogging/samples/HttpLogging.Sample/Startup.cs#L23

HttpLoggingFields.RequestPropertiesAndHeaders should be enough.

I just realized we didn't do https://github.com/dotnet/aspnetcore/issues/32247 yet, so you won't be able to get the IPs. Maybe a hybrid approach where we use HttpLogging for everything it can log and then a little custom middleware for the rest.
