### ISSUE TITLE
Typo in Blazor Webassembly Prerender Tutorial Code

### ISSUE THREAD

**Issue by elslush** [dotnet/AspNetCore.Docs#24545]
Within the Webassembly tutorial for prerendering ([link](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0&pivots=webassembly)):
![image](https://user-images.githubusercontent.com/26159293/148697831-7b886c30-31f6-48f6-8527-7a9edda14594.png)

the render-mode is set as "ServerPrerendered" when it should be "WebAssemblyPrerendered", as seen below.
![image](https://user-images.githubusercontent.com/26159293/148697892-d3d7a8da-18af-4bbd-a779-a5e5ae5f6ca0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329a19ef-fb46-1f6b-a734-fa1c1334b1e5
* Version Independent ID: 3fa4318a-3c11-c1d8-bf24-ddc6d8441ca2
* Content: [Prerender and integrate ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/prerendering-and-integration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/prerendering-and-integration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @elslush ... Given the complexity, I'll ask the PU ("product unit") next week to take a look at the whole scenario, possibly the whole topic. Indeed, it might have just been a cut-'n-paste typo along the way. We've had several updates to the content, some of which couldn't get PU review/feedback because they were just too busy with high priority framework issues (e.g., the .NET 6 release). I'll ask the end of next week. Everyone should be fully back and dug out on holiday email and whatnot ⛏️⛰️.

**Comment by guardrex** [comment]
Indeed, it looks like I was struggling with it on ...

https://github.com/dotnet/AspNetCore.Docs/pull/24035

... and couldn't reach it before the holiday break. According to what I said there, it's on my tracking issue, so it would've eventually had some feedback. Let's go ahead here with your issue and ask.

btw --- Just wildly guessing on what I was facing, I thought that I might have tried it the way you suggested and ran into trouble, then figured that I would pitch it as a `ServerPrerendered` rendering mode. It's easy enough to test either way. Apparently, you're saying that you've used `WebAssemblyPrerendered` and didn't have any ill effects in the running app ... no 😈.

**Comment by guardrex** [comment]
@elslush ... Ok, yes, I see now what you mean walking the guidance. I can't say if that's a typo or if I was trying to fix something else that broke in an edge case of some sort. I agree with you that this change should be made. My test app with two layouts, one for the hosted Blazor WASM app and one for the RP/MVC app, worked well with this update. I also found a few more nits and bits to update along the way.
