### ISSUE TITLE
Consistent syntax for `*.proto`

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#24543]
How should the file extension `*.proto` be shown in tests? There is inconsistent usage between italics - **\.proto* - and code - `*.proto`.

Which is correct?

**Comment by guardrex** [comment]
Code without an asterisk, as \`.proto\` for `.proto`. The asterisk wasn't thought to be meaningful; and although the MS Style Manual doesn't call for it, we code-fence them to prevent localization.

**Comment by Rick-Anderson** [comment]
I agree with @guardrex , Code without an asterisk, as \`.proto\` for `.proto`. 

@guardrex  BTW, Jason Card is no longer our Loc rep.

**Comment by guardrex** [comment]
Thx ... do we have a replacement for Jason to ping in case a future question arises?

**Comment by JamesNK** [comment]
This should stay open until all the `.proto` references are updated. It should just be a matter of a couple of find/replaces to make them consistent.

**Comment by guardrex** [comment]
Do you want me to knock it out in the morning?

**Comment by JasonCard** [comment]
hi @guardrex 
@khoiph1 (Khoi Pham) is the current localization owner you can ping then needed.

**Comment by guardrex** [comment]
Thanks @JasonCard ... and for all of your help here over the last few years. It was always great working with you on loc issues.
