### ISSUE TITLE
No example for javascript upload of large files

### ISSUE THREAD

**Issue by juszkiem** [dotnet/AspNetCore.Docs#24551]
In the section "Upload large files with streaming" it states "The following example demonstrates how to use JavaScript to stream a file to a controller action. "  There is no example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The 5.x sample app dropped that coverage but the topic's remark wasn't updated.

@juszkiem, you can see the JS code in the 3.x sample app. For example ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads/samples/3.x/SampleApp/Pages/StreamedSingleFileUploadDb.cshtml

**Comment by guardrex** [comment]
We might need to leave this open because @Rick-Anderson might decide to update that remark. If there's a PR for this, this issue will close automatically later when the PR merges. Otherwise, he might just close this as a won't-fix after looking things over.
