### ISSUE TITLE
Just use UseStaticFiles twice

### ISSUE THREAD

**Issue by geometrikal** [dotnet/AspNetCore.Docs#24559]
This popular SO question shows that people are confused about how to serve extra file locations as well as wwwroot: https://stackoverflow.com/questions/41021715/how-can-you-use-multiple-directories-for-static-files-in-an-aspnet-core-app/41021991#41021991

The answer to serving both wwwroot and another directory is to use static files twice:

```
app.UseStaticFiles();
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(
        Path.Combine(Directory.GetCurrentDirectory(), "static"))
});
```
However in the section **Serve files outside of web root** it only uses a single UseStaticFiles but the text gives the impression that wwwroot will also be server, when in fact the code does not do this.

Suggestion:

Update the text to say that if you want to serve other directories as well as wwwroot, you need to have a parameterless UseStaticFiles plus extra UseStaticFiles for each other directory. Add two UseStaticFiles to the code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0&viewFallbackFrom=aspnetcore-3.0#serve-files-outside-of-web-root)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @geometrikal. Thanks for the feedback.

An alternative approach, which lets you use just one instance of the middleware added with `UseStaticFiles`, might be to make use of `CompositeFileProvider`:

```csharp
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new CompositeFileProvider(
        builder.Environment.WebRootFileProvider,
        new PhysicalFileProvider(
            Path.Combine(Directory.GetCurrentDirectory(), "static")))
});
```

For versions before 6.0, the approach to access `WebRootFileProvider` is different, but the concept is the same. I can't speak for whether that's a _better_ approach, though.

@Rick-Anderson What do you think? We have a note in the article that says "Additional instances of `UseStaticFiles` and `UseFileServer` can be provided with other file providers to serve files from other locations." that covers this. That note came from PU, so there's a high probability that the approach I've suggested might not be recommended.

**Comment by geometrikal** [comment]
@serpent5 Thanks for that, I will try that one as well. :)

**Comment by Rick-Anderson** [comment]
@wtgodbe please review or recommend a reviewer. I like @serpent5  approach.

**Comment by wtgodbe** [comment]
@Tratcher @BrennanConroy could you take a look?

**Comment by Tratcher** [comment]
The double UseStaticFiles is simpler but does need some explanation.

CompositeFileProvider is self documenting but more complex. I think this approach also breaks blazor (https://github.com/dotnet/aspnetcore/issues/34159).

Let's go with the first one plus comments. Also, avoid CurrentDirectory.
```
app.UseStaticFiles(); // Serve files from wwwroot
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(
        Path.Combine(builder.Environment.ContentRoot, "static"))
});
```
