### ISSUE TITLE
Mistake in text

### ISSUE THREAD

**Issue by MollsAndHersh** [dotnet/AspNetCore.Docs#24556]
Please find where it says "Optional parameters aren't supported"... this should say "Optional parameters **ARE** supported" based off the content that immediately follows the statement :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#route-to-components-from-multiple-assemblies)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MollsAndHersh ... It's considered a hack. At 3.1 **formal** optional parameters aren't supported. Optional params **_are supported_** for 5.0 or later.
