### ISSUE TITLE
.NET 6 NSwag 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24573]
Update sample to .NET 6 or .NET 7 or .NET 8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by smandia** [comment]
@Rick-Anderson  Can I work on these and create new samples.

**Comment by Rick-Anderson** [comment]
Yes

**Comment by Rick-Anderson** [comment]
@smandia  start with the code. See https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag/samples/stub.txt

**Comment by smandia** [comment]
Work in progress

**Comment by Rick-Anderson** [comment]
@smandia It might be easier to put the sample code in https://github.com/dotnet/AspNetCore.Docs.Samples

**Comment by Rick-Anderson** [comment]
@smandia  let me know if you're still interested in this and if I can help.

**Comment by postmeback** [comment]
Hi @smandia , any update ?
