### ISSUE TITLE
Add F# samples

### ISSUE THREAD

**Issue by jkone27** [dotnet/AspNetCore.Docs#24578]
Also add F# samples in code boxes please
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We don't have the resources to support F#

**Comment by jkone27** [comment]
Oh come on it’s just docs, is this serious 🧐

**Comment by SeanMartz** [comment]
I don't think we should trivialize the time and effort it takes to maintain high quality docs, but I do wish that there were F# samples.

**Comment by SeanMartz** [comment]
@Rick-Anderson  Is this something that the community can assist with, and if so what might that look like?

 I'd hate to see this option as something that's completely off the table without full consideration for the options; especially considering how awesome I've found the F# community to be. 
 
 If this has been considered in the past and hasn't been possible, then please feel free to point me to those discussions so I can catch up.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Is this something that the community can assist with, and if so what might that look like?

Right now we don't have the resources to maintain F# samples, so we're not taking F# contributions. However, we can vet an external sample and link to that, at least in the current version.
