### ISSUE TITLE
Dependency injection in the healthchecks

### ISSUE THREAD

**Issue by laazik** [dotnet/AspNetCore.Docs#24571]
It would make sense to note on the health checks page (and also add at least one example with the constructor) that health checks dependency injection works same way as any other service creation and registration in the stack.

Right now it is not clearly obvious that all DI constructs behave and thus if e.g. one needs to inject either a logger or a singelton describing the state of a service into the health check it just works. I personally assumed that since it is using a completely different registration chain (`.AddCheck`) with quite different signatures to other service registration methods, it is not supported.

E.g.
```
public class Foo : IHealthCheck {
    private ILogger<Foo> _log;
    public Foo(ILogger<Foo> log) {
        _log = log; // <- gets injected
    }
}
```
The use case for this would be e.g. a health check that validates not only some sort of connection being up (e.g,. AMQP to Rabbit), but also that the worker has been processing messages or is not stalled. Implementing this would actually need to have a service specific global singleton that has relevant data for the healthcheck. And this can be solved using the DI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> that health checks dependency injection works same way as any other service creation and registration in the stack.

Why would you think it works differently?

**Comment by laazik** [comment]
Because it's not obvious. There is a lot of talk about custom creators etc., but nothing about the DI, somehow I draw a conclusion that this is not possible and based on digginging in the API-s and docs. 

So instead of writing a test program to validate if it actually works, it would make sense to make a note of this. Especailly considering that there is a weird example that allows sending parameters to the health check constructor during the registration, which was very confusing.

**Comment by JuergenGutsch** [comment]
Maybe it makes sense to add just a small hint or a small demo to show that DI into a health check is working, but this also needs a hint that actually doing DI into a health check might cause confusion and doesn't make sense in cases where you need to use a check twice with different configurations. This is why most health check extensions receive a config object that gets passed to the constructor explicitly without DI. Means: explicit configuration per health check registration.

Most checks do very explicit checks that don't need a kind of a global configuration. I would agree that there might be some scenarios where it would make sense to use DI.

(I recently stumbled upon that problem as well while working on a book about health checks.)

**Comment by Rick-Anderson** [comment]
@JuergenGutsch  any chance you could create a sample app in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/host-and-deploy/health-checks/samples (create 7.x folder) ) and maybe draft out the explanation?

**Comment by JuergenGutsch** [comment]
@Rick-Anderson yes, sure!
