### ISSUE TITLE
How do we set the HttpClient base URL if that URL is in appsettings.json file?

### ISSUE THREAD

**Issue by xavierjohn** [dotnet/AspNetCore.Docs#24609]
How do we set the HttpClient base URL if that URL is in appsettings.json file?
Tried this which works locally but fails on Azure web app so maybe it is not the correct approch.

```
builder.Services.AddHttpClient<SomeClass>()
.ConfigureHttpClient((sp, httpClient) =>
{
var genevaClientSettings = sp.GetRequiredService<IOptions<GenevaClientSettings>>().Value;
httpClient.BaseAddress = genevaClientSettings.GenevaBaseUrl;
})

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @xavierjohn ... I think it's in the Configuration doc, but there's a nibblet in the *Configuration* section of the Minimal API doc that I can cross-link quickly ...

https://docs.microsoft.com/aspnet/core/fundamentals/minimal-apis#configuration

**Comment by xavierjohn** [comment]
Thanks. I will try 
builder.Configuration.GetValue<string>("{THE KEY}");

I can't use option since the app is still being configured.
