### ISSUE TITLE
No "Services" folder in ASP .Net Core MVC 5

### ISSUE THREAD

**Issue by aks2161989** [dotnet/AspNetCore.Docs#24611]
A line from this tutorial says

Create a class to fetch the secure email key. For this sample, create Services/AuthMessageSenderOptions.cs:

I am using >Net Core 5.0 on Visual Studio 2019. There is no "services" folder in my project. Please modify the tutorial accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @aks2161989. Thanks for taking the time to provide feedback.

 The `Services` folder shouldn't already exist in the project - this is a folder that you'll need to create yourself.
