### ISSUE TITLE
SQLite for dev section refers to startup.cs, needs update for 6.0

### ISSUE THREAD

**Issue by soyfrien** [dotnet/AspNetCore.Docs#24626]
***EDIT by @Rick-Anderson*** Fix [VS-mac Scaffold the movie model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-mac&source=docs#scaffold-the-movie-model)

There doesn't seem to be any autogenerated Startup.cs class following the VS for Mac guide. Could it be made less confusing?

It was also optional to omit this step with out any issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-mac&source=docs)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  can you fix this ASAP?

**Comment by soyfrien** [comment]
I think I can fix it. I remember Startup.cs from 1.0, I think maybe the section is talking about Program.cs and erroneously displays class instead. If @wadepickett is busy I can fork a fix..

**Comment by Rick-Anderson** [comment]
.NET 6 doesn't use Startup. That code didn't get updated.

**Comment by soyfrien** [comment]
Never mind he actually fixed it right away: 

https://github.com/dotnet/AspNetCore.Docs/commit/2dab2c07f48421407de1962e47eed6f09ac06199#diff-e4b7c5dc266a0f437d1ed4d95eac773a08626e05f8c694aaa458ae0d045930bc

Thank you... I do have a a feature request that I'll link back to this dock regarding the Terminal always starting in ~/

**Comment by soyfrien** [comment]
Oh wait it hasn't been pushed up yet.

**Comment by wadepickett** [comment]
Just adding a note: old startup code example that needs to be updated is in section _Use SQLite for development, SQL Server for production_.   The [6.0 sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60) is correct (thank goodness).  Will update that section of the doc.  Sorry it was missed.

**Comment by wadepickett** [comment]
This one had to wait for VS 2022 for mac.  Working on it now with the RC version available, along with all other updates that were waiting.
