### ISSUE TITLE
How does SignalR work with Blazor Server when everything is rendered server-side?

### ISSUE THREAD

**Issue by rysep2** [dotnet/AspNetCore.Docs#24620]
I understand that Server Blazor doesn't run client-side, instead every frontend rendering is done by the server and updated to the browser over SignalR in the background. So what happens when I create a "second" SignalR hub/client like explained in the referenced Microsoft Docs page? The SignalR hub is server-side but the SignalR client in the .razor file is server-side too. Does that mean that in this case the SignalR library just forces a rerender of the page server-side and then it is pushed to the browser over the existing Blazor Server SignalR connection? Or is there somehow a second websocket connection?

I'm sorry if this was asked before or if I'm asking in the wrong place. I couldn't find any information on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097456af-6293-8c24-3991-fc815b94dcbf
* Version Independent ID: 978264ac-18f8-e937-30db-7050e53ac7d1
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=server#feedback)
* Content Source: [aspnetcore/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rysep2 ... It's best to ask on the product unit's repo at ...

https://github.com/dotnet/aspnetcore/issues

Please add a ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24620
```

... to the bottom of your opening comment. If they indicate something good to add to the topic, then I'll re-open this for work.
