### ISSUE TITLE
Share authentication cookies among ASP.NET apps

### ISSUE THREAD

**Issue by feededit** [dotnet/AspNetCore.Docs#24633]
I set AuthenticationType, CookieName and CookieDomain in UseCookieAuthentication in subdomain Startup.cs page which is ASP.NET 4.x.

Even with this configuration, subdomain sites can get User.Identity.Name and User.Identity.Id from cookies.

Like how I did it in ASP.NET 4.x,
Can ASP.NET Core get User.Identity.Name and User.Identity.Id from cookies?

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
