### ISSUE TITLE
Misleading paragraph about Razor components

### ISSUE THREAD

**Issue by alvipeo** [dotnet/AspNetCore.Docs#24631]
I was trying to use View Components and then I read the following:
>When considering if view components meet an app's specifications, consider using Razor components instead. Razor components also combine markup with C# code to produce reusable UI units. Razor components are designed for developer productivity when providing client-side UI logic and composition. For more information, see ASP.NET Core Razor components. 

ok, I spent some time learning about Razor Components. What did I find? I found it a complete WASTE of time when it comes to ASP.NET Razor pages project (to use Razor Components). Razor Components are pain in the ass to use in regular Razor pages. Please remove that paragraph. Do not confuse people!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0#view-components)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @alvipeo ... That's not an opinion that management shares. Besides, you aren't being forced to use them. All this says is to "consider" using them.

**Comment by alvipeo** [comment]
@guardrex that's not just my opinion, I also found here - [https://andrewlock.net/dont-replace-your-view-components-with-razor-components/](https://andrewlock.net/dont-replace-your-view-components-with-razor-components/).

I was reading on component options for MVC/Razor pages but suddenly, after reading that paragraph and moving to the Razor components page I found myself in the Blazor territory. And that is NOT what I want. Then, reading about how to invoke Razor components and passing parameters I just stopped. Too much hassle.

**Comment by guardrex** [comment]
Let's consider options to improve the coverage.

Side notes ...

* The product unit is aware of the challenges of integrating components into RP/MVC apps. For example (and this might not be the only open/closed issue), see https://github.com/dotnet/aspnetcore/issues/38112, which is currently scheduled for .NET 7 in ~November if it makes the final roadmap and timelines for release hold up.
* We've made the integration process clearer in the docs, but it's a work in progress. It is still challenging for a dev to get all of the pieces into place to adopt Razor components in an RP/MVC app, especially when UI layout and styles should match, authn/authz is involved, when user state is in play, interaction with databases is required, and service lifetimes are different (i.e., scoped to circuits versus scoped to HTTP requests). We may do something with this remark, and we may look at the integration guidance again as part of this issue, but I think we'll only focus on the remark here and work further on the integration topic when we see what the product unit does for .NET 7.

We'll need to wait a bit to engage with this issue, perhaps a few weeks up to a month. We're in the midst of a number of high priority issues at the moment that must be resolved near-term, including lingering 6.0 issues and the introduction of a new doc node for .NET MAUI.
