### ISSUE TITLE
Render Blazor components from JavaScript:Set childContent Parameter

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24648]
I try to set the childContent from JavaScript but it give me error relating to RenderFragment. How we can set Render Fragment Parameter from JavaScript here?
```
var dialogElem=document.getElementById("dialog");
Blazor.rootComponents.add(dialogElem,"dialog",{title:"Title of Dialog",childContent:`Test sample`});
```
![image](https://user-images.githubusercontent.com/48277995/149845174-0f0acfec-c3a8-4e9e-834d-5aed699b39c6.png)

Thanks for your response

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... Please ask the product unit on that one at ...

https://github.com/dotnet/aspnetcore/issues

Please add a ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24648
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.
