### ISSUE TITLE
Blazor File Downloads Docs result in exception

### ISSUE THREAD

**Issue by groogiam** [dotnet/AspNetCore.Docs#24656]
This documentation appears to result in an exception. Opened an issue with the ASP.NET team to figure out the proper way to dispose of stream reference.

https://github.com/dotnet/aspnetcore/issues/39603

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Version Independent ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Content: [ASP.NET Core Blazor file downloads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-downloads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @TanayParikh
* Microsoft Alias: **taparik**

**Comment by TanayParikh** [comment]
Thanks @groogiam. I've replied to the aspnetcore issue. @guardrex have you seen this before, I haven't been able to repro. Closing out the docs issue and will track any fixes if required on aspnetcore (as it'll likely be a framework fix if somethings broken).
