### ISSUE TITLE
.NET 6: SignalR with TypeScript and Webpack

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/AspNetCore.Docs#24650]
remove versions, ie use `npm i -D clean-webpack-plugin css-loader html-webpack-plugin mini-css-extract-plugin ts-loader typescript webpack webpack-cli`
Replace cook book instructions with copy the `src` folder from the download sample. Explain the contents of each file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
@Petermarcu  yes, we're marching through these based on traffic. I'll move this one up in priority and try to get it updated next week.

**Comment by Petermarcu** [comment]
Priority based on traffic is fine. I mainly just wanted to make sure it was on the radar and had a plan. You can close this if you are tracking elsewhere.

**Comment by Rick-Anderson** [comment]
Put the sample code in https://github.com/dotnet/AspNetCore.Docs.Samples
I can show how to reference snippets from there.
