### ISSUE TITLE
Missing code in JsonOptions sample

### ISSUE THREAD

**Issue by andrebires** [dotnet/AspNetCore.Docs#24669]
Seems that is something missing in the code sample for configuring the JsonOption with minimum APIs.

Maybe something like this?

```csharp

using Microsoft.AspNetCore.Http.Json;

var builder = WebApplication.CreateBuilder(args);

// THIS IS MISSING?
builder.Services.Configure<JsonOptions>(options =>
{
    options.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase, false));
});


var app = builder.Build();

app.MapGet("/", () => new Todo { Name = "Walk dog", IsComplete = false });

app.Run();

class Todo
{
    public string? Name { get; set; }
    public bool IsComplete { get; set; }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@andrebires  nice catch, thanks.

**Comment by serpent5** [comment]
The missing code for this can come from [here](https://gist.github.com/davidfowl/ff1addd02d239d2d26f4648a06158727#customizing-json-binding):

```csharp
// Configure JSON options
builder.Services.Configure<JsonOptions>(options =>
{
    options.SerializerOptions.IncludeFields = true;
});
````

@Rick-Anderson Do you want me to add this, or perhaps we could offer it up as a good-first-issue?

**Comment by Rick-Anderson** [comment]
@serpent5 can you fix, it would be nice to get this fix out soon.
