### ISSUE TITLE
There is no sample app source code

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/AspNetCore.Docs#24670]
Sample app section is missing a link to an actual sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @VictorioBerra ... I'm not sure why, but the link we normally have at the top isn't present. It's down in the *Additional resources* section.

Leave this open ... it might be updated per your issue here.

**Comment by Rick-Anderson** [comment]
@guardrex One of the PMs did a study with alot of folks and they were confused by the sample at the top. They thought that the sample was needed before they could start. Maybe we should leave samples at the top in some cases. For sure on onboarding tutorials we want them at the bottom.

**Comment by guardrex** [comment]
Yeah ... I understand that happening. Let me know if there's a general move. I have very few in the Blazor docs. You know I've been trying avoid sample apps 😩 like the plague ... ugh ... *bad joke* during COVID! I do have one in the EF Core doc, and there's one in the SignalR-Blazor tutorial. I'm going to mark my tracking issue to adopt it at least for the tutorial.

**Comment by Rick-Anderson** [comment]
Let's just have that policy on onboarding tutorials. The rest, use your judgement.

**Comment by guardrex** [comment]
Define "onboarding."

**Comment by Rick-Anderson** [comment]
New to the product, intro tutorials, nothing advanced. We assume no prior programming in that framework.

**Comment by guardrex** [comment]
Ok
