### ISSUE TITLE
Mentioned incorrect file name

### ISSUE THREAD

**Issue by SAMR1T** [dotnet/AspNetCore.Docs#24674]
When talking about the URL routing it says:

"
The routing format is set in the **Program.cs** file:

```
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
```
"
but this cannot be found in the Program.cs file, this is instead found in **Startup.cs** file. So I believe that change needs to be made so the tutorial is easier to follow. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in Program with .NET 6

**Comment by SAMR1T** [comment]
OK, just got confusing because I assumed when I clicked the "Visual Studios Code" tab that all instructions below would be according to that. Thanks.
