### ISSUE TITLE
the hub connection is working fine on the desktop chrome , mozilla and etc. but not working on ios 10 safari using PWA

### ISSUE THREAD

**Issue by mortezakehtari** [dotnet/AspNetCore.Docs#24673]
Hey there, 
here i have a strange behavior of microsoft/signalr:
actually I have created a PWA app using service worker. it's working fine on my desktop browsers even after installing the app.
but it's not working on ios 10 safari and cannot create hub connection.

here is the code of hub service:
import { Injectable } from '@angular/core';
import {
  HttpTransportType,
  HubConnection,
  HubConnectionBuilder,
  LogLevel,
} from '@microsoft/signalr';
import { BehaviorSubject } from 'rxjs';
import { take } from 'rxjs/operators';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class GeolocationHubService {

  hubUrl = environment.hubURL;
  private hubConnection: HubConnection;

  constructor() { }

  createHubConnection(data: any) {
    this.hubConnection = new HubConnectionBuilder()
      .withUrl(this.hubUrl + `geolocation?code=${data.code}&date=${data.date}`, {
        accessTokenFactory: () => localStorage.getItem('token'),
      })
      .configureLogging(LogLevel.Debug)
      .withAutomaticReconnect()
      .build();
    console.log(this.hubConnection);
    this.hubConnection.start().catch((error) => {
      console.log(error);
    });
  }
  async sendlocation(data: any) {
    this.hubConnection.invoke('SendLocation', data).catch((error) => {
      console.log(error);
    });
  }
  stopHubConnection() {
    if (this.hubConnection) this.hubConnection.stop();
  }

}

And i must mention that i changed the tsconfig.base.json target to "es5" because otherwise the app will not run on the old ios device.
Is the "es5" or ios 10 safari the main problem?
how can i resolve this problem?

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://learn.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---
[Associated WorkItem - 61756](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61756)

**Comment by Rick-Anderson** [comment]
@adityamandaleeka  I could add that info to [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-6.0) then provide a link to the `ES5 for browsers that do not support ES6`  in every SignalR topic under

## Additional information

* `Link to transpile the library to ES5 for browsers that do not support ES6`

**Comment by mortezakehtari** [comment]
finally I could find the error message,
when the app is trying to build hub connection this error happens : "cannot find variable require"
it is just happening on IOS safari 10- browsers. and I don't know why.
i hope the error message might help to find the problem.

**Comment by adityamandaleeka** [comment]
> @adityamandaleeka I could add that info to [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-6.0) then provide a link to the `ES5 for browsers that do not support ES6` in every SignalR topic under
> 
> ## Additional information
> * `Link to transpile the library to ES5 for browsers that do not support ES6`

Sounds good to me, any thoughts @BrennanConroy?

**Comment by BrennanConroy** [comment]
Seems fine, but putting it on every page might be a bit much?
