### ISSUE TITLE
Default console logger format set to JSON breaking change

### ISSUE THREAD

**Issue by tverboon** [dotnet/AspNetCore.Docs#24687]
Migrating from .Net 5 to .Net 6 while running in containers, will change the default console logging formatter to json -> https://github.com/dotnet/dotnet-docker/issues/3274

I totally missed this unfortunately. Maybe an idea to add something about this to **Update Docker Images**:
https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#update-docker-images

It isn't mentioned in the breaking changes links AFAIK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Added to https://github.com/dotnet/docs/issues/27906
