### ISSUE TITLE
Improve docs on debugging ASP.NET Core product source in VS 2019

### ISSUE THREAD

**Issue by billti** [dotnet/AspNetCore.Docs#24691]
Opening a new issue, as dotnet/aspnetcore#9350 is closed, but it is in line with what @sebazzz was trying to achieve I believe. (I guess it related to dotnet/aspnetcore#27380 also).

The docs/wiki aren't that clear on how to set up a local environment for running and debugging the ASP.NET Core source (preferably without running an installer which results in non-local changes). This is really helpful not just as a learning aid, but also for developing and debugging the product.

I spent a while trying to get this set up the past couple of days, and ended up with a simple / productive workflow. I wrote up what I ended up doing at https://ticehurst.com/2021/04/06/debugging-asp-net.html . If this looks roughly right, I'm happy to contribute to a wiki page or markdown file to help others. (And if it isn't quite right, happy to fix it up and then contribute).

@natemcmaster mentioned he was trying to make debugging the source easier, and @pilchie had some suggestions for working with NuGet packages (which was my biggest pain), so tagging here to see if they have input.

The docs are great, but it really clicked for me after being able to seamlessly step through the code for some of the more complex or nuanced stuff. Let me know how I can help! Thx.

**Comment by dougbu** [comment]
Transferred issue though @tommcdon may push for a change in VS to make things easier. Later comments make the action @Rick-Anderson expects to do more clear.

**Comment by tommcdon** [comment]
> Suspect [1310497](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1310497) isn't planned for immediate work. If that's the case (@tommcdon❔), we should move this issue to one of the docs repos...

> Transferred issue though @tommcdon may push for a change in VS to make things easier. Later comments make the action @Rick-Anderson expects to do more clear.

I think it is reasonable to document in the asp.net docs repo.  The workaround would be to:

1. Set `COMPlus_ReadyToRun=0` in the project system to disable Ready to Run
2. Enable `Suppress JIT optimization on module load` in the debugger to JIT the framework code as debuggable

The Visual Studio project system provides mechanisms for setting environment variables in the project system.  Adding @tmeschter who might know where that is documented.

**Comment by billti** [comment]
I will note, I found it interesting that the VS Code extension does document some of these settings for launching its debugger. Might want to align guidance there. See https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#suppress-jit-optimizations

**Comment by Rick-Anderson** [comment]
> The Visual Studio project system provides mechanisms for setting environment variables in the project system. Adding @tmeschter who might know where that is documented.

It's documented [here](https://docs.microsoft.com/en-us/visualstudio/debugger/jit-optimization-and-debugging)

cc @vancem

**Comment by tmeschter** [comment]
> 
> It's documented [here](https://docs.microsoft.com/en-us/visualstudio/debugger/jit-optimization-and-debugging)
> 

That shows you how to turn on `Suppress JIT optimization on module load`. To set the COMPlus_ReadyToRun environment variable, you need to update the launch profile that will be used on F5/Ctrl+F5.

Open the drop down menu on the "Start" button, like so:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/10506730/150580850-e5229bc8-6772-49cd-ac86-c194443a56e7.png">

and then update "Environment variables":

![image](https://user-images.githubusercontent.com/10506730/150580598-5cd082b7-d748-4156-84e6-e12960dedb71.png)

_Note we're working on bringing back the grid we used to have for environment variables in the old UI, but for the moment you'll need to edit them as text._

These settings all get saved to the launchSettings.json file associated with the project and are also available when using the `dotnet` cli.

**Comment by Rick-Anderson** [comment]
It's documented [here](https://docs.microsoft.com/en-us/visualstudio/debugger/jit-optimization-and-debugging)
but it was badly out of day, two versions out of date so I [PR'd](https://github.com/MicrosoftDocs/visualstudio-docs/pull/7560/files) it just now. 

> These settings all get saved to the launchSettings.json file associated with the project and are also available when using the `dotnet` cli.

That's [my PR fix](https://github.com/MicrosoftDocs/visualstudio-docs/pull/7560/files), just add the settings to the `launchSettings.json` file. Much easier and when the UI changes, no need to update the doc.
