### ISSUE TITLE
What does p:DeployOnBuild=true do?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#24690]
Can someone add some details with regard to the switch:  **-p:DeployOnBuild=true** 

- What does this do?

The article only states "Don't pass DeployOnBuild to the dotnet publish command." -- but gives no explanation as to why or what this switch even means -- Apologies in advance if I missed something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @bdcoder2 ... It's an old MSBuild property that isn't supported for the SDK. It probably could be removed at this point. It was probably more important to warn folks off of in the beginning of .NET Core.

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/hh720861(v=vs.120)

**Comment by Rick-Anderson** [comment]
See https://endjin.com/blog/2016/10/how-to-package-a-web-project-for-deployment-from-the-command-line#:~:text=One%20possible%20way%20to%20get,are%20really%20just%20transitive%20dependencies.&text=%22DeployOnBuild%22%20tells%20msbuild%20that%20this,as%20part%20of%20the%20build.

**Comment by bdcoder2** [comment]
For anyone else that asks...

Found this:  [https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/building-and-packaging-web-application-projects](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/building-and-packaging-web-application-projects)

Which states:

- The DeployOnBuild=true property essentially means "I want to execute an additional target when build completes successfully.
- The DeployTarget property identifies the name of the target you want to execute when the DeployOnBuild property is equal to true. In this case, you're specifying that you want MSBuild to execute the Package target after building the project.

All I was doing was using the command line (msbuild) to publish a website to a folder -- since my publishing profile does NOT contain a "DeployTarget" node, I can simply exclude the -p:DeployOnBuild=true option.  Seems to work just fine without it.
