### ISSUE TITLE
How to work with OpenApiProjectReference

### ISSUE THREAD

**Issue by yonexbat** [dotnet/AspNetCore.Docs#24705]
Hi,

This article is missing important information. After adding an open-api-file, what happens next? Looking at the unit tests (https://github.com/dotnet/aspnetcore/blob/main/src/Tools/Microsoft.dotnet-openapi/test/OpenApiAddProjectTests.cs), it adds nswag client package and adds an _OpenApiProjectReference_.  
How do I work with _OpenApiProjectReference_s? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by Rick-Anderson** [comment]
See https://github.com/OAI/OpenAPI-Specification
