### ISSUE TITLE
why use await Task.Yield() ?

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#24702]
why do you need `await Task.Yield(); ` before
`messageText = "Blaze It!";` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omuleanu ... I don't have further information from the PU on that bit or outside of what's explained by the [API doc on `Task.Yield`](https://docs.microsoft.com/dotnet/api/system.threading.tasks.task.yield) ... i.e., "to force the method to complete asynchronously." You can open an issue for them on their repo to inquire further on it ...

https://github.com/dotnet/aspnetcore/issues

If you do so, please add a ping for me. If they reply with useful information, I'll re-open this and provide additional information. Here's a bit that you can paste into the bottom of your opening comment ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/24702
```

**Comment by omuleanu** [comment]
I don't think this is an asp.net core issue, 
my best bet would be that the one wrote the demo code:
probably wanted to show that you can put an `async` method for the `EventCallback` property but at the same time there was nothing to await and he wanted to avoid the async without await method warning
