### ISSUE TITLE
is there extra configuration?

### ISSUE THREAD

**Issue by cherchyk** [dotnet/AspNetCore.Docs#24701]
Don't we need to add?

    `"Logging": {
        "LogLevel": {
            "Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware": "Information"
        }
    },`

without `Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware` sample in the article dosn't output logs

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by Rick-Anderson** [comment]
Its there, could be more clear.

https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0#enabling-http-logging

**Comment by Rick-Anderson** [comment]
I think I just added that in #24681 so it might not have been there when you looked at the doc. See https://github.com/dotnet/AspNetCore.Docs/commits/main/aspnetcore/fundamentals/http-logging/index.md
