### ISSUE TITLE
asp-page does not work as described

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/AspNetCore.Docs#24706]
```cshtml
<a asp-page="/Test/Attendee">All Attendees</a>
```

> Prefixing the page name with a forward slash ("/") creates the URL.

If this were the case, we would get the following result:

```html
<a href="/Attendee">All Attendees</a>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
That could be better worded. Prefix with `/` and it looks for the matching page from the root of the app.

**Comment by yecril71pl** [comment]
> That could be better worded. Prefix with `/` and it looks for the matching page from the root of the app.

Are you sure?.

```cshtml
<a asp-page="../Test/Attendee">All Attendees</a>
```

Does this always evaluate to the absolute path?

```html
<a href="/Test/Attendee">All Attendees</a>
```
