### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/AspNetCore.Docs#24708]
Databases are important for websites but styling is too. I think I am more interested in a short explanation of how to manage styles. The VS ASP.Net Core template uses Bootstrap, right? So it would help to mention that. For me I want to reset the fonts to the default fonts for HTML (Times Roman?). It is difficult for me to determine how to do that. Some guidance in this tutorial that just points to relevant (Bootstrap?) documentation for that type of thing would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Styling is not the focus of our tutorials but there's plenty available on the web.

**Comment by SimpleSamples** [comment]
No there is not; not that is relevant here.

**Comment by Rick-Anderson** [comment]
https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps
