### ISSUE TITLE
gRPC interceptors on .NET

### ISSUE THREAD

**Issue by erni27** [dotnet/AspNetCore.Docs#24718]
Hi,

Recently I've been working on gRPC on .NET. Although the existing documentation wrote mostly by @JamesNK is really comprehensive it seems to lack section about intercepting. gRPC interceptors are barely mentioned in different sections and for people who just getting started with gRPC it could be a little bit difficult to put everything together. 
So my proposal is to create a separate section within `Remote Procedure Call apps` aggregate dedicated to gRPC interceptors. (https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0).
The topic might contain the following:
- Introduction
- Unary interceptors with example
- Stream interceptors with example
- How to apply interceptors for both client and server apps

I'd love to work on this section by my own but before I get started for real please let me know what you think about this.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by wadepickett** [comment]
Reopened as #24720 and suggestion for new section in the doc approved.
