### ISSUE TITLE
Sentence needs to be updated. It implies .NET 6 hasn't been released yet.

### ISSUE THREAD

**Issue by erhanalankus** [dotnet/AspNetCore.Docs#24715]
# Before you open an issue

If the issue is with an ASP.NET Core document:

* Do **not** open a new issue using this form.
* Open the issue with the **This page** button and form at the bottom of the document's page.

Using the **This page** button and form to open an issue:

* Adds article metadata for tracking, which indicates the article that you're commenting on.
* Automatically notifies the article's author about your issue.

If the issue is:

* A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
* A general support question, consider asking on a support forum site.
* A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
* A problem completing a tutorial, compare your code with the completed sample.
* A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

The sentence:
`Ignore NU1603 package mismatch warnings, they will be fixed when .NET 6 is released.`
on page: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio#fix-the-warning-messages
implies .NET 6 hasn't yet been released.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
