### ISSUE TITLE
gRPC interceptors on .NET

### ISSUE THREAD

**Issue by erni27** [dotnet/AspNetCore.Docs#24720]
Hi,

Recently I've been working on gRPC on .NET. Although the existing documentation wrote mostly by @JamesNK is really comprehensive it seems to lack section about intercepting. gRPC interceptors are barely mentioned in different sections and for people who just getting started with gRPC it could be a little bit difficult to put everything together. 
So my proposal is to create a separate section within `Remote Procedure Call apps` aggregate dedicated to gRPC interceptors. (https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0).
The topic might contain the following:
- Introduction
- Unary interceptors with example
- Stream interceptors with example
- How to apply interceptors for both client and server apps

I'd love to work on this section by my own but before I get started for real please let me know what you think about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
Yes, I think this would be good documentation.

Something to consider is client interceptors vs server interceptors. The same type is used to create both client and server interceptors which is slightly confusing. I think the page should be broken up into client and server sections.

This example could be used for doc samples - https://github.com/grpc/grpc-dotnet/tree/master/examples#interceptor

I think this section on interceptors vs middleware can be added at the bottom: https://docs.microsoft.com/en-us/aspnet/core/grpc/migration?view=aspnetcore-6.0#grpc-interceptors-vs-middleware

Table of contents:

* Introduction
 * Client interceptors (include bullet point list of methods on Interceptor to override for client)
   * Unary interceptors with example
   * Stream interceptors with example (note: I think this is pretty advanced. Should probably leave out)
   * Configure client interceptors
 * Server interceptors (include bullet point list of methods on Interceptor to override for server)
   * Unary interceptors with example
   * Stream interceptors with example (note: I think this is pretty advanced. Should probably leave out)
   * Configure server interceptors
   * gRPC Interceptors vs Middleware

What do you think?

**Comment by wadepickett** [comment]
@erni27, thanks for help!   I will watch for your PR and help with any editing needed or formatting to fit into the doc set.  I will also help review, although @JamesNK 's review will be paramount.

**Comment by wadepickett** [comment]
Follow up:

@erni27, were you still planning on writing a new section related to the code example you provided?  If not, we can look at taking it from here and writing something up.  If you still planned on writing it, great.  No worries either way and your contributions thus far are already greatly appreciated.

**Comment by erni27** [comment]
Hi @wadepickett! Yeah, I'm still on it. I just have had a lot of things to do. But this is my number one on my cool things to-do list. 😅 I wrote a draft already but I'm not satisfied with it. I can safely say that the pr will be submitted in early March at the latest.

**Comment by wadepickett** [comment]
@erni27, sounds good, no worries.  Thanks for the update.
