### ISSUE TITLE
Overriding SetParametersAsync 

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24739]
I think it may be better to make it clear in the document that even in case of overriding component's `SetParametersAsync` we should have one of following similar returns expression:
`return base.SetParametersAsync(ParameterView.Empty);`
`return base.SetParametersAsync(parameters);`
It does not work in case of` return Task.CompletedTask;` as expected. Apparantely the default method calls sth which make the component rendering continues.
https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... It already shows that ...

```csharp
await base.SetParametersAsync(parameters);
```

It's in the example. The text states ...

> If `base.SetParametersAsync` isn't invoked, developer code can interpret the incoming parameters' values in any way required. For example, there's no requirement to assign the incoming parameters to the properties of the class.

These remarks have been reviewed and approved by the product unit several times. I believe this is what they'd like to state.
