### ISSUE TITLE
Is it appropriate to return NoContent in case of DbConcurrencyException

### ISSUE THREAD

**Issue by ddonabedian** [dotnet/AspNetCore.Docs#24756]
If a DbUpdateException occurs, when the TodoItem exists the sample code returns NoContent.
It seems more appropriate to return an HTTP code indicating a server error (HTTP 503 ?) to inform the client.

 ```
 try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException) when (!TodoItemExists(id))
            {
                return NotFound();
            }

            return NoContent();
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's template generated code. You open this issue in https://github.com/dotnet/aspnetcore/issues
