### ISSUE TITLE
.Net 6 tutorials shows .Net 5 tutorials.

### ISSUE THREAD

**Issue by mesn1985** [dotnet/AspNetCore.Docs#24755]
The Documentation seems to be for .Net 5 and not .Net 6. There are some differences to the structure  of
the scafolded project (E.g. Startup class i no longer used).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, dup of #13920

**Comment by Rick-Anderson** [comment]
note to self, Add warning, link to RP version, etc.

**Comment by mesn1985** [comment]
Ah sorry, i missed issue 13920.

**Comment by Rick-Anderson** [comment]
@mesn1985 That's OK. Can you follow https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro
