### ISSUE TITLE
HttpHandler and HttpModules do not work the way this article assumes.

### ISSUE THREAD

**Issue by bobsort** [dotnet/AspNetCore.Docs#24764]
This is just a feedback,

HttpHandlers and HttpModules are not always used the same way that this article assumes (that they are in same assembly and in same application at all time).

With HttModules I can transfer request to an entirely different application. I can load assemblies at runtime that contain the handler. and I can configure which handlers are binding to which requests by just editing the web.config (which technically only restarts application for new requests and request in progress is not affected) 

With middleware implementation of .net core, everything is hard coded into the C# code of the application (unless special functionality implemented with very complex code) you will not be able to swap in or out a handler, without compiling the whole project and deploying it again.

With HttpModules and Httpandlers I can simply edit the web.config and reroute traffic to another handler. or drop in a different logger HttpModule in place of existing logger HttpModule and even if I want I can load it from a different assembly too.

I hope I was clear.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f81f11-5621-b581-69f5-60093946b8ed
* Version Independent ID: 886858c7-29eb-714a-22ff-c30973d889e1
* Content: [Migrate HTTP handlers and modules to ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/http-modules.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/http-modules.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
