### ISSUE TITLE
Adopt param attribute value prefix `@` convention

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#24769]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7ba96d-bae0-96ee-e76a-71c6e5f4c23f
* Version Independent ID: 5fe884b8-51e1-1b91-57f8-522ff0b7890c
* Content: [ASP.NET Core Blazor cascading values and parameters](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/cascading-values-and-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by rswetnam** [comment]
I found this page confusing.  Not sure if I shoiuld start with empty or Blazor Server App or BlazorServer App Empty.  After starting on empty and adding MainLayout to root directory, it became obvious that I should have used first option as Nav was missing.  MainLayout should have been pasted over Main Layout in Shared Shared Folder.  Inconsistent casing , difficult to follow - needs to be looked at more closely

**Comment by guardrex** [comment]
The "empty" template is a special template without boilerplate code and described in these locations ...

* https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-7.0&pivots=windows#blazor-template-options
* https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-7.0

I'll open an issue on the rest. Idk what you mean about inconsistent casing, but I agree that this article could use a simpler set of introductory examples for base use cases. The themed styling example is fine, but it's overkill for the most basic use case. Starting with something simpler and clearer will make the feature easier to understand.

It will take a while to reach the new issue tho. We're buried in .NET 8 work right into 24Q1.

**Comment by guardrex** [comment]
I opened it here ...

https://github.com/dotnet/AspNetCore.Docs/issues/30107

You can tack on something about "inconsistent casing" if you wish. Idk what you mean by that.

**Comment by guardrex** [comment]
... and BTW just for future reference, we need a new issue for everything. Open an issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
