### ISSUE TITLE
"Small" vs "Large" file size

### ISSUE THREAD

**Issue by SvendK** [dotnet/AspNetCore.Docs#24763]
Just a tiny thing. The doc is discussing solutions for either "small" or "large" files, and we can all agree that a few kilobytes is small and several gigabytes is large, but where is the line? 

Even if it is hardware dependent (better hardware can handle larger files), there should still be a section discussing this. I'm going to handle files of normally 10-4000 kilobytes but it could be bigger. I'm going with small files for now, but if my files where several megabytes, I would be more in doubt.

Thanks :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#upload-small-files-with-buffered-model-binding-to-a-database)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SvendK ... There's no firm answer to this question because the underlying technology bears on exhausting resources. The best that the PU could offer is the section that deals with the tradeoffs between buffering and streaming. The critical point is ...

> If the size or frequency of file uploads is exhausting app resources, use streaming.

Several megabytes is probably considered "small" in most contexts.
