### ISSUE TITLE
Excellent clarity on the topic

### ISSUE THREAD

**Issue by pinkesh79** [dotnet/AspNetCore.Docs#24765]
[Enter feedback here]
Excellent clarity on the topic, it really helped me resolving my issue related to migration to ASP.Net Core 3.1! Thank a ton!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio#mvc-service-registration)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Thank you for taking the time to provide us with your feedback, @pinkesh79. It's great to see that this was helpful and guided you along in your migration efforts.
