### ISSUE TITLE
Use streaming in ASP.NET Core SignalR: clean up moniker hell

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24787]
See [13 dependabot commits on Jan 27th](https://github.com/dotnet/AspNetCore.Docs/commits/main) to bump version for security fixes.

@BrennanConroy  Can I delete 2.2 given it's out of support? Can I delete 2.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
2.2 definitely, 2.1 I'm not sure... what are we doing about 2.1 docs?

**Comment by Rick-Anderson** [comment]
2.1 is out of support, except for 2.1 on .NET framework. But that's just support, not how to docs. Should I delete the 2.1? We haven't had a 2.1 question in years.

**Comment by BrennanConroy** [comment]
> We haven't had a 2.1 question in years.

We've had customers looking at newer versions of docs before and complain that the feature described in the docs doesn't work for them, and it ends up being because they are on an older version of the product and just need to select the correct version of the docs to read.

I'm not super against removing 2.1 docs, but it would be nice to include notes/warnings in sections that apply after version X. Like the streaming docs would say the `IAsyncEnumerable` parts apply to 3.1+.

**Comment by guardrex** [comment]
Following adding those types of remarks across the content, would the plan be to leave those comments in place release-to-release in far-future versions?

Say ASP.NET Core **_17_** is the current version and the earliest supported version is a couple of versions earlier, **15.x**. Docs retain remarks like, "This section applies to ASP.NET Core 3.1 or later." Is that ok in the **ASP.NET Core 17** era of docs?

**Comment by BrennanConroy** [comment]
> Following adding those types of remarks across the content, would the plan be to leave those comments in place release-to-release in far-future versions?

Idk, I'm just trying to avoid people opening issues saying feature X doesn't work for me. If we don't think that's a big issue, then maybe we don't need the notes and can just remove old docs.

**Comment by Rick-Anderson** [comment]
All we need is to add the metadata `monikerRange: '>= aspnetcore-3.1'`
When you select an unsupported version, you get a warning at the top of the page 
 The requested page is not available for ASP.NET Core 2.2. You have been redirected to the newest product version this page is available for.

![image](https://user-images.githubusercontent.com/3605364/151601476-742057a7-7b8a-4fb9-8566-0e737913736d.png)

**Comment by Rick-Anderson** [comment]
Fixed in #24826
