### ISSUE TITLE
What is the built-in? And where can it be found?

### ISSUE THREAD

**Issue by ongzhixian** [dotnet/AspNetCore.Docs#24785]
On Blazor WebAssembly authentication there's a sentence that states:

`To handle authentication, use of a built-in or custom AuthenticationStateProvider service is covered in the following sections.`

It would be helpful if there's a reference to what the built-in AuthenticationStateProvider service is and where it could be found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ongzhixian ...

It's defined in the first line of ...

https://docs.microsoft.com/aspnet/core/blazor/security/#authenticationstateprovider-service

> `AuthenticationStateProvider` is the underlying service used by the `AuthorizeView` component and `CascadingAuthenticationState` component to get the authentication state.

... with a cross-link to the API doc at ...

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.components.authorization.authenticationstateprovider

... which indicates the assembly. You can then find it in reference source at ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/Authorization/src/AuthenticationStateProvider.cs

We don't cross-link reference source for most of the API. Devs should seek out the framework's implementations on the product unit's repo.

**Comment by omarceloribeiro** [comment]
that class is the abstract class. I could not find the builtin implementation class.

this doesn't works: 
builder.Services.AddScoped<AuthenticationStateProvider, AuthenticationStateProvider>();
