### ISSUE TITLE
Outdated information implies functionality only for ASP.NET Core 3.1

### ISSUE THREAD

**Issue by AndrewTriesToCode** [dotnet/AspNetCore.Docs#24792]
This page states:
> Referencing ASP.NET Core in this manner is only supported for projects targeting .NET Core 3.x 

and in general is very .NET 3.1 oriented. It refers to a GitHub issue for later version of ASP.NET Core.

However in the [referenced GitHub issue](https://github.com/dotnet/AspNetCore.Docs/issues/22048) @davidfowl confirmed that this method applies to .NET 5 and presumable .NET 6.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98629146-7d64-9f48-6e45-51bafe8c7116
* Version Independent ID: cdb2b89f-bf1c-f313-0062-7f6b7ef8b611
* Content: [Use ASP.NET Core APIs in a class library](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/target-aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
#21725 tracks .NET 6
