### ISSUE TITLE
Scope-URL instead of scope-name must be used

### ISSUE THREAD

**Issue by olivertrampenau** [dotnet/AspNetCore.Docs#24790]
The sample code with the ConfigureHandler method in the section "Custom AuthorizationMessageHandler class" did not work in my Blazor WebAssembly App. I have to either omit the scopes parameter or to provide the scope-URL (like "api://db475c27-cf47-4076-863a-f2b69719cd6f/example.read") instead of the scope name "example.read". My scope is defined in Azure AD > app registration > API permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-5.0#custom-authorizationmessagehandler-class)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @olivertrampenau ... Yes, that's by-design for this section. This is a **_highly generic_** section. It doesn't seek to make any firm remarks about exactly what the scopes will be for a given provider. Those are truly just examples. I do like the idea of stating that under the example ... even using an example for Azure, as you stated. I'll do that right now. Thanks for commenting on this.

**_Leave this issue open. It will close automatically when the PR merges._**
