### ISSUE TITLE
Unclear how to use on Mac

### ISSUE THREAD

**Issue by Bon-saiGecko** [dotnet/AspNetCore.Docs#24801]
The documentation does not provide any instructions on Mac and the Visual Studio instructions don't seem to be the same. I am using Visual Studio 2022 for Mac Preview, but I have experienced the same in Visual Studio 2019 for Mac. I am unsure how to use this on Mac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use the **.NET Core CLI** instructions and work from the command line.
