### ISSUE TITLE
Behavior of IsEnabled method in .Net 5.0 ? ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#24815]
Looking for more information with regard to logging - specifically the behavior of the **IsEnabled** method, please see my Stackoverflow question at:
[https://stackoverflow.com/questions/70931855/net-5-0-ilogger-method-isenabled-always-returns-true-why](https://stackoverflow.com/questions/70931855/net-5-0-ilogger-method-isenabled-always-returns-true-why)

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at the source and the test. [EventLogLoggerTest](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging/tests/Common/EventLogLoggerTest.cs#L21-L35) shows it works as expected when using only the event logger and setting it.

**Comment by bdcoder2** [comment]
Yes - when using ONLY the event logger -- my code is using the Console logger -- and IsEnabled (for all log levels) is returning true no matter what settings are configured !!

**Comment by bdcoder2** [comment]
All good -- found the relevant information in the .Net 6 documentation which contains much more detail than the .Net 5 document I was referencing.  Have updated my original Stackoverflow question as well.  Thanks again for the quick reply - appreciated (and very much appreciate the additional information added to the .Net 6 documentation) !!
