### ISSUE TITLE
Integration tests example uses In-memory database provider discouraged by EF Core

### ISSUE THREAD

**Issue by martinzwirner** [dotnet/AspNetCore.Docs#24811]
The example uses an In-memory database provider, specifically in the example code below [Customize WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory).

According to the [EF Core documentation](https://docs.microsoft.com/en-us/ef/core/testing/choosing-a-testing-strategy#in-memory-as-a-database-fake) using this provider in tests is highly discouraged due to several shortcomings.

While implementing integration tests I found one of the shortcomings of the In-memory provider: Unique indizes are not enforced and therefore adding the same value repeatedly does not throw an error.

I searched online but couldn't find a simple example on how to implement this. It would be nice if the ASP.NET Core documentation would be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I think highly is highly overstated, see https://github.com/dotnet/EntityFramework.Docs/pull/3710

**Comment by martinzwirner** [comment]
Shouldn't the example in the documentation use the recommended provider then rather than a limited one?

For those who are interested, I got it working using [this example](https://raaaimund.github.io/tech/2019/05/08/aspnet-core-integration-testing/).

**Comment by Rick-Anderson** [comment]
> Shouldn't the example in the documentation use the recommended provider then rather than a limited one?

Yes, that's why the issue is still open. Why aren't you using .NET 6?
