### ISSUE TITLE
Register the database context needs to be updated

### ISSUE THREAD

**Issue by Shruti-Ramenahalli** [dotnet/AspNetCore.Docs#24835]
[Enter feedback here]
WebApplication.CreateBuilder(args); is no longer recognized! The code given in the program.cs is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Shruti-Ramenahalli** [comment]
.NET 6.0!

**Comment by serpent5** [comment]
Ok, thanks. Can you provide more information about the error you see? The tutorial is correct, so `WebApplication.CreateBuilder(args)` _should_ work without issue.

**Comment by Shruti-Ramenahalli** [comment]
![image](https://user-images.githubusercontent.com/93712099/152002198-d5e58144-d937-4a94-9e3d-2f48b93ced1e.png)
![image](https://user-images.githubusercontent.com/93712099/152002223-34c824b0-34fe-4525-9968-3c1c7c90a39f.png)

**Comment by serpent5** [comment]
Your `.csproj` is missing the following, as shown in the [sample](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api/samples/6.0/TodoApi/TodoApi.csproj#L6):

```xml
<ImplicitUsings>enable</ImplicitUsings>
```

If you'd prefer not to use implicit usings, you can add the following to the top of *Program.cs* instead:

```csharp
using Microsoft.AspNetCore.Builder;
```

**Comment by Shruti-Ramenahalli** [comment]
Thanks million...That worked! I am a newbie to this! :)

**Comment by serpent5** [comment]
You're welcome. I'm glad I could help. There's a lot to learn... 😅
