### ISSUE TITLE
Still getting nullable reference type warnings

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#24839]
I deleted "<Nullable>enable</Nullable>" from the MvcMovie.csproj file, but I am still getting errors about using nullable reference types 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande*
![nullable-type-warnings](https://user-images.githubusercontent.com/54067228/152064300-0bc29a31-5641-455d-9370-ceb7aa373dd2.png)
![nullable-type-warnings](https://user-images.githubusercontent.com/54067228/152064337-8191e937-7dfc-4015-bb73-918a9a8ff7d7.png)
*

**Comment by guardrex** [comment]
Try explicitly disabling it ...

```xml
<Nullable>disable</Nullable>
```

**Comment by smiller7812** [comment]
The nullable char is used in the Movie model.
Will that cause an error?

________________________________

**Comment by smiller7812** [comment]
I just tried it.  And restarted Visual Studio.  Didn't seem to make a difference.

________________________________

**Comment by guardrex** [comment]
😕 ... What versions of VS and .NET are you on?

@Rick-Anderson and @serpent5 will be along here, too, at some point to pitch-in. They may have already seen this and can help.

**Comment by guardrex** [comment]
If you're pre VS 2022/6.0, then you can set the topic version back to 5.0 and this code will drop the nullable ref types.

**Comment by smiller7812** [comment]
I'm using Visual Studio 2022 and .Net 6.0.
I've never seen this issue before in previous versions, but I am seeing talk about it on stack for previous versions.

________________________________

**Comment by smiller7812** [comment]
I'm on VS 2022/.Net 6.0 - downloaded all the prerequisites and set up environment so I could get into 6.0.

________________________________

**Comment by guardrex** [comment]
Looks like perhaps a known issue under investigation and resolution. See: https://github.com/dotnet/AspNetCore.Docs/issues/24476

**Comment by guardrex** [comment]
Find that line in the topic ...

> The compiler generates several warnings about how null values are handled. See this GitHub issue and Nullable reference types for more information.

... and go to the GH issue that it cross-links. It probably explains what's going on and when/how they'll fix it.

**Comment by serpent5** [comment]
Hi @smiller7812. Would you be able create a GitHub repo with your project that generates these warnings? I can take a quick look at that to try and find out what's going wrong.

**Comment by smiller7812** [comment]
Hi Kirk,

You can pull it down from:
https://github.com/smiller7812/AspNet6MvcMovie

I just put <Nullable>enable</Nullable>
back into the .csproj file since it didn't make a difference.
I notice scaffolding puts #nullable at the top of CS files.
I guess I might end up doing that from now on.

Thanks,
Sam

________________________________

**Comment by serpent5** [comment]
Thanks for the repo, @smiller7812. I think I know what's going on...

The guidance in the tutorial to disable Nullable Reference Types _changes_ the warnings from something like "Non-nullable property 'RequestId' must contain a non-null value when exiting constructor. Consider declaring the property as nullable." to something like "The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.".

If you want to turn off the warnings completely, you need to do _two_ things:

1. Remove `<Nullable>enable</Nullable>` or set it to `<Nullable>disable</Nullable>`.
2. Remove the nullable annotations from the types. For example, in [`ErrorViewModel`](https://github.com/smiller7812/AspNet6MvcMovie/blob/master/MvcMovie/Models/ErrorViewModel.cs#L5), there's this:

   ```csharp
   public string? RequestId { get; set; }
   ```

   The nullable annotation here is the `?`, so just remove that and the warning should go away. There's a couple more, but the warnings are quite descriptive once you know that, I think.

**Comment by guardrex** [comment]
A very quick thing could be done with the coverage at ...

https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#nullable-reference-types-nrts-and-net-compiler-null-state-static-analysis

In that bullet list, we could just have this added (cut-'n-paste) ...

```
* [Still getting nullable reference type warnings (dotnet/AspNetCore.Docs #24839)](https://github.com/dotnet/AspNetCore.Docs/issues/24839#issuecomment-1028878063)
```

... and then we'd have quick access to it.

**Comment by guardrex** [comment]
... and this ...

> following resources in the C# documentation:

... would go to ...

> following resources:

**Comment by smiller7812** [comment]
What do you do if you need it to be nullable?

________________________________

**Comment by serpent5** [comment]
> What do you do if you need it to be nullable?

Keep `<Nullable>enable</Nullable>` and have a look at [https://docs.microsoft.com/en-us/dotnet/csharp/nullable-warnings](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-warnings).

**Comment by Rick-Anderson** [comment]
See [Nullable reference types (NRTs) and .NET compiler null-state static analysis](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#review-breaking-changes)

See [Fix the warning messages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio#fix-the-warning-messages) in the Razor Pages tutorial for fixing NRT warnings the scaffolder generates.
