### ISSUE TITLE
System.Security.Cryptography.CryptographicException: 'The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning'

### ISSUE THREAD

**Issue by palmej2** [dotnet/AspNetCore.Docs#24847]
I can't actually get this to work.  

- I have a basic ASP.NET MVC .NET 4.8 project created using the examples in the article with the DataProtectionDemo.cs and using the Microsoft.AspNetCore.DataProtection.SystemWeb nuget package.  I did everything exactly how the article described.  Setup as follows:
![image](https://user-images.githubusercontent.com/10965439/152157729-4dd21e58-a73c-42c6-8d90-185a17e2d769.png)

-I created a basic .NET Core Console application injecting the IDataProtectionProvider and setting up the AddDataProjection() exactly how it was done in the first example (but in core).

![image](https://user-images.githubusercontent.com/10965439/152157658-0c291b52-be1a-46af-9908-6c71a7181c20.png)

If I protect a value (any value) on the ASP.NET site and try and unprotect that value on the console application I get the "The payload was invalid.".  Either there missing information in that product article critical to getting this working, or there is a bug in the process.  I've double-checked everything the article mentions.  

- keys are generated correctly in the same file location for both applications
- application name is exactly the same in both applications (my-app)

Any help would appreciated 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709a375-e1f3-a47a-5f91-6bed1782a594
* Version Independent ID: 53e91296-c75c-b446-1487-6710b024ad60
* Content: [Replace the ASP.NET machineKey in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/replacing-machinekey?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/data-protection/compatibility/replacing-machinekey.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/compatibility/replacing-machinekey.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by palmej2** [comment]
> @palmej2 can you create the simplest possible project that reproduces the problem and post a link to the GitHub repository?

@Rick-Anderson - here it is https://github.com/palmej2/DNETFW-2-DNETCORE

**Comment by Rick-Anderson** [comment]
.NET Framework is beyond the scope of this repo.

**Comment by blowdart** [comment]
Log a bug in the aspnet repo. But that package was meant as a stop gap to get you up to 2.1. Really we ought to retire it now, mixing and matching old and new like this isn't great and it's limited to file system and nothing more

**Comment by Rick-Anderson** [comment]
@palmej2 log a but at https://github.com/dotnet/aspnetcore/issues

**Comment by palmej2** [comment]
> @palmej2 log a but at https://github.com/dotnet/aspnetcore/issues

https://github.com/dotnet/aspnetcore/issues/39958

**Comment by palmej2** [comment]
@blowdart Is there a workaround?

**Comment by blowdart** [comment]
@palmej2 Basically stop trying to share cookies like this. It was targeted at auth, and honestly, moving to a proper SSO solution like Identity Server is a much more scalable option here.

**Comment by palmej2** [comment]
I'm failing to see the connection here.  The MachineKey encryption is offered as a general utility and doesn't have to be only used for cookie value encryption (as you are inferring).  Data protection is data protection.
