### ISSUE TITLE
Missing guidance in .NET 5+ version of the docs?

### ISSUE THREAD

**Issue by andrewlock** [dotnet/AspNetCore.Docs#24844]
If you view the .NET Core 3.1 version of this page, you can see additional guidance about installing the ANCM module etc e.g.

![image](https://user-images.githubusercontent.com/18755388/152141150-ee53d6ca-2598-47fd-8c0b-86aca230c980.png)

However, for .NET 5+, this guidance is missing, and doesn't appear to be available anywhere on docs.microsoft.com (possible after this PR? https://github.com/dotnet/AspNetCore.Docs/pull/19987)

Has the guidance changed around app pools and the ANCM module? If so it would be good for that to be explicitly called out. If not, then this content should be available prominently somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mkArtakMSFT please assign someone to review this issue.

**Comment by HaoK** [comment]
I don't think the guidance has changed, but it was already optional, seems reasonable to bring it back though

**Comment by Rick-Anderson** [comment]
@guardrex  compare the [3.1 version](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1) of the doc side by side with the [5.0 most current version](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/)

There are massive sections removed. Do you know the reason? I was thinking about adding an link to the current version,

For more information on 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/3605364/161158430-68f82691-562a-4b7b-8b51-d6a0eb0b5166.png">

See `link to the 3.1 version`.

**Comment by guardrex** [comment]
Was it all moved back to *Advanced scenarios*. Justin did a big shake-up, and I think a lot of basic guidance was moved back to *Advanced scenarios* that aren't really "*advanced*."
