### ISSUE TITLE
Clear All NuGet Caches when scaffolding fails - create Include file.

### ISSUE THREAD

**Issue by iamzm** [dotnet/AspNetCore.Docs#24842]
I am unable to Scaffold area using Visual Studio 2022/2019. 

![image](https://user-images.githubusercontent.com/10797646/152126814-95d87b63-fc61-49d4-b25f-d57021f598d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ammar441** [comment]
You need to clear the NuGet Cache.
1. Go to Tools
2. Options
3. NuGet Package Manager
4. General
5. Clear All NuGet Cache(s)

**Comment by iamzm** [comment]
Thanks, It worked

**Comment by Rick-Anderson** [comment]
@serpent5  should we create an include to add in all the scaffolding topics with a list of remedies when scaffolding fails?

**Comment by serpent5** [comment]
I don't know if this is a problem common enough to need inline troublshooting guidance, but we could link to e.g. [dotnet nuget locals](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals#examples). That page shows an example of how to clear the NuGet cache with one command:

```console
dotnet nuget locals all --clear
````
