### ISSUE TITLE
How to create async Timed background tasks

### ISSUE THREAD

**Issue by jasekiw** [dotnet/AspNetCore.Docs#24848]
This document only covered how to create a timed background task using synchronous programming. I've been using async all the way through my program and converting a task to void or calling .Result has it's issues. Is there an example that can be provided that can avoid these issues for a timed service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gfoidl** [comment]
You can go _async_ by
```c#
...
_timer = new Timer(async _ => await DoWorkAsync(), null, TimeSpan.Zero, TimeSpan.FromSeconds(5));
...

private static async Task DoWorkAsync()
{
    ...
}
```
Just take care that no unhandled exception bubbles up to the async lambda passed to the timer.

---

For .NET 6 with the introduction of the `PeriodicTimer` I'd propose to update the "template" given in the docs to
```c#
public class TimedHostedService : BackgroundService
{
    private int executionCount = 0;
    private readonly ILogger<TimedHostedService> _logger;
    private Timer _timer = null!;

    public TimedHostedService(ILogger<TimedHostedService> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Timed Hosted Service running.");

        // When the timer should have no due-time, then do the work once now.
        DoWork();

        using PeriodicTimer timer = new(TimeSpan.FromSeconds(5));

        while (await timer.WaitForNextTickAsync(stoppingToken))
        {
            DoWork();
        }

        _logger.LogInformation("Timed Hosted Service is stopping.");
    }

    // Could also be a async method, that can be awaited in ExecuteAsync above
    private void DoWork()
    {
        int count = Interlocked.Increment(ref executionCount);

        _logger.LogInformation("Timed Hosted Service is working. Count: {Count}", count);
    }
}
```

--- 

I can submit a PR if this approach seems fine (I use this one in a similar way for quite some time in production).

**Comment by Rick-Anderson** [comment]
@gfoidl can you create a sample in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/host?

**Comment by Rick-Anderson** [comment]
@gfoidl  are you still interested in writing the sample code?

**Comment by gfoidl** [comment]
Oh, sorry I missed the comment from 1st Oct 2022.
Yeah, I can create the sample in a week or two (at the moment a bit busy).

**Comment by Rick-Anderson** [comment]
Awesome. No hurry.

**Comment by Rick-Anderson** [comment]
@gfoidl just checking in.

**Comment by gfoidl** [comment]
@Rick-Anderson did you means something like https://github.com/dotnet/AspNetCore.Docs.Samples/pull/117?

---

Sorry for not being more active 😞, but in winter it's a bit busy for me 😃

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/117

**Comment by jasekiw** [comment]
@Rick-Anderson Why was this closed? The code snippet in the PR never made it to the documentation page that I initially created the issue for.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Why was this closed? The code snippet in the PR never made it to the documentation page that I initially created the issue for.

Sorry, see #28533

**Comment by jasekiw** [comment]
@Rick-Anderson Thanks! I appreciate it.

**Comment by nikolay-dimitrov** [comment]
Im using the BackgroundService - is it possible to have multiple task in **one** background service in .net core with different timer duration:
FirstLoop - execute every second
SecondLoop - execute every minute
ThirdLoop - execute every hour
ForthLoop - execute every day

For some reason only the FirstLoop is been executed and every loop after it is not been executed. What are my options to make this work? 

protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
    if (double.TryParse(_configuration["FirstLoop"], out double firstLoopExecution))
    {
        using PeriodicTimer timer = new PeriodicTimer(TimeSpan.FromSeconds(firstLoopExecution));
        while (!stoppingToken.IsCancellationRequested &&
            await timer.WaitForNextTickAsync(stoppingToken))
        {
            //Wrap any invocations inside this while loop into a try catch so that when one run of the while loop fails, it doesn’t break the entire method meaning the periodic loop continues
            try
            {
                await DoFirstWorkAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error in first loop , " + ex.Message + ", InnerException ex:" + ex.GetOriginalException()?.Message + ", stackTrace:" + ex.StackTrace);
            }

        }
    }
    else
    {
        _logger.LogError("Missing FirstLoop configuration");
    }

    if (double.TryParse(_configuration["SecondLoop"], out double secondLoopExecution))
    {
        using PeriodicTimer timer = new PeriodicTimer(TimeSpan.FromSeconds(secondLoopExecution));
        while (!stoppingToken.IsCancellationRequested &&
            await timer.WaitForNextTickAsync(stoppingToken))
        {
            //Wrap any invocations inside this while loop into a try catch so that when one run of the while loop fails, it doesn’t break the entire method meaning the periodic loop continues
            try
            {
                await DoSecondWorkAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error in second loop , " + ex.Message + ", InnerException ex:" + ex.GetOriginalException()?.Message + ", stackTrace:" + ex.StackTrace);
            }

        }
    }
    else
    {
        _logger.LogError("Missing SecondtLoop configuration");
    }

    if (double.TryParse(_configuration["ThirdLoop"], out double thirdLoopExecution))
    {
        using PeriodicTimer timer = new PeriodicTimer(TimeSpan.FromSeconds(thirdLoopExecution));
        while (!stoppingToken.IsCancellationRequested &&
            await timer.WaitForNextTickAsync(stoppingToken))
        {
            //Wrap any invocations inside this while loop into a try catch so that when one run of the while loop fails, it doesn’t break the entire method meaning the periodic loop continues
            try
            {
                await DoThirdWorkAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error in first loop , " + ex.Message + ", InnerException ex:" + ex.GetOriginalException()?.Message + ", stackTrace:" + ex.StackTrace);
            }

        }
    }
    else
    {
        _logger.LogError("Missing ThirdLoop configuration");
    }

  if (double.TryParse(_configuration["ForthLoop"], out double forthLoopExecution))
    {
        using PeriodicTimer timer = new PeriodicTimer(TimeSpan.FromSeconds(forthLoopExecution));
        while (!stoppingToken.IsCancellationRequested &&
            await timer.WaitForNextTickAsync(stoppingToken))
        {
            //Wrap any invocations inside this while loop into a try catch so that when one run of the while loop fails, it doesn’t break the entire method meaning the periodic loop continues
            try
            {
                await DoForthWorkAsync();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error in first loop , " + ex.Message + ", InnerException ex:" + ex.GetOriginalException()?.Message + ", stackTrace:" + ex.StackTrace);
            }

        }
    }
    else
    {
        _logger.LogError("Missing ForthLoop configuration");
    }
}
