### ISSUE TITLE
Missing using

### ISSUE THREAD

**Issue by johndhunter** [dotnet/AspNetCore.Docs#24856]
Might want to add:
Add a reference to Microsoft.Extensions.Logging;
`using Microsoft.Extensions.Logging;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8795bcc-45ef-7edc-4657-fca867c8ff81
* Version Independent ID: d0b1a040-5dae-8233-dbee-c5837a0c231d
* Content: [ASP.NET Core Blazor logging](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/logging.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @johndhunter ... It already appears several times in the doc. Which scenario are you referring to?

**Comment by johndhunter** [comment]
Basically. right at the beginning
The first using (using Microsoft.AspNetCore.Components.WebAssembly.Hosting;) is not enough by itself at the point the reader hits the next block of code.

**Comment by guardrex** [comment]
Ok, thanks.

**Comment by guardrex** [comment]
It kind'a depends on what features of logging one is using, so I'll place the text that way. I'll call it out as 'some feature also require ... blah blah blah ...' and then have the `using` in it's own cut-'n-paste code block. That should do the trick.
