### ISSUE TITLE
No NuGet package source on my Visual Studio 2022 Community Edition

### ISSUE THREAD

**Issue by alex-lau808** [dotnet/AspNetCore.Docs#24855]
When I followed the step to install NuGet Package. it failed. I checked my NuGet set up and it only showed a local source. I want to know how to add source to my NuGet configuration.

Thanks,

Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you try again?

**Comment by serpent5** [comment]
I've experienced this a few times, when I've set up a new machine, for example. Run the following command to add the default `nuget.org` source:

```
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
```

**Comment by alex-lau808** [comment]
Thanks @serpent5 and @Rick-Anderson for the replies. I resolved it by adding the nuget.org API endpoints in the package manager configuration. I then added the dependencies by right clicking on the solution explorer dependencies tab and added the dependences there.
