### ISSUE TITLE
False-valued-attribute-erasing magic is undocumented

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/AspNetCore.Docs#24860]
This code does not make any sense:
```cshtml
<input asp-for="LastName" 
       disabled="@(Model?.LicenseId == null)" />
```

It is functionally equivalent to the following code:
```cshtml
<input asp-for="LastName" disabled>
```

&hellip; unless you *know* that Razor removes the attribute if its *computed* value is `false`, which is undocumented.  This makes the attribute declarations `disabled=false` and `disabled="@false"` work differently, which is so unexpected that it begs an explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @yecril71pl. Thanks for taking the time to open an issue.

Have you tested this? It's my understanding that Razor excludes the `disabled` attribute entirely if the expression evaluates to `false`.
