### ISSUE TITLE
Component disposal with IDisposable and IAsyncDisposable - Notes Behavior incorrectly/unclearly

### ISSUE THREAD

**Issue by jkdba** [dotnet/AspNetCore.Docs#24863]
The doc notes:

>If a component implements IDisposable, IAsyncDisposable, or both, the framework calls for unmanaged resource disposal when the component is removed from the UI. Disposal can occur at any time, including during [component initialization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-initialization-oninitializedasync).

However the behavior in the [render](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/RenderTree/Renderer.cs#:~:text=disposeComponentState.Component%20is%20IAsyncDisposable) is to only execute one method and to prioritize IAsyncDisposable, meaning you can have both IAsyncDisposable and IDisposable implemented but the framework will not call both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-disposal-with-idisposable-and-iasyncdisposable)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jkdba ... Thanks for the issue. Unclearly, perhaps, but I don't think incorrectly. It doesn't remark on that aspect. Also, that doesn't sound 👂 right to me, but I admit to no deep understanding on it. Let's ask a *real framework engineer* 😄 about it ...

cc: @pranavkm to see if an additional or updated remark makes sense there.

**Comment by guardrex** [comment]
I'm going to introduce language per the PU code comment ...

> Components shouldn't need to implement IAsyncDisposable and IDisposable simultaneously,
> but in case they do, we prefer the async overload since we understand the sync overload
> is implemented for more "constrained" scenarios.
> Component authors are responsible for their IAsyncDisposable implementations not taking
> forever.
