### ISSUE TITLE
Link Component in Blazor

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#24867]
According to this paragraph there should be a `Link` component in Blazor which is distinct from `link` in html. But I get the warning that there is not such component. Does it require to add any package to RCL to have that?

> To provide additional library component styles from stylesheets in the library's wwwroot folder, link the stylesheets using the framework's Link component.

![image](https://user-images.githubusercontent.com/48277995/152442762-3a11ef78-29f7-4200-8219-959f3d5f6083.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b709f5-e04e-fee3-7eea-1364893ab997
* Version Independent ID: a92c88d3-6ee8-1e69-f4c3-49eb82909746
* Content: [Consume ASP.NET Core Razor components from Razor class libraries](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
🐀🍔 **_Roasted Rat Burgers!_** 🐀🍔😄 ... Sorry about that @abdollahkahne! You found a bit of guidance that didn't get reverted out of the docs.

The product unit **_DID_** create such a thing for the 5.0 preview. We documented it for the release. They ran into some issues with it, so it was reverted out of the framework and wasn't released at that time. I tried to get the bits we added **OUT** on https://github.com/dotnet/AspNetCore.Docs/issues/20319, but this **_sneaky devil_** 😈 got by me!

Take a look at the new approach with the `HeadContent` component at ...

https://docs.microsoft.com/aspnet/core/blazor/components/control-head-content

... as it should do the same thing for you in this situation. You can place your stylesheet `<link>` there ...

```razor
<HeadContent>
    <link href="..." rel="stylesheet">
</HeadContent>
```

... and that should 🤞 work.

**_Leave this issue open._** I'll fix it to indicate the new `HeadContent` approach. This issue will automatically close when the PR merges.
