### ISSUE TITLE
Installing aspnetcore-runtime-6.0.1-win-x64.exe fails to detect IIS on Windows Server 2019 and does not install ASPNetCoreModule. 

### ISSUE THREAD

**Issue by devteam-itconsilium** [dotnet/AspNetCore.Docs#24881]
it's likely the .Net 6 Bundle aspnetcore-runtime-6.0.1-win-x64.exe is detecting for an IIS Express setup.  Is there a work round?

**Comment by guardrex** [comment]
Hello @devteam-itconsilium ... Please open for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
