### ISSUE TITLE
Documentation missing AzureBlobLoggerOptions properties?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#24899]
Please refer to my Stackoverflow question at: [https://stackoverflow.com/questions/70992091/net-azureblobloggeroptions-properties-documentation](https://stackoverflow.com/questions/70992091/net-azureblobloggeroptions-properties-documentation)

In the section entitled **Azure App Service**, reference is made to [AzureBlobLoggerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.azureappservices.azureblobloggeroptions), however, the documentation for the options seems to be missing some properties, such the **FileNameFormat** property (an example or two would be most helpful).  Could the documentation be updated to include the missing properties?  

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
It looks like `FileNameFormat` was added in 6.0. There doesn't seem to be an API docs page for anything after 3.1 for the `AzureBlobLoggerOptions` class, so that explains why it's missing. I don't know why there isn't a 5.0 or 6.0 version of the API docs...

**Comment by serpent5** [comment]
@Rick-Anderson Should this issue be transferred elsewhere? How do we understand why there's no version > 3.1 for [AzureBlobLoggerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.azureappservices.azureblobloggeroptions)?

**Comment by Rick-Anderson** [comment]
I'll ping @v-alje offline.
