### ISSUE TITLE
.NET 6: SignalR configuration

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#24895]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks, could you be a little more specific about what the ask is?   It needs to be updated to 6.x?  Or it is 6.x and needs to be updated to 7.x?

**Comment by wadepickett** [comment]
Oh, nevermind, I see you assigned and closed it.  So I guess its moot.
