### ISSUE TITLE
The two different examples (Home, Product) got mixed up together.

### ISSUE THREAD

**Issue by jeancallisti** [dotnet/AspNetCore.Docs#24931]
I think there's a typo.
On this line : 

> The route template "{controller=Home}/{action=Index}/{id?}":

I think you meant to write : 

> The route template "{controller=Product}/{action=Details}/{id?}":

Same with the code snippet just above it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @jeancallisti. Thanks for taking the time to report an issue.

I don't think there's a typo here. In the example, `"{controller=Home}/{action=Index}/{id?}"` represents the route template. The explanation that follows explains how an incoming URL, such as `/Products/Details/5`, maps to that route template. Although the default value for `controller` is `Home`, an incoming URL `/Products/Details/5` sets the value of `controller` as `Products`. However, if the incoming URL is '/', for example, `controller` will be set to `Home`, the default.
