### ISSUE TITLE
dotnet dev-certs https --import doesn't seem to work

### ISSUE THREAD

**Issue by weeix** [dotnet/AspNetCore.Docs#24930]
In the "Trust HTTPS certificate from Windows Subsystem for Linux" section > WSL window, import command doesn't seem to work.

> $ dotnet dev-certs https --clean --import aspnetcore.pfx -p *****************
> Specify --help for a list of available options and commands.
> $ dotnet --version
> 3.1.416

The certificate in `https://localhost:5001` isn't the one that I exported from Windows (the thumbprint doesn't match)

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/th-th/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-2.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by cuongnguyenh** [comment]
> In the "Trust HTTPS certificate from Windows Subsystem for Linux" section > WSL window, import command doesn't seem to work.
> 
> > $ dotnet dev-certs https --clean --import aspnetcore.pfx -p *****************
> > Specify --help for a list of available options and commands.
> > $ dotnet --version
> > 3.1.416
> 
> The certificate in `https://localhost:5001` isn't the one that I exported from Windows (the thumbprint doesn't match)
> 
> #### รายละเอียดเอกสาร
> ⚠ _อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub_
> 
> * ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
> * Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
> * Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/th-th/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-2.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
> * Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-security**
> * GitHub Login: @Rick-Anderson
> * Microsoft Alias: **riande**

I have the same issue

**Comment by Rick-Anderson** [comment]
Dup of #25164

**Comment by Rick-Anderson** [comment]
See #19141
