### ISSUE TITLE
Clarify hot-reload vs Runtime compilation?

### ISSUE THREAD

**Issue by JoeMarkov** [dotnet/AspNetCore.Docs#24944]
I am a bit confused, 

Before .NET 6 I would add Runtime compilation to get the "hot reload" experience, being to make changes to my views and see the response directly in my browser.

But now with HotReload, when would I want to add Runtime compilation? Is if if I want to allow changes in production??

So, what I would like to see is more clear guidance, on when to add RuntimeCompilation and when to just be happy with the HotReload feature.

Also, relevant, the old browser-link concept, is that dead? or is that still supported and used? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 67058](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67058)

**Comment by tdykstra** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/23910#issuecomment-1033107013
