### ISSUE TITLE
The name 'WebApplication' does not exist in the current context

### ISSUE THREAD

**Issue by jsfree** [dotnet/AspNetCore.Docs#24953]
When updating the Program.cs file to include the seeded records, receiving an error "The name 'WebApplication' does not exist in the current context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jsfree** [comment]
> That's usually because the project file is missing ` <ImplicitUsings>enable</ImplicitUsings>`

I'm not exactly sure where I would correct this, could you give me some direction? :)

**Comment by Rick-Anderson** [comment]
Edit the project file.
