### ISSUE TITLE
The code sample has a typo

### ISSUE THREAD

**Issue by vborovikov** [dotnet/AspNetCore.Docs#24951]
The code from the page is wrong:
```cs
if (!app.Environment.IsDevelopment())
{
    app.UseMigrationsEndPoint();
}
else
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}
```
The `!` operator should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vborovikov ... I think this was fixed by https://github.com/dotnet/AspNetCore.Docs/pull/24939 and should go live shortly.

**Comment by guardrex** [comment]
Actually, that went live a while ago on https://github.com/dotnet/AspNetCore.Docs/pull/24940.

@vborovikov ... If you're looking at a non English-US version of the topic, it can take up to two weeks for our doc changes to go live.
