### ISSUE TITLE
UseEndpoints Missing in sample code

### ISSUE THREAD

**Issue by JNickVA1** [dotnet/AspNetCore.Docs#24971]
[Enter feedback here]
The documentation states: _UseRouting, UseAuthentication, UseAuthorization, and UseEndpoints must be called in the order shown in the preceding code._ However, there is no call to UseEndpoints shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @JNickVA1. Thanks for taking the time to open an issue.

Would you be interested in creating a Pull Request to fix this?

**Comment by JNickVA1** [comment]
Yes, I can do that later today.

> Hi @JNickVA1. Thanks for taking the time to open an issue.
> 
> Would you be interested in creating a Pull Request to fix this?

**Comment by JNickVA1** [comment]
I am trying to follow the instructions on the [Contribute to the ASP.NET Core documentation](https://github.com/dotnet/AspNetCore.Docs/blob/bd926d87a7280b7c8ff9d65e85a0cfaa81ec1d8d/CONTRIBUTING.md) page for a [Simple correction or suggestion](https://github.com/dotnet/AspNetCore.Docs/blob/bd926d87a7280b7c8ff9d65e85a0cfaa81ec1d8d/CONTRIBUTING.md#how-to-make-a-simple-correction-or-suggestion), but when I click the Edit link I don't see any directions for creating a Pull Request.

**Comment by Rick-Anderson** [comment]
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
