### ISSUE TITLE
Incorrect example in 'Remove a single secret'

### ISSUE THREAD

**Issue by valcarcelperez** [dotnet/AspNetCore.Docs#24973]
[Enter feedback here]
The example below: 
'The app's secrets.json file was modified to remove the key-value pair associated with the MoviesConnectionString key:'
appears to be incorrect.

It says:
{
  "Movies": {
    "ServiceApiKey": "12345"
  }
}

It should be:
{
  "Movies:ServiceApiKey": "12345"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You can flatten them per the doc but they're the same.
