### ISSUE TITLE
Exception Filter - Exception Propogation

### ISSUE THREAD

**Issue by karayanni** [dotnet/AspNetCore.Docs#24987]
the following is written in the doc of the exception filter:

To handle an exception, set the exceptionhandled property to true or write a response. This stops propagation of the exception. An exception filter can't turn an exception into a "success". Only an action filter can do that. - [see link](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0#:~:text=To%20handle%20an%20exception%2C%20set%20the%20ExceptionHandled%20property%20to%20true%20or%20write%20a%20response.%20This%20stops%20propagation%20of%20the%20exception.%20An%20exception%20filter%20can%27t%20turn%20an%20exception%20into%20a%20%22success%22.%20Only%20an%20action%20filter%20can%20do%20that.)

how ever, when writing to the response the exception is still propogated.

this is how we write the response:
```cs
public async Task OnExceptionAsync(ExceptionContext context)
{
    context.HttpContext.Response.StatusCode = (int)requestFailureException.ResponseStatusCode;
    await context.HttpContext.Response.WriteAsJsonAsync(CreateErrorResponse()).ConfigureAwait(false);
}
```

it's either that the docs aren't 100% clear, or there is a Bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @karayanni. Thanks for taking the time to open an issue.

It appears that setting `ExceptionHandled` to `true` is required, as writing a response doesn't stop the exception from propagating, as you've said. It also appears that it _is_ possible to turn an exception into a "success", as setting `ExceptionHandled` and writing a response results in a 200 status-code by default. I've tested this using Razor Pages and an `IAsyncExceptionFilter`.

I agree: the docs either aren't clear, or something has changed since it was written.

@pranavkm Could you please advise on what might be wrong here in the docs, or let me know who I should ask? I can provide a minimal sample if that helps.

**Comment by pranavkm** [comment]
It should say if `ExceptionHandled` is set or `ExceptionContext.Result` is assigned which would prevent MVC from rethrowing the exception.

**Comment by serpent5** [comment]
> It should say if `ExceptionHandled` is set or `ExceptionContext.Result` is assigned which would prevent MVC from rethrowing the exception.

Thank you @pranavkm.

**Comment by Rick-Anderson** [comment]
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by karayanni** [comment]
@serpent5 sure thing.

**Comment by karayanni** [comment]
@serpent5  can u please give me write permissions

**Comment by karayanni** [comment]
linked a PR to the issue:
https://github.com/dotnet/AspNetCore.Docs/pull/25015

give it a look when u get a chance and thanks for the quick response time.
