### ISSUE TITLE
Issues in ASP.Net core 6

### ISSUE THREAD

**Issue by sxr1999** [dotnet/AspNetCore.Docs#24981]
I don't find anything about `b-nhqxrkkbzm` in document.

I use ASP.NET Core 6 Razor Pages template to create a new peoject, In my ` _Layout.cshtml` the code is

```
<div class="container">
        <main role="main" class="pb-3"> 
```         
But when I use F12 to see the page in browser, I find it create a new attribute b-nhqxrkkbzm, the code is

```
<div b-nhqxrkkbzm class="container">
    <main b-nhqxrkkbzm role="main" class="pb-3">
```

I want to ask what is `b-nhqxrkkbzm`? I find it just in .Net6.

**Comment by guardrex** [comment]
Hello @sxr1999 ... See ...

https://docs.microsoft.com/aspnet/core/razor-pages/#css-isolation

**Comment by sxr1999** [comment]
@guardrex ,[Luke Latham](https://github.com/guardrex)thank you very much
