### ISSUE TITLE
Thanks for doc improvements / Routemap pages (rmp) for .Net websites WITHOUT MVC or Razor

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#24990]
Hello,

Just a note of thanks with regard to the routing information found on this page -- a significant improvement in the details provided compared to the 5.0 and previous docs!

Also, just out of curiosity, I spent some time on the weekend creating an example that uses [routemap] attributes without the need of MVC or Razor -- for lightweight websites.  It seems to work just fine, but I was wondering if anyone from MS had any comments with regard to this method / technique?  I posted the code at: [https://github.com/bdcoder2/rmp](https://github.com/bdcoder2/rmp).

Cheers.

ps: Sorry for the snake_case usage, but its rather difficult to change after 40+ years in the trenches :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment.
