### ISSUE TITLE
HOWTO: Create a blazor web assembly project or a blazor server project 

### ISSUE THREAD

**Issue by dhaanpaa-lab0** [dotnet/AspNetCore.Docs#25009]
**Help us make content visible**

- Blazor server project from scratch
- Blazor web assembly project from scratch

This is the document that I found that did not help: https://docs.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-6.0

**Describe the new topic**

-The topic is needs because there are situations like when you have a corporate template that was done in html or you just want to be able to understand how to build the blazor app from scratch. Also some people have to take to much time to get rid of the extra stuff in the project template
- I Recomend you put this in the blazor documentation
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
This topic will cover how to using visual studio, visual studio code or visual studio for mac be able to build an blazor wasm/server app without using project templates.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
Purpose
Visual studio for mac
Visual studio code
Visual studio
.NET CLI

**Comment by guardrex** [comment]
I've answered you at ...

https://github.com/dotnet/AspNetCore.Docs/issues/25006#issuecomment-1039734786
