### ISSUE TITLE
when i use Code first gRPC ，can i use  Grpc .net. ClientFactory in client?

### ISSUE THREAD

**Issue by doufeng007** [dotnet/AspNetCore.Docs#25014]
my question:
i use Code first gRPC , so my grpc client is ISingletonDependency ;
but sometimes  RAM is too big;
it exist too many Grpc.Core.Channel in memory;

when i use Code first gRPC ，can i use  Grpc .net. ClientFactory in client?
i do not have a class for client  like this:

services.AddGrpcClient<Greeter.GreeterClient>(o =>
{
    o.Address = new Uri("https://localhost:5001");
});

how can i make the Greeter.GreeterClient?

**Comment by wadepickett** [comment]
@doufeng007, could you put your question into context of what we have provided in the topic: [Code-first gRPC services and clients with .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/code-first?view=aspnetcore-6.0)?  That might help me understand what you still need clarified in the docs.  At the bottom of the topic there is an option to leave feedback which files a github issue on the topic.

**Comment by wadepickett** [comment]
Closing, didn't have enough info to understand what might need to be changed in the doc itself.
