### ISSUE TITLE
Add an AAD scenario: authorized client apps for APIs

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25026]
> ... run the application and attempt to fetch data from the server, I get a "Needs Admin Approval" pop-up from the authorization attempt

> add authorization for the client application within the Server API's settings in Azure AD

<img width="912" alt="Capture" src="https://user-images.githubusercontent.com/1622880/154082181-a1ed88f7-6e49-4bd5-9112-fdeb871a44a7.PNG">

This will be for each of the ADD-based articles.

Thanks @tomreich for the tip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92b9c5cb-0e48-25bc-2b7e-e7354bafbe2d
* Version Independent ID: b1e8aedc-b46b-41f1-55c1-e293bc6c93db
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@tomreich ... Can you send me a screenshot of your **_CLIENT_** app's Azure portal screen for **API permissions**? I think you missed a step that then required you to make that setting on the server API app's registration. I think one has to grant admin consent for the permission from the client-side configuration per the doc ... which should ... in theory ... not require the server API app to grant permission to the client app. Also, that's not even an available configuration for untrusted publisher domains, so devs using an untrusted pub domain would have to follow the doc's guidance.

**Comment by tomreich** [comment]
Sorry, I missed this notification.  You're correct that my client app doesn't have Admin permission... I don't have authority to grant that permission; it's delegated.  I was looking for a way to request permission from the user, which the method mentioned in the original post above seems to allow.

To clarify, this is a Blazor app connecting to a custom API and using AAD.  I used the template in Visual Studio, customized using the instructions in the link you posted above.

**Comment by guardrex** [comment]
Ok ... yeah ... that makes sense. I'm **_NOT_** a security guru 😄 ... I'm just a **normal person** 😆. I think now that I know how to scope the configuration that I can cover it in the topics. Let me try, and Javier can review the PR to see if I'm making any sense. I'll try to get to this within the next few days, and I'll ping u on the PR.

**Comment by guardrex** [comment]
You'll get a ping on the PR, so you'll be able to remark on it there. Javier **_IS_** our security guru 👨‍🎓 for the Blazor bits, so he'll confirm/update the PR to make sure that the new text doesn't go off the rails. Keep an 👂 open for the PR ping. It might be tomorrow, but you never know around here ... ⛰️⛏️😅 ... anything with a super-priority will get worked first. For example, I'm expecting Blazor Hybrid coverage to arrive at any time, and I'll need to drop everything for an arbitrary amount of time to deal with Hybrid coverage when it lands.
