### ISSUE TITLE
Align documentation for MVC with Razor Pages

### ISSUE THREAD

**Issue by kevinvavelin** [dotnet/AspNetCore.Docs#25030]
As we look into documentation for the same Get Started tutorial about Entity Framework Core. The version for MVC still mention Startup.cs and not provide the same code source in Razor Pages part. In order to avoid more debate about RP or MVC, I think having both sharing the same code base (except for Controllers and PageModel), will be better for our community

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of https://github.com/dotnet/AspNetCore.Docs/issues/13920
