### ISSUE TITLE
Duplicate paragraph

### ISSUE THREAD

**Issue by ianfoster99** [dotnet/AspNetCore.Docs#25049]
First two paragraphs are almost identical

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [Introduction to ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @ianfoster99. Thanks for taking the time to open an issue.

This was reported and fixed yesterday in https://github.com/dotnet/AspNetCore.Docs/pull/25035. The change will be live soon.
