### ISSUE TITLE
Add middleware ordering for GRPC-web service projects

### ISSUE THREAD

**Issue by danielleiszen** [dotnet/AspNetCore.Docs#25046]
The page does not contain any information about ASP.NET Core services using GrpcWeb endpoints. Regarding #https://github.com/openiddict/openiddict-core/issues/1385 it took some time to figure out the correct ordering for the GrpcWeb middleware in an authorization scenario. The middleware page contains a section about the ordering for a Razor pages scenario which I understand is the most common case. However, mentioning the GrpcWeb middleware in that document would help others finding the right approach to debug these issues. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JamesNK  can you outline the changes needed for this doc to support gRPC?

**Comment by JamesNK** [comment]
gRPC-Web shouldn't be on this page because it isn't bundled with ASP.NET Core.

The only requirement for gRPC-Web is it's between UseRouting and UseEndpoints. That's covered here: https://docs.microsoft.com/en-us/aspnet/core/grpc/browser?view=aspnetcore-6.0#configure-grpc-web-in-aspnet-core

**Comment by danielleiszen** [comment]
> I tested whether gRPC-Web middleware comes before or after CORS and it didn't make a difference. The gRPC-Web middleware shouldn't impact CORS preflight requests.

Should it be true even if used along with Authentication and Authorization?
The issue I mentioned has a repo to test.  The GRPC-web service is called from a Flutter client, and I am not sure if that causes the issue. 

I am really happy to help and since I already put up a repo about it, I can make modifications to make the issue reproducible using MS technology stack alone. Will you have any suggestions on how to test it further?

**Comment by JamesNK** [comment]
Could you get server logs? Lower the log level to Trace to get as much information as possible. Repeat for successful .NET client and unsuccessful flutter client.

There are docs for enabling logging at https://docs.microsoft.com/en-us/aspnet/core/grpc/diagnostics?view=aspnetcore-6.0#grpc-services-logging

**Comment by JamesNK** [comment]
PR that updates the GrpcWebMiddleware - https://github.com/grpc/grpc-dotnet/pull/1618

I don't think this is the issue, but it doesn't hurt to limit middleware to only run if content-type = application/grpc-web AND the request is a POST.
