### ISSUE TITLE
Why documentation says to use NegotiateDefaults for IIS?

### ISSUE THREAD

**Issue by valuator18** [dotnet/AspNetCore.Docs#25052]
Why not `builder.Services.AddAuthentication(IISDefaults.AuthenticationScheme);` for Windows Authentication in IIS/IISExpress? That's how the documentation said to do it in .NET 5 and earlier, still works in .NET 6, and doesn't require brining in an additional package. The docs even specify using the `Microsoft.AspNetCore.Server.IISIntegration` namespace which includes `IISDefaults.AuthentiationScheme`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio#iisiis-express)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
