### ISSUE TITLE
Unneeded namespace in BlazorServer example

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#25074]
I believe in the code under
"Add services and an endpoint for the SignalR hub",
------------------------------------------------------------ 
 using Microsoft.AspNetCore.ResponseCompression;
 using BlazorServerSignalRApp.Server.Hubs;
------------------------------------------------------------ 
the namespace "BlazorServerSignalRApp.Server.Hubs" is  not needed for your example.
I don't think this namespace exists and it does not compile until I remove it.

I'm still having trouble getting mine to work.  I downloaded the samples and the downloaded version works.  I'm comparing mine to that right now.

I believe this may be the line you wanted there:
using BlazorServerSignalRApp.Hubs;
The download and the version I am working through both have that line and not the other.
I'm not sure how I got that in there.  I may have used a smart tag.  I like to use the smart tags to insert the namespaces as I go instead of following the examples on the to usings so I can learn what the namespaces are.

I'm going to scrap and work my way through again.
I just wanted to report that little namespace thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=server)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @smiller7812 ... Yes, this is possible. Many code samples are pulled from the sample apps, but some aren't. This looks like a case where the code is static ... placed directly into the topic. This code must be manually updated but likely didn't get touched for the recent 6.0 release. I'll patch it up right now.

Thanks for reporting this. Leave this issue open. It will close automatically when the PR merges.

**Comment by guardrex** [comment]
@smiller7812 ... Actually, let me revise that last remark ... now that I've looked closer.

That namespace was probably held over accidentally from the Blazor hosted WASM topic. It's not due to the 6.0 release. Yes, I think it should be removed.

I'll fix it right now. Leave this issue open. It will close automatically shortly.

**Comment by guardrex** [comment]
Hummmm ... well ... it is in the sample app tho ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor/samples/6.0/BlazorServerSignalRApp/Hubs/ChatHub.cs#L4

I'll open it locally and see what's what. It is a bit strange that for the Blazor Server sample app that I retained the exact Hubs namespace from the hosted WASM solution (the **`Server`** project) ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor/samples/6.0/BlazorWebAssemblySignalRApp/Server/Hubs/ChatHub.cs#L4

**Comment by guardrex** [comment]
There's another situation to take into account: Implicit usings for namespaces have resulted in these being optional. We'll be trying to work them **_OUT_** of the examples as we go. I'll drop them now where I can.
