### ISSUE TITLE
Issue with HelloWorld Endpoint

### ISSUE THREAD

**Issue by Shanejp** [dotnet/AspNetCore.Docs#25084]
[Enter feedback here]
After Copying and Pasting the HomeController Code, attempt to run code and redirect to the Url with "HelloWorld" appended at the End, results in an error - Page Cannot Be found. Is there another config required to redirect to HelloWorld?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No

**Comment by Shanejp** [comment]
So why would this not be working then?

**Comment by davidfowl** [comment]
Assuming you did the getting started, then did the add controller piece?

**Comment by Shanejp** [comment]
yes, not sure if it matters, I'm using VS 2022

**Comment by Rick-Anderson** [comment]
VS doesn't make a difference. Rather than speculate on all the possible differenced between your code and the instructions code,  compare your code to https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/first-mvc-app/start-mvc/sample/6.0-completed
