### ISSUE TITLE
Expand section on parameter binding to show how to do it by hand

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#25081]
To help users appreciate parameter binding, we should have a section comparing common binding scenarios:
- Reading from route parameter
- Reading from query parameter
- Reading from header
- Reading JSON from the body

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[Explicit Parameter Binding](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0#explicit-parameter-binding)

**Comment by davidfowl** [comment]
Sorry, not this, I used the same words though. I mean Taking in the HttpContext/HttpRequest in the constructor and using them to do those 4 scenarios
- context.Request.RouteValues["id"]
- context.Request.Query["pageSize"]

etc

**Comment by serpent5** [comment]
@davidfowl When you say "in the constructor", what constructor is that? Did you mean to say "in the route handler"? For example, would it be something like this?:

```csharp
app.MapGet("/route/with/{id}", (HttpRequest req) => req.RouteValues["id"]);
```

**Comment by Rick-Anderson** [comment]
> @davidfowl When you say "in the constructor", what constructor is that? Did you mean to say "in the route handler"? For example, would it be something like this?:
> 
> ```cs
> app.MapGet("/route/with/{id}", (HttpRequest req) => req.RouteValues["id"]);
> ```

@brunolins16  can you answer this?

**Comment by brunolins16** [comment]
Reading through comments seems to be exactly what it is. 

I think the idea is to add to the document that the same magic that the Parameter binding does can be accomplished by hand using the `HttpRequest`/`HttpContext` with total control over the binding, but the binding mechanism give it to them "magically" :).

@davidfowl is that sounds right?

**Comment by davidfowl** [comment]
oops, I meant the handler.
