### ISSUE TITLE
Clarification on ITrackingConsentFeature Interface properties ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#25082]
With regard to the [ITrackingConsentFeature Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.itrackingconsentfeature?view=aspnetcore-6.0) and [EU General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-6.0) article, can additional clarity be given with regard to the following properties:

- **CanTrack** - I assume the **developer** sets this value to true when a user gives permission to be "tracked"?
- **HasConsent** - I assume the **developer** sets this value to true when a user gives consent to accept cookies?
- **IsConsentNeeded** - I assume this acts as a flag (for each request) that the developer can check to see if the user has given consent?  For example, IsConsentNeeded will be true until such time that a GDPR cookie is created.  When a GDPR cookie is created and detected by the framework, the value will be false?   The cookie is created by calling the [CreateConsentCookie](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.itrackingconsentfeature.createconsentcookie?view=aspnetcore-6.0#microsoft-aspnetcore-http-features-itrackingconsentfeature-createconsentcookie) method.

Perhaps a table approach as shown below in the **Definition** section or in the description of each property would make it clear as to the action one should take given the value of each property.  (The action items shown below are for illustration purposes -- as I am not 100% sure if they are correct or not).

```
Property          Value   Application Action
----------------  -----  ------------------------------------
CanTrack          true    No action required
                  false   Request consent from user (by displaying banner or alert with opt in/out)

HasConsent        true    No action required
                  false   Request consent from user (by displaying banner or alert with opt in/out)

IsConsentNeeded   true    Request consent from user (by displaying banner or alert with opt in/out),
                          and create a GDPR cookie (include example how)
                  false   No action required
----------------  -----   ------------------------------------
```

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by bdcoder2** [comment]
Sorry for the delay -- I have updated the original post to include more information and questions that arise when someone completely new to the topic reads the existing documentation -- hope that helps.  

I did eventually get things working; by examining the source code of the Interface / classes used for setting up a GDPR cookie.   IMO, It would be nice if additional details were found in the MS official documentation rather than having to spend hours wading through source code and/or examples from third-party sources.

**Comment by Rick-Anderson** [comment]
@blowdart  please review.

**Comment by blowdart** [comment]
The interface doesn't do anything, it's a marker, so saying something like "No action required" or "display banner" is incorrect, that's down to your own specific site implementation.

**Comment by bdcoder2** [comment]
@[blowdart](https://github.com/blowdart) As per the original post:  

_The action items shown below are for illustration purposes -- as I am not 100% sure if they are correct or not_

... hence, the original post -- asking for clarification / action that should be taken given the true / false values;  regardless, I think I have figured it out, so no further action is necessary.
