### ISSUE TITLE
SubdirectoryHandler.SendAsync drops Port

### ISSUE THREAD

**Issue by YaakovN** [dotnet/AspNetCore.Docs#25086]
[Enter feedback here]
IMHO first line in body of SubdirectoryHandler.SendAsync should rather be
`var url = $"{request.RequestUri.Scheme}://{request.RequestUri.Host}:{request.RequestUri.Port}";`
Otherwise a non-default port (e.g. 5001) gets redirected to the default port (e.g. 443)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by YaakovN** [comment]
To clarify, the above refers to [this documentation](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#calling-grpc-services-hosted-in-a-sub-directory).

**Comment by JamesNK** [comment]
Thanks for reporting this. Fix here - https://github.com/dotnet/AspNetCore.Docs/pull/25218
