### ISSUE TITLE
Selecting Japanese shows Turkish for Bundle and minify static assets in ASP.NET Core

### ISSUE THREAD

**Issue by jessegood** [dotnet/AspNetCore.Docs#25083]
As mentioned in the title, the wrong language is shown for `Bundle and minify static assets in ASP.NET Core` page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-6.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
cc: @khoiph1

**Comment by jessegood** [comment]
Just to clarify, this happens for most languages, not just Japanese, the language set in the `html` element and `body` do not match:

![image](https://user-images.githubusercontent.com/13356442/154887320-0ef84196-63a7-459e-86fd-62588657fa66.png)

**Comment by khoiph1** [comment]
Thanks for the feedback. We are investigating the issue https://portal.microsofticm.com/imp/v3/incidents/details/290632050/home

**Comment by khoiph1** [comment]
The publishing issue was fixed by re-running the handback.

**Comment by guardrex** [comment]
Thanks @khoiph1.
