### ISSUE TITLE
Saving Files in File System directly in Blazor Web Assembly

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#25103]
I think the component `FileUpload1` in case of Blazor web Assembly pivot should be removed due the following description.
In component `Pages/FileUpload1.razor` It proposes an approach to save files in files system. Although it works for Blazor Server since it runs on Server and we have access to file system, we can not use the approach in web Assembly. Also, according to code, the example uses `IWebHostEnvironment` to inject environment related data but in case of blazor web assembly, the host type is web host only in prerendering and after the host environment type is `IWebAssemblyHostEnvironment` which has not `ContentRootPath` field. So I think the only option we have in Blazor Web Assembly for file upload is to use APIs (Hosted server or external service). 

Thanks again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by abdollahkahne** [comment]
Oh sorry, I think I am reading something else, Thanks and I close it

**Comment by guardrex** [comment]
btw @abdollahkahne ... We probably will do some work along these lines. True, WASM doesn't access the client file system. Therefore, it's really more like 'process file bytes' when it comes to a Blazor WebAssembly app than a formal 'file upload' ... the word 'upload' is overloaded here and not a good description of what's going on.

> Hosted server or external service).

Yes, that part is right on. That latter section on using a hosted WebAssembly app with a controller is far more likely useful for many scenarios ... it's truly a 'file upload.' ... and it could be a service, yes ... not a controller-type set up.

I don't think we need a formal issue on this. I'm going to add a note to my 2022 tracking issue to come back and work on this in the topic. Thanks for commenting.
