### ISSUE TITLE
Strongly type SignalR

### ISSUE THREAD

**Issue by tacoWanneeJama** [dotnet/AspNetCore.Docs#25115]
When converting a `: Hub` to `: Hub<ImyInterface>`
The Clients.All gives a null exception.
Using a IHubContext is a possible solution, but is not what I want.

I use .Net6 and all libraries the latest versions.

Now I fall back to a not strongly typed Hub.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
Can you share more of what you are doing? Clients.All should not null ref unless you're accessing the Hub manually (which is not supported) or on a separate thread from the Hub method.

**Comment by tacoWanneeJama** [comment]
In the Startup.cs of the client I make the hub available as:
services.AddSingleton<NotificationHub, NotificationHub>();

This works fine when I do it not-strongly typed.

Is this the correct way?

**Comment by BrennanConroy** [comment]
Don't add the Hub to DI

**Comment by BrennanConroy** [comment]
> How can I access the Hub instance?

You don't. The Hub is entirely controlled by the SignalR library and you should not be trying to access an instance of it anywhere.

> Groups don't fulfill this functionality, because I want to be able to list all channels

This sounds like an addition to your background service. It should maintain a list of all channels, and it looks like you can still use groups if all you need is "list all channels" as an extra feature, which your background service can provide.
