### ISSUE TITLE
Is it possible to disable app secret flattening?

### ISSUE THREAD

**Issue by tibold** [dotnet/AspNetCore.Docs#25116]
The app secret flatting removed important comments from my secrets, not to mention that for my eyes the flattened structure in unreadable. :( 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#json-structure-flattening-in-visual-studio)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tibold ... I think this is a 'won't-fix' ... see the issue :point_right: https://github.com/dotnet/aspnetcore/issues/4105
