### ISSUE TITLE
the chinese version is displayed incorrectly

### ISSUE THREAD

**Issue by FrancisFYK** [dotnet/AspNetCore.Docs#25125]
the chinese version is displayed incorrectly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2d968-17a6-1a50-53cd-1d6b9ad0276d
* Version Independent ID: cd22a135-4446-79f5-89db-b741bd44a720
* Content: [Write custom ASP.NET Core middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/write.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/write.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What is displayed incorrectly?

**Comment by Rick-Anderson** [comment]
@FrancisFYK  I'll reopen this when you explain what's wrong.
