### ISSUE TITLE
OKR: Discovery

### ISSUE THREAD

**Issue by mcleblanc** [dotnet/AspNetCore.Docs#25126]
GOAL:
Drive discovery and awareness through SEO improvements.

OBJECTIVES:
Perform selective SEO audits on the following candidate topics:

[Introduction to ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core)
[Introduction to ASP.NET Core SignalR | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction)
[Get started with ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/getting-started/)
[ASP.NET Core Module | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module)
[ASP.NET Core fundamentals | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/)
[Choose an ASP.NET Core UI | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui)
[Common errors reference for Azure App Service and IIS with ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference)
[Facebook, Google, and external provider authentication in ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/)
[Overview of ASP.NET Core Security | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/)
[Develop ASP.NET Core apps using OpenAPI | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi)
[Use ASP.NET Core SignalR with TypeScript and Webpack | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack)
[Resource-based authorization in ASP.NET Core | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased)
[ASP.NET Core Data Protection | Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction)

RESULTS:
Improved organic search rates (>60%) for audited topics.

**Comment by Rick-Anderson** [comment]
| Topic | Owner | Complete |
| ----- | ----- |------ |
| [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core) | @wadepickett | [ ] |
| [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction) | @wadepickett | [ ] |
| [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/) | @wadepickett | [ ] |
| [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module) | @serpent5 | [ ] |
| [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/) | @serpent5 | [ ] |
| [Choose an ASP.NET Core UI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui) | @wadepickett | [ ] |
| [Common errors reference for Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference) | @Rick-Anderson | [ ] |
| [Facebook, Google, and external provider authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/) | @wadepickett | [ ] |
| [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/) | @Rick-Anderson | [ ] |
| [Develop ASP.NET Core apps using OpenAPI](https://docs.microsoft.com/en-us/aspnet/core/web-api/microsoft.dotnet-openapi) | @Rick-Anderson | [ ] |
| [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack) | @serpent5 | [ ] |
| [Resource-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased) | @Rick-Anderson | [ ] |
| [ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction) | @wadepickett | [ ] |

**Comment by Rick-Anderson** [comment]
@mcleblanc  OKR completed.
