### ISSUE TITLE
Add links to  Tutorial: Deploy an ASP.NET Core and Azure SQL Database app to Azure App Service

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25138]
Add links to https://docs.microsoft.com/en-us/azure/app-service/tutorial-dotnetcore-sqldb-app to the end of all on boarding tutorials.

**Comment by wadepickett** [comment]
@Rick-Anderson ,
By "onboarding tutorials" do you mean just:
[Razor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-6.0&tabs=visual-studio)
[MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-6.0)
[Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-6.0&pivots=server)

Or did you intend this link to be added to more than that such as:
[Minimal Web API](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)    (Not sure if this is the new intended starting point or not for web API)
[SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-6.0&tabs=visual-studio)

**Comment by Rick-Anderson** [comment]
Yes, all of those are introduction tutorials.
