### ISSUE TITLE
Service folder

### ISSUE THREAD

**Issue by dbisignani** [dotnet/AspNetCore.Docs#25145]
This tutorial explains that the confirmation email should be set up in the services folder.  However, when I started the project and added individual user accounts, the services folder was not created anywhere in the project.  I am not sure how to proceed.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@dbisignani ... It doesn't say this ...

> the confirmation email should be set up in the services folder

What line are you referring to?
