### ISSUE TITLE
Generic methods can be used to call view components

### ISSUE THREAD

**Issue by xxxxue** [dotnet/AspNetCore.Docs#25151]
I found no examples of generics in "invoking a view component"..
Generic methods can be used to call view components :
In cshtml, this bracket is required and cannot be removed
```cshtml
@using MvcBlog.ViewComponents

@(await Component.InvokeAsync<NavViewComponent>())

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by xxxxue** [comment]
I found no examples of generics in "invoking a view component"..
So I want to add a generic example

**Comment by Rick-Anderson** [comment]
@xxxxue  did you want to submit a PR with an example?
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
