### ISSUE TITLE
The Migration instructions are missing.

### ISSUE THREAD

**Issue by mitselplik** [dotnet/AspNetCore.Docs#25153]
No instructions exist to "follow the instructions to apply migrations."  If the user clicks the Register link and attempts to register in the demo app, an error occurs - presumably because whatever instructions are needed to apply migrations and create a data store are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The browser provides instructions. It's the same with any other tutorial that uses Identity.

**Comment by mitselplik** [comment]
No the browser does *not* provide instructions.  The browser provides error information when you supply an email address and password:
![image](https://user-images.githubusercontent.com/43304288/155869468-8c315457-82a0-4ef3-ad85-66ace39df4c0.png)
