### ISSUE TITLE
Issue with WSL certificate generation

### ISSUE THREAD

**Issue by FrankAtHexagon** [dotnet/AspNetCore.Docs#25164]
The [Trust HTTPS certificate from Windows Subsystem for Linux](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.0&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux-1) section indicates the following command should be run on WSL:

```
dotnet dev-certs https --clean --import /mnt/c/<<path-to-folder>>/aspnetcore.pfx -p $CREDENTIAL_PLACEHOLDER$
```

However, despite providing the correct path and `$CREDENTIAL_PLACEHOLDER$`, the following output always appears:

```
Specify --help for a list of available options and commands.
```

And the HTTPS certificate isn't trusted, resulting in errors when running using WSL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-https-certificate-from-windows-subsystem-for-linux-1)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@javiercn  we've had multiple reports of this problem. See also #24930

**Comment by Rick-Anderson** [comment]
@FrankAtHexagon  see #19141 which seems to answer this.

**Comment by FrankAtHexagon** [comment]
Thanks for your help! For the record, this didn't fix the issue I was seeing. I was only able to get the commands to succeed after upgrading to .NET SDK version 5.0.

**Comment by Rick-Anderson** [comment]
> Thanks for your help! For the record, this didn't fix the issue I was seeing. I was only able to get the commands to succeed after upgrading to .NET SDK version 5.0.

Good to here, but why not go to .NET 6 as it's LTS.

**Comment by FrankAtHexagon** [comment]
We'll consider it since you can have multiple .NET installations on a single machine, but I think you'll find that .NET Core 3.1 is still very popular with many development teams.
