### ISSUE TITLE
Missing MapControllers in tutorial

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#25163]
In program.cs I have to add:

app.MapControllers();

to get this to work.

I also have to change the connection string in appsettings.json from:

mongodb://127.0.0.1:27017
to
mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
The templates add `app.MapControllers();`
