### ISSUE TITLE
MVC Controller Cookie Auth doesn't work with AddIdentityServerJwt

### ISSUE THREAD

**Issue by jlkalberer** [dotnet/AspNetCore.Docs#25169]
I am migrating an old Asp.Net 5 site to Asp.Net core
I have many MVC controllers that I don't want to migrate to Razor Pages as there is a high probability to introduce bugs and a ton of work to do so.

I followed the example on this page and can successfully login with Asp.Net Core Identity through the scaffolded Identity Razor pages.
The API controllers (WebAPI controllers I migrated) work with a JWT using an OIDC flow (Postman)

**My issue is that when I enable the JWTs with `services.AddIdentityServerJwt()`, cookies no longer work with controllers.**
I need these controllers to work with cookies as they are MVC and not API controllers.

Is there a configuration I need to add which would enable JWTs and cookies on these controllers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
