### ISSUE TITLE
Definitive document for the ASP.Net Startup Object

### ISSUE THREAD

**Issue by jsmarsch** [dotnet/AspNetCore.Docs#25176]
Hello:  I'm looking for a definitive/complete list of all of the methods and constructor parameters (injections) that I can do with the class whose type I pass as the type parameter when I call IWebHostBuilder.UseStartup<Startup>().  I searched around for UseStartup, and I get the gist of of -- Startup is kind of a "magic" object that can contain certain methods that can be called, and can demand certain items in its constructor.  There are plenty of examples: "do it kinda like this, did you know you can do this, etc", but it would be nice to know the complete list of what you can do with the startup object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jsmarsch ... You might wish to use the API docs for that ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iwebhostbuilder?view=aspnetcore-6.0

**Comment by jsmarsch** [comment]
Thanks -- I had already read through the links Luke provided, but I didn't
see anything that directly stated what could be put into the startup
class.

Here's an example:  There's an IStartup interface, and it describes 2
methods that can go into Startup.  And somewhere (don't have a link), I
found reference to 2 different constructors that the Startup object can
support, where system objects are injected.  But then, in our own codebase,
I found a third constructor (this one just takes an IConfiguration), And
although I couldn't find any documentation stating that the Startup object
can demand the Configuration, it does work.  I figure it can't be as simple
as saying that all configured injections work, because the startup object
is instanced before ConfigureServices gets called (it defines the
ConfigureServices method).  So then, I was just looking for some info
around what is supported by the Startup object.

**Comment by guardrex** [comment]
@jsmarsch ... In that case, look directly into the reference source given that we often don't describe the framework's implementations in detail ...

https://github.com/dotnet/aspnetcore

btw ... "Startup" ... as in what happens when the app starts ... is covered in much more detail on a **_by-host_** basis in the *Generic Host* topic ...

https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host

... with more details about fundamental services in the cross-linked *Fundamentals* topic ...

https://docs.microsoft.com/aspnet/core/fundamentals/

This topic is really only trying to cover the basic application startup code.
