### ISSUE TITLE
Missing Information on WebAssembly Logging and JS Console Interop

### ISSUE THREAD

**Issue by qJake** [dotnet/AspNetCore.Docs#25172]
This page is missing information specifically around Blazor WebAssembly client-side only logging.

It mentions how to set it up, but does not mention if there are any solutions out of the box or if one **must** be written from scratch.

The documentation has this line in a code sample:

```cs
builder.Logging.AddProvider(new CustomLoggingProvider());
```

However it's not clear what `CustomLoggingProvider` is or where it comes from (is there sample code?), or if you have to write it yourself, and where that sample code can be found.

Additionally, there is no mention of whether or not it is possible to log to the browser's JavaScript console and how to achieve that. Something should be included to guide users as to the proper way to handle this, whether that is through the `ILogger` interface (if this is even possible), or whether they should use the JS Interop feature to call `console.log` or similar.

For example, if there is a way to connect `ILogger` to the browser's console, provide sample code on how that can be achieved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8795bcc-45ef-7edc-4657-fca867c8ff81
* Version Independent ID: d0b1a040-5dae-8233-dbee-c5837a0c231d
* Content: [ASP.NET Core Blazor logging](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/logging.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @qJake ...

Yes, it's at least missing a cross-link to ...

https://docs.microsoft.com/en-us/dotnet/core/extensions/custom-logging-provider

... for a custom logger, but I agree that a quick example here makes sense. I haven't personally checked that out, so I'll need to whip something up and see how it goes 🤞.

WRT logging to the console, you get that OOB by default. You can just grab an `ILogger` in a component and use it ...

```razor
@page "/log-it"
@using Microsoft.Extensions.Logging
@inject ILogger<Index> Logger

<p>
    <button @onclick="LogIt">Log IT!</button>
</p>

@code{
    private void LogIt()
    {
        Logger.LogInformation($"Something logged! {DateTime.Now}");
    }
}
```

Leave this issue open. I'll make an update to the topic to provide additional info on Wednesday morning. This issue will close automatically when the PR merges. Hopefully, the customer logger advice will work. That guidance came directly from the product unit devs who built the Blazor framework, so it should work ... *in theory* ........ **_maybe_** ...... well ..... 🎲🎲 *I'm sure that there are Vegas odds on it working!* 😆 I'll report back tomorrow.

**Comment by qJake** [comment]
Fantastic, much clearer documentation and answers a lot of questions. Thanks so much @guardrex! Can't wait for this to push to live. 🙂

**Comment by guardrex** [comment]
Cool. I should be wrapping this up on Monday. Thanks again for your issue, @qJake.
