### ISSUE TITLE
Clarification of the need for IDisposable with event handlers 

### ISSUE THREAD

**Issue by TheAtomicOption** [dotnet/AspNetCore.Docs#25185]
After the sections showing how to implement IDisposable and IDisposableAsync in components, there is a section "Event handlers" for unsubscribing event handlers from .NET events. Currently the phrasing is:

>Unsubscribe event handlers from .NET events. The following [Blazor form](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-3.1) examples show how to unsubscribe an event handler in the Dispose method:

If any use of .NET events requires implementing IDisposable, the phrasing should be made stronger by replacing the directive to unsubscribe with a statement that unsubscription is required. For example:

>A Blazor component which subscribes to .NET events must implement IDisposable or IDisposableAsync to unsubscribe from them in order to avoid leaking references. The following Blazor form examples show how to unsubscribe a .NET event handler in the Dispose method:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#detect-when-the-app-is-prerendering)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @TheAtomicOption ... I'm a bit buried at the moment ⛰️⛏️😅. I'll get back to you on this either Friday or early next week.

**Comment by guardrex** [comment]
Ok ... I'm *BACK*.

🤔 .... I think the word "always" would result in the same effect, and the section could use a cross-link to the earlier section, which cross-links to external docs on the subject. The line is already written in imperative tone, so it's a direct instruction. I'll adjust the text. Thanks for your feedback.
