### ISSUE TITLE
How to set LoggerFactoryOptions.ActivityTrackingOptions via appsettings.json?

### ISSUE THREAD

**Issue by svdHero** [dotnet/AspNetCore.Docs#25184]
[This paragraph](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#automatically-log-scope-with-spanid-traceid-parentid-baggage-and-tags) describes how to make a logger add the W3C trace context (trace id, span id, parent id, tc.) to all log messages.

Is there an easy way how I can configure this via `appsettings.json` without having to hardwire the logging configuration into my C# code?
If so, could you please add a json code snippet to the documentation? Most other paragraphs on said site contain json examples for the configuration options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Nope. See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/w3c-logger/
