### ISSUE TITLE
Missing code for LanguageFilterAttribute in "Use hub filters in ASP.NET Core SignalR" doc

### ISSUE THREAD

**Issue by vancodocton** [dotnet/AspNetCore.Docs#25207]
I've read the document about the hub filter for SignalR. I think this page is incomplete that I get errors about "LanguageFilterAttribute"
Is anyone face a situation like mine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82746d56-6a32-5ede-d6eb-2878b2246fa4
* Version Independent ID: 6a84855a-42cc-4dcd-0397-dac5d25599a1
* Content: [Use hub filters in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hub-filters?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/hub-filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hub-filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @Brecon
* Microsoft Alias: **brecon**

**Comment by serpent5** [comment]
Hi @vancodocton. The `LanguageFilterAttribute` class doesn't exist in the article. The text just states "_assume a `LanguageFilterAttribute` class is defined_", so you're not missing anything here. If you want to run the example code, you'll need to create your own `LanguageFilterAttribute` class with a `FilterArgument` property.
