### ISSUE TITLE
new edge won't let this project come up on p 80

### ISSUE THREAD

**Issue by Amondale** [dotnet/AspNetCore.Docs#25212]
Go to http://localhost:5000 in a browser to test the app. Works in Firefox, even though Firefox alerts me to http: sites as being insecure. Works in Chrome too! Tried the edge://flags/#edge-automatic-https but no slider emerged to set it on/off temporarily.

[Available for preview: Automatic HTTPS helps keep your browsing more secure](https://blogs.windows.com/msedgedev/2021/06/01/available-for-preview-automatic-https-helps-keep-your-browsing-more-secure/)

No visible setting to allow http even after setting )
Automatic HTTPS switches your connections to websites from HTTP to HTTPS on sites that are **highly likely** to support the more secure protocol. 

Guess this means http://localhost ?
The app is showing this output:
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /app/","State":{"Message":"Content root path: /app/","contentRoot":"/app/","{OriginalFormat}":"Content root path: {contentRoot}"}}
{"EventId":3,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware","Message":"Failed to determine the https port for redirect.","State":{"Message":"Failed to determine the https port for redirect.","{OriginalFormat}":"Failed to determine the https port for redirect."}}

Suggest a rewrite of this page so all browsers including Edge work with this project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Sounds like a question for the Edge preview team.
