### ISSUE TITLE
broken link to sample code in Next Action section (bottom)

### ISSUE THREAD

**Issue by menaheme** [dotnet/AspNetCore.Docs#25222]
hi

the link at the bottom of the page:

To experiment with filters, [download, test, and modify the GitHub sample](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/controllers/filters/3.1sample).

is broken (seeing 404)

i see that the docs are now at (https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/controllers/filters/samples/3.x/FiltersSample)

and the link should probably be updated to the 6.x release anyway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @menaheme,

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by menaheme** [comment]
Hi , tried that first, clicked the button , nothing happens so came here, so cannot do that. Good day

**Comment by serpent5** [comment]
Ok. I've added the metadata to this existing issue.
