### ISSUE TITLE
AddSignalR() does not exists in 6.0.2

### ISSUE THREAD

**Issue by LURKEN** [dotnet/AspNetCore.Docs#25220]
'IServiceCollection' does not contain a definition for 'AddSignalR' and no accessible extension method 'AddSignalR' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by serpent5** [comment]
Hi @LURKEN. The [sample](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/signalr/samples/SignalRChat) for this builds without issue, so I suggest you use that to see if you can see what's not quite right in your own example.
