### ISSUE TITLE
Example code need a correction

### ISSUE THREAD

**Issue by workaholic** [dotnet/AspNetCore.Docs#25231]
Example code that located in 'MainWindows.xaml' section need a correction.
This code will be error occurred when Building project, Because Counter component doesn't exists on 'WpfBlazor'.

Before)
xmlns:local="clr-namespace:WpfBlazor;assembly=ComponentLibrary"

After: Correction)
xmlns:local="clr-namespace:ComponentLibrary;assembly=ComponentLibrary"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Version Independent ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Content: [Build a Windows Presentation Foundation (WPF) Blazor app](https://docs.microsoft.com/ko-kr/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/wpf.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @workaholic.

@danroth27 ... This approach came from your sample app, and I didn't have the problem that @workaholic is reporting ...

https://github.com/danroth27/BlazorHybridWpf/blob/main/BlazorHybridWpf/MainWindow.xaml#L6

Do you want the `clr-namespace` changed?
