### ISSUE TITLE
How do you handle secrets in a Production environment?

### ISSUE THREAD

**Issue by norm-bell** [dotnet/AspNetCore.Docs#25241]
The article is very useful, but also very frustrating. While it does a good job of explaining how to safely store secrets in ASP.NET Core, it only tells you how to do this when you're in a Development environment. It doesn't tell you how to do this when in a Production environment. This knowledge would be of significant higher value and utility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @norm-bell. Thanks for taking the time to provide feedback.

There's another article that sits alongside this one, [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0), which describes how to use Azure Key Vault to store secrets for Production environments.
