### ISSUE TITLE
Configure service does not work

### ISSUE THREAD

**Issue by dougfunk01** [dotnet/AspNetCore.Docs#25242]
I can never get any of the examples to work because they contain either core 1, 2, 3.1, or 5 code.

builder.Services.AddDefaultIdentity<IdentityUser>() does not exist in .net core 6. Really frustrating trying to migrate from the .net framework 4.7+ world

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @dougfunk01. Thanks for taking the time to provide feedback.

The `AddDefaultIdentity` method lives in the [Microsoft.AspNetCore.Identity.UI](https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.UI) NuGet package, so you'll need to add a reference to that if you haven't already.
