### ISSUE TITLE
How to set the Order property when using MapMethods ?

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#25254]
**Environment**
Microsoft Visual Studio Community 2022
Version 17.1.1
VisualStudio.17.Release/17.1.1+32228.430
Microsoft .NET Framework
Version 4.8.04084

Can an example be shown on how to set the Order when using a method such as MapMethods()?  For example:

```
// route_pattern is a String
// allowed_http_method_list is a list of strings (HTTP verbs, i.e.: "GET", "POST", etc.)
// route_handler is the RequestDelegate.
// order is an Int32 that contains the order (priority) number.

// Add the endpoint using a convention to update the Order ...

endpoints.MapMethods( route_pattern, allowed_http_method_list, route_handler ).Add( builder => ( ( RouteEndpointBuilder )builder ).Order = order );
```

The above works, but I would like to know if this is deemed the "correct" way to set the Order property when using the MapMethods() method.

I would like to see an example of the Order property being set using a variable as shown above, rather than just "hardcoded", i.e.: 

`endpoints.MapMethods( route_pattern, allowed_http_method_list, route_handler ).Add( builder => ( ( RouteEndpointBuilder )builder ).Order = 2 );`

... as my use case does not "hard-code" the Order, it is set at runtime via an attribute.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@halter73  please review.

**Comment by halter73** [comment]
Generally there should only be at most one endpoint that matches any given request. `RouteEndpointBuilder.Order` exists to support legacy MVC scenarios as far as I know.  I've also written code like `builder => (( RouteEndpointBuilder)builder).Order = order` before, so I understand the temptation. I don't think there's a better way to do this, but this is a fairly advanced scenario that I doubt we'll encourage by documenting or trying to make any easier.

@davidfowl Do you have any thoughts here?

**Comment by bdcoder2** [comment]
@halter73 - Thank-you for taking the time to check.  I just wanted to support order for route patterns in a [routemap pages](https://github.com/bdcoder2/rmp) project I was experimenting with.   Seems to work well.

Thanks again.
