### ISSUE TITLE
Add information that certificate subject is a part of the subject and not a full subject

### ISSUE THREAD

**Issue by dcarapic** [dotnet/AspNetCore.Docs#25255]
Recently I was trying to configure the SSL certificate via appsettings.json and it simply did not work (see [https://stackoverflow.com/questions/71381744/asp-net-core-3-1-re-using-iis-certificate-in-self-hosted-kestrel-application](https://stackoverflow.com/questions/71381744/asp-net-core-3-1-re-using-iis-certificate-in-self-hosted-kestrel-application)).  
In essence my issue was that supplying the full certificate subject was not working. I needed to supply just one part of the subject for the certificate to be used. 
I think docs should maybe include that somewhere to avoid this gotcha.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dcarapic can you post the complete *appsettings.json* that worked?

@halter73 who's the right person to review this. Also, in this doc, under [Client Certificates
](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#client-certificates), we have the following JSON which violates are security requirements not to hard code passwords in source code:

```JSON
{
  "Kestrel": {
    "Endpoints": {
      "MyHttpsEndpoint": {
        "Url": "https://localhost:5001",
        "ClientCertificateMode": "AllowCertificate",
        "Certificate": {
          "Path": "<path to .pfx file>",
          "Password": "$CREDENTIAL_PLACEHOLDER$"
        }
      }
    }
  }
}
```

How do we move `"Password": "$CREDENTIAL_PLACEHOLDER$"` to secret manager?

cc @serpent5

**Comment by dcarapic** [comment]
@Rick-Anderson 
Sure, 
Here is an example certificate that I would like to use):
![image](https://user-images.githubusercontent.com/5895972/157621447-f4b904be-08eb-4ccd-8ad0-ab948c5d5ede.png)

here is my first appsettings.json (which did not work):

````
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://*:5000"
      },
      "Https": {
        "Url": "https://*:5001"
      }
    },
    "Certificates": {
      "Default": {
        "Subject": "CN = localhost",
        "Store": "My",
        "Location": "LocalMachine"
      }
    }
  }
}
````

This one works (I've just changed the certificate subject string):


````
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Kestrel": {
    "EndPoints": {
      "Http": {
        "Url": "http://*:5000"
      },
      "Https": {
        "Url": "https://*:5001"
      }
    },
    "Certificates": {
      "Default": {
        "Subject": "localhost",
        "Store": "My",
        "Location": "LocalMachine"
      }
    }
  }
}
````

**Comment by halter73** [comment]
> How do we move "Password": "$CREDENTIAL_PLACEHOLDER$" to secret manager?

I imagine `dotnet user-secrets set "Kestrel:Endpoints:MyHttpsEndpoint:Certificate:Password" "$CREDENTIAL_PLACEHOLDER$"` would do the trick.

@wfurt might be a good resource for cert requirements.

**Comment by Rick-Anderson** [comment]
@wfurt  can you also comment on 
>  I needed to supply just one part of the subject for the certificate to be used.

**Comment by wfurt** [comment]
I'm not sure I fully understand the conversation. To me, there are two independent parts: 1) how do you select the right certificate and 2) how do you maintain password (if needed) for the private key. 

Depending how the certificates are managed, one can use thumbprint. Using name, may be OK but I've seen cases when some other software also creates "localhost" and you end up with ambiguity and surprise. 

For the secret, I would expect you can set permissions so the app does not need secret e.g. avoid loading from file.

**Comment by Rick-Anderson** [comment]
@wfurt  sorry I hijacked the question with a new one, how do we get rid of  ` "Password": "$CREDENTIAL_PLACEHOLDER$"`.

> For the secret, I would expect you can set permissions so the app does not need secret e.g. avoid loading from file.

OK, I'll remove the following line from *appsettings.json*:
`"Password": "$CREDENTIAL_PLACEHOLDER$"`

@dcarapic  wants us to update the doc to say ` "Subject": "CN = localhost"` is not how you specify the `Certificates\Default\Subject`, it's `"Subject": "localhost"`

Should I add that with his image as an example in this doc?

**Comment by serpent5** [comment]
It doesn't appear to be possible to use a thumbprint with Kestrel and `IConfiguration`: https://github.com/dotnet/aspnetcore/issues/4385. The [CertificateConfig](https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Servers/Kestrel/Core/src/Internal/ConfigurationReader.cs#L356) class shows what exactly can be read from configuration.

**Comment by wfurt** [comment]
That may be good suggestion for improvements.
