### ISSUE TITLE
Can not call js class static methods inside OnAfterRender

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#25265]
**Regarding this heading: Pass a DotNetObjectReference to a class with multiple JavaScript functions**
I am using Blazor Web Assembly with dotnet 6.0.201. Altough I get the error with one of this page sample (`Pages/CallDotNetExampleOneHelper.razor`) but it seems related to JS interop as whole and not restericted to passing `DotNetObjectReference` to js.
According to example `CallDotNetExampleOneHelper`. I defined a `JS class `with multiple **static** methods and I want to call one of its static method inside `OnAfterRenderAsync`. I call it conditionally at first render and I get the following error:
` Microsoft.JSInterop.JSException: Could not find 'CallDotNetExampleOneHelper.setDotNetHelper' ('CallDotNetExampleOneHelper' was undefined).`

The js class defined in head of html layout.cshtml/index.html as below:

```
<script>
  class GreetingHelpers {
    static dotNetHelper;

    static setDotNetHelper(value) {
      GreetingHelpers.dotNetHelper = value;
    }

    static async sayHello() {
      const msg = 
        await GreetingHelpers.dotNetHelper.invokeMethodAsync('GetHelloMessage');
      alert(`Message from .NET: "${msg}"`);
    }

    static async welcomeVisitor() {
      const msg = 
        await GreetingHelpers.dotNetHelper.invokeMethodAsync('GetWelcomeMessage');
      alert(`Message from .NET: "${msg}"`);
    }
  }
</script>
```
And it called as below:
```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            dotNetHelper = DotNetObjectReference.Create(this);
            await JS.InvokeVoidAsync("GreetingHelpers.setDotNetHelper", 
                dotNetHelper);
        }
    }

```

I also reported this issue to ASP.NET Core repository too since it seems related to JS Interop.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#pass-a-dotnetobjectreference-to-a-class-with-multiple-javascript-functions)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @abdollahkahne ... Sounds like you placed the JS in the wrong spot. Per the doc, try .........

> Inside the closing tag of wwwroot/index.html (Blazor WebAssembly)

**Comment by guardrex** [comment]
LOL 🙈 ... I did just notice a *NIT* there. It should be inside the closing `</body>` tag. I'll patch that up right now.

**Comment by guardrex** [comment]
Ok ... that got it.

Anyway ... yeah ... it's not recommended for the `<head>`. Try it from just inside the `</body>` tag.

For more info, see the remarks at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0#load-a-script-in-head-markup

**Comment by guardrex** [comment]
Ok, thanks. I knew that there was a problem with `<head>` as the engineers called out. I'll keep an 👁️ on your engineering issue in case we need docs. I'll re-open this if we need to do work over here.

**Comment by guardrex** [comment]
Ok ... that explains it. Steve did **_NOT_** mention that **_important_** bit when we discussed this coverage. I'll put in an update to the doc right now.
