### ISSUE TITLE
Clarity in documentation of class / methods regarding logging configuration settings ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/AspNetCore.Docs#25267]
For those of us that are completely new to .Net / logging ...

Can a link to this excellent resource: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#dnrvs)  please be added to the following page:

[ConsoleLoggerExtensions Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.consoleloggerextensions?view=dotnet-plat-ext-6.0)

The above page **makes no mention of how** the Console logger is configured by default.  For newbies such as myself, having the first link above added to the ConsoleLoggerExtensions Class page would have made life SO much easier!   Instead (again, remember, for those of us that are complete newbies), I could have saved several hours had the link to the fundamentals been included.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#how-filtering-rules-are-applied)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sorry, @bdcoder2 ... We can't do it. The API docs are automatically generated.

**Comment by bdcoder2** [comment]
Understood.

Perhaps it may be time to rethink how the documentation is written / generated?   Would it not be possible to generate (via an automated process) a MERGE of the API docs with such relevant "background" info as in the above example?

Anyone old enough to remember the DEC VAX/VMS documentation set? -- that was a gold standard. :)

Thanks again ( @guardrex / @Rick-Anderson ) for your replies!

**Comment by Rick-Anderson** [comment]
> Anyone old enough to remember the DEC VAX/VMS documentation set? -- that was a gold standard. :)


Yup, it was pretty good but not as extensive as all of docs.microsoft.com

**Comment by bdcoder2** [comment]
... @Rick-Anderson - Yes, about 17 3-inch binders! (I still have the doc set on CD).   Every API had its own binder and everything was in **one location** (the relevant binder) -- that (documentation) paradigm made learning an API so much easier.    Don't get me wrong -- docs.microsoft.com is getting better with each version.  For those of us that jump into an framework / API cold -- for example, by looking up a class, its methods and properties, we expect to find everything in that one location, not in 10 or 20 different locations.   I am sure once I get my hands a little dirtier, it will start to come together;  however, I can certainly see why so many people struggle with .Net from the get-go.
