### ISSUE TITLE
Missing example on how to use TestServer with ASP.NET 6

### ISSUE THREAD

**Issue by benm-eras** [dotnet/AspNetCore.Docs#25263]
The section titled [Test with WebApplicationFactory or TestServer](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#test-with-webapplicationfactory-or-testserver) only includes an example of how to use the `WebApplicationFactory` with .NET 6. Is the `TestServer` still available in .NET 6? If so, is it possible to use it with Blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated to the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@benm-eras ... The Blazor (Razor component) test guidance is located in the Blazor node at ...

https://docs.microsoft.com/aspnet/core/blazor/test

AFAICT, there has been work on `TestServer` for Blazor testing scenarios since that topic went up. The testing guidance was put up ~18 months ago. This is a good time to ask if it's all still valid and good in it's present form or if it will need work. I'll ping Artak offline to see where things stand.

**Comment by guardrex** [comment]
Yes, I'm trying to jog my memory on this subject after 18 months. No issues on this subject have been opened since then IIRC.

Now that you mention it, yes ... I just looked 👀 ... I see/recall now that Playwright is just for the browser automation aspect. 

`TestServer` has had work when problems were reported to the product unit. I see the issues/PRs in their repo.

> an example of how to use the WebApplicationFactory with .NET 6

There's a line at the end tho that says ...

> The .NET 5 version and .NET 6 version with the `WebApplicationFactory` are identical by design.

Does that cover your ask here?

**Comment by benm-eras** [comment]
I am looking to use the ["TestServer"](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#with-testserver) method and the resulting `IHost`, not so much the [`WebApplicationFactory`](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#with-webapplicationfactory) which will give you an `HttpClient`. This is because I need to have the application available at a given URL/Port to point Playwright at. 

I see no mention of `TestServer` or creating an `IHost` in the .NET 6 section of the page. As I say my existing .NET 5 code seems to work:

```
var host = Microsoft.Extensions.Hosting.Host
    .CreateDefaultBuilder()
    .UseEnvironment(this.Environment)
    .ConfigureAppConfiguration(b => {  /* do app config */ })
    .ConfigureWebHostDefaults(b=> b.UseUrls(myUrl).UseStartup<MyStartup>())
    .ConfigureServices((b,s) => { /* add stuff to DI container */ })
    .Build();

await host.StartAsync();
```

I can then point Playwright (or my browser) to `myUrl` and I am good to go. So if you tell me that the .NET 6 version of this is identical to .NET 5 I will be a happy camper, though I feel that last sentence needs amending to explicitly mention `TestServer`/`IHost`?

**Comment by benm-eras** [comment]
Ah I see, I still don't think that is very clear as I don't think I would be able to use the `WebApplicationFactory<TEntryPoint>` to do integration testing with Playwright (or similar) unless I am missing something? Where they link to "[Test with WebApplicationFactory or TestServer]"(https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#twa) there is no advice on TestServer for .NET 6. 

Everything is working as I would expect, but I just think the Docs need some more information on .NET 6 and TestServer. Thanks for your time regardless.

**Comment by guardrex** [comment]
Yeah ... Rick will be along in a bit to see if a line (and/or example) makes sense. What I'm going to do is make a note on a tracking issue that I use for Blazor docs to provide guidance about the `TestServer` setup for Playwright (probably including the non-`TestServer` Blazor WASM case) or cross-link to anything helpful on it in Playwright docs (although I doubt that they say anything really about this aspect). We should have working example(s) in the Blazor topic anyway, regardless of what's done with the migration coverage.

**Comment by Rick-Anderson** [comment]
This will be covered in #27089
