### ISSUE TITLE
HTTPS page does not speak about selecting TLS certificate

### ISSUE THREAD

**Issue by sandersaares** [dotnet/AspNetCore.Docs#25272]
This page is all about HTTPS but somehow does not describe how I can associate my TLS certificates with my endpoints. I also cannot find any such page in the ToC for "Hosting" chapter. I ran out of places to look. There is no obvious page that tells me how I can choose a TLS certificate to use. I was expecting this page to tell me, or at least link me somewhere useful.

There is a link for how to do it with IIS but IIS is just one of many ways to host, and I am not using IIS but Kestrel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @sandersaares. The [Configure endpoints for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0) article explains how to configure endpoints used in Kestrel, including how to apply certificates using configuration and code.
