### ISSUE TITLE
Outdated content on Tutorial: Create a web API with ASP.NET Core page

### ISSUE THREAD

**Issue by kev1010** [dotnet/AspNetCore.Docs#25282]
The section, "Update the launchUrl" instructs to adjust the browser startup page using `launchURL`; however, the template no longer uses `launchURL `and uses `serverReadyAction` instead. Refer to the section "Starting a Web Browser" in [this blog post] (https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#starting-a-web-browser) for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @kev1010 ,

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by kev1010** [comment]
Hello Kirk, I did use the link.

**Comment by serpent5** [comment]
The instructions show that you need to update `Properties\launchSettings.json` and _not_ `.vscode/launch.json`. `launchSettings.json` is used by `dotnet run` and Visual Studio.
