### ISSUE TITLE
Please document where IFormFile buffering will place the temporary files

### ISSUE THREAD

**Issue by fschmied** [dotnet/AspNetCore.Docs#25290]
Under _File upload scenarios/Buffering_, there is no information on where ASP.NET Core will place the corresponding temporary files. This is important if this folder needs to be moved to a different disk (e.g., a faster disk or a larger disk) or needs to be exempt from a realtime malware scanner.

Looking at the code of the `AspNetCoreTempDirectory` class, the temporary file location seems to be governed by the `ASPNETCORE_TEMP` environment variable; if it's not set, it's the result of `Path.GetTempPath()`. This is variable is indeed documented in the [EnableBuffering](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequestrewindextensions.enablebuffering?view=aspnetcore-6.0#microsoft-aspnetcore-http-httprequestrewindextensions-enablebuffering(microsoft-aspnetcore-http-httprequest)) docs, but to me, it wasn't clear at all that this also applies to the buffering performed by `IFormFile` model binding.

This has also confused other people in the past, e.g., see https://github.com/dotnet/aspnetcore/issues/3704.

Please add the information to this docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0#file-upload-scenarios)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fschmied can you give me a link to the source for `AspNetCoreTempDirectory` class?

**Comment by fschmied** [comment]
@Rick-Anderson Sure: https://github.com/dotnet/aspnetcore/blob/2b4a186c29667003d06bef8d629f5d3266b5804a/src/Http/WebUtilities/src/AspNetCoreTempDirectory.cs .

**Comment by fschmied** [comment]
And here's how that class is involved with multipart/form-data:
* https://github.com/dotnet/aspnetcore/blob/2b4a186c29667003d06bef8d629f5d3266b5804a/src/Http/Http/src/Features/FormFeature.cs#L205
* https://github.com/dotnet/aspnetcore/blob/2b4a186c29667003d06bef8d629f5d3266b5804a/src/Http/Http/src/Internal/BufferingHelper.cs#L45
