### ISSUE TITLE
Cannot execute these instruction

### ISSUE THREAD

**Issue by TriOpTech** [dotnet/AspNetCore.Docs#25320]
As of the day of this writing, Visual Studio 2022 does not have the ability to scaffold items.  With a base project created, you CANNOT, I say again, you CANNOT scaffold items as you get a "Error There are no scaffolders supported for this item" when attempting to scaffold.

These instructions are invalid until this issue is fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
To report Visual Studio problems
**Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)
