### ISSUE TITLE
Prerequisites NET Core 3.0 but Can't do it in ASP.NET Core 5.0

### ISSUE THREAD

**Issue by SimonLeesk** [dotnet/AspNetCore.Docs#25338]
https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio

While following codes in "Configure startup to support email", 
I found "WebApplication.CreateBuilder()"(in line 7) can be used only in NET CORE 6.0. 

I tried ASP.NET Core 3.1, but the same codes are shown. So I cannot use the codes. 
Please show me available codes for ASP.NET Core 5.0 and 3.1.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/accconfirm?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Run `dotnet --list-sdks`
If it's generating .NET 6 code,  you have the .NET 6 SDK installed. 

Use https://docs.microsoft.com/en-us/dotnet/core/tools/global-json to control the version used
