### ISSUE TITLE
Use of AddLocalization() without options

### ISSUE THREAD

**Issue by gsig91** [dotnet/AspNetCore.Docs#25345]
Greetings,

My question is, what if we do not use options when initializing our services? meaning:

Using
```
services.AddLocalization();
```
instead of the proposed
```
services.AddLocalization(options => options.ResourcesPath = "Resources");
```

At what path should the resources be placed if we use the ```services.AddLocalization();```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfc7f38-7c0f-cc95-92c4-e99e0ad1812e
* Version Independent ID: 9a1dccda-d7bf-1eb5-e5e3-8aba4aeb444f
* Content: [Troubleshoot ASP.NET Core Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/troubleshoot-aspnet-core-localization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/troubleshoot-aspnet-core-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @hishamco
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
It should be `Empty`, so try to place the resources on the app root
