### ISSUE TITLE
.NET 6: Publish an ASP.NET Core web API to Azure API Management with VS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25341]
Replace "At this point, you need to add an API to the Azure API Management service. Leave Visual Studio open while you complete the following tasks." creating the API in the current dialog. It now support that.

Remove all the pic's. The pic's are so big they're not helpful anyway and change too often.

Copy/paste the beginning instructions from https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api
have them  Delete `[Route("[controller]")] ` and add `[Route("/")]`

In the instructions
Replace `services.AddSwaggerGen();` with
```
services.AddSwaggerGen(config =>
{
    config.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "WeatherForecasts",
        Version = "v1"
    });
});
```
.NET 3.2 and 5.0 both generated the replacement code, not so in .NET 6

> Notice the name of the API is different than what you named it
I don't think that's true when you create it from the pub profle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by Rick-Anderson** [comment]
@codemillmatt are you the right cloud advocate to review this issue? Can you outline what changes you'd like to see to this? It's total cook book now and doesn't explain what's going on or what would be useful.

**Comment by codemillmatt** [comment]
@rick-anderson yes - I'll take a look at it.

**Comment by codemillmatt** [comment]
@Rick-Anderson - I'll take care of the changes here. It'll probably take me into the week of March 28 to get to them & finish them. That cool?

**Comment by Rick-Anderson** [comment]
@codemillmatt can you schedule this PR?
