### ISSUE TITLE
CultureSelector.razor smaller alternative

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#25347]
[EDIT by guardrex to provide complete code for the property and that matches the doc's current example naming.]

on `CultureSelector.razor` we could remove the need for a controller by using this code on `Culture` `set`

```csharp
@inject IJSRuntime JS

...

private CultureInfo Culture
{
    get => CultureInfo.CurrentCulture;
    set
    {
        if (value is null || value == Culture)
        {
            return;
        }

        var str = CookieRequestCultureProvider.DefaultCookieName + "="
           + CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(value));

        await JS.InvokeVoidAsync("eval", $"document.cookie = \"{str}\"");

        Nav.NavigateTo(Nav.Uri, forceLoad: true);
    }
}
```

(`await` used because I used onchange instead of bind)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=server)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Let's ask @hishamco what he thinks about that.

**Comment by omuleanu** [comment]
@guardrex you could avoid eval if you want, but you'll have to create a small js function that will set `document.cookie` and call it instead

**Comment by guardrex** [comment]
I have a feeling that you're going to have to re-pitch the whole idea on the JS interop basis because I think that `eval` like this on the basis of client data is going to be flatly rejected by the PU. Perhaps, you should close this issue and make a new issue with the complete updated approach using JS interop, then we can ping Hisham to look at that approach.

**Comment by omuleanu** [comment]
@guardrex what is PU ?

**Comment by guardrex** [comment]
"product unit" ... Steve, Javier, Tanay, etc. ... The ones who actually know how to write real software ... not 🦖  **_Dinohacks_**&trade; 😆.

**Comment by hishamco** [comment]
Seems I came late ;), I'm not sure why you are using `await JS.InvokeVoidAsync("eval", $"document.cookie = \"{str}\"");` which is something scary

Please let me know are using Server-Side Blazor or WebAssembly, coz things different here

**Comment by guardrex** [comment]
@hishamco ... I don't think we want to make changes to what the doc shows. If devs want to take a different approach (e.g., @omuleanu's JS concept) to avoid the controller/round-trip, that's fine, but I think they'd just do that on their own. Do you disagree? Do you prefer for the doc's example to change? I'm 🏃⛰️⛏️😅 as usual and we're very busy with high priority issues; so if this can be taken as an optional case for devs to implement on their own if they want it, then I'd prefer to close this and stick with what we have.

**Comment by hishamco** [comment]
@guardrex I'm not suggesting to change the docs, AFAIK our docs already have a sample. The questions are:

-  What's the wrong with what we have?
- What are the advantages for the suggested approach over settings the culture from `Program.cs`?

**Comment by guardrex** [comment]
I'm saying that you're suggesting it. @omuleanu is suggesting the change. I'm asking the same questions.

1. Nothing if the round-trip perf isn't a problem. *I don't think it's a big deal.*
2. It isn't about setting the culture from `Program.cs`. It's about avoiding the round-trip to the controller to set the cookie. It's to avoid this ...

   ```csharp
   [Route("[controller]/[action]")]
   public class CultureController : Controller
   {
       public IActionResult Set(string culture, string redirectUri)
       {
           if (culture != null)
           {
               HttpContext.Response.Cookies.Append(
                   CookieRequestCultureProvider.DefaultCookieName,
                   CookieRequestCultureProvider.MakeCookieValue(
                       new RequestCulture(culture, culture)));
           }

           return LocalRedirect(redirectUri);
       }
   }
   ```

**Comment by hishamco** [comment]
As I mentioned earlier if it's in Server-Side Blazor you can set the culture with the available stragtegies, either in PageModel, MVC Controller. In Blazor WebAssembly this could be done in `Program.cs` itself

I don't think there's an issue here, he could use his technique in custom implementation, taking the JavaScript risk in his mind

**Comment by hishamco** [comment]
As usual @guardrex os fast to open , so fast to close ;)
