### ISSUE TITLE
Possible incorrect statment.

### ISSUE THREAD

**Issue by JamesKiddSmyth** [dotnet/AspNetCore.Docs#25376]
In the section "HttpContext.Items", this sentence doesn't seem right ... "For middleware that's only used in a single app, fixed string keys are acceptable. Middleware shared between apps should use unique object keys to avoid key collisions." It seems to me that any middleware needs to use a unique key so that it won't conflict with any other middleware in the same app. What does some other app have to do with collision around this object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-6.0#httpcontextitems)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The difference is ***object***, should use unique object keys to avoid key collisions

I think unique threw you off. Perhaps unique should be dropped as object keys are unique.
cc @serpent5

**Comment by Rick-Anderson** [comment]
@JamesKiddSmyth thanks for reporting this. The update will be live soon.
