### ISSUE TITLE
For implicit grant, you do want to check box for Access tokens and ID tokens

### ISSUE THREAD

**Issue by purplemon** [dotnet/AspNetCore.Docs#25386]
I think this statement below is erroneous, you do want those boxes checked for implicit flow. It is stated correctly in the MSAL.js 2.0 section in [this other doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow) which doesn't use the implicit flow and says not to check the boxes since they are for implicit flow only.

> 2. For **Implicit grant**, ensure that the checkboxes for Access tokens and ID tokens are **not** selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3039ff79-ee86-20b1-0082-d3899a84c823
* Version Independent ID: af4a3a75-ae52-5f6d-2120-737bc2fefb07
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @purplemon ... Implicit flow isn't supported for the current release. The statement is **correct**: Don't select the checkboxes.
