### ISSUE TITLE
"isCompleted":false

### ISSUE THREAD

**Issue by ehsung2019** [dotnet/AspNetCore.Docs#25395]
[When I input httprepl https://localhost:7005/api/todoitems
post -h Content-Type=application/json -c "{"name":"walk dog","isComplete":true}" on powershell, it shows "isCompleted": false not "isCompleted": true like tutorial. Can you please tell me why?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @ehsung2019. It looks like you may be using `isComplete` in your JSON but `isCompleted` in the `TodoItem` class. Double-check that you use `isComplete` in both.
