### ISSUE TITLE
Error: Database cannot be created

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#25409]
At the end of this tutorial page I kept getting a database cannot be created error.
So I commented out DbInitialize in program.cs.
It started up without errors in the console.
But the students and instructors pages still do not work.
They return 500 errors.
Debugger does not throw an exception anywhere.
Just comes back as 500.

I cut and pasted the migration UP method directly.  No typing.
The database looked good.  Student data seemed to transfer over to Person table ok.

So I went to download the completed app for this section so I could move on to the last topic.
But the link to get the code just goes to a source control page in GIT.  Not a downloadable page for the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @smiller7812. Thanks for taking the time to provide feedback.

> Debugger does not throw an exception anywhere.

You can enable all CLR exceptions to pause the debugger in Visual Studio under *Exception Settings*:

![image](https://user-images.githubusercontent.com/6025110/159931652-46f70c83-52d0-4e94-afd4-626c4dd2d910.png)

Click the checkbox for *Common Language Runtime Exceptions* **twice** and it'll change to a tick. Once that's done, all exceptions will pause the debugger.

> But the link to get the code just goes to a source control page in GIT. Not a downloadable page for the app.

To run a sample app, you'll need to download the `AspNetCore.Docs` repo, as described [here](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-6.0#how-to-download-a-sample).

**Comment by serpent5** [comment]
Great, thanks for the extra information. There are a few known issues in this article that are being tracked in #17465. I'll close this as I believe addressing the existing issue will cover it.
