### ISSUE TITLE
Manually published app fails to run in container

### ISSUE THREAD

**Issue by asos-markkidd** [dotnet/AspNetCore.Docs#25426]
After carrying out the instructions to create the Dockerfile in the section  _"To use the manually published app within a Docker container,"_  I can see the image using `docker images` but when I try to run it I get the following:

`~/dotnet-docker/samples/aspnetapp/aspnetapp$  docker run -it --rm --name myaspnetapp_ex myaspnetapp`
```
Cannot use file stream for [/app/aspnetapp.deps.json]: No such file or directory
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/app/aspnetapp.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/app/aspnetapp.runtimeconfig.json' file and specify the appropriate framework.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to #27141
