### ISSUE TITLE
Get project to run on Ubuntu/SQLite?

### ISSUE THREAD

**Issue by Amondale** [dotnet/AspNetCore.Docs#25428]
Is there a GH repo where I can load the completed Razor/EF sample (ContosoUniversity) and run it successfully under Ubuntu or WSL2? Or does everything break when I replace SQLLocalDB with SQLite? Or might there already be a SQLLocalDB for Linux?

**Comment by guardrex** [comment]
Hello @Amondale ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
