### ISSUE TITLE
Very poor documentation. If i said what I really think I'd probably get banned, this is not documentation

### ISSUE THREAD

**Issue by AndyF1ynn22** [dotnet/AspNetCore.Docs#25443]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-3.1)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @AndyF1ynn22 ... There's no built-in bundling and minification tooling for the framework. Therefore, there's nothing much to document. Devs are welcome to use any of dozens of products and services for it, but MS doesn't pick a winner by recommending any specific tool. It's up to you to research and determine what's best for your workflow and feature spec.

If you're using Mad's bits&trade; ... the "BundlerMinifier" that he maintains ... see the docs available (the README at least) via his repo at ...

https://github.com/madskristensen/BundlerMinifier

**Comment by guardrex** [comment]
... and take a look at ...

https://github.com/dotnet/aspnetcore/issues/3023

The PU is thinking it over, and there might be a direction ... a future plan ... for it described there.
