### ISSUE TITLE
Out of date tooling warning needed

### ISSUE THREAD

**Issue by cesoftware** [dotnet/AspNetCore.Docs#25444]
When going through the tutorial, at the section where I manually enter commands through the NuGet console, there is a warning about tooling being earlier than the current version of EF (6.0.2 to 6.0.3). The page just needs a warning to update the tooling before attempting to run the commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's likely a transient error that will be corrected soon.
