### ISSUE TITLE
Add a section about the interaction during development for Static Web Assets and static files middleware

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#25446]
In the context of serving files from a separate folder, it is important to note that when the app uses static web assets (which is enabled by default). The assets are discovered at build time and served during development based on the locations they were discovered at.

When updating the convention to serve files from a folder different than the wwwroot folder by updating the `IWebHostEnvironment.WebRootPath` it is important to also update the static web assets configuration to reflect this fact, as otherwise, the assets inside the wwwroot folder will still be considered and served during development.

To update the configuration you can do it in one of two ways:
* Completely disable static web assets (which will prevent content from Razor Class Libraries from being taken into account) by setting up `<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>` in your project file.
* Remove the files inside the wwwroot folder from the list of implicit content items `<Content Remove="wwwroot\**" />` so that they don't get considered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@space-alien see https://github.com/Rick-Anderson/WebRoot

> Remove the files inside the wwwroot folder from the list of implicit content items `<Content Remove="wwwroot\**" />` so that they don't get considered.

See https://github.com/Rick-Anderson/WebRoot/blob/main/WebRoot.csproj#L10
That hides ***wwwroot*** from project manager in VS, but in dev mode, still serves files from ***wwwroot*** 

It seems easier to just set `ASPNETCORE_ENVIRONMENT` to anything other than `Development` in ***Properties\launchSettings.json***

You can also set **WebApplicationOptions.EnvironmentName** to anything other than `Development` 
see https://github.com/Rick-Anderson/WebRoot/blob/main/Program.cs#L5
