### ISSUE TITLE
SignalRBackgroundServiceSample6 incorrect setting in Server/launchsettings.json

### ISSUE THREAD

**Issue by cssmonauts** [dotnet/AspNetCore.Docs#25445]
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/signalr/background-service/samples/6.0

The two Console applications are listening on port 5001 as per HubServiceInterface/Strings.cs

`public static string HubUrl => "https://localhost:5001/hubs/clock";`

However, the Server applicationUrl setting in Server/Properties/launchSettings is not set to 5001:

`"applicationUrl": "https://localhost:62552;http://localhost:62553"`

Therefore the console applications are unable to connect to the SignalR Hub.

**Comment by serpent5** [comment]
Hi @cssmonauts,

Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by cssmonauts** [comment]
awesome.
