### ISSUE TITLE
Change example code to .NET 6 style

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/AspNetCore.Docs#25440]
Cross-link: #25437

Update the article to use .NET 6 code style.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebdbdab0-c474-3fdd-76aa-ade905e76079
* Version Independent ID: 761ea2cc-7e05-4ae0-0875-44061a163621
* Content: [Multi-factor authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/mfa.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/mfa.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @vanillajonathan.

@damienbod ... If you check @vanillajonathan's (closed) PR at https://github.com/dotnet/AspNetCore.Docs/pull/25437, you'll see the code changes and my remarks on the versioning. If you don't want to take this on, it would only take me a few minutes to knock it out, so let me know either way 👂.

**Comment by damienbod** [comment]
I can do this sometime next week, greetings Damien
