### ISSUE TITLE
BindNever can only be applied to model properties, not method parameters.

### ISSUE THREAD

**Issue by tniemenmaa** [dotnet/AspNetCore.Docs#25448]
Is this correct? 

```
[BindNever] attribute
Can only be applied to model properties, not to method parameters. Prevents model binding from setting a model's property. 
```

Adding this to controller actions parameter seems to always cause the parameter to be null even if the data is provided and the AttributeUsage targets for it do not seem to reflect this behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tniemenmaa  I just tested it on a parameter and it had no impact. 

Can you post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem? If so, I'll reopen and investigate.

**Comment by tniemenmaa** [comment]
Here is the sample
https://github.com/tniemenmaa/bindneversample

**Comment by fiyazbinhasan** [comment]
The behavior is correct for this. As mentioned it has no effect when applied on the method parameter level. In your scenario, it should be applied on a property of the `SimpleModel`,

```
public class SampleModel {
    [BindNever]
    public string Name { get; set; }
    public int Value { get; set; }
}
```

**Comment by tniemenmaa** [comment]
@fiyazbinhasan
> As mentioned it has no effect when applied on the method parameter level.
Yes that is what your documentation states, but if you look at the sample I provided it shows that adding it to method parameter level has effect of not binding the value. Or are you getting different behavior running it?

**Comment by fiyazbinhasan** [comment]
@tniemenmaa I was tinkering around with the `BindNever` attribute a bit. I guess the information in the documentation is a bit misleading when it says "can **_only_**". The XML comment describes it more appropriately,

>  Indicates that a property should be excluded from model binding. When applied to a property, the model binding
    system excludes that property. When applied to a type, the model binding system excludes all properties that
    type defines.

@Rick-Anderson should we take any action on this? Maybe changing the definition in the doc with the above?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson should we take any action on this? Maybe changing the definition in the doc with the above?

Yes, please
