### ISSUE TITLE
Blazor JS interop with generic methods

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25450]
**UPDATE (3/31)**: Ok ... done with the first draft at https://github.com/dotnet/AspNetCore.Docs/pull/25465. It's ready for review.

**UPDATE (3/30)**: The PR is up now at https://github.com/dotnet/AspNetCore.Docs/pull/25465, but it's very 🚧 **_WIP_** 🚧 at the moment and not ready for review.

@TanayParikh ... Let's take a look at this one on generics, as we don't currently carry coverage on it. I think I can get the PR in without further review if this looks good or if we can iron out any rough spots here on the issue.

Exploring an entry on the [UE tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/24615) for possible coverage:

> The *Call .NET from JS* topic mentions but doesn't show an example of calling a generic class method ... include one? Cross-ref: [`InteropComponent.razor`](https://github.com/dotnet/AspNetCore/blob/main/src/Components/test/testassets/BasicTestApp/InteropComponent.razor), [`jsinteroptests.js`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/wwwroot/js/jsinteroptests.js), and [`GenericType<TValue>`](https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/InteropTest/JavaScriptInterop.cs#L507)

The `BasicTestApp` approach seems overly engineered for a basic explanation and example. The following might work.

❓ and remarks on the following draft code ...

1. Can we say that synchronous .NET calls will execute in order, but asynchronous .NET calls (and results) will depend on thread scheduling in an arbitrary order that can't be predicted. Is that correct, or what can we say about call ordering?
2. I'd like to retain the logging on both sides of the calls (JS and .NET) because it isn't clear from the final values of `GenericType<TValue>.Value` in the component what's happening behind the scenes. I don't want separate examples (even in the same component) for each .NET call or call set (sync vs. async). Digesting this all from a single interop action means that we'll need to log on both sides.
3. I'd like to retain the random numbers so that the reader can identify which call from the JS side matches a .NET method execution.
4. I'd like to retain the `double` vs. `string` because it illustrates that the `GenericType` really is a **_generic type_**. I know ... *duh, of course* 🙄 on this point ... still tho ... I think that it's a nicer demo with a pair of types.
5. The main ❓ is ... Did I create a 💩👃 **_Rex Stinker_**&trade; 💩👃 here 😄?

`GenericType.cs`:

```csharp
using Microsoft.JSInterop;

public class GenericType<TValue>
{
    public TValue? Value { get; set; }

    [JSInvokable]
    public void Update(TValue newValue)
    {
        Value = newValue;

        Console.WriteLine($"Update: GenericType<{typeof(TValue)}>: {Value}");
    }

    [JSInvokable]
    public async void UpdateAsync(TValue newValue)
    {
        await Task.Yield();
        Value = newValue;

        Console.WriteLine($"UpdateAsync: GenericType<{typeof(TValue)}>: {Value}");
    }
}
```

JS (HTML):

```html
<script>
  const randomInt = () => Math.floor(Math.random() * 99999);

  window.invokeDotNetMethodsAsync = 
      async (supportSyncInterop, dotNetHelper1, dotNetHelper2) => {
    
    var n = randomInt();
    console.log(`JS: invokeAsync:Update('string ${n}')`);
    await dotNetHelper1.invokeMethodAsync('Update', `string ${n}`);

    n = randomInt();
    console.log(`JS: invokeAsync:UpdateAsync('string ${n}')`);
    await dotNetHelper1.invokeMethodAsync('UpdateAsync', `string ${n}`);

    if (supportSyncInterop) {
      n = randomInt();
      console.log(`JS: invokeMethod:Update('string ${n}')`);
      dotNetHelper1.invokeMethod('Update', `string ${n}`);
    }

    n = randomInt();
    console.log(`JS: invokeMethodAsync:Update(${n})`);
    await dotNetHelper2.invokeMethodAsync('Update', n);

    n = randomInt();
    console.log(`JS: invokeMethodAsync:UpdateAsync(${n})`);
    await dotNetHelper2.invokeMethodAsync('UpdateAsync', n);

    if (supportSyncInterop) {
      n = randomInt();
      console.log(`JS: invokeMethod:Update(${n})`);
      dotNetHelper2.invokeMethod('Update', n);
   }
  };
</script>
```

`Pages/GenericsExample.razor`:

```razor
@page "/generics-example"
@using System.Runtime.InteropServices
@inject IJSRuntime JSRuntime

<p>
    <button @onclick="InvokeInterop">Invoke interop</button>
</p>

<ul>
    <li>genericType1: @genericType1?.Value</li>
    <li>genericType2: @genericType2?.Value</li>
</ul>

@code {
    private GenericType<string> genericType1 = new() { Value = "string 0" };
    private GenericType<double> genericType2 = new() { Value = 0 };

    public async Task InvokeInterop()
    {
        var supportSyncInterop = 
            RuntimeInformation.IsOSPlatform(OSPlatform.Create("BROWSER"));

        await JSRuntime.InvokeVoidAsync(
            "invokeDotNetMethodsAsync",
            supportSyncInterop,
            DotNetObjectReference.Create(genericType1),
            DotNetObjectReference.Create(genericType2));
    }
}
```

Rendered and run ...

<img width="526" alt="Capture" src="https://user-images.githubusercontent.com/1622880/160810091-002d929e-5e06-4854-a4f1-b60a3b8c7610.PNG">

> JS: invokeMethodAsync:Update('string 37802')
> .NET: Update: GenericType<System.String>: string 37802
> JS: invokeMethodAsync:UpdateAsync('string 53051')
> JS: invokeMethod:Update('string 26784')
> .NET: Update: GenericType<System.String>: string 26784
> JS: invokeMethodAsync:Update(14107)
> .NET: Update: GenericType<System.Double>: 14107
> JS: invokeMethodAsync:UpdateAsync(48995)
> JS: invokeMethod:Update(12872)
> .NET: Update: GenericType<System.Double>: 12872
> .NET: UpdateAsync: GenericType<System.String>: string 53051
> .NET: UpdateAsync: GenericType<System.Double>: 48995

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by TanayParikh** [comment]
Thanks @guardrex, will review tomorrow 😄

**Comment by guardrex** [comment]
@TanayParikh ... The PR is at https://github.com/dotnet/AspNetCore.Docs/pull/25465. It's just a rough draft at the moment, but it's 6am here CST, so I think I'll have it shaped up for review by the time you get on the repo. If you see the PR is **_off of DRAFT_**, it's ready.
