### ISSUE TITLE
Only implementing ConfigureAppConfiguration from FunctionsStartup as per documentation does not compile

### ISSUE THREAD

**Issue by edvinkugelberg-ff** [dotnet/AspNetCore.Docs#25451]
Following the tutorial on how to use dependency injection for azure functions, the code under the subtitle ["Customizing configuration sources"](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources) results in error:

`Abstract inherited member 'void Microsoft.Azure.Functions.Extensions.DependencyInjection.FunctionsStartup.Configure(IFunctionsHostBuilder)' is not implemented`

The code snippet causing the error is as follows:

```
using System.IO;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]

namespace MyNamespace
{
    public class Startup : FunctionsStartup
    {
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            FunctionsHostBuilderContext context = builder.GetContext();

            builder.ConfigurationBuilder
                .AddJsonFile(Path.Combine(context.ApplicationRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
                .AddJsonFile(Path.Combine(context.ApplicationRootPath, $"appsettings.{context.EnvironmentName}.json"), optional: true, reloadOnChange: false)
                .AddEnvironmentVariables();
        }
    }
}
```

While in another article [Quickstart: Create an Azure Functions app with Azure App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-functions-csharp?tabs=in-process#connect-to-an-app-configuration-store) the missing override is present, making the code compilable:

```
using System;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

[assembly: FunctionsStartup(typeof(FunctionApp.Startup))]

namespace FunctionApp
{
    class Startup : FunctionsStartup
    {
        public override void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
        {
            string cs = Environment.GetEnvironmentVariable("ConnectionString");
            builder.ConfigurationBuilder.AddAzureAppConfiguration(cs);
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {
        }
    }
}
```

I thus, expect that the first code snippet from ["Customizing configuration sources"](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources) is faulty and should be changed to also contain the missing override of `void Configure(IFunctionsHostBuilder builder)`

**Comment by wadepickett** [comment]
Thanks @edvinkugelberg-ff !

The repo this issue has been opened on is not the one that actually contains the document you indicated needs a fix.   I will open a new one on the right repo (azure-docs) add a link to it so you can see where it moved to and then close this one.  Thanks for taking the time to point out this issue, it is very appreciated.

**Comment by wadepickett** [comment]
This issue has been moved to the azure-docs repo that contains the topic this issue is referencing.
The new tracking issue is:
[azure-docs    Issue 90632 ](https://github.com/MicrosoftDocs/azure-docs/issues/90632)
