### ISSUE TITLE
Scaffolding Identity in .Net 6 Core

### ISSUE THREAD

**Issue by JeffW12345** [dotnet/AspNetCore.Docs#25460]
The ['Scaffold Identity into a Razor project without existing authorization'](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio#scaffold-identity-into-a-razor-project-without-existing-authorization) instructions for  don't work for .Net 6.0 Core.

The following code was automatically added to my Program.cs file as a result of doing scaffolding for a Razor Pages app, using a context that did not previously exist:

builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true).
AddEntityFrameworkStores<ApplicationDbContext)<>();builder.Services.AddDbContext<ApplicationDbContext>(options => 
options.UseSqlServier(connectionString));

I got two error messages:

- IServiceCollection does not contain a definition for 'AddDefaultIdentity'.
- The name 'connectionString' does not exist in the current context.

What do you suggest, please?

Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Do you have  `    <ImplicitUsings>enable</ImplicitUsings>` in you project file? 
Can you post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem? 
File a bug with the repo. If you used the CLI, file in https://github.com/dotnet/Scaffolding
 For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team. For Visual Studio Code, you can open an issue at [microsoft/vscode issues](https://github.com/Microsoft/vscode/issues).
