### ISSUE TITLE
Missing await in gRPC Health Client code sample

### ISSUE THREAD

**Issue by martin-pes** [dotnet/AspNetCore.Docs#25476]
Section https://docs.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0#call-grpc-health-checks-service has missing await in code sample
```
var response = await client.CheckAsync(new HealthCheckRequest());
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1e8570-b223-d4b9-c85f-afeb2e3e8941
* Version Independent ID: 5a1e8570-b223-d4b9-c85f-afeb2e3e8941
* Content: [gRPC health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
Good spotting. Fix: https://github.com/dotnet/AspNetCore.Docs/pull/25477
