### ISSUE TITLE
Commented out content showing up

### ISSUE THREAD

**Issue by markjulmar** [dotnet/AspNetCore.Docs#25487]
Page:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio

Source:
https://raw.githubusercontent.com/dotnet/AspNetCore.Docs/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md

A section of the Markdown looks like it was supposed to be commented out, but the comment is closed on the starting line - leaving the rest of the content rendered.

![image](https://user-images.githubusercontent.com/5099741/161166466-53f15c3d-1cc2-4827-90e2-09cd37721376.png)

The error occurs on line 171: `<!-->`

The trailing `>` is closing the HTML comment off so the remainder of the block is being rendered as part of the tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
