### ISSUE TITLE
[Minimal APIs] Add documentation for route handler filters

### ISSUE THREAD

**Issue by captainsafia** [dotnet/AspNetCore.Docs#25483]
# Filters in Minimal API applications

Minimal APIs support a filters experience that allows developers to implement business logic that supports inspecting and modifying parameters provided during a route handler invocation and intercepting the response behavior of a route handler. Filters can be helpful in scenarios where you want to:

- Validate request parameters and body that are sent to an endpoint
- Log information about the request and response that were processed
- Validate that a request is targeting a supported API version

Like many constructs in the minimal APIs space, filters can be registered onto an endpoint by using the `AddFilter` extension method overloads.

Filters can be registered by providing a Delegte that takes a RouteHandlerInvocationContext and a RouteHandlerFilterDelegate.

```csharp
app.MapGet("/todos/{id}", (int id) => ...)
  .AddFilter((invocationContext, next) => ...);
```

The `RouteHandlerInvocationContext` provides access to the `HttpContext` associated with the request and a `Parameters` list indicating the arguments passed to the handler in the order in which they appear in the argument list of the handler.

When registered, the contents of the delegate will be executed before the handler is invoked. When multiple `AddFilter` invocations are made on a handler, the filters will be executed in order of FILO order, so the first filter registered will run last.

```csharp
app.MapGet("/todos/{id}", (int id) => ...)
  .AddFilter(FilterA)
  .AddFilter(FilterB)
  .AddFilter(FilterC);
```

In the scenario above, the filters an handlers will be executed in the following order FilterC -> FilterB -> FilterA -> handler, where the `next` for `FilterC` is `FilterB` and so on.

Filters can also be registered using a delegate that takes a `RouteHandlerContext` and returns a `RouteHandlerFilterDelegate`. This factory pattern is particularly helpful when you want to register filter that depends on the signature of the target route handler. For example, let's say that we wanted to register a filter that validated endpoints which consumed a `Todo` object in the body.

```csharp
app.MapPost("/todos/{id}", (Todo todo) => ...)
.AddFilter((routeHandlerContext, next) => {
  var parameters = routeHandlerContext.MethodInfo.GetParameters();
  var anyTodos = parameters.FindIndex(parameter => parameter.ParameterType == typeof(Todo));
  return async (invocationContext) => 
  {
    if (anyTodos >= 0)
    {
      var todoParameter = invocationContet.Parameters[anyTodos];
      if (!IsValid(todoParameter))
      {
        return Results.Problem("The Todo is invalid.");
      }
    }
    return await next(invocationContext);
  };
});
```

The `RouteHandlerContext` object provides access to the `MethodInfo` associated with the endpoint's handler as well as the  `EndpointMetadata` that has been applied on the endpoint.

In addition to being passed as delegates, filters can be registered by implementing the `IRouteHandlerFilter` interface.

```csharp
public class MyFilter : IRouteHandlerFilter
{
  public ValueTask<object?> InvokeAsync(RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next)
  {
     ...
   }
}
```

We can register the `MyFilter` implementation above by passing an instance of the class to the `AddFilter` extension method.

```csharp
app.MapGet("/todos/{id}", (int id) => ...)
.AddFilter(new MyFilter());
```

Filters that implement the `IRouteHandlerFilter` interface can also consume dependencies from DI when registered onto an endpoint using the `AddFilter<TFilterType>()` overload.  For example, the following filter consumes the `ILoggerFactory` dependency from DI.

```csharp
public class MyFilter : IRouteHandlerFilter
{
  private ILoggerFactory _loggerFactory;

  public MyFilter(ILoggerFactory loggerFactory)
  {
    _loggerFactory = loggerFactory;
  }

  public ValueTask<object?> InvokeAsync(RouteHandlerInvocationContext context, RouteHandlerFilterDelegate next)
  {
     ...
   }
}
```

And can be registered onto an endpoint with the following syntax.

```csharp
app.MapGet("/todos/{id}", (int id) => ...)
.AddFilter<MyFilter>();
```

> 💡 Although filters can resolve their dependencies from DI, filters themselves can not be resolved from DI.

As of .NET 7 Preview 4, filters are not supported on route groups.

As of .NET 7 Preview 5, the `RouteHandlerInvocationContext` also provides support for a `GetParameter<T>` API. Previously, parameters could only be asked using the `Parameters` list on the `RouteHandlerInvocationContext`. With the new model, the following invocation.

```csharp
var todoParameter = (Todo)invocationContext.Parameters[0];
```

Becomes...

```csharp
var todoParameter = invocationContext.GetParameter<T>(0);
```

**Comment by Rick-Anderson** [comment]
@captainsafia  do you have a complete sample I could use?

**Comment by Rick-Anderson** [comment]
@captainsafia  can you recommend where we should add this content?

**Comment by captainsafia** [comment]
> @captainsafia do you have a complete sample I could use?

They are not the most real-world samples but [this repo](https://github.com/captainsafia/MinimalFiltersExample) has the current complete API surface area used.

This API is shipping in preivew3 and we made some changes in preview4 and will probably tweak it a bit in response to feedback in preview5. My thinking is that we keep samples to a minimum as we polish things up.

> @captainsafia can you recommend where we should add this content?

It doesn't look like we have a top-level heading for minimal yet (correct me if I'm wrong) so I think putting it as a new heading under https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0 is probably sufficient.

**Comment by captainsafia** [comment]
I've updated the content in the original issue to be a little bit more informative. Let me know if anything is still missing!

**Comment by Rick-Anderson** [comment]
@captainsafia can you fix [this code](https://github.com/Rick-Anderson/TodoApi7_filters/blob/main/Program.cs#L42-L57)

**Comment by hgirma** [comment]
I can't find IRouteHandlerFilter, my project is .net 7, but getting The type or namespace name 'type/namespace' could not be found (are you missing a using directive or an assembly reference?)

I have downloaded the .net 7 SDK (7.0.101) and have the latest VS 2022 (17.4.2)

**Comment by captainsafia** [comment]
@hgirma It's now called `IEndpointFilter` as of the official .NET 7 release. Have you confirmed you're reading the 7.0 GA version of the docs?

See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-7.0

**Comment by hgirma** [comment]
That explains it, saw a few blogs referring to the old interface as well, but didn't consult the GA doc. Thank you.
