### ISSUE TITLE
HTML Helpers link is out of date 

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/AspNetCore.Docs#25494]
The `Html Helpers` link in the [The @model directive](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-6.0&tabs=visual-studio#the--directive-3) section on this page links to some seriously out of date documentation [here](https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/views/creating-custom-html-helpers-cs#understanding-html-helpers)

This is some old documentation for MVC1 and looks like classic ASP syntax to me that doesn't work in a Razor page at all.

Isn't there some more up-to-date documentation that this could link to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Part 3, scaffolded Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
[@model directive section](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-6.0&tabs=visual-studio#the--directive-3) is pointing to 4.x content: [Creating Custom HTML Helpers (C#)](https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/views/creating-custom-html-helpers-cs#understanding-html-helpers) but it is specifically calling out the  `@Html.Dispalyfor` HTML Helper.

**Comment by Rick-Anderson** [comment]
@Neutrino-Sunset  nope, that's the newest. I'd like to get rid of [HTML helpers](https://github.com/dotnet/aspnetcore/issues/3956)

**Comment by Neutrino-Sunset** [comment]
Can tag helpers even do all the things the HTML Helpers can do? Discussions like [this](https://stackoverflow.com/a/55474543/954927) suggest not.

How in a Razor page do I reuse a trivial bit of UI in which I want to pass a ModelExpression defined by the parent to `asp-for` in an input tag helper in the partial? The post linked above suggests it's only possible with an obtuse combination of tag helpers and HTML Helpers, but there is no up-to-date documentation for tag helpers anywhere so even this approach is impossible to follow.

It's all very well saying you want to get rid of something, but if it's the only way to perform certain tasks, and you don't have anything else that can completely replace it, saying you want to get rid of it isn't sufficient grounds for it not currently being documented.
