### ISSUE TITLE
New doc content for ShadowCopying

### ISSUE THREAD

**Issue by HaoK** [dotnet/AspNetCore.Docs#25499]
Part of https://github.com/dotnet/aspnetcore/issues/40961 to make ShadowCopy non experimental we should document this feature

New section content:

## ShadowCopying 

In .NET 6 we added experimental support for shadow copying app assemblies to the ASP.NET Core Module (ANCM) for IIS. When an ASP.NET Core app is running on Windows, the binaries are locked so that they cannot be modified or replaced. You can stop the app by deploying an [app offline file](https://docs.microsoft.com/aspnet/core/host-and-deploy/app-offline), but sometimes doing so is inconvenient or impossible. Shadow copying enables the app assemblies to be updated while the app is running by making a copy of the assemblies.

Starting in .NET 7 preview4 shadow copying is no longer experimental and will be fully supported. The feature is not intended to enable zero-downtime deployment, so its expected that IIS will still recycle the app, and some requests may get 503.  We recommend using a pattern like [blue-green deployments](https://www.martinfowler.com/bliki/BlueGreenDeployment.html) for zero-downtime deployments. Features like shadow copy help, but don't guarantee that you can do a zero-downtime deployment.

You can enable shadow copying by customizing the ANCM handler settings in web.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore"/>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".logsstdout">
      <handlerSettings>
        <handlerSetting name="enableShadowCopy" value="true" />
        <!-- Ensure that the IIS ApplicationPool identity has permission to this directory -->
        <handlerSetting name="shadowCopyDirectory" value="../ShadowCopyDirectory/" />
      </handlerSettings>
    </aspNetCore>
  </system.webServer>
</configuration>
```

***EDIT by @Rick-Anderson***
Update:
*  ` https://github.com/dotnet/aspnetcore/issues/40961` when this issue is resolved.
* [Shadow copying in IIS](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#shadow-copying-in-iis)
* Close https://github.com/dotnet/AspNetCore.Docs/issues/23733

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d172b69-845d-739a-742c-617b9eed04fe
* Version Independent ID: 79d553f1-9112-b61a-0ad0-dfbb11e5071a
* Content: [Advanced configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Location: As a section under IIS -> Advanced (Or does this deserve its own Shadow Copying page?)

An H2 should have plenty of SEO juice
## ShadowCopying

**Comment by Rick-Anderson** [comment]
> Location: As a section under IIS -> Advanced (Or does this deserve its own Shadow Copying page?)

An H2 should have plenty of SEO juice
## ShadowCopying

**Comment by HaoK** [comment]
@Rick-Anderson is this enough for you to add the section with the content in the issue, or do you prefer if I open a PR and make the changes myself (I'm sure my words will require some editing and all that too)

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson is this enough for you to add the section with the content in the issue, or do you prefer if I open a PR and make the changes myself (I'm sure my words will require some editing and all that too)

I'll PR it and you can suggest changes.
