### ISSUE TITLE
Pluralization: What if the default language of the application is Czech?

### ISSUE THREAD

**Issue by reponemec** [dotnet/AspNetCore.Docs#25508]
But what if the default language of the application is Czech? I need to translate from Czech to English. All keys are therefore written in Czech. In this case, how to write singular and plural forms in Czech?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1098b7-dbe7-a8d8-f57f-017b1c94e960
* Version Independent ID: 96179de2-df1c-ff1d-5a2e-89b0949e0620
* Content: [Configure portable object localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/portable-object-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/portable-object-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @sebastienros
* Microsoft Alias: **scaddie**

**Comment by sebastienros** [comment]
As explained in this section https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-6.0#using-a-different-default-pluralized-language you can create an extension method that takes the exact number of plural arguments for your language.
