### ISSUE TITLE
Are there any caveats not mentioned, because I have Net5 projects and cannot get rid of CORS errors using this alone

### ISSUE THREAD

**Issue by PandaWood** [dotnet/AspNetCore.Docs#25504]
I've been following this documentation and cannot get CORS to work properly (ie without browser errors)
No matter what middleware code or order I set (based on this documentation) I still get `strict-origin-when-cross-origin` referrer policy
I feel that there must be something missing from this documentation

I add this code in the ConfigureServices() of a new .NET5 web API

```
services.AddCors(o => o.AddDefaultPolicy(options =>
{
	options.AllowAnyOrigin()
		 .AllowAnyMethod()
	 	 .AllowAnyHeader();
}));
```

Then 
`app.UseCors();`

in Configure() method

In exactly the same position, relative to other calls, as the documentation requires. I've also tried every other combination I could imagine. But I cannot query my API from my partner NET5 MVC project without CORS browser errors (ie being serviced up a strict-origin-when-cross-origin referral)

I'm hoping we can add a troubleshooting guide in here. Are there any caveats, such as different behaviour on kestrel? only working with actual cross-domain requests... or anything that can be added to save the weary traveller?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0#dp)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @PandaWood. As I understand it, the referrer policy and CORS don't impact each other. Can you share a screenshot or more information about the error you see here?

**Comment by PandaWood** [comment]
You're right about referer policy, I meant to say it's not adding any headers eg [Access-Control-Allow-Origin]
Error is 
`Access to XMLHttpRequest at 'localhost:5001/core/subsgroups?description=fr' from origin 'http://localhost:5002' has been blocked by CORS policy: ...`
My WebMvc project is on :5002 and my API on :5001

And my code, following relative order in this doc is summarized as:
```
services.AddAuthorization();	
services.AddCors(o => o.AddDefaultPolicy(options =>
{
	options.AllowAnyOrigin()
 	 .AllowAnyMethod()
 	 .AllowAnyHeader();
}));

services.AddControllers();
services.AddRouting(options => options.LowercaseUrls = true);
```

And then 
```
app.UseStaticFiles();
app.UseRouting();
app.UseCors();
app.UseAuthorization();

app.UseEndpoints(endpoints =>
{...
```

**Comment by serpent5** [comment]
You may also find that the headers aren't set if there's an exception being thrown in the ASP.NET Core API, for example.
