### ISSUE TITLE
Issue with the ConfigurePrimaryHttpMessageHandler Documentation for Core 3.1, 5.0 and (possibly) 6.0

### ISSUE THREAD

**Issue by jrovny** [dotnet/AspNetCore.Docs#25516]
There appears to be an error in the code snippet documentation regarding the ConfigurePrimaryHttpMessageHandler [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1#implement-an-httpclient-using-a-certificate-and-a-named-httpclient-from-ihttpclientfactory-1) for Core 3.1, 5.0 and (possibly) 6.0.

Here's the code snippet from the docs:
```
var clientCertificate = 
    new X509Certificate2(
      Path.Combine(_environment.ContentRootPath, "sts_dev_cert.pfx"), "1234");

var handler = new HttpClientHandler();
handler.ClientCertificates.Add(clientCertificate);

services.AddHttpClient("namedClient", c =>
{
}).ConfigurePrimaryHttpMessageHandler(() => handler); // Delegate is returning the same obj in memory which gets disposed
```

The delegate being called by ConfigurePrimaryHttpMessageHandler is returning the same object in memory, which is disposed after 2 minutes per the documents [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#httpclient-and-lifetime-management-2). This resulted in the following error message: Cannot access a disposed object. Object name: 'SocketsHttpHandler'

To correct this issue in my code, I tweaked it to be the following, which works:
```
var clientCertificate = 
    new X509Certificate2(
      Path.Combine(_environment.ContentRootPath, "sts_dev_cert.pfx"), "1234");

services.AddHttpClient("namedClient", c =>
{
}).ConfigurePrimaryHttpMessageHandler(() =>
{
    var handler = new HttpClientHandler(); // Returning a new HttpClientHandler for each call instead of referring to same one in memory
    handler.ClientCertificates.Add(clientCertificate);
    return handler;
});
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b7960d-6de5-78ee-bc45-d7218239bbc8
* Version Independent ID: d2db534b-198a-dc99-5b5a-0525582d39ac
* Content: [Configure certificate authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/certauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/certauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @blowdart
* Microsoft Alias: **bdorrans**

**Comment by blowdart** [comment]
@HaoK @Tratcher

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler?view=dotnet-plat-ext-6.0
> The configureHandler delegate should return a new instance of the message handler each time it is invoked.

Their fix looks good.
