### ISSUE TITLE
Change the filename extension of DLL files - script in guidance incorrect or alternate behavior

### ISSUE THREAD

**Issue by sykesbPragmatics** [dotnet/AspNetCore.Docs#25517]
1)
If i create a file publish profile from within
Microsoft Visual Studio Professional 2022
Version 17.2.0 Preview 2.1
VisualStudio.17.Preview/17.2.0-pre.2.1+32317.152
Microsoft .NET Framework
Version 4.8.04084

and execute it, the powershell script task in the example appears to be executed BEFORE the end of the publish cycle.  The files that the script is attempting to update do not yet exist.  Running the same publish from the command line via "dotnet publish" appears to work in the proper sequence.  If this example is only expected to work from the command line I believe that should be highlighted.

2)

The documentation states: "app's published output (for example, {CONTENT ROOT}/bin/Release/netstandard2.1/publish/wwwroot)."

however the path listed in the ChangeDLLExtensions.ps1 example is acting upon the wwwroot of the BUILT assemblies, not the published ones.
$filepath\bin\Release\$tfm\wwwroot\_framework\_bin

Whereas it should be:

(NOTE addition of "publish")
$filepath\bin\Release\$tfm\publish\wwwroot\_framework\_bin

Additionally, the example path has "_bin" as the final folder.  In my version of blazor wasm (.Net Core 6.0) the _bin folder does not appear to exist.  Its possible that this is the result of something I'm doing different in my project but I do not believe so.

The script that works for me is:
```
param([string]$filepath,[string]$tfm)
dir $filepath\bin\Release\$tfm\publish\wwwroot\_framework | rename-item -NewName { $_.name -replace ".dll\b",".bin" }
((Get-Content $filepath\bin\Release\$tfm\publish\wwwroot\_framework\blazor.boot.json -Raw) -replace '.dll"','.bin"') | Set-Content $filepath\bin\Release\$tfm\publish\wwwroot\_framework\blazor.boot.json
Remove-Item $filepath\bin\Release\$tfm\publish\wwwroot\_framework\blazor.boot.json.gz
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-ca/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#change-the-filename-extension-of-dll-files)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sykesbPragmatics ... The content here was derived from the framework engineers, who reviewed and approved the doc's content (both Dan Roth and Steve Sanderson) a few years ago on https://github.com/dotnet/aspnetcore/issues/5477 with additional discussion on https://github.com/dotnet/aspnetcore/issues/5477 ... and a few small NIT updates along the way since then. IIRC, I did try it and it worked for me; but that was a while ago ... probably over a year ago. Things do break 💥 release-to-release. I'll take a look as soon as I can. Hopefully, I'll have some time next week. Thanks for writing in on this.

**Comment by sykesbPragmatics** [comment]
@guardrex Yup, i figured which is why i wrote it up.  I wish this functionality was baked directly into blazor build/publish since it seems like it would be a widespread issue.  Maybe a flag in blazor client config or publish?  Thanks!

**Comment by guardrex** [comment]
That was an ask at https://github.com/dotnet/aspnetcore/issues/21489 ... *but it looks like they rejected it* 😢.

**Comment by guardrex** [comment]
**UPDATE (4/14)**: I'm trying to get back to this, but I had a couple of days off for R&R, had a sick day for a root canal ... **_Ouch!_** 👨‍⚕️ 💉, and am currently bogged down in high priority issues. I'll get back to this issue *ASAP*.

**Comment by sykesbPragmatics** [comment]
@guardrex Hope you feel better

**Comment by guardrex** [comment]
Thanks ... I'm fine. It was more uncomfortable and stressful than actually painful. It was yesterday morning, so I'm getting back to normal now. Given that today is Thursday, this will probably drift out to next week ... **_IF_** I don't get any surprises around here. You never can tell. I hate to make predictions on when issues will be worked ... *I'm wrong at least 50% of the time* 😆.

**Comment by guardrex** [comment]
Ok ... I'm **_BACK!_** I have time this morning to see if I can repro this and make updates if so.

Right off the bat tho ... I see you used VS Preview. I prefer not to doc from that for non-preview scenarios. The previews of VS can behave strangely. It's best to check on this with the current release of VS, and that's what I'll do.

I'll get back here in a bit or go straight to a PR depending on how things play out.
