### ISSUE TITLE
Enhance with hosted Blazor WASM debug scenario

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25512]
Per **Debugging Blazor WASM after publish**: https://github.com/dotnet/aspnetcore/issues/41033.

Dev:

> But the problem is that, when I publish it (both with Release or Debug configuration), and when I launch the output executable, Alt+Shift+D throws an error on the browser console:
>
> Cannot start debugging, because the application was not compiled with debugging enabled.

Javier:

> You need to make sure you enable `DebuggerSupport` as well as `CopyOutputSymbolsToPublishDirectory` when you publish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@captainsafia ... We never addressed **_published, hosted Blazor WASM_** for the prior rounds of content work in the *Debug Blazor WebAssembly* topic. Do you have any feedback on this before I take a stab at adding a section of coverage from Javier's PU issue remark?

**Comment by captainsafia** [comment]
> We never addressed published, hosted Blazor WASM for the prior rounds of content work in the Debug Blazor WebAssembly topic. Do you have any feedback on this before I take a stab at adding a section of coverage from Javier's PU issue remark?

Documenting the workaround should be sufficient. I would emphasize that users should make sure that flag is only enabled for local, published apps and not pushed to production deployments.
