### ISSUE TITLE
Missing Method in the Tutorial

### ISSUE THREAD

**Issue by PostalMike** [dotnet/AspNetCore.Docs#25523]
This method is not in the project to be updated:

```
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem todoItem)
{
    _context.TodoItems.Add(todoItem);
    await _context.SaveChangesAsync();

    //return CreatedAtAction("GetTodoItem", new { id = todoItem.Id }, todoItem);
    return CreatedAtAction(nameof(GetTodoItem), new { id = todoItem.Id }, todoItem);
}
```
Tried adding it to the TodoItemsController.cs, didn't work because GetTodoItem doesn't exist in the context.

Great tutorial otherwise but one other point can be clarified better -- the generated code file where the [ApiController]
 attribute is placed is WeatherForecastController.  But here is the text, it says 'marks the class' without saying where it is.  So the text ApiController, searched for, finds it.

The generated code:

Marks the class with the [[ApiController]](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.apicontrollerattribute) attribute. This attribute indicates that the controller responds to web API requests. For information about specific behaviors that the attribute enables, see [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0).
Uses DI to inject the database context (TodoContext) into the controller. The database context is used in each of the [CRUD](https://wikipedia.org/wiki/Create,_read,_update_and_delete) methods in the controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there, this is what's generated

```

// POST: api/TodoItems
// To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem todoItem)
{
    _context.TodoItems.Add(todoItem);
    await _context.SaveChangesAsync();

    return CreatedAtAction("GetTodoItem", new { id = todoItem.Id }, todoItem);
}
```

**Comment by PostalMike** [comment]
Rick, it is NOT in the generated code anywhere.

 

What I sent to you came from the page in your tutorial.

**Comment by PostalMike** [comment]
What I’m saying is the copy in my email comes from the tutorial page.  It’s not in the code that was generated.

 

And the object ‘GetTodoItem’ flags as not existing in the content.

 

I’m not sure what the protocol is on closing tickets but please check with me first.

**Comment by PostalMike** [comment]
Aha, let me be more clear.

 

Instructions in the tutorial state to *update* the code with the method provided in the tutorial.  It does not exist to update it.

 

I could not see where to put it from the instructions.  Searched for and could not find it.

 

Put it in the Controller – the GetTodoItem flags as not existing in the content.  Checked in both controllers, the full code does not exist already.

 

The instructions don’t say to *insert* the code but to *update* it.  I’m expecting it to exist already.

 

At any rate the GetTodoItem flags as not existing in the context.  So it’s still broken from what I see.

 

Wonder if this isn’t an instructions typo?

 

From: Michael Durthaler ***@***.***> 
Sent: Wednesday, April 6, 2022 06:59
To: 'dotnet/AspNetCore.Docs' ***@***.***>; 'dotnet/AspNetCore.Docs' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [dotnet/AspNetCore.Docs] Missing Method in the Tutorial (Issue #25523)

 

What I’m saying is the copy in my email comes from the tutorial page.  It’s not in the code that was generated.

 

And the object ‘GetTodoItem’ flags as not existing in the content.

 

I’m not sure what the protocol is on closing tickets but please check with me first.
