### ISSUE TITLE
ObjectGraphDataAnnotationsValidator.TryValidateRecursive needs to be public.

### ISSUE THREAD

**Issue by axedaddy** [dotnet/AspNetCore.Docs#25528]
ObjectGraphDataAnnotationsValidator.TryValidateRecursive  needs to be public.

I want to validate the BillingAddress only when the BillingSameAsShipping is false. 
I copied your code for ObjectGraphDataAnnotationsValidator and ValidateComplexType.
Renamed them to BlazorObjectGraphDataAnnotationsValidator  and BlazorValidateComplexType

Now in my Models Validate function I can call BlazorObjectGraphDataAnnotationsValidator.TryValidateRecursive(BillingAddress, validationContext)  and the correct validation occurs and the validation message is shown next to the properties as usual.
I cant do this with your experimental ObjectGraphDataAnnotationsValidator as all the functions are internal. 

Everything else is great.

    public class CheckoutViewModel : IValidatableObject
    {
        public CheckoutType CheckoutType { get; set; }

        [BlazorValidateComplexType]
        public RegisterViewModel Register { get; set; }

        [BlazorValidateComplexType]
        public AddressViewModel ShippingAddress { get; set; }
        
        public AddressViewModel BillingAddress { get; set; }

        public bool BillingSameAsShipping { get; set; }

        [Required]
        public bool TermsAndConditions { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var results = new List<ValidationResult>();

            if (BillingSameAsShipping == false)
            {
                BlazorObjectGraphDataAnnotationsValidator.TryValidateRecursive(BillingAddress, validationContext);
            }

            return results;
        }

    } 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @axedaddy ... We only work on documentation here. The product unit has their own repo, and the button for **This product** at the bottom of the topic takes readers to content for opening an issue for the product unit.

You're welcome to adopt the API for your needs. If you want to ask them directly about this approach and make a feature request, you can open an issue on their repo ...

https://github.com/dotnet/aspnetcore/issues
