### ISSUE TITLE
asp-for get expression name from expression

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/AspNetCore.Docs#25531]
This documentation describes how the `asp-for` attribute of a `label` or `input` tag helper is used to specify an 'expression name' which is the property of the model that the server should use to generate the appropriate `label` or `input` markup, i.e. label display name and input validation as specified by the model property's attributes.

What it doesn't explain is how do you specify this expression name via an expression as opposed to hard-coding it. If for example you are using the tag helper in a partial then having a hard coded expression name is not going to be very useful, since your partial is likely to want to target different properties at each place where the partial is used.

Here is a concrete example

I have a form in a Razor page containing loads of fields, all with identical markup.

    @page "{id:int}"
    @model RazorPagesMovie.Pages.Movies.EditModel
    
    <form method="post">
       <div class="form-group">
          <label asp-for="Movie.Title" class="control-label"></label>
          <input asp-for="Movie.Title" class="form-control" />
          <span asp-validation-for="Movie.Title" class="text-danger"></span>
       </div>
       <div class="form-group">
          <label asp-for="Movie.ReleaseDate" class="control-label"></label>
          <input asp-for="Movie.ReleaseDate" class="form-control" />
          <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
       </div>
       <div class="form-group">
          <label asp-for="Movie.Genre" class="control-label"></label>
          <input asp-for="Movie.Genre" class="form-control" />
          <span asp-validation-for="Movie.Genre" class="text-danger"></span>
       </div>
    </form>

Rather than my page file being stuffed with all this copy/paste I decide to eliminate the code duplication using the feature the ASP documentation says I should be using for this, namely a partial.

So I create a partial

    @model object
    
    <div class="form-group">
       <label asp-for="@Model" class="control-label"></label>
       <input asp-for="@Model" class="form-control" />
       <span asp-validation-for="@Model" class="text-danger"></span>
    </div>

...and reference that from my page file using

    <partial name="_MovieField" for="Movie.Title" />

Only problem, nothing works. The `asp-for="@Model"` in the label doesn't resolve the display name for the property so the label is blank, and none of the validation works either.

I've tried passing the desired property in ViewData and accessing that in the partial, but that doesn't work.

    <label asp-for="@(ViewData["PropertyName"])" class="control-label"></label>

I've even tried reflection, but that doesn't work either.

    <label asp-for="@(Model.GetType().GetProperty("Title"))" class="control-label"></label>

Is there any way to get this to work? If not and you simply can't use tag helpers that expect expression names in partials, then that would seem to make partials pretty useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@NTaylorMullen can you take a quick look?

**Comment by NTaylorMullen** [comment]
@Rick-Anderson I no longer work on the ASP.NET Core runtime team and am not quite sure the correct expectations in this scenario 😢

**Comment by frankabbruzzese** [comment]
@Neutrino-Sunset,
Using @Model is not correct since it doesn't compute names but just the value of the input field. asp-for expects a property path in order to compute the right names. However, in this case, the path is empty, and an empty path is not accepted by asp-for (this might be considered a bug). Conclusion?

In this case, you can't use Tag helpers but you must implement your partial view with Html helpers. With Html helpers you represent properties with lambda expressions, thus you can represent also an empty property path as m => m, thus overcoming the issue.

**Comment by Rick-Anderson** [comment]
@Neutrino-Sunset  if this is still a problem, 

1. create the simplest possible project that reproduces the issue
2. Create an issue at https://github.com/dotnet/aspnetcore/issues with a link to the public GitHub repo
3. mention this issue.
