### ISSUE TITLE
In ASP.NET Core, why are Session and User not accessible from services instead of members of HttpContext?

### ISSUE THREAD

**Issue by wessleym** [dotnet/AspNetCore.Docs#25536]
In ASP.NET Core, not all sites use sessions, user authentication, or WebSockets.  So why are `Session`, `User`, and `WebSockets` members of `HttpContext`?  Why wouldn't these have been made available through some kind of per-request `ServiceLifetime.Transient` service (e.g., `AuthenticatedUserService.User`)?

Is it included on `HttpContext` just for convenience since so many sites do use `Session` and `User`?  Or is it to maintain some resemblance of .NET Framework's ASP.NET?  I'm trying to understand Microsoft's logic in how they decided what should be accessible from a service and what should be included as a member of `HttpContext`.  I've searched through the documentation, and I can't find a statement of how Microsoft made this determination.

I've never opened an issue in this repository, so I apologize if I did something incorrectly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hello @wessleym. This looks like a question for the product unit, and the button for _This product_ at the bottom of the topic takes readers to content for opening an issue for the product unit. If something comes out of an issue there that requires an update in the documentation, we can re-open this issue and act accordingly.

**Comment by wessleym** [comment]
@serpent5, since this was just a question that I expected find in the documentation, I thought this would be the best place to post it.  I'm sorry for the trouble, and thank you for your time.  I've now reposted this in the aspnetcore repository issues.
