### ISSUE TITLE
Use Startup with the new minimal hosting model provides the following bonus

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25544]
To the section [Use Startup with the new minimal hosting model](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#use-startup-with-the-new-minimal-hosting-model)
add the pros/cons from [this comment](https://github.com/dotnet/sdk/issues/19672#issuecomment-921229903)

There's some added bonus:

No more reflection magic to call the Startup class (less magic)
You can write async code because you control the call into the Startup class
You can write code that interleaves ConfigureServices and Configure
The Startup class can be internal
The only downside is that if you want to inject a dependency into Configure, you need to manually resolve the service in Program.cs. That seems like a small price to pay for the other pros listed.

@serpent5  is this worth doing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 59731](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59731)

**Comment by serpent5** [comment]
> @serpent5 is this worth doing?

Yes, I think so.
