### ISSUE TITLE
Inconsistent diff sample for appsettings

### ISSUE THREAD

**Issue by baseTwo** [dotnet/AspNetCore.Docs#25550]
The bullet (below) mentions that |Microsoft.Hosting.Lifetime| should be removed from the appsettings, but the diff example underneath shows erroneously that "Microsoft":"Warning" should be removed too

* `"Microsoft.Hosting.Lifetime": "Information"` was removed from both `appsettings.json` and `appsettings.Development.json`:

```diff
- "Microsoft": "Warning", <---- This should be removed
- "Microsoft.Hosting.Lifetime": "Information"
+ "Microsoft.AspNetCore": "Warning"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wadepickett  can you test this? I think the diff is correct but the wording is not completely accurate.

**Comment by wadepickett** [comment]
@Rick-Anderson.  Yes, `"Microsoft.AspNetCore": "Warning"` is the new default in the templates. It replaces the previous defaults of:
`"Microsoft": "Warning",`
`"Microsoft.Hosting.Lifetime": "Information`

Specifying "Microsoft.AspNetCore": "Warning" instead is about namespace level control for log level.  It still allows all the information level messages from the `Microsoft` namespace such as `Microsoft.Entity FrameworkCore`, while keeping `Microsoft.AspNetCore` at a level of "Warning" or higher.

As you suggest, the explanation needs help.  In the topic, I don't think we want to give the message that `Microsoft.Hosting.Lifetime` has to be removed and replaced when migrating an app. You don't have to as far as I can see and it will build, run and log.  Instead, I think I need to explain you can take advantage of log level settings that allow for more control at the namespace level.  More of a best practice of being more explicit about intent, or a preference of simply wanting more control at a namespace level, as opposed to being actually required for migration, I think.  

I will verify with the dev team what the messaging should be for this.
