### ISSUE TITLE
I need to clean and generate a new certificate every time

### ISSUE THREAD

**Issue by ParsaGachkar** [dotnet/AspNetCore.Docs#25583]
I need to clean and generate a new certificate every time I want to switch between projects? I don't think this is a real solution!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf7806c-d9e4-1811-3308-b5efb6f159f0
* Version Independent ID: 2117dfa1-9e6d-2bc2-2348-e792f3c81806
* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/docker-compose-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ravipal
* Microsoft Alias: **ravipal**

**Comment by Rick-Anderson** [comment]
@ParsaGachkar  I think that's beyond the scope of this article.
