### ISSUE TITLE
App startup in ASP.NET Core

### ISSUE THREAD

**Issue by irsharp23** [dotnet/AspNetCore.Docs#25582]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by irsharp23** [comment]
Does this just apply to ASP.NET Core Razor apps?
The project team I am working with is accomplishing a major project(combining multiple standalone apps) under one overarching database and interface.
When I attempt to apply this article to what I'm working on, our environment cannot handle it.
After I enter the first line:

var builder = WebApplication.CreateBuilder(args)

I attempt the next two lines.

Adding ".Services" after builder results in an error:

"...does not contain a definition for "Services..."

**Comment by irsharp23** [comment]
Our current environment is ASP.NET Core MVC...not yet ASP.NET Core RazorPages

**Comment by Rick-Anderson** [comment]
Per the doc

<img width="239" alt="image" src="https://user-images.githubusercontent.com/3605364/162494785-681e0867-5888-4159-8619-4cc0aa78c96e.png">

**Comment by irsharp23** [comment]
I saw the article at docs.microsoft.com entitled "Part 5, work with a database in an ASP.NET Core MVC app".., by Rick Anderson & John P. Smith.That article says to include the following  commands:
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorPages();object p = builder.Services.AddRazorPages();builder.Services.AddDbContext<ApplicationDbContext>(options.UseSqlServer(builder.Configuration.GetConnectionString("ApplicationDbContext")));
One possibility is that I need additional assemblies("using" statements)...but if so, I have no idea which ones.
I already have the following:
using ProjectName.Data;using Microsoft.EntityFrameworkCore;using Microsoft.AspNetCore.Builder;using Microsoft.AspNetCore.Mvc;


Sent from Yahoo Mail on Android 
 
  On Fri, Apr 8, 2022 at 12:48 PM, Rick ***@***.***> wrote:   


Per the doc
