### ISSUE TITLE
Azure Static Web Apps missing from list under Host and Deploy

### ISSUE THREAD

**Issue by zackJKnight** [dotnet/AspNetCore.Docs#25591]
In the nav menu for this doc page, Azure Static Web Apps is missing from the list of pages under the Host and Deploy section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb594f-04bf-c4d7-c94b-6cd6d8b12d75
* Version Independent ID: 64e973ac-838d-4459-06b0-4e943bff936e
* Content: [Host and deploy ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you provide a screen shot?

**Comment by zackJKnight** [comment]
![image](https://user-images.githubusercontent.com/8475387/162856627-68546552-e9e7-48fc-912a-410e56b6f99a.png)

**Comment by zackJKnight** [comment]
Oops. I was thinking of this in the context of Blazor WASM. I... don't think Static Web Apps is appropriate in the host and deploy list.
