### ISSUE TITLE
Add new section on dotnet migration for VS Code

### ISSUE THREAD

**Issue by Mwiku** [dotnet/AspNetCore.Docs#25595]
You need to update the Debug folder when migrating from Dotnet 5 to Dotnet 6, otherwise debugging does not work in VS Code.

This is an important step that should be specified in the documentation.

I'm ready to add this section if approved. It will be a minimal section.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
