### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by slaneyrw** [dotnet/AspNetCore.Docs#25594]
Can we please replace, or add, a version that uses TypeScript instead of javascript.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use React with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by serpent5** [comment]
Hi @slaneyrw. Thanks for taking the time to provide feedback.

The ASP.NET Core template for React doesn't include an option for using TypeScript, but the official [Create React App docs](https://create-react-app.dev/docs/adding-typescript/#installation) explains how to add TypeScript to an existing Create React App project.
