### ISSUE TITLE
Need to add `using System;` to {Timestamp}_Inheritance.cs?

### ISSUE THREAD

**Issue by Amondale** [dotnet/AspNetCore.Docs#25592]
[Enter feedback here]
May have missed something in the dense (but generally well written!) docs, but the project wouldn't build until added 'using System;'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is an advanced tutorial. Hopefully we'll have time to look at that.
