### ISSUE TITLE
Add section for updating debugger when migrating (VS Code)

### ISSUE THREAD

**Issue by Mwiku** [dotnet/AspNetCore.Docs#25607]
[When migrating from Dotnet 5 to Dotnet 6 the debugger in VS Code stops working

I believe the steps to make the debugger work again should be specified in the documentation because debugging is a core part of a developer's workflow.

I can add the section if approved]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's changed?
Can you outline steps here?

**Comment by Mwiku** [comment]
When you migrate to Dotnet 6, the following line in the launch.json has to be updated to reflect the current framework in use. Otherwise, the Debugger points to the old framework which renders it non-functional.
```
// If you have changed target frameworks, make sure to update the program path.
 `"program": "${workspaceFolder}/bin/Debug/net6.0/xx.dll",`
```

**Comment by Rick-Anderson** [comment]
What template generates a `launch.json` file? TFM is not specified in `launchSettings.json`

**Comment by Mwiku** [comment]
@Rick-Anderson, The launch.json file is generated by the VS Code debugger and it resides in the ".vscode" directory.

In the figure attached, I've highlighted the launch.json file and the directory which is used by the debugger for debugging an application(i.e in debug mode).

![vscode_launch_debugger](https://user-images.githubusercontent.com/10756213/163399884-7c5179bd-1eb0-4d48-9c06-0b9445ea1187.png)

**Comment by Rick-Anderson** [comment]
@serpent5  please review. AFAIK, we've never had this in previous migration guides.
