### ISSUE TITLE
appsettings Urls takes precedence over ASPNETCORE_URLS in 6.0.4

### ISSUE THREAD

**Issue by Hoffs** [dotnet/AspNetCore.Docs#25626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using aspnet 6.0.4 runtime, precedence of appsettings.json `Urls` and `ASPNETCORE_URLS` seems to be different compared to previous versions. Specifying `ASPNETCORE_URLS` environment variable does not override the url provided in appsettings.json `Urls` property. Before 6.0.4, `ASPNETCORE_URLS` would have been used over `Urls` in appsettings.json .

I would assume that the order that these settings are overriden in is the same as for regular settings: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#default-configuration 

Based on those, environment variables are applied after appsettings.

I am guessing this is related to https://github.com/dotnet/aspnetcore/pull/39836 which meant to fix in-code overriding of any configuration value. Also, while that issue is tagged with 6.0.3, based on comment https://github.com/dotnet/aspnetcore/issues/40614#issuecomment-1067397572 it looks like it was shipped as part of 6.0.4, which is a bit confusing.

### Expected Behavior

`ASPNETCORE_URLS` is used instead of appsettings.json `Urls`.

### Steps To Reproduce

- Create new project `dotnet new webapi`
- Modify `appsettings.json` by adding `"Urls": "http://*:5300/"`
- Set env var `export ASPNETCORE_URLS="http://*:5200/"`
- `dotnet run`

```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5300
```

***@Rick-Anderson EDIT following lines***

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by nobugsincode** [comment]
Hm, it's interesting. I have my app running in Docker with `dotnet/aspnet` as a base image which sets `ASPNETCORE_URLS=http://+:80` but the app is running on port 5000 instead. I don't have any Urls set in the app config. So seems like Docker images now should use `URLS` instead of `ASPNETCORE_URLS`? I've noticed this after app update to 6.0.4. So it's no longer run on port 80 inside Docker container but on port 5000.
