### ISSUE TITLE
Chrome / iOS support (or lack of) should be more explicitly stated

### ISSUE THREAD

**Issue by kgkayak** [dotnet/AspNetCore.Docs#25640]
Why do I need to read between the lines to get that Blazor is not supported for Chrome running on iOS.  This should be explicitly stated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7957ff6-5b09-31dd-17dd-2bf3660a8ebd
* Version Independent ID: b03c3cec-a3de-d563-d0f8-45fabfb39758
* Content: [ASP.NET Core Blazor supported platforms](https://docs.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kgkayak ... I think it is by virtual of its absence from the supported list. The guidance states that ...

> For Blazor Hybrid apps, we test on and support the latest platform web view control versions:

... without listing Chrome on iOS. Management's intention isn't to list every browser that isn't supported when the better approach (a short list) is for what is supported.

However, there might be updates coming in this area. I'll ping internally to ask and get back to you here.

**Comment by kgkayak** [comment]
What makes it vague is the "including Android" part.  So Chrome is supported on some base set of platforms and then the "including Android" extends that to Android.  Only by reading the previous line about Safari can I infer that the base set of platforms does not include iOS.

**Comment by guardrex** [comment]
Sorry ... I thought you were talking about Hybrid. I'm trying to do *THREE things simultaneously here*, and that usually ends up being bad. I see ur asking about the Blazor WASM/Server piece now.

Sure, let's see what management want to do with it. They supplied this content, and they'll need to address your request and tell us exactly what they'd like to do. We must proceed carefully here in stating what is and isn't supported ... legal issues exist, for example.

**Comment by kgkayak** [comment]
I get your point about just listing what IS supported and not trying to list all the NOT supported combinations.  What is missing from listing what IS supported is a definition of the base set of platforms so that when "including Android" is stated, we know what Android is being included with.

**Comment by danroth27** [comment]
@kgkayak What issues are you hitting with Blazor in Chrome on iOS?

**Comment by kgkayak** [comment]
The issue is with keeping an open connection.  We are getting frequent Reloading events.  This is with the window staying in the foreground and only a few seconds of idle time.

**Comment by danroth27** [comment]
@kgkayak It sounds like this is a Blazor Server app then, correct? Can you verify if the app is successfully connecting using WebSockets or if it is falling back to a different transport? And just to verify, the app does work correctly using Safari *on the same device*, correct?

**Comment by guardrex** [comment]
@kgkayak ... Can you respond to @danroth27's question :point_up: ... or (with @danroth27's approval here) can you open a product support issue for the 'frequent Reloading events" on the [PU repo](https://github.com/dotnet/aspnetcore/issues) so that this can focus on the doc?

@danroth27 ... For the doc, one thing that we could do (if it's correct) is remove the qualifiers.

Go from the current ...

> Apple Safari, including iOS
> Google Chrome, including Android
> Microsoft Edge
> Mozilla Firefox

... to just ...

> Apple Safari
> Google Chrome
> Microsoft Edge
> Mozilla Firefox

I'd like to close this issue out soon with either a PR or as a `won't-fix` issue, if possible to determine what should be done at this point. 👂

**Comment by mkArtakMSFT** [comment]
There are too many browsers available on iOS sharing the Safari WebView. Hence the functionality should be the same. @kgkayak do you observe the issue with Safari too?

**Comment by guardrex** [comment]
We have PU feedback now on how to address this ...

> ... remove the platform qualifiers from the table.
>
> To clarify that we support both mobile and desktop browsers, we can amend the sentence about the table to say "…are supported in the browsers shown in the following table on both mobile and desktop platforms."
