### ISSUE TITLE
Blazor Hybrid WinForms sample code not working

### ISSUE THREAD

**Issue by rod-mac** [dotnet/AspNetCore.Docs#25647]
[Can't run the sample code as I get an error from the Program.cs file as follows: 

System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddWindowsFormsBlazorWebView' in the application startup code.
  Source=Microsoft.AspNetCore.Components.WebView.WindowsForms
  StackTrace:
   at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager..ctor(WebView2 webview, IServiceProvider services, Dispatcher dispatcher, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String hostPageRelativePath, Action`1 urlLoading)
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.StartWebViewCoreIfPossible()
   at Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager.WebView2WebViewManager(Microsoft.Web.WebView2.WinForms.WebView2, System.IServiceProvider, Microsoft.AspNetCore.Components.Dispatcher, Microsoft.Extensions.FileProviders.IFileProvider, Microsoft.AspNetCore.Components.Web.JSComponentConfigurationStore, string, System.Action<Microsoft.AspNetCore.Components.WebView.UrlLoadingEventArgs>)
    Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.StartWebViewCoreIfPossible()
    Microsoft.AspNetCore.Components.WebView.WindowsForms.BlazorWebView.OnCreateControl()
    System.Windows.Forms.Control.CreateControl(bool)
    System.Windows.Forms.Control.CreateControl(bool)
    System.Windows.Forms.Control.CreateControl()
    System.Windows.Forms.Control.WmShowWindow(ref System.Windows.Forms.Message)
    System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message)
    System.Windows.Forms.ScrollableControl.WndProc(ref System.Windows.Forms.Message)
    System.Windows.Forms.ContainerControl.WndProc(ref System.Windows.Forms.Message)
    ...
    [Call Stack Truncated]

The code in this file is:        

namespace WinFormsBlazor
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        /// 
     
        [STAThread]
        static void Main()
        {
            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
            ApplicationConfiguration.Initialize();
            Application.Run(new Form1());
        }
    }
}

]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-gb/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @rod-mac ... Thanks for the report! **_Yes!_** They made a change for the release last week ... that they didn't tell the doc guy about! 😢. I even asked them if there were any other changes, but they didn't say so. There was nothing in the blog post on this. I suspect that in addition to this change that I'll need to check on the WPF tutorial, too. I know the MAUI one is ok, as we made updates to that one for RC1.

I ran the WinForms app in the original form, too, following the guidance and received the same result that you did ...

<img width="519" alt="Capture" src="https://user-images.githubusercontent.com/1622880/163719328-739a0d4d-69af-4602-bbeb-cf2ca2df1f68.PNG">

The change that they made is in `Form1.cs`. They went from ...

```csharp
services.AddBlazorWebView();
```

... to ...

```csharp
services.AddWindowsFormsBlazorWebView();
```

If you make that change, you should be able to get it running ...

<img width="415" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/163719352-277efa1c-c582-4170-af8d-92e28ae05da2.PNG">

I'm going to put in an 🚑🚒🚓 **_emergency patch_** 🚑🚒🚓 on the tutorial right now, and it will go live within perhaps 20 minutes.

Leave this issue open, as it will close automatically in a few minutes after the update goes in.

Thanks again for the report, @rod-mac! 🎸
