### ISSUE TITLE
Seems like there are a lot of steps missing

### ISSUE THREAD

**Issue by smadgerano** [dotnet/AspNetCore.Docs#25650]
[EDIT by guardrex to add the metadata manually.]

I'm utterly baffled by this - https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly

The document starts off saying "Downloading the tutorial's sample chat app isn't required for this tutorial. The sample app is the final, working app produced by following the steps of this tutorial." There are no further prerequisites mentioned.

After creating the client project and importing the library it states "In the BlazorWebAssemblySignalRApp.Server project, create a Hubs (plural) folder and add the following ChatHub class (Hubs/ChatHub.cs):"

....where? What project? We've not covered setting anything up for the server yet, all we've done is create a client porject and added the library. Does it have to be an MVC project, can I use Razor Pages, surely we need to download some sort of SignalR server library to add to it? Or is the tutorial just for craeting a signalr server inside a webassembley application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

btw --- It will be *ME* ... @guardrex ... who responds to it, but for tracking purposes please re-open the issue using our process. We use the metadata added to your issue to track work here.

**Comment by guardrex** [comment]
I was out for a bit ... back now ... btw ... don't forget Step 4 there. Make sure that you select for a **ASP.NET Core Hosted** template option. If you're using the CLI to create the app, you pass the `-ho` or `--hosted` option to the `dotnet new` command. It sounds to me like you merely missed Step 4. Without selecting for a hosted WASM app, you won't see **`Client`** and **`Server`** projects in the solution, which is perhaps why you were confused in that next step.

**Comment by guardrex** [comment]
I think I'll call that out. Why not? I'll have an added step there that says to confirm that **`Client`** and **`Server`** projects appear in the solution. If not, I'll say to start over and create a new app.

**Comment by smadgerano** [comment]
Just a quick note to say thanks - yes, I ws miossing step 4, for some reason I was completely blind to it. Thanks for the help and pointer, appreciate it :)
