### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ParaSwarm** [dotnet/AspNetCore.Docs#25653]
This link on the page is broken.

Changes the GetProduct action's return type from IHttpActionResult to ActionResult<Product>. For more info, see [Controller action return types](https://docs.microsoft.com/en-us/aspnet/web-api/action-return-types).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/webapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @ParaSwarm ... I'll see about patching that up.

**Comment by guardrex** [comment]
Looks like they moved it to ...

https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-6.0

... without placing a redirect. I'll fix it now.

**Comment by ParaSwarm** [comment]
@guardrex  Wow, fastest fix ever. Thanks!
