### ISSUE TITLE
Example does not work again. 

### ISSUE THREAD

**Issue by JerryMVC** [dotnet/AspNetCore.Docs#25661]
[EDIT by guardrex to add the metadata. @JerryMVC, please use the **This page** feedback button and form at the bottom of the **English-US** topics to open issues here, which adds metadata to the issue and pings the author automatically.]

Hi boys and girls from Microsoft,
I tried your example in here:

https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0

"b0b88d48-74df-8dc4-446d-121e65b552ab" 

https://github.com/dotnet/AspNetCore.Docs/issues?utf8=%E2%9C%93&q=%22b0b88d48-74df-8dc4-446d-121e65b552ab%22&in=body

but the example BlazorWinForms suffers from errors again:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	RZ10003	Markup, code and block directives are not valid in component imports.		C:\_APP\001 APP Blazor WinForms\WinFormsBlazor\WinFormsBlazor\_Imports.razor	1	

here is complete source code:
https://drive.google.com/file/d/1I8LRD92z7AwQAkw1bgrYiz5Vz4iayd4a/view?usp=sharing

I hope You will repair everything. 

Jerry 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @JerryMVC ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Nevermind, @JerryMVC ... I think I see what happened. I had **_TWO_** spots to update for some changes yesterday. I'll fix those on the PR and ping u in a sec.
