### ISSUE TITLE
Blazor Hybrid: Static files topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25674]
When content is provided in an issue comment here, please remove the PU member assignment and assign the issue to @guardrex 🦖. PU member will be pinged on the PR when it goes up.

```
aspnetcore/blazor/hybrid/static-files.md
```

**Comment by TanayParikh** [comment]
Is the ask here for documentation on how to access absolute file paths on the native file system, for all platforms?

cc/ @danroth27

**Comment by guardrex** [comment]
I wasn't told what the content would be.

**Comment by TanayParikh** [comment]
Oh is this to be a MAUI version of https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?

**Comment by guardrex** [comment]
If so on ...

> MAUI version

@danroth27 ... general ❓ ... is the intention is to circle around later to address any **_code example deltas_** for WPF and WinForms? I understand that the concepts will the same (or similar), but devs prefer to see doc examples for the framework that they're working with. We found that out *PDQ* when RP was released and the docs were mostly MVC-based.

**Comment by danroth27** [comment]
The idea behind this topic is that static files are a bit different in Blazor Hybrid apps. In web apps static files are deployed to the server and made available over HTTP. In a Blazor Hybrid app, static files are deployed into the app as static assets. How those static assets get handled is different on every platform. From what I understand .NET MAUI does some work to try to abstract this with their MAUI assets stuff. Then there's the question of how should you refer to static assets in a Blazor Hybrid app. From what I understand you simply use a relative path, similar to what you would do in a web app. Maybe we also need to say something about the base address for the Blazor Hybrid app - not sure. So this doc is about explaining about how static assets in a native app are similar & different than in a web app, and link to the appropriate .NET MAUI content on static asset handling.

**Comment by TanayParikh** [comment]
For Blazor Hybrid with WinForms & WPF, we'll be using the native `Resources` capability to stay consistent with platform standards. Steps are as follows:

1. Open your WPF/WinForms application, and setup the Blazor Web View (insert crosslink if required to initial setup instructions)
2. Create an asset you'd like to use in your application. For instance, I created a `Resources` directory, and placed `MyAsset.txt` within it, containing `This is some sample text within my asset.`.
3. Right click on your project, select `Properties` and then navigate to `Resources > General`.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/14852843/167964391-08821a44-2561-4173-9256-9888ba5c6857.png">

4. Select `Create or open assembly resources`
5. Open the `Strings` dropdown, and select `Files`

<img width="561" alt="image" src="https://user-images.githubusercontent.com/14852843/167964288-f25217f8-1f4b-4c02-8261-28d5875fb424.png">

6. Select `Add Resource`, and then select `MyAsset.txt` created earlier. You should see the asset reflected in your resources:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/14852843/167964354-98402104-4474-43d7-a69b-82fa28251abb.png">

7. Go back to your `*.razor` component and paste the following snippet, replacing `INSERT_PROJECT_NAME_HERE` with your project name.

```razor
@using System.Resources

@AssetText

@code {
    public string AssetText { get; set; } = "Loading asset...";

    protected override void OnInitialized()
    {   
        var resources = new ResourceManager(typeof(INSERT_PROJECT_NAME_HERE.Properties.Resources));
        var assetObject = resources.GetObject("MyAsset");
        if (assetObject is null)
        {
            throw new KeyNotFoundException("'MyAsset' could not be found");
        }

        AssetText = (string)assetObject;
    }
}
```

8. Run your application, and you should see the content of your `MyAsset.txt` file:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/14852843/167964731-cd01cea5-9e1b-4f32-8756-fa5e2bccf1cf.png">

**Comment by TanayParikh** [comment]
> For Blazor Hybrid MAUI, we'll be using the `MauiAsset` Build Action, as detailed [here](https://github.com/dotnet/maui/pull/4367), I'm confirming whether MAUI already has / will have official docs for this. If so, we'll just do some cross-linking.

Here's the Blazor Hybrid specific sample:

```
@using System.IO
@using Microsoft.Maui.Storage

<button @onclick="LoadMauiAsset">Load Asset</button>

<br />


@Contents

@code {
    public string Contents = "Loading...";
    async Task LoadMauiAsset()
    {

        using var stream = await FileSystem.OpenAppPackageFileAsync("AboutAssets.txt");
        using var reader = new StreamReader(stream);

        Contents = reader.ReadToEnd();
    }
}
```

This reads the default `Resources/Raw/AboutAssets.txt` file part of the `maui-blazor` template.

Complete instructions in how to use `MauiAsset` are summarized in [this table](https://github.com/dotnet/maui/pull/4367#issue-1116915145) and should be part of the MAUI general documentation (ie. not repeated in Blazor Hybrid docs).

**Comment by guardrex** [comment]
@TanayParikh ... WRT WinForms/WPF: I understand that taking the Resource Manager route would be useful in localized content situations, but what about the proverbial *low-hanging fruit* approach for loading static assets for Razor components in the normal way out of `wwwroot`? I'm just curious ... and reiterating my minimal experience with desktop/mobile.

1. Drop a text file and an image into `wwwroot`:

   `data.txt`:

   ```text
   This is test text from data.txt.
   ```

   The `data.txt` "Content" file must be marked to **Copy if newer** for ...

   ```xml
   <ItemGroup>
     <Content Update="wwwroot\data.txt">
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </Content>
   </ItemGroup>
   ```

   `yj.png`:

   ![yj](https://user-images.githubusercontent.com/1622880/168810400-6ca2b531-6de4-4fff-a89d-f2997ed2b8b9.png)

   For whatever reason ... apparently ... images don't require marking **Copy if newer**.

1. A component can reference these like the following. Using the `Counter` component just because it's handy in my test app ...

   ```razor
   <h1>Counter</h1>

   <p>@@assetText: @assetText</p>

   <p>
       <img alt="1991 Jeep Wrangler YJ" src="/yj.png" />
   </p>

   <p>Current count: @currentCount</p>

   <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

   @code {
       private int currentCount = 0;

       private void IncrementCount()
       {
           currentCount++;
       }

       public string assetText = "Loading asset...";

       protected override async Task OnInitializedAsync()
       {   
           try
           {
               using (var sr = new StreamReader("wwwroot/data.txt"))
               {
                   assetText = await sr.ReadToEndAsync();
               }
           }
           catch (FileNotFoundException ex)
           {
               assetText = ex.Message;
           }
       }
   }
   ```

Output ...

![Capture](https://user-images.githubusercontent.com/1622880/168813903-50c4af0e-17ff-49d7-b6fc-87ba701a29a9.PNG)

I also published this app and ran the executable out of the `publish` folder. That worked, too.

Is this valid? ... at all?? ... perhaps, as a **_Razor components only_** approach??? ... but I kind'a wonder if that isn't the only point of covering anything here for static assets/files. Aren't the docs for localized resources (i.e., Resource Manager) fully available elsewhere (e.g., WPF 'how to localize' ... https://docs.microsoft.com/dotnet/desktop/wpf/advanced/how-to-localize-an-application)?

BTW ... valid approach or not ... do you know why the text file in `wwwroot` (`data.txt`) required the **Copy if newer** gesture but the image file (`yj.png`) didn't? I expected to NOT need to mark anything in `wwwroot` given the direction of the tutorial with the stylesheet and `index.html` file.

**Comment by guardrex** [comment]
Hummmm 🤔 ... IntelliSense can't find `WinFormsBlazor2.Properties` in `var resources = new ResourceManager(typeof(WinFormsBlazor2.Properties.Resources));`.

**Comment by guardrex** [comment]
... and I think we can avoid the hoops and get the assembly with *ye olde `this`* ...

```csharp
var resources = new ResourceManager("WinFormsBlazor.Form1", this.GetType().Assembly);
```

**Comment by guardrex** [comment]
WPF mirrored your code as ...

```razor
@using System.Resources

<p>@@dataResourceText: @dataResourceText</p>

@code {
    public string dataResourceText = "Loading resource ...";

    protected override void OnInitialized()
    {   
        var resources = 
            new ResourceManager(typeof(WpfBlazor.Properties.Resources));
        dataResourceText = resources.GetString("Data") ?? "'Data' not found";
    }
}
```

**Comment by guardrex** [comment]
@TanayParikh ... Ok ... good start today. I have the WinForms and WPF bits laid out in my draft locally. Besides my **_RAMBLINGS ON HERE ☝️_** 🙈 , can you let me know if my [earlier remarks :point_up:](https://github.com/dotnet/AspNetCore.Docs/issues/25674#issuecomment-1128859254) about the Razor component-only approach with `wwwroot` static assets (with the Jeep image and text file) is valid/sane 😵? If so, I'll add it to a separate section at the end of the topic as an alternative (Blazory) approach.

On Wednesday morning, I'll add the .NET MAUI piece to the draft and polish the bits further from this morning. I plan to put the PR up tomorrow and ping u for review, but I might need one more day.

**Comment by TanayParikh** [comment]
> WRT WinForms/WPF: I understand that taking the Resource Manager route would be useful in localized content situations, but what about the proverbial _low-hanging fruit_ approach for loading static assets for Razor components in the normal way out of `wwwroot`?

> Is this valid? ... at all??

> If what I hacked up is valid tho, should it be in a separate section further down the topic's content?

Yep totally valid, we can definitely include this approach as well. Going the Resource route is just another option (as resources don't necessarily *have to* be used with localization (but often are).

> BTW ... valid approach or not ... do you know why the text file in wwwroot (data.txt) required the Copy if newer gesture but the image file (yj.png) didn't?

Not really sure why that would be.
