### ISSUE TITLE
Blazor Hybrid: Reuse Razor components topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25675]
When content is provided in an issue comment here, please remove the PU member assignment and assign the issue to @guardrex 🦖. PU member will be pinged on the PR when it goes up.

```
aspnetcore/blazor/hybrid/reuse-razor-components.md
```

**NOTE TO SELF**:

> This (referring to the **_Access native platform features topic_** topic) is covered by the section *Platform specific code on Blazor Maui applications* in this [PR].

**Comment by javiercn** [comment]
We should point out to the Podcasts sample

**Comment by guardrex** [comment]
@javiercn ... I need the link to the podcast that you mentioned :point_up:.
