### ISSUE TITLE
Blazor Hybrid: Globalization and localization topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25679]
When content is provided in an issue comment here, please remove the PU member assignment and assign the issue to @guardrex 🦖. PU member will be pinged on the PR when it goes up.

```
aspnetcore/blazor/hybrid/globalization-localization.md
```

**Comment by mkArtakMSFT** [comment]
We believe there is no MAUI-specific work to be documented here. The WebView2 has a Language setting which is set automatically and then the usual ASp.NET Core localization mechanism using IStringLocalizer can be used within the Blazor app to provide localized content.

@Redth do you know whether the assumption above is correct? Does MAUI set the localization info on the WebView automatically?

**Comment by Redth** [comment]
@rmarinho  or @PureWeen thoughts on this one?

**Comment by Eilon** [comment]
We have some notes in this issue from an earlier investigation: https://github.com/dotnet/maui/issues/2532#issuecomment-1026378294
