### ISSUE TITLE
Add documentation in v6 config for `AddEndpointsApiExplorer`

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#25685]
Please add an explanation for [this bit](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=netcore-cli#add-and-configure-swagger-middleware):
````cs
builder.Services.AddEndpointsApiExplorer();
````

It was not needed in v5.

It is the source of confusion, as see in [this SO post](https://stackoverflow.com/q/71932980/9971404).

It is especially confusing when used in conjunction with the "ASP.NET API Versioning" [library](https://github.com/dotnet/aspnet-api-versioning).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by lakeman** [comment]
Particularly since this example includes `.AddControllers()`, which already calls `.AddApiExplorer()`. I don't see anywhere in any documentation the answers to the following questions;
- Why is `.AddEndpointsApiExplorer()` required in v6?
- Why is `.AddApiExplorer()` no longer sufficient?

**Comment by lonix1** [comment]
For whomever works on this - note @commonsensesoftware provided detailed information in an [SO answer](https://stackoverflow.com/a/71933535/9971404). It can help when editing this doc.
