### ISSUE TITLE
Conversion bugs after changing model to DTO in Creating ASP.NET API (.NET Core) tutorial

### ISSUE THREAD

**Issue by Faronnnn** [dotnet/AspNetCore.Docs#25684]
[Enter feedback here]

In last section about using DTO model there are 3 bugs of conversion:
Severity	Code	Description	Project	
Error	CS1503	Argument 1: cannot convert from 'TodoApi.Models.TodoItemDTO' to 'TodoApi.Models.TodoItem'	TodoApi	

At the end I even tried to copy the whole file text in case I made some typos but unfortunately it wasn't made on my side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @Faronnnn. Thanks for taking the time to provide feedback.

The code in the article is taken from the [sample project](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/first-web-api/samples/6.0/TodoApiDTO), which builds without issue. Check your code against that project to see where the difference lies.
