### ISSUE TITLE
Blazor Hybrid: Security and Identity with AAD topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25681]
**_DON'T ASSIGN YET: Initial assignment will be made by PU management shortly._**

When content is provided in an issue comment here, please remove the PU member assignment and assign the issue to @guardrex 🦖. PU member will be pinged on the PR when it goes up.

```
blazor/hybrid/security/azure-active-directory.md
```

**Comment by mkArtakMSFT** [comment]
We don't plan to document Azure AD specific authentication in Blazor / MAUI docs. We have a separate issue tracking integration of Blazor auth with MAUI which is here: https://github.com/dotnet/maui/issues/2529
