### ISSUE TITLE
Update page for ASP.NET Core 6

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/AspNetCore.Docs#25694]
Update the page for ASP.NET Core 6 which uses nullable reference types.

The code:
```cs
[BindProperty]
public Customer Customer { get; set; }
```
Will complain that:

    CS8618	Non-nullable property 'Customer' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Nullable reference types (NRTs) and .NET compiler null-state static analysis](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#review-breaking-changes)

See [Fix the warning messages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio#fix-the-warning-messages) in the Razor Pages tutorial for fixing NRT warnings the scaffolder generates.

**Comment by vanillajonathan** [comment]
It would be more useful if the documentation reflected the best practices for how it should be idiomatically implemented.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  are you interested in fixing this? You need two more commit to break into the [top 20](https://github.com/dotnet/AspNetCore.Docs/graphs/contributors)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson sure! But I guess it is closed now. Please feel free to tag me anywhere you need my assistance 😃

**Comment by Rick-Anderson** [comment]
Fixed in #25721
