### ISSUE TITLE
Integration testing samples missing for v6

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#25703]
The v6 document references the [samples](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests/samples/3.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/RazorPagesProject.Tests.csproj#L4) on the repo, which are for v3.

Upgrading an integration testing project from 5 to 6 is quite hard. Does anyone have a working sample for 6?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
Hi @lonix1. The work for updating this article to include 6.0 examples is already being tracked in #23543.
