### ISSUE TITLE
The Client can't seem to invoke the methods on the server even after passing the correct name of the methods

### ISSUE THREAD

**Issue by KCMicheal** [dotnet/AspNetCore.Docs#25719]
Hi, Sorry I'm having issues with the front end not being able to call the method on the server to retrieve message history even after authentication is approved.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
