### ISSUE TITLE
Add "Add claims to Identity using IUserClaimsPrincipalFactory<ApplicationUser>" section to Core 6.0 doc

### ISSUE THREAD

**Issue by RickworkGit** [dotnet/AspNetCore.Docs#25714]
[Enter feedback here]
I am using .Net Core 6.0

Copy
"Add claims to Identity using IUserClaimsPrincipalFactory<ApplicationUser>" section from Core 3.1 doc to 6.0 doc

Instead of change ConfigureServices()

In .Net 6, change Program.cs to call class ApplicationUserClaimsPrincipalFactory() :

builder.Services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, ApplicationUserClaimsPrincipalFactory>();

builder.Services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddClaimsPrincipalFactory<ApplicationUserClaimsPrincipalFactory>();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I don't understand the question. Perhaps you could provide links to the sections in the doc and screen shots.

The doc was recently tested for .NET 6 and works.

**Comment by Rick-Anderson** [comment]
I get it. [Add claims to Identity using IUserClaimsPrincipalFactory<ApplicationUser>](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1&tabs=visual-studio#add-claims-to-identity-using-iuserclaimsprincipalfactoryapplicationuser) was dropped from the 6.0 version of the tutorial because it doesn't belong to that doc. It even says so:

Note

This section isn't an extension of the previous tutorial. To apply the following steps to the app built using the tutorial, see [this GitHub issue](https://github.com/dotnet/AspNetCore.Docs/issues/18797).

**Comment by mrukas** [comment]
@Rick-Anderson: 
Can someone explain why this part of the docs has been completely removed? Why isn't this listed anywhere else instead? Isn't this an important part?
I mean, if someone now reads the docs to find information on how to add custom claims he only finds the section about IClaimsTransformation.

IClaimsTransformation does not offer the same functionality as IUserClaimsPrincipalFactory. If you want to resolve additional claims based on the user you receive after login, you have to use IUserClaimsPrincipalFactory.

If you try to do the same with IClaimsTransformation you would need to read the user id from the already build ClaimsPrincipal and query the database again to get the desired informations.
