### ISSUE TITLE
More information for usage in a WebAPI

### ISSUE THREAD

**Issue by OlivierHogue** [dotnet/AspNetCore.Docs#25715]
Is it possible to indicate how to control the serialization behaviors in a Web API, in the goal to allow all derived types of an abstract class to be properly serialized ? I search the internet, and only found solutions involving Media Formatters and Custom Converters, however since the official way of serializing derived types is by simply overloading the Serialize method, I think there could be a simple way to do it for a Web API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@Rick-Anderson Information about this approach to configuring System.Text.Json in a Web API may be worth adding to the response formatting article.

**Comment by Rick-Anderson** [comment]
@brunolins16 please review this sample. Do you agree we should add it to [this doc](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-7.0) ?

**Comment by brunolins16** [comment]
@Rick-Anderson sorry for the delay.

We do have an extensive documentation about creation of polymorphic converter here [Support polymorphic deserialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0#support-polymorphic-deserialization) with System.Text.Json. 

Probably what we can do is add a block pointing to this doc and how to add the converter to the JsonOptions in this section [Configure System.Text.Json-based formatters](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-7.0#configure-systemtextjson-based-formatters-2)

**Comment by brunolins16** [comment]
Also, `Newtonsoft.Json` does the polymorphic serialization [Polymorphic serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?WT.mc_id=DOP-MVP-4039670&pivots=dotnet-6-0#polymorphic-serialization) and [Polymorphic deserialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?WT.mc_id=DOP-MVP-4039670&pivots=dotnet-6-0#polymorphic-deserialization). That might be another option to add the docs.
