### ISSUE TITLE
`appsettings.Development.json` contains no entry for ConnectionStrings - did i miss a step?

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/AspNetCore.Docs#25710]
In the tutorial  `appsettings.Development.json` contains this line
```
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=MyDB-2;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
```
But on my local machine  `appsettings.Development.json` has no entry regarding the  "ConnectionStrings"; only  `appsettings.json` contains this "ConnectionStrings" entry:

```
  "ConnectionStrings": {
    "RazorPagesMovieContext": "Data Source=RazorPagesMovieContext-6ce7ab9c-979e-4a13-bcab-9ed8276c15eb.db"
  }
```
Did i miss a step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
From the article:

> The appsettings.json file is updated with the connection string used to connect to a local database.

The connection string gets added when you scaffold the movie model. Have you completed that step?
