### ISSUE TITLE
Understated comment will break the next section on validation

### ISSUE THREAD

**Issue by IainHoult** [dotnet/AspNetCore.Docs#25726]
At the very end of the instructions it says 
> If all the records in the DB are deleted, the initialize method will seed the DB and include the Rating field.

This looks like a general comment rather than an instruction that must be followed to proceed.  If all records are not deleted the seed data which has been updated to include 'rating' will not be imported into the database, leaving the field empty for all records.  The next section adds validation to the 'rating' field, without having added the new seed data the application throws an exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Part 8, add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Correct
