### ISSUE TITLE
more benefits but no more drawbacks? hmm!

### ISSUE THREAD

**Issue by DickBaker** [dotnet/AspNetCore.Docs#25725]
The first 2 paras contrast server- and client-side architecture, and reasonably state benefits and drawbacks. Subsequent paras add extra benefits but omit any drawbacks. Sorry I don't buy the free-lunch invites. IMHO what is needed is 1. feature grid of each arch with real pro/con including learning curve, 2. 4-quadrant complexity/power and suggestions which tech might/not match each business scenario. just saying!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21671480-fba7-3692-1a20-e71843864b60
* Version Independent ID: 68d5aab0-63ce-de7a-0c56-341c2eef623d
* Content: [Choose an ASP.NET Core UI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback, we'll consider this on the next review.
