### ISSUE TITLE
Minor page improvement - CSS Isolation stylesheet link root instead of relative

### ISSUE THREAD

**Issue by SixOThree** [dotnet/AspNetCore.Docs#25738]
Section [CSS Isolation](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio#css-isolation) mentions adding a link to static asset CSS that is generated. This link should probably have ~/ in front. For example:
`<link rel="stylesheet" href="~/{APP ASSEMBLY}.styles.css" /> `
instead of
`<link rel="stylesheet" href="{APP ASSEMBLY}.styles.css" />`

This way it won't generate a 404 when referenced from Areas (such as Identity).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
A few passing notes on this that might help with the update(s) ...

This is a delta between MVC/RP and Blazor. MVC/RP **_DO_** have a `~/` by default ...

* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/Shared/_Layout.cshtml#L9
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_Layout.cshtml#L9

Blazor, as an SPA, doesn't by default ...

* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorServerWeb-CSharp/Pages/_Host.cshtml#L14
* https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/wwwroot/index.html#L12-L14

> adding a link to static asset CSS that is generated

There might be two more changes to make in regard to 'adding' such a link ...

* The line ...

  > A link to the bundled CSS styles is placed in the app's layout.

  ... is a bit cryptic (i.e., 'placed by who/what?'). It might indicate that this is a default of the project template indicating that the dev shouldn't have to add such a link. The framework won't ever add it, but the dev only needs to do so if they're adding CSS isolation to an app that doesn't use it or if the link is deleted by accident. For example, the Blazor doc does it this way ...

  > The following `<link>` element is added by default to an app created from the Blazor project templates, where the placeholder `{ASSEMBLY NAME}` is the project's assembly name:

  ... and then again referencing the project template to reinforce it before the example as ...

  > The following example is from a hosted Blazor WebAssembly **`Client`** app. The app's assembly name is `BlazorSample.Client`, and the `<link>` is added by the Blazor WebAssembly project template when the project is created with the Hosted option (`-ho|--hosted` option using the .NET CLI or **ASP.NET Core hosted** checkbox using Visual Studio):

  Cross-ref: https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#css-isolation-bundling

* The change should also happen for the example line. From ...

  > `<link rel="stylesheet" href="WebApp.styles.css" />`

  ... to ...

  > `<link rel="stylesheet" href="~/WebApp.styles.css" />`
