### ISSUE TITLE
Wrong namespace documentation of the upgrade guide

### ISSUE THREAD

**Issue by StefanKoenen** [dotnet/AspNetCore.Docs#25735]
The docs are referencing the wrong namespace for IWebHostEnvironment, "[Microsoft.Extensions.Hosting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting)" is used while it should be [Microsoft.AspNetCore.Hosting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.AspNetCore.hosting) .

 (https://github.com/dotnet/AspNetCore/issues/7749)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Fixed by #25736.  Thanks @StefanKoenen.
