### ISSUE TITLE
ASP. NET 6.0: Tutorial: Update related data. Can not add a course on Course page.

### ISSUE THREAD

**Issue by purelengend** [dotnet/AspNetCore.Docs#25737]
I follow this tutorial and have a trouble in customize page course. When i fill the form and click on create button, it won't work because the ModelState.IsValid is invalid. I add a breakpoint and see there are three invalid properties: Department, Enrollments and CourseAssisnments. I also try to run the original scaffolded code and got the same problem. What should i do to fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [Tutorial: Update related data - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data, it's more up to date.

**Comment by purelengend** [comment]
I fixed that by adding ? operator for the invalid properties in Models/Course.cs
