### ISSUE TITLE
new CustomResolver()

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#25745]
Following this page, one cannot determine what is CustomeResolver().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
There is no specific implementation of `CustomResolver` for the purposes of this doc. It is merely an example showing "this is where you would put a custom resolver if you have one". If you read the paragraph above the code we call out where you can learn more about custom resolvers.
