### ISSUE TITLE
InsertIfMissing is not described

### ISSUE THREAD

**Issue by mc0re** [dotnet/AspNetCore.Docs#25748]
[Enter feedback here]
`InsertIfMissing` transform type is not described. Which leaves a question: what else is not described? Maybe you also omitted something like `InsertOrReplace`, which would be nice :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c703c55-7ece-6e0d-2518-50786599530a
* Version Independent ID: 7e68f62c-8c84-e7a5-2a74-201fc60b3036
* Content: [Transform web.config](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/transform-webconfig?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/transform-webconfig.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/transform-webconfig.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
