### ISSUE TITLE
gRPC on macOS workaround is outdated

### ISSUE THREAD

**Issue by marcinjahn** [dotnet/AspNetCore.Docs#25742]
The "Unable to start ASP.NET Core gRPC app on macOS" section is a bit outdated. It relies on the pre .NET 6 style of `Program.cs`.

Here's how I tried to configure it:

```cs
using GrpcGreeter.Services;
using Microsoft.AspNetCore.Server.Kestrel.Core;

var builder = WebApplication.CreateBuilder(args);

// Additional configuration is required to successfully run gRPC on macOS.
// Kestrel does not support HTTP/2 over TLS on macOS.
builder.WebHost.ConfigureKestrel(options =>
{
    // Setup a HTTP/2 endpoint without TLS.
    options.ListenLocalhost(5000, o => o.Protocols =
        HttpProtocols.Http2);
});

// Add services to the container.
builder.Services.AddGrpc();

var app = builder.Build();

// Configure the HTTP request pipeline.
// app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
```

The app starts, however, when I `curl localhost:5000` I get `curl: (1) Received HTTP/0.9 when not allowed`. When I navigate to localhost:5000 from the web browser  I get:

> This page isn't working at the moment
> localhost sent an invalid response.
> ERR_INVALID_HTTP_RESPONSE

How to run gRPC server project (created with `dotnet new grpc` on macOS (M1)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#unable-to-start-aspnet-core-grpc-app-on-macos)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Addressed partially with PR #25783 with an updated 6.0 code example.

However, I will add another PR that clarifies the HTTP/2 endpoint port should reflect the http (not https) appilcationURL in launchSetting.json.   If you accidently use the https URL or do not realize the applicationURL is set randomly when the project is created, you will get an invalid response.
