### ISSUE TITLE
Hot reload does not work

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#25750]
Please see this issue: https://github.com/dotnet/aspnetcore/issues/39073#issuecomment-1044702453

If there are steps missing from this article, please update so that we can use hot reload. It has been out for a while, so it's unexpected that it does not work when running `dotnet watch run` via CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Version Independent ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Content: [.NET Hot Reload support for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/hot-reload.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/hot-reload.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'm 👁️+👂 in case this results in Blazor-specific content updates. As it stands, I have no additional info from the PU beyond what's already been stated in the topic.

**Comment by guardrex** [comment]
This was apparently resolved in the cross-linked issue and in https://github.com/dotnet/aspnetcore/issues/41776.
