### ISSUE TITLE
The tag helper documentation involving Microsoft.AspNetCore.Razor.Tools doesn't look correct

### ISSUE THREAD

**Issue by Rod-in-NM** [dotnet/AspNetCore.Docs#25756]
It looks to me like there's an error in the [documentation at this page](https://docs.microsoft.com/en-US/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0#intellisense-support-for-tag-helpers). It says there:

> When you create a new ASP.NET Core web app in Visual Studio, it adds the NuGet package "Microsoft.AspNetCore.Razor.Tools"

I looked at a recent ASP.NET MVC Core I created, based upon .NET 6. It does not reference Microsoft.AspNetCore.Razor.Tools. I then looked at NuGet.org. According to NuGet.org that assembly is in preview4-final. Since I don't see Intellisense when working with tag helpers I'm wondering if there's a different NuGet package I should include?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-US/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You're correct. I think that changed in .NET 3
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rod-in-NM** [comment]
@Rick-Anderson, I've forked the page project, made the edit, committed it and have created a PR. Please review and give me any feedback, so I can make the necessary changes. 

Thank you!
