### ISSUE TITLE
show how asp-append-version can work in directories other than wwwroot

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25760]
Then link to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0#serve-files-from-multiple-locations

* Add below [Tag helper initializers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0#tag-helper-initializers)
* [Image TH](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/image-tag-helper?view=aspnetcore-6.0)

See #25743

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09866f1-f286-b98c-1073-e402a10f35d3
* Version Independent ID: 18653de6-49b6-3f75-0392-b5eba55145ad
* Content: [Image Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/image-tag-helper?view=aspnetcore-6.0#asp-append-version)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by dreamer820** [comment]
webroot
