### ISSUE TITLE
Immutable/mutable & known/unknown C# Guide cross-links

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#25776]
Tracking on https://github.com/dotnet/docs/issues/29187 for cross-link opportunities ... or perhaps a bit of text that makes sense to use for the line ...

> * All of the parameters are known immutable types or any \[primitive type](/dotnet/api/system.type.isprimitive) that hasn't changed since the previous set of parameters were set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8201d0b-a6c4-7656-a8d9-9ae1fee26d10
* Version Independent ID: 27742f9a-95e5-a2d0-aa54-0ef24cad3d2a
* Content: [ASP.NET Core Razor component rendering](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/rendering?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/rendering.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/rendering.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
LICK'D IT 🐮👅 ... I mustn't take any personal credit, of course, it's entirely due to Bill Wagner's influence!!! 🤣 ... to misquote a Tom Baker Dr. Who line! 😄

@szalapski ... Bill says to use the following ...

> All of the parameters are [verifiably immutable types](/dotnet/csharp/language-reference/builtin-types/unmanaged-types) or any [primitive type](/dotnet/api/system.type.isprimitive) that hasn't changed since the previous set of parameters were set.

... so I'll shoot that in right now.

**Comment by szalapski** [comment]
That still seems wrong, as those lists don't include string or DateTime.

**Comment by guardrex** [comment]
Ask Bill these questions on the issue that I opened over there ...

https://github.com/dotnet/docs/issues/29187
