### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by erikgassler** [dotnet/AspNetCore.Docs#25785]
[Enter feedback here]
Followed the instructions. Where is `blazorWebView1` coming from? VS is giving me an error that it can't find this. I see no reference to this name anywhere else in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
You probably accidently dragged over a normal `WebView` instead of a `BlazorWebView` from the Toolbox.

Look again and see if that's what happened. If so, leave this open because I think the topic can say that these two are SxS in the Toolbox and one has to be careful to get the right one.

`blazorWebView1` is what VS is going to auto-name it when you drag it over.

**Comment by guardrex** [comment]
In the image ...

![image](https://user-images.githubusercontent.com/1622880/166169577-9d776050-a6ed-449a-98c1-449516836edb.png)

The `WebView2` above it is the **_wrong one_**. In fact, I need to double-check the next image after that one that shows the control as "WebView2." That doesn't look right ... **_BUT_** ... we are in *preview* ... so it wouldn't surprise me either way that the image is incorrect (*bad doc!* 😄) --OR-- the control actually says "WebView2" after it's dragged over (*bad framework!* 😄). We're working the 🐞 out of these preview docs right now before final release, which is coming soon.

**Comment by erikgassler** [comment]
> You probably accidently dragged over a normal `WebView` instead of a `BlazorWebView` from the Toolbox.
> 
> Look again and see if that's what happened. If so, leave this open because I think the topic can say that these two are SxS in the Toolbox and one has to be careful to get the right one.
> 
> `blazorWebView1` is what VS is going to auto-name it when you drag it over. The update can call this out as a sub-step there so that devs know that they have the right one in the form.

This was the issue, I selected the wrong WebView component. I deleted the old one and added the correct one and the code then worked.

**Comment by guardrex** [comment]
Ok ... yeah ... I think that's something that I can fix here and in the other two tutorials with a bit more text and a red :x: on the regular `WebView`.

Thanks for writing in. Leave this issue open. It will close when the PR merges.
