### ISSUE TITLE
Reference to obsolete RNGCryptoServiceProvider

### ISSUE THREAD

**Issue by StalaK** [dotnet/AspNetCore.Docs#25786]
The hashing passwords references the `RNGCryptoServiceProvider` class which is marked as obsolete. It looks like this should now reference the `RandomNumberGenerator` class instead [Related issue](https://github.com/dotnet/runtime/issues/40169)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
And update to .NET 6
