### ISSUE TITLE
Message template should be compile time constant

### ISSUE THREAD

**Issue by ivog** [dotnet/AspNetCore.Docs#25790]
In Chapter "[Create Logs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#create-logs)" the example uses this:

        Message = $"About page visited at {DateTime.UtcNow.ToLongTimeString()}";
        _logger.LogInformation(Message);

It would be better if the example would use:        
      
        string messageTemplate = "About page visited at {PageVisitDate}";
        _logger.LogInformation(messageTemplate, DateTime.UtcNow.ToLongTimeString());

This allows structured logging. The logger can save the parametervalues separately from the template which allows for easier searching in application insights or other sinks. 

See also [this anwer on stackoverflow](https://stackoverflow.com/a/65938575)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Agreed! From the StackOverflow answer

> Now for the real question: Why is there a warning? The answer is that string interpolation prevents structured logging. When you pass the variables after the message, you make it possible for the logger to save them separately. If you just save the log to a file you may not see a difference, but if you later decide to log to a database or in some JSON format, you can just change your logging sink and you will be able to search through the logs much easier without changing all the log statements in your code.

Though I've been facing this warning lately in Rider only. But I agree that it's a best practice that we emphasize using templates rather than string interpolation. And what a better way to show it off in this very logging documentation. What do you guys think?

**Comment by guardrex** [comment]
Thanks ... I've got a sec to fix it up.
