### ISSUE TITLE
Suggest alternative actions when MAUI Templates are not installed with VS 2022 Preview 6.0

### ISSUE THREAD

**Issue by Tonur** [dotnet/AspNetCore.Docs#25794]
During the MAUI Blazor docs tutorial, I could not follow the steps, as I did not have the templates installed in Visual Studio 2022 Preview 6.0.

![image](https://user-images.githubusercontent.com/15033328/166658401-22b1e5c4-66a2-4e9c-8b02-78fe124feaa3.png)

After several installations and uninstallations of Visual Studio 2022 Preview 6.0 the MAUI templates still did not show up in the "New Project" screen, and I was totally lost.

![image](https://user-images.githubusercontent.com/15033328/166658531-f20faf20-7ebd-42df-8f99-6e31a30a0e70.png)

I found a solution where I queried the `dotnet new --search MAUI`, and found a dotnet template package that included these templates mentioned in the tutorial.
![image](https://user-images.githubusercontent.com/15033328/166657145-8b29923e-49ec-4c1a-9352-b39be0c92289.png)

My suggestion is that the tutorial could mention that the MAUI Templates are aquireable with the `dotnet new -i Microsoft.Maui.Templates` command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Version Independent ID: e66171ce-7dca-bf91-36be-f02e38c00678
* Content: [Build a .NET MAUI Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/maui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/maui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Tonur ... Please report this at ...

https://github.com/dotnet/maui/issues

... and please add the following line to your opening comment there so that I can follow along ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25794
```
