### ISSUE TITLE
Confusing sentence

### ISSUE THREAD

**Issue by AdawiHub** [dotnet/AspNetCore.Docs#25810]
Hi

> The ASP.NET Core Module specifies the port via an environment variable at startup. 

I think this sentence is confusing. After a lot of tries and errors, I discovered that ANCM starts dotnet process and sends port number using process arguments, isn't it? Also, the essay says in the previous sentence:

> The module forwards the requests to Kestrel on a random port for the app. The random port isn't 80 or 443.

So what port does ANCM specify via env variables? Is it the port Kestrel listen to?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f99cd387-53b0-8b37-4f2c-fc4edd1ed080
* Version Independent ID: a1fcfbef-c5f0-c0f4-4246-8aee6ac72aea
* Content: [Out-of-process hosting with IIS and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/out-of-process-hosting?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/out-of-process-hosting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/out-of-process-hosting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/

**Comment by AdawiHub** [comment]
Based on the provided link. This [document ](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/out-of-process-hosting?view=aspnetcore-6.0)is wrong or vague. ANCM does not use environment variables to specify ports to Kestler.  

The provided link also states that command-line arguments override environment variables. So, even if environment variables configuration was used, it would be useless.

I think the documentation has an issue and should be fixed.
