### ISSUE TITLE
Blazor WebAssembly debugging docs

### ISSUE THREAD

**Issue by Domonion** [dotnet/AspNetCore.Docs#25811]
Hi, a couple of months ago I made issue #25205. Judging from my experiments with project templates - blazor webassembly debugging requires at least one of the following nuget packages - ```Microsoft.AspNetCore.Components.WebAssembly.DevServer``` for standalone and  ```Microsoft.AspNetCore.Components.WebAssembly.Server```  for server hosting type. Can you verify that information or point me to the right docs? Is it true that these packages contains debugging proxy?

Thank you in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Domonion ... I'm not aware that specific packages must be added by devs to debug apps. If you find that you need to add these packages, then open an issue for the product unit ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/25811
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

**Comment by Domonion** [comment]
<img width="603" alt="Screen Shot 2022-05-08 at 1 01 05 AM" src="https://user-images.githubusercontent.com/12771085/167269981-59741dc0-43cf-47a9-ac57-9fec1577a97f.png">
@guardrex this is blazorwasm template from .NET 6,  if I remove either of packages - WebAssembly stops working. 

Same goes for the hosted variant.
<img width="603" alt="Screen Shot 2022-05-08 at 1 14 49 AM" src="https://user-images.githubusercontent.com/12771085/167270381-c9d7a38e-6eb5-4fa8-8cd0-0c38e1a409a8.png">

After some digging I found following chain of calls.
1. in the [devserver package](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/WebAssembly/DevServer/src/Microsoft.AspNetCore.Components.WebAssembly.DevServer.csproj) there is [```UseWebAssemblyDebugging```](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/WebAssembly/DevServer/src/Server/Startup.cs#L30) call that address to [server package](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/WebAssembly/Server/src/WebAssemblyNetDebugProxyAppBuilderExtensions.cs#L35)
2. There is an additional endpoint ```/_framework/debug``` mentioned as an ```inspectUri``` at [Debug ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-6.0&tabs=visual-studio) page
3. That endpoint [launches a debugging proxy](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/WebAssembly/Server/src/DebugProxyLauncher.cs#L104). Proxy also mentioned at docs page.
4. Proxy address to [```Microsoft.NETCore.BrowserDebugHost.Transport``` package](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/nuget/Microsoft.NETCore.BrowserDebugHost.Transport/Microsoft.NETCore.BrowserDebugHost.Transport.pkgproj) ([sources](https://github.com/dotnet/runtime/tree/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/wasm/debugger/BrowserDebugProxy)). That nuget package is referenced at [```Microsoft.AspNetCore.Components.WebAssembly.Server```](https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Components/WebAssembly/Server/src/Microsoft.AspNetCore.Components.WebAssembly.Server.csproj#L16). 

So as far as I can see, either of these packages required for debugging. Correct me please.

**Comment by guardrex** [comment]
Sorry, I wasn't paying attention. Yes, that's right. However, those are the default packages for Blazor WebAssembly (or hosted Blazor WebAssembly). No other packages are required. Are you asking for the topic to mention these packages, or are you just trying to verify your points 1-4 are correct, which seem fine to me, but I admit that haven't looked at how the framework handles debugging in detail.

**Comment by Domonion** [comment]
It will be great if there would be a topic that these packages are required for Blazor WebAssembly to work ;) 

There [are not even a word](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-6.0&terms=Microsoft.AspNetCore.Components.WebAssembly.DevServer) about ```Microsoft.AspNetCore.Components.WebAssembly.DevServer``` package and [very little](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.server?view=aspnetcore-6.0) for ```Microsoft.AspNetCore.Components.WebAssembly.Server```.  It drove me crazy what the purpose for these packages are ;)

**Comment by guardrex** [comment]
Ok ... sounds good to me. I'll schedule this issue for work.
