### ISSUE TITLE
I do not see what is wrong with this code

### ISSUE THREAD

**Issue by JohnKlineKurtz** [dotnet/AspNetCore.Docs#25814]
[EDIT by guardrex to add the code styles]

My code has this... I cannot distinguish it from your suggested code.

```csharp
app.MapGet("/qnas/{id}", (int pID) =>
{
    return new QuestionController().GetQNA(pID);
}).WithName("GetQNA");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f5a19ea-2ba9-a36f-7fb6-61c39ef91b96
* Version Independent ID: 0f5a19ea-2ba9-a36f-7fb6-61c39ef91b96
* Content: [ASP0005: Do not place attribute on method called by route handler lambda](https://docs.microsoft.com/en-us/aspnet/core/diagnostics/asp0005?view=aspnetcore-6.0)
* Content Source: [aspnetcore/diagnostics/asp0005.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0005.md)
* Product: **aspnet-core**
* GitHub Login: @captainsafia
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JohnKlineKurtz ... 

`pID` doesn't match `id`. Did you try ...

```csharp
app.MapGet("/qnas/{id}", (int id) =>
{
    return new QuestionController().GetQNA(id);
}).WithName("GetQNA");
```

**Comment by JohnKlineKurtz** [comment]
I ended up with this for the .NET:
app.MapDelete("/qnas/{id}", (int id) =>
{
    if (new QuestionController().DeleteQNA(id))
    {
        return Results.Ok(null);
    }
    else
    {
        return Results.Problem("Could not delete");
    }

}).WithName("DeleteQNA");

It hink the problem was in my Angular... this finally worked:
  deleteQuestion(pQ: Question): Observable<HttpResponse<any>> {
    var sURL = this.URLForQNAs + "/" + pQ.id;
    console.log("Calling DELETE with " + sURL);
    return this.http.delete<HttpResponse<any>>(sURL, { observe: 'response' });
  }

**Comment by guardrex** [comment]
Ok ... glad u got it working.

Could you try something? Use that exact code on both ends, but change it back to where the route param doesn't match the method signature ...

```csharp
app.MapDelete("/qnas/{id}", (int pID) =>
{
    if (new QuestionController().DeleteQNA(pID))
    {
        return Results.Ok(null);
    }
    else
    {
        return Results.Problem("Could not delete");
    }
}).WithName("DeleteQNA");
```

Run it ... see if it throws ... see **_WHAT exception_** it throws if it throws one.

**Comment by guardrex** [comment]
Closing without the final checks as resolved by customer.
