### ISSUE TITLE
Empty `Visual Studio Code` section

### ISSUE THREAD

**Issue by mystiquewolf** [dotnet/AspNetCore.Docs#25818]
Below the `Update the /Views/Movies/Create.cshtml with a Rating field.` text there is an empty `Visual Studio Code` section.
![Screenshot_20220508_220535](https://user-images.githubusercontent.com/16529989/167311761-ce2831bd-9db0-421c-9bcb-1897d2c653b7.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Part 8, add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-6.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, nothing to show, per the doc

[`<!-- This tab intentionally left blank. -->`](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/new-field.md?plain=1#L73)

**Comment by mystiquewolf** [comment]
@Rick-Anderson Wouldn't it be better if there was an actual text saying that you don't have to do anything for VS Code? Or even better, just remove the VS Code part when it's not usable. It's *confusing*.
