### ISSUE TITLE
Example for handling JSON patch docs while still using System.Text.Json does not work

### ISSUE THREAD

**Issue by pdevito3** [dotnet/AspNetCore.Docs#25816]
The example for [handling JsonPatchDocs while still using `System.Text.Json`](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0#add-support-for-json-patch-when-using-systemtextjson) does not work.

For a snapshot, the recommendation is:

```c#
builder.Services.AddControllers(options =>
{
    options.InputFormatters.Insert(0, MyJPIF.GetJsonPatchInputFormatter());
});

public static class MyJPIF
{
    public static NewtonsoftJsonPatchInputFormatter GetJsonPatchInputFormatter()
    {
        var builder = new ServiceCollection()
            .AddLogging()
            .AddMvc()
            .AddNewtonsoftJson()
            .Services.BuildServiceProvider();

        return builder
            .GetRequiredService<IOptions<MvcOptions>>()
            .Value
            .InputFormatters
            .OfType<NewtonsoftJsonPatchInputFormatter>()
            .First();
    }
}
```

Worth noting there is already [a ticket](https://github.com/dotnet/aspnetcore/issues/24333) around the root cause of this that has gotten a good bit of traffic over the course of more than 2 years and has been mostly ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/aspnetcore/issues/24333 asks that `System.Text.Json` should handle `JsonPatchDocument`. 
Are you saying [Microsoft.AspNetCore.Mvc.NewtonsoftJson](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/) doesn't handle `JsonPatchDocument`?

**Comment by pdevito3** [comment]
Hey Rick, no it's more that I have to use `.AddNewtonsoftJson()` explicitly. Using the `options.InputFormatters.Insert(0, MyJPIF.GetJsonPatchInputFormatter());` input formatter doesn't seem to work.

**Comment by pdevito3** [comment]
Rick, here is [an example repo](https://github.com/pdevito3/borken-patchdoc-example).

You can toggle the controller setup [here](https://github.com/pdevito3/borken-patchdoc-example/blob/main/RecipeManagement/src/RecipeManagement/Extensions/Services/WebAppServiceConfiguration.cs)

It will use an in memory db, so you can just do a `dotnet run` add a default record using a POST, and do a patch doc like so:
```
[
    { "op": "replace", "path": "/title", "value": "bar"},
]
```

The newtonsoft only version will work, the custom formatter will not

**Comment by jaliyaudagedara** [comment]
yeah, I am facing the same:
[Add support for JSON Patch when using System.Text.Json](https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-7.0#add-support-for-json-patch-when-using-systemtextjson) does not work.

**Comment by colmabe** [comment]
We also have an issue with this.

When we use the generic class JsonPatchDocument<> as the model type the solution with the NewtonsoftJsonPatchInputFormatter works. But the endpoints that have the none generic class JsonPatchDocument as model type it will not use the Newtonsoft formatter to parse the model.

**Comment by luizhlelis** [comment]
Hello everyone,
@pdevito3 , @jaliyaudagedara , @colmabe 

I was facing the same issue but then I realized that the `Content-Type` header on the client side was wrong. If you want to follow the [JSON Patch when using System.Text.Json](https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-7.0#add-support-for-json-patch-when-using-systemtextjson) approach, you need to set the `Content-Type` header to `application/json-patch+json` client side. Therefore, no `.AddNewtonsoftJson()` will be required.

@Rick-Anderson and @captainsafia, I can create a PR with the above info as a note if you think it makes sense.

**Comment by Rick-Anderson** [comment]
It says that [right at the top of the article](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/jsonpatch.md?plain=1#L32).

**Comment by hysnyasir** [comment]
I am also facing the above, have you found any solution, I want to use AddJsonOptions instead of AddNewtonsoftJson. 
Can anyone help me with it?

**Comment by luizhlelis** [comment]
@hysnyasir , currently, [the System.Text.Json-based input formatter doesn't support JSON Patch](https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-7.0#add-support-for-json-patch-when-using-systemtextjson). If you want to use PATCH in ASP.NET Core, you can add `Newtonsoft.Json`, while leaving the other input and output formatters unchanged following the steps in the doc.

**Comment by hysnyasir** [comment]
@luizhlelis I am using AddJsonOptions in which I configured different JsonSerializerOptions converters i.e JsonStringEnumConverter
JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase

So if I add .AddNewtonsoftJson() then AddJsonOptions didn't work. So I need to user AddJsonOptions with patch. 

I configured it i.e 

builder.Services.AddControllers(options =>
{
    options.InputFormatters.Insert(0, MyJPIF.GetJsonPatchInputFormatter());

})..AddJsonOptions(options =>
{
    options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
    //Converters
    //Converters
    //Converters
    //Converters
});

with these configuration

**Comment by hysnyasir** [comment]
And getting this error:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/15126317/ac607a3e-d694-45d9-812f-f7c243b7bb7d)

**Comment by duszekmestre** [comment]
I'm happy to announce small workaround. You can use `JsonPatchDocument<object?>` as argument type instead of `JsonPatchDocument` in controller. After that you are allowed to use Newtonsoft implementation alongside Sytem.Text.Json.

The root issue is in here: https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonPatchInputFormatter.cs#L87

I guess removing `IsGenericType` check should resolve issue but this requires testing.
