### ISSUE TITLE
Sample code unclear and not available for lower .net versions

### ISSUE THREAD

**Issue by jeroenvrijnsen** [dotnet/AspNetCore.Docs#25827]
Two points of attention:
1. The downloadable sample code is only available for .net6.0 - can it be made available for the other versions as well, matching the selected .net version (e.g. 5.0)?
2. In the constructor of the integration test, can it be explained where the fixture and outputHelper arguments of the MockedGreeterServiceTests constructor are initialized? This is also not clear from the sample code (but I could not verify if it builds/runs, since I cannot use .net6.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ad662e-1855-15bb-8e98-698e8c29b7fb
* Version Independent ID: 24ad662e-1855-15bb-8e98-698e8c29b7fb
* Content: [Test gRPC services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-5.0)
* Content Source: [aspnetcore/grpc/test-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/test-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
