### ISSUE TITLE
Handle Concurrency Conflicts

### ISSUE THREAD

**Issue by HSouhaib** [dotnet/AspNetCore.Docs#25835]
[Enter feedback here]

in the department delete razor page, 
Update the page directive from @page to @page "{id:int}".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Part 8, Razor Pages with EF Core in ASP.NET Core - Concurrency](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's left to the reader.
