### ISSUE TITLE
Please add an explanation as to why there's a benefit to using the "No Managed Code" flag

### ISSUE THREAD

**Issue by kristianjaeger** [dotnet/AspNetCore.Docs#25831]
[Enter feedback here]
Hello, Please add an explanation as to why there's a benefit to using the "No Managed Code" flag.  There could be a plausible one here - https://www.reddit.com/r/dotnet/comments/crojnl/what_is_the_benefit_os_using_no_managed_code_in/ . Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d172b69-845d-739a-742c-617b9eed04fe
* Version Independent ID: 79d553f1-9112-b61a-0ad0-dfbb11e5071a
* Content: [Advanced configuration](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Setting the .NET CLR version to No Managed Code is optional but recommended.

**Comment by kristianjaeger** [comment]
@Rick-Anderson That does not explain why though...  Why did you just close this?
