### ISSUE TITLE
Re-add documentation on `Microsoft.AspNetCore.Grpc.HttpApi`

### ISSUE THREAD

**Issue by adeal** [dotnet/AspNetCore.Docs#25837]
A change (https://github.com/dotnet/AspNetCore.Docs/pull/25825) was made to this page to add information about gRPC JSON transcoding. However, this removed the existing info for `Microsoft.AspNetCore.Grpc.HttpApi`. Since json transcoding is a new dotnet 7 feature, is it possible to have the old details for net5/net6 alongside this new info?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa3c933-30c4-eb49-d9a5-507aff44ce00
* Version Independent ID: 1485c456-eb24-a446-e296-dd3686456837
* Content: [gRPC JSON transcoding](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi)
* Content Source: [aspnetcore/grpc/httpapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/httpapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
GrpcHttpApi is an experiment that's getting replaced. I don't think docs.microsoft.com is the right place to keep docs for it long term. However, there is some docs at https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi. Does it have all the information you are looking for?

We could add a link to the GitHub page from https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi and remove it in a couple of years once .NET 7 and greater is more widely available.

**Comment by wadepickett** [comment]
@JamesNK, [gRPC JSON transcoding](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi) is not version specific yet.  I can give it a <= 6.0 version that includes https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi  and 7.0 version that does not include it.  That work?

**Comment by JamesNK** [comment]
Sure. That sounds like a good idea.

**Comment by adeal** [comment]
> @JamesNK, This doc, [gRPC JSON transcoding](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi) is not version specific yet. I can give it a <= 6.0 version that includes https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi and 7.0 version that does not include it. That work?

This is the solution I was hoping for. Essentially, for <=6.0, use the docs that existed before @JamesNK change in https://github.com/dotnet/AspNetCore.Docs/pull/25825. The documentation that existed was actually a bit more informative than https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi in terms of setup steps.

Thank you!

**Comment by wadepickett** [comment]
@JamesNK, looking at the diff between the original "Create JSON Web APIs from gRPC" topic and [ASPLabs gRPC HTTP API](https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi) I'm thinking it might be better to update the latter to include what it was missing.  Namely the section: Enable Swagger/OpenAPI support.  Then link to it as you first suggested, although I will put that link in <= 6.0 versions.

OK to move the old section: Enable Swagger/OpenAPI support we had in this doc to [ASPLabs gRPC HTTP API](https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi) and just link?

**Comment by JamesNK** [comment]
Go ahead

**Comment by wadepickett** [comment]
AspLabs page for gRPC HTTP API was updated with this PR: https://github.com/aspnet/AspLabs/pull/509
