### ISSUE TITLE
Scenarios with custom domain

### ISSUE THREAD

**Issue by thismaker** [dotnet/AspNetCore.Docs#25849]
My suggestion is that the tutorial include a note or something for the reader who might be using a custom domain in Azure, for example while the assigned domain might be `contoso.onmicrosoft.com`, they may have added a custom domain such as `example.com` and set it as the primary domain. When using the template to generate the project, it generates the scope as `https://contoso.onmicrosoft.com/{CLIENT_ID}/scope`, however, in the Azure portal, due to the custom domain, it will be `https://example.com/...`. I spent a whole lot of time trying to figure out the cause of a strange error I was receiving, and I even thought the documentation was incorrect. I am therefore sure a small note informing the reader that, if they are using a custom domain, they should confirm the generated scope. Otherwise the small typo, especially since it's hard to catch as you'll be used to both domains, can cost a lot of time, and cause great pain and agony to the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @thismaker ... Thanks for the feedback, but it is the developer's responsibility to use the correct settings for their app. We won't be able to cover every conceivable scenario where a misconfigured setting breaks an app's hosting. Besides, the topics here were only put up at the time to cover these scenarios in a temporary and minimal way until Azure documentation was written cover these hosting scenarios for Blazor with Azure AAD/B2C. Azure docs now have their own tutorials for these scenarios, and we're looking at dropping these topics in this doc set by the end of the year.
