### ISSUE TITLE
Startup class details no longer in v6 docs

### ISSUE THREAD

**Issue by droyad** [dotnet/AspNetCore.Docs#25846]
The v6.0 version of the docs no longer contain details about the `The Startup class`. For me in particular what the method conventions are.

If you switch back to the v5 docs the details are there.

If you [search the for ConfigureServices](https://docs.microsoft.com/en-us/search/?scope=ASP.NET%20Core&view=aspnetcore-6.0&terms=ConfigureServices) this page comes up (result 5 or so). The details are there in the preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
On the upper left you select the .NET 5.0 version which covers this information for that version and its related startup info.  Agreed, we do want to keep that information.  It is kept by version.  I will review the search results to see if there is anything to change on that end.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/10985336/168139699-60770718-12e6-4861-9abe-6ebcc5b4f314.png">

**Comment by droyad** [comment]
Our app is ASP.NET 6.0 and has a Startup class, hence the confusion
