### ISSUE TITLE
Wrong Cache-Control max-age value in the given image under "Set HTTP response headers" section

### ISSUE THREAD

**Issue by ankitwww** [dotnet/AspNetCore.Docs#25848]
Under the section "Set HTTP response headers", there is an image depicting the Response header, which shows Cache-Control max-age. In the above example code, it was calculated as one week (604800 seconds), however, the image shows it as 600 seconds. This seems a small typo and the image should be replaced with the right value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ankitwww** [comment]
Happy to take up this issue!

**Comment by Rick-Anderson** [comment]
@ankitwww  go ahead.

**Comment by Rick-Anderson** [comment]
Personally, I'd just remove the image.

**Comment by ankitwww** [comment]
Yes, removing the image seems a straightforward solution.
