### ISSUE TITLE
UseWindowsService

### ISSUE THREAD

**Issue by jlpm10091** [dotnet/AspNetCore.Docs#25869]
Where is the example on how to host a Blazor application using a Windows Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b20b470-161a-8723-b66d-c0c1804874f0
* Version Independent ID: 2712f7a2-90e7-0012-f7d9-f3a7e7e345d7
* Content: [Host and deploy ASP.NET Core Blazor Server](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jlpm10091 ... There isn't because Blazor Server apps are normal ASP.NET Core apps, so the ASP.NET Core doc instructions apply ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service
