### ISSUE TITLE
Really lacks basic information for implementation.

### ISSUE THREAD

**Issue by mberickson** [dotnet/AspNetCore.Docs#25860]
[Enter feedback here]

The line "using Microsoft.AspNetCore.Headers" DOES NOT work for the standard VS 2019 project. Need information of what to link to and how to get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by ankitwww** [comment]
I guess you meant "using Microsoft.AspNetCore.HttpLogging". BTW, which .NET version you are targeting? HTTP logging middleware was introduced in .NET 6 - so check your project's TargetFramework once.
