### ISSUE TITLE
Confused about ways of enabling CORS

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#25867]
Hello, guys. IMO, it's a bit confusing when you write about avoiding combing middleware and `[EnableCors]` attribute usage:

>  We recommend against combining policies. Use the [EnableCors] attribute or middleware, not both in the same app.

This creates an impression that `app.UseCors()` should not be called at all, if `[EnableCors]` is used. Yet as I can see from the codebase, cors middleware is the only consumer of this attribute. Furthermore, [source code comments](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Middleware/CORS/src/Infrastructure/CorsMiddleware.cs#L117) contradict what you claim:

> // CORS policy resolution rules:
//
// 1. If there is an endpoint with IDisableCorsAttribute then CORS is not run
// 2. If there is an endpoint with ICorsPolicyMetadata then use its policy or if
//    there is an endpoint with IEnableCorsAttribute that has a policy name then
//    fetch policy by name, prioritizing it above policy on middleware
// 3. If there is no policy on middleware then use name on middleware

versus 

>  When the `[EnableCors]` attribute is applied to a controller, page model, or action method, and CORS is enabled in middleware, both policies are applied.

Does
> CORS is enabled in middleware

actually mean:
- Middleware is added to pipeline
- Middleware is added to pipeline with specified named  policy (or default) AND that named policy (or default) defined in the call to `services.AddCors`  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
