### ISSUE TITLE
Razor Tutorial: Update to .NET SDK 6.0.300 - Template updates and non-nullable no longer issue

### ISSUE THREAD

**Issue by rmeby** [dotnet/AspNetCore.Docs#25862]
Updated by wadepickett:
There are a few changes in the template for the .NET SDK 6.0.300 that require a new app sample update plus some changes in the Razor tutorial set.

- Nullable warnings are no longer encountered when following the tutorial because the generated `RazorPagesMovieContext.cs` file now makes the Movie property nullable.   This needs to be addressed both in the app sample and in [Razor Tutorial - Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code)
- Program.cs has changed and should be reflected in the app sample.
- Scaffolding output has changed.
- Packages have newer versions.
- Package manager screenshot needs to be updated to show Latest stable 6.0.5
- Migrations output has changed.
- Bootstrap has updated.

While I am updating I will also update a few screenshots of the running app sample.  Some show "2017" in them. Just to reassure folks that this tutorial is up to date.

The same update needs to occur for the MVC tutorial, moved to its own issue #26094 and PR. 

Thanks to @rmeby for pointing out this needed an update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What version?  The scaffolded code generated more than one warning.

**Comment by rmeby** [comment]
```
PS C:\> dotnet --version
6.0.300
PS C:\> dotnet tool list -g
Package Id                       Version      Commands
-------------------------------------------------------------------------
dotnet-aspnet-codegenerator      6.0.4        dotnet-aspnet-codegenerator
dotnet-ef                        6.0.5        dotnet-ef
```

**Comment by wadepickett** [comment]
@Rick-Anderson, The scaffolding has been updated just recently so there is no longer an issue that needs to be addressed. So this section is only needed for previous 6.0 versions.  I think we mention this in the MVC tutorial as well.  VS for Windows/VS Code and VS for Mac.  I just verified in the latest VS for Mac RC.

I'll update for both.

**Comment by wadepickett** [comment]
Hmm:  Just saw this new comment on that dotnet issue: 
https://github.com/dotnet/Scaffolding/issues/1594#issuecomment-1122928785

"The error appears before the step Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore which makes it disappear but the document text doesn't mention the error directly or that it will be resolved with the above step. Thanks!"
