### ISSUE TITLE
Needs more explanation

### ISSUE THREAD

**Issue by MichaelBrooks-Informatyx** [dotnet/AspNetCore.Docs#25877]
[Enter feedback here]
This is a pretty good exercise, but in order to gain best value from it the reader needs to understand how everything works.
The bit that really needs to be explained is line 5: `<h1>Todo (@todos.Count(todo => !todo.IsDone))</h1>`
The syntax is easy enough to follow; the unclear bit is the invocation mechanism. "@todos.Count(todo => !todo.IsDone)" is not within any form of event handler, so what causes it to be called every time a change is made to an **IsDone** property in any item within the **todos** array? There is an explicit binding specified between the **IsDone** property and the checkbox, but no binding (that I can see) has been specified between this or the **TodoItem** or the **todos** array and the "@todos.Count(todo => !todo.IsDone)" Blazor code.
Without a visible event handler or binding, my natural expectation would have been that this line only gets executed when the browser loads or refreshes the page, but clearly it is being invoked much more frequently than that. If you could explain (or point to an explanation of) the mechanism here, that would make a huge difference to my understanding of Blazor - I suspect that without understanding this mechanism I will be severely limited in my ability to write effective Blazor code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f2cad2-31f9-d5d1-671c-5613fb812b19
* Version Independent ID: 23f2cad2-31f9-d5d1-671c-5613fb812b19
* Content: [Build a Blazor todo list app](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MichaelBrooks-Informatyx ...

> browser loads or refreshes the page

That's not how the model for single-page apps (SPAs) work. Blazor controls the rendering/re-rendering, and Razor statements are evaluated when rendering occurs.

> needs to understand how everything works

> I suspect that without understanding this mechanism I will be severely limited in my ability to write effective Blazor code.

Tutorials aren't meant to explain framework details, just to exhibit an overview of them. The following documentation ... the articles further along the table of contents (ToC) in the *Blazor* node ... go into all of the features and behaviors that you're seeing. The event handling and binding aspects are explained out in great detail by documents in the *Components* node.

Having said that tho, I think adding a line or two here for additional information on the behavior is fine. I just don't want to get too carried away with it trying to explain out behaviors in detail.

Thanks for the feedback. Leave this issue open, as it will close automatically later when the PR merges.

**Comment by MichaelBrooks-Informatyx** [comment]
Thanks for that Luke. Yes, I’ve found what you’re referring to – hopefully that will fill in all the blanks in my understanding.

 

Regards,

Michael
