### ISSUE TITLE
UI cluttered after executing the provided code

### ISSUE THREAD

**Issue by jankiny** [dotnet/AspNetCore.Docs#25875]
hi there,

I create the project and add the code according to the documentation, however, in the browser I see that the added input box is not displayed correctly. There are two places:

Firstly, in the section of [Update the Account/Manage/Index.cshtml page](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio#update-the-accountmanageindexcshtml-page), after adding and executing the code below the sentence `Update the Areas/Identity/Pages/Account/Manage/Index.cshtm`, the UI I get is like this
![image](https://user-images.githubusercontent.com/31720722/168636995-1f62d31e-5aba-4b46-8462-3b4f83b887d2.png)
Based on the context of the code, I think it should be
```cshtml
<div class="form-floating">
    <input asp-for="Input.Name" class="form-control"/>
    <label asp-for="Input.Name" class="form-label"></label>
</div>
<div class="form-floating">
    <input asp-for="Input.DOB" class="form-control"/>
    <label asp-for="Input.DOB" class="form-label"></label>
</div>
```

The same problem in the register page, in the section [Update the Account/Register.cshtml page](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio#update-the-accountregistercshtml-page), after the sentence `Update the Areas/Identity/Pages/Account/Register.cshtml`, the highlight code should be
```cshtml
<div class="form-floating">
    <input asp-for="Input.Name" class="form-control"/>
    <label asp-for="Input.Name"></label>
    <span asp-validation-for="Input.Name" class="text-danger"></span>
</div>
<div class="form-floating">
    <input asp-for="Input.DOB" class="form-control"/>
    <label asp-for="Input.DOB"></label>
    <span asp-validation-for="Input.DOB" class="text-danger"></span>
</div>
```

By the way, after registering the user successfully, the two newly added fields for `WebApp1User` are not saved to the database. I'm not sure if I missed something, I tried adding `user.Name = Input.Name; user.DOB = Input.DOB;` before `var result = await _userManager.CreateAsync(user, Input.Password);` and it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you add a migration?

**Comment by jankiny** [comment]
I deleted the data table and the migrations folder in the project, then added migrations again, and I can find the `Name` and `DOB` fields in the "AspNetUsers" data table. 

>  I tried adding `user.Name = Input.Name; user.DOB = Input.DOB;` before `var result = await _userManager.CreateAsync(user, Input.Password);`

But If I remove these two lines of code, the data filled in for registration still cannot be saved to the database.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
