### ISSUE TITLE
Omitted word in 'Detailed errors during development' section

### ISSUE THREAD

**Issue by lcichanowicz** [dotnet/AspNetCore.Docs#25873]
In the last paragraph of the '[Detailed errors during development](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0#detailed-errors-during-development)' section, there is a work omitted.

Currently:
The blazor-error-ui element is normally hidden due the presence of the display: none...

Should be:
The blazor-error-ui element is normally hidden due **_to_** the presence of the display: none...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adbc1392-92dc-c42e-ba48-a722cffa9b6d
* Version Independent ID: 66a0b1c2-c45c-98ca-9808-6f340a861c44
* Content: [Handle errors in ASP.NET Core Blazor apps](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @lcichanowicz. I'll patch that right now.
