### ISSUE TITLE
Missing code for .NET 6.0

### ISSUE THREAD

**Issue by JoshClose** [dotnet/AspNetCore.Docs#25880]
.NET 6.0 uses `WebApplicationBuilder`. For this to work, some modifications need to be made. I was not able to get this to run without these.

https://stackoverflow.com/questions/70571849/host-asp-net-6-in-a-windows-service

```cs
var webApplicationOptions = new WebApplicationOptions
{ 
    ContentRootPath = AppContext.BaseDirectory, 
    Args = args, 
    ApplicationName = System.Diagnostics.Process.GetCurrentProcess().ProcessName 
};
var builder = WebApplication.CreateBuilder(webApplicationOptions);

builder.Host.UseWindowsService();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting.
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by JoshClose** [comment]
I'll give it a shot.

**Comment by JoshClose** [comment]
Looks like there are some unresolved issues for this. You are in on the conversation on the docs one. Seems like the solution that @davidfowl suggests is setting the `--contentRoot` instead of changing the `WebApplicationOptions`.

https://github.com/dotnet/runtime/issues/69212
https://github.com/dotnet/aspnetcore/issues/37464
https://github.com/dotnet/AspNetCore.Docs/issues/23387

I tried this and it works fine that way.

I updated the doc to change the PowerShell `New-Service` command to use `--contentRoot` instead of the other code.

https://github.com/dotnet/AspNetCore.Docs/pull/25882

**Comment by Rick-Anderson** [comment]
Nice work!
