### ISSUE TITLE
Should we change Url.Action to mention that the 'controller' argument expects a controller route value, instead of a controller's name?

### ISSUE THREAD

**Issue by kikaragyozov** [dotnet/AspNetCore.Docs#25889]
If we want to do routing to a controller class named `SomeController`, the `controller` argument that we must pass into `UrHelperl.Action` is `Some`, and not `SomeController`. This is implicitly noticed with the demo code, but never further expanded about. That is not the same for action methods - there, the full name of the action method is used, with a slight caveat that the MVC options allow the consumer to disable Async prefixes being removed from said action methods, as by default, they are trimmed from action method names.

Perhaps also expanding the remarks section to the relevant [UrlHelperExtensions.Action](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.urlhelperextensions.action?view=aspnetcore-6.0) method overloads is the more accurate place for this? Or maybe we can just expand both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by kikaragyozov** [comment]
> Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

Hello Rick! Shouldn't we make it more clear of what `Url.Action` expects as parameters? Although I'm not sure where the best place for the addition would be. Probably [UrlHelperExtensions.Action](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.urlhelperextensions.action?view=aspnetcore-6.0)?

**Comment by kikaragyozov** [comment]
I'm willing to try and draft something if you guys are open to the idea?

**Comment by MackinnonBuck** [comment]
@kikaragyozov If you have a change you'd like to propose, please feel free to submit a PR. Thanks!

**Comment by Rick-Anderson** [comment]
> I'm willing to try and draft something if you guys are open to the idea?

That would be great, please do.

**Comment by kikaragyozov** [comment]
Sorry, been swarmed with work lately. I'll try to draft something up this weekend! Thanks for the opportunity!

**Comment by mkArtakMSFT** [comment]
Thanks for your willingness to help with this, @kikaragyozov. Given that a lot of time has passed and we've seen no other members from the community express similar concerns we've decided to close this issue. If you find time to submit a PR with your proposed changes, we'll happily consider it.

**Comment by Altav1sta** [comment]
Please do it, I spent 2 days in debugging trying to understand why Url.Action is not working. The fact that something is trimmed in these parameters is ridiculous. How people should understand that?
