### ISSUE TITLE
Add line about "AddRoles" 

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#25895]
I would like to recommend that you add a small section on EnablingRoles, to the Roles section.  If Roles are not enabled, then it appears that the section on Roles "does not work."  This is exactly what happened to me and it took me some searching on 3rd party sites to find the answer.

This is what I recommend:

-- Existing Text
The [AuthorizeView](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.authorization.authorizeview) component supports role-based or policy-based authorization.

--Added Text
To use role based authorization, add support for roles to startup code:

```
builder.Services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
    .AddRoles<IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>();
```

--Existing Text
For role-based authorization, use the [Roles](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.authorization.authorizeview.roles#microsoft-aspnetcore-components-authorization-authorizeview-roles) parameter:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gregoryagu ... Immediately after the example it cross-links ...

> For more information, see \<xref:security/authorization/roles>.

... which leads to the to the role auth doc in the main doc set, where the reader receives the guidance that you suggest in the *Add role services to Identity* section ...

https://docs.microsoft.com/aspnet/core/security/authorization/roles#add-role-services-to-identity

Thanks for the suggestion, but we prefer not to duplicate coverage, so I'm going to leave it as it stands.

**Comment by guardrex** [comment]
Actually ... 🤔 ... let's just make the lead-in for the cross-link clear that config information will be found there.
