### ISSUE TITLE
Need to doc new ANCM disableRotatationOnConfig handler setting

### ISSUE THREAD

**Issue by HaoK** [dotnet/AspNetCore.Docs#25893]
Was added in https://github.com/dotnet/aspnetcore/pull/37474 (7.0-preview1)

***@Rick-Anderson EDIT to add the following metadata***

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module (ANCM) for IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 61757](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61757)

**Comment by Rick-Anderson** [comment]
@guardrex  is this the right article to add new ANCM disableRotatationOnConfig handler setting?
@ShreyasJejurkar can you help me get the draft started?

**Comment by ShreyasJejurkar** [comment]
Hi Rick, I am not getting why I am tagged here!? And also I am not aware of the given topic to start a draft! 
I guess you mistakenly tagged me! 😅

**Comment by Rick-Anderson** [comment]
@ShreyasJejurkar I was hoping you were familiar with `disableRotatationOnConfig` and could get me started. Sorry for pinging you. I'll wait for Haok.

**Comment by HaoK** [comment]
Sure I can provide a high level overview of what this flag is intended for.  This is actually a setting intended for blue/green scenarios where they don't want a change to global config to tear down all sites.  When this flag is true, this means only changes relevant to the site itself will cause an application recycle, i.e. web.config changes, or something relevant to the site's path from IIS's perspective.  But a general change to applicationHost.config would not cause an app recycle when this flag is true.

This is analogous to https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.applicationpoolrecycling.disallowrotationonconfigchange?view=iis-dotnet

Does that help in terms of what this flag does?

**Comment by ShreyasJejurkar** [comment]
> @ShreyasJejurkar I was hoping you were familiar with `disableRotatationOnConfig` and could get me started. Sorry for pinging you. I'll wait for Haok.

No worries Rick. I didn't work with ANCM and never used it. 😅

**Comment by tdykstra** [comment]
@Haok In which article should this setting be documented -- where are other ANCM handler settings documented?
