### ISSUE TITLE
Fix for documentation

### ISSUE THREAD

**Issue by nmesar** [dotnet/AspNetCore.Docs#25903]
Hello,

In the DecimalValue partial class, I will suggest to remove the declaration of Nanos and Units properties since its automatically generated from the decimalValue.proto file. 
Unless I am understanding something differently.

Thanks,
Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc570f1c-bb62-88b8-fbfc-ca4e436e8091
* Version Independent ID: 4ce52659-cd0f-0172-2f8c-e58b8497eadc
* Content: [Create Protobuf messages for .NET apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/protobuf?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/protobuf.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/protobuf.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
PR that removes the properties - https://github.com/dotnet/AspNetCore.Docs/pull/25961. It also explains where the properties come from.
