### ISSUE TITLE
Update 7.0 docs to point to duende 6.0 upgrade docs

### ISSUE THREAD

**Issue by HaoK** [dotnet/AspNetCore.Docs#25902]
We are updating to Duende Identity server 6.x (currently 6.0.4 but probably will be 6.1x) as part of 7.0, can we document the potential dataschema issues that users may run into: https://docs.duendesoftware.com/identityserver/v6/upgrades/v5.2_to_v6.0/

Something like: "We're updating to the latest supported Identity Server in our extensions. Either don't use the extensions and use their configuration methods or update your schema and use our helpers""

See https://github.com/dotnet/aspnetcore/issues/41315 for more context

This affects anyone that uses Microsoft.AspNetCore.ApiAuthorization.IdentityServer which also includes some of the auth variants of Spa/Blazor templates

***Edit by @Rick-Anderson below***
> We decided on sticking with 6.0.4 for 7.0 due to 6.1 having a database schema update https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.0_to_v6.1/

Above from [this comment](https://github.com/dotnet/aspnetcore/issues/41315#issuecomment-1242470839)

---
[Associated WorkItem - 61487](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61487)

**Comment by Rick-Anderson** [comment]
Blazor:  https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server - cc @guardrex 

Not Blazor, gRPC, or SignalR

* https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization
* https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app
* https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa
* https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api
*

**Comment by Rick-Anderson** [comment]
@HaoK  given
> We decided on sticking with 6.0.4 for 7.0 due to 6.1 having a database schema update https://docs.duendesoftware.com/identityserver/v6/upgrades/v6.0_to_v6.1/

Above from [this comment](https://github.com/dotnet/aspnetcore/issues/41315#issuecomment-1242470839)

What do we need to update for .NET 7?

**Comment by guardrex** [comment]
Since this seems to be a migration concern and because the Blazor doc doesn't refer to Duende versions, I don't think this is actionable for the Blazor doc. Let me know if I've misinterpreted this.

**Comment by Rick-Anderson** [comment]
@HaoK  closing this. Let me know if doc's need update.
