### ISSUE TITLE
The Linux version of the page asks the reader to see the Linux version of the page

### ISSUE THREAD

**Issue by gaazkam** [dotnet/AspNetCore.Docs#25913]
Linux version of this page, section [§ Use Visual Studio Code for cross-platform Blazor development](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux#use-visual-studio-code-for-cross-platform-blazor-development) has this to say:

> [Visual Studio Code](https://code.visualstudio.com/) is an open source, cross-platform Integrated Development Environment (IDE) that can be used to develop Blazor apps. Use the [.NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/) to create a new Blazor app for development with Visual Studio Code. For more information, see the [Linux version of this article](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?pivots=linux&view=aspnetcore-6.0).

This does not make sense here.

This section should be either:

- Removed completely, or
- Moved to the top of the page and reworded in the following way:

> [Visual Studio Code](https://code.visualstudio.com/) is an open source, cross-platform Integrated Development Environment (IDE) that can be used to develop Blazor apps. Use the [.NET CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/) to create a new Blazor app for development with Visual Studio Code. See instructions below for more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3e99ba-cbe1-e8a1-6628-9b6eb39710a4
* Version Independent ID: dd777362-b92d-cac6-2343-a7aaf31d0bdf
* Content: [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=windows#trust-a-development-certificate)
* Content Source: [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tooling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @gaazkam ... I'll fix this bit up. It happened because at some point I versioned the content **_without READING IT_** 🙈😄 ... going just a wee bit tooooooo *FAST* 🏃.
