### ISSUE TITLE
Blazor Hybrid vs PWA

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#25910]
Do we have a doc that covers the differences between using a blazor webassembly PWA and a Blazor Hybrid app. Could we have one? Here is some initial content for it.
![image](https://user-images.githubusercontent.com/6995051/169362841-85aef895-757a-405e-9616-7f58d2dab120.png)

/cc: @danroth27

**Comment by danroth27** [comment]
We do have https://docs.microsoft.com/aspnet/core/blazor/hosting-models which addresses the pros/cons of the different Blazor hosting models including Blazor Hybrid vs Blazor WebAssembly. Instead of creating a new topic I prefer to update the existing one if needed.

**Comment by guardrex** [comment]
The topic covers some/most of these points, but the table that we have doesn't split out PWAs for contrast with Hybrid. I think we should try to resolve this using the existing table first, so I'll see if I can add a column to the existing table and add rows for missing characteristics from the content here. If that doesn't work, then we might need a new table. Let's see on the PR how things compose.

https://docs.microsoft.com/aspnet/core/blazor/hosting-models#which-blazor-hosting-model-should-i-choose

**Note to self**: Table content in text ...

Hybrid | PWA
--- | ---
No need to host the content anywhere public, it is rendered directly from the app into a webview. | PWAs are essentially websites (you need to host the content on some server.
The static content is packages with the application in the appropriate installer (apk, msix, etc.). | They're installed from the browser (or from some stores) but there is no installer.
Same access to the platform as any other native app would have, directly from within C#. | Access to native capabilities is limited (whatever the browser offers) and via JS interop with C#.
The app is deployed and updated as any other native app for a given platform. Following the appropriate procedures for a given platform. | They're updated automatically when the site is updated (no updates via stores, no validation/verification process for updates).
Will run using the .NET runtime natively on the target platform, which offers the best possible speed. | Will run using the .NET runtime for WebAssembly, which is slower than running directly on the platform, even for apps ahead-of-time (AOT) compiled for WebAssembly in the broswer.
