### ISSUE TITLE
Page refers to distro and browser for instructinos how to trust the dotnet dev cert, even though another page of your documentation provides these instructions

### ISSUE THREAD

**Issue by gaazkam** [dotnet/AspNetCore.Docs#25912]
Chose the Linux version of this page.

Following the instructions in this page up to section [§ Trust a development certificate](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux#trust-a-development-certificate) results in the browser displaying certificate errors. Section [§ Trust a development certificate](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux#trust-a-development-certificate) has this to say on how to fix these errors:

> There's no centralized way to trust a certificate on Linux. Typically, one of the following approaches is adopted:
> 
> - Exclude the app's URL in browser's exclude list.
> - Trust all self-signed certificates for localhost.
> - Add the certificate to the list of trusted certificates in the browser.
> 
> For more information, see the guidance provided by your browser manufacturer and Linux distribution.

The reason I find this surprising is that another page of your documentation, namely [Enforce HTTPS in ASP.NET Core § Trust HTTPS certificate on Linux](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-https-certificate-on-linux) does provide instructions how to fix the aforementioned browser errors. I followed the instructions from the subsection [§ Trust HTTPS certificate on Linux using Edge or Chrome](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-https-certificate-on-linux-using-edge-or-chrome) and they do seem to be working as expected: Chrome no longer displays certificate errors.

I believe that the Linux version of the page [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux), section [§ Trust a development certificate](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0&pivots=linux#trust-a-development-certificate) should link to [§ Trust HTTPS certificate on Linux using Edge or Chrome](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-https-certificate-on-linux-using-edge-or-chrome) instead of saying "*For more information, see the guidance provided by your browser manufacturer and Linux distribution.*".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3e99ba-cbe1-e8a1-6628-9b6eb39710a4
* Version Independent ID: dd777362-b92d-cac6-2343-a7aaf31d0bdf
* Content: [Tooling for ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/tooling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tooling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gaazkam ...

The remarks in this topic **_predate_** the content in the main doc set, so that's why the cross-link isn't there. The Linux cert trust content was put up in November, 2021 ...

https://github.com/dotnet/AspNetCore.Docs/pull/23766

... but the Linux remarks here were put up in July, 2020 ...

https://github.com/dotnet/AspNetCore.Docs/pull/19121

I'll cross-link this bit now. Thanks for calling it out.
