### ISSUE TITLE
.NET 7: document Stream binding to minimal API

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25918]
Per https://github.com/dotnet/aspnetcore/issues/38153 and [this GitHub comment](https://github.com/dotnet/aspnetcore/issues/41426#issuecomment-1118854363), show example of stream binding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0&branch=pr-en-us-25863#openapi-1)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33220](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33220)

**Comment by tdykstra** [comment]
@Rick-Anderson It looks like this issue should be closed -- there's a Stream example in the [minimal API doc](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#bind-the-request-body-as-a-stream-or-pipereader).
