### ISSUE TITLE
Offer to write introduction and usage for DisplayTemplates/EditorTemplates

### ISSUE THREAD

**Issue by Ducki** [dotnet/AspNetCore.Docs#25921]
The DisplayTemplates/EditorTemplates are a very useful system to abstract displaying values and form controls in views.

Unfortunately, they’re basically undocumented.

I would like to write an introduction to them and show how to use them, by also providing a minimal sample project (using the outlined conventions in the contribution guide of course) with a razor page that uses a DisplayTemplate and EditorTemplate for a small custom type.

The outline would be
* Use case
* How they work (folder/file name convention)
* How to use them with an example

If this is OK with you, please give me a green light, and I will make a pull request shortly.

Concerning the location of the page, perhaps within the _Web Apps_ /_Advanced_ section would be a good place.

Thanks!
Alex

**Comment by Ducki** [comment]
Yes, exactly.

**Comment by Rick-Anderson** [comment]
@Ducki  that would be great. Be sure to mention that's what the scaffolder uses.

**Comment by Ducki** [comment]
Fixed with #25959
