### ISSUE TITLE
Wrong Windows Insider build version mentioned?

### ISSUE THREAD

**Issue by korteksz** [dotnet/AspNetCore.Docs#25930]
Hi,

Currently I am investigating the possibilities to connect a grpc client from .net framework 4.8 project to a grpc server which is hosted in .net6. I already found a working solution which uses Grpc.AspNetCore.Web described [here](https://github.com/grpc/grpc-dotnet/issues/1552), but I wanted to try it with Grpc.Core and WinHttpHandler implementation too as suggested [here](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework). 

On the webpage it is mentioned that I need a Windows Insider build with a version 19622 or higher. I found [some blog pages](https://blogs.windows.com/windows-insider/2020/05/06/announcing-windows-10-insider-preview-build-19624/) where this build has been announced for 2 years. Afterwards I was looking for that build and I couldn't find such a high build number on the [Windows Insiders page](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso?rfs=1). The only version I see in the dropdown here is 19044.1288 in the Release Preview Channel (There are no other channels like "Fast ring" which is mentioned in the announcement blog for Win10 for me) and neither listed in the [Insiders Hub page](https://docs.microsoft.com/en-us/windows-insider/flight-hub/). So I installed the previously mentioned 19044.1288 version on a VM and enabled the Insider program on it hoping that it will allow me from the Windows to install later Insider versions. Unfortunately that was not the case. I don't know if that is the problem but for me in the Windows the only Insider Program Channel is the Release Preview and I can't change it to Dev or something. 

Could you give me some advice please what I am doing wrong? 

Thanks in advance,
Zoltán

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54f7bd57-6f98-4f49-62b0-f53ae5c46727
* Version Independent ID: 64cee8f6-7635-0cc8-4b9a-72f265414931
* Content: [Use gRPC client with .NET Standard 2.0](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/grpc/netstandard.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/netstandard.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@korteksz ,   There was an announcement just a few days ago for Windows 11 Insider Preview Build 25120.   See the Windows Blogs at:  [Announcing Windows 11 Insider Preview Build 25120](https://blogs.windows.com/windows-insider/2022/05/18/announcing-windows-11-insider-preview-build-25120/0

I will add a link right to the updates and announcements here so those are easier to find.  
[Latest News from Windows Insider](https://blogs.windows.com/windows-insider/)

Thanks for the heads up!

**Comment by wadepickett** [comment]
@korteksz, sorry, disregard my previous suggestion. You were looking to get a later build of an old build, and I sent you links to the very latest.  I'll see if we can provide a better link for what you are looking for that we can also update the doc with.

**Comment by wadepickett** [comment]
@JamesNK,
On [Use gRPC client with .NET Standard 2.0 | Section .NET Framework](https://docs.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework) we have the following note:

"Note
.NET Framework support is in its early stages and requires using pre-release software:
Windows 10 Build 19622 or later is available as a [Windows Insider](https://insider.windows.com/) build.
[System.Net.Http.WinHttpHandler](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) version 6.0.1 or later."

However, per this [Windows Insider build list page](https://docs.microsoft.com/en-us/windows-insider/flight-hub/) 19044.1288 is listed as the very last insider build."   

Is the wrong build number listed in the Note?  I don't know the history on this one.

**Comment by wadepickett** [comment]
Thanks @korteksz for pointing out the issue!
