### ISSUE TITLE
Explicitly detail why DOTNET_ENVIRONMENT and ASPNETCORE_ENVIRONMENT exist

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/AspNetCore.Docs#25955]
Seems a bit confusing and it would be nice to at least have it clearly explained.  Even if it's just due to the evolution of things...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
ASP.NET Core and .NET are different.

**Comment by atrauzzi** [comment]
That is not at all informative.

**Comment by tylerburd** [comment]
There is such little detail around these two variables and yet so much overlap. When would someone use one over the other?  What overrides what?  If you have DOTNET in the system env variables but ASPNETCORE in a web.config, for instance... which wins (it's not what I would intuit)?  That scenario is not covered anywhere.  The answer of "ASP.NET Core and .NET are different" does not provide any clarification.  The interaction between these two variables and the (breaking) changes made to their precedence in .NET 7 caused quite a bit of confusion and troubleshooting time for my staff and me.
