### ISSUE TITLE
Update the `Complex data model` EF Core tutorial for Nullable reference types

### ISSUE THREAD

**Issue by mystiquewolf** [dotnet/AspNetCore.Docs#25967]
Update the `Complex data model` EF Core tutorial for Nullable reference types, or at least add a note.

Example issue is the text `The Instructor entity has a nullable OfficeAssignment navigation property`, but this is not correct as the code actually creates a required property IF the Nullable Reference Types feature is enabled. Which is on by default for new projects BTW.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [Tutorial: Create a complex data model - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is rolled into the .NET 7 update.
