### ISSUE TITLE
Not applicable to container-to-container HTTPS communication

### ISSUE THREAD

**Issue by OliverRC** [dotnet/AspNetCore.Docs#25963]
The page only describes a docker-compose architecture with a single container exposed to the host on `localhost`.
It does not indicate that the dev-certs cannot be used for container-to-container SSL communication as the certificates are only valid for localhost domains, which the internal docker-compose network does not use since it uses it's own DNS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf7806c-d9e4-1811-3308-b5efb6f159f0
* Version Independent ID: 2117dfa1-9e6d-2bc2-2348-e792f3c81806
* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/docker-compose-https.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @ravipal
* Microsoft Alias: **ravipal**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
