### ISSUE TITLE
Partial VS PartialView Question

### ISSUE THREAD

**Issue by RickIsWright** [dotnet/AspNetCore.Docs#25971]
The article on partial views indicates to use the keyword Partial, which is not available directly in .NET Core 6 for MVC pages, as far as I can find.  I was able to use PartialView in lieu of.  If  I declare a PageBase pb = new PageBase(), I am then able to use PageBase.Partial(). The code in the article is confusing, as I can't find a Page that derives from PageBase when creating an MVC or Razor page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/25972
