### ISSUE TITLE
port tunneling in Visual Studio for ASP.NET Core projects

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#25977]
* [Dev tunnels in Visual Studio for ASP.NET Core projects](https://devblogs.microsoft.com/visualstudio/dev-tunnels-in-visual-studio-for-asp-net-core-projects/)

Add doc to the TOC in the Test section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [ASP.NET Core security topics](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 55316](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55316)

**Comment by vladboss61** [comment]
Does it work without IIS Express settings in the launchsettings.json ?
