### ISSUE TITLE
Partial or PartialView? Partial fails to Compile

### ISSUE THREAD

**Issue by RickIsWright** [dotnet/AspNetCore.Docs#25972]
The article on partial views indicates to use the keyword Partial, which is not available directly in .NET Core 6 for MVC pages, as far as I can find.  I was able to use PartialView in lieu of.  If  I declare a PageBase pb = new PageBase(), I am then able to use PageBase.Partial(). The code in the article is confusing, as I can't find a Page that derives from PageBase when creating an MVC or Razor page.
This Example for instance: 
```
public IActionResult OnGetPartial() =>
    Partial("_AuthorPartialRP");
```
Will not compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The sample compiles fine
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PartialViewsSample.Pages
{
    public class DiscoveryModel : PageModel
    {
        public void OnGet() => Page();

        #region snippet_OnGetPartial
        public IActionResult OnGetPartial() =>
            Partial("_AuthorPartialRP");
        #endregion
    }
}
```

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.

**Comment by Codgereight-hour** [comment]
I experienced the same difficulty and crafted a remedy https://testngxml58.github.io/unordered356/
