### ISSUE TITLE
How to access developer tools with this example?

### ISSUE THREAD

**Issue by dt200r** [dotnet/AspNetCore.Docs#25994]
Usual accessors Ctrl+Shift+I or F12 don't appear to work.

**Comment by guardrex** [comment]
@dt200r ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
