### ISSUE TITLE
Mention that you can use  "dotnet run --environment Production "

### ISSUE THREAD

**Issue by mpawelski** [dotnet/AspNetCore.Docs#26016]
There are different examples how to run dotnet app with different environment but this ones (the easiest IMO) are not:

```
dotnet run --environment Production
```
or
```
dotnet run -- --environment Production
```

I found it by accident on [this](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#change-the-content-root-app-name-and-environment-by-environment-variables-or-command-line) page but IMO it should be mentioned explicitly on "Use multiple environments in ASP.NET Core" documentation page also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by darul9061** [comment]
This is 2024. This has been mentioned since 2022. He is right and should be part of the "dotnet run command" doc
