### ISSUE TITLE
Clarify if middleware that was registered before branching with Map() is shared among both branches.

### ISSUE THREAD

**Issue by JVanloofsvelt** [dotnet/AspNetCore.Docs#26028]
When using Map() to branch a pipeline, if you want to use UseEndpoints() on that branch, it throws an error explaining that you need to call UseRouting() on that same branched pipeline as well. Normally the UseRouting() is implicitly configured to be at the start of the original pipeline, which confused me about whether or not the previously registered middleware is shared with the branched pipeline or not. Maybe it only applies to the UseRouting() and UseEndpoints() pair, maybe not. The documentation is not helping here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
