### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by dush-a** [dotnet/AspNetCore.Docs#26024]
[Enter feedback here]
Apply migration section https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-3.1&tabs=visual-studio#apply-the-migration

explains how to migrate a database with existing data. But at the end of the section, it says to delete existing data before updating the database. 

> _**Because the DbInitializer.Initialize method is designed to work only with an empty database, use SSOX to delete all the rows in the Student and Course tables. (Cascade delete will take care of the Enrollment table.)**_

> _**Run the app. Running the app runs the DbInitializer.Initialize method. The DbInitializer.Initialize populates the new database.**_

This defeated the purpose of the migration,  I deleted records as instructed but when you repopulate the database Student.ID  changed, for example, it changed the ID = 9 for Alexander, In a real situation, this is not acceptable. It makes no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Part 5, Razor Pages with EF Core in ASP.NET Core - Data Model](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, that part is not migration. Keep reading.
