### ISSUE TITLE
Link for "Add claims to Identity using IUserClaimsPrincipalFactory" doesn't lead to anywhere useful

### ISSUE THREAD

**Issue by wT-** [dotnet/AspNetCore.Docs#26032]
For ASP.Net 6 docs, the part of the [Add custom user data to Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-3.1) page that explains IUserClaimsPrincipalFactory was removed in this issue: https://github.com/dotnet/AspNetCore.Docs/issues/18797 but there's a link still at the bottom of this [Extend or add custom claims in ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0#add-claims-to-identity-using-iuserclaimsprincipalfactoryapplicationuser) page.

I'm not sure if the IUserClaimsPrincipalFactory is explained anywhere else right now. It's in the ASP.Net Core 3.1 version [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0#add-claims-to-identity-using-iuserclaimsprincipalfactoryapplicationuser).

Maybe the link should be removed for now until that section is added back somewhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666f14c7-d1cd-04cc-fb3f-fb91c6445f99
* Version Independent ID: b01e1351-d362-fd61-4dcb-bacb21559f76
* Content: [Mapping, customizing, and transforming claims in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @damienbod
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@wT-  can you supply a screen shot? I can't see the link.
