### ISSUE TITLE
Error found in compiling the code in program.cs    Compile Error can be fixed.  

### ISSUE THREAD

**Issue by jmgraceofbatonrouge** [dotnet/AspNetCore.Docs#26040]
[Enter feedback here]

You will obtain an compile error inside of program.cs at
   builder.Services.AddDatabaseDeveloperPageExceptionFilter()   

the error message is:
error cs1061 'iservicecollection' does not contain a definition for 'adddatabasedeveloperpageexceptionfilter'

You can fix the problem by installing the following NuGet  Package: 
    Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -Version 6.0.5

I found the above solution at:
  https://stackoverflow.com/questions/65007086/services-adddatabasedeveloperpageexceptionfilter-error-code-cs1061

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's in https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio#add-nuget-packages
