### ISSUE TITLE
Blazor Hybrid API doc cross-links

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#26044]
**UPDATES**

* **11/3/22**: Four appeared in the API docs since this issue was opened.
* **11/10/22**: Added the `UrlLoadingStrategy` enum for .NET 7.
* **12/19/22**: API docs should be online now. This issue is unblocked for work, which I hope to reach this week.
* **12/21/22**: Updating today for the latest API doc adds. Still missing a few.
* **12/23/22**: Added a NOTE on the `InitializeComponent` method where it's called out in the Hybrid docs.

Currently MIA ...

* `ExternalNavigationStarting`
* `ExternalLinkNavigationEventArgs`
* `ExternalLinkNavigationPolicy`

Prior MIA API that became available. The following have already received their API doc cross-links:

* ~`InitializeComponent`~: Generated at build time.
* ✔️ `Microsoft.Maui.Hosting.MauiApp`: `<xref:Microsoft.Maui.Hosting.MauiApp>`
* ✔️ `UseMauiApp`: `<xref:Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiApp%2A>`
* ✔️ `MauiAppBuilder`: `<xref:Microsoft.Maui.Hosting.MauiAppBuilder>`
* ✔️ `Microsoft.Maui.Storage`: `<xref:Microsoft.Maui.Storage>`
* ✔️ `UrlLoading`
* ✔️ `UrlLoadingEventArgs`
* ✔️ `UrlLoadingStrategy`
* ✔️ `Microsoft.AspNetCore.Components.WebView.WindowsForms`
* ✔️ `Microsoft.AspNetCore.Components.WebView.Wpf`
* ✔️ `AddMauiBlazorWebView`
* ✔️ `BlazorWebView`
* ✔️ `BlazorWebViewInitializing`
* ✔️ `BlazorWebViewInitialized`

**Comment by davidbritch** [comment]
@guardrex .NET MAUI's `InitializeComponent` method is generated by a source generator at app build time and added to the compilation object for the calling class. So there isn't an API doc for it.

**Comment by guardrex** [comment]
@davidbritch ... Are you aware if there's anything going on in the background to get the following API exposed in the API docs?

* ExternalNavigationStarting
* ExternalLinkNavigationEventArgs
* ExternalLinkNavigationPolicy

I'd like to be able to cross-link those to API docs in order to close this issue out.

**Comment by davidbritch** [comment]
@guardrex What namespaces are those types in?

**Comment by guardrex** [comment]
@davidbritch ... I see the problem!

Mackinnion and Tanay made changes to ***totally drop this API*** prior to the 6.0 release in favor of `UrlLoadingStrategy`, etc.

***However,*** I had a [7.0 release tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/26364) that referred to the ***older PU issue*** for the original work on the feature that included ***this API***. Well ... that API never made the cut for 6.0, which explains why it can't be found in the API docs 🙈😄. I dutifully followed my own broken roadmap tracking entry and added API to the topic that never existed in the first place.

I hate when this type of thing happens ... when these rotten 😈 get into the docs. However, we do have all of the correct API and API doc cross-links for the navigation features and the correct guidance for the feature. It's just this extra section of coverage that needs to be 🔪 out of the doc, which I'm taking care of right now on https://github.com/dotnet/AspNetCore.Docs/pull/28132.

*Sorry to have bothered you on this one!* I can close this issue out now. We have all of the API doc cross-links for all of the API that needs linking.
