### ISSUE TITLE
Error: The 'page' directive expects a string surrounded by double quotes.(RZ1016)

### ISSUE THREAD

**Issue by visheshcallin** [dotnet/AspNetCore.Docs#26043]
[Enter feedback here]

Issue found in example code:
for below Page directive to work
@page "{id:int?}"
you need to remove the double quotes around @item.ID in Index.chtml. 

The reference error code is: 
The 'page' directive expects a string surrounded by double quotes.(RZ1016)

Please re-visit and clarify.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Part 5, update the generated pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@visheshcallin  just tested sample in https://github.com/dotnet/AspNetCore.Docs/pull/26046/files and it works fine.
