### ISSUE TITLE
Add a topic on implementing Custom Authentication in Blazor Server

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#26050]
Hey @guardrex, it's your favorite end user again with another dynamite suggestion:

Add a topic (not sure where) on how to implement Custom Authentication in Blazor Server.

I am struggling to do this, and I have not found any guidance in the docs on this subject, except [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/?view=aspnetcore-6.0&pivots=maui)   But that topic is about Hybrid Blazor Apps, so it's not directly applicable to Blazor Apps.  It took me a great deal of search to even find that topic.

I have searched and searched, and there are no good blog posts or Stack-Overflow questions about this topic, so I think it would be a great one to add to the docs.  I am still struggling to adapt the Hybrid sample to a regular Blazor Server App.

I think doing Custom Authentication is a worthwhile topic, as Identity/Active Azure Directory/3rd Party Logins are only the start of ways to Authenticate End users.

In my scenario, I am creating a website for a company who wants users to not register, only input a few bits of information which is then validated against their existing user store.  If they pass the validation, then the user should be considered Authorized.  Seems like a valid use case for Custom Authentication.

Also, sense Authentication is an important topic to get correct, so some official guidance would be prudent.

So anyways, I just thought I would pass this on to you as I have spent quite a bit of time trying to work this out.

I think it would be a bit much to include directly in this topic, but a link to another article or a sample app would be great.

I would call it "Custom Authorization", although it is actually about implementing a custom AuthenticationStateProvider, but users searching for the topic are not going to know that. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75d9405-19a5-a14b-3a09-a3605b240750
* Version Independent ID: 1247ee64-fbc9-ce29-0710-f6e59380f5ee
* Content: [ASP.NET Core Blazor authentication and authorization](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi ... Blazor Server apps are ordinary ASP.NET Core apps, so the guidance in the main doc set applies. We won't provide further info than what u see in the Blazor Server node today per management's decision.

**Comment by gregoryagu** [comment]
Is there guidance in the main doc set for Custom Authentication?  If so, I cannot find it.  Maybe that would be a good place to add a non-Blazor specific article.  I would expect to find something [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0) on the topic.

**Comment by guardrex** [comment]
Not sure what you mean by "custom authentication." If you mean a custom `AuthenticationStateProvider`, it's covered here ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-6.0&tabs=visual-studio#implement-a-custom-authenticationstateprovider

... the dev can do anything they want in there with the claims principal and/or claims identity.

**Comment by gregoryagu** [comment]
Great, thank you Luke, that is exactly what I was looking for.  I don't know how I managed to miss that.

**Comment by gregoryagu** [comment]
One last suggestion:  When I was looking for this topic, I was looking under the "ASP.NET Core Blazor authentication and authorization" topic, under the "AuthenticationStateProvider Service" section.  At the end of this section, there are some links which say "For more information...."

I would like to suggest that you add a link to the above topic to this: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-6.0&tabs=visual-studio#implement-a-custom-authenticationstateprovider

This would have made it easy to find.  

For example:  "For more information on creating a Custom Authentication State Provider, see..."

Just my two cents.  I seriously spent quite some time searching for this and only found the topic because you gave it to me above.

**Comment by jereytucker** [comment]
commit # #

**Comment by jereytucker** [comment]
commit # #

**Comment by guardrex** [comment]
@jereytucker ... Please don't post random comments to issues and PRs here. This is an active repo with lots of work in progress, and these are generating pointless pings to the staff here (i.e., *ME* 😄 lol).
