### ISSUE TITLE
ClaimActionCollection does not contain a definition for 'MapJsonKey'

### ISSUE THREAD

**Issue by david-forster10** [dotnet/AspNetCore.Docs#26059]
When using the code snippet straight from the page within a Blazer Server app, receiving the following error:

> error CS1061: 'ClaimActionCollection' does not contain a definition for 'MapJsonKey' and no accessible extension method 'MapJsonKey' accepting a first argument of type 'ClaimActionCollection' could be found (are you missing a using directive or an assembly reference?)

#### dotnet info:

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-2.2#map-user-data-keys-and-create-claims)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by david-forster10** [comment]
That seems to have resolved the problem, thank you. It's weird because according to my Visual Studio Code it was detecting that ClaimActions was part of the `Microsoft.AspNetCore.Authentication` package so I wasn't aware it needed to be explicitly included as well.

**Comment by guardrex** [comment]
It's in the topic only in the first code example, probably because these code examples are sucked in from a sample app via snippets that don't capture that line at the very top of the file. I'm not sure if @Rick-Anderson will want to make any changes to the topic regarding this ... he'll see this later today.
