### ISSUE TITLE
Scope Validation link in the Recommendation section doesn't work

### ISSUE THREAD

**Issue by AbhilashKuvalkar** [dotnet/AspNetCore.Docs#26057]
In the "_Recommendation_" section, sixth point the "_Scope Validation_" link doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0#scope-validation-1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You need to be on the .NET 6 version
<img width="213" alt="image" src="https://user-images.githubusercontent.com/3605364/172034691-390ad571-da76-41d6-b7c4-1e6ccd1d608b.png">
