### ISSUE TITLE
I do not see why your documentation does include the name of nugget package one must install in order to get things rolling

### ISSUE THREAD

**Issue by jvelezc** [dotnet/AspNetCore.Docs#26081]
[Enter feedback here]
For example, I am having a compilation error about .bind extension method not being found. I can't find the nugget package for it. But if it was in the documentation... boy things would be so much easier...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No NuGet package needed.
