### ISSUE TITLE
Format response data for text/plain

### ISSUE THREAD

**Issue by Jakub27blue** [dotnet/AspNetCore.Docs#26080]
Hello everyone,
I want to set the [Produces ("text/plain")] attribute for a method that returns an int value. 
Unfortunately, the method returns a status code of 406.
**Code:**
```
        [Produces("text/plain")]
        public int Get()
        {
            return 1;
        }
```
**Request:**
without accept header
**Response:**
Error: response status is 406

In the [documentation](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0):

> By default, ASP.NET Core supports the following media types:
>application/json
>text/json
>text/plain

The documentation is not clear about this.
Do you know how to return an int value in text/plain format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
