### ISSUE TITLE
JSRuntime.InvokeVoidAsync not found

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/AspNetCore.Docs#26095]
There's no ` JSRuntime.InvokeVoidAsync` method in the latest release.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nicholasyin ... Inject a JS runtime instance for it at the top of the component file: `@inject IJSRuntime JSRuntime`. I'll update the section to call that out. Thanks for the issue. Leave this open, as it will close automatically when the PR merges.

**Comment by nicholasyin** [comment]
The point is that InvokeVoidAsync is not under JSRuntime, not JSRuntime itself. There're only several InvokeAsync method overloads.

**Comment by guardrex** [comment]
@nicholasyin ... I don't follow. It should be an extension ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.jsruntimeextensions.invokevoidasync?view=aspnetcore-6.0

Post a repro project to GH so that I can see the full app + component.

**Comment by nicholasyin** [comment]
See your point now. The method is an extension for IJSRuntime. Adding the @inject has cleared the error.
