### ISSUE TITLE
First MVC Tutorial Series: Update for .NET SDK 6.0.3.00 - Template changes

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#26094]
There are a few changes in the template for the .NET SDK 6.0.300 that require a new app sample update plus some changes in the Razor tutorial set.

- Nullable warnings are no longer encountered when following the tutorial because the generated `RazorPagesMovieContext.cs` file now makes the Movie property nullable.   This needs to be addressed both in the app sample and in [Razor Tutorial - Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code)
- Program.cs has changed and should be reflected in the app sample.
- Scaffolding output has changed.
- Packages have newer versions.
- Package manager screenshot needs to be updated to show Latest stable 6.0.5
- Migrations output has changed.
- Bootstrap has updated.

While I am updating I will also update a few screenshots of the running app sample.  Some show "2017" in them. Just to reassure folks that this tutorial is up to date.

Thanks to @rmeby for pointing out this needed an update.
See related #25862 for same update needed for Razor Tutorial series and app sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll focus on the .NET 7 version.
