### ISSUE TITLE
Specific support scenarios supported, limitations

### ISSUE THREAD

**Issue by jeffputz** [dotnet/AspNetCore.Docs#26107]
It would be helpful to have a specific matrix here of what is or isn't supported in the context of a web app. For example, I've found:
* If you enable response compression in your web app, it doesn't work, and browser link isn't inserted into pages. Lost a day trying to figure that one out. It fails silently.
* What is the connection between hot reload and browser link anyway? It doesn't seem like one works without the other, but this isn't explained anywhere. They're two different buttons in the UI.
* CSS and script (including Typescript, when `tsconfig.json` is set to compile on save) seems to work. But if it's in a dependent project, like a Razor Class Library, a valid scenario, it doesn't bubble to the web project even though Razor page edits do. It's fine if that's a limitation, but it should be called out.
* Updating a Razor view sometimes, but not always, triggers a total rebuild. I haven't read anything that explains that.

Thanks for taking the feedback, docs team!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Version Independent ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Content: [.NET Hot Reload support for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/hot-reload.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/hot-reload.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
