### ISSUE TITLE
Was a great tutorial until you got to DTO, and then the explanations assumed I already knew the topic

### ISSUE THREAD

**Issue by tradegear** [dotnet/AspNetCore.Docs#26108]
Once the tutorial got to this step:

    Update the code to use TodoItemDTO:

And I implemented the recommended code, and the instructions said:

    Verify you can't post or get the secret field.

What I can verify is that the project in Visual Studio no longer executes; it cannot open the browser and resolve to the localhost:port:  
HTTP ERROR 404
And if I use Postman to do a PUT in order to create a new entry, it returns an HTTP 405, Method not allowed.
And I am lost as to the purpose of why I would want to make my project error out, and effectively do nothing.
So the rest of the tutorial provided no meaning.
Whoever wrote this document must have run out of time to continue writing it, and pressed the "submit this article" button in a rush.
I do appreciate the effort put forth on the first part (that worked).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@tradegear, thanks for bringing this up.   I am sorry to hear about your experience.

The topic this issue on is for .NET 6.0+.   

This may be not related at all to where your project , but I'll mention just in case:  
Using the .NET 6.0 SDK or higher, the port number is randomly assigned.  I do see that this topic suggests as an example to use the URI: https://localhost:5001/todoitems. That needs to be updated and clarified for sure.  That would work for earlier versions of .NET as is, and while it is a valid example, it makes it sound like that is the exact URI to use, and it is not.  For 6.0 you need to look up the assigned port that gets randomly assigned when the project is created:

In your project, go to:  Properties/launchSettings.Json.  There you will see the `applicationURL` set for https:

`"applicationUrl": "https://localhost:7152;http://localhost:5152",`

In the previous example, the randomly assigned port is set to `7152`.   So the URL to test would be: `https://localhost:7152/todoitems`

Is there a very particular step for creating the DTO where you felt the doc started to need help?

You mentioned VS no longer executes.  If you build and run the app while debugging, are there any build or runtime errors that would give me a clue?

Finally, what version of Visual Studio are you using and was your project targeting ".NET 6.0 LTS" when you created it?

**Comment by Rick-Anderson** [comment]
Moving to a DTO is an advanced step where one needs to understand all the previous code.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
