### ISSUE TITLE
Clarify lines to add at a step in the Blazor-SignalR tutorial

### ISSUE THREAD

**Issue by Ricardoaraujo00** [dotnet/AspNetCore.Docs#26105]
In blazor webAssembly section.
In the section **Add a SignalR hub** we have this:

```
using Microsoft.AspNetCore.SignalR;

namespace BlazorWebAssemblySignalRApp.Server.Hubs
{
    public class ChatHub : Hub
    {
        public async Task SendMessage(string user, string message)
        {
            await Clients.All.SendAsync("ReceiveMessage", user, message);
        }
    }
}
```

But the compiles says it doesn't knows what the Clients are, right  after the await.
The `using Microsoft.AspNetCore.SignalR;` is not being underlined so it is detected even without adding any nuget package to the server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Ricardoaraujo00 ... I can't explain that behavior. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26105
```

... to the bottom of your opening comment so that I follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
btw @Ricardoaraujo00 ... When you say you didn't add a package, you must add the [`Microsoft.AspNetCore.SignalR.Client`](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client) package to the `BlazorWebAssemblySignalRApp.Client` project, so make sure that you did that. See ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-6.0&tabs=visual-studio&pivots=webassembly#add-the-signalr-client-library

**Comment by Ricardoaraujo00** [comment]
Thank you for your suggestion but I believe this is a documentation issue. I don't want to mess around with issues for the development team when I think it is documentation related.
If you try to implement SignalR in a clean WebAssembly application according to those instructions you will face the problem I'm reporting. If i find the problem I'll report it back here for documentation correction.

Thank you

**Comment by Ricardoaraujo00** [comment]
I'm sorry. Everything is fine with the code. The problem is that it is a bit susceptible to errors following along because the lines we are supposed to add up are mixed with lines that already exist in the base model, and for a proper standout maybe they should be in bold.

For example, I must add two lines of this code section:
`builder.Services.AddSignalR();
builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();
builder.Services.AddResponseCompression(opts =>
{
    opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
        new[] { "application/octet-stream" });
});`

And maybe they should standout be:
`**builder.Services.AddSignalR();**
builder.Services.AddControllersWithViews();
builder.Services.AddRazorPages();
**builder.Services.AddResponseCompression(opts =>
{
    opts.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
        new[] { "application/octet-stream" });
});**`

This way I know that I must add the first line. It was a lack of attention of mine, but nevertheless... I leave that suggestion.

**Comment by guardrex** [comment]
Ok ... that's fine ... except that I can't do that in the doc with the doc features that we have. Let me work on that tho ... I'm sure that I can distill it down and clarify what's being added where to solve that.
