### ISSUE TITLE
C# Mongodb in-memory database for unittesting 

### ISSUE THREAD

**Issue by sekarcse** [dotnet/AspNetCore.Docs#26116]
Hi,

Is it possible to have something in Mongodb  memory database for unit testing ?

**Comment by wadepickett** [comment]
@sekarcse, thanks for letting us know what you need.

This scenario is missing from the unit test documentation in this repository and could be added to existing content.

Just as a side note:
I think the only thing we have that is even somewhat close is part of the [.NET Microservices guide](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps)

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
