### ISSUE TITLE
What is the latest version of Blazor?

### ISSUE THREAD

**Issue by DebasisPaul** [dotnet/AspNetCore.Docs#26120]
[ I searched a lot but couldn't find it. Is  blazor is related to the .net release? Such as dot net 7, ASP dot net 7, Blazor ASP dot net 7. In fact, I want to know what is the latest version of blazor now? Release date or end support etc.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc28995-6784-a7d2-5c0b-9811a8d19c1a
* Version Independent ID: 1668c8fb-024c-c86d-d4d5-e22e3355c04b
* Content: [ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DebasisPaul ... Blazor is part of ASP.NET Core/.NET and follows the same release cycle. Therefore, you can get that information at ...

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

The current release is .NET 6.

.NET 7 is in development now, and I think the latest release of that is Preview 4. Preview 5 is probably close to release. If you check out Dan Roth's .NET Blog posts, you can see the announcements for what's in these early previews of ASP.NET Core 7.0 ...

https://devblogs.microsoft.com/dotnet/author/danroth27/

The roadmap that the product unit maintains shows all of the items under consideration and complete ...

https://github.com/dotnet/aspnetcore/issues/39504

That roadmap is updated as they go. Things are added and subtracted at any time all the way up to the Release Candidate.
