### ISSUE TITLE
Using Graph API with Azure AD B2C from Blazor WASM

### ISSUE THREAD

**Issue by korteksz** [dotnet/AspNetCore.Docs#26127]
Hello,

I've been trying to implement a solution based on [this page](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-6.0#graph-sdk) for a Blazor WASM application which is using Azure B2C for authentication.

I imagine the solution as follows:
- I want to use Azure AD B2C for user management (already works)
- When a user logs in then I want to fetch all of the belonging Security Group entries from Azure AD B2C and add them to the Claims as a Role on Blazor WASM side (I was able to do it from Blazor Server, but not yet from Blazor WASM) so that I can use Authorize attribute base on it on the pages. This role mapping would be done in the CustomAccountFactory -> CreateUserAsync() method.

I am a little bit confused now whether if it's possible, that is why I am writing this issue. I found a [post](https://stackoverflow.com/questions/71517488/blazor-wasm-using-azure-ad-b2c-fails-calling-microsoft-graph-api) which is saying that I should create a deamon app instead and call the Graph API through this one, but this seems a bit overkill to me and I would expect that this is possible from WASM easily only I haven't found the way yet. 

Here you can see my code snippets and in the comments my observations:

Program.cs:
```
//Copied from https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-6.0#graph-sdk
builder.Services.AddGraphClient("https://graph.microsoft.com/User.Read.All", "https://graph.microsoft.com/Group.Read.All", "https://graph.microsoft.com/GroupMember.Read.All");
builder.Services.AddMsalAuthentication<RemoteAuthenticationState, RemoteUserAccount>(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.LoginMode = "redirect";

    //API scope
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://{domain}.onmicrosoft.com/{apiClientId}/access_as_user");

    //If I uncomment these lines and leave the above line active as well, then I get into infinite redirect loop when the application starts up
    //options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/User.Read.All"); 
    //options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/Group.Read.All");
    //options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/GroupMember.Read.All");

}).AddAccountClaimsPrincipalFactory<RemoteAuthenticationState, RemoteUserAccount, CustomAccountFactory>();

```

NoOpGraphAuthenticationProvider.class:
```
public async Task AuthenticateRequestAsync(HttpRequestMessage request)
{
     var result = await TokenProvider.RequestAccessToken(new AccessTokenRequestOptions()
     {
           Scopes = new[] { "User.Read.All" }
     });
                
      //The token is always null here
      if (result.TryGetToken(out var token))
      {
           request.Headers.Authorization ??= new AuthenticationHeaderValue("Bearer", token.Value);
      }
}
```

So basically my biggest problem is that I don't know how to connect from Blazor WASM to Azure B2C through Graph API. There is nothing in the document which would imply that it is not possible, however if it isn't indeed then please extend the documentation with it and mention a way, how it can be absolved then.

Looking forward for you reply and thanks in advance!

Greetings,
korteksz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896be20d-1321-0e2f-3efb-d0ce8f1e631a
* Version Independent ID: f5e2b80f-9478-7500-2bc5-930237274f4b
* Content: [Use Graph API with ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/graph-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/graph-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @korteksz ... That's correct AFAIK, and Azure docs don't mention it or have any samples of this scenario ... only for AAD. I've read exactly the same thing, namely that for a B2C scenario with WASM that a separate web API is probably the best approach. 

This whole Blazor security node is due for an overhaul, which I hope to be able to perform in July. I'll include a link to this issue in my tracking for that work so that I add a remark to the topic on this unsupported scenario.
