### ISSUE TITLE
Delete Database Update-Database 

### ISSUE THREAD

**Issue by panthia** [dotnet/AspNetCore.Docs#26124]
I am getting lost in the tutorial at this point (Part 7 - Add A Migration): 

> Delete all the records in the database, the initializer will seed the database and include the Rating field. Deleting can be done with the delete links in the browser or from Sql Server Object Explorer (SSOX).

> Another option is to delete the database and use migrations to re-create the database. To delete the database in SSOX:

I am using Visual Studio 2022, in the instructions 1-5 after "Another option ..." I never see the check option, 

> 3. Check Close existing connections.

 I have not been able to get the database back once it has been deleted. 

It seems the steps 1 to 5 are related to option 1 in how to resolve the `SqlException: Invalid column name 'Rating'.` but I am not really sure.  

It would be helpful if there were full separate instructions for each of the three options to handle the SqlException. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Part 7, add a new field](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> I have not been able to get the database back once it has been deleted.

per the instructions, run

`Update-Database`
