### ISSUE TITLE
Github Download Not allowed

### ISSUE THREAD

**Issue by pgaTechnology** [dotnet/AspNetCore.Docs#26134]
[Enter feedback here]
Attempting to download finished project from github. Trying to find why my project is failing. When I try to download using github desktop it asks for authentication. when browsing github it doesn't allow me to download any files, only view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pgaTechnology ... Download the ZIP of the entire repo and then use the path to the sample to get the sample app. Guidance is here ...

https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-6.0#how-to-download-a-sample
