### ISSUE TITLE
UNEXPECTED BEHAVIOUR

### ISSUE THREAD

**Issue by Coscotex101** [dotnet/AspNetCore.Docs#26131]
[Edit by guardrex to fix the code blocks. @Coscotex101 ... it's a triple-backtick on separate lines above and below code blocks.]

Hi,
I don't know if this is a bug, but I'm getting an unexpected behaviour. I get it, when I modify your "EventCallback" example.

**Shared/Child.razor:**

![image](https://user-images.githubusercontent.com/48105603/173337339-2b6fab1f-5cd0-41a2-b9ae-bfee019c1a05.png)

```razor
@code {

    public List<string> DataSource = new List<string>{"cow", "dog", "pig", "rat"};

    [Parameter]
    public string Title { get; set; }

    [Parameter]
    public RenderFragment ChildContent { get; set; }

    [Parameter]
    public Func<string, Task> OnClickCallback { get; set; }
}
```

**Shared/Parent.razor:**

```razor
@inject IJSRuntime JS
```

![image](https://user-images.githubusercontent.com/48105603/173334126-007b91d8-d2e2-4022-bc0f-35ee0cdd2543.png)

```razor
@code {
    private string message;
    public Func<string, Task> ShowMessageHolder{ get; set; }

    protected async override Task OnAfterRenderAsync(bool firstRender)
    {
        ShowMessageHolder= ShowMessage;
    }

    private async Task ShowMessage(string str)
    {
        await JS.InvokeVoidAsync("alert", str);
    }
}
```

**Expected Result**: I get a list of buttons with different labels with the following Labels => "cow", "dog", "pig", "rat". And when I click on any of the button, I should get a pop-up alert displaying the label text of the button I clicked.

**Actual Result**:  I get a list of buttons with different labels with the following Labels => "cow", "dog", "pig", "rat".  But when I click on the button, I get a pop-up alert displaying "rat" regardless of whatever button I'm clicking.

I don't know, is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Coscotex101** [comment]
Hi, it works now. Although I didn't show it in the example I gave above. I assigned a default handler to OnClickCallback in the child component.

```
[Parameter]
    public Func<string, Task> OnClickCallback { get; set; } = DoNothingAsync;
private static async Task DoNothingAsync(string param)
    {
        await Task.CompletedTask;
    }
```

 And that made it behave wierdly. I removed the default handler in the child component, cleaned and rebuild my project, and it works now.

**Comment by guardrex** [comment]
btw @Coscotex101 ... There's an [alternative approach in the *Binding* topic](https://docs.microsoft.com/aspnet/core/blazor/components/data-binding#binding-with-component-parameters) that might be a hair cleaner ... certainly easier for my simple 🦖🧠 to comprehend! 😆

 I updated it along these lines as ...

`Child.razor`:

```razor
<h1>@Title</h1>

<p>
    @foreach (var item in DataSource)
    {
        <button @onclick="() => UpdateFromChild(item)">
            @item
        </button>
    }
</p>

@code {
    public List<string> DataSource = new () {"cow", "dog", "pig", "rat"};

    [Parameter]
    public string? Title { get; set; }

    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    [Parameter]
    public string? Item { get; set; }

    [Parameter]
    public EventCallback<string> ItemChanged { get; set; }

    private async Task UpdateFromChild(string s)
    {
        await ItemChanged.InvokeAsync(s);
    }
}
```

`Parent.razor`:

```razor
@page "/parent"

<h1>Parent-child example</h1>

<Child Title="Panel Title from Parent" ItemChanged="@ShowItem">
    Content of the child component is supplied by the parent component.
</Child>

<p>@item</p>

@code {
    private string? item;

    private void ShowItem(string s)
    {
        item = s;
    }
}
```

**Comment by Coscotex101** [comment]
> btw @Coscotex101 ... There's an [alternative approach in the _Binding_ topic](https://docs.microsoft.com/aspnet/core/blazor/components/data-binding#binding-with-component-parameters) that might be a hair cleaner ... certainly easier for my simple 🦖🧠 to comprehend! 😆
> 
> I updated it along these lines as ...
> 
> `Child.razor`:
> 
> ```
> <h1>@Title</h1>
> 
> <p>
>     @foreach (var item in DataSource)
>     {
>         <button @onclick="() => UpdateFromChild(item)">
>             @item
>         </button>
>     }
> </p>
> 
> @code {
>     public List<string> DataSource = new () {"cow", "dog", "pig", "rat"};
> 
>     [Parameter]
>     public string? Title { get; set; }
> 
>     [Parameter]
>     public RenderFragment? ChildContent { get; set; }
> 
>     [Parameter]
>     public string? Item { get; set; }
> 
>     [Parameter]
>     public EventCallback<string> ItemChanged { get; set; }
> 
>     private async Task UpdateFromChild(string s)
>     {
>         await ItemChanged.InvokeAsync(s);
>     }
> }
> ```
> 
> `Parent.razor`:
> 
> ```
> @page "/parent"
> 
> <h1>Parent-child example</h1>
> 
> <Child Title="Panel Title from Parent" ItemChanged="@ShowItem">
>     Content of the child component is supplied by the parent component.
> </Child>
> 
> <p>@item</p>
> 
> @code {
>     private string? item;
> 
>     private void ShowItem(string s)
>     {
>         item = s;
>     }
> }
> ```

Thanks a lot, for giving this some attention. But just me thinking, why should the scope of "obj" affect the results in my code. If i place it within the foreach loop -> it works as expected, but if I paste it  before the foreach loop -> it acts wierdly.

Thanks again
