### ISSUE TITLE
Info about how to setup authentication, or a link to it would be helpful

### ISSUE THREAD

**Issue by Vaccano** [dotnet/AspNetCore.Docs#26139]
Getting swagger to authenticate with Azure AD is very hard.  Having some info here, or a link to a place with instructions on how to get swagger authenticating with Azure AD using `Microsoft.Identity.Web` would be great!

(Or even better, just have your template that sets up a connection to Azure AD using `Microsoft.Identity.Web` also configure swagger to authenticate.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
