### ISSUE TITLE
Incorrect explanation of lifecycle

### ISSUE THREAD

**Issue by joostvz** [dotnet/AspNetCore.Docs#26132]
The explanation and diagrams describing the lifecycle of Razor components is incorrect and misleading. Also see this closed issue: https://github.com/dotnet/AspNetCore.Docs/issues/22742.

I spend a few hours today finding out why I got a `NullReferenceException` while my `OnInitializedAsync` was not finished yet. Based on the diagrams and the documentation I thought the rendering would only take place **after** the `OnInitializedAsync` was completed (awaited). But looking at [the source code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs#L229-L262), rendering is also executed **before** any awaiting is done. 

So if you use `OnInitializedAsync` or `OnParametersSetAsync`, you have no guarantee that these methods are finished before the rendering is done.  Please update the docs to reflect this, or at least add a remark that the diagram is an oversimplification. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a970fb72-3dd0-d173-585d-2ccdd7923f81
* Version Independent ID: 4871f4f7-9cf6-ac7a-0f21-c65d34bd1119
* Content: [ASP.NET Core Razor component lifecycle](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#handle-incomplete-async-actions-at-render)
* Content Source: [aspnetcore/blazor/components/lifecycle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @joostvz ... I'll ping Steve to ask about this. He said earlier that one might need to do exactly what you did ... consult the ref source ... because the diagrams and explanations are simplifications and that the logic in the framework is too complex to show/explain simply. However, your last line ...

> you have no guarantee that these methods are finished before the rendering is done

... might be what those two sections can explain to cover it. I'll ping him shortly to see what he'd like to do.

**Comment by guardrex** [comment]
@joostvz ... Can you clarify further what's "incorrect"? The section ...

https://docs.microsoft.com/aspnet/core/blazor/components/lifecycle#handle-incomplete-async-actions-at-render

... states ...

> Asynchronous actions performed in lifecycle events might not have completed before the component is rendered. Objects might be null or incompletely populated with data while the lifecycle method is executing. Provide rendering logic to confirm that objects are initialized. Render placeholder UI elements (for example, a loading message) while objects are null.

**Comment by joostvz** [comment]
@guardrex Good point, I didn't notice that section. I think I didn't notice it because [the Lifecycle events section](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#lifecycle-events) explicitly states:

> Call [OnInitialized{Async}](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#component-initialization-oninitializedasync). If an incomplete [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is returned, the [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is awaited and then the component is rerendered.

Also the diagram in this section confirms this statement, so I didn't have reasons to believe otherwise.

Indeed, I think a remark with a cross-link to the other section might help.
