### ISSUE TITLE
Code provided to initially add search filter box to index.cs page has error.

### ISSUE THREAD

**Issue by fairlite2u** [dotnet/AspNetCore.Docs#26147]
[Enter feedback here]
The code snippet provided to add the form containing the searchString filter box has an error (8th code snippet box). 
The code provided to add is:
<form asp-controller="Movies" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString"/>
        <input type="submit" value="Filter"/>
    </p>
However, name="SearchString" should actually be asp-for="SearchString" so the MovieGenreViewModel is accessed.

It is shown incorrectly in one more code snippet before being corrected in the "Add search by genre to the Index view" section to: 
        Title: <input type="text" asp-for="SearchString" />
But if someone, like me, only adds/updates the green highlighted code in their own code, they miss the corrected line of code for the SearchString reference. Then it takes a while to figure out why the searchString isn't retained in the search filter box (which, by the way, was supposed to work before the corrected code appears - "When the user searches for the item, the search value is retained in the search box." - line right before the code snippet with the corrected code. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Part 7, add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll fix this in the .NET 7 push
