### ISSUE TITLE
Does not work for a api project in .net 6. I have tried the default binding policy.

### ISSUE THREAD

**Issue by WasiqulIslam** [dotnet/AspNetCore.Docs#26146]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The sample published to https://cors1.azurewebsites.net works.

**Comment by WasiqulIslam** [comment]
Great, thanks for the information. I'll try that hopefully soon.

**Comment by WasiqulIslam** [comment]
hi,

Sorry to say that, I only can test the code. I don't get the original
source code from there.

Thanks,
Wasiqul Islam
