### ISSUE TITLE
Show how to log in Program.cs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26143]
This is a [frequent request at StackOverflow](https://stackoverflow.com/questions/45220938/logging-within-program-cs).

How about the following code:

```
var builder = WebApplication.CreateBuilder(args);

var logger = LoggerFactory.Create(config =>
{
    config.AddConsole();
    config.AddConfiguration(builder.Configuration.GetSection("Logging"));
}).CreateLogger("Program");

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.MapGet("/Test", async context =>
{
    logger.LogInformation("Testing logging in Program.c");
    await context.Response.WriteAsync("Testing");
});

app.Run();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ericstj please review or suggest another reviewer.

**Comment by ericstj** [comment]
@dotnet/area-extensions-logging crew please have a look.

**Comment by tarekgh** [comment]
It is a good idea to have a doc describing logging in simple scenarios. The one listed here is good but can feel it is mostly for aspnet scenarios. We have a doc which describe using the logging with the host https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#create-logs-in-main. We can have a conceptual doc listing samples for different scenarios like console apps, UI apps, aspnet,...etc.

**Comment by Rick-Anderson** [comment]
> . The one listed here is good but can feel it is mostly for aspnet scenarios.
Yes, this an ASPNET Core doc.

> We have a doc which describe using the logging with the host https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#create-logs-in-main. We can have a conceptual doc listing samples for different scenarios like console apps, UI apps, aspnet,...etc.

At the top of the doc we point to .NET logging: 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/3605364/173695612-393015cc-617b-4529-99b7-ff931800e538.png">

> We have a doc which describe using the logging with the host https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#create-logs-in-main. 

But those samples don't use the new minimal host that folks using ASP.NET Core 6.0 use.

**Comment by maryamariyan** [comment]
Another small snippet:

```c#
        using var loggerFactory = LoggerFactory.Create(builder =>
        {
            builder.AddSimpleConsole(i => i.ColorBehavior = LoggerColorBehavior.Disabled);
        });

        var logger = loggerFactory.CreateLogger<Program>();
```

**Comment by Rick-Anderson** [comment]
@Tratcher  `@tarekgh` approved this code in #26143 but you might want to take a quick look to see if that's how ASP.NET Core folks should be logging in `Program.cs`
