### ISSUE TITLE
Get request context in HttpContextInBackgroundThread

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26150]
In https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/Program.cs#L33-L52

@fiyazbinhasan 
I'd like use the request context to log the user agent. How do I get the context?

```
app.MapGet("/", async context =>
{
    await context.Response.WriteAsync("HelloMessage");
});
```

**Comment by fiyazbinhasan** [comment]
you mean something like this?

```
app.MapGet("/", async context =>
{
    await context.Response.WriteAsync(context.Request.Headers["user-agent"].ToString());
});
```

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  exactly, but I'd like to do it in https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context/samples/6.x/HttpContextInBackgroundThread/Program.cs#L33-L52

which has a different delegate.

**Comment by fiyazbinhasan** [comment]
You can overload the parameters like this,

```
app.MapGet("/branches", async (IHttpClientFactory httpClientFactory, HttpContext context, ILogger<Program> logger) =>
{
    logger.LogInformation(context.Request.Headers["user-agent"].ToString());
   
    .....
}
```

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan perfect. Thanks!
