### ISSUE TITLE
.NET 7: dotnet user-jwts

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26155]
Create new doc for `dotnet user-jwts` under Secrets management.

See 
* [ASP.NET Core updates in .NET 7 Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/)
* https://github.com/dotnet/aspnetcore/pull/42125

**New doc title**: Create and manage JWTs for development
**Location**: 
![image](https://user-images.githubusercontent.com/3605364/173941329-e468bc13-9171-4080-9006-2a994040d210.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: will be **_sibling_** of [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@captainsafia please review `dotnet user-jwts` doc plan. I can start this tomorrow if you like.

**Comment by captainsafia** [comment]
I think it might make more sense to put the doc under the "Authentication" segment instead of secrets management since it is more tied to auth than secrets.

**Comment by Rick-Anderson** [comment]
> I think it might make more sense to put the doc under the "Authentication" segment instead of secrets management since it is more tied to auth than secrets.

I can put it in both places unless you think it should only show up under Authn.

**Comment by Rick-Anderson** [comment]
@captainsafia please review. Note, my instructions worked last week. Today when I test I get the following error in the curl console:

```
HTTP/1.1 401 Unauthorized
Content-Length: 0
Date: Wed, 27 Jul 2022 03:09:35 GMT
Server: Kestrel
WWW-Authenticate: Bearer error="invalid_token", error_description="The signature key was not found"
```

And there's no logging information to help out.
