### ISSUE TITLE
Host blazor webassembly app with same base path locally and on the website, to avoid manually changes of base tag after publish.

### ISSUE THREAD

**Issue by engineerTrooper** [dotnet/AspNetCore.Docs#26170]
This issue is picking up on: [#40205](https://github.com/dotnet/aspnetcore/issues/40205)
But I can't add any information there because of *limited conversation*.

----------------------------------------------------------------------------------------------

It is good and a fine solution to change the *base path*, but to do that every time manually... 

I used some tries with time and reading in different forums and websites. I saw some JavaScript solutions, which will executed on client side in web browser, but that isn't feeling clean... 

The following solution is a suggestion to add into the documentation. The solution will stop the changing of the base URL by hand after publish. Also, it gives the benefit to work locally without any path-problems to access the files or other routing issues. This is helpful if you develop a **Standalone Blazor WebAssembly**. For the other use case as **Blazor Server App** I not speak here.

Two steps are required:

1. edit inside the ```wwwroot/index.html``` the base tag to: ```<base href="/<yourapp>/" />``` like it is [described in the documentation](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path) already.
2. add or change three lines inside the project ```launchSettings.json``` under ```"profiles"``` to the following:

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:18552",
      "sslPort": 44326
    }
  },
  "profiles": {
    "AbbreviationPresenter": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "<yourapp>",
      "commandLineArgs": "--pathbase=/<yourapp>",
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/<yourapp>/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "applicationUrl": "https://localhost:7081;http://localhost:5081",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
**Note:** Make sure you were setting the ```/``` in your code correct, like the snippets above!

What do you think about that suggestion and workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-6.0&tabs=visual-studio#app-base-path)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, @engineerTrooper ... *Great idea!* It can appear right after the manual approach for setting the pathbase with `dotnet run`. I'll get this scheduled for work and probably have it written up next week. I'll ping u on the PR when it goes up.
