### ISSUE TITLE
Error!!

### ISSUE THREAD

**Issue by ramamanigomathi** [dotnet/AspNetCore.Docs#26174]
Webapplication:createbuilder line webapplication does not exist in the current context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
`WebApplication.CreateBuilder` is part of 6.0, if it doesn't exist you are using a different version of the framework and should select the version you are using in the version selector. For example for 5.0 docs go here:
https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-5.0&tabs=visual-studio

**Comment by wadepickett** [comment]
Closing this issue. If this turns out not to be related selecting a topic version that aligns with the version of .NET you are using, feel free to comment and reopen.  Thanks.
