### ISSUE TITLE
Sub-section for Hot Reload appears twice on the page

### ISSUE THREAD

**Issue by Victor-Tseng** [dotnet/AspNetCore.Docs#26191]
**Hot Reload** is mentioned twice with similar descriptions but different links to reference materials:

### [Hot Reload](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#hot-reload)
Quickly make UI and code updates to running apps without losing app state for faster and more productive developer experience using [Hot Reload](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0). For more information, see [Update on .NET Hot Reload progress and Visual Studio 2022 Highlights](https://devblogs.microsoft.com/dotnet/update-on-net-hot-reload-progress-and-visual-studio-2022-highlights/).

### [Hot Reload](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#hot-reload-1)
Hot Reload minimizes the number of app restarts after code changes. For more information, see [.NET Hot Reload support for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0).

Please consider revising the two sections into one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Victor-Tseng ... I'll fix that up right now.
