### ISSUE TITLE
Why aren't Swagger services added to DI container conditionally (only in development)?

### ISSUE THREAD

**Issue by Dillion132** [dotnet/AspNetCore.Docs#26195]
When using the ASP.NET core Web API template to create an API application with OpenAPI support (Checked the Enable OpenAPI support). The Program.cs file is below:

![image](https://user-images.githubusercontent.com/16394302/174765288-0aa509c5-4a6c-4aae-bfc9-7f8eb7cc3efd.png)

As we can see, the UseSwagger() and UseSwaggerUI() middleware are activated only in development. But why AddEndpointsApiExplorer() and AddSwaggerGen() are not activated only in development as well. 

I know we can add Swagger services to the DI container conditionally using the following code. But I hope this operation can be achieved by design, it will auto generate after creating the application using the template.

```
builder.Services.AddEndpointsApiExplorer();
if(builder.Environment.IsDevelopment())
{
    builder.Services.AddSwaggerGen();
}
```

Environment: VS 2022, Asp.Net 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by wadepickett** [comment]
Hi @Dillion132,
Thanks for providing the product feedback.  For this product change/feature you would like to file, please select to provide feedback on "This Product" at the bottom of the page.  Then you are filling an issue on the product at the product repository.  You can copy paste to a new issue there and consequently receive notification as it is reviewed.

![image](https://user-images.githubusercontent.com/10985336/174888273-6373bbfe-2596-4661-8ded-efb67805fe68.png)


1. Go here: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio)
2. Select to provide feedback to "This Product" at the bottom of the page.
