### ISSUE TITLE
Scaffolding | Installing Nuget Packages Takes Multiple Hours

### ISSUE THREAD

**Issue by drcrook1** [dotnet/AspNetCore.Docs#26201]
[Enter feedback here]

I hit the part were we scaffold out and its literally been "Installing Nuget Packages" for the past 2 hours and it still hasn't completed.
![image](https://user-images.githubusercontent.com/6099287/174807714-ba913daa-9bb6-4886-b0f4-4aeb1c67a245.png)

Maybe its possible to modify this doc to install those seperately and then scaffold?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I haven't heard that problem before
