### ISSUE TITLE
More Documentation on the overload for ConfigureServices and Config IOptions.

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/AspNetCore.Docs#26222]
I think you need to include more documentation on around passing in the `context` to `ConfigureServices` into use its Configuration object.

Example:

```c#
var host = Host.CreateDefaultBuilder(args)
    .ConfigureHostConfiguration(options =>
    {
        options.AddJsonFile("appsettings.json");
    })
    .UseWindowsService(options =>
    {
        options.ServiceName = "Example Service Name";
    })
    .ConfigureServices((context,services) =>
    {
        services.AddOptions()
            .Configure<PositionOptions>(context.Configuration.GetSection(nameof(PositionOptions)))
            .AddHostedService<Worker>()
            .AddLogging()
    })
    .Build();
```

Another way of configuring which might not be obvious to people. Wasn't to me!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We won't be updating the 3.1 version. Why aren't you using the new minimal host and .NET 6?
