### ISSUE TITLE
Microsoft.AspNetCore.SignalR Package marked as deprecated

### ISSUE THREAD

**Issue by ArunoDh** [dotnet/AspNetCore.Docs#26224]
Dear,

The example showing on this page uses the nuget package that uses Microsoft.AspNetCore.SignalR, which is flagged as deprecated.
As I currently don't find any other package to use, I keep using this one.

I try to setup a .NET 6 API that uses SignalR. It works with the deprecated package, for now.

Regards,
Arno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Tutorial: Get started with ASP.NET Core SignalR using TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by ArunoDh** [comment]
Regarding the docs you are right, i'm sorry.
I tried to create a new hub in a secondary library, there you do need to install it as a package.

That's not within the example's scope.

Sorry again and thank you for your time

**Comment by BrennanConroy** [comment]
> there you do need to install it as a package.

No you don't, you should instead reference the shared library: https://docs.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio

**Comment by ArunoDh** [comment]
@BrennanConroy I just checked it out and this works like a charm. 
I guess I didn't read enough on the .NET 6 framework to know about it. 
Thanks for the quick answers and guidance, appreciated!
