### ISSUE TITLE
Describe support and/or configuration for RCL and Typescript scenarios

### ISSUE THREAD

**Issue by jeffputz** [dotnet/AspNetCore.Docs#26227]
For some context: https://github.com/MicrosoftDocs/visualstudio-docs/issues/8093

Deeper explanation of how to configure, and options in project files, would be great. Right now it's largely magic. For example, I can see it work even when I save a Typescript file in a web project, but if the TS file is in a Razor Class Library that the web project references, it doesn't reload. If I save a .cshtml file in the RCL, it does propagate the change to the web project that references it. Are these limitations in implementation or configuration or something else?

Maybe what I'm really suggesting is that the doc should describe what front-end client code change scenarios are and are not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Version Independent ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Content: [.NET Hot Reload support for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/hot-reload.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/hot-reload.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of your issue #26107
Please add to that issue.
