### ISSUE TITLE
.NET 7: Create "What's new in 7.0 previews"

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26229]
Historically we publish this article just before release. I'd like to get started. Until the final preview, it will be titled "What's new in 7.0 previews"
![image](https://user-images.githubusercontent.com/3605364/175751262-9b97b14b-f127-4789-ba0b-5fe4dc212c49.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Version Independent ID: 3e9c3677-ab1b-2466-6c19-71111b49f84a
* Content: [What's new in ASP.NET Core 6.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-6.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-6.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danroth27  @Pilchie  @LadyNaggaga @mkArtakMSFT @rafikiassumani-msft  @adityamandaleeka  OK if I get started now?

**Comment by Pilchie** [comment]
Love it - the EF team does something similar early in the release with the plan, and then updates it with each preview.
