### ISSUE TITLE
Disabling Caching

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#26235]
Would appreciate a paragraph devoted to explaining how best to disable caching throughout a Core MVC Web application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-6.0)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @xenophilios ... *Perhaps, yes!* I searched and found general filters coverage and general `ResponseCacheAttribute` coverage **_but_** didn't find the simple approach of ...

```csharp
builder.Services.AddControllersWithViews().AddMvcOptions(options => 
    options.Filters.Add(
        new ResponseCacheAttribute
        {
            NoStore = true, 
            Location = ResponseCacheLocation.None
        }));
```

... which perhaps could appear at the bottom of the "*NoStore and Location.None*" section at ...

https://docs.microsoft.com/aspnet/core/performance/caching/response#nostore-and-locationnone

... and side note that setting `Duration = 0` in that existing guidance is a no-op I think 🤔 and probably should be removed.

Rick will be along in a bit to say if I'm making any sense here ... *I'm only on my first cup!* ☕😆

**Comment by guardrex** [comment]
I have a second here ... I'll go ahead and toss that into a PR in case Rick likes it. Let's take this discussion up further on the PR if that will do the trick. *Stand-by* for a few minutes while I whip that up.
