### ISSUE TITLE
Create a new class named SeedData in the models folder, needs clarity and explanation.

### ISSUE THREAD

**Issue by TimothyMalahy** [dotnet/AspNetCore.Docs#26237]
Documents say to "Create a new class named SeedData" in the _models_ folder. This could use clarity. Are they asking me to overwrite Movie.cs in models? Are they asking me to make a new file and put a class in it called SeedData?

Both things I attempted didn't seem to resolve the issue I had.

[Seed the database instructions](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md#visual-studio-code--visual-studio-for-mac-2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by TimothyMalahy** [comment]
Adding to this, watched a tutorial that helped a bit. I think that it would be important to reference "SeedData.cs" is a class, and maybe remove "Replace the generated code with the following:"

This appears that it is due to instructions being written for visual studio initially, but unless I missed something VSCode does not "create classes" the same was visual studio does.

**Comment by Rick-Anderson** [comment]
The instructions are pretty clear, I'm sorry you had problems with them.

**Comment by TimothyMalahy** [comment]
Would it not benefit users, as a tutorial to clarify to 'create a class file containing a class', not just a 'create a class'

Especially since it reference "Replace the generated code with the following:"  

If you make it on VSCode it has no generated code, since it's a blank file. Visual Studio though would generate code...

It currently reads like this from a VSCode or other text editor

1. "Create a class called SeedData" in the models folder
2. Replace the generated code with the following


What I first tried, before solving it was.

Overwrite Models\Movie.cs 's generated code with the C# code in the instructions. Because I had no file with generated code other than that one.
