### ISSUE TITLE
How to download the project RazorPagesMovie60?

### ISSUE THREAD

**Issue by hsnprojects** [dotnet/AspNetCore.Docs#26234]
"Tutorial: Get started with Razor Pages in ASP.NET Core" from the following url:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio

has a section "Troubleshooting with the completed sample" and that states that we can "download completed project" from GitHub.

But I do not see a project under that name, it is actually a folder -  does that mean that I have to download the whole "dotnet/AspNetCore.Docs" in order to download that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hsnprojects ... That's correct. Take the ZIP of the repo, decompress, and navigate to the sample per the *How to download a sample* section at ...

https://docs.microsoft.com/aspnet/core/introduction-to-aspnet-core#how-to-download-a-sample
