### ISSUE TITLE
There is no example for blazor WASM. 

### ISSUE THREAD

**Issue by UrielMhezzek** [dotnet/AspNetCore.Docs#26246]
[Enter feedback here]
There is no example for blazor WASM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8bc6ab-a440-d860-e40c-8f18aa1eafb3
* Version Independent ID: 8a5b47e7-b29c-b049-30e8-5b405a5086b6
* Content: [ASP.NET Core Blazor environments](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @UrielMhezzek ... The whole topic only applies to Blazor WebAssembly.
