### ISSUE TITLE
Transitioning to HTML needs more information.

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/AspNetCore.Docs#26247]
The section on Transitioning to HTML states:

"The default language in a code block is C#, but the Razor Page can transition back to HTML", 

but it provides no explanation of the scope of that transition - at what point the transition starts, and (more importantly) at what point the transition ends and the interpretation reverts back to C# code.
 
The implication is that it might be triggered by an html `<tag>`, and continues until it finds the balancing `</tag>`, but that is just guesswork on my part - it really needs to be stated explicitly in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
From#26248

The documentation talks about @{ } code blocks, but then goes on to separately talk about Control Structures (like @if and @foreach), but does not explain why these two separate approaches exist that appear to achieve the same result.

For example, what is the distinction between doing:
`@{
  foreach ( var x in myCollection ) { }
}`

and

`@foreach ( var x in myCollection )
{
}`

If there is no difference, then that also needs to be pointed out - that the various Control Structures are in fact just shortcuts to expressing the same construct in a code block.
