### ISSUE TITLE
Documentation needs to explain how Control Structures differ from Code Blocks

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/AspNetCore.Docs#26248]
The documentation talks about @{ } code blocks, but then goes on to separately talk about Control Structures (like @if and @foreach), but does not explain why these two separate approaches exist that appear to achieve the same result.

For example, what is the distinction between doing:
`@{
  foreach ( var x in myCollection ) { }
}`

and

`@foreach ( var x in myCollection )
{
}`

If there is no difference, then that also needs to be pointed out - that the various Control Structures are in fact just shortcuts to expressing the same construct in a code block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#razor-reserved-keywords)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to  #26247
