### ISSUE TITLE
Typo in code sample

### ISSUE THREAD

**Issue by codemonkey85** [dotnet/AspNetCore.Docs#26263]
Isn't this 'invocationContext' supposed to be called 'rhiContext'?

![image](https://user-images.githubusercontent.com/1414036/176565042-4c21e60a-c595-4caf-993d-96140c86befa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a109e339-bce8-9580-12f8-dab879a3dcfc
* Version Independent ID: a109e339-bce8-9580-12f8-dab879a3dcfc
* Content: [Filters in Minimal API applications](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/min-api-filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/min-api-filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by codemonkey85** [comment]
Here's a direct link to the line in question: https://github.com/dotnet/AspNetCore.Docs/blob/c963eefaf7c12890b7bd911abd3874c0bfd693cb/aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples/Filters/Program.cs#L12

**Comment by Rick-Anderson** [comment]
@codemonkey85  nice catch. Fixed in #26264

**Comment by Rick-Anderson** [comment]
@codemonkey85  see[ this suggestion](https://github.com/dotnet/AspNetCore.Docs/pull/26188#discussion_r909092815
)
