### ISSUE TITLE
Signal R + Redis clustering Unclear Docs

### ISSUE THREAD

**Issue by AlanMacdonald** [dotnet/AspNetCore.Docs#26271]
The official docs says "[Redis Clustering](https://redis.io/topics/cluster-spec) is a method for achieving high availability by using multiple Redis servers. Clustering isn't officially supported, but it might work." This isn't clear enough for almost every production level app. If you are using SignalR on a farm you need a backplane and are probably using Redis. That backplane needs to high availability otherwise it is simply not possible to provide an enterprise level solution. The docs have said this vague statement for years. We can't pretend that it's ok for this to be unknown when it comes up almost every single time someone tries to build an enterprise application using Signal R.

Currently everybody using SignalR has to go and do trial and error to see whether this vague statement means in practical terms it does work and then decide whether they can risk it being broken in the future since it's not officially suppported.

The optimum outcome for everyone would be it is officially supported and documented as such. It basically needs to be supported otherwise SignalR is not fit for enterprise without using a third party backplane provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by wadepickett** [comment]
I see, that makes sense.  Thanks!
