### ISSUE TITLE
The "Preview an image provided by the InputFile component" content seems strange

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/AspNetCore.Docs#26276]
A couple of aspects of the "Preview an image provided by the InputFile component" content seem odd to me:

 * Why does it round-trip the data to .NET? That's potentially very expensive, and could be avoided. Instead, the .NET side already knows the `Name` of the file being uploaded, so it can send that to some JS function `setImage` along with a reference to the `<input type=file>` element, and then the JS code can read `inputFileElement.files` to look up the corresponding file data without it ever having to be sent to .NET
 * Why does it claim that "Because setImage is called from a form, it isn't necessary for the setImage function to call [revokeObjectURL](https://developer.mozilla.org/docs/Web/API/URL/revokeObjectURL)"? I don't know what "form" is being referred to here, or why that has any bearing on the fact that `createObjectURL` will leak memory if you fail to revoke the object URL later. As far as I'm aware, it *is* necessary to revoke the object URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Version Independent ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Content: [Work with images in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
@TanayParikh is the content provider for these scenarios.

Tanay, my recent UE ("user experience") pass was performed on https://github.com/dotnet/AspNetCore.Docs/pull/26161 about ten days ago, but IIRC the changes were limited to non-technical aspects. My PR opening comment calls out the changes, and I don't think they bear on @SteveSandersonMS's remarks.

The cross-ref for the original content submission is https://github.com/dotnet/AspNetCore.Docs/pull/23720 ... there were some minor updates along the way outside of my UE pass.

**Comment by TanayParikh** [comment]
> Instead, the .NET side already knows the Name of the file being uploaded, so it can send that to some JS function setImage along with a reference to the <input type=file> element, and then the JS code can read inputFileElement.files to look up the corresponding file data without it ever having to be sent to .NET

Sounds good, we'd just need to call out the duplicate file name issue with a directory upload, that you mentioned in https://github.com/dotnet/aspnetcore/issues/31638#issuecomment-1171540860.

> * Why does it claim that "Because setImage is called from a form, it isn't necessary for the setImage function to call [revokeObjectURL](https://developer.mozilla.org/docs/Web/API/URL/revokeObjectURL)"? I don't know what "form" is being referred to here, or why that has any bearing on the fact that `createObjectURL` will leak memory if you fail to revoke the object URL later. As far as I'm aware, it _is_ necessary to revoke the object URL.

I think this may have been a miscommunication at some point. We definitely need to still revoke. The following should be better:


```diff
- When implementing the preceding function for a form (<xref:Microsoft.AspNetCore.Components.Forms.EditForm> component), it usually isn't necessary to revoke the object URL because it's typically revoked after the user submits the form for processing, as the object URL is no longer required at that point. For a form that uses `setImage`, you can remove the call to [`revokeObjectURL`](https://developer.mozilla.org/docs/Web/API/URL/revokeObjectURL).
+ When implementing the preceding function for a form (<xref:Microsoft.AspNetCore.Components.Forms.EditForm> component), the object URL should typically be revoked after the user submits the form for processing, as the object URL is no longer required at that point.
```

**Comment by TanayParikh** [comment]
@guardrex please let me know if the above answers the `needs-more-info` query, or if there's any other info I can provide 😄

**Comment by guardrex** [comment]
Sure thing. I'll be back online tomorrow (Friday) morning.

**Comment by guardrex** [comment]
@TanayParikh ... Can you email me at my aquent.com address (user: llatham) to discuss this offline? I don't have your email address, nor do I have access to the global address book.

**Comment by TanayParikh** [comment]
@guardrex assigning this to myself as well, as I know I need to get back to you on this.

**Comment by guardrex** [comment]
Thanks @TanayParikh ... No rush. I took out the **_offending code that I placed earlier_** 🙈🤣. We're not showing what he said was bad to show.

I just couldn't quite follow what Steve was saying to do. I understood bits and phrases but not the whole coding concept.
