### ISSUE TITLE
Possible incorrect code snippet

### ISSUE THREAD

**Issue by jamesatgreymetis** [dotnet/AspNetCore.Docs#26275]
In the section "The following code shows a typical authorization service configuration:"

The code snippet adds a policy using the RequireClaim method. Is correct? I was expecting the example to add a policy using the AddRequirements method as the page is able Requirements and Requirements handlers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0&source=docs#feedback)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
I don't see a problem in that snipped. The snipped is still in the general policy based authorization section, so it shows an example for that. Later in the requirements section, there are example snippets for how to build requirements and how to use them.
Keep in mind, that policies and requirements is not the same. I hope I understood your concern correctly.

**Comment by Rick-Anderson** [comment]
Thanks @Ducki
