### ISSUE TITLE
Blazoe Windows Forms sample doesn't appear to work

### ISSUE THREAD

**Issue by RussKie** [dotnet/AspNetCore.Docs#26284]
I follow the sample, but I'm getting errors, and when run it doesn't appear to work.

Here's what I'm getting with .NET 7 SDK installed:
![image](https://user-images.githubusercontent.com/4403806/176802790-3df28c25-df9e-4aea-8020-51ba8af5db07.png)
![image](https://user-images.githubusercontent.com/4403806/176802807-053a744d-df4b-4293-acdf-c13ae7cac8bb.png)

![image](https://user-images.githubusercontent.com/4403806/176803381-cbc3c64c-a237-4bab-a6cc-a07f4774bc77.png)

If I uninstall .NET 7 SDK, then I don't get the above errors, but now I'm getting:
![image](https://user-images.githubusercontent.com/4403806/176803488-9812248c-617c-475c-bbe8-0daeafa5e519.png)

This doesn't appear prevent the app from compiling and running, but the net result is the same - the black screen.

VS 17.3.0 Preview 3.0 [32606.499.main].

<details>
<summary>dotnet --info</summary>

```
PS D:\Development\!Tests\BlazorWinFormsApp\BlazorWinFormsApp> dotnet --info
.NET SDK:
 Version:   7.0.100-preview.7.22329.1
 Commit:    4545c34392

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.7.22329.1\

Host:
  Version:      7.0.0-preview.6.22329.3
  Architecture: x64
  Commit:       ade0b21465

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.7.22329.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.7.22324.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22322.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22329.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.7.22322.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RussKie ... It works here, so I can't explain that behavior. Can you put the solution up in a GitHub repo so that I can take a look at it?

**Comment by RussKie** [comment]
Bizarre :) 
Here's a zip of the folder [BlazorWinFormsApp.zip](https://github.com/dotnet/AspNetCore.Docs/files/9024357/BlazorWinFormsApp.zip)

Thank you

**Comment by guardrex** [comment]
I'm unable to open ZIPs here due to security restrictions. I can only look at the app if you post it to GitHub.

**Comment by guardrex** [comment]
You say you have VS 17.3.0 Preview 3.0. I'm only showing Preview 2 as the latest preview release ...

https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#visual-studio-2022-version-173-preview-releases

**Comment by RussKie** [comment]
That's the internal preivew

**Comment by guardrex** [comment]
I see ... ok.

**Comment by RussKie** [comment]
I pushed the sample to https://github.com/RussKie/BlazorWinFormsApp

**Comment by RussKie** [comment]
I just tried it in VS 17.2.4 - same result

**Comment by guardrex** [comment]
I'll take a look.

**Comment by guardrex** [comment]
Rename your static assets folder from `www` to `wwwroot`.

**Comment by RussKie** [comment]
Bah... that's embarassing 🤦‍♂️

That worked! Thank you so much for your help.

**Comment by RussKie** [comment]
I'm going to try this with .NET 7 installed now.

**Comment by guardrex** [comment]
Sure thing ... glad it worked.

We'll close this as fixed, but I'd like to ping @mkArtakMSFT and @danroth27 just so they can put an 👁️ on that bizarre set of VS UI complaints for that particular problem.

**Comment by RussKie** [comment]
Confriming - with .NET 7 SDK installed the red squiggles are back, though they don't appear to have any effect on the running sample
![image](https://user-images.githubusercontent.com/4403806/176802790-3df28c25-df9e-4aea-8020-51ba8af5db07.png)
![image](https://user-images.githubusercontent.com/4403806/176802807-053a744d-df4b-4293-acdf-c13ae7cac8bb.png)

**Comment by guardrex** [comment]
Ok ... I think Dan and Artak will see this per my pings. If it's worth further action by the product unit, they'll take it from here, probably by opening an issue on their repo for investigation/work.

**Comment by RussKie** [comment]
Yep. And now I know who to ping directly too :)

**Comment by guardrex** [comment]
Well, you'd open an issue directly on their repo for product support at ...

https://github.com/dotnet/aspnetcore/issues

... and then it would be triaged in their normal workflow. It's best NOT to ping them directly. They're 🏃😅 most of the time.

**Comment by guardrex** [comment]
The other factor here is that VS is a different team, and they take their issues via the **Report a Problem** gesture from within VS. That's a different workflow/group from the ASP.NET Core group. That's why it's best to let Dan/Artak look at this to see how best to handle it if they want to do anything in particular. They might say that it should be reported to the VS team and not on their repo.

**Comment by RussKie** [comment]
Thank you. I know this drill, I'm part of the .NET team as well.

**Comment by guardrex** [comment]
Oh, ok ... sorry about that. I didn't roll over your avatar to see the affiliation.

**Comment by RussKie** [comment]
No worries at all :)
Thank you for your help in real time

**Comment by danroth27** [comment]
@RussKie If you clean out the bin and obj folders and rebuild do the red squiggles go away?
