### ISSUE TITLE
Add .NET 7 sample code for Binding arrays and StringValues from headers and query strings in minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26290]
[Binding arrays and StringValues from headers and query strings in minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/#provide-endpoint-descriptions-and-summaries-for-minimal-apis)

Add samples to https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples folder

Remove https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/bindingArrays/7.0-samples/ReadMe.md

cc @fiyazbinhasan

**Comment by fiyazbinhasan** [comment]
on it! :)
