### ISSUE TITLE
.NET 7: write sample for Dependency injection for SignalR hub methods

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26292]
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/#dependency-injection-for-signalr-hub-methods

**Comment by BrennanConroy** [comment]
Is this section not enough?
https://docs.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-7.0#inject-services-into-a-hub
