### ISSUE TITLE
URL NOT WORKING

### ISSUE THREAD

**Issue by teebabs** [dotnet/AspNetCore.Docs#26315]
I cannot access files in the URL. I created a folder under the pages folder named faculties and added a razor page with name create.cshtml. On my browser, I typed the following URL after the localhost, /faculties/create. All I get is error 404 - page cannot be found. What could be wrong

**Comment by guardrex** [comment]
Hello @teebabs ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
