### ISSUE TITLE
Microsoft.AspNetCore.SignalR nuget package deprecated? 

### ISSUE THREAD

**Issue by purplesmash** [dotnet/AspNetCore.Docs#26319]
Hi can you tell me if Signal R has moved, the nuget package is deprecated https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR/ so I am unsure of where to turn. I use this in an application that runs in .net 6.0. I can see that this page is being maintained so I am hoping that the hub work has been moved to a different package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @purplesmash ... It's part of the shared framework, so you don't need to do anything in a typical app targeting a recent release for the package to come in. If you dig into the `obj` folder for a Release configuration and look at `project.assets.json`, you'll see the framework reference for [`Microsoft.AspNetCore.App`](https://www.nuget.org/packages/Microsoft.AspNetCore.App#dependencies-body-tab). From there, you'll see the SignalR packages come in referenced by that package. If you want to read more on this subject, we don't have those docs here, but you should be able to find shared framework content in the [.NET docs](https://docs.microsoft.com/dotnet/fundamentals/).

**Comment by guardrex** [comment]
Yeah ... I just looked ... they do have a doc pertaining to this ... see if ...

https://docs.microsoft.com/aspnet/core/fundamentals/metapackage-app

... helps, and they also cross link to a Nate McMaster blog, too, at ...

https://natemcmaster.com/blog/2018/08/29/netcore-primitives-2/
