### ISSUE TITLE
Misleading statement about Authorize/AllowAnoynmous override

### ISSUE THREAD

**Issue by Blackclaws** [dotnet/AspNetCore.Docs#26332]
The document in its current form leads one to believe that combining Authorize with AllowAnonymous on a controller will lead to Authorize being ignored, this is only partially true.

What really happens is that the result of the authorization is ignored it is, however, still performed.

This behavior means that the authentication pipeline will indeed run and you will have access to the User Identity in the HttpContext _if_ the user was authenticated. 

This can be seen as an alternative to calling HttpContext.AuthenticateAsync() within the controller if you have an endpoint that switches on the authentication state anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33226](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33226)

**Comment by Rick-Anderson** [comment]
It states
You can also use the `AllowAnonymous `attribute to allow access by non-authenticated users to individual actions.

**Comment by Rick-Anderson** [comment]
> Which to me signals that Authorize attributes aren't even processed, which isn't true. Authentication middleware _does_ run.

It just states the authorization is bypassed. It doesn't state the middleware doesn't run.

**Comment by Blackclaws** [comment]
The thing is, middleware _doesn't_ run if there is no [Authorize] attribute. So the presence of the [Authorize] attribute has an effect. Which the Warning posted above implies it doesn't have because [AllowAnonymous] would lead to [Authorize] being ignored.

Its just a detail that might be nice to add to the text as a clarification, saying:

If Authorize is present Authentication middleware runs, if AllowAnonymous is also present the result of the Authentication middleware is ignored and all requests are processed by the endpoint.

**Comment by Rick-Anderson** [comment]
@blowdart  please review

**Comment by Rick-Anderson** [comment]
> @HaoK Thoughts on how best to word this?

**Comment by HaoK** [comment]
I would word this something to the effect of, "Authorization requirements specified by [Authorize] will be ignored, but any related authentication will still be done."

**Comment by Stuart88** [comment]
Updating the documentation feels like a workaround for something that is simply wrong.

[AllowAnonymous] by nature should bypass [Authorize].

Would love to know the reasoning behind it being the way it is.
