### ISSUE TITLE
How to pass image URL from controller?

### ISSUE THREAD

**Issue by dmaziuk** [dotnet/AspNetCore.Docs#26349]
Serving static files as described in the manual: `<img src="~/images/MyImage.jpg" class="img" alt="My image" />` only works in .cshtml. In real life we need to pass static assets' URLs from the code, e.g. from the database. Here's what happens in VS2022 .NET 6 using the default MVC template:

`Index.cshtml`:
```
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>foo</p>
    <img src="~/images/turning-points-header.png" />
    <p>bar</p>
    <img src='@Html.Raw(ViewData["img"])' />
    <p>baz</p>
    <img src=@ViewData["img"] />
    <p>bleh</p>
    @{
        string bleh = ViewData["img"].ToString();
            <img src="@bleh" />
    }
</div>
```

`HomeController.cs`:
```
       [Route("")]
        [Route("[action]")]
        public IActionResult Index()
        {
            ViewData["img"] = "~/images/turning-points-header.png";
            return View();
        }
```
(using attribute routing but the result is the same w/ conventional route too)

**The result**

![Capture](https://user-images.githubusercontent.com/3136401/177816971-2dc2198f-8034-4eca-ba82-cec80ae914a7.PNG)

Generated html is 
```
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core>building Web apps with ASP.NET Core</a>.</p>
    <p>foo</p>
    <img src="/images/turning-points-header.png" />
    <p>bar</p>
    <img src='~/images/turning-points-header.png' />
    <p>baz</p>
    <img src=~/images/turning-points-header.png />
    <p>bleh</p>
            <img src="~/images/turning-points-header.png" />
</div>
```

**The question**

How are we supposed to pass URLs from the controller? Using absolute URL (`/images/turning-points-header.png`) is not an answer since the application will not run in IIS root and `/` will not resolve properly.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I just tested it and it works fine

```
@{
    <img src=@ViewData["img"]>
}
```

**Comment by dmaziuk** [comment]
No it doesn't. It will resolve is your page is `/home` but not if your page is `/home/subsection`. Similarly you can do `ViewData["img"] = "/img/rear1.png";` and it will work, even in subpages, as long as your app is in the top level of your IIS's site hierarchy. 

The whole point of tilde is it's supposed to map to `${application}/wwwroot` from anyplace in the application. Which evidently is not what's happening in .NET, despite what the documentation suggests.

**Comment by dmaziuk** [comment]
OK so my best guess is whatever processes `.cshtml` files does a "first pass" in which ~ is expanded to wherever `wwwroot` is mapped to, and **after that** `@` vars and code blocks are processed. So tilde expansion doesn't happen in those.

I guess it's not a bug in the documentation: `~/images/rear1.png` works exactly as documented -- but **only** exactly as documented and not in any other context. Ideally that should be noted in the docs.
