### ISSUE TITLE
.NET 7: Add sample for Minimal API IFormFile and IFormFileCollection Support

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26345]
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/
Sample code goes in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples

~@JuergenGutsch are you interested in writing a minimal sample?~

**Comment by Rick-Anderson** [comment]
@martincostello this is all yours.

**Comment by JuergenGutsch** [comment]
I saw it too late :-( 
Just in case, I would have samples ready.

**Comment by martincostello** [comment]
@JuergenGutsch Feel free to work on this instead if you've already got something.

**Comment by JuergenGutsch** [comment]
Thanks @martincostello 
@Rick-Anderson do you agree?

**Comment by Rick-Anderson** [comment]
@martincostello  thanks for being so generous. Hopefully  you can find an interesting issue to work on [`is:issue is:open label:"code help wanted" `](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22)

@JuergenGutsch  thanks for taking this.

**Comment by Rick-Anderson** [comment]
@JuergenGutsch  can you PR some of your samples in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/iformFile/7.0-samples
