### ISSUE TITLE
.NET 7: Add customizing the cookie consent value

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26341]
[Customize the cookie consent value](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/#customize-the-cookie-consent-value)

* https://github.com/dotnet/aspnetcore/issues/40164
* https://github.com/dotnet/aspnetcore/pull/40213

I'm not sure the best place to document this. Add links to where we document it to the following:

* [What's new in ASP.NET Core 7.0 preview](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0)
* [EU General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-6.0)
* [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-6.0)
* [Work with SameSite cookies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-6.0)
* [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-6.0)

@Tratcher  please suggest the primary doc to add this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@daviddesmet can you suggest where this should be documented?

**Comment by daviddesmet** [comment]
@Rick-Anderson I think it should be in [EU General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-6.0) since is related to the cookie consent.
