### ISSUE TITLE
.NET 7: Code sample for Improved unit testability for minimal route handlers

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26352]
[Improved unit testability for minimal route handlers](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#improved-unit-testability-for-minimal-route-handlers)

- [x] Create sample app #26801
- [x]  Create new doc
- [x] Update What's new

**Comment by fiyazbinhasan** [comment]
I can take this 😸

**Comment by Rick-Anderson** [comment]
> I can take this 😸

Fantastic.
