### ISSUE TITLE
.NET 7: Code sample for Bind using TryParse in MVC and API Controllers

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26354]
[Bind using TryParse in MVC and API Controllers](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#bind-using-tryparse-in-mvc-and-api-controllers)

Add sample code to [this folder](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/controllers/bind-tryparse/7.0-samples)

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan

**Comment by fiyazbinhasan** [comment]
on it!
