### ISSUE TITLE
Adding example of AntiForgery scenarios with standards Web APIs

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#26350]
Part of https://github.com/dotnet/aspnetcore/pull/42586

Was decided to not have any in-box default behavior for both (`API controllers` and `Minimal APIs`), however, we should add an example of how the users could implement it using `IAntiforgery` services.

Here is a sample code with the server implementation: https://gist.github.com/brunolins16/3d11b2fd9861afaec22e79abfc2a55fd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#generate-antiforgery-tokens-with-iantiforgery)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@brunolins16 don't worry about the wording, I can clean that up. Just get a good start.
