### ISSUE TITLE
.NET 7: Code for New Results.Stream() overloads

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26355]
The sample at [New Results.Stream() overloads](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/#new-results-stream-overloads) throws `ObjectDisposedException: Cannot access a disposed object. Object name: 'Image`1'.` because of `using` in the following line
`    using var image = await Image.LoadAsync("puppy.jpeg");`

Removing `using` and code seems to work. See [this GitHub sample that reproduces the error](https://github.com/Rick-Anderson/Results.Stream/blob/main/Program.cs#L10-L12)

The blog is for Preview 3, I'm using `7.0.100-preview.5.22307.18`.

@halter73 please advise

**Comment by halter73** [comment]
If you move all the logic into the Results.Stream callback including the `using var image`, it should work.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  add code to [this folder](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/resultsStream/7.0-samples)
