### ISSUE TITLE
Can we add some concrete examples for JavaScript initializers in this page?

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#26363]
[EDIT by guardrex to change the metadata to point to the *Startup* topic, where we can place the examples with existing ones.]

Examples are:
* Ensuring that your library is loaded before Blazor Starts.
* Automatically loading the scripts that your library needs.
* Ensuring that Blazor has been initialized before calling into it from your library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad891f84-d11e-e334-fcdc-b55c5171fca4
* Version Independent ID: 11f8db3d-9988-e0a1-89c5-c3552ee47b93
* Content: [ASP.NET Core Blazor startup](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'm changing the metadata for this b/c this was classified as a fundamental startup concept and placed in the *Startup* doc at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-6.0#javascript-initializers

... which is cross-linked from the JS interop topic. I think I'll adjust the cross-link to make it more obvious in the JS interop overview section.

We'll add the scenario examples to the *Startup* topic.

**Comment by guardrex** [comment]
I'm going to place my notes here and mark this back off of **In progress** to **P1** until I get a clearer understanding for each ask. Right now, here are the directions that I was thinking ...

1. **Ensuring that your library is loaded before Blazor Starts.**

   For this, does one add `async="false"` and `defer="false"` with a script tag appended to the head (in code) in `beforeStart`?

   We already show a script tag appended to the head in `beforeStart`; so if that's correct, I just need to show an example of adding `async` and `defer` after the existing example.

2. **Automatically loading the scripts that your library needs.**

   As I said, we already show a script tag appended to the head in `beforeStart`.

   Do you want to add the approach for modules of using an `import` statement ... and if so ...

   (a) What should the doc say about adding an `import` statement to the top of the `*.lib.module.js` file? ... anything in particular about it?

   (b) Using a dynamic `import({MODULE PATH});` statement within `beforeStart`? ... anything in particular?

3. **Ensuring that Blazor has been initialized before calling into it from your library.**

   This doesn't just mean calling the library's initialization FN from `afterStarted`? I guess I'm not clear on where/when you mean for the "calling into it" part of that.

4. **Another ? #1 ...**

   Does the IIFE pattern play a role in any JS initializer scnearios?

5. **Another ? #2 ...**

   Should the guidance state that it's OK for a dev to export custom JS FNs from within the `*.lib.module.js` file SxS with `beforeStart`/`afterStarted`?
