### ISSUE TITLE
When I uses this code snippet it is suggested that RNGCryptoServiceProvider is Obsolete! 

### ISSUE THREAD

**Issue by TLYoz** [dotnet/AspNetCore.Docs#26365]
I tried following this as an example of how to hash in .net 6 and the example class is deprecated. Is this therefore a good example to include in the documentation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See #26253
