### ISSUE TITLE
Tutorial: Create User accounts with Razor

### ISSUE THREAD

**Issue by JoeyJaySWE** [dotnet/AspNetCore.Docs#26379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

No

### Describe the solution you'd like

I've been experimenting with some .NET Core using the Razor Pages, and I find it pretty handy in how easy you can set up database connections and make simple CRUD operations with the Razor Pages tutorial; however, most of the features I work with online is requiring user Roles with Account verifications and while there is a pretty straight forward tutorial on how to create entries to a Database with CRUD, it stores the data in plain text. This is a problem when it comes to storing personal information and especially passwords. 

Now, I'm sure there is a way of doing it with razor, but I can't seem to find the relevant documentation for it. I do find for ASP.NET using the MVC5, but I'm not sure if that is compatible with Razor, and if it is, maybe you could add a link to it among the Razor Pages tutorial for further readings?

**Comment by JoeyJaySWE** [comment]
Thanks for the quick reply @javiercn
 however, upon further reading the link I provided for [Web Pages, ](https://docs.microsoft.com/en-us/aspnet/web-pages/overview/security/16-adding-security-and-membership) the page recommends setting up a WebMatrix and upon further reading about it, it's "is no longer recommended as an integrated development environment for ASP.NET Web Pages. Use Visual Studio or [Visual Studio Code](https://code.visualstudio.com/)." 
 
(As mentioned [here](https://docs.microsoft.com/en-us/aspnet/web-pages/videos/introduction/install-and-use-the-microsoft-webmatrix-tool) )

And with that, I'm sadly back to a stand-still in my quest for knowledge as [the guide](https://docs.microsoft.com/en-us/aspnet/web-pages/overview/security/16-adding-security-and-membership) mentions that it indeed can be done manually or with WebMatrix, but it only demonstrates how to build it with WebMatrix. You don't happen to have any good idea of where I may find a guide for the manual version?

**Comment by Ducki** [comment]
Hi @JoeyJaySWE,

you're still in the docs for an outdated version ;)

Web Matrix doesn't exist anymore. To add authentication to your _Razor Pages_ app, have a look at the docs for ASP.NET Core 6:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=netcore-cli

There is also a nice introduction/tutorial from one of the Microsoft employees here (though quite lengthy, but thorough): https://www.youtube.com/watch?v=u898_hiWJY0

**Comment by Rick-Anderson** [comment]
@JoeyJaySWE take a look at https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data

**Comment by JoeyJaySWE** [comment]
After reviewing the provided links I feel like I managed to find the functions I was looking for. Thanks everyone for the help!
