### ISSUE TITLE
.NET 7: Code sample for Microsoft.AspNetCore.Http.TypedResults

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26370]
See [Typed results for minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#typed-results-for-minimal-apis)

Put the code in aspnetcore\fundamentals\minimal-apis\misc-samples\typedResults and remove the Readme.txt file.

**Comment by sammychinedu2ky** [comment]
working on this
