### ISSUE TITLE
Introductory paragraph is difficult to comprehend!

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/AspNetCore.Docs#26398]
I'm sorry, but I have read this sentence four times now and I still cannot parse what it is actually trying to say!

"Components are covered in detail in the Components articles, but it's important to learn component basics and note conventions used in the articles before reading Fundamentals articles, which use components to demonstrate concepts."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Version Independent ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Content: [ASP.NET Core Blazor fundamentals](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Loophole62ndFF ... It's just trying to say 'let's look at the basics of components before getting into fundamental concepts.' Yes, that's a sentence that I'll simplify quite a bit. Thanks for the note on it.
