### ISSUE TITLE
Azure App Service gRPC support

### ISSUE THREAD

**Issue by maloo** [dotnet/AspNetCore.Docs#26402]
Could you please add a link to info about the experimental support for gRPC support in Azure App Services so we get a chance to test it? And it says only in some regions, could you add a link where we could check what reagions are supported?

BR
Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76d3f0ff-f65f-97d2-940f-4509b0d425bd
* Version Independent ID: ea62de0b-d7e5-e543-b892-a587d6e9dc84
* Content: [gRPC on .NET supported platforms](https://docs.microsoft.com/en-us/aspnet/core/grpc/supported-platforms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
