### ISSUE TITLE
Test behavior not working for me

### ISSUE THREAD

**Issue by tjhftw** [dotnet/AspNetCore.Docs#26407]
Hello, I've been through the series of tutorials up to this point with no problems. However, when I attempted the exercise below I was unable to observe any difference in how the local page behaved using Edge. 

Test the behavior of @page "{id:int?}":

Set the page directive in Pages/Movies/Details.cshtml to @page "{id:int?}".
Set a break point in public async Task<IActionResult> OnGetAsync(int? id), in Pages/Movies/Details.cshtml.cs.
Navigate to https://localhost:5001/Movies/Details/.
With the @page "{id:int}" directive, the break point is never hit. The routing engine returns HTTP 404. Using @page "{id:int?}", the OnGetAsync method returns NotFound (HTTP 404)

In each case I see:

This localhost page can’t be found
No webpage was found for the web address: https://localhost:7253/Movies/Details
HTTP ERROR 404

:[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Part 5, update the generated pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@tjhftw, Just tested again. It is working as it should.  In both cases you get a 404 with no web page found, but in the case of @page "{id:int} the breakpoint specified is never hit.

I do I see an opportunity to clarify on the instruction that specifies a specific port when really it is your own random assigned port.

**Comment by tjhftw** [comment]
Thanks wadepickett. I see what you mean. I am new to this. From the text, I was expecting the print screen of the error to show a clear difference between the two cases.
Also, I didn't understand that I should run the solution in debug mode to see that the breakpoint was not hit with {id:int} but was with {id:int?}.

**Comment by tjhftw** [comment]
Dear Wade, I hope this gets through to you.
I finished the tutorial, and was able to publish the app to Azure and even modify it a little.
I am having trouble understanding how it actually works though.
For example, when one edits an entry on the edit page, the way that ends up modifying the database is not transparent to me.
If / when you have time, I’d be very grateful if you’d explain how the user’s input on the webpage ends up modifying the database.
Thanks in advance, Tom
