### ISSUE TITLE
Unclear on Program/Startup

### ISSUE THREAD

**Issue by ileanaP** [dotnet/AspNetCore.Docs#26414]
Here it says that Program.cs is the place where services are configured, but both in .Net 5 and .Net Core 3.1 default templates created for a web app, the Program.cs contains CreateHostBuilder, which sets Startup class as default startup class, and then services are later set in ConfigureServices of Startup class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-6.0&tabs=windows)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ileanaP ... That's correct. If you flip the document version selector down to 5.0 or 3.1, that's the coverage that you'll see.

![image](https://user-images.githubusercontent.com/1622880/178750068-65c87c07-0354-4ad4-ad6e-3bcd4dd6902a.png)
