### ISSUE TITLE
Add to documentation how to Redirect inside the <NotFound> element

### ISSUE THREAD

**Issue by dirkesquire** [dotnet/AspNetCore.Docs#26415]
When a route is not found, the following documentation is supplied for App.razor:

```
<NotFound>
        <h1>Sorry</h1>
        <p>Sorry, there's nothing at this address.</p> b
</NotFound>

```

As great as that may be, another very common scenario is to redirect the user to another page when landing at a page that is not a match. Please could you provide an example in the documentation of how to Redirect inside the <NotFound> element as I think that will be super useful and it is not really clear to me how I would do that. 

```
<NotFound>
   @{ NavigationManager.NavigateTo("/Home", false); }
</NotFound>

```

This is something I tried. This does have the desired effect, however can't be correct as it throws a NavigationException initially while the app is loading up when debugging. So what is the the correct way? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dirkesquire ... Could ask the product unit this question by opening an issue at ...

https://github.com/dotnet/aspnetcore/issues

Please add the following to the bottom of your opening comment ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/26415
```

Normally, I close a docs issue because I can't be sure that they'll pitch covering a scenario in the docs. I re-open when there's something to cover. Your question is **_so good_** that I'm sure that I want to cover this scenario. Therefore, I'm going to leave this open and schedule it.

When you ask them, WRT ......

> can't be correct as it throws a `NavigationException` initially while the app is loading up when debugging

Tell them the exact error that you're seeing. That might be important.

**Comment by guardrex** [comment]
Actually, @dirkesquire, before you ask over there, let's discuss it further here.

I tried your code concept in a WASM app as ...

```razor
@inject NavigationManager NavigationManager

...

<NotFound>
    @{ NavigationManager.NavigateTo("/", false); }
</NotFound>
```

It works here, and I see no error ......

<img width="672" alt="Capture" src="https://user-images.githubusercontent.com/1622880/178787757-c70e4a86-ef5c-43da-9602-1837f92984d0.PNG">

<img width="389" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/178787781-98c454dc-6563-4a06-9bda-ff8f7a38702d.PNG">

What error are you getting?

**Comment by guardrex** [comment]
*AH!* I see what you mean ... you're using a Blazor Server app ...

```
Microsoft.AspNetCore.Components.NavigationException
  HResult=0x80131500
  Message=Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.
  Source=Microsoft.AspNetCore.Components.Server
  StackTrace:
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.NavigateToCore(String uri, NavigationOptions options)
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateToCore(String uri, Boolean forceLoad)
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateTo(String uri, Boolean forceLoad)
   at BlazorServerTestFileDownload.App.<BuildRenderTree>b__0_1(RenderTreeBuilder __builder2) in C:\Users\xxx\Desktop\BlazorServerTestFileDownload\BlazorServerTestFileDownload\App.razor:line 15
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

Let me take a closer look at that and get back to u.

**Comment by guardrex** [comment]
I'm taking a deeper look now. If nothing occurs to me, then we'll proceed with a PU issue. I'll get back to u shortly.

**Comment by guardrex** [comment]
Yeah ... I think that's ok without sweating the `firstRender` check because it navigates on the prerender and so no double-execution can occur. ....... 😄 ... *I* 🤔 *think*.

When I work this up into guidance for the section, I will ping for the PU to look to confirm that what's being shown and said is all good.

**Comment by dirkesquire** [comment]
I do like this solution, thank you!

It was my hunch also and it does make sense to me that the error was being thrown in a PreRender but at the same time that wasn't helpful.

Drawing from inspiration from the React world, specifically React-Router, you have not only a NavigationManager you can invoke functions on but there is also a built in element <Navigate> element that I think would make sense here which I was kinda expecting you might mention (if it existed - but I take it it doesn't). This would avoid the user having to 'roll their own' <RedirectToUser> element.

This is the type of solution I would expect:

```
<NotFound>
   <Navigate to="/" />
</NotFound>
```

I am of course happy building my own Navigate page as it is quite easy, but I think it would be a beneficial addition to the framework.

My only other comment is that after trying your solution it renders a white page instead of the page I am expecting, but perhaps that is because I'm trying to redirect to a MVC page as the home page. But I assume that is a different problem.

**Comment by guardrex** [comment]
> I am of course happy building my own Navigate page as it is quite easy, but I think it would be a beneficial addition to the framework.

That would be a request for the product unit on their repo.

I'm going ask Steve to look at that PR that I just put up. I'll add a remark NOW before he looks to see if he'll answer you on that PR to avoid you having to open a new issue.

WRT .....

>  I'm trying to redirect to a MVC page as the home page

Let me see what happens here. I'll try that and see if I can repro it / work that scenario out. I'll get back to you either in a few minutes or in a few hours. I'm just about to go OOF for perhaps ..... er .... 2-3 hours ... but I'll be back later later for sure.

**Comment by guardrex** [comment]
WELL ... "all set" except for the MVC endpoint situation. 

I'll check on that when I get back in a few hours and get back to you.

**Comment by guardrex** [comment]
Ok ... I had a sec. Try with the force load to `true`. It works if you do it this way ...

```
NavigationManager.NavigateTo("/Home/Index", true);
```

... I'll add that to the Steve ask on the PR for confirmation.

**Comment by dirkesquire** [comment]
Genius!

`NavigationManager.NavigateTo("/Home/Index", true);`

Yes this fixes it for me 😃
To be clear, I'm only needing the true, because I'm redirecting to an older MVC page inside the same site, and that all works nicely now.

**Comment by dirkesquire** [comment]
Your solution is absolutely great. I have embellished it with parameters and thought it could be useful if I shared this also:

**App.Razor:**
```
<NotFound>
    <Navigate to="/Home/Index" forceRedirect=@true />
</NotFound>
```

**Pages/Navigate.razor:**
```
@inject NavigationManager NavigationManager

@code {
    [Parameter]
    public string to { get; set; }

    [Parameter]
    public bool forceRedirect { get; set; } = false;

    protected override void OnAfterRender(bool firstRender)
    {
        NavigationManager.NavigateTo(to, forceRedirect);
    }
}
```

**Comment by guardrex** [comment]
See the PR ... per Steve's response, closing now.

**Comment by Curlack** [comment]
> Your solution is absolutely great. I have embellished it with parameters and thought it could be useful if I shared this also:
> 
> **App.Razor:**
> 
> ```
> <NotFound>
>     <Navigate to="/Home/Index" forceRedirect=@true />
> </NotFound>
> ```
> 
> **Pages/Navigate.razor:**
> 
> ```
> @inject NavigationManager NavigationManager
> 
> @code {
>     [Parameter]
>     public string to { get; set; }
> 
>     [Parameter]
>     public bool forceRedirect { get; set; } = false;
> 
>     protected override void OnAfterRender(bool firstRender)
>     {
>         NavigationManager.NavigateTo(to, forceRedirect);
>     }
> }
> ```

Not sure if naming convention is important to you, but public properties should be PascalCase'd
Just my two cents....
