### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Korporal** [dotnet/AspNetCore.Docs#26417]
The [article ](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/routing-in-aspnet-web-api)refers to pre-Core practices and conventions. There is no `WebApiConfig.cs`  or `App_Start` folder! Even this issue report seems to admit this yet refused to correct the article!

This is a hugely important aspect of API development so how can this be left in this state?

https://developercommunity.visualstudio.com/t/missing-app-start-folder-in-net-core-web-api-proje/793558

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use the version selector:

![image](https://user-images.githubusercontent.com/3605364/117202152-323e4a80-ad89-11eb-82d4-22b9bcbd4035.png)

You're looking at an old version

**Comment by Rick-Anderson** [comment]
@guardrex Should I open a request for a warning when you're not viewing the latest released version? There are so many links to docs that contain an old version query string value.
