### ISSUE TITLE
About Multi Tab CSRF

### ISSUE THREAD

**Issue by FahaoTang** [dotnet/AspNetCore.Docs#26422]
Hi team,
In the document section Multiple browser tabs and the Synchronizer Token Pattern, it mentioned that antiforgery token will not work as only the latest tab will have the valid token.

However, I've tested locally and I found it does work even I open multiple forms in one browser to submit. Please suggest. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Maybe we should say not guaranteed to work in all browsers in all environments.
[Multiple browser tabs and the Synchronizer Token Pattern](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0#multiple-browser-tabs-and-the-synchronizer-token-pattern) state:
Using multiple tabs can be problematic

**Comment by FahaoTang** [comment]
> 

I've tested in my production environment. It also works.

- Open a page with a form that uses CSRF token
- Open another page with a form that uses CSRF
- Submit the first form - no issues.
