### ISSUE TITLE
Extremely difficult to understand this doc.

### ISSUE THREAD

**Issue by greg-adze** [dotnet/AspNetCore.Docs#26421]
Seems to me there are 2 important points that need to be made here.  
1. Create the Area with a controller in it
2. Use the Area's controller created in step 1

This doc did not really help me with either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's all in the doc.

**Comment by greg-adze** [comment]
Glad you think so. Probably shouldn’t ask for feedback if you feel that way.


"Your mountain is waiting, so ... get on your way!"
-greg
________________________________
