### ISSUE TITLE
Blazor WASM options configuration coverage

### ISSUE THREAD

**Issue by dougclutter** [dotnet/AspNetCore.Docs#26439]
Based on the documentation, I can bind an options object using code like this:
`builder.Services.Configure<PositionOptions>(
    builder.Configuration.GetSection(PositionOptions.Position));`

Unfortunately, this doesn't work unless we include the `Microsoft.Extensions.Options.ConfigurationExtensions` package.  It would be great if the documentation mentioned this.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7367a651-2b27-0a57-e7d0-95686cc97f1c
* Version Independent ID: 8c769648-728d-72ce-ebf6-2a06e5076aa2
* Content: [ASP.NET Core Blazor configuration](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I just tested and it works fine without it.

**Comment by dougclutter** [comment]
Hi Rick - could you please test it while creating a Blazor Wasm application?  That's where I ran into the problem.

**Comment by guardrex** [comment]
@dougclutter ... Look at the Blazor version of the doc. I placed examples for everything that WASM can do with ASP.NET Core config, including mini-examples. I also think that all of the required package mentions are there. If you find a scenario that isn't, please open a new issue from the bottom of that topic (**This page** feedback button+form).

https://docs.microsoft.com/aspnet/core/blazor/fundamentals/configuration

**Comment by guardrex** [comment]
No, let's go ahead and re-purpose this issue. I'll change the metadata and update the title. I should make a pass on **Options** config and expand the doc at least a little to call out either that everything works as expected from the main doc or scope the scenarios that do work.

Note that we're crazy busy for the upcoming .NET 7 release, so I expect that it will take quite a while to reach this.

**Comment by dougclutter** [comment]
@guardrex - I understand crazy busy Luke; thanks for looking into it.
