### ISSUE TITLE
.NET 7 update required: JSON options configuration

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26445]
[JSON options configuration](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/#json-options-configuration)

`ConfigureRouteHandlerJsonOptions` has been renamed `ConfigureHttpJsonOptions`, see https://github.com/dotnet/aspnetcore/pull/42747

Need to update the following code for next release:

```
using System.Text.Json.Serialization;

var builder = WebApplication.CreateBuilder(args);

builder.Services.ConfigureRouteHandlerJsonOptions(options =>
{
    options.SerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    options.SerializerOptions.AllowTrailingCommas = true;
    options.SerializerOptions.MaxDepth = 8;
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

**Comment by tdykstra** [comment]
> Need to update the following code for next release:

Where is the code that needs to be updated?

**Comment by Rick-Anderson** [comment]
Looks like it never made, so you just need to document it.
