### ISSUE TITLE
MakeCert is deprecated...

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/AspNetCore.Docs#26443]
the documentation says:
>Create a PKCS#12 archive (.pfx) certificate. Options for creating certificates include [MakeCert on Windows](https://docs.microsoft.com/en-us/windows/desktop/seccrypto/makecert) and [OpenSSL](https://www.openssl.org/).

but:

![image](https://user-images.githubusercontent.com/14079228/179255665-7c4f61bc-47b5-4ea8-9819-33ebb1418c9f.png)
source: https://docs.microsoft.com/en-us/windows/win32/seccrypto/makecert

seems like this page should be updated to [New-SelfSignedCertificate](https://docs.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate?view=windowsserver2022-ps)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@heaths  @JoshLove-msft please review

**Comment by heaths** [comment]
See the linked PR

**Comment by spottedmahn** [comment]
nice, thanks!  Shall I close or will the PR completion auto-close?

**Comment by heaths** [comment]
Merging the PR should close this, yes.
