### ISSUE TITLE
Doesn't work.   Using Preview 3, the screenshots don't match

### ISSUE THREAD

**Issue by kasajian** [dotnet/AspNetCore.Docs#26454]
There's no "Maui" in the drop down when creating a new project with Visual Studio 2022 Preview.

Please either fix the page, or delete it.

Thank you.

**Comment by guardrex** [comment]
Hello @kasajian ... Please use the **This page** feedback button and form at the bottom of any **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

I assume that you're looking at the MAUI Blazor tutorial at ...

https://docs.microsoft.com/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0

Please see the purple NOTE box in the [Create a .NET MAUI Blazor app](https://docs.microsoft.com/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0#create-a-net-maui-blazor-app). If the templates don't appear, it's a known issue that they're working on. You'll need to install them manually with the following .NET CLI command in a command shell:

```dotnetcli
dotnet new -i Microsoft.Maui.Templates
```

More information can be found at the cross-linked product unit *Known Issues* page ...

https://github.com/dotnet/maui/wiki/Known-Issues#net-maui-templates-do-not-appear-in-visual-studio
