### ISSUE TITLE
What's new for gRPC and SignalR in ASP.NET Core 7.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26477]
- [x]  [Preview 1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/)
- [x]  [Preview 2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-2/)
 - [x]  [Preview 3](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-3/)
 - [x]  [Preview 4](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/)
 - [x]  [Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/)
- [x]  [Preview 6](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/)
- [x]  [Preview 7](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/)
- [x]  [RC1](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/)
- [x]  [RC2](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/)  (No new related features)

@wadepickett this is the gRPC and Signal version of what's new  for .NET 7 issue tracking.:

* Create issues for each item in the preview blogs that's tied to the gRPC or Signal doc.
* After you update a gRPC or Signal doc, update [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0). You need to do a fast update, checked out no more that 2 hours because @guardrex  and I are making frequent updates to that doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33227](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33227)

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks.  Please see your calendar.  I will not be able to be on this until after the 26th.

**Comment by wadepickett** [comment]
@Rick-Anderson,  do you mean pull all gRPC and SignalR info from previews 1-6 blogs (combining and updating where needed) and putting them into the [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0) with the information? Do I understand correctly? (I do understand the part about getting in and out of the final What's new quickly.)  Thanks for the help.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, do you mean pull all gRPC and SignalR info from previews 1-6 blogs (combining and updating where needed) and putting them into the [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0) with the information? Do I understand correctly? (I do understand the part about getting in and out of the final What's new quickly.) Thanks for the help.

1. Create a container issue like #26326 to track gRPC and SignalR from the preview blogs. 7 will be out soon and others will follow, so keep updating that.
2. Typically a new feature needs to be added to an existing doc and rarely to a new doc. Do that first. In the pr, mention contributes to `#123` (the tracking issue). Once that's merged, finish up of the issue by updating [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0)

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks that clears it up I think.  You want me to update all existing gRPC and SignalR docs we have in this repo to v7.0 as it relates to new features covered in the 1-6 preview 7.0 blogs.  Then as a last step update the  [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-6.0).  You were losing me on scope what all I was updating in the line "After you update a gRPC or Signal doc".   Thanks for help.

**Comment by Rick-Anderson** [comment]
Update to to reflect the new 7.0 features, I'm not asking you to update them for .NET 7. And it's not just 1-6, it's all the new features, even those that come out for RTW post the last preview.

**Comment by wadepickett** [comment]
@Rick-Anderson, thanks, just reflect the new feature information.  Yes, and not just the 1-6 you listed, but the future ones for RTW.  Thanks!

**Comment by wadepickett** [comment]
Notes:  (Draft, still adding info)
**gRPC:**
[ ] gRPC JSON Transcoding, Introduced in .NET 7.0 Preview 4.  
  - We already have this topic covered from a number of PR's for [gRPC JSON transcoding in ASP.NET Core gRPC apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-7.0)

[ ] gRPC JSON Transcoding: support for multi-segment parameters, Introduced .NET 7.0 Preview 6.
  - tracking issue: #26622

**Comment by BrennanConroy** [comment]
Don't add anything about the source generator.

**Comment by Rick-Anderson** [comment]
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/#experimental-openapi-support-for-grpc-json-transcoding

**Comment by wadepickett** [comment]
@Rick-Anderson, I thought we had that covered already in the recent https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?view=aspnetcore-7.0&source=docs.     Is there some part of it you think is missing?  Could you provide more information about what you are communicating with the link?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, I thought we had that covered already in the recent https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-openapi?view=aspnetcore-7.0&source=docs. Is there some part of it you think is missing? Could you provide more information about what you are communicating with the link?

Now how would anyone know that? See #26326 which shows each release where you can track the PR where each feature is addressed. This issue doesn't have RC1.

**Comment by wadepickett** [comment]
Got it, what you were intending to communicate with the link was to make sure I have it accounted for in this tracking issue. Thanks, that makes sense and is helpful.  You are right,  I should have noted RC-1 even though the issue was already taken care of.

**Comment by JamesNK** [comment]
A couple of gRPC features that were added in grpc-dotnet should be highlighted.

PR: https://github.com/dotnet/AspNetCore.Docs/pull/27454

**Comment by wadepickett** [comment]
No tasks left.
Last task fixed with #27454
