### ISSUE TITLE
.NET 7 sample code: Route groups with MapGroup 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26476]
[Route groups](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups)

Copy `fundamentals\minimal-apis\7.0-samples\todo\` to `fundamentals\minimal-apis\7.0-samples\todo-group\`

***EDIT by @Rick-Anderson*** Do #26549 as separate PR

**Comment by sammychinedu2ky** [comment]
I'll take care of it

**Comment by sammychinedu2ky** [comment]
done

**Comment by tdykstra** [comment]
Fixed by #27377
