### ISSUE TITLE
Download the app?

### ISSUE THREAD

**Issue by AzzaClazza** [dotnet/AspNetCore.Docs#26485]
Which confusingly named folder of the vast repository corrosponds to this stage of the tutorial?  I've tried to follow the instructions 3 times but I keep getting the same error at the same place. Online forums report the same issue with no clear fix so I had to try to 'download the app'.
I finally worked out how to 'fork the repository' but you can't execute it...I have to replace my code with the sample code...update-database...not, that's .net 5, this one it too early, this one doesn't work....
The link should ideally go to git folder containing the package that corrosponds to that stage of the tutorial.
It's a great tutorial, but I've spent 3/4 of my time working to make things work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Part 2, Razor Pages with EF Core in ASP.NET Core - CRUD](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment.
