### ISSUE TITLE
.NET 7:Microsoft.AspNetCore.Http.TypedResults

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26480]
[Microsoft.AspNetCore.Http.TypedResults](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#microsoft-aspnetcore-http-typedresults)

Write sample code.

**Comment by wcontayon** [comment]
Hi @Rick-Anderson, can I try a PR on this docs topics 🙂

**Comment by Rick-Anderson** [comment]
@wcontayon  thanks for the offer and checking. It looks like this is a duplicate issues and it was completed with #26463
I'm sorry I created a duplicate issue. cc @sammychinedu2ky 

Have a look at the untaken [`is:open label:"code help wanted"`](https://github.com/dotnet/AspNetCore.Docs/labels/code%20help%20wanted)
