### ISSUE TITLE
Note to inform readers to UseKestrel() method

### ISSUE THREAD

**Issue by jjacob15** [dotnet/AspNetCore.Docs#26489]
I'd like to add the following statement in the document to warn users that they need to call UseKestrel() before they start configuring it.

"Ensure you have called **UseKestrel()**  before calling the ConfigureKestral method in WebHost."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  please review

**Comment by Tratcher** [comment]
Technically true, but UseKestrel is built into many of the host setup APIs. Calling UseKestrel can break IIS for portable apps.
