### ISSUE TITLE
Docs page links to a deprecated nuget package, describing it as experimental

### ISSUE THREAD

**Issue by gaazkam** [dotnet/AspNetCore.Docs#26500]
Sections [Blazor data annotations validation package](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#blazor-data-annotations-validation-package) and [Nested models, collection types, and complex types](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0#nested-models-collection-types-and-complex-types) of this docs page deal with the [Microsoft.AspNetCore.Components.DataAnnotations.Validation](https://www.nuget.org/packages/Microsoft.AspNetCore.Components.DataAnnotations.Validation) package. This package is described as experimental.

However, on Nuget, the package is said to be legacy, deprecated and no longer maintained.

Given this I believe that these two sections of this docs page should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef47457-c8cf-74a4-b884-c1fe5c2ef52d
* Version Independent ID: 09a02d10-2834-467d-d8c2-3fd19ceb3863
* Content: [ASP.NET Core Blazor forms and validation](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/forms-validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @gaazkam. Last I heard, they were still suggesting it, but the 🧀 may have moved since then. I'll check with the PU on it.

**Comment by guardrex** [comment]
Thus far, looks like they rolled it into the framework. Still checking ... I'd like to 👀 **See It!_**&trade; 👀 before taking action 😄.

**Comment by guardrex** [comment]
No ... they were going to and then it didn't make the cut. See ......

https://github.com/dotnet/aspnetcore/issues/28640

Until .NET 8 arrives, I suspect the package will need to remain available. I'll check further.

**Comment by guardrex** [comment]
Alrighty ...... I ask at https://github.com/dotnet/core/issues/7420#issuecomment-1191626785 and pinged Artak offline to find out what's what. I'll react with a PR when we know what's what. Thanks again, @gaazkam for the shout out 📣.

**Comment by guardrex** [comment]
Fixed in NuGet.
