### ISSUE TITLE
Incorrect description for [BindRequired]

### ISSUE THREAD

**Issue by OleksandrOmelchenko** [dotnet/AspNetCore.Docs#26501]
The documentation for `[BindRequired]` attributes states that it cannot be applied to method parameters which is not accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#input-formatters-1)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@brunolins16 see [[BindRequired] attribute](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#bindrequired-attribute-1) That doesn't appear to be correct, did that change?

**Comment by brunolins16** [comment]
@Rick-Anderson the support for all BindBehavior in the top-level action parameters was added back in 2017 (https://github.com/dotnet/aspnetcore/commit/236ef5d1d1d12a2503c6da0900b3c40ca5470985)
