### ISSUE TITLE
Rate limiting middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26515]
* [RateLimiting middleware](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/#ratelimiting-middleware) from the blog [Announcing Rate Limiting for .NET](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/)
* [Rate limiting middleware](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#rate-limiting-middleware) 
* [Blog update](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#updates-to-rate-limiting-middleware) 
* https://github.com/dotnet/aspnetcore/issues/41667

[System.Threading.RateLimiting](https://www.nuget.org/packages/System.Threading.RateLimiting) will be documented in  https://github.com/dotnet/docs/issues/30426  and this article will point to that. This article will document the [Microsoft.AspNetCore.RateLimiting](https://www.nuget.org/packages/Microsoft.AspNetCore.RateLimiting) NuGet package.

@BrennanConroy do you have any ASP.NET Core samples I can start with?

**Comment by Jhstvf4t** [comment]
I don't have money anymore to go out to the workshop, I want to eat, let alone me

**Comment by Rick-Anderson** [comment]
@Kahbazi are you interested in writing the sample code for rate limiting middleware?

**Comment by Kahbazi** [comment]
@Rick-Anderson I have not write any docs yet, but I would like to give it a try. I'm not familiar with this repo. Where should I start? Are there any specifics samples you have in mind?

**Comment by Jhstvf4t** [comment]
Can I call you?

Pada tanggal Sab, 30 Jul 2022 13:49, Kahbazi ***@***.***>
menulis:

**Comment by Rick-Anderson** [comment]
@Kahbazi  I'll handle the document. It would be great if you could write a sample showing how to use [System.Threading.RateLimiting](https://www.nuget.org/packages/System.Threading.RateLimiting).  I have a basic sample [here](https://github.com/Rick-Anderson/WebRateLimitMw) but [`MyCustomLimiter : RateLimiter`](https://github.com/Rick-Anderson/WebRateLimitMw/blob/main/MyCustomLimiter.cs) isn't implemented.

**Comment by Kahbazi** [comment]
@Rick-Anderson I created a [gist](https://gist.github.com/Kahbazi/94beef16aa145503d8407b56a46efd6c) of how to use RateLimiting, but it's basically what you already have in the sample. The sample is limiting the endpoints by IP and by username.
I try to understand how I can help. Do you need a custom implementation of `RateLimiter`? Does that mean a new algorithm like Token Bucket, Sliding window?

**Comment by Rick-Anderson** [comment]
@Kahbazi  take a look at the first sample under [RateLimiting middleware](https://devblogs.microsoft.com/dotnet/announcing-rate-limiting-for-dotnet/#ratelimiting-middleware). That's what I copied [here](https://github.com/Rick-Anderson/WebRateLimitMw) but [MyCustomLimiter : RateLimiter](https://github.com/Rick-Anderson/WebRateLimitMw/blob/main/MyCustomLimiter.cs) isn't implemented.

>  Do you need a custom implementation of `RateLimiter`? Does that mean a new algorithm like Token Bucket, Sliding window?

For the first sample we provide, `MyCustomLimiter` should be as simple as possible and not too different from the sample code:

```
if (!StringValues.IsNullOrEmpty(httpContext.Request.Headers["token"]))
        {
            return RateLimitPartition.CreateTokenBucketLimiter("token", key =>
                new TokenBucketRateLimiterOptions(tokenLimit: 5, queueProcessingOrder: QueueProcessingOrder.OldestFirst,
                    queueLimit: 1, replenishmentPeriod: TimeSpan.FromSeconds(5), tokensPerPeriod: 1, autoReplenishment: true));
        }
```

>  Do you need a custom implementation of `RateLimiter`? Does that mean a new algorithm like Token Bucket, Sliding window?

A custom implementation of `RateLimiter` would probably be great too.

Create a PR with the sample code [here](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/middleware/rate-limit/samples).
