### ISSUE TITLE
One nuget installations command seems to be forgotten

### ISSUE THREAD

**Issue by senglory** [dotnet/AspNetCore.Docs#26523]
In my case attempt to issue 'Add-Migration' led to "The term 'Add-Migration' is not recognized" message in the cmd line.
Then I came across  [the following post](https://www.c-sharpcorner.com/blogs/addmigration-the-term-addmigration-is-not-recognized) and after issuing:

`Install-Package Microsoft.EntityFrameworkCore.Tools`

the following 'Add-Migration' started working

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Maybe you missed a prereq in the article
