### ISSUE TITLE
Page doesn't match link from

### ISSUE THREAD

**Issue by tgafpc** [dotnet/AspNetCore.Docs#26529]
this page is linked from the Configure Storage Emulator Local wizard in Visual Studio.

But the choices in the wizard do not match any labels in the doc.

So, the user has to guess, deduce, presume what each means.

Even worse, the consequences of each choice, like None, are not documented.

Very bad show.  Disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows&viewFallbackFrom=aspnetcore-2.2)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> this page is linked from the Configure Storage Emulator Local wizard in Visual Studio.

Where?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
