### ISSUE TITLE
Documentation, code examples seem poor

### ISSUE THREAD

**Issue by MarcoEnxuto** [dotnet/AspNetCore.Docs#26524]
Hi, 
I tried to understand the doc, but by using the coded provided on this page, seems quite impossible to get secrets by using DI.
Is this a draft?

Also, i checked the sample, and by using "Managed" it seems to not working correctly at all.
I read several times the doc, and i might get the idea.
How do i get a secret on a controller?
By using DI calling KeyVaultManager?
If so, how do i get the secret?

Seems confusing to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Also, i checked the sample, and by using "Managed" it seems to not working correctly at all.

Where do https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/key-vault-configuration/samples/6.x/KeyVaultConfigurationSample do that?

I recommend you first go through https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection and test your code with secrets manager then deploy to azure and test.
