### ISSUE TITLE
No DB schema example for SQLite

### ISSUE THREAD

**Issue by idobrodushniy** [dotnet/AspNetCore.Docs#26533]
Part 8, section [Apply migrations](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-6.0&tabs=visual-studio-code) ⬇️ 

We specify that the current schema of the table is 
```
CREATE TABLE [dbo].[Movie] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [Title]       NVARCHAR (MAX)  NULL,
    [ReleaseDate] DATETIME2 (7)   NOT NULL,
    [Genre]       NVARCHAR (MAX)  NULL,
    [Price]       DECIMAL (18, 2) NOT NULL,
    [Rating]      NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_Movie] PRIMARY KEY CLUSTERED ([ID] ASC)
);
```

Meanwhile, we don't mention it applies only to SQL server implementation (which is a showcase when people use Visual Studio, not Visual studio code), since if student follows the steps in the tutorial and uses Visual Studio Code, then the current schema is ⬇️ , because that's how EF core generated the migration for SQLite context. 

```
CREATE TABLE IF NOT EXISTS "Movie" (
    "ID" INTEGER NOT NULL CONSTRAINT "PK_Movie" PRIMARY KEY AUTOINCREMENT,
    "Genre" TEXT NOT NULL,
    "Price" decimal(18, 2) NOT NULL,
    "Rating" TEXT NOT NULL,
    "ReleaseDate" TEXT NOT NULL,
    "Title" TEXT NOT NULL
);
```

Probably I am getting something wrong or lacking experience with EF framework, then please suggest on why there is a difference in my local db and in the mentioned schema. 

Moreover, looks like in [code sample repo](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie60) we have only visual studio example, not the one with Visual Studio Code, it makes it kinda unfriendly for those who are coming for a cross-platform development. Again, probably I am just missing something, then please suggest! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Part 8, add validation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Earlier in the tutorial it recommends SQLite tools

**Comment by idobrodushniy** [comment]
@Rick-Anderson not sure what you mean. 
Could you please specify exactly the line in the doc and how SQLite tools are related to my question?
