### ISSUE TITLE
Logging Information is incorrect

### ISSUE THREAD

**Issue by crtjr64** [dotnet/AspNetCore.Docs#26544]
Signalr javascript is trapping all my errors so I don't know about them when called from a signalr process I created such as receive message. Inside the javaScript, this code is run by Signalr

`this._logger.log(LogLevel.Error, A callback for the method ${invocationMessage.target.toLowerCase()} threw error '${e}'.);`

which prevents the error from coming back to my browser and so I never see it while debugging I have tried turning it off per your instructions in this document using: `signalR.LogLevel.None` but to to Microsoft form, as I have found and complained about numerous times before, it doesn't work. The signalr app continues to trap the error and there's no way to get it to come back. In fact every option posed by this document failed to return the error back to me. this is a simple process, with as usual extremely unprofessional and poor documentation and I am again left in the dark. I need to debug my code and this removes that option from me and I have NO WAY to get these messages back to me... and yes, and unlike the documentation assumes I AM NOT USING TYPESCRIPT... I repeat: I AM NOT USING TYPESCRIPT!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef32cc5-6a1f-25c9-0d89-a984a3f68851
* Version Independent ID: 3e302985-8504-d333-3222-ab8da8902da2
* Content: [Logging and diagnostics in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/diagnostics.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/diagnostics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by crtjr64** [comment]
found an issue, it looks like the non option either doesn't work or is the default but when I specified the Information option, the messages came back to the console.

**Comment by Rick-Anderson** [comment]
Yes, the error log is the console.

**Comment by crtjr64** [comment]
it doesn't show the line of code as when I trap the error. These extra time wasting steps should have more detailed documentation... Its just skimmed over.
