### ISSUE TITLE
.NET 7: Request decompression middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26541]
[Request decompression middleware](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#request-decompression-middleware)

See https://github.com/dotnet/aspnetcore/pull/40279

Put sample [here](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/middleware/samples) then delete the [readme file](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/samples/readme.txt)

**Comment by Rick-Anderson** [comment]
@david-acker would you be interested in writing a sample app showing how to use you new Request decompression middleware?

**Comment by david-acker** [comment]
> @david-acker would you be interested in writing a sample app showing how to use you new Request decompression middleware?

Absolutely! I'd be happy to put something together.
