### ISSUE TITLE
Minimal API parameter binding for argument lists

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26540]
[Minimal API parameter binding for argument lists](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-5/#minimal-api-parameter-binding-for-argument-lists)

see https://github.com/dotnet/aspnetcore/pull/41325

Put code in https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/arg-lists/readme.txt and delete readme.txt

Use
```
var connection = new SqliteConnection("DataSource=:memory:");
connection.Open();
```

`@brunolins16` to review

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  @martincostello  anyone interested in writing this sample code?

**Comment by martincostello** [comment]
Sure, I can put something together for this.

**Comment by martincostello** [comment]
@Rick-Anderson I'll put together a specific example a bit later today or tomorrow, but I'd already written a sample app for an internal talk at my work last month, so I've just put the whole file for all the new features I did examples for as far as preview 5/6 [here](https://gist.github.com/martincostello/742dfe99eaa3d872bb90f5e3a295bba2). The specific one for `[AsParameters]` is [here](https://github.je-labs.com/martin-costello/aspnet-core-7-samples/blob/63b15e3c12418e52cf8520003c1a1e2d6b983f98/src/TodoApp/SampleEndpoints.cs#L200-L208).

**Comment by Rick-Anderson** [comment]
@martincostello  can you put your sample in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples ?

**Comment by Rick-Anderson** [comment]
@martincostello  do you have an ETA on when you'll be able to write this sample? If possible, use a variation of [todoitems](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api)

**Comment by martincostello** [comment]
Sorry for the delay with this - been quite busy with other things at the moment to get around to this. I'll aim to get you something for that other repo by the end of next week.

**Comment by martincostello** [comment]
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/26
