### ISSUE TITLE
.NET 7: Output caching middleware

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26542]
[Output caching middleware preview 7.6 blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-6/#output-caching-middleware)

Should this be a new topic under [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0)

<img width="208" alt="image" src="https://user-images.githubusercontent.com/3605364/181122879-a16dd3ef-c5f7-432b-8e97-51e19c6d0887.png">

cc @Tratcher

**Comment by Tratcher** [comment]
This is not minimal specific, it's a general ASP.NET Core capability.

@sebastienros

**Comment by Rick-Anderson** [comment]
> This is not minimal specific, it's a general ASP.NET Core capability.

We'll put it under [Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware)

**Comment by tdykstra** [comment]
I think it fits better under Performance --> Caching, alongside Response Caching Middleware.

![image](https://user-images.githubusercontent.com/1569635/183956382-6af9f367-c281-427f-a53a-e6501e668cd8.png)

**Comment by Rick-Anderson** [comment]
@tdykstra  put it under both.

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/AspNetCore.Docs/issues/26326
