### ISSUE TITLE
.NET 7:  Support for nullable models in MVC views and Razor Pages

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26569]
See [ Support for nullable models in MVC views and Razor Pages](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-7-preview-1/#support-for-nullable-models-in-mvc-views-and-razor-pages)

But it looks like this was added in .NET 6

See [Support for nullable models in MVC views and Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0#support-for-nullable-models-in-mvc-views-and-razor-pages)

**Comment by Rick-Anderson** [comment]
@martincostello is this really new for .NET 7 or was it .NET 6? If it's new for .NET 7, would you be able to write a sample using it?

**Comment by brunolins16** [comment]
@dotnet/aspnet-blazor-eng can someone help here?
