### ISSUE TITLE
Need detail about Build Identity components under Blazor Server Identity

### ISSUE THREAD

**Issue by Kumima** [dotnet/AspNetCore.Docs#26571]
[EDIT by guardrex to add the metadata. @Rick-Anderson ... I'll take care of this one. It's for the Blazor remarks in the Scaffolding doc.]

[Build Identity components](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio#build-identity-components)

This part needs to be detailed,"SignInManager and UserManager aren't supported in Razor components" is well questioned. Code samples are needed like how to build API controller to be used in Identity Razor components, especially for external login such as Microsoft for Razor Component, since I've realized basic login/out. The scaffold stuff is understandable, just feels weird when using different UI stuff. It will be better if we can keep building front in razor component when handling identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio#build-identity-components)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Kumima ... FYI, please use the **The page** feedback buttom and form from the bottom of any US-English topic to open issues here. It will add metadata about the topic and ping the author automatically. I'll manually add the metadata to your opening comment.

WRT your remarks: The product unit has indicated that they prefer (for the time being) not to provide auth-based Razor components, and they have told developers **_why_** SignInManager/UserManager aren't supported.

Some members of the community have put out third party packages to deal with it. Check [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor), search the Net, and ask on public forums.

Cross-references:

* https://github.com/dotnet/aspnetcore/issues/34095
* https://github.com/dotnet/aspnetcore/issues/21199
* https://github.com/dotnet/aspnetcore/issues/13601
* https://github.com/dotnet/aspnetcore/issues/11411

... and there are several other issues with similar remarks.

**_Leave this issue open._** I would like to investigate explaining the remark in the article further, possibly with a cross-link to that first product unit issue.

I'll be quite busy ⛰️⛏️😅 through the end of the year with .NET 7 documentation. I'll probably reach this in 23Q1.
