### ISSUE TITLE
Collection binding without index works only on Form Data

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#26580]
When working on this PR #24175, I accidentally removed the following statement:

* The following format is supported only in form data:
  ```
  selectedCourses[]=1050&selectedCourses[]=2000
  ```

Related: https://github.com/dotnet/aspnetcore/issues/42921

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections-2)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ladeak** [comment]
I still cannot see this on the rendered page, although based on the dates I am seem to be looking an up-to-date [version](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-6.0#collections-1)

![image](https://user-images.githubusercontent.com/10052368/198696619-63e4ef80-3e0d-4e06-beb9-42f5e8340cf6.png)

It should be here between the two samples: 
![image](https://user-images.githubusercontent.com/10052368/198696921-be2e6eaa-33a8-4a43-b843-3c95d360d8e1.png)

**Comment by ladeak** [comment]
What does the "The following format is supported only in form data:" mean? If I used [FromForm] attribute on the `List<Product> products` and replace the POST to GET it worked?

**Comment by ladeak** [comment]
Thank you
