### ISSUE TITLE
Scaffolding tutorial doesn't use the .NET 6 minimal hosting model used elsewhere

### ISSUE THREAD

**Issue by bretmcg** [dotnet/AspNetCore.Docs#26582]
In the tutorial _Web apps -> Razor Pages -> Add a model -> Scaffold the movie model_ the **Visual Studio for Mac** instructions include outdated code in the section: _Use SQLite for development, SQL Server for production_.

In that section the Mac code shows the Startup class, even though that code and file aren't generated using the default ASP.NET 6.0 minimal hosting model. The Visual Studio Code version appears to be correct.

I suggest swapping `[!INCLUDE[](~/includes/RP/sqlitedev.md)]` to instead use `[!INCLUDE[](~/includes/DevProdSQLite.md)]` to match the correct code example that the Visual Studio Code instructions use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bretmcg  thanks for reporting this. 
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
