### ISSUE TITLE
line should be in service rather than in controller

### ISSUE THREAD

**Issue by gbthakkar** [dotnet/AspNetCore.Docs#26596]
I am writing this to you because, I feel that MS document should provide example with "best practice"

The below line
updatedBook.Id = book.Id;

which is in controller - should be in service to make sure we update the values for the same object/document.

it is required to be in service so that if developer forget to do so, the service will ensure that it is updating the correct object.

let me know if you have different objective by putting it in controller.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Create a web API with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?WT.mc_id=dotnet-35129-website&view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Best practice is debatable.
