### ISSUE TITLE
This page is now specific to Top Level Statements

### ISSUE THREAD

**Issue by genifycom** [dotnet/AspNetCore.Docs#26598]
Because Microsoft chose to implement Top Level Statements, this page will not be able to be followed by anyone creating a new Blazor Webassembly app.

This is why we HATE developers just implementing something and then setting this as the DEFAULT!

With Top Level Statements there is no startup.cs so ALL doc has to be updated now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @genifycom ... Are you looking at the correct version of the doc? Check the version selector in the upper-left of the UI to confirm that you're looking at 6.0 or 7.0. If you still detect a problem, let me know what hosting model you're using (WASM or Server).

**Comment by guardrex** [comment]
Actually, I'm confused by your issue ... you speak about WASM, but there never was a `Startup.cs` in WASM. Clarify your scenario.
