### ISSUE TITLE
Startup.cs not fully compatible with .NET 6 secrets

### ISSUE THREAD

**Issue by fceci90** [dotnet/AspNetCore.Docs#26591]
I have an issue with the following statement: "Apps migrating to 6.0 don't need to use the new minimal hosting model."

It seems as though secrets.json will not get read if you are not using the new minimal hosting model, and decide to use Startup.cs. We upgraded an app from .NET Framework 4.7.2 and the upgrade assistant upgraded to .NET 6 using Startup.cs insted of the minimal hosting model. However, configuration won't read from secrets.json.

Based on this documentation here https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows: 

> [WebApplication.CreateBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createbuilder) initializes a new instance of the [WebApplicationBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplicationbuilder) class with preconfigured defaults. The initialized WebApplicationBuilder (builder) provides default configuration and calls [AddUserSecrets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) when the [EnvironmentName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.environmentname#microsoft-extensions-hosting-ihostenvironment-environmentname) is [Development](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.environmentname.development)

I don't see any way to call AddUserSecrets from within Startup.cs or Program.cs when using .NET 6 with Startup.cs.

Switching to the .NET 5 docs here https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0&tabs=windows I see the following:

> The user secrets [configuration provider](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers) registers the appropriate configuration source with the .NET [Configuration API](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0).
> 
> The user secrets configuration source is automatically added in Development mode when the project calls [CreateDefaultBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.host.createdefaultbuilder). CreateDefaultBuilder calls [AddUserSecrets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.usersecretsconfigurationextensions.addusersecrets) when the [EnvironmentName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostenvironment.environmentname#microsoft-extensions-hosting-ihostenvironment-environmentname) is [Development](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.environmentname.development):

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>();
        });
```
This is the code added when using the upgrade assistant.

When replacing CreateHostBuilder(args).Build().Run(); in Program.cs Main method with code that explicitly adds secrets.json as per the .NET 5 docs, the solution won't run in .NET 6:
```
public class Program
{
    public static void Main(string[] args)
    {
        var host = new HostBuilder()
            .ConfigureAppConfiguration((hostContext, builder) =>
            {
                // Add other providers for JSON, etc.

                if (hostContext.HostingEnvironment.IsDevelopment())
                {
                    builder.AddUserSecrets<Program>();
                }
            })
            .Build();
        
        host.Run();
    }
}
``` 
I've read through the migration documentation and I can't seem to find anything that addresses this issue, so I guess in the meantime I will just migrate over to using Program.cs. If these findings are correct, it would be helpful to add an annotation to the documentation that clarifies this issue. However, I assume there is a way to do this that I just can't figure out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#where-do-i-put-state-that-was-stored-as-fields-in-my-program-or-startup-class)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Access to secret manger is just part of configuration, can you get other configuration providers to work?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
