### ISSUE TITLE
WebApplicationFactory example test fails with: The entry point exited without ever building an IHost.

### ISSUE THREAD

**Issue by cove** [dotnet/AspNetCore.Docs#26609]
The [With WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#with-webapplicationfactory) example of how to [Test with WebApplicationFactory or TestServer](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#test-with-webapplicationfactory-or-testserver) doesn't appear to succeed using VS2022 (17.2.6) or Rider 2022.2 EAP 11.

Possibly there's something I'm not following in the docs too, not sure either way.

The following test code based on the example returns:
` System.InvalidOperationException : The entry point exited without ever building an IHost. `

Example code:
```c#
namespace Test
{
    public class Tests
    {   

        [Fact]
        public async Task HelloWorld()
        {
            var application = new WebApplicationFactory<Program>()
                .WithWebHostBuilder(builder => { builder.ConfigureServices(services => { services.AddSingleton<IHelloService, MockHelloService>(); }); });

            var client = application.CreateClient();

            var response = await client.GetStringAsync("/");

            Assert.Equal("Test Hello", response);
        }
        class MockHelloService : IHelloService
        {
            public string HelloMessage => "Test Hello";
        }
        internal interface IHelloService
        {
        }
    }
}

public partial class Program
{
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Version Independent ID: 20acee3e-8b6e-b3fb-8271-661e1a287bdd
* Content: [Code samples migrated to the new minimal hosting model in 6.0](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0#test-with-webapplicationfactory-or-testserver)
* Content Source: [aspnetcore/migration/50-to-60-samples.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jakewins** [comment]
I'm not sure this is the same as your issue, but I'm finding that anytime you have your Program.cs throw an exception, that exception gets lost (technically you can find it logged as an uncaught exception in console, it seems?), and you get this generic "your code didn't produce an IHost" error with no cause. 

You might try removing parts of your Program.cs, one line at a time, to see if you can figure out if any statement you've got there is throwing an exception. 

Alternatively, you could wrap all code before `builder.Build()` in a try-catch, where the catch just logs the error, to help you find what's failing.

**Comment by cove** [comment]
Right I found the same thing the real exception is lost and this exception is just telling you something went wrong. I'd expect the example in the docs to work however.

I gave up on the newer ways of starting things up since I ran into too many issues like this when using gRPC. And all the gRPC examples use the old startup style still and work fine.

**Comment by cove** [comment]
Solved and giving up are a little different imo, but ok :)

**Comment by jalle007** [comment]
I solved problem by adding this line to the bottom of program.cs 

`public interface IIdentityApiMarker { }`

**Comment by mh-logiten** [comment]
Given that the code in the Program.cs is run in-process you can just set a break point in the Program.cs file to diagnose these issues.
