### ISSUE TITLE
Non-specific configuration

### ISSUE THREAD

**Issue by BlanketFortGames** [dotnet/AspNetCore.Docs#26604]
The section on editing Properties/launchSettings.json gives no clue WHERE to put the specified lines.  Any error results in the app not starting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @BlanketFortGames ... It's at the root of the profile, as the example shows, where it says, "The following example shows the full launch profile for an app at port 7279:".

I'll add a cross-link to ...

https://docs.microsoft.com/aspnet/core/fundamentals/environments?view=aspnetcore-6.0#development-and-launchsettingsjson

... for more information.

Leave this issue open. It will close automatically when the PR merges.

**Comment by BlanketFortGames** [comment]
Sorry I was insufficiently specific about the section I was looking at.  I'm talking about a WASM app.

> If you prefer to configure the app's launch profile to specify the pathbase automatically instead of manually with dotnet run, set the commandLineArgs property in Properties/launchSettings.json. The following also configures the launch URL (launchUrl):

"commandLineArgs": "--pathbase=/{RELATIVE URL PATH (no trailing slash)}",
"launchUrl": "{RELATIVE URL PATH (no trailing slash)}",
Using CoolApp as the example:

"commandLineArgs": "--pathbase=/CoolApp",
"launchUrl": "CoolApp",

**Comment by guardrex** [comment]
It's the same thing ... maybe I'll add a pair of cross-links, one near each first mention. It will be on the PR shortly.
