### ISSUE TITLE
disambiguate "follows"- meaning of execution order, OR- text on the doc page 

### ISSUE THREAD

**Issue by xela-trawets** [dotnet/AspNetCore.Docs#26612]
"Host configuration follows application configuration"
is stated at the top of the page. I couldn't tell if this means that Host configuration happens "after" application configuration, or the word "follows" is describing the ordering of presentation in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Host configuration happens "after" application configuration

**Comment by xela-trawets** [comment]
Thanks, 
What was confusing me was that "The host is responsible for app startup and lifetime management" - implying that the Host would be instantiated first.  However, the configuration occurs in the opposite order.
