### ISSUE TITLE
.NET 7.0 Update: gRPC JSON transcoding: add support for multi-segment parameters

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#26622]
In the 7.0 version of the gRPC JSON transcoding add a new section: _Support for multi-segment parameters_ which was a feature added in .NET 7.0 preview 6.  

This issue has a parent tracking issue: #26477

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa3c933-30c4-eb49-d9a5-507aff44ce00
* Version Independent ID: 1485c456-eb24-a446-e296-dd3686456837
* Content: [gRPC JSON transcoding in ASP.NET Core gRPC apps](https://docs.microsoft.com/en-us/aspnet/core/grpc/httpapi?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/httpapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/httpapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@JamesNK , should I add a new section to this doc:  Support for multi-segment parameter, reflecting what you provided in 7.0 preview 6 blog, or do you envision that being covered elsewhere?

**Comment by JamesNK** [comment]
There is a link to https://cloud.google.com/service-infrastructure/docs/service-management/reference/rpc/google.api#google.api.HttpRule from our doc which covers how to annotate the proto files.

I would eventually like to summarize annotating on our gRPC JSON transcoding doc.

This particular feature - multi-segment parameters - is unlikely to be used by many people. Don't need to talk about it.

**Comment by wadepickett** [comment]
Thanks!
It looks like that is what you already covered annotating the _.proto_ here correct?  Maybe you want to expand more on what was provided there with info on HttpRule?
[Announcing gRPC JSON transcoding for .NET](https://devblogs.microsoft.com/dotnet/announcing-grpc-json-transcoding-for-dotnet/#getting-started)

Do you want me to get a PR started using your work and examples as a guide, or is this something you want to do yourself?

**Comment by wadepickett** [comment]
@JamesNK ,
Can I take what you already covered for annotating the .proto here and move it into a PR for this doc? 
[Announcing gRPC JSON transcoding for .NET](https://devblogs.microsoft.com/dotnet/announcing-grpc-json-transcoding-for-dotnet/#getting-started).

If you were looking forward to doing that yourself, that's cool, just seeing if I could help since I was assigned to get the updates in where I can that the What's new would point back to.

**Comment by wadepickett** [comment]
@JamesNK, Sorry for the needless noise, cancel that request on annotating.  I realized simply covering it as a step as it is in this doc already (of course) and you were wanting to summarize it better.  I'll give that a shot given what you already have available.

**Comment by wadepickett** [comment]
Tracking the new summary for annotation in #26688.  Closing this issue on multi-segment since we don't need it.
