### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by chrisleadbeater** [dotnet/AspNetCore.Docs#26639]
With all due respect, please provide more examples in addition to the steps required. Please do not assume everyone knows all that you do. Write with a "beginners mind". I needed to go elsewhere to discover how to deploy my new ASP.NET Core web app to IIS.

Interspersing a basic how to document with advanced topics such as "Data Protection" and "add registry keys" is not useful at this stage. Tell me how to get my new app up and running on IIS and then have advanced topics such as security, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
