### ISSUE TITLE
Missleading information about client streaming

### ISSUE THREAD

**Issue by iamNoah1** [dotnet/AspNetCore.Docs#26637]
[Enter feedback here]
The docs on the Section about client streaming say, that this kind of communication works 'without the client sending a message'. The following sentence: 'The client **can choose** to send messages with RequestStream.WriteAsync' implies that the client can but does not have to send messages to the server. 

But according to [this](https://grpc.io/docs/languages/csharp/basics/), the whole point of client streaming communication is that the client streams messages to the server instead of sending each message using the unary call. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7ec3c3-918c-6ffd-1ac0-4f88b89d9295
* Version Independent ID: 1c1f72f1-3d5d-3397-c17d-1889dbae6fee
* Content: [Call gRPC services with the .NET client](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
In the example below `AccumulateCount` starts a gRPC client streaming call without sending a message. And a client streaming call can complete without one being sent.

I don't know what is misleading here.
```cs
var client = new Counter.CounterClient(channel);

// starts call to the server (without sending a message)
using var call = client.AccumulateCount();

// send message (optional)
await call.RequestStream.WriteAsync(new CounterRequest { Count = 1 });

// complete request stream
await call.RequestStream.CompleteAsync();
```

**Comment by iamNoah1** [comment]
Thanks for the quick feedback @JamesNK. I found it misleading, because what's the point of client stream method of communication if the client does not send any message at all. My suggestion is to rephrase it a little bit in order to show the difference to the unary call which is: make a call (aka open a stream) and then send messages vs send separate requests not using a call (aka stream). 

What do you think?

**Comment by wadepickett** [comment]
Closing this issue.  If you feel it should be reopened, feel free to do so.
