### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by Brain2000** [dotnet/AspNetCore.Docs#26636]
This page does not describe when you would use Factory vs Conventional middleware. Showing me how to do something doesn't help to understand WHY you want to use one over the other.

Also, the UseTransient< > function is used for the factory. Why? What is AddTransient< >? I read recently that there is also a AddScoped< >, what is that? Or AddSingleton< >??

Why is Microsoft documentation always lacking and I have to go to 3rd party services like Stackoverflow constantly to figure out how to do anything!? I've been developing for 25 years, since Windows NT 4.0. I just cannot believe that the documentation is still so lacking all these years later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f5eb44-55e5-d4a5-0ab1-5122c29a1db5
* Version Independent ID: 0b8da6a7-8333-5d8f-23a5-05bf0ca661f9
* Content: [Factory-based middleware activation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/extensibility.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Also, the UseTransient< > function is used for the factory. Why? What is AddTransient< >? I read recently that there is also a AddScoped< >, what is that? Or AddSingleton< >??

See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0

**Comment by Brain2000** [comment]
Thank you Rick, this is good documentation. It clears up some of the confusion. I wish there were better examples and links between documentation pages. I'm the type of person who needs to know why something works. I hate using code just for the sake of using it just because the documentation showed an example. That's an assured recipe to guarantee you can't troubleshoot something when things go wrong.

I am converting a .net 4.8 web api application with hundreds of endpoints to .net 6. I feel like the documentation is all there... somewhere... but finding all the pieces is like looking for Waldo. It seems like it is taking an exceedingly long time to find all the pieces of information needed.

I'm a bit surprised that there doesn't seem to exist a tutorial showing an extensive conversion of Global.asax.cs to Program.cs and Startup.cs in asp.net 6.

Thank you for your time Rick.

**Comment by Rick-Anderson** [comment]
> Startup.cs in asp.net 6.
ASP.NET Core 6 doesn't use Startup

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
