### ISSUE TITLE
Page is not helpful

### ISSUE THREAD

**Issue by genifycom** [dotnet/AspNetCore.Docs#26631]
Stating this does NOT help me find how to do it.

Files can be downloaded from the app's own static assets

BTW, adding Top Level Statements has COMPLETELY messed up finding solutions to anything!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Version Independent ID: e4ad584d-0d9a-da8c-1296-b2d186e437ad
* Content: [ASP.NET Core Blazor file downloads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-downloads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-downloads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
Hello @genifycom ... I'll take a look at clarifying that Static File Middleware is the underlying API actually serving the file content for hosted WebAssembly and Blazor Server (if the source of the file is either of those app types) either via streaming (small files) or via the URL approach (large files) as described by the article. However, these are also the recommended small and large file approaches when the server is a different app or source (e.g., CDN, file server, etc.).

Minimal APIs (top-level statements) is the recommended approach by the product unit as of ASP.NET Core 6.0. We won't show both approaches for all of the examples everywhere. Besides, it isn't relevant specifically to this article outside of CORS configuration, which is only covered here by way of cross-links. Nothing here pertains to `Program.cs`.
