### ISSUE TITLE
Test your documentation

### ISSUE THREAD

**Issue by chrisleadbeater** [dotnet/AspNetCore.Docs#26640]
Suggestion: Before publishing a how-to page like this (or any topic for that matter). Create a new, fresh Windows 10 computer/VM and have someone on your staff do the same process based solely on the documentation. Test your documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f92a99a8-6ffa-e5f9-b7ef-f13fa1e0f17b
* Version Independent ID: 51273790-5178-875b-010e-15d7725da535
* Content: [Publish an ASP.NET Core app to IIS](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio#prerequisites)
* Content Source: [aspnetcore/tutorials/publish-to-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@chrisleadbeater  please don't make duplicate issues #26639
