### ISSUE TITLE
Under "Save the access token" the `props` variable is initialized but not used

### ISSUE THREAD

**Issue by paviad** [dotnet/AspNetCore.Docs#26651]
The example where external login provider tokens are persisted in the application cookie does not work. The `props` variable of type `AuthenticationProperties` which is initialized in `OnPostConfirmationAsync` is not actually used, and the tokens are not added to the cookie.

***EDIT by @Rick-Anderson***
[Save the access token](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-6.0#save-the-access-token)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faf33b-2511-5e8f-c1b0-94f32dc07fa4
* Version Independent ID: 2697abc8-7727-2eba-74a5-fbbc8a7c80ff
* Content: [Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/security/authentication/social/additional-claims.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @paviad ... Thanks for the report. I see what you mean. Yeah, I think that's the wrong overload for `SignInAsync`. It probably should be the one that takes an auth properties (i.e., `props`) ... and you can see that the setting for `props` already sets `IsPersistent`.

Try that this way and see how it goes ...

```csharp
await _signInManager.SignInAsync(user, props, info.LoginProvider);
```

**Comment by paviad** [comment]
That is 100% correct, a fix to the documentation here is simple.

Note however, that there is no suitable overload when using external login, see https://github.com/dotnet/aspnetcore/issues/12047

I've submitted a PR for it https://github.com/dotnet/aspnetcore/pull/43132

**Comment by Rick-Anderson** [comment]
> That is 100% correct, a fix to the documentation here is simple.

@paviad 
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by paviad** [comment]
I'd love to but how do I access the code snippets? They appear as
```
[!code-csharp[](additional-claims/samples/6.x/ClaimsSample/Program.cs?name=snippet_AddGoogle2&highlight=9)]
```

and

```
[!code-csharp[](additional-claims/samples/6.x/ClaimsSample/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs?name=snippet_OnPostConfirmationAsync&highlight=49-53)]
```

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/additional-claims/samples/6.x/ClaimsSample/Program.cs

**Comment by paviad** [comment]
Hmm, I might have submitted an incomplete PR, the highlight should be added to that modified line too, shouldn't it?

**Comment by paviad** [comment]
I could not verify that the highlight change actually hits the desired line, but the numeric calculations check out :)
