### ISSUE TITLE
Typo in Tutorial razor page

### ISSUE THREAD

**Issue by oinpentuls** [dotnet/AspNetCore.Docs#26653]
Hi, 

There is minor typo in this page under the visual studio code tab. It should be `development`.

![image](https://user-images.githubusercontent.com/39396616/183301549-c1d2459b-9cb0-426f-8ff9-274a90ea2ca0.png)

![image](https://user-images.githubusercontent.com/39396616/183301566-4a5792b6-d15d-4d70-a32c-3a82b518d663.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by oinpentuls** [comment]
I think it is already fixed. The paragraph has changed.

![image](https://user-images.githubusercontent.com/39396616/183315798-d919b897-1756-4bf4-b397-7178e695748c.png)
