### ISSUE TITLE
Outdated Visuals and Code Samples

### ISSUE THREAD

**Issue by jeffpatton1971** [dotnet/AspNetCore.Docs#26665]
This document describes setting up attribute based routing with net 4.61 and we're currently on 6.0. The images are from VS 2017 and the current version is 2022. Attempting to follow along with this tutorial in current technologies is difficult as things have changed a little, could we look at perhaps updating this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> This document describes setting up attribute based routing with net 4.61 and we're currently on 6.0.

Where  is .NET 6.41 mentioned?

> The images are from VS 2017 and the current version is 2022.
What image?

**Comment by jeffpatton1971** [comment]
If you look at the images on the page, those step you through everything and that's where it shows .net version and outdated visual studio interfaces.

**Comment by Rick-Anderson** [comment]
> that's where it shows .net version and outdated visual studio interfaces.

Can you provide a screen shot here?

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
