### ISSUE TITLE
Support MVVM in future release?

### ISSUE THREAD

**Issue by GreggAtCarfac** [dotnet/AspNetCore.Docs#26669]
Hello

We find it very interesting to combine Blazor pages with wpf and are testing how far we can go with this.
I have created a multi screen wpf application with Razor pages and ViewModels (MVVM) using Microsoft.Extensions.DependencyInjection.
We notice if we change a property on 1 screen, it does not update on the other screen.
Not even when we call the Onpropertychanged event. 

is this support coming in a future release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Version Independent ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Content: [Build a Windows Presentation Foundation (WPF) Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/wpf.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GreggAtCarfac ...

Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
