### ISSUE TITLE
Article needs a better walkthrough of how to get to app service logs

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/AspNetCore.Docs#26664]
There is a pretty easy way to be able to diagnose startup failures in ASP.NET Core apps on app service, but you need to know the trick, which doesn't seem to be readily documented anywhere. This mechanism is easier that what is included at https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0#troubleshoot-on-azure-app-service.

In the Azure Portal for the app:

* In the left pane, go to `Monitoring` -> `App Service Logs`, and turn on filesystem logging for `Web Server Logging`. You can turn on Application logging here too.
* In the left pane go to `Monitoring` -> `Log stream`, and then select the `Web Server Logs` option.

You will then get a live view of the logs, and can retry the scenario to see what is causing the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a7104-1d14-2e8a-0984-d92aa311c108
* Version Independent ID: 5e3c0546-c579-afb9-5289-b14532c127eb
* Content: [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/troubleshoot-azure-iis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/troubleshoot-azure-iis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@samsp-msft thanks for the tip, I'll get this documented.

**Comment by Rick-Anderson** [comment]
<img width="188" alt="image" src="https://user-images.githubusercontent.com/3605364/183528550-27e54ad0-32ff-4a42-88e0-1e37dd6d2027.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/3605364/183528795-532665c0-ce87-4ed3-8e4d-4b374d469c2a.png">

That's so cool. I'll get this documented ASAP. I'd love to include a few images buy Azure portal images change so frequently. Should I add a few images and when they change just delete the images?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/183529287-f63d3e1c-ee5b-4ca1-bcb6-a8c29d8b26f5.png)

**Comment by samsp-msft** [comment]
Yes. I think having the images will make it easier to understand, and also provides a signpost in the doc so that if you scroll through it quickly, it'll catch your eye. Thankfully this isn't that long an article, but it always helps when scanning through to see what sub consciously pops out at you.

This doesn't seem to be well documented anywhere.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/183561255-91f3d5e1-141b-413b-a403-91e74a770545.png)

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/183573538-80645002-d1c3-4451-9a2f-91ef4de4e248.png)
