### ISSUE TITLE
Simplify Introduction to Localization Help Page

### ISSUE THREAD

**Issue by s52** [dotnet/AspNetCore.Docs#26676]
This article is an introduction to localisation. It appears to contain a lot of useful information, but I think that users would already need to understand a lot about localisation to understand the article. Can I make the following suggestions.

Anyone looking at this article wants to be able to (a) create a Net Core MVC project, then (b) define a resource in say two languages, then (c) see a view with that string translated, then (d) know how to change the URL, or the code, to change the language used.

The example you've supplied is far far too long. We don't need a triple or four column layout. We don't need 20 links. We need (a) no columns, and (b) one localisation example.

If someone wants to localise a site, and they are starting, and looking at this article, they may want to know (a) how to have a single global resource file, I think a lot of small sites would need no more than this, and (b) how to use resource files at the controller level.

So you need :-

 - A very very very simple example of a global resource file
 - A very very very simple example of two non-global resource files
 
Once you have these two very simple examples, it would be really helpful for users who know very little about i18n but want to used it if you could :-

 - Comment these files profusely IMPORTANT
 - Comment every line that you add to the base project produced by Visual Studio IMPORTANT

On a final note, when you click on the feedback link at the bottom of the page, it moves to this page. The problem is that anyone making comments on a page wants to refer to the page when drafting the feedback. So, when users click on the feedback link, it makes much more sense to open a new tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback. This is a complicated topic and we don't have the resources to make a quick guide and maintain the complete guide.

**Comment by s52** [comment]
Hi Rick

Just to let you know that I quite understand the position, but really
appreciate the feedback.

I'm in the middle of creating a guide for my own use, and if it turns out
to look helpful, I'll keep you posted.

Cheers

Terence

Terence Schoenherr
Head of Development

Travinet Ltd
***@***.***
www.travinet.com
+44 (0)1493 600954
