### ISSUE TITLE
IFormFile/IFormFileCollection support for authenticated requests in minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26683]
[IFormFile/IFormFileCollection support for authenticated requests in minimal APIs](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/#iformfile-iformfilecollection-support-for-authenticated-requests-in-minimal-apis)

See    #26345 Code done, see #26453 can't publish until .NET 7 . See also [test sample](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/samples/IFormFile/Program.cs)

**Comment by Rick-Anderson** [comment]
@martincostello  can you update the code from #26494 to use authenticated requests?

**Comment by martincostello** [comment]
Might that get a bit scope-creepy having to configure a whole app's worth of auth stuff into a non-auth sample to just go _"oh, and it works in that context too now"_?

It's not really relevant to the file upload functionality in of itself other than before preview 1 it was actively blocked as the security-concerns hadn't been addressed at that point.

Feels to me it's equivalent to if there was a feature that only worked on Windows for a while, and then later it also worked on other OSs. You wouldn't update the samples to prove they also now worked on the other operating systems.

Or am I misunderstanding exactly what you're asking for?

**Comment by Rick-Anderson** [comment]
@martincostello do you think if we just say authenticated requests are supported, that's enough?

**Comment by martincostello** [comment]
Maybe just something that points the user to consider whether they would also need to incorporate anti-forgery like in the blog post?

> There is no built-in support for anti-forgery in minimal APIs. However, it can be [implemented using the IAntiforgery service](https://docs.microsoft.com/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0#antiforgery-with-minimal-apis).

**Comment by Rick-Anderson** [comment]
> Might that get a bit scope-creepy having to configure a whole app's worth of auth stuff into a non-auth sample to just go _"oh, and it works in that context too now"_?

If I use JWT like [this sample](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/rate-limit/WebRateLimitAuth/Program.cs#L383-L451) it one short file. But even that doesn't seem worth doing.



> Maybe just something that points the user to consider whether they would also need to incorporate anti-forgery like in the blog post?
> 
> > There is no built-in support for anti-forgery in minimal APIs. However, it can be [implemented using the IAntiforgery service](https://docs.microsoft.com/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0#antiforgery-with-minimal-apis).

Agreed, I'll do that.
