### ISSUE TITLE
.NET 7.0: Add mention WebSocket support over HTTP/2 in topic: WebSockets support in ASP.NET Core

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#26696]
SignalR and the SignalR browser JavaScript client have been updated to support WebSockets over HTTP/2. Introduced in .NET 7.0 Preview 6.  

Something like:

.NET 7.0 allows WebSocket support over HTTP/2 for:

- ASP.NET Core SignalR JavaScript client
- ASP.NET Core SignalR with Blazor WebAssembly

Using WebSockets over HTTP/2 lets you take advantage of new features like header compression and multiplexing that reduce the time and resources needed when making multiple requests to the server.

Fixes #26477   (Final PR for it.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#signalr)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
Note: Only clients running in the browser have support for this today. So javascript or SignalR .NET client with WASM.

**Comment by wadepickett** [comment]
Thanks @BrennanConroy!

Should I wait until RTW to see where it is at then, or just mention those two new options for now (in this Websockets topic).

**Comment by BrennanConroy** [comment]
Either is fine, if you do the latter, maybe keep the issue open and assign me to look at and update once we RTM if it needs updating.

**Comment by Rick-Anderson** [comment]
Dup of #26366

**Comment by wadepickett** [comment]
Closing since this is a duplicate of Dup of https://github.com/dotnet/AspNetCore.Docs/issues/26366
