### ISSUE TITLE
Rename RouteHandlerFilter to EndpointFilter

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26699]
See https://github.com/dotnet/aspnetcore/pull/42678/files

@fiyazbinhasan  can you update your code in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/min-api-filters/7samples then I'll update the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a109e339-bce8-9580-12f8-dab879a3dcfc
* Version Independent ID: a109e339-bce8-9580-12f8-dab879a3dcfc
* Content: [Filters in Minimal API applications](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/min-api-filters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/min-api-filters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Hi @Rick-Anderson, sure I'll take a look at it asap :)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson we can close this
