### ISSUE TITLE
swift5 iOS no proper document. 

### ISSUE THREAD

**Issue by santhoshappdev** [dotnet/AspNetCore.Docs#26703]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc76539-dcd8-8271-b876-f2b492af9b49
* Version Independent ID: d0106767-c04e-39a8-fe1d-a40352552c62
* Content: [ASP.NET Core SignalR supported platforms](https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/supported-platforms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/supported-platforms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
The SignalR team does not ship a supported Swift or iOS client **to** document.
