### ISSUE TITLE
Including passing parameter the interceptor

### ISSUE THREAD

**Issue by jwu-dharmo** [dotnet/AspNetCore.Docs#26707]
It will be nice to include information on how to pass parameters the the interceptor.

For example, I know we can specify parameters during the AddServiceOptions() call, but how do we "pass on that value" to AddTransient() or AddSingleton() call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf211766-acfe-e599-8286-a5b1d8a071f1
* Version Independent ID: cf211766-acfe-e599-8286-a5b1d8a071f1
* Content: [gRPC interceptors on .NET](https://docs.microsoft.com/en-us/aspnet/core/grpc/interceptors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/interceptors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/interceptors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @erni27
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Closing.  If you feel this issue should be reopened, feel free to do so.
