### ISSUE TITLE
How about a Beginners Version

### ISSUE THREAD

**Issue by bizinbarefeet** [dotnet/AspNetCore.Docs#26724]
I have no idea how to get setup basic email service in a demo asp.net core web app.  How about making a beginners version of this file as its linked from the web app template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Follow the sendgrid link.

**Comment by bizinbarefeet** [comment]
We don't use SendGrid.  Just want a simple SMTP email service.  Am so surprised it's not provided out of the box like previous frameworks.

**Comment by Rick-Anderson** [comment]
> Just want a simple SMTP email service

There is no such thing. They're difficult to secure and impossible to get through SPAM filters.

**Comment by bizinbarefeet** [comment]
Hmmmm.  So unlike previous Microsoft IDEs which provided working templates out of the box there is none in .net core to allow a user to setup a test installation with test user login.  I find this very strange.
