### ISSUE TITLE
Replace string arguments with typed parameters at ContosoUniversity/Pages/Courses/DepartmentNamePageModel.cs

### ISSUE THREAD

**Issue by zxcq544** [dotnet/AspNetCore.Docs#26725]
This fix is for page https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-6.0 ,
line 31 of  page https://github.com/dotnet/AspNetCore.Docs/edit/main/aspnetcore/data/ef-rp/update-related-data.md ,
which leads to source code https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Courses/DepartmentNamePageModel.cs#L21 . Fix is at line 21.

Currently line 20-21 of https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu50/Pages/Courses/DepartmentNamePageModel.cs#L20 looks like that 
```C#
DepartmentNameSL = new SelectList(departmentsQuery.AsNoTracking(),
                        "DepartmentID", "Name", selectedDepartment);
```
Here we can see that SelectList parameters "DepartmentID" and "Name" are passed as strings, but it would be better to pass typed values like that
```C#
DepartmentNameSL = new SelectList(departmentsQuery.AsNoTracking(), 
                        nameof(Department.DepartmentID), nameof(Department.Name), selectedDepartment);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Part 7, Razor Pages with EF Core in ASP.NET Core - Update Related Data](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 58041](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58041)

**Comment by Rick-Anderson** [comment]
@zxcq544  I agree. We'll likely do that on the next update of the doc. cc @tdykstra
