### ISSUE TITLE
Too high level

### ISSUE THREAD

**Issue by randykroeger** [dotnet/AspNetCore.Docs#26727]
Although, the post was good in providing snipits.  It really does not help in understanding what is being built.  We only get the using statement and the code from within the method.  You should provide the full contents of your code file to give a better picture.  Copying this will not help someone that is starting out.   Also, providing descriptions is always helpful as well (e.g. post, put, get...).  It is basic, but it helps in understanding what is being built and the purpose.   

No need to respond.  This was only a review. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
All the code is included in the tutorial.
