### ISSUE TITLE
Add Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore in NuGet Package Section

### ISSUE THREAD

**Issue by useready-andyv** [dotnet/AspNetCore.Docs#26737]
Code does in not compile in 'Add API Code' section as NuGet package 
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore is missing in [previous step](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio#add-nuget-packages). Please update the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @useready-andyv ... The instruction is already present (the last bullet point).

https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio#add-nuget-packages

**Comment by guardrex** [comment]
Oh! Did you mean for the Visual Studio for Mac tab?

**Comment by useready-andyv** [comment]
Would suggest moving the last bullet up before selecting the project box for ease of use I missed it some others might miss the same thing too!

Pardon my typos, thumb typed on a handheld.
________________________________

**Comment by guardrex** [comment]
I don't disagree and made the suggestion a while back. Let's leave this for @Rick-Anderson to take a look at. I was only closing it because I thought that we had it covered. There are two considerations ...

* That package has been missed over the years by several devs.
* The VS4Mac tab isn't claiming that it should be added, but I don't understand why. Seems like it should be there, too.

**Comment by Rick-Anderson** [comment]
We'll look at this on the next update.

**Comment by Rick-Anderson** [comment]
> Oh! Did you mean for the Visual Studio for Mac tab?

The meta-data links contain the tab and the version when the issue is created.. No need to guess.
