### ISSUE TITLE
Setting IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion

### ISSUE THREAD

**Issue by alexisconsuegra** [dotnet/AspNetCore.Docs#26748]
First suggested method: Adding  <IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion> to PropertyGroup did not solved the problem. Is there anything missing in this aproach?
Migrating to Boostrap 5 is not possible at this time.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7a18c8-acae-f101-fcbd-f3b79f4e7c9f
* Version Independent ID: 266e32ee-567e-f8dd-7da8-e82c277aab1c
* Content: [Breaking change: Default version of Bootstrap used with Identity now 5 - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5)
* Content Source: [docs/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/aspnet-core/6.0/identity-bootstrap4-to-5.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @serpent5
* Microsoft Alias: **gewarren**

**Comment by alexisconsuegra** [comment]
Hi Yes, let me have a simple project. FYI. It works in my local host, but it throws the error at my hosted enviroment. I have confirmed core 6 is installed.

**Comment by bcons009** [comment]
Hi. This is the simple repo with @alexisconsuegra 's issue: https://github.com/bcons009/netcore-demo5

**Comment by Rick-Anderson** [comment]
@alexisconsuegra  I create an ASP.NET Core MVC project with individual user accounts using .NET 6, then I updated the project settings with the following:
```
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<IdentityUIFrameworkVersion>Bootstrap4</IdentityUIFrameworkVersion>
		<UserSecretsId>aspnet-WebApplication1-66EF50D6-BDA8-4633-8B19-2CB038E9DA15</UserSecretsId>
	</PropertyGroup>
```
And it worked as expected. F12 tools shows it's using Bootstrap4

**Comment by alexisconsuegra** [comment]
I guess the work around only works in localhost. FYI. Locally works for me too, but not in the hosted enviroment.

**Comment by Rick-Anderson** [comment]
https://webbootstrap44.azurewebsites.net/
Works fine deployed too.
