### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Jymms** [dotnet/AspNetCore.Docs#26743]
[Enter feedback here]
Maybe it's the title of the page "ASP.NET Core Blazor" which isn't an option when making a project?  Maybe there's a step that is being skipped? I selected Blazor Server App and I do not get a picture.  I get an icon of a broken picture and when I put in alt="Not working" that shows as well.

Running it as IIS Express or the name of the project produces the same result. 

The page will load I can put other things on the page i.e. 
<h3> Test Images <h3> 

But I can not get an image to show. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Version Independent ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Content: [Work with images in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
Hello @Jymms ... That's not enough information to understand what you did. Can you explain out exactly what you did (e.g., show code) or put up a repro project in GitHub for me to look at?

**Comment by Jymms** [comment]
I've started a new project and it works, so I must have done something while following the tutorials.  Maybe I've screwed up the css file?  I'm not sure, but with a fresh project it works.

**Comment by guardrex** [comment]
I don't know without analysis, which I'm hard pressed to perform under the workload here.

Can we close this as 'fixed by customer'?

**Comment by Jymms** [comment]
Yes, I will use this project as my new 'examples' project and delete the one I've messed up. Retyping the other pages is good for the memory anyway ;)  (i.e. how to make a Grid...)
