### ISSUE TITLE
Missing information that duplicate keys from the same source is invalid

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/AspNetCore.Docs#26752]
The documentation is missing the information that duplicate keys from the same provider are not allowed.

This will succeed:

```csharp
var configFile1 = Path.Combine(Environment.CurrentDirectory, "appsettings1.json");
File.WriteAllText(configFile1, "{\"setting\":\"value\"}");
var configFile2 = Path.Combine(Environment.CurrentDirectory, "appsettings2.json");
File.WriteAllText(configFile2, "{\"SETTING\":\"VALUE\"}");
var config = new ConfigurationBuilder()
    .AddJsonFile(configFile1)
    .AddJsonFile(configFile2)
    .Build();
```

And this:

```csharp
var section = config.GetSection("setting");
Console.WriteLine($@"Key: {section.Key}
Path: {section.Path}
Value: {section. Value}");
```

will output this:

```text
Key: setting
Path: setting
Value: VALUE
```

But this:

```csharp
var configFile = Path.Combine(Environment.CurrentDirectory, "appsettings.json");
File.WriteAllText(configFile, "{\"setting\":\"value\", \"SETTING\":\"VALUE\"}");
var config = new ConfigurationBuilder()
    .AddJsonFile(configFile)
    .Build();
```

will throw:

```text
An item with the same key has already been added. Key: SETTING

   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   ...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#keys)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by paulomorgado** [comment]
https://github.com/dotnet/docs/issues/30709

**Comment by Rick-Anderson** [comment]
Why would you want to use duplicate keys? Doing so throws an exception to tell you the problem. Why should that be documented?

**Comment by Rick-Anderson** [comment]
In [Configuration keys and values](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#configuration-keys-and-values) we state:

Configuration keys:

Are case-insensitive. For example, `ConnectionString `and `connectionstring` are treated as equivalent keys.
