### ISSUE TITLE
Note requirement to include UseStaticWebAssets in Staging environment

### ISSUE THREAD

**Issue by KurtP20** [dotnet/AspNetCore.Docs#26751]
[EDIT by guardrex to change the metadata]

I bumped into a nasty error when switching from Devlopment so Staging environment: In Staging, static web assests (e.g. site.css and other java scripts) are not served automatically. You can try this by making a new Blazor Server Side App, switch to Staging and you will see, that site.css is not loaded.

The [fix](https://forum.radzen.com/t/radzen-blazor-components-dont-respect-custom-environments/2690/2) seems to be to include `UseStaticWebAssets`. Unfortunately, it took me quite a while to figure out where to include this, so a code example would be useful. I work off the .net 5 template, so in `Program.cs` I added
`Host.ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStaticWebAssets();   
                    webBuilder.UseStartup<Startup>();
                })`

I also did not find a description of the side effects when including `UseStaticWebAssets` in all environments and I don't know how to access the Environment in `ConfigureWebHostDefaults`.

- [ ] I think it would be good to mention/highlight the need to include `UseStaticWebAssets` on this page in the documentation and also in the xml documentation of `ConfigureWebHostDefaults`, as it mentions that static assets are included, but does not mention that this is only in development environment.

- [ ] Please also elaborate on the side effect of using `UseStaticWebAssets` in all environments in the api documentation [page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilderextensions.usestaticwebassets?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStaticWebAssets)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=aspnetcore-6.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0af7f84-f8dd-92d9-dacd-2aab76d3a039
* Version Independent ID: 25458428-030f-6acb-457e-1b4dfa722043
* Content: [ASP.NET Core Blazor static files](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  please review

**Comment by guardrex** [comment]
Hello @KurtP20 ... *Interesting!* Yes, I just found out that this is a by-design *feature* 😄. See ...

https://github.com/dotnet/aspnetcore/issues/39596#issuecomment-1015279408

I'm going to update the metadata and work this guidance into the Blazor *Static Files* topic, probably with a cross-link in the Blazor *Environments* topic.

**Comment by guardrex** [comment]
I'm going to take a closer look when I get back to this, but try it this way ...

```csharp
if (builder.Environment.IsEnvironment("Staging"))
{
    StaticWebAssetsLoader.UseStaticWebAssets(builder.Environment, builder.Configuration);
}
```

**Comment by KurtP20** [comment]
Thanks for updating the documentation! 

In the .net 5 template I don't see right away where to include your code. But now I better understand the "side effects" and the reason of having to use `UseStaticWebAssets`, and since I do want to serve static context in all environments, I do not need to access the environment any more. Thanks for your help.

**Comment by guardrex** [comment]
I found this in a discussion ...

```csharp
.ConfigureAppConfiguration((ctx, cb) => {
	if (ctx.HostingEnvironment.IsStaging()) {
		StaticWebAssetsLoader.UseStaticWebAssets(ctx.HostingEnvironment, ctx.Configuration);
	}
});
```

**Comment by guardrex** [comment]
Looks like this ...

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseStaticWebAssets();
```

... should work for 7.0 or later. It looks like the workaround in 6.0 is simply ...

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseWebRoot("wwwroot").UseStaticWebAssets();
```

When I get the PR put together, I'll ping Safia to look and confirm that I have the guidance correct.

**Comment by KurtP20** [comment]
... and in 5.0 it is
```
Host.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder.UseStaticWebAssets();    
    webBuilder.UseStartup<Startup>();
})
```

Your suggestion
```
.ConfigureAppConfiguration((hostContext, builder) => 
{                    
    StaticWebAssetsLoader.UseStaticWebAssets(hostContext.HostingEnvironment, hostContext.Configuration);
});
```
does not work for me as parameter 1 cannot be converted from `IHostEnvironment` to `IWebHostEnvironment`, but one could probably simly call `StaticWebAssetsLoader.UseStaticWebAssets` without parameters. The first version is preferred as the call to `ConfigureWebHostDefaults` is already in the template and `ConfigureAppConfiguration` is not.

**Comment by guardrex** [comment]
Well, it wasn't **_my_** suggestion 😄 ... it was in the discussion remarks. Yes, that's right about the param. I did note it in passing. One my personal problems here is that I just set up a brand new PC, and I didn't get it set up with 5.0 hoping that I wouldn't need to. I'd rarely use it, as we're heading into 7.0 at this point. I may fire up the old PC to see what's what.

**Comment by guardrex** [comment]
I didn't really copy it exactly. They actually have ...

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureAppConfiguration((ctx, cb) => {
    if (ctx.HostingEnvironment.IsStaging()) {
        StaticWebAssetsLoader.UseStaticWebAssets(ctx.HostingEnvironment, ctx.Configuration);
    }
});
```

**Comment by KurtP20** [comment]
I would not want to install 5.0 on a new machine either. It's just so much work to change from the 5 to the 6 template where app configuration is much different. The solution with `ConfigureWebHostDefaults` works and looks similar to `builder.WebHost.ConfigureAppConfiguration`.

**Comment by guardrex** [comment]
I can keep the default.

It's just that I don't like cluttering my machine with hundreds of megs of (mostly) *dead files* 💀 ... *5.0, it's so 2021!* 😆

**Comment by KurtP20** [comment]
I found these related issues [13190](https://github.com/dotnet/aspnetcore/issues/13190) and [13864](https://github.com/dotnet/AspNetCore.Docs/issues/13864) via [this post](https://forum.radzen.com/t/radzen-blazor-components-dont-respect-custom-environments/2690/2), maybe you want to leave a comment at those issues as well?
