### ISSUE TITLE
Facebook external authentication in Angular application doesn't work based on document

### ISSUE THREAD

**Issue by hifeamin** [dotnet/AspNetCore.Docs#26757]
I have tested this document and it redirect to the Facebook. but when return to the address "https://localhost:{port}/signin-facebook" the angular returns this error:

```core.js:6479 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'signin-facebook' Error: Cannot match any routes. URL Segment: 'signin-facebook'```

I think something is missed in the document. I have done this to do it correctly.

I have just added `"/signin-facebook"` to the property `PROXY_CONFIG.context` in the file `proxy.conf.js`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Angular is beyond the scope of this tutorial.
