### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Api.Analyzers does nothing; docs or product?

### ISSUE THREAD

**Issue by kjkrum** [dotnet/AspNetCore.Docs#26764]
I've followed [the docs](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-6.0) to enable `Microsoft.AspNetCore.Mvc.Api.Analyzers` in a aspnetcore-6.0 project in VS2022 17.2.6 and 17.3.1. The analyzer is listed in the Solution Explorer under Dependencies/Analyzers. The inspection error levels are set to Warning. The project contains controllers decorated with `[ApiController]` that do not document their responses. I'm not using any [conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-6.0). But the analyzer produces no warnings about the undocumented responses.

It's possible that this has been [broken for years](https://github.com/dotnet/aspnetcore/issues/26341). But I'm opening the issue against the docs because it's possible that the docs omit an essential step for making this work past .NET Core 2.2 or 3.0. There's no sample project to refer to. That should be remedied even if this is a bug in the analyzer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a1e05b-c19d-6933-92fc-4c100340504f
* Version Independent ID: d72414f7-2c53-53a7-1def-428160792a90
* Content: [Use web API analyzers](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/analyzers?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/advanced/analyzers.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/advanced/analyzers.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> for making this work past .NET Core 2.2 or 3.0.

This wasn't introduced until 3.1
Are you using as [ProducesResponseTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.producesresponsetypeattribute) or [ProducesAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.producesattribute) ?

**Comment by kjkrum** [comment]
@Rick-Anderson Neither yet. Hence my expectation of seeing a warning.

**Comment by Rick-Anderson** [comment]
That's required.

**Comment by kjkrum** [comment]
@Rick-Anderson Isn't the entire purpose of this analyzer to emit a warning if you *don't* use those attributes, either explicitly or via a convention?

**Comment by kjkrum** [comment]
@Rick-Anderson And this was *not* introduced in 3.1. There are lots of third-party tutorials about how to use it in 2.2.

**Comment by kjkrum** [comment]
@Rick-Anderson https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.2

**Comment by kjkrum** [comment]
@Rick-Anderson It's a bug in the product. I'll open another ticket.
