### ISSUE TITLE
MVC tutorial for ASP.NET Core - unexpected error in VS when performing the EF Scaffolding step (part 4)

### ISSUE THREAD

**Issue by brobbins** [dotnet/AspNetCore.Docs#26762]
There seems to be an issue with the step in the tutorial that involves the Scaffolding tool.  
I am targeting version ASP.NET Core 3.1, so I installed the version of the "Microsoft.EntityFrameworkCore.SqlServer" NuGet package (in this case v3.1.28) related to the framework I chose.  When I get to the part of using the Scaffolding tool to add the CRUD items, it caused VS 2022 to restart, with no restored/installed changes (after restart, comes back like it was before that step).  When I tried the step again, I got an error dialog about not having the latest version of the EF library (sorry, did not capture).  When I tried a third time, it appears to have worked. 

NOTE: I do see in the Code Generation Log in VS that it does seem to identify the EF version, judging by this statement:

  --**Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'**

This may just be a fluke, but other devs may experience this, so wanted to make your team aware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Why aren't you targeting 6.0?
