### ISSUE TITLE
calculating "MultipartBodyLengthLimit" quota in byte 

### ISSUE THREAD

**Issue by kh-nasser** [dotnet/AspNetCore.Docs#26769]
hello there, in [upload document](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md#multipart-body-length-limit-1) Multipart Body Length Limit is set to 268435456 byte (which is 2 raised to power of 28) and added a comment that it 

>  Set the limit to 256 MB

`services.AddRazorPages(options =>
{
    options.Conventions
        .AddPageApplicationModelConvention("/FileUploadPage",
            model.Filters.Add(
                new RequestFormLimitsAttribute()
                {
                    // Set the limit to 256 MB
                    MultipartBodyLengthLimit = 268435456
                });
});`
, my question is shouldn't value set to 256_000_000 byte instead?
or is there any hidden calculation which I am unaware of it?

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
