### ISSUE TITLE
Outdated version of VS used in the article

### ISSUE THREAD

**Issue by AngelosP** [dotnet/AspNetCore.Docs#26774]
The project creation, the publish and the provisioning all look different in the latest version of VS. Also the version of the ASP.NET template being used is old as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33235](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33235)

**Comment by Rick-Anderson** [comment]
We'll get this updated and ping you if we have questions.

**Comment by wadepickett** [comment]
@Rick-Anderson, since this topic includes Azure, should I **not** keep the previous version in a moniker range?   It looks like for the VS Code version we have of this topic we were just keeping to the latest without maintaining a copy of the old version.  (Working on this issue right now)

**Comment by Rick-Anderson** [comment]
No need to keep old versions of Azure topics.

**Comment by Rick-Anderson** [comment]
2,228 PV/month
