### ISSUE TITLE
IdentityServer4 eol 

### ISSUE THREAD

**Issue by the-programmer** [dotnet/AspNetCore.Docs#26797]
According to the support page identity server 4 seems to be (almost) EOL.

>  IdentityServer4 will be maintained with security updates until November 2022.

Source: https://docs.identityserver.io/en/latest/index.html

To be honest I am not sure if it's just the link and description that are wrong (since, if I recall correctly the scaffolding will result in the identity server from duende software.

But at any rate, I think it would be good to update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33236](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33236)

**Comment by Rick-Anderson** [comment]
Replace with [Duende IdentityServer](https://docs.duendesoftware.com/identityserver/v6)

**Comment by JeremyLikness** [comment]
Hi @Rick-Anderson what's the status of this? And what are the plans for .NET 8? Thanks.
