### ISSUE TITLE
calculating "MultipartBodyLengthLimit" quota in byte

### ISSUE THREAD

**Issue by kh-nasser** [dotnet/AspNetCore.Docs#26795]
hello there, in [upload document](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md#multipart-body-length-limit-1) Multipart Body Length Limit is set to 268435456 byte (which is 2 raised to power of 28) and added a snippet and comment which I am quoted in bellow:

> Set the limit to 256 MB
`services.AddRazorPages(options => { options.Conventions .AddPageApplicationModelConvention("/FileUploadPage", model.Filters.Add( new RequestFormLimitsAttribute() { // Set the limit to 256 MB MultipartBodyLengthLimit = 268435456 }); });`

, **my question is when we want 256 MB body length limit, shouldn't value set to 256_000_000 byte instead?
or is there any hidden calculation which I am unaware of it?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We don't use the IEC **_naming_** under IEEE 1541 ("MiB"), but we do use the **_calculation_** based on powers of two. You'll find this convention throughout the framework and the documentation.

**Comment by kh-nasser** [comment]
Thank you for your response
