### ISSUE TITLE
Kestrel IPC source missing

### ISSUE THREAD

**Issue by mm1nIPOVdDsu** [dotnet/AspNetCore.Docs#26796]
Only the csproj exists in the examples:

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/grpc/interprocess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583bb8dd-b80f-763e-4b84-1b0d2f4e823d
* Version Independent ID: 3d706460-ea6a-59f2-05d7-8a3c9f02e211
* Content: [Inter-process communication with gRPC](https://docs.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/interprocess.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/interprocess.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Could use the full app sample here.  The code snippets are inline to the topic as opposed to in a sample project and pulled in.
