### ISSUE TITLE
.NET 7: Migrate from 6 to 7

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26800]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**

---
[Associated WorkItem - 41139](https://dev.azure.com/msft-skilling/Content/_workitems/edit/41139)

**Comment by Rick-Anderson** [comment]
@tdykstra can you take this?

**Comment by tdykstra** [comment]
What or where are the sources?
