### ISSUE TITLE
Is the article "Localization & Generics" linked in the page still valid?

### ISSUE THREAD

**Issue by programatix** [dotnet/AspNetCore.Docs#26806]
Is the article "Localization & Generics" linked in the page still valid? The link is http://hishambinateya.com/localization-and-generics. It talked about ```UseGenericResources``` property in ```LocalizationOptions```. However, the ```LocalizationOptions``` that come with ```Microsoft.Extensions.Localization (6.0.0.0)``` does not contain that property.

And yes, I'm having issue with localization for generic class, which is the same exact issue reported in https://github.com/dotnet/aspnetcore/issues/3422.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-6.0&viewFallbackFrom=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review

**Comment by programatix** [comment]
The discussion/blog/article at http://www.hishambinateya.com/localization-and-generics is good. It explained what happened and how to "_resolve_" it. However, the issue is, the "_solution_" provided require modification to ASP.NET Core itself. This is not an average developer can do. Furthermore, it would require a fork.

At the very least, it should describe how to actually resolve it by perhaps provide a way to replace ```ResourceManagerStringLocalizerFactory``` with a custom factory.

As far as I can see, https://github.com/dotnet/aspnetcore/issues/3422 was never resolved. The issue the OP was having never resolved by ASP.NET Core itself, nor there was any working implementation which a "normal" developer can use.

**Comment by hishamco** [comment]
Sorry I was totally busy nowadays coz I'm moving to a new house, regarding your concern I'm agree that changing to localization APIs is not a good solution, but you could register your own `LocalizationOptions` class this way no need to change anything

FYI I wrote that at the time of working on localization APIs just to show that you use generic resource

**Comment by hishamco** [comment]
@Rick-Anderson what's the action needed here? we didn't hear anything since two months

**Comment by programatix** [comment]
I would recommend that the article is updated to better explain what should the developer do. For example @hishamco mentioned "you could register your own ```LocalizationOptions``` class". Frankly speaking registering that class on its own does nothing. The actual solution is the modified ```ResourceManagerStringLocalizerFactory```. How do we replace that? It was never mentioned.

**Comment by hishamco** [comment]
> The actual solution is the modified ResourceManagerStringLocalizerFactory.

How `StringLocalizerFactory` will fix the issue?!!

> How do we replace that? It was never mentioned.

You could replace the implementation by creating a new `IStringLocalizerFactory` implementation or subclass the current one, it depends on what you are trying to do

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
