### ISSUE TITLE
"Inspect the Razor C# class generated for a view" obsolete for current versions

### ISSUE THREAD

**Issue by Ducki** [dotnet/AspNetCore.Docs#26804]
The section _"Inspect the Razor C# class generated for a view"_ is obsolete in current versions, since the generated views are not emitted by default anymore. There is no comment about manually enabling the output of the artifacts (e.g. described [in this blog post here](https://andrewlock.net/creating-a-source-generator-part-6-saving-source-generator-output-in-source-control/)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#inspect-the-razor-c-class-generated-for-a-view)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Ducki** [comment]
I actually did already, but somewhere I got lost digging for the exact version, that brought this change. Anyway, PR coming up now :)
