### ISSUE TITLE
Use a flag to prevent multiple concurrent operations  Is it safe?

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/AspNetCore.Docs#26813]
1、![image](https://user-images.githubusercontent.com/39435771/186315383-e4e49bac-89de-46b5-9520-022d83601176.png)
Should I use lock?

2、I have seen owningcomponentbase and understand its usage.

If dbcontext is injected into a service, will owningcomponentbase release the dbcontext inside the dependent service at the end of the component life cycle?

3、
Will “OwningComponentBase<T1,T2,T3,T4...>” be provided, which allows more services to be injected

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EF Core)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-6.0&source=docs)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Ping @JeremyLikness for comment.

**Comment by guardrex** [comment]
Thanks @JeremyLikness ... I'll add that using your language with only minor grammar/style updates.

Thanks @bxjg1987 ... Thanks for asking. Leave this issue open. It will close automatically when the PR merges later.
