### ISSUE TITLE
Route groups

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#26819]
[Route groups](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups)

Probably do this in multiple PR's

- [x] Update this intro tutorial using sample code for a basic scenario
- [ ] sample code for more advanced scenarios
- [ ] Update [Minimal APIs overview](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0) and [What's new in ASP.NET Core 7.0](https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fiyazbinhasan** [comment]
Sure. I would like to do that :)

**Comment by fiyazbinhasan** [comment]
I think @tdykstra already started on this. Do let me know if you need a hand 😺

**Comment by tdykstra** [comment]
Yes I do! The MapGroup sample code I have in the intro tutorial is too basic for the what's new article. For the what's new I need an example that includes code similar to what we have in the [Preview 4 blog post](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups), i.e., code that illustrates what you can do with route groups in more advanced scenarios. This sample would ideally also include code that [returns multiple result types from an endpoint](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#return-multiple-result-types-from-minimal-apis).

**Comment by Rick-Anderson** [comment]
@tdykstra  @fiyazbinhasan  and the sample should go in https://github.com/dotnet/AspNetCore.Docs.Samples

@tdykstra  how much more do you need than what's in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample

**Comment by tdykstra** [comment]
>how much more do you need 

It's not ideal for showing what you can do with routes. The middleware code gets in the way of showing the MapVerb method calls, and it doesn't illustrate this statement, which the blog code does:

>It allows for customizing entire groups of endpoints with a single call to methods like `RequireAuthorization()` and `WithMetadata()`.

**Comment by Rick-Anderson** [comment]
What I should have said is create an issue in https://github.com/dotnet/AspNetCore.Docs.Samples/issues and list what you need with the though that it could borrow much from the [tests sample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample)

**Comment by Rick-Anderson** [comment]
> Since this is mainly to provide snippets for docs, wouldn't it fit better in the docs repo?

If we expect customers to download the code, then it should go in the samples repo. If it's a good sample to download, the samples repo.

**Comment by tdykstra** [comment]
I don't think this needs to be a download-friendly sample--do you think otherwise? If so, can you point me to a doc that displays snippets from code in the samples repo?

**Comment by Rick-Anderson** [comment]
Here's the format 
```
:::code language="csharp" source="~/../AspNetCore.Docs.Samples/signalr/hubs/samples/6.x/SignalRHubsSample/Snippets/Hubs/ChatHub.cs" id="snippet_OnDisconnectedAsync":::

```

**Comment by Rick-Anderson** [comment]
Probably can live in this repo.

**Comment by tdykstra** [comment]
I need a project that I can use for snippets in the overview article sections on MapGroup and returning multiple result types. The snippets need to show what the [Preview 4 blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#route-groups) shows:

* Map the same collection of endpoints using two different groups configured differently (in the blog code, one requires authz, one does not)
* The collection of endpoints is a series of MapGet, MapPost ,etc. statements without extraneous code such as for endpoint filters, i.e., a short method like what is shown as the MapTodosApi method in the Preview 4 blog
* Endpoint handler code for POST uses relative path to support multiple group prefixes, like the CreateTodo method in the Preview 4 blog.
* In the handler methods use TypedResults
* Somewhere outside of the MapTodosApi method, include a MapGet call similar to [the one in the Preview 4 blog that illustrates multiple return types](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#return-multiple-result-types-from-minimal-apis).

The project can be put in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group2 to differentiate it from the existing ...todo-group sample.

**Comment by tdykstra** [comment]
@fiyazbinhasan  Do you still want to write this sample, and if so how soon could you have it ready?

**Comment by fiyazbinhasan** [comment]
Do you need something more than this one? I've two endpoint group here that covers everything.
https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample/WebMinRouteGroup

**Comment by fiyazbinhasan** [comment]
@tdykstra plz check these groups https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/MinApiTestsSample/WebMinRouteGroup/TodoEndpointsV1.cs and 
https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/MinApiTestsSample/WebMinRouteGroup/TodoEndpointsV2.cs

**Comment by tdykstra** [comment]
Those don't provide what I need for snippets, as described in https://github.com/dotnet/AspNetCore.Docs/issues/26819#issuecomment-1262684941 e.g. they have extraneous endpoint filter code.

**Comment by fiyazbinhasan** [comment]
ok. I'll bootstrap a separate project and upload it to this repo. but it would be pretty much same without filters. TodoEndpointV1 and TodoEndpointV2. Are you ok with that?

**Comment by tdykstra** [comment]
See the Preview 4 blog section on route groups and the way it calls the same MapGet etc. endpoint code for setting up each group

**Comment by fiyazbinhasan** [comment]
Isn't this the same thing? 

// todoV1 endpoints
app.MapGroup("/todos/v1")
    .MapTodosApiV1()
    .WithTags("Todo Endpoints");


// todoV2 endpoints
app.MapGroup("/todos/v2")
    .MapTodosApiV2()
    .WithTags("Todo Endpoints");

https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/MinApiTestsSample/WebMinRouteGroup/Program.cs#L24-L32

**Comment by tdykstra** [comment]
That's two distinct MapTodos methods.

**Comment by fiyazbinhasan** [comment]
ok, I'll upload something in a few hours. we will discuss afterwards

**Comment by tdykstra** [comment]
This repo  https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/7.0-samples/todo-group2

**Comment by tdykstra** [comment]
Reopening, as only the code sample was done, still need to get route groups into a doc.
