### ISSUE TITLE
The proxy-load-balancer page is outdated.

### ISSUE THREAD

**Issue by hv0905** [dotnet/AspNetCore.Docs#26824]
In section [Forward the scheme for Linux and non-IIS reverse proxies](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0#forward-the-scheme-for-linux-and-non-iis-reverse-proxies), it said that to use forward header middleware, I have to add and configure it manually.

However, according to [dev blog](https://devblogs.microsoft.com/dotnet/forwarded-headers-middleware-updates-in-net-core-3-0-preview-6/) release in 2019, I can just set `ASPNETCORE_FORWARDEDHEADERS_ENABLED` to `true`, then the framework will automatically enable the middleware and apply some default settings.

I think the document should include this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher please review

**Comment by Tratcher** [comment]
That's correct, but needs a warning. The settings enabled by that flag are designed for cloud environments and they do not enable features such as the KnownProxies option to restrict which IPs  forwarders are accepted from.
