### ISSUE TITLE
Secret manager - link to a production how to document

### ISSUE THREAD

**Issue by chrisleadbeater** [dotnet/AspNetCore.Docs#26826]
>> The Secret Manager tool doesn't encrypt the stored secrets and shouldn't be treated as a trusted store. **It's for development purposes only**. The keys and values are stored in a JSON configuration file in the user profile directory.

This is a good document but I'm wondering how to do this in production?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
In production you would probably use (depending on your way of deployment) [environment variables](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0) or a central key vault (something like [Vault](https://www.hashicorp.com/products/vault) or [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/) to communicate secrets (like database connection strings) to your app.

There are several ways to keep passwords out of your source code – you can find lots of material online about it :)

**Comment by chrisleadbeater** [comment]
Hi Alexander.

I did eventually decide on encrypting/decrypting the connection string password. We are on-premises with Oracle as the database so options are limited and we need the password to be in the application files.

Would have been nice to see at least a mention of various other scenarios, at the high level at least, in this page though.

Thanks for the reply.
Chris

**Comment by Rick-Anderson** [comment]
> we need the password to be in the application files.

Per the first paragraph of the article

`Never store passwords or other sensitive data in source code. `
