### ISSUE TITLE
Title is confusing.

### ISSUE THREAD

**Issue by neumn** [dotnet/AspNetCore.Docs#26839]
Good article, but the title is confusing.
It should be
Enable Cross-Origin Resource Sharing (CORS) in ASP.NET Core

It made me look for a potential subtle difference between Cross-Origin Resource Sharing and Cross-Origin Requests, which there wasn't.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That is the title
