### ISSUE TITLE
big string about 300k , memory increase very high

### ISSUE THREAD

**Issue by renkaifei** [dotnet/AspNetCore.Docs#26837]
string about 300k , 10/ sec。 return using signalr. Memory increase very high.

**Comment by guardrex** [comment]
Hello @renkaifei ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
