### ISSUE TITLE
Please review content for compatibility with .net 6

### ISSUE THREAD

**Issue by rheywood75** [dotnet/AspNetCore.Docs#26843]
I think some of this content need to be reviewed for compatibility with .net 6.  UseWindowsService() was throwing a not supported exception for me.  A couple other posts helped me work around the issue.

https://stackoverflow.com/questions/72932609/net-6-usewindowsservice-throws-exception
https://stackoverflow.com/questions/70571849/host-asp-net-6-in-a-windows-service

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio#app-configuration)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The [included sample](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service/samples/6.x/WebAppServiceSample/Program.cs#L15) doesn't throw.
