### ISSUE TITLE
How do add Reference to the Script files that are required by Nuget Package ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#26848]
I have created Razor Class Library that is using third party Nuget package.
https://github.com/sabitertan/BlazorBarcodeScanner

I now want to consume this library in my MAUIBlazor project.

BlazorBarcodeScanner library requires that I  add the reference to the following script in index.html
```
 <script src="_content/BlazorBarcodeScanner.ZXing.JS/zxingjs.index.min.js"></script>
 <script src="_content/BlazorBarcodeScanner.ZXing.JS/BlazorBarcodeScanner.js"></script>
```

So in my MAU Blazor project(which is consuming Razor class Library), after adding project reference to the Razor Class Library I tried adding the script reference as shown below but it fails with error "BlazorBarcodeScanner not found"

 <script src="_content/RCLLibraryName/zxingjs.index.min.js"></script>
 <script src="_content/RCLLibraryName/BlazorBarcodeScanner.js"></script>

What would be correct way to properly reference libraries of Nuget Package that is being used in Razor Class Library
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2b709f5-e04e-fee3-7eea-1364893ab997
* Version Independent ID: a92c88d3-6ee8-1e69-f4c3-49eb82909746
* Content: [Consume ASP.NET Core Razor components from a Razor class library (RCL)](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/components/class-libraries.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/class-libraries.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nssidhu ... Did you try adding the `_content/BlazorBarcodeScanner.ZXing.JS/...` BlazorBarcodeScanner library script references directly to the MAUI-Blazor project's `index.html` file?

**Comment by nssidhu** [comment]
Yes, that works. Can you update the document that when referencing the Libraries from Nuget package the way to reference is same as we would do when referencing it locally in the project and that article only applies to custom scripts and css in Razor Class Library ?

**Comment by guardrex** [comment]
Yes ... I'm going to cross-link this to my PR over there and leave the email ping on this in my Inbox. I'll also check the Blazor class library topic to make sure that we have coverage in both topics for this scenario. I'll take care of it first thing Monday morning.
