### ISSUE TITLE
dev-cert with custom url

### ISSUE THREAD

**Issue by DianaKoenraadt** [dotnet/AspNetCore.Docs#26859]
# Issue description

I'd like to instruct `dev-certs` that I'm not approaching the application at 'localhost' but at 'develop.mydomain.com'. How can I do this? I've seen hacky solutions online where I have to modify my code depending on whether it's running in Development or Production but I'd rather not make that a concern of my code.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ x] .NET Core 6.0

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic ...

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl

Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
