### ISSUE TITLE
Missing nuget.org

### ISSUE THREAD

**Issue by pmdci** [dotnet/AspNetCore.Docs#26855]
Got stuck in this tutorial because the default nuget.org package source didn't exist. Had to look into here how to manually create it: https://developercommunity.visualstudio.com/t/missing-default-nuget-package-source/1453751

I suggest updating the tutorial with a link to a proper documentation on how to eithe rinitialise or manually create the nuget.org entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What NuGet package doesn't exist?

**Comment by pmdci** [comment]
> What NuGet package doesn't exist?

I said PACKAGE SOURCE, not package. It means the repository buit I am using the exact term Visual Studio UI uses.

The link I provided covers the issue in detail.

**Comment by pmdci** [comment]
@Rick-Anderson Why is this closed if you tagged as "needs-more-info"?

**Comment by Rick-Anderson** [comment]
[Microsoft.EntityFrameworkCore.Design isavailable.](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Design/)

**Comment by pmdci** [comment]
@Rick-Anderson 
Once again: This tutorial is missing steps if a person has never ran NuGet before.

A person might not know how to open the package manager command prompt, and might be unaware of the steps to do to ensure tha tthe NuGuet.org becomes available.

**Comment by Rick-Anderson** [comment]
> Once again: This tutorial is missing steps if a person has never ran NuGet before.

We have several million users who've successfully completed it that would disagree.

**Comment by pmdci** [comment]
@Rick-Anderson And they they all ran this tutorial right after installing VS for the first time, and then came here to tell you that they successfuly completed the tutorial, yes?

**Comment by pmdci** [comment]
> > Once again: This tutorial is missing steps if a person has never ran NuGet before.
> 
> We have several million users who've successfully completed it that would disagree.

@Rick-Anderson "Several million",  do you? And they they all ran this tutorial right after installing VS for the first time, and came here to tell you that they successfuly completed the tutorial, yes? Microsoft's QA at its best.

It is a FACT that in some fresh installs of VS nuget.org might not be available as a source. (Google it) All I did was to point this out, and suggest a paragraph explaining how to enable it in such cases.

Yet you misread the problem and closed it before making the effort to understand it. Then when I try to explain, you responded with laconism, followed hyperbolle and arrogance.
