### ISSUE TITLE
.NET 5.0 SPA showcase uses improper angular command

### ISSUE THREAD

**Issue by Perustaja** [dotnet/AspNetCore.Docs#26864]
The article acts as though both SPA apps have IdentityServer in them. Based on [this page](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#spa) the angular template command is wrong and should go from

```dotnet new angular -o <output_directory_name>``` 
to
```dotnet new angular -o <output_directory_name> -au Individual```

Looks like it is wrong for net3.1 as well and possibly earlier versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-5.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's correct in [the .NET 6 version](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0#create-an-app-with-api-authorization-support).

Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

Just fix V5

99% of customers are looking at V6

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
