### ISSUE TITLE
Update AppAssembly value in examples

### ISSUE THREAD

**Issue by Michael-Ziluck** [dotnet/AspNetCore.Docs#26903]
Project generated by `dotnet new blazorwasm` has the following at the top of the `App.razor` file:
```razor
<Router AppAssembly="@typeof(App).Assembly">
```

The docs on this page have the following however:
```razor
<Router AppAssembly="@typeof(Program).Assembly">
```

Not sure if it should reference `Program.cs` or `App.razor`. There is some disconnect between the naming of files and classes between generated projects and the docs here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Michael-Ziluck ... I'll take a look and get back to you. It might just be some stale content that didn't receive an update when the framework changed.

**Comment by guardrex** [comment]
# **_A ha!_** 👀 

I've found some additional sneaky devils 😈 in the doc set. I'll re-open this issue and fix those up on a second PR shortly.

**Comment by Michael-Ziluck** [comment]
_Blaz_-ingly fast turnaround! Thanks for clarifying and getting those fixed!!
