### ISSUE TITLE
Document usage of problem details in the client app

### ISSUE THREAD

**Issue by glatzert** [dotnet/AspNetCore.Docs#26917]
I was looking for advice, how to use ProblemDetails on the receiver end.
The class itself is defined in Microsoft.AspNetCore.Mvc and is contained in the Http.Abstractions assembly.

Both parts make me wonder, how we'd use ProblemDetails in a client application.
This might be a non issue, but I'd rather not include the aforementioned assembly into a Blazor-WASM project or a desktop application.

Perhaps it would be useful to make some samples using ProblemDetails with generated clients via nswag.
Also the scenario of a shared class for the "http models" would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6504cd-a059-c5d4-73fb-61222ef1c6e0
* Version Independent ID: 1b42352c-a34f-7703-aa3e-d7e3156bd0bd
* Content: [Handle errors in ASP.NET Core web APIs](https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestions, we'll be reviewing this document.
