### ISSUE TITLE
Blazor file uploads example

### ISSUE THREAD

**Issue by hrvoje-grabusic** [dotnet/AspNetCore.Docs#26923]
The example code in Pages/FileUpload2.razor freezes blazor when uploading two files.
[38842](https://github.com/dotnet/aspnetcore/issues/38842)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> Hi all, I took another look through the repro, and that behavior is by design.
>
> Please note per the [Stream.ReadAsync docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=net-6.0):
>
> The result value can be less than the number of bytes allocated in the buffer if that many bytes are not currently available, or it can be 0 (zero) if the end of the stream has been reached.
>
> That's essentially what's happening in this case. When a single call is made to ReadAsync, it only gives you the first (few) chunks that have been sent from JS, you are not guaranteed to receive the full file. Blazor subsequently [throws an error](https://cs.github.com/dotnet/aspnetcore/blob/5adbdcb18ce1167321e919b930d575cbbfb7512c/src/Components/Server/src/Circuits/RemoteJSDataStream.cs?q=Did%20not%20receive%20any%20data%20in%20the%20allotted%20time#L211) as you've only read a part of the stream and the stream subsequently times out.
>
> The way you'd want to achieve this would be by leveraging [Stream.CopyToAsync](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copytoasync?view=net-6.0) or by using Stream.ReadAsync using smaller chunks until you reach the end of the stream. Note this is in line with our [streaming](https://docs.microsoft.com/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0#stream-from-javascript-to-net) and [file upload](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server) guidance. Specific examples and sample code are also available in those docs pages.
> 
> Note in @huseyin-ezemi's https://github.com/dotnet/aspnetcore/issues/38842#issuecomment-1043976343 above, they used ReadAsByteArrayAsync, that could also work as they're allowing the whole stream to be read. Note this may pose some security & scalability concerns as you're storing the whole stream/file in memory. This approach isn't recommended.
>
> ```csharp
> var fileContent = new StreamContent(e.File.OpenReadStream(1024 * 1024 * 15));
> buffer = await fileContent.ReadAsByteArrayAsync();
> ```
>
>The above explains the behavior presented within andrzejczar84's repro app, however in the original issue Liero mentions running into this with CopyToAsync. This is more concerning, however I've been unable to repro. If Liero, angularsen or anyone else has a repro of this issue with CopyToAsync, I'd very much be interested in it. I'm marking this issue as "needs author feedback", it'll get auto-closed after a while if a repro can't be found. Though please feel free to re-open / start a new issue (and link this issue) if you do end up finding a repro with CopyToAsync.

**Comment by guardrex** [comment]
@TanayParikh ... Upon a quick glance 👀 (as I'm off now until Tuesday), it looks like the discussion doesn't apply directly to the approaches and examples laid out in the topic. If you want me to add something, could you re-open this and provide the content? If you don't re-open, I'll assume that what we have is fine.

**Comment by TanayParikh** [comment]
```csharp
                    var fileContent = 
                        new StreamContent(file.OpenReadStream(maxFileSize));

                    fileContent.Headers.ContentType = 
                        new MediaTypeHeaderValue(file.ContentType);

                    files.Add(new() { Name = file.Name });

                    content.Add(
                        content: fileContent,
                        name: "\"files\"",
                        fileName: file.Name);

```

This poses an issue where we're opening the stream for reading (`OpenReadStream`), however not reading till potentially later. I was able to repro https://github.com/dotnet/aspnetcore/issues/38842 by using this component and uploading multiple files (~1.5MB each) simultaneously.

---

Other things;

> The following controller in the web API project saves uploaded files from the client.

Not sure how this is done throughout the rest of the docs (so please ignore if this is standard convention), but maybe we can provide more details about how the controller doesn't go into the `Blazor Server` project, but rather, you have to create a new `webapi` project to use this controller.

> To use the following code, create a Development/unsafe_uploads folder at the root of the web API project for the app running in the Development environment. 

Could we potentially add this folder creation as part of the code snippet. This would ensure the code is "plug and play" (I admittedly didn't read the instructions to create the directory prior to running the `webapi` initially 😄).

**Comment by guardrex** [comment]
Thanks @TanayParikh ... I'll get this squared away on Tuesday morning and ping u on the PR for review.

**Comment by TanayParikh** [comment]
> provide the content

One workaround would be:

```csharp
                    var ms = new MemoryStream();
                    await file.OpenReadStream(maxFileSize).CopyToAsync(ms);
                    ms.Position = 0;
                    
                    var fileContent = new StreamContent(ms);
```

but it requires copying the file into memory. Ideally we'd can pipe it over to `StreamContent` without first saving in memory...

**Comment by TanayParikh** [comment]
> Ideally we pipe it over to `StreamContent` without first saving in memory...

According to https://stackoverflow.com/a/35246905, that's essentially the purpose of `StreamContent`, I wonder what's going wrong then?

**Comment by TanayParikh** [comment]
> I'll get this squared away on Tuesday morning and ping u on the PR for review.

Let's hold off on this, I'm investigating it further...

**Comment by hrvoje-grabusic** [comment]
> Other things;
> 
> > The following controller in the web API project saves uploaded files from the client.
> 
> Not sure how this is done throughout the rest of the docs (so please ignore if this is standard convention), but maybe we can provide more details about how the controller doesn't go into the `Blazor Server` project, but rather, you have to create a new `webapi` project to use this controller.

I was confused by this but i tried it that eaxmple anyway. 
I expected that FileUpload2 example would belong in client side blazor.

Further down in the docs FileUpload3 is what i expected for a server side blazor example and that works fine.

**Comment by guardrex** [comment]
You have to set the hosting model at the top to get the correct content for WASM vs. Server. IIRC, the controllers aren't the same.

![image](https://user-images.githubusercontent.com/1622880/188264877-0538f3a8-ab83-4523-af5d-cf63c49b676b.png)

**Comment by hrvoje-grabusic** [comment]
I was looking at the server hosting model tab.
And i am still confused why anyone would want to upload files via post request like the FileUpload2 example in a server side blazor app.

Tho i opened the issue because that example freezes blazor not because i think it doesn't belong in the docs.

**Comment by guardrex** [comment]
I took another look ... the components are different and the controller is the same.

> why anyone would want to upload files via post request like the FileUpload2 example in a server side blazor app.

The answer is in the opening line ...

> The following example demonstrates uploading files from a Blazor Server app to a backend web API controller in a separate app, possibly on a separate server.

**Comment by hrvoje-grabusic** [comment]
Thanks i missed that somehow.
It does make sense when using a separate storage service.

**Comment by TanayParikh** [comment]
@guardrex the main issue with `OpenReadStream` is a product bug and the docs can be left as-is for now.

Other things from above are still valid.

---

Other things;

> The following controller in the web API project saves uploaded files from the client.

Not sure how this is done throughout the rest of the docs (so please ignore if this is standard convention), but maybe we can provide more details about how the controller doesn't go into the `Blazor Server` project, but rather, you have to create a new `webapi` project to use this controller.

> To use the following code, create a Development/unsafe_uploads folder at the root of the web API project for the app running in the Development environment. 

Could we potentially add this folder creation as part of the code snippet. This would ensure the code is "plug and play" (I admittedly didn't read the instructions to create the directory prior to running the `webapi` initially 😄).

**Comment by guardrex** [comment]
It already states the purpose of the controller in this section in the opening line ...

> The following example demonstrates uploading files from a Blazor Server app to a backend web API controller in a separate app, possibly on a separate server.

On ...

> Could we potentially add this folder creation as part of the code snippet.

:+1: ... I'll use this issue to track the update.
