### ISSUE TITLE
Source assembly for extension methods

### ISSUE THREAD

**Issue by jholovacs** [dotnet/AspNetCore.Docs#26922]
I'm looking at this document where it says to use the extension method `.AddCors` and yet I don't see a single reference to where that extension method is located. I'm making my CORS policy to be common among several WebAPI projects and it should be clear what packages I need to reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jholovacs ... `AddCors` is cross-linked in this doc to the API docs ...

https://docs.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.corsservicecollectionextensions.addcors

... and the assembly is noted there.

Generally, we recommend using the API docs when the assembly isn't clear. We try to link those docs as much as we can, and they always call out the assembly.

**Comment by Rick-Anderson** [comment]
Or right click, go to definition.
