### ISSUE TITLE
Use of 'var' makes these examples difficult to understand.

### ISSUE THREAD

**Issue by GaTechThomas** [dotnet/AspNetCore.Docs#26920]
This page has lots of good info about the things I'm trying to do. However, it's difficult to understand what types are involved when the variables are all defined using 'var' instead of their type names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a7ec3c3-918c-6ffd-1ac0-4f88b89d9295
* Version Independent ID: 1c1f72f1-3d5d-3397-c17d-1889dbae6fee
* Content: [Call gRPC services with the .NET client](https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/client.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/client.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by guardrex** [comment]
Hello @GaTechThomas ... That's a standard convention that we aren't going to change. We call out types in many cases in the article text around the code examples. If you're unsure or want to look something up, use the API docs to determine types ...

https://docs.microsoft.com/dotnet/api/

**Comment by guardrex** [comment]
I just noticed something about this particular doc ... it's sorely lacking in API doc cross-links for API in the text.

@JamesNK ... I have a handful of minutes left this week and can run through and update these API references with API doc cross-links. I'll take care of it.
