### ISSUE TITLE
Necessary using statements not mentioned on forms page

### ISSUE THREAD

**Issue by Michael-Ziluck** [dotnet/AspNetCore.Docs#26939]
To actually use all the Blazor form components, you need to add the following to the `_Imports.razor` file or at the top of each component that uses them:
```razor
@using Microsoft.AspNetCore.Components.Forms;
```

 From what I can see, that is never mentioned which can cause issues with people trying to follow the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3128506-d228-35ca-e34a-183a881acdec
* Version Independent ID: c3128506-d228-35ca-e34a-183a881acdec
* Content: [ASP.NET Core Blazor forms and input components](https://docs.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-and-input-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Michael-Ziluck ... You shouldn't need to add it if the project is based on the project template, which includes it by default. However, it's a good idea to call it out, so I'll add that. Thanks for the suggestion.
