### ISSUE TITLE
IsLockedOut has a different meaning than LockoutEnabled.

### ISSUE THREAD

**Issue by KeesAlderliesten** [dotnet/AspNetCore.Docs#26932]
[Enter feedback here]

`IsLockedOut `has a different meaning than `LockoutEnabled`.
`IsLockedOut `is set if a user had too many failed logins. If `LockoutEnabled `is set then a user **can** be locked out with too many failed attempts (resulting in `LockoutEnd `being set to a date in the future). If `LockoutEnabled `is false then a user is never locked out.

So, migrating `IsLockedOut `to `LockedoutEnabled `makes no sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef1bf52a-1488-eb9b-9961-7843704d2717
* Version Independent ID: 1983fca0-2c10-a835-7a37-e67ad97793a1
* Content: [Migrate from ASP.NET Membership authentication to ASP.NET Core 2.0 Identity](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/membership-to-core-identity?view=aspnetcore-6.0)
* Content Source: [aspnetcore/migration/proper-to-2x/membership-to-core-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/proper-to-2x/membership-to-core-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaacrlevin
* Microsoft Alias: **scaddie**

---
[Associated WorkItem - 61502](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61502)

**Comment by Rick-Anderson** [comment]
@haok please review.

**Comment by HaoK** [comment]
Since I don't believe membership had the ability to toggle this on or off per user.  I think its probably better to just change it to set LockoutEnabled to true as part of this migration

**Comment by Rick-Anderson** [comment]
@KeesAlderliesten Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by KeesAlderliesten** [comment]
I edited the article but I’m not sure I did it correctly, I don’t see my changes anymore…


Kind regards,

Kees Alderliesten

[Beschrijving: Frames Logo 2011 200]

Bourgondischelaan 30e
2983 SH  Ridderkerk
The Netherlands
Tel +31-180-849446
www.frames.nl<http://www.frames.nl/>

Van: Rick Anderson ***@***.***>
Verzonden: vrijdag 30 september 2022 19:50
Aan: dotnet/AspNetCore.Docs ***@***.***>
CC: Kees Alderliesten | Frames automatisering bv ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [dotnet/AspNetCore.Docs] Error in documentation (Issue #26932)


@KeesAlderliesten<https://github.com/KeesAlderliesten> Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

[image]<https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png>

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
> I edited the article but I’m not sure I did it correctly, I don’t see my changes anymore…
Try again, it will offer to make a PR.

**Comment by Rick-Anderson** [comment]
@KeesAlderliesten  can you try again. It will create a new branch for you and a PR.

**Comment by Rick-Anderson** [comment]
@tdykstra  see 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/3605364/215903416-4e2b9bc0-e56f-4481-a41e-4d977f065602.png">

**Comment by tdykstra** [comment]
Sorry, I missed that, reverting assignment.
