### ISSUE TITLE
Test CORS section should include integration test with Test Server rather than testing it via browser.

### ISSUE THREAD

**Issue by marafiq** [dotnet/AspNetCore.Docs#26933]
**Help us make content visible**

- How to unit test CORS

https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0#test-cors

**Describe the new topic**

- It helps verifying the required behavior.

**Comment by Rick-Anderson** [comment]
That would be better. Unfortunately we don't have the resources.

**Comment by marafiq** [comment]
Would u like me to open PR?
