### ISSUE TITLE
UseStatusCodePagesWithReExecute incorrect description

### ISSUE THREAD

**Issue by sbakharev** [dotnet/AspNetCore.Docs#26935]
Hello!

The [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0#usestatuscodepageswithreexecute) article explicilty states:

> The UseStatusCodePagesWithReExecute extension method:
> - **Returns the original status code to the client.**
> - Generates the response body by re-executing the request pipeline using an alternate path.

... and later once again:

> This method is commonly used when the app should:
> - Process the request without redirecting to a different endpoint. For web apps, the client's browser address bar reflects the originally requested endpoint.
> - **Preserve and return the original status code with the response.**

Meanwhile real-life tests show that the status code is not being preserved, only path and query are. We originally thought that this is a bug of StatusCodePagesMiddleware because such behavior is unintuitive. And even though our suspections are confirmed by several articles and posts from previous years (like [this 2017 article](https://andrewlock.net/re-execute-the-middleware-pipeline-with-the-statuscodepages-middleware-to-create-custom-error-pages/) or [this 2018 GitHub comment](https://github.com/dotnet/aspnetcore/issues/3404#issuecomment-411933384)), [this recent _2022_ GitHub issue comment](https://github.com/dotnet/aspnetcore/issues/40518#issuecomment-1061006478) clarifies that status code preservation is not intended, so this is not a bug.

If the current behavior is actually intentional then this part of the article needs to be fixed to not confuse anyone.

But if the behavior described by the article is the correct one and the 2022 commenter has made a mistake (which would have been _good_, because we are now forced to invent workarounds for using ReExecute in combination with StaticFiles just like [this post's author](https://rimdev.io/fixing-aspnet-core-usestatuscodepages-middleware/)) then a bugfix is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 60640](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60640)

**Comment by Rick-Anderson** [comment]
@brunolins16  please review

**Comment by tdykstra** [comment]
@Tratcher is "returns the original status code" incorrect for  UseStatusCodePagesWithReExecute?

**Comment by Tratcher** [comment]
Ah, I see where the confusion comes in.

UseStatusCodePagesWithReExecute does not modify the status code:
https://github.com/dotnet/aspnetcore/blob/ea683686bfac765690cb6e40f6ba7198cae26e65/src/Middleware/Diagnostics/src/StatusCodePage/StatusCodePagesMiddleware.cs#L66-L77

However, the component that is rendering the page on re-execute (like StaticFiles) might overwrite the status code. I'm not sure there's a good way for UseStatusCodePagesWithReExecute to prevent that.

We could improve this by saving the status code on IStatusCodeReExecuteFeature so that it is available in case the response generator overwrites it, like in StaticFile's OnPrepareResponse.
We could also avoid setting default response status codes (200) in static files and mvc.

I'm going to re-open 40518.

**Comment by mdekrey** [comment]
Would you be interested in a PR to adjust the docs for this, considering it looks like the fix is slated for .NET 8?

**Comment by tdykstra** [comment]
Sure, that would be great, thanks.
