### ISSUE TITLE
First paragraph and ControlBase Section have extraneous information.

### ISSUE THREAD

**Issue by kev1010** [dotnet/AspNetCore.Docs#26943]
This page could be more structured and coherent if the first paragraph was reworded and the section "ControllerBase class" was removed. Any information that the user needs to know about the controllerbase class should be defined in xref:Microsoft.AspNetCore.Mvc.ControllerBase; therefore a link is the most efficient way of communicating this.

Here is a suggested rewrite:

```
ASP.NET Core supports creating web APIs using controllers or [using minimal APIs](<xref:tutorials/min-web-api>). This article shows how to use controllers for handling web API requests. Web API *Controllers* are classes derived from <xref:Microsoft.AspNetCore.Mvc.ControllerBase>, but the ApiController attribute provides the functionality we consider unique to Web API.

The web API project template provides a starter controller:

[!code-csharp[](index/samples/6.x/Controllers/WeatherForecastController.cs?name=snippet_ControllerSignature&highlight=3)]


## Attributes
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-6.0#multipartform-data-request-inference)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion, we'll review it on the next doc update.

**Comment by kev1010** [comment]
This is a pretty awful response. You closed the ticket without thought to the issue that was arose. You said that you would bring during the next doc update but that doesn’t make sense since you closed the task. If you don’t want community feedback, stop asking for it and turn the feature off. It’s disrespectful and a waist of our time.

**Comment by kev1010** [comment]
OK, Thank you.
