### ISSUE TITLE
Document how to configure CoreWebView2EnvironmentOptions in Blazor MAUI

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/AspNetCore.Docs#26948]
[EDIT by guardrex to add metadata for the *Overview* topic. We might place this in or just under the existing *Web View configuration* section.]

There are many useful options on `CoreWebView2EnvironmentOptions`, and it's possible to configure them thanks to the PR at https://github.com/dotnet/maui/pull/5802. However the docs don't mention it as far as I can tell.

We don't have to document what the options are or what they do, since that is documented by WebView2. We should just document how to access the `CoreWebView2EnvironmentOptions` object during app startup so you can configure it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0781779e-0e2e-2e6d-53ef-a719ce27fb61
* Version Independent ID: 0781779e-0e2e-2e6d-53ef-a719ce27fb61
* Content: [ASP.NET Core Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by javiercn** [comment]
We have docs for this here https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?source=recommendations&view=net-maui-7.0
