### ISSUE TITLE
can't find the MvcMovie.csproj file

### ISSUE THREAD

**Issue by genti02** [dotnet/AspNetCore.Docs#26959]
I'm trying to find MvcMovie.csproj file.
Also when I run the application it does not show the database.
@Rick-Anderson

**Comment by guardrex** [comment]
Hello @genti02 ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
