### ISSUE TITLE
asp-append-version

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#26951]
Would appreciate a more detailed explanation of asp-append-version.
When I update a JavaScript file (in the wwwroot/JS folder) in a Core MVC application in Visual Studio 2022, VS will still use the previous version. So I have to change the name of the JS file and change it wherever it is referenced. Would asp-append-version take care of this problem automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90104e1-65b1-0007-e56d-0dffef4b1a44
* Version Independent ID: 5c95e5dc-dc10-8658-91fd-1d55d3959c37
* Content: [Script Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You're doing something wrong. That's what `asp-append-version` is for.
What do you mean VS, do you mean Kestrel or IIS Express?

**Comment by xenophilios** [comment]
I have not been using asp-append-version until now. From your answer, it sounds as though it will take care of the problem I mentioned. The problem used to occur when I ran an application in development mode, i.e. on the local server. I think I may have had to deal with it on the remote server too, but I am not sure about that. Now I routinely rename JS files after updating them, which can be quite an inconvenience. Is the issue related to browser caching, or is it a quirk of ASP.NET?

**Comment by Rick-Anderson** [comment]
It's not caching, it breaks caching.  If tag helpers are not enabled, that attribute won't do anything. For example if you're missing  `@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"`

Use the F12 tools to view source and see what's generated.

**Comment by xenophilios** [comment]
Thank you for this clarification. This tag helper will save me a lot of trouble!
