### ISSUE TITLE
Secure Data Tutorial (samples -- final 6)

### ISSUE THREAD

**Issue by oravprojects** [dotnet/AspNetCore.Docs#26967]
This tutorial (https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0#feedback) is impossible to follow. The samples do not have sln files or any files that will run the app. 

Instead of a step by step set of instructions, the explanation keeps referring to other pages (download this, start that, test this), all of which do not have step by step instructions that work. Rather than being straight forward and productive, giving the user a working app that s/he can test and manipulate, this page ends up being a waste of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-6.0#test-the-completed-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> The samples do not have sln files or any files that will run the app.
That's not necessary, just use the project file.
This is an advanced tutorial with plans to eliminate all instructions and just explain the finished code.
