### ISSUE TITLE
Unclear explanations of how to send events to redis for subscribed SignalR Hubs

### ISSUE THREAD

**Issue by douglasg14b** [dotnet/AspNetCore.Docs#26963]
The docs are unclear on the specification of events sent to redis, how they are sent and how they are subscribed to, other than hand-waving it under an implied, (but not explicitly stated) "it just works, only with your Hub instance".

For example, if you have a microservice that *does not* have a SignalR hub, but has received all the information it needs to send a message via SignalR, what is the message specification it needs to employ to send a message to redis in order to trigger a function call from subscribed SignalR hubs? 

It seems unreasonable that every service & instance would need to have a hub instance in order to send messages no? What if these are plain console apps with no Asp.Net references? What if said service isn't even written in C#?

A solution might be to have some sort of "broker" hub that exists just to receive messages from other services in order to publish calls to the redis backplane. But even then that feels hacky, and introduces avoidable complexity.

Example:

![image](https://user-images.githubusercontent.com/1400380/189499749-5efb535d-21dd-4cbe-8bc3-03a632464009.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?source=recommendations&view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
