### ISSUE TITLE
Possibly make a little more clear that the environment is set before Program.cs is invoked?

### ISSUE THREAD

**Issue by taylorchasewhite** [dotnet/AspNetCore.Docs#26971]
This may be superfluous / not something you want to add, and that's okay, but just want to throw my 2 cents in:

In reading this page (which is very well written, thanks), it was somewhat unclear to me _when_ the middleware/code for the .NET Hosted WASM actually is executed to _set up_ the environment. 

Essentially, as a consumer, all I really want to know is:

> Is it safe for me to read from [IWebAssemblyHostEnvironment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.hosting.iwebassemblyhostenvironment) _from_ `Main` (where I do service registration).

When I came across the [Read the Environment](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0#read-the-environment) section I felt more assured that it _will_ be set prior to the Program.cs/Main call since you provide such an example (thanks), but it was still a little unclear. I think this is something folks probably feel since typically Main is the first entry point of any C#/.NET program, but is not the case here since there is javascript setting up/downloading the WASM DLLs (and thus the header that provides the environment).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb8bc6ab-a440-d860-e40c-8f18aa1eafb3
* Version Independent ID: 8a5b47e7-b29c-b049-30e8-5b405a5086b6
* Content: [ASP.NET Core Blazor environments](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-6.0#set-the-environment-via-startup-configuration)
* Content Source: [aspnetcore/blazor/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's called out implicitly as part of the remark at the top of the doc ...

> The client-side Blazor app (Client) of a hosted Blazor WebAssembly solution determines the environment from the Server app of the solution via a middleware that communicates the environment to the browser. The Server app adds a header named Blazor-Environment with the environment as the value of the header. The Client app reads the header.

... so the potential fix here is to extend the last sentence of that to say ...

> The Client app reads the header and sets the environment when the `WebAssemblyHost` is created in `Program.cs` (<xref:Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.CreateDefault%2A?displayProperty=nameWithType>).

**Comment by taylor-white-zocdoc** [comment]
I’d support that change to be explicit as opposed to implicit—when I read the portion you mention, my immediate reaction was “but when!!!!”. Thanks!
