### ISSUE TITLE
Broken anchor

### ISSUE THREAD

**Issue by chrisxfire** [dotnet/AspNetCore.Docs#26978]
[Enter feedback here]

Under the the "Logging output from dotnet run and Visual Studio" section, the "default logging providers" anchor is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#create-filter-rules-in-configuration)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Many of the anchors don't work for old versions. Why are you looking at 3.1?

**Comment by chrisxfire** [comment]
Because I'm maintaining a legacy app and the page indicates it was last updated a week ago.

________________________________
