### ISSUE TITLE
Multithreading in ObjectPool

### ISSUE THREAD

**Issue by michaelclinch** [dotnet/AspNetCore.Docs#26981]
It is not stated clearly in the page, whether `ObjectPool` or `DefaultObjectPool` is thread safe, and issues regarding multi-threading and async/await are not discussed or clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 075aad4c-9e53-92c1-8405-70bd5ed54baa
* Version Independent ID: fa535bff-449d-ac12-ea5b-8a975b0682f6
* Content: [Object reuse with ObjectPool in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/objectpool?view=aspnetcore-3.1)
* Content Source: [aspnetcore/performance/ObjectPool.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/ObjectPool.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@stevejgordon @gfoidl  

> It is not stated clearly in the page, whether `ObjectPool` or `DefaultObjectPool` is thread safe, and issues regarding multi-threading and async/await are not discussed or clarified.

**Comment by gfoidl** [comment]
`DefaultObjectPool` is thread-safe -- as well the use with `async/await`.
`ObjectPool` is an abstract class, the provided implementation (`DefaultObjectPool` and the one specifically for StringBuilder) are thread-safe as well. But we can't state any guarantee for other custom sub-classes (as we don't know their implementation).

Regarding docs: is there a short paragraph like
> ### Thread-safety
> All the static and instance methods on `ObjectPool` and provided sub-classes are thread-safe.

enough?
