### ISSUE TITLE
Part 6, controller methods and views in ASP.NET Core should include a pointer to the recommended way for implementing Edit

### ISSUE THREAD

**Issue by nikosft** [dotnet/AspNetCore.Docs#26982]
[Enter feedback here]
According to [this page](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-6.0#update-the-edit-page) the scaffolder generated page is not the recommended code. Nevetheless, the MVC tutorial ([Part 6, controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-6.0#feedback)) shows only this code. I suggest to add at least a pointer to the recommended code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Part 6, controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is just an introduction. See https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud for optimal code.

**Comment by nikosft** [comment]
@Rick-Anderson We are saying the same thing. In the Introduction there should be something like "The example code below is code generated by the scaffolder, which is not the recommended approach for implementing the Edit method. For the recommended approach see [here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-6.0#feedback)" 

Note, it is not about optimization: the Introduction includes (according to Microsof docs) unrecommended code.
