### ISSUE TITLE
{ASSEMBLY NAME} appears to be optional when working within the same assembly

### ISSUE THREAD

**Issue by contractcooker** [dotnet/AspNetCore.Docs#26980]
The documentation doesn't make clear that {ASSEMBLY NAME} does not need to be specified when working within the same assembly. Perhaps this is common knowledge but it was not immediately clear to me.

dotNetHelper.invokeMethodAsync("MethodName", data); is how we are using it in our codebase.

I believe the documentation would be clearer if some mention were made that {ASSEMBLY NAME} is optional in certain cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, @contractcooker ... Good idea. I'll make that update now.

**Comment by guardrex** [comment]
Actually, I think I see that overload now ...

https://github.com/dotnet/aspnetcore/blob/7efa83061a4ceaf347bdf164c255c2c9af707e39/src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts#L482-L484

**Comment by guardrex** [comment]
> @param assemblyName The short name (without key/version or .dll extension) of the .NET assembly holding the method to invoke. The value may be null when invoking instance methods.

👉 **The value may be null when invoking instance methods.**

**Comment by contractcooker** [comment]
@guardrex thank you very much for your prompt and thoughtful response. I was not expecting such a quick response and concede that in the grand scheme of things this is a minor issue. I understand completely that this may not be the most pressing issue. Again, thank you for taking the time to look at it.

**Comment by guardrex** [comment]
Sure thing. I should be able to address this next week.

This week, there's a huge push to get 7.0 RC1 out ... *and the docs to go with it.* 🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️🏃‍♂️😅

**Comment by guardrex** [comment]
**UPDATE**: *Well! So much for the "next week" plan!* 😄 It's going to take a bit longer. We're working on the .NET 7 guidance. I have a huge JS interop PR in the works, and none of the Blazor migration or *What's New* content has been generated. I'll get back to this as soon as I can, but I'm still not too crazy worried about it, given that what the topic shows isn't wrong ... it's just not fully explained. I now suspect it will take at least another full week or two to reach this ... but possibly even longer than that. The .NET 7 content has a **_hard deadline_** for the framework release in early November and the 🕐 is ticking. 🏃🏃🏃🏃😅

**Comment by guardrex** [comment]
Passing update before getting out on the 🦃 weekend holiday ...

We did get all of the .NET 7 work done, and I cleared out a bunch of issues prior to getting into the weeds with the Blazor *Security* node over the 🦃 to 🎅🎆 period, but I didn't reach this issue in time to resolve it this year. This is still scheduled for work as soon as I can get to it. I hope to resolve this issue in January.
