### ISSUE TITLE
Uses the pre-6.0 hosting model configuration

### ISSUE THREAD

**Issue by MrJohnLocke** [dotnet/AspNetCore.Docs#26997]
[Enter feedback here]
This MVC tutorial uses the Startup.cs and Program.cs classes from the older hosting model (pre-NET6.0) as opposed to the newer minimal hosting model of a single Program.cs class.  I did check with the Razor Pages sister tutorial and it does correctly use the minimal hosting model there.  I thought this one should also be maintained similarly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@MrJohnLocke, thanks for taking the time to point this out.  You are correct, the sample and the topic do need to be updated for 6.x +.

**Comment by wadepickett** [comment]
This issue is a duplicate #13920 and it has been assigned.  So I'll close this one.
