### ISSUE TITLE
Command line examples

### ISSUE THREAD

**Issue by amccool** [dotnet/AspNetCore.Docs#26993]
Looking for more guidance on setting configuration variables using the command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@amccool, thanks for the suggestion.   There is some coverage in this doc on running from the dotnet CLI.  Could you be more specific about where in the doc you were getting stuck and why so we can make sure we address what you ran into?

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0#windows---set-environment-variable-globally

**Comment by amccool** [comment]
specially I was looking for the syntax to set variables from the produced exe,  not `dotnet.exe xxx.dll` or `dotnet.exe run`

for instance
`.\MyWebService.exe --TopLevel:NextLevel="https://xxxx.local/" --Environment Development`

it was difficult to find any reference to setting variables when using the produced exe.  In addition, the `:` syntax was not easy to find examples of.   There seems to be plenty of environment variable usage, just not much for command line.
