### ISSUE TITLE
Good page, my issue wasn't too complex, here are the details for my issue.

### ISSUE THREAD

**Issue by donrolling** [dotnet/AspNetCore.Docs#27000]
I was having a lot of issues with my service. It wouldn't start. This page helped me get to the bottom of it.

I needed this nuget package: Microsoft.Extensions.Hosting.WindowsServices

Set the base path if we're in windows
```
.ConfigureAppConfiguration((context, builder) =>
{
	if (OperatingSystem.IsWindows())
	{
		builder.SetBasePath(AppContext.BaseDirectory);
	}
	var path = "appsettings.json";
	builder.AddJsonFile(path, optional: false, reloadOnChange: true);
})
```
and this UseWindowsService if we're running in windows, that was it!
```
if (OperatingSystem.IsWindows())
{
    hostBuilder.UseWindowsService();
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to container https://github.com/dotnet/AspNetCore.Docs/issues/28041
