### ISSUE TITLE
ServerAuthenticationStateProvider class

### ISSUE THREAD

**Issue by jorgearana** [dotnet/AspNetCore.Docs#27010]
It's interesting that after i readed the page to find answers, now I have to search for this class ServerAuthenticationStateProvider mentioned here, but it doesn't appear anywhere. The solution became a problem with this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, I think you're just saying that without the namespace it isn't clear where this API is located. I'll add a remark to that section calling it out. Thanks for the issue.
