### ISSUE TITLE
InstructorsController.cs throws warning in the Index() function after changes

### ISSUE THREAD

**Issue by kunaldas1997** [dotnet/AspNetCore.Docs#27038]
In the InstructorsController.cs, where the Index() function definition is to be changed, the following warning comes up.

![image](https://user-images.githubusercontent.com/26971428/190870030-605bd557-9498-4acc-8938-7e1d50f88456.png)

**Comment by guardrex** [comment]
btw @kunaldas1997 ... It's best if you open issues using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by kunaldas1997** [comment]
> btw @kunaldas1997 ... It's best if you open issues using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.
> 
> <img alt="Capture" width="404" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

forgot to report from there. Sorry about that.
