### ISSUE TITLE
It would help enormously with seeing the high level structure of a section as large as Fundamentals->Configuration if headings were hierarchically numbered. e.g. "2.3.1 Some Subsection" instead of trying to infer by looking at the styling applied to the (sub)header.

### ISSUE THREAD

**Issue by Sanda35** [dotnet/AspNetCore.Docs#27035]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-gb/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Sanda35 ... Thanks for the note, but we adhere to Microsoft's guidelines, which don't call for an approach like that. You can provide general docs feedback at ...

https://github.com/MicrosoftDocs/feedback/issues

**Comment by guardrex** [comment]
btw tho ... passing note that might be a little bit helpful ... you can at least see the H2 headings in the topic's table of contents sidebar. It used to show the full H2 structure right out in the open, but they collapsed it recently much to my dismay. You now need to click it to show the full H2 structure of the doc.
