### ISSUE TITLE
Areas and _ViewImports.cshtml

### ISSUE THREAD

**Issue by cthompson92** [dotnet/AspNetCore.Docs#27031]
Wanted to ask a question, because I couldn't decipher the answer from the docs page.

Given this project structure:
```
.
+-- Views
|   +-- _ViewImports.cshtml
+-- Areas
|   +-- Area1
|       +-- Views
|           +-- MyView.cshtml
|           +-- _ViewImports.cshtml
```

Would the imports defined in `Views/_ViewImports.cshtml` be applied to `Areas/Area1/Views/MyView.cshtml` ? In other words, is the `_ViewImports.cshtml` file at the root Views folder effectively 'global', or does a `_ViewImports.cshtml` file *need* to be created in each Area if there are imports that you want to make available to _all_ view files in the project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-6.0#area-folder-structure
