### ISSUE TITLE
.NET 7: Update Route Group code

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27047]
Per [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/26549#issuecomment-1250022570)

> @sammychinedu2ky you might want to update your `todo-group` sample since it's not working. Some of the APIs has changed e.g. `AddRouteHandlerFilter` has been renamed to `AddEndpointFilter`

> once you update the sample, that could be used for showcasing the `Route Group` feature in the doc.

cc @sammychinedu2ky 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson I've already made the changes
