### ISSUE TITLE
Is this misleading?

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/AspNetCore.Docs#27055]
In this section : https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#use-key-to-control-the-preservation-of-elements-and-components

> When rendering a list of elements or components and the elements or components subsequently change, Blazor must decide  which of the previous elements or components can be retained and how model objects should map to them. _**Normally, this process is automatic and can be ignored**_, but there are cases where you may want to control the process.

This is misleading as it suggests that Blazor will "get it right" most of the time and that is good enough. The truth is that preservation of elements/components rendered in a list/loop in Blazor is _only guaranteed_ by use of the `@key` directive - as noted further down the page, but only if the reader gets that far.

> Use of [@key](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#key) guarantees the preservation of elements or components based on the key's value.

The reason I am raising this issue is because of the number of times developers are still not using the [@key](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-6.0#key) and posting questions on SO about why they are seeing strange behaviour in loops.

### Suggestion:

Change the wording in that opening section

> When rendering a list of elements or components and the elements or components subsequently change, Blazor must decide  which of the previous elements or components can be retained and how model objects should map to them. Without use of the `@key` directive, this process is automatic based on ordering of the rendered items. However, there are many cases where you may want to control the process.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> This is misleading as it suggests that Blazor will "get it right" most of the time and that is good enough.

That's what the product unit sent for publication. 

I disagree with your sentiment on ...

> only if the reader gets that far

The title of the whole section is "Use @key to control the preservation of elements and components," and the little bit of content (the example) before reaching the remark on `@key` is an example "where you may want to control the process." It even states in the middle, "After demonstrating the poor behavior with the following component, the `@key` directive attribute is used to improve the user's experience." We do require readers to *read the whole section*.

**_However_**, I do agree that the opening paragraph should remark on `@key` in the way that you suggest. That's a great idea here to make sure that the API that's the focus of the section is called out in the first paragraph. I'm going to update it, but probably combine what you suggest with what the product unit provided for publication.

**Comment by SQL-MisterMagoo** [comment]
Luke, 

It would be nice if people read the whole section, but I don't think you can require it, that's why the opening paragraph(s) are so important.

My experience is that people don't read the whole thing - they skim for what they hope to see.

I appreciate your time and am happy for us to disagree on sentiment - anything that makes it clear that guarantees of rendering accuracy only come with action on the reader's part would be great!
