### ISSUE TITLE
Standardize Blazor byte abbreviation conventions

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#27056]
@Rick-Anderson @wadepickett 

I raised this❓a couple of times over the years about removing the confusion on KB, MB, and GB. Devs get confused, for example, knowing if 1 KB is 1,000 bytes or 1,024 bytes. My remarks on this go back as far as the old issue  (*2017!* 👴) ...

**Beefing up my (mis)understandings on contribution guidelines**
https://github.com/dotnet/AspNetCore.Docs/issues/2617

... and that brings up a few fun memories 😄.

The style manual only hints that they want to *avoid embracing the standard* that's been out for like 20 years now 😢 ...

https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/bits-bytes-terms

Technically per IEC and SI, we should be using "KiB" (kibibyte), "MiB" (mebibyte), and "GiB" (gibibyte) to eliminate the confusion ...

https://en.wikipedia.org/wiki/IEEE_1541-2002

Since they won't permit that approach, I've been hardening docs for several years using either of the following techniques ...

* Place the exact number of bytes in parentheses after the mention ... "The default is 32 KB (32,768 bytes)."
* Show the calculated number of bytes ... "The default is 32 KB (32 * 1024)."

I would prefer to standardize on one of those and **not** drop the clarification entirely. I think it makes it sooooo much plainer what we mean ... it's *perfectly clear* in light of avoiding the standard.

I don't think you care if I continue using a technique in Blazor docs, but what do you think about those two approaches? Do you like one better than the other?

**UPDATE**: I'm going to explain that these abbreviations use the non-standard convention in the *Fundamentals* overview and drop my conventions from the individual topics. 

Still tho, I **_wish one day_** 🙏 that MS/.NET foundation would adopt the IEC/SI standard on this. It's silly to me that in 20 years people are still going to be confused by what these docs state.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Version Independent ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Content: [ASP.NET Core Blazor fundamentals](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I prefer `The default is 32 K`. I think most folks know that means 32,768 bytes, but even if they don't, when is it that important? cc @tdykstra

> I don't think you care if I continue using a technique in Blazor docs

Correct.

**Comment by guardrex** [comment]
I suppose another way to go is just for me to briefly remark on this in the Blazor *Fundamentals* overview and go with your suggestion everywhere (i.e., drop my convention). I agree that most devs know what MS means because MS has always taken the non-standards approach.

Still tho ... my recommendation for all companies in this industry is to adopt the IEC/SI standard so that now and in another 20 years people still aren't confused about what these figures mean.

**Comment by Rick-Anderson** [comment]
How about using the KiB notation and make KiB a link to our readme or some other doc that defines it. I don't like Wikipedia links.  Or find a good link like https://web.stanford.edu/class/cs101/bits-gigabytes.html

**Comment by guardrex** [comment]
I don't want to break management's guidance tho. Maybe I'm giving them too much credit, but I think they're preserved their guidance on purpose. What I've been doing isn't going to ruffle any feathers because it adopts their implicit approach and merely clarifies it for our readers. If I go with "KiB"/"MiB"/"GiB", they might *sharpen their beaks and claws* 🦅 for me 😨😄.

I think I've talked myself out of my convention. Tanay just told me that he thinks almost all of the devs out there know what MS means in our docs. You said that independently. I think so ... I think that's right.

I'm going to recast this issue for resolving the Blazor docs on a short bit in the *Fundamentals* overview and just using "KB"/"MB"/"GB" everywhere.
