### ISSUE TITLE
Is this page upto date for net6?

### ISSUE THREAD

**Issue by mikeblakeuk** [dotnet/AspNetCore.Docs#27059]
Is this page upto date for net6?
It talks about "ASP.NET Core 6 introduced WebApplication which removed the need for a Startup class."
but then talks about using the Startup class.

Can someone up date the examples for net6 (or 7) with a net6 style WebApp + Integrataion tests that have their own test config/settings json.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #23543
