### ISSUE TITLE
/api/todoitems/{id}

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#27067]
Great article! Thank you.

Would appreciate the addition of a function to site.js to illustrate capturing data from the object returned by the action method corresponding to the URL "/api/todoitems/{id}".

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment. That's beyond the scope of the article.

**Comment by xenophilios** [comment]
The article on which this article seems to be based includes a function corresponding to the route mentioned. An example of the type requested would be trivial compared to the functions already included in site.js. If it is too much effort for you, perhaps you could supply a link to an explanation.
