### ISSUE TITLE
Kestrel as a Reverse Proxy Supporting HTTP/2

### ISSUE THREAD

**Issue by ChinnPlan** [dotnet/AspNetCore.Docs#27066]
We are looking into use gRPC to connect to our EDMS (M-Files).  Our clients would use the M-Files desktop client to connect to a reverse proxy in the DMZ that would direct requests to the M-Files application server in the internal network.  So far, I have only heard of this working with proxy servers running on Linux (eg. HAProxy, NGINX), because M-Files requires HTTP/2 in this configuration.  I have heard that Application Request Routing using HTTP/2 is not yet supported in IIS.
Is this still true?  Or does using Kestrel provide a suitable way to do this in Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93ed7bfe-e34c-540c-8cd6-92cbca4c301a
* Version Independent ID: c02fcf64-71fc-d05b-8e0a-87e4c0b97030
* Content: [Use HTTP/2 with the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http2?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/http2.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/http2.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
@JamesNK, I don't know the answer to this one.  It does seem like it would be out of scope for this doc.  Thoughts?

**Comment by JamesNK** [comment]
Yes, YARP - built on Kestrel - supports proxying gRPC.

https://microsoft.github.io/reverse-proxy/articles/grpc.html

**Comment by Rick-Anderson** [comment]
See [When to use Kestrel with a reverse proxy](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy?view=aspnetcore-6.0)

I think that's the right place to surface YARP.  @JamesNK  let me know if we should add that YARP link in other places.

**Comment by JamesNK** [comment]
I think what is there today is fine.
