### ISSUE TITLE
Move Min api unit & integration tests sample to https://github.com/dotnet/AspNetCore.Docs.Samples

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27072]
Move the samples from #26801 to https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples

I think many customers will want to download the code, and the AspNetCore.Docs.Samples repo is much smaller and easier to navigate.

@fiyazbinhasan  can you do that? Copy the code over first before delete this version.

**Comment by Rick-Anderson** [comment]
I think [`app.MapGet("/admin", () => "Authorized Endpoint")`](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/7.0-samples/MinApiTestsSample/WebMinRouteGroup/Program.cs#L38-L39) should be removed since we can't test that.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson do you want me to remove the source code from this repo in a separate PR?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson do you want me to remove the source code from this repo in a separate PR?

Yes, 2 PR's. One to move the source, one to delete this source. Really great code.
