### ISSUE TITLE
.NET 7: Update integration tests to .NET 7

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27089]
Create the new sample in https://github.com/dotnet/AspNetCore.Docs.Samples and create a `test\integration-tests` folder.

Address the following issues:

- [ ] #26085
- [ ] #24204
- [ ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jvandertil would you be able to update this test code?

**Comment by jvandertil** [comment]
@Rick-Anderson I'm willing to help out. Could you be a bit more specific what you need? In the past I contributed code focused on the authorized endpoints integration tests.

**Comment by Rick-Anderson** [comment]
Update the [3.x/IntegrationTestsSample](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/test/integration-tests/samples/3.x) to .NET 7 but PR it in the test\integration-tests folder you create in https://github.com/dotnet/AspNetCore.Docs.Samples 

I'm hoping it won't be too much work to update the code from 3.1 to 7.0 RC1.

**Comment by Rick-Anderson** [comment]
@FredCni @martincostello are you interested in updating the code to .NET 7?
