### ISSUE TITLE
Documentation for HTTP headers analyzer

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#27081]
New analyzer in https://github.com/dotnet/aspnetcore/pull/44123

Should have matching docs.

**Comment by Rick-Anderson** [comment]
> IHeaderDictionary has DIM properties for many commonly used headers: [IHeaderDictionary.Keyed.cs](https://github.com/dotnet/aspnetcore/blob/ff2148be7592be83f1f88e2f372ef04f02fdfdb8/src/Http/Http.Features/src/IHeaderDictionary.Keyed.cs)

DIM?

**Comment by JamesNK** [comment]
Default interface implementation

**Comment by JamesNK** [comment]
This is .NET 8 btw

**Comment by tdykstra** [comment]
This was fixed in https://github.com/dotnet/AspNetCore.Docs/pull/27727
It's [ASP0015](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0015?view=aspnetcore-8.0)
