### ISSUE TITLE
Missing AddScoped from refactored MyConfigServiceCollectionExtensions

### ISSUE THREAD

**Issue by AnturGyffrous** [dotnet/AspNetCore.Docs#27095]
In the [Combining service collection](https://learn.microsoft.com/aspnet/core/fundamentals/configuration#combining-service-collection) section of the [Configuration in ASP.NET Core](https://learn.microsoft.com/aspnet/core/fundamentals/configuration) page, the refactored code calls an `AddMyDependencyGroup` extension method that isn't defined in the `MyConfigServiceCollectionExtensions` class.

I think this is an omission, and that the `MyConfigServiceCollectionExtensions` class should have an extension method called `AddMyDependencyGroup` which calls `AddScoped` for the `IMyDependency` and `IMyDependency2` dependencies. E.g.

```diff
using ConfigSample.Options;
using Microsoft.Extensions.Configuration;

namespace Microsoft.Extensions.DependencyInjection
{
    public static class MyConfigServiceCollectionExtensions
    {
        public static IServiceCollection AddConfig(
             this IServiceCollection services, IConfiguration config)
        {
            services.Configure<PositionOptions>(
                config.GetSection(PositionOptions.Position));
            services.Configure<ColorOptions>(
                config.GetSection(ColorOptions.Color));

            return services;
        }

+       public static IServiceCollection AddMyDependencyGroup(
+            this IServiceCollection services)
+       {
+
+           services.AddScoped<IMyDependency, MyDependency>();
+           services.AddScoped<IMyDependency2, MyDependency2>();
+
+           return services;
+       }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by AnturGyffrous** [comment]
I've come accross more examples of this code, e.g. in the [Dependency injection in ASP.NET Core](https://learn.microsoft.com/aspnet/core/fundamentals/dependency-injection) section, am I just misunderstanding some magic? I can't see how `AddMyDependencyGroup` is defined, but the note on the page says "_Each `services.Add{GROUP_NAME}` extension method adds and potentially configures services._", so is there some dynamic magic that knows to add and configure the `MyDependency` interfaces and classes? How is it doing this? How about `MyDependency2`? Maybe I'm missing a piece that connects the dots? I shall read more and inspect the sample code more throughly.

**Comment by AnturGyffrous** [comment]
I think I see, the copy says "_The remaining services are registered in a similar class_", so is it assumed that the reader would need to create this class? That makes sense, and is what I have put together in my code snippet. In my opinion, the docuemtation could be tightened up here.

**Comment by Rick-Anderson** [comment]
@AnturGyffrous  take a look at https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/configuration/index/samples/6.x

Multiple places in the doc say the [sample download](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample)
