### ISSUE TITLE
Reference to app.Services Incorrect

### ISSUE THREAD

**Issue by sykesbPragmatics** [dotnet/AspNetCore.Docs#27099]
Example currently is:
```
    var antiforgery = app.Services.GetRequiredService<IAntiforgery>();

            app.Use((context, next) =>
            {
                var requestPath = context.Request.Path.Value;

                if (string.Equals(requestPath, "/", StringComparison.OrdinalIgnoreCase)
                    || string.Equals(requestPath, "/index.html", StringComparison.OrdinalIgnoreCase))
                {
                    var tokenSet = antiforgery.GetAndStoreTokens(context);
                    context.Response.Cookies.Append("XSRF-TOKEN", tokenSet.RequestToken!,
                        new CookieOptions { HttpOnly = false });
                }

                return next(context);
            });
```

The reference to 
var antiforgery = app.Services.GetRequiredService<IAntiforgery>();
should be:
var antiforgery = app.ApplicationServices.GetRequiredService<IAntiforgery>();

Not sure if/when it was changed but currently under .Net core the IApplicationBuilder interface exposes "ApplicationServices"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
The example uses the ASP.NET 6 version's [WebApplication](https://learn.microsoft.com/en-us/dotnet/api/Microsoft.AspNetCore.Builder.WebApplication?view=aspnetcore-6.0&viewFallbackFrom=net-6.0) (which is what the `app` variable in this case represents). This is the default way in the current version.

**Comment by Rick-Anderson** [comment]
@Ducki  thanks
See https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery/samples/6.x/AntiRequestForgerySample/Program.cs#L26
