### ISSUE TITLE
Incorrect Sample Project

### ISSUE THREAD

**Issue by pmbusa** [dotnet/AspNetCore.Docs#27097]
The corresponding repository has been updated and this tutorial is no longer valid for the specified sample projects

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3653642e-61ef-717b-5436-9bd0a3c4e6f4
* Version Independent ID: 80c1ce51-46fb-0693-525a-7cad37150c7b
* Content: [Docker images for ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/building-net-docker-images?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/docker/building-net-docker-images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/docker/building-net-docker-images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of [these issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=%2280c1ce51-46fb-0693-525a-7cad37150c7b%22++is%3Aopen)
