### ISSUE TITLE
FixedWindowRateLimiterOptions no longer has a constructor

### ISSUE THREAD

**Issue by glennc** [dotnet/AspNetCore.Docs#27098]
The first code sample doesn't work anymore, the types constructor was removed. A working example of the same would probably be something like this:

```csharp
app.UseRateLimiter(new RateLimiterOptions()
    .AddFixedWindowLimiter(
            policyName: "fixed",
            configureOptions: (tokenOptions) => new FixedWindowRateLimiterOptions()
            {
                PermitLimit = 4,
                Window = TimeSpan.FromSeconds(12),
                QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
                QueueLimit = 2
            }));
```

Other samples on the page using that type would also need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Version Independent ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Content: [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0#test7)
* Content Source: [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #27005

**Comment by Rick-Anderson** [comment]
@glennc  updates are live now.
