### ISSUE TITLE
Hot reload doesn't work for razor pages using a functions block

### ISSUE THREAD

**Issue by xt0rted** [dotnet/AspNetCore.Docs#27103]
After a lot of painful debugging I discovered that hot reload, though it works with razor pages, it doesn't work if you're using a single `.cshtml` file with a `@functions` block instead of the code behind style.

This holds true for both `dotnet watch --project ...` and launching from Visual Studio. Your changes will be detected, the console will say `dotnet watch 🔥 Hot reload of changes succeeded.`, and the page will refresh. But your changes will not be relfected on the page until you restart `dotnet watch` or restart the application in Visual Studio.

I haven't seen this documented anywhere, or mentioned in general. I've seen a number of people complaining about hot reload being super spotty and in those instances the projects all seem to be Razor Pages, some of which are using a single file layout.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Version Independent ID: 41ab3e64-1abc-987b-13db-4e49f2d68ff3
* Content: [.NET Hot Reload support for ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0)
* Content Source: [aspnetcore/test/hot-reload.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/hot-reload.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by xt0rted** [comment]
I tried to reproduce this issue in a new project but was unable to, so it looks like there's more to it than I first thought. I'll see if I can get a stable repro and report back as well as open an issue in the sdk repo about it.

**Comment by wadepickett** [comment]
Thanks @xt0rted for the update.  I will close this for now, but feel free to re-open if needed.
