### ISSUE TITLE
IUserRepository definition/explanation missing from example

### ISSUE THREAD

**Issue by awdorrin** [dotnet/AspNetCore.Docs#27104]
The example of UserRepository : IUserRepository does not define/explain the interface IUserRepository.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`IUserRepository` represents the database. For example:

```
public interface IUserRepository
{
    List<User> GetAll();
}
```
See 
* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie/samples/6.x/CookieSample/CookieAuthenticationEvents.cs#L34
* https://stackoverflow.com/questions/29113206/change-injected-object-at-runtime
