### ISSUE TITLE
DotNetObjectReference multiple instances created, only last one disposed

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#27117]
I see in docs you have code that only disposes the last instance of `DotNetObjectReference`
```
@page "/call-dotnet-example-2"
...
    <button @onclick="TriggerDotNetInstanceMethod">
        Trigger .NET instance method
...
@code {
  ...
    public async Task TriggerDotNetInstanceMethod()
    {
        objRef = DotNetObjectReference.Create(this);
        result = await JS.InvokeAsync<string>("sayHello1", objRef);
    }
    public void Dispose()
    {
        objRef?.Dispose();
    }
}
```
You're calling `DotNetObjectReference.Create` on each button click, so `Dispose` will only execute on the last created instance. 
Is that an issue ?

---
also I see here: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.jsinterop.dotnetobjectreference-1?view=aspnetcore-6.0

> the reference must later be disposed by JS code or by .NET code

can you dispose the DotNetObjectReference in JS or it is an error in the doc ?

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27036

### .NET Version

6

**Comment by mkArtakMSFT** [comment]
Closing this as you have it tracked as part of the other linked issue. Thanks @guardrex !
