### ISSUE TITLE
Missing: Yarp

### ISSUE THREAD

**Issue by Otto404** [dotnet/AspNetCore.Docs#27129]
Interesting, but I miss information on how to use YARP

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Otto404 ... We can't cover *every* conceivable reverse proxy scenario. I recommend that if [YARP docs](https://microsoft.github.io/reverse-proxy/articles/getting-started.html) don't address your scenario(s) that you ask them to provide additional guidance in their doc set. Note that we're very compartmentalized ... more so than most people think. We only maintain the ASP.NET Core docs here and rely upon dedicated doc sets from other teams (and 3rd party doc sets for 3rd party API/tools/frameworks) to cover technology integration scenarios.

**Comment by guardrex** [comment]
Actually tho! We don't have a cross-link to their doc set. Re-opening for Rick to assess if that's a good idea.
