### ISSUE TITLE
.NET 7: Add IResults support in MVC docs 

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#27121]
Related issue: https://github.com/dotnet/aspnetcore/issues/40639

***EDIT: @Rick-Anderson***
code complete in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/81
See also #18090

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by brunolins16** [comment]
@Rick-Anderson I will work on it, ok?

**Comment by brunolins16** [comment]
@Rick-Anderson Should I add the sample code in this repo or `AspNetCore.Docs.Samples`?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Should I add the sample code in this repo or `AspNetCore.Docs.Samples`?

Either place. If we expect many customers to download the code, we prefer the samples repo.

**Comment by brunolins16** [comment]
@Rick-Anderson the current sample for this page are here: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/web-api/action-return-types/samples. Do you want, for .NET 7, we have them in the new repo as well?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson the current sample for this page are here: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/web-api/action-return-types/samples. Do you want, for .NET 7, we have them in the new repo as well?

No, let's keep it here. We don't want to duplicate it for sure.

**Comment by brunolins16** [comment]
> **EDIT**: I'd prefer the new sample go in the samples repo

I have the code sample already, and can submit a PR.

**Comment by brunolins16** [comment]
Close by #27157
