### ISSUE TITLE
Hosting in subdirectory not broadly supported.

### ISSUE THREAD

**Issue by lucasmaj** [dotnet/AspNetCore.Docs#27140]
This is particular to 'Calling gRPC services hosted in a sub-directory' solution. 

There was a big surprise for me, and I have a feeling for other implementors as well, that I would hope is mentioned somewhere. While 'SubdirectoryHandler' solves the issue for .net clients, it appears that hosting in subdirectory is generally not supported by other clients: Postman, grpcurl (https://github.com/fullstorydev/grpcurl/issues/318). Id don't know if/how other clients/libraries approach it.  Effectively for universal compatibility, gRPC service has to be deployed under dedicated subdomains. I just wish it was mentioned somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#feedback)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
It's mentioned on this page, in the section you're talking about, that gRPC is a prescribed address format. Do you want it to also say that other gRPC tools won't support this workaround and you should consider finding a way to host gRPC as the root address?

**Comment by lucasmaj** [comment]
Yes, that would have helped. Thank you.

**Comment by Rick-Anderson** [comment]
@lucasmaj  Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by lucasmaj** [comment]
Yes, I can.

**Comment by lucasmaj** [comment]
Pull request created. https://github.com/dotnet/AspNetCore.Docs/pull/27174
