### ISSUE TITLE
Doc HTTP_PORTS, HTTPS_PORTS

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#27156]
https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http_ports-and-https_ports-config-support

https://github.com/dotnet/aspnetcore/pull/44194

HTTP_PORTS=5000;5002
HTTPS_PORTS=5001;5003

This is new shorthand for listing on all IPs on these ports with the given protocol.
URLS=http://*:5000;http://*:5002;https://*:5001;https://*:5003

This is mainly for use with Kestrel, but it could also be used with HttpSys.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
[HTTP.sys web server implementation in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys) so consider using an include used by both docs.
