### ISSUE TITLE
Too much magic, no real details

### ISSUE THREAD

**Issue by Jessica-W** [dotnet/AspNetCore.Docs#27169]
This is just a recipe book that doesn't explain how anything actually works or what to do if you need to change anything. Everything significant is wrapped in extension methods without proper explanations of what they do. I feel like I didn't actually learn anything reading this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your comment. We'll take it under consideration when we have the resources to update this doc.
