### ISSUE TITLE
No mention of ApplicationDiscriminator

### ISSUE THREAD

**Issue by Cybrosys** [dotnet/AspNetCore.Docs#27196]
The page does not mention `ApplicationDiscriminator` and how to set/configure that value. We were unable to get our tokens working across multiple instances unless we gave a consistent value to `ApplicationDiscriminator`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Cybrosys ... When the app name is set, the discriminator is set ...

https://github.com/dotnet/aspnetcore/blob/main/src/DataProtection/DataProtection/src/DataProtectionBuilderExtensions.cs#L39-L52

... but unfortunately, the section on setting the name doesn't connect the idea to earlier remarks in the topic about the discriminator ... **_and_** the lines that speak to the discriminator don't specifically mention the API property (`ApplicationDiscriminator`) and don't cross-link the API doc for it.

* https://learn.microsoft.com/aspnet/core/security/data-protection/configuration/overview#setapplicationname
* https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionoptions.applicationdiscriminator

Rick, here's a cut-'n-paste for that API ...

```
<xref:Microsoft.AspNetCore.DataProtection.DataProtectionOptions.ApplicationDiscriminator?displayProperty=nameWithType>
```

**Comment by Cybrosys** [comment]
Thank you @guardrex!

Just read through the SetApplicationName chapter and forwarded the information internally. What I found was interesting and also confusing, is that it says we should not have to use SetApplicationName as long as the APIs have the same content root path. For us, we have dentical VMs behind a load balancer (shared secrets etc), yet, the only thing that made it work was setting the ApplicationDiscriminator (SetApplicationName).

Either I am not understand the root path or we're somehow doing something that results in it being unique per VM instance.

@Rick-Anderson I feel I am not the right person to update the documentation considering I have barely begun scraping the surface on the topic. As @guardrex pointed out, the important part we missed was the SetApplicationName (which according to the doc we should not have to use...).

**Comment by guardrex** [comment]
That's an absolute path tho, so I think it is unique per VM. I think if you read the value of `ApplicationDiscriminator` without setting it ... read the value on each VM after deployment ... you'll probably see different paths reported by each.

@Rick-Anderson ... I'll do an update on this one in the morning. I'm awaiting feedback on a few Blazor things and have a few minutes to knock it out. I'll ping u for review tomorrow.

**Comment by guardrex** [comment]
A quick one-liner can go like ...

```csharp
app.Logger.LogInformation($"ApplicationDiscriminator: {app.Services.GetRequiredService<IOptions<DataProtectionOptions>>().Value.ApplicationDiscriminator}");
```

... right after the app is built in `Program.cs`.
