### ISSUE TITLE
Break page into multiple pages or provide index in side bar

### ISSUE THREAD

**Issue by PassivePicasso** [dotnet/AspNetCore.Docs#27209]
This page contains a lot of useful information but it is easy to miss where to look for information because this page has become one page to document everything for the minimal api.

Having this page be broken into multiple pages with listings in the sidebar would make this easier in discovery.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs overview](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your suggestion and we're working on that now.

**Comment by matteocontrini** [comment]
Where did the sidebar in documentation pages go? It should've been made sticky and instead it was removed, it makes no sense 😕
