### ISSUE TITLE
no mention of communication between wpf and blazor in your docs

### ISSUE THREAD

**Issue by WirelessMistress** [dotnet/AspNetCore.Docs#27220]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0781779e-0e2e-2e6d-53ef-a719ce27fb61
* Version Independent ID: 0781779e-0e2e-2e6d-53ef-a719ce27fb61
* Content: [ASP.NET Core Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/hybrid/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @WirelessMistress ... I'm not sure what you mean by "communication." The tutorial that shows how to host Razor components in a WPF app is at ...

https://learn.microsoft.com/aspnet/core/blazor/hybrid/tutorials/wpf
