### ISSUE TITLE
Github link to Test Minimal APIs is pointing to invalid URL

### ISSUE THREAD

**Issue by code2mars** [dotnet/AspNetCore.Docs#27233]
GitHub link in Test Minimal APIs section is pointing to invalid URL, upon clicking it's taking to a page that doesn't exist anymore.

I am guessing new link should be https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra  can you fix this?
@code2mars  where is the link? Can you provide a screenshot of copy/paste text around the link?
