### ISSUE TITLE
Issues with Tutorial

### ISSUE THREAD

**Issue by mbowles201** [dotnet/AspNetCore.Docs#27237]
First, there is an additional nuget packet that is required when you get to the database section: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore

Second, the kestrel server limits you to get and post, so the put and delete sections throw 405 errors.  I have tried to implement those actoins in code via CORS and no luck.

Sites recommend removing WebDAV, but it is not installed on my dev box.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3605364/194940876-2f8d4e1a-fa42-4c07-9cfb-a5d2608ef1b0.png">

> Second, the kestrel server limits you to get and post, so the put and delete sections throw 405 errors

That's not correct

**Comment by mbowles201** [comment]
If you would so kindly advise how to get past the 405's with Kestrel, I would appreciate that in lieu of a "that's not correct".
![image](https://user-images.githubusercontent.com/3237002/194971025-2b3362d4-c1f0-40b5-a53b-fa068213d9fe.png)
