### ISSUE TITLE
command aspnet-code-generator not working on mac

### ISSUE THREAD

**Issue by jf-gbg** [dotnet/AspNetCore.Docs#27246]
On my machine the command dotnet-aspnet-codegenerator produces the result zsh: command not found: dotnet-aspnet-codegenerator. However, using dotnet aspnet-codegenerator works fine and produces the results as listed in the tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 63580](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63580)

**Comment by Rick-Anderson** [comment]
I think `dotnet aspnet-codegenerator` is preferred although both should work. Once I get the definitive answer I'll update this doc and others. If you want, you could try

Uninstall with this comand:

`dotnet tool uninstall --global dotnet-aspnet-codegenerator`

Then reinstall with this command:

`dotnet tool install --global dotnet-aspnet-codegenerator`

When you uninstall, It should give you some commands that will help export the path should it not already be in your path for the zsh shell. In other words, it most likely isn't in the zsh path and you need to do an export command script in the shell from the current .dotnet/tools directory.

See [this issue](https://github.com/dotnet/Scaffolding/issues/1404#issuecomment-769432908)

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by jf-gbg** [comment]
No worries. Have created the pr now. Thanks for creatig the tutorial!
