### ISSUE TITLE
Add MAT examples for Blazor Server

### ISSUE THREAD

**Issue by wstaelens** [dotnet/AspNetCore.Docs#27243]
[EDIT by guardrex to add the metadata]

add examples how to use Microsoft MAT in a Blazor Server application:

https://learn.microsoft.com/nl-nl/windows/apps/design/globalizing/use-mat

MAT = Multilingual App Toolkit 

VS2022+ extension download: https://marketplace.visualstudio.com/items?itemName=dts-publisher.mat2022 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @wstaelens ... We don't have the ability or desire to document MAT here. You'll need to rely on their docs, possibly with their product unit and community support, to implement its use. I don't think that there's anything special about using MAT with a Blazor Server app in VS to comment on. If you find anything in particular ... any any *gotchas* 😈, please open an issue for the existing Blazor loc topic using the **This page** feedback button and form from the bottom of that topic.
