### ISSUE TITLE
Tutorial Issue... cannot define  'SaveChangesAsync' nor  'SaveChanges'

### ISSUE THREAD

**Issue by RangoonPost** [dotnet/AspNetCore.Docs#27265]
I explicitly followed the example as written, but again VS complains.   I tried all the recommendations that I can find.  But nothing fixes this.  On my personal machine and many past companies, MANY of these tutorials always encounter an issue or 3.

Three of the 7 Error messages connected with the 'SaveChangesAsync'.  
 - "There is no implicit reference conversion from 'TodoDb' to 'Microsoft.EntityFrameworkCore.DbContext'.	ToDoAPI"
 - CS0311: The type 'TodoDb' cannot be used as type parameter 'TContext' in the generic type or method 'DbContextOptions<TContext>'
 - CS1061:'TodoDb' does not contain a definition for 'SaveChangesAsync' and no accessible extension method 'SaveChangesAsync' accepting a first argument of type 'TodoDb' could be found (are you missing a using directive or an assembly reference?)	ToDoAPI	

[Program_cs.zip](https://github.com/dotnet/AspNetCore.Docs/files/9768323/Program_cs.zip)

**Comment by guardrex** [comment]
Hello @RangoonPost ... Would you mind re-opening this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by RangoonPost** [comment]
![image](https://user-images.githubusercontent.com/4431219/195618800-1ffa3c8c-225a-4b18-8eda-6ed40f1c190c.png)
@guardrex I'm still looking, I havn't found the feedback you are directing me too.  I've looked under the tabs and other links...

**Comment by guardrex** [comment]
It's available via the live (published) doc, not on GH.

**Comment by RangoonPost** [comment]
Done.  Thank you.
