### ISSUE TITLE
RazorPagesMovie Project missed file

### ISSUE THREAD

**Issue by Abduro** [dotnet/AspNetCore.Docs#27272]
\Pages\Shared\_Layout.cshtml file has a reference to RazorPagesMovie.styles.css
but such file does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Abduro ... That's due to CSS isolation, which creates the file at build time ...

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio#css-isolation

**Comment by Abduro** [comment]
Hello Luke
Thank you for the response.
Isolation of CSS looks like something cool and magic.
I removed that reference from the _Layout.cshtml and nothing has changed,
everything looks like before.

It looks very much like that I am married to a woman, which I have never
seen before.
What I mean is -  if I want to style some page specifically I just do it
without any fake or auto generated files.
Anyway, thank you for your explanation.
Regards,Vladimir

**Comment by guardrex** [comment]
You should be able to disable it by adding this to the project file ...

```xml
<PropertyGroup>
  <DisableScopedCssBundling>true</DisableScopedCssBundling>
</PropertyGroup>
```

**Comment by Abduro** [comment]
Everything is clear.
