### ISSUE TITLE
IIS hosting compression and middlware for response compression both enabled clarification.

### ISSUE THREAD

**Issue by malylemire1** [dotnet/AspNetCore.Docs#27287]
It's not clear what happens when both IIS compression and the middleware are enabled. Does IIS hosting disable the middleware? If an app can be hosted on both IIS and Kestrel, is it needed to explicitly disable the middleware by verifying in code if it's currently hosted on IIS? If so the doc should provide an example on how to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response compression in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-6.0)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of https://github.com/dotnet/aspnetcore/issues/3956
cc @guardrex

**Comment by guardrex** [comment]
Was that cross-link for the TH vs. Html Helper issue?

**Comment by Rick-Anderson** [comment]
Oops, copy/paste error, corrected to https://github.com/dotnet/AspNetCore.Docs/issues/2279#issuecomment-1278994354
