### ISSUE TITLE
Where is the documentation for Html Helper?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/AspNetCore.Docs#27290]
This page states "it's important to recognize that Tag Helpers don't replace HTML Helpers and there's not a Tag Helper for each HTML Helper".

However there is no link to any up-to-date information on Html Helpers in this page or anywhere else in the documentation.

Where is the documentation on Html Helpers?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-6.0&source=docs)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @Neutrino-Sunset ... That's the old way ... from ancient times 👴😄.

https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/views/creating-custom-html-helpers-cs#understanding-html-helpers

**Comment by guardrex** [comment]
The idea there is just to tell devs that are thinking about using one that they know about or trying to migrate from them to Tag Helpers when migrating an old app to ASP.NET Core that Tag Helpers are not direct, equivalent replacements.

**Comment by Neutrino-Sunset** [comment]
They're not replacements at all since there are still things you can do in Html helpers that you cannot do in Tag Helpers.

The article that is linked is useless and only serves to confuse as it's from 2009 and gives examples in classic ASP syntax which is completely incompatible with Razor pages.

**Comment by Rick-Anderson** [comment]
Dup of #24246
