### ISSUE TITLE
OpenAPI support in minimal APIs v7 Examples

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#27298]
Hello, first of all thanks for the new `OpenAPI` API 🎉

While going through the docs, I tried out the examples in the docs and bumped against the following issue.

The examples in the v7 docs that are using `WithOpenApi` do not compile.

For example, the snippet at https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0#add-operation-ids-to-openapi-1

```cs
app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync())
    .WithOpenApi(operation => new(operation)
    {
        OperationId = "GetTodos"
    });
```

Give the following error:

```
Constructor 'OpenApiOperation' has 0 parameter(s) but is invoked with 1 argument(s)
```

Screenshot:

![image](https://user-images.githubusercontent.com/28659384/195991916-a394adf2-c66d-40bb-98c1-e4ca39847444.png)

I'm using the latest version (7.0.0-rc.2.22476.2) of Microsoft.AspNetCore.OpenApi, which came with a newly generated project using `dotnet new`.

I suppose this should become the following, if so I'm happy to update the docs 😀

```cs
app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync())
    .WithOpenApi(operation =>
    {
        operation.OperationId = "GetTodos";
        return operation;
    })
```

One small detail: I think the snippet is used for v6 and v7, but it would be great if the snippet contained the correct number - which makes it easier to copy paste 😊

![image](https://user-images.githubusercontent.com/28659384/195991723-762595e6-f62b-4fe4-a570-5f2e3f29d754.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b18acd86-50e3-2316-27be-27156651e5a8
* Version Independent ID: b18acd86-50e3-2316-27be-27156651e5a8
* Content: [How to use OpenAPI with minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
> Give the following error:

Good catch! This is a result of the fact that the API we're leveraging here is support for copy-constructs that was introduced to the `Microsoft.OpenApi` package recently. The update was consumed in https://github.com/dotnet/aspnetcore/pull/44229 which is targeting 7.0 GA, not RC2, so that's why you're getting the issue. Adding the following package reference in your project should do the trick.

```
<PackageReference Include="Microsoft.OpenApi" Version="1.4.3" />
```

I'll add a note that the copy constructors used here ship in that particular version of `Microsoft.OpenApi`.

> One small detail: I think the snippet is used for v6 and v7, but it would be great if the snippet contained the correct number - which makes it easier to copy paste 

Good catch!

**Comment by captainsafia** [comment]
Closing as the doc updates have been merged.

@timdeschryver Feel free to file an issue for anything else you encounter.
