### ISSUE TITLE
Blazor: Mention other state management techniques

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#27297]
The page mentions state management using cascading parameters, state container, injectable services, etc. In my [other issue](https://github.com/dotnet/AspNetCore.Docs/issues/27296) I stated that it should also mention a state container as a cascading parameter.

But there are other techniques too. It would be nice to mention MVVM and Flux. One can't spend more than a few minutes on StackOverflow without running into twenty posts about how awesome they are compared to the basic stuff in this document.

*And, it would be EXTREMELY helpful to mention that the aspnet team does not recommend those unless absolutely necessary.*

I went down a deep rabbit hole with flux because I thought it was what all the cool kids do. What an utter waste of time for general use cases! Mentioning that there are other options, but that they're completely unnecessary, would help many devs from falling into the pit of failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae14b3e3-3271-b919-9e0a-6f317a6b2d2d
* Version Independent ID: e5e1273b-195e-5da1-b4aa-66bbcff1425b
* Content: [ASP.NET Core Blazor state management](https://learn.microsoft.com/en-us/aspnet/core/blazor/state-management?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/state-management.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/state-management.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We can't make a recommendation like that. Microsoft and the .NET foundation wants the community and third-party companies to develop add-on tech for .NET and doesn't have the capacity to even keep up with those efforts, much less actually determine any level of quality. It might also be considered an attempt to suppress competition with anti-competitive conduct to make any such remark ... and the CELA lawyers for the .NET foundation and MS might get very 😡 about that 😄.
