### ISSUE TITLE
Contribute an existing Sample related to invoking an external AuthZ service for further permissions check.

### ISSUE THREAD

**Issue by seekdavidlee** [dotnet/AspNetCore.Docs#27317]
A common use case we see today is the ability for runtime assertation of additional permissions with an external API-based authorization service given some claims provided via Authentication. The aspnetcore security [samples](https://github.com/dotnet/aspnetcore/tree/main/src/Security/samples) do not currently contain such an example. We have already created such an example [here](https://github.com/msft-davidlee/aspnetcore-authz-with-ext-authz-service). 

We have reviewed CONTRIBUTING.md but it appears there is not a specified format to contribute to a sample. Can someone advise on what's the best path to contribute the [sample](https://github.com/msft-davidlee/aspnetcore-authz-with-ext-authz-service) we have created?

***EDIT by @Rick-Anderson***
code at https://github.com/dotnet/AspNetCore.Docs.Samples/pull/104/files

---
[Associated WorkItem - 33266](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33266)

**Comment by Rick-Anderson** [comment]
@seekdavidlee  can you suggest where in [authorization ](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction) this sample should be surfaced?

**Comment by Rick-Anderson** [comment]
@seekdavidlee can you suggest where in [authorization ](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction) this sample should be surfaced?

**Comment by seekdavidlee** [comment]
> @seekdavidlee can you suggest where in [authorization ](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction) this sample should be surfaced?

@Rick-Anderson - Suggested location is [Policy-based authorization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies). The idea is that IAuthorizationHandler provides a place to perform runtime assertation of additional permissions with an external API-based authorization service given some claims provided via Authentication.

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/104
