### ISSUE TITLE
Part 4 of Razor Pages tutorial: Seed the database code issue

### ISSUE THREAD

**Issue by DMack333** [dotnet/AspNetCore.Docs#27318]
The line `using RazorPagesMovie.Data;` in the Visual Studio Code / Visual Studio for Mac version of the code of the "[Seed the database" section](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-6.0&tabs=visual-studio-code#seed-the-database-2) in "Part 4 of tutorial series on Razor Pages" is causing the following problem in VS Code (Mac) for me:

`The type or namespace name 'Data' does not exist in the namespace 'RazorPagesMovie' (are you missing an assembly reference?) [RazorPagesMovie]`

I have verified that I do have a directory named 'Data' on the project root that contains file 'RazorPagesMovieContext'. 

The tutorial up to this point has worked flawlessly. Not sure what I've got wrong here. Please advise. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Part 4, work with a database](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's an excellent error. Compare to the downloaded code.
