### ISSUE TITLE
"Apply Migrations" instructions are incorrect/unhelpful

### ISSUE THREAD

**Issue by danielbrauer** [dotnet/AspNetCore.Docs#27315]
If I understand them correctly, the instructions in [this section](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio#apply-migrations) are not possible to follow. They ask you to create a new user before applying migrations, which I think would run into an error with the database not being set up. Moreover, the instructions don't tell you how to apply migrations, and they don't link to any docs which explain this.

It looks to me as if this should be two separate sections:

- Database setup and applying migrations
- Registering a new user

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook and Google authentication in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The "follow the instructions" bit is **_via the app_**. This is a first-run automatic setup experience. After that, the migrations step is complete, and the guided instructions don't appear again.

**Comment by danielbrauer** [comment]
You're totally right! It was broken because of my unrelated database issue, which I'd incorrectly assumed was migration-related. Sorry for the bother.
