### ISSUE TITLE
Blazor-SignalR configuration updates

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#27320]
Per https://github.com/dotnet/aspnetcore/pull/44623#issuecomment-1283093817

@BrennanConroy ... This wasn't caught on review. The text is right ... the code example is incorrect for the `Blazor.start` piece. 

Reminder: This is for a hosted Blazor WebAssembly with SignalR app. The user needs to extend the server timeout. I was also covering the keep-alive bit, saying to set keep-alive equally on both sides if changed but not recommending a change for merely extending the server timeout, just showing how to change keep-alive for reference.

The SignalR guidance states for the `KeepAliveInterval` server setting ...

> When changing `KeepAliveInterval`, change the `ServerTimeout` or `serverTimeoutInMilliseconds` setting on the client.

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=javascript#configure-server-options

What are we doing about setting `serverTimeoutInMilliseconds`/`keepAliveIntervalInMilliseconds` client-side in `Blazor.start`? The following (in the doc right now) is wrong (Chris and Tanay informed me that `builder` = `HubConnectionBuilder`, not `HubConnection`) ...

```html
<script>
  Blazor.start({
    configureSignalR: function (builder) {
      builder.serverTimeoutInMilliseconds = 30000;
      builder.keepAliveIntervalInMilliseconds = 15000;
    }
});
</script>
```

I considered the following from a PU issue ...

```javascript
Blazor.start({
  configureSignalR: function (builder) {
    let c = builder.build();
    c.serverTimeoutInMilliseconds = 30000;
    c.keepAliveIntervalInMilliseconds = 15000;
    builder.build = () => {
      return c;
    };
  }
});
```

Cross-ref: https://github.com/dotnet/aspnetcore/issues/18840#issuecomment-1182694070

... but that's described as a workaround and looks hackish.

... and configuration of `configureSignalR` doesn't seem to be effective at all for the client of a hosted WASM solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0969556b-b77e-bdb8-8e20-fd6971be0c25
* Version Independent ID: d17e4c28-ea82-0dd8-295d-19f6ada147ea
* Content: [ASP.NET Core Blazor SignalR guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-server-timeout-and-keep-alive-on-the-client)
* Content Source: [aspnetcore/blazor/fundamentals/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
btw @BrennanConroy ... Not directly related to this, but I'm having trouble getting control of client-side logging ***via app settings***.

A minimum level can be set via ...

```csharp
.ConfigureLogging(logging =>
{
    logging.AddProvider(LoggerProvider);
    logging.SetMinimumLevel(LogLevel.Trace);
})
```

... but that's perhaps not ideal to show because I fear devs will forget to turn it off. I'd prefer an `appsettings.Development.json` approach ***client-side*** for this, but I can't get it working. Is there a way to set the hub connection logging client-side via app settings?

**Comment by BrennanConroy** [comment]
> I'd prefer an `appsettings.Development.json` approach _**client-side**_ for this, but I can't get it working. Is there a way to set the hub connection logging client-side via app settings?

Sort of but not really, the whole "development" vs "production" concept is an end-to-end experience we built into VS and Web apps. Console apps (client code) doesn't get an "ASPNETCORE_ENVIRONMENT" variable set when you launch it via VS, and you would need to write some configuration loading to load a json file that you hand create.

The easiest and "best" way I can think of doing it is using `#if DEBUG`
```csharp
#if DEBUG
    logging.AddProvider(LoggerProvider);
    logging.SetMinimumLevel(LogLevel.Trace);
#endif
```

> What are we doing about setting `serverTimeoutInMilliseconds`/`keepAliveIntervalInMilliseconds` client-side in `Blazor.start`?

I don't know how Blazor exposes SignalR objects, suggest talking to blazor folks about if the `HubConnection` is accessible.

**Comment by BrennanConroy** [comment]
> given that environmental settings are supported for Blazor WASM apps

I don't know anything about this 🤷

**Comment by guardrex** [comment]
Normally for logging in WASM, we say to drop the file in the `wwwroot` folder and activate in `Program.cs` with ...

```csharp
builder.Logging.AddConfiguration(builder.Configuration.GetSection("Logging"));
```

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-6.0#logging-configuration

It also works tho without that `Program.cs` line if the app settings file is in the root of the app.

Anyway ... I was just hoping that the normal app settings for development might isolate trace connection logging to that environment. Compiler directives are ok. We do that in a half dozen or so spots for special circumstances.

**Comment by guardrex** [comment]
🤔 ... Perhaps, we could read config for `SetMinimumLevel` ... mmmmmm ... that sounds good.

**Comment by BrennanConroy** [comment]
That can work for the SignalR client too if you have access to `builder.Configuration` when setting up logging for the client.

**Comment by guardrex** [comment]
I'm working on the doc updates to cover this. The workaround code shown above doesn't work, but setting the props on the Hub connection in a component works for the client on both WASM and Server. The following approach for connection building is what what we show in the Blazor-SignalR tutorial. The following values are purely for demo purposes and aren't meant to make sense.

```csharp
protected override async Task OnInitializedAsync()
{
    hubConnection = new HubConnectionBuilder()
        .WithUrl(Navigation.ToAbsoluteUri("/chathub"))
        .Build();

    hubConnection.ServerTimeout = TimeSpan.FromSeconds(61);
    hubConnection.HandshakeTimeout = TimeSpan.FromSeconds(31);
    hubConnection.KeepAliveInterval = TimeSpan.FromSeconds(17);

    Logger.LogInformation($"\n\n\nhubConnection.ServerTimeout: {hubConnection.ServerTimeout}" +
        $"\nhubConnection.HandshakeTimeout: {hubConnection.HandshakeTimeout}" +
        $"\nhubConnection.KeepAliveInterval: {hubConnection.KeepAliveInterval}\n\n");

    hubConnection.On<string, string>( ... );

    await hubConnection.StartAsync();
}
```

Output ...

> hubConnection.ServerTimeout: 00:01:01
> hubConnection.HandshakeTimeout: 00:00:31
> hubConnection.KeepAliveInterval: 00:00:17

The code pitched on the PU issue by a community member for `Blazor.start` is ***ineffective*** for both hosting models AFAICT. I'll angle coverage this way for Blazor Server and hosted WASM for the server (not shown here, but it will be on the PR) and client (shown above). If there's any further discussion on the doc updates, feel free to add remarks to this issue.
