### ISSUE TITLE
Reference shared framework in SignalR docs

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/AspNetCore.Docs#27325]
I think we should cross-ref to https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio from this page or multiple pages in SignalR. I see many questions where people are trying to update their SignalR package in class libraries (since we removed the package in 3.0+ and moved to the shared framework).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-6.0)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---
[Associated WorkItem - 33242](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33242)

**Comment by wadepickett** [comment]
Thanks Brennan.  Got it.
