### ISSUE TITLE
Add to TOC: Middleware in Minimal API apps

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27327]
From #27283 see [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/27283#issuecomment-1278386089)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e126168-04ac-f820-baad-c336729e4da5
* Version Independent ID: 8e126168-04ac-f820-baad-c336729e4da5
* Content: [Middleware with Minimal API applications](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-7.0&branch=pr-en-us-27283)
* Content Source: [aspnetcore/fundamentals/minimal-apis/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @BrennanConroy
* Microsoft Alias: **brecon**

---
[Associated WorkItem - 61499](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61499)

**Comment by tdykstra** [comment]
This was already fixed by #27328
