### ISSUE TITLE
Document IComponent

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#27337]
I couldn't find any documentation about IComponent in the Blazor docs. A user pointed out this missing content in the Blazor eBook: https://github.com/dotnet/docs/issues/31426.

IComponent is the lowest level abstraction for components in Blazor. Typically, you implement Razor components using .razor files, which are based on ComponentBase, but you can build use components based on IComponent instead. It's an advanced scenario, but it should be documented somewhere.

@SteveSandersonMS Thoughts on how you'd like IComponent documented? Could you provide a sketch of the desired content?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The only place that we show `IComponent` is at ...

https://learn.microsoft.com/aspnet/core/blazor/fundamentals/dependency-injection#request-a-service-in-a-component

... where it's used in an `InjectAttribute` example without comment.
