### ISSUE TITLE
IdentityServer 4 alternative

### ISSUE THREAD

**Issue by jsangco** [dotnet/AspNetCore.Docs#27347]
Given than IdentityServer 4 has updated their license and does not officially support ASP.NET 6, is there guidance on how to authenticate users without having to take a dependency on the pay-for services?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Given than IdentityServer 4 has updated their license and does not officially support ASP.NET 6,
Where does it say that?

**Comment by Rick-Anderson** [comment]
https://duendesoftware.com/license/SoftwareLicense.pdf

LICENSE FEES
A. If you wish to use the Software in a production environment, you may download
and use the Software for the Term upon payment of the appropriate license fee
as indicated on the Quote in accordance with the terms and conditions of this
Agreement.
B. If you wish to use the Software in a non-production environment, you may
download and access the source and/or binaries at no charge solely for the
purposes of testing, evaluation, demonstration, trials and training and in accordance
with all license limitations and restrictions set forth in this Agreement.

**Comment by guardrex** [comment]
The community edition license (free for under 1M users, not developing for clients, not redistributing) is at https://duendesoftware.com/products/communityedition.

The most recent PU discussion on adopting and continuing with IdS is at https://github.com/dotnet/aspnetcore/issues/32494.

An earlier similar discussion (3.x era) with a lot of feedback on the paid aspect took place on https://github.com/dotnet/aspnetcore/issues/26489.

Duende IdS is supported for 6.0 (https://www.nuget.org/packages/Duende.IdentityServer#supportedframeworks-body-tab).
