### ISSUE TITLE
How to disable SSL?

### ISSUE THREAD

**Issue by replaysMike** [dotnet/AspNetCore.Docs#27351]
The documentation describes a fair bit about how to integrate Microsoft Identity, IdentityServer, and SPA however it is seemingly impossible to disable HTTPS requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Apps on ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @javiercn
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Disable the middleware ...

```csharp
// app.UseHttpsRedirection();
```

Cross-ref: https://learn.microsoft.com/aspnet/core/security/enforcing-ssl

Because this isn't actionable given the nature of the coverage ... ***security*** 😨 ... I'll close as answered and not actionable for the doc.

**Comment by replaysMike** [comment]
that's simply not enough for an SPA application using IdentityServer / openid.

See my SO question & answer [here](https://stackoverflow.com/questions/74148302/how-to-disable-ssl-requirement-in-asp-net-core-6-identity-spa-react-app/74167894#74167894)

There are many layers each requiring different overrides as none of them understand or respect the `app.UseHttpsRedirection()`.

**Comment by guardrex** [comment]
> They don't provide options to ignore if the HTTPS certificate matches the name

... and you can't use a development certificate with them or a wildcard cert?

**Comment by replaysMike** [comment]
I originally tried that first and requests would still fail, likely they are configured to not accept self-signed certs. Hence going the route of using HTTP instead as they recommend, didn't figure it would be as hard as it turned out to be with IdentityServer & SPA in the mix.

**Comment by guardrex** [comment]
Let's let @Rick-Anderson decide on this, as he calls the shots here ... or ping Barry Dorrans, our PU security guru, to ask what he thinks.

**Comment by Rick-Anderson** [comment]
> seemingly impossible to disable HTTPS requirements.

Wow, that's great. The Security teams has made it clear they only support HTTPS

**Comment by replaysMike** [comment]
yea I mean it's not the worst thing in the world but there should be a good case for allowing simple http only sites. It's just a little hard to configure - or figure out what needs to be configured - for end users atm.
