### ISSUE TITLE
Incorrectly highlighted example code

### ISSUE THREAD

**Issue by replaysMike** [dotnet/AspNetCore.Docs#27359]
The code on `Register.cshtml.cs` is incorrectly highlighted (missing) under `Update the Account/Register.cshtml page`.

The code
```csharp
user.Name = Input.Name;
user.DOB = Input.DOB;
```

should be highlighted to show what was changed from the default sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
Also a screen shot would help to quickly identify the problem.

**Comment by replaysMike** [comment]
Here is the [PR](https://github.com/dotnet/AspNetCore.Docs/pull/27417) to correct the highlighting in section `Update the Account/Register.cshtml page`

**Comment by tdykstra** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/27417
