### ISSUE TITLE
download link unavailable

### ISSUE THREAD

**Issue by mohammadrafiee179** [dotnet/AspNetCore.Docs#27355]
[Enter feedback here]
The download [link](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.10-windows-hosting-bundle-installer) for Windows Hosting Bundle is broken
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?tabs=aspnetcore2x&view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It works here, @mohammadrafiee179.

Paste the link into a browser ...

https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer

... or obtain the Hosting Bundle Installer here ...

https://dotnet.microsoft.com/download/dotnet/6.0

It's on the right, under **ASP.NET Core Runtime 6.0.10**
