### ISSUE TITLE
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore is needed to follow guide

### ISSUE THREAD

**Issue by p1k4x** [dotnet/AspNetCore.Docs#27369]
Using VS 2022 and following instructions but got:

Error	CS1061	'IServiceCollection' does not contain a definition for 'AddDatabaseDeveloperPageExceptionFilter' and no accessible extension method 'AddDatabaseDeveloperPageExceptionFilter' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)

Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore was missing.

Sauce:
https://stackoverflow.com/questions/65007086/services-adddatabasedeveloperpageexceptionfilter-error-code-cs1061

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@p1k4x ... I'm going close this now because my suggestion has visibility for a possible inclusion on an existing PR for this topic. It's best if we avoid self-inflicted 😈 ***merge conflicts*** 😈 where we can. 😄

**Comment by wadepickett** [comment]
fixed with #27353.

**Comment by wadepickett** [comment]
This was important to fix and happened to be already underway for a couple of topics, including this one.  Thanks #p1k4x for taking the time to identify the issue.  Really appreciate your commitment to the community.
