### ISSUE TITLE
Please detail the purpose and nuances of `ValidateIssuerSigningKey`

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/AspNetCore.Docs#27371]
It's unclear to me if `ValidateIssuerSigningKey` impacts JWKS at all, a manually provided key, or a key embedded in the JWT.

There's some ambiguity.

Particularly: If I set `ValidateIssuerSigningKey` to `false`, will the JWT system still perform JWKS validation?

See: https://stackoverflow.com/questions/74195977/does-setting-validateissuersigningkey-to-false-disable-jwks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @atrauzzi ... It doesn't appear to be cross-linked here. The external docs are ...

* API doc: https://learn.microsoft.com/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuersigningkey
* Article: https://learn.microsoft.com/azure/active-directory/develop/scenario-protected-web-api-app-configuration

If it's not clear from those docs, then I'd recommend opening an issue from the bottom of that topic (the 2nd one :point_up:) to ask if they'll enhance their coverage. In your issue for the article, you can reference the API doc, too, asking for additional **Remarks** section content in the API doc if that seems appropriate. This bit of API is for the MS Identity Platform and your question is general, not just for this framework. It seems like that would be the best place to ask for more detailed coverage.

We can leave this open until @mjrousos takes a look to see if my suggestion is sane 😵 or not 😄 and see if anything is actionable for this topic.

**Comment by atrauzzi** [comment]
Excellent, thank you.  Provided I'm interpreting this correctly from your 2nd link:

_"Ensures the application validating the token trusts the key that was used to sign the token. There's a special case where the key is embedded in the token. But this case doesn't usually arise."_

It might be worthwhile to mention in this page as well as the other two pages that this parameter doesn't have anything to do with JWKS.

**Comment by guardrex** [comment]
Very well. I defer to @mjrousos on if/how this is actionable.

Also, I think this API is handled by the product unit here ...

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

You could ask the product unit there in lieu of a docs issue if you feel that the API doc is the right spot for additional remarks. The PU controls the API docs, not the documentation folks, because the remarks are generated from the reference source. It's probably best to go one way or the other and not try to ask simultaneously on both repos.

Mike will know best how to proceed from here. Leave this issue open. I think he'll be along in a bit.

**Comment by guardrex** [comment]
Thanks @mjrousos.

@atrauzzi, take this in that direction. There's a **This page** feedback button and form at the bottom of the API doc. They'll take it from there.
