### ISSUE TITLE
Hook up to TOC

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27379]
@captainsafia  please review the two places where I'll put this article.

<img width="239" alt="image" src="https://user-images.githubusercontent.com/3605364/197899591-ac912eb7-14eb-4ee5-84e7-75a2ac4016b3.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/3605364/197899640-1275ab77-6347-4589-9dcf-a1f5c84bb9d2.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Version Independent ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Content: [Configuring authentication for minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0&branch=pr-en-us-27356)
* Content Source: [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @captainsafia
* Microsoft Alias: **safia**

---
[Associated WorkItem - 33268](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33268)

**Comment by captainsafia** [comment]
@Rick-Anderson I think it's sufficient to just have this under the "minimal APIs" subheading. It doesn't make sense amongst the top-level topics under "Security".

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I think it's sufficient to just have this under the "minimal APIs" subheading. It doesn't make sense amongst the top-level topics under "Security".

But it should be someplace under security because it's a security topic. Maybe under both Authn and AuthZ
<img width="188" alt="image" src="https://user-images.githubusercontent.com/3605364/198392332-34f2c28d-86a3-4a7d-a449-64df682664f3.png">

**Comment by tdykstra** [comment]
>I think it's sufficient to just have this under the "minimal APIs" subheading. 

I agree. We try to avoid having one item in multiple locations in the TOC, as it doesn't work very well. You could add links to this article from articles in the Authn/Authz part of the TOC.
