### ISSUE TITLE
Update simple type definition to include TryParse method

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#27389]
In .NET 7, the `simple type` definition was updated to also based on the existence of a TryParse method (https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#bind-with-tryparse)

So, the following paragraph need to be update to something like:

``` diff
Model binding uses specific definitions for the types it operates on. A simple type is converted from a single string in the input. A complex type is converted from multiple input values. 
- The framework determines the difference based on the existence of a TypeConverter. 
+ The framework determines the difference based on the existence of a TypeConverter or a well-defined TryParse method. 
We recommend you create a type converter if you have a simple string -> SomeType mapping that doesn't require external resources.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfb00531-4ac6-8bf6-9bd8-1eed6446397f
* Version Independent ID: ed418d09-6c33-699a-0d48-9aabc99457be
* Content: [Custom Model Binding in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-7.0#model-binding-review)
* Content Source: [aspnetcore/mvc/advanced/custom-model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/advanced/custom-model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
fixed in #27415
