### ISSUE TITLE
delete VS Add NuGet packages

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27381]
[Add NuGet packages](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio#add-nuget-packages-3) isn't required in .NET 7

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33244](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33244)

**Comment by tdykstra** [comment]
I had to install Microsoft.VisualStudio.Web.CodeGeneration.Design to get scaffolding to work. I'll have to try not installing the other ones.
