### ISSUE TITLE
Runtime razor compilation fails - cannot find HttpContext extension methods

### ISSUE THREAD

**Issue by ghost** [dotnet/AspNetCore.Docs#27390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Razor views fail during runtime compilation when trying to call an extension method of HttpContext within the views.

### Expected Behavior

The razor views should compile at runtime successfully, as they do when runtime compilation is disabled.

### Steps To Reproduce

Create a minimal .NET 6 web app in VS 2022 with Razor pages, enable runtime razor compilation by installing the RuntimeCompilation NuGet package and adding "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" to the launch profiles in launchSettings.json.

In the _Layout.cshtml file, include a call to @Context.GetRouteValue("page") just above @RenderBody.
Run the app. It errors as follows:

'HttpContext' does not contain a definition for 'GetRouteValue' and no accessible extension method 'GetRouteValue' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)

The same error can be recreated by adding a call to @HttpContext.GetRouteValue("page") into Index.cshtml.

Disable runtime compilation by reverting launchSettings.json. Run the app and it works - the calls to GetRouteValue result in the "/Index" URL being displayed.

Why is runtime compilation failing - is it not picking up using statements to allow it to resolve the extension method?

### Exceptions (if any)

'HttpContext' does not contain a definition for 'GetRouteValue' and no accessible extension method 'GetRouteValue' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)

### .NET Version

6.0

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson can you please get this documented? Thanks!

**Comment by kieranbenton** [comment]
Is there any reason why this could not be resolved properly? Its... more than mildly inconvenient and not at all obvious when you add the package in that its not going to work - only some googling later eventually gets you to the documentation change via one of these issues.
