### ISSUE TITLE
"AspNetCore.HealthChecks.SqlServer": "6.0.2" vulnerability package

### ISSUE THREAD

**Issue by yotkoKanchev** [dotnet/AspNetCore.Docs#27410]
ASP.NET Core 6 "AspNetCore.HealthChecks.SqlServer": "6.0.2"  -> "Microsoft.Data.SqlClient": "3.0.1" -> "System.Configuration.ConfigurationManager": "4.7.0" -> "System.Security.Permissions": "4.7.0" -> "System.Windows.Extensions": "4.7.0" referencing vulnerability package "System.Drawing.Common": "4.7.0"

**Comment by guardrex** [comment]
Hello @yotkoKanchev ... Please open that for the product unit. We only work on documentation here.

https://github.com/dotnet/aspnetcore/issues
