### ISSUE TITLE
Complete ### Customize problem details

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27416]
See https://github.com/dotnet/AspNetCore.Docs/pull/27400/files

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0&branch=pr-en-us-27400#problem-details)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by brunolins16** [comment]
@Rick-Anderson I missed that in the mentioned pr. I will updated there. I mean to be a simple overview and link to all options. Thanks.
