### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by davhdavh** [dotnet/AspNetCore.Docs#27411]
https://github.com/dotnet/runtime/pull/61776 says there is Firefox support

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec2f61c7-9f51-6735-e328-3c7b495d70c3
* Version Independent ID: 4d06e565-282d-6387-aa90-cb2c2986d35a
* Content: [Debug ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/debug.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @davhdavh.

@captainsafia ... Shall I schedule rolling in FF as a supported browser. If so ...

* What doc version (ASP.NET Core version) shall we start with for the coverage on this?
* I noticed that we describe `"browser": "{chrome|edge}"` support for `launch.json` (VSC) but not `Properties/launchsettings.json`, but I think it works from launch settings for VS ... is that correct? If so, I'll roll that in. I'll do that regardless of what happens for this issue. Also, I assume that if we're going forward with this that the setting value for FF is `"browser": "firefox"` ... correct?

**Comment by captainsafia** [comment]
@guardrex I'm not doing much work in Blazor these days so not sure if all the necessary work has been done to consume this Firefox support in VS Code/VS/etc.

@mkArtakMSFT @danroth27 for guidance.

**Comment by guardrex** [comment]
Ok, thanks ... sorry, I didn't know.

**Comment by captainsafia** [comment]
> Ok, thanks ... sorry, I didn't know.

No worries! You're welcome to ping on anything minimal APIs/MVC-related though!

**Comment by danroth27** [comment]
Oh wow, I didn't realize we had added Firefox support for Blazor WebAssembly debugging! 😲

@thaystg Can you help out with the questions above? https://github.com/dotnet/AspNetCore.Docs/issues/27411#issuecomment-1293296323

**Comment by thaystg** [comment]
We still need to do some changes on blazor side to make it work, currently it's a little bit hard to use the firefox support on blazor, because Blazor only send the PDB's if it's Chrome or Edge. Maybe we should schedule a meeting if you want to implement the support, or you can wait, it's in my to do list do the changes on Blazor side.

**Comment by guardrex** [comment]
@thaystg ... Is there a PU issue that I can track this on for those updates?

**Comment by guardrex** [comment]
I'm going to track this item via my UE tracking issue. It doesn't sound actionable near-term for docs. In-design framework features are rarely tracked here because they tend to clutter the workload with blocked issues.

Dan, I'll check back with you in 23Q1 on this.
