### ISSUE TITLE
input and label tags reversed

### ISSUE THREAD

**Issue by derekpotts** [dotnet/AspNetCore.Docs#27414]
In the "Update the Areas/Identity/Pages/Account/Manage/Index.cshtml with the following highlighted markup" code block, the input and label tags are reversed for the highlighted lines. Also note that the class names are not reversed. The label tags erroneously have the class name of form-control and the input tags have the class name of form-label. It also seems like form-group should be form-floating, to match the neighboring divs.

For example,
```
            <div class="form-group">
                <label asp-for="Input.Name" class="form-control"></label>
                <input asp-for="Input.Name" class="form-label" />
            </div>
```
should be
```
            <div class="form-floating">
                <input asp-for="Input.Name" class="form-control" />
                <label asp-for="Input.Name" class="form-label"></label>
            </div>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by postmeback** [comment]
Hi,

When i tried to rectify the document, I found the below screenshot

![image](https://github.com/dotnet/AspNetCore.Docs/assets/14862687/0e064447-61c4-47fe-81ad-9c38f50cc5cf)


Need someone's guidance to fix this issue

**Comment by postmeback** [comment]
https://github.com/dotnet/AspNetCore.Docs/pull/29441

**Comment by derekpotts** [comment]
The issue isn't fixed by #29441. It needs fixed in aspnetcore/security/authentication/add-user-data/samples/6.x/SampleApp/Areas/Identity/Pages/Account/Manage/Index.cshtml.

**Comment by postmeback** [comment]
Hi @derekpotts , would you like to show the error using a screenshot or maybe create a new PR to fix

**Comment by Rick-Anderson** [comment]
@postmeback you changed the 3.x version. aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Pages/Item.cshtml
https://github.com/dotnet/AspNetCore.Docs/pull/29441/files

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests/samples/3.x/HttpRequestsSample/Pages/Item.cshtml


Can you change the 6.x version in https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data/samples/6.x/SampleApp/Areas/Identity/Pages/Account/Manage/Index.cshtml

**Comment by postmeback** [comment]
Sure, I will.

**Comment by postmeback** [comment]
https://github.com/dotnet/AspNetCore.Docs/pull/29495/

**Comment by postmeback** [comment]
This can be also closed.
