### ISSUE TITLE
Add HTTP/2 WebSockets to What's New in 7

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#27442]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#http2-websockets-support

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33269](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33269)

**Comment by Rick-Anderson** [comment]
@wadepickett  looks like you forgot to update WN in #26768

**Comment by wadepickett** [comment]
@Rick-Anderson,  You are right!  I updated the doc but forgot to add the mention  and link in the What's New as I moved to another 7.0x doc issue.  I'll get it in...
