### ISSUE TITLE
Blazor WebAssembly Not Support Firefox 52

### ISSUE THREAD

**Issue by SajadAbbasi** [dotnet/AspNetCore.Docs#27457]
Hi 
Are You Support Blazor WebAssembly In Mozilla 62v ?

aspnet core
Blazor WebAssembly 5v
@guardrex

thanks

**Comment by guardrex** [comment]
Probably not ... that's very old. The product unit favors support for the latest versions per our guidance in ...

https://learn.microsoft.com/aspnet/core/blazor/supported-platforms
