### ISSUE TITLE
How to reduce the verbosity of logging (it takes 6 lines to see 4 properties of a single request)

### ISSUE THREAD

**Issue by PandaWood** [dotnet/AspNetCore.Docs#27471]
I just wanted to raise a topic on how to reduce the extreme verbosity of this logging
I only want to see method/path/query and statuscode, I'm able to do that with the config below but the output (further below) is inappropriate for me. I want only a single line of logging to see 4 simple properties, not 6 lines.

```
	services.AddHttpLogging(logging =>
			{
				logging.LoggingFields =
					HttpLoggingFields.RequestMethod |
					HttpLoggingFields.RequestPath |
					HttpLoggingFields.RequestQuery |
					HttpLoggingFields.ResponseStatusCode;
			});
```

I would like to see a single line of log output to see 4 simple properties - but instead I get 6 ->

```
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[1]
      Request:
      Method: GET
      PathBase:
      Path: /test/bookings/0af30924-7b1e-4d1b-bb3d-1e59d5e44346
      QueryString:
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c772b2a-5d37-84af-624c-9022efe0758b
* Version Independent ID: b39594cc-9d1c-611c-e3e7-8755d74253a6
* Content: [HTTP Logging in .NET Core and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @jkotalik
* Microsoft Alias: **jukotali**

**Comment by guardrex** [comment]
Hello @PandaWood ... The built-in logger has no facility to allow you to change that. You can open a feedback issue with the product unit to see if they would be interested in adding features to control the format of the output ...

https://github.com/dotnet/aspnetcore/issues
