### ISSUE TITLE
error in generating url for asp-route-page

### ISSUE THREAD

**Issue by kh-nasser** [dotnet/AspNetCore.Docs#27474]
Hi there, 
it seems there is a problem with "page" as query id, since asp-route-page did not generate desired href.
im leaving my code in bellow
`<a asp-route-page="@pageIndex" class="active tm-paging-link">@i</a>
`
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> since asp-route-page did not generate desired href.

What did it generate?

**Comment by kh-nasser** [comment]
nothing, href was a empty string as `<a class="tm-paging-link" href="">2</a>`

**Comment by kh-nasser** [comment]
I used as ` <a asp-route-pages="@pageIndex" class="active tm-paging-link">@i</a>` and everything was ok , it seems we plain "page" is not ok to use

**Comment by guardrex** [comment]
That's reserved ...

https://learn.microsoft.com/aspnet/core/mvc/views/razor#razor-reserved-keywords
