### ISSUE TITLE
An example is wrong?

### ISSUE THREAD

**Issue by AntonC9018** [dotnet/AspNetCore.Docs#27486]
The example in the "Ambient values and explicit values" section
```csharp
var subscribePath = _linkGenerator.GetPathByAction(
    "Subscribe", null!, new { id = 17 })!;
```
will just fail, it throws on null.
Even in general, using null forgiving on null is cursed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#ambient-values-and-explicit-values)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 33273](https://dev.azure.com/msft-skilling/Content/_workitems/edit/33273)

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
