### ISSUE TITLE
View Components

### ISSUE THREAD

**Issue by xenophilios** [dotnet/AspNetCore.Docs#27499]
Would appreciate some guidance on whether any of the techniques described in this article can be adapted for asynchronously updating view components and, if so, how. Thank you for your trouble.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c31071a6-97f2-d0ae-22a7-10e461a3c679
* Version Independent ID: d3227595-fe2a-7630-0379-8da3b1dba2ee
* Content: [Tutorial: Call an ASP.NET Core web API with JavaScript](https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-javascript?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/web-api-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/web-api-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is about calling Web APIs from JavaScript. The Web APIs can be async
