### ISSUE TITLE
The Changes should be also highlighted this first query

### ISSUE THREAD

**Issue by honeybadger007** [dotnet/AspNetCore.Docs#27507]
viewModel.Instructors = await _context.Instructors
                  .Include(i => i.OfficeAssignment)
                  .Include(i => i.CourseAssignments)
                    .ThenInclude(i => i.Course)
                        .ThenInclude(i => i.Department)
                  .OrderBy(i => i.LastName)
                  .ToListAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-3.1)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting. That will get fixed under #26505
