### ISSUE TITLE
No documentaion on the templated default Blazor layout

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/AspNetCore.Docs#27515]
There's no documentation as to the default Blazor layout itself, i.e. the MainLayout.razor and its accompanying css. In fact, the documentation doesn't even mention that this default layout uses flex layout, not the grid style.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 251fbc5f-ce3e-4036-ba2b-f641d7de4e27
* Version Independent ID: 58e0022a-ac6c-9bf8-380a-40b7d068a887
* Content: [ASP.NET Core Blazor layouts](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/layouts?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/components/layouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nicholasyin ... Part of that I don't follow, as it's described at ...

https://learn.microsoft.com/aspnet/core/blazor/components/layouts#mainlayout-component

... and the file is listed/defined in the *Project Structure* topic at ...

https://learn.microsoft.com/aspnet/core/blazor/project-structure

As for ....

> doesn't even mention that this default layout uses flex layout, not the grid style

Thus far ...

* The stylesheet is [cross-linked in the reference source](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Shared/MainLayout.razor.css).
* Upon inspection of the file, it's immediately evident that flex is in use. 

However ...

* Flex has always been used for both hosting models going all the way back to 3.1, so there's no problem to mention it in passing.
* There are slight differences in the Blazor Server and Blazor WebAssembly stylesheets, and the text only cross-links the Blazor WebAssembly file. I'd like to link both there.
* I spotted one small change to `MainLayout.razor` that doesn't appear in the file example of the *Layouts* article: The `main` element is used now over a `<div>` with a `main` class. I addressed that change for most of the in-text examples, but I don't see it updated in the 6.0/7.0 snippet sample apps in the [`dotnet/blazor-samples`](https://github.com/dotnet/blazor-samples/) GH repo, and I spotted a couple of more *sneaky gremlins* 😈 to update in the articles.

Thanks for the issue ... I'll fix up those aspects right now.

**Comment by nicholasyin** [comment]
Some readers of the Blazor documentation, such as me, are mostly backend developers, with less or little experience of frontend programming. So, I hope there could be a little more frontend information/background knowledge there for backend developers, maybe some external resource links.

**Comment by guardrex** [comment]
Blazor docs build on the main ASP.NET Core doc set. They don't cover general front-end programming concepts. It's more like an ***add-on node*** of docs that extend and enhance the main docs. For anything specific that applies to Blazor, such as what you're asking about on this issue, we need a specific request.

**Comment by nicholasyin** [comment]
Yep, I think mentioning that the default layout utilizes flexbox instead of grid, and if users accustomed to grid style could rewrite the index.html or the main layout if they want to keep it, would be helpful.
