### ISSUE TITLE
Prerendering url key wrong

### ISSUE THREAD

**Issue by OnSive** [dotnet/AspNetCore.Docs#27530]
The prerendering header link should be `https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-3.1#prerendering` but is actually `https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-3.1#prerendering-2`.

The linking on the page does not work with the `prerendering-2` like in 
```
For Blazor apps with prerendering enabled, calling into JS isn't possible during prerendering. For more information, see the [Prerendering](#prerendering) section.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7ea38a-649b-303d-bebf-c701e216ba25
* Version Independent ID: 9e197a8b-2616-8363-0a15-38cac802e82e
* Content: [Call JavaScript functions from .NET methods in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-3.1#prerendering)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @OnSive ... This is a known issue with our current documentation versioning system. There is a long-range plan in place to covert over to a new versioning of doc content that will fix this link, but I don't have an exact ETA on when it will be implemented.
