### ISSUE TITLE
not in toc

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27545]
@tdykstra 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
It is in the toc.
![image](https://user-images.githubusercontent.com/1569635/200677208-d7728c26-9e75-4c2a-9f1f-e72b8d932e91.png)

**Comment by Rick-Anderson** [comment]
Arg, I couldn't see it on my mobile.
