### ISSUE TITLE
DotNet.createJSObjectReference for calls originating from JS

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#27552]
Per https://github.com/dotnet/aspnetcore/issues/26049.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@JinShil ... I'm working on adding `DotNet.createJSObjectReference(jsObject)` and `DotNet.createJSStreamReference(streamReference)` to the *Call .NET* article. I like your example as a potential example to show in the article. However, I'm not sure about something you're doing. For .......

```csharp
[JSInvokable]
public void OnClick(IJSObjectReference jsReference)
{
    Console.WriteLine("Clicked");
}
```

What were you going to do with the event (`e`) marshalled as an `IJSObjectReference` in there?

If I use your example, I think the code should do something meaningful with it, but I'm not sure what to do there. What were you going to do with it?

I thought that in this case ... a `click` event ... that it might marshall into a `MouseEventArgs` as ...

```csharp
[JSInvokable]
public void OnClick(MouseEventArgs args)
{
    Console.WriteLine($"Mouse coordinates: {args.ScreenX}:{args.ScreenY}");
}
```

It doesn't throw, but it doesn't report event arguments either ... `Mouse coordinates: 0:0` is the result.

**Comment by JinShil** [comment]
It's been a long time since I submitted this bug, but if I remember correctly, I needed to conditionally call `e.preventDefault()` according to some logic in the C# `OnClick` method.  Currently, and certainly at the time I submitted the bug, Blazor did not have a way to call `e.preventDefault()` and `e.stopPropagation()` conditionally without writing the logic in Javascript.

**Comment by guardrex** [comment]
I see. Thanks for letting me know.

As you can see on the PU issue, Steve has given me a quick example to show to cover it. I won't place a full-blown example into the doc after all.

**Comment by JinShil** [comment]
I think a more prudent example would be to use the javascript keyboard events (e.g. `keydown`, `keyup`) and conditionally call `e.preventDefault()` based on which key was pressed.
