### ISSUE TITLE
JSImport: Not enough information regarding interop for non-module code

### ISSUE THREAD

**Issue by yugabe** [dotnet/AspNetCore.Docs#27554]
The page doesn't mention the `[JSImport]` overload that only takes a single `string functionName` argument (without the `string moduleName` second parameter):

![image](https://user-images.githubusercontent.com/14803737/200842992-f176b86b-628d-42b2-98a5-c4ad195fa247.png)

This implies there is an alternate way to reference functions, but the page makes no mention of this. The API/source isn't clear either:
![image](https://user-images.githubusercontent.com/14803737/200844301-dc267b91-a61f-419c-827e-5235004d34f5.png)
![image](https://user-images.githubusercontent.com/14803737/200844338-6315dad7-d8d2-4097-b9b6-fe26f2c89180.png)

As the alternative `IJSRuntime`-based JS interop takes objects that reside on the global object, it is not straighforward to migrate to the new `JSImport`-based solution. This can be increasingly troublesome, because bundling the resulting application code in a JavaScript bundle might not support exporting the bundle as an EcmaScript module ([webpack support is only experimental](https://github.com/webpack/webpack/issues/2933)). Bundling (with minification, optimizations etc.) is still considered by many a superior solution than loading individual (small) module files over network and can simplify deployment or caching of resources.

The questions unclear are: 
- Is there a way to refer to already loaded objects/functions instead of loading different modules?
- How to use the `[JSImport(string functionName)]` overload of the attribute?

I haven't found an easy way to invoke non-module members with `JSImport`, but if it is an intentional design choice, there is a simple hack to work around that:
```js
const w = window;
export { w as window };
```

I'd rather the API supported the window/global object by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aab92a0-c05f-ef01-fb74-a0bf525aae69
* Version Independent ID: 8aab92a0-c05f-ef01-fb74-a0bf525aae69
* Content: [JavaScript JSImport/JSExport interop with ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/import-export-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/import-export-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @yugabe ... Let's ping @pavelsavara for comment on this.

**Comment by pavelsavara** [comment]
- module name on `JSImport` is just a name. It doesn't have to be JS file. You could use `setModuleImports` to set the exports of virtual "module" and bind it to any function, even things on `globalThis`. [Example](https://github.com/dotnet/runtime/blob/feb9968ad754c7116178fdc3216dc12977bebbf0/src/mono/sample/wasm/browser/main.js#L15)
- You can pass `globalThis` prefix to `[JSImport("globalThis.console.log")]` [Example](https://github.com/dotnet/runtime/blob/feb9968ad754c7116178fdc3216dc12977bebbf0/src/libraries/System.Runtime.InteropServices.JavaScript/tests/System.Runtime.InteropServices.JavaScript.UnitTests/System/Runtime/InteropServices/JavaScript/JavaScriptTestHelper.cs#L20)

**Comment by yugabe** [comment]
Thanks @pavelsavara, I'll take a look. I tried prefixing with "window", but it didn't work (didn't log an error either, but it's probably an issue elsewhere in my code base). This is enough for me to go on.

This could maybe worth mentioning in the docs, especially as it seems this is just undocumented, but there are test cases that support it is working. @guardrex?

**Comment by guardrex** [comment]
I'll take look, but it will probably be tomorrow/Friday due to on-going .NET 7 docs work.

**Comment by pavelsavara** [comment]
> didn't log an error either

It could not fail on compile time when the attribute is processed, because we don't know if you provided `window` module at runtime. It would fail when you call the imported function.

**Comment by yugabe** [comment]
The issue was indeed in one of my test projects (Blazor didn't register some event handlers correctly, so the generated interop method wasn't called). 

Using it as @pavelsavara described works as intended. Prefixing with "window" in itself does not work, but "globalThis" does. Thanks for the help.
