### ISSUE TITLE
Output caching middleware limits

### ISSUE THREAD

**Issue by onurbiyik** [dotnet/AspNetCore.Docs#27559]
Docs should mention following features for output caching middleware:

- `IOutputCacheStore `is used as storage. By default MemoryCache is used. An example of how to use `IDistributedCache `would be helpful.
- Default cache limit is 100MB. When this limit is exceeded, no new responses will be cached until older entries are evicted.
- Other `OutputCacheOptions `like `MaximumBodySize `and `UseCaseSensitivePaths`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb423d54-ee93-6dfd-87bb-ed79dff8b7b6
* Version Independent ID: cb423d54-ee93-6dfd-87bb-ed79dff8b7b6
* Content: [Output caching middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/caching/output.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/output.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 34550](https://dev.azure.com/msft-skilling/Content/_workitems/edit/34550)

**Comment by tdykstra** [comment]
cc @sebastienros

**Comment by tdykstra** [comment]
Per discussion offline with @sebastienros, we don't recommend using `IDistributedCache` with output caching because it doesn't have atomic features, which makes tagging brittle.
