### ISSUE TITLE
gRPC Duplex Streaming with .NET Framework using Grpc.Net.Client

### ISSUE THREAD

**Issue by JinsPeter** [dotnet/AspNetCore.Docs#27571]
Is there no way future way to use Duplex streaming from a .NET Framework client using Grpc.Net.Client?

https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-6.0#net-framework

What is the underlying limitation here? Note that we were able to use Grpc.Core for duplex streaming.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54f7bd57-6f98-4f49-62b0-f53ae5c46727
* Version Independent ID: 64cee8f6-7635-0cc8-4b9a-72f265414931
* Content: [Use gRPC client with .NET Standard 2.0](https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/netstandard.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/netstandard.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JinsPeter** [comment]
@JamesNK

**Comment by JamesNK** [comment]
The limitation is in Windows.

We use WinHttp for HTTP/2, and it didn't support duplex streaming. It is coming, but I don't know which version of Windows. Have you tried it with the latest Win11 2022 release? It might work there.

**Comment by wadepickett** [comment]
@JamesNK, should I add a note calling this out, or wait until duplex streaming is supported on Windows and update then?

**Comment by JamesNK** [comment]
I don't think there is anything to change here right now.
