### ISSUE TITLE
Add more Fixes to help migration to Top Level Route

### ISSUE THREAD

**Issue by begerard** [dotnet/AspNetCore.Docs#27578]
This rule will trigger for every migration of MVC .Net6 application .Net7. It should at least give some pointer to help understand Minimal API, and give more usuals cases fixes.

For example this one already cover in a ticket https://github.com/dotnet/aspnetcore/issues/44959#issuecomment-1308223971.
And other like the properties of IEndpointRouteBuilder which are now internal and must be accessed like that 
`((IEndpointRouteBuilder)app).DataSources...` instead of `endpoints.DataSources...` (unless there is a better solution).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Version Independent ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Content: [ASP0014: Suggest using top level route registrations](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-7.0)
* Content Source: [aspnetcore/diagnostics/asp0014.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0014.md)
* Product: **aspnet-core**
* GitHub Login: @safia
* Microsoft Alias: **safia**

**Comment by Rick-Anderson** [comment]
> This rule will trigger for every migration of MVC .Net6 application .Net7.
Do you mean this rule is triggered for every update of ASP.NET Core 6 to 7? Can you provide the simplest possible repo?

If you're migrating Web API controllers to minimal APIs, you need to understand minimal API.

**Comment by begerard** [comment]
No, I mistake "top level route" to "Minimal API", sorry. I think this rule help should give more information about "top level route" and migration from "endpoint" style MVC to "top level route" style, like the example I give.

That said, as "top level route" and "Minimal API" can be mixed up, adding a link to Minimal API documentation would be helpful too.
