### ISSUE TITLE
Add information about gRPC JSON configuration options

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#27588]
There are some config options available when registering gRPC JSON services. Docs should have a table that mentions them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Version Independent ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Content: [gRPC JSON transcoding in ASP.NET Core gRPC apps](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0#feedback)
* Content Source: [aspnetcore/grpc/json-transcoding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/json-transcoding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
This is already done on a different page - https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-binding?view=aspnetcore-7.0#customize-json

**Comment by wadepickett** [comment]
Represented on Azure DevOps content tracking here:
https://dev.azure.com/msft-skilling/Content/_workitems/edit/46155
