### ISSUE TITLE
Cheat sheet: Put most important at the top.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27599]
Until #27600, it's critical this doc provide the most important info up front. 

[Read the environment 1st](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#read-the-environment)
[Read the environment - Duplicate](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#read-the-environment-1)

Please put order sections should be listed.

My order
* Working with ports, not at the top,  should be near the bottom.
* Multiple ports after working with ports
* All the stuff with port in the H2 should go to the bottom
* Listen on all interfaces - near the end
* Listen on all interfaces using ASPNETCORE_URLS - ditto
* Certs stuff - low priority
* Config, logging, DI at the top
* Add Middleware top 1/3rd
* Custom dependency injection (DI) container - right after first DI 
* Request handling #1, should be at top
* Routing: Much higher than now
* Parameter Binding - near the top (and all the associated H3's that follow)
* Responses move up
* Filters and auth, move up

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs quick reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 61755](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61755)

**Comment by Rick-Anderson** [comment]
@rafikiassumani-msft  can you suggest optimal order?

**Comment by rafikiassumani-msft** [comment]
@Rick-Anderson I will add some comments by tomorrow.

**Comment by tdykstra** [comment]
Copying from https://github.com/dotnet/AspNetCore.Docs/pull/27709#issuecomment-1324258227

> @Rick-Anderson  and @tdykstra Can we use the following order? These are only big titles.
>
> - WebApplication -> rename to Host 
> - Handling request 
> - Routing (Everything)
> - Parameter Binding (Everything)
> - Handling Results (Everything including TypedResults)
> - Configurations
> - Environment
> - Ports
> - Services and DI
> - Customizations (Other stuffs)

**Comment by tdykstra** [comment]
@rafikiassumani-msft @BrennanConroy Putting Configuration, Environment, etc. toward the end involves taking sections out of WebApplication and WebApplicationBuilder. The resulting H2/H3 structure is below, showing what remains in WebApp/WebAppBuilder renamed Host.

The outline shows Customizations as an everything else category. The H3s in Host could go under Customizations and vice versa. The heading "Customizations" isn't a perfect fit for everything in it.

Please let me know if you'd like to make any changes to this plan.

```
## Host
### Template code (first part of current WebApplication section, currently doesn't have a heading)
### Customize the IHostBuilder
### Customize the IWebHostBuilder

## Handle requests - Routing
### Route Handlers
### Named endpoints and link generation
### Route Parameters
### Wildcard and catch all routes
### Route constraints

## Handle requests - Parameter binding
### Explicit Parameter Binding
### Parameter binding with DI
### Optional parameters
### Special types
### Custom Binding
### BindAsync
### Binding failures
### Binding Precedence
### Customize JSON binding
### Read the request body

## Handle Results
### Example return values
### Built-in results
### Customizing results

## Configuration
### Read Configuration (from WebApplication and WebApplicationBuilder)
### Add configuration providers (from WebApplicationBuilder)

## Environment
### Read the environment (from WebApplication and WebApplicationBuilder)

## Working with Ports
### Multiple ports
### Set the port from the command line
### Read the port from environment
### Set the ports via the ASPNETCORE_URLS environment variable

## Services and DI
### Add services (from WebApplicationBuilder)
### Access the Dependency Injection (DI) container (from WebApplication)
### Custom dependency injection (DI) container (from WebApplicationBuilder)
### Logging (from WebApplication)
### Add logging providers (from WebApplicationBuilder)

## ASP.NET Core Middleware
### Add Middleware (from WebApplicationBuilder)
### Developer exception page (from WebApplicationBuilder)

## Authorization
### Allow unauthenticated users to access an endpoint

## CORS

## Customizations
### Listen on all interfaces (from WebApplication) 
### Working with certificates (from WebApplication)
### Change the content root, application name, and environment (from WebApplicationBuilder)
### Change the web root (from WebApplicationBuilder)

## See also
Links to Filters and OpenAPI docs -- we could make these H2s with link only instead so they would show up in the automatic in-page TOC.
```
