### ISSUE TITLE
Add asp0014 to TOC

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27597]
And verify the test of the ASPxxx are hooked up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Version Independent ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Content: [ASP0014: Suggest using top level route registrations](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-7.0)
* Content Source: [aspnetcore/diagnostics/asp0014.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0014.md)
* Product: **aspnet-core**
* GitHub Login: @safia
* Microsoft Alias: **safia**

**Comment by tdykstra** [comment]
Fixed by #27727
