### ISSUE TITLE
Add guidance on shared resource approach in Blazor loc article

### ISSUE THREAD

**Issue by AlessandroMartinelli** [dotnet/AspNetCore.Docs#27594]
[Enter feedback here]
For what concerns Blazor webassembly localization, an user is likely to want to use his/her own folders hierarchy, and may not want to have the .resx file name equal to one of the .razor class using it. Thus, I think the doc is missing the following points:

- In IStringLocalizer<CultureExample2>, CultureExample2 is the name of the .resx class providing translations, not of the .razor class using it. It took me about two hours to understand this.
- In order to let dotnet find the CultureExample2 .resx file, you need to make a .cs class, even a fake one, with the same qualified name. This may seems obvious, but for someone who has never used .resx files so far like me, it is not. It took me about one hour trying to figure this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AlessandroMartinelli ... We won't be able to invest in anything ***too custom*** here. This is meant to be just the basic approach to loc in the simplest, most common terms. We would direct to the main doc set or to the community for anything more advanced or unusual. Let's ask Hisham for a comment on this one, he's our 👨‍🏫 *Loc Professor* 🏫 around here ...

@hishamco ... Isn't the way that we have the topic set up following the *normal* layout for maintaining `.rex` resource files ... SxS with the Razor components with the same name in the `.resx` filename? If so, then I plan to leave anything else to the main doc set or the community.

**Comment by AlessandroMartinelli** [comment]
Hi, @guardrex and thanks for the answer.
I know this may be a bit off topic, but if the _normal_ layout is actually one resx file for razor file, it could be useful to explain why. Is there a performance advantage in doing this? to me, it seems more like a risk of duplicating terms. Thus I'd like to know if there are any advantage in the _normal_ layout.

By the way: you said you'd leave details like this one is the main doc... but isn't [this](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0&pivots=webassembly#localization) the main doc? otherwise, it means I wasn't able to find the main doc on the topic while I was struggling to make localization work in the way that seemed normal to me (an unique .resx file in order to avoid duplicates).

**Comment by guardrex** [comment]
I'll leave it to @hishamco to answer. I'm not expert at loc and only have created a handful of apps over the years that had a requirement for it.

No, this isn't the main subject matter content for loc. It's in two spots ...

https://learn.microsoft.com/en-us/dotnet/core/extensions/localization

... which is linked via the 2nd sentence of the 2nd paragraph, and it's also in ...

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0

... which is linked in the line just above the purple NOTE in the opening remarks ...

> For additional general information, see \[Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0).

**Comment by guardrex** [comment]
I fixed those links. Those docs changed location at some point and had a redirect in place. I also laid the two .NET Fundamentals links out more plainly in the coverage.

**Comment by hishamco** [comment]
@guardrex I'm just localization manic ;)

AFAIK localization in Blazo is quite limited especially in WASM, but I'm not sure if there's something new in the latest release coz all my work on ASP.NET Core <=> Blazor Server-Side rendering

Backing to the comment

> For what concerns Blazor webassembly localization, an user is likely to want to use his/her own folders hierarchy, and may not want to have the .resx file name equal to one of the .razor class using it.

If you mean resources folder, you can place them into your custom path. In case you dislike the mapping 1-1 per source you can too but with extra efforts

**Comment by hishamco** [comment]
Frankly I didn't have a look to Blazor specific sample, but I might do. At the end localzation APIs is flexible and extensible, I did many implementation such EF, JSON, XLIFF. Also Orchard Core has PO files

So, nothing stop from doing what you want. For the docs, we already explained the RESX and path in much details, nothing to add here IMO. @guardrex correct me if i'm wrong

**Comment by hishamco** [comment]
@AlessandroMartinelli if you need any help on localization please ping, I'm available in many OSS to localize them ;)

BTW don't forgot to checkout [Oqtane Framework](https://github.com/oqtane/oqtane.framework) we did a great localization story there, especially for Blazor, have a look if you are interested

**Comment by guardrex** [comment]
I don't mind checking on the two OP items that you, @AlessandroMartinelli, called out in the OP.

I'm done for the week, but I am just sitting here goofing off. I may as well check on this scenario and see what what's here.

Let me get back to you guys shortly with what I find out and we can compare notes.

**Comment by guardrex** [comment]
Ok, I see what you're getting at, @AlessandroMartinelli.

Here's what I did @hishamco in following @AlessandroMartinelli general approach:

* Create a dummy class with an arbitrary class name.

  `Localization/ComponentLocalization.cs`:

  ```csharp
  namespace BlazorSample.Localization
  {
      public class ComponentLocalization
      {
      }
  }
  ```

* SxS in that `Localization` folder, I placed my resource files named the same way.

  * `Localization/ComponentLocalization.resx`
  * `Localization/ComponentLocalization.es.resx`

* In the component, I use the namespace and set up `IStringLocalizer` with that class:

  ```razor
  @using Localization
  @inject IStringLocalizer<ComponentLocalization> Loc
  ```

... and that seems to work fine.

@hishamco ... Is that a ........

* ### 👍 respectable, technically-correct way to go? ... and OK to add to the doc along those lines?
* ### train wreck 🚂💥⚰️😄 ... and not something that we should describe?

**Comment by hishamco** [comment]
What you did is simply a shared resource, we already did something similar in Oqtane Framework just for resource strings that are commonly used such as 'Add', `Edit` .. etc

**Comment by guardrex** [comment]
Do you know if that's documented clearly? I can go look. If I have a cross-link for a "shared resource" that describes that, then I'll cross-link to it. If not tho, then it sounds like you're saying that it would be ok to show that in the topic.

**Comment by guardrex** [comment]
mmmmm .... ok .... Yes, I see the dummy class in use in the main docs scenario on this at ...

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0#make-the-apps-content-localizable

**Comment by hishamco** [comment]
I'm sure we mentioned that somewhere, please hold on ..

**Comment by guardrex** [comment]
That doc makes it too cryptic in the most basic case.

I that that we probably should have a short section on this in the topic. I will cross-link to that topic ☝️, but I'd prefer to show something like my little test case ☝️ to make it dead simple to implement. Then if they need an `IHtmlLocalizer` or `IStringLocalizer`, they can look at that topic because I think it would be very similar to what's shown there.

**Comment by hishamco** [comment]
> mmmmm .... ok .... Yes, I see the dummy class in use in the main docs scenario on this at ...

Exactly, I saw it somewhere in our docs ;)

**Comment by guardrex** [comment]
Ok, I'll schedule this and try to knock it out quickly. We're still 🏃🏃🏃🏃🏃🏃😅 on a lot of .NET 7 work, but I'll squeeze it in.

Thanks, @AlessandroMartinelli ... I'll ping u on the PR later. Leave this issue open, as it will close automatically later.

Thanks again, @hishamco! 🥇 ***Localization Maniac***&trade; 🥇🤣

**Comment by hishamco** [comment]
IMHO we might add a paragraph to check the globalization & localization before the audience move forward into Blazor localization, no need to redundant the stuff here again

**Comment by guardrex** [comment]
I already have the cross-links at the top of this topic, but not directly to that section.

Even if the reader sees that section, my guess is that a reader wouldn't be able to figure out how simple it is. Since this won't take up very much space, I don't mind a short section here on it that refers to the preceding example that we already have in this topic.

**Comment by AlessandroMartinelli** [comment]
Hi,
thank you for all the answers, really more than I asked for :)  

The only thing I think it could be useful is a comparison in terms of advantages between the following two scenarios

- Localization keys (the terms to be translated) taken from a constants file. This would help guarantee uniqueness of keys but would introduce a little overhead since all terms have to be inserted in the constants file first.
- Localization keys sparsed among the .razor files. This would allow to avoid the constants file overhead, but it would be harder to keep uniqueness of keys (important to avoid duplicated works during keys translation by the hand of the human translator)

**Comment by guardrex** [comment]
> thank you for all the answers, really more than I asked for :)

Sure thing. I hope to reach this within a week before the 🦃 holiday break here.

> The only thing I think it could be useful is a comparison in terms of advantages between the following two scenarios

I don't think the guidance on that subject would be different from whatever is recommended for MVC apps (views) and Razor Pages apps (pages). It's best for the main doc set loc topics to cover that angle. However, I don't see anything on that in the [*Overview* topic](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0). You could open a separate issue on that for consideration from the bottom of that topic.
