### ISSUE TITLE
repl commands don't work

### ISSUE THREAD

**Issue by rmnrdi** [dotnet/AspNetCore.Docs#27608]
Copying a pasting the following command into the cli, as per the instructions, doesn't work correctly.

httprepl https://localhost:7159/api/todoitems
post -h Content-Type=application/json -c "{"name":"walk dog","isComplete":true}"

**If I paste it into notepad++ and put it on the same line, I get this error.**
C:\Users\rober\source\repos\TodoApi-App>httprepl https://localhost:5001/api/todoitemspost -h Content-Type=application/json -c "{"name":"walk dog","isComplete":true}"
(Disconnected)> connect https://localhost:5001/api/todoitemspost -h Content-Type=application/json -c {name:walk dog,isComplete:true}
UnknownOption -- -h
UnknownOption -- -c
ArgumentCountOutOfRange -- 2
Usage: connect [rootAddress] [--base baseAddress] [--openapi openApiDescriptionAddress] [--verbose] [--persist-headers] [--persist-paths]

Configures the directory structure and base address of the api server based on the arguments and options specified. At least one of [rootAddress], [--base baseAddress] or [--openapi openApiDescriptionAddress] must be specified

By default, existing headers set via the `set header` command and path segments beyond the base address are cleared when this command is executed. Use [--persist-headers] and [--persist-paths] to change those defaults

[rootAddress] will be used to automatically determine the base address and OpenAPI description address
[--base baseAddress] and [--openapi openApiDescriptionAddress] allow you to explicitly set those addresses and skip auto detection
[--verbose] provides more detail about OpenAPI Description discovery and parsing
[--persist-headers] leaves existing session headers in place when connecting to a new API
[--persist-path] leaves existing path segments in place when connecting to a new API

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Copying a pasting the following command into the cli, as per the instructions, doesn't work correctly.

Doesn't work how?

**Comment by Rick-Anderson** [comment]
Use the default, version .NET 7 of the tutorial
https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio&source=docs#test-posttodoitem

**Comment by rmnrdi** [comment]
I put how it didn’t work in the body of the message….

**Comment by rmnrdi** [comment]
> Use the default, version .NET 7 of the tutorial https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio&source=docs#test-posttodoitem

That just came out the other day and probably won't  be using that version for my project. Is there something wrong with the .NET 6 tutorial?

It is a cool tutorial, I just can't get repl working to complete it

**Comment by Rick-Anderson** [comment]
> That just came out the other day and probably won't be using that version for my project. Is there something wrong with the .NET 6 tutorial?

Nope, it works for me and many customers. You don't need .NET 7  to use Swagger,  Why don't you want to use the latest released version of .NET?

> 
> It is a cool tutorial, I just can't get repl working to complete it

Figure it out and post back here what you did wrong with [HttpRepl](https://learn.microsoft.com/en-us/aspnet/core/web-api/http-repl/?view=aspnetcore-6.0&tabs=windows)

**Comment by rmnrdi** [comment]
Why would I post something I did wrong in Github? 

 

I displayed what I pasted into the terminal, I put the errors in it.

 

Is what I copy\pasted incorrect? Assuming that’s my port number. Which it is.

**Comment by Rick-Anderson** [comment]
> Why would I post something I did wrong in Github?

That's the open source way, to help others that made the same mistake. Another GitHub best practice is to not reply to email but directly at the issue.

**Comment by rmnrdi** [comment]
Is it the “Open source way” to ask for more information in a ticket and then close the ticket (as completed?) about an hour later? 

 

Also, I’m getting emails, so I’m replying to emails…
