### ISSUE TITLE
Move snippet to code file

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27609]
In [aspnetcore/includes/route-groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/route-groups.md) 

Move
 ```csharp
var outer = app.MapGroup("/outer");
var inner = outer.MapGroup("/inner");

inner.AddEndpointFilter((context, next) =>
{
    app.Logger.LogInformation("/inner group filter");
    return next();
});

outer.AddEndpointFilter((context, next) =>
{
    app.Logger.LogInformation("/outer group filter");
    return next();
});

inner.MapGet("/", () => "Hi!").AddEndpointFilter((context, next) =>
{
    app.Logger.LogInformation("MapGet filter");
    return next();
});
```

From embedded snippet to code like the rest of the file

`:::code language="csharp" source="~/fundamentals/minimal-apis/7.0-samples/todo-group/TodoEndpoints.cs" id="snippet_create":::`

See #27607

cc @sammychinedu2ky 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sammychinedu2ky** [comment]
Ok would work on that✍️ @Rick-Anderson

**Comment by Rick-Anderson** [comment]
done in https://github.com/dotnet/AspNetCore.Docs/pull/27615
