### ISSUE TITLE
Ihr wollt ein Feedback, gerne

### ISSUE THREAD

**Issue by Daniel-Majunke** [dotnet/AspNetCore.Docs#27601]
[Enter feedback here]
 eure Seiten führen mich in 90% der Fälle zu keiner Lösung ich denke manchmal das ihr nicht verstanden habt das wir nur 80 Jahre leben. Das zu installierennde Nugetpackage Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore ist nicht mit net 6 kompatibel vielen Dank dafür.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [Tutorial: Get started with EF Core in an ASP.NET MVC web app](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
your pages don't lead me to a solution in 90% of the cases, I sometimes think that you haven't understood that we only live 80 years. The nuget package to be installed Install-Package `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` is not compatible with net 6 thanks for that.

It is, see https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
