### ISSUE TITLE
Create Overview of Minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27600]
~@rafikiassumani-msft~ @JeremyLikness   just get a solid draft and I'll polish it off.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Version Independent ID: b09824ab-b051-75a1-13b7-b0e281cc46e0
* Content: [Minimal APIs quick reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JeremyLikness** [comment]
Will do. Expect a draft by Thanksgiving. Thanks.
