### ISSUE TITLE
Include YARP

### ISSUE THREAD

**Issue by maroonedsia** [dotnet/AspNetCore.Docs#27613]
Hi, I think this doc should get updated with YARP scenarios. Thanks!  👍

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62fb594f-04bf-c4d7-c94b-6cd6d8b12d75
* Version Independent ID: 64e973ac-838d-4459-06b0-4e943bff936e
* Content: [Host and deploy ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @maroonedsia ... This is a dupliate of https://github.com/dotnet/AspNetCore.Docs/issues/25309.

**Comment by maroonedsia** [comment]
Hi, thanks for the info. It’s an honor to open an issue that David Fowler has already opened! 😝

Regards,
Siavash Mortazavi
