### ISSUE TITLE
Update Migration doc for dotnet 6 to 7 to include a fix for "untrusted SQL authority certificate"

### ISSUE THREAD

**Issue by Yousif-FJ** [dotnet/AspNetCore.Docs#27612]
Add a fix for the error "The certificate chain was issued by an authority that is not trusted".
This error happens when upgrading to EF core 7, and using untrusted certificate on the server. The behavior is different from EF core 6 as this error didn't happen there.
For me, this page helped me [error after upgrading SNAC applications](https://learn.microsoft.com/en-us/troubleshoot/sql/connect/certificate-chain-not-trusted?source=recommendations&tabs=ole-db-driver-19)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Yousif-FJ  isn't that [Encrypt defaults to true for SQL Server connections](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#encrypt-defaults-to-true-for-sql-server-connections)?

EF Core breaking changes are documented there.
