### ISSUE TITLE
Wrong using statement added to Razor Pages work with a database tutorial's Visual Studio Code examples

### ISSUE THREAD

**Issue by colinkiama** [dotnet/AspNetCore.Docs#27614]
Some of the VIsual Studio Code examples contain the following using statement:
```cs
using RazorPagesMovie.Data;
``` 
This line stops the example from building when going through the tutorial with Visual Studio Code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Part 4, work with a database](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-7.0&tabs=visual-studio&source=docs)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 36499](https://dev.azure.com/msft-skilling/Content/_workitems/edit/36499)

**Comment by Rick-Anderson** [comment]
Stops it how? What's wrong with it?

**Comment by colinkiama** [comment]
On my machine, `Data/RazorPagesMovieContext.cs` is created without being in the `RazorPagesMovie.Data` namespace.

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

    public class RazorPagesMovieContext : DbContext
    {
        public RazorPagesMovieContext (DbContextOptions<RazorPagesMovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorPagesMovie.Models.Movie> Movie { get; set; } = default!;
    }
```
This doesn't cause any issues until the "work with a Database" Visual Studio Code code examples which starts adding using statements for the RazorPagesMovie.Data namespace.

I think the issue is with the consistency of the code examples for example in this section: https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-7.0&tabs=visual-studio-code#add-the-seed-initializer

It made me think that I missed a step somewhere because it's not consistent with the code I have in my editor for `Program.cs` before adding the highlighted code in the [Add the seed initializer]( https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-7.0&tabs=visual-studio-code#add-the-seed-initializer) step:

```cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddDbContext<RazorPagesMovieContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("RazorPagesMovieContext") ?? throw new InvalidOperationException("Connection string 'RazorPagesMovieContext' not found.")));

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
```

**Comment by colinkiama** [comment]
Here's an example of the error that occurs on build:
```sh
/home/colinkiama/RazorPagesMovie/Models/SeedData.cs(2,23): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'RazorPagesMovie' (are you missing an assembly reference?) [/home/colinkiama/RazorPagesMovie/RazorPagesMovie.csproj]
```

**Comment by Rick-Anderson** [comment]
@wadepickett can you investigate ASAP?

**Comment by wadepickett** [comment]
@Rick-Anderson,

Following the tutorial as it is published now, on VSC for Windows, you do get the following for Data/RazorPagesMovieContext.cs:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

    public class RazorPagesMovieContext : DbContext
    {
        public RazorPagesMovieContext (DbContextOptions<RazorPagesMovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorPagesMovie.Models.Movie> Movie { get; set; } = default!;
    }



Worth noting, there are couple of moments when the code shown in the latest VSC tutorial update do not match the project:

For VSC at the top of the work with a database tutorial it says appsettings.json should have **"Data Source=RazorPagesMovie.Data.db"**:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "RazorPagesMovieContext": **"Data Source=RazorPagesMovie.Data.db"**
  }
}

But this is what is generated following the steps is **"Data Source=.db"**:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "RazorPagesMovieContext": **"Data Source=.db"**
  }
}



Then later creating the seed initializer and updating program.cs:
Using RazorPagesMovie.Data; is shown, but not highlighted as one to add.  However, "using RazorPagesMovie.Data" does not exist in program.cs.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/10985336/201778238-37ce1bc1-ffed-4f2f-85bf-996f5659df88.png">

**Comment by wadepickett** [comment]
@Rick-Anderson 
Removing:
`using RazorPagesMovie.Data;`

from the _SeedData.cs_ code in steps for [Work with a database - Seed the database](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-7.0&tabs=visual-studio-code#seed-the-database) allows it all to work fine.

I am not catching on to why the connection string is set as "Data Source=.db" plus the RazorPagesMovie.Data namespace is not used.  Is that as designed, and we simply need to drop `using RazorPagesMovie.Data` or is that not intended and I should file a bug?  If you are not sure, that's fine, I'll just file it and find out.

**Comment by Rick-Anderson** [comment]
@wadepickett open a scaffold bug. If it's creating a file outside the root folder without the folder name in the namespace, that's a bug.

Use the simplest possible instructions in the repo.

something like

1. Create a new RP web app in VS, call in ...
2. Create a model (doesn't need to be in models folder)
3. Create the Pages/Movies folder
4. Scaffold

Then have CLI instructions to do the same

**Comment by wadepickett** [comment]
Ok thanks Rick.  Honestly I don’t know where that scaffolding repo is that the bug should go into.  Where is it?
________________________________

**Comment by Rick-Anderson** [comment]
https://github.com/dotnet/Scaffolding

**Comment by wadepickett** [comment]
Also of note: since the db context name is being provided and the cli tool seems to be completely ignoring that on output.

**Comment by wadepickett** [comment]
Tracking product issue: dotnet/Scaffolding#2104

**Comment by wadepickett** [comment]
Development team took a look at this issue and will work on it.

In between time the solution is to update the tutorials to specify the namepace in the  `-dc` in the scaffolding command:

Here is the suggestion provided:
The namespace name is added for the DbContext if a . separator is used when specifying the db context, ala, `dotnet aspnet-codegenerator razorpage -m Movie -dc **BlahNamespace**.RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries -sqlite`

So I will update this tutorial and create issues for others that need it for now and take care of those as well.
