### ISSUE TITLE
Review: Migrate from ASP.NET Core 6.0 to 7.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27625]
This has most of the migration info but needs a comprehensive review.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&branch=pr-en-us-27102&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
This migration guide checks out for minimal APIs, IMO, assuming this is not the place where we document new features users can adopt (e.g. endpoint filters or TypedResults).

**Comment by Rick-Anderson** [comment]
> This migration guide checks out for minimal APIs, IMO, assuming this is not the place where we document new features users can adopt (e.g. endpoint filters or TypedResults).

Correct, not where we doc new features

**Comment by Rick-Anderson** [comment]
Moved to #27786

**Comment by tdykstra** [comment]
> Moved to #27786

I don't think that's the right number. Did you mean #27625?
