### ISSUE TITLE
Lazy loaded `BlazorCustomElements.js` file does not adhere to the `loadBootResource` configuration

### ISSUE THREAD

**Issue by martinlingstuyl** [dotnet/AspNetCore.Docs#27638]
[EDIT by guardrex to add the metadata]

Hi guys,

Since .NET 7 is out, I've been test driving Blazor WASM to see how to use it in combination with other frameworks.

I've configured the following to be able to point the loading of resources to a specific server.
https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources

Which works nicely.

I'm now using the `Microsoft.AspNetCore.Components.CustomElements` nuget package to get CustomElements to work.
Initially you had to reference the script manually:

```html
<script src="_content/Microsoft.AspNetCore.Components.CustomElements/BlazorCustomElements.js"></script>
```

But since .NET 7 has been released it's lazy loaded by ASP.NET. Which is awesome. The only problem is: it uses the URL of the server you are on, to lazy load the file, while it should be respecting the `loadBootResource` configuration.

Which is a problem for me, as I'm depending on the `loadBootResource` function to get the WASM files from another server, for example a CDN.

Is that something you guys can fix? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad891f84-d11e-e334-fcdc-b55c5171fca4
* Version Independent ID: 11f8db3d-9988-e0a1-89c5-c3552ee47b93
* Content: [ASP.NET Core Blazor startup](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources)
* Content Source: [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @martinlingstuyl ... Please use the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

I'll add the metadata manually to this issue, but please use that process in the future.

**Comment by guardrex** [comment]
I see what ur saying. This isn't a docs issue at this point. Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27638
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
I'll keep an 👁️ on your PU issue and re-open this if they explain something good for coverage on this scenario.

**Comment by martinlingstuyl** [comment]
Thanks!
