### ISSUE TITLE
Syntax problem @onclick="Navigation.NavigateTo("/counter")"

### ISSUE THREAD

**Issue by yogyogi** [dotnet/AspNetCore.Docs#27635]
[EDIT by guardrex to add the metadata. @yogyogi ... Please use the **This page** feedback form at the bottoms of topics to open issues.]

# Issue description

The problem is for the syntax of onclick event for blazor routing and navigation page. The code is from "Handle/prevent location changes" section. 

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core
* [ ] .NET 7.0 

<details>
<summary>The below code will not work as it's syntax is wrong. Double quotes inside double quotes.</summary>

```
<button @onclick="Navigation.NavigateTo("/counter")">
        Counter (Prevented)
    </button>
```
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Thanks for the report @yogyogi ... I'll fix this right now.
