### ISSUE TITLE
WebOptimizer not compatible with .NET6/7

### ISSUE THREAD

**Issue by ParaxxTwo** [dotnet/AspNetCore.Docs#27645]
Why would you write that ASP.NET Core is compatible with WebOptimizer when it is not compatible with .NET6/7. Please advise. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-6.0)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Yes, Rick ... it doesn't look good ... weakly supported at best and probably broken for .NET 6 or later ...

* https://github.com/ligershark/WebOptimizer/issues/239
* https://github.com/ligershark/WebOptimizer/issues/232

... but one commenter said they got it working without saying how ...

https://github.com/ligershark/WebOptimizer/issues/227

... and one person saying that they figured out the reason for the 6.0 failure and stated a workaround ...

https://github.com/ligershark/WebOptimizer/issues/210#issuecomment-1029860096

**Comment by Rick-Anderson** [comment]
Dup of  #20808
