### ISSUE TITLE
Incorrect UI location

### ISSUE THREAD

**Issue by frank-hoffman** [dotnet/AspNetCore.Docs#27648]
The article reads: "In a Blazor Server app, customize the experience in the Pages/_Host.cshtml file:"

However, this code actually exists in Pages/_Layout.cshtml

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adbc1392-92dc-c42e-ba48-a722cffa9b6d
* Version Independent ID: 66a0b1c2-c45c-98ca-9808-6f340a861c44
* Content: [Handle errors in ASP.NET Core Blazor apps](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/handle-errors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/handle-errors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @frank-hoffman ... It depends on the version ... it changed to `_Layout.cshtml` for 6.0 but then back to `_Host.cshtml` for 7.0. I'll check and see if all of the versioning are correct right now. BRB ...............

**Comment by frank-hoffman** [comment]
Thanks I see it now
