### ISSUE TITLE
This example assumes 1 instance

### ISSUE THREAD

**Issue by jstafford5380** [dotnet/AspNetCore.Docs#27662]
I think this example assumes that you only have one instance of the application running. If there were multiple (i.e. production), then you couldn't necessarily guarantee that both users are connected to the same instance in order for chat to work. It would help to call this out and/or link to an article describing out to integrate with an external hub (and not just signalr for azure) which I have not been able to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jstafford5380 ... You need sticky sessions for that scenario. It's covered in the *Host and deploy* doc ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-7.0#signalr-configuration

I'll check and see if there's a cross-link missing here in the additional resources area.

**Comment by guardrex** [comment]
*Confirmed!* The cross-link to the *Host and deploy* doc is in the *Additional resources* section.

Note that this is just a tutorial for a basic experience. The reference docs take care of the rest of the coverage, and the main SignalR docs apply.

**Comment by guardrex** [comment]
btw for ...

> and not just signalr for azure

We cross-link out for IIS, and we have a bit for Kubernetes there. The Linux docs ***might*** have coverage on it in the main doc set *Host and deploy* coverage and/or via the SignalR node of the main doc set.

Other server products will need to provide their own docs. We can't cover every server out there that MS doesn't own.
