### ISSUE TITLE
ASP.NET Core Identity is broken, it implements explicitly an old version of Duende API.

### ISSUE THREAD

**Issue by hi-diego** [dotnet/AspNetCore.Docs#27671]
This is broken, AspNetCore is using a depercataded version of Duende as you can see in this Open issue https://github.com/dotnet/aspnetcore/issues/44990

[ApiAuthorizationDbContext.cs](https://github.com/dotnet/aspnetcore/blob/c85baf8db0c72ae8e68643029d514b2e737c9fae/src/Identity/ApiAuthorization.IdentityServer/src/Data/ApiAuthorizationDbContext.cs) implements explicitly the old Duende API.

Duende is so aware of this that they even have commments on their [code](https://github.com/DuendeSoftware/IdentityServer/blob/5d64bcff67e40b1d2471e7bf7fe74a19453c0222/src/EntityFramework.Storage/Interfaces/IPersistedGrantDbContext.cs) that explains the problem

I have created a PR to add a missing property on ApiAuthorizationDbContext, please follow it https://github.com/dotnet/aspnetcore/pull/45145

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Let's close this until https://github.com/dotnet/aspnetcore/issues/44990 is resolved.
