### ISSUE TITLE
Potential Typo?

### ISSUE THREAD

**Issue by NickHoggard2** [dotnet/AspNetCore.Docs#27697]
Maybe I'm miss-reading this, but given the contents of the remainder of the paragraph after the statement below, I feel this should be stating "generally **not as** secure as ...".  

" Receiving the access token via query string is generally secure as using the standard Authorization header"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8af11946-ea05-3be2-6fa1-c4c01aa76d8c
* Version Independent ID: 58e87eb0-240b-ab00-c5f4-32a0ab2e0028
* Content: [Security considerations in ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-7.0)
* Content Source: [aspnetcore/signalr/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
"generally as secure as" is more accurate. The main downside is stated in the next sentences about servers logging the url + query string.

**Comment by NickHoggard2** [comment]
Wouldn't the fact that the authentication data is visible in the logs enough to say it is not as secure as an authorization header, which wouldn't be visible in any logs?

**Comment by BrennanConroy** [comment]
Hence the usage of "generally". If it was the same as an authorization header we wouldn't add "generally" to the sentence.

> authorization header, which wouldn't be visible in any logs?

This isn't always true, anyone could log headers, it's just less common in practice.
