### ISSUE TITLE
Can we integerate Docker with the ContosoUniversity application for ASP.NET 6 MVC?

### ISSUE THREAD

**Issue by LayersOfAbstraction** [dotnet/AspNetCore.Docs#27696]
You know after having to reformat Windows 10 move than once, I have observed locally installing SQL Server is a bit of a pain in contrast to creating the CU database in a Docker Image (which is much easier). I have seen tutorials that allow you to:

Use .NET6 apps in Docker.

[Use a local SQL Server instance inside a docker image.](https://www.yogihosting.com/docker-aspnet-core-sql-server-crud/#docker-compose-sql)

That being said, I'm wondering if we can do the same thing with the doco for ContosoUniversity and have integration with Docker as a secondary option? We could just give them a link to Docker website for them getting started with installing Docker and in an (optionally marked) heading, cover migrating the MVC webapp to Docker container and generate an SQL Server database in a Docker image?

**Comment by Rick-Anderson** [comment]
Using SQL Express or SQLite is easy. This tutorial is not about docker.
