### ISSUE TITLE
Support Redis Clusters with Redis 7 & SSubscribe/SPublish

### ISSUE THREAD

**Issue by tomap** [dotnet/AspNetCore.Docs#27693]
Hello, 

Currently, the way to scale out SignalR servers is to rely on a backplane.
Unfortunately, this backplane cannot be made redundant by using a Redis Cluster because the current behavior of SignalR is to use Subscribe/Publish commands which are not relayed to the other nodes of a redis cluster

Redis 7 introduced SSubscribe & SPublish which is a pub sub mecanism compatible with cluster (aka messages are relayed to every node of the cluster)
https://redis.io/docs/manual/pubsub/#sharded-pubsub
This could be a way to support Redis Clusters

The current status is that StackExchange.Redis does not support those new commands, but work is tracked here:
https://github.com/StackExchange/StackExchange.Redis/issues/2055
Hopefully, once the work is done on StackExchange.Redis side, SignalR can pickup from there to use those new features

For reference: https://github.com/dotnet/AspNetCore.Docs/issues/7814#issuecomment-1231516740

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://learn.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-7.0)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by guardrex** [comment]
Hello @tomap ... Is this a documentation-only request, or does the support you're requesting pertain to first have updates to SignalR in the framework? ... then docs later if the product unit decides to take on the request.

**Comment by tomap** [comment]
Indeed, I'll post a request on SignalR repository :)

**Comment by guardrex** [comment]
Ok, thanks. We try to keep a clean backlog here. If they adopt it in the framework for a future release, it will go on a roadmap tracking issue on their side + get 8.0 labeling. We then draw new issues from there, so we can close this.
