### ISSUE TITLE
Blazor CORS dead link

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/AspNetCore.Docs#27705]
> For information on Cross-origin resource sharing (CORS), see the [CORS guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-6.0&pivots=webassembly#cross-origin-resource-sharing-cors) later in this article.

The link is dead it appears.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Call a web API from an ASP.NET Core Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think this is going to turn out to be a Whole-topic Versioning problem. I'll look when I get home in an hour or so.

**Comment by guardrex** [comment]
Confirmed. I'll fix this by calling out the section in text without a link, which is fine in a case like this where it's an intra-doc cross-link.
