### ISSUE TITLE
Typo on Page

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#27703]
This is minor, but this code sample results in a compile error.  The error is

```
Error (active)	CS0542	'people': member names cannot be the same as their enclosing type.	
```
```
public List<Person> people =
        new()
       {
            { new Person { Data = "Person 1" } },
            { new Person { Data = "Person 2" } },
            { new Person { Data = "Person 3" } }
        };
```
---

The issue is that the name of the page is "People" and then the list name is also 'people'

Would suggest changing the name of the list to `peopleList`.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks, @gregoryagu ... If it's not part of the snippet sample, I'm not surprised. Most of this particular error was cleaned up when examples went into the apps because they 💥 with this one on build there, alerting me 🦖 to the problem.

**Comment by gregoryagu** [comment]
Note, you actually can have the same name if the page name is Capitalized.  But still, might be a good idea to change it so it is more clear.
