### ISSUE TITLE
Remove class on "Unthemed" sample button

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#27714]
This snippet:
```
<p>
    <button class="btn" @onclick="IncrementCount">
        Increment Counter (Unthemed)
    </button>
</p>

<p>
    <button 
        class="btn @(ThemeInfo is not null ? ThemeInfo.ButtonClass : string. Empty)" 
        @onclick="IncrementCount">
        Increment Counter (Themed)
    </button>
</p>
```

Currently produces this output:

![image](https://user-images.githubusercontent.com/3810620/203308519-09cf67a3-932a-46da-bf70-b95eb2f52983.png)

Note that the Increment Count (Unthemed) button is actually partially themed by the Bootstrap class, and it does not actually look like a button.

If the class is removed like this:

```
<p>
    <button @onclick="IncrementCount">
        Increment Counter (Unthemed)
    </button>
</p>
```

Then actually looks unthemed:

![image](https://user-images.githubusercontent.com/3810620/203308050-3ed130da-429e-4e1b-8904-66c7e832b90c.png)

I would recommend removing the class.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7ba96d-bae0-96ee-e76a-71c6e5f4c23f
* Version Independent ID: 5fe884b8-51e1-1b91-57f8-522ff0b7890c
* Content: [ASP.NET Core Blazor cascading values and parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/cascading-values-and-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yeah ... good idea. I'll do that right now ... and I think 🤔 ... if I get lucky here 🍀🤞 ... that's in a snippet from the samples repo, so I can address this in the samples repo with a quick PR over there. *Stand-by* ... I'll take a look.

**Comment by guardrex** [comment]
***Confirmed!*** ... I'm going to open this over on that repo and knock it out right now.

**Comment by gregoryagu** [comment]
You are amazing @guardrex!

**Comment by guardrex** [comment]
![Organon](https://user-images.githubusercontent.com/1622880/203312039-8258eca0-dd9f-412f-9c97-1926bdeea4c4.png)

### *My horoscope said I'd be useful to somebody today.*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&mdash; Organon ([Geoffrey Bayldon](https://www.imdb.com/name/nm0001933/)) Dr. Who: [The Creature from the Pit](https://www.bbc.co.uk/programmes/b00s63gx), &copy;1979 [BBC](https://www.bbc.com/)
