### ISSUE TITLE
Typo in app offline documentation

### ISSUE THREAD

**Issue by petrhavlak** [dotnet/AspNetCore.Docs#27713]
Typo in documentation, bottom section has app_offine.htm instead of app_offline.htm, missing letter l.

![image](https://user-images.githubusercontent.com/43609940/203308317-a299e58a-5cc4-4b83-ade7-48bacc5a5e95.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89993243-0d30-a0d7-a01a-b43f763e8a09
* Version Independent ID: ec3a2dab-4b7d-36c4-939f-f392a236611f
* Content: [App Offline file (app_offline.htm)](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/app-offline?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/app-offline.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/app-offline.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @petrhavlak.

@Rick-Anderson ... I have a second here between *Blazory Things*&trade;, so I'll knock it out.
