### ISSUE TITLE
Update DateRangeTP in [ Bind with TryParse ] 

### ISSUE THREAD

**Issue by BlueHtml** [dotnet/AspNetCore.Docs#27720]
- The use of `DateRangeTP` class in document and example is wrong(<https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding#bind-with-tryparse>)
- code example also need to be updated(<https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC>)

#### document

the following paragraph need to be update to something like:

```diff
public class DateRangeTP
{
    public DateOnly? From { get; }
    public DateOnly? To { get; }

    public DateRangeTP(string from, string to)
    {
        if (string.IsNullOrEmpty(from))
            throw new ArgumentNullException(nameof(from));
        if (string.IsNullOrEmpty(to))
            throw new ArgumentNullException(nameof(to));

        From = DateOnly.Parse(from);
        To = DateOnly.Parse(to);
    }

    public static bool TryParse(string? value, out DateRangeTP? result)
    {
+      var range = value?.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
+      if (!range?.Length == 2)
-       if (string.IsNullOrEmpty(value) || value.Split('-').Length != 2)
        {
            result = default;
            return false;
        }

-       var range = value.Split(',');
        result = new DateRangeTP(range[0], range[1]);
        return true;
    }
}
```

```diff
+ The following controller action uses the DateRangeTP class to bind a date range:
- The following controller action uses the DateRDateRangeTPange class to bind a date range:
```

```diff
// GET /WeatherForecast/ByRangeTP?range=7/24/2022,07/26/2022
+ public IActionResult ByRangeTP([FromQuery] DateRangeTP range)
- public IActionResult ByRangeTP([FromQuery] DateRange range)
{
```

#### code example

- call method: <https://github.com/dotnet/AspNetCore.Docs/blob/0484277eef60875c7024781814d1f0111d72636b/aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Controllers/WeatherForecastController.cs#L66>
- DateRangeTP class:<https://github.com/dotnet/AspNetCore.Docs/blob/0484277eef60875c7024781814d1f0111d72636b/aspnetcore/mvc/controllers/bind-tryparse/7.0-samples/BindUsingTryParse/BindTryParseMVC/Models/DateRangeTP.cs#L22>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#itp7)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan please review

**Comment by fiyazbinhasan** [comment]
Nice catch! @BlueHtml are you interested in fixing these in a PR? Let me know 😸 
tag: @Rick-Anderson

**Comment by BlueHtml** [comment]
@fiyazbinhasan PR is here #27738

**Comment by fiyazbinhasan** [comment]
oops, what a coincident. let me close my PR
