### ISSUE TITLE
Code Errors from "Use the MapGroup API" onward

### ISSUE THREAD

**Issue by Jakester26** [dotnet/AspNetCore.Docs#27725]
The tutorial code fails with "CS8802 Only one compilation unit can have top-level statements."
 Top-level statements - programs without Main methods

The workaround is the body of the code, i.e. everything after the "using" statements in the traditional partial class with the Main(). 

```
using Microsoft.EntityFrameworkCore;
using TodoApi;

partial class Program
{
    private static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 42409](https://dev.azure.com/msft-skilling/Content/_workitems/edit/42409)

**Comment by Rick-Anderson** [comment]
@Jakester26  on [Use the MapGroup API](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio#use-the-mapgroup-api), the code is correct.

See [Top-level statements - programs without Main methods](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements), the full project [here](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoGroup), and [Program.cs](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoGroup/Program.cs)

I'm guessing you have another file that's using top level statements, that's a common reason for the error.

cc @tdykstra

**Comment by Jakester26** [comment]
You are correct. I was making a copy of the program.cs in the same folder using File Manager and I didn’t notice VS2022 was picking it up.

 

I moved the copies to another folder and the problem disappeared.

**Comment by Rick-Anderson** [comment]
@Jakester26 thanks for letting us know.
