### ISSUE TITLE
Forced usage of `IHealthCheckPublisher` in gRPC health checks

### ISSUE THREAD

**Issue by cvetomir-todorov** [dotnet/AspNetCore.Docs#27734]
What is the point of forcing one to use the `IHealthCheckPublisher`? With HTTP health checks it's not mandatory.

In my scenario I want to configure the initial delay, period and timeout in my Kubernetes probes. I don't want to duplicate those in my application. Additionally, Kubernetes has logic of the `startup` probe which, before returning success, prevents the `live` and `ready` probes from being called. Duplicating that with the `predicate` is definitely suboptimal. Why should I write code to prevent issues like calling a dependency in the `live` endpoint, before the dependency is even setup successfully, which happens only after `startup` succeeds?

I already removed the service descriptor but that simply broke the gRPC health check endpoint. In the code I inspected the `GrpcHealthCheckPublisher` is the only place calling `SetStatus` which makes me sad...

```C#
ServiceDescriptor[] descriptors = services.Where(descriptor => descriptor.ServiceType == typeof(IHealthCheckPublisher)).ToArray();
foreach (ServiceDescriptor descriptor in descriptors)
{
    bool removed = services.Remove(descriptor);
    Debug.Assert(removed, $"Failed to remove {nameof(IHealthCheckPublisher)} implementation {descriptor.ImplementationType?.FullName}");
}
```

How can I get rid of this flow-disrupting unneeded functionality? I simply need my gRPC health checks being called on demand, as configured in my Kubernetes probes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1e8570-b223-d4b9-c85f-afeb2e3e8941
* Version Independent ID: 5a1e8570-b223-d4b9-c85f-afeb2e3e8941
* Content: [gRPC health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@JamesNK, add to this topic?

**Comment by cvetomir-todorov** [comment]
@JamesNK I ended up here from the link in the asp.net docs. But anyway copied the issue and toned it down a bit. Initially I was very frustrated about the lack of flexibility which should be the case of a widely used base library. I hope you guys can fix this. I would close this issue, if you don't mind.
