### ISSUE TITLE
No user info in controllers after login

### ISSUE THREAD

**Issue by tabinnorway** [dotnet/AspNetCore.Docs#27732]
So, when I use this article to enable Google login, it kinda almost sorta works.
I have created a Blazor app with google login and individual users. As per tutorials.
When I then call the WeatherForecast API, I get that the user is authenticated,
but there is no User.Identity.Name for example.

How do I get the user info in server controllers after login?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
- https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio
- https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio
- https://learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-7.0&tabs=visual-studio

**Comment by tabinnorway** [comment]
Thank you for your answer, but it doesn't appear to me, and I might be a complete idiot here, but it seems like these articles describe how to set up authorization in my Blazor app. I seem to have managed that fine, and when I log in with Google, in the top corner of my Blazor pages my email is displayed. So, I have in fact logged in.

From my Blazor app I then call the WebAPI in WeatherController, which has an [Authorize] attribute. However, when that API is called, I can find no information about the login. Inside WeatherController I have the following:
User?.Identity?.Name == null
await _userManager.GetUserAsync(User); returns null
HttpContext?.User?.Identity?.Name

What I am able to do is to grab the bearer token from
Request.Headers["Authorization"];
I can then decode the JWT token and from that get the "sub" - which is the GUID for the user in question from the DB. I doubt this is the standard manner of grabbing the user information from Identity. Is it?

**Comment by Rick-Anderson** [comment]
This article is limited to [Google external login setup in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins)

You need to read and understand Identity topics.

> How do I get the user info in server controllers after login?

see https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity#layout-and-authentication-flow-changes
which I mentioned on my first response

**Comment by tabinnorway** [comment]
I am so sorry for being a complete idiot here, but I can't see anywhere in any of the articles anything about server-side controller user information retrieval. So far in my developer life I have used Windows auth, and when I do, and I decorate my server controllers with [Authorize], in the controller I will have a User from which I can get information about the logged in user. I can't see anything in these articles about anything of that kind. So, forget all about Blazor, this is not a question about Blazor at all. It is a question about a WebAPI controller where you sign in with Google auth, and get a JWT token as a response from Google.

Assume I am using Postman (not a Blazor app) to access the WeatherController endpoint, how can I, in the WatherController, find the email that I logged in to google with, from the incoming Request? Currently I decode the JWT token my self, grab the user GUID out of the sub part of the JWT token, and do a lookup in the DB, which works. What I wonder about is if there is not a more "direct" way of doing this. I have been looking through all the documentation about Microsoft Identity, and I am not finding anything about this.

I would, for example, think that userManager.GetUserAsync( <claims stuff> ) would do something sensible, but it returns null.

Again, sorry for being a complete idiot here, but I find this to be overly obfuscated in Microsoft Identity. I have created a number of Golang servers using OAuth and Google auth, and these are straightforward, and I expected Microsoft Identity to be relatively straightforward too, but it is clearly a significant difference in how to handle this on the server depending on which method of auth you use.

**Comment by tabinnorway** [comment]
For the record - this is the answer:

In the controller constructor, inject UserManager<ApplicationUser>

Whenever you need to get the logged in user, call (or similar)
var user = await _userManager.FindByIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty);

It is surprising that the UserManager.GetUserAsync doesn't return a user, failing the "last surprise" principle.
