### ISSUE TITLE
Scaffolding a controller fails (Visual Studio Pro 17.4.1)

### ISSUE THREAD

**Issue by matthias-glubrecht** [dotnet/AspNetCore.Docs#27730]
In the instructions it said that if the scaffolding fails the first time, you should try it again. It didn't, and I tried multiple times.
I uninstalled and reinstalled the **Microsoft.VisualStudio.Web.CodeGeneration.Design** NuGet package (it was Version 7.0.0 before and after) in the package manager. Doing so must have installed some required dependencies.
After that, the scaffolding step worked for me.
Thanks to @[cokietech ](https://github.com/cokietech)who suggested it on [this page](https://github.com/dotnet/Scaffolding/issues/1540).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @deepchoudhery
