### ISSUE TITLE
Provide information on where secrets are stored on linux

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/AspNetCore.Docs#27748]
This page needs to explain where the secret manager stores secrets by default on linux (and other OSses as well I guess).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#set-multiple-secrets)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
That is actually explained a bit further up on the very same page :)
See [https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#how-the-secret-manager-tool-works](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-6.0&tabs=windows#how-the-secret-manager-tool-works)

**Comment by Rick-Anderson** [comment]
Danke @Ducki

**Comment by atrauzzi** [comment]
Ah nice!  Thank you, I obviously missed it. :stuck_out_tongue_winking_eye:
