### ISSUE TITLE
When renaming .dll to .x adjustment to web.config is required

### ISSUE THREAD

**Issue by edgett** [dotnet/AspNetCore.Docs#27741]
1. Rename wasm .dll to .blazor in webDeploy.zip
2. Deploy to App Service with az webapp deploy
3. Browse to web app: HTTP 404 on .blazor files (the ones renamed in the first step)

This happened on one of two App Services. On App Service A the renamed files are returned. The other, App Service B, HTTP 404 when attempting to get the renamed files. 

To resolve this I adjusted the web.confg section configuration/system.webServer/staticContent and replaced .dll with .blazor

Original staticContent in web.config:
```
 <staticContent>
      <remove fileExtension=".blat" />
      <remove fileExtension=".dat" />
      <remove fileExtension=".dll" />
      <remove fileExtension=".json" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dll" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
    </staticContent>
```
Updated staticContent in web.config:
```
 <staticContent>
      <remove fileExtension=".blat" />
      <remove fileExtension=".dat" />
      **<remove fileExtension=".blazor" />**
      <remove fileExtension=".json" />
      <remove fileExtension=".wasm" />
      <remove fileExtension=".woff" />
      <remove fileExtension=".woff2" />
      <mimeMap fileExtension=".blat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".blazor" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".dat" mimeType="application/octet-stream" />
      <mimeMap fileExtension=".json" mimeType="application/json" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
      <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
      <mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
    </staticContent>
```

My only idea for the cause of this is: App Service B (not working) was set to runtime .net 5 runtime. App Service A (working) was set to runtime 6. In my case I don't care about this because the app service is hosting wasm files only. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
### ***We're back!*** ⛏️😄 

Hello @edgett ... Yes, I think it's fine for us to call out in this section that the change should be made. I don't believe that there's any reason for the framework to make any automatic adjustments to the `web.config` file for any latter version (6.0, 7.0), so I think we should just call this out at the bottom of the section using generic language that won't focus on any particular server. However, we can have the IIS example in place. I'll take care of this right now and ping u on the PR. Leave this open. It will close automatically when the PR merges.
