### ISSUE TITLE
Broken Liink; ASP.NET Core Blazor Server with Entity Framework Core (EF Core)

### ISSUE THREAD

**Issue by tim-elmer** [dotnet/AspNetCore.Docs#27756]
Link to `https://github.com/dotnet/blazor-samples/blob/main/6.0/BlazorServerEFCoreSample/Pages/Index.razor` is broken, should probably be `https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorServerEFCoreSample/Pages/Index.razor`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EF Core)](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Thanks @tim-elmer ... It's missing a URL segment (`BlazorServerDbContextExample`). I'll fix it right now.
