### ISSUE TITLE
Migrating the ContosoUniversity application from .NET 5 to .NET 6 ASP.NET MVC

### ISSUE THREAD

**Issue by LayersOfAbstraction** [dotnet/AspNetCore.Docs#27750]
Hi guys, thanks for accepting my previous PR. I have a bunch of ideas that I will separate into each issue.

In regards to my attempt to migrate the MVC doco from .NET 5 to .NET 6, I see a couple of options. 

* We could create the whole ContosoUniversity sample solution app from scratch which would make developing it probably easier and call it say '6cu'.

* Or we could slowly migrate the application `cu` at `aspnetcore\data\ef-mvc\intro\samples\cu` from .NET 2.2 to .NET 6 but it may mean wiping out some previous work. I think the first approach may be the better approach just so the previous contributions are preserved. What are your thoughts, on upgrading CU to .NET6, please?

# Software versions

* [ ] .NET 6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67d4c57d-4eb1-71fe-6587-b9967ad1b445
* Version Independent ID: 8f0488f1-adc0-b42c-9549-b4028d4317d6
* Content: [ASP.NET Core MVC with EF Core - tutorial series](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [my previous response](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+author%3ALayersOfAbstraction+)
