### ISSUE TITLE
Where's the map?

### ISSUE THREAD

**Issue by AndrewBS42** [dotnet/AspNetCore.Docs#27753]
For people trying to learn, the Start Here page (e.g. https://learn.microsoft.com/en-us/aspnet/core/?view=aspnetcore-7.0)
has links to the start of courses on...
- Create an ASP.Net Core App
- Crete your first Web UI
- Create your first Web API
- Create your first real-time web app

But there's no explanation on that page of what those things actually are.  So I'm not sure which one to start with.
And if I click through to the linked pages, I don't find any explanation there, either.
The linked pages launch into the building and instructing without telling you where you'll wind up, why you want to wind up there, or where you can go from there when you're done.

Cool, I can follow these instructions to build one of these, or one of those...
But exactly what are these?  and what are those?  and how do they fit together?

True, if I already know what a Web API is and why I want one, then the current pages are good, because they don't "waste my time" with stuff I don't need to read.  But there are those of us who missed the whole web revolution.  We want to learn, and want to understand.  We'll build the Legos following your instructions but we won't know what to do with them once we have them.
The instructions that are there are really good, and the Legos they build are quite fancy.  But we need the map to find out how they best fit together.

Where's the map?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
For UI's, try https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui
