### ISSUE TITLE
learn  .NET

### ISSUE THREAD

**Issue by Jerry2108** [dotnet/AspNetCore.Docs#27757]
[Nhập phản hồi vào đây]

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho learn.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://learn.microsoft.com/vi-vn/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Jerry2108 ... Your issue doesn't really have an ask, so I'll close this as possibly just a mistake or a test. By the way, it's best if you open new issues from the bottom of the **English - US** topic.
