### ISSUE TITLE
Multiple Policies in Authorize attribute

### ISSUE THREAD

**Issue by dajma00** [dotnet/AspNetCore.Docs#27761]
The page shows the following example for authorize:
`[Authorize(Policy = "AtLeast21")]`

But it does not explain what happens if multiple policies are applied, like:
`[Authorize(Policy = "AtLeast21, IsFemale")]`

What is the behavior in this case? Are the two policies ANDed or ORed?

Docs should be clear in this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by captainsafia** [comment]
> What is the behavior in this case? Are the two policies ANDed or ORed?

The `Authorize` attribute doesn't support taking multiple policies via a comma-separated list. This invocation is likely to lead to an exception because the `AuthorizationService` will try to look for a policy with the name "AtLeast21, IsFemale". The recommended approach here is to use two `Authorize` attributes on the endpoint. The policies in each attribute will be combined at the end.

IMO, the docs are clear about `Authorize` only accepting a policy name. We might want to consider adding a code sample that showcases applying multiple attributes to OR the applied policies together but I think that's likely to make the samples more complicated than needed.

**Comment by 0-gravity** [comment]
> > What is the behavior in this case? Are the two policies ANDed or ORed?
> 
> The `Authorize` attribute doesn't support taking multiple policies via a comma-separated list. This invocation is likely to lead to an exception because the `AuthorizationService` will try to look for a policy with the name "AtLeast21, IsFemale". The recommended approach here is to use two `Authorize` attributes on the endpoint. The policies in each attribute will be combined at the end.
> 
> IMO, the docs are clear about `Authorize` only accepting a policy name. We might want to consider adding a code sample that showcases applying multiple attributes to OR the applied policies together but I think that's likely to make the samples more complicated than needed.

Any example to multiple policies with "OR" combination?

**Comment by qgshaha** [comment]
Any example to multiple policies with "OR" combination please?

**Comment by rodionboroviy** [comment]
Agree. Would be nice to have more examples.
Also. The documentation says: "If multiple policies are applied at the controller and action levels, all policies must pass before access is granted"
`[Authorize(Policy = "AtLeast21")]
public class AtLeast21Controller2 : Controller
{
    [Authorize(Policy = "IdentificationValidated")]
    public IActionResult Index() => View();
}`

But what if I want to override the controllers policy for one endpoint and have multiple ORed policies on it:
`[Authorize(Policy = "AtLeast21")]
public class AtLeast21Controller2 : Controller
{
    public IActionResult Index() => View();

    [Authorize(Policy = "AtLeast21")]
    [Authorize(Policy = "IdentificationValidated")]
    public IActionResult Another() => View();
}`

**Comment by tsawyer999** [comment]
Hello,

Did someone achieved it and would like to share the solution? :)

Thank you

**Comment by tsawyer999** [comment]
I cannot paste the code but here what we did to achieve it:

1. Create a class that implement IAuthorizationRequirement
2. In HandleRequirementAsync method, split the requirement.Action by "," then validate each action with claims from user role context.User.GetRoleClaims
3. Finally, register the implemented class of IAuthorizationRequirement.
5. .NET will call HandleRequirementAsync for each end-point with a decorator Authorize(Policy="policy1, policy2")

Good luck everyone!

**Comment by IseduardoRezende** [comment]
This lines saved my life haha

```
public class DynamicPolicyProvider : DefaultAuthorizationPolicyProvider
{
    public DynamicPolicyProvider(IOptions<AuthorizationOptions> options) : base(options) { }

    public override async Task<AuthorizationPolicy?> GetPolicyAsync(string policyName)
    {
        var policy = await base.GetPolicyAsync(policyName);

        if (policy is not null)
            return policy;

        // For multiple policies using (OR) logic
        if (policyName.Contains(','))
        {
            var features = policyName.Split(',').Select(f => f.Trim());
            var policyBuilder = new AuthorizationPolicyBuilder();

            policyBuilder.AddRequirements(new FeatureRequirement(features));
            return policyBuilder.Build();
        }

        return policy;
    }

// Inside Program main
builder.Services.AddSingleton<IAuthorizationPolicyProvider, DynamicPolicyProvider>();
```

Now you can do this for example:

```
[HttpPost]
[Authorize($"{nameof(FeatureCodes.ControllerCreation)},{nameof(FeatureCodes.ControllerEdition)}")] 
[ProducesResponseType(typeof(SuccessResult<ReadReceiverDTO>), StatusCodes.Status200OK)]
//....
```

The handler used by the policy builder is:

```
  protected override async Task HandleRequirementAsync(
     AuthorizationHandlerContext context,
     FeatureRequirement requirement)
 {
     //Some code here...

     foreach (var featureCode in requirement.FeatureCodes)
     {
         var hasPermission = // your custom logic here
         
         if (hasPermission)
         {
             context.Succeed(requirement);
             return; // Just return if one policy was successful
         }
     }
 }
```
