### ISSUE TITLE
.NET 7: Update "Migrate from ASP.NET to ASP.NET Core" and reconcile with incremental 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#27786]
Per https://github.com/dotnet/systemweb-adapters/issues/98

Reconcile this doc with the [Incremental ASP.NET to ASP.NET Core migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/overview) series.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @isaacrlevin
* Microsoft Alias: **riande**

---
[Associated WorkItem - 60644](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60644)

**Comment by sebastienlabine** [comment]
In the migration tutorial there seems to miss a closing bracket under the Update package references section https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio

### Update package references
```
<ItemGroup>
-    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="6.0.9" />
-    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.9">
-    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="6.0.9" />
-    <PackageReference Include="System.Net.Http.Json" Version="6.0.0" />
+    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="7.0.0" />
+    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">   <---- Bracket not close Not closed
+    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="7.0.0" />
+    <PackageReference Include="System.Net.Http.Json" Version="7.0.0" />
</ItemGroup>
```

**Comment by Rick-Anderson** [comment]
> In the migration tutorial there seems to miss a closing bracket under the[ Update package references section](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio#update-package-references)
> 
> ### [Update package references](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio#update-package-references)
> ```

How about a screen shot with a callout? I don't see anything.

**Comment by sebastienlabine** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/8888846/208698915-93bdfd8d-0e88-46d5-acd2-346473df801d.png">
