### ISSUE TITLE
This section of the documentation doesn't seem to be correct:

### ISSUE THREAD

**Issue by piersb** [dotnet/AspNetCore.Docs#27782]
This section of the documentation doesn't seem to be correct:

```
Configure the published API name

Notice the name of the API is named WeatherAPI; however, we would like to call it Weather Forecasts. Complete the following steps to update the name:
Add the following to Program.cs immediately after servies.AddSwaggerGen();
C#

Copy
builder.Services.ConfigureSwaggerGen(setup =>
{
    setup.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title = "Weather Forecasts",
        Version = "v1"
    });
});
Republish the ASP.NET Core web API and open the Azure API Management instance in the Azure portal.
Refresh the page in your browser. You'll see the name of the API is now correct.
```

If I follow the steps given, the display name in Azure Portal does not change.

<img width="1557" alt="Screenshot 2022-11-29 at 16 36 51" src="https://user-images.githubusercontent.com/1419092/204588380-a107c972-5c0a-4f3d-a2fb-f480e1dffa59.png">

However, if I activate SwaggerUI on Azure and look at the information there, I can see that the name of the API has been correctly changed.

<img width="791" alt="Screenshot 2022-11-29 at 16 38 10" src="https://user-images.githubusercontent.com/1419092/204589068-0fa73aaa-4edd-4cf1-bbef-810f5147ae6f.png">

Tested on: 
MacOS 12.6
Visual Studio for Mac 17.4

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by Ducki** [comment]
The SwaggerUI and its configuration have nothing to do with any Azure API service. The configuration you're describing is only relevant to the Swagger UI.
