### ISSUE TITLE
Concurrency handlng in example seems incorrect

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/AspNetCore.Docs#27783]
In this example the implementation of `Edit.cshtml.cs` contains

```
catch (DbUpdateConcurrencyException)
// Etc...
```

However the `Customer` model does not configure a concurrency token, and there is nothing in the EF documentation on [concurrency handling](https://learn.microsoft.com/en-us/ef/core/saving/concurrency?source=recommendations&tabs=data-annotations) to suggest that if you don't define a property as a concurrency token that anything is used automatically.

Which suggests that if you don't define a concurrency token then the 'last write wins', potentially losing any changes made in another concurrent write. In which case the `catch (DbUpdateConcurrencyException)` in the example will never be executed and serves no purpose.

Is this correct or is there some key documentation missing about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 44979](https://dev.azure.com/msft-skilling/Content/_workitems/edit/44979)

**Comment by Rick-Anderson** [comment]
That's scaffolder generated code. It should be documented in https://learn.microsoft.com/en-us/ef/core/ - if not, open an issue there and link back here.

**Comment by Neutrino-Sunset** [comment]
How can it be using scaffolded code? The example is using the in-memory database and I don't see how the in-memory database can be scaffolded since the database doesn't exist until the EF model code is executed, it's a chicken and egg situation.

If it is scafolded code I would have to guess that it's scaffolded code copied out of one project and then incorrectly hacked into this example code.

At any rate I think this project should take responsibility for the quality of its own example code.

**Comment by Rick-Anderson** [comment]
see https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0#review-concurrency-exception-handling

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-7.0

**Comment by Rick-Anderson** [comment]
@Neutrino-Sunset did you review https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0#review-concurrency-exception-handling

that tells you how to verify the code

**Comment by Neutrino-Sunset** [comment]
I've worked it out and created a pull request that better explains the concurrency support in the scaffolded code.
