### ISSUE TITLE
Specifying minimum version of packages would have save me half a day's work

### ISSUE THREAD

**Issue by marcslevesque** [dotnet/AspNetCore.Docs#27784]
Even though my project is running on dot net core 3.1 and I selected the dot net 3.1 version of the page, when mimicking the code on the page I was getting the error as shown here: https://stackoverflow.com/questions/71971570/system-typeloadexceptionmethod-committransactionasync-in-type-microsoft-ent

For easier reference, the error is: System.TypeLoadException: 'Method 'CommitTransactionAsync' in type 'Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTransactionManager' from assembly 'Microsoft.EntityFrameworkCore.InMemory, Version=3.1.21.0, Culture=neral, PublicKeyToken=ad' does not have an implementation.'

I also had to update the version of Microsoft.EntityFrameworkCore.InMemory to version 5 (.0.17) to overcome the error.  I would have expected the code on the page to work with package version 3.1.x, unless specified otherwise, which it is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1&source=docs)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/EntityFramework.Docs/issues/4165#issuecomment-1330979273

**Comment by marcslevesque** [comment]
@Rick-Anderson If I develop anything new, I use the newer frameworks, but unfortunately not every employer is willing to pay their developers to update all existing applications to the newer frameworks every three years.
