### ISSUE TITLE
Incorrect documentation (Cloud authentication with Azure Active Directory B2C in ASP.NET Core)

### ISSUE THREAD

**Issue by JandosKh** [dotnet/AspNetCore.Docs#27793]
This page has several issues.
1) The project created with given instruction has no Startup class, but further instructions mentions that class.
2) Configuration names without user flow ("AzureB2C") is different from with user flow ("AzureAdB2C").
3) For user flows it says:
    For Domain, use the domain of your Azure AD B2C tenant.  (Actual value shown is "fabrikamb2c.onmicrosoft.com")
    For Instance, use the domain of your Azure AD B2C tenant. (Actual value shown is "https://fabrikamb2c.b2clogin.com")
    The values shown are different; but instruction texts are exactly the same.
4) Why should we put TenantId in appsettings.json, if we don't need it?

ADDITION (12/03/2022)
5) We need more clarity on registering app on Azure AD B2C. Specifically, there are two check boxes:
    - Access tokens (used for implicit flows)
    - ID tokens (used for implicit and hybrid flows)
    When should those check boxes be checked, and when not? If I have traditional ASP.NET Core web app,
    then should we check ID tokens, or should both be cleared out, etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-6.0)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

---
[Associated WorkItem - 58144](https://dev.azure.com/msft-skilling/Content/_workitems/edit/58144)

**Comment by damienbod** [comment]
@Rick-Anderson  @CamSoper I could do a PR for this if you want

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson @CamSoper I could do a PR for this if you want

Fantastic!
