### ISSUE TITLE
.NET 6 Migration Including Blazor

### ISSUE THREAD

**Issue by fceci90** [dotnet/AspNetCore.Docs#27800]
In the migration to .NET 6 documentation it states:

> To adopt all of the [new 6.0 features for Blazor apps](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-5.0#blazor), we recommend the following process:
> Create a new 6.0 Blazor project from one of the Blazor project templates. For more information, see [Tooling for ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-5.0).
Move the app's components and code to the 6.0 app making modifications to adopt the new 6.0 features.

This documentation seems to fail to address applications that include Blazor within it. In my case, I have a very large MVC application that also includes Razor pages for Identity (started out in .NET Core 2.2 and migrated to 3.1) which I have added Blazor to in .NET Core 3.1.

With .NET Core 3.1 reaching end of life, does this mean that when an application is updated to .NET 6 it won't be able to take advantage of any new updates to Blazor?

Link to documentation [here](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#blazor).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bec61f9-7298-170d-5e12-abb27cde584e
* Version Independent ID: 27a43e3f-149d-9058-f937-0eda1d6dd4f2
* Content: [Migrate from ASP.NET Core 5.0 to 6.0](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#am6)
* Content Source: [aspnetcore/migration/50-to-60.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fceci90 ... Migrating to the 6.0 shared framework will brings in all of the features across these app models. You'll get all of the Blazor 6.0 release feature updates along with all of the MVC/Razor Pages 6.0 feature updates. Just make sure that you update all packages to 6.0.
