### ISSUE TITLE
AddEndpointsApiExplorer() explanation

### ISSUE THREAD

**Issue by pkcodes92** [dotnet/AspNetCore.Docs#27807]
I had see the documentation for the Minimal APIs while looking for the ASP.NET Core 7.0 and reading through the necessary documentation seeing the new features and upgrades. The code snippet mentioned in the OpenAPI support for minimal API apps here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0 had the following line:

```cs
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
```
This documentation would be required because as a developer:

1. I would be interested to know what the extension method would do
2. It could be helpful to show the output of the method AddEndpointsApiExplorer

**Comment by Rick-Anderson** [comment]
Can you create an issue from the  ***English-US*** topic page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

See [Writing Useful Github Issues](https://upthemes.com/blog/2014/02/writing-useful-github-issues/) and the **What Not To Do** section.

**Comment by Ducki** [comment]
Possibly duplicate of #25685

**Comment by wadepickett** [comment]
@pkcodes92, could you clarify which document this issue is targeted for?  Rick provides instructions above on how to create an issue on a specific topic so that information is included.   We have a number of topics on Minimal API, including ones that call out what you are asking for.  I'm trying to guess what you intended but I'm not spotting it.

**Comment by Rick-Anderson** [comment]
> The code snippet mentioned in the OpenAPI support for minimal API apps here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0 had the following line:

**Comment by pkcodes92** [comment]
@wadepickett, and @Rick-Anderson thanks for the guidance and I think this issue can be closed. I will go ahead and close it out!
