### ISSUE TITLE
This page should be broken up

### ISSUE THREAD

**Issue by frank-hoffman** [dotnet/AspNetCore.Docs#27811]
This is a really long page that I think you should consider breaking up. As a developer reading this it's hard to keep my place when the page has a 3-hour read time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @frank-hoffman ... Thanks for the feedback. I'll mark this on my tracking issue for the next major round of updates to this topic. Yes, I agree with you. We tend to add little bits at a time as we go release-to-release. Slowly over time, it gets too long. I'll work on it probably in 23H1.
