### ISSUE TITLE
Clarify if a package is needed to use the `AddProblemDetails` method

### ISSUE THREAD

**Issue by nathanpovo** [dotnet/AspNetCore.Docs#27812]
The documentation section on `ProblemDetals` mentions using a method called `AddProblemDetails` but that method does not exist in the default packages of a web API. The documentation needs to clarify what package needs to be installed to be able to use this method.

At the bottom of the page, the NuGet package [Hellang.Middleware.ProblemDetails](https://www.nuget.org/packages/Hellang.Middleware.ProblemDetails/) is mentioned as an **alternative** to the code in the rest of the page. However, I found [this](https://andrewlock.net/handling-web-api-exceptions-with-problemdetails-middleware/) article that says the aforementioned package **has** to be installed to use the `AddProblemDetails` method.

[This](https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-7.0#problem-details-service) documentation page also references the `AddProblemDetails` method without specifying what is needed to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#pds7)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Ducki** [comment]
The `AddProblemDetails` method and all with it is new and included by default in ASP.NET Core **7**.
I just created a new web app to confirm.

Both docs pages you referenced are for version 7, thus it is included by default and therefore any mention of package installation is not necessary. The blog article you linked is from 2020, so before .NET 7 was released.

**Comment by nathanpovo** [comment]
My bad.

Wasn't aware that there was such a big difference from version 6 to version 7.

Apologies for any inconvenience caused.

**Comment by Rick-Anderson** [comment]
[New problem details service in 7.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0#new-problem-details-service)
