### ISSUE TITLE
Not enough reference regarding pubxml files

### ISSUE THREAD

**Issue by EricWu91** [dotnet/AspNetCore.Docs#27815]
There's not enough reference documenting the .pubxml files!

https://stackoverflow.com/questions/21419219/is-the-meaning-of-all-the-tags-properties-usable-in-a-publish-profile-pubxml

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
All that information is in the doc or in https://github.com/dotnet/sdk/tree/main/src/WebSdk
