### ISSUE TITLE
Detecting download completed

### ISSUE THREAD

**Issue by Ciders** [dotnet/AspNetCore.Docs#27826]
Great Article.

It would be great if there was some way to know when a download has completed.

Thanks

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
