### ISSUE TITLE
Document limitations of Blazor custom elements

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#27837]
We don't support child content or templated components with Blazor custom elements.

@MackinnonBuck @SteveSandersonMS Are there any other limitations of Blazor custom elements that we should document?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The PR is up. I'll hold off on merging until we hear back from @MackinnonBuck and/or @SteveSandersonMS

**Comment by MackinnonBuck** [comment]
While it's shown in the example already linked in the docs, it might be worth calling out that complex properties (JSON-serializable types as well as `EventCallback`s) _can_ be used as parameters for Blazor components registered as custom elements. However, values for complex cannot be specified through the use of HTML attributes. Instead, you set properties directly on the element's JavaScript object. See [this](https://github.com/dotnet/aspnetcore/blob/9767efb81faaa3562841c9192e00a4c8f94a4a48/src/Components/test/testassets/BasicTestApp/wwwroot/js/customElementTests.js#L3) as an example.
