### ISSUE TITLE
Incorrect documentation for Mac

### ISSUE THREAD

**Issue by piersb** [dotnet/AspNetCore.Docs#27835]
The documentation to install CodeGeneration and EntityFrameworkCore for the Mac is incorrect. Any command-line attempts to install the latest 7.0.0 version fail with the following error message:

```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design -v 7.0.0-*
zsh: no matches found: 7.0.0-*
```

The installation works correctly without the "-*" on the end 

```
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design -v 7.0.0
  Determining projects to restore...
  Writing /var/folders/t0/j2zh5hkj5wd91nrk4q5n1mz80000gn/T/tmpldvwRW.tmp
...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @piersdb.  You are correct.  It was previously set up for 7.0 preview versions.  It should be updated.  Will get it fixed.

**Comment by wadepickett** [comment]
Thanks @piersdb.  You are correct.  It was previously set up for when 7.0 was in preview.  It should be updated.  Will fix.
