### ISSUE TITLE
Min Web API: Update for latest Postman & POST Dog should show a return of 201, not 200

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [dotnet/AspNetCore.Docs#27839]
The code returns `Created` but the screenshot shows a 200, not a 201. When I run it locally, I see the correct 201. This is the image I am referring to:

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api/_static/post2.png?view=aspnetcore-7.0

Additional tasks added by wadepickett:
The Postman app has changed somewhat since this tutorial was last updated.  Review and update all instructions and screenshots for Win and MacOS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
The screenshot needs to be corrected.  Thanks @simonkurtz-MSFT!

**Comment by simonkurtz-MSFT** [comment]
Thank you so much, Wade! Otherwise, perfect article!
