### ISSUE TITLE
What does it mean by word "small file" or "large file"?

### ISSUE THREAD

**Issue by AmirHosseinKarimi1997** [dotnet/AspNetCore.Docs#27847]
[Enter feedback here]
What does "small files" mean in this article?
and also "large files"?
If we are dividing them by size, I think it is not clear what a small file is or what a large file is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-7.0#file-upload-scenarios)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 55818](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55818)

**Comment by Tratcher** [comment]
Benchmarking is the correct approach, ensuring your approach can handle the file sizes your application expects. Pay attention to memory, CPU, disk, and database usage. What's acceptable will depend heavily on the resources available to your app (e.g. the hardware spec).

While we can't give you specific boundaries about what is small vs large for your deployment, we can document AspNetCore's related defaults. E.g. [FormOptions](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Features/FormOptions.cs).
- By default, HttpContext.Form does not buffer the entire request body (BufferBody), but it does buffer any multipart form files included.
- MultipartBodyLengthLimit is the max size for buffered form files, defaults to 128MB.
- MemoryBufferThreshold indicates how much to buffer files in memory before transitioning to a buffer file on disk, defaults to 64KB.

From this perspective, anything over 64KB is considered a large file by default and dumped to disk to avoid consuming too much application memory. If your application has more memory available, you may want to raise this value to avoid the perf costs of buffering to disk.

**Comment by AmirHosseinKarimi1997** [comment]
Thank you so mush for the response 👍 .

**Comment by Rutix** [comment]
@Rick-Anderson sorry for my nonreaction. I have been busy at work and because of the holidays. If there are any other questions on this article don't hesitate to mention me in the future :). I will try to react more quicker.
