### ISSUE TITLE
Custom WebApplicationFactory doesn't work correctly for overriding Configure Method in ConfigureWebHost

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/AspNetCore.Docs#27844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,
I've created a custom [WebApplicationFactory](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs) and in this factory I override [ConfigureWebHost](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/WebApplicationFactoryWithHost.cs#L31) and inner this `WebHostBuilder` I have a [Configure](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/WebApplicationFactoryWithHost.cs#L45) for extending startup configuration. But my problem is my [Startup Configure method](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/SampleMiddlewareTests.cs#L40) doesn't call at all, and I get error because my startup Configure didn't call at first and when I remove [override Configure](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/WebApplicationFactoryWithHost.cs#L45) method in CustomFactory it works. I don't know Why?

Also, I defined a custom [CreateHostBuilder](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/WebApplicationFactoryWithHost.cs#L52) here.

### Expected Behavior

I want my [override Configure](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/WebApplicationFactoryWithHost.cs#L30) method run after [startup Configure method](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/master/src/Test/SampleMiddlewareTests.cs#L41)

### Steps To Reproduce

For producing error, just run [this test](https://github.com/mehdihadeli/WebApplicationFactoryWithHost-Sample/blob/bug/src/Test/SampleMiddlewareTests.cs#L30).

### .NET Version

7.0.0

### Anything else?

*** EDIT by @Rick-Anderson  to add meta-data**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-6.0&branch=pr-en-us-23615)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 50838](https://dev.azure.com/msft-skilling/Content/_workitems/edit/50838)

**Comment by halter73** [comment]
Specifically, once we add the `IStartupFilter` docs back since those still work, we should probably link to it from our `WebApplicationFactory` docs. https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#customize-webapplicationfactory
