### ISSUE TITLE
Extra 'b' character fix does not show in documentation

### ISSUE THREAD

**Issue by RichardPoes** [dotnet/AspNetCore.Docs#27855]
Minor issue here, but in the example of [this](blazor-samples/6.0/BlazorSample_WebAssembly) section (the section titled "Provide custom content when content isn't found"), there is a random `b` being shown. 
This comes from the example listed [here](https://github.com/dotnet/blazor-samples/blob/main/6.0/BlazorSample_WebAssembly/routing/App2.razor), but there it has been fixed 2 months ago. 
This raises the question why the fixed doesn't show up in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RichardPoes ... I'll try updating the date on the article to see if the build system will pull the updated file.

**Comment by guardrex** [comment]
Actually, no. I see the problem. It was updated in the 6.0 sample but not in the 7.0 sample ...

https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorSample_WebAssembly/routing/App2.razor#L7

... so I'll fix it there first. Then, I'll change the date of the topic to grab the file.

**Comment by RichardPoes** [comment]
Well that was quick! Thanks!
