### ISSUE TITLE
Version of Microsoft.AspNetCore.Components.Webview.WindowsForms matters.

### ISSUE THREAD

**Issue by mbaugus** [dotnet/AspNetCore.Docs#27852]
With the current latest version 7.0.49 no controls are available in the toolbox,  Have to use 6.0.547 to follow this tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Version Independent ID: b0b88d48-74df-8dc4-446d-121e65b552ab
* Content: [Build a Windows Forms Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/windows-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mbaugus ... Please open this for the product unit because the `BlazorWebView` should be there ...

https://github.com/dotnet/maui/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27852
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
