### ISSUE TITLE
Model Validation should mention `ModelState.AddModelError`

### ISSUE THREAD

**Issue by jfoshee** [dotnet/AspNetCore.Docs#27861]
`aspnetcore/mvc/models/validation.md` may be the first page someone reads about validation. Yet it seems to miss the simplest method to return a validation error to the user (where built-in attributes fall short): [ModelState.AddModelError](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.modelstatedictionary.addmodelerror).

This method makes it particularly easy, for example, if the validation needs to check a database

```
if (dbContext.Records.Any(record => record.Name == model.Name))
{
    ModelState.AddModelError("Name", "The Name is already in use.");
    return View(model);
}
```

The existing documentation leads the reader to believe that creating a custom `ValidationAttribute` or implementing `IValidatableObject` are the only alternatives to built-in attributes.

Thanks for your consideration!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 64069](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64069)

**Comment by Rick-Anderson** [comment]
@jfoshee you're right. It should also show how to add a model error to the model, not the property:

```
ModelState.AddModelError(string.Empty, "My error message");
```
