### ISSUE TITLE
Change the title, footer, and menu link in the layout file

### ISSUE THREAD

**Issue by sf1984** [dotnet/AspNetCore.Docs#27866]
Not clear where to copy the part
<title>@ViewData["Title"] - Movie App</title>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Part 3, add a view to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
You don't copy, you update the markup.
Check the finished sample
