### ISSUE TITLE
Add a JS Blazor Hybrid static file example

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#27862]
Per https://github.com/dotnet/AspNetCore.Docs/pull/27854#discussion_r1042669154.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Version Independent ID: 1b14a096-b1a3-2270-e57f-8238a25601cd
* Content: [ASP.NET Core Blazor Hybrid static files](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/static-files?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 ... WRT ...

> ... we should be showing how to load some JavaScript as a static web asset.

Cross-ref: https://github.com/dotnet/AspNetCore.Docs/pull/27854#discussion_r1042669154

I didn't find anything tricky about it for an example/demonstration. I dropped a JS file into `wwwroot` and was able to load a module with the expected use of `./` notation ...

```csharp
module = await JS.InvokeAsync<IJSObjectReference>("import", "./scripts.js");
```

... along the lines of our existing *JavaScript isolation in JavaScript modules* coverage.

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-7.0#javascript-isolation-in-javascript-modules

I focused on that for my test because loading JS module/lib seems like it would be a common scenario (i.e., a dev needs to use a 3rd party JS lib in their Hybrid app's Razor components).

#### *1. Is that what you'd like the Hybrid static files article to call out (in the form of a fully-working example)?* 👂 

*Or, what would you like to show for* "***some JavaScript***"?

Side Note: There's no problem using collocated JS either. My app was quite happy 😄 with the following for some `Counter` component-based JS ...

```csharp
module = await JS.InvokeAsync<IJSObjectReference>("import", "./Pages/Counter.razor.js");
```

#### *2. That's not directly related to your original ask, but should I mention it in passing (probably a one-liner) with a cross-link to the appropriate Blazor section?* 👂 

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component

**Comment by danroth27** [comment]
>  Is that what you'd like the Hybrid static files article to call out (in the form of a fully-working example)? Or, what would you like to show for "some JavaScript"?

Yup. My [comment](https://github.com/dotnet/AspNetCore.Docs/pull/27854#discussion_r1042669154) was in the context of https://github.com/dotnet/AspNetCore.Docs/issues/27819. I opened that doc issue because we had a user who ran into a bunch of problems trying to load some JS modules from a .NET MAUI Blazor app when they had put their host page in a sub directory of wwwroot. If you put your host page in the root, then everything should work fine.

> Should I mention it in passing (probably a one-liner) with a cross-link to the Blazor section that describes it?

Yeah, I think that would be helpful. From your example, it looks like we also treat the paths to collocated JS files as logical subpaths of wwwroot, which isn't immediately obvious and is worth calling out.
