### ISSUE TITLE
Documentation for `user-jwts` mentions the `delete` command instead of `remove`

### ISSUE THREAD

**Issue by andychiare** [dotnet/AspNetCore.Docs#27870]
This documentation page mentions `delete` as an available command for `user-jwts` (e.g., `dotnet user-jwts delete 3ac99ee7 `). Actually, the correct command should be `remove` as per final release (e.g., `dotnet user-jwts remove 3ac99ee7 `).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f76a2aaf-732a-f686-343b-d811faa43d44
* Version Independent ID: f76a2aaf-732a-f686-343b-d811faa43d44
* Content: [Generate tokens with dotnet user-jwts](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-7.0&tabs=windows)
* Content Source: [aspnetcore/security/authentication/jwt-authn.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/jwt-authn.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 53179](https://dev.azure.com/msft-skilling/Content/_workitems/edit/53179)

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by andychiare** [comment]
> Thanks for reporting this. Any chance you could PR this? 

Done!
