### ISSUE TITLE
There is no definition of TodoItem on the page

### ISSUE THREAD

**Issue by Duke4848** [dotnet/AspNetCore.Docs#27901]
There is no definition of TodoItem on the page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Duke4848 ... It's in the sample app, which is cross-linked in the topic, at ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components/sample6.x/ViewComponentSample/Models/ToDoItem.cs

Leave this issue open. This is a topic that @Rick-Anderson manages. He'll be along in a bit to look at this issue and see if any work is required on the issue.
