### ISSUE TITLE
Document mistakes in the Dependency injection

### ISSUE THREAD

**Issue by liaosunny123** [dotnet/AspNetCore.Docs#27917]
There is a mistake in the section [Disposal of services](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0#disposal-of-services).
According to the define of Service3 , the expected output in the Index page is Service3: "Service3: IndexModel.OnGet, MyKey =" instead of "Service3: IndexModel.OnGet" which the document said.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 88860](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88860)

**Comment by postmeback** [comment]
I would like to take it up @Rick-Anderson

**Comment by Rick-Anderson** [comment]
> I would like to take it up @Rick-Anderson

Yes

**Comment by liaosunny123** [comment]
It is a simple mistake, and I post a pr. Hope that can help you learn about this mistake fast.
