### ISSUE TITLE
ASP.NET Core Identity for APIs

### ISSUE THREAD

**Issue by eeskildsen** [dotnet/AspNetCore.Docs#27913]
This page makes it sound like ASP.NET Core Identity is only for UIs, but it can be used for user management in an API too. Is it not recommended for APIs?

> ASP.NET Core Identity adds user interface (UI) login functionality to ASP.NET Core web apps. To secure web APIs and SPAs, use one of the following:
> 
> * [Azure Active Directory](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-protect-backend-with-aad)
> * [Azure Active Directory B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw) (Azure AD B2C)
> * [IdentityServer4](https://identityserver.io/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
correct

**Comment by eeskildsen** [comment]
The page seems a bit misleading, then; it says that Identity adds "user interface (UI) login functionality," and the next sentence recommends alternatives as if they're necessary for that reason. But Identity can be used in an API without a UI, too.

Is Identity being deprecated for APIs?

**Comment by Rick-Anderson** [comment]
Nope

**Comment by eeskildsen** [comment]
What about something like this?

Current:

> ASP.NET Core Identity adds user interface (UI) login functionality to ASP.NET Core web apps. To secure web APIs and SPAs, use one of the following:

Proposed:

> ASP.NET Core Identity can add login functionality to an ASP.NET Core web app or web API, but it isn't recommended for APIs because [reason]. To secure web APIs and SPAs, one of the following is recommended:

To make it more obvious that Identity does work with APIs.

**Comment by Rick-Anderson** [comment]
That's not what the security team wants.

**Comment by lamelyan** [comment]
@Rick-Anderson Could you add details as to why it's not recommended to use ASP.NET Core Identity for APIs?

**Comment by burakt91** [comment]
This pages also needs an example like "Using ASP.NET Identity on ASP.NET Core Web API", but instead, it redirects developers to a 3rd party commercial solution like Duende.
