### ISSUE TITLE
Bug in Blazor file upload sample code

### ISSUE THREAD

**Issue by Eelke76** [dotnet/AspNetCore.Docs#27924]
In the file `Pages/FileUpload2.razor` the line `files.Add(new() { Name = file.Name });` 
should be the first in the try block otherwise exceptions thrown by the `file.OpenReadStream`
are not reported because the UI lists the results only for what is in `files`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Eelke76 ... I'll make that update right now.

**Comment by guardrex** [comment]
Ok ... that lick'd IT. This particular code example is pulled in from the `blazor-samples` repo, so the change was made over there for each release version of the snippet sample app.

I'll change the date on this topic now to activate the code here in the built topic.

Thanks again for the fix suggestion, @Eelke76! 🚀
