### ISSUE TITLE
Docs Site Search Engine Favicon Caching

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/AspNetCore.Docs#27922]
Okay this is a weird one. 

Search Engine:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/14852843/208214128-c50a5de3-98bf-42c0-af09-f7e288b2fdde.png">

Browser:
<img width="98" alt="image" src="https://user-images.githubusercontent.com/14852843/208214180-ffacfaf8-b4f6-4f21-a4ce-fc85ea0ef759.png">

Notice how we have the default ASP.NET favicon in the search engine results (beside `learn.microsoft.com`). This _could_ be a bing caching issue, however I think it's more likely to be a config issue on the docs site.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Version Independent ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Content: [Work with images in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **taparik**

**Comment by guardrex** [comment]
@Rick-Anderson will need to open an internal issue on this one. He'll likely close this after that because it will be looked at and worked internally.

**Comment by guardrex** [comment]
Actually, @Rick-Anderson ... I think it best for me to put you on this one given that I have no capacity to take it further outside of a MS Docs feedback repo issue, and that ... along with DocFX issues ... has been a real ⚫ ***black hole*** ⚫ for me in the past 🙈😆. I don't even bother opening issues there any longer. It's a waste of 💰 *Gaurav's Treasure*&trade; 💰. An internal issue ... from ***you*** 😄 ... is the best bet imo if you want to proceed with this.

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/MicrosoftDocs/feedback/issues/3874
