### ISSUE TITLE
“Kestrel doesn't support HTTP/2 with TLS on macOS”

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/AspNetCore.Docs#27928]
Perhaps this information is out of date?

The page says
   “Kestrel doesn't support HTTP/2 with TLS on macOS” ...
   “You'll see the following error message when you attempt to start the gRPC server:”

On
   macOS Ventura 13.1,
I just created a new project (in Rider) from the template
   ASP.NET Core Web Application
of type
   gRPC Service

Then I ran it in the debugger and there seemed to be no problem.  Here is the console output:
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/yost/Desktop/fs/csharp/ASPGrpcService
```

Also, the code created by the template says this:
```
// Additional configuration is required to successfully run gRPC on macOS.
// For instructions on how to configure Kestrel and gRPC clients on macOS, visit https://go.microsoft.com/fwlink/?linkid=2099682
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c730b5f9-031e-beab-b838-6e2f8befde30
* Version Independent ID: 84ddcb67-03be-655c-470a-f43a5152606f
* Content: [Troubleshoot gRPC on .NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#unable-to-start-aspnet-core-grpc-app-on-macos)
* Content Source: [aspnetcore/grpc/troubleshoot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

---
[Associated WorkItem - 55680](https://dev.azure.com/msft-skilling/Content/_workitems/edit/55680)

**Comment by Rick-Anderson** [comment]
@daveyostcom thanks for bringing this to our attention.

**Comment by JamesNK** [comment]
> Kestrel doesn't support HTTP/2 with TLS on macOS

This is still true. @daveyostcom your app started without TLS.
