### ISSUE TITLE
It required some modifications to work with blazor server ... some instructions with build. in the start should be removed ... some instructions should be in the starup.cs not in program.cs

### ISSUE THREAD

**Issue by aldefrawy** [dotnet/AspNetCore.Docs#27939]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=server)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @aldefrawy ... 

> should be in the starup.cs

I think you're looking at the wrong version of the topic. Use the doc version selector to load an earlier version of the topic. `Startup.cs` was a 5.0 or earlier default project file; so if you're working in 5.0, set the doc version selector to 5.0. You'll get this topic version ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=server

... which will have the correct files indicated.

**Comment by aldefrawy** [comment]
I'm working on version 7.0

**Comment by aldefrawy** [comment]
I think you are right my project was on old version
Thanks for your explanations
