### ISSUE TITLE
ASP.NET Core Razor components overview - split out Blazor Custom Elements sections

### ISSUE THREAD

**Issue by timschwallie** [dotnet/AspNetCore.Docs#27931]
Blazor custom elements should have it's own page. It's that big of a deal.
Make new entry in tree, and cut-paste on new page. Done. Searching works, sort of.

In fact, this overview should be broken into many pages. Its huge. It appears to be a massive catch all and the documentation searching tool doesn't find things in it.
 
Feels like folks got lazy making new entries into the navigation tree.

**Comment by guardrex** [comment]
Hello @timschwallie ... Yes, this is already under consideration on a [tracking issue](https://github.com/dotnet/AspNetCore.Docs/issues/24615) that I keep and will probably be addressed in 23Q1.

btw --- When you open issues here, please use the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
