### ISSUE TITLE
Document the tasks, targets, properties, implicit blobs, etc. in the .NET Core web sdk for msbuild

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#2795]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 275b32fd-9419-e174-6fdf-75a0e8ab3a71
* Version Independent ID: f210fd34-23d8-b573-ce6f-9df02e49d80f
* Content: [ASP.NET Core Web SDK](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/web-sdk?view=aspnetcore-6.0)
* Content Source: [aspnetcore/razor-pages/web-sdk.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/web-sdk.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
contact is web tools team/@MLorbetske

**Comment by MaherJendoubi** [comment]
@danroth27 Would you please add more description : the context and a sample? Thanks.
@Rick-Anderson Excuse my ignorance, what does P1 label mean? Thanks.

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  P1 - is priority.

**Comment by Rick-Anderson** [comment]
@MLorbetske can you outline these and I'll get the doc written.

**Comment by mlorbetske** [comment]
@vijayrkn I believe you've started with some of the documentation for aspnet/WebSDK - can you link to what you have so far here?

**Comment by vijayrkn** [comment]
All the documentation I have so far is here - https://github.com/aspnet/websdk

This does not have much details on the default globs & prepublish/postpublish targets. I will try to add some more info in the Readme.

**Comment by Rick-Anderson** [comment]
@vijayrkn @dsplaisted @marcpopMSFT @ViktorHofer I'd like to include a link to https://github.com/dotnet/sdk/tree/main/documentation but I don't see where this is documented.

**Comment by vijayrkn** [comment]
@Rick-Anderson - The documentation is currently here : https://github.com/dotnet/sdk/tree/main/src/WebSdk#microsoftnetsdkweb
