### ISSUE TITLE
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore install fails

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#27969]
When I used package manager console to install:
"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore",
it tried to install version 7.  Since this is in .Net 6 framework it fails as incompatible.
I ended up copying the package manager command from Nuget.org for version 6.0.12.
It installs ok.
I haven't finished the page tutorial yet though.  I am on the Create a Database section.
I'm pretty sure it will work though.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If your TFM is 7, it will install 7

**Comment by anro95** [comment]
I also get this error same as @smiller7812  and I have <TargetFramework>net6.0</TargetFramework> in my .csproj file.

**Comment by smiller7812** [comment]
It's because the tutorial has us use .Net 6.0 as the framework to target instead of seven since it has not been updated.  So when you install with the Install-Package command in the tutorial with no version specified it will get the latest.

I go to nuget.org, search for "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore",  click the package manager tab.  There is a versions button where you can get the latest 6.X.X version. Click the copy button and plug it into Visual Studio Package Manager console.

________________________________

**Comment by Rick-Anderson** [comment]
> I also get this error same as @smiller7812 and I have ` <TargetFramework>net6.0</TargetFramework>` in my .csproj file.

Then you'll get the .NET 6 version.
Perhaps you had a transient error and need to try again.

**Comment by anro95** [comment]
I don't get the ,Net 6 version... I have to explicitly install it!

I use VS 2022 to create razor project. I get the TargetFramework=net6.0. I follow tutorial and run this in Package Manager Console:  
`Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore`

I then get this errormessage: "NU1202: Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 7.0.1 is not compatible with net6.0..."

I solve it by using smiller7812's solution to run this in Package Manager Console: 
`NuGet\Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -Version 6.0.12`

It installs and works. Problem solved!
