### ISSUE TITLE
Blazor wasm app.UseRequestLocalization

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#27964]
In blazor wasm 
`app.UseRequestLocalization` doesn't seem to be available

I can set the asp.net culture cookie like this:
```
        await JS.InvokeVoidAsync(
            "mySetCookieMethod",
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(new CultureInfo(name))));
```
but to read it back and set the `CurrentCulture` in blazor server I would call `app.UseRequestLocalization` in Startup.cs/Program.cs

do we have to do this manually in Blazor Wasm ? call js to get the cookie and set CurrentCulture ?
or is there at least some way to read something like "Response.Cookies" in Program.cs  (before calling `await app.RunAsync();`)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@omuleanu ... I think you should check the Blazor glob and loc doc and see if that guidance helps. If not, open a new issue from the bottom of that topic ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0&pivots=webassembly
