### ISSUE TITLE
Messy and unhelpful

### ISSUE THREAD

**Issue by TTWill** [dotnet/AspNetCore.Docs#27963]
Says "Host ASP.NET Core in a Windows Service"

So far so good, relevant and helpful. Atleast until the "Deployment type" section, then things get VERY confusing.

You would want the "Create and manage the Windows Service" section to be thorough, easy to understand or at least explained in details. After all this is to be run as a windows service.

The Windows Service part is explained to a PS profesional why?? And why the unnecessary details on how to start/stop at service in powershell? It is irrelevant in this context.

Taken the importance of being able to run any C# service application in a windows hosting environment, this documentation appears both unhelpful and misguiding at best. There is no "red thread" in the guidance, nor code leaning towards net6.0/7.0 even though it is said to be NET 7.0 compliant.

I have tried the examples. They did not work. Case scenarios are missing, after all the new Workers template is supposed to be an improvement. So far, it appears to be so confusing, that even professionals have a hard time decoding the relevant subjects within this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to container https://github.com/dotnet/AspNetCore.Docs/issues/28041
