### ISSUE TITLE
Improve Documentation to state that the class InitialApplicationState is just a custom class.

### ISSUE THREAD

**Issue by gregoryagu** [dotnet/AspNetCore.Docs#27970]
`InitialApplicationState`

In trying to add Identity to a Blazor Server App, I followed the instructions of this page.  However, I was stumped on where to find the class `InitialApplicationState`.  Turns out it's just a hand rolled class.

It would be helpful if it was clear that this class is just a custom class, not something supplied by a Library.  It took me a lot of looking until I found an example [here](https://github.com/javiercn/blazor-server-aad-sample) that made this clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
btw @gregoryagu ... I think it's already cross-linked here in the section where it's mentioned ... although ... yes, it might not be clear that that's where the class is shown, so an update might be warranted. Anyway, the link goes to ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0#pass-tokens-to-a-blazor-server-app

... where it shows the class.

I'm OOF through the EOY, so I'll take a closer look when I get back.

***Happy New Year!*** 🍾🎆
