### ISSUE TITLE
Add search to ASP.NET Core Razor Pages does not work

### ISSUE THREAD

**Issue by Taofeekfolami** [dotnet/AspNetCore.Docs#27973]
[I have implemented the tutorial up till part 6 and the add search does not work. The tutorial is based on ASP .NET 5.0 and i am using VS2019. I have searched and implemented suggestions from several fora but no luck. I will appreciate your suggestions.
The Index.cshtml.cs file contents is pasted below

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Data;
using RazorPagesMovie.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RazorPagesMovie.Pages.Movies
{
    public class IndexModel : PageModel
    {
        private readonly RazorPagesMovie.Data.RazorPagesMovieContext _context;

        public IndexModel(RazorPagesMovie.Data.RazorPagesMovieContext context)
        {
            _context = context;
        }

        public IList<Movie> Movie { get;set; }

        // Add search 
        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }
        public SelectList Genres { get; set; }
        [BindProperty(SupportsGet = true)]
        public string MovieGenre { get; set; }

        public async Task OnGetAsync()
        {
            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Movie
                                            orderby m.Genre
                                            select m.Genre;

            // Original. Search did not work
            var movies = from m in _context.Movie
                         select m;

            // Reported solutions.
            // source https://stackoverflow.com/questions/64746676/error-on-razor-page-when-searching-for-a-string

            // from stackoverflow. Still did not work

            //var movies = from m in _context.Movie
            //             where string.IsNullOrEmpty(SearchString) || m.Title.Contains(SearchString)
            //             select m;
            //////////////////////////////////////////////////////
            ///

            if (!string.IsNullOrEmpty(SearchString))
            {
                movies = movies.Where(s => s.Title.Contains(SearchString));
            }

            Genres = new SelectList(await genreQuery.Distinct().ToListAsync());

            Movie = await _context.Movie.ToListAsync();

        }
    }
}

]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Part 6, add search](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
It works. Why aren't you using .NET 7? You might want to look at the completed sample.
