### ISSUE TITLE
can we already use bind:set

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#27976]
Regarding: 

> The @bind:get and @bind:set features are receiving further updates at this time. To take advantage of the latest updates, confirm that you've installed the [latest SDK](https://learn.microsoft.com/en-us/download/dotnet/7.0).

The SDK link gives 404.
can we already use `bind:set` ?
In my project I have 
`<TargetFramework>net7.0</TargetFramework>`
and
`<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.1" />`
is this ^ what you mean by latest SDK ? ( aspnetcore package/dll ?)

I tried it and it works, only my VS2022 shows red wavy lines under the markup that uses `@bind:set`, but it builds and it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @omuleanu. It's a relative link, so it broke 😈. I'll patch it up right now to ...

https://dotnet.microsoft.com/download

... and ***Yes!*** ... 7.0.1 is the current release. They're still taking feedback on when/how these new binding features fail. If you want to see the latest, search their issues. I don't think much will be done with it in the near-term tho. Everyone is out for the holiday break. They won't be back in force until January.
