### ISSUE TITLE
How to add general isolated css for the component?

### ISSUE THREAD

**Issue by cveld** [dotnet/AspNetCore.Docs#27975]
How can I add a background color to the component? Or set the position to relative?
I found `::deep` but that only applies to child components. There is no `::host` directive like Angular provides.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cveld ...

AFAIK, you just set up a container element (e.g., a `div`) to hold the component's markup and set a style class up for the container element in the companion CSS file for the component. I don't think there's supposed to be anything tricky about it in the simplest case; but if the behavior isn't what you expect, I need more to go on showing exactly what's going wrong.

If you need product support, try the usual support channels listed in the holiday message :point_up:. We're all out on vacation at the moment.

**Comment by cveld** [comment]
E.g. I have a component <myComponent>. And I want the background to be black. In Angular you can use the pseudo-element :host. E.g.

```css
:host {
   background-color: black;
}
```

Introducing a wrapper div introduces a new layer which impacts flex box semantics and is undesired.

Where can I raise this feature request? The guidance above doesn't tell me where to submit Blazor related feature requests.

**Comment by guardrex** [comment]
@cveld ... Open it for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

**Comment by guardrex** [comment]
... and it's probably a good idea to cross-ref this issue and ping me, too, so I can follow the discussion that you have with them. 

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/27975
```

... to the bottom of your opening comment of your issue over there. I'll be 👂 on it for any juicy tidbits that might be good to document. I'll take care of re-opening this issue and working on it if that comes to pass.
