### ISSUE TITLE
remove Student, Instructor from SchoolContext.OnModelCreating

### ISSUE THREAD

**Issue by DreadedTuba** [dotnet/AspNetCore.Docs#28015]
SchoolContext `OnModelCreating` should remove these lines.
```csharp
modelBuilder.Entity<Student>.ToTable("Student")
modelBuilder.Entity<Instructor>.ToTable("Instructor")
```
I'm getting EF exception about them not existing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-7.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is handled under #26505
