### ISSUE TITLE
anchor links not working

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/AspNetCore.Docs#28021]
these anchor links aren't working:

![image](https://user-images.githubusercontent.com/14079228/210846276-6a082067-3de1-483a-a735-c3dd980296c4.png)
[source](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#apicontroller-attribute-3)

---

It seems to have something to do w/ the versioning feature 🤷‍♂️.

See how the anchor link changes slightly w/ the `-3` vs `-1` based upon w/ version of ASP.NET core is selected:

https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#attribute-routing-requirement-3
https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0#attribute-routing-requirement-1

but the doc page doesn't have `-N` in them.  This is the link on the page:
https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#attribute-routing-requirement

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0#automatic-http-400-responses-3)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's correct, @spottedmahn. This is a known limitation of the current versioning. Duplicate section headings are enumerated by the build system, so the links in earlier versions of the doc break. There's some background work going on to try and address this, but there's no ETA at this time on a new versioning implementation.
