### ISSUE TITLE
Generating sequence numbers using line numbers while manually building a render tree

### ISSUE THREAD

**Issue by MCGPPeters** [dotnet/AspNetCore.Docs#28036]
One way to achieve the same result as with Razor component files (using line numbers to get stable, compile-time constant, sequence numbers) is by utilizing the [CallerLineNumber] attribute. Use a method to create nodes in the render tree with the last parameter being the optional parameter decorated with the [CallerLineNumber] attribute. See an example [here](https://github.com/MCGPPeters/Radix/blob/434f60ab526d115c3d4a120fb29de4216b654e7a/src/Radix.Interaction.Web/Components/Attributes.cs#L11)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a84b780b-ca41-c255-9fbf-12e9af990c8a
* Version Independent ID: 8d522def-5710-f0ec-97aa-9ac636785f12
* Content: [ASP.NET Core Blazor advanced scenarios (render tree construction)](https://learn.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-6.0)
* Content Source: [aspnetcore/blazor/advanced-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/advanced-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @MCGPPeters.

Pinging @SteveSandersonMS to determine if the approach should be covered.

**Comment by SteveSandersonMS** [comment]
https://github.com/dotnet/aspnetcore/issues/10890
