### ISSUE TITLE
// Use LINQ to get list of genres. IQueryable<string> genreQuery = from m in _context.Movie                                 orderby m.Genre                                 select m.Genre;

### ISSUE THREAD

**Issue by jamunasiraj** [dotnet/AspNetCore.Docs#28034]
[Enter feedback here]

// Use LINQ to get list of genres.
IQueryable<string> genreQuery = from m in _context.Movie
                                orderby m.Genre
                                select m.Genre;

this showing like this issue 

Microsoft EntityFrameworkCore query internal EntityQueryable 1(System string).....
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Part 7, add search to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by tsancanin** [comment]
> [Enter feedback here]
> 
> // Use LINQ to get list of genres. IQueryable genreQuery = from m in _context.Movie orderby m.Genre select m.Genre;
> 
> this showing like this issue
> 
> ## Microsoft EntityFrameworkCore query internal EntityQueryable 1(System string).....
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: f9b9859c-b83c-5fc3-41d5-15531232185f
> * Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
> * Content: [Part 7, add search to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0)
> * Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/search.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-tutorials**
> * GitHub Login: @wadepickett
> * Microsoft Alias: **wpickett**

  IQueryable<string> genreQuery = from m in _context.Movie
                                            orderby m.Genre
                                            select m.Genre;
You're forget the tip <string> , If I'm right

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
