### ISSUE TITLE
Blazor components external JavaScript files

### ISSUE THREAD

**Issue by plastovicka** [dotnet/AspNetCore.Docs#28044]
There's a bug in the docs:
```
    <script src="_framework/blazor.{webassembly|server}.js"></script>
    <script src="./_content/{PACKAGE ID}/{SCRIPT PATH AND FILENAME (.js)}"></script>
```
Microsoft.JSInterop.JSException is thrown in a component's OnAfterRenderAsync function if the _content script is big and a user has slow internet connection. Then the page is rendered before scripts are loaded and JavaScript functions are not defined.

This bug can be fixed easily. Just swap the lines:
```
    <script src="./_content/{PACKAGE ID}/{SCRIPT PATH AND FILENAME (.js)}"></script>
    <script src="_framework/blazor.{webassembly|server}.js"></script>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57ed3088-2f9b-f51a-fd17-0c0de2949c57
* Version Independent ID: 49fa31d8-72a6-01a1-027d-6edeac9e0fc4
* Content: [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by SteveSandersonMS** [comment]
1. Yes, that's normally correct. The Blazor WebAssembly/Server startup process is asynchronous, so scripts added after that script tag are loaded and block the JS engine until they've finished loading. So under normal circumstances, the bug being reported here cannot occur, no matter the internet connection speed. I don't know what additional steps are needed to reproduce an error, but perhaps @plastovicka could provide complete repro steps and a runnable app to demonstrate them.
2. Yes that's an even more explicit way to control the execution order. However it shouldn't normally be required except if the developer is doing something special to make their scripts load out-of-order or asynchronously (e.g., adding `async` or `defer` attributes).

**Comment by guardrex** [comment]
@plastovicka ... I'm going to proceed with an improvement to the INCLUDE file to cover this based on Steve's remark on Item 1.

If you can provide repro steps to the product unit and a runnable app to demonstrate them, please open that for them on their repo at ...

https://github.com/dotnet/aspnetcore/issues

... because this issue will close out automatically with the PR that I'm going to merge shortly. Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28044
```

... to the bottom of your opening comment so that I can follow along.

**Comment by guardrex** [comment]
I'll add a bit to what I touched on the last PR. Javier is saying that if you load the script in `beforeStarted`, it will be there by the time Blazor starts.
