### ISSUE TITLE
Not a Step-by-Step Tutorial

### ISSUE THREAD

**Issue by maroonedsia** [dotnet/AspNetCore.Docs#28040]
Hi, with all respects, I think this article has fragments of useful information, but is vague as a tutorial, which prevents devs to use it as a step-by-step instructions:

TLDR: please provide a source code sample for this article to remove all the confusions. Also, the article can be restructured, for example, provide all the instructions for setting up the worker service project in one section, and all the instructions for the asp.net core projects in another one. For example, there are these "The following Program.cs calls AddHostedService to register ServiceA" and "In the following example, the custom_settings.json file exists..." program.cs code snippets, but which projects do they belong to?!

Here are some confusions:
1. Is worker service a separate project? If yes, it should get clarified to which project the second code snippet for Program.cs  belongs to.
2. There is no use of UseWindowsService() until "Use ContentRootPath or ContentRootFileProvider" section, so is the code snippet for worker service Program class or the asp.net core? And, why it's still the old style for .NET 7? (no top level statements?)
3. The text after "The following sample apps accompany this topic:" does not include any link to sample codes. Am I missing them?
4. By creating projects using VS or CLI templates, the project SDK types are set correctly, so the "SDK" section is very confusing.
5. For the "Self-contained deployment", should I set it for the worker service or asp.net core project?
6. For creating the Windows Service using PowerShell, should I create it for the worker service executable or asp.net core project?
7. The entry point of the service and the projects structure is confusing: If the entry point is the worker service, there is no trace of it being aware of the asp.net core project. If the entry point is the asp.net core project, then the only connection between the projects is at "builder.Services.AddHostedService<ServiceA>();" in asp.net core program.cs, so the worker service's program and CreateHostBuilder() => UseWindowsService() will never run?! If the code is correctly wired, it required some good explanation. 

Thanks! 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to container #28041
