### ISSUE TITLE
MapGet method is not defined, examples don't compile

### ISSUE THREAD

**Issue by ygoe** [dotnet/AspNetCore.Docs#28054]
There's a method named "MapGet" and similar mentioned on the page in several examples. When I copy the lines into my application, the compiler says it doesn't exist. Looking at the linked documentation page, it's defined in another interface, not IApplicationBuilder. Something is severely wrong with this documentation. I'm using .NET 7.0 so it's the correct version. Everything else can be compiled (but controllers cannot be found, I'm trying to figure out why that doesn't work this time). In general, I don't understand why endpoint routing is necessary. I think routes and controllers are enough, what are endpoints other than that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>  don't understand why endpoint routing is necessary. I think routes and controllers are enough

For most apps yes, the doc says that.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.endpointroutebuilderextensions.mapget
