### ISSUE TITLE
Useless Documentation

### ISSUE THREAD

**Issue by micklord49** [dotnet/AspNetCore.Docs#28053]
[Enter feedback here]

On the page you use two classes/Objects:
MockDB
TodoEndpointsV1

But nowhere is there any clear explanation of what these are supposed to be. Which makes the entire page utterly useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9487a919-5254-627c-d5cf-169d99a7e51b
* Version Independent ID: 9487a919-5254-627c-d5cf-169d99a7e51b
* Content: [Test Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/test-min-api?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/test-min-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/test-min-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's a sample and not for beginners.

**Comment by micklord49** [comment]
Ok, but if it's on your LEARN site (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/test-min-api?view=aspnetcore-7.0), then it should be more than a sample, it needs to convey enough information for you to actually be able to learn how to do do dependency injection of a mock database when coding a unit test! 

Given that I am trying to learn how to inject a mock database into a minimal api endpoint and that article is the first that comes up on Google seach - it's just not helpful at all so I do not see what the point of even having a sample is!
