### ISSUE TITLE
API's TOC work

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28058]
1.	Instead of a Web API and Minimal APIs node in our docs, replace with a single “APIs” node
2.	Write an overview that explains the two approaches and pros/cons, and links to the respective overviews (use the comparison from the tutorial [as rick pointed out.
3.	Make a “Controllers” sub-node and move the current Web API docs under that
4.	Make a “Minimal APIs” sub-node with current minimal APIs docs

**Comment by LadyNaggaga** [comment]
> 3. Make a “Controllers” sub-node and move the current Web API docs under that

I worry that this sub-node might not be descriptive enough  should it be `Controller based APIs` ?

**Comment by tdykstra** [comment]
It could be `Controller-based APIs`; elsewhere we've used `APIs with controllers`.
