### ISSUE TITLE
The Slack Team link died 💀 

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#28066]
@spboyer ... The Slack Team link went 404. Is there a new one?

This is what I've been using ...

https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA

***OR*** ... are new-to-Slack folks supposed to provide an email and get their "magic code" to join the team? ...

![image](https://user-images.githubusercontent.com/1622880/211803839-9a3c4a5e-3272-400e-8aaa-bc7c6cafce6c.png)

@Rick-Anderson ... When I have a replacement, I'll set up a repo-wide update PR in case it exists outside of the Blazor node.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Version Independent ID: 618e1209-44b8-c367-13e7-fbcfc26b07ea
* Content: [ASP.NET Core Blazor fundamentals](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by spboyer** [comment]
This is the current invitation link: https://join.slack.com/t/aspnetcore/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA

**Comment by guardrex** [comment]
Thanks @spboyer 🍻 ... I'll make the updates right now.

**Comment by guardrex** [comment]
@spboyer ... That link is throwing here ...

> https://aspnetcore.slack.com/join/shared_invite/zt-1b60h73p0-PZPq3YCCaPbB21RcujMSVA#/shared-invite/error

![image](https://user-images.githubusercontent.com/1622880/211831643-dc7987d9-973e-457b-95f2-240504bc3512.png)

**Comment by spboyer** [comment]
Created a new one : https://join.slack.com/t/aspnetcore/shared_invite/zt-1mv5487zb-EOZxJ1iqb0A0ajowEbxByQ
with no expiration.
