### ISSUE TITLE
Can't find the "Solution Tool Window" in VS Code

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#28079]
In the "[Create the initial database schema using EF's migration feature](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code#create-the-initial-database-schema-using-efs-migration-feature)" section I'm instructed to "In the Solution Tool Window, right-click the RazorPagesMovie project, and then select Open in Terminal." 

There is as far as I can tell no Solution Tool Window in VS Code. Is this perhaps a reference to a window in Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 60044](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60044)

**Comment by Rick-Anderson** [comment]
yes

**Comment by MartinNr5** [comment]
Ok... Will you update the documentation so that it's correct?

**Comment by wadepickett** [comment]
Thanks @MartinNr5 for pointing this out, very appreciated. I will get it fixed in the doc.  Looks like it was accidentally moved around from the Visual Studio content.

**Comment by MartinNr5** [comment]
@wadepickett - You're welcome.
