### ISSUE TITLE
SignalR - Is there a way to serve data to the server from client upon a request from the server?

### ISSUE THREAD

**Issue by knoxgon** [dotnet/AspNetCore.Docs#28078]
I'm trying to understand if there's a way to serve data from client to server upon request from the server without implementing any new methods in the `Hub` or without using e.g., `ConcurrentDictionary` to keep the track of the incoming requests.

In my case, I'm not really using a web browser as a client but rather a backend service written in nodejs where it needs to serve data to another source using SignalR. Where the source is thought to be the Server and the nodejs instance to be the Client.
In this case, we are talking about One-to-One communication with one client and one server instead of multi clients and one/multi server(s).
And no, we are not allowed to use REST as a solution.

My issue is that I'm trying to make the SignalR client available to serve data whenever the Server asks for it. Unfortunately, the `SendAsync` method does not wait for the response from the client for good reasons. Although, in some situations, there can be a case where one could need this functionality in place.

I've read on different forums that SignalR may not be the best option for this logic. A [user](https://stackoverflow.com/a/48288580/4393935) on StackOverflow has a post from 2018 where he states why request/response would be an antipattern. As the answer is pretty old, I'm wondering if there is an update on this issue.

How I imagine could be a way is to introduce the ability to execute the Hub methods directly from within the Hub server.
When the client receives that call event, it could immediately return the data back to the server.

The following codesnippets demonstrate such scenarios.

Client (e.g., NodeJs) with `@microsoft/signalr`
```js
// Whenever the server invokes this method, send back the data in the same request to the server
// There can be a timeout like 10 ms or 1 second to keep the request alive under that time.
connection.on('ServeUserData', async (username) => {
  const userData = await SQL.ExecuteQuery("...");
  return userData;
})
```

Server - Hub (e.g., C# with .NET 6)
```cs
public class MyHub : Hub
{
    //Make the injected IHubContext instance to be able to call this method with a return value
    public async Task<object> GetUserInfo(string username)
    {
        //Redirect the data passed from the background service to the client
        var dataFromClient = await Clients.Client.All.SendAsync("ServeUserData", username);
        return dataFromClient;
    }
}
```

Server - BackgroundService (e.g., C# with .NET 6)
```cs
public class MyService : BackgroundService
{
    private readonly IHubContext<MyHub> _hub;

    public MyService (IHubContext<MyHub> hub)
    {
        _hub = hub;
    }
    public async Task DoWork(CancellationToken stoppingToken)
    {
        //Logic
        var usersToSync = await Global.GetUserNames();
        for (var username of usersToSync)
        {
            //Execute the Hub method and wait for response from the client.
            var userinfo = await _hub.ExecuteMethod("GetUserInfo", username);
            //Process the returned data
            Global.UpdateUserInfo(username, userinfo);
        }
    }
}
```

**Comment by BrennanConroy** [comment]
Have you looked at and tried [Client Results](https://learn.microsoft.com/aspnet/core/signalr/hubs?view=aspnetcore-7.0#client-results)?

**Comment by BrennanConroy** [comment]
We can't port to 6.0. New APIs and features are not put in patches.

**Comment by knoxgon** [comment]
> We can't port to 6.0. New APIs and features are not put in patches.

Very reasonable. I can communicate with the customer highlighting the importance of this upgrade.
Although, when .NET 8 would be released in 6th or 7th of November, I really hope there won't be any breaking change updates releated to SignalR. :)

Thank you

**Comment by BrennanConroy** [comment]
> I really hope there won't be any breaking change updates releated to SignalR

We try not to 😃

**Comment by knoxgon** [comment]
@BrennanConroy I've to reopen this thread to ask if the connectionId could be accessible from the outside. If I now call the invokeAsync method, it naturally requires a connectionId.

Suppose, I'm trying to request data from the client inside a server controller with an injected IHubContext. Do I still need to keep an array of the connectionIds as Context is not accessible from the outside of Hub? (Or so do I believe).
As the `invokeAsync` is a member of `Client`, I'm kind of forced to provide a connectionId outside of the Hub class.

**Comment by stlsw** [comment]
is there way to set the timeout for waiting client to return the response ?
