### ISSUE TITLE
On "Fundamentals" page Include link to "WebApplication and WebApplicationBuilder in Minimal API apps"

### ISSUE THREAD

**Issue by agehrke** [dotnet/AspNetCore.Docs#28076]
This page contains a section about "Host" which mentions the three different hosts: 

> [.NET WebApplication Host](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0#new-hosting-model), also known as the Minimal Host.
[.NET Generic Host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-7.0)
[ASP.NET Core Web Host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-7.0)

The link to ".NET WebApplication Host" points to the 5.0 -> 6.0 migration page which has a lot of great info on the Minimal Host. But I think it should be considered to also link to the page [WebApplication and WebApplicationBuilder in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-7.0). Eg by making the text "Minimal Host" in above quote a link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals overview](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-7.0&tabs=windows)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 59303](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59303)

**Comment by Rick-Anderson** [comment]
@agehrke  thanks for the great suggestion, which should be live in 20 minutes. Check it out to make sure that's what you wanted.

**Comment by agehrke** [comment]
Looks good. Thank you 🙂
