### ISSUE TITLE
Imports are not found

### ISSUE THREAD

**Issue by jstafford5380** [dotnet/AspNetCore.Docs#28084]
All of these imports are 'not found' after installing recommended package and updating all grpc and protobuf packages to latest.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Version Independent ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Content: [gRPC JSON transcoding in ASP.NET Core gRPC apps](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/json-transcoding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/json-transcoding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by jstafford5380** [comment]
nevermind... didn't realize it mean I need to physically add those files to a directory structure by hand

**Comment by jstafford5380** [comment]
When I physically add the files, it throws on startup 

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The stored extension value has a type of 'Google.Api.HttpRule, <redacted>, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. This a different from the requested type of 'Google.Api.HttpRule, Google.Api.CommonProtos, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'.
  Source=Google.Protobuf
  StackTrace:
   at Google.Protobuf.ExtensionSet.Get[TTarget,TValue](ExtensionSet`1& set, Extension`2 extension)
   at Google.Protobuf.Reflection.MethodOptions.GetExtension[TValue](Extension`2 extension)
   at Grpc.Shared.ServiceDescriptorHelpers.TryGetHttpRule(MethodDescriptor methodDescriptor, HttpRule& httpRule)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
   at <redacted>.Reports.ReportService.BindService(ServiceBinderBase serviceBinder, ReportServiceBase serviceImpl) in C:\source\<redacted>\<redacted>\src\<redacted>\obj\Debug\net7.0\<redacted>\<redacted>\<redacted>.cs:line 189
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

```

**Comment by wadepickett** [comment]
@jstafford5380, thanks for the heads up!

Here are the latest packages versions to check against your project file.
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.21.12" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.49.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.49.0" />
    <PackageReference Include="Grpc.Tools" Version="2.49.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="7.0.2" />
  </ItemGroup>

Or you can run the following at the command line:
dotnet list YourProjectNameHere.csproj package --verbosity d

Are you working with a preview version of the .NET 7 SDK by chance or an earlier version of .NET?

**Comment by wadepickett** [comment]
@jstafford5380, thanks for the heads up.

This would be the latest package version to check against your project file.
  <ItemGroup>

    <PackageReference Include="Google.Protobuf" Version="3.21.12" />

    <PackageReference Include="Grpc.AspNetCore" Version="2.49.0" />

    <PackageReference Include="Grpc.Net.Client" Version="2.49.0" />

    <PackageReference Include="Grpc.Tools" Version="2.49.0">

      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>

    </PackageReference>

    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="7.0.2" />

  </ItemGroup>

Or you can run the following at the command line:
dotnet list YourProjectNameHere.csproj package --verbosity d

Are you working with a preview version of the .NET 7 SDK by chance?

**Comment by jstafford5380** [comment]
Ok I'll jump in once I'm back in the office on monday thanks

**Comment by wadepickett** [comment]
Since I just verified that the packages are there, able to download, compile and run.  I will close this for now.  Feel free to reopen however if we are missing something.  Thanks again.
