### ISSUE TITLE
SignalR - How to access connectionIds outside of Hub when using ISingleClientProxy.InvokeAsync?

### ISSUE THREAD

**Issue by knoxgon** [dotnet/AspNetCore.Docs#28081]
Is there a way to access the `connectionId` list outside of a Hub (e.g., from a Controller with an injected IHubContext)?
If I call the `ISingleClientProxy.InvokeAsync` method from e.g., a controller, it naturally requires a connectionId.

Suppose, I'm trying to request data from the client inside a server controller with an injected IHubContext. Do I still need to keep an array of the connectionIds as Context is not accessible from the outside of Hub? (Or so do I believe).
As the `InvokeAsync` is a member of `Client`, I'm kind of forced to provide a `connectionId` outside of the Hub class.
Unfortunately (maybe for good reasons), I can't call InvokeAsync on `.All`.

I just read this [post](https://stackoverflow.com/a/50394456/4393935) that it's not possible to have access to the connectionIds from the outside of Hub. 
However, in the case of invoking a client method would require the IHubContext to have an immediate access to the connectionIds. Otherwise, I'm not entirely sure how it would work.

In [this doc](https://learn.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0#get-an-instance-of-ihubcontext-in-middleware), it states that it's not possible.

> When client methods are called from outside of the Hub class, there's no caller associated with the invocation. Therefore, there's no access to the ConnectionId, Caller, and Others properties.

In that case, I'm baffled as to how I could use InvokeAsync function when having no access to connectionIds.

The [documentation](https://learn.microsoft.com/sv-se/aspnet/core/signalr/hubs?view=aspnetcore-7.0#client-results) provides an example of InvokeAsync usage but nothing about how the `connectionID` is retrieved.

I'm guessing it must be from a class where it has direct access to Hub thus its connections... A comprehensive example would really be helpful.

```cs
async Task SomeMethod(IHubContext<MyHub> context)
{
    string result = await context.Clients.Client(connectionID).InvokeAsync<string>(
        "GetMessage");
}
```

---
[Associated WorkItem - 60042](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60042)

**Comment by BrennanConroy** [comment]
Getting the Connection ID outside of the Hub is up to the user. You can store it in a Singleton service, you can pass it around the clients, you could store it in a global list (please no).

The reason there is no provided Connection ID outside of the Hub is because we have no way of knowing what ID you want. Even if we provided a `List<string> ConnectionID`, what ID would you want to use? Maybe in your specific scenario you want to loop over all of them and do something for each one. But that's not a common enough scenario that we provide something out of the box, and also it doesn't work very well in a scaled out environment since we don't share the IDs across servers.

So, it's left up to the user to store/share IDs in a way that's useful for their application.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by knoxgon** [comment]
@BrennanConroy Understandable. This is a piece of information that really needs to be citated in the documentation.

Thank you

**Comment by BrennanConroy** [comment]
Probably would be good in https://learn.microsoft.com/aspnet/core/signalr/hubcontext?view=aspnetcore-7.0 since that page is all about using the HubContext outside of the Hub context.

**Comment by wadepickett** [comment]
Related to this thread https://github.com/aspnet/SignalR/issues/2274#issuecomment-389013456

**Comment by wadepickett** [comment]
Related to issue: #27021 Monitor gRPC and SignalR doc requests
