### ISSUE TITLE
"Debug" required for breakpoints to work

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#28108]
In the "[Add route template](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0#add-route-template)" section the reader is instructed to test the behavior of ```@page "{id:int?}"``` by setting a breakpoint in the code and navigate to a specific page in the RazorPagesMovie app.

There is no mention that the app needs to be run in debug mode (F5) for the breakpoint to work. It's likely that the reader will continue to use Ctrl-F5 as that is what they are instructed to use to run the app in the first page of the tutorial.

The same issue is present later, in the "[Review concurrency exception handling](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0#review-concurrency-exception-handling)" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Part 5, update the generated pages](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Good point.  Will change to make this smoother.  Thanks @MartinNr5

**Comment by Rick-Anderson** [comment]
We don't have that every time we suggest debugging, we expect programmers to know that.

**Comment by MartinNr5** [comment]
@Rick-Anderson Then why do you explicitly tell the reader to use Ctrl+F5 to run without the debugger in the first page of the tutorial? Isn't that also something that they should know or figure out?

By telling the reader to use Ctrl+F5 you set the bar for the level of detail in the tutorial and if the reader is new to ASP.NET Razor Pages - which is likely since they follow a tutorial - they might not think twice about specifically pressing Ctrl+F5 to run without the debugger.

Finally, why is it a bad thing to explicitly tell the reader what to do? Isn't the whole purpose of a tutorial to guide them?
