### ISSUE TITLE
Why is this page under AspNetCore?

### ISSUE THREAD

**Issue by HughWarrington** [dotnet/AspNetCore.Docs#28101]
This page seems to be the best (only?) documentation on the .pubxml file format.

However those files are used for different kinds of deployment, e.g. ClickOnce.

Should this documentation be moved elsewhere? And could it be expanded to be more generic and include other deployment types?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's targeted to ASP.NET Core. Feel free to open issues in other places that should link to it.
