### ISSUE TITLE
Incorrect code example for VS Code

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#28107]
In the first code example section the VS Code example is missing ```using RazorPagesMovie.Data;``` on line 3. This line is present in the code example for Visual Studio, and in the code on my workstation after following the tutorial up to this point.

Also, the incorrect part of the code example is highlighted for VS Code , perhaps due to this line missing? 

In the code example for Visual Studio the following code is highlighted:
```
builder.Services.AddDbContext<RazorPagesMovieContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("RazorPagesMovieContext
```
For the VS Code example the following code is highlighted:
 ```
// Add services to the container.
builder.Services.AddRazorPages();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Part 4, work with a database](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 60043](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60043)

**Comment by Rick-Anderson** [comment]
Thanks for reporting this @MartinNr5. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.

**Comment by Rick-Anderson** [comment]
@MartinNr5  just fix the line at https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/sql.md?plain=1#L24

**Comment by MartinNr5** [comment]
Hi @Rick-Anderson.

No problem, I'll take care of it.
