### ISSUE TITLE
Problems scaffolding the movie model

### ISSUE THREAD

**Issue by catfishsushi** [dotnet/AspNetCore.Docs#28106]
When I try to scaffold the movie model I end up with the following error. 

<img width="303" alt="MovieModelError" src="https://user-images.githubusercontent.com/42792811/212596917-e1214942-17d1-49b1-9368-60bfe70ae9c7.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
@catfishsushi, thanks for the heads up.  Looking at the error I am guessing you may have an older global tools or bit of a version miss match with the packages.

You might try the following commands at the commandline:

dotnet list YourProjectNameHere.csproj package --verbosity d

Try uninstalling and install the global tools and get the latest:

dotnet tool uninstall dotnet-aspnet-codegenerator --global
dotnet tool install --global  dotnet-aspnet-codegenerator

**Comment by wadepickett** [comment]
I will close this issue for now, but if you decide it needs to be re-opened for a change in the topic,please feel free to do so.
