### ISSUE TITLE
Typo in example for configuring gRPC LoggingInterceptor Service

### ISSUE THREAD

**Issue by dbarU** [dotnet/AspNetCore.Docs#28110]
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddGrpc(options =>
    {
        options.Inteceptors.Add<LoggingInterceptor>();
    });
    services.AddSingleton<LoggingInterceptor>();
}
```
Should be:
  options.**Interceptors**.Add<LoggingInterceptor>();

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc8dc9f-9cc8-bda7-2cda-e9461f7c3a5d
* Version Independent ID: 85b23cfb-29a8-37f4-16f7-fdf6b0dde773
* Content: [gRPC for .NET configuration](https://learn.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-7.0#configure-services-options)
* Content Source: [aspnetcore/grpc/configuration.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

---
[Associated WorkItem - 59533](https://dev.azure.com/msft-skilling/Content/_workitems/edit/59533)

**Comment by wadepickett** [comment]
@dbarU, thanks, just fixed it.
