### ISSUE TITLE
CS8602 Warning on ASPNET-CORE example

### ISSUE THREAD

**Issue by b4cktr4ck5r3** [dotnet/AspNetCore.Docs#28116]
Hello,

The given example for https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0#add-search-by-genre-to-the-index-view-1 result to 5 CS8602 warning :

![image](https://user-images.githubusercontent.com/59377281/212962713-f13ca5f7-f251-4887-a22a-8f58039e8a56.png)

If you have any idea to solve this.

Thank you,
Tom.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Part 7, add search to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @b4cktr4ck5r3 for taking the time to let us know.
If you are getting that warning here, I'm guessing that you might have missed one of the following steps:

1. https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio#build-the-app

To eliminate the warnings from nullable reference types, remove the following line from the MvcMovie.csproj file:
`<Nullable>enable</Nullable>`

 2. When adding the model class, including setting nullable reference types, which are mentioned here when the data model class is first added:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio

..or when updating the data model is updated here using nullable reference types:
(https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-6.0&tabs=visual-studio#add-a-data-model-class-1).

I will close this issue for now, but if you have more information and think the doc needs to change, feel free to reopen.
