### ISSUE TITLE
Document Blazor's caching behavior

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#28134]
Blazor does its own caching, which can catch developers by surprise if they try to disable browser caching but then find that their app is still cached. We mention Blazor's caching behavior indirectly in a couple of places, like here: https://learn.microsoft.com/aspnet/core/blazor/host-and-deploy/webassembly#resolve-integrity-check-failures. But it seems like it should get a more direct treatment.

@mkArtakMSFT  Is there someone on the team that can help out with content for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad891f84-d11e-e334-fcdc-b55c5171fca4
* Version Independent ID: 11f8db3d-9988-e0a1-89c5-c3552ee47b93
* Content: [ASP.NET Core Blazor startup](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 ... A few sections down from your cross-linked (second-level) introduction in the *Disable integrity checking for non-PWA apps* section, the property for disabling caching is presented ...

```xml
<BlazorCacheBootResources>false</BlazorCacheBootResources>
```

... with followup remarks on browser caching ...

> Even with this setting, the browser's normal HTTP cache may still cache those files, but whether or not this happens depends on your web server configuration and the cache-control headers that it serves.

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#disable-integrity-checking-for-non-pwa-apps

For PWAs, the guidance is covered in the section after that, [Disable integrity checking for PWAs](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#disable-integrity-checking-for-pwas).

Perhaps, we just need to change the section headings (and some of the content in the sections) ...

```diff
- ## Diagnosing integrity problems
+ ## Boot resource caching and diagnosing integrity problems
```

```diff
- ### Disable integrity checking for non-PWA apps
+ ### Disable resource caching and integrity checks for non-PWA apps
```

```diff
- ### Disable integrity checking for PWAs
- ### Disable resource caching and integrity checks for PWAs
```

... and I'd touch the content of these sections a bit to include more "resource caching" language with the existing "disable integrity checks" language.

Shall I proceed with that plan and ping u on the PR?

**Comment by danroth27** [comment]
> Perhaps, we just need to change the section headings (and some of the content in the sections) ...
> - ## Diagnosing integrity problems
> + ## Boot resource caching and diagnosing integrity problems

I think this should actually be split into separate sections. I want to separate out the explanation of how Blazor does caching on the client from the troubleshooting information

> It looks now like the HTTP Caching article should be under a "WebAssembly" node in Host and Deploy with the "integrity check (boot resource caching)" sections pulled out into that article that combines with content with the HTTP Caching article, probably with a different article name

Yeah, that all sounds reasonable to me :+1:

> Anyway ... if you sort of agree with some/most of this ... I'll get a PR together for us to consider.

Yup, the general proposal sounds good.
