### ISSUE TITLE
New FromForm binding support

### ISSUE THREAD

**Issue by brunolins16** [dotnet/AspNetCore.Docs#28167]
The parameter binding documentation should be update with the new support for `FromForm` in Minimal APIs that will be introduced in .NET 8 Preview 1.

https://github.com/dotnet/aspnetcore/pull/44653

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a09dcf06-a685-e5b8-0ce4-a4e53c57a9fd
* Version Independent ID: a09dcf06-a685-e5b8-0ce4-a4e53c57a9fd
* Content: [Parameter binding in Minimal API applications](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/parameter-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/parameter-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 82761](https://dev.azure.com/msft-skilling/Content/_workitems/edit/82761)

**Comment by brunolins16** [comment]
@Rick-Anderson Can we start the documentation updates for .NET 8 already or the moniker won't work?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Can we start the documentation updates for .NET 8 already or the moniker won't work?

Start, I'll get the .NET 8 preview monikers enabled.

**Comment by Rick-Anderson** [comment]
Your work item is here:
https://ceapex.visualstudio.com/Onboarding/_workitems/edit/770041

**Comment by Rick-Anderson** [comment]
@brunolins16  just supply the code and a solid draft. You can even copy/paste the code in the MD file and I'll make the change to snippets. Just supply a working project. I'll do all the editing and clean up.

**Comment by brunolins16** [comment]
Ok. I will create a PR in the ASP.NET Core doc samples repository with the sample code soon.

**Comment by Rick-Anderson** [comment]
We can do .NET anytime.
