### ISSUE TITLE
This page is empty!

### ISSUE THREAD

**Issue by DavidH541** [dotnet/AspNetCore.Docs#28175]
[Enter feedback here]
As the title states, the page is empy....
https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1
![image](https://user-images.githubusercontent.com/48517401/214268406-13b28b2d-df62-4120-bac5-954182d25206.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 60518](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60518)

**Comment by Rick-Anderson** [comment]
I'll fix that but in the mean time select the current version, not 3.1
?view=aspnetcore-3.1
<img width="252" alt="image" src="https://user-images.githubusercontent.com/3605364/214370273-b0c34366-1471-4f47-a3a7-5e8e31ebbb3d.png">
