### ISSUE TITLE
Identity Scaffolding Procedure for Blazor Server Apps results in a "no code generators" error

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/AspNetCore.Docs#28186]
Following the scaffolding procedure described for Blazor Server apps, the process fails at the "Finding the generator 'identity'" step, with an error: "There was an error running the selected code generator: 'No code generators found with the name 'identity''

The Output window displays:

Finding the generator 'identity'..
No code generators found with the name 'identity'
at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) 

You might want to add this to https://github.com/dotnet/Scaffolding/issues/1395

Exit & restart VS sometimes helps. Try if from the command line.
