### ISSUE TITLE
false line of code highlighted 

### ISSUE THREAD

**Issue by idea-lei** [dotnet/AspNetCore.Docs#28196]
In the part of [Add services and an endpoint for the SignalR hub](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio&pivots=webassembly#add-services-and-an-endpoint-for-the-signalr-hub), section 4: In Program.cs
![image](https://user-images.githubusercontent.com/30424884/214704676-31e94f04-1e2f-4aee-9825-77b2cc5b0127.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Version Independent ID: 85af7a99-672c-0438-dcc2-e8edfaf70c54
* Content: [Use ASP.NET Core SignalR with Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/tutorials/signalr-blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @idea-lei ... I'll patch that right now.

**Comment by guardrex** [comment]
It looks like the fix for this will be over on the sample app side, which is on another repo. I'll patch it over there, then I'll update the date of this article to make sure the change makes it into the live doc.
