### ISSUE TITLE
Contents of DepartmentNamePageModel.cs incorrect and differs from finished code on GitHub

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#28202]
The contents of the *DepartmentNamePageModel.cs* file in the tutorial isn't working - I get the error "The name 'Department' does not exist in the current context [ContosoUniversity]" on line 21 and 22 - and when checking the code for stage 7 of the tutorial on GitHub [the contents of the file](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu-completed-stages/part7/ContosoUniversity/Pages/Courses/DepartmentNamePageModel.cs) is different but allows me to run the application with intended functionality.

The errors in my code might be because I missed something but I've gone through everything in the tutorial that relates to Department and can't find my mistake if there is one.

I would none the less argue that the code on GitHub should be the same as in the tutorial, or vice versa as the code on GitHub actually works. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Part 7, Razor Pages with EF Core in ASP.NET Core - Update Related Data](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-7.0)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 60936](https://dev.azure.com/msft-skilling/Content/_workitems/edit/60936)

**Comment by wadepickett** [comment]
At first glance I thought this was the Razor Pages Getting started series, so I accidentally assigned it.  Set it back since I am not up on this doc series.

**Comment by tdykstra** [comment]
@MartinNr5 thanks for reporting that -- I'm fixing it by adding a missing using directive and copying the new code to the other code file.

**Comment by Rick-Anderson** [comment]
@MartinNr5 thanks for taking the time to report this. Other than this issue, how do you like the tutorial?

**Comment by MartinNr5** [comment]
@Rick-Anderson I enjoyed it quite a bit. It's very informative and explains a lot of concepts that I know from past experience but that's new to me in Razor pages and EF Core.

It's also relevant for building real life applications, with a (relatively) complex database model and corresponding Razor pages for editing and maintaining the data.

I've just finished it and will take a look at the suggested MVC version of the tutorial to see if what I'm missing (more on how to work on the front-end side of the app with Razor pages and not just the backend) might be included there.

**Comment by Rick-Anderson** [comment]
@MartinNr5 thanks for responding. The MVC version is really badly out of date but does have a lot of stuff missing from the RP version. We plan to add that. See #26505

**Comment by MartinNr5** [comment]
@Rick-Anderson I noticed that the MVC version isn't using Razor pages at all but I'll take a closer look at the dedicated Razor pages documentation to glean as much as possible from them before I sit down and write my actual app.

I'll also read through the parts of the MVC tutorial that talks about the more advanced topics you mention in #26505. 

As an aside, I'm in no way qualified to write actual documentation for you but if time permits - and I'm allowed to - I'm more than happy to beta test any tutorials, especially for RP and EF.

**Comment by Rick-Anderson** [comment]
Yes, it's all MVC. You could blast through [Get started with ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc) and it won't take you long to figure out how to go from RP to MVC.

>As an aside, I'm in no way qualified to write actual documentation for you but if time permits - and I'm allowed to - I'm more than happy to beta test any tutorials, especially for RP and EF.

Fantastic, we'll take you up on that.
