### ISSUE TITLE
Slightly misleading example code concerning validation rules. 

### ISSUE THREAD

**Issue by aspeckt-112** [dotnet/AspNetCore.Docs#28215]
The first example of the validation code here: https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-7.0#add-validation-rules-to-the-movie-model

Clearly displays:

`[DataType(DataType.Currency)]`

As an existing attribute on the Price member.

However, that attribute isn’t added to the code until later on in the example, here: https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-7.0#using-datatype-attributes

It’s totally not a big deal, but it did confuse one of my junior developers who was working through the example and then went back and checked their existing code because they thought they’d missed something.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Part 9, add validation to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 61232](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61232)

**Comment by wadepickett** [comment]
Thanks @aspeckt-112 for pointing this out!  Looks like it might be pointing to the wrong version of code sample in the sequence of steps.  We will get it fixed.
