### ISSUE TITLE
Code for "Update the Delete Razor page" is incorrect

### ISSUE THREAD

**Issue by MartinNr5** [dotnet/AspNetCore.Docs#28218]
The code shown for ["Update the Delete Razor page"](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-7.0&tabs=visual-studio-code#update-the-delete-razor-page) is incorrect.

On line 36 it has ```@Utility.GetLastChars(Model.Department.ConcurrencyToken)``` while the existing code in my project has ```@Html.DisplayNameFor(model => model.Department.ConcurrencyToken)```. The code in my project results in a more correct display when deleting a department.

The code in the tutorial is also highlighted incorrectly with line 42 highlighted instead of line 45.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Part 8, Razor Pages with EF Core in ASP.NET Core - Concurrency](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 61143](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61143)

**Comment by tdykstra** [comment]
@MartinNr5 Thanks again for reporting that!
