### ISSUE TITLE
Add document to trace Configuration DebugView during Startup 

### ISSUE THREAD

**Issue by cnmade** [dotnet/AspNetCore.Docs#28217]
[EDIT by guardrex to add the metadata. @cnmade, please use the **This page** feedback button and form at the bottom of the topic, which adds the metadata automatically and pings the author. I'll add it manually to this issue, so no worries here.]

I am hardly to find the way to debug Configuration while development

here is my Startup.cs
```csharp



 // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger<Startup> logger)
        {
            var _cm = "Configure@Startup.cs";
            logger.LogInformation(_cm + " env:" + env.ToString() + " > " + env.EnvironmentName);
            logger.LogInformation(_cm + " configfile: " + (Configuration as IConfigurationRoot).GetDebugView());
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "MyArea",
                    pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

And these code can print the configuration you were using on the console, It is very useful.

![image](https://user-images.githubusercontent.com/278153/215092458-73a69976-863e-4787-a08c-570f2cc0f631.png)

For summary , i use two key point to make this possible.

1. Inject logger for `Configure` method, to let it can log into console
2. Call IConfigurationRoot.GetDebugView() to dump the valid and the working Configuration file loaded into memory

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@cnmade [Startup.cs hasn't been used since ASP.NET Core 5 and earlier](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0&tabs=visual-studio#new-hosting-model), two versions back.

Why are you using Startup?

**Comment by cnmade** [comment]
Tracing the loaded `env` and `configuration` during the boot time

**Comment by cnmade** [comment]
If something wrong ,we check the startup log, we can know it.

**Comment by Rick-Anderson** [comment]
We're not adding to Startup documents anymore.
