### ISSUE TITLE
More information required when using "Parameters" for the RootComponent

### ISSUE THREAD

**Issue by Daeer-Projects** [dotnet/AspNetCore.Docs#28219]
I would like to pass an object from the view model to the Blazor component.

I have a XAML view which is bound to a view model (MVVM).

As I'm adding a Blazor WebView component to the XAML, and I want to see how to pass the object to the Blazor component.

All of the documents only show the two main parameters:

- `ComponentType`
- `Selector`

Nothing is showing how we can use the `Parameters`.  All they say is it's a `Dictionary<string, object?>?`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Version Independent ID: 8de1a060-dbbb-c4a1-0407-b80f91b600be
* Content: [Host a Blazor web app in a .NET MAUI app using BlazorWebView - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/blazorwebview?view=net-maui-7.0)
* Content Source: [docs/user-interface/controls/blazorwebview.md](https://github.com/dotnet/docs-maui/blob/main/docs/user-interface/controls/blazorwebview.md)
* Product: **dotnet-mobile**
* Technology: **dotnet-maui**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@guardrex It's all yours. Many thanks!

**Comment by guardrex** [comment]
@davidbritch ... ❓ on conventions: Your sample namespaces don't include the folder names (e.g., `XamlSamples.KeypadPage` instead of `XamlSamples.Views.KeypadPage` and `XamlSamples.KeypadViewModel` over `XamlSamples.ViewModels.KeypadViewModel`. I plan to stick with your conventions as much as I can in Blazor doc examples, but I was just wondering if that's a normal approach for desktop/mobile to avoid the folder names in the namespaces?

**Comment by guardrex** [comment]
Ok ... well ... I put something together that ***seems to work*** 😆 ... another one of my 🦖 ***RexHacks!***&trade; 🦖🙈 no doubt! 😄

Let's start with this and see what we think before I go to trying to write it up. Any objections to the following as an example ...

This is based on the Key Pad page example at https://learn.microsoft.com/en-us/dotnet/maui/xaml/fundamentals/mvvm?view=net-maui-7.0#commanding.

1. Although I could set `Parameters` directly, I decided to go with the code-behind approach. Give the root component an `x:Name` in `MainPage.xaml` ...

   ```xaml
   <RootComponent x:Name="rootComponent" Selector="#app" ComponentType="{x:Type local:Main}" />
   ```

2. In code, assign the view model in the ctor ...

   ```csharp
   rootComponent.Parameters = new Dictionary<string, object> { { "KeypadViewModel", new KeypadViewModel() } };
   ```

3. In the `Main` component, add a parameter for it ...

   ```razor
   @code {
       [Parameter]
       public KeypadViewModel KeypadViewModel { get; set; }
   }
   ```

4. In the `MainLayout` component, add an `@code` block with ...

   ```razor
   @code {
       private KeypadViewModel keypadViewModel = new();
   }
   ```

   ... and wrap the `<article>` element with a `CascadingValue` for the view model ...

   ```razor
   <CascadingValue Value="@keypadViewModel">
       <article class="content px-4">
           @Body
       </article>
   </CascadingValue>
   ```

5. ... and then we should be able to use the cascaded view model in a component wherever we want across the app 🤞 ...

   ```razor
   @page "/keypad"

   <h1>Keypad</h1>

   <table class="table">
       <thead>
           <tr>
               <th colspan="2">@KeypadViewModel.DisplayText</th>
               <th><button @onclick="DeleteChar">&#x21E6;</button></th>
           </tr>
       </thead>
       <tbody>
           <tr>
               <td><button @onclick="@(e => AddChar("1"))">1</button></td>
               <td><button @onclick="@(e => AddChar("2"))">2</button></td>
               <td><button @onclick="@(e => AddChar("3"))">3</button></td>
           </tr>
           <tr>
               <td><button @onclick="@(e => AddChar("4"))">4</button></td>
               <td><button @onclick="@(e => AddChar("5"))">5</button></td>
               <td><button @onclick="@(e => AddChar("6"))">6</button></td>
           </tr>
           <tr>
               <td><button @onclick="@(e => AddChar("7"))">7</button></td>
               <td><button @onclick="@(e => AddChar("8"))">8</button></td>
               <td><button @onclick="@(e => AddChar("9"))">9</button></td>
           </tr>
           <tr>
               <td><button @onclick="@(e => AddChar("*"))">*</button></td>
               <td><button @onclick="@(e => AddChar("0"))">0</button></td>
               <td><button @onclick="@(e => AddChar("#"))">#</button></td>
           </tr>
       </tbody>
   </table>

   @code {
       [CascadingParameter]
       protected KeypadViewModel KeypadViewModel { get; set; }

       private void DeleteChar()
       {
           if (KeypadViewModel.DeleteCharCommand.CanExecute(null))
           {
               KeypadViewModel.DeleteCharCommand.Execute(null);
           }
       }

       private void AddChar(string key)
       {
           KeypadViewModel.AddCharCommand.Execute(key);
       }
   }
   ```

**Comment by davidbritch** [comment]
@guardrex There was a time when using Xamarin.Forms that adding a type to a folder in a project still put the type in the root namespace, rather than Root.Folder.Type. Some samples date back to that time, and I've simply ported them with the updates required to get them working in MAUI.

The ideal approach would be RootNamespace.Folder.Type, which is how I write them now.

**Comment by guardrex** [comment]
Ah! Ok ... cool ... I'll take that approach, as we did earlier for that last example on routing among components and pages. The preceding will require just a few touch-ups to fix that aspect, and I'll put that on the PR.

Let me know if your 👁️ just ***popped out*** looking at that ***HACK*** code up there ☝️. It seems to work ... at least! 😄 I think it's at least ***approximately*** the right approach if not exactly correct. If we need Tanay or Mackinnion to look, let me know.

**Comment by davidbritch** [comment]
> Let's start with this and see what we think before I go to trying to write it up. Any objections to the following as an example ...

LGTM!

**Comment by guardrex** [comment]
Cool! I'll write it up that way.

I don't think I'll need a review on the PR. This turned out to be fairly straight-forward, and I like that we're going with an existing .NET MAUI example that I can just cross-link to ... they can put both into a test app and it should ✨ ***Just Work!***&trade; ✨.

**Comment by guardrex** [comment]
Note that I'm going to have to keep the namespaces the way that that are because the existing .NET MAUI text and sample app do so. I mean to let devs ***cut-'n-paste*** their way to a happy experience in a test app. I'll make a note tho in the topic that the example matches the namespaces of the .NET MAUI doc/example and to change it if they change there.
