### ISSUE TITLE
Adding Scaffold the movie model

### ISSUE THREAD

**Issue by cowps92** [dotnet/AspNetCore.Docs#28225]
I ran into the following the follow error when going through a tutorial.  I've made sure i have the correct Scaffolding.Shared version installed. Can anyone give me any pointers?

![Screenshot_20230128_083856](https://user-images.githubusercontent.com/123802689/215256337-ed1ea2a8-14d6-4864-97cf-85cdeb225575.png)

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
