### ISSUE TITLE
Make it easier to consume the docs

### ISSUE THREAD

**Issue by ilmax** [dotnet/AspNetCore.Docs#28226]
Yesterday evening I was watching a live stream about astro on linkedin, you can find it here https://www.linkedin.com/events/what-snewinastro2-0-opensourcef7024505940087382016.

They came up with an interesting idea on how to consume the docs via a conversational interface that uses gpt3 trained with their documentation. I think it's an interesting idea and I found it worth sharing here.

The docs are extensive and it's easy to get lost, especially if you're unsure what to look for, so I think a conversational ui would make the docs easier to consume.

**Comment by guardrex** [comment]
Hello @ilmax ... We don't control those types of decisions here. We only work on the content. You can open a feedback issue on that at ...

https://github.com/MicrosoftDocs/feedback/issues
