### ISSUE TITLE
Explain dev's need to manage SPA version

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28223]
Work with `@javiercn` on verbiage that .NET doesn't update SPA framework version in servicing releases, the developer must do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1ffb8e1-215c-c148-0b28-da0d62665fa4
* Version Independent ID: c1ffb8e1-215c-c148-0b28-da0d62665fa4
* Content: [Overview of Single Page Applications (SPA) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/spa/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **jacalvar**

---
[Associated WorkItem - 61175](https://dev.azure.com/msft-skilling/Content/_workitems/edit/61175)

**Comment by mkArtakMSFT** [comment]
Thanks @Rick-Anderson.
I'm working on this internally and will get back on this with updates as necessary. Let's mark this as `blocked` for now and assign it to me.

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson I think this should be closed now, as you've merged another PR: https://github.com/dotnet/AspNetCore.Docs/pull/28345
