### ISSUE TITLE
Adding Scaffold the movie model

### ISSUE THREAD

**Issue by cowps92** [dotnet/AspNetCore.Docs#28232]
[Enter feedback here]
I ran into the following the follow error when going through a tutorial. I've made sure i have the correct Scaffolding.Shared version installed. Can anyone give me any pointers?

![image](https://user-images.githubusercontent.com/123802689/215290028-73394bbb-eecb-449f-85b4-9a393cb3595c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
One possibility to check:

The related tools might be out of date.  They do not automatically update if you install but had an existing older one.  Run the following at the command line to uninstall and reinstall the latest:

```text
dotnet tool uninstall dotnet-ef --global
dotnet tool install --global dotnet-ef
dotnet tool uninstall dotnet-aspnet-codegenerator --global
dotnet tool install --global  dotnet-aspnet-codegenerator
```

I will close this for now, unless you are able to get more information that might point to a change needed in the doc.  In which case feel free to reopen.
