### ISSUE TITLE
Helpful as Fuck!

### ISSUE THREAD

**Issue by DontForgetTheMango** [dotnet/AspNetCore.Docs#28240]
Thanks for whoever put this site together! As a C# .Net Core developer who wants to work his way into web-dev, this site has been incredibly helpful in understanding Microsoft's approach! Can't wait to make my first site!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0#razor-code-blocks)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Removed inappropriate language from the title.
