### ISSUE TITLE
Feedback for blazor data binding in v7

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#28245]
### 1
In [this](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0#use-bindgetbindset-modifiers-and-avoid-event-handlers-for-two-way-data-binding) section there's a typo in the code:

````cs
        inputValue = newValue.Length > 4 ? "Long!" : inputValue = newValue;
````
Should be
````cs
        inputValue = newValue.Length > 4 ? "Long!" : newValue;
````

### 2
In [this](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0#binding-to-a-property-with-c-get-and-set-accessors) section it says:

    > For two-way data binding in ASP.NET Core 7.0 or later, we recommend using @bind:get/@bind:set modifiers. For more information, see the @bind:get/@bind:set in the opening section of this article.

But it doesn't say why? I assume that the new v7 syntax allows one to perform a "set" with an async method, which cannot be done using a regular c# (sync) property setter. That is useful, for e.g., when doing autocomplete. Maybe there are other reasons?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @lonix1 ... I'm going to patch (fix) this issue quickly and open a follow-up on the motivation for the `@bind:get`/`@bind:set` aspect.
