### ISSUE TITLE
Trust HTTPS certificate on RHEL

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28278]
Add instructions to [trust HTTPS certificate on RHEL](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-https-certificate-on-linux)

RHEL version of:

- [ ]  [Ubuntu trust the certificate for service-to-service communication](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communicatio)
- [ ] Trust HTTPS certificate on Linux using Edge or Chrome
- [ ] Trust the certificate with Firefox on Linux

Partial instructions [here](https://github.com/dotnet/aspnetcore/issues/32842#)

Related #16974
parent: #27603

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communication)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 62078](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62078)

**Comment by Rick-Anderson** [comment]
@djgalvan can you help me write instructions to get the cert working n RHEL. I created a VM on Azure with 8.6 RHEL. I think I can create a 9.0 VM if that's better.

**Comment by Rick-Anderson** [comment]
RFH

**Comment by djgalvan** [comment]
@Rick-Anderson I've got ample time this weekend. I can run through 8.6 and verify 9.0 afterwards if you'd like.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I've got ample time this weekend. I can run through 8.6 and verify 9.0 afterwards if you'd like.

Awesome, much appreciated. No hurry. I'd like to get it done this month is all.

**Comment by djgalvan** [comment]
Looking over, we'll want [tabs](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.4&tabs=azure-portal%2Crhel#tabpanel_3_rhel) for Ubuntu and RHEL [here](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communication) using the fedora section [here](https://github.com/dotnet/aspnetcore/issues/32842#issue-895287688). Verifying that those instruction work or adjusting as necessary. I'm on the road with a Mac so if you set me up in that VM I'll work on what I can.

**Comment by djgalvan** [comment]
disregard the vm

**Comment by Rick-Anderson** [comment]
>  I'm on the road with a Mac so if you set me up in that VM I'll work on what I can.
Can you email me and I'll send you VM connection instructions? riande@microsoft.com

Just tested via:

```
dotnet new web -o web
cd web
dotnet run
```

Launch another PS window and test with curl. HTTP returns Hello World!
HTTPS:
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it.

**Comment by Rick-Anderson** [comment]
> Looking over, we'll want [tabs](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.4&tabs=azure-portal%2Crhel#tabpanel_3_rhel) for Ubuntu and RHEL [here](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#ubuntu-trust-the-certificate-for-service-to-service-communication) using the fedora section [here](https://github.com/dotnet/aspnetcore/issues/32842#issue-895287688). 

I can handle the tabs, just need help with the instruction. I also have to do SLES https://github.com/dotnet/AspNetCore.Docs/issues/28292

**Comment by djgalvan** [comment]
See #[32842](https://github.com/dotnet/aspnetcore/issues/32842#issuecomment-1418161969)
