### ISSUE TITLE
Service Extension should use ConfigurationManager instead of IConfiguraiton in .NET 7

### ISSUE THREAD

**Issue by fchenGT** [dotnet/AspNetCore.Docs#28274]
The example under "[Combining service collection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#combining-service-collection)" won't work because

`
builder.Services.AddConfig(builder.Configuration).AddMyDependencyGroup();
` 

in .NET 7 builder.Configuration returns ConfigurationManager not IConfiguration.

However, the second parameter of the AddConfig is of type IConfiguration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 62415](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62415)

**Comment by Rick-Anderson** [comment]
@fchenGT  can you provide the correct code?

**Comment by fchenGT** [comment]
``` 
      public static IServiceCollection AddConfig(
             this IServiceCollection services, IConfiguration config)
        {
            services.Configure<PositionOptions>(
                config.GetSection(PositionOptions.Position));
            services.Configure<ColorOptions>(
                config.GetSection(ColorOptions.Color));

            return services;
        }
```

All you need to do is to change IConfiguration to ConfigurationManager for this method's parameter type.

**Comment by fchenGT** [comment]
Note that this happens because in your example the builder created using the new hosting model.
`var builder = WebApplication.CreateBuilder(args);`

If you still use the old hosting model describe in this section:
[var builder = WebApplication.CreateBuilder(args);](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0&tabs=visual-studio#use-startup-with-the-new-minimal-hosting-model)

Then this should still work:
`public static IServiceCollection AddConfig(this IServiceCollection services, IConfiguration config)`

Otherwise, with then new hosting model, you need to do:
`public static IServiceCollection AddConfig(this IServiceCollection services, ConfigurationManager config)`

**Comment by tdykstra** [comment]
@fchenGT The sample app this snippet comes from is here: 

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample

The code in question is here:

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index/samples/6.x/ConfigSample/Options/MyConfigServiceCollectionExtensions.cs#L8-L17

Changing the project to target net7.0 has no apparent impact on that code -- it compiles without error in both .NET 6 and 7 with the second parameter as IConfiguration or ConfigurationManager.  What problem would arise from leaving it as IConfiguration in .NET 7?

**Comment by fchenGT** [comment]
@tdykstra You are right. Disregard please!
It must be some weird intellisense issue/lag in VS 2022 that highlighted it as an error before I compiled the code.
It actually works fine in VS Code, the ConfigurationManager inherits IConfigurationRoot, which inherits IConfiguration. 
Hence the example is correct. Sorry for the false positive alert. Hope you have a wonderful day! :)
