### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by aldefrawy** [dotnet/AspNetCore.Docs#28287]
during appling this code:
@code {
    private ValueTask ShowPreview()
        => JS.InvokeVoidAsync("previewImage", inputFile!.Element, previewImageElem);
}

it didn't work untill i changed ValueTask  to void ... then it worked.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=server)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report on that, @aldefrawy ... I'll take a look today and get back to you. This might have happened when I was "translating" some code provided to me by the product unit into something to show in the doc. Sometimes, they send me an example for something that isn't so great as a documentation example. I then try to fix it up into a good doc example and end up 💥 their code by mistake 🙈😆. I try not to, but it does happen. I'll get back to you in a few hours.

**Comment by guardrex** [comment]
I did have a second to take a look before I go out.

No ... actually ... I didn't screw this one up! 😆 ...

https://github.com/dotnet/AspNetCore.Docs/pull/27923/files#diff-9012cebaab9cbf7514d15a5fe98bf0796212a89ab3de29029487d329f6cf9a4bR597

Tanay sent that over as returning a `ValueTask`.

Ok ... let me take a closer look when I return in a few hours and we'll see what's what. I can't ping him tho. He's not available. However, let me see if I can just repro it and make the change based on the behavior that you've reported.

**Comment by guardrex** [comment]
I think he meant to make that a `Task` ... and we can make this `async` with an `await` ...

```csharp
private async Task ShowPreview()
        => await JS.InvokeVoidAsync("previewImage", inputFile!.Element, previewImageElem);
```

**Comment by aldefrawy** [comment]
Yes you are right
Thanks

**Comment by guardrex** [comment]
Sure thing. I'm glad you asked about this because I would like to wrap-up that doc section with the fully-working, cut-'n-paste example of a component. That's easier for readers than piecing it together bit by bit when they want to play with the code.

**Comment by guardrex** [comment]
... and I'll attach the FN to `window` to make that simpler to play with, too ...

```javascript
window.previewImage = (inputElem, imgElem) => {
  const url = URL.createObjectURL(inputElem.files[0]);
  imgElem.addEventListener('load', () => URL.revokeObjectURL(url), { once: true });
  imgElem.src = url;
}
```

**Comment by aldefrawy** [comment]
Awesome, thanks!
