### ISSUE TITLE
Unable to connect to web server MvcProject

### ISSUE THREAD

**Issue by gaurav-space** [dotnet/AspNetCore.Docs#28284]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Part 5, work with a database in an ASP.NET Core MVC app](https://learn.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Hi @gaurav-space, thanks for taking the time to let us know you are running into an issue.  Looking at the link to the doc, it looks like you were going through the .NET 7.0 version of the tutorial and following the Visual Studio (Windows) tab of instructions.  Could you provide a bit of detail on what is happening and at what step?  Is there a specific error?  Thanks for any info you can provide.

**Comment by wadepickett** [comment]
Closing this issue for now.  This doc was just recently updated and tested.  If you can provide some details later, feel free to re-open.  Thanks.
