### ISSUE TITLE
Departments pages does not work after this module

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#28297]
After following this page, changing the up method in the migration, and running the dotnet ef database update, I looked at the person data and the data has indeed been moved over to that table.
But on the next page in Advanced Topics, it will not run the Departments page now.
It says Instructor is an invalid object name.
I cut and pasted the migration code as is from the tutorial.

This is the current code in Departments/Index that fails:
        public async Task<IActionResult> Index()
        {
            var schoolContext = _context.Departments.Include(d => d.Administrator);
            return View(await schoolContext.ToListAsync());
        }
 
Disappointing because the whole reason I went through this tutorial was to see Dynamic Linq queries. Now I can't move on to it.
It took a long time to get to this point.  The estimated times on these pages is way underestimated.  8 minutes and 13 minutes is rediculous.  It takes me hours per page if you want to really understand it and not just type it in and make it work.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [Tutorial: Implement inheritance - ASP.NET MVC with EF Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-7.0)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Will be fixed under #26505
