### ISSUE TITLE
Add app.MapGet("/todoitems/complete to DTO sample

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28303]
See [code](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs#L12-L16)

[GetCompleteTodos](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todoDTO/Program.cs#L29-L31) was added in #28271, but no endpoint was added.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 62456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62456)

**Comment by dersonmutemba** [comment]
Alright sir. Let me fix it
