### ISSUE TITLE
Remove steps to create and use a TLS certificate for HTTPS

### ISSUE THREAD

**Issue by GerardFR** [dotnet/AspNetCore.Docs#28307]
The **Host in Azure App Service with a custom domain and certificate** section has 16 steps, which is a lot. Some of them concern creating and using a certificate for HTTPS. I believe this is another topic that only brings confusion here (or it could be in a separate section for completeness).
I followed the steps keeping only the self-signed certificate for Identity Server, and it works well. I also kept the default xx.azurewebsites.net domain name (I'll move to a custom domain name when the application is ready), so I didn't need a certificate for HTTPS as it was already supplied.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9638772f-0f1e-c2a9-8a58-ae8c3e37ae28
* Version Independent ID: 7a5b169e-08cb-cdba-4501-88d3da2723bb
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Identity Server](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-7.0&tabs=visual-studio#host-in-azure-app-service-with-a-custom-domain-and-certificate)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-identity-server.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GerardFR ... Thanks for the feedback, but we're keeping this for devs who require the guidance. Piecing the steps together from external docs was very challenging for the exact use case that this covers (which is clearly indicated by the section's heading and lead-in remarks), and this cleared things up for multiple devs who opened issues asking for the coverage. At this point, we just want to adjust it for any changes that are required as new versions of .NET roll out and as the Azure portal/features evolve. Thanks again tho for the feedback.
