### ISSUE TITLE
Missing registration of implementator of IValidateOptions

### ISSUE THREAD

**Issue by ogysha** [dotnet/AspNetCore.Docs#28312]
In the section [ValidateOnStart](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#validateonstart), there is a code block that is correct but is not complete, thus misleading: it lacks a statement from the code block from above:

`builder.Services.AddSingleton<IValidateOptions<MyConfigOptions>, MyConfigValidation>();`

Our team got false positive test results on the validation of our options class, where we had a bug in `MyConfigValidation.Validate` method. The test run went successfully because `Validate` method was never called if `MyConfigValidation` is not registered in DI container.

So the complete and correct solution is:

```
builder.Services.AddSingleton<IValidateOptions<MyConfigOptions>, MyConfigValidation>();

builder.Services.AddOptions<MyConfigOptions>()
    .Bind(builder.Configuration.GetSection(MyConfigOptions.MyConfig))
    .ValidateDataAnnotations()
    .ValidateOnStart();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you need to validate Data Annotation, you need to specify that, as in the sample in the article

```
using OptionsValidationSample.Configuration;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllersWithViews();

builder.Services.AddOptions<MyConfigOptions>()
            .Bind(builder.Configuration.GetSection(MyConfigOptions.MyConfig))
            .ValidateDataAnnotations()
        .Validate(config =>
        {
            if (config.Key2 != 0)
            {
                return config.Key3 > config.Key2;
            }

            return true;
        }, "Key3 must be > than Key2.");   // Failure message.

var app = builder.Build();
```

**Comment by ogysha** [comment]
Thanks for the clarification but I think I wasn't clear enough on the exact issue.
Let me try to explain it in more detail via example.
We have:

```
public class MyConfigOptions : IValidateOptions<MyConfigOptions>
{
   public string Foo {get; set;}
   public string Bar {get; set;}
   ...

   public ValidateOptionsResult Validate(string name, MyConfigOptions options)
   {
   	// here we do non trivial validation and
	// early exits with return ValidateOptionsResult.Fail(nameof(Foo));
	
	
	return ValidateOptionsResult.Success;
   }
}
```

We've chosen that MyConfigOptions class implements `IValidateOptions` due to the encapsulation principle: we don't want feature envy smell and we want high cohesion on this design decision.
We do not rely in this particular case on attributes.

Now, as we found out the following snippet is not enough for validation to be triggered:
```
services.AddOptions<MyConfigOptions>()
	.Bind(configuration.GetSection(MyConfigOptions.MyConfig))
        .ValidateOnStart();
```
We need to also add:
```
services.AddSingleton<IValidateOptions<MyConfigOptions>, MyConfigOptions>();
```

Thus, I conclude that in section [ValidateOnStart](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#validateonstart) where the usage of that method is described, it definitely should be covered a case to use if one is just relying on `IValidateOptions<>`, not data attributes. That said, it lacks the line of registering explicitly IValidateOptions<> as in the code snippet above.

Hope that the above description gives more information on the real subject of the issue.
