### ISSUE TITLE
Update review date

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28322]
Update date on [this line](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md?plain=1#L6)

@dersonmutemba can you take this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 62947](https://dev.azure.com/msft-skilling/Content/_workitems/edit/62947)

**Comment by dersonmutemba** [comment]
Doing. Sorry for being late. Had some busy days

**Comment by Rick-Anderson** [comment]
@dersonmutemba  It doesn't look like the change was big enough to get you on the contributors list, but I'll figure out something. Maybe the list is slow to update.

**Comment by dersonmutemba** [comment]
@Rick-Anderson no problem. I'm fine with it hehe

**Comment by Rick-Anderson** [comment]
It's slow to update
<img width="259" alt="image" src="https://user-images.githubusercontent.com/3605364/218288898-96a69d59-b92f-4b6e-a1bd-a00b41b50f20.png">
