### ISSUE TITLE
Documentation for `ActivityTrackingOptions.Tags`

### ISSUE THREAD

**Issue by nZeus** [dotnet/AspNetCore.Docs#28320]
Hello,

There is absolutely no documentation on how to use `ActivityTrackingOptions.Tags` and `Baggage`.
How to add tags?

I think this is a crucial information that is missing to use the feature

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [LoggerFactoryOptions.ActivityTrackingOptions Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactoryoptions.activitytrackingoptions?view=dotnet-plat-ext-7.0#microsoft-extensions-logging-loggerfactoryoptions-activitytrackingoptions) (Link in the article) and [Automatically log scope with SpanId, TraceId, ParentId, Baggage, and Tags.](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#automatically-log-scope-with-spanid-traceid-parentid-baggage-and-tags) from the article.

**Comment by nZeus** [comment]
I've seen those, but they don't explain how to add tags or fill in the Baggage. No info on that at all.

**Comment by Rick-Anderson** [comment]
Gets or sets the activity tracking options to indicate which parts of the tracing context information should be included with the logging scopes.
