### ISSUE TITLE
Correction under Files created and updated heading "The scaffold process adds the following highlighted code to the Startup.cs file"  under 

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#28357]
---
**Issue moved from MicrosoftDocs/feedback#3892**
- Please respond to @abhiroy4.

---

_From @abhiroy4 on Saturday, January 28, 2023 5:43:58 PM_

**Describe** the bug**
Correction of file name as Startup.cs under Part 2, add a model to a Razor Pages app in ASP.NET Core section => "Files created and updated" heading wherever Program.cs filename is mentioned. Below is the correction;

- The scaffold process adds the following highlighted code to the **Startup**.cs file:

- The **Startup**.cs changes are explained later in this tutorial.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3892**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Saturday, January 28, 2023 5:43:59 PM_

Thank you for opening an issue! One of our team members will get back to you with additional information.
  
If this is a product issue, please close this issue and contact the product's support instead. For a list of support websites, see [Support for Microsoft products and apps](https://support.microsoft.com/all-products).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3892**
- Please respond to @gewarren.

---

_From @gewarren on Saturday, February 11, 2023 3:02:40 AM_

This looks to be about https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio.

**Comment by Rick-Anderson** [comment]
Program.cs replaced Startup a couple version past.
