### ISSUE TITLE
table-success css class

### ISSUE THREAD

**Issue by Nianwei** [dotnet/AspNetCore.Docs#28353]
In the view code for displaying courses, the selectedRow part is incorrect. Should be "table-success" then it will highlight correctly. 
```
 if (item.CourseID == (int?)ViewData["CourseID"])
 {
                selectedRow = "success";
}
```
Should be
```
 if (item.CourseID == (int?)ViewData["CourseID"])
 {
                selectedRow = "table-success";
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f988f508-f5be-9961-830d-aa569adfcce9
* Version Independent ID: 823ce300-dcb9-b51d-fe4b-5bb4625a8126
* Content: [Tutorial: Read related data - ASP.NET MVC with EF Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/read-related-data?view=aspnetcore-6.0)
* Content Source: [aspnetcore/data/ef-mvc/read-related-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
All issues are tracked in the next rewrite at #26505
