### ISSUE TITLE
українська

### ISSUE THREAD

**Issue by DudkaP** [dotnet/AspNetCore.Docs#28366]
[Введіть відгук тут]
немає української мови

---
#### Відомості про документ

⚠ *Не змінюйте цей розділ. Він необхідний, щоб пов’язувати сторінки learn.microsoft.com і проблеми на GitHub.*

* ID: c165f8e4-d058-27b2-ee9b-1bbed0996f1f
* Version Independent ID: faed8bb0-79ef-7af4-5deb-e7645cdf2e39
* Content: [Overview of ASP.NET Core](https://learn.microsoft.com/uk-ua/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-7.0)
* Content Source: [aspnetcore/introduction-to-aspnet-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/introduction-to-aspnet-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DudkaP ...

That's correct. I think you are the second or third person to ask about it. We don't control that here. There are open issues on the Microsoft general feedback GitHub repository. Take a look at the following issues ...

> Це правильно. Я думаю, що ви другий чи третій, хто запитує про це. Ми тут це не контролюємо. У сховищі загальних відгуків Microsoft GitHub є відкриті проблеми. Зверніть увагу на наступні проблеми...

> Tse pravylʹno. YA dumayu, shcho vy druhyy chy tretiy, khto zapytuye pro tse. My tut tse ne kontrolyuyemo. U skhovyshchi zahalʹnykh vidhukiv Microsoft GitHub ye vidkryti problemy. Zvernitʹ uvahu na nastupni problemy...

https://github.com/MicrosoftDocs/feedback/issues?q=is%3Aissue+Ukrainian+
