### ISSUE TITLE
HttpContext not working in Kestrel in Visual Studio Code

### ISSUE THREAD

**Issue by Ninja4Code** [dotnet/AspNetCore.Docs#28365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have set up Windows authentication with the Negotiate package but in Kestrel I am noticing that the HttpContext gets dropped after the initial ClaimsTransformation works.  It's later down the pipeline where I'm not getting the context.User in the AuthorizationRoleHandler.  This worked in ASP.NET Core 5/IIS with essentially the same code, except Program was split into Startup, etc.

**I'm noticing that the AuthenticationType is showing as NTLM.  My understanding is that Kerberos will try Negotiate first and will fall back to NTLM.  This seems to be occuring as I see NTLM listed as the AuthenticationType when I'm debugging.**

`builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();`

I'm also wiring up a Claims Transformer.

`builder.Services.AddSingleton<IClaimsTransformation, MyClaimsTransformer>();`

Within the Claims transformer everything is working fine.  It picks up the user identity and assigns the claims;

```
public class MyClaimsTransformer : IClaimsTransformation
{
    public Task<ClaimsPrincipal> TransformAsync(ClaimsPrincipal principal)
    {
         ClaimsIdentity identity = principal.Identity as ClaimsIdentity;
         //add claims
        return Task.FromResult(principal);
    }
}
```

I've also wired up an HttpContextAccessor

`builder.Services.AddHttpContextAccessor();`

```
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = options.DefaultPolicy;
    options.AddPolicy("AuthenticatedOnly", policy => {
          policy.Requirements.Add(new AuthenticatedRequirement(true));
    ]);
]);
```

builder.Services.AddSingleton<IAuthorizationHandler,AuthenticatedRoleHandler>();`

The problem comes in where I'm using Policies with Requirements.  The AuthorizationRoleHandler is not picking up the user from the context.  This behavior I notice in Visual Studio Code with ASP.NET Core 6.  In a similar project in Visual Studio 2019, ASP.NET Core 5 the basically same code works as expected.  I'm also noticing this behavior when I deploy the application in a Docker container with Kestrel.

```
public class AuthenticatedRoleHandler:AuthorizationHandler<AuthenticatedRequirement>
{
     protected override Task HandleRequirementAsync(AuthorizationContext context, AuthenticatedRequirement requirement)
    {
             **ClaimsPrincipal user = context.User;//Here it is null**
             // other code
     }
}
```

### Expected Behavior

The role handler should be picking up the AuthorizationHandlerContext user, but it is null.

```
public class AuthenticatedRoleHandler:AuthorizationHandler<AuthenticatedRequirement>
{
     protected override Task HandleRequirementAsync(AuthorizationContext context, AuthenticatedRequirement requirement)
    {
             **ClaimsPrincipal user = context.User;//Here it is null**
             // other code
     }
}
```

### Exceptions (if any)

I get a 401 status code Unauthorized on an annotated controller method.

### Anything else?

6.0.13 runtime
6.0.402 sdk

***EDIT by @Rick-Anderson*

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?branch=pr-en-us-28705&view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 70835](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70835)

**Comment by davidfowl** [comment]
@Ninja4Code feel free to suggest a doc change.

**Comment by Rick-Anderson** [comment]
@Ninja4Code can you suggest a change to [Kestrel web server implementation in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-7.0)?

**Comment by Ninja4Code** [comment]
Sure, I'm putting something together right now.  It will probably be more than you need but you can edit it if you like.  Give me about an hour or so.

**Comment by Rick-Anderson** [comment]
> Sure, I'm putting something together right now. It will probably be more than you need but you can edit it if you like. Give me about an hour or so.

Awesome, no hurry.

**Comment by Ninja4Code** [comment]
[windows-auth-kestrel.docx](https://github.com/dotnet/AspNetCore.Docs/files/10717523/windows-auth-kestrel.docx)

**Comment by Ninja4Code** [comment]
This is what I view as a separate issue but is somewhat related to what I posted here.  I am now having an issue with Negotiate working on the http port 80 but not on the https port 443.  Should I create a new issue?

**Comment by Rick-Anderson** [comment]
@Ninja4Code Create an issue in https://github.com/dotnet/AspNetDocs/issues/809
Provide a link to a public repo that contains the simplest possible sample that demonstrates the problem.

cc @Tratcher  in case he has other ideas.

**Comment by Ninja4Code** [comment]
That link is for documentation though?

**Comment by Ninja4Code** [comment]
But I think I discovered something in the logging.  It's creating an HTTP/2 request when I use https and I read that Kerberos does not support that.  If I launch an http request on 80 that's an HTTP/1.1 and that goes through.

**Comment by Tratcher** [comment]
You're correct, Kerberos doesn't work over HTTP/2. You should disable HTTP/2 in Kestrel.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#listenoptionsprotocols

**Comment by davidfowl** [comment]
@Tratcher is this in our docs?

**Comment by Rick-Anderson** [comment]
> @Tratcher is this in our docs?

No it doesn't. #28408 I'll have @Tratcher  review my update

**Comment by Ninja4Code** [comment]
The one difference I would make in the documentation is that for the setspn statement that it needs to be the user account either running the application, app pool or container.  I think it mentions in the ASP.NET Core documentation that Kerberos is a user-based authentication, rather than kernel-based.

**Comment by Ninja4Code** [comment]
I was able to completely resolve the Kerberos issue in the Docker container with a registered SPN to the docker container host  machine with a GMSA account.  I can confirm this.
