### ISSUE TITLE
Link to spanish version of mdn CORS article even though my language is english

### ISSUE THREAD

**Issue by AndrewLamWARC** [dotnet/AspNetCore.Docs#28363]
[Enter feedback here]
Linking to https://developer.mozilla.org/es/docs/Web/HTTP/CORS
instead of https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AndrewLamWARC ... Check your browser settings because every link in this topic to MDN doesn't state the localization segment ...

https://github.com/dotnet/AspNetCore.Docs/edit/main/aspnetcore/security/cors.md

**Comment by AndrewLamWARC** [comment]
Yes, it's an issue at mdn.
The link is to https://developer.mozilla.org/docs/Web/HTTP/CORS (no language segment) and my accept-language header is en-GB,en-US;q=0.9,en;q=0.8
However, mdn still immediately 302 redirects me to the spanish version.

Thanks for looking into this.
