### ISSUE TITLE
ASP0014 triggered even when no routes are actually registered

### ISSUE THREAD

**Issue by iSOcH** [dotnet/AspNetCore.Docs#28364]
Under certain circumstances, the user wants to control the position of `EndpointMiddleware` in the middleware pipeline, for example when a ("catch-all") terminal middleware is registered from user code which should only be executed when no endpoint matches.

My concrete case:
```
...
app.MapControllers();

// without this, WebApplicationBuilder will add EndpointMiddleware at the end of the pipeline
// UseProxyToSpaDevelopmentServer adds a terminal middleware, this will block access to
// the controllers
// docs say it's fine to call this method, but then it seems very weird that 
// ASP0014 rule says you should never ignore its warnings 🤦
// https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-7.0
#pragma warning disable ASP0014 // we need EndpointMiddleware before UseProxyToSpaDevelopmentServer
app.UseEndpoints(_ => {});
#pragma warning restore ASP0014

app.UseSpa(spa => {
    if (builder.Environment.IsDevelopment())
        spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
});

app.Run();
```

Ideally, ASP0014 should only be triggered when the user actually adds mappings. Alternatively, the documentation should mention such a use case instead of the general `Do not suppress a warning from this rule.`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Version Independent ID: 16b83e45-7b75-639c-dc8d-cc691fd40222
* Content: [ASP0014: Suggest using top level route registrations](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0014?view=aspnetcore-7.0)
* Content Source: [aspnetcore/diagnostics/asp0014.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0014.md)
* Product: **aspnet-core**
* GitHub Login: @captainsafia
* Microsoft Alias: **safia**

**Comment by captainsafia** [comment]
> Ideally, ASP0014 should only be triggered when the user actually adds mappings. Alternatively, the documentation should mention such a use case instead of the general Do not suppress a warning from this rule.

Agreed! We got similar feedback around making the analyzer more particular about what it triggers on and are tracking making the change in the framework over at https://github.com/dotnet/aspnetcore/issues/46270.

I've opened https://github.com/dotnet/AspNetCore.Docs/pull/28438 to update the docs.
