### ISSUE TITLE
Use SQLite for development, SQL Server for production (AVOID in tutorial)

### ISSUE THREAD

**Issue by jsuddsjr** [dotnet/AspNetCore.Docs#28379]
The section entitled *Use SQLite for development, SQL Server for production* opens a can of worms that the tutorial doesn't address. EF migrations for SQL Server are not compatible with SQLite, so naively suggesting that the user should make this change while completing an introductory tutorial will cause more problems than they are prepared to solve, nor do you adequately explain the pitfalls of doing so.

* Setting up a DbContext for each provider
* Passing additional arguments to the EF commands
* Managing multiple appsettings files, with unique connection strings
* (etc)

RECOMMEND: I would avoid this subject entirely. Migrations with multiple providers deserves its own standalone tutorial. See https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?source=recommendations&tabs=dotnet-core-cli   

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 87022](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87022)

**Comment by wadepickett** [comment]
Hi @jsuddsjr, thanks for the suggestion.  I do agree that this series of tutorials feels a bit like it is trying to do too much at some points, this being one of them.  For this subject, as you say, we could just mentioned there is a developing-in-the-real-world consideration to be aware of and link to dedicated topic on the subject.  We will be updating this series of tutorials for .NET 8.0 Preview soon, that will give us a chance to rethink this tutorial series a bit, so good timing.

**Comment by Rick-Anderson** [comment]
> The section entitled _Use SQLite for development, SQL Server for production_ opens a can of worms that the tutorial doesn't address. EF migrations for SQL Server are not compatible with SQLite, so naively suggesting that the user should make this change while completing an introductory tutorial will cause more problems than they are prepared to solve, nor do you adequately explain the pitfalls of doing so.
> 
> * Setting up a DbContext for each provider

`DbContext` is the same.

> * Passing additional arguments to the EF commands

How is that relevant?

> * Managing multiple appsettings files, with unique connection strings

That's easy, see 
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu60/appsettings.json#L9-L10
and 
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro/samples/cu60/appsettings.Development.json#L9-L10

> * (etc)
Such as?

We should add a link to [Migrations with Multiple Providers](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?source=recommendations&tabs=dotnet-core-cli)

**Comment by wadepickett** [comment]
" _We should add a link to [Migrations with Multiple Providers](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?source=recommendations&tabs=dotnet-core-cli)_"
 
Good point. Will add something like this to end of VSC/VS for Mac initial migration section:

For more information on maintaining multiple providers such as Microsoft SQL Server and SQLite, see [Migrations with Multiple Providers](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?source=recommendations&tabs=dotnet-core-cli)
