### ISSUE TITLE
Need clarification: section "Default BadRequest response"

### ISSUE THREAD

**Issue by newpowera** [dotnet/AspNetCore.Docs#28395]
[Enter feedback here]

In the section "Default BadRequest response", the description above the first JSON example looks like this:
**"The following response body is an example of the serialized type:"**,
which is not clear.

Seems like the JSON example it's trying to explain is the JSON response format for model validation failure's BadRequest before ASP.NET Core 2.2, which is an array of plain strings as the value of the KeyValuePair. I am suggesting updating this information in the description.

This description is correct in this document before version ASP.NET Core 3.0, then this issue happens in this document's version from ASP.NET Core 3.0.

Thanks,
Wei

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Create web APIs with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 88859](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88859)

**Comment by postmeback** [comment]
Shall I take it up? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
> Shall I take it up? @Rick-Anderson

Yes
