### ISSUE TITLE
Add .NET MAUI Blazor deep linking guidance 9.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#28401]
Per https://github.com/dotnet/maui/issues/3788#issuecomment-1421550198

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48146c6d-f864-0b56-a2d5-0493a843c7a7
* Version Independent ID: 48146c6d-f864-0b56-a2d5-0493a843c7a7
* Content: [ASP.NET Core Blazor Hybrid routing and navigation](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The PU has moved this to the .NET 9 Planning milestone.

**Comment by BethMassi** [comment]
@guardrex recently @Redth on the MAUI team provided this guidance for deep linking, can we use this to incorporate into the docs? https://github.com/redth/maui.applinks.sample

**Comment by guardrex** [comment]
Sure thing. That looks great as the basis for a new article.

What's the demand/priority? Can it wait a week? I'm mired this week in setting up the Blazor Web App snippet sample app and linking to it for all of the code snippets across the docs. I'm free next week if that's ok.

**Comment by BethMassi** [comment]
Priority is getting higher (hence why Jon wrote this up) but I'd say ya, totally can wait a week.
