### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by alimakyol** [dotnet/AspNetCore.Docs#28412]
_SelectLanguagePartial cannot find the languages.

In program.cs, below code should be added for it to work.

builder.Services.Configure<RequestLocalizationOptions>(options =>
	{
		var supportedCultures = new[]
		{
				new CultureInfo("en-US"),
				new CultureInfo("tr-TR")
		};
		options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
		options.SupportedCultures = supportedCultures;
		options.SupportedUICultures = supportedCultures;
	});

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
@alimakyol which sample you refer to?

**Comment by alimakyol** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0

Best Regards,
Alim Akyol

**Comment by hishamco** [comment]
AFAIK the localization sample is not been updated since `3.x` it's in my list, I will push two PR ASAP

**Comment by hishamco** [comment]
@Rick-Anderson I just added a sample for `6.x`, then test it, everything working as expected. I might create one for `5.x` even it's not supported now (for consistency purpose)

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I just added a sample for `6.x`, then test it, everything working as expected. I might create one for `5.x` even it's not supported now (for consistency purpose)

I wouldn't, we've got bigger fish for you to fry. Do it if you want though.
