### ISSUE TITLE
Not clear if the rate limit applies on the endpoint generally or per user

### ISSUE THREAD

**Issue by Asim-A** [dotnet/AspNetCore.Docs#28415]
I cannot completely understand whether the contents' examples apply to an endpoint in the general sense or if it applies per user. User through e.g. some identifier in the claims or IP-address maybe. 

I want to implement this in my solution, and I want the rate limit to apply using some unique claim in the HttpContext. I this possible using one of the rate limiting techniques described in the docs content?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Version Independent ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Content: [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You can limit on anything you want. In the doc

`        if (context.User.Identity?.IsAuthenticated is true)`
