### ISSUE TITLE
Add localization sample for 5.x

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28426]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 64419](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64419)

**Comment by hishamco** [comment]
Needs to be closed

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/AspNetCore.Docs/pull/28423
