### ISSUE TITLE
Sample: JSON extension methods for HttpRequest and HttpResponse

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28424]
Demonstrate the following APIs:

* Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync
* Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.HasJsonContentType
* Microsoft.AspNetCore.Http.HttpRequestJsonExtensions.ReadFromJsonAsync
* Customize serialization for an endpoint: 
  * `WriteAsJsonAsync` and `ReadFromJsonAsync` overloads that accept `System.Text.Json.JsonSerializerOptions`
  * Call `Results.Json` and pass it a `JsonSerializerOptions` object
* Customize serialization globally
  * Microsoft.Extensions.DependencyInjection.HttpJsonServiceExtensions.ConfigureHttpJsonOptions
  * Use `JsonOptions` directly for global serialization options, e.g. `builder.Services.Configure<JsonOptions>(options =>`
* How to work with JsonNode / JsonElement in a scenario like the one described in https://github.com/dotnet/runtime/issues/81968

Sample code goes in https://github.com/dotnet/AspNetCore.Docs/tree/main/fundamentals/minimal-apis/basic-json-apis/samples/7.x

---
[Associated WorkItem - 64399](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64399)

**Comment by Rick-Anderson** [comment]
@tdykstra  looks fun. What document should this go in?
cc @sammychinedu2ky  @fiyazbinhasan  in case one of you wants to write a fun sample.

**Comment by tdykstra** [comment]
> @tdykstra looks fun. What document should this go in? 

We have https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-7-0#httpclient-and-httpcontent-extension-methods

However, I think a new how-to-use-System.Text.Json-with-ASP.NET-Core article might be worth doing. It could show this and other aspects of using JSON in an ASP.NET Core app.

**Comment by tdykstra** [comment]
I'll come up with some additional functionality to show.

**Comment by tdykstra** [comment]
Two ways to set serializer options, as shown here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-7.0#configure-json-serialization-options

**Comment by tdykstra** [comment]
And how to work with JsonNode / JsonElement in a scenario like the one described here: https://github.com/dotnet/runtime/issues/81968
