### ISSUE TITLE
System.Text.Json integration is incomplete.

### ISSUE THREAD

**Issue by michaelcsilva** [dotnet/AspNetCore.Docs#28439]
The System.Text.Json example is incomplete and not useable end-to-end.  The example leads to a broken swagger display of the JSON patch format when using Swashbuckle, meaning API consumers are given incorrect information on what data to provide. 

The prototype given in swashbuckle's swagger is:
```
{
   "operations": [
      {
      "operationType": 0,
      "path": "string",
      "op": "string",
      "from": "string",
      "value": "string"
     }
   ],
   "contractResolver": []
}

```

This is not the JSON patch format.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 593f528c-61b9-7021-335d-c1c0ec1814d1
* Version Independent ID: 6a88d237-1a03-b865-e3c5-20ceedef2a1f
* Content: [JsonPatch in ASP.NET Core web API](https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/jsonpatch.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/jsonpatch.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 65412](https://dev.azure.com/msft-skilling/Content/_workitems/edit/65412)

**Comment by Rick-Anderson** [comment]
@tdykstra  please review

**Comment by jeffhandley** [comment]
Routing to @dotnet/area-system-text-json for the crew to nominate a team member to review this.

**Comment by eiriktsarpalis** [comment]
Looking at the doc in question, there is no System.Text.Json JSON Patch integration as such, instead it provides a workaround for using the Newtonsoft provider while still falling back to STJ for everything else. 

@michaelcsilva I think the issue you're referring to however concerns Swashbuckle not detecting that configuration correctly? If that's the case, I would recommend you open an issue with the [Swashbuckle maintainers](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) instead as it is not a tool maintained by Microsoft.
