### ISSUE TITLE
Not working on IIS / Server 2022

### ISSUE THREAD

**Issue by gignat** [dotnet/AspNetCore.Docs#28442]
If you use provided code for Blazor WebAssembly to upload file to a server and it is working perfect on developer's machine BUT it does not work on 2022 server with IIS, try this
replace 
var response = await Http.PostAsync("/Filesave", content);
with 
var response = await Http.PostAsync("/filesave", content);
Yes, the api endpoint should be all lowercase!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor file uploads](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-7.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gignat ... I don't quite follow. Exactly what's the problem?

**Comment by guardrex** [comment]
Are you merely remarking on the format (casing) of the URL, or are you reporting an upload failure? If it's an upload failure, then did you investigate further (e.g., logging on the server)?

**Comment by guardrex** [comment]
If you're just reporting that you need the app to make the URLs all lowercase, try this ...

```csharp
builder.Services.AddRouting(options =>
    {
        options.LowercaseUrls = true;
        options.LowercaseQueryStrings = true;
    });
```

I'm going to close because I think you're merely reporting a problem with the URL casing, and that's not a focus of the guidance here.

**Comment by guardrex** [comment]
Unfortunately, I just found out that the Blazor Router doesn't provide a `RouteOptions` feature. You'll need to adjust hard-coded URL paths for the server that you're using, use rewriting on the server, or change IIS behavior to case-insensitive routing.

**Comment by gignat** [comment]
Of course I investigated on the server: that api endpoint is not hit at all as long as the url is not entirely lowercase. 
Not saying it is a bug, but merely the sample code provided will work in development but will fail on IIS/2022 Server.

**Comment by guardrex** [comment]
# 🤔 

Hummmmmmmmmmmm ....

Well, I'm not opposed to making this and all of the endpoint links lowercase for Blazor's `HttpClient` calls, in this doc and the other docs. Kestrel is fine with it. It would open up the IIS case. Still tho, that's a significant change given that the Blazor project templates configured to make such a call in the Weather Forecast Service example cases the request URL ...

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Client/Pages/FetchData.razor#L58

Let me ask on this point what Dan thinks about it. We don't want to make a sweeping change like this without careful consideration ... ***i.e., ask the boss!*** 🤣 

However, let me ping him next week. We're on the three-day holiday weekend now for President's Day. It's the last day off we formally get until Memorial Day.

**Comment by guardrex** [comment]
@gignat ... Are you sure that you don't have a rewrite rule in place on the server? IIS should be case sensitive but not be enforcing all lowercase URLs without some "help" ... e.g., URL Rewriting Module.
