### ISSUE TITLE
Update tutorial to use the new .NET Upgrade Assistant VS extension

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#28448]
This incremental migration tutorial needs to be updated to be based on the new .NET Upgrade Assistant VS extension: https://devblogs.microsoft.com/dotnet/upgrade-assistant-now-in-visual-studio/

Note that there is a related topic in the .NET Upgrade Assistant docs for ASP.NET Core. I've opened https://github.com/dotnet/docs/issues/34164 to track updating that doc as well. We should try to avoid duplicating content across these two docs if possible. Maybe this one should just point to the .NET UA doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aac48416-a842-31e5-f00a-84deb3701d9c
* Version Independent ID: aac48416-a842-31e5-f00a-84deb3701d9c
* Content: [Get started with incremental ASP.NET to ASP.NET Core migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/start?view=aspnetcore-7.0)
* Content Source: [aspnetcore/migration/inc/start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 67559](https://dev.azure.com/msft-skilling/Content/_workitems/edit/67559)

**Comment by Rick-Anderson** [comment]
The bulk of the work will be in #28608
