### ISSUE TITLE
Prerequistes information missing

### ISSUE THREAD

**Issue by arung2207** [dotnet/AspNetCore.Docs#28440]
The installation prerequisites information is missing. Is it enough to install only the ASP.NET web development workload? Do we need the Node.js workload? What about Angular CLI? Can we install these outside of Visual Studio? What if we need to upgrade NPM and Angular CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use Angular with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/angular?source=recommendations&view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by Rick-Anderson** [comment]
Dup of #25028
