### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by ygoe** [dotnet/AspNetCore.Docs#28451]
https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0#set-up-conventional-route

> See [Route Template Reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0#route-template-reference) for a detailed description of route template syntax.

Clicking on the link displays the desired heading text for a brief moment, then it disappears and cannot be found anymore on the page. The URL anchor is also dead and does not scroll anywhere. I suspect it only exists in another version that is hidden shortly after the page has loaded. In the end, the link is broken and does not lead to the content.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 64610](https://dev.azure.com/msft-skilling/Content/_workitems/edit/64610)

**Comment by Rick-Anderson** [comment]
I cannot reproduce. The link work.

**Comment by ygoe** [comment]
Can I attach you the complete HTML of the page I see, so you can verify it? The link is still broken here, the issue is **not** resolved.

**Comment by ygoe** [comment]
Still not working. The referenced content cannot be found anywhere on the target page. Also for .NET 8. Giving up.
