### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by timschwallie** [dotnet/AspNetCore.Docs#28457]
There's a lot of how to do's one this page.
However, the page seems to lack the why's?
Like why rename files extensions?

Maybe a troubleshooting tutorial would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @timschwallie ... I'm off today for the President's Day holiday. I'll get back to on Tuesday morning.

**Comment by guardrex** [comment]
Btw tho ... you only list one potential missing "why." I recommend calling out all of the "whys" that you think are missing. I'm very busy these days, and I can't react to general, open-ended feedback.

**Comment by timschwallie** [comment]
Sure. 
I noticed a couple.
Why do you need to rename the files from 'dll' to something else?
Various Firewalls place restrictions on downloading '.dll' files. Some Anti-Virus software will block downloading '.dll' files. Blazor Webassembly requires downloading many '.dll' files. To overcome these issues use https://github.com/stavroskasidis/BlazorWasmAntivirusProtection 
or https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebAssembly.MultipartBundle
or https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/main/doc/features-obfsucation.md
or the following technique with a post power shell script.
The usage of these tools will affect download performance and are more for uncontrolled environments, like the internet.

Why would you disable compression?
Need to think about this one. Hence, a little 'why' would help.

**Comment by guardrex** [comment]
Sorry ... the close of this was merely due to being on my phone while OOF ... ***fat fingers*** ✋ got the better of me! 😄

**Comment by guardrex** [comment]
Ok ... we're *BACK*.

We're not going to pitch specific services that we have no way to validate on security or quality. We pitch [Awesome Blazor](https://github.com/AdrienTorris/awesome-blazor) to devs to find third-party tools and packages.

I will add a remark about firewalls that block DLLs.

WRT compression: I don't know why, but I don't think it's important to mention something. If the dev must disable it, the guidance is in the section.
