### ISSUE TITLE
Replace this topic with (an existing one in .NET)

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/AspNetCore.Docs#28470]
This topic is a bit confusing, as its mixing the implementation of the sample together with how to use the API.

It turns out, that there is a better version of this content at 

https://learn.microsoft.com/en-us/dotnet/core/extensions/high-performance-logging

It would be good if the TOC can link you off to this topic instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48e02614-5cdd-0c85-3193-75a2325326b4
* Version Independent ID: fca176e2-c56e-0f17-de1b-e60912091e4b
* Content: [High-performance logging with LoggerMessage in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/logging/loggermessage.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/loggermessage.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
Thanks for the suggestion. I am switching the target of the TOC link to the other article.
