### ISSUE TITLE
Americentrism / US-centrism

### ISSUE THREAD

**Issue by ChristophLindemann** [dotnet/AspNetCore.Docs#28490]
If you use the "official" name for countries, you should do it for all countries. And not only for the United States of America and it's neighbors. Even though it might come as a surprise that the earth and the universe do not revolve around the US 😉

So for the  [Enum binding](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-7.0#enum-binding) I suggest

```csharp
using System.ComponentModel.DataAnnotations;

namespace FormsTagHelper.ViewModels
{
    public enum CountryEnum
    {
        [Display(Name = "United Mexican States")]
        Mexico,
        [Display(Name = "United States of America")]
        USA,
        Canada,
        [Display(Name = "French Republic")]
        France,
        [Display(Name = "Federal Republic of Germany")]
        Germany,
        [Display(Name = "Kingdom of Spain")]
        Spain
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-7.0#the-input-tag-helper)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ChristophLindemann** [comment]
Uh, oh

There I totally fell into the Ethnocentrism trap.

The example should of course not only consist of European countries and their American colonies, but also include European colonies from other continents.

**Comment by Rick-Anderson** [comment]
> their American colonies

??

@ChristophLindemann  all good points. We'll consider this the next time we do a major review. We review the last 15 closed issues on major reviews.
