### ISSUE TITLE
app.MapHub<yourhub> doesn't work like that anymore! The direct reference to app.MapHub is gone!

### ISSUE THREAD

**Issue by jajessup** [dotnet/AspNetCore.Docs#28494]
[Enter feedback here]
It is now:
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<yourhub>("/yourendpoint");
});

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by BrennanConroy** [comment]
> app.MapHub<yourhub> doesn't work like that anymore!

Yes it does, if you use `WebApplication` which the sample does.

**Comment by jajessup** [comment]
“This method is obsolete and will be removed in a future version. The recommended alternative is to use MapHub<THub> inside Microsoft.AspNetCore.Builder.UseEndpoints(...).”

 

Careful, this will just cause confusion as it did for me until I figured out what was going on.

**Comment by BrennanConroy** [comment]
That's a bit unfortunate, the obsolete message was made before `WebApplication` existed and made `UseEndpoints` optional.

But, the obsolete API was removed in 5.0 and only exists in 3.X which is out of support now, so it shouldn't be seen by many people.

**Comment by kenlnetherland** [comment]
Microsoft, please get better at updating your documentation.  I get that Agile has rendered documentation as an obsolete practice for most, but I get so tired of reading your conflicting docs.

https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0&tabs=visual-studio
