### ISSUE TITLE
A small modification is required in Culture fallback behavior section

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/AspNetCore.Docs#28508]
> Welcome.resx (if the NeutralResourcesLanguage is "fr-CA")

In specifying fallback culture for request with fr-CA, you specified that it first search for resource (fr-CA) and then (fr) and then default conditionally if Neutral Resources Language attribute set to fr-CA. But As I understand and tested, `NeutralResourcesLanguage` Attribute specify that select the mentioned culture in that attribute as the last resort. It can be simply an empty culture Identifier which packaged to main assembly or it can be any other language resources which packed by default as satellite assembly. So in the example the third option is Welcome.resx (if the `NeutralResourcesLanguage` is "") or if it is not empty then it is every culture which mentioned as Neutral Resource Language. 

**Simply to said, the quoted text should be replace with following:**

`Welcome.resx` (if the `NeutralResourcesLanguage` is "") OR any other resource which mentioned in `NeutralResourcesLanguage` Attribute for example en-GB

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
If you refer to the following:

Imagine your site receives a request for a "Welcome" resource using culture "fr-CA". The localization system looks for the > following resources, in order, and selects the first match:

Welcome.fr-CA.resx
Welcome.fr.resx
Welcome.resx (if the NeutralResourcesLanguage is "fr-CA")

I don't see any issue

**Comment by hishamco** [comment]
@abdollahkahne don't confuse between `NeutralResourcesLanguage` and `InvariantCulture`

**Comment by hishamco** [comment]
@abdollahkahne don't confuse between `NeutralResourcesLanguage` and `InvariantCulture`
