### ISSUE TITLE
Update validation sample to include Name and ShortName

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28514]
Update the model:

```
public class Contact
{
    public int Id { get; set; }

    public string Name { get; set; } = String.Empty;
    public string ShortName { get; set; } = String.Empty;
    public string Email { get; set; } = String.Empty;
    public string PhoneNumber { get; set; } = String.Empty;
}
```

Then have a validation check like:

```
        if (Contact.Name == Contact.ShortName) {
            ModelState.AddModelError(nameof(Contact.ShortName),
                                               "Short name can't be the same as Name.");
        }
```

Code at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/mvc/models/ModelStateError

It's easier to delete the existing code and create a new project and scaffold it.

Bonus points if you move from MVC to Razor Pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 66362](https://dev.azure.com/msft-skilling/Content/_workitems/edit/66362)

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  Let me know if you're interest in this.

I think the `Contact.Name == Contact.ShortName` is a more natural first example to show. The others would be better done by remote validation, but we won't do remote validation in this sample. It's good to show what you have, but after name/shortname check.

**Comment by sammychinedu2ky** [comment]
I should use this as the only sample validation in the code ? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
> I should use this as the only sample validation in the code ? @Rick-Anderson

No, add this check to the code you have.

**Comment by sammychinedu2ky** [comment]
> > I should use this as the only sample validation in the code ? @Rick-Anderson
> 
> No, add this check to the code you have. I'll show the DB check. This check won't require a call to the DB.

alright

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson you stated **Bonus points if you move from MVC to Razor Pages.** but then the following folder is under the MVC directory

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  actually keep your MVC sample and add the code to check the short name is not the same. For bonus points create a RP version in the https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/RazorPages folder of the same thing.

**Comment by sammychinedu2ky** [comment]
> @sammychinedu2ky actually keep your MVC sample and add the code to check the short name is not the same. For bonus points create a RP version in the https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/RazorPages folder of the same thing.

Alright chief

**Comment by Rick-Anderson** [comment]
Fixed in 28445
