### ISSUE TITLE
Explanation of Basic Routing incorrect

### ISSUE THREAD

**Issue by geertdoornbos** [dotnet/AspNetCore.Docs#28532]
This [documentation](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md) about routing basics is out of date. The explained UseRouting behavior is incorrect:

> However, apps can change the order in which UseRouting and UseEndpoints run by calling these methods explicitly. For example, the following code makes an explicit call to UseRouting: 
...
> If the preceding example didn't include a call to UseRouting, the custom middleware would run after the route matching middleware.

The order of execution is **not** changed.

_Originally posted by @geertdoornbos in https://github.com/dotnet/AspNetCore.Docs/issues/24539#issuecomment-1450347133_

***EDIT by @Rick-Anderson : Please open doc issues from the doc page to get the following meta-data***
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What's incorrect about the following:

However, apps can change the order in which `UseRouting `and `UseEndpoints ` run by calling these methods explicitly. For example, the following code makes an explicit call to `UseRouting`:

**Comment by geertdoornbos** [comment]
Hmmm, I misread the documentation I guess. The example is talking about route matching, not route execution. When reading the text, I assumed order of execution instead of matching.
