### ISSUE TITLE
Move Remote app session state snippets to project in samples folder

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28549]
[EDIT by guardex to fix a link (missing an opening bracket) and to add Blazor+Yarp]

See #28548
Create code for embedded snippets in the https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/migration/inc/samples folder

 Take the snippet code that right now is in a MD file and copy it to a project file so it compiles (and hopefully works), the do a PR to save the code in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/migration/inc/samples/remote folder. Don't worry about the MD file, I'll update that to use the new code files.

- [ ] [Wrapped ASP.NET Core session state](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/wrapped?view=aspnetcore-8.0)
- [ ] [ASP.NET to ASP.NET Core incremental session state migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/session?view=aspnetcore-8.0)
- [ ]  [Remote app session state](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-session?view=aspnetcore-8.0)
- [x] [Blazor with Yarp](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-7.0): Done on #28574.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65f9cf2c-ee58-0a74-3ada-c4d9114a0422
* Version Independent ID: 65f9cf2c-ee58-0a74-3ada-c4d9114a0422
* Content: [Remote app session state](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/remote-session?view=aspnetcore-8.0)
* Content Source: [aspnetcore/migration/inc/remote-session.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/remote-session.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39325afa-1628-c5ea-dcaf-d79a404a8193
* Version Independent ID: 39325afa-1628-c5ea-dcaf-d79a404a8193
* Content: [ASP.NET to ASP.NET Core incremental session state migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/session?view=aspnetcore-8.0)
* Content Source: [aspnetcore/migration/inc/session.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/session.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a2ce838-5dfd-bc85-d0f4-5e208e1692bf
* Version Independent ID: 9a2ce838-5dfd-bc85-d0f4-5e208e1692bf
* Content: [Wrapped ASP.NET Core session state](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/wrapped?view=aspnetcore-8.0)
* Content Source: [aspnetcore/migration/inc/wrapped.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/wrapped.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
cc @davethieben if you're interested.

**Comment by davethieben** [comment]
> cc @davethieben if you're interested.

what needs to happen? move each code block to a separate file in git and update the markdown to reference the files?

**Comment by Rick-Anderson** [comment]
@davethieben it's easier than that. Take the snippet code that right now is in a MD file and move it to a project file so it compiles (and hopefully works), the do a PR to save the code in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/migration/inc/samples/remote folder.

 #28574 did that for the Blazer Yarp snippet. In that case it was just one file.

I'll fixup the MD file to reference the snippet rather than a copy of the code in the MD file. You're welcome to do that step too if you like. See  #28574 for an example where `@guardrex` replaced the snippet with a code file.

**Comment by Rick-Anderson** [comment]
@davethieben  let me know if you're interested and if I can help.
