### ISSUE TITLE
Edit pass of Blazor Support in Incremental Migration

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28565]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Version Independent ID: 79fad59a-5573-2f8a-5c8b-f444cc98ea3b
* Content: [Blazor Support in Incremental Migration](https://learn.microsoft.com/en-us/aspnet/core/migration/inc/blazor?view=aspnetcore-8.0&branch=pr-en-us-28535)
* Content Source: [aspnetcore/migration/inc/blazor.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/inc/blazor.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @twsouthwick
* Microsoft Alias: **tasou**

**Comment by guardrex** [comment]
@Rick-Anderson ... What does the "Incremental Migration" part mean? ... b/c Dan, Artak, and I have discussed the nearly impossible challenge (well 💰 ***extreme COST*** 💰) of trying to maintain incremental migration docs for Blazor, and it was determined that it shouldn't be provided for every project template change, just on a per-feature basis and cross-linked via the migration doc to any new coverage each release. Forgive me if it was an internal decision tho to provide such coverage ... this is just the first that I'm hearing about this.
