### ISSUE TITLE
Update for Graph SDK 5.0

### ISSUE THREAD

**Issue by cloudhal** [dotnet/AspNetCore.Docs#28573]
This document https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?view=aspnetcore-7.0&pivots=graph-sdk is specific to graph SDK 4.x and does not work with the latest 5.0 release, and therefore needs updating.

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Hello @cloudhal ... Could you please re-open this issue that way ☝️. That will get the metadata in place for me. I'm 🏃 like mad today and tomorrow to catch up on things due to a major cross-state move in Florida ... *a very LONG state to cross!* 😄

**Comment by guardrex** [comment]
btw ... I'll say if you re-open that this is already tracked by https://github.com/dotnet/AspNetCore.Docs/issues/28001. It's been a long time ... like three years ... for a big overhaul and update to the security node of Blazor docs. We've just been making small incremental changes. Now, I'm performing a large set of passes. This topic that you're calling out will be addressed when I reach it. That should happen soon, possibly this week ... very probably by the end of the following week.

**Comment by cloudhal** [comment]
OK no problem, thanks
