### ISSUE TITLE
Register the user secrets configuration source invalid

### ISSUE THREAD

**Issue by kev1010** [dotnet/AspNetCore.Docs#28579]
The "Register the user secrets configuration source" section does not instruct how to register the user secrets. The link the user secrets [configuration provider](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers) should actually link to the configuration provider for the user secrets and not the page describing configuration providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It does, see https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows#set-a-secret
