### ISSUE TITLE
MinimalAPI tutorial: DeleteTodo() does not use DTO model

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/AspNetCore.Docs#28582]
In the last section titled **Prevent over-posting**, you return `Todo` object that should be `TodoItemDTO`. See the following.

```csharp
static async Task<IResult> DeleteTodo(int id, TodoDb db)
{
    // .........
    {
        // .........
        return TypedResults.Ok(todo);
    }

    // .........
}
```

should be

```csharp
static async Task<IResult> DeleteTodo(int id, TodoDb db)
{
    // .........
    {
        // .........
        return TypedResults.Ok(new TodoItemDTO(todo)); // <===== EDITED
    }

    // .........
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks for pointing this out @pstricks-fans. Your suggestion looks right to me.  I think the version 7 update of this topic may have had the DTO model update snippet accidently changed.  Will fix.

**Comment by Rick-Anderson** [comment]
This is not urgent and should be done as part of the .NET 8 wave.

**Comment by Rick-Anderson** [comment]
Actually the code is fine as the delete doesn't suffer from over-posting venerability.
