### ISSUE TITLE
Invalid C# array construction in code example

### ISSUE THREAD

**Issue by yv989c** [dotnet/AspNetCore.Docs#28587]
Change `var productIds = [345, 789, 135, 689];` to `var productIds = new[] { 345, 789, 135, 689 };`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor routing and navigation](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#handle-cancellations-in-onnavigateasync)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @yv989c ... I'll take a look at this first thing Tuesday morning.

**Comment by yv989c** [comment]
Happy to help Mr. 🦖
