### ISSUE TITLE
"dotnet ef database update" is not part of the step!!!

### ISSUE THREAD

**Issue by krueger80** [dotnet/AspNetCore.Docs#28591]
[Enter feedback here]
Trying to follow the instruction for this tutorial and I hit this same error as mentioned. But they said we missed the "dotnet ef database update" witch doesn't exist!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-8.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 69494](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69494)

**Comment by krueger80** [comment]
The missing command was: "Update-Database". Maybe I'm dumb but it's not exactly the same as "dotnet ef database update".
Thanks

**Comment by wadepickett** [comment]
@krueger80, you were right, this needed an improvement.  Reopening and will fix. Thanks for taking the time to let us know.
