### ISSUE TITLE
HTTP/3 enabled by default

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28599]
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#http-3-enabled-by-default

@Tratcher  what change in this IIS article for .NET 8 and HTTP/3?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 463c5211-c04b-b2ac-c4e8-20c7fc68f81a
* Version Independent ID: 0730968d-e379-ca78-3e4c-248b8035b14a
* Content: [Use ASP.NET Core with HTTP/3 on IIS](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/http3?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/iis/http3.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/http3.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Tratcher
* Microsoft Alias: **chrross**

---
[Associated WorkItem - 71299](https://dev.azure.com/msft-skilling/Content/_workitems/edit/71299)

**Comment by Tratcher** [comment]
HTTP/3 was enabled by default *for Kestrel*.

We do not control if HTTP/3 is enabled or not for IIS or Http.Sys, that's config that happens at the OS/NetSh layer.

**Comment by Rick-Anderson** [comment]
@tdykstra this is the issue I changed from no-one to me after you didn't respond.
