### ISSUE TITLE
Improve JSInvokable documentation in case of trimming.

### ISSUE THREAD

**Issue by ScarletKuro** [dotnet/AspNetCore.Docs#28627]
Link to the doc: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript

There is no caution about JS Interop (Call .NET from JS) when **trimming** / **AOT** is enabled.

Linker has no idea about JS Interop and when there is no reference in project to the method with `JSInvokable`, this method will be removed in case of trimming / AOT and you will get a runtime exception about the missing method when JS tries to call this .NET method.

The docs should warn you about this and offer a solution.
For example, if you inspect aspnetcore [source code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/InputFileJsCallbacksRelay.cs), you can see how they deal with this by using `DynamicDependency` attribute.

```CSharp
internal sealed class InputFileJsCallbacksRelay : IDisposable
{
    private readonly IInputFileJsCallbacks _callbacks;

    public IDisposable DotNetReference { get; }

    [DynamicDependency(nameof(NotifyChange))]
    public InputFileJsCallbacksRelay(IInputFileJsCallbacks callbacks)
    {
        _callbacks = callbacks;

        DotNetReference = DotNetObjectReference.Create(this);
    }

    [JSInvokable]
    public Task NotifyChange(BrowserFile[] files)
        => _callbacks.NotifyChange(files);

    public void Dispose()
    {
        DotNetReference.Dispose();
    }
}
```

This is also important, because when you contribute to blazor open source projects the project owner might ask for documentation about this behavior.

**Comment by guardrex** [comment]
Hi @ScarletKuro ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

... and pings the author just means ***ME*** 🦖 really 😆.
