### ISSUE TITLE
Add / update documentation to use Tag Helpers in Razor Class Libraries

### ISSUE THREAD

**Issue by rupesh-adapty** [dotnet/AspNetCore.Docs#28639]
[Enter feedback here]

In the sample code provided for this topic, the Tag Helpers do not seem to work. For example: Adding an `a` tag with `asp-page` to a page within the Razor Class library project does not seem to work and generates a blank `href` tag which effectively links back to the same page.

Please add explicit documentation to show how to get TagHelper derived Tags working in RCL.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem?

**Comment by Rick-Anderson** [comment]
I'm guessing you missed https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-7.0#addtaghelper-makes-tag-helpers-available

**Comment by rupesh-adapty** [comment]
In my attempt to provide you the source code, I did a "Clean Solution" followed by a "Rebuild Solution" and that seems to have miraculously fixed the issue.
