### ISSUE TITLE
Improve JSInvokable documentation in case of trimming.

### ISSUE THREAD

**Issue by ScarletKuro** [dotnet/AspNetCore.Docs#28630]
There is no caution about JS Interop (Call .NET from JS) when **trimming** / **AOT** is enabled.

Linker has no idea about JS Interop and when there is no reference in project to the method with `JSInvokable`, this method will be removed in case of trimming / AOT and you will get a runtime exception about the missing method when JS tries to call this .NET method.

The docs should warn you about this and offer a solution.
For example, if you inspect aspnetcore [source code](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/InputFileJsCallbacksRelay.cs), you can see how they deal with this by using `DynamicDependency` attribute.

```CSharp
internal sealed class InputFileJsCallbacksRelay : IDisposable
{
    private readonly IInputFileJsCallbacks _callbacks;

    public IDisposable DotNetReference { get; }

    [DynamicDependency(nameof(NotifyChange))]
    public InputFileJsCallbacksRelay(IInputFileJsCallbacks callbacks)
    {
        _callbacks = callbacks;

        DotNetReference = DotNetObjectReference.Create(this);
    }

    [JSInvokable]
    public Task NotifyChange(BrowserFile[] files)
        => _callbacks.NotifyChange(files);

    public void Dispose()
    {
        DotNetReference.Dispose();
    }
}
```
This is also important, because when you contribute to blazor open source projects the project owner might ask for documentation about this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2964d558-cd6d-7421-f7b9-cb939792c2cf
* Version Independent ID: a3517e56-69fc-1ec7-b55a-dbb54d68a807
* Content: [Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-dotnet-from-javascript.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the issue, @ScarletKuro ... and for re-opening from the topic. You can see how it adds the tracking metadata.

*Stand-by* for just a day (or until early next week). I'd like to ping the product unit to comment on this situation before we proceed with coverage.

btw ... Is it viable ... if you know/tested ... to avoid trimming a single method by decorating with ...

```csharp
[AssemblyMetadata("IsTrimmable", "True")]
```

Cross-reference: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#enable-trimming

You can see what I'm thinking there. It seems like a little ***window dressing*** 😄 on these invokable methods that avoids the trimming behavior would be a nice, easy way to sidestep it without affecting the whole app or trimming behavior otherwise.

**Comment by guardrex** [comment]
**UPDATE**: I've pinged for product unit assistance. *Stand-by for a bit*, @ScarletKuro, and we'll get some feedback from them on how they'd like to cover these aspects.

**Comment by ScarletKuro** [comment]
> btw ... Is it viable ... if you know/tested ... to avoid trimming a single method by decorating with ...
[AssemblyMetadata("IsTrimmable", "False")]

You can't decorate method with `AssemblyMetadata`.

Also, as far as I know(I might be wrong), starting from .net7.0 linker is is ignoring `[AssemblyMetadata("IsTrimmable", "False")]`. See https://github.com/dotnet/linker/issues/2991 and https://github.com/dotnet/linker/issues/3178

Probably should ask [vitek-karas](https://github.com/vitek-karas) for more details.

**Comment by guardrex** [comment]
Ok, thanks. That's fine ... just a wild guess/hope on that, as it caught my eye.

For `[DynamicDependency(nameof(XXX))]`, did you try it from the component class, like ...

```razor
@page "/"
@attribute [DynamicDependency(nameof(MyInvokableMethod))]
```

That would be nice ... if it works 😄.

**Comment by ScarletKuro** [comment]
Sure, I will test.

**Comment by ScarletKuro** [comment]
> ```
> @page "/"
> @using System.Diagnostics.CodeAnalysis
> @attribute [DynamicDependency(nameof(MyInvokableMethod))]
> ```

Can't declare it like this, only on constructor. 

But I found something new that I didn't know before.
If it's within component (IComponent / ComponentBase) then it won't be trimmed, because the `RenderTreeBuilder` and `RootComponentMappingCollection` protects them with`[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]`. However, if you use it outside of the component, like in some places of aspnetcore (example [1](https://github.com/dotnet/aspnetcore/blob/9c7db555f5c8b7069347b9c62976bd951afba4a0/src/Components/Web/src/Forms/InputFile/InputFileJsCallbacksRelay.cs#L15), [2](https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Components/Web/src/WebRenderer.cs#L100)) or [Mudblazor](https://github.com/MudBlazor/MudBlazor/blob/dev/src/MudBlazor/Services/KeyInterceptor/KeyInterceptor.cs) then it's important to put proper annotations if your blazor library aims to support trimming.

**Comment by guardrex** [comment]
Ok, thanks. That makes sense that the product unit would've prevented trimming from components.

I think we'll need a short section on this subject, which will be cross-linked from the *Razor class libraries* topic and the trimming section in the *Host and deploy* area.

I'll see if I can reach this issue next week for work. I have a feeling that Blazor security work is going to tie me up tomorrow, Friday. Monday, I'll probably be working on some new .NET 8 Blazor coverage. I'll see if I can get to this after those tasks are done.
