### ISSUE TITLE
Updated .NET MAUI Blazor App project template name for .NET 8

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#28644]
In .NET 8 we're updating the .NET MAUI Blazor App project template name to ".NET MAUI Blazor Hybrid App" to make the association with Blazor Hybrid clearer: https://github.com/dotnet/maui/issues/13804. We'll need to update corresponding docs and screenshots.

**Comment by danroth27** [comment]
> I think only the spots that refer specifically to the project template (and screenshots) will need to be versioned for the change.

Sure, that sounds find.

**Comment by guardrex** [comment]
@danroth27 ... It's not normal that I should need to run ...

```dotnetcli
dotnet new install Microsoft.Maui.Templates
```

... to get the templates, correct? ... is that just a point-in-time problem?

**Comment by guardrex** [comment]
Also, I don't see the name change yet ...

![image](https://user-images.githubusercontent.com/1622880/231284176-6f4f196e-bd7b-470d-9dbb-83a3ab7b7b52.png)

I have Preview 3 on the machine now. Perhaps I need to pass the preview switch to the CLI command. I'll try that next.

**Comment by guardrex** [comment]
Mmmmmm ... `--prerelease` switch isn't an option. I'll need the package version.

**Comment by guardrex** [comment]
This issue was closed ...

https://github.com/dotnet/maui/issues/14008

... in favor of this one ...

https://github.com/dotnet/maui/issues/14001

... where ...

```dotnetcli
dotnet workload install maui
```

... is suggested. Trying that now.

**Comment by guardrex** [comment]
@danroth27 ... 

# 🎉 ***Success!***

That workload install did the trick ... I'm good. I'll proceed with the screenshot updates now.

![image](https://user-images.githubusercontent.com/1622880/231288563-f776a39e-3f77-4b3e-a3cc-16ed22ef51da.png)

**Comment by guardrex** [comment]
@danroth27 ... I have the Windows side done, but no 🎲🎲 on the Mac side. I have VS4Mac Preview installed with the Preview 3 SDK, which I can see in the VS4Mac preferences under the .NET SDK location. I also performed a system reboot. I don't see the updated template name.

**Comment by guardrex** [comment]
We can close this now, as VS4Mac is being mothballed.
