### ISSUE TITLE
Request: per-version Latest Hosting Bundle permalinks

### ISSUE THREAD

**Issue by TheXenocide** [dotnet/AspNetCore.Docs#28642]
Help us make content visible

- Tell us what search terms you used and how you searched docs.
  - .NET 6 latest hosting bundle link
  - .NET 6 hosting bundle permalink
  - .NET LTS hosting bundle permalink
- Tell us what docs you found that didn't address your concern.
  - [Host ASP.NET Core on Windows with IIS (Version: ASP.NET Core 6)](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0#install-the-net-core-hosting-bundle)

Describe the new topic

Ideally each major version of the hosting bundle would have its own permalink to point to its latest release. Currently there is only a single link that always points to the very latest of all hosting bundles, which is now a .NET 7 hosting bundle. We do not support rollForward for major versions and our prerequisite documentation is more convoluted than it would be if we could point someone to a "Install the latest .NET 6 Hosting Bundle" link, instead of that link pointing to .NET 7. It seems there are still some cases where the current universal "latest and greatest" link is applicable, but it would be very helpful for us and our customers to have a latest-per-version link as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0#install-the-net-core-hosting-bundle)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
1. https://dotnet.microsoft.com/en-us/download/dotnet
2. Select **Out of support versions**
3. Select a version
4. Select **Hosting Bundle**

<img width="410" alt="image" src="https://user-images.githubusercontent.com/3605364/224427134-b93d62bd-7539-43d2-93e3-20d507a22d57.png">

**Comment by TheXenocide** [comment]
Just to note, for starters, I'm not personally looking for an out of support version, I'm basically looking for a "latest .NET 6 LTS hosting bundle" permalink instead of one that changes to .NET 7 and .NET 8 and so on but still points to a direct download of the latest update of .NET 6. As it stands there's only one "latest hosting bundle" permalink and it points to .NET 7 which is not what we're recommending our customers install for production since our software was written and tested on .NET 6. It's this link here that would be nice to have a per-version equivalent:

![image](https://user-images.githubusercontent.com/398012/224727705-5bce4ba6-c2cc-453b-9638-056ac9404df8.png)

I understand what the current link does (and it makes sense for other scenarios to have a "just the absolute latest" direct download link) but it would be nice to not have to walk customers through how to get the latest bundle for a specific .NET version with screenshots containing version numbers that could become confusing/dated, etc. The current link is:

https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer

My thought is, in addition to that, it would be nice to have URLs like:

/permalink/dotnetcore-current-net6-windows-runtime-bundle-installer
/permalink/dotnetcore-current-net7-windows-runtime-bundle-installer
/permalink/dotnetcore-current-net8-windows-runtime-bundle-installer

and so on. This way for any given version of the product, tied to a given version of .NET, the link in the docs can always be accurate.

**Comment by TheXenocide** [comment]
@Rick-Anderson it looks like this ticket indicates that it is closed as a result of your PR, though I don't think my request was addressed. I guess is the official response that you don't intend to add this link, even for currently supported versions? (Keeping in mind .NET 6 is the *Long Term Support* version, which is why we targeted it to offer production software to customers on it, while we will not for .NET 7). It seems like the ticket is completely devoid of any discussion about the decision being made/why/etc. which I'm not used to regarding MS feature requests/bug reports/etc.

**Comment by TheXenocide** [comment]
@mairaw I noticed from #23934 that you might have some ownership over the link in question here and I'm wondering if it's possible to request similar links on a per-version basis, rather than making the documentation point to this github issue (which may also inadvertently make people believe .NET 6 is out of support). I'm hoping for a more convenient link we can include in our installation documentation that will stay up-to-date without forcing people to use unsupported (by our software) newer bundles. We will want something similar when .NET 8 becomes LTS to prevent the "convenience" of the link from becoming an inconvenience when .NET 9 starts releasing bundles that we don't develop or test against so I'm hoping we can establish this as a pattern for versions starting with the current LTS but also going forward?

**Comment by MacKinley** [comment]
Not sure if this helps you @TheXenocide but each `major.minor` of a hosting bundle has a permalink to the latest patch.

Ex:
- https://aka.ms/dotnetcore-6-0-windowshosting
- https://aka.ms/dotnetcore-3-1-windowshosting

**Comment by peter-bertok** [comment]
> Not sure if this helps you @TheXenocide but each `major.minor` of a hosting bundle has a permalink to the latest patch.
> 
> Ex:
> 
>     * https://aka.ms/dotnetcore-6-0-windowshosting
> 
>     * https://aka.ms/dotnetcore-3-1-windowshosting

It would be *really* helpful if this was properly documents.

I've been searching the Internet for hours looking for a way to keep an IIS web server "up to date" with the latest security patch of of a .NET Core hosting bundle, but there's very little (no?) official guidance.

It ought to be just as simple as the updates users receive for .NET Framework -- updates via Windows Update.

Failing that, there should be an official installer and/or updater script that can be used to deploy the .NET Core shared runtime.

Currently, users have to roll their own solution based on Github issue comments...

**Comment by TheXenocide** [comment]
Agreed with @peter-bertok but yes, that helps tremendously, thank you
