### ISSUE TITLE
Need explanation/example on how to renew the access token on expiry

### ISSUE THREAD

**Issue by dobestar** [dotnet/AspNetCore.Docs#28658]
The docs say that for Bearer token authentication, "The access token function provided is called before every HTTP request made by SignalR. If the token needs to be renewed in order to keep the connection active, do so from within this function and return the updated token. The token may need to be renewed so it doesn't expire during the connection."

In my tests using the .net client, invoking a hub method does not call that function, and so there is no way of checking the token expiry as long as the connection is alive. As far as I can see, as stated in the other docs, the token won't be checked until the connection drops and reconnects. 

If this is the case, how does the access token function help with refreshing tokens?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by wadepickett** [comment]
@BrennanConroy, is the note on the access token function in the section [Bearer token authentication](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0#bearer-token-authentication), correct?  I don't know enough about that subject to determine if needs a clarification or a change.  Thanks for any insight.

**Comment by BrennanConroy** [comment]
> is the note on the access token function in the section [Bearer token authentication](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-7.0#bearer-token-authentication), correct?

It is technically correct, but it's not obvious to users what it means.

> invoking a hub method does not call that function

This is a good example of why it's confusing, a hub method invocation does not necessarily create an HTTP request. For example, with Websockets there is only ever a single HTTP request for the lifetime of the connection.

See https://github.com/dotnet/AspNetCore.Docs/issues/13144 for a duplicate issue.

**Comment by wadepickett** [comment]
Thanks Brennan.

Also adding this related open issue for reference:  [Refreshing auth tokens for SignalR](https://github.com/dotnet/aspnetcore/issues/5297)

**Comment by wadepickett** [comment]
@BrennanConroy 
Closing this issue as duplicate to #13144.    I can see I can't take on #13144.  I think we need a clear draft of guidance from the dev team and I can certainly help with clean up/edit.
