### ISSUE TITLE
.NET 8 sample for  IResettable to ObjectPooling 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28664]
* Copy sample code from  https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/performance/ObjectPool/ObjectPoolSample6 to
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/performance/ObjectPool/ObjectPoolSample8
* Update to .NET 8
* Add code with New `IResettable` interface in `ObjectPool`

See [New IResettable interface in ObjectPool](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-2/#new-iresettable-interface-in-objectpool)

Related #28656

---
[Associated WorkItem - 79658](https://dev.azure.com/msft-skilling/Content/_workitems/edit/79658)

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan @sammychinedu2ky  FYI
Also Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Comment by sammychinedu2ky** [comment]
on it @Rick-Anderson

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson the **IResettable** doesn't seem to be available in the SDK.
I am using 8.0.0-preview.1.23110.8

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson the **IResettable** doesn't seem to be available in the SDK. I am using 8.0.0-preview.1.23110.8

You might need to wait for the [next preview](https://github.com/dotnet/aspnetcore/issues/44901#issuecomment-1425211635). 

@xiaoyuvax what version are you using.

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky you'll have to wait for the next preview or install the [daily build](https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries). 
@geeknoid wrote the code.

**Comment by sammychinedu2ky** [comment]
Okay

**Comment by xiaoyuvax** [comment]
> > @Rick-Anderson the **IResettable** doesn't seem to be available in the SDK. I am using 8.0.0-preview.1.23110.8
> 
> You might need to wait for the [next preview](https://github.com/dotnet/aspnetcore/issues/44901#issuecomment-1425211635).
> 
> @xiaoyuvax what version are you using.

?? any context?

**Comment by xiaoyuvax** [comment]
now i have Microsoft.Extensions.ObjectPool 7.0.3, probably 7.0.2 when i wrote my comment.

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  see [project file](https://github.com/xiaoyuvax/ObjectPoolReuseCaseDemo/blob/main/ObjectPoolDemo/ObjectPoolDemo.csproj)

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky how's this going?

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson I still get the error saying 
The type or namespace name 'IResettable' could not be found (are  
you missing a using directive or an assembly reference?)
