### ISSUE TITLE
Use "DI container" instead of "DI" when taking about DI containers

### ISSUE THREAD

**Issue by grzesiek-galezowski** [dotnet/AspNetCore.Docs#28665]
This document makes multiple remarks about having something "in DI". This is incorrect and instead of DI should use "DI container". 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Version Independent ID: ed83a5ff-cb3a-8655-9f9a-a441da52424e
* Content: [What's new in ASP.NET Core 7.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-7.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-7.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-7.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This has been common shorthand around the repo for several years. @Rick-Anderson ... I'm 👀 on this in case you decide to make a change in the main doc set. I have just have a few spots to update in the Blazor docs if we adopt @grzesiek-galezowski's suggestion.

**Comment by Rick-Anderson** [comment]
There's no ambiguity.

**Comment by grzesiek-galezowski** [comment]
Thanks so much for making this change. Using this shorthand was a pain for so long that we now have a whole generation of .NET programmers that believe DI is about registering services in some kind of reflection-based mechanism. It's becoming increasingly hard to explain DI to people who read Microsoft (and not only) docs. You are my heroes!
