### ISSUE TITLE
Blazor Server Stream Image Example

### ISSUE THREAD

**Issue by gabephudson** [dotnet/AspNetCore.Docs#28666]
I wonder if streaming image (or file) data via JS is the best solution? This can also be done by adding a Razor Page to the Blazor Server project and using the traditional "return File()" method in the controller. This allows for simple URL's in an image tag and browser caching. Just a thought when streaming binary data.

To add Razor Page to the project, all one has to do is add app.MapRazorPages(); to Program.cs for routing and we are off to the races.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Version Independent ID: 66bb1712-60ac-77a6-10d2-f2d795126783
* Content: [Work with images in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/images?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/images.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/images.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gabephudson ... IIRC, it's even simpler than that. IIRC, a Blazor Server app can just call `File.OpenRead(@"{PATH}")` in a component to get a stream of any file (cross-ref: [*File Downloads* article](https://learn.microsoft.com/en-us/aspnet/core/blazor/file-downloads?view=aspnetcore-7.0#download-from-a-stream)). I think this article could use a similar tip/approach example.

I'm buried in work at the moment trying to get through Blazor *Security* node updates. This issue will be tracked by the Blazor project, so it won't get lost. I'll try to get back to it within a couple of weeks. I'll ping u on the PR when it goes up.

*Thanks for the issue!*

**Comment by gabephudson** [comment]
Thanks, Guardrex. The issue I'm trying to solve is, once we have a stream (or byte array) on the server side (this could be a local file, database binary, Azure blob, etc.) is how do we stream it to the client as a file/image with the proper content-type? Both articles suggest one has to write the stream to the client using JS interop?

JS streaming works ok for one-time files, but for things like dynamic images (clients can upload their logo for example), it causes one to have to stream all the data for the image each time it's requested. Using a classic controller, the binary data can be streamed and then cached as an image by the browser, so it's not read from the sever each time it's requested.

My goal, for example, is to be able to do something like img src="/image?id=xxxx" from Blazor server and have the "image" component stream down the file to the client as binary data with proper headers/content-type. This can be done with MVC/Razor Pages, but not sure how to have a Blazor component stream binary data? Looks like we have to use JS to accomplish (or add a classic controller like suggested)...
https://stackoverflow.com/questions/68393235/download-file-from-server-with-blazor-app

**Comment by guardrex** [comment]
@gabephudson ... We decided to let the devs/community take this approach on if they wish. Tanay put up a general, starting point approach, and we'll just stick with that for now. Thanks for your issue tho.

Mackinnion said that you might want to take a look at https://github.com/dotnet/aspnetcore/issues/25274 WRT general improvements on the subject.
