### ISSUE TITLE
Please add more info about shared files

### ISSUE THREAD

**Issue by Edelbitter** [dotnet/AspNetCore.Docs#28674]
Hi everyone,

It would be very helpful if the documentation contained explicit information how to use "SharedResources", i.e. one file (per culture) for all localized strings. It is unclear where to place the files and what to name them, in order for IStringLocalizer (etc.) to find the strings.
I could not figure it out and found my answer here
https://stackoverflow.com/questions/42647384/asp-net-core-localization-with-help-of-sharedresources
but this information should be included in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 201bbea9-555e-5ff1-ebd8-204b0c77f83e
* Version Independent ID: 201bbea9-555e-5ff1-ebd8-204b0c77f83e
* Content: [Provide localized resources for languages and cultures in an ASP.NET Core app](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/provide-resources?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/localization/provide-resources.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization/provide-resources.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco  PLEASE review

**Comment by hishamco** [comment]
What about this one https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?view=aspnetcore-7.0#shared-resources

If I remembered we already have a sample for shared resources, please check the samples in the repo

**Comment by hishamco** [comment]
What about this one https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?view=aspnetcore-7.0#shared-resources

If I remembered we already have a sample for shared resources, please check the samples in the repo

**Comment by Edelbitter** [comment]
I've looked at the samples here https://github.com/aspnet/Entropy/tree/master/samples with 'localization' in the name, and could not find anything.

I saw the section about SharedResources, that's how I knew it was possible to use them. But there is no information about how to structure the folders and files and namespaces an that in services.AddLocalization, no Path should be entered.

**Comment by hishamco** [comment]
The `SharedResource` is just a dummy class

> I've looked at the samples here https://github.com/aspnet/Entropy/tree/master/samples with 'localization' in the name, and could not find anything.

Have a look to this 

https://github.com/dotnet/AspNetCore.Docs/blob/46ec24e1a1d9260430669d0cfd9fefe3cc9f0a57/aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/InfoController.cs#L66-L68

**Comment by Edelbitter** [comment]
Now I'm completely confused why I had to remove the Path to get it to work but ok. The sample has an unused file, btw: Resources.SharedResource.fr.resx. Thanks

**Comment by hishamco** [comment]
> Now I'm completely confused why I had to remove the Path to get it to work but ok.

Which path do you mean?

> The sample has an unused file

Don't blow my mind :)

https://github.com/dotnet/AspNetCore.Docs/blob/46ec24e1a1d9260430669d0cfd9fefe3cc9f0a57/aspnetcore/fundamentals/localization/sample/6.x/Localization/Controllers/InfoController.cs#L12

As I told you it's just a marker or dummy class

**Comment by Edelbitter** [comment]
I know it's a dummy class, that was the first thing I implemented.

This Path
`services.AddLocalization(options => options.ResourcesPath = "Resources");`

When I set it to "Resources" (which is where my .resx files actually are), it searched at
"<projectName>.Resources.<projectName>.Resources".
(That's what it said when I looked at the whole object returned by _localizer["key"])

My SharedResources class is in the Resources directory, too (but in the project namespace) but I had the same problem when I put it into the project root.

Not setting a ResourcesPath is suggested in the stackoverflow thread so I tried that and it worked. But it seems that's not the only way to make it work, as shown by the sample.

**Comment by hishamco** [comment]
When you set the path as it was shown, it should look for the resources inside that folder, unless you did something wrong with the namespaces

I don't know if you are working on another project, but I'm pretty sure it might be namespace issue. Could you please share a minimal repo to reproduce the issue?

**Comment by Edelbitter** [comment]
Both. It's hardcoded to use French but the result is the same if English is used.

**Comment by hishamco** [comment]
I just found two issues here:

1. Try to avoid using special characters in the project names, so replace `loca-demo` with `loca-demo`
2. Move the `SharedResources` to the root

Two of the craziest issues in localization are resource naming and namespaces :)

**Comment by Edelbitter** [comment]
Interesting. The actual customer project has a hyphen in the project name, too.
But it's pretty weird how that causes problems or doesn't, depending on where the resources are.

Move just the dummy class or all of the files?  

When moving just the class, I get this
![image](https://user-images.githubusercontent.com/17107746/226606791-2009e7cb-9cc5-4e00-a40a-c20d189e35d1.png)

**Comment by hishamco** [comment]
> Move just the dummy class or all of the files?

Just the `SharedResources` out of the `Resources` folder

**Comment by hishamco** [comment]
Please update your repo, then give me access write to it, so I can commit directly

**Comment by hishamco** [comment]
@Edelbitter check your repo now, as I told you before naming is critical in localization :)

You might check the troubleshooting section in our docs. @Rick-Anderson is there anything to add here or we can close this one

**Comment by Edelbitter** [comment]
I'll remember never to use hyphens for anything! Thank you for your time :)

**Comment by hishamco** [comment]
Not only hyphens, any invalid symbol :)

**Comment by akmalnodirov** [comment]
@hishamco that helped me too, I spent more than 4 hours before, your solution about moving the base file to the root folder)

**Comment by hishamco** [comment]
Exactly

**Comment by Dino222** [comment]
Helped me too. My problem was that my dummy class SharedReferences.cs was not in root. @hishamco thanks for clearing those things out.

**Comment by hishamco** [comment]
Great that helps you
