### ISSUE TITLE
Output caching was already implemented but docs suggest it wasn't

### ISSUE THREAD

**Issue by milanio** [dotnet/AspNetCore.Docs#28678]
The section below still mentions that "Output caching is a design proposal" but it was implemented in NET7, wasn't it?

Original section in the current docs:

There's no developer control over this caching behavior when using the [Response Caching Middleware](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-7.0) because the middleware adheres to the official caching specification. Support for output caching to better control server load is a design proposal for a future release of ASP.NET Core. For more information, see [Add support for Output Caching (dotnet/aspnetcore #27387)](https://github.com/dotnet/aspnetcore/issues/27387).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
Yes, you're correct, thanks for reporting that. I'll remove the out-of-date section.
