### ISSUE TITLE
Where is the code sample?

### ISSUE THREAD

**Issue by amanmcse** [dotnet/AspNetCore.Docs#28687]
Please include the link to the entire code sample in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @amanmcse ... I don't think that this topic has a full sample. The code files for it are at ...

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/security/authentication/ws-federation/samples

... as you can see there, it's just code pulled into the document.
