### ISSUE TITLE
Deprecated CSS preprocessor

### ISSUE THREAD

**Issue by boppbo** [dotnet/AspNetCore.Docs#28681]
[Delegate.SassBuilder](https://www.nuget.org/packages/Delegate.SassBuilder) is archived at github. Consider replacing it with [AspNetCore.SassCompiler](https://www.nuget.org/packages/AspNetCore.SassCompiler)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2703a48e-8b35-53fc-ac36-cfb395833077
* Version Independent ID: 39d464d9-aca6-34fa-7e52-5fde2e393ba7
* Content: [ASP.NET Core Blazor CSS isolation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-7.0#css-preprocessor-support)
* Content Source: [aspnetcore/blazor/components/css-isolation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @boppbo ... I'll put it into a PR and see if management would like to approve the swap.

**Comment by boppbo** [comment]
@guardrex found two another occurences. There might be more

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#css-preprocessor-support)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-7.0#css-preprocessor-support)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... I'll search the whole repo and get them all out. *Stand-by ......*

**Comment by guardrex** [comment]
Looks like there were only two other spots, which arrive in those articles by an INCLUDE file. I've added a commit to the PR to change that INCLUDE file.
