### ISSUE TITLE
Incorrect detail and implementation details missing

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#28685]
[[Enter feedback here]](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#client-connections)
In the section
**Client connections** : , there is a mention about how to prevent circuit exhaustion by using Authentication.

"Require authentication, which naturally limits the ability of unauthorized users to connect to the app. For this scenario to be effective, users must be prevented from provisioning new users on demand."

In reality, what i have found is that just opening a login page itself uses a 1 WebSocket connection, whether you decide to login or not.
So the above statement is not correct.

**Limit the number of connections per user**, than there is another mention of limit the number of connections.
for example, when a connection limit is established based on the client's IP address.
But there is no details around(example or links) to show how to implement this.
Can you please provide links to pages that show how to implement it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff954815-0f8b-9f1b-9772-1657744b4f9e
* Version Independent ID: ed7d726d-41c6-73d8-d564-91530b4935c3
* Content: [Threat mitigation guidance for ASP.NET Core Blazor Server](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/server/threat-mitigation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/threat-mitigation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @nssidhu ... Pinging @javiercn, as he provided the remarks.

**Comment by guardrex** [comment]
@nssidhu ... I think the coverage related to the scenario is over in the *Fundamentals* > *SignalR* article and in the *Security* node's *Additional scenarios* topic. Take a look at the following. They aren't tailored to this specific case. What you say is correct ... we don't have an explicit example for what the *Threat Mitigation* doc states.

* https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#blazor-server-circuit-handler
* https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0#circuit-handler-to-capture-users-for-custom-services

**Comment by guardrex** [comment]
Ok ... I'm *BACK!* I messaged Javier offline to see if he'll triage this for us and provide assistance.

@javiercn ... The remarks + concerns are for ...

**... there's no limit on the number of connections per user for a Blazor Server app. If the app requires a connection limit, take one or more of the following approaches:**

> Require authentication, which naturally limits the ability of unauthorized users to connect to the app.

... but @nssidhu says that a WebSocket/circuit is created ("a connection") just accessing the app. Can that statement be improved?

> Limit the number of connections per user.

... but we don't have specific guidance for any of the app-level approaches recommended. Do you want to schedule this issue to provide something concrete for it at some point, or should it be left to the community/dev to work out on their own?

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/threat-mitigation?view=aspnetcore-7.0#client-connections

**Comment by javiercn** [comment]
I don't think that's the case.

The only time this happens if is a component is rendered on the page and active. If the user navigates to another page that does not have a component, the WebSocket connection is dropped.

The guidance applies here, but I suspect the default app is rendering the head/title components in the layout, hence why a circuit is established.

There are other things that can be done like rate-limiting the SignalR negotiate endpoint via the rate limiting middleware, but that's not an approach that I want to cover here for the time being, as any security recommendation requires vetting.

**Comment by guardrex** [comment]
Thanks @javiercn ... closing out (for now) as a won't-fix for docs.
