### ISSUE TITLE
Example demonstrating conditionally prevent default.

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/AspNetCore.Docs#28692]
Include an example demonstrating preventDefault based on the Key pressed. Currently there is some misunderstanding regarding this functionality.

https://stackoverflow.com/questions/61373674/how-to-conditionally-preventdefault-inside-the-input-component-in-blazor

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#prevent-default-actions)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LunicLynx ... Isn't it already covered at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0#prevent-default-actions

If that guidance isn't effective for your scenario, you can open a product support request with the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28692
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
I'll take a closer look, but it won't be until next week due to the workload right now. I'm ⛰️⛏️😅 at the moment 😄.

**Comment by LunicLynx** [comment]
No rush ✌️ , just to make sure other people don't run into this situation.

Good luck ⛰️⛏️ 😀

**Comment by guardrex** [comment]
I'm almost back to this. I have an important task tomorrow, Friday, so I hope to reach this by Monday 🤞.

**Comment by LunicLynx** [comment]
I can prepare a demo app, if that helps?

**Comment by guardrex** [comment]
You say it's a common use case, but the product unit didn't think so when coverage went up. Let's ask @SteveSandersonMS if coverage for this should appear ... and if so ... *what coverage* he would like to see for it. *Stand-by ........*

**Comment by guardrex** [comment]
@LunicLynx ... No response from Steve yet. I'll send another message.

**Comment by guardrex** [comment]
Sorry for the delay. The team is working feverishly on the .NET 8 preview 🏃🏃🏃. We'll get back to this as soon as we can. I'll try to reach out to Steve again next week.

**Comment by SteveSandersonMS** [comment]
@LunicLynx Could you clarify what you are asking or suggesting? You mention: *handle arrow keys differently on an input field while not changing the default behavior for all other keys*

... but I can't tell whether you're saying this is something you can or can't do. Are you asking for guidance on how to do it? Or you're saying you can do it but the docs say you can't?

In summary, what specific changes to the docs are you asking for?

**Comment by SteveSandersonMS** [comment]
I posted an example at https://blazorrepl.telerik.com/QnuzOtFr04ZL1crR57. Perhaps that will cover your scenario.

@guardrex Do you think this is a suitable example for docs?

**Comment by LunicLynx** [comment]
I'm so sorry, but this is not what I'm talking about.

Ok ok ok. Let me explain. I looked at the source and found that whenever a rendering is happening, then `stopPropagation` and `preventDefault` are set here:

https://github.com/dotnet/aspnetcore/blob/220b05497fc1deffb3480e59e361a5fffa25db78/src/Components/Web.JS/src/Rendering/BrowserRenderer.ts

In lines 387 and 391

Since a render is triggered BEFORE a event call returns to javascript, here:

https://github.com/dotnet/aspnetcore/blob/220b05497fc1deffb3480e59e361a5fffa25db78/src/Components/Components/src/RenderTree/Renderer.cs#L446

Means that when looking at the source in:
https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/Events/EventDelegator.ts

That the event is delegated in line: 189 and after that the handlerInfos are checked for  `stopPropagation` and `preventDefault` in lines 196 and 200 respectively.

These were updated as part of the rendering call, allowing this code to function correctly:

https://blazorrepl.telerik.com/GduTFbPQ31hhoo2926

No JS necessary.

This functionality, when looking at the code, feels intentional, but isn't documented.

**Comment by LunicLynx** [comment]
Im talking about the order this is happening in. That setting the bool in the event callback has an effect on the outcome.

**Comment by SteveSandersonMS** [comment]
Very interesting. Thanks @LunicLynx for pointing that out and showing the example. I simply couldn't make sense of a description in human language (not because of your English, which seems perfect) but seeing it in code is perfectly clear!

I actually did not realise this would work in the way you are showing it, and I don't think we specifically planned for it to do so. However I can see that it *looks* intentional and people may well be relying on this.

We should definitely clarify this. I'm filing https://github.com/dotnet/aspnetcore/issues/48193 for the team to consider.
