### ISSUE TITLE
EnableRateLimiting does nothing on a RazorPage method

### ISSUE THREAD

**Issue by theo-albers** [dotnet/AspNetCore.Docs#28714]
When I place the EnableRateLimitingAttribute on the RazorPage class, the rate limiter is respected. When I only place it on a Post method of the RazorPage, the rate limiter is ignored.

This works:

```csharp
[AllowAnonymous]
[EnableRateLimiting(RateLimitingPolicies.PasswordResetPolicy)]
public class PasswordForgotModel : PageModel
{
   public async Task<IActionResult> OnPostAsync(string? returnUrl = null, CancellationToken cancellationToken = default)
   // ...
}
```

This doesn't
```csharp
[AllowAnonymous]
public class PasswordForgotModel : PageModel
{
   [EnableRateLimiting(RateLimitingPolicies.PasswordResetPolicy)]
   public async Task<IActionResult> OnPostAsync(string? returnUrl = null, CancellationToken cancellationToken = default)
   // ...
}
```

There are no specifics in the documentation other than "The same rules apply to Razor Pages". So how can we enable ratelimiting on the POST of a razor page and not on the GET via the attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Version Independent ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Content: [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-7.0%3A)
* Content Source: [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 71058](https://dev.azure.com/msft-skilling/Content/_workitems/edit/71058)

**Comment by Rick-Anderson** [comment]
@theo-albers filters can't be apply to  Razor Page handlers, see [Authorize attribute and Razor Page](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-79.0#authorize-attribute-and-razor-pages)

I'll get this documented. 

@wtgodbe  or @BrennanConroy  will correct me if I'm wrong.

**Comment by theo-albers** [comment]
Ah, OK, it's not clear those filters are used by reading the docs. Of course you can't repeat all requirements here, but a small pointer here would be useful.

**Comment by theo-albers** [comment]
Maybe it's also worth mentioning that adding a named ratelimiter attribute requires the ratelimiter to exist. There will be a runtime exception at the page with the attribute when the rate limiter doesn't exist.

**Comment by Rick-Anderson** [comment]
> Maybe it's also worth mentioning that adding a named ratelimiter attribute requires the ratelimiter to exist. There will be a runtime exception at the page with the attribute when the rate limiter doesn't exist.

Great error message.
