### ISSUE TITLE
ASP.NET Core developer certificate still not trusted after following instructions on Ubuntu 22.04

### ISSUE THREAD

**Issue by athoma13** [dotnet/AspNetCore.Docs#28716]
Followed the instructions to the letter... 
However, when launching my app, I still get the warning

> The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.

This is my terminal window...

```
:~$ dotnet dev-certs https
The HTTPS developer certificate was generated successfully.
:~$ sudo -E dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
A valid HTTPS certificate is already present.
:~$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
done.
```

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://learn.microsoft.com/en-gb/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&tabs=visual-studio%2Clinux-ubuntu#ssl-linux)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Take a look at https://blog.wille-zone.de/post/aspnetcore-devcert-for-ubuntu/

**Comment by brianpursley** [comment]
> Take a look at https://blog.wille-zone.de/post/aspnetcore-devcert-for-ubuntu/

This ultimately was what worked for me.

It would be nice if there was an official script that worked, or ideally if `dotnet dev-certs https` just worked.
