### ISSUE TITLE
No instructions on how to create a websocket client

### ISSUE THREAD

**Issue by ljbw-online** [dotnet/AspNetCore.Docs#28753]
This article only demonstrates how to make a websocket server. I have not been able to find a description of how to make a simple websocket client.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
I haven't reviewed or tested this, but Here's what chatGPT says:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/3605364/227401394-b3eaa7d7-2215-440d-acb1-34ddea14a2f3.png">


To create a WebSocket client that connects to an ASP.NET Core WebSocket server, you can follow these steps:

Add the System.Net.WebSockets.Client NuGet package to your client project. This package contains the ClientWebSocket class, which you will use to create a WebSocket client.

In your client code, create a new instance of ClientWebSocket.

csharp
Copy code
using System.Net.WebSockets.Client;

var webSocket = new ClientWebSocket();
Set the WebSocket's options, such as the server URI, subprotocols, and any headers that you want to send.
csharp
Copy code
webSocket.Options.SetRequestHeader("MyHeader", "MyValue");
webSocket.Options.AddSubProtocol("myprotocol");
await webSocket.ConnectAsync(new Uri("ws://localhost:5000/chat"), CancellationToken.None);
Once you have set the WebSocket options, call the ConnectAsync method to establish the WebSocket connection. You must pass in the URI of the WebSocket server you want to connect to.

After the WebSocket connection is established, you can send and receive data using the SendAsync and ReceiveAsync methods of the ClientWebSocket class.

Here is an example of how to send a message to the server:

csharp
Copy code
var message = Encoding.UTF8.GetBytes("Hello, server!");
await webSocket.SendAsync(new ArraySegment<byte>(message), WebSocketMessageType.Text, true, CancellationToken.None);
And here is an example of how to receive a message from the server:

csharp
Copy code
var buffer = new byte[1024];
var result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
var message = Encoding.UTF8.GetString(buffer, 0, result.Count);
Note that the ReceiveAsync method will block until a message is received from the server, so you should call it on a separate thread or in an asynchronous method.





Regenerate response
