### ISSUE TITLE
Code only: New APIs in ProblemDetails to support more resilient integrations

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28754]
[Problem details](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errrors?view=aspnetcore-73.0#problem-details)

[New APIs in ProblemDetails to support more resilient integrations](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-2/#new-apis-in-problemdetails-to-support-more-resilient-integrations)

Put sample code in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/minimal-apis/handle-errrors/sample8

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 457f91a3-57c8-5b11-e060-71f8384ab27d
* Version Independent ID: 457f91a3-57c8-5b11-e060-71f8384ab27d
* Content: [Handle errors in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errrors?view=aspnetcore-7.0#problem-details)
* Content Source: [aspnetcore/fundamentals/minimal-apis/handle-errrors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/handle-errrors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @brunolins16
* Microsoft Alias: **brolivei**

---
[Associated WorkItem - 76920](https://dev.azure.com/msft-skilling/Content/_workitems/edit/76920)

**Comment by Rick-Anderson** [comment]
@Tiscs @martincostello @david-acker @fiyazbinhasan anyone interested in writing a sample showing [New APIs in ProblemDetails to support more resilient integrations](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-2/#new-apis-in-problemdetails-to-support-more-resilient-integrations)?

**Comment by david-acker** [comment]
I'm interested in helping out with this. Should this sample only focus on the new `TryWriteAsync` API that's mentioned in the blog post?

**Comment by brunolins16** [comment]
@Rick-Anderson not sure the plan but we have this new feature as well https://github.com/dotnet/aspnetcore/issues/47651

**Comment by Rick-Anderson** [comment]
> I'm interested in helping out with this. Should this sample only focus on the new `TryWriteAsync` API that's mentioned in the blog post?

Yes, that and the new `Exception `property.

**Comment by david-acker** [comment]
@Rick-Anderson I've put up a draft PR with a sample using `IProblemDetailsService.TryWriteAsync`. Right now it just includes a very simple demo of the fallback behavior when used with the `UseStatusCodePages` and `UseExceptionHandler` middleware. Locally, I tested out the fallback behavior by hitting the endpoints with an `Accept` header that's not supported by the `DefaultProblemDetailsWriter` (e.g. `text/plain`).

Since the `Exception` property on `ProblemDetailsContext` will be added in the next .NET 8 Preview, do we want to include this in the sample? Or should this be added in a separate PR once .NET Preview 4 is released?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I've put up a draft PR with a sample using `IProblemDetailsService.TryWriteAsync`. Right now it just includes a very simple demo of the fallback behavior when used with the `UseStatusCodePages` and `UseExceptionHandler` middleware.
> 
> Locally, I tested out the fallback behavior by hitting the endpoints with an `Accept` header that's not supported by the `DefaultProblemDetailsWriter` (e.g. `text/plain`). Would it make sense to mention something about this somewhere (either a code comment or in one of the written docs) to give a simple example of a scenario where the fallback behavior would be used?
> 

Yes, put some code comments in. When we add this to the document, we may move the comments out of code and into the doc.

> Since the `Exception` property on `ProblemDetailsContext` will be added in the next .NET 8 Preview, do we want to include this in the sample? Or should this be added in a separate PR once .NET Preview 4 is released?

#29126
