### ISSUE TITLE
CORS doc improvement

### ISSUE THREAD

**Issue by fiyazbinhasan** [dotnet/AspNetCore.Docs#28774]
Hi @Rick-Anderson 

I didn't find much information about ASP0023 here https://learn.microsoft.com/en-us/aspnet/core/diagnostics/code-analysis?view=aspnetcore-7.0. Wondering if we should link this issue instead, https://github.com/dotnet/aspnetcore/issues/46936

The anchor links are not taking me to the appropriate section,

https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#testc6
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#cpo6
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#dc6
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#tcer
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#ecors6
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#dp
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#attr
https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-7.0#how-cors

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/cors?branch=pr-en-us-28763&view=aspnetcore-7.0#enable-cors-with-endpoint-routing)
* Content Source: [aspnetcore/security/cors.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [this line](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors/includes/cors7.md?plain=1#L113) and #28746

Thanks for the review and all the work you've done on this doc.

**Comment by Rick-Anderson** [comment]
> The anchor links are not taking me to the appropriate section,

The anchor are broken because of duplicate's in the versions.
