### ISSUE TITLE
Missing instructions for hosted WASM

### ISSUE THREAD

**Issue by Flachdachs** [dotnet/AspNetCore.Docs#28777]
Right now this page seems to describe only the _standalone_ Blazor WebAssembly app (when you switch to Blazor WebAssembly on top of the page). How is the procedure when there are separate Client and Server projects in a _hosted_ Blazor WebAssembly app?
 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Flachdachs ... The **Client** project of a hosted Blazor WebAssembly solution is a ***served*** Blazor WebAssembly app. Therefore, apply the guidance from the "WebAssembly" pivot of this doc to the **Client** project.

Leave this issue open. I'll make an update to the document to call this out. This issue will close automatically when the PR merges.
