### ISSUE TITLE
Typing Mistake

### ISSUE THREAD

**Issue by dipak8959** [dotnet/AspNetCore.Docs#28780]
[Enter feedback here]

The Program.cs file contains the following code:

should be

The Startup.cs file contains the following code:
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Ducki** [comment]
Since .NET 6, there is no Startup.cs anymore by default – the docs correctly refer to the Program.cs.
