### ISSUE TITLE
Irrelevant to web API?

### ISSUE THREAD

**Issue by chr1st0scli** [dotnet/AspNetCore.Docs#28789]
Hi.
This security concern is irrelevant to web API right? That's why it is titled as "Prevent Cross-Site Scripting (XSS) in ASP.NET Core", i.e. web API is not mentioned at all and I guess this is also why the example solutions refer to razor pages, right? In other words, the problem applies to MVC because it builds the pages it serves.

In my understanding, a RESTful web API's response type is typically application/json, so it only declares that it correctly returns json, not web pages. Besides, the API's clients might not even be browsers at all. In other words, it's client agnostic.

And I think this is why I have observed that web API clients that are web pages like SPA libraries, single page applications, take care to properly html encode the content they need to present themselves. 

Is this right? The topic is a little vaguely covered in the web.

Thank you. 
---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων learn.microsoft.com ➟ GitHub.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://learn.microsoft.com/el-gr/aspnet/core/security/cross-site-scripting?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the [first sentence of the article](https://learn.microsoft.com/el-gr/aspnet/core/security/cross-site-scripting?view=aspnetcore-77)
Cross-Site Scripting (XSS) is a security vulnerability which enables an attacker to place client side scripts (usually JavaScript) into ***web pages***.

Web APIs that return data in the form of HTML, XML, or JSON can be vulnerable to XSS attacks if they don't properly sanitize user input. For example, if an API accepts user-generated content and returns it in an HTML response, an attacker could inject malicious scripts into the content that will execute when the response is rendered in the user's browser.

To prevent XSS attacks, web APIs should implement input validation and output encoding. Input validation ensures that user input meets expected criteria and doesn't include malicious code. Output encoding ensures that any data returned by the API is properly sanitized so that it can't be executed as code by the user's browser.

@blowdart  should I add something like that to the doc or is the first sentence enough?

Cross-Site Scripting (XSS) is a security vulnerability which enables an attacker to place client side scripts (usually JavaScript) into ***web pages***.

**Comment by chr1st0scli** [comment]
Thank you for the prompt response and the proposed enrichment. 

But what about the essence of the argument, that API's are agnostic to their clients' nature?

You said "if an API accepts user-generated content and returns it in an HTML response", but the argument is that API's don't typically return HTML responses. I have seen this view before but I get the feeling it's like an unpopular opinion.

Finally, if an API should proceed and do it, I would like to know the recommended way it should apply output encoding in the form of an example. E.g. using a Middleware and applying this or that encoder to some JSON content. 

Thanks again.

**Comment by Rick-Anderson** [comment]
> You said "if an API accepts user-generated content and returns it in an HTML response", but the argument is that API's don't typically return HTML responses. I have seen this view before but I get the feeling it's like an unpopular opinion.

Create a MVC controller with view or easier Razor Page if you want an HTML response.

> Finally, if an API should proceed and do it, I would find useful the recommended way it should apply output encoding in the form of an example.

Forms are Controller/view or Razor Pages.

Try this

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddWebEncoders();   // ADD WEB ENCODERS

builder.Services.AddControllers();

var app = builder.Build();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

```
using Microsoft.AspNetCore.Mvc;

namespace WebAPI_XSS.Controllers;

[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet]
    public IActionResult GetUserGeneratedContent()
    {
        var userGeneratedContent = "User-generated content here";
        return Content(userGeneratedContent);
    }    
}
```

**Comment by Rick-Anderson** [comment]
To implement input validation to prevent XSS attacks:

1. Use model validation to ensure that any data submitted to the API is valid and safe. You can do this by using data annotations to decorate your model classes and properties with validation rules.
1. Use input validation middleware to validate incoming requests and block any requests that contain potentially malicious input.
1. Sanitize any user-generated content before storing it in your database or using it in your application.

Here's an example of how you can use data annotations to decorate your model classes and properties with validation rules:

```dotnetcli
public class User
{
    [Required]
    public string Username { get; set; }

    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}

```

The preceding example is using:

* The `Required` and `EmailAddress` data annotations to ensure that the `Username` and `Email` properties are not empty and contain a valid email address.
* The `DataType` data annotation to ensure that the `Password` property contains a password and not some other type of data.

Use input validation middleware to validate incoming requests and block any requests that contain potentially malicious input. To do this, add the following code to `Progam.cs`:

```csharp
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddWebEncoders();
// Add input validation middleware
builder.Services.AddMvc(options =>
{
    options.Filters.Add(new AutoValidateAntiforgeryTokenAttribute());
});

builder.Services.AddControllers();

var app = builder.Build();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

In this example, we're adding the `AutoValidateAntiforgeryTokenAttribute` filter to the MVC options. This filter automatically validates any incoming requests and blocks any requests that contain potentially malicious input.

Sanitize any user-generated content before storing it in your database or using it in the app. To do this, use an HTML sanitizer library like the `Microsoft.AspNetCore.WebUtilities` package:

```csharp
using Microsoft.AspNetCore.Mvc;

namespace WebAPI_XSS.Controllers;

[Route("api/[controller]")]
[ApiController]
public class MyController : ControllerBase
{
    [HttpGet]
    public IActionResult GetUserGeneratedContent()
    {
        var userGeneratedContent = "User-generated content here";
        return Content(userGeneratedContent);
    }    
}
```
