### ISSUE TITLE
Sample links are broken/don't exist

### ISSUE THREAD

**Issue by rafael-f** [dotnet/AspNetCore.Docs#28804]
Page contains broken sample links: https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorServerEFCoreSample/BlazorServerDbContextExample/Pages/Index.razor

There's no BlazorServerDbContextExample at https://github.com/dotnet/blazor-samples/tree/main/7.0/BlazorServerEFCoreSample for version 7.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a101e4d-85a2-8013-0f62-40e13e45b3c6
* Version Independent ID: 66a0a920-ebd8-9b1d-c8c5-953ebb766de0
* Content: [ASP.NET Core Blazor Server with Entity Framework Core (EF Core)](https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/blazor-server-ef-core.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-server-ef-core.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **jeliknes**

**Comment by guardrex** [comment]
Thanks @rafael-f ... The sample is here (there's an extra ***wrong*** URL path segment in the published link) ... 

https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorServerEFCoreSample/Pages/Index.razor

I think a find-'n-replace 😈 got me. I was just working on this topic last week, and we don't have a built-in cross-link checker for external links ... I wish we did.
