### ISSUE TITLE
"scale" is not a known CSS property name

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/AspNetCore.Docs#28800]
![image](https://user-images.githubusercontent.com/4510984/228153454-8c09d4c8-a7e8-443b-a200-ff2f31888b7e.png)

![image](https://user-images.githubusercontent.com/4510984/228153519-799bf314-9c9d-44a5-994b-7517a31df274.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad891f84-d11e-e334-fcdc-b55c5171fca4
* Version Independent ID: 11f8db3d-9988-e0a1-89c5-c3552ee47b93
* Content: [ASP.NET Core Blazor startup](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @GF-Huang ... It's supported by recent browser versions now.

* https://developer.mozilla.org/en-US/docs/Web/CSS/scale
* https://caniuse.com/?search=scale

Visual Studio uses a custom CSS linter, so you could open a request (**Report a Problem**) with the Visual Studio team asking for the CSS property to be added ...

https://developercommunity.visualstudio.com/VisualStudio/report

**Comment by guardrex** [comment]
It's not a new property, and it is supported. The linter is just giving you a tip. It's not really telling you what "Can I use..." will tell you about the adoption of a CSS property across browsers. It's also required for the new feature to work, so there's no way to get around it for that particular use case. I think the best way to look at this is just that there's a lag for the VS team to react to new CSS properties. Someone may need to tell them when a CSS property is widely adopted and request that it be added to the linter. Either way, the product unit that works on ASP.NET Core and the product unit that work on Visual Studio are two different teams. They have a fair amount of communication; but on something like this it might take more time for coordination to occur. I think you should just "Report a Problem" to them using the built-in VS feature. That goes directly to the VS team.

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/228246690-615ad7d1-dbf8-4566-992f-b1ff95f7fa29.png)
