### ISSUE TITLE
official blazor docs with .net 7.0 has build errors

### ISSUE THREAD

**Issue by EivindAntonsen** [dotnet/AspNetCore.Docs#28817]
Hi,
the code example provided on binding causes build errors.
> Argument 3: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<string>' to 'System.Action<string?>'

I tried copypasting the code under the "correct approach" with this description:
> Consider the following correct approach using @bind:get/@bind:set for two-way data binding:

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by EivindAntonsen** [comment]
I may have found the error. The description above the code example has bind in upper case, but the code example has lower case. I tried changing my code to `@Bind` from `@bind` and now the code runs.

**Comment by guardrex** [comment]
@EivindAntonsen ... That error was due to a point-in-time problem. Update your Visual Studio to the latest version, and it should go away and work as the article directs.
