### ISSUE TITLE
Fix asp-src

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28818]
[asp-src](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?branch=pr-en-us-28802&view=aspnetcore-7.0#asp-src)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c90104e1-65b1-0007-e56d-0dffef4b1a44
* Version Independent ID: 5c95e5dc-dc10-8658-91fd-1d55d3959c37
* Content: [Script Tag Helper in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?branch=pr-en-us-28802&view=aspnetcore-7.0#asp-src)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/script-tag-helper.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by pkellner** [comment]
Looks good to me though I don't think I wrote that particular doc on the script tag helper. I can't find any other discussion of asp-src so sounds like a mistake. Maybe got confused with asp-fallback-src?

**Comment by Rick-Anderson** [comment]
@pkellner  much appreciated.
