### ISSUE TITLE
High contrast mode code example bug

### ISSUE THREAD

**Issue by a-matusewicz** [dotnet/AspNetCore.Docs#28819]
Some of the code examples do not render readably in high contrast mode. I have to highlight the sections to read them.

Ex.
![image](https://user-images.githubusercontent.com/29668914/228652272-92914a51-244e-40ba-8511-2622e25336ea.png)
![image](https://user-images.githubusercontent.com/29668914/228652282-94cca4f3-89b3-4ec2-874d-5b50b69d62c8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JasonWHowell** [comment]
@a-matusewicz can you please tell us more about your setup - what kind of device, what OS, and what browser and version are you using when it happens?

On a recent build of the Edge browser, [the page](https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-7.0#generate-antiforgery-tokens-with-iantiforgery) looks OK in high contrast mode.

![image](https://user-images.githubusercontent.com/5067358/228693957-c70564e6-04f3-4024-82df-993ab2cce1ea.png)


Thanks, Jason

**Comment by Rick-Anderson** [comment]
@JasonWHowell  can you test in Chrome?

**Comment by JasonWHowell** [comment]
Chrome on Windows PC. Maybe its Firefox or Safari, or macOS. 

![image](https://user-images.githubusercontent.com/5067358/229303950-b6e4f6d6-c208-434f-8a28-dd0f3c3c64b0.png)

**Comment by JasonWHowell** [comment]
Just a thought: Sometime AdBlockers can cause funny things to happen as well.
