### ISSUE TITLE
Document shows a call to Microsoft.Extensions.Options.Options.Get, but no such method exists in .NET 7.

### ISSUE THREAD

**Issue by szalapski** [dotnet/AspNetCore.Docs#28831]
[This code sample](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio#code-try-4) includes a call to `Microsoft.Extensions.Options.Options.Get`, but no such method exists in .NET 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio#blazor-webassembly-authentication-uses-history-state-for-redirects)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

**Comment by szalapski** [comment]
Cool, never realized that.  Thanks.
