### ISSUE TITLE
No docs for external login 

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#28832]
In the docs we can see how to **setup** google sign in, but nowhere can I find demo code for how to actually do the sign In.

For example in MVC5 I had:
```
[HttpPost]
[AllowAnonymous]
public ActionResult ExternalLogin(string provider, string returnUrl) // provider = Google
{
    // Request a redirect to the external login provider
    return new ChallengeResult(provider, Url.Action("ExternalSign", "Account", new { ReturnUrl = returnUrl }));
}

[AllowAnonymous]
public async Task<ActionResult> ExternalSign(string returnUrl)
{
    var loginInfo = await HttpContext.GetOwinContext().Authentication.GetExternalLoginInfoAsync();
    ...
```
Is there somewhere in the docs the equivalent for ASP.net Core ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0#sign-in-with-google)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The instructions are complete. Run the app and sign in.
Take a look at https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity to see that code.

**Comment by omuleanu** [comment]
> The instructions are complete. Run the app and sign in.

@Rick-Anderson That's what the user will do,
I can't "sign in" until I wrote the action for SignIn,

for that I need to know :
1) How to redirect to Google Sign in, 
2) Read the result (LoginInfo) from Google

**Comment by omuleanu** [comment]
found an example here: https://stackoverflow.com/a/53705039/112100

**Comment by Rick-Anderson** [comment]
Why don't you want to use `SignInManager`, `UserManager `or ASP.NET Core Identity itself?

**Comment by omuleanu** [comment]
@Rick-Anderson I've never used those, and don't know how they work, think identity needs several tables in the Db, in my case it's the bare minimum, even the First/Last Name is not registered.

All I need is to get from Google the Email, Name

(I'm converting an app from MVC5 to .net Core 7)
in mvc5 I was using owin,
`var loginInfo = await HttpContext.GetOwinContext().Authentication.GetExternalLoginInfoAsync();`
and getting
`loginInfo.Login.LoginProvider, loginInfo.Email, loginInfo.ExternalIdentity.Name`

now I'm guessing
```
var res = await HttpContext.AuthenticateAsync("External");
res.Principal.FindFirst(ClaimTypes.NameIdentifier)
res.Principal.FindFirst(ClaimTypes.Email)
```
not sure for the `LoginProvider`

**Comment by Rick-Anderson** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/migration/mvc

**Comment by omuleanu** [comment]
@Rick-Anderson thnx, but I haven't used membership, and I'm not using identity now.

I found some info here: https://github.com/aspnet/AspNetIdentity/blob/main/src/Microsoft.AspNet.Identity.Owin/Extensions/AuthenticationManagerExtensions.cs

this method:
`private static ExternalLoginInfo GetExternalLoginInfo(AuthenticateResult result)`
