### ISSUE TITLE
Create sample using IProblemDetailsWriter

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28847]
`IProblemDetailsWriter` from  [ problem details response](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-7/#new-problem-details-service)

Update sample In https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/problem-details-service or write a new sample in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware

This is how the blog post code should be ☹️:

``` c#
public class SampleProblemDetailsWriter : IProblemDetailsWriter
{
    public bool CanWrite(ProblemDetailsContext context)
        => context.HttpContext.Response.StatusCode == 400;

    public ValueTask WriteAsync(ProblemDetailsContext context)
    {
        //Additional customizations

        // Write to the response
        return new ValueTask(context.HttpContext.Response.WriteAsJsonAsync(context.ProblemDetails));
    }
}
```

See https://github.com/dotnet/AspNetCore.Docs.Samples/issues/34

**Comment by david-acker** [comment]
> Update sample In https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/problem-details-service or write a new sample in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware

Just to clarify, should these changes be made in this repo or the [dotnet/AspNetCore.Docs.Samples](https://github.com/dotnet/AspNetCore.Docs.Samples) repo mentioned above?

**Comment by Rick-Anderson** [comment]
> Just to clarify, should these changes be made in this repo or the [dotnet/AspNetCore.Docs.Samples](https://github.com/dotnet/AspNetCore.Docs.Samples) repo mentioned above?

Either place.

**Comment by david-acker** [comment]
Hmm, it looks like the sample code in AspNetCore.Docs.Samples is functionally the same as the corrected sample above.

SampleProblemDetailsWriter:
```csharp
var response = context.HttpContext.Response;
return new ValueTask(response.WriteAsJsonAsync(context.ProblemDetails));
``` 

Corrected Blog Post Code:
```sharp
return new ValueTask(context.HttpContext.Response.WriteAsJsonAsync(context.ProblemDetails));
```

ProblemDetails were also returned as expected when I tested the sample out locally (with bad input for division, square rootm, etc.).

Ex:
```json
{
    "type": "https://wikipedia.org/wiki/Division_by_zero",
    "title": "Bad Input",
    "status": 400,
    "detail": "Divison by zero is not defined."
}
```

Are there any additional changes/fixes we need to make here? I didn't noticed anything else mentioned in https://github.com/dotnet/AspNetCore.Docs.Samples/issues/34.

**Comment by Rick-Anderson** [comment]
@david-acker  thanks. I think we can close this. The sample is used [here](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md?plain=1#L269-L273)
