### ISSUE TITLE
Provide explanation for TypedResults

### ISSUE THREAD

**Issue by dcarapic** [dotnet/AspNetCore.Docs#28850]
It is unclear what TypedResults provide here. There should be either be an explanation of why to use them or a link to a page where it is explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 85494](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85494)

**Comment by Rick-Anderson** [comment]
@wadepickett  this was posted 3 days ago. Can you answer it?

**Comment by Rick-Anderson** [comment]
@dcarapic sorry for the slow response, I'll take this over.

See 
* [this](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#microsoft-aspnetcore-http-typedresults) for one reason.
* [TypedResults vs Results](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-7.0#typedresults-vs-results)

Expanding on `TypedResults` vs `Results` advantages:
* `TypedResults ` return strongly typed objects, which can improve code readability and reduce the chance of runtime errors.
* Provides automatic serialization
* More concise code
* Improved testability as described above.

**Comment by dcarapic** [comment]
Thank you

**Comment by Rick-Anderson** [comment]
@dcarapic  see above https://github.com/dotnet/AspNetCore.Docs/pull/28918
That automatically closes this issue when the PR merges.
