### ISSUE TITLE
The cookie consent banner does not close when clicking Accept

### ISSUE THREAD

**Issue by AlbertoPa** [dotnet/AspNetCore.Docs#28862]
The cookie consent partial does not work properly when added to the .Net 7 web app template with Razor Pages: the Accept button does not close the banner:

``data-dismiss="alert" ``

needs to be changed to

``data-bs-dismiss="alert"``

Also, the button is not styled as in 2.2. Adding ``btn btn-link`` addresses this.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 85491](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85491)

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

**Comment by AlbertoPa** [comment]
Done. Let me know if it is OK. If so, this can be closed.

**Comment by Rick-Anderson** [comment]
@AlbertoPa  it will automatically close when the PR merges. Thanks for doing this.

**Comment by Rick-Anderson** [comment]
@AlbertoPa thanks for the PR and this reminder.

Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)
