### ISSUE TITLE
Why not expose a scoped HttpContext directly?

### ISSUE THREAD

**Issue by kzu** [dotnet/AspNetCore.Docs#28875]
Another (even more idiomatic and DI-friendly, IMHO) would be to just expose a scoped service for `HttpContext` to retrieve the current user from:

```csharp
// Program.cs
builder.Services.AddHttpContextAccessor();
builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpContextAccessor>().HttpContext!);
```

Now any component can just declare a constructor dependency and get the right instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://learn.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-7.0)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by Tratcher** [comment]
They can already inject IHttpContextAccessor. This isn't a different approach, just syntax sugar over the existing one.

**Comment by Rick-Anderson** [comment]
See #29742
