### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by ergonrod** [dotnet/AspNetCore.Docs#28890]
dotnet user-jwts - **Cleans the output of a project.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f76a2aaf-732a-f686-343b-d811faa43d44
* Version Independent ID: f76a2aaf-732a-f686-343b-d811faa43d44
* Content: [Generate tokens with dotnet user-jwts](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-7.0&tabs=windows)
* Content Source: [aspnetcore/security/authentication/jwt-authn.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/jwt-authn.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 83526](https://dev.azure.com/msft-skilling/Content/_workitems/edit/83526)

**Comment by Rick-Anderson** [comment]
```
dotnet --version
8.0.100-preview.2.23157.25

dotnet user-jwts


Usage: dotnet user-jwts [options] [command]

Options:
  -p|--project  The path of the project to operate on. Defaults to the project in the current directory.
  -o|--output   The format to use for displaying output from the command. Can be one of 'default', 'token', or 'json'.
  -h|--help     Show help information

Commands:
  clear   Remove all issued JWTs for a project
  create  Issue a new JSON Web Token
  key     Display or reset the signing key used to issue JWTs
  list    Lists the JWTs issued for the project
  print   Print the details of a given JWT
  remove  Remove a given JWT

Use "dotnet user-jwts [command] --help" for more information about a command.
```

**Comment by ergonrod** [comment]
Thanks for the info. I think the description is wrong in the documentation: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-7.0&tabs=windows

![image](https://user-images.githubusercontent.com/19294010/230227787-434b7eb9-7ce6-4c59-935f-019976ee6412.png)

It says: Cleans the output of a project.

**Comment by Rick-Anderson** [comment]
@dotnet-bot  thanks for the clarification and bringing this to our attention.
