### ISSUE TITLE
S&M only except for admin

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28891]
Per [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/28826#issuecomment-1498214622)

> In other repos (dotnet/aspnetcore, aspnet/Benchmarks, dotnet/runtime, etc) we have it set to only allow squash. And Admin is required for anything else. Is there a reason this repo doesn't follow the same approach?

Set up this repo to only allow S&M except for admin override.

---
[Associated WorkItem - 83525](https://dev.azure.com/msft-skilling/Content/_workitems/edit/83525)

**Comment by Rick-Anderson** [comment]
@guardrex  @tdykstra  can one of you set this up?

**Comment by tdykstra** [comment]
I set it up:

![image](https://user-images.githubusercontent.com/1569635/230230353-476068e4-f494-4c9b-80f7-a7c7358522df.png)

**Comment by tdykstra** [comment]
This doesn't provide a convenient admin override method.  The admin would have to go in to this same Settings section and enable Merge without squash, then go back and reset the setting after merging the PR.
