### ISSUE TITLE
Example in section triggers an exception with the message 'For a dotnetjs resource, custom loaders must supply a URI string'

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/AspNetCore.Docs#28903]
Applying the second example triggers an exception with the message `For a dotnetjs resource, custom loaders must supply a URI string`. What the message mean is that the loader expects a string or `null` or `default` return value when loading the resource `dotnetjs`, and not a `fetch(...)` promise (that is returned for all resources in the second example).

The first example returns a string in the case of `dotnetjs`, `dotnetwasm` and `timezonedata`.

Combining the first and second examples, make the loader work as expected, something like the following

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        Blazor.start({
            loadBootResource: function (type, name, defaultUri, integrity) {
                console.log(`Loading: '${type}', '${name}', '${defaultUri}', '${integrity}'`);
                switch (type) {
                    case 'dotnetjs':
                    case 'dotnetwasm':
                    case 'timezonedata':
                        return null;
                    default:
                        return fetch(defaultUri, {
                            cache: 'no-cache',
                            integrity: integrity,
                            headers: { 'Custom-Header': 'Custom-Value' }
                        });
                }
            }
        });
    </script>

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad891f84-d11e-e334-fcdc-b55c5171fca4
* Version Independent ID: 11f8db3d-9988-e0a1-89c5-c3552ee47b93
* Content: [ASP.NET Core Blazor startup](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources)
* Content Source: [aspnetcore/blazor/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jan-johansson-mr ... Yes, I'm able to repro that. Open this as a product support request with the product unit. IIRC, this code used to work, so I suspect that something shifted over the last year or two. When you open for them, provide the full error ...

```
blazor.webassembly.js:1 
        
Uncaught Error: For a dotnetjs resource, custom loaders must supply a URI string.
    at blazor.webassembly.js:1:43248
    at window.__wasmmodulecallback__ (blazor.webassembly.js:1:43352)
    at <anonymous>:1:20
    at blazor.webassembly.js:1:43463
    at blazor.webassembly.js:1:43478
    at new Promise (<anonymous>)
    at Object.start (blazor.webassembly.js:1:34639)
    at Object.At [as start] (blazor.webassembly.js:1:59571)
```

Open the issue for them at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28903
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
