### ISSUE TITLE
Add sample using Microsoft.AspNetCore.Http.TypedResults

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#28916]
See 
[Microsoft.AspNetCore.Http.TypedResults](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#microsoft-aspnetcore-http-typedresults)

Can we get this into the code sample project?
See [this code](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/minimal-apis/samples/MinApiTestsSample/UnitTests/TodoInMemoryTests.cs)

Also we need the following code in a sample from [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/28918#issuecomment-1500499632)
That can go into a different sample if that's easier.

cc @fiyazbinhasan 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9487a919-5254-627c-d5cf-169d99a7e51b
* Version Independent ID: 9487a919-5254-627c-d5cf-169d99a7e51b
* Content: [Test Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/test-min-api?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/test-min-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/test-min-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 83791](https://dev.azure.com/msft-skilling/Content/_workitems/edit/83791)

**Comment by fiyazbinhasan** [comment]
sure. I'll take a look at it 😊

**Comment by Rick-Anderson** [comment]
Also we need the following code in a sample from [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/28918#issuecomment-1500499632)
That can go into a different sample if that's easier.
