### ISSUE TITLE
Possible mistake   in proxy load balancing  section

### ISSUE THREAD

**Issue by zaozaoniao** [dotnet/AspNetCore.Docs#28919]
[Enter feedback here]

The proxy load balancer
say：  L7 proxies understand HTTP/2, and are able to distribute gRPC calls multiplexed to the proxy on one HTTP/2 connection across multiple endpoints.

maybe：  The LB distributes the RPC call to one of **the available backend servers**  that implement the actual logic for serving the call.  not **proxy**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484737e7-abb8-c142-35f8-22a35817270d
* Version Independent ID: 9e412677-c511-9f5b-4654-95e0177c7dd4
* Content: [Performance best practices with gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/performance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
See [Proxy load balancing](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#proxy-load-balancing)
An L7 (application) proxy works at a higher level than an L4 (transport) proxy. L7 proxies understand HTTP/2, and are able to distribute gRPC calls multiplexed to the proxy on one HTTP/2 connection across multiple endpoints. Using a proxy is simpler than client-side load balancing, but can add extra latency to gRPC calls.

**Comment by zaozaoniao** [comment]
Why make a copy？

client===> L7  proxy  ===》 upstream backend endpoints 

The  L7 proxy  distribute the  grpc  call  to  upstream backend endpoint， Not to itself.

**Comment by JamesNK** [comment]
Is this clearer?

https://github.com/dotnet/AspNetCore.Docs/pull/28938
