### ISSUE TITLE
defaults for IMemoryCache.set

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#28924]
What are the default options when calling:
```
IMemoryCache.Set(key, value)
```
after how much time the value will expire ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 85497](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85497)

**Comment by Rick-Anderson** [comment]
It's not time based.
