### ISSUE TITLE
instructions dont match

### ISSUE THREAD

**Issue by JosephmachinegunG** [dotnet/AspNetCore.Docs#28926]
wft instructions don't match what visual studio is showing dumb as f

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://learn.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-5.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Hi @JosephmachinegunG, what version of Visual Studio are you using?   The version of the topic you created this issue on like it is .NET 5.   In which case the version of Visual Studio that was available for .NET 5 would be represented in the docs which is Visual Studio 2019, listed in the Prerequisites section.  On the top left is a version selector, and you can choose .NET 7.0 which is also representing the latest Visual Studio 2022.  Those two versions of Visual Studio are notably different for the getting started steps.

I will close this issue for now, but if you feel there is still an issue here, feel free to reopen it.
