### ISSUE TITLE
Blazor and TypeScript 

### ISSUE THREAD

**Issue by Flachdachs** [dotnet/AspNetCore.Docs#28923]
The other day I tried to write my JS interop scripts in TypeScript. This worked quite well. There are documentations like [this tutorial](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2022) that describes how to get simple TypeScript support in C# projects and also documentation that describe [how to manage npm packages](https://learn.microsoft.com/en-us/visualstudio/javascript/npm-package-management?view=vs-2022) in your projects. (I ended up with a more sophisticated but still simple solution with a single output file created with Webpack.) But then I searched the net for "blazor typescript" to find a .d.ts file/package for the DotNet and DotNetObject strongly typed definitions and found nothing. Also searching for "blazor" in the npm packages repository gave me no useful result. I only found the quite outdated 3rd party project @types/blazor__javascript-interop at DefinitelyTyped. One participant of that project told me finally about `@microsoft/dotnet-js-interop`.

My suggestion is to add a section about TypeScript to the official documentation, e.g. in Blazor ->JavaScript interop -> Overview. In my opinion you don't need to go into the deep details, but `@microsoft/dotnet-js-interop` should definitely be mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57ed3088-2f9b-f51a-fd17-0c0de2949c57
* Version Independent ID: 49fa31d8-72a6-01a1-027d-6edeac9e0fc4
* Content: [ASP.NET Core Blazor JavaScript interoperability (JS interop)](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/javascript-interoperability/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @Flachdachs ... Let's ask @mkArtakMSFT and @danroth27 to take a look at your request.

**Comment by guardrex** [comment]
@Flachdachs ... Management is agreeable to surfacing information on `@microsoft/dotnet-js-interop`.

The most basic info is from the package.json file ...

> Provides abstractions and features for interop between .NET and JavaScript code.

... with the link at npm ...

https://www.npmjs.com/package/@microsoft/dotnet-js-interop?activeTab=readme

... and the reference source at ...

https://github.com/dotnet/aspnetcore/tree/main/src/JSInterop

What else would be helpful, or would it be enough to merely surface its existence with the cross-links?

**Comment by Flachdachs** [comment]
The minimum in my opinion is to mention that `@microsoft/dotnet-js-interop` exists. To be a bit more helpful the two links from my opening post can help readers to get things rolling. But the first article isn't Blazor specific, the reader has to adjust some parts to the conditions in a Blazor project. Not a big deal if you understand what you are doing and not just repeating tutorials step by step.

Also for complete newbies a short description what TypeScript is and how it can help can be useful, including the link to https://www.typescriptlang.org/ for the details and a tutorial.

The next step would be using webpack or a comparable tool. Because following the mentioned tutorials you will get one .js file for each .ts file, and you need to add references for each of them in the `index.html` resp. `_Host.cshtml`. Additionally references are different when using a Razor Class Library, but that is already [described in the docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries). However, webpack can create a bundled single file. But this is an advanced topic, that should be covered on a separate page. I can't tell how much JS Interop a typically project needs and how many developers have the wish to separate their code in multiple files. On the other hand it wasn't that difficult (for me) to figure out a solution after reading webpack's tutorial.

**Comment by guardrex** [comment]
***UPDATE***: I'll circle around to this issue after I get caught up on .NET 8 preview coverage. It might take a few weeks to get there, but this is tracked and won't get lost. I will get back to it *ASAP* 🏃.

**Comment by guardrex** [comment]
Yes, that's fine. For a full-fledged article on the subject, we'd want to have it approved before you went to the trouble of spending a lot of time on a write-up. If the content is relatively short, more like for a section of a topic, it's less of a burden if management decides not to carry the content. You can post a comment here, and then we'll take it from there.
