### ISSUE TITLE
SignalR with Asp.net MVC & Azure SQL Database to perform realtime CRUD operations

### ISSUE THREAD

**Issue by Frankd4** [dotnet/AspNetCore.Docs#28925]
[Enter feedback here]

Hi Team,

Would you be able to also create a Doc on how to use SignalR with Asp.net MVC & Azure SQL Database to perform realtime CRUD operations (Visual Studio C#) (Simple Example)? It would be very helpful.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-gb/aspnet/core/tutorials/signalr?tabs=visual-studio&WT.mc_id=dotnet-35129-website&view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @Frankd4 for taking the time to make this suggestion.

**Comment by wadepickett** [comment]
@bradygaster, any thoughts on this as far as priority, or are you hearing a lot of requests for a particular scenario that is related?

**Comment by Rick-Anderson** [comment]
What's the use case for this? There's many problems with such an architecture, not limited to:

* Security: Real-time communication  security  is complicated. You need protection against unauthorized access, data breaches, and injection attacks. You'll need to implement appropriate security measures, such as authentication, authorization, and input validation, to ensure the security of your application and data.
* Implementing real-time CRUD operations with SignalR is very complicated. You need to handle real-time updates, synchronization, conflicts & concurrency .

**Comment by Frankd4** [comment]
Hi @Rick-Anderson 

I understand, but all the examples are only related to chat, that is not the only a real world use case, customers also use databases (I'm interested in Azure SQL DB) and it would help to at least show a simple example of how to achieve this with SignalR. For example a Website which has a dashboard which needs to be refreshed with data from the database as soon as it changes or updates etc.

**Comment by Frankd4** [comment]
You also closed the issue when the user is still discussing the issue and active.
