### ISSUE TITLE
Enhance docs for TypedResult response for handling open api documentation

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/AspNetCore.Docs#28931]
Hi,
In the [TypedResults vs Results](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-7.0#typedresults-vs-results) docs, it will be great if we have a guide that when we use a local function instead of lambda for handling opne-api in a single typed result, we should use `Task<OK<TResponse>>` in the response and using `Task<IResult>` doesn't work for handling open-api docs.
I don't see any guide about this in the docs at all for single typed result with local function.

``` csharp
Task<Ok<GetProductByIdResponse>> Handle()
{
    return Task.FromResult<Ok<GetProductByIdResponse>>(TypedResults.Ok(new Message() {  Text = "Hello World!" }));
}
app.MapGet("/hello",Handle);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0e5da68-cd54-ce74-1ff3-ebd7d9fd09a4
* Version Independent ID: f0e5da68-cd54-ce74-1ff3-ebd7d9fd09a4
* Content: [Create responses in Minimal API applications](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-7.0#typedresults-vs-results)
* Content Source: [aspnetcore/fundamentals/minimal-apis/responses.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/responses.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @brunolins16
* Microsoft Alias: **brolivei**

---
[Associated WorkItem - 85489](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85489)

**Comment by captainsafia** [comment]
I believe https://github.com/dotnet/AspNetCore.Docs/pull/28918 addresses this question.

cc: @Rick-Anderson

**Comment by mehdihadeli** [comment]
For better comparison and understanding, it is better to add my sample [here](https://github.com/dotnet/AspNetCore.Docs/pull/28918/files#diff-d80d12e2f43960148282dfda0b56d276bdf1e3437d3ddc501ff1995e3cc197dfR81) with a small description about use TypedResult with local function
