### ISSUE TITLE
Dispatch exceptions to Blazor’s sync context

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#28933]
* [PU Issue](https://github.com/dotnet/aspnetcore/issues/44920)
* [API Proposal](https://github.com/dotnet/aspnetcore/issues/46068)
* [PU PR](https://github.com/dotnet/aspnetcore/pull/46074)

This will be a H3 under the *Synchronization context* section.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a32115-33f8-7d06-aaf0-b8ce918b5527
* Version Independent ID: 31ad18df-1904-bbdd-cfed-8d0d0267c10e
* Content: [ASP.NET Core Razor components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-6.0#invoke-component-methods-externally-to-update-state)
* Content Source: [aspnetcore/blazor/components/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rick-Anderson ... something 🐟 just happened here. The **dotnet-bot** added my labels for "Blazor" and "Source - Docs.ms" and then took them off for no apparent reason ☝️ ... so I'll re-add them manually now. I think there's a 😈 in the label management now.

**Comment by Rick-Anderson** [comment]
@guardrex  keep me posted. If this re-occurs, I'll open a support issue with the build team.
