### ISSUE TITLE
Example for client creation in .net48

### ISSUE THREAD

**Issue by korteksz** [dotnet/AspNetCore.Docs#28951]
Hi,

UnixDomainSocketEndPoint and SocketsHttpHandler are only available in netstandard2.1 and greater. I would like to create a client connection from .net48 application, but for me it is not that straightforward how to do it. Could you provide an example for this scenario as well? 

Thanks in advance!

Greetings,
Zoltán

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9af2ca8f-eefb-ae3d-ba52-d6b2a826945d
* Version Independent ID: 9af2ca8f-eefb-ae3d-ba52-d6b2a826945d
* Content: [Inter-process communication with gRPC and Unix domain sockets](https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-uds?view=aspnetcore-6.0)
* Content Source: [aspnetcore/grpc/interprocess-uds.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/interprocess-uds.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
That's not supported on .NET Framework

**Comment by korteksz** [comment]
Ah okay, and using the named pipes is supported on .NET Framework?

**Comment by korteksz** [comment]
Okay, thanks for the fast feedback!

**Comment by korteksz** [comment]
Maybe one last question to the named pipes. 

The NamedPipeClientStream class is available in .net48 according to this page:
https://learn.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeclientstream?view=net-7.0

Only the SocketsHttpHandler is missing, but they have a remark which states that it can be replaced by a HttpClientHandler somehow:
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-7.0#remarks

I would assume based on that information that it is possible to use named pipes in .NET Framework. Could you give me an explanation why isn't it supported then?

**Comment by JamesNK** [comment]
Because SocketsHttpHandler is missing.
