### ISSUE TITLE
New Visual Studio templates make for easy mistakes in "First MVC App" tutorial.

### ISSUE THREAD

**Issue by mdekrey** [dotnet/AspNetCore.Docs#28960]
In the template selection for Visual Studio, the named template is "ASP.NET Core Web App (Model-View-Controller)". Unfortunately, for someone new to Visual Studio, "ASP.NET Core Web App" seems correct and works for the first step of the tutorial, but does not work at "Add a controller". Is there a way this can be clarified?

I'm happy to submit a PR, though I am unsure how to improve the wording. An additional image may be necessary.

Thanks - this has been a valuable tool for those I have been mentoring!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 85498](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85498)

**Comment by wadepickett** [comment]
@mdekrey, thanks for bringing this up.  I am actually right in the middle of updating that entire series today.  I will consider the possibility of rewording or adding a note.  I agree it is relatively easy for someone new to select the wrong one since **ASP.NET Core Web App** shows first in the list as you start entering text for a search.

**Comment by Rick-Anderson** [comment]
@wadepickett don't change this without my approval. This hasn't been an issue with the previous 4M folks that followed these steps and we don't want to add extra verbiage for the next 10M.
