### ISSUE TITLE
Would be helpful if there was an example for EventCallback (with no return value). 

### ISSUE THREAD

**Issue by gregowahoo** [dotnet/AspNetCore.Docs#28973]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa724f22-3a49-c7f6-1500-ac2d8dde5894
* Version Independent ID: 5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0
* Content: [ASP.NET Core Blazor event handling](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/event-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gregowahoo ... The product unit doesn't really agree. They provided the following to me for publication in the article ...

> Prefer the strongly typed `EventCallback<TValue>` over `EventCallback`. `EventCallback<TValue>` provides enhanced error feedback to users of the component. Similar to other UI event handlers, specifying the event parameter is optional. Use `EventCallback` when there's no value passed to the callback.

... which indicates their suggestion that devs should favor the typed version, and it's not difficult to strip it off if you want to. Thanks anyway for the feedback.
