### ISSUE TITLE
on macos, have to add nuget package "Microsoft.EntityFrameworkCore.Sqlite"

### ISSUE THREAD

**Issue by soumunote** [dotnet/AspNetCore.Docs#28992]
on macos, have to add nuget package "Microsoft.EntityFrameworkCore.Sqlite".
like [tutorial for MVC](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio-mac#add-nuget-packages)

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 85485](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85485)

**Comment by wadepickett** [comment]
Thanks @soumunote, for letting us know your experience.

When your first create the project from the template, the  Microsoft.EntityFrameworkCore.Sqlite package is not included.

Once scaffolding is run on VS for Mac per the steps in this tutorial, it includes Microsoft.EntityFrameworkCore.Sqlite (currently version 7.0.5) along with Microsoft.EntityFrameworkCore.SqlServer and a few others for you at that point.

I will test through the latest VS for Mac for this tutorial however, and verify that is the case.

**Comment by wadepickett** [comment]
I see what is happening, I think.  When using the scaffolder for **Razor Pages using Entity Framework (CRUD)** on VS for Mac, it would get the 7.0.4 package for **Microsoft.EntityFrameworkCore.Sqlite** and show up in the NuGet packages for the project.   Then it was giving a build error that it could not find it, even though the package was there.  Running update on the downloaded 7.0.4 package to 7.0.5 (Released 5 days ago) then that would take care of the problem. I will need to spend some more time on it as I have a chance to figure out what is out of sync.  Of course, downloading 7.0.5 ahead of time also takes care of issue.  Either way, I will get the doc updated to work for what the situation is.

**Comment by wadepickett** [comment]
Now after the latest update, the scaffolding is loading the  Microsoft.EntityFrameworkCore.Sqlite 7.0.5 package as opposed to 7.04 (which it was doing earlier) and adds the 7.0.5 version to the project file (.csproj) but the scaffolding tool is then not recognizing the package is there, even though it is, when it tries to add the scaffolding files.  I am adding a line of instructions in the macOS version to run add package at the CLI first, then run scaffolding for now until this is fixed, which does work.  Reporting the issue as well.
