### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by SkipSailors** [dotnet/AspNetCore.Docs#28993]
in the section titled "Configuration keys and values" (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#configuration-keys-and-values) on the first list, last bullet where it says "Array binding is described in the Bind an array to a class section," the link for "Bind an array to a class section." (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#boa)  Seems to not be present.  When I click on that link (using Brave 1.50.115) nothing happens.  When I copy the link and open it in Edge I see the top of the page, not the referenced section.  Where do I find documentation on how the Configuration API binds arrays of objectss?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#boa)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
#28994 warns you need to be on the current version for some links to work.

**Comment by Rick-Anderson** [comment]
@SkipSailors  fix will be live in 10 minutes. Try it after that.

**Comment by Rick-Anderson** [comment]
@tdykstra  fixed by include.

**Comment by SkipSailors** [comment]
Same behavior.  I will try again tomorrow, to rule out strange cache things.

**Comment by Rick-Anderson** [comment]
^F
Go to top of document.

**Comment by SkipSailors** [comment]
Behavior persists.

I see a thing.  The phrase with the href says:
              <a href="#boa" data-linktype="self-bookmark">Bind an array to a class</a>
The target anchor
              <a name=”boa”></a>
Appears thrice in the page, once at line 1746 and then again at 3313 and again at 3382.  I didn’t do a lot of studying to see if any of those names are in commented sections or something.  If all of these are in active text, I expect my browser can’t really tell where it should go, so doesn’t go anywhere.

**Comment by Rick-Anderson** [comment]
Go to current version.

**Comment by SkipSailors** [comment]
I see.

ASP.NET 6 will not be corrected.  ASP.NET 8 works.

Thanks.

**Comment by Rick-Anderson** [comment]
> ASP.NET 6 will not be corrected.  ASP.NET 8 works.

Or 7
