### ISSUE TITLE
Add additional step required for parameters to cascade from Main component

### ISSUE THREAD

**Issue by UnusualJustin** [dotnet/AspNetCore.Docs#29009]
[EDIT by guardrex to fix the code blocks]

The documentation is lacking one crucial step (and another is incorrect). The steps related to editing the Main.razor file should include the following:

```razor
<Found Context="routeData">
  <CascadingValue Value="@KeypadViewModel">
    <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
    <FocusOnNavigate RouteData="@routeData" Selector="h1"/>
  </CascadingValue>
</Found>
```

The next steps that state you need to add a private field to MainLayout.razor should be updated to:

```csharp
[CascadingParameter]
public string? KeypadViewModel { get; set; }
```

Based on my testing, this is the only way to get the value passed using the RootComponent.Parameters property to actually cascade from root. After making these changes, the parameters work as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e560e9f-cf5e-d6ab-6ba3-3bf7a45986a5
* Version Independent ID: 5e560e9f-cf5e-d6ab-6ba3-3bf7a45986a5
* Content: [Pass root component parameters in ASP.NET Core Blazor Hybrid](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/root-component-parameters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/root-component-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/root-component-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @UnusualJustin ... I'll take a look at this first thing tomorrow morning.

**Comment by UnusualJustin** [comment]
@guardrex, I'm not sure how relevant it is, but for my testing I'm using MAUI BlazorWebView / .NET 7. If I can be of any other help (or if you discover that I'm incorrect), please let me know.

**Comment by guardrex** [comment]
... and the 🧀 moved in the sample app. The files that the document says are in the sample app aren't present, so I'll need to track those down. Even if I do find them for new cross-links, I think it's best if the topic keeps a copy of them in the text, so I'm going to add them to the topic.

**Comment by guardrex** [comment]
It either moved or the link was never correct. That sample app is over here ...

https://github.com/davidbritch/dotnet-maui-samples/tree/main/XAML/XamlSamples/XamlSamples

... but I would like to see about the topic hosting the sample code to prevent this from happening again.

**Comment by guardrex** [comment]
I actually found my local sample app for this experience, and it runs here ...

![image](https://user-images.githubusercontent.com/1622880/233074252-dee296ef-591f-4197-aac0-3f368def522e.png)

I'll check your remarks against the code that I have. *Stand-by .........................*

**Comment by guardrex** [comment]
But I thought that the `KeypadViewModel` was assigned in the dict passed to the params in `MainPage.xaml.cs`, and then the `Keypad` component's `KeypadViewModel` comes from that dictionary.

```csharp
public MainPage()
{
    InitializeComponent();
    rootComponent.Parameters = new Dictionary<string, object> { { "KeypadViewModel", new KeypadViewModel() } };
}
```

We need to ping the engineer who wrote the article and built the sample ... @davidbritch ... David, can you take a look at this issue and confirm that the view model instance is passed correctly using the article/sample's guidance? If not, do we need to make the changes that @UnusualJustin is suggesting?

**Comment by guardrex** [comment]
I see what you mean. Let's let @davidbritch take a look and confirm, given that this content/sample came from him or from the sample code in the sample app over there, then we can proceed to change the example with his blessing. He should be along in a bit to take a look at this.

**Comment by davidbritch** [comment]
I've just looked at this and I agree with @UnusualJustin . From the doc it looks like:

1. A `KeypadViewModel` is instantiated in MainPage.xaml.cs that's passed to the `KeypadViewModel` property in Main.razor.
2. Another `KeypadViewModel` is instantiated in MainLayout.razor, which then cascades down the component hierarchies.

 new `KeypadViewModel` is instantiated in MainLayout.razor, which is then cascaded. So while that shows the technique, IMO a better example would be to cascade `KeypadViewModel` from MainPage.xaml.cs into MainLayout.razor.

**Comment by guardrex** [comment]
I think I figured out what I'm doing here .... *MAYBE* 🙈😆. I agree with your suggested testing approach, @UnusualJustin, of setting an `Id` property value in the dictionary to confirm the behavior with ...

```csharp
rootComponent.Parameters = 
    new Dictionary<string, object>
    {
        {
            "KeypadViewModel", 
            new KeypadViewModel()
            {
                Id = "Set in MainPage.xaml.cs"
            }
        }
    };
```

... and that did work using your suggested code updates ...
 
![image](https://user-images.githubusercontent.com/1622880/233364981-4abee781-f434-425a-a07d-8ef9c1563a9d.png)

I'll see about writing up the changes now, and I'll ping you both on the PR for review.
