### ISSUE TITLE
Error - no database provider found

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#29007]
See https://github.com/MicrosoftDocs/feedback/issues/3910.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 87019](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87019)

**Comment by wadepickett** [comment]
At first glance, I see a package version mismatch between packages in the original example which may be the issue.  
7.0.5 for Microsoft.VisualStudio.Web.CodeGeneration.Design
7.0.4 for the rest of the packages.

The packages were just recently updated for 7.0.5.

I will test the instruction of course though.

**Comment by wadepickett** [comment]
I think I see what happened. There was a change in the UI for adding a new scaffolding item that appeared in a recent tooling update that this topic had not yet accounted for.  It was updated to VS 2022/.NET 7 but before the recent update changing the VS UI.  

The provider such as SQL Server and SQLite can be selected now in the UI for **Add New Scaffold Item** when setting the target model and DbContext class.  In the case here where VS (Windows) was used, SQL Server should be selected.

So the instructions would be updated to something along the lines of this, along with new screenshots for VS for Windows:

In the **Add New Scaffolded Item** dialog:

* In the left pane, select **Installed** > **Common** > **MVC**.
* Select  **MVC Controller with views, using Entity Framework**.
* Select **Add**.

Complete the **Add MVC Controller with views, using Entity Framework** dialog:

* In the **Model class** drop down, select **Movie (MvcMovie.Models)**.
* In the **Data context class** row, select the **+** (plus) sign.
  * In the **Add Data Context** dialog, the class name *MvcMovie.Data.MvcMovieContext* is generated.
  * Select **Add**.
* In the **Database provider** drop down, select **SQL Server**.
* **Views** and **Controller name**: Keep the default.
* Select **Add**.

**Comment by gewarren** [comment]
[like]  Genevieve Warren reacted to your message:
________________________________

**Comment by wadepickett** [comment]
Fixed with #29115 

Updated the scaffolding instruction and screenshots as planned per above.
