### ISSUE TITLE
Earlier versions of .NET Hosting Bundle installers

### ISSUE THREAD

**Issue by jovton** [dotnet/AspNetCore.Docs#29019]
On this page (https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0#earlier-versions-of-the-installer) there is a section that talks about earlier versions of the Hosting Bundle installer, warning us that they may contain versions of .NET that have reached end-of-life (support). Although there is a link to the end-of-life (support) policy (https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), I cannot find information anywhere on which installers (hosting bundle) contain which EOL versions. Can this information be added anywhere on the documentation, please? Our managers are constantly nagging us for this information. Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jovton ... Each version of the hosting bundle has the .NET version in the filename of the installer. The EOL versions of .NET are in the document you cited in the **Out of support versions** table.

**Comment by jovton** [comment]
thanks @guardrex for the info. Question: Will a NET Core 3.1 app be able to run on an IIS installation where only the .NET 6 or 7 hosting bundle was installed?

**Comment by guardrex** [comment]
My memory of the ANCM from several years ago when I worked on these hosting docs quite a bit is that it was said to be backwards compatible with prior framework releases. If you have 3.1 installed on the machine (or are publishing/deploying self-contained apps), the newer ANCM (from 6.0 or 7.0) *should be* 🤞🍀 work just fine. There's always the possibility that *something* will go sideways. I'm not sure how extensively the team tests each release of the ANCM with prior framework release apps.

Pinging @halter73 to take a look at this.

**Comment by guardrex** [comment]
Well ... we do say "LTS releases" on the backwards-compat remark ...

> The ASP.NET Core Module (ANCM) is installed with the .NET Core Runtime from the [.NET Core Hosting Bundle](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0). The ASP.NET Core Module is forward and backward compatible with LTS releases of .NET.

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-6.0#install-aspnet-core-module-ancm

So yeah ... I think you'll be ok with LTS releases per that remark.

**Comment by guardrex** [comment]
Note to @halter73 ... They don't show the **Release type** column on the **Out of support versions** table ...

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

... so it will be hard going forward to match our ANCM backward-compat remark to the content that's provided there.

Note @jovton from the latest releases that strictly-speaking that .NET 7 is an STS release and wouldn't be supported for 3.1 apps ... ***strictly-speaking*** that is. It might work, but it wouldn't be supported if we go by the plain interpretation of the text.
