### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by dwhiteddsoft** [dotnet/AspNetCore.Docs#29026]
I have a method on my Hub called join:
```csharp
        public async void Join(string group)
        {
            if (_groups.IndexOf(group) > -1) 
            {
                if (!_games.ContainsKey(group)) 
                {
                    Console.WriteLine($"Joining: {group} from {Context.ConnectionId}");
                    await Groups.AddToGroupAsync(Context.ConnectionId, group);
                    await Clients.Group(group).SendAsync("joined", true);
                }
                _games[group].Add(Context);
            }
        }
```

Why is it when I run the exact same code as the example on this page, I receive the following error:
```text
System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'GameHub'.'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-7.0)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by wadepickett** [comment]
@dwhiteddsoft, thanks for relating your experience.   

The example for groups in SignalR uses `async Task`:
 `public async Task AddToGroup(string groupName)`.   

However your example uses `async void`:
 `public async void Join(string group)`.

This great topic by David Fowler might be helpful:  https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#async-void

I will go ahead and close this issue, but if you feel there is something to correct in this document, feel free to re-open.

**Comment by dwhiteddsoft** [comment]
So wait, are you saying that the only way to add/remove a user to/from a group in a hub is to have a methods **SPECIFICALLY** named like the below? I could not simply name the message handlers on the hub foo and bar?

```csharp
public async Task AddToGroup(string groupName)
{
    await Groups.AddToGroupAsync(Context.ConnectionId, groupName);

    await Clients.Group(groupName).SendAsync("Send", $"{Context.ConnectionId} has joined the group {groupName}.");
}

public async Task RemoveFromGroup(string groupName)
{
    await Groups.RemoveFromGroupAsync(Context.ConnectionId, groupName);

    await Clients.Group(groupName).SendAsync("Send", $"{Context.ConnectionId} has left the group {groupName}.");
}
```

**Comment by wadepickett** [comment]
I was trying to communicate to use `async Task` rather than `async void`, you were using `async void`.  That was the restriction to apply.  Sorry for the confusion.  Connections are added to groups or removed from groups on the hub server using the `AddToGroupAsync` and `RemoveFromGroupAsync` methods.
