### ISSUE TITLE
Add a note that the SupplyParameterFromQueryAttribute only works on routing components

### ISSUE THREAD

**Issue by OnSive** [dotnet/AspNetCore.Docs#29027]
There is no information that the [`SupplyParameterFromQueryAttribute`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.supplyparameterfromqueryattribute?view=aspnetcore-7.0) only works on routing components.

The only reference I found was in a GitHub issue on dotnet/aspnetcore that says "This is currently by design" (https://github.com/dotnet/aspnetcore/issues/36966#issuecomment-961864699).

It would be great if there was a highlighted note on the documentation pages to prevent desperation like I had.
- https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0#query-strings
- https://learn.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components#query-string-parameters

**Comment by Rick-Anderson** [comment]
Per ChatGPT:

The SupplyParameterFromQueryAttribute is an ASP.NET Core attribute that can be applied to action method parameters to bind them to values from the query string.

While it is commonly used with routing components, it can also be used with other types of controllers such as ApiController or Controller.

The SupplyParameterFromQueryAttribute can be used to bind parameters from a query string to action method parameters, regardless of the controller type, as long as the action method has a parameter that matches the query string key.

For example, you can apply the SupplyParameterFromQueryAttribute to an action method parameter in a regular Controller like this:

```
public IActionResult Index([SupplyParameterFromQuery] string searchTerm)
{
    // ...
}
```
In this case, the searchTerm parameter will be bound to the value of the "searchTerm" key in the query string, regardless of whether the controller is a routing component or a regular Controller.

**Comment by guardrex** [comment]
Hello @OnSive ... The content states (emphasis added) ...

> Use the `[SupplyParameterFromQuery]` attribute with the `[Parameter]` attribute to specify that a component parameter ***of a routable component*** can come from the query string.

... so I think that is covered by the article.

btw -- Please use the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by guardrex** [comment]
Actually ... I agree this morning! ☕ is working, I guess! 😆 Let's make that point a bit clearer.

Thanks for the issue, @OnSive.

**Comment by guardrex** [comment]
btw @OnSive ... The following NOTE was already there. You may have read past it when you accessed the section ...

```
> [!NOTE]
> Component parameters can only receive query parameter values in routable components with an [`@page`](xref:mvc/views/razor#page) directive.
```

... but I'm going to add to that NOTE with Steve's reasoning.

**Comment by OnSive** [comment]
Thank you for your work!
I somehow completely over red the already existing hint multiple times.

Sorry for the extra effort.

**Comment by guardrex** [comment]
No worries, @OnSive. I'm glad that you wrote in about this. I think the enhanced coverage with the ***reason*** that Steve provided will help devs understand why this was done. It might even head off a few product unit issues on their repo from devs wondering why this is the case. I think the additional remark to just use a normal param or create a custom param in this case will send devs down the happy path 😄 ........ so I'm glad you opened the issue. Thanks, again! 🎸
