### ISSUE TITLE
Review new ObjectPool sample

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29036]
@gfoidl  @sammychinedu2ky  please review new sample [here](https://learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?view=aspnetcore-8.0#objectpool-sample) featuring `IResettable`

Code has been reviewed, more interested in comments about the sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 075aad4c-9e53-92c1-8405-70bd5ed54baa
* Version Independent ID: fa535bff-449d-ac12-ea5b-8a975b0682f6
* Content: [Object reuse with ObjectPool in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?branch=pr-en-us-29034&view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/ObjectPool.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/ObjectPool.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 86075](https://dev.azure.com/msft-skilling/Content/_workitems/edit/86075)

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson please where can I obtain the value for the moniker ends
![image](https://user-images.githubusercontent.com/36219292/233290247-142fa18e-0183-4b26-a4c9-0800f246638d.png)

and which **T** is being referred to in the image below
![image](https://user-images.githubusercontent.com/36219292/233290431-9a7c34ec-e1c8-4030-8ead-c1bb1f608413.png)

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson please where can I obtain the value for the moniker ends
![image](https://user-images.githubusercontent.com/36219292/233290247-142fa18e-0183-4b26-a4c9-0800f246638d.png)

and which **T** is being referred to in the image below
![image](https://user-images.githubusercontent.com/36219292/233290431-9a7c34ec-e1c8-4030-8ead-c1bb1f608413.png)

**Comment by gfoidl** [comment]
The sample is clear and meaningful 👍🏻 

---

![grafik](https://user-images.githubusercontent.com/5755834/233321188-f34efbb0-511d-4554-8844-f5231cdae6d4.png)

`IResettable` is linked to source.dot.net and not to the api-docs. Interim solution?

---

https://github.com/dotnet/AspNetCore.Docs/blob/8eaae4a63b3f45d877ddf0822621f06a1e12870f/aspnetcore/performance/ObjectPool/ObjectPoolSample8/Program.cs#L38-L42

For the comment I'd write something like
```c#
// Data is automatically reset if the pooled type implements IResettable
```

It's already written similar in the text above the sample-code, but a lot of people don't read text and look only for code.
And to make it very clear, that only with `IResettable` the automatic reset of the pooled objects is done.

In the "ObjectPool concepts" it's stated that a custom `PooledObjectPolicy<T>` can be used to reset the object's state before returned to the pool. But I feel this information is easily overread. Thus below the sample (also see my last point here) I'd write:

> **Note**: when the pooled type `T` doesn't implement `IResettable`, then a custom `PooledObjectPolicy<T>` can be used to reset the state of the objects before they are returned to the pool.

---

> and which T is being referred to in the image below

It's the generic type `T` from the `ObjectPool<T>`.
For me that's clear as section "ObjectPool concepts" declares that. 
Though if it's not clear enough -- cf. @sammychinedu2ky question -- maybe repeat that info here.

---

![grafik](https://user-images.githubusercontent.com/5755834/233318223-cb2c1ebd-d59b-4dc6-9b9e-68b8debc8bb4.png)
The text below the sample looks like it belongs to the sample, as further explanation. As it's not, maybe move this up to section "How to use ObjectPool"?

**Comment by sammychinedu2ky** [comment]
> The sample is clear and meaningful 👍🏻
> 
> ![grafik](https://user-images.githubusercontent.com/5755834/233321188-f34efbb0-511d-4554-8844-f5231cdae6d4.png)
> 
> `IResettable` is linked to source.dot.net and not to the api-docs. Interim solution?
> 
> https://github.com/dotnet/AspNetCore.Docs/blob/8eaae4a63b3f45d877ddf0822621f06a1e12870f/aspnetcore/performance/ObjectPool/ObjectPoolSample8/Program.cs#L38-L42
> 
> For the comment I'd write something like
> 
> ```cs
> // Data is automatically reset if the pooled type implements IResettable
> ```
> 
> It's already written similar in the text above the sample-code, but a lot of people don't read text and look only for code. And to make it very clear, that only with `IResettable` the automatic reset of the pooled objects is done.
> 
> In the "ObjectPool concepts" it's stated that a custom `PooledObjectPolicy<T>` can be used to reset the object's state before returned to the pool. But I feel this information is easily overread. Thus below the sample (also see my last point here) I'd write:
> 
> > Note: when the pooled type `T` doesn't implement `IResettable`, then a custom `PooledObjectPolicy<T>` can be used to reset the state of the objects before they are returned to the pool.
> 
> > and which T is being referred to in the image below
> 
> It's the generic type `T` from the `ObjectPool<T>`. For me that's clear as section "ObjectPool concepts" declares that. Though if it's not clear enough -- cf. @sammychinedu2ky question -- maybe repeat that info here.
> 
> ![grafik](https://user-images.githubusercontent.com/5755834/233318223-cb2c1ebd-d59b-4dc6-9b9e-68b8debc8bb4.png) The text below the sample looks like it belongs to the sample, as further explanation. As it's not, maybe move this up to section "How to use ObjectPool"?

I think the **T** should implement **IResettable** and not **IDisposable**

**Comment by sammychinedu2ky** [comment]
@Rick-Anderson

**Comment by sammychinedu2ky** [comment]
> > I think the **T** should implement **IResettable** and not **IDisposable**
> 
> `T` can have either `IResettable` (to reset the state before returned to the pool) or `IDisposable` (to dispose when not returned, or dispose when the pool itself gets disposed). These are orthogonal.
> 
> Thus I'd move this text (marked with red bracket) to be not below the sample-code.

Thanks for the clarification, but I don't know why it should implement the IDisposable since the aim of the Object pool is to not dispose but reuse. Please could you clarify me on this @gfoidl . 🙏

**Comment by sammychinedu2ky** [comment]
I also agree that the highlighted section should come before the code

**Comment by sammychinedu2ky** [comment]
please where is this value extrapolated from in the markdown @Rick-Anderson 
![image](https://user-images.githubusercontent.com/36219292/233536299-5e489cd4-dcb2-457a-bbd5-415c4a984c10.png)

I can see two include statements but they contain more than the rendered text in the published article
![image](https://user-images.githubusercontent.com/36219292/233536399-a48e01b2-ac18-42f3-aefd-4f1bc36e518c.png)

**Comment by Rick-Anderson** [comment]
@gfoidl @sammychinedu2ky  thanks
It should be good now
https://learn.microsoft.com/en-us/aspnet/core/performance/ObjectPool?view=aspnetcore-8.0

**Comment by Rick-Anderson** [comment]
> IResettable is linked to source.dot.net and not to the api-docs. Interim solution?

We should have the new API in a week.

**Comment by gfoidl** [comment]
>  It should be good now

👍🏻
