### ISSUE TITLE
Multiple apps sample

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#29043]
This topic might need an update. Potentially some tips and tricks on how to troubleshoot.

There is an updated sample https://github.com/javiercn/BlazorMultipleApps that can be used as a reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96763362-f8ba-0f11-0070-da8f9f533e21
* Version Independent ID: 96763362-f8ba-0f11-0070-da8f9f533e21
* Content: [Multiple hosted ASP.NET Core Blazor WebAssembly apps](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Notes on the differences ...

* At 5.0, you removed the leading forward slash on the 2nd app's `MapFallbackToFile` endpoint, but you might have just done that for consistency because you had the 1st app's `MapFallbackToFile` endpoint without it. The article's sample always used leading forward slashes.
* At 7.0, you added a call for `second.UsePathBase("/SecondApp");` (without mirroring it for the first app) under a "remap static files to the base path" commit title. The article's approach sets the static file path for each app ... `first.UseStaticFiles("/FirstApp");` and `second.UseStaticFiles("/SecondApp");`. The article's approach didn't set the base path for one or both apps, but the article's example does remap the request paths prior to the other middleware calls/configs ...

  ```csharp
  first.Use((ctx, nxt) =>
  {
      ctx.Request.Path = "/FirstApp" + ctx.Request.Path;
      return nxt();
  });
  ```

  ... and ...

  ```csharp
  second.Use((ctx, nxt) =>
  {
      ctx.Request.Path = "/SecondApp" + ctx.Request.Path;
      return nxt();
  });
  ```

I'll run the article's guidance for 7.0 and see how it fares and report back.

**Comment by guardrex** [comment]
So far, the article's approach ✨ ***Still Works!***&trade; ✨ (under 8.0 preview).

I'll try the updated version from your repo now.

**Comment by guardrex** [comment]
Your app isn't fully working AFAICT ... I request the `FirstApp` path, and it loads ...

![image](https://user-images.githubusercontent.com/1622880/235504009-353052e5-fed1-4743-a22b-099888a9d4d6.png)

When I request the `SecondApp` it 💥 ...

![image](https://user-images.githubusercontent.com/1622880/235504119-d15fd429-57ac-4959-ba9b-2285db19089b.png)

**Comment by guardrex** [comment]
I have a 🙈 ***RexHacked!***&trade; 🙈 version that runs at paths now. It's not too hacked ... it's close to what you have. I don't have/need a `UsePathBase` call in the `MapWhen`s. Here's the setup ...

Each client app gets a `<base>` tag ...

```html
<base href="/FirstApp/" />
```

```html
<base href="/SecondApp/" />
```

With a **Server** app `MapWhen` pair like this ...

```csharp
app.MapWhen(ctx => ctx.Request.Path.StartsWithSegments("/FirstApp"), first =>
    {
        first.UseBlazorFrameworkFiles("/FirstApp");
        first.UseStaticFiles();
        first.UseStaticFiles("/FirstApp");
        first.UseRouting();

        first.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapFallbackToFile("/FirstApp/{*path:nonfile}",
                "FirstApp/index.html");
        });
    });

app.MapWhen(ctx => ctx.Request.Path.StartsWithSegments("/SecondApp"), second =>
    {
        second.UseBlazorFrameworkFiles("/SecondApp");
        second.UseStaticFiles();
        second.UseStaticFiles("/SecondApp");
        second.UseRouting();

        second.UseEndpoints(endpoints =>
        {
            endpoints.MapControllers();
            endpoints.MapFallbackToFile("/SecondApp/{*path:nonfile}",
                "SecondApp/index.html");
        });
    });
```

One has to make sure that images ***don't*** have a leading slash to get the clients' base segment into the request path. In each of the `Index` components ...

```razor
<img src="jeep-yj.png" />
```

![image](https://user-images.githubusercontent.com/1622880/235658048-7507bbb0-27ff-4250-b752-b0be39cd20e2.png)

![image](https://user-images.githubusercontent.com/1622880/235658087-9d4771f4-2187-4319-bd0c-c8349bfb2c18.png)

![image](https://user-images.githubusercontent.com/1622880/235658176-194447f5-bc02-4c8d-ac22-dd4a5592f407.png)

![image](https://user-images.githubusercontent.com/1622880/235658231-ba8cba2b-6258-40a0-86d2-fd3d8e2f5762.png)

**Comment by philip-reed** [comment]
@guardrex Mind pushing your example please, I don't see the latest code in your fork.
I'm curious if the generated `@import` statement for the css in MultipleAppsRazorClassLibrary is using the correct subpath.

**Comment by guardrex** [comment]
Yes, I'll put that up now, but I can't get back to discussing this one today due to being buried in another set of updates. I should be free to get back to this on Monday.

**Comment by guardrex** [comment]
Clarify what you mean by ...

> generated @import statement for the css in MultipleAppsRazorClassLibrary is using the correct subpath.

There is no such line. The CSS is bundled. It's applied to the client apps via the guidance at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0&pivots=route-subpath#razor-class-library-rcl-support

**Comment by guardrex** [comment]
Moving discussion to https://github.com/dotnet/AspNetCore.Docs/issues/29248
