### ISSUE TITLE
Razor  Pages: Add a model: EF scaffolding: Tool - package mismatch possible

### ISSUE THREAD

**Issue by johndroc8** [dotnet/AspNetCore.Docs#29052]
This is the third MS tutorial I've tried to go through related to ASP.NET and Visual Studio, and none of them work.  It feels like they're either outdated or not really meant for the Mac version.  It's very frustrating.

Checking if needed NuGet packages are already installed…
Building project…
Running /Users/johnm/Projects/RazorPagesMovie/RazorPagesMovie/obj/dotnet-aspnet-codegenerator --configuration "Debug" --project "/Users/johnm/Projects/RazorPagesMovie/RazorPagesMovie/RazorPagesMovie.csproj" razorpage --model Movie --dataContext RazorPagesMovie.Data.RazorPagesMovieContext  --referenceScriptLibraries  --useDefaultLayout --no-build -outDir "/Users/johnm/Projects/RazorPagesMovie/RazorPagesMovie/Pages/Movies" --namespaceName RazorPagesMovie.Pages.Movies --useSqlite 
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
--useSqlite|-sqlite option is obsolete now. Use --databaseProvider|-dbProvider instead in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 87020](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87020)

**Comment by Rick-Anderson** [comment]
@wadepickett  can you respond?

**Comment by wadepickett** [comment]
@johndroc8, thanks for letting us know what you were running into.  Sorry for the bad experience.

The related packages for this part of the tutorial were recently updated.  In the example you provide above, I think it is an older version of the tooling that is out of sync with the newer packages.  As it warns, the tooling should not be using `--useSqlite` and would instead use  `--databaseProvider`. 

What version of Visual Studio for Mac are you using?

As a side note: This is also related to the VS Code version for the MVC tutorials I am updating at the moment for #28815 and the recently fixed issue for the VS Code version for this Razor pages tutorial #28813

**Comment by johndroc8** [comment]
Thanks much, for looking at this. I’m very new to VS and Razor Pages. I’m using the latest version of VS for Mac. Where/how do I change the db switch?

**Comment by wadepickett** [comment]
Checked through this again after an update occurred and here is what is going on, I think.  Switching back to the VS Code tab would cause the error above, I had assumed that only macOS instructions were followed since the issue was reported on the macOS tab and VS Mac was mentioned in the issue.   That said, now there seems to be an issue where the EF scaffolding tooling loads up the correct packages and they appear in the project, but it doesn't recognize that the SQLite package is there when the scaffolding begins.  Loading the SQLite package ahead of running scaffolding is a temporary fix, which I am adding to the tutorial until the scaffolding tool issue is addressed, which I am reporting.
