### ISSUE TITLE
rule explanation not sufficient

### ISSUE THREAD

**Issue by oocx** [dotnet/AspNetCore.Docs#29055]
"Configure isn't the recommended strategy for configuring logging in a minimal API application."

Why? Is it just because the recommended strategy is less code, or is there a functional difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71ea104c-b4a9-ce36-0b90-1fdba5956ddc
* Version Independent ID: 71ea104c-b4a9-ce36-0b90-1fdba5956ddc
* Content: [ASP0013: Suggest switching from using Configure methods to WebApplicationBuilder.Configuration](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0013?view=aspnetcore-7.0)
* Content Source: [aspnetcore/diagnostics/asp0013.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0013.md)
* Product: **aspnet-core**
* GitHub Login: @safia
* Microsoft Alias: **safia**

**Comment by Rick-Anderson** [comment]
copy/paste your question to ChatGPT:
'
The Configure method is a valid strategy for configuring logging in a minimal API application. However, it may not be the recommended strategy for a few reasons:

Lack of granularity: The Configure method provides a global configuration for the application, which may not provide enough granularity for more complex logging requirements. For example, you may want to log certain parts of your application at a higher or lower level of severity than others.

Limited flexibility: The Configure method is executed at application startup and provides a static configuration that cannot be changed at runtime. This may not be sufficient if you need to dynamically change logging configuration based on specific conditions or events.

Code readability: Placing logging configuration in the Configure method can make the code less readable and harder to maintain. Separating logging configuration from application startup code can make it easier to understand and modify.

Instead, a recommended strategy for configuring logging in a minimal API application is to use a logging framework such as Serilog or Microsoft.Extensions.Logging. These frameworks provide more granular and flexible configuration options, support runtime configuration changes, and improve code readability. You can configure the logging framework in the Program.cs file using the CreateHostBuilder method or in a separate logging.json configuration file.
