### ISSUE TITLE
Clarify difference between .NET 6 and .NET 7

### ISSUE THREAD

**Issue by gewarren** [dotnet/AspNetCore.Docs#29059]
Creating this issue based on https://github.com/dotnet/docs/pull/35007#issuecomment-1517575085. It's not clear on this page that in .NET 6, non-nullable properties on generic types aren't implicitly required, but in .NET 7, they are. The https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#non-nullable-properties-on-generic-types-and-required-attribute section simply disappears from the page if you change the moniker from .NET 6 to .NET 7.

The OP feels that this is a breaking change, and if so, there is a different process to follow as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#non-nullable-properties-on-generic-types-and-required-attribute)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by johnkors** [comment]
An ASP.NET Core API with an affected endpoint cannot be upgraded from ASP.NET 6 to ASP.NET 7 without changing _something_ in the code base. Doing _nothing_ will break the contract between a client and our ASP.NET Core API.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
