### ISSUE TITLE
No examples/documentation on how to use variables in localization strings

### ISSUE THREAD

**Issue by replaysMike** [dotnet/AspNetCore.Docs#29060]
This page/section no longer contains any samples on how to use variables in localization strings. Seems like a major missing topic for new users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-2.2#make-the-apps-content-localizable)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 88858](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88858)

**Comment by Rick-Anderson** [comment]
Follow the links, nothing has been dropped.

**Comment by replaysMike** [comment]
I've gone through all of the parent links, navigational sections and read / searched for "variable". Came up with nothing and gave up - google also does not come up with results for the topic.

If it's in there, it's hard as heck to find.

**Comment by Rick-Anderson** [comment]
> I've gone through all of the parent links, navigational sections and read / searched for "variable". Came up with nothing and gave up - google also does not come up with results for the topic.
> 
> If it's in there, it's hard as heck to find.

I prefer the old style with one big topic. That makes for better SEO and much easier to find in the article. @tdykstra probably knows where it's at.

**Comment by Rick-Anderson** [comment]
@replaysMike  take a look at [the pre split version](https://github.com/dotnet/AspNetCore.Docs/blob/3057fe3e950d41d39d55b45d7545acdba63defed/aspnetcore/fundamentals/localization.md)

**Comment by Rick-Anderson** [comment]
@replaysMike  is this what you're looking for?

In the preceding code, the `IStringLocalizer<T>` implementation comes from [Dependency Injection](dependency-injection.md). If the localized value of "About Title" isn't found, then the indexer key is returned, that is, the string "About Title". You can leave the default language literal strings in the app and wrap them in the localizer, so that you can focus on developing the app.

**Comment by Rick-Anderson** [comment]
@replaysMike so that's two votes for the monolithic article and 999 against.

**Comment by Rick-Anderson** [comment]
@tdykstra  this landing page needs more keywords to find the right article. Let's work on that after the .NET 8 push.

**Comment by postmeback** [comment]
Hi @Rick-Anderson , requesting you to add on this. I would like to contribute

**Comment by Rick-Anderson** [comment]
> Hi @Rick-Anderson , requesting you to add on this. I would like to contribute

Thanks.
