### ISSUE TITLE
References an interface that doesn't exist.

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/AspNetCore.Docs#29072]
In the article it lists a class to create:

`public class AuthMessageSender : IEmailSender, ISmsSender`

The interface ISmsSender does not appear to exist. A Google search can't find it. You need to reference where it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7af94e25-52f5-9f7e-33e2-67f223c7472c
* Version Independent ID: 344f2974-548c-9449-c892-5622063892fe
* Content: [Two-factor authentication with SMS in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/2fa.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/2fa.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Here it is ...

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.ui.services.iemailsender?view=aspnetcore-7.0

It's cross-linked better in the *Account confirmation* article ...

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-7.0&tabs=visual-studio#register-user-with-simulated-email-confirmation

**Comment by DavidThielen** [comment]
That has IEmailSender but not ISmsSender.

I did a Ctrl-F for it – it’s not there. Am I missing something?

Thanks – dave
