### ISSUE TITLE
This page needs a lot of work

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/AspNetCore.Docs#29070]
This page is really poorly written. A couple of issues:

1. Where can I find the interface ISmsSender?
2. The code also implements IEmailSender? Is that needed or was this just sloppy left-over code?
3. Where/how do I store the secrets for the Twilio credentials? I can't find where it gives the name for them.
4. What do I do to have the Identity code send a text? Preferably to verify the user's phone number?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7af94e25-52f5-9f7e-33e2-67f223c7472c
* Version Independent ID: 344f2974-548c-9449-c892-5622063892fe
* Content: [Two-factor authentication with SMS in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/2fa.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/2fa.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/3605364/234137141-7fda4383-daff-4467-8b6a-103d69c8c5f9.png">


> Where/how do I store the secrets for the Twilio credentials?

Per the article, [Provide credentials for the SMS service](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1#provide-credentials-for-the-sms-service)
