### ISSUE TITLE
Complete the documentation on creating a SMS provider

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/AspNetCore.Docs#29076]
# Issue description

Yes this is about an ASP.NET Core document but when I entered the issue with the link at the bottom of the page - @Rick-Anderson told me to open a new issue. So here's the new issue.

The documentation at https://learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1 has numerous problems (I get the feeling that it was written quickly). Problems include:

1. It references the interface ISmsSender in the example code. But that interface does not appear to exist. (Not to be confused with IEmailSender which does exist).
2. It does not provide the keys to use to store the twilio credentials in the secrets. It dies list it for ASPSMS.
3. Same for the options, the SMSoptions appears to be for ASPSMS with no listing for twilio.
4. Noting about how to use Identity to verify a phone number. It has the instructions to use it for 2FA, but not for just verification when it is not being used for 2FA.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [x] .NET Core
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
Stop creating new issues.
