### ISSUE TITLE
How do you have Identity verify a phone number?

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/AspNetCore.Docs#29075]
The article talks about how to use SMS for 2FA. But it does not cover how to have the Identity system confirm a phone number belongs to the user.

You need to add how to handle confirmation for systems that are not using SMS for 2FA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7af94e25-52f5-9f7e-33e2-67f223c7472c
* Version Independent ID: 344f2974-548c-9449-c892-5622063892fe
* Content: [Two-factor authentication with SMS in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/2fa.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/2fa.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DavidThielen stop creating issues on this topic that's out of support. Add to open issues.

**Comment by DavidThielen** [comment]
I’m clicking the link at the bottom of the page where it asks to submit feedback. You should change the wording to say you only want – I’m not sure what it is you find acceptable as you don’t want to be told of incomplete documentation.

Anyways point taken, don’t report anything via that link at the bottom.

**Comment by Rick-Anderson** [comment]
Stop creating new issues. Add to existing issues.  This topic is out of support.

**Comment by DavidThielen** [comment]
I added to existing issues and you told me to add it to open issues. I added a new open issue and you’re telling me to add to existing issues.

So, if you’re actually willing to accept a report of problems, tell me exactly where to enter it.

If you’re no longer interested in problems in this documentation, then say so at the bottom of the page and remove the link to report problems.

And you should say at the top of that page, at a minimum, that it requires code that does not exist and therefore can’t be used.

- dave



David Thielen- (ex)CEO/founder Windward Studios
Substack: Liberal & Loving It<https://liberalandlovingit.substack.com/> | I Don’t Know What I’m Doing<https://ceobook.substack.com/>
LinkedIn<https://www.linkedin.com/in/davethielen/> | calendy<https://calendly.com/davethielen>
(720) 352-0676 – cell
