### ISSUE TITLE
Example for RequestHeader set "X-Forwarded-Proto" Doesn't Work

### ISSUE THREAD

**Issue by cbfrank** [dotnet/AspNetCore.Docs#29079]
[EDIT by guardrex to fix the code blocks. @cbfrank, use three backticks top and bottom, and you can add a code language to the first triple-backtick group if it applies (e.g., `csharp`, `js`, `json`, `css`, `xml`, etc.]

This example code doesn't work with the apache 2.4.6, when tested with "sudo apachectl configtest", it shows the error: "Unrecognized header format %"

```
<VirtualHost *:*>
   RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
</VirtualHost>
```

instead, a "s" should be appended at the end, based on this document https://httpd.apache.org/docs/2.4/mod/mod_headers.html

```
<VirtualHost *:*>
   RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}s
</VirtualHost>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-7.0#https-configuration)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **shboyer**

---
[Associated WorkItem - 87023](https://dev.azure.com/msft-skilling/Content/_workitems/edit/87023)

**Comment by Rick-Anderson** [comment]
@spboyer please review
