### ISSUE TITLE
Use "trimming" instead of "linking"

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#29089]
The .NET platform has standardized on "trimming" instead of "linking". For example, see https://learn.microsoft.com/dotnet/core/deploying/trimming/trim-self-contained. We should do a pass on the Blazor docs to align with the trimming terminology.

**Comment by danroth27** [comment]
> Drop all references to "linker"/"linking," including updating the 3.1 topic?

No need to mess with the 3.1 docs. I'm primarily concerned here with the docs for the supported versions: 6+

**Comment by guardrex** [comment]
Resolved by https://github.com/dotnet/AspNetCore.Docs/pull/28970/commits/bdc9728dc35732a233d30282a5df0a84d8477754.

All of the other references to "linking"/"linker" pertain to content in or linked to ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1
