### ISSUE TITLE
Is it worth calling out some more popular publish targets like Azure?

### ISSUE THREAD

**Issue by AngelosP** [dotnet/AspNetCore.Docs#29113]
We don't have to re-write the actual tutorial / guidance, we can simply link to it, but it would be nice if Azure at least was called out on the page as a target with a link to the full details of how to achieve that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e07aaa4d-4ad4-778f-f74a-60d8f05d9075
* Version Independent ID: c82cf121-831d-75dd-a796-c735aad3b3e9
* Content: [Host and deploy ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio#publish-the-app)
* Content Source: [aspnetcore/blazor/host-and-deploy/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @AngelosP ... It's covered in the sub-topics of this node for each of Blazor Server and Blazor WebAssembly, as they have particular details pertaining to each hosting model.
