### ISSUE TITLE
Remove non-.NET projects like Gluu Server

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29122]
per @kevinchalet in #29116

On a related note, it's not clear at all why non-.NET projects like Gluu Server (built on top of the Janssen Project, which is Java-based) and Authentik (Python-based, AFAICT) are included in this list. This `community.md` page was originally created to list exclusively the authentication projects designed and built for ASP.NET Core: has anything changed in this regard?

Note: I'm OpenIddict's developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a218cc00-a5c0-717e-5b42-5efd6caf8abb
* Version Independent ID: 69bded75-ba42-d3ff-f27b-f7e715f6d2f8
* Content: [Community OSS authentication options for ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/community?branch=pr-en-us-29116&view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/community.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/community.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by postmeback** [comment]
I would like to contribute on this. is it ok ?

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@postmeback sure. Maybe separate them into .NET and Other Languages and Frameworks.
