### ISSUE TITLE
Blazor | SignalR + JWT - actual code missing

### ISSUE THREAD

**Issue by ghostidentity** [dotnet/AspNetCore.Docs#29129]
The sample is incomplete: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/signalr/authn-and-authz/6.0sample/SignalRAuthenticationSample

"Sample does not include code to acquire the actual JWT token" , need to know the actual process.

![image](https://user-images.githubusercontent.com/4637625/235429251-5640ff82-1a31-4c6d-98c4-9d8f9ab13f8e.png)

**Comment by guardrex** [comment]
Hello @ghostidentity ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
