### ISSUE TITLE
healthcheck default caching behaviour

### ISSUE THREAD

**Issue by oising** [dotnet/AspNetCore.Docs#29131]
This is a really odd example to show here that (imho) only serves to confuse the reader:

```csharp
app.MapHealthChecks("/healthz", new HealthCheckOptions
{
    AllowCachingResponses = false
});
```

The fact that you're showing this example would seem to imply (to a rational thinker) that the default is to allow caching responses (i.e. the value is true) - which is a nonsensical default for a health check API. I can only assume this is not the case, which tells me that this example is a bad one. 

edit: If the default behaviour is in fact to allow caching of responses, please justify this behaviour with a technical explanatory note. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 88168](https://dev.azure.com/msft-skilling/Content/_workitems/edit/88168)

**Comment by Rick-Anderson** [comment]
It states 
If the value is false (default), th
