### ISSUE TITLE
Not clear where to paste the XML code 

### ISSUE THREAD

**Issue by mortgage-calculator-online** [dotnet/AspNetCore.Docs#29145]
It's not clear where to paste the XML code once the CultureExample2.resx is created and saved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=webassembly)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
If you mean that you created the file in VS, then that ***is*** the XML of the file. You don't paste the XML if you create the file using VS. It's explained in the NOTE above the XML.

I'll close as answered, but you can post additional information if I'm not understanding your issue.
