### ISSUE TITLE
Password parameter not used

### ISSUE THREAD

**Issue by mstortz** [dotnet/AspNetCore.Docs#29153]
In the code example "Shared/PasswordEntry.razor", the Password parameter does not determine the initial value of the password.  See the example [BlazorFiddle](https://blazorfiddle.com/s/1km91kp1).

Perhaps the value of password should be set in OnParametersSet?

```
    protected override void OnParametersSet()    
    {
        base.OnParametersSet();
        password = Password;
    }
```

[Updated BlazorFiddle](https://blazorfiddle.com/s/rwbchb8m)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor data binding](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1#bind-across-more-than-two-components-3)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @mstortz ... I'll take a look. This is a rather ***very*** old example 👴 that may have gone sideways at some point over the years with updates.

**Comment by guardrex** [comment]
One thing that I just noticed is that this example hasn't had the NRT treatment. I've been refactoring how the Blazor topics handle versioning over the last several months, and I haven't reached this example yet for the NRT updates. I should try to update this topic ***soon*** 🏃. I'll see if I can do that this week. Anyway ... I'll take a look at the example now.

**Comment by guardrex** [comment]
The example is fine. A normal password field wouldn't show the "Not set" value, so the `<input>` being bound to the field (`value="@password"`), not to the parameter, is by design. The example is really about the three bullet list items above the example, which are about binding and callbacks. You're free from there, of course, to make a specific password child component for your own apps have whatever behavior that you want.

**Comment by guardrex** [comment]
... and BTW ... the callback will 💥 without the parameter. You can't have `PasswordChanged` without a paired `Password` param. The value of `Password` is used and is updated. If you drop in some markup to demo that, you can see it in the UI when the `<input>` value is updated. Add this to the `PasswordEntry` component to study the behavior ...

```razor
<p>
    @@Password: @Password
</p>
```
