### ISSUE TITLE
Missing core startup docs - startup56.md is not included in startup.md

### ISSUE THREAD

**Issue by ohads-MSFT** [dotnet/AspNetCore.Docs#29157]
This file: https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup/includes/startup56.md

Should be included here: https://github.com/dotnet/AspNetCore.Docs/blob/d14978d15469f307d03ab0dd228adaf1e2718ce5/aspnetcore/fundamentals/startup.md?plain=1#L77

But for some reason it doesn't work, the content is not included in the final learn.microsoft.com article.

Tagging @Rick-Anderson who added it here: https://github.com/dotnet/AspNetCore.Docs/commit/4569f24d79b75c23353ea8e9164db2610087007d

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 89039](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89039)

**Comment by wadepickett** [comment]
Thanks @ohads-MSFT,
The include is only used for versions previous to .NET 7.0, (when the doc selector on the top left is set for 6.0 or earlier).

The current version of this content is already in the main doc, and the include is just used for previous versions.  I took a look at version 7 - 8  of the doc and the information is there.   Looking at the 6.0 version of the doc the include is used as expected for that version.  

I will go ahead and close this issue, but if you think I might have missed something and it should be re-opened please feel free to re-open.

**Comment by ohads-MSFT** [comment]
@wadepickett after .NET 5, I don't see anything starting from `The Startup class` in the include file and below. Namely all of this is missing: 

> ## The Startup class

ASP.NET Core apps use a `Startup` class, which is named `Startup` by convention. The `Startup` class:

* Optionally includes a <xref:Microsoft.AspNetCore.Hosting.StartupBase.ConfigureServices%2A> method to configure the app's *services*. A service is a reusable component that provides app functionality. Services are *registered* in `ConfigureServices` and consumed across the app via [dependency injection (DI)](xref:fundamentals/dependency-injection) or <xref:Microsoft.AspNetCore.Builder.IApplicationBuilder.ApplicationServices%2A>.
* Includes a <xref:Microsoft.AspNetCore.Hosting.StartupBase.Configure%2A> method to create the app's request processing pipeline.

`ConfigureServices` and `Configure` are called by the ASP.NET Core runtime when the app starts:

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/Startup.cs?name=snippet)]

The preceding sample is for [Razor Pages](xref:razor-pages/index); the MVC version is similar.

The `Startup` class is specified when the app's [host](xref:fundamentals/index#host) is built. The `Startup` class is typically specified by calling the [`WebHostBuilderExtensions.UseStartup`/`<TStartup>`](xref:Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStartup*) method on the host builder:

[!code-csharp[](~/fundamentals/startup/3.0_samples/Program3.cs?name=snippet_Program&highlight=12)]

The host provides services that are available to the `Startup` class constructor. The app adds additional services via `ConfigureServices`. Both the host and app services are available in `Configure` and throughout the app.

Only the following service types can be injected into the `Startup` constructor when using the [Generic Host](xref:fundamentals/host/generic-host) (<xref:Microsoft.Extensions.Hosting.IHostBuilder>):

* <xref:Microsoft.AspNetCore.Hosting.IWebHostEnvironment>
* <xref:Microsoft.Extensions.Hosting.IHostEnvironment>
* <xref:Microsoft.Extensions.Configuration.IConfiguration>

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/StartUp2.cs?name=snippet)]

Most services are not available until the `Configure` method is called.

### Multiple Startup

When the app defines separate `Startup` classes for different environments (for example, `StartupDevelopment`), the appropriate `Startup` class is selected at runtime. The class whose name suffix matches the current environment is prioritized. If the app is run in the Development environment and includes both a `Startup` class and a `StartupDevelopment` class, the `StartupDevelopment` class is used. For more information, see [Use multiple environments](xref:fundamentals/environments#environment-based-startup-class-and-methods).

See [The host](xref:fundamentals/index#host) for more information on the host. For information on handling errors during startup, see [Startup exception handling](xref:fundamentals/error-handling#startup-exception-handling).

## The ConfigureServices method

The <xref:Microsoft.AspNetCore.Hosting.StartupBase.ConfigureServices%2A> method is:

* Optional.
* Called by the host before the `Configure` method to configure the app's services.
* Where [configuration options](xref:fundamentals/configuration/index) are set by convention.

The host may configure some services before `Startup` methods are called. For more information, see [The host](xref:fundamentals/index#host).

For features that require substantial setup, there are `Add{Service}` extension methods on <xref:Microsoft.Extensions.DependencyInjection.IServiceCollection>. For example, **Add**DbContext, **Add**DefaultIdentity, **Add**EntityFrameworkStores, and **Add**RazorPages:

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/StartupIdentity.cs?name=snippet)]

Adding services to the service container makes them available within the app and in the `Configure` method. The services are resolved via [dependency injection](xref:fundamentals/dependency-injection) or from <xref:Microsoft.AspNetCore.Builder.IApplicationBuilder.ApplicationServices%2A>.

## The Configure method

The <xref:Microsoft.AspNetCore.Hosting.StartupBase.Configure%2A> method is used to specify how the app responds to HTTP requests. The request pipeline is configured by adding [middleware](xref:fundamentals/middleware/index) components to an <xref:Microsoft.AspNetCore.Builder.IApplicationBuilder> instance. `IApplicationBuilder` is available to the `Configure` method, but it isn't registered in the service container. Hosting creates an `IApplicationBuilder` and passes it directly to `Configure`.

The [ASP.NET Core templates](/dotnet/core/tools/dotnet-new) configure the pipeline with support for:

* [Developer Exception Page](xref:fundamentals/error-handling#developer-exception-page)
* [Exception handler](xref:fundamentals/error-handling#exception-handler-page)
* [HTTP Strict Transport Security (HSTS)](xref:security/enforcing-ssl#http-strict-transport-security-protocol-hsts)
* [HTTPS redirection](xref:security/enforcing-ssl)
* [Static files](xref:fundamentals/static-files)
* ASP.NET Core [MVC](xref:mvc/overview) and [Razor Pages](xref:razor-pages/index)

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/Startup.cs?name=snippet)]

The preceding sample is for [Razor Pages](xref:razor-pages/index); the MVC version is similar.

Each `Use` extension method adds one or more middleware components to the request pipeline. For instance, <xref:Microsoft.AspNetCore.Builder.StaticFileExtensions.UseStaticFiles%2A> configures [middleware](xref:fundamentals/middleware/index) to serve [static files](xref:fundamentals/static-files).

Each middleware component in the request pipeline is responsible for invoking the next component in the pipeline or short-circuiting the chain, if appropriate.

Additional services, such as `IWebHostEnvironment`, `ILoggerFactory`, or anything defined in `ConfigureServices`, can be specified in the `Configure` method signature. These services are injected if they're available.

For more information on how to use `IApplicationBuilder` and the order of middleware processing, see <xref:fundamentals/middleware/index>.

<a name="convenience-methods"></a>

## Configure services without Startup

To configure services and the request processing pipeline without using a `Startup` class, call `ConfigureServices` and `Configure` convenience methods on the host builder. Multiple calls to `ConfigureServices` append to one another. If multiple `Configure` method calls exist, the last `Configure` call is used.

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/Program1.cs?name=snippet)]

## Extend Startup with startup filters

Use <xref:Microsoft.AspNetCore.Hosting.IStartupFilter>:

* To configure middleware at the beginning or end of an app's [Configure](#the-configure-method) middleware pipeline without an explicit call to `Use{Middleware}`. `IStartupFilter` is used by ASP.NET Core to add defaults to the beginning of the pipeline without having to make the app author explicitly register the default middleware. `IStartupFilter` allows a different component to call `Use{Middleware}` on behalf of the app author.
* To create a pipeline of `Configure` methods. [IStartupFilter.Configure](xref:Microsoft.AspNetCore.Hosting.IStartupFilter.Configure%2A) can set a middleware to run before or after middleware added by libraries.

`IStartupFilter` implements <xref:Microsoft.AspNetCore.Hosting.StartupBase.Configure%2A>, which receives and returns an `Action<IApplicationBuilder>`. An <xref:Microsoft.AspNetCore.Builder.IApplicationBuilder> defines a class to configure an app's request pipeline. For more information, see [Create a middleware pipeline with IApplicationBuilder](xref:fundamentals/middleware/index#create-a-middleware-pipeline-with-iapplicationbuilder).

Each `IStartupFilter` can add one or more middlewares in the request pipeline. The filters are invoked in the order they were added to the service container. Filters may add middleware before or after passing control to the next filter, thus they append to the beginning or end of the app pipeline.

The following example demonstrates how to register a middleware with `IStartupFilter`. The `RequestSetOptionsMiddleware` middleware sets an options value from a query string parameter:

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/RequestSetOptionsMiddleware.cs?name=snippet1)]

The `RequestSetOptionsMiddleware` is configured in the `RequestSetOptionsStartupFilter` class:

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/RequestSetOptionsStartupFilter.cs?name=snippet1&highlight=7)]

The `IStartupFilter` is registered in the service container in <xref:Microsoft.AspNetCore.Hosting.StartupBase.ConfigureServices*>.

[!code-csharp[](~/fundamentals/startup/3.0_samples/StartupFilterSample/Program.cs?name=snippet&highlight=19-20)]

When a query string parameter for `option` is provided, the middleware processes the value assignment before the ASP.NET Core middleware renders the response.

Middleware execution order is set by the order of `IStartupFilter` registrations:

* Multiple `IStartupFilter` implementations may interact with the same objects. If ordering is important, order their `IStartupFilter` service registrations to match the order that their middlewares should run.
* Libraries may add middleware with one or more `IStartupFilter` implementations that run before or after other app middleware registered with `IStartupFilter`. To invoke an `IStartupFilter` middleware before a middleware added by a library's `IStartupFilter`:

  * Position the service registration before the library is added to the service container.
  * To invoke afterward, position the service registration after the library is added.

## Add configuration at startup from an external assembly

An <xref:Microsoft.AspNetCore.Hosting.IHostingStartup> implementation allows adding enhancements to an app at startup from an external assembly outside of the app's `Startup` class. For more information, see <xref:fundamentals/configuration/platform-specific-configuration>.

## Additional resources

* [The host](xref:fundamentals/index#host)
* <xref:fundamentals/environments>
* <xref:fundamentals/middleware/index>
* <xref:fundamentals/logging/index>
* <xref:fundamentals/configuration/index>

:::moniker-end

**Comment by wadepickett** [comment]
@ohads-MSFT, This is correct.  Starting with ASP.NET 6.0, the Startup.cs was removed and Program.cs is where where the startup code goes, such as registering the dependencies of the application.  So you should see the Startup.cs referred to in version 5 or below and you should see Program.cs referred to in version 6 or above.

**Comment by ohads-MSFT** [comment]
@wadepickett at the very least, `Startup.cs` is still supported and working - we are on ASP.NET 7 and using it to this day. As for `Program.cs`, where are the docs for registering dependencies there? I can't find `IServiceCollection` in the current page, which is would presumably be featured somehow - you need to it to call methods like `AddSingleton`...

**Comment by ohads-MSFT** [comment]
@wadepickett interesting, didn't know about this minimal model, but the docs you linked to say in bold: `Apps migrating to 6.0 don't need to use the new minimal hosting mode`. And more explicitly:

> Apps migrating to 6.0 don't need to use the new minimal hosting model
> Using Startup and the [Generic Host](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-7.0) used by the ASP.NET Core 3.1 and 5.0 templates is fully supported.

**Comment by ohads-MSFT** [comment]
@wadepickett also, I'd expect the minimal hosting model docs to be included in the app startup docs - it doesn't make sense that they can only be found on the 5->6 migration page...

**Comment by wadepickett** [comment]
Sounds like you are looking for more a migration perspective.  Getting a better understanding of what went where and changed for startup from 5.0 to 6.0, which was a fairly big change.

This section of the same migration topic noted above does go over what happens with IServiceCollection.  That changed as well:
https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-7.0&tabs=visual-studio#differences-between-the-aspnet-core-5-and-6-hosting-models

**Comment by ohads-MSFT** [comment]
@wadepickett reached out internally but just in case you're not on Teams I'll write here:
1. The old style is still supported, and so should be documented
1. The new style (minimal) is not documented in the current app start docs, and it's very hard to guess where to look for it

If a user new to ASP.NET read the docs today, they wouldn't understand how to add dependencies...

**Comment by wadepickett** [comment]
Thanks.  Adding the author:  @Rick-Anderson 

I am guessing he kept this topic scope to a target audience of new ASP.NET developers, whereas someone moving from the old 5.0 to a newer version would be in more of a migration scope.

**Comment by ohads-MSFT** [comment]
oh, my mistake - please disregard point (2) above (about the new style not being documented).
I think point (1) still stands, namely IMHO at least mention the old style, and at the minimum link to the ASP.NET 5 docs to see how it can be used.

**Comment by Rick-Anderson** [comment]
> I think point (1) still stands, namely IMHO at least mention the old style, and at the minimum link to the ASP.NET 5 docs to see how it can be used.

It's my impression that folks using Startup with the new hosting model know that's unusual and know how to find the old docs. If we get more requests, we'll revisit this assumption. Most customers using new versions of .NET have migrated to the new hosting model.

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.
