### ISSUE TITLE
Is this document about building a Blazor app inside a Windows Form?

### ISSUE THREAD

**Issue by 365ejk** [dotnet/AspNetCore.Docs#29167]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Version Independent ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Content: [Build a Windows Presentation Foundation (WPF) Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/wpf.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @365ejk ... I think you want the WinForms version at ...

https://learn.microsoft.com/aspnet/core/blazor/hybrid/tutorials/windows-forms

**Comment by guardrex** [comment]
I'll close as answered. I can re-open if further discussion is needed.
