### ISSUE TITLE
ICACLS Useage

### ISSUE THREAD

**Issue by jguett** [dotnet/AspNetCore.Docs#29168]
From my experience the line:
ICACLS C:\sites\MyWebApp /grant "IIS AppPool\DefaultAppPool":F

should be corrected to:
ICACLS C:\sites\MyWebApp /grant "IIS AppPool\DefaultAppPool:F"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d172b69-845d-739a-742c-617b9eed04fe
* Version Independent ID: 79d553f1-9112-b61a-0ad0-dfbb11e5071a
* Content: [Advanced configuration](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-7.0#application-pool-identity)
* Content Source: [aspnetcore/host-and-deploy/iis/advanced.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/advanced.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jguett ... I thought only the security identifier was quoted because of the space. The permission mask is tacked on to the end, after the quoted string. When you say, "from my experience," what do you mean? Are you saying that the line as it stands doesn't apply full access permissions? I think we need to confirm it one way or the other before changing this because the product unit approved the command as it appears.

**Comment by jguett** [comment]
I'm not very familiar with ICACLS. I just tried to perform this step on Windows Server 2022.  The command appears to succeed with :F inside the quote but fail with it outside. 

Tangent:
:F seems to result in the target folder having "special permissions".  Looks like the special permissions from :F may be from :F not specifying inheritance.  The option, : :(OI)(CI)F, seems to result full permissions for the target folder.  The /T transverse option might also be relevant for descendent files and folders.

![image](https://user-images.githubusercontent.com/2326966/236308755-e620b8c2-ede7-476a-8e3a-a506fcf18aaa.png)

![image](https://user-images.githubusercontent.com/2326966/236309338-9ab6eac3-1368-40d5-be26-d805d7835cdb.png)

**Comment by guardrex** [comment]
@Rick-Anderson ... I'll work on this one with @jguett ... I have some time for it.

**Comment by guardrex** [comment]
Looks like ...

```console
ICACLS C:\sites\MyWebApp /grant "IIS AppPool\DefaultAppPool:RX"
```

... might do the trick (`RX` = Read & execute).
