### ISSUE TITLE
Razor Pages Tutorial: EF scaffolding tooling changes in VS 2022: Not connecting to Server

### ISSUE THREAD

**Issue by ksweet1nz** [dotnet/AspNetCore.Docs#29183]
I don't know if there have been some changes to Vususal Studio 2022 but when I try to "Add Razor pages using Entity Framework (CRUD)" my dialog box will display a third dropdown to select a server. There are two options: SQL Server or SQL Lite. In the tutorial this is not shown.

Continuing the tutorial using SQL Server, and then testing it after running "Add-Migration InitialCreate" and "Update-Database", I get an error that the server was not found or accessible:

"A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 50 - Local Database Runtime error occurred. Cannot create an automatic instance. See the Windows Application event log for error details.
)"

I can't continue from there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 89140](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89140)

**Comment by wadepickett** [comment]
There has just been an update recently in Visual Studio 2022 for EF tooling, you are correct.  I am actually working on updating this topic for it this sprint, among other changes and for .NET 8 Preview.  Sorry for the bad experience.

A similar tutorial but for MVC that I just updated reflects the new update in the UI for scaffolding: https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-8.0&tabs=visual-studio

I have received the "not found or accessible" error before if I left the app running from previously verifying it and then attempting scaffolding. I'm sure there are many other possibilities such as an incorrect connection string or something up with the server, but leaving the app running is one of the easier mistakes to make.
