### ISSUE TITLE
It works

### ISSUE THREAD

**Issue by rolandwales10** [dotnet/AspNetCore.Docs#29186]
This example works!  I've been looking for a solution for custom validation for hours, and you have it!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3128506-d228-35ca-e34a-183a881acdec
* Version Independent ID: c3128506-d228-35ca-e34a-183a881acdec
* Content: [ASP.NET Core Blazor forms and input components](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/forms-and-input-components.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms-and-input-components.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback, @rolandwales10! 🎸 I'm glad it ✨ ***Just Works!***&trade; ✨😄
