### ISSUE TITLE
HTML class mixup

### ISSUE THREAD

**Issue by dietbrand** [dotnet/AspNetCore.Docs#29181]
[EDIT by guardrex to fix the code blocks. @dietbrand ... Use triple-backticks above and below with a code language behind the first triple-backtick group]

Where it says to change "Areas/Identity/Pages/Account/Manage/Index.cshtml". the classes in the highlighted HTML code are mixed up. it uses 'class="form-control"' where it should be 'class="form-label"'. Example:

```razor
<div class="form-group">
    <label asp-for="Input.Name" class="form-control"></label>
    <input asp-for="Input.Name" class="form-label" />
</div>
```

should be:

```razor
<div class="form-group">
    <label asp-for="Input.Name" class="form-label"></label>
    <input asp-for="Input.Name" class="form-control" />
</div>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, code hasn't been updated in some time. But that shouldn't stop you from understanding the topic.
