### ISSUE TITLE
Add a explanation and sample how to pass parameters to component

### ISSUE THREAD

**Issue by sulmar** [dotnet/AspNetCore.Docs#29228]
[Enter feedback here]
I have proposal to add a explanation and sample how to pass parameters to component.

For example:

1. Create _MyComponent.razor_ file.
~~~ html
<h4>@Message</h4>

@code {

    [Parameter, EditorRequired]
    public required string Message { get; set; }    

}
~~~ 

1. Pass parameters base on dictionary
~~~ csharp
 var dictionary = new Dictionary<string, object>
    {
        { "Message", "Hello World!" }
    };

    var parameters = ParameterView.FromDictionary(dictionary);

    var output = await htmlRenderer.RenderComponentAsync<MyComponent>(parameters);

~~~ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12387a0a-7052-5419-5aae-82879c1d2904
* Version Independent ID: 12387a0a-7052-5419-5aae-82879c1d2904
* Content: [Render Razor components outside of ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-components-outside-of-aspnetcore?view=aspnetcore-8.0)
* Content Source: [aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-components-outside-of-aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Great idea, @sulmar ... I'll schedule this.
