### ISSUE TITLE
Write app using SampleProblemDetailsWriter 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29222]
Need complete app using [Custom IProblemDetailsWriter](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#custom-iproblemdetailswriter)

The code is at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/problem-details-service

This code is needed for [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/29221#discussion_r1189273900)

@sammychinedu2ky  can you do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29221&view=aspnetcore-8.0#customize-problem-details)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 89655](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89655)

**Comment by sammychinedu2ky** [comment]
We've already done this before 😅

**Comment by Rick-Anderson** [comment]
> We've already done this before 😅

Do you know where the code is at?

**Comment by sammychinedu2ky** [comment]
Here is it @Rick-Anderson 
https://github.com/dotnet/AspNetCore.Docs.Samples/pull/25#event-7309770452

**Comment by Rick-Anderson** [comment]
@sammychinedu2ky  right, but we never register [SampleProblemDetailsWriter](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/SampleProblemDetailsWriter.cs) in [Program.cs](https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/Program.cs)

**Comment by sammychinedu2ky** [comment]
> Need complete app using [Custom IProblemDetailsWriter](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#custom-iproblemdetailswriter)
> 
> The code is at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/middleware/problem-details-service
> 
> This code is needed for [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/29221#discussion_r1189273900)
> 
> @sammychinedu2ky can you do this?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
> * Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
> * Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?branch=pr-en-us-29221&view=aspnetcore-8.0#customize-problem-details)
> * Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
> * Product: **aspnet-core**
> * Technology: **aspnetcore-fundamentals**
> * GitHub Login: @tdykstra
> * Microsoft Alias: **riande**
> 
> [Associated WorkItem - 89655](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89655)

So I should edit this code write?

**Comment by Rick-Anderson** [comment]
> So I should edit this code write?

Yup, just add a `#define ` and new snippet tag around it. Above that in the comments list instructions to test it.

**Comment by Rick-Anderson** [comment]
Update the following

https://github.com/dotnet/AspNetCore.Docs.Samples/blob/main/fundamentals/middleware/problem-details-service/Program.cs
