### ISSUE TITLE
Is this really for .net7 or is it me?

### ISSUE THREAD

**Issue by althepal78** [dotnet/AspNetCore.Docs#29230]
Can you actually do this for .net7 because that startup configure is no longer a file or am I a missing something. Like if it is to be with the actual published files whey did you have me publish them first and not add this shit. This page makes it so confusing. Like our we configuring Program.cs because there is not Startup.Configure or am I missing something

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0&tabs=linux-rhel)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 89920](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89920)

**Comment by Rick-Anderson** [comment]
```
using System.Net;

var builder = WebApplication.CreateBuilder(args);

// Configure forwarded headers
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.KnownProxies.Add(IPAddress.Parse("10.0.0.100"));
});

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

I'll have a PR for this in an hour.
