### ISSUE TITLE
Migrate IIS trouble shooting docs - Tom

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29234]
migrating [troubleshooting articles](https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/new-features-introduced-in-iis-10-1709) that are currently in the IIS product group site into the [troubleshooting site](https://learn.microsoft.com/en-us/troubleshoot/) 

Assist @aartig13 in the effort

Related #29235

---
[Associated WorkItem - 89923](https://dev.azure.com/msft-skilling/Content/_workitems/edit/89923)

**Comment by tdykstra** [comment]
Redirects were added in https://github.com/MicrosoftDocs/iis-docs/pull/998
