### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by senglory** [dotnet/AspNetCore.Docs#29241]
[Enter feedback here]

%PROGRAMFILES%\Mozilla Firefox\distribution\policies.json - there's no such file and 'distribution' folder at least for 64bit Firefox from version 112

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-7.0&tabs=visual-studio%2Clinux-ubuntu#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
The directions say to create a policies.json file, they don't say that one is already present. You would have to create the distribution folder to put the file in as well.

**Comment by senglory** [comment]
Ok, but if the specified folder %PROGRAMFILES%\Mozilla Firefox\distribution\ does not exist, does it mean that I should create the subfolder "\distribution" explicitly? I was a bit confused because the original Firefox installer didn't create this folder.

**Comment by tdykstra** [comment]
Yes, create the distribution folder.

**Comment by postmeback** [comment]
Updated the text 

PR: https://github.com/dotnet/AspNetCore.Docs/pull/29264

Please review

**Comment by postmeback** [comment]
As the above mentioned pull request fixes this issue, this issue can be closed.
