### ISSUE TITLE
You're kind of missing one important part

### ISSUE THREAD

**Issue by Rhywden** [dotnet/AspNetCore.Docs#29243]
So, you explain how to do authentication with Blazor Server. You're erxplaining Blazor WASM.

You're completely forgetting about Blazor WASM Hosted. I.e. the one with the included backend.

First of all, it's great that this particular version includes a hard reference to Identity Server. Which then completely and utterly fails to provide a working example or guidance on how to make it work. Case in point: This here is a freshly created Blazor WASM Hosted with Individual Accounts. I just started it up:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/84586/b78b7712-d0ee-42f1-8bed-b878a979750f)

So, what now?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 985b834f-534a-aba6-80a0-d8845adbfc25
* Version Independent ID: d2b5a556-82a4-e939-be68-2357a3d4408f
* Content: [Secure an ASP.NET Core Blazor WebAssembly standalone app with the Authentication library](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/standalone-with-authentication-library.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The hosted WASM with Duende IdS is here ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-7.0&tabs=visual-studio
