### ISSUE TITLE
I cant scaffold

### ISSUE THREAD

**Issue by rolandnii** [dotnet/AspNetCore.Docs#29258]
This is the error I am getting using vscode for ubuntu

There was an error creating a DbContext :(15,53): error CS0053: Inconsistent accessibility: property type 'DbSet<Movie>' is less accessible than property 'RazorPagesMovieContext.Movie'
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Part 2, add a model](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
@rolandnii,  Thanks for letting us know your experience.  We appreciate the heads up.

Just a side note: The version of the tutorial you have reported on is for .NET 6.

It sounds like a mismatch between private and public for a property and class.

Given the error, I am assuming `Data/RazorPagesMovieContext.cs` was created.  Does `Data/RazorPagesMovieContext.cs` look any different in your project than this following example, as shown in the tutorial?

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using RazorPagesMovie.Models;

namespace RazorPagesMovie.Data
{
    public class RazorPagesMovieContext : DbContext
    {
        public RazorPagesMovieContext (DbContextOptions<RazorPagesMovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorPagesMovie.Models.Movie>? Movie { get; set; }
    }
}
```

I will retest version 6, which is what you are using, with the latest related packages and again with the packages available at the time for version 6.  The tooling changed recently for scaffolding, there could be something up there.  I am currently working through all tutorials and code samples in this series for version 8, I'll check this too.

**Comment by wadepickett** [comment]
Closing, was unable to recreate.  More info needed, see questions above.
