### ISSUE TITLE
More Info on Configuring Existing SPA to Use Blazor Custom Elements

### ISSUE THREAD

**Issue by epetersoni** [dotnet/AspNetCore.Docs#29253]
I would find it useful if this page included more information about how to use registered custom elements from an existing app that is using a different framework (e.g. Angular or React).

For Blazor Server apps, I've been using the VS templates for Angular or React with an ASP.NET Core backend. After creating and registering the custom elements, I've also needed to:
1) Modify `setupProxy.js` to add proxy middleware for `"/_framework"`, `"/_blazor"`, and `"/_content"`
1) Update the client app `index.html` to include the `_content/Microsoft.AspNetCore.Components.CustomElements/Microsoft.AspNetCore.Components.CustomElements.lib.module.js` and `_framework/blazor.server.js` scripts
1) Also add any other CSS or scripts required by the Blazor component that is registered as a custom element
1) For Angular, update `app.module.ts` to register `CUSTOM_ELEMENTS_SCHEMA` to avoid build errors when using custom elements
1) I had to set `LongPolling` as the transport type, even with `ws: true` in the proxy config. I've seen some potential fixes for this but haven't gotten one to work yet.

For Blazor WASM apps, I haven't been able to get a simple Angular app to show a Blazor custom element. Here's what I've done:

1) Created and published a simple Blazor WASM app that registers a component as a custom element
1) Created a project using the VS Standalone Angular template and added a reference to the custom element
1) Copied the published Blazor files over to the root of the Angular project
1) Added `"_content/Microsoft.AspNetCore.Components.CustomElements/Microsoft.AspNetCore.Components.CustomElements.lib.module.js"` and `"_framework/blazor.webassembly.js"` to the `scripts` collection in `angular.json`
1) At this point I see these console errors when running the Angular app:
   * Failed to load resource: the server responded with a status of 404 (Not Found) `:4200/_framework/blazor.boot.json:1`
   * SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON `_framework\blazor.webassembly.js:1`

I'm assuming there's more proxy / routing configuration that I need to set up, but as someone who has never used Angular I'm not sure how to do so.

Examples of how to re-configure existing apps to use Blazor Custom Elements would be really useful. I managed to piece together something that works with Blazor Server elements from various posts around the web, but I haven't found a working example or much info on doing so with Blazor WASM elements. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 444b03b4-f910-656a-642c-6c9064d6ce28
* Version Independent ID: 444b03b4-f910-656a-642c-6c9064d6ce28
* Content: [Use Razor components in JavaScript apps and SPA frameworks](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/js-spa-frameworks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/js-spa-frameworks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @epetersoni. I'm more of an MS .NET 🐈 than an Angular/React 🐈, so we'll need to get some help from the product unit.

Ping @mkArtakMSFT for triage.

**Comment by guardrex** [comment]
@epetersoni ... I received word that Mackinnon of the product unit will be along within a few weeks to take a look. The delay is likely due to all of the work going on for the upcoming release of .NET 8. Everyone is 🏃🏃🏃😅 right now.

**Comment by epetersoni** [comment]
@guardrex This is becoming a more urgent issue for us. We need to prove that Blazor Custom Elements will allow us to reuse Blazor components in existing SPA based on other web frameworks, and determine the implications of doing so (in terms of performance, amount of work involved, etc.). If we can't, we may need to move away from Blazor for many projects. Now that .NET 8 is close to release, is there more time to look into this?

**Comment by guardrex** [comment]
I'll send an email to Artak. This will need product unit assistance to resolve.

**Comment by mkArtakMSFT** [comment]
@javiercn can you please help here? Thanks!

**Comment by javiercn** [comment]
Here is a sample that shows how to do it with Blazor Server and WebAssembly and Angular https://github.com/javiercn/CustomElementsBlazorSample see the branches `blazor-server` and `blazor-wasm`
