### ISSUE TITLE
Anchor not working

### ISSUE THREAD

**Issue by abarberenaCPDS** [dotnet/AspNetCore.Docs#29260]
Hello guys 👋 @tdykstra, @Tratcher, @ardalis, @halter73,

Just a minor thing, but wanted to make you aware, when selecting **_macOS_** and **_Linux_**, the **Kestrel vs. HTTP.sys** hyperlink does not take you to the content.

One must click the Windows tab to display the content.  

## 👀 
> <img width="759" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/43246964/3031ffa4-21ee-4284-b978-ca2e4e34465b">

Thanks,

abe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-3.1&tabs=linux#korh)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Hello guys 👋 @tdykstra, @Tratcher, @ardalis, @halter73,

Please don't list contributors next time.
