### ISSUE TITLE
Need to add `-a arm64` if on Apple Silicon

### ISSUE THREAD

**Issue by aglee** [dotnet/AspNetCore.Docs#29262]
There is an instruction to run this command: `dotnet tool install -g Microsoft.Web.LibraryManager.Cli`.

The resulting installation of `libman` was Intel.  I was on an M1 machine without Rosetta installed, so `libman` failed.  I found that adding `-a arm64` fixed this: `dotnet tool install -a arm64 -g Microsoft.Web.LibraryManager.Cli`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 97030](https://dev.azure.com/msft-skilling/Content/_workitems/edit/97030)

**Comment by guardrex** [comment]
Thanks, @aglee.

@Rick-Anderson @wadepickett @tdykstra ... We can cross-link to ...

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options

... but there's no mention of explicitly naming an architecture in the following articles ...

* https://learn.microsoft.com/aspnet/core/client-side/libman/libman-cli#installation
* https://learn.microsoft.com/dotnet/core/tools/global-tools#install-a-global-tool
* https://learn.microsoft.com/dotnet/core/tools/global-tools-how-to-use

Perhaps, the article in our doc set should have *something* on this. If so, there are 26 tool installs in 54 other files around the repo that could link to it.

**Comment by wadepickett** [comment]
I could create an include that as a note, something like the note below wherever we use `dotnet tool install`.   

Example:

In the integrated terminal, run the following commands to install LibMan after uninstalling any previous version, if one exists.

```dotnetcli
dotnet tool uninstall -g Microsoft.Web.LibraryManager.Cli
dotnet tool install -g Microsoft.Web.LibraryManager.Cli
```
> [!NOTE]
> By default the architecture of the .NET binaries to install represent the currently running OS architecture. To specify an different OS architecture, see [dotnet-install options](dotnet/core/tools/dotnet-install-script.md#options).

**Comment by guardrex** [comment]
That's good because this goes beyond just this package.

**Comment by tdykstra** [comment]
Good idea, but note that your sample links to the wrong article -- should be dotnet tool install, not dotnet-install-scripts.

Also, the dotnet tool install article needs -a/--arch added to its options sections.

Tweaking the proposed text slightly:
 
> [!NOTE]
> By default the architecture of the .NET binaries to install represents the currently running OS architecture. To specify a different OS architecture, see [dotnet tool install, --arch option](dotnet/core/tools/dotnet-tool-install#options).

**Comment by wadepickett** [comment]
This issue was fixed with the following PR work on both the dotnet/docs and aspnetcore.docs repos:
- dotnet/docs#36345
- dotnet/docs#36395
- #29923
