### ISSUE TITLE
Reference to "Run" menu should be "Start"

### ISSUE THREAD

**Issue by aglee** [dotnet/AspNetCore.Docs#29261]
The tutorial refers to a Run > Start Without Debugging menu item.  On my Mac version of VS (17.5.4 build 8) there's no Run menu.  It's Debug > Start Without Debugging.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-7.0&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by guardrex** [comment]
Thanks, @aglee. It's the same on Windows. I'll patch that right now.
