### ISSUE TITLE
Async lamdba example, bad practice ?

### ISSUE THREAD

**Issue by dust63** [dotnet/AspNetCore.Docs#29270]
[Enter feedback here]
```
app.MapGet("/todos", async (TodoDb db) => await db.Todos.ToListAsync())
    .WithOpenApi(operation => new(operation)
    {
        Tags = new List<OpenApiTag> { new() { Name = "Todos" } }
    });
```

It is a good practice to use an async lambda:  `async (TodoDb db) => `.

I can see many article that explain why to avoid this...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b18acd86-50e3-2316-27be-27156651e5a8
* Version Independent ID: b18acd86-50e3-2316-27be-27156651e5a8
* Content: [How to use OpenAPI in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes.
