### ISSUE TITLE
Unable to get HttpContext.Session from View in MVC or Razor Page

### ISSUE THREAD

**Issue by doggy8088** [dotnet/AspNetCore.Docs#29273]
The code sample of this page shows you can use `@HttpContext.Session` to access Session object which is wrong. The right way to get session in the View should be `@Context.Session`. See here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0&WT.mc_id=DT-MVP-4015686#access-httpcontext-from-a-razor-view-in-mvc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-7.0&WT.mc_id=DT-MVP-4015686#session-state)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
> See here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0&WT.mc_id=DT-MVP-4015686#access-httpcontext-from-a-razor-view-in-mvc

That article is about MVC projects, while this code sample with `@HttpContext` is a Razor Pages project. `@Context` works in an MVC app, not in a Razor Pages app.
