### ISSUE TITLE
[JS Interop] Clarification on AOT / JIT Needed

### ISSUE THREAD

**Issue by HazyFish** [dotnet/AspNetCore.Docs#29329]
Can we add details about whether the WebAssembly module built is using AOT or JIT on the following documentations, since it's critical for performance considerations? I would like to use .NET in my React project for computation intensive algorithms if it's AOT compiled, but I would use TypeScript if a .NET runtime has to be shipped to browser via network.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efff6954-a035-d1da-5975-af04ff7c05ed
* Version Independent ID: efff6954-a035-d1da-5975-af04ff7c05ed
* Content: [Run .NET from JavaScript](https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/dotnet-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @pavelsavara
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ping @pavelsavara to indicate if that's the case or not and what to say about it if so.

**Comment by pavelsavara** [comment]
The Blazor wasm is running on Mono runtime, which has interpreter and and AOT options, but not JIT.
When you use wasm-tools workload, you could AOT compile your application together with the Mono runtime.
The runtime will be always part of the download. Usually it takes few MB with non trivial application.
So if you have small utility which is easy to write in TS, it would be most likely better choice.

This is not really interop question and I don't know where this fits. Maybe it's a topic for next article https://github.com/dotnet/runtime/issues/80098

I added comment there and we could close this one.
