### ISSUE TITLE
Add note: UsePathBase() duplicates route paths

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29324]
See https://github.com/dotnet/aspnetcore/issues/47723

@QuantumToasted would you be able to add a note for this and PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

cc @abrasat if you're interested in documenting this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?branch=pr-en-us-29322&view=aspnetcore-7.0#optional-route-parameter-order)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by QuantumToasted** [comment]
Hi, I appreciate the offer for a documentation/notes PR, but I'm terribly unfamiliar with best practices when it comes to editing documentation pages such as these and am a little out of my comfort zone 😓  - not even sure where to begin with where the best place to put it would be, let alone what I would put there.

**Comment by Rick-Anderson** [comment]
See https://github.com/dotnet/aspnetcore/issues/48370#issuecomment-1558412786
