### ISSUE TITLE
Package deprecation?

### ISSUE THREAD

**Issue by broomfn** [dotnet/AspNetCore.Docs#29344]
Hi, I'm seeking clarity as to whether this documentation is still accurate give the packages status as now deprecated?

https://www.nuget.org/packages/Microsoft.AspNetCore.StaticFiles

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @broomfn ... Yes, it's still accurate. The package is depreciated for standalone use (i.e., no need to add a package reference to a project for this API), but the namespace/assembly is still valid with full support. The API has been rolled into the shared framework. For more information, see https://learn.microsoft.com/aspnet/core/fundamentals/metapackage-app. If you want to see the assemblies that are rolled into it, check out https://github.com/dotnet/aspnetcore/blob/main/docs/SharedFramework.md ... and then follow the link to the local shared framework assemblies ... https://github.com/dotnet/aspnetcore/blob/main/eng/SharedFramework.Local.props.

**Comment by broomfn** [comment]
Right, I think I was using it in a netstandard library, I assume I'll need to target .net 6 (or later) now, or can I include Microsoft.AspNetCore.App into netstandard?

**Comment by guardrex** [comment]
> target .net 6 (or later) now

Yes ... for currently supported frameworks, .NET 6 or .NET 7 ... or .NET 8 in November when it reaches RTM. After that, you should be fine. Static assets are supported from libs as long as the app adding the lib enables the middleware (`UseStaticFiles`), which the vast majority of lib-consuming apps will have ... and certainly any apps that you control in-house.

**Comment by broomfn** [comment]
Thanks again, just in case it helps, it was really the FileExtensionContentTypeProvider class we were using to resolve MIME types, it's a handy utility class that has potential uses in many different places/scenarios IMHO.

**Comment by guardrex** [comment]
Sure, but you can just take that from the API and drop it into your lib ... or another lib/package that you can consume widely. Plus, I'm sure that there's a gazillion community packages that can take care of it. I don't think the product unit will split it out, and it's true ... they don't currently have that type of data in any form that you can readily use it in this case. If you want to ask them tho, open a feature request for the product unit and suggest that they split it out in some way ...

https://github.com/dotnet/aspnetcore/issues

**Comment by broomfn** [comment]
Noted, thanks for all your help :-)
