### ISSUE TITLE
Broken anchor link in Validation

### ISSUE THREAD

**Issue by matteocontrini** [dotnet/AspNetCore.Docs#29367]
The link in the sentence `See [Required] attribute for details about this attribute's behavior.`  in the model validation docs page is broken.

Current:

`#non-nullable-reference-types-and-the-required-attribute`

Should be:

`#non-nullable-reference-types-and-required-attribute`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-7.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@matteocontrini Thanks for reporting that!
