### ISSUE TITLE
.NET 8: MapIdentityApi<TUser>() 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29363]
See [`MapIdentityApi<TUser>() `](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-4/#identity-api-endpoints)

Related: #30066

The main goal of the MapIdentityApi is to make it easy for developers to use ASP.NET Core Identity for authentication in JavaScript-based single page apps (SPA) or **_Blazor apps_**. 

~Since it's for Blazor app, assigning to @guardrex. If you don't want this, let me know.~

---
[Associated WorkItem - 159474](https://dev.azure.com/msft-skilling/Content/_workitems/edit/159474)

**Comment by danroth27** [comment]
@guardrex @JeremyLikness Let's track the doc work for using Blazor with the new Identity endpoints separately. This issue should track generically documenting the Identity endpoints so they can be used from any client.

**Comment by guardrex** [comment]
I've opened a Blazor-specific issue, and I'll keep an :eye: on this and the tokens issue.

https://github.com/dotnet/AspNetCore.Docs/issues/30394

**Comment by Rick-Anderson** [comment]
@JeremyLikness  can you provide a draft for this?

**Comment by JeremyLikness** [comment]
Let me sync with @halter73 and make sure we're not duplicating effort. Is this a conceptual document about the API?
