### ISSUE TITLE
Whether MVC is design pattern or architectural pattern

### ISSUE THREAD

**Issue by shreedharpatil** [dotnet/AspNetCore.Docs#29375]
[Enter feedback here]

Hello,

Referring to the page https://learn.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-7.0, in the beginning line, it mentions MVC as design pattern and immediately in the first section(MVC pattern) it mentions as architectural pattern which is bit confusing. I believe design pattern and architectural patterns are different. Does MVC fall under both category and can use them interchangeably OR documentation is incorrect and needs updating?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9b26c2a-d481-043c-e37b-cbe3ad427d41
* Version Independent ID: d7d85488-c055-7aea-0664-2e97bc937a04
* Content: [Overview of ASP.NET Core MVC](https://learn.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-7.0)
* Content Source: [aspnetcore/mvc/overview.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/overview.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Topic of debate
