### ISSUE TITLE
Where is IAuthenticationService used in AuthenticationMiddleware

### ISSUE THREAD

**Issue by propounder** [dotnet/AspNetCore.Docs#29378]
I couldn't find any use of IAuthenticationService interface in AuthenticationMiddleware.cs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 393b3379-6061-50a4-0975-b3d1d82b660b
* Version Independent ID: 48e4e204-ea22-c225-0cbc-0d811bdb90ed
* Content: [Overview of ASP.NET Core Authentication](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sorry for the delay ... I got pulled off on something else. IIRC, the the `AuthenticateAsync` is from `IAuthenticationService`'s implementation.

I noticed from the API that this is mentioned in passing for `GetDefaultAuthenticateSchemeAsync` in the middleware ...

> Returns the scheme that will be used by default for `AuthenticateAsync(HttpContext, String)`.

... where `AuthenticateAsync` specifically denotes `IAuthenticationService.AuthenicateAsync`.

Cross-refs:

* https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.iauthenticationschemeprovider.getdefaultauthenticateschemeasync
* https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.iauthenticationservice.authenticateasync

I'll close, but @mjrousos will see this and can revise my remarks if I'm incorrect.
