### ISSUE TITLE
There is an error in blazor migration code snippet.

### ISSUE THREAD

**Issue by umunu** [dotnet/AspNetCore.Docs#29390]
In the following code snippet there is an error. `NavigationManager.NavigateToLogin` seems to be a static method from NavigationManager. But it actually is an extension method of `NavigationManager`. It should be renamed from `NavigationManager.NavigateToLogin` to `Navigation.NavigateToLogin` to use the `@inject NavigationManager Navigation` object.
```
@inject NavigationManager Navigation
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
@using Microsoft.Extensions.Options

@inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> OptionsSnapshot
@code {
    protected override void OnInitialized()
    {
        NavigationManager.NavigateToLogin(OptionsSnapshot.Get(Options.DefaultName).AuthenticationPaths.LogInPath);
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, that's correct, @umunu. Thanks for reporting it. I'll fix that right now. 🚑🚓🚒
