### ISSUE TITLE
Problems encountered in Android development

### ISSUE THREAD

**Issue by impPDX** [dotnet/AspNetCore.Docs#29398]
An error occurred when using signalr in Android development. My configuration is as follows:
What's the reason for this? Do you know the big shots
![image](https://github.com/dotnet/AspNetCore.Docs/assets/50691694/88ccd10f-1e82-4491-9ccc-cab9b05b762e)

![image](https://github.com/dotnet/AspNetCore.Docs/assets/50691694/d8186a18-389d-4597-ad28-3b2e80810baf)

**Comment by guardrex** [comment]
Hello @impPDX ... Please open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

... ***BUT*** note that they're probably going to need more to go on than this. They often ask for a minimal repro project on GitHub that demonstrates the error; and if you can track down and show the code throwing the exception, that's helpful to show in your issue comment.
