### ISSUE TITLE
MIA API in Minimal APIs security article

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#29391]
Safia ... I was working on something else, and my build report flagged an XREF here ...

> \<xref:Microsoft.Identity.Web.PolicyBuilderExtensions.RequireScope%2A>

... and I can't find that in the API browser.

It's in this section ...

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0#configuring-authorization-policies-in-minimal-apps

I'm going to change the XREF to code for now to unblock [the PR](https://github.com/dotnet/AspNetCore.Docs/pull/29384) that I'm working on ...

```diff
- <xref:Microsoft.Identity.Web.PolicyBuilderExtensions.RequireScope%2A>
+`Microsoft.Identity.Web.PolicyBuilderExtensions.RequireScope`
```

If you want to tell me how to fix this section, I'll take care of it. That is to say, fix it ***IF*** this is a real problem in the text/example code and not a ghost due to some temporary API docs problem. If you know that there's nothing really wrong with the existing text/code, I'll just circle back around later and put the XREF back into place after they fix whatever the problem is with the API docs system.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Version Independent ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Content: [Authentication and authorization in minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @captainsafia
* Microsoft Alias: **safia**

**Comment by captainsafia** [comment]
@guardrex I think the example here is incorrect and I suspect it came across from copy-pasting code samples from docs that referenced IdentityServer. We don't have a `RequireScope` API in the framework.

We can update the sample to use the `RequireClaim` API like so:

```csharp
builder.Services.AddAuthorizationBuilder()
  .AddPolicy("admin_greetings", policy =>
        policy
            .RequireRole("admin")
            .RequireClaim("scope", "greetings_api"));
```

**Comment by guardrex** [comment]
Thanks @captainsafia ... I'll take care of it by EOD.
