### ISSUE TITLE
Tutorial doesnt work for me

### ISSUE THREAD

**Issue by moerwald** [dotnet/AspNetCore.Docs#29408]
I'm always seeing the signalr error message in the browser console. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @moerwald for letting us know. Looks like you were working through the Visual Studio on Windows version for .NET 8 Preview? I will retest the tutorial, something may have changed.  Could you be more specific about the error you are experiencing?

**Comment by wadepickett** [comment]
Closing for lack of any information.
