### ISSUE TITLE
Create a web API: dotnet-aspnet-codegenerator: VS Code on macOS

### ISSUE THREAD

**Issue by mahdiHaji70** [dotnet/AspNetCore.Docs#29409]
hi
thanks for your helpful document
when i use this command : "dotnet-aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers"
i got an error that says: command not found: dotnet-aspnet-codegenerator

i can solve it with the correction like this: dotnet aspnet-codegenerator controller -name TodoItemsController -async -api -m TodoItem -dc TodoContext -outDir Controllers

if that was my problem and the recommended code in page is correct then every thing is ok
but if its wrong please correct it. 
i will be thankful if report me the result. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 97036](https://dev.azure.com/msft-skilling/Content/_workitems/edit/97036)

**Comment by wadepickett** [comment]
Related to issue #16997 dotnet [SPACE] aspnet-codegenerator vs dotnet-aspnet-codegenerator and PR [28342](https://github.com/dotnet/AspNetCore.Docs/pull/28342/files).

I will take a fresh look at it.  
@mahdiHaji70, the doc issue was created while you were on the Visual Studio for Windows tab of instruction, but you must have been working through either VS Code or VS for macOS.   Which IDE and environment were you on and if VS for macOS, which version?  Thanks so much.

**Comment by mahdiHaji70** [comment]
yes, i use vs code for macos and its version is 1.78.2(universal)

**Comment by wadepickett** [comment]
@mahdiHaji70, thanks!!!

**Comment by wadepickett** [comment]
dotnet SPACE is preferred since it has better error handling.  However, if running Windows 10, the terminal needs to be restarted once that global tool is installed or dotnet SPACE aspnet-codegenerator will not be found, or we can follow with a line to run an update on the tool.  I will add a line to update on the tool: dotnet tool update -g Dotnet-aspnet-codegenerator, and change the scaffolding line to use the space:   dotnet aspnet-codegenerator controller...
