### ISSUE TITLE
Incorrect Example Code

### ISSUE THREAD

**Issue by Kevin-Andrew** [dotnet/AspNetCore.Docs#29413]
On this page, and other versions of it, like the ASP.NET Core 7.0, you have a couple of incorrect lines of example code. Namely,
`User = await JS.InvokeAsync<Profile>("sessionStorage.getState", "resumeSavingProfile");`
and
`await JS.InvokeVoidAsync("sessionStorage.setState", "resumeSavingProfile", User);`
(Note, on the web page, those lines of code have a line break in them, so be warned if you try to copy mine and search the page.)

The part that is incorrect about those lines of code are the `getState` and `setState`. For the JavaScript `sessionStorage` object, there are no such methods. Instead, they should be `getItem` and `setItem`, respectively. See [getItem()](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem) and [setItem()](https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem).

Further down on this page, you do have more code example where this is done correctly. For example,
`await JS.InvokeVoidAsync("sessionStorage.setItem", AuthenticationState.Id, State.GetStateForLocalStorage());`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0#save-app-state-before-an-authentication-operation)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It turns out that the original FNs are probably correct. Those FNs that Javier named, `getState`/`setState` look to be custom FNs that he didn't make available with his original content dump at ...

https://gist.github.com/javiercn/85a6d4ce46a78239ccb427baad3a66da#handling-token-request-errors

I'm investigating further now. I'll be working the updates on the new issue at https://github.com/dotnet/AspNetCore.Docs/issues/31534.

**Comment by Kevin-Andrew** [comment]
Sorry, Luke, I still don't think that's the case.

If 
![image](https://github.com/dotnet/AspNetCore.Docs/assets/22459191/a14a60e6-b715-49e0-8ef4-e550f941048b)
were an actual valid method, then doing an Internet search for it would return a bunch of results, however, it only returns 2. One of which appears to be a copy of the first.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/22459191/b79a2cff-d256-4b2d-a6c2-256ebe2aba70)

Compare that to the actual, correct function name, `sessionStorage.getItem`
![image](https://github.com/dotnet/AspNetCore.Docs/assets/22459191/0fcd8242-3c61-4102-b370-44845568666d)

Could it be a custom method, sure, anything is possible. But, as Javier said in [the comment](https://github.com/dotnet/aspnetcore/issues/53465#issuecomment-1898908605), it was a bug in the user's code, because they were not passing a string. And then that person said they were just copying the example.

That means it is another error in the example that I failed to point out originally, because I was never trying to save an object, just strings, so I never paid attention to that part of the code example.

Unfortunately, this means that the problem is a bit bigger than just an incorrect method name. There will need to be a few more lines of code or something added to the example. The code will need to serialize and deserialize the `User` object to and from a string, when setting it or getting it from the `sessionStorage`.

(Thanks for the thorough follow up. Good memory.)

**Comment by guardrex** [comment]
Ok ... so that is the answer ... he made ***TWO*** mistakes, which is very extremely unlike him to do. Not only were the method names wrong, but the arguments were incorrect as well. He's usually like 99.5% correct about everything he says and does. That's why I thought that he might have had some custom FNs doing some custom serialization processing. I'll work on the code on the other issue as soon as I can get free ⛰️⛏️😅.

**Comment by Kevin-Andrew** [comment]
Awesome.

It helps to have a team and people like you too.

Thanks.
