### ISSUE TITLE
Difference between UseHealthChecks and MapHealthChecks

### ISSUE THREAD

**Issue by ngbrown** [dotnet/AspNetCore.Docs#29421]
This **Health checks in ASP.NET Core** page doesn't mention `UseHealthChecks` at all, and the few places in this repository that contain it, don't explain the difference between `UseHealthChecks` and `MapHealthChecks` very well. The [2.2 to 3.0 migration page](https://github.com/dotnet/AspNetCore.Docs/blob/57d21ee8b0701947b2d97dd0fa283a31c4a78e4d/aspnetcore/migration/22-to-30.md?plain=1#L1020) mentions benefits of authentication, but that wouldn't apply to the Kubernetes use that this page is using as an example.

Because this page mentions Kubernetes readiness and liveness probe, and these endpoints are called a lot, I think this distinction would especially helpful. I've seen it mention that one might want to use one vs. the other when using logging middleware of requests.

I view one of the advantages of `UseHealthChecks` is that it will terminate the pipeline if the path matches so it can be placed before the logging middleware and the logs will be skipped.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 97769](https://dev.azure.com/msft-skilling/Content/_workitems/edit/97769)

**Comment by cremor** [comment]
> I view one of the advantages of `UseHealthChecks` is that it will terminate the pipeline if the path matches so it can be placed before the logging middleware and the logs will be skipped.

I agree. But the difference is confusing. See https://github.com/dotnet/AspNetCore.Docs/pull/29439#discussion_r1221227616
