### ISSUE TITLE
Add instructions for switching to the directory that includes the newly created ADB2C tenant

### ISSUE THREAD

**Issue by martillodecampo** [dotnet/AspNetCore.Docs#29423]
This is an excellent tutorial! In the "Register a server API app in Azure" section, I think it would be helpful to add a first step that explains that you need to switch to the directory that contains the newly-created ADB2C tenant (similar to [this step in the "Create user flows and custom policies in Azure Active Directory B2C" tutorial.](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow#:~:text=Make%20sure%20you%27re%20using%20the%20directory%20that%20contains%20your%20Azure%20AD%20B2C%20tenant.%20Select%20the%20Directories%20%2B%20subscriptions%20icon%20in%20the%20portal%20toolbar))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 520b9821-ecef-20af-a601-ea36c4297d88
* Version Independent ID: da9c8ac9-4d7a-4b40-56a2-a4bfe7083567
* Content: [Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the feedback, @martillodecampo. I'll take a look on Monday morning.
