### ISSUE TITLE
The RequestAborted token should be passed to async APIs like Task.Delay

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#29436]
The current sample code looks like this:
```
app.MapGet("/", async (HttpContext context) => {
    await Task.Delay(TimeSpan.FromSeconds(2));

    if (context.RequestAborted.IsCancellationRequested) {
        return Results.Content("Timeout!", "text/plain");
    }

    return Results.Content("No timeout!", "text/plain");
}).WithRequestTimeout(TimeSpan.FromSeconds(1));
```

However this continues to wait past the timeout period. The Request aborted token should be passed to Task.Delay so it can be ended without waiting the full time. Generating a timeout response can be done by catching the exception locally, or using WriteTimeoutResponse when a policy is defined.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 449a4031-c1d1-5fbe-8e8f-b0e931a5b7ab
* Version Independent ID: 449a4031-c1d1-5fbe-8e8f-b0e931a5b7ab
* Content: [Request timeouts middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/timeouts?view=aspnetcore-8.0#configure-one-endpoint-or-page)
* Content Source: [aspnetcore/performance/timeouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/timeouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
The article's intro says

> When a timeout limit is hit, a CancellationToken in HttpContext.RequestAborted has IsCancellationRequested set to true. The request is not aborted automatically. It's up to the app to check RequestAborted and decide how to handle the timeout.

It looks likes "The request is not aborted automatically." is no longer true when we pass the cancellation token in to the async API.  I'm seeing a 504 get returned automatically. Is it still true in some scenarios, and if so when does it still apply?

**Comment by Tratcher** [comment]
"The request is not aborted automatically." can be clarified to "Abort() is not automatically called on the request, the application may still produce a success or failure response." The 504 is default behavior if the app doesn't handle the exception and produce a response.
