### ISSUE TITLE
FileResolver class constructor name

### ISSUE THREAD

**Issue by daniele-bortoluz** [dotnet/AspNetCore.Docs#29466]
In the FileResolverClass the name of the constructor should be FileResolver instead of FileResolver

```
    public FileResolver(Uri address, int defaultPort, ILoggerFactory loggerFactory)
        : base(loggerFactory)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac62acc-1270-cc98-024e-659b3a80f4ca
* Version Independent ID: d6f25885-6c43-0d2c-96e2-3b47a4fd7bd7
* Content: [gRPC client-side load balancing](https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/loadbalancing.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/loadbalancing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by JamesNK** [comment]
It is FileResolver....

**Comment by wadepickett** [comment]
Assigning to James since he already has the pr in.
