### ISSUE TITLE
Identity guidance

### ISSUE THREAD

**Issue by JeremyLikness** [dotnet/AspNetCore.Docs#29462]
A new document that provides clear guidance on how to determine the right auth solution. Based on requirements, will explain the trade-offs associated with deciding between self hosted (ASP.NET Core Identity), managed (Azure AD) or third-party solutions (i.e. when an on-premises OIDC server is required). 

Parent: #29452

**Comment by JeremyLikness** [comment]
My goal with this document is to provide a clear set of guidelines for choosing solutions to manage identity for web apps written in .NET. Most of it likely it will be in the "matrix style" with options and requirements so as a developer you can pick the row that addresses the majority of your requirements.

I propose the following solution buckets:

- Self-host with simple sign on - ASP.NET Core Identity and related APIs
- Self-host with requirements that lead to an OAuth Server - use the [ASP.NET Core Identity management solutions](https://learn.microsoft.com/aspnet/core/security/identity-management-solutions) document to find the right solution
- Managed (Microsoft) - Microsoft Entra solutions, link to their ASP.NET specific guidance
- Managed (other) - same page, follow vendor guidance                                                                                                                   

For the matrix, I plan to pivot on:

- Do you handle settings and options via interactive code, or do you prefer configuration and/or environment variables, or perhaps something more specific like Azure Key Vault?
- How much customization do you need or are able to do? (legacy app that is locked in vs. app you have more control over)
- Do you need to support external and/or "social" authentication?
- Do you need custom logic in your authorization flows?
- Do you need easy and straightforward access to the authenticated user's name or other identity-specific credentials?
- How do you handle consent?
- Is cookie-based auth fine or do you need tokens?
- How important are refresh tokens to your user experience?
- Do you need single sign on between environments (development and test for example)
- Do you need support for clients in multiple languages and platforms?
- Will mobile applications require access to your APIs?

What else influences your decision to go with a particular identity management solution?

This issue will track the progress of the new "guidance document", and also serve a place for our developer community to provide thoughts and feedback for our consideration. The ASP.NET Core team is committed to delivering improved documentation in the .NET 8 timeline. I also appreciate when those of you who own or coordinate a project or solution in this space provide feedback and help us improve what and how we deliver features that support the requirements in your product or service offerings.

/cc @damienbod @brockallen @kevinchalet

**Comment by michaelvgibson** [comment]
Thanks for this @JeremyLikness   I am looking forward to seeing the end product.

**Comment by franks1** [comment]
This is great

**Comment by carolynlschroeder** [comment]
These are all important considerations and I thank you for you efforts.  When working with clients, the question of authentication is always the first that needs to be answered.  To implement my designs, I need custom logic in authorization flows.

**Comment by deastr** [comment]
- Where to store tokens for SPAs. localStorage/sessionStorage/cookie, or use auth cookie and save it in backend (like BFF)

**Comment by damienbod** [comment]
Hi @JeremyLikness If you are creating docs about choosing an identity management solution and then authentication based on this environment, maybe you should also include docs about FIDO2/passkeys and ID-tech solutions (self sovereign identity SSI based). The security context is most important when choosing a solution, not just the technical implementation. 

Greetings Damien
