### ISSUE TITLE
I'm getting Error Code TS5055

### ISSUE THREAD

**Issue by programatix** [dotnet/AspNetCore.Docs#29470]
[Enter feedback here]
Adding a [pagename].cshtml.js caused the following error popping up in the Error List.

```
Severity	Code	Description	Project	File	Line	Category	Suppression State
Error	TS5055	Cannot write file '.../Pages/.../Details.cshtml.js' because it would overwrite input file.
  Adding a tsconfig.json file will help organize projects that contain both TypeScript and JavaScript files. Learn more at https://aka.ms/tsconfig.	Miscellaneous	....sln	1	Error	Active
```

I'm not using any TS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 98750](https://dev.azure.com/msft-skilling/Content/_workitems/edit/98750)

**Comment by wadepickett** [comment]
Thanks @programatix for taking the time to relay the issue you are running into.  I will investigate.

**Comment by wadepickett** [comment]
@programatix,  there was a recent report of someone experiencing this issue if a .cshtml.js file is left open (even if it was not changed).   If you have a chance, could you verify that all files are closed, the app is not running, and then recompile and run to see if the issue resolves itself?  There are some other possibilities, but this is a good one to quickly check here.


Also, what version of Visual Studio and the .NET SDK are you using?    Many thanks in advance!

**Comment by programatix** [comment]
Thanks @wadepickett for the fast reply. Taking the clues from your post, I found the following.

- Open the .cshtml file only and run.
  - OK
- Open the .cshtml.js file only and run.
  - OK
- Open both the .cshtml and .cshtml.js files and run.
  - The project successfully builds and runs fine, but once the project starts (debugging mode), the error appears in the Error List. 
  - Once the error appears, it will stay until I either close .cshtml or .cshtml.js (or both) and followed by a run. It disappears when the project starts.

I'm using Visual Studio Pro 2022 (version 17.5.5) and .NET 7.0.203 for the ASP.NET Core project.

**Comment by wadepickett** [comment]
This behavior may also be related to an issue still being discussed here: https://github.com/microsoft/TypeScript/issues/54299

Closing this doc specific issue.
