### ISSUE TITLE
Grammar and spelling

### ISSUE THREAD

**Issue by bluebaroncanada** [dotnet/AspNetCore.Docs#29482]
This document is fraught with misspellings and grammatical errors.

"depending in" => "depending on"

Irregular capitalization of api or API: "... client app places in the api. For example, if an API ..."

Unnecessary comma: "Never put untrusted data into your HTML input, unless you follow the rest of the steps below."

Non-parallel list and run-on sentence: "Untrusted data is any data that may be controlled by an attacker, HTML form inputs, query strings, HTTP headers, even data sourced from a database as an attacker may be able to breach your database even if they cannot breach your application."

Dependent clause followed by an independent clause requires a comma: "Before putting untrusted data inside an HTML element ensure it's HTML encoded. HTML encoding takes characters such as < and changes them into a safe form like &lt;"

I'm gonna stop there.  This really needs a proofread.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

**Comment by bluebaroncanada** [comment]
I have a reading disability and I don't think I should be the one to fix this. I can try my best, but I have to look everything up in The Gregg.

**Comment by postmeback** [comment]
I will fix this.

**Comment by Rick-Anderson** [comment]
@postmeback sure.

**Comment by postmeback** [comment]
@bluebaroncanada , if i may ask, can you proofread the changes ?
