### ISSUE TITLE
Facebook Not Activate

### ISSUE THREAD

**Issue by Mukeshk1407** [dotnet/AspNetCore.Docs#29480]
I am setup facebook external authentication in my dot net application by follwing this document but i am facing App is not activated issue.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/92352730/c29f4760-3977-4cdd-bf1a-eba1e32b3a77)

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
