### ISSUE TITLE
the github link returns page not found

### ISSUE THREAD

**Issue by mohammadreza-khakpour** [dotnet/AspNetCore.Docs#29493]
the provided link for github sample code returns 404
the link is: https://github.com/davidfowl/TodoApi/blob/main/TodoApi.Tests/TodoTests.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @mohammadreza-khakpour for letting us know!  We will get this fixed.
