### ISSUE TITLE
Document guidance for upgrading Blazor Server apps to .NET 8 

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#29505]
Blazor Server apps will still be supported in .NET 8, but we should provide guidance for upgrading to use the latest Blazor full stack web UI features.

Sample and guidance: https://github.com/danroth27/Net8BlazorServer

**Comment by garrettlondon1** [comment]
In .NET 8, it looks like pre-rendering is enabled by default with RenderMode.Server. This may cause some confusion considering the Server vs ServerPrerendered rendering modes that Blazor Server folks are used to.

It may be worth showing an example of how to also change InteractiveServer mode to not pre-render, as now there are only three render modes.

**Comment by danroth27** [comment]
The Blazor Server template already enabled prerendering by default. This made sense because the components always run from the server. 

I think where users are more likely to get surprised is when migrating Blazor WebAssembly apps. We didn't enable prerendering by default for Blazor WebAssembly in previous releases because there is added complexity in designing component to run from both the client and the server.

Regardless, we should certainly document how to disable prerendering if it is causing issue.
