### ISSUE TITLE
Page Not found - error 404 fixed.

### ISSUE THREAD

**Issue by csmdpampa** [dotnet/AspNetCore.Docs#29509]
I followed the example in VS 2022 and was able to get my EDGE browser to view the basic entry screen in this project.  but was unable to get the "Welcome" message to execute due to the Page Not found error 404.  
Finally, after much reading and searching I was able to discover that this was due to the missing code :

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

The above code inserted in the program.cs fixed the problem.  It was not mentioned, in following that example that this explicitly needs to be added to program.cs and is NOT generated automatically.  The straight reading of the example would have suggested that the code is automatically there and that the example will run the Welcome message , when it fact is DOES NOT.   
I otherwise have enjoyed the introduction to ASP.NET and look forward to more. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by postmeback** [comment]
I believe you might have missed the part, please refer the below screenshot

![image](https://github.com/dotnet/AspNetCore.Docs/assets/14862687/9a8c4c55-70cd-4979-9f14-afa53eeb7f28)

**Comment by wadepickett** [comment]
@postmeback, thanks for jumping in to help!
@csmdpampa, I think @postmeback has hit on what you might have missed in the steps.  Closing this issue.  However, if you feel we have missed something, feel free to re-open.
