### ISSUE TITLE
Default timeout is 30 seconds, not 5 seconds

### ISSUE THREAD

**Issue by worming004** [dotnet/AspNetCore.Docs#29511]
Documentation said on lines 63 and 72 that task will be stopped after 5 seconds https://github.com/dotnet/AspNetCore.Docs/blob/3483429fc29be74eace65ceb7bebb3ec87f78f61/aspnetcore/fundamentals/host/hosted-services.md?plain=1#L63-L72

But default timeout on HostOptions is 30 seconds https://source.dot.net/#Microsoft.Extensions.Hosting/HostOptions.cs,18

It can be reproduced by a basic `dotnet new worker` and adding this worker

public class ExampleWorker : BackgroundService
{
    private readonly ILogger<ExampleWorker> _logger;
    private int seconds = 1000;

    public ExampleWorker(ILogger<ExampleWorker> logger)
    {
        _logger = logger;
    }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        return LogInLoop(stoppingToken);
    }

    private async Task LogInLoop(CancellationToken stoppingToken)
    {
        try
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
        catch (TaskCanceledException taskEx)
        {
            _logger.LogError(taskEx, taskEx.ToString());
        }
        finally
        {
            _logger.LogInformation("Loop exit");
            await Task.Delay(15 * seconds);
            _logger.LogInformation("Gracefully shutdown"); // This will be printed, even if cancel was asked for approximatively 10 seconds ago
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@worming004 Thanks for reporting that!

**Comment by worming004** [comment]
Thanks for the quick response. What a CI !
