### ISSUE TITLE
Directions out of order

### ISSUE THREAD

**Issue by blodgettb** [dotnet/AspNetCore.Docs#29512]
1. To see the final output as shown, one must do this BEFOREHAND (not afterwards):
Update the appsettings.Development.json file by adding the following lines:
"Microsoft.AspNetCore.Hosting": "Information",
"Microsoft.AspNetCore.Routing.EndpointMiddleware": "Information"
2. An additional comma is needed before these added lines in appsettings.Development.json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
@blodgettb thanks for letting us know.

@wadepickett show the entire file and highlight the added lines. Note the leading `,`

```
,"Microsoft.AspNetCore.Hosting": "Information",
"Microsoft.AspNetCore.Routing.EndpointMiddleware": "Information"
```

**Comment by Rick-Anderson** [comment]
@postmeback if you're interested:

- Add the lines to https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/grpc/grpc-start/sample/sample8/GrpcGreeter/appsettings.Development.json
- ref this appsettings.Development.json
`  [!code-json[](~/tutorials/grpc/grpc-start/sample8/GrpcGreeter/appsettings.Development.json?highlight=6-7)]
- put instructions before running per the issue

**Comment by postmeback** [comment]
Give me a day or two. I will be completing this.

**Comment by postmeback** [comment]
Step 1: I have done that, PR: #29549 

Step 2: Not sure, I have tried to follow the process to my best understanding, PR: #29550 

Requesting you to review it, before merging it.

**Comment by Rick-Anderson** [comment]
> Step 1: I have done that, PR: #29549
> 
> Step 2: Not sure, I have tried to follow the process to my best understanding, PR: #29550
> 
> Requesting you to review it, before merging it.

If you're working from the browser,  edit https://github.com/dotnet/AspNetCore.Docs/pull/29550/files
Navigate to the other file
<img width="465" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/cb8bdb69-a611-4ae8-9385-80c2c8ffb89a">

Edit the file, then you can commit change to the #29550
That way all the changes are in one PR and we can see how they work together.

**Comment by postmeback** [comment]
![Github-Rick](https://github.com/dotnet/AspNetCore.Docs/assets/14862687/48de6ec6-6540-463d-9927-e506f13d4aaf)


Refer to the screenshot, I have already made the changes here.

**Comment by postmeback** [comment]
I believe this issue is fixed. Requesting to close.
