### ISSUE TITLE
Document guidance for upgrading ASP.NET Core hosted Blazor WebAssembly apps to .NET 8

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#29522]
ASP.NET Core hosted Blazor WebAssembly apps will still be supported in .NET 8, but we should provide guidance for upgrading to use the latest Blazor full stack web UI features.

Sample and guidance: https://github.com/danroth27/Net8BlazorWebAssembly

**Comment by Jimmys20** [comment]
ASP.NET Core hosted Blazor WASM template also had the "Progressive Web Application" option. What is the recommended way to create progressive web apps with offline support using Blazor in .NET 8? How should we upgrade existing ASP.NET Core hosted Blazor WASM Progressive Web Apps?  Please provide guidance what changes need to be done to `service-worker.published.js`.

**Comment by robertmclaws** [comment]
Question: Has the sample above been updated for RC1/2?

Thanks!

**Comment by danroth27** [comment]
> Question: Has the sample above been updated for RC1/2?

@robertmclaws Not yet. Feel free to beat me to it! 😅

**Comment by Webreaper** [comment]
Would be great if you could - I used this guidance to try and update my app to use interactive webassembly, but now I've upgraded to .Net 8 RC2 the app doesn't load, and I'm hoping I can use your sample to figure out how to revert my app back to hosted WASM. :-)

**Comment by robertmclaws** [comment]
> Would be great if you could - I used this guidance to try and update my app to use interactive webassembly, but now I've upgraded to .Net 8 RC2 the app doesn't load, and I'm hoping I can use your sample to figure out how to revert my app back to hosted WASM. :-)

I just upgraded to the RC2 binaries and didn't change anything else, and my app still works fine. I'm not going to migrate over to the new structure & features until I understand it better and there are more concrete instructions plus a benefit analysis on what is gained by doing so.

**Comment by saadshaukat1** [comment]
will the guide work for .net 8.0 GA ?

**Comment by saadshaukat1** [comment]
> ASP.NET Core hosted Blazor WebAssembly apps will still be supported in .NET 8, but we should provide guidance for upgrading to use the latest Blazor full stack web UI features.
> 
> Sample and guidance: https://github.com/danroth27/Net8BlazorWebAssembly

will the guide work for .net 8.0 GA ?

**Comment by SeanFeldman** [comment]
@danroth27, thank you for putting out a minimal upgrade guide/repo for the .NET 8 pre-release.
As someone who had to take a client's production application and upgrade from Blazor WebAssembly .NET 6 to .NET 8, I'd like to emphasize that the ASP.NET Blazor team should have put some more effort for the clients that wanted to stay on the hosted option. The current guide is insufficient and is misleading. Some examples of the issues that are not covered would be the default pre-rendering that needs to be disabled, the lazy loading that has changed the extension from .dll to .wasm, etc. I see why folks stay away from Microsoft UI frameworks. Migrating from one LTS of .NET to its subsequent LTS version shouldn't be riddled with surprises and pain. This issue is closed, but it's not completed.

**Comment by danroth27** [comment]
> @danroth27, thank you for putting out a minimal upgrade guide/repo for the .NET 8 pre-release. As someone who had to take a client's production application and upgrade from Blazor WebAssembly .NET 6 to .NET 8, I'd like to emphasize that the ASP.NET Blazor team should have put some more effort for the clients that wanted to stay on the hosted option. The current guide is insufficient and is misleading. Some examples of the issues that are not covered would be the default pre-rendering that needs to be disabled, the lazy loading that has changed the extension from .dll to .wasm, etc. I see why folks stay away from Microsoft UI frameworks. Migrating from one LTS of .NET to its subsequent LTS version shouldn't be riddled with surprises and pain. This issue is closed, but it's not completed.

Thanks @SeanFeldman for sharing this feedback. I've updated #32138 to address these gaps. We do cover disabling prerendering in our upgrade [guidance](https://learn.microsoft.com/aspnet/core/migration/70-80#convert-a-hosted-blazor-webassembly-app-into-a-blazor-web-app), but it looks like we missed the impact of webcil on lazy loading. If there are other upgrade steps we missed, please let me know!
