### ISSUE TITLE
Document `IExceptionHandler`

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#29520]
See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/#iexceptionhandler for detail about this feature.

Should be added to https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#exception-handler-page

@Tratcher @adityamandaleeka @joperezr 

@tdykstra edit to add document details block

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#exception-handler-page)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 115465](https://dev.azure.com/msft-skilling/Content/_workitems/edit/115465)

**Comment by wadepickett** [comment]
@tdykstra, just a heads up, I think that is your doc.

**Comment by Rick-Anderson** [comment]
See related #29600
