### ISSUE TITLE
Update What's new for preview 5

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29532]
[[Enter feedback here]](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/#improved-asp-net-core-debugging-experience)

What's new only, doesn't go into any of our docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Version Independent ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Content: [What's new in ASP.NET Core 8.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-8.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 115462](https://dev.azure.com/msft-skilling/Content/_workitems/edit/115462)

**Comment by tdykstra** [comment]
@Rick-Anderson Is this for preview 5 only or 1-5?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson Is this for preview 5 only or 1-5?

Hopefully 1-5

**Comment by tdykstra** [comment]
I made other issues for 1-3, and you made [one for 4 that I self-assigned](https://github.com/dotnet/AspNetCore.Docs/issues/29364), so this one can be for Preview 5 only.
