### ISSUE TITLE
HTTP.sys: Update sample code from 3.x to 8.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29562]
Make an 8.x version of
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/servers/httpsys/samples/3.x/SampleApp  in the newly created 8.x folder

@david-acker  are you interested in this

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-8.0)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 117032](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117032)

**Comment by david-acker** [comment]
@Rick-Anderson Sure! I can get started on this tomorrow.

**Comment by Rick-Anderson** [comment]
@david-acker Consider starting with an empty project. I think you can do everything with that.
