### ISSUE TITLE
New analyzer for recommended AuthorizationBuilder usage

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29583]
[New analyzer for recommended AuthorizationBuilder usage](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/#new-analyzer-for-recommended-authorizationbuilder-usage)

Put under
`## Authentication and authorization`

`<xref:Microsoft.Extensions.DependencyInjection.PolicyServiceCollectionExtensions.AddAuthorizationBuilder%2A>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Version Independent ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Content: [What's new in ASP.NET Core 8.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-8.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 117230](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117230)

**Comment by tdykstra** [comment]
This is ASP0025 
https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0025?view=aspnetcore-8.0

**Comment by Rick-Anderson** [comment]
@tdykstra  but don't we need to update What's new with the change? Do you want to own this issue?

**Comment by tdykstra** [comment]
Sure

**Comment by tdykstra** [comment]
I just looked, and ASP0025 is already in the what's new in the list of analyzers.
