### ISSUE TITLE
SNI hostname in ITlsHandshakeFeature

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29598]
[SNI hostname in ITlsHandshakeFeature](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/#sni-hostname-in-itlshandshakefeature)

Is [Web server implementations in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-8.0&tabs=windows) the right place to document SNI hostname in[ `ITlsHandshakeFeature`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.connections.features.itlshandshakefeature?view=aspnetcore-8.0)?

After closing this Issue, create a new issue for the What's new doc and add a link to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-8.0&tabs=windows)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 117422](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117422)

**Comment by Rick-Anderson** [comment]
@Tratcher is this the right place to document `ITlsHandshakeFeature ` ? cc @karimsalem1

**Comment by Tratcher** [comment]
Roughly. Maybe there should be another doc next to this called Shared Features?
