### ISSUE TITLE
New topic: Debugging .NET Core on Unix over SSH

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#2960]
Need doc covering content on [team blog on this topic](https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/).

Per [@]Andrew-MSFT
You need either the ASP.NET and web development workload or the .NET Core cross platform workload installed.

Also, we should make the topic focus on debugging ASP.NET Core, that will be by far the more common scenario. Remote debugging a console app is not a common need.

Original issue: https://github.com/dotnet/docs/issues/1627

**Comment by Rick-Anderson** [comment]
- [Debugging ASP Core on Linux with Visual Studio 2017](https://blogs.msdn.microsoft.com/premier_developer/2017/11/10/debugging-asp-core-on-linux-with-visual-studio-2017/)
- [Remote debugging asp.net core on linux server SO post](https://stackoverflow.com/questions/42483122/remote-debugging-asp-net-core-on-linux-server)
- [SO: How to debug a .NET Core app runnig in Linux Docker container from Visual Studio](https://stackoverflow.com/questions/48661857/how-to-debug-a-net-core-app-runnig-in-linux-docker-container-from-visual-studio)

**Comment by mendozafelipe1021-a11y** [comment]
> Need doc covering content on [team blog on this topic](https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/).
> 
> Per [@]Andrew-MSFT You need either the ASP.NET and web development workload or the .NET Core cross platform workload installed.
> 
> Also, we should make the topic focus on debugging ASP.NET Core, that will be by far the more common scenario. Remote debugging a console app is not a common need.
> 
> Original issue: [dotnet/docs#1627](https://github.com/dotnet/docs/issues/1627)
