### ISSUE TITLE
Sample code under "Attach tokens to outgoing requests" doesn't work

### ISSUE THREAD

**Issue by jdh148** [dotnet/AspNetCore.Docs#29606]
Adding this snippet of code to a new .NET 7 Blazor WASM project:

```
using System.Net.Http;
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;

...

builder.Services.AddHttpClient("WebAPI", 
        client => client.BaseAddress = new Uri("https://www.example.com/base"))
    .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

builder.Services.AddScoped(sp => sp.GetRequiredService<IHttpClientFactory>()
    .CreateClient("WebAPI"));
```

Results in these two errors:

```
[CS1061] 'IServiceCollection' does not contain a definition for 'AddHttpClient' and no accessible extension method 'AddHttpClient' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
[CS0246] The type or namespace name 'IHttpClientFactory' could not be found (are you missing a using directive or an assembly reference?)
```

I fixed the errors by adding the `Microsoft.Extensions.Http` package to the project (which was originally created using `dotnet new blazorwasm -au Individual -o MyProject`)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53f3209c-2414-9b35-6245-383c9b7c6338
* Version Independent ID: cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe
* Content: [ASP.NET Core Blazor WebAssembly additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jdh148 ... I see that it doesn't explicitly tell the reader to add the package. It's covered, but not as an instruction, so I'll make it say to add the package and provide our package INCLUDE that we place to tell devs how to do it.
