### ISSUE TITLE
Add sample code for IDistributedCache

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29618]
Provide samples for Azure Redis.
Put the sample in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/performance/caching/distributed/samples

put in 8.x/RedisCache folder

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 117610](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117610)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson @tdykstra Does this sample require any additional configuration other than the following?

```
builder.Services.AddStackExchangeRedisCache(options =>
{
    options.Configuration = builder.Configuration.GetConnectionString("MyAzureRedisConStr");
    options.InstanceName = "SampleInstance";
});
```

```
"MyAzureRedisConStr": "<cache name>.redis.cache.windows.net,abortConnect=false,ssl=true,allowAdmin=true,password=<primary-access-key>"
```
