### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by MichaelBrooks-Informatyx** [dotnet/AspNetCore.Docs#29626]
[Enter feedback here]
"Client requirements may exclude **user's** who have low-end devices"
WTF is that apostrophe there for? The plural of user is users - no apostrophe! Can Microsoft no longer afford to employ people with even a rudimentary grasp of English grammar?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21671480-fba7-3692-1a20-e71843864b60
* Version Independent ID: 68d5aab0-63ce-de7a-0c56-341c2eef623d
* Content: [Choose an ASP.NET Core UI](https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/choose-web-ui.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
It was a missed typo, which can happen.  Thanks for raising the issue, but do be civil, and please review our [code of conduct](https://github.com/dotnet/AspNetCore.Docs/blob/6dbb1216ed83e5cc031badf42cab79ee42cc9b1c/CODE_OF_CONDUCT.md).

**Comment by MichaelBrooks-Informatyx** [comment]
Sorry Wade - the continual degradation in the quality of written English that I witness on a daily basis tends to make my blood boil, especially when I see so much of it from supposedly degree-educated software developers (not saying that the author of this was a degree-educated software developer; that's merely whom I am surrounded by on a daily basis). Typographical errors are fair enough as we all make them (the fingers are controlled by muscle memory), so I should indeed be more tolerant. Rebuke accepted humbly.

Regards,
Michael
