### ISSUE TITLE
Update .NET Creating Metrics

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29621]
[Creating metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation)

Use the same code as [Collect metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-collection)

See https://github.com/dotnet/docs/issues/35927

**Comment by tdykstra** [comment]
This looks like a duplicate of [#35927](https://github.com/dotnet/docs/issues/35927) - what's the difference?

**Comment by Rick-Anderson** [comment]
One issue is in our repo. I don't monitor issues in the .NET repo. that's the difference.
