### ISSUE TITLE
Please be advised - The final example is, IMO, incorrect

### ISSUE THREAD

**Issue by ThomSimone** [dotnet/AspNetCore.Docs#29638]
Mr. Pickett:

First of all, thank you for this tutorial.  It is helping me.

I am NO expert in Web development, but I have been a coder for 45 years.

I ran into an issue on the final part of this page. Here Rick is discussing the use of parameters.

After working with the "HelloWorld" Controller, the tutorial discusses the subject of Parameters.  It states that the "id" can be utilized as a parameter and therefore returned by default.  Unfortunately, I don't think it does.  I could not get this to work correctly until I moved this "Welcome" GET method to the "Home" Controller and matched the call to reflect this.

As in
     "https://localhost:XXXX/Home/Welcome/3?UserName=Thom"
instead of
     "https://localhost:XXXX/HelloWorld/Welcome/3?UserName=Thom"

What is shown next is exactly what is in the default app.MapControllerRoute in Program.cs.

app.MapControllerRoute(
	name: "default",
	pattern: "{controller=Home}/{action=Index}/{id?}");

Notice that this still points to "Home".  As written, the GET always returns 0.  Creating a "Welcome" GET in the "Home" Controller, I receive a non-zero value.

Respectfully,

Thom Simone
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Part 2, add a controller to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
@ThomSimone, thanks for the heads up!  We will get it fixed.

**Comment by postmeback** [comment]
I would like to contribute. 😃

**Comment by Rick-Anderson** [comment]
@wadepickett  @postmeback  the instructions are correct, this has worked since ASP.NET MVC (pre core).



> @ThomSimone, thanks for the heads up! We will get it fixed.

Refrain from acknowledging a problem until you've confirmed it.
