### ISSUE TITLE
Developer Exception Page clarification

### ISSUE THREAD

**Issue by lcichanowicz** [dotnet/AspNetCore.Docs#29633]
It is confusing to say that the code _enables_ the Developer Exception Page.  I think the code's call to WebApplication.CreateBuilder will have the effect of enabling the Developer Exception Page, but that code does not explicitly enable it.

> The following code:
> 
> Is similar to the code generated by the ASP.NET Core templates.
> Enables the [Developer Exception Page](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0#developer-exception-page) when ASPNETCORE_ENVIRONMENT is set to Development. This is done automatically by the [WebApplication.CreateBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createbuilder) method.
> 

I suggest changing that line to:

Implicitly enables the [Developer Exception Page]...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion
