### ISSUE TITLE
Source generation does not work in sdk style project

### ISSUE THREAD

**Issue by sensslen** [dotnet/AspNetCore.Docs#29640]
When I moved my project that used this approach to an sdk style project, the sources would no longer be generated and also the proto files would no longer show up in the project in VisualStudio

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7223e694-85ba-4b95-96c8-68ae14753e7c
* Version Independent ID: 28ec8399-ba0e-c995-3ac2-b1f28e93331b
* Content: [gRPC services with C#](https://learn.microsoft.com/en-us/aspnet/core/grpc/basics?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/basics.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/basics.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@sensslen, sorry to hear your project is not running as you expected.   The information is a bit vague here for me to work with since I don't know your project.  It sounds like your project worked until you moved the project to an "SDK style" project.  By "
SDK style" I am guessing that you are referring to creating and running the project at the command line.   

We have a tutorial that walks through using Visual Studio to create a gRPC server and client.  It also has a tab you can select to see the same instruction using VS Code & CLI.  Going through those side by side might clarify things and help you understand what to apply to your own project.  See [Tutorial: Create a gRPC client and server in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-7.0&tabs=visual-studio)

I will close this issue that pertains to a request in changes to the topic, but if you have something more specific or more information that would be helpful, feel free to reopen.

**Comment by sensslen** [comment]
@wadepickett To give you a better Idea of what I did:

I had a project file that looked something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <ProjectGuid>--GUID removed--</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>--namespace removed--</RootNamespace>
    <AssemblyName>--assembly name removed--</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <LangVersion>9.0</LangVersion>
    <FileAlignment>512</FileAlignment>
    <OutputPath>bin\$(Platform)\$(Configuration)\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>TRACE;DEBUG;GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Protobuf Include="Path/to/some/protofile.proto" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf">
      <Version>3.12.3</Version>
    </PackageReference>
    <PackageReference Include="Grpc.Tools">
      <Version>2.54.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

I then updated this to:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>9.0</LangVersion>
    <OutputPath>bin\$(Platform)\$(Configuration)\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>x64</Platforms>
    <DefineConstants>$(DefineConstants);GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Path/to/some/protofile.proto" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf">
      <Version>3.12.3</Version>
    </PackageReference>
    <PackageReference Include="Grpc.Tools">
      <Version>2.54.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

No other file did change.
Where the first file does in fact create the necessary c# files to interact with the proto file, the second does not.
