### ISSUE TITLE
Refactor: Fundamentals\log-mon contains Logging, HTTP logger, W3C Logger, Health checks, and Metrics.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29645]
Move from host and deploy to a new high level section Heath checks and metrics. That could be an empty heading with health checks and metrics article .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 118039](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118039)

**Comment by Rick-Anderson** [comment]
@tdykstra  please approve

**Comment by tdykstra** [comment]
How about a new section under Fundamentals, named something like **Logging and monitoring**, which would contain **Logging**, **HTTP logger**, **W3C Logger**, **Health checks**, and **Metrics**.

**Comment by Rick-Anderson** [comment]
Fundamentals\Logging\metrics

* [Overview](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics) (external)
* [metrics tutorial](https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics?view=aspnetcore-8.0)
* [Microsoft.AspNetCore.Hosting & Kestrel metrics](https://github.com/dotnet/aspnetcore/issues/47536) make this doc
* SignalR metrics
