### ISSUE TITLE
Redundant "Add > New Scaffolded Item" image

### ISSUE THREAD

**Issue by zrk1** [dotnet/AspNetCore.Docs#29661]
Dear Sirs:

I've noticed that there seems to be a redundant image on this page "Part 4, add a model to an ASP.NET Core MVC app". Under the heading "Scaffold movie pages" there are two images that show the selection of a menu item "Add > New Scaffolded Item". I would expect that the second image should actually show an image representing the "Add New Scaffolded Item dialog".

Please let me know if I'm missing something :)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by postmeback** [comment]
![Screenshot 2023-07-04 120427](https://github.com/dotnet/AspNetCore.Docs/assets/14862687/29e94aea-9318-46d2-a7ca-9faba25a34b5)


I think we should remove this image, and it will get fixed. Shall I create a PR on this?

**Comment by wadepickett** [comment]
More info:  Version 8 and <= 6 are right, but for version 7 the image link should be pointing to an "Add New Scaffolded Item" dialog for VS 2022 instead in that location.
