### ISSUE TITLE
Update of the Server JSON needs to occur prior to instructions to view the kestrel log

### ISSUE THREAD

**Issue by ketchup201** [dotnet/AspNetCore.Docs#29675]
[Enter feedback here]

Instructions are out of order. They say to view the greeter activity in the kestrel log but we can't because the instructions to make that happen are done in the next step.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d298a6c-8ddc-dbc8-d219-0fa7138442c2
* Version Independent ID: b96be346-958a-cfcd-d80a-c352d64223e8
* Content: [Create a .NET Core gRPC client and server in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-7.0&tabs=visual-studio#create-a-grpc-service)
* Content Source: [aspnetcore/tutorials/grpc/grpc-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/grpc/grpc-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

---
[Associated WorkItem - 118753](https://dev.azure.com/msft-skilling/Content/_workitems/edit/118753)

**Comment by Rick-Anderson** [comment]
@postmeback  fixed the 8.0 version in #29549
Problem reported in https://github.com/dotnet/AspNetCore.Docs/pull/29549

@postmeback  can you apply the same fix to the 7.0 version?

**Comment by postmeback** [comment]
Sure, I can. 

Can you help me with the necessary links?
