### ISSUE TITLE
It's unclear on the source of User Accounts during Azure SQL Database Deployment

### ISSUE THREAD

**Issue by ccnicholls99** [dotnet/AspNetCore.Docs#29706]
During the Deployment of SQL Database(s), the documentation is silent on the source of User Accounts for the Server Administrator and Database Connection User...

Ex.1
![image](https://github.com/dotnet/AspNetCore.Docs/assets/26383029/eb550718-57fb-407e-9b83-d3b17ea2ae77) ...and...
Ex.2
![image](https://github.com/dotnet/AspNetCore.Docs/assets/26383029/38ea9529-ca45-4f54-a382-ff0a0d7bb6d0)

...
* Are these User Accounts created during deployment? (One is to assume NOT since one of the requirements, in Ex.1 is the Db Administrator must have 'Create' Access - but how/where is this access defined?)
* If Accounts are assumed to exist - then where are they defined?  In the App?, in the local DB? On Azure SQL? In Azure AD? 

Some relevant links to any pre-requisite Account Setup steps may be helpful for this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71a44c72-d256-fbee-ea70-2eb7472f8182
* Version Independent ID: 157027ff-0bad-828d-a442-a98acd219fba
* Content: [Publish an ASP.NET Core app to Azure with Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
> Are these User Accounts created during deployment? 

Yes
