### ISSUE TITLE
Request: include an example of documenting models and their (optional) required properties

### ISSUE THREAD

**Issue by PureKrome** [dotnet/AspNetCore.Docs#29702]
👋🏻 G'Day!

OpenAPI has the concept of allow us to describe the actual model and also which properties are _required_.

Here's an [example of the canonical "petstore" swagger UI](https://petstore.swagger.io/):

![image](https://github.com/dotnet/AspNetCore.Docs/assets/899878/b7123645-6820-44c6-b3ad-a478ebd5dc4a)

with a snippet of the json for this OpenAPI being:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/899878/89a730ac-96fd-4696-ba75-0e8f62b25183)

This would really help people add more detail to their OpenAPI's in their Minimal API apps.

Even if this is an implementation detail about OpenAPI and is not specific to Minimal API apps, even a link to external information would be 💯 lovely!

For bonus points, if you were able to add something to this page ... using `record`s (instead of classes) would be so awesome. or both `record`'s and `class`es

thanks kindly, awesome team! 🎉 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b18acd86-50e3-2316-27be-27156651e5a8
* Version Independent ID: b18acd86-50e3-2316-27be-27156651e5a8
* Content: [How to use OpenAPI in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/openapi.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by garrettlondon1** [comment]
Can’t you use the [Required] data annotation on your DTO? Swashbuckle will pick it up and show the asterisks as well

**Comment by PureKrome** [comment]
Maybe? Whatever the answer is, my request here was to get it documented for noobs like myself. 😊

**Comment by garrettlondon1** [comment]
https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&tabs=visual-studio#data-annotations

This should help you out, there is a good example of the [Required] data annotation

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
