### ISSUE TITLE
"Build a Windows Presentation Foundation (WPF) Blazor app" does not work

### ISSUE THREAD

**Issue by WinterIsComming861047** [dotnet/AspNetCore.Docs#29725]
Can't follow the tutorial when it comes to "MainWindow.xaml" replace part.

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0418	Assembly 'Microsoft.AspNetCore.Components.WebView.Wpf' was not found. Verify that you are not missing an assembly reference. Also, verify that your project and all referenced assemblies have been built.	WpfBlazor	C:\Users\xxxxx\source\repos\WpfBlazor\WpfBlazor\MainWindow.xaml	6	

Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0008	The name "BlazorWebView" does not exist in the namespace "clr-namespace:Microsoft.AspNetCore.Components.WebView.Wpf;assembly=Microsoft.AspNetCore.Components.WebView.Wpf".	WpfBlazor	C:\Users\xxxxx\source\repos\WpfBlazor\WpfBlazor\MainWindow.xaml	11	

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Version Independent ID: 94872f14-0dce-0cf3-0d25-88f23ca8d8ef
* Content: [Build a Windows Presentation Foundation (WPF) Blazor app](https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/hybrid/tutorials/wpf.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @WinterIsComming861047 ... Did you add the [`Microsoft.AspNetCore.Components.WebView.Wpf`](https://nuget.org/packages/Microsoft.AspNetCore.Components.WebView.Wpf) package to the app?

**Comment by guardrex** [comment]
I'm going to close as answered, but you can leave additional information if you do have the package referenced in the app and are still hitting that error.

**Comment by WinterIsComming861047** [comment]
Hi, thanks for your reply.
I thought you were talking about the part of installing Nuget package.
I just re do the tutorial again and post it to the github, maybe you can
point out which part I was doing wrong.

WinterIsComming861047/WPFBlazor (github.com)
<https://github.com/WinterIsComming861047/WPFBlazor>

Luke Latham ***@***.***> 於 2023年7月7日 週五 下午7:47寫道：

**Comment by guardrex** [comment]
Hello @WinterIsComming861047 ... I'm off for the weekend, so I'll take a look on Monday.

**Comment by WinterIsComming861047** [comment]
Sure, any help is appreciated. Thanks

Luke Latham ***@***.***> 於 2023年7月14日 週五 下午9:20寫道：

**Comment by guardrex** [comment]
I had a chance to look before taking off for the weekend:

* You (probably) didn't install the .NET desktop development workload.
* The app isn't named correctly. It should be `WpfBlazor`, not `WPFBlazor`. It (probably) caused a namespace problem.
* The `app.css` file goes into a `wwwroot` folder.
* You didn't follow the step for updating the `MainWindow.xaml` code.

I just walked the steps, and the guidance still works ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/4f034a64-b957-434f-8676-cdf4f6558128)

**Comment by FlorentVllasa** [comment]
For some reason it does not work for me when using .net6 although everything is correct including the namespaces etc. When switching to .net7 everything works fine. When trying to install the Microsoft.AspNetCore.Components.WebView.Wpf nuGet package, I also see that it installs more other packages than when installing it with .net6. Is that explaiable?

**Comment by guardrex** [comment]
@FlorentVllasa ... Open an issue for the product unit here ...

https://github.com/dotnet/aspnetcore/issues
