### ISSUE TITLE
Need help with CRUD operations on child records (enrollments)

### ISSUE THREAD

**Issue by JohnGossard** [dotnet/AspNetCore.Docs#29727]
I was expecting this tutorial to eventually perform CRUD operations with the enrollments table.  Is there any tutrorials or discussions regarding this topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
For CRUD operations in general for a single table see the [second tutorial in this series](https://learn.microsoft.com/aspnet/core/data/ef-rp/crud?view=aspnetcore-7.0); for working with relationships that enrollments has to other tables, the code in the reading related data and updating related data tutorials ([six](https://learn.microsoft.com/aspnet/core/data/ef-rp/read-related-data) and [seven](https://learn.microsoft.com/aspnet/core/data/ef-rp/update-related-data) in this series) is relevant to enrollments.
