### ISSUE TITLE
How to check if User is already in the Group ?

### ISSUE THREAD

**Issue by nssidhu** [dotnet/AspNetCore.Docs#29736]
Is there a way to check if User is already in the Group?
If there is no check will adding it again error or it just ignores adding user again and does nothing ?
Secondly does Groups and users in the Groups Survive Server Restarts?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://learn.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-7.0)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-signalr**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

---
[Associated WorkItem - 226927](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226927)

**Comment by gfoidl** [comment]
> Is there a way to check if User is already in the Group?

No.

> will adding it again error or it just ignores adding user again and does nothing ?

Put simple: if the user is already in the group, it does nothing. You're safe to add it multiple times.
Implementation detail: the book-keeping is based on ConcurrentDictionary, and here AddOrUpdate is used.

> does Groups and users in the Groups Survive Server Restarts?

They are kept in-memory, so no they won't survive.
You can look into Azure SignalR Services for such scenarios.

**Comment by wadepickett** [comment]
Thanks @gfoidl!  @nssidu, all good questions.  We should provide some insight in the doc.

**Comment by nssidhu** [comment]
@gfoidl related question
I don't see option to just create group, is it automatically created when adding user using the group name provided with connectionID ?

**Comment by gfoidl** [comment]
Yes.

You can imagine the group-membership as ConcurrentDictionary, where the groupName is the key.
All operations are fault-tolerarant, i.e. they don't throw for duplicate-keys (groupNames), etc.

**Comment by nssidhu** [comment]
@gfoidl appreciate your quick response and clarification
