### ISSUE TITLE
Document built-in metrics

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#29731]
Related to https://github.com/dotnet/AspNetCore.Docs/issues/29292

ASP.NET Core has added built-in metrics. We should provide information about what counters there are and what information they collect.

This is available in GitHub issues:

* https://github.com/dotnet/aspnetcore/issues/47536
* https://github.com/dotnet/aspnetcore/issues/47745
* https://github.com/dotnet/aspnetcore/issues/48670

Things have been renamed and changed since these were approved. Also, they're still changing. An engineer (probably me) will need to come up with final data once .NET 8 locks down.

---
[Associated WorkItem - 124029](https://dev.azure.com/msft-skilling/Content/_workitems/edit/124029)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc4aa26a-a037-2bd9-f313-e3073d6b8232
* Version Independent ID: fc4aa26a-a037-2bd9-f313-e3073d6b8232
* Content: [ASP.NET Core metrics](https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0)
* Content Source: [aspnetcore/log-mon/metrics/metrics.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/log-mon/metrics/metrics.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Update `uid: log-mon/metrics/metrics` with link to this document. Update
See [ASP.NET Core metrics](https://github.com/dotnet/aspnetcore/issues/47536) for ASP.NET Core specific metrics.
