### ISSUE TITLE
Blazor tutorials should include IDE steps where applicable

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/AspNetCore.Docs#29753]
Should have a Visual Studio option rather than doing everything from the cmd line. For the stages where you are creating the app, or adding pages, then use the Tab view to create alternate streams of content for the IDE verses cmd line options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23f2cad2-31f9-d5d1-671c-5613fb812b19
* Version Independent ID: 23f2cad2-31f9-d5d1-671c-5613fb812b19
* Content: [Build a Blazor todo list app](https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @samsp-msft ... Management decided for this one that they want the simplest approach to have a successful experience, so they only want this one to use the .NET CLI.

**Comment by danroth27** [comment]
It looks like we have a separate copy of the todo list tutorial in this learn module, which has both VS Code and VS versions: https://learn.microsoft.com/training/modules/build-blazor-webassembly-visual-studio-code/. Could we consolidate our content by redirecting the docs version of the tutorial to the learn module? Perhaps we'd need to do a clean up pass on the learn module first?

**Comment by guardrex** [comment]
Yes, especially if you want to drop prior versions of the tutorials. That was one of my questions on last Friday's email update.

I don't have access to the Learn module to directly update it, but would you like me to indicate the changes it would need for Blazor Server now? ... or we wait for 8.0 and take care of this later when it can be changed directly into a Blazor Web Apps experience?

**Comment by guardrex** [comment]
***UPDATE***: As a side task, I put up a PR to link both the Learn Module path and the filtered Learn Modules list in the *Tutorials* topic. When I first placed a link in our *Tutorials* topic, I think there were only a handful of Learn Modules there, and I don't think that there was a path. Now, there are a dozen of them and a path that we can link.

WRT the introductory Learn Module with VS, the changes I see at a glance are:

* The prereqs and objectives only refer to VSC.
* They pegged it to the 6.0 SDK and shared framework.

Other than those items, it should be ok ... but that's based on a quick look 🏃. I didn't read every paragraph.
