### ISSUE TITLE
Need a more detailed step-by-step

### ISSUE THREAD

**Issue by sujayvsarma** [dotnet/AspNetCore.Docs#29762]
The webpage linked to below provides a set of links to other pages and leaves it to the imagination of the reader to know what to pick from them. I have set up, run and managed IIS servers since the days of Windows NT. However, it is still difficult for me to understand how exactly I need to configure IIS if all I want to do is run ASP.NET Core (and ASP.NET 5+) on it.

This document needs to be a lot more step by step. Make it opinionated, no problem, but give details on exact configuration steps to be performed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sujayvsarma ... Note that there's a tutorial with the bare bones basic process at https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio. I don't see a cross-link here to it, so Rick might decide to add one when he sees your issue (`xref:tutorials/publish-to-iis`).

**Comment by sujayvsarma** [comment]
Hi @guardrex, 
I have seen the article you're referring to. It is not really barebones, because it has this so-called section in it:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/132370674/af1115c1-ee1d-4cfa-913f-16f2032c878f)

That is supposed to help you, but it really doesn't. It leaves way too many choices open like "install whatever IIS modules you like" -- well, I need to know what modules are *required* to be able to run ASP.NET Core. The IIS part of it needs to be minimal to support just ASP.NET Core. That's my point of raising this issue.

**Comment by guardrex** [comment]
Barebones is to accept the default IIS install modules.

We still have the section on minimal modules needed ...

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules?view=aspnetcore-7.0#minimum-module-configuration

... and perhaps Rick will decide that the cross-link for that section should also appear here ... perhaps also adding that cross-reference to that WARNING box in the tutorial, too. Rick, here's the cross-ref on that one in case you decide to go that way ...

```
<xref:host-and-deploy/iis/modules#minimum-module-configuration>
```

Butt-covering qualification tho: I wrote that section in ***ancient*** ASP.NET Core history! 👴 I can't say if it's been maintained or is currently accurate. It ***was*** accurate ... mmmm 🤔 ... *FIVE years ago!* 😆 It should be checked actually to confirm that it's all still true. 😄

**Comment by guardrex** [comment]
... and btw ... if you scroll *UP* in that one, you can see the table that lists which modules work with ASP.NET Core apps. Again, I put that together many years ago. At this point, I can't attest to it being 100% accurate. It's been maintained by other doc authors since then with product unit support.

**Comment by guardrex** [comment]
I don't think we agree (but you need to clarify what you mean by "this article" ... the overview or the tutorial). The purpose of the tutorial is a step-wise IIS base case experience. We won't be placing step-wise content for IIS hosting in the overview, as that's not a normal function of overview-type reference articles. I think cross-linking is a concern. Rick may or may not agree. It's really his call to decide where to go with any updates. I don't work in this area of the ToC any longer.

**Comment by Rick-Anderson** [comment]
>Let me see if I can find some time to rewrite the page in the way I'm talking about and post you a link.

If you want to write a blog post we'll consider including it. 

> What people need is for that article to be actually a 1-2-3-4 step-wise process and for it to be really prescriptive.

That's outside the scope of ASP.NET Core documentation.
