### ISSUE TITLE
Access HttpContext from custom components - Could you please mention in this area that IHtttpContextAccessor can be used only in Web SDK packages. 

### ISSUE THREAD

**Issue by Supratheesh** [dotnet/AspNetCore.Docs#29768]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by Supratheesh** [comment]
If we read this section, we assume that IHtttpContextAccessor can be used in custom created packages. But it seems it can only be used if the package is Web SDK. For better clarity, I suggest, we should mention this fact as well.

**Comment by Rick-Anderson** [comment]
Given all the templates generate `<Project Sdk="Microsoft.NET.Sdk.Web">`, why does this need to be mentioned?
