### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by jstafford5380** [dotnet/AspNetCore.Docs#29772]
Is this still up to date? When I create the protofiles in the directories described and then add the options to my service, when it runs, it throws the following on startup

> The stored extension value has a type of 'Google.Api.HttpRule, Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. This a different from the requested type of 'Google.Api.HttpRule, Google.Api.CommonProtos, Version=2.5.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'.

This seems to be related to https://github.com/dotnet/aspnetcore/issues/48192

I'm trying to reconcile between these ideas of pulling in the Google.Apis.CommonProtos (which didn't work for me, it woudln't import the protos it needed) and adding the file manually (which causes the error above).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Version Independent ID: 25375ca1-0ce8-a3ca-0c3a-446328f09ba1
* Content: [gRPC JSON transcoding in ASP.NET Core gRPC apps](https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/json-transcoding.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/json-transcoding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
@wadepickett  please review.

**Comment by jstafford5380** [comment]
Disregard, this was my mistake. It turns out that my <Protobuf> element's Include attribute glob was also capturing the http.proto and annotations.proto which was causing a conflict. Once I fixed that such that those protos were not captured, it works fine. Probably worth calling out in a document somewhere.
