### ISSUE TITLE
Hosting Bundle LTS Installer Permalink

### ISSUE THREAD

**Issue by Banner-Keith** [dotnet/AspNetCore.Docs#29785]
There is a permalink to the current Hosting Bundle Installer.

Is there one for the latest LTS version? That would be a lot more useful since a lot of enterprises try to stay LTS on production applications. If so it would be wonderful to have it documented here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65973393-2cb9-a656-01b8-7963a7a40b39
* Version Independent ID: 22e2323b-18c3-ad2b-174c-84fbf642715e
* Content: [Hosting Bundle](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0#direct-download-current-version)
* Content Source: [aspnetcore/host-and-deploy/iis/hosting-bundle.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's easy to get to from the link provided [here in the doc](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-6.0#direct-download-current-version)

**Comment by Banner-Keith** [comment]
@Rick-Anderson I am only seeing the link to latest which is .net 7. Is there one for LTS which is .net 6?
