### ISSUE TITLE
Missing example for how to use appsettings with HttpClient

### ISSUE THREAD

**Issue by sliekens** [dotnet/AspNetCore.Docs#29799]
[EDIT by guardrex to change the metadata. This will be for the *Fundamentals* > *Configuration* doc.]

It's not entirely clear how you would use appsettings to configure an HttpClient, for example when setting the base address. The article demonstrates hard-coding the URL but that is not realistic for pre-production and production environments.

``` csharp
builder.Services.AddHttpClient("GitHub", httpClient =>
{
    // How to use appsettings here?
    httpClient.BaseAddress = new Uri("https://api.github.com/");
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Rick, I have a few minutes to toss up a quick PR for this, as I'm waiting on some guidance from the PU for Blazory bits.
