### ISSUE TITLE
Reference to ".NET Framework" may have been meant to be ".NET Standard".

### ISSUE THREAD

**Issue by matrachlin** [dotnet/AspNetCore.Docs#29800]
Where it says:
The recommended way to use Entity Framework 6 in an ASP.NET Core application is to put the EF6 context and model classes in a class library project that targets .NET Framework. 

Is ".NET Framework" meant to be ".NET Standard"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f376ed07-b726-292f-eb33-7a918337367b
* Version Independent ID: 817b265f-0769-80e1-b42c-e1b0d05ff13b
* Content: [ASP.NET Core and Entity Framework 6](https://learn.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1#overview)
* Content Source: [aspnetcore/data/entity-framework-6.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/entity-framework-6.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 125055](https://dev.azure.com/msft-skilling/Content/_workitems/edit/125055)

**Comment by tdykstra** [comment]
@jeremylikness In the sample solution, both the class library and the MVCCore project target .NET Framework -- is that still the way to use EF6 with .NET Core?

**Comment by matrachlin** [comment]
I've since come across this page: https://learn.microsoft.com/en-us/ef/ef6/what-is-new/#ef-630

It states the following:

**Comment by bricelam** [comment]
I agree that this page seems out of date. Since 3.0, you don't have to target .NET Framework to use EF6 with ASP.NET Core.

**Comment by tdykstra** [comment]
> Where it says: The recommended way to use Entity Framework 6 in an ASP.NET Core application is to put the EF6 context and model classes in a class library project that targets .NET Framework.
> 
> Is ".NET Framework" meant to be ".NET Standard"?

The quoted sentence only shows up when ASP.NET Core 2.2 or earlier is selected as the Version. With 3.0 or later selected, all the article says is:

> [Entity Framework Core](https://learn.microsoft.com/en-us/ef/) should be used for new development. The [download sample](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/data/entity-framework-6/3.xsample) uses [Entity Framework 6 (EF6)](https://learn.microsoft.com/en-us/ef/ef6), which can be used to migrate existing apps to ASP.NET Core.

It's easy to miss that, so I'm going to put a warning notice about out-of-date content on the page.
