### ISSUE TITLE
Request: mention that [Authorize] attributes are additive

### ISSUE THREAD

**Issue by david-acker** [dotnet/AspNetCore.Docs#29802]
Original question: [Confusing logic of [Authorize(Policy = xxx)] #49118](https://github.com/dotnet/aspnetcore/discussions/49118)

It's possible that I've just missed this, but I wasn't able to find an explicit mention in the docs that `[Authorize]` attributes work additively when applied to controllers and actions:

i.e. `MyAction` requires both policies `P1` and `P2`, as opposed to `P2` overriding `P1`.
```csharp
[Authorize(Policy = "P1")]
public class MyController
{
    [HttpGet]
    [Authorize(Policy = "P2")]
    public IActionResult MyAction() { ... }
}
```

Is this mentioned anywhere? If not, it might be good to describe with behavior along with some simple examples to help prevent confusion.

**Comment by guardrex** [comment]
Hello @david-acker ... It's likely that more work needs to be done in comments and examples.

It's currently addressed in the roles doc at https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-7.0#adding-role-checks. That example applies both attributes at the controller level, not at the controller and action method levels. It might be good to add an example there.

The claims doc does a good job of addressing it directly at https://learn.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-7.0#multiple-policy-evaluation.

The policies doc doesn't mention it in https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-7.0#apply-policies-to-mvc-controllers.

It's not necessary to address it for RP, per ...

> Policies can not be applied at the Razor Page handler level, they must be applied to the Page.

I'll toss up a quick PR for Rick to take a look at.

**Comment by david-acker** [comment]
Ah the example under "Multiple Policy Evaluation" on the claims doc is exactly what I was looking for. Completely missed that!

Thanks for putting up a PR for this!
