### ISSUE TITLE
UseHttps is inaccessible

### ISSUE THREAD

**Issue by megasuperlexa** [dotnet/AspNetCore.Docs#29815]
`ConfigureHttpsDefaults`  operates with `HttpsConnectionAdapterOptions` type.
Whereas `UseHttps` extension method is defined for `Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions` type.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#sni-with-servercertificateselector)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 132844](https://dev.azure.com/msft-skilling/Content/_workitems/edit/132844)

**Comment by tdykstra** [comment]
Where in the article is the code you are referring to?

**Comment by megasuperlexa** [comment]
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(serverOptions =>
{
    **serverOptions.ConfigureHttpsDefaults(listenOptions** =>
    {
        // ...
    });
});

I think this is just unfortunate naming that confused me. I thought `listenOptions` is listenOptions indeed, so it must have `UseHttps()`. Which it doesn't.

**Comment by tdykstra** [comment]
It looks like this issue is resolved, so I'm closing it. Feel free to reopen if you want to continue the discussion.
