### ISSUE TITLE
Wrong Language of Docs

### ISSUE THREAD

**Issue by ThomasHofbauerOasis** [dotnet/AspNetCore.Docs#29837]
[Enter feedback here]
Google only suggests German Docs. I only search using English prompts.
Here are the Issues:
- there is no need for a German translation because most of programming  related things(tutorials, forums etc.) is in English
- it should not be the only google result, there has to at least be the English Documentation linked
- switching to English is hidden completely at the bottom of the page which makes it really annoying

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=linux)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
cc @kgliang

**Comment by Rick-Anderson** [comment]
@ThomasHofbauerOasis  this issue should be created at https://github.com/MicrosoftDocs/feedback/issues as it pertains to all https://learn.microsoft.com/ docs. We can't address learn in this repo. Unfortunately, https://github.com/MicrosoftDocs/feedback/issues seems to be a bit bucket where issues are rarely addressed.
