### ISSUE TITLE
Incomplete instructions - FrameworkReference needed

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/AspNetCore.Docs#29865]
[Enter feedback here]
The nuget instructions on this page don't work. I believe the correct path is to remove the ASPNET related NugetPackages and add 
```<FrameworkReference Include="Microsoft.AspNetCore.App" />``` in an <ItemGroup> in the project csproj files.

The net7.0 nuget packages dont exist or are not available following the instructions in this page, so developers need to remove certain ones first, then add the FrameworkReference on affected projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`Microsoft.AspNetCore.App` hasn't been used since 2.2

**Comment by shadowfoxish** [comment]
Thank you very much for kindly reviewing this so quickly. 

The project I'm upgrading was a .NET Core 3.1 aspnetcore site, I moved from 3.1 to 6 following that documentation, and now doing 6->7 with this page and the combination of instructions between the two projects just don't work or are incomplete/missing something. (Im stuck with deprecated 2.x nuget packages, or missing Frameworks).

Following up on your comment; I guess, the Microsoft.AspNetCore.App package doesn't exist as a nuget package anymore, but that moniker is still used in VS
From a VS template project for .NET 7:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/12143535/a1c76aa7-cb04-40e6-9c69-0cf4f2fd8490)

Either way, there do not appear to be .NET 7 ASPNET nuget packages to actually upgrade. [Perhaps they were supposed to be removed in the 3.1->6 conversion? But then, what are they replaced with?]

The ones Nuget Package Manager suggests are v2 and are all marked deprecated. There also doesn't appear in Visual Studio directly to add a FrameworkReference to a project. 

I don't know what it is, but this particular documentation is clear as mud, at least for this 3.1->7 use case. I might just blow the project away and bring in my class files into one of the VS default template projects or something.
