### ISSUE TITLE
ASP.NET Core or just ASP.NET?

### ISSUE THREAD

**Issue by EduardoPires** [dotnet/AspNetCore.Docs#29888]
Why the MS still calling ASP.NET of ASP.NET Core if the .NET is no longer called .NET Core.

Can we just use the name ASP.NET without commit a mistake?

**Comment by Rick-Anderson** [comment]
That's not changing.

**Comment by EduardoPires** [comment]
So can I assume that ASP.NET will still be called "ASP.NET Core" for years to come?

I'm preparing a lot of content about ASP.NET (I'm an MVP) and I want to use the permanent name so I don't have to change it anymore.

**Comment by EduardoPires** [comment]
@Rick-Anderson your answer wasn't very clear to me, could you help me understand?
