### ISSUE TITLE
Interfaces/proxies for web+native device scenarios sample

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#29880]
The Blazor sample repo is at [`dotnet/blazor-samples`](https://github.com/dotnet/blazor-samples). I try to avoid creating sample apps because they're costly 💰💰💰 to keep up with release-to-release. I don't think its necessarily a concern. New Hybrid samples might fall to others to maintain.

Cross-refs:

* https://learn.microsoft.com/aspnet/core/blazor/hybrid/reuse-razor-components?#net-maui-blazor-platform-specific-code
* https://github.com/BethMassi/BethTimeUntil

Metadata:

* **Physical path:** *[e.g., `/blazor/hybrid/topic-url-segment`]*
* **Title:** *Typical limit is 59 characters + the technology name ("ASP.NET Core Blazor Hybrid")*
* **Author:** *Author's GH handle*
* **Description:** *Preferred range 115-145 characters long*
* **Framework version:** 
* **UID:** *Usually, matches the physical path [e.g., `blazor/hybrid/topic-url-segment`]*

**Comment by BethMassi** [comment]
@guardrex I'm going to take a stab at a simple example we can use and the step-by-step of setting it up.

**Comment by guardrex** [comment]
If you want to host it, create a folder for it here ...

https://github.com/dotnet/blazor-samples/tree/main/8.0

We'll see how updates go each year. Hopefully, there won't be wild amounts of churn such that the app breaks when I try to upgrade it.

For content, you can just paste it all into an issue comment here if you want me to set up the PR. Otherwise if you want to set up the PR, I'll answer any ❓ on our (many 😩) repo rules, conventions, and secret bylaws 😄.

**Comment by guardrex** [comment]
Oh ... and if you need write access to the Blazor samples repo, hit up Artak for that. Have him add you to the `aspnet-blazor-eng` team.

**Comment by BethMassi** [comment]
I'll probably just start with a personal repo and readme with the steps there. I'll keep you posted!

**Comment by BethMassi** [comment]
@guardrex I've vetted the design and this sample is good to go. We're using this as the basis for a new Solution template for .NET 9. However, this repo shows the manual steps needed to set this up yourself and how to deal with Blazor rendering modes in MAUI in .NET 8. It has branches for each of the interactivity settings. 

https://github.com/BethMassi/HybridSharedUI 

How do you recommend we proceed?

**Comment by guardrex** [comment]
That's great! Yes, I can get that set up into a PR within a week ... possibly even early next week ... and ping you for review and updates from there. Is that ok on timing?

**Comment by BethMassi** [comment]
Awesome! There's a couple small tweaks to the WebAsm per page component interactivity mode we just discussed so I'll be updating that branch later this afternoon.

**Comment by guardrex** [comment]
Ok ... cool. I'm going to be free .... well ..... ⛰️⛏️😅 ***free-er-ish*** ... early next week, Monday ... Tuesday. I'll try to get this taken care of quickly. If you end up needing additonal time, let me know, and I'll push it back into late next week.

**Comment by BethMassi** [comment]
Branch (and readme) is updated so should be good to go!

**Comment by guardrex** [comment]
@BethMassi ... Working on this now. We should discuss it for a sec ...

We don't use branches on the Blazor samples repo, but I see why you did so on your example repo. Also, it seems like you'll be taking issues/PRs on your repo. These factors lend themselves to cross-linking your repo to the article. After the article goes live, I imagine that you'll pull the content from the README in favor of a link to the new article that will contain all of that guidance.

If that all seems ok thus far ...

You used My-named solution/projects, and I've steered clear of My-named things across the Blazor docs. The article can go with My-naming or can drop it in favor of something else.

For example ...

* Solution: `MAUIBlazorWeb`
* MAUI: `MAUIBlazorWeb.MAUI`
* BWA: `MAUIBlazorWeb.Web`
* Shared: `MAUIBlazorWeb.Shared`

... or something else. Do you even have the time to change it? If not, let's go with the existing My-naming. I'm sure that my OCD can handle it! 😆 

One other docs NIT ... MS docs management prefers doc repos and sample repos avoid "`master`" default branch naming. Can you go with "`main`" instead? I have a feeling that we're going to get yelled at about it. 😨

**Comment by guardrex** [comment]
🤔 Thinking further ...

If we did away with the extra branches and rolled whatever changes those branches use into the article, then the sample could move entirely to the Blazor samples repo. In process of setting it up, I could adopt the new non-My naming for whatever we end up calling this sample app.

**Comment by BethMassi** [comment]
I'm good with that. Whatever you think is best.

**Comment by guardrex** [comment]
@BethMassi ... Update: It's going well. I have a good bit of the rough draft written, but ...

* I haven't added the solution creation steps yet. The steps aren't really useful for someone just looking to demo the setup. It's painful to go through all of it when the sample app is available for download. However, steps are virtually required for migrating an existing MAUI app to MAUI+BWA. I'll add the steps in a format that makes sense for that purpose.
* I haven't rolled in the other branches (render mode) pieces yet.

I hope to have the article done and up for review tomorrow (Wednesday).
