### ISSUE TITLE
Internal traffic should promote TLS as well.

### ISSUE THREAD

**Issue by marcin-sowa** [dotnet/AspNetCore.Docs#29897]
> Only the reverse proxy server requires an X.509 certificate, and that server can communicate with the app's servers on the internal network using plain HTTP.

Promoting HTTP(no TLS) traffic should be discouraged even in loopback network. TLS should be always used end2end.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89fbfe58-e10b-b59b-53f8-d04d3dc958af
* Version Independent ID: e57d3a17-0d5a-4586-b6cc-ca592454515c
* Content: [When to use a reverse proxy with the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/when-to-use-a-reverse-proxy.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 133308](https://dev.azure.com/msft-skilling/Content/_workitems/edit/133308)

**Comment by tdykstra** [comment]
@Tratcher Should we make any changes to the quoted statement in the doc?

**Comment by Tratcher** [comment]
Internal TLS is certainly better, but comes at a cost that many services are unwilling to pay (more CPU, memory, latency, and configuration overhead). @blowdart 

The statement can be clarified to:
> Only the reverse proxy server requires the X.509 certificate for the public domain(s), and that server can communicate with the app's servers on the internal network using plain HTTP or HTTPS with locally managed certificates. Internal HTTPS increases security but adds significant overhead.

**Comment by marcin-sowa** [comment]
Then let's work on proper documentation, how to setup TLS for internal traffic with performance in mind.

1. Overhead is negligible after session is established(handshake).
2. Session resumption.
3. Smaller key(1024, 2048) for internal traffic.
