### ISSUE TITLE
Problem details examples causes start-up errors

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#29902]
The Problem Details examples (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#problem-details and https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#customizeproblemdetails-operation) contain a mistake that results that the application doesn't start. Instead, it results in the following error:

```
Unhandled exception. System.InvalidOperationException: The service collection cannot be modified because it is read-only.
   at Microsoft.Extensions.DependencyInjection.ServiceCollection.ThrowReadOnlyException()
   at Microsoft.Extensions.DependencyInjection.ServiceCollection.System.Collections.Generic.ICollection<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>.Add(ServiceDescriptor item)
   at Microsoft.Extensions.DependencyInjection.ProblemDetailsServiceCollectionExtensions.AddProblemDetails(IServiceCollection services)
   at Program.<Main>$(String[] args) in C:\Users\timde\dev\ProblemDetailsExample\Program.cs:line 16
```

The problem is that problem details are added after the application is build:

```csharp
var app = builder.Build();        

// 👇 this line (should be invoked before builder.Build())
builder.Services.AddProblemDetails();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler();
    app.UseHsts();
}

app.UseStatusCodePages();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-7.0#custom-iproblemdetailswriter)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@timdeschryver thanks for notifying us. One of the rare times that @serpent5  got it wrong
https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/error-handling/samples/6.x/ErrorHandlingSample/Snippets

**Comment by Rick-Anderson** [comment]
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.

Check out [is:issue is:open label:"code help wanted" "](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22code+help+wanted%22+) and [is:open is:issue label:"Good first issue"](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22)

**Comment by serpent5** [comment]
> One of the rare times that @serpent5 got it wrong
> https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/error-handling/samples/6.x/ErrorHandlingSample/Snippets

It looks like `AddProblemDetails_Custom` wasn't in the original version, but was added to the 7.x version, which was after my time. 😅
