### ISSUE TITLE
Can't find Endpoint Explorer in Visual Studio 2022

### ISSUE THREAD

**Issue by nirwana101** [dotnet/AspNetCore.Docs#29901]
Hello,

This document tells me that there must be a Preview Feature in Visual Studio 2022 (from 17.6 Preview 6) called the Endpoints Explorer. That sounds pretty cool to me, so I want to use this.

But I cannot find it, not in the regular Visual Studio and also not in the Preview version of VS.

I read that there should be an option that you can enable, because the feature is still in preview, but I also cannot find that feature flag underneath Environment > Preview Features.

I also cannot find the tool-window underneath View > Other windows. 

Is this still an experimental feature? Did the experiment not reach the finishing line? 
I can hardly imagine, because this sounds like a cool new feature.

Please update the documentation to the current situation of this Endpoints Explorer (aka Web API Endpoints Explorer) feature.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Version Independent ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Content: [Use .http files in Visual Studio 2022](https://learn.microsoft.com/nl-nl/aspnet/core/test/http-files?view=aspnetcore-8.0#requests)
* Content Source: [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by sayedihashimi** [comment]
It was removed from Preview Features because it's no longer a preview feature. You should be able to see it by selecting View > Other Windows > Endpoints Explorer.

**Comment by tdykstra** [comment]
Thanks, I didn't see it there before but now I see it.
