### ISSUE TITLE
.NET 8: AOT: ADD DynamicallyAccessedMembers

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29913]
[DynamicallyAccessedMembers](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-3/#asp-net-core-and-native-aot-compatibility)

Link to [this](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#dynamicallyaccessedmembers)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8839fa1e-7c10-4b22-d03d-669906a2b9ea
* Version Independent ID: 8839fa1e-7c10-4b22-d03d-669906a2b9ea
* Content: [ASP.NET Core support for native AOT](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?branch=main&branchFallbackFrom=pr-en-us-29358&view=aspnetcore-8.0)
* Content Source: [aspnetcore/fundamentals/native-aot.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/native-aot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

---
[Associated WorkItem - 141713](https://dev.azure.com/msft-skilling/Content/_workitems/edit/141713)

**Comment by studentqiming** [comment]
haha、

**Comment by Rick-Anderson** [comment]
Added to https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0
