### ISSUE TITLE
Tutorial flow

### ISSUE THREAD

**Issue by jaymy2030** [dotnet/AspNetCore.Docs#29936]
[Enter feedback here]
Thank you for the documentation. It has been helpful and fun learning .Net. However, there is a little issue with the Nuget package installation flow. It reads as follows: "Visual Studio automatically installs the required packages."
1) I think it would be better to introduce the beginner to Nuget Packages briefly under that section.
2) Introduce the Dependency injection as Scaffolded Views will render data but from the DataContext class.
2) Provide the required packages to install as adding new scaffold Views will result in an error. That error is resolved after installing the required packages. So why not do this step instead of stirring the user to a step that gives an error?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-MVC-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion.
