### ISSUE TITLE
Add external links to Additional resources section

### ISSUE THREAD

**Issue by BoostMyTool** [dotnet/AspNetCore.Docs#29934]
Hello,
I have a YouTube channel about web development and programming languages: https://www.youtube.com/@BoostMyTool
I have many videos about ASP.NET, such as: https://youtu.be/t2h1UxXyqEc
I want to create more videos about ASP.NET and I am wondering if you could include links to my videos in your documentation web pages.
For example, if I make a detailed video about authentication without ASP.NET Identity, could you include the link in this page?
Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-7.0)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Unfortunately the bar for security links is very high and require a full audit by the security team. We don't have the resources for such an audit.
