### ISSUE TITLE
blocked: AOT CLI: remove install VS

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#29944]
<img width="419" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/828d4967-ea8b-42da-bc32-1cbff87316ee">

@mitchdenny  when can we remove this hacky step for CLI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68422c34-cfab-aefa-dc58-9a33f79e140d
* Version Independent ID: 68422c34-cfab-aefa-dc58-9a33f79e140d
* Content: [Tutorial: Publish an ASP.NET Core app using native AOT](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?view=aspnetcore-8.0&branch=pr-en-us-29938&tabs=netcore-cli)
* Content Source: [aspnetcore/fundamentals/aot/native-aot-tutorial.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/aot/native-aot-tutorial.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @mitchdenny
* Microsoft Alias: **midenn**

---
[Associated WorkItem - 143187](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143187)

**Comment by mitchdenny** [comment]
@Rick-Anderson ... I'm not sure on the answer to this one. I'm looping you into a thread.

**Comment by mitchdenny** [comment]
This remains a hard dependency (no current plans to fix).
