### ISSUE TITLE
Fix does not match 

### ISSUE THREAD

**Issue by sspates-starbucks** [dotnet/AspNetCore.Docs#29951]
The fix does not match the error, nor does it provide accurate details on what object to use on the built object for the IWebHostBuilder. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 876d1834-587a-1000-7222-05485e1e6a2c
* Version Independent ID: 876d1834-587a-1000-7222-05485e1e6a2c
* Content: [ASP0010: Do not use UseStartup with WebApplicationBuilder.WebHost](https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0010?view=aspnetcore-7.0)
* Content Source: [aspnetcore/diagnostics/asp0010.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0010.md)
* Product: **aspnet-core**
* GitHub Login: @safia
* Microsoft Alias: **safia**

**Comment by Rick-Anderson** [comment]
This is just a warning. What fix?

**Comment by sspates-starbucks** [comment]
@Rick-Anderson  In the "How to fix violations" section, the fix listed doesn't even correspond to the issue.  The fix asks to change to builder.Services.AddAuthentication(); which has nothing to do with builder.WebHost.UseStartup<Startup>(); so the fix in the page is useless.  I don't know what the proper fix would be for this so I can't submit a suggested update.
