### ISSUE TITLE
.NET from JS article enhancements

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#29985]
Enhance the guidance from https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md.

@pavelsavara ... It will take a little while to reach this issue due to the .NET 8 Blazor workload. I think we should cross-link at the top of this article for now to surface the *Configuring and hosting .NET WebAssembly applications* guidance. I'll come back and integrate guidance from `features.md` document into this article in a few months when I get past most of the .NET 8 work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efff6954-a035-d1da-5975-af04ff7c05ed
* Version Independent ID: efff6954-a035-d1da-5975-af04ff7c05ed
* Content: [Run .NET from JavaScript](https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/dotnet-interop.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/dotnet-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @pavelsavara
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pavelsavara ... Do you still want me to try and integrate the `features.md` coverage or create a new article from it?

Currently, it's cross-linked at the top of the existing article, where it states ...

> For additional guidance, see the \[Configuring and hosting .NET WebAssembly applications](https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md) guidance in the .NET Runtime (\`dotnet/runtime\`) GitHub repository. We plan to update this article to include new information in the cross-linked guidance in the latter part of 2023 or early 2024.

Cross-ref: https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-8.0

Even if you decide that cross-linking alone is fine, I'll need to remove that sentence from that paragraph. Otherwise, I'm not sure our plan for what to do with that content.

**Comment by pavelsavara** [comment]
Let's just remove the last sentence. Thank you.
