### ISSUE TITLE
Configure ASP.NET Core Data Protection

### ISSUE THREAD

**Issue by rwb196884** [dotnet/AspNetCore.Docs#30000]
What is `"<keyIdentifier>"`
What does it look like?
How do I get one?

This 'security' nonsense just stops things from working; it would be better to just turn it off.

**Comment by rwb196884** [comment]
Doesn't work
```
AspNetCoreDataProtectionOptions aspNetCoreDataProtectionOptions = new AspNetCoreDataProtectionOptions();
builder.Configuration.GetSection("AspNetCoreDataProtection").Bind(aspNetCoreDataProtectionOptions);
aspNetCoreDataProtectionOptions.BlobUriWithSasToken = "https://whatever.blob.core.windows.net/whatever-data-protection?sp=racwdl&st=2023-08-08T09:23:11Z&se=2123-08-08T17:23:11Z&spr=https&sv=2022-11-02&sr=c&sig=bwixpImR4CVWERyi%2BDtmqGxeCDVX9P0nrzNLaEaWOTQ%3D";
aspNetCoreDataProtectionOptions.KeyIdentifier = "https://whatever-key-vault.vault.azure.net/keys/whatever-data-protection/4a1114f79ad94cceaf6761796668c712";

string keyVaultName = builder.Configuration.GetValue<string>("KeyVaultName");
    string trimmedContentRootPath = builder.Environment.ContentRootPath.TrimEnd(Path.DirectorySeparatorChar);
if (!string.IsNullOrEmpty(keyVaultName))
{
    builder.Services.AddDataProtection()
        .PersistKeysToAzureBlobStorage(new Uri(aspNetCoreDataProtectionOptions.BlobUriWithSasToken))
        .ProtectKeysWithAzureKeyVault(new Uri(aspNetCoreDataProtectionOptions.KeyIdentifier), new DefaultAzureCredential())
        .SetApplicationName(trimmedContentRootPath);
}
```


RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f03a5230-d01e-0095-41db-c9b7b8000000 Time:2023-08-08T09:37:27.3109517Z Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.) ErrorCode: AuthenticationFailed Additional Information: AuthenticationErrorDetail: Signature did not match. String to sign used was racwdl 2023-08-08T09:23:11Z 2123-08-08T17:23:11Z /blob/whateverstorage/$root https 2022-11-02 c Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f03a5230-d01e-0095-41db-c9b7b8000000 Time:2023-08-08T09:37:27.3109517Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was racwdl 2023-08-08T09:23:11Z 2123-08-08T17:23:11Z /blob/truthliteintstorage/$root https 2022-11-02 c </AuthenticationErrorDetail></Error> Headers: Server: Microsoft-HTTPAPI/2.0 x-ms-request-id: f03a5230-d01e-0095-41db-c9b7b8000000 x-ms-error-code: AuthenticationFailed Access-Control-Allow-Origin: * Date: Tue, 08 Aug 2023 09:37:27 GMT Content-Length: 532 Content-Type: application/xml

    Azure.Storage.Blobs.BlobRestClient.DownloadAsync(string snapshot, string versionId, Nullable<int> timeout, string range, string leaseId, Nullable<bool> rangeGetContentMD5, Nullable<bool> rangeGetContentCRC64, string encryptionKey, string encryptionKeySha256, Nullable<EncryptionAlgorithmTypeInternal> encryptionAlgorithm, Nullable<DateTimeOffset> ifModifiedSince, Nullable<DateTimeOffset> ifUnmodifiedSince, string ifMatch, string ifNoneMatch, string ifTags, CancellationToken cancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, bool rangeGetContentHash, long startOffset, bool async, CancellationToken cancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, bool rangeGetContentHash, IProgress<long> progressHandler, string operationName, bool async, CancellationToken cancellationToken)
    Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(Stream destination, BlobRequestConditions conditions, CancellationToken cancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync(Stream destination, BlobRequestConditions conditions, IProgress<long> progressHandler, StorageTransferOptions transferOptions, bool async, CancellationToken cancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination, BlobRequestConditions conditions, StorageTransferOptions transferOptions, CancellationToken cancellationToken)
    Azure.Extensions.AspNetCore.DataProtection.Blobs.AzureBlobXmlRepository.GetLatestDataAsync()
    Azure.Extensions.AspNetCore.DataProtection.Blobs.AzureBlobXmlRepository.GetAllElementsAsync()
    Azure.Extensions.AspNetCore.DataProtection.Blobs.AzureBlobXmlRepository.GetAllElements()
    Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
    Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
    Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, bool forceRefresh)
    Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(byte[] plaintext)

**Comment by guardrex** [comment]
Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
