### ISSUE TITLE
No mention to HttpResults

### ISSUE THREAD

**Issue by lucaslra** [dotnet/AspNetCore.Docs#30001]
Hi,

Despite the `HttpResults` types introduction in .NET 6, they are only first referenced on the .NET 7 page of this document.

Is there a particular reason for that? I would like to add the section to the .NET 6 document page, but I am not sure if it belongs there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core web API](https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-6.0)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @lucaslra ... The API came in at 7.0 ... https://github.com/dotnet/aspnetcore/pull/41161.
