### ISSUE TITLE
Dynamic culture approach updates 8.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#30002]
This might not be reached until after RTM.

Two tasks ...

* [x] **Resolved on #30576**: The dynamic approach server-side relies on the loc cookie approach and `_Host.cshtml`. I've versioned that whole section out for <8.0. We need to update the approach for BWAs with the `App` component.
* [x] **Resolved on #30860**: Fix the server-side dynamic culture section, which had its `App` component code updated but not its `Program` file (and other instructions) updated.
* [x] Since it's common for localized apps to permit culture changes from anywhere in the app (via for example what we show using the `MainLayout` component), the dynamic approaches should be integrated for BWA client- and server-side user culture changes. Perhaps, the BWA should adopt a state preservation service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7c51d-1839-1849-813a-23c4d21c64ae
* Version Independent ID: d6f07538-228e-9f96-680f-6c324caf11d6
* Content: [ASP.NET Core Blazor globalization and localization](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/globalization-localization.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by amather** [comment]
I was just about to open a new issue, but this one seems to be a god fit as well:

Both, traditional .NET developers as well as traditional web developers, are used to being able to switch the culture at runtime, e.g. just re-render UI components after applying a new culture information.

With Blazor WebAssembly client apps this is different, as the culture has to be set before the Host runs (for whatever reason). 

Imho, this is a crucial limitation (of BWA) the documentation fails to mention.

Switching culture the way the documentation correctly shows, has severe impact on user experience (takes very long as the page has to refresh, i.e. the runtime has to restart vs simple component re-render). So newcomers to Blazor WebAssembly like me, will think that the approach taken by the documentation isn't the best way to do it, start implementing a culture switch at runtime and will waste hours on trying to find out why it's not working as expected (there's no error message at runtime)...

So mentioning/warning that it's a requirement for BWA client apps to (*dynamically* or *statically*) set the culture information before the host runs (before `WebAssemblyHost.RunAsync()` is called) would be nice!
