### ISSUE TITLE
Blazor wasm AuthorizeView error in docs

### ISSUE THREAD

**Issue by TDroogers** [dotnet/AspNetCore.Docs#30005]
According to issue https://github.com/dotnet/aspnetcore/issues/41011 the following docs are incorrect.

```
<AuthorizeView Roles="Admin">
    <AuthorizeView Roles="Developer">
        ...
    </AuthorizeView>
</AuthorizeView>
```

This gives the following error: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error	RZ9999	The child content element 'ChildContent' of component 'AuthorizeView' uses the same parameter name ('context') as enclosing child content element 'ChildContent' of component 'AuthorizeView'. Specify the parameter name like: '<ChildContent Context="another_name"> to resolve the ambiguity	project	C:\Users\Name\source\repos\project\src\Client\CSC	1	

should be:

```
<AuthorizeView Roles="Admin">
    <AuthorizeView Roles="Developer" Context="SomeOtherName">
        ...
    </AuthorizeView>
</AuthorizeView>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 217bc7a2-94db-e23b-9e74-7ad48b884462
* Version Independent ID: 071763aa-0173-af10-9634-9c50a4d5868b
* Content: [ASP.NET Core Blazor WebAssembly with Azure Active Directory groups and roles](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/azure-active-directory-groups-and-roles?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/azure-active-directory-groups-and-roles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @TDroogers ... Yes, we have the correct approach here ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-7.0#role-based-and-policy-based-authorization

... but it wasn't updated where you found it. I'll take care of it.

**Comment by TDroogers** [comment]
Thanks!
