### ISSUE TITLE
Error in code sample

### ISSUE THREAD

**Issue by nlips** [dotnet/AspNetCore.Docs#30019]
The property Options is not defined in the class EmailSender
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nlips ... Can you provide the full stack trace? I don't think that will be enough info for Rick to go on, given that the property is defined in the class with ...

> public AuthMessageSenderOptions Options { get; } //Set with Secret Manager.

**Comment by nlips** [comment]
Yes, sorry. I didn't see it!
