### ISSUE TITLE
Before and after targets are wrong for filesystem web publish

### ISSUE THREAD

**Issue by BadgerB1** [dotnet/AspNetCore.Docs#30013]
This page should be updated to say that filesystem web publish doesn't have a BeforePublish or AfterPublish target.  The only target that the filesystem publish has is GatherAllFilesToPublish and that seems to end before the publishing is actually performed.  The copying seems to be outside of a target somehow.  

Please clarify and offer any other way to do something after or before publishing.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles (.pubxml) for ASP.NET Core app deployment](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-7.0#publish-profiles)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 147380](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147380)

**Comment by tdykstra** [comment]
@sayedihashimi Who can we direct .pubxml questions to?

**Comment by sayedihashimi** [comment]
Hi @tdykstra, for pubxml @AngelosP or @vijayrkn should be able to assist.

**Comment by tdykstra** [comment]
@AngelosP or @vijayrkn can you help with this question?

**Comment by Rick-Anderson** [comment]
> This page should be updated to say that filesystem web publish doesn't have a BeforePublish or AfterPublish target. The only target that the filesystem publish has is GatherAllFilesToPublish and that seems to end before the publishing is actually performed. The copying seems to be outside of a target somehow.
> 
> Please clarify and offer any other way to do something after or before publishing.
> 

Just tested and `BeforePublish `  and  `AfterPublish`


```
<Project>
  <PropertyGroup>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <ResourceId>/subscriptions/a8a5e23a-c020-403d-9450-45d5a7b98628/resourcegroups/TP_RG/providers/Microsoft.Web/sites/TP22</ResourceId>
    <ResourceGroup>TP_RG</ResourceGroup>
    <PublishProvider>AzureWebSite</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish>https://tp22.azurewebsites.net</SiteUrlToLaunchAfterPublish>
    <LaunchSiteAfterPublish>true</LaunchSiteAfterPublish>
    <ExcludeApp_Data>false</ExcludeApp_Data>
    <ProjectGuid>3128b417-8530-4717-bd22-cd6021aa346e</ProjectGuid>
    <MSDeployServiceURL>tp22.scm.azurewebsites.net:443</MSDeployServiceURL>
    <DeployIisAppPath>TP22</DeployIisAppPath>
    <RemoteSitePhysicalPath />
    <SkipExtraFilesOnServer>true</SkipExtraFilesOnServer>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>true</EnableMSDeployBackup>
    <EnableMsDeployAppOffline>true</EnableMsDeployAppOffline>
    <UserName />
    <_SavePWD>false</_SavePWD>
    <_DestinationType>AzureWebSite</_DestinationType>
    <InstallAspNetCoreSiteExtension>false</InstallAspNetCoreSiteExtension>
  </PropertyGroup>
	<Target Name="CustomActionsBeforePublish" BeforeTargets="BeforePublish">
		<Message Text="Inside BeforePublish" Importance="high" />
	</Target>
	<Target Name="CustomActionsAfterPublish" AfterTargets="AfterPublish">
		<Message Text="Inside AfterPublish" Importance="high" />
	</Target>
</Project>
```
