### ISSUE TITLE
 Add AddAntiforgery to minimal APIs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30016]
See:

*  Source for this document [middleware include file](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/includes/middleware.md)
* Blog [Antiforgery middleware](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-7/#antiforgery-middleware)
* PR [Add support for anti-forgery middleware](https://github.com/dotnet/aspnetcore/pull/49233)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e126168-04ac-f820-baad-c336729e4da5
* Version Independent ID: 8e126168-04ac-f820-baad-c336729e4da5
* Content: [Middleware with Minimal API applications](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/middleware.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/middleware.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @BrennanConroy
* Microsoft Alias: **brecon**

---
[Associated WorkItem - 145864](https://dev.azure.com/msft-skilling/Content/_workitems/edit/145864)

**Comment by Rick-Anderson** [comment]
@martincostello @Kahbazi can you explain the following? 

* [CORS](https://developer.mozilla.org/docs/Web/HTTP/CORS) is an [HTTP](https://developer.mozilla.org/en-US/docs/Glossary/HTTP)-header based mechanism, it doesn't use tokens. Why are tokens used here?
* See [Middleware in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-7.0)
  ```
app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
```

Is that replaced by:

```
var builder = WebApplication.CreateBuilder();

builder.Services.AddAntiforgery();

var app = builder.Build();

// Implicitly added by WebApplicationBuilder
// app.UseAntiforgery();

app.Run();
```

**Comment by Rick-Anderson** [comment]
The exception explains the token
AntiforgeryValidationException: The required antiforgery request token was not provided in either form field "__RequestVerificationToken" or header value "RequestVerificationToken".

So `builder.Services.AddAntiforgery()` provides a token mechanism tor CORS. This still needs more explaining.

**Comment by guardrex** [comment]
@Rick-Anderson @tdykstra @wadepickett  ... I'm working on the Blazor forms/antiforgery bits now, and I hope to have it wrapped up by EOD Tuesday. I'm working with the Antiforgery topic in the main doc set security node for some of it. I recommend holding off on any general antiforgery/forms work that would touch that topic until I get my PR merged.

**Comment by captainsafia** [comment]
> See [Middleware in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-
> apis/middleware?view=aspnetcore-7.0)
> app.UseCors();
> app.UseAuthentication();
> app.UseAuthorization();
> Is that replaced by:

This section should stay the same. It is meant to document how users should register middleware if they want them to run in a particular order.

As of .NET 8 Preview 7, the minimal hosting model will automatically register the following middleware in this order.

1. UseRouting
2. UseAuthentication
3. UseAuthorization
4. UseAntiforgery

The code-snippet documents what the user would need to do if they wanted to add CORS to their application. CORS needs to run _before_ authentication and authorization since we don't want to read any claims on the request if it's cross-origin.

> So builder.Services.AddAntiforgery() provides a token mechanism for CORS. This still needs more explaining.

The anti-forgery services are unrelated to CORS. They provide APIs for validating the anti-forgery tokens on the request.
