### ISSUE TITLE
Tutorial: Create a minimal API with ASP.NET Core

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#30026]
A student asked me a question today about the minimal API tutorial, and I wasn't able to provide a good answer.

On the delete action, the API returns the todo entity.
I expect this to return a `Results.NoContent()` instead.

```cs
app.MapDelete("/todoitems/{id}", async (int id, TodoDb db) =>
{
    if (await db.Todos.FindAsync(id) is Todo todo)
    {
        db.Todos.Remove(todo);
        await db.SaveChangesAsync();
        // 👇
        return Results.Ok(todo);
    }

    return Results.NotFound();
});
``` 

Some observations why I think this snippet within the Minimal API docs is wrong:

- while reading the documentation, it seems like the overview table at the top of the page also expects this behavior.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/28659384/690d57df-2ae4-4300-8875-885270e48d56)

- the [examples within controller-based APIs](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-7.0&tabs=visual-studio#the-deletetodoitem-method) also use `NoContent()` as the return value

I raised this issue because it seems like the snippet is wrong, and I also find it a better practice to use `NoContent()` as the return value for a delete action.

If accepted, I can update the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab408035-6313-a183-9940-32de00e0e977
* Version Independent ID: ab408035-6313-a183-9940-32de00e0e977
* Content: [Tutorial: Create a minimal API with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/min-web-api.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 147251](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147251)

**Comment by wadepickett** [comment]
Thanks @timdeschryver for bringing this to light, it looks like the topic was originally created that way and carried forward.  :(

The code example is pulled into the docs from the following code file, and it is this file that needs the change:
https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api/samples/7.x/todo/Program.cs

If you would like to make the pull request yourself, that's great!  If you don't have time and would like us to fix it, I will queue it up to get it fixed in our very next sprint.

**Comment by wadepickett** [comment]
@tdykstra spotted the PR for this and helped with some updates, so I assigned it to him so he can get some credit here. Thanks Tom. :)
