### ISSUE TITLE
The sequence is broken for me - there is no startup.cs created

### ISSUE THREAD

**Issue by WayneMRoseberry** [dotnet/AspNetCore.Docs#30028]
Following the sequence specified on this page, there is no "startup.cs" file created in my project.
When clicking "Publish" there is an error saying that "AddSwaggerGen" needs to be in the Configure method of the Startup.cs file

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d70145c2-e2ba-77fb-050d-44d18354e370
* Version Independent ID: 19c98d91-e5fe-5832-6c75-23e677e469a3
* Content: [Publish an ASP.NET Core web API to Azure API Management with Visual Studio](https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-7.0)
* Content Source: [aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/publish-to-azure-api-management-using-vs.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by guardrex** [comment]
Hello @WayneMRoseberry ... Are you looking at an earlier version of the article. Try the current release version ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-api-management-using-vs?view=aspnetcore-7.0
