### ISSUE TITLE
.NET 8: Support for tokens in lieu of cookies for Identity sign on

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30066]
[Identity](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-7/#identity)

Related to #29363

---
[Associated WorkItem - 159475](https://dev.azure.com/msft-skilling/Content/_workitems/edit/159475)

**Comment by guardrex** [comment]
@JeremyLikness ... Are you planning on documenting `MapIdentityApi<TUser>()` and API endpoints (per issue #29363) and this one (token support) for the *Client-side development* node (SPA apps) as part of your work?

If not, I can work on these, but it will take me two to four weeks to reach them given the Blazor workload.

**Comment by JeremyLikness** [comment]
@guardrex best person to coordinate with is @halter73 for the API endpoint docs.
