### ISSUE TITLE
Start vs. Run, the difference is not clear

### ISSUE THREAD

**Issue by peterdrier** [dotnet/AspNetCore.Docs#30070]
Linguistically, "Start" and "Run" are very similar programming concepts.  Given the documentation here, it's not obvious what the difference between them (and their various flavors) is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 147811](https://dev.azure.com/msft-skilling/Content/_workitems/edit/147811)

**Comment by tdykstra** [comment]
@peterdrier Thanks for the question.  I'm adding this text to the article:

>The difference between `Run*` and `Start*` methods is that `Run*` methods wait for the host to complete before returning, whereas `Start*` methods return immediately. The `Run*` methods are typically used in console apps, whereas the `Start*` methods are typically used in long-running services.
