### ISSUE TITLE
Clarify use of magic number' -2147024864 in code sample

### ISSUE THREAD

**Issue by fdcastel** [dotnet/AspNetCore.Docs#30080]
In two different samples the condition 

```csharp
ex.HResult != -2147024864
```

is checked without a better explanation of what is doing. It is probably the Windows code for "file is locked".

Questions:

- Is this Windows-only? Or it will work across different platforms?
- What is the meaning of this error code?

Related: 

- [this issue](https://github.com/dotnet/runtime/issues/926) (which seems to be an open wound in dotnet for year now😢)
- [this answer](https://stackoverflow.com/questions/9293227/how-to-check-if-ioexception-is-not-enough-disk-space-exception-type/9294382#9294382) in StackOverflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9310e951-5185-4c31-064d-3a151acc17cf
* Version Independent ID: 42bc4b7b-2a1c-0248-2740-0decdda6000c
* Content: [Detect changes with change tokens in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/change-tokens.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/change-tokens.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by fdcastel** [comment]
> it would only mean that the code needs to wait for the three checks to occur when a locked-file condition is present 

BTW: I consider this an improvement over the original code. Since the file can be unlocked during the retries.

**Comment by guardrex** [comment]
Yes ... that's right. That would be better. I don't know which of the goober doc authors did that ... ***cough*** ***cough*** 🦖 ***cough*** ... but they should be sliced up for the butcher's counter 👨‍🍳🔪🥩 ... 😨.

> Since the file can be unlocked during the retries.

It was done on purpose, and it was signed off by one of the top .NET engineers on the product unit. I'm sure we had some rationale for it. We probably were thinking that it's unlikely that it will unlock in that period.

This article was written six years ago in ancient .NET times 👴 before indoor plumbing and the wheel was invented 😆, so why we did it this way is lost to space and time.

**Comment by guardrex** [comment]
Rick, I have a few minutes here ... done with Blazor bits for the day. I'll knock this out. It's my bad anyway! 😆
