### ISSUE TITLE
have error in dotnet core 7 minimal api

### ISSUE THREAD

**Issue by Arman-Espiar** [dotnet/AspNetCore.Docs#30100]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-7.0

In dot net core 7 need register _builder.Services.AddMemoryCache()_ to **program.cs** to prevent error:

> Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: OrchardCore.Localization.ILocalizationManager Lifetime: Singleton ImplementationType: OrchardCore.Localization.LocalizationManager': Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'OrchardCore.Localization.LocalizationManager'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Localization.IStringLocalizerFactory Lifetime: Singleton ImplementationType: OrchardCore.Localization.PortableObject.PortableObjectStringLocalizerFactory': Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'OrchardCore.Localization.LocalizationManager'.) (Error while validating the service descriptor 'ServiceType: Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizerFactory Lifetime: Singleton ImplementationType: OrchardCore.Localization.PortableObject.PortableObjectHtmlLocalizerFactory': Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'OrchardCore.Localization.LocalizationManager'.)

**Comment by guardrex** [comment]
Hello @Arman-Espiar ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">
