### ISSUE TITLE
8.0 Update: Prerequisites outdated version info

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#30120]
Hi, when I was moving embedded snippets to projects files for a gRPC page I also took the opportunity to taker a closer look into gRPC (win-win!). 
I noticed that the referenced page in this issue is using outdated versions for the Prerequisites.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/28659384/2c108915-9076-4d5a-a5e1-9ca808a8531b)

If desired I can update these versions based on the selected ASP.NET version.

**The following is added by wadepickett:**

- Versions 5-8 need to point to the correct prereq include.
- This aspnetcore/includes/net-prereqs-vs-6.0.md prereq include needs to add the .NET 6.0 SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#configure-grpc)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Thanks @timdeschryver, we will fix.  I appreciate that you pointed this out.
