### ISSUE TITLE
searchString is absent

### ISSUE THREAD

**Issue by Haroonabdulrazaq** [dotnet/AspNetCore.Docs#30132]
[Enter feedback here]
Search String has not been implemented at this stage Part 4, Search String was introduced in Part 7. Learners might run into syntax errors if they copy and paste the code.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/50737259/e5037b5c-5f0a-48f2-9505-ab466874d9dd)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Part 4, add a model to an ASP.NET Core MVC app](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

---
[Associated WorkItem - 155414](https://dev.azure.com/msft-skilling/Content/_workitems/edit/155414)

**Comment by Rick-Anderson** [comment]
@wadepickett  pls fix

**Comment by wadepickett** [comment]
Verified as in my recent PR.
I looked through all versions and tabs of this topic just in case.
Fixed by #30192
