### ISSUE TITLE
Screen reader accessibility and keyboard shortcuts for HTTP files in Visual Studio

### ISSUE THREAD

**Issue by Luke-Robinett** [dotnet/AspNetCore.Docs#30149]
I'm blind and use a screen reader to access my computer. Postman has known accessibility challenges so I'm excited to learn about the HTTP files feature in Visual Studio as a possible screen reader-friendly alternative. I'd like to request shortcut key bindings be added when working in an HTTP file:
1. Switch between HTTP text editor and response/result pane (couldn't find a way to focus to this using the keyboard.)
2. Accessing the endpoint browser and any other toolbars or sections of the HTTP editor interface
In addition, some screen reader alerting would be helpful:
* Announce when request sent.
* Announce when response received.
* Announce when error occurs.
* Any other dynamic changes to the VS HTTP editor that would be useful for the operator to know about.

If some of this is already available, please share documentation for it or feel free to direct me to that documentation if it already exists. I couldn't find anything specifically about using the new HTTP files feature with a screen reader. Thanks!

Also, just noticed that nodes in the endpoint browser are not being verbalized by their text content. When I go to the endpoint browser and use the up and down keys to traverse it's items, I hear things like this being spoken by the screen reader (NVDA):
"Microsoft.WebTools.ProjectSystem.Components.Endpoints.Nodes.ProjectTreeNode."
A similar issue occurs in the request list dropdown accessed by pressing F4. Once there, I hear this announced for the selected item in the dropdown list:
"Microsoft.WebTools.Languages.Rest.VS.Margins.RequestViewModel."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Version Independent ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Content: [Use .http files in Visual Studio 2022](https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0)
* Content Source: [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by sayedihashimi** [comment]
@tdykstra is it possible to migrate this to the VS developer community or does that need to be done manually? I think this would be better tracked there.

**Comment by tdykstra** [comment]
That needs to be done manually. I'll create a couple of feature requests there.

**Comment by sayedihashimi** [comment]
Thanks Tom.

**Comment by tdykstra** [comment]
I made 3 entries into https://developercommunity.visualstudio.com/VisualStudio

* [screen reader alerting](https://developercommunity.visualstudio.com/t/Screen-reader-alerting-when-working-with/10467752?q=tdykstra%40microsoft.com&sort=newest&ref=native&refTime=1694834088036&refUserId=5b8bd876-8982-4590-8f01-5c1643b1a72c)
* [shortcut keys](https://developercommunity.visualstudio.com/t/Shortcut-key-bindings-needed-when-workin/10467751?q=tdykstra%40microsoft.com&sort=newest&ref=native&refTime=1694834088036&refUserId=5b8bd876-8982-4590-8f01-5c1643b1a72c)
* [verbalize nodes by text](https://developercommunity.visualstudio.com/t/Nodes-in-the-endpoint-browser-are-not-be/10467749?q=tdykstra%40microsoft.com&sort=newest&ref=native&refTime=1694834088038&refUserId=5b8bd876-8982-4590-8f01-5c1643b1a72c)

**Comment by tdykstra** [comment]
Closing, as these issues are now tracked in Developer Community.

**Comment by tdykstra** [comment]
One of this issue's requests is being implemented: https://developercommunity.visualstudio.com/t/Nodes-in-the-endpoint-browser-are-not-be/10467749
