### ISSUE TITLE
Incorrect code formatting in Tab.razor example

### ISSUE THREAD

**Issue by TheAtomicOption** [dotnet/AspNetCore.Docs#30157]
In the "Pass data across a component hierarchy" section, the code for Tab.razor has incorrect syntax highlighting for the closing html tags and much of the `@code { }` block. 

This appears to be a failure to switch back to expecting html from expecting csharp when parsing the closing quote at the end of ` class="nav-link @TitleCssClass"`. Changing to ` class="nav-link @(TitleCssClass)"` might avoid this parsing error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7ba96d-bae0-96ee-e76a-71c6e5f4c23f
* Version Independent ID: 5fe884b8-51e1-1b91-57f8-522ff0b7890c
* Content: [ASP.NET Core Blazor cascading values and parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/components/cascading-values-and-parameters.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/cascading-values-and-parameters.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report, @TheAtomicOption. I'll take a look on Monday morning (or this weekend) and get it fixed.

**Comment by guardrex** [comment]
@Rick-Anderson ... Was this opened internally? If so, should I leave this open just for tracking? I fear that if I close it that I'll forget to check back in a few months to see if this has been fixed.
