### ISSUE TITLE
Update ASP.NET Core SPA content for .NET 8

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#30155]
In .NET 8 we've removed the ASP.NET Core SPA templates from the .NET SDK in favor of the newer Visual Studio SPA templates. We need to update the ASP.NET Core SPA docs for .NET 8 docs accordingly, linking to the Visual Studio SPA docs as appropriate:

- [JavaScript and TypeScript in Visual Studio overview](https://learn.microsoft.com/visualstudio/javascript/javascript-in-visual-studio)
- [Tutorial: Create an ASP.NET Core app with React in Visual Studio](https://learn.microsoft.com/visualstudio/javascript/tutorial-asp-net-core-with-react)
- [Tutorial: Create an ASP.NET Core app with Angular in Visual Studio](https://learn.microsoft.com/visualstudio/javascript/tutorial-asp-net-core-with-angular)
- [Tutorial: Create an ASP.NET Core app with Vue in Visual Studio](https://learn.microsoft.com/visualstudio/javascript/tutorial-asp-net-core-with-vue)
- [Tutorial: Create an ASP.NET Core app with TypeScript in Visual Studio](https://learn.microsoft.com/visualstudio/javascript/tutorial-aspnet-with-typescript)

@joj @jiayac

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1ffb8e1-215c-c148-0b28-da0d62665fa4
* Version Independent ID: c1ffb8e1-215c-c148-0b28-da0d62665fa4
* Content: [Overview of Single Page Applications (SPA) in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?view=aspnetcore-7.0)
* Content Source: [aspnetcore/client-side/spa/intro.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/intro.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **jacalvar**

---
[Associated WorkItem - 149989](https://dev.azure.com/msft-skilling/Content/_workitems/edit/149989)

**Comment by milkshakeuk** [comment]
@danroth27 Why were the spa templates removed from the dotnet SDK? Now only people with visual studio can "new up" these projects, seems a little unfair, can anyone point me to a dotnet issue or rational for this?

**Comment by danroth27** [comment]
Hi @milkshakeuk. We removed the old SPA templates from the .NET SDK because the new ones in Visual Studio are significantly more features rich:

- They support both JavaScript & Typescript.
- There are templates for Angular, React, & Vue.
- They stay up to date with the latest Vite or Angular CLIs.
- They are setup with the new JavaScript SDK and project system.

It didn't really make sense to support two separate sets of SPA templates and we've long wanted to get out of the business of trying to keep the .NET SDK SPA templates up to date with the latest JavaScript versions.

It's true that the new templates can currently only be created from within VS, but you can build, run, and publish them from the .NET CLI. To be able to create these templates from the .NET CLI, we'd need to publish a .NET template pack for them. We've discussed doing this in the past, but we'd need to figure out how to handle the logic the templates use to invoke the frontend CLIs to generate their content. If creating these templates from the .NET CLI is something you'd like to see supported, please open a Visual Studio Feedback issue with this request and we'll investigate.

**Comment by milkshakeuk** [comment]
@danroth27 thank you for the response, couldn't the same logic the visual studio template uses to generate the cli content be used in the dotnet SDK template?

**Comment by danroth27** [comment]
@milkshakeuk There are some limitations of the .NET templating engine that currently make that a bit hard to do. But we can always improve the templating engine for this purpose. It's worth considering. If you could submit this feedback, we can investigate with the VS folks.

**Comment by elOG8** [comment]
Hello @danroth27, will be available PWA option in new template Blazor Web App... I only see is available in web assembly available.
Thanks

**Comment by snmps2** [comment]
Hay
