### ISSUE TITLE
Missing information on where to place .cs files

### ISSUE THREAD

**Issue by marcospgp** [dotnet/AspNetCore.Docs#30164]
Missing information on where to place .cs files

Project template only includes a root-level .cs file, the rest is .razor and .razor.css

No guidance on where to place .cs files one may need to create

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d31248d7-d2c2-1a17-3173-889a0d9bb6e8
* Version Independent ID: 6f27ff37-6b3a-57f5-353a-5cf5aabba7cf
* Content: [ASP.NET Core Blazor project structure](https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/project-structure.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @marcospgp ... That's because that's your call, just like it would be for any non-Blazor ASP.NET Core project. Outside of SxS files for components, such as a stylesheet (`.razor.css`), a JS file (`.razor.js`), or code-behind file (`.razor.cs`) that would be SxS with the component `.razor` file, it's up to you for everything else. We don't have any firm recommendations, and devs use a number of layouts for their app's C# files.

**Comment by marcospgp** [comment]
Sounds good @guardrex, thanks for considering this. At this time according to the docs it's unclear whether adding custom `.cs` files is actually encouraged, so I think some additional guidance would be great (not necessarily prescriptive). Cheers!

**Comment by guardrex** [comment]
I've finally worked my way around to this. Unfortunately, there isn't anything that we can really say on this subject that would appease all developer philosophies. The second the article says 'do it this way,' we're going to get devs complaining that they don't like it. C#/.NET works on a namespace basis; and outside of that, you can place the files virtually anywhere you want ... and name them any way that you want. There are probably dozens of app layout philosophies out there. It's truly up to the developer. Closing on that basis.
