### ISSUE TITLE
Improve and fix VS Code new project instruction across getting started tutorials

### ISSUE THREAD

**Issue by EACUAMBA** [dotnet/AspNetCore.Docs#30163]
In Visual Studio Code  section **Run the app** the first run says to use the combination of **control + F5** but it does not run the app, is does nothing, the right should be only **F5** (with debugger) because in the first run the Visual Studio Code will build the project .vscode directory, so the subsequents runs can use **Control + F5**

--- Added by WadePickett
Expanded this to reviewing and improving all the getting started tutorials for setup and run steps for VS Code.  (Except a separate one was made for Blazor getting started)

Move common instruction where I can into an included.

Address steps from new project, to accept authors, to accept assets to create the .vscode folder with generated launch.json and tasks.json files and verify through Ctrl + F5 step, the first run of the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-7.0&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks very much @EACUAMBA for taking the time to point out this issue.  We will get it fixed and I will look for other instances of this issue in the tutorials.

**Comment by EACUAMBA** [comment]
No problem, it's a pleasure help to benefit everyone.

**Comment by wadepickett** [comment]
There are missing steps in the tutorial to add but a little different than originally thought: 
1. `code -r RazorPagesMovie` opens the newly created project folder in VS Code.
2. The **Trust the authors?** dialog is displayed and trusted.
3. A prompt to add the required assets to build and debug appears but is not mentioned in the tutorial and should be.  

    - After selecting**Yes**, Visual Studio Code automatically adds the `.vscode` folder with generated `launch.json` and `tasks.json` files.
4. Selecting Ctrl+F5 results in the VS Code building and running without debugging.

There are at least two common cases and one outlier I can see where that prompt to create build and debug assets would not appear, (provided the prerequisites were followed), that would result in Ctrl+F5 (or F5) not immediately building and running the project:

1. C# Dev Kit is installed: It can cause a conflict where the prompt of debug assets will not occur. (Just tested that, still occurs).
2. The user accidentally or intentionally selected **Don't Ask Again** at the build assets in the past, so no it will no longer prompt.
3. (Not as common but folks have done this) Following the tutorial, the 2nd command line instruction `code -r RazorPagesMovie` was accidentally not run with a return.

The fix needed I think is to:
1.  Call out the add assets prompt, which occurs after the **trust the authors** dialog.
2.  Add something like the following in case the prompt is unable to run: " If this step was missed or unavailable, select **View** > **Command Palette** and enter *.NET: Generate Assets for Build and Debug*.

**Comment by wadepickett** [comment]
Ended up reviewing, and updating, testing, 6 tutorials, versions 5 through 8 of each.

**Comment by EACUAMBA** [comment]
> Expanded this to reviewing, updating, testing, 6 tutorials, versions 5 through 8 of each, and using an include where we can to keep these consistant.

It will help a lot of people, when that stuck in this situation.
