### ISSUE TITLE
Change links to point to 6.0 sample and other minor changes

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/AspNetCore.Docs#30168]
I suggest the following changes for [Introduction to Razor Pages in ASP.NET Core 6.0](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio-code) or above 

1. Add an explanation what will be created at the start of [Create a Razor Pages project](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio-code#create-a-razor-pages-project). Example:  _This tutorial creates a contact form with an in memory database_  
2. Add the information that the demo is created in the folder _RazorPagesContacts_ 
3. Replace `Startup.cs` with `Program.cs` and link to [Razor Page Contact sample 6.0](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts) instead of 3.0
4. Minor change: Add `dotnet add package Microsoft.EntityFrameworkCore.InMemory --version 6.*` as a convenience

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-6.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorpages**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> Replace Startup.cs with Program.cs and link to [Razor Page Contact sample 6.0](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/razor-pages/index/6.0sample/RazorPagesContacts) instead of 3.0

@tdykstra can you fix that? 

The rest of the fixes don't apply per the start of the tutorial:

This document provides an introduction to Razor Pages. It's not a step by step tutorial. If you find some of the sections too advanced, see [Get started with Razor Pages](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0).
