### ISSUE TITLE
bUnit Example Update

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/AspNetCore.Docs#30165]
The current bUnit example on the page needs to be updated and reflect our (cc @egil) latest recommendation.
I do understand that it's "just" a 3rd party library and maintaining the docs might be too much. That is why, if accepted, I can file a pull request.

Our recommendation would be:
1. Use razor syntax instead of "plain old" C# syntax. It might make sense to have both examples prominent for the user.
2. Inherit from `TestContext` instead of creating a new instance per test

The first approach could be achieved thanks to docfx quite easily:

~~~no-class
# [Razor](#tab/razor]
```razor
Here goes razor code
```

# [Csharp](#tab/csharp]
```csharp
Here goes C# code
```

---
~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61f0e0ba-e807-c5e8-3120-dbcf35a98f59
* Version Independent ID: 2890676f-3c63-5ab7-dd31-6b223212da30
* Content: [Test Razor components in ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/test?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/test.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/test.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @linkdotnet ... The example is only meant to demonstrate that setting up tests is easy with bUnit. We want it to be the simplest, quickest valid example of use. We'd prefer the bUnit docs to take it from there. Does the example shown no longer work, or in what way does it break your recommendations for a quick, simple test?

**Comment by guardrex** [comment]
We can add a line that says something to the effect ...

> The following example merely demonstrates a basic test and doesn't reflect bUnit's best practices. For complete guidance on using bUnit, see the bUnit documentation.

... with "bUnit documentation" cross-linked to the [getting started with bUnit doc](https://bunit.dev/docs/getting-started/).

**Comment by guardrex** [comment]
I see in @egil's Oslo '21 talk the use of the Razor component approach described as the 'Hello world!' example for bUnit ...

https://www.youtube.com/watch?v=Co7QetPYiO4

(btw- Great talk, @egil! I plan to watch the whole thing next week.)

Let's go with one or the other. If the component approach is now the favored approach, let's change the example. An added line can remark that tests can be authored in C# if the developer prefers it. If there's a doc in the bUnit documentation that pertains to C# tests, we can cross-link to it.

**Comment by egil** [comment]
Thanks, appreciate the kind words.

We did not recommend the razor approach previously because the editor experience wasn't great. 

Our docs show both c# and razor versions via the tab feature, e.g.: https://bunit.dev/docs/providing-input/passing-parameters-to-components.html?tabs=csharp

**Comment by guardrex** [comment]
If they're equally favored/popular, then we can show both. Let's show them SxS without the use of tabs.

@linkdotnet ... You can submit a PR for it. Let me know if the examples will be .NET version-specific. We might just say in the text what versions of .NET are covered by the examples and leave the whole doc at >=3.1. Whatever we do, let's try to harden it for as few changes as possible going forward. It's best if churn in the .NET framework or bUnit won't likely break the example soon.

**Comment by linkdotnet** [comment]
Sounds reasonable - the examples shown are not bound to any .NET-specific version.
Also, bUnit is not bound to any hosting model (as of now) - Luckily for us, we did not have to do much to support .net8.

Let's see if there are big changes in RC1/RC2.

**Comment by guardrex** [comment]
Cool.  👍 

I marked this 'in-progress', but there's no rush. Let me know if you have any questions for your PR.

**Comment by linkdotnet** [comment]
Currently in the train and do have some minutes spare anyway - so I'll open the PR
