### ISSUE TITLE
Container: Azure AD is being renamed Microsoft Entra ID.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30185]
This is the container issue to list all doc's to rename Azure AD yo Microsoft Entra ID.

## @Rick-Anderson  and @tdykstra  responsible docs

- [x] #30186
- [x] #30187
- [x] #30190
- [x] #30241
- [x] #30200
- [x] #30242
- [x] #30244
- [x] #30246
- [x] #30245
- [ ] 

## Blazor @guardrex 

- [x] #30194
- [x] #30199

## SignalR and gRPC @wadepickett 

- [x] #30590
- [x] #30591
- [x] #30592

---
[Associated WorkItem - 153933](https://dev.azure.com/msft-skilling/Content/_workitems/edit/153933)

**Comment by Rick-Anderson** [comment]
@wadepickett  you also need to update the tutorials you own, such as [MongoDB](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-7.0&tabs=visual-studio) and get them listed and updated.

**Comment by wadepickett** [comment]
On it, sorry I didn't see this, thanks.

**Comment by wadepickett** [comment]
Complete for my items, thanks.
