### ISSUE TITLE
Extend configuration doc with binding source generator info

### ISSUE THREAD

**Issue by layomia** [dotnet/AspNetCore.Docs#30215]
[EDIT by guardrex to add the metadata. @layomia ... If you use the **This Page** feedback button+form at the bottom of the article, the metadata is added automatically.]

- https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0
- https://github.com/dotnet/AspNetCore.Docs/blob/512d76abcd03ac415764964fcc3adcd8e8fa8e3c/aspnetcore/fundamentals/configuration/index.md
- Lower level binder doc https://github.com/dotnet/docs/issues/36939

FYI @dotnet/area-extensions-configuration @eerhardt @captainsafia.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@layomia 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0
That's the wrong version, you'd want `view=aspnetcore-8.0`

Even so, `EnableConfigurationBindingGenerator` is enabled by default for AOT web apps so no need to document it in the config file above.

> https://github.com/dotnet/AspNetCore.Docs/blob/512d76abcd03ac415764964fcc3adcd8e8fa8e3c/aspnetcore/fundamentals/configuration/index.md

What's that link for?

> `FYI https://github.com/orgs/dotnet/teams/area-extensions-configuration @eerhardt @captainsafia.`
Please don't ping everyone, we'll review issues. Closing as I don't see an issue here.

**Comment by layomia** [comment]
ASP.NET apps can be built without AOT compilation so I'd think that mentioning the generator would be useful. Also, AOT compat isn't the only benefit of the generator -- it also improves start-up, throughput, and memory allocs.

> `FYI https://github.com/orgs/dotnet/teams/area-extensions-configuration @eerhardt @captainsafia.`
> Please don't ping everyone, we'll review issues.

These are the folks I'm working on the generator with.
