### ISSUE TITLE
Add an alert box in VS for Mac sections of tutorials, to warn about impending retirement of VS for Mac

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#30217]
https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

---
[Associated WorkItem - 159812](https://dev.azure.com/msft-skilling/Content/_workitems/edit/159812)

**Comment by guardrex** [comment]
Thanks for the heads-up, @tdykstra. We're going to go ahead and remove it from the Blazor node now on the idea that getting devs started with it while we know its on its way out will just end in tears for those who like it. I'm going to work it for the Blazor node via #30219 on Tuesday.
