### ISSUE TITLE
ASP.NET Core 7.0 Documentation | Servers > Kestrel > Endpoints Section Header Text Overlapping

### ISSUE THREAD

**Issue by rajgog** [dotnet/AspNetCore.Docs#30223]
<img width="1274" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/98525852/5d4c2a84-a93f-4cd3-ba5f-4e0fda55d27d">

The text of header/section title is overlapping documentation panel on the right.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 312df0ba-e769-c904-40b2-733c291704a0
* Version Independent ID: fd9cc0c2-3ea3-f437-e0ac-8789fb96faf7
* Content: [Configure endpoints for the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/endpoints.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@rajgog Thanks for reporting that! The fix should be live later today or tomorrow.
