### ISSUE TITLE
Improve example for FrameworkReference in "Only support the Blazor Server hosting model"

### ISSUE THREAD

**Issue by FabioPagano** [dotnet/AspNetCore.Docs#30221]
In the .csproj XML example at

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#only-support-the-blazor-server-hosting-model

in the section "Only provide a framework reference to ASP.NET Core in the library's project file" (the section where is the .csproj content with "FrameworkReference" in it), I think can be added other information to make it clearer.

1. In the current example it seems that the .csproj should be composed "only" of:
`<Project Sdk="Microsoft.NET.Sdk.Razor">`
`  <ItemGroup>`
`    <FrameworkReference Include="Microsoft.AspNetCore.App" />`
`  <ItemGroup>`
`</Project>`
Instead are of course needed in the .csproj also other information such as "TargetFramework", so I think that in the example should be added three dots in the omitted parts, that is:
`<Project Sdk="Microsoft.NET.Sdk.Razor">`
`  ...`
`  <ItemGroup>`
`    <FrameworkReference Include="Microsoft.AspNetCore.App" />`
`  </ItemGroup>`
`  ...`
`</Project>`
with the three dots that means that must be something in that place.

2. The current example refers to:
`<Project Sdk="Microsoft.NET.Sdk.Razor">`
Should be added (as a note or as another example) that the proposed solution works also in .csproj of type
`<Project Sdk="Microsoft.NET.Sdk">`
(that is a simple class without web or razor components).

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98629146-7d64-9f48-6e45-51bafe8c7116
* Version Independent ID: cdb2b89f-bf1c-f313-0062-7f6b7ef8b611
* Content: [Use ASP.NET Core APIs in a class library](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/fundamentals/target-aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/target-aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks for the feedback, @FabioPagano. I'll take care of these updates next week on Tuesday. We're off for a holiday (Labor Day) on Monday.
