### ISSUE TITLE
Avoid usage of LoggerFactory.Create to setup logging pipeline

### ISSUE THREAD

**Issue by cijothomas** [dotnet/AspNetCore.Docs#30239]
A lot of code snippets use `LoggerFactory.Create` to setup logger factory. This is confusing as it'll end up as a new logging pipeline, and not "attaching" to the existing logging pipeline created in the default builders. This would be okay in non-Host apps, but mentioning `LoggerFactory.Create` approach in Asp.Net Core is confusing.

Suggestions:
Remove `LoggerFactory.Create` completely from this doc.
Keep `LoggerFactory.Create`, but callout or warn that this is to be done only if interested in setting up an alternate logging pipeline.

LoggerProviders like OpenTelemetry explicitly [warns users against this.](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/getting-started-console#note-for-different-application-types), as we have found user unintentionally ending up with more than one logging pipelines!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in .NET Core and ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#log-in-programcs)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 156755](https://dev.azure.com/msft-skilling/Content/_workitems/edit/156755)

**Comment by Rick-Anderson** [comment]
```
var builder = WebApplication.CreateBuilder(args);

// Configure logging with AddConsole()
builder.Logging.AddConsole();

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.MapGet("/Test", async context =>
{
    var logger = app.Logger; // Access the configured logger directly
    logger.LogInformation("Testing logging in Program.cs");
    await context.Response.WriteAsync("Testing");
});

app.Run();
```

Is the right way to do the first snippet.

**Comment by cijothomas** [comment]
> ```
> var builder = WebApplication.CreateBuilder(args);
> 
> // Configure logging with AddConsole()
> builder.Logging.AddConsole();
> 
> var app = builder.Build();
> 
> app.MapGet("/", () => "Hello World!");
> 
> app.MapGet("/Test", async context =>
> {
>     var logger = app.Logger; // Access the configured logger directly
>     logger.LogInformation("Testing logging in Program.cs");
>     await context.Response.WriteAsync("Testing");
> });
> 
> app.Run();
> ```
> 
> Is the right way to do the first snippet.

That looks correct. I usually find examples retrieving Logger from Constructor DI like:
app.MapGet("/", (ILogger<Program> logger) =>
{   
    logger.LogInformation("Testing logging in Program.cs");
    await context.Response.WriteAsync("Testing");
});

**Comment by Rick-Anderson** [comment]
@cijothomas 

That looks correct. I usually find examples retrieving Logger from Constructor DI like:
```
app.MapGet("/", (ILogger logger) =>
{
logger.LogInformation("Testing logging in Program.cs");
await context.Response.WriteAsync("Testing");
});
```
But not context is undefined.

**Comment by Rick-Anderson** [comment]
Is this better?

```
app.MapGet("/Test", async context =>
{
    var logger = context.RequestServices.GetRequiredService<ILogger<Program>>();
    logger.LogInformation("Testing logging in Program.cs");
    await context.Response.WriteAsync("Testing");
});
```
