### ISSUE TITLE
Replace ALL VS images in ALL onboarding tutorials with default dark theme.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30254]
When updating each series for .NET 8
Add contributes to `#30254` to each so we can track changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @wadepickett
* Microsoft Alias: **wpickett**

**Comment by wadepickett** [comment]
Thanks @Rick-Anderson .  Is this a standard now across doc repos?  Why are we switching to a dark theme for all onboarding tutorial screenshots?

**Comment by wadepickett** [comment]
Thanks @Rick-Anderson. Is this a standard now across doc repos?  Why are we switching to a dark theme for all onboarding tutorial screenshots?

**Comment by wadepickett** [comment]
Ah, I misread this and get it now.  You were referring of course to all the VS UI images in the default dark theme, and for a moment there I thought we meant browser screenshots of the apps as well, not sure why.  Understood.  Are we also doing this for all docs, Blazor, etc, or just the tutorials, or just the onboarding tutorials?  What is the standard going forward?

**Comment by wadepickett** [comment]
Thanks @guardrex.  What is the scope of the standard going forward?  VS dark theme for all docs?  Just so I am on the same page.

**Comment by guardrex** [comment]
I'm awaiting Rick to confirm, too, but that's my assumption from the issue title.

I'll take care of the three Blazor Hybrid tutorials, which are the only Blazor articles with VS UI images, but I can't say when I'll be able to reach them. I'm absolutely ***buried in work*** ⛏️🗻😨 for the foreseeable future, probably through 8.0 RTM, and these three Blazor Hybrid tutorials have quite a few VS images in them. It will take a full day to get them all re-shot, and I won't have a full day for anything that isn't .NET 8 critical for a long time 🏃🏃🏃🏃😅.

**Comment by Rick-Anderson** [comment]
All onboarding tutorials. All new/updated images in any tutorial.

VS screen shots are mainly used in onboarding tutorials.
