### ISSUE TITLE
Document WASM runtime max heap size to accomodate mobile browser demands

### ISSUE THREAD

**Issue by maraf** [dotnet/AspNetCore.Docs#30278]
_Originally posted at https://github.com/dotnet/runtime/pull/91277#issuecomment-1697864758_

We should add something to https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/blazor about making Blazor apps for mobile devices. In particular it seems like apps that want to support mobile Safari will need <EmccMaximumHeapSize>268435456</EmccMaximumHeapSize> (256MiB). Not sure if we have any specific Android guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @maraf ... We carry guidance on Blazor Hybrid specifically for desktop and mobile native client frameworks ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0

**Comment by guardrex** [comment]
... and the main doc set for .NET MAUI isn't here, as we mostly focus on Razor component scenarios with the embedded Web View. The main doc set for MAUI is here ...

https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui

**Comment by maraf** [comment]
This is relevant for MAUI, as in MAUI the .NET bits are not run on WebAssembly, right?

I probably chose an not ideal issue title, I didn't thought about MAUI, sorry for that. 

My goal is tell the users if they are building Blazor WebAssembly app that target mobile devices, especially Safari/iPhone, they should think about setting max memory using MSBuild property `EmccMaximumHeapSize`.

**Comment by guardrex** [comment]
Oh! I see this came from a runtime team issue ...

https://github.com/dotnet/runtime/pull/91277

Hold on ... let me 👀 that and see what was said.

I'm a bit ***overwhelmed*** at the moment with .NET 8 doc work, so it's hard to focus on anything else at the moment. Bear with me for a sec! 😆

**Comment by guardrex** [comment]
It's unclear if this would be part of the effort for ...

https://github.com/dotnet/docs/issues/27395

I would prefer to cross-link for such coverage because we're getting into runtime configuration coverage, not Blazor framework coverage.

That general issue is taking quite a while to reach, and it would probably only be to place guidance for the properties that can be set. I don't think that issue would cover specific runtime config guidance for heap sizes as they relate to mobile browser support.

Let's wait to hear from @pavelsavara. Pavel, do you know about adjusting heap sizes for mobile (what we would cover and where), or would Larry or someone else be better to ask?

**Comment by pavelsavara** [comment]
Discussing it here https://github.com/dotnet/runtime/issues/84638

**Comment by guardrex** [comment]
Given that a recommendation for prior/current releases is forthcoming, we can leave this docs issue open to document it with our Host and deploy for WebAssembly coverage. I'll add the metadata to the opening comment.
