### ISSUE TITLE
Authentication and authorization in ASP.NET Core SignalR there are errors

### ISSUE THREAD

**Issue by MuJint** [dotnet/AspNetCore.Docs#30280]
![image](https://github.com/dotnet/AspNetCore.Docs/assets/28145880/3b8977b0-73af-4829-9a12-bf12f11b19f1)
In jwt authentication, the document appears to obtain a token from the request, but in reality it does not.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/28145880/72398e95-c5b7-478c-93c2-897db6255f24)
Request header has access_token,This is very bad, it wastes a lot of my time！！

**Comment by BrennanConroy** [comment]
There is a giant comment above the line you highlighted explaining that the access_token query string is **sometimes** used.

The code will use the `Authorization` header otherwise.

**Comment by MuJint** [comment]
Where is it?
I didn't see that it was necessary to use a header

**Comment by BrennanConroy** [comment]
That's how JWT auth works. It looks at the Authorization header.
https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.jwtbearerextensions.addjwtbearer?view=aspnetcore-7.0

If you're using the SignalR clients we provide you don't need to worry about adding the header. The client will do that for you if you use the access token factory.

**Comment by wadepickett** [comment]
Thanks Brennen!  Closing this issue.  If either of you feel the issue should be reopened feel free to do so.
