### ISSUE TITLE
Endpoints Explorer only recognizes literal route strings

### ISSUE THREAD

**Issue by johnholliday** [dotnet/AspNetCore.Docs#30293]
The Endpoints Explorer window only recognizes literal strings for routes.  For example, the following declaration shows up in the Endpoints Explorer window:

```csharp
public static class MyEndpoints {
  public static void MapMyEndpoints(this IEndpointRouteBuilder routes) {
    var group = routes.MapGroup("api/test");
    group.MapGet("/{id}", TestGetMethod);
}}
```

However, the following is invisible to the Endpoints Explorer window:

```csharp
public static class MyEndpoints {
  private const string ApiBase = "api/Test";
  public static void MapMyEndpoints(this IEndpointRouteBuilder routes) {
    var group = routes.MapGroup(ApiBase);
    group.MapGet($"{ApiBase}/{id}", TestGetMethod);
}}
```

This can be a significant limitation, since it forces the declaration literal route strings that may be spread across many solution files, and other projects that may consume the API.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Version Independent ID: 26f1374f-556a-35fc-cc42-b8911746db80
* Content: [Use .http files in Visual Studio 2022](https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0)
* Content Source: [aspnetcore/test/http-files.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
That's not a documentation issue.  You should open this issue  at https://developercommunity.visualstudio.com/VisualStudio

**Comment by johnholliday** [comment]
I will do that.  However, I think it is actually something that should be mentioned in the documentation.  Otherwise people will likely waste a lot of time chasing a non-issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by guardrex** [comment]
We have no way to version such content, and we have no way to track the fix for it because it would be internal to the VS team. I agree with Rick. I think problems with VS features generally need to go to that team for resolution.

**Comment by guardrex** [comment]
btw @johnholliday ... I recommend the **Report a problem** feature in VS. I don't think those community issues generate bug reports.

https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by Rick-Anderson** [comment]
@johnholliday  please post links here where you have reported the issue.
