### ISSUE TITLE
new doc: Migrate from ASP.NET Core 7.0 to 8.0

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30303]
@guardrex  to do Blazor
@wadepickett  to do gRPC and SignalR

@tdykstra  and @Rick-Anderson  will do everything but the previous

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9669d35-3de1-997d-258c-745ebbdbface
* Version Independent ID: e9669d35-3de1-997d-258c-745ebbdbface
* Content: [Migrate from ASP.NET Core 6.0 to 7.0](https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/migration/60-70.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/60-70.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 159036](https://dev.azure.com/msft-skilling/Content/_workitems/edit/159036)

**Comment by danroth27** [comment]
Related breaking changes are here: https://learn.microsoft.com/dotnet/core/compatibility/8.0#aspnet-core.

We also want to add guidance for folks that want to optionally upgrade existing Blazor Server and Blazor WebAssembly apps to the new Blazor Web App model: #29522, #29505.
