### ISSUE TITLE
HTTP/3 disabled by default

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30344]
[HTTP/3 disabled by default](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#http-3-disabled-by-default)

After closing this issue add the information to the What's new doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57282931-0741-9ae0-1bc3-1918160769e2
* Version Independent ID: d8ff0551-6287-7921-b18d-2cad70fce012
* Content: [Use HTTP/3 with the ASP.NET Core Kestrel web server](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/http3?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/servers/kestrel/http3.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/http3.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @wtgodbe
* Microsoft Alias: **wigodbe**

**Comment by tdykstra** [comment]
Fixed by #30146 
#30146 also fixed the What's New, by removing the section saying that HTTP/3 was enabled by default. Preview 1 enabled it by default, and now it's disabled by default, so there's no change from .NET 7 in .NET 8.
