### ISSUE TITLE
Page recommends using deprecated package

### ISSUE THREAD

**Issue by bharrison44** [dotnet/AspNetCore.Docs#30370]
The page, and a few of its siblings, recommend using the package `Microsoft.AspNetCore.App` which has been deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrate from ASP.NET Core 2.2 to 3.0](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-7.0&source=recommendations&tabs=visual-studio)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is migration from 2.2 to 3.0
