### ISSUE TITLE
Missing line of code in the Minimal API Authentication example

### ISSUE THREAD

**Issue by mvheap** [dotnet/AspNetCore.Docs#30383]
In [Enabling authentication in minimal apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0#enabling-authentication-in-minimal-apps) we have the code:

```c#
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication().AddJwtBearer();
builder.Services.AddAuthorization();

var app = builder.Build();

app.UseCors();
app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/", () => "Hello World!");
app.Run();
```

which is missing the line `builder.Services.AddCors();` to work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Version Independent ID: 3a9d7eb8-6c1f-4619-00fa-9b69dbe3dcea
* Content: [Authentication and authorization in minimal APIs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/security?view=aspnetcore-7.0)
* Content Source: [aspnetcore/fundamentals/minimal-apis/security.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/security.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @captainsafia
* Microsoft Alias: **safia**

**Comment by Rick-Anderson** [comment]
@mvheap  thanks for reporting this. I wonder how that snuck by.
