### ISSUE TITLE
Prerequisites on gRPC page are out of date

### ISSUE THREAD

**Issue by JamesNK** [dotnet/AspNetCore.Docs#30389]
These prerequisites should be updated to .NET 6.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/303201/d6c4af1f-a5aa-4cbe-8896-e7501cea52e1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
On it, thanks!

**Comment by wadepickett** [comment]
Closing as dupe to a broader issue #30120 I already had in tracking for this month's sprint so I will close this one.
Addressed in PR #30445.  Thanks for pointing this out though, appreciated.
