### ISSUE TITLE
Move or copy Host gRPC in non-ASP.NET Core projects to dotnet docs

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30399]
Move 
[Host gRPC in non-ASP.NET Core projects](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-8.0&tabs=visual-studio#host-grpc-in-non-aspnet-core-projects)
 to https://github.com/dotnet/docs/

See #30390

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e072aff-35c1-1fc2-3f94-97dc7a809414
* Version Independent ID: 2f05b9da-0d50-ce84-d6af-332da7d9d625
* Content: [gRPC services with ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-8.0&branch=pr-en-us-30390&tabs=visual-studio#host-grpc-in-non-aspnet-core-projects)
* Content Source: [aspnetcore/grpc/aspnetcore.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/aspnetcore.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
@Rick-Anderson.  OK, thanks.  
This feels a little awkward in dotnet/docs.  It still relies on `Microsoft.AspNetCore.App`.  Plus there wouldn't be any of the related docs that explain all about gRPC.  I would expect it in the sub-section of the topic James put it in already in PR #30390 as far as traffic flow and interest, and then link to that from dotnet/docs someplace so you keep all the rest of the context together.   Except honestly, I'm not sure where that link would go, so maybe it is the best choice even if awkward.  Just want to bring up those points in case.  cc @JamesNK 

@TomDykstra & @BillWagner, any thoghts on where this topic or section would best exist in dotnet/docs?

**Comment by JamesNK** [comment]
I'd prefer to keep it where it is. It's gRPC content in the gRPC docs. What is the reason to move it?

**Comment by wadepickett** [comment]
I would rather keep it where it is, and just make it discoverable from dotnet/docs with a link if possible.

**Comment by Rick-Anderson** [comment]
> I'd prefer to keep it where it is. It's gRPC content in the gRPC docs. What is the reason to move it?

I said move or copy. But maybe just some reference to it in the docnet docs.
