### ISSUE TITLE
Add Kestrel certificate auto rotation support

### ISSUE THREAD

**Issue by aelij** [dotnet/AspNetCore.Docs#30404]
See https://github.com/dotnet/aspnetcore/issues/32351 and https://github.com/dotnet/aspnetcore/pull/49979

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Version Independent ID: f30dbb9e-d64d-a925-01ca-00d9d035e6c1
* Content: [What's new in ASP.NET Core 8.0](https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-8.0.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-8.0.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-releasenotes**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 196559](https://dev.azure.com/msft-skilling/Content/_workitems/edit/196559)

**Comment by aelij** [comment]
Kind reminder - the feature has been released and there's still no documentation for it.
I would also mention it on this page - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0

**Comment by Rick-Anderson** [comment]
@aelij or @pinkfloydx33 would you be able to provide a sample for this?

**Comment by aelij** [comment]
@Rick-Anderson

* Kestrel support for auto-rotation is on by default (when `reloadOnChange` is true)
* Can be disabled with app context switch `Microsoft.AspNetCore.Server.Kestrel.DisableCertificateFileWatching`
* Does not apply to code-based configuration, which never triggers reloads
* Does not trigger on file deletion

So a separate sample is not needed - it's the same as [configuring HTTPS certs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0#configure-https).

Also tagging @amcasey who developed this feature.

**Comment by amcasey** [comment]
I definitely remember writing prose for the feature - I wonder where it ended up. 😆 Maybe there are release notes or something.

**Comment by amcasey** [comment]
Okay, I had to refresh my memory a bit on this one, but I think I mostly remember what changed.  @aelij, can you tell me more about what documentation you'd like to see?  Just a mention of the appcontext switch in case people need to opt out?  I'm not sure a partial fix to a specific scenario is something I'd want to advertise widely.  Hopefully, it just starts working and people continue to not have to think about it.

**Comment by aelij** [comment]
"Just starts working" is not something people would expect. Principle of least astonishment at all that :) Plus on AKS we'd need to turn on the auto-rotation feature for this to work, which users may not do unless they know it should work. I think at the very least it should be mentioned in the release notes, with the caveats (bullets above I copied from the PR).
