### ISSUE TITLE
Note that request timeout behavior differs in debug mode

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#30431]
Add an alert box in the article intro explaining what happens to timeout handling when you're running in debug mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 449a4031-c1d1-5fbe-8e8f-b0e931a5b7ab
* Version Independent ID: 449a4031-c1d1-5fbe-8e8f-b0e931a5b7ab
* Content: [Request timeouts middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/timeouts?view=aspnetcore-8.0)
* Content Source: [aspnetcore/performance/timeouts.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/timeouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

---
[Associated WorkItem - 161880](https://dev.azure.com/msft-skilling/Content/_workitems/edit/161880)

**Comment by tdykstra** [comment]
@Kahbazi Is it accurate to say that timeouts are disabled when you run in debug mode? Anything else we should say about debugging timeouts?

**Comment by Kahbazi** [comment]
@tdykstra Yes, the middleware will be skipped if a debugger is attached. It's the same behavior as the kestrel timeout.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-7.0#behavior-with-debugger-attached

> Anything else we should say about debugging timeouts?

I don't have anything else in mind.

**Comment by tdykstra** [comment]
@Kahbazi Thank you!
