### ISSUE TITLE
Details on keepalive for gRPC in Azure App Service

### ISSUE THREAD

**Issue by karpikpl** [dotnet/AspNetCore.Docs#30444]
Hi,
I've been running gRPC server on an App Service.
I noticed my long running streaming call has been failing with 504 issues. To fix it I've implemented a dummy keep-alive message to be sent from the server every 2 minutes and that fixed it.

But then I noticed this [documentation](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#keep-alive-pings) and I switched to keepalive pings configured on the channel. After doing that, the issue started again - you can see it in attached screenshot (before - my dummy keepalive call that has to be ignored by the client, later - keepalive pings)

![image](https://github.com/dotnet/AspNetCore.Docs/assets/3539908/1f3086df-f1ad-45bb-b56b-a6c21bdb122e)

Can the docs be updated for how to use keepalives in Azure? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 484737e7-abb8-c142-35f8-22a35817270d
* Version Independent ID: 9e412677-c511-9f5b-4654-95e0177c7dd4
* Content: [Performance best practices with gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0)
* Content Source: [aspnetcore/grpc/performance.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/performance.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by wadepickett** [comment]
Thanks @karpikpl for the details on your experience for the issue.

@JamesNK, is there any guidance or clarification to add specific to Azure App Service for this section?  [Performance best practices with gRPC: section: Keep alive pings](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#keep-alive-pings)

**Comment by karpikpl** [comment]
Here's my keep alive client configuration - copied from docs
```csharp
builder.Services
    .AddGrpcClient<Notifications.Notifier.NotifierClient>(o =>
    {
        o.Address = new Uri(downstreamApiUrl);
        o.ChannelOptionsActions.Add(channelOptions =>
        {
            channelOptions.HttpHandler = new SocketsHttpHandler
            {
                PooledConnectionIdleTimeout = Timeout.InfiniteTimeSpan,
                KeepAlivePingDelay = TimeSpan.FromSeconds(60),
                KeepAlivePingTimeout = TimeSpan.FromSeconds(30),
                EnableMultipleHttp2Connections = true
            };
        });
    });
```

**Comment by wadepickett** [comment]
Hi @JamesNK , is there any related guidance or clarification to add specific to Azure App Service for this section I should add? [Performance best practices with gRPC: section: Keep alive pings](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0#keep-alive-pings)

**Comment by JamesNK** [comment]
Keep alive pings don't help to keep long-running gRPC calls alive. Periodically sending dummy messages that you're already doing is a good way to keep long-running calls alive.

PR to update docs to be clearer https://github.com/dotnet/AspNetCore.Docs/pull/30489

**Comment by chwarr** [comment]
Is there anything in the gRPC.NET implementation kill calls due to inactivity (but keeps the connection alive)?

I have experience with the older "C Core" library. I don't remember it having a per call timeout mechanism (outside of deadlines). So long as the HTTP2 connection stayed alive, the call remained active until both sides hung up. And configuring HTTP2 PING/PONG keep alive messages was enough to keep the HTTP2 connection alive for me. (I wasn't using App Service.)

Or, are you saying that what could be happening is that App Service is looking at the HTTP2 connection, only seeing PING/PONG messages, and deciding to close the HTTP2 connection due to inactivity?

**Comment by wadepickett** [comment]
Addressed with James PR earlier, closing.
