### ISSUE TITLE
Qutoes didn't removed from boudndary

### ISSUE THREAD

**Issue by mulei2023** [dotnet/AspNetCore.Docs#30474]
[EDIT by guardrex to add the metadata]

**Describe the bug**
Qutoes didn't removed from boudndary

**To Reproduce**
1. Go to 'https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads/samples/5.x/LargeFilesSample/Controllers/FileUploadController.cs'
2. Check line No.49. It didn't remove the quotes which may lead to upload failure.

**Expected behavior**
Remove the quotes

**Screenshots**
![image](https://github.com/MicrosoftDocs/feedback/assets/4969802/ffc119f5-678d-4f67-ad61-213667e0006a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [Upload files in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-7.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

---
[Associated WorkItem - 164045](https://dev.azure.com/msft-skilling/Content/_workitems/edit/164045)

**Comment by guardrex** [comment]
Hello @mulei2023 ... For future issues, please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

I added the metadata manually to your opening comment, so we're good here. Thanks for reporting this. I'll ping for review on your PR.
