### ISSUE TITLE
Document how to add Auto component rendering to a Blazor Server app in .NET 8

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#30471]
Some Blazor Server users may want to add WebAssembly based components to their existing apps after upgrading to .NET 8. We should document how to add the client project and how to setup components to use the WebAssembly or Auto interactive render modes.

**Comment by guardrex** [comment]
Related to https://github.com/dotnet/AspNetCore.Docs/issues/29505 and probably worked with it.
