### ISSUE TITLE
Grammer mistake

### ISSUE THREAD

**Issue by sivaji55** [dotnet/AspNetCore.Docs#30526]
Under the concurrency section, there is a small grammar mistake.

"The concurrency limiter limits the number concurrent requests." should be "The concurrency limiter limits the number of concurrent requests."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Version Independent ID: bb96b20f-0991-d6de-4d98-192cd469460f
* Content: [Rate limiting middleware in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0)
* Content Source: [aspnetcore/performance/rate-limit.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

**Comment by sivaji55** [comment]
sure

**Comment by Rick-Anderson** [comment]
Fixed in #30548
