### ISSUE TITLE
Add guidance trimming IL after AOT 8.0

### ISSUE THREAD

**Issue by AceHack** [dotnet/AspNetCore.Docs#30535]
Here is my github https://github.com/AlephZ-ai/auto-scheduler
Here is the live site https://alephz-ai.github.io/auto-scheduler/
You can see the errors 
<img width="1013" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/578953/17b5536d-32be-49d4-9b66-5fb1b3f16ef2">
[Enter feedback here]

I would like to host a default template of Blazor 8 on GitHub pages.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Host and deploy ASP.NET Core Blazor WebAssembly](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by AceHack** [comment]
It was this line in the csproj that caused the issue, removing it fixed it.
    <WasmStripILAfterAOT>true</WasmStripILAfterAOT>

**Comment by guardrex** [comment]
Thanks @AceHack ... I'll remark on that line in the guidance.

**Comment by guardrex** [comment]
cc: @mkArtakMSFT ... in case this is something that the product unit should know about.

**Comment by guardrex** [comment]
Re-opening this. I'll add remarks that the compiler team suggests.
