### ISSUE TITLE
Application Insights and Blazor Server

### ISSUE THREAD

**Issue by DennyFiguerres** [dotnet/AspNetCore.Docs#30546]
can we get some details on using application insights with blazor server  on an azure web app ?

i have been searching for more information and can not find any good guides for blazor server

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8795bcc-45ef-7edc-4657-fca867c8ff81
* Version Independent ID: d0b1a040-5dae-8233-dbee-c5837a0c231d
* Content: [ASP.NET Core Blazor logging](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-7.0)
* Content Source: [aspnetcore/blazor/fundamentals/logging.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/logging.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DennyFiguerres ... Your request should go to the Azure doc authors who write on it for the App Insight docs here ...

https://learn.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview?tabs=net

Given that server-side Blazor (as either Blazor Server of <8.0 or Blazor Web App of >=8.0) is just an ASP.NET Core app, we default to the main doc set coverage. It's minimal, but that's all that the product unit here wants to cover ...

https://learn.microsoft.com/en-us/aspnet/core/performance/diagnostic-tools?view=aspnetcore-7.0#application-insights

If you want to request special Blazor coverage from the Azure doc authors ask them if they'll consider it by opening an issue on their repo ...

https://github.com/MicrosoftDocs/azure-docs/issues

**Comment by DennyFiguerres** [comment]
well there is a request on the application insights repo that has not been answered for over a year.....
and the default install and configure do not help with much.   full tracking is not happening with it.

someone needs to step up and tell us how to use it !  so far it seems like "hot potato"  with everyone poassing it to the next one......

**Comment by DennyFiguerres** [comment]
https://github.com/dotnet/aspnetcore/issues/30972

**Comment by guardrex** [comment]
I see. I hadn't heard about that. Anyway ... that's scheduled for ***NOW*** 😄 ... by the .NET 8 release in November. It might get bumped to next year because they've been so busy with the framework, but tracking on that issue is the best thing to do.

**Comment by DennyFiguerres** [comment]
also read this thread
https://github.com/dotnet/aspnetcore/issues/5461

its very disturbing that folks keep asking and no one can find the time to deal with the very simple question of getting it to work.
or at the least for Microsoft to just publish some kind of how to guide on what the developer should do. 

i think i am getting close to an working answer but i have to keep looking and searching ......

it looks like in the end i may have to use the javascript route just cause thats the one that most folks have done and that there is a repo by a developer that they got to work....

**Comment by DennyFiguerres** [comment]
all of that i do understand.
but my point is this: at the end of the day all of this: azure, dotnet, blazor and application insights  *ARE* owned by Microsoft.
so who on what team does the things I really do not care about.  what I do care about is that multiple folks are asking in both places and not getting any solid results.

I cant see what's going on internally , I cant control it..... i can only keep asking and hope that someone takes action.

also some folks are taking on the web assembly side of this but does that code also work for server ??  there is a lot of that we need to get some clarity on..... can we have a common method that will work for Server and Web and Unified ??

also by the way i sent dan an email asking about this ..... just so you know i have tried that and not yet heard back .... may never hear back but i tried.

**Comment by guardrex** [comment]
Usually when enough customers request ... er .... *demand* ... action ... when it reaches the point of 💀 ***death threats*** 💀 😆 , perfect for Halloween 🎃 btw 😆, it's like 'squeaky wheel gets the grease' time. That's when someone, somewhere, swings into action and takes steps to resolve it. It's a matter of priorities. MS owns it ... ***True!*** ... and should explain how to use it with each programming framework ... ***Indeed!*** ... but MS also doesn't have unlimited 💰💰 ***funds*** 💰💰 to spend. It looks like with that issue that it has reached critical mass. Dan took this on directly, so he obviously feels that it has high importance.

**Comment by DennyFiguerres** [comment]
one last comment and i will leave this alone....

just to let you know I have been developing for a long time.   years ago I loved when there was a web site called "Channel9"  that Microsoft ran and back then I had a lot of contact with folks.... folks like Barry / aka / blowdart  for example
https://github.com/blowdart
but channel 9 is gone and now it is what it is....

**Comment by DavidThielen** [comment]
Has this been documented yet? If so, where? TIA

**Comment by zachrybaker** [comment]
> Usually when enough customers request ... er .... demand ... action ... when it reaches the point of 💀 death threats 💀 😆 ,

I'm not gonna go that far, but common Microsoft, make a solid lift here!
