### ISSUE TITLE
Set up new feedback control

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#30570]
Add template and docfx.json metadata to enable the new unified feedback control in this repo.

**Comment by tdykstra** [comment]
The GitHub ID of the author is in the **Article author** field in the **Article information** section.

You can get all page feedback issues by searching issues for the value of the **Version Independent Document ID** field in the **Article information** section. We're looking into whether we can make this a link so it's more convenient to use.

**Comment by cremor** [comment]
> The GitHub ID of the author is in the **Article author** field in the **Article information** section.

Yes, but it is not in the `@username` syntax, so the user will not be notified of the new issue.

> We're looking into whether we can make this a link so it's more convenient to use.

That would be very useful, thanks.

**Comment by tdykstra** [comment]
> > The GitHub ID of the author is in the **Article author** field in the **Article information** section.
> 
> Yes, but it is not in the `@username` syntax, so the user will not be notified of the new issue.

The .NET docs team decided to omit the @ sign to reduce notifications, so they would only get notified when someone explicitly mentioned them in a comment.
