### ISSUE TITLE
How will request header be accessible in Blazor ASP.NET Core 8?

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#30575]
Since there is no longer a `Pages/_Host.cshtml` (or `Pages/_Host.cshtml.cs`), how will request header values be accessible without access to `HttpContext`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8acbbf-c9d4-7041-c1a7-ec9ce8f0981b
* Version Independent ID: c98be365-408d-7ee6-cb74-14c44d01b0b8
* Content: [Server-side ASP.NET Core Blazor additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app)
* Content Source: [aspnetcore/blazor/security/server/additional-scenarios.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrlife ... This node of docs hasn't been updated yet. It's scheduled for post-RC2, pre-RTM. Can you post your question to engineering and add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/30575
```

... to the bottom of your opening comment?

Updating this node is tracked by another issue. I'll make a cross-link on that issue to the issue that you open to make sure that we get the right guidance placed. This issue can be closed, as it will be tracked on https://github.com/dotnet/AspNetCore.Docs/issues/28161.

**Comment by mrlife** [comment]
Thank you! Just got an answer from Dan and will add the cc there.
