### ISSUE TITLE
Create Code sample for keyed services in minimal APIs, MVC, and SignalR

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30586]
See [Keyed services support in Di](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#support-for-keyed-services-in-minimal-apis-mvc-and-signalr) and [this link](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#support-for-keyed-services-in-minimal-apis-mvc-and-signalr)

Create sample code in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples

See https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/samples/WebKeyedService to avoid duplicates

cc @sammychinedu2ky @fiyazbinhasan @timdeschryver 

doc the code at #30345

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/dependency-injection.md

### Document Version Independent Id

f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf

### Article author

ardalis

**Comment by sammychinedu2ky** [comment]
Would work on this

**Comment by gfoidl** [comment]
> See [Keyed services support in Di](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#support-for-keyed-services-in-minimal-apis-mvc-and-signalr) and [this link](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-1/#support-for-keyed-services-in-minimal-apis-mvc-and-signalr)

@Rick-Anderson both links point to the same destination. Copy and paste blooper?

**Comment by fiyazbinhasan** [comment]
[Sample](https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/samples/WebKeyedService) pretty much covers every possible scenario. Do you need any additional samples? @Rick-Anderson

**Comment by Rick-Anderson** [comment]
fixed in https://github.com/dotnet/AspNetCore.Docs.Samples/pull/184
