### ISSUE TITLE
The content is out of sync with the code. 

### ISSUE THREAD

**Issue by chanmmn** [dotnet/AspNetCore.Docs#30588]
### Type of issue

Outdated article

### Description

The code downloaded from the link below is out of sync with the document. 
https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/MinApiTestsSample
See more information here:
https://github.com/chanmmn/issue/blob/main/Create%20a%20minimal%20API%20with%20ASP.docx

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Document Version Independent Id

ab408035-6313-a183-9940-32de00e0e977

### Article author

wadepickett

**Comment by guardrex** [comment]
@chanmmn ... Please re-open this issue using the **This page** feedback button and form at the bottom of the **English-US** topic. Use of the **This page** feedback form adds metadata to your GitHub issue that cross-links the topic and automatically pings the author.

<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/1622880/81926733-0b02d200-95a8-11ea-8683-8dadc5483fb1.PNG">

**Comment by tdykstra** [comment]
@guardrex That feedback control is no longer used - this issue was created by the feedback control that replaced it. It provides the page URL, source URL, doc ID, and author in the issue description like the old one did.

**Comment by guardrex** [comment]
Woe! ... ***so*** that's why we're not getting labeling on issues. ... and without an "@" on our author, we don't get a ping.

It's off topic here, so I'll email the team about it so I can ask some questions.

**Comment by wadepickett** [comment]
@chanmmn, thanks for taking the time to point this out. 

I will look through the samples site example and update.

The samples specific to the tutorial and where its code examples are pulled from is located here and have been updated to .NET 8, and the previous versions are there as well: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/min-web-api/samples

So we could also help make that discoverable.
