### ISSUE TITLE
AAD rename for all tutorials and other content owned by WP

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#30592]
Contributes to #30185

This is to track AAD rename updates in all topics I own outside of gRPC and SignalR (which are being tracked seperately) such as tutorials, etc.

Replace "Azure Active Directory," "Azure AD," and "AAD"

List topics here:

None for the tutorials node, but there are tutorials that use the following includes that require the rename:
- [ aspnetcore/includes/DuendeldentityServer ] 

Examples:

Product references:

Azure Active Directory
becomes
Microsoft Entra ID

Azure Active Directory (AAD)
becomes
Microsoft Entra ID (ME-ID), but only if we are really referring to "ME-ID" later, otherwise it would be "Microsoft Entra ID".

Azure AD
becomes
Microsoft Entra ID

AAD
becomes
ME-ID

Topic file names and their links:
azure-active-directory.md
might become
microsoft-entra-id

Links:
Azure Active Directory (AAD) or Azure Active Directory
becomes
Microsoft Entra ID (ME-ID)  or just "Microsoft Entra ID" if there was no need to refer to later ME-ID after first use.

**Comment by wadepickett** [comment]
Searched through entire aspnetcore\tutorials node.   

Zero hits for:
"Azure Active"  
"Azure AD"  
"Azure-active"  
"Azure-ad"
"AAD"  (which brings up 20 random doc ID's that had "aad" in the sequence but no legit AAD hits).

Next: verify aspnetcore/includes that might be used in the tutorials that mention a variation on AAD.

**Comment by tdykstra** [comment]
>Azure Active Directory (AAD)
>becomes
>Microsoft Entra (ME-ID)

Shouldn't this be Microsoft Entra ID (ME-ID) and only keep the ME-ID if it's actually used in the context?

**Comment by wadepickett** [comment]
Yes, I should have put Microsoft Entra ID (ME-ID)

I figured use just "ME-ID" after first use of "Microsoft Entra ID (ME-ID)" otherwise folks will not really know what that acronym is.  That sound right?

**Comment by tdykstra** [comment]
Right, but if they never use AAD they would never need you to introduce ME-ID as its equivalent.

**Comment by wadepickett** [comment]
Aha, yes, sorry, I see your point.  Use "Microsoft Entra ID (ME-ID)" if there is a second use where you would refer to (ME-ID) otherwise use Microsoft Entra ID.
