### ISSUE TITLE
Code sample needed for RDG010 warning

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30596]
### Description

Sample needed in https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/aot/diagnostics for RDG0100 warning

cc @timdeschryver  @fiz

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/request-delegate-generator/diagnostics/rdg010?branch=main&branchFallbackFrom=pr-en-us-30587&view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/aot/request-delegate-generator/diagnostics/rdg010.md

### Document Version Independent Id

36843f44-e306-0fa5-77e2-6340dee034f6

### Article author

captainsafia

---
[Associated WorkItem - 167642](https://dev.azure.com/msft-skilling/Content/_workitems/edit/167642)

**Comment by timdeschryver** [comment]
I'm on it! :)
