### ISSUE TITLE
Replace dashes with dots in instrumentName usage

### ISSUE THREAD

**Issue by andy-g** [dotnet/AspNetCore.Docs#30604]
### Type of issue

Typo

### Description

I'm not sure if it's an issue because I'm on a mac, but all the instances of `http-server-request-duration` in the documentation need to be updated to `http.server.request.duration` (replacing dashes with dots) :

This is both for the `dotnet-counter` output (snippet from my local machine below):
```sh
Press p to pause, r to resume, q to quit.
    Status: Running

[Microsoft.AspNetCore.Hosting]
    http.server.active_requests ({request})                     
        http.request.method=GET,url.scheme=http                            0    
    http.server.request.duration (s)                            
        http.request.method=GET,http.response.status_code=200,ht           0    
        http.request.method=GET,http.response.status_code=200,ht           0    
        http.request.method=GET,http.response.status_code=200,ht           0 
```

...as well as when configuring `builder.AddView` (updated code below - with simplified buckets to easily show when applied successfully).
```csharp
builder.AddView("http.server.request.duration",
            new ExplicitBucketHistogramConfiguration
            {
                Boundaries = new double[] { 0, 0.001, 0.01, 0.1, 1, 10 }
            });
```

I'm currently running dotnet version: `8.0.100-rc.1.23463.5`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/log-mon/metrics/metrics.md

### Document Version Independent Id

fc4aa26a-a037-2bd9-f313-e3073d6b8232

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
@JamesNK  should I update this page with a MacOS tab `replacing dashes with dots`?

**Comment by andy-g** [comment]
But surely if this is Mac specific there's bigger problems. Adding code such as `builder.AddView("http.server.request.duration...` should be cross platform, if you need to use dashes on some operating systems & dots on others then surely it means the code isn't truly cross platform?

**Comment by andy-g** [comment]
Doesn't this suggest using dots as separators anyway. Any chance this was a refactor at some point and dots are being used consistently across platforms now?
https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation#best-practices

**Comment by JamesNK** [comment]
Done https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore
