### ISSUE TITLE
"Prerendering with authentication" link is broken.

### ISSUE THREAD

**Issue by TrieBr** [dotnet/AspNetCore.Docs#30607]
### Type of issue

Other (describe below)

### Description

At the bottom, under "Additional Resources", the "Prerendering with authentication" link is broken. That anchor/section doesn't exist in the linked page.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-8.0#client-sidespa-security

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/index.md

### Version Independent Document ID

8670b314-460d-3194-c53b-9a44f39c6b2a

### Article author

guardrex

**Comment by Rick-Anderson** [comment]
It works for me. Next time open an issue at the bottom of the page

<img width="203" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/79ab421d-c5f8-475a-9f2a-d5c0aa8cec51">
