### ISSUE TITLE
Support for form files in new form binding

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30644]
### Description

Update this after #30659 closes.
[Support for form files in new form binding](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-2/#support-for-form-files-in-new-form-binding)

Probably put it under [Explicit binding from form values](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0#explicit-binding-from-form-values)

See https://github.com/dotnet/aspnetcore/pull/49935

Also update WN

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md

### Version Independent Document ID

b09824ab-b051-75a1-13b7-b0e281cc46e0

### Article author

Rick-Anderson

---
[Associated WorkItem - 169118](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169118)

**Comment by Rick-Anderson** [comment]
@guardrex  I take it this is not a Blazor issue?

**Comment by guardrex** [comment]
Not directly if that's only for form binding. Indirectly tho ... conceptually ... I need to check on antiforgery support with some of the controllers that are in used around the Blazor docs (e.g., the `FilesaveConsoller` for uploading files from a Razor component. I'll make a note to investigate it further.
