### ISSUE TITLE
HTTP logging middleware has several new capabilities:

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30642]
Also add to WN doc.

### Description

See [HTTP logging](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-2/#http-logging-extensibility)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-logging/index.md

### Version Independent Document ID

b39594cc-9d1c-611c-e3e7-8755d74253a6

### Article author

Rick-Anderson

---
[Associated WorkItem - 169119](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169119)

**Comment by iamcymentho** [comment]
Hello @tdykstra ,

I noticed this open issue regarding the HTTP logging middleware's new capabilities. I'd like to express my interest in contributing to this. If it's possible, could this issue be assigned to me? I believe my skills and expertise align with the requirements for this task, and I'm eager to work on it.

Looking forward to your response.

**Comment by tdykstra** [comment]
@iamcymentho Thank you for the offer, but I already have [a PR ready to address this issue](https://github.com/dotnet/AspNetCore.Docs/pull/30814). You're welcome to review the PR if you are interested in doing that.
