### ISSUE TITLE
Shorten menu title: How to chose an identity management solution

### ISSUE THREAD

**Issue by damienbod** [dotnet/AspNetCore.Docs#30648]
@JeremyLikness I am cleaning up the Security and Identity/Authentication menus and docs

You created the following doc: **How to chose an identity management solution**

Would it be possible to shorten the menu title so it fits on one line?

Greetings Damien

**Comment by tdykstra** [comment]
How about "Identity management options" or "Identity management choices"

**Comment by damienbod** [comment]
I like both but we already have the following two links pointing to different docs:

-	Community OSS authentication options
-	Identity management solutions

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/

How about just:

**How to choose an identity solution**

I like  "Identity management choices" as well.

**Comment by damienbod** [comment]
@tdykstra  Linked a PR, thanks
