### ISSUE TITLE
Fix include hell in minimal APIs doc.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30657]
### Description

It's difficult to go from the article to the proper MD file. It's vastly complicated by  many  inconsistent include. It's difficult to reason about version specific changes.

Fix this after 8.0 RTW

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md

### Version Independent Document ID

b09824ab-b051-75a1-13b7-b0e281cc46e0

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
@tdykstra  how about renaming aspnetcore/fundamentals/minimal-apis/includes/webapplication.md to webapplication8.md to fix this issue?

**Comment by tdykstra** [comment]
[laugh]         Tom Dykstra reacted to your message:
________________________________
