### ISSUE TITLE
Replace VSCode C# extension with the new DevKit extension

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#30653]
[EDIT by guardrex to remove the Blazor links. Blazor work on this is tracked by #30443]

### Type of issue

Outdated article

### Description

Should the VSCode prerequisites be updated now that the [C# DevKit is released](https://devblogs.microsoft.com/dotnet/csharp-dev-kit-now-generally-available/)?
The new DevKit extension provides a better experience (and will also automatically install the C# extension). 

This change consists of updating the installation steps, and replace the C# extension with the new C# DevKit extension.

If accepted, I can create a PR with the needed changes.

Besides the generic VSCode prerequisites (e.g. https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/includes/net-prereqs-vsc-8.0.md) that affect multiple pages, the following pages also need to be updated because these reference the C# extension:

- https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vscode?view=aspnetcore-7.0#prerequisites
- https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-5.0&tabs=visual-studio-code
- https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-5.0&tabs=visual-studio-code

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Version Independent Document ID

ab408035-6313-a183-9940-32de00e0e977

### Article author

wadepickett

**Comment by guardrex** [comment]
Thanks @timdeschryver ... The Blazor items are already tracked separately by https://github.com/dotnet/AspNetCore.Docs/issues/30443, so I'm going to remove those from your OP. The docs cats 🐱 will take care of the non-Blazor articles.

**Comment by wadepickett** [comment]
@timdeschryver, Don't create the PR,  I will go ahead and make the change however across all tutorials (except blazor which guardrex is on) once I review.   Thanks for the awesome offer though! We did have a previous issue where devkit seemed to be suppressing the pop-up to build assets on new ASP.NET projects which would cause problems for new users.  That may have been corrected though, I will test with the latest version.

**Comment by wadepickett** [comment]
I re-tested the latest C# DevKit extension v0.5.150 for Visual Studio Code.  It still suppresses the offer to build assets for new ASP.NET projects.  So we can't really require it as a prereq to tutorials for ASP.NET.  It is not an actual requirement and unfortunately also causes this unexpected problem for folks creating new projects on the command line.

Here is an example of steps to reproduce.  

**Expectation: ** You get the auto request to create the build assets for debugging after creating a new ASP.NET project on the  command line.

**Actual outcome: ** The request to add assets for debugging never shows if devkit is installed.

**Steps**

Select New Terminal from the Terminal menu to open the integrated terminal.

Change to the directory (cd) that will contain the project.

Run the following commands (in this case to create a new RazorPages app:

```.NET CLI
dotnet new webapp -o RazorPagesApp
code -r RazorPagesApp
```

The dotnet new command creates a new Razor Pages project in the RazorPagesApp folder.

The code command opens the RazorPagesApp project folder in the current instance of Visual Studio Code.

Visual Studio Code might display a dialog box that asks: Do you trust the authors of the files in this folder?  Choose to trust.

At this point VSC should request to add assets to build and debug the project.  However, if DevKit is installed, it will not.

**Comment by wadepickett** [comment]
@guardrex, closing.  See my reasoning directly above.  If you don't agree, let me know, maybe I missed something.

**Comment by guardrex** [comment]
Thanks, I'll take a look at this when I reach the Blazor Debug doc. I'm not sure when that will be, but I should reach it by RTM 😅.
