### ISSUE TITLE
code sample needed for form binding

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#30659]
### Description

Write code for [Support for form files in new form binding](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-rc-2/#support-for-form-files-in-new-form-binding) at https://github.com/dotnet/AspNetCore.Docs.Samples/tree/main/fundamentals/minimal-apis/samples/IFormFile

I think you can just slightly modify [this sample](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/parameter-binding/samples8/Iform/Program.cs)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md

### Version Independent Document ID

b09824ab-b051-75a1-13b7-b0e281cc46e0

### Article author

Rick-Anderson

cc @timdeschryver @fiyazbinhasan @sammychinedu2ky 

---
[Associated WorkItem - 169367](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169367)

**Comment by sammychinedu2ky** [comment]
I would work on it
