### ISSUE TITLE
The type or namespace name 'Counter' could not be found

### ISSUE THREAD

**Issue by behnamasaei** [dotnet/AspNetCore.Docs#30708]
### Description

error CS0246: The type or namespace name 'Counter' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "WinFormsBlazor.csproj" -- FAILED.

** Counter.razor in root of solution

Form.cs
var services = new ServiceCollection();
            services.AddWindowsFormsBlazorWebView();
            blazorWebView1.HostPage = "wwwroot\\index.html";
            blazorWebView1.Services = services.BuildServiceProvider();
            blazorWebView1.RootComponents.Add<Counter>("#app");
            
            

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-7.0#create-a-windows-forms-blazor-project

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/windows-forms.md

### Document ID

b0b88d48-74df-8dc4-446d-121e65b552ab

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @behnamasaei ... Can you check and confirm that you used a ***`BlazorWebView` control***?

There's a step that calls out making sure that you're placing the correct control. It's where the article says ...

> Be careful not to accidentally drag a WebView2 control into the form.

If you accidentally use a plain `WebView2`, I think it throws that error.
