### ISSUE TITLE
Blazor support, lowest browser version numbers

### ISSUE THREAD

**Issue by dotnetKyle** [dotnet/AspNetCore.Docs#30712]
### Description

If we know the lowest versions of the browser that Blazor has been tested on: can we update this documentation to reflect those numbers?  

Just saying `Current` for each support browser isn't all that helpful. What would be much more helpful is something like `Chrome 57+` if we know those numbers.  Coming from an enterprise point of view, we are not always on the most current version of a browser. I just ran into an issue where my Blazor WASM app didn't run properly inside Firefox and I would love to know what version to show a not supported message for all of the browsers and I would also love to be able to tell my system administrators what versions of the browser are the minimum.

Here is an example from the current version of the document:

> ## Blazor WebAssembly
> 
> | Browser                     | Version               |
> | --------------------------- | --------------------- |
> | Apple Safari                | Current&dagger;       |
> | Google Chrome               | Current&dagger;       |
> | Microsoft Edge              | Current&dagger;       |
> | Microsoft Internet Explorer | Not Supported&Dagger; |
> | Mozilla Firefox             | Current&dagger;       |
> 
> &dagger;*Current* refers to the latest version of the browser.  
> &Dagger;Microsoft Internet Explorer doesn't support [WebAssembly](https://webassembly.org).

My suggestion would be something more like this:

> ## Blazor WebAssembly
> 
> | Browser                     | Version               |
> | --------------------------- | --------------------- |
> | Apple Safari                | 11+*       |
> | Google Chrome               | 57+*       |
> | Microsoft Edge              | 16+*       |
> | Microsoft Internet Explorer | Not Supported&Dagger; |
> | Mozilla Firefox             | 52+*       |
> 
> \* These are just an example numbers. I got these numbers from the browser support table on [MDN](https://developer.mozilla.org/en-US/docs/WebAssembly#browser_compatibility) and the version numbers are based on basic web assembly support. I assume the actual Blazor WASM support numbers would be different.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/supported-platforms?view=aspnetcore-6.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/supported-platforms.md

### Document ID

b03c3cec-a3de-d563-d0f8-45fabfb39758

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @dotnetKyle ... No, we can't do that. What you see is ***exactly*** what the product unit wants to tell devs. They support some variable level of prior browsers ***within reason***, but we can't say what that is. It depends on a problem and what browser is failing, which the team would learn about from an issue opened on their repo for investigation. This question has been asked and answered several times, and that's the final answer on it.
