### ISSUE TITLE
.NET 7 DI documentation references KeyedServices, but that appears only on .NET 8 API documentation

### ISSUE THREAD

**Issue by cbittencourt** [dotnet/AspNetCore.Docs#30741]
### Description

The Keyed Services section does not seem to belong in the .NET 7 version of the Dependency Injection documentation. 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0#keyed-services

The API does not include those methods. We did not find a nuget package that'd provide that implementation. 
  * .NET 7 docs missing extension methods: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions?view=dotnet-plat-ext-7.0
  * .NET 8 docs showing extension methods: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions?view=dotnet-plat-ext-8.0

If there's a specific package that we should install to enable this, could that be included in the Dependency Injection documentation?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0#keyed-services

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md

### Document ID

2251f557-dd3a-ec35-2558-6243337db009

### Article author

Rick-Anderson

**Comment by tdykstra** [comment]
Keyed services belongs in the .NET 8 version of the docs, I'm moving it now. Thanks for reporting this.
