### ISSUE TITLE
Example Code does not compile

### ISSUE THREAD

**Issue by philip-reed** [dotnet/AspNetCore.Docs#30789]
### Description

The example code provided for `CustomAccountFactory.cs` does not compile when copied to Visual Studio.
Specifically, the following lines which call `.Request()`:

` var request = client.Me.Request();`

`var memberships = await requestMemberOf.Request().GetAsync();`

Is there a missing Package Reference, or is the documentation using an older version of the package?

![image](https://github.com/dotnet/AspNetCore.Docs/assets/7798175/6254a7a5-b561-44f3-b708-d4195f7cfc3b)

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/microsoft-entra-id-groups-and-roles?view=aspnetcore-7.0#custom-user-account

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/microsoft-entra-id-groups-and-roles?view=aspnetcore-7.0#scopes

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/microsoft-entra-id-groups-and-roles.md

### Document ID

4088c5ca-39c2-9bed-ebc5-683d3441b615

### Article author

guardrex

**Comment by guardrex** [comment]
I'll try to take a look at this one today. I just need to get through some .NET 8 migration work first.

**Comment by guardrex** [comment]
Yes, I think I see the problem. This article hasn't been updated for Graph SDK v5. I think it will adopt the pattern more like ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/graph-api?pivots=graph-sdk-5&view=aspnetcore-7.0#customize-user-claims-using-the-graph-sdk

The code in the topic pertains to v4. The update will drop the use of `ActivatorUtilities` in favor of a `new GraphServiceClient`.

I can upgrade it fairly fast ... ***but*** I do need to get the .NET 8 migration guidance on track first.

I'll try to get this done by EOD.

**Comment by guardrex** [comment]
Ok ... I'm free now ... I'll about updating this code. I'm going to do the same thing here that I did in the *Graph API* article. I'll make a v4 versus v5 ***pivot***. I'll update the code for the v5 pivot.

**Comment by philip-reed** [comment]
> Which Graph SDK version are you using v4 or v5? They might (probably, actually) have changed something between v4 and v5. That might be why it's breaking.

Yea I think I had selected v5. Good spot.

**Comment by guardrex** [comment]
I just about have it ........ 🤔 ***I think*** 😆. The transition to v5 for this code is fairly clean and easy. I'll have the PR up shortly for you to look at.
