### ISSUE TITLE
app.MapRazorPages(); is not correct for razor pages

### ISSUE THREAD

**Issue by lukos** [dotnet/AspNetCore.Docs#30809]
### Description

I was trying to add Razor pages into an existing .Net 6.0 MVC core project and found this page. It says to use `app.MapRazorPages();` but that doesn't work. Instead, I need to use `endpoints.MapRazorPages()` inside `app.UseEndpoints()`

I don't know if I have misunderstood something but it looks like the doc is wrong.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-6.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/razor-pages-start.md

### Document ID

5492c641-af15-64b8-beaa-ddf511be73e6

### Article author

wadepickett

**Comment by wadepickett** [comment]
Thanks for the heads up.  The 6.0 may have been accidentally updated at some point when updated to 7.0 or 8.0.  I will take a look and retest the entire 6.0 series.

**Comment by Rick-Anderson** [comment]
[MapRazorPages](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.razorpagesendpointroutebuilderextensions.maprazorpages?view=aspnetcore-6.0) APPLIES to 3.0 and later.

**Comment by lukos** [comment]
OK, I think the confusion is that my net6 app uses the traditional `Startup.cs` model with `Configure(IApplicationBuilder)` which means that `MapRazorPages` has to be added inside `UseEndpoints()` instead of directly on the `IApplicationBuilder`.

Thanks
