### ISSUE TITLE
8.0:  gRPC: Named pipes support should only be on 8.0 version not earlier versions of topic

### ISSUE THREAD

**Issue by himanshuz2** [dotnet/AspNetCore.Docs#30823]
### Description
(Added by WadePickett)
- Only the 8.0 version of this topic should mention named pipes support, but it is also on earlier versions of the doc which should be removed.  Support for named pipes in Kestrel was added starting with .NET 8 preview 1.   See https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#support-for-named-pipes-in-kestrel  (as guardrex kindly pointed out)

- The doc also needs to be moved to the new include file versioning architecture.

Original description before we realized the issue was the named pipes content should have only been on the 8.0 version of the content but was applied to earlier versions:

The ServerOptions.ListenNamedPipe is defined in the Microsoft.AspNetCore.App.Ref package but it cannot be referenced via Nuget.

NU1213: The package Microsoft.AspNetCore.App.Ref 7.0.13 has a package type DotnetPlatform that is incompatible with this project. 

From web search tried this option but that didn't work either.
<Project Sdk="Microsoft.NET.Sdk.Web">

  ......

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/interprocess.md

### Document ID

3d706460-ea6a-59f2-05d7-8a3c9f02e211

### Article author

JamesNK

**Comment by wadepickett** [comment]
@JamesNK, is there guidance I should add here in the Inter-process communications section?

Sidenote: Microsoft.AspNetCore.App.Ref per NuGet  is not meant to be used as a normal package reference; it is meant as an internal implementation of the .NET Core SDK.

**Comment by himanshuz2** [comment]
I tried this. It didn't add the option for ListenNamedPipes.
<Project Sdk="Microsoft.NET.Sdk.Web">

  ......

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>

**Comment by guardrex** [comment]
@himanshuz2 ... Is your app targeting the 8.0 preview?

**Comment by guardrex** [comment]
Yeah ... I think that API is 8.0 ...

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-1/#support-for-named-pipes-in-kestrel

If that's correct, it looks like the updates weren't versioned that way in the article.

**Comment by himanshuz2** [comment]
Thank you much appreciated.

**Comment by guardrex** [comment]
Sure thing!

@wadepickett might re-open this and work on the article. I think they'll end up applying different versioning so that this content only shows up for 8.0+.

**Comment by guardrex** [comment]
It changed at some point after the initial PR went in on ...

https://github.com/dotnet/AspNetCore.Docs/pull/28129/files

... that PR has the article at 8.0+. Later, I guess it was changed to 5.0+.

**Comment by wadepickett** [comment]
Thanks @guardrex!  

Yes, reopening and will so all versions are what they should be.  Adding notes to description..
