### ISSUE TITLE
gRPC-Web: requires code samples and instruction updates for v6-8, references startup.cs

### ISSUE THREAD

**Issue by markmcdelm** [dotnet/AspNetCore.Docs#30836]
### Description

(added by WadePickett)
This topic and its code samples need to be updated for versions 6-8.  It still references startup.cs.  Update, test out app samples for each, verify instruction, features up to date.

(Original description)
I want to add gRpc-web functionality to my ASP.NET Core 7.0 project.  The instructions tell me to add some lines to startup.cs but I do not have a startup.cs file, which I think is because my project uses minimal API.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/grpcweb.md

### Document ID

54326b95-f14d-f0e2-cfcb-7280b10b064a

### Article author

JamesNK

---
[Associated WorkItem - 182960](https://dev.azure.com/msft-skilling/Content/_workitems/edit/182960)

**Comment by wadepickett** [comment]
Thanks @markmcdelm, you are right, this topic really needs an update.  We will get it fixed.  Sorry for the bad experience.
