### ISSUE TITLE
Blazor LifeCycle picture and SetParametersAsync

### ISSUE THREAD

**Issue by henk787** [dotnet/AspNetCore.Docs#30855]
### Description

The picture suggests that SetParametersAsync is only called during the First render. It actually is called on each re-render. 

This leads to some misinforamtion, it is stated more directly as a fact [here](https://www.telerik.com/blogs/blazor-basics-blazor-component-re-rendering) for example. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-7.0&source=docs

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @henk787 ... This type of issue appears a few times a year asking about the accuracy of the diagrams and text, and I've checked multiple times with the product unit engineers. Each time, they say that the diagrams and text are an oversimplification and that this is exactly what they want to show and explain. We added the following to the topic to cover it ...

> This article simplifies component lifecycle event processing in order to clarify complex framework logic. You may need to access the [ComponentBase reference source](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Components/src/ComponentBase.cs) to integrate custom event processing with Blazor's lifecycle event processing.

> The following simplified diagrams illustrate Razor component lifecycle event processing.
