### ISSUE TITLE
Documentation for ValidateScopes and ValidateOnBuild in minimal apis

### ISSUE THREAD

**Issue by mehdihadeli** [dotnet/AspNetCore.Docs#30878]
Hi,
I can't find any documentation that says `ValidateScopes` and `ValidateOnBuild ` are enabled by default in the `Development` mode in minimal APIs and `WebApplicationBuilder`. I think [`this doc`](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scope-validation) should be enhanced for clarifying `ValidateScopes` and `ValidateOnBuild`  for both minimal and none-minimal api host builders

for example:
>  `CreateDefaultBuilder` and `WebApplicationBuilder` in minimal apis sets `ServiceProviderOptions.ValidateScopes` and `ServiceProviderOptions.ValidateOnBuild` to true if the app's environment is Development.

***EDIT by @Rick-Anderson add the folllowing meta-data***
### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis.md

### Document ID

b09824ab-b051-75a1-13b7-b0e281cc46e0

### Article author

Rick-Anderson

---
[Associated WorkItem - 177294](https://dev.azure.com/msft-skilling/Content/_workitems/edit/177294)

**Comment by Rick-Anderson** [comment]
@thomaslevesque  @mehdihadeli  That's not the results I'm getting from the following code:

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

if (app.Environment.IsDevelopment())
    Console.WriteLine("Development environment");
else
    Console.WriteLine("Release environment");

builder.Host.UseDefaultServiceProvider(options =>
{
    Console.WriteLine($"ValidateScopes = {options.ValidateScopes}");
    Console.WriteLine($"ValidateOnBuild = {options.ValidateOnBuild}");
});

app.MapGet("/", () => "Hello World!");

app.Run();

// OUPUT:
//Development environment
//ValidateScopes = False
//ValidateOnBuild = False
```

**Comment by thomaslevesque** [comment]
Uh. I was pretty sure ValidateScopes was enabled in Development. Maybe it has changed at some point?

**Comment by Rick-Anderson** [comment]
@captainsafia  I'm closing this issue because it's not true. See the following code

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

if (app.Environment.IsDevelopment())
    Console.WriteLine("Development environment");
else
    Console.WriteLine("Release environment");

builder.Host.UseDefaultServiceProvider(options =>
{
    Console.WriteLine($"ValidateScopes = {options.ValidateScopes}");
    Console.WriteLine($"ValidateOnBuild = {options.ValidateOnBuild}");
});

app.MapGet("/", () => "Hello World!");

app.Run();

// OUPUT:
//Development environment
//ValidateScopes = False
//ValidateOnBuild = False
```

**Comment by Rick-Anderson** [comment]
On further examination, the following code doesn't write the correct state:

```
builder.Host.UseDefaultServiceProvider(options =>
{
    Console.WriteLine($"ValidateScopes = {options.ValidateScopes}");
    Console.WriteLine($"ValidateOnBuild = {options.ValidateOnBuild}");
});
```

The following code throws in development but not release mode:

```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddScoped<MyScopedService>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    Console.WriteLine("Development environment");
}
else
{
    Console.WriteLine("Release environment");
}

app.MapGet("/", context =>
{
    // Intentionally getting service provider from app, not from the request
    // This causes an exception from attempting to resolve a scoped service
    // outside of a scope.
    var service = app.Services.GetRequiredService<MyScopedService>();
    return context.Response.WriteAsync( "Service resolved");
});

app.Run();

public class MyScopedService { }
```

**Comment by Rick-Anderson** [comment]
@thomaslevesque  @mehdihadeli  see https://github.com/dotnet/AspNetCore.Docs.Samples/pull/237 which provides sample code to demonstrate this issue.
