### ISSUE TITLE
Link doesn't open in a new tab

### ISSUE THREAD

**Issue by playground0076** [dotnet/AspNetCore.Docs#30870]
### Description

refit link should open in a new tab as the icon next to the hyperlink suggests but it opens in the same tab.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#generated-clients

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md

### Document ID

3d356334-e672-7e8b-1fef-7944ebee99eb

### Article author

stevejgordon

**Comment by Rick-Anderson** [comment]
That's not how it works.
