### ISSUE TITLE
LocationChanged event and location changing handlers interaction with enhanced navigation 8.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#30876]
### Description

> When an enhanced navigation occurs, LocationChanged event handlers registered in interactive runtimes (i.e., Blazor Server/WebAssembly) get invoked. However, location changing handlers may or may not intercept enhanced navigations, so it's important that app logic not rely on location changing handlers being invoked reliably. For example, the user might switch to another page before an interactive runtime becomes available. In .NET 8, if server-side routing and enhanced navigation are enabled, location changing handlers will only get invoked for programmatic navigations initiated from an interactive runtime. In future .NET versions, more types of navigations (e.g., link clicks) may also invoke location changing handlers"

Per https://github.com/dotnet/aspnetcore/issues/51436#issuecomment-1786018976

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

guardrex

**Comment by garrettlondon1** [comment]
@guardrex I just read https://github.com/dotnet/aspnetcore/issues/51436 coincidentally and just want to clarify:

If you are rendering a fully static page with an InteractiveServer island
- That island depends on catching external navigations

The InteractiveServer island will be unable to catch **any** LocationChanged events outside of its HTML purview? The only solution is to make the entire surrounding page Interactive with pre-rendering?

**Comment by guardrex** [comment]
Due to the complexity of the question, it's best to open a product support request on that ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex
```

... your opening issue comment so that I can follow the discussion.
