### ISSUE TITLE
Invalid console commands

### ISSUE THREAD

**Issue by BSarmady** [dotnet/AspNetCore.Docs#30883]
### Description

In almost all console commands for .NET Core CLI command to invoke entityframwork core is specified as 

`dotnet ef`

which does not run, it should be 

`dotnet-ef`

This is at least true for .NET 7 and above. If it was different for previous versions, I think a note should be added on top of document, or multiple versions of the command specified for each console command.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md

### Document ID

3e25547b-e2c9-6634-2c38-2a77207f17d4

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
Hello @BSarmady ... This question has come up a few times over the years, but it's never matched their docs ...

https://learn.microsoft.com/en-us/ef/core/cli/dotnet

... and there's nothing in their docs on it AFAICT. I also checked their repo for issues, but a scan didn't turn anything up. It would be nice to get to the bottom of it to understand why some devs face this.

**Comment by guardrex** [comment]
I researched this further, and nothing states the dash should be in the command name when an EF Core tools command is being executed. One passing remark by Kirk to a dev who seemed to have this problem said that it might be a PATH problem. Another passing remark about it said that it might be required when using Docker.

@BSarmady ... I think you'll need to seek assistance over on the EF Core repo if you can't get it working without the dash ...

https://github.com/dotnet/efcore/issues

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/ef/core/get-started/overview/install#get-the-net-core-cli-tools

**Comment by BSarmady** [comment]
@guardrex, You are right, it does look like a path issue, but the actual problem is I am not the one setting the path, it is Visual Studio Installer or SDK installer. Each of them adds a different path to Environment which then causes one  or other one unavailable.

In Either case, a few solution would come to mind

1. Since I can reach document people but do not have access to VS or SDK devs, a note in document should explain that in Visual Studio it would be one and in SDK (Core CLI) would be other one.
1. If someone from document team can reach SDK team, convince them to 
  - Make one of the VS or SDK follow the other one and change the path
  - Put all executable in same folder so both dotnet ef and dotnet-ef so both are available.


@Rick-Anderson I'm not installing SDK myself, it is installed by Visual Studio installation.

**Comment by guardrex** [comment]
> access to VS ... devs

The **Report a Problem** feedback gesture from within VS opens a work item for the VS team.

> access to ... SDK devs

Can be reached via their repo at https://github.com/dotnet/sdk/issues. Be sure to search their issues (open and closed) first to see if you can find one or more existing issues on this problem.

Over the years, several devs have opened issues on our repo asking for the commands to be changed. When we inquired with the product unit several years ago about this, I only recall that we were told that the non-dashed versions of the commands are the correct commands to show. However, I don't recall if they said anything about why this is happening or how to fix it. Even if they had told us, we wouldn't be able to address it cleanly here, as we only handle *ASP.NET Core framework docs*, not CLI command docs. They have a separate repo at https://github.com/dotnet/docs/issues ... and you might want to search there (again, open and closed issues) to see if this subject has come up. It seems to me, based on a quick look, that the following doc would be a great place to describe this problem and how to fix it, so you might want to open an issue from the bottom of this article asking them if they would entertain covering this problem ...

https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues

... and they have some info there on PATHs for global tools. See if those remarks help at all.

**Comment by BSarmady** [comment]
@guardrex , Thank you for update, I'm not sure what was changed in my PC in past few days that now I can run both commands.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/2040435/f0e1e9a7-018d-4db6-8cc5-f9c66874149d)

probably I have added path to tools myself. My suggested note was something like (using the helpful link you have provided)

> "If "dotnet ef" does not work try using "dotnet-ef" instead, refer to [Troubleshoot .NET tool usage issues](https://learn.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues) document for more details"

Interestingly the first table in the page mentions that executable name is `dotnet-<toolName>.exe` and can run with `dotnet <toolName>` which means if there is an executable with that name in path, it will for sure can run and `dotnet <toolname>` is just an `alias` to invoke that executable (I doubt it is the other way).

Anyway, if you won't be able to add the note to document you can close this comment, since my issue is resolved.

Thank you for your time and effort

**Comment by guardrex** [comment]
I'm glad you got it working.

First, I'm not clear if that article has the right information for a cross-link. I saw something about PATHs there, but I didn't think the lead-in text made it sound like their PATH remarks were directly related to the command being found and working with the dash or not. I think they'd need to update that doc to even make a cross-link possible.

Second, I don't think that @Rick-Anderson and the team will want to apply a NOTE like this because we'd be required to place it in ***MANY*** places around our doc set for a problem that like <1% of devs face. I speculate that I've seen issues for this problem opened less than a dozen times in the ~6-7 years that I've been here. That's not enough to warrant a call out given that we've had hundreds of thousands of devs consume these docs.

My recommendation (if their *Troubleshoot* doc doesn't call this problem out clearly where they discuss PATH problems) is for you (or one of us ... I'll do it) to open an issue on their article and explain that this is happening and that the section could use some improved lead-in remarks, namely that the problem manifests itself as the command runs with a dash but not without it.
