### ISSUE TITLE
Wrong code extract with app.MapHealthChecks() ; should be endpoints.MapHealthChecks() 

### ISSUE THREAD

**Issue by ericbl** [dotnet/AspNetCore.Docs#30899]
### Description

The aspnet documentation about healthchecks is correctly explaining at the bottom the difference between UseHealthChecks vs. MapHealthChecks, but manages to propose WRONG code extract with them.

As seen in the linked source code of [UseHealthChecks](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckApplicationBuilderExtensions.cs) and [MapHealthChecks](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs), they both use different object, 

```
UseHealthChecks(this IApplicationBuilder app, ...)
MapHealthChecks( this IEndpointRouteBuilder endpoints, ...)
```

so any reference to 
`app.MapHealthChecks(...);`

is just WRONG!

it should be in the 

```
 app.UseEndpoints(endpoints =>
         {
                endpoints.MapHealthChecks(...);
                endpoints.MapControllers();
     }

```

please fix the doc accordingly!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-6.0#entity-framework-core-dbcontext-probe

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md

### Document ID

52d8efc9-a336-71d9-6d90-98173cbf6bf4

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
> so any reference to  `app.MapHealthChecks(...);`  is just WRONG!

[Google `app.MapHealthChecks`](https://www.google.com/search?q=%22app.MapHealthChecks%22&rlz=1C1RXQR_enUS990US990&oq=%22app.MapHealthChecks%22&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQABiABDIGCAIQABge0gEIMzg5N2owajeoAgCwAgA&sourceid=chrome&ie=UTF-8#ip=1) and you get hundreds of authoritive hits. Are they all wrong?

**Comment by ericbl** [comment]
I might have missed something (like an extension), but the code can not get compiled on my side.
So yes, please precise how to get app.MapHealthChecks working!
