### ISSUE TITLE
Please add a warning concerning app.MapHealthChecks() that app is WebApplication  and not IApplicationBuilder 

### ISSUE THREAD

**Issue by ericbl** [dotnet/AspNetCore.Docs#30905]
### Description

The aspnet documentation about healthchecks is correctly explaining at the bottom the difference between UseHealthChecks vs. MapHealthChecks

As seen in the linked source code of [UseHealthChecks](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckApplicationBuilderExtensions.cs) and [MapHealthChecks](https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HealthChecks/src/Builder/HealthCheckEndpointRouteBuilderExtensions.cs), they both use different object, 

```
UseHealthChecks(this IApplicationBuilder app, ...)
MapHealthChecks(this IEndpointRouteBuilder endpoints, ...)
```

The doc page is using a few references to 
`app.MapHealthChecks(...);`

where app is from 
`WebApplication app = builder.Build();`
WebApplication implements IEndpointRouteBuilder so no issue in the logic.

BUT for those still having complex startup configuration and still using the old Startup.cs with

`public virtual void Configure(IApplicationBuilder app, ...)`

app here does NOT implement the IEndpointRouteBuilder.
The correct way is then
```
 app.UseEndpoints(endpoints =>
         {
                endpoints.MapHealthChecks(...);
                endpoints.MapControllers();
     }
```

please add a warning in the documentation page to remove the confusion.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-7.0&branch=pr-en-us-29439

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md

### Document ID

52d8efc9-a336-71d9-6d90-98173cbf6bf4

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
See https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0&branch=pr-en-us-29439#usehealthchecks-vs-maphealthchecks

**Comment by ericbl** [comment]
You apparently don't get my point. I give up.
