### ISSUE TITLE
Non-standard or well-known terminology used

### ISSUE THREAD

**Issue by istoyneva** [dotnet/AspNetCore.Docs#30901]
### Description

[Enter feedback here]
There is a reference to IIS "sub application", but it's coupled with the term "forked pipeline" and that renders the section less useful.

It would be helpful to illustrate "forked pipeline" with an example or provide a formal definition of "forked pipeline"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md

### Document ID

c82cf121-831d-75dd-a796-c735aad3b3e9

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @istoyneva ... I'll take a closer look at this tomorrow morning and get back to you.
