### ISSUE TITLE
Update .NET 8 Docs for Claim Mapping

### ISSUE THREAD

**Issue by rudiv** [dotnet/AspNetCore.Docs#30935]
### Description

As of .NET 8 Preview 7, the referenced code under `Claims namespaces, default namespaces` will no longer work.

It suggests calling `JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();` which is now `JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear();`.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0#claims-namespaces-default-namespaces

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/claims.md

### Document ID

b01e1351-d362-fd61-4dcb-bacb21559f76

### Article author

damienbod

**Comment by damienbod** [comment]
I can do this, @rudiv  thanks for reporting

Greetings Damien

**Comment by rudiv** [comment]
@damienbod awesome, I'm not sure if it's worth suggesting the new `MapInboundClaims = false` option rather than this though? This is global whereas the option is per scheme.

**Comment by terryaney** [comment]
> @damienbod awesome, I'm not sure if it's worth suggesting the newer `MapInboundClaims = false` option rather than this though? This is global whereas the option is per scheme.

Isn't [it saying the opposite](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/claims.md#claims-namespaces-default-namespaces)?

> If you need to disable the namespaces per scheme and not globally, you can use the `MapInboundClaims = false` option.

**Comment by jgga16** [comment]
Thanks, Is Ok
