### ISSUE TITLE
Update-Database fails on basic build of a demo site

### ISSUE THREAD

**Issue by bizinbarefeet** [dotnet/AspNetCore.Docs#30941]
### Description

[Enter feedback here]
Update-Database : The term 'Update-Database' is not recognized as the name of a cmdlet, 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md

### Document ID

0e0d870e-e49a-e16c-c259-68d58e701b8f

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/ef/core/cli/powershell#update-database
