### ISSUE TITLE
Can't use {PORT} in Authorized redirect URI

### ISSUE THREAD

**Issue by SSteve** [dotnet/AspNetCore.Docs#30961]
### Description

Under **Create the Google OAuth 2.0 Client ID and secret** the Authorized redirect URI can't be set to `https://localhost:{PORT}/signin-google`. It results in two errors: "Invalid Redirect: must end with a public top-level domain (such as .com or .org)." and "Invalid Redirect: must use a domain that is a valid [top private domain ](https://github.com/google/guava/wiki/InternetDomainNameExplained#public-suffixes-and-private-domains)."

It can be set to `https://localhost/signin-google`.
<img width="523" alt="Screenshot 2023-11-07 at 12 41 52 PM" src="https://github.com/dotnet/AspNetCore.Docs/assets/523551/993935b0-f19a-43aa-bd97-8cddc9145bb6">

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/social/google-logins.md

### Document ID

747a179e-90b7-de07-e270-82414963048a

### Article author

Rick-Anderson

**Comment by guardrex** [comment]
Hello @SSteve ...

> ... where the `{PORT}` placeholder is the app's port.
