### ISSUE TITLE
TargetFramework- 7.0 | Index.cshtml.cs line 27

### ISSUE THREAD

**Issue by vvgonline** [dotnet/AspNetCore.Docs#30973]
**ERROR**:: Argument 2: cannot convert from 'int' to 'System.Threading.CancellationToken' [CS1503] | (parameter) int id

**Comment by guardrex** [comment]
Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and indicates the author. For some articles, it will even ping the author automatically for a faster response.
