### ISSUE TITLE
argetFramework- 7.0 | Index.cshtml.cs

### ISSUE THREAD

**Issue by vvgonline** [dotnet/AspNetCore.Docs#30978]
### Description

[Index.cshtml.cs](https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#the-home-page)
`var contact = await _context.Customer.FirstAsync(id);`
ERROR:: Argument 2: cannot convert from 'int' to 'System.Threading.CancellationToken' [CS1503] | (parameter) int id

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-7.0&tabs=visual-studio#the-home-page

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md

### Document ID

b3e2bc87-1582-2d34-c7c2-7c8e901ac771

### Article author

tdykstra

**Comment by Rick-Anderson** [comment]
`FirstAsync` is not used on that page. I think you have a typo for `FindAsync`
