### ISSUE TITLE
docker image default port changed

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/AspNetCore.Docs#30971]
### Description

Since .NET 8 docker image default port changed from 80 to 8080, should we mention it in the docker section

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#convert-a-blazor-server-app-into-a-blazor-web-app

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/70-80.md

### Document ID

534ab561-09c5-c33b-4394-0effba34d666

### Article author

Rick-Anderson

**Comment by Rick-Anderson** [comment]
https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
