### ISSUE TITLE
Blazor migration: compression enabled property

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#30979]
### Description

This has already been covered in the Blazor ref docs. 

Add it to the Migration doc.

Also, check on this ...

> MSBuild properties with the name Blazor in them

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/70-80.md

### Document ID

534ab561-09c5-c33b-4394-0effba34d666

### Article author

guardrex

**Comment by guardrex** [comment]
@MackinnonBuck ... WRT the remark that I saw ...

> The Static Web Assets feature was moved from the Blazor WebAssembly SDK into its own SDK in .NET 8. As part of this work, MSBuild properties with the name Blazor in them were renamed to indicate that they are not limited to Blazor scenarios.

I can't find the PU issue/PR (in our repo or the SDK repo) for that work. What other properties were renamed as part of that effort?

... and generally speaking, there are other "Blazor"-named MS Build properties/items out there. Is everything else stable for this release?

* `BlazorWebAssemblyLoadAllGlobalizationData`
* `BlazorEnableTimeZoneSupport`
* `BlazorWebAssemblyPreserveCollationData`
* `BlazorWebAssemblyLazyLoad`
* `BlazorWebAssemblyEnableLinking` (3.1 release only)
* `BlazorLinkerDescriptor` (3.1 release only)
* `BlazorWebAssemblyI18NAssemblies` (3.1 only)
* `BlazorCacheBootResources`

**Comment by MackinnonBuck** [comment]
@guardrex It looks like just `BlazorEnableCompression` was renamed.

`BlazorWebAssemblyLoadAllGlobalizationData` - good for 8.0
`BlazorEnableTimeZoneSupport` - good for 8.0
`BlazorWebAssemblyPreserveCollationData` - I can't find any mentions of this in any source code for last the several versions of .NET - @javiercn do you know anything about this?
`BlazorWebAssemblyLazyLoad` - good for 8.0
`BlazorWebAssemblyEnableLinking` - still 3.1 only
`BlazorLinkerDescriptor` - still 3.1 only
`BlazorWebAssemblyI18NAssemblies` - Looks like this was removed starting in 5.0
`BlazorCacheBootResources` - good for 8.0

**Comment by guardrex** [comment]
`BlazorWebAssemblyPreserveCollationData` is a very old one ... 3.1 era ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/performance?view=aspnetcore-3.1#disable-unused-features

I'll make sure `BlazorWebAssemblyI18NAssemblies` is versioned out. I think it is, but I'll check to make sure.
