### ISSUE TITLE
Blazor BWA external/social login guidance 8.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#30994]
### Description

Per https://devblogs.microsoft.com/dotnet/whats-new-with-identity-in-dotnet-8/#add-an-external-login.

Update *Blazor Identity UI (Individual Accounts)* in the Server security doc with a cross-link to the new section.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md

### Document ID

c98be365-408d-7ee6-cb74-14c44d01b0b8

### Article author

guardrex

**Comment by guardrex** [comment]
@JeremyLikness ... Is the OIDC sample from Halter meant to cover this issue? I'm not sure if there was a plan for demonstrating a social login provider, such as Google or FB, with a different sample coming later.

**Comment by JeremyLikness** [comment]
The template for Blazor Web App has it out of the box. You can just add the OIDC package for the social you want, and configure your client id/secret, and it should automatically appear as an option for logging in and work. I tested it with Twitter and had no issues.

Jeremy

**Comment by guardrex** [comment]
Great, then I'll close this out. Thx!
