### ISSUE TITLE
Save and Unsave HTTP  In-Depth explanation 

### ISSUE THREAD

**Issue by MoMakkawi** [dotnet/AspNetCore.Docs#31001]
### Description

We need more in-depth explanation about [safe/unsafe HTTP](https://learn.microsoft.com/en-gb/training/modules/implement-http-operations-asp-razor/) , as I think it would be great to have other examples that clarify the decisive point in terms of code, because I did not find many sources that explain in depth about the difference between Implement unsafe HTTP operations and Implement safe HTTP operations in .Net7 .

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/model.md

### Document ID

7096fdb3-612e-9e00-bd0b-8ea4886a09ce

### Article author

wadepickett

**Comment by wadepickett** [comment]
Thanks @MoMakkawi for the suggestions!  It would be good to point to more detailed information.   This getting started tutorial is long as it is, but a little more information and links to where more details are covered would be helpful and not out of scope.

- [safe/unsafe HTTP](https://learn.microsoft.com/en-gb/training/modules/implement-http-operations-asp-razor/)
- [Fundamentals doc on enforcing HTTPS](https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&tabs=visual-studio%2Clinux-ubuntu#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)

**Comment by MoMakkawi** [comment]
Thank you @wadepickett for your help. I actually read [safe/unsafe HTTP](https://learn.microsoft.com/en-gb/training/modules/implement-http-operations-asp-razor/) many times, But I did not understand all the details in the required depth, as after I took the exam it turned out that I had made a mistake in both of Implement unsafe HTTP operations and Implement safe HTTP. Indeed, as you mentioned, more links would be very useful.

**Comment by BearsPunch** [comment]
So, can anyone explain to me what the difference is in this test between safe and unsafe? Because in my first try, I had safe and unsafe highlighted in green. However, in the second try, only safe HTTP was highlighted in green, even though I'm pretty sure that I did the same thing in both tries.
