### ISSUE TITLE
Out of the box incomprehensible - not working

### ISSUE THREAD

**Issue by stancoffyn** [dotnet/AspNetCore.Docs#31053]
### Description

`app.UseRequestLocalization(new RequestLocalizationOptions()
    .AddSupportedCultures(new[] { "en-US", "es-CL" })
    .AddSupportedUICultures(new[] { "en-US", "es-CL" }));`

This doesn't work at all out of the box, and no reference I can add makes this work. There's no real explanation on how to get this middleware referenced or use. This kind of problem DRIVES ME NUTS. I see this all the time with MS docs, you just don't flipping explain stuff or give me some kind of breadcrumb trail that isn't just some "Hey look at the middleware" yada yada that is so genericized that I cannot figure out what to do. Call me an idiot or whatever, but this is so annoying. Please add some way for this article to work in the first place. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

guardrex

**Comment by guardrex** [comment]
@stancoffyn ... Provide more information ...

* Blazor app type (Blazor Server, Blazor WebAssembly, or Blazor Web App)
* Framework version
* How did you test and confirm that the guidance isn't working?
