### ISSUE TITLE
QuickGrid Demo website crashes when scrolling all the way to the to bottom with the Remote data QuickGrid 

### ISSUE THREAD

**Issue by vegguid** [dotnet/AspNetCore.Docs#31072]
### Description

On the QuickGrid demo site that is linked in the QuickGrid documentation and .NET 8 changelog and go to the section "Remote data" on the page [Data sources](https://aspnet.github.io/quickgridsamples/datasources) and then scroll all the way down on the QuickGrid that is in that section, The website will crash due to a 400 bad request response. 
I'm not sure if this is the right repo to report this as the code isn't here but I could not find any other repo where it would make sense to report this.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?preserve-view=true&view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/quickgrid.md

### Document ID

564e71e3-82ed-ce23-4f9f-a00a58734a62

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @vegguid ... Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues
