### ISSUE TITLE
Kestrel limits are not loaded from appsettings.config

### ISSUE THREAD

**Issue by andriysavin** [dotnet/AspNetCore.Docs#31108]
### Description

At the beginning of the article there is a statement that 

> By default, Kestrel configuration is loaded from the Kestrel section using a preconfigured set of configuration providers.

and a sample is given

``` json
{
  "Kestrel": {
    "Limits": {
      "MaxConcurrentConnections": 100,
      "MaxConcurrentUpgradedConnections": 100
    },
    "DisableStringReuse": true
  }
}
```
However, neither of these settings seems to be loaded from the config, from my observation.
I also peeked at the [KestrelConfigurationLoader](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs) and found no sign of these properties being loaded there.
I also found a [sample](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L154C24-L154C24) where Kestrel options for some reason are loaded manually from the config during startup:

>  options
>                .Configure(context.Configuration.GetSection("Kestrel"), reloadOnChange: true)

So either the documentation page contains wrong information, or this is a bug in the code. Or I'm missing something :)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/options.md

### Document ID

5a5a34c5-1c75-ff17-b3d6-762194391319

### Article author

tdykstra

---
[Associated WorkItem - 203246](https://dev.azure.com/msft-skilling/Content/_workitems/edit/203246)

**Comment by tdykstra** [comment]
@Tratcher, in the introduction section to the [Kestrel Options doc](https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel/options), should we remove the quoted text and sample config:

> By default, Kestrel configuration is loaded from the Kestrel section using a preconfigured set of configuration providers.

> ```json
> {
>   "Kestrel": {
>     "Limits": {
>       "MaxConcurrentConnections": 100,
>       "MaxConcurrentUpgradedConnections": 100
>     },
>     "DisableStringReuse": true
>   }
> }
> ```

The config example illustrates the statement "Kestrel options can also be set using a configuration provider" -- should that read "Some Kestrel options ..." and can you suggest a better example to illustrate the statement?

**Comment by Tratcher** [comment]
@amcasey

**Comment by tdykstra** [comment]
That seems to be correct based on the comments, but there's also the sample that suggests appsettings.json might not be read by default:

>"I also found a [sample](https://github.com/dotnet/aspnetcore/blob/release/7.0/src/Servers/Kestrel/samples/SampleApp/Startup.cs#L154C24-L154C24) where Kestrel options for some reason are loaded manually from the config during startup:"

**Comment by amcasey** [comment]
"By default" is a little fuzzy here.  If you're using the default builder, I believe that _is_ hooked up automatically, but there are certainly code paths where it isn't (e.g. with the `HostBuilder`, as in that sample).  In any case, the text does indicate that "the File Configuration Provider **can** load Kestrel configuration from an appsettings.json or appsettings.{Environment}.json file" [emphasis added].  It's a bit subtle, but that doesn't seem to be the core of the complaint.

**Comment by amcasey** [comment]
Empirically, those settings do end up in the configuration provider, but they _do not_ end up reflected in `KestrelServerLimits`.  Unfortunately, adding that functionality isn't a priority, at the moment (though I agree that it's uncomfortably inconsistent), but we absolutely shouldn't have a sample in the document that doesn't actually work.  The short-term mitigation is probably to pick kestrel configurations that _are_ picked up.  I'll see what I can find.
