### ISSUE TITLE
Guidance on "Set the authentication scheme" causes routing conflict when using "AddInteractiveServerRenderMode"

### ISSUE THREAD

**Issue by RobJDavey** [dotnet/AspNetCore.Docs#31113]
### Description

I am attempting to get access tokens within a new .NET 8 app following the "Server-side ASP.NET Core Blazor additional security scenarios" article which talks about a method for passing these tokens.

Under the "Set the authentication scheme" section it is required to set `RequireAuthorization` on the Blazor Hub:
``` csharp
app.MapBlazorHub().RequireAuthorization(
    new AuthorizeAttribute 
    {
        AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme
    });
```

However this application is using the new interactive server render mode:
``` csharp
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();
```

When `AddInteractiveServerRenderMode` is called, this internally calls `MapBlazorHub()`, and so there are now two hubs mapped to the `/_blazor` endpoint.

This results in an `AmbiguousMatchException` when a component attempts to connect to the Blazor Hub:
``` shell
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 


Blazor initializers
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

The same happens if you follow the guidance on the [ASP.NET Core Blazor SignalR guidance](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0), which states you should
> Place the call to `app.MapBlazorHub` after the call to `app.MapRazorComponents` in the app's `Program` file

As the call to `AddInteractiveServerRenderMode()`  does not return the `ComponentEndpointConventionBuilder` created from the internal `MapBlazorHub` call, it's not clear from the documentation how you are meant to call `RequireAuthorization` for the Blazor Hub under the new .NET 8 method of setting up the applications.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md

### Document ID

c98be365-408d-7ee6-cb74-14c44d01b0b8

### Article author

guardrex

**Comment by guardrex** [comment]
Hello @RobJDavey ... As you can see, I'm still getting the .NET 8 coverage into place. Thanks for remarking on this spot. I'll fix it on Monday. In the meantime, do it this way ...

```csharp
using Microsoft.AspNetCore.Authentication.OpenIdConnect;

...

app.MapRazorComponents<App>().RequireAuthorization(
    new AuthorizeAttribute
    {
        AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme
    })
    .AddInteractiveServerRenderMode();
```

**Comment by RobJDavey** [comment]
Hi @guardrex, thank you for the quick response. Do you know if there is a sample project that demonstrates the contents of the [Server-side ASP.NET Core Blazor additional security scenarios](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-8.0) page, as even with your fix above I am struggling to get this to work. My `TokenProvider` always contains `null` when it is run from an interactive component call, and I've attempted to create a circuit handler as shown in [Access server-side Blazor services from a different DI scope](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-8.0#access-server-side-blazor-services-from-a-different-di-scope) but the `CreateInboundActivityHandler` is never called, so I'm at a bit of a loss as to how to get hold of my OpenIdConnect access tokens when inside an interactive callback safely.

**Comment by guardrex** [comment]
No, there isn't. Such samples must be maintained, and we have limited staffing ... well ... just *me* 🦖 really 😄.

Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Give them an explanation of what you're trying to do, what you've tried, and what's breaking/not working. They tend to prefer that a minimal repro project be placed on GH so that they can see how you've set up your app's code.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31113
```

... to the bottom of your opening comment so that I can follow along. After I see how you and they work out the problem(s), I'll either re-open this issue or create a new issue to address the guidance.

**Comment by RobJDavey** [comment]
I'll put together a sample project, and raise an issue.
I had no idea it was just you, thank you for all the hard work!
