### ISSUE TITLE
Documentation for generic controller

### ISSUE THREAD

**Issue by zmark9** [dotnet/AspNetCore.Docs#31120]
### Description

There are no docs on how to customize swagger when you are using a generic controller. I have found some ideas around setting options in the SwaggerGenOptions class using the Schema filter, but nothing solid. 

![swagger Controller](https://github.com/dotnet/AspNetCore.Docs/assets/32187855/d9fd2686-d126-46d7-a6a6-6cc9cc810eb1)
![swagger Options](https://github.com/dotnet/AspNetCore.Docs/assets/32187855/f5b38024-5c7c-4ea0-92a9-b57b918404f8)
![swagger Program](https://github.com/dotnet/AspNetCore.Docs/assets/32187855/e74c0b3d-de9b-4cd1-ade9-79e820e24e1d)
![swagger UI](https://github.com/dotnet/AspNetCore.Docs/assets/32187855/169df8c0-023a-4e92-a828-b0c12eb3cc43)

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md

### Document ID

59222460-a971-e76e-4fe9-23d4d7d768ee

### Article author

zuckerthoben

**Comment by guardrex** [comment]
Hello @zmark9 ... The doc is only meant to be a "getting started" doc on the subject. The package maintainer keeps the docs in the README file at ...

https://github.com/domaindrivendev/Swashbuckle.AspNetCore

Can you float this to them for coverage there? Also, your question is probably better asked in their repo issues. You'll probably at least get a faster response.
