### ISSUE TITLE
@rendermode InteractiveServer

### ISSUE THREAD

**Issue by joaocolombo** [dotnet/AspNetCore.Docs#31158]
### Description

Error	CS0103	The name 'rendermode' does not exist in the current context	BlazorApp1	C:\SL\BlazorApp1\BlazorApp1\Pages\Index.razor	2	Active

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md

### Document ID

85af7a99-672c-0438-dcc2-e8edfaf70c54

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @joaocolombo ... Did you install the 8.0 SDK (or fully update your VS)? It sounds like you're using one of the preview releases from back when the render mode was specified by `@attribute` and not `@rendermode`.

**Comment by guardrex** [comment]
I'm going to close because I think you'll just need to update to the release SDK. Please post back if that isn't the problem.
