### ISSUE TITLE
Missing Caveat

### ISSUE THREAD

**Issue by CenturySparkle** [dotnet/AspNetCore.Docs#31157]
### Description

[Enter feedback here]
The documentation does not mention the fact that wildcards do not work for URLs like "app-1.*.domain.com"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md

### Document ID

d3f332c4-4c60-039e-0e1e-bc6b11831f87

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
See [SetIsOriginAllowedToAllowWildcardSubdomains](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.cors.infrastructure.corspolicybuilder.setisoriginallowedtoallowwildcardsubdomains) and [Set the allowed origins](https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0#set-the-allowed-origins)
