### ISSUE TITLE
Custom Events is lacking information

### ISSUE THREAD

**Issue by puppetSpace** [dotnet/AspNetCore.Docs#31174]
### Description

I'm trying to follow the example given in the section Custom event arguments, but the documentation is not complete.

```
function eventArgsCreator(event) { 
  return {
    customProperty1: 'any value for property 1',
    customProperty2: event.srcElement.value
  };
```

what 'type' is `event`? what else can I get from it?

```
  blazor.registerCustomEventType('customevent', {
    createEventArgs: eventArgsCreator
  });
```

what else can I pass to registerCustomeEventType? `createEventArgs` cannot possible be the only field or option?

```
<button @oncustomevent="HandleCustomEvent">Handle</button>

@code
{
    private void HandleCustomEvent(CustomEventArgs eventArgs)
    {
        // eventArgs.CustomProperty1
        // eventArgs.CustomProperty2
    }
}
```

how is `@oncustomevent` triggered? I cannot find documentation on how to trigger that function.
On StackOverflow I found this:
```
function OnMarkerClick(pId) {
    const event = new CustomEvent('cityclicked', {
        bubbles: true,
        detail: pId
    });
    document.getElementById('CarteLeaflet').dispatchEvent(event);
}
```

Is this the way to do it? Does not say in the documentation

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @puppetSpace ... One small thing that I see is that a cut-'n-paste 😈 is in the code example ...

```diff
@using namespace BlazorSample.CustomEvents
@using BlazorSample.CustomEvents
```

That's easy enough to fix.

***BUT*** ...  I think there's a regression in the framework or in the docs. I agree ... this guidance doesn't seem to work in a Blazor Web App. `@oncustomevent` isn't firing here either. I'll ping for assistance.

@MackinnonBuck ... In this section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0#general-configuration

... there seems to be a problem for a Blazor Web App.

I'm going to test it in a Blazor WebAssembly app and see what happens.

**Comment by guardrex** [comment]
***Nevermind***, @MackinnonBuck! ... I figured out the problem :tada: and am pushing a PR now to fix it.

**Comment by guardrex** [comment]
WRT your questions ...

> what 'type' is event?

AFAIK, a DOM Event.

> what else can I get from it?

The usual DOM Event instance properties. See the MDN docs ...

https://developer.mozilla.org/en-US/docs/Web/API/Event

> what else can I pass to registerCustomeEventType?

Nothing but the name and options AFAIK. See the reference source for details ...

https://github.com/dotnet/aspnetcore/blob/474d2944dba601440987b328d7044155023c3c14/src/Components/Web.JS/src/Rendering/Events/EventTypes.ts

It's possible that we might eventually expand this documentation with more details; but right now, we'll let devs look at the ref source for further details. It's a low priority until more devs ask for more detail given the high backlog of doc issues that I have to address.

**Comment by puppetSpace** [comment]
> WRT your questions ...
> 
> > what 'type' is event?
> 
> A DOM Event.
> 
> > what else can I get from it?
> 
> The usual DOM Event instance properties. See the MDN docs ...
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Event
> 
> > what else can I pass to registerCustomeEventType?
> 
> Nothing but the name and options AFAIK. See the reference source for details ...
> 
> https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Rendering/Events/EventTypes.ts
> 
> It's possible that we might eventually expand this documentation with more details; but right now, we'll let devs look at the ref source for further details. It's a low priority until more devs ask for more detail given the high backlog of doc issues that I have to address.

This is already a big help. Knowing that event is pure Javascript and not a blazer added type. 
The reference source also helps. Tried looking for it, but didn't find it.

Thanks for the help.
