### ISSUE TITLE
quick grid search

### ISSUE THREAD

**Issue by hubsamirus** [dotnet/AspNetCore.Docs#31206]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-8.0#sample-app

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/quickgrid.md

### Document ID

564e71e3-82ed-ce23-4f9f-a00a58734a62

### Article author

@guardrex

**Comment by guardrex** [comment]
@hubsamirus ... Is this meant to be an issue about something regarding QuickGrid?
