### ISSUE TITLE
All samples not working without setting rendermode to InteractiveServer or InteractiveWebAssembly

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/AspNetCore.Docs#31202]
### Description

In each component that raises or received an EventHandler callback the interactive rendermode must be set to get the samples work:

@rendermode InteractiveServer (Server side Interactive)

or 

@rendermode InteractiveWebAssembly (Client side interactive)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

**Comment by guardrex** [comment]
It's in progress now and tracked by https://github.com/dotnet/AspNetCore.Docs/issues/31029. Should be resolved across the doc set by the end of the week 🤞🍀.
