### ISSUE TITLE
DOTNET_PRINT_TELEMETRY_MESSAGE was replaced by DOTNET_NOLOGO

### ISSUE THREAD

**Issue by Bykiev** [dotnet/AspNetCore.Docs#31223]
### Description

`DOTNET_PRINT_TELEMETRY_MESSAGE` environment variable was replaced by `DOTNET_NOLOGO`. Service configurations still setting this env variable to false. Example of the docs: https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu#create-the-service-file

related issues: 
https://github.com/dotnet/docs/issues/37830
https://github.com/dotnet/sdk/issues/9734 (seems it was removed in .net core 3)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu#create-the-service-file

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md

### Document ID

815fe034-c9fc-aee3-a8b5-f2e860b30302

### Article author

@Rick-Anderson

---
[Associated WorkItem - 191038](https://dev.azure.com/msft-skilling/Content/_workitems/edit/191038)

**Comment by Rick-Anderson** [comment]
Fixed in #31399
