### ISSUE TITLE
Please add comprehensive information to `WebApplication.CreateSlimBuilder()`

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#31222]
### Description

**Please add missing precise information to the document page on `WebApplication.CreateSlimBuilder()`:**

(1) What NuGet package is to be included in order to call `UseKestrelHttpsConfiguration()` et all.?

(2) Please add a concise table, comparing the features that are applied with `CreateSlimBuilder()` compared to `CreateBuilder()`, like this:

|Feature|`CreateSlimBuilder()`|`CreateBuilder()`|
|-|:-:|:-:|
|UseKestrelCore()|❌|✔️|
|UseKestrelHttpsConfiguration()|❌|✔️|
|UseQuic()|❌|✔️|
|…|❌|✔️|

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-8.0#the-createslimbuilder-method

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/native-aot.md

### Document ID

8839fa1e-7c10-4b22-d03d-669906a2b9ea

### Article author

@mitchdenny

---
[Associated WorkItem - 191039](https://dev.azure.com/msft-skilling/Content/_workitems/edit/191039)

**Comment by Rick-Anderson** [comment]
> (1) What NuGet package is to be included in order to call UseKestrelHttpsConfiguration() et all.?

None. From the Web API (native AOT) template code, just add the call.

```
var builder = WebApplication.CreateSlimBuilder(args);
builder.WebHost.UseKestrelHttpsConfiguration();
```

**Comment by Rick-Anderson** [comment]
@mitchdenny  please review and supply the table, I'll get the doc updated.
