### ISSUE TITLE
Auto rendering mode does not work properly

### ISSUE THREAD

**Issue by bxjg1987** [dotnet/AspNetCore.Docs#31229]
### Description

Environment:.net8 vs2022 Community Version 17.8.3

In the same statically rendered page, there are two components of the same type A \ B. A is set to server rendering mode and B is set to assembly rendering mode. When running, component B always runs in server mode.

If component A is removed, component B will work as expected at runtime.

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#child-components-with-different-render-modes

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-modes.md

### Document ID

7c9948a3-9886-8097-6014-492a4c21ea4e

### Article author

@guardrex

**Comment by guardrex** [comment]
If that's happening, it sounds like a bug. Open this for the product unit for investigation at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31229
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
