### ISSUE TITLE
Multiple Hosted apps with Blazor & net 8.0

### ISSUE THREAD

**Issue by philip-reed** [dotnet/AspNetCore.Docs#31230]
### Description

This document is missing guidance for hosting multiple apps with net 8 using the new Blazor Web App conventions.
Are multiple apps supported in net 8 Blazor Web Apps or do applications need to remain on the hosted WASM configuration?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/multiple-hosted-webassembly?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-8.0&pivots=route-subpath

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/multiple-hosted-webassembly.md

### Document ID

96763362-f8ba-0f11-0070-da8f9f533e21

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @philip-reed ... Support for it has been pushed back to .NET 9 (November, 2024). It's tracked for the docs by ...

https://github.com/dotnet/AspNetCore.Docs/issues/30392

... and there are two cross-linked PU issues there for work they need to do in the framework to support it.

AFAIK, apps that require this type of setup will need to remain on hosted WASM (7.0 era, but supported for 8.0 ... we just don't carry the doc for 8.0 any longer) until .NET 9 when they resolve the framework features needed to do it with a BWA. If you have questions about it that are relevant to those two PU issues, I think you can ask them over on their repo about it. If you have something different to ask about it than is covered by those issues, then open a new issue for them to address it.
