### ISSUE TITLE
Incorrect TOC for page 'Logging (not ASP.NET Core)' 

### ISSUE THREAD

**Issue by GerardSmit** [dotnet/AspNetCore.Docs#31237]
### Description

In https://github.com/dotnet/AspNetCore.Docs/pull/28726 the page "[Logging (not ASP.NET Core)](https://learn.microsoft.com/en-us/aspnet/core/migration/logging-nonaspnetcore?view=aspnetcore-8.0)" has been moved to "Advanced":

![image](https://github.com/dotnet/AspNetCore.Docs/assets/2109929/a5d764e3-115f-4cd2-8d52-e6f32c5531d7)

In the TOC:

https://github.com/dotnet/AspNetCore.Docs/blob/b7ae8c247e6db5918138541cd7287f1c033480fd/aspnetcore/toc.yml#L1777-L1779

I think this has been a mistake, because this page is about the migration from 2.1 to 2.2 or 3.0. Doesn't this belong under "Migration and Updates"?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/logging-nonaspnetcore?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/Logging-nonaspnetcore.md

### Document ID

dbcd23c0-3bca-e480-936b-2cf6f2d62c7e

### Article author

@Rick-Anderson

---
[Associated WorkItem - 192423](https://dev.azure.com/msft-skilling/Content/_workitems/edit/192423)

**Comment by tdykstra** [comment]
Yes, you're right, I'll move it.
