### ISSUE TITLE
Poor language in the introduction to event callbacks

### ISSUE THREAD

**Issue by markharwood101** [dotnet/AspNetCore.Docs#31234]
### Description

[Enter feedback here]
The following section could be written a little better:

EventCallback
A common scenario with nested components executes a parent component's method when a child component event occurs. An onclick event occurring in the child component is a common use case. To expose events across components, use an [EventCallback](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.eventcallback). A parent component can assign a callback method to a child component's [EventCallback](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.eventcallback).

"A common scenario with nested components executes a parent component's method when a child component event occurs."

This is a little nonsensical.

Perhaps something like the following would be better?

"A common scenario with nested components is that they may have a need to execute a method in a parent component when a child component event occurs. An onclick event occurring in the child component is a common use case."

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

**Comment by guardrex** [comment]
Sure ... great suggestion, @markharwood101. I'll make that change right now.

**Comment by guardrex** [comment]
I don't fully agree with your choice of words, but I will improve and simplify the language along the lines of what you suggest.
