### ISSUE TITLE
Integration Challenge: ASP.NET Core Identity Crashes with reCAPTCHA in Blazor Web App (rendermode InteractiveServer)

### ISSUE THREAD

**Issue by sinand** [dotnet/AspNetCore.Docs#31243]
## Issue Summary:

I am using .NET 8 and Blazor with the new "Blazor Web App" template. In the template, there are default pages for login, register, etc., provided by ASP.NET Core Identity.

By default, everything works fine. However, when I try to add reCAPTCHA to my login page by creating a component, the reCAPTCHA component works fine with `@rendermode InteractiveServer`. But, when I set the `rendermode` of `login.razor` to "InteractiveServer," ASP.NET Core Identity crashes because `HttpContext` is null.

## Steps to Reproduce:

1. Create a new Blazor Web App using .NET 8.
2. Add a reCAPTCHA component to the login page.
3. Set the `rendermode` of `login.razor` to "InteractiveServer."
4. Observe the crash in ASP.NET Core Identity due to a null `HttpContext`.

## Expected Behavior:

The reCAPTCHA component should work on the login page without affecting the functionality of ASP.NET Core Identity.

## Actual Behavior:

Setting the `rendermode` of `login.razor` to "InteractiveServer" causes ASP.NET Core Identity to crash due to a null `HttpContext`.

## Additional Information:

- ReCAPTCHA component is working fine with `@rendermode InteractiveServer`.
- ASP.NET Core Identity crashes when `rendermode` of `login.razor` is set to "InteractiveServer."

## Environment Details:

- .NET Version: 8.0
- Blazor Web App Template

**Comment by maojsm** [comment]
Estou com problema similar, quando adiciono o ReCaptcha na pagina ela passa a se estatica. Parece ignorar "@rendermode InteractiveServer". 
Não apresenta nenhum erro, apenas fica estatica e não renderiza conforme as iterações do usuário.
