### ISSUE TITLE
Error in the "@foreach(var items in Items)"

### ISSUE THREAD

**Issue by goCORA** [dotnet/AspNetCore.Docs#31248]
### Description

Following the example on this page (see Page URL below), the "Items" in the @foreach loop has the error:

foreach statement cannot operate on variables of type 'RenderFragment<TItem>' because 'RenderFragment<TItem>' does not contain a public instance or extension definition for 'GetEnumerator'

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/templated-components.md

### Document ID

ae663e33-6a08-0b24-aa19-3fc3c9edccfc

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the report @goCORA ... I'll check on this and get back to you shortly. I happen to be working on the snippet sample apps right now, and I'll place this code, repro the error here, and then take it from there. *Stand-by .............*

**Comment by goCORA** [comment]
I have corrected it. My mistake. Sorry for the false indication of an issue

**Comment by guardrex** [comment]
No worries. Closing now.
