### ISSUE TITLE
Guidance related to <base href="/" /> is missing

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/AspNetCore.Docs#31250]
### Description

This document needs to explicitly state that `<base href="/" />` needs to be modified if the app is running as an IIS sub-application 

There is mention of it [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio) **after** the user is referred to this documentation - and even this mention is not clear about IIS sub-applications.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/webassembly.md

### Document ID

250e7458-3c1d-0117-261d-c03ac136f16a

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @sam-wheat ... I'll set up that cross-link now.
