### ISSUE TITLE
Missing instruction to add Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by atwright147** [dotnet/AspNetCore.Docs#31260]
### Description

I think this is missing an instruction to run `dotnet add package Microsoft.EntityFrameworkCore.Tools` before scaffolding the TodoItemsController.cs

Following by wadepickett:
Also reported for VS on a dupe issue although I suspect VS Code is what was meant, but verify all three tab versions times .net 7-8 versions.
### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio-code

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

---
[Associated WorkItem - 196935](https://dev.azure.com/msft-skilling/Content/_workitems/edit/196935)

**Comment by Rick-Anderson** [comment]
@wadepickett  multiple reports, can you fix ASAP?

**Comment by wadepickett** [comment]
I can as soon as I get back from vacation tomorrow morning.  Thanks.

**Comment by wadepickett** [comment]
Fixed with#31344
