### ISSUE TITLE
Real project files for Blazor WebAssembly are different with the document description

### ISSUE THREAD

**Issue by shui106** [dotnet/AspNetCore.Docs#31262]
### Description

Real project files for Blazor WebAssembly are different with the document. 
VS version: vs2022 17.8

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md

### Document ID

6f27ff37-6b3a-57f5-353a-5cf5aabba7cf

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @shui106 ... Check your document version selector and make sure that it's set to the correct framework version.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/7201d755-2ebb-4951-86a1-9eccdf3c8e6c)
