### ISSUE TITLE
Proxy pass definition error 

### ISSUE THREAD

**Issue by Slip360** [dotnet/AspNetCore.Docs#31264]
### Description

[Escriba sus comentarios aquí]
When defining the "proxy_pass" property, you must place a forward slash "/" at the end of the port where the API is hosted. Following the example "http://127.0.0.1:5000" should be "http://127.0.0.1:5000/".

The configuration I have is:

location / {
                   # First attempt to deliver the request as a file, then
                   # as a directory, then returns a 404.
                   try_files $uri $uri/ /index.html?$args;
}

location /api_development/ {
                   proxy_pass http://127.0.0.1:5000/;
                   proxy_http_version 1.1;
                   proxy_set_header Update $http_upgrade;
                   proxy_set_header Connection kept active;
                   proxy_set_header Host $host;
                   proxy_cache_bypass $http_upgrade;
                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                   proxy_set_header X-Forwarded-Proto $schema;
}

### Page URL

https://learn.microsoft.com/es-es/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md

### Document ID

815fe034-c9fc-aee3-a8b5-f2e860b30302

### Article author

@Rick-Anderson

---
[Associated WorkItem - 194284](https://dev.azure.com/msft-skilling/Content/_workitems/edit/194284)

**Comment by Rick-Anderson** [comment]
@javiercn  please review
