### ISSUE TITLE
 Microsoft.VisualStudio.Web.BrowserLink is deprecated

### ISSUE THREAD

**Issue by lukos** [dotnet/AspNetCore.Docs#31278]
### Description

Since this nuget package is marked as deprecated, the instructions should be updated to either say that there is no way to do this any more or to use whatever package is not marked as deprecated.

Ideally, the people who choose these deprecated packages should always think to check and update documentation.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/using-browserlink.md

### Document ID

78a1947e-dea7-65b4-2376-05c7795e4bf9

### Article author

@ncarandini

**Comment by guardrex** [comment]
Looks like there are duplicate issues on this one ... even one of the two existing issues should probably be closed. 

cc: @tdykstra 

* https://github.com/dotnet/AspNetCore.Docs/issues/30826
* https://github.com/dotnet/AspNetCore.Docs/issues/30337
