### ISSUE TITLE
Documentation about persisting prerendered state is deceptive

### ISSUE THREAD

**Issue by viliml** [dotnet/AspNetCore.Docs#31275]
### Description

The component PrerenderedCounter2.razor as described in the guide does not work in the case of enhanced navigation (https://github.com/dotnet/aspnetcore/issues/51584), which is most cases since enhanced navigation is on by default.
Developers who try to follow the guide to implement persisting prerendered state will be confused why it doesn't work.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerender?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/prerender.md

### Document ID

ffdc8df3-55a8-b757-d4e6-38c104916002

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks, @viliml ... I'll address this as soon as I can, but it might be after the holiday 🎆 break.

In the meantime to surface this issue and the PU issue, I'll drop a quick note into the article right now.
