### ISSUE TITLE
Add troubleshoot step for <DebuggerSupport> when using custom debug profiles

### ISSUE THREAD

**Issue by Bradtus** [dotnet/AspNetCore.Docs#31281]
### Description

Hello, 
After searching for a few days why my custom debug profiles for blazor wasm did not work after upgrading visual studio i finally found the 
`<DebuggerSupport Condition="'$(Configuration)' == 'Debug' or '$(Configuration)' == 'DebugCustom'">true</DebuggerSupport>`
option. This was not needed before upgrading.
I think this would be a great addition to the troubleshooting steps. Or maybe mentioned elsewhere in this documentation.
Kind regards,

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md

### Document ID

4d06e565-282d-6387-aa90-cb2c2986d35a

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Bradtus ... AFAIK, that's enabled by default for Debug builds. If that's correct, then something else is going on. Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

You can just cut and paste what you wrote here :point_up: as the description. I'll add a remark after you open the issue.

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31281
```

... to the bottom of your opening comment to give me a ping. We'll close here for now, but they may ask for coverage. For example, we had a remark for enabling `DebuggerSupport` for Release-built apps for local testing, but that coverage was dropped when we dropped all of the coverage on hosted WebAssembly solutions. I would like to ask Javier about adding something back.

**Comment by guardrex** [comment]
@Bradtus ... I reached this for work, and I think a section will be better than a *Troubleshoot* entry.

Can you do me a favor tho? I'd like to cross-link to the PU issue, but that issue title isn't good link text.

Can you go to your PU issue at ...

https://github.com/dotnet/runtime/issues/96239

... and see if you can edit the title from ...


> Blazor WASM Custom debug configs need <DebuggerSupport Condition="''$(Configuration)' == 'DebugCustom'">true</DebuggerSupport>

... ***TO*** ...

> Blazor WebAssembly custom debugger configuration
