### ISSUE TITLE
Wrong URL for dotnet.d.ts

### ISSUE THREAD

**Issue by myieye** [dotnet/AspNetCore.Docs#31291]
### Description

dotnet.d.ts was [recently moved](https://github.com/dotnet/runtime/pull/95940/files#diff-211a657f164897b86f194ea4b0bce9065f7765f4180a79639ee29c711c13941c) to: https://github.com/dotnet/runtime/blob/main/src/mono/browser/runtime/dotnet.d.ts
The link should be updated accordingly.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/12587509/1e6f25a1-5418-412a-9553-e3d9344a4064)

(I believe there are more links that need to updated to the new location, but I can't remember where I found them)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/dotnet-interop.md

### Document ID

efff6954-a035-d1da-5975-af04ff7c05ed

### Article author

@pavelsavara

**Comment by guardrex** [comment]
Thanks @myieye ... I'll update that one. If you find more, please feel free to open new issues for them as needed.

**Comment by pavelsavara** [comment]
cc @radical
