### ISSUE TITLE
Cross-link bUnit Oslo '22

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#31299]
### Description

@egil ... Happy holidays! ❄️⛄ I'd like to cross-link your excellent Oslo '21 talk ...

**Best practices unit testing Blazor components with bUnit - Egil Hansen - NDC Oslo 2021**
https://www.youtube.com/watch?v=Co7QetPYiO4

... in the *Additional Resources* section of the Blazor *Test* article. Is the content of the talk still valid?

We normally don't like to cross-link presentation content due to how fast it goes stale, but I can check back with you each year to see when it's no longer a good resource to cross-link.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/test?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/test.md

### Document ID

2890676f-3c63-5ab7-dd31-6b223212da30

### Article author

@guardrex

**Comment by egil** [comment]
Thanks, appreciate the kind words. Not a lot of the fundamentals have changed. Think I mention a feature of bUnit that's in preview that's no longer that, but other than that it's still current.

Another presentation that's newer and have overlapping content is https://youtu.be/L_n-12FglLI?si=o-tBHId3HPyjzMas, which you could also include or use instead.

**Comment by guardrex** [comment]
Very good. I'll use the newer one.

**Comment by egil** [comment]
Do note that the second also discusses component design and not just testing.

Either should be fine though 😊

**Comment by guardrex** [comment]
I watched it. It's great. I think devs should consume the design portion. I'm glad you retained the `Counter` component testing for a basic bUnit explanation in the middle before reaching the data table testing at the end. It all works, and I think devs will enjoy learning from it. It's live now ... 

https://learn.microsoft.com/aspnet/core/blazor/test#additional-resources

This was an item that was lingering on my ToDo list, which I've just about knocked out this Xmas 🎄 ...

* Trashed dozens of old projects.
* Cleaned up my desktop.
* Cleared my Inbox.
* Dropped dozens of old bookmarks.
* Did the laundry.
* Lifted 💪 my weights.
* Ate a chicken dinner 🍗.

I've been very productive today! .... and I guess this means I can ***STOP*** working now 🙈. *I'm supposed to be on vacation!* 😆

**Comment by egil** [comment]
Well done sir. Yes, go do vacationing 😀
