### ISSUE TITLE
Wrong names for legacy methods

### ISSUE THREAD

**Issue by shui106** [dotnet/AspNetCore.Docs#31309]
### Description

_For Blazor Server, Blazor WebAssembly, and Blazor Hybrid apps:_

_**beforeWebStart** is used for tasks such as customizing the loading process, logging level, and other options._
_**afterWebStarted** is used for tasks such as registering Blazor event listeners and custom event types._

I think "beforeWebStart " and  "afterWebStarted" should be  "beforeStart" and "afterStarted".

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-8.0.md

### Document ID

f30dbb9e-d64d-a925-01ca-00d9d035e6c1

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Thanks @shui106 ... *Yes!* That's a typo. I'll fix it right now.
