### ISSUE TITLE
environment file should be mentioned in the docs

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/AspNetCore.Docs#31306]
### Description

Currently, VS now supports environment files, think it should be mentioned in the documentation

see: https://devblogs.microsoft.com/visualstudio/safely-use-secrets-in-http-requests-in-visual-studio-2022/

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thaks for the suggestion, but we already have issue #30432 for this, so I'm closing it as a duplicate.
