### ISSUE TITLE
Missing Microsoft.EntityFrameworkCore.Tools when creating controller

### ISSUE THREAD

**Issue by andreasottosson** [dotnet/AspNetCore.Docs#31312]
### Description

Instructions are missing

`dotnet add package Microsoft.EntityFrameworkCore.Tools`

in section, "Scaffold a controller"

at least for me on Fedora 39.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&WT.mc_id=dotnet-35129-website&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Thanks very much @andreasottosson, for bringing up this issue.  We will get it fixed.  Sorry for the late reply, I was out on vacation for two weeks, just back this morning.

Since this is a duplicate of #31260 I will close this one as a dupe and use the other one for tracking to completion.
