### ISSUE TITLE
Nothing works in Blazor Web App .NET 8 on the Server side with InteractiveServer render mode 

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/AspNetCore.Docs#31317]
### Description

I tried the CircuitHandler to catch connection drops on the server side and I tried all your javascript samples as suggested to catch connection drop issues. 

Nothing works in a Blazor Web App .NET in the server part. My root component "/" is set to 

`@rendermode @(new InteractiveServerRenderMode(prerender:false))`

Even the `onConnectionUp` is **never** invoked when I [add ](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#modify-the-server-side-reconnection-handler)the to my `App.razor`

```
<script src="{BLAZOR SCRIPT}" autostart="false"></script>
<script>
  Blazor.start({
    circuit: {
      reconnectionHandler: {
        onConnectionDown: (options, error) => console.error(error),
        onConnectionUp: () => console.log("Up, up, and away!")
      }
    }
  });
</script>
```
The [Circuit Handler's](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#server-side-circuit-handler) OnConnection* methods are never invoked . Only the .ctor.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0&preserve-view=true

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md

### Document ID

d17e4c28-ea82-0dd8-295d-19f6ada147ea

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @ericbrunner ... Please open this for the product unit with a minimal repro project that shows the behavior at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31317
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.

**Comment by guardrex** [comment]
... and btw @ericbrunner ... you don't show it, but make sure that you replace the placeholder with the script path ...

```
{BLAZOR SCRIPT}
```

... should be ...

```
_framework/blazor.web.js
```

... for a BWA app.

**Comment by guardrex** [comment]
... when you say "nothing works" ... nothing will work if the Blazor script isn't correctly referenced there.

**Comment by guardrex** [comment]
Actually, I think I'll use this issue to highlight that point in the article. I'll make those lines ***BOLD*** so that they stand out well from the text.
