### ISSUE TITLE
BUG: When running directly - not as a Windows service, the code after await is never reached.

### ISSUE THREAD

**Issue by Alemvik** [dotnet/AspNetCore.Docs#31320]
[EDIT by guardrex to code fence the code and reset the article author. BTW, @Alemvik ... For future issues, leave the GitHub user entered as the author so that they get an automatic ping when the issue opens. It helps us triage the issues faster.

### Description

// Bad
```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
  while (!stoppingToken.IsCancellationRequested) {
    if (_logger.IsEnabled(LogLevel.Information))
      _logger.LogInformation("Worker running at: {time:yyyy-MM-dd HH:mm:ss.mmm}", DateTimeOffset.Now);
    await Task.Delay(TimeSpan.FromSeconds(5), stoppingToken);
  }  ; // Code NOT reached when user do ctrl-c in the console windows
}
```

// Good

```csharp
protected override async Task ExecuteAsync(CancellationToken stoppingToken)
{
  while (!stoppingToken.WaitHandle.WaitOne(TimeSpan.FromSeconds(5))) { // Will this yield ?
    if (stoppingToken.IsCancellationRequested) break;
    if (_logger.IsEnabled(LogLevel.Information))
      _logger.LogInformation("Worker running at: {time:yyyy-MM-dd HH:mm:ss.mmm}", DateTimeOffset.Now);
  }
  ; // Code reached when user do ctrl-c in the console windows
}
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/windows-service.md

### Document ID

4b60d24e-ef05-15e5-10b4-483094081bf3

### Article author

@tdykstra

**Comment by Alemvik** [comment]
I need the ctrl-c to act as a STOP service command.

**Comment by tdykstra** [comment]
>When running directly - not as a Windows service, the code after await is never reached.

This article is for a Windows service; modifying the code for use when running an app directly is outside the scope of the article.
