### ISSUE TITLE
Different desctiption about model validation statement in Native Mobile Backend from one in .NET Core MVC doc

### ISSUE THREAD

**Issue by JLWJL** [dotnet/AspNetCore.Docs#31350]
### Description

Native Mobile Backend docs mentions "Checking ModelState.IsValid performs [model validation](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0), and should be done in every API method that accepts user input. However, in [model validation](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0), it mentions "[Web API controllers don't have to check ModelState.IsValid if they have the [ApiController] attribute...](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#:~:text=Web%20API%20controllers%20don%27t%20have%20to%20check%20ModelState.IsValid%20if%20they%20have%20the%20%5BApiController%5D%20attribute)"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-6.0#creating-the-aspnet-core-project

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mobile/native-mobile-backend.md

### Document ID

d06996cc-14aa-96e2-fd62-9d5bbc059107

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Web API controllers aren't used with user input, that's what Razor Pages and MVC controllers with views are for. If you need to check user input, use a MVC controller with views.
