### ISSUE TITLE
Error for Id property in Starship3 example

### ISSUE THREAD

**Issue by sikora507** [dotnet/AspNetCore.Docs#31360]
### Description

The ID in InputText does not exist in Starship class.

The InputText component:
`<InputText @bind-Value="Model!.Id" />`

The Starship class property:
```
    [Required]
    [StringLength(16, ErrorMessage = "Identifier too long (16 character limit).")]
    public string? Identifier { get; set; }
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/input-components?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms/input-components.md

### Document ID

52ee411b-69fe-c0bc-5305-846d9384ebbd

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the report, @sikora507 ... I'll take a look here in a few minutes and see what's what.

**Comment by guardrex** [comment]
I think since I was using "Id" everywhere else that it would simplest and quickest 🏃 to stick with "Id" ... in which case the fix will be over on the `dotnet/blazor-samples` repo.

**Comment by guardrex** [comment]
I'm fixing it now ... it will only take a few minutes to update everything.
