### ISSUE TITLE
Sample code can't solve CORS exception

### ISSUE THREAD

**Issue by KameLong** [dotnet/AspNetCore.Docs#31373]
### Description

Section:"Cross-Origin Resource Sharing"

The sample code lacks the description of header.

I succeeded in avoiding CORS errors by this code
```
builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
                      policy =>
                      {
                          policy.WithOrigins("http://example.com");
                          policy.WithMethods("GET", "POST");
                          policy.AllowAnyHeader();//append this line
                          policy.AllowCredentials();
                      });
});
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/security.md

### Document ID

58e87eb0-240b-ab00-c5f4-32a0ab2e0028

### Article author

@bradygaster

---
[Associated WorkItem - 203532](https://dev.azure.com/msft-skilling/Content/_workitems/edit/203532)

**Comment by wadepickett** [comment]
@BrennanConroy, it is true that for the CORS policy example, that that a CORS exception would be generated, such as:  _..blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response._   And it is true that can error can be avoided by setting `policy.AllowAnyHeader()` 

However, isn't it a risk to just allow any header?   Should I add `policy.AllowAnyHeader()`  but warn it is recommended that the header be specified to make it more secure?  I'm not sure what should be recommended here. 

Also, is allowing any header (or a specific one) only required after a particular version of .NET?

Thanks for any insights!

**Comment by BrennanConroy** [comment]
> it is true that for the CORS policy example, that that a CORS exception would be generated, such as: _..blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response._ And it is true that can error can be avoided by setting `policy.AllowAnyHeader()`

Sounds about right.

> However, isn't it a risk to just allow any header?

Probably. I don't think this option needs to be used unless you have custom client logic.

> I'm not sure what should be recommended here.

We link to the CORS middleware docs earlier in the page. If we do anything here it might be to push the user to that page more explicitly if they need to customize their CORs settings.

> Also, is allowing any header (or a specific one) only required after a particular version of .NET?

I'd be surprised if a default app needed to allow all headers. We need a repro app.
