### ISSUE TITLE
Custom Elements Example

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/AspNetCore.Docs#31372]
### Description

There isn't necessarily anything this wrong in the documentation. I just wanted to make an issue and see if an example for custom elements could be added. Because I have looked for a few hours trying to find an example application and I haven't been able to find one.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/js-spa-frameworks?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/js-spa-frameworks.md

### Document ID

444b03b4-f910-656a-642c-6c9064d6ce28

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @josephaw1022 ... It covers the default `Counter` component without showing it. I'll add the component to the coverage.
