### ISSUE TITLE
Azure Sentinel support for ASP.Net Core Identity

### ISSUE THREAD

**Issue by MrImpossibru** [dotnet/AspNetCore.Docs#31385]
### Description

Hello,

I haven't found it anywhere so I'm asking here: is there a native support of Azure Sentinel service to monitor and make some actions on security issues? If not, are there any plans to implement such support?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity.md

### Document ID

0e0d870e-e49a-e16c-c259-68d58e701b8f

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
No
