### ISSUE TITLE
When made scaffolding in Identity in .net 6 , when override any file the update not work when run the app 

### ISSUE THREAD

**Issue by Hany-kelany** [dotnet/AspNetCore.Docs#31395]
That when add 

_Hello_

 in Login.cshtml file 

this word not appear in Login page when run the app

![Error](https://github.com/dotnet/AspNetCore.Docs/assets/84659136/63a1b620-aa89-40a0-8552-1cb9963c5fb7)

**and** the output is and Hello not appeared in page and .net 7 the same problem 

![output](https://github.com/dotnet/AspNetCore.Docs/assets/84659136/f2168a4f-49ca-4499-8465-02325258a4dc)

but when i use .net5 it work.

**Comment by guardrex** [comment]
Hello @Hany-kelany ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-8.0&tabs=visual-studio
