### ISSUE TITLE
Blazor Server app -- removed for .NET 8 ?

### ISSUE THREAD

**Issue by KristinBethea** [dotnet/AspNetCore.Docs#31397]
### Description

[Enter feedback here]
After wayyyy too much research, it seems that the Blazor Server app itself is no longer part of the Blazor install. One must install just the Blazor app itself and code accordingly. Therefore, shouldn't this page be updated to reflect those changes?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-8.0#location-of-head-and-body-content

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md

### Document ID

6f27ff37-6b3a-57f5-353a-5cf5aabba7cf

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @KristinBethea ... Blazor Server is still supported in 8.0, and this doc has already received updates for 8.0. 

You mentioned researching a bit on the changes for 8.0. There's a Whats New doc each release. The latest is at ...

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-8.0?view=aspnetcore-8.0#blazor

It explains what's going on with the project templates for this release.
