### ISSUE TITLE
The content inside <NotAuthorized> tag in Routes component won't be displayed 

### ISSUE THREAD

**Issue by FengRuikai** [dotnet/AspNetCore.Docs#31402]
### Description

The content inside <NotAuthorized> tag won't be displayed  if we don't configure Interactiveserver render mode for entire app,but its was not mentioned in the document

A related issue:https://stackoverflow.com/questions/77748801/how-to-do-windows-authentication-i-cant-get-notauthorized-to-show/77750838?noredirect=1#comment137134432_77750838

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/index.md

### Document ID

8da62490-e36f-8f38-8f06-d5d6bceaafde

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @FengRuikai ... I see what you mean ... and from looking at the PU issues. I'm looking at Javier's explanations at ...

https://github.com/dotnet/aspnetcore/issues/52176#issuecomment-1825677291

... in particular his remark ...

> During SSR we won't show NotAuthorized, because your component doesn't even get to render.

... which seems like the critical bit pertaining to this issue. However, I might need to provide more coverage on the behaviors based on his full set of remarks.

**Comment by guardrex** [comment]
I've studied several PU issues. I'm not sure what to do yet in the docs. Are we merely going to state the reason, or are we also going to prescribe approaches to take to address the behaviors? If we're stating approaches, what approaches? I'll need to work on this further tomorrow.

I think what I'll need to do is play with some local scenarios to study BWA behaviors so I can see what devs are reporting firsthand ... ***and*** ... try a few things that are discussed to see their effect on the app. I can probably address the approaches aspect better if I work directly with use cases. Trying to understand it from dev descriptions and PU responses is only partially working for me right now. I'll pick back up tomorrow with this. I just hit a 🦖🧠🔥 for the day on this subject 😆.

**Comment by guardrex** [comment]
**UPDATE** ... It's taken ***forever*** 😩 to get back to this. I've been 🏃‍♂️ on higher priority 8.0 issues over the last several weeks. This is one of the last issues to address. I'm going to work on it ***right now***.
