### ISSUE TITLE
ASP.NET Core 8.0

### ISSUE THREAD

**Issue by Dacoband** [dotnet/AspNetCore.Docs#31406]
### Description

[Enter feedback here]
Good Tutorial

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

**Comment by wadepickett** [comment]
@Dacoband, wonderful to hear!  Thanks!!!
