### ISSUE TITLE
Request new metadata subservices and update docfx config

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#31413]
There's a link in ...

https://review.learn.microsoft.com/en-us/help/platform/validation-ref/ms-service-subservice-invalid?branch=main

... to request the subservices for our `ms.service` of `aspnet-core`. The subservices that we need are ...

* clientside
* data
* getstarted
* hostdeploy
* razorpages
* releasenotes
* signalr
* test
* webapi
* whatsnew
* blazorhybrid

... but now is a good time to change any if desired and add any new ones wanted.

***Note tho*** that it might have been decided that these shouldn't be subservices, and the correct ones were approved. If so, then someone just needs to check their approved pairings (`ms.service allowlist` link in their article) to make sure we have them all. No further action needs to be taken to put any back that I just 🔪 out.

After approval, one of us can replace the `ms.subservice` config in `docfx.json` with the following, including any updates for any that will change.

This is the original config, both working and non-working that were cut out on  #31411, so it's a cut-'n-paste for the file ...

```json
"**/client-side/**/**.md": "clientside",
"**/data/**/**.md": "data",
"**/fundamentals/**/**.md": "fundamentals",
"**/getting-started/**/**.md": "getstarted",
"**/grpc/**/**.md": "grpc",
"**/host-and-deploy/**/**.md": "hostdeploy",
"**/migration/**/**.md": "migration",
"**/mobile/**/**.md": "mobile",
"**/mvc/**/**.md": "mvc",
"**/performance/**/**.md": "performance",
"**/razor-pages/**/**.md": "razorpages",
"**/release-notes/**/**.md": "releasenotes",
"**/security/**/**.md": "security",
"**/signalr/**/**.md": "signalr",
"**/test/**/**.md": "test",
"**/tutorials/**/**.md": "tutorials",
"**/web-api/**/**.md": "webapi",
"whats-new/**/**.md": "whatsnew",
"**/blazor/**/**.md": "blazor",
"**/blazor/hybrid/**/**.md": "blazorhybrid"
```

**Comment by tdykstra** [comment]
The new values are already set up -- see https://review.learn.microsoft.com/en-us/help/platform/metadata-fields/ms-prod?branch=main
Search for aspnetcore and you'll find them all listed, e.g.:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/1569635/800f1437-6f7a-4787-b7a6-5aecb4a82d7d)

**Comment by guardrex** [comment]
I see. It looks like a number of them were slightly changed, usually with a dash added ... `data` to `data-access` ... `clientside` to `client-side` ... `blazorhybrid` to `blazor-hybrid`.

I'll make another pass on this in a few minutes to see if I can rectify the ones that I cut out.

**Comment by guardrex** [comment]
Sorry ... I thought that was another restricted page. I should be able to resolve all of them now.
