### ISSUE TITLE
Must use the @namespace for components in MVC app

### ISSUE THREAD

**Issue by nitrospaz** [dotnet/AspNetCore.Docs#31429]
### Description

[Enter feedback here]
If you are adding razor or Blazor components to a MVC app the components must use the @namespace reference in the @code section. Otherwise, the program can't find the component. 

This is not referenced or explained in any of the examples.

This is a screenshot of how the component code should look with the @namespace reference.
<img width="484" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/36904927/5638d5ff-c548-44c3-9543-e60c28420c52">

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#component-namespaces

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/integration.md

### Document ID

d7e39bbc-cd54-92aa-4997-f9dd39dd6ef3

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @nitrospaz ... It's dependent upon the app ... on where the dev places the components. Component namespaces are determined by their location in the app, which we cover at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#component-name-class-name-and-namespace

If the component is placed in a `Components` folder, you shouldn't need to state its namespace that way. If you're seeing that happen tho, we'd need to look into it and possibly have a product unit bug investigation.

There's also a section at the end that touches on adding an `@using` statement to view imports to help views find them.

I don't think I need to add more content at this time, but I'll keep an 👂 open for more trouble.

... and BTW ... if you do use the `@namespace` directive to assign a namespace, we recommend that they go at the top of the file.

**Comment by nitrospaz** [comment]
Thanks for the prompt reply. I moved the @namespace to the top. I have a Components folder in my project root directory and the component is in that folder. If I don't put anything at the top of the component I get errors from the other references to the namespace. I tried putting the @using statement at the top of the component and it gives me the CS0234 "namespace does not exist...". If I put the @namespace at the top the errors go away and it will build. 

<img width="842" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/36904927/efe0f76a-c1ae-4678-b5a1-0fa925d3351d">

**Comment by guardrex** [comment]
The `@using` doesn't go at the top of the component file. It goes in the view where the component is used or in the view imports file for all views to find them.

**Comment by guardrex** [comment]
The namespace rules and conventions are described here ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#component-name-class-name-and-namespace

**Comment by nitrospaz** [comment]
> The `@using` doesn't go at the top of the component file. It goes in the view where the component is used or in the view imports file for all views to find them.

Yes I already had those @using statements in the views and it was giving me the "namespace does not exist" errors untill I put the @namespace reference in the component.  
<img width="855" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/36904927/6b230bc7-16bd-46fb-9fb6-c6fb8c4da351">

**Comment by nitrospaz** [comment]
Ok so I made a fresh MVC app, and the directions for adding the components without having to use the namespace work with that. You can find the example here: https://github.com/nitrospaz/MvcExample I have a branch where I added the razor component stuff.

I did have some issues with adding the 
 `app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();`
to the Program.cs file. 

It couldn't find the App reference because the base MVC setup does not come with an App.razor file.
In fact, I looked at a fresh razor pages example and it doesn't come with an App.razor file either.
I found an App.razor file example in another example somewhere in some docs, I don't know if its correct, but it works. 
If you have any feed back on what I did I would love to hear it. Good or bad.

I wonder if the original @namespace problem was because the application I was working on had the old-style program structure with a Program.cs and Startup.cs file. I noticed that the fresh example uses the single Program.cs structure now. What do you think?

**Comment by guardrex** [comment]
Adding the `App` component is in the instructions.

I think what's missing just a namespace for it. I'll add that now.

**Comment by guardrex** [comment]
I pinged you on the PR. This was a bit more complicated (***and weirder***) than I thought it was going to be.

*Stand-by until next week for Mackinnon's response.*

In the meantime, add a no-op `App` component to your app ...

`Components/App.razor`:

```razor
@* No-op App Component *@
```

... and a using at the top of the `Program` file to surface the `App` component for the `MapRazorComponents` call.

After that, you should be able to embed components into views as the rest of that section describes.

We'll find out next week if a no-op `App` component is the right thing to do. It's the only way I could get ***interactive*** components to work here (e.g., the `EmbeddedCounter` component placed into the `Index` view ...

`Views/Home/Index.cshtml`:

```cshtml
@using BlazorSample.Components
@{
       ViewData["Title"] = "Home Page";
}

<component type="typeof(EmbeddedCounter)" render-mode="ServerPrerendered" />
```
