### ISSUE TITLE
Swashbuckle is not supported on .NET 8

### ISSUE THREAD

**Issue by Nisden** [dotnet/AspNetCore.Docs#31437]
### Description

For .NET 8 Swashbuckle is mentioned as an option of working with OpenAPI specs.
However, Swashbuckle have not been updated for the past year, and is incompatible with .NET 8

See issues like https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2707 & https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2725

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md

### Document ID

59222460-a971-e76e-4fe9-23d4d7d768ee

### Article author

@zuckerthoben

---
[Associated WorkItem - 199402](https://dev.azure.com/msft-skilling/Content/_workitems/edit/199402)

**Comment by Nisden** [comment]
Hi @Rick-Anderson 

You missed the in-page reference on the "Overview" page.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1127727/4aac4661-123b-4619-9d87-1b58a1be19e8)

**Comment by vernou** [comment]
The template `dotnet new webapi` use **Swashbuckle** :
[WebApi-CSharp.csproj.in](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/WebApi-CSharp.csproj.in)

Do you consider to replace by **NSwag**?

**Comment by konrad-jamrozik** [comment]
Another reference to Swashbuckle from ASP.NET Core 8 docs:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-8.0#add-openapi-annotations-to-endpoints-via-withopenapi

> Calling [WithOpenApi](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.openapiendpointconventionbuilderextensions.withopenapi) on the endpoint adds to the endpoint's metadata. This metadata can be:
> 
> Consumed in third-party packages like [Swashbuckle.AspNetCore](https://www.nuget.org/packages/Swashbuckle.AspNetCore/).

**Comment by gabrielsimas** [comment]
No problem! We're do it for SwashBukle... Lol
