### ISSUE TITLE
Missing Deployment Information for DOTNET 8 SSR Sites

### ISSUE THREAD

**Issue by wonsil** [dotnet/AspNetCore.Docs#31448]
### Description

The introduction of prerendered Server-Side Rendered sites seems like a natural for Azure Static Sites, but a dotnet publish does not create a folder of HTML like HUGO, Svelte, etc. Maybe the functionality doesn't exist yet, but if it does, it would be helpful to have it documented here.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md

### Document ID

c82cf121-831d-75dd-a796-c735aad3b3e9

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @wonsil ... That's not what Blazor is designed to accomplish as a framework. Blazor is focused on allowing developers to use .NET/C# for browser UI and user interaction in the browser. An Azure Static Site can serve Blazor WebAssembly apps, but the Blazor framework isn't focused on creating a static HTML website to be hosted by a static website host. For more information on Blazor's design goals, see the description of Blazor in the introduction at https://learn.microsoft.com/aspnet/core/blazor/.

**Comment by wonsil** [comment]
Then what purpose does the new Blazor 8 Static Site rendering mode supposed to serve?

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

**Comment by guardrex** [comment]
Let me see ... I may have forgotten about a new 8.0 feature.

**Comment by wonsil** [comment]
Also here: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0

**Comment by guardrex** [comment]
I see how you're interpreting the language now. The content rendered by static server rendering is static HTML markup in individual webpages for clients (and to be distinguished from "interactive" where the client interacts with the server-based app over a SignalR connection between the server and client) ... that's true ... ***but*** Blazor doesn't create a website of static HTML pages. Blazor Web Apps are still server-side apps that run on the server and generate content on-the-fly. It's not a technology that publishes a static HTML website.

The basic problem with describing Blazor with "static" rendering is that terms are overloaded and mean different things in different contexts. Here, "static server-side rendering (static SSR)" only means how Blazor processes Razor markup and C# into individual pages. It doesn't mean what one would think coming from other technologies and tooling, where static websites are produced and published.

None of the article content that we added makes remarks about static SSR producing whole websites of static pages, and I'm not sure that we'd preemptively try to make statements in that regard ... *yet anyway*. I think we'd wait a little longer to see how many new-to-Blazor devs report confusion about what static SSR means.

Currently, the general concepts are covered earlier in the doc set at ...

* https://learn.microsoft.com/aspnet/core/blazor/#build-a-full-stack-web-app-with-blazor
* https://learn.microsoft.com/aspnet/core/blazor/hosting-models#blazor-server

What's a little closer to producing something that doesn't require a server ... i.e., a "static" type of published app ... would be a Blazor WebAssembly app. That's described at ...

* https://learn.microsoft.com/aspnet/core/blazor/hosting-models#blazor-webassembly
* https://learn.microsoft.com/aspnet/core/blazor/hosting-models#static-site-hosting

**Comment by guardrex** [comment]
Keep in mind that your use of "static site" was something that you interpreted. That's not a phrase that any Blazor doc uses ... 🤔 AFAIK 😄. Indeed, one can't add the word "site" like that to "static" in that context of SSR (server-side rendering). That's not a Blazor design goal or feature. If you want to ask the product unit to create a ***new feature*** for Blazor that would truly produce a static HTML website, that might be a reasonable ask. Search their issues first tho (open and closed) because someone may have already asked them about it ...

https://github.com/dotnet/aspnetcore/issues

**Comment by wonsil** [comment]
Ah, gotcha. It is confusing. I mean, even classic ASP.NET created static HTML on the server. 🤔 

I keep seeing statements like, "Blazor is a full-stack Web UI," and I made the leap that it would also provide functionality to create static sites. It looks like for the meantime, those who want that capability will have to use something other than Blazor like Svelte, Gatsby, Hugo, etc. There is a market for static sites that can be deployed on Azure Static Sties, GitHub profiles, or even blob storage, so I think I will submit the new feature. It would be nice to teach new web developers the beauty of components early and let them add interactivity as they grow.

Separately, I see that someone else likes the idea of using Blazor to create static sites: https://github.com/tesar-tech/BlazorStatic

Thanks for your help!

**Comment by guardrex** [comment]
Sounds good ... just keep in mind as you open an issue for them that standalone Blazor WebAssembly can be hosted the same way as a static HTML website. Azure Static Sites and GH Pages will host standalone Blazor WebAssembly apps, and I think Azure Blob Storage can host them, too. We don't cover that scenario, but I've heard of devs doing it. Such an app isn't a Blazor Web App, and "server rendering" concepts, such as static SSR and prerendering, don't apply in those static hosting scenarios.

**Comment by wonsil** [comment]
Agreed that WASM can be served this way but that's a lot of extra bandwidth. It is also not SEO friendly as only the meta data, title, etc. are indexed but not the content.
