### ISSUE TITLE
Missing documentation for npm dependencies, bundling, external dependencies in general

### ISSUE THREAD

**Issue by JeroMiya** [dotnet/AspNetCore.Docs#31442]
### Description

The JS interop documentation seems to be missing any references or guidance on incorporating external frontend npm dependencies. And many community articles on this topic are either out of date, incomplete, or don't mention modern options. Webpack works as usual, but you must bundle all of your app's JS code into one file, unlike the JS module isolation examples in this page which use component-specific ES modules. It's an option, but what I'd love to see is an example and maybe best practices for more modern tooling that keeps each ES module separate. Like the now-defunct Snowpack or the new Vite tooling. Preferably including examples both with bundling and without. Even a Webpack example would be nice as a fallback. Thanks!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#blazor-javascript-isolation-and-object-references

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

### Document ID

9e197a8b-2616-8363-0a15-38cac802e82e

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @JeroMiya ... The product unit has decided at this time not to pursue writing documentation on that subject, mostly because they have no specific recommendations in this area. It's up to devs to research and determine what tooling will work best for them.
