### ISSUE TITLE
How to specify HttpClient timeout for requests?

### ISSUE THREAD

**Issue by rolfik-mycronic** [dotnet/AspNetCore.Docs#31456]
### Description

I need to control request timeout. Is there a way?
Thank You

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0#send-an-http-request

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

---
[Associated WorkItem - 200668](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200668)

**Comment by tdykstra** [comment]
@sayedihashimi A question about .http file features.

**Comment by tdykstra** [comment]
Thanks!
