### ISSUE TITLE
NSwag.AspNetCore 14 does not contain definition for UseSwaggerUi3

### ISSUE THREAD

**Issue by Magnus-K-work** [dotnet/AspNetCore.Docs#31455]
### Description

As of version 14 of NSwag.AspNetCore, the configuration method UseSwaggerUi3 has been renamed UseSwaggerUi. Please update the linked documentation.

Reference for this changed method name:
https://github.com/RicoSuter/NSwag/issues/4524

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag.md

### Document ID

25f7fb5b-92b0-a45b-57ab-fdceab571884

### Article author

@zuckerthoben

---
[Associated WorkItem - 200667](https://dev.azure.com/msft-skilling/Content/_workitems/edit/200667)

**Comment by timdeschryver** [comment]
I can pick this one up if you'd like.

I just need some guidance how a change like this needs to be documented in the docs.
Do we just replace the implementation, or do we add a comment to document both versions?
For example:

```cs
// Using NSWag V14
app.UseSwaggerUi();  

// Using NSwag V13
app.UseSwaggerUi3();
```

For context:

- NSwag v13 has by far the most downloads (according to [NuGet](https://www.nuget.org/packages/NSwag.AspNetCore))
- NSwag v13 has .NET 5 - .NET 7 support
- NSwag v14 has .NET 6 - .NET 8 support

**Comment by Magnus-K-work** [comment]
> Do we just replace the implementation, or do we add a comment to document both versions? For example:
> 
> ```cs
> // Using NSWag V14
> app.UseSwaggerUi();  
> 
> // Using NSwag V13
> app.UseSwaggerUi3();
> ```
> 
> For context:
> 
> * NSwag v13 has by far the most downloads (according to [NuGet](https://www.nuget.org/packages/NSwag.AspNetCore))
> * NSwag v13 has .NET 5 - .NET 7 support
> * NSwag v14 has .NET 6 - .NET 8 support

^ This would have helped me. Great suggestion!

**Comment by Rick-Anderson** [comment]
@timdeschryver  
> Do we just replace the implementation, or do we add a comment to document both versions?
Just replace to the new UI.
Thanks for taking this.
