### ISSUE TITLE
The default value of PreferHostingUrls is incorrect

### ISSUE THREAD

**Issue by QianMoXi** [dotnet/AspNetCore.Docs#31493]
### Description

If I'm not mistaken, this value is only set to true when using IISIntegration, and when using Kestrel or HttpSys, it defaults to false.

Only the following code sets PreferHostingUrls to true:
https://github.com/dotnet/aspnetcore/blob/f533c51cd99901e8f3ed5004bd9ce7d824ea8e9a/src/Servers/IIS/IISIntegration/src/WebHostBuilderIISExtensions.cs#L85C17-L85C17

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/web-host.md

### Document ID

f35451f4-7c74-3ada-e969-b769428b94f4

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@QianMoXi Thanks for reporting that, I've fixed it.
