### ISSUE TITLE
Improve auth state provider guidance for BWAs

### ISSUE THREAD

**Issue by PMcVries** [dotnet/AspNetCore.Docs#31496]
### Description

Following the documentation I came across an issue configuring authentication and authorization for a Blazor Server app. The [Authorize] attribute kept redirecting to (I assume) my authentication scheme's fallback path instead of just displaying the fallback message "Not authorized. I used Cookie Authentication. Neither role-based, policy-based nor the default policy was recognized. 
After some research I've found this workaround to fix this problem. [https://github.com/dotnet/aspnetcore/issues/52317#issuecomment-1830673284](url)

The workaround just inserts a middleware step and assumingly skips the redirections issue.

Please add this information into the documentation since it seems to be a recent problem since the introduction of .NET 8. 
Thank you!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#additional-resources

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md

### Document ID

1247ee64-fbc9-ce29-0710-f6e59380f5ee

### Article author

@guardrex

**Comment by PMcVries** [comment]
@AdmiralSnyder fyi

**Comment by guardrex** [comment]
Thanks, @PMcVries ... I'll get on this tomorrow or early next week.

**Comment by guardrex** [comment]
I don't think we'll document the workaround. We're more interested in Surayya's suggestion ...

> it's better if you perform the authentication within the ASP.NET Core auth system and your authentication state provider only takes care of reflecting that state.

I think the one she's referring to this this one ...

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/PersistingRevalidatingAuthenticationStateProvider.cs

That one, along with the other auth state providers, is covered in the article, but it's only a quick mention and cross-link to the reference source.

I'll use this issue to both call out the behavior and clarify that these project template-based approaches are what the PU recommends.
