### ISSUE TITLE
Missing "/" closing tag for package ref in .NET 7 to 8 upgrade guide. 

### ISSUE THREAD

**Issue by PSCourtney** [dotnet/AspNetCore.Docs#31494]
### Description

In the article Migrate from ASP.NET Core 7.0 to 8.0
The code for adding <ItemGroup> one of the package references is missing a closing tag.

Namely:
`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">`

Fix by:
`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" **/**>`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-the-net-sdk-version-in-globaljson

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/70-80.md

### Document ID

534ab561-09c5-c33b-4394-0effba34d666

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
The syntax is correct

```
dotnet new web -n MyEmptyProject
cd MyEmptyProject
dotnet add package Microsoft.EntityFrameworkCore.Tools
```

**Comment by PSCourtney** [comment]
![Capture](https://github.com/dotnet/AspNetCore.Docs/assets/23056141/0e86e3f3-7d7f-4b52-9c18-043edfcd5243)
See attached.
