### ISSUE TITLE
Misleading typo on page "Rate limiting middleware in ASP.NET Core"

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#31501]
### Description

The [`EnableRateLimiting` and `DisableRateLimiting` attributes](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0#enableratelimiting-and-disableratelimiting-attributes) section of the page has a typo in one of the examples:

`app.MapDefaultControllerRoute();` is written twice, yet the actual function call to be demonstrated is not mentioned. Not even in the prose following the example.

![Typo](https://github.com/dotnet/AspNetCore.Docs/assets/9283914/d40b8aa5-67a8-49dc-9a97-d55687eb2ef0)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0#enableratelimiting-and-disableratelimiting-attributes

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md

### Document ID

bb96b20f-0991-d6de-4d98-192cd469460f

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
The only error I see is calling `MapDefaultControllerRoute` twice:

Consider the following code which doesn't call `RequireRateLimiting` on `MapRazorPages` or `MapDefaultControllerRoute`:
```
app.UseHttpsRedirection();
app.UseStaticFiles();

app.MapRazorPages();
app.MapDefaultControllerRoute();
app.MapRazorPages();
app.MapDefaultControllerRoute();

app.Run();
```

> yet the actual function call to be demonstrated is not mentioned. 

What would that be?
