### ISSUE TITLE
Add link to page explaining the term "Minimal API" to "Middleware in Minimal API apps"

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#31502]
### Description

The "Middleware in Minimal API apps" page explains which middleware is automatically added to WebApplication in Minimal APIs, yet it lacks …

- linking to `WebApplication` reference page (i.e., what kind of `WebApplication` class is being referred to?)
- linking to a page defining the term "Minimal API".

Please add this information.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/middleware?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/middleware.md

### Document ID

8e126168-04ac-f820-baad-c336729e4da5

### Article author

@BrennanConroy

---
[Associated WorkItem - 203534](https://dev.azure.com/msft-skilling/Content/_workitems/edit/203534)

**Comment by wadepickett** [comment]
Thanks @SetTrend for letting us know your experience with this doc and for your suggestions.  Those would be helpful links on the page.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/overview?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/webapplication?view=aspnetcore-8.0
