### ISSUE TITLE
Typo <h1> should be <p>

### ISSUE THREAD

**Issue by Masoud-Sal** [dotnet/AspNetCore.Docs#31513]
### Description

In [Route parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#route-parameters) section, instead of "the `<h1>` tag content is rendered as Blazor is amazing!" it should be "the `<p>` tag content is rendered as Blazor is amazing!"

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

@guardrex

**Comment by Masoud-Sal** [comment]
In [Route parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#route-parameters) section, instead of "the <h1> tag content is rendered as Blazor is amazing!" it should be "the <p> tag content is rendered as Blazor is amazing!"

**Comment by guardrex** [comment]
Thank you, @Masoud-Sal ... Yes! ... A 😈 got into the text. I changed the sample app that supplies the code, but I didn't update the text. I'll take care of this right now.
