### ISSUE TITLE
Numerous nameof(GetByID) that should be nameof(CreateAsync)

### ISSUE THREAD

**Issue by plblum** [dotnet/AspNetCore.Docs#31539]
### Description

Found a likely typo in examples. Functions not named GetById (like CreateAsync) were using nameof(GetById).
`public async Task<IResult> CreateAsync(Product product)
{
    if (product.Description.Contains("XYZ Widget"))
    {
        return Results.BadRequest();
    }

    _productContext.Products.Add(product);
    await _productContext.SaveChangesAsync();

    var location = Url.Action(nameof(**GetById**), new { id = product.Id }) ?? $"/{product.Id}";
    return Results.Created(location, product);
}`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/action-return-types.md

### Document ID

b51bc104-a6e2-b21f-8362-45cee22e8c22

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@plblum Thanks for reporting that, the copy/paste errors have been corrected.
