### ISSUE TITLE
[Parameter] is necessary also for [SupplyParameterFromQuery]

### ISSUE THREAD

**Issue by JZO001** [dotnet/AspNetCore.Docs#31554]
### Description

In the section "Query strings", information is missing. "SupplyParameterFromQuery" does not stand alone, [Parameter] attribute is also necessary. Without it, the parameter from the query will not be processed.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

@guardrex

**Comment by JZO001** [comment]
On my side - using .NET 7.0.15 - on a normal page (not a component), I used the "SupplyParameterFromQuery" to get an int? parameter from query. It does not work, and I had to google for a while to figure out the reason. Than I spotted out, in other examples, there is the "Parameter" also. After added it to my property into my page, than it started to work fine.

**Comment by guardrex** [comment]
> normal page (not a component)

I don't understand. This API is only for Razor components AFAIK.

Mackinnon, one of our TOP product unit engineers will be along in a bit to take a look at this and advise further. I'll email him, too, to make sure he gets the ping. He usually responds by EOD unless he's OOF. *Stand-by .......................*

**Comment by MackinnonBuck** [comment]
> On my side - using .NET 7.0.15

Ah, yep. Before .NET 8, both `[Parameter]` _and_ `[SupplyParameterFromQuery]` were required in order for a parameter's value to be supplied via query. We removed this requirement in .NET 8.

AFAICT, the docs are correct - the .NET 8 page omits the `[Parameter]` attribute, and the .NET 7 page includes it.

@guardrex, do you think it would make sense to add a note in the .NET 8 version of the docs to clarify that when using a version _earlier_ than .NET 8, the `[Parameter]` attribute must be used in conjunction with the `[SupplyParameterFromQuery]` attribute? Or do we try to avoid including info about previous .NET versions?

**Comment by guardrex** [comment]
> add a note in the .NET 8 version of the docs ... Or do we try to avoid including info about previous .NET versions?

Yes that's right about not adding it to the reference doc. I'll place a section on this in the *Migration* article. We mostly avoid doing it in the reference docs because they would eventually be filled with thousands of little "this changed in version X" remarks.
