### ISSUE TITLE
Selfsigned CA gives error

### ISSUE THREAD

**Issue by hhvdblom** [dotnet/AspNetCore.Docs#31565]
### Description

Selfsigned CA gives error while running first time. Solution: describe how to bypass this error and run on localhost with selfsigned CA.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md

### Document ID

46a7c2e0-4871-491f-02c2-54f7df2237b1

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Thanks @hhvdblom for taking the time to give up on a potential problem.

What error are you getting?   Normally Visual Studio would show a notice that the project is configured for SSL and asks if you would like to trust the self-signed cert.  If you choose to do so, it creates the cert for you and lets you know that.  This doc walks through those steps and includes screenshots, but maybe you are getting an error I am not anticipating, or I don't fully understand what you are running into.  Thanks again for sharing your experience.

**Comment by wadepickett** [comment]
I went ahead dedicated time for tested through the current version of the tutorial for Visual Studio which is the version the issue was raised on, and it seems to be working as expected following the instruction provided for trusting the self-signed cert.   

I will close this issue, but if there is something I am missing please do feel free to comment here and we can re-open if needed.  Thanks.

**Comment by hhvdblom** [comment]
Its not an error of Visual Studio but its Edge that gives the CA error while running the site with an self signed CA certificate. You will have to change the settings of Edge to trust local host with self signed CA certificates. If you dont do that you cannot run the wep app with self signed CA because the continue button is not displayed in Edge, I think thats changed because previous Edge version did that.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
