### ISSUE TITLE
Calling Blazor Web App 'recommended' with no justification is confusing

### ISSUE THREAD

**Issue by jez9999** [dotnet/AspNetCore.Docs#31572]
### Description

There are several places in the Blazor documentation where Blazor Web App, as opposed to Blazor WebAssembly Standalone App, is marked as 'recommended' with no link or justification, which I find quite confusing.  Surely in many circumstances the Standalone App is appropriate, so why is it "not recommended"?  The documentation should be made much clearer, or if there's no actual reason to recommend Blazor Web App, 'recommended' should just be removed.

### Page URL

https://learn.microsoft.com/en-gb/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=windows

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tooling.md

### Document ID

dd777362-b92d-cac6-2343-a7aaf31d0bdf

### Article author

@guardrex

**Comment by guardrex** [comment]
@jez9999 ...

> several places

If it appears elsewhere that you know of, can you let me know where you spotted it. I'm ***BURIED*** in work at the moment 😩. It will save me a search if you can report other spots.

**Comment by jez9999** [comment]
I think it's just the 2 instances on that page.

**Comment by guardrex** [comment]
Ok, thanks.
