### ISSUE TITLE
Add section for CosmosDB distributed cache

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/AspNetCore.Docs#31577]
### Description

CosmosDB has [Distributed Caching extensions](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos).

Add an entry to the [Establish Distributed Caching Services](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-8.0#establish-distributed-caching-services) section. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-8.0#establish-distributed-caching-services

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/distributed.md

### Document ID

5b9a6572-3671-0d54-b2ef-83d04f8b3e96

### Article author

@tdykstra

---
[Associated WorkItem - 203537](https://dev.azure.com/msft-skilling/Content/_workitems/edit/203537)

**Comment by tdykstra** [comment]
Thanks, @luisquintanilla. Can you provide a draft of what should go in the new **CosmosDB cache** h3 section, or should we just link to the [README](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/README.md)?

**Comment by luisquintanilla** [comment]
I think we can start with 

1. Add a bullet point to the list of distributed cache providers
2. Add a section for CosmosDB

```markdown
### Distributed Azure Cosmos DB Cache

Azure Cosmos DB that can be used in ASP.NET Core as a Session State Provider by leveraging the `IDistributedCache` interface. 

[Azure Cosmos DB](/azure/cosmos-db/introduction) is a fully managed NoSQL and relational database for modern app development that offers high availability, scalability, and low-latency access to data for mission-critical applications.

After installing the [Microsoft.Extensions.Caching.Cosmos](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Cosmos) NuGet package, you can configure an Azure Cosmos DB distributed cache as follows:

#### Reuse an existing client

The easiest way to configure your distributed cache is by reusing an existing Azure Cosmos DB client. In this case, the `CosmosClient` instance won't be disposed when the provider is disposed.

\```csharp
services.AddCosmosCache((CosmosCacheOptions cacheOptions) =>
{
    cacheOptions.ContainerName = Configuration["CosmosCacheContainer"];
    cacheOptions.DatabaseName = Configuration["CosmosCacheDatabase"];
    cacheOptions.CosmosClient = existingCosmosClient;
    cacheOptions.CreateIfNotExists = true;
});
\```

#### Create a new client

Alternatively, you can instantiate a new client. In this case, the `CosmosClient` instance will get disposed when the provider is disposed.

\```csharp
services.AddCosmosCache((CosmosCacheOptions cacheOptions) =>
{
    cacheOptions.ContainerName = Configuration["CosmosCacheContainer"];
    cacheOptions.DatabaseName = Configuration["CosmosCacheDatabase"];
    cacheOptions.ClientBuilder = new CosmosClientBuilder(Configuration["CosmosConnectionString"]);
    cacheOptions.CreateIfNotExists = true;
});
\```
```

Make sure to remove the backticks in the code snippets. I added those so it's easier to copy-paste the entire block.

@Pilchie can you take a look and see if this is accurate?

**Comment by Pilchie** [comment]
Looks good to me, but also tagging @kirankumarkolli and @ealsur.

**Comment by ealsur** [comment]
This looks good, aligns with the examples in https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos

I also wonder if you want to link the GitHub repo too
