### ISSUE TITLE
Comment in example identifies a method that I cannot find anywhere

### ISSUE THREAD

**Issue by plblum** [dotnet/AspNetCore.Docs#31596]
### Description

Locate this comment:
        // Don't rely on the file.FileName as it is only metadata that can be manipulated by the end-user
        // Take a look at the `Utilities.IsFileValid` method that takes an IFormFile and validates its signature within the AllowedFileSignatures
I'd love to use Utilities.IsFileValid. I've searched all of the .net documentation and cannot yet find a match. Perhaps a wild goose chase? Perhaps a misspelling? 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md

### Document ID

3fec6e08-fc99-7a5c-796f-3f2347cad891

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
It's in the sample app cross-linked by the article just above where that remark appears ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files/samples/8.x/StaticFileAuth/Utilities.cs
