### ISSUE TITLE
Microsoft.AspNetCore.HttpOverrides package is depriciated.

### ISSUE THREAD

**Issue by yogyogi** [dotnet/AspNetCore.Docs#31590]
### Description

The package **Microsoft.AspNetCore.HttpOverrides** used in this article is depreciated so article need to be updated to newer package.  
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-8.0&tabs=linux-ubuntu

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md

### Document ID

815fe034-c9fc-aee3-a8b5-f2e860b30302

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Hello @yogyogi ... It's only depreciated for direct use. It's part of the shared framework, which is added automatically for the `Microsoft.NET.Sdk.Web` SDK.

https://learn.microsoft.com/aspnet/core/fundamentals/metapackage-app

**Comment by yogyogi** [comment]
OK. Thank you.

**Comment by guardrex** [comment]
I'll go ahead and slap that line on there. I think Rick will like it.
