### ISSUE TITLE
SignalR Redis Configuration needs update

### ISSUE THREAD

**Issue by breynolds** [dotnet/AspNetCore.Docs#31631]
### Description

The existing .net 8 documentation for SignalR horizontal scaling with Redis tells us to configure it like this:
```
services.AddSignalR()
  .AddStackExchangeRedis(connectionString, options => {
      options.Configuration.ChannelPrefix = "MyApp";
  });
```

When we use the existing documentation to configure a redis backplane for SignalR, we receive a warning that says:
```
warning CS0618: 'RedisChannel.implicit operator RedisChannel(string)' is obsolete: 
'It is preferable to explicitly specify a PatternMode, or use the Literal/Pattern methods' 
```

Please update the .Net 8 documentation to have a signalr setup that does not produce warnings. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/redis-backplane.md

### Document ID

bddd7575-422d-4342-af48-f6b0979fb69a

### Article author

@bradygaster

**Comment by BrennanConroy** [comment]
Feel free to put up a PR to fix this, it should be as simple as changing `"MyApp"` to `RedisChannel.Literal("MyApp")`
