### ISSUE TITLE
Topic could use a conceptual introduction

### ISSUE THREAD

**Issue by plblum** [dotnet/AspNetCore.Docs#31649]
### Description

I started reading this topic without any prior knowledge of rate limiting. I had my suspicions to its purpose, but it took getting deep into the article to prove it to myself.
I found the link to Maarten's post at the bottom and it was great help. Something from that as an intro to this article will help.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md

### Document ID

bb96b20f-0991-d6de-4d98-192cd469460f

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. This is an advanced topic.
