### ISSUE TITLE
Issue with getting query parameters

### ISSUE THREAD

**Issue by joel-matthias** [dotnet/AspNetCore.Docs#31666]
### Description

In the section about getting query parameters using SupplyParameterFromQuery attribute, I also had to add the Parameter attribute for it to work. The documentation does not indicate this.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @joel-matthias ... You must be targeting .NET 7 or earlier. The requirement was dropped for >=8.0. The docs for <8.0 correctly call out that it's needed.
