### ISSUE TITLE
Http Files and how to use them in an automated way with a unit test framework

### ISSUE THREAD

**Issue by minoseah629** [dotnet/AspNetCore.Docs#31668]
### Description

a major question I have of http files is that it can provide testing for API Testing, but is not oriented to any integration with a unit test framework and a build / test pipeline.  the concept is unique but is limited by the lack of these 2 discrepancies.  

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

**Comment by tdykstra** [comment]
This is a feature request rather than a documentation issue. Please use the Visual Studio **Suggest a feature** tool, at **Help** > **Send feedback**:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/1569635/bec96e20-f9a3-42fe-9278-50a1714d37d9)
