### ISSUE TITLE
如何才能看的懂微软.NET系列文档

### ISSUE THREAD

**Issue by W2426566602** [dotnet/AspNetCore.Docs#31687]
### Description

没有demo ，内容散乱 
链接很多 一个系列能跳很多页面 

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-enable-qrcodes.md

### Document ID

270bedc7-a636-5bd0-9e2f-e42235deec8c

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Yes, authentication is complex.
 Start at https://learn.microsoft.com/aspnet/core/security/authentication/
