### ISSUE TITLE
Missing (link to) details of the "subset" of .NET API available through WebAssembly 

### ISSUE THREAD

**Issue by anderscarlman-bambora** [dotnet/AspNetCore.Docs#31692]
### Description

Documentation page states "/.../while Blazor WebAssembly apps are limited to a subset of .NET APIs"
Where can I find an explicit list of the API components that are part of this subset (or possibly the inverse, what components are NOT part of the subset)?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-6.0#complete-net-api-compatibility

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hosting-models.md

### Document ID

72c2a844-ffb2-4799-2c7a-a7a73d3b6833

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the ❓, @anderscarlman-bambora. IIRC and AFAIK, they merely didn't want to try and list them explicitly because they're subject to change without notice and probably churn a bit release-to-release.

***However*** .... ***where*** to find out exactly which .NET assemblies are included in a given release we might be able to cross-link to the reference source. Stand-by and I'll see what we can do. If I don't see a good cross-link, I'll ping a product unit engineer to assist.

**Comment by guardrex** [comment]
I emailed Steve to ask about this. *Stand-by for his response ........................*

**Comment by guardrex** [comment]
No response 🙈😆. I'll try Mackinnon ........ *Stand-by .........................*

**Comment by MackinnonBuck** [comment]
Hm, I'm not aware if we have a curated list of APIs that are supported on the browser. But you could manually search for a list of all APIs annotated with [`[UnsupportedOSPlatform("browser")]`](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Runtime/Versioning/PlatformAttributes.cs,34041602e232c616,references) to find out what's not supported in WebAssembly. If we decide to make any change to the docs, we could call out that using APIs marked with `[UnsupportedOSPlatform("browser")]` in WebAssembly will result in a warning at compile-time and an exception at runtime. I'm not sure why a complete list of unsupported APIs is necessary if you can specifically check the ones you're interested in, but maybe there's a common use case I'm not thinking of!

**Comment by guardrex** [comment]
I thought it would be nice to cross-link ... even just with a search filter such as you just provided ... that would reveal in the repo the ones that aren't available.

I really don't think that the *Hosting Models* article is the right spot for the coverage; but of course, this remark on "the subset" can be cross-linked to wherever I would end up placing coverage. I'll need to 🤔 on the coverage location.

It's ***FRIDAY*** 🎉  and I'm out of time and out of 🧠 power for the week. I'll look into this next week to see if we can do anything to help readers understand the "subset" remark.
