### ISSUE TITLE
Provide detail on the order of the synchronous and asynchronous methods

### ISSUE THREAD

**Issue by ShaunCurtis** [dotnet/AspNetCore.Docs#31690]
### Description

Small comment:

In the sections on `OnInitialized{Async}` and `OnParametersSet{Async}` you don't explicitly say that the synchronous method is called before the asynchronous one.  I may of course have missed the information else!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @ShaunCurtis ... Yes, we can add something on that if that's always true. We'll need the PU to confirm it tho, so I'll ping Steve now to ask.

**Comment by guardrex** [comment]
***Confirmed!*** (offline) ... Yes, he says go ahead and work this. I'll get to it soon because it will only take a couple of minutes to resolve.
