### ISSUE TITLE
Missing RenderFragment information for blazor

### ISSUE THREAD

**Issue by chsienki** [dotnet/AspNetCore.Docs#31697]
### Description

The section `Templated Razor Delegates` is currently only applicable to MVC and Razor pages. The code samples as listed don't work in Blazor, where instead you need to use `RenderFragment`.

PR https://github.com/dotnet/AspNetCore.Docs/pull/31696 adds a note that the docs as-is don't apply to Blazor, but we should also add a section that shows how to do the equivalent in Blazor using `RenderFragment`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-8.0#templated-razor-delegates

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md

### Document ID

a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Hello @chsienki ... It's covered in the Blazor docs. We keep almost all of the Blazor content in that node. `RenderFragment`s are covered in several spots pertaining to different use case scenarios. The two main coverage spots are ...

* *Components* Overview (search the article text for "RenderFragment": https://learn.microsoft.com/aspnet/core/blazor/components/
* *Templated components*: https://learn.microsoft.com/aspnet/core/blazor/components/templated-components
