### ISSUE TITLE
Should user-jwts tool also work inside the Microsoft Docker SDK image?

### ISSUE THREAD

**Issue by bmcdavidepi** [dotnet/AspNetCore.Docs#31715]
### Description

Here is a sample repository which works locally but not in a docker compose run scenario which is intended to run during CI builds.

https://github.com/bmcdavidepi/user-jwts

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/jwt-authn?view=aspnetcore-8.0&tabs=linux

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/jwt-authn.md

### Document ID

f76a2aaf-732a-f686-343b-d811faa43d44

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Nope, per the doc, this is for local dev only.
