### ISSUE TITLE
Missing information in article asp0013

### ISSUE THREAD

**Issue by wilfriedb** [dotnet/AspNetCore.Docs#31742]
### Description

The article states "`Configure` isn't the recommended strategy for reading and writing to configuration in a minimal API application." but it's doesn't say why this isn't recommended. Also it doesn't say why this method exists in te first place regarding that `ConfigureAppConfiguration` exists, and doesn't give counter example for which use cases it is actually recommended.

And more, the article is talking about `Configure` while the actual method name is `ConfigureAppConfiguration`, which is confusing.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0013?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0013.md

### Document ID

71ea104c-b4a9-ce36-0b90-1fdba5956ddc

### Article author

@Rick-Anderson 

---
[Associated WorkItem - 209390](https://dev.azure.com/msft-skilling/Content/_workitems/edit/209390)

**Comment by guardrex** [comment]
@Rick-Anderson ... I placed you in the OP because you know that Safia moved teams.
