### ISSUE TITLE
Mention that App.razor always renders statically

### ISSUE THREAD

**Issue by mrlife** [dotnet/AspNetCore.Docs#31740]
### Description

The App.razor component always renders statically. One implication is that any services included via `@inject` directives in _Imports.razor will be created more than once if App.razor's children contain a different render mode.

Everything I've seen about render modes up until now talked about how services would be created more than once if pre-rendering was enabled (once for pre-render and once for the regular render). So, the first paragraph above was unexpected.

ref: https://github.com/dotnet/aspnetcore/issues/53804#issuecomment-1932592019

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-modes.md

### Document ID

7c9948a3-9886-8097-6014-492a4c21ea4e

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @mrlife ... I'll get to this as soon as I can, but I'm buried in work at the moment. In the meantime, for ...

> So, the first paragraph above was unexpected.

Can you clarify which paragraph?

**Comment by mrlife** [comment]
Hi, @guardrex! Thank you, the paragraph referred to is:
> The App.razor component always renders statically. One implication is that any services included via @inject directives in _Imports.razor will be created more than once if App.razor's children contain a different render mode.

**Comment by guardrex** [comment]
Oh, I see :smile: ... that ***WAS*** the paragraph.

**Comment by guardrex** [comment]
@mrlife ... I'm looking at this now.

> Is the only workaround to @inject into each razor component instead of in _Imports.razor?

Did you try placing an `_Imports.razor` file with the service injection ***in the `Pages` folder*** and confirm that it won't apply to the `App` component from there?

**Comment by guardrex** [comment]
Very well ... I'm working that idea into the PR that I'm working on. I'll ping you on the PR shortly and we can take a look at my ideas for addressing this situation.
