### ISSUE TITLE
Clarify purpose of CONFIGURE_RUNTIME env var for WASM config

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#31754]
### Description

The env var `CONFIGURE_RUNTIME` is used by the framework, but we don't have guidance on what it does. This issue will track adding additional information on its purpose to the article.

cc: @hakenr 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/startup.md

### Document ID

11f8db3d-9988-e0a1-89c5-c3552ee47b93

### Article author

@guardrex

**Comment by hakenr** [comment]
@guardrex I think you've been caught up in the confusion of that name, and even in the test project, it's used only as a test variable (the framework doesn't interact with it in any way):
https://github.com/dotnet/aspnetcore/blob/main/src/Components/test/testassets/BasicTestApp/ConfigureRuntime.razor#L5

**Comment by guardrex** [comment]
# 😆

The PU really got the better of me on this one!
