### ISSUE TITLE
[Blazor] Handle Errors - misleading examples on DispatchExceptionAsync (net8)

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31765]
@guardrex I believe the `TimerService.cs` + `Notifications.razor` example on `DispatchExceptionAsync` in [Handle errors](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0) - [Handle caught exceptions outside of a Razor component's lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#handle-caught-exceptions-outside-of-a-razor-components-lifecycle) section is wrong.

Following the article's guidance (and the readily available example in the [blazor-samples repo](https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorSample_BlazorWebApp/Components/Pages/Notifications.razor) and easily applicable there), the exception added to `TimerService.cs` is reported to the user even without adding the `try-catch` and `DispatchExceptionAsync(ex)` to `OnNotify` method.
  * This happens due to the `await Timer.Start()` call in `StartTimer()` method, where the exception from the timer loop gets propagated to Blazor
    ```csharp
    private async Task StartTimer()
    {
        await Timer.Start();
    }
    ```
  * Changing this method to a fire-and-forget approach causes exceptions not to be reported to the user
    ```csharp
    private void StartTimer()
    {
        _ = Timer.Start();
    }
    ```
Unfortunately, adding a `try-catch` block to the `OnNotify()` method as suggested does not effectively capture or handle exceptions, since the try block does not encompass the potential source of the exception (either directly or by capturing exceptions from the task where they occur). Incorporating this try-catch into the modified example above does not route exceptions to the previously added `ErrorBoundary` as expected.

I can work on creating a functional example that incorporates `DispatchExceptionAsync(ex);` based on the `TimerService.cs` and `Notifications.razor` if that would help. However, I'd appreciate it if you could first validate the concerns I've outlined above.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#handle-caught-exceptions-outside-of-a-razor-components-lifecycle

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/handle-errors.md

### Document ID

66a0b1c2-c45c-98ca-9808-6f340a861c44

### Article author

@guardrex

**Comment by hakenr** [comment]
@guardrex  I scratched a sample demonstrating the practical use of `DispatchExceptionAsync` method.
For easier reading I submitted my code as draft PR to the blazor-samples repo:
https://github.com/dotnet/blazor-samples/pull/186/files?diff=split&w=1

(Please double-check the sample with the PU if you decide to use it in the doc.)

**Comment by guardrex** [comment]
BTW ... Note that issues should be opened using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to the GitHub issue that cross-links the topic and pings us automatically. I'll add the metadata to this issue manually.

I'll take a look today to see if this is a 🦖-generated example or a PU-generated example. If furnished by the PU, we'll get their input for sure. I'll take a closer look at the issue itself Tuesday (or Wednesday if things get really crazy).

**Comment by guardrex** [comment]
Let's consider the remark change on the patch PR along with this issue at this time.

The recommended change is on Line 138 ...

> A common scenario is if a component wants to start an asynchronous operation but doesn't await a \<xref:System.Threading.Tasks.Task>. If the operation fails, you may still want the component to treat the failure as a component lifecycle exception for the following example goals:

... to (changing underscores of the original suggestion to asterisks for emphasis) ...

> A common scenario is if a component wants to start an asynchronous operation but doesn't await a \<xref:System.Threading.Tasks.Task> (a technique sometimes called \*fire and forget\*). If the operation fails, you may still want the component to treat the failure as a component lifecycle exception for the following example goals:

**Comment by guardrex** [comment]
Steve worked with me on the original content. I'm not sure if he checked the composition of the demo that I pitched. This section was set up on ...

https://github.com/dotnet/AspNetCore.Docs/pull/28936

WRT how the async method is called between this section's discard/fire-and-forget example (`_ = SendReportAsync();`), which came from his comment on the PR, and the demo's example (`await Timer.Start();`), my initial reading of his remarks is that discarding the `Task` is an *additional scenario* and not strictly required for the purpose of surfacing exceptions as lifecycle exceptions. I'll review his remarks closely when I get back to this.

Let me circle back around to this Tuesday morning (possibly Wednesday if things get crazy 😵 tomorrow). It might be a good idea not to cloud the issue with the original example, which is used in the other section. If we provide a demo, it might be best to create a sister component and paired services for this section's example.

**Comment by guardrex** [comment]
Things are still ***CRAZY*** 😵 right now. I'm merging quite a bit of security guidance. I'll try to get back to this tomorrow, but I can't make a promise on it. We're also hitting a 3-day weekend here. If it gets pushed to early next week, it will be Tuesday. I'll get back to this *ASAP* ⛰⛏😅.

**Comment by hakenr** [comment]
Don't worry, take your time. If the bot doesn't automatically close the issue due to inactivity, I'm ok.

**Comment by guardrex** [comment]
Fortunately, we don't run automated code that will close issues unexpectedly. I have seen quite a few devs get rather upset when that happens on the PU repo. Because we don't do it here, I avoid quite a few 💀 *threats of 🦖 dismemberment!* 😨

I think this is going to be for early next week. The other issue ... `ProductDetails` for the sample app is quick to resolve, so that can happen ... *right now* 🏃‍♂️.
