### ISSUE TITLE
SignalR app.MapHub is this still accurate or should it be endspoints.MapHub?

### ISSUE THREAD

**Issue by jafin** [dotnet/AspNetCore.Docs#31766]
### Description

[Enter feedback here]
This page talks about configuring SignalR via `app.MapHub<>`  yet other documentation suggest that is deprecated and instead use something like

```c#
app.UseEndpoints(endpoints => {
   endpoints.MapHub<T>("/notify");
}
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/hubs.md

### Document ID

fb016cdc-d281-6b5b-7466-2c718e7274b4

### Article author

@bradygaster

**Comment by BrennanConroy** [comment]
> other documentation suggest that is deprecated

What documentation suggests this?

Both ways are supported, in fact if you look closely they are actually the same method.

**Comment by wadepickett** [comment]
Closing since the existing sample is supported.
