### ISSUE TITLE
Defaults for HttpClient helper methods 

### ISSUE THREAD

**Issue by markarnolditpro** [dotnet/AspNetCore.Docs#31778]
### Description

@guardrex  Given the option to modify Headers shown [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0&pivots=webassembly#httpclient-and-httprequestmessage-with-fetch-api-request-options) it would be great to see what the defaults for some of the more interesting headers when using the **HttpClient Helpers**, such as `Headers.Accept`, `Headers.AcceptEncoding`,  `Content.Headers.ContentType`, `HttpCompletionOption`, etc.  I may be going to unnecessary troubles to configuring what's already default in the Helpers.   Thanks!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0&pivots=webassembly#typed-httpclient

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md

### Document ID

c7e59a08-1c60-32c2-75fd-33cb77ff7a5d

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @markarnolditpro ... I'll need to get back to you in a day (***or three!*** 😆). I'm experiencing an extremely high Blazor issue load at the moment ⛰️⛏️😅. I'll get back to you as soon as I can.

**Comment by guardrex** [comment]
OK ... ***I'm BACK!*** 😄 

Well ... I don't think that are very many (or any 😄) to describe ***for Blazor*** (i.e., headers that Blazor sets for you). AFAIK, a new `HttpClient` will get the default request headers ...

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultrequestheaders?view=net-8.0#system-net-http-httpclient-defaultrequestheaders

... based on a new `HttpRequestHeaders` ...

[HttpRequestHeaders ](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.httprequestheaders?view=net-8.0)

... and I don't think very many (or any) of those get set ***by Blazor***.

Let's ask @MackinnonBuck if he has a comment on this ... about Blazor setting any request headers, which I don't think Blazor really does, and any non-Blazor influences on headers ... Kestrel influences ... middleware along the pipeline ... the browser itself. I'm not sure that we can be specific at all, except perhaps to say that ***Blazor*** doesn't set additional request headers for an `HttpClient`.

**Comment by MackinnonBuck** [comment]
> I'm not sure that we can be specific at all, except perhaps to say that Blazor doesn't set additional request headers for an `HttpClient`.

Yep, this sounds right to me 🙂

**Comment by markarnolditpro** [comment]
Thanks @MackinnonBuck @guardrex.  Farther down in the doc I see: 

> Blazor's client-side implementation of [HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) uses [Fetch API](https://developer.mozilla.org/docs/Web/API/fetch). Fetch API allows the configuration of several [request-specific options](https://developer.mozilla.org/docs/Web/API/fetch#Parameters)....

Implication is that `HttpClient` for Blazor WASM is something "else", hence my concern that it may not have the same functionality / behavior as a non-browser implementation.

**Comment by guardrex** [comment]
It's "something else" in the sense that it isn't an ASP.NET Core API ... it's a JavaScript API. It's used by Blazor, so it's not "something else" in that sense.

The article covers how one can use the `HttpRequestMessage` API of `System.Net.Http` to interact with headers. I think I'll add a remark immediately under that to the effect that Blazor doesn't directly set other request headers. Actually, I don't think the Fetch API does either, but I won't mention that. That's covered by the Fetch API docs, which are cross-linked. The user agent interacts directly with headers, but that's also in external doc sets, including the Fetch API docs, and doesn't pertain to Blazor.
