### ISSUE TITLE
Broken Url - sample app

### ISSUE THREAD

**Issue by stanimirovv** [dotnet/AspNetCore.Docs#31786]
### Description

in this part of the documentation:
![Screenshot 2024-02-13 at 17 35 52](https://github.com/dotnet/AspNetCore.Docs/assets/4281340/73922ebb-a967-4b5a-9520-3e2031ddcbce)

The hyper link leads to a broken path: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/%7E/fundamentals/dependency-injection/samples/6.x

The correct path is: https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/dependency-injection/samples/6.x

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/dependency-injection.md

### Document ID

2251f557-dd3a-ec35-2558-6243337db009

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.

**Comment by stanimirovv** [comment]
Yep, sounds like a plan.

**Comment by stanimirovv** [comment]
@Rick-Anderson  PR attached. URL was broken in an additional place as well.
