### ISSUE TITLE
Blank C# Example - Handle HEAD request with an OnGet handler fallback

### ISSUE THREAD

**Issue by jnic40** [dotnet/AspNetCore.Docs#31825]
### Description

The "Handle HEAD requests with an OnGet handler fallback" section has a blank C# code block.

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-8.0&tabs=visual-studio&source=docs#handle-head-requests-with-an-onget-handler-fallback

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-8.0&tabs=visual-studio&source=docs

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/index.md

### Document ID

b3e2bc87-1582-2d34-c7c2-7c8e901ac771

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thanks for reporting that! I'm fixing it in PR #31829.
