### ISSUE TITLE
Add Grpc Client factory sample for HealthCheck client

### ISSUE THREAD

**Issue by SamGuoMsft** [dotnet/AspNetCore.Docs#31828]
### Description

I saw the health check client sample from here
[gRPC health checks in ASP.NET Core | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-8.0#call-grpc-health-checks-service), I also did the client factory way since the HealthClient is just a grpc client generated by proto file. It will be great to share a sample of client factory DI approach, especially how to do DI with naming for multiple HealthClient for different underlying grpc service.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-8.0#call-grpc-health-checks-service

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/grpc/health-checks.md

### Document ID

5a1e8570-b223-d4b9-c85f-afeb2e3e8941

### Article author

@JamesNK

---
[Associated WorkItem - 258556](https://dev.azure.com/msft-skilling/Content/_workitems/edit/258556)

**Comment by JamesNK** [comment]
I think a small snippit of code in this section - https://learn.microsoft.com/en-us/aspnet/core/grpc/health-checks?view=aspnetcore-8.0#call-grpc-health-checks-service - is enough.

e.g. configure the client
```cs
builder.Services
    .AddGrpcClient<Health.HealthClient>(o =>
    {
        o.Address = new Uri("https://localhost:5001");
    })
```
Then get `Health.HealthClient` instance via DI and make a call.
