### ISSUE TITLE
Generic documentation issue

### ISSUE THREAD

**Issue by Porkechebure** [dotnet/AspNetCore.Docs#31846]
### Description

Please fire Rick Anderson.
He isn't able to write docs and all of his docs are confusing and word salads.

Really, get some freshman out of school and will do much better.
Or let your OpenAI LLM models do it because he is skilled in writing like a schizophrenic amateur blog owner

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-8.0&tabs=windows

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md

### Document ID

ba688ac2-e90e-fce5-f60d-40c2553c3efd

### Article author

@tdykstra

**Comment by wadepickett** [comment]
Please review the code of conduct here: https://dotnetfoundation.org/about/policies/code-of-conduct.
Closing this issue.
