### ISSUE TITLE
Missing row in sample

### ISSUE THREAD

**Issue by pietroorlando** [dotnet/AspNetCore.Docs#31855]
### Description

In the final part of the article, in the part "completed Todo component" is missing the row:

@rendermode InteractiveServer

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md

### Document ID

23f2cad2-31f9-d5d1-671c-5613fb812b19

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @pietroorlando ... Yes, that happened because the example at the end comes from the sample app and not from an INCLUDE file that resides here with the article.

I'll fix this shortly ... sometime before EOD. Thanks for letting me know about it.
