### ISSUE TITLE
Blazor Convention Authorization when pages folder in different assembly

### ISSUE THREAD

**Issue by yadavvineet** [dotnet/AspNetCore.Docs#31869]
# Blazor Convention Authorization not working when target pages in different assembly. 

i have a normal mvc project called `ProjectA`. This references another project called `ProjectA.Blazor` which is a blazor project. this works fine. ALl pages/components works perfectly fine. Also for authentication, it works fine if i explicitly use. i am using AuthorizeView with policy, which works fine. 

The challange is i want to protect the complete pages. I tried to follow the convention based authorization as mentioend in page as mentioned here: https://learn.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-8.0
The condition is the target folder `Pages/Admin` is in project ProjectA.Blazor. The policies are not applied at all. 
i have tried all permutations, combinations for parameters but nothing seems to work.

Is this some bug or limitation or am i missing something. 

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [x] .NET 8
* [ ] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```
//tried diff valuies, nothing seems to work
options.Conventions.AuthorizeFolder("/Pages");
options.Conventions.AuthorizeFolder("/Pages/Admin");
options.Conventions.AuthorizeFolder("/Admin");
```
</details>

**Comment by guardrex** [comment]
Actually, @yadavvineet ... Open that for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/31869
```

... to the bottom of your opening comment so that I can follow along.

**Comment by guardrex** [comment]
Note that they might need a minimal GH repro project that demonstrates what you're doing and the problem that you're seeing.
