### ISSUE TITLE
[Blazor] Components overview - Capture references to components - misleading example with event handler delegate ReferenceParent2.razor

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31860]
### Description

> A component reference is only populated after the component is rendered, and its output includes ReferenceChild's element. Until the component is rendered, there's nothing to reference.
> To manipulate component references after the component has finished rendering, use the OnAfterRender or OnAfterRenderAsync methods.

The preceding paragraphs explain that you can only use a component reference after the referred component is rendered, typically in the `OnAfterRender` method. I'm puzzled by the focus on event handlers in the next paragraph, suggesting two approaches:
* lambda expression
* event handler delegate

> To use a reference variable with an event handler, employ a lambda expression or assign the event handler delegate in the [OnAfterRender or OnAfterRenderAsync methods](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#after-component-render-onafterrenderasync). This ensures the reference variable is assigned before the event handler is set up.

```razor
@page "/reference-parent-1"

<PageTitle>Reference Parent 1</PageTitle>

<h1>Reference Parent Example 1</h1>

<button @onclick="@(() => childComponent?.ChildMethod(5))">
    Call <code>ReferenceChild.ChildMethod</code> with an argument of 5
</button>

<ReferenceChild @ref="childComponent" />

@code {
    private ReferenceChild? childComponent;
}
```

The discussion here revolves not around event handlers and their syntax, but the general safety of using component references. Guarding the usage of a component reference with a null-conditional operator (`childComponent?.ChildMethod()`) is one approach and is not limited to lambda expressions.

The `ReferenceParent2.razor` example doesn't add value by using the `callChildMethod` event handler delegate, as the only code in `CallChildMethod()` is also guarded with a null-conditional operator.

```razor
@page "/reference-parent-2"

<PageTitle>Reference Parent 2</PageTitle>

<h1>Reference Parent Example 2</h1>

<button @onclick="@(() => callChildMethod?.Invoke())">
    Call <code>ReferenceChild.ChildMethod</code> with an argument of 5
</button>

<ReferenceChild @ref="childComponent" />

@code {
    private ReferenceChild? childComponent;
    private Action? callChildMethod;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            callChildMethod = CallChildMethod;
        }
    }

    private void CallChildMethod()
    {
        childComponent?.ChildMethod(5);
    }
}
```

The original intention might have been to present an alternative to the null-conditional operator guard, but I still argue that enabling/disabling event handlers by using a delegate assigned in `OnAfterRender` complicates readability and maintainability, even if it technically works.

To demonstrate an alternative approach to guarding the component reference with a null-conditional operator, consider using a `bool isReady` flag. This can be checked whenever you need to verify the component reference is usable. Note: The `OnAfterRender` method doesn't guarantee the component reference will be set and ready, e.g., if the referred component is conditionally rendered.

```razor
@page "/reference-parent-2"

<PageTitle>Reference Parent 2</PageTitle>

<h1>Reference Parent Example 2</h1>

<button @onclick="CallChildMethod">
    Call <code>ReferenceChild.ChildMethod</code> with an argument of 5
</button>

<ReferenceChild @ref="childComponent" />

@code {
    private ReferenceChild? childComponent;
    private bool isReady;

    protected override void OnAfterRender(bool firstRender)
    {
            isReady = true;
    }

    private void CallChildMethod()
    {
        if (!isReady)
        {
           return;
        }
        childComponent?.ChildMethod(5);
    }
}
```

My proposal:
1. Remove the focus on "event handlers" from the explanation.
2. Remove the whole `ReferenceParent2.razor` example or replace it with code using an `isReady` (or better named) flag if we want to show alternative approach to null-checking of component reference.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md

### Document ID

31ad18df-1904-bbdd-cfed-8d0d0267c10e

### Article author

@guardrex

**Comment by SteveSandersonMS** [comment]
I agree the content here can be simplified. I'm not certain why the docs suggest explicitly capturing a delegate for `callChildMethod` since it would work exactly the same without doing that.

That is, this code in the doc:

```razor
<button @onclick="@(() => callChildMethod?.Invoke())">
    Call <code>ReferenceChild.ChildMethod</code> with an argument of 5
</button>

<ReferenceChild @ref="childComponent" />

@code {
    private ReferenceChild? childComponent;
    private Action? callChildMethod;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            callChildMethod = CallChildMethod;
        }
    }

    private void CallChildMethod()
    {
        childComponent?.ChildMethod(5);
    }
}
```

... could be simplified to:

```razor
<button @onclick="@CallChildMethod">
    Call <code>ReferenceChild.ChildMethod</code> with an argument of 5
</button>

<ReferenceChild @ref="childComponent" />

@code {
    private ReferenceChild? childComponent;

    private void CallChildMethod()
    {
        childComponent!.ChildMethod(5);
    }
}
```

I think it's better to use `childComponent!.ChildMethod` (rather than `childComponent?.ChildMethod`) so that you get a clear error if `childComponent` is somehow not yet populated (which it always will be in this example).

@guardrex I think we should remove the suggestion to "assign the event handler delegate in the OnAfterRender or OnAfterRenderAsync methods". Unless I'm missing something, there's no reason for people to be capturing these delegates manually, and it will make no difference to the validity of calling them.

**Comment by guardrex** [comment]
@SteveSandersonMS ... It would've been something pertaining to @mrlife's discussion with Artak here 👉 https://github.com/dotnet/AspNetCore.Docs/pull/19038.

I'll get your updates :point_up: scheduled now.

**Comment by hakenr** [comment]
@guardrex Ah, now I understand the issue the original samples were addressing. It's not about "the component reference not being available at the moment of clicking the button." Rather, it's about "the component reference not being available at the moment of assigning the `@onClick` delegate," where the incorrect approach is `@onclick="childComponent.ChildMethod"`. In my opinion, I suggest explicitly stating something like, "You cannot use `@onclick="childComponent.ChildMethod"` because the component reference is not available at the moment of assigning such an expression. Use a `HandleClick` method or a lambda expression instead."

cc @SteveSandersonMS

**Comment by guardrex** [comment]
It's already on the PR, @hakenr ... let me know over there how the draft text works. We can work on the wording further if needed.
