### ISSUE TITLE
ModelState is invalid

### ISSUE THREAD

**Issue by meowthing** [dotnet/AspNetCore.Docs#31863]
Hello

I'm working through the "Razor Pages with EFCore" tutorial, and am struggling to understand why my ModelState is invalid when trying to do any CRUD operation after modifying the code to use TryModelUpdateAsync.

For example, after making the changes to the Course pages (https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-8.0), when debugging the Create request, the `ModelState.IsValid` will return `false`. 

Looking at the model values it appears the properties not present in the form submission, such as Department, Enrollments and Instructors are null, which leads to their validation state to be `Invalid`. My questions are, why, and how do I properly address this?

For reference, linked is my personal repo of the work thus far: https://github.com/meowthing/ContosoUniversityEFCore

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/update-related-data.md

### Document ID

9bc46ffa-60db-bdee-0984-fab183c8f503

### Article author

@tdykstra

---
[Associated WorkItem - 214380](https://dev.azure.com/msft-skilling/Content/_workitems/edit/214380)

**Comment by tdykstra** [comment]
See the [Troubleshooting section](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-8.0&tabs=visual-studio#troubleshooting) of the first tutorial in the series. The sample app that section links to works, so you can look through what you built by following the tutorial and compare it to the sample app to see where the differences are.

**Comment by meowthing** [comment]
It turns out I missed out on removing the `<Nullable>enable</Nullable>` from the csproj file. Doing so made the Model State ignore the nullable references when doing CRUD operations.
