### ISSUE TITLE
Person property and migration discrepancy

### ISSUE THREAD

**Issue by smiller7812** [dotnet/AspNetCore.Docs#31895]
### Description

In the Person class you have the FirstMidName property but then in the modified migration you have INSERT INTO FirstName.  They both need to match.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/inheritance.md

### Document ID

aa826512-74a5-752a-0ad0-0f8133f6c39e

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thank you for contacting us. The Column attribute on the FirstMidName field maps that field to the FirstName column in the database.
