### ISSUE TITLE
Cookie example does not work for .Net 8 template because the state container does not instantiate in user scope

### ISSUE THREAD

**Issue by kaleidocore** [dotnet/AspNetCore.Docs#31899]
### Description

This example does not seem to work with the .Net 8 Blazor template, i.e. when using the new type of server-interactive rendering.
The reason is that the root App component does not render in user-scope, but rather in some anonymous pre-render scope that you cannot disable. This causes the state container (TokenProvider service) to instantiate once for the App component while a different (user-scoped) instance is created for the consuming component.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?preserve-view=true&view=aspnetcore-8.0#pass-tokens-to-a-server-side-blazor-app

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/additional-scenarios.md

### Document ID

c98be365-408d-7ee6-cb74-14c44d01b0b8

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @kaleidocore ... This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/31691. Although I've pinged engineering for assistance with it, I haven't heard back yet.

I'll take two actions...

1. I'll ping again offline (email) on Monday.
2. I'll research further on my own and report back on the other issue. Keep an 👁️ on it for an update by Monday afternoon EST.

**Comment by guardrex** [comment]
One more thing ... depending on what ur trying to implement, take a look at our new article and samples for BWAs with OIDC at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

**Comment by kaleidocore** [comment]
@guardrex Thanks for the very quick reply and suggestion! I was actually not trying to implement authentication but rather theming and localization, which are also based on cookies before first render to avoid FOUC. I did however (independently) discover the workaround suggested in the https://github.com/dotnet/AspNetCore.Docs/issues/31691#issuecomment-1937358269 in the duplicate post. Sorry for the dupe!

**Comment by guardrex** [comment]
For managing localization in a BWA, see the PR that I just put up this morning, and my test app is linked there. Perhaps, it will help with your project.

https://github.com/dotnet/AspNetCore.Docs/pull/31894

**Comment by guardrex** [comment]
Re-opening for work now that we have knowledge of ...

https://github.com/javiercn/BlazorWebNonceService/

... via [the PU issue](https://github.com/dotnet/aspnetcore/issues/54134#issuecomment-1967290030).

I'll probably work this along with https://github.com/dotnet/AspNetCore.Docs/issues/31691 on the same PR. I hope to reach this work within the next few days.

**Comment by kaleidocore** [comment]
> Re-opening for work now that we have knowledge of ...
> 
> https://github.com/javiercn/BlazorWebNonceService/
> 

Just FYI, the persist pattern also does not work in this case because the root component never re-renders in user-scope, or at all for that matter.
