### ISSUE TITLE
Blazor - move DispatchExceptionAsync() documentation to Synchronization context page

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31912]
### Description

Consider moving the section [Handle caught exceptions outside of a Razor component's lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#handle-caught-exceptions-outside-of-a-razor-components-lifecycle) to the _Components / Synchronization context_ page.

The _Synchronization context_ page currently references the `Handle errors` page in its final paragraph:
>To dispatch caught exceptions from the background TimerService to the component, treating the exceptions as though they were normal lifecycle event exceptions, see [Handle caught exceptions outside of a Razor component's lifecycle](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#handle-caught-exceptions-outside-of-a-razor-components-lifecycle) in the Handle errors article.

It seems more logical to document `DispatchExceptionAsync` within the _Synchronization context_ page since it addresses the same scenario. Consequently, the _Handle errors_ page would then link to the _Synchronization context_ page. This change merely adjusts the location and direction of cross-linking.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/synchronization-context?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/synchronization-context.md

### Document ID

84b3cb04-9275-388a-6983-c298c0a5dcfd

### Article author

@guardrex

**Comment by guardrex** [comment]
I agree. This is an artifact of splitting up the *Components* overview.

Let's get the other PR in first, and then I'll move the section.
