### ISSUE TITLE
Blazor - overwriting-parameters - TwoWayExpander - ability to toggle expander from parent component

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31922]
### Description

Started here: https://github.com/dotnet/blazor-samples/pull/214

The `BadExpander.razor` effectively demonstrates the problem: the `Expanded` state can be overwritten by a parent component's re-rendering.

The improved `Expander.razor` avoids resetting the state upon a parent component's re-render. However, this approach only allows for changes to the `Expanded` parameter during the "initial state" (`OnInitialized`):
- The parent component cannot toggle the expander by modifying the `Expanded` parameter value.
- In certain scenarios, an already initialized `Expander` component instance might be reused to render completely different content (for example, when used in a master-detail view and the selected item changes, or when used in a loop without the `@key` directive) and maintains its state without a chance for reset.
Indeed, naming the parameter something like `InitialExpanded` could be more accurate. Many users likely struggle with this sample code as they attempt to toggle the expander externally by changing the `Expander` parameter.

To support both internal and external state changes (enabling expander toggling from outside), using two-way binding for the state might be the only viable solution. This involves incorporating the `ExpandedChanged` parameter and `OnParametersSet` instead of `OnInitialized`. Consequently, the parent component must utilize `@bind-Expanded` to maintain state synchronization.
(An alternative could be to introduce `Expand()` and `Collapse()` methods to the `Expander`, but that's probably beyond the scope of what we're aiming to illustrate on the `overwriting-parameters.md` page.)

I believe we should explain the limitations of the `Expander.razor` with `OnInitialized` approach and offer a `TwoWayExpander.razor` alternative with further explanation.

If you want me to work on this, I can contribute by preparing more polished sample code, including support for older .NET versions, and submit a PR to the docs repository for further refinement.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/overwriting-parameters.md

### Document ID

e687c953-409d-49b9-664a-19ca1f836e4b

### Article author

@guardrex

**Comment by guardrex** [comment]
Great idea, and I agree with your proposal.

**Comment by hakenr** [comment]
Fixed in #31999.
