### ISSUE TITLE
Unclear section of code

### ISSUE THREAD

**Issue by Expecho** [dotnet/AspNetCore.Docs#31933]
### Description

Regarding the section "Load a script from an external JavaScript file (.js) collocated with a component", there is a piece of example code

```csharp
@page "/js-collocation-1"
@inject IJSRuntime JS

<PageTitle>JS Collocation 1</PageTitle>

<h1>JS Collocation Example 1</h1>

<button @onclick="ShowPrompt">Call showPrompt1</button>

@if (!string.IsNullOrEmpty(result))
{
    <p>
        Hello @result!
    </p>
}

@code {
    private string? result;

    public async void ShowPrompt()
    {
        result = await JS.InvokeAsync<string>(
            "showPrompt1", "What's your name?");
        StateHasChanged();
    }
}
```

My issue is with the `@page "/js-collocation-1"` part; where does `js-collocation-1` come from? 

Also, is there a complete example solution somewhere demonstrating this code?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-7.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/index.md

### Document ID

49fa31d8-72a6-01a1-027d-6edeac9e0fc4

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Expecho ...

> My issue is with the @page "/js-collocation-1" part; where does js-collocation-1 come from?

Made up by ***ME*** 🦖😄 ... You can make the names of the component files and the paths anything you wish. 

> Also, is there a complete example solution somewhere demonstrating this code?

Yes ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-8.0#sample-apps
