### ISSUE TITLE
Remove the top-level Server/WebAssembly pivot in the Blazor Call an API article

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#31941]
### Description

The "Call a web API from Blazor" doc currently has content pivoted on Server and WebAssembly, but in Blazor Web Apps these concerns are merged and overlapping. A Blazor Web App might contain both interactive Server and interactive WebAssembly components. Also, all components are prerendered by default, so even WebAssembly-based components need support server-side execution. The current pivot is mostly a remnant of the earlier Server vs WebAssembly hosting model split. Now that everything is merged into a single app model I think we want to remove the pivot and just have separate sections for calling APIs from the client and the server along with some introductory content that frames how there are separate concerns for each. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md

### Document ID

c7e59a08-1c60-32c2-75fd-33cb77ff7a5d

### Article author

@guardrex

**Comment by guardrex** [comment]
Ok ... but note that the article is going to go back to being ***very*** long. Part of the reason to maintain the pivots was to cut down the length of the coverage.

**Comment by danroth27** [comment]
> Ok ... but note that the article is going to go back to being _**very**_ long. Part of the reason to maintain the pivots was to cut down the length of the coverage.

I suspect there are probably opportunities to simplify the content to keep the length reasonable. For example https://github.com/dotnet/AspNetCore.Docs/issues/31940. We could also look at reducing the amount of sample code that isn't directly related to the concept covered by a doc.

**Comment by guardrex** [comment]
> reducing the amount of sample code

I'm concerned about it, but sure thing ... ***you're the boss!*** 😆 I can yank all of the ToDo app examples. The doc will still work without the tutorial aspects. I'll see what I can cut when I drop the pivots.

**Comment by guardrex** [comment]
... and I just had an idea that would make me feel good about cutting all of the example code ... ***add a sample app***. If I set up the ToDo code in a sample app with a functional backend, devs won't lose access to these examples as a valuable resource, especially new-to-Blazor/new-to-programming devs. The article will merely cross-link to the sample app.
