### ISSUE TITLE
[PT-BR] A simple problem with translation with indices

### ISSUE THREAD

**Issue by olucaslrc** [dotnet/AspNetCore.Docs#31942]
### Description

Hello,

I've been seen a simple translation orthographic error from English to Portuguese (Brazil) in documentation about .NET Secrets indices here:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/49102884/b9b5cfdb-b3f7-4e0d-afd2-cb5474c146cd)

In this image, we can see the word "Virtual Studio" to refer to Visual Studio, but the right is "Visual Studio" in Portuguese translation.

### Page URL

https://learn.microsoft.com/pt-br/aspnet/core/security/app-secrets?view=aspnetcore-8.0&tabs=linux

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/app-secrets.md

### Document ID

ba688ac2-e90e-fce5-f60d-40c2553c3efd

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thanks for reporting that.  I've transferred the report to the internal work item https://dev.azure.com/ceapex/CEINTL/_workitems/edit/950462, so I'm closing this issue.
