### ISSUE TITLE
[Blazor] Data binding - Binding with component parameters - section cleanup

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#31969]
### Description

I think the [Binding with component parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#binding-with-component-parameters) needs some cleanup and streamlining.  It seems to compile several iterations of the original _Data Binding_ content, which might not be optimal.

In essence, this section aims to explain two key concepts:
1. How to make a parameter bindable by using a parameter pair:
   ```csharp
    [Parameter] public int Year { get; set; }
    [Parameter] public EventCallback<int> YearChanged { get; set; }
   ```
2. How to bind a field or property to such a bindable parameter, using the syntax `@bind-{PARAMETER}="{FIELD OR PROPERTY}"`

The term chained bind might not be the best fit in this context.

For instance, the paragraph:

> [Component parameters](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#component-parameters) permit binding properties of a parent component with @bind-{PROPERTY} syntax, where the {PROPERTY} placeholder is the property to bind.

could be confusing, especially for beginners (and me). It's not immediately clear if the {PROPERTY} placeholder refers to a property in the parent component or something else.

The original text seems to have some inaccuracies. For example, the commit at
For example see the https://github.com/dotnet/AspNetCore.Docs/commit/0305c3a4b76c44f4156f6b05ef21d5d40be1b3a8#diff-9180209a69e150c947913cc2c57d3a1d4e2cb58fd884fb4c7b48025b2e3cee92L130

>Component parameters permit binding properties and fields of a parent component with `@bind-{PROPERTY OR FIELD}` syntax.

However, this syntax `@bind-{PROPERTY OR FIELD}` is incorrect. The actual syntax is `@bind-{PARAMETER}="{PROPERTY OR FIELD}"`.

The wrong syntax probably came somewhere from https://github.com/dotnet/AspNetCore.Docs/blame/5fcfb38138a45582bd0240786b5a11daf46d9d62/aspnetcore/blazor/components.md#L369

See also
https://github.com/dotnet/AspNetCore.Docs/blame/5fcfb38138a45582bd0240786b5a11daf46d9d62/aspnetcore/blazor/components.md#L434

But it probably somehow survived from the pre-historic era:
https://github.com/dotnet/AspNetCore.Docs/blame/aba1eaf9d0ee8dc7de8c7e562f8de2c3304f7fdb/aspnetcore/blazor/components.md#L164

If you're interested, I could propose a pull request to clean up this section, simplifying it to focus on the two main concepts mentioned above.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @hakenr ... I'll take a look at this next week and get back to you.
