### ISSUE TITLE
Create Min API tutorial: Update all API test instruction - all versions

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#31980]
### Description

Update/Rewrite the VS Code and macOS versions of this tutorial to use the latest recommended API testing tool.

This has to be done for all versions, v3-8 times the VS Code and macOS versions. 

Related to #31967

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-8.0&tabs=visual-studio-mac

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/min-web-api.md

### Document ID

ab408035-6313-a183-9940-32de00e0e977

### Article author

@wadepickett

---
[Associated WorkItem - 226926](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226926)

**Comment by Rick-Anderson** [comment]
> This has to be done for all versions, v3-8 times the VS Code and macOS versions.

Negative, for versions below 6,  replace postman with something like:

* **_Use an HTTP client to test the endpoints._**
*  ***An API Testing Tool***
* ***Use a REST API testing tool to test the endpoints.***     I don't think the PU likes to use REST.

No testing needed on Versions < 6.

> Update/Rewrite the VS Code and macOS versions of this tutorial to use the latest recommended API testing tool.

Negative, see [Visual Studio for Mac is scheduled for retirement on August 31, 2024 in accordance with Microsoft’s](https://learn.microsoft.com/en-us/visualstudio/mac/supported-versions-net?view=vsmac-2022)

Don't spend much time on vsMac, scrub but be terse.

@CamSoper is the expert, he'll chime in if I'm wrong.

**Comment by CamSoper** [comment]
> @CamSoper is the expert

*[citation needed]*

**Comment by wadepickett** [comment]
Thanks @Rick-Anderson.
Cam and I talked about the options and he favored going with OpenAPI (Swagger) and therefore curl, since it uses curl.
You good with that as a general choice for VS Code (Windows/macOS) in these scenarios?

For versions below 6 you suggested the following:
"
- Use an HTTP client to test the endpoints.
- An API Testing Tool
- Use a REST API testing tool to test the endpoints. I don't think the PU likes to use REST.
No testing needed on Versions < 6.
"
By this do you mean that for <6 versions I should:
1. Remove the API testing steps altogether on <6 versions and just provide that quick summary?
or
2. Keep the API testing steps, but generalize in each step so that I am not walking through the actual use of an API testing tool?  

I assume 1. but was not sure and best to clarify.

**Comment by Rick-Anderson** [comment]
> Cam and I talked about the options and he favored going with OpenAPI (Swagger) and therefore curl, since it uses curl.
> You good with that as a general choice for VS Code (Windows/macOS) in these scenarios?

Agreed 

> * By this do you mean that for <6 versions I should:
> 
> 1. Remove the API testing steps altogether on <6 versions and just provide that quick summary?
>    or
> 2. Keep the API testing steps, but generalize in each step so that I am not walking through the actual use of an API testing tool?
> 
> I assume 1. but was not sure and best to clarify.

I don't see a big difference with either. Use your best judgement and @tdykstra  and I will review your PR's.

> For VS Mac:
> It is not clear to me what "scrub but be terse" would look like. Would that look like essentially what you are suggesting for < 6 versions?

_Would that look like essentially what you are suggesting for < 6 versions?_

Correct.

cc @CamSoper,  you da man!

*[**NO** citation needed]*
