### ISSUE TITLE
some files are available by default even outside the webroot

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#31990]
### Description

In my project which has no custom static files configuration, there are files that are available outside of the webroot;

they are located here:
`contentroot\.well-known\acme-challenge\verylongfilename`

I thought maybe `.well-known` is reserved, and I tried copy pasting the folder with a different name 

`contentroot\aaa\acme-challenge\verylongfilename`
`contentroot\bbb\acme-challenge\verylongfilename`

and these new files were also available from the browser, just by writing
`example.com\aaa\acme-challenge\verylongfilename`

UPDATE:
I noticed this probably works because of a `web.config` file inside the `acme-challenge` folder, 
however this file doesn't seem to have any effect when running the app via docker (not IIS)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md

### Document ID

3fec6e08-fc99-7a5c-796f-3f2347cad891

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Can you post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem?

**Comment by omuleanu** [comment]
@Rick-Anderson 
Looks like it is an IIS specific feature,
when running with `IISExpress`, you can have a folder in your ContentRoot with a web.config like this:
```
<?xml version = "1.0" encoding="UTF-8"?>
 <configuration>
    <system.webServer>
        <staticContent>
            <mimeMap fileExtension="." mimeType="text/plain" />
        </staticContent>
        <handlers>
            <clear />
            <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
        </handlers>
     </system.webServer>
 </configuration>
```
and you can access via the url its files, but when running with `http` (kestrel) and docker also uses Kestrel, this web.config has no effect whatsoever
