### ISSUE TITLE
WPF Blazor Hybrid topic doesn't have a step to add bootstrap css

### ISSUE THREAD

**Issue by alvinashcraft** [dotnet/AspNetCore.Docs#31995]
### Description

This walkthrough worked great for me except that my unstyled Blazor page looked like a website from 1998. The step to edit the HTML correctly includes the line to reference the bootstrap file:

```
<link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
```

But there's no instructions to put the `bootstrap.min.css` file in that location or where to get it. I copied one from another Blazor project and put it in `css/bootstrap/` and then everything looked like other Blazor apps.

If I get time, I'll submit a PR to add the missing instructions.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/tutorials/wpf.md

### Document ID

94872f14-0dce-0cf3-0d25-88f23ca8d8ef

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @alvinashcraft ... I'll take look at this Friday (tomorrow) morning.
