### ISSUE TITLE
IdleCircuitHandler should log a meaningful log message

### ISSUE THREAD

**Issue by gerektoolhy** [dotnet/AspNetCore.Docs#32021]
### Description

Example for [Monitor server-side circuit activity
](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#monitor-server-side-circuit-activity) contains below code, which prints a log message, when circuit is detected to be idle:

```
private void CircuitIdle(object? sender, System.Timers.ElapsedEventArgs e)
{
        logger.LogInformation("{Circuit} is idle", nameof(CircuitIdle));
}
```

Above code, when triggered, would print `CircuitIdle is dile`, which is not a very helpful log message. A more meaningful message would include the ID of the circuit that has become idle.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/signalr.md

### Document ID

d17e4c28-ea82-0dd8-295d-19f6ada147ea

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @gerektoolhy ... The content came from Dan Roth's blog post. @MackinnonBuck built these bits, so I'm pinging him for assistance.

**Comment by guardrex** [comment]
This needs a service registration as well ...

```csharp
builder.Services.AddIdleCircuitHandler(options => options.IdleTimeout = TimeSpan.FromSeconds(5));
```

**Comment by guardrex** [comment]
... and missing ...

```csharp
using System.Timers;
using Timer = System.Timers.Timer;
```

You can see how content was rolling out *FAST* 🏃‍♂️ (and untested 😢).

**Comment by guardrex** [comment]
@MackinnonBuck ... I think I have the code to resolve this issue (🦖 ***RexHaqs!***&trade; 🙈). I'll put it on a PR for review.
