### ISSUE TITLE
when using Connection keep-alive SignalR will initially fail to connect

### ISSUE THREAD

**Issue by omuleanu** [dotnet/AspNetCore.Docs#32022]
### Description

This problem is also described here: https://stackoverflow.com/questions/48300288/signalr-in-asp-net-core-behind-nginx

and using  `proxy_set_header Connection $http_connection;`

instead of `proxy_set_header Connection keep-alive;` as described in the documentation page
fixes the problem

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1&tabs=linux-ubuntu#configure-nginx

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/linux-nginx.md

### Document ID

815fe034-c9fc-aee3-a8b5-f2e860b30302

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
> `view=aspnetcore-3.1`
ASP.NET Core 3.1 is out of support.
