### ISSUE TITLE
Parameter binding code

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#32046]
### Description

@jensj reported on https://github.com/dotnet/AspNetCore.Docs/pull/32043 for the INCLUDE file at ...

```
aspnetcore/fundamentals/minimal-apis/includes.parameter-binding8.md
```

> Binding form-posted data to the boolean property "IsCompleted" does not work.
>
> The example given is not working at all.
>
> The form-posted data includes the value "on" is not applicable to the expected value "true" or "false" of the target which is of boolean type.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/parameter-binding.md

### Document ID

a09dcf06-a685-e5b8-0ce4-a4e53c57a9fd

### Article author

@Rick-Anderson

---
[Associated WorkItem - 230275](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230275)

**Comment by Rick-Anderson** [comment]
@tdykstra  feel free to grab,

**Comment by tdykstra** [comment]
@jensj where do you see the value "on"?

**Comment by jensj** [comment]
The section on "Bind to collections and complex types from forms" (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-8.0#bind-to-collections-and-complex-types-from-forms) gives an example where a form representing a "Todo" i posted to the API.

The input element used in the example is

<input type="checkbox" name="isCompleted" />

and posts the value "on" as per the W3 specification. The value "on" can not be parsed to a boolean value by the API and results in the error message:

"BadHttpRequestException: The value 'on' is not valid for 'IsCompleted'."

The example also seems to be lacking "app.UseAntiforgery();" to be working.

**Comment by timdeschryver** [comment]
As mentioned in #31799, I can pick this issue up.
@guardrex If you want I can also go through the code snippets and update the line highlights and spacing if you are not working one this.

**Comment by guardrex** [comment]
@tdykstra is handling this AFAICT.

**Comment by tdykstra** [comment]
I welcome any contribution from @timdeschryver!
