### ISSUE TITLE
CustomizeProblemDetails section's code example is incorrect

### ISSUE THREAD

**Issue by IGx89** [dotnet/AspNetCore.Docs#32047]
### Description

AddProblemDetails needs to be called before builder.Build(), but the code example shows it being called after.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md

### Document ID

38515dfb-91a5-b395-db9d-084bbaf095c8

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@IGx89 Thanks for reporting that, I'm fixing it.
