### ISSUE TITLE
Wrong Mac Command 

### ISSUE THREAD

**Issue by chiarapaskulin** [dotnet/AspNetCore.Docs#32045]
### Description

The tutorial has a wrong Mac command on Get started with ASP.NET Core MVC>Run the app:

Instead of:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/44075372/3ac4b0fd-0d2c-4fc0-85f8-8e5da9221595)
It should be:
<img width="762" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/44075372/bc2585e6-69bb-4099-a1f9-d62ebe1243cf">

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-8.0&tabs=visual-studio-code#run-the-app

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/start-mvc.md

### Document ID

46a7c2e0-4871-491f-02c2-54f7df2237b1

### Article author

@wadepickett

**Comment by wadepickett** [comment]
@chiarapaskulin thanks very much for letting us know.  Will fix.

**Comment by chiarapaskulin** [comment]
There are other problems with the tutorial @wadepickett . From [Add View](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-8.0&tabs=visual-studio-code#add-a-view) onwards. The code doesn't compile/throws error and is way different than the [samples provided in Github](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/tutorials/first-mvc-app/start-mvc/sample). It's really confusing

**Comment by wadepickett** [comment]
@chiarapaskulin, thanks for letting me know what you are experiencing.  I will test through the tutorial series to see what is going on.

Do you mind telling me what the compile error is you are receiving?  I see that from where you filed this issue in the tutorial it looks like you were using VS Code on macOS correct?  

There are three different versions (Visual Studio, Visual Studio Code, Visual Studio for Mac) of this 10 tutorial series.   The series builds the app sample up along with the appropriate database over the course of those tutorials so there are 10 different states of progress building towards the final sample.  Depending on the IDE chosen there are different packages, and it will use either SQL Server Express or SQLite depending on which path is chosen.  So there are a lot of variations.
