### ISSUE TITLE
appsettings.template.json

### ISSUE THREAD

**Issue by jovton** [dotnet/AspNetCore.Docs#32040]
### Description

[Enter feedback here]
By default, when creating an appsettings.json configuration file for our .NET application, it is empty and there are no "sub" application.ENV.json files for the different deployment environments, unless we create them manually also. These we have created, and they each have different values for the settings that differ per environment. Visual Studio groups these "sub" appsettings files underneath the appsettings.json file, visually within the Solution Explorer.

Then, as an experiment, we created another file called appsettings.template.json within the root of the project in Visual Studio 17.9.2. 

Suddently Visual Studio duplicated all the other previously created "sub" appsetting.ENV.json files and grouped them underneath the appsettings.template.json file within the Solution Explorer. It did this automatically without us asking, and this behavior was not expeted and undesirable.

We cannot find any documentation anywhere online about this behavior of Visual Studio when it comes to appsettings.template.json.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/5833599/6cb632a9-0920-4503-83a3-7cc2dd2aafab)

Please, can someone explain this, and document it so people can understand it and why it's happening?

Thanks much!

Johan van Tonder

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md

### Document ID

ba2254a0-ea8e-9b28-e94b-edd0fc58c043

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
For Visual Studio, use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) gesture or [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) gesture within VS, which open internal issues for the VS team.
