### ISSUE TITLE
No store type was specified for decimal property 'Price' on entity type 'Movie'

### ISSUE THREAD

**Issue by AlbertLi255** [dotnet/AspNetCore.Docs#32056]
### Description

**It pops up "No store type was specified for decimal property 'Price' on entity type 'Movie'", after create class "SeedData" according to the document**

Crtl + F5 to run and can't be successed
the prompt is here:

![image](https://github.com/dotnet/AspNetCore.Docs/assets/68913634/e88be1ee-54c6-4890-99ff-7ed13b6a25e6)

Https to run can be successed but still have that warning
the prompt is here:

`warn: Microsoft.EntityFrameworkCore.Model.Validation[30000]
      No store type was specified for the decimal property 'Price' on entity type 'Movie'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values in 'OnModelCreating' using 'HasColumnType', specify precision and scale using 'HasPrecision', or configure a value converter using 'HasConversion'.
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (15ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1
              FROM [Movie] AS [m]) THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END`

![image](https://github.com/dotnet/AspNetCore.Docs/assets/68913634/d255ccd1-b527-4325-be8d-1b2b23a31ad6)

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md

### Document ID

a0b5e15c-d747-8710-95fb-a55c09861a1e

### Article author

@wadepickett

---
[Associated WorkItem - 251073](https://dev.azure.com/msft-skilling/Content/_workitems/edit/251073)

**Comment by wadepickett** [comment]
Looking back there have been a number of community-filed issues  in the past over the confusion associated with this section for what is a high traffic topic

**Comment by wadepickett** [comment]
Closing per Rick's feedback after review.
