### ISSUE TITLE
MainLayout.razor ChangeToDarkTheme function Unable to trigger breakpoint

### ISSUE THREAD

**Issue by roxxxxssss** [dotnet/AspNetCore.Docs#32057]
### Description

Unable to trigger breakpoint -> MainLayout.razor -> ChangeToDarkTheme 

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/components/cascading-values-and-parameters?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/cascading-values-and-parameters.md

### Document ID

5fe884b8-51e1-1b91-57f8-522ff0b7890c

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @roxxxxssss ... I can't reproduce a problem here ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/7ff4c551-cf0c-4473-894d-7f75e7ad40fc)

Open a Visual Studio bug report with **Help** > **Send Feedback** > **Report a Problem** from the Visual Studio menu bar.
