### ISSUE TITLE
add authorization

### ISSUE THREAD

**Issue by Flash0124** [dotnet/AspNetCore.Docs#32065]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-8.0&source=recommendations

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/introduction.md

### Document ID

84241d82-3261-1225-d1f9-a94d38f6155b

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
See [Create an ASP.NET Core web app with user data protected by authorization](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-8.0)

and several others.
