### ISSUE TITLE
OpenApiInfo, TermsOfService have to be uri not string

### ISSUE THREAD

**Issue by DenisMtfl** [dotnet/AspNetCore.Docs#32073]
### Description

OpenApiInfo, **TermsOfService** have to be `Uri` not `String`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-NSwag.md

### Document ID

25f7fb5b-92b0-a45b-57ab-fdceab571884

### Article author

@zuckerthoben

**Comment by wadepickett** [comment]
Thanks, I took a look at the latest spec to see if something changed.  Per the spec it should be a URL as type string.  Looking at the code example on this doc and it uses an example of a valid URL as a string.  

` TermsOfService = "https://example.com/terms"`

I will go ahead and close, but if I am missing something here let me know and I am happy to reopen.

The latest spec (3.1.0):
[3.1.0 ](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md)

**termsOfService**
Type: String
Description: A URL to the Terms of Service for the API. This MUST be in the form of a URL.
