### ISSUE TITLE
SignalR

### ISSUE THREAD

**Issue by Miraga99** [dotnet/AspNetCore.Docs#32071]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-8.0#transports

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/introduction.md

### Document ID

1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1

### Article author

@bradygaster

**Comment by wadepickett** [comment]
@Miraga99, there is no description here.  I will close this issue, but if you were intending to provide some information on your experience with the doc, feel free to create a new one.  We are always grateful to hear any feedback.
