### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by ice6** [dotnet/AspNetCore.Docs#32074]
### Description

若要禁用**整个应用的呈现模式**，请在应用组件层次结构中不是根组件的最高级交互组件上指示呈现模式。

[在此处输入反馈]
若要禁用**整个应用的预渲染模式**，请在应用组件层次结构中不是根组件的最高级交互组件上指示呈现模式。

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#render-modes

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-modes.md

### Document ID

7c9948a3-9886-8097-6014-492a4c21ea4e

### Article author

@guardrex

**Comment by guardrex** [comment]
Translation ...

> To disable rendering mode for an entire app, indicate rendering mode on the highest-level interactive component in the app's component hierarchy that is not the root component.

@ice6 ... I don't understand the feedback. Also, the issue title (翻译错误) didn't translate at all.
