### ISSUE TITLE
[Blazor] Lifecycle - lifecycle1.png update (eg. SetParametersAsync is not "-first render only-")

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#32091]
### Description

@guardrex Where do I find source-files for the diagrams in the page? I would like to propose some adjustments.

For example the `lifecycle1.png`
![image](https://github.com/dotnet/AspNetCore.Docs/assets/12828888/399bba68-06da-404f-847f-b0720fbfa927)
It is not true that `SetParametersAsync` is _- First render only -_.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
They're here ...

https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/blazor/components/lifecycle/_static

... but wait until you discuss proposed changes with Steve and/or Javier before performing work on the images/text. Many issues have come in over the years from devs claiming that the diagrams are oversimplified to the point of being incorrect. When they were reviewed by Steve and/or Javier for those issues, they determined that these were generally correct simplifications of how Blazor processes lifecycle events and that they didn't want them updated. I added text to that effect ...

> This article simplifies component lifecycle event processing in order to clarify complex framework logic. 

... and ...

> The following simplified diagrams illustrate Razor component lifecycle event processing.

Other than your remark ...

> It is not true that `SetParametersAsync` is - *First render only* -.

... list out other changes that you propose to make. When you're ready for them to take a look, I'll email them (i.e., they probably won't see a ping from this repo, and I'll need to email to get their attention on this).

**Comment by guardrex** [comment]
Steve/Javier ... @hakenr also recommends the following change on #32089 ...

```diff
The `Render` lifecycle:

- 1. Avoid further rendering operations on the component:
-    * After the first render.
-    * When [`ShouldRender`](xref:blazor/components/rendering#suppress-ui-refreshing-shouldrender) is `false`.
+ 1. Avoid further rendering operations on the component when both of the following conditions are met:
+    * It is not the first render.
+    * [`ShouldRender`](xref:blazor/components/rendering#suppress-ui-refreshing-shouldrender) returns `false`.
2. Build the render tree diff (difference) and render the component.
3. Await the DOM to update.
4. Call [`OnAfterRender{Async}`](#after-component-render-onafterrenderasync). The synchronous method is called prior to the asychronous method.
```

**Comment by guardrex** [comment]
I sent them an email, so we'll hear back soon 👂on this and the two open PRs.

**Comment by hakenr** [comment]
>> It is not true that SetParametersAsync is - First render only -.
>
> ... list out other changes that you propose to make. When you're ready for them to take a look, I'll email them (i.e., they probably won't see a ping from this repo, and I'll need to email to get their attention on this).

Actually, this is the only factual correction needed.

The only other modification I'm considering involves reorganizing the diagram to make it clearer that the execution flow continues to the "regular Render" (bottom left) after the `OnInitialized[Async]` and `OnParametersSet[Async]` methods, regardless of whether a task is completed or not. Additionally, there's an extra rendering executed after the task is awaited. (This concept is definitely already represented in the diagram; I'm just exploring ways to make it more visually obvious.)

**Comment by SteveSandersonMS** [comment]
> Actually, this is the only factual correction needed.

Agreed.

**Comment by guardrex** [comment]
Thanks @SteveSandersonMS.

@hakenr ... Please proceed with your PR.

@SteveSandersonMS ... I'll email when @hakenr's PR is up.

... and Steve (or @javiercn) ... The two @hakenr PRs still require review ...

* https://github.com/dotnet/AspNetCore.Docs/pull/32089
* https://github.com/dotnet/AspNetCore.Docs/pull/32086

**Comment by hakenr** [comment]
> https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/blazor/components/lifecycle/_static

@guardrex The links lead to exported PNG images, but I'm searching for the original (Visio?) files.
(I’d like to avoid introducing a new visual style to the docs by creating completely new diagrams.)

**Comment by guardrex** [comment]
I see what you mean. Let me check ... I think those were done in PPT. I'll get back to you soon ...........

**Comment by guardrex** [comment]
*Ugh!* ... horrible ... just horrible. As I was looking back for where I may have cross-linked them, I found some of the earlier issues/PRs where these diagrams were created, and I note that ...

* Both Steve and Javier looked right at them and didn't pick up on this error.
* Dan ***DID*** see the problem with `SetParameterAsync` there ... told me to remove it (or revert it back to what it used to say, **Property Injection** IIRC) ... I lost track of his remark while making other changes ... **and I left it in the diagram!** 🙈 ***ORF!***

Well, these diagrams (and the text to a certain extent) have been very buggy 😈 from the start. We've worked on them at least three separate times that I can recall, and I think the PU has seen them more times than that because we had other issues come in saying that they were confusing/wrong/oversimplified/misleading/etc. and engineers said not to sweat it because they're supposed to be simplifications.

Anyway ... let me look a little more for the PPT. Unfortunately, it was four years ago, and I have a new PC here. I'm not sure that I have the originals. Let me search a bit more tho.

**Comment by guardrex** [comment]
# 🎉 

***I found IT!*** ... 😆 ... Not bad after sitting in a buried folder for several years across two PCs.

Let me see if I can post the file here ............

[Blazor lifecycle diagram.pptx](https://github.com/dotnet/AspNetCore.Docs/files/14704232/Blazor.lifecycle.diagram.pptx)

**Comment by hakenr** [comment]
@guardrex TBH, I think the reverted version with "Create instance / Property injection" won't last very long as in net9 there is the new constructor injection and it does not make much sense to mention _Property injection_ in the diagram.

Still better than the version where the `SetParametersAsync` was part of "-first render only-" block.

**Comment by guardrex** [comment]
I suppose it could go to "Property/constructor injection" language at 9.0+. I'll make a note to confirm later with the PU if that makes sense.

**Comment by hakenr** [comment]
Constructor injection is part of the "Create instance". I would rather remove the "injection" from the diagram altogether as it "just works" and it is not a significant lifecycle phase that needs to be explained.

Having discussed all of the above, I would remove all the "Create instance", "* injection" and `SetParametersAsync` blocks from the diagram and leave only the `OnInitialized[Async]` in the "-first render only-" box, because the purpose of this diagram is to explain the very basic flow of `OnInitialized[Async]`, `OnParametersSet[Async]` and the rendering logic.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/12828888/9ade9481-434c-4bc6-8da1-0f1120b3ad3b)
