### ISSUE TITLE
Blazor Configuration Clarify appsettings.json Location

### ISSUE THREAD

**Issue by xxAtrain223** [dotnet/AspNetCore.Docs#32110]
### Description

In the article documentation, it mentions that `wwwroot/appsettings.json` is automatically loaded ([here](https://github.com/dotnet/AspNetCore.Docs/blob/c73d571a0a892aaa2723bfcb118348abfa22024d/aspnetcore/blazor/fundamentals/configuration.md?plain=1#L31-L34) and [here](https://github.com/dotnet/AspNetCore.Docs/blob/c73d571a0a892aaa2723bfcb118348abfa22024d/aspnetcore/blazor/fundamentals/configuration.md?plain=1#L53-L55)). When using the Blazor Web App WebAssembly (and Auto) project template, it creates 2 projects, e.g. `BlazorApp1` and `BlazorApp1.Client`. The server project has a default `wwwroot` directory, but the client project does not have a `wwwroot` by default. I wanted to have some configuration available to a WebAssembly component, so I created a `appsettings.json` in the only `wwwroot` directory I saw, which was in the server project, expecting it to automatically be loaded and available to the WebAssembly component. After 2 hours of troubleshooting, I finally looked at the sample projects and saw that the `wwwroot/appsettings.json` was located in the client project, so I created the `wwwroot` folder and `appsettings.json` file in my client project, and it was automatically loaded.

It would have saved me 2 hours of troubleshooting if the documentation mentioned that only the appsettings files **from the client project's `wwwroot` folder** is automatically loaded.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/configuration.md

### Document ID

8c769648-728d-72ce-ebf6-2a06e5076aa2

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @xxAtrain223 ... I'll add content to the opening of the article to clarify that point. I'm now OOF for the weekend, so I'll get to this early next week.
