### ISSUE TITLE
[Blazor] Lifecycle - AfterRender.razor simplification

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#32117]
### Description

I'm not getting the point what is the `AfterRender.razor` sample trying to demonstrate (what would be specific to Blazor) by using the `message` field, whose value is being changed in synchronous `OnAfterRender` method.

```razor
@page "/after-render"
@inject ILogger<AfterRender> Logger 

<PageTitle>After Render</PageTitle>

<h1>After Render Example</h1>

<p>
    <button @onclick="LogInformation">Log information (and trigger a render)</button>
</p>

<p>Study logged messages in the console.</p>

@code {
    private string message = "Initial assigned message.";

    protected override void OnAfterRender(bool firstRender)
    {
        Logger.LogInformation("OnAfterRender(1): firstRender: " +
            "{FirstRender}, message: {Message}", firstRender, message);

        if (firstRender)
        {
            message = "Executed for the first render.";
        }
        else
        {
            message = "Executed after the first render.";
        }

        Logger.LogInformation("OnAfterRender(2): firstRender: " +
            "{FirstRender}, message: {Message}", firstRender, message);
    }

    private void LogInformation()
    {
        Logger.LogInformation("LogInformation called");
    }
}
```
It is quite obvious that the result will be:
> OnAfterRender(1): firstRender: True, message: Initial assigned message.
> OnAfterRender(2): firstRender: True, message: Executed for the first render.
> LogInformation called
> OnAfterRender(1): firstRender: False, message: Executed for the first render.
> OnAfterRender(2): firstRender: False, message: Executed after the first render.

Why do we need the `message` field and why do we have to show its original value at the beginning of `OnAfterRender` before changing its value under `if (firstRender)` condition? It is simple synchronous logic (not specific to Blazor) which causes the line
> OnAfterRender(1): firstRender: False, message: Executed for the first render.

I think, to explain the `OnAfterRender[Async]` logic, following sample would be much easier to understand:
```razor
@page "/after-render"
@inject ILogger<AfterRender> Logger 

<PageTitle>After Render</PageTitle>

<h1>After Render Example</h1>

<p>
    <button @onclick="HandleClick">Log information (and trigger a render)</button>
</p>

<p>Study logged messages in the console.</p>

@code {
    protected override void OnAfterRender(bool firstRender)
    {
        Logger.LogInformation("OnAfterRender: firstRender = {FirstRender}", firstRender);
    }

    private void HandleClick()
    {
        Logger.LogInformation("HandleClick called");
    }
}
```
The `lifecycle.md` can then contain the output of the sample:
> OnAfterRender: firstRender = True
> HandleClick called
> OnAfterRender: firstRender = False

(I also renamed the `LogInformation` button click handler to `HandleClick` to avoid confusion where there is already a `Logger.LogInformation()` method being used.)

 @guardrex, If you will agree, I will change the `blazor-samples` for all framework versions accordingly.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @hakenr ... Yes, please proceed.
