### ISSUE TITLE
Link for more information of configuration binder source generator is wrong

### ISSUE THREAD

**Issue by StefanOssendorf** [dotnet/AspNetCore.Docs#32114]
### Description

The link for more information about the configuration binder source generator is wrong. It points to the "whats new" of dotnet and not to the actual info under Runtime infos:
https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/runtime#configuration-binding-source-generator

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md

### Document ID

ba2254a0-ea8e-9b28-e94b-edd0fc58c043

### Article author

@Rick-Anderson

---
[Associated WorkItem - 236528](https://dev.azure.com/msft-skilling/Content/_workitems/edit/236528)

**Comment by Rick-Anderson** [comment]
There are 13 links "for more information", I couldn't find one on ***configuration binder source generator***
Please send a link to the line in the MD file containing the link, for example:

-  [`https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md?plain=1#L92`]
- (https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md?plain=1#L92) 
- Text to search, for example **_For more information on storing passwords or other sensitive data:_**
- A screen shot 
<img width="362" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/10f753ac-aae3-4b57-9f69-c6eeb4325118">

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. Any chance you could PR this? At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again.  Edit, then Save.
