### ISSUE TITLE
[Blazor] Lifecycle - Component disposal - Explain why finalizers are not being used

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#32129]
### Description

I propose adding the following subsection to the [Component disposal with `IDisposable` and `IAsyncDisposable`](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#component-disposal-with-idisposable-and-iasyncdisposable) section:

### Unmanaged Resources and Finalizers
Blazor components are not designed to directly use unmanaged resources, such as file handles, and therefore, they don't need to implement an object's finalizer (historically referred to as a destructor). There's no need to implement the full [dispose pattern with finalizers](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern) within a component. However, adopting the simplified dispose pattern to support inheritance is still suggested.

---

I'm still debating whether this addition is necessary. It might only be relevant for those familiar with the comprehensive resource-wrapper pattern (dispose pattern) and wondering why Blazor doesn't use `GC.SuppressFinalize(this)` and finalizers.

@guardrex, have you encountered any questions or issues related to finalizers in Blazor?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
No questions on the subject that I can recall.

We have some sample code that uses `GC.SuppressFinalize(this)`. IIRC, it was either code sent over for publication or my reaction to static analysis that suggested it.

I defer to you working out with the PU (@MackinnonBuck for now) on what should be covered and how. @MackinnonBuck may ping others ... Javier ... Steve ... if needed.

**Comment by guardrex** [comment]
I checked on the calls to `SuppressFinalize` in sample code ... it's only done in C# code, not in components. I think we're good on that point.

**Comment by guardrex** [comment]
I didn't hear back from Mackinnon on this one. Go ahead and add if the paragraph if you wish, and I'll email him to look at your PR.

**Comment by MackinnonBuck** [comment]
I would say adding that detail to the docs probably isn't necessary. If it ever becomes a source of confusion, we could add a note like that, but I don't think customers will write finalizers in components unless they're following samples, and we don't provide samples that do that.

**Comment by guardrex** [comment]
Thx @MackinnonBuck and @hakenr.
