### ISSUE TITLE
[Blazor] include/prerendering.md - Replacing the bad practices with simple demos

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#32124]
### Description

Is this intentional that the included section `includes/prerender.md` is full of bad practices and (repeated) explanations why these are bad? Do we want to use this as documentation of what not to do?

If not. I propose to replace the JS interop samples with some simpler ones which do not implicate the need of the "bad practice warnings".

For example, for `PrerenderInterop1.razor` (which demonstrates the need to wait for `divElement` field to be populated) we could use something like `element.scrollIntoView` (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) instead of manipulating the DOM.

For `PrerenderingInterop2.razor` (which demonstrates gathering return value from JS and need for `StateHasChanged()` to re-render the component with usage of the value gathered) we could use `window.getScreenDetails` (https://developer.mozilla.org/en-US/docs/Web/API/Window/getScreenDetails) to display screen size in the component.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0#component-initialization-oninitializedasync

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

**Comment by guardrex** [comment]
Yes, improvements are welcome for these examples.

Generally, WRT avoiding module use and keeping the `pollutes the client with global functions` warning, we're going to stick with the approach for now. Keep one of these warnings with a cross-link for anything JS interop-based that doesn't use a module.

**Comment by guardrex** [comment]
@hakenr ... Made it back here finally 😅.

I like your idea of using `scrollIntoView`, and I'd like to remove the first example. Two examples of this concept isn't necessary.

How about this .......

```javascript
window.scrollElementIntoView = (element) => {
  element.scrollIntoView();
  return element.getBoundingClientRect().top;
}
```

`PrerenderedInterop.razor`:

```razor
@page "/prerendered-interop"
@using Microsoft.AspNetCore.Components
@using Microsoft.JSInterop
@inject IJSRuntime JS

<PageTitle>Prerendered Interop</PageTitle>

<h1>Prerendered Interop Example</h1>

<div @ref="divElement" style="margin-top:2000px">
    Set value via JS interop call: <strong>@scrollPosition</strong>
</div>

@code {
    private ElementReference divElement;
    private double? scrollPosition;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender && scrollPosition is null)
        {
            scrollPosition = await JS.InvokeAsync<double>(
                "scrollElementIntoView", divElement);

            StateHasChanged();
        }
    }
}
```

I have that just about ready to go on a branch with article updates to the INCLUDE file. I'll hold here for your feedback because I'm going to update all of the sample apps with it.

**Comment by hakenr** [comment]
I like the new demos! ;-)
