### ISSUE TITLE
Identity model customization: Change primary key type" does not cover changes to _LoginPartial.cshtml

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32130]
### Description

This issue has been ported from the Unified Feedback Tool:

Customer feedback verbatim:
""Change primary key type" does not cover changes to _LoginPartial.cshtml.Look at this SO question with ~100k views. Shows how many have stumbled over this... Please fix it.https://stackoverflow.com/q/52568264"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/customize-identity-model.md

### Document ID

8750939b-6ae5-3b9a-6c32-5e84b7fea22c

### Article author

@ajcvickers

**Comment by Rick-Anderson** [comment]
Per SO, My target framework is netcoreapp2.1.

which is out of support.
