### ISSUE TITLE
Need authentication tutorials

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32154]
### Description

Verbatim from feedback control:
>Are there ANY tutorials that cover authentication in Blazor?  I'm bumping into issues that Server rendered vs wasm are completely different, and on top of that there is now Blazor 8 Web App, but I can find zero tutorials explaining how to do authentication in any of them, just unhelpful posts saying "you can't do that bwecause that's not how it works"How DOES it work??

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/index.md

### Document ID

1a2f2ad2-3a29-a5cc-a7aa-1003f7588a8a

### Article author

@guardrex

**Comment by guardrex** [comment]
We'll only maintain a reference article on this subject, and there is a new one to cover BWA+OIDC.
