### ISSUE TITLE
Which controller has the OnPostAsync method shown

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32155]
### Description

Verbatim from the feedback control:
>What controller does OnPostAsync method from the examples belongs to?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/cookie.md

### Document ID

b18a015b-914d-f014-f711-120d208904d9

### Article author

@Rick-Anderson

---
[Associated WorkItem - 239924](https://dev.azure.com/msft-skilling/Content/_workitems/edit/239924)

**Comment by Rick-Anderson** [comment]
See 
<img width="365" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/6dde7ed5-640e-4414-94dc-e6a82c3a7f4d">
