### ISSUE TITLE
MessageHandler not found

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32153]
### Description

Verbatim from feedback control:
> The code here errors out due to the app not being able to find the MessageHandler.  We need better instructions on how to secure a http request on a blazor 8 web app where the webassembly project is calling a controller on the server side part of the app

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/additional-scenarios.md

### Document ID

cc8dfcd6-8d93-5aa3-c381-2b613e88cdbe

### Article author

@guardrex

**Comment by guardrex** [comment]
This is partially covered by the new BWA+OIDC article and partially covered by the recent updates to the *Call web API* article, which includes a new BWA-based web API coverage and sample app. We might be adding more ***secure*** server (web) API coverage, but that's TBD at this time.
