### ISSUE TITLE
Missing the scenario where applications were deployed in containers

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/AspNetCore.Docs#32151]
### Description

... in which case, 1st, the detection of remote ip address is tricky because it's in a weird format, and 2nd, the ip address could change from container restart or recreation.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/ip-safelist?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/ip-safelist.md

### Document ID

51de9bc4-775c-36b6-79d4-71ff635b53a6

### Article author

@damienbod

**Comment by Rick-Anderson** [comment]
Container deployment is beyond the scope of this article.
