### ISSUE TITLE
Provide or link to missing information

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32171]
### Description

Verbatim from feedback control:
>There is a notion about server side blazor: "The built-in AuthenticationStateProvider service obtains authentication state". And not to use httpcontext.But there is no example.After this it continues with more in depth stuff. But I want to know: How to apply CascadingAuthenticationState. And how to use stateprovider. And what packages to include in my project.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md

### Document ID

1247ee64-fbc9-ce29-0710-f6e59380f5ee

### Article author

@guardrex

**Comment by guardrex** [comment]
Not sure what the reader isn't getting. There are three examples in the article of how to use the `AuthenticationStateProvider`. `CascadingAuthenticationState` is also explained with an example. The only package required is described for client-side app scenarios, and it's also covered.
