### ISSUE TITLE
Request for a sample app

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32172]
### Description

Verbatim from the feedback control:
>Please reference a full code demo for this, perhaps on GitHub, using a Blazor project with only server-side rendering.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/static-server-rendering.md

### Document ID

c991c83d-dc0b-1962-2ef2-d7da0a7e56f8

### Article author

@guardrex

**Comment by guardrex** [comment]
Actually, we aren't going to take this on. We can't grant every request for a sample demo. The article covers a fully working, cut-'n-paste experience. That's the best that we can do with the workload, backlog, and staffing at this time.
