### ISSUE TITLE
Wade: React to .NET 9 Preview 3 features

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32181]
Parent issue #32042

---
[Associated WorkItem - 240651](https://dev.azure.com/msft-skilling/Content/_workitems/edit/240651)

**Comment by wadepickett** [comment]
The SignalR and Web API related content was moved into the What's new very early on (February and first week of April), the work completed before I knew what we were doing with this one.  So I took on additional other issues for April instead per discussion and reviwe with Mark.
