### ISSUE TITLE
missing the line "@rendermode 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32184]
### Description

> The final content for .NET 8 is missing the line "@rendermode InteractiveServer"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md

### Document ID

23f2cad2-31f9-d5d1-671c-5613fb812b19

### Article author

@guardrex

**Comment by guardrex** [comment]
This was fixed by an earlier PR.
