### ISSUE TITLE
Update: This information relates to a pre-release product

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32185]
### Description

> "This information relates to a pre-release product that may be substantially modified before it's commercially released."Surely .NET 8 has been released now. Is this disclaimer still valid?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/output.md

### Document ID

cb423d54-ee93-6dfd-87bb-ed79dff8b7b6

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Already fixed in #32177
