### ISSUE TITLE
typos 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32192]
### Description

> Web App -> Blazor -> Component (should be a component)There are typos in this tab

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md

### Document ID

31ad18df-1904-bbdd-cfed-8d0d0267c10e

### Article author

@guardrex

**Comment by guardrex** [comment]
It isn't clear what this feedback refers to. If the feedback is that they want singular ToC entry names, we'll stick with what we have.
