### ISSUE TITLE
Wade: review IIS, ASP.NET Framework, and misc Issues and PR's

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32202]
review IIS, ASP.NET Framework, and misc Issues and PR's

---
[Associated WorkItem - 240648](https://dev.azure.com/msft-skilling/Content/_workitems/edit/240648)

**Comment by wadepickett** [comment]
Reviewed IIS issues/PR's:

[Reviewed and corrected code for IIS doc PR 956](https://github.com/MicrosoftDocs/iis-docs/pull/956/files)
[Reviewed, had to John Heart for issue 1027](https://github.com/MicrosoftDocs/iis-docs/issues/1027)
[Reviewed 1044 and closed after verifying issue was properly moved to API ref repo](https://github.com/MicrosoftDocs/iis-docs/issues/1044)
