### ISSUE TITLE
[Blazor] Templated components - add @key

### ISSUE THREAD

**Issue by hakenr** [dotnet/AspNetCore.Docs#32229]
### Description

I think we should use `@key` in the `TableTemplate.razor` example because we have no control over the `RowTemplate` content, and the `TableTemplate` user can't address this issue on their end. This is because the `RowTemplate` is wrapped in a `<tr>`, so any `@key` added to the `RowTemplate` by the user won't work as intended:
```razor
@typeparam TItem
@using System.Diagnostics.CodeAnalysis

<table class="table">
    <thead>
        <tr>@TableHeader</tr>
    </thead>
    <tbody>
        @foreach (var item in Items)
        {
            if (RowTemplate is not null)
            {
                <tr @key="item">@RowTemplate(item)</tr>
            }
        }
    </tbody>
</table>

@code {
    [Parameter]
    public RenderFragment? TableHeader { get; set; }

    [Parameter]
    public RenderFragment<TItem>? RowTemplate { get; set; }

    [Parameter, AllowNull]
    public IReadOnlyList<TItem> Items { get; set; }
}
```

@guardrex, I know you were somewhat skeptical about the need for `@key` earlier. Therefore, I'm waiting for your approval of the proposed addition before I create the corresponding PR in the `blazor-samples` repo.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/templated-components.md

### Document ID

ae663e33-6a08-0b24-aa19-3fc3c9edccfc

### Article author

@guardrex

**Comment by guardrex** [comment]
Good idea to address this in the article. However, you're correct ... I'm not keen on addressing it in that way. This is introducing another concept that isn't required to demonstrate the basic use of a template, namely content that doesn't require keying.

How about adding a ***new section*** at the end of the article on it? ... and include a fully working, cut-'n-paste (and via the sample app) demonstration (probably the same sort of example that's here ... pets from movies is the theme of these examples, `KeyedTableTemplate.razor`? `Pets5.razor` that uses it?) with keying, briefly explaining the value of keying (as you did in the OP :point_up:) and cross-linking to that subject matter at ...

```
<xref:blazor/components/key>
```

That way, a new Blazor dev won't have an extra concept shot at them early, but the doc will address the value of keying data in the end for this feature.

Feel free to push back on that, but I think you can see where I'm going. I'd like to keep the first examples as simple and clear as possible, and then the article can introduce additional concepts further down the article in additional sections/examples.

**Comment by guardrex** [comment]
Actually, perhaps all that would be required is referencing the earlier template and showing the change in that one line ...

```diff
- <tr>@RowTemplate(item)</tr>
+ <tr @key="item">@RowTemplate(item)</tr>
```

... and then if a `Pet5` could demo something reasonable where the data should be keyed, that would be nice 🤔.

It's late here, and I have to get some 💤 in now 🛌. See if what I'm suggesting makes sense or not and let me know. I'll be back on in the morning.

**Comment by hakenr** [comment]
To be honest, the intention was to "avoid inaccurate sample" to prevent users from reusing it in their applications. The proposed solution - to leave the initial sample as is and to add another sample with an explanation of `@key` - does not align with my intent, as it would still preserve the problematic sample.

If introducing another concept isn't desirable (which I understand), I'd prefer to change the sample so that it doesn't need the `@key` at all. This would require removing the wrapping element from the loop (like `<tr>` in this instance), leading us to consider scenarios that don't require individually templated items to be wrapped. I believe something like Bootstrap's Navbar could serve as an acceptable example:
```razor
<div class="navbar-nav">
  <a class="nav-link active" aria-current="page" href="#">Home</a>
  <a class="nav-link" href="#">Features</a>
  <a class="nav-link" href="#">Pricing</a>
  <a class="nav-link disabled" aria-disabled="true">Disabled</a>
</div>
```
`Navbar.razor`:
```razor
...
<div class="navbar-nav">
  @foreach (var item in Items)
  {
      if (ItemTemplate is not null)
      {
          @ItemTemplate(item)
      }
  }
</div>
...
```
Would you accept this sample in place of `TableTemplate.razor`?

**Comment by guardrex** [comment]
I'm still not clear then on the intent ... aren't you speaking to the case where the dev has no control over the template (e.g., RCL/package they've consumed). If this is their code, they can add the keying if needed. To merely display the templated (static) data, they don't need to key in that scenario AFAIK. Give me more info on the requirement for keying there in the simplest case because the dev controls all of this code in the simplest case and there's nothing to key in the example that actually does anything. Blazor can track these static table display items fine AFAIK.

**Comment by guardrex** [comment]
Just to summarize my morning ramblings 😆 ... ***I'm only on my first cup of*** ☕ ***!*** ...

Yes ... if you want to take it all on ... change the examples to move to the simpler nav bar case with my usual pitch to make the content something interesting.

Add a section at the end with one pets-based template and table, ***keyed***, explaining why keying is important in some cases and cross-linked to the `@key` article.

Place a byline for yourself, as this is an overhaul of how the article explains templated components. I think you're aware that bylines are good street credit for MVPs. However, Dan is aware that you're helping quite a bit, and the PU decides directly on MVP status.

**Comment by hakenr** [comment]
### 👍

Will try to get to this by the end of the week. 🤞

**Comment by hakenr** [comment]
(Sorry, currently stuck on my other tasks. Hope I get to this next week.)
