### ISSUE TITLE
"Cookies vs. bearer tokens" statement

### ISSUE THREAD

**Issue by lamereactor** [dotnet/AspNetCore.Docs#32238]
### Description

In the documentation "Authentication and authorization in ASP.NET Core SignalR," within the section ["Cookies vs. bearer tokens"](https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0#cookies-vs-bearer-tokens), is the statement below specific to SignalR, or does it apply "in general"?

> Cookies are specific to browsers. Sending them from other kinds of clients adds complexity compared to sending bearer tokens. Cookie authentication isn't recommended unless the app only needs to authenticate users from the browser client. Bearer token authentication is the recommended approach when using clients other than the browser client.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/authn-and-authz.md

### Document ID

6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81

### Article author

@bradygaster

**Comment by wadepickett** [comment]
The text context is scoped to the topic of SignalR but could be applied in general.  Cookies are specific to browsers.  Trying to use it for other clients adds unneeded complexity.
