### ISSUE TITLE
Issue: unauthenticated API request results in 200 and HTML

### ISSUE THREAD

**Issue by nwoolls** [dotnet/AspNetCore.Docs#32247]
### Description

Following the OIDC BFF example I ran into what I think is an issue, or at least less than desirable and may prove difficult to handle with client-side code.

While the call info to the Blazor server for weather forecast _does_ require authentication, if the request is not authenticated, instead of returning a 401 and potentially some JSON (e.g. Problem Details), a 200 is returned along with HTML (seems to be the MS login screen).

This can be seen with the example code by editing `MinimalApiJwt.http` to call the Blazor server instead of the API server.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

**Comment by guardrex** [comment]
Good question. Open this for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32247
```

... to the bottom of your opening comment so that I can follow along. Depending on what they say, I'll re-open this for doc work.
