### ISSUE TITLE
Suggestion: document usage w/out Aspire

### ISSUE THREAD

**Issue by nwoolls** [dotnet/AspNetCore.Docs#32245]
### Description

I tried following the BFF sample without using Aspire and was mostly successful, except for the bit using Yarp. The documentation & example seem to rely on the service discovery provided by Aspire. Without Aspire, using an actual URL as the second parameter to `app.MapForwarder()` results in a service discovery error.

I seem to have been able to get things going but it's required a fair amount of code that I'm unsure about, as it is not itself documented.

Specifically I followed:

* https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html
* https://satish1v.medium.com/yarp-based-direct-forwarding-pattern-f3f7d556be4b

However, this is quite a bit more code than your example, and lacks the inline comments you've provided. Just as an example, all of these properties - it's unclear if they are non-default, required, safe, etc.:

```csharp

var httpClient = new HttpMessageInvoker(new SocketsHttpHandler
{
    UseProxy = false,
    AllowAutoRedirect = false,
    AutomaticDecompression = DecompressionMethods.None,
    UseCookies = false,
    EnableMultipleHttp2Connections = true,
    ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current),
    ConnectTimeout = TimeSpan.FromSeconds(15),
});
```

And maybe this isn't necessarily the right path - maybe the `app.MapForwarder()` call can be used with some sort of overload?

It would be wonderful if the documentation touched on this.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

**Comment by guardrex** [comment]
We're only supporting the two approaches and samples that you see ... BFF with Yarp/Aspire and non-BFF without them. We're not supporting any other combination. You will need to work that out on your own. As I mentioned on the samples repo, we recommend taking up discussion on custom configs on public forums. We only work on docs here and don't provide much product support for custom code. I do know that these two versions of the BWA are all that the product unit is going to provide at this time.
