### ISSUE TITLE
Missing @formname on razor syntax page

### ISSUE THREAD

**Issue by chsienki** [dotnet/AspNetCore.Docs#32266]
### Description

The `@formname` directive attribute was added in .NET 8 to allow forms in SSR to be identified across updates. It's mentioned in https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/?view=aspnetcore-8.0 but we don't have it listed on the actual syntax page. 

We should add it with a brief explanation of what it does, and a link to the forms article linked above.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md

### Document ID

a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Thanks @chsienki ... @Rick-Anderson ... I'll look into this on Monday. I'm OOF now for the weekend 🎉🍻🕺💃.
