### ISSUE TITLE
Avoid magic string in Razor Page @page

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#32264]
### Description

The [`@attribute`](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0#attribute) section shows how to avoid magic strings in pages/views. However it does not work for Razor Pages.

It shows this:
```diff
- @page "/counter"
+ @attribute [Route(Constants.CounterRoute)]
```

Which works for Blazor and MVC.

But for Razor Pages it should show this:
```diff
- @page "/counter"
+ @page
+ @attribute [RazorCompiledItemMetadata("RouteTemplate", Constants.CounterRoute)]
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0#attribute

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/razor.md

### Document ID

a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Right, you need to use Razor syntax
