### ISSUE TITLE
Components/App.razor should be Components/Pages/App.razor

### ISSUE THREAD

**Issue by conradagramont** [dotnet/AspNetCore.Docs#32271]
### Description

In the text that says...

_Add an App component to the app, which serves as the root component, which is the first component the app loads.
Components/App.razor:_

This later failed when adding the following in program.cs

`app.MapRazorComponents<App>();`

The file App.razor should be in the "Components/Pages/" folder.  Then it all worked.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/integration.md

### Document ID

d7e39bbc-cd54-92aa-4997-f9dd39dd6ef3

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @conradagramont ... Can you give me the exact error when it resides in the `Components` folder because that's where we'd really like it placed. It's not a routable page, it's a root component.

**Comment by guardrex** [comment]
Kind'a sounds like the article is missing an instruction to add a namespace in the `Program` file for the `Components` folder ...

```csharp
using {APP NAMESPACE}.Components;
```

**Comment by guardrex** [comment]
Yeah ... that's probably it. See how the BWA template has that here ...

https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Program.cs#L12

**Comment by guardrex** [comment]
Looks like it's in the article. Did you skip this step? ...

In the ASP.NET Core project's `Program` file:

* Add a `using` statement to the top of the file for the project's components:

  ```csharp
  using {APP NAMESPACE}.Components;
  ```

  In the preceding line, change the `{APP NAMESPACE}` placeholder to the app's namespace. For example:

  ```csharp
  using BlazorSample.Components;
  ```

**Comment by guardrex** [comment]
@conradagramont ... I'm going to close because I think you missed the step where the namespace is added to the `Program` file. I'm not sure without the error message. If that doesn't resolve the problem, post the error message in a comment here, and I'll re-open this issue to investigate it further.
