### ISSUE TITLE
First Web API: No new build item

### ISSUE THREAD

**Issue by jixianqi** [dotnet/AspNetCore.Docs#32280]
### Description

构建控制器时，工具中并没有“新建构建项”。
但有新建“控制器”
请问到底是新建哪个文件

[在此处输入反馈]

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

---
[Associated WorkItem - 251078](https://dev.azure.com/msft-skilling/Content/_workitems/edit/251078)

**Comment by jixianqi** [comment]
构建控制器
[Visual Studio](https://learn.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio#tabpanel_6_visual-studio)
[Visual Studio Code / Visual Studio for Mac](https://learn.microsoft.com/zh-cn/aspnet/core/tutorials/first-web-api?view=aspnetcore-8.0&tabs=visual-studio#tabpanel_6_visual-studio-code+visual-studio-mac)
右键单击 Controllers 文件夹。

选择“添加”>“**新建构建项**”。

选择“其操作使用实体框架的 API 控制器”，然后选择“添加” 。

在“添加其操作使用实体框架的 API 控制器”对话框中：

在“模型类”中选择“TodoItem (TodoApi.Models)” 。
在“数据上下文类”中选择“TodoContext (TodoAPI.Models)” 。
选择“添加”。
如果基架操作失败，请选择“添加”以第二次尝试使用基架。

**Comment by jixianqi** [comment]
这里说明的新建构建项，但是在程序中并没有该选项

**Comment by jixianqi** [comment]
我使用的是
ASP.NET Core Web API，.net 8.0版本

**Comment by wadepickett** [comment]
Quick machine translation:

"When you build a controller, there is no "New Build" in the tool.
But there is a new "controller"
Which file is being created?"

"Build the controller
Visual Studio
Visual Studio Code / Visual Studio for Mac
Right-click the Controllers folder.

Select Add > New build.

Select API controller whose actions use Entity Framework, and then select Add.

In the Add API Controller whose actions use Entity Framework dialog:

In Model Class, select TodoItem (TodoApi.Models).
In Data Context Class, select TodoContext (TodoAPI.Models).
Select Add.
If the scaffolding operation fails, select Add to make a second attempt to use the scaffolding.

**Comment by wadepickett** [comment]
@tdykstra , I could use your advice on this one.  Per the contributor's guide we should use bold `**` around UI menu items.

However, those are getting translated/localized, and in this case **New Scaffolded Item** in the following markdown is being translated into the equivalent in CN to **New Build** which is understandably causing confusion:
` Select **Add** > **New Scaffolded Item**.`

What do we do for cases like this?

**Comment by tdykstra** [comment]
Use the [no-loc Markdown extension](https://review.learn.microsoft.com/en-us/help/platform/markdown-reference?branch=main#non-localized-strings). You can use it inline, or in file metadata to apply to all instances of a word or phrase.
