### ISSUE TITLE
Concurrency conflicts and token not working or being handled properly.

### ISSUE THREAD

**Issue by Pefam** [dotnet/AspNetCore.Docs#32306]
### Description

I've had to rewrite some of the code because model validation wasn't working as described.
I got that working but now I am having trouble with the Concurrency token. Even when I manually change the concurrency token a conflict does not get flagged. I'll include my model and the page code. I'm leaving the code where I manually set the concurrency token. Not sure why it is not working. I open two tabs and it still does not work, even when I make a change after having opened the page and I don't refresh the page before saving my changes.

Department Model:

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Department
    {
        public int DepartmentID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Budget { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
                       ApplyFormatInEditMode = true)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        public int? InstructorID { get; set; }

        [Timestamp]
        public byte[] ConcurrencyToken { get; set; }

        public Instructor Administrator { get; set; }
        public ICollection<Course> Courses { get; set; }

        public Department()
        {
            Courses = new List<Course>();
        }
    }
}

The edit.cshtml.cs:

using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Pages.Departments
{
    public class EditModel : PageModel
    {
        private readonly ContosoUniversity.Data.SchoolContext _context;
        private readonly ILogger<EditModel> _logger;

        public EditModel(ContosoUniversity.Data.SchoolContext context, ILogger<EditModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        [BindProperty]
        public Department Department { get; set; }
        // Replace ViewData["InstructorID"] 
        public SelectList InstructorNameSL { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            Department = await _context.Departments
                .Include(d => d.Administrator)  // eager loading
                .AsNoTracking()                 // tracking not required
                .FirstOrDefaultAsync(m => m.DepartmentID == id);

            _logger.LogInformation("Entity loaded with ID: {ID}", id);

            if (Department == null)
            {
                return NotFound();
            }

            // Use strongly typed data rather than ViewData.
            InstructorNameSL = new SelectList(_context.Instructors,
                "ID", "FirstMidName");

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            _logger.LogInformation("Starting to handle POST request for department with ID: {ID}", id);
            // Remove unnecessary model state to clean up validation for properties not directly updated through form
            ModelState.Remove("Department.Administrator");

            var departmentToUpdate = await _context.Departments
                .Include(i => i.Administrator)
                .FirstOrDefaultAsync(m => m.DepartmentID == id);

            // Simulate concurrency conflict by changing the token
            departmentToUpdate.ConcurrencyToken = Guid.NewGuid().ToByteArray();

            if (departmentToUpdate == null)
            {
                return HandleDeletedDepartment(id);
            }

            // Manually update properties. You can adjust as needed for your specific scenario.
            departmentToUpdate.Name = Department.Name;
            departmentToUpdate.Budget = Department.Budget;
            departmentToUpdate.StartDate = Department.StartDate;
            departmentToUpdate.InstructorID = Department.InstructorID;

            departmentToUpdate.ConcurrencyToken = Guid.NewGuid().ToByteArray();

            // Manually find and set the Administrator
            if (Department.InstructorID.HasValue)
            {
                departmentToUpdate.Administrator = await _context.Instructors
                    .FindAsync(Department.InstructorID.Value);
            }
            else
            {
                departmentToUpdate.Administrator = null;  // Clear the Administrator if no instructor is selected.
            }
            _logger.LogInformation("Attempting to save changes for department with ID: {ID}", departmentToUpdate.DepartmentID);
            _logger.LogInformation("Validating model state for department with ID: {ID}", id);
            if (!ModelState.IsValid)
            {
                InstructorNameSL = new SelectList(_context.Instructors, "ID", "FullName", departmentToUpdate.InstructorID);
                return Page();
            }

            try
            {
                _logger.LogInformation("Changes are about to be saved for department with ID: {DepartmentID}", departmentToUpdate.DepartmentID);
                await _context.SaveChangesAsync();
                _logger.LogInformation("Changes saved successfully for department with ID: {DepartmentID}", departmentToUpdate.DepartmentID);
                _logger.LogInformation("Successfully updated department with ID: {ID}", departmentToUpdate.DepartmentID);
                return RedirectToPage("./Index");
            }
            catch (DbUpdateConcurrencyException ex)
            {
                _logger.LogError(ex, "Concurrency conflict for department with ID: {ID}", departmentToUpdate.DepartmentID);
                _logger.LogWarning("Concurrency conflict encountered for department with ID: {ID}. Error: {ErrorMessage}", departmentToUpdate.DepartmentID, ex.Message);
                var exceptionEntry = ex.Entries.Single();
                var clientValues = (Department)exceptionEntry.Entity;
                var databaseEntry = await exceptionEntry.GetDatabaseValuesAsync();
                if (databaseEntry == null)
                {
                    _logger.LogError("Error saving changes. The department was deleted by another user.");
                    ModelState.AddModelError(string.Empty, "Unable to save changes. The department was deleted by another user.");
                }
                else
                {
                    var dbValues = (Department)databaseEntry.ToObject();
                    _logger.LogError("Concurrency conflict for department {DepartmentID}. Error: {ErrorMessage}", dbValues.DepartmentID, ex.Message);

                    // Additional logic to handle concurrency conflict

                    if (dbValues.Name != clientValues.Name)
                    {
                        ModelState.AddModelError("Department.Name", $"Current database value: {dbValues.Name}");
                        _logger.LogInformation("Current database value for Name: {Name}", dbValues.Name);
                    }
                    // Repeat for other properties as necessary

                    ModelState.AddModelError(string.Empty, "The record you attempted to edit was modified by another user. If you still want to edit this record, click Save again. Otherwise, click Cancel.");

                    // Update the concurrency token for the next attempt
                    Department.ConcurrencyToken = (byte[])dbValues.ConcurrencyToken;
                }

                // Re-populate the instructor dropdown list
                InstructorNameSL = new SelectList(_context.Instructors, "ID", "FullName", departmentToUpdate.InstructorID);

                return Page();
            }

            // If we reach here, something went wrong; re-show form
            InstructorNameSL = new SelectList(_context.Instructors, "ID", "FullName", departmentToUpdate.InstructorID);
            return Page();
        }

        private IActionResult HandleDeletedDepartment(int id)
        {
            _logger.LogWarning("Department with ID: {ID} not found or deleted.", id);
            // ModelState contains the posted data because of the deletion error
            // and overides the Department instance values when displaying Page().
            ModelState.AddModelError(string.Empty,
                "Unable to save. The department was deleted by another user.");
            InstructorNameSL = new SelectList(_context.Instructors, "ID", "FullName", Department.InstructorID);
            return Page();
        }

        private async Task SetDbErrorMessage(Department dbValues,
                Department clientValues, SchoolContext context)
        {

            if (dbValues.Name != clientValues.Name)
            {
                ModelState.AddModelError("Department.Name",
                    $"Current value: {dbValues.Name}");
            }
            if (dbValues.Budget != clientValues.Budget)
            {
                ModelState.AddModelError("Department.Budget",
                    $"Current value: {dbValues.Budget:c}");
            }
            if (dbValues.StartDate != clientValues.StartDate)
            {
                ModelState.AddModelError("Department.StartDate",
                    $"Current value: {dbValues.StartDate:d}");
            }
            if (dbValues.InstructorID != clientValues.InstructorID)
            {
                Instructor dbInstructor = await _context.Instructors
                   .FindAsync(dbValues.InstructorID);
                ModelState.AddModelError("Department.InstructorID",
                    $"Current value: {dbInstructor?.FullName}");
            }

            ModelState.AddModelError(string.Empty,
                "The record you attempted to edit "
              + "was modified by another user after you. The "
              + "edit operation was canceled and the current values in the database "
              + "have been displayed. If you still want to edit this record, click "
              + "the Save button again.");
        }
    }
}

The edit.cshtml:

@page "{id:int}"
@model ContosoUniversity.Pages.Departments.EditModel
@{
    ViewData["Title"] = "Edit";
}
<h2>Edit</h2>
<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Department.DepartmentID" />
            <input type="hidden" asp-for="Department.ConcurrencyToken" />
            <div class="form-group">
                <label>Version</label>
                @Utility.GetLastChars(Model.Department.ConcurrencyToken)
            </div>
            <div class="form-group">
                <label asp-for="Department.Name" class="control-label"></label>
                <input asp-for="Department.Name" class="form-control" />
                <span asp-validation-for="Department.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department.Budget" class="control-label"></label>
                <input asp-for="Department.Budget" class="form-control" />
                <span asp-validation-for="Department.Budget" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department.StartDate" class="control-label"></label>
                <input asp-for="Department.StartDate" class="form-control" />
                <span asp-validation-for="Department.StartDate" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <label class="control-label">Instructor</label>
                <select asp-for="Department.InstructorID" class="form-control"
                        asp-items="@Model.InstructorNameSL"></select>
                <span asp-validation-for="Department.InstructorID" class="text-danger">
                </span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-page="./Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

The SchoolContext.cs:

using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;

namespace ContosoUniversity.Data
{
    public class SchoolContext : DbContext
    {
        public SchoolContext(DbContextOptions<SchoolContext> options) : base(options)
        {
        }

        public DbSet<Course> Courses { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Instructor> Instructors { get; set; }
        public DbSet<OfficeAssignment> OfficeAssignments { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>().ToTable(nameof(Course))
                .HasMany(c => c.Instructors)
                .WithMany(i => i.Courses);
            modelBuilder.Entity<Student>().ToTable(nameof(Student));
            modelBuilder.Entity<Instructor>().ToTable(nameof(Instructor));
        }
    }
}

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/concurrency.md

### Document ID

e337d2e1-7447-634a-d11a-511247e0f897

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
Can you post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem?

**Comment by Pefam** [comment]
@Rick-Anderson I'll work on it. Thank you.

**Comment by Rick-Anderson** [comment]
- See [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
- Post to a public GitHub repo the [simplest possible sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this problem.
- Post code, not images.
