### ISSUE TITLE
publish a MAUI Blazor project that uses RCL? 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32304]
### Description

> Has anyone tried to publish a MAUI Blazor project that uses RCL? That won't work with Visual Studio (no matter which version of VS or NET)! A few people (including me) have been reporting this problem to the VS team for a year, unfortunately to no effect!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/class-libraries.md

### Document ID

a92c88d3-6ee8-1e69-f4c3-49eb82909746

### Article author

@guardrex

**Comment by guardrex** [comment]
@Rick-Anderson ... This would have to go to the MAUI team for investigation ...

https://github.com/dotnet/maui/issues

Do you want to cross-link this in case I need to re-open it for work? If so, use this in the PU issue OP ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/32304
```

**Comment by Rick-Anderson** [comment]
> Do you want to cross-link this in case I need to re-open it for work? If so, use this in the PU issue OP ...

No, let the MAUI folks do that if necessary.
