### ISSUE TITLE
[WebAPI Tutorial] - Wrong references for PostTodoItem

### ISSUE THREAD

**Issue by sousadiego11** [dotnet/AspNetCore.Docs#32320]
# Issue description

The `PostTodoItem` method in the `aspnetcore/tutorials/first-web-api/samples/7.0/TodoApi/Controllers/TodoItemsController.cs` line 83 and 84 wrong references the `GetTodoItem` method.
The same occurs in the `aspnetcore/tutorials/first-web-api.md` line 364

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [x] .NET Core
* [x] .NET 5.0 or later

**Comment by guardrex** [comment]
Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by guardrex** [comment]
Ah! I see that you submitted a PR. Great! Thanks for that. I'll re-open this and ping the doc's author for review.

**Comment by sousadiego11** [comment]
> Ah! I see that you submitted a PR. Great! Thanks for that. I'll re-open this and ping the doc's author for review.

Thanks!

**Comment by wadepickett** [comment]
Thanks @sousadiego11, I'll take a look at it...

**Comment by sousadiego11** [comment]
> Thanks @sousadiego11, I'll take a look at it...

Ok @wadepickett, i have a PR for this: https://github.com/dotnet/AspNetCore.Docs/pull/32321
this is something i came across while following the tutorial
