### ISSUE TITLE
Enable SwaggerUI only in development environment

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32325]
In sample code, the `app.UseSwaggerUI` call should be inside the `if (env.IsDevelopment)` block.

See [Internal notes](https://github.com/dotnet/aspnetcore-internal/issues/4522#issuecomment-2050624301)

---
[Associated WorkItem - 245602](https://dev.azure.com/msft-skilling/Content/_workitems/edit/245602)

**Comment by Rick-Anderson** [comment]
@Rick-Anderson  PR's

* https://github.com/dotnet/aspnet-api-versioning/pull/1081
*
