### ISSUE TITLE
CreateClient should be wrapped in `using` in your examples.

### ISSUE THREAD

**Issue by bradlis7** [dotnet/AspNetCore.Docs#32338]
### Description

The simple examples call

```
var httpClient = _httpClientFactory.CreateClient();
```

But these need to be wrapped in using as they aren't needed after the function, correct?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-8.0&source=docs#generated-clients

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-requests.md

### Document ID

3d356334-e672-7e8b-1fef-7944ebee99eb

### Article author

@stevejgordon

**Comment by Rick-Anderson** [comment]
Not needed.
