### ISSUE TITLE
Add a Blazor tutorial on using scaffolding to connect to data

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#32359]
For MVC & Razor Pages we have tutorials that show how to scaffolded some CRUD pages based on an EF Core model that connect to data:

- [Tutorial: Create a Razor Pages web app with ASP.NET Core](https://learn.microsoft.com/aspnet/core/tutorials/razor-pages)
- [Get started with ASP.NET Core MVC](https://learn.microsoft.com/aspnet/core/tutorials/first-mvc-app/start-mvc)

Blazor now supports static server-side rendering and has the same CRUD scaffolder support. We should add a similar tutorial for Blazor.

**Comment by Rick-Anderson** [comment]
See #26505 where we're waiting for the EF team to update the code to .NET 9
@danroth27 should we continue to maintain the RP version but retire the MVC version? The MVC version hasn't been updated in several versions.

**Comment by danroth27** [comment]
> should we continue to maintain the RP version but retire the MVC version? The MVC version hasn't been updated in several versions.

I think we need to continue to maintain & publish the MVC & Razor Pages versions. These are still supported frameworks with lots of users. But I don't think we need to add new expansive content to the MVC & Razor Pages versions. Instead, I would focus efforts to on the Blazor content, which is our recommended web UI offering, particularly for new users.

**Comment by guardrex** [comment]
BTW ... I'll pounce on the final Blazor tutorial updates as soon as we hit the Pre7 release ...

* Confirm my guesses on the updates that I made for scaffolded code (or update as needed).
* Walk the topic again and make sure everything works properly. Get the final 😈 out.
* Merge the tutorial ... I'll email when it goes live.
