### ISSUE TITLE
The option for identity scaffold is missing for blazor web app

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32351]
### Description

> The option for identity scaffold is missing for blazor web app

### Page URL

https://learn.microsoft.com/en-au/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md

### Document ID

3e25547b-e2c9-6634-2c38-2a77207f17d4

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
Rick ... I'm going to assign myself for work on this. It's probably not too far off because the language changes from "Blazor Server" to "server-side Blazor apps" to cover both Blazor Server and BWAs. I'll get to this as soon as I can, but it probably will take a few days given the Pre6 release.
