### ISSUE TITLE
Wrong snippet in "TypedResults vs Results"

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#32363]
### Description

I think the first snippet in the "TypedResults vs Results" section doesn't match the snippet, instead it shows the same code as for the `TypedResults` example.

To fix this the first snippet should show the following code using `Results` as return value:

https://github.com/dotnet/AspNetCore.Docs/blob/90ed3d1bf188f066df900e542394b6d07875363d/aspnetcore/tutorials/min-web-api/samples/7.x/todo/Program.cs#L95-L99

If accepted I can update the page.

Screenshot of the snippets:
![image](https://github.com/dotnet/AspNetCore.Docs/assets/28659384/1d71db5e-de1e-47e2-8cc5-4b3215695335)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/responses.md

### Document ID

f0e5da68-cd54-ce74-1ff3-ebd7d9fd09a4

### Article author

@brunolins16

**Comment by tdykstra** [comment]
I agree, please go ahead and fix it.
