### ISSUE TITLE
Audit localized content for UseSwaggerUI best practice changes.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32377]
Per [internal issue](https://github.com/dotnet/aspnetcore-internal/issues/4522):
- [x] Create a list of locals supported (eg, `es, fr`) assigned to @tdykstra 
- [ ] Create a list of topics in this repo featuring `UseSwaggerUI` and divide that list between @Rick-Anderson , @tdykstra , @wadepickett ***List creation divided in 3 assigned to @wadepickett*** 

We may not have to check every topic, but we should check every local for several topics.

---
[Associated WorkItem - 247985](https://dev.azure.com/msft-skilling/Content/_workitems/edit/247985)

**Comment by tdykstra** [comment]
Supported languages:
es-es
tr-tr
zh-tw
ja-jp
pl-pl
ru-ru
fr-fr
zh-cn
pt-br
it-it
ko-kr
de-de
cs-cz
