### ISSUE TITLE
Hybrid cache in What's new doc

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32370]
### Description

See https://github.com/dotnet/AspNetCore.Docs/issues/32361#issuecomment-2070480937

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 247989](https://dev.azure.com/msft-skilling/Content/_workitems/edit/247989)

**Comment by mgravell** [comment]
Not sure if this is the same ticket, but we need to think about primary docs for `HybridCache`, which is fundamentally parallel to `IDistributedCache` and `IMemoryCache`, which puts the logical location as `/aspnet/core/performance/caching/`. Happy to help provide content for this, a lot of which I've already done (see linked comment) - and we also probably want to add a "consider `HybridCache` to the existing `IDistributedCache` and `IMemoryCache` documentation. I don't "docs" a lot, so if someone can advise me on the best way I can start this process, I'd be grateful!
