### ISSUE TITLE
Туннельы replace with Туннель

### ISSUE THREAD

**Issue by sergiomarotco** [dotnet/AspNetCore.Docs#32379]
### Description

На странице https://learn.microsoft.com/ru-ru/aspnet/core/test/dev-tunnels?view=aspnetcore-8.0 встречается текст Туннель**ы**. В русском языке я полагаю должно быть слово Туннел**ь**.

### Page URL

https://learn.microsoft.com/ru-ru/aspnet/core/test/dev-tunnels?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/dev-tunnels.md

### Document ID

cc01239c-b0fa-599f-506f-810572b43b1f

### Article author

@tdykstra

---
[Associated WorkItem - 248171](https://dev.azure.com/msft-skilling/Content/_workitems/edit/248171)

**Comment by tdykstra** [comment]
Every instance of Туннельы on the page correctly translates the original "tunnels".
