### ISSUE TITLE
Double check UseSwaggerUI is only used in dev mode.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32414]
- [x] In VS code load all .cs files in this repo and search for `UseSwaggerUI`. Verify it's called only in dev mode.
- [x] In VS code load all .md files and search for `UseSwaggerUI`. Verify it's called only in dev mode.
- [x] In VS code load all .cs files in https://github.com/dotnet/AspNetCore.Docs.Samples and search for `UseSwaggerUI`. Verify it's called only in dev mode.

**Comment by wadepickett** [comment]
To be clear, am I fixing all I find, or just creating a list for us to split?

**Comment by wadepickett** [comment]
73 hits in 62 files, sorting through them...

**Comment by wadepickett** [comment]
Hits (in progress):

line 66:        tutorials\web-api-help-pages-using-swagger\samples\6.x\SwashbuckleSample\Snippets\Program.cs

**Comment by wadepickett** [comment]
Checking samples repo....

**Comment by wadepickett** [comment]
https://github.com/dotnet/AspNetCore.Docs.Samples is clean, zero hits.  All use dev env for UseSwaggerUI
