### ISSUE TITLE
Delete last unprotected  UseSwaggerUI call in archived repo

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32459]
Per https://github.com/dotnet/aspnetcore-internal/issues/4522

https://github.com/dotnet/website-api/tree/master This repository has been archived by the owner on Jul 23, 2020. It is now read-only.

https://github.com/dotnet/website-api/blob/master/src/Website.Api/Startup.cs is problematic.

**Comment by Rick-Anderson** [comment]
@richlander who can delete https://github.com/dotnet/website-api/blob/master/src/Website.Api/Startup.cs  ?

**Comment by richlander** [comment]
I suggest one of two things:

- Call it a day on a repo that is archived.
- Delete the repo.

**Comment by Rick-Anderson** [comment]
> * Delete the repo.

Can you do that? I don't have permission.

**Comment by richlander** [comment]
I changed repo visibility for now.

**Comment by Rick-Anderson** [comment]
Thanks!
