### ISSUE TITLE
cannot enable "Support pages and views" for WebAssembly client projects

### ISSUE THREAD

**Issue by ghhv** [dotnet/AspNetCore.Docs#32453]
### Description

[Enter feedback here]
You should highlight that you cannot enable "Support pages and views" for WebAssembly client projects. If you do, you get the painful error, "no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'"
I highlighted the changes made and a fix here - https://github.com/dotnet/aspnetcore/issues/53671#issuecomment-2081461812

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/class-libraries.md

### Document ID

a92c88d3-6ee8-1e69-f4c3-49eb82909746

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @ghhv! ... I'll get a PR up shortly to address this.
