### ISSUE TITLE
Timeout is not configured in the Options

### ISSUE THREAD

**Issue by MatthewSteeples** [dotnet/AspNetCore.Docs#32468]
### Description

The documentation states `For example, the timeout setting can be configured on the Advanced tab`. The value in the Advanced tab does not affect the timeout used. I'm not sure whether the documentation is wrong or the product is wrong, but the timeout is fixed at 100 seconds currently.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

---
[Associated WorkItem - 250823](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250823)

**Comment by tdykstra** [comment]
This is a product issue rather than a documentation error. To report a problem with Visual Studio, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) feature.
