### ISSUE TITLE
Executive overview for Version-by-File support

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#32487]
@Rick-Anderson @tdykstra @wadepickett ... Per internal discussion with PU management, I'll be preparing an executive overview to try and get support for implementing *Version-by-File* support. IIRC, there were two problems that I faced with my implementation that remained unsupported, thus forcing me to abandon it ...

* Localization was either broken or heavily delayed.
* The sidebar ToC wouldn't highlight the correct article that the dev was reading for non-current-release articles.

Otherwise, everything seemed to work great. Cross-links and navigation worked great, and there was no duplicate heading problem with copied content because each copy of the content was in a separate file. Docs would've been easy to update and maintain because all docs for a given release were in one folder named for its version (i.e., `3.1`, `5.0`, `6.0`, etc.). You could simply set a search filter on a given release folder to isolate content for find-'n-replace updates (e.g., sample cross-links). It was really nice, and I could see how it would save a lot of time ... thus 💰💰💰💰.

I won't reach this for a few weeks. I need to get a Blazor tutorial written and work up the Pre4 Blazor coverage first. The purpose of this issue is primarily to track it as a work item. If you have input on this, you can email me. I'll email the draft to you for comments when it's ready.

**Comment by Rick-Anderson** [comment]
> * Localization was either broken or heavily delayed.

Loc is gone, there is no more loc.

> I won't reach this for a few weeks.

Let me know a couple days before you start and I'll arrange for support.

**Comment by guardrex** [comment]
@Rick-Anderson ...

> Loc is gone, there is no more loc.

What does that mean? Articles are still localized, so I don't follow what you're saying.

**Comment by guardrex** [comment]
Placing a few links here for my tracking ...

* https://github.com/dotnet/AspNetCore.Docs/commits/f39e314537c492bdb88ec53ad2942c4baa2af264/aspnetcore
* https://github.com/dotnet/AspNetCore.Docs/pull/22776
* https://github.com/dotnet/AspNetCore.Docs/pull/22784
* https://github.com/dotnet/AspNetCore.Docs/issues/22975

**Comment by guardrex** [comment]
Email sent ... closing as completed 🎉.

**Comment by Rick-Anderson** [comment]
> What does that mean? Articles are still localized, so I don't follow what you're saying.

They are not. I found a bunch of loc repo's that weren't deleted and had them deleted. Our content is no longer localized. Open an issue if you find localized content and I'll get the repo deleted as the loc content is not updated.

**Comment by guardrex** [comment]
Not according to dev tools. Look at the server response for a page request and see that the content is coming down translated.

Besides, it's not the actual translation that was the problem for Version-by-File. The problem was that the links to the articles were malformed. IIRC, the version segment wasn't being removed. It looked like to me that the feature wasn't implemented for Version-by-File (or "Group Topic Versioning" if that's what they call it).

**Comment by guardrex** [comment]
Note that when I say "localized," I mean translated. I probably should've used the word "translated" in the first place to avoid confusion. Yes, browsers handle localization of numbers, currencies, etc. I was referring to MS's loc/culture routing system ... that's what wasn't working for the feature.
