### ISSUE TITLE
Method in tutorial no longer exists

### ISSUE THREAD

**Issue by ta1H3n** [dotnet/AspNetCore.Docs#32508]
### Description

Documentation says to use `app.MapHub<ChatHub>("/chatHub");`, which no longer exists. It is now:
```cs
app.UseEndpoints(endpoints =>
{
    endpoints.MapHub<ChatHub>("/chatHub");
});
```

Related issue:
https://github.com/dotnet/AspNetCore.Docs/issues/28494

Affects these tutorials:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-8.0
https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-8.0

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr.md

### Document ID

5e3fbe1d-c97f-9940-4f0c-067d4b2112b1

### Article author

@bradygaster

**Comment by guardrex** [comment]
@ta1H3n ... Read Brennan's remarks. All of the tutorials that you mention use `WebApplication`.

> > app.MapHub<yourhub> doesn't work like that anymore!

> Yes it does, if you use `WebApplication` which the sample does.
