### ISSUE TITLE
ASP.NET Core metrics documentation says to install obsolete package Microsoft.Extensions.Testing.Telemetry

### ISSUE THREAD

**Issue by jackhorton** [dotnet/AspNetCore.Docs#32552]
### Description

MetricCollector<T> seems to actually live in Microsoft.Extensions.Diagnostics.Testing, not Microsoft.Extensions.Testing.Telemetry.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/log-mon/metrics/metrics.md

### Document ID

fc4aa26a-a037-2bd9-f313-e3073d6b8232

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@jackhorton thanks for notifying us of this error.
