### ISSUE TITLE
Interface tab list broken

### ISSUE THREAD

**Issue by themarkx11** [dotnet/AspNetCore.Docs#32558]
### Description

Under the h2 "Worker Service template" the tab list showing the options [Visual Studio], [Visual Studio for Mac] and [.NET Core CLI] seems to break when selecting [Visual Studio for Mac]. When it is selected, switching back to [Visual Studio] doesn't seem to work, and selecting [.NET Core CLI] results in the first and second option to be highlighted.
Tested in Edge and Chrome.
![image](https://github.com/dotnet/AspNetCore.Docs/assets/56363952/76085137-38f4-4498-8451-e18658b582f8)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md

### Document ID

b2dece1f-15b8-03af-6d52-7cc070432b4b

### Article author

@tdykstra

---
[Associated WorkItem - 253575](https://dev.azure.com/msft-skilling/Content/_workitems/edit/253575)

**Comment by tdykstra** [comment]
@themarkx11 Thanks for reporting that!
