### ISSUE TITLE
Swagger Issues

### ISSUE THREAD

**Issue by RaulSamada** [dotnet/AspNetCore.Docs#32574]
### Description

After install Swashbuckle.AspNetCore and even if I remove the steps for use the Swagger UI in my backend, my asp.net 8 project doesn´t run. I got: 
_System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Swagger.ISwaggerProvider Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Swashbuckle.AspNetCore.Swagger.IAsyncSwaggerProvider Lifetime: Transient ImplementationType: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.ApiDescriptions.IDocumentProvider Lifetime: Singleton ImplementationType: Microsoft.Extensions.ApiDescriptions.DocumentProvider': No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.)'_
InvalidOperationException: No constructor for type 'Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator' can be instantiated using services from the service container and default values.

### Page URL

https://learn.microsoft.com/es-es/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/getting-started-with-swashbuckle.md

### Document ID

59222460-a971-e76e-4fe9-23d4d7d768ee

### Article author

@zuckerthoben

**Comment by guardrex** [comment]
Hello @RaulSamada ... See the note at the start of the article. Swashbuckle isn't supported in .NET 8 or later. For an alternative, see [ASP.NET Core web API documentation with Swagger / OpenAPI](https://learn.microsoft.com/es-es/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-8.0).

**Comment by guardrex** [comment]
However, @RaulSamada, see ...

https://github.com/dotnet/AspNetCore.Docs/pull/32576

... because it looks like support is returning. If you make the changes shown by the PR, hopefully the errors will clear.

**Comment by martincostello** [comment]
If they don't, please log an issue [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/new/choose) and we can fix it 😃
