### ISSUE TITLE
the TryHandleException method should change to the TryHandleAsync method

### ISSUE THREAD

**Issue by doggy8088** [dotnet/AspNetCore.Docs#32578]
### Description

In this doc, the `TryHandleException` method should change to the `TryHandleAsync` method.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0&WT.mc_id=DT-MVP-4015686

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md

### Document ID

38515dfb-91a5-b395-db9d-084bbaf095c8

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
Related #32594

**Comment by tdykstra** [comment]
@doggy8088 Thanks for reporting this!
