### ISSUE TITLE
Résaux

### ISSUE THREAD

**Issue by OlivierOutlook** [dotnet/AspNetCore.Docs#32589]
### Description

[Tapez vos commentaires ici]
![Screenshot_20240121_131009_YouTube](https://github.com/dotnet/AspNetCore.Docs/assets/169863148/d12f956b-3135-4e14-beae-18040f2c1e11)
Litep

### Page URL

https://learn.microsoft.com/fr-fr/aspnet/core/client-side/libman/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/libman/index.md

### Document ID

08df0875-304c-bca1-3b83-6e636f910bc0

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Images do use no good.
