### ISSUE TITLE
Redundant call to builder.Services.AddOptions()

### ISSUE THREAD

**Issue by BassFaceIV** [dotnet/AspNetCore.Docs#32597]
### Description

The section [Expose the authentication state as a cascading parameter](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#expose-the-authentication-state-as-a-cascading-parameter) mentions client-side apps should include a call to builder.Services.AddOptions() in the Program file. This seems unnecessary since [builder.Services.AddAuthorizationCore() already includes a call to AddOptions()](https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs).

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/index.md

### Document ID

1247ee64-fbc9-ce29-0710-f6e59380f5ee

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @BassFaceIV ... I'll take a look early next week, hopefully on Monday.

**Comment by guardrex** [comment]
Hello @BassFaceIV ... Thanks for the report. It seems to be a point-in-time situation ...

* [3.1](https://github.com/dotnet/aspnetcore/blob/v3.1.32/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs#L21-L35): ❌ Not included by default
* [5.0 or later](https://github.com/dotnet/aspnetcore/blob/v5.0.17/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs#L30): ✔️ Included by default

I'll version it out for 5.0 or later.
