### ISSUE TITLE
link to #use-setsize-size-and-sizelimit-to-limit-cache-size broken

### ISSUE THREAD

**Issue by damiensawyer** [dotnet/AspNetCore.Docs#32606]
### Description

References to link to use-setsize-size-and-sizelimit-to-limit-cache-size don't appear to go anywhere. I assume a label is missing. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1#use-setsize-size-and-sizelimit-to-limit-cache-size

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/memory.md

### Document ID

640b4f36-5886-7b69-1c95-cfc8574a02fd

### Article author

@tdykstra

**Comment by tdykstra** [comment]
You have ASP.NET Core in .NET 3.1 selected. 3.1 is out of support, and due to a limitation of our publishing system, links to internal anchors don't work for old .NET versions.
