### ISSUE TITLE
The simplified Chinese translation is incorrect

### ISSUE THREAD

**Issue by wu1234a** [dotnet/AspNetCore.Docs#32602]
### Description

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0#enhanced-navigation-and-form-handling

When calling NavigateTo：
If forceLoad is false, which is the default  

The correct Chinese translation is : 如果 forceLoad 为默认值 false:

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/routing.md

### Document ID

b6cb2574-6326-a40d-0b6c-d1661328e828

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for the report. I'll ping @khoiph1 (Khoi Pham) on this and close, as it will be handled internally. I don't think he sees these GitHub pings, so I'll email him offline now about this ...... *stand-by* ...... ***Done!*** 👍 I sent him an email to inform him of your issue.
