### ISSUE TITLE
Make a clear description of file location for JSHost.ImportAsync

### ISSUE THREAD

**Issue by maraf** [dotnet/AspNetCore.Docs#32618]
### Description

The documentation currently states

> The CallJavaScript1 module is imported asynchronously from the [collocated JS file](https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?view=aspnetcore-8.0#load-a-script-from-an-external-javascript-file-js-collocated-with-a-component) with [JSHost.ImportAsync](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.javascript.jshost.importasync).

It's not entirely true based on other file collocation that works in RCL. `JSHost.ImportAsync` always loads files relative to `wwwroot/_framework` directory. Examples for paths for `JSHost.ImportAsync`:
- If a file to load is `wwwroot/MyModule.js`, then relative path can be `../MyModule.js`
- If a file to load is in RCL `MyLibrary` in `wwwroot/MyLibraryModule.js`, then relative path can be `../_content/MyLibrary/MyLibraryModule.js` (this is true for both cases when the import is done from RLC itself or from the Blazor app)
Note: absolute paths could be used as well, but then it could cause problems when the site is not hosted in the root of the domain.

Based on feedback from https://github.com/dotnet/aspnetcore/issues/55817

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/import-export-interop.md

### Document ID

8aab92a0-c05f-ef01-fb74-a0bf525aae69

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @maraf ... I'll get this fixed up as soon as possible, but it will take a couple of weeks to reach it due to a high priority tutorial that I'm working on.
