### ISSUE TITLE
Clarification required to understand what runtime environnements are currently supported

### ISSUE THREAD

**Issue by ohault** [dotnet/AspNetCore.Docs#32638]
### Description

The main question is the following
Does it compatible to run under Azure App services or Azure ?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/aot/native-aot-tutorial?view=aspnetcore-8.0&tabs=netcore-cli

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/aot/native-aot-tutorial.md

### Document ID

68422c34-cfab-aefa-dc58-9a33f79e140d

### Article author

@mitchdenny

**Comment by Rick-Anderson** [comment]
Using a released version of .NET, you should be able to publish to Azure App services.

**Comment by ohault** [comment]
@Rick-Anderson, I have just check this page, but I cannot see what's has been done to provide the required clarification ?

**Comment by Rick-Anderson** [comment]
It's supported on Azure.

**Comment by ohault** [comment]
> It's supported on Azure.

It is currently absolutely not obvious to understand how it is supported ?
e.g. this will not be hosted an Azure App Services I guess, but in others Azure services or K8S, or .....

A roadmap about ASP.NET core 9 about new Native AOT feature is also important because AFAIK, there are currently big limitation as the lack of support of MVC, EF.core, ....
