### ISSUE TITLE
[UUF Port] Version 7 instruction loads version 8 packages

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32659]
### Description

United User Feedback Port:
Customer Feedback:
"The cli commands are picking up version 8 packages and fail. I have project with dotnet 7"

Action: The CLI example 'Install-Package` command would specify the last matching version (unless for some reason we are explicitly recommending a newer one).

Latest version for .NET 7:
`Install-Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore -Version 7.0.19`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md

### Document ID

3e25547b-e2c9-6634-2c38-2a77207f17d4

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
This is basic 'Install-Package`
