### ISSUE TITLE
[UUF Port]: Blazor: Secure Server Side: Clarify code examples

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32667]
### Description

United User Feedback Port:
Customer Feedback:
"
The code examples on this page are confusing. For one, there is already an existing Core class called AuthenticationService. Also, the CustomAuthStateProvider constructor example has a new authenticationState created, and then right after it, calls NotifyAuthenticationStateChanged with ANOTHER new AuthenticatonState(user) call. Confusing.
"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/index.md

### Document ID

8da62490-e36f-8f38-8f06-d5d6bceaafde

### Article author

@guardrex

**Comment by guardrex** [comment]
> there is already an existing Core class called AuthenticationService

I don't think the product unit cares if it's renamed, so ... 🤔 ... perhaps `BlazorAuthenticationService` would be better.

> the CustomAuthStateProvider constructor example has a new authenticationState created, and then right after it, calls NotifyAuthenticationStateChanged with ANOTHER new AuthenticatonState(user) call

It doesn't do that "right after." Per the guidance, the text explains (emphasis added) ...

> ***When there's a change in user,*** a new authentication state is created with the new user (`new AuthenticationState(newUser)`) for calls to `GetAuthenticationStateAsync`

... i.e., `UserChanged` is an `Action<ClaimsPrincipal>` delegate. It executes when a new user is assigned.

I think I can add a few more words to the explanation to improve it, but it's fairly close in its present form to covering what's happening.

Cross-reference: https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio#notification-about-authentication-state-changes
