### ISSUE TITLE
[UUF Port]:Proxy Load Balancer: Need more info on Reverse Proxy

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32662]
### Description

United User Feedback Port:
Customer Feedback:
"
Generally wish to give thumbs up, but:1. Would be great if the article is explicit where it refers to the Reverse Proxy and where to the endpoint application.2. Looks like the code refers to the endpoint app, so I need to do more searching to find out what do I need to do to get YARP to forward the protocol, as after disposing TLS, my app redirects to http as opposed to https.So the article is helpful, but needs a bit more work to become a really good one.Thanks!
"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/proxy-load-balancer.md

### Document ID

c48abb08-bea3-dcff-c067-2edf5dc9b3a6

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Topic is complex and we don't have the resources to expand it.
