### ISSUE TITLE
[UUF Port]: EF-MVC tutorial intro: Needs Update - wrong info

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32664]
### Description

United User Feedback Port:
Customer Feedback:
"
Lots of errors and wrong information. For example Program.cs do not have Main method when creating project. CreateHostBuilder do not work. Etc.
"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md

### Document ID

8daf79df-eac4-358b-e6f0-6def45bd54da

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
Dup of #26505
cc @tdykstra
