### ISSUE TITLE
[UUF Port] dotnet-interop: May need an update for .NET 8

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32660]
### Description

Unified User Feedback Port:
Customer feedback:
"This content does not appear to be correct for .NET 8. The project file format is different from what is documented here when using .NET 8 experimental template. There also no longer seems to be an AppBundle.The new template uses Microsoft.NET.Sdk.WebAssembly vs Microsoft.NET.Sdk"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/dotnet-interop.md

### Document ID

efff6954-a035-d1da-5975-af04ff7c05ed

### Article author

@pavelsavara

**Comment by Rick-Anderson** [comment]
@wadepickett  did you verify the assertions above? Can you also remove the 
<img width="68" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/cff31c56-d760-4e3d-80fe-ca73be5e3922">
label after creating issues?

**Comment by guardrex** [comment]
>  after creating issues?

This one I should deal with via `docfx.json` ... the file needs a path entry to this doc that adds the Blazor `ms.subservice`. At that point, this article will get the correct labels, project, and assignment.

I opened https://github.com/dotnet/AspNetCore.Docs/issues/32710 to take care of that.

As for this article, @pavelsavara and I can look into the comments to see what's what. I see one thing for sure, the SDK line isn't versioned. However, I've been hardening those lines lately by just cross-linking the landing page and saying 'get the latest SDK.'

@pavelsavara ... I'll be free ....... ***free-er-ish*** 😄 .... in about a week. I can take a look then.

**Comment by pavelsavara** [comment]
cc @maraf

**Comment by guardrex** [comment]
@maraf ... Do you want to submit a PR here, or do you want to list the changes for me to make?

I'll be free in about a week. I must get this ***GIANT*** 🐘 Blazor tutorial wrapped up first, which will take me into about the middle of next week. Then, I should have some time ... to work on this and the other issue that we discussed a week or two ago. I'll play catch-up as soon as I can.

**Comment by guardrex** [comment]
> did not realized we have it covered in docs

I felt that it would be best to split the Blazor coverage from the non-Blazor coverage on this because readers are probably split into two groups of developers, each probably not wanting to be concerned looking at text and examples of the other. There's this article here for the non-Blazor coverage, and there's the Blazor article on this subject at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-8.0

Dan and Artak approved the split.

This one ... the one outside of the Blazor node ... isn't generating the correct Blazor labeling and ping to me due to our DocFX config. I opened that issue to fix that shortly ... *ASAP* after I wrap up this big tutorial that I'm writing.

**Comment by guardrex** [comment]
@maraf ... I started working on this, but I didn't get far before hitting a brick wall 💥...

```dotnetcli
dotnet workload install wasm-experimental
```

... yields ...

> No workload update found.
>
> Successfully installed workload(s) wasm-experimental android aspire ios maccatalyst maui-windows.

```dotnetcli
dotnet new wasmbrowser
```

... yields ...

> No templates or subcommands found matching: 'wasmbrowser'.

... which is correct. `wasmbrowser` and `wasmconsole` aren't installed.

**Comment by maraf** [comment]
That is weird. Nothing has changed around these. What does `dotnet --info` print for you? Does it contain `wasm-tools` and `wasm-exprimental` workloads?

**Comment by guardrex** [comment]
I can try a system restart if you think that would help, but I need to wrap up some work that I'm doing first.

**Comment by guardrex** [comment]
Performed a system restart. Ran the commands again. No 🎲🎲 ... I'm not getting the workload to install, and I don't have the templates. Therefore, I can't see exactly what to update beyond the OP comments ... and even those are a bit vague (e.g., "project file format is different").

**Comment by guardrex** [comment]
I'll go ahead and guess what the changes are and put that up in a PR for you to take a look at.
