### ISSUE TITLE
[UUF Port]: Blazor Components: Clarification on base class

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32665]
[EDIT by guardrex to code-fence at-inherits because that's a GH handle for a GH user.]

### Description

United User Feedback Port;
Customer Feedback:
"
In the section with the heading "Specify a base class", the example is a bit strange.  The `@inherits` directive in BlazorRocks1.razor would make sense if some C# class was defined that derives from BlazorRocksBase1, but only markup is present in BlazorRocks1.razor.    

Furthermore, there is no indication in BlazorRocksBase1.cs that the class is a partial class, i.e. the "partial" keyword is absent.  Is this correct?
"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/index.md

### Document ID

31ad18df-1904-bbdd-cfed-8d0d0267c10e

### Article author

@guardrex

**Comment by guardrex** [comment]
All components are C# classes. It's covered in a few spots, but this is probably the most explicit ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#component-name-class-name-and-namespace

> no indication in BlazorRocksBase1.cs that the class is a partial class

It's not a partial class. It's explained by the section ...

> Unlike using partial classes, which only split markup from C# logic, using a base class allows you to inherit C# code for use across a group of components that share the base class's properties and methods.
