### ISSUE TITLE
[UUF Port]: Blazor data-binding: More detail on steps needed

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#32663]
### Description

United User Feedback Port:
Customer Feedback:
"
1. after first creating a Bind.razor, what is expected to happen? where should I put it? The page localhost:num/bind doesn't work
2. after then creating BindTheory.razor, what is expected to happen? where should I put it? Now the page localhost:num/bind starts to work, why? but when I enter numbers and letters in the input fields, nothing happens, why? The fields aren't updated in localhost:num/bind-theory either.
3. same issues for BindEvent.razor, why doesn't it work, what is missing?
4. @inject ISearchService SearchService where does that code go, I cannot figure it out, and now I'm lost and cannot come further on.
"

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

**Comment by wadepickett** [comment]
> BTW ... We don't have a way to reach this dev?

If you mean do we have a way to reach the customer/community member who provided the feedback, we don't unfortunately.  These UUF (Unified User Feedback) issues are all anonymous, unlike the doc issues created right in the repo by the "Open a documentation issue" feature available at the bottom of each doc page.

If you see "UUF" ported issues like this, it is anonymous, there is no more information available than the quote of the feedback inserted in the issue.  You may decide after reviewing, knowing your content, that it is a lower priority than other work, or that it is a non-issue and should be closed, etc.  Handle it accordingly, how you feel it should be handled.  I am trying to weed out any UUF issues that are non-issues, or are already fixed before, or there is obviously not enough information to work with before I port them here, but the owner of the docs are going to know best how to handle it from there.

**Comment by guardrex** [comment]
Thanks ... I thought that was the case. it's too bad that I can't assist this dev directly.

This is a good issue. I know why the dev had this experience. Dan and I have tried to head this off with the content thus far, but I'll analyze the problem further in two weeks and see what else can be done.
