### ISSUE TITLE
Suggestion on cross-link

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#32676]
### Description

Wade, you might consider a different link for ...

```
/dotnet/framework/data/adonet/ef/language-reference/query-execution
```

... because that's an ADO.NET source. There's similar info in the LINQ docs at ...

https://learn.microsoft.com/en-us/dotnet/csharp/linq/get-started/introduction-to-linq-queries#deferred

I just noticed it in passing while working on the Blazor tutorial. If you prefer the ADO.NET link, no worries ... it's just a passing thought. Please close this in that case.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/search.md

### Document ID

b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d

### Article author

@wadepickett

---
[Associated WorkItem - 261113](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261113)

**Comment by wadepickett** [comment]
Thanks @guardrex, will fix!
