### ISSUE TITLE
ReDoc link goes to the wrong place

### ISSUE THREAD

**Issue by danzel** [dotnet/AspNetCore.Docs#32687]
### Description

The ReDoc link goes to some AI writing tool, not to the actual redoc page.
Recommend it goes to https://github.com/Redocly/redoc instead.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md

### Document ID

d515a3d8-28f2-578f-c302-dc884544aaf4

### Article author

@captainsafia

**Comment by captainsafia** [comment]
:interrobang:

Dunno how that got there 😅 

Opened a PR to fix.
