### ISSUE TITLE
The `Movie` model class changes between tutorial parts

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#32694]
### Description

The `Movie` model in this part of the tutorial is different than the one shown earlier in the series at ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-8.0&tabs=visual-studio#add-a-data-model

... here's the delta section ...

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio#adding-a-rating-property-to-the-movie-model

NRTs before, no NRTs here.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/razor-pages/new-field.md

### Document ID

24699fe5-9744-1796-0798-f7b211ec0f2f

### Article author

@wadepickett

---
[Associated WorkItem - 261112](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261112)

**Comment by wadepickett** [comment]
You are right.  The model does get updated twice I think over the course of the series, but it looks like an update was made at some point in the New Field tutorial and not introduced and added to the earlier tutorials.  Thanks for catching this!
Thanks @guardrex

**Comment by wadepickett** [comment]
Verified the correct model changes occur at: /tutorials/razor-pages/da1#update-the-model in PR #32850
