### ISSUE TITLE
Missing links in this page

### ISSUE THREAD

**Issue by romarro** [dotnet/AspNetCore.Docs#32709]
### Description

[Enter feedback here]
The link to the [PersistentAuthenticationStateProvider class (reference source)](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/PersistentAuthenticationStateProvider.cs)
is going to a missing page

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/index.md

### Document ID

8da62490-e36f-8f38-8f06-d5d6bceaafde

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @romarro ... Yes, they moved the 🧀 on that one. I'll update the link. Thanks for the report!
