### ISSUE TITLE
ShutdownTimeout default value inconsistency

### ISSUE THREAD

**Issue by nharren** [dotnet/AspNetCore.Docs#32704]
### Description

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-8.0#shutdowntimeout

In the ShutdownTimeout section, it says in the paragraph "The default value is five seconds". However, this was changed in .NET 6 to 30 seconds and shows correctly in the summary below it.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-8.0#ihostlifetime

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/generic-host.md

### Document ID

2373a3df-6ea3-50c7-d63d-61c51d572511

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@nharren Thanks for reporting that!
