### ISSUE TITLE
HTTPS URLS not processed by app on Mac using VS Code

### ISSUE THREAD

**Issue by omatrot** [dotnet/AspNetCore.Docs#32722]
### Description

I'm going through the ASP.NET MVC Tutorial on a Mac using VS Code.
When you specify HTTPS urls, it does not work on my machine, the controllers are only reachable on HTTP.

There is a warning int the console output:
```
Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md

### Document ID

3477519b-1bc2-73be-33e3-63067383d426

### Article author

@wadepickett

**Comment by wadepickett** [comment]
Thanks @omatrot for taking the time to let us know your experience with this tutorial series.
In the previous tutorial in this series there is a step for running a dotnet command to trust the HTTPS development certificate here:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-8.0&tabs=visual-studio-code#run-the-app

If that step was missed, or the following step when you are asked about installing the certificate, then you could receive the same error you are receiving now as you try to access a HTTPS URI for the app example.

I have tested again through that part of the topic this morning and it seems to be working OK, but if you think I am still missing something, feel free to re-open the issue.   Thanks again.

**Comment by omatrot** [comment]
This has nothing to do with trusting the certificate. Rather, Visual Studio Code lets you choose which profile to use after choosing the debugger. I have accidentally chosen 'http' and not 'https'. Maybe this has to be clarified in the docs. Thanks.
