### ISSUE TITLE
New setting #10117

### ISSUE THREAD

**Issue by joshmouch** [dotnet/AspNetCore.Docs#32745]
### Description

@BrennanConroy 

Hi, there's a new setting that you'll likely be adding to the docs soon from this issue:
https://github.com/dotnet/aspnetcore/issues/41340

The PR and the issue thread are both locked now, so I couldn't ask there, but I think it's unclear to what value shutdownDelay or ANCM_shutdownDelay settings should be set.
From reading some comments we found in the source code, we think it should be set to greater than the longest running request in the app.  So, for example, if the app has an endpoint that runs for 2 minutes, then that value should be set to > 120 seconds.
However, that's a long time, so we need to know what the pros and cons are of longer versus shorter delay values.

The new default value for ASP.NET Core 9.0+ should be shown somewhere.

It should also be pointed out that this error will manifest itself as an HTTP 503 Win32status 1255 (0x4E7).  Because while the fix gives a mechanism to resolve the error, it's not obvious that the two are related.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-8.0#options

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/iis/hosting-bundle.md

### Document ID

22e2323b-18c3-ad2b-174c-84fbf642715e

### Article author

@Rick-Anderson

**Comment by BrennanConroy** [comment]
It's already been added to documentation: https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/advanced?view=aspnetcore-9.0#reduce-503-likelihood-during-app-recycle

If you think it needs more documentation, open a new issue from that page.

**Comment by Rick-Anderson** [comment]
@BrennanConroy  would it be worth adding expanding **Additional resources**

<img width="254" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/3bf9e2a8-740b-4047-b3b3-d66d95a58d2c">
Moving that to an include, and adding it to most of the topics under IIS?
<img width="146" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/52a0beb7-d5dc-42a6-8bc8-ea1bc5beab41">

### Advanced configuration of the ASP.NET Core Module and IIS

A link to Should probably be added to most topics.
