### ISSUE TITLE
"Secure a hosted ASP.NET Core Blazor WebAssembly app with Azure Active Directory B2C" Article has incorrect example for "Authentication Component" Section

### ISSUE THREAD

**Issue by akleinaegis** [dotnet/AspNetCore.Docs#32758]
### Description

The article in question has a bad example in the "Authentication Component" section https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0#authentication-component

The `<RemoteAuthenticatorView Action="Action" />` should be `<RemoteAuthenticatorView Action="@Action" />`. The example as presented here passes the string literal "Action" to the RemoteAuthenticatorView which results in an `InvalidOperationException` with the message `Invalid action 'action'`.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory-b2c?view=aspnetcore-7.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/webassembly/hosted-with-azure-active-directory-b2c.md

### Document ID

da9c8ac9-4d7a-4b40-56a2-a4bfe7083567

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @akleinaegis! ... I'll get this fixed ASAP, but it might be tomorrow because I'm buried in a tutorial-writing task at the moment.

**Comment by guardrex** [comment]
Actually, I have a sec right now. I can't stand a 🐛 ***doc BUG*** 🪲 in the article! 😆
