### ISSUE TITLE
Delegate event handlers are not called unless @rendermode InteractiveServer is set

### ISSUE THREAD

**Issue by codeshanks** [dotnet/AspNetCore.Docs#32763]
### Description

The section on Delegate event handlers is incorrect. The previous page/section on Render Modes https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#static-server-side-rendering-static-ssr correctly states that if the page rendering is static, delegates will not be called. The documentation on this page implies it will work with the default static rendering and "@renderMode" is not included in the sample code.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @codeshanks ... I'll make a few changes at the top of the article to address it.
