### ISSUE TITLE
No file names for code snippets

### ISSUE THREAD

**Issue by nicholasbergesen** [dotnet/AspNetCore.Docs#32772]
### Description

This page doesn't give filenames for each of the code snippets, making it difficult to follow what's being demonstrated in the priority list examples.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-8.0#create-a-view-component

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/view-components.md

### Document ID

b5715d72-5f10-bb93-1051-7f06dfa9cde8

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
See [Create a basic view component](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-8.0#create-a-basic-view-component) which has [Download](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/views/view-components/sample6.x), build and test the starter code.

**Comment by nicholasbergesen** [comment]
Hi @Rick-Anderson, I think the docs could be improved by adding a little context to the code snippets in the doc. I understand the code is fully available via the download link but the point is to improve the documentation describing the code.
