### ISSUE TITLE
Is partial tag helper self closing?

### ISSUE THREAD

**Issue by omatrot** [dotnet/AspNetCore.Docs#32788]
### Description

The documentation shows many examples with the partial tag helper self closing.
The last example explicitly closes the HTML element.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md

### Document ID

e7df465a-5f3b-1522-b2d9-5e3afbf74257

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
No, it should be closed `<partial name="_MyPartialView" />`
