### ISSUE TITLE
Detect the current component render mode at runtime

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32780]
[EDIT by guardrex to change the article]

### Description

~Update [Component classes](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/#component-classes) section~ Add a section to include [Detect the current component render mode at runtime](https://github.com/dotnet/AspNetCore.Docs/issues/32692#issuecomment-2155207887)

Contributes to 32692

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-modes.md

### Document ID

7c9948a3-9886-8097-6014-492a4c21ea4e

### Article author

@guardrex

---
[Associated WorkItem - 262163](https://dev.azure.com/msft-skilling/Content/_workitems/edit/262163)

**Comment by Rick-Anderson** [comment]
@guardrex do you want this or should I take it. It's mostly aimed at Blazor, right?

**Comment by guardrex** [comment]
Yes, it's for Blazor. I'll take care of it on Monday.

**Comment by guardrex** [comment]
https://github.com/dotnet/AspNetCore.Docs/issues/32781 and https://github.com/dotnet/AspNetCore.Docs/issues/32780 are duplicates ... and this probably won't be for this article. It will be for the *Render Modes* article. No worries ... I'll sort it out on Monday.

**Comment by Rick-Anderson** [comment]
@guardrex  should I add the new content to [View components in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-9.0)?

**Comment by guardrex** [comment]
It only applies to Razor components.
