### ISSUE TITLE
WN: Optimizing static web asset delivery

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32783]
### Description

[Optimizing static web asset delivery](https://github.com/dotnet/AspNetCore.Docs/issues/32692#issuecomment-2155207887)
related 
#32782
cc @guardrex 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 262164](https://dev.azure.com/msft-skilling/Content/_workitems/edit/262164)

**Comment by guardrex** [comment]
I see that this one bridges into the Blazor framework. I'll probably open a parallel issue only for the Blazor static files article. I'll work on that on Monday with the other Pre5 Blazor items.
