### ISSUE TITLE
Optimizing static web asset delivery

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32782]
### Description

See [issue: Optimizing static web asset delivery](https://github.com/dotnet/AspNetCore.Docs/issues/32692#issuecomment-2155207887)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/static-files.md

### Document ID

3fec6e08-fc99-7a5c-796f-3f2347cad891

### Article author

@Rick-Anderson

---
[Associated WorkItem - 262166](https://dev.azure.com/msft-skilling/Content/_workitems/edit/262166)

**Comment by guardrex** [comment]
BTW for when this is reached ... Map Static Assets Middleware will also be linked in the middleware table at ...

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-9.0

**Comment by Rick-Anderson** [comment]
Fixed in #33050
