### ISSUE TITLE
Migrate 2nd batch of topics from `ms.author: riande` to Wade per Jill.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32831]
Migrate  topics from `ms.author: riande` to Wade per Jill.

Coordinate with @tdykstra who's leading the ownership migration.

**Comment by wadepickett** [comment]
Following up with you both offline to figure that out.

**Comment by wadepickett** [comment]
@Rick-Anderson, how does this issue differentiate from #32830?  "Migrate 25 topics from ms.author: riande to Wade per Jill."

Is it an accidental duplicate or does it mean some unnamed amount of topics in addition to the first 25?   Also, There are topics still assigned to folks such as Scott Addie and others that might make sense, not just from the set you have?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, how does this issue differentiate from #32830? "Migrate 25 topics from ms.author: riande to Wade per Jill."
> 
> Is it an accidental duplicate or does it mean some unnamed amount of topics in addition to the first 25? Also, There are topics still assigned to folks such as Scott Addie and others that might make sense, not just from the set you have?

2nd round, she wants a balanced ownership. I don't think 25 will do it.

**Comment by wadepickett** [comment]
OK thanks, I understand now.  On it...
