### ISSUE TITLE
Update PS code language to proper noun capitalization

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#32847]
Per the PS docs, we're supposed to be doing it this way ...

✔️ \`\`\`PowerShell

... not ...

:x: \`\`\`powershell

**Comment by tdykstra** [comment]
Where did you see that? Here it's all lowercase, which is the standard way to do all languages in this setting:
https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.4#markdown-for-code-samples

**Comment by guardrex** [comment]
All over the place ... for example in that article a little further down ...

https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.4#avoid-using-powershell-prompts-in-examples

However, they're somewhat scatterbrained about it ...

https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.4#formatting-cmdlet-reference-articles

... and ...

https://learn.microsoft.com/en-us/contribute/content/code-in-docs#supported-languages

... but it's all over the place. Here are some examples (separate articles ... there are tons of them) ...

* https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/01-getting-started?view=powershell-7.4#how-do-i-launch-powershell
* https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/02-help-system?view=powershell-7.4#get-help
* https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/03-discovering-objects?view=powershell-7.4#properties
* https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/04-pipelines?view=powershell-7.4#one-liners
* https://learn.microsoft.com/en-us/powershell/scripting/learn/ps101/05-formatting-aliases-providers-comparison?view=powershell-7.4#format-right

.... and it just keeps going like that. They say to use all lowercase; but in practice, they seem to never actually use lowercase AFAICT.

**Comment by guardrex** [comment]
I'll close this, but I think someone should take it up with them to see if they really do want "PowerShell" for command shell blocks.

**Comment by tdykstra** [comment]
I don't see where it is uppercase except when rendered -- the  source for the one you mention at 7.4 avoid using is
~~~
Prompts are required in examples to illustrate commands that alter the prompt or when the path
displayed is significant to the scenario. The following example illustrates how the prompt changes
when using the Registry provider.

```powershell
PS C:\> cd HKCU:\System\
PS HKCU:\System\> dir

    Hive: HKEY_CURRENT_USER\System

Name                   Property
----                   --------
CurrentControlSet
GameConfigStore        GameDVR_Enabled                       : 1
                       GameDVR_FSEBehaviorMode               : 2
                       Win32_AutoGameModeDefaultProfile      : {2, 0, 1, 0...}
                       Win32_GameModeRelatedProcesses        : {1, 0, 1, 0...}
                       GameDVR_HonorUserFSEBehaviorMode      : 0
                       GameDVR_DXGIHonorFSEWindowsCompatible : 0
```
~~~
