### ISSUE TITLE
peris 

### ISSUE THREAD

**Issue by Periswambui678** [dotnet/AspNetCore.Docs#32854]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/partial.md

### Document ID

c20d4db8-d403-9218-c39d-47e56c34e767

### Article author

@ardalis

**Comment by Periswambui678** [comment]
good work successful completed

**Comment by guardrex** [comment]
Thanks, @Periswambui678! 🚀
