### ISSUE TITLE
How can partials be minified?

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32866]
### Description

UUF verbatim:
>Need more info for "Load minified partial view TagHelper". How can partials be minified? That isn't discussed anywhere, just stated as if it's well known, it isn't.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/views/tag-helpers/authoring.md

### Document ID

9a0cbaa2-65c9-1618-1003-5fd2e7f6192f

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Use a minification tool, the same as JavaScript, css, etc. 
```
@inject IWebHostEnvironment env
@if (env.IsProduction())
{
    <partial name="_MyPartialView.min" /> 
}
else
{
    <partial name="_MyPartialView" /> 
}
```
