### ISSUE TITLE
Clarify UI instructions

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32869]
### Description

UUF verbatim:
>I tried creating an isolated css file twice and it didn't work because I was selecting Add > Razor Component. Maybe add a note saying select Add > New Item. (Add > Razor Component results in a file called Name.razor.razor, even if you type Name.razor.css.)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/css-isolation.md

### Document ID

39d464d9-aca6-34fa-7e52-5fde2e393ba7

### Article author

@guardrex

**Comment by guardrex** [comment]
A CSS file would be created as a ***stylesheet***, not a Razor component. Anyway .......

Generally, we don't cover specific tooling gestures for creating files. We cater to every type of tooling outside of ***tooling-specific coverage*** ... *tutorials* ... where we would have guidance like this for VS, VSC, and CLI.

Thanks @tdykstra for opening these UUF-based issues. I'll definitely schedule the ones that I think are good to address.
