### ISSUE TITLE
Need to improve discoverability

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32865]
### Description

UUF verbatim:
>This should be one of the main pages of Blazor. I had to dig to find this

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/render-modes.md

### Document ID

7c9948a3-9886-8097-6014-492a4c21ea4e

### Article author

@guardrex

**Comment by guardrex** [comment]
This page is in this position for specific reasons in relation to other articles in the ToC. This was a carefully considered decision and approved by management. This article won't move ... well ... *unless DR changes his mind!* 😆

However, the article is cross-linked in ***NINE*** earlier articles where render modes are referenced, and it shows up first in docs search with the search phrase "render modes" ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/2cd7b653-35b6-4c6d-85be-6e89d04e3c48)

... and from Google with a filtered search on the repo ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/ee6f1edf-c4d0-44ec-9422-3da0f0277969)

... and from Google on a "Blazor" search ...

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/26ec0f23-173f-438f-9e9e-ed03d333fb7a)
