### ISSUE TITLE
How to get an ILogger during the startup process before calling Build()

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32867]
### Description

UUF verbatim:
>Hello, please add an example how to get an ILogger<> during the startup process before calling . Build()It was easy with Startup.cs but the "new" php like startup style makes it impossible right?sorry, but i am very frustrated about this bad programming style and the problems that come with it :(

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/50-to-60-samples.md

### Document ID

20acee3e-8b6e-b3fb-8271-661e1a287bdd

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
See [Log in Program.cs](https://learn.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-8.0) which is the 3rd line of code. What's the use case of needing it before 
```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
```
