### ISSUE TITLE
Content Root Details

### ISSUE THREAD

**Issue by lozh** [dotnet/AspNetCore.Docs#32894]
### Description

I think the explanation of Content Root is missing some nuance. It says the Content Root is the path for binaries. However, when running under Visual Studio the Content Root is set to the project folder. This folder has no binaries. I assume that if you run the program from VS, it runs the binary for your current configuration, but with a working directory of the project folder. This implies that the binary can find dlls in the same directory as itself, regardless of the working directory.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-8.0&tabs=linux

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/index.md

### Document ID

8e663029-63b9-2622-f852-9f8a2ec70db3

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Yes the binary can locate DLLs in the same directory as itself, regardless of the working directory. This behavior is facilitated by the Content Root Path, which serves as a starting point for file resolution during application execution.
