### ISSUE TITLE
Authentication scheme configuration

### ISSUE THREAD

**Issue by chrisdrobison** [dotnet/AspNetCore.Docs#32936]
In the Blazor samples here:  https://github.com/dotnet/blazor-samples/blob/31b59a54a172a3ee18dde49dbbea83e41ca8e757/8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs#L84

It says that configuration of authentication schemes is automatically pulled from config. I have been all over the documentation and have not found that anywhere. If this truly is the case, this needs a major highlight in the docs because all the other examples I see are of manual setup of the configuration objects.

**Comment by guardrex** [comment]
Hello @chrisdrobison ... Please open this from the **Open a documentation issue** link/feedback form at the bottom of the article at ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

Note that out on vacation this week and will return on Monday, July 1.
