### ISSUE TITLE
Refactor "OpenAPI support in minimal API apps" and "Get started with Microsoft.AspNetCore.OpenApi"

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#32949]
### Description

@tdykstra  please review
Also applies to content health.

Some duplication but related content is scattered between the two docs

Refactor OpenAPI support in minimal API apps

**`OpenAPI support in minimal API apps`**

## [Describe endpoints](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-9.0#describe-endpoints)

OpenAPI supports providing summaries and descriptions of routes that are registered in an app. Minimal APIs support two strategies for setting these properties on a given endpoint, using the following extension methods and attributes:

Summaries: [WithSummary](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.openapiroutehandlerbuilderextensions.withsummary)
Descriptions: [WithDescription](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.openapiroutehandlerbuilderextensions.withdescription)
Summaries: [EndpointSummaryAttribute](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.endpointsummaryattribute)
Descriptions: [EndpointDescriptionAttribute](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.endpointdescriptionattribute)

**`Get started with Microsoft.AspNetCore.OpenApi`**

## [Customize OpenAPI endpoints with endpoint metadata](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?view=aspnetcore-9.0&tabs=visual-studio#customize-openapi-endpoints-with-endpoint-metadata)
The following list shows the endpoint metadata that is used to customize the generated OpenAPI document:

Summaries from [IEndpointSummaryMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.metadata.iendpointsummarymetadata)
Descriptions from [IEndpointDescriptionMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.metadata.iendpointdescriptionmetadata)
Request body from [IAcceptsMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.metadata.iacceptsmetadata)
Response information from [IProducesResponseTypeMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.metadata.iproducesresponsetypemetadata)
Operation IDs from [IEndpointNameMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.iendpointnamemetadata)
OpenAPI tags from [ITagsMetadata](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.metadata.itagsmetadata)
To learn more about customizing the generated OpenAPI document by modifying endpoint metadata, see [How to use OpenAPI in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-9.0).

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/openapi?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/minimal-apis/openapi.md

### Document ID

b18acd86-50e3-2316-27be-27156651e5a8

### Article author

@Rick-Anderson

---
[Associated WorkItem - 273722](https://dev.azure.com/msft-skilling/Content/_workitems/edit/273722)

**Comment by tdykstra** [comment]
>@tdykstra please review

I would refactor into 3 articles:
* **Overview** - A basic introduction to OpenApi and its support in minimal API apps. Explain how OpenApi documents are and how they are used, what transformers are and how they are used. Minimal details about specific APIs / how to describe endpoint requests and response, etc. Mention controller-based APIs and what is available for them.
* **How to use OpenApi in ASP.NET Core minimal APIs** - This will have all the details about how to customize endpoint descriptions, use transformers, etc. Optionally make this multiple articles -- how to customize endpoint descriptions (nothing about transformers), how to use transformers. There may be more ways to divide this content into multiple articles. If you can get it into a set of smaller how-tos, you could try using the Learn Linter and try following the official how-to pattern.
*  **Tutorial: Get started with OpenApi in ASP.NET Core minimal APIs** - No attempt to do everything as in the how-to, but detailed guidance through creating a document, customizing endpoint descriptions, and using transformers. Include a section on using an OpenApi document, maybe with swagger UI, not just create a document.

**Comment by Rick-Anderson** [comment]
c.osed
