### ISSUE TITLE
How to do pagination in MVC

### ISSUE THREAD

**Issue by Gluups** [dotnet/AspNetCore.Docs#32944]
### Description

In the page I read "This tutorial has not been updated for ASP.NET Core 6 or later."
For an initiation to pagination with MVC in 2024, what platform would you recommend?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md

### Document ID

8daf79df-eac4-358b-e6f0-6def45bd54da

### Article author

@tdykstra

---
[Associated WorkItem - 286792](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286792)

**Comment by Rick-Anderson** [comment]
@tdykstra  @wadepickett  can we clean up titles? That's really important for Azo too.

**Comment by tdykstra** [comment]
>For an initiation to pagination with MVC in 2024, what platform would you recommend?

Hello @Gluups. If you follow the tutorial directions and create a .NET 5 project, the tutorial should still work. The Program.cs code will be out of date, but the pagination section code should work the same in the current release.
