### ISSUE TITLE
Comment documentation is wrong

### ISSUE THREAD

**Issue by jameswiseman76rlg** [dotnet/AspNetCore.Docs#32950]
### Description

Documentation states 

Lines that start with either # or // are comments. These lines are ignored when Visual Studio sends HTTP requests.

This is not correct. You need 3 hashes (###) to start a comment.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

**Comment by tdykstra** [comment]
The statement about comments is correct. Three hashes are needed only as a delimiter between requests, as in the following example:
```
# comment
@WebApplication9_HostAddress = http://localhost:5056
# comment
GET {{WebApplication9_HostAddress}}/weatherforecast/
Accept: application/json
# comment.
### start a new request
# comment
GET {{WebApplication9_HostAddress}}/weatherforecast?date=2023-05-11
Accept: application/json
# comment
```
The function of the three hashes is explained [here](https://learn.microsoft.com/en-us/aspnet/core/test/http-files#requests)
