### ISSUE TITLE
Not provided `IStringLocalizer` implementation

### ISSUE THREAD

**Issue by runceel** [dotnet/AspNetCore.Docs#32959]
### Description

In this document, it is mentioned that the `IStringLocalizer<T>` implementation can be found as follows:

`In the preceding code, the IStringLocalizer<T> implementation comes from [Dependency Injection](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0).`

However, I could not find the said implementation on the `Dependency Injection` page.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/localization/make-content-localizable?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/localization/make-content-localizable.md

### Document ID

72e0699e-f13a-8ca8-9106-59c301ee2de4

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
That means it was added to DI and fetched to DI. DI is a container for things added.
