### ISSUE TITLE
Remove user from a role

### ISSUE THREAD

**Issue by wxommzwsdao** [dotnet/AspNetCore.Docs#32963]
### Description

In this page we talk about roles.  Perhaps you could add the section contained in the link [Add or remove a user to a role](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-8.0#add-or-remove-a-user-to-a-role) where you references this issue [Mute or remove privileges from a user. Admin changes](https://github.com/dotnet/AspNetCore.Docs/issues/8502).

Is the solution of this issue valid today?

Thanks.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/roles.md

### Document ID

980a23e7-56e4-da94-a139-cab85135c5f7

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Roles hasn't changed since that issues.
