### ISSUE TITLE
Xamarin.Forms reached EOS on 1st May

### ISSUE THREAD

**Issue by davidbritch** [dotnet/AspNetCore.Docs#32961]
### Description

This article talks about an ASP.NET Core backend for a Xamarin.Forms app. All Xamarin products reached EOS on 1st May, and Xamarin docs were archived on that day. Therefore this article either needs replacing with a .NET MAUI equivalent, or archiving.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-8.0&tabs=windows#the-sample-native-mobile-app

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mobile/native-mobile-backend.md

### Document ID

d06996cc-14aa-96e2-fd62-9d5bbc059107

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
This is a duplicate of https://github.com/dotnet/AspNetCore.Docs/issues/26109.
