### ISSUE TITLE
aidemos.microsoft.com not working

### ISSUE THREAD

**Issue by kawada711** [dotnet/AspNetCore.Docs#32964]
### Description

aidemos.microsoft.com not working
![image](https://github.com/dotnet/AspNetCore.Docs/assets/100365282/6f1c7c8c-7c08-4577-8a55-e5daae80810c)

### Page URL

https://learn.microsoft.com/en-gb/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/troubleshoot-azure-iis.md

### Document ID

5e3c0546-c579-afb9-5289-b14532c127eb

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
This is asp.net core, your app is using .NET Framework.
