### ISSUE TITLE
Bug in Blazor sample code 

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#32978]
### Description

UUF verbatim:

```public Task SendConfirmationLinkAsync(ApplicationUser user, string email, 
         string confirmationLink) => SendEmailAsync(email, "Confirm your email",
         $"Please confirm your account by " +
        "<a href='{confirmationLink}'>clicking here</a>.");
```
>This is actually wrong - you need another $ on the second line of the string :)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/server/account-confirmation-and-password-recovery?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/server/account-confirmation-and-password-recovery.md

### Document ID

973eba04-8bc3-44be-23db-02f2b0c97a5c

### Article author

@guardrex

**Comment by guardrex** [comment]
Right ... breaking lines to fit 😈 got me. I'll fix it right now. 🏃
