### ISSUE TITLE
I follow each instructiosn but still, it is impossible to see the app as you show in the picture, the app remains as the beggining without showing the " hello messages/ welcome one) I did the cacahe celaning, the degrading to previous version in C, i the vs code, I did everything posible that i found in internet, but still I am unable to build the app as you show. teh code is there but with some issues. Why do you  make steps along with copy paste code that dont work?

### ISSUE THREAD

**Issue by desivar** [dotnet/AspNetCore.Docs#32977]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/adding-controller.md

### Document ID

3477519b-1bc2-73be-33e3-63067383d426

### Article author

@wadepickett

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
Perhaps start over and read about debugging in visual studio. This tutorial has a high success rate and we're not staffed to provide individual help.
