### ISSUE TITLE
How can I get the new Angular template without Visual Studio?

### ISSUE THREAD

**Issue by Donistivanov** [dotnet/AspNetCore.Docs#32989]
Could there please be instructions for Visual Studio code or how to do things through the command line for https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-8.0&source=recommendations&tabs=visual-studio?

**Comment by guardrex** [comment]
Hello @Donistivanov ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.
