### ISSUE TITLE
Logging documentation missing information on LoggingBuilderExtensions.AddConfiguration

### ISSUE THREAD

**Issue by dk-ebeisecker** [dotnet/AspNetCore.Docs#32986]
### Description

The dotnet logging documentation contains a lot of great information on how to use the dotnet logging APIs. However, the examples provided seem to indicate that log settings can be set via an `appsettings.json` config file if the `appsettings.json` file has been added as a Configuration provider. However, in my testing, a call to [AddConfiguration](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggingbuilderextensions.addconfiguration?view=net-8.0) is needed before the providers defined in the ILoggerFactory are configured with the Log filters that are defined in the `appsettings.json` file. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/logging/index.md

### Document ID

726e3bf1-f367-d733-8933-bccc04da0e16

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
You realize that by default, locally, `appsettings.Development.json` is used?
Default template, change  `appsettings.Development.json` to:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Information"
    }
  }
}
```
![image](https://github.com/dotnet/AspNetCore.Docs/assets/3605364/b0d85dec-e864-4111-b6b7-91ff0c2d0fbd)
