### ISSUE TITLE
Update the PostTodoItem create method is wrong

### ISSUE THREAD

**Issue by henrycomm100** [dotnet/AspNetCore.Docs#32982]
### Description

`[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem todoItem)
{
    _context.TodoItems.Add(todoItem);
    await _context.SaveChangesAsync();

    //return CreatedAtAction("PostTodoItem", new { id = todoItem.Id }, todoItem);
    return CreatedAtAction(nameof(PostTodoItem), new { id = todoItem.Id }, todoItem);
}`

[Enter feedback here]

The document says - References the GetTodoItem action to create the Location header's URI. The C# nameof keyword is used to avoid hard-coding the action name in the CreatedAtAction call.

But the code provided is still using the nameof(PostTodoItem). It should be nameof(GetTodoItem).

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio#scaffold-a-controller-1

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

**Comment by timdeschryver** [comment]
@wadepickett I can create a PR for this if you want (and also update the 3.0, 5.0, and 6.0 versions of the docs)

**Comment by wadepickett** [comment]
@timdeschryver, thanks for offering, you are welcome to.  I am on vacation for two more days and was planning to hit it when I got back.
