### ISSUE TITLE
How can I get the new Angular template without Visual Studio?

### ISSUE THREAD

**Issue by Donistivanov** [dotnet/AspNetCore.Docs#32990]
### Description

Could there please be instructions for Visual Studio code or how to do things through the command line?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-8.0&source=recommendations&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/angular.md

### Document ID

c58d57e5-a0c2-201d-f6dd-076ad5971fcb

### Article author

@SteveSandersonMS

---
[Associated WorkItem - 280320](https://dev.azure.com/msft-skilling/Content/_workitems/edit/280320)

**Comment by Rick-Anderson** [comment]
`dotnet new angular `

**Comment by Donistivanov** [comment]
@Rick-Anderson That doesn't seem to work. I am on 8.0.301. Is the one you are thinking of discontinued this release: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates#spa ?

**Comment by Rick-Anderson** [comment]
What doesn't work?

```
c:\tmp>dotnet new angular
The template "ASP.NET Core with Angular" was created successfully.

Processing post-creation actions...
Restoring c:\tmp\tmp.csproj:
Restore succeeded.
```

**Comment by Donistivanov** [comment]
@Rick-Anderson Yes, can there be support for non-VS folks?

These SPA templates sometimes feel over engineered, but at least I should try to study it and adjust it to what I think would be best for me

**Comment by Donistivanov** [comment]
@Rick-Anderson Is it ok if this kindly remains open so it's visible and someone can pick it up?

**Comment by Rick-Anderson** [comment]
@Donistivanov in the mean time have you looked at Blazor? Although Angular is still support, most of the development effort is around Blazor.

**Comment by Donistivanov** [comment]
@Rick-Anderson I can take a look at the tutorial for a little bit and report back. I'm pretty happy with Angular though.

But that's what I am saying. They are trying to make it so running the server app runs the client app across different frameworks, but that just makes it confusing. The SPA story needs to be, run any front end separate during dev and have ASP.NET Core sit in front and be the proxy + easy publish front end files in wwwroot. Then it shouldn't matter that Blazor is the focus. In other words, the SPA story is not the Blazor story

**Comment by Donistivanov** [comment]
@Rick-Anderson Ok, I wanted to say I did the smaller tutorials in the docs.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson I can take a look at the tutorial for a little bit and report back. I'm pretty happy with Angular though.

I don't blame you for that. If you have experience with Angular, that won't help much with C#/.net Blazor.

>the SPA story is not the Blazor story

Yup.

cc @guardrex

**Comment by tdykstra** [comment]
We've created an internal work item to track the work to make the new templates accessible from the CLI `dotnet new`. If you'd like there to be a public request on file, the best place for that is a suggestion on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/VisualStudio/suggest), since those templates are now a Visual Studio feature.

**Comment by Donistivanov** [comment]
@tdykstra Thank you, don't forget the docs, too!
