### ISSUE TITLE
Update Angular links to the new Angular website

### ISSUE THREAD

**Issue by timdeschryver** [dotnet/AspNetCore.Docs#32992]
# Before you open an issue

If the issue is with an ASP.NET Core document:

* Do **not** open a new issue using this form.
* Open the issue using the **Open a documentation issue** link and feedback form at the bottom of the article. 

Using the **Open a documentation issue** link and form to open an issue adds article metadata for tracking, which indicates the article that you're commenting on.

If the issue is:

* A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
* A general support question, consider asking on a support forum site.
* A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/issues/new/choose).
* A problem completing a tutorial, compare your code with the completed sample.
* A duplicate of an open or closed issue, leave a comment on that issue.

# Issue description

Hello, sorry for not using the button on the https://learn.microsoft.com website but this is an issue that across multiple pages. In matter fact, it isn't even .NET related, but Angular related.
Angular has moved their website from https://angular.io to https://angular.dev (as part of their rebranding), and they didn't do a great job with adding redirects.

This has an impact to the links in the ASP.NET documentation, for example the links all have a banner on the top of the page.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/28659384/5fead549-8339-4625-a615-2aaffa26d339)

There are 15 links in total (not counting the generated ones in code files) that references the Angular website, here's a list of the unique links:

- https://angular.io/
- https://angular.io/docs
- https://angular.io/cli
- https://angular.io/cli/serve
- https://angular.io/guide/http#security-xsrf-protection

Via this way I wanted to raise my concerns that this isn't a great experience, and that those docs might become outdated in the future.
If you want, I can go over all the links and update them to their new location on the new  https://angular.dev website.

**Comment by tdykstra** [comment]
Hello,
Yes, we'd welcome a PR to do that.
Thanks
