### ISSUE TITLE
Please clarify "Mon prep Azure trouble"

### ISSUE THREAD

**Issue by QueryCoordinator** [dotnet/AspNetCore.Docs#33004]
### Description

Hello,

please clarify what "Mon prep Azure trouble" means, especially 'Mon' in this context. Please consider rewriting the segment. Also 'mon split' a few rows below this one is not clear, what 'mon' refers to.

Kind regards,
Anne H., QC

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/whats-new/dotnet-aspnetcore.docs-mod0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/whats-new/dotnet-AspNetCore.Docs-mod0.md

### Document ID

48082057-3e16-fd3f-5ce6-5e31e44a2d04

### Article author

@Rick-Anderson

**Comment by ParsaMehdipour** [comment]
I am guessing that it means : Monitor preparation for Azure trouble

**Comment by Rick-Anderson** [comment]
Select the link [Troubleshoot ASP.NET Core on Azure App Service and IIS](https://learn.microsoft.com/en-us/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-8.0)
select edit, select history to see exactly the change.

It's actually _moniker preparation_ and has nothing to do with updating the content, just the way it's organized.
