### ISSUE TITLE
WN static asset updates

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33019]
### Description

See [this comment](https://github.com/dotnet/AspNetCore.Docs/issues/32960#issuecomment-2214414155)

@Rick-Anderson ... I'm working on the Blazor-specific static asset updates (fingerprinting, etc.) for the Blazor *Static Files* article, and I should have a PR up for review shortly.

The following link can be used for the new feature *What's New* blurb ...

> For more information on Blazor's new file delivery features, see \<xref:blazor/fundamentals/static-files?view=aspnetcore-9.0>.

@guardrex  can you add that link to WNinV9 or should I?

>I think for the *What's New* blurb, it could be as simple as the edited opening remarks on "History" and "Goals" that Javier provided at ...
>
>https://github.com/dotnet/aspnetcore/issues/52824

cc @tdykstra 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 280589](https://dev.azure.com/msft-skilling/Content/_workitems/edit/280589)

**Comment by guardrex** [comment]
I was leaving the WN blurb on that to you so that I didn't step on your efforts to update the main doc set's *Static Files* article (or any other updates that you needed to make to the WN file). I didn't want to create a merge conflict unnecessarily 💥.

I can give you a blurb of text here based on Javier's remarks for the article, and then all you'd need to do is drop it in with your edits to it and possibly a cross-link to a section that you might add to the main doc set's *Static Files* article. This is a cut-'n-paste that I envision would go in an open, general area of the WN doc (i.e., not in a MVC/RP/Blazor subsection) ...

> \#\# Optimize file delivery for web apps
>
> Following production best practices for serving static assets requires a significant amount of work and technical expertise. Files are usually delivered to browsers without optimizations, such as compression, caching, and fingerprinting. As a result, the browser is forced to perform additional requests on every page load, more bytes are transferred through the network, and even stale versions of files are sometimes served to clients.
>
> .NET 9 includes optimizations that accomplish the following goals:
>
> \* Serve a given asset once until the file changes or the browser clears its cache.
> \* Preclude the browser from using old or stale assets after an app is updated.
> \* Preclude the browser from using old asset versions during development.
> \* Decrease page load times by delivering assets faster using modern browser features.
> \* Minimize the size of assets served to the browser. (This optimization doesn't include minification.)
>
> For more information on the new file delivery features, see the following resources:
>
> \* \<xref:fundamentals/static-files?view=aspnetcore-9.0>
> \* \<xref:blazor/fundamentals/static-files?view=aspnetcore-9.0>
