### ISSUE TITLE
Including App doesn't work while following the tutorial

### ISSUE THREAD

**Issue by Rod-at-DOH** [dotnet/AspNetCore.Docs#33055]
### Description

[Enter feedback here]

I've been following along in the tutorial. Everything was going fine, until I entered this code just before the `app.Run()` command at the end of Program.cs:

```csharp
app.MapRazorComponents<App>();
```

That line raises this error:

> CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)

Have I done something wrong or is there something missing?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/integration.md

### Document ID

d7e39bbc-cd54-92aa-4997-f9dd39dd6ef3

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Rod-at-DOH ... Make sure that you have the namespace at the top of the `Program.cs` file (`using BlazorSample.Components;`) and that the `App` component (`App.razor`) is in the `Components` folder. These instructions are in the guidance.

**Comment by Rod-at-DOH** [comment]
Hi @guardrex, I do have the NAMESPACE.Components at the top of my Program.cs file:

```csharp
using Microsoft.AspNetCore.Authentication.Negotiate;
using AspNetCoreWithWindowsAuth.Components;
```

(AspNetCoreWithWindowsAuth is my project's name.)

Well, dang, now it recognizes **App** in the MapRazorComponents<App> call. I don't know what to say; yesterday it didn't, this morning it does.

Thank you for your reply.
