### ISSUE TITLE
What's New: SignalR supports trimming and AOT: Edit and move to include

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33054]
Contributes to #33031

Do an edit/writing pass on content/code provided by eerhardt here:
https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2219013346

..and move to an include in the What's New for .NET 9 Preview 7 for https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

---
[Associated WorkItem - 284277](https://dev.azure.com/msft-skilling/Content/_workitems/edit/284277)

**Comment by JusterZhu** [comment]
@wadepickett When using AspNetCore.SignalR.Client to write a client application with AOT (Ahead Of Time) compilation, issues may arise such as not being able to receive messages from the server. As for when AspNetCore.SignalR.Client.Core will support this, it would be best to keep an eye on official announcements from the ASP.NET Core team or check their GitHub repository for any updates on feature support and compatibility. You can also reach out to the community or file an issue on their GitHub page to get more specific information or potential workarounds.
I'm using .NET 9, and the code is as follows:
`  _connection = new HubConnectionBuilder()
                .WithUrl("http://localhost:5000/UpgradeHub")
                .Build();

            _connection.On<string, string>("11", (user, message) =>
            {
                Console.WriteLine($"{user}: {message}");
            });
            await _connection.StartAsync();`

**Comment by mobinseven** [comment]
> [@wadepickett](https://github.com/wadepickett) When using AspNetCore.SignalR.Client to write a client application, I encountered an issue where AOT publishing prevents receiving messages from the server.

I confirm this report as it happened to me. A simple working signalr code stops working when published by AOT flag.

**Comment by mobinseven** [comment]
@JusterZhu 
> When using AspNetCore.SignalR.Client to write a client application, I encountered an issue where AOT publishing prevents receiving messages from the server. 

You can solve this with these three steps for classes that are being processed by SignalR (they are either an input type or an output type):

1. Write a `JsonConverter` for them:

Assume this class:

```csharp

[JsonConverter(typeof(PointDataDtoConverter))]
public class PointDataDto
{
    public byte[] PointData { get; set; }
}
```
Which is used as output type of a signalr server function:
```csharp
public class ServerHub : Hub
{
    public async Task<PointDataDto> GetPointData() => await PointDataDtoGenerator();
}
```
Write a `JsonConverter` for it:

```csharp

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

public class PointDataDtoConverter : JsonConverter<PointDataDto>
{
    public override PointDataDto Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if(reader.TokenType != JsonTokenType.StartObject)
        {
            throw new JsonException();
        }

        var pointDataDto = new PointDataDto();

        while(reader.Read())
        {
            if(reader.TokenType == JsonTokenType.EndObject)
            {
                return pointDataDto;
            }

            if(reader.TokenType == JsonTokenType.PropertyName)
            {
                string propertyName = reader.GetString();
                reader.Read();

                if(propertyName == "PointData")
                {
                    string base64String = reader.GetString();
                    pointDataDto.PointData = Convert.FromBase64String(base64String);
                }
                else
                {
                    throw new JsonException();
                }
            }
        }

        throw new JsonException();
    }

    public override void Write(Utf8JsonWriter writer, PointDataDto value, JsonSerializerOptions options)
    {
        writer.WriteStartObject();

        writer.WritePropertyName("PointData");
        string base64String = Convert.ToBase64String(value.PointData);
        writer.WriteStringValue(base64String);

        writer.WriteEndObject();
    }
}


```
2. Write a `JsonSerializerContext` for them:
It is an empty class based on `JsonSerializerContext`. It must have `JsonSerializable` attributes of type of the class itself and its members.
```csharp
namespace System.Text.Json.Serialization;
[JsonSerializable(typeof(PointDataDto))]
[JsonSerializable(typeof(byte[]))]
public partial class PointDataDtoContext : JsonSerializerContext { }
```
3. Register the `JsonSerializerContext`:
```csharp
builder.Services.Configure<JsonHubProtocolOptions>(o =>
{
    o.PayloadSerializerOptions.TypeInfoResolverChain.Insert(1, PointDataDtoContext.Default);
});
```

Works as it should when compiling with aot enabled in dotnet 9.
