### ISSUE TITLE
Customizing scafolded item

### ISSUE THREAD

**Issue by saeednoruzi** [dotnet/AspNetCore.Docs#33060]
### Description

[Enter feedback here]
how can I customize the default template of scaffolded items such as view and  controllers to my  preferences

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/tools/dotnet-aspnet-codegenerator.md

### Document ID

754e1c4d-4742-a83b-7f2d-5dead439e569

### Article author

@tdykstra

**Comment by tdykstra** [comment]
This is outside the scope of this article, but see [this blog](https://anuraj.dev/blog/custom-scaffold-templates-in-asp-net-core/). You also might be able to get a helpful answer by posting to a support forum such as StackOverflow. GitHub Copilot provides the following guidance, but I haven't tried it myself, so I can't guarantee that it will work.

>To customize the default template of scaffolded items such as views and controllers in ASP.NET using the `dotnet-aspnet-codegenerator` tool, follow these steps:

>1. **Locate Default Templates**: First, find where the default templates are located on your system. They are typically found within the NuGet package directory. For example, on a Windows machine, they might be located in a path similar to `C:\Users\<YourUsername>\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\<Version>\Templates`.

>2. **Copy Default Templates**: Copy the templates you want to customize from their original location to your project. It's a good practice to create a specific folder within your project to store these templates, such as `Templates`.

>3. **Customize Templates**: Once you've copied the templates into your project, you can modify them according to your preferences. You can edit the Razor views (.cshtml files) or the controller templates (.cs files) as needed.

>4. **Use Custom Templates with dotnet-aspnet-codegenerator**: When running the `dotnet-aspnet-codegenerator` command, specify the path to your custom templates using the `-t` or `--template` option. For example, if you're generating a controller and you have customized controller templates, you would use a command like:

>```shell
>dotnet aspnet-codegenerator controller -name MyController -m MyModel -dc MyDbContext --relativeFolderPath Controllers ->-templatePath Templates/ControllerTemplates
>```

>In this command:
>- `-name` specifies the name of the controller.
>- `-m` specifies the model.
>- `-dc` specifies the DbContext.
>- `--relativeFolderPath` specifies where to place the generated controller within your project.
>- `--templatePath` specifies the path to your custom templates relative to the project directory.

>5. **Repeat for Other Scaffolded Items**: Repeat the customization process for other scaffolded items as needed, such as views. Ensure to use the appropriate option to specify the template path for each type of item you are scaffolding.

>By following these steps, you can customize the scaffolding templates used by `dotnet-aspnet-codegenerator` to better suit your project's needs and preferences.
