### ISSUE TITLE
Misleading part about ResourcesPath

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#33078]
### Description

There's a note
> Localization is resource path that can be set via [LocalizationOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.localizationoptions).

In section [SharedResources](https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0#shared-resources).

This is extremely misleading. =( It took me a while to udnerstand how things really work.

`ResourceManagerStringLocalizerFactory` has two [`Create`](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Localization/Localization/src/ResourceManagerStringLocalizerFactory.cs#L122) methods.
The one which accepts `Type` [is used inside `IStringLocalizer<T>`](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Localization/Abstractions/src/StringLocalizerOfT.cs#L26) which wraps the instance of `IStringLocalizer`

If you follow the code of `Create` method, you will see, that if `ResourcesPath` is not set, it [has no effect](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Localization/Localization/src/ResourceManagerStringLocalizerFactory.cs#L84) for `IStringLocalizer<T>`, that is resource files just need to be placed where `SharedResources` class is. Otherwise 'ResourePath` seem to be a path relative to the path of the class!
Look at [this comment](https://github.com/dotnet/aspnetcore/blob/90a622d4f3f377dcf4eabbbbb8765ba9d3e65415/src/Localization/Localization/src/ResourceManagerStringLocalizerFactory.cs#L88)

Here's how embedded resource is named in assembly:
![image](https://github.com/user-attachments/assets/95b3f5ca-aee6-4270-82dd-ab51ef649642)

Here's the part of the project:
![image](https://github.com/user-attachments/assets/c7b2d4c0-55b5-4b0b-a69c-fc6e83979d12)

And here's how class is defined:
```
namespace DutchVerbs.Spa.Xyz;

internal sealed class Strings
{
}
```

Look how name of the resource changes if I move resource files:
![image](https://github.com/user-attachments/assets/adfe296d-70bc-439b-9343-ec14cade7419)

![image](https://github.com/user-attachments/assets/34fbbf64-96fa-467c-bcfd-ca19c5965cc9)

In this case I indeed need to set `ResourcesPath = "Resources"`

It also means that combining the usage of both `IStringLocalizer` and `IStringLocalizer<T>` when resources are placed differently won't work.

The absence of `Strings` class affects how resources get named (no `Xyz` namespace anymore):
![image](https://github.com/user-attachments/assets/3bf52b1e-9faf-4023-87e0-48509b17808a)

![image](https://github.com/user-attachments/assets/bda06b46-dc1b-45bc-a204-9a37167a3bd0)

IMO, Xmldoc (api reference) part of `Localization` package is missing a lot of details. We should also push the devs to add more.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks for this analysis, @voroninp.

First on this bit ...

> IMO, Xmldoc (api reference) part of Localization package is missing a lot of details. We should also push the devs to add more.

That will need to be an issue on the product unit's repo at https://github.com/dotnet/aspnetcore/issues. It's a separate workflow from us, and they'll need to address it directly.

For the article ...

> In this case I indeed need to set ResourcesPath = "Resources"
>
> ... seem to be a path relative to the path of the class!

In this special case with the dummy class, I agree that it's misleading to point to the API docs. I'll need to clarify it.

> It also means that combining the usage of both `IStringLocalizer` and `IStringLocalizer<T>` when resources are placed differently won't work.

That's a limitation that I can also add to the text.

I'll try to address these as soon as I can 🏃‍♂️. Thanks for calling them out.

**Comment by guardrex** [comment]
@voroninp ... For ...

> It also means that combining the usage of both IStringLocalizer and IStringLocalizer<T> when resources are placed differently won't work.

Which one doesn't work?
