### ISSUE TITLE
UUF port: DI into controllers: More info on Configuration needed

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33073]
### Description

UUF Feedback tool port:

Customer Verbatim Feedback:
"I've been developing code for 40+ years and can't follow this article. Where does "Configuration" come from in this line of code: "services. Configure<SampleWebSettings>(Configuration);"? It's a class you created somewhere, but where????"

See [all open issues for this doc](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/mvc/controllers/dependency-injection.md

### Document ID

f9a790d8-f25b-0e1d-eb63-c8ed3ac518cf

### Article author

@ardalis

**Comment by wadepickett** [comment]
Set to P1 (to be resolved within 1-2 monthly sprints per LT.)

**Comment by wadepickett** [comment]
Tom, I assigned to you since you are listed as ms.author.

**Comment by tdykstra** [comment]
In this code, `Configuration` is a property of the `Startup` class that holds the application's configuration settings. It is of type `IConfiguration`, which is an interface provided by the .NET Core framework for accessing configuration data.

The `Configuration` property is initialized in the constructor of the `Startup` class. The constructor takes an `IConfiguration` object as a parameter, which is passed in by the ASP.NET Core runtime when the application starts. This `IConfiguration` object is typically built from various configuration sources, such as `appsettings.json`, environment variables, and command-line arguments.
