### ISSUE TITLE
Can we have more details for the note, please?

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#33077]
### Description

[Enter feedback here]
There's a note:
> Always set [DefaultThreadCurrentCulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentculture#system-globalization-cultureinfo-defaultthreadcurrentculture) and [DefaultThreadCurrentUICulture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.defaultthreadcurrentuiculture#system-globalization-cultureinfo-defaultthreadcurrentuiculture) to the same culture in order to use [IStringLocalizer](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizer) and [IStringLocalizer<T>](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizer-1).

This is nice, but it does not provide the explanation of **why**? String localizer should use `CurrentUICulture` exclusively, why does it need `CurrentCulture` as well?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @voroninp ... Yes, I think the NOTE should explain it.

First, let's cross-ref the source for the WASM culture provider ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs#L65

Here are the docs PR and PU issue cross-links related to this ...

* https://github.com/dotnet/AspNetCore.Docs/pull/24716
* https://github.com/dotnet/aspnetcore/issues/25296

Although the PU issue closed out on the reason from Jeff that ...

> "because Blazor WebAssembly is a UI framework, I would expect both CurrentCulture and CurrentUICulture to be the same"

I don't follow that reasoning. I wouldn't necessarily expect them to be the same.

I don't understand the thinking behind this line of the provider where only the `CurrentCulture` is used ...

https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/WebAssembly/src/Hosting/WebAssemblyCultureProvider.cs#L65

@hishamco ... Do you know why (or can you guess why) this limitation actually exists beyond that 'resources won't load properly'?

**Comment by voroninp** [comment]
Yes, indeed strange they are using `CurrentCulture` to load resources.

**Comment by voroninp** [comment]
We in our company started writing special comments with categories: `Decision`, `Hack`, `Assumptions`, etc.
We currently do not generated docs for them but we have plans to do so. I've seen many places in the sources of .NET where such comments would be precious and coud add valuable insights to the coumentation.

Inspired by this book https://www.oreilly.com/library/view/living-documentation-continuous/9780134689418/

**Comment by guardrex** [comment]
For that suggestion, it would go to 👉 https://github.com/MicrosoftDocs/feedback/issues.

**Comment by guardrex** [comment]
Received an update from Steve on this: He thinks this might be a bug. He's going to let me know if I should open a new issue on it or if the original PU issue that was closed should be re-opened for work.

In the meantime, I'll see about adding remarks on this when I reach this issue for work.

**Comment by voroninp** [comment]
What is PU?

**Comment by guardrex** [comment]
"product unit"

**Comment by hishamco** [comment]
I did write the note, but I think this is important for WebAssembly only to set the proper culture resources to be loaded, and no need to set that on the server

**Comment by guardrex** [comment]
Steve thinks it sounds like a bug. Either he'll re-open that issue from 2020, or I'll open a new one over there. I'll ping you on it either way so you can keep an 👁️ on it.

**Comment by guardrex** [comment]
I'll try to repro the behavior and give them a sample app for that PU issue :point_up: soon ... either today or tomorrow.

In the meantime, I'll try to resolve this issue for now by adding a cross-link to the PU issue.

Since I'm tracking on the PU issue, I'll see when/how they deal with it and open a new docs issue later for an additional update, which we hope will be to remove the notes and remark in passing that it is OK to set the current and current UI cultures to different values.
