### ISSUE TITLE
Remove Postman

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33085]
### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/policies.md

### Document ID

7089b376-949f-c1c6-c37a-5d8cc7ecf104

### Article author

@Rick-Anderson

---
[Associated WorkItem - 286115](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286115)

**Comment by wadepickett** [comment]
@Rick-Anderson: Is this a dupe of #33083 or different in some way?
