### ISSUE TITLE
Mr. 

### ISSUE THREAD

**Issue by Fapetuade** [dotnet/AspNetCore.Docs#33082]
### Description

[Enter feedback here]
Good afternoon sir/ma, I want to change my email ,old is sulaimanfapetu@gmail.com, new is sulaimanfapetuadewale@gmail.com , thanks 

### Page URL

https://learn.microsoft.com/en-ca/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/azure-iis-errors-reference.md

### Document ID

daf78291-6119-23c6-e1b1-0606a74bd510

### Article author

@Rick-Anderson

**Comment by guardrex** [comment]
@Fapetuade ... This is not the correct place to open issues such as this one and the last one that you opened. This is a documentation repository for the ASP.NET Core documentation. Please only open issues here for the ASP.NET Core documentation. We aren't able to assist with any other requests.
