### ISSUE TITLE
Remove Postman across all team repos

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33083]
Do a sweep for postman across all .NET/ASP.NET/C++ team repos and refer to current reporting available.
Notify stakeholders what was completed per repo and if anything is outstanding for any reason and update reports tracking.
Update linked ADO parent that tracks across the org.

[Instructions and latest reports here](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1720727481062?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1720727481062&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1720727481062)

See more details in the generated ADO tracking item lined below:

- [x] Fix two topics in Odata-docs repo #33326 and update the tracking spreadsheet.  PR https://github.com/MicrosoftDocs/OData-docs/pull/323

- [x] Fix yaml reference for community standup video in show-pr #33327 and update the tracking spreadsheet.

- [x] Verify all other fixes are in and update the tracking spreadsheet. (done by Wade)

---
[Associated WorkItem - 286116](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286116)

**Comment by wadepickett** [comment]
@Rick-Anderson, in Odata-docs repo there are two docs you are listed as owner for that had "Postman" in them:

- https://github.com/MicrosoftDocs/odata-docs/Odata-docs/webapi/first-odata-api.md	Hits: Postman	Post some data to the web API app, using a tool such as [HTTP REPL](/aspnet/core/web-api/http-repl) or [Postman]

- https://github.com/MicrosoftDocs/odata-docs/Odata-docs/webapi/odata-expand.md	Hits: Postman	This tutorial uses Postman to test the web API.  AND * Install [Postman](https://www.getpostman.com/apps)    AND * Start Postman.

Do you want to handle those?  It didn't occur to me earlier to search through that repo.  Sorry to just realize they were there.

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson, in the Odata-docs repo there are two docs you are listed as owner for that had "Postman" in them:
> 
> * https://github.com/MicrosoftDocs/odata-docs/Odata-docs/webapi/first-odata-api.md	Hits: Postman	Post some data to the web API app, using a tool such as [`HTTP REPL](/aspnet/core/web-api/http-repl) or [Postman]`
> * https://github.com/MicrosoftDocs/odata-docs/Odata-docs/webapi/odata-expand.md	Hits: Postman	This tutorial uses Postman to test the web API.  AND * Install `[Postman](https://www.getpostman.com/apps)`    AND * Start Postman.
> 
> Do you want to handle those? It didn't occur to me earlier to search through that repo. Sorry to just realize they were there.

Create an issue in this repo for them and assign to me for the Aug sprint.

**Comment by wadepickett** [comment]
Note to self, the two odata files are being handled in this PR https://github.com/MicrosoftDocs/OData-docs/pull/323

I don't have write access to link back so I'll watch for the PR to merge and close.

**Comment by wadepickett** [comment]
Closing as fixed so I don't forget this one.  We are waiting for a merge by repo owners of https://github.com/MicrosoftDocs/OData-docs/pull/323 but it has gone through an initial review.
