### ISSUE TITLE
Slightly confusing documentation

### ISSUE THREAD

**Issue by codebuzz** [dotnet/AspNetCore.Docs#33097]
### Description

[Enter feedback here]
The documentation and samples are great, but there is a confusing message highlighted in yellow at the top. Message says that samples use pbkdf2 which should not be used and instead password hasher should be used. However, [source code ](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/Extensions.Core/src/PasswordHasher.cs) for password hasher shows that it uses pbkdf2 internally and causes confusion whether we should use the provided password hasher or not. Please let me know if i am missing something here. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/data-protection/consumer-apis/password-hashing.md

### Document ID

61e65ca8-4008-ed27-7254-93385a9ed6d7

### Article author

@Rick-Anderson

---
[Associated WorkItem - 286793](https://dev.azure.com/msft-skilling/Content/_workitems/edit/286793)

**Comment by Rick-Anderson** [comment]
It says:

The following code shows how to use KeyDerivation.Pbkdf2 to generate a shared secret key. It should not be used to hash a password ***for storage in a datastore.***
