### ISSUE TITLE
Can you close the results pane of the .http file editor in Visual Studio?

### ISSUE THREAD

**Issue by lozh** [dotnet/AspNetCore.Docs#33116]
### Description

When you run a request from the .http editor, it opens a new pane in the tab for the results. Is there any way to close this pane?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/test/http-files.md

### Document ID

26f1374f-556a-35fc-cc42-b8911746db80

### Article author

@tdykstra

**Comment by tdykstra** [comment]
If you close the file and reopen it, it opens without the results pane showing. The pane appears only after you send a request. If you want a more direct route to close the results pane, I recommend submitting a suggestion to the Visual Studio Developer Community. From the menu select **Help** > **Send Feedback** > **Suggest a Feature**.
