### ISSUE TITLE
Injecting ApplicationDbContext is bad practice

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/AspNetCore.Docs#33120]
### Description

Injecting DbContext into blazor server pages is bad practice as it remains for the life of the user session, becomes stale, and generally leaks memory.

The source code shows

```
@inject ApplicationDbContext AppDbContext

<QuickGrid Items="@AppDbContext.People">
    ...
</QuickGrid>
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/quickgrid.md

### Document ID

564e71e3-82ed-ce23-4f9f-a00a58734a62

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @mrpmorris ... This is a known issue and being tracked by another work item.

**Comment by guardrex** [comment]
... and btw ... It will be fixed by EOD.
