### ISSUE TITLE
IEmailSender required with MapIdentityApi<IdentityUser>

### ISSUE THREAD

**Issue by zabpetrus** [dotnet/AspNetCore.Docs#33128]
### Description

hello! I tried to do the tutorial on the page, but it failed at the app.MapIdentityApi<IdentityUser>() line with the error: System.InvalidOperationException: 'Cannot resolve 'Microsoft.AspNetCore.Identity.IEmailSender`1[Microsoft.AspNetCore.Identity.IdentityUser]' from root provider because it requires scoped service 'Microsoft.AspNetCore.Identity.UI.Services.IEmailSender'.'

I tried to implement what was on the page
[https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-8.0&tabs=visual-studio](
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-8.0&tabs=visual-studio)
but SendGrid requires you to have a active website. I tried to create a website on InfinityFree, but they blocked me because of that, so I can't use SendGrid. I wanted an option that wouldn't make me feel embarrassed, because SendGrid doesn't offer it. I wanted an option that simulates the Email sending functionality or that allows you to configure it in IIS.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization.md

### Document ID

137d4b94-7b26-3911-b22d-42c754a95fc1

### Article author

@tdykstra

---
[Associated WorkItem - 288937](https://dev.azure.com/msft-skilling/Content/_workitems/edit/288937)

**Comment by tdykstra** [comment]
Here is an implementation of IEmailSender that simulates sending email by writing logs. You just need to set the namespace to the same as what you have in Program.cs.

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/EmailSender.cs

Let me know if this helps.

**Comment by ParsaMehdipour** [comment]
> Here is an implementation of IEmailSender that simulates sending email by writing logs. You just need to set the namespace to the same as what you have in Program.cs.
> 
> 
> 
> https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/EmailSender.cs
> 
> 
> 
> Let me know if this helps.

@zabpetrus 

Don't forget to register the IEmailSender service in program.cs

**Comment by tdykstra** [comment]
> @zabpetrus
> 
> Don't forget to register the IEmailSender service in program.cs

Yes, thanks, example of that is [here](https://github.com/dotnet/AspNetCore.Docs/blob/89ecfe6866885aa648c389c4b937e729fd3c352e/aspnetcore/security/authentication/identity-api-authorization/8samples/APIforSPA/Program.cs#L41).

**Comment by AndiRudi** [comment]
Something is odd here. `IEmailSender` should not require a transient scope, shouldn't? For example my implementation of the `IEmailSender` is a bit more sophisticated and uses a `DbContext` which is usually also scoped. So that won`t work. Not sure if this is the right place to flag this. But basically it means I cannot use `MapIdentityApi`...
