### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NetCito** [dotnet/AspNetCore.Docs#33136]
### Description

The "YouTube videos" link in the "Reliable web app patterns" paragraph is broken. When you click the link it shows the attached image:
![Screenshot 2024-07-22 101200](https://github.com/user-attachments/assets/16e98c94-f5bc-46ee-a914-088a983fa42d)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/details.md

### Document ID

1bf4792d-dab4-e03d-2021-3dcdcaff6a0f

### Article author

@wadepickett

---
[Associated WorkItem - 291900](https://dev.azure.com/msft-skilling/Content/_workitems/edit/291900)

**Comment by wadepickett** [comment]
@NetCito, thanks for letting us know!   It appears that the video has moved to here: https://www.youtube.com/watch?v=tU2kYzB3noM&list=PLI7iePan8aH54gIDJquV61dE3ENyaDi3Q

We will update the link.
