### ISSUE TITLE
Stop using AI for technical documentation

### ISSUE THREAD

**Issue by JeroMiya** [dotnet/AspNetCore.Docs#33146]
### Description

I know it says that a human has reviewed the AI output of the documentation, I have a hard time trusting any AI generated technical documentation. I don't want to spend hours trying to figure out why the provided sample code doesn't work when it's because some LLM hallucinated the code from who knows what training data. Already there has been an overall decline in the quality of technical documentation on learn.microsoft.com, but the introduction of AI generated docs, with all due respect, represents a major loss of credibility above and beyond that. Please consider changing the policy to stop using AI generated documentation, sample code, etc... on learn.microsoft.com and bring back human (and only human) writers for all technical documentation and sample code.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0#use-health-checks-routing

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md

### Document ID

52d8efc9-a336-71d9-6d90-98173cbf6bf4

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thanks for contacting us. GitHub Copilot is just a tool; it does more for us than a tool like Intellisense has been doing until now, but humans use the tool and review everything it helps with.
