### ISSUE TITLE
Mention about lang attribute.

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#33143]
### Description

Hello, and sorry for the annoynace.
I belive there's one suttle but important thing missing in the docs.

The tmplate (at least for standalone static blazor wasm) creates `index.html` file which contains:
```
<!DOCTYPE html>
<html lang="en">
```

It's worth mentioning that updating the value of `lang` attribute is a good idea because it's [used by accessibility tools](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang#accessibility_concerns).
```
<script>
  // update htlm's lang attribute
  document.documentElement.lang = 'en-US';

  Blazor.start({
    applicationCulture: 'en-US'
  });
</script
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @voroninp ... Thanks for the issue. I agree, and it's easy enough to mention it (and show that example :point_up:) for the static guidance. The question is whether or not the product unit wants to also provide guidance on dynamically changing the value via JS interop for the dynamic approaches in the article ... *which does work BTW* 🎉. I'll ask Mackinnon what he thinks about it.

**Comment by guardrex** [comment]
It was mentioned here ... https://github.com/dotnet/aspnetcore/issues/51181 ... along with a few other complaints.

**Comment by SteveSandersonMS** [comment]
I have no objection to *mentioning* it, but in general I'd say it's not the goal of the ASP.NET Core / Blazor docs to document everything about HTML. Other sources should be used to learn about HTML or DOM APIs in general. This is true even for providing advice about accessibility topics (assuming they aren't Blazor-specific, which this one isn't).

As such I don't think there's any particular reason to document that you can use Blazor's JS interop to set `document.documentElement.lang`. As long as we have documented that you can use JS interop to call arbitrary JS code, then the reader can understand that from there they can invoke any DOM APIs, which would include this.

**Comment by guardrex** [comment]
I'll limit remarks to mentioning it.

**Comment by voroninp** [comment]
@SteveSandersonMS it's a fair point.
But on the other hand, it's not obvious whether setting the culture inside Blazor will have immediate effect on this attribute.

**Comment by guardrex** [comment]
I think it can be stated at the end of the sentence that I plan to construct, which can end something like this ...

> ..., which can be set via JS interop.

We'll see on the PR, and I hope to reach this soon. However, I do have a lot of P2 issues to address, so it might take longer than I think to reach this 🏃‍♂️.

**Comment by SteveSandersonMS** [comment]
> But on the other hand, it's not obvious whether setting the culture inside Blazor will have immediate effect on this attribute.

I accept it's possible someone might wonder if setting the .NET thread culture will change the `document.documentElement.lang` value, but we never claim anywhere that it does, and we can't document everything that *doesn't* happen :)

**Comment by voroninp** [comment]
@SteveSandersonMS, it's just a mental model of the developer spoiled by .NET where one usually has exactly one setting to get the required behavior or when everything works out of the box. ;-) Things are thought out.

I am so spoiled, that I keep asking myself why guys did not include msbuild functionality to update base tag when publishing static blazor wasm. =D

P.S. Thanks for the very nice framework.
