### ISSUE TITLE
Debugger support change for 8.0

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#33168]
### Description

@maraf ... The section was added on #32287 ...

https://github.com/dotnet/AspNetCore.Docs/pull/32287/files

That's only spot where the article discusses the app's debug, release, or custom configuration.

Do we need to keep that section because a dev will still need to set `<DebuggerSupport>` for non-Debug/non-Release custom configs? If that's the change, we keep the section but change one line.

From ...

> By default, the Blazor framework \*disables\* debugger support for all non-Debug configurations. To enable debugger support for a non-Debug configuration, add a \`\<DebuggerSupport>\` property to the app's project file.

... to ...

> By default, the Blazor framework \*disables\* debugger support for all non-Debug/non-Release custom configurations. To enable debugger support for a custom configuration, add a \`\<DebuggerSupport>\` property to the app's project file.

While I'm at it, I'll also remove 🔪 the "For more information" line.

Alternatively if the configuration is irrelevant now, then I just need to 🔪 the entire section out of the doc.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/debug.md

### Document ID

4d06e565-282d-6387-aa90-cb2c2986d35a

### Article author

@guardrex

**Comment by maraf** [comment]
> Do we need to keep that section because a dev will still need to set <DebuggerSupport> for non-Debug/non-Release custom configs?

No, we should remove `DebuggerSupport` as that won't be needed anymore

**Comment by guardrex** [comment]
Very well ... I'll take care of it within a few hours. *I'm buried in Blazor Hybrid code at the moment.* ⛰️⛏️😅

**Comment by maraf** [comment]
No rush, the fix not released yet
