### ISSUE TITLE
Missing Step in Creating SignalR App

### ISSUE THREAD

**Issue by Wayne42** [dotnet/AspNetCore.Docs#33161]
### Description

The following Snippet seems to be missing in the documentation:
 
`app.Run();`

It should be mentioned somewhere in the step **"Configure the server".** 

### Page URL

https://learn.microsoft.com/de-de/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/signalr-typescript-webpack.md

### Document ID

1cee43b4-b672-e480-3e26-72e08a6c2d77

### Article author

@ssougnez

**Comment by BrennanConroy** [comment]
The tutorial is telling you what modifications to make to an app that was created from a template. `app.Run();` should already exist in the template and isn't needed when telling you what modifications to make.

See the beginning of the docs where it says
> To create a new ASP.NET Core web app:
> Use the File > New > Project menu option and choose the ASP.NET Core Empty template. Select Next.

**Comment by Wayne42** [comment]
You are right, I missed that part and created the wrong type of project. 
Thank you very much for your quick and kind response :)
