### ISSUE TITLE
Web2FA Sample - The namespace 'Web2FA.Services' already contains a definition for 'AuthMessageSender'

### ISSUE THREAD

**Issue by MikeOtown** [dotnet/AspNetCore.Docs#33164]
Build error

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0101	The namespace 'Web2FA.Services' already contains a definition for 'AuthMessageSender'	Web2FA	C:\temp\AspNetCore.Docs-main\aspnetcore\security\authentication\2fa\sample\Web2FA\Services\MessageServices_ASPSMS.cs	9	Active

**Comment by guardrex** [comment]
Hello @MikeOtown ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article that goes with this code. Use of the form adds metadata to the GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by guardrex** [comment]
Also, it looks like that's from a depreciated framework. The current version of the article is ...

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-8.0
