### ISSUE TITLE
EF Core samples: Add a way to update Enrollment Data when editing a Student Record

### ISSUE THREAD

**Issue by Amondale** [dotnet/AspNetCore.Docs#33173]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**
There is a walkthrough that details many-many relationship of Instructor-Course-Enrollment (and Instructor-Department) but for Student-Enrollment-Course this would be a simple add and represents a headscratcher to me when I've completed the Razor and MVC EFCore walkthroughs. 

Kudos for adding SQLite3 support to the walkthroughs BTW, really adds simplicity when building on non-Windows platforms.

- Explain why this topic is needed.
"Black Hole" that I solved by scaffolding around the Enrollment table

- Suggest a location in the Table of Contents.
Somewhere around Part 6/7 in the Razor EFCore walkthrough

- Write an abstract. In one **short** paragraph, describe what this topic will cover.
Unification of the sample app by closing the circle of important missing functionality

- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
<img width="788" alt="StudentDetailsCouldBeEditableWithEnrollment" src="https://github.com/user-attachments/assets/9b777bdc-7324-4e7d-9743-ffbec2f10678">

**Comment by Rick-Anderson** [comment]
This tutorial is to get you started on EF with ASP.NET Core. We won't be adding any new scenarios.
