### ISSUE TITLE
Revise "Choose a hybrid solution" heading to avoid confusion with Blazor Hybrid

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#33188]
### Description

The last section in this doc is titled "Choose a hybrid solution: ASP.NET Core MVC or Razor Pages plus Blazor", which risks some confusion with Blazor Hybrid. Initially when I saw this section, I thought it was going to be about using Blazor Hybrid, but it's actually about combining multiple web UI technologies. 

Suggested new heading: "Combine multiple web UI solutions: ASP.NET Core MVC or Razor Pages plus Blazor".

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md

### Document ID

68d5aab0-63ce-de7a-0c56-341c2eef623d

### Article author

@wadepickett

---
[Associated WorkItem - 289451](https://dev.azure.com/msft-skilling/Content/_workitems/edit/289451)

**Comment by wadepickett** [comment]
This was accidentally reopened. It was fixed with my pr #33189, verified, re-closing.
