### ISSUE TITLE
Suggestion ASP0018 is wrong and cannot be resolved

### ISSUE THREAD

**Issue by ygoe** [dotnet/AspNetCore.Docs#33191]
### Description

I have this code:

```cs
var builder = WebApplication.CreateSlimBuilder(args);
var app = builder.Build();
app.MapGet("/topic/{topic}", async context =>
{
    string topic = (string)context.GetRouteValue("topic")!;
    string? address = context.Connection.RemoteIpAddress?.ToString();
    // ...
}
```

The part `{topic}` is underlined with the suggestion "ASP0018: Unused route parameter 'topic'". As you can see from the code, that's not correct. The referenced documentation suggests to resolve this by adding the parameter to the handler delegate. But that's incompatible with my existing code. And I can't see any method overload that would accept such parameters.

Is the documentation wrong or the product (analyzer or ASP.NET API) broken? Things aren't aligned here.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0018?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0018.md

### Document ID

14d6bdfb-c7f2-b1c6-4e7b-3252b0e65530

### Article author

@tdykstra

---
[Associated WorkItem - 291123](https://dev.azure.com/msft-skilling/Content/_workitems/edit/291123)

**Comment by guardrex** [comment]
Should the pattern be the following? It will silence that suggestion.

```csharp
app.MapGet("/topic/{topic}", async (HttpContext context, string topic) =>
{
    var address = context.Connection.RemoteIpAddress?.ToString();
    // Use "topic" directly now.
    //...
});
```

**Comment by tdykstra** [comment]
@captainsafia Should this be documented as another scenario where ASP0018 is incorrectly generated?

**Comment by captainsafia** [comment]
> The referenced documentation suggests to resolve this by adding the parameter to the handler delegate. But that's incompatible with my existing code. 

Out of curiousity, can you explain why this is incompatible with your current code? I'd expect that you can make the following delta and get the same results:

```diff
var builder = WebApplication.CreateSlimBuilder(args);
var app = builder.Build();
- app.MapGet("/topic/{topic}", async context =>
+ app.MapGet("/topic/{topic}", async (context, topic) =>
{
-   string topic = (string)context.GetRouteValue("topic")!;
    string? address = context.Connection.RemoteIpAddress?.ToString();
    // ...
}
```

**Comment by ygoe** [comment]
Oh, that works. I was looking at the IntelliSense documentation and didn't see an overload that would accept additional arguments. Maybe it just wasn't shown. ASP.NET Core does strange things after all. Still I wouldn't be able to find that from the documentation.

**Comment by captainsafia** [comment]
> Oh, that works. I was looking at the IntelliSense documentation and didn't see an overload that would accept additional arguments. 

We do have a feature in route tooling that provides autocompletions if you have the argument in the route parameter. It's documented [in this blog post](https://devblogs.microsoft.com/dotnet/aspnet-core-route-tooling-dotnet-8/#autocomplete-of-parameter-and-route-names).

If it is not working for you, it might indicate that there is an issue with the implementation.

**Comment by ygoe** [comment]
I think I was looking more at the list of overloads for `MapGet` and couldn't find anything relevant in there.
