### ISSUE TITLE
IDistributedCache not recommended statement

### ISSUE THREAD

**Issue by johnwc** [dotnet/AspNetCore.Docs#33218]
### Description

The last paragraph states that IDistributedCache not recommended. With the release of HybridCache, is that recommended?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/output.md

### Document ID

cb423d54-ee93-6dfd-87bb-ed79dff8b7b6

### Article author

@tdykstra

**Comment by tdykstra** [comment]
The statement about IDistributedCache not being recommended applies to Output caching, not to HybridCache. It still applies to Output caching.

cc: @sebastienros
