### ISSUE TITLE
I'm confused as to what I should put into the App.razor file

### ISSUE THREAD

**Issue by Rod-at-DOH** [dotnet/AspNetCore.Docs#33216]
### Description

I'm following along in the *Integrate ASP.NET Core Razor components into ASP.NET Core apps* training so I can learn how to incorporate Blazor components into a Razor and MVC application. Early in the tutorial the instructions said I was to create an App.razor file in the Components folder at the root level of the Razor/MVC application. I did that, then entered the following as instructed:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="AspNetCoreWithWindowsAuth.styles.css" /> 
    <HeadOutlet />
</head>

<body>
    <Routes />
    <script src="_framework/blazor.web.js"></script>
</body>

</html>
```

Now I'm about halfway through the tutorial, at the *Add an non-operational (no-op) App component to the project* section. The sub-section *Use non-routable components in pages or views* says:

> Add an non-operational (no-op) App component to the project.
> 
> Components/App.razor:

with just this code:

```html
@* No-op App component *@
```

I am confused. Do I wipe out what was previously instructed to put into App.razor? Or is this NOOP change only meant to be used, if I have non-routable components in pages or views? For the purpose of learning how to incorporate Blazor components into a Razor/MVC app, I created a new app that included Windows Authentication, because I've got include Windows Authentication for this application. I'm using .NET 8 for this application.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#use-non-routable-components-in-pages-or-views

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/integration.md

### Document ID

d7e39bbc-cd54-92aa-4997-f9dd39dd6ef3

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Rod-at-DOH ...

That section ([*Use non-routable components in pages or views*](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#use-non-routable-components-in-pages-or-views)) is only for integrating components into pages/views with the Component Tag Helper. I need to make that clearer at the top of that section and perhaps at the top of the article.

If you need routable components, you did the right thing following the opening guidance in the article. Let me know if you adopt the non-Component Tag Helper approach.

Apart from that, it looks like the [*Use routable components*](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#use-routable-components) section should've been removed from the 8.0 and later version of the article when the new guidance was added at the top of the article.

I'll work on the article to improve these aspects. Leave this issue open. It will close when the PR merges later. Thanks for writing in about the article.

**Comment by Rod-at-DOH** [comment]
Thank you, @guardrex, for your feedback. I'll skip ahead to the `Razor Pages` subsection and do that. I love Git, as I can create new branches to experiment. If it all goes up in flames, I can blow the branch away and go back to a "last known good".

Thank you again for your work on the documentation. It means a **LOT** to me!!
