### ISSUE TITLE
CS Effort:  IIS docs Repos: ROPC [TRIAGE STAGE]

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33228]
## Password  74
- [Use the Database Manager](https://docs.microsoft.com/en-us/iis/extensions/database-manager/use-the-database-manager)
- [Database Manager for Hosters](https://docs.microsoft.com/en-us/iis/web-hosting/web-server-for-shared-hosting/database-manager-for-hosters)
- [Planning Step 3: Plan Data Source Settings](https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/planning-step-3-plan-data-source-settings)
- [DatabaseProvider.CalculateConnectionString Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-calculateconnectionstring-method-microsoft-web-management-databasemanager)
- [ConnectionStringsSection Class](https://docs.microsoft.com/en-us/iis/wmi-provider/connectionstringssection-class)
- [Configuring Step 3: Configure Data Source Settings](https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/configuring-step-3-configure-data-source-settings)
- [ConnectionStringSettings Class](https://docs.microsoft.com/en-us/iis/wmi-provider/connectionstringsettings-class)
- [DatabaseProvider.ConnectionStringArguments Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-connectionstringarguments-property-microsoft-web-management-databasemanager)
- [DatabaseProvider.GetServerTypes Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getservertypes-method-microsoft-web-management-databasemanager)
- [Configuring Step 2: Configure ASP.NET Settings](https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/configuring-step-2-configure-asp-net-settings)
- [DatabaseProvider Class (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-class-microsoft-web-management-databasemanager)
- [DatabaseProvider.ExecuteQuery Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-executequery-method-microsoft-web-management-databasemanager)
- [IDbViewManager.GetViews Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-getviews-method-microsoft-web-management-databasemanager)
- [DatabaseProvider.GetDatabaseInfo Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getdatabaseinfo-method-microsoft-web-management-databasemanager)
- [DatabaseProvider.TestConnection Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-testconnection-method-microsoft-web-management-databasemanager)
- [IDbStoredProcedureManager.GetStoredProcedureParameters Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedureparameters-method-microsoft-web-management-databasemanager)
- [IDbTableManager.GetTableInfo Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-gettableinfo-method-microsoft-web-management-databasemanager)
- [IDbTableManager.CreateTable Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-createtable-method-microsoft-web-management-databasemanager)
- [Web Deploy error codes - Internet Information Services](https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/iis/deployment-migration/web-deploy-error-codes)
- [Verifying the Developer Experience - ASP.NET](https://docs.microsoft.com/en-us/iis/web-hosting/verifying-the-deployment/verifying-the-developer-experience-aspnet)
- [IDbStoredProcedureManager.GetStoredProcedures Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedures-method-microsoft-web-management-databasemanager)
- [ConnectionArgument.Name Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-name-property-microsoft-web-management-databasemanager)
- [IDbTableManager.GetTables Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-gettables-method-microsoft-web-management-databasemanager)
- [IDbBackupManager.CreateBackup Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbbackupmanager-createbackup-method-microsoft-web-management-databasemanager)
- [IDbTableManager.DropTable Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-droptable-method-microsoft-web-management-databasemanager)
- [ConnectionArgument.Value Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-value-property-microsoft-web-management-databasemanager)
- [ConnectionArgument.DefaultValue Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-defaultvalue-property-microsoft-web-management-databasemanager)
- [IDbStoredProcedureManager.GetStoredProcedureCreateStatement Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedurecreatestatement-method-microsoft-web-management-databasemanager)
- [IDbTableManager.EditTable Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-edittable-method-microsoft-web-management-databasemanager)
- [IDbViewManager.DropView Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-dropview-method-microsoft-web-management-databasemanager)
- [IDbTableManager.GetPrimaryKey Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-getprimarykey-method-microsoft-web-management-databasemanager)
- [IDbViewManager.CreateView Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-createview-method-microsoft-web-management-databasemanager)
- [DatabaseProvider.GetDatabaseHostName Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getdatabasehostname-method-microsoft-web-management-databasemanager)
- [ConnectionArgument.IsRequired Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-isrequired-property-microsoft-web-management-databasemanager)
- [Application Pool Identities and SQL Server Express](https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities-and-sql-server-express)
- [ConnectionArgument Class (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-class-microsoft-web-management-databasemanager)
- [IDbCustomBackupRestoreManager.ListBackups Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbcustombackuprestoremanager-listbackups-method-microsoft-web-management-databasemanager)
- [DatabaseProvider Methods (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-methods-microsoft-web-management-databasemanager)
- [Export a Package through IIS Manager](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/export-a-package-through-iis-manager)
- [SqlCacheDependencyDatabase Class](https://docs.microsoft.com/en-us/iis/wmi-provider/sqlcachedependencydatabase-class)
- [Building a Web Deploy Package from Visual Studio 2010](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/building-a-web-deploy-package-from-visual-studio-2010)
- [IDbRestoreManager.RestoreBackup Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbrestoremanager-restorebackup-method-microsoft-web-management-databasemanager)
- [IDbStoredProcedureManager.DropProcedure Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-dropprocedure-method-microsoft-web-management-databasemanager)
- [ConnectionArgument.IsPassword Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-ispassword-property-microsoft-web-management-databasemanager)
- [PowerShell scripts for automating Web Deploy setup](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/powershell-scripts-for-automating-web-deploy-setup)
- [Import a Package through IIS Manager](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/import-a-package-through-iis-manager)
- [APPL_PHYSICAL_PATH Server Variable on Windows Vista RTM](https://docs.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/applphysicalpath-server-variable-on-windows-vista-rtm)
- [Table.CreateDate Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/table-createdate-property-microsoft-web-management-databasemanager)
- [Table.Schema Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/table-schema-property-microsoft-web-management-databasemanager)
- [Table.Name Property (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/table-name-property-microsoft-web-management-databasemanager)
- [APPL_PHYSICAL_PATH Server Variable on Windows Vista RTM](https://docs.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/applphysicalpath-server-variable-on-windows-vista-rtm)
- [IDbViewManager.CreateView Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-createview-method-microsoft-web-management-databasemanager)
- [Introduction to Web Deploy](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/introduction-to-web-deploy)
- [IDbStoredProcedureManager.GetStoredProcedureCreateFromExistingStatement Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedurecreatefromexistingstatement-method-microsoft-web-management-databasemanager)
- [Configuring FTP with .NET Membership Authentication in IIS 7](https://docs.microsoft.com/en-us/iis/publish/using-the-ftp-service/configuring-ftp-with-net-membership-authentication-in-iis-7)
- [Web Deploy PowerShell Cmdlets](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/web-deploy-powershell-cmdlets)
- [IDbTableDataManager.DeleteRow Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtabledatamanager-deleterow-method-microsoft-web-management-databasemanager)
- [IDbTableDataManager.EditRow Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtabledatamanager-editrow-method-microsoft-web-management-databasemanager)
- [IDbStoredProcedureManager.GetStoredProcedureExecStatement Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedureexecstatement-method-microsoft-web-management-databasemanager)
- [IDbTableDataManager.GetData Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtabledatamanager-getdata-method-microsoft-web-management-databasemanager)
- [Run SQL Server stored procedures from an ASP Page - Internet Information Services](https://docs.microsoft.com/en-us/troubleshoot/developer/webapps/iis/active-server-pages/run-sql-server-stored-procedures-asp-page)
- [IDbTableDataManager.DeleteRow Method (Microsoft.Web.Management.DatabaseManager)](https://docs.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtabledatamanager-deleterow-method-microsoft-web-management-databasemanager)
- [Tools and Utilities Questions](https://docs.microsoft.com/en-us/iis/web-hosting/frequently-asked-questions-faq/tools-and-utilities-questions)
- [Feature to Configuration Reference](https://docs.microsoft.com/en-us/iis/get-started/planning-your-iis-architecture/feature-to-configuration-reference)
- [SessionStateSection Class](https://docs.microsoft.com/en-us/iis/wmi-provider/sessionstatesection-class)
- [Using Custom Rewrite Providers with URL Rewrite Module](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/using-custom-rewrite-providers-with-url-rewrite-module)
- [Delegated Administration](https://docs.microsoft.com/en-us/iis/web-hosting/web-server-for-shared-hosting/delegated-administration)
- [Use the Web Deployment Tool](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/use-the-web-deployment-tool)
- [Using Classic ASP with Microsoft Access Databases on IIS](https://docs.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/using-classic-asp-with-microsoft-access-databases-on-iis)
- [Planning Step 2: Plan ASP.NET Settings](https://docs.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/planning-step-2-plan-asp-net-settings)
- [ConfigurationSectionWithCollection Class](https://docs.microsoft.com/en-us/iis/wmi-provider/configurationsectionwithcollection-class)
- [CollectionElement Class](https://docs.microsoft.com/en-us/iis/wmi-provider/collectionelement-class)
- [Create an FTP Authentication Provider with Dynamic IP Restrictions](https://docs.microsoft.com/en-us/iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-authentication-provider-with-dynamic-ip-restrictions)
- [Web Deploy Parameterization](https://docs.microsoft.com/en-us/iis/publish/using-web-deploy/web-deploy-parameterization)

## Connection string 60

- [ ] [connectionstringssection class](https://learn.microsoft.com/en-us/iis/wmi-provider/connectionstringssection-class)
- [ ] [configuring step 3 configure data source settings](https://learn.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/configuring-step-3-configure-data-source-settings)
- [ ] [connectionstringsettings class](https://learn.microsoft.com/en-us/iis/wmi-provider/connectionstringsettings-class)
- [ ] [databaseprovider connectionstringarguments property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-connectionstringarguments-property-microsoft-web-management-databasemanager)
- [ ] [databaseprovider getservertypes method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getservertypes-method-microsoft-web-management-databasemanager)
- [ ] [configuring step 2 configure asp net settings](https://learn.microsoft.com/en-us/iis/application-frameworks/scenario-build-an-aspnet-website-on-iis/configuring-step-2-configure-asp-net-settings)
- [ ] [databaseprovider class MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-class-microsoft-web-management-databasemanager)
- [ ] [databaseprovider executequery method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-executequery-method-microsoft-web-management-databasemanager)
- [ ] [idbviewmanager getviews method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-getviews-method-microsoft-web-management-databasemanager)
- [ ] [databaseprovider getdatabaseinfo method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getdatabaseinfo-method-microsoft-web-management-databasemanager)
- [ ] [databaseprovider testconnection method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-testconnection-method-microsoft-web-management-databasemanager)
- [ ] [idbstoredproceduremanager getstoredprocedureparameters method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedureparameters-method-microsoft-web-management-databasemanager)
- [ ] [idbtablemanager createtable method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-createtable-method-microsoft-web-management-databasemanager)
- [ ] [web deploy error codes](https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/iis/deployment-migration/web-deploy-error-codes)
- [ ] [verifying the developer experience aspnet](https://learn.microsoft.com/en-us/iis/web-hosting/verifying-the-deployment/verifying-the-developer-experience-aspnet)
- [ ] [idbstoredproceduremanager getstoredprocedures method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedures-method-microsoft-web-management-databasemanager)
- [ ] [connectionargument name property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-name-property-microsoft-web-management-databasemanager)
- [ ] [idbtablemanager gettables method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-gettables-method-microsoft-web-management-databasemanager)
- [ ] [idbbackupmanager createbackup method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbbackupmanager-createbackup-method-microsoft-web-management-databasemanager)
- [ ] [idbbackupmanager createbackup method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbbackupmanager-createbackup-method-microsoft-web-management-databasemanager)
- [ ] [idbtablemanager droptable method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-droptable-method-microsoft-web-management-databasemanager)
- [ ] [connectionargument value property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-value-property-microsoft-web-management-databasemanager)
- [ ] [connectionargument defaultvalue property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-defaultvalue-property-microsoft-web-management-databasemanager)
- [ ] [idbstoredproceduremanager getstoredprocedurecreatestatement method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedurecreatestatement-method-microsoft-web-management-databasemanager)
- [ ] [idbtablemanager edittable method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-edittable-method-microsoft-web-management-databasemanager)
- [ ] [idbviewmanager dropview method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-dropview-method-microsoft-web-management-databasemanager)
- [ ] [idbtablemanager getprimarykey method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtablemanager-getprimarykey-method-microsoft-web-management-databasemanager)
- [ ] [idbviewmanager createview method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-createview-method-microsoft-web-management-databasemanager)
- [ ] [databaseprovider getdatabasehostname method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-getdatabasehostname-method-microsoft-web-management-databasemanager)
- [ ] [connectionargument isrequired property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-isrequired-property-microsoft-web-management-databasemanager)
- [ ] [application pool identities and sql server express](https://learn.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities-and-sql-server-express)
- [ ] [connectionargument class MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-class-microsoft-web-management-databasemanager)
- [ ] [idbcustombackuprestoremanager listbackups method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbcustombackuprestoremanager-listbackups-method-microsoft-web-management-databasemanager)
- [ ] [databaseprovider methods MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-methods-microsoft-web-management-databasemanager)
- [ ] [databaseprovider methods MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/databaseprovider-methods-microsoft-web-management-databasemanager)
- [ ] [export a package through iis manager](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/export-a-package-through-iis-manager)
- [ ] [building a web deploy package from visual studio 2010](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/building-a-web-deploy-package-from-visual-studio-2010)
- [ ] [idbrestoremanager restorebackup method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbrestoremanager-restorebackup-method-microsoft-web-management-databasemanager)
- [ ] [idbstoredproceduremanager dropprocedure method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-dropprocedure-method-microsoft-web-management-databasemanager)
- [ ] [connectionargument ispassword property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/connectionargument-ispassword-property-microsoft-web-management-databasemanager)
- [ ] [import a package through iis manager](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/import-a-package-through-iis-manager)
- [ ] [applphysicalpath server variable on windows vista rtm](https://learn.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/applphysicalpath-server-variable-on-windows-vista-rtm)
- [ ] [table createdate property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/table-createdate-property-microsoft-web-management-databasemanager)
- [ ] [table schema property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/table-schema-property-microsoft-web-management-databasemanager)
- [ ] [table name property MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/table-name-property-microsoft-web-management-databasemanager)
- [ ] [applphysicalpath server variable on windows vista rtm](https://learn.microsoft.com/en-us/iis/application-frameworks/running-classic-asp-applications-on-iis-7-and-iis-8/applphysicalpath-server-variable-on-windows-vista-rtm)
- [ ] [idbviewmanager createview method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbviewmanager-createview-method-microsoft-web-management-databasemanager)
- [ ] [introduction to web deploy](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/introduction-to-web-deploy)
- [ ] [idbstoredproceduremanager getstoredprocedurecreatefromexistingstatement method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbstoredproceduremanager-getstoredprocedurecreatefromexistingstatement-method-microsoft-web-management-databasemanager)
- [ ] [configuring ftp with net membership authentication in iis 7](https://learn.microsoft.com/en-us/iis/publish/using-the-ftp-service/configuring-ftp-with-net-membership-authentication-in-iis-7)
- [ ] [web deploy powershell cmdlets](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/web-deploy-powershell-cmdlets)
- [ ] [run sql server stored procedures asp page](https://learn.microsoft.com/en-us/troubleshoot/developer/webapps/iis/active-server-pages/run-sql-server-stored-procedures-asp-page)
- [ ] [idbtabledatamanager deleterow method MWM DB MGR](https://learn.microsoft.com/en-us/iis/extensions/database-manager-reference/idbtabledatamanager-deleterow-method-microsoft-web-management-databasemanager)
- [ ] [tools and utilities questions](https://learn.microsoft.com/en-us/iis/web-hosting/frequently-asked-questions-faq/tools-and-utilities-questions)
- [ ] [feature to configuration reference](https://learn.microsoft.com/en-us/iis/get-started/planning-your-iis-architecture/feature-to-configuration-reference)
- [ ] [sessionstatesection class](https://learn.microsoft.com/en-us/iis/wmi-provider/sessionstatesection-class)
- [ ] [configurationsectionwithcollection class](https://learn.microsoft.com/en-us/iis/wmi-provider/configurationsectionwithcollection-class)
- [ ] [collectionelement class](https://learn.microsoft.com/en-us/iis/wmi-provider/collectionelement-class)
- [ ] [how to use managed code c to create an ftp authentication provider with dynamic ip restrictions](https://learn.microsoft.com/en-us/iis/develop/developing-for-ftp/how-to-use-managed-code-c-to-create-an-ftp-authentication-provider-with-dynamic-ip-restrictions)
- [ ] [web deploy parameterization](https://learn.microsoft.com/en-us/iis/publish/using-web-deploy/web-deploy-parameterization)
Triaging + plan for completion must be complete by end of September, actual fixing can occur after that.

CS effort for repo:
IIS-docs and MicrosoftDocs/IIS.Administration-docs

ROPC:
107 files in IIS-docs
0 in IIS.Administration-docs

---
[Associated WorkItem - 295458](https://dev.azure.com/msft-skilling/Content/_workitems/edit/295458)

**Comment by wadepickett** [comment]
Closing, since we are organizing by Issue type.

**Comment by Rick-Anderson** [comment]
The list completes the triage
