### ISSUE TITLE
CS Effort: AspNetDocs: Global Admin

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33227]
CS effort for repo:
**AspNetDocs**

For details see:
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

Global:
3 Files

Assigned to all three of us until we work out who is doing what.

See CS Dashboard per email thread.

---
[Associated WorkItem - 295457](https://dev.azure.com/msft-skilling/Content/_workitems/edit/295457)

**Comment by tdykstra** [comment]
The 3 global administrator files are:

> [Windows Azure Authentication | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/visual-studio/overview/2012/windows-azure-authentication) 25 weekly page views
> [Developing ASP.NET Apps with Azure Active Directory - ASP.NET 4.x | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/identity/overview/getting-started/developing-aspnet-apps-with-windows-azure-active-directory) 63 weekly pv
> [Creating ASP.NET Web Projects in Visual Studio 2013 | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/visual-studio/overview/2013/creating-web-projects-in-visual-studio) 17 weekly pv

Given that they are for an out-of-support version of VS and traffic is extremely low at around 100 pv/month, I wonder if we could look into the feasibility of just deleting them?

**Comment by Rick-Anderson** [comment]
> 
> Given that they are for an out-of-support version of VS and traffic is extremely low at around 100 pv/month, I wonder if we could look into the feasibility of just deleting them?

More importantly Azure and security has changed so much since they were written we can safely delete the first two and redirect .

For the 3rd, see https://github.com/dotnet/AspNetDocs/pull/895

HOw do I tract https://github.com/dotnet/AspNetDocs/pull/895 in issues, work items, etc?

**Comment by tdykstra** [comment]
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

**Comment by wadepickett** [comment]
@Rick-Anderson & @tdykstra 

I updated the status in the linked spreadsheet from [SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)


[Windows Azure Authentication | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/visual-studio/overview/2012/windows-azure-authentication) 25 weekly page views
**Status: In Progress**

[Developing ASP.NET Apps with Azure Active Directory - ASP.NET 4.x | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/identity/overview/getting-started/developing-aspnet-apps-with-windows-azure-active-directory) 63 weekly pv
**Status: In Progress**

[Creating ASP.NET Web Projects in Visual Studio 2013 | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/visual-studio/overview/2013/creating-web-projects-in-visual-studio) 17 weekly pv
**Status: Completed - Removed**

**Comment by Rick-Anderson** [comment]
> 
> [Creating ASP.NET Web Projects in Visual Studio 2013 | Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/visual-studio/overview/2013/creating-web-projects-in-visual-studio) 17 weekly pv **Status: Completed - Removed**


[It's not closed or removed](https://github.com/dotnet/AspNetDocs/pulls?q=is%3Apr+is%3Aclosed)

**Comment by Rick-Anderson** [comment]
> I updated the status in the linked spreadsheet from [SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

@wadepickett  can you update the spreadsheet. All these have been removed

**Comment by wadepickett** [comment]
I believe I already did, I will go check and update here

**Comment by wadepickett** [comment]
You are right, I had not updated yet.  They are now.

All three global items are listed as complete along with the PR links entered in the spreadsheet.  Thanks.
