### ISSUE TITLE
Remove FF special Trust the HTTPS cert instructions

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33230]
### Description

Maybe remove it from 6.0+ and in earlier version add a note it may not be necessary?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&branch=pr-en-us-33221&tabs=visual-studio%2Clinux-sles

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md

### Document ID

12ca0b9a-2638-a4ce-c45f-d4579c83dafb

### Article author

@tdykstra

---
[Associated WorkItem - 292347](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292347)

**Comment by amcasey** [comment]
> add a note it may not be necessary

I suspect it depends on the FF version, rather than the dotnet version, so this is probably a good compromise.

**Comment by tdykstra** [comment]
Addressed by #33221
