### ISSUE TITLE
Add .NET 9 version  and remove The preceding command requires .NET 9.0 or higher on Linux.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33231]
### Description

See #33221

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-8.0&branch=pr-en-us-33221

https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-8.0&branch=pr-en-us-33221&tabs=visual-studio%2Clinux-sles

* Content: [Hosting ASP.NET Core image in container using docker compose with HTTPS](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https)

### Content source URL

* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/docker-https.md
* https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md
*  Content Source: [aspnetcore/security/docker-compose-https.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/docker-compose-https.md)

### Document ID

2f32c7c3-8667-0e88-495b-c0c888572964

### Article author

@Rick-Anderson

---
[Associated WorkItem - 292346](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292346)

**Comment by amcasey** [comment]
Note that 8.0 is expected to get this functionality in a patch: https://github.com/dotnet/aspnetcore/pull/57108

**Comment by tdykstra** [comment]
@Rick-Anderson The text "The preceding command requires .NET 9.0 or higher on Linux." doesn't appear anywhere in these articles, so should we just mark this issue as completed?

**Comment by tdykstra** [comment]
Fixed by #33572 and #33580
