### ISSUE TITLE
Update rowversion data type for EF Core 8

### ISSUE THREAD

**Issue by cremor** [dotnet/AspNetCore.Docs#33237]
### Description

This page should be updated for EF Core 8. You can now use `long` or `ulong` properties for the row version with SQL Server.

This also applies to other pages. E.g. the page [Tutorial: Handle concurrency - ASP.NET MVC with EF Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency) should also be updated.

See also:
https://github.com/dotnet/EntityFramework.Docs/issues/4774
https://github.com/dotnet/EntityFramework.Docs/pull/4764 (note: The change from that PR is not live yet. The page [What's New in EF Core 8](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#numeric-rowversions-for-sql-azuresql-server) still shows the not needed `HasConversion` call.)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-8.0&tabs=visual-studio#conflict-detection-in-ef-core

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/concurrency.md

### Document ID

e337d2e1-7447-634a-d11a-511247e0f897

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thanks, @cremor. We'll address this when we update the tutorials for .NET 8.

**Comment by Rick-Anderson** [comment]
@cremor  that's should be taken care of in #26505
