### ISSUE TITLE
"Problems with route value invalidation": This paragraph is missing explanation

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#33248]
### Description

The paragraph sub title reads: _"The following code shows an example of a URL generation scheme that's not supported by routing:"_ — yet, the text following the example doesn't fulfill the heading's promise: it doesn't explain _exactly_ what in these _**two**_ examples is not supported and why.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-9.0#problems-with-route-value-invalidation

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/routing.md

### Document ID

86aeab13-1c25-9fc1-4e56-0390cb40c242

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
The desire is to have the `culture `parameter always accepted as an ambient value. However, the culture parameter is **_not_** accepted as an ambient value because of the way required values work:

In the "default" route template, the culture route parameter is to the l

**Comment by SetTrend** [comment]
So "changes to controller _won't invalidate_ culture" is interchangeable with "not _supported_"?
