### ISSUE TITLE
Comment out Linux cert support until it's released

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33247]
### Description

See [this comment](https://github.com/dotnet/AspNetCore.Docs/pull/33221#issuecomment-2266244371)

See #33221

cc @tdykstra 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?branch=main&branchFallbackFrom=pr-en-us-33221&view=aspnetcore-8.0&tabs=visual-studio%2Clinux-sles

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/enforcing-ssl.md

### Document ID

12ca0b9a-2638-a4ce-c45f-d4579c83dafb

### Article author

@tdykstra

---
[Associated WorkItem - 292556](https://dev.azure.com/msft-skilling/Content/_workitems/edit/292556)

**Comment by amcasey** [comment]
@Rick-Anderson What do I need to do for this?  Revert my change and stage a new PR restoring it?

**Comment by Rick-Anderson** [comment]
@amcasey  so sorry I got my PR's mixed up. I'll fix everything. See #33260 which backs out the change. As soon as RC1 is released, I'll update and fix all the versions.

**Comment by tdykstra** [comment]
Fixed by #33572
