### ISSUE TITLE
Issue in - VS 2022 Community version - <input @bind="InputValue" @bind:event="oninput" />

### ISSUE THREAD

**Issue by suren1503** [dotnet/AspNetCore.Docs#33268]
### Description

<input @bind="InputValue" @bind:event="oninput" />

This code is not working in VS 2022 Community version. Please help

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @suren1503 ... Mixed case directive attributes isn't supported. See the last line of ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0#markup

Also, a minor NIT on your issue ... you opened this issue from the bottom of the wrong article. The content on this is in the *Data Binding* article.

**Comment by guardrex** [comment]
I also should mention in passing that even if you did use lowercase directive attributes that all Blazor features require an interactive render mode and don't run on the client when the component only adopts static server rendering (SSR). It's covered in ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#enable-support-for-interactive-render-modes
