### ISSUE TITLE
Misleading statement about Developer Exception Page

### ISSUE THREAD

**Issue by SetTrend** [dotnet/AspNetCore.Docs#33264]
### Description

In paragraph "[Developer Exception Page](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-9.0#developer-exception-page)" it reads:

> ASP.NET Core apps enable the developer exception page by default when […] running in the Development environment.

That statement either is wrong or misleading.

Every other ASP.NET Core documentation page claims that the user must _manually_ enable the Developer Exception page:

```c#
if (env.IsDevelopment())
{
  app.UseDeveloperExceptionPage();
}
```

### Page URL
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-9.0#developer-exception-page

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md

### Document ID

38515dfb-91a5-b395-db9d-084bbaf095c8

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
The doc states:

# BOTH

ASP.NET Core apps enable the developer exception page by default when **_both_**:

Running in the [Development environment](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-9.0).
The app was created with the current templates, that is, by using [WebApplication.CreateBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createbuilder).
