### ISSUE TITLE
UUF: how use wwwroot/BlazorPageScript.lib.module.js, on layout ? on page ? after initial page ?

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33277]
### Description

how use wwwroot/BlazorPageScript.lib.module.js, on layout ? on page ? after initial page ?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/static-server-rendering?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/static-server-rendering.md

### Document ID

c991c83d-dc0b-1962-2ef2-d7da0a7e56f8

### Article author

@guardrex

**Comment by guardrex** [comment]
This is covered by the article. The `PageScript` component that loads the module can be placed anywhere the dev wants.
