### ISSUE TITLE
UUF: full tutorial on Blazor and EF

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33279]
### Description

RElated issue: #33278
Please! Do a tutorial from scratch like https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/installI want to learn how to implement EF Core in a fresh project, and not by cloning a sample repository. Just use the https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial tutorial and extend it by adding a database. Thanks!

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-ef-core.md

### Document ID

2ebc5e4d-bab4-6d30-9018-9a712c482236

### Article author

@guardrex

**Comment by guardrex** [comment]
Already covered by https://github.com/dotnet/AspNetCore.Docs/issues/32359.
