### ISSUE TITLE
The upload stream is closing after the loop.

### ISSUE THREAD

**Issue by rodrigo-lemela-duarte** [dotnet/AspNetCore.Docs#33272]
[EDIT by guardrex to fix the code block ... @rodrigo-lemela-duarte, it's triple-backticks on a line above and below code in a comment]
[EDIT by guardrex to update the report on the var access that results in the error about the closed stream. The error occurs on `content` access.]

### Description

At the `FileUpload2.razor` code:

This part of the code is throwning error:

```csharp
var fileContent = new StreamContent(file.OpenReadStream(maxFileSize));
```

After you get out of the loop and try to access ~`fileContent`~ [should be `content`, see comment below], .NET throws an error saying that the **stream is closed**.

The right piece of the code is:

```csharp
await using var fileStream = uploadedFile.OpenReadStream(maxAllowedSize: maxFileSize);
using var memoryStream = new MemoryStream();
await fileStream.CopyToAsync(memoryStream);
var fileContent = new ByteArrayContent(memoryStream.ToArray());
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/file-uploads.md

### Document ID

c11d981c-05af-c19d-a333-feedd5978639

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @rodrigo-lemela-duarte for opening the issue over here. This is the repo where we work issues.

That code, which is part of the `FileUpload2` component isn't supposed to be used that way. The contents of `fileContent` are only used to establish content for the `MultipartFormDataContent`, which is used to POST the file content to the server. This scenario is described at the top of the section ...

> The following example demonstrates uploading files from a server-side app to a backend web API controller in a separate app, possibly on a separate server.

I think the scenario that you should focus on for a BWA uploading content to the BWA is in the *Server-side file upload example* section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0#server-side-file-upload-example

**Comment by guardrex** [comment]
I see. Thanks for the clarification.

Let me see if I can reproduce that error here. I'll get back to you soon ... hopefully by tomorrow afternoon.

**Comment by guardrex** [comment]
I'll leave this open for one of the product unit engineers to take a look during the holidays (or sooner if more bug reports come in), but I can't reproduce a problem with the current demonstration code ...

<img width="365" alt="Capture" src="https://github.com/user-attachments/assets/832e1028-271b-457a-92c5-5bd7b9fac47e">

After changing the generated file extensions to their correct values (`.png` and `.txt`) ...

<img width="578" alt="Capture1" src="https://github.com/user-attachments/assets/af27f9df-9b3b-4094-93f0-5bb194cc6f0e">

<img width="578" alt="Capture2" src="https://github.com/user-attachments/assets/0d5b29bc-c841-4203-8c32-8e4a860d4d5c">

**Comment by rodrigo-lemela-duarte** [comment]
Strange. Can be something local?
After that change, mentioned on the first comment, my code started to work.

**Comment by guardrex** [comment]
I don't know ... maybe. We'll have to have one of the product unit engineers take a look at this issue.

However, they can't look right now. They're too busy putting the final touches on the .NET 9 release for November.

I'll contact them around the holidays in late November to take a look.

**Comment by guardrex** [comment]
@rodrigo-lemela-duarte ... Mackinnon just remarked on this (and similar problems). I'll work on adding a section and/or updating the existing approach. See ....

https://github.com/dotnet/aspnetcore/issues/38842
