### ISSUE TITLE
文档缺字

### ISSUE THREAD

**Issue by feilyang** [dotnet/AspNetCore.Docs#33284]
### Description

![image](https://github.com/user-attachments/assets/8a4c5b44-0e6d-44ac-9e10-2548c86708e9)

[在此处输入反馈]

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/health-checks.md

### Document ID

52d8efc9-a336-71d9-6d90-98173cbf6bf4

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Please explain what the issue is about in text, not just an image. Thanks.
