### ISSUE TITLE
Add note to manually invoke ValueChanged event callback in Editor

### ISSUE THREAD

**Issue by Hwiet** [dotnet/AspNetCore.Docs#33294]
### Description

`Editor<T>` itself does not call `ValueChanged`. So the **StarshipSubform** component example will never invoke the *after* event handler if it is bound, meaning `AfterModelDetailsChanged` is never called in the following example, even when the value passed to the subform is changed.

```razor
<StarshipSubform @bind-Value="Model.Details" @bind-Value:after="AfterModelDetailsChanged" />
```

It may be helpful to add a note that the `ValueChanged` event callback needs to be manually invoked in a component inheriting `Editor<T>`, and tweak the `StarshipSubform.razor` example to something like this:

```razor
@inherits Editor<ShipDetails>

<div>
    <label>
        Description: 
        <InputText @bind-Value="Value!.Description" @bind-Value:after="InvokeValueChanged" />
    </label>
</div>
<div>
    <label>
        Length: 
        <InputNumber @bind-Value="Value!.Length" @bind-Value:after="InvokeValueChanged" />
    </label>
</div>

@code {
    private async void InvokeValueChanged()
    {
        if (ValueChanged.HasDelegate)
        {
            await ValueChanged.InvokeAsync(Value);
        }
    }
}

```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/forms/binding.md

### Document ID

19296123-d389-3d2f-da8f-89420cc3a96e

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @Hwiet ... *Maybe* we could cover this, but I'll need to ask Mackinnon to determine if this scenario is common enough in general use cases to cover it. However, I can't ping him right now because the whole team is busy working on the final push to get .NET 9 out in November ⛰️⛏️😅. Let's sit on this for now, and I'll ask him to look at this when the holidays 🦃 get here.

**Comment by guardrex** [comment]
@Hwiet ... I can't reproduce the behavior that you're describing. I set up the article's example with a `AfterModelDetailsChanged` method as you describe, and the method is definitely called after the fields are changed and lose focus.

If you've found what you think is a bug or strange 👽 behavior, open it for the product unit on their repo ...

https://github.com/dotnet/aspnetcore/issues

You can copy me on it by placing the following at the bottom of your opening comment ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33294
```

I'll keep an 👁️ on the discussion and possibly re-open this based on your convo with them.
