### ISSUE TITLE
What's new: Improved security and performance observability with Kestrel connection metrics

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33316]
### Description

* Add a section to What's new covering [Improved security and performance observability with Kestrel connection metrics](https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274516260)
* Create an issue for updating the permanent documentation, and then do that

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 295442](https://dev.azure.com/msft-skilling/Content/_workitems/edit/295442)

**Comment by Rick-Anderson** [comment]
> Create an issue for updating the permanent documentation, and then do that

@tdykstra  can you assign that to me? 
I wrote the metrics article in asp.net core and rewrote the .net version. I’m working on metrics right now so I’d like to own metrics.

**Comment by tdykstra** [comment]
> > Create an issue for updating the permanent documentation, and then do that
> 
> @tdykstra can you assign that to me? I wrote the metrics article in asp.net core and rewrote the .net version. I’m working on metrics right now so I’d like to own metrics.

Will do ... actually, you can create the issue yourself if you want.

**Comment by tdykstra** [comment]
Did you create the issue, or do I need to? I'm back looking at these, so I can create it now if you haven't.
