### ISSUE TITLE
What's new: Opt-out of HTTP metrics on certain endpoints and requests

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33315]
### Description

- [x] Add a section to What's new covering [Opt-out of HTTP metrics on certain endpoints and requests](https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274637569)
- [x] Create an issue for updating the permanent documentation, and then do that ---- #33319
- [ ] Hook up WN9 `[!INCLUDE[](~/release-notes/aspnetcore-9/includes/opt_out_metrics.md)`

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 295443](https://dev.azure.com/msft-skilling/Content/_workitems/edit/295443)

**Comment by Rick-Anderson** [comment]
As soon as #33320 merges, add `[!INCLUDE[](~/release-notes/aspnetcore-9/includes/opt_out_metrics.md)]` to wn9.md
