### ISSUE TITLE
.NET 9: OpenIdConnectHandler adds support for Pushed Authorization Requests (PAR)

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33332]
### Description

See [OpenIdConnectHandler adds support for Pushed Authorization](https://github.com/dotnet/AspNetCore.Docs/issues/33031#issuecomment-2274440169)  and #33307

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/claims.md

### Document ID

b01e1351-d362-fd61-4dcb-bacb21559f76

### Article author

@damienbod

---
[Associated WorkItem - 296817](https://dev.azure.com/msft-skilling/Content/_workitems/edit/296817)

**Comment by damienbod** [comment]
I'll make a PR this week, good?
