### ISSUE TITLE
WN9.7: Move non-blazor embedded snippets to project

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33354]
### Description

Our policy is to ***NOT*** use embedded snippets. For .NET 10 previews, we should aim to have Compilable code `:::code language="csharp" source="~/fundamentals/Program.cs" id="snippet_1" highlight="1":::`

<img width="265" alt="image" src="https://github.com/user-attachments/assets/fb8533ac-21c9-498b-a865-6f18669fe586">

Every snipped I migrated to a project had at least 1 compiler error I fixes.
Record how many snippets you had to change here.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

---
[Associated WorkItem - 302691](https://dev.azure.com/msft-skilling/Content/_workitems/edit/302691)

**Comment by wadepickett** [comment]
#33318
Moved the original inline code for What's New  .NET 9 Prev 7 for the SignalR section a project that was compiled and tested.

**Comment by wadepickett** [comment]
@tdykstra , I'm completed with this (PR's listed above).  Can we close this or do you still have some to do?  If so, I might move my name to a separate tracking issue and close it for November and refer back to this one.

**Comment by tdykstra** [comment]
Close
