### ISSUE TITLE
This documentation is outdated

### ISSUE THREAD

**Issue by benehudson** [dotnet/AspNetCore.Docs#33378]
### Description

This documentation is listed under .NET Core 8.0 and it references adding code to Startup.cs, but .NET Core 8.0 doesn't use a Startup.cs file.  Recommend updating this documentation to account for the elimination of Startup.cs.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/intro.md

### Document ID

8daf79df-eac4-358b-e6f0-6def45bd54da

### Article author

@tdykstra

**Comment by tdykstra** [comment]
Thank you for contacting us. Our priority is to [update the Razor Pages version of this series and to create a Blazor version of it](https://github.com/dotnet/AspNetCore.Docs/issues/26505). We don't have resources to invest in updating the MVC version.
