### ISSUE TITLE
Connect to TOC: Generate OpenAPI documents at build-time

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33371]
### Description

Title says it all

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/openapi/buildtime-openapi?view=aspnetcore-8.0&branch=pr-en-us-33361&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/openapi/buildtime-openapi.md

### Document ID

97a2b16c-8dac-beb5-54ae-b10f4813325b

### Article author

@captainsafia

---
[Associated WorkItem - 297627](https://dev.azure.com/msft-skilling/Content/_workitems/edit/297627)

**Comment by tdykstra** [comment]
Closing, as this was already done by https://github.com/dotnet/AspNetCore.Docs/pull/33359
