### ISSUE TITLE
Incorrect info for setting environment in Azure Portal

### ISSUE THREAD

**Issue by tlunsfordCXP** [dotnet/AspNetCore.Docs#33388]
### Description

In section [Azure App Service](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-8.0#azure-app-service), one step says "In the Application settings tab, select New application setting." That tab does not exist. It appears that this is intended to set up in the "Environment variables" blade.

Direct link to problematic text, highlighted:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-8.0#:~:text=In%20the%20Application%20settings%20tab%2C%20select%20New%20application%20setting.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/environments.md

### Document ID

1cb5eb30-dd84-e5e1-5826-d74243fabf04

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@tlunsfordCXP Thanks for reporting this. I'm fixing it.
