### ISSUE TITLE
Project structure Blazor App

### ISSUE THREAD

**Issue by WILLEM-LENS** [dotnet/AspNetCore.Docs#33393]
### Description

[Enter feedback here]
Project structure when creating Blazor App - with "interactive Auto" selected - in Visual Studio 2022 Version 17.10.6 is different as described in the articke: Server content corresponds to Client content and the other way around. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/project-structure?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/project-structure.md

### Document ID

6f27ff37-6b3a-57f5-353a-5cf5aabba7cf

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @WILLEM-LENS ... I wouldn't describe it quite that way, but your point is taken that it would be best to either use a more generic layout to list the files and folders that includes location information depending on the options selected or separate layouts for each project depending on the rendering/location options. I'll work on this and come up with a better presentation. Thanks for the issue!
