### ISSUE TITLE
New topic: Secure Authentication Flows for ASP.NET

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33426]
Per discussion in #33408

Create a new topic that covers secure authentication flows for ASP.NET Core.

This topic would be linked to from other topics where we use examples of a local database that doesn't require the user to be authenticated, while recommending production apps should use the most secure authentication flow available

Update the following include to refer to the new topic:
_aspnetcore/includes/managed-identities-test-non-production.md_

With this:

> This article uses a local database that doesn't require the user to be authenticated. Production apps should use the most secure authentication flow available. For more information on authentication for deployed test and production apps, see [Secure authentication flows](/aspnet/core/security/).

(Created and assigned per Rick's request)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/index.md

### Document ID

48e4e204-ea22-c225-0cbc-0d811bdb90ed

### Article author

@mjrousos

**Comment by Rick-Anderson** [comment]
Fixed in #33521
