### ISSUE TITLE
Provide clarity on component level binding when the component has input elements

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/AspNetCore.Docs#33441]
### Description

[Enter feedback here]
All the examples provided in the component binding have a button click _generating_ a value which is sent back to the parent via event call back.
In real life, the child component will have input elements (text, radio, check) that need to be bound to members of the parent component. Visualize a component that lets the user to choose if the font is bold, italic and underlined. In this this scenario, the parent will pass IsBold, IsItalic, IsUnderlined which get bound to one checkbox each in the child component. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#bind-across-more-than-two-components

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @mayur-ekbote ... Thanks for commenting, but I don't agree. That specific scenario is covered by the "Password Entry" example. It even leads in with the text ...

> In a more sophisticated and real-world example ...

Buttons are just used for convenience in other examples to demonstrate basic concepts. We don't say that event handling or binding would be any different for input elements, and a dev can experiment easily enough by swapping buttons for input elements in the examples. I'll keep an 👂 open for further feedback. Thanks again for the issue.

**Comment by mayur-ekbote** [comment]
There are two problems with the password example 
1. there is no data binding in the PasswordEntry.razor component itself. It does traditional data binding i.e. value + oninput. 
2. As the note says, PasswordEntry is for _one way_ data binding. There is no example for two way data binding. 

> The preceding example binds the password one-way from the child PasswordEntry component to the parent PasswordBinding component. Two-way binding isn't a requirement in this scenario if the goal is for the app to have a shared password entry component for reuse around the app that merely passes the password to the parent. For an approach that permits two-way binding without [writing directly to the child component's parameter](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/overwriting-parameters?view=aspnetcore-8.0), see the NestedChild component example in the [Bind across more than two components](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0#bind-across-more-than-two-components) section of this article.

**Comment by guardrex** [comment]
It wasn't clear that you were only talking about two-way binding when you wrote "all examples." I guess you meant all of the component examples of the two-way binding section. I often rely on the dev's comments, not the cross-link in the metadata, when I'm trying to understand what they're referring to.

I don't want to change the example (or the text). I think it's fine in its present form.

**Comment by mayur-ekbote** [comment]
As mentioned. password example has no data binding in the component itself. It lends to the belief that for two way data binding the child component must not use data binding. However, this is the simplest way to do it:

```
 <input type="checkbox" @bind:get="@IsBold" @bind:set="@(async(e)=> await IsBoldChanged.InvokeAsync(e))" @bind:event="oninput">

 <input type="checkbox" @bind:get="@IsItalic" @bind:set="@(async(e)=> await IsItalicChanged.InvokeAsync(e))" @bind:event="oninput">

@code{
    [Parameter]
    public bool IsBold { get; set; }

    [Parameter]
    public EventCallback<bool> IsBoldChanged { get; set; }

    [Parameter]
    public bool IsItalic { get; set; }

    [Parameter]
    public EventCallback<bool> IsItalicChanged { get; set; }
}
```

Anyway. It was a feedback, not an "issue" per se. But that is how, upon clicking "send feedback" link, the form data is auto filled.
