### ISSUE TITLE
Move the Instance property coverage into a dedicated section with a working example

### ISSUE THREAD

**Issue by ShaunCurtis** [dotnet/AspNetCore.Docs#33453]
### Description

Go down the page to this code example in the first section:

```csharp
<DynamicComponent Type="typeof({COMPONENT})" @ref="dc" />

<button @onclick="Refresh">Refresh</button>

@code {
    private DynamicComponent? dc;

    private Task Refresh()
    {
        return (dc?.Instance as IRefreshable)?.Refresh();
    }
}
```
`IRefreshable` is described as:

> an example interface provided by the developer for the dynamic component instance.

Which is about as clear as mud! 

How is anyone supposed to follow this without a clear explanation of how to implement `IRefreshable`?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/dynamiccomponent?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/dynamiccomponent.md

### Document ID

3cefd835-d898-6486-607e-01f42ebb4b6e

### Article author

@guardrex

**Comment by guardrex** [comment]
*Yeah!* The product unit wrote that part. 🙈😆 *Are you surprised?* The rest of the article was written by me 🦖, and the examples are clear. IIRC, all of the other examples are in the [Blazor sample apps](https://github.com/dotnet/blazor-samples/tree/main/8.0/BlazorSample_BlazorWebApp), so you can try them out without having to copy-paste a lot of code. 

I'll see what I can do to flesh that opening example out into a fully-working example.

**Comment by guardrex** [comment]
I think the best thing to do with the bit on the the `Instance` property is to remove it from the article's opening remarks into a dedicated section further down the article and make the example a fully-working piece that's in the sample apps.

**Comment by guardrex** [comment]
Here's the source ...

https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-preview-7/#new-dynamiccomponent-instance-property

... and they didn't provide more info there.

**Comment by ShaunCurtis** [comment]
For reference this question on StackOverflow - 

 - https://stackoverflow.com/questions/78915482/how-to-implement-irefreshable-using-the-instance-property-of-the-dynamiccompon 
  
 alerted me to it in the first place.
