### ISSUE TITLE
SFI CS Effort: ROPC for AspNetCore.Docs: Triage ~and NOT fix where possible with include statement.~

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#33504]
Contributes to parent tracking issue: #33229

For the remaining 66 ROPC flagged items in repo AspNetCore.Docs

Review and triage.
Apply where we can the standard include regarding secure auth flow, see example pr #33408
Update the tracking spreadsheet here:
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)
• [ROPC & Global - SFI Update - Content remediation action items!](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmessage%2F19%3A49ff5836203f4b358334bfcfa593f252%40thread.tacv2%2F1722361260037%3FtenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47%26groupId%3D8d8475c9-f864-4ed0-825e-b2e419026017%26parentMessageId%3D1722361260037%26teamName%3DContent%2520Team%2520%257C%2520C%252BE%2520Skilling%26channelName%3DGeneral%26createdTime%3D1722361260037&data=05%7C02%7Cwpickett%40microsoft.com%7Cf49c51fc14f747fbb02708dcb8918170%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638588182292262817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qFwA7q8Qb3K8nMotMj4%2FasBUwmbPwDmQ7pMyFLmMZIA%3D&reserved=0) (ROPC/Global Admin) July 30, 2024 10:41 AM

For any remainder ROPC items that require more involved re-work create a tracking issue.

## remediated issues

- [ ] #33598
- [ ] #33543
- [ ] #33518
- [x] #33407 
                - Completed  with PR #33408

## Triaged issues

- [x] #33716
- [ ] 
---
[Associated WorkItem - 307298](https://dev.azure.com/msft-skilling/Content/_workitems/edit/307298)

**Comment by Rick-Anderson** [comment]
@tdykstra will correct me if I'm wrong, but the SFI-ROPC is in two phases, Triage then later on remedy. 
So this should be a triage issues like #33226 that lists all the potential candidates. Once that list is made and you scan through the articles to get an idea of how to remediate, you then create a remediation issue like #33699

**Comment by Rick-Anderson** [comment]
@wadepickett  I fixed up the top screen. Can you add the RP tutorials you did ROPC remediation?

**Comment by Rick-Anderson** [comment]
@wadepickett  only Triage is required for this sprint.
