### ISSUE TITLE
Inconsistent port numbers make documentation confusing

### ISSUE THREAD

**Issue by awdorrin** [dotnet/AspNetCore.Docs#33510]
### Description

.csproj file shows:
` <SpaProxyServerUrl>https://localhost:44414</SpaProxyServerUrl>`
launchSettings.json shows:
```
      "applicationUrl": "http://localhost:51783",
      "sslPort": 44329
...
"applicationUrl": "https://localhost:7145;http://localhost:5273",
```
package.json shows:
```
  "start:windows": "ng serve --port 44483 --ssl --ssl-cert \"%APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem\" --ssl-key \"%APPDATA%\\ASP.NET\\https\\%npm_package_name%.key\"",
    "start:default": "ng serve --port 44483 --ssl --ssl-cert \"$HOME/.aspnet/https/${npm_package_name}.pem\" --ssl-key \"$HOME/.aspnet/https/${npm_package_name}.key\"",
```
proxy.conf.js shows the following (and doesn't explain ASPNETCORE_HTTPS_PORTS)
```
const target = env.ASPNETCORE_HTTPS_PORTS ? `https://localhost:${env.ASPNETCORE_HTTPS_PORTS}` :
  env.ASPNETCORE_URLS ? env.ASPNETCORE_URLS.split(';')[0] : 'http://localhost:51951';
```

Not one port number matches from all of the examples, so it is hard to know which ones should match.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/intro?view=aspnetcore-7.0&preserve-view=true

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/client-side/spa/intro.md

### Document ID

c1ffb8e1-215c-c148-0b28-da0d62665fa4

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Per the doc: Provide the port,
