### ISSUE TITLE
ROPC Blazor

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33517]
### Description

See #33504

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

**Comment by guardrex** [comment]
Moved to #33523 to place correct metadata. We don't have an easy cut-'n-paste way to handle metadata any longer.
