### ISSUE TITLE
Should appsettings.json be used instead of Web.Config?

### ISSUE THREAD

**Issue by Rod-at-DOH** [dotnet/AspNetCore.Docs#33529]
### Description

In the IIS section it recommends adding Windows Authentication configuration details in the Web.Config file. However, the Web.Config file has been replaced by the appSettings.json file. So, should the documentation for IIS use appSettings.json instread?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md

### Document ID

fbc36c26-9992-1f4c-66d3-02f898ee7ec4

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
> However, the `Web.Config` file has been replaced by the `appSettings.json`  file.

Not for the ANCM and IIS. Where did you read that?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson , I read it on this page: https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/windowsauth.md where it says:
> 
> > IIS uses the ASP.NET Core Module to host ASP.NET Core apps. Windows Authentication is configured for IIS via the web.config file. The following sections show how to:
> > Provide a local web.config file that activates Windows Authentication on the server when the app is deployed.
> > Use the IIS Manager to configure the web.config file of an ASP.NET Core app that has already been deployed to the server.

That's correct, but it doesn't mention `appsettings.json`

**Comment by Rod-at-DOH** [comment]
Thank you, @Rick-Anderson. It is now my understanding that Blazor doesn't have a Visual Studio project template that works with Windows Authentication for an Intranet application. That instead what I need to do, if I use a Blazor Visual Studio project template, is to specify `None` for authentication with the Blazor Server template (or the Blazor Web App VS project template), then add in the Windows Authentication code into a Web.Config file. I'm not exactly sure how to do that, but that seems to be the correct approach. If I'm wrong, please correct me.
