### ISSUE TITLE
No useful information after the link jump

### ISSUE THREAD

**Issue by Varorbc** [dotnet/AspNetCore.Docs#33522]
https://social.msdn.microsoft.com/Forums/SqlServer/5ed119ef-1704-4be4-8a4f-ef11de7c8f34/a-certificate-chain-processed-but-terminated-in-a-root-certificate-which-is-not-trusted-by-the

https://github.com/dotnet/AspNetCore.Docs/blob/51317b23974267231db9243399c6706410ba2341/aspnetcore/security/authentication/certauth.md?plain=1#L214

**Comment by guardrex** [comment]
Hello @Varorbc ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.
