### ISSUE TITLE
What does disabling Blazor wasm exception handling mean?

### ISSUE THREAD

**Issue by ite-klass** [dotnet/AspNetCore.Docs#33535]
### Description

The section Exception handling describes that exception handling can be disabled via `WasmEnableExceptionHandling`.

It does not mention what kind of exception handling, in what scopes, and to what conclusions.

What does `WasmEnableExceptionHandling` change? Is it limited to the WebAssembly code/scope? How does it interface to/with JS etc?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-build-tools-and-aot?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/webassembly-build-tools-and-aot.md

### Document ID

bbbdf15e-1918-cee9-ff03-0ebbca80e86e

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @ite-klass ... I'll add a cross-link to ...

https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md#eh---exception-handling

... which further cross-links to the additional info at ...

https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md

**Comment by ite-klass** [comment]
Thank you @guardrex 👍🚀

**Comment by gptucci** [comment]
iPadOS 18.4.1 - Blazor Wasm 9.4 stopped to work
I get the errors

**[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dotnet.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dotnet.runtime.js.map, line 0)**

**Comment by guardrex** [comment]
@gptucci ... Please don't comment on closed issues or PRs.

You'll need to open a product unit issue on that, and they'll need more details and probably a minimal repro app hosted in a public GitHub repository that demonstrates the errors ...

https://github.com/dotnet/aspnetcore/issues
