### ISSUE TITLE
MVC tutorial: Add ROPC warning

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33543]
### Description
Exact same global find/replace as #33408 for the `sql.md` files.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-mvc-app/working-with-sql.md

### Document ID

a0b5e15c-d747-8710-95fb-a55c09861a1e

### Article author

@wadepickett

**Comment by wadepickett** [comment]
I'll take this one for my doc, thanks.  At first I thought it was for me so I created a PR already.  So I will just finish.
