### ISSUE TITLE
Blazor guidance organization (cross-link Blazor articles)

### ISSUE THREAD

**Issue by jastewart** [dotnet/AspNetCore.Docs#33555]
### Description

Prime example: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-8.0
I am trying to implement on-behalf-of authentication in a Blazor WebAssembly project. A large number of MS and other examples show code such as: builder.Services.AddAuthentication(...)  But, for me, this doesn't EVER compile and the error is only "IServiceCollection does not contain a definition for AddAuthentication...". So where IS AddAuthentication? It surely depends on the type of "builder" and yet you hardly ever spell this out. The result is the impression that your code snippets just don't work. They probably do work though, but in what exact context? The whole area of .NET versions, .Net FX, and the various flavours of Blazor, not to mention all other ASP.Net things is extremely confusing. Search results nearly always do not apply, or are out of date or incompatible with what I am trying to do. Please try to define what "builder" is, or can be, in ALL of your code examples. I have wasted days on this whole topic and feel I am getting exactly nowhere. Yes, I have things to learn, but critical examples that start with "builder" without saying what "builder" is, do not help. 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/index.md

### Document ID

48e4e204-ea22-c225-0cbc-0d811bdb90ed

### Article author

@mjrousos

**Comment by guardrex** [comment]
Hello @jastewart ... This is part of a larger concern on content organization these days now that Blazor has become the primary recommendation for new ASP.NET Core app development.

For Blazor, we have a special node (folder) of articles that apply to Blazor security scenarios under the "Blazor" node in the "Web apps" node ...

https://learn.microsoft.com/aspnet/core/blazor/security/

There (and in the [Blazor samples repo for our articles](https://github.com/dotnet/blazor-samples)), you'll find Blazor-specific API in use.

This is also true for Azure docs and examples that specifically target Blazor, which they call out in article titles and sample names.

We've had some discussion about how to cover Blazor in the ASP.NET Core doc set now that Blazor is the primary recommendation for new development. Management wants to keep the node (folder) separation of articles for Blazor (versus Razor Pages/MVC) for the time being.

However, you can quickly see the problem with the coverage right now: Content in the main doc set's *Fundamentals* node, *Security and Identity* node, *Host and Deploy* node, and other nodes ***don't apply to Blazor*** in a many cases 😨. At this time, devs must look in the Blazor node to see Blazor-specific coverage that takes precedent over a lot of coverage in the main doc set. *This is confusing! I agree!*

I had a discussion with Dan Roth recently on this, but I feel that we didn't get too far with it. I'm going to try again. I'll refashion this issue to track the public discussion. I'll return here shortly with an update on management's thinking (or Dan will respond directly here after we chat offline about it).

**Comment by guardrex** [comment]
I'm going to perform a general article assessment on this problem and use this issue to track it. I hope to work on this next week. I'll post an update here with my conclusions.

WRT this specific issue, @jastewart, I'm going to add some content to the top of the main doc set's *Security and Identity* overview article mentioning that we have Blazor-specific coverage in the Blazor node.

Leave this issue open. I'll close it later when we're done with it.
