### ISSUE TITLE
WN: Override InputNumber type attribute

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33551]
### Description

See https://github.com/dotnet/AspNetCore.Docs/issues/33442#issuecomment-2330249873

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

**Comment by Rick-Anderson** [comment]
Is this Blazor related? @guardrex

**Comment by guardrex** [comment]
It is ... moving to #33556.
