### ISSUE TITLE
Aspire name product treated as a verb in Italian translation

### ISSUE THREAD

**Issue by GioviQ** [dotnet/AspNetCore.Docs#33567]
### Description

In this page and in other pages where .NET Aspire is mentioned Aspire is translate in italian as the verb "aspirare".

Like "Windows" Aspire is a product name and does not need to be translated

### Page URL

https://learn.microsoft.com/it-it/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=with-bff-pattern

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @GioviQ ... I have an easy way to stop translation of "Aspire," and I'll configure that for the whole repo shortly.
