### ISSUE TITLE
Document bad interaction between MapStaticAssets and UseBlazorFrameworkFiles

### ISSUE THREAD

**Issue by hwoodiwiss** [dotnet/AspNetCore.Docs#33571]
### Description

I spent a while trying to find out why the Blazor framework static assets files in my API project (built from a referenced Blazor WASM project) weren't being served when using `MapStaticAssets`, instead returning a 500 status code, as the requests reached the end of the request handling pipeline without being handled.

I found that the issue was due to having `UseBlazorFrameworkFiles` in my middleware pipeline, I'm not sure of the details as to why it caused a 500 rather than just serving the framework files.

I feel this would make sense as a warning in the Blazor/Fundementals/Static Files docs, in the section discussing using `MapStaticAssets`, I'm happy to contribute this, I'd just like to get a consensus that this is the correct move first. I _personally_ don't think this is a bug that needs fixing.

I've drafted something [here](https://github.com/hwoodiwiss/AspNetCore.Docs/blob/hwoodiwiss-33570/aspnetcore/blazor/fundamentals/static-files.md?plain=1#L55-L56).

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/static-files.md

### Document ID

25458428-030f-6acb-457e-1b4dfa722043

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @hwoodiwiss ... This is worth a look by the product unit because calling `UseStaticAssets` wasn't a problem with `UseBlazorFrameworkFiles`. There might be a bug. Can you provide the full stack trace of the 500 in an issue comment here so that when I ping for a product unit engineer to look at this they can see exactly what the error is?

**Comment by hwoodiwiss** [comment]
The exception thrown is:
```
System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: ''. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__25_0(HttpContext context)
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Components.WebAssembly.Server.ContentEncodingNegotiator.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.ComponentsWebAssemblyApplicationBuilderExtensions.<>c__DisplayClass3_0.<<UseBlazorFrameworkFiles>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context, HttpLoggingOptions options, HttpLoggingAttribute loggingAttribute, HttpLoggingFields loggingFields)
         at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context, HttpLoggingOptions options, HttpLoggingAttribute loggingAttribute, HttpLoggingFields loggingFields)
         at HwoodiwissHelper.Middleware.UserAgentBlockMiddleware.HandleAsync(HttpContext context, RequestDelegate next) in R:\source\repos\HwoodiwissHelper\src\HwoodiwissHelper\Middleware\UserAgentBlockMiddleware.cs:line 30
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

My guess from looking at the code is that something is setting the Endpoint in `IEndpointFeature` to null after the Static files middleware that UseBlazorFrameworkFiles has already not returned a file due to the check on `IEndpointFeature.Endpoint` not being null.

**Comment by hwoodiwiss** [comment]
I spent some time digging into why this happens.

UseBlazorFrameworkFiles branches the request pipeline when the path starts with `/_framework`, meaning in that case, there is only the `ContentEncodingNegotiator` middleware and `StaticFileMiddleware` that it then adds, [here](https://github.com/dotnet/aspnetcore/blob/4bc867dee200dffb10c9e3693b875311407bdfc6/src/Components/WebAssembly/Server/src/ComponentsWebAssemblyApplicationBuilderExtensions.cs#L42). That means that if the `StaticFileMiddleware` doesn't resolve a file, and instead calls `_next(context)`, we'll hit the end of the branched pipeline without having responded.

When `MapStaticAssets` is used, `StaticFileMiddleware` will always call `_next(context)` when the asset to be returned is in the staticwebassets.endpoints.json, as the `EndpointRoutingMiddleware` will have set the endpoint for the request earlier in the pipeline, so [this](https://github.com/dotnet/aspnetcore/blob/4bc867dee200dffb10c9e3693b875311407bdfc6/src/Middleware/StaticFiles/src/StaticFileMiddleware.cs#L60) check will fail, leaving us in a position where requests to mapped `/_framework` files will always fail.

I think the fix would be to add `context.GetEndpoint()?.RequestDelegate is null` to the conditions for branching the pipeline in `ComponentsWebAssemblyApplicationBuilderExtensions`. Happy to raise the fix if you agree.

**Comment by guardrex** [comment]
In that case, the thing to do is close here and open for the product unit on their repo. Open an issue for them here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33571
```

... to the bottom of your opening comment so that I can follow along.

They might fix it quickly for .NET 9 (due out in November). If so, the article won't need an update.

If they agree to do something about this but push it to .NET 10, they can let me know on your new product unit issue. I'll re-open this issue for adding a remark to the article.

**Comment by guardrex** [comment]
I think it's reasonable to convey Javier's remarks that ...

> In general, we don't think that it's important to make app.UseBlazorFrameworkFiles work alongside app.MapStaticAssets because the latter supersedes the other one.
>
>In fact, it's not necessary to even call UseBlazorFrameworkFiles in 8.0 and onwards, since it's automatically called when invoking AddInteractiveWebAssemblyComponents.

I'll create a PR to address this as opposed to asking for a PR from you because I want to phrase it a certain way. I should be able to address this within an hour or so 🤞🍀.
