### ISSUE TITLE
Document bad interaction between MapStaticAssets and UseBlazorFrameworkFiles

### ISSUE THREAD

**Issue by hwoodiwiss** [dotnet/AspNetCore.Docs#33570]
I spent a while trying to find out why the Blazor framework static assets files in my API project (built from a referenced Blazor WASM project) weren't being served when using `MapStaticAssets`, instead returning a 500 status code, as the requests reached the end of the request handling pipeline without being handled.

I found that the issue was due to having `UseBlazorFrameworkFiles` in my middleware pipeline, I'm not sure of the details as to why it caused a 500 rather than just serving the framework files.

I feel this would make sense as a warning in the Blazor/Fundementals/Static Files docs, in the section discussing using `MapStaticAssets`, I'm happy to contribute this, I'd just like to get a consensus that this is the correct move first. I _personally_ don't think this is a bug that needs fixing.

I've drafted something [here](https://github.com/hwoodiwiss/AspNetCore.Docs/blob/hwoodiwiss-33570/aspnetcore/blazor/fundamentals/static-files.md?plain=1#L55-L56).

**Comment by guardrex** [comment]
Hello @hwoodiwiss ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author (🦖 ... me in this case) automatically.
