### ISSUE TITLE
Incorrect querystring in example

### ISSUE THREAD

**Issue by sdtrip7s** [dotnet/AspNetCore.Docs#33619]
### Description

titleSearch should be titleFilter in the below screenshot, thank you

![2024-09-16_14-08-33](https://github.com/user-attachments/assets/963325f3-3417-4f18-b7b3-ae5c4e7f126d)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-6?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/movie-database-app/part-6.md

### Document ID

6d15bd42-ea91-ec59-1ebc-185653dc7ef4

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @sdtrip7s ... I'll fix that image right now 🏃‍♂️.
