### ISSUE TITLE
Foreign key and navigation properties: bullet 2

### ISSUE THREAD

**Issue by nkn300pm** [dotnet/AspNetCore.Docs#33624]
### Description

[Enter feedback here]
**section:** Foreign key and navigation properties
**section link**: https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-8.0&tabs=visual-studio#foreign-key-and-navigation-properties-1

**bullet 2**:  An administrator is always an instructor. Therefore the InstructorID property is included as the _FK to the Instructor entity._

I think it should be: _FK to the Department entity_

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-rp/complex-data-model.md

### Document ID

7a77b058-f005-8d68-ae46-e487c597f18e

### Article author

@tdykstra

**Comment by tdykstra** [comment]
>>InstructorID property is included as the FK to the Instructor entity.

> I think it should be: FK to the Department entity

I don't see the logic in calling InstructorID the FK to the Department entity; wouldn't that be named DepartmentID?

**Comment by nkn300pm** [comment]
About the  Section **Foreign key and navigation properties** is the definition of **Department** entity

According to  the **Department** definition included below, we can see that **InstructorID** clearly the FK to the **Department** table.

public class Department
    {
        public int DepartmentID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Budget { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
                       ApplyFormatInEditMode = true)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        public int? InstructorID { get; set; }

        public Instructor Administrator { get; set; }
        public ICollection<Course> Courses { get; set; }
    }

Therefore, I believe it not ok  when bullet 2 says that " ... **Therefore the InstructorID property is included as the FK to the Instructor entity**."   In the **Department** table, **InstructorID** is the FK to the **Department** table

**Comment by Rick-Anderson** [comment]
> Above the Section **Foreign key and navigation properties** is the class definition of **Department** entity
> 
> According to the class definition of the **Department** which is included below, we can see that **InstructorID** clearly the FK to the **Department** entity.
> 
> public class Department { public int DepartmentID { get; set; }
> 
> ```
>     [StringLength(50, MinimumLength = 3)]
>     public string Name { get; set; }
> 
>     [DataType(DataType.Currency)]
>     [Column(TypeName = "money")]
>     public decimal Budget { get; set; }
> 
>     [DataType(DataType.Date)]
>     [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
>                    ApplyFormatInEditMode = true)]
>     [Display(Name = "Start Date")]
>     public DateTime StartDate { get; set; }
> 
>     public int? InstructorID { get; set; }
> 
>     public Instructor Administrator { get; set; }
>     public ICollection<Course> Courses { get; set; }
> }
> ```
> 
> Therefore, I believe it is not ok when bullet 2 says that " ... **Therefore the InstructorID property is included as the FK to the Instructor entity**." As we can see in the **Department** table, **InstructorID** is the FK to the **Department** table

That's not correct.
