### ISSUE TITLE
CS triage effort: EF API: ROPC

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33669]
For details see:
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

I think all the EF APIs fall under `/dotnet/api/`, such as the problematic [DbContextInfo Constructors](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.infrastructure.dbcontextinfo.-ctor?view=entity-framework-6.2.0)

Creates a new instance representing a given [DbContext](https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.dbcontext?view=entity-framework-6.2.0) type. An external config object (e.g. app.config or web.config) can be supplied and will be used during connection string resolution. This includes looking for connection strings and DefaultConnectionFactory entries.

@tdykstra  if this is right, close out this issue and mark the spreadsheet as none and complete.

**Comment by tdykstra** [comment]
> and mark the spreadsheet as none and complete.

Where is the spreadsheet that has these?
