### ISSUE TITLE
Pipeline is rejoined only if middleware does not short-circuit

### ISSUE THREAD

**Issue by deep-outcome** [dotnet/AspNetCore.Docs#33662]
### Description

From https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0#branch-the-middleware-pipeline

> [UseWhen](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.usewhenextensions.usewhen) also branches the request pipeline based on the result of the given predicate. Unlike with MapWhen, this branch is rejoined to the main pipeline **if it doesn't short-circuit or contain a terminal middleware**:

From https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0

>  **When a middleware short-circuits, it's called a terminal middleware** because it prevents further middleware from processing the request.

Thus, as I understand, there has to be either "doesn't short-circuit" or "contain a terminal middleware" but no both.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/middleware/index.md

### Document ID

3926c686-0ccc-f9fe-ca52-0134612a1623

### Article author

@tdykstra

---
[Associated WorkItem - 357008](https://dev.azure.com/msft-skilling/Content/_workitems/edit/357008)

**Comment by tdykstra** [comment]
@bravequickcleverfibreyarn What change to the text would you propose to fix this?

**Comment by bravequickcleverfibreyarn** [comment]
I would propose:
- either "if it doesn't short-circuit:"
- or " if it doesn't contain a terminal middleware:"
