### ISSUE TITLE
Bad href anchor for Problem details for error status codes

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/AspNetCore.Docs#33663]
### Description

From https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#problem-details-from-middleware

![Anchor only](https://github.com/user-attachments/assets/7c4e1ae5-aecb-4b84-a235-e24121f7580f)

Depicted hyperlink references

https://learn.microsoft.com/en-us/aspnet/core/web-api/#problem-details-for-error-status-codes-1 while it should be https://learn.microsoft.com/en-us/aspnet/core/web-api/#problem-details-for-error-status-codes.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/error-handling.md

### Document ID

38515dfb-91a5-b395-db9d-084bbaf095c8

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@bravequickcleverfibreyarn Thanks for reporting this.
