### ISSUE TITLE
 author request headers link href anchor does not exist

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/AspNetCore.Docs#33661]
### Description

From https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0#preflight-requests.

![Anchor](https://github.com/user-attachments/assets/b5f628ad-e5af-490a-9cf8-b3a488b7a407)

Link anchor `#author-request-headers` does not exist.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0#ecors6

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/cors.md

### Document ID

d3f332c4-4c60-039e-0e1e-bc6b11831f87

### Article author

@tdykstra

**Comment by tdykstra** [comment]
@bravequickcleverfibreyarn Thanks for reporting this.
