### ISSUE TITLE
Bad French Translation

### ISSUE THREAD

**Issue by Gameplushy** [dotnet/AspNetCore.Docs#33690]
### Description

> If you aren't converting an app for the latest release, pass the -f|--framework option. The following example creates the app for ASP.NET Core version 5.0:

In French :
> Si vous ne convertissez pas l’application vers la dernière version, ignorez l’option -f|--framework. L’exemple suivant crée l’application pour ASP.NET Core version 5.0 :

"ignorez" means "ignore", not "pass". Use "passez" or "utilisez" instead.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/progressive-web-app.md

### Document ID

6240f626-97d4-ace0-5e34-20e1c3592f86

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @Gameplushy ... The translation is performed by the localization team via an automated system. We don't handle it directly here, so I'll see if I can pass this information along.

@khoiph1 ... Does this information go to you for processing?

**Comment by Gameplushy** [comment]
Thank you @guardrex ! Where can I forward other translation errors, if not here? This can be useful info for later.

**Comment by guardrex** [comment]
I'm not authorized to provide the internal team contact. However, they apparently have a special approach to provide translation feedback ...

https://learn.microsoft.com/en-us/contribute/content/provide-feedback#use-the-standard-experience

See the line that reads ...

> Readers of localized content will see an additional option to provide feedback on the translation quality.

When I put the Blazor landing page in French and hit the Feedback button, there is an entry to indicate the feedback is on the translation. I recommend giving that process a shot. I suppose it goes to the same team that Khoi emailed directly.

![image](https://github.com/user-attachments/assets/4e99a318-33fe-4970-81ed-d953e46699a8)

**Comment by Gameplushy** [comment]
Whoops, missed that. Will use that later on!
