### ISSUE TITLE
White screen after add _framework/blazor.server.js

### ISSUE THREAD

**Issue by Matiasits** [dotnet/AspNetCore.Docs#33691]
I am working on a project which I created. When running the project for the first time and implementing the designs in the app, I tried to execute a C# method from the frontend where I did not receive a response, since the code was reviewed and is correct for it to be executed. I investigated and found the solution of adding <script src="~/_framework/blazor.server.js"></script> in _Layout.cshtml. The problem is that when you add this line to that file and run the project, it loads, shows the normal design for a second and then a blank screen, leaving the project without any errors.
My teammates have executed exactly the same project, with the same database in their environments and it works perfectly for them.

![Captura de pantalla 2024-09-23 112429](https://github.com/user-attachments/assets/c75398dc-51e6-4385-8416-f5680661576a)

C# .Net 6.0
DotNet Version: 7.0.403
Blazor 6.0 
Project: Blazor Server

_Layout.cshtml:
@using Microsoft.AspNetCore.Components.Web
@namespace GoleAdminApp.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="GoleAdminApp.styles.css" rel="stylesheet" />
    
    <link rel="shortcut icon" href="~/assets/images/favicon.png">

    
    <link rel="stylesheet" href="~/assets/vendor/daterangepicker/daterangepicker.css">

    
    <link rel="stylesheet" href="~/assets/vendor/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.css">

    
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-style" />

    
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />

    
    <link href="~/assets/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    @RenderBody()

    
    <script src="~/assets/js/vendor.min.js"></script>

    
    <script src="~/assets/vendor/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js"></script>
    <script src="~/assets/vendor/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/assets/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js"></script>
    <script src="~/assets/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js"></script>
    <script src="~/assets/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="~/assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/assets/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js"></script>
    <script src="~/assets/vendor/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="~/assets/vendor/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="~/assets/vendor/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="~/assets/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="~/assets/vendor/datatables.net-select/js/dataTables.select.min.js"></script>

    
    <script src="~/assets/js/pages/demo.datatable-init.js"></script>

    
    <script src="~/assets/js/config.js"></script>

    
    <script src="~/assets/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/assets/vendor/daterangepicker/daterangepicker.js"></script>

    
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>

    
    <script src="~/assets/vendor/admin-resources/jquery.vectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/assets/vendor/admin-resources/jquery.vectormap/maps/jquery-jvectormap-world-mill-en.js"></script>

    
    <script src="~/assets/js/pages/demo.dashboard.js"></script>

    
    <script src="~/assets/js/app.min.js"></script>

    <script src="~/_framework/blazor.server.js"></script>
    
</body>
</html>

_Host.cshtml:
@page "/"
@namespace GoleAdminApp.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "_Layout";
}

<component type="typeof(App)" render-mode="ServerPrerendered" />

**Comment by guardrex** [comment]
BTW, you should open new issues for us via the **Open a documentation** issue at the bottom of an article, which adds metadata and pings us automatically.

However, this will need to go to the product unit for comment or investigation. Open an issue for them here ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33691
```

... to the bottom of your opening comment so that I can follow along. I might re-open this for doc work depending on what they say.
