### ISSUE TITLE
ROPC: Fix/ mitigate EF docs 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33699]
Close https://github.com/dotnet/EntityFramework.Docs/issues/4788 when this is completed
**dotnet_EntityFramework_Docs**

- [x]  [Connection Strings](https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-strings)
- [x] [Connection strings and models](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/connection-strings)
- [x] [Scaffolding (Reverse Engineering)](https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/?tabs=dotnet-core-cli)
- [x] [Configuration File Settings](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/config-file)
- [x] [EF Core tools reference (Package Manager Console) - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/powershell)
- [x] [EF Core tools reference (.NET CLI) - EF Core](https://learn.microsoft.com/en-us/ef/core/cli/dotnet)
- [x] [Multi-tenancy - EF Core](https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy)
- [x] [Azure Cosmos DB Provider - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/cosmos/)
- [x] [What's New in EF Core 5.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/whatsnew)
- [x] [Entity Framework 6 SQL Server provider based on Microsoft.Data.SqlClient](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/microsoft-ef6-sqlserver)
- [x] [Visual Studio Releases - EF6](https://learn.microsoft.com/en-us/ef/ef6/what-is-new/visual-studio)
- [x] [Applying Migrations - EF Core](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying)
- [x] [Port from EF6 to EF Core - Detailed Cases](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-detailed-cases)
- [x] [Using migrate.exe - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/migrate-exe)
- [x] [Database Providers - EF Core](https://learn.microsoft.com/en-us/ef/core/providers/)
- [x] [Porting from EF6 to EF Core - Porting a Code-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-code)
- [x] [Tools & Extensions - EF Core](https://learn.microsoft.com/en-us/ef/core/extensions/)
- [x] [DbContext Lifetime, Configuration, and Initialization - EF Core](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/)
- [x] [Enum Support - EF Designer - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/data-types/enums)
- [x] [Code First Conventions - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/built-in)
- [x] [Interceptors - EF Core](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors)
- [x] [Database First - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/workflows/database-first)
- [x] [What's New in EF Core 6.0](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew)
- [x] [Code First to an Existing Database - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database)
- [x] [Advanced Performance Topics](https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics)
- [x] [Entity Framework Designer Keyboard Shortcuts - EF6](https://learn.microsoft.com/en-us/ef/ef6/modeling/designer/keyboard-shortcuts)
- [x] [Breaking changes in EF Core 7.0 (EF7) - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes)
- [x] [Databinding with WinForms - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/databinding/winforms)
- [x] [Databinding with WPF - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/databinding/wpf)
- [x] [The Entity Framework 6 provider model - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/providers/provider-model)
- [x] [Overview of Entity Framework Core - EF Core](https://learn.microsoft.com/en-us/ef/core/)
- [x] [Upgrading from previous versions to EF Core 2 - EF Core](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-2.0/upgrade)
- [x] [Get Started with Windows Forms - EF Core](https://learn.microsoft.com/en-us/ef/core/get-started/winforms)
- [x] [Dependency resolution - EF6](https://learn.microsoft.com/en-us/ef/ef6/fundamentals/configuring/dependency-resolution)
- [x] [Porting from EF6 to EF Core - Behavior changes](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-behavior)
- [ ] [Porting from EF6 to EF Core - Porting an EDMX-Based Model - EF](https://learn.microsoft.com/en-us/ef/efcore-and-ef6/porting/port-edmx)

For details see:
[SFI info in Teams](https://teams.microsoft.com/l/message/19:49ff5836203f4b358334bfcfa593f252@thread.tacv2/1722361260037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=8d8475c9-f864-4ed0-825e-b2e419026017&parentMessageId=1722361260037&teamName=Content%20Team%20%7C%20C%2BE%20Skilling&channelName=General&createdTime=1722361260037)

See CS Dashboard per email thread.

---
[Associated WorkItem - 295456](https://dev.azure.com/msft-skilling/Content/_workitems/edit/295456)

**Comment by wadepickett** [comment]
@Rick-Anderson (cc @tdykstra), checking through the SFI Dashboards own linked spreadsheet, absolutely all items are now set to "fixed".  Do you know who set all to fixed?  Is that the case that they are all fixed?

Looking through the items in that spreadsheet for repo ef docs I am seeing some that do not look fixed, but maybe I am not interpreting the issue correctly:

For example:

Password issue flagged for this topic:
https://github.com/dotnet/EntityFramework.Docs/blob/main//entity-framework/core/managing-schemas/migrations/applying.md
"
The following example applies migrations to a local SQL Server instance using the specified username and password.

`.\efbundle.exe --connection 'Data Source=(local)\MSSQLSERVER;Initial Catalog=Blogging;User ID=myUsername;Password=myPassword'`
"

**Comment by Rick-Anderson** [comment]
> Absolutely all items are now set to "fixed". Do you know who set all to fixed? Is that the case that they are all fixed?

I was under the wrong assumption that triaged meant fixed. So I'll change them to NA or "In Progress" as appropriate.

**Comment by Rick-Anderson** [comment]
> Password issue flagged for this topic:
https://github.com/dotnet/EntityFramework.Docs/blob/main//entity-framework/core/managing-schemas/migrations/applying.md
"
Create an issue  for that (in our repo and the EF repo) link each issue and assign that to Tom for October.

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/dotnet/EntityFramework.Docs/pull/4849

**Comment by Rick-Anderson** [comment]
@wadepickett 

> @Rick-Anderson (cc @tdykstra), checking through the SFI Dashboards own linked spreadsheet for the repo tab for EF docs: Absolutely all items are now set to "fixed". 

They're all fixed now
