### ISSUE TITLE
Change to text in #33639

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33701]
From (bold just highlights changed text):

> [!WARNING]
> This article uses the [Secret Manager tool](xref:security/app-secrets) to store the password for the seeded user accounts. The Secret Manager tool is used to store sensitive data during local development. **For more information on authentication for deployed test and production apps,** see [Secure authentication flows](xref:security/index#secure-authentication-flows).

to:

> [!WARNING]
> This article uses the [Secret Manager tool](xref:security/app-secrets) to store the password for the seeded user accounts. The Secret Manager tool is used to store sensitive data during local development. **For information on authentication procedures that can be used when an app is deployed to a test or production environment,** see [Secure authentication flows](xref:security/index#secure-authentication-flows).

This text is from a PR that put it in [security/authorization/secure-data.md](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-8.0#test-the-completed-app)

---
[Associated WorkItem - 317466](https://dev.azure.com/msft-skilling/Content/_workitems/edit/317466)

**Comment by Rick-Anderson** [comment]
@tdykstra  change text where? Can you add a link or open from doc page if it's not an include?

**Comment by tdykstra** [comment]
Added a link to the Description box.
