### ISSUE TITLE
Typo CROS vs. CORS

### ISSUE THREAD

**Issue by Thomas-S-B** [dotnet/AspNetCore.Docs#33717]
### Description

Hello,
there is a typo in the german version, CROS should be CORS:
"Ursprungsübergreifende Ressourcenfreigabe (Cross-Origin Resource Sharing, CROS)"
should be
"Ursprungsübergreifende Ressourcenfreigabe (Cross-Origin Resource Sharing, CORS)"

### Page URL

https://learn.microsoft.com/de-de/aspnet/core/signalr/security?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/signalr/security.md

### Document ID

58e87eb0-240b-ab00-c5f4-32a0ab2e0028

### Article author

@bradygaster

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+58e87eb0-240b-ab00-c5f4-32a0ab2e0028)

**Comment by guardrex** [comment]
Thanks @Thomas-S-B ... I submitted it via the "Feedback" link on the page as "Translation quality" issue. That will send it to the localization team (we hope! 🤞). They perform their work internally, so we can't track the progress on it. However, you can report back to us on a new issue here in a few months if they don't update it. We can email a localization manager to look into it if they fail to take action on it. Thanks again!

**Comment by Thomas-S-B** [comment]
Thank You!
