### ISSUE TITLE
Update the "What's new in ASP.NET Core 9.0" for .NET 9 Release Candidate 2

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#33713]
### Description

Update the "What's new in ASP.NET Core 9.0" for .NET 9 Release Candidate 2

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/release-notes/aspnetcore-9.0.md

### Document ID

4e75ad25-2c3f-b28e-6a91-ac79a9c683b6

### Article author

@Rick-Anderson

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+4e75ad25-2c3f-b28e-6a91-ac79a9c683b6)

---
[Associated WorkItem - 322621](https://dev.azure.com/msft-skilling/Content/_workitems/edit/322621)

**Comment by guardrex** [comment]
Noting that for Blazor, request streams is on #33693, which is scheduled for review in a couple of weeks.

**Comment by guardrex** [comment]
Yes, it wasn't on whatever list I started with for 9.0. I discovered and added it as soon as I became aware. I'm ready to move forward with that PR after the assigned engineer comes in to assist with the two known open questions.

**Comment by tdykstra** [comment]
It looks like we don't have anything at all new for RC2 -- is that correct?

**Comment by danroth27** [comment]
## Updated to latest Bootstrap, jQuery, and jQuery Validation versions

The ASP.NET Core project templates and libraries have been updated to use the latest versions of Bootstrap, jQuery, and jQuery Validation, specifically:

* Bootstrap 5.3.3
* jQuery 3.7.1
* jQuery Validation 1.21.0

**Comment by danroth27** [comment]
@tdykstra Just the version updates for Bootstrap, JQuery, and jQuery Validation.
