### ISSUE TITLE
An improved debugging experience for Blazor WebAssembly apps 

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33728]
@guardrex  I couldn't find a dup. Do you own this?

`author: daroth` 
Data types shown in the debugger now match the expected .NET data types. - Type members and member visibility use expected icons. - The displayed call stack is cleaned up to only shows the .NET call stack and correctly honors the *Just My Code* setting. - The modules window is now supported. - Expression evaluation support in the Immediate window and for watches and conditional breakpoints is expanded and improved. To enable the new debugging experience simply update your Blazor app to target .NET 9.

[Internal only: blazor-wasm-debugger-improvements](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fmsft-skilling%2FContent%2F_workitems%2Fedit%2F310642&data=05%7C02%7CRick.Anderson%40microsoft.com%7C5f492b096a09458a799708dcde4b9373%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638629663380811899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uIwn94fKvRl4tlLy99Cv%2FwLzION7%2FdCaE4CmDo3PKqU%3D&reserved=0)

**Comment by guardrex** [comment]
I'll check on this; but because we mostly don't document tooling features, we might not be covering these ... they're just things that now work that didn't work before.

**Comment by Rick-Anderson** [comment]
> I'll check on this; but because we mostly don't document tooling features, we might not be covering these ... they're just things that now work that didn't work before.

Maybe @ghogen is responsible and you review it?

**Comment by guardrex** [comment]
I doubt it. Usually, absent tooling features just catch up in the background without any fanfare. If we had to say that something wasn't work, that gets called out. That's why I need to check those items to confirm that we didn't say anything about a broken/missing feature. Even if I don't find any doc changes to make, I can drop these remarks into the *Migration* article just to surface them.

**Comment by guardrex** [comment]
I checked ... we're good here 👍. No changes to the coverage are required because these features failing to work in the past weren't covered by the article. Closing now.
