### ISSUE TITLE
Scaffold Identity into an MVC project without existing authorization doesn't work

### ISSUE THREAD

**Issue by craigs100** [dotnet/AspNetCore.Docs#33737]
### Description

Scaffold Identity into an MVC project without existing authorization doesn't work in that DB Context doesn't get built and therefore the migration won't run.  I assumed this section of the document is for "back fitting" authentication to an existing project. It already has a DB Context. If Identity needs it's own special DB Context then something needs to generate it and connect to the existing DB.  This seems to have been missed.

I've spent days on this and I'm no nearer getting it installed.  I've been using the CLI approach as I'm using Rider on Linux and building a DotNet Core 8.0 project which works fine in all other respects.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-8.0&tabs=net-cli

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/scaffold-identity.md

### Document ID

3e25547b-e2c9-6634-2c38-2a77207f17d4

### Article author

@Rick-Anderson

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+3e25547b-e2c9-6634-2c38-2a77207f17d4)

**Comment by Rick-Anderson** [comment]
Can you open this issue in https://github.com/dotnet/Scaffolding?
