### ISSUE TITLE
ROPC: remove building-real-world-cloud-apps-with-windows-azure

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#33742]
[[building-real-world-cloud-apps-with-windows-azure](https://github.com/dotnet/AspNetDocs/tree/main/aspnet/aspnet/overview/developing-apps-with-windows-azure/building-real-world-cloud-apps-with-windows-azure)

remove and redirect

can [Free ebook: Building Cloud Apps with Microsoft Azure](https://learn.microsoft.com/en-us/archive/blogs/microsoft_press/free-ebook-building-cloud-apps-with-microsoft-azure) be removed?

---
[Associated WorkItem - 320291](https://dev.azure.com/msft-skilling/Content/_workitems/edit/320291)

**Comment by wadepickett** [comment]
Thanks Rick, by "remove" you mean delete or do you mean archive?  I am guessing you mean delete but good to verify of course.

For this: "can [Free ebook: Building Cloud Apps with Microsoft Azure](https://learn.microsoft.com/en-us/archive/blogs/microsoft_press/free-ebook-building-cloud-apps-with-microsoft-azure) be removed?"

What you want here is for me to verify with the dev team if they are OK with it all being deleted and if so delete it?  (or archive if you meant archive).

Thanks.

**Comment by Rick-Anderson** [comment]
I think the topic is archived. It has no value but lots of risk. No need for approval, delete them all. I don't care if you skip redirect either but you could redirect to azure if you like.

**Comment by wadepickett** [comment]
@jongalloway, This content [building-real-world-cloud-apps-with-windows-azure](https://github.com/dotnet/AspNetDocs/tree/main/aspnet/aspnet/overview/developing-apps-with-windows-azure/building-real-world-cloud-apps-with-windows-azure) was used by web camps many years ago.  Before deleting it, I figured it would be good to check in with you first to see if you have an opinion on the redirect:

I think we can redirect to this which would be still helpful and more current, sound good to you?:
[Create cloud-native apps and services with .NET and ASP.NET Core - Training | Microsoft Learn](https://learn.microsoft.com/en-us/training/paths/create-microservices-with-dotnet/)

**Comment by wadepickett** [comment]
It looks like the archived blog mentioning the eBook here [Free ebook: Building Cloud Apps with Microsoft Azure](https://learn.microsoft.com/en-us/archive/blogs/microsoft_press/free-ebook-building-cloud-apps-with-microsoft-azure) provides a link to the eBook itself but that link is already redirected to the top of the training content and the eBook has been removed.
