### ISSUE TITLE
Targets won't run before or after publishing from VS 2022

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33759]
### Description

Verbatim:

> Targets won't run before or after publishing when publishing a .NET core console app using VS 2022 GUI. It must be mentioned in the documentation.https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-8.0#run-a-target-before-or-after-publishing

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md

### Document ID

2db330b4-e830-715f-0a15-e406f85e1d3b

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+2db330b4-e830-715f-0a15-e406f85e1d3b)

**Comment by Rick-Anderson** [comment]
Dup of #30013
