### ISSUE TITLE
x-client-X-MS-CLIENT-PRINCIPAL-NAME header is only available on the first call to oninitialized

### ISSUE THREAD

**Issue by tdykstra** [dotnet/AspNetCore.Docs#33760]
### Description

if you deploy your code in app service and have app service check authentication, the x-client-X-MS-CLIENT-PRINCIPAL-NAME header is only available on the first call to oninitialized()... so disabling is probably necessary and needs to be documented.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/lifecycle.md

### Document ID

4871f4f7-9cf6-ac7a-0f21-c65d34bd1119

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+4871f4f7-9cf6-ac7a-0f21-c65d34bd1119)

**Comment by guardrex** [comment]
I assume this is an internal feedback item, so I can't discuss this with the dev.

That task wouldn't be handled that way in a Blazor app. The auth state provider can establish a claim from the header. And ...

> disabling is probably necessary and needs to be documented

... makes no sense without additional context.
