### ISSUE TITLE
Minor syntax/style fix

### ISSUE THREAD

**Issue by gstoynev-arrowstream** [dotnet/AspNetCore.Docs#33780]
### Description

[Enter feedback here]
This is not that significant - just style:
I see this in the document: 
protected async override Task OnAfterRenderAsync(bool firstRender)

should be:
protected override async Task OnAfterRenderAsync(bool firstRender)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md

### Document ID

af240267-89c0-f192-7807-cf426001ad8d

### Article author

@guardrex

**Comment by guardrex** [comment]
Thanks @gstoynev-arrowstream ... I'll fix this right now 🏃‍♂️.
