### ISSUE TITLE
Blazor host and deploy: Configure the app base path should mention that app base path only applies to the following paths

### ISSUE THREAD

**Issue by tobbi** [dotnet/AspNetCore.Docs#33797]
### Description

While following the steps to configure the app base path, I noticed that it won't work after I added the tag to my index.html document. It took me a while to figure out that the base element needs to be added before every other element that uses relative sources.

https://www.seoclarity.net/resources/knowledgebase/glossary/base-tags

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#configure-the-app-base-path

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/host-and-deploy/index.md

### Document ID

c82cf121-831d-75dd-a796-c735aad3b3e9

### Article author

@guardrex

**Comment by guardrex** [comment]
Hello @tobbi ... I don't understand your remark ...

> the base element needs to be added before every other element that uses relative sources.

Can you explain further and/or use examples to clarify?

**Comment by tobbi** [comment]
> Hello @tobbi ... I don't understand your remark ...
> 
> > the base element needs to be added before every other element that uses relative sources.
> 
> Can you explain further and/or use examples to clarify?

I published a blazor app in order to help you understand what I mean. This app loads:
http://4.233.87.237/iistest_markus/

This is a working blazor app. If you look at the source code of the index.html page, you can see it shows this at the beginning of the <head> tag (line 5):
```
    <base href="/iistest_markus/" />
```

In order to make you understand, I then copied the entire directory contents of my blazor app into a new directory and created another IIS app, adapting the base href path to the path of the new app, but adding it at the bottom of the <head> element instead of the beginning (line 13):
http://4.233.87.237/iistest_markus_wrongbase

```
<base href="/iistest_markus_wrongbase/" />
```

It appears that the placement of the <base> tag is important and that the <base> tag only applies to the following resource paths. This is not apparent from the documentation.

**Comment by tobbi** [comment]
Furthermore, you can verify if you take a look at the loaded assets (e.g. using Development Tools) that it tries to use the old path in the wrongbase app until you specify a new one.

**Comment by tobbi** [comment]
Even Mozilla Developer Network at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base writes this:

Warning: A <base> element must have an href attribute, a target attribute, or both. If at least one of these attributes are specified, **the <base> element must come before other elements with attribute values that are URLs, such as a [&lt;link&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)'s href attribute.**

**Comment by guardrex** [comment]
> It appears that the placement of the tag is important and that the tag only applies to the following resource paths. This is not apparent from the documentation.

Gotcha! Thanks for clarifying. I'll schedule this for work.
