### ISSUE TITLE
Cover that the default SQLite dB doesn't support automatic concurrency tokens

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#33799]
### Description

I found out why the sample app doesn't support concurrency via the automatic concurrency token. The sample app uses a SQLite dB, and SQLite doesn't support this concurrency feature OOB. Call this out in the article.

Reference: https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=fluent-api#native-database-generated-concurrency-tokens

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/blazor-ef-core.md

### Document ID

2ebc5e4d-bab4-6d30-9018-9a712c482236

### Article author

@guardrex

**Comment by guardrex** [comment]
@Rick-Anderson ... Not sure what's gone wrong, but our auto-labeling (`aspnet-core/svc` ... and `blazor/subsvc` via `docfx.json`) aren't working for issues opened from topics. Did Andy do something recently that may have broken it, or perhaps something else that changed behind the scenes?

**Comment by Rick-Anderson** [comment]
> @Rick-Anderson ... Not sure what's gone wrong, but our auto-labeling (`aspnet-core/svc` ... and `blazor/subsvc` via `docfx.json`) aren't working for issues opened from topics. Did Andy do something recently that may have broken it, or perhaps something else that changed behind the scenes?

@adegeo
