### ISSUE TITLE
Missing `nameof`?

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/AspNetCore.Docs#33821]
### Description

From https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#bind-hierarchical-configuration-data-using-the-options-pattern

![Position](https://github.com/user-attachments/assets/ce4613c8-5c8a-4ad7-a6a2-22887d20773a)

Looking at phrase 

> In the preceding code, Position is not bound. The Position field is used so the string "Position" doesn't need to be hard coded in the app when binding the class to a configuration provider.

and code

```csharp
var positionOptions = new PositionOptions();
        Configuration.GetSection(PositionOptions.Position).Bind(positionOptions);
```

one could think that `GetSection` could have some magical capabilities of understanding figure `GetSection(nameof(PositionOptions))` but more likely there is some goulash in wording.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/index.md

### Document ID

ba2254a0-ea8e-9b28-e94b-edd0fc58c043

### Article author

@tdykstra

**Comment by tdykstra** [comment]
I don't see the problem here -- the existing code and text looks fine to me.

**Comment by bravequickcleverfibreyarn** [comment]
I shall clarify:

> The Position field is used so the string "Position" doesn't need to be **hard coded** in the app when binding the class to a configuration provider.

In fact `string` `"Position"` is hardcoded to app. It is _value_ of `public const string Position`. So:

- Either this refers to other place in app, likely _startup/program_ class, which seems to.
- Or there is some degree of confusion.

I see my wrong now, nonetheless I would still vote for little clarification:

- `const` _fields_ are unlikely to be ever bindable
- settings does not have property `Position` so no-bindability is not proven at all
- suitability of hardcoded "Position" placement is rather driven by project politics that any of binder capabilities.

### Example:

```json
  "Position": {
    "Position": "not-bindable",
    "Title": "Editor",
    "Name": "Joe Smith"
  }
```

```csharp
public class PositionOptions
{
    public string Position = "Position";

    public string Title { get; set; } = String.Empty;
    public string Name { get; set; } = String.Empty;
}
```


_An options class:_

_- Must be non-abstract with a public parameterless constructor._
_- All public read-write properties of the type are bound._
_- Fields are not bound. In the preceding code, `Position` property of `PositionOptions` is not bound._
_- <mark>"Position" section name is aptly placed into configuration model.</mark>_
