### ISSUE TITLE
Startup.cs doesn't exist?

### ISSUE THREAD

**Issue by IsaacDeSnuts69** [dotnet/AspNetCore.Docs#33841]
### Description

I was trying to follow this tutorial but I didn`t find the "startup.cs" file it mentions in the first part as if it was automatically created by the mvc template

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/data/ef-mvc/index.md

### Document ID

8f0488f1-adc0-b42c-9549-b4028d4317d6

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+8f0488f1-adc0-b42c-9549-b4028d4317d6)

---
[Associated WorkItem - 327375](https://dev.azure.com/msft-skilling/Content/_workitems/edit/327375)

**Comment by tdykstra** [comment]
This tutorial series has not been updated from .NET 5.0. You can use the [Razor Pages](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro) version of it instead or you can use the [5.0 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/5.0). The Razor Pages version is updated to use [6.0 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/6.0), which is also not the latest SDK version but doesn't use Startup.cs so you won't see that discrepancy in the instructions.
