### ISSUE TITLE
Explain partition key for rate limiting

### ISSUE THREAD

**Issue by lonix1** [dotnet/AspNetCore.Docs#33845]
### Description

I'm using the partitioned rate limiter, which involves a *"partition key"* concept. Unfortunately, that's not explained anywhere.

After trial-and-error I realised:
- for incoming requests: it allows for policies-per-users, e.g. partitioned by username, IP address, access token
- for outgoing requests to external APIs: one would probably use a constant partition key, e.g. "aws-sns-service", "azure-auth-service"

It would be helpful to add a small explanation about this concept and how to use it.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/rate-limit.md

### Document ID

bb96b20f-0991-d6de-4d98-192cd469460f

### Article author

@tdykstra

**Comment by Rick-Anderson** [comment]
> After trial-and-error I realized: for incoming requests: it allows for policies-per-users, e.g. partitioned by username, IP address, access token

That's shown in a couple places.

[ASP.NET Core rate limiting middleware](https://blog.maartenballiauw.be/post/2022/09/26/aspnet-core-rate-limiting-middleware.html) goes into even more detail.

`@Kahbazi @maartenba` can be called in more info needed and backup `@wtgodbe`

**Comment by tdykstra** [comment]
I suspect the reason it was closed was the thought that the means for answering the question had been provided -- either by checking the referenced blog post or by asking one of the individuals tagged as resources if more information was needed.
