### ISSUE TITLE
Statically set the server-side culture: Where to add app.UseRequestLocalization

### ISSUE THREAD

**Issue by Schoof-T** [dotnet/AspNetCore.Docs#33847]
# Issue description

In my Blazor Server application I'm trying to statically set the culture for every user (to en-GB). I found the following guidance: https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-8.0#statically-set-the-server-side-culture

However it is not clear to me where to add `app.UseRequestLocalization("en-GB");`. The document says "immediately after Routing Middleware". But as far as I can see Blazor Server does not add any Routing Middleware?

Below is the whole Program.cs from the Template:

```
using BlazorApp2.Components;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseStaticFiles();
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
```

I am also hosting the application in IIS, having set the Application Pool as follows:
![Image](https://github.com/user-attachments/assets/d326b502-dfdb-441f-8589-ef40568dff82)

The Identity is a an account, with limited access.

What is your recommendation?

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

* [ ] .NET Core
* [x] .NET 5.0 or later
* [ ] .NET Framework
* [ ] .NET Standard

**Comment by guardrex** [comment]
Hello @Schoof-T ... In the future, please use the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by guardrex** [comment]
As of 8.0, this sentence should change. The main doc set article states to call the middleware "before any middleware that might check the request culture (for example, `app.UseMvcWithDefaultRoute()`)." In this case for Blazor apps, I'll update the sentence using similar language and tell readers to place the middleware before the call to `MapRazorComponents`.

Leave this issue open. It will close automatically after I make the update.

Thanks for writing in on this! 👍

**Comment by Schoof-T** [comment]
Thank you @guardrex!

I'm not sure if this is the correct place to continue this discussion, but having set it up as documented now, it does not work for me.

And I added `app.UseRequestLocalization("en-GB")` just before `MapRazorComponents`.

![Image](https://github.com/user-attachments/assets/dd3cbc59-f9b9-45a0-ae75-2c473ba5def8)
This is the result of the deployed website in IIS. The decimal seperator should be a ".", and the thousand seperator should be a ",".

**Comment by guardrex** [comment]
Off the top of my head, I didn't think that Static Files Middleware (or Map Static Assets Middelware for the upcoming 9.0 or later) used the request culture, but that's a guess. I'll need to research that further this afternoon.

I'll re-open this issue. I have time later today to look more closely at this issue. I'll get back to you.

**Comment by guardrex** [comment]
I'm tied up today (Tuesday). I should be able to take a look tomorrow morning 🤞.

**Comment by guardrex** [comment]
BTW ... You said "Blazor Server application," but the code indicates that you're using a Blazor Web App. We have to know because these apps use different API. I'll assume it's 8.0.

**Comment by guardrex** [comment]
I made some mods to the `CultureExample1` component to study the API behavior that you're using ...

```razor
@page "/culture-example-1"
@using System.Globalization

<h1>Culture Example 1</h1>

<ul>
    <li><b>CurrentCulture</b>: @CultureInfo.CurrentCulture</li>
    <li><b>CurrentUICulture</b>: @CultureInfo.CurrentUICulture</li>
</ul>

<h2>Rendered values</h2>

<ul>
    <li><b>Date</b>: @dt</li>
    <li><b>Number</b>: @number.ToString("N2")</li>
</ul>

<h2><code>&lt;input&gt;</code> elements that don't set a <code>type</code></h2>

<p>
    The following <code>&lt;input&gt;</code> elements use
    <code>CultureInfo.CurrentCulture</code>.
</p>

<ul>
    <li><label><b>Date:</b> <input @bind="dt" /></label></li>
    <li><label><b>Number:</b> <input @bind="number" /></label></li>
</ul>

<h2><code>&lt;input&gt;</code> elements that set a <code>type</code></h2>

<p>
    The following <code>&lt;input&gt;</code> elements use
    <code>CultureInfo.InvariantCulture</code>.
</p>

<ul>
    <li><label><b>Date:</b> <input type="date" @bind="dt" /></label></li>
    <li><label><b>Number:</b> <input type="number" @bind="number" /></label></li>
</ul>

<h2>Additional</h2>

<ul>
    <li><b>Current: Decimal Separator</b>: @currentCultureNumberDecimalSeparator</li>
    <li><b>Current: Group Separator</b>: @currentCultureNumberGroupSeparator</li>
    <li><b>Current UI: Decimal Separator</b>: @currentUICultureNumberDecimalSeparator</li>
    <li><b>Current UI: Group Separator</b>: @currentUICultureNumberGroupSeparator</li>
</ul>

@code {
    private DateTime dt = DateTime.Now;
    private double number = 1999.69;
    private string? currentCultureNumberDecimalSeparator;
    private string? currentCultureNumberGroupSeparator;
    private string? currentUICultureNumberDecimalSeparator;
    private string? currentUICultureNumberGroupSeparator;

    protected override void OnInitialized()
    {
        var currentCulture = CultureInfo.CurrentCulture;
        NumberFormatInfo nfi = currentCulture.NumberFormat;
        currentCultureNumberDecimalSeparator = nfi.NumberDecimalSeparator;
        currentCultureNumberGroupSeparator = nfi.NumberGroupSeparator;

        var currentUICulture = CultureInfo.CurrentUICulture;
        NumberFormatInfo nfui = currentUICulture.NumberFormat;
        currentUICultureNumberDecimalSeparator = nfui.NumberDecimalSeparator;
        currentUICultureNumberGroupSeparator = nfui.NumberGroupSeparator;
    }
}
```

I'm not seeing the behavior that you report. I get the expected result ...

![Image](https://github.com/user-attachments/assets/15dd9615-4a0e-4e0b-b05a-2a1c602cc092)

Open an issue for the product unit at ...

https://github.com/dotnet/aspnetcore/issues

Please add ...

```
cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/33847
```

... to the bottom of your opening comment so that I can follow along.

**Comment by Schoof-T** [comment]
> BTW ... You said "Blazor Server application," but the code indicates that you're using a Blazor Web App. We have to know because these apps use different API. I'll assume it's 8.0 with global Server rendering.

Sorry for the confusion. It's a project created with the 'Blazor Web App' template, .NET 8 and Global Server rendering.

**Comment by Schoof-T** [comment]
> I made some mods to the `CultureExample1` component to study the API behavior of the API that you're using ...
> ...

I created a ticket on the ASP.NET Core github repo. Thanks!

**Comment by guardrex** [comment]
Great ... I'll keep an 👁 on that. I'll likely re-open this for article work after they respond with why that's happening and what you can do about it.
