### ISSUE TITLE
The description of interaction of Authorize and AllowAnonymous attrbiutes could be improved.

### ISSUE THREAD

**Issue by voroninp** [dotnet/AspNetCore.Docs#33866]
### Description

There's a note:

> If you combine [AllowAnonymous] and an [Authorize] attribute, the [Authorize] attributes are ignored.

This is not completely true, and below you provide an indirect proof:
> Authentication middleware is not short-circuited but doesn't need to succeed.

It's worth explicitly saying, that schemes specified in `AuthenticationSchemes` property of `[Authorize]` attribute will be used for authentication.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-8.0#use-the-authorize-attribute

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authorization/simple.md

### Document ID

cea5942d-fb01-f5bf-3b63-25873d5b79cf

### Article author

@Rick-Anderson

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+cea5942d-fb01-f5bf-3b63-25873d5b79cf)

**Comment by Rick-Anderson** [comment]
We could change it to ***effectively ignored***, but that's just semantics. I don't find the current writing problematic.

**Comment by voroninp** [comment]
Let me explain my confusion.

Here's the question: 

— How does one ensure that authentication for a particular (not default) scheme is executed (auth handler gets called) but a successful result is optional?

Default authentication is always executed by Authentication middleware, and not default one is the responsibility of Authorize middleware.

For me it was not immediately obvious that the combination of `Authorize` with the scheme and `AllowAnonymous` attributes works. I had to chack that scheme from the attribute will be used.
