### ISSUE TITLE
Js interop examples

### ISSUE THREAD

**Issue by JelleHissink** [dotnet/AspNetCore.Docs#33919]
### Description

Should the documentation explain the new `ResourceAssetCollection` behaviour? 

eg. 
```csharp
JsInterop.InvokeAsync("import", Assets["blah.js"])
```

My main question was, if the ResourceAssetCollection can be accessed, or provided somewhere using an injected interface. I always tend to encapsulate javascript modules with a csharp class. However I inject the IJSInterop there, but have no way to resolve the assets.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/location-of-javascript.md

### Document ID

af240267-89c0-f192-7807-cf426001ad8d

### Article author

@guardrex

**Comment by guardrex** [comment]
@adegeo ... I saw your earlier response on the other issue ("it's been hard to test in production to reproduce the error"). It failed again here ... no labels at all.

Perhaps, a GH Action would be a better way to apply the initial issue labels. I think if Repoman runs and tries to apply the labels a second time that it will just no-op when they're already there. I'll set that up for a test, and we can see what happens. I'll just set up the test for the Blazor node for now.
