### ISSUE TITLE
Document warning that `Scaffolding May Fails with Old-Style Entrypoint Programs`

### ISSUE THREAD

**Issue by bukowa** [dotnet/AspNetCore.Docs#33940]
- https://github.com/dotnet/Scaffolding/issues/3045

Scaffolding commands may not work correctly with applications using older entrypoint styles (e.g., public static void Main). Modern ASP.NET Core scaffolding assumes the minimal hosting model (WebApplication.CreateBuilder) for program initialization. Using the traditional Startup class or non-minimal hosting entrypoints could lead to errors or incomplete scaffolding output.

\/
https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-8.0&tabs=visual-studio

**Comment by guardrex** [comment]
Hello @bukowa ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by bukowa** [comment]
> Hello [@bukowa](https://github.com/bukowa) ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

Thanks, done. Would be cool to have this information in the README.md of this repository.

**Comment by guardrex** [comment]
When **New issue** is selected for a doc issue, the GH template states it ...

> # Before you open an issue
>
> If the issue is with an ASP.NET Core document:
> 
> * Do **not** open a new issue using this form.
> * Open the issue using the **Open a documentation issue** link and feedback form at the bottom of the article. 

The problem that I see is that we don't have that for the "blank issue" template. I'll look now and see if we can add that.

**Comment by bukowa** [comment]
@guardrex True, would it be possible here (*when creating new issue on github), that after clicing doc issue it would automatically ask for the url and fill the template? 
So we don't have to scroll to the bottom (*and leave github) of the page to click it ?

![Image](https://github.com/user-attachments/assets/5779bcca-8d00-484c-9b0c-89f568a066f9)

**Comment by guardrex** [comment]
I'm not sure about that ... pinging @Rick-Anderson who might know.

For now, I just put that PR up to at least add it to the README.
