### ISSUE TITLE
wrong namespace

### ISSUE THREAD

**Issue by shiruide** [dotnet/AspNetCore.Docs#33968]
### Description

The name space of TodoItem.cs should be TodoList.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md

### Document ID

23f2cad2-31f9-d5d1-671c-5613fb812b19

### Article author

@guardrex

**Comment by guardrex** [comment]
I think this happened because I might be pulling code from the sample app, where the namespace is `BlazorSample`. I'll inline that code into the article to fix this. Thanks for the report, @shiruide.
