### ISSUE TITLE
Revise to show Blazor instead of MVC or Razor Pages

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#33967]
### Description

Blazor is now our recommended approach to building web UI with ASP.NET Core. We should update this ASP.NET Core Fundamentals overview to show Blazor instead of MVC or Razor Pages

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-8.0&tabs=macos

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/index.md

### Document ID

8e663029-63b9-2622-f852-9f8a2ec70db3

### Article author

@tdykstra

**Comment by guardrex** [comment]
This is a dup of #33127.

**Comment by danroth27** [comment]
> This is a dup of [#33127](https://github.com/dotnet/AspNetCore.Docs/issues/33127).

Whoops! 😆
