### ISSUE TITLE
There is a typo in the French translation of the title for the output cache page

### ISSUE THREAD

**Issue by alexandre-ava** [dotnet/AspNetCore.Docs#33975]
### Description

The title should be "Intergiciel de mise en cache de sortie dans ASP.NET Core" instead of "Intergiciel de mise en cache de sorite dans ASP.NET Core"

### Page URL

https://learn.microsoft.com/fr-fr/aspnet/core/performance/caching/output?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/performance/caching/output.md

### Document ID

cb423d54-ee93-6dfd-87bb-ed79dff8b7b6

### Article author

@tdykstra

**Comment by guardrex** [comment]
Hello @alexandre-ava ... Please use the **Feedback** form to report it ...

![Image](https://github.com/user-attachments/assets/48322619-066c-40d7-b8b9-60fce2c6b084)

When you select the button for "No" (the page isn't helpful), there's an entry for the type of feedback: 👉  "Quality of the translation" 👈
