### ISSUE TITLE
I can't find the steps to create client and server

### ISSUE THREAD

**Issue by shiruide** [dotnet/AspNetCore.Docs#33988]
### Description

I am wondering if anyone read through and followed the step of this tutorial. The first step is create BlazorSignalRApp. However, in the next steps, it mentions BlazorSignalRApp.Client project, and later there is BlazorSignalRApp.Server project. 
Did the author really followed the steps? 

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/signalr-blazor?view=aspnetcore-8.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/signalr-blazor.md

### Document ID

85af7a99-672c-0438-dcc2-e8edfaf70c54

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+85af7a99-672c-0438-dcc2-e8edfaf70c54)

**Comment by guardrex** [comment]
There might be a problem that developed when we introduced coverage for Blazor Web Apps. I'll check on it and get back to you.

**Comment by guardrex** [comment]
There's no reference to `BlazorSignalRApp.Server` ... where do you see that?

The `BlazorSignalRApp.Client` project is generated for a Blazor Web App when you select Interactivity location: **Per page/component** when creating the app.

The app should look like what you see in the sample, which is cross-linked ...

https://github.com/dotnet/blazor-samples/tree/main/9.0/BlazorSignalRApp

**Comment by shiruide** [comment]
Sorry, my bad. I missed the option of webassembly.
Thanks for quick response. Just curious if this is answered by AI or a real person.


Shirui Xu


Software Engineer

***@***.******@***.***>

Office:  314-736-4224

[cid:243eb79b-5c14-4a3e-a444-9e4226bef705]

641 Spirit Valley Central Dr.

Chesterfield MO 63005

www.DEdesignworks.com<http://www.dedesignworks.com/>
This email transmission may contain information controlled for export purposes under the U.S. International Traffic in Arms Regulations (ITAR) and is intended for the recipient only. No export, sale, transfer, release or other disposition of this information is permitted without prior authorization from the U.S. Government.

________________________________
