### ISSUE TITLE
More explanation and explicit guidelines needed

### ISSUE THREAD

**Issue by ialbert-AUT** [dotnet/AspNetCore.Docs#34075]
### Description

The documentation says:
"Two-way binding to a property with get/set accessors requires discarding the [Task](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) returned by [EventCallback.InvokeAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.eventcallback.invokeasync). For two-way data binding, we recommend using @bind:get/@bind:set modifiers. For more information, see the @bind:get/@bind:set guidance in the earlier in this article."

It is not clear where the Task and InvokeAsync is also not clear about supported c# property usage. The beginning of the article explicitly says you can bind to a c# property.

I would need more explicit guidlines for the scenarios like:
- binding to field -> no validation, no logic --> no need for event:oninput
- :after -> async operation (debounce problem, Rx etc)
- :get / :set -> use then validation logic needed, value can be modified in the setter, event:oninput is ok to use here.
- C# property get-set -> don't use with event:oninput? don't modify value in the setter? only for formatting and type conversion with onchange?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/data-binding.md

### Document ID

3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc)

**Comment by guardrex** [comment]
Hello @ialbert-AUT ...

> It is not clear where the Task and InvokeAsync is also not clear about supported c# property usage. The beginning of the article explicitly says you can bind to a c# property.

It was leftover from the <7.0 era before binding with `:get`/`:set` appeared. I'll adjust that remark when I work #33994.

To learn more about the prior approach for two-way binding with a property and discarding the Task, see the 6.0 version of that section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/data-binding?view=aspnetcore-6.0#bind-across-more-than-two-components

With regard to the other scenarios that you mentioned, I'd like to discuss them with one of the product unit engineers. .NET 9 is releasing this week, and I'm working on some high priority security coverage at the moment. We'll circle back around to this issue shortly. Let's get past the current workload and .NET 9 release first ⛰⛏😅.

**Comment by guardrex** [comment]
**UPDATE (11/22)**: I hope to reach this soon (along with #33994), but Mackinnon Buck is still unavailable to discuss the subject. We'll discuss this with him when he's gets back. I think he's OOF 🏖 at the moment.

**Comment by guardrex** [comment]
**UPDATE (12/9)**: This will be fixed on the existing (earlier) issue #33994.
