### ISSUE TITLE
Clean up and Connect ASP0028 to TOC

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#34090]
### Description

As soon as #34089 merges

### Page URL

https://review.learn.microsoft.com/en-us/aspnet/core/diagnostics/asp0028?view=aspnetcore-10.0&branch=pr-en-us-34084

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/diagnostics/asp0028.md

### Document ID

af008025-771a-d712-decc-00598dc31606

### Article author

@DeagleGross

---
[Associated WorkItem - 343312](https://dev.azure.com/msft-skilling/Content/_workitems/edit/343312)

**Comment by damienbod** [comment]
Created a new issue related to this: https://github.com/dotnet/AspNetCore.Docs/issues/34177
