### ISSUE TITLE
Not latest version INCLUDE breaks on out-of-support moniker line

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#34100]
@Rick-Anderson @tdykstra @wadepickett 

I went to activate the not-latest version INCLUDE in my >=8.0 articles, but the newer out-of-support section of the INCLUDE breaks the file ...

> Line 6: [Warning] No  intersection between zone and file level monikers. The result of zone  level range string '= aspnetcore-7.0 \|\| = aspnetcore-5.0 \|\| =  aspnetcore-3.0 \|\| = aspnetcore-3.1 \|\| = aspnetcore-2.0' is  'aspnetcore-2.0', 'aspnetcore-3.0', 'aspnetcore-3.1', 'aspnetcore-5.0',  'aspnetcore-7.0', while file level monikers is 'aspnetcore-10.0',  'aspnetcore-8.0', 'aspnetcore-9.0'.

That section of the file can't be there until .NET 9 (STS) falls out of support (i.e., a `|| = aspnetcore-9.0` is added to the conditional) for any >=8.0 articles, so either that section of the file has to go, or I'll need to create a Blazor-specific version of the file without that section. Which way do you want me to go to solve it? 👂

**Comment by tdykstra** [comment]
What is different about the Blazor docs compared to the non-Blazor docs?

**Comment by guardrex** [comment]
Perhaps, a new INCLUDE in the main doc set just for new 8.0 articles would be best. It would be the same as the existing file but without the out-of-support content in it.

**Comment by guardrex** [comment]
# 🤔 

I wonder if parentheses are supported in these ranges?

```
:::moniker range="< aspnetcore-9.0 && (= aspnetcore-7.0 || = aspnetcore-5.0 || = aspnetcore-3.0 || = aspnetcore-3.1 || = aspnetcore-2.0)"
```

I guess that's worth a shot, but I think it's going to 💥. I'll find out ...... brb ...........

**Comment by guardrex** [comment]
I'll add a file to move this forward.
