### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by aoxixixp** [dotnet/AspNetCore.Docs#34132]
### Description

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-9.0#build-a-todo-list-blazor-app
下的“向 Todo 组件添加 AddTodo 方法，并使用 @onclick 属性来为按钮注册方发。 选择按钮时，会调用 AddTodo C# 方法：”的“方法”写成了“方发”

### Page URL

https://learn.microsoft.com/zh-cn/aspnet/core/blazor/tutorials/build-a-blazor-app?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/build-a-blazor-app.md

### Document ID

23f2cad2-31f9-d5d1-671c-5613fb812b19

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+23f2cad2-31f9-d5d1-671c-5613fb812b19)

**Comment by guardrex** [comment]
> Under "Add the AddTodo method to the Todo component and use the @OnClick attribute to register the button for the button. When the button is selected, the AddTodo C# method is called:" the "method" is written as "party"

Hello @aoxixixp ...

***When looking at the non-English version of the article***, please use the **Feedback** form to report it (the word "Feedback" will be in a non-English language) ...

![Image](https://github.com/user-attachments/assets/48322619-066c-40d7-b8b9-60fce2c6b084)

When you select the button for "No" (translated), there's an entry for the type of feedback: 👉 "Quality of the translation" 👈 (also translated).

When you select that entry and describe the translation problem, the feedback goes to the localization team.
