### ISSUE TITLE
Attribute Routing and Binding Source Parameters works even without the [ApiController] Attribute

### ISSUE THREAD

**Issue by MaduraDias** [dotnet/AspNetCore.Docs#34144]
### Description

Attribute Routing and Binding Source Parameters works even without the [ApiController] Attribute. Please see the image below.

Please advise.

![Image](https://github.com/user-attachments/assets/d7c8f862-7d53-4953-99d9-1637b642f849)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-9.0#apicontroller-attribute

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/index.md

### Document ID

263a7b64-2e42-bbfc-c1d3-61680438e1e4

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+263a7b64-2e42-bbfc-c1d3-61680438e1e4)

**Comment by Rick-Anderson** [comment]
At least right now. Doesn't hurt to add it.
