### ISSUE TITLE
Step states using .net 8 for .net 9 article

### ISSUE THREAD

**Issue by BradleySharp** [dotnet/AspNetCore.Docs#34145]
### Description

Confirm the Framework is .NET 8.0 (Long Term Support).

I think should be:
Confirm the Framework is .NET 9.0
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-9.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/first-web-api.md

### Document ID

95f2549e-29f9-e31a-b4d0-432b971643ff

### Article author

@wadepickett

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+95f2549e-29f9-e31a-b4d0-432b971643ff)

**Comment by wadepickett** [comment]
This topic was not updated to .NET 9. It needs to be rewritten and new app sample provided that accounts for template changes and use OpenAPI as we are doing going forward.

Closing this issue since the update tracking for this topic and its app sample/code will be with existing issue #34148
