### ISSUE TITLE
origin of 'totalEmployees' variable in code example not clear

### ISSUE THREAD

**Issue by NikolaJacques** [dotnet/AspNetCore.Docs#34149]
### Description

Not sure whether this is an issue or not, but in the code example below I noticed that a 'totalEmployees' variable is used, which I cannot gather from context where it comes from / where it gets its value:

```
private async ValueTask<ItemsProviderResult<Employee>> LoadEmployees(
    ItemsProviderRequest request)
{
    var numEmployees = Math.Min(request.Count, **totalEmployees** - request.StartIndex);
    var employees = await EmployeesService.GetEmployeesAsync(request.StartIndex, 
        numEmployees, request.CancellationToken);

    return new ItemsProviderResult<Employee>(employees, **totalEmployees**);
}
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/virtualization.md

### Document ID

26ed2425-63ec-e206-edcb-e51f17edb844

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+26ed2425-63ec-e206-edcb-e51f17edb844)

**Comment by guardrex** [comment]
Hello @NikolaJacques ... It's just pulled via a method call elsewhere in the component, such as during initialization. I'll make a remark for that example. Leave this issue open, as it will close automatically when the PR merges later. Thanks for the issue!
