### ISSUE TITLE
Razor Pages: GenerateMvcApplicationPartsAssemblyAttributes has an incorrect description

### ISSUE THREAD

**Issue by edahlberg** [dotnet/AspNetCore.Docs#34161]
### Description

The **GenerateMvcApplicationPartsAssemblyAttributes** option still very much used in .NET 6+. It's used right there:

https://github.com/dotnet/sdk/blob/fc58e122239d2b640aac0584028dc820fee65b09/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets#L22

If you set it to false in .Net 8, MvcApplicationPartsAssemblyInfo won't be generated for your DLL. This can be easily observed with EmitCompilerGeneratedFiles enabled. Clearly this option is "used", since it has effects on the compilation.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/razor-pages/sdk.md

### Document ID

6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e)

**Comment by tdykstra** [comment]
GitHub Copilot explains it this way:

> It is true that `GenerateMvcApplicationPartsAssemblyAttributes` is not used in .NET 6 and later. This setting was used in earlier versions of ASP.NET Core to generate assembly attributes for MVC application parts, which helped with the discovery of controllers and views.

> In .NET 6 and later, the ASP.NET Core framework has improved mechanisms for discovering controllers and views, making this setting obsolete. The framework now automatically handles the discovery process without the need for this specific setting.

> If you are working with .NET 6 or later, you do not need to include or use `GenerateMvcApplicationPartsAssemblyAttributes` in your project configuration. The framework will manage the necessary assembly attributes internally.

> In .NET 6 and later, including .NET 8, the `GenerateMvcApplicationPartsAssemblyAttributes` setting is not used. The ASP.NET Core framework no longer relies on this setting to generate `MvcApplicationPartsAssemblyInfo` for your DLL.

> The `EmitCompilerGeneratedFiles` setting allows you to observe compiler-generated files, but it does not change the fact that `GenerateMvcApplicationPartsAssemblyAttributes` is obsolete in .NET 6 and later. The framework handles the discovery of MVC application parts without needing this setting.
