### ISSUE TITLE
.NET 9 is included in Visual Studio 2022 version17.12

### ISSUE THREAD

**Issue by SatyaKarki** [dotnet/AspNetCore.Docs#34176]
# Issue description
.NET 9 is included in Visual Studio 2022 version17.12 So we can update prerequisites : Visual Studio 2022 Preview as depicted in the image below.
![Image](https://github.com/user-attachments/assets/433401b3-4979-4f4c-846d-40257b82f55a)

**Comment by guardrex** [comment]
Hello @SatyaKarki ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by guardrex** [comment]
Here's the link to the article ...

https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-9.0&tabs=visual-studio

The **Open a documentation issue** link is at the bottom of the article.
