### ISSUE TITLE
authorization in .net core

### ISSUE THREAD

**Issue by Majidazadi12** [dotnet/AspNetCore.Docs#34204]
![Image](https://github.com/user-attachments/assets/ec1fdfb2-a4d2-41ef-9776-2ba63e6a6915)
![Image](https://github.com/user-attachments/assets/07474451-e69e-4fcb-9d12-e166c261581c)
hi.
i get these errors that is attached in my images here.when trying to test authorization in ,net core in microsoft document.any advice?thanks.
https://learn.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-8.0#create-the-starter-app

**Comment by guardrex** [comment]
Hello @Majidazadi12 ... Please re-open this issue using the **Open a documentation issue** link/feedback form at the bottom of the article. Use of the form adds metadata to your GitHub issue that cross-links the topic and pings the author automatically for a faster response.

**Comment by Majidazadi12** [comment]
i have some problem in implementing microsoft asp.net core authorization with sqlite not localDb.any advice?
