### ISSUE TITLE
Incorrect: Adopting EF Core's code-first approach speeds up the process of app development

### ISSUE THREAD

**Issue by beachseeker** [dotnet/AspNetCore.Docs#34208]
### Description

This is an opinion which is only true for persons with minimal experience working with the given DB.  All moderate to experienced DB developers will find using the native DB design tools easier than hacking through the model markup and relationship syntax required for EFCore.  Also, as of my last doc review, there are still elements in DBs which EFCore has no capability to model in code.  These are often useful or best-practice things that EFCore SHOULD support, and which are necessary to build high-capability, efficient DBs, but by using code-first are not available to the developer.  Finally, I believe this is bad advice leading to poor database design.  Using code-first, a beginner developer will not be exposed to the theory, full capability, and practical experience which is necessary to build a good DB.  

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/tutorials/movie-database-app/part-2?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/tutorials/movie-database-app/part-2.md

### Document ID

f9acc6f3-d6e2-ca66-9a66-7e0ea09aa38f

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+f9acc6f3-d6e2-ca66-9a66-7e0ea09aa38f)

**Comment by guardrex** [comment]
Hello @beachseeker ... I'll pass this one to Dan Roth, Principal Product Manager of .NET, to address. *Stand-by until he gets on here.*

**Comment by guardrex** [comment]
**UPDATE (12/11)**: Running late getting back to this. The team is tied up at the moment with other tasks. We'll get to this *ASAP* 🏃‍♂, hopefully soon!

**Comment by SteveSandersonMS** [comment]
@guardrex If you want to rephrase "speeds up the process" to "aims to speed up the process" that would seem fine to me and is a little more open to other points of view. But personally I don't feel strongly about this either way.

**Comment by guardrex** [comment]
I'll make that update now.

Thanks for your feedback generally, @beachseeker. AFAIK, Dan Roth either has seen this or will see it via my offline pings.
