### ISSUE TITLE
Document that QuickGrid will render additional empty rows and cells to fill in the final page of data

### ISSUE THREAD

**Issue by danroth27** [dotnet/AspNetCore.Docs#34211]
### Description

QuickGrid will render additional empty rows to fill in the final page of data when used with a Paginator. In .NET 9, it will also fill in empty data cells. This is intended to facilitate styling the QuickGrid so that it has a stable height and styling across all pages. Something like this:

```css
::deep tr {
    height: 2em;
}
```

Note that for `::deep` to work when using component specific styles for whatever component is the parent of the QuickGrid, the QuickGrid needs to have a wrapper element.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-9.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/quickgrid.md

### Document ID

564e71e3-82ed-ce23-4f9f-a00a58734a62

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+564e71e3-82ed-ce23-4f9f-a00a58734a62)

**Comment by guardrex** [comment]
@danroth27 ... This part is straightforward, and I'll get it into the article ...

> QuickGrid will render additional empty rows to fill in the final page of data when used with a Paginator. In .NET 9, it will also fill in empty data cells. This is intended to facilitate styling the QuickGrid so that it has a stable height and styling across all pages.

However, I'm confused on how that's related to row styling. Your example will style ***all rows***, not just the additional empty rows.

Outside of that, the problem of the border remains. The following will work as long as all of the populated row data cells have data. Do you want this workaround covered separately for >=9.0? ... and/or do you want the movie dB tutorial (>=9.0) to include guidance on it?

```css
::deep td:empty {
    border-bottom-width: 0;
}
```

**Comment by davem7714** [comment]
Any way to get the extra rows to not have the gridline?  I'm not real happy with the solution.  I'd rather the extra lines didn't show up or at least make it an option on the QuickGrid.

**Comment by guardrex** [comment]
@davem7714 ... See the guidance in the QuickGrid article to style the lines off of the non-data rows. You can't currently remove the extra rows using .NET alone.

**Comment by guardrex** [comment]
Here it is ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/quickgrid?view=aspnetcore-9.0&tabs=visual-studio#apply-row-styles

... scroll down to the second example.

**Comment by davem7714** [comment]
Thanks!  That did the trick.
