### ISSUE TITLE
BlazorWebAppOidc sample: incorrect CookieOidcRefresher implementation

### ISSUE THREAD

**Issue by albi005** [dotnet/AspNetCore.Docs#34235]
### Description

`CookieOidcRefresher` expects an ID token from the token endpoint. This seems wrong, based on the [spec](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse), [the Duende implementation](https://github.com/DuendeSoftware/foss/blob/551666e9c40975d8dd76c346f6b29321cacf791b/access-token-management/src/AccessTokenManagement.OpenIdConnect/UserTokenEndpointService.cs#L138) and the fact that it always fails in my app.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/blazor-web-app-with-oidc?view=aspnetcore-8.0&pivots=without-bff-pattern

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/blazor-web-app-with-oidc.md

### Document ID

c3346d3a-346b-8db4-2650-ec044b3f0dd9

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+c3346d3a-346b-8db4-2650-ec044b3f0dd9)

**Comment by halter73** [comment]
It looks like we need to determine whether the refresh token is really an ID token before indiscriminately reading claims from it. If it's not an ID token, we should probably just continue to use the old claims stored in the cookie. https://github.com/dotnet/aspnetcore/issues/58826 is also related to getting the right claims on refresh, but that's focused on refreshing claims from the /userinfo endpoint if it's enabled.

**Comment by guardrex** [comment]
So ... @halter73 ... do you want to transfer this issue to the PU repo, or should @albi005 open a new PU issue on this?

**Comment by albi005** [comment]
In the meantime, I think it would make sense to add a comment to the sample/docs noting that the refresh implementation might need to be updated depending on the Identity Provider.

**Comment by guardrex** [comment]
I can add whatever makes sense to add, but it's best if one of you who understands what the text should say write it in a comment here for publication, and then I'll edit it for style+grammar and place it in the article. If it should go in under a heading to help surface it in the article, give me proposed heading text as well.

**Comment by albi005** [comment]
## Token refresh

The sample includes code in `CookieOidcRefresher.cs` showing how to update the user's claims automatically when they expire. The current implementation expects to receive an ID token from the token endpoint in exchange for the refresh token. This ID token is then used to overwrite the user's claims.

The sample implementation doesn't include code for requesting claims from the UserInfo endpoint on token refresh. Refer to the following issue for an example on how to do that: https://github.com/dotnet/aspnetcore/issues/58826#issuecomment-2492738142

> [!NOTE]
> Some identity providers only return an access token when using a refresh token[^1]. You should handle this as needed.

[^1]: https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse


---

```md
## Token refresh

The sample includes code in `CookieOidcRefresher.cs` showing how to update the user's claims automatically when they expire. The current implementation expects to receive an ID token from the token endpoint in exchange for the refresh token. This ID token is then used to overwrite the user's claims.

The sample implementation doesn't include code for requesting claims from the UserInfo endpoint on token refresh. Refer to the following issue for an example on how to do that: https://github.com/dotnet/aspnetcore/issues/58826#issuecomment-2492738142

> [!NOTE]
> Some identity providers only return an access token when using a refresh token[^1]. You should handle this as needed.

[^1]: https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
```

---

I think this should go above the "Cryptographic nonce" section.

@halter73 could you please check if this is correct?

**Comment by guardrex** [comment]
Great ... I'm going to go ahead and update the PR with language closer to this.

We can take up the discussion over there on https://github.com/dotnet/AspNetCore.Docs/pull/34315.
