### ISSUE TITLE
https://learn.microsoft.com/en-us/answers/questions/573925/blazor-mouse-events-and-mouse-capture does not include @rendermode on line 2

### ISSUE THREAD

**Issue by Tandry** [dotnet/AspNetCore.Docs#34248]
### Description

The code does not work as presented.  Code requires @rendermode InteractiveAuto below @page in order to work properly.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/components/event-handling.md

### Document ID

5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+5e8ef502-ccf9-659d-f25a-0f8f3c75f6e0)

**Comment by guardrex** [comment]
Hello @Tandry ... That's true for ***all*** of the examples across the Blazor doc set that apply generally Blazor. Note that for Blazor WebAssembly, the app is always interactive; and unless otherwise stated, examples apply to Blazor WebAssembly, too, We also assume that devs had read the *Render Modes* article, which is early in the table of contents, before reaching these other articles and understand that no component example for Blazor Web Apps that requires interactivity is going to exhibit interactive behavior without an interactive render mode. For these reasons, we'll continue with the current approach for coverage.

**Comment by guardrex** [comment]
BTW ... It's also covered in the *Fundamentals* > *Overview* article in this section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-9.0#static-and-interactive-rendering-concepts

**Comment by Tandry** [comment]
Luke,

The point is that there are no references to those articles from where the
code is.  The code, as copyable from the documentation, does not work -
that's a fact.

People like me, new to Blazor, are accessing these pages and copying code.
The user experience - which is the only thing that matters here - is that
Microsoft is supplying unworking code.  That's enough to sway people not to
pursue working with Blazor right there, and I doubt that's what you want.

Other organizations supply working code.

Relying on tribal knowledge or saying "well, you should be using the
documentation this other way" isn't acceptable.  Users (such as myself) use
documentation the way we use documentation and the product MUST change to
suit the usage pattern of the customer.

Given the existence of hyperlinks, there's absolutely no reason not to
place something in the documentation to the effect of, "The working of this
code sample is affected by the current @rendermode, which may be set
elsewhere in the code.  Documentation on @rendermode can be reviewed at
<http...."

I highly recommend changing the current policy to assist customers in
consuming these documents.  Most won't take the time to open a ticket and
respond, they'll just badmouth on social media.  I'm hoping my words will
have a positive effect and help other folks who may, such as in my case,
want to stick with C# instead of learning JavaScript, do so with Blazor.
Unfortunately, right now, my experience isn't positive at all.

Thanks for your time,

Steve

**Comment by guardrex** [comment]
I had a remark at the top of every page stating exactly that (close to what the "important" note states in the section that I cross-linked) when 8.0 released and for a time thereafter. @danroth27, Principal Product Manager for .NET, asked me to remove them. He's "*the boss*" 😄, and it's up to him if such remarks would be replaced.

**Comment by Tandry** [comment]
Luke,
Well, in my opinion, that's an extremely bad policy.  I cannot fathom a
justification for such a removal when someone had sufficient forethought to
place the links there.
To my thinking, each page must be self-contained, either by embedded (on
page) information, or links to external stuff needed to make things work.
Anything less is simply frustrating, especially since VS won't catch the
problem.
Please feel free to forward my conversation to Dan.  I'd be delighted to
take up the issue with him.  This policy is working very hard to get people
NOT to adopt Blazor (or MAUI).  I've had this same type of issue with
MAUI's docs as well.  An extra line or two in a document vs having someone
spend 90 minutes trying to hunt down the actual answer....not much of a
contest there in terms of user experience.
Thanks for your reply.
Steve

**Comment by guardrex** [comment]
I tagged him with his GitHub handle in my last comment, so it's already forwarded to him.

This is the issue that he opened, which I believe contains his justification ...

https://github.com/dotnet/AspNetCore.Docs/issues/31940

**Comment by guardrex** [comment]
... and I should mention that he remarked about the "front matter" in the one article that he was commenting on, but that content was actually via an INCLUDE that I added to many/most of the articles. If you look at the referenced PR, you'll see where I pulled that INCLUDE from the doc set after that discussion.
