### ISSUE TITLE
Are these example codes missing "@rendermode InteractiveServer"?

### ISSUE THREAD

**Issue by geniuszxy** [dotnet/AspNetCore.Docs#34249]
### Description

I'm new to blazor. Today I tried the examples on this page, but they didn't work. I searched on internet and found a solution by adding "@rendermode InteractiveServer". I'm not sure if this step is necessary or if these examples are outdated. The same issue also appears on this page: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/location-of-javascript Please take a look.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/call-javascript-from-dotnet.md

### Document ID

9e197a8b-2616-8363-0a15-38cac802e82e

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+9e197a8b-2616-8363-0a15-38cac802e82e)

**Comment by guardrex** [comment]
Hello @geniuszxy ... Developers have written in on this few times ([recent example](https://github.com/dotnet/AspNetCore.Docs/issues/34248)). It's covered here for the whole doc set ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/?view=aspnetcore-9.0#static-and-interactive-rendering-concepts

When .NET 8 released last year, I placed remarks at the top of every article, but I was asked by management to remove them ([issue](https://github.com/dotnet/AspNetCore.Docs/issues/31940), [pr](https://github.com/dotnet/AspNetCore.Docs/pull/31944)). I was going to remove them anyway at some point, even if they had been allowed to stay.

I'll talk to management again next week about this situation to see if permanent remarks should be added back to the articles. Thanks for commenting on it.
