### ISSUE TITLE
Link to Source Code

### ISSUE THREAD

**Issue by lockhartsoftware** [dotnet/AspNetCore.Docs#34253]
### Description

At the bottom of the article:

Enable QR code generation for TOTP authenticator apps in an ASP.NET Core Blazor Web App
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/qrcodes-for-authenticator-apps?view=aspnetcore-9.0

It states:

"Collaborate with us on GitHub: The source for this content can be found on GitHub"

Can you please provide me with the link in GitHub for the source code for this article please.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/qrcodes-for-authenticator-apps?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md

### Document ID

8c46bfee-4145-afc7-e44c-d700c7652b85

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+8c46bfee-4145-afc7-e44c-d700c7652b85)

**Comment by guardrex** [comment]
It's there by virtue of your opening this issue ...

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/qrcodes-for-authenticator-apps.md

Note that there are several changes about to be made to this article on https://github.com/dotnet/AspNetCore.Docs/pull/34189. I hope to have that merged by the end of next week, but it's dependent on review from one or more members of the product unit. We're in the holiday season now, so reviews are kind'a hard to get these days 😆.

I'll close this as answered, but you can respond if you need to.

**Comment by lockhartsoftware** [comment]
Thank you

**Comment by guardrex** [comment]
Sure thing. For any given article, you can use the pencil icon to edit the article, and that will also show you the link to where it resides ...

![Image](https://github.com/user-attachments/assets/32c1b254-11ab-4cc7-94d8-8b2ad12d64c7)

👇 

![Image](https://github.com/user-attachments/assets/33d37f59-047a-437b-926a-35271246e627)
