### ISSUE TITLE
Check on replacement for the Podcasts app

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#34272]
### Description

@BethMassi ... Hope you had a great 🦃 break!

The Podcasts sample app went away ... https://github.com/microsoft/dotnet-podcasts.

I commented it out in the Blazor Hybrid class libraries article went it went stale. This is what we used to have in a dedicated section on it ...

```markdown
## Sample app

For an example of the scenarios described in this article, see the .NET Podcasts sample app:

* [GitHub repository (`microsoft/dotnet-podcasts`)](https://github.com/microsoft/dotnet-podcasts)
* [Running sample app (Azure Container Apps Service)](https://dotnetpodcasts.azurewebsites.net/)

The .NET Podcasts app showcases the following technologies:

* [.NET](https://dotnet.microsoft.com/download/dotnet)
* [ASP.NET Core](https://dotnet.microsoft.com/apps/aspnet)
* [Blazor](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)
* [.NET MAUI](https://dotnet.microsoft.com/apps/maui)
* [Azure Container Apps](https://azure.microsoft.com/services/container-apps/)
* [Orleans](/dotnet/orleans/overview)
```

It was also mentioned in the *Reuse Razor components* aritcle. Here's what that used to have ...

```markdown
## Additional resources

* .NET MAUI Blazor podcast sample app
  * [Source code (`microsoft/dotnet-podcasts` GitHub repository)](https://github.com/microsoft/dotnet-podcasts)
  * [Live app](https://dotnetpodcasts.azurewebsites.net/)
```

Is there a replacement example of a class libraries demo app that you'd like me to put there, or do you want me to just kill that commented-out section off permanently?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/class-libraries?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/hybrid/class-libraries.md

### Document ID

ec81036a-98aa-ec0e-b7ac-1fb441a370b8

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+ec81036a-98aa-ec0e-b7ac-1fb441a370b8)

**Comment by BethMassi** [comment]
eShop is the latest "mega" sample for .NET that includes a hybrid app: https://github.com/dotnet/eShop/tree/main/src/HybridApp

**Comment by guardrex** [comment]
Great ... thx ... I'll get that in there.
