### ISSUE TITLE
HttpContext is valid in Interactive Server Rendering Blazor page

### ISSUE THREAD

**Issue by huazhb** [dotnet/AspNetCore.Docs#34301]
### Description

On the website, it says "[IHttpContextAccessor](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor) must be avoided with interactive rendering because there isn't a valid HttpContext available." which seems not true. I use the IHttpContextAccessor on the Blazor page using Interactive Server rendering and I can access the HttpContext from IHttpContextAccessor without any issue. When switch to Interactive Client it will be null. (Of course it is since it is running on client side). So, I don't know where this statement coming from, or it will be invalid under some circumstances? Can anyone double check if this statement is valid for all Interactive rendering mode or it is only valid for the Interactive client mode?

 

Thank you

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-8.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md

### Document ID

79cb05f8-9ac0-26a8-8434-15de071160c3

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+79cb05f8-9ac0-26a8-8434-15de071160c3)

**Comment by guardrex** [comment]
Hello @huazhb ... Yes, this is a point of confusion. This section is placed here via an [INCLUDE file](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/includes/httpcontext.md) that also appears in the SignalR article and in the Threat Mitigation article. The section's guidance is the latest that I received from the product unit on the subject. Let's double-check this now and clear this up.

@MackinnonBuck ... This is one of the questions on my list of items to address, so we may as well tackle it now. 

Here's the section (via the INCLUDE) ...

> \<xref:Microsoft.AspNetCore.Http.IHttpContextAccessor> must be avoided with interactive rendering because there isn't a valid \`HttpContext\` available.
>
> \<xref:Microsoft.AspNetCore.Http.IHttpContextAccessor> can be used for components that are statically rendered on the server. \*\*However, we recommend avoiding it if possible.\*\*
>
> \<xref:Microsoft.AspNetCore.Http.HttpContext> can be used as a [cascading parameter](xref:Microsoft.AspNetCore.Components.CascadingParameterAttribute) only in \*statically-rendered root components\* for general tasks, such as inspecting and modifying headers or other properties in the \`App\` component (\`Components/App.razor\`). The value is always \`null\` for interactive rendering.
>
> ```csharp
> [CascadingParameter]
> public HttpContext? HttpContext { get; set; }
> ```
>
> For scenarios where the \<xref:Microsoft.AspNetCore.Http.HttpContext> is required in interactive components, we recommend flowing the data via persistent component state from the server. For more information, see \<xref:blazor/security/additional-scenarios#pass-tokens-to-a-server-side-blazor-app>.

Cross-reference (LIVE section example): https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-8.0#ihttpcontextaccessorhttpcontext-in-razor-components-blazor

That came about from my chat with either (or both) you and Javier.

There's a [related issue on the samples repo](https://github.com/dotnet/blazor-samples/issues/258) about this that boils down to code in the BWA+OIDC sample app ...

https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/ServerWeatherForecaster.cs

... where the `ServerWeatherForecaster` is using `IHttpContextAccessor` to check for an `HttpContext`. Can you go through the rendering process step-by-step and explain if that code is running interactively or not ... and if it is running interactively (e.g., after prerendering on the server) then how it isn't in conflict with the general guidance on use of `IHttpContextAccessor`, both the 'don't do it' part and the 'it's always null for interactive rendering' part?

**Comment by guardrex** [comment]
From Mackinnon offline ...

> The IHttpContextAccessor question is something I'm not sure about either. The app gets rendered using the InteractiveAuto render mode, and it seems like things would break if that resolved to using server interactivity. I think Stephen would be the one to ask about that.

Ping to @halter73 to take a look at this issue and recommend updates for the section on `IHttpContextAccessor`/`HttpContext`. It looks like we're missing caveats ...

* For `IHttpContextAccessor`, we state that it's ok to use it "for components that are statically rendered on the server."
* For `HttpContext`, we state that it "can be used as a cascading parameter only in *statically-rendered root components* for general tasks, such as inspecting and modifying headers or other properties in the `App` component."

Should these remarks include a caveat for client request processing by the server project, including server-side services used by that processing?

**Comment by halter73** [comment]
We advise against using `IHttpContextAccessor` in general mostly because managing the flow of the execution context can be tricky and isn't something you otherwise really have to pay attention to. That's why using something like `[CascadingParameter]` or `Hub.Context.GetHttpContext()` is preferrable.

That said, as fair as I know, using `IHttpContextAccessor` in the context of a SignalR hub invocation should mostly work. And this includes Blazor events handled by interactive server rendering. In cases where the server-sent events transport is used you'd probably get the `HttpContext` from the send POST request rather than the text/event-stream request you'd get from calling `GetHttpContext()` directly inside the SignalR hub, but for many purposes that's probably fine. For long polling things get a bit weirder, but that's not supported by Blazor.

However, I do recall @javiercn mentioning that using `IHttpContextAccessor` in a Blazor app is insecure. Javier, do you remember this? I don't think I really understood the issue at the time, but maybe if you could explain exactly what makes it insecure, we could add it to the documentation. Sorry, if I'm misremembering anything.

@BrennanConroy @dotnet/aspnet-blazor-eng In case anyone wants to disagree with or add to my assessment.

**Comment by BrennanConroy** [comment]
> For long polling things get a bit weirder, but that's not supported by Blazor.

I don't think that's true unless things changed recently.

> In cases where the server-sent events transport is used you'd probably get the HttpContext from the send POST request

I believe the context is still from the long running initial request. Although, SSE is not supported by Blazor as it uses a binary message protocol which SSE doesn't support.

Blazor has things like pre-rendering and `InitalizeAsync` being called twice (maybe that's pre-rendering?), I don't know if those work with `IHttpContextAccessor`.

**Comment by guardrex** [comment]
Steve remarked offline ...

> The truth is you can sometimes use `IHttpContextAccessor` but there are caveats and risks, which is why we’ve found it safer just to tell people not to use it. If our existing guidance is inadequate that may require more thought. Javier would be a great person to give more detailed guidance.

@javiercn, if you're still happy with what we're telling devs ...

* [LIVE article section](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-8.0#ihttpcontextaccessorhttpcontext-in-razor-components-blazor)
* [INCLUDE file source for the section](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/security/includes/httpcontext.md)

... then I think we just need to say why we're going against the advice in the article for the BWA+OIDC sample app ...

https://github.com/dotnet/blazor-samples/blob/main/8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/ServerWeatherForecaster.cs

If people send a few doc issues after that, then I'll point them to this issue discussion. If I see devs regularly opening doc issues on this, then I propose to add a link to the section (and the BWA+OIDC article) along the lines of ...

```
For more information, see [HttpContext is valid in Interactive Server Rendering Blazor page 
(`dotnet/AspNetCore.Docs` #34301)](https://github.com/dotnet/AspNetCore.Docs/issues/34301).
```

**Comment by guardrex** [comment]
I'll make a couple of changes to the first line of the INCLUDE file.

The current line is ...

> `IHttpContextAccessor` must be avoided with interactive rendering because there isn't a valid `HttpContext` available.

I'll change that to read ...

> `IHttpContextAccessor` generally should be avoided with interactive rendering because a valid `HttpContext` isn't always available. 

To suggest a better sentence, let me know here or on the PR that I'm about to open. I'll let it sit and merge it EOD (Thursday evening) to give everyone time to respond.

In the BWA+OIDC article, I'll mention in passing for the server-based weather forecaster ...

> In the `ServerWeatherForecaster` class, `IHttpContextAccessor` is checked to determine if a valid `HttpContext` is available. `HttpContext` is only used by the `GetWeatherForecastAsync` method if it's available. For more information, see {CROSS-LINK TO ONE OF THE INCLUDE SECTIONS}.

I've had perhaps three doc issues come in on this subject. If more doc issues are opened, I think at least a cross-link to this issue is warranted, perhaps directly to @halter73's comment ☝. Let's see how things go in 2025.

**Comment by huazhb** [comment]
Hi, @guardrex, thank you for all the efforts to clarifying the HttpContext issue. Still I don't see exactly why the IHttpContextAccessor is not secure in Blazor interactive rendering especially on server side rendering even though I can access it from my own testing.  Hope @javiercn can make it more clear in the next year.

**Comment by nicholasyin** [comment]
By debugging, I can see that, in SSR, the same code gets to run twice. In the first time HttpContext has value while in the second time it's null.

**Comment by Mike-E-angelo** [comment]
> Hope @javiercn can make it more clear in the next year.

As this seems like this is a security concern (and generally the reason I have stayed away from `IHttpContextAccessor`) this seems like it should be a priority to address with certainty, correct?  From what I can tell this has not been addressed.  Should a new issue be made to ensure this rather important detail is verified and discussed with clarity?

Thank you for any further assistance you can provide around this rather complex and involved issue. 🙏

**Comment by JoeTomkinson** [comment]
To pile in, I've yet to see a circumstance where using `IHttpContextAccessor `has failed to provide the context. 

However, I would like to understand the potential security issues associated with this, as that seems like an important distinction to make in the documentation, if accurate.

I agree with @nicholasyin that, typically, when using `InteractiveServer `mode on a page (such as the Accounts/Manage pages), the typical lifecycle methods tend to run twice: once when `HttpContent `(when provided as a cascading parameter) is populated, and once when it is null. This often results in elements that require it to render correctly, then suddenly disappear (for example, if there's an @if statement to display specific content depending on the user, which is retrieved from the Context).

**Comment by Mike-E-angelo** [comment]
Yes, it is important to understand the security implications.  At one point, I remember reading something that implied that due to the backing logical async store, a user's identity can be inadvertently flowed over into another context, and as a result, would switch the context of the current user for the request.  It would be valuable to know this has been mitigated (or not).
