### ISSUE TITLE
Xamarin - update references - AspNetCore.Docs - Blazor docs only

### ISSUE THREAD

**Issue by wadepickett** [dotnet/AspNetCore.Docs#34325]
Xamarin should no longer be referred to and we should refer to or direct to Maui instead:
https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui?view=net-maui-9.0

In the AspNetCore.Docs repo, for Blazor content only

- Remove all references to "Xamarin" or update to ".NET Multi-platform App UI (.NET MAUI)" for first reference and ".NET MAUI" for following references in the same doc.
- If a topic centers on .NET MAUI and requires a complete rewrite rather than just an updated link or reference update, and/or requires a code sample update, AND we decide not to retire or archive it as the solution, then identify it here and create a new tracking issue for that work.

Currently there are around 14 files referencing "Xamarin", in this repo, a few of those are for Blazor docs and the rest for non-Blazor docs.  

See also #34324 for non-blazor effort.

**Comment by wadepickett** [comment]
@guardrex,  I figured you would want to handle the few Blazor docs that still reference Xamarin for this update effort, so I created this separate Blazor related issue.  If you don't want to handle it, feel free to assign it to me.

**Comment by guardrex** [comment]
Thx @wadepickett ... I'll take care of it very soon, probably tomorrow morning.

**Comment by wadepickett** [comment]
Great!  I don't think this has to be done right away.  January sprint for example would be fine.
