### ISSUE TITLE
POST endpint that creates a resource and returns it in the body - for `CreatedAtAction` action name should contain GET action not POST Action

### ISSUE THREAD

**Issue by flamaniac** [dotnet/AspNetCore.Docs#34361]
### Description

In the examples here:
https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-9.0#asynchronous-action-1

the first parameter of CreatedAtAction points to the same method (POST) but in description, it states that the location header will be pointing to the get method.

It is confusing. 
Shouldn't this be GET like here: https://stackoverflow.com/a/64315534

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/web-api/action-return-types.md

### Document ID

b51bc104-a6e2-b21f-8362-45cee22e8c22

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+b51bc104-a6e2-b21f-8362-45cee22e8c22)

**Comment by tdykstra** [comment]
Where do you see something that indicates

> the first parameter of CreatedAtAction points to the same method (POST)

**Comment by flamaniac** [comment]
In the example under the link in descriprion .

`return CreatedAtAction(nameof(CreateAsync_ActionResultOfT), new { id = product.Id }, product);`

Should be "nameof(GetProductAsync)"

**Comment by tdykstra** [comment]
You are correct, thanks for reporting this. I'm fixing it in https://github.com/dotnet/AspNetCore.Docs/pull/34390 and https://github.com/dotnet/AspNetCore.Docs.Samples/pull/268
