### ISSUE TITLE
Why recommend Blazor by default?

### ISSUE THREAD

**Issue by developpeur-pro** [dotnet/AspNetCore.Docs#34376]
### Description

> For new project development, we recommend ASP.NET Core Blazor.

This sentence without any further explanation raises questions. Are we to understand that Microsoft will no longer develop Razor Pages and MVC?

Currently, Blazor Server does not cover all use cases for classic ASP.Net Core applications (MPA) with server-side rendering. Classic MPA apps with HTMX or Hydro remain the simplest and most economical option for creating applications with good interactivity and low consumption of server-side resources. Blazor Server's dynamic rendering consumes many more resources due to web socket connections, and the possibilities offered by static rendering remain very limited and poorly documented. This is why it seems very premature to me to recommend using Blazor for any new web application.

Please clarify this point or delete this sentence.

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/tutorials/choose-web-ui?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/tutorials/choose-web-ui.md

### Document ID

68d5aab0-63ce-de7a-0c56-341c2eef623d

### Article author

@wadepickett

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+68d5aab0-63ce-de7a-0c56-341c2eef623d)

**Comment by guardrex** [comment]
Hello @developpeur-pro ... This is only a recommendation, and we won't be pulling the remark or adding additional content to it at this time. Microsoft isn't abandoning RP/MVC; and if Blazor doesn't meet your needs, then please continue with RP/MVC.
