### ISSUE TITLE
Options pattern class naming convention

### ISSUE THREAD

**Issue by backlash1897** [dotnet/AspNetCore.Docs#34384]
### Description

Hello documentation team, 

Is it best practice to name the class with the "Options" suffix?

e.g. PositionOptions, NameTitleOptions

In another example in the article the "Settings" suffix is used:

[TopItemSettings](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-9.0&preserve-view=true#named-options-support-using-iconfigurenamedoptions)

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-9.0&preserve-view=true

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/configuration/options.md

### Document ID

dc7e3449-650b-d117-5eac-69e5ccb250cb

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+dc7e3449-650b-d117-5eac-69e5ccb250cb)

**Comment by tdykstra** [comment]
It's outside the scope of this documentation to recommend a naming practice.   "Options" makes sense, but so does "Settings." What to name these classes is a decision best left up to each developer team.
