### ISSUE TITLE
No example usage for setting blazor-environment header in a standalone Blazor wasm app not using IIS

### ISSUE THREAD

**Issue by nicholasyin** [dotnet/AspNetCore.Docs#34392]
### Description

The documentation only gives example of configuring IIS via web.config file. What if I'm developing under Linux/MacOS and can only use dotnet CLI/VSCode to launch and debug?

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/environments?view=aspnetcore-9.0#set-the-client-side-environment-via-blazor-startup-configuration

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/fundamentals/environments.md

### Document ID

8a5b47e7-b29c-b049-30e8-5b405a5086b6

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+8a5b47e7-b29c-b049-30e8-5b405a5086b6)

**Comment by guardrex** [comment]
Hello @nicholasyin ... Try using the `launchSettings.json` file in the `Properties` folder. Set it via the environment variable. For example in the `https` profile when running with HTTPS:

```json
"environmentVariables": {
  "ASPNETCORE_ENVIRONMENT": "Staging"
}
```

Leave this issue open. I think this became a feature for standalone WASM apps at some point over the years and never made its way into the article. If it was always a feature, I was never told it was the case. I was only instructed that use of the header or startup config (`Blazor.start`) approaches were valid. Otherwise for sure, I'd have placed this technique into the article.

I'll ask a product unit engineer to confirm this offline and see if we can figure out when it became a feature (for versioning) or why it never made it into the article. I'll use this issue to work on it.

**Comment by guardrex** [comment]
I think this line ...

> For a standalone Blazor WebAssembly app running locally, the development server adds the `blazor-environment` header.

... is what will need an update. What's happening ... I think 🤔 ... is that the development server (basically Kestrel via Blazor startup) is reading the environment variable from launch settings and setting the header. This is only when running the app locally. For hosting scenarios, I think you must set the header on your own using the server (if you're trying to use something different than the published default of `Production` for the environment).

I'll talk to Steve offline about this tomorrow and come back with the answer, then I'll see about updating this aspect of the article.

**Comment by nicholasyin** [comment]
> Hello [@nicholasyin](https://github.com/nicholasyin) ... Try using the `launchSettings.json` file in the `Properties` folder. Set it via the environment variable. For example in the `https` profile when running with HTTPS:
> 
> "environmentVariables": {
>   "ASPNETCORE_ENVIRONMENT": "Staging"
> }
> If you're running with the `http` profile for HTTP (insecure), then set it in that section of the file.
> 
> Leave this issue open.

What if I want to set for testing/production environment? Can I also set in `launchSettings.json` and it will be read during startup?

**Comment by guardrex** [comment]
Yes, but keep in mind that this approach that we're discussing with the `launchSettings.json` file is for the ***development server running locally***. It won't work when publishing the app to a file server host somewhere in a production deployment.

For a published app, the only two current ways to set the environment are via `Blazor.start` (`environment` key) and the `blazor-environment` response header set on the `blazor.boot.json` file.

The issue that I cross-linked on the [PR](https://github.com/dotnet/AspNetCore.Docs/pull/34394) is where the team is looking at improving the features ...

https://github.com/dotnet/aspnetcore/issues/59456

They have that scheduled for consideration for .NET 10 (November, 2025) ... but only for consideration ... they might cut it and push it back to .NET 11 (November, 2026). That happens quite a bit with features under consideration.
