### ISSUE TITLE
Add coverage for BlazorWebAssemblyLoadGlobalizationDataForCultures

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#34393]
### Description

Discovered that we didn't document this MS Build property.

```xml
<BlazorWebAssemblyLoadGlobalizationDataForCultures>en-US;nb-NO</BlazorWebAssemblyLoadGlobalizationDataForCultures>
```

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/globalization-localization.md

### Document ID

d6f07538-228e-9f96-680f-6c324caf11d6

### Article author

@guardrex

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+d6f07538-228e-9f96-680f-6c324caf11d6)

**Comment by guardrex** [comment]
@ilonatommy ... I saw something in passing that I hadn't come across before ...

```xml
<BlazorWebAssemblyLoadGlobalizationDataForCultures>...</BlazorWebAssemblyLoadGlobalizationDataForCultures>
```

It was shown in passing in a product unit issue ...

https://github.com/dotnet/aspnetcore/issues/59466#issuecomment-2540954342

I went looking for that MS Build property to provide documentation on it, but I can't find it. It doesn't come up in a general web search or in a search of the `dotnet/runtime` repo ...

* https://www.google.com/search?client=firefox-b-1-d&q=%22BlazorWebAssemblyLoadGlobalizationDataForCultures%22
* https://github.com/search?q=repo%3Adotnet%2Fruntime+BlazorWebAssemblyLoadGlobalizationDataForCultures&type=code

*I think the dev made that up!* 😆 It's *NOT* a thing, right?

**Comment by ilonatommy** [comment]
We don't have `BlazorWebAssemblyLoadGlobalizationDataForCultures` property in the runtime, it has to be project-specific.
