### ISSUE TITLE
Link to ASP.NET Core authentication-handler broken on OIDC Web authentication page

### ISSUE THREAD

**Issue by apicht** [dotnet/AspNetCore.Docs#34395]
### Description

The link in this sentence is not rendering: 

https://github.com/dotnet/AspNetCore.Docs/blob/b1e1428d5899fda009f65e2c4e41dac6a60df7b6/aspnetcore/security/authentication/configure-oidc-web-authentication.md?plain=1#L55

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/configure-oidc-web-authentication?view=aspnetcore-9.0

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/security/authentication/configure-oidc-web-authentication.md

### Document ID

5d97b8bb-6505-9268-efbc-33fc2c02f4d8

### Article author

@damienbod

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+5d97b8bb-6505-9268-efbc-33fc2c02f4d8)

**Comment by guardrex** [comment]
Thanks for the report @@apicht 

@damienbod ... I'll fix this on my open PR tomorrow morning.

**Comment by guardrex** [comment]
All good! It's on the PR, and I think that PR will merge tomorrow.

Thanks again for the report, @apicht.
