### ISSUE TITLE
Add warning that VS and Docker don't hit Stop events

### ISSUE THREAD

**Issue by JohnGoldsmith** [dotnet/AspNetCore.Docs#34407]
### Description

Hi, I don't think I've missed it in this article, but I've found that when trying to debug BackgroundService stop events in Visual Studio and Docker Desktop, the process is terminated and code in these events is never hit.

It would be helpful to highlight this somewhere in the article, unless you feel that it's too specific to a particular IDE / Setup?

You can see an issue that I raised about this in the DockerTools issues repo here:

https://github.com/microsoft/DockerTools/issues/451

I don't think it's necessary to add the workaround, but just highlighting the behaviour would save people a lot of time.  Or at least me anyway :)

Best regards, John

### Page URL

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-9.0&tabs=visual-studio

### Content source URL

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/host/hosted-services.md

### Document ID

b2dece1f-15b8-03af-6d52-7cc070432b4b

### Article author

@tdykstra

[Related Issues](https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+b2dece1f-15b8-03af-6d52-7cc070432b4b)

**Comment by tdykstra** [comment]
>it's too specific to a particular IDE / Setup

Yes, but you could create a question and answer on StackOverflow.

**Comment by JohnGoldsmith** [comment]
> ... create a question and answer on StackOverflow.

That's fine.  Will do.

**Comment by JohnGoldsmith** [comment]
Just for the record, added here: https://stackoverflow.com/questions/79320703/cannot-hit-breakpoints-in-graceful-shutdown-stop-events-in-net

**Comment by tdykstra** [comment]
Thanks!
