### ISSUE TITLE
Can we get a life cycle poster, like for Asp.NET web api 2 or asp.net mvc?

### ISSUE THREAD

**Issue by vhe1** [dotnet/AspNetCore.Docs#3524]
For the pre-core asp.net you offered two beautiful posters, showing the life cycle of a message in

- asp.net mvc 5: https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/lifecycle-of-an-aspnet-mvc-5-application with this link [Download PDF document](https://opdhsblobprod01.blob.core.windows.net/contents/2c5850f658eb4c6992d3a09891c2eaa9/d0ed2e012c44fea6a368d4591ea14088?sv=2015-04-05&sr=b&sig=pkKMb6FViNu3W7V2DflQytBtJFI%2B1Fkcy9QEo6tFnLg%3D&st=2018-12-05T22%3A01%3A28Z&se=2018-12-06T22%3A11%3A28Z&sp=r)
- asp.net web api 2: https://www.asp.net/media/4071077/aspnet-web-api-poster.pdf

I'm sure that these adore many office walls. Can we have one or more similar posters for asp.net core? It makes things much easier to understand.

**Comment by Rick-Anderson** [comment]
@danroth27  if you can get someone to do a mock-up I'll get the art department to produce them. CC @tdykstra  @scottaddie

**Comment by Rick-Anderson** [comment]
Cut due to priorities.

**Comment by srumyantsev** [comment]
Looks like this issue was closed. Why it wasn't moved to next release?
Is it possible to reopen it and create this poster?

**Comment by Rick-Anderson** [comment]
@danroth27 	assigning this to the PU. I you can come up with the diagram, I'll have the art team create the PDF.

**Comment by CrossBound** [comment]
I would also love to see the poster for this as well... That poster is very helpful in determining which extensibility points need to be utilized to achieve a particular objective.

**Comment by denis-peshkov** [comment]
very needed in this doc

**Comment by Legends** [comment]
Upvoted! Would be nice to have it. Thanks.

**Comment by Expecho** [comment]
Too bad I ended up here searching for this. At least I know it is coming ;-)

**Comment by admalledd** [comment]
For what it is worth, [the Filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters) documentation has not the same but similar information for those wanting to hook into the request lifecycle.

**Comment by mkArtakMSFT** [comment]
Here is the link in case people want to find it: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1#middleware-order
