### ISSUE TITLE
Fix Add IdentityUser POCO Navigation Properties sample

### ISSUE THREAD

**Issue by blowdart** [dotnet/AspNetCore.Docs#5028]
_From @postb99 on December 17, 2017 21:49_

 Please fix the "Add IdentityUser POCO Navigation Properties" example code on [this page](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#add-identityuser-poco-navigation-properties) register entities: in my case I have derivated types for IdentityUser, IdentityRole, IdentityUserRole, IdentityUserToken, IdentityUserLogin (they have int primary/foreign  key), with "long" naming of navigation properties (User has a navigation property named "UserRoles" instead of "Roles"...)

Then my user has UserRoles, UserTokens, UserLogins navigation properties, my Role has UserRoles navigation property.

I end up with correct initial migration with these mapping declarations: in addition to the example code, I declare the one to many relationship from Role to UserRole, so that "RoleId1" column isn't created.

```
modelBuilder_.Entity<User>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.RoleId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<Role>().HasMany(e => e.UserRoles).WithOne().HasForeignKey(e => e.RoleId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserLogins).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
modelBuilder_.Entity<User>().HasMany(e => e.UserTokens).WithOne().HasForeignKey(e => e.UserId).IsRequired().OnDelete(DeleteBehavior.Cascade);
```

_Copied from original issue: aspnet/Identity#1533_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-6.0#add-identityuser-poco-navigation-properties)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by postb99** [comment]
After afterthought, the correct indication would be that the entity mapping should be explicitly redefined for every entity that references the "TKey" column, either as a PK or as a FK. It wasn't obvious for me at first sight, being a learner. Thanks.

**Comment by Rick-Anderson** [comment]
@postb99  any chance you could help out with the PR?

**Comment by postb99** [comment]
Yes, you're right,I can handle it.

**Comment by scottaddie** [comment]
@ajcvickers I'm looking for some guidance on how to update the code snippet in question.

**Comment by ajcvickers** [comment]
@scottaddie It's on my list to get to this. Is it critical this is done now?

**Comment by scottaddie** [comment]
@ajcvickers We do consider this critical. This is a high-traffic document, and several customers have commented on this particular code snippet.

**Comment by Rick-Anderson** [comment]
@ajcvickers I think in the next week would be OK.

**Comment by ajcvickers** [comment]
@Rick-Anderson @scottaddie That's going to require some significant re-shuffling of priorities, since I need to spend significant time getting up to speed learning this area before I will be able to make any meaningful comments. Even if I start now, I don't know I will have anything concrete by next week.

**Comment by Rick-Anderson** [comment]
I think we can wait a month - will that work?

**Comment by Rick-Anderson** [comment]
@HaoK  would you be able to consult? @blowdart  who else could help?

**Comment by ajcvickers** [comment]
@Rick-Anderson A month makes it easier.

**Comment by HaoK** [comment]
For navigation properties, i'm basically a more inefficient route to @ajcvickers :)

**Comment by scottaddie** [comment]
@ajcvickers Revisiting this issue, as customers continue to ask about it. Any updates to provide?

**Comment by Rick-Anderson** [comment]
@ajcvickers  would you be able to schedule this sometime in the next 8 weeks? The topic has 15K PVM from very important customers.

**Comment by ajcvickers** [comment]
@Rick-Anderson Closing down 2.1 is currently the priority, so it depends how that goes. Identity/docs issues are currently next on my list, although VS/NuGet issues could end up bumping this.

**Comment by Rick-Anderson** [comment]
@ajcvickers  scheduling for end of Q3

**Comment by ajcvickers** [comment]
@Rick-Anderson My intention was that you could update this taking the bits you want from the most comprehensive document that I created. Do you want me to do that part also?

**Comment by Rick-Anderson** [comment]
@scottaddie can you do this? Ping @ajcvickers if you run into problems.

**Comment by Rick-Anderson** [comment]
@danroth27 	please review/set priority.

**Comment by Rick-Anderson** [comment]
No hits on [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-6.0#add-identityuser-poco-navigation-properties) in 3 years as it migration to 2.0  so closing.
