### ISSUE TITLE
Add more Docker + ASP.NET Core samples

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/AspNetCore.Docs#5450]
We frequently get asked to build features into our Docker images that are already possible and easy to do without needing changes to the base images.

Instead, we would like to address this by adding more samples and docs for these commonly asked features/questions.

 - How to use multi-stage builds
 - Using NodeJS 9
 - Add NodeJS so JavascriptServices works at runtime
 - Using powershell in Linux images or NanoServer 1709
 - Running tests in docker 
 - Writing a Dockerfile to building a solution or multiple .csproj files
 - Debugging remotely into a docker container (vsdbg)

cc @glennc 

`[Edit - append by @rick-anderson]`
Create basic windows/MacOs dev/productions samples using HTTPS from https://github.com/dotnet/dotnet-docker/tree/master/samples

**Comment by glennc** [comment]
What I am thinking here is something akin to a Docker recipes page. Including examples for each of the ones you listed as well as how to do libgdiplus in Docker.

I think we could link to this from the top of our scaffold-ed Dockerfiles.

//cc @richlander

**Comment by Rick-Anderson** [comment]
//cc @spboyer

**Comment by MichaelSimons** [comment]
Here is an additional request for doc on ASP.NET Core SPA templates - https://github.com/dotnet/dotnet-docker/issues/393

**Comment by johnknoop** [comment]
One use case that I don't even know if it's supported, and at least not documented, is to be able to just recompile the application without needing to rebuild and restart the container. Right now I have to do CTRL+F5 for the entire docker-compose, even if I've just made changes to one of the projects, which results in a very slow feedback cycle. It would be nice to get the same live update experience for compiled code, as I do for static files. Perhaps using dotnet watch, or, failing that, using some post-build script that updates the running container with new binaries or something like that.

**Comment by dapalmi** [comment]
I just opened the new Visual Studio 15.7, created a new ASP.NET Core 2.1 project with the Angular template, added Docker Support started the application and ... got an exception 👎 
This all is now a release candidate!!!
Honestly, I would get into trouble making software like that

**Comment by Rick-Anderson** [comment]
@dapalmi  This repro is for document issues. Did you want to open an issue with the product?  If so, see the ASP.NET [How to contribute](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md)

It's helpful to add the steps to reproduce the problem, what happened, and what was expected.

**Comment by dapalmi** [comment]
Ok. Sorry. I thought this is the continuation of this [issue](https://github.com/aspnet/aspnet-docker/issues/347)

**Comment by Rick-Anderson** [comment]
@dapalmi  no problem. Does the workaround solve your issue?

**Comment by dapalmi** [comment]
@Rick-Anderson The workaround works. Thanks. It just doesn't fit into the otherwise very nicely flowing ASP NET Core workflows. In Visual Studio Angular Templates are offered and you can add Docker support, so me as a normal user would expect this to work without having to google a workaround first

**Comment by Rick-Anderson** [comment]
@dapalmi  agreed.  
@scottaddie  can you work with the PU to get a fwlink on the wizard to warn folks. The fwlink could point an H2 in our Angular doc, which in turn could point to that issue.

**Comment by dalibor983** [comment]
@natemcmaster [This](https://github.com/aspnet/aspnet-docker/issues/347#issuecomment-354316642) is good way to install nodejs in linux based docker image. But there is one issue with docker integration with visual studio because visual studio mount local source in docker container but all native nodejs components (like node sass) are built for windows not for linux :disappointed:

**Comment by Rick-Anderson** [comment]
@natemcmaster 	@glennc 	do you have any samples/content we can start with?

**Comment by Rick-Anderson** [comment]
@natemcmaster @glennc do you have any samples/content we can start with?

**Comment by glennc** [comment]
This might be solved by the work that @richlander has been doing.

**Comment by spboyer** [comment]
See https://github.com/dotnet/dotnet-docker 
There are well-documented samples in [/samples/aspnetapp](https://github.com/dotnet/dotnet-docker/tree/master/samples) with README for many scenarios.

**Comment by SirwanAfifi** [comment]
I have the same issue: https://github.com/Microsoft/aspnet-docker/issues/164
