### ISSUE TITLE
Sample Update Tracking Issue - complete list

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#5495]
**Last Updated**: 4/18/21

Doesn't include migration topic samples.

| | Current<br>Version | Topic + Notes |
| :---: | :---: | --- |
| 🟢 | 5.0, 3.1 | Blazor Samples |
| 🟢 | 2.1 | client-side/libman/index.md |
| 🔴 | 1.1 | client-side/spa-services.md |
| 🔴 | 2.0 | common/samples/WebApplication1 |
| 🔴 | 2.0 | common/samples/WebApplication1DotNetCore2.0App |
| 🔴 | 5.0, 2.2 | data\ef-mvc\intro.md |
| 🔴 | 5.0, 3.0, 2.1, 2.0 | data\ef-rp\intro.md |
| 🟢 | 3.1 | entity-framework-6.md |
| 🔴 | 3.0, 2.2 | fundamentals/metapackage-app.md |
| 🔴 | 3.1, 2.2 | fundamentals\app-state.md |
| 🔴 | 3.1, 2.2 | fundamentals\change-tokens.md |
| 🔴 | 3.1, 2.2 | fundamentals\configuration\index.md |
| 🔴 | 3.1, 2.2 | fundamentals\configuration\options.md |
| 🔴 | 3.1, 2.2 | fundamentals\dependency-injection.md |
| 🔴 | 3.1, 2.2 | fundamentals\environments.md |
| 🔴 | 5.0, 2.2 | fundamentals\error-handling.md |
| 🔴 | 3.1, 2.2 | fundamentals\file-providers.md |
| 🔴 | 2.2 | fundamentals\host\generic-host.md |
| 🔴 | 3.1, 2.2 | fundamentals\host\hosted-services.md |
| 🔴 | 3.0, 2.2, 2.1, net2.0 | fundamentals\host\platform-specific-configuration.md |
| 🔴 | 3.1, 2.2 | fundamentals\http-requests.md |
| 🟢 | 3.1, 2.1 | fundamentals\localization.md |
| 🔴 | 3.1, 3.0, 2.2 | fundamentals\logging\index.md |
| 🔴 | 3.1, 2.2 | fundamentals\logging\loggermessage.md |
| 🔴 | 2.0 | fundamentals/metapackage/samples/Metapackage.All.Example.csproj |
| 🔴 | 3.1, 2.2 | fundamentals\middleware\extensibility.md |
| 🟢 | 3.1 | fundamentals\middleware\extensibility-third-party-container.md |
| 🟢 | 3.1 | fundamentals\middleware\request-response.md |
| 🔴 | 1.0 | fundamentals\owin.md |
| 🔴 | 3.1, 2.2 | fundamentals\routing.md |
| 🔴 | 3.1, 2.2 | fundamentals\servers\httpsys.md |
| 🔴 | 5.0, 3.1, 2.2 | fundamentals\servers\kestrel.md |
| 🔴 | 3.0 | fundamentals\startup.md |
| 🟢 | 3.1| fundamentals\static-files.md |
| 🔴 | 3.0 | fundamentals/target-aspnetcore.md |
| 🔴 | 3.1, 2.2 | fundamentals\url-rewriting.md |
| 🔴 | 2.2, 1.1 | websockets.md |
| 🔴 | 3.0 | grpc/authn-and-authz.md |
| 🔴 | 2.1, 2.0 | host-and-deploy/docker/visual-studio-tools-for-docker.md |
| 🔴 | 5.0, 3.1, 2.2 | host-and-deploy/health-checks.md |
| 🔴 | 3.1, 3.0, 2.2 | host-and-deploy\windows-service.md |
| 🟢 | 5.0, 3.1 | includes/scaffoldTFM.md |
| 🔴 | 3.0, 2.2 | mvc\advanced\app-parts.md |
| 🔴 | 3.1, 3.0, 2.1 | mvc\advanced\custom-model-binding.md |
| 🔴 | 3.0, 2.2 | mvc/compatibility-version.md |
| 🟢 | 3.1 | mvc/controllers/application-model.md |
| 🔴 | 3.1, 2.2 | mvc/controllers/areas.md |
| 🔴 | 3.1, 2.2 | mvc\controllers\dependency-injection.md |
| 🔴 | 3.1, 2.2 | mvc/controllers/filters.md |
| 🟢 | 3.1, 2.1 | mvc/controllers/routing/samples/2.x |
| 🔴 | 3.0, 2.2 | mvc\controllers\testing.md |
| 🔴 | 3.1, 2.2 | mvc\models\file-uploads.md |
| 🔴 | 3.0, 2.2 | mvc/models/model-binding.md |
| 🔴 | 3.0, 2.2 | mvc/models/validation.md |
| 🔴 | 1.0 | mvc\views\dependency-injection.md |
| 🔴 | 2.2 | mvc\views\partial.md |
| 🔴 | 3.1, 2.0 | mvc/views/razor.md |
| 🔴 | 1.1 | mvc\views\tag-helpers\authoring.md |
| 🟢 | 2.1 | mvc\views\tag-helpers\built-in\samples |
| 🟢 | 2.1 | mvc/views/tag-helpers/th-components.md |
| 🔴 | 2.2 | mvc\views\view-components.md |
| 🔴 | 1.0  | mvc\views\working-with-forms.md |
| 🔴 | 3.1, 2.2 | performance\caching\distributed.md |
| 🔴 | 3.0, 2.2, 2.1 | performance\caching\memory.md |
| 🔴 | 3.1, 2.2 | performance\caching\middleware.md |
| 🔴 | 3.0, 2.2 | performance\caching\response.md |
| 🔴 | 2.2 | performance/objectPool.md |
| 🔴 | 3.0 | performance/performance-best-practices.md |
| 🔴 | 3.0, 2.2 | performance\response-compression.md |
| 🟢 | 3.1, 2.1 | razor-pages\filter.md **RC package present** |
| 🔴 | 3.0, 2.0 | razor-pages\index.md |
| 🔴 | 3.1, 2.2 | razor-pages\razor-pages-conventions.md |
| 🟢 | 2.1 | razor-pages\sdk.md |
| 🔴 | 2.2, 2.0 | razor-pages\ui-class.md |
| 🔴 | 2.0, 1.0 | security\anti-request-forgery.md |
| 🟢 | 3.1, 2.1 | security/app-secrets.md |
| 🔴 | 5.0 | security/anti-request-forgery.md |
| 🔴 | 1.1 | security\authentication\2fa.md |
| 🔴 | 3.0, 2.2, 2.1 | security\authentication\accconfirm.md |
| 🔴 | 3.0, 2.2 | security\authentication\add-user-data.md |
| 🔴 | 3.1, 2.2 | security\authentication\cookie.md |
| 🟢 | 2.1 | security\authentication\identity-configuration.md |
| 🔴 | 1.1 | security\authentication\identity-custom-storage-providers.md |
| 🔴 | 5.0, 3.1, 2.2 | security\authentication\identity.md |
| 🔴 | 3.0, 2.1 | security\authentication\scaffold-identity.md |
| 🔴 | 3.1, 2.2 | security\authentication\social\additional-claims.md |
| 🟢 | 3.1 | security/authorization/simple |
| 🔴 | 3.0, 2.2 | security\authorization\policies.md |
| 🔴 | 3.1, 2.2 | security\authorization\razor-pages-authorization.md |
| 🔴 | 3.0, 2.0, 1.1 | security\authorization\resourcedbased.md |
| 🔴 | 3.0, 2.2 | security\authorization\secure-data.md |
| 🔴 | 3.1, 2.2 | security\cors.md |
| 🟢 | 2.1 | security/gdpr.md |
| 🟢 | 3.1, 2.1 | security/ip-safelist.md |
| 🟢 | 3.1 | security\key-vault-configuration.md |
| 🟢 | 3.1 | security/same-site.md |
| 🟢 | 2.1 | signalr/authn-and-authz.md |
| 🔴 | 3.1, 2.2 | signalr/background-service.md |
| 🟢 | 2.1 | signalr/dotnet-client.md |
| 🟢 | 2.1 | signalr/groups.md |
| 🟢 | 2.1 | signalr/hubcontext.md |
| 🟢 | 2.1 | signalr/hubs.md |
| 🟢 | 3.1, 2.1 | signalr/javascript-client.md |
| 🔴 | 3.0, 2.2, 2.1 | signalr/streaming.md |
| 🔴 | 3.1, 2.2 | test\integration-tests.md |
| 🟢 | 3.1 | test\razor-pages-tests.md |
| 🔴 | 2.0 | tutorials/dotnet-watch.md |
| 🔴 | 3.0, 2.2 | tutorials/first-mongo-app.md |
| 🔴 | 2.0 | tutorials/first-mvc-app-xplat.md |
| 🔴 | 5.0, 3.1, 2.2, 2.0 | tutorials/first-mvc-app.md |
| 🔴 | 5.0, 3.1, 3.0, 2.2 | tutorials\first-web-api.md |
| 🟢 | 3.1 | tutorials/grpc.md (GrpcGreeter, GrpcGreeterClient) |
| 🔴 | 5.0, 3.1, 2.2, 2.1, 2.0 | tutorials/razor-pages/razor-pages-start.md |
| 🔴 | 3.0, 2.1 | tutorials/signalr-typescript-webpack.md |
| 🟢 | 5.0, 3.1 | tutorials/signalr-blazor.md |
| 🔴 | 3.0, 2.1, 2.0 | tutorials/web-api-help-pages-using-swagger.md **RC packages present** |
| 🟢 | 3.1, 2.1 | web-api/action-return-types.md |
| 🔴 | 2.2 | web-api/advanced/conventions.md |
| 🔴 | 3.1, 2.2 | web-api/advanced/custom-formatters.md |
| 🔴 | 5.0, 3.0, 2.2 | web-api/advanced/formatting.md |
| 🔴 | 3.0, 2.2, 2.1 | web-api/handle-errors/samples/2.x |
| 🟢 | 3.1 | web-api/http-repl.md |
| 🔴 | 3.0, 2.2, 2.1 | web-api/index.md |
| 🔴 | 3.1, 2.2 | web-api/jsonpatch.md |
| 🟢 | 5.0 | web-api/route-to-code.md |

**Comment by user135711** [comment]
On the change tokens sample, please add an explanation of how cache dependencies work. I've been trying to figure it out from the source code and debugger, and the Docs don't provide sufficient explanation: 
```
    using (var entry = _cache.CreateEntry(CacheKeys.Parent))
    {
        // expire this entry if the dependant entry expires.
        entry.Value = DateTime.Now;
        entry.RegisterPostEvictionCallback(DependentEvictionCallback, this);

        _cache.Set(CacheKeys.Child,
            DateTime.Now,
            new CancellationChangeToken(cts.Token));
    }

```
How does the child token above communicate to the parent token to evict and what is the purpose of disposing of the parent token? Is this a hack where the parent eviction only occurs because the already marked as expired parent gets evicted when the child cancellation triggers a remove expired entries search? Second suggestion add to sample app a compilable version of this dependent cache entries construction because it makes more sense: https://github.com/aspnet/Caching/issues/48

**Comment by vsaranea** [comment]
I am struggling to figure out how to improve the performance of my shiny new Razor Pages/Page Model based app. I have some hefty partial page renders (sidebar icons based on heavy DB calls), which I want to cache (per-model).

I've tried using the <cache> tag helper, but I can't get the example working as expected.

Is there any ETA for the 2.1 release (with the attached docs drop), or better yet - a way to preview the docs as they are being written by Luke?

**Comment by guardrex** [comment]
> Is there any ETA for the 2.1 release

The only ETA I'm aware of was given by Scott Hunter at the //Build conference when he said that they were aiming for sometime around the end of this month.

> with the attached docs drop

The 2.1 docs are under continuous release now. They're rolling out almost daily. However, samples (this issue) will not be updated until 2.1 releases. We won't have 1.x, 2.0, and 2.1 samples ... only 1.x and 2.x (2.x will be 2.0 prior to 2.1 release; 2.x will become 2.1 after the 2.1 release). We don't want to break users using the latest stable release (2.0) until 2.1 actually hits the street.

**Comment by guardrex** [comment]
@Tratcher The HTTPsys sample isn't happy ("Secure connection failed") with HTTPS Redirection Middleware and ...

```csharp
.UseHttpSys(options =>
{
    // The following options are set to default values.
    options.Authentication.Schemes = AuthenticationSchemes.None;
    options.Authentication.AllowAnonymous = true;
    options.MaxConnections = null;
    options.MaxRequestBodySize = 30000000;
    options.UrlPrefixes.Add("https://localhost:5001");
});
```

Should I not use the middleware in this sample ... or how do I fix this?

**Comment by Tratcher** [comment]
HttpSys https is hard to set up, we didn't do anything to improve that for 2.1. You don't need to add the middleware for this sample, the middleware usage/config wouldn't be any different here.

**Comment by guardrex** [comment]
Sounds good. Thx. I'll comment the line and add a quick note so that its existence is surfaced.

**Comment by Rick-Anderson** [comment]
> there shouldn't be any harm if the folder is updated to samples (plural) at the same time.

Let's not do that. It's fine to have a sample folder with multiple samples under it.

**Comment by guardrex** [comment]
> Let's not do that.

I'll need to revert some changes when I was preparing for 3.x (i.e., I was setting up a "2.x" folder for the work that will be coming for "3.x" in the future). Do you want me to go back and do that?

**Comment by Rick-Anderson** [comment]
>  Do you want me to go back and do that?

No, don't revert. Just stop making the change from sample to samples in future work.

**Comment by bplubell** [comment]
I sounds like this may be on the radar, but wanted to mention it anyway. The [`security\authorization\razor-pages-authorization.md`]() page has a link to a non-existent sample, which looks to have been removed when introducing the 2.x sample in #6835).

**Comment by guardrex** [comment]
Thanks for the heads-up. I'll take a look ... as soon as Gulf Power gets the electricity back on (Florida thunderstorm beat the crap out of us this afternoon).

**Comment by guardrex** [comment]
@bplubell Good news ... Link fixed by phone PR #6978 :+1: ... Bad news ... Gulf Power now says that equipment was destroyed by the storm ... No power until tomorrow. :fearful:

**Comment by spboyer** [comment]
bump. This is a huge issue.  How are we keeping all of the samples up to date with the releases?

**Comment by guardrex** [comment]
@spboyer I'm going as fast as I can. 🏃🏃🏃🏃😅

I'm bogged down a bit by other high priority issues. I try to do these updates whenever I can.

This round of updates from 2.0 to 2.1 requires quite a few small changes. Inevitably, the topic requires concurrent changes, and then I find other problems that need to be fixed along the way. Often, it has been so long since the topic has had a major overhaul/update that it's worth going ahead and taking the time to enhance/update it [e.g., File Providers (#7708) and DI (#7412) topics in review now are in this bucket].

It's also been a longstanding problem that we haven't had the staffing to keep samples updated even prior to 2.1 RTM. I'm still to this day finding:

* 1.0 *project.json*-based samples in the repo! *Yikes!*
* Topics with only a 1.x sample ... a 2.0 sample was never created.
* Samples resting on MVC ... when as of 2.0, they're supposed to be RP-based.
* Even samples resting entirely on console apps. *Geebers McScreebers!* :smile:

> How are we keeping all of the samples up to date with the releases?

As laid out in the table, I recommended that we "call dibs" on them and work them through asap. We just want to make sure that two authors don't quietly pick up the *same topic+sample* and begin working it over. As you can see, I've sort of taken the lead on this issue. I'm getting about two done per week.

One good thing about my having taken so many is that we will achieve a *very high level of consistency* in the layout and feel of the samples. The downside is that with the other priorities distracting me from this issue it's taking longer than I would like to get them done.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @tdykstra Poser, question, query ❓ ...

The new templates include a package for Razor support with MSBuild. This package isn't necessary for samples to run; however, it would be a *nice-to-have* and *mirror-the-template philosophy* to include it in sample apps ...

```xml
<PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
```

... sooooooooooooo .... do you want to include that?

I guess we're already leaning toward samples that take the in-proc prop ...

```xml
<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
```

... that's another one that isn't strictly required for sample apps to run. Under the *mirror-the-template philosophy*, Scott and I said&dagger;, '*Hell, yeah!*'

&dagger;Well, I added the "hell" part. Scott just said "yeah" on that one. :smile:

**Comment by tdykstra** [comment]
This is the kind of "nice to have" that I wouldn't spend time on.

**Comment by guardrex** [comment]
Ok, but I'll eventually need firmer guidance. If we're dropping the in-proc prop into the file just because it's in the template, then doesn't it follow that this one should go in? I'm cool either way ... just asking what we're doing.

**Comment by scottaddie** [comment]
@guardrex I've been removing the `Microsoft.AspNetCore.Razor.Design` package reference, since it's not needed to demonstrate concepts in my docs. It's not worth the time to go back and remove them, but something to consider moving forward.

**Comment by guardrex** [comment]
Ok ... in-proc in and Razor.Design out. Sounds good to me. :+1:

**Comment by bradygaster** [comment]
@guardrex is this issue still current? If not, can you close? Also - apologies if i send a few pings your way from some open issues, i'm trying to do a survey of some of the long-standing open issues to address some of them this week. Reach out if i'm hitting you up too much from GitHub. :)

**Comment by guardrex** [comment]
@bradygaster ... That depends. What normally happens on this issue is that at several points in the past, perhaps once a year, I actually canvas **_every sample app on the repo_** 😅 and update this issue. Then, we usually hit several of the ...... er ..... *more disturbing cases* lol ... like 2.x samples 🙈😄 lingering for popular topics.

It's best to ask @Rick-Anderson if he wants to proceed with this process. I don't mind performing another update of this issue in early 2022 if he/you would like to keep using this. This issue is the only overview of where everything stands with sample apps. I fear without it that we'd have no clear knowledge of what's going on. However, it may have outlived its usefulness. I yield to @Rick-Anderson and you to close if that seems best.

**Comment by bradygaster** [comment]
I'd love to do a survey like that with you. Have you seen the fantastic improvements to the Orleans samples' visibility Reuben made? I think something like that for SignalR and for the broader ASP.NET would be fantastic.

**Comment by Rick-Anderson** [comment]
@guardrex  should we close?

**Comment by guardrex** [comment]
I think so. I don't have time to tend to this further, and it isn't relevant for Blazor, as I've adopted a :x: **_NO SAMPLES!_**&trade; :x: (where possible) approach 😄. This tracking issue was helpful in the old days 👴 to update a bunch of samples release-to-release for topics that I worked on regularly.
