### ISSUE TITLE
ASP.NET Core Razor SDK needs a sample project with code samples

### ISSUE THREAD

**Issue by user135711** [dotnet/AspNetCore.Docs#6130]
[ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1) needs a compilable sample project with actual code in order to be useful.

**Comment by Rick-Anderson** [comment]
@user135711 good idea. Would you be willing to contribute? We should probably make two issues out of this.

**Comment by user135711** [comment]
@Rick-Anderson Sure, if it can wait till next weekend. The Request Features in ASP.NET Core topic is over a year and a half old so I assume it can wait a week.

**Comment by Rick-Anderson** [comment]
@user135711  no hurry.

**Comment by Rick-Anderson** [comment]
@user135711 	any interest in this?

**Comment by user135711** [comment]
@Rick-Anderson sure, Let me find out what my two days off next week are and I'll do it then.

**Comment by user135711** [comment]
Yes, I should have time rather soon.
