### ISSUE TITLE
ActionResult Errors

### ISSUE THREAD

**Issue by Gordon-Fredericks** [dotnet/AspNetCore.Docs#6145]
Adding the following methods to TodoController:

[HttpGet]
public ActionResult<List<TodoItem>> GetAll()
{
    return _context.TodoItems.ToList();
}

[HttpGet("{id}", Name = "GetTodo")]
public ActionResult<TodoItem> GetById(long id)
{
    var item = _context.TodoItems.Find(id);
    if (item == null)
    {
        return NotFound();
    }
    return item;
}

generated the following error:
"The non-generic type 'ActionResult' cannot be used with type arguments"

My fix is as follows:

        [HttpGet]
        public ActionResult GetAll()
        {
            return new ObjectResult(_context.TodoItems.ToList());
        }

        [HttpGet("{id}", Name = "GetTodo")]
        public ActionResult GetById(long id)
        {
            var item = _context.TodoItems.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            return new ObjectResult(item);
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@Gordon-Fredericks The `ActionResult<T>` type assumes you're using ASP.NET Core 2.1. That's the release in which this feature was introduced. You must have selected "ASP.NET Core 2.1 Preview 2" from the version selector at the top of the page. Select 2.0 instead to view that version of the tutorial.

I see now where the confusion stems from in this 2.1 tutorial version. The screenshot at the top of the tutorial reflects ASP.NET Core 2.0. I'll address this.
