### ISSUE TITLE
Request dedicated GitHub repo for code samples

### ISSUE THREAD

**Issue by tony-long** [dotnet/AspNetCore.Docs#6611]
Your GitHub appears to be a dumping ground for code snippets, but I sure people would like better examples that match to real world use cases and have someone clean and organize the GitHub.

`Edit by @Rick-Anderson` Similar issues:
#9763

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @tony-long ... This will improve when the topic is addressed on the overhaul/update on https://github.com/aspnet/Docs/issues/5331. 

Let's leave this issue open, and it will close when the PR merges.

**Comment by Rick-Anderson** [comment]
@tony-long keep in mind the primary use of the repo is to contain snippets that are imported into the produced documents. Providing samples is secondary.

**Comment by tony-long** [comment]
Thanks for the quick response – I’m very impressed with all of you guys!

________________________________

**Comment by Rick-Anderson** [comment]
@SyntaxC4 @dend 	this is a frequent ask. Can you share the plans?
