### ISSUE TITLE
CORS Wild Card support in Azure

### ISSUE THREAD

**Issue by OzBob** [dotnet/AspNetCore.Docs#7167]
The apicors azure portal end point does not accept 
https://*.domain.com/ as a valid 'allowed origin'

A little red exclamation appears and says it must be in the format
[HTTP:HTTPS]://[www.]domain.[TLD][:portnumber]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex  should that info go in an Azure doc?
@OzBob  where do you think it should go?

**Comment by guardrex** [comment]
@OzBob so ...

```
https://domain.com/
```

doesn't work?

**Comment by OzBob** [comment]
no
they do
https://*.domain.com
doesn't

**Comment by OzBob** [comment]
Correction: https://stackoverflow.com/a/49943569/1586498 and https://github.com/aspnet/CORS/pull/76  say that it is now supported in code.
I still can't get it to be a valid origin in the azure portal webapp api CORS form. @Rick-Anderson  is there docs on how to use that CORS feature of the Azure Portal?

**Comment by Rick-Anderson** [comment]
@CamSoper 	

> is there docs on how to use that CORS feature of the Azure Portal?

**Comment by pranavkm** [comment]
Support for wildcard subdomains is a feature of the ASP.NET Core CORS middleware, not actually part of the CORS (fetch) spec. My guess is the Azure service (is this Azure App Services) does not support this feature.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by weisssean** [comment]
I still don't understand how you want us to get around this issue. Azure Static App creates a dynamic url for each environment so how can it call an azure function if the URL changes? Is it just unusable?

**Comment by Rick-Anderson** [comment]
@weisssean @OzBob @clintnetwork if you can recommend the appropriate azure document, I'll transfer this issue to Azure and try to get some help.

**Comment by OzBob** [comment]
Documents that mention CORS that would benefit from noting the limitations of the UI in the portal and maybe (i haven't tested it yet) how to use the Azure CLI instead:

https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api#add-cors-functionality
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0

Azure CLI CORS commands: https://docs.microsoft.com/en-us/cli/azure/webapp/cors?view=azure-cli-latest#az_webapp_cors_add

**Comment by Rick-Anderson** [comment]
@OzBob can you open issues there? This doesn't seem to be related to ASP.NET Core

**Comment by OlivierShi** [comment]
Found the solution for this issue -- APIM CORS with Wild Card

1. Remove CORS policy from APIM for all operations of service.

2. Add an OPTIONS operation for those APIs that needs CORS with wildcards. E.g.,

2.1. With perspective to the operation GET /service/items/{id}

2.2. Add in APIM a new corresponding operation OPTIONS /service/items/{id}

3. Configure the service with the customized CORS policy, like
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/24621410/179013735-860a0940-e129-4acd-b5d8-5f3bc217d58d.png)
4. `app.UseCors(this.allowSpecificOrigins);`

**Comment by weisssean** [comment]
Actually, what I was suggesting was to wildcard the part that changes, so:
`https://smoked-bacon-[*].azurestaticapps.net/`.
