### ISSUE TITLE
signalr/bearer-auth New topic on bearer authentication

### ISSUE THREAD

**Issue by rachelappel** [dotnet/AspNetCore.Docs#7218]
As per [this comment](https://github.com/aspnet/Docs/pull/7199#discussion_r197016867) by @davidfowl, we could use a doc on bearer authentication specifically with server side examples of consuming the token using the JWT auth handler.

**Comment by BrennanConroy** [comment]
This issue is old and might pre-date a lot of the doc work that's been done. Bearer auth is covered in https://docs.microsoft.com/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.1#bearer-token-authentication. If something is missing feel free to file a new issue.
