### ISSUE TITLE
Document main Azure Active Directory integration scenarios in our templates

### ISSUE THREAD

**Issue by javiercn** [dotnet/AspNetCore.Docs#7224]
As part of 2.1 we moved all the support out from the templates and into packages. As part of that move we made some changes:
* Move views/controllers into an area
* Use a policy scheme to setup the different configurations.

We should document how to accomplish a few of the common scenarios with Azure AD and the best practices to extend the logic from the current packages.

* Samples
  * How to setup multiple handlers on the same app.
    * Bearer and OIDC.
  * How to extend the existing code to handle common scenarios
    * Get an access token
* Best practices
  * Where to put different parts of the code
  * How to register them (what order)

**Comment by Rick-Anderson** [comment]
@CamSoper 	 is this something you can do in the next two sprints? If not, @scottaddie 	can take it.

**Comment by CamSoper** [comment]
Wade's got me 100% on this book thing with Jeffrey Palermo. I can help @scottaddie with it, though.

**Comment by Rick-Anderson** [comment]
@javiercn 	@danroth27 	can you assign someone to write the samples and draft the best practices? We don't have the expertise or bandwidth for this.

Note the `PU` label. All `PU` issues are assigned to you guys (Product Unit). We'll provide editing services.

**Comment by javiercn** [comment]
https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8

**Comment by Rick-Anderson** [comment]
@javiercn  Is https://gist.github.com/javiercn/62044bab948e42cc9e4e695e4aaee7b8 ready to turn into a doc?

**Comment by Rick-Anderson** [comment]
ported to #22745 but per `@javiercn`  point people out to Microsoft.Identity.Web
