### ISSUE TITLE
Suggest to add notice for file IISUrlRewrite.xml to use copy always in build action

### ISSUE THREAD

**Issue by EdiWang** [dotnet/AspNetCore.Docs#7292]
When building the App, the file IISUrlRewrite.xml should be set to "copy always" in build action. Or there will be a System.IO.FileNotFoundException after Publish the website.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f7c61-a9fa-bd34-001d-217477874bb6
* Version Independent ID: 9c48da92-af90-3fc1-fde0-c3f74fa88510
* Content: [URL Rewriting Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/url-rewriting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/url-rewriting.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @EdiWang. Thanks for commenting. We don't generally include very much tooling-specific topic instructions for publishing extra files in reference topics. We *do* include project file configuration to move the assets on publish in the sample apps for these topics. In the sample app for this topic, see ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/url-rewriting/sample/UrlRewritingSample.csproj#L7-L9

**Comment by Rick-Anderson** [comment]
@EdiWang  How about mentioning the following is needed in the project file?

```
	<ItemGroup>
		<Content Include="ApacheModRewrite.txt;IISUrlRewrite.xml;" CopyToPublishDirectory="PreserveNewest" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
```

I notice the build action defaults to "Copy if newer", which works for deployment to Azure.
<img width="159" alt="image" src="https://user-images.githubusercontent.com/3605364/156845751-ff9b65ab-b2fe-4db3-9cdc-299029774353.png">
