### ISSUE TITLE
Include more LogEvent detail in "Logging in ASP.NET Core"

### ISSUE THREAD

**Issue by ArjayHawco** [dotnet/AspNetCore.Docs#7384]
Would it be possible to get additional information in the EventLog section of the above docs (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x)?

In short:
1) Details around using AddEventLog(EventLogSettings) and the requirement of running the app in administrator mode to get the event log and source created.
2) How to embed event related message resources in .net core app and register the app so the dreaded "The description for Event xxx from source yyy cannot be found" messages.
3) A helpful tip to instruct the user to restart the machine after registering a source and log name (otherwise, the events won't show up in the event viewer)

The sample for Windows EventLog Provider shows the following code snippet.
`logging.AddEventLog()`

This can be improved by noting the AddEventLog(EventLogSettings) override that allows the user to set the SourceName and LogName properties.  In addition, it would be helpful to note that admin permissions are required to during the first time when the SourceName/LogName pair doesn't exist and needs to be created.  In addition, noting that the Event Log has some quirks where restarting the dev machine is sometimes required in order that the event logs will show up would be helpful as well.

Lastly, there is no documentation on how to include resource messages in the .Net core app so the event doesn't appear in the event viewer with the "The description for Event xxx from source yyy cannot be found" message.

There are several articles on the web that tell you to set the EventMessageFile in the registry or via powershell and instruct the reader to set it to the .net framework that is being used.  When the EventLogSettings class is used (and the app is run in administrator mode), the EventMessageFile is set to 
`C:\...\.nuget\packages\runtime.win-x64.microsoft.netcore.app\2.0.0\runtimes\win-x64\native\EventLogMessages.dll.`

We need a detailed article on the proper way to include event messages in the .net core app and how to register it so we don't get the above missing event id error in the event log entry.

**Comment by guardrex** [comment]
Thanks for commenting @ArjayHawco. I agree with you. The reason that it seems like the coverage is so light is that this topic goes back to the days of 1.0. It's received some updates along the way, but it hasn't had a major overhaul since it was first written. I'm making updates to it today on #7386, and it will get more updates when the sample app is upgraded on #5495. I think we should have another round of updates beyond that to address your remarks on this issue. Let's use this issue to track the work.

**Comment by ArjayHawco** [comment]
Thanks guardrex.  I'll keep checking back.  You may want to include details docs/samples for EventSource as well.  I'll file a separate issue for that.

**Comment by guardrex** [comment]
Let's use this issue for that too. Can you add that to the top? :point_up: May as well do both at the same time.

**Comment by guardrex** [comment]
Just hit this one myself ...

> This can be improved by noting the AddEventLog(EventLogSettings) override that allows the user to set the SourceName and LogName properties. 

It needs at least these minimal bits. It might need some cross-links for setting up a custom log ... or perhaps even some explicit instructions on the subject.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
