### ISSUE TITLE
Add .editorconfig file to enforce consistency in ASP.NET Core sample apps

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#7487]
See https://github.com/aspnet/Docs/pull/7474#discussion_r200680276

**Comment by Rick-Anderson** [comment]
cc @serpent5

**Comment by serpent5** [comment]
I think we could do this now, with a basic set of formatting rules to ensure newlines at the end of files, etc. We can build up the rules as we go for C# conventions, etc.
