### ISSUE TITLE
Add caveats to HttpContext (IHttpContextAccessor) topic

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#7721]
Access HttpContext in ASP.NET Core
fundamentals/httpcontext

Perf: aspnet/Hosting#793

See https://github.com/dotnet/aspnetcore/issues/27392 and close that issue once this issues is closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Things to document
- The HttpContext is *NOT* thread safe, accessing it from multiple threads is a no no
- The HttpContext may be captured outside of the request flow when using the IHttpContextAccessor (will provide an example)
- IHttpContextAccessor.HttpContext may be null if accessed outside of the request flow.

cc @benaadams @Tratcher @halter73 @pakrym 

I'll expand this when I scavenge more things we've seen in issues.

**Comment by halter73** [comment]
> IHttpContextAccessor.HttpContext may be null if accessed outside of the request flow.

I think we should be stronger with our guidance. If you want to access info from the HttpContext outside of the request flow, you should copy out the info inside the request flow. Since the HttpContext is not thread safe, trying to access it outside of the request flow is asking for problems.

**Comment by davidfowl** [comment]
@halter73 agreed, we should also have examples. I'm mostly looking for a brain dump right now so we can get all of the topics.

**Comment by davidfowl** [comment]
@gulbanana Yes that would help some of these issues but it also is limited (it can't be injected into singletons) and has the downside that it's yet another way to do a similar thing.

**Comment by gulbanana** [comment]
having two overlapping ways to do it sucks, yeah, but this mechanism could at least be used by asp.net’s own stuff. right now features like Authentication have to use IHttpContextAccessor and risk leaking memory..

**Comment by Rick-Anderson** [comment]
@halter73 if you can provide a draft and sample code we can get this documented.

**Comment by halter73** [comment]
I think updating the `SendEmail` example to be a service instead of a Controller might be sufficient. The thread safety issues aren't unique to `IHttpContextAccessor`, but it can be easier not to consider the ramifications of accessing the HttpContext from a background thread when it's accessed from a service via `IHttpContextAccessor`.


```csharp
public class EmailService : IEmailService
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public EmailService(IHttpContextAccessor httpContextAccessor) =>
        _httpContextAccessor = httpContextAccessor;

    
    public void SendEmail(string email)
    {
        // Services should account for the possibility of HttpContext being null if not called from a request thread.
        // The service should either throw or gracefully handle this. 
        var correlationId = _httpContextAccessor?.HttpContext.Request.Headers["X-Correlation-Id"].ToString();

        _ = SendEmailCoreAsync(correlationId);
    }

    private async Task SendEmailCoreAsync(string? correlationId)
    {
        // ...
    }
}
```

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan can you provide a sample with the preceding code? Put the sample in https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/fundamentals/http-context/samples/6.x

**Comment by fiyazbinhasan** [comment]
Sure. I'll take a look at it asap 😺

**Comment by halter73** [comment]
I also like the remarks in the [API docs for IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-6.0). We should include this in the conceptual docs.

> This interface should be used with caution. It relies on [AsyncLocal<T>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1) which can have a negative performance impact on async calls. It also creates a dependency on "ambient state" which can make testing more difficult.
