### ISSUE TITLE
Document "tail-async" code in SignalR

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#7876]
See PR  #7865

When this pattern is used, we need a comment like:

This method runs asynchronously. See dotnet/docs#6734 
Hopefully @BillWagner  will provide an article we can link to

It would be good to  comment/link the first time this pattern is used in an article.

**Comment by tdykstra** [comment]
@Rick-Anderson

* Do you want to wait for https://github.com/dotnet/docs/issues/6734 to be addressed first so we have an article to link to?  Or go ahead now and link to issue 6734?
* The only place I'm aware of that needs the note is the one in https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md ; are you aware of others?
* That article uses range for snippets, I would also update it to use snippet tags while adding the tail-async notes.

**Comment by Rick-Anderson** [comment]
go ahead now and link to issue 6734?

>are you aware of others?
@BrennanConroy do you where else to Document "tail-async" code?

>I would also update it to use snippet tags while adding the tail-async notes.
🥇

**Comment by BrennanConroy** [comment]
I saw one more tail-async in https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md

**Comment by bradygaster** [comment]
closing due to age. @BrennanConroy - re-open with a comment if this needs to remain open.
