### ISSUE TITLE
How are user roles managed

### ISSUE THREAD

**Issue by eschneider999** [dotnet/AspNetCore.Docs#8162]
There is nothing in this article to explain how a role is given/taken from a user?
Or at least a link to the topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio

**Comment by eschneider999** [comment]
Thanks Rick

**Comment by RyanTaite** [comment]
@Rick-Anderson Hey Rick, that link makes no mention of adding or removing Roles to a User, am I misunderstanding it or is there by chance another topic I can view?

**Comment by Rick-Anderson** [comment]
Sorry, wrong link
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1

the app uses auth handlers.

**Comment by RyanTaite** [comment]
Great, thank you!
