### ISSUE TITLE
Says Asynchronous Code should be used but DbInitializer.cs Example is Not Asynchronous

### ISSUE THREAD

**Issue by robinwilson16** [dotnet/AspNetCore.Docs#8214]
The documentation says to always use asynchronous code yet the code given in DbInitializer.cs is synchronous.

The code should be re-written to use asynchronous methods (unless I am missing something).

This would involve changing commands from:
```
context.Student.Add(s);
context.SaveChanges();
```
To
```
await context.Student.AddAsync(s);
await context.SaveChangesAsync();
```
Either seems to work ok though and produce the desired result. Maybe as it only runs once during project startup it doesn't really matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@robinwilson16  good suggestion. We hope to rewrite the initializer . See #8138

**Comment by Rick-Anderson** [comment]
@robinwilson16 given seeding the DB is a one-time operation for non-production code, simplicity/debugabilty is more important. I've had to debug seed code more than once.

**Comment by robinwilson16** [comment]
Ok thanks Rick. I can see why it isn't needed there in that case.
Robin

**Comment by Rick-Anderson** [comment]
Thanks for bringing this up. When we update the doc we'll explain why we're using synchronous.
