### ISSUE TITLE
Migration to HttpClientFactory

### ISSUE THREAD

**Issue by scottaddie** [dotnet/AspNetCore.Docs#8313]
Per an email from Glenn, create one of the following:

1. A new doc under the Migration ToC node titled "Migrate from HttpClient to HttpClientFactory".
1. A new section in the [existing doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests) that covers migration from `HttpClient`.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
