### ISSUE TITLE
Update EF Core Tools

### ISSUE THREAD

**Issue by sana-ajani** [dotnet/AspNetCore.Docs#8545]
How do I update EF Core Tools? I tried running "update-package" in the PMC, but still get this warning when doing "Update-Database": 

The EF Core tools version '2.1.1-rtm-30846' is older than that of the runtime '2.1.3-rtm-32065'. Update the tools for the latest features and bug fixes.
Microsoft.EntityFrameworkCore.Model.Validation[30000]. 

`@Rick-Anderson` edit/summary of solution:

* If you get the warning via the console/CLI `dotnet ef` command,  install the latest version of the [.NET Core SDK](https://www.microsoft.com/net/download/archives)- but not the preview version.
* If you get this warning in the PMC (Program Manager Console - using EF commands (`Update-Database` etc.) - Add the following package reference to the *.csproj* project file:

`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4" />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What does `dotnet --version` show? Can you share your project file (.csproj).

cc @tdykstra @scottaddie @guardrex

**Comment by Rick-Anderson** [comment]
@sana-ajani install the latest version of the [.NET Core SDK](https://www.microsoft.com/net/download/archives) But not the preview version.

**Comment by Rick-Anderson** [comment]
@bricelam  more customers are reporting this problem with the current SDK.

**Comment by prlcutting** [comment]
You can add me to the list of people experiencing this problem.  I have version 2.1.402 of the SDK installed on a Windows 10 machine and get the error message when issuing EF commands in the Package Manager Console window in Visual Studio 2017 (version 15.8.4).

**Comment by bricelam** [comment]
If you get the error using `dotnet ef`, update the SDK like @Rick-Anderson said.
If you get the error using PMC (`Update-Database` and friends), update the package like @GiorgioG said.

**Comment by prlcutting** [comment]
@bricelam So, is this a new requirement to install the EntityFrameworkCore.Tools package?  My project file does not have a reference to an older version of this package, and I used to be able to issue EF commands from the PMC without getting this warning message before.

**Comment by bricelam** [comment]
For now, yes. We're sorting it out in future versions. (See also aspnet/Home#3503)

**Comment by DarrenGansberg** [comment]
> If you get the warning using `dotnet ef`, update the SDK like @Rick-Anderson said.
> If you get the warning using PMC (`Update-Database` and friends), update the package like @GiorgioG said.
> If you're not encountering any issues or missing features, also feel free just to ignore the warning.

Can someone clarify exactly which project would reference the package in the .csproj file, if using a multiple project solution, in order to resolve the issue, as per Rick Anderson's suggestion?

**Comment by Rick-Anderson** [comment]
@DarrenGansberg 	the project that's using the EF tools.

**Comment by redplane** [comment]
@GiorgioG solution worked.

**Comment by hayfaaa** [comment]
Update tools by using the package manager console:

`Install-Package Microsoft.EntityFrameworkCore.Tools -Version 2.1.3`

**Comment by jkdmyrs** [comment]
Just experienced this issue in an Azure DevOps build pipeline. Using YAML builds, didn't alter my YAML file at all, and started to experience this issue. Does anyone have any insight into why this would randomly stop working in an environment like AzureDevOps hosted agents, or direct me to the correct location to report the problem? I have build and repo history which proves nothing changed on my end to cause the build to stop working with ADO.

**Comment by mrlife** [comment]
> For reference, to fix it in dotnet core 3, run the following:
> 
> ```
> dotnet tool update --global dotnet-ef
> ```

Even though I'm on the latest version of the SDK and `Microsoft.EntityFrameworkCore.Tools`, I needed to run the above.
