### ISSUE TITLE
Create new doc article on handling server side and client side culture on ASP.NET

### ISSUE THREAD

**Issue by eriawan** [dotnet/AspNetCore.Docs#8585]
**Describe the new topic**

- This topic is highly needed because currently in the docs pages there's no article that describe server side and client side culture handling in ASP.NET Core 2.2, as described in issue #4076  
- This culture handling topic should be located under ["Globalization and localization"](https://docs.microsoft.com/aspnet/core/fundamentals/localization).

**Abstract**
- Describe server-side culture feature in ASP.NET Core 2.2 and handling them (with sample code)
- Describe client-side culture feature in ASP.NET Core 2.2 and handling them (with sample code)
- incorporate sample validation as described in #4076 

**Items to track**

- [ ] Handle client-side (user agent's) culture from server side culture and sample code
- [ ] Handle client-side (user agent's) culture from client-side culture handling and sample code, using `AcceptLanguageHeaderRequestCultureProvider` in combination with jQuery
- [ ] Use validation sample as another sample case with code

NOTES: other contents will be added later

cc @Rick-Anderson 

I welcome feedback 🙂

**Comment by hishamco** [comment]
> Describe server-side culture feature in ASP.NET Core 2.1 and handling them (with sample code)

If you mean providing culture using `IRequestCultureProvider` the current docs already describes this, also `AcceptLanguageHeaderRequestCultureProvider` described there, i'm not sure what you will add, but I write my comments later

thanks

**Comment by eriawan** [comment]
@hishamco 

Thanks!
Yes, current doc already describes that. I may as well add the needed case on client side while also add more detail on server side. My WIP may or may not be in the form of new page.

**Comment by hishamco** [comment]
>  I may as well add the needed case on client side while also add more detail on server side

Could you please elaborate?

**Comment by eriawan** [comment]
I mean, for client side I will try to integrate with the previous problem when handling with jquery validation, and also try to have one sample that has handling for both server-side and client-side culture.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg please review outline.

**Comment by ryanbrandenburg** [comment]
By outline do you mean the items under the abstract heading? What's there is fine, but it doesn't give me much of an idea of what the doc will look like or say.

**Comment by Rick-Anderson** [comment]
@eriawan go ahead.

**Comment by eriawan** [comment]
@Rick-Anderson 
thanks! I will start tomorrow.

**Comment by ryanbrandenburg** [comment]
Seems like this is on @eriawan's plate now. If there was still an action item for me here re-assign me with a description of what needs done.

**Comment by Rick-Anderson** [comment]
Thanks @ryanbrandenburg 	just wanted to verify you were OK with the plan.

**Comment by eriawan** [comment]
Yes, the work is still ongoing.
I have updated the abstract above to indicate that the page will describe and emphasize handling client-side culture from server-side and client side.

**Comment by hishamco** [comment]
@eriawan can create a WIP PR so we can see what's going on, also it's good to get the feedback at the early stages

**Comment by eriawan** [comment]
@hishamco 
I agree, thanks for the help 🙂 
yes, I will put the PR after I finish testing my code against some web browsers first.

**Comment by hishamco** [comment]
@eriawan any update on this?

**Comment by eriawan** [comment]
@hishamco 

hang on, my testing to many web browsers about this feature is done, also because I've also tested the upgrade to .net core 2.1.500 SDK and test on it too. I'm alsoe adding some highlights comparing to core 2.0. 

I'll push it soon within next week, please be patient 🙂

**Comment by FFMartin** [comment]
@eriawan 
Any update on the subject ?

**Comment by eriawan** [comment]
@FFMartin 
testing is done! the page will be ready, with additional info for .NET Core 2.2 to keep up with.
 please be patient 🙂

**Comment by dotVip** [comment]
Any update on the subject ?

**Comment by eriawan** [comment]
@dotVip 

The article will be ready around end February, with samples on .NET Core 2.1 and 2.2 and interop with server side. Please be patient 🙂

**Comment by Rick-Anderson** [comment]
@eriawan 	I wouldn't worry about 2.1

**Comment by guillos** [comment]
Any Update? I´m stuck on this and don´t konw what to do...

**Comment by Ragowit** [comment]
Any update on the subject?

**Comment by hishamco** [comment]
@eriawan could you please share what you did till now, so anyone can contribute on this in case you are busy

**Comment by hishamco** [comment]
@eriawan What's the status of this one?

**Comment by eriawan** [comment]
@hishamco 

Apologize, I have been too busy for 5 months of work related (mostly focusing on cloud and DevOprs work), and traveling a lot for the last 2 months. I have had a working code with some explanation on my side on ASP.NET Core 2.2.

Will load on my Gist first this week and I may need some help from you.

Thanks for being patience! 🙏 👍

**Comment by hishamco** [comment]
> Will load on my Gist first this week and I may need some help from you.

Anytime .. You can push what you come up with and review it, draft PR may suitable for this case

**Comment by hishamco** [comment]
@eriawan Any updates?

**Comment by Rick-Anderson** [comment]
@eriawan  Just update or 3.0

**Comment by hishamco** [comment]
@eriawan seems this one is lost :)

**Comment by eriawan** [comment]
> @eriawan Just update or 3.0

Yes, I'll focus on .NET Core 3.0 RTM. It's easier to do in 3.0, actually..
Apologize it took too long for me to test.

**Comment by hishamco** [comment]
👀

**Comment by Rick-Anderson** [comment]
@eriawan  checking in. A 3.1 version would be great - or 5.0 :)

**Comment by dannevesdantas** [comment]
Hey guys, are you searching for contributors to help writing the server/client side culture docs?

**Comment by eriawan** [comment]
@Rick-Anderson 
yes, I think 3.1 is better and it should be not much different on 5.0.

thanks for your patience! I'm still testing it, especially on the latest Chrome, Firefox and MS Edge beta that uses Chromium.

**Comment by Rick-Anderson** [comment]
@dannevesdantas  always looking for help.

**Comment by hishamco** [comment]
Me too :smile:, but I'm not sure why this takes so long, without any draft?!!

**Comment by dannevesdantas** [comment]
Can we help in some way @eriawan? Do you need some help?

**Comment by hishamco** [comment]
@eriawan any updates on this one, could you please push a draft PR, so we can help you

**Comment by eriawan** [comment]
@hishamco 

please be patient, I'm still migrating the code to .NET Core 3.1

**Comment by hishamco** [comment]
My intend to help you nothing else, coz this issue takes long time

**Comment by ericvb** [comment]
What is the current status?

**Comment by hishamco** [comment]
Any progress on this one?

**Comment by hishamco** [comment]
Any progress on this one?

**Comment by Rick-Anderson** [comment]
@eriawan  anything we can do to help? .NET 6 is all we need.

**Comment by eriawan** [comment]
@Rick-Anderson 

My bad, I apologize.
Let me revisit and try to come up wip in a week.

**Comment by hishamco** [comment]
I suggest to send WIP PR, we can all help you on this

**Comment by Rick-Anderson** [comment]
@eriawan anything we can do to help? .NET 7 is all we need.

**Comment by hishamco** [comment]
This issues has no progress since 4 years unless there's a local branch doesn't push, again anything we can help you?

**Comment by eriawan** [comment]
I'm deeply sorry I had taken this too long and I also I had to switch jobs during pandemic.
I have had work this on my work for .NET 6 and as suggested, I'm goiing to continue to put for .NET 7

**Comment by Rick-Anderson** [comment]
> For .NET 7 I should use VS 2022 17.4 Preview with .NET 7 SDK Preview, right?

I'm on Version 17.4.0 Preview 2.0 today. Use the most current version.

**Comment by Rick-Anderson** [comment]
@eriawan Just use .NET 7.

**Comment by hishamco** [comment]
Could you please post a WIP PR, this took more than two years

**Comment by Rick-Anderson** [comment]
@eriawan  any ETA. You can use .NET 8

**Comment by hishamco** [comment]
@Rick-Anderson this is taken too long, is there anything here to help you with?

**Comment by Rick-Anderson** [comment]
I'll close the issue. IF @eriawan  makes a PR, we can re-open.

**Comment by Ragowit** [comment]
I really hope to see an update, since culture/localization is very important to all of us with more then just English as language. But yeah, it's been 6 years now...

**Comment by hishamco** [comment]
@Ragowit is there anything in particular you need to update?

**Comment by Ragowit** [comment]
@hishamco I have switched job over the last six years so I don't work with ASP.NET anymore. But I'm still keeping an eye on this out of interest.

**Comment by hishamco** [comment]
All the best
