### ISSUE TITLE
Cannot set shortcut key

### ISSUE THREAD

**Issue by mayatstafford** [dotnet/AspNetCore.Docs#8733]
Press shortcut keys field is read only

Update:  I was trying to type F7.   Pressing the F7 key worked. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@mayatstafford A couple of questions for you:
1. Can you please provide a screenshot?
2. Which version of Visual Studio 2017 are you using? You can find this info in **Help** > **About Microsoft Visual Studio**.

**Comment by mgoldy-linux** [comment]
I have the same issue. I can place the cursor in the "Press shortcut keys:" text box but cannot enter "F7".  My version is the Community version 15.8.4

**Comment by Rick-Anderson** [comment]
15.9 preview 2 and higher community works without having to set the F7 key.

**Comment by mayatstafford** [comment]
I'm using Visual Studio Professional 2017 15.8.0
![image](https://user-images.githubusercontent.com/20777925/46542785-4944f500-c88d-11e8-962f-58edd3c91550.png)
