### ISSUE TITLE
Update Choose 4.x or Core for 3.0 - update for .NET 5

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/AspNetCore.Docs#8749]
When .NET 5 RC1 is released.

https://github.com/aspnet/Announcements/issues/324

@scottaddie  what does this look like for .NET 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51aecd70-d07a-3e43-0f93-63fc1a4ed1b1
* Version Independent ID: fbc66624-1597-225a-3945-1f16e08ddaec
* Content: [Choose between ASP.NET and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/choose-aspnet-framework.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/choose-aspnet-framework.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by wadepickett** [comment]
Completed update for  first topic for this issue (Choose between ASP.NET and ASP.NET Core) with PR 13310. 
Now moving on to fix 2nd topic  Choosing between .NET Core and .NET Framework for server apps..
