### ISSUE TITLE
Add docs for recommended patterns for multi-tenancy in DI

### ISSUE THREAD

**Issue by davidfowl** [dotnet/AspNetCore.Docs#9078]
See https://github.com/aspnet/AspNetCore/issues/2964#issue-305746022

**Comment by Rick-Anderson** [comment]
@Antaris would you be able to provide a draft of this doc? cc @sebastienros

**Comment by Antaris** [comment]
@Rick-Anderson Happy to have a look at this 👍

**Comment by Rick-Anderson** [comment]
@Antaris 	any luck with a draft?

**Comment by Antaris** [comment]
@Rick-Anderson Sorry I haven't been able to get on this yet, life stuff (marriage, etc). Do you have a deadline you would like a draft by?

**Comment by Rick-Anderson** [comment]
@Antaris 	no hard deadline, when you have a chance.

**Comment by Antaris** [comment]
@Rick-Anderson I know I am now half a year late on this (changing jobs, etc. :-)), but I've finally sat down to start putting some guidance together. Hope to have a draft with you by the end of this week

**Comment by Rick-Anderson** [comment]
@Antaris  just checking in
