### ISSUE TITLE
Hard to find download link

### ISSUE THREAD

**Issue by ArveSystad** [dotnet/AspNetCore.Docs#9093]
As of now, you have to read through quite a bit of text just to find the download link. People experienced with IIS and hosting want a simple "Download hosting bundle here!" at the top of the screen, instead of browsing through loads of pages and reading lots of text to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I like it. I can also place a link next to it that takes the visitor down to the section where it's described if they need more detail.

The reason this probably didn't come to mind is that the topic's TOC makes it easy to get to the link. It is true tho that the :eye: has to wander over there to find the link to that section ...

<img width="203" alt="capture" src="https://user-images.githubusercontent.com/1622880/47152614-d121fa80-d2a2-11e8-8048-9c738fddb2a8.PNG">
