### ISSUE TITLE
Enhance WS topic with FDD scenario

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/AspNetCore.Docs#9214]
This article currently specifies that self-contained is required, which is not exactly true. Framework-dependent apps can be used to run Windows services as well. With .NET Core 2.0 and older, this requires setting up the service to run `dotnet.exe foo.dll`. With .NET Core 2.1 and newer, users have an additional option -- framework dependent executables (`foo.exe`). In the 2.1 SDK, this feature is opt in (`<UseAppHost>true</UseAppHost>`). In the 2.2 SDK, this will be on by default. https://github.com/dotnet/sdk/pull/2462

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
1. What's the recommendation for 2.1 or earlier? Should we just link over to the [App deployment topic](https://docs.microsoft.com/en-us/dotnet/core/deploying/), where the pros and cons of each are described and let the dev base their decision on that content?
1. WRT FDE (since 2.1): Is that only available for services and not available for other deployments of .NET Core apps? Is there a plan to cover FDE in the App deployments topic (AFAICT there's no issue on dotnet/docs for it)?
1. WRT scheduling: Is this more of a 'we need it soon' (weeks), or can this wait until later in the year?

cc: @shirhatti

**Comment by natemcmaster** [comment]
1. I think linking to that deployment doc and helping people understand the tradeoffs is good enough. There are advantages each way: isolation vs servicing, app size vs dependencies, etc.
2. FDE: I also didn't see anything in https://github.com/dotnet/docs/issues on the subject. @peterhuene @livarcocc are there already plans to document framework dependent executables?
3. IMO later this year is fine. There is nothing _wrong_ with doing self-contained apps as a Windows service. It's just a little misleading that the doc says it is required.

**Comment by Rick-Anderson** [comment]
@guardrex 	focus on 2.1 and later for the first update.

**Comment by guardrex** [comment]
@natemcmaster I'm starting work on this one today. I'm still wondering about the FDE scenario. I should be able to get it in here. Without FDE coverage in the deployment topic, I don't have anything to point to for dev guidance for that scenario. I'll need to carry a little bit of deployment content here to cover that scenario.

@mairaw, *Hola!* :wave: ...... AFAICT, there's no issue to document the "framework-dependent executable (FDE)" scenario in [.NET Core application deployment](https://docs.microsoft.com/dotnet/core/deploying/). Should there be an issue, or will FDE not be covered (or at least not for the foreseeable future)?

Another option is not to cover FDE with the FDD updates here. However, that just produces an issue to replace this one. I'd like to see the issue count **_go down_** ... not sideways.

**Comment by natemcmaster** [comment]
@guardrex 

> Another option is not to cover FDE with the FDD updates here. 

I wouldn't attempt to completely explain the framework-dependent executables in this aspnet doc. That seems like something the dotnet/docs team should handle since this feature applies to all .NET Core projects, not just aspnet. I don't have all the details on this feature and what it should be named in documentation, but @livarcocc @peterhuene @kathleendollard may be able to help.

**Comment by guardrex** [comment]
I'm trying the most minimal coverage that I can get away with ... something like ...

> When the FDD scenario is used with an ASP.NET Core app, the SDK produces an assembly (library) file (*\*.dll*) that's run with the `dotnet` command. When the FDD scenario is used with an ASP.NET Core Windows Service app, the SDK produces an executable (*\*.exe*), called a *framework-dependent executable*.

Other than listing the two deployment scenarios, I don't say anything else. I refer the reader to the .NET Core doc on the subject.

[I *just* typed that out ... so the paint isn't dry on it yet. We can strike or update it on review.]

**Comment by guardrex** [comment]
@natemcmaster WRT FDE ...

> framework dependent executables (foo.exe) ... In the 2.1 SDK, this feature is opt in (<UseAppHost>true</UseAppHost>). In the 2.2 SDK, this will be on by default. dotnet/sdk#2462

If I only use the `netcoreapp2.2` TFM with the 2.2.0-preview3 SDK ...

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.2</TargetFramework>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>
```

... and publish ...

```console
dotnet publish --configuration Release --output c:\\svc
```

I do get an FDD, but I don't get an **FDE** ...

<img width="198" alt="capture" src="https://user-images.githubusercontent.com/1622880/48911612-cf66cc00-ee38-11e8-934a-f73acabcb84f.PNG">

If I add the `<UseAppHost>` prop, the SDK demands that I provide an RID. When I provide the RID, it publishes with an executable. It also publishes with an EXE if I only add the RID. However in both of those cases, it doesn't publish as an FDD/FDE ... it publishes an SCD. This is in spite of using the same `dotnet publish` command without an RID.

If I provide an RID **_AND_** the `<SelfContained>` switch set to `false` ...

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.2</TargetFramework>
  <SelfContained>false</SelfContained>
  <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>
```

... and publish ...

```console
dotnet publish --configuration Release --output c:\\svc
```

... the output is what I'm looking for ...

<img width="200" alt="capture" src="https://user-images.githubusercontent.com/1622880/48912545-895f3780-ee3b-11e8-9a46-43a80a4c4e5d.PNG">

Idk if that runs yet ... I think it will run ... I'll find out in a few minutes. 🤞

Is that the correct FDE guidance? ... provide the `<SelfContained>` switch set to `false` and an RID?

Side-question: I like using the `Sdk.Web` for its helpful publishing characteristics. However, this isn't a web app. I don't like seeing the *web.config* come out. Thus far, I'm tossing in ye olde `<IsTransformWebConfigDisabled>` set to `false`. Are you ok with that?

**Comment by natemcmaster** [comment]
> Is that the correct FDE guidance? ... provide the `<SelfContained>` switch set to false and an RID?

It appears that is what is required to generate a framework dependent executable. I'll let @peterhuene @nguerrera and @livarcocc say whether the guidance is the intended usage or not: FDE is an SDK feature that they worked on.

**Comment by guardrex** [comment]
@nguerrera Thanks ... and that's good news really because I guessed on the PR to go that way. I'm going to open a 3.0 docs issue referencing this convo so the docs team doesn't lose track of it.

@natemcmaster I guess we can proceed with review if you have more updates. I'll wait tho to hear back from Sourabh on the `<SubType>Component</SubType>` component bit.
