### ISSUE TITLE
Non-IPageConvention conventions descriptions for RP and MVC

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#9269]
From @pranavkm on #5520 ...

&gt; might be good to add a quip about property model \ parameter model conventions. Sort of along the lines of https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#sample-modifying-the-parametermodel. For most parts, you could copy the docs \ samples verbatim.

The current RP conventions topic entirely focuses on conventions that implement `IPageConvention` ... so it's very RP `options.Conventions`-focused. Copying over other "conventions" that apply to both MVC and RP will probably lead to a duplication of content.

We might need to restructure how conventions that apply to both MVC and RP are covered.

@Rick-Anderson 	edit: 3.6 K PV/month

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c32c8-ec27-1771-bb62-71d6aa55b1d6
* Version Independent ID: 99dc76fb-8762-20a6-d7b1-df3ce6e6fc4d
* Content: [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/razor-pages-conventions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
MOved to Master Razor Pages route: #16808

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
