### ISSUE TITLE
Article version should match linked download 

### ISSUE THREAD

**Issue by mayatstafford** [dotnet/AspNetCore.Docs#9292]
The starter & complete app download links are for 2.0.   The repository has version 2.1.  Where is the download for 2.2 which is referenced in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1#the-starter-and-completed-app)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by monsij** [comment]
Hello there. Can you tell m what is to be done in this issue? Should I change the download links? @mayatstafford

**Comment by mayatstafford** [comment]
The links go to 2.0 samples although the article looks like it is written for 2.1 or higher so that needs to go to the correct version.  I don't know what version this page is written for.

Also, in the samples the final 2.1 project targets 2.2 and the starter 2.1 project targets 2.1.

**Comment by mayatstafford** [comment]
So this article is for a 2.2 which is a preview version?

**Comment by Rick-Anderson** [comment]
Just that one API call. See [this GitHub issue](https://github.com/aspnet/Identity/issues/1813#issuecomment-394543909) for a work-around.
