### ISSUE TITLE
How to publish Runtime Store IHostingStartup implementation assembly to Azure

### ISSUE THREAD

**Issue by toryb** [dotnet/AspNetCore.Docs#9408]
Hi,
One thing that doesn't seem to be addressed here is how to make a runtime store IHostingStartup assembly available when I publish the WebHost application to Azure. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.1&tabs=windows#runtime-store)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I presume you mean for a no-compile-time reference hosting startup, since a hosting startup published as a NuGet package with a compile-time reference is ok. My impression is that for a no-compile-time approach that one would need to use an installer. @pakrym, can u clarify?

**Comment by toryb** [comment]
@guardrex 
> I presume you mean for a no-compile-time reference hosting startup

Yes that is what I meant. 

In the document, no-compile-time reference was deployed using the runtime store method. I don't know if there is any access to adding to the runtime store for Azure deployed Web Apps. I really hope so because the no-compile-time reference will really solve an issue for us.

**Comment by guardrex** [comment]
Correct ... AFAIK, the approach requires an *installer* in the mix to take care of placing the hosting startup in the runtime store ✨ *auto-magically* ✨ for an end user (i.e., someone who won't be executing the `dotnet store` command on their machine).

... However, I defer to Pavel to tell us what's what.

![mccoy](https://user-images.githubusercontent.com/1622880/47953270-6848ac80-df49-11e8-962f-b0c9f6bf7cf7.png)

*Damn it Jim! I'm a doc doctor, not a Microsoft engineer!* - Dr. Leonard H. "Bones" McCoy ([DeForest Kelley](https://en.wikipedia.org/wiki/DeForest_Kelley))
[Star Trek](http://www.startrek.com/), ©1966-69 [Paramount Pictures](http://www.paramount.com)

**Comment by pakrym** [comment]
I think we had a mistake from the beginning. Dotnet store uses csproj as manifest, generating store items for package references in it without ever building or including csproj output. We have to have manifest as a separate csproj from hosting startup.

I'm going to fix things up.

**Comment by VictorioBerra** [comment]
I came here by googling "Azure IHostingStartup" because I had a similar (maybe the same?) question. I am just now ramping up on all the IHostingStartup but you never see Azure mentioned a single time in this whole page https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.1&tabs=windows#runtime-store

@guardrex is there a way we could get some additional information on there? How would someone create their own little [StartupDiagnostics](https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/platform-specific-configuration/samples/2.x/StartupDiagnostics)  "app enhancement" project and share it to a variety of Azure Web Services hosted apps?

**Comment by guardrex** [comment]
I think ur asking about an approach that doesn't require a NuGet package ... I think you're ultimately asking about how to do it without a compile-time reference.

If so, the answer AFAIK would be that you would need to distribute an installer to get the hosting startup installed into the runtime store on each machine where the app will run.

Now .... let's ask a *real engineer* lol ... @pakrym Thoughts? ... and whatever the case may be, what should we cover (if anything) in the topic on this point?

**Comment by VictorioBerra** [comment]
@guardrex I didn't know I could run an installer on Azure App Services like that. I always figured it was more of a PaaS option unless you did a Azure App Services Container deployment. Or maybe i am missing some feature of Kudu? Ill wait for Pavel's reply.

**Comment by pakrym** [comment]
Runtime store and additional deps that we produce are part of site extension (https://azure.microsoft.com/en-us/blog/azure-web-sites-extensions/ and https://www.nuget.org/packages/Microsoft.AspNetCore.AzureAppServices.SiteExtension/). You can download and unpack it to see some implementation details. 

There are docs on how to package site extensions [here](https://azure.microsoft.com/en-us/blog/writing-a-site-extension-for-azure-websites/)

**Comment by guardrex** [comment]
**_Ah! Very good!_** I'll look that over and enhance the topic from there.

**Comment by guardrex** [comment]
> found odd

I'll look at that when I get to the updates. In the non-Azure case (the topic today), I think it's ok to rely upon PS. Apparently, adding the site extension to an app adds the env vars. In the non-Azure case, there's no similar mechanism to set them, thus PS is the suggested approach.

WRT the site extensions, I've only used the preview runtime extensions. It will be interesting (and hopefully *fun*) to build one out for the topic sample and topic update. I hope to get to this fairly soon ... this sprint, if possible.

**Comment by guardrex** [comment]
@pakrym WRT building a site extension for a hosting startup, should `dotnet pack` work? I tried a vanilla `dotnet pack` approach, but that didn't go well when I tried to upload the package. The Site Extensions website says either ...

> Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.

> A manifest was not found at the root of the package.

I tried with ...

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <Target Name="PackTaskDependencies" BeforeTargets="GenerateNuspec">
    <ItemGroup>
      <_PackageFiles Include=".\bin\Release\netcoreapp2.0\StartupDiagnosticsSiteExtension.deps.json">
        <PackagePath>lib\netstandard2.0</PackagePath>
        <Visible>true</Visible>
        <BuildAction>Content</BuildAction>
      </_PackageFiles>
    </ItemGroup>
  </Target>

  <PropertyGroup>
    <Authors>ASP.NET Core Docs</Authors>
    <ContentTargetFolders>content</ContentTargetFolders>
    <Description>ASP.NET Core lightup startup diagnostic integration with Azure App Service.</Description>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <IncludeSource>false</IncludeSource>
    <IsPackable>true</IsPackable>
    <LicenseUrl>https://raw.githubusercontent.com/aspnet/Home/2.0.0/LICENSE.txt</LicenseUrl>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <PackageIconUrl>https://go.microsoft.com/fwlink/?LinkID=288859</PackageIconUrl>
    <PackageId>StartupDiagnostics</PackageId>
    <PackageTags>aspnetcore;StartupDiagnostics</PackageTags>
    <PackageType>AzureSiteExtension</PackageType>
    <ProjectUrl>https://docs.microsoft.com/aspnet/core/fundamentals/host/platform-specific-configuration</ProjectUrl>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <SharedFrameworkVersion>2.2.0</SharedFrameworkVersion>
    <TargetFrameworks>netcoreapp2.0</TargetFrameworks>
    <Title>Startup Diagnostics</Title>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="$(SharedFrameworkVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="$(SharedFrameworkVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(SharedFrameworkVersion)" />
  </ItemGroup>

</Project>
```

... and it came up with (and btw -- it never honors the `<RequireLicenseAcceptance>` prop in the project file) ...

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>StartupDiagnostics</id>
    <version>1.0.0</version>
    <title>Startup Diagnostics</title>
    <authors>ASP.NET Core Docs</authors>
    <owners>ASP.NET Core Docs</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <iconUrl>https://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <description>ASP.NET Core lightup startup diagnostic integration with Azure App Service.</description>
    <tags>aspnetcore StartupDiagnostics</tags>
    <packageTypes>
      <packageType name="AzureSiteExtension" />
    </packageTypes>
    <dependencies>
      <group targetFramework=".NETCoreApp2.0">
        <dependency id="Microsoft.AspNetCore.Hosting" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.AspNetCore.Hosting.Abstractions" version="2.2.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.DependencyInjection" version="2.2.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

... and *lib/netstandard2.0* contains the *StartupDiagnosticsSiteExtension.deps.json* file. I did see `<TargetsForTfmSpecificBuildOutput>` described as a newer way to handle the `PackTaskDependencies` target, but let's hold off on that for a sec.

**Comment by Rick-Anderson** [comment]
Thank you for contacting us. Due to a lack of activity on this discussion issue we're closing it in an effort to keep our backlog manageable. If you believe there is a concern which hasn't been addressed, please file a new issue.
