### ISSUE TITLE
Multiple validation with CookieAuthenticationDefaults and OAuthValidationDefaults

### ISSUE THREAD

**Issue by vovikdrg** [dotnet/AspNetCore.Docs#9484]
**Help us make content visible**

asp net core cookie and bearer token authentication
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.1&tabs=aspnetcore2x

**Describe the new topic**

Many applications are using cookie and JWT auth.

So would be nice to see 

**Use multiple authentication schemes: Cookie and OpenId**
So this would describe which packages to install and then some code samples 

```
  services.AddAuthentication(options =>
                {
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = OAuthValidationDefaults.AuthenticationScheme;
                })
                .AddExternalAuthProviders(Configuration)
                .AddFlymarkOpenIdConnectServer()
                .AddCookie(cfg =>
                {
                    cfg.LoginPath = "/identity/account/login";
                    cfg.SlidingExpiration = true;
                    cfg.Events.OnRedirectToLogin = context =>
                    {
                        if (context.HttpContext.Request.Path.Value.Contains("/api")) context.Response.StatusCode = 401;

                        return Task.CompletedTask;
                    };
                })
                .AddOAuthValidation(OAuthValidationDefaults.AuthenticationScheme);

```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
