### ISSUE TITLE
Docs for new AccessDeniedPath feature

### ISSUE THREAD

**Issue by Tratcher** [dotnet/AspNetCore.Docs#9603]
Feature PR: https://github.com/aspnet/Security/pull/1887

Scenario:
When using a remote authentication provider (Facebook, OIDC, etc..) if the user hits "Denied" or "Cancel" then you get redirected back to the application with a specific error.

Feature:
A new AccessDeniedPath option was introduced that when set will cause this class of errors to be automatically redirected to the given page. The suggested contents for this page are why-did-you-cancel-me-I-needed-that-would-you-like-to-try-again-please.

Docs that should mention this:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/other-logins?view=aspnetcore-2.1
https://github.com/aspnet/Docs/issues/7025

**Comment by Rick-Anderson** [comment]
@kevinchalet 
I tried testing this with the following code:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
        .AddEntityFrameworkStores<ApplicationDbContext>();
    services.AddRazorPages();

    services.AddAuthentication()
.AddGoogle(options =>
{
    IConfigurationSection googleAuthNSection =
        Configuration.GetSection("Authentication:Google");

    options.ClientId = googleAuthNSection["ClientId"];
    options.ClientSecret = googleAuthNSection["ClientSecret"];
    options.AccessDeniedPath = "/Privacy";
});
}
```
But Google doesn't give me an option to cancel at any point.

When I use the wrong redirect URI, I get a google error:

Error: redirect_uri_mismatch

The redirect URI in the request, https://localhost:44337/signin-google, does not match the ones authorized for the OAuth client.

Can you suggest how I document this?

**Comment by Tratcher** [comment]
You're right, I didn't see an easy option for this on Google. On Facebook, if I wasn't signed into Facebook then I'd end up at the login page. The last option on that page is "Not Now", which would send you back to the app with an access denied error.

If I was signed into Facebook but had not yet authorized the app, then I'd get a prompt to continue or cancel. You can test this scenario by making a new app or by revoking account permissions for the old app.

**Comment by Rick-Anderson** [comment]
Notes:
As stated above, Google doesn't provide a cancel.
Twitter has a built in one:

![image](https://user-images.githubusercontent.com/3605364/78311235-ee28a880-74eb-11ea-99d2-e9fa3433cf08.png)
