### ISSUE TITLE
SignalR:  Accessing the hub routing table

### ISSUE THREAD

**Issue by zanate4019** [dotnet/AspNetCore.Docs#9700]
Is there a way to access the hub routing table after it's been configured?

**Comment by Rick-Anderson** [comment]
@zanate4019 	what's the scenario where you need to do so?

**Comment by zanate4019** [comment]
The main reason is because I'd like to drop the urls in javascript variables in my mvc template using razor.  This will allow my front-end SPA to always know the address of my SignalR endpoints even if the routing changes and only have to configure it in one place (startup.cs).

Here's some psuedo code for what I'm talking about:
`    <script>
        var bwf = {
            userUrl: '@Url.Action("Index", "User", null)',
            pagingUrl: '@Url.Action("Index", "Paging", null)',
            dataminingUrl: '@Url.Action("Index", "Datamining", null)',
            reportingUrl: '@Url.Action("Index", "Reporting", null)',
            examUpdateUrl: '@Url.Hub.Action("ExamHub")',            // Url to the Exam Hub endpoint
            userUpdateUrl: '@Url.Hub.Action("UserHub")',            // Url to the User Hub endpoint
            workItemUpdateUrl: '@Url.Hub.Action("WorkItemHub")',    // Url to the Work Item endpoint
        };
    </script>`

**Comment by Rick-Anderson** [comment]
@bradygaster 	@BrennanConroy 	please respond

**Comment by BrennanConroy** [comment]
Couldn't you do this by making a variable for the route and using it in startup.cs and the razor file?

**Comment by bradygaster** [comment]
question to @glennc - would [endpoint routing(https://blogs.msdn.microsoft.com/webdev/2018/08/27/asp-net-core-2-2-0-preview1-endpoint-routing/) support the Hub URLs? I ask as, maybe it's possible that could help in this scenario. If users could use endpoint routing to generate the correct URL as a string, it could then be pumped into the HTML as a variable or model property.

**Comment by zanate4019** [comment]
@BrennanConroy I could, but it wouldn't really buy anything.  I need the absolute Urls because I'm consuming it with Angular and the relative Uri's get mis-interpreted.  There are number of factors that go into format of the Url and would like to it be dynamic as possible so I'm only configuring it in one place.

**Comment by bradygaster** [comment]
Closing this as it appeared to be a discussion on the API rather than on the doc. @BrennanConroy - open to your opinion if you feel documenting this would augment the documentation.
