### ISSUE TITLE
Update Authenticate users with WS-Federation 

### ISSUE THREAD

**Issue by fabich** [dotnet/AspNetCore.Docs#9706]
This article is no longer up to date.

@Rick-Anderson 	EDIT:  3.1K  to 5K PV, 75% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
We'll try to get this updated. 
@scottaddie 	- this is an advanced topic. I think we should remove all the screen shots so it's easier to keep up to date.

**Comment by Rick-Anderson** [comment]
Moved to master issue: WS-Federation #16508

**Comment by Rick-Anderson** [comment]
@Rick-Anderson ,

Hi, thanks for following up.

I was referring mostly to this introduction:

> This tutorial demonstrates how to enable users to sign in with a WS-Federation authentication provider like Active Directory Federation Services (ADFS) or Azure Active Directory (AAD). It uses the ASP.NET Core 2.0 sample app described in Facebook, Google, and external provider authentication.

> For ASP.NET Core 2.0 apps, WS-Federation support is provided by Microsoft.AspNetCore.Authentication.WsFederation. This component is ported from Microsoft.Owin.Security.WsFederation and shares many of that component's mechanics. However, the components differ in a couple of important ways.

If I'm mistaken, then my apologies.

I have a large website using ws-federation on .net 4.6.1 right now and I'm looking into upgrade paths to asp core 3.1. I can't find any actual end-to-end usage or implementation of it in any Microsoft sample. And most other usage is using owin still.

If you happen to know of something I might be missing that would be greatly appreciated! Thanks.
