### ISSUE TITLE
Create a PFX cert for Kestrel from .crt+.key files

### ISSUE THREAD

**Issue by guardrex** [dotnet/AspNetCore.Docs#9756]
Surface how to create a PFX cert for Kestrel from a certificate file (*.crt*) and private key file (*.key*) in code at runtime.

See: https://github.com/aspnet/KestrelHttpServer/issues/3017#issuecomment-432095118

cc: @Praveen-Rai

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by ogg130** [comment]
Been a while since you asked this but I just conquered this using docker:

1) Make dockerfile run a script called configure.sh instead of using your dotnetcore app as an entrypoint. 

2) Modify the following script as needed. You may not need passin/passout, that is used if you password encrypted your CSR/KEY:

```
echo "Convering text encoded cert and key files into binary PFX certificate..."
openssl pkcs12 -export -in <CRTFILE> -inkey <KEYFILE> -out <PFXNAME>.pfx -certfile CAcert -passin pass:<PEMPASSPHRASE> -passout file:<EXPORTPASSWORD>

echo "Running the dotnetcore application..."
dotnet <PUBLISHEDDLL>.dll --environment=Production --server.urls http://*:80
```
3) Profit using your new handy PFX cert.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider. We'll also reconsider this issue in the next doc update. You might try https://stackoverflow.com/
