### ISSUE TITLE
Documentation Wrong for Asp.Net Core 2.2 Angular Template

### ISSUE THREAD

**Issue by mbeckenbach** [dotnet/AspNetCore.Docs#9882]
As the ASP.Net Core 2.2 Template which ships with VS 2019 Preview has finally been upgraded to use angular 6, the documentation on ssr is wrong. Angular 6 does not use the angular-cli.json. There is a new configuration file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by blogcraft** [comment]
Any idea how to make SSR work with 2.2? The docs are not useful.

**Comment by hartov** [comment]
So, first of all this guide is wrong. some steps are incorrect fo .net core 2.2 template. But full publishing project contain folder node_modules! As for me this implementation is not good idea. I think if you are using Angular SSR and .net core API you should to separate this two projects and add CORS to .net. So you have node.js with angular SSR witch call your .net core API by CORS.

**Comment by joshberry** [comment]
Checkout this example: https://github.com/joshberry/dotnetcore-angular-ssr.

I started fresh with asp.net 2.2 and angular 7.2 and is was not too difficult to setup the hosting and server side rendering. It doesn't require node_modules to be deployed to the server either. Let me know if you see any issue with or shortcomings to this setup.

**Comment by jonas-thuvesson-winberg** [comment]
@joshberry Thank you! You're the best!

**Comment by blogcraft** [comment]
@joshberry Thanks for the example, I get this error:

AngularCliBuilder: Error: Unknown option: '--watch'

Any ideas? Thanks!

Using: Net Core 3.0-preview (I know the example is in 2.2 but i'm doing some testing)
Angular: 7.3

**Comment by agiletuan** [comment]
app.UseSpa(spa =>
            {
                // To learn more about options for serving an Angular SPA from ASP.NET Core,
                // see https://go.microsoft.com/fwlink/?linkid=864501

                spa.Options.SourcePath = "ClientApp";
                spa.UseSpaPrerendering(options =>
                {
                    options.SupplyData = (context, data) =>
                    {
                        // Creates a new value called isHttpsRequest that's passed to TypeScript code
                        data["isHttpsRequest"] = context.Request.IsHttps;
                    };
                });

                if (env.IsDevelopment())
                {
                    spa.UseAngularCliServer(npmScript: "start");
                }
            });

**Comment by agiletuan** [comment]
Hic, how to edit my comment on this docs?!!

**Comment by stephenlautier** [comment]
Now using .netcore 3.0 it seems that SSR is not a thing in aspnet? or am i wrong?

![image](https://user-images.githubusercontent.com/3908723/66426232-b1369a00-ea11-11e9-9920-fa0337a06c7f.png)

**Comment by stephenlautier** [comment]
@blogcraft for anyone who needs I had just updated my sample https://github.com/sketch7/dotnet-ngx-sample

- using **angular 8.2.9**
- netcore 3/also [netcore 2.2](https://github.com/sketch7/dotnet-ngx-sample/tree/ng8-netcore2.2)

Unfortunately, I haven't seen @joshberry example before now - but its very similar to his

NOTE: theres a bit of a hack inorder for it to work, as latest angular doesnt work so I had to copy `AngularCliBuilder` and modify

**Comment by Rick-Anderson** [comment]
2.2 is out of support.
