### ISSUE TITLE
Example of generating link of Web API using LinkGenerator

### ISSUE THREAD

**Issue by NimeshDhruve** [dotnet/AspNetCore.Docs#9886]
Can you please add an example which shows how to get URL like "/api/todo" using LinkGenerator class? My get WebApi method takes bunch of arguments and with .Net Core 2.1 I was able to generate the URL using following code:

```
Url.RouteUrl("SomeRouteName", new { controller = 
"SomeWebAPIController", arg1 = arg1value, arg2 = arg2value, arg2 = arg3value })
```
I was setting this URL as action to "form" tag which was using AJAX later submitted.

This code stopped working after changing compatibility version to 2.2 (i.e. `SetCompatibilityVersion(CompatibilityVersion.Version_2_2))`, I understand I can go back to old routing system by setting `EnableEndpointRouting = false`, however I would love to use recent routing improvements and for life of me I couldn't figure out how to generate the URL.

@Rick-Anderson edit: Need useful/realist code sample generating URLs outside of Razor or in some Middleware. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rynowak** [comment]
@Rick-Anderson - there's a brief example here - at the bottom: https://www.hanselman.com/blog/ASPNETCore22ParameterTransformersForCleanURLGenerationAndSlugsInRazorPagesOrMVC.aspx

@nimeshdhruve - could you please open an issue for this on aspnet/AspNetCore - I want to understand why that doesn't work.

**Comment by nimeshdhruve** [comment]
I am wondering in that case would you recommend to add Scott's blog URL in the page? I am still of the opinion that it would be better if the document has direct example. 

I am trying to create a small example where I can reproduce this issue and after that I will add this as an issue in aspnet/AspNetCore

**Comment by nimeshdhruve** [comment]
I have created a repo [here](https://github.com/nimeshdhruve/WebAPIRoutingDemo) where you can see that I have reproduced the issue , I haven't logged any issue in AspNetCore in past so I am little hesitant to log this there before you can verify. 

The repo is very simple with one page and one webapi call, this is how the page looks like:

![image](https://user-images.githubusercontent.com/7783989/49693045-13dfb080-fb37-11e8-8a9c-8e5049814b97.png)

**Comment by Rick-Anderson** [comment]
@rynowak 	see the repro at https://github.com/nimeshdhruve/WebAPIRoutingDemo

**Comment by mkArtakMSFT** [comment]
@Rick-Anderson seems like there is no more action pending here. Should this be closed?
